### PR TITLE
Fix system tags conflict situations

### PR DESCRIPTION
**Pull request by PVince81**
Does not disrupt the UX whenever a tag or association was created
concurrently. The input field will adjust itself as if the tag was
already there in the first place.

Reported here: https://github.com/owncloud/core/pull/20847#issuecomment-173170615

Please review @nickvergessen @rullzer @blizzz @icewind1991 

There are multiple types of conflicts due to concurrency, in all cases open two browsers one for user1 and one for user2, and open the dropdown once to make sure the list was fetched:
1) user1 creates tag "conflict1" on file "test", user2 creates tag "conflict1" on file "test" => user2 sees "conflict1" properly added to the dropdown and input selection
2) user1 creates tag "conflict2" on file "test", user2 creates tag "conflict2" on file "another test" => user2 sees "conflict2" properly added to the dropdown and input selection
3) user1 assigns tag "conflict1" on file "test2", user2 also assigns tag "conflict1" on file "test2" => user2 sees that still properly assigned

In most cases the goal is that the UI doesn't complain about the conflict and just carries on as if there was no conflict in the first place, and have a consistent state.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and fixes the issue :+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by LukasReschke** [comment]
(Too late… :speak_no_evil:)

**Pull request merged**
