### PR TITLE
Provide IAppContainer as dependency injection

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @BernhardPosselt @nickvergessen @butonic 

This is useful if you want to query an object dynamically from your apps container.

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Can you outline the usecase? AFAIK we had a PR like this once and it was closed.

**Comment by MorrisJobke** [comment]
I have an app that has a list of objects that implement the same interface. I store the name of the classes of this objects in the database and want to construct them later. To avoid the ugly `fixDI`method that does all the dependency resolving, I want to use the build in functionality with the type hinting. This is easily possible to do with `$c->query($className)` and I get the complete object.

**Comment by BernhardPosselt** [comment]
Ok, in order to dynamically resolve this each time something is executed, there is basically no way to do this without the container. So basically injecting the container is ok under the following reasons:
* The container is injected into a class that abstracts its access away
* The class returns one or more instances of a known type

**BAD**:
```php
class Service {
    private $container;
    /* create any instance */
    public createInstance($key) return $this->container->query($key);
}
```

**GOOD**
```php
class ConfigLocator {
    private $container;
     /* Find and read all current config files */
    public getCurrentConfigs() {
        return array_map(function ($configFile) {
            $config = $this->container->query(OCA\MyApp\Config::class);
            $config->read($configFile);
            return $config;
        }, scandir('configs/'));
    }
}
```

:+1:

**Comment by MorrisJobke** [comment]
@LukasReschke @nickvergessen Mind to review?

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
