### PR TITLE
Jenkins add verbosity to upgrade

### PR DESCRIPTION
**Pull request by MorrisJobke**
Jenkins for #17088

### CODE REVIEW

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

just work this time...

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
I'm getting the same oracle initialization issue locally ... will investigate

**Comment by DeepDiver1975** [comment]
increasing the wait time solved it :sob:

**Pull request closed without merging**
