### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by hefee** [comment]
Not done completly:
$ grep -r 'ownCloud.*Inc' src
src/libsync/theme.cpp:    re += tr("<p>Copyright ownCloud, Incorporated</p>");
src/libsync/owncloudtheme.cpp:               "<p>Copyright ownCloud, Inc.</p>"

**Comment by DeepDiver1975** [comment]
please report in client repo - thx @hefee

**Pull request merged**
