### PR TITLE
Remove background job if the server accepted to ask for the shared secret

### PR DESCRIPTION
**Pull request by schiessle**
If we don't remove it the server will later ask the remote server to ask for the shared secret which will result in a error log message on the remote server and in some circumstances maybe even to a failure.

cc @MorrisJobke please test if this changes anything with respect to https://github.com/owncloud/core/issues/21929. Even if it still fails please check the error message if something changed there.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
The error messages are now gone, because they were related to the second run of the background job on the other server. But the initial problem still exists but seems to be unrelated to the error message.

:+1: for this nevertheless

**Comment by schiesbn** [comment]
Yes, didn't expect that it fix something. But it keeps the log clean so that it is easier to focus on the real issue if something goes wrong.

**Comment by MorrisJobke** [comment]
@LukasReschke @nickvergessen please review

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
