### PR TITLE
Use setUp in RouterTest instead of constructor

### PR DESCRIPTION
**Pull request by PVince81**
For https://github.com/owncloud/core/pull/31939#discussion_r203268935

@DeepDiver1975 please review as you pointed this out

I've already cherry-picked this onto the stable10 PR https://github.com/owncloud/core/pull/31939

### CODE REVIEW

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
This got 
```
In SuiteController.php line 67:
                                                                           
  `apiSharing-v1` suite is not found or has not been properly registered.  
```
That was renamed to just ``apiSharing`` a while ago. I am surprised that this PR branch is old. But maybe it started life from an older ``master``

**Comment by phil-davis** [comment]
Now:
```
fatal: unable to access 'https://github.com/owncloud/core.git/': Could not resolve host: github.com
exit status 128
```
I luv CI :(

**Comment by PVince81** [comment]
all green. @DeepDiver1975 happy with my change from `__construct` to `setUp` ?

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
