### PR TITLE
[stable8.1] [user mgnt] fix delete user feedback on failure

### LINKED ISSUE #18099: JS TypeError when deleting user
You get a JS error after having deleted a user
`TypeError: result is undefined deleteHandler.js:197:0`

Not sure who deals with this. @PVince81 ?

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #18114 - fixes #18099 in stable8.1
Approval https://github.com/owncloud/core/pull/18114#issuecomment-134566309

I tested it and it works.

@LukasReschke @oparoz @PVince81 @blizzz Please review

### CODE REVIEW

**Comment by blizzz** [comment]
@MorrisJobke when I attempt do delete an LDAP user, i will get the error message twice. And only after the second time, the user entry is back in the list.

**Comment by MorrisJobke** [comment]
> @MorrisJobke when I attempt do delete an LDAP user, i will get the error message twice. And only after the second time, the user entry is back in the list.

But it works for me in master?

**Comment by blizzz** [comment]
> But it works for me in master?

No, but the (visible) messages are different:

1. Go to Users page.

2. Attempt to delete an LDAP User, here Zombie15, by clicking on the trash icon.

y a a y 4

So far so good.

Network Log for this step:

y a a y 4


3. Attempt to delete another LDAP User, here Zombie16, by clicking on the trash icon.

y a a y 4

Repeated Message! And a little bit later:

y a a y 4

Click messages away.

Network Log for this step:

y a a y 4


4. Attempt to delete another LDAP User, here Zombie17, by clicking on the trash icon:

y a a y 4

Failed to delete Zombie16!

y a a y 4

Now message about Zombie17.

Network Log for this step:

y a a y 4


5. Reload the page by pressing F5:

y a a y 4

Is visible before the reloading is completed.

Also here the last delete operation is retried:

y a a y 4

That's now all against master, but the same symptoms i see on the backport.

**Comment by MorrisJobke** [comment]
I will kill this backport until the issue is fixed on master: https://github.com/owncloud/core/issues/20254

**Pull request closed without merging**
