### PR TITLE
Remove travis since drone is used instead

### PR DESCRIPTION
**Pull request by codisart**
## Motivation and Context

Reduce technical debt

## How Has This Been Tested?

Travis can not be run on this branch

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
We still want the travis YML because we still want to be able to enable it to run webUI acceptance tests on Microsoft browsers (IE11 and Edge) that need a service like SauceLabs to run. That is currently configured in the Travis YML in a way that should be easy enough to trigger.

In Phoenix we have started running IE11 acceptance tests from drone connecting to SauceLabs. If we did similar here in core, then the Travis YML could be deleted.

But we could immediately remove any of those other "supporting" scripts that are not called by anything in the UI acceptance tests Travis workflow.

**Comment by phil-davis** [comment]
These can be removed:
`start_ui_tests.sh` 

If `.travis.yml` is cleaned up to remove reference to `TEST_DAV` then `changed_app.sh`  can be removed.

`custom.ini` looks like it might no longer be useful (it is mentioned in `before_install.sh` )

This needs a bit of digging around to see exactly what is still needed to run acceptance tests, and what is old.

@codisart do you want to progress this?

**Comment by codisart** [comment]
Hello @phil-davis, 

I will see what I can do.

**Comment by codisart** [comment]
hello @phil-davis, 

Could you explain to me what is "dav" ? and why should the travis tests would not pass the app when it was changed ?

**Comment by phil-davis** [comment]
> hello @phil-davis,
> 
> Could you explain to me what is "dav" ? and why should the travis tests would not pass the app when it was changed ?

dav is "distributed authoring and versioning" - e.g. read about webDAV https://en.wikipedia.org/wiki/WebDAV

For ownCloud core Travis we only need to be able to run webUI acceptance tests (and choose any of the browsers, but most importantly IE11 or Edge). Everything else runs in drone CI nowadays, so can be cleaned up from Travis.

**Comment by JammingBen** [comment]
@phil-davis Is travis still needed? What about https://github.com/owncloud/core/pull/36578?

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
It has been a long time since we actually used Travis. And Travis has changed a lot of open-source rules. So I very much doubt that we would use Travis again. We might use Sauce-Labs for running webUI  tests on the Edge browser, but that can be done directly from drone if we do it.

I rebased this PR, resolved conflicts and added another commit to remove other references to Travis. It is ready for merge when drone CI passes.

**Pull request merged**
