### PR TITLE
keyid is autoincrement and as an implicit result PK and has an index - n...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
...o need to add another key - refs #14827

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I would feel better if there is the primary setting on the column. Maybe this "implicit" logic changes and the index is missing.

Just my 2ct

**Comment by DeepDiver1975** [comment]
> I would feel better if there is the primary setting on the column. Maybe this "implicit" logic changes and the index is missing.
> 
> Just my 2ct

hmmm .... let me double check the logic ...

**Comment by DeepDiver1975** [comment]
:-1: for now

**Comment by DeepDiver1975** [comment]
we need to find th root cause of  #14827

**Pull request closed without merging**
