### PR TITLE
[3rdparty] Bump doctrine/dbal

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/256

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and still works :+1:

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by DeepDiver1975** [comment]
> 3rdparty merged

@rullzer mind rebasing? THX

**Comment by rullzer** [comment]
@DeepDiver1975 done :)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 done :)

thx

**Pull request merged**
