### PR TITLE
UI tests uploading chunked files & more integration tests for chunking

### PR DESCRIPTION
**Pull request by individual-it**
## Description
1. UI tests to test the chunked upload
2. Some integration tests for chunking upload to test difficult characters in the filename

## Related Issue
owncloud/QA#437

## Motivation and Context
test more upload cases
some tests are skipped because of #29599

## How Has This Been Tested?
run tests locally, travis and jenkins will run full set of tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase was successful!

**Review by phil-davis — APPROVED** [review]

**Comment by individual-it** [comment]
backport in #29626

**Pull request merged**
