### PR TITLE
Dont verify shared mount point on mount

### PR DESCRIPTION
**Pull request by icewind1991**
From what I can tell a share is unshared from self when you delete it's parent folder.

Verifying the mount point is the most expensive part of mounting shares

cc @schiesbn @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> From what I can tell a share is unshared from self when you delete it's parent folder.

cc @owncloud/designers @schiesbn

**Comment by schiesbn** [comment]
:-1: it is much more expensive if you need to calculate a unique target for each user on a group share if a file is shared with a large group. This was moved to the mount operation by purpose. Also now that a share can be located everywhere we need to check for collisions during mount, e.g. if the admin created a new system wide mount point which has the same name and location as a share for some users.

**Comment by icewind1991** [comment]
The problem is that it's currently done on every page load, even if it would be more expensive to do when creating the share it's still way better to do an expensive operation once instead of taking up time every single request

**Comment by schiesbn** [comment]
On share it really hurts, because you also need to set up every users filesystem, mount all mount points, etc. This can take really really long until a share is created. If you ask me if we can optimize it? Sure. Maybe only do it once when the share gets mounted for the first time with a flag in the share table which indicate that it was already checked. Operation like creating a system wide mount point could reset the flag so that it gets checked again for every user. Just thinking.... But removing it completely is not a solution.

**Comment by schiesbn** [comment]
btw. in the future user might also need to accept the shares before they become visible. So we can do the check at this point.

**Comment by PVince81** [comment]
This PR doesn't seem to provide an alternative for generating the unique target ?

Note that in the past we considered several moments where it could be done but many would risk running into race conditions. Now that we have locking, it might be an idea to reconsider such alternatives.

**Comment by PVince81** [comment]
Related https://github.com/owncloud/core/issues/14795

**Comment by schiesbn** [comment]
> Related #14795

Actually that's a good example why it is as it is. #14795 shouldn't be a issue any longer because now we verify the mount point when they are needed (during mount)

**Comment by MorrisJobke** [comment]
@schiesbn @icewind1991 @PVince81 This looks like we should better close this PR, right?

**Comment by rullzer** [comment]
While I agree that we need to think of solutions. I have to agree with @schiesbn that doing it at share time is simply not an option. If you share with a group with N members and N becomes huge this simply doesn't scale.

Closing due to inactivity and the Christmas cleanup ;)

**Pull request closed without merging**
