### PR TITLE
Use URLGenerator instread of OC_Helper for linkToDocs

### PR DESCRIPTION
**Pull request by rullzer**
Trivial fix to move the core apps to OCP calls.
Solves a part of #4774

### CODE REVIEW

**Comment by rullzer** [comment]
CC: @DeepDiver1975 @Xenopathic @LukasReschke @PVince81

**Comment by karlitschek** [comment]
:+1:

**Comment by Xenopathic** [comment]
Oh piss off Jenkins

@owncloud-bot retest this please

:+1: for the actual change

**Comment by rullzer** [comment]
@owncloud-bot retest this please

**Pull request merged**
