### PR TITLE
Issue 15804 occ user delete exception

### LINKED ISSUE #15804: php fatal error trying to delete a LDAP user
### Steps to reproduce
1. Setup a LDAP server and configure it in OC
2. Login in OC with any of the LDAP users. This will create the user data folder in OC (you can upload some files)
3. Disconnect the LDAP server (or set the configuration inactive in the LDAP wizard)
4. Run `./occ user:delete <userID>` (you can check the userID in the data folder)

### Expected behaviour
The user data is deleted from OC

### Actual behaviour
A php fatal error is shown

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.1 alpha 1

**Updated from an older ownCloud or fresh install:** fresh install

#### console output
```
PHP Fatal error:  Call to a member function delete() on a non-object in /home/jvillafanez/src/owncloud/owncloud2/core/command/user/delete.php on line 54

Fatal error: Call to a member function delete() on a non-object in /home/jvillafanez/src/owncloud/owncloud2/core/command/user/delete.php on line 54
```

### Notes
The same error is thrown trying to delete a wrong user (the user is missing)

After checking that the user is missing and added to the "remnants list" (using ldap:check-user), the user data can be deleted correctly

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #15804
- [x] Added unit tests for user:delete
- [x] Added unit tests for user:lastseen
- [x] Use Interfaces for type hints
- [x] Use DI for the UserManager for better testing
- [x] Unified the output of the commands (use of highlight and strings)

@jvillafanez @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I can't reproduce #15804 but the code looks good and still works :+1:

**Comment by nickvergessen** [comment]
@MorrisJobke just run `./occ user:delete DOESNOTEXIST` ? 
```
nickv@nickv-think ~/ownCloud/master/core {master*}:
$ ./occ user:delete DOESNOTEXIST
PHP Fatal error:  Call to a member function delete() on a non-object in /home/nickv/ownCloud/master/core/core/command/user/delete.php on line 54
PHP Stack trace:
PHP   1. {main}() /home/nickv/ownCloud/master/core/occ:0
PHP   2. require_once() /home/nickv/ownCloud/master/core/occ:11
PHP   3. OC\Console\Application->run() /home/nickv/ownCloud/master/core/console.php:59
PHP   4. Symfony\Component\Console\Application->run() /home/nickv/ownCloud/master/core/lib/private/console/application.php:75
PHP   5. Symfony\Component\Console\Application->doRun() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRunCommand() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Application.php:195
PHP   7. Symfony\Component\Console\Command\Command->run() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Application.php:874
PHP   8. OC\Core\Command\User\Delete->execute() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php:253

Fatal error: Call to a member function delete() on a non-object in /home/nickv/ownCloud/master/core/core/command/user/delete.php on line 54

Call Stack:
    0.0001     227392   1. {main}() /home/nickv/ownCloud/master/core/occ:0
    0.0002     238808   2. require_once('/home/nickv/ownCloud/master/core/console.php') /home/nickv/ownCloud/master/core/occ:11
    0.0785   12382056   3. OC\Console\Application->run() /home/nickv/ownCloud/master/core/console.php:59
    0.0785   12382352   4. Symfony\Component\Console\Application->run() /home/nickv/ownCloud/master/core/lib/private/console/application.php:75
    0.0786   12388096   5. Symfony\Component\Console\Application->doRun() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Application.php:126
    0.0787   12388984   6. Symfony\Component\Console\Application->doRunCommand() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Application.php:195
    0.0787   12389456   7. Symfony\Component\Console\Command\Command->run() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Application.php:874
    0.0789   12393232   8. OC\Core\Command\User\Delete->execute() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php:253

**Comment by MorrisJobke** [comment]
> @MorrisJobke just run ./occ user:delete DOESNOTEXIST ?

m( I disabled the LDAP server and tried with a LDAP account. But this is also working now smoothly. Thanks

**Comment by blizzz** [comment]
Code looks good and works :+1:

**Pull request merged**
