### PR TITLE
Stable8.1 backport sharingcheckmiddleware fixes

### PR DESCRIPTION
**Pull request by rullzer**
As reqeusted in https://github.com/owncloud/core/pull/19487#issuecomment-145797404

Basically backports 3 PR's that solve issues we had in the sharing middleware. The request was only for the last PR but without the whole bunch things would get kind of messy. And since all 3 PR's are pretty clean this seemed like the best solution and improved the sharing middleware for 8.1.

In order:
1. Throw error if link sharing is disabled and a link share is visited: https://github.com/owncloud/core/pull/19262
2. Show not found page (via not found exception): https://github.com/owncloud/core/pull/19470
3. Split files sharing middleware to allow federated sharing even when link sharing is disabled: https://github.com/owncloud/core/pull/19487

Of course the introduced tests are backported as well.

@karlitschek please confirm backport

@MorrisJobke @michaelstingl: please have a look and test.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
* [x] public link shares are not accessible anymore after deactivating sharing API in admin settings
* [x] federated cloud shares can be received if only the share API (first checkbox) and the two federated cloud sharing settings are active

:+1: from my side

@nickvergessen @LukasReschke Can you review this please?

**Comment by PVince81** [comment]
:+1:

But what's up with the OCS API integration tests ci ?

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Do the ocs api integration tests work on stable8.1?

**Comment by PVince81** [comment]
maybe @SergioBertolinSG knows ?

**Comment by PVince81** [comment]
Looking at https://github.com/owncloud/core/pull/19784 which contains changes unrelated to OCS also have it fail on 8.1, so the tests for OCS API probably don't work against 8.1.

**Comment by rullzer** [comment]
@MorrisJobke @PVince81 intergration tests stuff was only added in 8.2 so the files are missing here ;)

**Comment by PVince81** [comment]
Okay, then this is good to go

**Comment by rullzer** [comment]
@karlitschek can you approve this backport(s)?

**Comment by karlitschek** [comment]
yes. please backport

**Comment by SergioBertolinSG** [comment]
> But what's up with the OCS API integration tests ci ?

It is only prepared for master at the moment.

**Pull request merged**
