### PR TITLE
Use userFolder instead of rootFolder

### PR DESCRIPTION
**Pull request by micbar**
## Description
- Code  Improvements

## How Has This Been Tested?
- CI

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
Unit tests that use `samba` are broken because of the changes to `owncloudci/php` docker image.
Those tests were disabled in `master` branch so that we could keep working. See issue #36322 
This `release-10.3.1` branch comes from an earlier point, where the tests are enabled.
We need to disable the tests here to get CI green.

**Comment by DeepDiver1975** [comment]
Any commit we can cherry pick into this pr? Thx

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/pull/36374 should "make CI great again" in 10.3.1 branch.
Then we can rebase here.

**Comment by DeepDiver1975** [comment]
> #36374 should "make CI great again" in 10.3.1 branch.

Let's rebase this one now ....

**Comment by DeepDiver1975** [comment]
> Let's rebase this one now ....

done

**Pull request merged**
