### PR TITLE
Remove $CLASSPATH - this is no longer needed. Apps are using proper n…

### LINKED ISSUE #12573: Classes in apps/ should use OCA\ namespace
- Encryption uses OCA\Encryption instead of OCA\Files_Encryption: https://github.com/owncloud/core/pull/12568
- Sharing is hacking itself into all kind of namespace/OC_:

``` php
OC::$CLASSPATH['OC_Share_Backend_File'] = 'files_sharing/lib/share/file.php';
OC::$CLASSPATH['OC_Share_Backend_Folder'] = 'files_sharing/lib/share/folder.php';
OC::$CLASSPATH['OC\Files\Storage\Shared'] = 'files_sharing/lib/sharedstorage.php';
OC::$CLASSPATH['OC\Files\Cache\Shared_Cache'] = 'files_sharing/lib/cache.php';
OC::$CLASSPATH['OC\Files\Cache\Shared_Permissions'] = 'files_sharing/lib/permissions.php';
OC::$CLASSPATH['OC\Files\Cache\Shared_Updater'] = 'files_sharing/lib/updater.php';
OC::$CLASSPATH['OC\Files\Cache\Shared_Watcher'] = 'files_sharing/lib/watcher.php';
```
- Same issue with the externals:

``` php
OC::$CLASSPATH['OC\Files\Storage\StreamWrapper'] = 'files_external/lib/streamwrapper.php';
OC::$CLASSPATH['OC\Files\Storage\FTP'] = 'files_external/lib/ftp.php';
OC::$CLASSPATH['OC\Files\Storage\OwnCloud'] = 'files_external/lib/owncloud.php';
OC::$CLASSPATH['OC\Files\Storage\Google'] = 'files_external/lib/google.php';
OC::$CLASSPATH['OC\Files\Storage\Swift'] = 'files_external/lib/swift.php';
OC::$CLASSPATH['OC\Files\Storage\SMB'] = 'files_external/lib/smb.php';
OC::$CLASSPATH['OC\Files\Storage\SMB_OC'] = 'files_external/lib/smb_oc.php';
OC::$CLASSPATH['OC\Files\Storage\AmazonS3'] = 'files_external/lib/amazons3.php';
OC::$CLASSPATH['OC\Files\Storage\Dropbox'] = 'files_external/lib/dropbox.php';
OC::$CLASSPATH['OC\Files\Storage\SFTP'] = 'files_external/lib/sftp.php';
OC::$CLASSPATH['OC_Mount_Config'] = 'files_external/lib/config.php';
```

Now the question is, what happens if we try to rename the storage/cache backends: @icewind1991 

Also both use `OCA\Files\External` / `OCA\Files\Share` instead of `OCA\Files_External` / `OCA\Files_Sharing` for some classes, that should simply be renamed:

``` php
OC::$CLASSPATH['OCA\Files\Share\Api'] = 'files_sharing/lib/api.php';
OC::$CLASSPATH['OCA\Files\Share\Maintainer'] = 'files_sharing/lib/maintainer.php';
OC::$CLASSPATH['OCA\Files\Share\Proxy'] = 'files_sharing/lib/proxy.php';

OC::$CLASSPATH['OCA\Files\External\Api'] = 'files_external/lib/api.php';
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…amespaces today.

## Description
$CLASSPATH as  a very old concept to perform auto loading in ownCloud.

As of today all apps use a proper namespace e.g. OCA\Calendar\ to load classes living in the calendar app.

Furthermore composer is more and more used and has a far better autoloaded then ownCloud itself.

## Issues

closes https://github.com/owncloud/core/issues/12573

## Motivation and Context
Deprecate/remove old concepts 

## How Has This Been Tested?
- manually 
- unit tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
> manually

retested SMB storage and OC ext storage config ?

**Comment by DeepDiver1975** [comment]
> retested SMB storage and OC ext storage config ?
> Merge state

I made sure in debugger that the class is loaded and can be used - which is the case in app.php.
No further testing necessary from my pov

**Comment by DeepDiver1975** [comment]
Issues raised:
- https://github.com/owncloud/SMStorage/issues/5
- https://github.com/owncloud/apps/issues/2228
- https://github.com/owncloud/ownbrander/issues/815

**Review by PVince81 — APPROVED** [review]
:+1: thanks

**Comment by DeepDiver1975** [comment]
there seems to be something wrong with the phpunit test execution - AutoloadTest shall fail .....

**Comment by phil-davis** [comment]
Backport `stable10` #35755

**Pull request merged**
