### PR TITLE
[9.0] handle connection errors as storage not available in smb

### PR DESCRIPTION
**Pull request by icewind1991**
Backport #23300

cc @Xenopathic @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
Second reviewer please @jmaciasportela @Xenopathic @blizzz @DeepDiver1975

**Comment by PVince81** [comment]
@MorrisJobke ?

**Comment by PVince81** [comment]
steps are here https://github.com/owncloud/core/issues/22826#issue-138235727

**Comment by PVince81** [comment]
@owncloud/qa can you help testing ?

**Comment by PVince81** [comment]
or @blizzz ?

**Comment by PVince81** [comment]
Steps here https://github.com/owncloud/core/issues/22826
You might need to do `update oc_storages set last_checked=0` to accelerate availability check after restoring the SMB server.

**Comment by blizzz** [comment]
With stock stable9 I cannot reproduce the issue. I am getting a 503 and the available flag is set to 0. The next propfind (after setting last_checked to 0) also shows the contents and sets available flag again.

**Comment by blizzz** [comment]
At least it continues to work with this patch :smiley_cat:

**Comment by blizzz** [comment]
> Setup a SMB mount with custom credentials as "/smb". (make sure there are already files in there)

Whatever is meant with "custom credentials" I assumed the "Username and password" option

**Comment by SergioBertolinSG** [comment]
@blizzz GET http://docker.oc.solidgear.es:56192/remote.php/webdav/SMB/Hayden.jpg 500 (Internal Server Error)

**Comment by SergioBertolinSG** [comment]
With this stable9+this patch:
GET http://HOST/remote.php/webdav/SMB/Hayden.jpg 503 (Service Unavailable)

Works fine :+1:

**Comment by blizzz** [comment]
I tried with PROPFIND as described in the steps.

**Pull request merged**
