### PR TITLE
run litmus tests on new public webdav endpoint

### PR DESCRIPTION
**Pull request by individual-it**
## Description
run litmus tests on the new webdav endpoint for public links

## Related Issue
part of #36006

## How Has This Been Tested?
:robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by tboerger** [comment]
Why do you move all the env variables to the commands section? They are static, just keep them in the environment block.

**Comment by individual-it** [comment]
because for the new endpoint I need the token `$PUBLIC_TOKEN`, could not work out how to inject the env variable I get from a command `source .env` to the environment section

**Comment by tboerger** [comment]
Then you could still put most of the env variables into the environment block except the url env variable.

**Comment by individual-it** [comment]
@tboerger done, moved what I think I could back to the environment section

**Review by tboerger — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
