### PR TITLE
The files_external app might need the password so autologin must be disabled

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Makes sense – not the best solution from an UX PoV but better than broken files => :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by LukasReschke** [comment]
@carlaschroder This needs to be documented for 8

Please add a note that the "remember me" login functionality is not working when either one of those apps is enabled:

- files_encryption
- files_external
- windows_network_drive

THX!

**Comment by LukasReschke** [comment]
"not working" as in the user cannot select it on the login page

**Pull request merged**
