### PR TITLE
Implement getConfigs for its use in password_policy app

### PR DESCRIPTION
**Pull request by paurakhsharma**
## Description
Implement required functions to get app configs.

## Related Issue
https://github.com/owncloud/password_policy/issues/132

## How Has This Been Tested?
Locally

## Types of changes
- [x] Tests

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
Let's do this now, it will work. But it might be slow if used a lot when there are many app parameter values to get. It calls ``runOcc`` multiple times, and each call will have to talk to the testing app.

For the next refactoring, we can look at the testing app ``/apps/testing/api/v1/apps`` and make that have a GET that will respond with all the app parameter values in a single call. See testing app issue https://github.com/owncloud/testing/issues/28

**Comment by paurakhsharma** [comment]
Backport on #32771

**Comment by phil-davis** [comment]
Congratulations @paurakhsharma you got PR #32768

**Comment by paurakhsharma** [comment]
Thank you @phil-davis

**Pull request merged**
