### PR TITLE
[Stable8.2] Bump sabre/dav 2 1 9

### PR DESCRIPTION
**Pull request by rullzer**
For https://github.com/owncloud/core/issues/21914
Requires https://github.com/owncloud/3rdparty/pull/246

CC: @DeepDiver1975 @RealRancor

### CODE REVIEW

**Comment by rullzer** [comment]
@owncloud/qa can you do your magic to see if this break anything of 8.2.3?

**Comment by SergioBertolinSG** [comment]
@rullzer please fill a issue in the QA repo. We need to prioritize tasks.

**Comment by RealRancor** [comment]
Tested by a user here: https://github.com/owncloud/3rdparty/pull/246#issuecomment-175737422 without an issue (so far).

**Comment by DeepDiver1975** [comment]
We have 3 users reporting that this works - lets get smashbox green and we are ready to merge

**Comment by rullzer** [comment]
- CI was all green.
- 3rdparty merged.
- Rebased

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
