### PR TITLE
Add timeouts to make the UI usable again when a remote share is unrea…

### LINKED ISSUE #23005: removing invalid remote shares
### Steps to reproduce
1. Add/accept share from a remote OwnCloud server
2. Make the remote OwnCloud server inaccessible

### Expected behaviour
It should be possible to somehow remove/un-accept/forget those invalid shares.

### Actual behaviour
Remote shares are not shown as they are not accessible, but they cause OwnCloud throwing errors about those in owncloud.log.

### Server configuration
**Operating system**: FreeBSD

**Web server:** Apache 2.4

**Database:** MariaDB 10.0

**PHP version:** 5.6

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.2.2 (through 9.0.0RC1)

**Where did you install ownCloud from:** FreeBSD ports

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium

**Operating system:** Linux

#### ownCloud log (data/owncloud.log)
```
{"reqId":"qJf7Nngjr2C6iK9NRnQD","remoteAddr":"10.0.254.102","app":"core","message":"Exception while scanning storage \"shared::0834fb19a1db5e6deca1117a75491c65\": Sabre\\HTTP\\ClientException: Could not resolve host: inaccessible-owncloud.server","level":3,"time":"2016-03-09T09:47:37+00:00"}
{"reqId":"VQYsiweJAmR0dupbxJJW","remoteAddr":"10.0.254.102","app":"core","message":"Exception while scanning storage \"shared::0834fb19a1db5e6deca1117a75491c65\": Sabre\\HTTP\\ClientException: Could not resolve host: inaccessible-owncloud.server","level":3,"time":"2016-03-09T09:48:21+00:00"}
{"reqId":"VrBK1xG3bJkx46jtARyc","remoteAddr":"10.0.254.102","app":"core","message":"Exception while scanning storage \"shared::0834fb19a1db5e6deca1117a75491c65\": Sabre\\HTTP\\ClientException: Could not resolve host: inaccessible-owncloud.server","level":3,"time":"2016-03-09T09:50:29+00:00"}
```

### PR DESCRIPTION
**Pull request by nickvergessen**
…chable
### Steps
1. Make a local remote share and accept
2. Change the URL in share_external to an URL that is invalid (not 404 or anything else) e.g. jobisch.no-ip.org
3. Change the md5 in storages to `md5(share_external.share_token . '@' . share_external.remote)`
4. Open the UI for the recipient
### Before

Not reachable
### After

Takes 3 seconds then it shows up.

Fix #23005

The UI is now usable (after the 3 sec timeout), but the share can still not be removed correctly.
Will have a look at that tomorrow.

### CODE REVIEW

**Comment by nickvergessen** [comment]
Okay, after having a look at this, it seems to not be possible, since unshare triggers a delete and therefor tries to get the node from sabredav which then fails to connect to the host.
So this can be dealt with in another PR.

**Comment by guruz** [comment]
👍

**Comment by PVince81** [comment]
Good idea. Not sure if 3 seconds is enough in case of slow servers/connections, especially private servers or shared hosters

**Comment by PVince81** [comment]
I've increased timeout to 10.
Also: rebased.
Looks good :+1:

**Comment by PVince81** [comment]
Failing tests:
```
12:27:07 1) OCA\FederatedFileSharing\Tests\DiscoveryManagerTest::testWithMalformedFormattedEndpointCached
12:27:07 Expectation failed for method name is equal to <string:get> when invoked 1 time(s)
12:27:07 Parameter 1 for invocation OCP\Http\Client\IClient::get('https://myhost.com/ocs-provider/', Array (...)) does not match expected value.
12:27:07 Failed asserting that two arrays are equal.
12:27:07 --- Expected
12:27:07 +++ Actual
12:27:07 @@ @@
12:27:07  Array (
12:27:07 +    'timeout' => 10
12:27:07 +    'connect_timeout' => 10
12:27:07  )
12:27:07 
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/lib/DiscoveryManager.php:90
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/lib/DiscoveryManager.php:127
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/tests/DiscoveryManagerTest.php:97
12:27:07 
12:27:07 2) OCA\FederatedFileSharing\Tests\DiscoveryManagerTest::testGetWebDavEndpointWithValidFormattedEndpointAndNotCached
12:27:07 Expectation failed for method name is equal to <string:get> when invoked 1 time(s)
12:27:07 Parameter 1 for invocation OCP\Http\Client\IClient::get('https://myhost.com/ocs-provider/', Array (...)) does not match expected value.
12:27:07 Failed asserting that two arrays are equal.
12:27:07 --- Expected
12:27:07 +++ Actual
12:27:07 @@ @@
12:27:07  Array (
12:27:07 +    'timeout' => 10
12:27:07 +    'connect_timeout' => 10
12:27:07  )
12:27:07 
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/lib/DiscoveryManager.php:90
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/lib/DiscoveryManager.php:127
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/tests/DiscoveryManagerTest.php:118
12:27:07 
12:27:07 3) OCA\FederatedFileSharing\Tests\DiscoveryManagerTest::testGetWebDavEndpointWithValidFormattedEndpointWithoutDataAndNotCached
12:27:07 Expectation failed for method name is equal to <string:get> when invoked 1 time(s)
12:27:07 Parameter 1 for invocation OCP\Http\Client\IClient::get('https://myhost.com/ocs-provider/', Array (...)) does not match expected value.
12:27:07 Failed asserting that two arrays are equal.
12:27:07 --- Expected
12:27:07 +++ Actual
12:27:07 @@ @@
12:27:07  Array (
12:27:07 +    'timeout' => 10
12:27:07 +    'connect_timeout' => 10
12:27:07  )
12:27:07 
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/lib/DiscoveryManager.php:90
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/lib/DiscoveryManager.php:127
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/tests/DiscoveryManagerTest.php:138
12:27:07 
12:27:07 4) OCA\FederatedFileSharing\Tests\DiscoveryManagerTest::testGetShareEndpointWithValidFormattedEndpointAndNotCached
12:27:07 Expectation failed for method name is equal to <string:get> when invoked 1 time(s)
12:27:07 Parameter 1 for invocation OCP\Http\Client\IClient::get('https://myhost.com/ocs-provider/', Array (...)) does not match expected value.
12:27:07 Failed asserting that two arrays are equal.
12:27:07 --- Expected
12:27:07 +++ Actual
12:27:07 @@ @@
12:27:07  Array (
12:27:07 +    'timeout' => 10
12:27:07 +    'connect_timeout' => 10
12:27:07  )
12:27:07 
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/lib/DiscoveryManager.php:90
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/lib/DiscoveryManager.php:137
12:27:07 /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/federatedfilesharing/tests/DiscoveryManagerTest.php:158
12:27:07 
12:27:07 5) OCA\FederatedFileSharing\Tests\DiscoveryManagerTest::testWithMaliciousEndpointCached
12:27:07 Expectation failed for method name is equal to <string:get> when invoked 1 time(s)
12:27:07 Parameter 1 for invocation OCP\Http\Client\IClient::get('https://myhost.com/ocs-provider/', Array (...)) does not match expected value.
12:27:07 Failed asserting that two arrays are equal.
12:27:07 --- Expected
12:27:07 +++ Actual
12:27:07 @@ @@
12:27:07  Array (
12:27:07 +    'timeout' => 10
12:27:07 +    'connect_timeout' => 10
12:27:07  )
12:27:07 
```

**Comment by PVince81** [comment]
Fixed the tests and rebased

**Pull request merged**
