### PR TITLE
dont update search onResize

### PR DESCRIPTION
**Pull request by fl4p**
backport of https://github.com/owncloud/core/pull/24682

### CODE REVIEW

**Comment by georgehrke** [comment]
Contribution was declared as MIT licensed in https://github.com/owncloud/core/pull/24682#issuecomment-219852683

**Comment by georgehrke** [comment]
👍

**Comment by georgehrke** [comment]
needs a second reviewer
@PVince81 @MorrisJobke @Xenopathic

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
