### PR TITLE
Throw generic exception to overcome, senstitive exception data exposure

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Sensible information could be exposed when downloading a share via public link. We now throw a generic exception that overwrites the original exception message. Also fixed an error which caused such behavior when appending a null byte to the download URL.

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/4536

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by C0rby — APPROVED** [review]
This seems to do the trick.
Looks good to me. :+1:

**Comment by JanAckermann** [comment]
@C0rby wouldn't it be better to wrap the whole controller function in a try-catch block and dedicate the NotFoundException (will throw NotFoundExcpetion) and every other Exception will throw the generic \Exception ?

**Comment by C0rby** [comment]
I have no hard opinion on that. It seems that the generic Exception ends up showing a "Not Found" error in the frontend.

**Comment by JanAckermann** [comment]
Then we'll leave it as it is, as it has minium impact.

**Pull request merged**
