### PR TITLE
Don't append user in a filtered list if groups don't match

### LINKED ISSUE #9551: [users] Adding users in filtered list bug
### Steps to reproduce
1. Go to the user management page
2. Create a group "group1" in the sidebar
3. Create a group "group2" in the sidebar
4. Filter by "group1"
5. Add a user "user1" using the top form and assign to "group2" (but not "group1")

### Expected result
User "user1" does not appear in the list, as it doesn't match the current filter.

### Actual result
User "user1" appears in the list.

### Versions
OC 7 git master 404ac8bcd32aca8f9b004621ac737800cd86dfd1

@blizzz  @raghunayyar

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/9551

@LukasReschke @MorrisJobke @Xenopathic

### CODE REVIEW

**Comment by karlitschek** [comment]
bug killing spree :-) :+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Pull request merged**
