### PR TITLE
Allow login by email address via webdav as well 

### LINKED ISSUE #24791: Login by e-mail is only possible with browsers
Thanks to https://github.com/owncloud/core/pull/24389 it's possible to log in to ownCloud by e-mail address. However, that enhancement was only added to the LoginController, which means only browser sessions are affected. As a user I want to be able to configure clients with the same credentials I use for the browser login. It is unexpected that the same credentials work on the browser, but not on APIs.

### Steps to reproduce
1. Configure e-mail address
2. Configure your (sync) client and use the e-mail address as username

### Expected behaviour
Login should succeed.

### Actual behaviour
Login fails.

**ownCloud version:**
9.1.0

cc @DeepDiver1975 @PVince81 
also @MTRichards as this is a requirement of #23458

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #24791

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Oh crap! All :boom:

**Comment by DeepDiver1975** [comment]
@PVince81 @ChristophWurst @dragotin please review - thx

**Comment by ChristophWurst** [comment]
:+1: tested and works

**Comment by ChristophWurst** [comment]
since you fixed it in ``logClientIn`` it *should* be fixed for OCS, ``base.php`` and ``@CORS`` routes too

**Comment by ChristophWurst** [comment]
btw. this is PR/issue number #25000 :-P

**Comment by PVince81** [comment]
> since you fixed it in logClientIn it should be fixed for OCS, base.php and @CORS routes too

better try it out ?

**Comment by ChristophWurst** [comment]
OCS, CORS and base.php work by e-mail address and password. I had to rebase the branch locally as 9997c431c312042f313792fd3ba511ec703595e9 is needed for the CORS fix.

**Comment by DeepDiver1975** [comment]
> OCS

tested by the ocs integration tests - this was causing the failure on the first try

**Comment by PVince81** [comment]
Looks good, tested with cadaver :+1:

**Pull request merged**
