### PR TITLE
Don't log credentials of LoginController::tryLogin

### LINKED ISSUE #25895: After upgrade from 8.2 to 9.1: plain password in owncloud.log
OwnCloud version 9.1. When enter login on web page, plain pass is showing in owncloud.log

### Steps to reproduce
Open OwnCloud web page, enter login on web page and enter:
user: 		aaaaa
password: 	bbbbb

user: 		aaaaa
password: 	bbbbb

{"reqId":"tAboChzhlAec4q9vgwvN","remoteAddr":"192.168.100.15","app":"user_ldap","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name on 10.90.2.23:10389\",\"Code\":0,\"Trace\":\"
#0 /var/www/owncloud/apps/user_ldap/lib/User_LDAP.php(120): OCA \User_LDAP \User_LDAP->getLDAPUserByLoginName('aaaaa') n
#1 [internal function]: OCA \User_LDAP \User_LDAP->checkPassword(*** sensitive parameters replaced ***) n
#2 /var/www/owncloud/apps/user_ldap/lib/User_Proxy.php(67): call_user_func_array(Array, Array) n
#3 /var/www/owncloud/apps/user_ldap/lib/Proxy.php(139): OCA \User_LDAP \User_Proxy->walkBackends('aaaaa', 'checkPassword', Array) n
#4 /var/www/owncloud/apps/user_ldap/lib/User_Proxy.php(182): OCA \User_LDAP \Proxy->handleRequest('aaaaa', 'checkPassword', Array) n
#5 /var/www/owncloud/lib/private/User/Manager.php(190): OCA \User_LDAP \User_Proxy->checkPassword(*** sensitive parameters replaced ***) n
#6 /var/www/owncloud/core/Controller/LoginController.php(177): OC \User \Manager->checkPassword(*** sensitive parameters replaced ***) n
#7 [internal function]: OC \Core \Controller \LoginController->

tryLogin('aaaaa', 'bbbbb', NULL) n

#8 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array) n
#9 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC \AppFramework \Http \Dispatcher->executeController(Object(OC \Core \Controller \LoginController), 'tryLogin') n
#10 /var/www/owncloud/lib/private/AppFramework/App.php(110): OC \AppFramework \Http \Dispatcher->dispatch(Object(OC \Core \Controller \LoginController), 'tryLogin') n
#11 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC \AppFramework \App::main('LoginController', 'tryLogin', Object(OC \AppFramework \DependencyInjection \DIContainer), Array) n
#12 [internal function]: OC \AppFramework \Routing \RouteActionHandler->__invoke(Array) n
#13 /var/www/owncloud/lib/private/Route/Router.php(280): call_user_func(Object(OC \AppFramework \Routing \RouteActionHandler), Array) n
#14 /var/www/owncloud/lib/base.php(891): OC \Route \Router->match('/login') n
#15 /var/www/owncloud/index.php(39): OC::handleRequest() n
#16 {main}\",\"File\":\"/var/www/owncloud/apps/user_ldap/lib/User_LDAP.php\",\"Line\":104}","level":3,"time":
"2016-08-22T10:53:35+00:00",
"method":"POST",
"url":"\/index.php\/login?user=aaaaa","user":"--"}
{"reqId":"tAboChzhlAec4q9vgwvN",
"remoteAddr":"192.168.100.15",
"app":"user_ldap",
"message":"Exception: {\"Exception\":\"Exception\",\"Message\":\
"No user available for the given login name on 192.168.1.14:3268\",\"Code\":0,\"Trace\":\"

### Expected behaviour
in OwnCloud 8.2 version with same loglevel there was none plain passwords.

### Server configuration
Debian 8
Apache/2.4.10 (Debian)
mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3
PHP 5.6.9-0+deb8u1 (cli) (built: Jun  5 2015 11:03:27)
OwnCloud 9.1
version updated:

1) sudo -u www-data php occ maintenance:mode --on
2) /etc/init.d/apache2 stop
3) gunzip owncloud-files_9.1.0.orig.tar.gz | tar xvf -
4) chown -hR www-data:www-data owncloud/
5) bkp: config/ and data/ directory.
6) rm -rf old files and copy new one (except config/config.php)
7) /etc/init.d/apache2 restart
8) cd /var/www/owncloud
9) sudo -u www-data php occ upgrade

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/9.1.0/Debian_8.0/owncloud-files_9.1.0.orig.tar.gz

**Signing status (ownCloud 9.0 and above):**

```
http://example.com/index.php/settings/integrity/failed - paste the results here:
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```root@files:/var/www/owncloud# sudo -u www-data php occ app:list
Enabled:
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - user_ldap: 0.9.0

Disabled:
  - activity
  - comments
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - files_pdfviewer
  - files_sharing
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - notifications
  - provisioning_api
  - systemtags
  - templateeditor
  - updatenotification
  - user_external


**The content of config/config.php:**
# cat config.php 
<?php
$CONFIG = array (
  'instanceid' => 'instance_id',
  'passwordsalt' => 'pAsSwOrDsAlT',
  'secret' => 'SeCrEt',
  'trusted_domains' => 
  array (
    0 => 'domain.domain.org',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://files.files.org/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'session_lifetime' => 28800,
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'domain.org',
  'mail_smtphost' => 'smtp.smtp.org',
  'mail_smtpport' => '25',
  'ldapIgnoreNamingRules' => false,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'loglevel' => '4',
  'maintenance' => false,
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbuser' => 'username',
  'dbpassword' => 'pass',
  'theme' => '',
  'trashbin_retention_obligation' => 'auto',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
root@sfiles:/var/www/owncloud# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "instanceid",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sfiles.sfiles.org"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\files.files.org\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "installed": true,
        "mail_smtpmode": "smtp",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "session_lifetime": 28800,
        "mail_from_address": "owncloud",
        "mail_domain": "files.org",
        "mail_smtphost": "smtp.smtp.org",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "loglevel": "4",
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "trashbin_retention_obligation": "auto"
    }
}
root@files:/var/www/owncloud# 
or 

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Ldap and Active Directory
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #25895

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
MEEP

```
17:19:45 1) Test\LoggerTest::testDetecttryLogin with data set #0 ('abc', 'def')
17:19:45 Failed asserting that '3 Exception: {"Exception":"Exception","Message":"test","Code":0,"Trace":"#0 [internal function]: Test\\LoggerTest->testDetecttryLogin(*** sensitive parameters replaced ***)\n#1 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/Framework\/TestCase.php(908): ReflectionMethod->invokeArgs(Object(Test\\LoggerTest), Array)\n#2 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/Framework\/TestCase.php(768): PHPUnit_Framework_TestCase->runTest()\n#3 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/Framework\/TestResult.php(612): PHPUnit_Framework_TestCase->runBare()\n#4 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/Framework\/TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(Test\\LoggerTest))\n#5 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/Framework\/TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))\n#6 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/Framework\/TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))\n#7 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/Framework\/TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))\n#8 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/TextUI\/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))\n#9 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/TextUI\/Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)\n#10 phar:\/\/\/usr\/local\/bin\/phpunit\/phpunit\/TextUI\/Command.php(100): PHPUnit_TextUI_Command->run(Array, true)\n#11 \/usr\/local\/bin\/phpunit(548): PHPUnit_TextUI_Command::main()\n#12 {main}","File":"\/var\/lib\/jenkins\/workspace\/owncloud-core\/core\/PR-25902\/tests\/lib\/LoggerTest.php","Line":133}' contains "validateUserPass(*** sensitive parameters replaced ***)".
17:19:45 
17:19:45 /var/lib/jenkins/workspace/owncloud-core/core/PR-25902/tests/lib/LoggerTest.php:140
```

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
> MEEP

nooo432

**Comment by DeepDiver1975** [comment]
@kostas707 THX a lot - mind testing again?

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
@DeepDiver1975 please backport

**Comment by kostas707** [comment]
Thomas, Vincent, viel Danke. Thanks, now all fine. Have a nice days guys :+1:

**Pull request merged**
