### PR TITLE
[jenkins] Dump Arrays, Objects and Exceptions to the log

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs #12682

TODO:
- [x] ref 3rdparty commit https://github.com/owncloud/3rdparty/pull/195

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I rebased this on master.

**Comment by DeepDiver1975** [comment]
> I rebased this on master.



> I rebased this on master.

is the 3rdparty pr mergable as well?

**Comment by DeepDiver1975** [comment]
> is the 3rdparty pr mergable as well?

yes - THX @MorrisJobke

**Comment by DeepDiver1975** [comment]
3rdparty merged .. please update submodule - THX

**Comment by MorrisJobke** [comment]
> 3rdparty merged .. please update submodule - THX

Done

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
