### PR TITLE
Add a warning if a storage wrapper was registered outside of the hook

### LINKED ISSUE #24249: Can not wrap storage of owner anymore
Since some day in the last week, I can not wrap non-shared-storages anymore.

### Steps to reproduce
1. As user1 create folder test1/test2/
2. Share test2 with user2
3. Tag test1 with "Tag"
4. Create a workflow autotagging rule to tag files with "Tag" when a parent is tagged with "Tag"
5. As user2 upload a file
6. Check that the file is tagged

### Expected behaviour
Tag is added

### Actual behaviour
Tag is not added

### Debugging
It works when you check out cdcabbd0b3f6209b2a312b30a84c381f125bcf68 which is the last merge commit before: https://github.com/owncloud/core/pull/23919

So I checked the storages and it looks like the sourceStorage inside the SharedStorage is created without being wrapped. I also checked with @schiesbn sitting next to me and there was never a try to wrap that storage.

Please help @rullzer @icewind1991

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #24249 

@icewind1991 @rullzer

### CODE REVIEW

**Comment by rullzer** [comment]
I like it!
Is it possible to have tests?

**Comment by nickvergessen** [comment]
> Is it possible to have tests?

well it's all static and it only creates a log entry, not sure if that is suitable for writing a useful test

**Comment by icewind1991** [comment]
:+1: good to have

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
