### PR TITLE
Trim leading or trailing slashes in file cache paths

### PR DESCRIPTION
**Pull request by PVince81**
This is just an additional safety in case bugs similar to https://github.com/owncloud/core/pull/13170 pop up.

Passing a file name with a leading slash to the file cache would store it as is and in some cases have -1 as parent id instead of the root's parent.

This fix trims leading and trailing slashes.

But also I'm not sure whether it makes sense API-wise.
Should every filesystem-based function auto-trim slashes everywhere ?

@icewind1991 @MorrisJobke

### CODE REVIEW

**Comment by Xenopathic** [comment]
I'd say that the fs functions should definitely cope with leading slashes (it's the UNIX way after all), so this gets :+1: from me

**Comment by MorrisJobke** [comment]
```

14:00:48 1) Test\Files\Cache\Wrapper\CacheJail::testBogusPaths with data set #0 ('/bogus.txt', 'bogus.txt')
14:00:48 Failed asserting that false is not false.
14:00:48 
14:00:48 /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/tests/lib/files/cache/cache.php:545
14:00:48 
14:00:48 2) Test\Files\Cache\Wrapper\CacheJail::testBogusPaths with data set #1 ('//bogus.txt', 'bogus.txt')
14:00:48 Failed asserting that false is not false.
14:00:48 
14:00:48 /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/tests/lib/files/cache/cache.php:545
```

**Comment by MorrisJobke** [comment]
@icewind1991 please have a look at this

**Comment by icewind1991** [comment]
Looks good :+1:

**Pull request merged**
