### PR TITLE
DnD folder with Firefox 31 behaves incorrectly

### LINKED ISSUE #9857: OC7.0.0 Cannot upload 2 directories through Drag and Drop
Create 2 folders Folder1 & Folder 2. Put one text file in each folder.
Select the 2 folders in explorer (Linux Mint 17 file explorer)
Drag and drop into OC Documents folder (displayed in Firefox 31)
File transfert starts and fails immediately. A small orange notification zone is displayed. It is empty
POST requests receive no answer.
owncloud.log contains:
{"reqId":"53d10a32b13d4","app":"files","message":"Upload error: 3 - Le fichier n'a \u00e9t\u00e9 que partiellement envoy\u00e9.","level":3,"time":"2014\/07\/24 15:29:22","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php"}
{"reqId":"53d10a32f157c","app":"files","message":"Upload error: 3 - Le fichier n'a \u00e9t\u00e9 que partiellement envoy\u00e9.","level":3,"time":"2014\/07\/24 15:29:22","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php"}
=> The file has been only partially sent.
No other message in the web server (Apache 2.2 under Centos 6.5 with PHP 5.3) log

Made another test: the feature works with Chrome 36.

So two solutions:
- there is a problem inside Firefox browser
- there is a problem with browser side OC code that occurs only in Firefox

Can somebody help me locate the javascript (jQuery?) code that calls apps/files/ajax/upload.php ?

### PR DESCRIPTION
**Pull request by PhilJung**
Fixes #9857
New version of #10082 including comments:
- original fix
- modified message
- localisation support
- but no french translation included

### CODE REVIEW

**Comment by PhilJung** [comment]
I rebased the PR to the current HEAD but:
- inspection reports 2 issues I don't understand
- CI bot tells that commit start point does not exist and finishes with an exception.
Would somebody have a clue of what to do next ? :-)

**Comment by MorrisJobke** [comment]
> CI bot tells that commit start point does not exist and finishes with an exception. Would somebody have a clue of what to do next ?

He sometimes doesn't want to work. A retest showed, that everything is fine.

> inspection reports 2 issues I don't understand

I guess this is just because Scrutinizer doesn't know about this. @LukasReschke @PVince81 Wasn't there a special comment to mark a variable/object as available for scrutinizer?

We need to test this also for other browsers - especially IE8+, Chrome and Safari, because there isn't anything listed here for example: https://developer.mozilla.org/en-US/docs/Web/API/DOMError#Browser_compatibility

@LukasReschke Can you give the Safari browser a try?

**Comment by PhilJung** [comment]
Found that syncrhonous call must be inside a Worker and not online. I need to check how to do this. And if I add a worker, I loose the synchronous / blocking behaviour that was expected.
Will see how I can rework this part.

**Comment by PhilJung** [comment]
OK. We have a problem.
First case: we stay with async FileReader. In this case, under FF, the result of readAsArrayBuffer is not known when we evaluate the next lines. So we cannot decide if file is or is not a folder. We cannot wait for the result in a while loop because the async operation starts only when we exit from the "add" function. 
We could make the readAsArrayBuffer call after having defined onload and onerror callbacks. The callbacks would perform the real work. But it look like "add" needs to return true (continue adding files) or false (stop adding false) => it need this information syncrhonously.
Second case: we replace FileReader by FileReaderSync. In this case, under FF, new FileReaderSync must be called from within a worker job. And now the job is asynchronous and we fall back into first case.

The solution seems to be somewhere else. Any idea ?

**Comment by PVince81** [comment]
With a bit of luck the newer versions of Firefox might work better ?

**Comment by DeepDiver1975** [comment]
looks dead to me ... requires heavy rebase action - we better restart this from scratch

@PhilJung sorry for letting this PR rott :crying_cat_face:

**Pull request closed without merging**
