### PR TITLE
[stable8.1] Fix removal of share permissions when share disabled for user

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/18124

Please review @Xenopathic @MorrisJobke @karlitschek @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
:+1:

**Comment by Xenopathic** [comment]
:+1:

**Comment by Xenopathic** [comment]
SHIT - accidentally merged this. Please re-open @PVince81

**Comment by Xenopathic** [comment]
@jancborchardt Perhaps you can use this as an argument as to why undo > confirm? I quite happily clicked through the confirmation... :smile:

**Comment by jancborchardt** [comment]
LOL :D

**Comment by jancborchardt** [comment]
cc @jospoortvliet on that one

**Comment by jancborchardt** [comment]
@Xenopathic and that’s exactly why there is a »Revert« button as well here. ;)

**Comment by Xenopathic** [comment]
@jancborchardt Well, I did press that, but it doesn't *undo* the action, it allows you to *revert* the action (aka create a new PR that reverts it). I did that, then decided that it wasn't very useful, so manually removed the commits from the history with a force push.

**Pull request merged**
