### PR TITLE
JS tests for jquery.avatar

### PR DESCRIPTION
**Pull request by rullzer**
javascript tests for the avatar code. Taken from #17998 since I need to fix that and this is actually unrelated.

But it is always good to get more tests in.

CC: @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
The subject is misleading. This is not only JS tests but also fixes a rounding issue.

:+1:

**Comment by rullzer** [comment]
@PVince81 ah yes. Minor fix but you are right :)

**Comment by rullzer** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Needs a second reviewer @Xenopathic @blizzz @nickvergessen @schiesbn

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
