### PR TITLE
[Tests-Only] add api test for webdav requests with multiple slashes in the endpoints

### LINKED ISSUE #34365: extra "/" in DAV URL makes server return "500 Internal Server Error"
### Steps to reproduce
1. access webDAV endpoint with an extra `/` before `remote.php` e.g `curl -u admin:admin  "http://localhost/owncloud-core//remote.php/dav/files/admin/welcome.txt"  -v`

### Expected behaviour
nice error with some 4xx code returned

### Actual behaviour
500 Internal Server Error

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Apache2
**Database:**
SQLite
**PHP version:**
7.1.26
**ownCloud version:** (see ownCloud admin page)
11.0.0 prealpha (git) 
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oce1t8r2vis9",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "172.17.0.1"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "version": "11.0.0.0",
        "logtimezone": "UTC",
        "htaccess.RewriteBase": "\/owncloud-core\/",
        "ldapIgnoreNamingRules": false,
        "enable_previews": false,
        "csrf.disabled": true,
        "loglevel": 0,
        "theme": "",
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "sharing.federation.allowHttpFallback": true,
        "files_external_allow_create_new_local": "true",
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/tests\/acceptance\/..\/..\/apps\/testing\/data\/apiSkeleton",
        "log_type": "owncloud",
        "firewall.debug": 1,
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "dav.enable.async": true
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.4.1
  - comments: 0.3.0
  - dav: 0.4.0
  - diagnostics: 0.1.3
  - enterprise_key: 0.1.4
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firewall: 2.7.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.3.1
  - testing: 0.1.0
  - user_management: 0.0.1
  - windows_network_drive: 0.7.2
  - workflow: 0.3.0
Disabled:
  - brute_force_protection
  - files_antivirus
  - files_classifier
  - files_primary_s3
  - guests
  - multidirtest
  - notifications
  - oauth2
  - password_policy
  - ransomware_protection
  - search_elastic
  - twofactor_totp
  - updatenotification
  - user_ldap

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### ownCloud log (data/owncloud.log)
```{"reqId":"rIW2E7vfRsC5tszMac8O","level":3,"time":"2019-02-04T07:40:28+00:00","remoteAddr":"127.0.0.1","user":"--","app":"remote","method":"GET","url":"\/owncloud-core\/\/remote.php\/dav\/files\/admin\/welcome.txt","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Message\":\"Requested uri (\\\/owncloud-core\\\/remote.php\\\/dav\\\/files\\\/admin\\\/welcome.txt) is out of base uri (\\\/owncloud-core\\\/\\\/remote.php\\\/dav\\\/)\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(534): Sabre\\\\DAV\\\\Server->calculateUri('\\\/owncloud-core\\\/...')\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Server.php(309): Sabre\\\\DAV\\\\Server->getRequestUri()\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Server.php(148): OCA\\\\DAV\\\\Server->isRequestForSubtree(Array)\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->__construct(Object(OC\\\\AppFramework\\\\Http\\\\Request), '\\\/owncloud-core\\\/...')\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/remote.php(175): require_once('\\\/home\\\/artur\\\/www...')\\n#5 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":568}"}
```

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Add tests for requesting dav endpoints with multiple slashes `/` in the url

## Related Issue

- Fixes https://github.com/owncloud/core/issues/34365

## How Has This Been Tested?

:robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm :+1:

**Comment by phil-davis** [comment]
Note: CI is currently broken in core. See PR #38370 - need to merge that first and then rebase this.

**Review by swoichha — COMMENTED** [review]
Why there is no test for `GET` request? @dpakach

**Review by swoichha — COMMENTED** [review]
LGTM

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Rebased to get fresh, an hopefully passing, CI.

**Comment by dpakach** [comment]
@phil-davis it was failing because an issue got fixed in sabre/dav thanks to you. I've fixed it and should be green now

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
