### PR TITLE
Trashbin restore to folder

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Add API tests for deleting a file in a folder and:
- the file ends up in the trashbin root
- when restored, it goes back in the original folder
- if the original folder has been deleted, then the file goes back in the root folder
- if the original folder has been deleted and then restored, then the file goes back in the original folder
- if the original folder has been deleted and then recreated, then the file goes back in the original folder

## Motivation and Context
Have tests for the behaviour of the trashbin when dealing with individual files from folders.
Make the tests "document" the existing behaviour.

## How Has This Been Tested?
Running the new tests locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New test coverage

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
Only the last commit is relevant here. The others are the integration test refactoring that is awaiting review.

I did these API test additions to illustrate the sort of thing that is not covered at present. The behaviour when restoring a file whose original folder does not exist was asked about today, and the "requirement" for that does not really exist anywhere. So Behat feature files become the requirement definition.

Of course many existing feature files need to be split into smaller "features", and the "feature" explained a bit at the top of the file, followed by a reasonable numb er of tests for the feature.

**Comment by phil-davis** [comment]
Note: no response from drone this morning.

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
DO NOT MERGE YET - until after #30413 is merged.

**Comment by phil-davis** [comment]
PR #30490 has code squashed and rebased on top of latest proposed integration test refactoring.

**Pull request closed without merging**
