### PR TITLE
clarify link on apps management to the dev documentation

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @jancborchardt @MTRichards

### CODE REVIEW

**Comment by jancborchardt** [comment]
It’s still a bit strange wording, better to call it »Developer documentation« to be clear?

**Comment by karlitschek** [comment]
I like Developer documentation better but Develop your app is also fine with me :+1:

**Comment by MorrisJobke** [comment]
I updated the term.

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by Raydiation** [comment]
:+1:

**Comment by jancborchardt** [comment]
Great stuff, thanks!

**Pull request merged**
