### PR TITLE
Correct regular expressions

### PR DESCRIPTION
**Pull request by LukasReschke**
Previously the regex was only matching on single characters. Meaning that file names such as ":+1:.txt" where possible while ":+1:" alone never was. This check apparently never worked as expected.

@DeepDiver1975

### CODE REVIEW

**Comment by LukasReschke** [comment]
Also stuff for the testing plan.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@karlitschek we should backport this

**Comment by karlitschek** [comment]
agreed. please backport

**Comment by LukasReschke** [comment]
Will do. 8.1.2 please. This can break stuff.

**Comment by LukasReschke** [comment]
Ref https://github.com/owncloud/core/pull/17991

**Pull request merged**
