### PR TITLE
fixed path - vendor/zxcvbn/dist/zxcvbn.js

### LINKED ISSUE #24422: settings/personal: new password always marked very weak
When changing the password on the personal settings page, password strength indication isn't updated properly:
After typing the first letter, the strength bar is one segment long and red, the tooltip displays "Very weak password" which is expected.
While further typing more characters, the strength bar gets longer and turns green, while the tooltip remains on "Very weak". No messages on the browser error console.

Observing Firefox Debugger, the strengthify-wrapper title actually changes to "Strong password", but the displayed tooltip isn't updated. Poking around, I found that the tooltip text is updated from data-original-title, not from title.

V9.0.1, tested on latest OSX Firefox and Safari.

### PR DESCRIPTION
**Pull request by alieneby**
## Description

In the personal settings page the password strength was not displayed.
Reason the Javascript file zxcvbn.js could not be loaded.
I updated the path for this file.
## Related Issue

fixes https://github.com/owncloud/core/issues/24422
## How Has This Been Tested?

I tested it on my MacBook.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Tested - works :+1:

**Comment by DeepDiver1975** [comment]
@alieneby Please fix your github account as explained above and also please sign the CLA. THX

**Comment by VicDeo** [comment]
:+1: tested, works 

Waiting for CLA stuff

**Comment by PVince81** [comment]
:+1: fixes the lib, strong password get a green indicator.

However it doesn't fix the issue with the sticky tooltip. I think jquery.strengthify has a bug and doesn't update its tooltip properly.

Still ok to merge from my POV.

**Pull request merged**
