### PR TITLE
Test locking with strange filename

### PR DESCRIPTION
**Pull request by butonic**
Verify the db locking layer can handle strange filenames

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
cc @rullzer @LukasReschke @nickvergessen @DeepDiver1975

**Comment by nickvergessen** [comment]
We md5 the path, so not sure we need this?

**Comment by MorrisJobke** [comment]
> We md5 the path, so not sure we need this?

At least it doesn't hurt, because once we maybe change the locking internals this is still a valid use case.

**Comment by rullzer** [comment]
Yeah can't hurt.
:+1:

**Pull request merged**
