### PR TITLE
Makes settings quota select like multiselect.

### LINKED ISSUE #18672: user management different drop down box
I just saw this in master (Iceweasel 40.0.3):

Why does the quota checkbox looks different than the "groups" and "group admin" check boxes?

cc @jancborchardt

### PR DESCRIPTION
**Pull request by raghunayyar**
Fixes #18672

So, the default select looks like the multi-select now, making selects consistent on that page.

@schiesbn @jancborchardt @owncloud/designers have a look.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Awesome :+1:

**Comment by jancborchardt** [comment]
Nice! Few details:
* [ ] the arrow should be slightly transparent instead of full black, compare to the other dropdown
* [ ] clicking on the arrow should also open the dropdown
* [ ] can you get rid of the dotted outline (in Firefox)
* [ ] it’s not yet fixed for example in the language dropdown in Personal settings or in the account switcher in the Mail app

**Comment by raghunayyar** [comment]
> it’s not yet fixed for example in the language dropdown in Personal settings or in the account switcher in the Mail app

Well, the container of the select has to be used for introducing that triangle. So, I will write a class for it in core. I am afraid, there is no other way of making that triangle over there (unless we use an image)

**Comment by jancborchardt** [comment]
Instead of writing a class for it in core, can’t you just attach it to the select type directly?

**Comment by MorrisJobke** [comment]
Tested and works. :+1:

**Comment by raghunayyar** [comment]
I think, only these 2 issues which I have fixed in the previous issue can be fixed. Need one more thumbs up and this shall go in.

**Comment by jancborchardt** [comment]
Nice, fixed some stuff. :+1:

**Pull request merged**
