### PR TITLE
Acceptance test for searching names of files and folders containing  …

### PR DESCRIPTION
**Pull request by bhawanaprasain**
## Description
Users can search files and folders that contain emoji in their name .

Part of issue #34437

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests only (no source changes)

### CODE REVIEW

**Comment by bhawanaprasain** [comment]
@dpakach @skshetry  @paurakhsharma please review on my PR.

**Review by skshetry — COMMENTED** [review]
:+1:

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@bhawanaprasain please make a backport to `stable10`

**Comment by phil-davis** [comment]
Backport `stable110` #35379

**Pull request merged**
