### PR TITLE
[stable9] Add test for duplicate 401 headers on DAV

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/26690 to stable9

@owncloud/qa

### CODE REVIEW

**Comment by PVince81** [comment]
```
Expected value 'Basic realm="ownCloud"' for header 'WWW-Authenticate', got 'Basic realm="sabre/dav"' (Exception)
```

@DeepDiver1975 is it expected that the realm was "sabre/dav" instead of "ownCloud" on stable9 ? Or is it another bug ?

**Comment by SergioBertolinSG** [comment]
´´´Expected value 'Basic realm="ownCloud"' for header 'WWW-Authenticate', got 'Basic realm="sabre/dav"'´´´

That realm was renamed in 9.1? Should it be ownCloud in stable9 as well?

**Comment by SergioBertolinSG** [comment]
XD same message.

**Comment by PVince81** [comment]
From what I seem to remember the realm was always the same. But let's check its name in OC <= 8.2

**Comment by PVince81** [comment]
Seems like a regression:

8.1:
```
WWW-Authenticate: Basic realm="ownCloud"
```

8.2
```
WWW-Authenticate: Basic realm="ownCloud"
```

9.0:
```
WWW-Authenticate: Basic realm="sabre/dav"
```

Not sure how bad that is...

**Comment by PVince81** [comment]
I'll make a separate ticket to address this

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/26720 for the wrong realm

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/pull/26721 which is the realm backport fix

**Pull request closed without merging**
