### PR TITLE
[stable10] Sync code deduplication and core controlled sync

### PR DESCRIPTION
**Pull request by butonic**
backport of https://github.com/owncloud/core/pull/29669, https://github.com/owncloud/core/pull/30367 and https://github.com/owncloud/core/pull/30412 to stable10

### CODE REVIEW

**Comment by tomneedham** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by patrickjahns** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by tomneedham** [comment]
Codecov sorted itself out. Waiting on jenkins now.

**Comment by butonic** [comment]
summoning @DeepDiver1975 and @PVince81 to update them on how user sync changes and get a review out of them for 10.0.8

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
