### PR TITLE
fix: previews:cleanup with chunk size argument

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Fix previews:cleanup with chunk size argument

## Related Issue
- https://github.com/owncloud/core/pull/40045#issuecomment-1243721634

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
no change log entry - belongs to 40045

**Review by jnweiger — CHANGES_REQUESTED** [review]
Casting a string "chunk_size=1234" to int does not do the trick. It yields 0.
Martin uses it wrong.

Insert coffee.

**Comment by mmattel** [comment]
> Martin uses it wrong.

This is correct, but casting to int reduces to possible errors when using non integer...

**Review by phil-davis — DISMISSED** [review]
Should we add more validation?
If `chunk_size` `is_numeric` and greater than 0 then it is probably OK and can be cast to `int` and used. Otherwise spit out an error message to the user and `exit(1)`

**Comment by phil-davis** [comment]
And do we target this to `release-10.11.0` branch?

**Pull request closed without merging**
