### PR TITLE
Fix constructor arguments for APCUIterator

### PR DESCRIPTION
**Pull request by icewind1991**
See also https://secure.php.net/manual/en/class.apcuiterator.php

### CODE REVIEW

**Comment by Xenopathic** [comment]
This is the most inconsistent doc page I've ever seen: https://secure.php.net/manual/en/apcuiterator.construct.php

The definition says there isn't that extra parameter, the argument list says there is, and the examples show there is...

**Comment by icewind1991** [comment]
Probably to much copy paste from the `APCIterator`

**Comment by icewind1991** [comment]
[the source](https://github.com/krakjoe/apcu/blob/master/apc_iterator.c#L532) seems to agree that there is no extra param

**Comment by Xenopathic** [comment]
:+1:

**Comment by icewind1991** [comment]
Submitted a patch to the docs

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
