### PR TITLE
Use array_merge when reading cached groups members

### PR DESCRIPTION
**Pull request by PVince81**
For https://github.com/owncloud/core/pull/24950#discussion_r65373325

@nickvergessen @alexweirig @owncloud/ldap

### CODE REVIEW

**Comment by nickvergessen** [comment]
Can't test, but looks way better logicwise to me

**Comment by rullzer** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
unit tests?

**Comment by PVince81** [comment]
> unit tests?

:cry: 

I can have a try but it might take a day or two, especially considering that there is no test for this section of the code.

**Comment by PVince81** [comment]
Let's see whether I can mock my way into that specific branch of the code... that function is huge!

**Comment by PVince81** [comment]
Ha, take this! https://github.com/owncloud/core/pull/25024/commits/059778bef0fbc37b7d46a0ca2a02dcb339e36f9a

Reverting the array_merge change will make this fail.

Please review!

**Comment by alexweirig** [comment]
@PVince81 
I changed the line of code and tested in the 9.1 daily build I had setup last week and the merge doesn't seem to cause any problems.
👍

**Comment by PVince81** [comment]
@alexweirig thanks a lot!

**Comment by DeepDiver1975** [comment]
Backports are pending - down to which version?
- [ ] 9
- [ ] 8.2
- [ ] 8.1
- [ ] 8

**Comment by PVince81** [comment]
Sorry, forgot to remove the label.

This was a special case: we already had a backport to 9.0 https://github.com/owncloud/core/pull/24950#discussion_r65373325 but @nickvergessen found a problem. This PR here fixes it and I cherry-picked the fix to the backport PR, which is also merged already.

**Comment by alexweirig** [comment]
@DeepDiver1975 maybe backport to 8.2 if possible?

**Comment by nickvergessen** [comment]
> maybe backport to 8.2 if possible?

Not needed, because the breaking commit was only introduced with 9.0+

**Comment by alexweirig** [comment]
But 8.2 didn't even have dynamic groups support, we implemented it based on 8.2 and we're still using 8.2.1 because later 8.2 versions don't have it, or am I wrong?

**Pull request merged**
