### PR TITLE
[stable9] fix endless loop

### PR DESCRIPTION
**Pull request by butonic**
backport of https://github.com/owncloud/core/pull/25094 to stable9

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
@DeepDiver1975 @guruz second review ?

**Comment by guruz** [comment]
I think it's nicer that https://github.com/owncloud/core/pull/25094/files has a code comment explaining this.  But not mandatory 👍

**Comment by butonic** [comment]
lets wait for an updated opinion of @DeepDiver1975 in the master PR https://github.com/owncloud/core/pull/25094

**Comment by PVince81** [comment]
Setting as critical because the infinite loop which makes Oracle unusable with lots of shares.

**Comment by butonic** [comment]
not "lots" ... a *single* link share causes an infinite loop when opening the share tab, quickly killing all apache php processes.

**Comment by PVince81** [comment]
:scream_cat:

**Pull request closed without merging**
