### PR TITLE
add details icon for file actions dropdown

### PR DESCRIPTION
**Pull request by jancborchardt**
@PVince81 @MorrisJobke can you hook it up?

### CODE REVIEW

**Comment by PVince81** [comment]
Done

**Comment by jancborchardt** [comment]
:+1: let’s do it! I assume you want to do the order fix in a different PR?

**Comment by PVince81** [comment]
Yes, the order needs more thinking for a good solution. No need to block this PR for that.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
