### PR TITLE
Add mod_cgi and mod_fastcgi to .htaccess

### PR DESCRIPTION
**Pull request by ghost**
Follow-up of https://github.com/owncloud/core/pull/18194

Ref for mog_cgi: https://github.com/owncloud/core/issues/15883

### CODE REVIEW

**Comment by RealRancor** [comment]
TBD in https://github.com/owncloud/core/issues/22178

**Comment by RealRancor** [comment]
Not quite sure if the ``SetEnvIfNoCase Authorization "(.+)" HTTP_AUTHORIZATION=$1`` should be added to each apache module block.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by RealRancor** [comment]
Just a short note: I have no idea what i'm doing here :see_no_evil:

**Comment by MorrisJobke** [comment]
As there are no specific complains about this and nobody who could test this I will close this here.

Sorry @RealRancor :( I hope you understand that such a PR that simply lies around doesn't help anybody

**Comment by RealRancor** [comment]
@MorrisJobke I'm absolutely fine with that. Sometimes complains about users of non-mod_php modules are hitting the forums but personally i don't care about that. It's easier to point those users to Apache2 + mod_php or nginx + php-fpm where that stuff is not needed.

**Pull request closed without merging**
