### PR TITLE
locking: handle exceptions correctly during copy operation

### LINKED ISSUE #19242: Locking should be able to handle exceptions
I just debugged a issue where we throw a exception during a copy operations because something went wrong. (https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L788)

In this case we never free the lock and we will run into a lock exception later on, if we catch the error and try to recover.

We should always have a try-catch block between ````$this->lockFile(...);```` and ````$this->unlockFile(....);```` to make sure that we also release the lock correctly if something goes wrong.

cc @PVince81 @icewind1991 @DeepDiver1975

### PR DESCRIPTION
**Pull request by schiessle**
catch exceptions during the copy operation and make sure that we free the lock correctly

fix https://github.com/owncloud/core/issues/19242

cc @icewind1991 @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Makes sense, as discussed :+1:

**Comment by schiesbn** [comment]
failing tests are unrelated and can be ignored.

**Comment by karlitschek** [comment]
:+1:

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Pull request merged**
