### PR TITLE
Enhancement: Right click on filelist table row opens ownCloud context menu

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Enhancement: Right click on filelist table row opens ownCloud context menu

## Related Issue
- Fixes <issue_link>

## How Has This Been Tested?
See comment https://github.com/owncloud/core/pull/39376#pullrequestreview-787877769

## Screenshots (if appropriate):
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
@pmaier1 do you agree to have this feature in the product, It always bothered me, that we don't have it.

**Review by phil-davis — APPROVED** [review]
WFM - I tried right-click on both files and folders. The various context menu items all work. You can even right-click when on top of the icons on the right-hand end of a file row (sharing, create public link, "..." and over the Size column. The context menu is shown and works.

**Comment by phil-davis** [comment]
> Freezed, needs a decision by @pmaier1

@pmaier1 this seems a reasonable thing to me. Go ahead?

**Review by IljaN — APPROVED** [review]

**Comment by JanAckermann** [comment]
Not accepted by PM

**Pull request closed without merging**
