### PR TITLE
[IE8] Fix file type sizes and popover menus in file list

### PR DESCRIPTION
**Pull request by PVince81**
Added a new hack to be able to use a filter to downscale or upscale file type icons, that will do for now.
- fixes file type icons in file list (PNGs are now 32x32)
- fixes file type icon when displayed in the sidebar
- fixes small file type icons in the "New" menu by downscaling with filter
- fix popover menu borders ("New" menu and also file actions menu)

Please review @MorrisJobke @owncloud/designers @karlitschek

### CODE REVIEW

**Comment by PVince81** [comment]
For https://github.com/owncloud/core/issues/18619

**Comment by karlitschek** [comment]
:+1:

**Comment by davitol** [comment]
:-1: The checkboxes are not well located and preview icons of the sidebar are still broken.

screen shot 2015-09-30 at 08 29 42
screen shot 2015-09-30 at 08 30 43

**Comment by PVince81** [comment]
@davitol I didn't fix the checkboxes in this PR, only the icons. Please revisit your comment.

**Comment by PVince81** [comment]
(step by step, checkboxes to be fixed in a separate PR)

**Comment by MorrisJobke** [comment]
Weird:

* the mimetype icon of `Bath_from_alecandra_park.jpg` just is well scaled
* the `casette.psd` mimetype icon not

Both should use the same source.

bildschirmfoto von 2015-09-30 10-15-22

**Comment by MorrisJobke** [comment]
Ah ... found the issue. The `jpg` uses the `preview.png` and the other one is the actual mimetype icon

**Comment by MorrisJobke** [comment]
* after clearing the cache a third time the issue is resolved.

**Comment by MorrisJobke** [comment]
Now It looks good :+1:

**Comment by PVince81** [comment]
Note to self: always clear the cache at least three times in IE8 :wink:

**Comment by PVince81** [comment]
@davitol can you clear the IE8 cache three times and see if the text file icon solves itself ?

**Comment by davitol** [comment]
@PVince81 I've cleared IE8 cache three times (i felt like i was summoning Candyman :smile_cat: ) but it did not work for me.

**Comment by MorrisJobke** [comment]
The too big thumbnails are fixed with #19468

**Comment by MorrisJobke** [comment]
@davitol Can you disable previews in the config.php and check if this is actually a thumbnail of the mimetype and not a rendered thumbnail inside a preview (which is fixed in #19468)

**Comment by PVince81** [comment]
I managed to reproduce the issue with the text thumbnail: just create an empty text file.
Then I merged https://github.com/owncloud/core/pull/19468 into this branch, and it fixed the thumbnail size.

So I think this can be merged, do you agree @davitol ?

**Comment by MorrisJobke** [comment]
> Then I merged #19468 into this branch, and it fixed the thumbnail size.

Yes. Then it's a preview that contains the mimetype icon. Kind of bad but this seems to how it works.

**Comment by davitol** [comment]
Using #19468 the 'new button' is deformed.

screen shot 2015-09-30 at 11 16 36

**Comment by PVince81** [comment]
@davitol I haven't fixed the button yet, I'll add it to the main list: https://github.com/owncloud/core/issues/18619#issuecomment-144335627

**Comment by MorrisJobke** [comment]
> Using #19468 the 'new button' is deformed.

Needs to be addressed in another PR. This is only about the mimetype icons and the menus.

**Comment by davitol** [comment]
@PVince81 @MorrisJobke https://github.com/owncloud/core/pull/19454#issuecomment-144331221

I've added 'enable_previews' => false, to my config.php, and even apllying the patch this is the behaviour:

screen shot 2015-09-30 at 12 29 42
screen shot 2015-09-30 at 12 26 12

**Comment by davitol** [comment]
:+1:

**Comment by PVince81** [comment]
@SergioBertolinSG can you confirm the issue with the text icon ? Maybe don't test on Windows Server, it seems to be bugged

**Pull request merged**
