### PR TITLE
 WIP print error message when no password in occ

### PR DESCRIPTION
**Pull request by JKawohl**
## Description

Added a do-while loop to check if the password string length is larger than 0 when called by occ.
## Related Issue
#25206
## Motivation and Context

When you entered a password with a length of 0 in occ you could set a password with a length of 0. This is not desirable and also doesn't work in the ui. The behaviour should be consistent
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Kawohl** [comment]
There where no tests yet for ResetPassword.php i will need some advice in writing one please

**Comment by butonic** [comment]
👍 

@Kawohl have @PhilippSchaffrath walk you through the test in person ;)

**Comment by PhilippSchaffrath** [comment]
@butonic we paired to create those tests :)

**Comment by davitol** [comment]
IMHO the "print error message" when no password in occ should be shown in the first step when we are asked for a new password and we set 'empty'. It should not be needed to set empty value twice

screen shot 2016-11-04 at 13 32 06

offtopic: In the same warning it is used did not and later didn't. I would be better homogenize the warning without contractions.

**Comment by PhilippSchaffrath** [comment]
Some of the tests fail because Jenkins and some Tests where updated in master, now Jenkins fails those tests for your branch. A rebase should fix this.

**Comment by PhilippSchaffrath** [comment]
Looks like a missing `--force` after the rebase push. Not sure how to fix it. @DeepDiver1975 do you have experience with this?

**Comment by PhilippSchaffrath** [comment]
Since this PR performed a messed up rebase, i cherry-picked the commits into #26929.

**Pull request closed without merging**
