### PR TITLE
[stable10] oc_migration column length

### PR DESCRIPTION
**Pull request by tomneedham**
Backport to stable10 for PR https://github.com/owncloud/core/pull/28086

### CODE REVIEW

**Comment by phil-davis** [comment]
@individual-it finished looking at the Travis UI test errors, so I restarted the jobs and they have passed this time.

**Comment by PVince81** [comment]
need to increase version.php to make sure the migration runs

**Comment by PVince81** [comment]
@tomneedham version increase please

**Comment by tomneedham** [comment]
Fixed version and squashed, pushed, waiting for CI.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by tomneedham** [comment]
kicked jenkins

**Comment by tomneedham** [comment]
rebased

**Comment by tomneedham** [comment]
One rebase-party too many for me today - I messed up. New PR referenced.

**Pull request closed without merging**
