### PR TITLE
Allow deletion of group with special characters

### PR DESCRIPTION
**Pull request by sharidas**
Allow deletion of group with special characters

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change allows deletion of groups which has special characters in the group name.

## Related Issue

https://github.com/owncloud/core/issues/29984

## Motivation and Context

Deletion of group names with special character allowed.

## How Has This Been Tested?

- [x] Create group names with special characters like "/&$#' and then try delete
- [x] Group name get deleted.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sharidas** [comment]
@phil-davis @individual-it This PR can be considered if the discussion in the issue mentioned : If everyone agrees that deletion of group names with special chars is acceptable. Else I will close this PR.

**Review by PVince81 — APPROVED** [review]
Code looks good 👍

**Comment by PVince81** [comment]
please backport to stable10

**Comment by phil-davis** [comment]
Backport stable10 #30111

**Comment by phil-davis** [comment]
and it works - I successfully deleted some group names containing "/" that I had created while replicating the original bug, thanks.

**Pull request merged**
