### PR TITLE
Add missing public link share dialog features

### LINKED ISSUE #31125: [10.0.8 RC1] Public link share dialog
- [ ] Size of the modal itself may not change when multiple (long) mail addresses are entered (it even changes when selecting the input field and selecting another item in the dialog)
- [ ] Move "Share" button to the right
- [ ] E-mail validation should be added (currently select2 takes all values): name@domain.tld

public_link1
---
Adding long/many mail address(es) (modal size increases)

public_link2
---
Unselect the input field (modal size shrinks)

public_link3

@PVince81

### PR DESCRIPTION
**Pull request by lordelix**
## Description

- [x] Size of the modal itself may not change when multiple (long) mail addresses are entered (it even changes when selecting the input field and selecting another item in the dialog)
- [x] Move "Share" button to the right, "Cancel" to the left. The current order seems not intuitive.
- [x] E-mail validation should be added (currently select2 takes all values; you can even just enter spaces): name@domain.tld
- [x] Multiple mail recipients should not be able to see the other recipient's mail addresses. Therefore we should not put all mail addresses in the "To" field but in "BCC". @PVince81 
- [x] "Send copy to self" does not work at all (mails are only sent to the recipients). No ability to receive a copy, tried various scenarios. @PVince81 
- [x] "E-Mail sent" has been removed. It was an explicit requirement to show "E-Mail sent" longer for that the user actually has a chance to read it.
- [x] Public link sendmail: "Sending" is now green, but the actual idea was to have the success message "E-Mail sent" green (which has been removed!)
- [x] "Sending" now seems to have a delay of 2 seconds until it disappears. This was the idea for the "E-Mail sent" indicator.

## Related Issue

Fixes: https://github.com/owncloud/core/issues/31125

## How Has This Been Tested?

Manually tested in FF, Chrome and IE11

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
all recipient mail now in BCC field, including self when ticked

**Review by PVince81 — APPROVED** [review]
:+1: for Felix' part.

**Review by lordelix — COMMENTED** [review]
For @PVince81 part.

**Comment by felixheidecke** [comment]
Backport https://github.com/owncloud/core/pull/31142

**Pull request merged**
