### PR TITLE
Test create share

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Add acceptance test scenarios for when a user is in a group that is excluded from sharing, and that user tries to share a file or folder with a user or group.

Suitable status codes should be returned - e.g. 403 forbidden - and the share should not be created.

The scenarios have been adjusted to currently expect the status codes being returned, with commented-out examples of the status codes that probably should be returned when the related issue is fixed.

## Related Issue
#33733 

## How Has This Been Tested?
Local acceptance test runs

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
This PR demonstrates the statuses that I think should be returned for the test scenarios.
Currently CI will fail because those statuses are not being returned.

Once we agree what statuses should be returned, I can adjust the PR and then skip the test scnarios until issue #33733 is fixed.

**Comment by phil-davis** [comment]
The 4 scenarios * 2 OCS API versions make 8 test fails:
```
--- Failed scenarios:

    /drone/src/tests/acceptance/features/apiShareManagement/createShare.feature:393
    /drone/src/tests/acceptance/features/apiShareManagement/createShare.feature:394
    /drone/src/tests/acceptance/features/apiShareManagement/createShare.feature:412
    /drone/src/tests/acceptance/features/apiShareManagement/createShare.feature:413
    /drone/src/tests/acceptance/features/apiShareManagement/createShare.feature:429
    /drone/src/tests/acceptance/features/apiShareManagement/createShare.feature:430
    /drone/src/tests/acceptance/features/apiShareManagement/createShare.feature:448
    /drone/src/tests/acceptance/features/apiShareManagement/createShare.feature:449
```
https://drone.owncloud.com/owncloud/core/13117/355

with results like:
```
    Examples:
      | ocs_api_version | ocs_status_code | http_status_code |
      | 1               | 403             | 200              |
        OCS status code is not the expected value
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'403'
        +'100'
      | 2               | 403             | 403              |
        OCS status code is not the expected value
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'403'
        +'200'
```
we get back OCS status code 100 or 200, which are "success" codes.

Note: if we comment out the OCS status code checks, then we see that we keep getting back HTTP status code 200 instead of 403. And if we comment out those checks, then we see that the share actually does not exist (which is the end-behavior that we want anyway)

**Comment by phil-davis** [comment]
Rebased. Waiting to see CI results and then adjust actual and expected results in test scenarios.

**Comment by phil-davis** [comment]
Expected status codes have been adjusted.
@individual-it this is ready for review.

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport ``stable10`` #34513

**Pull request merged**
