### PR TITLE
Fix type hint errors in the container and the interface

### PR DESCRIPTION
**Pull request by nickvergessen**
@Xenopathic @LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1: -> comments only

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 ;)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 ;)

@MorrisJobke :wink:

**Pull request merged**
