### PR TITLE
Failing mysql master tests

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 @LukasReschke 

Fixes multiple failures that each on itself can cause the tests to fail.
At least the group/manager.php change should probably be backported.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@nickvergessen 

````
OCA\Provisioning_API\Tests\GroupsTest::testGetGroupAsSubadmin
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'users' => Array (...)
+    0 => Array (...)
 )

/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/provisioning_api/tests/groupstest.php:66

**Comment by nickvergessen** [comment]
Should be fixed now

**Comment by LukasReschke** [comment]
As discussed :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
