### PR TITLE
Creating second share to user who renamed received folder creates a second entry

### PR DESCRIPTION
**Pull request by PVince81**
### Steps
1. Create a user "user1" in a group "group1"
2. As admin, share a folder "test" with "group1"
3. Login as "user1"
4. Rename "test" to "test_renamed"
5. Login as "admin"
6. Share "test" with "user1"
7. Login as "user1" and check folders
### Expected result

Only one folder "test_renamed" appear
### Actual result

Two folders, "test" and "test_renamed".
Also happens when sharing first with "user1" and "group1"
### Versions

Regression since OC 9.0, works fine in OC 8.2.7.

This PR brings an integration test to cover this case.
On master there were fixes regarding to grouping for https://github.com/owncloud/core/issues/24575 but they failed to cover this specific case.
Let's address this inside this PR.

@owncloud/sharing

### CODE REVIEW

**Comment by PVince81** [comment]
@owncloud/sharing @rullzer please review carefully

@rullzer I hope that my usage of `moveShare` here to adjust the file_target is ok. It seems to work and it shouldn't have any side effects, correct ?

**Comment by PVince81** [comment]
TODOs after merge:
- [ ] backport to this stable9.1 PR: https://github.com/owncloud/core/pull/25534
- [ ] backport to this stable9 PR, will need to adjust 'OC_Share::groupItems` instead: https://github.com/owncloud/core/pull/25543

**Comment by rullzer** [comment]
@PVince81 yes that is the correct usage.

:+1:

**Comment by PVince81** [comment]
@DeepDiver1975 can the Jenkinsfile thing be ignored ?
```
hudson.plugins.git.GitException: Failed to fetch from https://github.com/ownCloud/core.git
```

If yes, please merge.

**Pull request merged**
