### PR TITLE
[stable8.1] setting to skip migration tests by default

### PR DESCRIPTION
**Pull request by MorrisJobke**
- if you install owncloud via package it is not
  possible to skip migration tests
- this also allows to disable migration tests for
  an instance by default

Backport of #19508 - @karlitschek Please approve

@PVince81 @LukasReschke @nickvergessen Please review

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I tested this with occ and webUI each enabled and disabled.

**Comment by karlitschek** [comment]
discussion over there: https://github.com/owncloud/core/pull/19661#issuecomment-146606583

**Comment by DeepDiver1975** [comment]
> discussion over there: #19661 (comment)

@karlitschek what shall we do this this? THX

**Comment by karlitschek** [comment]
Wow. You are asking me? This is a mess. ;-)
So I don't think we should skip this be default. There is a very valid reason why we have build this feature. So no here :-1: 
BUT we need a way to skip this for large installation. This is already possible with the occ flag. Unfortunately this is executed automatically without a way for an admin to use this flag in case linux packages are used. Correct analysis?
I have no idea what we can do here? Set the skip migration testing flag in the linux packages occ call?
No idea how to tell the old packages to not do migration. Any idea @jnweiger @dragotin ?
Just to be clear. This is no an issue for 8.2 because occ is not call at all. And this is also not an issue for tar/zip files because an admin can call it manually with the right options.
Not sure what to do in case 8.0 and 8.1 linux packages are used.

**Comment by DeepDiver1975** [comment]
@karlitschek so - we can close this PR - right?

**Comment by DeepDiver1975** [comment]
my only intention is to close 8.1.4

**Comment by karlitschek** [comment]
yes. close it. we need a different soltion

**Comment by cmonteroluque** [comment]
@msrex comment in https://github.com/owncloud/core/pull/19661

**Comment by jnweiger** [comment]
@cmonteroluque msrex does not say anything about Morris' solution. See my comment over there.

**Pull request closed without merging**
