### PR TITLE
Allow indirect set in CappedMemoryCache

### PR DESCRIPTION
**Pull request by icewind1991**
cc @PVince81 @jmaciasportela

### CODE REVIEW

**Comment by jmaciasportela** [comment]
LGTM :+1: Thank You

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
Can we backport this down to 8.2 ?
Because another backport needs this https://github.com/owncloud/core/pull/24413 and wouldn't work (CappedCache), important for memory usage optimization.

@icewind1991 can you make backport PRs to 9 and 8.2 ?

CC @DeepDiver1975 @cmonteroluque

**Comment by PVince81** [comment]
@icewind1991 never mind, https://github.com/owncloud/core/pull/24413 already contains your commit.
Thanks, nothing to do here

**Pull request merged**
