### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @DeepDiver1975 @nickvergessen @LukasReschke @PVince81

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
I hereby approve this :one: byte change! :+1:

**Comment by MorrisJobke** [comment]
Backport in https://github.com/owncloud/core/pull/22323

**Pull request merged**
