### PR TITLE
Backport translations for 8.2

### LINKED ISSUE #19946: Inconsistent use of different languages
After a fresh installation of OC 8.2 and with the default language German I receive the following after opening the administration menue:

> Sicherheits- & Einrichtungswarnungen
>
> Transactional file locking is using the database as locking backend, for best performance it's advised to configure a memcache for locking. See the documentation ↗ for more information.
>  Es wurde kein PHP Memory Cache konfiguriert. Konfiguriere zur Erhöhung der Leistungsfähigkeit, soweit verfügbar, einen Memory Cache. Weitere Informationen finden Sie in unserer Dokumentation.
>
> Bitte überprüfe noch einmal die Installationsanleitungen ↗ und kontrolliere das Log auf mögliche Fehler oder Warnungen.

regards, hitam4450

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #19946 

@DeepDiver1975 @MorrisJobke @vgezer

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Changes look good :+1:

**Comment by MorrisJobke** [comment]
BTW: I tested some languages and there are no errors ;)

**Comment by PVince81** [comment]
Makes sense :+1:, thanks

**Comment by PVince81** [comment]
@karlitschek can you add your seal of approval here for this translations backport ?

**Comment by karlitschek** [comment]
backport is fine! :+1:

**Pull request merged**
