### PR TITLE
Return false if the login is canceled in a hook

### PR DESCRIPTION
**Pull request by icewind1991**
See https://github.com/owncloud/core/pull/13275#issuecomment-69647377

cc @DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
this will result in a message on the login page stating that the password was wrong - we need to adjust this as well - somehow ...

**Comment by Xenopathic** [comment]
@DeepDiver1975 Perhaps that's good behaviour though? If a hook prevents a user from logging in, the user shouldn't get any feedback other than 'your password was incorrect', since otherwise an attacker can learn information about the system.

**Comment by LukasReschke** [comment]
We consider user enumeration through login not a security risk.

**Comment by LukasReschke** [comment]
Other than that, I see no risk in exposing whether login is impossible due to a running encryption process. Telling users wrongly that their password is invalid is a sin :-)

**Comment by Sugaroverdose** [comment]
@LukasReschke what about to tell classical and secure 'Username or password is incorrect'?)

**Comment by LukasReschke** [comment]
@Sugaroverdose It's not really worth it. User enumeration is also possible on a lot of other ways such as timing attacks etc.

It will only give you a warm fluffy feeling while actually not providing more security, instead it will only confuse a lot of your non-technical users. The usability penalty is way higher than any gain that you have. – There is a reason why a lot of  modern web application actually tells you if an account exists or not :-)

**Comment by DeepDiver1975** [comment]
@icewind1991 can you please come up with a solution for https://github.com/owncloud/core/pull/13314#issuecomment-69738206 - THX

**Comment by icewind1991** [comment]
Not sure if there is a proper way to fix it since there's currently no way to tell the reasons of a failed login appart

**Comment by DeepDiver1975** [comment]
> Not sure if there is a proper way to fix it since there's currently no way to tell the reasons of a failed login appart

What about throwing an exception and catch it? @icewind1991

**Comment by PVince81** [comment]
This might fix https://github.com/owncloud/core/issues/12412 too

**Comment by DeepDiver1975** [comment]
> This might fix #12412 too

seems so

**Comment by MorrisJobke** [comment]
I have this issue and will apply this patch to my v7.0.4 instance

**Comment by MorrisJobke** [comment]
See https://github.com/owncloud/core/issues/12412#issuecomment-70742344

**Comment by icewind1991** [comment]
Switched to throwing an exception

**Comment by DeepDiver1975** [comment]
> Switched to throwing an exception

Is the behavior now different?

**Comment by icewind1991** [comment]
It gives 'Login canceled by app' as error message now, cant easily give a more specific message (since encryption cant throw an exception from within the hook)

**Comment by DeepDiver1975** [comment]
I'm fine with that for the scope of OC8 - thx @icewind1991 

For the future we could look into a mechanism where exceptions caught during hook execution are passed back out - maybe

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@MorrisJobke can you please retest this? THX

**Comment by MorrisJobke** [comment]
Works, but not in the context I had yesterday, as this issue isn't reproducable today :see_no_evil: But anyway. Code looks good. Exception message is fine and it also looks good in the UI :+1:

**Pull request merged**
