### PR TITLE
Setup for ui tests

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
This PR modifies the existing small Behat/Selenium/Mink UI testing structure so it is ready to move forward with adding new tests easily.
1. Provide "skeleton" files that will be a set of default files that new users created in the test environment will have. This will make it easy to construct tests that move, rename, delete, copy etc files.
2. Modify the structure of the feature/scenario text so that special tags like "AdminLogin" are not needed. Instead of those tags, scenarios that need "givens" can say things like:
```
Given a regular user exists
Given I am logged in as admin
```
This makes it easy to use the "natural language" of Behat's BDD implementation, without messing with special tags to make variable scenario setup happen.
3. Provide some infrastructure for creating users, so that the scenario steps can just say stuff like:
```
Given a regular user exists
```
and the underneath code will create an ordinary user that the scenario can use. Then at the end of the scenario the user gets removed by the AfterScenario code, ensuring isolation between scenarios.
4. Cleanup whitespace at end of lines - easy to tidy everything up now and it is ready to move forward with future minimal diffs.

## Related Issue
#27858 

## Motivation and Context
Having automated UI tests will give more immediate feedback if a change has broken the end-to-end UI behavior in some way. It will also reduce the load of manual testing needed.

## How Has This Been Tested?
The code has been tried in a separate repo to make sure that Travis and SauceLabs process it successfully.
The Travis build/test steps should also run and pass here once the PR is submitted.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Documentation on how to run this test environment on a local machine is under review at https://github.com/owncloud/documentation/pull/3049

### CODE REVIEW

**Comment by phil-davis** [comment]
:( Jenkins seems to be unhappy with all the recent PRs.
What is that all about?

**Comment by DeepDiver1975** [comment]
> What is that all about?

here has been an issue with the docker container to fire up - I just restarted it

**Comment by phil-davis** [comment]
It is still not happy:
```
15:08:17 Fire up the mysql docker
15:08:18 Waiting for MySQL(utf8mb4) initialisation ...
15:18:20 ........................................................................................................................................................................................................
15:18:20 [ERROR] Waited 600 seconds, no response
```

**Comment by phil-davis** [comment]
Note: "use preseedconfig to set lang & skeleton and not autoconfig" https://github.com/owncloud/core/pull/27860/commits/11ca7e97b0363861d118bfcae738c55afe43a886 added by @individual-it to fixup/improve getting the skeleton files in place correctly.

**Comment by PVince81** [comment]
Jenkins slept again... 😴

**Comment by DeepDiver1975** [comment]
@phil-davis there are conflicts in here - please rebase - thx

**Comment by phil-davis** [comment]
@DeepDiver1975 GitHub is telling me "This branch has no conflicts with the base branch"???

**Comment by phil-davis** [comment]
@DeepDiver1975 or @SergioBertolinSG IMHO this is ready to get a review tick and merging.

**Comment by phil-davis** [comment]
@DeepDiver1975 sorry to harass! @individual-it is getting quite a few changes that he has ready that branch off here, assuming this code will be reviewed soon (and hopefully merged in something similar to the shape it is in).
Any chance to get a review/merge soon?

**Comment by SergioBertolinSG** [comment]
@phil-davis we are currently quite busy with the next release. Review will come after it, thanks for your patience.

**Comment by PVince81** [comment]
@phil-davis @individual-it you guys can also review each other's code ?

**Comment by phil-davis** [comment]
Hmmm - that seems a bit odd for ones where we have already worked on bits of it "together" and commits are there from both of us, or actually one of us "summarized" code that both of us worked. It is a bit difficult to be independent when reviewing! But yeh, if you are happy, then when one of us has done something, the other can review it.
The other thing is that until we have more experience with the accepted coding standards for ownCloud, it is good to get review from someone with more coding experience on the project - to make sure we do not go off in a direction that does not fit nicely with other parts of the code/test infrastructure.

**Comment by PVince81** [comment]
Ah, I didn't realize that many commits were from two people writing them 😄 

My comment was mostly for separate work.

**Comment by phil-davis** [comment]
@PVince81 I saw your other comments now on PRs that are based on this. So we should merge this one now, let CI do whatever it does on master, then the others should each slide in nicely on top.

**Comment by individual-it** [comment]
before making a PR to oC @phil-davis & me, we do peer-review stuff "internally"

**Review by individual-it — APPROVED** [review]

**Pull request merged**
