### PR TITLE
allow customization of cron lock file - fixes #13712

### LINKED ISSUE #13712: Lockfile of cron.php is waking up HDD
It is not possible to spin down a HDD which is used for data storage of your ownCloud installation because of the lockfile which is written every 15 minutes to the data/ directory.
Why don't you write it somewhere else inside of the ownCloud installation?

I use a timeout of 10 minutes to spindown my HDD but it is woken up 5 minutes after it goes to sleep because of the lockfile.

(I know it is possible to change it in cron.php but maybe it should be changed or at least be configurable.)

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #13712 

@minils @lordaivan please test - THX

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1: makes sense

**Comment by mmattel** [comment]
Suggestion regarding the description text. What about to mention why it is maybe necessary to change the location of the cron lock file, like: "As the cron lock file is accessed in regular intervals, it may prevent enabled disk drives from spinning down. A different location for this file can solve such issues"

**Comment by DeepDiver1975** [comment]
@mmattel @minils please review the updated text.
@th3fallen maybe as well - because you are a native speaker - THX

**Comment by mmattel** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
closing this in favor of #14400

**Pull request closed without merging**
