### PR TITLE
Update group.php

### PR DESCRIPTION
**Pull request by goodkiller**
Here is fox for my LDAP users OW 7.0.2

### CODE REVIEW

**Comment by LukasReschke** [comment]
This change seems to low to be copyrightable and thus should be safe to merge. It seems like a sensible bug fix and we should accept it?

@karlitschek Please confirm.
@blizzz @nickvergessen Please rereview.

**Comment by nickvergessen** [comment]
Still :+1: from me, although I'd like to have a test for this, for future cases

**Comment by blizzz** [comment]
This thing cannot be tested properly,  without refactoring  lib/private/group.php. Nevertheless, test is desirable.

**Comment by blizzz** [comment]
License question is still open as far as i can see it.

**Comment by DeepDiver1975** [comment]
> License question is still open as far as i can see it.

Not relevant for changes of 5 lines or less

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
