### PR TITLE
List remote shares in shared with you

### LINKED ISSUE #9098: Display remote shares in "Shared with you" section
### Steps to reproduce
1. Mount a remote share (server to server sharing)
2. Go to "Shared with you" section

### Expected result
Share has an entry

### Actual result
List is empty

I'm not sure whether we should add this to the "Shared with you" section or whether it should be yet another section. Or should it appear under "Shared with link" ?

Note that for any cases the API calls will need to be adapted to also return the remote shares as they are currently not returned at all.

Also note that the remote share mounts do not appear either under the "External storage" section, and I think it is correct.

@owncloud/designers @schiesbn @icewind1991 

Setting as "Enhancement", might not have enough time for OC 7.

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #9098
- [x] Depends on #19386

Start of code that lists the remote shares in the shared with you section.
Not done but here to keep track since it is related #19386 

TODO:
- [x] Get remote shares to display
- [x] Get them to properly display
- [x] Fix unit tests
- [x] Add unit tests

### CODE REVIEW

**Comment by rullzer** [comment]
Only the last 3 commits are new.

**Comment by rullzer** [comment]
updated js unit tests and extend them to cover the remote share case

**Comment by rullzer** [comment]
Review time!

CC: @PVince81 @MorrisJobke

**Comment by PVince81** [comment]
:+1: works

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
