### PR TITLE
Bump 3rdparty for dbal-2.5.2

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/214

Lets see if all db's are happy....

### CODE REVIEW

**Comment by LukasReschke** [comment]
> Lets see if all db's are happy....

I like your optimism :speak_no_evil: :wink:

**Comment by PVince81** [comment]
Update testing will also need to be done. Last time a change in DBAL caused some issues.

**Comment by DeepDiver1975** [comment]
> Update testing will also need to be done. Last time a change in DBAL caused some issues.

@jvillafanez can you upgrade test this change? Is the upgrade testing system ready for this? THX

**Comment by jvillafanez** [comment]
It's not ready, but I think I can prepare something manually as long as we have a tarball with the change. I can change the image to use a different DB and tweak one of the mappings to download the new tarball instead of the daily stable8.2, but I need to download the tarball from somewhere.

**Comment by DeepDiver1975** [comment]
> but I need to download the tarball from somewhere.

hmmm ... kind of hard ...

maybe @jmaciasportela has some ideas - he built the docker images to install owncloud from tar ball as well as from github branches

**Comment by jmaciasportela** [comment]
I have explained to @jvillafanez how to use the now docker images to deploy specific PR/Branches. 
Now docker images are ready to use with Mysql, Sqlite and pgSQL. Do you need oracle also?

**Comment by rullzer** [comment]
Yes oracle as well please... since I don't trust it to behave in any situation...

**Comment by jvillafanez** [comment]
I'll be updating the info...

Tests are for ubuntu 14.04 and PHP 5.5.9, updating from stable8.2 to this dbal-2.5.6 branch (git-based upgrade)

MySQL | postgresQL | sqlite | oracle
:---------: | :---------------: | :-------: | :----------:
:white_check_mark: | :white_check_mark: | :question: | :question:

**Comment by DeepDiver1975** [comment]
THX @jvillafanez

**Comment by jvillafanez** [comment]
@jmaciasportela any chance of having a docker image with oracle and the support for git? I think the one we have doesn't have git support...

No docker, no fun.

**Comment by jmaciasportela** [comment]
Yes I'm working on it, I have problems with offline instalation.

Hope to fix it soon

2015-10-28 11:30 GMT+01:00 Juan Pablo Villafañez <notifications@github.com>:

> @jmaciasportela <https://github.com/jmaciasportela> any chance of having
> a docker image with oracle and the support for git? I think the one we have
> doesn't have git support...
>
> No docker, no fun.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/pull/20045#issuecomment-151794470>.
>



-- 
<http://solidgear.es/email_footers/small/jmacias.png>

*P* Antes de imprimir este mensaje, por favor, compruebe que es
verdaderamente necesario. El medioambiente es cosa de todos. Before
printing think about your responsibility & commitment with the Environment!

Este mensaje se dirige exclusivamente a su destinatario y puede contener
información privilegiada o confidencial. Si no es vd. el destinatario
indicado, queda notificado de que la lectura, utilización, divulgación y/o
copia sin autorización está prohibida en virtud de la legislación vigente.
Si ha recibido este mensaje por error, le rogamos que nos lo comunique
inmediatamente por esta misma vía y proceda a su destrucción.

El correo electrónico vía Internet no permite asegurar la confidencialidad
de los mensajes que se transmiten ni su integridad o correcta recepción.
Solid Gear no asume ninguna responsabilidad por estas circunstancias.

This message is intended exclusively for its addressee and may contain
information that is CONFIDENTIAL and protected by a professional privilege
or whose disclosure is prohibited by law. If you are not the intended
recipient you are hereby notified that any read, dissemination, copy or
disclosure of this communication is strictly prohibited by law. If this
message has been received in error, please immediately notify us via e-mail
and delete it.

Internet e-mail neither guarantees the confidentiality nor the integrity or
proper receipt of the messages sent. Solid Gear does not assume any
liability for those circumstances.

**Comment by jmaciasportela** [comment]
docker oracle image is ready to test

**Comment by jvillafanez** [comment]
It needs confirmation, but the upgrade crashes with oracle during the upgrade. ownCloud works fine before the upgrade.

```
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: ' in /opt/owncloud/lib/private/db/connection.php:52
Stack trace:
#0 /opt/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(973): OC\DB\Connection->connect()
#1 /opt/owncloud/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('SET TRANSACTION...', Array, Array)
#2 /opt/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): OC\DB\Connection->executeUpdate('SET TRANSACTION...')
#3 /opt/owncloud/lib/private/db/connection.php(135): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#4 /opt/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\OCI8\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#5 /opt/owncloud/lib/private/db/connectionfactory.php(118): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /opt/owncloud/lib/private/server.php(327): OC\DB\ConnectionFactory->getConnection('oci', Array)
#7 /opt/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#8 /opt/owncloud/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('DatabaseConnect...')
#9 /opt/owncloud/lib/private/server.php(762): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#10 /opt/owncloud/lib/private/db.php(42): OC\Server->getDatabaseConnection()
#11 /opt/owncloud/lib/private/server.php(235): OC_DB::getConnection()
#12 /opt/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#13 /opt/owncloud/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('AppConfig')
#14 /opt/owncloud/lib/private/server.php(701): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#15 /opt/owncloud/lib/private/server.php(372): OC\Server->getAppConfig()
#16 /opt/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#17 /opt/owncloud/lib/private/appframework/utility/simplecontainer.php(104): Pimple\Container->offsetGet('AppManager')
#18 /opt/owncloud/lib/private/server.php(928): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#19 /opt/owncloud/lib/private/app.php(259): OC\Server->getAppManager()
#20 /opt/owncloud/lib/private/app.php(104): OC_App::getEnabledApps()
#21 /opt/owncloud/lib/base.php(567): OC_App::loadApps(Array)
#22 /opt/owncloud/lib/base.php(1082): OC::init()
#23 /opt/owncloud/console.php(42): require_once('/opt/owncloud/l...')
#24 /opt/owncloud/occ(11): require_once('/opt/owncloud/c...')
```

Logs
```
{"reqId":"ASJ7t3W377uzMM0BV59n","remoteAddr":"::1","app":"PHP","message":"fopen(\/opt\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/opt\/owncloud\/lib\/private\/config.php#188","level":3,"time":"2015-10-28T16:12:14+00:00"}
{"reqId":"z7+0tCmtCi467ITWfXuP","remoteAddr":"","app":"PHP","message":"oci_connect(): Error while trying to retrieve text for error ORA-01804\n at \/opt\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/OCI8\/OCI8Connection.php#63","level":3,"time":"2015-10-28T16:13:56+00:00"}
```

**Comment by DeepDiver1975** [comment]
Is the Oracle Server gone?

**Comment by jvillafanez** [comment]
I've checked in another environment to discard a possible issue with the space (I had the disk almost full after the test), but the result is the same.

The oracle server should be up because I've been able to connect to the DB after the test. I don't have any explanation of how the server could be down (if that's the reason of the failure). In addition, smashbox tests were run before doing the upgrade, so there is connectivity to the DB at least until the time the upgrade is done.

**Comment by DeepDiver1975** [comment]
ORA-01804: failure to initialize timezone information in DB11.2.0.4
https://community.oracle.com/message/12523423

I honestly consider this a environment specific issue - regular unit test on oci do succeed

**Comment by rullzer** [comment]
> I honestly consider this a environment specific issue - regular unit test on oci do succeed

Agreed. So do we want to fix the enviroment and check again? Or just merge this?

**Comment by DeepDiver1975** [comment]
@rullzer please update submodule - THX

**Comment by rullzer** [comment]
Rebased

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
