### PR TITLE
Expand occ user reset password email validation

### PR DESCRIPTION
**Pull request by settermjd**
## Description

Improves the email address validation performed when running `occ user:resetpassword --email-link`.

## Related Issue

- Extends https://github.com/owncloud/core/pull/32345
- Relates to https://github.com/owncloud/core/issues/29542

## Motivation and Context

When I was documenting the changes that https://github.com/owncloud/core/pull/32345 made, I found that when running `occ user:resetpassword --email-link`, an error message is displayed only if a user's password is `null`. However, if it was an empty string, then the error would not be thrown and the code would attempt to send an email using the invalid email address. 

I created these changes to ensure that only valid email addresses are able to be used.

:information_desk_person: fwiw, I'm not totally sure that using a [Zend\Validator\EmailAddress](https://docs.zendframework.com/zend-validator/validators/email-address/) object directly is the best approach.

## How Has This Been Tested?

- Updated the covering tests and ensured that they all passed.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests

## Checklist:

- [X] Code changes
- [X] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [X] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@settermjd please backport

**Comment by phil-davis** [comment]
@settermjd did a backport happen?
There is no reference here, and the backport-request label is still on.

**Comment by phil-davis** [comment]
@settermjd @PVince81 I don't see any backport for this???

**Comment by phil-davis** [comment]
Backport ``stable10`` #33945

**Comment by settermjd** [comment]
Thanks for backporting @phil-davis.

**Comment by davitol** [comment]
@settermjd Those are the options available for user:resetpassword commnand

```
occ user:resetpassword --help
Usage:
  user:resetpassword [options] [--] <user>

Arguments:
  user                     The user's name.

Options:
      --password-from-env  Read the password from the OC_PASS environment variable.
      --send-email         The email-id set while creating the user, will be used to send link for password reset. This option will also display the link sent to user.
      --output-link        The link to reset the password will be displayed.
  -h, --help               Display this help message
  -q, --quiet              Do not output any message
  -V, --version            Display this application version
      --ansi               Force ANSI output
      --no-ansi            Disable ANSI output
  -n, --no-interaction     Do not ask any interactive question
      --no-warnings        Skip global warnings, show command output only
  -v|vv|vvv, --verbose     Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Resets the password of the named user.
```

In the OP it says run command ```occ user:resetpassword --email-link``` . Can you please clarify me if it is the command I should run? Thanks in advance.

**Pull request merged**
