### PR TITLE
[user_ldap] properly decode cached objects

### LINKED ISSUE #21896: Sharing with LDAP Users not working on subsequent attempts when cache is enabled
### Steps to reproduce
1. Having cache enabled: APCu 4.0.7, Redis 2.2.7 
2. Trying to share some files/folders with an LDAP User
2. When typing the first letters of the Username, User is being correctly found on the first attempt
3. However, when deleting the letters and searching again for the same User, this cannot be found and the search seems to be stuck
4. This only happens when cache is enabled

### Expected behaviour

LDAP User should also be found on the second attempt

### Actual behaviour

See above

### Server configuration
**Operating system**:

Debian Jessie

**Web server:**

Apache 2.4

**Database:**

Percona XtraDB 5.6.27

**PHP version:**

5.6

**ownCloud version:** (see ownCloud admin page)

8.2.2

**Updated from an older ownCloud or fresh install:**

Fresh install

**Are you using external storage, if yes which one:** local/smb/sftp/...

local

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

@MorrisJobke can you maybe help here?

00004656

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #21896 

cc @LukasReschke @blizzz 

Alternative to https://github.com/owncloud/core/pull/21998

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I just tested locally and it works. :)

**Comment by blizzz** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@nickvergessen Mind to review?

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
@MorrisJobke please state your backport versions

**Comment by MorrisJobke** [comment]
stable8.2: #22040 
stable8.1: there it isn't a problem because unserialize was used: https://github.com/owncloud/core/blob/stable8.1/apps/user_ldap/lib/connection.php#L209

**Pull request merged**
