### PR TITLE
Process null app config value

### LINKED ISSUE #39553: occ config:app:set stores an empty string that cannot be overwritten when called without --value
Seen in 10.9.0 beta1 

```
# occ config:app:delete foo bar
# occ config:app:set foo bar
Config value bar for app foo set to 
# occ config:app:get foo bar

# occ config:app:set foo bar --value='hammer'
Config value bar for app foo set to hammer
# occ config:app:get foo bar

#
```

The second `set` command reports that it did set the value to `hammer`, but in reality it failed.

Expected behaviour:
* Invoking config:app:set without --value should print a syntax error.
* Correct commands that fail should print an error, not a success message.

Workaround: `occ config:app:delete foo bar`

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
An app config value that is set to null can now be updated to a not-null value, for example, with the occ config:app:set command.

Note: when Oracle stores an app config value of the empty string '' it actually stores `null` and returns `null`. Trying to update the value from `null` to the empty string in Oracle results in no-change. I expanded the unit tests so that they demonstrate this difference.

This PR is an alternative to #39554 - which changes the interface to set/get config values so that `null` is not an available setting, and any current uses of `null` become the empty string.

"someone"  (tm) needs to decide which PR to approve.

## Related Issue
- Fixes #39553 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiOnSqlite-sqlite-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33953/178/1

**Comment by mmattel** [comment]
Is this docs relevant?

**Comment by phil-davis** [comment]
> Is this docs relevant?

It fixes an existing bug - when an app config value was set to `null` (usually accidentally) then it could not be updated with the `occ config:app:set` command. So for that, there is no need to change documentation - the system will now work as it should.

Investigation here has uncovered the fact that an app config value cannot be set to the empty string on Oracle (Oracle turns that into `null`) I have no idea if that should be documented! I can't think of any actual app where a config value needs to differentiate between `null` and "".

**Comment by phil-davis** [comment]
The solution in #39554 was chosen and merged.

**Pull request closed without merging**
