### PR TITLE
[stable10] Kill a route to removed script

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #29549 to stable10

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@gitmate-bot rebase

**Comment by sils** [comment]
@DeepDiver1975 rebase

**Comment by sils** [comment]
@nkprince007 can you check sentry and the code? Something is wrong here, I think this is on our end.

**Comment by sils** [comment]
@DeepDiver1975 sorry for this, this is really emberassing - we're lowering the comment text to get rid of all casing issues but we're not lowering the username. Since your user contains upper case characters it doesn't work. Here's a fix: https://gitlab.com/gitmate/open-source/gitmate-2/merge_requests/345

**Comment by sils** [comment]
@DeepDiver1975 rebase

**Comment by DeepDiver1975** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by DeepDiver1975** [comment]
Automated rebase was successful!

**Comment by DeepDiver1975** [comment]
@owncloud-bot rebase

**Comment by tboerger** [comment]
@DeepDiver1975 please use @ownclouders for that :)

**Pull request merged**
