### PR TITLE
Maintenance mode message might be misleading

### LINKED ISSUE #14627: maintenance message is misleading
If the ownCloud maintenance mode is switched on the webpage says: "This ownCloud is currently upgraded...." The admin might think that an upgrade is happening at the moment. But it is not.
We should change this to something more neutral like: "This ownCloud is currently in maintenance mode, ...."

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #14627

@karlitschek @RealRancor @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by nickvergessen** [comment]
That is why we have `Contact your system administrator if this message persists or appeared unexpectedly.` two lines bellow?

**Comment by RealRancor** [comment]
Ah, yes. You're right. Hopefully this change will point the users to the right direction.

**Comment by karlitschek** [comment]
nice :+1:  a backport would be great :-)

**Comment by nickvergessen** [comment]
Will prepare a backport after 8.0.1 so translations can be backported in time

**Pull request merged**
