### PR TITLE
German Typo

### PR DESCRIPTION
**Pull request by nerdoc**

### CODE REVIEW

**Comment by nerdoc** [comment]
Sorry, the newline at file end at the second commit was added by the github editor.

**Comment by LukasReschke** [comment]
THX for that fix. But translations are handled via transifex, see https://github.com/owncloud/core#important-notice-on-translations

**Comment by nerdoc** [comment]
Oh, sorry. I'll do that there.

**Comment by LukasReschke** [comment]
Awesome. Thank you, @nerdoc 🚀

**Comment by nerdoc** [comment]
Done. ;-)

**Pull request closed without merging**
