### PR TITLE
Give ceph more time ....

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@Xenopathic mind taking a look?


````
12:03:18 Digest: sha256:8692356f6d96002522dccf9d742329df2ff67e26e8a5820941c4bfb937e36038
12:03:18 Status: Image is up to date for xenopathic/ceph-keystone:latest
12:03:18 xenopathic/ceph-keystone container: af623d0494eadde074cbbb8942cde152aac70c28d43fc19029a616dc54b77931
12:03:18 Waiting for ceph initialization................................................................................................................................................................................
12:13:18 [ERROR] Waited 600 seconds, no response
12:13:18 creating /etc/ceph/ceph.client.admin.keyring
12:13:18 creating /etc/ceph/ceph.mon.keyring
12:13:18 monmaptool: monmap file /etc/ceph/monmap
12:13:18 monmaptool: set fsid to 9e3139f9-b2bb-443a-863a-96dbcb473fc1
12:13:18 monmaptool: writing epoch 0 to /etc/ceph/monmap (1 monitors)
12:13:18 creating /tmp/ceph.mon.keyring
12:13:18 importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
12:13:18 importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
12:13:18 ceph-mon: set fsid to 9e3139f9-b2bb-443a-863a-96dbcb473fc1
12:13:18 ceph-mon: created monfs at /var/lib/ceph/mon/ceph-af623d0494ea for mon.af623d0494ea
12:13:18 2015-12-09 17:03:13.549083 7f8992781700  1 -- :/0 messenger.start
12:13:18 2015-12-09 17:03:13.549278 7f8992781700  1 -- :/1000049 --> 172.17.0.196:6789/0 -- auth(proto 0 30 bytes epoch 0) v1 -- ?+0 0x7f8988023a00 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.549440 7f89817fa700  1 -- 172.17.0.196:0/1000049 learned my addr 172.17.0.196:0/1000049
12:13:18 2015-12-09 17:03:13.552644 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 1 ==== mon_map magic: 0 v1 ==== 202+0+0 (2433050981 0 0) 0x7f8978000ac0 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.552689 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 2 ==== auth_reply(proto 2 0 (0) Success) v1 ==== 33+0+0 (505382853 0 0) 0x7f8978000f90 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.552761 7f8983fff700  1 -- 172.17.0.196:0/1000049 --> 172.17.0.196:6789/0 -- auth(proto 2 32 bytes epoch 0) v1 -- ?+0 0x7f896c001330 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.552968 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 3 ==== auth_reply(proto 2 0 (0) Success) v1 ==== 206+0+0 (961188987 0 0) 0x7f8978000f90 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553026 7f8983fff700  1 -- 172.17.0.196:0/1000049 --> 172.17.0.196:6789/0 -- auth(proto 2 165 bytes epoch 0) v1 -- ?+0 0x7f896c001d00 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553216 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 4 ==== auth_reply(proto 2 0 (0) Success) v1 ==== 393+0+0 (2481373767 0 0) 0x7f8978000f90 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553259 7f8983fff700  1 -- 172.17.0.196:0/1000049 --> 172.17.0.196:6789/0 -- mon_subscribe({monmap=0+}) v2 -- ?+0 0x7f89880296d0 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553300 7f8992781700  1 -- 172.17.0.196:0/1000049 --> 172.17.0.196:6789/0 -- mon_subscribe({monmap=2+,osdmap=0}) v2 -- ?+0 0x7f8988023a00 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553331 7f8992781700  1 -- 172.17.0.196:0/1000049 --> 172.17.0.196:6789/0 -- mon_subscribe({monmap=2+,osdmap=0}) v2 -- ?+0 0x7f8988029db0 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553392 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 5 ==== mon_map magic: 0 v1 ==== 202+0+0 (2433050981 0 0) 0x7f8978001230 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553416 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 6 ==== mon_subscribe_ack(300s) v1 ==== 20+0+0 (474813950 0 0) 0x7f89780014f0 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553504 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 7 ==== osd_map(1..1 src has 1..1) v3 ==== 855+0+0 (3862622644 0 0) 0x7f8978001290 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553552 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 8 ==== mon_subscribe_ack(300s) v1 ==== 20+0+0 (474813950 0 0) 0x7f8978001710 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553560 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 9 ==== osd_map(1..1 src has 1..1) v3 ==== 855+0+0 (3862622644 0 0) 0x7f8978001db0 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.553595 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 10 ==== mon_subscribe_ack(300s) v1 ==== 20+0+0 (474813950 0 0) 0x7f8978000f30 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.556015 7f8992781700  1 -- 172.17.0.196:0/1000049 --> 172.17.0.196:6789/0 -- mon_command({"prefix": "get_command_descriptions"} v 0) v1 -- ?+0 0x7f8988016b40 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.557093 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 11 ==== mon_command_ack([{"prefix": "get_command_descriptions"}]=0  v0) v1 ==== 72+0+35141 (1092875540 0 2917257709) 0x7f8978001a70 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.592885 7f8992781700  1 -- 172.17.0.196:0/1000049 --> 172.17.0.196:6789/0 -- mon_command({"var": "size", "prefix": "osd pool set", "pool": "rbd", "val": "1"} v 0) v1 -- ?+0 0x7f8988016b40 con 0x7f8988023e30
12:13:18 2015-12-09 17:03:13.597492 7f8983fff700  1 -- 172.17.0.196:0/1000049 <== mon.0 172.17.0.196:6789/0 12 ==== mon_command_ack([{"var": "size", "prefix": "osd pool set", "pool": "rbd", "val": "1"}]=0 set pool 0 size to 1 v2) v1 ==== 122+0+0 (3471761803 0 0) 0x7f8978001070 con 0x7f8988023e30
12:13:18 set pool 0 size to 1
12:13:18 2015-12-09 17:03:13.601163 7f8992781700  1 -- 172.17.0.196:0/1000049 mark_down 0x7f8988023e30 -- 0x7f898802d010
12:13:18 2015-12-09 17:03:13.601206 7f8992781700  1 -- 172.17.0.196:0/1000049 mark_down_all
12:13:18 2015-12-09 17:03:13.601275 7f8992781700  1 -- 172.17.0.196:0/1000049 shutdown complete.
12:13:18 creating osd storage image
12:13:18 100+0 records in
12:13:18 100+0 records out
12:13:18 104857600 bytes (105 MB) copied, 0.0400687 s, 2.6 GB/s
12:13:18 Turning ON incompat feature 'mixed-bg': mixed data and metadata block groups
12:13:18 Turning ON incompat feature 'extref': increased hardlink limit per file to 65536
12:13:18 SMALL VOLUME: forcing mixed metadata/data groups
12:13:18 
12:13:18 WARNING! - Btrfs v3.12 IS EXPERIMENTAL
12:13:18 WARNING! - see http://btrfs.wiki.kernel.org before using
12:13:18 
12:13:18 Created a data/metadata chunk of size 8388608
12:13:18 fs created label (null) on /tmp/osddata
12:13:18 	nodesize 4096 leafsize 4096 sectorsize 4096 size 100.00MiB
12:13:18 Btrfs v3.12
12:13:18 mounting via loopback
12:13:18 mount: Could not find any loop device. Maybe this kernel does not know
12:13:18        about the loop device? (If so, recompile or `modprobe loop'.)
12:13:18 stop: stop-swift-ceph.sh
12:13:18 Docker executable found - stop and remove docker containers
12:13:18 Stopping and removing docker container af623d0494eadde074cbbb8942cde152aac70c28d43fc19029a616dc54b77931
12:13:18 af623d0494eadde074cbbb8942cde152aac70c28d43fc19029a616dc54b77931
12:13:18 rm: cannot remove ‘./../apps/files_external/tests//config.swift.php’: No such file or directory
12:13:18 Error during start file execution ... terminating
12:13:18 Build step 'Execute shell' marked build as failure
12:13:18 Recording test results
12:13:28 Finished: FAILURE

**Comment by Xenopathic** [comment]
@DeepDiver1975 That's the Btrfs logic running, from the entrypoint.sh you used in the other PR.

**Comment by DeepDiver1975** [comment]
> That's the Btrfs logic failing,

that much I'm getting as well :wink:

**Comment by DeepDiver1975** [comment]
> from the entrypoint.sh you used in the other PR.

This PR is using the plain docker image ... no additional entrypoint.sh

**Comment by Xenopathic** [comment]
> This PR is using the plain docker image ... no additional entrypoint.sh

...which now uses the entrypoint.sh that was supplied from the other PR, including the btrfs loopback thing.

**Comment by DeepDiver1975** [comment]
> ...which now uses the entrypoint.sh that was supplied from the other PR, including the btrfs loopback thing.

but fail compared to the other PR/master ... so where is the issue?

**Comment by PVince81** [comment]
Not following... where's the issue ? @Xenopathic

**Comment by DeepDiver1975** [comment]
we have a working solution in place -> close

**Pull request closed without merging**
