### PR TITLE
Update version to 8.2 in README and bower

### PR DESCRIPTION
**Pull request by PVince81**
- [x] requires documentation to be available here: https://doc.owncloud.org/server/8.2/developer_manual/ (CC @carlaschroder)

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> requires documentation to be available here: https://doc.owncloud.org/server/8.2/developer_manual/ (CC @carlaschroder)

we shall open an issue in the documentation repo

**Comment by PVince81** [comment]
I shall

**Comment by PVince81** [comment]
Raised as https://github.com/owncloud/documentation/issues/1289

**Comment by DeepDiver1975** [comment]
> Raised as owncloud/documentation#1289

THX

**Pull request merged**
