### PR TITLE
Only hard depend on the info.xml and not the app.php

### LINKED ISSUE #14959: Apps that do not ship an app.php are not listed on the page where you can enable apps
appinfo/app.php should be fully optional

@DeepDiver1975 @nickvergessen @MorrisJobke @jbtbnl @PVince81 @LukasReschke

### PR DESCRIPTION
**Pull request by BernhardPosselt**
Fix #14959

@MorrisJobke @DeepDiver1975 @nickvergessen @LukasReschke @PVince81

### CODE REVIEW

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/blob/9c45ab49a152545991ec324bfdc4f41292e91bad/lib/private/app.php#L62-L64 needs fixing aswell?

**Comment by Raydiation** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
:+1:

**Comment by karlitschek** [comment]
makes sense :+1:

**Pull request merged**
