### PR TITLE
feat: php 8.2

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## TODO
- [ ] migrate SwiftMailer to Symfony mail - https://github.com/owncloud/core/pull/41009
- [x] drop opis/closure - use laravel/serializable-closure

## Not in scope of this PR
- [ ] upgrade to phpunit 10.x

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
@DeepDiver1975 CI is working - I will leave you to look at the various things reported by phan, phpstan etc.
Ping if you want any input from me.

**Comment by DeepDiver1975** [comment]
cleaning up - I think this is no longer of anybody's interest

**Comment by hellwolf** [comment]
> no longer of anybody's interest

correction: no longer of interest of anybody from owncloud.

This is just infuriatingly, I guess I have just been a sucker that haven't prioritized the migration away from owncloud a priority.

Fwiw, I am also the packager of owncloud-client on nixpkgs.

This spells the end of this thing. But I guess that's what owncloud wanted!

**Comment by DeepDiver1975** [comment]
> This spells the end of this thing. But I guess that's what owncloud wanted!

The end of owncloud 10 was marked by the time all forces have been moved to infinite scale. It was quite obvious in all these years. Not really shocking - right?

**Comment by hellwolf** [comment]
That itself was not shocking.

The fact that this branch existed and now abandoned signals some change that you folks have all the rights to reserve to yourself. I get that, I guess many people get that. But that's the trust eroded that you won't get back anytime soon.

**Comment by iasdeoupxe** [comment]
Was it really that obvious? At least not for PHP 8.x support (https://github.com/owncloud/core/issues/40241#issuecomment-1693202976 from August 2023):

> No need to continue in here. PHP 8.x will come these days....

And even if it was "that obvious" for the ownCloud team it wasn't obviously for the community, how should we as users know such stuff like:

> by the time all forces have been moved to infinite scale

Why not just communicate things like this correctly and just disclose the plans from your side? There was not a single real announcement from ownCloud.

How this whole topic was handled from ownCloud side is so awkward / terrible and so frustrating, i can bite into my ass that i have put trust into ownCloud.

If you can't handle an open source project with the responsibility coming from it like transparent communication then just make your product closed source and don't keep it open in such a pseudo open source way.

Farewell ownCloud, time to vanish.

**Pull request closed without merging**
