### PR TITLE
apps/files: Fix typos in comments (found and fixed by codespell)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil sw@weilnetz.de

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by stweil** [comment]
PR updated, commit message now includes a license statement.

**Comment by stweil** [comment]
Any of my contributions to this repository may be used under MIT license.

Do I have to add such a statement each time I make a PR (if I don't sign the contributor agreement)?
I noticed that sometimes the commit message includes a license statement, but obviously that statement is ignored by the owncloud-bot.

**Pull request merged**
