### PR TITLE
Add some generic default headers as well via PHP

### PR DESCRIPTION
**Pull request by LukasReschke**
@karlitschek As discussed.
## TODO
- [x] Add some basic security docs  (https://github.com/owncloud/documentation/pull/989)
- [x] Adjust the text for the warning in case of some headers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Thanks for the intendation :)

**Comment by LukasReschke** [comment]
@karlitschek @MorrisJobke @nickvergessen Please review. THX :smile:

**Comment by LukasReschke** [comment]
```
12:36:48 Installing ....
12:36:51 ownCloud is not installed - only a limited number of commands are available
12:36:52 Oracle connection could not be established
12:36:52  -> ORA-01033: ORACLE initialization or shutdown in progress Check environment: ORACLE_HOME=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server ORACLE_SID=XE LD_LIBRARY_PATH=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/lib: NLS_LANG=AMERICAN_AMERICA.AL32UTF8 tnsnames.ora is readable
```

:question:

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> :question:

docker was not up and running .... kind of ignorisch :speak_no_evil:

**Comment by MorrisJobke** [comment]
There is a problem :-1: (just kidding)

**Comment by nickvergessen** [comment]
:-1:

**Comment by LukasReschke** [comment]
Cybermobbing! :cry:

**Comment by PVince81** [comment]
:+1: works

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by PeterPablo** [comment]
There indeed can be a problem if [this line](https://github.com/owncloud/core/pull/15225/files#diff-8052c42ab3b8aa06a3f5f788a4ddccc2R12) is not being exectued due to `mod_env` being absent. This can happen on a shared hoster (e.g. [Speicherzentrum.de](https://speicherzentrum.de)) and yields to the problem described in the [forums](https://forum.owncloud.org/viewtopic.php?t=29338&p=92262#p91875) on Chrom(e|ium):
`Refused to execute script from 'xxx' because its MIME type ('text/x-js') is not executable, and strict MIME type checking is enabled. `

I ran into this issue and asked the support to enable the module. OwnCloud 7 ran fine.

**Pull request merged**
