### PR TITLE
Disallow Windows Server in Server Check

### PR DESCRIPTION
**Pull request by LukasReschke**
Will prevent users from using ownCloud on Windows Server :see_no_evil:

First step…

@DeepDiver1975 @karlitschek @MTRichards @nickvergessen

### CODE REVIEW

**Comment by LukasReschke** [comment]
Reasons that speak for a hard vs. soft-fail:

1. Users ignore soft-fails, see the OS X thing. Would still get us ton of annoyed users and reports. Better to piss them off once ("It does not work") instead of ("Your files are now gone").
2. Nobody here develops on Windows and things explode really big there. While on OS X we have at least some devs using it.

**Comment by LukasReschke** [comment]
Also would allow us to get rid of a lot of hacks in the code-base…

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MTRichards** [comment]
Agree for Subscriptions, just not 100% for community. 
@DeepDiver1975 @karlitschek thoughts?

**Comment by LukasReschke** [comment]
Well… The problem is that if we claim to support something but actually don't test this at all nor have unit tests for it we should not offer it.

Windows Support on 8.0 is *horrible* broken, broken as in: Our users complained that you can't even save files in most scenarios. And we didn't notice.

I'm all in for being honest instead of having even more angry users ;-)

**Comment by nickvergessen** [comment]
We really need a "Yes or No" here, not CE/EE/whatever only decision.
Either we fix the Filesystem all the way down, then we can use it for all, or we don't then we should not allow it at all.

**Comment by karlitschek** [comment]
Let´s talk about this at the next developer meeting in nürnberg. this is a bigger topic. Thanks

**Comment by DeepDiver1975** [comment]
scheduling this for 8.1 - would be great to get a final decision before the release

Personal opinion:
A hard warning/failure is the right way to go - in order to continue people to work/test/use/develop they can uncomment he check in the code.

As a hard fact we need to be strict with bug reports on windows as well: close them all!

**Comment by bantu** [comment]
This seems to be Windows in general, not only "Windows Server".

**Comment by bantu** [comment]
http://windows.php.net/download#php-5.6:

> The x64 builds of PHP for Windows should be considered experimental, and do not yet provide 64-bit integer or large file support.

This means that we can not support files larger than 2/4 GiB right now.

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2015-03-30 08 49 09

**Comment by jospoortvliet** [comment]
:+1: a little poll on our social media show >97% of our (vocal...) users use Linux or can move to it if needed. Not worth keeping 'support' for something we actually don't support and clear communication is a better way of dealing than just warning.

One thing: for the text, I suggest to add: Find Linux packages as well as easy to deploy virtual machine images on owncloud.org/install
(reading this message will be frustrating. We should make sure we offer a way out of that frustration right there and then rather than lose the potential user. Better wording or a better link is welcome of course)

**Comment by DeepDiver1975** [comment]
@karlitschek please choose the next step
- [ ] merge
- [ ] don't merge
@LukasReschke can I ask you to update the text

**Comment by LukasReschke** [comment]
> @LukasReschke can I ask you to update the text

If we already go that route I'd welcome a blog post that explains how to migrate to a Linux system and we can link to that then here. Otherwise it's like "have fun setting up everything again and loose all your data"…

**Comment by karlitschek** [comment]
This is good. But we need a few more days to communicate this properly. Like with a blog post as @LukasReschke said.

**Comment by RealRancor** [comment]
Hi,

additional to the blogpost also consider: https://github.com/owncloud/updater/issues/107

Don't want to know how many users are not reading either the blogpost or the release notes and just click "update". :see_no_evil:

**Comment by karlitschek** [comment]
agreed. We need a proper warning

**Comment by ev0lister** [comment]
Really sad to have the support dropped. Would mabye make sense to also point to docu howto migrate to Linux? Otherwise there might arise questions regarding this..

**Comment by LukasReschke** [comment]
Okay, I propose the following:

`Running ownCloud is unsupported on Windows Server and due to data loss problems not anymore possible since ownCloud 8.1. Find Linux packages as well as easy to deploy virtual machine images on <a href="%s">%s</a>. For migrating existing installations to Windows you can find some tips on <a href="%s">our blog</a>.` - the first link goes to owncloud.org/install,  the second one would go to a blog post of us explaining why we dropped Windows support and what the next steps are? – Though that requires that we actually want to write such a post… If nobody volunteers to do it I can get something ready over the next week (obviously with @jospoortvliet helping me on the "making it sound nice" ;-)) and then we can review and publish it before we release 8.1…

That would move the links out of l10n so that we can adjust it later without having a final blog post yet. 

@karlitschek @jospoortvliet @DeepDiver1975 What do you think?

**Comment by LukasReschke** [comment]
(will adjust the PR once we have settled on something)

**Comment by jospoortvliet** [comment]
@LukasReschke a post about ending Windows support is done and currently being reviewed by Kait ;-)

I will send it to you for input.

The notification should be worded more like this:
Running ownCloud Server on the Microsoft Windows platform is not supported. We suggest you use a Linux server in a virtual machine if you have no option for migrating the server itself. Find Linux packages as well as easy to deploy virtual machine images on <a href="%s">%s</a>. For migrating existing installations to Windows you can find some tips and a migration script on <a href="%s">our blog</a>.

First link should simply be owncloud.org/install and the second will be https://owncloud.org/?p=8045

**Comment by LukasReschke** [comment]
That we can do. Awesome. Thanks :smile:

**Comment by LukasReschke** [comment]
Reworded and rebased. Awaiting reviews please.

**Comment by jospoortvliet** [comment]
I can't check the code but :+1: on the text.

**Comment by nickvergessen** [comment]
fine by me :+1:

**Comment by karlitschek** [comment]
Fine with me. Two small things:
- I wouldn´t say "data loss problems" but "instability of PHP on Windows"
- Not sure we should link to a blog post. Seems a bit strange. Can we have the information also in the documentation and link to that?
Beside that :+1:

**Comment by LukasReschke** [comment]
> Not sure we should link to a blog post. Seems a bit strange. Can we have the information also in the documentation and link to that? Beside that :+1:

Sure… If we have a page in the documentation regarding that we can link to that.

So what about rephrasing the last sentence to `For migrating existing installations to Windows you can find some tips and a migration script on our <a href="%s">documentation</a>.`, the link we can always adjust this way.

**Comment by LukasReschke** [comment]
So for the documentation this means https://doc.owncloud.org/server/8.1/admin_manual/installation/windows2_installation.html and https://doc.owncloud.org/server/8.1/admin_manual/installation/windows_installation.html has to go away.

@carlaschroder Ideas where a nice small page with some information about the fact that we do not support Windows anymore and so on might be best located?

**Comment by DeepDiver1975** [comment]
@karlitschek we are waiting for the blog to be released or merge now as we enter freeze?

**Comment by karlitschek** [comment]
I would merge now. We can add the link later.

**Comment by LukasReschke** [comment]
Rebased again… Last Jenkins round then before merging :rocket:

**Comment by carlaschroder** [comment]
@Lukas, the 'What's New' and 'Release Notes' pages in the Admin manuals are the usual places for announcements like this, though dropping Windows support needs to be mentioned and discussed in multiple locations. (Dropping Windows support is, IMNSHO, a wise move.)

Regarding migrating ownCloud from Windows to Linux-- the existing installation docs, especially the ones for installing & maintaining ownCloud from the oBS and EE repos,  are fine for new Linux installations, assuming the user has basic Linux knowledge. I can whip up a special introduction doc for Windows immigrants that points to appropriate docs, with a place for adding tips and tricks.

Migration is a more difficult problem-- you nice smart people will have to help me with that. As I understand it, it's more complicated to migrate ownCloud DBs than just doing routine dumps & imports.

What about 8.0? It's already in the release notes that running an ownCloud server on Windows Server is not supported in 8.0. Shall we make it a clean sweep and say no ownCloud server on any version of Windows starting with 8.0?

**Comment by jospoortvliet** [comment]
@carlaschroder so the plan is that Thomas makes or oversees the making of an 'export script' which gets all user data out of ownCloud. Not sure if that will include sharing data, favorites and such. In any case, it won't be a flat-out database migration (and I think that that would be scary, risky and error prone as well as beneficial to only a few people anyway).

**Comment by DeepDiver1975** [comment]
The script I have in mind will export files only. This is the critical part because file names are modified and users want the true nanes in thieir files.

**Comment by RealRancor** [comment]
Some raging at the forums about the dropped windows support: https://forum.owncloud.org/viewtopic.php?f=31&t=27449&p=84753#p84751

You have to fix "your code" instead of dropping windows support. :speak_no_evil:

**Comment by LukasReschke** [comment]
Well, said users can just open the pocket and throw money at ownCloud Inc. to actually hire full-time developers for Windows support. Or they fix it themselves. If they don't do neither of that, well then it gets hard ;-)

Besides that: It's open-source, we don't have signed some contract with the devil to support Windows forever ;-)

Closing this one before the users appear in here :see_no_evil:

**Comment by karlitschek** [comment]
We should make clear in our communication that it is possible to bring this feature back IF someone takes over the maintainance of the Windows support and implements all the needed workarounds.
It´s not true that the fore developer don´t LIKE the feature. It is just that is doesn´t work at the moment and no one volunteered to look into it.
@jospoortvliet

**Comment by LukasReschke** [comment]
Also we should link to https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule#overview to make sure that people will understand that 8.0 is planned to receive security updates until Q4 2016. So they actually have quite some time to plan a migration and there is no need to panic right away… Though the bugs will still be present and nobody will really fix them but at least they can run it.

In IRC there is often a misunderstanding about which versions we support officially.

**Comment by jospoortvliet** [comment]
Ok on both last points, will do.

**Comment by jospoortvliet** [comment]
Added a final paragraph:

    We want to emphasize that we do not drop support for Windows Server out of
    dislike–rather, we feel forced to. ownCloud Server does not work reliably on the Windows 
    platform and nobody has stepped up to fix the problems. We urge those of you impacted by
    this change to consider your options. Aside from migration, if enough people step up to
    fix the bugs related to Windows Server support in ownCloud 8 and commit to supporting
    ownCloud on Windows, there is no reason not to bring a future release
    back to Windows Server.

Feedback always welcome.

**Comment by karlitschek** [comment]
Sounds good. 
@carlaschroder @LukasReschke @DeepDiver1975 What do you think?

**Comment by carlaschroder** [comment]
Well I don't like Windows and the whole MS software stack because it's a terrible pile of overpriced underperforming non-secureable junk. Jos' wording is fine, though, no need to change it. Not sure it will decrease Windows user unhappiness, but it does add clarity and a proposed solution. 

Is it feasible to distribute native Hyper-V images of ownCloud on a Linux guest?  Also, how about making Hyper-V images of oC 8 Server and add it to https://owncloud.org/install/? Currently there is only the VMWare download of ES at https://owncloud.com/download/. I suspect that a business case for native Windows support will show that it's a loser, but I don't think we can ignore Windows users entirely as that is a lot of potential customers. The trick is making it cost-effective to support them, and native Hyper-V images, plus VMWare/Virtualbox seems like the way to do this. Then it's a dead-simple installation for both casual and business users, with the same upgrade path to paid support as on Linux.

**Comment by carlaschroder** [comment]
Also I have this old pull request for documenting Hyper-V; https://github.com/owncloud/documentation-enterprise/pull/219/files  There are vhd (Hyper-V) images on http://download.owncloud.com/internal/eval_appliance/oc8ee/, but I do not know if they are meant to be distributed, or who should have access to them.

**Comment by jospoortvliet** [comment]
@carlaschroder a Hyper-V image is available from SUSE Studio. I'll adjust the install page to note that more clearly.

**Pull request merged**
