### PR TITLE
Show app icons in app-settings

### PR DESCRIPTION
**Pull request by lordelix**
## Description

- Show app icons in app-settings if browser is IE11.
- Scale up icons, so IE SVG scaling is not an issue

## Related Issue

https://github.com/owncloud/core/issues/29004

## How Has This Been Tested?

Visual test in IE11

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Seems you deleted some of the app icons instead of scaling ?

**Comment by davitol** [comment]
@felixheidecke It seems that now icons are shown but there are apps that don't appear like e.g. 'first run wizard' etc
screen shot 2017-10-16 at 10 57 41

**Comment by davitol** [comment]
> Seems you deleted some of the app icons instead of scaling ?

screen shot 2017-10-16 at 11 13 21
 Agree like mail notification

**Comment by felixheidecke** [comment]
@davitol I deleted where the icon was the cog. I automatically falls back to the cog icon in core anyways so I figured that I should remove it in this cases instead of scaling it separately.

I will go ahead and fix the wizzard, mail template and notifications.

@settermjd there are a few infos we need to convey to app-devs (@oc and externally) on how to create icons with the right dimensions. Currently, it doesn't say anything about icons in the dev manual: https://doc.owncloud.org/server/10.0/developer_manual/app/ :-(

**Comment by settermjd** [comment]
@felixheidecke, what should I add?

**Comment by felixheidecke** [comment]
> @felixheidecke, what should I add?

Haha … I forgot already :-/
I'l be getting back to you once I get this done.

**Comment by DeepDiver1975** [comment]
@felixheidecke what is the status of this? THX

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by davitol** [comment]
Is it ready to review? @felixheidecke

**Comment by PVince81** [comment]
@felixheidecke is this still an issue ? is it quick to finish ?

**Comment by davitol** [comment]
> is this still an issue ?

It is still an issue in oC 10.0.8

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
