### PR TITLE
Webapp config patch

### PR DESCRIPTION
**Pull request by noci2012**
Please find the .webappconfig patch

### CODE REVIEW

**Comment by noci2012** [comment]
not sure why 93f0773  is included

**Comment by noci2012** [comment]
I hereby grant you the complete use of this change (addition of .webapp in security scanner) under any license the owncloud/core requires.
being it MIT, GPL...

**Comment by noci2012** [comment]
BTW: there is bitrot   the link     https://owncloud.org/code-reviews-on-github/

**Comment by DeepDiver1975** [comment]
In order to cleaup the commit history and let jenkins do his job - a new pr was submitted: https://github.com/owncloud/core/pull/25184

**Pull request closed without merging**
