### PR TITLE
[stable10] do not urlencode group id

### PR DESCRIPTION
**Pull request by butonic**
backport of https://github.com/owncloud/user_management/pull/20

### CODE REVIEW

**Comment by phil-davis** [comment]
Manual test works in webUI with a group "a space" with this change. Other webUI group add/delete/ member change/display operations seem to still work fine.

I also tried other "nasty" group names like "a%age" "a/slash" and those had the similar problem before this change - their members did not display on the webUI. They work with this fix.

Note: the provisioning API (different API that can manage users/groups/membership) works OK with groups containing spaces. Provisioning API test cases for various weird group names, including with spaces, are being added in #31017

**Comment by mmattel** [comment]
@butonic would´t it be good to reflect in the PR name [stable10] as it is a backport ?
Just for the sake for better identification 😃

**Comment by DeepDiver1975** [comment]
acceptance tests are failing ... please have a closer look

**Comment by butonic** [comment]
superseded by https://github.com/owncloud/core/pull/31224

**Comment by PVince81** [comment]
- [ ] raise ticket to ban slashes from group creation

**Review by PVince81 — APPROVED** [review]
:+1: code looks good.

not merging due to freeze

**Comment by DeepDiver1975** [comment]
@butonic can you resolve the conflicts please? THX

**Comment by PVince81** [comment]
@phil-davis can you help solve the conflicts ?

**Comment by phil-davis** [comment]
Resolved, rebased, force pushed. Let's see if CI is happy.

**Pull request merged**
