### PR TITLE
hide sort indicator when in multiselect mode, ref #19056

### PR DESCRIPTION
**Pull request by jancborchardt**
Ref #19056, but as said there @PVince81 @MorrisJobke you need to remove the logic as well because the header is still clickable.

### CODE REVIEW

**Comment by PVince81** [comment]
Fixed, please review @MorrisJobke @nickvergessen @schiesbn @rullzer @blizzz

**Comment by MorrisJobke** [comment]
> Fixed, please review @MorrisJobke @nickvergessen @schiesbn @rullzer @blizzz

* [ ] on hover the file size the little arrow is still visible

**Comment by PVince81** [comment]
The selector wars has begun!

**Comment by PVince81** [comment]
Please rereview

**Comment by MorrisJobke** [comment]
Tested and works :+1: (even on IE8) :dancer:

**Comment by blizzz** [comment]
yup, works :+1:

**Pull request merged**
