### PR TITLE
[9.0] Catch the ForbiddenException to make sure it gets handled

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of https://github.com/owncloud/core/pull/24949
Approval in https://github.com/owncloud/core/pull/24949#issuecomment-223008256

### CODE REVIEW

**Comment by nickvergessen** [comment]
@PVince81 @icewind1991 backport review please

**Comment by PVince81** [comment]
:+1:

**Comment by rullzer** [comment]
:+1:

**Comment by rullzer** [comment]
Rebased to make github happy

**Pull request merged**
