### PR TITLE
Create new method for uploading file with headers in tests

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Add new method to upload file in webdav.php for uploading file with headers

## Related Issue

- Related to https://github.com/owncloud/firewall/issues/539

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
I guess that you want to use this new method from other places?
Oh, I see you already put a link to firewall.

**Comment by dpakach** [comment]
Stable10 backport in #33787

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@dpakach conflicts to resolve
Note: I also fixed a ``php-cs-fixer`` code style error last night, so make sure to pull the latest branch from github first.

**Comment by phil-davis** [comment]
@dpakach it still says there are conflicts

**Comment by dpakach** [comment]
> @dpakach it still says there are conflicts

Ok I didnt noticed your comment before I am working to fix this

**Pull request merged**
