### PR TITLE
Remove old ocs share api code

### PR DESCRIPTION
**Pull request by rullzer**
The old code is no longer reachable as the endpoint that uses OCS has taken it all over now.

Thus we can say farewell to this old code.

CC: @schiesbn @nickvergessen @DeepDiver1975 @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by rullzer** [comment]
Oracle had a weird timeout on some tests... lets see if that happens again..

**Comment by rullzer** [comment]
Ok oracle timesout on 

```
15:50:31 1) Test_Files_Sharing_Api::testPublicLinkUrl
15:50:31 Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT * FROM "oc_share" WHERE ("share_type" = ?) AND (("uid_initiator" = ?) OR (("uid_owner" = ?) AND ("uid_initiator" IS NULL))) ORDER BY "id" ASC' with params [3, "test-share-user1", "test-share-user1"]:
15:50:31 
15:50:31 Execution aborted after 15 minutes
15:50:31 
15:50:31 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:119
15:50:31 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:836
15:50:31 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
15:50:31 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
15:50:31 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:135
15:50:31 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:493
15:50:31 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:835
15:50:31 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:450
15:50:31 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:485
15:50:31 
```

I have no idea why

**Comment by DeepDiver1975** [comment]
really fishy

````
02:33:40.162 
02:33:40.162 There were 8 errors:
02:33:40.162 
02:33:40.162 1) Test_Files_Sharing_Api::testPublicLinkUrl
02:33:40.163 Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT * FROM "oc_share" WHERE ("share_type" = :dcValue1) AND (("uid_initiator" = :dcValue3) OR (("uid_owner" = :dcValue2) AND ("uid_initiator" IS NULL))) ORDER BY "id" ASC' with params [3, "test-share-user1", "test-share-user1"]:
02:33:40.163 
02:33:40.163 Execution aborted after 15 minutes
02:33:40.163 
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:119
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:836
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:135
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:493
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:450
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:485
02:33:40.163 
02:33:40.163 Caused by
02:33:40.163 PHP_Invoker_TimeoutException: Execution aborted after 15 minutes
02:33:40.163 
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/SQLParserUtils.php:70
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/SQLParserUtils.php:116
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:823
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:135
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:493
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:450
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:485
02:33:40.163 
02:33:40.163 2) Test_Files_Sharing_Api::testGetShareFromSource
02:33:40.163 PHP_Invoker_TimeoutException: Execution aborted after 15 minutes
02:33:40.163 
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/node/node.php:87
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/node/node.php:178
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:483
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:450
02:33:40.163 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:539
02:33:40.164 
02:33:40.164 3) Test_Files_Sharing_Api::testGetShareFromFolder
02:33:40.166 Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT * FROM "oc_share" WHERE ("share_type" = ?) AND (("uid_initiator" = ?) OR (("uid_owner" = ?) AND ("uid_initiator" IS NULL))) AND ("file_source" = ?) ORDER BY "id" ASC' with params [3, "test-share-user1", "test-share-user1", "5559"]:
02:33:40.166 
02:33:40.166 Execution aborted after 15 minutes
02:33:40.166 
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:119
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:836
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:135
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:493
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:393
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:438
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:645
02:33:40.166 
02:33:40.166 Caused by
02:33:40.166 PHP_Invoker_TimeoutException: Execution aborted after 15 minutes
02:33:40.166 
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:84
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:104
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:825
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:135
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:493
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:393
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:438
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:645
02:33:40.166 
02:33:40.166 4) Test_Files_Sharing_Api::testGetShareFromFolderReshares
02:33:40.166 Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT * FROM "oc_share" WHERE ("share_type" = ?) AND (("uid_initiator" = ?) OR (("uid_owner" = ?) AND ("uid_initiator" IS NULL))) AND ("file_source" = ?) ORDER BY "id" ASC' with params [3, "test-share-user2", "test-share-user2", "5571"]:
02:33:40.166 
02:33:40.166 Execution aborted after 15 minutes
02:33:40.166 
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:119
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:836
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:135
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:493
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:393
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:438
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:716
02:33:40.166 
02:33:40.166 Caused by
02:33:40.166 PHP_Invoker_TimeoutException: Execution aborted after 15 minutes
02:33:40.166 
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:84
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:104
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:825
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:135
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:493
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:393
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:438
02:33:40.166 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:716
02:33:40.167 
02:33:40.167 5) Test_Files_Sharing_Api::testGetShareFromSubFolderReShares
02:33:40.167 PHP_Invoker_TimeoutException: Execution aborted after 15 minutes
02:33:40.167 
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/expressionbuilder/expressionbuilder.php:84
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:471
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:393
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:438
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:755
02:33:40.167 
02:33:40.167 6) Test_Files_Sharing_Api::testGetShareFromFolderReReShares
02:33:40.167 PHP_Invoker_TimeoutException: Execution aborted after 15 minutes
02:33:40.167 
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:423
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:1028
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:890
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:491
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:393
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:438
02:33:40.167 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:803
02:33:40.168 
02:33:40.168 7) Test_Files_Sharing_Api::testGetShareMultipleSharedFolder
02:33:40.168 PHP_Invoker_TimeoutException: Execution aborted after 15 minutes
02:33:40.168 
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:1262
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:988
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:455
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:450
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:852
02:33:40.168 
02:33:40.168 8) Test_Files_Sharing_Api::testGetShareFromFileReReShares
02:33:40.168 Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT * FROM "oc_share" WHERE ("share_type" = ?) AND (("uid_initiator" = ?) OR (("uid_owner" = ?) AND ("uid_initiator" IS NULL))) AND ("file_source" = ?) ORDER BY "id" ASC' with params [3, "test-share-user3", "test-share-user3", 5602]:
02:33:40.168 
02:33:40.168 Execution aborted after 15 minutes
02:33:40.168 
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:119
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:836
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:135
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:493
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:393
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:438
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:913
02:33:40.168 
02:33:40.168 Caused by
02:33:40.168 PHP_Invoker_TimeoutException: Execution aborted after 15 minutes
02:33:40.168 
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:212
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:828
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:135
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/defaultshareprovider.php:493
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/share20/manager.php:859
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:393
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/api/share20ocs.php:438
02:33:40.168 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/api.php:913
02:33:40.168

**Comment by rullzer** [comment]
Ok it seems oracle needs https://github.com/owncloud/core/commit/e7f5f13e226cbfc5313831e044717b110377af79

Else it keeps on looping.

All is fine now. Please review.

**Comment by rullzer** [comment]
please review @PVince81 @schiesbn @nickvergessen @MorrisJobke @DeepDiver1975 @LukasReschke 

Basically it just removes the old OCS endpoint (unused anyway) and converts all the integration tests tests we had on the old endpoint to the new endpoint.

**Comment by MorrisJobke** [comment]
Looks good so far :+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
