### PR TITLE
Remove unused ldapUserCleanupInterval

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Remove unused ``ldapUserCleanupInterval``

## Related Issue
#30419 

## Motivation and Context
Reduce confusion

## How Has This Been Tested?
Search all code.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by cdamken** [comment]
@phil-davis We have to remove the background job and probably cleaning some stuff in core.

**Comment by cdamken** [comment]
@phil-davis We have to remove the background job and probably cleaning some stuff in core.

**Comment by phil-davis** [comment]
Point me at something - since ``ldapUserCleanupInterval`` is not used anywhere, then what other code/stuff is there to remove/adjust?

**Comment by PVince81** [comment]
the background job likely has a different name or maybe was removed already. to be done separately.

let's merge

**Comment by phil-davis** [comment]
Backport ``stable10`` #30812

**Pull request merged**
