### PR TITLE
Revert "Debounce cancel upload message"

### PR DESCRIPTION
**Pull request by icewind1991**
Reverts owncloud/core#19628

Merged to early

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
so - somebody needs to reopen the PR for 8.2.1 again

**Comment by icewind1991** [comment]
https://github.com/owncloud/core/pull/19710

**Pull request merged**
