### PR TITLE
smb: rename textfield from root to subfolder

### PR DESCRIPTION
**Pull request by mmattel**
This PR is based on: https://github.com/owncloud/core/issues/12826 (Suggestion: renaming some box texts when you do a SMB mount)
@karlitschek this is the corresponding PR for.

It is about that some translations in SMB are too aggressive and should stay with the original wording as they are proper names commonly used.

Right now there are two terms which should be changed:

Already done on Transifex
English: Share
German: Teilen --> Share 

This PR
English: Root --> Subfolder
German:  Root --> Subfolder

(example, see also: https://answers.uchicago.edu/22499)

Is there another place where I should/must add the term "Subfolder" or is this done automatically?

The term "Root" can stay because this PR only affects SMB and other extenal storages use the term root too.

If this PR gets agreed and merged, I will also do a PR at documentation/configuration/files_external to finalize this adoption.

### CODE REVIEW

**Comment by Xenopathic** [comment]
cc @jancborchardt 

I think it's a good idea to change 'Root' to something else, but we need to make sure there isn't any confusion on whether this option refers to the subdirectory of the share that is used, or the subdirectory of oC that the mount is placed in. The ownCloud mount type uses 'Remote subfolder' for that field, perhaps it would be better to use?

In addition, a couple of other mount types use 'Root', such as FTP, SFTP and WebDav - it'd be nice to change them all in one PR.

**Comment by jancborchardt** [comment]
@Xenopathic Yes, »Remote subfolder« is a more clear name.

@mmattel 
> German: Teilen --> Share

This is wrong. Facebook (arguably the biggest user of »Share«) uses »Teilen«. Would be cool if you can change that back on Transifex.

**Comment by jancborchardt** [comment]
Ah wait – disregard my comment about the »Share«. It’s of course correct in this context. Sorry @mmattel! :)

**Comment by mmattel** [comment]
IMHO I do not see any possible confusion regarding subfolder // remote subfolder, as the name for the place where owncloud mounts to is called Folder Name (Ordnername). Also the term subfolder is a common used term in microsoft environments - what I have tried to show up via the link of the University of Chicago at the top. But if it is wanted, let me know, I will change it.

Regarding the generic replacement of root with subfolder, hmmmm - I would not do that because as I see it, with other external storage types, the term root is mabe a valid one.

Suggestion: let´s check each one by one and clarify it.

(BTW: Why is there a build failure when only text has been changed??)

**Comment by mmattel** [comment]
Ok, I have made a list of all currently existing external storage systems and where the mount of a subfolder is possible:

External Storage Type | Subfolder possible
-------------------------------|-------------------------
Local | no
Amazon S3 and S3 compliant | no
Dropbox | no
Google Drive | no
OpenStack Object Storage | no
FTP/SFTP | yes
SMB/CIFS | yes
SMB/CIFS using OC login | yes
ownCloud | yes
WebDAV | yes

The term ``Remote Subfolder`` already exists in: apps/files_external/appinfo/app.php#160
````
OC_Mount_Config::registerBackend('\OC\Files\Storage\OwnCloud', array(
	'backend' => 'ownCloud',
	'priority' => 100,
	'configuration' => array(
		'host' => (string)$l->t('URL'),
		'user' => (string)$l->t('Username'),
		'password' => '*'.$l->t('Password'),
		'root' => '&'.$l->t('Remote subfolder'),
		'secure' => '!'.$l->t('Secure https://'))));
````
As the term ``Remote Subfolder`` already exists for external storage: OwnCloud, I vote for reusing it.
I will update the commit for all corresponding storage items.

I also will update the german translation of ``Remote Subfolder`` on Transifex because the original wording is a proper commonly used name and should not be "Germanized".

**Comment by Xenopathic** [comment]
:+1:

**Comment by mmattel** [comment]
@jancborchardt @Xenopathic 
can we merge this or do we have to wait for merge accepts fo 8.1 ?

**Comment by Xenopathic** [comment]
If it's not too late, I'd like to get this merged for oC 8, but it'd be best for someone with more knowledge than me to press the button :smile: In addition, we still need another reviewer.

**Comment by MorrisJobke** [comment]
I'm fine with that :+1:

@DeepDiver1975 @karlitschek Is this fine for merge?

@mmattel Can you squash the two commits? Thanks

**Comment by karlitschek** [comment]
Makes sense from my point of view :+1:   @jancborchardt

**Comment by MorrisJobke** [comment]
edcba11 <- I merged by hand to master

**Comment by MorrisJobke** [comment]
Actual merge commit: 8b95494073ff1465f327bd1b24aee5bbfcf954a4

**Comment by MorrisJobke** [comment]
@mmattel Thanks

**Pull request closed without merging**
