### PR TITLE
Change default sync-client-url and default-doc-base-url 

### LINKED ISSUE #38957: [QA] broken links on the first login banner
Seen in 10.8.0 beta2

When a user logs in for the first time, he sees a banner like this:
image

The button "Connect your calendar" has a broken link:  https://doc.owncloud.org/server/10.8/go.php?to=user-sync-calendars
The button "Connect your contacts" has a broken link: https://doc.owncloud.org/server/10.8/go.php?to=user-sync-contacts

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Before this PR, If the user clicks on the Desktop app button, he will be redirected to:
https://owncloud.com/download-server/#install-clients
The anchor for #install-clients seems to be missing. 

With this PR we will redirect now to the client landing page:
https://owncloud.com/desktop-app/

image

## Related Issue

- Fixes #38957 38960

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToRoot1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31030/63/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiWebdavProperties1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31030/101/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliExternalStorage-10.6.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31035/127/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-6-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31036/176/1

**Review by phil-davis — APPROVED** [review]
LGTM - do we want this in 10.8?

**Comment by JanAckermann** [comment]
@phil-davis answer from @mmattel still pending, I guess yes. Will do a backport after this is merged to master

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIAdminSettings-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31038/129/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/31038/13/9
There is a unit test fail:
1) Tests\Settings\Panels\Admin\EncryptionTest::testGetPanel

It looks like a real fail - some unit test expectation related to the code changes in this PR.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/31038/129/1
```
runsh: Total unexpected failed scenarios throughout the test run:
webUIAdminSettings/helpAndTips.feature:15
webUIAdminSettings/helpAndTips.feature:16
webUIAdminSettings/helpAndTips.feature:17
webUIAdminSettings/helpAndTips.feature:18
webUIAdminSettings/helpAndTips.feature:19
```

There are also acceptance tests that check these links - the test expectations need to be adjusted.

**Comment by phil-davis** [comment]
Tests have been adjusted.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport to 10.8 is PR #38965

**Pull request merged**
