### PR TITLE
fix webdav quota check for the root of the dav endpoint

### LINKED ISSUE #16245: User can't update a single file shared from server1 to server2
Tested in current master:

- share a single text file from server1 to server2 (make sure that "can edit" is set)
- try to edit the file on server2 with the internal text editor
-> save will fail. The sabredav quotaplugin throws a \Sabre\DAV\Exception\InsufficientStorage, even if no quota is set.

cc @PVince81 

If I remember correctly we had a similar problem during the 8.0 development cycle. Vincent told me that this was fixed back than by @icewind1991 but it seems like the bug is back. @icewind1991 can you have a look at it? Thanks!

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #16245

cc @DeepDiver1975 @schiesbn @PVince81

### CODE REVIEW

**Comment by schiesbn** [comment]
Tested, works... :+1: if Jenkins finish successfully.

Thanks for taking care of it Robin!

**Comment by PVince81** [comment]
Can you please add a unit test ?

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
:-1: this needs a unit test.

@icewind1991 I know you might be busy with other stuff (locking) so let me know if you want me to add this myself.

**Comment by icewind1991** [comment]
> @icewind1991 I know you might be busy with other stuff (locking) so let me know if you want me to add this myself.

Please do

**Comment by PVince81** [comment]
I have added a unit test.
Basically the old unit test already called free_space with "null" but it wasn't caught in the mock.

Please review @icewind1991 

:+1: for the other code changes from me

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
