### PR TITLE
Fix usage of PHP method within namespace

### PR DESCRIPTION
**Pull request by MorrisJobke**
- introduced with https://github.com/owncloud/core/pull/20373

cc @LukasReschke @nickvergessen

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I got following during php cron.php execution:

```
PHP Fatal error:  Call to undefined function OC\Security\random_int() in lib/private/security/securerandom.php on line 80
```

**Comment by LukasReschke** [comment]
Strange. Works for me locally but if it fixes the issue for you: :+1:

**Comment by rullzer** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> Strange. Works for me locally but if it fixes the issue for you: :+1:

maybe related to the fact that the function is either from php or from random_compat library

**Pull request merged**
