### PR TITLE
user_ldap: add support default quota match Regex on user DN

### PR DESCRIPTION
**Pull request by chakphanu**
To define default quota by comparison regular expression with user DN.
example
"/cn=admin,ou=people/i","25 GB"
"/cn=sales,ou=people/i","1 GB"

First line mean if user DN contain cn=admin,ou=people  and not have quota attribute,quota is seting to "25 GB".
Second line mean if user DN contain cn=sales,ou=people  and not have quota attribute,quota is seting to "1 GB".

### CODE REVIEW

**Comment by chakphanu** [comment]
from https://owncloud.org/contribute/agreement/ .
I'm signed and emailed PDF.
please review again.

**Comment by chakphanu** [comment]
from https://owncloud.org/contribute/agreement/ .
I'm signed and emailed PDF.
please review again.

Chakphanu Komasathit

**Comment by blizzz** [comment]
did you close it on purpose?

Anyway, honestly I tend to not have this feature included. Quotas should be managed from within LDAP, instead of introducing magic on our side.

**Comment by chakphanu** [comment]
i will try to read doc/code again, for using posixGroup(memberUid not
memberOf) with quota attribute for make default group quota.
เมื่อ 6 เม.ย. 2016 17:34 "blizzz" <notifications@github.com> เขียนว่า

**Pull request closed without merging**
