### PR TITLE
fixing wrong usage of license vs licence

### LINKED ISSUE #13120: App license information is missing
### Steps to reproduce

1. Install both master and enterprise tar balls
2. Navigate to the apps page

### Expected behaviour

The license information should be available for each app

### Actual behaviour

The license information is missing for each app

p234

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0 alpha 1 (daily) Build:2015-01-05T04:12:18+00:00

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://github.com/owncloud/core/issues/13120

@jancborchardt @karlitschek @jnfrmarks 

bildschirmfoto von 2015-01-06 13 08 14

### CODE REVIEW

**Comment by Xenopathic** [comment]
:+1: It'd be nice to have some formal requirement for an app `info.xml`, just a friendly reminder that oC targets British English and the noun is 'licence'. :laughing:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
works :)

**Comment by jancborchardt** [comment]
»licence« is British English, and we use American English everywhere else. ;) Should be »license«.

**Comment by DeepDiver1975** [comment]
in info.xml mainly license is used - but there is a fallback to support both writings

**Pull request merged**
