### PR TITLE
Update doctrine/dbal to 2.5.5

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

doctrine/dbal 2.5.5 has just been released
## Motivation and Context

stay up to date with our libs
## How Has This Been Tested?

Jenkins will do the job
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Ouch, DB-related test failures

**Comment by butonic** [comment]
👍 phew

**Comment by butonic** [comment]
backport to 9.1? to 9.0.x?

**Comment by DeepDiver1975** [comment]
> backport to 9.1? to 9.0.x?

any reason to do so?

**Comment by butonic** [comment]
customers with oracle are trying to move to php7 because the php5.5 they are currently using is EOL but their enterprise distros basically skip 5.6. I had hoped 2.5.5 would already contain the necessary oracle fixes, but ... they don't, yet: https://github.com/owncloud/core/issues/18425#issuecomment-258602147 If dbal 2.6 is available we might need to backport to 9.1 at least ... if we still support it by then.

**Comment by DeepDiver1975** [comment]
> If dbal 2.6 is available we might need to backport to 9.1 at least

Let's see once we get there ... but until then: I consider backporting dbal as too critical.
Oracle and php7 users need to use 9.2 (assuming we get dbal 2.6 within the release schedule of oc9.2)

**Comment by DeepDiver1975** [comment]
> Oracle and php7 users need to use 9.2 (assuming we get dbal 2.6 within the release schedule of oc9.2)

let's see what dbal devs say - https://github.com/doctrine/dbal/issues/2468#issuecomment-260483121

**Pull request merged**
