### PR TITLE
[8.1] Expose syslog tag in the configuration

### PR DESCRIPTION
**Pull request by Gomez**
BP: https://github.com/owncloud/core/pull/19957#event-443754584

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense. backport is fine :+1:

**Comment by DeepDiver1975** [comment]
> makes sense. backport is fine :+1:

@cmonteroluque @karlitschek 8.1.4 or 8.1.5 ? risk is minimal from my pov so 8.1.4 would be ok

**Comment by karlitschek** [comment]
Yes. 8.1.4 should be fine

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by cmonteroluque** [comment]
thanks

**Pull request merged**
