### PR TITLE
[stable7] Fix deleting selected files in the trashbin

### PR DESCRIPTION
**Pull request by PVince81**
Please review @icewind1991 @DeepDiver1975 @karlitschek @nickvergessen @LukasReschke 

Fixes showstopper for OC 7.0.5: https://github.com/owncloud/core/issues/14687

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
hmm - 7.0.5 is closed from my understanding - we need to coordinate this with @karlitschek and @jnfrmarks 

Please do not merge before we have feedback - THX

**Comment by DeepDiver1975** [comment]
Note to self: another reason why we shall have automated ui tests ....

**Comment by PVince81** [comment]
Or have a unit test for the trashbin to detect the delete link, which is currently missing.

**Comment by nickvergessen** [comment]
I'd go with the js unit test here.
Not sure it's worth a show stopper. They can't manually make space free yeah, but it will be auto-deleted at some point?

**Comment by PVince81** [comment]
@nickvergessen I'm already working on the JS unit test for a separate PR

**Comment by icewind1991** [comment]
:+1: makes sense

**Comment by PVince81** [comment]
Unit test here for master: https://github.com/owncloud/core/pull/14690

**Comment by karlitschek** [comment]
:+1:  This is a bad regression. Please backport to stable7. We will redo the packages. @jnfrmarks FYI

**Comment by PVince81** [comment]
@karlitschek thanks. This is the backport PR already, please merge if you agree.

**Comment by jnfrmarks** [comment]
@jnweiger 

Please let me know when the new packages are ready for testing

**Comment by jnweiger** [comment]
@karlitschek please ping me when new tar balls are ready. 
7.0.5 as seen on dl-oo is currently dated Feb 21.

**Comment by DeepDiver1975** [comment]
@karlitschek @jnfrmarks please note that stable7 contains more fixes since we last time bundled 7.0.5 - https://github.com/owncloud/core/commits/stable7

**Comment by karlitschek** [comment]
:-( :-( :-( let´s talk later

**Comment by jnweiger** [comment]
@DeepDiver1975 @karlitschek Can we have a short changelog? Sorry to bring that up again...

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/compare/v7.0.5...stable7

**Pull request merged**
