### PR TITLE
Backport admin checkboxes #19744 to stable8.2

### PR DESCRIPTION
**Pull request by Henni**
replaces #19762 
backport of #19744

### CODE REVIEW

**Comment by nickvergessen** [comment]
Looks better, thanks!

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by jancborchardt** [comment]
Note that this is scheduled for 8.2.1 – that means **no merging until 8.2 is released**.

**Comment by jancborchardt** [comment]
Or rather … @karlitschek is this intended to be 8.2.1? I guess 8.2 is completely closed, right?

**Comment by karlitschek** [comment]
backport for 8.2.0 is still possible. Of course the relevant developer will be personally grilled by me and other who breaks the release. ;-)
But I guess this change has very low risk. So please backport :-)

**Comment by jancborchardt** [comment]
Ok, then press the merge button. ;)

**Comment by MorrisJobke** [comment]
> Of course the relevant developer will be personally grilled by me and other who breaks the release. ;-)

:fire:

**Pull request merged**
