### PR TITLE
Support for files_external customjs from apps

### LINKED ISSUE #27682: Storage backend `getCustomJS` must support specifying app name
Currently `getCustomJS` only supports returning a single string which is the JS script name.
That gets converted to `addScript('files_external', ' scriptname')`.

But for app devs who implement ext storages we need this to also allow app names.

### PR DESCRIPTION
**Pull request by PVince81**
## Related Issue
Fixes https://github.com/owncloud/core/issues/27682

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@davicente please test

### CODE REVIEW

**Comment by PVince81** [comment]
Tested as follows:

1. Check out the files_external_ftp app
1. Patch it:
```diff
diff --git a/js/test.js b/js/test.js
new file mode 100644
index 0000000..3c1510b
--- /dev/null
+++ b/js/test.js
@@ -0,0 +1 @@
+console.log('loaded!');
diff --git a/lib/Backend/FTP.php b/lib/Backend/FTP.php
index 2b5b112..ffa7835 100644
--- a/lib/Backend/FTP.php
+++ b/lib/Backend/FTP.php
@@ -34,6 +34,7 @@ class FTP extends Backend {
                        ->addIdentifierAlias('\OC\Files\Storage\FTP') // legacy compat
                        ->setStorageClass('\OCA\Files_external_ftp\Storage\FTP')
                        ->setText($l->t('FTP (Fly)'))
+                       ->setCustomJS(['files_external_ftp', 'test'])
                        ->addParameters([
                                (new DefinitionParameter('username', $l->t('Username'))),
                                (new DefinitionParameter('password', $l->t('Password')))
```

3. Enable the app
4. Go to storages panel and check browser console

With this PR the console shows "loaded!"

@davicente not sure why it didn't work in your case.

@jvillafanez @DeepDiver1975 review ?

**Comment by davicente** [comment]
@PVince81 if I remember well, it was because I didn't use the exact name "files_onedrive" for the app. Then it worked fine

**Comment by PVince81** [comment]
Can you retest with this PR ? Then we can merge it.

**Comment by davicente** [comment]
I have tested with   js/onedrive.js   and   js/test.js

Working:   With  js/onedrive.js   and   `->setCustomJS(['files_onedrive', 'onedrive']);`  in the backend

Not working:   With js/test.js      and    `->setCustomJS(['files_onedrive', 'test']);`  in the backend 
The file is loaded, but failes because it doesn't get the value of this variable:
`var clientId = $tr.find('.configuration [data-parameter="client_id"]').val();`
I don't know if it helps you or if it's my problem

**Comment by PVince81** [comment]
This PR is only about actually loading the JS file. If it's loaded then it fits its purpose.

If the JS file code itself has problems for whatever reason, it is not related to this PR which only opens the door.

**Comment by davicente** [comment]
Then it works

**Comment by PVince81** [comment]
Thanks for the feedback.

Rebased for CI

**Pull request merged**
