### PR TITLE
Add user additional info field for share autocomplete

### LINKED ISSUE #28979: Make duplicate sharee autocomplete results easier to distinguish
### Steps

1. Create three users "user1", "user2" and "user3"
1. Set the display name of all three to "hallo"
1. Go to the files view
1. Open the sharing panel
1. Type "hal" in the autocomplete

### Expected result
Three distinguishabe entries.

### Actual result
All three entries say "hallo".
With no avatars set, there is no visual way for distinction.
The tooltip shows the user id but might not be suitable in the case of LDAP uuids.

### Version
ownCloud 10.0.3RC1

See also https://github.com/owncloud/guests/issues/142#issuecomment-326035866

@pmaier1 @tomneedham

### PR DESCRIPTION
**Pull request by PVince81**
## Related Issue
Fixes https://github.com/owncloud/core/issues/28979

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
@pmaier1 please try it out.

We might want to tweak the visual design a bit.

**Review by jvillafanez — APPROVED** [review]
Code looks good, not tested

**Comment by PVince81** [comment]
@felixheidecke any suggestion the visual design ? Now having the email address appearing there makes the sidebar look more loaded. Eventually we might want to move those permissions to a sub-panel/accordion but out of scope for this PR/feature.

**Comment by PVince81** [comment]
To test please go to the settings page under the "Sharing" section where you can select what information to display with the sharee in autocomplete and in the rows.

**Review by lordelix — APPROVED** [review]
I added a little CSS. Looks good from a UI pov. 👍

**Comment by PVince81** [comment]
seems I need to look into test failures

**Comment by PVince81** [comment]
Added PHP unit tests, squashed, rebased.

Quick rereview appreciated @jvillafanez

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/29457

**Pull request merged**
