### PR TITLE
Fix bogus entry that appears when switching with arrow keys

### LINKED ISSUE #19260: select user in share drop down with strange content
select user in the new share drop down shows strange content in some situations

Steps to reproduce:

1. login as 
2. create a user called "user1"
3. go to the share dialog
4. enter "use" -> the auto complete list will show you user1
5. press twice the "arrow down" key

The input field will show now ````[Object object] ````

cc @blizzz @PVince81

### PR DESCRIPTION
**Pull request by PVince81**
This piece was missing from the old code.

Fixes https://github.com/owncloud/core/issues/19260

@schiesbn @blizzz @rullzer

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Rebase needed ;)

**Comment by PVince81** [comment]
Rebase or call the master so he can merge this himself as there is no conflict and it's a simple fix.
But I don't mind rebasing and adding additional load to our CI.

**Comment by MorrisJobke** [comment]
> Rebase or call the master so he can merge this himself as there is no conflict and it's a simple fix.
> But I don't mind rebasing and adding additional load to our CI.

Yep. I also noticed that we now applied harder policies.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by PVince81** [comment]
Hmm that's JS unit, not worth a force push.
@DeepDiver1975 please merge this JS-only fix

**Comment by schiesbn** [comment]
works :+1:

**Pull request merged**
