### PR TITLE
Revert "move fonts from Regular+Bold to Light+Semibold for lighter feel"

### PR DESCRIPTION
**Pull request by MorrisJobke**
Reverts owncloud/core#18522

See #18954

### CODE REVIEW

**Comment by karlitschek** [comment]
:-1:  This was discussed and decided otherwise. We could try to tune the color maybe but we need @jancborchardt option for that.

**Comment by MorrisJobke** [comment]
I'm fine with this.

@jancborchardt Maybe you can give a statement.

@karlitschek @cmonteroluque Even in the current pre-release phase many complains about the too tiny font popped up. Maybe include this into 8.2 to not kill the UX for too many users.

**Comment by MorrisJobke** [comment]
> :-1: This was discussed and decided otherwise. We could try to tune the color maybe but we need @jancborchardt option for that.

https://github.com/owncloud/core/issues/18954#issuecomment-145435319

I would be against tuning of colors, because it's quite heavy. The revert would be an easy non-breaking solution.

**Comment by MorrisJobke** [comment]
Left: this PR, right: master
bildschirmfoto von 2015-10-08 18-30-50

**Comment by karlitschek** [comment]
@MorrisJobke Hmm. Not sure i would call it 'easy'. This kills the UI that was designed and driven forward by @jancborchardt 
No changes without proper discussion with him please!

**Comment by MorrisJobke** [comment]
> No changes without proper discussion with him please!

Sure. It's just hard, because he is on vacation and he also proposed the revert. Maybe he will read this here and can comment.

**Comment by karlitschek** [comment]
@MorrisJobke Sure. All I want is a proper discussion. I'm sure he will comment in time :-)

**Comment by jancborchardt** [comment]
(Still on vacation til Monday ;)

I started a discussion, did not propose a revert.

The new style looks very good and modern – on modern systems. As seen on your screenshot.

The thing here is the backwards compatibility. Can we add fixes for that, like special browsers (e.g. IE, or Firefox on some Linuxes where font rendering is borked) or is that too much work? Can we make a list of the setups where it doesn't look good?

**Comment by danimo** [comment]
> The new style looks very good and modern – on modern systems. As seen on your screenshot.

it looks good, but it's also very hard to read. This may work better on HiDPI displays, but so far I have not received an upgraded work laptop. *cough*

Ideas welcome.

**Comment by MorrisJobke** [comment]
Superseded by https://github.com/owncloud/core/pull/20176

**Pull request closed without merging**
