### PR TITLE
Tag scenario that is not relevant to encryption

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Tag ``resetPassword.feature`` scenario about reset password UI page with ``@skipOnEncryption``

## Related Issue
Encryption PR https://github.com/owncloud/encryption/pull/34 needs this.

## Motivation and Context
We need a way to indicate which core webUI tests are testing behavior that is overridden/changed in some app(s), or tests that just do not work nicely in some app(s). We already do this for LDAP by tagging such scenarios ``@skipOnLDAP``.

Now we want to run the webUI tests with backend encryption on. At the moment just 1 scenario fails - when a user resets their password. For encryption, there is an extra warning and checkbox to check. So in core, tag that scenario ``@skipOnEncryption``. Then the encryption app can easily skip it.

The encryption app can be responsible for implementing its own test scenario to check the different behavior that it introduces.

## How Has This Been Tested?
CI in encryption will know, when this skip tag gets merged.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test infrastructure

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
I tagged this QA because it would be good to get this in place straight away so we can get the encryption app tests running automatically and passing.

@patrickjahns @individual-it if you are happy with this, please approve (and the backport) - so it gets in the earliest nightly build...

**Review by patrickjahns — APPROVED** [review]
👍 LGTM

**Comment by phil-davis** [comment]
In webUI we used camelCase. In API tests there is underscore.
Choose one standard, and we can easily patch the other - e.g. in API tests we would add equivalent camelCase tags, changing scripts in core that use them, then change scripts in apps, then remove the old underscore tags in core.

**Comment by phil-davis** [comment]
> However - I am not sure that this is a functionality only available with encryption app

Yes, the tagging system in core might need more thought for the future! Actually multiple apps might have reason to override certain "components"  of core. (notifications does, encryption does...) 

So we might find a better way in the longer term that we can tag logical core functionality like ``@resetPasswordBehavior`` ``@notificationBehavior`` ```@loginBehavior``... Then an app that overrides that part of core behavior can easily skip the tests for that core behavior, and implement its own tests. But it needs some thought, because often the app will only override a bit of the behavior, and some (or most)  of the core tests still work.

**Comment by phil-davis** [comment]
Backport ``stable10`` #31809

**Pull request merged**
