### PR TITLE
Check whether the user exists before trying to set up his file system

### LINKED ISSUE #16752: Can not run cron anymore when there is a "Expire versions" task for a deleted user
```
$ php ./cron.php 
PHP Fatal error:  Call to a member function getOwner() on a non-object in /home/nickv/ownCloud/Smashbox/master/lib/private/files/filesystem.php on line 872
PHP Stack trace:
PHP   1. {main}() /home/nickv/ownCloud/Smashbox/master/cron.php:0
PHP   2. OC\BackgroundJob\QueuedJob->execute($jobList = *uninitialized*, $logger = *uninitialized*) /home/nickv/ownCloud/Smashbox/master/cron.php:130
PHP   3. OC\BackgroundJob\Job->execute($jobList = *uninitialized*, $logger = *uninitialized*) /home/nickv/ownCloud/Smashbox/master/lib/private/backgroundjob/queuedjob.php:42
PHP   4. OC\Command\CommandJob->run($serializedCommand = *uninitialized*) /home/nickv/ownCloud/Smashbox/master/lib/private/backgroundjob/job.php:52
PHP   5. OCA\Files_Versions\Command\Expire->handle() /home/nickv/ownCloud/Smashbox/master/lib/private/command/commandjob.php:34
PHP   6. OCA\Files_Versions\Storage::expire($filename = *uninitialized*, $versionsSize = *uninitialized*, $offset = *uninitialized*) /home/nickv/ownCloud/Smashbox/master/apps/files_versions/command/expire.php:54
PHP   7. OCA\Files_Versions\Storage::getUidAndFilename($filename = *uninitialized*) /home/nickv/ownCloud/Smashbox/master/apps/files_versions/lib/storage.php:558
PHP   8. OC\Files\Filesystem::getOwner($path = *uninitialized*) /home/nickv/ownCloud/Smashbox/master/apps/files_versions/lib/storage.php:71
```

I'm not sure if we can simply delete those tasks. Or will this break versions on shared files (not expiring them)

@schiesbn @PVince81 any ideas

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #16752 

Due to our architecture that stores serialized objects in the database, we can not use DI without breaking existing jobs:
https://github.com/owncloud/core/blob/9a6d253af39dba49a1397416fb448e922df8a7a1/apps/files_versions/lib/storage.php#L543-L544
https://github.com/owncloud/core/blob/b585d87d9d6ccf964d10cd2e2cb1d465eb537a25/lib/private/command/asyncbus.php#L58-58
https://github.com/owncloud/core/blob/b585d87d9d6ccf964d10cd2e2cb1d465eb537a25/lib/private/command/asyncbus.php#L105-L107

My suggestion would be to fix the architectural problem asap in 8.2, so we store the classname and arguments, instead of the object.

@PVince81 @schiesbn @icewind1991 @DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> My suggestion would be to fix the architectural problem asap in 8.2, so we store the classname and arguments, instead of the object.

Hmm ... having the explicit object/closure in the job queue was part of the original feature request. 
reverting this to the old classname approach is sub-optimal.

**Comment by nickvergessen** [comment]
> Hmm ... having the explicit object/closure in the job queue was part of the original feature request.
reverting this to the old classname approach is sub-optimal.

Okay well we can keep the closure way for who-ever requested that. But we might to stop using it for our jobs because of stuff like this. Should then also document it, that BC needs to be taken into account and objects can not be further edited?

**Comment by DeepDiver1975** [comment]
> Okay well we can keep the closure way for who-ever requested that.

me :wink:

**Comment by DeepDiver1975** [comment]
> Should then also document it, that BC needs to be taken into account and objects can not be further edited?

yes - documentation is necessary on this - thanks for finding this at the end

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by nickvergessen** [comment]
I added unit tests only for the non existing user case.

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
Works :+1:

**Pull request merged**
