### PR TITLE
fix probably devastating typo

### PR DESCRIPTION
**Pull request by butonic**
pretend ... not preten**t**

I don't know where this code is called, but it looks rather nasty. php doc says `pretend`: https://github.com/owncloud/core/pull/27938/files#diff-ad8c79933f6e78c27903df782afaf76cL65

### CODE REVIEW

**Comment by PVince81** [comment]
never seen this before... maybe it's to create a fake app that will purposefully fail installing, for testing ?

I also grepped the whole code and didn't see any reference

**Comment by phil-davis** [comment]
Note that "pretend" is also at https://github.com/owncloud/core/blob/master/lib/private/Installer.php#L199 which has lots of description of updateApp that is not actually what it does. Maybe that could be cleaned up as a separate thing.

**Comment by butonic** [comment]
yes, afaict it is not use ... better fix it before someone uses it ...

**Comment by mrow4a** [comment]
Nice typo :+1:

**Comment by PVince81** [comment]
or remove this completely if it isn't used anywhere ?

**Comment by DeepDiver1975** [comment]
@dependabot rebase

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase failed! Please rebase your pull request manually via the command line.

Reason:
```
Command: git rebase base/master

Exit Code: 128

Cause:

.git/rebase-apply/patch:31: trailing whitespace.
* The issues in other components should be reported in their respective repositories: 
.git/rebase-apply/patch:137: trailing whitespace.
--> 
.git/rebase-apply/patch:167: trailing whitespace.
Login as admin user into your ownCloud and access 
.git/rebase-apply/patch:168: trailing whitespace.
http://example.com/index.php/settings/integrity/failed 
.git/rebase-apply/patch:187: trailing whitespace.
or 
warning: squelched 1614 whitespace errors
warning: 1619 lines add whitespace errors.
warning: Cannot merge binary files: core/img/background.jpg (49c1a3945f283112d0e419031d079a8205e92191 vs. fix issue #23600 - mail invites through v1 webdav (#26188))
error: Failed to merge in the changes.


```

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
