### PR TITLE
Update libs and pin version to 5.6

### PR DESCRIPTION
**Pull request by PVince81**
Update dependencies to latest version compatible with PHP 5.6.32.

Pinned version to PHP 5.6.32 because if you update the libs with composer of PHP 7 it might pick the wrong versions... So better be safe.

This PR is to be backported to stable10.
At some point we can redo the same and pin to PHP 7.1 for 10.1 on master.

Things to retest:
- Dropbox external storage app (flysystem is pulling a Dropbox v2 adapter)
- CI

### CODE REVIEW

**Comment by PVince81** [comment]
Hmm, we should also update the libs in "apps/files_external"... but for that I'd rather we first move out the backends and update the libs then: https://github.com/owncloud/core/issues/27542

**Comment by PVince81** [comment]
- [ ] update the JS libs as well

**Comment by DeepDiver1975** [comment]
- [ ] dav tests need to adjust the version

````
OCA\DAV\Tests\unit\CardDAV\ConverterTest::testCreation with data set #0 ('BEGIN:VCARD\nVERSION:3.0\nPRODI...VCARD\n')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'BEGIN:VCARD
 VERSION:3.0
-PRODID:-//Sabre//Sabre VObject 4.1.2//EN
+PRODID:-//Sabre//Sabre VObject 4.1.3//EN
 UID:12345
 FN:12345
 N:12345;;;;
 PHOTO;ENCODING=b;TYPE=JPEG:MTIzNDU2Nzg5
 END:VCARD
 '

**Comment by phil-davis** [comment]
I discovered the Sabre VObject version bump last week when rebasing the Guzzle version PR:
https://github.com/owncloud/core/pull/29773/commits

It will be good to have that merged into master so I can remove the commit from Guzzle changes.

**Comment by PVince81** [comment]
Updated JS libs to latest minor versions.

To retest:
- [x] TEST: md5 / base64: public page upload with password
- [x] TEST: clipboard: copy public link
- [x] TEST: davclient, es6-promise: Webdav works
- [x] TEST: moment: relative timestamps still work in web UI
- [x] TEST: backbone JS: comments still work
- [x] TEST: strengthify: password meter in personal settings
- [x] TEST: jcrop: avatar setting
- [x] TEST: snap: left sidebar toggle on mobile
- [ ] TEST: bowser: IE < 11 or older browsers warning
- [ ] TEST: timezone detect (?)

Note: we should consider major release update for 10.1. Note that jquery update will break a lot of things so need to plan some time...

**Comment by PVince81** [comment]
We should also look at have the new Sabre changes released so we can update to it for https://github.com/owncloud/core/issues/28341

**Comment by PVince81** [comment]
- [ ] update node libs (ex: karma, jasmine, etc)

**Comment by PVince81** [comment]
No output for `npm update` or `npm outdated`, so it seems our npm libs are already up to date.

**Comment by PVince81** [comment]
Regarding timezone, I didn't find what code uses it, maybe it's obsolete.

Anyway, I checked the hidden input fields and their value was set correctly, so the library update worked.

**Comment by PVince81** [comment]
:+1: for @DeepDiver1975's test fixes.

Review for the update in general ?

I think we should backport this afterwards.

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by PVince81** [comment]
@DeepDiver1975 can you take care of the backport and version updates in general ? seems the libs updated again...

**Comment by phil-davis** [comment]
@PVince81 @DeepDiver1975 I see a backport request label here, but it did not get backported.
So is it planned to get all the composer stuff up-to-date in ``stable10`` for the next point release?

**Comment by PVince81** [comment]
That would be nice, yes

**Comment by phil-davis** [comment]
PR #30430 has what would be the backported code for ``bower.json`` and ``core/js/core.json``
See comment there deciding not to push those version bumps back to ``stable10``

**Comment by phil-davis** [comment]
All needed backports are done.

**Pull request merged**
