### PR TITLE
Take autoconfig into account when installing from occ

### PR DESCRIPTION
**Pull request by icewind1991**
cc @DeepDiver1975

### CODE REVIEW

**Comment by Xenopathic** [comment]
Can't we deprecate this autoconfig stuff already? It's effectively replaced with `./occ maintenance:install` anyways

**Comment by DeepDiver1975** [comment]
autoconfig holds no addition information compared to occ install

**Comment by icewind1991** [comment]
I like it for separating the *boring* backend options for filling in the username/password in the setup.

I use it for my [docker setup](https://github.com/icewind1991/owncloud-dev) where install is usually done trough the WI

**Comment by icewind1991** [comment]
so do we want this or not?

**Comment by rullzer** [comment]
> so do we want this or not?

@DeepDiver1975 ping

**Comment by MorrisJobke** [comment]
> so do we want this or not?

Correct. I vote for closing this.

**Comment by DeepDiver1975** [comment]
I'm all in for closing this - we want to kill this autoconfig hack one day and not add more to it.

**Pull request closed without merging**
