### PR TITLE
Remove license implementation

### LINKED ISSUE #38843: Remove a license key
Issue from community: https://central.owncloud.org/t/invalid-license-key-notifications/29852

**Steps**
1. Enter an invalid license key in the admin UI
2. See the "invalid key" error message
3. Try to get rid of the error message without having a valid key

**Expected behavior**
You can at least send an empty string or have a way to purge an invalid license key

**Actual behavior**
It's not possible to get rid of the warning without messing with the db (see central ticket)

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Enhancement: Introduce a remove license button in WebUIBefore this PR, it was not possible, to remove any ownCloud license. This lead to an issue if someone enters an invalid license, a permanent message indicator was shown in the WebUI.
With this PR it is possible to remove the license.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/38843

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation ticket raised: https://github.com/owncloud/docs/issues/3694
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
@jvillafanez Do you see any problems with this implementation ?

**Comment by jvillafanez** [comment]
We'll have to double-check possible issues, but the code looks good :+1:

**Comment by JanAckermann** [comment]
@jvillafanez do you know possible issues/side effects?

**Comment by jvillafanez** [comment]
It's mainly to confirm there are no problems.
* Interaction with the grace period
  1. Enable EE app without license
  2. Check grace period started
  3. Wait for a while
  4. Add EE license and check the warning disappears
  5. Remove license
  6. Grace period reappears **without resetting**

  I assume this will be the behaviour since we aren't touching the grace period. This is fine for me.
* License complains tracking.
  I don't remember why we needed to track this, so I'm not fully sure if we want to clear those values or not in this case. At first sight, it makes sense because we can consider we're setting a new license. I haven't checked in depth, but I'm ok with clearing those values.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiShareOperationsToShares-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiShareOperationsToShares-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiTranslation-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingIntGroup2-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingNotify-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIAddUsers-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiShareUpdateToShares-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiAuthWebDav-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiFederationToShares1-10.6.0-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiShareReshareToShares3-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by JanAckermann** [comment]
> I assume this will be the behaviour since we aren't touching the grace period. This is fine for me.
Confirmed =)

**Review by IljaN — APPROVED** [review]
LGTM :+1:

**Pull request merged**
