### PR TITLE
Fix group principal

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
Fixes the Exception :+1:

**Comment by nickvergessen** [comment]
Steps to test:
1. Enable calendar-rework app
2. Add user test to a group
3. Open calendar
4. Check status of `http://localhost/remote.php/dav/calendars/test/`

**Comment by PVince81** [comment]
:+1: let's get this in

**Comment by DeepDiver1975** [comment]
thx

**Pull request merged**
