### PR TITLE
Move console application to it's own class - allows reuse in the web shell

### PR DESCRIPTION
**Pull request by DeepDiver1975**
This introduces an app for admins to execute console commands in the browser - might be helpful for people running ownCloud at a shared hoster without terminal access.

Inspired by https://github.com/owncloud/core/pull/15445#issuecomment-90749219

The app lives now here: https://github.com/DeepDiver1975/web_shell

### CODE REVIEW

**Comment by LukasReschke** [comment]
Ewww… Please not in core or as official app… I already get way too many people complaining about the fact that administrators can do too much etc…

**Comment by LukasReschke** [comment]
Ah… If we can ensure this is only for the ownCloud commands this is fine… But please no complete bash shell…

**Comment by DeepDiver1975** [comment]
> Ewww… Please not in core or as official app… I already get way too many people complaining about the fact that administrators can do too much etc…

sure

**Comment by DeepDiver1975** [comment]
> Ah… If we can ensure this is only for the ownCloud commands this is fine… But please no complete bash shell…

hell - no - only commands of occ are allowed

**Comment by karlitschek** [comment]
cool idea. but please in a separate repo :-)

**Comment by DeepDiver1975** [comment]
@karlitschek @LukasReschke @MorrisJobke the app has been removed from this branch - this pr now only holds some code reorganizations to allow web shell to reuse the console application.

THX

**Comment by PVince81** [comment]
Console commands still work and also still respect maintenance mode :+1:

**Comment by DeepDiver1975** [comment]
@ownCloudPlusOneBot

**Comment by MorrisJobke** [comment]
cc @owncloudplus1bot

**Pull request merged**
