### PR TITLE
Username autocomplete option in admin menu now also toggles autocomp…

### PR DESCRIPTION
**Pull request by IljaN**
## Description
The "Allow username autocompletion in share dialog" option in the admin menu toggles the auto-completion for the username input while leaving auto-completion behaviour for the email field (share by email) unaffected. This allows user name and e-mail address enumeration which results in a privacy leak in some use-cases 
This fix makes the option also apply for auto-completion on the e-mail field.

autocomplete_broke

## Related Issue
#26504 

## Motivation and Context
Fixing potention privacy leak for some users by possible e-mail address enumeration.

## How Has This Been Tested?
- Login as Admin, enable "Allow users to send mail notification for shared files" and "Allow username autocompletion in share dialog."
- Share a file, type something in the e-mail field -> see autocompletion.
- Disable autocompletion in admin menu -> no more autocompletion in the e-mail field.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks. There is actually another API that needs adjusting as well.
The OCS Share API is used by clients like desktop or mobile clients to provide autocomplete.
You can trigger it using this curl call:
```
curl -u admin:admin "http://localhost/owncloud/ocs/v1.php/apps/files_sharing/api/v1/sharees?itemType=folder"
```

(yes, we really should have only one API, later on ajax/share.php will be killed once the web UI is switched completely to use the OCS Share API as well)

**Comment by PVince81** [comment]
ref https://github.com/owncloud/documentation/issues/1626

**Comment by IljaN** [comment]
@PVince81 Thanks for the info, I will look into it.

**Comment by IljaN** [comment]
@PVince81 
The enumeration setting already [applies](https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Controller/ShareesController.php#L209) to the /sharees endpoint (v1.php and v2.php)

With disabled enumeration:
```bash
$ curl -u admin:123 "http://localhost:8000/ocs/v2.php/apps/files_sharing/api/v1/sharees?itemType=folder&format=json
```
```json
{
    "ocs": {
        "meta": {
            "status": "ok",
            "statuscode": 100,
            "message": "OK",
            "totalitems": "",
            "itemsperpage": ""
        },
        "data": {
            "exact": {
                "users": [],
                "groups": [],
                "remotes": []
            },
            "users": [],
            "groups": [],
            "remotes": []
        }
    }
}
```
Should we add an search by email option?

**Comment by PVince81** [comment]
> The enumeration setting already applies to the /sharees endpoint (v1.php and v2.php)

Oh, nice!

For the integration tests you just need to run "run.sh" inside build/integration, that should be all.
Might need to run composer there first.

From what I see it's one of the tests that randomly fails and no one every found out why... especially considering that the test order shouldn't change. I'll restart the build. Your PR is good to go :+1:

**Comment by PVince81** [comment]
Please backport to:
- [ ] stable9.1
- [ ] stable9
- [ ] stable8.2
- [ ] stable8.1 (if applicable)

**Comment by PVince81** [comment]
@IljaN can you take care of the backports ? Just create a branch off stable9.1 and cherry-pick the commits there then make a new PR. Then same with the other branches.

Thanks

**Comment by Kawohl** [comment]
@IljaN could you please do the backports?

**Comment by IljaN** [comment]
https://github.com/owncloud/core/pull/26953

**Comment by PVince81** [comment]
All backports were done and merged and will be released as part of the next maintainenance release end of january.

**Pull request merged**
