### PR TITLE
Cache results of testRemoteUrl

### PR DESCRIPTION
**Pull request by LukasReschke**
Otherwise setting up the storage will result in a HTTP request and thus slowing down ownCloud.

Replaces https://github.com/owncloud/core/pull/22855

cc @icewind1991 @PVince81 This one also works with Pydio.

### CODE REVIEW

**Comment by icewind1991** [comment]
I'm okay with this but I still think we should delay the remote check in the scanner

:+1:

**Comment by blizzz** [comment]
Looks good :+1: but cannot judge whether it really can replace ##22855. Nevertheless, the caching is good to have.

**Comment by LukasReschke** [comment]
Thanks, @blizzz and @icewind1991. Your reviews are _WELCOME_.

**Comment by blizzz** [comment]
@LukasReschke You're welcome, pall!

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
