### PR TITLE
allow apps to execute code after a service has been registered

### PR DESCRIPTION
**Pull request by butonic**
I quickly wanted to answer https://github.com/owncloud/templateeditor/issues/12 But stumbled over the unpredictable order in which apps are initialized. So I created this simple observer mechanism that allows apps to register closures to be executed after a service has been registered.

An example is the template app, that can register itself with the server to allow other apps to register additional templates. See the above mentioned issue.

While we can use st like `\OC::$server->getSearch()->registerProvider(...)` for apps that are part of core, this allows interaction between apps ... without core needing to know about them up front.
- [ ] we might need to add `registerService()` to the `IServerContainer` interface to make registering with the server as in https://github.com/owncloud/templateeditor/issues/13 public.

### CODE REVIEW

**Comment by butonic** [comment]
@DeepDiver1975 and I did not get to this in Nürnberg ... feel free to take over this PR.

**Comment by nickvergessen** [comment]
Would be nice, if we can get back to this.
All the gallery, files_* and other css/js that are loaded on the activity app to display a non-existing file list just make it unnecessary slow :/

In my opinion we could also start with the files app as an exception and add the relevant hooks/events there, because that seems to be the most affected place

**Comment by PVince81** [comment]
I wonder if your case @nickvergessen should be linked to routes somehow. Make it possible for apps to trigger functions whenever a specific route is being prepared. RouteManager ? DependencyManager?

**Comment by MorrisJobke** [comment]
@deepdiver1975 Can this be better addressed with the symfony eventhandler?

**Comment by DeepDiver1975** [comment]
> @deepdiver1975 Can this be better addressed with the symfony eventhandler?

yes -> close

**Pull request closed without merging**
