### PR TITLE
[stable8.1] add test for factories

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
use ref for factory test

Ensure we construct SimpleContainer

Use single instance of DIContainer in routing tests

Backport of #17852 

cc @karlitschek @Raydiation @MorrisJobke @DeepDiver1975 @icewind1991

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by MorrisJobke** [comment]
Oracle failed

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
