### PR TITLE
Cleanup garbage collection for global file cache

### LINKED ISSUE #14389: unlink() error in log after executing cronjob
### Steps to reproduce
1. Can't say :(

### Expected behaviour
No error after cronjob

### Actual behaviour
Exactly 1 sec. after executing the 15min-cronjob, there appears the following error-msg:

`(...)"unlink(\/tmp\/owncloud-ocpygo73d442\/user): Is a directory at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobal.php#107","level":3,(...)`

### Server configuration
**Operating system**: Ubuntu 14.04.1 LTS

**Web server:**  Apache/2.4.7

**Database:** MySQL 5.5.41

**PHP version:** PHP 5.5.9

**ownCloud version:** 8.0 (stable)

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:** 
Activity 1.2.0
Bookmarks 0.4
Deleted files 0.6.2
Documents 0.9.0
External storage support 0.2.3
File Locking 
First Run Wizard 1.1
Full Text Search 0.6.0
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Server-side Encryption 0.7.1
Share Files 0.6.0
Text Editor 0.4
Updater 0.4
Versions 1.0.5
Video Viewer 0.1.3

**The content of config/config.php:**
```
  'instanceid' => '<edit>',
  'passwordsalt' => '<edit>',
  'secret' => '<edit>',
  'trusted_domains' =>
  array (
    0 => '<edit>.de',
    1 => 'www.<edit>.de',
  ),
  'datadirectory' => '/home/owncloud-data',
  'overwrite.cli.url' => 'https://<edit>.de',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => '<edit>',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '<edit>',
  'dbpassword' => '<edit>',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'loglevel' => 1,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Movies',
    5 => 'OC\\Preview\\MSOffice2003',
    6 => 'OC\\Preview\\MSOffice2007',
    7 => 'OC\\Preview\\MSOfficeDoc',
    8 => 'OC\\Preview\\OpenDocument',
    9 => 'OC\\Preview\\PDF',
  ),
  'mail_from_address' => 'do-not-reply',
  'mail_smtpmode' => 'php',
  'mail_domain' => '<edit>.de',
```

**Are you using external storage, if yes which one:** activated but none connected

**Are you using encryption:** yes

### Client configuration
**Browser:** Chrome 40

**Operating system:** Win8.1

#### Web server error log
```
no errors in apache.log or errors.log
```

#### ownCloud log (data/owncloud.log)
```
Last Lines:


{"reqId":"8e2a68323e78dddbc2e854c1191bcb5d","remoteAddr":"","app":"PHP","message":"unlink(\/tmp\/owncloud-ocpygo73d442\/user): Is a directory at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobal.php#107","level":3,"time":"2015-02-19T17:45:02+00:00"}
{"reqId":"650e50a17936b468d66027fa65664f10","remoteAddr":"","app":"PHP","message":"unlink(\/tmp\/owncloud-ocpygo73d442\/user): Is a directory at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobal.php#107","level":3,"time":"2015-02-19T18:00:02+00:00"}
{"reqId":"39f9533bb129cb4ea66636616f99cb0c","remoteAddr":"","app":"PHP","message":"unlink(\/tmp\/owncloud-ocpygo73d442\/user): Is a directory at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobal.php#107","level":3,"time":"2015-02-19T18:15:02+00:00"}
{"reqId":"704fd1a9b059f21b7d122750aba8e449","remoteAddr":"","app":"PHP","message":"unlink(\/tmp\/owncloud-ocpygo73d442\/user): Is a directory at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobal.php#107","level":3,"time":"2015-02-19T18:30:01+00:00"}
{"reqId":"cc53d7f685c9bd7562122648903c0303","remoteAddr":"<IP edited>","app":"core","message":"Invalid OCS content returned for app files_external","level":4,"time":"2015-02-19T18:37:49+00:00"}
{"reqId":"4dfe813a7218dbb47e97cfef2905b328","remoteAddr":"","app":"PHP","message":"unlink(\/tmp\/owncloud-ocpygo73d442\/user): Is a directory at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobal.php#107","level":3,"time":"2015-02-19T18:45:01+00:00"}
{"reqId":"a42482d0601843687934526f98f9a15b","remoteAddr":"","app":"PHP","message":"unlink(\/tmp\/owncloud-ocpygo73d442\/user): Is a directory at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobal.php#107","level":3,"time":"2015-02-19T19:00:02+00:00"}
{"reqId":"58add03c89ee620f72afad3bcea91245","remoteAddr":"","app":"PHP","message":"unlink(\/tmp\/owncloud-ocpygo73d442\/user): Is a directory at \/var\/www\/owncloud\/lib\/private\/cache\/fileglobal.php#107","level":3,"time":"2015-02-19T19:15:02+00:00"}

```

### PR DESCRIPTION
**Pull request by icewind1991**
Also fixes it to ignore directories (fixes #14389), makes the code testable and adds unit tests.

cc @DeepDiver1975 @PVince81 @oparoz

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: makes sense

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@karlitschek issue was reported for OC8 - backport?

**Comment by karlitschek** [comment]
yes. please backport

**Comment by icewind1991** [comment]
stable8: e82f30c

**Comment by PVince81** [comment]
@icewind1991 next time please send a PR for backports, to avoid risking to break Jenkins there. (this was decided a few weeks ago)

**Comment by icewind1991** [comment]
ok

**Comment by DeepDiver1975** [comment]
@icewind1991 I hope you are subscribed to the mailing list :speak_no_evil: 

https://mailman.owncloud.org/pipermail/devel/2015-January/000964.html

**Pull request merged**
