### PR TITLE
php-cs-fixer fix . --rules=native_function_invocation

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
php functions should be called with their full namespace
one of many resource about the details: https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

## Motivation and Context
- Write proper code
- Give the code some speedup

## How Has This Been Tested?
Pure unit testing

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mmattel** [comment]
WOW
If this gets merged, we need to add a note in the developer guide !
I file a small reminder in documentation 
@settermjd

**Comment by mmattel** [comment]
@DeepDiver1975 if this gets merged, we will have code added in the meanwhile which does not have the namespace added. How can we make sure we can 
a.) identify these elements and 
b.) post-change them
I guess that the process of a+b will be needed to rerun from time to time...

**Comment by DeepDiver1975** [comment]
> I guess that the process of a+b will be needed to rerun from time to time...

I did add the php-cs-fixer as drone step - as soon as anybody violates the rules - the build will fail

**Comment by mmattel** [comment]
This is great for new PR´s an thanks for higlighting this as this is a very important doc-note !

But this also means a one time delta job for those PR´s which are not covered by this one but merged in between. May I assume that you volunteer to fix them :smile:

**Comment by DeepDiver1975** [comment]
> May I assume that you volunteer to fix them smile

anybody can easily run the php-cs-fixer to not only detect the changes but also to apply them.
we will fix this which in a short period of time

**Review by butonic — APPROVED** [review]
:heart:

**Review by butonic — CHANGES_REQUESTED** [review]
and some more ...

**Review by butonic — APPROVED** [review]

**Comment by mmattel** [comment]
@DeepDiver1975 question: what is the impact to other repositories if there is one, lets take as an example oauth2 (could be any other). How can those be improved by this approach ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 question: what is the impact to other repositories if there is one, lets take as an example oauth2 (could be any other). How can those be improved by this approach ?

we will step by step introduce php-cs-fixer to all other repos as well.

**Comment by phil-davis** [comment]
Yes, and it will minimize pain for future backports.

**Comment by patrickjahns** [comment]
Before Backporting:

I had a bit of more time to think and check other projects using / implementing it - and I would actually prefer the approach the doctrine project went ahead:

instead of using `\` for all global functions (i.e. `\ltrim()..." they use function imports

```
use function ltrim;
ltrim()
```

ref: https://github.com/doctrine/doctrine2/issues/6807

while this is merged now - we could create codesniffer rules: https://github.com/doctrine/coding-standard/pull/15/files

**Comment by phil-davis** [comment]
Note: backport of this is likely to be superceded by the "ownCloud coding standard" implementation in PR #31442

**Comment by phil-davis** [comment]
Effective backport is included in #31453

**Pull request merged**
