### PR TITLE
collapse app descriptions by default, make expandable, fix #13112

### LINKED ISSUE #13112: Collapse app descriptions to be able to more easily browse apps
### Steps to reproduce

1. Install both master and enterprise tar balls
2. Navigate to the apps page to see the new app layout

### Expected behaviour

Ease of use to find all apps enabled, disabled, and recommended

### Actual behaviour

I have to do a lot of scrolling to see what's enabled, disabled, and recommended.  Perhaps having a list of apps that are links to the descriptions would be better?  Then, I can see all apps on the one page and click on the descriptions as needed

The Recommended link displays a blank page.  What should be displayed when I click on this link?

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0 alpha 1 (daily) Build:2015-01-05T04:12:18+00:00

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix  #13112, please review @owncloud/designers @jnfrmarks @DeepDiver1975 @karlitschek 

This hides the whole description and puts a »Show description …« text in its place. When clicked, the description slides down.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
It slides weirdly. It expands with a left "margin" and then the "margin" gets removed and the text justs to the left.

And I don't really like this in that way. Maybe put the description below the "Install" and "Uninstall" button?

**Comment by karlitschek** [comment]
Nice improvement. Would be great to have a way to collapse it again

**Comment by nickvergessen** [comment]
How about showing the first n characters all the time? So we only hide it, when it is getting out of hands?

**Comment by karlitschek** [comment]
@nickvergessen Good idea.

**Comment by karlitschek** [comment]
@nickvergessen Do you also have an idea how to collapse it again?

**Comment by jancborchardt** [comment]
Fixed the janky animation, and added the ability to collapse it again.

@MorrisJobke the description should go before the enable button – otherwise it looks strange when expanded. Also the enable/disable button is something you can then press after you read through the description.

@nickvergessen I thought about it but hiding it completely is fine. Also there’s not really a space gain if we show the first x lines cause most apps have about 5 lines only anyway.

Please retest @karlitschek @owncloud/designers

**Comment by MorrisJobke** [comment]
https://cloud.morrisjobke.de/public.php?service=files&t=fNdGknXjefFEs9r <- toggling the descript looks weird, because it jumps around.

**Comment by MorrisJobke** [comment]
Works now - pulling before checking helps :)

Thanks! Looks nice now :+1:

**Comment by MorrisJobke** [comment]
:tada: Even works on IE8 :tada: :balloon:

**Comment by MorrisJobke** [comment]
@oparoz @rullzer @Xenopathic Want to review this?

**Comment by MorrisJobke** [comment]
and @nickvergessen @jnfrmarks Review time?

**Comment by oparoz** [comment]
I don't like it, sorry :(. That list looks empty, unbalanced and introduces repetitive text.

I think the list interface needs an overhaul if you want to show less text. Here are my suggestions:
* Introduce a short description in the app's xml and use that as the main description, or simply use an excerpt like on blogs, etc.
* Use maybe a universal +/- button to collapse/uncollapse the long description. Could be next to the ellipsis
* Move the disable button to the right side, maybe next to the title. The current location makes the page taller for no good reason
* Keep the documentation links outside of the collapsible area

**Comment by jancborchardt** [comment]
> * Introduce a short description in the app's xml and use that as the main description, or simply use an excerpt like on blogs, etc.

That’s what the description is now already. Sure, devs sometimes have a longer description, but hey. This list is more comparable to the list you see when you browse the app store or play store – only icons, titles, and little more info.

> * Use maybe a universal +/- button to collapse/uncollapse the long description. Could be next to the ellipsis

We could do that in the future, yes. Might not be fully understandable though so I think text is better here.

> * Move the disable button to the right side, maybe next to the title. The current location makes the page taller for no good reason

That’s what my initial design was. The good reason for the current location though is the feature of enabling an app only for specific groups. That takes significant space and wouldn’t work well on the right.

> * Keep the documentation links outside of the collapsible area

Why? The point of collapsing it is to save space. If we keep the docs links outside of it, it’s not much saved.

**Comment by oparoz** [comment]
>> * Introduce a short description in the app's xml and use that as the main description, or simply use an excerpt like on blogs, etc.

> That’s what the description is now already. Sure, devs sometimes have a longer description, but hey. This list is more comparable to the list you see when you browse the app store or play store – only icons, titles, and little more info.

The problem is that having all or nothing introduces a lot of empty space and everything is stacked vertically. It might make sense on a mobile interface, but on a desktop, it looks strange.
Google Play on the desktop is just an icon wall, with only the titles. You only see the description when in an app and there, the long descriptions fade away under the read more button.

>> * Use maybe a universal +/- button to collapse/uncollapse the long description. Could be next to the ellipsis

> We could do that in the future, yes. Might not be fully understandable though so I think text is better here.

The standard "Read more" button if admins get to see the first 100 characters of the description maybe?

>> * Move the disable button to the right side, maybe next to the title. The current location makes the page taller for no good reason

> That’s what my initial design was. The good reason for the current location though is the feature of enabling an app only for specific groups. That takes significant space and wouldn’t work well on the right.

OK, I haven't seen what it looks like in this configuration, but taking the Google Play example again, you get all the buttons in the header, next to the icon, title, author, etc.
That also makes me think that screenshots would look nice in that admin area as well :)

>> * Keep the documentation links outside of the collapsible area

> Why? The point of collapsing it is to save space. If we keep the docs links outside of it, it’s not much saved.

Only if there is a bit of description shown. That would be akin to the "Additional information" row of the Play store

All in all, this only seen by admins, so not that big of a deal, but the placement of everything in collapsed mode did not convince me :)

**Comment by nickvergessen** [comment]
"Show description" is definetly wrong, when it also hides the documentation links.

And as said early, I don't think it makes sense to hide them all, just because some apps are too long. Having a 1-3 line description displayed by default is way better then having to click a ~~stupid button~~ link text before.
So I'm with @oparoz here and would tend to -1 if you have a list with plenty apps, you dont want to press plenty links before just to know what they do exactly

**Comment by jancborchardt** [comment]
@jnfrmarks would showinf the first 2 lines of the app description still solve issue #13112 for you?

**Comment by karlitschek** [comment]
Hmm. I agree with the feedback. Not the most awesome solution ever but a step forward :+1:

**Comment by jancborchardt** [comment]
@oparoz @nickvergessen folks – let’s iterate instead of overthinking it. Right now the problem is that scrolling and scanning through the apps can take a long time. Hiding the description only partly will not really help here.

In the future we can do stuff like have the layout use 2 columns to show the apps. Also there’s more detail stuff for the apps to come like screenshots and the like, so we need to have a proper detail view anyway.

**Pull request merged**
