### PR TITLE
[stable10] Repair step to fix orphan reshares

### PR DESCRIPTION
**Pull request by sharidas**
Its being reported that shares are orphaned.
And in such state when an upgrade operation is
performed results in failure. This repair
step fixes the orphan shares.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change would help to fix the failures caused during upgrade operation, when orphan reshares are residing in oc_share.

## Related Issue

https://github.com/owncloud/core/issues/30199

## Motivation and Context

This change would help to fix the failures caused during upgrade operation, when orphan reshares are residing in oc_share. This change tries to remove the orphan shares fro the table which doesn't have parent.

## How Has This Been Tested?

- Verified by creating the same scenario explained in 8.2.11 upgrade to 10.0.6.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sharidas** [comment]
Original PR: https://github.com/owncloud/core/pull/30653

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by jvillafanez** [comment]
Tested:
* OC 8.2.11 updated to 10.0.8RC1 and mysql 5.7.20 ✅ 

I haven't tested with a large dataset... I'm not sure about the performance
```
mysql> explain delete from share where parent not in (select id from (select id from share order by id) t);
+----+--------------------+------------+------------+----------------+---------------+-------------+---------+------+------+----------+-------------------------------------------------+
| id | select_type        | table      | partitions | type           | possible_keys | key         | key_len | ref  | rows | filtered | Extra                                           |
+----+--------------------+------------+------------+----------------+---------------+-------------+---------+------+------+----------+-------------------------------------------------+
|  1 | DELETE             | share      | NULL       | ALL            | NULL          | NULL        | NULL    | NULL |    1 |   100.00 | Using where                                     |
|  2 | DEPENDENT SUBQUERY | <derived3> | NULL       | index_subquery | <auto_key0>   | <auto_key0> | 4       | func |    2 |   100.00 | Using where; Using index; Full scan on NULL key |
|  3 | DERIVED            | share      | NULL       | index          | NULL          | PRIMARY     | 4       | NULL |    1 |   100.00 | Using index                                     |
+----+--------------------+------------+------------+----------------+---------------+-------------+---------+------+------+----------+-------------------------------------------------+
3 rows in set (0.01 sec)
```

**Comment by jvillafanez** [comment]
* OC 8.2.11 updated to 10.0.8RC1 and postgresql 9.6.8 ✅

Performance doesn't look good at first sight for large datasets.
```
owncloud=# explain delete from oc_share where parent not in (select id from (select id from oc_share order by id) t);
                                       QUERY PLAN                               
         
--------------------------------------------------------------------------------
---------
 Delete on oc_share  (cost=11.49..21.86 rows=15 width=6)
   ->  Seq Scan on oc_share  (cost=11.49..21.86 rows=15 width=6)
         Filter: (NOT (hashed SubPlan 1))
         SubPlan 1
           ->  Sort  (cost=11.04..11.11 rows=30 width=4)
                 Sort Key: oc_share_1.id
                 ->  Seq Scan on oc_share oc_share_1  (cost=0.00..10.30 rows=30 
width=4)
(7 rows)
```

**Comment by PVince81** [comment]
strange because I thought @butonic already optimized it as he added https://github.com/owncloud/core/pull/31004/files#diff-e37c59ae9672d3ba539a69df6838eed1R87 and other stuff

**Comment by jvillafanez** [comment]
Couldn't test properly with oracle due to ownCloud complaining about missing tables... ownCloud was installed via `occ maintenance:install` (first try the installation failed due to oracle wasn't fully up).

In any case the target delete query goes through, so I guess that if the connection is properly set up it should fix the issue.

```
SQL> explain plan for delete from "oc_share" where "parent" not in (select "id" from (select "id" from "oc_share" order by "id") t);

Explained.

SQL> select PLAN_TABLE_OUTPUT from TABLE(DBMS_XPLAN.DISPLAY());

PLAN_TABLE_OUTPUT
--------------------------------------------------------------------------------
Plan hash value: 4160578067

--------------------------------------------------------------------------------
| Id  | Operation	    | Name     | Rows  | Bytes | Cost (%CPU)| Time     |
--------------------------------------------------------------------------------
|   0 | DELETE STATEMENT    |	       |     1 |   117 |     5	(20)| 00:00:01 |
|   1 |  DELETE 	    | oc_share |       |       |	    |	       |
|*  2 |   HASH JOIN ANTI SNA|	       |     1 |   117 |     5	(20)| 00:00:01 |
|   3 |    TABLE ACCESS FULL| oc_share |     1 |   104 |     2	 (0)| 00:00:01 |
|   4 |    TABLE ACCESS FULL| oc_share |     1 |    13 |     2	 (0)| 00:00:01 |
--------------------------------------------------------------------------------

PLAN_TABLE_OUTPUT
--------------------------------------------------------------------------------

Predicate Information (identified by operation id):
---------------------------------------------------

   2 - access("parent"="id")

Note
-----
   - dynamic sampling used for this statement (level=2)

20 rows selected.
```

**Pull request merged**
