### PR TITLE
Revert "Highlight files after setFiles"

### LINKED ISSUE #28106: Permalink to files in subfolders doesn't point to the file.
### Steps to reproduce

1. Create a folder 'FOLDER'. 
2. Upload a file 'file.txt' to 'FOLDER'.
3. Copy permalink of the file (chain icon in the sidebar).
4. Open the copied link in a new window/tab.

### Expected behaviour
It should open 'file.txt' folder, showing it selected. (maybe with the sidebar open? cc @pmaier1 )

### Actual behaviour
It opens the folder 'FOLDER'. The permalink points to that folder. File 'file.txt' is not selected.

This affects mobile development (cc @nasli).

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Firefox

**Logs**
```
```

### PR DESCRIPTION
**Pull request by PVince81**
This reverts PR https://github.com/owncloud/core/pull/28665

Fixes https://github.com/owncloud/core/issues/28106

See explanation here https://github.com/owncloud/core/issues/28106#issuecomment-329757776

stable10: https://github.com/owncloud/core/pull/29019

### CODE REVIEW

**Comment by PVince81** [comment]
@SergioBertolinSG also review/test this one (forward port to master) ? no rush

**Comment by SergioBertolinSG** [comment]
Doesn't work on current master. :-1:

**Comment by SergioBertolinSG** [comment]
It is like the highlight gets lost.

**Comment by SergioBertolinSG** [comment]
Ah nevermind, it is the same behaviour in stable10, the file is highlighted, but if you move the cursor on the rows and refresh the page, the highlight is lost. Not sure if we want to fix this.

**Comment by PVince81** [comment]
how do you move the cursor on the row ? if you mean when you open the sidebar by having the row selected, it doesn't affect the URL. The URL only points to the folder

**Comment by SergioBertolinSG** [comment]
Yeah, the url is right but after refreshing or moving it doesn't highlight the correct row:

highlighting_lost

**Pull request merged**
