### PR TITLE
[WIP] Removed quota stream wrapper, allow soft quota

### LINKED ISSUE #7626: Encryption + quota file truncation risk when reaching quota
### Steps to reproduce:
1. Enable encryption.
2. Set a quota of 250 kb.
3. Upload two files with 100 kb.
### Expected result

File is uploaded correctly
### Actual result

The second 100kb file is truncated (and encrypted)
### Versions

ownCloud 7 pre-alpha (and potentially 6.0.2 as well)
### More info

Encrypted files are generally a bit bigger than original files, but the quota calculation is based on unencrypted sizes, which causes confusion and makes the quota wrapper truncate the file too early.

I've discussed this with @schiesbn and we agreed to go with a soft quota. Actually, we've already decided for having a soft quota before because of metadata and other files that do not count into it.

However, the quota stream implementation is still enforcing a hard quota (truncates the last bytes that exceed the quota), and it is tricky to make it work properly in situations where multiple files are uploaded from different sources at the same time and different speeds (race conditions).

We will thus remove the hard limit, which might also mean removing the quota stream wrapper completely as its sole purpose seems to be to enforce that hard limit.

Additionally, as per #7589 it will be possible to also count external storages in the used space, which means that the potential concurrency and file truncation will become even more incontrollable.

I will prepare a PR to remove the hard limit.

CC @icewind1991

### PR DESCRIPTION
**Pull request by PVince81**
The quota stream wrapper was used to provide a hard quota that would
truncate files when exceeding the quota. Since we decided to go with a
soft quota, the stream wrapper isn't necessary any more.

This fixes issues where file would randomly be truncated when the quota
was almost reached, happening with encryption and could happen when
uploading multiple files from multiple sources concurrently.

Fixes #7626 

Note: It is not possible to properly test this before #7624 is merged.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @butonic

**Comment by MorrisJobke** [comment]
@butonic @PVince81 Any news here? Can this be closed or revived?

**Comment by MorrisJobke** [comment]
@PVince81 Ping

**Comment by PVince81** [comment]
I think we should revive this.

The quota stream wrapper doesn't make sense because:
- it checks the free space only before starting to write, so it means that if the free space / quota changes during transfer it will not notice
- it truncates the files if there is not enough space left, which we **never** want
- it might make the `streamCopy` from Webdav fail, but then it could as well be made to fail earlier before we even started the transfer (the Sabre quota plugin should do that)

**Comment by PVince81** [comment]
- and in the case where it's really the disk becoming full, the file will be truncated anyway. No need for a quota stream wrapper for that

**Comment by PVince81** [comment]
Let's revive this for 9.1

**Comment by PVince81** [comment]
Not much reason keeping this open. To be redone once we address the ticket.

**Pull request closed without merging**
