### PR TITLE
Mount options GUI for external storage

### PR DESCRIPTION
**Pull request by PVince81**
Requires https://github.com/owncloud/core/pull/11884 to be merged first.

@icewind1991 @DeepDiver1975 @Xenopathic FYI

mountoptions

@jancborchardt I hope the look of this dropdown is ok for now (there will be more checkboxes soon)

### CODE REVIEW

**Comment by Xenopathic** [comment]
Nice!

**Comment by karlitschek** [comment]
nice :+1:

**Comment by jancborchardt** [comment]
@PVince81 yes, for now the look is ok. We can polish the popovers for 8.2 then.

**Comment by Xenopathic** [comment]
Needs rebasing

**Comment by PVince81** [comment]
in progress

**Comment by PVince81** [comment]
Rebased onto master.

@icewind1991 do we already have an option name for disabling the scanner ?

**Comment by icewind1991** [comment]
Same as the global config one `'filesystem_check_changes'`

**Comment by PVince81** [comment]
Cool, thanks. I'll add it.
- [ ] add "filesystem_check_changes" option in dropdown

**Comment by PVince81** [comment]
I have added the option, but there seems to be a problem when reading it.
The config becomes this:
```
{
    "user": {
        "all": {
            "\/$user\/files\/SFTP": {
                "id": 1,
                "class": "\\OC\\Files\\Storage\\SFTP",
                "options": {
                    "host": "localhost",
                    "user": "vincent",
                    "password": "",
                    "root": "\/home\/vincent\/temp\/sftpmount",
                    "undefined": "100",
                    "password_encrypted": "REMOVED"
                },
                "priority": 100,
                "mountOptions": {
                    "previews": "false",
                    "filesystem_check_changes": "true"
                },
                "storage_id": "13"
            }
        }
    }
}
```

When debugging the code here https://github.com/owncloud/core/blob/master/lib/private/files/storage/common.php#L336 the value was not set / empty array.
Will try and debug this further.

- [ ] BUG: FS option not read properly (or possibly options not stored in correct location)

Also:
- [ ] BUG: "undefined" property, possibly a bug with priority

**Comment by PVince81** [comment]
Ok, turns out the option is available, but the booleans are converted to strings somehow.
Also the watcher is not a bool but an int.

- [ ] properly convert data types (or maybe POST the data as JSON instead of form-encoded)
- [ ] use select box + int for watcher

**Comment by PVince81** [comment]
I fixed all the issues.

I also noticed that the default watcher policy (1) doesn't even seem to work ? Raised as https://github.com/owncloud/core/issues/15081

**Comment by PVince81** [comment]
Here we go Mr Jenkins https://github.com/owncloud/core/pull/15082

**Comment by MorrisJobke** [comment]
Rebase needed :(

**Comment by MorrisJobke** [comment]
Looks nice so far :)

**Comment by PVince81** [comment]
Rebased.

Note: while you can change the watcher setting, the watched might not work properly, which will be addressed in https://github.com/owncloud/core/issues/15081

**Comment by PVince81** [comment]
Jenkins PR second edition: https://github.com/owncloud/core/issues/15213

**Comment by MorrisJobke** [comment]
@PVince81 Is this ready to review or still WIP? (see label) ;)

**Comment by PVince81** [comment]
To review. Thanks.

**Comment by karlitschek** [comment]
still :+1:  from my side

**Comment by Xenopathic** [comment]
:+1:

**Comment by PVince81** [comment]
- [ ] BUG: policy value is read as string instead of int, so the policy isn't applied properly

I'm on it.

**Comment by PVince81** [comment]
Fixed reading the mount options, which now actually make the watcher work properly.
Please re-review.

To test:
1. Mount a SMB storage
2. Add a file directly on SMB
3. Refresh the web UI: new file appears
4. Set the watcher policy to "Never"
5. Create a file directly on SMB
6. Refresh the web UI: no change, new file not detected
7. Switch watcher policy to "Always" (third option)
8. Refresh the web UI: last file appears

**Comment by PVince81** [comment]
Jenkins PR: https://github.com/owncloud/core/pull/15236

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by Xenopathic** [comment]
:+1:

**Comment by oquidave** [comment]
Wouldn't it be cool to have an option that lets you mount external storage directly as a users home directory? Supposing I've owncloud installed on $5 DigitalOcean VPS. I only have about 10GB on that box. But I can buy cheaper storage from Amazon S3 and hook it up to my owncloud. But it shouldn't appear as "external storage folder". Instead, I should have the option of having an S3 bucket as the primary storage. Thanks

**Comment by PVince81** [comment]
@oquidave yes it would be cool. Please raise it as a separate ticket to make sure this doesn't get lost.

**Pull request merged**
