### PR TITLE
add example theme

### LINKED ISSUE #4031: Demo theme
Create a very simple demo theme showing what can be changed. Use just CSS, images and the defaults.php – NO TEMPLATE CHANGES.

Anyone interested, @owncloud/designers?

cc @karlitschek @schiesbn @DeepDiver1975

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix https://github.com/owncloud/core/issues/4031 – very simple example, just changing:
- logos
- main color (log in background, header, primary action button)
- names & text

Please review @owncloud/designers @karlitschek @schiesbn @pierrejochem @jon-tlmi 

capture du 2015-05-22 02 19 19
capture du 2015-05-22 02 18 48

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by pierrejochem** [comment]
Perfect :+1:

**Comment by jancborchardt** [comment]
@pierrejochem great, thanks! Hope it's ok that we don't take your pull request. :/ Just not possible due to the images. Also this example is shorter - so I hope it helps with your themes as well. :)

**Comment by pierrejochem** [comment]
@jancborchardt: So far yes ;-) and if there is something what is missing then I will make a new pull request ala Opensource!

Cheers and have a nice WE!

**Comment by jancborchardt** [comment]
Good stuff! Another review maybe @owncloud/designers?

**Comment by PVince81** [comment]
Looks nice :+1: 

Maybe the menu background color should be adapted too, I think it doesn't fit well:
examplethememenu

**Comment by schiesbn** [comment]
I think a demo theme doesn't have to be perfect... Looks nice and gives people a nice skeleton as a base for their own theme. :+1:

**Comment by pierrejochem** [comment]
@PVince81 That would be great :+1: ... but I think then the spinner-images must be added/adapted as well. @jancborchardt Correct?

**Comment by PVince81** [comment]
@jancborchardt your call about the bkg color. Feel free to merge if you choose to keep it.

**Comment by jancborchardt** [comment]
@karlitschek I would also say we can remove the https://github.com/owncloud/themes repo now. The only themes we support are the default one and the example one, both are in the core repo. The example theme in the themes repo is outdated too.

**Comment by karlitschek** [comment]
agreed. done

**Comment by jancborchardt** [comment]
:+1: good stuff

**Comment by ennnnno** [comment]
Thanks for example theme, nice! :+1:
just added logo-wide for the shared page into it

shared-page

**Comment by raghunayyar** [comment]
Woke up to see this today. Bliss. ;)

**Pull request merged**
