### PR TITLE
add target="_blank" to href in setupcheck

### PR DESCRIPTION
**Pull request by ryno83**
Simple PR for the issue #21317

### CODE REVIEW

**Comment by ryno83** [comment]
Maybe we could also add the small arrow ↗

**Comment by RealRancor** [comment]
@ryno83 You can add an:

Fixes https://github.com/owncloud/core/issues/21317

to the text of this PR and that issue will be automatically closed once this is merged.

**Comment by PVince81** [comment]
The arrow for another time maybe, let's merge this as it fixes the real issue.

:+1:

**Comment by PVince81** [comment]
Second reviewer ? @LukasReschke @MorrisJobke @rullzer

**Comment by rullzer** [comment]
:+1: 
I agree lets do the arrows in a separate PR

**Comment by LukasReschke** [comment]
This broke the unit tests on master…

**Pull request merged**
