### PR TITLE
Skip unnecessary cache updates

### PR DESCRIPTION
**Pull request by individual-it**
This is the rebased copy of the PR #18753

`OC\Files\Cache\Updater::update` does a couple of updates. Not all are needed in every case the method is called.
In this example if `touch()` only is changing the mtime we should skip the update of the folder size as that would not change.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @PVince81 @icewind1991 @schiesbn

**Comment by PVince81** [comment]
Unfortunately the code now has move to the "apps/dav" app so this would need another rebase.

But I'd like to know what @icewind1991 thinks of this approach and whether there is a better way that doesn't involve passing around a flag. Does the new improved propagation cover this ?

**Comment by PVince81** [comment]
Closing due to lack of activity. Not sure how critical the fix is. If it is, feel free to reopen/resubmit.

**Comment by PVince81** [comment]
Side note: cache update and etag propagation performance has been improved on other part of the code in 9.0/9.1

**Pull request closed without merging**
