### PR TITLE
[stable9.1] fix typo

### PR DESCRIPTION
**Pull request by butonic**
fixes a bug introduced with https://github.com/owncloud/core/pull/25845

cc @PVince81 @jvillafanez I will look for a test case to cover this in a separate PR

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by jvillafanez** [comment]
:ambulance:  :+1:

**Comment by PVince81** [comment]
this wasn't discovered by CI and likely won't either.

A local run of ./autotest-external.sh which covers some cases didn't show any failures.

**Comment by DeepDiver1975** [comment]
> A local run of ./autotest-external.sh which covers some cases didn't show any failures.

is executed by jenkins as well

**Pull request merged**
