### PR TITLE
fix broken logtimezone - backport of PR #23222

### PR DESCRIPTION
**Pull request by Phiber2000**
backported as requested

### CODE REVIEW

**Comment by Phiber2000** [comment]
**License comment**
These contributions by me are licensed under MIT.

**Comment by PVince81** [comment]
Ref #23222 (to make it a clickable link)

**Comment by Phiber2000** [comment]
(had to fix commit user - owncloud-bot was faster than me...)

**Comment by PVince81** [comment]
@owncloud-bot we need to teach you to read threads, license is here https://github.com/owncloud/core/pull/23224#issuecomment-196316652

**Comment by Phiber2000** [comment]
Should I PR a new backport which is commited in oc-repo?

**Comment by PVince81** [comment]
@Phiber2000 yes, please. That will make CI work corretcly.
Thanks.

**Comment by Phiber2000** [comment]
backport replaced by: #23235

**Pull request closed without merging**
