### PR TITLE
Move background job registration to install update

### PR DESCRIPTION
**Pull request by nickvergessen**
Remove 3 unnecessary queries per page view.

@karlitschek should really backport this to down to infinity.

cc @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
yes. please backport

**Comment by icewind1991** [comment]
:+1: makes sense

**Comment by icewind1991** [comment]
In the future it would be nice to have this moved to info.xml or something simular but for now this fixes the problem

**Comment by MorrisJobke** [comment]
Tested :+1:

**Comment by MorrisJobke** [comment]
Tests run fine locally

**Comment by MorrisJobke** [comment]
@nickvergessen Please prepare the backports

**Comment by blizzz** [comment]
Thank you @nickvergessen – please notify me about LDAP PRs as well in future.

**Pull request merged**
