### PR TITLE
Add cli test for adding, deleting and listing system and app configs

### LINKED ISSUE #33386: create acceptance tests for occ config commands (app set, system set, list...)
create cli tests for setting system and app configs

from main issue #33051

### PR DESCRIPTION
**Pull request by dpakach**
## Description

create acceptance tests for occ config commands (app set, system set, list...)

## Related Issue

- Fixes #33386
- Related to #33051

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by dpakach** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport ``stable10`` #33401

**Comment by phil-davis** [comment]
Weird PHP unit test fails related to thumbnails???
I will try to rebase again...

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
