### PR TITLE
Respect User enumeration

### PR DESCRIPTION
**Pull request by foobarable**
Respect shareapi_allow_share_dialog_user_enumeration in user_ldap filter
generation function to increase seach performance in sharing dialog.

cc @blizzz @MorrisJobke

### CODE REVIEW

**Comment by foobarable** [comment]
Should also be respected in getAdvancedFilterPartForSearch()

**Comment by MorrisJobke** [comment]
@blizzz I just discussed with @foobarable the performance of the fix that was introduced with #18353 

The question here is if this has effects to the user management search. Any idea how to handle this?

**Comment by MorrisJobke** [comment]
@owncloud-bot this is okay to test

**Comment by blizzz** [comment]
> The question here is if this has effects to the user management search. Any idea how to handle this?

I discussed this with @foobarable: Yes, it has impact, when you search for a user on the User page. However, an admin usually knows the user id, so it should not be a problem. Listings without search term work normally.

**Comment by blizzz** [comment]
> Should also be respected in getAdvancedFilterPartForSearch()

The direct approach is:

```diff
diff --git a/apps/user_ldap/lib/access.php b/apps/user_ldap/lib/access.php
index a2eb834..7f928e0 100644
--- a/apps/user_ldap/lib/access.php
+++ b/apps/user_ldap/lib/access.php
@@ -1121,8 +1121,12 @@ class Access extends LDAPUtility implements user\IUserTools {
        }
        $searchWords = explode(' ', trim($search));
        $wordFilters = array();
+       $config = \oc::$server->getConfig();
+       $allowEnum = $config->getAppValue('core', 'shareapi_allow_share_dialog_user_enumeration', false);
        foreach($searchWords as $word) {
-           $word .= '*';
+           if($allowEnum === true) {
+               $word .= '*';
+           }
            //every word needs to appear at least once
            $wordMatchOneAttrFilters = array();
            foreach($searchAttributes as $attr) {
```

It adds a bit of duplication (getting the config instance, fetching the value, modifying the search termn), this could be summed up in a method of it's own e.g. (prepareSearchTerm($term)) that returns the final search term as done by

```
$search = empty($search) ? '*' : 
     $allowEnum ? $search . '*' : $search;
```

The advanced method just calls it for every $word.

**Comment by MorrisJobke** [comment]
@foobarable Can we get the second change that was proposed by @blizzz in?

**Comment by DeepDiver1975** [comment]
we are beyond feature freeze -> 9.0

**Comment by DeepDiver1975** [comment]
@blizzz anything missing? THX

**Comment by MorrisJobke** [comment]
@foobarable Still open ;) Did you recently found time to fix the remaining stuff?

**Comment by jancborchardt** [comment]
@owncloud/ldap can you test this? You can also use this shorthand mention to get your pull requests reviewed. :)

**Comment by foobarable** [comment]
@blizzz @MorrisJobke 
So you mean like this? I have not testet this yet but can do if you think this is the correct way.
```
diff --git a/apps/user_ldap/lib/access.php b/apps/user_ldap/lib/access.php
index 667f107..b3f71a7 100644
--- a/apps/user_ldap/lib/access.php
+++ b/apps/user_ldap/lib/access.php
@@ -1193,7 +1193,7 @@ class Access extends LDAPUtility implements user\IUserTools {
                $searchWords = explode(' ', trim($search));
                $wordFilters = array();
                foreach($searchWords as $word) {
-                       $word .= '*';
+                       $word = $this->prepareSearchTerm($word);
                        //every word needs to appear at least once
                        $wordMatchOneAttrFilters = array();
                        foreach($searchAttributes as $attr) {
@@ -1226,7 +1226,8 @@ class Access extends LDAPUtility implements user\IUserTools {
                                );
                        }
                }
-               $search = empty($search) ? '*' : $search.'*';
+
+               $search = $this->prepareSearchTerm($search);
                if(!is_array($searchAttributes) || count($searchAttributes) === 0) {
                        if(empty($fallbackAttribute)) {
                                return '';
@@ -1243,6 +1244,16 @@ class Access extends LDAPUtility implements user\IUserTools {
                return $this->combineFilterWithOr($filter);
        }
 
+       private function prepareSearchTerm($term) {
+               $config = \oc::$server->getConfig();
+
+               $allowEnum = $config->getAppValue('core', 'shareapi_allow_share_dialog_user_enumeration', false);
+
+               $term = empty($term) ? '*' :
+                       $allowEnum ? $term . '*' : $term;
+               return $term;
+       }
+
        /**
         * returns the filter used for counting users
         * @return string
```

**Comment by MorrisJobke** [comment]
> So you mean like this? I

Looks good. Can you please apply the changes? (you don't need to merge in the master branch via github ;))

**Comment by blizzz** [comment]
I second @MorrisJobke

**Comment by foobarable** [comment]
The patch as i wrote it does not work yet in Version 8.2.1.4 Still trying to find out what's wrong.

**Comment by foobarable** [comment]
Created new pull request here: https://github.com/owncloud/core/pull/21324

**Pull request closed without merging**
