### PR TITLE
Fix overlapping filename and sharees

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Fix overlapping names and "sharees" if the filename is a bit longer than usual.

## Related Issue

Fixes https://github.com/owncloud/enterprise/issues/2068

## How Has This Been Tested?

Visual test in latest Google Chome

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by haukman** [comment]
just checked the patch:

grafik

Looks good!!

Will this be part of 10.0.3?

**Comment by PVince81** [comment]
Needs testing in all browsers, especially considering that we're using some modern CSS technique.

And test whether resizing the browser to smaller sizes doesn't mess up.

**Comment by haukman** [comment]
Correct - I tried it initially with FF and it looks fine. IE is also looking good - Chrome is still looking strange.

**Comment by felixheidecke** [comment]
This was just a quick shot if the result comes near what is expected. I'll go into it in more detail, especially older IE support:

> Chrome is still looking strange.

@haukman Screenshot, or it didn't happen!

**Comment by haukman** [comment]
@felixheidecke 

There you go :)

grafik

**Comment by felixheidecke** [comment]
@haukman … I hope you did purge your cache ⚓️

**Comment by haukman** [comment]
@felixheidecke: Please forgive me - you are correct: Also looking fine in Chrome!

**Comment by felixheidecke** [comment]
I tested in IE11 as well and it does work fine.
@PVince81 should we have someone else take a look at it in all browsers?

**Comment by PVince81** [comment]
@felixheidecke if you tested yourself I think it's fine to merge now.

**Comment by PVince81** [comment]
@felixheidecke please backport to stable10

**Pull request merged**
