### PR TITLE
[Stable8] Backport 14766 compare array insertifnotexists

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #14766 

@MorrisJobke @DeepDiver1975 @PVince81 @icewind1991 @LukasReschke

### CODE REVIEW

**Comment by karlitschek** [comment]
backport as discusse :+1:

**Comment by DeepDiver1975** [comment]
:-1: we wanted to wait a bit before we backport - furthermore recent tests have shown that this approach will not work on Oracel due to clob

**Comment by karlitschek** [comment]
@DeepDiver1975 ok. Do you have a timeline for that?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 ok. Do you have a timeline for that?

@nickvergessen and myself will look into this ... let's see ... maybe we merge this in one week from now - or two?

**Comment by DeepDiver1975** [comment]
> maybe we merge this in one week from now - or two?

... with the fix for oracle for sure :wink:

**Comment by nickvergessen** [comment]
> ... with the fix for oracle for sure :wink:

"Oracle" fix is included now

**Comment by nickvergessen** [comment]
@PVince81 want run your smashbox against this?

**Comment by PVince81** [comment]
I'm not sure what tests @jnfrmarks ran originally.
Currently running all the tests don't help because some are still expected to fail (cleanup in progress)

**Comment by jnfrmarks** [comment]
I ran the test_uploads.py test case multiple times in a row.

**Comment by MorrisJobke** [comment]
@jnfrmarks @PVince81 I tried to run smashbox against this, but it doesn't work well (stable8 and this branch fails) Let us have a look at this tomorrow

**Comment by MorrisJobke** [comment]
I ran smashbox 10 times with test_uploadFiles. Before 3 out of 10 runs failed, because of the database error. after this everything works without an error. :+1: from me

**Comment by nickvergessen** [comment]
@DeepDiver1975

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
