### PR TITLE
disable the recovery key if the master key is enabled

### PR DESCRIPTION
**Pull request by schiessle**
it doesn't make sense to have a recovery key if the master key is  enabled, so we don't show this option in this case.

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by schiesbn** [comment]
second reviewer... @nickvergessen  @owncloud/encryption ? Thanks!

**Comment by PVince81** [comment]
@schiesbn is this something to be backported? Probably not critical enough.

**Comment by schiesbn** [comment]
no, nothing to backport... I just want to clean up my list of open pull requests :wink:

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/pull/22792/files?w=1 makes sense

:+1:

**Pull request merged**
