### PR TITLE
Investigate phpunit out of memory problems

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #35685 

Log memory usage at various points in the testing.
After trying a few points I have narrowed the problem down to:
```
Finished Archive:TestBase:testMoveRemove
memory_get_usage 197345216
memory_get_peak_usage 199975936
Test 'Test\Archive\TARTest::testRecursive' started
[PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 65536 bytes) in /drone/src/lib/composer/pear/archive_tar/Archive/Tar.php on line 987]
[PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 65536 bytes) in /drone/src/lib/private/Shutdown/ShutDownManager.php on line 58]
[PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 167936 bytes) in Unknown on line 0]
```

`tests/lib/Arcive/TARTest` `testMoveRemove` runs fine. By that point in the unit test run, the peak memory usage has been almost 200MB. That seems reasonable.

`Test\Archive\TARTest::testRecursive` runs "for a while" and runs out of memory. The `echo` statements that I put in it do not appear in the drone log output. I guess that `phpunit` is accumulating the test output and outputting it at the end of the test. When PHP dies like this, phpunit does not get the chance to output the log information.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
You can add this to our Test Base class https://github.com/owncloud/core/blob/986b22e0e01bdb1ffc244db791d543c406c777f2/tests/lib/TestCase.php#L37

Just an idea .... 👍

**Comment by phil-davis** [comment]
Now @patrickjahns has bumped PHP to the latest ppatch versions, e.g. `7.1.30`
I got a test run that shows lots of memory being used:
```
10:06:12 Finished testRecursive
memory_get_usage 4148449504
memory_get_peak_usage 4148450064
```
It just survives inside the 4096MB limit (4294967296 bytes).

The memory usage steadily climbs as it adds files to the test archive. Here is a sample:
```
addFile /dir/themes/abc/apps/files/l10n/bn_IN.js /drone/src/tests/data/themes/abc/apps/files/l10n/bn_IN.js
memory_get_usage 3794279872
memory_get_peak_usage 3794280032
get contents /drone/src/tests/data/themes/abc/apps/files/l10n/bn_IN.js
after get contents length of source 1628
memory_get_usage 3794281568
memory_get_peak_usage 3794300888
after addString
memory_get_usage 3805815904
memory_get_peak_usage 3805822280
addFile /dir/themes/abc/apps/files/l10n/af_ZA.json /drone/src/tests/data/themes/abc/apps/files/l10n/af_ZA.json
memory_get_usage 3811451144
memory_get_peak_usage 3811451304
get contents /drone/src/tests/data/themes/abc/apps/files/l10n/af_ZA.json
after get contents length of source 3833
memory_get_usage 3811455144
memory_get_peak_usage 3811472160
after addString
memory_get_usage 3822923944
memory_get_peak_usage 3822930336
addFile /dir/setUploadLimit/htaccess /drone/src/tests/data/setUploadLimit/htaccess
memory_get_usage 3846054152
memory_get_peak_usage 3846054264
get contents /drone/src/tests/data/setUploadLimit/htaccess
after get contents length of source 2029
memory_get_usage 3846056632
memory_get_peak_usage 3846075152
after addString
memory_get_usage 3857590968
memory_get_peak_usage 3857597336
addFile /dir/setUploadLimit/user.ini /drone/src/tests/data/setUploadLimit/user.ini
memory_get_usage 3863422008
memory_get_peak_usage 3863422120
get contents /drone/src/tests/data/setUploadLimit/user.ini
after get contents length of source 165
memory_get_usage 3863422120
memory_get_peak_usage 3863443008
after addString
memory_get_usage 3874890920
memory_get_peak_usage 3874897288
addFile /dir/testavatar.png /drone/src/tests/data/testavatar.png
memory_get_usage 3880789408
memory_get_peak_usage 3880789504
get contents /drone/src/tests/data/testavatar.png
after get contents length of source 3705
memory_get_usage 3880793440
memory_get_peak_usage 3880810400
after addString
memory_get_usage 3892262240
memory_get_peak_usage 3892268600
```

**Comment by phil-davis** [comment]
I tried going back to `pear/archive_tar 1.4.6` - that makes no difference:
```
- Installing pear/archive_tar (1.4.6): Loading from cache
11:03:09 Starting Archive:TestBase:testRecursive
memory_get_usage 194978280
memory_get_peak_usage 199748976

11:04:11 Finished testRecursive
memory_get_usage 4148173112
memory_get_peak_usage 4148173672
```

`testRecursive` runs for more than 1 minute and eats up nearly all the available memory.

**Comment by phil-davis** [comment]
Enabling garbage collection does the trick - `zend.enable_gc=1`

```
addFile /dir/testimage.gif /drone/src/tests/data/testimage.gif
memory_get_usage 160436032
memory_get_peak_usage 176615680
get contents /drone/src/tests/data/testimage.gif
after get contents length of source 362
memory_get_usage 160436416
memory_get_peak_usage 176615680
after addString
memory_get_usage 160436416
memory_get_peak_usage 176615680
addFile /dir/testimage.jpg /drone/src/tests/data/testimage.jpg
memory_get_usage 160436840
memory_get_peak_usage 176615680
get contents /drone/src/tests/data/testimage.jpg
after get contents length of source 25392
memory_get_usage 160465448
memory_get_peak_usage 176615680
after addString
memory_get_usage 160465448
memory_get_peak_usage 176615680
addFile /dir/data.zip /drone/src/tests/data/data.zip
memory_get_usage 160437632
memory_get_peak_usage 176615680
get contents /drone/src/tests/data/data.zip
after get contents length of source 4705
memory_get_usage 160445768
memory_get_peak_usage 176615680
after addString
memory_get_usage 160445768
memory_get_peak_usage 176615680
11:35:03 Finished addRecursive
memory_get_usage 160024592
memory_get_peak_usage 176615680
11:35:03 Finished testRecursive
memory_get_usage 160438048
memory_get_peak_usage 176615680
```

Now we get a peak memory use of only 176MB.

I guess that setting is turned off in the default docker PHP.

**Comment by phil-davis** [comment]
This was just a "test" PR to gather phpunit memory usage information

**Pull request closed without merging**
