### PR TITLE
Validate email address in mail settings

### LINKED ISSUE #28436: Admin Settings: Email From address takes any value
In the admin general settings, section email server _from address_ is accepting any character as valid value. Even when I enter an @ into both fields this is accepted.

This issue stumbled upon me, when a client entered a trailing comma for the user part by mistake (which prevented the mailer from sending emails)

There should be a check on valid email addresses.

### PR DESCRIPTION
**Pull request by PVince81**
Resend of https://github.com/owncloud/core/pull/28948

Fixes https://github.com/owncloud/core/issues/28436

### CODE REVIEW

**Comment by mmattel** [comment]
Q: would it be an idea to split the error message into ``mail_from_address`` and ``$mail_domain`` parts?
That would guide better to the point of problem...

**Comment by PVince81** [comment]
Rebased to kick Drone

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
unrelated ?

```
rerun failed tests: /drone/src/tests/ui/features/files/deleteFilesFolders.feature:12
@insulated
Feature: deleting files and folders
  As a user
  I want to delete files and folders
  So that I can keep my filing system clean and tidy

  Background:                            # /drone/src/tests/ui/features/files/deleteFilesFolders.feature:7
    Given a regular user exists          # FeatureContext::aRegularUserExists()
    And I am logged in as a regular user # FeatureContext::iAmLoggedInAsARegularUser()
    And I am on the files page           # FilesContext::iAmOnTheFilesPage()

  Scenario: Delete files & folders one by one and check its existence after page reload # /drone/src/tests/ui/features/files/deleteFilesFolders.feature:12
Error while deleting file
-------------------------
unknown error: Element <a href="#" class="menuitem action action-delete permanent" data-action="Delete">...</a> is not clickable at point (726, 856). Other element would receive the click: <a href="#" class="menuitem action action-rename permanent" data-action="Rename">...</a>
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.0-26-generic x86_64)
-------------------------

INFORMATION: retried to delete file 'lorem.txt' 1 times
Error while deleting file
-------------------------
unknown error: Element <a href="#" class="menuitem action action-delete permanent" data-action="Delete">...</a> is not clickable at point (726, 856). Other element would receive the click: <span>...</span>
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.0-26-generic x86_64)
-------------------------

Error while deleting file
Error while deleting file
-------------------------
Page\FilesPageElement\FileActionsMenu::findButton xpath //a[@data-action='Delete'] could not find button 'Delete' in action Menu
-------------------------

Error while deleting file
-------------------------
unknown error: Element <a href="#" class="menuitem action action-delete permanent" data-action="Delete">...</a> is not clickable at point (726, 856). Other element would receive the click: <a href="#" class="menuitem action action-rename permanent" data-action="Rename">...</a>
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.0-26-generic x86_64)
-------------------------

Error while deleting file
-------------------------
Element not found with xpath, ((//html//div[contains(@class,'fileActionsMenu')])[1]//a[@data-action='Delete'])[1]

no such element: Unable to locate element: {"method":"xpath","selector":"((//html//div[contains(@class,'fileActionsMenu')])[1]//a[@data-action='Delete'])[1]"}
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.0-26-generic x86_64)
-------------------------

INFORMATION: retried to delete file 'strängé filename (duplicate #2 &).txt' 5 times
    When I delete the elements                                                          # FilesContext::iDeleteTheElements()
      | name                                  |
      | simple-folder                         |
      | lorem.txt                             |
      | strängé नेपाली folder                 |
      | strängé filename (duplicate #2 &).txt |
      │ INFORMATION: retried to delete file 'lorem.txt' 1 timesINFORMATION: retried to delete file 'strängé filename (duplicate #2 &).txt' 5 times
    Then the deleted elements should not be listed                                      # FilesContext::theDeletedMovedElementsShouldBeListed()
      Failed asserting that '' contains "could not find file with the name 'strängé filename (duplicate #2 &).txt'".
    And the deleted elements should not be listed after a page reload                   # FilesContext::theDeletedMovedElementsShouldBeListedAfterPageReload()

--- Failed scenarios:

/drone/src/tests/ui/features/files/deleteFilesFolders.feature:12
```

@phil-davis

**Comment by phil-davis** [comment]
Yes, unrelated. Nothing in those file delete tests has anything to do with validating email addresses.
I restarted the drone job.

**Comment by PVince81** [comment]
Merging, approved from original PR

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/30315

**Pull request merged**
