### PR TITLE
Remove depreciated function which is not in interface specification

### PR DESCRIPTION
**Pull request by mrow4a**
## Description

This function is not in ICache interface, is depreciated and no longer used (in legal way I know at least)

## How Has This Been Tested?

Unit/integration tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
Unit test fails in ``tests/lib/Files/Cache/CacheTest.php`` which uses ``getById``

**Comment by mrow4a** [comment]
Sorry forgot to push unit tests, will do later.

**Comment by mrow4a** [comment]
⚔️ with 🔥 ? @DeepDiver1975 @PVince81

**Comment by mrow4a** [comment]
-0.01% code coverage difference, interesting :>

**Comment by phil-davis** [comment]
``getAll`` and ``getById`` look like they had better than the project average test coverage. So when the code+tests are deleted, the average project coverage goes down.

It would be nice if codecov could notice that the PR is all code+test removal, and in that case not fail.

**Review by PVince81 — APPROVED** [review]
Ok for OC11

**Pull request merged**
