### PR TITLE
Log errors and create 404 in network list when a css or js is missing

### PR DESCRIPTION
**Pull request by nickvergessen**
instead of throwing an Exception.

As discussed @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Tested with "Imprint" from the apps repo:
1) Checkout this commit: https://github.com/owncloud/apps/commit/931e969af03d4974fcaf86f573bc9c8eafb5d33b (that was before the "chosen" fix, there's a failing CSS and JS)
2) Enable imprint app
3) Go to "Admin" page: boom
4) Switch to this PR's branch. admin page displayed properly! JS console containing load errors.

Works.

Can you fix the warnings:
```
{"reqId":"3PyLzmKTbOCBSbsYshPz","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/template\/resourcelocator.php#77","level":0,"time":"2015-03-04T13:50:20+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}
{"reqId":"3PyLzmKTbOCBSbsYshPz","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/template\/resourcelocator.php#77","level":0,"time":"2015-03-04T13:50:20+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin"}
```

**Comment by MorrisJobke** [comment]
Awesome :+1: Log awaited and really needed. This will also remove a lot of those white pages of death.

**Comment by MorrisJobke** [comment]
Ah ... I tested this of course ;)

**Comment by rullzer** [comment]
Very nice! Working as expected. :+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Do we want this in that way?

**Comment by LukasReschke** [comment]
In my PoV a hard-failure is way better than leaving to some half-broken state that are horrible to debugs and users tend to look never at the log.

I really prefer the hard-fail…

**Comment by LukasReschke** [comment]
Or if something failed in an app.php we should not load the app at all…

**Comment by PVince81** [comment]
@LukasReschke we cannot detect fails in app.php.
This block:
```php
try { require_once "somefile.php" } catch (\Exception $e) {}}
```
doesn't catch any exception that happen in somefile.php...

The hard fail is more likely to lock users out of functionality (ex: admin page not reachable due to Imprint's section there that requires a missing chosen.js, which is ridiculous)

**Comment by LukasReschke** [comment]
Well – I didn't say :-1: on that one. If this is the easiest/best solution from a technical PoV we should get it in :smile:

**Comment by PVince81** [comment]
Just had a try: if the required script throws an exception explicitly, it can be caught.
But if you try and load a non-existing class, it fails fatally and cannot be caught.
Also found this: http://stackoverflow.com/questions/4421320/why-doesnt-php-catch-a-class-not-found-error

**Comment by PVince81** [comment]
Putting that info there: https://github.com/owncloud/core/issues/5508

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
