### PR TITLE
[stable10] Add php-intl as hard requirement

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Backport of https://github.com/owncloud/core/pull/29500 to stable10

## Related Issue
https://github.com/owncloud/core/issues/29247

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by Ablablab** [comment]
this makes Owncloud incompatible with Qnap Nas (no php_intl available).

**Comment by jvillafanez** [comment]
According to the official PHP documentation, the php bindings should be already available since they're bundled with PHP, but you'll need the native ICU library (http://php.net/manual/en/intl.requirements.php)
The ubuntu package for the ICU library is libicu52. You might want to check a similar package is available.

**Comment by Ablablab** [comment]
Qnap Nas have PHP 5.6 builtin. No package for libicu52 or php-intl is available. I suggest to remove Owncloud from Qnap Package store because it is not compatible anymore cause this hard dependency.

**Comment by patrickjahns** [comment]
@Ablablab 
There are alternative packages for QNAP - for example: https://forum.qnap.com/viewtopic.php?f=320&t=110391

**Comment by Ablablab** [comment]
but it's not stock on Qnap and requires 64bit hardware. I just suggest to remove the Owncloud from Qnap package store, not from the forum.

**Comment by patrickjahns** [comment]
@Ablablab 
As far as I know - the package is not maintained nor provided by us - so most likely you need to write an email to the contact in the qnap spackage store and seek the discussion with the maintainer

**Pull request merged**
