### PR TITLE
changed ZipStreamer to use composer for updates, update to 0.7

### PR DESCRIPTION
**Pull request by McNetic**
This is the necessary (really very small) change necessary to bump ZipStreamer to v0.7 (as discussed in #10001). Additionally, Zipstreamer is not referenced via composer properly. Also requires corresponding pull request owncloud/3rdparty#196.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
THX @McNetic

**Comment by PVince81** [comment]
Zip download still works :+1:

**Comment by PVince81** [comment]
@McNetic can you update the 3rdparty commit id ? After merging in the other repo it usually changes due to the merge commit. Hopefully pushing here will awaken CI again...

**Comment by McNetic** [comment]
Ugh. I'd really like to. How do I do that?

**Comment by PVince81** [comment]
`cd 3rdparty; git pull origin master`
Then add it to a commit, it should now point to https://github.com/owncloud/3rdparty/commit/6b6575b04c01e30e5f38dbb373fd5166cce0ef54 (you should see it in the diff)

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/pull/19028 was merged where ci did pass - THX @McNetic

**Comment by McNetic** [comment]
This also fixes #12505.

**Pull request merged**
