### PR TITLE
Drop example user backend

### PR DESCRIPTION
**Pull request by LukasReschke**
We already provide an interface for application developers, this file is outdated and thus should get removed.

Addresses No. 3 from https://github.com/owncloud/core/issues/14847

cc @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/blob/0d9f149dd93997085b85e2b174f5989a1b996263/lib/private/user/backend.php#L56 <- please also update this to point at our Interface (or simply drop the part)

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
