### PR TITLE
Rename share icon to be adblock friendly

### LINKED ISSUE #33642: Print a warning when ad-blockers are breaking sharing functions?
Look at https://github.com/owncloud/core/issues/33579 for motivation.

In short: for days I was investigating where the sharing functionalities have gone. They disappeared out of a sudden. Until I realised my ad-blocker (uBlock Origin) was the cause.

In this ticket I suggest to implement an ad-block detection and to print a warning. That would have saved me lots of hours and will for others too in future.

### LINKED ISSUE #35070: Adblock admin sharing settings hiding
### Steps to reproduce
1. Enabled Adblock
2. Check admin settings
3. Disabled Adblock
4. Check again addmin settings

### Expected behaviour
Warning on Adblock shown or sharing icon shown.

Maybe use idea by https://github.com/sualko/cloud_piwik/pull/65 or by https://github.com/nextcloud/server/pull/4337?

### Actual behaviour
With Adblock no sharing icon

admin_adblock

Without Adblock sharing icon

admin_noadblock

### Server configuration
**ownCloud version:** 10.1.1

### Client configuration
**Browser:** Firefox 66.0.3 + Adblock +

Adblock Warning Removal List
Fanboy's Social Blocking List
ABP filters
EasyList
Allow nonintrusive advertising without third-party tracking

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
This PR renames 'icon-share' to 'icon-shared' to be Adblock friendly. Also, we have two duplicated icon for share:
- https://github.com/owncloud/core/blob/master/core/img/actions/shared.svg
- https://github.com/owncloud/core/blob/master/core/img/actions/share.svg 
With this PR core will not use `share.svg` anymore. However, since some of the apps (Activity, Contacts) still using `share.svg`, I did not touch it. If we migrate them to use `shared.svg`, we can delete duplicated `share.svg`. @PVince81 Should we spend time for it? It will require re-release these apps.

As @PVince81 stated https://github.com/owncloud/core/issues/35070#issuecomment-486668832,  this PR could have an impact on some themes that might use 'icon-share', so would consider this a breaking change that needs mentioning in release notes. @pmaier1 FYI.

## Related Issue
- Fixes #35070
- Fixes #33642

## Motivation and Context
Users using an advertisement blocker extension on the browser can not see 'icon-share' and this situation reducing user experience.

## How Has This Been Tested?
1- Enable AdblockPlus Mozilla extension and also open blocking social media icons tracking
2- Share Icons should be visible (It should be not visible on the current master).

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation ticket raised: 

## Open tasks:
- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
for backward compatibility and theming we could keep the old one as well to avoid breakage.

however themes that override this icon in the files app would also need adjusting, this is something we can state in the release notes

**Comment by karakayasemi** [comment]
I added some tests to pass from codecov diff coverage check.

**Comment by karakayasemi** [comment]
@ownclouders rebase

**Comment by karakayasemi** [comment]
Codecov was complaining about missing coverage on `share.js/uptadeIcon` method. When I check it on my IDE, I saw it marked as an unused function. I searched it organization-wide on GitHub and search with grep in my local, I could not find any usage as IDE said. So, I removed it instead of adding redundant js test.

**Review by jvillafanez — APPROVED** [review]
Assuming there isn't any additional change to be done and we're replacing everything we need to replace

**Comment by karakayasemi** [comment]
Yepp, nothing left in core. We kept `share.svg` for some of the apps.

**Comment by karakayasemi** [comment]
- Backport in here: https://github.com/owncloud/core/pull/35199,
- Docs update in here: https://github.com/owncloud/docs/pull/1183

**Comment by ho4ho** [comment]
Contacts app by https://github.com/owncloud/contacts/pull/663

Not sure with activity:

https://github.com/owncloud/activity/blob/723e5ba848a0ddde1b0f0aea2af333709e8299c7/tests/acceptance/features/apiActivity/list.feature
https://github.com/owncloud/activity/blob/df83d97489b38f275f2cfc3c017282f0d8790abb/css/style.css#L194

**Pull request merged**
