### PR TITLE
[stable8.1] fix getting mount points when passing a path to the files:scan command

### PR DESCRIPTION
**Pull request by MorrisJobke**
backport #17077 which was opened against 8.1.0

cc @cmonteroluque @karlitschek @DeepDiver1975 @PVince81 @icewind1991 

Feel free to move to to 8.1.1

### CODE REVIEW

**Comment by PVince81** [comment]
Let's move to 8.1.1. The original ticket was actually set to 8.2...

**Comment by MorrisJobke** [comment]
> Let's move to 8.1.1. The original ticket was actually set to 8.2...

Yes, because I changed it, because otherwise I will be very confused in 4-6 months, when I need to check which change went into which version ;)

bildschirmfoto von 2015-07-02 13-32-01

**Comment by MorrisJobke** [comment]
Ah... the original ticket (not the fixing PR) was 8.2. Okay. Then better do this with 8.1.1

**Comment by karlitschek** [comment]
backport is fine but for 8.1.1 please :-)

**Comment by PVince81** [comment]
Could not test this, seems the CLI options parser is broken on my env: https://github.com/owncloud/core/issues/17414

**Comment by PVince81** [comment]
Tested with `./occ files:scan --path="/user1/files/sftp/"`
The external storage was scanned properly.

:+1:

**Comment by MorrisJobke** [comment]
As I only cherry picked the stuff in here: I tested this and on stable8.1 it doesn't scan and with this it scans successfully an external storage. :+1:

**Comment by PVince81** [comment]
Seems we should also backport this to 8.0 as it fixes "occ files:scan" issue where ext storages aren't scanned at all.

@karlitschek @DeepDiver1975 @MorrisJobke what do you think ?

Ref: https://github.com/owncloud/enterprise/issues/1330

**Comment by karlitschek** [comment]
i agree. this is bad enough. please backport

**Comment by MorrisJobke** [comment]
@icewind1991 Ping - please backport :)

**Comment by PVince81** [comment]
I made a partial backport here https://github.com/owncloud/core/pull/24901, to fix https://github.com/owncloud/enterprise/issues/1330

**Pull request merged**
