### PR TITLE
Add capability for blacklisted files regex

### PR DESCRIPTION
**Pull request by JammingBen**
## Related Issue

- Needed for https://github.com/owncloud/web/issues/5518

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by kulmann — COMMENTED** [review]
Thanks for taking care 🚀 
Not sure if the duplication in `BLACKLIST_FILES_REGEX` vs `BLACKLIST_FILES_EXTENSIONS` is acceptable, since I'm not a maintainer of this repo... 

Seeing the code here now, I'd also be fine having the `blacklisted_files_regex` as an additional capability, instead of adding the new `blacklisted_files_extensions`.

**Comment by JammingBen** [comment]
> Not sure if the duplication in BLACKLIST_FILES_REGEX vs BLACKLIST_FILES_EXTENSIONS is acceptable, since I'm not a maintainer of this repo...

Thought about that too while implementing. Cleanest approach IMO would be for `BLACKLIST_FILES_REGEX` to consume `BLACKLIST_FILES_EXTENSIONS` and then build the regex part on top of it. But that's not possible without breaking anything :/ If you're fine with `blacklisted_files_regex`, I think I also prefer this solution.

**Comment by kulmann** [comment]
> > Not sure if the duplication in BLACKLIST_FILES_REGEX vs BLACKLIST_FILES_EXTENSIONS is acceptable, since I'm not a maintainer of this repo...
> 
> Thought about that too while implementing. Cleanest approach IMO would be for `BLACKLIST_FILES_REGEX` to consume `BLACKLIST_FILES_EXTENSIONS` and then build the regex part on top of it. But that's not possible without breaking anything :/ If you're fine with `blacklisted_files_regex`, I think I also prefer this solution.

Cool, then let's switch over to `blacklisted_files_regex` in the capabilities 👍

**Review by kulmann — APPROVED** [review]
Awesome, thanks for taking care! 🚀 🥳

**Review by phil-davis — APPROVED** [review]
LGTM - I pushed an acceptance test scenario for the new capability.

**Pull request merged**
