### PR TITLE
Change visibility of php variables and functions

### PR DESCRIPTION
**Pull request by paurakhsharma**
## Description
PHP functions and variables whose visibility can be changed to private are changed

## Motivation and Context
Clean up code

## How Has This Been Tested?
Locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Please have a look if there is a php-cs-fixer rules for this - THX

**Comment by phil-davis** [comment]
@paurakhsharma drone fails here - please look

**Review by phil-davis — APPROVED** [review]
Looks good. The latest drone passed but somehow did not report back here to GitHub. I restarted drone - let's see.

**Comment by phil-davis** [comment]
@paurakhsharma drone is not reporting its success here.
Please rebase to latest master and force push.

**Comment by phil-davis** [comment]
Note: Trashbin ``restore.feature`` file somehow had CRLF Windows-style line endings. The changes here correct those. There is no change to the real content of that file.

**Comment by paurakhsharma** [comment]
Backport in #31324

**Pull request merged**
