### PR TITLE
fix search for results only from subfolder

### LINKED ISSUE #16878: Search result misalignment if only results from subfolder
If there are no results in the current folder, the folder list is not shown. This leads to this error:
music search mislayout

Which is caused by the CSS which uses a negative margin-top to counter the whitespace on the bottom of the normal filelist. If the normal filelist doesn’t exist, there’s no whitespace to counter and instead the other search results are pushed up even more.

cc @owncloud/designers @aidanamavi @colmoneill anyone want to pick this up?

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/owncloud/core/issues/16878

 @jancborchardt I added the class `filter-empty` now it is your turn to add the css magic.

### CODE REVIEW

**Comment by schiesbn** [comment]
@jancborchardt now it is ready for you class is called "filter-empty"

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by jancborchardt** [comment]
Done, please review @owncloud/designers @th3fallen @VicDeo

**Comment by jancborchardt** [comment]
@owncloud-bot retest this please

**Comment by jancborchardt** [comment]
@DeepDiver1975 @schiesbn Jenkins having problems again maybe? Seems to break in the setup phase.

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 @schiesbn Jenkins having problems again maybe? Seems to break in the setup phase.

Yes. Because of a poweroutage at our build slaves housing ;)

**Comment by schiesbn** [comment]
tested, css changes from @jancborchardt works as expected :+1: for this part

**Comment by VicDeo** [comment]
:+1:  
tested too, waiting for the build to complete

**Comment by jancborchardt** [comment]
(@schiesbn btw, I changed the .filter-empty class to be on the #searchresults element instead because for some reason the CSS sibling selector `~` didn’t work. Maybe a performance thing.)

**Comment by th3fallen** [comment]
:+1: works here

**Pull request merged**
