### PR TITLE
[stable8] Fix share permission checks

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/13802 to stable8

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
Ran the smashbox test https://github.com/owncloud/smashbox/pull/38 and it worked fine.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Pull request merged**
