### PR TITLE
[backport] [stable8] LDAP: attempt to connect to backup server again, if main server is no…

### LINKED ISSUE #18701: Backup Host for LDAP server does not automatically connect
### Steps to reproduce
1. Setup an LDAP connection with a Backup server
2. Block the network access to the main LDAP server -- To simulate failure, I've added an entry to the owncloud host file pointing the ldap server to localhost, when this is in place users are unable to login to the web interface with the error "An internal error occurred.
3.

### Expected behaviour
Once the Main LDAP server is unreachable, the Backup server should be used for connections

### Actual behaviour
Errors are displayed when a user attempts to login. Logins will happen if the check box disable main server is enabled, so we are certain the backup host configuration is correct.
```
{"app":"handleLogin","message":"OC\\ServerNotAvailableException: Lost connection to LDAP server.","level":4,"time":"2015-08-28T09:23:44-06:00"}
{"app":"handleLogin","message":"OC\\ServerNotAvailableException: Lost connection to LDAP server.","level":4,"time":"2015-08-28T09:25:31-06:00"} 
```

### Server configuration
**Operating system**: RHEL 6

**Web server:** Apache

**Database:** Oracle

**PHP version:** 5.4.40

**ownCloud version:** 7.0.8

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** See config report https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F18701

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration
See config report

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"app":"handleLogin","message":"OC\\ServerNotAvailableException: Lost connection to LDAP server.","level":4,"time":"2015-08-28T09:23:44-06:00"}
{"app":"handleLogin","message":"OC\\ServerNotAvailableException: Lost connection to LDAP server.","level":4,"time":"2015-08-28T09:25:31-06:00"} 
```

### PR DESCRIPTION
**Pull request by blizzz**
…t available. Fixes #18701 

Backport of #20271

@davitol @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Doesn't work:

bildschirmfoto 2015-11-06 um 15 32 06


I would also say, that a backport to stable8 is not really worth the effort. What is your opinion @karlitschek @blizzz ? Stable8 has also other problems with regards to error handling of unavailable LDAP servers (I just noticed this while testing, because it behaved a lot different in comparison to stable8.1 or 8.2)

**Comment by blizzz** [comment]
Tried again, but still works for me. Was your backup host set up correctly and running?

**Comment by davitol** [comment]
I got the same behaviour as @MorrisJobke.

**Comment by blizzz** [comment]
@davitol same question as above.

**Comment by MorrisJobke** [comment]
> @davitol same question as above.

I did the same setup as on stable8.1 where it worked.

**Comment by blizzz** [comment]
> I did the same setup as on stable8.1 where it worked.

I did not do it differently… occ show-config?

**Comment by davitol** [comment]
> I did the same setup as on stable8.1 where it worked.

Same as @MorrisJobke 

@blizzz Just contact me via IRC and I show you my personal LDAP config shown by ldap:show-config

**Comment by PVince81** [comment]
Any update ? Has the configuration been shared ?

**Comment by cmonteroluque** [comment]
@davitol ping

**Comment by blizzz** [comment]
nothing since yet

**Comment by cmonteroluque** [comment]
@davitol @rperez we need some focus on this, please

**Comment by davitol** [comment]
@cmonteroluque configuration shared via irc

**Comment by blizzz** [comment]
Works for me there just as well.

**Comment by davitol** [comment]
:+1: It works. In 8.0 you need to press the Save button :see_no_evil:

Thanks @blizzz for all

**Comment by PVince81** [comment]
The code looks good :+1: 

Let's merge this.

**Comment by cmonteroluque** [comment]
@davitol @blizzz @PVince81 thank you

**Pull request merged**
