### PR TITLE
McNetic zipstreamer

### PR DESCRIPTION
**Pull request by DeepDiver1975**
rebased and hijacked version of https://github.com/owncloud/core/pull/6893

@McNetic Thanks a lot! Awesome work!

@PVince81 @butonic @kabum @blizzz @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Is there any chance to backport this to stable6? @cdamken Asked for this.

**Comment by cdamken** [comment]
The problem that I have is with Japanese file-names become garbled when downloaded in zip
In oC7 Works fine but oC6 is a problem

00002918

**Comment by DeepDiver1975** [comment]
> In oC7 Works fine but oC6 is a problem

-> upgrade :speak_no_evil:

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Is there any chance to backport this to stable6?

no

**Comment by cdamken** [comment]
@DeepDiver1975  I tested with oC 7.0.4 which is running as our lab, and the result was same with what you observed in oC7 (with the Japanese characters)
With Windows default tool the characters were garbled, but with Winrar it was fine.

**Comment by DeepDiver1975** [comment]
> With Windows default tool the characters were garbled, but with Winrar it was fine.

yes - please open an issue at Microsoft :speak_no_evil:

**Comment by DeepDiver1975** [comment]
ref http://superuser.com/questions/330760/view-properly-file-names-inside-a-zip-file-in-windows-1251cyrillic-encoding

**Pull request merged**
