### PR TITLE
[stable10] Add email option to user:add command

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/core/pull/28122

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: assuming you retested this

**Comment by tomneedham** [comment]
Yep

**Comment by PVince81** [comment]
you got to be kidding me... old randomly failing zombie?!
```
sharing.Merging shares for recipient when shared from outside with group then user and recipient renames in between
```

**Comment by PVince81** [comment]
zombie killer: https://github.com/owncloud/core/pull/28310

**Pull request merged**
