### PR TITLE
Add mod_proxy_fcgi to .htaccess

### PR DESCRIPTION
**Pull request by ghost**
mod_proxy_fcgi seems to be a new way for Apache and php5-fpm which needs this line:

https://forum.owncloud.org/viewtopic.php?f=31&t=29720#p93713
https://forum.owncloud.org/viewtopic.php?f=14&t=29732#p93792

### CODE REVIEW

**Comment by RealRancor** [comment]
MIT licensed.

This line is also recommended in https://github.com/owncloud/core/issues/11779, https://github.com/owncloud/core/issues/7719 and some other issues.

**Comment by RealRancor** [comment]
Btw. i have no idea about mod_proxy_fcgi or mod_fcgid... :see_no_evil:

**Comment by idefix6** [comment]
If you need me to test a modification, please let me know.
Currently it is working if for apache in the virtual host this line is defined:
```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```

**Comment by RealRancor** [comment]
Not sure if mod_fastcgi.c should be also added. Any opinions about that?

@idefix6 Sure, testing is always welcome. Personally i don't have such an environment so i can't test that.

**Comment by RealRancor** [comment]
Just added also mod_fastcgi. Probably worth as there might be still a lot of legacy apaches out there.

**Comment by oparoz** [comment]
Tested with a properly configure vhost which already included the proper directives and there were no conflicts, so :+1:

**Comment by idefix6** [comment]
I tested it, is not working.

**Comment by RealRancor** [comment]
@idefix6 Have you enabled the two needed modules "mod_headers" and "mod_setenvif"?

As the line is the same as you're currently using it just "can't work".

**Comment by DeepDiver1975** [comment]
@LukasReschke

**Comment by idefix6** [comment]
I understand your problems. Maybe the easiest solution is if you setup the environment by yourself.
It is really easy, I will post what is necessary.
Versions I used are apache 2.4.16 (I think every version higher then 2.4.10 should be fine). Php 5.6.11.
Make sure the following modules are loaded additional to the ones owncloud requires:
```
LoadModule proxy_module libexec/apache24/mod_proxy.so
LoadModule proxy_fcgi_module libexec/apache24/mod_proxy_fcgi.so
```
Do not load php module in apache or any other fcgi modules!

Create a new virtual host like:
```
<VirtualHost  _IP_TO_LISTEN>         # owncloud.domain.de
ServerName owncloud.domain.de
ServerAdmin webmaster@domain.de
DocumentRoot /usr/local/www/owncloud
ErrorLog /usr/home/http/owncloud.domain.de/logs/error.log
TransferLog /usr/home/http/owncloud.domain.de/logs/access.log
CustomLog /usr/home/http/owncloud.domain.de/logs/custom.log combined
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

 <Directory /usr/local/www/owncloud>
  AllowOverride All
  Options Indexes Includes FollowSymLinks
  Require all granted
 </Directory>

ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://localhost:9000/usr/local/www/owncloud/$1
</VirtualHost>
```

Make sure php-fpm is running, I use a standard php-fpm config file that comes with freebsd.
I had nothing to change.
```
[global]
pid = run/php-fpm.pid

[www]
user = www
group = www
listen = 127.0.0.1:9000
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
```
Make sure php-fpm is running and listening on port 9000.

Now reload apache, create a new database for owncloud and connect a mobile owncloud app or the client from windows to this installation.
Remove the line from the virtual host entry:
```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```
and restart apache, you directly see that you cannot connect anymore to the system. Add the line again, reload apache and connection works fine again.

I hope that helps you to reproduce the problem easily.

**Comment by idefix6** [comment]
@RealRancor 
yes, the modules are loaded. I use the following modules:
```
LoadModule authn_file_module libexec/apache24/mod_authn_file.so
LoadModule authn_dbm_module libexec/apache24/mod_authn_dbm.so
LoadModule authn_anon_module libexec/apache24/mod_authn_anon.so
LoadModule authn_dbd_module libexec/apache24/mod_authn_dbd.so
LoadModule authn_socache_module libexec/apache24/mod_authn_socache.so
LoadModule authn_core_module libexec/apache24/mod_authn_core.so
LoadModule authz_host_module libexec/apache24/mod_authz_host.so
LoadModule authz_groupfile_module libexec/apache24/mod_authz_groupfile.so
LoadModule authz_user_module libexec/apache24/mod_authz_user.so
LoadModule authz_dbm_module libexec/apache24/mod_authz_dbm.so
LoadModule authz_owner_module libexec/apache24/mod_authz_owner.so
LoadModule authz_dbd_module libexec/apache24/mod_authz_dbd.so
LoadModule authz_core_module libexec/apache24/mod_authz_core.so
LoadModule access_compat_module libexec/apache24/mod_access_compat.so
LoadModule auth_basic_module libexec/apache24/mod_auth_basic.so
LoadModule auth_form_module libexec/apache24/mod_auth_form.so
LoadModule auth_digest_module libexec/apache24/mod_auth_digest.so
LoadModule allowmethods_module libexec/apache24/mod_allowmethods.so
LoadModule file_cache_module libexec/apache24/mod_file_cache.so
LoadModule cache_module libexec/apache24/mod_cache.so
LoadModule cache_disk_module libexec/apache24/mod_cache_disk.so
LoadModule cache_socache_module libexec/apache24/mod_cache_socache.so
LoadModule socache_shmcb_module libexec/apache24/mod_socache_shmcb.so
LoadModule socache_dbm_module libexec/apache24/mod_socache_dbm.so
LoadModule socache_memcache_module libexec/apache24/mod_socache_memcache.so
LoadModule macro_module libexec/apache24/mod_macro.so
LoadModule dbd_module libexec/apache24/mod_dbd.so
LoadModule dumpio_module libexec/apache24/mod_dumpio.so
LoadModule buffer_module libexec/apache24/mod_buffer.so
LoadModule ratelimit_module libexec/apache24/mod_ratelimit.so
LoadModule reqtimeout_module libexec/apache24/mod_reqtimeout.so
LoadModule ext_filter_module libexec/apache24/mod_ext_filter.so
LoadModule request_module libexec/apache24/mod_request.so
LoadModule include_module libexec/apache24/mod_include.so
LoadModule filter_module libexec/apache24/mod_filter.so
LoadModule substitute_module libexec/apache24/mod_substitute.so
LoadModule sed_module libexec/apache24/mod_sed.so
LoadModule deflate_module libexec/apache24/mod_deflate.so
LoadModule mime_module libexec/apache24/mod_mime.so
LoadModule log_config_module libexec/apache24/mod_log_config.so
LoadModule log_debug_module libexec/apache24/mod_log_debug.so
LoadModule logio_module libexec/apache24/mod_logio.so
LoadModule env_module libexec/apache24/mod_env.so
LoadModule cern_meta_module libexec/apache24/mod_cern_meta.so
LoadModule expires_module libexec/apache24/mod_expires.so
LoadModule headers_module libexec/apache24/mod_headers.so
LoadModule unique_id_module libexec/apache24/mod_unique_id.so
LoadModule setenvif_module libexec/apache24/mod_setenvif.so
LoadModule version_module libexec/apache24/mod_version.so
LoadModule remoteip_module libexec/apache24/mod_remoteip.so
LoadModule proxy_module libexec/apache24/mod_proxy.so
LoadModule proxy_fcgi_module libexec/apache24/mod_proxy_fcgi.so
LoadModule session_module libexec/apache24/mod_session.so
LoadModule session_cookie_module libexec/apache24/mod_session_cookie.so
LoadModule session_crypto_module libexec/apache24/mod_session_crypto.so
LoadModule ssl_module libexec/apache24/mod_ssl.so
LoadModule lbmethod_byrequests_module libexec/apache24/mod_lbmethod_byrequests.so
LoadModule lbmethod_bytraffic_module libexec/apache24/mod_lbmethod_bytraffic.so
LoadModule lbmethod_bybusyness_module libexec/apache24/mod_lbmethod_bybusyness.so
LoadModule unixd_module libexec/apache24/mod_unixd.so
LoadModule status_module libexec/apache24/mod_status.so
LoadModule autoindex_module libexec/apache24/mod_autoindex.so
LoadModule asis_module libexec/apache24/mod_asis.so
LoadModule info_module libexec/apache24/mod_info.so
LoadModule cgi_module libexec/apache24/mod_cgi.so
LoadModule cgid_module libexec/apache24/mod_cgid.so
LoadModule vhost_alias_module libexec/apache24/mod_vhost_alias.so
LoadModule negotiation_module libexec/apache24/mod_negotiation.so
LoadModule dir_module libexec/apache24/mod_dir.so
LoadModule imagemap_module libexec/apache24/mod_imagemap.so
LoadModule actions_module libexec/apache24/mod_actions.so
LoadModule speling_module libexec/apache24/mod_speling.so
LoadModule userdir_module libexec/apache24/mod_userdir.so
LoadModule alias_module libexec/apache24/mod_alias.so
LoadModule rewrite_module libexec/apache24/mod_rewrite.so
```

**Comment by wpoely86** [comment]
Doesn't work for me. I need: 
```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```

**Comment by RealRancor** [comment]
@wpoely86 Thanks for testing. Could you just replace the line of the module your're using in the updated .htaccess with the the line you need?

**Comment by wpoely86** [comment]
@RealRancor that would of course work. There's nothing wrong with your code but you should use `HTTP_AUTHORIZATION` instead of `XAUTHORIZATION`?

**Comment by RealRancor** [comment]
> There's nothing wrong with your code but you should use HTTP_AUTHORIZATION instead of XAUTHORIZATION?

Arghhhss, i completely missed the difference here. Just changed it, anyone willing to test?

**Comment by idefix6** [comment]
sry, does not work.
It seems that this definition must be on virtual host level and not on directory level?
Does maybe apache ignore the setting in .htaccess?

But I have AllowOverride All, so it should work?

**Comment by RealRancor** [comment]
A short pointer / note for me:

http://www.christianroessler.net/tech/2015/owncloud-on-debian-jessie-with-apache-2.4-and-php-fpm.html

**Comment by RealRancor** [comment]
@idefix6 @wpoely86 Could you test this once more? The mod_proxy_fcgi part is now based on http://www.christianroessler.net/tech/2015/owncloud-on-debian-jessie-with-apache-2.4-and-php-fpm.html which hopefully works now.

I've also removed the mod_fastcgi part as it seems that a configuration in the vhost is needed according to: http://footle.org/2006/05/24/http-authorization-with-apachefastcgi/

**Comment by wpoely86** [comment]
@RealRancor Alas, doesn't work for me.

**Comment by RealRancor** [comment]
@wpoely86 Thanks for testing. So lets close this baby then. I think it won't work within the .htaccess.

Have now added https://github.com/owncloud/documentation/issues/1691 as well as https://forum.owncloud.org/viewtopic.php?f=17&t=30646 which is guiding the people having such environments to the right way.

**Comment by justinkb** [comment]
I'm going to try this patch when I get back home, it seems like that .htaccess tweak should have worked perfectly fine, actually.

**Comment by RealRancor** [comment]
@justinkb Great info, will have a look later this week. Thanks!

**Comment by RealRancor** [comment]
@justinkb 

The only difference i see is ``SetEnvIf`` from your patch vs. ``SetEnvIfNoCase`` on mine. The docs of Apache is telling:

> The SetEnvIfNoCase is semantically identical to the SetEnvIf directive, and differs only in that the regular expression matching is performed in a case-insensitive manner.

but i'm not quite sure if this makes the difference.

**Comment by justinkb** [comment]
The non-case sensitive version works too, as expected (case sensitivity is a strictly stronger requirement, so if it worked then, it should also work now). Of course, I'm not really sure if this commit won't have any wider consequences, but I see you guys have test suites to keep track of that. I think going with the non-case sensitive version might be a safer option. Then again, I'm not an expert on the HTTP standard and if it requires parties send commands and replies in uppercase necessarily.

**Comment by RealRancor** [comment]
@justinkb Thanks for testing. I have no idea about Apache, especially together with mod_fastcgi so i can't tell you whats the correct way here. Just had collected that from the links in the initial comment.

**Comment by PVince81** [comment]
@icewind1991 @LukasReschke @DeepDiver1975  can you comment on this change ?

**Comment by DeepDiver1975** [comment]
> @icewind1991 @LukasReschke @DeepDiver1975 can you comment on this change ?

I'll leave this to the apache/htaccess experts :speak_no_evil: @LukasReschke @icewind1991

**Comment by DeepDiver1975** [comment]
@butonic do you have knowledge about proxy fcgi? THX

**Comment by LukasReschke** [comment]
I can't judge on whether this works for mod_proxy_fcgi _BUT_ the change should at least not break anything for users that don't use it. So I'd give a :+1: for 9.0 considering that it was tested in the forum.

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
