### PR TITLE
Update icewind/streams and other libs

### PR DESCRIPTION
**Pull request by PVince81**
I wanted to upgrade icewind/streams only but composer decided to update more libs (minor versions), so why not.

The main goal is upgrade icewind/streams to get this PR https://github.com/icewind1991/Streams/pull/5 which is a partial fix for https://github.com/owncloud/core/issues/22370

@DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/3rdparty/pull/284

**Comment by PVince81** [comment]
Discussed with @DeepDiver1975 and he said he was ok with updating more libs.

Now let's go and fix that t... OH NO, Jenkins is dead? https://jenkins.owncloud.org/job/owncloud-core/job/core/job/PR-26762/1/

**Comment by PVince81** [comment]
Ok, what @DeepDiver1975 meant was actually https://github.com/owncloud/3rdparty/pull/284#issuecomment-264931213 for 9.1.

Still, I think it should be fine to upgrade all libs on master at this stage.

**Comment by PVince81** [comment]
@DeepDiver1975 add your guzzle update here ?

**Comment by PVince81** [comment]
Rebased to reboot CI

**Comment by PVince81** [comment]
Tested, passed. Merge ? @DeepDiver1975

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/26961
stable9: TODO

**Pull request merged**
