### PR TITLE
get user email address from user account and not preferences table

### PR DESCRIPTION
**Pull request by individual-it**
## Description
since commit 9489104cb3880f22d52bcf7b439a67dd3db60ccf / PR #27276
The email address is not stored in the preferences table any more but in the user account
https://github.com/owncloud/core/commit/9489104cb3880f22d52bcf7b439a67dd3db60ccf#diff-3030ca4989f892c50dea24eaa3f1ae38R151

So need to get it from there also

## Related Issue

#27554

## How Has This Been Tested?

manual test & updated unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
Nice catch 👍 

@DeepDiver1975 can you shake Jenkins repeatedly to make it restart the build ?
```
java.lang.Exception: Resume after a restart not supported for non-blocking synchronous steps
```

**Comment by individual-it** [comment]
Do this tests need to be fixed too?
https://github.com/owncloud/core/blob/master/tests/lib/Files/Storage/HomeStorageQuotaTest.php#L36
https://github.com/owncloud/core/blob/master/tests/lib/HelperStorageTest.php#L139

**Comment by PVince81** [comment]
I guess they do. But they didn't even fail ?

@DeepDiver1975 please confirm

**Pull request merged**
