### PR TITLE
Shorter cache key for URL entries

### LINKED ISSUE #23076: memcached error - no activities are being shown
### Steps to reproduce
1. Just go to the activities app

### Expected behaviour
Some activities should be shown.

### Actual behaviour
No activities are being shown. Instead, I get this error message in the log:
`Error 33 interacting with memcached : A BAD KEY WAS PROVIDED\\\/CHARACTERS OUT OF RANGE\`

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** PostgreSQL 9.4

**PHP version:** 5.6

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Update from 8.2.3 

**Where did you install ownCloud from:** tar.bz2 from owncloud.org

**Signing status (ownCloud 9.0 and above):**
```
Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 7bae810b6f5ca98d062ac9985cac7fb2dc8e22d981ec41e8327e53a5ee7f33017b128bbb4ceefbe665dbd35f7a1ee3a0926c4278aeeeb6d7b4325197be1ed9a9
                        )

                )

        )

)
```

**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.0
  - calendar: 1.0
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: true
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "51adb70420b3a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/owncloud-data",
        "dbtype": "pgsql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "forcessl": true,
        "loglevel": 2,
        "log_rotate_size": 2097152,
        "theme": "",
        "maxZipInputSize": 1610612736,
        "allowZipDownload": true,
        "trusted_domains": [
            "owncloud.brodbeck-online.de",
            "brodbeck-online.de"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 44.0.2

**Operating system:** Arch Linux

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. Set up `memcached` WITH d :exclamation: 
2. Create a file-path that is longer then 250 characters
3. Trigger an activity for that file
4. Try to open the activity app

Fix #23076 

@beedaddy @blizzz @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by nickvergessen** [comment]
@karlitschek should backport to 9.0.1

**Comment by karlitschek** [comment]
great fix. please backport

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by nickvergessen** [comment]
Backport in https://github.com/owncloud/core/pull/23221

**Comment by PVince81** [comment]
Makes sense :+1:

**Pull request merged**
