### PR TITLE
allow apps to load additional scripts on the user settings page ...

### PR DESCRIPTION
**Pull request by butonic**
... via the event dispatcher. I want that for the impersonate app.

cc @MorrisJobke

### CODE REVIEW

**Comment by nickvergessen** [comment]
This is only needed when the app itself has no template, correct?

**Comment by nickvergessen** [comment]
@DeepDiver1975 tech debt, way to go? yes?

**Comment by butonic** [comment]
I need it to only load special js on the settings app and not on every request.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
