### PR TITLE
Rename tests/lib to tests/unit

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Rename tests/lib to tests/unit

## Related Issue
#28233

## Motivation and Context
The stuff in tests/lib is really unit tests (and some integration tests, depending on a strict definition of unit vs integration tests). Renaming this folder will make it clearer, and allow a new lib folder to be created in future for shared code between different unit/integration/acceptance (API and UI and...) tests.

## How Has This Been Tested?
A run of Jenkins has passed.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by butonic** [comment]
Hm, this has bigger consequences than I was aware of. Currently, apps that come with a bootstrap.php for unit teats manually include this folder, eg. https://github.com/owncloud/activity/blob/master/tests/bootstrap.php#L28

I would still like to clean this up, because it moves things into the right places and lowers the barrier of entry for new developers. Now is probably the best time to change it because the apps doing this are all in the owncloud repo and can be fixed by us. But I wonder if we can't come up with a better way to bootstrap the test environment for php unit tests. Probably download the bootstrap.php? Or include a generic one from core?

@PVince81 @DeepDiver1975 @tomneedham ideas on a cleaner approach?

**Comment by DeepDiver1975** [comment]
> Hm, this has bigger consequences than I was aware of. Currently, apps that come with a bootstrap.php for unit teats manually include this folder, eg. https://github.com/owncloud/activity/blob/master/tests/bootstrap.php#L28

yes - so this is breaking all apps - so this is 👎 for me

**Comment by phil-davis** [comment]
I presume that when app tests run automagically in CI, they are fetching the core master branch code. So for that, when (if) this change is merge to core master, we just make the little edit in each app so it knows where to find this folder.
For cross-testing of apps against older core branches, I guess there is more to it. e.g. someone/something has stable10 core locally, installs/enables some app, then wants to run the PHP unit tests. They would have to use some older version of the app, or the app test code needs to go looking for both folders.
???

**Comment by DeepDiver1975** [comment]
> I presume that when app tests run automagically in CI, they are fetching the core master branch code. So for that, when (if) this change is merge to core master, we just make the little edit in each app so it knows where to find this folder.
> For cross-testing of apps against older core branches, I guess there is more to it. e.g. someone/something has stable10 core locally, installs/enables some app, then wants to run the PHP unit tests. They would have to use some older version of the app, or the app test code needs to go looking for both folders.
> ???

ofcourse this is doable - but honestly: why waste half a day just because of renaming a folder.

i see no benefit

**Comment by phil-davis** [comment]
Apps bootstrap.php could do checks like https://github.com/owncloud/activity/pull/579 to decide if they should look in tests/unit or tests/lib - that would make them work with both old and new-style core.

Or I suppose core lib/base.php could have a "unit tests folder" property added to it. Apps would still need some bonus logic to check if property_exists() then use it (pointing to tests/unit/) otherwise do the old hard-coded behavior looking in tests/lib/
(Or such an addition to base.php could be back-ported to all supported stable* branches, indicating the correct tests/lib or tests/unit for the branch. Then apps can just get the property, which will exist in any supported branch, and which will exist in any upcoming point release)

**Comment by DeepDiver1975** [comment]
sure - anything can be done - but I still dont see any benefit compared to the effort which is to be put in

**Comment by individual-it** [comment]
one advantage of having a `lib` folder that contains only libraries would be that we can place the "reusable" pieces of code there https://github.com/owncloud/QA/issues/467

**Comment by DeepDiver1975** [comment]
tests/lib holds tests for code which lives in the upper lib folder - the relationship is quite clear from my pov

**Comment by individual-it** [comment]
> tests/lib holds tests for code which lives in the upper lib folder - the relationship is quite clear from my pov

💡 
I haven't seen it that way before, but makes sense because there are also a `Core` and a `Settings` folder that also contain unit tests. it is called `tests/libs` because it does tests the code in `libs`

Then we could have a `tests/TestHelpers` folder for all the helpers that would contain all "shareable" code and if we really care about making the structure a little bit clearer call the `integration` folder `IntegrationTests` and the `ui` folder `UITests` as this two folders do not contain tests that correspond to the upper level same name folder

**Comment by phil-davis** [comment]
For completeness, I added the last commit here. It was actually running a lot less tests than expected!
That commit makes it actually find and run the tests in tests/unit
If someone in future needs to do a renaming like this, then the changes in this PR will give them a clue.
Now that we have another way forward, I will close here when the CI has demonstrated the last little fix.

**Pull request closed without merging**
