### PR TITLE
When (re-)sharing an incomming federated share set the corrent owner

### LINKED ISSUE #22500: [oc 9] Reshare not allowed on a fed shared data
### Enviroment
2 servers with the version: ownCloud 9.0 beta 1 (daily) Build:2016-02-18T04:41:04+00:00 4422f9c9ef755ef44385a2ed9e0c42f7d1c459d5

### Steps to reproduce
1. Server1 being logged in as admin, select to share with admin@server2 a folder with "can edit enable"
2. access to admin @ server 2
3. You get a notification about the fed sharing accept it
4. Click on the share icon on the fed sharing folder
5. Share the folder internally, with user2

### Expected behaviour
The folder is shared

### Actual behaviour
There is an error: 

screen shot 2016-02-18 at 12 21 43
On the web browser:

```POST http://docker.oc.solidgear.es:55181/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json 403 (Forbidden)```

And the share selector is like:

screen shot 2016-02-18 at 12 22 49

If you select again "test" user, there is an error : path already shared with user

If you refresh: 

screen shot 2016-02-18 at 12 23 55

### Server configuration
ownCloud 9.0 beta 1 (daily) Build:2016-02-18T04:41:04+00:00 4422f9c9ef755ef44385a2ed9e0c42f7d1c459d5
### Client configuration
**Browser:** chrome

**Operating system:**

#### ownCloud log (data/owncloud.log)
```

Error	PHP	OC\User\NoUserException: Backends provided no user object for admin@docker.oc.xxx/ at /opt/owncloud/lib/private/files/filesystem.php#387	2016-02-18T11:23:53+00:00
Error	files	Backends provided no user object for admin@docker.oc.xxxx/	2016-02-18T11:23:53+00:00
```

#### Browser log
```
POST http://docker.oc.xxx/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json 403 (Forbidden)
```

### PR DESCRIPTION
**Pull request by rullzer**
Incomming federated shares are a special kind. We mount them as normal
webdav shares but we do supply owner info with the federated cloud id of
the share owner.

Since we do not yet have the new resharing behaviour on federated shares
we need to set the correct owner. Which will allow sharing and proper
mounting for other users.

fixes #22500 

@rperezb please verify

CC: @schiesbn @nickvergessen @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by rullzer** [comment]
To test

1. userA@server1 shares with userB@server2
2. userB@server2 shares (locally) with userC.

Before: :boom: 

Now: :beers:

**Comment by rullzer** [comment]
@SergioBertolinSG can I ask you to create federated intergration tests for this?

**Comment by SergioBertolinSG** [comment]
@rullzer Yes, I'll open an issue in QA repo.

**Comment by PVince81** [comment]
@schiesbn can you double check this ? Reminds me of your other likely unrelated PR, but who knows...

**Comment by rperezb** [comment]
now :beers:

**Comment by nasli** [comment]
:+1: #22500 and #22484 fixed!
But on this PR I see a couple of things,
*the notifications to accept a federated sharing it looks like the old way with the alert
*Add new text file button has disapeared

**Comment by rullzer** [comment]
@nasli are the notification and texteditor apps enabled?

**Comment by nasli** [comment]
Notification app it is enabled, but I do not see the bell on the top
For add new text files it is necessary that app? I mean this button:
screen shot 2016-02-19 at 10 38 49

**Comment by nasli** [comment]
@rullzer , the notification enabled was only  Update notification app. 
For both things need to add those apps, Ok

**Comment by schiesbn** [comment]
I tried following:

1. share a file from admin@server1 to admin@server2
2. admin@server2 accept the share and re-share it to the local user user1
3. user1 sees the file and can read it
4. BUT user1 is not able to edit the file

NOTE: I first rebased this branch on the latest master to get this fix https://github.com/owncloud/core/pull/22444

error messages:

Apache error.log 

````
[Fri Feb 19 12:44:26.792344 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP Fatal error:  Call to a member function getStorage() on boolean in /home/src/owncloud/server/master/apps/files_versions/lib/storage.php on line 195
[Fri Feb 19 12:44:26.792368 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP Stack trace:
[Fri Feb 19 12:44:26.792405 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP   1. {main}() /home/src/owncloud/server/master/index.php:0
[Fri Feb 19 12:44:26.792442 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP   2. OC::handleRequest() /home/src/owncloud/server/master/index.php:39
[Fri Feb 19 12:44:26.792521 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP   3. OC\\Route\\Router->match() /home/src/owncloud/server/master/lib/base.php:856
[Fri Feb 19 12:44:26.792563 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP   4. call_user_func:{/home/src/owncloud/server/master/lib/private/route/router.php:273}() /home/src/owncloud/server/master/lib/private/route/router.php:273
[Fri Feb 19 12:44:26.792619 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP   5. OC\\AppFramework\\routing\\RouteActionHandler->__invoke() /home/src/owncloud/server/master/lib/private/route/router.php:273
[Fri Feb 19 12:44:26.792663 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP   6. OC\\AppFramework\\App::main() /home/src/owncloud/server/master/lib/private/appframework/routing/routeactionhandler.php:45
[Fri Feb 19 12:44:26.792718 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP   7. OC\\AppFramework\\Http\\Dispatcher->dispatch() /home/src/owncloud/server/master/lib/private/appframework/app.php:110
[Fri Feb 19 12:44:26.792771 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP   8. OC\\AppFramework\\Http\\Dispatcher->executeController() /home/src/owncloud/server/master/lib/private/appframework/http/dispatcher.php:89
[Fri Feb 19 12:44:26.792817 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP   9. call_user_func_array:{/home/src/owncloud/server/master/lib/private/appframework/http/dispatcher.php:159}() /home/src/owncloud/server/master/lib/private/appframework/http/dispatcher.php:159
[Fri Feb 19 12:44:26.792862 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP  10. OCA\\Files_Texteditor\\Controller\\FileHandlingController->save() /home/src/owncloud/server/master/lib/private/appframework/http/dispatcher.php:159
[Fri Feb 19 12:44:26.792907 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP  11. OC\\Files\\View->file_put_contents() /home/src/owncloud/server/master/apps/files_texteditor/controller/filehandlingcontroller.php:155
[Fri Feb 19 12:44:26.792956 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP  12. OC\\Files\\View->basicOperation() /home/src/owncloud/server/master/lib/private/files/view.php:622
[Fri Feb 19 12:44:26.793001 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP  13. OC\\Files\\View->runHooks() /home/src/owncloud/server/master/lib/private/files/view.php:1048
[Fri Feb 19 12:44:26.793047 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP  14. OC_Hook::emit() /home/src/owncloud/server/master/lib/private/files/view.php:1172
[Fri Feb 19 12:44:26.793082 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP  15. call_user_func:{/home/src/owncloud/server/master/lib/private/hook.php:104}() /home/src/owncloud/server/master/lib/private/hook.php:104
[Fri Feb 19 12:44:26.793128 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP  16. OCA\\Files_Versions\\Hooks::write_hook() /home/src/owncloud/server/master/lib/private/hook.php:104
[Fri Feb 19 12:44:26.793172 2016] [:error] [pid 5399] [client 127.0.0.1:39133] PHP  17. OCA\\Files_Versions\\Storage::store() /home/src/owncloud/server/master/apps/files_versions/lib/hooks.php:60
````

owncloud.log (server2):

````
^[[C{"reqId":"vzZc9Wa9tibABj5GUmzM","remoteAddr":"127.0.0.1","app":"PHP","message":"fopen(\/home\/src\/owncloud\/server\/master\/data\/schiesbn\/files_versions\/welcome - fed.txt\/.v1455881715): failed to open stream: No such file or directory at \/home\/src\/owncloud\/server\/master\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-02-19T11:44:26+00:00"}
{"reqId":"vzZc9Wa9tibABj5GUmzM","remoteAddr":"127.0.0.1","app":"PHP","message":"fclose() expects parameter 1 to be resource, boolean given at \/home\/src\/owncloud\/server\/master\/lib\/private\/files\/storage\/common.php#593","level":3,"time":"2016-02-19T11:44:26+00:00"}
{"reqId":"vzZc9Wa9tibABj5GUmzM","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getStorage() on boolean at \/home\/src\/owncloud\/server\/master\/apps\/files_versions\/lib\/storage.php#195","level":3,"time":"2016-02-19T11:44:26+00:00"}
```

**Comment by schiesbn** [comment]
added a commit to fix the issue I reported... Everything works now :+1:

**Comment by rullzer** [comment]
:+1: for the latest commit.

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
