### PR TITLE
Submit button on password-protected link disabled when password field is empty

### LINKED ISSUE #20177: Submit button on password-protected link page should be disabled until something is put in
Because I assume there can not be empty passwords anyway? @DeepDiver1975 @PVince81 @MorrisJobke

### PR DESCRIPTION
**Pull request by rullzer**
Replaces https://github.com/owncloud/core/pull/21302 by @gmurayama
Fixes #20177

Rebased, commits squashed. And comments addressed.

Review time! @owncloud/javascript @owncloud/sharing

### CODE REVIEW

**Comment by rullzer** [comment]
@gmurayama did you already sign the licence agreement? Or is your patch MIT licenced?

**Comment by MorrisJobke** [comment]
> @gmurayama did you already sign the licence agreement? Or is your patch MIT licenced?

@karlitschek Did you received something?

**Comment by karlitschek** [comment]
negative

**Comment by rullzer** [comment]
So what to do here? close?

**Comment by DeepDiver1975** [comment]
> So what to do here? close?

no CLA or MIT -> close

**Pull request closed without merging**
