### PR TITLE
[Jenkins only] Logfile download

### PR DESCRIPTION
**Pull request by MorrisJobke**
jenkins PR for #12988

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@owncloud-bot restest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot restest this please

**Comment by MorrisJobke** [comment]
I force pushed the exact same commit from the original PR to this one. @georgehrke Nonetheless have a look at the failing tests here

**Pull request merged**
