### PR TITLE
[stable10] Backport of Increase size of login_name from 64 to 255

### PR DESCRIPTION
**Pull request by sharidas**
Increase size of column login_name from 64 to 255.
It would help to accomonate long strings.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Increase the size of `login_name` column of table `oc_authtoken`. This would help to use long user name for login. This issue was seen when user was trying to authenticate with long username using OAuth2.

## Related Issue

- Fixes <issue_link>

## Motivation and Context

Increasing the size of `login_name` column of the table `oc_authtoken`. This would help to use long user name for login.

## How Has This Been Tested?

- test environment:
- The testing done in https://github.com/owncloud/core/pull/34269 should apply here too because, it was tested by upgrading from 10.0.9 to 10.0.10.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
will require release note and also would trigger the next release to be 10.2 instead of 10.1.1 due to DB change that requires downtime

@pmaier1

**Comment by phil-davis** [comment]
drone https://drone.owncloud.com/owncloud/core/14918/247 got:
```
Initialized empty Git repository in /drone/src/.git/
+ git remote add origin https://github.com/owncloud/core.git
+ git fetch --no-tags --depth=50 origin +refs/pull/34280/merge:
fatal: The remote end hung up unexpectedly
time="2019-02-07T15:31:02Z" level=fatal msg="exit status 128" 
```
stupid thing! I will ask for a rebase again.

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
