### PR TITLE
Acceptance test style 20180920

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Fix a couple of things reported by ``phpcs``

## Motivation and Context
Keep acceptance test PHPdoc up-to-date.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by patrickjahns** [comment]
Please put a task into drone that will automatically check the acceptance tests - or migrate the styling over to php-fixer and check it via php-fixer

**Comment by phil-davis** [comment]
Backport ``stable10`` #32778

**Review by individual-it — APPROVED** [review]

**Comment by patrickjahns** [comment]
@phil-davis 
Please follow up on the discussion of more then one tool as coding-standard for ownCloud here: https://github.com/owncloud/coding-standard/issues/11

I am asking to avoid the anti-pattern of pull request that just fix some code styles that can be easily prevented by automation.
Please create an issue to schedule the automated check of phpcs in drone.

**Comment by phil-davis** [comment]
Issue #32782 for automating ``phpcs`` checks.

**Pull request merged**
