### PR TITLE
Fix bug issue 21110

### LINKED ISSUE #21110: SMB icon not replaced properly after availability check
### Steps

1. Mount SMB storage globally (admin page)
1. Go to the files app "All files"
1. Wait for availability check to finish

### Expected result
After availability check, icon shows properly

### Actual result
Icon disappears after availability check. (I cleared the cache, same result)

@jmaciasportela please have a look.

### PR DESCRIPTION
**Pull request by jmaciasportela**
Fixes #21110

### CODE REVIEW

**Comment by jmaciasportela** [comment]
cc @PVince81

**Comment by Xenopathic** [comment]
:+1:

Why is there a list of all the other backends, but with just the default icon? It seems to me that they can all be omitted and the behaviour would be exactly the same.

**Comment by jmaciasportela** [comment]
@Xenopathic yes it could be omitfed. I did it to be able to customize other external storage icons. No other reason.

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
