### PR TITLE
[8.2] Allow to overwrite a single language string via the theme folder

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #22677 
Approval https://github.com/owncloud/core/pull/22677#issuecomment-189385792

@MorrisJobke @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by nickvergessen** [comment]
@PVince81 pick your change inhere as well?

**Comment by PVince81** [comment]
@nickvergessen yes please

**Comment by nickvergessen** [comment]
done, :+1: for not my commit

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
Let's merge after CI passes

**Pull request merged**
