### PR TITLE
Clean-up of messages (orthography, format)

### PR DESCRIPTION
**Pull request by cmeh**
**Changes:**
- "the users encryption key" in line 81 of controller.php is corrected to "the user's encryption key" (correct genitive).
- "Back-end" in line 81 of controller.php is changed to "Backend" without a hyphen. It's written like that in all other instances across ownCloud (e.g. [here](https://github.com/owncloud/contacts/blob/master/lib/contact.php#L282), [here](https://github.com/owncloud/contacts/blob/master/lib/addressbook.php#L426), [here](https://github.com/owncloud/core/blob/master/core/templates/installation.php#L160) …).
- A missing space between value and unit is added to line 519 of admin.php ("100 MB" instead of "100MB").

### CODE REVIEW

**Comment by cmeh** [comment]
This contribution is MIT licensed.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
THX

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
