### PR TITLE
Don't auto-trust servers by default when creating remote shares

### PR DESCRIPTION
**Pull request by PVince81**
## Description

This makes sure that only admins who really want this feature must
opt-in instead of opt-out.
## Motivation and Context

Adding a server as trusted will expose local users for the remote server's sharing autocomplete.
I think admins seldom would want that, and even if they do it should be opt-in, not opt-out to avoid leakage by mistake.
## How Has This Been Tested?
- [x] TEST: setup new OC: setting disabled on admin page
- [x] TEST: update from old OC where setting was untouched: setting disabled on admin page
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@DeepDiver1975 @butonic @Peter-Prochaska

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
as discussed :+1:

**Comment by PVince81** [comment]
Note that if the setting was never touched, then it has no value in the DB.
This could result in an env updating from having it enabled by default to suddenly be disabled.

Is that acceptable ?

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2016-10-20 12-15-09

**Comment by PVince81** [comment]
fixed test

**Comment by PVince81** [comment]
@DeepDiver1975 tests pass now

**Comment by PVince81** [comment]
I suggest we don't backport this as it changes default behavior.
The behavior change will then only be in 10 and we'll want to have this documented.

**Pull request merged**
