### PR TITLE
sidebar fixes

### LINKED ISSUE #10815: Difficulties to change the view in the files app in small screens
### Steps to reproduce
1. Activate one or more views in the files app (share or external storage)
2. Reduce the window height enough so the "deleted files" entry is overlapped with other entries

### Expected behaviour
All entries are easily clickable

### Actual behaviour
The "Deleted files" entry overlaps one or two entries, making those entries difficult to click

### Server configuration
**ownCloud version:**  {"installed":"true","version":"7.0.2.1","versionstring":"7.0.2","edition":""}

### Client configuration
**Browser:**  Firefox 31.0

screenshot from 2014-09-02 10 07 50

Note: This could also happen if there are too many entries.

### LINKED ISSUE #13264: Webinterface: groups hidden behind app settings
When there are a lot of groups, the last group is invisible because the App-settings panel hides it at the bottom. This is in the User-management panel in OwnCloud 7.0.4.

What I did to work around this is add another bogus group called 'ZZZZZ' that will always end up at the end of the list to push the last item up a bit, but the proper solution would be that the scroll bar only extends up to the app settings panel instead of underneath it.

### PR DESCRIPTION
**Pull request by jancborchardt**
- add bottom padding to sidebar, fix last element being hidden below settings, fix #13264 cc @MadEgg
- fix position of 'Deleted files' sidebar entry, fix #10815 cc @jvillafanez 

Please also review @owncloud/designers

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by MorrisJobke** [comment]
Doesn't work. The hover of last entry is highlighted over the full width:

sidebar

**Comment by jancborchardt** [comment]
Fixed and amended (force pushed), please retest @MorrisJobke @owncloud/designers

**Comment by jvillafanez** [comment]
Looks like it works in Chrome but not in Firefox. Firefox still hides the element behind the "Deleted files" and there isn't enough scroll to pull it out.

There is also an ugly horizontal scrollbar appearing in my case (both Chrome and Firefox)

screenshot from 2015-03-18 12 48 08

**Comment by jancborchardt** [comment]
@jvillafanez fixed for real this time. ;)

**Comment by jancborchardt** [comment]
(CSS changes only, Jenkins can be ignored.)

**Comment by MorrisJobke** [comment]
I guess you need to add a bottom-margin for the last entry in upper list:

Overlapping step 1:
step1
Overlapping step 2 without enough vertical space (list should already be in scroll mode and background of the trashbin entry should be non-transparent)
step2
Overlapping step 3 - vertical scrollbar appears once the last element hits the settings entry (but it should be there once it hits the trashbin entry)
step3

**Comment by jancborchardt** [comment]
@MorrisJobke I fixed that already – the »Deleted files« entry has a background color. Refresh cache.

**Comment by MorrisJobke** [comment]
It looks also broken:
broken-entry

**Comment by jancborchardt** [comment]
@MorrisJobke can’t reproduce that error. This is how it looks for me in both FF and Cr:
capture du 2015-03-18 16 20 48

**Comment by MorrisJobke** [comment]
I will investigate

**Comment by MorrisJobke** [comment]
Works now :( Sorry.

I would like to add `margin-bottom: 44px;` to `.nav-sharinglinks` (last element in the upper part of the list) because then you will be able to scroll to all elements. Otherwise the last one is hidden behind the trashbin element.

**Comment by jancborchardt** [comment]
@MorrisJobke that already works. Because the »Deleted files« entry is part of the list, and the list already has a bottom margin of 44px.

**Comment by MorrisJobke** [comment]
I refreshed very often now, but it always overlaps without scrollbar. :(

**Comment by jancborchardt** [comment]
Straange! Different browser maybe? Or Incognito window?

**Comment by jancborchardt** [comment]
Ugh – so apparently with Chrome it works, but with Firefox even more padding is needed. @MorrisJobke I think for now I will just add the big padding by default.

**Comment by jancborchardt** [comment]
@owncloud/designers please test again cc @MorrisJobke @jvillafanez

**Comment by jancborchardt** [comment]
@MorrisJobke @jvillafanez please review again.

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by jancborchardt** [comment]
@jvillafanez we still need your thumbs up ;)

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
nickvergessen is working on the broken tests

**Comment by jvillafanez** [comment]
Just a couple of minor issues that probably aren't worthy to fix right now:
* The scrollbar in the menu is partially hidden with the "Deleted files" entry (the same is happening in the file list).
* When the sidebar is scrolled to the bottom, there is extra blank space in Chrome but not in Firefox.

Anyway the sidebar is usable, so I wouldn't change anything for now.

:+1:

**Comment by jancborchardt** [comment]
@jvillafanez yeah, that are the small tradeoffs which seem to be necessary. Previously the last entry was hidden in FF but not in Cr, so we needed to just add extra 44px there.

**Comment by jancborchardt** [comment]
@karlitschek @MorrisJobke should we backport this?

**Comment by karlitschek** [comment]
not an critial fix. let´s not backport

**Pull request merged**
