### PR TITLE
Use ArrayCache if ownCloud is not installed

### PR DESCRIPTION
**Pull request by LukasReschke**
If ownCloud has not been installed yet the prefix might otherwise change at this point quite some time and thus the cache runs havoc.

This made installing ownCloud impossible on systems where APCu or so was available. However, I was not able to reproduce the same problem for application upgrades so this patch seems to work fine for this situation as well.

Fixes itself.

cc @MorrisJobke The problem we talked about.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@DeepDiver1975 @icewind1991 Mind to review as well?

**Comment by karlitschek** [comment]
good idea :+1:

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by nickvergessen** [comment]
Since we said "don't use unless configured" The solution here would be NullCache

**Comment by nickvergessen** [comment]
But either is fine by me

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
14:51:06 Finished: SUCCESS

Test succeed -> merge

**Pull request merged**
