### PR TITLE
[stable8] backport of #17464: fix uncaught exception on not permitted file types when setting avata…

### LINKED ISSUE #17232: LDAP - avatar in format other than jpg/png throws exception
Hi,
when using LDAP with OwnCloud lib/private/avatar.php ( https://github.com/owncloud/core/blob/master/lib/private/avatar.php#L104 ) could make instance unusable for some users. If they have avatar in other format than jpg or png - they have 500 internal server error, in logs you just see exception from avatar.php.

Exception:
```javascript
{"Message":"Unknown filetype","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(346): OC_Avatar->set(Object(OCP\\Image))\n#1 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(319): OCA\\user_ldap\\lib\\user\\User->setOwnCloudAvatar()\n#2 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(134): OCA\\user_ldap\\lib\\user\\User->updateAvatar()\n#3 \/var\/www\/html\/owncloud\/apps\/user_ldap\/user_ldap.php(213): OCA\\user_ldap\\lib\\user\\User->update()\n#4 \/var\/www\/html\/owncloud\/lib\/private\/user\/manager.php(113): OCA\\user_ldap\\USER_LDAP->userExists('user')\n#5 \/var\/www\/html\/owncloud\/lib\/private\/user\/manager.php(142): OC\\User\\Manager->get('user')\n#6 \/var\/www\/html\/owncloud\/lib\/private\/user.php(574): OC\\User\\Manager->userExists('user')\n#7 \/var\/www\/html\/owncloud\/lib\/private\/user.php(334): OC_User::userExists('user')\n#8 \/var\/www\/html\/owncloud\/lib\/base.php(774): OC_User::isLoggedIn()\n#9 \/var\/www\/html\/owncloud\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/avatar.php","Line":66} 
```

Steps to reproduce:
1. Use LDAP
2. Create user in LDAP with f.e. gif avatar.
3. Try to login to OwnCloud

or
1. Use LDAP
2. Create user in LDAP
3. Login to OwnCloud with that user
4. Set in LDAP gif avatar
5. Every link user opens - will give 500 Internal server error.

### PR DESCRIPTION
**Pull request by blizzz**
…r, fixes #17232

Includes the plain fix, not the integration tests (not backportable).

@MorrisJobke @SergioBertolinSG @hostingnuggets here is the backport to OC 8 if you like to test and review.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
:+1: Tested on stable8.1+this PR working fine. Only draws jpg and png.

**Comment by blizzz** [comment]
> :+1: Tested on stable8.1+this PR working fine. Only draws jpg and png.

@SergioBertolinSG did you intend to comment here (8.0) or rather  at  https://github.com/owncloud/core/pull/17951?

**Comment by SergioBertolinSG** [comment]
In stable8.1, sorry.

**Comment by SergioBertolinSG** [comment]
I've tested this on stable8, but images doesn't appear, any of them jpg or png are not shown. Gif is ignored as well so not 500 error.

**Comment by PVince81** [comment]
Any update?

**Comment by DeepDiver1975** [comment]
not fixed -> 8.0.8

**Comment by hostingnuggets** [comment]
what about 8.1.1?

**Comment by blizzz** [comment]
works for me. @SergioBertolinSG what were your  test  steps?

**Comment by blizzz** [comment]
@hostingnuggets 8.1 fix is merged and will be released with 8.1.2

**Comment by hostingnuggets** [comment]
@blizzz cheers!

**Comment by SergioBertolinSG** [comment]
:+1:  (Erasing lastFeatureRefresh for not waiting 24h)

**Comment by blizzz** [comment]
Thank you @SergioBertolinSG 

We need a second reviewer here (against 8.0)! Maybe @Xenopathic  @Nick-Lock @benwilliams @johansmitsnl?

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
