### PR TITLE
Use the normal OC.menu JS for handling the Settings menu

### LINKED ISSUE #19916: User menu does not close on file actions menu opening
This works fine with the apps menu and the actions menu, and the apps menu and the user menu. It’s just that when you:
1. Open the user menu in the top right
2. Open the file actions menu on a file

You would expect the user menu to close. But it doesn. cc @PVince81

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #19916

@jancborchardt @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
Excellent :+1:

**Comment by MorrisJobke** [comment]
This only works if the "action menu" is open and you click on the user menu. The other way around doesn't work.

* [ ] open user menu (top right) and then click on the three dots of the action menu of a file

**Comment by PVince81** [comment]
@MorrisJobke works for me

**Comment by PVince81** [comment]
Did you mean clicking on the "Share" action maybe ? That doesn't close the menu, probably due to blocked click event... this is likely to happen in many many places.

**Comment by PVince81** [comment]
Argh, actually clicking outside anywhere doesn't close the menu.

**Comment by PVince81** [comment]
It looks like the menu API is broken, the other menus also don't close.
Let me have a look at this separately.

**Comment by nickvergessen** [comment]
Fixed, sorry deleted one block too much

**Comment by PVince81** [comment]
All work now :+1:

**Comment by MorrisJobke** [comment]
Oh sorry...it worked before ... I was wrong ... I simply used the wrong instance ... I can push your old commit if you want.

**Comment by MorrisJobke** [comment]
It works with the latest commit :+1:

Nevermind all my problems.

**Comment by DeepDiver1975** [comment]
I'd love to see at least the jsunit test pass

**Comment by jancborchardt** [comment]
Btw, this should also be backported, no? cc @karlitschek

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by jancborchardt** [comment]
@nickvergessen please prepare the backport.

**Comment by nickvergessen** [comment]
The bug was reported for 9.0 and does not happen in anything previously?

**Comment by jancborchardt** [comment]
Ah k, sorry. I assumed this was happening on 8.2 as well.

**Pull request merged**
