### PR TITLE
Set the debugoutput channel to error_log instead of echoing it

### LINKED ISSUE #13482: Cannot configure email
I have Owncloud 7.0.4.

When I try to send a test mail to my email (after configuration), I get this error:
Cannot modify header information - headers already sent by (output started at /var/www/3rdparty/phpmailer/phpmailer/class.smtp.php:181) at /var/www/lib/private/appframework/app.php

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #13482 

@DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
backport has been approved: https://github.com/owncloud/core/pull/13548#issuecomment-70845199

**Comment by DeepDiver1975** [comment]
summoning backporter @MorrisJobke :speak_no_evil:

**Comment by nickvergessen** [comment]
@DeepDiver1975 #13555 is already available for stable7

**Pull request merged**
