### PR TITLE
[WIP] Bump PHP dependencies 2022-08-29

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) First commit:
```
Updating dependencies
Lock file operations: 0 installs, 6 updates, 0 removals
  - Upgrading guzzlehttp/guzzle (7.4.5 => 7.5.0)
  - Upgrading guzzlehttp/promises (1.5.1 => 1.5.2)
  - Upgrading guzzlehttp/psr7 (2.4.0 => 2.4.1)
  - Upgrading roave/security-advisories (dev-master 4f051d7 => dev-master bd4a45f)
  - Upgrading symfony/console (v4.4.44 => v4.4.45)
  - Upgrading symfony/translation (v4.4.44 => v4.4.45)
Writing lock file
```

2) Second commit for new dependency updates as at 2022-08-31:
```
Updating dependencies
Lock file operations: 0 installs, 4 updates, 0 removals
  - Upgrading phpunit/php-code-coverage (9.2.16 => 9.2.17)
  - Upgrading phpunit/phpunit (9.5.23 => 9.5.24)
  - Upgrading roave/security-advisories (dev-master bd4a45f => dev-master 9d7e96a)
  - Upgrading sebastian/type (3.0.0 => 3.1.0)
Writing lock file
```

3) https://github.com/phpseclib/phpseclib/releases/tag/3.0.15
```
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Upgrading phpseclib/phpseclib (3.0.14 => 3.0.15)
  - Upgrading roave/security-advisories (dev-master 9d7e96a => dev-master 6d26039)
Writing lock file
```

4) https://github.com/nikic/PHP-Parser/releases/tag/v4.15.1
```
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading nikic/php-parser (v4.14.0 => v4.15.1)
Writing lock file
```

5) phpseclib 3.0.16
```
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading phpseclib/phpseclib (3.0.15 => 3.0.16)
Writing lock file
```

6) dev dependencies related to phpunit
```
Updating dependencies
Lock file operations: 0 installs, 4 updates, 0 removals
  - Upgrading roave/security-advisories (dev-master 6d26039 => dev-master 5cf4af1)
  - Upgrading sebastian/comparator (4.0.6 => 4.0.8)
  - Upgrading sebastian/exporter (4.0.4 => 4.0.5)
  - Upgrading sebastian/type (3.1.0 => 3.2.0)
Writing lock file
```

7) sabre/uri (2.2.3 => 2.2.4)
```
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Upgrading roave/security-advisories (dev-master 5cf4af1 => dev-master 264a508)
  - Upgrading sabre/uri (2.2.3 => 2.2.4)
Writing lock file
```

A minor version of Guzzle was released:
https://github.com/guzzle/guzzle/releases/tag/7.5.0
But it does not have any bug fixes. It adds support for PHP 8.2. So we don't really need to push that into the core oC 10.11.0 release branch.

The monthly symfony patch release also happened over the weekend. There is nothing urgent for us there either.

So I have marked this PR as Draft. The purpose, for now, is just to confirm that CI passes. We can do the changelog and merge this PR etc after 10.11.0 is released and merged back to master.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
Rebased and updated with the latest dependencies as at 2022-08-31

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuthWebDav-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36739/51

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiComments-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36739/53

**Comment by phil-davis** [comment]
done in #40337

**Pull request closed without merging**
