### PR TITLE
Add search API to capabilities

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Add the search API to the server capabilities

## Related Issue
https://github.com/owncloud/core/issues/25373

## How Has This Been Tested?
Manually tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: great

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@jvillafanez please backport or cherry-pick on the stable10 backport of the search API

**Comment by jvillafanez** [comment]
https://github.com/owncloud/core/pull/31946 already contains these commits.

**Pull request merged**
