### PR TITLE
[files_external] sftp tests

### PR DESCRIPTION
**Pull request by MorrisJobke**
same as #13922 but for SFTP

I had some trouble on my machine with PHPUnit.

@DeepDiver1975 Can you create a job for this on Jenkins? Thanks ;)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@icewind1991 Can you give this a try. It looks like a dead lock in the tests:

```
...
Waiting 5 seconds for sftp initialization ... 
No coverage
PHPUnit 4.4.5 by Sebastian Bergmann.

Configuration read from /home/mjob/Projekte/owncloud/master/tests/phpunit-autotest-external.xml

^Cstop: stop-sftp-atmoz.sh
...
```

I had to cancel the phpunit execution, because nothing happened. I also tried the `-v` but there was no additional output.

**Comment by LukasReschke** [comment]
What is the status here?

**Comment by DeepDiver1975** [comment]
> What is the status here?

merge and watch out for jenkins fail - next: fixit

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> merge and watch out for jenkins fail - next: fixit

- [x] merge
- [ ] watch out for jenkins fail - https://ci.owncloud.org/job/server-master-linux-externals/database=sqlite,external=sftp-atmoz,label=vm-slave-02/
- [ ] fixit

**Comment by atmoz** [comment]
Just happened to notice that my SFTP image is used here, got curious and had a look at the code. 

Not sure how this test environment works, but from what I can tell you are starting a container without mounting any volumes. That will not work well, because the home folders are jailed, and only root has access to that folder (edit/create new files).

I guess that's why jenkins fails all the time.

You can mount a volume, or maybe just create a new folder as root and give the user full access to that folder. Since this is just for testing, it doesn't matter if the content of that folder will be destroyed alongside with the container itself. Like: `docker exec $container bash -c "mkdir /home/$test/upload && chown $test:users /home/$test/upload"`.

**Comment by MorrisJobke** [comment]
@atmoz Thanks for checking this out. I thought I had some working tests, but only some where failing. I will have a look at this.

**Pull request merged**
