### PR TITLE
add index.html suffix to web.baseUrl

### PR DESCRIPTION
**Pull request by micbar**
## Description
Add an `index.html`suffix to the `web.baseUrl` in the app switcher url

## Related Issue

- https://github.com/owncloud/enterprise/issues/4301#issuecomment-744338673
## Motivation and Context
Make it work with thee oc10 web app

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by micbar** [comment]
@xoxys @DeepDiver1975 
This was manually tested also with the docker image. https://phoenix.owncloud.com/index.html
Seems to be compatible

@LukasHirt That needs documentation
- No trailing slash at the end of `web.baseUrl`. I tested it, it does not break immediately, but better not have a duplicate slash

Could we also add the example for the web app switcher and the settings to the docs?
```
{
  "server" : "https://cloud.local",
  "theme": "owncloud",
  "version": "0.1.0",
  "auth": {
    "clientId": "WMJn08mw5FmgaCPQM67Yq2tpmkERoZfcRhiGjcRvQfqfro2U17EnXoCiyzLUh9qw",
    "url": "https://cloud.local/index.php/apps/oauth2/api/v1/token",
    "authUrl": "https://cloud.local/index.php/apps/oauth2/authorize"
  },
  "apps" : [
    "files"
  ],
  "applications" : [
    {
      "icon": "switch_ui",
      "target": "_self",
      "title": {
        "de": "Klassisches ownCloud",
        "en": "Classic Design"
      },
      "url": "https://cloud.local/index.php/apps/files"
    },
    {
      "icon": "application",
      "menu": "user",
      "target": "_self",
      "title": {
        "de": "Einstellungen",
        "en": "Settings"
      },
      "url": "https://cloud.local/index.php/settings/personal"
    }
  ]
}
```

- Add description to the docs about the oauth2 config and redirect url

**Comment by phil-davis** [comment]
> SonarCloud Quality Gate failed.

Note: This is because this PR is to 10.6.0 and there are code-quality improvements in `master`. So SonarCloud sees this PR as going "backwards" compared to `master`

**Comment by mmattel** [comment]
@micbar hope you do not mind if I am asking, but is it correct to use `index.html`? I was astonished that it is not `index.php`...

**Comment by micbar** [comment]
It is a index.html file which loads the vue.js app
No php involved..

**Comment by xoxys** [comment]
@micbar can we please simply normalize the url? Do we really need to care about slash/double slashes in 2020?

**Comment by micbar** [comment]
@xoxys pushing...

**Review by kulmann — APPROVED** [review]

**Comment by micbar** [comment]
@LukasHirt Now the url is insensitive to trailing slashes.

**Comment by LukasHirt** [comment]
> Now the url is insensitive to trailing slashes.

Cool! Will reflect it in the docs :wink:

**Comment by phil-davis** [comment]
@micbar https://drone.owncloud.com/owncloud/core/27956/2/7 ccode style fails, needs a space.

**Comment by micbar** [comment]
thanks. Fixed.

**Comment by micbar** [comment]
merging, sonarCloud is explained by @phil-davis

**Pull request merged**
