### PR TITLE
pass view hooks trough to the node hooks

### LINKED ISSUE #18759: File upload/delete and folder delete through web UI doesn't trigger corresponding hooks
### Steps to reproduce
Upload/delete/create a file or delete a folder through web UI

### Expected behaviour
Corresponding [hooks](https://doc.owncloud.org/server/8.2/developer_manual/app/hooks.html#filesystem-root) like `postWrite`, `postDelete` should be invoked.

### Actual behaviour
The hooks are never invoked.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4.7

**Database:** MySQL

**PHP version:**  5.5.9

**ownCloud version:** ownCloud 8.2 pre alpha (git) (master@f8d8de5)

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### PR DESCRIPTION
**Pull request by icewind1991**
Listen to the hooks from the view and emit the proper ones on the root folder

Fixes #18759

@pellaeon can you verify that this fixes the problem

cc @PVince81 @DeepDiver1975 @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
makes a lot of sense :+1:

**Comment by PVince81** [comment]
@pellaeon can you help ?

**Comment by pellaeon** [comment]
@icewind1991 confirmed and it works!

**Comment by PVince81** [comment]
Counting as :+1: from @pellaeon 

Also :+1: from me

**Pull request merged**
