### PR TITLE
Fix the last insert id test by changing to an autoincremen…

### LINKED ISSUE #21052: Failing test on Oracle
Introduced with https://github.com/owncloud/core/pull/21030

```
13:45:02 There was 1 error:
13:45:02 
13:45:02 1) Test\DB\QueryBuilder\QueryBuilderTest::testGetLastInsertId
13:45:02 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-02289: sequence does not exist
13:45:02 
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:116
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:157
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1087
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/lib/private/db/connection.php:226
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/lib/private/db/adapteroci8.php:36
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/lib/private/db/connection.php:221
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:1057
13:45:02 /ssd/jenkins/workspace/server-master-linux/database/oci/label/SLAVE/tests/lib/db/querybuilder/querybuildertest.php:1135
```

### LINKED ISSUE #21057: Failing test on PGSQL
Introduced with #21030

```
Test\DB\QueryBuilder\QueryBuilderTest::testGetLastInsertId
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT lastval()':

SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  lastval is not yet defined in this session

/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:836
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/lib/private/db/connection.php:182
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:541
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/lib/private/db/adapterpgsql.php:28
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/lib/private/db/connection.php:221
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:1057
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/tests/lib/db/querybuilder/querybuildertest.php:1135
```

### PR DESCRIPTION
**Pull request by nickvergessen**
…t table

Superseeds #21058

Fix #21057 
Fix #21052

@MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
On PHP7:

```
1) Test\DB\QueryBuilder\QueryBuilderTest::testGetLastInsertId
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_properties" ("userid", "propertypath", "propertyname") VALUES('testFirstResult', 'testing50', '50')':

SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_properties.propertyvalue

/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/db/connection.php:203
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:121
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/tests/lib/db/querybuilder/querybuildertest.php:1133

Caused by
Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_properties.propertyvalue

/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:59
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:993
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/db/connection.php:203
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:121
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/tests/lib/db/querybuilder/querybuildertest.php:1133

Caused by
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_properties.propertyvalue

/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:993
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/db/connection.php:203
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:121
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/tests/lib/db/querybuilder/querybuildertest.php:1133
```

**Comment by MorrisJobke** [comment]
Code changes make sense :+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by LukasReschke** [comment]
Still broken on Oracle.

```
04:51:24 Time: 21.28 minutes, Memory: 257.75Mb
04:51:24 
04:51:24 There was 1 error:
04:51:24 
04:51:24 1) Test\DB\QueryBuilder\QueryBuilderTest::testGetLastInsertId
04:51:24 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-02289: sequence does not exist
04:51:24 
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:116
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:157
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1087
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/lib/private/db/connection.php:226
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/lib/private/db/adapteroci8.php:36
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/lib/private/db/connection.php:221
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:1057
04:51:24 /ssd/jenkins/workspace/core-ci-linux@6/database/oci/label/SLAVE/tests/lib/db/querybuilder/querybuildertest.php:1136
04:51:24 
```

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/blob/master/db_structure.xml#L597-L604

WTF? @DeepDiver1975 any idea?

**Comment by nickvergessen** [comment]
Fixing

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
