### PR TITLE
calculate and update the version of the encryption signature correctly

### LINKED ISSUE #22260: Encryption signature version not increased on upload
### Steps

1. Enable encryption
1. Upload a file "test.txt"
1. Update the file "test.txt" in the web UI with the text editor, save
1. Check "encrypted" column in database
1. Update the file "test.txt" with Webdav PUT
1. Check "encrypted" column in database

### Expected result
Value of "encrypted" increases after every save

### Actual result
Value only increases when updated with the text editor, not Webdav

### Versions
9.0 git master 9ebcc4ce312db574173627488887f14db2f4bc34

@LukasReschke @schiesbn

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/owncloud/core/issues/22260

steps to test:
1. Enable encryption
2. Upload a file "test.txt"
3. Update the file "test.txt" in the web UI with the text editor, save
4. Check "encrypted" column in database
5. Update the file "test.txt" with Webdav PUT
6. Check "encrypted" column in database

cc @PVince81 @LukasReschke

### CODE REVIEW

**Comment by schiesbn** [comment]
will write/update unit test... but please test this already if it fixes all the issues. @PVince81 maybe you can run smashbox against it? Thanks!

**Comment by nickvergessen** [comment]
Smashing: :hourglass_flowing_sand:

**Comment by nickvergessen** [comment]
```json


{
  "reqId": "byzACVvfhAscHVi4RgP8",
  "remoteAddr": "10.0.2.2",
  "app": "PHP",
  "message": "Call to a member function update() on null at \/home\/nickv\/ownCloud\/master\/core\/lib\/private\/files\/storage\/wrapper\/encryption.php#263",
  "level": 3,
  "time": "2016-02-10T10:34:24+00:00"
}
```

Exception when trying to delete:
```
Unexpected response: Status code: 500 - 
Operation "rmdir" must be allowed when share permissions are 31  ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
```

**Comment by nickvergessen** [comment]
Unit tests fail as well, so that should help finding the issue

```
PHP Fatal error:  Call to a member function update() on null in /ssd/jenkins/workspace/core-ci-linux@3/database/sqlite/label/SLAVE/lib/private/files/storage/wrapper/encryption.php on line 263
```

**Comment by schiesbn** [comment]
OK, this version should hopefully work for all tests. I'm not completely happy with the solution but I have no better idea at the moment.

**Comment by LukasReschke** [comment]
Did some kinda extensive smoke testing locally. Worked fine :+1:

**Comment by nickvergessen** [comment]
Smashbox: :white_check_mark:

**Comment by PVince81** [comment]
That looks good, even with versions:
```
| files/test.txt                                                              |         4 |
| files_versions/test                                                         |         0 |
| files_versions/test.txt.v1455113368                                         |         1 |
| files_versions/test.txt.v1455113435                                         |         2 |
| files_versions/test.txt.v1455113498                                         |         3 |
| files_versions/test/test2.txt.v1455113375                                   |         1 |
| files_versions/test/test2.txt.v1455113441                                   |         2 |
| files_versions/test/test2.txt.v1455113487                                   |         3 |
```

Tested after upgrading with existing encrypted versions.

**Comment by PVince81** [comment]
I also checked that the version files can still be downloaded.

:+1:

**Pull request merged**
