### PR TITLE
Fix facade autotest

### LINKED ISSUE #16296: autotest.sh broken if PHPUnit is installed using a script as facade
If PHPUnit is installed using a script as facade invoking it will fail, in my case this means:

```
➜  master git:(master) ✗ which phpunit
/usr/local/bin/phpunit
➜  master git:(master) ✗ cat /usr/local/bin/phpunit
#!/usr/bin/env bash

/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/phpunit/4.6.4/libexec/phpunit-4.6.4.phar $*%
```

Invoking `php /usr/local/bin/phpunit` will fail hard now. As it is a shell script and not a PHAR file.

Regression caused by https://github.com/owncloud/core/pull/16045

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes #16296

@DeepDiver1975 Can you check if the HHVM tests still run on Jenkins? - THX.

### CODE REVIEW

**Comment by Xenopathic** [comment]
This *will* break horribly if the path to PHPUnit contains spaces. I'd advise using an array to store the PHPUnit execution path, with proper quoting:

    if ...; then
        PHPUNITEXE=( "$PHP" "$PHPUNIT" )
    else
        PHPUNITEXE=( "$PHPUNIT" )
    fi
    ....
    "${PHPUNITEXE[@]}" --configuration ...

**Comment by DeepDiver1975** [comment]
hhvm is being executed :+1:

**Comment by LukasReschke** [comment]
```
This will break horribly if the path to PHPUnit contains spaces. I'd advise using an array to store the PHPUnit execution path, with proper quoting:

if ...; then
    PHPUNITEXE=( "$PHP" "$PHPUNIT" )
else
    PHPUNITEXE=( "$PHPUNIT" )
fi
....
"${PHPUNITEXE[@]}" --configuration ...
```

Gotta love bash :boom: :bomb: 

…

on it – thanks :see_no_evil:

**Comment by LukasReschke** [comment]
Adjusted.

**Comment by Xenopathic** [comment]
:+1:

**Pull request merged**
