### PR TITLE
by default send mail for new server-to-server share

### PR DESCRIPTION
**Pull request by schiessle**
by default send mail notification for new server-to-server share, as discussed with various people.

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@schiesbn looks like there are no unit tests on the activity extension - please add while working on this piece anyhow - THX

https://github.com/owncloud/core/commit/b533aad21697de29e8d69d7bb99b0309f2114d07

**Comment by schiesbn** [comment]
@DeepDiver1975 the activity class derives from a class which is not in core but in a separate apps repository. This makes it hard to instantiate it to run tests against the methods.

**Comment by schiesbn** [comment]
tests passed over here: https://github.com/owncloud/core/pull/13638

**Comment by DeepDiver1975** [comment]
THX :+1:

**Pull request merged**
