### PR TITLE
Update 3rdparty reference

### PR DESCRIPTION
**Pull request by LukasReschke**
Ref https://github.com/owncloud/3rdparty/pull/194

### CODE REVIEW

**Comment by LukasReschke** [comment]
@MorrisJobke :smile:

**Comment by DeepDiver1975** [comment]
Some Oracle fuck up - looks similar to the issues I had with php7 ..... Strange

**Comment by LukasReschke** [comment]
@DeepDiver1975 Oracle is fucked up on master as well.

**Comment by DeepDiver1975** [comment]
WHOT?

**Comment by DeepDiver1975** [comment]
You people drive me nuts!

**Comment by LukasReschke** [comment]
> You people drive me nuts!

Come on. We just want to ensure that you have something to do when back from holiday :speak_no_evil: :see_no_evil: :hear_no_evil:

**Comment by DeepDiver1975** [comment]
So please somebody fix it

**Comment by DeepDiver1975** [comment]
Btw: status on PostgreSQL unit test execution times?

**Comment by LukasReschke** [comment]
> 16:03:14 Time: 16.01 minutes, Memory: 209.00Mb

**Comment by LukasReschke** [comment]
No idea why https://ci.owncloud.org/job/server-master-linux/database=pgsql,label=SLAVE/2480/console takes longer… The PRs take 15 mins … mhm …

**Comment by DeepDiver1975** [comment]
THX? Any idea on the reasons why it was so slow last Werk?

**Comment by DeepDiver1975** [comment]
Afaik there are no coverage on pg

**Comment by LukasReschke** [comment]
> Afaik there are no coverage on pg

There is, see https://ci.owncloud.org/job/server-master-linux/database=pgsql,label=SLAVE/:

> 03:48:37 Generating code coverage report in Clover XML format ... done

Without coverage it takes only 15 min. With coverage it takes longer as expected…

**Comment by LukasReschke** [comment]
And then it fails on:

> 03:49:56 [Cobertura] No coverage results were found using the pattern 'tests/karma-coverage/**/cobertura-coverage.xml' relative to '/var/jenkins/workspace/server-master-linux/database/pgsql/label/SLAVE'.  Did you enter a pattern relative to the correct directory?  Did you generate the XML report(s) for Cobertura?

**Comment by DeepDiver1975** [comment]
Grrrr .... Note to self: dont mess with the CI system before vacation

**Comment by LukasReschke** [comment]
So any reviewers? ;-) :speak_no_evil:

**Comment by DeepDiver1975** [comment]
rebased ...

**Comment by DeepDiver1975** [comment]
bääääh - conflicting submodule

**Pull request merged**
