### PR TITLE
[LDAP] add second field for additional/optional display name attribute

### PR DESCRIPTION
**Pull request by blizzz**
Resolves https://github.com/owncloud/enterprise/issues/690

If the additional value is retrieved from LDAP, it as appended in brackets to the obligatory display name value. 

Example with full name as display name attribute and `samaccountname` as additional one, on personal page:

spectacle h27448

Example with mail as additional display name, on users list:

spectacle l27448

And the setting itself:

spectacle k27663

What do you think? @owncloud/ldap @karlitschek @MTRichards @scolebrook  @MorrisJobke

### CODE REVIEW

**Comment by scolebrook** [comment]
58 different kinds of awesome!

Love the avatar btw. I'm not sure HR would let me put something like that in our AD. :smile:

**Comment by MorrisJobke** [comment]
I upgraded from a manually patched version of this and everything still works :+1:

**Comment by MorrisJobke** [comment]
> What do you think? @owncloud/ldap @karlitschek @MTRichards @scolebrook @MorrisJobke

I really like this.

**Comment by blizzz** [comment]
> Love the avatar btw. I'm not sure HR would let me put something like that in our AD. :smile:

You know, 10 types of people, those with humour and those without. Not sure about the ratio in HR. But this Avatar just lives on a development setup ;)

**Comment by scolebrook** [comment]
@blizz 10! :laughing:

**Comment by PVince81** [comment]
The code looks good. If this has been tested at least in 2-3 setups, then can we merge this ? @MorrisJobke @scolebrook

**Comment by scolebrook** [comment]
@PVince81 I don't have a dev system where I can use master branch at the moment. Sorry. In fact, our regular dev system is still on 8.1. We're upgrading it in a few weeks to 8.2.x ahead of production upgrades in March. Getting a virtual host running master is on my to do list :smile:

**Comment by karlitschek** [comment]
perfect :+1:

**Comment by MorrisJobke** [comment]
> The code looks good. If this has been tested at least in 2-3 setups, then can we merge this ?

I know that it runs fine on 2 setups and mine ;)

**Comment by blizzz** [comment]
The 8.2 version this is based on was also confirmed as working and desired in https://github.com/owncloud/enterprise/issues/690#issuecomment-180546528

**Comment by MorrisJobke** [comment]
@karlitschek Is a backport of this okay or should it stay in master only?

**Comment by karlitschek** [comment]
please backport if reasonable! @blizzz

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/22250

**Pull request merged**
