### PR TITLE
Add verbosity option to app:check-code

### PR DESCRIPTION
**Pull request by MorrisJobke**
- by default only lists files with errors
- option `-v` lists all files even if there are no errors

Makes it more usable for large apps. cc @nickvergessen @DeepDiver1975 @Raydiation 

Compliant app:

```
$ ./occ app:check-code news   
App is compliant - awesome job!     
```

Verbose:

```
$ ./occ app:check-code news -v
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/plugin/client/plugin.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/fetcher/youtubefetcher.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/fetcher/fetcherexception.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/fetcher/feedfetcher.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/fetcher/ifeedfetcher.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/fetcher/fetcher.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/config/appconfig.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/config/dependencyexception.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/config/config.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/admin/admin.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/hooks/user.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/cron/updater.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/appinfo/app.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/appinfo/routes.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/appinfo/register_command.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/appinfo/application.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/folder.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/statusflag.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/mysql/itemmapper.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/feed.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/item.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/foldermapper.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/feedmapper.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/iapi.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/feedtype.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/newsmapper.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/entityjsonserializer.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/itemmapper.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/db/mapperfactory.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/explore/recommendedsites.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.content.shortcuts.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.navigation.addfeed.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.content.explore.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.navigation.unreadfeed.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.content.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.navigation.addfolder.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.content.cronwarning.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.navigation.explore.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.navigation.starredfeed.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/admin.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.navigation.feed.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.settings.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/part.navigation.folder.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/templates/index.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/foldercontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/pagecontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/itemcontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/folderapicontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/itemapicontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/feedapicontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/utilityapicontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/exportcontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/feedcontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/jsonhttperror.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/entityapiserializer.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/controller/admincontroller.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/command/generatesearchindices.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/articleenhancer/xpatharticleenhancer.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/articleenhancer/enhancer.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/articleenhancer/articleenhancer.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/articleenhancer/regexarticleenhancer.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/http/textdownloadresponse.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/http/textresponse.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/service/service.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/service/serviceexception.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/service/servicenotfoundexception.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/service/servicevalidationexception.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/service/statusservice.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/service/feedservice.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/service/serviceconflictexception.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/service/folderservice.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/service/itemservice.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/utility/opmlexporter.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/utility/updater.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/utility/picofeedfaviconfactory.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/utility/picofeedclientfactory.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps2/news/utility/proxyconfigparser.php
 0 errors
App is compliant - awesome job!
```

Not compliant app:

```
$ ./occ app:check-code user_ldap   
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/settings.php
 1 errors
    line   30: OC_Util - static method call on private class
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/helper.php
 1 errors
    line   63: OC_Config - static method call on private class
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/filesystemhelper.php
 1 errors
    line   43: OC_Util - static method call on private class
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/appinfo/app.php
 1 errors
    line   58: OC_User - static method call on private class
App is not compliant
```

Verbose

```
$ ./occ app:check-code user_ldap -v
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/user_proxy.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/settings.php
 1 errors
    line   30: OC_Util - static method call on private class
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/configuration.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/proxy.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/logwrapper.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/helper.php
 1 errors
    line   63: OC_Config - static method call on private class
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/wizardresult.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/filesystemhelper.php
 1 errors
    line   43: OC_Util - static method call on private class
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/access.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/jobs.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/jobs/cleanup.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/user/manager.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/user/iusertools.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/user/user.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/user/offlineuser.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/user/deletedusersindex.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/wizard.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/mapping/usermapping.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/mapping/abstractmapping.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/mapping/groupmapping.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/ildapwrapper.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/ldaputility.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/backendutility.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/connection.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/lib/ldap.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/appinfo/app.php
 1 errors
    line   58: OC_User - static method call on private class
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/appinfo/install.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/appinfo/routes.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/appinfo/register_command.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/group_proxy.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/user_ldap.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/templates/settings.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/templates/part.wizard-server.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/templates/part.settingcontrols.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/templates/part.wizard-userfilter.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/templates/part.wizard-groupfilter.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/templates/part.wizardcontrols.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/templates/part.wizard-loginfilter.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/command/deleteconfig.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/command/createemptyconfig.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/command/search.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/command/testconfig.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/command/showremnants.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/command/showconfig.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/command/setconfig.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/command/checkuser.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/group_ldap.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/ajax/setConfiguration.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/ajax/getConfiguration.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/ajax/deleteConfiguration.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/ajax/wizard.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/ajax/clearMappings.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/ajax/getNewServerConfigPrefix.php
 0 errors
Analysing /home/mjob/Projekte/owncloud/master/apps/user_ldap/ajax/testConfiguration.php
 0 errors
App is not compliant
```

### CODE REVIEW

**Comment by nickvergessen** [comment]
fine by me

**Comment by MorrisJobke** [comment]
> fine by me

Is this a +1 or not? ;)

**Comment by nickvergessen** [comment]
> Is this a +1 or not? ;)

since it changes something on the "public side" of owncloud, no, until approved by authorities

**Comment by nickvergessen** [comment]
Okay, let's get this in, so we can fix the hard-failure vs warning issue, before things explode on the 8.1 release

**Pull request merged**
