### PR TITLE
handle invalid storages in LazyStorageMountInfo

### PR DESCRIPTION
**Pull request by icewind1991**
Handle some more cases of trying to cache an invalid storage

### CODE REVIEW

**Comment by nickvergessen** [comment]
Makes sense code-wise, but do we need to handle the -1 anywhere else?

**Comment by icewind1991** [comment]
Don't think so

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
Makes sense :+1:

**Comment by PVince81** [comment]
I ran the integration tests localy and get this:
```
--- Failed scenarios:

    /srv/www/htdocs/owncloud/build/integration/features/provisioning-v1.feature:279
    /srv/www/htdocs/owncloud/build/integration/features/sharing-v1.feature:29
    /srv/www/htdocs/owncloud/build/integration/features/sharing-v1.feature:39
    /srv/www/htdocs/owncloud/build/integration/features/sharing-v1.feature:70
```

will rerun on master in case the problem is there, especially considering that the integration tests didn't run properly lately.

**Comment by PVince81** [comment]
I ran the tests on master and they fail there too: https://github.com/owncloud/core/issues/25090

**Pull request merged**
