### PR TITLE
Fix preview of old file on public upload conflicts

### PR DESCRIPTION
**Pull request by georgehrke**
pr #17753 was sent against stable8.1

bug is also present in master, so we need to cherry-pick the fix to master.

please review @PVince81 @oparoz

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: tested, works

**Comment by PVince81** [comment]
(merged with master when testing)
You might need to rebase

**Comment by georgehrke** [comment]
rebased

**Comment by oparoz** [comment]
Actually, the plan was to do things differently in 8.2. See @PVince81 's comment
https://github.com/owncloud/core/issues/17618#issuecomment-120993311

**Comment by georgehrke** [comment]
rebased

**Pull request merged**
