### PR TITLE
Add coverage-upload to phpunit pipelines which generate coverage

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Since some weeks no php code coverage got uploaded to codecov.io

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
core has `.drone.jsonnet` which generates `.drone.yml`
I will have a look at adjusting `.drone.jsonnet` so that it generates this coverage-upload.

Note: since the jsonnet code was done, it was decided to move to using starlark for generating the drone matrix. That has been happening in app repos. In core, the jsonnet still needs to be "converted" to starlark.

**Comment by DeepDiver1975** [comment]
coverage got uploaded - https://drone.owncloud.com/owncloud/core/20664/15/10

**Comment by DeepDiver1975** [comment]
Screenshot from 2019-09-23 12-11-48

**Comment by phil-davis** [comment]
@DeepDiver1975 I added a commit to change `pipeline.libsonnet` so it generates phpunit coverage upload.

**Comment by phil-davis** [comment]
```
Merging #36209 into master will increase coverage by 10.82%.
```
The coverage increased back to where it used to be - good stuff.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
