### PR TITLE
Always set up a config object within the user object

### PR DESCRIPTION
**Pull request by MorrisJobke**
- the new getEmailAddress and setEmailAddress relies on this anyway

This could otherwise lead to problems when the config object is not injected and the email address methods are used.

cc @DeepDiver1975 @blizzz

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Best to review with whitespace changes ignored: https://github.com/owncloud/core/pull/21832/files?w=1

**Comment by blizzz** [comment]
Hm, I'd assume if config is not passed then for a reason and we should not force to use it. Instead, add checks in the email address methods. … OTOH, urlGenerator is set like this as well. Does not seem to be very clean in my eyes.

The only instantiation without config paremeter is here (did not check tests): https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L1206, which will get to FileInfo at some point and can get retrieved by a public method. Did not look further, but config seems to be good to have. 

Since there are just two spots were user is instantiated I'd prefer to properly inject it in Files\View over doing magic.

```ack
lib/private/user/manager.php
152:            $this->cachedUsers[$uid] = new User($uid, $backend, $this, $this->config);

lib/private/files/view.php
1206:                   return new User($ownerId, null);
```

**Comment by PVince81** [comment]
Any update on this ?

**Comment by MorrisJobke** [comment]
> Any update on this ?

I tried to replace all occurrences, but dealing with all this in the test cases is a nightmare :( I would like to keep it as it is now. cc @blizzz

**Comment by blizzz** [comment]
Well, then, it's still an improvement :+1:

**Comment by MorrisJobke** [comment]
Rebased to retrigger CI

@nickvergessen @LukasReschke @PVince81 @rullzer Please review :)

**Comment by LukasReschke** [comment]
:speak_no_evil: :see_no_evil: :hear_no_evil: :+1:

**Pull request merged**
