### PR TITLE
[stable10] Initialize the root folder lazily

### PR DESCRIPTION
**Pull request by jvillafanez**
## Related Issue
https://github.com/owncloud/enterprise/issues/2445

## How Has This Been Tested?
Manually tested as described in the issue

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
I guess "backport request" is really "forwardport request" in this case, since this PR is against ``stable10`` and the change needs to go forward to ``master``

**Comment by PVince81** [comment]
> I guess "backport request" is really "forwardport request" in this case

yes it is. no need for another label

**Review by butonic — APPROVED** [review]

**Comment by PVince81** [comment]
@jvillafanez please port to master

**Comment by jvillafanez** [comment]
Port in https://github.com/owncloud/core/pull/30875

**Pull request merged**
