### PR TITLE
Revert "Bump @bower_components/bowser from 1.6.0 to 2.1.0 in /build"

### PR DESCRIPTION
**Pull request by PVince81**
Reverts owncloud/core#34333

### CODE REVIEW

**Comment by individual-it** [comment]
now we have a JS test failure

```
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Sharing.App tests Action events accept share triggers reload of sharein and files fileLists FAILED
	Expected 2 to equal 1.
	<Jasmine>
	apps/files_sharing/tests/js/appSpec.js:313:50
	<Jasmine>
	Expected 2 to equal 1.
	<Jasmine>
	apps/files_sharing/tests/js/appSpec.js:314:43
<Jasmine>
```

**Review by individual-it — APPROVED** [review]
JS test issue should be fixed by  #34436

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by individual-it** [comment]
some tests failing because the nightly QA build is broken

**Comment by phil-davis** [comment]
Note: FYI this bump never happened in master, PR #34289 was purposely closed, which turned out to be "a good thing"

**Pull request merged**
