### PR TITLE
[Tests-Only] Send coverage to SonarCloud

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Analyse and upload to SonarCloud.

1) At the end of each JavaScript and PHPunit pipeline that collects coverage, sync the coverage report to an S3 cache
2) After all coverage-related pipelines are finished, sync the coverage reports from the S3 cache to a local pipeline `sonar-analysis`
3) Setup a "server" in that analysis pipeline so that the source code is there to analyse.
4) Run the Sonar analysis and let it upload to SonarCloud

SonarCloud analysis in drone is at https://drone.owncloud.com/owncloud/core/27145/34/9
The report is at https://sonarcloud.io/dashboard?id=owncloud_core&pullRequest=37982

The report shows 55.1% coverage. I was hoping that it would show about 64% like the old covedcov reports, e.g. https://github.com/owncloud/core/pull/37956#issuecomment-700255057

The analysis emits messages like:
```
INFO: Analyzing PHPUnit coverage report: results/clover-phpunit-php7.2-mariadb10.2.xml
WARN: Could not resolve 5098 file paths in clover-phpunit-php7.2-mariadb10.2.xml, first unresolved path: /drone/src/config/config.php
```

I have not been able to work out why the `WARN` is there. The source files are in `/drone/src` - I asked in chat https://community.sonarsource.com/t/how-to-get-total-coverage-from-multiple-unit-test-runs/31719/11 but no response.

Note: This is a cleaned-up, rebased and squashed version of PR #37946 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by micbar** [comment]
54,1 % arrived at sonarcloud.
Seems we are  still missing some files.

**Comment by phil-davis** [comment]
I was hoping for 64%  coverage. See the top post - I can't work out what to do next to help it get better...

**Comment by micbar** [comment]
maybe we need to work on the exclusions?

**Comment by phil-davis** [comment]
@micbar commented https://github.com/owncloud/core/pull/37984#issuecomment-704242386
"Yes. let us merge and see." - to get an initial set of `master` coverage information where we will be able to (hopefully)  browse around the results and see the detail of the coverage that SonarCloud is calculating.

I also found https://community.sonarsource.com/t/sonarqube-and-code-coverage/4725 - that has information about how the "coverage" metric is calculated by SonarCloud. It includes calculations of conditions that have evaluated to both true and false, as well as "basic line coverage". So that might also have some influence on the numbers.

After merging, we will see...

**Comment by phil-davis** [comment]
This code was merged in #37984

**Pull request merged**
