### PR TITLE
Complex webdav properties support

### LINKED ISSUE #32670: Cannot store complex custom Webdav property values + wrong values + Oracle failure
### Steps

1. Create a file "proppatch.xml" with the contents `<?xml version="1.0" encoding="utf-8" ?><propertyupdate xmlns='DAV:'><set><prop><t:valnspace xmlns:t='http://example.com/neon/litmus/'><foo xmlns='http://bar'/></t:valnspace></prop></set></propertyupdate>` which sets a complex value
1. Create a folder "test" in the OC instance
1. `curl -k -D - -u admin:admin -X PROPPATCH -H "Content-Type: text/xml" --data-binary "@proppatch.xml" "http://localhost/owncloud/remote.php/webdav/test"`
1. Create a file "propfind.xml" with the contents `<?xml version="1.0"?><a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns"><a:prop><t:valnspace xmlns:t='http://example.com/neon/litmus/'/>        </a:prop></a:propfind>`
1. `curl -k -D - -u admin:admin -X PROPFIND -H "Content-Type: text/xml" --data-binary "@propfind-oracle.xml" "http://localhost/owncloud/remote.php/webdav/test"`
1. Check the "oc_properties" database table

### Expected result
oc_properties table must contain `<foo xmlns='http://bar'/>` or something alike.
the PROPFIND response should contain `<foo xmlns='http://bar'/>`.

#### With MySQL
oc_properties table contain the string "Object" as value.
the PROPFIND response contains `<x1:valnspace xmlns:x1="http://example.com/neon/litmus/">Object</x1:valnspace>`

#### With Oracle
PROPPATCH fails:
```

{"reqId":"u35FUAVYSNddV4jLeZoS","level":4,"time":"2018-09-10T20:50:17+00:00","remoteAddr":"172.18.0.4","user":"admin","app":"webdav","method":"PROPPATCH","url":"\/remote.php\/webdav\/litmus\/prop2","message":"Exception: An exception occurred while executing 'INSERT INTO \"oc_properties\" (\"fileid\",\"propertyname\",\"propertyvalue\") VALUES(?,?,?)' with params [123, \"{http:\\\/\\\/example.com\\\/neon\\\/litmus\\\/}valnspace\", {}]:\n\nORA-01008: not all variables bound: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO \\\"oc_properties\\\" (\\\"fileid\\\",\\\"propertyname\\\",\\\"propertyvalue\\\") VALUES(?,?,?)' with params [123, \\\"{http:\\\\\\\/\\\\\\\/example.com\\\\\\\/neon\\\\\\\/litmus\\\\\\\/}valnspace\\\", {}]:\\n\\nORA-01008: not all variables bound\",\"Code\":0,\"Trace\":\" #0 \\\/drone\\\/src\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractOracleDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\OCI8\\\\OCI8Exception))\\n #1 \\\/drone\\\/src\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\OCI8\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\OCI8\\\\OCI8Exception), 'INSERT INTO \\\"oc...', Array)\\n #2 \\\/drone\\\/src\\\/lib\\\/private\\\/DB\\\/Connection.php(207): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO \\\"oc...', Array, Array)\\n #3 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/DAV\\\/FileCustomPropertiesBackend.php(182): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO \\\"oc...', Array)\\n #4 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/DAV\\\/AbstractCustomPropertiesBackend.php(206): OCA\\\\DAV\\\\DAV\\\\FileCustomPropertiesBackend->updateProperties('litmus\\\/prop2', Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File), Array)\\n #5 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropPatch.php(317): OCA\\\\DAV\\\\DAV\\\\AbstractCustomPropertiesBackend->OCA\\\\DAV\\\\DAV\\\\{closure}(Array)\\n #6 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropPatch.php(245): Sabre\\\\DAV\\\\PropPatch->doCallBackMultiProp(Array, Object(Closure))\\n #7 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1265): Sabre\\\\DAV\\\\PropPatch->commit()\\n #8 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(385): Sabre\\\\DAV\\\\Server->updateProperties('litmus\\\/prop2', Array)\\n #9 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropPatch(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n #10 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n #11 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPPATC...', Array)\\n #12 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n #13 \\\/drone\\\/src\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(64): Sabre\\\\DAV\\\\Server->exec()\\n #14 \\\/drone\\\/src\\\/remote.php(165): require_once('\\\/drone\\\/src\\\/apps...')\\n #15 {main}\",\"File\":\"\\\/drone\\\/src\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractOracleDriver.php\",\"Line\":76}"}
--
```

This is likely because the complex value cannot be converted to string properly, so some process in Doctrine attempts to transform it to string. In MySQL it becomes `Object`, with Oracle it becomes an empty string or the weird `{}` value in the query.

### Version
ownCloud 10.0.10 RC1

Discovered while debugging Oracle Litmus failure with PROPPATCH, see https://github.com/owncloud/core/pull/32639#issuecomment-420236619

Not sure if this ever worked before.
I'm really surprised Litmus lets this pass for MySQL.

I suspect this never worked before as we never really tested with complex properties.

### LINKED ISSUE #37027: Custom properties not working with Oracle
Run the acceptance tests with Oracle database. (see PR #37025 )
https://drone.owncloud.com/owncloud/core/23587/63/13
```
  Scenario: add multiple properties to files inside a folder and do a propfind of the parent folder        # /drone/src/tests/acceptance/features/apiWebdavProperties/getFileProperties.feature:215
    Given user "user0" has created folder "/TestFolder"                                                    # FeatureContext::userHasCreatedFolder()
    And user "user0" has uploaded file with content "test data one" to "/TestFolder/test1.txt"             # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "user0" has uploaded file with content "test data two" to "/TestFolder/test2.txt"             # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "user0" has set the following properties of file "/TestFolder/test1.txt" using the WebDav API # WebDavPropertiesContext::userHasSetFollowingPropertiesUsingProppatch()
      | property  | value |
      | testprop1 | AAAAA |
      | testprop2 | BBBBB |
    And user "user0" has set the following properties of file "/TestFolder/test2.txt" using the WebDav API # WebDavPropertiesContext::userHasSetFollowingPropertiesUsingProppatch()
      | property  | value |
      | testprop1 | CCCCC |
      | testprop2 | DDDDD |
    When user "user0" gets the following properties of folder "/TestFolder" using the WebDav PropFind API  # WebDavPropertiesContext::userGetsFollowingPropsWithNamespaceOfFileUsingWebDavAPI()
      | property  |
      | testprop1 |
      | testprop2 |
    Then the HTTP status code should be success                                                            # FeatureContext::theHTTPStatusCodeShouldBeSuccess()
    And as user "user0" the last response should have the following properties                             # WebDavPropertiesContext::theResponseShouldHavePropertyWithValue()
      | resource              | property  | value                  |
      | /TestFolder/test1.txt | testprop1 | CCCCC                  |
      | /TestFolder/test1.txt | testprop2 | BBBBB                  |
      | /TestFolder/test2.txt | testprop1 | CCCCC                  |
      | /TestFolder/test2.txt | testprop2 | DDDDD                  |
      | /TestFolder/          | status    | HTTP/1.1 404 Not Found |
      WebDavPropertiesContext::theResponseShouldHavePropertyWithValue Expected 'CCCCC' but got 'AAAAA'
      Failed asserting that SimpleXMLElement Object &0000000004dff26d000000000e2b1393 (
          0 => 'AAAAA'
      ) matches expected 'CCCCC'.
```

```
  Scenario Outline: Setting custom complex DAV property and reading it                                                                                             # /drone/src/tests/acceptance/features/apiWebdavProperties/setFileProperties.feature:24
    Given using <dav_version> DAV path                                                                                                                             # FeatureContext::usingOldOrNewDavPath()
    And user "user0" has uploaded file "filesForUpload/textfile.txt" to "/testcustomprop.txt"                                                                      # FeatureContext::userHasUploadedAFileTo()
    And user "user0" has set property "very-custom-prop" with namespace "x1='http://whatever.org/ns'" of file "/testcustomprop.txt" to "<foo xmlns='http://bar'/>" # WebDavPropertiesContext::userHasSetPropertyWithNamespaceOfEntryTo()
    When user "user0" gets a custom property "very-custom-prop" with namespace "x1='http://whatever.org/ns'" of file "/testcustomprop.txt"                         # WebDavPropertiesContext::userGetsPropertiesOfFile()
    Then the response should contain a custom "very-custom-prop" property with namespace "x1='http://whatever.org/ns'" and value "Object"                          # WebDavPropertiesContext::theResponseShouldContainACustomPropertyWithValue()

    Examples:
      | dav_version |
      | old         |
        The HTTP status code 500 is not between 200 and 299
        Failed asserting that 500 is equal to 299 or is less than 299.
      | new         |
        The HTTP status code 500 is not between 200 and 299
        Failed asserting that 500 is equal to 299 or is less than 299.
```

```
--- Failed scenarios:

    /drone/src/tests/acceptance/features/apiWebdavProperties/getFileProperties.feature:215
    /drone/src/tests/acceptance/features/apiWebdavProperties/setFileProperties.feature:33
    /drone/src/tests/acceptance/features/apiWebdavProperties/setFileProperties.feature:34

96 scenarios (93 passed, 3 failed)
697 steps (690 passed, 3 failed, 4 skipped)
```

### PR DESCRIPTION
**Pull request by VicDeo**
- [x] requires at least minor version bump for the dav app

## Description
Store webdav property type  along with the value

## Related Issue
Fixes #32670 
Fixes #37027 

## Motivation and Context
Proper Complex webdav properties support

## How Has This Been Tested?
acceptance tests
also see https://github.com/owncloud/core/issues/32670#issue-359004368

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
@VicDeo I expect that you will need to adjust acceptance test scenario https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdavProperties/setFileProperties.feature#L23 to check for the now-correct value being returned.

**Comment by VicDeo** [comment]
@phil-davis thanks. I want to check whether it fails anything else.

**Comment by DeepDiver1975** [comment]
Please keep in mind that this table is really hugh on some installations - schema change will take forever .....

**Comment by VicDeo** [comment]
@DeepDiver1975 yes, but it is possible to add these fields in advance before upgrading the code.
I wrote the migration in a way that it does nothing when the field exists already

**Comment by VicDeo** [comment]
@phil-davis I updated the acceptance test as it  parsed complex values incorrectly.

**Comment by micbar** [comment]
@pmaier1 Let us consider to include it in 10.5

**Review by phil-davis — COMMENTED** [review]
Looks OK in acceptance tests.

Needs a couple of unit tests adjusted for dav 0.6.0

**Comment by jvillafanez** [comment]
Code changes look fine.
There is a deleted comment about Oracle and php 7.4. I'm not sure if we have tests with that setup or if this has been tested.

**Comment by phil-davis** [comment]
> There is a deleted comment about Oracle and php 7.4. I'm not sure if we have tests with that setup or if this has been tested.

Is it related to #37312 ? and issue #37026 ? That was an intermittent problem with restoring checksums from trashbin with Oracle. (maybe not related)

**Comment by jvillafanez** [comment]
> Is it related to #37312 ? and issue #37026 ? That was an intermittent problem with restoring checksums from trashbin with Oracle. (maybe not related)

This is the comment https://github.com/owncloud/core/pull/37314/files#diff-d9adeff76c4cf2852e19574ce708c588L190-L192
It seems unrelated to the checksum problem mentioned

**Comment by VicDeo** [comment]
@jvillafanez 
> This is the comment https://github.com/owncloud/core/pull/37314/files#diff-d9adeff76c4cf2852e19574ce708c588L190-L192
It seems unrelated to the checksum problem mentioned

This PR fixes exactly that FixMe: a webdav property  constructed using a class `Complex` is serialized properly now

**Review by jvillafanez — APPROVED** [review]

**Pull request merged**
