### PR TITLE
Adding symfony events for feature change in group admin

### PR DESCRIPTION
**Pull request by sharidas**
When a user is made as group admin or when a user
is removed as group admin, a symfony event is triggered.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

A symfony event is triggered when a user is added to a group as group admin. Similarly when a user is removed as group admin.

## Motivation and Context

A symfony event is triggered when a user is added to a group as group admin. Similarly when a user is removed as group admin.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sharidas** [comment]
Stable10 branch PR : https://github.com/owncloud/core/pull/31132

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
