### PR TITLE
Remove info about database locking performance

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@karlitschek @LukasReschke @jancborchardt @jospoortvliet @dragotin @jnweiger

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:  as discussd. please backport

**Comment by DeepDiver1975** [comment]
> :+1: as discussd. please backport

https://github.com/owncloud/core/pull/21124

**Comment by karlitschek** [comment]
@jnweiger @dragotin @cmonteroluque @msrex FYI
This will be gone

**Comment by icewind1991** [comment]
Any specific reason why? I feel it's good to tell admins that there are steps they can take to increase performance

**Comment by DeepDiver1975** [comment]
> Any specific reason why? I feel it's good to tell admins that there are steps they can take to increase performance

business ...

**Comment by karlitschek** [comment]
this should go into the performance tuning documentation instead. @carlaschroder

**Comment by icewind1991** [comment]
> business ...

Where using redis will be even more important for performance...

**Comment by carlaschroder** [comment]
> this should go into the performance tuning documentation instead.

It's already there:
https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/performance_tuning/oc_server_tuning.html#caching
https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/caching_configuration.html
https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/files_locking_transactional.html

**Comment by karlitschek** [comment]
awesome

**Comment by DeepDiver1975** [comment]
so - merge and bye-bye

**Pull request merged**
