### PR TITLE
[Not merge] Remove patchwork library

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Remove the patchwork library because it won't be used anymore

## Related Issue
Requested in https://github.com/owncloud/core/pull/29500#issuecomment-342604553

## How Has This Been Tested?
Manually tested:

* ✅  Having the php-intl package installed and a working ownCloud installation, I've created some folders with utf8 names and upload several files also with utf8 name. No problems detected.

    The behaviour seems to be the same with and without the library, which includes some chars drawn as fallback symbols in some situations (very likely browser related, but anyway patchwork won't fix the issue)
* ⚪️  Removing the php-intl package will crash ownCloud (kind of expected):

    ```
    {"reqId":"HJIE7sQ6C9tMY6AmcmSL","level":3,"time":"2017-11-08T09:28:06+00:00","remoteAddr":"10.0.2.4","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'Normalizer' not found\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(864): OC_Util::normalizeUnicode('\\\/admin\\\/files_ex...')\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1099): OC\\\\Files\\\\Filesystem::normalizePath('\\\/admin\\\/files_ex...')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(380): OC\\\\Files\\\\View->basicOperation('is_dir', '\\\/admin\\\/files_ex...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Security\\\/CertificateManager.php(76): OC\\\\Files\\\\View->is_dir('\\\/admin\\\/files_ex...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(66): OC\\\\Security\\\\CertificateManager->listCertificates()\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(135): OC\\\\Http\\\\Client\\\\Client->setDefaultOptions()\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Updater\\\/VersionCheck.php(111): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/updates...')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Updater\\\/VersionCheck.php(81): OC\\\\Updater\\\\VersionCheck->getUrlContent('https:\\\/\\\/updates...')\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/updatenotification\\\/lib\\\/UpdateChecker.php(42): OC\\\\Updater\\\\VersionCheck->check()\\n#9 \\\/opt\\\/owncloud\\\/apps\\\/updatenotification\\\/appinfo\\\/app.php(36): OCA\\\\UpdateNotification\\\\UpdateChecker->getUpdateState()\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(223): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(174): OC_App::requireAppFile('updatenotificat...')\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(128): OC_App::loadApp('updatenotificat...')\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/base.php(913): OC_App::loadApps()\\n#14 \\\/opt\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php\",\"Line\":1359}"}
    ```
* ~After reinstalling the php-intl package, there has been some problems with files having utf8 chars, not sure if some weird locale was set at some point. The "Setting locale to ... failed" error message appeared.~ https://github.com/owncloud/core/pull/29508/commits/1389f290fe2ea445b831d308738723270258ca75 seems to solve the problem
* 🔴  ~Upgrade hasn't been tested yet, but it seems we should prevent the upgrade somehow if the php-intl package isn't installed.~ Check https://github.com/owncloud/core/pull/29508#issuecomment-342807566

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Note that some of the sabre urls in the composer.lock file have changed.

### CODE REVIEW

**Comment by jvillafanez** [comment]
> The behaviour seems to be the same with and without the library, which includes some chars drawn as fallback symbols in some situations (very likely browser related, but anyway patchwork won't fix the issue)

To be a bit clearer, target file name is `Ḽơᶉëᶆ ȋṕšᶙṁ ḍỡḽǭᵳ ʂǐť ӓṁệẗ, ĉṓɲṩḙċťᶒțûɾ ấɖḯƥĭṩčįɳġ ḝłįʈ.dat` inside a folder `Ḽơᶉëᶆ ȋṕšᶙṁ/ḍỡḽǭᵳ ʂǐť ӓṁệẗ`.

Chrome rendered all the symbols fine, while firefox (50.1.0) had some problems rendering some symbols in some parts of the window (title is fine but not the rest of the window). The file was downloaded with the right name in any case.

**Comment by jvillafanez** [comment]
Upgrading from stable10 to the branch **without** the php-intl package makes ownCloud explode:
```
An unhandled exception has been thrown:
Error: Class 'Normalizer' not found in /opt/owncloud/lib/private/legacy/util.php:1364
Stack trace:
#0 /opt/owncloud/lib/private/Files/Filesystem.php(864): OC_Util::normalizeUnicode('/')
#1 /opt/owncloud/lib/private/Files/Mount/MountPoint.php(207): OC\Files\Filesystem::normalizePath('/')
#2 /opt/owncloud/lib/private/Files/Mount/MountPoint.php(93): OC\Files\Mount\MountPoint->formatPath('/')
#3 /opt/owncloud/lib/private/Files/Filesystem.php(528): OC\Files\Mount\MountPoint->__construct('\\OC\\Files\\Stora...', '/', Array, Object(OC\Files\Storage\StorageFactory))
#4 /opt/owncloud/lib/private/legacy/util.php(83): OC\Files\Filesystem::mount('\\OC\\Files\\Stora...', Array, '/')
#5 /opt/owncloud/lib/private/legacy/util.php(283): OC_Util::initLocalStorageRootFS()
#6 /opt/owncloud/lib/private/Files/Filesystem.php(265): OC_Util::setupFS('')
#7 /opt/owncloud/lib/private/Server.php(222): OC\Files\Filesystem::getMountManager(NULL)
#8 /opt/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /opt/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('RootFolder')
#10 /opt/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('RootFolder')
#11 /opt/owncloud/lib/private/Server.php(935): OC\ServerContainer->query('RootFolder')
#12 /opt/owncloud/lib/private/Server.php(423): OC\Server->getRootFolder()
#13 /opt/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /opt/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('AvatarManager')
#15 /opt/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AvatarManager')
#16 /opt/owncloud/lib/private/Server.php(926): OC\ServerContainer->query('AvatarManager')
#17 /opt/owncloud/lib/private/Repair.php(142): OC\Server->getAvatarManager()
#18 /opt/owncloud/core/register_command.php(135): OC\Repair::getRepairSteps()
#19 /opt/owncloud/lib/private/Console/Application.php(92): require_once('/opt/owncloud/c...')
#20 /opt/owncloud/console.php(105): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /opt/owncloud/occ(11): require_once('/opt/owncloud/c...')
#22 {main}
```
After installing the php-intl package, the upgrade runs without further problems. After a quick check, everything seems in place.

We should prevent the upgrade in a nicer way.

**Comment by jvillafanez** [comment]
@DeepDiver1975 @PVince81 any idea about how we can handle the error above? I'm afraid people will upgrade to the next version without the php-intl module installed and they'll have ownCloud in a completely unusable state until they install the module, and there is no hint to tell the users to install it.

I'll try to catch and handle the error around lib/private/Console/Application.php

**Comment by jvillafanez** [comment]
Some possible solutions:
* Catch the error thrown and run the `occ check` command (which I guess it's what should be working but it isn't). The problem is that the solution is only viable for PHP7+ so PHP5.6 will remain with the problem.
* Remove the `occ check` command and force the underlying checks to be run before any other command. I guess this is the best option available. Note that the output from the checks and the actual command will overlap, I mean the error output from the check might be interpreted as a valid output of the command, which might cause some confusion.

**Comment by DeepDiver1975** [comment]
> Removing the php-intl package will crash ownCloud (kind of expected):

which is not allowed - its a hard requirement

**Comment by jvillafanez** [comment]
The problem is the upgrade from a previous version without having the php-intl installed (https://github.com/owncloud/core/pull/29508#issuecomment-342807566). Other scenarios seem acceptable.

**Comment by jvillafanez** [comment]
Anything to do here?

**Comment by PVince81** [comment]
should we close this then if it has no solution and no high priority ?

**Comment by jvillafanez** [comment]
We can schedule the removal of the library to 11.0 (?) and make announcements that the library will be removed in that version so people can install the php-intl library with enough time to jump over the problem, but that won't work for everyone.

**Pull request closed without merging**
