### PR TITLE
25532_issue_password_update_notification

### PR DESCRIPTION
**Pull request by JackWillDavis**
Applying a fix for issue #25532

This adds a temporary notification on updating a user password so the user knows it has gone through successfully. Previously, there was no feedback provided to the user unless it failed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Thanks a lot for your contribution @JackWillDavis 

Please squash your commits into one - THX

**Comment by DeepDiver1975** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by JackWillDavis** [comment]
Right, I can't seem to be able to rebase the commits for some reason. Is it better if I just create a new pull request and delete this one?

**Comment by DeepDiver1975** [comment]
> Is it better if I just create a new pull request and delete this one?

if rebase doesn't work - yes please.

**Pull request closed without merging**
