### PR TITLE
Make getLanguageCode() return the current language when it's being forced

### LINKED ISSUE #145: Notification mails sometimes use a wrong language
The title is translated correctly, but the email text sometimes is in the language of the user which triggered the email, rather then the recipient.

Copied from owncloud/core#10859

### PR DESCRIPTION
**Pull request by nickvergessen**
The method has fooled me more then once already. The name implies behavior that is not given.

3 Examples of what you would think:

``` php
'de' === OC_L10N::get('lib', 'de')->getLanguageCode();
'de' === (new \OC\L10N\Factory())->get('lib', 'de')->getLanguageCode();
'de' === \OC::$server->getL10N('lib', 'de')->getLanguageCode();
```

However the old `getLanguageCode()` was more a `tryToFindTheCorrectLanguageForThisUserAndAGivenApp()` (always returns the personal language of the user instead of the one set via the constructor)
The only method that was using it in this way was `Util::addTranslations()`. I changed that method to use OC_L10N::findLanguage() directly, instead of creating an object and then call a method on the object which then calls `findLanguage()`.

@DeepDiver1975 can we have this please? Otherwise I need to create a new method with a name that is close to similar which reflects the correct behaviour. No one should manually rely on this method in it's old way anyhow, since they can just keep `null` in the constructor and will have the old behaviour.

Fix owncloud/activity#145

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@nickvergessen looks like we need another pr for jenkins :sigh: - THX

**Comment by nickvergessen** [comment]
Rebased version passed at #14674
@LukasReschke second +1

**Comment by LukasReschke** [comment]
@nickvergessen Not since you left me in the office :cry:

**Comment by LukasReschke** [comment]
:+1:

**Comment by nickvergessen** [comment]
Merged the rebased branch

**Pull request closed without merging**
