### PR TITLE
Make app updates better visible (part1)

### LINKED ISSUE #17230: AppStore: Make updates more prominent with sidebar entry + notification
We should make updates more prominent with a dedicated side bar entry and also a yellow notification such as we have for normal system updates to remind admins. Probably worth doing together with https://github.com/owncloud/core/issues/17223

Updating applications currently requires to go to the apps menu as well as select update which nearly no admin does :speak_no_evil:

### PR DESCRIPTION
**Pull request by nickvergessen**
1. Show a temp notification when there are app updates available
2. Show a red message on apps that have an update available for better visibility
3. Add an option to filter for apps with updates.

bildschirmfoto vom 2016-02-16 12 55 34

Fix #17230 

@PVince81 @jancborchardt @LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by jancborchardt** [comment]
As @PVince81 and I said in https://github.com/owncloud/core/issues/17230, there’s a simpler way:

> > It should probably be like on Android: have a grouped block at the top containing all the apps that need upgrading.
> 
> Exactly what I would have suggested. Just sort the apps which need upgrade up top in the »Enabled« list.

**Comment by nickvergessen** [comment]
resorting the apps list is not simpler and most likely nothing we can do in the remaining time. If you want resorting its going to be one more release-cycle

**Comment by nickvergessen** [comment]
> resorting the apps list is not simpler and most likely nothing we can do in the remaining time

As an explanation, because the update information is loaded async afterwards, because the appstore has not the needed functionality to get all infos with one call, we would display the result in order A, B, C and then reorder it to C, A, B. If you happen to just (try to) press any button in the moment of reordering, it's going to be a worse experience and not a better one. That's why I added the filter-checkbox

**Comment by MorrisJobke** [comment]
> As an explanation, because the update information is loaded async afterwards, because the appstore has not the needed functionality to get all infos with one call, we would display the result in order A, B, C and then reorder it to C, A, B.

Why then not simply wait for the other call to respond. Or show a "checking for updates..." feedback.

**Comment by karlitschek** [comment]
this is awesome! :+1:  Thanks @nickvergessen

**Comment by nickvergessen** [comment]
> Why then not simply wait for the other call to respond. Or show a "checking for updates..." feedback.

Because then we show a blank page for `1.5+sec * num-of-apps` which I think is very bad. We intentionally moved it to be async, this is a great step forward already. Once the app store has the endpoint to get multiple ids and tell us the last version for it, that can be extended and done in a better way... little step forward in the meantime or not, that's the question

**Comment by jancborchardt** [comment]
> resorting the apps list is not simpler

@nickvergessen I was referring to the UX of course.

If this change needs to be, please only do the »There are updates available for X apps«. The checkbox is not necessary.

**Comment by nickvergessen** [comment]
> The checkbox is not necessary.

If you have a list of 20 apps, with having an update available, the checkbox is quite nice, because it hides all non-update-apps.
Btw the checkbox only shows up when you have an app that needs an update. But sure, if you still insist on removing it, I can do that.

**Comment by LukasReschke** [comment]
I'd prefer if we keep that TBH :+1:

**Comment by PVince81** [comment]
Another alternative idea: have an additional section in the left navigation bar "Updatable apps"

**Comment by jancborchardt** [comment]
Yeah, both having updateable apps sorted up top or having a section in the sidebar »Updates« would be better than this strangely placed checkbox.

**Comment by nickvergessen** [comment]
And both require the endpoint on the appstore.
The "strangely placed checkbox" is in a controls bar, just like breadcrumb+upload button on the file list.

**Comment by jancborchardt** [comment]
Well, then we should provide the endpoint on the appstore.

**Comment by nickvergessen** [comment]
Removed the checkbox, ready to go in

**Comment by LukasReschke** [comment]
:+1:

**Comment by jancborchardt** [comment]
Yep, sounds good. Next step then is to add the endpoint to the appstore to properly sort the apps to update up top. You can see how nicely that works from the Play store and iOS app store.

**Comment by PVince81** [comment]
:+1:

**Comment by jancborchardt** [comment]
@nickvergessen will you be taking care of the »sort apps with updates to top« or should I create an issue?

**Comment by nickvergessen** [comment]
create an issue and put it to backlog

**Pull request merged**
