### PR TITLE
Issue #19790 File name and sharee user name are overlapped

### PR DESCRIPTION
**Pull request by edwardcrompton**
Please see #19790

### CODE REVIEW

**Comment by schiesbn** [comment]
Great, thanks for stepping up and fixing it!

I just gave it a try and resized the window from quite small (short before it would switch to the mobile view) to large. What I observed is that somewhere in the middle the user name is shortened but for smaller or larger windows it goes back to the full user name. While you could argue that for larger windows it is the right behavior it is probably wrong for smaller windows.

small window:



medium size window:



large window:

**Comment by jancborchardt** [comment]
@edwardcrompton awesome, thanks for the contribution! Can you fix the issues mentioned by @schiesbn? :)

@rperezb @davitol please review as well.

**Comment by PVince81** [comment]
@edwardcrompton any update ? See https://github.com/owncloud/core/pull/19873#issuecomment-149829681

**Comment by edwardcrompton** [comment]
Hi @PVince81 @schiesbn thanks for the review and for waiting!

I've updated this so that the username and filename are appropriate sizes at smaller screen sizes. I've tested on chrome at screensizes of 1200px and lower.

You'll notice that there is also a reference to a class called ".with-app-sidebar" and I haven't made any changes to the max-width when this class is present. Do you know under what conditions this class appears so that I can check this condition too?

**Comment by jancborchardt** [comment]
@edwardcrompton .with-app-sidebar appears when the right app-sidebar is present, that is when you open sharing, versions or the file details.

@owncloud/designers please review as well. :)

**Comment by edwardcrompton** [comment]
@jancborchardt Thanks. I've added conditions for when the right app-sidebar is present too.

**Comment by jancborchardt** [comment]
@edwardcrompton can you rebase the branch against master again? Also please squash the commits into one. :)

**Comment by LukasReschke** [comment]
Commits squashed in https://github.com/owncloud/core/pull/21872 (`git rebase -i master`)  and also on our organisation for unit test execution.

Thanks a lot again for your contribution, @edwardcrompton. Much appreciated :rocket:

**Pull request closed without merging**
