### PR TITLE
Repeated calls to loginWithApache() should not not try to set user in…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #18481

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
@LukasReschke ?

**Comment by LukasReschke** [comment]
Well, I'm fine with this but don't have any Shibboleth setup. If it works: Great. Seems like a hack but as long as it works :speak_no_evil:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
