### PR TITLE
External share dialog must properly read entered password

### LINKED ISSUE #13526: Remote share with password cannot be mounted
On master, but nees https://github.com/owncloud/core/pull/13506 to be applied first:

### Steps
1. As "user1": create a folder "folder"
2. Share "folder" with link, set a password
3. Log out
4. As "user2" on the same instance, open the link
5. Add to ownCloud (the same instance)
6. Getting "unknown error"

The log says "Passed token is not valid".
```
{"reqId":"0a75dbcbf1557247ced4272b6b14aff1","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the server container is deprecated. Use type annotations to inject core services instead!","level":0,"time":"2015-01-20T17:08:33+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/external"}
{"reqId":"15b662b406ae36d2b8618953d494a469","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the server container is deprecated. Use type annotations to inject core services instead!","level":0,"time":"2015-01-20T17:08:34+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/shareinfo?t=wNN0001MDhGfTpx"}
{"reqId":"15b662b406ae36d2b8618953d494a469","remoteAddr":"127.0.0.1","app":"core-preview","message":"Passed token parameter is not valid","level":0,"time":"2015-01-20T17:08:34+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/shareinfo?t=wNN0001MDhGfTpx"}
{"reqId":"0a75dbcbf1557247ced4272b6b14aff1","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\Files_Sharing\\\\External\\\\Storage->getShareInfo()\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(466): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(22): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->__call('getShareInfo', Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(22): OCA\\\\Files_Trashbin\\\\Storage->getShareInfo()\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/ajax\\\/external.php(55): OCA\\\\Files_Sharing\\\\External\\\\Scanner->scanAll()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_2406', Array)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_sha...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(28): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php\",\"Line\":228}","level":4,"time":"2015-01-20T17:08:34+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_sharing\/external"}
```

@icewind1991 @LukasReschke @schiesbn 

Marked as OC 8 showstopper @karlitschek @DeepDiver1975

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/13526

Also introduces JS unit tests for that JS code.

Please review @schiesbn @icewind1991 @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Check the white space free version of the diff: https://github.com/owncloud/core/pull/13540/files?w=1

Note: this replaces `$(document).ready()` with a plugin-attach logic that only runs when the files app is there.
This means the share confirm dialog will now only pop up in the files app, which I think is ok.

**Comment by icewind1991** [comment]
Tested :+1:

**Comment by DeepDiver1975** [comment]
finding during testing this pr:

adding the same share twice results in exception in the log and a status code 500 in the browser

```json
{"reqId":"8180dfc4ff291c16a84c8970f8f5a8e5","remoteAddr":"::1","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\Files_Sharing\\\\External\\\\Storage->getShareInfo()\\n#1 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(466): call_user_func_array(Array, Array)\\n#2 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(22): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->__call('getShareInfo', Array)\\n#3 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/scanner.php(22): OCA\\\\Files_Trashbin\\\\Storage->getShareInfo()\\n#4 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core\\\/apps\\\/files_sharing\\\/ajax\\\/external.php(55): OCA\\\\Files_Sharing\\\\External\\\\Scanner->scanAll()\\n#5 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/home\\\/deepdiver...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_1792', Array)\\n#8 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_sha...')\\n#9 \\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core\\\/index.php(28): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/deepdiver\\\/Development\\\/ownCloud\\\/core\\\/apps\\\/files_sharing\\\/lib\\\/external\\\/storage.php\",\"Line\":228}","level":4,"time":"2015-01-21T15:41:02+00:00","method":"POST","url":"\/oc\/core\/index.php\/apps\/files_sharing\/external"}

**Comment by PVince81** [comment]
This PR should fix many of the exceptions: https://github.com/owncloud/core/pull/13525

**Comment by DeepDiver1975** [comment]
note: first added share was not password protected - the second was the same link with password protection

**Comment by DeepDiver1975** [comment]
tested :+1:

**Pull request merged**
