### PR TITLE
[stable10] check loglevel before interpolating message

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #31072 

This is an easy backport and seems like "a good thing", so I made the backport. Feel free to close if it is not to be backported.

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
approved - merging is upon @PVince81 since stable10 is in freeze for 10.0.8

**Comment by DeepDiver1975** [comment]
From my pov we can abandon this backport - the performance benefit is lost due to the event dispatcher

@butonic

**Comment by PVince81** [comment]
if Symfony provides a way to detect how many listeners are registered, the optimization could be kept if there is no listener at all. but then, increases code complexity

**Comment by phil-davis** [comment]
I resolved the latest conflicts. 

If somebody would like this for stable10, then merge it.

Otherwise close it.

**Comment by PVince81** [comment]
closed, thanks. we need to resolve https://github.com/owncloud/core/pull/31135 first before talking backports

**Pull request closed without merging**
