### PR TITLE
Change way how to show/hide tag edit actions

### LINKED ISSUE #39515: Renaming a tag shows another pencil icon, a second edit box opens
Seen with 10.9.0 beta1

* Click on the 3 dots of e.g. Photos, the sidebar opens, click tags.
* Enter one or two tags, e.g. blue, green
* Click on the white space next to the tag names, a tag editor opens:

image

* Click on the pencil icon to rename a tag. Its name becomes editable. OK

image

* The pencil and trashcan icon are shown next to the edit box. BAD.
* Click this pencil. A second edit box opens. (again with a pencil, more editors can be opened, as long as there is space). BAD.

image

Expected behaviour:
* When clicking on the pencil icon, the edit box opens and the pencil and trahscan icons disappear.
* no additional edit boxes can be opened. as. e.g. seen in 10.8.0:
image

This is a regression, found by @ChrisEdS

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes https://github.com/owncloud/core/issues/39515

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-5-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33793/174/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIFfSmoke-3-1-firefox-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33794/161/1

**Comment by JanAckermann** [comment]
Ok, this is not the approach we should choose...
The hidden class will not be deleted from some items, even if it should.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIPersonalSetting-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33795/134/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiWebdavOperations-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/94/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareManagementToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/64/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiComments-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/51/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCapabilities-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/50/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiWebdavLocks2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/89/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToShares3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/78/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToShares2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/61/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUILogin-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/130/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiVersions-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/85/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIProxySmoke-3-3-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/166/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIMobileSize-3-1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33796/167/1

**Review by JammingBen — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]
works for me

**Pull request merged**
