### PR TITLE
[Stable10] inttest adding trashbin scenarios

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Backport of https://github.com/owncloud/core/pull/28111
Edit: and backport of https://github.com/owncloud/core/pull/28196

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by SergioBertolinSG** [comment]
@PVince81 Requires backport of https://github.com/owncloud/core/pull/28196

**Comment by SergioBertolinSG** [comment]
Weird failure on jenkins:
```
auth.access files app with basic auth

When requesting "/index.php/apps/files" with "GET" using basic auth:

Server error response [url] http://localhost:8100/index.php/apps/files [status code] 500 [reason phrase] Internal Server Error
```

**Comment by PVince81** [comment]
@SergioBertolinSG can you rebase once just in case ? If the same error appears again we should dig deeper.

**Comment by PVince81** [comment]
the jenkins needs the boot

**Comment by PVince81** [comment]
```
19:50:10 --- Skipped scenarios:
19:50:10 
19:50:10     /var/lib/jenkins/workspace/owncloud-core_core_PR-28268-RS56ERDLELP5YGB6S6XY4BWH23KEIBTL6KWMLKOZ5SELCGDK3S5Q/tests/integration/features/auth.feature:10
```

**Comment by SergioBertolinSG** [comment]
Now it is needing https://github.com/owncloud/core/pull/28310 .

**Pull request merged**
