### PR TITLE
UI tests multiple browsers

### PR DESCRIPTION
**Pull request by individual-it**
## Description

This makes every UI test run in multiple browser.

**What tests are run now:**

- Chrome 48 on Linux, the newest Chrome that Saucelabs supports on Linux

- latest Chrome on Windows 10 (currently 57)

- latest-1 Chrome on Windows 10 (currently 56)

- oldest available Chrome (26) on Windows 10, as oC [claims to run on Chrome 18+ ](https://doc.owncloud.com/server/10.0/admin_manual/installation/system_requirements.html#web-browser)

- Firefox 47 on Windows 10 
webdriver for current Firefox is actually not ready, so we need to test on 47.0. see https://github.com/SeleniumHQ/selenium/issues/3693 & https://stackoverflow.com/questions/38746148/behat-mink-force-selenium-driver-to-use-chrome-instead-of-firefox#38764599

- oldest available Firefox (14) on Windows 10, as oC [claims to run on FF 14+ ](https://doc.owncloud.com/server/10.0/admin_manual/installation/system_requirements.html#web-browser)

- IE 11
IE has a problem with one test, getBoundingClientRect() throws an error. This is a known bug but I don't expect MS to fix it :-)
so I just skip this test for IE

Because the tests are run now multiple times it takes them much longer to pass. This time will increase again as we add UI tests.
to discuss

1. **what  browser/OS combinations do we want to run.**
e.g. do we really want to support ancient browsers like FF 14 or Chrome 26? Or should the [documentation](https://doc.owncloud.com/server/10.0/admin_manual/installation/system_requirements.html#web-browser) just be changed to support only the latest versions of browsers, versions on ESR and maybe latest-1
2. **do we want to run all UI tests on every PR?**
we could run only a part of the tests (limited by browser and/or test suits) on PRs and then run all tests on "master" or periodically. Then in case somebody thinks a special change should run all UI tests there can be a test-special branch that runs all tests.

_Side note: The first problem, and that took me a while to figure out, was the fact that the setting of env. variables does not work as expected in travis when separating them by a semicolon. They were somehow not correctly set. Need to separate them by a space (according to travis documentation)_

## Motivation and Context

Currently all UI tests are only run inside Chrome 48 on Linux, its better to test multiple browsers to catch bugs that only happen in a certain browser

## How Has This Been Tested?

It is the test  :-) http://www.commitstrip.com/en/2017/01/03/developer-bedtime-paradox/
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
tests are visible here: https://saucelabs.com/beta/builds/aaa2abaa35f84426adbe54c166035101

There seems to be an issue with the success state - can you please have a look? @individual-it THX

**Comment by individual-it** [comment]
from the saucelabs documentation:

> After you've run your tests, you may notice in your Sauce Labs dashboard that the test status is Complete, rather than Passed/Failed. This is because Selenium doesn't have a way to interpret test results, only whether the test ran to completion or not. You have a few ways to set the Pass/Fail status of your tests.

> You must use the the update_job method in the Sauce Labs REST API after the test has run.

I will check and implement it

**Comment by individual-it** [comment]
the status should now be reported to saucelabs and also travis will report a link to the saucelabs builds. So everybody can look at the video, screenshots etc.

But travis somehow doe not accept the job any-more. Any setting changed in the night?

**Comment by felixboehm** [comment]
1) make a reasonable choice
2) yes, on commits only a certain browser x suite should run. We will setup nightly builds and tests to cover a larger matrix.

- [ ] Please document: How to run the tests with only one, two or all browsers from commandline?

**Comment by individual-it** [comment]
wrote documentation and made a PR here: https://github.com/owncloud/documentation/pull/3049

**Comment by individual-it** [comment]
reduced the amount of browsers, left the browsers that I personally would test for every PR

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
> the status should now be reported to saucelabs and also travis will report a link to the saucelabs builds. So everybody can look at the video, screenshots etc.
> 
> But travis somehow doe not accept the job any-more. Any setting changed in the night?

this is not working - no idea why - the travis console shows no sign of the command being executed

bildschirmfoto von 2017-05-12 10-55-59

**Comment by individual-it** [comment]
working now
sc
you should be able to get the badges now

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2017-05-12 12-45-38

**Pull request merged**
