### PR TITLE
Properly reset the checksum if the file data has changed

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Properly reset the checksum if the file has changed

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/2561

## Motivation and Context
Checksum wasn't being reset in that scenario. The previous condition was wrong

## How Has This Been Tested?

Manually tested with the scenario described in the issue
- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
@jvillafanez would be good to add a unit test

at first look I have a hard time to understand what you actually changed, might explain the difference before vs after ?

**Comment by jvillafanez** [comment]
The code is fundamentally the same: if the size, storage_mtime, mtime or etag has changed, then reset the checksum. The new code is better because the old one used `array_intersect_key` and `in_array` while the new one just uses `isset`

The problem was that the `$data[$key] != $newData[$key]` condition wasn't working properly because the values where the same, so the checksum wasn't being reset.

**Comment by PVince81** [comment]
@jvillafanez will this change have other side effects ?

would be good to check and extend the unit tests to confirm this works correctly

**Comment by jvillafanez** [comment]
There are still some unittests failing, but I'm not sure where the problem is. Updated code still works and makes sense, so there shouldn't be a problem with the changes but the checksum repair tests are failing. I'm not sure if there are some problems with the tests.

**Comment by IljaN** [comment]
@jvillafanez Try breaking the checksum intentionally and then repairing it via repair command to see if checksum repair works as expected. If this is the case we can debug the test to see what is going wrong

**Comment by jvillafanez** [comment]
I've modifed the data in the DB and it seems the command works.

If the checksum has been reset:
```
sudo -u www-data ./occ files:checksums:verify -vvv -r
.....
Skipping synctest.log => No Checksum
```
If not:
```
sudo -u www-data ./occ files:checksums:verify -vvv -r
....
Checking synctest.log => SHA1:73cbb1d69ba106bf6fe1d7ec1111111111111111 MD5:d451afb7ec8b2aaa1111111111111111 ADLER32:d2999111
Mismatch for synctest.log:
 Filecache:	SHA1:73cbb1d69ba106bf6fe1d7ec1111111111111111 MD5:d451afb7ec8b2aaa1111111111111111 ADLER32:d2999111
 Actual:	SHA1:73cbb1d69ba106bf6fe1d7ec5e3a8214d1f15f81 MD5:d451afb7ec8b2aaa14389bbbf7ce15c4 ADLER32:d2999e73
Repairing synctest.log
```

**Review by IljaN — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
I assume this requires backport ....

**Comment by DeepDiver1975** [comment]
> I assume this requires backport ....

looks like no needed - @jvillafanez please clarify - thx

**Comment by DeepDiver1975** [comment]
> stable10 is required - hence blue-ticket !

upon cherry-pick I get an empty commit ... so I assume this was merged with some other pr already ...

this is why I was asking for clarification.

**Comment by jvillafanez** [comment]
Backport was https://github.com/owncloud/core/pull/32284 (already merged)

**Comment by PVince81** [comment]
how to test this manually, is there a shortcut ?

Steps I tried:
1. Setup SFTP mount as "/sftp"
1. Create a file "/sftp/test.txt"
1. Download the file to generate a checksum
1. Check checksum in oc_filecache
1. Directly on the SFTP storage, do a `touch` with a date in the past
1. In web UI, refresh the folder again

Result: the mtime of the file changed in the web UI

On both v10.0.9 and v10.0.10RC1 the checksum gets cleared properly.

Are there any more subtle things to setup ? @jvillafanez

**Comment by jvillafanez** [comment]
Other than the steps in the original ticket I'm not sure if this can be easily reproduced. I think the key point is to have the same checksum with different etag and size over the same file in different moments.

**Pull request merged**
