### PR TITLE
Improve the UX for "not found" perma links

### LINKED ISSUE #24939: Bad UX with perma links
### Steps to reproduce
1. Share folder with user1
2. As user1 open the folder
3. As admin delete and recreate user1
4. As user1 refresh the page and login with the form

### Expected behaviour
Should see the files list

### Actual behaviour
Exception-like window with file not found:
> File not found
The specified document has not been found on the server.
You can click here to return to ownCloud.

The problem is, the file id does not exist anymore, I thought I broke my instance, until I realized the fileid in the URL. I think we should either go back to the file list silently or with a yellow banner.
But not stay on the exception page.

@PVince81

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #24939

@PVince81 @rullzer @alpsleonardo

### CODE REVIEW

**Comment by nickvergessen** [comment]
For better review try https://github.com/owncloud/core/pull/25001/files?w=1

**Comment by PVince81** [comment]
Tested, works :+1: 

I shivered a bit when I saw the hidden input approach but AFAIK there is no better way so far.

**Comment by alpsleonardo** [comment]
@nickvergessen, good job... I suppose I am not that familiar with the source code yet.

**Comment by nickvergessen** [comment]
> PHP Fatal error:  Call to undefined method OCA\Files\Tests\Controller\ViewControllerTest::expectException() in /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/apps/files/tests/Controller/ViewControllerTest.php on line 416

Older phpunit version will adjust the test.

**Comment by ChristophWurst** [comment]
nice :+1:

**Comment by PVince81** [comment]
Failed pgsql tests unrelated, already happening on master => merge

**Pull request merged**
