### PR TITLE
[WIP] Use stream wrapper that allows to seek HTTP files

### PR DESCRIPTION
**Pull request by lokeller**
We want to start pushing to client connecting to owncloud the content of files stored on a remote DAV server while we are still downloading 
it from the remote server without waiting to first fully download the file on the owncloud server. We cannot directly use fopen('http://...') because
we want to be able to seek the resource, instead we use the stream wrapper implemented here.

Some things on which feedback would be very useful: 
- is the wrapper implementing enough functions or some are missing?
- what is the best way to create unit tests for this code?

### CODE REVIEW

**Comment by PVince81** [comment]
@owncloud-bot ok to test

**Comment by PVince81** [comment]
@icewind1991 is this PR a good alternative to your older PR https://github.com/owncloud/core/pull/10620 ?

**Comment by icewind1991** [comment]
I would still prefer having a generic caching stream wrapper that takes an existing non-seekable stream and makes it seekable.

**Comment by PVince81** [comment]
Might be related https://github.com/owncloud/core/pull/18653

**Comment by lokeller** [comment]
Yes, the objective of my patch was the same as #18653 . The new implementation is clearly better because reuses code already in present. I'm retracting my pull request.

**Pull request closed without merging**
