### PR TITLE
ownCloud Theme 2017

### PR DESCRIPTION
**Pull request by lordelix**
## Description

Reposition Elements appearing in the top bar. Replace the left caret with a burger menu.

## Motivation and Context

Internal Requirement

## How Has This Been Tested?

Visual test done on the latest Versions of:
- Google Chrome
- Firefox
- MS Edge

## Screenshots:

ec_reworking_header

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
@felixheidecke I restarted the Travis job that failed - it got the error where it seems to forget it is logged in, and the page redirects to the login page in the middle of a test. It usually runs fine. The real reason for the problem needs to be found somehow - but not your problem!

**Comment by DeepDiver1975** [comment]
Please squash

**Comment by felixheidecke** [comment]
Don't know why this needs no review, but I would like to have someone reassure me that this doesn't f*** things up ;-)

**Comment by tomneedham** [comment]
tested on safari 10.1.1 👍

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
- [ ]  no X in the login screen
- [ ] backgroud  image on login needs love - see https://central.owncloud.org/t/new-background-image-your-call/7927/18?u=deepdiver1975
- [ ]  apps in public link share is 💩 
bildschirmfoto von 2017-07-03 22-01-53

**Comment by PVince81** [comment]
@felixheidecke any update ?

**Comment by felixheidecke** [comment]
Sorry for the mess. I will clean that up in a fresh PR if all is good to go.

**Comment by felixheidecke** [comment]
Replaced by https://github.com/owncloud/core/pull/28424

**Pull request closed without merging**
