### PR TITLE
Adding Cross-Origin Resource Sharing to CORS

### PR DESCRIPTION
**Pull request by mmattel**
## Description

In Settings:Personal:Security: Adding the text ``Cross-Origin Resource Sharing`` next to ``CORS``

## Related Issue

none

## Motivation and Context

Making it more clear what CORS means

## How Has This Been Tested?

Opera and Firefox

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Beautyfying

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mmattel** [comment]
Codecov complains about:
https://codecov.io/gh/owncloud/core/compare/61b93be45043971725a7be71144776f4f9fac62c...5d8b3cf985c63fe98ce53623f669b241e9f5c697/src/lib/private/Files/Cache/Propagator.php#L135
which I do not even touch ??

**Review by PVince81 — APPROVED** [review]
:+1: thanks

**Comment by mmattel** [comment]
backporting?

**Comment by mmattel** [comment]
btw, I added in the PR the item ``- [ ] Beautyfying``
Mabe an idea to add this in general ? 😄

**Comment by PVince81** [comment]
beautifying is an enhancement. maybe we should rename "new feature" to enhancement

Codecov is ill and seems to see ghost changes... that propagator line wasn't touched since May 2016... ignore

**Comment by PVince81** [comment]
backport is ok

**Comment by PVince81** [comment]
fix for codecov failure that was related to a time element (basically how fast the tests run): https://github.com/owncloud/core/pull/30664

**Comment by phil-davis** [comment]
Backport ``stable10`` #30663

**Pull request merged**
