### PR TITLE
make sure that there is a space between user- and admin-documentation

### PR DESCRIPTION
**Pull request by schiessle**
make sure that there is a space between user- and admin-documentation in the apps menu.

Before (no space between user and admin documentation, one continuous underline) :

After (with a space):

cc @jancborchardt

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1: always wondered where this comes from :stuck_out_tongue:

**Comment by jancborchardt** [comment]
Nice catch! Pushed another improvement, adding an arrow to indicate the external link. (Also fixed the quote style and capitalization.)

Please review @owncloud/designers

**Comment by nickvergessen** [comment]
> Also fixed the ... capitalization.

now we can't backport it anymore to 8.1.1 because it breaks the translations?

**Comment by MorrisJobke** [comment]
@owncloud-bot Retest this please

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by jancborchardt** [comment]
> now we can't backport it anymore to 8.1.1 because it breaks the translations?

@nickvergessen then in the backport we need to adjust the word »Documentation« to be uppercase. In master it should be fixed like this though.

**Comment by schiesbn** [comment]
@karlitschek should we backport it. No critical bug but improves the visual impression and can't really break anything. I would suggest to backport only the first commit to solve the visual bug described above without breaking translations.

**Comment by jancborchardt** [comment]
Right, backporting only your commit sounds totally fine.

**Comment by karlitschek** [comment]
Sure. Please backport :-)

**Pull request merged**
