### PR TITLE
Grammar, removal of line break

### PR DESCRIPTION
**Pull request by cmeh**
- Corrected "… if the user forgets their password." to "… if the user forgets his or her password" in line 17.
- Removed line break from line 17 to line 18.

### CODE REVIEW

**Comment by bantu** [comment]
@owncloud-bot This is okay to test.

**Comment by bantu** [comment]
@owncloud-bot This is okay to test.

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by cmeh** [comment]
This contribution is MIT licensed (owncloud-bot didn't ask this time, but just in case… :grinning: ).

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
