### PR TITLE
Remove duplicated definition of APIController

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke @MorrisJobke @PVince81

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Something for 8.0

**Comment by nickvergessen** [comment]
Not really important (in terms of doesn't hurt)
The second definition just overwrites the first one.

**Comment by DeepDiver1975** [comment]
:+1: - 8.0 as it doesn't hurt

**Pull request merged**
