### PR TITLE
Check parent locks when creating node in DAV collection

### LINKED ISSUE #33848: Persistent lock on folder still allows to create files but not overwrite
### Steps

1. Two users "user1" and "user2"
1. Login as "user1"
1. Share a new folder "test" with "user2"
1. As user1 lock the folder "test": `curl -u user1:test -X LOCK http://localhost/owncloud/remote.php/webdav/test -d "<?xml version='1.0' encoding='UTF-8'?><d:lockinfo xmlns:d='DAV:'> <d:lockscope><d:shared/></d:lockscope></d:lockinfo>"`
1. Login as "user2"
1. Upload a file "test.txt" into the "test" folder
1. Overwrite file "test.txt" into the "test" folder by uploading again

### Expected result
Neither initial upload nor overwrite should be allowed.

### Actual result
Initial upload goes through but overwrite says "Locked".

### Version
Observed while testing https://github.com/owncloud/core/pull/32250, likely also present on master ac0f01b60f423a46464f3ee226b5c5190723feec

@DeepDiver1975 is this by design ?

### PR DESCRIPTION
**Pull request by PVince81**
## Description
When checking locks on a URI for a non-existing node, check for parent
locks instead of assuming no locks at all.

This makes it possible to prevent creation of new collection members in
case of a lock on the parent collections

## Related Issue
- Fixes https://github.com/owncloud/core/issues/33848 but only for depth: infinite

## How Has This Been Tested?
Manual test + unit test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
@individual-it can you check the failing test ? https://drone.owncloud.com/owncloud/core/14317/705

With this change of behavior, the upload should fail because of the lock.
From what I see the test is trying to find the row of the new file to check for its lock, but it shouldn't be created in the first place.

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by individual-it** [comment]
Fixed the expectations for the new file scenario. Now a moving file scenario fails

```
SCENARIO RESULT: (fail)
  Scenario Outline: moving a file into a locked folder                                                                  # /drone/src/tests/acceptance/features/webUIWebdavLocks/locks.feature:467
    Given the user "brand-new-user" has locked file "/simple-empty-folder" setting following properties                 # WebDavLockingContext::lockFileUsingWebDavAPI()
      | lockscope | <lockscope> |
    And the user has browsed to the files page                                                                          # WebUIFilesContext::theUserBrowsesToTheFilesPage()
    When the user moves file "lorem.txt" into folder "simple-empty-folder" using the webUI                              # WebUIFilesContext::theUserMovesFileFolderIntoFolderUsingTheWebUI()
    And as "brand-new-user" file "/simple-empty-folder/lorem.txt" should exist                                          # FeatureContext::asFileOrFolderShouldExist()
    And as "brand-new-user" file "lorem.txt" should not exist                                                           # FeatureContext::asFileOrFolderShouldNotExist()
    And file "lorem.txt" should not be listed on the webUI                                                              # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()
    And 1 locks should be reported for file "/simple-empty-folder/lorem.txt" of user "brand-new-user" by the WebDAV API # WebDavLockingContext::numberOfLockShouldBeReported()

    Examples:
      | lockscope |
      | shared    |
        file '/simple-empty-folder/lorem.txt' expected to exist but not found
        Failed asserting that false is true.
```

I guess a moved file is kind of a new file

**Comment by PVince81** [comment]
according to the RFC you can't move a file in our out of the collection, nor change their name (URI): https://tools.ietf.org/html/rfc4918#page-26

@individual-it ^

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/34203

**Pull request merged**
