### PR TITLE
Stable9 integration tests adding etag support

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Backport of #26370

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
@PVince81 the etag has changed, bug with fix not backported perhaps?

**Comment by PVince81** [comment]
Not sure if bug or if it's the tests:
```
03:05:32 --- Failed scenarios:
03:05:32 
03:05:32     /var/lib/jenkins/workspace/owncloud-core_core_PR-26703-PYXCKBDQAXGN54B7SOMMYS764SOBV5IRYHZRV6OQEAZUIWBEXOUA/build/integration/features/sharing-v1.feature:768
```

**Comment by PVince81** [comment]
Hmm, but with unshare from self the etag must change for the recipient who just unshared. Is that what the test does ?

**Comment by SergioBertolinSG** [comment]
The failing assertion is the last one 

And etag of element "/PARENT" of user "user0" has not changed                      # FeatureContext::checkIfETAGHasNotChanged()
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'"58369eabce844"'
      +'"58369eab293dd"'


This works this way in master and stable9.1.

**Comment by PVince81** [comment]
Ok, I'll investigate

**Comment by PVince81** [comment]
I tested this completely manually and it works fine, so let's verify if the etag check code works properly.

**Comment by PVince81** [comment]
There is a bug in the test.

When getting properties of "PARENT" to verify the etag it actually reads the etag from the root of user0 instead. I suspect that somewhere in `asGetPropertiesForPath` it doesn't use the given `$path`.

@SergioBertolinSG can you have a look ? Maybe another missing piece ?

**Comment by PVince81** [comment]
I know there's a bug in the test because while I had the breakpoint stopped there, I checked the etag with cadaver for PARENT and it was unchanged. I noticed that when I query the etag for "/" with cadaver it's the same as the one from the response here.

**Comment by PVince81** [comment]
Please merge this PR into https://github.com/owncloud/core/pull/26666 and let's focus on fixing the issues there instead, to save some time.

**Comment by SergioBertolinSG** [comment]
Merged into https://github.com/owncloud/core/pull/26666

**Pull request closed without merging**
