### PR TITLE
Update composer.lock for updated libs

### PR DESCRIPTION
**Pull request by PVince81**
To fix the warning that composer.lock is not up to date.

This PR updates composer.lock through `make update-composer`.

@DeepDiver1975 @PhilippSchaffrath please double check to be sure this update is correct.

### CODE REVIEW

**Comment by PhilippSchaffrath** [comment]
That's exactly what i expected. I had the same strange errors in the tests when i updated the dependencies last time. Good to have a separate ticket for that now :)

    1) Test\App\ManagerTest::testEnableApp
    ParseError: syntax error, unexpected '??' (T_COALESCE), expecting variable (T_VARIABLE)
    ...

I have no clue what is going on there!

**Comment by PVince81** [comment]
Doesn't happen for me locally with PHP 5.6.27.

**Comment by PVince81** [comment]
Sometimes Jenkins is sick... pushing a separate branch to verify: https://github.com/owncloud/core/pull/26479

**Comment by PhilippSchaffrath** [comment]
Same happened again, just like when i pushed a composer update.

**Comment by PVince81** [comment]
runtime:  PHP 7.1.0RC1

let's try that locally...

**Comment by PVince81** [comment]
Ok, locally I also get this with 7.1.0RC1 (from phpenv):
```
1) Test\App\ManagerTest::testEnableApp
ParseError: syntax error, unexpected '??' (T_COALESCE), expecting variable (T_VARIABLE)
```

Let's try again with 7.1.0RC4.

**Comment by PVince81** [comment]
No such weird issues with 7.1.0RC4.

@DeepDiver1975 can we update Jenkins from 7.1.0RC1 to 7.1.0RC4 ?

**Comment by PhilippSchaffrath** [comment]
No such issues with 7.0.8 too.

**Comment by DeepDiver1975** [comment]
7.1RC4 is now available on jenkins ...

**Comment by DeepDiver1975** [comment]
aha - much better with 7.1RC4

````
0:23:26 Time: 1.42 minutes, Memory: 172.00MB
00:23:26 
00:23:26 There were 4 failures:
00:23:26 
00:23:26 1) Test\Comments\ManagerTest::testGetComment
00:23:26 Failed asserting that two DateTime objects are equal.
00:23:26 --- Expected
00:23:26 +++ Actual
00:23:26 @@ @@
00:23:26  2016-10-25T22:22:04+0000
00:23:26 
00:23:26 /var/lib/jenkins/workspace/owncloud-core_core_PR-26476-MNN7CDVM5JONKOMQNADXUNNP62OTCAGAR5OFYESKH4STOA3OS3EQ/tests/lib/Comments/ManagerTest.php:110
00:23:26 
00:23:26 2) Test\Comments\ManagerTest::testSaveNew
00:23:26 Failed asserting that two DateTime objects are equal.
00:23:26 --- Expected
00:23:26 +++ Actual
00:23:26 @@ @@
00:23:26  2016-10-25T22:22:04+0000
00:23:26 
00:23:26 /var/lib/jenkins/workspace/owncloud-core_core_PR-26476-MNN7CDVM5JONKOMQNADXUNNP62OTCAGAR5OFYESKH4STOA3OS3EQ/tests/lib/Comments/ManagerTest.php:372
00:23:26 
00:23:26 3) Test\Comments\ManagerTest::testSetMarkRead
00:23:26 Failed asserting that two DateTime objects are equal.
00:23:26 --- Expected
00:23:26 +++ Actual
00:23:26 @@ @@
00:23:26  2016-10-25T22:22:04+0000
00:23:26 
00:23:26 /var/lib/jenkins/workspace/owncloud-core_core_PR-26476-MNN7CDVM5JONKOMQNADXUNNP62OTCAGAR5OFYESKH4STOA3OS3EQ/tests/lib/Comments/ManagerTest.php:576
00:23:26 
00:23:26 4) Test\Share20\DefaultShareProviderTest::testCreateLinkShare
00:23:26 Failed asserting that two DateTime objects are equal.
00:23:26 --- Expected
00:23:26 +++ Actual
00:23:26 @@ @@
00:23:26  2016-10-25T22:22:22+0000
00:23:26 
00:23:26 /var/lib/jenkins/workspace/owncloud-core_core_PR-26476-MNN7CDVM5JONKOMQNADXUNNP62OTCAGAR5OFYESKH4STOA3OS3EQ/tests/lib/Share20/DefaultShareProviderTest.php:747
00:23:26 
00:23:26 --

**Comment by DeepDiver1975** [comment]
Failed auch auf master

**Comment by PVince81** [comment]
Let's merge this PR then and address the issues in a separate one since they aren't related to composer.lock ? @DeepDiver1975

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/26488 to fix test failures for 7.1.0RC4

**Comment by PVince81** [comment]
Fix for the failures on master is here: https://github.com/owncloud/core/pull/26502

**Comment by butonic** [comment]
👍

**Comment by PVince81** [comment]
rebased

**Pull request merged**
