### PR TITLE
[stable8.2] Bring back delete permission in share overview

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/20160 to stable8.2
- [x] approval pending https://github.com/owncloud/core/pull/20160#issuecomment-164394399

Please review @MorrisJobke @rullzer @nickvergessen @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by SergioBertolinSG** [comment]
Works fine :+1:

**Comment by SergioBertolinSG** [comment]
But why there is an unshare option in shared with me screen?

This option is missing in master. And https://github.com/owncloud/core/pull/20160 is already merged.

screen shot 2015-12-14 at 12 49 07

**Comment by PVince81** [comment]
@SergioBertolinSG "Unshare" means "Unshare from myself" or "I'm not interested in this share any more". The action does not delete the folder but just removes you from the recipient list.

**Comment by rullzer** [comment]
:+1:

**Comment by SergioBertolinSG** [comment]
@PVince81 Sure. So this should appear in master as well.

**Comment by PVince81** [comment]
@SergioBertolinSG it will appear properly in master with https://github.com/owncloud/core/pull/21181 (different fix because of the move to Webdav)

**Pull request merged**
