### PR TITLE
[stable10] Backport of Log exceptions from exceptionHandler method

### PR DESCRIPTION
**Pull request by sharidas**
## Description

Log the exceptions thrown by occ command and also echo the exceptions into the console. This solves the problem when the command is executed as cron job and due to some reason if exception happens in the command, the data is logged in to the owncloud logger. So its helpful for the admin to look for the exception due to which the command was exited. Also we set the `catchExceptions` of symfony's console application to `false`. This helps to catch the exception in owncloud's console.php. 

## Related Issue

- Fixes <issue_link>

## Motivation and Context

Log the exception which is caused by the occ commands.

## How Has This Been Tested?

- The test at https://github.com/owncloud/core/pull/35362#issuecomment-500849944 applies here too.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by sharidas** [comment]
Original PR: https://github.com/owncloud/core/pull/35362

**Review by micbar — APPROVED** [review]

**Comment by micbar** [comment]
@sharidas @phil-davis 
We need to revert this. It does not meet the expected behaviuor.

Expected behaviour was: Don't change the occ error messages, but log exception in owncloud.log

This doesn't seem possible.

@phil-davis Do we need to consider something related to tests?

**Comment by phil-davis** [comment]
From what I see, the command-line behaviour change that is "strange" is that the error messages come in `stdout`  rather than `stderr`. For a real person who is just typing commands and looking at the output, there is not really a difference. But if people have scripts that do `occ` commands and parse `stderr` for error message text, then this will break a script like that.

So it would be nice if we could get the `stderr` output back.

**Comment by sharidas** [comment]
@phil-davis I have created revert PR https://github.com/owncloud/core/pull/35873. This should bring back the change which you have mentioned at https://github.com/owncloud/core/pull/35543#issuecomment-512689624

**Comment by phil-davis** [comment]
> @phil-davis I have created revert PR #35873. This should bring back the change which you have mentioned at [#35543 (comment)](https://github.com/owncloud/core/pull/35543#issuecomment-512689624)

That is the easy way to get back to the old behaviour. But is there a way to get that old `stderr`  behaviour and also get the exception logging of this PR?

**Comment by sharidas** [comment]
> That is the easy way to get back to the old behaviour. But is there a way to get that old `stderr` behaviour and also get the exception logging of this PR?

I doubt we can acheive both. Because the old stderr exceptions are handled by symfony and then I couldn't find a way where symfony throws back the exception to oC.

**Comment by micbar** [comment]
@phil-davis We come to the conclusion, that the logging needs to be done in the Command Classes themselves.

**Pull request merged**
