### PR TITLE
[9.0] Call private cache methods only for `OC\Files\Cache\Cache`

### PR DESCRIPTION
**Pull request by d--j**
Backport of #23972 (Jenkins #24179)
Approval https://github.com/owncloud/core/pull/23972#issuecomment-213386258

@PVince81 @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
@d--j Jenkins PR is only needed if your PR comes from a separate repo, because CI has trouble with forks. However in the case of this backport PR you pushed to the owncloud repo, so CI should work :smile:

**Comment by PVince81** [comment]
Thanks for the backport!

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
Rebased to nudge CI

**Comment by PVince81** [comment]
Looks like the Jenkins PR passed already anyway. :+1:

**Comment by PVince81** [comment]
Had a quick test with sharing and encryption and propagation of size apparently still works.

**Pull request merged**
