### PR TITLE
[Stable7] Backport 12779 - Fixing english fallback for plural strings

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #12779

@DeepDiver1975 as discussed in #12327 
@MorrisJobke mind reviewing, you also reviewed the master PR back in december

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Didn't work. :-1:

I changed `"_%n file_::_%n files_"` in `apps/files/l10n/de.php` to `array("", "")` and it simply doesn't show anything in the web UI. (files app footer)

**Comment by nickvergessen** [comment]
@MorrisJobke this comes with unit tests, showing it does work.
Mind elaborating your "testing"?

**Comment by MorrisJobke** [comment]
My patch: https://gist.github.com/MorrisJobke/ba791877babdf11eb456

What it looks like:
bildschirmfoto von 2015-02-17 19 25 06

**Comment by nickvergessen** [comment]
Hmm, I think that's JS :/

You can try the activity app by uploading multiple (5+) files and then delete the translations for "%n more"

I will have a look tomorrow, whether the JS fix is missing from master aswell

**Comment by nickvergessen** [comment]
Okay, my patch is working and can be tested as follows:

In the activity app `template/activity.box.php` find (this is required, because the markup uses `"` which seems to break translating in general, looking into that):
```php
<?php print_unescaped($_['event']['subjectformatted']['markup']['trimmed']) ?>
```
and replace with:
```php
<?php print_unescaped($_['event']['subjectformatted']['trimmed']) ?>
```

in the language file find
```php
"_%s and %n more_::_%s and %n more_" => array("%s und %n mehr","%s und %n weitere"),
```
and replace with
```php
"_%s and %n more_::_%s and %n more_" => array("",""),
```

With the patch the activity shows
`Du hast C.txt, A.txt, B.txt and 3 more erstellt`
without the patch it's
`Du hast  erstellt`

Fixing the same in JS (for the `%n files` you tried first) will be handled in a new issue/PR

**Pull request closed without merging**
