### PR TITLE
Welcome 2017 ....

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
It's 2017 .... for quite some time now .....

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
/me scared to click "File changes" to not crash Github.

Ok so you changed the year 👍

**Comment by DeepDiver1975** [comment]
> Ok so you changed the year :+1:

and the license headers got updated using our script

**Comment by PVince81** [comment]
Yeah, I had a peek by checking out the branch locally. Looks good.

**Comment by PVince81** [comment]
```
23:56:26 Waiting for MySQL(utf8mb4) initialisation ...
00:06:27 ........................................................................................................................................................................................................
00:06:27 [ERROR] Waited 600 seconds, no response
```

**Comment by DeepDiver1975** [comment]
reason for mysql not starting: ???

````
2017-02-13T14:11:09.512999Z 0 [Note] InnoDB: Buffer pool(s) load completed at 170213 14:11:09
2017-02-13T14:11:09.669148Z 0 [Note] Event Scheduler: Loaded 0 events
2017-02-13T14:11:09.669565Z 0 [Note] mysqld: ready for connections.
Version: '5.7.16'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2017-02-13T14:11:10.420373Z 2 [Warning] IP address '172.17.0.1' could not be resolved: Name or service not known
2017-02-13T14:12:11.426005Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 5697ms. The settings might not be optimal. (flushed=6 and evicted=0, during the time.)
2017-02-13T14:12:40.736555Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 11093ms. The settings might not be optimal. (flushed=24 and evicted=0, during the time.)
2017-02-13T14:13:12.896953Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 13157ms. The settings might not be optimal. (flushed=46 and evicted=0, during the time.)

**Pull request merged**
