### PR TITLE
Issue 20218 min max owncloud version warning

### LINKED ISSUE #20218: Enforce "min-version" and "max-version" for apps
From my PoV we should enforce a "min-version" and "min-version" for apps in their appinfo.xml. If they don't have one: Don't allow users to enable the app.

Way too many apps are somehow trying to inject stuff in other core code resulting in a famously broken ownCloud. That would help from my PoV.
(as long as developers don't set ownCloud 9999 as `max-version`…)

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #20218
1. Added warning in the UI
2. Added warning in the console check
3. Fixed the warning for shipped apps (in this repo)
4. Removed the deprecated shipped field from shipped apps.

For now it's a warning, app still passes the code-check and can be installed.
That is to be changed in ownCloud 11 as per the comments.
### occ app:check-code:

app-check-code
(minMax is replaced with either one, just took an old screenshot)
### app list

app-list

@LukasReschke @DeepDiver1975 @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
Is the shipped tag really deprecated? How does the logic work without this? 
This is fragile logic as we learned the hard way the last few year. So we have to be extra careful.

**Comment by nickvergessen** [comment]
> Is the shipped tag really deprecated? How does the logic work without this?
This is fragile logic as we learned the hard way the last few year. So we have to be extra careful. 

Yes, it's replaced by https://github.com/owncloud/core/commits/master/core/shipped.json which is in use since 8.1 already. The value in info.xml is not read anymore (apart from the check-code command, which then tells you that the value doesn't do anything)

**Comment by DeepDiver1975** [comment]
> Is the shipped tag really deprecated? How does the logic work without this?

The definition of shipped is defined by core (using the shipped.json) instead of giving the app the opportunity to define this by itself.

This change arose from the decision to remove calendar and contacts from the shipped apps.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

Code looks good

**Comment by karlitschek** [comment]
Ahh. My bad! I remember now. :+1:

**Comment by DeepDiver1975** [comment]
> This change arose from the decision to remove calendar and contacts from the shipped apps.

This was changed back in 8.1 - https://github.com/owncloud/core/pull/14862

**Pull request merged**
