### PR TITLE
Remove no longer needed repair step MoveAvatarOutsideHome

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
This repair step is broken on master because of https://github.com/owncloud/core/pull/31105

Assuming we no longer need this repair step - this PR kills it.
Otherwise we need to fix this.

## Motivation and Context
https://drone.owncloud.com/owncloud/update-testing/94/64
screenshot from 2018-07-27 09-26-24

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@PVince81 @tomneedham we need to make a decision on this.
1. remove the repair job
2. fix it (not that easy)
3. revert #31105

**Comment by PVince81** [comment]
according to my note in https://github.com/owncloud/core/issues/28902, this repair step would still be relevant if some setups are still on OC 8.2 and want to upgrade to OC 11 directly, thanks to our migrations system.

**Comment by DeepDiver1975** [comment]
preparing revert PR ....

**Comment by DeepDiver1975** [comment]
> preparing revert PR ....

https://github.com/owncloud/core/pull/32193

**Comment by tomneedham** [comment]
This affects pre-10 instances, using autoprovision backends

**Comment by DeepDiver1975** [comment]
no longer needed - I reverted the PR originally causing this issue

**Pull request closed without merging**
