### PR TITLE
Switching to Symfony DI container

### PR DESCRIPTION
**Pull request by phisch**
## Description

This is the **_wip**_ implementation of symfonys DI container.
## Motivation and Context

Currently we are using pimple for our dependency injection. This usually is fine for smaller projects but it can get clustered pretty quickly in enterprise projects. 

Modernizing the ServiceContainer would enable us to do the following:
- centralize service definitions and configuration values (parameters)
- inject configuration values into services
- be more productive during development due to features like autowiring
- override parameters and services through apps
- check for errors during compilation
- use tagged services and compiler passes

Besides it enabling us to do a lot more stuff, it also helps us getting rid of a lot of technical debt. I am looking at stuff like:
- business logic inside the service definitions
- heavy use of static objects or singletons
- static config class using config.php file inside services making it harder to write tests
## How Has This Been Tested?

Currently only tested manual since the container needs to be built in the untestable `lib/base.php`. I will try to extract the container initialization into another class to test it properly.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
What about the app framework ? From what I saw we have some logic there in core to do DI resolution. If we're able to get rid of this as well it would be cool because I don't see the point having that much custom stuff in core.

**Comment by PhilippSchaffrath** [comment]
@PVince81 what exactly do you mean? The capability of apps to register Services?
If so, that's not yet developed, it's one of the next steps. As far as i can see, that's quite complicated though, since you only want to load enabled apps definitions, and whenever an app gets enabled or disabled, the cached container has to be invalidated.

**Comment by jancborchardt** [comment]
cc @BernhardPosselt regarding Appframework :)

**Comment by BernhardPosselt** [comment]
I see no problem if there is no breakage. However note that a lot of your points like autowiring are already implemented in our custom subclass

**Comment by PhilippSchaffrath** [comment]
@BernhardPosselt that's to be expected. You can also extend pimple with all of those features, but why should we do that if there is already a well written and tested alternative that already provides solutions for all those problems and even more things we might make a good use of in the future?

Nothing against pimple, it's great, but it gets messy in larger scale projects like this.

**Comment by PVince81** [comment]
this is quite old. keep ?

**Comment by phisch** [comment]
Yes, i would like to keep it, maybe i will be able to sneak in some ninja weekend coding for this.

**Pull request closed without merging**
