### PR TITLE
Add unit test for migrator with different prefix

### PR DESCRIPTION
**Pull request by PVince81**
This is a unit test for https://github.com/owncloud/core/pull/14660 and can help reproduce the issue from https://github.com/owncloud/core/issues/14916

Please review @nickvergessen @oparoz @icewind1991 @MorrisJobke

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by MorrisJobke** [comment]
@PVince81 Can you have a look at the failing unit tests? Thanks

**Comment by PVince81** [comment]
I got the sqlite test failing locally, will look into it.

**Comment by PVince81** [comment]
Ok I think I understand what @VicDeo said: probably meant that there is no prefix for SQLite and adding one in the tests make it fail.

**Comment by PVince81** [comment]
I just tried setting up OC with SQLite, and I can see that there are prefixes on master.
Now I wonder why the unit test used to pass on master but not on this branch.

**Comment by PVince81** [comment]
*facepalm* I shouldn't have skipped :coffee: today: the prefix is missing in the unit test when creating `$this->tableName`

**Comment by PVince81** [comment]
Rebased + fixed unit test

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
