### PR TITLE
[stable10]  Rename user creation given step to be default

### PR DESCRIPTION
**Pull request by skshetry**
Backport for #33551

### CODE REVIEW

**Review by phil-davis — DISMISSED** [review]

**Review by individual-it — APPROVED** [review]
looks good to me, assuming CI passes one day

**Review by phil-davis — APPROVED** [review]

**Comment by skshetry** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
