### PR TITLE
fix accessibility of New button, use alt text instead of tooltip

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @davitol @owncloud/designers

### CODE REVIEW

**Comment by davitol** [comment]
:+1: Fixed

**Comment by PVince81** [comment]
@jancborchardt this removes the tooltip. Is this intended ?

**Comment by PVince81** [comment]
Right, the description says so, so assuming it's intended. :+1:

**Comment by jancborchardt** [comment]
Yup, removing the tooltip is intended. Not really needed since it’s a plus button, and pretty obvious when clicked once. (Tooltip doesn’t work on mobile anyway, so we shouldn’t go too much overboard with them. ;)

**Comment by PVince81** [comment]
Yeah, I don't think chinese people will mistaken it for the number 10 十 anyway :wink:

**Comment by jancborchardt** [comment]
LOL

**Pull request merged**
