### PR TITLE
[stable10] Exceptions need to properly be handled in the preview plugin

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Exceptions being thrown during preview generation need to properly translated into sabre dav exception

## Motivation and Context
No http status code 500 shall be returned

## How Has This Been Tested?
- add firewall app
- add rule which prevents a use from accessing a file
- call the preview url with curl
- 403 shall be returned - not 500

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Code looks fine. Can you add unit tests ?

Also see https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/File.php#L628 and https://github.com/owncloud/core/issues/17220

**Review by PVince81 — CHANGES_REQUESTED** [review]
please add unit tests, if possible

**Comment by phil-davis** [comment]
Forward port to ``master`` is PR #31749

**Comment by phil-davis** [comment]
Rebased here to get past files_primary_s3 PHP version issue with CI.

**Review by PVince81 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 please port to master.

already in https://github.com/owncloud/core/pull/31749 - unit tests adopted

**Comment by phil-davis** [comment]
Removed ``backport-request`` label, because commit has been added to forward-PR #31749 and has been merged.

**Pull request merged**
