### PR TITLE
Close the directory after reading

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Close the directory handler after reading the entries.

## Related Issue
Related to https://github.com/owncloud/windows_network_drive/pull/358

## Motivation and Context
This handler was being automatically freed once the request finished. The problem with this behaviour is that some resources that were attached to the custom directory stream wrapper weren't closed properly because those attached resources were missing at that time.
Some problems found were: missing class definition in the custom `dir_closedir` implementation (pretty random, probably due to how PHP was freeing the memory), and invalid native resource (of unknown type) for the underlying calls.

## How Has This Been Tested?
automatically tested with the WND app.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30850/129/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/30850/129/15
```
runsh: Total unexpected failed scenarios throughout the test run:
webUIComments/comments.feature:40
runsh: There were no unexpected success.
```
```
element click intercepted: Element <a class="action action-share permanent" href="#" data-action="Share" data-original-title="" title="">...</a> is not clickable at point (767, 165). Other element would receive the click: <a href="#">...</a>
```

This is a similar thing to issue #38908 - "something happened" about 30 hours ago to the webUI tests. The fails are all related to elements of sharing dialogs/panels that are sometimes being "obscured" somehow. I will followup the issue as a priority.

**Comment by jvillafanez** [comment]
I don't think we need a changelog item for this tiny change. There is no real open issue, and it's hard to explain without being too technical.

**Review by AlexAndBear — APPROVED** [review]

**Review by JammingBen — APPROVED** [review]

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIRestrictSharing-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30882/140/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/30882/140/15
```
runsh: Total unexpected failed scenarios throughout the test run:
webUIRestrictSharing/restrictSharing.feature:25
webUIRestrictSharing/restrictSharing.feature:34
```
I have also seen these fail sometimes. That's sad :(

I restarted CI. Hopefully tomorrow I can sort out what is really going on with these restrictSharing UI tests.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30883/149/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIFfSmoke-3-1-firefox-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30888/164/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIProxySmoke-3-1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30889/167/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-10.6.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30890/114/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingExt1-latest-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30890/159/1

**Comment by phil-davis** [comment]
There were annoying issues with CI late yesterday. This passes now. IMO this is "a good thing". Merge?

**Pull request merged**
