### PR TITLE
More secure proposal

### PR DESCRIPTION
**Pull request by pierrejochem**
fileglobalgc improvment

### CODE REVIEW

**Comment by pierrejochem** [comment]
This contribution is MIT licensed!

**Comment by nickvergessen** [comment]
@owncloud-bot its okay to test this

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
cc @icewind1991 @DeepDiver1975 8.1?

**Comment by icewind1991** [comment]
Fine by me :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
