### PR TITLE
don't throw exception if a file gets uploaded and encryption is disabled

### PR DESCRIPTION
**Pull request by schiessle**
don't write error messages that the encryption module couldn't be found if encryption is disabled and the user uploads a file.

cc @nickvergessen @th3fallen @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by nickvergessen** [comment]
Stops the log-spam here
But don't have time to look at the code atm.

**Comment by nickvergessen** [comment]
:+1: code looks good

**Comment by PVince81** [comment]
Makes sense :+1:

**Pull request merged**
