### PR TITLE
Added test case about downloading by range a public shared file

### PR DESCRIPTION
**Pull request by SergioBertolinSG**

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
cc @PVince81

**Comment by MorrisJobke** [comment]
I fixed the indentation. Beside that this looks good :+1:

**Comment by PVince81** [comment]
Looks good.

Do we have test for sub-files ? Currently you're downloading "public.php/webdav" directly. Would be good to have cases that check that for folder shares we also have "public.php/webdav/path/to/file.txt" work.

**Comment by PVince81** [comment]
We can merge this first :+1:

**Comment by SergioBertolinSG** [comment]
> Do we have test for sub-files ? Currently you're downloading "public.php/webdav" directly. Would be good to have cases that check that for folder shares we also have "public.php/webdav/path/to/file.txt" work.

Not yet. The case is to share publicly a folder and later download a file inside it with range, isn't?

**Comment by PVince81** [comment]
Yes

**Pull request merged**
