### PR TITLE
[Stable-10] Send requests in loop rather than scenario outline to speed up CI

### PR DESCRIPTION
**Pull request by bhawanaprasain**
Backport on: #35395

## Description
These tests speedup CI .

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests only (no source changes)

### CODE REVIEW

**Comment by phil-davis** [comment]
@bhawanaprasain there are more lines deleted from ` tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature` than happened in core `master`

I think this feature had some differences in `stable10`

Can you explain what happened?

**Comment by bhawanaprasain** [comment]
@phil-davis I have found no differences in this backport and PR  #35395 .

**Comment by individual-it** [comment]
the problem is in https://github.com/owncloud/core/pull/34645 :see_no_evil:

**Comment by individual-it** [comment]
should be fine after #35548 maybe a rebase will be needed

**Comment by phil-davis** [comment]
@bhawanaprasain please rebase and resolve the conflict. (or make a new backport branch and PR)
This should work better now that #35548 has been merged to `stable10`

**Pull request closed without merging**
