### PR TITLE
Add acceptance test flags in makefile for autocompletion

### PR DESCRIPTION
**Pull request by skshetry**
## Description

This PR adds flag to the makefile, so that, if your terminal support this (`zsh`, maybe `fish` as well), you'll get autocompletion for makefile env variables. Sadly, `bash-completions` does not support variable autocompletion.

## Motivation and Context

Just felt like it would help.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
Please mention the shells that you know will work for this.
It will help other people to understand if they have any hope to use it.

**Comment by skshetry** [comment]
@phil-davis, this currently only supports `zsh` (maybe, `fish`), but not the bash. So, if you think it would not help many, we could close this. Or else, we could merge this. :grinning:

**Comment by phil-davis** [comment]
Works for me with `zsh`. It will be useful for anyone that happens to use a shell with this support.

**Review by phil-davis — DISMISSED** [review]

**Comment by phil-davis** [comment]
It broke CI. Maybe it sees `BEHAT_FEATURE` as an empty string?
And so nothing runs.

**Review by phil-davis — APPROVED** [review]

**Comment by skshetry** [comment]
Backport for `stable10` on #35383

**Pull request merged**
