### PR TITLE
Exclude owncloud-news-gitter-bot from mention bot

### PR DESCRIPTION
**Pull request by ghost**
As seen in e.g. https://github.com/owncloud/documentation/pull/2507

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
but you need to put it into the documentation repo as well afaik

**Comment by DeepDiver1975** [comment]
WhoFT is @owncloud-news-gitter-bot anyhow?

**Comment by DeepDiver1975** [comment]
> WhoFT is @owncloud-news-gitter-bot anyhow?

Ah @BernhardPosselt 's old account? https://github.com/owncloud/documentation/commit/ffc402768497a19b02c26fe59555aa8fcf859708.patch

**Comment by BernhardPosselt** [comment]
Yeah, thats only for communicating from gitter to IRC and vice versa ;)

**Comment by DeepDiver1975** [comment]
> Yeah, thats only for communicating from gitter to IRC and vice versa ;)

any holds all your commits related to your gmail address - see the linked commit

**Comment by RealRancor** [comment]
Ahhh, thought this is a global config. Currently there is no ``.mention-bot`` in https://github.com/owncloud/documentation/

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
