### PR TITLE
scroll window if element not visible

### LINKED ISSUE #18830: Action menu in Files is unreachable when at the bottom of the screen
### Steps to reproduce
1. Open a folder containing more images that the viewport
2. Click on the action menu of the last item
### Expected result

Interface scrolls up and menu items are reachable
### Actual result

Menu items are not reachable

@jancborchardt @PVince81

### PR DESCRIPTION
**Pull request by individual-it**
## Description
When element not completely in view the window get scrolled to show the corresponding element completely
This should fix #18830
It uses the fix made by @oparoz for #15817

## Related Issue

#18830

## Motivation and Context

see discussion in #18830

## How Has This Been Tested?

so far only manual tested (FF & Chrome)

If the change is generally approved I would write some UI tests for it

## Screenshots (if appropriate):
action_menu_scroll

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
````
Feature: login

  Scenario: simple login                                     # /home/travis/build/owncloud/core/tests/ui/features/login.feature:3

    Given I am on login page                                 # LoginContext::iAmOnLoginPage()

PHP Fatal error:  Call to a member function getAttribute() on null in /home/travis/build/owncloud/core/tests/ui/features/lib/OwncloudPage.php on line 77

PHP Stack trace:

PHP   1. {main}() /home/travis/build/owncloud/core/lib/composer/behat/behat/bin/behat:0

PHP   2. Symfony\Component\Console\Application->run() /home/travis/build/owncloud/core/lib/composer/behat/behat/bin/behat:34

PHP   3. Behat\Testwork\Cli\Application->doRun() /home/travis/build/owncloud/core/lib/composer/symfony/console/Application.php:120

PHP   4. Symfony\Component\Console\Application->doRun() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Cli/Application.php:124

PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/travis/build/owncloud/core/lib/composer/symfony/console/Application.php:189

PHP   6. Symfony\Component\Console\Command\Command->run() /home/travis/build/owncloud/core/lib/composer/symfony/console/Application.php:826

PHP   7. Behat\Testwork\Cli\Command->execute() /home/travis/build/owncloud/core/lib/composer/symfony/console/Command/Command.php:262

PHP   8. Behat\Testwork\Tester\Cli\ExerciseController->execute() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Cli/Command.php:63

PHP   9. Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:108

PHP  10. Behat\Testwork\Ordering\OrderedExercise->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:149

PHP  11. Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php:80

PHP  12. Behat\Testwork\Tester\Runtime\RuntimeExercise->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php:70

PHP  13. Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php:71

PHP  14. Behat\Testwork\Hook\Tester\HookableSuiteTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php:72

PHP  15. Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php:73

PHP  16. Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php:63

PHP  17. Behat\Behat\Hook\Tester\HookableFeatureTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php:71

PHP  18. Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php:72

PHP  19. Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php:84

PHP  20. Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php:69

PHP  21. Behat\Behat\Hook\Tester\HookableScenarioTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php:103

PHP  22. Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php:74

PHP  23. Behat\Behat\Tester\StepContainerTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php:76

PHP  24. Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php:59

PHP  25. Behat\Behat\EventDispatcher\Tester\TickingStepTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php:73

PHP  26. Behat\Behat\Hook\Tester\HookableStepTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/EventDispatcher/Tester/TickingStepTester.php:59

PHP  27. Behat\Behat\Tester\Runtime\RuntimeStepTester->test() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php:74

PHP  28. Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php:73

PHP  29. Behat\Testwork\Call\CallCenter->makeCall() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php:125

PHP  30. Behat\Testwork\Call\CallCenter->handleCall() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Call/CallCenter.php:96

PHP  31. Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Call/CallCenter.php:140

PHP  32. Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:59

PHP  33. call_user_func_array:{/home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:103}() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:103

PHP  34. LoginContext->iLoginWithUsernameAndPassword() /home/travis/build/owncloud/core/lib/composer/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:103

PHP  35. ProxyManagerGeneratedProxy\__PM__\Page\LoginPage\Generatedb755cbf3bea1a48cfcd917422d91a2e8->waitTillPageIsloaded() /home/travis/build/owncloud/core/tests/ui/features/bootstrap/LoginContext.php:56

PHP  36. Page\OwncloudPage->waitTillPageIsloaded() /tmp/ProxyManagerGeneratedProxy__PM__PageLoginPageGeneratedb755cbf3bea1a48cfcd917422d91a2e8.php:44

PHP  37. Page\OwncloudPage->elementHasCSSValue() /home/travis/build/owncloud/core/tests/ui/features/lib/OwncloudPage.php:38

**Comment by individual-it** [comment]
SauceLabs uses [Chrome 48 on Linux](https://saucelabs.com/platform) and that one seems not to like default parameter in function definitions.
Locally I've tested with Chrome 54 and that did work fine.
That's where cross browser tests would be handy.

**Comment by DeepDiver1975** [comment]
Well we can  add more webdrivers - right?

Let me know if you need anything

**Comment by individual-it** [comment]
@DeepDiver1975 I just wrote you a longer mail to your public github email address

**Comment by PVince81** [comment]
Tested manually, works well even in IE11 ! 👍

**Pull request merged**
