### PR TITLE
Revert "Close cursor early in calculateFolderSize" for now

### LINKED ISSUE #13788: [stable7] oracle unit test failing
https://github.com/owncloud/core/pull/13752
https://github.com/owncloud/core/pull/13772

### PR DESCRIPTION
**Pull request by nickvergessen**
This reverts commit 234f33e01e630f763f34c51114d25986bae02b42.

Fix #13788

@PVince81 @DeepDiver1975 @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
Should we rather add an exception for Oracle here ? Or close the cursor only for SQLite ?
If we revert this parallel upload will not work on OC 7.

**Comment by MorrisJobke** [comment]
Can somebody with oracle please retest stable7 because https://github.com/owncloud/core/pull/13798 is now merged and maybe has the fix in doctrine.

**Comment by nickvergessen** [comment]
@MorrisJobke wtf, the linked PR does not touch doctrine in anyway!

**Comment by nickvergessen** [comment]
> Should we rather add an exception for Oracle here ? Or close the cursor only for SQLite ?
If we revert this parallel upload will not work on OC 7.

thought the same, but was not sure which one is better. But at least unbreaking it is better atm. We can still refix this later.
Also the second PR you made yesterday was not backported, so this needs to be reinvestigated anyway

**Comment by MorrisJobke** [comment]
-.- sorry ... mixed up doctrine with sabre dav ... forget everything I said ...

**Comment by MorrisJobke** [comment]
:+1:

**Comment by PVince81** [comment]
Ok then, let's resubmit with an Oracle-compatible fix. :+1:

**Comment by nickvergessen** [comment]
@DeepDiver1975 please run oracle and verify :)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 please run oracle and verify :)

on it ....

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
@guruz FYI

**Pull request merged**
