### PR TITLE
[Stable9.1]  Check that the most recent app version is loaded

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
Backport of https://github.com/owncloud/core/pull/28002 ~and https://github.com/owncloud/core/pull/28221~

## How Has This Been Tested?
Testcase details https://github.com/owncloud/core/pull/27989#issuecomment-304685800

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Weird failure, probably unrelated. Please rebase for Jenkins.

👍 assuming this was retested

**Comment by VicDeo** [comment]
Rebased

**Comment by PVince81** [comment]
:cry: what 

```
11:17:13                                                                        
11:17:13   [Behat\Behat\Context\Exception\ContextNotFoundException]             
11:17:13   `AppManagementContext` context class not found and can not be used. 
```

on stable9.1 ??

**Comment by PVince81** [comment]
@VicDeo ah... you might need to backport more stuff to make the tests work on stable9.1...

cc @SergioBertolinSG

**Comment by SergioBertolinSG** [comment]
The recommendation by @felixboehm is to focus on tests for master. 
So I recommend only backport to stable10.

**Comment by VicDeo** [comment]
oops. I missed that stable9.1 has no integration tests.
Integration tests are stripped, retested manually.

**Comment by SergioBertolinSG** [comment]
Well it has most tests, but located in build/integration and we didn't backport everything from 10.

**Comment by VicDeo** [comment]
@PVince81 @SergioBertolinSG tests were removed. The build is passed.

**Comment by PVince81** [comment]
the PR is merged

**Pull request merged**
