### PR TITLE
LDAP: reset paged search on null limit [stable7]

### PR DESCRIPTION
**Pull request by blizzz**
Fixes an issues found in https://github.com/owncloud/core/issues/13533#issuecomment-76092306 ff

OC 7 version

Thing is, the issue is hard to reproduce. I wrote a test script, but was never able to reproduce the issue on my system against AD 2008 nor 2012.  On the system of the ticket however, it was reproducible, the test worked and the fix also.

I don't expect side effects.

### CODE REVIEW

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by blizzz** [comment]
@sbelov1 tested it on his system successfully (https://github.com/owncloud/core/issues/13533#issuecomment-77398860), I take it as :+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by sbelov1** [comment]
@blizzz So, it looks like the issue stands in 8.0.1/8.0.2. I've just upgraded and experiencing the same issue. Applying the patch to v8 doesn't seem to work either. It wouldn't render an ownCloud page - looks to be a compatibility issue. Can we please update the patch for v8? Hopefully we can backport this 8.0.2/8.0.3 at some point.

**Comment by blizzz** [comment]
@sbelov1: stable8 version is here: https://github.com/owncloud/core/pull/14751 Not merged yet, needs a tester.

**Comment by sbelov1** [comment]
@blizzz Perfect. This one worked! ;)

**Pull request merged**
