### PR TITLE
Add CalDAVTester to travis

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@evert Apple's CalDAVTester seems to expect a user under principals/users/user01/
see https://travis-ci.org/owncloud/core/jobs/88461175#L342

We list all users directly under principals.

Is this sub collection 'users' part of some specification? I did not find anything. THX

**Comment by evert** [comment]
It's not a standard, but their testing tool has a lot of expectations around what a server should look like. Most of this is configurable though.

**Comment by DeepDiver1975** [comment]
@evert any idea on how to model this properly? I played around with the order of plugins being added - but this doesn't really work out. :cry:

**Comment by evert** [comment]
I once made a start here:

https://github.com/evert/caldavtester

hese tests run (but still with a ton of failures). It will probably take a bunch more work to get it into a state where it will become useful, but doing this already caused a few bugs to surface (which I then fixed).

**Comment by evert** [comment]
I would suggest starting with an extremely small set of features. Get those to work and then slowly expand.

**Comment by DeepDiver1975** [comment]
> I would suggest starting with an extremely small set of features. Get those to work and then slowly expand.

I just started with current-user-principal test and I'm facing this issue where an unauthorized propfind to the root should behave different compared to the same request against the sub folder principals.

**Comment by evert** [comment]
Well at least it sounds like you have things running =)

I don't think I fully understand the issue you are seeing though. How should it be different?

**Comment by DeepDiver1975** [comment]
I'll explain later ... :beers: are calling :speak_no_evil:

**Comment by evert** [comment]
Have fun!

**Comment by DeepDiver1975** [comment]
@evert So ... this test https://github.com/DeepDiver1975/CalDAVTester/blob/master/scripts/tests/CardDAV/current-user-principal.xml#L57 send an unauthenticated propfind to the webdav root and the expectation is that a multistatus is returned containing the xml element unauthenticated.

Sending the same request to the principals collection a 401 is expected - https://github.com/DeepDiver1975/CalDAVTester/blob/master/scripts/tests/CardDAV/current-user-principal.xml#L126

I see no way to model this .... THX

**Comment by evert** [comment]
Ah interesting. Well we definitely don't support this. I would disable that that frankly. I don't think it's required

**Comment by DeepDiver1975** [comment]
First test suite active!

@blizzz @evert @icewind1991 @LukasReschke @PVince81

**Comment by blizzz** [comment]
More tests :+1:

**Pull request merged**
