### PR TITLE
Fix Share::getUsersSharingFile() for mount points

### LINKED ISSUE #15858: File and folder location is wrong at shared external folders
Originally reported at https://github.com/owncloud/activity/issues/284 by @tibmanus

> ### Steps to reproduce
1. Admin user mounts a local folder as an external storage. (Folder name: Localhhh)
2. Admin user creates a folder inside this folder (Folder name: external), then shares it with 'testuser'.
3. Testuser creates a file in this folder (Name: file1).
4. Testuser checks the Activity app: "You created file1"
>
> ### Expected behaviour
Tooltip and link shows the correct location for testuser: external/
>
> ### Actual behaviour
Tooltip and link for testuser goes to this location:   externalcalhhh/external
>
> ### Server configuration
**Operating system**:
Ubuntu 14.04
>
> **Web server:**
Apache2
>
> **Database:**
SQLite
>
> **ownCloud version:** (see ownCloud admin page)
8.02
>
> **Updated from an older ownCloud or fresh install:**
Happens both at fresh and updated version.
>
> **Are you using external storage, if yes which one:**
local
>
> **Are you using encryption:** 
no
>
> **Are you using an external user-backend, if yes which one:** 
no

[lib/private/share/share.php#L282-L288](https://github.com/owncloud/core/blob/1911472b88898868969bfbefa16e0e2e3168c146/lib/private/share/share.php#L282-L288)
```php
					while ($row = $result->fetchRow()) {
						foreach ($fileTargets[$row['fileid']] as $uid => $shareData) {
							$sharedPath = $shareData['file_target'];
							$sharedPath .= substr($path, strlen($row['path']) -5);
							$sharePaths[$uid] = $sharedPath;
						}
					}
```
This code generates broken paths. Instead of `$path` starting with `files/` it starts with the mount point name, so stripping should be until the next slash instead of hardcoded 5 characters?

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #15858 
### Steps
- Create a global mountpoint SFTP with `folder/text.txt` in it
- Create `/folder/subfolder/img.jpg`
- Share `/SFTP/folder` with test1
- Share `/folder/subfolder` with test1
- As test1 rename `folder` to `folder2`
- As test1 rename `subfolder` to `subfolder3`
### Testscript

``` php
<?php
include('master/core/lib/base.php');
$normal = \OC\Share\Share::getUsersSharingFile('/folder/subfolder/img.jpg', 'admin', true, true);
var_dump($normal);
$mount = \OC\Share\Share::getUsersSharingFile('/SFTP/folder/test.txt', 'admin', true, true);
var_dump($mount);
```
### Expected

```
array (size=2)
  'test1' => string '/subfolder3/img.jpg' (length=19)
  'admin' => string '/folder/subfolder/img.jpg' (length=25)

array (size=2)
  'test1' => string '/folder2/test.txt' (length=17)
  'admin' => string '/SFTP/folder/test.txt' (length=21)
```
### Actual

```
array (size=2)
  'test1' => string '/subfolder3/img.jpg' (length=19)
  'admin' => string '/folder/subfolder/img.jpg' (length=25)

array (size=2)
  'test1' => string '/folder2SFTP/folder/test.txt' (length=28)
  'admin' => string '/SFTP/folder/test.txt' (length=21)
```

@schiesbn

### CODE REVIEW

**Comment by nickvergessen** [comment]
Will try to write a unit test for this.

**Comment by PVince81** [comment]
Any update ? How are the unit tests going ? :smile:

**Comment by nickvergessen** [comment]
Well everything I came up with just shows that it either works for shares or for external storages.
As per issue this will have to wait for the mounts table

**Comment by MorrisJobke** [comment]
@icewind1991 Could we get your feedback on this?

**Comment by nickvergessen** [comment]
I rebased and it works now, so seems like the ground work with the mount stuff solved this.

Please review @schiesbn @PVince81 @icewind1991 @MorrisJobke @rullzer

**Comment by nickvergessen** [comment]
Posted a testplan for QA https://github.com/owncloud/QA/issues/195

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by nickvergessen** [comment]
Second review @schiesbn @PVince81 @icewind1991 @rullzer

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Rebased to trigger CI

**Comment by MorrisJobke** [comment]
@nickvergessen Even a signed commit ;)

**Pull request merged**
