### PR TITLE
Setting oci as supported database

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@LukasReschke @MorrisJobke this fixes broken ci on master

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Sure we want to add OCI support for CE and SQLite for EE if the install command is used? Why not add these options to a `config/jenkins.config.php` ;)

**Comment by DeepDiver1975** [comment]
> Sure we want to add OCI support for CE and SQLite for EE if the install command is used? Why not add these options to a config/jenkins.config.php ;)

hmmm - honestly - who uses the cli tools ShouldTF know what he is doing. I don't wan to add another magic file - I'm honestly happy that we got rid of the autoconfig-kung-fu in autotest.sh

**Comment by nickvergessen** [comment]
Wouldn't it be better to ignore the check completly on CLI, instead of writing stuff to the config file :see_no_evil:

**Comment by LukasReschke** [comment]
Acceptable from my PoV :+1:

**Comment by DeepDiver1975** [comment]
> Wouldn't it be better to ignore the check completly on CLI, instead of writing stuff to the config file :see_no_evil:

hmm - true - let me see ....

**Comment by MorrisJobke** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
