### PR TITLE
Added a blank to display names of shared objects

### PR DESCRIPTION
**Pull request by Julian1998**
## Description

Added a blank to display names of shared objects

## Related Issue

https://github.com/owncloud/calendar/issues/905

## Motivation and Context

Have Calendar (user) instead of Calendar(user)
A blank is looking more beautiful ;)

## How Has This Been Tested?

Manually and unit test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Julian1998** [comment]
@DeepDiver1975 Can you please restart drone somehow

**Comment by phil-davis** [comment]
CI configuration has changed for the caldav job(s), so the error on the last drone job is because between Git and drone the PR is "pretend rebased" against current master. Then it turns out that that caldav job no longer exists/works in the form in which it was already started in drone.

Rebase the branch and the internet will be fixed.

**Comment by Julian1998** [comment]
@phil-davis Thanks!!! Good to know...

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
