### PR TITLE
[Stable 8] app upgrade order

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/13865 to stable8

@blizzz @DeepDiver1975 @icewind1991 @karlitschek @MorrisJobke

### CODE REVIEW

**Comment by blizzz** [comment]
:+1:

**Comment by PVince81** [comment]
Hmm but that's your code. I say :+1: for your change.

Still need :+1: from two other people though.

**Comment by blizzz** [comment]
:v:

**Comment by LukasReschke** [comment]
:v: :+1: or whatever

**Comment by blizzz** [comment]
@LukasReschke 

>  Since the 1960s, when the ["V sign"](https://en.wikipedia.org/wiki/V_sign) was widely adopted by the counterculture movement, it has come to be used as a symbol of peace (usually with palm outward).

**Comment by LukasReschke** [comment]
/me is searching for some "you don't say" meme ;-)

Merge or not?

**Comment by blizzz** [comment]
Aaaand,  did you find it?

We need one more thumb.

**Comment by MorrisJobke** [comment]
Tested upgrade from stable7 to this branch :+1: works

**Pull request merged**
