### PR TITLE
fix: login redirect url has to hold the msofba-success route which wa…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…s missing due to the earlier change

## Description
Regression due to #39204

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by JammingBen — APPROVED** [review]

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32289/124/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/32289/124/15
Issue #39213 - unrelated to this PR. I restarted CI.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32290/124/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32293/124/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32295/144/1

**Comment by DeepDiver1975** [comment]
rebased again .....

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32331/144/1

**Comment by DeepDiver1975** [comment]
seems not related ... @phil-davis or am I missing anything? THX

Screenshot from 2021-09-14 11-48-57

**Comment by phil-davis** [comment]
> seems not related ... @phil-davis or am I missing anything? THX

not related - another annoying UI intermittent test!

**Pull request merged**
