### PR TITLE
Update doctrine/dbal to 2.5.1 #13537

### LINKED ISSUE #13303: dbal 2.5.1 has been released - we should consider updating
@VicDeo  can I ask you to prepare a PR which updates 3rdparty repo and core? THX

In case you have questions feel free to ping me

### PR DESCRIPTION
**Pull request by VicDeo**
Closes #13303 
Depends on owncloud/3rdparty#152

Scheduled for 8.1

### CODE REVIEW

**Comment by VicDeo** [comment]
@DeepDiver1975 as I said, it's enough to skip extra `primary` keys for the tests to pass.
Will check migration manually as well

**Comment by DeepDiver1975** [comment]
> as I said, it's enough to skip extra primary keys for the tests to pass.

nice - thx

**Comment by VicDeo** [comment]
Manual migration from OC7 to this branch was successful for sqlite. 
Common scenarios to work with indexes are already covered:
https://github.com/owncloud/core/blob/master/tests/lib/db/migrator.php

**Comment by VicDeo** [comment]
@DeepDiver1975 FYI this originated from SQLite autoincrement kinks http://www.doctrine-project.org/jira/browse/DBAL-188

**Comment by DeepDiver1975** [comment]
Unit tests on oracle just run fine :+1: 
Successful migration testing done as well :+1:

**Comment by DeepDiver1975** [comment]
@icewind1991 please review - THX

**Comment by icewind1991** [comment]
Tested upgrade with pgsql, mysql and oracle, nothing seems to explode

:+1:

**Comment by AdamWill** [comment]
I've also done a quick test on this for Fedora packaging purposes, looks good for sqlite deployment so far, will be testing other DBs and 7.x upgrades soon.

**Comment by DeepDiver1975** [comment]
@VicDeo please create PRs in core and 3rdparty against stable8 branch to introduce dabl 2.5.1 - THX

**Comment by VicDeo** [comment]
@DeepDiver1975 
done https://github.com/owncloud/core/pull/14515

**Comment by DeepDiver1975** [comment]
THX

**Comment by AdamWill** [comment]
I've tested 8.0.0 plus the commit from this PR for clean deployment with sqlite, mariadb, and pgsql, and for upgrade with mysql using both a small test set of data and my production deployment: worked fine on all of them.

**Pull request merged**
