### PR TITLE
[8.2] add locks in the scanner to prevent multiple scanners running on the …

### PR DESCRIPTION
**Pull request by icewind1991**
…same files

Backport of https://github.com/owncloud/core/pull/24205 to stable 8.2

### CODE REVIEW

**Comment by PVince81** [comment]
@icewind1991 just tried reproducing the original issue and I'm getting a different behavior on v8.2.3 without this fix.

It seems that a "mv" operation never rescans the folder's contents, while a "ls" does. So even with the `sleep(1);`, the "mv" will finish quickly.

While "ls" is running the rescan, a "mv" will properly be locked out.

So not sure, maybe the scanner workflow was different in v8.2.3 and since OC 9 we scan in more situations ? I hope this is intended and not an unintended side effect. @icewind1991 can you confirm ?

**Comment by PVince81** [comment]
It does make sense for OC to first rescan a folder's contents before renaming it, so I'd say OC 9 is right and OC 8 was wrong.

**Comment by PVince81** [comment]
Even stranger: when I start first a "mv test test2" and directly after that I do "ls test", the "ls" wins and "mv" fails with 423 Locked.

**Comment by PVince81** [comment]
I just tested two concurrent "ls" on the same to-be-rescanned folder. (like https://github.com/owncloud/core/issues/20555#issuecomment-213447528 but with two "ls" operations)

Before this fix: both hang and take time, one times out.
After this fix: one hangs and takes time, the other one returns the old results

:+1: since this does fixes an issue let's move forward with it.

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by PVince81** [comment]
Regression in occ files:scan with single file shares: https://github.com/owncloud/core/issues/24507

**Pull request merged**
