### PR TITLE
Use jmikola/wildcard-event-dispatcher

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
jmikola/wildcard-event-dispatcher is an alternative implementation of EventDispatcherInterface which allows listening to events with a wild card pattern.

see https://github.com/jmikola/WildcardEventDispatcher/blob/master/README.md

## How Has This Been Tested?
- manually with https://github.com/DeepDiver1975/autobahn

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Automated rebase failed! Please rebase your pull request manually via the command line.

Error:
```Command '['git', 'clone', '--depth', '1', 'rebase', '/tmp/tmpjqva9xwm']' returned non-zero exit status 128.```

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase was successful!

**Comment by PVince81** [comment]
conflicts.

moving to triage for rescheduling if this is useful

**Comment by DeepDiver1975** [comment]
we can revive this once we move on with the message bus stuff -> close

**Comment by phil-davis** [comment]
``backport-request`` label removed, since it is not relevant to closed PRs.

**Pull request closed without merging**
