### PR TITLE
core will handle invalid URLs and redirects properly

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @PVince81 @LukasReschke @nickvergessen @rullzer @Xenopathic

### CODE REVIEW

**Comment by PVince81** [comment]
also @icewind1991

**Comment by PVince81** [comment]
Tested, works :+1: 
Basically, enable activity app, open activity app in separate tab. Disable activity app, then refresh the activity app tab. Redirect still works.

**Comment by icewind1991** [comment]
:+1:

**Comment by PVince81** [comment]
@icewind1991 when adding your second thumbs up, please set the labels from "To review" to "To release" for @DeepDiver1975 to merge. Thanks.

**Pull request merged**
