### PR TITLE
Make Travis CI pass when DAV was not touched

### LINKED ISSUE #20121: Travis always red when not modifying dav app
```
The command "bash tests/travis/test_for_app.sh $APP" failed and exited with 1 during .
```
The above is intended in order to not waste travis time.
However, we actually would like it pass or not run at all, instead of error/fail.

Will have a look if there is a way around it

cc @DeepDiver1975

### PR DESCRIPTION
**Pull request by nickvergessen**
Changed DAV: https://travis-ci.org/owncloud/core/jobs/88074104
Unchanged: https://travis-ci.org/owncloud/core/builds/88074438

Fix #20121

### CODE REVIEW

**Comment by nickvergessen** [comment]
@MorrisJobke @DeepDiver1975 this is ready.

Feel free to cancel the jenkins queue (I pushed like 7 times)

**Comment by DeepDiver1975** [comment]
As soon as we are going to move more tests or even more apps in here - this will be really messy :puke:

**Comment by nickvergessen** [comment]
> As soon as we are going to move more tests or even more apps in here - this will be really messy :puke:

Not really a lot more then currently:
```sh
sh -c "if [ '$TEST_DAV $TEST_EXTERNAL' != '0 0' ]; then bash tests/travis/before_install.sh $DB; fi"
```

Or we event make one value that tests for all of them

**Comment by MorrisJobke** [comment]
I also don't really like it. It looks completely wrong :(

**Comment by DeepDiver1975** [comment]
this approach might be doable for dav only - but we cannot move any additional apps to travis then

@karlitschek keep this approach for dav and do all the external apps in own repos? No ideal either - I know

**Comment by DeepDiver1975** [comment]
okay - let's fix this in to fix our prs :+1:

**Comment by karlitschek** [comment]
@DeepDiver1975 yes. let's keep this for now and see how it goes.

**Comment by karlitschek** [comment]
thanks a lot guys

**Comment by MorrisJobke** [comment]
okay :+1:

**Pull request merged**
