### PR TITLE
[WIP] Allow indices to be only applied on new installations

### PR DESCRIPTION
**Pull request by DeepDiver1975**
So ... what is this all about?
# Background

On MySql we have limitation on the index length (767 bytes in total) which means we cannot create an index over the path of filecache for example.
But MySql offers the possibility to define length on the column to be used for the index which means we can define an index over the path column of filecache which will index at least the first 254 characters of the path - http://dev.mysql.com/doc/refman/5.7/en/create-index.html

This means we might not get a full hit on the path but at least can limit the set within the like query will be performed. (An assumption we need to prove - I'm work on that)
# Problem

Adding an index to oc_filecache is a no go for all live systems out there!
# Solution
- We allow a length to be specified in the schema xml on the column definition of an index
- On MySql we respect this length definition (others as well :question: )
- Indexes can now be defined as <only-on-create/> which results in this index to be only created on new installations
- An occ command db:apply-indexes can be used to apply these indexes after migration during live operations.

@karlitschek @icewind1991 @MorrisJobke objections? Am I walking a total crazy and stupid path? THX
# ToDos
- [ ] fix columns length on initial setup
- [ ] prove performance benefit for sync of many small files
- [ ] prove index helps by reducing the result set for the like query

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@DeepDiver1975 What is the background of this? Doesn't this makes it harder for us in the long run?

**Comment by DeepDiver1975** [comment]
@MorrisJobke see the WIP? Let me first finish - then I'll add some background and we can discuss :wink:

**Comment by DeepDiver1975** [comment]
Setup issue:

````
10:59:49 Error while trying to create admin user: An exception occurred while executing 'CREATE TABLE `oc_filecache` (`fileid` INT AUTO_INCREMENT NOT NULL, `storage` INT DEFAULT 0 NOT NULL, `path` VARCHAR(4000) DEFAULT NULL, `path_hash` VARCHAR(32) DEFAULT '' NOT NULL, `parent` INT DEFAULT 0 NOT NULL, `name` VARCHAR(250) DEFAULT NULL, `mimetype` INT DEFAULT 0 NOT NULL, `mimepart` INT DEFAULT 0 NOT NULL, `size` BIGINT DEFAULT 0 NOT NULL, `mtime` INT DEFAULT 0 NOT NULL, `storage_mtime` INT DEFAULT 0 NOT NULL, `encrypted` INT DEFAULT 0 NOT NULL, `unencrypted_size` BIGINT DEFAULT 0 NOT NULL, `etag` VARCHAR(40) DEFAULT NULL, `permissions` INT DEFAULT 0, `checksum` VARCHAR(255) DEFAULT NULL, UNIQUE INDEX fs_storage_path_hash (`storage`, `path_hash`), UNIQUE INDEX fs_storage_path (`storage`, `path`), INDEX fs_parent_name_hash (`parent`, `name`), INDEX fs_storage_mimetype (`storage`, `mimetype`), INDEX fs_storage_mimepart (`storage`, `mimepart`), INDEX fs_storage_size (`storage`, `size`, `fileid`), PRIMARY KEY(`fileid`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':
10:59:49 
10:59:49 SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by icewind1991** [comment]
I would be hesitant to go this route because it will create a split in setups, some instances would have other indexes than others and we will have to support both of them

(for the specific filecache use case I don't expect many performance gains from a (partial) index on the path column since it already indexes path_hash but I don't have any hard data on it)

**Comment by DeepDiver1975** [comment]
@icewind1991 this query for example is not working on the path_hash column - https://github.com/owncloud/core/blob/master/lib/private/files/cache/cache.php#L513 - no idea how big the impact is.

This needs deeper analysis ...

**Comment by DeepDiver1975** [comment]
@karlitschek @MorrisJobke still waiting on your feedback - THX

**Comment by MorrisJobke** [comment]
I still fear that we make our lives a lot harder with this. Because then we have instances with different DB schemas setup. See it as a config option that multiplies all test scenarios. I personally don't like it :(

**Comment by DeepDiver1975** [comment]
Points taken ... the questions then is: will we ever have the capability to add indexes to existing big installations?

**Comment by MorrisJobke** [comment]
> Points taken ... the questions then is: will we ever have the capability to add indexes to existing big installations?

The actual point here is, that all big installations I know use a MySQL cluster 🙈

**Comment by DeepDiver1975** [comment]
> The actual point here is, that all big installations I know use a MySQL cluster :see_no_evil:

yes - and? How does that relate? We might want/need to apply additional indexes there as well

**Comment by MorrisJobke** [comment]
> yes - and? How does that relate? We might want/need to apply additional indexes there as well

~~Wasn't the topic of this PR to add indexes to databases that are not Mysql-based.~~

Nevermind. I just reread the comment. You want to add a partial index.

To clarify: The index then will be available on all instances, not by default, but as an opt-in (occ command). On some instances this index will be a full index and on mysql this will be a partial index for the first n characters. Right?

**Comment by DeepDiver1975** [comment]
> On some instances this index will be a full index and on mysql this will be a partial index for the first n characters. Right?

yes - and in addition to this (because we are talking about oc_filecache) we need a mechanism to apply indexes in live operations (not necessarily using occ) and NOT block the regular migration.

**Comment by MorrisJobke** [comment]
> yes - and in addition to this (because we are talking about oc_filecache) we need a mechanism to apply indexes in live operations (not necessarily using occ) and NOT block the regular migration

Ah. So this is also a decoupling of the mechanismns. I'm still not 100% convinced, but I guess we have no other way than to do it in that way.

Maybe we could add a I-dont-care-mode, that always adds the index for very small instances. And allow admins of bigger installations to run it when they want it and not at some point in time.

**Comment by DeepDiver1975** [comment]
> Maybe we could add a I-dont-care-mode, that always adds the index for very small instances.

Could be depending on the table size ....

**Comment by MorrisJobke** [comment]
> Could be depending on the table size ....

The metric that needs evaluated to check if it could be simply applied can be determined in a later step.

**Comment by PVince81** [comment]
@DeepDiver1975 9.2 or bugfix for 9.1 ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 9.2 or bugfix for 9.1 ?

9.2

**Comment by PVince81** [comment]
@DeepDiver1975 still interested in continuing this ?

**Comment by DeepDiver1975** [comment]
once we have doctrine migrations in place this can be done with them -> close

**Pull request closed without merging**
