### PR TITLE
Decode request content only on getContent

### LINKED ISSUE #17712: zotero stopped synchronising binary files with owncloud after upgrade to ownCloud 8.1
I used to use owncloud's webdav as a space for zotero's binary files storage as described here: https://www.zotero.org/support/sync#webdavhttps://www.zotero.org/support/sync#webdav

I think that just after the ownCloud has been upgraded to 8.1 on Centos7 (PHP5.4) the webdav synchronisation on zotero got broken. Zotero put only two files in the zotero directory gave an error message 400. Each time I retry get the same.

Here is what I have been founding in the owncloud.log:

```
{"reqId":"VakHwvGuYo1oTZ3-cedXDwAAAAA","remoteAddr":"10.0.0.7","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 110 got 0\",\"Code\":0,\"Trace\":\"
#0 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(113): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #251)\\n
#1 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('A3ZH6IP5.prop', Resource id #251)\\n
#2 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('zotero\\\/A3ZH6IP5...', Resource id #251, NULL)\\n
#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#4 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#5 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n
#6 \\\/home\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#7 \\\/home\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n
#8 \\\/home\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/home\\\/www\\\/owncl...')\\n
#9 {main}\",\"File\":\"\\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":144}","level":4,"time":"2015-07-17T13:48:51+00:00"}
```

### LINKED ISSUE #18428: Provisioning API broken on PHP 5.4
A recent change seems to have broken the provisioning API and it doesn't behave properly any more on PHP 5.4 and 5.5 (probably old) on Travis when trying to create a user and verify its creation.

It works fine on PHP 5.6.

I don't have more details at this point, except that everything was fine last night.

This is what happens when I try to create a user

```
1) Failed to create a user via the provisioning api in OcsCreateUserCept (tests/api/OcsCreateUserCept.php)
 Step  I see xml response includes "DOMDocument"
 Fail  found in XML Response
Failed asserting that '<ocs><meta><status>failure</status><statuscode>999</statuscode><message>Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT:
</message></meta><data></data></ocs>' contains "<status>ok</status>".
```

Checking for the presence of a user still works.

Could someone please confirm that behaviour.

### LINKED ISSUE #18588: Group ID can not be read from request body on OCS "remove user from group"
The following works:
```
curl -X "DELETE" 'http://...@localhost/ocs/v1.php/cloud/users/test3/groups?groupid=test1'
```

Request body does not work anymore:
```
curl -X "DELETE" -d "groupid=test1" 'http://...@localhost/ocs/v1.php/cloud/users/test3/groups'
```

Causing commit is https://github.com/owncloud/core/commit/6a3fb0d3b36dce7a6583d58ded1b133f086e2a95

This causes Smashbox to fail on the `lib/oc-tests/test_shareGroup.py`

Happens on php 5.5.9 and 5.5.28

@LukasReschke @DeepDiver1975

### LINKED ISSUE #18661: After upgrade to 8.1.1 - Bookmark upload via Xmarks and WebDAV fails
### Client configuration
- Ubuntu 14.04
- Firefox 40.0.3
- Xmarks 4.3.7.1-signed
- URI for sync is: http://darkpi:8008/remote.php/webdav/bookmarks.txt

### Steps to reproduce
1. Do changes on local bookmarks
2. Try to synchronize with OC or make complete upload of bookmarks (via addon settings)

### Expected behaviour
Successful sync.

### Actual behaviour
Failed with HTTP status 400 (Bad Request). Owncloud.log says
```
{"reqId":"OBgB9LCwxoPwbq1xIebx","remoteAddr":"192.168.178.38","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 81675 got 0\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #181)\\n#1 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('bookmarks.txt', Resource id #181, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/darkcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/darkcloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/darkcloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/darkcl...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/darkcloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":144}","level":4,"time":"2015-08-28T20:40:41+00:00"}
```

### Server configuration
**Operating system**: Raspbian (Linux 3.4.90 #2 SMP PREEMPT Tue Aug 5 14:11:40 CST 2014 armv7l) on BananaPi

**Web server:** Apache/2.2.22 (Debian)

**Database:** mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (armv7l) using readline 6.2

**PHP version:** PHP 5.4.44-0+deb7u1 (cli) (built: Aug 27 2015 17:22:22) 

**ownCloud version:** 8.1.1.3

**Updated from an older ownCloud or fresh install:** Upgrade from 8.0.x via web updater

**List of activated apps:**

```
    Enabled:
     - bookmarks: 0.4
     - calendar: 0.7.3
     - contacts: 0.4.0.0
     - encryption: 1.0.0
     - files: 1.1.10
     - files_sharing: 0.6.2
     - files_texteditor: 0.4
     - firstrunwizard: 1.1
     - gallery: 0.6.0
     - notes: 1.0.0
     - templateeditor: 0.1
     - updater: 0.6
    Disabled:
     - activity
     - admin_dependencies_chk
     - documents
     - external
     - files_external
     - files_locking
     - files_pdfviewer
     - files_trashbin
     - files_versions
     - files_videoviewer
     - provisioning_api
     - search_lucene
     - user_external
     - user_ldap
     - user_webdavauth
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc8qghi17t9v',
  'passwordsalt' => 'SECRET',
  'secret' => 'SECRET',
  'trusted_domains' =>
  array (
    0 => 'darkpi',
  ),
  'datadirectory' => '/var/www/darkcloud/data',
  'overwrite.cli.url' => 'http://darkpi:8008/darkcloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'installed' => '1',
  'dbname' => 'DarkCloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_CloudMaster1',
  'dbpassword' => 'SECRET',
  'theme' => '',
  'maintenance' => false,
);
```

### References/Hints
- Original forum post 
https://forum.owncloud.org/viewtopic.php?f=31&t=30136
- Maybe same as https://github.com/owncloud/core/issues/17712 ?

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Delay reading `php://input` until the content is actually needed, avoiding the bug with `php://input` only being able to be read once in PHP <5.6.

The Request unit tests pass locally, and my own tests PUTting data with the `application/json` and `application/x-www-form-urlencoded` now succeed. A quick play with the web UI shows basic functions working fine too. Also, `lib/oc-tests/test_shareGroup.py` in smashbox also now succeeds (reported broken in #18588)!

Fixes #17712, fixes #18661, fixes #18428 (hopefully?), fixes #18588 

ref owncloud/smashbox#128

@nickvergessen @LukasReschke @karlitschek @DeepDiver1975 @PVince81 @MorrisJobke @oparoz 

@karlitschek This bug also affects older versions of ownCloud, albeit with a lower severity (see #17712, #18661). Perhaps we want to backport this?

### CODE REVIEW

**Comment by Xenopathic** [comment]
Now, time for some sleep methinks.

**Comment by karlitschek** [comment]
hmm. @Xenopathic @DeepDiver1975 how risky is the backport?

**Comment by Xenopathic** [comment]
cc @Raydiation

**Comment by nickvergessen** [comment]
Fixes the OCS request and the failing files texteditor.
Will test smashbox, once I got some refreshments.

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1: Also the code looks really good

**Comment by nickvergessen** [comment]
https://github.com/owncloud/files_texteditor/issues/95

**Comment by PVince81** [comment]
Talked with @cmonteroluque @Xenopathic @MorrisJobke, backport will be done for 8.1.3 only.
This problem only affects PHP < 5.6 and third party Webdav applications (not the official clients)

**Comment by nickvergessen** [comment]
+ OCS + shipped Apps?

But yes 8.1.3 it is

**Comment by Xenopathic** [comment]
@nickvergessen In 8.1 OCS is still working, since @LukasReschke hadn't broken it yet. The bug is still there, but only triggers on those specific third party DAV requests

**Pull request merged**
