### PR TITLE
Do not use APCu when apc.enabled is Off.

### PR DESCRIPTION
**Pull request by bantu**
Possible fix for #15146

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by bantu** [comment]
User says this is good. https://github.com/owncloud/core/issues/15146#issuecomment-86074727

**Comment by LukasReschke** [comment]
:+1:

Probably good to backport?

**Comment by karlitschek** [comment]
:+1: 
please backport

**Comment by DeepDiver1975** [comment]
@bantu can you please submit a backport pr against stable8? THX

**Pull request merged**
