### PR TITLE
[stable7] Fix config API usage in cron.php

### PR DESCRIPTION
**Pull request by PVince81**
Fixes cron.php issue: https://github.com/owncloud/core/pull/14846#issuecomment-85597279

### CODE REVIEW

**Comment by PVince81** [comment]
Please review @AdamWill @DeepDiver1975 @nickvergessen @karlitschek

**Comment by nickvergessen** [comment]
:+1:

**Comment by AdamWill** [comment]
:+1: 

This is the same change I came up with locally; I'll confirm with the bug reporter that it works for him.

**Comment by DeepDiver1975** [comment]
> :+1: taking half of the shame on the original PR

leave the rest of the shame for me - :so_sorry: :+1:

**Comment by AdamWill** [comment]
Downstream reporter confirms the fix, thanks.

**Pull request merged**
