### PR TITLE
throw exception when LDAP Connection was lost

### PR DESCRIPTION
**Pull request by blizzz**
Addition to https://github.com/owncloud/core/pull/15489 (it's included in the stable7 and stable8 based PRs).

How to test: https://github.com/owncloud/core/pull/15332#issuecomment-95174046

@butonic @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by DeepDiver1975** [comment]
unit test? @blizzz thx

**Comment by blizzz** [comment]
@DeepDiver1975 nada unit, integration test only. Let me script one.

**Comment by blizzz** [comment]
```
$ sudo -u www-data php -f apps/user_ldap/tests/integration/exceptionOnLostConnection.php 
Test PASSED
```

returns "Test FAILED" with the other commit. Needs toxiproxy, but it's pretty straightforward to set up.

@DeepDiver1975 happy?

**Comment by blizzz** [comment]
@owncloud-bot retest this please

**Comment by blizzz** [comment]
jenkins hiccup…

**Comment by blizzz** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by blizzz** [comment]
master does not run for me at all locally, quits with error code 1. did investigate it further.

**Comment by blizzz** [comment]
did not ... (cannot edit posts in mobile view)

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
Hmm ... looks like jenkins wants to execute the integration tests ....
````
08:10:42 PHP Fatal error:  Uncaught exception 'Exception' with message 'Failed to connect to localhost port 8474: Connection refused' in /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/user_ldap/tests/integration/exceptionOnLostConnection.php:151
08:10:42 Stack trace:
08:10:42 #0 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/user_ldap/tests/integration/exceptionOnLostConnection.php(97): ExceptionOnLostConnection->checkCurlResult(Resource id #690, false)
08:10:42 #1 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/user_ldap/tests/integration/exceptionOnLostConnection.php(74): ExceptionOnLostConnection->setUp()
08:10:42 #2 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/user_ldap/tests/integration/exceptionOnLostConnection.php(190): ExceptionOnLostConnection->__construct('http://localhos...', 'ldap', 'dc=owncloud,dc=...')
08:10:42 #3 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/apps.php(17): require_once('/var/jenkins/wo...')
08:10:42 #4 /var/jenkins/workspace/pull-re in /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/user_ldap/tests/integration/exceptionOnLostConnection.php on line 151
08:10:42 Build step 'Execute shell' marked build as failure
08:10:43 Recording test results
08:10:44 ERROR: Publisher 'Publish JUnit test result report' failed: No test report files were found. Configuration error?
08:10:44 Setting commit status on GitHub for https://github.com/owncloud/core/commit/e8263a52751239a18cab945c923514695dee7709

**Comment by DeepDiver1975** [comment]
@blizzz

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
