### PR TITLE
Directly honour robots.txt if htaccess.RewriteBase

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

If `htaccess.RewriteBase` is set, then robots.txt can't be requested.
This PR then solves this issue.

Thank you 👍 

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
Hi,
Some news regarding this tiny patch ?
Thank you 👍

**Comment by benrubson** [comment]
Hi,
Some news regarding this very-easy-to-review tiny patch ?
Many thanks 👍

**Comment by benrubson** [comment]
Hi,
Some news regarding this very-easy-to-review tiny patch please ?
Many thanks 👍

**Comment by benrubson** [comment]
Hi,
Some news regarding this very-easy-to-review tiny patch please ?
@DeepDiver1975 ?
Many thanks 👍

**Comment by benrubson** [comment]
I'm still facing this issue with 10.0.10.
Could we then think about merging this tiny patch please ?
@DeepDiver1975 ?
Many thanks again 👍

**Comment by benrubson** [comment]
I'm still facing this issue with 10.1.0.
Could we then think about merging this tiny patch please, so that it'll be in 10.1.1 ?
@DeepDiver1975, @PVince81, @phil-davis ? :)
Many thanks again 👍

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase failed! Please rebase your pull request manually via the command line.

Reason:
```
Command: git push --force origin HEAD:robots.txt

Exit Code: 1

Cause:

To <hidden_oauth_token>
 ! [remote rejected] HEAD -> robots.txt (shallow update not allowed)
error: failed to push some refs to '<hidden_oauth_token>'


```

**Comment by benrubson** [comment]
Thank you @phil-davis 👍 
I then just rebased manually.

**Comment by benrubson** [comment]
Still facing with 10.1.1...
Any news regarding this tiny thing please ?
Thank you again...

**Review by PVince81 — APPROVED** [review]
looks safe :+1: 

please backport by branching off stable10 and sending a PR back to stable10 with this change

**Comment by benrubson** [comment]
@PVince81, thank you very much 👍
Here is then the PR against stable10 : #34949
Thank you again !

**Pull request merged**
