### PR TITLE
hasKey() is there for a reason :speak_no_evil:

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by Xenopathic** [comment]
The only problem with this approach is the potential for a race condition - if the cache entry expires between `hasKey()` and `get()`, the `get()` will get a null - bad! I've started using the following pattern:

```
if ($result = $this->cache->get('foobar')) {
    return $result;
}
```

Avoids the race condition and reduces the number of calls to the memcache backend :speak_no_evil:

**Comment by DeepDiver1975** [comment]
> Avoids the race condition and reduces the number of calls to the memcache backend :speak_no_evil:

true story - thx

**Comment by DeepDiver1975** [comment]
as a result we should not have added hasKey() in the first place

@Xenopathic can I ask you to submit a PR with your approach? THX

**Comment by Xenopathic** [comment]
@DeepDiver1975 Well, `hasKey()` does have some limited uses (in particular when a value returned from the memcache may be `null`), but I agree that in the majority of cases a simple `get()` is best. I'll rewrite any flawed `hasKey()` usage when I see it :smile:

**Pull request closed without merging**
