### PR TITLE
Minimum search length will be applied for all shares

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Minimum search length will be applied to all shares (user, group and remote)

## Related Issue
https://github.com/owncloud/enterprise/issues/5833

## How Has This Been Tested?
Manually tested with federation. No remote will be shown if the search length is lower than the minimum allowed. Only exact matches will be shown if the search term is below the minimum char length

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by jvillafanez** [comment]
```
 Scenario: autocomplete short user/display names when completely typed                    # /drone/src/tests/acceptance/features/webUISharingAutocompletion1/shareAutocompletion.feature:57
    Given the administrator has set the minimum characters for sharing autocomplete to "4" # WebUISharingContext::setMinCharactersForAutocomplete()
    And user "autocomplete-test-user" has logged in using the webUI                        # WebUILoginContext::theUserHasLoggedInUsingTheWebUI()
    And the user has browsed to the files page                                             # WebUIFilesContext::theUserBrowsesToTheFilesPage()
    And these users have been created without skeleton files and not initialized:          # FeatureContext::theseUsersHaveBeenCreatedWithoutSkeletonFiles()
      | username | password | displayname | email        |
      | fiv      | %alt1%   | Someone     | fi@oc.com.np |
INFORMATION: timed out waiting for ajax calls to start
    And the user has opened the share dialog for folder "simple-folder"                    # WebUISharingContext::theUserOpensTheShareDialogForFileFolder()
      │ INFORMATION: timed out waiting for ajax calls to start
    When the user types "fiv" in the share-with-field                                      # WebUISharingContext::theUserTypesInTheShareWithField()
    Then only user "Someone" should be listed in the autocomplete list on the webUI        # WebUISharingContext::onlyUserNameShouldBeListedInTheAutocompleteList()
      expected 1 autocomplete item but there are 0
      Failed asserting that actual size 0 matches expected size 1.
    And user "User Five" should not be listed in the autocomplete list on the webUI        # WebUISharingContext::userShouldNotBeListedInTheAutocompleteListOnTheWebui()
SCENARIO RESULT: (fail)
```
This scenario is failing now because the search term must have at least the minimum length. What we should do with it?

**Comment by phil-davis** [comment]
> This scenario is failing now because the search term must have at least the minimum length. What we should do with it?

What is the requirement?

If the minimum characters for sharing autocomplete is set to some value like `4` and there are users with usernames and/or display names with length less than `4`, then how can someone share with that user?

IMO exact matches with what is typed should be returned no matter how short they are.

**Comment by jvillafanez** [comment]
You're right. I've also checked https://github.com/owncloud/core/blob/master/config/config.sample.php#L374 and exact matches are expected to be returned no matter the length.

I've pushed a new commit with a different approach. It should keep the same requirements, so tests should pass

**Review by pako81 — APPROVED** [review]

**Comment by phil-davis** [comment]
I suppose that this should get into 10.13.0 ?
And I see that `release-10.13.0` branch has already been created.

What is the workflow for things like this that need to get into the release branch?
@jnweiger

**Comment by jvillafanez** [comment]
Worst case, it should be easy to create a new branch from the release and cherry-pick these commits

**Comment by phil-davis** [comment]
The tricky part is the changelog file. In the release branch, there is no `changelog/unreleased` folder. So if we make a PR to the release branch, and this PR also gets merged to master, then there can be hassles with the merge-back of the release branch...

So we just need to be careful not to merge into both places.

I will make a PR to the release branch in a few minutes, and someone can decide what to merge.

**Comment by jnweiger** [comment]
Nothing complex has yet happened in the release-branch. 
If it helps, I can destroy the current release-10.13.0 again, and we continue in master, until we reach feature completeness for 10.13

**Comment by pako81** [comment]
merge it?

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
