### PR TITLE
use requesttoken from request when (memory) session does not contain …

### PR DESCRIPTION
**Pull request by butonic**
:skull: :skull::skull: :skull::skull: :skull: **Insecure, see https://github.com/owncloud/core/pull/16186#issuecomment-100140688** :skull: :skull::skull: :skull::skull: :skull: 

…token, fixes session when using querylog

Current master: when I set `'log_query' => true,` I can no longer use owncloud because the in memory session is stored in the request before the login could be handled.

This may not be the correct fix. but it is too late for me to find a better one.

cc @LukasReschke in case this opens an attack vector...

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by butonic** [comment]
meh ... I still cannot upload files ... screw this ... all I wanna do is get a query log for deleting a shared file. Jesus ... I'm out. n8 all

**Comment by karlitschek** [comment]
n8 @butonic

**Comment by butonic** [comment]
just for reference, the update queries we currently execute when deleting a file in the root folder. trashbin and versions are enabled. the file was shared with a single user:
```json
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `storage` =  ?, `path` = ?, `path_hash` = ?, `name` = ?, `parent` =? WHERE `fileid` = ?","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => '1',   1 => 'files_trashbin\/files\/Neue Textdatei.txt.d1431045513',   2 => '4f61877a2cbf05404467bf2d4763e6a6',   3 => 'Neue Textdatei.txt.d1431045513',   4 => '5279',   5 => 5286, )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
--
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `mimepart` = ?, `mimetype`=? WHERE (`mimepart` <> ? OR `mimetype` <> ? ) AND `fileid` = ? ","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => '5',   1 => '9',   2 => '5',   3 => '9',
  4 => '5286', )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
--
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `mtime` = ?, `storage_mtime`=? WHERE (`mtime` <> ? OR `storage_mtime` <> ? ) AND `fileid` = ? ","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => 1431045513,   1 => 1431045513,   2 => 1431045513,   3 => 1431045513,   4 => '2', )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
--
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `mtime` = ?, `storage_mtime`=? WHERE (`mtime` <> ? OR `storage_mtime` <> ? ) AND `fileid` = ? ","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => 1431045513,   1 => 1431045513,   2 => 1431045513,   3 => 1431045513,   4 => '5279', )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
--
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `mtime` = ?, `etag`=? WHERE (`mtime` <> ? OR `etag` <> ? ) AND `fileid` = ? ","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => 1431045513,   1 => '554c058928e01',   2 => 1431045513,   3 => '554c058928e01',   4 => 1, )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
--
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `mtime` = ?, `etag`=? WHERE (`mtime` <> ? OR `etag` <> ? ) AND `fileid` = ? ","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => 1431045513,   1 => '554c05892a324',   2 => 1431045513,   3 => '554c05892a324',   4 => 2, )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
--
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `mtime` = ?, `etag`=? WHERE (`mtime` <> ? OR `etag` <> ? ) AND `fileid` = ? ","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => 1431045513,   1 => '554c05892ba09',   2 => 1431045513,   3 => '554c05892ba09',   4 => 5275, )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
--
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `mtime` = ?, `etag`=? WHERE (`mtime` <> ? OR `etag` <> ? ) AND `fileid` = ? ","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => 1431045513,   1 => '554c05892cef5',   2 => 1431045513,   3 => '554c05892cef5',   4 => 5279, )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
--
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `mtime` = ?, `storage_mtime`=? WHERE (`mtime` <> ? OR `storage_mtime` <> ? ) AND `fileid` = ? ","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => 1431045513,   1 => 1431045513,   2 => 1431045513,   3 => 1431045513,   4 => '2', )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
--
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB prepare : UPDATE `oc_filecache` SET `mtime` = ?, `etag`=? WHERE (`mtime` <> ? OR `etag` <> ? ) AND `fileid` = ? ","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"JhEIs35TpGHTgnpKaIV9","remoteAddr":"192.168.56.1","app":"core","message":"DB execute with arguments : array (   0 => 1431045513,   1 => '554c0589348f3',   2 => 1431045513,   3 => '554c0589348f3',   4 => 2, )","level":0,"time":"2015-05-08T00:38:33+00:00","method":"POST","url":"\/index.php\/apps\/files\/ajax\/delete.php"}
```

**Comment by LukasReschke** [comment]
This actually introduces a security bug since it makes our CSRF protection useless. Let's think about what a CSRF protection is about:

In the web as of today a web page can link to other web pages and do some kind of requests such as `GET`'s to other webpages. That is completely fine and since the web was fully static in the first years nobody thought about the future implications caused by this. 
Now let's consider you have an administrative interface in your web site and an endpoint like `deleteUser.php?id=$userId`, when you request `deleteUser.php?id=test` for example the user `test` will get deleted. Now imagine what would happen if another webpage links you to `deleteUser.php?id=test` or loads it automatically via Javascript, it will happily delete the user.
That's what the CSRF token is here to prevent, it is a shared secret that will get appended to every request. So the server now will deny any requests to `deleteUser.php?id=test` but would allow it if `deleteUser.php?id=test&token=alongrandomtoken` is sent. Of course, that token is only known to the original web page (for example via JS magic as we do) and the actual web server.
Please notice that any sane developer would nowadays use `POST` for the above, `POST` is vulnerable to CSRF attacks as well but it is always easier to explain it using `GET` :-) 

So, with this patch applied you effectively break the CSRF protection as the shared secret can actually be created by the browser and thus also other malicious websites. Given that the user has not yet received any CSRF token applied to the session which is indeed possible in a few scenarios.

The easiest one, which means there are likely some others that require more fiddling around but as an attacker you have time, is:

1. Upload a file `test.html` with the following content to a web server and adjust the action URL

```html
<html>
  <body>
    <form action="http://localhost/master/index.php/settings/users/users" method="POST">
      <input type="hidden" name="username" value="hacker" />
      <input type="hidden" name="password" value="hacker" />
      <input type="hidden" name="email" value="" />
      <input type="hidden" name="requesttoken" value="foo" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
```

2. Checkout your branch
3. Delete all ownCloud cookies
4. In your browser open http://localhost/master/remote.php/webdav/ and login with an admin account, do only this request.
5. Open the `test.html` (in my case it's on attacker.dev/test.html)
6. An user "hacker" with the password "hacker" has been created

We should really not lower security measures as a workaround around the actual bug. In this case we need to investigate why this fails and fix the bug appropriately :-)

Thanks for mentioning me on this issue.

**Comment by butonic** [comment]
Yes, I feared I was messing with forces beyond my power. Let me explain what happens, so someone with more insight into the dependency injection can fix this properly.

When enabling the query logging the initial empty in memory session is used to initialize the request object because the query log accesses the user session. As a result the subsequent calls will all receive a request object that has been initialized with the empty session and as a result the requesttoken set to false.

I tried unsetting the request object in the server container, but only discovered that that also delete the factory ... In any case it was too late and I was getting tired of finding the right solution. The result is this new security vulnerability...

I will now crawl back into my cave...

**Comment by DeepDiver1975** [comment]
@butonic what shall we do with this? THX

**Comment by PVince81** [comment]
(R)evive, (D)efer, (C)lose ?

**Comment by PVince81** [comment]
@LukasReschke @butonic any interest in finishing this ? Is this needed ?

**Comment by MorrisJobke** [comment]
@butonic @LukasReschke Should we revive or kill it?

**Comment by butonic** [comment]
try to reproduce this by deleting a file when `'log_query' => true,` trashbin and versions enabled.

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/17600

:+1:

**Comment by PVince81** [comment]
had a chat with @LukasReschke and he told me that this is insecure.

So :-1:

**Comment by PVince81** [comment]
Maybe we should revampt the query logger and do it differently.

**Comment by icewind1991** [comment]
Apps can do query logging (atm only if debug mode is enabled)

**Comment by icewind1991** [comment]
With debug mode enabled `\OC::$server->getQueryLogger()->getQueries()` will return every query that was executed during the request

**Comment by PVince81** [comment]
@icewind1991 didn't we fix the log_query thing already, differently ?

**Comment by icewind1991** [comment]
not that I'm aware of

**Comment by MorrisJobke** [comment]
This works with stable8.2, stable9 and master -> closing

**Pull request closed without merging**
