### PR TITLE
Fixing issue #15322 - showing Settings button next to gear icon

### PR DESCRIPTION
**Pull request by ddxor**
Removed span class which caused Settings text to fail to appear.

### CODE REVIEW

**Comment by ddxor** [comment]
this contribution is MIT licensed

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by MorrisJobke** [comment]
Fixes #15322

**Comment by MorrisJobke** [comment]
@owncloud-bot This is okay to test

**Comment by Xenopathic** [comment]
I like this - it gives much needed visibility to that option, which is often overlooked on larger displays :+1:

**Comment by jancborchardt** [comment]
A follow up is at #15488 – showing both text and icons for all sidebar entries in the Files app. I also picked up your commit @ddxor, please review. :)

**Comment by MorrisJobke** [comment]
Was merged with #15488

**Comment by jancborchardt** [comment]
Thank you @ddxor! :)

**Comment by jancborchardt** [comment]
@ddxor @bnvk you are both very welcome in our #owncloud-design IRC channel (on freenode).

**Pull request closed without merging**
