### PR TITLE
add method to count users by loginname and use it for diagnose test, …

### LINKED ISSUE #20151: LDAP 'UserMapper was not assigned to this Access instance'
With the latest (29/10/2015) master, I'm seeing an error when ~~editing the raw LDAP filter on the Login Attributes section and~~ trying to verify a user on the Login Attributes panel: 'UserMapper was not assigned to this Access instance'. The following appears in the log:

```
{"reqId":"486hGY\/e1\/nKOpD7ry0+","remoteAddr":"10.248.41.23","app":"PHP","message":"Undefined index: displayname at \/srv\/git@robin\/owncloud\/core\/apps\/user_ldap\/lib\/access.php#696","level":3,"time":"2015-10-29T13:44:12+00:00"}
```

LDAP configuration:

```
+-------------------------------+--------------------------------------------+
| Configuration                 | s01                                        |
+-------------------------------+--------------------------------------------+
| hasMemberOfFilterSupport      |                                            |
| hasPagedResultSupport         |                                            |
| homeFolderNamingRule          |                                            |
| lastJpegPhotoLookup           | 0                                          |
| ldapAgentName                 |                                            |
| ldapAgentPassword             | ***                                        |
| ldapAttributesForGroupSearch  |                                            |
| ldapAttributesForUserSearch   |                                            |
| ldapBackupHost                |                                            |
| ldapBackupPort                |                                            |
| ldapBase                      | dc=mccorkell,dc=me,dc=uk                   |
| ldapBaseGroups                | ou=groups,dc=mccorkell,dc=me,dc=uk         |
| ldapBaseUsers                 | ou=users,dc=mccorkell,dc=me,dc=uk          |
| ldapCacheTTL                  | 600                                        |
| ldapConfigurationActive       | 1                                          |
| ldapEmailAttribute            |                                            |
| ldapExperiencedAdmin          | 0                                          |
| ldapExpertUUIDGroupAttr       | cn                                         |
| ldapExpertUUIDUserAttr        | uid                                        |
| ldapExpertUsernameAttr        |                                            |
| ldapGroupDisplayName          | cn                                         |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))             |
| ldapGroupFilterGroups         |                                            |
| ldapGroupFilterMode           | 0                                          |
| ldapGroupFilterObjectclass    | posixGroup                                 |
| ldapGroupMemberAssocAttr      | memberUid                                  |
| ldapHost                      | zeus.lan.mccorkell.me.uk                   |
| ldapIgnoreNamingRules         |                                            |
| ldapLoginFilter               | (&(|(objectClass=posixAccount))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                            |
| ldapLoginFilterEmail          | 0                                          |
| ldapLoginFilterMode           | 1                                          |
| ldapLoginFilterUsername       | 1                                          |
| ldapNestedGroups              | 0                                          |
| ldapOverrideMainServer        |                                            |
| ldapPagingSize                | 500                                        |
| ldapPort                      | 389                                        |
| ldapQuotaAttribute            |                                            |
| ldapQuotaDefault              |                                            |
| ldapTLS                       | 0                                          |
| ldapUserDisplayName           | displayName                                |
| ldapUserFilter                | (|(objectclass=posixAccount))              |
| ldapUserFilterGroups          |                                            |
| ldapUserFilterMode            | 0                                          |
| ldapUserFilterObjectclass     | posixAccount                               |
| ldapUuidGroupAttribute        | auto                                       |
| ldapUuidUserAttribute         | auto                                       |
| turnOffCertCheck              | 0                                          |
| useMemberOfToDetectMembership | 1                                          |
+-------------------------------+--------------------------------------------+
```

cc @blizzz

### PR DESCRIPTION
**Pull request by blizzz**
…fixes #20151 

Test steps:
1. Configure an LDAP connection until finishing Login Filter tab
2. Test a valid Login name

Before: Instead of a success message "UserMapper was not assigned to this Access instance"  is shown
Now: Works

Please test and review @Xenopathic @PVince81 @GreenArchon @davitol 

@karlitschek needs to be backported til 8.1 – ok?

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport

**Comment by Xenopathic** [comment]
Works :+1: (on a side note, the yellow box for displaying success isn't very good, we should have an inline green box/message/tick that appears next to the verify button on success, like for change display name or email, @jancborchardt )

**Comment by ggujabidze** [comment]
Sorry guys that I'm jumping into conversation of developers, I'm just one of users who is eager to find solution from this issue. Because my manager requested from me to upgrade owncloud version as soon as possible on Production. So this night, I'm working on this migration and got faced with that nasty bug  :(

So, I don't want to fall back and hence made all the suggested changes in php scripts and yes, now the Test Loginname works, but I still can't see my users list on user's tab, as all of my users are imported/mapped from M$ Active Directory, hence I can not login into web page with my ldap account. Maybe I can help you some how to test it more deeply and provide you more logs?

There're few similar error logs:

ldap_search(): Partial search results returned: Sizelimit exceeded at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#257

Call to undefined method OCA\user_ldap\lib\user\OfflineUser::processAttributes() at /var/www/html/owncloud/apps/user_ldap/lib/access.php#712 

Sorry I don't know how to format text in post.

**Comment by LukasReschke** [comment]
> Sorry guys that I'm jumping into conversation of developers, I'm just one of users who is eager to find solution from this issue. Because my manager requested from me to upgrade owncloud version as soon as possible on Production. So this night, I'm working on this migration and got faced with that nasty bug :(

On a related note: If you use ownCloud professionally you might also consider getting official support from https://owncloud.com/ to support the further development of ownCloud. (https://owncloud.com/subscriptions/)

**Comment by LukasReschke** [comment]
> Maybe I can help you some how to test it more deeply and provide you more logs?

Mind open a new issue following the issue template? THX. => https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by ggujabidze** [comment]
Hi LukasReschke,

Don't think that I'm claiming anything, I'm Linux system administrator for years, so I do understand what Free software means. When I was upgrading, I was realizing that there will be many bugs  and I have no guarantee that the product will be ready for production. That's why I have full backup of my owncloud virtual machine and I can restore it in minutes, I just like to dig deeper into configs and try fix things ( with the help of Community ), that's it.  ;-)

**Comment by Xenopathic** [comment]
@ggujabidze If you can, run a Wireshark capture on the LDAP communication, see exactly what gets sent over the wire.

**Comment by ggujabidze** [comment]
@Xenopathic Sorry for late reply, I've captured traffic with tcpdump, filtered it with destination IP (LDAP server IP), and it's very strange, I don't know why, but server tries to generate ARP list of all ldap user PCs  :(

Here's piece of dump

03:17:34.303496 IP owncloud01.gcfund.dc.37461 > gcf-r2.gcfund.dc.domain: 40136+ A? owncloud01.gcfund.dc. (38)
03:17:34.303851 IP owncloud01.gcfund.dc.57881 > gcf-r2.gcfund.dc.domain: 42893+ PTR? 220.0.168.192.in-addr.arpa. (44)
03:17:34.304245 IP owncloud01.gcfund.dc.57957 > gcf-r2.gcfund.dc.domain: 65477+ A? gcf-r2.gcfund.dc. (34)
03:17:34.304256 IP owncloud01.gcfund.dc.57957 > gcf-r2.gcfund.dc.domain: 3277+ AAAA? gcf-r2.gcfund.dc. (34)
03:17:34.304392 IP owncloud01.gcfund.dc.45814 > gcf-r2.gcfund.dc.domain: 36964+ PTR? 228.0.168.192.in-addr.arpa. (44)
03:17:34.304618 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [S], seq 2040816294, win 14600, options [mss 1460,sackOK,TS val 133546 ecr 0,nop,wscale 7], length 0
03:17:34.304805 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [.], ack 1474200914, win 115, options [nop,nop,TS val 133546 ecr 88916281], length 0
03:17:34.304984 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [P.], seq 0:66, ack 1, win 115, options [nop,nop,TS val 133546 ecr 88916281], length 66
03:17:34.306036 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [.], ack 23, win 115, options [nop,nop,TS val 133547 ecr 88916282], length 0
03:17:34.306480 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [P.], seq 66:319, ack 23, win 115, options [nop,nop,TS val 133548 ecr 88916282], length 253
03:17:34.348054 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [.], ack 2919, win 160, options [nop,nop,TS val 133590 ecr 88916282], length 0
03:17:34.348247 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [.], ack 5815, win 205, options [nop,nop,TS val 133590 ecr 88916286], length 0
03:17:34.348260 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [.], ack 8711, win 250, options [nop,nop,TS val 133590 ecr 88916286], length 0
03:17:34.348335 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [.], ack 10158, win 273, options [nop,nop,TS val 133590 ecr 88916286], length 0
03:17:34.357254 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [P.], seq 319:363, ack 10158, win 273, options [nop,nop,TS val 133599 ecr 88916286], length 44
03:17:34.357284 IP owncloud01.gcfund.dc.38874 > gcf-r2.gcfund.dc.ldap: Flags [F.], seq 363, ack 10158, win 273, options [nop,nop,TS val 133599 ecr 88916286], length 0
03:17:56.146221 ARP, Request who-has gcf-r2.gcfund.dc tell g-gujabidze.gcfund.dc, length 46
03:17:56.146384 IP owncloud01.gcfund.dc.45985 > gcf-r2.gcfund.dc.domain: 35993+ PTR? 212.0.168.192.in-addr.arpa. (44)
03:18:01.141665 ARP, Reply owncloud01.gcfund.dc is-at 00:0c:29:d3:22:77 (oui Unknown), length 28
03:18:18.461943 ARP, Request who-has gcf-r2.gcfund.dc tell tjokhadze-hp.gcfund.dc, length 46
03:18:18.462134 IP owncloud01.gcfund.dc.56981 > gcf-r2.gcfund.dc.domain: 63014+ PTR? 84.0.168.192.in-addr.arpa. (43)
03:18:23.141884 ARP, Reply owncloud01.gcfund.dc is-at 00:0c:29:d3:22:77 (oui Unknown), length 28
03:18:27.464951 ARP, Request who-has gcf-r2.gcfund.dc tell 192.168.0.23, length 46
03:18:27.465114 IP owncloud01.gcfund.dc.47264 > gcf-r2.gcfund.dc.domain: 26529+ PTR? 23.0.168.192.in-addr.arpa. (43)
03:18:27.940464 ARP, Request who-has gcf-r2.gcfund.dc tell 192.168.0.101, length 46
03:18:27.940640 IP owncloud01.gcfund.dc.35015 > gcf-r2.gcfund.dc.domain: 13963+ PTR? 101.0.168.192.in-addr.arpa. (44)
03:18:39.661520 ARP, Request who-has gcf-r2.gcfund.dc tell 192.168.0.74, length 50
03:18:39.661730 IP owncloud01.gcfund.dc.34654 > gcf-r2.gcfund.dc.domain: 56135+ PTR? 74.0.168.192.in-addr.arpa. (43)
03:18:40.517004 ARP, Request who-has gcf-r2.gcfund.dc tell meetingroom.gcfund.dc, length 46
03:18:40.517182 IP owncloud01.gcfund.dc.56841 > gcf-r2.gcfund.dc.domain: 60001+ PTR? 167.0.168.192.in-addr.arpa. (44)
03:18:40.885838 ARP, Request who-has gcf-r2.gcfund.dc tell 192.168.0.106, length 46

**Comment by ggujabidze** [comment]
As I said before, on LDAP configuration, when I push the button Verify setting and count user (after I narrow search with group filter) it gives me green message and text 45 users found, it also bring all the windows groups available in ldap directory, after I made changes suggested by blizzz, I also was able to successfully verify test loginname, it bring message user found and settings verified. But I can not logon with my ldap user, neither see my ldap users list  :(

**Comment by ggujabidze** [comment]
OK, here is the more verbose dump, filtered also via destination port - 389, I'm not an Ace of TCP protocol, but I guess the checksums are incorrect/damaged somehow.

tcpdump -i ens160 dst port 389 -vv
tcpdump: listening on ens160, link-type EN10MB (Ethernet), capture size 65535 bytes
03:42:13.351009 IP (tos 0x0, ttl 64, id 1021, offset 0, flags [DF], proto TCP (6), length 60)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [S], cksum 0x833f (incorrect -> 0xc6a7), seq 4144601293, win 14600, options [mss 1460,sackOK,TS val 1612592 ecr 0,nop,wscale 7], length 0
03:42:13.351208 IP (tos 0x0, ttl 64, id 1022, offset 0, flags [DF], proto TCP (6), length 52)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [.], cksum 0x8337 (incorrect -> 0x9749), seq 4144601294, ack 3705581964, win 115, options [nop,nop,TS val 1612593 ecr 89064180], length 0
03:42:13.351234 IP (tos 0x0, ttl 64, id 1023, offset 0, flags [DF], proto TCP (6), length 118)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [P.], cksum 0x8379 (incorrect -> 0x1d3d), seq 0:66, ack 1, win 115, options [nop,nop,TS val 1612593 ecr 89064180], length 66
03:42:13.352760 IP (tos 0x0, ttl 64, id 1024, offset 0, flags [DF], proto TCP (6), length 52)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [.], cksum 0x8337 (incorrect -> 0x96f0), seq 66, ack 23, win 115, options [nop,nop,TS val 1612594 ecr 89064180], length 0
03:42:13.353222 IP (tos 0x0, ttl 64, id 1025, offset 0, flags [DF], proto TCP (6), length 305)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [P.], cksum 0x8434 (incorrect -> 0x17f5), seq 66:319, ack 23, win 115, options [nop,nop,TS val 1612595 ecr 89064180], length 253
03:42:13.395119 IP (tos 0x0, ttl 64, id 1026, offset 0, flags [DF], proto TCP (6), length 52)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [.], cksum 0x8337 (incorrect -> 0x8a4a), seq 319, ack 2919, win 160, options [nop,nop,TS val 1612637 ecr 89064181], length 0
03:42:13.395253 IP (tos 0x0, ttl 64, id 1027, offset 0, flags [DF], proto TCP (6), length 52)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [.], cksum 0x8337 (incorrect -> 0x7ec9), seq 319, ack 5815, win 205, options [nop,nop,TS val 1612637 ecr 89064185], length 0
03:42:13.395283 IP (tos 0x0, ttl 64, id 1028, offset 0, flags [DF], proto TCP (6), length 52)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [.], cksum 0x8337 (incorrect -> 0x734c), seq 319, ack 8711, win 250, options [nop,nop,TS val 1612637 ecr 89064185], length 0
03:42:13.395337 IP (tos 0x0, ttl 64, id 1029, offset 0, flags [DF], proto TCP (6), length 52)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [.], cksum 0x8337 (incorrect -> 0x6d8e), seq 319, ack 10158, win 273, options [nop,nop,TS val 1612637 ecr 89064185], length 0
03:42:13.403366 IP (tos 0x0, ttl 64, id 1030, offset 0, flags [DF], proto TCP (6), length 96)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [P.], cksum 0x8363 (incorrect -> 0x9ea5), seq 319:363, ack 10158, win 273, options [nop,nop,TS val 1612645 ecr 89064185], length 44
03:42:13.403389 IP (tos 0x0, ttl 64, id 1031, offset 0, flags [DF], proto TCP (6), length 52)
    owncloud01.gcfund.dc.39066 > gcf-r2.gcfund.dc.ldap: Flags [F.], cksum 0x8337 (incorrect -> 0x6d59), seq 363, ack 10158, win 273, options [nop,nop,TS val 1612645 ecr 89064185], length 0

**Comment by Xenopathic** [comment]
@ggujabidze Sorry, I won't be able to help you with your problem, you'd be best asking on the forums or on IRC. Please keep this PR for developer reviews

**Comment by ggujabidze** [comment]
@Xenopathic That's OK, anyways, thanks for you feedbacks. It's really too late in my timezone, so I have to backup my VM and go to sleep, as in couple hours my colleagues should be able to do their daily job and access their files located on ownCloud server.

Maybe someone also will face the same issue...

**Comment by blizzz** [comment]
@ggujabidze please see the issue https://github.com/owncloud/core/issues/20090 and, if this is what happens to you, testing the fix https://github.com/owncloud/core/pull/20192 would be helpfull

**Comment by blizzz** [comment]
> (on a side note, the yellow box for displaying success isn't very good, we should have an inline green box/message/tick that appears next to the verify button on success, like for change display name or email, @jancborchardt )

Open to changes like this, but not in a bugfix.

**Comment by ggujabidze** [comment]
@blizzz No, I think my case was a bit different, as I don't have any flagged for deletion users, neither in AD, not in ownCloud  :(  though I also had exactly that error message in my log, but there also was a lot of:

**Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-31T01:47:14+04:00"}**

And non-of my ldap users could log in, I only was able to logon with my local admin account and I said above, when I tried to go to the Users tab, only the rotating circle was appearing and nothing comes on front, as if there was some infinite loop in something like that. The strange thing is that, at first time I had "UserMapper was not assigned to this Access instance" problem, but after applying your fixes to the upgraded version, the "Test loginname" button started working. It can find user, it also returns the number of users which fall under my ldap filter but can not generate the userlist.

**Comment by ggujabidze** [comment]
Oh, and I forgot to say, that unfortunately I had to roll back new version on that night, as it'll be impossible to work on the next day. So I restored entire VM from my full backup :(

**Comment by blizzz** [comment]
@ggujabidze You can ignore ``Partial search results returned``. I am pretty sure the issues i linked to are correct, since you mention ``Call to undefined method OCA\user_ldap\lib\user\OfflineUser::processAttributes() at /var/www/html/owncloud/apps/user_ldap/lib/access.php#712``. Please try them. Otherwise, this is the totally wrong place here to  discuss it, so if they really does not solve your problem, please open a bug report using the [Issue Template](https://raw.github.com/owncloud/core/master/issue_template.md).

**Comment by blizzz** [comment]
Back to topic, any more reviewers? Maybe @alex42ka, @Takuto88, @MorrisJobke or others?

**Comment by ggujabidze** [comment]
@blizzz  Well... Actually I opend a bug according to your template, as soon as I faced to that. the bug number is  #20194, but it was closed by MorrisJobke minutes ago. Maybe it will help, I'm only saying that I had a different sympthoms, in hereby case, some user are still able to log in, in my case non of the users can and more over, there was no users in users list ( at least system could not give me that list).

Anyways, of course you can close this bug and when official update will be available, I'll try to upgrade my current version one more time.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by DeepDiver1975** [comment]
failing oracle unrelated

**Comment by blizzz** [comment]
Backport to stable8.2: #20241 

Backport to 8.1 is unnecessary, because we have other hardenings on board that went in through more findings during testing compared to the original master PR review.

**Pull request merged**
