### PR TITLE
[Stable10] Increasing timeout for encryption integration tests in jenkins

### PR DESCRIPTION
**Pull request by SergioBertolinSG**

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by SergioBertolinSG** [comment]
Error in jenkins:
```
Test execution failed: java.lang.NullPointerException: Cannot invoke method startsWith() on null object
```

I'll try something, but maybe we have to use the testResultLocation variable (or add another one).

**Comment by SergioBertolinSG** [comment]
OK env.STAGE_NAME doesn't seem to work, @PVince81 do you know any way to get stage name?

If not, it is ok to you to use the report filename as condition to increase timeout?

**Comment by PVince81** [comment]
@SergioBertolinSG I don't know much about Jenkinsfile. Please research this yourself, unless @DeepDiver1975 has a clue.

**Pull request merged**
