### PR TITLE
[stable10] Wording change

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Backport of https://github.com/owncloud/core/pull/30773 to stable10

## Related Issue
https://github.com/owncloud/core/issues/29526

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
:-1: for backporting this. We will loose all translations.

**Comment by PVince81** [comment]
@DeepDiver1975 this was never released before and is post 10.0.7. The original text was backported too when we added these options, so the same problem applies ?

**Comment by DeepDiver1975** [comment]
> so the same problem applies ?

yes

**Review by PVince81 — APPROVED** [review]
ok then... let's move this forward :+1:

**Pull request merged**
