### PR TITLE
Addin caldav test suite for old endpoint

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
The legacy caldav and carddav endpoints stopped working in oc10.

## Related Issue
#27778

## How Has This Been Tested?
- [x] caldav and carddav test suite
- [x] manual testing

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2017-05-04 12-29-33

**Comment by neandrethal** [comment]
Hello,
DeepDiver1975. Thank you for diving into the problem. I'd like to test the patch but could you please describe procedure for applying it? I am new here, I am not familiar with php and I do not like to do something wrong and destroy my system.
If there is any description, send me a link please.

**Comment by DeepDiver1975** [comment]
> I am new here, I am not familiar with php and I do not like to do something wrong and destroy my system.

easiest would be if you have a owncloud test installation which is installed from git directly.

alternative would be to download all files manually and apply them. you can ignore the travis.yml as well as all sh and xml files

**Comment by neandrethal** [comment]
Thank you. Now everything seam to work fine for me.
Should I close #27778 issue?

**Comment by neandrethal** [comment]
OK, thank you.

**Pull request merged**
