### PR TITLE
Prevent stored mail settings password from get shown in the ui

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Security: Prevent stored mail settings password from showing in the webUI

## Related Issue

- Fixes [issues/5035](owncloud/security-tracker#379)

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToRoot1-10.8.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34764/104/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIManageQuota-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34764/132/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic2-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34764/148/1

**Comment by phil-davis** [comment]
I added a UI test scenario that sets those mail credentials, reloads the page, checks that they are set in config.php, but that the mail credentials password is not sent back to the UI. It fails on current master and passes with the code in this PR.

**Review by phil-davis — COMMENTED** [review]
LGTM - works

**Comment by JanAckermann** [comment]
@phil-davis THX, unfortunately I re-requested your review

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
