### PR TITLE
Add security check when updating the permissions of a federated share

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
This fixes a security issue where a federated share recipient could increase permissions on his share. We now limit the permission updates to federated re-shares only.

More detailed explanation of the problem: https://github.com/owncloud/enterprise/issues/4537#issuecomment-832577146
Steps to reproduce: https://github.com/owncloud/enterprise/issues/4537#issue-874550227

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/4537

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JammingBen** [comment]
I'm not a 100% sure about this solution, just started digging into this whole federated thing... either way this needs heavy testing. The more federated servers and shares, the better.

**Comment by C0rby** [comment]
So this does fix the security issue. I'm just not sure if that is best/correct fix.
Someone with more OC10 experience should review this.

**Review by jvillafanez — COMMENTED** [review]
code wise it looks fine, just a little detail

**Review by jvillafanez — APPROVED** [review]
I'm assuming this is the solution we want

**Review by C0rby — APPROVED** [review]

**Pull request merged**
