### PR TITLE
adjust style of triangle and caret icons

### PR DESCRIPTION
**Pull request by jancborchardt**
Before, strangely long triangles:
capture du 2015-08-25 15-44-06
After, nicer:
capture du 2015-08-25 15-43-41

Please review @owncloud/designers

### CODE REVIEW

**Comment by karlitschek** [comment]
indeed nicer :+1:

**Comment by PVince81** [comment]
Looks nice :+1:

**Comment by jancborchardt** [comment]
DONT MERGE, I didn’t compress the images yet!

**Comment by jancborchardt** [comment]
Compressed now – merging cause it’s just an image change.

**Comment by MorrisJobke** [comment]
Nice :+1:

**Pull request merged**
