### PR TITLE
Get user home folder before deletion

### PR DESCRIPTION
**Pull request by PVince81**
## Description
After the deletion getHome() will fail because the user doesn't exist
any more, so we need to fetch that value earlier.

## Related Issue
Discovered while looking into https://github.com/owncloud/core/pull/26846

## How Has This Been Tested?
Fix was tested by applying it on top of https://github.com/owncloud/core/pull/26846.
To test manually, use the MD5 getHome hack from 67dbcdc3b841d9c3d5eb9a7c1ce578a7ceef5e91, then delete a user who has already logged in once.
Before the fix: home folder (md5) is not correctly deleted.
After the fix: home folder (md5) is still deleted.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Please review @owncloud/qa @butonic @DeepDiver1975 @VicDeo

### CODE REVIEW

**Comment by PVince81** [comment]
Note that this might not be reproducible in LDAP cases because for LDAP the user is rather deleted from within LDAP. It could happen however than after the LDAP user becomes a "remnant", deleting using `occ user:delete` will not delete the home folder when LDAP uses the "home directory rule" approach.

Would be good to test that manually too @davitol @SergioBertolinSG

**Comment by PhilippSchaffrath** [comment]
Besides what @PVince81 mentioned about possible LDAP problems: :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/27492

**Pull request merged**
