### PR TITLE
Style of acceptance test string concatenation

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Adjust the style of string concatenation in places that I found.

## Motivation and Context
Review comment https://github.com/owncloud/core/pull/29773#discussion_r209946744

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [x] Code changes

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
@individual-it @DeepDiver1975 please comment - what is the project "standard" for forming strings in PHP?

**Comment by DeepDiver1975** [comment]
Benefits in Performance and memory consumption are to be ignored when comparing string concat vs string Interpolation.
I find Interpolation nicer to read.

**Comment by phil-davis** [comment]
@DeepDiver1975 do the style of changes I made here match the style you would like to have?
If yes, then approve this PR.
If no, the mention what could be different (e.g. maybe I went too far putting some things inline with ``"folder/{$varXyz['key']}/stuff"`` type of syntax)

**Comment by phil-davis** [comment]
@DeepDiver1975 @individual-it comments or approval please.

**Review by individual-it — APPROVED** [review]
I like concatenation more, but lets not get blocked by that and just define this as standard and get on with work

**Comment by phil-davis** [comment]
Backport ``stable10`` #32393

**Pull request merged**
