### PR TITLE
ignore encryption keys for propagation

### PR DESCRIPTION
**Pull request by icewind1991**
no need to have things like etags and mtimes propagator there

For #18359

cc @PVince81 @schiesbn

### CODE REVIEW

**Comment by PVince81** [comment]
Interesting approach. Let me test it.

**Comment by PVince81** [comment]
Tested, works :+1: 

@icewind1991 I guess this won't be backportable because it requires the new storage API ?

Second reviewer ? @nickvergessen @schiesbn @DeepDiver1975

**Comment by icewind1991** [comment]
> @icewind1991 I guess this won't be backportable because it requires the new storage API ?

Yes, 8.2 would require a separate approach

**Comment by LukasReschke** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
````
14:28:10 There was 1 error:
14:28:10 
14:28:10 1) Test_DBSchema::testSchema
14:28:10 Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT alc.constraint_name,
14:28:10           alc.DELETE_RULE,
14:28:10           alc.search_condition,
14:28:10           cols.column_name "local_column",
14:28:10           cols.position,
14:28:10           r_alc.table_name "references_table",
14:28:10           r_cols.column_name "foreign_column"
14:28:10      FROM user_cons_columns cols
14:28:10 LEFT JOIN user_constraints alc
14:28:10        ON alc.constraint_name = cols.constraint_name
14:28:10 LEFT JOIN user_constraints r_alc
14:28:10        ON alc.r_constraint_name = r_alc.constraint_name
14:28:10 LEFT JOIN user_cons_columns r_cols
14:28:10        ON r_alc.constraint_name = r_cols.constraint_name
14:28:10       AND cols.position = r_cols.position
14:28:10     WHERE alc.constraint_name = cols.constraint_name
14:28:10       AND alc.constraint_type = 'R'
14:28:10       AND alc.table_name = 'oc_storages'
14:28:10  ORDER BY alc.constraint_name ASC, cols.position ASC':
14:28:10 
14:28:10 Execution aborted after 15 minutes
14:28:10 
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:119
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:836
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:766
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:319
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:284
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:268
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/mdb2schemawriter.php:56
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php:57
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db.php:161
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/dbschema.php:74
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/dbschema.php:57
14:28:10 
14:28:10 Caused by
14:28:10 PHP_Invoker_TimeoutException: Execution aborted after 15 minutes
14:28:10 
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:212
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:116
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:833
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:183
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:766
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:319
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:284
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:268
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/mdb2schemawriter.php:56
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/mdb2schemamanager.php:57
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db.php:161
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/dbschema.php:74
14:28:10 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/lib/dbschema.php:57
14:28:10 
14:28:10 --
14:28:10 
14:28:10 There were 201 skipped tests:

**Comment by DeepDiver1975** [comment]
This oracle issue seems unrelated ....

**Comment by schiesbn** [comment]
This will fail if the admin changed the root of the encryption keys, which is possible since oC 8.2 as some kind of "key-storage light".

In general I would prefer not to have a per-app or per-folder exception but a more general rule to skip etag propagation for everything outside `data/<user>/files`. Nothing outside the files directory needs a etag.

**Pull request merged**
