### PR TITLE
[stable9.1] Just use moment to comupte the time left for the upload - translation…

### LINKED ISSUE #26804: Upload progress bar: wrong plural for German translation
In the upload progress bar, German words use wrong plural.

**Wrong:**
Sekunde ==> Sekundes
Minute ==> Minutes
Stunde ==> Stundes

image001

**Correct:**
Sekunde ==> Sekunden
Minute ==> Minuten
Stunde ==> Stunden

### Steps to reproduce
1. Install 9.1.2
2. Login and switch language to "German" on Personal page
3. Upload large file

### Expected behaviour
German UI should have correct plural.

### Actual behaviour
German UI has incorrect plural.

### Server configuration

**ownCloud version:** (see ownCloud admin page)
9.1.2

**Where did you install ownCloud from:**

Docker:
https://hub.docker.com/_/owncloud/

00006728

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…s are delivered as part of moment.js - fixes #26804

backport #26839

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@PVince81 should we kill the removed strings from the translation files as well?

**Comment by PVince81** [comment]
@DeepDiver1975 makes sense, but doesn't that happen automatically anyway ? Maybe not for backports though.

**Comment by DeepDiver1975** [comment]
> Maybe not for backports though.

yes - not for the backports ....

**Comment by PVince81** [comment]
:+1: still works

**Pull request merged**
