### PR TITLE
Create new DB index and add new condition

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
speed up searches in the addressbook in large setups

## Related Issue
https://github.com/owncloud/enterprise/issues/4655

## How Has This Been Tested?
Manually tested with 2 federated servers with around 1000 users each.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31350/113/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-10.6.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31354/115/1

**Comment by JammingBen** [comment]
LGTM code-wise.

SonarCloud complains about the code coverage though because the migration file is not tested. IMO migration files should not be unit-tested, but I've seen some (core-) apps do it...

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31792/115/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31792/114/1

**Comment by mrow4a** [comment]
@jvillafanez isnt there already one https://github.com/owncloud/core/pull/37152 ?

**Comment by jvillafanez** [comment]
The index isn't being used properly in that particular query. You can check some research in https://github.com/owncloud/enterprise/issues/4655#issuecomment-878239622

The checked performance is described in https://github.com/owncloud/enterprise/issues/4655#issuecomment-880052549

**Comment by mrow4a** [comment]
@jvillafanez in fact I proposed the index you have in this PR long time ago (https://github.com/owncloud/core/pull/30195#issuecomment-367671125) but it was rejected at a time , with prefered one also on value. I guess then we need both..

**Review by mrow4a — APPROVED** [review]

**Comment by jvillafanez** [comment]
Definitely we should have a usable index on the value, but the problems are the case insensitive search and the substring search. I don't think we can do much more without restricting the query, which would remove part of the current functionality, or adding new tables oriented to index this one.

**Comment by jvillafanez** [comment]
Rebased and tests added. The migration has been moved to the dav app.

**Review by mrow4a — APPROVED** [review]

**Review by JammingBen — APPROVED** [review]

**Review by AlexAndBear — CHANGES_REQUESTED** [review]

**Review by AlexAndBear — APPROVED** [review]

**Pull request merged**
