### PR TITLE
[Stable7] Fix "Only variables should be passed by reference" in stable7 template

### LINKED ISSUE #13751: Only variables should be passed by reference
when trying to install i get:

	Array
	(
		[app] => PHP
		[message] => Only variables should be passed by reference at \/usr\/share\/webapps\/owncloud\/7.0.4\/htdocs\/lib\/private\/template.php#287
		[level] => 3
		[time] => 2015-01-28T20:39:53+00:00
	)

where row 287 is the getHint() row in

      } else {
         $hint = '';
         if ($exception instanceof \OC\HintException) {
            $hint = OC_Util::sanitizeHTML($exception->getHint());
         }
      }

sending the result of a function to a function that takes a reference

    public static function sanitizeHTML( &$value )

in /usr/share/webapps/owncloud/7.0.4/htdocs/lib/private/util.php:975

same as #13296 ?

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #13751 

@LukasReschke we should get rid of the stupid reference one day
@DeepDiver1975 @puggan @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by LukasReschke** [comment]
Makes sense. Yes – we should also get rid of that bloody reference thing :+1: – See https://github.com/owncloud/core/issues/14643

**Comment by MorrisJobke** [comment]
@nickvergessen Is this stable7 only?

**Comment by nickvergessen** [comment]
Yes, couldn't find that code in 8 or master

**Pull request merged**
