### PR TITLE
Use custom attribute instead of the div identifier

### PR DESCRIPTION
**Pull request by LukasReschke**
Otherwise problems arrive when a username contains characters such as an `@`

Fixes https://github.com/owncloud/user_shibboleth/issues/38

@nickvergessen @DeepDiver1975

### CODE REVIEW

**Comment by nickvergessen** [comment]
Works here, can we add a test for this somehow, in the test file you edited?

**Comment by LukasReschke** [comment]
> Works here, can we add a test for this somehow, in the test file you edited?

There is a test?

**Comment by LukasReschke** [comment]
Ah you mean with @ … well we can do but it won't help much :P

**Comment by LukasReschke** [comment]
(as the only dangerous characters here are " and ' )

**Comment by nickvergessen** [comment]
hmm yeah I mean like sharing the item with a user and then check whether it works, just to make sure that if someone changes it back, it still works, or at least he sees, oh something special about `@`?

Anyway, :+1: from me

**Comment by DeepDiver1975** [comment]
tested :+1:

**Comment by DeepDiver1975** [comment]
I question where stuff like that can explode as well ....

**Comment by DeepDiver1975** [comment]
backport to stable8 please - THX

**Comment by karlitschek** [comment]
Yes. Definitely backport

**Comment by LukasReschke** [comment]
I'd love to backport. However I'm pretty sure that is a feature available in master only? :confused:

**Comment by LukasReschke** [comment]
> {"installed":true,"maintenance":false,"version":"8.0.0.9","versionstring":"8.0","edition":"Enterprise"}

@karlitschek Maybe we should change the version in master again just to see directly if it is master or stable8?

**Comment by PVince81** [comment]
I believe this is master only, 8.1.

Isn't it, @rullzer ?

**Comment by rullzer** [comment]
Yep only in 8.1 as far as I know

**Pull request merged**
