### PR TITLE
[stable9.1] Setupfs before access a users keys

### PR DESCRIPTION
**Pull request by DeepDiver1975**
port of https://github.com/owncloud/core/pull/26820

### CODE REVIEW

**Comment by PVince81** [comment]
Cherry-picked the additional commit

**Comment by PVince81** [comment]
Looks like we still have some unit test failures.

Automated tests will be added as part of https://github.com/owncloud/core/pull/26844.
I could already confirm that some tests had failed with alternate home + encryption and this PR here solves them.

**Comment by PVince81** [comment]
Cherry-picked additional test fixes from the master branch.

@jvillafanez please review

**Comment by PVince81** [comment]
Argh, need to replace `createMock` with `getMock`. Will do...

**Comment by PVince81** [comment]
Okay, should be good to go now.

**Comment by jvillafanez** [comment]
👍

**Comment by PVince81** [comment]
Let's wait before merging. Need to investigate this (not-so-critical-but-still) regression https://github.com/owncloud/core/issues/26935

**Comment by PVince81** [comment]
```
Parse error: ./tests/lib/Encryption/Keys/StorageTest.php:72

    70| 			->getMock();

    71| 

  > 72| 		$user = $this->getMock(IUser::class);

    73| 		$user->method('getUID')->willReturn('user1');

    74| 		$userSession = $this->getMock(IUserSession::class);

Unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
```

I'll adjust this later when rebasing.

**Comment by PVince81** [comment]
- [ ] TODO: fix unit test syntax error
- [ ] TODO: cherry-pick the regression fix: https://github.com/owncloud/core/pull/26938
- [ ] TODO: cherry-pick the other relevant fix about alternative home dir: https://github.com/owncloud/core/pull/26937

**Comment by felixboehm** [comment]
fix works fine in my production environment

**Comment by PVince81** [comment]
Need rereview, I cherry-picked backports of master to fix a regression and incomplete cases.

**Comment by jvillafanez** [comment]
My only worry is that this should be done after deleting the user. If the user isn't deleted, we'd already have deleted the keys with the current code.

Maybe if the keys are stored in the user's home and we can't access to it, we could suppose the keys are already deleted. If they're stored elsewhere we can delete them without problem after the user is deleted.

**Comment by PVince81** [comment]
Hmm, then I should revert https://github.com/owncloud/core/pull/26938 and find a better way

**Comment by PVince81** [comment]
- [ ] revert preDelete fix and find a better solution
- [ ] fix PHP 5.4 syntax error
```
Parse error: ./tests/lib/Encryption/Keys/StorageTest.php:296

    294| 			->willReturn(true);

    295| 

  > 296| 		$user = $this->createMock(IUser::class);

    297| 		$user->method('getUID')->willReturn('user1');

    298| 		$userSession = $this->createMock(IUserSession::class);

Unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
```

**Comment by PVince81** [comment]
@jvillafanez please review https://github.com/owncloud/core/pull/26968 with an alternative solution to the preDelete problem. Have to revert and refix on master before I can cherry-pick the new solution here.

**Comment by PVince81** [comment]
Rebased and removed the "preDelete" commit and cherry-picked the better fix from https://github.com/owncloud/core/pull/26968

**Comment by PVince81** [comment]
After all these additions, let's retest this:
- [ ] TEST: sharing with alt home works
- [ ] TEST: delete user works with no warnings
- [ ] TEST: delete user works with no warnings when using alternative key storage

**Comment by PVince81** [comment]
- [ ] backport the integration tests from https://github.com/owncloud/core/pull/26844

**Comment by PVince81** [comment]
```
Parse error: ./tests/lib/Encryption/Keys/StorageTest.php:296

    294| 			->willReturn(true);

    295| 

  > 296| 		$user = $this->createMock(IUser::class);

    297| 		$user->method('getUID')->willReturn('user1');

    298| 		$userSession = $this->createMock(IUserSession::class);

Unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

```

😢

**Comment by PVince81** [comment]
Integrations test backport pending to be merged https://github.com/owncloud/core/pull/26976

**Comment by jvillafanez** [comment]
Changes look good 👍

**Pull request merged**
