### PR TITLE
Add email option to user:add command

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
In the `user:add` command you can now specify the email for a user.

I would consider this a regression in functionality, assigned 10.0.3 to reintroduce this feature.

## Related Issue
https://central.owncloud.org/t/setting-email-with-occ-doesnt-show-in-gui/7987/3

## Motivation and Context
Now that emails are stored in the accounts table there is no way to set the email of a user via occ. Since it is metadata stored alongside users in the accounts table I thought it made sense to add this to the user:add command.

## How Has This Been Tested?
Local command line.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [] I have updated the documentation accordingly. https://github.com/owncloud/documentation/issues/3152#issuecomment-308095641
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Fine by me 👍 

@tomneedham was this removed on purpose ? Any link to the diff/PR that removed this option ?

Would like to hear from @DeepDiver1975 if it was on purpose.

**Comment by tomneedham** [comment]
My guess was that since we used to have email in the preferences table, we never added this to the user add command after the accounts table was added. Unless I missed this getting removed...

**Comment by tomneedham** [comment]
(You used to be able to run ./occ user:setting email --value=$email)

**Comment by tomneedham** [comment]
jenkins died from mysql/docker issues....

**Comment by PVince81** [comment]
@tomneedham rebase it ~~to death~~ until it works

**Comment by tomneedham** [comment]
I'm going to script this at some point:
 - curl github PR api and get CI status
 - curl jenkins console | grep 'mysql timeout'
 - git rebase origin/master && git push -f origin $branch

-.-

**Comment by PVince81** [comment]
if you do, make sure to give the script a violent name like "kick-jenkins", "hit-jenkins-in-the-face" or so

**Comment by tomneedham** [comment]
kicked

**Comment by PVince81** [comment]
rebased 🔨

**Review by PVince81 — APPROVED** [review]

**Comment by PVince81** [comment]
rebased 🔨 

@tomneedham can you raise the backport PR to stable10 ?

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/issues/28306

**Pull request merged**
