### PR TITLE
Fix setup config namespace

### PR DESCRIPTION
**Pull request by PVince81**
Fixes the broken unit tests on master.

@LukasReschke @DeepDiver1975 @icewind1991 @nickvergessen

### CODE REVIEW

**Comment by PVince81** [comment]
This happened because https://github.com/owncloud/core/pull/13733 (tests passing) was merged at the same time as https://github.com/owncloud/core/pull/14416/files#diff-98f9881af7a7dfc6011f6e2b2dfe7c9fR37 (tests passing too), but one changes the namespace and Jenkins couldn't notice unless we'd have re-run it on the former PR.

Anyway, please review.

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
THX for fixing!

**Pull request merged**
