### PR TITLE
Queries on the cards table by uri require the addressbook as well

### LINKED ISSUE #22284: federated share auto complete shows wrong user
Steps to reproduce:

- setup two instances
- create on both instances a user with the same user name (let's say "user1")
- enable federation and make sure that the address books are synced
- try to share a file with user1

Expected behavior:

The auto-complete should show two user1, once the local one and once the user on the second server

Actual result:

At first it looks good, you see "user1" and "user1 (remote)" but if you share with "user1 (remote)" you see that it will be shared again with the local user1, just as a remote share

Looks like by removing duplicates we remove the exactly wrong user in this case... @DeepDiver1975 can you have a look at this?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #22284 

@schiesbn @PVince81 @rullzer THX

### CODE REVIEW

**Comment by nickvergessen** [comment]
Looks good :+1:

**Comment by nickvergessen** [comment]
Tests fail:
```
14:14:22 OCA\DAV\Tests\Unit\CardDAV\CardDavBackendTest::testGetCardId
14:14:22 Missing argument 2 for OCA\DAV\CardDAV\CardDavBackend::getCardId()

14:14:22 2) OCA\DAV\Tests\Unit\CardDAV\CardDavBackendTest::testGetCardIdFailed
14:14:22 Missing argument 2 for OCA\DAV\CardDAV\CardDavBackend::getCardId()
```

**Comment by DeepDiver1975** [comment]
bloody invokePrivate ...

**Comment by DeepDiver1975** [comment]
@schiesbn please test - THX

**Comment by schiesbn** [comment]
works now... :+1:

**Comment by DeepDiver1975** [comment]
> works now... :+1:

THX

**Pull request merged**
