### PR TITLE
[stable10] update version information in Makefile

### PR DESCRIPTION
**Pull request by patrickjahns**
## Description
Push the responsibility of generating `version.php` into Makefile

## Related Issue
Resurrected https://github.com/owncloud/core/pull/27945

## Motivation and Context
A `make dist`//`make dist-qa` should be able to generate a core with all required information

## How Has This Been Tested?
- ✋ -> generated a release dir via `RELEASE_CHANNEL=testing RELEASE_EDITION=daily make dist-dir`
Result:

```
cat build/dist/owncloud/version.php 
<?php
/**
 * @author Frank Karlitschek <frank@karlitschek.de>
 * @author Ilja Neumann <ineumann@owncloud.com>
 * @author Joas Schilling <coding@schilljs.com>
 * @author Lukas Reschke <lukas@statuscode.ch>
 * @author Vincent Petry <pvince81@owncloud.com>
 *
 * @copyright Copyright (c) 2018, ownCloud GmbH
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */
// We only can count up. The 4. digit is only for the internal patchlevel to trigger DB upgrades
// between betas, final and RCs. This is _not_ the public version number. Reset minor/patchlevel
// when updating major/minor version number.
$OC_Version = [10, 2, 0, 0];

// The human readable string
$OC_VersionString = '10.2.0 prealpha';

$OC_VersionCanBeUpgradedFrom = [[8, 2, 11],[9, 0, 9],[9, 1]];

// The ownCloud channel
$OC_Channel = 'testing';

// The build number
$OC_Build = '2019-04-09T14:50:19+00:00 1eef291da8a77e724bc733069fc78f5127da718f';

// Vendor of this package
$vendor = 'owncloud';

$OC_Edition = 'daily';

```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)
- [x] Release scripting

## Checklist:
- not applicable

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
in what way is it cleaner ? because it strips the comments ?

the trouble with the old release script was that it was trying to parse the PHP and evaluate it. I remember one time where the build failed when we switched to square brackets for arrays and the build server still had PHP 5.4.

I'm unsure about the best approach here. If in doubt, we could keep the old approach for now.

**Comment by PVince81** [comment]
let's delay this to 10.3

**Comment by DeepDiver1975** [comment]
@patrickjahns we still need this? Can you please resolve the conflicts? THX

**Comment by patrickjahns** [comment]
currently not required - might need a look in the future from someone else

**Pull request closed without merging**
