### PR TITLE
Update changelog post sprint 52

### PR DESCRIPTION
**Pull request by PVince81**
@micbar FYI

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
@micbar is changing to https://github.com/owncloud/core/blob/master/changelog/README.md
and there are already some entries in https://github.com/owncloud/core/tree/master/changelog/unreleased
and PR #36261 ...

**Comment by PVince81** [comment]
ah, I didn't know the process changed. Then I'll leave this up to @micbar to update the changelog when he's back next week.

as far as I understand, developers should create those new files with each PRs but if they don't then the release manager needs to do this after the fact manually

**Comment by PVince81** [comment]
maybe we need a script or an extension for gen_changelog.sh that automatically creates such files then...

**Comment by phil-davis** [comment]
And currently people have been naming the file in `changelog/unreleased` using the PR number. It is not possible to do that in the first submission of a PR, because locally you do not know the PR number until after you push the branch and submit the PR. It would be easier to use the issue number (assuming there is an issue)

**Comment by phil-davis** [comment]
@PVince81 out-of-date, close?

**Pull request closed without merging**
