### PR TITLE
Update scanFile() and scanChildren() to the new signature of the parent ...

### LINKED ISSUE #14681: Internal Server Error after attempting to do "occ files:scan"
Hello,
After upgrading to latest ownCloud version (8.0.0 or 8.0.1) the files for various users no longer appears. All passwords worked normally and the ownCloud instance otherwise responded normally.

In attempting to resolve the issue by running "occ files:scan --all" the ownCloud instance now responds with an "Internal Server Issue".

The server logs report the following:

	{"reqId":"VPa8kse8zJwAAxPulDwAAAAB","remoteAddr":"[[[MY IP]]]","app":"PHP","message":"Declaration of OC\\Files\\ObjectStore\\NoopScanner::scanFile() should be compatible with OC\\Files\\Cache\\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL) at [[[WEBROOT]]]\/owncloud\/lib\/private\/files\/objectstore\/noopscanner.php#74","level":3,"time":"March 04, 2015 03:04:34","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
	{"reqId":"VPa8kse8zJwAAxPulDwAAAAB","remoteAddr":"[[[MY IP]]]","app":"PHP","message":"Declaration of OC\\Files\\ObjectStore\\NoopScanner::scanChildren() should be compatible with OC\\Files\\Cache\\Scanner::scanChildren($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1, $folderData = NULL) at [[[WEBROOT]]]\/owncloud\/lib\/private\/files\/objectstore\/noopscanner.php#74","level":3,"time":"March 04, 2015 03:04:34","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
	{"reqId":"VPa8sce8zJwAAxQyljkAAAGC","remoteAddr":"[[[MY IP]]]","app":"PHP","message":"Declaration of OC\\Files\\ObjectStore\\NoopScanner::scanFile() should be compatible with OC\\Files\\Cache\\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL) at [[[WEBROOT]]]\/owncloud\/lib\/private\/files\/objectstore\/noopscanner.php#74","level":3,"time":"March 04, 2015 03:05:05","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
	{"reqId":"VPa8sce8zJwAAxQyljkAAAGC","remoteAddr":"[[[MY IP]]]","app":"PHP","message":"Declaration of OC\\Files\\ObjectStore\\NoopScanner::scanChildren() should be compatible with OC\\Files\\Cache\\Scanner::scanChildren($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1, $folderData = NULL) at [[[WEBROOT]]]\/owncloud\/lib\/private\/files\/objectstore\/noopscanner.php#74","level":3,"time":"March 04, 2015 03:05:05","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"} 

What can I do to get rid of the message and restore the files?

All data still resides in the data folder for the respective users.

Thank you.

### PR DESCRIPTION
**Pull request by nickvergessen**
...class

Fix #14681 

@DeepDiver1975 should backport to stable8

@LukasReschke @butonic review please

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
@karlitschek backport?

**Comment by DeepDiver1975** [comment]
> @karlitschek backport?

yes - issue was reported against oc8

**Comment by DeepDiver1975** [comment]
@nickvergessen please open a backport pr - THX

**Comment by nickvergessen** [comment]
you guys where quick this time.
Will try if we can get a test for this to avoid it in the future and then backport both

**Comment by karlitschek** [comment]
yes. please backport

**Pull request merged**
