### PR TITLE
[stable10] Link to trusted domains docs in exception

### PR DESCRIPTION
**Pull request by ghost**
Backport of https://github.com/owncloud/core/pull/29689 as requested there by @mmattel 

Required documentation change is already backported: https://github.com/owncloud/documentation/pull/3587

### CODE REVIEW

**Comment by mmattel** [comment]
@PVince81 how can we restart drone to complete testing so it can be merged?

**Comment by PVince81** [comment]
I clicked and "Failed to restart your build". I suspect that Drone is still getting its brain surgery... Will check again next week.

**Comment by mmattel** [comment]
@PVince81 possible to take a look again ? Would like to get that completed

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase failed! Please rebase your pull request manually via the command line.

Error:
```Command '['git', 'clone', '--depth', '1', 'rebase', '/tmp/tmpxv4tzhmp']' returned non-zero exit status 128.```

**Comment by PVince81** [comment]
oh what the hell... merging

**Pull request merged**
