### PR TITLE
Fixed Issue 23316 - Invisible buttons should be visible

### PR DESCRIPTION
**Pull request by prisas**
Changed the style sheet for the Advanced settings and Delete icons as asked in issue #23316.
Re-uploaded as asked @MorrisJobke

### CODE REVIEW

**Comment by paurisa** [comment]
This contribution is MIT licensed.

**Comment by MorrisJobke** [comment]
Tested and works :+1: 

cc @Xenopathic @owncloud/designers @PVince81 @nickvergessen

**Comment by PVince81** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:  looks good

**Pull request merged**
