### PR TITLE
[stable9.1] Add transfer ownership integration tests (#26543)

### PR DESCRIPTION
**Pull request by PVince81**
Backport of new integration tests for transfer ownership https://github.com/owncloud/core/pull/26543 to stable9.1

@DeepDiver1975 @owncloud/qa

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] requires https://github.com/owncloud/core/pull/26623

**Comment by eshalp** [comment]
👍

**Comment by PVince81** [comment]
- [ ] requires https://github.com/owncloud/core/pull/26626 to properly detect the current failure

**Comment by jvillafanez** [comment]
What is the exit code in case an exception is thrown? Ideally it shouldn't overlap with anyone of ours.

**Comment by PVince81** [comment]
@jvillafanez currently it's always 1 in case of any error

**Comment by jvillafanez** [comment]
Should we open another issue to review the exit codes of all commands? Any plan to change the exit code of "Internal server error" or similar to other code?

**Comment by PVince81** [comment]
I don't see this as an urgent task to have separate codes so we could make a separate ticket.

Most important is to have something that is not 0 for automated testing.

**Comment by jvillafanez** [comment]
👍

**Pull request merged**
