### PR TITLE
[Proposal] Introduce locking RAII class

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Objects of this class acquire a lock on construction, and release the lock on destruction. This is the Resource Acquisition is Initialization pattern, heavily used in other OOP languages such as C++.

It aims to solve a problem with locks as written in #19242, where once a lock is acquired, if an exception occurs at some point then the lock will never be released again. With this class the problem is solved, since the lock is released as soon as the Lock object goes out of scope, like when an exception occurs and the stack unwinds.

Usage:

```
public function foobar() {
    $lock = new \OCP\Lock\Lock($lockingProvider, $path, $type);
    // do work now
    ...
} // $lock goes out of scope, lock is released.
```

cc @PVince81 @DeepDiver1975 @schiesbn @icewind1991

### CODE REVIEW

**Comment by icewind1991** [comment]
Please dont add classes in the OCP namespace, create an interface in OCP, with the implementation in OC (and we probably want a factory to)

**Comment by Xenopathic** [comment]
@icewind1991 I thought about using ILockingProvider as the factory; I'll change it to using a factory method + interface.

**Comment by karlitschek** [comment]
we should only add something to our public interface that is actually used somewhere. so please add the consumer of this API to the interface. without that :-1:

**Comment by Xenopathic** [comment]
@karlitschek OK, will do.

Any comments about the actual concept though?

**Comment by PVince81** [comment]
Busy with 8.2 stuff, sorry

**Comment by Xenopathic** [comment]
@DeepDiver1975 Please note that the linked issue is marked for 8.2, and this proposal would fix that cleanly (basically, without needing to catch exceptions *everywhere*)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Please note that the linked issue is marked for 8.2, and this proposal would fix that cleanly (basically, without needing to catch exceptions everywhere)

Sure - but I'm uncertain if RAII is a pattern we can use in PHP ... needs some deeper PHP insights, which I'm missing at the moment

**Comment by PVince81** [comment]
There is already a fix for the issue that is in the scope for 8.2 and that matches every other place where we fix it that we. Let's keep the new pattern in mind for 9.0.

**Comment by PVince81** [comment]
Probably nothing for 9.0 ? I'd set to backlog as this is more a research project

**Comment by Xenopathic** [comment]
I think the need for this has dropped, and introducing RAII is likely to be unpredictable in some strange convoluted way in PHP as @DeepDiver1975 pointed out -> closing

**Pull request closed without merging**
