### PR TITLE
Some user backends no not allow listing of users - we cannot sync the…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…se backends.
## Description
Without the capability to list user and to test if a user exists there is not much to be synced.

## Related Issue
https://github.com/owncloud/user_shibboleth/issues/167

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by davitol** [comment]
👎  Keeps failing

**Comment by DeepDiver1975** [comment]
stupid me - please retry - thx

**Comment by jvillafanez** [comment]
👍 for the code. I haven't tested it

**Comment by davitol** [comment]
👍 WFM

**Pull request merged**
