### PR TITLE
normalize path in getInternalPath

### LINKED ISSUE #21173: Owncloud Android App can't see Thumbnails of images located on some external storage in 8.2.1- 8.2.2 - 9.0.0
Steps to reproduce :

    Browse photo directories in external storage in Owncloud official app 1.9.0
        Only placeholder is shown
        Not Thumbnails in external storage on official android app - Works fine directly from web browser (Like Firefox)
        Thumbnails work fine out of the external storage on official android app
        Thumbnails work fine in external storage with Web browser

My external storage is just another local folder in the same owncloud's server

Expected behaviour : 

  There is a thumbnail.

Actual behaviour :

  Placeholder icon is shown

Operating system:

Debian Jessie (8.0)

Web server:
Apache

Database:
MySQL

PHP version:
5.6.14

ownCloud version: 8.2.1(stable) 

Owncloud log : 
`{"reqId":"qvwmBaQX\/gQVUzWPBpx5","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/Euro2008.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/Euro2008.png"}
{"reqId":"qvwmBaQX\/gQVUzWPBpx5","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/Euro2008.png"}
{"reqId":"qvwmBaQX\/gQVUzWPBpx5","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/Euro2008.png"}
{"reqId":"KxfNYjDs5j8L7qHjhX8D","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/FondEcranCroixSmartphoneSansPhoto.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/FondEcranCroixSmartphoneSansPhoto.png"}
{"reqId":"KxfNYjDs5j8L7qHjhX8D","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/FondEcranCroixSmartphoneSansPhoto.png"}
{"reqId":"KxfNYjDs5j8L7qHjhX8D","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/FondEcranCroixSmartphoneSansPhoto.png"}
{"reqId":"PfoWr48VV4NyRVJCDyhv","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/logo.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/logo.png"}
{"reqId":"PfoWr48VV4NyRVJCDyhv","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/logo.png"}
{"reqId":"PfoWr48VV4NyRVJCDyhv","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/logo.png"}
{"reqId":"CUZ+fj5crMxsSrxA6kG7","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/PtitCoeur.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:29+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/PtitCoeur.png"}
{"reqId":"CUZ+fj5crMxsSrxA6kG7","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:29+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/PtitCoeur.png"}
{"reqId":"CUZ+fj5crMxsSrxA6kG7","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:29+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/PtitCoeur.png"}
{"reqId":"C3fC8nRYyW+OxJYqPNd7","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/SmileyCoeur2.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/SmileyCoeur2.png"}
{"reqId":"C3fC8nRYyW+OxJYqPNd7","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/SmileyCoeur2.png"}
{"reqId":"C3fC8nRYyW+OxJYqPNd7","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/SmileyCoeur2.png"}
{"reqId":"0h45oTMfydQVuZWYy+32","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/WorldCup2010.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/WorldCup2010.png"}
{"reqId":"0h45oTMfydQVuZWYy+32","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/WorldCup2010.png"}
{"reqId":"0h45oTMfydQVuZWYy+32","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/WorldCup2010.png"}`

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #21173

please test @PVince81 @oparoz

supersedes https://github.com/owncloud/core/pull/24329

### CODE REVIEW

**Comment by oparoz** [comment]
All tests seem to pass, this seems to be a good solution. I'll need to test with Gallery to see if it has an impact, since there is a lot of duct tape to be able to retrieve the proper file.

**Comment by georgehrke** [comment]
rebased

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
I'm worried that it might interfered with https://github.com/owncloud/core/issues/21365

Maybe the normalization should use the flag that does not normalize UTF-8

**Comment by PVince81** [comment]
or use `trim($x, '7')` instead

**Comment by PVince81** [comment]
@oparoz did you get a chance to test this with gallery ?

@georgehrke please adjust and use the trim functions

**Comment by georgehrke** [comment]
AFAIK the double (or more) slashes were inside the string. `trim` will only cut of multiple slashes at the start and the end.

**Comment by PVince81** [comment]
@georgehrke then can you at least set $keepUnicode to true just to be sure ? See https://github.com/owncloud/core/blob/master/lib/private/Files/Filesystem.php#L771

**Comment by georgehrke** [comment]
done

**Comment by PVince81** [comment]
Thanks :+1: 

Did some testing with encryption and all still seem to work fine.

**Comment by PVince81** [comment]
@georgehrke can you backport to 9.0 and 8.2 ? Make sure to remove the "keepUnicode" bit as it didn't exist there :smile: 

CC @cmonteroluque @DeepDiver1975

**Comment by PVince81** [comment]
Rebased for CI

**Pull request merged**
