### PR TITLE
[stable8] Remove hacky Substring support for MSSQL

### PR DESCRIPTION
**Pull request by LukasReschke**
Substring() is not required for the core functionality and this allows us to get rid of a huge hack...

@DeepDiver1975 As discussed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@LukasReschke how critical is this with respect to 8.0.1 release?

I lack the time to test/review this - applies to prs against master etc as well - THX

**Comment by LukasReschke** [comment]
8.0.2 is fine for me - then we can schedule this together with the stable fixes. Deal?

**Comment by DeepDiver1975** [comment]
> Deal?

:moneybag:

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by PVince81** [comment]
I guess this can be merged now ? Not sure how to test, I just see that the same code as master was deleted, so :+1:

**Pull request merged**
