### PR TITLE
Hint to users to check spelling when they type in wrong fed cloud ids

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
Guide the users to also check their spelling - usually that is the issue not server down

## Related Issue
https://github.com/owncloud/core/issues/29494

## Motivation and Context
Users think the server is down but they typed it in wrong.

## How Has This Been Tested?
manually in UI

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
Looks a good idea. Text reads well to me.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport stable10 #30355

**Comment by PVince81** [comment]
Seems you missed an occurrence which I triggered while trying to reproduce this one: https://github.com/owncloud/core/blob/v10.0.8RC1/apps/federatedfilesharing/lib/FederatedShareProvider.php#L240

**Comment by PVince81** [comment]
To trigger the above, try sharing with "admin@localhost/unexist".

Not sure what code path triggers this PR

**Pull request merged**
