### PR TITLE
Updated the media type of some font types

### PR DESCRIPTION
**Pull request by oparoz**
There is an official media type for ttf and otf fonts since early 2013
https://www.iana.org/assignments/media-types/application/font-sfnt

Since this is only used internally, it shouldn't be a problem to update it

I've also added Type1 font support
Tests are provided and the RepairMimeTypes class has been updated as well and needs reviewing.

### CODE REVIEW

**Comment by oparoz** [comment]
cc @georgehrke  @jancborchardt

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by jancborchardt** [comment]
So in case an existing file is `application/x-font-ttf` (the type you removed), it will still work? That’s the only potential problem I can see here.

**Comment by oparoz** [comment]
@jancborchardt - Yes, that's what the upgrade script is taking care of.

**Comment by georgehrke** [comment]
Looks good to me as well :+1:

**Comment by MorrisJobke** [comment]
two :+1: and succeeding test -> merge

**Pull request merged**
