### PR TITLE
Move federated cloud sharing, files externals and updater to special pos...

### PR DESCRIPTION
**Pull request by nickvergessen**
...itions

@jancborchardt @karlitschek @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
Sweet!  :+1:

**Comment by DeepDiver1975** [comment]
bad ux :-1:

**Comment by DeepDiver1975** [comment]
@jancborchardt rebase please

**Comment by jancborchardt** [comment]
Rebasing needs to be done by @nickvergessen who also needs to fix the problem that the updater app is not shown in the sidebar. ;)

**Comment by jancborchardt** [comment]
:+1: works nicely! Just rebase and we’re good.

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
Jenkins PR: #15281

**Comment by jancborchardt** [comment]
@nickvergessen plz fix the test failures so we can get this in. :)

**Comment by MorrisJobke** [comment]
@jancborchardt last test failure was due to the github DDoS

**Comment by MorrisJobke** [comment]
New Jenkins PR: #15300

**Comment by MorrisJobke** [comment]
Jenkins is happy in his own PR :)

**Pull request merged**
