### PR TITLE
free up memory when releasing the last shared lock

### PR DESCRIPTION
**Pull request by icewind1991**
Reduces memory usage when using a lot of locks (file scanner)

[comparison](https://blackfire.io/profiles/compare/b74b9540-e881-4c30-9853-3136904ff289/graph)

cc @MorrisJobke @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Yes, makes sense :+1:

**Comment by PVince81** [comment]
Would be good to backport this to 9.0.3 and 8.2.5

@karlitschek @MorrisJobke @DeepDiver1975

**Comment by rullzer** [comment]
:+1:

**Comment by karlitschek** [comment]
nice. backport makes sense. 👍  I have the feeling that we could safe a ton more memory if we release resources and destroy objects earlier. But not critical at the moment of course.

**Comment by DeepDiver1975** [comment]
> nice. backport makes sense.

@icewind1991 please prepare backport prs - THX

**Comment by Kaelber** [comment]
Update :

with oc 9.0.2 and oc_9.1.0 pAlp-1 and Client 2.2.0 the follow situation :

Synology DS414 mit DSM 5.2 | ? : rescan runs and logs are storing, file only updateing, if I use --all in the scan command. If I use a user in the command, no update is done.

Synology DS712+ mit DSM 6 | ? : rescan runs and logs are storing, but no file update is running from server to client, also not with --all in the scan command

Regarding the filescan I got from the Logfile as follow :

With oc 9.1.0 preAlpha and DS414 mit DSM 5.2

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (kaelber)
Starting scan for user 3 out of 4 (rescan)
Starting scan for user 4 out of 4 (kaelber2)

+---------+--------+--------------+
| Folders | Files | Elapsed time |
+---------+--------+--------------+
| 47127 | 200633 | 02:23:05 |
+---------+--------+--------------+

----- End ----------

With oc 9.0.2 and DS712+ mit DSM 6

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (kaelber)
PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 77 bytes) in /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 128

----- End ----------

**Comment by MorrisJobke** [comment]
> @icewind1991 please prepare backport prs - THX

@icewind1991 Ping

**Comment by icewind1991** [comment]
stable9: https://github.com/owncloud/core/pull/24705
stable8.2: https://github.com/owncloud/core/pull/24704

**Comment by Kaelber** [comment]
Update :

with oc 9.1.0 Beta 1 and Client 2.2.0 the follow situation :

Synology DS414 mit DSM 5.2 | ? : scan runs and logs are storing, file only updating, **if I use --all** in the scan command. A **USER** in the command is **NOT RUNNING**, no update is done.

Synology DS712+ mit DSM 6 | ? : rescan runs and logs are storing, but no file update is running from server to client, **also not with --all in the scan command**

Regarding the filescan I got from the Logfile as follow :

**Synology DS414 with DSM 5.2**

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (kaelber)
Starting scan for user 3 out of 4 (rescan)
Starting scan for user 4 out of 4 (kaelber2)

+---------+--------+--------------+
| Folders | Files  | Elapsed time |
+---------+--------+--------------+
| 54235   | 238428 | 03:05:59     |
+---------+--------+--------------+

**----- End ----------**

**Synology DS712+ with DSM 6**

Scanning files for 4 users
Starting scan for user 1 out of 4 (admin)
Starting scan for user 2 out of 4 (kaelber)

**----- End ----------**

**Pull request merged**
