### PR TITLE
Replace the tiny arrow with a login button

### PR DESCRIPTION
**Pull request by ChrisEdS**
A suggestion for a login button to replace the small arrow we had before.

## Description
This pull request is used to check if we want this. I would test after a go to what extent other pages depend on the changes and what effects it has on the themeing.

## Screenshots:
**Before:** Especially in my case it is difficult to reach the button because of a plugin that moves a layer over it. But even without it, the arrow is much too small and hard to see.

image

**After:** Now you can see and reach the button beautifully.

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Edit feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Test with appearing error messages
- [ ] Test with Alternative login enabled
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by hurradieweltgehtunter** [comment]
push! UX wise this would be very useful and does not need a lot of work. 
@pmaier1 , @PVince81 any objections?

**Comment by pmaier1** [comment]
Fine with me to change this. THX.

**Comment by pmaier1** [comment]
@pvince81 agree as well?

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
4 commits to change one button?

Please squash ;-)

**Comment by PVince81** [comment]
ah, moving back and forth. we used to have this as a separate button and now back.

needs to be tested with other login methods as some might add additional buttons.
was it with shibboleth ? @DeepDiver1975

**Comment by ChrisEdS** [comment]
I didn't know that. I haven't been in the company that long.

**Review by lordelix — APPROVED** [review]
@ChrisEdS you can, in fact, get rid of the vendor prefixes as they are not needed anymore.

**Comment by ChrisEdS** [comment]
@felixheidecke You mean the `-ms-filter:`?

**Comment by DeepDiver1975** [comment]
> was it with shibboleth ? @DeepDiver1975

not an issue - not nice either ... :man_shrugging: 

Screenshot from 2019-07-30 08-35-36

**Review by DeepDiver1975 — APPROVED** [review]
approved - but needs to be re-opened these days ....

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
