### PR TITLE
add loading feedback to user menu entries

### LINKED ISSUE #19857: Loading feedback for user menu entries
Just like the spinner which appears when you click an app in the app menu, there should be a spinner for the entry in the user menu you click. Simply a `class="icon-loading-small"`, replacing the icon of the respective entry.

cc @owncloud/designers @PVince81 @MorrisJobke

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes #19857

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by nickvergessen** [comment]
The image has a white square border on chrome.
bildschirmfoto vom 2016-04-13 11 01 44

Also on firefox the image looks a bit odd, is it scaled down?
bildschirmfoto vom 2016-04-13 11 02 19

**Comment by ChristophWurst** [comment]
@jancborchardt @owncloud/designers any idea where that border comes from? I can't figure out why it's shown.

**Comment by ChristophWurst** [comment]
> Also on firefox the image looks a bit odd, is it scaled down?

Nope, that's the default spinner: https://raw.githubusercontent.com/owncloud/core/master/core/img/loading-small.gif

**Comment by jancborchardt** [comment]
The icon looking a bit odd is because it’s on a dark background. @ChristophWurst you need to use `.icon-loading-dark` (and maybe scale it appropriately using CSS).

I also have no idea why the border appears … I think we had this before somewhere but cannot recall. Any clue @owncloud/designers @skjnldsv?

**Comment by skjnldsv** [comment]
It is because of the missing src attribute! 
You need to change the img to a simple div with the correct classes. an img element without src is invalid. :)

**Comment by ChristophWurst** [comment]
@jancborchardt @skjnldsv thanks for your help. I've updated the PR, please test again :-)

**Comment by nickvergessen** [comment]
:+1:

**Comment by jancborchardt** [comment]
@skjnldsv aah, right, good catch! Sure, it should be a simple div with the icon class. :)

**Comment by skjnldsv** [comment]
:+1: good job
(Warning, the direct-menu extension will hide the image, you need to disable it)

**Comment by jancborchardt** [comment]
Btw this menu also needs the same fix as the apps menu: When you click an entry with Ctrl+Click, do not show the spinner and close the menu. :)

**Pull request merged**
