### PR TITLE
Fix of typo "Datenschutzerkärung" in i18n files for German

### PR DESCRIPTION
**Pull request by arneschuldt**
## Description

This is a minor fix of a typo in the i18n files for German ("Datenschutzerkärung" with missing "l" instead of "Datenschutzerklärung" for "Privacy Policy").

The typo had already been fixed by @DeepDiver1975 back in 2018, see https://github.com/owncloud/core/commit/f42f0d93f74421117d24a6fabddd65105b60361c. It seems that the error had been accidentally reintroduced this year with an update from transifex, see https://github.com/owncloud/core/commit/d39cc18bb0390ff229b30393741c9e624ad92a7a.

Additionally, I have suggested the following corrections for "Privacy Policy" at transifex which await approval:

- de_DE: core, mobile-ios-app, lib
- de: mobile-ios-app, lib

## Motivation and Context

Unfortunately, this typo is prominently visible on the login page of ownCloud instances in German language with the most recent version 10.3.1.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by arneschuldt** [comment]
Just an addition to prove the correction of the proposed modification:
[Datenschutzerklärung in the Duden dictionary](https://www.duden.de/rechtschreibung/Datenschutzerklaerung)
[Datenschutzerklärung in the German Wikipedia](https://de.wikipedia.org/wiki/Datenschutzerkl%C3%A4rung)

**Comment by DeepDiver1975** [comment]
@ChrisEdS for you :wave:

**Comment by ChrisEdS** [comment]
@DeepDiver1975 I set the correct translation in Transifex for `de_DE`, for `de` it was correct. Also, the translation in `lib` are reviewed. With the next sync from Transifex we are fine. Thank you for your contribution @arneschuldt

**Comment by ChrisEdS** [comment]
@arneschuldt I reviewed your suggestions.  I will take care that Transifex syncs back the changes you've made. This PR can therefore be closed. Nevertheless, many thanks for the tip and the good work.

**Comment by arneschuldt** [comment]
Thank you very much!

**Pull request closed without merging**
