### PR TITLE
[CI] run drone acceptance matrix with different databases - DONOTMERGE

### PR DESCRIPTION
**Pull request by patrickjahns**
## MOTIVATION

get Feedback from our ci when running acceptance tests with various db backends

# DONOTMERGE

### CODE REVIEW

**Comment by patrickjahns** [comment]
| Database       | API Tests .     | UI Tests .     | comment | 
| ------------- | ------------- | ------------- | ------------- |
|   postgres      |         ✅         |         ✅         |          |
|   mysqlmb4    |         ✅         |         ✅         |         |
|   mysql           |                       |         ✅         |         |
|   oracle          |                        |         ✅         |         |
|   mariadb      |         ✅         |         ✅         |     runs on all PRS   |

**Comment by patrickjahns** [comment]
closing for now - waiting for drone triggers to be able to run something similar on demand

**Comment by DeepDiver1975** [comment]
@patrickjahns we can use default values for env variables for the db images - see https://github.com/owncloud/update-testing/blob/ecdf625e74a084b79a75636c68371536bf2682f7/.drone.yml#L83

**Comment by patrickjahns** [comment]
@DeepDiver1975 
thanks for sharing - this PR had the intention of running all acceptance tests with various combinations of databases. Would like to be able to define a specific matrix permutation for all these databases and run this on demand (i.e. trigger once weekly, or per RC )

**Pull request closed without merging**
