### PR TITLE
[stable8] Fix size propagation over shared storage boundary

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/14720 to stable8

@icewind1991 @nickvergessen @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
Did a quick manual test in the web UI, the size is propagated properly.

Please review.

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
Test steps here: https://github.com/owncloud/core/issues/14596#issuecomment-77389915

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
