### PR TITLE
[full-ci] added last_login to getUser()

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
This is the code from https://github.com/ctcq/core/tree/provisioning-api-last-login - I have rebased it and adjusted the acceptance tests.

## Related Issue
#38624 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation ticket raised: https://github.com/owncloud/docs/issues/4201
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioning-v1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33538/54/1

**Comment by phil-davis** [comment]
@pmaier1 this should pass CI, and should be happily backward-compatible with existing consumers of the Provisioning API. It just adds a `last_login` data item to the data returned about a user.

See issue #38624 for the feature request.

Is it OK  to proceed?

**Review by JammingBen — COMMENTED** [review]
Code looks good. We should include a changelog item if we decide to add this.

**Comment by pmaier1** [comment]
> Is it OK to proceed?

Sure, thanks. Please consider dev docs and changelog. cc @mmattel

**Comment by phil-davis** [comment]
Changelog added and docs issue https://github.com/owncloud/docs/issues/4201 raised.

**Review by JammingBen — APPROVED** [review]

**Pull request merged**
