### PR TITLE
Add comment xpath to variables in DetailsDialog.php

### LINKED ISSUE #33527: move xpath to variable in DetailsDialog::getCommentXpath()
see https://github.com/owncloud/core/blob/master/tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php#L116

```
	/**
	 * find the xpath of comment with given content
	 *
	 * @param string $content
	 *
	 * @return string
	 */
	private function getCommentXpath($content) {
		return "//ul[@class='comments']//div[@class='message' and contains(., '" . $content . "')]";
	}
```

that xpath should be in a private variable like every other
@dpakach you have implemented that in #32927

### PR DESCRIPTION
**Pull request by dpakach**
## Description

move comment's xpath to a variable in DetailsDialog::getCommentXpath() 

## Related Issue

- Fixes #33527

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
In the issue, @individual-it mentioned 2 other places like this to be changed.

**Comment by dpakach** [comment]
> In the issue, @individual-it mentioned 2 other places like this to be changed.

I didn't noticed those earlier but they are fixed now

**Comment by phil-davis** [comment]
I guess this was accidentally closed.

@individual-it please review.

**Review by individual-it — APPROVED** [review]

**Comment by dpakach** [comment]
backport on #33553

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
