### PR TITLE
[10.3.x] [Tests-Only] Pin behat/mink to version 1.7.1

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Pin behat/mink to version 1.7.1 (similar to what had to be done in master PR #37112 )
2) switch drone to `.drone.star` because that is the script that drone CI is using now

This makes acceptance tests work in CI for the `v10.3.2` tag. It could be used to generate a new QA tarball (called 10.3.3 ?) that could be used to run automated tests for other existing custom 10.3.2 systems.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by micbar** [comment]
@phil-davis No luck with the acceptance tests.
Did we miss something?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/23935/89/17 fails a test:
```
Scenario: test resharing folder as readonly and set it as readonly by resharer                                                     # /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:273
```
That is a test that is logging in to the UI on the remote server and doing stuff. GitHub does some sort of "auto-pretend-merge" of the branch and is actually running some newer test code that expects a newer UI (with different sharing/expiration date UI...) and so does not manage to drive the "old" UI on the "remote" server.

I will look and see what I can do to work-around that...

**Comment by phil-davis** [comment]
I have skipped that test that drives the UI of a remote server.

We re-engineered all that in master in the last months. Test scenarios were turned around and/or split into 2 scenarios so that only API-based setup steps were done to the remote federated server, and any UI actions for the test were done on the local server. This ensured that it did not matter so much if the remote federated server was older than the local server (which is the real system-under-test). But finding all the pieces of that puzzle and cherry-picking back here is, IMO, not a worthwhile jigsaw to spend time on.

**Comment by micbar** [comment]
@phil-davis That would mean, we need to create a qa-tarball.

Lets wait for CI

**Comment by phil-davis** [comment]
Stupid drone errors like https://drone.owncloud.com/owncloud/core/23938/46/5
`apiTags-mariadb10.2-php7.1: Error: No such image: docker.io/owncloudci/php:7.1`

total BS from drone and docker - restarting CI...

**Review by micbar — APPROVED** [review]

**Comment by phil-davis** [comment]
@micbar Merged to `release-10.3.3` - now we have a `10.3.3` branch from which someone can build whatever things they like (a QA tarball or...)

**Pull request merged**
