### PR TITLE
Check if the file exists before trying to download it

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
When a mount point isn't set to check for changes on access, a 503 HTTP code could be thrown if that file has been removed. With the PR, it will throw a 404 HTTP code instead.

## Related Issue
No public issue

## Motivation and Context
Throw the right error instead of a wrong one.

## How Has This Been Tested?
Manually with SFTP: upload a file through ownCloud to a SFTP mount configured with "check for changes = never", remove the file in the backend, try to download the file.

A 404 HTTP code will be thrown, although the page show to the user will be the same

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
We should cover this with integration tests. There's a "local" external storage on which we could remotely delete the file to test this.

**Comment by jvillafanez** [comment]
I'd rather wait for @owncloud/qa for the integration tests. I'm not sure how it is planned or what is being covered for external storages.

**Comment by PVince81** [comment]
@owncloud/qa can you help @jvillafanez write the tests?

**Comment by PVince81** [comment]
CI restarted. Since this at least has unit tests I think we can merge first.

**Comment by phil-davis** [comment]
https://travis-ci.org/owncloud/core/jobs/261783308 got some wacky error when testing setting invalid quotas. I copied the error output in case I see it again, then restarted that job - hopefully Travis will be happy in 20 minutes or so.

**Comment by PVince81** [comment]
@jvillafanez please backport to stable10

**Comment by jvillafanez** [comment]
Backport to stable10: https://github.com/owncloud/core/pull/28613

**Comment by PVince81** [comment]
integration test here: https://github.com/owncloud/core/pull/28614

**Pull request merged**
