### PR TITLE
[stable10] extend substitution of inline codes in UI/integration tests

### PR DESCRIPTION
**Pull request by individual-it**
backport of #28460 to stable10

### CODE REVIEW

**Comment by phil-davis** [comment]
@individual-it  It says it has conflicts ??? It will need to be made happy somehow and CI run after that.

**Review by phil-davis — APPROVED** [review]
CI is happy and so am I.
But it is complaining about conflicts again???

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2017-07-24 23-36-32

no idea what is the way is should look like .... rebase your branch locally and resolve the conflict

**Comment by phil-davis** [comment]
@individual-it see #28478 - the commit cherry-pick went fine for me without any conflict...
It might be easiest just to let the CI run on that other PR and close here?

**Comment by individual-it** [comment]
closing in favour of #28478

**Pull request closed without merging**
