### PR TITLE
[stable8] add note about SSL in admin settings

### LINKED ISSUE #16778: Better description of "Enforce HTTPS" in admin backend
Hi,

the option "Enforce HTTPS" within the admin backend is subject of a lot of misinterpretation. Quite often it happens that:

1. Users think they can magically enable SSL within their webserver when using this option
2. Users don't know at all why the checkbox is greyed out

Currently don't know if its better to just document this: https://github.com/owncloud/documentation/issues/1197 or just extend the description here:

https://github.com/owncloud/core/blob/v8.0.4/settings/templates/admin.php#L396

This affects only OC8 and below as OC8.1 has removed this checkbox: https://github.com/owncloud/core/pull/14651

### PR DESCRIPTION
**Pull request by MorrisJobke**
- reborn #16867
- fixes #16778 

cc @DeepDiver1975 @karlitschek @RealRancor

### CODE REVIEW

**Comment by MorrisJobke** [comment]
This is only valid for stable8

**Comment by Xenopathic** [comment]
:+1:

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by karlitschek** [comment]
good :+1:

**Comment by DeepDiver1975** [comment]
t() is missing - but anyhow pointless since we will not update translations ...

**Comment by MorrisJobke** [comment]
> t() is missing - but anyhow pointless since we will not update translations ...

That's the reason I didn't added it ;)

**Comment by MorrisJobke** [comment]
Please wait for the 8.0.6 release on 2015-08-04 and then merge this.

**Pull request merged**
