### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by chriseqipe**
Send 401 on OPTIONS / HTTP/1.1 request coming from windows WebDAV service. 
This way the WebClient Service on Windows starts automatically on request.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kdslkdsaldsal** [comment]
This is related to:

https://github.com/owncloud/documentation/pull/2717
https://github.com/owncloud/documentation/pull/2668#issuecomment-260697742
https://github.com/owncloud/core/issues/26350

isn't it?

**Comment by chriseqipe** [comment]
Yes, they are all related. But Windows need a 401 answer and not the 301 version as currently implemented. We made a lot of testing and our/this pull request version of .htaccess is the only really working with Win 7 to Win 10. On Nextcloud I made the same pull request as here on owncloud. Therefore same it will be the same approach on Nextcloud as for owncloud. The reply 301 only works, if the MS Webdav Service was already startet for some reasons. The initial startup of the MS Webdav Service needs the 401 reply to start the service on demand and this is the default behavior on a unchanged/unpatched Windows.

**Comment by chriseqipe** [comment]
See Screencast I made tonight: 
https://www.youtube.com/watch?v=T50ZYrNBaeo

**Comment by PVince81** [comment]
Does this need to be done in htaccess or can it be done in a Webdav plugin ?

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Does this need to be done in htaccess or can it be done in a Webdav plugin ?

I'm having a hard time to judge on this ....

**Comment by mmattel** [comment]
@PVince81, I propose to merge this. Running nginx, the adequate ruleset solves the problem.

**Comment by mmattel** [comment]
There is an existing documentation for troubleshooting including this issue.
I have created a doc PR https://github.com/owncloud/documentation/pull/3891 to harmonize / fix the content and include a proper nginx ruleset. This is necessary to be on the safe side if this PR doesnt get merged!
In case of merging this core PR, I will post adapt the documentation.

**Comment by patrickjahns** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by mmattel** [comment]
Info: The nginx part has been moved in the meanwhile to the new nginx config page.

**Comment by PVince81** [comment]
I wonder if it would be possible and better to implement this on application level, maybe in the Sabre plugins ?

Mind explaining how the logic should work ?

**Comment by PVince81** [comment]
would rather have this in a SabreDAV plugin, to make Windows auto-login.

this way we can also restrict the effect of the change to only this one client

cc @DeepDiver1975

**Pull request closed without merging**
