### PR TITLE
Bump 3rdparty for guzzlehttp/http to 5.3.0

### PR DESCRIPTION
**Pull request by rullzer**
Includes bump of react/promise to 2.2.1

requires: https://github.com/owncloud/3rdparty/pull/209

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> requires: owncloud/3rdparty#209

merged - submodule needs to be updated ....

**Comment by rullzer** [comment]
@DeepDiver1975 done

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 done

THX

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
