### PR TITLE
Fix the fetching of LDAP users in the LocalAddressbook

### PR DESCRIPTION
**Pull request by LEDfan**
The LocalAdressbook wasn't able to discover/fetch LDAP users. (Reported here https://github.com/owncloud/chat/issues/128 )

CC @frykillr @DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by LEDfan** [comment]
@DeepDiver1975 there is a problem with this patch. It works perfect when you expect to fetch exactly one user and you know the exact id of this contact/user. However when you want to search for multiple users this won't work anymore. 

I'll have a look at this later.

**Comment by DeepDiver1975** [comment]
moving to 8.1 - time is up for 8.0

**Comment by LEDfan** [comment]
I think I found how to solve the problem I described.
If we call the function like this:
````
function search('id', array($userId),array())
````
Then the function searches for the user by calling the `$userManager->serach()` function.
If we call the function like this:
````
function search('id', array($userId),array('get'))
````
Then the user(s) is returned by calling the `$userManager->get()` method.

**Comment by MorrisJobke** [comment]
Replaced by #13819

**Pull request closed without merging**
