### PR TITLE
Sticky the notification types of files and sharing

### PR DESCRIPTION
**Pull request by nickvergessen**
@jancborchardt @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I don't get this, because the arrays are merged in the end. Can you explain what this should address?

**Comment by nickvergessen** [comment]
If you have calendar installed, currently you get files, calendar, sharing in the persinal settings.
With the patch the result is files, sharing, calendar, so core stuff comes first

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
@Xenopathic @rullzer @PVince81  Review?

**Comment by PVince81** [comment]
:+1:

**Comment by jancborchardt** [comment]
Thank you @nickvergessen!

**Pull request merged**
