### PR TITLE
[WIP] Throw an exception if any of specified app paths are not found

### PR DESCRIPTION
**Pull request by vgezer**
E.g. when we have app paths in config, but they do not exist,
currently we do not show any exception messages or write into log.

Try:
- Rename apps directory into something else
- refresh OC page.

Expected: A warning message or an entry in log

Actual: Just infinite loop warning by Chromium

This writes an exception to the log

### CODE REVIEW

**Comment by PVince81** [comment]
Any update ?

**Comment by wakeup** [comment]
@PVince81 due to a problem, we cannot print exception messages. I reverted the commit back but Exception calls throw

~~~
[Mon Feb 09 17:07:33.212983 2015] [:error] [pid 26291] [client 127.0.0.1:54391] PHP Fatal error:  Call to a member function getSecureRandom() on null in /var/www/oc_git/lib/private/request.php on line 52, referer: http://localhost/ocg/index.php
~~~

**Comment by wakeup** [comment]
In addition, removing or renaming an app directory gives:

~~~
[Mon Feb 09 17:20:43.193035 2015] [:error] [pid 26291] [client 127.0.0.1:54411] PHP Fatal error:  Call to a member function getValue() on null in /var/www/oc_git/lib/private/legacy/config.php on line 46, referer: http://localhost/ocg/index.php/apps/files/
~~~

**Comment by nickvergessen** [comment]
@vgezer mind taking a look at #14993 which replaces this PR?

**Comment by vgezer** [comment]
@nickvergessen Thanks for taking it over!

**Pull request closed without merging**
