### PR TITLE
[stable10] UI tests for reset password

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #31168

### CODE REVIEW

**Comment by phil-davis** [comment]
This is a rebased version of PR #31192 
I had trouble messing with that backport PR from @paurakhsharma so I made a new PR.

This backport had been stuck waiting for #31144 to be merged.

And other backports are waiting for this to get merged - e.g. backport for #31220 which will quickly remove all this ``EmailContext`` stuff again.

It is all easier if the backports happen in order - no conflict mess.

**Comment by phil-davis** [comment]
I had to add ``USE_EMAIL: true`` to ``webUIManageUsersGroups`` because it has ``resetPassword.feature`` (and ``webUIManageUsersGroups`` is no longer in ``core`` ``master`` - so it is always a bit of a learning experience backporting ``webUI`` infrastructure changes from ``core`` to ``stable10``

**Comment by patrickjahns** [comment]
>I had to add USE_EMAIL: true to webUIManageUsersGroups because it has resetPassword.feature (and webUIManageUsersGroups is no longer in core master - so it is always a bit of a learning experience backporting webUI infrastructure changes from core to stable10
@DeepDiver1975 
that is what i mean by not diverging from the contents of the branches too much

**Comment by phil-davis** [comment]
This works. Now we are stuck because of the Redis problem, and that Travis has these huge cron jobs running. So PR #31229 is waiting... for a few short Travis jobs to get run.

**Comment by phil-davis** [comment]
Rebased again - the Redis fixes are merged in ``stable10``. I expect CI to pass here now.

**Review by individual-it — APPROVED** [review]

**Pull request merged**
