### PR TITLE
make attributes to list configurable, add verbose option

### PR DESCRIPTION
**Pull request by butonic**
forward port of https://github.com/owncloud/core/pull/31115

### CODE REVIEW

**Comment by phil-davis** [comment]
Pushed a commit to fix the ``php-cs-fixer`` thing.

**Review by phil-davis — APPROVED** [review]
Works like it does in stable10

**Comment by phil-davis** [comment]
@tomneedham or @DeepDiver1975 - feeling happy about this?
I gave it a quick manual test from this branch and it works.

**Comment by mmattel** [comment]
stable10 has been merged already, any reason why this forward port to master ist not merged?
@DeepDiver1975 @PVince81

**Pull request merged**
