### PR TITLE
fix change password if no user is logged in, occ call

### LINKED ISSUE #15685: [enc2] Can not reset password via console when encryption is enabled
@schiesbn 

```
$ ./occ user:resetpassword admin
Enter a new password:
Confirm the new password:
PHP Fatal error:  Call to a member function canChangePassword() on a non-object in /home/nickv/ownCloud/master/core/apps/encryption/hooks/userhooks.php on line 199
PHP Stack trace:
PHP   1. {main}() /home/nickv/ownCloud/master/core/occ:0
PHP   2. require_once() /home/nickv/ownCloud/master/core/occ:11
PHP   3. OC\Console\Application->run() /home/nickv/ownCloud/master/core/console.php:59
PHP   4. Symfony\Component\Console\Application->run() /home/nickv/ownCloud/master/core/lib/private/console/application.php:75
PHP   5. Symfony\Component\Console\Application->doRun() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRunCommand() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Application.php:195
PHP   7. Symfony\Component\Console\Command\Command->run() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Application.php:874
PHP   8. OC\Core\Command\User\ResetPassword->execute() /home/nickv/ownCloud/master/core/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP   9. OC\User\User->setPassword() /home/nickv/ownCloud/master/core/core/command/user/resetpassword.php:109
PHP  10. OC\Hooks\PublicEmitter->emit() /home/nickv/ownCloud/master/core/lib/private/user/user.php:211
PHP  11. OC\Hooks\BasicEmitter->emit() /home/nickv/ownCloud/master/core/lib/private/hooks/publicemitter.php:32
PHP  12. call_user_func_array:{/home/nickv/ownCloud/master/core/lib/private/hooks/basicemitter.php:99}() /home/nickv/ownCloud/master/core/lib/private/hooks/basicemitter.php:99
PHP  13. OC\Server->OC\{closure}() /home/nickv/ownCloud/master/core/lib/private/hooks/basicemitter.php:99
PHP  14. OC_Hook::emit() /home/nickv/ownCloud/master/core/lib/private/server.php:166
PHP  15. call_user_func:{/home/nickv/ownCloud/master/core/lib/private/hook.php:103}() /home/nickv/ownCloud/master/core/lib/private/hook.php:103
PHP  16. OCA\Encryption\Hooks\UserHooks->preSetPassphrase() /home/nickv/ownCloud/master/core/lib/private/hook.php:103

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/owncloud/core/issues/15685

cc @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
Works, old files are also still encryptable :+1:

**Comment by nickvergessen** [comment]
@MorrisJobke @th3fallen second review?

**Comment by DeepDiver1975** [comment]
unit test please - this should have need covert from the beginning

**Comment by schiesbn** [comment]
unit test added for this specific case

**Comment by DeepDiver1975** [comment]
> unit test added for this specific case

THX :+1:

**Pull request merged**
