### PR TITLE
Fix subadmin permission check for addToGroup/removeFromGroup

### LINKED ISSUE #25496: API: Regular user with group admin perms cannot alter group memberships
### Steps to reproduce
1. try something like this with a non-admin user with group admin permissions:
```
curl -X POST --user <user>:<password> https://owncloud.server/files82/ocs/v1.php/cloud/users/uiserid/groups/  -d groupid=“testgroup"
```
2. Receive a status code of either 999 or 997

### Expected behaviour
The API call should modify users group memberships.

### Actual behaviour
You receive an error

This was tested on oc 8.2.5 and 9.0.3. This behaviour was consistent on both versions.

[00005763](https://na25.salesforce.com/5003100000cpFgY?srPos=0&srKp=500)

### PR DESCRIPTION
**Pull request by PVince81**
Fixes issue where subadmins could never add users to a group.
Added missing unit tests

Fixes https://github.com/owncloud/core/issues/25496
- stable9.1: https://github.com/owncloud/core/pull/25797
- stable9: https://github.com/owncloud/core/pull/25798

Please review @DeepDiver1975 @tomneedham @SergioBertolinSG @VicDeo @butonic

### CODE REVIEW

**Comment by PVince81** [comment]
@SergioBertolinSG do we have integration tests for the provisioning API ? If not, would you mind adding some ?

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
QA ticket for automated tests: https://github.com/owncloud/QA/issues/290

**Comment by PVince81** [comment]
Updated OP with backport tickets

**Pull request merged**
