### PR TITLE
Morlinest patch 1

### PR DESCRIPTION
**Pull request by DeepDiver1975**
continuation  of #22104

### CODE REVIEW

**Comment by PVince81** [comment]
@LukasReschke @BernhardPosselt

**Comment by Morlinest** [comment]
@DeepDiver1975 
Do i need to do anything? I deleted my branch as I saw PR is closed (cant write unit test to finish it), now i have to give permision (comment or sign contributor-agreement) again? I saw in jenkins log (cla-bot-core): "09:15:05 Morlinest is not yet a contributor". How can i help you (everything but unit tests :D)? Thanks.

**Comment by nickvergessen** [comment]
Well I  guess the comment from https://github.com/owncloud/core/pull/22104#issuecomment-188158622 is enough, now it just needs to be tested and then we can merge it. nothing required from you atm, apart if you want to add tests :wink:

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2016-06-06 18-06-37

**Comment by PVince81** [comment]
moving to backlog

**Comment by PVince81** [comment]
@DeepDiver1975 finish or close ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 finish or close ?

☠️

**Pull request closed without merging**
