### PR TITLE
explicit rollback when a database commit fails

### LINKED ISSUE #16445: Handle aborted transactions properly
We introduced transactions in some code parts. We should properly handle them like described in http://doctrine-dbal.readthedocs.org/en/latest/reference/transactions.html#transactions

See https://github.com/owncloud/core/pull/13948#issuecomment-102378344
- [ ] https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/lib/private/files/utils/scanner.php#L151
- [ ] https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/lib/private/db/mdb2schemamanager.php#L169
- [ ] https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/lib/private/db/migrator.php#L216
- [ ] https://github.com/owncloud/core/blob/a8b756154a533a2618f03c54aca56af957da12ae/lib/private/connector/sabre/custompropertiesbackend.php#L261
- [ ] https://github.com/owncloud/core/blob/80b892e7ed7b2d6b5220840e1bb3b11115c72cb4/lib/repair/repairlegacystorages.php#L164
- [ ] https://github.com/owncloud/core/blob/a13088818a73ecdf6f7d6600c011e0fa49054b51/lib/private/files/cache/scanner.php#L313
- [ ] https://github.com/owncloud/core/blob/f1903f61a11c9e9c7a5b50af82883031cb1e95c1/lib/private/files/cache/cache.php#L549

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #16445

cc @DeepDiver1975 @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
I guess this can't hurt. But hard to judge all possible scenarios. :+1: anyways.

**Comment by MorrisJobke** [comment]
it feels a bit strange ... we also need a way to undo changes to the filesystem if a file is moved for example ... I don't really like this super generic way, that only does half of the stuff. On an aborted commit the instance can still lose metadata (i.e. fileid).

**Comment by cmonteroluque** [comment]
@icewind1991 @MorrisJobke what's the follow up to Morris' comment? We need a resolution in the next day or so, Next steps?

**Comment by MorrisJobke** [comment]
> @icewind1991 @MorrisJobke what's the follow up to Morris' comment? We need a resolution in the next day or so, Next steps?

I just feel uncomfortable with this. I would better have this in very early in the dev cycle of 9.0 to have enough time to spot actual problems.

**Comment by karlitschek** [comment]
I agree. Let's delay this for 9.0 so that we get more time for testing

**Comment by karlitschek** [comment]
Hmm. This isn't really a proper handling of failed transactions. Can trigger other problems. Close for now.

**Pull request closed without merging**
