### PR TITLE
[stable8] Execute parallel-lint

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/owncloud/core/pull/22994 and https://github.com/owncloud/core/pull/23303

### CODE REVIEW

**Comment by LukasReschke** [comment]
:white_check_mark: Travis is passing on this one.

**Comment by DeepDiver1975** [comment]
@cmonteroluque @karlitschek please note that we introduce .travis.yml and composer.json with this PR (and related backports) - please make sure these files are not packaged - THX

**Comment by karlitschek** [comment]
done. removed in the build script.

**Comment by MorrisJobke** [comment]
:+1: 

Travis succeeded.

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
