### PR TITLE
Catch and convert LoginException to NotAuthenticated to show 401 instead of 503

### PR DESCRIPTION
**Pull request by butonic**
cc @tomneedham

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase was successful!

**Comment by PVince81** [comment]
unit test?

**Review by PVince81 — APPROVED** [review]
:+1: please backport

**Comment by PVince81** [comment]
Failing acceptance tests:
```
    webdav-related-new-endpoint.A disabled user cannot use webdav
    webdav-related-old-endpoint.A disabled user cannot use webdav
```

**Comment by tomneedham** [comment]
@phil-davis Can you update the acceptance tests here please? Guessing they dont like that we changed a response code. We now return a 403 instead of 503 when dealing with disabled users. This is so that clients can show better error messages.

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
Rebased to get a current set of test results. I will look...

**Comment by phil-davis** [comment]
API acceptance tests updated - it was too easy, just change some ``503`` to ``401``
Note that a disabled user (like a user who is not logged in) in ``unauthenticated`` and that is an HTTP status ``401`` which is what this returns - all good.

``403`` is for ``unauthorized`` which is used when the client is "logged in" (``authenticated`` - the system knows who you are) but does not have permission for the resource they are attempting to access.

In the title and other comments in this PR, you might like to ``s/403/401/g`` to avoid confusing people who read the text and then look at the code.

**Comment by phil-davis** [comment]
@PVince81 your approval on this is very old. Integration test changes needed were simple. Please review again and merge if happy.

**Review by tomneedham — APPROVED** [review]

**Comment by PVince81** [comment]
please backport as it affects clients

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/30639

**Pull request merged**
