### PR TITLE
Update doc links in README for 9.0

### PR DESCRIPTION
**Pull request by PVince81**
@DeepDiver1975 @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
Wouldn't it be better to build "master" from docs? Otherwise people take 9.0 for granted although stuff is subject of change

**Comment by MorrisJobke** [comment]
> Wouldn't it be better to build "master" from docs? Otherwise people take 9.0 for granted although stuff is subject of change

cc @danimo @carlaschroder

**Comment by MorrisJobke** [comment]
I'm fine with this :+1:

**Pull request merged**
