### PR TITLE
fix issue with not-closing sharing dialog in safari

### LINKED ISSUE #17125: Share button gets blocked browsing away using Safari as browser
### Steps to reproduce
1. Using Safari as browser click on the share button.
2. Browse away in the screen

### Expected behaviour
The share "menu" should dissapear

### Actual behaviour
The share menu is visible and share buttons are blocked

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:**"version":"8.1.0.7","versionstring":"8.1 RC1","edition":"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.0
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_shibboleth: 1.0.1.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/core/issues/17125

please review @LukasReschke @davitol

### CODE REVIEW

**Comment by PVince81** [comment]
I don't see any relationship between the left sidebar app toggle and the share dropdown.
Mind explaining ?

**Comment by PVince81** [comment]
:-1: breaks the settings panel at the bottom of the sidebar in Chromium 43.

I have no idea why, this all looks very weird. Your change looks valid but yet it breaks in Chromium.

**Comment by georgehrke** [comment]
> Mind explaining ?

When clicking outside the share-dialog i got this error message: `TypeError: undefined is not a function (evaluating 'event.target.closest('[data-apps-slide-toggle]')')` in `apps.js:61`
That's why I fixed that line

> breaks the settings panel 

What exact settings panel? I'm not sure I can follow

**Comment by georgehrke** [comment]
> What exact settings panel? I'm not sure I can follow

The one in the lower left corner, so never mind.

**Comment by georgehrke** [comment]
Will look into why it breaks the lower left menu tomorrow

**Comment by DeepDiver1975** [comment]
From my understanding there is no need to fix this one anymore in master. We will move the share dialog to the side bar soon. 

This fix might be interesting for stable8.1 and earlier releases - if at all.

**Comment by georgehrke** [comment]
okay, I'll create a pull request against stable8.1 then

**Pull request closed without merging**
