### PR TITLE
[stable8.1] fix addToGroup hook

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/owncloud/core/pull/17381

This should fix the root of the problems we debugged the last few days.

cc @MorrisJobke @nickvergessen @karlitschek

### CODE REVIEW

**Comment by nickvergessen** [comment]
@cmonteroluque

**Comment by karlitschek** [comment]
Thanks. 
Please backport.

**Comment by nickvergessen** [comment]
This is already the backport from #17381 I don't think 8.0 is affected? @schiesbn

**Comment by MorrisJobke** [comment]
:+1:

**Comment by schiesbn** [comment]
I'm not sure if 8.0 is affected but by looking at the code I have the feeling that we make the same mistake in 8.0. I prepared a backport so that we can test it: https://github.com/owncloud/core/pull/18920

**Comment by MorrisJobke** [comment]
@nickvergessen also said that this fixed the issue on his test system -> count this as :+1:

**Pull request merged**
