### PR TITLE
[tests-only] unmark test of reva-issue-165

### LINKED ISSUE #165: creating a folder that already exists returns HTTP 405  Method Not Allowed
```
$ curl -X MKCOL http://localhost:9140/remote.php/dav/files/user1/f1 -u user1:1234 -v 
*   Trying 127.0.0.1:9140...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9140 (#0)
* Server auth using Basic with user 'user1'
> MKCOL /remote.php/dav/files/user1/f1 HTTP/1.1
> Host: localhost:9140
> Authorization: Basic dXNlcjE6MTIzNA==
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Access-Control-Allow-Origin: *
< Vary: Origin
< X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTg4NTc4MzkyLCJpYXQiOjE1ODg1NzQ3OTIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJ1c2VyIjp7ImlkIjp7ImlkcCI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJvcGFxdWVfaWQiOiJ1c2VyMSJ9LCJ1c2VybmFtZSI6InVzZXIxIiwibWFpbCI6InVzZXIxQGV4YW1wbGUub3JnIiwiZGlzcGxheV9uYW1lIjoiVXNlciBPbmUifX0.NLsx_jlYgKFKh4PjuP-0ktFAViq2mi5-MjL1ZH9VoKw
< Date: Mon, 04 May 2020 06:46:32 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact

$ curl -X MKCOL http://localhost:9140/remote.php/dav/files/user1/f1 -u user1:1234 -v 
*   Trying 127.0.0.1:9140...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9140 (#0)
* Server auth using Basic with user 'user1'
> MKCOL /remote.php/dav/files/user1/f1 HTTP/1.1
> Host: localhost:9140
> Authorization: Basic dXNlcjE6MTIzNA==
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 405 Method Not Allowed
< Access-Control-Allow-Origin: *
< Vary: Origin
< X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTg4NTc4Mzk1LCJpYXQiOjE1ODg1NzQ3OTUsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJ1c2VyIjp7ImlkIjp7ImlkcCI6Imh0dHBzOi8vbG9jYWxob3N0OjkyMDAiLCJvcGFxdWVfaWQiOiJ1c2VyMSJ9LCJ1c2VybmFtZSI6InVzZXIxIiwibWFpbCI6InVzZXIxQGV4YW1wbGUub3JnIiwiZGlzcGxheV9uYW1lIjoiVXNlciBPbmUifX0.dz76kZ6isrskdiBMIdswzbT8OlmvzAzrpCS2EJQ5AN4
< Date: Mon, 04 May 2020 06:46:35 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

## vs oC10
```
$ curl -X MKCOL http://localhost/owncloud-core/remote.php/dav/files/uu1/f1 -u uu1:uu1 -v
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
* Server auth using Basic with user 'uu1'
> MKCOL /owncloud-core/remote.php/dav/files/uu1/f1 HTTP/1.1
> Host: localhost
> Authorization: Basic dXUxOnV1MQ==
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Date: Mon, 04 May 2020 06:49:06 GMT
< Server: Apache/2.4.43 (Ubuntu)
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Set-Cookie: oc4kyqahfanl=359lvlh8bm1tspd113v6nfo7mb; path=/owncloud-core; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=gKID%2BJjR5cg%2FQm080YjITUU46kXyiXByFZDioCNX%2FFTTA6fARoCV4%2BIQUL21A1ZtQPWiztomF3W2ZbLYT0%2FuOuJObLlgOs0V0%2FE3gX%2BM0g1tZMIVDExXoKYndjDU5rZM; path=/owncloud-core; HttpOnly
< Content-Security-Policy: default-src 'none';
< Set-Cookie: oc4kyqahfanl=patk0csl6ad4qsn91hvjnval22; path=/owncloud-core; HttpOnly
< Set-Cookie: cookie_test=test; expires=Mon, 04-May-2020 07:49:06 GMT; Max-Age=3600
< OC-FileId: 2147535348oc4kyqahfanl
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host localhost left intact

$ curl -X MKCOL http://localhost/owncloud-core/remote.php/dav/files/uu1/f1 -u uu1:uu1 -v
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
* Server auth using Basic with user 'uu1'
> MKCOL /owncloud-core/remote.php/dav/files/uu1/f1 HTTP/1.1
> Host: localhost
> Authorization: Basic dXUxOnV1MQ==
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 405 Method Not Allowed
< Date: Mon, 04 May 2020 06:49:13 GMT
< Server: Apache/2.4.43 (Ubuntu)
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Set-Cookie: oc4kyqahfanl=33t2jg58bvihkuh8uni0be5dsc; path=/owncloud-core; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=M17sap3Lsxy6IpxBAODEQ7JQXhgUZfHcciz6KZjt9jPeDCCGlkDQtu%2B0PiB0cyN%2B4u06sSHjvta9%2Fyivw3Paqgy4pUe42Qf%2BIvMfi6YohA3sL7S2JjCbOBTaSKE4Pxqm; path=/owncloud-core; HttpOnly
< Content-Security-Policy: default-src 'none';
< Set-Cookie: oc4kyqahfanl=8psntuhr14t43f6rndr1449ftg; path=/owncloud-core; HttpOnly
< Set-Cookie: cookie_test=test; expires=Mon, 04-May-2020 07:49:13 GMT; Max-Age=3600
< Allow: OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT, LOCK, UNLOCK
< Content-Length: 247
< Content-Type: application/xml; charset=utf-8
< 
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\MethodNotAllowed</s:exception>
  <s:message>The resource you tried to create already exists</s:message>
</d:error>
* Connection #0 to host localhost left intact
```

### PR DESCRIPTION
**Pull request by individual-it**
## Description
that tag is not needed because the issue is caused by something else

## Related Issue
- Fixes https://github.com/owncloud/ocis-reva/issues/165

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by individual-it** [comment]
strange phpstan failure in CI
```
Ignored error pattern #Result of function rewinddir \(void\) is used.#
     was not matched in reported errors.

**Comment by phil-davis** [comment]
There was a phpstan "bug" https://github.com/phpstan/phpstan/issues/3232
Fixed in https://github.com/phpstan/phpstan-src/pull/192
And release just 2 hours ago: https://github.com/phpstan/phpstan/releases/tag/0.12.22

Now that message is not emitted by phpstan any more. And so it breaks our CI.

I will make a PR to core...

**Comment by phil-davis** [comment]
core is fixed - rebased here.

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
