### PR TITLE
Style telephone inputs like other types

### PR DESCRIPTION
**Pull request by Henni**
Before:
image
After:
image

Please review @owncloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by nickvergessen** [comment]
Looks good, not sure if it really has to be 9.1, or if 9.0.1 is okay as well.
Up to @PVince81

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
trivial css change - might even go into 9.0 from my pov - but yes - @PVince81 has to make the call here

**Comment by jancborchardt** [comment]
:+1: otherwise the fields don’t look good in the new Contacts app.

@PVince81 would be cool if we can get it into 9.0 – scheduling it for that hence, but you can postpone if you decide so.

**Comment by DeepDiver1975** [comment]
@PVince81 please decide on milestone - THX

**Comment by PVince81** [comment]
This CSS change doesn't hurt, so let's have it for 9.0...

**Comment by DeepDiver1975** [comment]
> This CSS change doesn't hurt, so let's have it for 9.0...

thx

**Pull request merged**
