### PR TITLE
Fix PHPDoc + Add handling for error cases

### PR DESCRIPTION
**Pull request by LukasReschke**
Makes static code analyzers happier.

@schiesbn THX

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by rullzer** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
Rebase please to get CI green

**Comment by DeepDiver1975** [comment]
Rebase please to get CI green

**Comment by rullzer** [comment]
Rebased. Lets see if CI becomes a sea of green

**Comment by rullzer** [comment]
> Rebase please to get CI green

@DeepDiver1975 rebased and CI seems happy :)

**Pull request merged**
