### PR TITLE
Specify the target user when unsharing a federated share

### LINKED ISSUE #23148: Multiple federated unsharing removes the last, not the removed one
### Steps to reproduce
1. UserA (serverA) share a file with these sharees:

user1(server1)
user2(server1)
user1(server2)
user2(server2)

The list of sharees is displayed in that order in UserA account

2. All the sharees accept the federated sharing
3. One of the sharees (for example, the first one: user1 in server1) does not want the file and removes (unshares) it

### Expected behaviour
The list of sharees for UserA is:

user2(server1)
user1(server2)
user2(server2)

user1(server1) was removed because the sharee unshared it

### Actual behaviour

The list of sharees for UserA is:

user1(server1)
user2(server1)
user1(server2)

It was removed the last one of the list instead of the unshared one. If another user unshared the content as well, it will be removed the last one of the list -> user1(server2)

### Server configuration
ServerA: {"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}
Server1: {"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}
Server2: {"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}

The usernames to check were the same as descripted before

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #23148

@jesmrec can you verify if this fixes the problem for you

cc @schiesbn @rullzer

### CODE REVIEW

**Comment by jesmrec** [comment]
@icewind1991 Works fine! :+1:

**Comment by nickvergessen** [comment]
Needs a test

**Comment by icewind1991** [comment]
added test

**Comment by icewind1991** [comment]
@karlitschek should probably be backported for 9.0.1

**Comment by karlitschek** [comment]
please backport once @jesmrec confirms that it is working.

**Comment by nickvergessen** [comment]
he already did

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
@icewind1991 please prepare the backport PR

**Comment by icewind1991** [comment]
stable9: https://github.com/owncloud/core/pull/23302

**Pull request merged**
