### PR TITLE
drop OC_Preferences

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @LukasReschke @DeepDiver1975 

I provided PRs for all apps that live in the owncloud org. Two are still open: see #12260

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @Raydiation @PVince81

**Comment by LukasReschke** [comment]
Cool! :+1:

**Comment by MorrisJobke** [comment]
* [x] send mail to devel mailing list: https://mailman.owncloud.org/pipermail/devel/2015-February/000997.html

**Comment by karlitschek** [comment]
ok with me as long as the public api doesn´t change.

**Comment by MorrisJobke** [comment]
@karlitschek I will never break the `\OCP\` namespace. We have methods in place there and this just cleans up behind the scenes.

**Comment by Raydiation** [comment]
:+1:

**Comment by PVince81** [comment]
:+1: goodbye legacy code

**Pull request merged**
