### PR TITLE
Add l10n support to encryption settings

### LINKED ISSUE #16111: Some strings are not translatable
### Steps to reproduce

1. Use owncloud in a language different to english
2. Enable encryption app.
3. Go to admin page.

### Expected behaviour
Strings related with encryption are translatable.

### Actual behaviour
They can't be translated.

https://github.com/owncloud/core/blob/master/settings/templates/admin.php#L345

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition. + encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
yes

### Client configuration

**browser**
Chrome 41

**Operating system**
Mac OS X

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #16111

cc @nickvergessen @DeepDiver1975

### CODE REVIEW

**Comment by nickvergessen** [comment]
:see_no_evil: :+1:

**Comment by DeepDiver1975** [comment]
While at it - please kill the new lines here - can cause confusion for translators
Encryption is a one way process.

**Comment by DeepDiver1975** [comment]
and here https://github.com/owncloud/core/blob/encryption-l10n-settings/settings/templates/admin.php#L364

**Comment by karlitschek** [comment]
:+1:

**Comment by schiesbn** [comment]
Ouch! :+1:

**Comment by MorrisJobke** [comment]
> While at it - please kill the new lines here - can cause confusion for translators

Done

**Pull request merged**
