### PR TITLE
[Stable 8.2] Make ownCloud work again in php 7.0.6

### PR DESCRIPTION
**Pull request by rullzer**
See https://bugs.php.net/bug.php?id=72117

Backport of https://github.com/owncloud/core/pull/24326
@karlitschek for approval

@cmonteroluque FYI. Up to you if we want this fix in 8.2.4 or 8.2.5

CC: @nickvergessen @PVince81 @LukasReschke @DeepDiver1975 @maki-chan @HLFH

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by Xenopathic** [comment]
:+1:

**Comment by karlitschek** [comment]
👍  nice fix and backport makes sense.

**Comment by sksbir** [comment]
worked for me : oc 8.2.3 newly installed ( downloaded tar ), with PHP7.0.6 + apache 2.4.20 compiled on fedora 23.  :+1:

**Pull request merged**
