### PR TITLE
Fix search result link for file results outside default list

### LINKED ISSUE #23774: Search for files that are not in subfolder of current folder causes infinite URL switching
search-loop

### Steps to reproduce
1. create folders `subfolder-testing` > `searchthis`
2. go to "Shared with you" folder
3. search for `searchthis`
4. click on result in "search results in other folders" list

### Expected behaviour
see search result

### Actual behaviour
infinite URL switching

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache/2.4.7

**Database:**
mysql  Ver 15.1 Distrib 5.5.47-MariaDB

**PHP version:**
PHP 5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.3 ee

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**

```
Enabled:
  - activity: 2.1.4
  - admin_audit: 0.6
  - enterprise_key: 0.1.0
  - external: 1.2
  - files: 1.2.1
  - files_drop: 0.4
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_sharing_log: 0.5
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firewall: 2.2.0
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - password_policy: 
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
  - user_ldap: 0.7.1
  - windows_network_drive: 0.1.1
Disabled:
  - encryption
  - files_antivirus
  - files_ldap_home
  - objectstore
  - sharepoint
  - user_external
  - user_shibboleth
```

**The content of config/config.php:**

nothing modified

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Safari 9.1

**Operating system:**
Mac OS X 10.11.4

@MorrisJobke Who can help here?

00005148

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/23774

### CODE REVIEW

**Comment by icewind1991** [comment]
Looks good :+1:

**Comment by butonic** [comment]
ahh, nice 👍

**Comment by PVince81** [comment]
backport was requested by @michaelstingl 

I don't think this is critical so will set for the next maintenance, not current one.

@DeepDiver1975 @dragotin

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/issues/25264
stable8.2: https://github.com/owncloud/core/issues/25265

**Pull request merged**
