### PR TITLE
no update routine needed from OC 7 to 8

### PR DESCRIPTION
**Pull request by blizzz**
The title says it all.

@DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I tested this previously by hand for another PR.

**Comment by blizzz** [comment]
> I tested this previously by hand for another PR.

Ah, that's handy :)

**Comment by schiesbn** [comment]
:+1:

**Comment by nickvergessen** [comment]
This will break, if someone updates from <7.0 to 8.0 ?
Just wrap the update.php content with a version compare?

**Comment by blizzz** [comment]
> This will break, if someone updates from <7.0 to 8.0 ?

We don't support them. Upgrade goes only major to next major version. Only starting 8.0 this will change someway.

**Comment by blizzz** [comment]
Well tests went fine:

> 06:29:46 Tests: 3050, Assertions: 9421, Skipped: 125.

but there are some warnings later like

```
06:29:46 PHP Warning:  Unknown: Cannot destroy the zip context in Unknown on line 0
06:29:46 PHP Stack trace:
06:29:46 PHP   1. {main}() /usr/local/bin/phpunit:0
06:29:46 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:605
06:29:46 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
```

and

```
06:30:07 WARN: [36m'Missing plural form in language file'[39m
```

but those seem unrelated…

**Comment by MorrisJobke** [comment]
> but those seem unrelated…

Let me check that

**Comment by MorrisJobke** [comment]
I have problems with the unit tests locally :(

**Comment by MorrisJobke** [comment]
But not just  with your branch, but with master too.

**Comment by DeepDiver1975** [comment]
there is an issue with the js unit test execution:

````
00:42:03.388 .........................................................................
00:42:03.939 .................................................[33mWARN [PhantomJS 1.9.8 (Linux)]: [39mDisconnected (1 times), because no message in 10000 ms.
00:42:14.934 
00:42:14.934 PhantomJS 1.9.8 (Linux): Executed 217 of 387 (skipped 2)[31m DISCONNECTED[39m (11.892 secs / -23716051 mins 53.353 secs)
00:42:15.481 Build step 'Conditional step (single)' marked build as failure

**Comment by MorrisJobke** [comment]
@DeepDiver1975 For me the JS unit tests run just fine.

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
let's deliver this clean for OC8 :+1:

**Pull request merged**
