### PR TITLE
Fix SMB domain usage

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Domain usage is wrong and is seems to be causing problems in servers requiring domain. This might has been wrong since the library update.
Servers which don't require a domain seems to work fine without this patch.

## Related Issue
https://github.com/owncloud/enterprise/issues/3427

## How Has This Been Tested?
Not tested yet.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
@DeepDiver1975 why has this not been merged and backported?
It has been approved 8 days ago.

**Comment by jvillafanez** [comment]
probably either some tests failing or waiting for codecov

**Comment by DeepDiver1975** [comment]
> why has this not been merged and backported?

:man_shrugging: 

But this one now anyhow needs a rebase ....

**Comment by DeepDiver1975** [comment]
> But this one now anyhow needs a rebase ....

taken care off ...

**Pull request merged**
