### PR TITLE
Let users configure security headers in their Webserver

### LINKED ISSUE #14073: Add ability to disable HSTS completely
This is a duplicate of #11909 but since this issue is already closed, I need to open a new one.

I'm currently on ownCloud 8.0.0.7 and my apache is already delivering an HSTS header. Unfortunately ownCloud adds an additional max-age=0 property to the HSTS header. Even when SSL settings are disabled on ownCloud's administration page.

This leads to an invalid HSTS header like `Strict-Transport-Security:	max-age=31536000; includeSubDomains, max-age=0` and Firefox is complaining about it.

It would be nice if there were an option to tell ownCloud to not touch existing HSTS headers (or send them at all).

### PR DESCRIPTION
**Pull request by LukasReschke**
Additional info see https://github.com/owncloud/core/pull/13455

Fixes #14073

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by LukasReschke** [comment]
I gotta LOVE this bot.

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by LukasReschke** [comment]
```
14:55:29 .......................Slave went offline during the build
14:55:44 ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@7bfbc7e8[name=lex-j2]
```

:tada: :tada: :tada:

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by LukasReschke** [comment]
```
15:00:05 fatal: unable to access 'https://github.com/owncloud/3rdparty.git/': Could not resolve host: github.com
```

What did I expect else……… :angel:

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by LukasReschke** [comment]
```
15:38:51 ..[33mWARN [PhantomJS 1.9.8 (Linux)]: [39mDisconnected (1 times), because no message in 10000 ms.
15:39:01 
15:39:01 PhantomJS 1.9.8 (Linux): Executed 93 of 418 (skipped 2)[31m DISCONNECTED[39m (10.056 secs / -23755463 mins 48.674 secs)
```

What?!?

**Comment by DeepDiver1975** [comment]
@owncloud-bot Retest this please.

**Comment by DeepDiver1975** [comment]
@owncloud-bot Retest this please.

**Comment by LukasReschke** [comment]
Seems like I have to setup phantomjs then. But still travelling atm.

**Comment by DeepDiver1975** [comment]
according to @PVince81 this happens local as well - he promissed to look into it

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
:+1:

**Comment by nickvergessen** [comment]
We don't delete the config from existing config.php files, but I guess this is fine.
The less file changes we do on it, the lesser the chance for breaking it. :see_no_evil: 

so :+1:

**Comment by LukasReschke** [comment]
Thanks. Added to https://github.com/owncloud/core/wiki/ownCloud-8.1-Features

**Pull request merged**
