### PR TITLE
Check the correct config for displaying the "notify by email" option

### LINKED ISSUE #21511: Mail notification checkbox not shown in sharee list
### Steps to reproduce
1. Settings: allowMailNotification=yes, allowPublicMailNotification=no
2. Share a file with another (internal) ownCloud user

### Expected behaviour
"Notify by email" checkbox should be shown in sharee list on the right

### Actual behaviour
"Notify by email" checkbox doesn't show up, unless allowPublicMailNotification is set as well

### Affected version
8.2.2 EE as well as git master 601457d

### Likely issue
Wrong (copy/pasted?) if statement in:
core/js/sharedialogshareelistview.js:29

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #21511 

@MorrisJobke @rullzer @PVince81 @rzg-kaiser

### CODE REVIEW

**Comment by nickvergessen** [comment]
@karlitschek backport to 8.2 was requested

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
