### PR TITLE
Setting a password was triggered twice when hitting [RETURN] - becaus…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…e both events are fired keyup and focusout

@jancborchardt @PVince81 @blizzz @icewind1991 please review

@karlitschek because we should not waste server resources I'd like to backport this to 8.1

### CODE REVIEW

**Comment by karlitschek** [comment]
as discussed. please backport :+1:

**Comment by blizzz** [comment]
Cannot reproduce the misbehaviour. Is it browser-specific?

**Comment by DeepDiver1975** [comment]
I am using chromium. 
Steps to reproduce:
- throw an exception in share.php
-  enter password
- see two error dialogs

**Comment by rullzer** [comment]
The js unit tests fails here because of debounce. Apparently this goes wrong if LoDash is initialised before the sinon faketimers are.

Lets see what google has to say about that.

**Comment by blizzz** [comment]
@DeepDiver1975 my way so far was to check how  many ajax request were opened. It was always one, on FF and now also on Chromium.

With the reproduction steps i am only getting an neverending spinner.

**Comment by DeepDiver1975** [comment]
I was not precise enough - sorry .... throwing an Exception in https://github.com/owncloud/core/blob/master/core/ajax/share.php#L64 should make the deal

```php
throw new Exception('Go AWAY!');

**Comment by blizzz** [comment]
Ok, got it.

It is not about the [Return] press, but  the following losing focus while the password input is not empty. This is what triggers the second call (the popup apparently steals focus). 

With this PR the password is being attempted to be stored after a second of not typing, and the entered text will be removed. No matter whether you attempted to write more or not. I don't like it from UX and might be  an issue from Accessibility PoV. But  the error pops up only once.

cc @jancborchardt

**Comment by DeepDiver1975** [comment]
> I don't like it from UX and might be an issue from Accessibility PoV.

This was basically modeled after the edit filed on the personal settings

**Comment by jancborchardt** [comment]
Probably we shouldn’t use the same mechanic of autosaving for a password field if it behaves like that. Only focus lost and enter should save the password.

**Comment by jancborchardt** [comment]
(And in the future, I will fix this with a proper confirm button for text fields: #15176)

**Comment by DeepDiver1975** [comment]
@jancborchardt I need a backportable solution to this NOW - THX

**Comment by jancborchardt** [comment]
@DeepDiver1975 as discussed - if focusout is the problem then just remove that, enter should suffice. Saving password after timeout can lead to unwanted results as @blizzz pointed out.

**Pull request closed without merging**
