### PR TITLE
[stable10] Dont't expose hashed password in ocs api

### PR DESCRIPTION
**Pull request by IljaN**
## Description
Don't expose hashed password in ocs api

## Related Issue

- Fixes https://github.com/owncloud/security-tracker/issues/301

## Motivation and Context
Mostly hardening. Attacker could brute-force the password if he knows the internal salt and instance-id

## How Has This Been Tested?
- Test manually by creating and accessing password protected link in UI
- Test manually by changing password in UI
- Unit-Tests adjusted

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
@IljaN what did you test exactly ? just the API calls or did you retest the share link dialog to see if it still detects a password presence / absence ? if not, please also test the latter

**Comment by IljaN** [comment]
@PVince81 Works as expected

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@IljaN please port to master

**Comment by phil-davis** [comment]
Forward port to `master` is PR #34726

**Pull request merged**
