### PR TITLE
Fix the docs of the exceptions and remove hardcoded language from the…

### PR DESCRIPTION
**Pull request by nickvergessen**
… message

@PVince81 @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
As discussed :+1: 

Should the other exceptions also be stripped of messages ?

**Comment by MorrisJobke** [comment]
:+1:

**Comment by nickvergessen** [comment]
I wonder, since we have custom exceptions, if we should add a method to the exception, which holds the array, instead of doing wodo

**Comment by DeepDiver1975** [comment]
oooops - where did the 'to Release' label go?

@nickvergessen I guess you need to open a new pr if you want to change something :see_no_evil:

**Comment by nickvergessen** [comment]
Okay *seufz*

**Comment by DeepDiver1975** [comment]
> Okay seufz

SOOOOORY :cat:

**Pull request merged**
