### PR TITLE
[stable8.1] fix writing to cache when fallback server should be used immediately

### PR DESCRIPTION
**Pull request by blizzz**
Backport of #23282

Please test and review @owncloud/ldap @owncloud/qa @MorrisJobke

### CODE REVIEW

**Comment by blizzz** [comment]
Errors weird, but not related to changes:

```
15:48:07 Regular expression run condition: Expression=[origin/master|origin/stable\d+(\.\d+)?], Label=[origin/backport-23282-stable8.1]
15:48:07 Run condition [Regular expression match] preventing perform for step [[E-mail Notification]]
15:48:07 Recording test results
```

```
PHP Fatal error:  Class 'Imagick' not found in /ssd/jenkins/workspace/server-master-linux-php5.4-ci/database/sqlite/label/SLAVE/lib/private/preview/bitmap.php on line 77
```

```
16:41:50 Waiting for docker to be started
16:41:50 curl: (7) Failed to connect to 172.17.14.250 port 80: Connection refused
16:41:50 .curl: (7) Failed to connect to 172.17.14.250 port 80: Connection refused
16:41:55 .curl: (7) Failed to connect to 172.17.14.250 port 80: Connection refused
16:42:00 .curl: (7) Failed to connect to 172.17.14.250 port 80: Connection refused
…
16:43:40 2016-03-18 16:43:50,654 - ERROR - owner - recipient 4 uploads /test/test4.txt through reshare etag for / previous ["56ec687d77da8"] new ["56ec687d77da8"] 'etag for / previous [%s] new [%s]' % (root_etag6, root_etag7)) failed in owner() ["/ssd/jenkins/workspace/smashbox-on-docker-ci/DOCKER_IMAGE/ubuntu_oc_lamp-git/TEST_NAME/test_sharePropagationGroups/mirallBranch/v2.0.2/slave/SMASH/smashbox/lib/owncloud/test_sharePropagationGroups.py" at line 179]
```

```
16:39:31 Waiting for docker to be started
16:39:31 curl: (7) Failed to connect to 172.17.14.249 port 80: Connection refused
16:39:31 .curl: (7) Failed to connect to 172.17.14.249 port 80: Connection refused
16:39:36 .curl: (7) Failed to connect to 172.17.14.249 port 80: Connection refused
16:39:41 .curl: (7) Failed to connect to 172.17.14.249 port 80: Connection refused
…
16:41:10 2016-03-18 16:41:21,099 - ERROR - owner - recipient2 uploads to /test/test3.txt etag for / previous ["56ec67ee81829"] new ["56ec67ee81829"] 'etag for / previous [%s] new [%s]' % (root_etag2, root_etag3)) failed in owner() ["/ssd/jenkins/workspace/smashbox-on-docker-ci/DOCKER_IMAGE/ubuntu_oc_lamp-git/TEST_NAME/test_sharePropagationInsideGroups/mirallBranch/v2.0.2/slave/SMASH/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 150]
(etc.)

**Comment by PVince81** [comment]
@blizzz are these errors happening on stable8.1 too ? Else you might want to rebase to nudge CI to retry ?

**Comment by blizzz** [comment]
*rebased*

**Comment by PVince81** [comment]
Not sure if PHP 5.4 used to fail on this branch ? @blizzz 
Unfortunately the results were deleted already.

**Comment by MorrisJobke** [comment]
> Not sure if PHP 5.4 used to fail on this branch ? @blizzz

cc @DeepDiver1975

**Comment by PVince81** [comment]
If not solved today it will fall off 8.1.7 and be moved to 8.1.8

**Comment by blizzz** [comment]
another rebase, let's see whether we can have a glimpse on failing tests

**Comment by blizzz** [comment]
server-master-linux-php5.4-ci/database=sqlite,label=SLAVE:

```
16:42:00 ...............................FFFF............FFFF........PHP Fatal error:  Class 'Imagick' not found in /ssd/jenkins/workspace/server-master-linux-php5.4-ci/database/sqlite/label/SLAVE/lib/private/preview/bitmap.php on line 77
```

that's not my PR :tongue:

**Comment by blizzz** [comment]
> If not solved today it will fall off 8.1.7 and be moved to 8.1.8

It does not have a single reviewer, yet, anyway.

**Comment by blizzz** [comment]
The PHP 5.4 test also failed for https://github.com/owncloud/core/pull/24284

**Comment by PVince81** [comment]
A bit too close to release to risk it now, moving to backport to 8.1.8

CC @cmonteroluque

**Comment by PVince81** [comment]
@davitol @davicente @MorrisJobke can you help testing this ?

**Comment by PVince81** [comment]
:+1: for the code.

Needs testing @owncloud/qa

**Comment by davitol** [comment]
@PVince81 Following the steps in comment https://github.com/owncloud/core/pull/23282#issue-141131029:
To reproduce:
1. Have a memory cache enabled
2. Have an LDAP server configured including a backup server
3. Turn off main LDAP server
4. Attempt login twice

Everything went fine and no problems were found. But as https://github.com/owncloud/core/pull/23282#issue-141131029 says, " If you monitor your network, the main ldap server should be contacted only once (!), and the fallback twice."
Monitoring my network it never tries to contact tothe main ldap server (something that can be logic due to step 3. Turn off main LDAP server). Anyway, due to no problems were found :+1:

**Comment by PVince81** [comment]
Thanks @davitol !

**Pull request merged**
