### PR TITLE
Feature/21413 better occ user help

### PR DESCRIPTION
**Pull request by edwardcrompton**
I'm suggesting this as a fix in response to this issue: https://github.com/owncloud/core/issues/21413 @RealRancor @jancborchardt @MorrisJobke

### CODE REVIEW

**Comment by RealRancor** [comment]
Some systems without sudo installed might need something like:

```
su -s /bin/sh apache -c php ./occ
```

Not quite sure if this also should be added here?

**Comment by MorrisJobke** [comment]
> Not quite sure if this also should be added here?

Not really. We maybe add a disclaimer that this only works on some systems (but it still should work on most of the systems).

**Comment by RealRancor** [comment]
Yes, a disclaimer is then definitely needed. If its not added i'm already seeing forums posts like "you're telling me a command but its not working !!!!1111"

**Comment by jancborchardt** [comment]
It says »try adding …«, so that’s good already. I think adding more text here will not help the visibility of the tip.

Good work @edwardcrompton! :)

**Comment by jancborchardt** [comment]
So :+1: from my side.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by edwardcrompton** [comment]
Thanks for reviewing @MorrisJobke @jancborchardt & @RealRancor. My first owncloud pull request accepted!

**Comment by MorrisJobke** [comment]
> Thanks for reviewing @MorrisJobke @jancborchardt & @RealRancor. My first owncloud pull request accepted!

Feel free to join us - we have a mailing list, forums and an IRC channel -https://doc.owncloud.org/server/9.0/developer_manual/commun/index.html

Maybe you want to start with some easy tasks - we have special junior jobs: https://github.com/owncloud/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22junior+job%22 

Feel free to ping me in IRC if you have a question :)

**Comment by jancborchardt** [comment]
Yeah! Cheers for you @edwardcrompton :) :beers:

**Pull request merged**
