### PR TITLE
Integrity Check: Add Substring Match to ExcludeFileByNameFilterIterator.php

### LINKED ISSUE #24218: Integrity checker: exclude .webapp file
Currently, the integrity checker complains when there is a .webapp file in the root of the OwnCloud installation directory. This file is generated, and required, by the webapp-config tool used to install all web apps on Gentoo.
### Steps to reproduce
1. Install OwnCloud using webapp-config into the root of a subdomain (suggested method):

``` bash
webapp-config -h cloud.example.com -d / -I owncloud 9.0.0
```
### Expected behaviour

The integrity checker should not complain.
### Actual behaviour

The integrity checker gives the following error:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
    - EXTRA_FILE
        - .webapp

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.webapp] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                )

        )

)
```
### Server configuration

**Operating system**: Gentoo Linux

**Web server:** nginx 1.8.1

**Database:** MariaDB 10.0.23

**PHP version:** 5.6.20

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** webapp-config

**Signing status (ownCloud 9.0 and above):** see above

### PR DESCRIPTION
**Pull request by kaindl**
Fixes #24218 
TODO:
- [ ] add unit test

### CODE REVIEW

**Comment by PVince81** [comment]
Code looks good. Can you add unit tests ?

Also in the future I hope we can move all this to the config file (separately): https://github.com/owncloud/core/issues/23186

**Comment by PVince81** [comment]
@kaindl do you need help for the unit tests ?

**Comment by PVince81** [comment]
@VicDeo can you review and/or take over ?

**Comment by VicDeo** [comment]
@kaindl can you please rebase it?

@PVince81  Looks good in general. There is a gut feeling that strpos is not the best way  for such validation  though
`/^\.webapp-owncloud-.*/`  as a pattern
and
`if (preg_match($excludedFilename, $this->current()->getFilename()) > 0) {`
instead of
`if (strpos($this->current()->getFilename(),$excludedFilename) !== false) {`

is stricter (and more nerdy) IMO

**Comment by VicDeo** [comment]
Superseded by https://github.com/owncloud/core/issues/26782

**Pull request closed without merging**
