### PR TITLE
Move \OCP to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @nickvergessen @PVince81 @DeepDiver1975 @MorrisJobke @ChristophWurst

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Needs some adjustments ``PHP Warning:  require_once(public/constants.php): failed to open stream: No such file or directory``

**Comment by rullzer** [comment]
Fixed already ;)

**Comment by ChristophWurst** [comment]
> Fixed already ;)

I'm too slow for this :snail:

**Comment by nickvergessen** [comment]
:+1:

**Comment by ChristophWurst** [comment]
``PHP Fatal error:  Uncaught Error: Class 'OCP\PreconditionNotMetException' not found in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/DB/Connection.php:297`` https://ci.owncloud.org/job/server-master-linux-php7-ci/database=sqlite,label=SLAVE/39222/console

**Comment by rullzer** [comment]
@ChristophWurst fixed

**Comment by ChristophWurst** [comment]
:+1:

**Pull request merged**
