### PR TITLE
Wait until mariadb is up and running

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
lets see .... https://ci.owncloud.org/job/server-master-linux-mariadb/

**Comment by MorrisJobke** [comment]
Looks good :)

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@rullzer mind reviewing? THX

**Comment by rullzer** [comment]
Looks good and also works locally.
:+1:

**Pull request merged**
