### PR TITLE
Fix version rename with files and folders

### PR DESCRIPTION
**Pull request by PVince81**
- fix moving folder into another folder (note: I observed this on stable7, stable8 and master!)
- fix moving file or folder into shared folder as recipient (https://github.com/owncloud/core/issues/15867)

Please review @schiesbn @nickvergessen @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
@karlitschek we might want to backport this: moving a folder loses the versions of all contained files when moved into another folder, happens on stable7 and stable8.

**Comment by karlitschek** [comment]
yes. please backport after 8.0.3 :+1:

**Comment by schiesbn** [comment]
looks good :+1:

**Comment by rullzer** [comment]
Looking good! :+1: 
Tested both scenarios and working!

I'm having problems with versions via webdav but that is also on master. So this is unrelated.

**Comment by PVince81** [comment]
@rullzer versions via WebDAV ? There is no such thing in ownCloud. Still curious to hear how you did it :smile:

**Comment by PVince81** [comment]
I'll take care of the backport to stable8.
@karlitschek you didn't specify whether you also agreed with a stable7 backport as it is losing versions there too.

**Comment by PVince81** [comment]
stable8: https://github.com/owncloud/core/pull/16369

**Pull request merged**
