### PR TITLE
removed XSS

### PR DESCRIPTION
**Pull request by peterprochaska**
## Description
removed xss with a htmlspecialchar command

## Related Issue
HackerOne Report #215410

## Motivation and Context
make ownCloud more secure

## How Has This Been Tested?
Inject HTML. On the result page the html was escaped

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Please backport

**Comment by Peter-Prochaska** [comment]
@PVince81 i have backported to all 9er versions, but in 8.2 i got some strange errors on my macbook. can you backport it for me?

**Comment by PVince81** [comment]
Please post the links to the backport PRs. I can have a look at your stable8.2 PR. Thanks

**Comment by Peter-Prochaska** [comment]
Here are the PR's:
https://github.com/owncloud/core/pull/27723
https://github.com/owncloud/core/pull/27722

**Comment by PVince81** [comment]
How about the stable8.2 ? Even if it produces error you could still push your branch

**Comment by PVince81** [comment]
Hmmm, looking at this again.

What result page ? The download.php actually delivers a download file.

This looks like it would break downloads if the parent folder contains a quote.

@Peter-Prochaska can you confirm and verify ?

**Comment by PVince81** [comment]
I just tested and indeed this breaks downloading: https://github.com/owncloud/core/issues/27807

Please revert and find a different fix.

Would be good to find out what page the reporter was talking about because this really is just a download endpoint.

Maybe if the URL points to a non-existing entry then the error message would render the file/dir name. In this case the message must be escaped.

**Pull request merged**
