### PR TITLE
[stable9] Remove shares of the root folder

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/25075 to stable9

Please review @owncloud/sharing @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
@DeepDiver1975 @guruz second review ?

**Comment by PVince81** [comment]
Setting as critical because without this some LDAP environments that have the "mail" attribute set cause new users to not be able to login at all.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
I tagged this as critical by mistake, mixed it up with another PR.

Also this PR causes regressions: https://github.com/owncloud/core/issues/25156

Will revert

**Pull request merged**
