### PR TITLE
Use new APCu API

### LINKED ISSUE #21095: APCu 5.1.2 & PHP7: \OC\Memcache\APCu not usable
### Steps to reproduce
1. Install PHP7 and APCu 5.1.2
2. Set `memcache.local` config to `\OC\Memcache\APCu`

### Expected behaviour
ownCloud should use the APCu extension for caching.

### Actual behaviour
Error message `Memcache \OC\Memcache\APCu not available for local cache Is the matching PHP module installed and enabled?`

### Reason
The new APCu version drops the APC compatibility layer. The extension is now called `apcu.so` (instead of `apc.so`) and the functions and classes have changed prefixes. There is a compatibility extension ( https://pecl.php.net/package/apcu_bc ) but relying on that would IMHO be too restrictive.

### Workaround
Replace `lib/private/memcache/apcu.php` with the following:
```php
<?php
/**
 * @author Andreas Fischer <bantu@owncloud.com>
 * @author Morris Jobke <hey@morrisjobke.de>
 * @author Otto Sabart <ottosabart@seberm.com>
 * @author Robin Appelman <icewind@owncloud.com>
 *
 * @copyright Copyright (c) 2015, ownCloud, Inc.
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

namespace OC\Memcache;

use OCP\IMemcache;

class APCu extends Cache implements IMemcache {
  use CASTrait {
    cas as casEmulated;
  }

  use CADTrait;

  public function get($key) {
    $result = apcu_fetch($this->getPrefix() . $key, $success);
    if (!$success) {
      return null;
    }
    return $result;
  }

  public function set($key, $value, $ttl = 0) {
    return apcu_store($this->getPrefix() . $key, $value, $ttl);
  }

  public function hasKey($key) {
    return apcu_exists($this->getPrefix() . $key);
  }

  public function remove($key) {
    return apcu_delete($this->getPrefix() . $key);
  }

  public function clear($prefix = '') {
    $ns = $this->getPrefix() . $prefix;
    $ns = preg_quote($ns, '/');
    $iter = new \APCUIterator('user', '/^' . $ns . '/', APC_ITER_KEY);
    return apcu_delete($iter);
  }

  /**
   * Set a value in the cache if it's not already stored
   *
   * @param string $key
   * @param mixed $value
   * @param int $ttl Time To Live in seconds. Defaults to 60*60*24
   * @return bool
   */
  public function add($key, $value, $ttl = 0) {
    return apcu_add($this->getPrefix() . $key, $value, $ttl);
  }

  /**
   * Increase a stored number
   *
   * @param string $key
   * @param int $step
   * @return int | bool
   */
  public function inc($key, $step = 1) {
    $this->add($key, 0);
    return apcu_inc($this->getPrefix() . $key, $step);
  }

  /**
   * Decrease a stored number
   *
   * @param string $key
   * @param int $step
   * @return int | bool
   */
  public function dec($key, $step = 1) {
    return apcu_dec($this->getPrefix() . $key, $step);
  }

  /**
   * Compare and set
   *
   * @param string $key
   * @param mixed $old
   * @param mixed $new
   * @return bool
   */
  public function cas($key, $old, $new) {
    // apc only does cas for ints
    if (is_int($old) and is_int($new)) {
      return apcu_cas($this->getPrefix() . $key, $old, $new);
    } else {
      return $this->casEmulated($key, $old, $new);
    }
  }

  static public function isAvailable() {
    if (!extension_loaded('apcu')) {
      return false;
    } elseif (!\OC::$server->getIniWrapper()->getBool('apc.enabled')) {
      return false;
    } elseif (!\OC::$server->getIniWrapper()->getBool('apc.enable_cli') && \OC::$CLI) {
      return false;
    } elseif (version_compare(phpversion('apcu'), '5.1.2') === -1) {
      return false;
    } else {
      return true;
    }
  }
}
```

Obviously this is not a fix that can be incorporated into core since it relies on PHP7 & APCu 5.1.2. But it will do as a workaround.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.9

**Database:** mysql 5.5

**PHP version:** 7.0 (via https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0 )

**ownCloud version:** 8.2.1.4

**Updated from an older ownCloud or fresh install:** yes

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - notifications: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - gallery
  - provisioning_api
  - search_lucene
  - templateeditor
  - updater
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "installed": true,
        "has_internet_connection": true,
        "datadirectory": "\/cloud\/data\/owncloud",
        "dbtype": "mysql",
        "redis": {
            "host": "localhost",
            "port": "6379"
        },
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "version": "8.2.1.4",
        "maintenance": false,
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "trashbin_retention_obligation": "auto",
        "apps_paths": [
            {
                "writable": false,
                "url": "\/apps",
                "path": "\/var\/www\/owncloud\/apps"
            },
            {
                "writable": true,
                "url": "\/user-apps",
                "path": "\/var\/www\/owncloud-apps\/user-apps"
            }
        ],
        "dbname": "owncloud",
        "instanceid": "uniq-id",
        "dbhost": "localhost",
        "loglevel": 2,
        "trusted_domains": [
            "domain.name"
        ],
        "mail_smtpmode": "php"
    }
}

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### ownCloud log (data/owncloud.log)
```json
{"reqId":"F4CugmkIqRCiIqhhACjF","remoteAddr":"1.2.3.4","app":"core","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Memcache \\\\OC\\\\Memcache\\\\APCu not available for local cache\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/server.php(267): OC\\\\Memcache\\\\Factory->__construct('8d4c1e106006f44...', Object(OC\\\\Log), '\\\\\\\\OC\\\\\\\\Memcache\\\\\\\\AP...', '\\\\\\\\OC\\\\\\\\Memcache\\\\\\\\AP...', NULL)\\n#1 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#2 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): Pimple\\\\Container->offsetGet('MemCacheFactory')\\n#3 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/server.php(753): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('MemCacheFactory')\\n#4 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/server.php(242): OC\\\\Server->getMemCacheFactory()\\n#5 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#6 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): Pimple\\\\Container->offsetGet('URLGenerator')\\n#7 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/server.php(726): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('URLGenerator')\\n#8 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/helper.php(174): OC\\\\Server->getURLGenerator()\\n#9 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template\\\/functions.php(169): OC_Helper::imagePath('', 'favicon.png')\\n#10 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/core\\\/templates\\\/layout.guest.php(15): image_path('', 'favicon.png')\\n#11 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(160): include('\\\/var\\\/www\\\/8.2.1\\\/...')\\n#12 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(138): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/8.2.1\\\/...')\\n#13 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template.php(211): OC\\\\Template\\\\Base->fetchPage()\\n#14 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template.php(233): OC_Template->fetchPage()\\n#15 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#16 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template.php(308): OC\\\\Template\\\\Base->printPage()\\n#17 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/index.php(49): OC_Template::printErrorPage('Memcache \\\\\\\\OC\\\\\\\\Me...', 'Is the matching...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/factory.php\",\"Line\":94}","level":3,"time":"2015-12-10T01:57:00+00:00"}
```

### PR DESCRIPTION
**Pull request by LukasReschke**
This one is available since APCu 4.0, since we require APCu 4.0.6 this works fine. Also it brings us PHP 7 compatibility and thus fixes https://github.com/owncloud/core/issues/21095

@d--j Please test.

### CODE REVIEW

**Comment by danimo** [comment]
@LukasReschke Looks good (didn't know apcu_* symbols were already present in 4.0.x. Also works fine for me: :+1:

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by d--j** [comment]
Sorry for late reply: I have tested this version and it works with APCu 5.1.2 & PHP7

**Comment by LukasReschke** [comment]
@karlitschek Shall we backport this? - We already deployed this on S3 so it seems stable :wink:

**Comment by karlitschek** [comment]
hmm. not a critical bugfix so no backport at the moment please. may i ask why we deployed unreleased code? but let's discuss this seperately

**Comment by LukasReschke** [comment]
> hmm. not a critical bugfix so no backport at the moment please. may i ask why we deployed unreleased code? but let's discuss this seperately

Well. Simply because we agreed on dogfooding and updating S3 to PHP 7 which however turned out to have problems with APCu as some Backwards Compatibility code has gone out of the main package. The alternatives are to just force PHP 7 users to compile either the BC package of APCu (https://github.com/krakjoe/apcu-bc) or to not use APCu at all.

**Comment by karlitschek** [comment]
well dogfooding released software. or at least merged code. But please no patches!

**Comment by jospoortvliet** [comment]
That's testing a fix in production, don't we all love that? :fearful:

**Comment by karlitschek** [comment]
Well we don't. This is not professional software development.

**Comment by MorrisJobke** [comment]
@carlaschroder Can we add a release note that APCu is not supported on owncloud 8.2 with PHP7. So if you want to use PHP7 and 8.2 you need to disable APCu and only use redis (also as local cache).

**Comment by carlaschroder** [comment]
@MorrisJobke I could, but...I've been delaying writing up anything about PHP 7 because it's not officially supported, not very tested, and people keep finding issues with it. And most distros don't package it. My suggestion is for the PHP 7 fans to create a Wiki page on using PHP 7 with ownCloud https://github.com/owncloud/documentation/wiki

@jospoortvliet

**Comment by jospoortvliet** [comment]
@MorrisJobke It isn't supported on ownCloud 8.2 with PHP 7? I have that running, on recommendation by @LukasReschke 

...

Fight!

**Comment by LukasReschke** [comment]
A wild @LukasReschke appears.
It uses https://github.com/krakjoe/apcu-bc.
This is very effective.

**Comment by karlitschek** [comment]
I agree with Carla. I think PHP 7 is for enthusiasts only at the moment. Still buggy and only good for the people who like bleeding edge. It works and is actually tested by us. But not mainstream yet and we should be careful with recommending something that is still not widely available.

**Comment by karlitschek** [comment]
@LukasReschke I talked with a few more people. Would it be possible to backport this in a way that it only effects PHP 7 installations?

**Comment by cmonteroluque** [comment]
@karlitschek, @LukasReschke, @MTRichards. From our conversation today and the inherent risks, ok not to backport?

**Comment by rtjdamen** [comment]
I fixed this by apt-get install php-apcu-bc on Ubuntu

**Comment by sksbir** [comment]
Hello
Using this patch with owncloud 8.2.4, PHP 7.0.6 and apcu 5.1.3  .

Everything seems to works : no more warning in admin page , and an big folder with lots of jpeg which loads jpg thumbnails a bit more faster the second time I load the page.
No messages at all in owncloud log , even in 'all' mode.

Must just remember to repatch after upgrade to OC 825.
Thank's for the patch.

**Pull request merged**
