### PR TITLE
Update google-api-php-client to 1.1.2

### PR DESCRIPTION
**Pull request by AdamWill**
Just keeping up to date with upstream. Adds an autoloader. Also adds a logging mechanism with a couple of implementations, we could perhaps see if we can take advantage of that to stream the library's logs into the OC logs, but I didn't look into that yet.

I'm getting an error from doctrine-dbal trying to run the tests ATM, but I at least did a manual test of 1.1.2 on my server and it seems to work fine. If anyone else can run the test suite on this it'd be a help, thanks.

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I just tested it with an existing Google Drive mount and it isn't accessible anymore. In the logs following appear: 
```
{"reqId":"\/rDd8yESHSZqZuxomrgl","remoteAddr":"127.0.0.1","app":"PHP","message":"Class 'Google_Task_Runner' not found at \/home\/mjob\/Projekte\/owncloud\/master\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Http\/REST.php#40","level":3,"time":"2015-03-11T12:16:02+00:00","method":"GET","url":"\/master\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=5PyI%2BOlJJDjniEmV5GpB%2Bnc6uKD%2FN5"}
```

**Comment by MorrisJobke** [comment]
@AdamWill Can you have a look?

BTW: I also merge master into this branch for testing. Otherwise it doesn't work, because of outdated stuff.

**Comment by AdamWill** [comment]
Huh, that's odd. the Task_Runner stuff comes in with https://github.com/google/google-api-php-client/commit/aaaa179d037b7832d62ed7d6bcef967da3afebbc , but that clearly landed a week after 1.1.2. Not sure what I did wrong there, I'm sure I just pulled in the 1.1.2 release via composer...well, I'll try and find a minute to re-do it.

**Comment by MorrisJobke** [comment]
@AdamWill Thanks a lot :)

**Comment by DeepDiver1975** [comment]
any files external related fixes will go into 8.2 - THX

**Comment by MorrisJobke** [comment]
cc @PVince81

**Comment by DeepDiver1975** [comment]
> any files external related fixes will go into 8.2 - THX

okay 9.0 :crying_cat_face:

**Comment by AdamWill** [comment]
OK, I don't care about this any more at this point - I stopped using ownCloud myself and I never used Google Drive, and a few people have reported Google changed the oAuth stuff or something and we're getting the thing where auth stops working after an hour anyway.

So I'm abandoning this. May I suggest that if you can't find anyone else who's interested in keeping the Drive stuff working, you drop it from core?

**Pull request closed without merging**
