### PR TITLE
[stable9.1] Integration test encryption homedir

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/26844 to stable9.1

:warning: I added an extra commit to temporarily enable the new tests on this PR, needs to be removed before merge ! :warning:

@DeepDiver1975 @SergioBertolinSG

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
I've run that failing test locally and it works fine.

**Comment by SergioBertolinSG** [comment]
https://github.com/owncloud/core/pull/26920 should be backported first. To avoid that failure.

**Comment by SergioBertolinSG** [comment]
And that PR requires https://github.com/owncloud/core/pull/26865 also.

**Comment by PVince81** [comment]
I added the commits of https://github.com/owncloud/core/pull/27003 here before the previous ones.

Let's let Jenkins do the testing for hopefully better results.

**Comment by PVince81** [comment]
Ran the tests locally (but had to cherry-pick https://github.com/owncloud/core/pull/27008):
- [x] OC_TEST_ENCRYPTION_ENABLED=1 OC_TEST_ALT_HOME=1
- [ ] OC_TEST_ENCRYPTION_ENABLED=1
- [ ] OC_TEST_ALT_HOME=1

So far, tests passed.

**Comment by DeepDiver1975** [comment]
> :warning: I added an extra commit to temporarily enable the new tests on this PR, needs to be removed before merge ! :warning:

ah - this is why I'm getting notifications about broken build :wink:

**Comment by SergioBertolinSG** [comment]
Running with  OC_TEST_ALT_HOME=1 there are two failures:

build/integration/features/sharing-v1.feature:860
build/integration/features/webdav-related.feature:425


Our old friend the blinking merging shares tests:
"Merging shares for recipient when shared from outside with group then user and recipient renames in between"

```
Then as "user1" gets properties of folder "/merge-test-outside-groups-renamebeforesecondshare-renamed" with                                        # FeatureContext::asGetsPropertiesOfFolderWith()
      | {http://owncloud.org/ns}permissions |
      HTTP error: 404 (Sabre\DAV\Exception)
And the single response should contain a property "{http://owncloud.org/ns}permissions" with value "SRDNVCK"  
```

And "Creating a folder with special chars" 

```
When as "user0" gets properties of folder "/test_folder:5" with                                       # FeatureContext::asGetsPropertiesOfFolderWith()
      | {DAV:}resourcetype |
      HTTP error: 404 (Sabre\DAV\Exception)
    Then the single response should contain a property "{DAV:}resourcetype" with value "{DAV:}collection"
```

**Comment by PVince81** [comment]
For me locally all tests passed with  OC_TEST_ALT_HOME=1.
Note that I ran the tests with a Mysql instance.

@SergioBertolinSG what's yours ?

**Comment by SergioBertolinSG** [comment]
MySQL as well.

**Comment by PVince81** [comment]
And Jenkins only has a single failure:
```
/var/lib/jenkins/workspace/owncloud-core_core_PR-26993-XV2N62E24JPAXCGLBGNNXV2DF7ZQXMJUZ24SGHXEFGTTYNVVLLZQ/build/integration/features/external-storage.feature:7
```

**Comment by PVince81** [comment]
Consistency, where are thou ?

**Comment by PVince81** [comment]
I'm out of ideas and I can't debug this locally since it all works fine.

@SergioBertolinSG can you debug the failures on your side, I suggest you start with the one that you have in common with Jenkins. Thanks.

**Comment by SergioBertolinSG** [comment]
@PVince81 sure, I'm trying in a new environment to see if those errors happen again.

**Comment by SergioBertolinSG** [comment]
Ok in my new environment all has passed correctly. 👍

**Comment by SergioBertolinSG** [comment]
The remaining problem happens only using OC_TEST_ENCRYPTION_ENABLED=1 and it happens locally as well.

**Comment by SergioBertolinSG** [comment]
The remaining error is also happening in master. So I guess it would be better to fix it in another PR for master and add the backport here.

Running locally OC_TEST_ENCRYPTION_ENABLED=1 ./run.sh features/external-storage.feature

It passes when the server is fresh installed. A second run makes it fail.

**Comment by SergioBertolinSG** [comment]
Error logs:

```php
[Tue Jan 24 12:24:52 2017] fclose() expects parameter 1 to be resource, string given at /var/www/html/encryption_vincent/lib/private/Files/Storage/Wrapper/Encryption.php#749
[Tue Jan 24 12:24:52 2017] Exception: {"Message":"multikeydecrypt with share key failed:error:0E06D06C:configuration file routines:NCONF_get_string:no value","Exception":"OCA\\Encryption\\Exceptions\\MultiKeyDecryptException","Code":0,"Trace":"#0 \/var\/www\/html\/encryption_vincent\/apps\/encryption\/lib\/KeyManager.php(423): OCA\\Encryption\\Crypto\\Crypt->multiKeyDecrypt('\\x93\\t\\x8E\\xBA~\\xA4.\\x9D\\xCE2\\xFC\\x8A\\xF5G\\x97...', '\\xA1-\\xAC\\x12\\f\\xF6o\\x84\\xE9Z[Bh\\xC51...', '-----BEGIN PRIV...')\n#1 \/var\/www\/html\/encryption_vincent\/apps\/encryption\/lib\/Crypto\/Encryption.php(186): OCA\\Encryption\\KeyManager->getFileKey('\/user0\/files\/lo...', 'user0')\n#2 \/var\/www\/html\/encryption_vincent\/lib\/private\/Files\/Stream\/Encryption.php(257): OCA\\Encryption\\Crypto\\Encryption->begin('\/user0\/files\/lo...', 'user0', 'w', Array, Array)\n#3 [internal function]: OC\\Files\\Stream\\Encryption->stream_open('ocencryption:\/\/', 'w', 0, NULL)\n#4 \/var\/www\/html\/encryption_vincent\/lib\/private\/Files\/Stream\/Encryption.php(197): fopen('ocencryption:\/\/', 'w', false, Resource id #63)\n#5 \/var\/www\/html\/encryption_vincent\/lib\/private\/Files\/Stream\/Encryption.php(179): OC\\Files\\Stream\\Encryption::wrapSource(Resource id #62, Resource id #63, 'ocencryption', 'OC\\\\Files\\\\Stream...', 'w')\n#6 \/var\/www\/html\/encryption_vincent\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(459): OC\\Files\\Stream\\Encryption::wrap(Resource id #62, 'foo\/textfile0.t...', '\/user0\/files\/lo...', Array, 'user0', Object(OCA\\Encryption\\Crypto\\Encryption), Object(OC\\Files\\Storage\\Local), Object(OC\\Files\\Storage\\Wrapper\\Encryption), Object(OC\\Encryption\\Util), Object(OC\\Encryption\\File), 'w', 0, 0, 0, true)\n#7 \/var\/www\/html\/encryption_vincent\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(743): OC\\Files\\Storage\\Wrapper\\Encryption->fopen('foo\/textfile0.t...', 'w')\n#8 \/var\/www\/html\/encryption_vincent\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(613): OC\\Files\\Storage\\Wrapper\\Encryption->copyBetweenStorage(Object(OCA\\Files_Trashbin\\Storage), 'files\/textfile0...', 'foo\/textfile0.t...', true, true)\n#9 \/var\/www\/html\/encryption_vincent\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(568): OC\\Files\\Storage\\Wrapper\\Encryption->moveFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'files\/textfile0...', 'foo\/textfile0.t...')\n#10 \/var\/www\/html\/encryption_vincent\/lib\/private\/Files\/View.php(789): OC\\Files\\Storage\\Wrapper\\Wrapper->moveFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'files\/textfile0...', 'foo\/textfile0.t...')\n#11 \/var\/www\/html\/encryption_vincent\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php(262): OC\\Files\\View->rename('\/textfile0.txt', '\/local_storage\/...')\n#12 \/var\/www\/html\/encryption_vincent\/lib\/composer\/sabre\/dav\/lib\/DAV\/CorePlugin.php(642): OCA\\DAV\\Connector\\Sabre\\ObjectTree->move('textfile0.txt', 'local_storage\/f...')\n#13 [internal function]: Sabre\\DAV\\CorePlugin->httpMove(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 \/var\/www\/html\/encryption_vincent\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#15 \/var\/www\/html\/encryption_vincent\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:MOVE', Array)\n#16 \/var\/www\/html\/encryption_vincent\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \/var\/www\/html\/encryption_vincent\/apps\/dav\/appinfo\/v1\/webdav.php(58): Sabre\\DAV\\Server->exec()\n#18 \/var\/www\/html\/encryption_vincent\/remote.php(164): require_once('\/var\/www\/html\/e...')\n#19 {main}","File":"\/var\/www\/html\/encryption_vincent\/apps\/encryption\/lib\/Crypto\/Crypt.php","Line":653,"User":"user0"}
[Tue Jan 24 12:24:52 2017] 127.0.0.1:37838 [500]: /remote.php/webdav/textfile0.txt
    And User "user0" moved file "/textfile0.txt" to "/local_storage/foo/textfile0.txt" # FeatureContext::userMovedFile()
      Server error response [url] http://localhost:8080/remote.php/webdav/textfile0.txt [status code] 500 [reason phrase] Internal Server Error (GuzzleHttp\Exception\ServerException)
```

**Comment by PVince81** [comment]
Let's investigate if the env is properly cleant up, maybe something remains between runs.

**Comment by PVince81** [comment]
Known issue with ext storages and encryption: deleting an ext storage leaves stray keys: https://github.com/owncloud/core/issues/10371
What was not known is that such keys could cause further issues when recreating the storage.
To be addressed separately.

- [ ] Plan: disable enc tests with local storage on master and cherry-pick the fix to this PR and the stable9 one

**Comment by PVince81** [comment]
Cherry-picked https://github.com/owncloud/core/pull/27015, hopefully all will pass on Jenkins at least.

**Comment by SergioBertolinSG** [comment]
I've run locally the remaining case using only encryption. All tests have passed.

**Comment by PVince81** [comment]
and you've removed the "TEMP" commit now, thanks.

Merging.

**Pull request merged**
