### PR TITLE
[encryption] fix upload to sftp

### PR DESCRIPTION
**Pull request by schiessle**
fix #https://github.com/owncloud/core/issues/15688

cc @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Huh, why?

**Comment by PVince81** [comment]
This also needs a unit test.
Please add one.
Thanks.

**Comment by PVince81** [comment]
I can confirm that this fixes the issue with SFTP.

**Comment by schiesbn** [comment]
> Huh, why?

because if we want the dirname of the sharePath we should also pass it as a parameter :wink:

**Comment by PVince81** [comment]
Hmm ok. Why did it work with FTP ? Maybe FTP doesn't use the stream wrapper directly ?

**Comment by schiesbn** [comment]
On FTP the if statement above (if (!$this->storage->file_exists($this->internalPath)) isn't true for some reasons. Probably a implementation detail how both storages write the file to the target location.

**Comment by nickvergessen** [comment]
Works for me :+1: 

However as per PVince81 a test would be nice

**Comment by schiesbn** [comment]
unit tests added

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
