### PR TITLE
Allow public upload when the quota is unlimited

### LINKED ISSUE #24961: Upload to shared folder via link, based on a federated share, tells no space left
### Steps to reproduce
1. Use a incoming federated share
2. Reshare a folder from this federated share via link, allow writing to
3. Logoff and open the link via the browser and try to upload a file

### Expected behaviour
Upload should be possible

### Actual behaviour
1. Creating a folder via the browser works, also renaming this folder
2. Uploading even a small 3KB file reports an error on the browser screen - no space left, see screenshot 

### Additional test:
3. Uploading a file / folder to this federated share via granted user works - no space problems
4. In the users homedir (not on the federated share!) create a subfolder and reshare via link, rw access, upload works

### Screenshots
Admin settings
image

Browser error message
image

Folder link share setting
image

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.14

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.2 RC1 (daily) Build:2016-04-28T03:03:12+00:00 795f321a1985b682bff584f252dd6f2fd95dad65

**Updated from an older ownCloud or fresh install:**
This was a fresh setup from tar and updated once, daily channel

**Where did you install ownCloud from:**
tar

**Signing status (ownCloud 9.0 and above):**

```
Datei nicht gefunden
Das ausgewählte Dokument wurde auf dem Server nicht gefunden.
Sie können zur Rückkehr zu ownCloud hier klicken.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ock982ae3c5s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxxx",
        "dbtype": "mysql",
        "version": "9.0.2.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "xxxx",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "xxxx",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

#### owncloud.log
no corresponding log entries

#### Browser log
no corresponding log entries

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #24961

Steps in the ticket

Should backport to 9.0 @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Argh... thanks :+1:

**Comment by PVince81** [comment]
Yes, please backport.

CC @cmonteroluque @DeepDiver1975

**Comment by PVince81** [comment]
Needs a second reviewer @mmattel @icewind1991 @owncloud/sharing

**Comment by mmattel** [comment]
Tested works :+1:

**Comment by mmattel** [comment]
One thing to add:
I uploaded a file via the shared link (30kb), waited 1min, and tried to delete it - the browser showed a yellow hint telling error deleting file. Deleting it via a user who has direct access to the share worked.

This was the owncloud error message logged:
```
{"reqId":"hVP90bz4Ogbh4iAPGanX","remoteAddr":"xx.xx.xx.xx","app":"webdav","message":"Exception: {\"Message\":\"Attempted to initialize mount points for null user and no user in session\",\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(89): OC\\\\Files\\\\Filesystem::initMountPoints(false)\\
n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(203): OCA\\\\Files_Trashbin\\\\Trashbin::getUidAndFilename('Innovation Enga...')\\
n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(160): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('Innovation Enga...')\\
n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(95): OCA\\\\Files_Trashbin\\\\Storage->doDelete('Company Present...', 'unlink')\\
n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1063): OCA\\\\Files_Trashbin\\\\Storage->unlink('Company Present...')\\
n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(645): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/proxyconf.pac', Array)\\
n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(333): OC\\\\Files\\\\View->unlink('\\\/proxyconf.pac')\\
n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\
n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('proxyconf.pac')\\
n#9[internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\
n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\
n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\
n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\
n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(82): Sabre\\\\DAV\\\\Server->exec()\\
n#14 \\\/var\\\/www\\\/owncloud\\\/public.php(74): require_once('\\\/var\\\/w...')\\
n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php\",\"Line\":376,\"User\":false}","level":4,"time":"2016-06-02T20:35:12+02:00","method":"DELETE","url":"\/public.php\/webdav\/proxyconf.pac","user":"--"}
```

**Comment by PVince81** [comment]
@mmattel this is likely unrelated, mind submitting a separate issue ?
Maybe first try if you also get the error when a quota is set, which would exclude the connection with this PR/issue.

**Comment by mmattel** [comment]
> Maybe first try if you also get the error when a quota is set, which would exclude the connection with this PR/issue.

Hmmm... I am only aware of setting quotas for users. I have not seen quotas for links/shares or mounts. The user who is granting the link for the share has a limit set of 1GB. (it is NOT unlimited).
Having a shared link means at least from my POV unlimited access as there is no dedicated access user behind - or the implementation is wrong as the granting users limit is not used for the link / underlaying storage.

This leads me to the following questions when using sharing via links:
- does quota work also on non home / external / mounted storage or shares (like the federated share)
- do we want to have a unlimited quota by default (the granting user has a quota set, but the link accessor does not)
- do we want to set a quota for this link, accessor independent (imho yes, to be implemented)

Suggestion: If there is no quota on the link, we should add a small text note on the page when creating it like ``Link will have no space restrictions``

**Comment by mmattel** [comment]
@nickvergessen @PVince81 
Regarding error "Attempted to initialize mount points": shall I open a new issue or document this in #24938

**Comment by nickvergessen** [comment]
Use #24938 until we see its a different story.

**Comment by nickvergessen** [comment]
Well since data is not owned by the "link sharee" I guess that is the point of the problem. We don't know the quota of the original owner, since such stuff is not public as far as I know. So despite the local quota files should still be able to upload.

**Comment by PVince81** [comment]
@nickvergessen please backport to 9.0, thanks

CC @DeepDiver1975

**Pull request merged**
