### PR TITLE
Fix extracting basename from path in sharing

### LINKED ISSUE #17770: Sharing folder in S3, the first letter of the folder is missed in the share dialog.
### Steps to reproduce
1. Upload a file using S3 as external storage inside a Subfolder
2. Share the subfolder with another user
3. Browse into the Subfolder and click on the share button of the file

### Expected behaviour
The name of the subfolder should be visible

### Actual behaviour
The first letter of the subfolder's name is missed

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"version":"8.0.5.2","versionstring":"8.0.5","edition":""

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - files
 - files_encryption
 - files_external
 - files_sharing
 - files_trashbin
 - files_versions
 - provisioning_api
Disabled:
 - user_ldap
 - user_webdavauth

**Are you using external storage, if yes which one:** yes; S3
**Are you using encryption:** yes
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

captura de pantalla 2015-07-21 a las 8 53 09

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Fixes #17770 

cc @davitol @PVince81 @DeepDiver1975 @schiesbn 

I thought about adding unit tests, but I'm not familiar with the files_sharing code. Feel free someone to push directly here

@karlitschek Backport? This affects 8.1 and 8.0 only

### CODE REVIEW

**Comment by PVince81** [comment]
@Xenopathic was this another obscure case of "leading slash" vs "no leading slash" in path ?

**Comment by PVince81** [comment]
:+1: tested, works

**Comment by PVince81** [comment]
I don't think this is critical and rather a corner case, and it's only the displayed name and doesn't affect functionality. So not sure about the backport.

**Comment by PVince81** [comment]
Original ticket has sev4-low => no backport.

**Comment by MorrisJobke** [comment]
Tested and also works for "normal" shares.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by karlitschek** [comment]
makes sense. backport makes sense :+1:

**Comment by PVince81** [comment]
@karlitschek are you sure ? see https://github.com/owncloud/core/pull/18389#issuecomment-132199493

**Comment by karlitschek** [comment]
@PVince81 Agreed. i changed my mind ;-) let's not backport for now and evaluate later.

**Pull request merged**
