### PR TITLE
Fix format of log/private/ocs.php

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes https://github.com/owncloud/core/pull/14314#discussion_r37305256

cc @Xenopathic @rullzer @Raydiation @nickvergessen

### CODE REVIEW

**Comment by Raydiation** [comment]
:+1:

**Comment by Xenopathic** [comment]
:+1:

**Comment by MorrisJobke** [comment]
C'mon oracle

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Pull request merged**
