### PR TITLE
Cache js, css and files for half a year, woff for a week

### PR DESCRIPTION
**Pull request by butonic**
## Description

increases the cache duration for css and js files from 2 hours to half a year. Should they change the versionhash changes as well and a new file is fetched. Half a year should be long enough for oc updates.

Also allows caching woff files for 7 days. Currently, there is no versionhash available, but pressing F5 will also refresh the woff files.

## Related Issue

Cach-Control header for Avatars: https://github.com/owncloud/core/issues/26585

## Motivation and Context

I want as many resources as possible to be cached. This is a low hanging fruit.

## How Has This Been Tested?

Firefox, Chromium, Edge

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by butonic** [comment]
hm, may need nginx documentation changes

**Comment by butonic** [comment]
@PVince81 cant we use make to add a hash to the woff references in css: https://github.com/owncloud/core/blob/master/core/css/fonts.css ?

**Comment by PVince81** [comment]
@butonic we could but would not want to overwrite the original file. It would have to be a copy of the file, either side by side or in a another "build" folder.

Do we really still need "woff" files ? I thought those were a workaround for old browsers that didn't support ttf ?

**Comment by butonic** [comment]
@PVince81 the only browser that loads the woff files is Chromium on my ubuntu.

**Comment by PVince81** [comment]
What if we don't provide it, will it then load the ttf files instead then ?

**Comment by PhilippSchaffrath** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
