### PR TITLE
Migrate from jQuery 1

### PR DESCRIPTION
**Pull request by lordelix**
A list of removed, deprecated and altered methods. Work on it and update the list below using the [migration check script](https://gist.github.com/felixheidecke/c32ab1b38f7091f5c5d18d4a24fd0024)

## Removed

`.browser()`

`.live()`

- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js => test code only, ignore

`.die()`

- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js => test code only, ignore

`.sub()`

`.andSelf()`

- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-ui-1.8.14.custom.min.js => test code only, ignore

## Changed

`.toggle()`

- [x] apps/files/js/keyboardshortcuts.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/bootstrap.min.js => unrelated to product, test only, ignore

`.add()`

(most are unrelated to jquery)
- [x] apps/comments/tests/js/commentstabviewSpec.js
- [x] apps/federatedfilesharing/js/3rdparty/gs-share/gs-share.js
- [x] apps/files/js/filelist.js
- [x] apps/files/tests/js/fileUploadSpec.js
- [x] apps/files/tests/js/fileactionsSpec.js
- [x] apps/files/tests/js/fileactionsmenuSpec.js
- [x] apps/files/tests/js/filelistSpec.js
- [x] apps/files/tests/js/filesummarySpec.js
- [x] apps/files_external/js/app.js => returned element order doesn't matter here
- [x] apps/files_external/js/statusmanager.js
- [x] apps/files_sharing/tests/js/appSpec.js
- [x] apps/files_sharing/tests/js/sharedfilelistSpec.js
- [x] apps/systemtags/tests/js/systemtagsinfoviewSpec.js
- [x] core/js/shareconfigmodel.js
- [x] core/js/sharedialoglinklistview.js
- [x] core/js/tests/specs/systemtags/systemtagsinputfieldSpec.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-ui-1.8.14.custom.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/d3.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/holder.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/jquery.min.js

`.after()`

- [x] apps/comments/js/activitytabviewplugin.js => activity for comment still appears correctly
- [x] apps/comments/js/commentstabview.js => edit comment still works
- [x] apps/files/js/breadcrumb.js => breadcrumb ellipsis still works
- [x] apps/files/js/fileactions.js
- [x] apps/files/js/jquery.fileupload.js => upload still works (this lib also requires jquery.ui which was updated here)
- [x] apps/files/js/search.js => results in other folders still appear correctly
- [x] apps/files_external/js/mountsfilelist.js => ext storage list in files app columns still correct
- [x] core/js/js.js
- [x] core/js/systemtags/systemtagsinputfield.js
- [x] core/search/js/search.js

`.before()`

- [x] apps/comments/js/commentstabview.js
- [x] apps/files/js/filelist.js
- [x] apps/files_sharing/js/sharedfilelist.js
- [x] core/js/multiselect.js
- [x] core/js/singleselect.js
- [x] core/js/update.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js

`.replaceWith()`

- [x] apps/comments/js/commentstabview.js
- [x] apps/files/js/tagsplugin.js
- [x] core/js/lostpassword.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/jquery.min.js

`.appendTo()`

- [x] apps/files_external/js/settings.js
- [x] apps/files_sharing/js/public.js
- [x] core/js/jquery.ocdialog.js
- [x] core/js/multiselect.js => multiselect in user management group dropdown still works
- [x] core/js/setup.js
- [x] core/js/share.js
- [x] core/js/sharedialogview.js
- [x] core/js/tags.js
- [x] core/js/update.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-ui-1.8.14.custom.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/bootstrap.min.js

`.insertBefore()`

- [x] apps/federatedfilesharing/js/3rdparty/gs-share/gs-share.js
- [x] apps/files/js/filelist.js
- [x] core/js/jquery.ocdialog.js
- [x] core/js/lostpassword.js
- [x] core/js/multiselect.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/d3.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/holder.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/html5shiv.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/jquery.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/respond.min.js
- [x] tests/karma-coverage/Chrome 56.0.2924 (Linux 0.0.0)/prettify.js
- [x] tests/karma-coverage/PhantomJS 2.1.1 (Linux 0.0.0)/prettify.js
- [x] tests/karma-coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify.js
- [x] tests/output/coverage/PhantomJS 2.1.1 (Mac OS X 0.0.0)/prettify.js

`.insertAfter()`

- [x] core/js/jquery-showpassword.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/bootstrap.min.js

`.replaceAll()`

`.ajax()`

- [x] apps/federation/js/settings-admin.js
- [x] apps/files/js/jquery.fileupload.js => upload still works
- [x] apps/files/js/tagsplugin.js
- [x] apps/files_external/js/mountsfilelist.js
- [x] apps/files_external/js/settings.js
- [x] apps/files_external/js/statusmanager.js
- [x] apps/files_sharing/js/app.js
- [x] apps/files_sharing/js/external.js
- [x] apps/files_sharing/js/public.js
- [x] apps/files_sharing/js/sharedfilelist.js
- [x] apps/files_trashbin/js/filelist.js
- [x] apps/updatenotification/js/admin.js
- [x] core/js/js.js
- [x] core/js/setupchecks.js => see commit on this PR to fix it
- [x] core/js/share.js
- [x] core/js/shareitemmodel.js => reading, sharing and edit share, delete share still works (had to hack autocomplete due to jquery.ui-fixes.css bug)
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/jquery.min.js

## Minor

`.trigger()` (mostly checkboxes/radio)

- [x] apps/comments/js/commentcollection.js
- [x] apps/comments/tests/js/commentstabviewSpec.js
- [x] apps/files/js/app.js
- [x] apps/files/js/file-upload.js => upload works
- [x] apps/files/js/fileactions.js => file actions work
- [x] apps/files/js/filelist.js
- [x] apps/files/js/jquery.fileupload.js
- [x] apps/files/js/keyboardshortcuts.js
- [x] apps/files/js/navigation.js
- [x] apps/files/js/newfilemenu.js
- [x] apps/files/js/tagsplugin.js
- [x] apps/files/tests/js/appSpec.js
- [x] apps/files/tests/js/fileUploadSpec.js
- [x] apps/files/tests/js/filelistSpec.js
- [x] apps/files/tests/js/newfilemenuSpec.js
- [x] apps/files_external/js/oauth2.js
- [x] apps/files_external/js/settings.js
- [x] apps/files_external/tests/js/settingsSpec.js
- [x] apps/files_sharing/js/sharetabview.js
- [x] apps/files_sharing/tests/js/PublicUploadViewSpec.js
- [x] apps/files_sharing/tests/js/appSpec.js
- [x] apps/files_sharing/tests/js/shareSpec.js
- [x] apps/files_versions/js/versionmodel.js
- [x] apps/files_versions/js/versionstabview.js
- [x] apps/files_versions/tests/js/versionstabviewSpec.js
- [x] apps/systemtags/js/systemtagsfilelist.js
- [x] apps/systemtags/tests/js/systemtagsfilelistSpec.js
- [x] apps/systemtags/tests/js/systemtagsinfoviewSpec.js
- [x] core/js/apps.js
- [x] core/js/jquery-showpassword.js
- [x] core/js/jquery.ocdialog.js
- [x] core/js/js.js
- [x] core/js/login.js
- [x] core/js/lostpassword.js
- [x] core/js/multiselect.js
- [x] core/js/oc-backbone-webdav.js
- [x] core/js/oc-dialogs.js
- [x] core/js/setup.js
- [x] core/js/sharedialoglinkshareview.js
- [x] core/js/shareitemmodel.js
- [x] core/js/systemtags/systemtagscollection.js
- [x] core/js/systemtags/systemtagsinputfield.js
- [x] core/js/tags.js
- [x] core/js/tests/specs/coreSpec.js
- [x] core/js/tests/specs/sharedialoglinklistviewSpec.js
- [x] core/js/tests/specs/systemtags/systemtagsinputfieldSpec.js
- [x] lib/composer/behat/mink-selenium2-driver/src/Resources/syn.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-ui-1.8.14.custom.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/bootstrap.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/jquery.min.js

`.click()`

- [x] apps/comments/js/commentstabview.js
- [x] apps/comments/tests/js/commentstabviewSpec.js
- [x] apps/comments/tests/js/filespluginSpec.js
- [x] apps/federatedfilesharing/js/settings-personal.js
- [x] apps/files/js/filelist.js
- [x] apps/files/tests/js/appSpec.js
- [x] apps/files/tests/js/breadcrumbSpec.js
- [x] apps/files/tests/js/detailsviewSpec.js
- [x] apps/files/tests/js/favoritespluginspec.js
- [x] apps/files/tests/js/fileactionsSpec.js
- [x] apps/files/tests/js/fileactionsmenuSpec.js
- [x] apps/files/tests/js/filelistSpec.js
- [x] apps/files/tests/js/mainfileinfodetailviewSpec.js
- [x] apps/files/tests/js/newfilemenuSpec.js
- [x] apps/files/tests/js/tagspluginspec.js
- [x] apps/files_external/tests/appSpec.js
- [x] apps/files_external/tests/js/settingsSpec.js
- [x] apps/files_sharing/js/public.js
- [x] apps/files_sharing/tests/js/appSpec.js
- [x] apps/files_sharing/tests/js/shareSpec.js
- [x] apps/files_trashbin/js/filelist.js
- [x] apps/files_trashbin/tests/js/filelistSpec.js
- [x] apps/files_versions/tests/js/versionstabviewSpec.js
- [x] apps/updatenotification/js/admin.js
- [x] core/js/apps.js
- [x] core/js/jquery.ocdialog.js
- [x] core/js/js.js
- [x] core/js/login.js
- [x] core/js/lostpassword.js
- [x] core/js/multiselect.js
- [x] core/js/setup.js => autoexpand after error still works
- [x] core/js/share.js
- [x] core/js/singleselect.js
- [x] core/js/tests/specs/coreSpec.js
- [x] core/js/tests/specs/sharedialoglinklistviewSpec.js
- [x] core/js/tests/specs/sharedialogshareelistview.js
- [x] core/js/tests/specs/sharedialogviewSpec.js
- [x] lib/composer/behat/mink-selenium2-driver/src/Resources/syn.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/jquery.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/nv.d3.min.js

`.focus()`

- [x] apps/federatedfilesharing/js/3rdparty/gs-share/gs-share.js
- [x] apps/federation/js/settings-admin.js => add server auto-focus field
- [x] apps/files/js/filelist.js => focus on rename works
- [x] apps/files/js/files.js => webdav URL focus + autoselect works
- [x] apps/files/js/jquery.fileupload.js => unused as we have no upload field
- [x] apps/files/js/mainfileinfodetailview.js => permalink focus
- [x] apps/files/js/newfilemenu.js => create file/folder focus on name field
- [x] apps/files_external/js/settings.js => backend select focus
- [x] apps/files_external/js/statusmanager.js
- [x] apps/files_sharing/js/public.js => download field autofocus, add to ownCloud autofocus
- [x] core/js/jquery.ocdialog.js
- [x] core/js/js.js => selectRange worked in above cases
- [x] core/js/multiselect.js => create group in dropdown autofocus worked
- [x] core/js/sharedialoglinkshareview.js => autofocus first field
- [x] core/js/sharedialogview.js => initial focus on share field works
- [x] core/js/singleselect.js (unused?)
- [x] core/js/systemtags/systemtagsinputfield.js => rename tag focus works
- [x] core/search/js/search.js => ctrl+f focusses search box (I can't believe we overrode this shortcut!)
- [x] lib/composer/behat/mink-selenium2-driver/src/Resources/syn.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-ui-1.8.14.custom.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/bootstrap.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/jquery.min.js

## Neglectable

`.data()`

- [x] apps/comments/js/commentstabview.js
- [x] apps/comments/js/filesplugin.js
- [x] apps/federatedfilesharing/js/settings-personal.js
- [x] apps/files/js/breadcrumb.js
- [x] apps/files/js/file-upload.js
- [x] apps/files/js/fileactions.js
- [x] apps/files/js/filelist.js
- [x] apps/files/js/files.js
- [x] apps/files/js/jquery.fileupload.js
- [x] apps/files/js/tagsplugin.js
- [x] apps/files/tests/js/filelistSpec.js
- [x] apps/files_external/js/settings.js
- [x] apps/files_external/js/statusmanager.js
- [x] apps/files_external/tests/js/settingsSpec.js
- [x] apps/files_sharing/js/public.js
- [x] core/js/apps.js
- [x] core/js/jquery-showpassword.js
- [x] core/js/jquery.avatar.js
- [x] core/js/js.js
- [x] core/js/multiselect.js
- [x] core/js/oc-dialogs.js
- [x] core/js/select2-toggleselect.js
- [x] core/js/setup.js
- [x] core/js/share.js
- [x] core/js/shareconfigmodel.js
- [x] core/js/sharedialoglinksocialview.js
- [x] core/js/sharedialogresharerinfoview.js
- [x] core/js/sharedialogshareelistview.js
- [x] core/js/sharedialogview.js
- [x] core/js/singleselect.js
- [x] core/js/tests/specs/jquery.avatarSpec.js
- [x] core/js/tests/specs/sharedialogviewSpec.js
- [x] core/search/js/search.js
- [x] lib/composer/behat/mink-selenium2-driver/src/Resources/syn.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-ui-1.8.14.custom.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/bootstrap.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/d3.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/nv.d3.min.js

`.parents()`

- [x] apps/files/js/files.js
- [x] apps/files_external/js/statusmanager.js
- [x] core/js/lostpassword.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-ui-1.8.14.custom.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/bootstrap.min.js

`.attr()`

- [x] apps/comments/js/commentstabview.js
- [x] apps/comments/js/filesplugin.js
- [x] apps/comments/tests/js/commentstabviewSpec.js
- [x] apps/comments/tests/js/filespluginSpec.js
- [x] apps/federatedfilesharing/js/settings-admin.js
- [x] apps/federation/js/settings-admin.js
- [x] apps/files/js/breadcrumb.js
- [x] apps/files/js/detailsview.js
- [x] apps/files/js/favoritesplugin.js
- [x] apps/files/js/file-upload.js
- [x] apps/files/js/fileactions.js
- [x] apps/files/js/fileactionsmenu.js
- [x] apps/files/js/filelist.js
- [x] apps/files/js/files.js
- [x] apps/files/js/jquery.fileupload.js
- [x] apps/files/js/navigation.js
- [x] apps/files/js/newfilemenu.js
- [x] apps/files/js/search.js
- [x] apps/files/js/tagsplugin.js
- [x] apps/files/tests/js/breadcrumbSpec.js
- [x] apps/files/tests/js/detailsviewSpec.js
- [x] apps/files/tests/js/favoritesfilelistspec.js
- [x] apps/files/tests/js/fileactionsSpec.js
- [x] apps/files/tests/js/fileactionsmenuSpec.js
- [x] apps/files/tests/js/filelistSpec.js
- [x] apps/files/tests/js/mainfileinfodetailviewSpec.js
- [x] apps/files/tests/js/newfilemenuSpec.js
- [x] apps/files/tests/js/tagspluginspec.js
- [x] apps/files_external/js/app.js
- [x] apps/files_external/js/oauth1.js :no_entry_sign: => fix needed to use prop() for disabled
- [x] apps/files_external/js/oauth2.js :no_entry_sign: => fix needed to use prop() for disabled
- [x] apps/files_external/js/public_key.js
- [x] apps/files_external/js/settings.js :no_entry_sign: => fix needed to use prop() for disabled
- [x] apps/files_external/js/statusmanager.js
- [x] apps/files_external/tests/js/mountsfilelistSpec.js
- [x] apps/files_sharing/js/app.js
- [x] apps/files_sharing/js/public.js
- [x] apps/files_sharing/js/settings.js
- [x] apps/files_sharing/js/share.js
- [x] apps/files_sharing/js/sharedfilelist.js
- [x] apps/files_sharing/tests/js/appSpec.js
- [x] apps/files_sharing/tests/js/shareSpec.js
- [x] apps/files_sharing/tests/js/sharedfilelistSpec.js
- [x] apps/files_trashbin/js/app.js
- [x] apps/files_trashbin/js/filelist.js
- [x] apps/files_trashbin/tests/js/filelistSpec.js
- [x] apps/files_versions/js/versionstabview.js
- [x] apps/files_versions/tests/js/versionstabviewSpec.js
- [x] apps/systemtags/js/app.js
- [x] apps/updatenotification/js/admin.js
- [x] apps/updatenotification/js/notification.js
- [x] core/js/eventsource.js
- [x] core/js/jquery-showpassword.js
- [x] core/js/jquery.ocdialog.js
- [x] core/js/js.js
- [x] core/js/lostpassword.js
- [x] core/js/multiselect.js :no_entry_sign: change `attr('selected', 'selected')` with `prop('selected')` ??
- [x] core/js/oc-dialogs.js
- [x] core/js/octemplate.js
- [x] core/js/setup.js  :no_entry_sign: => fix needed to use prop() for disabled
- [x] core/js/share.js
- [x] core/js/sharedialoglinklistview.js
- [x] core/js/sharedialoglinkshareview.js :no_entry_sign: => fix needed to use prop() for disabled
- [x] core/js/sharedialogshareelistview.js
- [x] core/js/sharedialogview.js :no_entry_sign: => fix needed to use prop() for disabled
- [x] core/js/singleselect.js no_entry_sign: change `attr('selected', 'selected')` with `prop('selected')` ??
- [x] core/js/systemtags/systemtagsinputfield.js
- [x] core/js/tests/specs/shareSpec.js
- [x] core/js/tests/specs/sharedialoglinklistviewSpec.js
- [x] core/js/tests/specs/sharedialoglinkshareviewSpec.js
- [x] core/js/tests/specs/sharedialogshareelistview.js
- [x] core/js/tests/specs/sharedialogviewSpec.js
- [x] core/js/update.js
- [x] core/search/js/search.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-ui-1.8.14.custom.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/bootstrap.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/d3.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/jquery.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/nv.d3.min.js

`.prop()`

- [x] apps/comments/js/commentstabview.js
- [x] apps/comments/tests/js/commentstabviewSpec.js
- [x] apps/files/js/app.js
- [x] apps/files/js/filelist.js
- [x] apps/files/js/files.js
- [x] apps/files/js/jquery.fileupload.js => works, but this lib is using `.prop()` to set anchor attributes... might need update :question: 
- [x] apps/files/tests/js/filelistSpec.js
- [x] apps/files_external/js/oauth2.js
- [x] apps/files_external/js/settings.js
- [x] apps/files_external/tests/js/settingsSpec.js
- [x] apps/files_sharing/js/authenticate.js
- [x] apps/files_sharing/js/public.js
- [x] apps/files_trashbin/js/filelist.js
- [x] apps/systemtags/js/systemtagsfilelist.js
- [x] core/js/jquery-showpassword.js => works,it's using prop() to set type as per comment and still works
- [x] core/js/js.js => works, but better change it to `.attr()` :question: 
- [x] core/js/multiselect.js
- [x] core/js/oc-dialogs.js
- [x] core/js/sharedialogexpirationview.js
- [x] core/js/sharedialogmailview.js
- [x] core/js/sharedialogshareelistview.js
- [x] core/js/tests/specs/sharedialoglinkshareviewSpec.js
- [x] core/js/tests/specs/sharedialogmailviewSpec.js
- [x] core/js/visitortimezone.js
- [x] core/search/js/search.js :question: it uses `.prop('scrollHeight')` to get container height
- [x] lib/composer/behat/mink/driver-testsuite/web-fixtures/js/jquery-1.6.2-min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/bootstrap.min.js
- [x] lib/composer/phpunit/php-code-coverage/src/Report/Html/Renderer/Template/js/jquery.min.js

### CODE REVIEW

**Comment by PVince81** [comment]
@felixheidecke can we have checkboxes so we can tick them after having checked the code usage for each ?

I believe we should also delete jquery-migrate here ?

**Comment by felixheidecke** [comment]
@PVince81 Checkboxes are check. Delete jquery-migrate? Didn't find any on the list.

**Comment by PVince81** [comment]
@felixheidecke I've fixed the failing tests about setup checks. Now all pass for me locally.

**Comment by PVince81** [comment]
- [ ] BUG: share autocomplete doesn't open any more

I hope it's not an implicit jquery.ui update as with https://github.com/owncloud/core/pull/30088

**Comment by PVince81** [comment]
@felixheidecke oh no, it seems you also update jquery.ui to 1.12 in this PR ?

oh well, at least in all the other jquery tickets we could confirm that despite the jquery.ui update most things still worked

**Comment by PVince81** [comment]
- [ ] BUG: browser back button doesn't always navigate back to previous folder. history API broken ? need to compare with master

**Comment by PVince81** [comment]
- [ ] BUG: setup page styles broken, maybe jquery.ui related:
image

**Comment by PVince81** [comment]
I found some occurrences where `attr()` was used for disabled/checked properties. I've replaced them in the last commit and ticked the checkboxes in the above list.

There are others where `.attr('selected')` is used on select options. I'm not sure if those need to be changed again: marked in the list, unticked.

**Comment by PVince81** [comment]
Ok, I'm done with the checkboxes.

- [ ] check unprocessed checkboxes
- [ ] recheck style issues as jquery.ui update messed up some things

- [ ] sort out jquery.ui update, will need more commits here.

@felixheidecke please run your script for the jquery.ui updates (there are two steps)

**Comment by PVince81** [comment]
- [x] fixed jquery.ui autocomplete to display again
- [ ] need minor fix to autcomplete active item "ui-state-active" to avoid jumpiness when moving the selection

**Comment by felixheidecke** [comment]
> @felixheidecke oh no, it seems you also update jquery.ui to 1.12 in this PR?

I did. I am opening a new branch based on this one for jquery.ui update purposes.

**Comment by PVince81** [comment]
@felixheidecke maybe better reuse the same branch as we need to test the fixes in a combined manner ?

**Comment by felixheidecke** [comment]
All checkboxes have been checked and we are ready to go.

**Comment by PVince81** [comment]
please scroll down, there are more checkboxes

**Comment by felixheidecke** [comment]
@PVince81 https://github.com/owncloud/core/pull/32060#issuecomment-411481245
>  BUG: share autocomplete doesn't open any more

Can not confirm. Please re-check.

**Comment by felixheidecke** [comment]
@PVince81 https://github.com/owncloud/core/pull/32060#issuecomment-412068451
>  BUG: browser back button doesn't always navigate back to previous folder. history API broken ? need to compare with master

Bug is already bugging master. (Need to click back button multiple times)

**Comment by felixheidecke** [comment]
@PVince81 https://github.com/owncloud/core/pull/32060#issuecomment-416637992
> ... when moving the selection

Please specify what you mean by "when moving the selection"

**Comment by PVince81** [comment]
> Please specify what you mean by "when moving the selection"

@felixheidecke have 2-3 entries in the dropdown and then move the cursor to highlight the one or the other. When the highlight changes, it looks jumpy.

**Comment by felixheidecke** [comment]
@PVince81 https://github.com/owncloud/core/pull/32060#issuecomment-412071217

>  BUG: setup page styles broken, maybe jquery.ui related:

Can not confirm. Please re-test. (Branch is up to date)

**Comment by PVince81** [comment]
> @PVince81 [#32060 (comment)](https://github.com/owncloud/core/pull/32060#issuecomment-411481245)
> 
> > BUG: share autocomplete doesn't open any more
> 
> Can not confirm. Please re-check.

@felixheidecke needs rebase again, else web UI setup page cannot be opened. To get https://github.com/owncloud/core/pull/33414

**Comment by felixheidecke** [comment]
> need minor fix to autcomplete active item "ui-state-active" to avoid jumpiness when moving the selection

After a 1 hour pixel by pixel comparison and tedious bugfixing, I ran into … nothing … and it's still jumpy and I'll postpone going to move on with the merge.

margin and border

**Review by PVince81 — APPROVED** [review]
:+1:

we'll need to be careful during backport.

@felixheidecke please raise a ticket for the remaining "jumpy" issue so we try and solve it somehow before the backport

**Comment by phil-davis** [comment]
@felixheidecke @PVince81 this was not backported yet?
Do we backport? Or?

**Comment by PVince81** [comment]
no backport. we'll use master in the future for releases

**Pull request merged**
