### PR TITLE
file action detail style fixes

### PR DESCRIPTION
**Pull request by jancborchardt**
- use same font-size for share action text
- proper padding and whitespace for share and more actions (maybe this also alleviates the urge to click on the »more« icon when wanting to share, because there’s more space)
- remove border around bubble menu (also fixes the issue with the border being only on the left side of the triangle)
- fix share icons of shared items being placed off on mobile
- properly shade file actions and menu items, don't differentiate between mobile and desktop

Please review @owncloud/designers @nickvergessen @oparoz @Raydiation 

Before & after
capture du 2015-08-26 11-10-01  capture du 2015-08-26 11-09-22

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1: looks good

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
JS tests are broken. I will fix them.

**Comment by MorrisJobke** [comment]
> JS tests are broken. I will fix them.

Done.

**Comment by MorrisJobke** [comment]
@PVince81 Can you have a look at the unit test fixes? Thanks

**Comment by PVince81** [comment]
@MorrisJobke yeah, trimming is fine.

**Comment by nickvergessen** [comment]
:+1: fine by me.

@jancborchardt what do you think about moving the actions into the new right side bar?

**Comment by MorrisJobke** [comment]
JS tests pass locally and the other changes are CSS only -> merge

**Pull request merged**
