### PR TITLE
handle path not being set in shared cache

### LINKED ISSUE #24919: PHP Error: Undefined index: path
### Steps to reproduce
No idea

### Expected behaviour
No error

### Actual behaviour
The following error occorues frequently in the error-log:
Undefined index: path at /var/www/owncloud/apps/files_sharing/lib/cache.php#83

This error occures since our upgrade to version 9 on a new v-server.

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache + PHP-FPM

**Database:**
MySQL 14.14

**PHP version:**
PHP 7.0.6-1~dotdeb+8.1

**ownCloud version:** (see ownCloud admin page)
9.0.2

**Updated from an older ownCloud or fresh install:**
Upgrade from 8.0.2.2 with fresh tarball

**Where did you install ownCloud from:**
Fresh tarball from owncloud.org

**Signing status (ownCloud 9.0 and above):**
```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - logreader: 1.1.2
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - files_external
  - gallery
  - user_external
  - user_ldap
```

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "ocepst66lrus",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*****"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": "1",
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "niyu.de",
        "theme": "niyu",
        "maintenance": false,
        "singleuser": false,
        "trashbin_retention_obligation": "auto, 14",
        "version": "9.0.2.2",
        "enable_previews": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Web server error log
Corrisponding access-log entry
```
**IP** - - [31/May/2016:09:03:35 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1465 "-" "Mozilla/5.0 (Macintosh) mirall/2.1.1"
```

#### ownCloud log (data/owncloud.log)
```
Error 	PHP	Undefined index: path at /var/www/owncloud/apps/files_sharing/lib/cache.php#83	2016-05-31T09:06:35+00:00
Error	 PHP	Undefined index: path at /var/www/owncloud/apps/files_sharing/lib/cache.php#83	2016-05-31T09:06:19+00:00
Error 	PHP	Undefined index: path at /var/www/owncloud/apps/files_sharing/lib/cache.php#83	2016-05-31T09:06:13+00:00
Error 	PHP	Undefined index: path at /var/www/owncloud/apps/files_sharing/lib/cache.php#83	2016-05-31T09:06:12+00:00
```

Is there a way to extend this error-message while throwing to determine a filename or cause?

Thanks and best regards,

Moritz

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #24919

cc @owncloud/filesystem @owncloud/sharing

### CODE REVIEW

**Comment by rullzer** [comment]
So... in which situation can this actually happen... a share should always have a path.

**Comment by nickvergessen** [comment]
I wondered the same

No path is set, set to empty string, "what could possibly go wrong" :see_no_evil:

**Comment by icewind1991** [comment]
No clue why this happens, somehow the wrapped cache doesn't return the correct values

> "what could possibly go wrong"

Since the path is only used to get share permissions and owner (which is almost always the same for all files in a storage anyway), not much

**Comment by nickvergessen** [comment]
Hmm okay then :+1: 

Still would be nice to have reproduction steps, but the reportee had none aswell

**Comment by PVince81** [comment]
@icewind1991 maybe provide him with a separate patch that would log the stack trace to get more clues ?

:+1: for this PR

**Pull request merged**
