### PR TITLE
Debounce cancel upload message

### LINKED ISSUE #8433: Cancel a long list of upload, notification blinks
#### Steps:
1. Click on the upload button in the web UI
2. Select a long list of files that will take a few minutes to upload
3. While the upload runs, click on "Cancel Upload"
4. Observe the notification area

### Expected result
Upload cancelled, notification appears once.

### Actual result
Upload cancelled, notification blinks once for every file.

### Versions
ownCloud 7 pre-alpha (git master 6519b9672a7294282c9535d8544baea9a9d74ffd)

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/8433

Please review @jancborchardt @MorrisJobke @rullzer @blizzz @icewind1991

### CODE REVIEW

**Comment by icewind1991** [comment]
Makes sense :+1:

**Comment by MorrisJobke** [comment]
Tested, works and code looks good :+1:

**Comment by karlitschek** [comment]
sweet :+1:

**Comment by jancborchardt** [comment]
@PVince81 needs rebase. :)

**Comment by MorrisJobke** [comment]
> @PVince81 needs rebase. :)

No. @DeepDiver1975 will merge it. Due to the new github policy all branches need to be up to date with master, which is simply impossible. So an owner needs to merge it. We already asked Github for a solution.

**Comment by PVince81** [comment]
@icewind1991 this was scheduled for 8.2.1...

**Comment by icewind1991** [comment]
Opps, should I revert?

**Comment by PVince81** [comment]
@icewind1991 yes please

**Comment by icewind1991** [comment]
#19708

**Comment by jancborchardt** [comment]
Seems like stable8.2 should also be made a protected branch for the time until release so all these wrong merges are prevented? @DeepDiver1975 @karlitschek @cmonteroluque

**Pull request merged**
