### PR TITLE
[stable8.1] backport Tarstreamer 

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #19318
backport of https://github.com/owncloud/core/pull/19640

requires https://github.com/owncloud/3rdparty/pull/201
@msrex as discussed here https://github.com/owncloud/core/pull/19318#issuecomment-144070244

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@georgehrke  @karlitschek @LukasReschke mind testing this on your macs - THX

**Comment by LukasReschke** [comment]
Works :+1:

**Comment by rperezb** [comment]
@SergioBertolinSG can you please take care of this one?

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2015-10-09 13-01-17

**Comment by DeepDiver1975** [comment]
3rdparty ref updated after merge of owncloud/3rdparty#201

**Pull request merged**
