### PR TITLE
[3rdparty] Bump php-parser

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/229

https://github.com/owncloud/core/pull/20851 should go in first

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by rullzer** [comment]
Ref bumped

**Comment by DeepDiver1975** [comment]
> Ref bumped

thx

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
