### PR TITLE
Fix undefined offset 1 for wrong user mail address

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes Undefined offset: 1 at lib/private/mail.php#143

Steps to reproduce:
- go to personal settings
- type in a string without an @ as email address
  *Following log appeared: 
  
  ```
  {"reqId":"82168f27be8ddec69c7069f6adacfba2","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 1 at lib/private/mail.php#143","level":0,"time":"2015-01-22T14:16:42+00:00","method":"PUT","url":"/master/index.php/settings/users/mjob/mailAddress"}
  ```

cc @LukasReschke @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
I think the check should be one function earlier.
Can't be valid without an `@` so there is no need to start any work (in the 3rdparty)
```php
public static function validateAddress($emailAddress) {

**Comment by nickvergessen** [comment]
+ please add a test?

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@MorrisJobke unit tests are a must have - https://github.com/owncloud/core/commit/b533aad21697de29e8d69d7bb99b0309f2114d07#diff-6a3371457528722a734f3c51d9238c13

:-1:

**Comment by MorrisJobke** [comment]
Okay :)

**Comment by MorrisJobke** [comment]
Will add them

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Now with 100% more unit tests :P

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Done :)

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
agreed. please backport

**Comment by MorrisJobke** [comment]
stable7 491c714

**Pull request merged**
