### PR TITLE
Moved job phpunit sqlite php 7.0 from jenkins to drone

### PR DESCRIPTION
**Pull request by SergioBertolinSG**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
I wonder if we need that config - we already run tests with 7.0 ...

**Comment by SergioBertolinSG** [comment]
Tests are running using php7.1 with sqlite and php7.0 with mysql so this will only show particular problems using sqlite with php7.0 not happening with mysql.
I agree with just removing it.

**Comment by DeepDiver1975** [comment]
Wait - for anything else the sqlite we execute group DB only - in this case we need to run ALL php versions with sqlite

**Comment by SergioBertolinSG** [comment]
Ok then.

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport stable10 #29529

**Comment by phil-davis** [comment]
@SergioBertolinSG I made the backport to get CI moving along in the quiet hours.
Please remove backport-request label if this only backports to stable10.

**Pull request merged**
