### PR TITLE
[stable9.1] Fix failing preview unit tests (#26039)

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #26039 to stable9.1

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
EEEEEEEEEEEEEEEEHHHH
```
15:43:15 ...........EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 7076 / 7910 ( 89%)
15:43:16 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 7137 / 7910 ( 90%)
15:43:16 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 7198 / 7910 ( 90%)
15:43:17 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 7259 / 7910 ( 91%)
15:43:18 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEPHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/lib/jenkins/workspace/owncloud-core/core/PR-26043/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
15:43:18 Stack trace:
15:43:18 #0 /var/lib/jenkins/workspace/owncloud-core/core/PR-26043/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
15:43:18 #1 /var/lib/jenkins/workspace/owncloud-core/core/PR-26043/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
15:43:18 #2 /var/lib/jenkins/workspace/owncloud-core/core/PR-26043/lib/private/DB/Connection.php(209): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
15:43:18 #3 /var/lib/jenkins/workspace/owncloud-core/core/PR-26043/lib/private/AllConfig.php(305): OC\DB\Connection->executeUpdate('DELETE FROM `*P...', Array)
15:43:18 #4 /var/lib/jenkins/workspace/owncloud-core/core/PR-26043/lib/private/User/User.php(204): OC\AllConfig->deleteAllUserValues( in /var/lib/jenkins/workspace/owncloud-core/core/PR-26043/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
```

MySQL went to the bar and had a couple of beers.

Will restart the build.

**Comment by DeepDiver1975** [comment]
> Will restart the build.

thx

**Comment by PVince81** [comment]
@DeepDiver1975 :frowning: 

```
16:34:03 + ./autotest.sh pgsql
16:34:03 Using PHP executable /opt/phpenv/shims/php
16:34:03 PHP Fatal error:  Class 'Phar' not found in /usr/local/bin/phpunit on line 12
```

**Comment by PVince81** [comment]
base tests passed, swift docker failed init.
Merging this and hoping for a more happy build end on the main branch.

**Pull request merged**
