### PR TITLE
allow overwriting the config directory when using the occ command

### PR DESCRIPTION
**Pull request by icewind1991**
Mostly to make it easier for me to upgrade the various instances I run phpunit against

usage:

```
./occ --config=tests/config/encryption/ upgrade
```

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I don't really like to introduce all the hacks here just for some weird corner use case. :see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975 @PVince81 @nickvergessen @LukasReschke

**Comment by MorrisJobke** [comment]
> I don't really like to introduce all the hacks here just for some weird corner use case.


@DeepDiver1975 @PVince81 @karlitschek Can we have a decision here? I still don't like it :(

**Comment by nickvergessen** [comment]
yeah, :-1: from me as well.

Feel free to keep console2.php with the modification and call that instead, like others do when they modify stuff in a hacky way for their use case?

**Comment by karlitschek** [comment]
i agree with @MorrisJobke and @nickvergessen

**Comment by icewind1991** [comment]
Ok

**Pull request closed without merging**
