### PR TITLE
Revert "Fix column width of mtime column"

### PR DESCRIPTION
**Pull request by MorrisJobke**
Reverts owncloud/core#20842

I changed the translation to "Freigabezeitpunkt"

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@owncloud/designers @PVince81 @raghunayyar @Henni Please review


@jancborchardt Please review.

**Comment by rullzer** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by jancborchardt** [comment]
@MorrisJobke thanks a lot homie! :)

**Pull request merged**
