### PR TITLE
fix broken logtimezone

### PR DESCRIPTION
**Pull request by DeepDiver1975**
jenkins for https://github.com/owncloud/core/pull/23222

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Change has been approved in https://github.com/owncloud/core/pull/23222

**Comment by MorrisJobke** [comment]
@karlitschek Backport?

**Comment by MorrisJobke** [comment]
> @karlitschek Backport?

Original issue (https://github.com/owncloud/core/issues/23134) was scheduled for 9.0.1

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by Phiber2000** [comment]
Backport: #23240

**Pull request merged**
