### PR TITLE
Remove info about database locking performance

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@karlitschek @LukasReschke @jancborchardt @jospoortvliet @dragotin @jnweiger

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
:+1:

**Comment by danimo** [comment]
I just stumbled over this when looking for advise on how to do file locking with PHP 7. What is the rationale for removing this message? I think it's immensely helpful.

@DeepDiver1975 @karlitschek

**Comment by karlitschek** [comment]
the result of a ton of discussions of EE scenarios. we should merge it by the way

**Comment by DeepDiver1975** [comment]
> we should merge it by the way

it was merged 10 days back :see_no_evil:

**Comment by RealRancor** [comment]
I think based on this removed warning the following https://github.com/owncloud/core/issues/22318 should be implemented sooner then later. Running file_locking on sqlite is probably really nothing what should be done or am i wrong?

**Pull request merged**
