### PR TITLE
Fix order of actions in the files actions menu

### LINKED ISSUE #18280: Order of actions in action dropdown, move Delete to last position
The current order of actions is:
* Download
* Rename
* Delete
* Versions

Delete should be moved to the last position though, as it’s a destructive action. It should always be last and not just somewhere in the list. @PVince81 @owncloud/designers

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/18280

Please review @jancborchardt @MorrisJobke @rullzer @nickvergessen @schiesbn @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Please note that "order" is an internal attribute to be able to sort the default actions, so it's not in the public API.

File actions registered by apps will appear before "Delete" and be sorted by display name.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by nickvergessen** [comment]
magic numbers :see_no_evil: 

fine by me :+1:

**Comment by PVince81** [comment]
@nickvergessen it's either magic number or tab ids hard-coded inside DetailsView :wink:
I prefer the former

**Pull request merged**
