### PR TITLE
add icons to Files sidebar

### PR DESCRIPTION
**Pull request by jancborchardt**
A follow-up to https://github.com/owncloud/core/pull/15387 and https://github.com/owncloud/core/issues/15322 (I incorporated your commit, @ddxor :)

Adding not only text to the Settings icon, but also icons to the sidebar entries. We did it similarly in the Mail app already and it makes it easier to recognize the entries.

Please review @owncloud/designers @bnvk @ddxor @Xenopathic

### CODE REVIEW

**Comment by jancborchardt** [comment]
Screenshots before:
capture du 2015-04-08 19 33 20
After:
capture du 2015-04-08 19 32 40

**Comment by LukasReschke** [comment]
I like it :+1:

**Comment by karlitschek** [comment]
very nice :+1:

**Comment by bnvk** [comment]
Lookin super duper. I loves me some icon + word navigation :smile:

**Comment by cosenal** [comment]
I see this instead (diff: label »Settings« is centered) FF37.0
screen shot 2015-04-08 at 14 15 22

**Comment by jancborchardt** [comment]
@cosenal looks like a CSS caching error, as if your settings.css is outdated. Can you force refresh / check again with incognito mode?

**Comment by MorrisJobke** [comment]
Looks nice in IE8, Chrome and Firefox :+1:

(I added a minor IE8 fix ;))

**Comment by jancborchardt** [comment]
@MorrisJobke aaah thank you for adding that svg class! :)

**Comment by cosenal** [comment]
@jancborchardt my bad, i had messed things up with git

**Pull request merged**
