### PR TITLE
Add a tableprefix field to the setup wizard

### PR DESCRIPTION
**Pull request by Niduroki**
Pretty easy since the functionality already exists.
Fixing #3349

Tested in mysql, don't have any postgresql setup now :c 
_Should_ work anywhere though, because I'm not doing any black magic here.

@bartv2

### CODE REVIEW

**Comment by Mutos** [comment]
Hi all,


Sorry to come back on an old issue, but I'm precisely stuck with it...

I use ownCLoud for a small collective of some 10 persons and I'm limited in DBs by my hosting choices, so I want to have a prod ownCLoud and a test ownCloud in the same DB, which already holds several pairs of prod-test instances of phpBB and MediaWiki. I thought it would be an evidence that the prefix can be chosen, and now I'm stuck with it and plan B is to go to G....e cloud instead, which I would prefer not...

**Comment by jancborchardt** [comment]
@Mutos that's handled automatically. ownCloud uses "oc_" as prefix. If you install another owncloud, it should automatically use "oc2_" (or so). Is that correct @DeepDiver1975?

**Comment by andreas-p** [comment]
Actually, there are other use cases for a different table prefix. I'd like to access tables that do not start with 'oc_', but afaics the connection factory will force the prefix. So making the prefix non-changeable not only limits the owncloud instances to one but also limits access to tables.
I succeeded installing owncloud 8.2 without a prefix by using the occ tool, which should be sufficient for advanced usage.

**Comment by jancborchardt** [comment]
Yup – as you said, it can be done with occ, so no need to expose this in the UI.

**Pull request closed without merging**
