### PR TITLE
Fix email not sending to self

### LINKED ISSUE #32823: webUI scenario shareByPublicLink.feature:153 fails sometimes
```
tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature:153
```
That scenario seems to fail sometimes. I guess there is some timing problem with the public link dialog. It needs looking into.

### PR DESCRIPTION
**Pull request by skshetry**
## Description

Fixes bug in test with email not being received by the link creator.

## Related Issue

- Fixes #32823 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by skshetry** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by skshetry** [comment]
@owncloud rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by skshetry** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by skshetry** [comment]
@phil-davis This passed each time. So maybe we should merge this and then I'll monitor the ci for this specific scenario failure.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport ``stable10`` #32984

**Pull request merged**
