### PR TITLE
Do not try to login via auth module if the user is disabled

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Do not try to login with a disabled user

## Related Issue
https://github.com/owncloud/enterprise/issues/2509

## Motivation and Context
Duplicated auth token error message was happening trying to refresh the token of a disabled user

## How Has This Been Tested?
Manually checked with desktop client 2.5.4
1. Using the desktop client and the oAuth2 app, login normally with a user via oAuth2 and let the desktop client sync
2. After the sync finishes, disable the user in ownCloud
3. Try to resync

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](../changelog/README.md)

### CODE REVIEW

**Comment by phil-davis** [comment]
@micbar this has been sitting for a while?

**Comment by micbar** [comment]
@jvillafanez Please rebase.

**Comment by micbar** [comment]
@jvillafanez Please add changelog item.

**Comment by jvillafanez** [comment]
Added changelog item and rebased

**Comment by mmattel** [comment]
Because no reviewer was assigned, it layed around unattended.
If rebased, CI gets a kick to redo testing.

**Comment by phil-davis** [comment]
I rebased and new CI is running.

@micbar what to do about this PR?

**Comment by pascalwengerter** [comment]
@JanAckermann we have a request from @rpocklin regarding this PR, could you take a look and try to get this in? :)

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/tree/auth_module_user_disabled "This branch is 2 commits ahead, 2943 commits behind master. "

It really needs a rebase to see what happens in CI against current master.

**Review by AlexAndBear — APPROVED** [review]

**Comment by JanAckermann** [comment]
Rebased, fixed unit tests, looks good to me.

FYI @kulmann @pascalwengerter

**Pull request merged**
