### PR TITLE
[stable8] Allow removing of link password in OCS again

### PR DESCRIPTION
**Pull request by rullzer**
Backport of #17136

CC: @schiesbn @LukasReschke @nickvergessen

### CODE REVIEW

**Comment by schiesbn** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@cmonteroluque merging this in as it fixes a regression

**Comment by karlitschek** [comment]
Thanks :+1: @DeepDiver1975 Approval from me in the future please.

**Pull request merged**
