### PR TITLE
Fix the parameter order in the translation

### LINKED ISSUE #19: Order of parameters (username, filename) wrong in message
It says:

> You received jan@localhorst/owncloud-clean as a remote share from testing.txt

Should obviously be the other way around. Also, is it possible to bold both username and filename?

@nickvergessen @PVince81

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix owncloud/notifications#19

@jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
:+1: 

@nickvergessen I’m probably not the only person who should review this, right? Mention some more folks! :)

**Comment by nickvergessen** [comment]
@PVince81 quite easy and quick to review

**Comment by nickvergessen** [comment]
rebased for oci :(

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
