### PR TITLE
Process unknown accounts before adding new ones

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Updated PR for https://github.com/owncloud/core/pull/27828

## Related Issue
Linked in the original

## How Has This Been Tested?
Manually with LDAP backend

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
rebased for CI

**Comment by PVince81** [comment]
Code looks fine to me, @DeepDiver1975 any consequences in mind ?

**Comment by PVince81** [comment]
@jvillafanez any detailed test steps ? I don't see any in the original ticket

**Comment by jvillafanez** [comment]
It's just syncing the users. The disable / remove action will be performed before adding the users.

For something more flashy you can check with LDAP:

1. sync the users
2. clear the ldap mappings
3. sync the users again

Before the fix you'll have users with the "_4543" or so appended in the LDAP mapping, which indicates there has been a user with the same name. With the fix, the users have been deleted before adding the new ones, so this situations won't happen often (if the users are removed, it will happen if they are disabled)

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
