### PR TITLE
darker background image for better font contrast

### PR DESCRIPTION
**Pull request by ChristophWurst**
While working on the 2FA stuff I noticed that the background image makes it hard to read the thin, low contrast fonts. Hence I darkened the image and removed the yellow tint.
# Before

bildschirmfoto von 2016-06-07 22-36-43
bildschirmfoto von 2016-06-07 22-36-50
# After

bildschirmfoto von 2016-06-07 22-31-56
bildschirmfoto von 2016-06-07 22-35-12

@owncloud/designers what do you think? Is the blue too aggressive?

related to https://github.com/owncloud/core/issues/24035

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> @owncloud/designers what do you think? Is the blue too aggressive?

Yes. I don't like it that much :(

**Comment by DeepDiver1975** [comment]
Image Contest ? Let the Community vote?
@dragotin @pvince81

**Comment by enoch85** [comment]
I think it looks nice. :+1:

**Comment by skjnldsv** [comment]
I'm okay with that too! #bluelivesmatter :+1:

**Comment by ChristophWurst** [comment]
> Yes. I don't like it that much :(

how about that? Less aggressive, even better contrast:
bildschirmfoto von 2016-06-08 07-57-35

**Comment by jancborchardt** [comment]
That second one is great and it fits the darker ownCloud blue. Good work @ChristophWurst! :+1: :)

(As talked about before, we should not make a community voting contest out of this in the first iteration.)

**Comment by ChristophWurst** [comment]
Updated as I'd also prefer the darker one.

**Comment by nickvergessen** [comment]
:+1:

**Comment by ChristophWurst** [comment]
I guess those are enough :+1:'s -> to release :-)

**Pull request merged**
