### PR TITLE
[tests-only] [full-ci]Add type declaration and return type in functions part 3

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
This PR adds return type and declaration to functions in the files:
 - CapabilitiesContext.php
 - CommentsContext.php

## Related Issue

- part of: https://github.com/owncloud/core/issues/39243
## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require an increase of minor version instead of the patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM - a "part 4" commit just got pushed here, but that looks fine. We can merge when CI passes.

**Comment by SwikritiT** [comment]
> LGTM - a "part 4" commit just got pushed here, but that looks fine. We can merge when CI passes.

Yes, I was supposed to do that in a separate branch but I forget to check out the new branch and accidentally pushed it here.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingExt1-latest-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32587/154/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/32587/154/19
```
  Scenario: share a folder with a federated user and prohibit deleting - remote server shares - local server receives                              # /drone/src/tests/acceptance/features/webUISharingExternal1/federationSharing.feature:35
    Given user "Alice" from server "REMOTE" has shared "simple-folder" with user "Alice" from server "LOCAL" with permissions "create,read,update" # FederationContext::userFromServerHasSharedWithUserFromServerWithPermissions()
      Type error: Argument 6 passed to FederationContext::userFromServerHasSharedWithUserFromServerWithPermissions() must be of the type int or null, string given, called in /drone/src/vendor-bin/behat/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php on line 110 (Behat\Testwork\Call\Exception\FatalThrowableError)
```

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
