### PR TITLE
ETags for OCS responses

### PR DESCRIPTION
**Pull request by rullzer**
This commit adds ETags to OCS responses. The ETag is just the md5sum of the body of the response.
Which means that we can now also return a 304 when nothing has changed.

This will allow clients to efficiently check for updates.
For example in: https://github.com/owncloud/core/issues/6813#issuecomment-137012278

There is no way to properly test this as far as I know on the phpunit runs.
But we should add sets for it in the smashbox tests.
## Steps to test
1. Get your list of current shares via
   `curl -u USER:PASS -D - 'https://cloud2.famdouma.nl//ocs/v1.php/apps/files_sharing/api/v1/shares'`
2. Get the Etag ( for example ETag: "abc")
3. Request the list of shares again with the IF_NONE_MATCH header:
   `curl -u USER:PASS -D - 'https://cloud2.famdouma.nl//ocs/v1.php/apps/files_sharing/api/v1/shares' --header 'If-None-Match: "abc"'`
4. Add/remove a new share
5. Request the list of shares again:
   `curl -u USER:PASS -D - 'https://cloud2.famdouma.nl//ocs/v1.php/apps/files_sharing/api/v1/shares' --header 'If-None-Match: "abc"'`
#### Before

There is no etag in step 2. And the whole response is send each time
#### After

Step 3 will return a 304. Telling you that nothing has changed.
Step 5 will return the new response and a new ETag.
## Notice

The ETag only here only checks the content. So the only thing you know is that the response is the same as before. You do not know that nothing happend.

For example.
1. Request shares (and get ETag)
2. Add share X
3. Remove share X
4. Request share with IF_NONE_MATCH

Step 4 will return a 304. Which is what you want actually :)

CC: @PVince81 @Raydiation @Xenopathic @MorrisJobke @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
I am pretty uncertain about this. Can we move thisto 9.0 please i want to think and talk about this alter my vac. Thx

**Comment by rullzer** [comment]
@DeepDiver1975 sure.. The most direct benefit is for the webinterface (once that switches to webdav). Which will also be 9.0

But I am curious where your uncertainty is coming from.

**Comment by Xenopathic** [comment]
Well it certainly works. I'm not knowledgeable about how OCS should work though, so I'm unqualified to +1 :smile:

**Comment by DeepDiver1975** [comment]
I vote for :-1: 

if non match is not generally allowed but only in certain scenarios - http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.26

Before opening another battlefield - let's see how far we get without it.

**Comment by rullzer** [comment]
Ok lets see.

**Comment by DeepDiver1975** [comment]
THX @rullzer

**Pull request closed without merging**
