### PR TITLE
Use "off" and "off" instead of true booleans

### PR DESCRIPTION
**Pull request by LukasReschke**
Apparently a boolean in php.ini is according to the documentation "on" or "off"…

Fixes itself.

(that said… it magically worked for me :see_no_evil:)

@jmaciasportela @andyknownasabu Please test.

### CODE REVIEW

**Comment by jmaciasportela** [comment]
It works fine (y)

**Comment by andyknownasabu** [comment]
can also be an int according to the comment in php.ini

Will test...

**Comment by LukasReschke** [comment]
> can also be an int according to the comment in php.ini

Yep. Our helper should map that to true.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by andyknownasabu** [comment]
works for me

**Pull request merged**
