### PR TITLE
Adapted integration tests for stable8.2

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Removed several contexts and scenarios which doesn't apply to 8.2.

Currently several tests fail. This is because some tests needs to be adjusting, but maybe other failures are showing bugs. I'll continue modifying the tests.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
https://ci.owncloud.org/job/ocs-api-integration-tests-ci/12165/#showFailuresLink

bildschirmfoto von 2016-07-12 12-05-58

**Comment by SergioBertolinSG** [comment]
Favorites scenarios 24 and 33 failing because  ```{http://owncloud.org/ns}favorite``` property is not found. I'll file a bug about it.

**Comment by SergioBertolinSG** [comment]
provisioning-v1.feature:73 fails because special characters are being rejected as invalid data.

**Comment by SergioBertolinSG** [comment]
provisioning-v1.feature:160 fails because subadmins can't get users before 9.0.

https://github.com/owncloud/core/pull/18399

**Comment by SergioBertolinSG** [comment]
Removed tests about enabling or disabling users, that functionality started in 9.1.

**Comment by PVince81** [comment]
> Scenario: Don't allow sharing of the root

I think this is an old bug that was fixed only in 9.1 and 9.0 and not backported. See https://github.com/owncloud/core/pull/25138. You can remove that test.

**Comment by SergioBertolinSG** [comment]
Scenario: Check quota of owners parent directory of a shared file
This test is removed as the fix is only for >9.0 and won't be backported.

**Comment by SergioBertolinSG** [comment]
Remaining:
CSRF check in dav endpoint tests in webdav-related to be removed/modified.
curl failure in last federation test.

**Comment by PVince81** [comment]
Looks like you also need to remove the test about special chars.

Let's move that test to your other PR that fixes it.

**Comment by SergioBertolinSG** [comment]
OK

**Comment by PVince81** [comment]
One last failure:
```
06:12:02   Scenario: Overwrite a federated shared folder as recipient using old chunking                  # /ssd/jenkins/workspace/ocs-api-integration-tests-ci/build/integration/federation_features/federated.feature:129
06:12:02     Given Using server "REMOTE"                                                                  # FederationContext::usingServer()
06:12:02 [Fri Jul 15 06:12:02 2016] ::1:42675 [404]: /ocs/v2.php/cloud/users/user1
06:12:02 [Fri Jul 15 06:12:02 2016] ::1:42680 [200]: /ocs/v1.php/cloud/users
06:12:03 [Fri Jul 15 06:12:03 2016] ::1:42684 [200]: /ocs/v1.php/cloud/users/user1
06:12:03 [Fri Jul 15 06:12:03 2016] ::1:42700 [200]: /ocs/v2.php/cloud/users/user1
06:12:03     And user "user1" exists                                                                      # FederationContext::assureUserExists()
06:12:03 [Fri Jul 15 06:12:03 2016] ::1:42704 [404]: /ocs/v2.php/cloud/users/user2
06:12:03 [Fri Jul 15 06:12:03 2016] ::1:42707 [200]: /ocs/v1.php/cloud/users
06:12:04 [Fri Jul 15 06:12:04 2016] ::1:42710 [200]: /ocs/v1.php/cloud/users/user2
06:12:04 [Fri Jul 15 06:12:04 2016] ::1:42719 [200]: /ocs/v2.php/cloud/users/user2
06:12:04     And user "user2" exists                                                                      # FederationContext::assureUserExists()
06:12:04     And Using server "LOCAL"                                                                     # FederationContext::usingServer()
06:12:04 [Fri Jul 15 06:12:04 2016] ::1:38341 [404]: /ocs/v2.php/cloud/users/user0
06:12:04 [Fri Jul 15 06:12:04 2016] ::1:38343 [200]: /ocs/v1.php/cloud/users
06:12:05 [Fri Jul 15 06:12:04 2016] ::1:38355 [200]: /ocs/v1.php/cloud/users/user0
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38362 [200]: /ocs/v2.php/cloud/users/user0
06:12:05     And user "user0" exists                                                                      # FederationContext::assureUserExists()
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:42748 Invalid request (Unsupported SSL request)
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:42749 [200]: /ocs/v1.php/cloud/shares?format=json
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38363 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares
06:12:05     And User "user0" from server "LOCAL" shares "/PARENT" with user "user1" from server "REMOTE" # FederationContext::federateSharing()
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:42750 [200]: /ocs/v1.php/apps/files_sharing/api/v1/remote_shares/pending
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38390 [200]: /ocs/v1.php/cloud/shares/66/accept?format=json
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:42771 [200]: /ocs/v1.php/apps/files_sharing/api/v1/remote_shares/pending/9
06:12:05     And User "user1" from server "REMOTE" accepts last pending share                             # FederationContext::acceptLastPendingShare()
06:12:05     And Using server "REMOTE"                                                                    # FederationContext::usingServer()
06:12:05     And As an "user1"                                                                            # FederationContext::asAn()
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38393 [401]: /public.php/webdav/textfile0.txt
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38394 [404]: /public.php/webdav/textfile0.txt
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38397 [200]: /index.php/apps/files_sharing/shareinfo?t=oSj4D0wkGihWmuk
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38398 [404]: /public.php/webdav/textfile0.txt-chunking-42-3-0
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38399 [207]: /public.php/webdav/
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38400 [207]: /public.php/webdav/
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38401 [404]: /public.php/webdav/textfile0.txt-chunking-42-3-0
06:12:05 [Fri Jul 15 06:12:05 2016] ::1:38405 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:05 2016] ::1:38406 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:05 2016] ::1:42774 [201]: /remote.php/webdav/PARENT%20(2)/textfile0.txt-chunking-42-3-0
06:12:06     And user "user1" uploads chunk file "1" of "3" with "AAAAA" to "/PARENT (2)/textfile0.txt"   # FederationContext::userUploadsChunkFileOfWithToWithChecksum()
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38408 [401]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38409 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38410 [207]: /public.php/webdav/
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38411 [404]: /public.php/webdav/textfile0.txt-chunking-42-3-1
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38412 [207]: /public.php/webdav/
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38413 [404]: /public.php/webdav/textfile0.txt-chunking-42-3-1
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38414 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38417 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:42789 [201]: /remote.php/webdav/PARENT%20(2)/textfile0.txt-chunking-42-3-1
06:12:06     And user "user1" uploads chunk file "2" of "3" with "BBBBB" to "/PARENT (2)/textfile0.txt"   # FederationContext::userUploadsChunkFileOfWithToWithChecksum()
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38420 [401]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38428 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38429 [207]: /public.php/webdav/
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38430 [404]: /public.php/webdav/textfile0.txt-chunking-42-3-2
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38431 [207]: /public.php/webdav/
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38432 [404]: /public.php/webdav/textfile0.txt-chunking-42-3-2
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38433 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38434 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38435 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38438 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38441 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38442 [404]: /public.php/webdav/textfile0.txt
06:12:06 [Fri Jul 15 06:12:06 2016] ::1:38443 [404]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:06 2016] ::1:38444 [404]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38445 [404]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38446 [404]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38447 [404]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38448 [404]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38449 [404]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38450 [404]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38451 [404]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38452 [207]: /public.php/webdav/
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38453 [201]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38454 [207]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38455 [200]: /index.php/apps/files_sharing/shareinfo?t=oSj4D0wkGihWmuk
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38456 [200]: /index.php/apps/files_sharing/shareinfo?t=oSj4D0wkGihWmuk
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:42800 [201]: /remote.php/webdav/PARENT%20(2)/textfile0.txt-chunking-42-3-2
06:12:07     And user "user1" uploads chunk file "3" of "3" with "CCCCC" to "/PARENT (2)/textfile0.txt"   # FederationContext::userUploadsChunkFileOfWithToWithChecksum()
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38458 [401]: /public.php/webdav/
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38459 [207]: /public.php/webdav/
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38460 [207]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38461 [200]: /public.php/webdav/textfile0.txt
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:42839 [206]: /remote.php/webdav/PARENT%20(2)/textfile0.txt
06:12:07     When Downloading file "/PARENT (2)/textfile0.txt" with range "bytes=3-13"                    # FederationContext::downloadFileWithRange()
06:12:07       cURL error 18: transfer closed with 11 bytes remaining to read (GuzzleHttp\Exception\RequestException)
06:12:07     Then Downloaded content should be "AABBBBBCCCC"                                              # FederationContext::downloadedContentShouldBe()
06:12:07 [Fri Jul 15 06:12:07 2016] ::1:38462 [200]: /ocs/v1.php/cloud/users/user0
06:12:08 [Fri Jul 15 06:12:08 2016] ::1:38463 [404]: /ocs/v2.php/cloud/users/user0
06:12:08 [Fri Jul 15 06:12:08 2016] ::1:38465 [200]: /ocs/v1.php/cloud/shares/66/decline?format=json
06:12:08 [Fri Jul 15 06:12:08 2016] ::1:42846 [200]: /ocs/v1.php/cloud/users/user1
06:12:08 [Fri Jul 15 06:12:08 2016] ::1:42854 [404]: /ocs/v2.php/cloud/users/user1
06:12:08 [Fri Jul 15 06:12:08 2016] ::1:42855 [200]: /ocs/v1.php/cloud/users/user2
06:12:08 [Fri Jul 15 06:12:08 2016] ::1:42856 [404]: /ocs/v2.php/cloud/users/user2
06:12:08 
06:12:08 --- Failed scenarios:
06:12:08 
06:12:08     /ssd/jenkins/workspace/ocs-api-integration-tests-ci/build/integration/federation_features/federated.feature:129
```

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
