### PR TITLE
an-app-is-identified-by-having-a-info.xml-app.php-should-not-be-manda…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…tory

@MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
yep :+1:

**Comment by LukasReschke** [comment]
```
11:26:14 .............PHP Fatal error:  Uncaught Error: Class 'OC\Connector\Sabre\File' not found in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/dav/tests/unit/connector/sabre/file.php:825
```

lalalalalalalalalalalalalalalalalalalalala

**Comment by DeepDiver1975** [comment]
> lalalalalalalalalalalalalalalalalalalalala

 8a03684

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
With this branch webdav is working again :+1:

**Pull request merged**
