### PR TITLE
larger preview for images in the sidebar

### PR DESCRIPTION
**Pull request by icewind1991**
Before

After

cc @PVince81 @jancborchardt

### CODE REVIEW

**Comment by MorrisJobke** [comment]
* [ ] disable this for `'enable_previews' = false`

**Comment by jancborchardt** [comment]
Nice! :) As discussed.

Only 3 things:
* Don’t crop the image, showing the full one always takes precedence over having it full width
* If the image is smaller than the max height, the height of the container can be reduced (still have a bit of padding but not that much – try it with small icons)
* Account for when previews are disabled, just fallback to normal mode and show the filetype icon

Also cc @oparoz @owncloud/designers for review :)

**Comment by jancborchardt** [comment]
Btw @dragotin will be happy to see this. ;D Also cc @karlitschek because we talked about this.

**Comment by karlitschek** [comment]
cool :+1:

**Comment by icewind1991** [comment]
Everything should be fixed now.

**Comment by jancborchardt** [comment]
Not entirely. ;)
capture du 2015-08-28 20-49-40

Also, instead of showing the filetype icon in giant while loading the preview, just use class .icon-loading for the element so a spinner is shown.

**Comment by icewind1991** [comment]
Fixed the repeating mime icons and added a loading indicator.

(do we have a higher resolution version of the spinner, it's very pixelated)

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
* [ ] It doesn't seem to use the full width anymore:

bildschirmfoto von 2015-08-29 13-21-29

**Comment by icewind1991** [comment]
Blame jan for that decision

**Comment by MorrisJobke** [comment]
> Blame jan for that decision

@jancborchardt This looks ugly. I liked the zoomed in version more :P

**Comment by icewind1991** [comment]
I would also prefer the full with version

**Comment by oparoz** [comment]
I agree, just like thumbnails in Gallery, there should be no aspect ratio applied here. People will just need to click on the thumbnail to get the full picture. It looks much nicer when the top row is filled.

**Comment by icewind1991** [comment]
cc @jancborchardt

**Comment by icewind1991** [comment]
Now fills for landscape, fits for portrait

**Comment by jancborchardt** [comment]
:+1: any further details we can fix in follow-up PRs. Great work @icewind199! I think @dragotin will be happy about the larger previews. :)

**Comment by oparoz** [comment]
@icewind1991 - Tests are missing for the new mode
cc @DeepDiver1975

**Comment by PVince81** [comment]
Indeed. @icewind1991 please move the calculation codes to a separate function have write unit tests for the size/ratio calculations combinations.

**Comment by oparoz** [comment]
Tracking missing tests here to make sure they're not forgotten: 
https://github.com/owncloud/core/issues/18875

**Pull request merged**
