### PR TITLE
Harden settings page

### LINKED ISSUE #484: Clicking settings button leads to error
Hi!

We are using ownCloud 10.3.1 on Ubuntu 18.04.3 LTS and Apache 2.4.29. We are able to login with our LDAP accounts but clicking on the settings button produces the following error:

image
image

```
Dec  5 09:52:54 HOSTNAME ownCloud[13271]: [JE5FttI4uTGhBEru5Jda][IP][89591EE5-532F-4A06-BBDE-E0762256B3DE][index][GET][/owncloud/settings/personal] Exception: {"Exception":"OCA\User_LDAP\Exceptions\DoesNotExistOnLDAPException","Message":"89591EE5-532F-4A06-BBDE-E0762256B3DE","Code":0,"Trace":"
#0 /var/www/owncloud/lib/private/User/User.php(361): OCA\User_LDAP\User_Proxy->canChangeAvatar('89591EE5-532F-4...')
#1 /var/www/owncloud/settings/Panels/Personal/Profile.php(101): OC\User\User->canChangeAvatar()
#2 /var/www/owncloud/settings/Controller/SettingsPageController.php(167): OC\Settings\Panels\Personal\Profile->getPanel()
#3 /var/www/owncloud/settings/Controller/SettingsPageController.php(85): OC\Settings\Controller\SettingsPageController->getPanelsData(Array)
#4 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(153): OC\Settings\Controller\SettingsPageController->getPersonal('general')
#5 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(85): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\SettingsPageController), 'getPersonal')
#6 /var/www/owncloud/lib/private/AppFramework/App.php(100): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\SettingsPageController), 'getPersonal')
#7 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('SettingsPageCon...', 'getPersonal', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#8 /var/www/owncloud/lib/private/Route/Router.php(342): OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#9 /var/www/owncloud/lib/base.php(920): OC\Route\Router->match('/settings/perso...')
#10 /var/www/owncloud/index.php(54): OC::handleRequest()
#11 {main}","File":"/var/www/owncloud/apps/user_ldap/lib/User_Proxy.php","Line":244}
```

This error does not occur if i use an internal user.

If i comment the line 244 in "*\owncloud\apps\user_ldap\lib\User_Proxy.php" the error does not occur and i am able to enter "settings".

Maybe that's a problem with our ldap, can anyone point me to the right direction?

Regards

### PR DESCRIPTION
**Pull request by IljaN**
## Description
canChangeAvatar may throw an exception when LDAP is used. This makes the profile page inaccessible causing the settings link in the main view to break. The exception itself is likely caused by orphaned LDAP-Users (investigating).

https://github.com/owncloud/user_ldap/blob/master/lib/User_Proxy.php

Individual settings pages are still accessible via url. 

## Related Issue

- Fixes https://github.com/owncloud/user_ldap/issues/484

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by karakayasemi — COMMENTED** [review]
According to interface no exception is expected in `canChangeAvatar()`. I am not sure about merging this one.

Maybe we can try to solve the problem in user_ldap. We can catch exceptions in the related app method and return false in the catch block.

**Comment by jvillafanez** [comment]
I have the same concern. If the interface doesn't throw an exception, the implementation is wrong trying to throw it.

We can change the interface to allow throwing the exception, but it needs to be planned and designed: what exceptions are allowed to be thrown (plain exception is a terrible idea), under what circumstances the exceptions are thrown, for what use cases we need to throw an exception there...

For now, it's easiest to catch the exception in the implementation (ldap) and adjust the code to return either true or false, as the interface defines.

**Comment by IljaN** [comment]
@jvillafanez @karakayasemi Thing is that canChangeAvatar can throw all kinds of exceptions causing a DoS of the user-interface. My approach here was "keep settings alive at all costs"

https://github.com/owncloud/user_ldap/blob/master/lib/User_Proxy.php#L239-L243

**Comment by karakayasemi** [comment]
> @jvillafanez @karakayasemi Thing is that canChangeAvatar can throw all kinds of exceptions causing a DoS of the user-interface. My approach here was "keep settings alive at all costs"
> 
> See https://github.com/owncloud/user_ldap/blob/master/lib/User_Proxy.php#L239-L243

In my opinion, we should exactly fix that method. This method should not throw an exception. It can simply return false after catching exceptions. Core does not know that implementation, it is using `IUser` interface.

**Comment by IljaN** [comment]
Okay will do the change in user_ldap. Thing is that any other exception could potentially kill the settings page.

**Comment by IljaN** [comment]
Fixed via https://github.com/owncloud/user_ldap/pull/627

**Pull request closed without merging**
