### PR TITLE
Use insertIfNotExists() and reload mimetypes after inserting one

### LINKED ISSUE #13764: Parallel upload in fresh OC inserts same mimetype multiple times
### Steps to reproduce
1. Setup a brand new ownCloud instance (where the oc_mimetypes table is empty)
2. Setup the new sync client 1.8.x that supports parallel uploads
3. Copy a folder full of JPG files into the local folder and let it sync up (they all must have the same mime type)

### Expected result
No warnings

### Actual result
If you're (un)lucky, for each file uploaded in parallel, OC will try and insert the same mimetype concurrently as it doesn't exist yet:
```
{"reqId":"f4dc467bb2fb5b51f0b446be252b5f61","remoteAddr":"127.0.0.1","app":"core","message":"Exception during mimetype insertion: An exception occurred while executing 'INSERT INTO `oc_mimetypes`(`mimetype`) VALUES(?)' with params [\"image\\\/gif\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'image\/gif' for key 'mimetype_id_index'","level":0,"time":"2015-01-29T13:26:19+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sha\/penguins-mysql\/aniolek.gif"}
{"reqId":"62f861336eb5790dfd02addd2b462873","remoteAddr":"127.0.0.1","app":"core","message":"Exception during mimetype insertion: An exception occurred while executing 'INSERT INTO `oc_mimetypes`(`mimetype`) VALUES(?)' with params [\"image\\\/gif\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'image\/gif' for key 'mimetype_id_index'","level":0,"time":"2015-01-29T13:26:19+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sha\/penguins-mysql\/3m_sie.gif"}
{"reqId":"f4dc467bb2fb5b51f0b446be252b5f61","remoteAddr":"127.0.0.1","app":"core","message":"Exception during mimetype insertion: An exception occurred while executing 'INSERT INTO `oc_mimetypes`(`mimetype`) VALUES(?)' with params [\"image\\\/gif\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'image\/gif' for key 'mimetype_id_index'","level":0,"time":"2015-01-29T13:26:21+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sha\/penguins-mysql\/aniolek.gif"}
{"reqId":"62f861336eb5790dfd02addd2b462873","remoteAddr":"127.0.0.1","app":"core","message":"Exception during mimetype insertion: An exception occurred while executing 'INSERT INTO `oc_mimetypes`(`mimetype`) VALUES(?)' with params [\"image\\\/gif\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'image\/gif' for key 'mimetype_id_index'","level":0,"time":"2015-01-29T13:26:21+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sha\/penguins-mysql\/3m_sie.gif"}
{"reqId":"f4dc467bb2fb5b51f0b446be252b5f61","remoteAddr":"127.0.0.1","app":"core","message":"Exception during mimetype insertion: An exception occurred while executing 'INSERT INTO `oc_mimetypes`(`mimetype`) VALUES(?)' with params [\"image\\\/gif\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'image\/gif' for key 'mimetype_id_index'","level":0,"time":"2015-01-29T13:26:23+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sha\/penguins-mysql\/aniolek.gif"}
{"reqId":"62f861336eb5790dfd02addd2b462873","remoteAddr":"127.0.0.1","app":"core","message":"Exception during mimetype insertion: An exception occurred while executing 'INSERT INTO `oc_mimetypes`(`mimetype`) VALUES(?)' with params [\"image\\\/gif\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'image\/gif' for key 'mimetype_id_index'","level":0,"time":"2015-01-29T13:26:23+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sha\/penguins-mysql\/3m_sie.gif"}
{"reqId":"62f861336eb5790dfd02addd2b462873","remoteAddr":"127.0.0.1","app":"core","message":"Exception during mimetype insertion: An exception occurred while executing 'INSERT INTO `oc_mimetypes`(`mimetype`) VALUES(?)' with params [\"image\\\/gif\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'image\/gif' for key 'mimetype_id_index'","level":0,"time":"2015-01-29T13:26:25+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sha\/penguins-mysql\/3m_sie.gif"}
{"reqId":"f4dc467bb2fb5b51f0b446be252b5f61","remoteAddr":"127.0.0.1","app":"core","message":"Exception during mimetype insertion: An exception occurred while executing 'INSERT INTO `oc_mimetypes`(`mimetype`) VALUES(?)' with params [\"image\\\/gif\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'image\/gif' for key 'mimetype_id_index'","level":0,"time":"2015-01-29T13:26:25+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/sha\/penguins-mysql\/aniolek.gif"}
```
The warning is harmless though and won't cause further issues.

This only shows the kind of concurrency problems that exist in the codebase.

### Versions
OC 8 git master, also possible in OC 7 and previous.

@nickvergessen @icewind1991 @DeepDiver1975

### PR DESCRIPTION
**Pull request by nickvergessen**
...ition

Fix #13764

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
I'd go for INSERT WHERE NOT EXISTS - this would keep insert and check atomic

**Comment by nickvergessen** [comment]
does that exist for all dbs?

**Comment by DeepDiver1975** [comment]
> does that exist for all dbs?

time to find out

**Comment by nickvergessen** [comment]
@DeepDiver1975 everything went better then expected :speak_no_evil:

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 everything went better then expected :speak_no_evil:

awesome!

**Comment by nickvergessen** [comment]
> this call could be done conditionally - based on the return value of insertIfNotExist

@DeepDiver1975 while I see the idea behind this, I'd rather do it unconditionally, because otherwise we will run this query multiple times, because the local cache is never refreshed.
In case it's newly inserted we need to refresh the cache to get the value, in case it's not inserted we need to refresh the cache because it still does not contain the value.

**Comment by nickvergessen** [comment]
@PVince81 +1 from you as a reporter?

**Comment by nickvergessen** [comment]
@DeepDiver1975 @PVince81 @LukasReschke should be ready

**Comment by LukasReschke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
pr against master -> milestone 8.1

**Comment by DeepDiver1975** [comment]
@nickvergessen please open a pr against stable8 - THX

**Pull request merged**
