### PR TITLE
fix rename field position, fix #12927

### LINKED ISSUE #12927: Rename in Shared with you is too far to the right
* caused by the favorites stars that aren't present in the shared with you listing

cc @jancborchardt @PVince81 

favorites-fuck-up

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #12927

Please review @owncloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
Need to add an exception for when stars are not present still …

**Comment by jancborchardt** [comment]
All done now

**Comment by karlitschek** [comment]
nice :+1:

**Comment by MorrisJobke** [comment]
:+1: CSS only change -> merge

**Pull request merged**
