### PR TITLE
Oracle quote delete column

### PR DESCRIPTION
**Pull request by PVince81**
For https://github.com/owncloud/core/issues/27466.

- Adds a test for dropping columns to confirm that no extra quoting is needed for Oracle.
- Small tweak to autotest.sh to be able to run it without a local sqlplus instance.

@DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] before merging, check the log to make sure sqlplus did run on the Oracle log

**Comment by DeepDiver1975** [comment]
hmmmm - 18:20:54 sqlplus not found, using sleep to wait for Oracle initialization

**Comment by PVince81** [comment]
Damn, so `which sqlplus` cannot detect sqlplus ?

**Comment by PVince81** [comment]
I made a mistake in the original script, forgot a "$" when evaluating "SQLPLUS".
Should work now.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
