### PR TITLE
Remove arbitrary expression in empty

### LINKED ISSUE #19793: [8.2 RC2] White Screen of Death when Accessing Admin Page
When I log in as an admin and I try to get to the admin page via the top right menu (Admin option) I get a white screen of death.

Expected behavior:
Click on the admin panel and be able to see the admin page, and manage apps that are enabled.

What actually Happened:
Click on the admin panel and get a white screen of death. Log file below.

Likely this is the LDAP app, because as soon as I disable the LDAP app, the white screen goes away and I can access settings on the server.

Log Entry:
image

Setup:
SLES
MySQL
Windows 10 Firefox (repeated with Windows 8.1 Firefox and Chrome)
ownCloud 8.2.0 RC2 released 10/14/2015.
Dropped this onto the SLES enterprise appliance base build, and everything else seems to be working except this.

### PR DESCRIPTION
**Pull request by LukasReschke**
Those are only allowed in PHP 5.5, thus making our code incompatible with PHP 5.4

Fixes https://github.com/owncloud/core/issues/19793

### CODE REVIEW

**Comment by karlitschek** [comment]
nice! :+1: please also backport as discussed :-)

**Comment by LukasReschke** [comment]
8.2: https://github.com/owncloud/core/pull/19796

**Comment by nickvergessen** [comment]
:+1:

**Comment by Xenopathic** [comment]
> Fun fact though: `if(empty($var))` is equivalent to `if(!$var)`

So yeah, this is good, but IMO `empty()` is pretty redundant anyway

**Comment by nickvergessen** [comment]
`empty()` does not yield a warning about undefined keys, like `!` does.
So while in this case it is "redundant", it is the saver way for (nested) arrays.

**Pull request merged**
