### PR TITLE
port detection needs to take care of now thrown exceptions when LDAP …

### PR DESCRIPTION
**Pull request by blizzz**
…server is not available

How to reproduce?
1. Have LDAP enabled and a server ready with a default port (e.g. 389)
2. Do a new LDAP configuration and enter the host
3. Click "Detect Port" (on OC8 it is done automatically)

Before this fix: port is not found
With this fix: port is found

The regression was introduced with https://github.com/owncloud/core/pull/15811.
Stable 8 is affected as well, probably stable7 to  (~~will confirm~~ confirmed).  

@MorrisJobke  @DeepDiver1975 @butonic @cmonteroluque 

We also need to clarify whether it is a maintenance release blocker or not. Manual configuration still works.

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:  please back port

**Comment by MorrisJobke** [comment]
I tested this and it works now. On master it was broken. :+1:

Thanks for spotting it.

Code also looks good.

**Comment by MorrisJobke** [comment]
@blizzz Please prepare the backport

**Comment by blizzz** [comment]
on it

**Comment by blizzz** [comment]
And done #16758 (stable8),  #16759 (stable7)

**Pull request merged**
