### PR TITLE
[stable8] Backport of #15564

### PR DESCRIPTION
**Pull request by rullzer**
As requested in https://github.com/owncloud/core/pull/15564#issuecomment-92794691

Basically the same commit, now just at the stable8 branch.

CC: @PVince81 @MorrisJobke @DeepDiver1975 @LukasReschke @karlitschek

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I would say this have to wait for 8.0.4.

**Comment by karlitschek** [comment]
backport is fine but please 8.0.4

**Comment by rullzer** [comment]
Ah 8.0.4 is also fine of course :)

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
