### PR TITLE
Show individual sql schema migration steps during upgrade - on web as…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… well as on the command line

Display progress in the command line:
bildschirmfoto von 2016-03-30 23-31-26

Web upgrade in progress:
bildschirmfoto von 2016-03-30 23-07-50

Successful web upgrade:
bildschirmfoto von 2016-03-30 23-09-47

Successful web upgrade with warning:
bildschirmfoto von 2016-03-30 23-12-26

Error during upgrade:
bildschirmfoto von 2016-03-30 23-07-14

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Currently the upgrade is so fast, that the messages just flicker and are completely useless.

I would propose following:

* [ ] display all messages during the upgrade (might be collapsed while it finished successfully)
* [ ] display all messages if the upgrade fails (otherwise it is really hard to know where it failed)

**Comment by MorrisJobke** [comment]
cc @jancborchardt

**Comment by MorrisJobke** [comment]
* [ ] somehow avoid the wrapping on the console (stable9 to this branch):

bildschirmfoto 2016-03-30 um 23 54 29

**Comment by jancborchardt** [comment]
> Currently the upgrade is so fast, that the messages just flicker and are completely useless.

That’s completely fine. It gives a sense of fast progression. And if the messages vanish fast then they were successful and are thus irrelevant.

When there are errors or warnings, they are shown. What’s the exact problem here?

**Comment by MorrisJobke** [comment]
> When there are errors or warnings, they are shown. What’s the exact problem here?

The error itself is shown, but I would really love to see when it happens. It's a huge difference if an error happens during the DB schema upgrade or during the app upgrade.

**Comment by jancborchardt** [comment]
So we should add that info there when the error happened. Not necessary to show the whole log. :) Can you change that @DeepDiver1975?

**Comment by MorrisJobke** [comment]
> So we should add that info there when the error happened. Not necessary to show the whole log. :) Can you change that @DeepDiver1975?

I would really not for show the full log once an error happened.

**Comment by DeepDiver1975** [comment]
lets add an element where we list all messages just like before but hide the element and add some buttont/element to slide it up .....

**Comment by MorrisJobke** [comment]
> lets add an element where we list all messages just like before but hide the element and add some buttont/element to slide it up .....

@jancborchardt proposed to do this like the "Database & Storage" section during setup.

**Comment by DeepDiver1975** [comment]
@MorrisJobke console issue solved - mind retesting

**Comment by MorrisJobke** [comment]
This is how it looks now:

bildschirmfoto 2016-03-31 um 13 54 08


It somehow truncates, but not enough. :(

**Comment by DeepDiver1975** [comment]
> This is how it looks now:

me being tooooo stupid to substr :question: :confused:

**Comment by MorrisJobke** [comment]
Now the web UI looks like this:

bildschirmfoto 2016-03-31 um 14 26 19


The expanded view looks like:

bildschirmfoto 2016-03-31 um 14 26 44


Is this okay for you, @jancborchardt ?

**Comment by jancborchardt** [comment]
The »Detailed logs« thing should be after »The update was successful, but with errors.« And have the down arrow. We never ever use this right-arrow thingy and it’s not necessary.

Also, the detailed log should be in an extra container and text-align: left; just like the section »The following apps were deactivated«

Otherwise it’s fine. :)

**Comment by MorrisJobke** [comment]
I implemented the stuff that @jancborchardt wants to have. Ready for review now :)

**Comment by MorrisJobke** [comment]
> me being tooooo stupid to substr

Oh ... right the console part is broken.

**Comment by DeepDiver1975** [comment]
> me being tooooo stupid to substr :question: :confused:

fixed :idiot:

**Comment by jancborchardt** [comment]
Fine by me now btw after looking at it with @MorrisJobke. :+1:

**Comment by MorrisJobke** [comment]
Looks a lot better:

```
$ ./occ upgrade 
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for <dav> can be updated (this can take a long time depending on the database size)
CREATE UNIQUE INDEX dav_sha...            
 70/70 [============================] 100%
Checking whether the database schema for <federation> can be updated (this can take a long time depending on the database size)
CREATE UNIQUE INDEX url_has...            
 7/7 [============================] 100%  
Checking whether the database schema for <files_sharing> can be updated (this can take a long time depending on the database size)
CREATE INDEX sh_external_us...            
 9/9 [============================] 100%  
Checking whether the database schema for <files_trashbin> can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 0.2.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 0.5.0
Updating <updatenotification> ...
Updated <updatenotification> to 0.2.0
Updating <federation> ...
CREATE UNIQUE INDEX url_has...            
 7/7 [============================] 100%  
Updated <federation> to 0.1.0
Updating <files> ...
Updated <files> to 1.5.1
Updating <dav> ...
CREATE UNIQUE INDEX dav_sha...            
 70/70 [============================] 100%
Updated <dav> to 0.2.3
Updating <files_sharing> ...
CREATE UNIQUE INDEX sh_exte...            
 9/9 [============================] 100%  
Updated <files_sharing> to 0.10.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 0.9.0
Updating <files_versions> ...
Updated <files_versions> to 1.3.0
Updating <comments> ...
Updated <comments> to 0.3.0
Updating <systemtags> ...
Updated <systemtags> to 0.3.0
Update successful
Turned off maintenance mode
Reset log level
```


Also the web UI looks good.

But running `./occ upgrade -v` still has a glitch where the whitespace somehow grows between the messages:

bildschirmfoto 2016-04-04 um 13 58 59

**Comment by MorrisJobke** [comment]
This seems to be a problem with the output formatter. It looks like the formatter is applied recursively because the later messages have more whitespace in front.

Maybe @nickvergessen knows more

**Comment by DeepDiver1975** [comment]
@MorrisJobke @nickvergessen 

verbose output is fixed now and there is a second event for the schema migration test

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2016-04-04 16-24-18

**Comment by MorrisJobke** [comment]
Awesome, works like a charm :+1:

**Comment by jancborchardt** [comment]
Great work all around :raised_hands:

**Pull request merged**
