### PR TITLE
Prevent leaving the DB update page while in progress

### LINKED ISSUE #17528: Prevent closing upgrade page while upgrade in progress
### Steps to reproduce
1. Run OC upgrade using the web UI by clicking on "Start update"
2. During the upgrade, close the browser tab

### Expected result
A warning shows that upgrade is in progress.

### Actual result
Tab can be closed.

@owncloud/designers

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/17528

Please review @jancborchardt @MorrisJobke @nickvergessen @oparoz @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1: (even on IE8) Also the code looks good

**Comment by jancborchardt** [comment]
Can you provide a screenshot for quicker design review? I’m just interested if it’s a browser dialog, or OC dialog, and how the buttons are labeled if there are any.

**Comment by MorrisJobke** [comment]
Only the text of the browser popup can be changed:

bildschirmfoto von 2015-10-14 07-59-23

**Comment by MorrisJobke** [comment]
@pvince I just noticed following bug:

* [ ] allow to refresh if update has failed (checkout stable8.1 activity and try to upgrade from oc8.1 to this branch)

**Comment by PVince81** [comment]
Hmm right, I thought errors would go through the warning code path.

**Comment by PVince81** [comment]
done: https://github.com/owncloud/core/commit/1d3c9ff27f5d4ce3334dcf7cdc72625326c90ead

**Comment by jancborchardt** [comment]
Ok, looks good design- and wording-wise then. :)

**Comment by PVince81** [comment]
Needs a second reviewer @jancborchardt @nickvergessen @LukasReschke @oparoz

**Comment by PVince81** [comment]
or @rullzer @icewind1991 ?

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
I don't think this is critical, so not sure regarding backport @MorrisJobke @karlitschek

**Comment by karlitschek** [comment]
yes. not critical. No backporting for now.

**Comment by DeepDiver1975** [comment]
rebased ...

**Pull request merged**
