### PR TITLE
[8.2] Update list of deprecated methods

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #19731 

Approval https://github.com/owncloud/core/pull/19731#issuecomment-148082730

@karlitschek 8.2.0 or 8.2.1 your choice

@LukasReschke @MorrisJobke review :)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> @karlitschek 8.2.0 or 8.2.1 your choice

8.2.1 is enough from my PoV

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by rullzer** [comment]
:+1:

**Comment by karlitschek** [comment]
yes. definitely 8.2.1 please backport :-)

**Pull request merged**
