### PR TITLE
verify path when getting a node for sabredav

### LINKED ISSUE #16825: Renaming folders in webdav interface using backslash coded doesn't return proper error.
### Steps to reproduce

1. Rename a folder using curl:
```
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H 'Destination:http://User:Password@Host/remote.php/webdav/%2F'
```
or
```
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H 'Destination:http://User:Password@Host/remote.php/webdav/%2Fhola'
```
or
```
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H "Destination:http://User:Password@Host/remote.php/webdav/hola%2Fhola"
```

### Expected behaviour
It should answer error, forbidden characters.

### Actual behaviour
In first case it returns `<s:exception>Sabre\DAV\Exception\Forbidden</s:exception>`
In second case 'carpeta' is renamed to 'hola'
In third case it return "The destination node is not found"

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
None.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

curl

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #16825

cc @DeepDiver1975 @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
I hesitated to add this at first and added `verifyPath` in the specific operations then.
But I guess it makes sense to do it here to make sure it's always caught.

:+1:

**Comment by PVince81** [comment]
CC @SergioBertolinSG

**Comment by PVince81** [comment]
Total breakage. I knew I should have tested it... Did you even test it @icewind1991 ?

It breaks the sync client "Internal Server Error (empty filename not allowed)"

**Comment by PVince81** [comment]
Revert PR here https://github.com/owncloud/core/pull/16883

**Comment by PVince81** [comment]
I simply merged the revert PR.
Please resubmit. Thanks.

**Pull request merged**
