### PR TITLE
Orphaned shares test and some requirements

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
@PVince81 it is failing getting a 500 instead of a 400 in the last step added.

### CODE REVIEW

**Comment by PVince81** [comment]
Strange, am getting this:
```
--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @Given User :arg1 deletes file :arg2                                                                                                       
     */                                                                                                                                           
    public function userDeletesFile2($arg1, $arg2)                                                                                                
    {                                                                                                                                             
        throw new PendingException();                                                                                                             
    }     
```

**Comment by SergioBertolinSG** [comment]
Let me check.

**Comment by SergioBertolinSG** [comment]
Ok now it fails with the 500:  

https://jenkins.owncloud.org/job/owncloud-core/job/core/job/PR-25977/2/testReport/junit/(root)/sharing/orphaned_shares/

**Comment by PVince81** [comment]
Okay, got it reproduced now, thanks!

**Comment by PVince81** [comment]
Following the steps manually and at the end:
```
  % curl -X PROPFIND http://user1:test@localhost/owncloud/remote.php/webdav/sub
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>InvalidArgumentException</s:exception>
  <s:message>Jail rootPath is null</s:message>
</d:error>
```

**Comment by PVince81** [comment]
@SergioBertolinSG something to add to the test, maybe as separate case: can user1 create a folder called "sub" ? (the internal logic seems to forbid this, even though the share should not be mounted any more)

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/26001 for the core issue. This will take a bit longer to fix...

**Comment by PVince81** [comment]
oops, pushed on the wrong branch

**Comment by PVince81** [comment]
restored to the previous state.

**Comment by PVince81** [comment]
The test seems to pass with https://github.com/owncloud/core/pull/26004

**Comment by PVince81** [comment]
Rebased. The error should be gone now.

**Comment by PVince81** [comment]
Tests passed now, :+1: 

@SergioBertolinSG merge or did you want to add more stuff ?

**Comment by SergioBertolinSG** [comment]
Merge yes.

**Pull request merged**
