### PR TITLE
fix new menu not showing on mobile, fix #18879

### LINKED ISSUE #18879: "New" Button doesn't work on small screens
I just discovered the the new "New" Button doesn't work on small screens:

Steps to reproduce:

1. Reduce the size of your browser window until the sidebar at the left gets closed.
2. Click on the "New" button to create a new folder/file

Expected Result:

Dropdown opens and let you create a new file/folder

Actual Result:

Nothing happens

cc @PVince81

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix https://github.com/owncloud/core/issues/18879, please review @schiesbn @davitol @PVince81 @owncloud/designers

Simple z-index issue, easy to review.

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks :+1:

**Comment by jancborchardt** [comment]
Another review please @schiesbn @davitol @owncloud/designers

CI is irrelevant here because it’s only a CSS change.

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 @karlitschek any org owner please user their magic mighty powers to merge this then as it’s just a CSS change and tests are hence irrelevant …

**Comment by davitol** [comment]
:+1: it works :smiley:

**Comment by schiesbn** [comment]
works great :+1:

**Comment by jancborchardt** [comment]
I call for the powers that be to hear my prayers
and merge this simple CSS-only but very important change.

Oh I praise thee!

**Comment by DeepDiver1975** [comment]
REJECTED!

**Pull request merged**
