### PR TITLE
[jenkins] + rebased, of #21838

### PR DESCRIPTION
**Pull request by blizzz**
Once there are enough votes on https://github.com/owncloud/core/pull/21838 and test run, this one can be merged, as this is rebased in master (opposite to the original PR).

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@blizzz Could you check out the failing LDAP unit tests?

**Comment by blizzz** [comment]
reports are not there anymore, *rebased*

**Comment by blizzz** [comment]
I adjusted unit tests.

**Comment by MorrisJobke** [comment]
@alexweirig Could I ask you to state the license? Either state that this change is MIT licensed or sign the CLA (https://owncloud.org/contribute/agreement/) and send it to @karlitschek

**Comment by alexweirig** [comment]
@MorrisJobke Yes, I can confirm you that this is MIT licensed.

**Comment by blizzz** [comment]
looks good :+1: could not test with the additional attribute, but otherwise groups seems to work normally. 

@owncloud/ldap we need one more reviewer. Original PR is #21838, but this one here is up to date.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by blizzz** [comment]
@alexweirig now it's in – thank you for your contribution!

**Comment by alexweirig** [comment]
@blizzz Thank you very much for your support and patience.

**Pull request merged**
