### PR TITLE
[WIP] Stream download for DAV exteral storage

### PR DESCRIPTION
**Pull request by icewind1991**
Prevents having to first download files from DAV to a temporary stream

cc @PVince81 @DeepDiver1975 @lokeller

### CODE REVIEW

**Comment by PVince81** [comment]
@icewind1991 do we want to revive this for 8.2 ?

**Comment by MorrisJobke** [comment]
@Xenopathic @icewind1991 Revive or kill?

**Comment by icewind1991** [comment]
revive

**Comment by MorrisJobke** [comment]
> revive

Are you already reviving? ;)

**Comment by icewind1991** [comment]
Superseeded by #18653

**Pull request closed without merging**
