### PR TITLE
Backport of #16890 to stable7

### PR DESCRIPTION
**Pull request by blizzz**
@MorrisJobke @jvillafanez

### CODE REVIEW

**Comment by jvillafanez** [comment]
The user count, at least for the group, doesn't seem to be updated. The rest of the things work fine.

**Comment by blizzz** [comment]
> The user count, at least for the group, doesn't seem to be updated.

Also, perhaps caching?

**Comment by MorrisJobke** [comment]
Tested and works. :+1:

> The user count, at least for the group, doesn't seem to be updated. The rest of the things work fine.

Then it's another bug. This should only address the issue, that once a folder naming rule is configured the folder isn't deleted. And this PR fixes this.

**Comment by MorrisJobke** [comment]
@jvillafanez Please retest this.

**Comment by jvillafanez** [comment]
I'll open a bug for the user count. The rest is working as expected :+1:

**Comment by jvillafanez** [comment]
No bug for the user count. It's LDAP configuration related, so no problems on this side

**Pull request merged**
