### PR TITLE
Assert that there are no xml error left

### LINKED ISSUE #21267: InfoParser is not cleaning up the xml parser errors ....
... this is why we see https://github.com/owncloud/core/pull/21195 failing

Very funny .....

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #21267

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Ready to be reviewed - THX

**Comment by DeepDiver1975** [comment]
@LukasReschke @MorrisJobke @icewind1991 @nickvergessen @PVince81 
Ready to be reviewed - THX

**Comment by MorrisJobke** [comment]
:+1:

**Comment by rullzer** [comment]
Ah nice. Could be a frustrating debugging session otherwise
:+1:

**Comment by DeepDiver1975** [comment]
THX

**Pull request merged**
