### PR TITLE
run upgrades in incognito mode

### LINKED ISSUE #24592: oc_authtoken missing when accessing update screen with existing session
### Steps

1. Checkout v9.0.2 from git
1. Setup ownCloud
1. Login as admin and keep logged in
1. Switch to master 8729415880181275c9d4a05707273e13c9cf7e1b
1. Refresh the page

### Expected result
Update page appears

### Actual result
Error page, log:
```
{"reqId":"8jaFPhGD6jt8Gn97L\/y9","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `uid`, `password`, `name`, `type`, `token`, `last_activity` FROM `oc_authtoken` WHERE `token` = ?' with params [\\\"1154847d4a5776ff188063e5205d682dc4b98213a5dd6c1821a62ed69c3e30dd5b7a26c571544f29adb5d4a168cb64745fa12bd2f2f22d3e5052d8cfc4c35769\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_authtoken' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(184): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenMapper.php(77): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(112): OC\\\\Authentication\\\\Token\\\\DefaultTokenMapper->getToken('1154847d4a5776f...')\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(220): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->getToken('kq0j4n000o4cabh...')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(208): OC\\\\User\\\\Session->validateSession(Object(OC\\\\User\\\\User))\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/L10N\\\/Factory.php(131): OC\\\\User\\\\Session->getUser()\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/L10N\\\/Factory.php(99): OC\\\\L10N\\\\Factory->findLanguage('core')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Server.php(895): OC\\\\L10N\\\\Factory->get('core', NULL)\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Server.php(123): OC\\\\Server->getL10N('core')\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(102): Pimple\\\\Container->offsetGet('EncryptionManag...')\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('EncryptionManag...')\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Server.php(681): OC\\\\ServerContainer->query('EncryptionManag...')\\n#17 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(726): OC\\\\Server->getEncryptionManager()\\n#18 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(645): OC::registerEncryptionWrapper()\\n#19 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(947): OC::init()\\n#20 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(37): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#21 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","level":3,"time":"2016-05-12T08:45:19+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/","user":"admin"}
```

It looks like it's trying to access/use the session.
However when an update is due, the session must be ignored (or use the incognito mode).

Maybe the recent changes to the session workflow is causing this ?

@ChristophWurst @LukasReschke 

Assigning to @ChristophWurst as discussed

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes #24592

Not sure if this breaks other stuff as I don't fully understand the code in base.php

cc @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Doesn't seem to work when upgrading from v9.0.2 to this branch and having an existing session in Firefox:
```
{"reqId":"ozzQhuSPshCZY9XW1Nlr","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_authtoken`(`uid`,`password`,`name`,`token`,`type`,`last_activity`) VALUES(?,?,?,?,?,?)' with params [\\\"admin\\\", \\\"c5684966c91064838cd109d6aff31ea2|we3jz9kl9PRX13Bt|0cfa8fb4e53e750853aaad134b0b1b4a49f75959bdac183fbbdaa5b89f5af15be8e516338d1457888872e3def58ed38a053106d658f5f4ad9f5cb824fe692a66\\\", \\\"Mozilla\\\\\\\/5.0 (X11; Linux x86_64) AppleWebKit\\\\\\\/537.36 (KHTML, like Gecko) Chrome\\\\\\\/49.0.2623.112 Safari\\\\\\\/537.36\\\", \\\"b100cd6b6aaa898aa68809ef4a66afdb6ea0ebf95d608cc375e5fd2ae78d8523c880fa1eb8dbc198e101dfdf500d76350cafd38ddddadf87fa629ee2dece6380\\\", 0, 1463049294]:\\n\\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(175): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(251): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(125): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(84): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OC\\\\Authentication\\\\Token\\\\DefaultToken))\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(408): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->generateToken('4ibq7op4221tr37...', 'admin', 'admin', 'Mozilla\\\/5.0 (X1...')\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(188): OC\\\\User\\\\Session->createSessionToken(Object(OC\\\\AppFramework\\\\Http\\\\Request), 'admin', 'admin')\\n#7 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin('admin', 'admin', '%2Fowncloud%2Fi...')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(45): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/login')\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":3,"time":"2016-05-12T10:34:54+00:00","method":"POST","url":"\/owncloud\/index.php\/login?redirect_url=%252Fowncloud%252Findex.php%252Fapps%252Ffiles%252F","user":"admin"}
```

Maybe this happens even earlier ?

Strangely it seems to work on Chrome...

**Comment by PVince81** [comment]
Okay, it seems to be related to the route you use when opening the update page.

The index page works and shows the update page.
If the route is the files app, it doesn't work: http://localhost/owncloud/index.php/apps/files/ (blank page and exception as above)

**Comment by ChristophWurst** [comment]
@PVince81 please post the stack trace so I can see why and where it fails

**Comment by PVince81** [comment]
already posted here https://github.com/owncloud/core/pull/24597#issuecomment-218720805

I'll reformat it

**Comment by PVince81** [comment]
wrong stack trace apparently...

Will post the correct one

**Comment by PVince81** [comment]
Never mind, looks like something was messed up on my setup, possibly because I got the "too long user agent" issue with Chrome and then tried to rerun the upgrade in Firefox.

Looks like it works now in Firefox when testing from scratch :+1:

**Comment by ChristophWurst** [comment]
@LukasReschke please have a look as you also experienced that bug once

**Comment by MorrisJobke** [comment]
Works 👍

**Comment by PVince81** [comment]
Close enough... merging

**Pull request merged**
