### PR TITLE
make test run with latest FF

### PR DESCRIPTION
**Pull request by individual-it**
## Description
changes to make it possible to run UI tests in the current Firefox browser (tested with v56.0)
This tests do not run in CI, but can be run locally. To be able to run them in CI saucelabs needs to implement this feature request: https://saucelabs.ideas.aha.io/ideas/VDC-I-50 (**please vote for it!**)

To run them locally you need some additional steps to https://github.com/owncloud/documentation/blob/master/developer_manual/core/ui-testing.rst
1. set the browser version `export BROWSER_VERSION=56.0`
2. use selenium v.3.6.0
3. use geckodriver v0.18 or newer http://www.seleniumhq.org/download/
4. start selenium with `-enablePassThrough false` e.g. `java -jar selenium-server-standalone-3.6.0.jar -enablePassThrough false -port 4445`

I will update the documentation as soon this PR is tested and approved

The moving Files and Folders tests are skipped because of "moveMouseTo" issues in the geckodriver.

## Related Issue
#29284

## Motivation and Context
see issue

## How Has This Been Tested?
run tests locally in Firefox 56, made travis check if the tests still work in other

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
I have run this locally on my Ubuntu16.04 VM and got all tests to pass. Looks good.

**Comment by phil-davis** [comment]
Note: In #29199 I suggested moving the existing Firefox 47 automated UI test jobs into the Travis daily cron list, rather than running them on every PR. See comments there - a decision about that can happen separately to this PR.

**Comment by phil-davis** [comment]
Backport stable10 #29289

**Comment by individual-it** [comment]
documentation changes in https://github.com/owncloud/documentation/pull/3470

**Pull request merged**
