### PR TITLE
[stable8] Make update server URL configurable

### PR DESCRIPTION
**Pull request by LukasReschke**
Currently testing the updates is a big problem and not really super easy possible. Since we now have a new updater server we should also make this configurable so that people can properly test updates.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
:+1: makes sense. I've been asked this in the past, if it was possible - some ppl (eg providers) run multiple instances and like to control upgrades, too. Not sure if they are up right away for running their own upgrade server, but if they want...

Besides, could be interesting for support providers and partners, too I guess.

**Comment by blizzz** [comment]
looks good :+1:

**Comment by PVince81** [comment]
Rebased

**Comment by PVince81** [comment]
Failing encryption test not related.

**Pull request merged**
