### PR TITLE
[stable10] owncloud coding standard

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #31442 

The first commits backport the various interim php-cs-fixer changes from PR #31198 #31236 #31250 #31271 #31273 

That was the easy way to make a list of cherry-picks that all fit nicely on top of each other. And its brings along the ``Makefile`` and drone changes etc that were already done before #31442 

The last commit uses ``php-cs-fixer`` to make the automatic fixes needed for the code in ``stable10``

```
lib/composer/bin/php-cs-fixer fix -v --diff --allow-risky yes
```

### CODE REVIEW

**Review by patrickjahns — DISMISSED** [review]
Please wait until we have a final agreement when to do the backport

**Comment by phil-davis** [comment]
@patrickjahns @DeepDiver1975 now that the coding standard has been merged to ``master``, this can also be reviewed and merged whenever you are happy.

Lately when doing backports I have been having to process "mindless" conflicts due to the previously-applied coding standards in ``master`` that has not been backported. So having this backport done in ``stable10`` should make the code match better in the 2 branches and reduce "rubbish" conflicts.

**Comment by patrickjahns** [comment]
@phil-davis 

There are some open tasks that need to be checked on stable10 - especially if `native_function` breaks polyfill components

**Comment by phil-davis** [comment]
PR #31657 has a newer/cleaner set of commits for this.

**Pull request closed without merging**
