### PR TITLE
Cleanup trashbin expire code

### PR DESCRIPTION
**Pull request by MorrisJobke**
- [x] requires #20790 
- I tested some trash expiries and they still work 

cc @rullzer @PVince81 @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> cc @rullzer @PVince81 @schiesbn

This is now ready for review :)

**Comment by rullzer** [comment]
Looks good.
Removed and restored some files and all seemed well. Cronjob also did not choke.

:+1:

**Comment by MorrisJobke** [comment]
@nickvergessen @PVince81 @schiesbn Please review :)

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
