### PR TITLE
Fix pagination on public file list

### LINKED ISSUE #19886: pagination doesn't work on public link share page
Tested with v8.2.0 (git tag)

1. create a folder
2. upload 30 files (need to be more than 20 in my case)
3. share folder as link
4. open the link

Expected behavior:

file list should show all 30 files

Actual behavior:

file list shows only the first 20 files

cc @PVince81

### PR DESCRIPTION
**Pull request by Henni**
fixes #19886

please review @schiesbn @MorrisJobke @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by nickvergessen** [comment]
@karlitschek your :+1:  means backport is approved?

**Comment by PVince81** [comment]
usually it doesn't

**Comment by karlitschek** [comment]
absolutely. please backport. Thanks for the quick fix :-)

**Comment by karlitschek** [comment]
Yes. Thats different. Sorry for not being clear. Please backport. This one is obvious. And thanks for the quick fix :-)

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19896

**Comment by fritz-fritz** [comment]
Yes this definitely fixed the problem I was having. Thought I had broken something!

**Comment by five-team** [comment]
This fix doesn't works for Internet Explorer 11 :(

**Comment by MorrisJobke** [comment]
> This fix doesn't works for Internet Explorer 11 :(

Please open a new ticket for this.

**Pull request merged**
