### PR TITLE
Bump version in version.php

### PR DESCRIPTION
**Pull request by HanaGemela**

### CODE REVIEW

**Review by phil-davis — DISMISSED** [review]

**Review by jnweiger — CHANGES_REQUESTED** [review]
We miss some earlier steps in the release template.
https://github.com/owncloud/handbook/pull/244

The changelog/unrelease folder should be renamed *before* we tag and bump version here.

**Review by jnweiger — APPROVED** [review]
better :-)

**Review by micbar — APPROVED** [review]
please squash the commits into one

**Review by micbar — CHANGES_REQUESTED** [review]
the merge commit could be avoided by a rebase, please squash

**Comment by micbar** [comment]
@HanaGemela You have two commits because maybe you clicked "resolve conflicts"  in the UI.

This created a merge commit `merge changes from ...`

This could be avoided by rebasing.

Please squash the two commits into one.

**Comment by HanaGemela** [comment]
@micbar I can't. Merging and squashing is blocked because you requested changes.

**Comment by phil-davis** [comment]
@HanaGemela you do it locally with git commands and then force push.

**Comment by HanaGemela** [comment]
@phil-davis I haven't seen your comment. I used `git rebase -i HEAD~2` hope the outcome is also OK.

**Review by phil-davis — COMMENTED** [review]
Now it has 40 files changed. It has all the renames of the changelog entries. Those are already in the release branch.
What happened?
Maybe it will be easier to make a new PR.

**Comment by phil-davis** [comment]
Something hung in drone https://drone.owncloud.com/owncloud/core/24075/42/6
It has been running nearly 5 hours with no more output.
I will cancel and restart drone.

**Comment by HanaGemela** [comment]
Closing the PR and starting over

**Comment by jnweiger** [comment]
`release-10.4.1` branch is removed. Ready to starting over.

**Pull request closed without merging**
