### PR TITLE
Add use statement

### LINKED ISSUE #16011: OCP\AppFramework\Controller::buildResponse() indicates wrong return type
```php
/**
 * Serializes and formats a response
 * @param mixed $response the value that was returned from a controller and
 * is not a Response instance
 * @param string $format the format for which a formatter has been registered
 * @throws \DomainException if format does not match a registered formatter
 * @return Response
 * @since 7.0.0
 */
public function buildResponse($response, $format='json') {
```
https://github.com/owncloud/core/blob/master/lib/public/appframework/controller.php#L132-L141

The PHPDoc indicates the return type is ```OCP\AppFramework\Response```, which is not a defined typed. The actual return type is ```OCP\AppFramework\Http\Response```.

### PR DESCRIPTION
**Pull request by LukasReschke**
Just fixes the PHPDoc and also fixes #16011

### CODE REVIEW

**Comment by LukasReschke** [comment]
@MorrisJobke @dagan Please review. Thanks :smile:

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by dagan** [comment]
:+1:

**Pull request merged**
