### PR TITLE
show a better error message when trying to create a user that already exists

### LINKED ISSUE #14965: Adding user with already existing name gives unintelligble error
1. Have a list of users
2. Try to add a new user with an already existing name
3. Get unhelpful error modal: »Unable to create user«

Instead, there should be an inline tooltip at the username input field which says »Username already taken«.

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #14965

### CODE REVIEW

**Comment by MorrisJobke** [comment]
A lot better :+1:

cc @jancborchardt @nickvergessen @rullzer @oparoz @Xenopathic  Review time :)

**Comment by Xenopathic** [comment]
:+1:

**Comment by Xenopathic** [comment]
@karlitschek Suggest we backport this?

**Comment by jancborchardt** [comment]
Thanks again @icewind1991 :)

**Comment by karlitschek** [comment]
not an urgent fix but also low risk. Please backport

**Comment by MorrisJobke** [comment]
stable8 #15064

**Pull request merged**
