### PR TITLE
Fix check new dav rename target path name

### LINKED ISSUE #28441: Renaming to .htaccess problems in UI
### Steps to reproduce
1. Create a file aaaa.txt
2. Try to rename to .htaccess

### Expected behaviour
A reasonable error message is displayed - e.g. Could not rename "aaaa.txt"
The original aaaa.txt file is listed in the UI.

### Actual behaviour
Error displayed:
```
Could not rename "aaaa.txt", it does not exist any more
```
and the file is gone from the display in the UI.

Note: refreshing the page brings back the file aaaa.txt to the UI list. So the original file is still there on server storage.

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
PHP dev
**Database:**
MySQL
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
10.0.2+ current master as of right now 20/07/2017

### Client configuration
**Browser:**
Firefox 54.0
**Operating system:**
Ubuntu 16.04

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Verify target path earlier to make sure 403 is returned in case of wrong
target (ex: ".htaccess") instead of 404.

The reason this happens is because the rename code path between old and new DAV endpoints are different. Old DAV fails earlier when Sabre's CorePlugin does a `getNodeForPath()` on the target even for a local rename. New DAV doesn't go through this code path and reached `Node:setName()` more directly, possibly due to the necessary changes that were done lately regarding moves.

## Related Issue
Fixes https://github.com/owncloud/core/issues/28441.
Should also fix the renameFile/renameFolder failures on master.

## How Has This Been Tested?
Manual testing with cadaver on new dav endpoint: rename "welcome.txt" to ".htaccess".
Before the fix: 404
After the fix: 403

Automated tests have been reenabled.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by individual-it** [comment]
there are more skipped tests in `tests/integration/features/webdav-related-new-endpoint.feature`

**Comment by PVince81** [comment]
@individual-it I can't find them

**Review by individual-it — APPROVED** [review]
👍 fixes the issue

**Comment by individual-it** [comment]
sorry did overlooked one file in your commit

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/28737

**Review by phil-davis — APPROVED** [review]

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
