### PR TITLE
Set higher timeout limit

### PR DESCRIPTION
**Pull request by JetUni**
Set the timeout limit to be 20 instead of 5 for machines that take longer to load the apps from apps.owncloud.org so that it doesn't show up blank.

### CODE REVIEW

**Comment by PVince81** [comment]
I think it's fine :+1: 

What do you think @DeepDiver1975 @LukasReschke @georgehrke ?

**Comment by georgehrke** [comment]
seems reasonable 👍

**Comment by JetUni** [comment]
This contribution is MIT licensed

**Comment by rullzer** [comment]
This shows that we should tests all PR's on our CI.
This broke the master unit tests!

PR incomming.

**Pull request merged**
