### PR TITLE
[9.0] Add comment icons and "You commented" translations

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of https://github.com/owncloud/core/pull/23422
Approval https://github.com/owncloud/core/pull/23422#issuecomment-199227883

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
We need to backport translations as well .... who can run the might @vgezer tool? :wink: 
@nickvergessen @MorrisJobke THX

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by nickvergessen** [comment]
I will run the tool beginning next week

**Comment by nickvergessen** [comment]
Ref https://github.com/owncloud/core/issues/22916

**Pull request merged**
