### PR TITLE
Dont set the string storage id to the numeric storage id for personal mounts

### LINKED ISSUE #20800: Can't access a shared folder on external storage
### Steps to reproduce
1. Share a directory on a external folder with another user
2. From the second user, try to access to the folder

### Expected behaviour
When access to the shared folder, the user should see
the files inside.

### Actual behaviour
I can share a directory with a second user. But when I log
with the second user credentials, I can't see the folder
under the "All files" section. When I select the "Shared
with you" section, I see the shared folder, but when I click
on it, I am redirected to the root directory of the "All files"
section.
It works well with a shared folder on the local storage, only
with shared folder on external storage (Dropbox and sftp).

### Server configuration
**Operating system**: Linux / Debian 8.0

**Web server:** Nginx 1.8.0

**Database:** Mysql 5.5.46

**PHP version:** 5.6.14

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** Updated from 8.1

**List of activated apps:**
Enabled:
- activity: 2.1.3
- calendarplus: 1.1.1
- contactsplus: 1.0.9
- encryption: 1.1.0
- files: 1.2.0
- files_external: 0.3.0
- files_pdfviewer: 0.7
- files_sharing: 0.7.0
- files_texteditor: 2.0
- files_trashbin: 0.7.0
- files_versions: 1.1.0
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- galleryplus: 14.3.0
- news: 6.1.1
- provisioning_api: 0.3.0
- rainloop: 4.8
- tasksplus: 1.0.3
- templateeditor: 0.1
- updater: 0.6
Disabled:
- documents
- external
- files_mv
- files_videojs-sublime
- gallery
- notifications
- sharelinks
- user_external
- user_ldap

  **The content of config/config.php:**
{
    "system": {
        "instanceid": "ocol0bgh0j92",
            "passwordsalt": "***REMOVED SENSITIVE VALUE***",
            "secret": "***REMOVED SENSITIVE VALUE***",
            "trusted_domains": [
                "127.0.0.1",
            "***REMOVED SENSITIVE VALUE***"
            ],
            "datadirectory": "\/var\/oc-data",
            "overwrite.cli.url": "http:\/\/127.0.0.1:8080\/owncloud",
            "dbtype": "mysql",
            "version": "8.2.1.4",
            "dbname": "ocdb",
            "dbhost": "127.0.0.1",
            "dbtableprefix": "oc_",
            "dbuser": "***REMOVED SENSITIVE VALUE***",
            "dbpassword": "***REMOVED SENSITIVE VALUE***",
            "logtimezone": "UTC",
            "installed": true,
            "memcache.local": "\\OC\\Memcache\\APCu",
            "asset-pipeline.enabled": true,
            "mail_from_address": "owncloud",
            "mail_smtpmode": "php",
            "mail_domain": "***REMOVED SENSITIVE VALUE***",
            "loglevel": 2,
            "theme": "",
            "maintenance": false,
            "trashbin_retention_obligation": "auto"

    }

}

     **Are you using external storage, if yes which one:** local/sftp/Dropbox

     **Are you using encryption:** yes

     **Are you using an external user-backend, if yes which one:** No

### Client configuration
       **Browser:** Firefox (Iceweasel 40.0.3)

       **Operating system:** Linux / Debian Testing

#### Web server error log

31.32.174.92 - - [27/Nov/2015:19:31:34 +0100] "GET /index.php/apps/files/ajax/list.php?dir=%2FCecile.InstantUpload&sort=name&sortdirection=asc HTTP/1.1" 404 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 Iceweasel/40.0.3"
31.32.174.92 - - [27/Nov/2015:19:31:34 +0100] "GET /index.php/apps/files/ajax/list.php?dir=%2F&sort=name&sortdirection=asc HTTP/1.1" 200 2475 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 Iceweasel/40.0.3"
31.32.174.92 - - [27/Nov/2015:19:31:34 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 203 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 Iceweasel/40.0.3"
31.32.174.92 - vincent [27/Nov/2015:19:31:34 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2040 "-" "Mozilla/5.0 (Linux) mirall/2.0.2"

#### ownCloud log (data/owncloud.log)

{"reqId":"22uTGxVFlH9mUlFZ59Oj","remoteAddr":"31.32.174.92","app":"files_sharing","message":"Unable to get mount for shared storage '20' user 'cecile'","level":3,"time":"2015-11-27T18:31:34+00:00"}

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes getById for files on personal external storage mount (which broke shares from personal mounts)

Fixes #20800

cc @PVince81 @Xenopathic

### CODE REVIEW

**Comment by PVince81** [comment]
Hmm you just renamed the attribute name, how can this fix the issue ? Is there a hidden piece of magic I'm missing ?
Also, would be good to update/add unit tests if possible.

**Comment by icewind1991** [comment]
that's the whole fix :smile: , it was overwriting an attribute from the parent class that had a different meaning

**Comment by MorrisJobke** [comment]
> Hmm you just renamed the attribute name, how can this fix the issue ? Is there a hidden piece of magic I'm missing ?
> Also, would be good to update/add unit tests if possible.

storageID is also a variable in the parent class. This change avoids overwriting it ;)

**Comment by PVince81** [comment]
Arghhh, got it

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
Would still be good to have a unit test that at least reproduces the original issue.

**Comment by PVince81** [comment]
@icewind1991 mind adding a unit test ?

**Comment by icewind1991** [comment]
Added tests

**Comment by PVince81** [comment]
Nice :+1: 

Second reviewer @nickvergessen @Xenopathic @MorrisJobke ?

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek The original issue was scheduled for 8.2.2 - I would request a backport.

**Comment by karlitschek** [comment]
sure. please backport! :+1:

**Comment by icewind1991** [comment]
8.2: https://github.com/owncloud/core/pull/21069

**Pull request merged**
