### PR TITLE
Fix scanning: emit 'scanFile' will only fire on files and not on folders

### PR DESCRIPTION
**Pull request by mmattel**
This is a fix for #19458 (Scanner sends folder through the scanFile event)
In addition, I did some optical cleanups and improvements at ScanFile for better readability.
@icewind1991 @PVince81 @DeepDiver1975 @oparoz 

Before:

```
sudo -uwww-data ./occ files:scan --all -v
Scanning file   /user0/
Scanning folder /user0/
Scanning file   /user0/files
Scanning file   /user0/thumbnails
Scanning file   /user0/cache
Scanning folder /user0/files
Scanning file   /user0/files/welcome.txt
Scanning file   /user0/files/folder2
Scanning file   /user0/files/folder1
Scanning folder /user0/files/folder2
Scanning folder /user0/files/folder1
Scanning file   /user0/files/folder1/hs_err_pid3522.log
Scanning file   /user0/files/folder1/x11vnc-0.9.14-dev.tar.gz
Scanning folder /user0/thumbnails
Scanning file   /user0/thumbnails/3
Scanning folder /user0/thumbnails/3
Scanning file   /user0/thumbnails/3/2048-2048-max.png
Scanning file   /user0/thumbnails/3/32-32.png
Scanning folder /user0/cache
Scanning file   /user1/
Scanning folder /user1/
Scanning file   /user1/files
Scanning folder /user1/files
Scanning file   /user1/files/welcome.txt
Scanning file   /user2/
Scanning folder /user2/
Scanning file   /user2/files
Scanning folder /user2/files
Scanning file   /user2/files/welcome.txt

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 11      | 18    | 00:00:00.4   |
+---------+-------+--------------+
```

After:

```
sudo -uwww-data ./occ files:scan --all -v
Scanning folder /user0/
Scanning folder /user0/files
Scanning file   /user0/files/welcome.txt
Scanning folder /user0/files/folder2
Scanning folder /user0/files/folder1
Scanning file   /user0/files/folder1/hs_err_pid3522.log
Scanning file   /user0/files/folder1/x11vnc-0.9.14-dev.tar.gz
Scanning folder /user0/thumbnails
Scanning folder /user0/thumbnails/3
Scanning file   /user0/thumbnails/3/2048-2048-max.png
Scanning file   /user0/thumbnails/3/32-32.png
Scanning folder /user0/cache
Scanning folder /user1/
Scanning folder /user1/files
Scanning file   /user1/files/welcome.txt
Scanning folder /user2/
Scanning folder /user2/files
Scanning file   /user2/files/welcome.txt

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 11      | 7     | 00:00:00.5   |
+---------+-------+--------------+
```

### CODE REVIEW

**Comment by mmattel** [comment]
https://github.com/owncloud/gallery/pull/387 (@oparoz)

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by oparoz** [comment]
Thanks for the heads up. It doesn't really affect owncloud/gallery#387 unless it's back ported ;)

:+1:

**Comment by mmattel** [comment]
@oparoz There is a small but positive effect of this PR also for your PR 387. If this one gets merged, files/folders beeing processed will be counted correctly if your PR gets merged, so users can rely on proper data. Remember ~20k of pictures in many folders...  :smile:

**Comment by oparoz** [comment]
@mmattel - AFAIK, they're already [counted correctly](https://github.com/owncloud/gallery/pull/387/files#diff-286dd85312d39d2f79bf1dd8f5ee44bcR123) in my PR. The only benefit will be less data to process, but that's for any lister to the scanFile events :)

**Comment by mmattel** [comment]
Closing and restart with #21702

**Pull request closed without merging**
