### PR TITLE
[Tests-Only] Update issue tags for ocis tags

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Unskip ocis tests for custom href properties in webdav responses.

## Related Issue

- Related https://github.com/owncloud/ocis-reva/issues/122

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Comment by individual-it** [comment]
please make a PR to OCIS and OCIS-REVA to prove that it works there

**Comment by dpakach** [comment]
> please make a PR to OCIS and OCIS-REVA to prove that it works there

@individual-it  The issue is closed but seems like it is not properly fixed yet. Some tests are failing still

**Comment by individual-it** [comment]
do we need to reopen https://github.com/owncloud/ocis-reva/issues/122 ?

**Comment by dpakach** [comment]
> do we need to reopen [owncloud/ocis-reva#122](https://github.com/owncloud/ocis-reva/issues/122) ?owncloud/ocis-reva#122

No I think that was a different issue. I have opened new one in owncloud/ocis-reva#214

**Review by individual-it — APPROVED** [review]

**Pull request merged**
