### PR TITLE
Setting the active navigation entry to 'files_index' is so wrong ...

### LINKED ISSUE #27839: App title says "Apps" instead of "Files" for the files app
### Steps

1. Setup v10.0.0
1. Log in
1. See title behind the cloud icon on the top right

### Expected
"Files"

### Actual
"Apps"
Note that switching to "Gallery" properly replaces it with "Gallery", so might be specific to the special app "Files".

### Versions
10.0.0

Regression introduced through the info.xml support for navigation entries: https://github.com/owncloud/core/pull/26785

@DeepDiver1975 do you have time to have a look ?

cc @pmaier1

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
The app name of files should be files ... how magical ...

## Related Issue
fixes https://github.com/owncloud/core/issues/27839

## How Has This Been Tested?
- switch between files app and settings
- choose different language to make sure translations work as well

## Screenshots (if appropriate):
bildschirmfoto von 2017-05-09 15-31-22

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by davitol** [comment]
👍 WFM

**Comment by DeepDiver1975** [comment]
@individual-it any idea why this is falling apart? https://travis-ci.org/owncloud/core/jobs/230361342 THX

**Comment by individual-it** [comment]
some funny internal error ether on travis or saucelabs.
Restarting the job did fix it

**Comment by PVince81** [comment]
:+1: code makes sense

**Pull request merged**
