### PR TITLE
[stable10] Add Roave Security Advisories as a development dependency

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #31673

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: assuming this only affects dev time

**Comment by PVince81** [comment]
moving to next as there is currently no certainty that this will not affect the current lib versions at build time

**Comment by DeepDiver1975** [comment]
> moving to next as there is currently no certainty that this will not affect the current lib versions at build time

what will happen worst case is that make will fail on composer install because we use a vulnerable dependency. A good thing from my pov.

**Comment by PVince81** [comment]
does it mean future builds of old OC versions could fail if new descovered vulnerabilities have been found ?

**Comment by DeepDiver1975** [comment]
> does it mean future builds of old OC versions could fail if new discovered vulnerabilities have been found ?

no because this is a pure dev dependency

**Pull request merged**
