### PR TITLE
Allow to cancel 2FA after login

### LINKED ISSUE #24745: Ability to cancel two factor auth
### Steps to reproduce
1. Log in
2. See 2FA challenge page

### Expected behaviour
There should be a button/link to log out the current user.

### Actual behaviour
2FA is enforced, the only way to cancel it is clearing cookies.

**ownCloud version:**
9.1.0.2

cc @PVince81 @LukasReschke

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #24745 

@ChristophWurst

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Awesome, thanks!

**Comment by ChristophWurst** [comment]
@PVince81 @rullzer second review? :-)

**Comment by nickvergessen** [comment]
Just pushed, because I forgot to adjust the tests

**Comment by PVince81** [comment]
Tested, works :+1:

**Pull request merged**
