### PR TITLE
[8.0] Add a warning when the transaction isolation level is not READ_COMMITED

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of https://github.com/owncloud/core/pull/24889
Approval https://github.com/owncloud/core/pull/24889#issuecomment-222621118

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Second review ? @DeepDiver1975 @butonic

**Comment by nickvergessen** [comment]
or @rullzer

**Comment by DeepDiver1975** [comment]
looks a bit shitty :speak_no_evil: 


bildschirmfoto von 2016-06-03 23-13-21

**Comment by PVince81** [comment]
@nickvergessen might need some styles adjustment. I think there were changes between versions

**Comment by nickvergessen** [comment]
Done:
owncloud_-_2016-06-06_11 46 06

**Comment by PVince81** [comment]
:+1:

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
