### PR TITLE
Do not delete group if empty, hide delete icon for group admin

### PR DESCRIPTION
**Pull request by michag86**
fix for #18379

### CODE REVIEW

**Comment by karlitschek** [comment]
@blizzz what do you think?

**Comment by blizzz** [comment]
:+1: works

@MorrisJobke @LukasReschke how about you?

**Comment by MorrisJobke** [comment]
You should also remove https://github.com/owncloud/core/blob/9ad4510f5b8ddc5f932f78e55adeb6763906d12b/settings/js/users/users.js#L473-L481 otherwise the JS will remove the group from the interface.

**Comment by michag86** [comment]
@MorrisJobke @blizzz @LukasReschke  can you please check again?

**Comment by MorrisJobke** [comment]
Tested and works now :+1:

**Pull request merged**
