### PR TITLE
Backport 15596 remote share feedback urls

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #15596 - approved https://github.com/owncloud/core/pull/15596#issuecomment-97614501

Missing the modification of the external manager tests, because they are not in stable8 (missing #14537, #14580 and #15160)

### CODE REVIEW

**Comment by nickvergessen** [comment]
Missing the modification of the external manager tests, because they are not in stable8 (missing #14537, #14580 and #15160)

Not sure if we want to backport them all, @icewind1991 @DeepDiver1975

**Comment by DeepDiver1975** [comment]
@nickvergessen please push the required changes into this PR so that we can see how big the change will be at the end - THX

**Comment by nickvergessen** [comment]
@DeepDiver1975 done

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
Bump @icewind1991 @DeepDiver1975

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
