### PR TITLE
[stable8] Disable the cache updater when doing the encryption migration

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/owncloud/core/pull/14573

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@icewind1991 please label prs and issues accordingly - THX

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by PVince81** [comment]
@karlitschek looks good as in "backport approved" ? :wink:

**Comment by karlitschek** [comment]
yes :-)

**Comment by PVince81** [comment]
8.0.1 or 8.0.2 ? (testing now)

**Comment by DeepDiver1975** [comment]
8.0.1 would have been great - but time's up from my understanding @karlitschek @jnfrmarks

**Comment by karlitschek** [comment]
Yes. unfortunately too late for 8.0.1

**Comment by PVince81** [comment]
Fine by me, I also prefer 8.0.2. Just wanted to be sure.

:+1: tested with 1600 files, works

**Pull request merged**
