### PR TITLE
Compile JS scripts to find errors

### PR DESCRIPTION
**Pull request by rullzer**
Basically https://github.com/owncloud/core/issues/20299

You need to download and supply the file compiler yourself (https://developers.google.com/closure/compiler/docs/gettingstarted_app) since we probabaly don't want that in the repo.

The bash script is very simple but probably good enough for now. It does take some time unfortunatly. For CI it might make sense to find the changed js files and only pass those to the script.

CC: @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> The bash script is very simple but probably good enough for now. It does take some time unfortunatly. For CI it might make sense to find the changed js files and only pass those to the script.

Why not having a separate CI job for this? ;) cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Or make it part of the jsunit execution

**Comment by rullzer** [comment]
I thinking part of jsunit execution is fine. (I can add it there). But it will need some manual configuring since I don't think we want to add the compiler to our repo...

**Comment by DeepDiver1975** [comment]
> I thinking part of jsunit execution is fine. (I can add it there). But it will need some manual configuring since I don't think we want to add the compiler to our repo...

Let's add this to the autotest-js.sh script:
0. if /tmp/compiler.jar exists -> goto 3
1. download the zip https://dl.google.com/closure-compiler/compiler-latest.zip to tmp
2. unzip it
3. run it

**Comment by PVince81** [comment]
For syntax errors, you can use JSLint/JSHint in your IDE.
But yeah, checking for such errors for committed code is also a good idea.

**Comment by rullzer** [comment]
@PVince81 we should also use jslink and jshint indeed. But a compiler can even find different stuff.. for example it already throws some warnings about IE8 stuff.. which could be usefull. 

@DeepDiver1975 fair enough. Let me fix that.

**Comment by rullzer** [comment]
Let me close this until I have time to look into some of the issues... at least we now know that it can be done...

**Pull request closed without merging**
