### PR TITLE
Don't use pcre/pcre8 patterns to validate email addresses 

### LINKED ISSUE #16720: email syntax not accepted
Logged in as admin I can neither send share links to that email address nor use that address as a test recipient within the admin e-mail-server section.

It seems within the file /var/www/cloud803/3rdparty/phpmailer/phpmailer/class.phpmailer.php I run into the pcre8 switch where it verifies the email with a fals result. I added some error_log lines before and after, using kai(at)kaikretschmann.de as email doesn't work there. (Replace the "at" as usual).

And I can't debug that pattern manually.

PHP 5.6.9-1~dotdeb+7.1
apache 2.2.22
debian wheezy/7.8
OwnCloud 8.0.3

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #16720

@kkretsch please test if this fixes the issue for you - THX

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@kkretsch please retest once more - THX

**Comment by kkretsch** [comment]
As I suspected: the foreign phpmailer class revalidates on setting the receipient and sender email addresses within its own clas without any second argument defaulting to "auto" again. If I override that auto default for testing it works for me.

**Comment by DeepDiver1975** [comment]
not yet enough :coffee: in my :brain: .... @kkretsch let's try it once more ....

**Comment by kkretsch** [comment]
@DeepDiver1975 To be more precise: The file 3rdparty/phpmailer/phpmailer/class.phpmailer.php has to member functions addAnAddress and setFrom where it calls $this->validateAddress($address) for the given argument address.

That call has the implicit default argument of 'auto' for the validation and triggers the default switch case "pcre8" again. So even if we call the validation using the second argument beeing 'php' every call to those two function validates again using the no-wanted pcre8 syntax.

The only way might be to have these functions implemented different in a child class within owncloud. Or change the phpmail project itself.

**Comment by DeepDiver1975** [comment]
according to https://github.com/owncloud/core/issues/16720#issuecomment-110051198 - this will be fixed upstream

**Pull request closed without merging**
