### PR TITLE
show exception type in debug mode

### PR DESCRIPTION
**Pull request by icewind1991**
Makes debuging a bit easier

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@rullzer @Xenopathic @nickvergessen Want to review?

**Comment by MorrisJobke** [comment]
Really nice :) Works and helps a lot :+1:

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975

**Comment by Xenopathic** [comment]
Ah yes, the most important piece of information regarding exceptions :+1:

**Pull request merged**
