### PR TITLE
[stable10] Enable SMB logging for the Community Edition 

### PR DESCRIPTION
**Pull request by mmattel**
## Description
Backport of #30185 (Enable SMB logging for the Community Edition) 14b6937

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@PVince81 @jvillafanez

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

@cdamken FYI

**Comment by mmattel** [comment]
@PVince81 why did drone fail? Reading the output, it seems that it has no relation to the PR - or?

**Comment by phil-davis** [comment]
```
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57
```
Bad planetary alignment. I restarted the drone job.

**Comment by phil-davis** [comment]
The planets came back into alignment.

**Comment by mmattel** [comment]
@phil-davis 
hahaha, thanks

**Pull request merged**
