### PR TITLE
[stable8.2] LDAP: do not attempt to process user records without display name, fi…

### PR DESCRIPTION
**Pull request by blizzz**
…xes fatal error

(Missing) Backport of #20804 to 8.2

@karlitschek please approve backport :)

Please test and review @owncloud/ldap @MorrisJobke @it25fg @Uzzi @scollin @musaa32

### CODE REVIEW

**Comment by nextclouds** [comment]
awesome. backport makes sense 👍

**Comment by MorrisJobke** [comment]
awesome. backport makes sense :+1:

**Comment by davidak** [comment]
i applied this patch and it solves the problem. 👍 

(`occ user:report` shows the users but not the webinterface, but thats a different problem)

**Comment by blizzz** [comment]
thx @davidak

**Pull request merged**
