### PR TITLE
Add SFTP tests to CI

### PR DESCRIPTION
**Pull request by PVince81**
Thanks to the phpseclib update, the last remaining failing test is gone !

@DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Own repo? Move to ftp repo?

**Comment by PVince81** [comment]
> Own repo? Move to ftp repo?

Yes, at some point. But I don't want to start yet another construction site here until https://github.com/owncloud/core/pull/25422 is merged. Without that PR, every separate ext storage app would need to auto-enable files_external to work properly.

**Comment by DeepDiver1975** [comment]
Pretty long run time .....

````
00:54:45.489 Waiting for sftp initialization......
00:54:46.834 No coverage
00:54:46.834 PHPUnit 5.5.4 by Sebastian Bergmann and contributors.
00:54:46.835 
00:54:46.835 Runtime:       PHP 7.0.10 with Xdebug 2.4.1
00:54:46.836 Configuration: /var/lib/jenkins/workspace/owncloud-core_core_PR-26283-SNFCZ5D7XTG5URIGDACQIMBGTEJ73TXNN55PZGBXKIPDWNSXVHZA/tests/phpunit-autotest-external.xml
00:54:46.837 
02:54:19.758 ............................................................Sending interrupt signal to process
02:54:30.625 Makefile:121: recipe for target 'test-external' failed
02:54:30.634 make: *** [test-external] Terminated
02:54:30.638 Terminated

**Comment by PVince81** [comment]
Wow... on my local machine it might take 5 mins or so

**Comment by DeepDiver1975** [comment]
> Wow... on my local machine it might take 5 mins or so

let me rerun it ....

**Comment by DeepDiver1975** [comment]
> Wow... on my local machine it might take 5 mins or so

did hang again - also hangs on my machine ....

**Comment by PVince81** [comment]
Let's resume this when we move SFTP out into its own repo.

**Pull request closed without merging**
