### PR TITLE
Delete no longer existing users from system addressbook

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by rullzer** [comment]
Am I correct to assume this runs on every request? Because then this will not scale.

**Comment by rullzer** [comment]
But of course you kind of need to because LDAP e.g. do not notify us :(

**Comment by DeepDiver1975** [comment]
> Am I correct to assume this runs on every request? Because then this will not scale.

seriously - you expect me to submit a change like that? :fearful:

**Comment by rullzer** [comment]
> seriously - you expect me to submit a change like that?

That was why is was surprised... but now I see it is just the command... sorry :P

**Comment by rullzer** [comment]
so then: :+1:

**Comment by PVince81** [comment]
Unit test ? :wink: 
Maybe move it to a utility method to make it easier

**Comment by DeepDiver1975** [comment]
> Unit test ? :wink:
> Maybe move it to a utility method to make it easier

yes - the whole command is currently not tested - I need to move the logic into a class of it's own which can be reused from a cron job as well.

^ part of the next pr

**Comment by PVince81** [comment]
Fair enough :+1:

**Comment by DeepDiver1975** [comment]
THX

**Pull request merged**
