### PR TITLE
[stable10] Introduce persistent and explicit locking of file and folders, increase version to 10.1

### PR DESCRIPTION
**Pull request by DeepDiver1975**
# BLOCKED

backport of #31651

## ToDo
- [ ] "set min-version to 10.1"

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Blocker: proper version bump to 10.0

**Comment by PVince81** [comment]
you mean version bump to 10.1 ?

**Review by PVince81 — APPROVED** [review]
:+1: please resolve conflict

**Comment by DeepDiver1975** [comment]
Time outs on some ui tests:

```
INFORMATION: timed out waiting for outstanding ajax calls
SCENARIO RESULT: (fail)
  @skipOnOcV11 @issue-33634
  Scenario Outline: Admin can open links in help and tips page                      # /drone/src/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature:22
    When the administrator opens the link for "<linkName>"                          # WebUIHelpAndTipsContext::theAdministratorOpensTheLinkFor()
    Then the user should be redirected to a webUI page with the title "<pageTitle>" # WebUIGeneralContext::theUserShouldBeRedirectedToAWebUIPageWithTheTitle()

    Examples:
      | linkName                        | pageTitle                       |
      | How to do backups               | Backing up ownCloud             |
        │ INFORMATION: timed out waiting for outstanding ajax calls
        Failed asserting that 'Oops! You're lost.' starts with "Backing up ownCloud".
INFORMATION: timed out waiting for outstanding ajax calls
SCENARIO RESULT: (fail)
      | Performance tuning              | ownCloud Server Tuning          |
        │ INFORMATION: timed out waiting for outstanding ajax calls
        Failed asserting that 'Oops! You're lost.' starts with "ownCloud Server Tuning".
INFORMATION: timed out waiting for outstanding ajax calls
SCENARIO RESULT: (fail)
      | Improving the config.php        | Core Config.php Parameters      |
        │ INFORMATION: timed out waiting for outstanding ajax calls
        Failed asserting that 'Oops! You're lost.' starts with "Core Config.php Parameters".
INFORMATION: timed out waiting for outstanding ajax calls
SCENARIO RESULT: (fail)
      | Theming                         | Theming ownCloud                |
        │ INFORMATION: timed out waiting for outstanding ajax calls
        Failed asserting that 'Oops! You're lost.' starts with "Theming ownCloud".
INFORMATION: timed out waiting for outstanding ajax calls
SCENARIO RESULT: (fail)
      | Hardening and security guidance | Hardening and Security Guidance |
        │ INFORMATION: timed out waiting for outstanding ajax calls
        Failed asserting that 'Oops! You're lost.' starts with "Hardening and Security Guidance".

--- Failed scenarios:

    /drone/src/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature:27
    /drone/src/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature:28
    /drone/src/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature:29
    /drone/src/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature:30
    /drone/src/tests/acceptance/features/webUIAdminSettings/helpAndTips.feature:31

**Comment by PVince81** [comment]
I've restarted the swift tests, just in case...

**Comment by phil-davis** [comment]
UI tests, that is sad. That could be because those tests go off looking to see if the help links "really exist".
If drone has trouble seeing the "real internet" or the linked documentation site is down then the test likely fails. Issue https://github.com/owncloud/core/issues/33639 is raised to think about an improved way to "validate" a link.

**Review by PVince81 — APPROVED** [review]
:+1: let's move on...

**Comment by phil-davis** [comment]
Now I see that the UI test issue was real (and a dumb test, of course). This PR bumped the version to 10.1, which caused the generated doc links to contain ``10.1`` - e.g. https://doc.owncloud.org/server/10.1/go.php?to=admin-backup

And those do not exist on the real doc site.

If I had realized all that, I would have added a commit here to skip the "not smart enough" test.

Anyway, fixed by #33759

**Pull request merged**
