### PR TITLE
Utilize memberOf to boost loading time on users page (depending on LDAP server config)

### LINKED ISSUE #15956: Abnormally large time loading the users page with a large LDAP server
### Steps to reproduce
1. Setup a large LDAP server (checked with two local server with 6 and 1000 users, and two additional servers inside a VPN with 1000 and 1M users)
2. Go to the users page

### Expected behaviour
Page is loaded in an acceptable amount of time (showing the first 30 users and taking into account the network speed, probably less than 30 secs)

### Actual behaviour
It takes an abnormal amount of time (11m 22s) to load just the first 30 users.

screenshot from 2015-04-30 10 45 47

screenshot from 2015-04-30 10 57 31

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
To be checked if it because of the app, or due to a slow response of the LDAP server (bad configuration, LDAP server not optimized, server overloaded, etc)

### PR DESCRIPTION
**Pull request by blizzz**
As dicussed in https://github.com/owncloud/core/pull/16402#issuecomment-108010981, this PR will make fetching of a users group far more faster (takes on my system only 3-8% of the time compared to how much it ran before). 

It requires that the LDAP server supports memberOf (AD does out of the box, needs to be enabled in OpenLDAP, others unknown). Otherwise it will fall back to the default methods, which includes a costly search operation per user.

Reproduction steps: 
1. have LDAP with  memberOf overlay configured
2. open  users page and watch loading times of …/index.php/settings/users/users

Fixes #15956 together with https://github.com/owncloud/core/pull/16402

@DeepDiver1975 @jvillafanez @nickvergessen @Xenopathic

### CODE REVIEW

**Comment by karlitschek** [comment]
cool idea :+1:

**Comment by DeepDiver1975** [comment]
@jvillafanez can you please test this? THX
@jnfrmarks FYI

**Comment by jvillafanez** [comment]
Timing for this branch:

screenshot from 2015-06-08 12 58 28

Timing for master branch:

screenshot from 2015-06-08 12 58 53

The configuration is pretty much the same in both cases: the first one (for this branch) has an additional inactive server, which shouldn't eat too much time. In both cases, the server is in a local network.

Taking into account the extra requests the first one is doing (probably something related with firebug or the computed page height), the images confirm some improvement in the loading time.

I still need to check the remote LDAP server.

**Comment by DeepDiver1975** [comment]
> Fixes #15956 together with #16402

@jvillafanez #16402 (meanwhile merged) has to be applied as well to get a decent experiance

**Comment by blizzz** [comment]
> Taking into account the extra requests the first one is doing (probably something related with firebug or the computed page height), the images confirm some improvement in the loading time.

the stuff starting with GET 32?requesttoken is fetching user avatars. The changes have impact on GET users?…

**Comment by blizzz** [comment]
The avatar fetches cause two userExists checks each, caching helps with them.

**Comment by jvillafanez** [comment]
One large remote server over VPN:

screenshot from 2015-06-09 08 58 09

Last time I checked, it was around 15 min, so good improvement.

I think we can still boost the performance a bit more: one request to get all groups -> around 2-3 minutes, and another one to get the first users (including the memberof attribute) -> less than 1 minute. My timing calculation (including delays due to the VPN) doesn't match. Am I missing something?

**Comment by blizzz** [comment]
> one request to get all groups -> around 2-3

that's the thing: all groups. ideally we also fetch only a subset and have the remaining loaded using infinite scrolling. The challenge however is how to load the groups, because we sort by number of users. It would not be so much an issue for local groups, as this can be done by SQL magic. LDAP groups however … There is no sorting in Paged Results, even if it was possible to sort by number of $member attributes. And without, you cannot browse and get a bad performance. In the filter, you can also look for the presence of those and then it might be that the remaining users are filtered out. So, not a possibility. Loading only the first ones and the others following might bring a weird UX, but it would work. 

Best would be for the admin to keep the numbers of groups as small as possible.

We can do better when we decide to sync user / group lists so we have them ready in the database for that matter. This is not a short term solution, though.

**Comment by DeepDiver1975** [comment]
@MTRichards please decide of the performance as shown above is enough for 8.1 - THX

**Comment by MTRichards** [comment]
A 90% improvement seems like a good start. If it is only 90 %, well, I guess that is ok :smile:

Let's start here and consider the longer term solution in the future.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
