### PR TITLE
assume pgsql >=9 if checking the version fails

### LINKED ISSUE #19391: Bug? Error occurred while checking PostgreSQL version
I'm trying to get Owncloud 8.1.3 running on Wheezy with PostgreSQL 9.1.18.  Running through the wizard to setup the database I'm getting the following error:

    Error occurred while checking PostgreSQL version
    Please make sure you have PostgreSQL >= 9 or check the logs for more information about the error

I've updated the config.php file with version, with no luck.  [This thread refers](https://forum.owncloud.org/viewtopic.php?f=31&t=30677&p=97620#p97620).  Checking the Postgres version with the same line ([from util.php?](https://github.com/owncloud/core/commit/a152f3a50fbae79c2fae98cf013aa71ca82174fb)) that appears to issue the error:

    postgres=# SHOW SERVER_VERSION;
     server_version
    ----------------
     9.1.18
    (1 row)

So I'm unclear why this error is being raised.  Grateful for assistance.

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #19391

@CannyFoxx @DrDanke can you check if this solves the issue

cc @PVince81

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@icewind1991 milestone and labels please - THX

**Comment by icewind1991** [comment]
@PVince81 @DeepDiver1975 can this be merged?

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by geotheory** [comment]
This causes my page to fail:

**Comment by DeepDiver1975** [comment]
Please open a new issue. Thx

**Pull request merged**
