### PR TITLE
[3rdparty] Bump flysystem to 1.0.16

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/247

CC: @icewind1991 @Xenopathic @DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by rullzer** [comment]
rebased. and ref bumped

**Comment by DeepDiver1975** [comment]
> rebased. and ref bumped

thx

**Comment by rullzer** [comment]
All green :)

**Pull request merged**
