### PR TITLE
UI tests on Microsoft Edge browser

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Lengthen the files page wait till page is loaded timeout to 60 seconds. When using Edge, particularly in the sharing tests when the test logs in and out as user1, user2 and user3, things get slow in calculating and transferring... all the skeleton files with thumbnails at the 1st login of each user. It does actually work if it is given time. There is no point throwing a timeout exception "early" and there is no real loss in having the longer timeout. All the regular tests that work "quickly" in each browser will wait just like they used to. It is only if something goes wrong that we will now wait 60 seconds rather than 20 seconds before giving up.

2) The Edge webDriver is still rather stupid and unreliable. when calling ``$element->isVisible()`` or ``$element->click()`` it often throws back with ``NoSuchElement`` even though we just found the element. Catch this rubbish and do something reasonable (or just keep going, because sometimes it worked)

3) Run the Edge tests in the daily Travis cron job, like is done for Firefox and IE11.

4) Skip tests that try to navigate and click the sharing permissions buttons. Those tests require clicking on "label" elements, and Edge webDriver currently has trouble with clicking on stuff like that (it seems that thrying to click on a "label", "span", "a" and goodness knows what other tags is not working with Edge webDriver, but it works fine on Chrome and Firefox)

Some references for 4:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10290683/
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12306419/
https://github.com/SeleniumHQ/selenium/issues/4843
https://groups.google.com/forum/#!topic/selenium-users/xukryAZfpbc

## Related Issue
#29138 UI tests on Edge browser
#28016 Review supported browser versions

## Motivation and Context
Run the automated UI tests on as many supported browsers as reasonably possible.
That gives more confidence in finding annoying UI issues.

## How Has This Been Tested?
Successful runs of the Edge Travis matrix jobs have been done in a separate test PR in my fork.
e.g. https://github.com/phil-davis/core/pull/120

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

I will also make a test PR on top of this to run the Edge Travis matrix jobs here in the owncloud core repo.

### CODE REVIEW

**Review by individual-it — APPROVED** [review]
:+1: if the test run reasonable stable

**Comment by phil-davis** [comment]
Backport stable10 #29495

**Comment by kiragengis** [comment]
Hey phil-davis, looks like you solve the problem, what did you do ? I work with Selenium and C#

**Comment by kiragengis** [comment]
Hi, I figured out what is the problem, it's related to EDGE webDriver. The problem happen when the element has the attribute `overflow:hidden`, here you can follow this [issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11203904/)

**Pull request merged**
