### PR TITLE
Updated UI messages relating to the encryption functionality

### PR DESCRIPTION
**Pull request by settermjd**
This PR:

- Updates three UI message strings. The reason for updating them is that grammatically they're
not quite correct. Specifically, the corrections were to address:
  - Related phrases, which could be either separated or joined better
  - Related sentences, but which should be expressed as separate ones
  - Missing full-stops

### CODE REVIEW

**Comment by mmattel** [comment]
:+1:

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by settermjd** [comment]
Thanks for the rapid response

**Comment by PVince81** [comment]
screw Jenkins

**Pull request merged**
