### PR TITLE
fix: account terms can be removed if they differ with the ones stored

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Search terms for the accounts were only updated if new terms were present. However, if terms were removed, we weren't updating the terms.

## Related Issue
No opened issue

## How Has This Been Tested?
1. Install and configure the user_ldap app (consider default configuration)
2. Sync the ldap users
3. Change the "user search attributes" in the ldap wizard and add some attributes (at least 2)
4. Sync the ldap users again. Note that terms are populated in the "oc_account_terms" table
5. Remove one of the attributes in the "user search attributes"
6. Sync the ldap users

Without this patch, the "oc_account_terms" won't change, so the removed attribute can still be searched. With the patch, the table is updated

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by pako81 — APPROVED** [review]

**Comment by pako81** [comment]
@jvillafanez merge or should we ask for a second review?

**Review by phil-davis — APPROVED** [review]
Is it easy to add a test that covers this?

**Comment by jvillafanez** [comment]
> Is it easy to add a test that covers this?

If there aren't already tests for the class, I doubt it's easy

> @jvillafanez merge or should we ask for a second review?

Good to merge from my side.

**Comment by phil-davis** [comment]
> If there aren't already tests for the class, I doubt it's easy

Sadly, `lib/private/User/Account.php` does not have any unit tests.

**Pull request merged**
