### PR TITLE
[Test only] Make a comment change

### PR DESCRIPTION
**Pull request by phil-davis**
to see if Jenkins runs OK by default in stable10

### CODE REVIEW

**Comment by phil-davis** [comment]
This Jenkins fail happens here with just making a whitespace edit in a comment. So something is wrong with Jenkins or some code or test committed to stable10.
@PVince81 @SergioBertolinSG ???

**Comment by SergioBertolinSG** [comment]
hmm yes, seems there is a problem with auth.feature:10

```
08:17:02   ┌─ @BeforeScenario # FeatureContext::prepareParameters()
08:17:02   │
08:17:02   ╳  Failed asserting that '' contains "testing".
08:17:02   │
08:17:02   Scenario: access files app anonymously               # /var/lib/jenkins/workspace/owncloud-core_core_PR-28300-JYFUMONU36ZP3GGYQNOK7L35A3JQLD6FQ4LI4CKVIAVKZ65YKG7Q/tests/integration/features/auth.feature:10
```

I am thinking about the trashbin tests which requires a log in like using the web ui, maybe it is affecting this  test somehow.

**Comment by SergioBertolinSG** [comment]
No, trashbin tests were not merged yet. Actually that PR (https://github.com/owncloud/core/pull/28268) is failing for the same reason.

**Comment by SergioBertolinSG** [comment]
@PVince81 do you know about recent changes in stable10 which could make auth.feature:10 to fail?

**Comment by PVince81** [comment]
> @PVince81 do you know about recent changes in stable10 which could make auth.feature:10 to fail?

no

**Comment by PVince81** [comment]
bisect ?

**Comment by SergioBertolinSG** [comment]
The test alone doesn't fail locally. It has to run the whole suite. Probably it just requires some particular feature to run before auth.

Maybe we can modify run.sh to get tags as parameters, and add a tag to every feature. In this cases it is useful to be able to run just a couple of features.

**Comment by phil-davis** [comment]
This was only to test Jenkins runs - closing.

**Pull request closed without merging**
