### PR TITLE
[stable8] Disable video preview if previews are disabled

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #16840

Approved https://github.com/owncloud/core/pull/16840#issuecomment-110705012

Tested and works.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Fixes #9878

**Comment by MorrisJobke** [comment]
Please review @PVince81 @LukasReschke @cdamken

**Comment by PVince81** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
