### PR TITLE
Remove sidebar for trashbin view

### LINKED ISSUE #19506: Details view is unuseful for deleted files
### Steps to reproduce

1. Delete a file
2. Go to the trashbin
3. Click on details of the file deleted

### Expected behaviour
Details view makes nonsense for deleted files or previous activities should be shown

### Actual behaviour
Details view is available and shows the sidebar

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-10-01T03:09:06+00:00 d6e3195b38d8285c12a1fa4a23f8498e5122f4fe

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/19506

### CODE REVIEW

**Comment by PVince81** [comment]
Please review @nickvergessen @davitol @MorrisJobke @rullzer

**Comment by nickvergessen** [comment]
Works as intended, although it would be nice to have the activities and stuff available.

:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by davitol** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@PVince81 Please create the backport for 8.2.1

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19775

**Comment by karlitschek** [comment]
please backport :+1:

**Pull request merged**
