### PR TITLE
Fix cancel upload and hide 'uploading' message for files_drop shared folders

### LINKED ISSUE #33177: "File Drop" Public Link Cancelling is Buggy
### Steps to reproduce
1. Create a **file drop public link** in oC 10.0.10
2. Upload files

### Expected behaviour

1."uploading" text at the top of the page should **disappear** after the process is finished.
2. hitting the "x" to cancel the upload has to **cancel the upload**

### Actual behaviour

1."uploading" text at the top of the page **stays** after the process is finished.
2. hitting the "x" to cancel the upload has **no effect**.

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
Fix not working `cancel upload` and hide 'Uploading' message after the upload is done.

## Related Issue
- Fixes #33177 

## How Has This Been Tested?
https://github.com/owncloud/core/issues/33177#issue-369571133

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
@VicDeo would you manage some unit tests ? and/or UI tests ?

**Comment by phil-davis** [comment]
@VicDeo this suffered from the recent problem merged to master this afternoon.
Rebase and CI will feel better.

**Comment by VicDeo** [comment]
@PVince81 I see no opportunity for the unit tests here. acceptance tests are possible with a lot of pain.
Aching in progress...

**Comment by PVince81** [comment]
if this was never covered before it's an opportunity to bootstrap the tests... good luck

**Comment by VicDeo** [comment]
@PVince81 yes, files_drop page is not covered with acceptance tests at all.
Basic file upload scenario has been added. 
Our tests consider file to be uploaded as soon as the progress bar disappears.

**Review by PVince81 — APPROVED** [review]
:+1: fair enough

tests to be bootstrapped separately

**Comment by PVince81** [comment]
@VicDeo please backport for 10.1.1

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/core/pull/34097

**Pull request merged**
