### PR TITLE
Indicate that the share owner is remote in the filelist

### LINKED ISSUE #13571: Local and remote users with the same name show up as the same user when sharing files
### Steps to reproduce

1. Install owncloud on two systems
2. on system one, create user c1 and remote share an item with a user q1 on system 2 
3. on system two, create a user c1 and locally share with q1
4. The shared view shows "c1" in both cases

### Expected behaviour

The remote "c1" and the local "c1" would be differentiated in the shared icon

### Actual behaviour

The remote "c1" and the local "c1" are not differentiated in the shared icon

p248

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

### PR DESCRIPTION
**Pull request by nickvergessen**
Simple enough and improving UX quite a lot.
the remote domain is displayed on hover with tipsy

Fix #13571 

@jnfrmarks you reported this
@LukasReschke for the "social engineering attempt"
@jancborchardt for design approval

### CODE REVIEW

**Comment by LukasReschke** [comment]
Way to go. :+1:

I'm wondering whether we should give the `@…` some kind of other color to make it easier to distinct but that shall @jancborchardt decide ;-)

**Comment by nickvergessen** [comment]
Styling should easily be possible:
`html += '<span class="userDomain">@' + escapeHTML(userDomain) + '</span>';`

**Comment by nickvergessen** [comment]
@owncloud-bot re-test this please

**Comment by MorrisJobke** [comment]
Nice one :+1:

remote-share-vs-share

**Comment by MorrisJobke** [comment]
> I'm wondering whether we should give the @… some kind of other color to make it easier to distinct but that shall @jancborchardt decide ;-)

Adding yet another even lighter grey doesn't help here. I fine with that.

**Comment by jancborchardt** [comment]
Yeh, looks great! Sorry for not reviewing it earlier, still swamped with issues from last week.

**Pull request merged**
