### PR TITLE
[stable7] forward repair events to updater

### LINKED ISSUE #17313: Repair info during the upgrade isn't being shown
Checked upgrading 7.0.6 to 7.0.7 and with MySQL

### Steps to reproduce
1. Install ownCloud 7.0.6 with a MySQL DB
2. Modify some table charset and the collation to something different than utf8 (checked with charset = latin1 and collation = latin1_bin)
3. Upgrade the installation to 7.0.7 using cli

### Expected behaviour
Messages changing the collation of the tables to utf8 should be shown

### Actual behaviour
Those messages aren't shown.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.7

**Updated from an older ownCloud or fresh install:** upgrade from 7.0.6

ref https://github.com/owncloud/core/pull/17020

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #17313
- already in stable8+: 22bc37cb82368fba912a9e5a5ef0e87017d04b1e - #13513

cc @jvillafanez @nickvergessen @karlitschek Please review.

This only applies for stable7, because there the forwarding wasn't present.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Upgrade of 7.0.7 to 7.0.8:

before:
```
$ ./occ upgrade
Turned on maintenance mode
Checked database schema update
Updated database
Turned off maintenance mode
Update successful

```

after:
```
$ ./occ upgrade
Turned on maintenance mode
Repair info: removing duplicate entries from lucene_status
Checked database schema update
Updated database
Turned off maintenance mode
Update successful
```

**Comment by jvillafanez** [comment]
Validated :+1: 

I've changed the collation to latin1 of a couple of tables and the info shows fine
```
root@cdffc8a17f9a:/opt/owncloud# sudo -u www-data ./occ upgrade
Turned on maintenance mode
Repair info: Changed collation for filecache
Repair info: Changed collation for groups
Repair info: Changed collation for users
Repair info: lucene_status table does not exist -> nothing to do
Checked database schema update
Updated database
Turned off maintenance mode
Update successful
```
Back to utf8 after the upgrade, so all good.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by LukasReschke** [comment]
:bomb: :bomb: :bomb: This broke PHP 5.3 compatibility: https://github.com/owncloud/core/pull/18889 + https://github.com/owncloud/core/issues/18877 :bomb: :bomb: :bomb:

**Pull request merged**
