### PR TITLE
[tests-only] Tag recursive copy scenario with issue number

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
The new test scenario "Copying a folder into a sub-folder of itself" has similar recursive problem to the scenario "Moving a folder into a sub-folder of itself". There was a problem in reva-oCIS with this sending the server into an infinite recursion.

The problem has been fixed in reva edge branch, and in oCIS. But the inifinite recursion still happens in reva master branch. reva master branch CI has a filter for `~@issue-ocis-3023` - to avoid running the scenario(s) that have this problem.

This PR tags the new scenario so that it will not be run in reva master. 

The problem was noticed when bumping the core commit id in https://github.com/cs3org/reva/pull/3076#issuecomment-1186125240

2nd commit: bump sabre dependencies (just because patch bumps are available - not related to the skipping)
```
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 3 updates, 0 removals
  - Upgrading roave/security-advisories (dev-master 54cbc13 => dev-master 0144c12)
  - Upgrading sabre/http (5.1.5 => 5.1.6)
  - Upgrading sabre/vobject (4.4.2 => 4.4.3)
Writing lock file
```

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuthWebDav-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36335/51

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuthOcs-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36335/50

**Review by SagarGi — COMMENTED** [review]
lgtm :+1:

**Comment by phil-davis** [comment]
@SagarGi can you give a "green tick" approval please, so that I can merge this PR.

**Review by SagarGi — APPROVED** [review]

**Pull request merged**
