### PR TITLE
Soft fail when deleting and no entry found

### LINKED ISSUE #18770: Check if there are still a lot of useless deletes
Just checked a query log of a stable7 instance and there are 850 queries (out of 650k in 7 minutes) that looks like this:

```
DELETE FROM `oc_filecache` WHERE `fileid` = NULL
```

cc @icewind1991 @Xenopathic Please check if they are still done.

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Fixes #18770 

cc @MorrisJobke @PVince81 @icewind1991

### CODE REVIEW

**Comment by icewind1991** [comment]
use `empty` instead so we also check for null values/empty strign

**Comment by karlitschek** [comment]
:+1: looks good

**Comment by Xenopathic** [comment]
@icewind1991 `isset()` checks for `null`, and the value must be an integer (it can never be a string)

**Comment by icewind1991** [comment]
ok, :+1:

**Comment by Xenopathic** [comment]
Tests pass locally, I can still delete things -> merge

**Comment by nickvergessen** [comment]
Revert and find the root cause instead of fighting the symptom. Maybe we run 100 paarent propagations as well since we try to change something

**Pull request merged**
