### PR TITLE
[stable8.1] Fix parsing of sharetime as string

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #17489 to stable8.1

Approval: https://github.com/owncloud/core/pull/17489#issuecomment-125935048

@PVince81 @rullzer @nazar-pc Please test :)

### CODE REVIEW

**Comment by PVince81** [comment]
Code looks good :+1:

**Comment by rullzer** [comment]
Seems familiar :) :+1:

**Comment by karlitschek** [comment]
good :+1:

**Comment by nazar-pc** [comment]
Works fine :+1:

**Pull request merged**
