### PR TITLE
adjust the height of the sidebar preview image when resizing the browser

### PR DESCRIPTION
**Pull request by icewind1991**
Instead of setting the height once in js we have it set dynamically with some css magic for landscape images.

cc @jancborchardt @schiesbn

### CODE REVIEW

**Comment by schiesbn** [comment]
tested, works as expected :+1:

**Comment by jancborchardt** [comment]
Looks good! :+1: another review maybe @owncloud/designers just to be sure?

**Comment by MorrisJobke** [comment]
> Looks good! :+1: another review maybe @owncloud/designers just to be sure?

I couldn't find any difference while having a look at this. Everything behaves as expected before and after :see_no_evil:

**Comment by icewind1991** [comment]
> I couldn't find any difference while having a look at this.

Open the sidebar with a landscape image and resize the browser

**Comment by MorrisJobke** [comment]
Ah...resizing the width changes the size.

Looks good and works here :+1:

**Pull request merged**
