### PR TITLE
Delay check till scanner is used

### LINKED ISSUE #22973: Delay the check if the remote is an owncloud instance till we actually use the scanner
Ref https://github.com/owncloud/core/pull/22855, we should at this in a way so that other implementeros like Pydio still works.

This is especially relevant if one has mounted very slow S2S storages and no memory cache is configured.

Ref https://github.com/owncloud/core/issues/22987

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/core/issues/22973 and https://github.com/owncloud/core/issues/22987

Works when sharing with other ownClouds as well as when sharing with Pydio for me here.

cc @icewind1991 Objections? Thoughts?

### CODE REVIEW

**Comment by LukasReschke** [comment]
Seems to work for @atroxix (issue reporter) at https://github.com/owncloud/core/issues/22987#issuecomment-194222197

**Comment by LukasReschke** [comment]
Remark from https://github.com/owncloud/core/issues/22987#issuecomment-194236618:

> BTW, although I can login to web UI and see my files, OwnCloud client seems to be not able to finish its job, ie. it's constantly checking for changes, but doesn't do anything besides this.

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
:+1:

@karlitschek backport to 9.0?

**Comment by karlitschek** [comment]
makes sense. please backport :+1:

**Comment by LukasReschke** [comment]
stable9 at https://github.com/owncloud/core/pull/23259

**Pull request merged**
