### PR TITLE
Correct the parameters in Activity  getSpecialParameterList

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
PR #39430 implemented activity translations for rename and move actions. In that PR the parameters defined for the existing earlier switch cases in `getSpecialParameterList` were accidentally changed. This caused test fails in the activity app nightly CI like:
https://drone.owncloud.com/owncloud/activity/2253/16/11
```
runsh: Total unexpected failed scenarios throughout the test run:
webUIActivityDeleteRestore/delete.feature:150
webUIActivityDeleteRestore/restore.feature:252
webUIActivityDeleteRestore/restore.feature:270
```

```
  Scenario: Sharer and sharee check activity after sharer deletes shared file                                                 # /var/www/owncloud/testrunner/apps/activity/tests/acceptance/features/webUIActivityDeleteRestore/delete.feature:150
    Given these users have been created with default attributes and without skeleton files:                                   # FeatureContext::theseUsersHaveBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
      | username |
      | Brian    |
    And user "Alice" has shared file "textfile0.txt" with user "Brian"                                                        # FeatureContext::userHasSharedFileWithUserUsingTheSharingApi()
    And the user has reloaded the current page of the webUI                                                                   # WebUIGeneralContext::theUserReloadsTheCurrentPageOfTheWebUI()
    When the user deletes file "textfile0.txt" using the webUI                                                                # WebUIFilesContext::theUserDeletesFileUsingTheWebUI()
    And the user browses to the activity page                                                                                 # WebUIActivityContext::userHasBrowsedToTheActivityPage()
    Then the activity number 1 should contain message "You deleted textfile0.txt" in the activity page                        # WebUIActivityContext::theActivityNumberShouldContainMessageInTheActivityPage()
    And the activity number 2 should have a message saying that you have shared file "textfile0.txt" with user "Brian Murphy" # WebUIActivityContext::theActivityNumberShouldHaveAMessageSayingSharedFolderWithUser()
    When the user re-logs in as "Brian" using the webUI                                                                       # WebUILoginContext::theUserRelogsInUsingTheWebUI()
    And the user browses to the activity page                                                                                 # WebUIActivityContext::userHasBrowsedToTheActivityPage()
    Then the activity number 1 should contain message "Alice Hansen deleted textfile0.txt" in the activity page               # WebUIActivityContext::theActivityNumberShouldContainMessageInTheActivityPage()
      Failed asserting that 'Alice deleted textfile0.txt' contains "Alice Hansen deleted textfile0.txt".
```

The user display name is not being substituted in some messages.

This PR fixes the problem. For clarity, I have explicitly specified the exact parameters that are required by each activity type in the switch statement.

## How Has This Been Tested?
Local run of the failing activity app test scenarios is passing.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuth-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/47/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToRoot3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/77/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareManagementToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/63/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareOperationsToShares1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/69/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiComments-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/51/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioning-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/55/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioningGroups-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/57/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareOperationsToShares2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/70/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareOperationsToRoot1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/67/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiSharePublicLink1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/71/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToRoot2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/75/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiTags-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/81/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToShares1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/74/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioning-v1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/54/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareManagementBasicToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/65/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareManagementBasicToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/66/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingExt1-latest-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33485/156/1

**Comment by phil-davis** [comment]
@JammingBen please review. If this can be merged, then we will get a nightly CI run overnight that will confirm that the current tests pass (no more regressions)

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiSharePublicLink2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33488/72/1

**Review by JammingBen — APPROVED** [review]
Nice, 👍 for the more explicit approach.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/33488/72/13
```
The downloaded content was expected to be 'some data', but actually is ...
Sabre\DAV\Exception\ServiceUnavailable
Could not open file
HTTP status was 503
```
Strange unrelated test fail - restarting.

**Pull request merged**
