### PR TITLE
no need to store the form factor in the session - it's computation is ra...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
...ther cheep

Conflicts:
    lib/private/template.php

refs https://github.com/owncloud/core/pull/12140

@MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by MorrisJobke** [comment]
It's against stable7 - so I added the backport request

**Comment by MorrisJobke** [comment]
Everything still works and there are no errors in the logs :+1:

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Was already approved by @karlitschek  in https://github.com/owncloud/core/pull/12140#issuecomment-62737434

**Comment by LukasReschke** [comment]
:+1:

**Comment by karlitschek** [comment]
yes. still makes sense!  :-)

**Pull request merged**
