### PR TITLE
[stable9] Cache results of testRemoteUrl

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/owncloud/core/pull/22859

@karlitschek Please select milestone that you prefer.

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by karlitschek** [comment]
inthink 9.0.1 or is this a 9.0.0 showstopper? 
what do you think? @LukasReschke @icewind1991 @schiesbn @DeepDiver1975 ?

**Comment by karlitschek** [comment]
O.K. Let's do 9.0.0 because we have to redo packages anyways.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
