### PR TITLE
[stable9] Integration test encryption homedir

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/26844 to stable9.

~~I added an extra commit to temporarily enable the new tests on this PR, needs to be removed before merge !~~ it's gone

@DeepDiver1975 @SergioBertolinSG

### CODE REVIEW

**Comment by PVince81** [comment]
Cherry-picked the other backports from https://github.com/owncloud/core/pull/26993

**Comment by SergioBertolinSG** [comment]
Running tests locally:

- [ ] OC_TEST_ENCRYPTION_ENABLED=1 OC_TEST_ALT_HOME=1
- [ ] OC_TEST_ENCRYPTION_ENABLED=1
- [ ] OC_TEST_ALT_HOME=1

**Comment by PVince81** [comment]
Cherry-picked https://github.com/owncloud/core/pull/27015, hopefully all will pass on Jenkins at least.

**Review by SergioBertolinSG — APPROVED** [review]
After removing external storage test with encryption all tests pass.

**Comment by PVince81** [comment]
When will it end ?

```
18:29:25 --- Failed scenarios:
18:29:25 
18:29:25     /var/lib/jenkins/workspace/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA/build/integration/features/sharing-v1.feature:758
```

**Comment by PVince81** [comment]
Seems to be from this run. `OC_TEST_ENCRYPTION_ENABLED=1 ./run.sh`

**Comment by PVince81** [comment]
Here is the matching log from CI:
```
18:02:56   Scenario: sharing again an own file while belonging to a group                # /var/lib/jenkins/workspace/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA/build/integration/features/sharing-v1.feature:758
18:02:56     Given As an "admin"                                                         # FeatureContext::asAn()
18:02:57 [Tue Jan 24 18:02:57 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:02:57 [Tue Jan 24 18:02:57 2017] ::1:48715 [404]: /ocs/v2.php/cloud/users/user0
18:02:58 [Tue Jan 24 18:02:58 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:01 [Tue Jan 24 18:03:01 2017] ::1:48722 [200]: /ocs/v1.php/cloud/users
18:03:03 [Tue Jan 24 18:03:02 2017] ::1:48747 [200]: /ocs/v1.php/cloud/users/user0
18:03:03 [Tue Jan 24 18:03:03 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:03 [Tue Jan 24 18:03:03 2017] ::1:48760 [200]: /ocs/v2.php/cloud/users/user0
18:03:03     Given user "user0" exists                                                   # FeatureContext::assureUserExists()
18:03:04 [Tue Jan 24 18:03:04 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:04 [Tue Jan 24 18:03:04 2017] ::1:48768 [404]: /ocs/v2.php/cloud/groups/sharing-group
18:03:04 [Tue Jan 24 18:03:04 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:04 [Tue Jan 24 18:03:04 2017] ::1:48775 [200]: /ocs/v1.php/cloud/groups
18:03:05 [Tue Jan 24 18:03:05 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:05 [Tue Jan 24 18:03:05 2017] ::1:48781 [200]: /ocs/v2.php/cloud/groups/sharing-group
18:03:05     And group "sharing-group" exists                                            # FeatureContext::assureGroupExists()
18:03:05 [Tue Jan 24 18:03:05 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:05 [Tue Jan 24 18:03:05 2017] ::1:48787 [200]: /ocs/v2.php/cloud/users/user0/groups
18:03:06 [Tue Jan 24 18:03:05 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:06 [Tue Jan 24 18:03:05 2017] ::1:48791 [200]: /ocs/v1.php/cloud/users/user0/groups
18:03:06 [Tue Jan 24 18:03:06 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:06 [Tue Jan 24 18:03:06 2017] ::1:48795 [200]: /ocs/v2.php/cloud/users/user0/groups
18:03:06     And user "user0" belongs to group "sharing-group"                           # FeatureContext::assureUserBelongsToGroup()
18:03:07 [Tue Jan 24 18:03:06 2017] ::1:48802 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares?path=welcome.txt
18:03:07 [Tue Jan 24 18:03:07 2017] ::1:48812 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares
18:03:08 [Tue Jan 24 18:03:08 2017] ::1:48818 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares?path=welcome.txt
18:03:08     And file "welcome.txt" of user "user0" is shared with group "sharing-group" # FeatureContext::assureFileIsSharedWithGroup()
18:03:08 [Tue Jan 24 18:03:08 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:08 [Tue Jan 24 18:03:08 2017] ::1:48824 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares/83
18:03:08     And Deleting last share                                                     # FeatureContext::deletingLastShare()
18:03:09 [Tue Jan 24 18:03:09 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:09 [Tue Jan 24 18:03:09 2017] Exception: {"Exception":"OCA\\Encryption\\Exceptions\\PrivateKeyMissingException","Message":"Private Key missing for user: please try to log-out and log-in again","Code":0,"Trace":"#0 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/encryption\/lib\/keymanager.php(412): OCA\\Encryption\\Session->getPrivateKey()\n#1 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/encryption\/lib\/crypto\/encryption.php(384): OCA\\Encryption\\KeyManager->getFileKey('\/admin\/files\/\/w...', 'admin')\n#2 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/encryption\/update.php(181): OCA\\Encryption\\Crypto\\Encryption->update('\/admin\/files\/\/w...', 'admin', Array)\n#3 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/encryption\/update.php(90): OC\\Encryption\\Update->update('\/admin\/files\/\/w...')\n#4 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/encryption\/hookmanager.php(35): OC\\Encryption\\Update->postShared(Array)\n#5 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/hook.php(105): OC\\Encryption\\HookManager::postShared(Array)\n#6 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/share20\/manager.php(612): OC_Hook::emit('OCP\\\\Share', 'post_shared', Array)\n#7 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/files_sharing\/api\/share20ocs.php(396): OC\\Share20\\Manager->createShare(Object(OC\\Share20\\Share))\n#8 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/files_sharing\/api\/ocssharewrapper.php(44): OCA\\Files_Sharing\\API\\Share20OCS->createShare()\n#9 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/api.php(175): OCA\\Files_Sharing\\API\\OCSShareWrapper->createShare(Array)\n#10 [internal function]: OC_API::call(Array)\n#11 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/route\/router.php(276): call_user_func(Array, Array)\n#12 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/ocs\/v1.php(54): OC\\Route\\Router->match('\/ocs\/apps\/files...')\n#13 {main}","File":"\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/encryption\/lib\/session.php","Line":78}
18:03:09 [Tue Jan 24 18:03:09 2017] ::1:48828 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares
18:03:09     When sending "POST" to "/apps/files_sharing/api/v1/shares" with             # FeatureContext::sendingToWith()
18:03:09       | path      | welcome.txt   |
18:03:09       | shareWith | sharing-group |
18:03:09       | shareType | 1             |
18:03:09     Then the OCS status code should be "100"                                    # FeatureContext::theOCSStatusCodeShouldBe()
18:03:09       Failed asserting that SimpleXMLElement Object &0000000068a987f0000000000e9ffcb2 (
18:03:09           0 => '403'
18:03:09       ) matches expected '100'.
18:03:09     And the HTTP status code should be "200"                                    # FeatureContext::theHTTPStatusCodeShouldBe()
18:03:10 [Tue Jan 24 18:03:09 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:10 [Tue Jan 24 18:03:09 2017]  Backends provided no user object for user0
18:03:10 [Tue Jan 24 18:03:09 2017] ::1:48833 [200]: /ocs/v1.php/cloud/users/user0
18:03:10 [Tue Jan 24 18:03:10 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:10 [Tue Jan 24 18:03:10 2017] ::1:48838 [404]: /ocs/v2.php/cloud/users/user0
18:03:10 [Tue Jan 24 18:03:10 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:10 [Tue Jan 24 18:03:10 2017] ::1:48841 [200]: /ocs/v1.php/cloud/groups/sharing-group
18:03:11 [Tue Jan 24 18:03:11 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:11 [Tue Jan 24 18:03:11 2017] ::1:48846 [404]: /ocs/v2.php/cloud/groups/sharing-group
18:03:11 [Tue Jan 24 18:03:11 2017] Login failed: 'user0' (Remote IP: '::1')
18:03:11 [Tue Jan 24 18:03:11 2017] ::1:48847 [401]: /remote.php/webdav/myFileToComment.txt
18:03:11 [Tue Jan 24 18:03:11 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:11 [Tue Jan 24 18:03:11 2017] ::1:48848 [404]: /remote.php/dav/addressbooks/users/admin/MyAddressbook
18:03:12 [Tue Jan 24 18:03:11 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:12 [Tue Jan 24 18:03:11 2017] ::1:48852 [404]: /remote.php/dav/calendars/admin/MyCalendar
18:03:12 [Tue Jan 24 18:03:12 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
18:03:12 [Tue Jan 24 18:03:12 2017] ::1:48860 [207]: /remote.php/dav/systemtags/
18:03:12 [Tue Jan 24 18:03:12 2017] Login failed: 'user0' (Remote IP: '::1')
18:03:12 [Tue Jan 24 18:03:12 2017] ::1:48868 [401]: /remote.php/webdav/myFileToTag.txt
18:03:12 
```

I wasn't able to reproduce this locally. Maybe this requires running all test suites one after the other to create side effects ? 😿

**Comment by SergioBertolinSG** [comment]
I cannot reproduce it locally as well. But when I run this test I am not seeing this messages:

Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature

**Comment by SergioBertolinSG** [comment]
In the logs of https://github.com/owncloud/core/pull/26996#issuecomment-274887010 there is also an exception:
```
{"Exception":"OCA\\Encryption\\Exceptions\\PrivateKeyMissingException","Message":"Private Key missing for user: please try to log-out and log-in again","Code":0,"Trace":"#0 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/encryption\/lib\/keymanager.php(412): OCA\\Encryption\\Session->getPrivateKey()\n#1 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/encryption\/lib\/crypto\/encryption.php(384): OCA\\Encryption\\KeyManager->getFileKey('\/admin\/files\/\/w...', 'admin')\n#2 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/encryption\/update.php(181): OCA\\Encryption\\Crypto\\Encryption->update('\/admin\/files\/\/w...', 'admin', Array)\n#3 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/encryption\/update.php(90): OC\\Encryption\\Update->update('\/admin\/files\/\/w...')\n#4 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/encryption\/hookmanager.php(35): OC\\Encryption\\Update->postShared(Array)\n#5 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/hook.php(105): OC\\Encryption\\HookManager::postShared(Array)\n#6 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/share20\/manager.php(612): OC_Hook::emit('OCP\\\\Share', 'post_shared', Array)\n#7 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/files_sharing\/api\/share20ocs.php(396): OC\\Share20\\Manager->createShare(Object(OC\\Share20\\Share))\n#8 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/files_sharing\/api\/ocssharewrapper.php(44): OCA\\Files_Sharing\\API\\Share20OCS->createShare()\n#9 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/api.php(175): OCA\\Files_Sharing\\API\\OCSShareWrapper->createShare(Array)\n#10 [internal function]: OC_API::call(Array)\n#11 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/lib\/private\/route\/router.php(276): call_user_func(Array, Array)\n#12 \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/ocs\/v1.php(54): OC\\Route\\Router->match('\/ocs\/apps\/files...')\n#13 {main}","File":"\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-26996-G67YK4J3OUDLGAY5S5VADD3WQLLMECZUUAOFWVSU5R7BBE4PMALA\/apps\/encryption\/lib\/session.php","Line":78}
```

**Comment by PVince81** [comment]
All tests passed for me with encryption locally.

**Comment by PVince81** [comment]
Rebased... let's hope...

**Comment by PVince81** [comment]
When running the tests locally, I never see that "Bad Signature" message which appears all the time on Jenkins:
```
21:39:55 [Fri Feb  3 21:39:55 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
```

**Comment by PVince81** [comment]
Ok, interesting, I'm able to get the "Bad signature" messages when I run the integration tests with SQLite.

So far I've always run them with Mariadb.

**Comment by PVince81** [comment]
Steps to reproduce the encryption issue:

1. `rm -Rf config/config.php`
1. `./occ maintenance:install --admin-pass=admin`
1. `cd build/integration`
1. `OC_TEST_ENCRYPTION_ENABLED=1 ./run.sh features/sharing-v1.feature:758`

This sets up ownCloud with SQLite and this somehow triggers this error...
```
[Mon Feb  6 16:48:58 2017] 127.0.0.1:41834 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares?path=welcome.txt
    And file "welcome.txt" of user "user0" is shared with group "sharing-group" # FeatureContext::assureFileIsSharedWithGroup()
[Mon Feb  6 16:48:59 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
[Mon Feb  6 16:48:59 2017] 127.0.0.1:41856 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares/1
    And Deleting last share                                                     # FeatureContext::deletingLastShare()
[Mon Feb  6 16:48:59 2017] Could not decrypt the private key from user "admin"" during login. Assume password change on the user back-end. Error message: Bad Signature
[Mon Feb  6 16:48:59 2017] Exception: {"Exception":"OCA\\Encryption\\Exceptions\\PrivateKeyMissingException","Message":"Private Key missing for user: please try to log-out and log-in again","Code":0,"Trace":"#0 \/srv\/www\/htdocs\/owncloud\/apps\/encryption\/lib\/keymanager.php(412): OCA\\Encryption\\Session->getPrivateKey()\n#1 \/srv\/www\/htdocs\/owncloud\/apps\/encryption\/lib\/crypto\/encryption.php(384): OCA\\Encryption\\KeyManager->getFileKey('\/admin\/files\/\/w...', 'admin')\n#2 \/srv\/www\/htdocs\/owncloud\/lib\/private\/encryption\/update.php(181): OCA\\Encryption\\Crypto\\Encryption->update('\/admin\/files\/\/w...', 'admin', Array)\n#3 \/srv\/www\/htdocs\/owncloud\/lib\/private\/encryption\/update.php(90): OC\\Encryption\\Update->update('\/admin\/files\/\/w...')\n#4 \/srv\/www\/htdocs\/owncloud\/lib\/private\/encryption\/hookmanager.php(35): OC\\Encryption\\Update->postShared(Array)\n#5 \/srv\/www\/htdocs\/owncloud\/lib\/private\/hook.php(105): OC\\Encryption\\HookManager::postShared(Array)\n#6 \/srv\/www\/htdocs\/owncloud\/lib\/private\/share20\/manager.php(612): OC_Hook::emit('OCP\\\\Share', 'post_shared', Array)\n#7 \/srv\/www\/htdocs\/owncloud\/apps\/files_sharing\/api\/share20ocs.php(396): OC\\Share20\\Manager->createShare(Object(OC\\Share20\\Share))\n#8 \/srv\/www\/htdocs\/owncloud\/apps\/files_sharing\/api\/ocssharewrapper.php(44): OCA\\Files_Sharing\\API\\Share20OCS->createShare()\n#9 \/srv\/www\/htdocs\/owncloud\/lib\/private\/api.php(175): OCA\\Files_Sharing\\API\\OCSShareWrapper->createShare(Array)\n#10 [internal function]: OC_API::call(Array)\n#11 \/srv\/www\/htdocs\/owncloud\/lib\/private\/route\/router.php(276): call_user_func(Array, Array)\n#12 \/srv\/www\/htdocs\/owncloud\/ocs\/v1.php(54): OC\\Route\\Router->match('\/ocs\/apps\/files...')\n#13 {main}","File":"\/srv\/www\/htdocs\/owncloud\/apps\/encryption\/lib\/session.php","Line":78}
[Mon Feb  6 16:48:59 2017] 127.0.0.1:41874 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares
    When sending "POST" to "/apps/files_sharing/api/v1/shares" with             # FeatureContext::sendingToWith()
      | path      | welcome.txt   |
      | shareWith | sharing-group |                                                                                                                                         
      | shareType | 1             |                                                                                                                                         
    Then the OCS status code should be "100"                                    # FeatureContext::theOCSStatusCodeShouldBe()
      Failed asserting that SimpleXMLElement Object &000000007a222979000000007ad72f73 (
          0 => '403'                                                                                                                                                        
      ) matches expected '100'.                                                                                                                                             
    And the HTTP status code should be "200"                                    # FeatureContext::theHTTPStatusCodeShouldBe()
```

**Comment by PVince81** [comment]
Ok got it... My reset script usually deletes all contents of the "data" directory.

However if you reset OC by just deleting the config but keeping the "data" directory, then the old private key of admin from a previous setup still exists, and that key is invalid.

Now I wonder why it worked on stable9.1 and master, I'll check if the cleanup there is deeper.

**Comment by PVince81** [comment]
- rebased
- added cleanup of data folder between test runs
- removed external storage workaround because the above might just fix it (we can re-add it if really needed)

**Comment by PVince81** [comment]
- [ ] TODO: forward port the cleanup commit, just in case

**Comment by PVince81** [comment]
@SergioBertolinSG tests finally passed now! I'll remove the TEMP TEST commit now.

**Comment by PVince81** [comment]
> 08:07:16  -> ORA-12514: TNS:listener does not currently know of service requested in connect descriptor Check environment: ORACLE_HOME=/usr/lib/oracle/12.1/client64 ORACLE_SID= LD_LIBRARY_PATH= NLS_LANG= tnsnames.ora is not readable

Bad luck is in the air today...

**Comment by PVince81** [comment]
Anyway, this PR doesn't affect regular unit tests.

👍 for @SergioBertolinSG's commits.

Merge ?

**Comment by SergioBertolinSG** [comment]
Agreed.

**Pull request merged**
