### PR TITLE
Fixes Issue #27182

### PR DESCRIPTION
**Pull request by noveens**
## Description

The overlapping progress-bar and app-details have now been fixed

## Related Issue

https://github.com/owncloud/core/issues/27182

## How Has This Been Tested?

Tested at various resolutions.

## Screenshots (if appropriate):
desktop-animation

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by noveens** [comment]
@tomneedham ,
can you review?

**Comment by noveens** [comment]
@PVince81 ,
Is this solution okay?

**Comment by PVince81** [comment]
Sounds like a hack... @felixheidecke suggestions ?

**Comment by felixheidecke** [comment]
The spinner should (and does) display while the data is loading and is remove once the container is populated. Thus, we don't need to shove it to the side. It could be displayed nicer, true … but I'd rather suggest placing center / center where it belongs for now.
In this case

```
#apps-list {
	position: relative;
	height: 100%;
	min-height: 90vh;
}
```

**Comment by noveens** [comment]
@felixheidecke ,
suppose there are around 5 apps loaded,
still won't your solution overlap with some of the apps?

**Comment by felixheidecke** [comment]
@noveens … It does, and I believe it's the loaders purpose to overlay ;-)
This should be solved differently. Limiting the app-description-containers width by adding a margin is indeed hacky and should be left as it is.

Maybe expanding the overlaying pseudo to overlay it all and fading it out, exposing the apps underneath would be far nicer. Not only in code but also visually.

**Comment by noveens** [comment]
@felixheidecke ,
Then, I guess the solution of placing the progress bar at the centre of the screen would be the best one, I'll update it.

**Comment by noveens** [comment]
@felixheidecke ,
Another doubt, when will the progress bar disappear?

**Comment by felixheidecke** [comment]
It disappears once it's populated.
https://github.com/owncloud/core/blob/master/settings/js/admin-apps.js#L123

**Comment by noveens** [comment]
@felixheidecke ,
Apparently it never seems to populate at my machine.
Any ideas?

**Comment by noveens** [comment]
@felixheidecke @PVince81 ,
Please review this.

**Comment by tomneedham** [comment]
Please can you review https://github.com/owncloud/core/pull/27236 first @noveens as I think this solves a lot of issues with the admin page.

**Comment by PVince81** [comment]
Is this PR still needed ?

**Comment by noveens** [comment]
@PVince81 ,
I guess so.

**Review by tomneedham — COMMENTED** [review]
In my opinion this PR is not needed. If there is an issue with the loading circle not disappearing then this should be resolved.

**Comment by noveens** [comment]
@tomneedham ,
apparently before installing the gallery app, the circle never seemed to disappear.

Maybe you can test with a fresh clone of owncloud/core without any external apps installed?

**Comment by tomneedham** [comment]
Let's close this for now. If you can reproduce the overlapping issue, then maybe update this issue (https://github.com/owncloud/core/issues/27182) with some additional details and we can come at it from the point of view of the icon not disappearing correctly

**Pull request closed without merging**
