### PR TITLE
[tests-only] [full-ci] Test with pgSQL 15

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
15.3 is the latest pgSQL 15 docker image.

https://www.postgresql.org/docs/release/15.3

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/38867/22/5
```
php occ maintenance:install -vvv --database=pgsql --database-name=owncloud --database-table-prefix=oc_ --admin-user=admin --admin-pass=admin --data-dir=/drone/src/data --database-host=postgres --database-user=owncloud --database-pass=owncloud
Error while trying to create admin user: An exception occurred while executing 'CREATE TABLE "oc_appconfig" ("appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, "configvalue" TEXT DEFAULT NULL, PRIMARY KEY("appid", "configkey"))':
SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for schema public
LINE 1: CREATE TABLE "oc_appconfig" ("appid" VARCHAR(32) DEFAULT '' ...
```

"something happens" when trying to set up the database. Needs investigation.

**Comment by pako81** [comment]
Reproducible. This is because in version 15, only the database owner can create objects in the public schema: https://www.cybertec-postgresql.com/en/error-permission-denied-schema-public/

After running:

```
\c owncloud postgres
GRANT ALL ON SCHEMA public TO owncloud;
```

I was able to successfully install 10.12.2 with PostgreSQL 15.3 on Ubuntu 20.04. I guess this just need docs update?

**Comment by phil-davis** [comment]
> I guess this just need docs update?

yes, for users. I will also see if I can adjust the CI so that it also works - that will let the test suites run and confirm that the real functionality works.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/38901/22/5
```
wait-for-it -t 600 postgres:5432
waiting for database to be ready
services are ready!
+ DB=pgsql
+ PGPASSWORD=owncloud
+ psql -h postgres -U owncloud -c 'GRANT ALL ON SCHEMA public TO owncloud;'
GRANT
+ declare -x PRIMARY_OBJECTSTORE
+ [[ ! -z '' ]]
+ install_cmd='maintenance:install -vvv       --database=pgsql       --database-name=owncloud       --database-table-prefix=oc_       --admin-user=admin       --admin-pass=admin       --data-dir=/drone/src/data '
+ [[ postgres != \s\q\l\i\t\e ]]
+ [[ postgres != \o\r\a\c\l\e ]]
+ install_cmd+=' --database-host=postgres                      --database-user=owncloud                      --database-pass=owncloud'
+ php occ maintenance:install -vvv --database=pgsql --database-name=owncloud --database-table-prefix=oc_ --admin-user=admin --admin-pass=admin --data-dir=/drone/src/data --database-host=postgres --database-user=owncloud --database-pass=owncloud
Error while trying to create admin user: An exception occurred while executing 'CREATE TABLE "oc_appconfig" ("appid" VARCHAR(32) DEFAULT '' NOT NULL, "configkey" VARCHAR(64) DEFAULT '' NOT NULL, "configvalue" TEXT DEFAULT NULL, PRIMARY KEY("appid", "configkey"))':
SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for schema public
LINE 1: CREATE TABLE "oc_appconfig" ("appid" VARCHAR(32) DEFAULT '' ...
```

Hmmm - something more is needed to give the oC10 installer full access to create tables.

**Comment by pako81** [comment]
> Hmmm - something more is needed to give the oC10 installer full access to create tables.

`PGPASSWORD="owncloud" psql -h postgres -U owncloud -c "GRANT ALL ON SCHEMA public TO owncloud;"`

 I think the GRANT has to be done as an admin user (`postgres`) and not as user `owncloud`

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/38902/22/5
```
PGPASSWORD=owncloud
+ psql -h postgres -U owncloud -c 'GRANT ALL ON SCHEMA public TO owncloud;'
GRANT
+ PGPASSWORD=owncloud
+ psql -h postgres -U owncloud -c '\du'
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 owncloud  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

The postgres docker image is started with POSTGRES_USER and POSTGRES_PASSWORD set to "owncloud".

The output above shows that there is a Superuser called "owncloud" (and there is not a user/role "postgres").

I am thinking what can be the last piece of magic needed to get this working.

**Comment by pako81** [comment]
Not sure how the user `owncloud` is being created but normally when using the `CREATE USER owncloud WITH PASSWORD 'owncloud'` command the created role has empty attributes and the problem is not reproducible (the installation goes through):

```
postgres=# \du owncloud
           List of roles
 Role name | Attributes | Member of 
-----------+------------+-----------
 owncloud  |            | {}
```

While the problem is reproducible for me when using the `CREATE ROLE` command:

```
CREATE ROLE owncloud WITH LOGIN SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS PASSWORD 'owncloud'
```

In this case what makes the difference is to remove the `CREATEROLE` attribute for the user:

```
postgres=# \du owncloud9
                             List of roles
 Role name |                  Attributes                   | Member of 
-----------+-----------------------------------------------+-----------
 owncloud9 | Superuser, Create DB, Replication, Bypass RLS | {}
```

In this case the installation goes through. So maybe we can try to remove that attribute before running the install (`ALTER ROLE owncloud WITH NOCREATEROLE;`).

**Comment by phil-davis** [comment]
> This way the installation succeeds (don't ask me why). So maybe we can test by removing that attribute before running the install (ALTER ROLE owncloud WITH NOCREATEROLE).

That is magic! It worked.

**Pull request closed without merging**
