### PR TITLE
Add error logging to federation handshake

### PR DESCRIPTION
**Pull request by icewind1991**
Makes it possible to figure out why the handshake is failing

cc @DeepDiver1975 @schiesbn

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
````
09:49:13 .....................PHP Fatal error:  Uncaught TypeError: Argument 6 passed to OCA\Federation\API\OCSAuthAPI::__construct() must implement interface OCP\ILogger, none given in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/federation/api/ocsauthapi.php:71
09:49:13 Stack trace:
09:49:13 #0 [internal function]: OCA\Federation\API\OCSAuthAPI->__construct(Object(Mock_IRequest_e5ed851b), Object(Mock_ISecureRandom_fab9c9a6), Object(Mock_JobList_a7573449), Object(Mock_TrustedServers_1fdc683c), Object(Mock_DbHandler_4537403e))
09:49:13 #1 phar:///usr/local/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php(257): ReflectionClass->newInstanceArgs(Array)
09:49:13 #2 phar:///usr/local/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php(225): PHPUnit_Framework_MockObject_Generator->getObject('class Mock_OCSA...', 'Mock_OCSAuthAPI...', 'OCA\\Federation\\...', true, true, Array, false, NULL)
09:49:13 #3 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(1259): PHPUnit_Framework_MockObject_Generator->getMock('OCA\\Federation\\. in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/federation/api/ocsauthapi.php on line 71

**Comment by icewind1991** [comment]
Fixed

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Code logs good and federation still works :+1:

**Pull request merged**
