### PR TITLE
Properly throw exception in OC_Mount_Config::getBackendStatus

### PR DESCRIPTION
**Pull request by PVince81**
This issue is only on master.

Please review @Xenopathic @icewind1991 @nickvergessen

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/20280 where the exception is supposed to be ignored until we can click "Grant access".

**Comment by nickvergessen** [comment]
@Xenopathic please start using an IDE or learn to configure your VIM correctly:
https://github.com/owncloud/core/commit/9a4d37f626dca4663ea7d25f78f7c1f174306ab5#diff-14b8730b6a49a5833c7439f509cbcc76

**Comment by nickvergessen** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
