### PR TITLE
Rename experimental to transactional file locking

### LINKED ISSUE #17120: Change the name of "experimental file locking" to "transactional locking"
I can't find this issue and I know we filed it and discussed it.

Let's change the name of "experimental file locking" to "transactional locking"

At a minimum, this will have an impact on the admin server status information and config.php. 

@MTRichards @icewind1991 @PVince81 @cmonteroluque

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/17120

Note that I still mentioned "BETA" in the switches' doc.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by oparoz** [comment]
:dancers:

**Comment by davitol** [comment]
:+1:

**Pull request merged**
