### PR TITLE
Sync version 10 03

### PR DESCRIPTION
**Pull request by phil-davis**
Forward port version.php changes from stable10 to master.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
3 commits ? I think one would have been enough

**Comment by PVince81** [comment]
anyway, merge once done

**Comment by phil-davis** [comment]
I thought to just cherry-pick all the different history, in case there was some odd diff. But in the end it was just the same 2 lines changed in each commit.

**Pull request merged**
