### PR TITLE
To be safe don't unload until end

### LINKED ISSUE #21485: Wrong image rotation
Hi all,

I want to refer to this issue: https://github.com/interfasys/galleryplus/issues/29
I have the same problem and it seems there is no open issue yet.

Pictures are wrong rotated in gallery, as well as thumbnails and file explorer in owncloud.
If I download the pictures it´s all fine and my windows app shows correctly.

**Operating system**: Ubuntu Server 14.04

**Web server:** nginx current version

**Database:** MySQL

**PHP version:** Current version, exif enabled

**ownCloud version:** (see ownCloud admin page): 8.2.1

**Updated from an older ownCloud or fresh install:** fresh installation

### PR DESCRIPTION
**Pull request by josh4trunks**
Fixes https://github.com/owncloud/core/issues/21485
Please test and backport to 9.0.X

### CODE REVIEW

**Comment by josh4trunks** [comment]
@oparoz @DeepDiver1975 @snoopyf @Rayn0r

**Comment by oparoz** [comment]
@josh4trunks - I'm sorry, I should have seen this earlier, but this won't work properly :| 
Are you OK with PHP and git?

**Comment by josh4trunks** [comment]
@oparoz
what won't work?

I'm not that great at PHP or git, just know enough to get by, lol.

**Comment by oparoz** [comment]
>what won't work?

@josh4trunks - Because the script returns just after the image is deemed valid, the temp file is never removed, so the better way to do this is to collect the return value and to return after the temp file has been removed.

**Comment by josh4trunks** [comment]
ahh, good point. OK so we either gotta have it how I originally proposed or change things a bit.
I was just trying to unlink after the scaletofit like you mentioned, but u don't know if this is actually needed.

feel free to take this over, or I can make the change in a few hours when I'm free.

**Comment by josh4trunks** [comment]
@oparoz ok fixed.
@snoopyf @Rayn0r I know you already tested this, but if you can just confirm it works on this PR that would be great.

**Comment by oparoz** [comment]
@josh4trunks Since `$image->fixOrientation();` fails when the file has been deleted, what makes you think that `$image->scaleDownToFit($maxX, $maxY);` will still work as expected?

It may very well be the case, but I have no idea why `fixOrientation` doesn't work even though it's using a new resource and not the file located in /tmp

**Comment by josh4trunks** [comment]
@oparoz I don't know for a fact if `scalDownToFit` needs an actual file. If you have an image I can test this with I gladly would do so with/without encryption.

Here's a discussion on why PHP's `exif_read_data` needs an actual file path.
http://grokbase.com/t/php/php-bugs/1372p2wp45/php-bug-req-65187-new-exif-read-data-add-support-for-stream-resource
Do we have a bug report for `scaleDownToFit` not working with encryption? If not, I don't see a reason to not commit this knowing it fixes https://github.com/owncloud/core/issues/21485.

**Comment by josh4trunks** [comment]
@MorrisJobke @oparoz 
Is there anything further I should do to get this looked at/work on?

I just don't want to keep to having to patch my owncloud code after each update so that wrongly rotated thumbnails aren't created and I have to delete and regenerate thousands of thumbnails again.
Thanks

**Comment by MorrisJobke** [comment]
> I just don't want to keep to having to patch my owncloud code after each update so that wrongly rotated thumbnails aren't created and I have to delete and regenerate thousands of thumbnails again.

@nickvergessen @LukasReschke @blizzz @rullzer Maybe one of you could check out this PR :)

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by rullzer** [comment]
Looks good. Let me prepare a CI PR so we have a little more certainlty it won't break...

**Comment by rullzer** [comment]
Squashed and rebased PR in #23907

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by josh4trunks** [comment]
thanks guys =]

**Comment by MorrisJobke** [comment]
> thanks guys =]

Could you prepare the backport to stable9?

**Comment by josh4trunks** [comment]
sure, I believe that means creating a new PR off that branch. I'll get that done today.

**Comment by josh4trunks** [comment]
Backport request is here https://github.com/owncloud/core/pull/23924

**Pull request merged**
