### PR TITLE
New animated loader: full css

### LINKED ISSUE #19091: Switch to simpler looking loading spinner
We should switch to a simpler spinner for the next version. The current one is very complex, has many parts, and the GIF is not optimized for HiDPI.

Similar to this maybe (of course better quality and scalable etc.):

Or the one of the new HTML5 player on https://twitch.tv

Ref https://github.com/owncloud/gallery/issues/336 for previous discussion on the spinner. cc @owncloud/designers @oparoz

### PR DESCRIPTION
**Pull request by skjnldsv**
New spinner. This time we're going full css. This is the best solution.
See discussion in ref issue.

We have a gif fall-back for css replaced elements (inputs, img...). This should easily do the trick, and is fully compatible with all browsers (including IE \o/)
I also added a small black loading icon: icon-loading-small-dark

ref and fix #19091 
@oparoz @Henni @jancborchardt @PVince81

### CODE REVIEW

**Comment by skjnldsv** [comment]
Seems to have an issue with some of the gifs. I'm checking it.

**Comment by skjnldsv** [comment]
Ok, fixed now! :)
Gifs are now optimised and a bit more visible. Obviously, the render isn't as good as the full css, but this is a fallback after all ;)

**Comment by MorrisJobke** [comment]
Ready for reviews?

**Comment by skjnldsv** [comment]
@MorrisJobke 
Yes! :)

**Comment by ChristophWurst** [comment]
When opening a text file with the text editor, the loading spinner stays forever. Does not happen with the old spinner on master.
Apart from that it looks very nice! Tested with FF on Linux

**Comment by skjnldsv** [comment]
See owncloud/files_texteditor#173 for the text loading bug.
Not related to this commit:

```
<skjnldsv> ok I think I see why
<skjnldsv> the class stays
<skjnldsv> but the textarea just go over it
<skjnldsv> so the loading is not visible
<skjnldsv> but now, because we're not using a background but a separated css element (::after) its stays on top
<ChristophWurst> ah, so it's just a coincidence it worked with the old one? :D
<skjnldsv> exactly ^^
```

**Comment by ChristophWurst** [comment]
:+1: then, no other problems detected

**Comment by MorrisJobke** [comment]
Tested, looks really nice and works also in IE11 👍 😃

**Comment by MorrisJobke** [comment]
@DeepDiver1975 JSUnit tests pass and the other stuff is CSS only. Could you merge this?

**Comment by skjnldsv** [comment]
Finally! \o/

**Comment by jancborchardt** [comment]
Nice dude, great work! :)

**Comment by skjnldsv** [comment]
Thanks @jancborchardt !
Took a while to figure out the best.

**Comment by oparoz** [comment]
Well done @skjnldsv - This was merged rather quickly, so let's hope enough people will be able to test it before launch to offer feedback. I still think the ring is a bit thin which makes it too discreet in some situations. We'll see :)

**Comment by skjnldsv** [comment]
We already review the colors previously with jan!
I think this is alright (except the gif), we'll see if something came up :)

**Comment by jancborchardt** [comment]
Yeah, now we have enough time to see it in action so it's good we finally merged it! :)

**Pull request merged**
