### PR TITLE
prevent users from deleting their own session token

### LINKED ISSUE #24911: Users can log out by killing the session token (unintentionally)
### Steps to reproduce
1. Start owncloud session from several browser devices
2. Go to the personal page
3. Delete your own session
### Expected behaviour

The users should not be able to delete their current sessions
### Actual behaviour

The users can log out by killing the session token
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.1.0.5","versionstring":"9.1.0 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**browser**

 Chrome

deletesessions

@ChristophWurst

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes #24911

### CODE REVIEW

**Comment by georgehrke** [comment]
@davitol

**Comment by davitol** [comment]
:-1: Using Firefox 47.0 for OSX I still being able to delete my own session, but using chrome as browser it works fine.
Screenshots of the same situation:

Firefox:

screen shot 2016-06-28 at 15 48 50

Chrome

screen shot 2016-06-28 at 15 48 44

**Comment by ChristophWurst** [comment]
tested it again with FF an Chromium. Works for me with both browsers

**Comment by ChristophWurst** [comment]
Please post the reponse of the '/settings/person/authtokens' call on FF. It should like like this:
bildschirmfoto von 2016-06-28 16-15-32
Note that one of the entries *should* have ``canDelete`` set to ``false``.

**Comment by davitol** [comment]
screen shot 2016-06-28 at 16 24 20
Now I see it works and the trashbin icon is not enabled... I'll try to reproduce it again, and if i cannot, i'll thumb up when finishing testing

**Comment by davitol** [comment]
:+1: Seems to WFM

**Comment by ChristophWurst** [comment]
@PVince81 @DeepDiver1975 @georgehrke second review?

**Comment by PVince81** [comment]
Tested, works :+1:

**Pull request merged**
