### PR TITLE
[AppManager] Adding methods to install and upgrade an app - as well a…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Adds some necessary public api for apps handling

## Motivation and Context
https://github.com/owncloud/market/pull/2

## How Has This Been Tested?
Running market occ commands

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

…s getting app info

### CODE REVIEW

**Comment by PVince81** [comment]
The code looks good but I'd prefer to have the new apps page merged before. Because with this PR alone app management becomes impossible on master and will annoy devs who can't quickly enable apps (yeah I know, CLI...)

**Comment by PVince81** [comment]
Will the new app page from https://github.com/owncloud/core/pull/26449 break after we merge this PR ? Will that one need to be adjusted to the new API ?

**Comment by PVince81** [comment]
If yes I suggest to split this PR into two PRs: one PR that adds the new APIs and another one that kills the old ones.

**Comment by DeepDiver1975** [comment]
- Kill the app mgmt is here: https://github.com/owncloud/core/pull/26763

**Comment by DeepDiver1975** [comment]
> If yes I suggest to split this PR into two PRs: one PR that adds the new APIs and another one that kills the old ones.

- this pr now only holds the new interface methods
- Kill the app mgmt is here: https://github.com/owncloud/core/pull/26763

**Comment by PVince81** [comment]
Looks good, thanks 👍

**Pull request merged**
