### PR TITLE
Inttest add objectstore option

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
This PR is required for https://github.com/owncloud/objectstore/pull/52

### CODE REVIEW

**Comment by PVince81** [comment]
I think this is the wrong approach.
We can't add every storage app out there into our run.sh script.

A) The way I think it should be done:
- the objectstore app provides its own behat tests runner
- the runner script in the app also inherits / extends the tests provided by core and runs them with the app enabled and preconfigured

This is similar to custom groups and other apps which need to be able to reuse tests / test steps from core.

B) Or a better alternative:

- don't change core this way
- make it so that core tests can be run against any independent docker instance of the server (this is what we discussed in Nbg)
- let @tboerger setup a test run where two docker containers are involved:
    - container1: behat tests from git/core
    - container2: ownCloud server preconfigured with object store

@DeepDiver1975 or did I misunderstood and we decided using a different approach ?

**Comment by PVince81** [comment]
basically https://github.com/owncloud/QA/issues/329

**Comment by SergioBertolinSG** [comment]
This is just an option needed to enable the app. The tests will run in the app repository.

My goal is to run the same tests we have in core, but with objectstore. So the best approach is to call the same code it is in core, because it can (will) change.

In the core's jenkinsfile there won't be a new run using objectstore.

**Comment by PVince81** [comment]
@SergioBertolinSG I still don't like having code in run.sh that is not related to the core repo.

Could you try pre-enabling that app from inside the objectstore repo ? You'll certainly have a runner script there too, so enable it there. Or alternatively enable it in your Jenkinsfile/Travis file specific to the app.

**Comment by PVince81** [comment]
in fact, your repo travis file should already contain file to preinstall ownCloud (before_install.sh), so just add `occ app:enable objectstore` after that.

**Comment by SergioBertolinSG** [comment]
Ok then, @PVince81 .

**Pull request closed without merging**
