### PR TITLE
Fix mimetype filter in getDirectoryContent

### LINKED ISSUE #20899: \OCA\Files\Helper::getFiles() $filter does not work properly in master
This seems to be regression caused sometime during last ~3 weeks.

I have an app that looks up list of files (from external mounted OwnCloud instance) and prints them out, and is using following snippet:

```
$dir = '/External/Media';
$filter = 'httpd/unix-directory';
foreach(\OCA\Files\Helper::getFiles($dir, 'name', false, $filter) as $d) {
  // do something...
}
```
Now, after pulling latest master (8d218bf3ef842d76c2b97a175b28e13054497952), I'm not getting any directories after this call, but I managed to get things working with following workaround:

```
$dir = '/External/Media';
$filter = 'httpd/unix-directory';
foreach(\OCA\Files\Helper::getFiles($dir, 'name', false, Null) as $d) {
  if ($d->getMimeType() !== $filter)
    continue;
  // do something...
}
```

### PR DESCRIPTION
**Pull request by icewind1991**
Added tests to keep it working in the future

Fixes https://github.com/owncloud/core/issues/20899

cc @PVince81 @Xenopathic

### CODE REVIEW

**Comment by LukasReschke** [comment]
```
10:50:36 There were 2 failures:
10:50:36 
10:50:36 1) Test\Files\View::testMountPointMove
10:50:36 Can rename mount point
10:50:36 Failed asserting that false is true.
10:50:36 
10:50:36 /ssd/jenkins/workspace/server-master-linux-php7-ci@2/database/sqlite/label/SLAVE/tests/lib/files/view.php:1575
10:50:36 
10:50:36 2) Test\Files\View::testLockMoveMountPoint
10:50:36 Source path locked properly during operation
10:50:36 Failed asserting that null matches expected 2.
10:50:36 
10:50:36 /ssd/jenkins/workspace/server-master-linux-php7-ci@2/database/sqlite/label/SLAVE/tests/lib/files/view.php:2265
10:50:36 
```

**Comment by Xenopathic** [comment]
Wtf how did that code even work originally?! :+1: for sure

**Comment by icewind1991** [comment]
all fixed

**Comment by PVince81** [comment]
:+1: (failing OCS test unrelated)

**Pull request merged**
