### PR TITLE
[stable10] acceptance test fixes

### PR DESCRIPTION
**Pull request by individual-it**
combined backports:
- backport of #32378
- backport tests of #30920
- backport of #32433

### CODE REVIEW

**Comment by individual-it** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Review by phil-davis — COMMENTED** [review]
What happened to code changes from #30920 like:
https://github.com/owncloud/core/pull/30920/files#diff-c493b80ad1a9bcfa6b69637097972371R995
and
https://github.com/owncloud/core/pull/30920/files#diff-5af29c9f0fdb4338457f3bb7024dc991
?

**Comment by phil-davis** [comment]
i.e. why do we want just the tests backported, and not the code?

**Comment by phil-davis** [comment]
Note: ``Provisioning.php`` ``checkAttributesForUser()`` method that was added in #30920 has already been backported (somewhere). So it does not appear in the diffs here.

**Review by phil-davis — APPROVED** [review]
test backport diffs look correct

**Comment by individual-it** [comment]
in stable10 `/settings/users/{id}/mailAddress` is used to change the settings, in master this functionality was moved to the `user_management` app, so if that app is not installed in master the user could not change its own settings. That is why  #30920 changes the functionality to use the provisioning API to change own settings. This change is not needed in stable10 because `/settings/users/{id}/mailAddress` is always available

**Pull request merged**
