### PR TITLE
[full-ci] Revert loader logic in ChunkLocationProvider.php

### PR DESCRIPTION
**Pull request by pako81**
## Description
Revert loader logic in ChunkLocationProvider.php

## Related Issue
- https://github.com/owncloud/firewall/issues/742

## Motivation and Context
File Firewall acceptance tests were failing after merging https://github.com/owncloud/core/pull/40693 as we changed the position of the loader in the constructor. Not sure why this is happening but reverting the change seems to make the tests to pass.

## How Has This Been Tested?
Ran File Firewall acceptance tests locally and make sure that following scenarios pass (they were previously failing):

```
webUILimitUpload/limituploadbasedonsize.feature:29
webUILimitUpload/limituploadbasedonsize.feature:37
webUILimitFileAccess/limitfileaccessbasedonrequesttype.feature:13
```

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised
- [ ] Changelog item

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares2-10.9.1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38130/104

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIRestrictSharing-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38130/132

**Comment by jvillafanez** [comment]
I think we'll have to investigate what's happening there. Accordingly to the constructor in https://github.com/owncloud/core/blob/master/lib/private/Files/Mount/MountPoint.php#L79 , if the loader is null, we use an "empty" storage factory instead of whatever storage factory is prepared. In particular, some wrappers could be set in place in the factory we want to inject, but they won't be present in the newly created one (if the loader is null).

If that's the case, we should remove the loader parameter in this PR because it's unused.

We probably should also investigate why the code is dependent on a specific loader; the wrappers around the storages shouldn't matter I think.

**Comment by phil-davis** [comment]
Yes, changing this code here does help the firewall tests to all pass. But actually the change here is removing the passing of "loader" to the `MountPoint` constructor. It gets passed as an entry in the `$arguments` parameter and gets ignored. So if this is the "fix" then we should completely remove `$loader` from being passed at all.

As @jvillafanez says, this needs investigation to understand what the code used to do, and what it should do. (And to try and provide a solution that is reasonably upward-compatible for apps like firewall - so that we don't have to require specific versions of firewall to go with specific releases of core)

**Comment by pako81** [comment]
When running the tests locally, in both cases (with and without loader in ChunkLocationProvider.php) following is logged:

```
{"reqId":"zG36QILFddhbJ6cEzTpW","level":4,"time":"2023-03-27T20:05:59+00:00","remoteAddr":"128.140.6.151","user":"admin","app":"webdav","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/filespecificSize.txt-chunking-3098-3-0","message":"Exception: HTTP\/1.1 403 Access to this resource has been forbidden by a file firewall rule.: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"Access to this resource has been forbidden by a file firewall rule.\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1098): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile()\\n
#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(504): Sabre\\\\DAV\\\\Server->createFile()\\n
#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPut()\\n
#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n
#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n
#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n
#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n
#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n
#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":185}"}
```

In addition, with the loader in place (which makes the firewall tests to fail) this is also logged:
```
**{"reqId":"ikmhcKdsCxI2FXrxI1Ok","level":4,"time":"2023-03-27T20:06:00+00:00","remoteAddr":"128.140.6.151","user":"admin","app":"webdav","method":"PUT","url":"\/owncloud\/remote.php\/dav\/uploads\/admin\/chunking-7148\/0","message":"Exception: Access to this resource has been forbidden by a file firewall rule.: {\"Exception\":\"OCP\\\\Files\\\\ForbiddenException\",\"Message\":\"Access to this resource has been forbidden by a file firewall rule.\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/firewall\\\/lib\\\/storagewrapper.php(91): OCA\\\\Firewall\\\\Firewall->checkRulesForFiles()\\n
#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/firewall\\\/lib\\\/storagewrapper.php(356): OCA\\\\Firewall\\\\StorageWrapper->checkFirewall()\\n
#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(726): OCA\\\\Firewall\\\\StorageWrapper->fopen()\\n
#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(*** sensitive parameters replaced ***)\\n
#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(754): OC\\\\Files\\\\View->emittingCall()\\n
#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(527): OC\\\\Files\\\\View->file_put_contents()\\n
#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Upload\\\/UploadFolder.php(37): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFileDirectly()\\n
#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1098): OCA\\\\DAV\\\\Upload\\\\UploadFolder->createFile()\\n
#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(504): Sabre\\\\DAV\\\\Server->createFile()\\n
#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPut()\\n
#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n
#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n
#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(348): Sabre\\\\DAV\\\\Server->start()\\n
#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n
#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n
#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/firewall\\\/lib\\\/firewall.php\",\"Line\":194}"}
```

**Comment by jvillafanez** [comment]
I don't know if those errors are ok because there is a firewall rule being correctly applied, or the errors shouldn't happen...

**Review by jnweiger — APPROVED** [review]
Let us merge this for 10.12.1
I'd like to see a full CI run. Please rebase and merge.

Please open a separate issue for further investigation of the $loader wrapper logic.

**Comment by jnweiger** [comment]
My rebase attempt failed. The history here is now a mess.
Clean restart at #40719

**Pull request closed without merging**
