### PR TITLE
Email confirmation link fix

### PR DESCRIPTION
**Pull request by imujjwal96**
## Related Issue
#27506
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by imujjwal96** [comment]
Hey @PVince81 ! Can you review this PR. 
I stored the email address in the same field as the email change confirmation token. 
":" is not a valid email address character and its presence is handled by javascript. Thus it should not be of concern.

**Comment by PVince81** [comment]
Looks good, tested works. 👍 

I'm a bit surprised that this didn't break any unit tests.

**Comment by imujjwal96** [comment]
I guess they'll need an upgrade. I'll push a commit for that.

**Comment by PVince81** [comment]
@imujjwal96 I'd like to merge this now as this is critical.

Please make a separate PR with unit tests. I suspect that there are no unit tests at all for this piece of code, that's why there were no failures.
Thanks

**Pull request merged**
