### PR TITLE
[3rdparty] Bump symfony/routing

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/219

https://github.com/owncloud/core/pull/20636 should go in first!

Lets see what our mighty CI has to say.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I did some basic checks and all still works :+1:

**Comment by rullzer** [comment]
Failing unit test seems unrelated.

**Comment by rullzer** [comment]
Also bumped since 3rdparty was rebased.

Blocked by https://github.com/owncloud/core/pull/20636

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by rullzer** [comment]
Updated

**Pull request merged**
