### PR TITLE
correct form of upload-white icon to be same as upload icon

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @owncloud/designers @skjnldsv

### CODE REVIEW

**Comment by jancborchardt** [comment]
Also cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@LukasReschke @MorrisJobke @icewind1991

**Comment by DeepDiver1975** [comment]
@karlitschek backport requested by @jancborchardt

**Comment by jancborchardt** [comment]
Backport at https://github.com/owncloud/core/pull/23631

**Comment by skjnldsv** [comment]
:+1:

**Comment by karlitschek** [comment]
please backport :+1:

**Pull request merged**
