### PR TITLE
adapt to new html structure

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
## Related Issue
Possible fix for https://github.com/owncloud/core/pull/38821#issuecomment-861349066
Issue https://github.com/owncloud/password_policy/issues/338

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
Looks good - test scenarios are passing in https://drone.owncloud.com/owncloud/password_policy/1812/24/11 webUIPasswordReset test suite. (They were failing without this fix)

**Comment by phil-davis** [comment]
You could add a link to this PR onto https://github.com/owncloud/core/blob/master/changelog/unreleased/38506

**Review by phil-davis — APPROVED** [review]

**Comment by hurradieweltgehtunter** [comment]
Let's wait for CI to complete?

**Comment by phil-davis** [comment]
> Let's wait for CI to complete?

I  am confident - the test CI in password_policy will finish and be green in 30 minutes. This core PR will take about an hour to finish its CI. Then we will know the meaning of "life, the universe and everything" and can merge this ;)

**Comment by hurradieweltgehtunter** [comment]
Going full-range philosophical here :D
Ok fine with me, up to you. You are a lot more familiar with CI

**Comment by phil-davis** [comment]
Test PR https://github.com/owncloud/password_policy/pull/339 has passed. This is "a good thing"  and can be merged when CI is green.

**Pull request merged**
