### PR TITLE
[stable8] Properly log out test users in unit tests

### PR DESCRIPTION
**Pull request by PVince81**
So far only to test Jenkins, but that call should be useful (it's on master too)

### CODE REVIEW

**Comment by PVince81** [comment]
Backport of https://github.com/owncloud/core/commit/eab55aa959d0bd167b6a2a51483cb1f24d471df0 from master

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
(just in case it causes random side effects)

**Comment by MorrisJobke** [comment]
:+1:

**Comment by rullzer** [comment]
makes sense

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
Backport approved here: https://github.com/owncloud/core/pull/16374#issuecomment-102464488 (several commits were approved, this PR includes one of them)

**Pull request merged**
