### PR TITLE
Adding header support to class OC_OCS_Result

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@rullzer

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by rullzer** [comment]
Looks good! :+1: 
To bad we do not have tests for this so we know it keeps working.

**Comment by DeepDiver1975** [comment]
we would need to have amockable class for functions like header - actually there is something in the appframework http io or something like this - but nothing for now - let's move this in .....

**Comment by rullzer** [comment]
@DeepDiver1975 I just noticed this is incomplete. Since we merge OCS responses the headers get lost.

**Comment by DeepDiver1975** [comment]
Ah -  forgot that .... Will take care asap.

**Pull request merged**
