### PR TITLE
Add NoAdminRequired annotation

### LINKED ISSUE #16288: User can't install root certificate
### Env
Master, PHP 5.5

### Steps to reproduce

1. Go to user settings
2. Click on "Import root certificate"
3. Select PEM encoded certificate

### Expected result

The certificate should be uploaded and listed in the admin area

### Actual result

The GUI shows the following error
"An error occurred. Please upload an ASCII-encoded PEM certificate."

which according to the logs is not what is happening

### Logs

`"app":"no app in context","message":"Logged in user must be an admin","level":0,"time":"2015-05-12T15:44:30+00:00","method":"POST","url":"\/index.php\/settings\/personal\/certificate" `

### PR DESCRIPTION
**Pull request by LukasReschke**
Stupid mistake in master, fixes https://github.com/owncloud/core/issues/16288

### CODE REVIEW

**Comment by LukasReschke** [comment]
cc @oparoz Please test

**Comment by oparoz** [comment]
:+1: works!

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Works :+1:

**Pull request merged**
