### PR TITLE
[tests-only] Acceptance test changes pending for master

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Currently we are in the core 10.9.0 release process. There is a `release-10.9.0` branch and there will be some behavior and test changes that will be done in that branch during the process. So we don't want to make unnecessary test core changes in core master for now. That might cause conflicts with the release branch.

We will add commits here for test code changes that will be useful to run for `owncloud/ocis` and `cs3org/reva`. After 10.9.0 release is stable we can decide when to merge this test branch to core master.

1) Improve checks in tests for disabling a user - related to issues https://github.com/owncloud/ocis/issues/1420 and #39512 - this provides extra checks in test scenarios that will help the oCIS test suite to fail for the right reason on these test scenarios.

2) Reduce use of "download range" in acceptance tests - part of #39513

3) Fix SetupHelper runOcc to use strings only in exception messages

4) Add tests to demonstrate group names with leading and trailing spaces

5) Adjust group tests for issue #39533

6) Refactor getGroups tests to not depend on the starting groups - this removes the need to list the pre-existing groups in a system-under-test.

7) Fix missing HTTP status code in createPublicLinkShare test scenarios

8) Use when step for the test scenario with only Then. (small refactoring of `webUIAdminSettings/adminGeneralSettings.feature` )

9) Fixed order dependent flaky test detected in files_classifier app (cherry-picked from PR #39548 )

10) add tests for db-convert occ command (cherry-picked and squashed from PR #39393 )

11) Do not allow white space at the start or end of a group name (cherry-picked and squashed from PR #39540 ) Having this here will allow the API tests to run in oCIS, and group name validation rules can be corrected there as needed.

12)  Add bug demonstration test for sending PUT request to other user's webdav endpoint

13) refactor test helpers and contexts for parallel deployment tests (code from #39603 )

14) skipOnEncryption dbConversion.feature as it needs special CI setup - skips the dbConversion scenario, because that is a very special scenario that requires starting with sqlite installed.

15) added tests for files_external occ command - cherry-picked from PR #39511 

16-17) Add spaces as a new webdav url type - merged from #39599 

18) Add extra checks to getPersonalSpaceIdForUser  - to better report when a space can't be found

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareManagementBasicToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33785/66/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/33785/66/1
`fatal: unable to access 'https://github.com/owncloud/core.git/': The requested URL returned error: 503`

There are problems accessing GitHub. That has been happening all weekend in some nightly CI. I am not in a hurry to run CI in this PR.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioningGroups-v1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34016/56/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProvisioningGroups-v2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34016/57/1

**Comment by phil-davis** [comment]
See #39612 for the rebased code being merged to master. After that happens, and the commit branch and id are updated in oCIS and reva then we can close this draft PR.

**Comment by phil-davis** [comment]
Merge to master in #39612 

I will close this PR but leave the branch here, because it is currently referenced by oCIS and reva CI.

**Pull request closed without merging**
