### PR TITLE
chore: drop deprecated API since ownCloud 6.0.0

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
:zzz: 

## Motivation and Context
:rocket: 

## How Has This Been Tested?
:robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
what do we do about semver?
normally deprecated things would be removed in the first release of a masjor version - so, for example, this could have been removed in 7.0.0 8.0.0. 9.0.0 or 10.0.0. 
Do we merge this now, and it will be removed in 10.14.0 ?

**Comment by DeepDiver1975** [comment]
We stopped using server as soon as the oc10 version mess started. 🤷

**Comment by phil-davis** [comment]
yes, we have been doing things like the Guzzle upgrade - for that we provided some code checks that detected the Guzzle version in use, and released that in a minor version 10.* (which obeys semver). But then we delete the old Guzzle5 code blocks a few minor versions later. That is a similar flow to what is happening here - remove old/deprecated things in some minor version release that comes "long enough" afterwards.

**Comment by DeepDiver1975** [comment]
If we wait for oc11 we will never re-juvenile the code base.

**Comment by phil-davis** [comment]
I agree - merge this.

**Pull request merged**
