### PR TITLE
add Tips & tricks section to admin settings

### PR DESCRIPTION
**Pull request by jancborchardt**
Just for jenkins purposes to get https://github.com/owncloud/core/pull/15083 tested.

### CODE REVIEW

**Comment by karlitschek** [comment]
looks good so far. :+1: 
I would improve the text a bit:
- How to do monitoring
- How to improve the performance
- How do do theming
- Advanced config.php settings

**Comment by jancborchardt** [comment]
I deliberately did the text like that so it doesn’t all start with »How to …« because that makes it quite difficult to distinguish.

**Comment by MorrisJobke** [comment]
Nice :+1:

**Comment by MorrisJobke** [comment]
@karlitschek Backport to stable8?

**Comment by MorrisJobke** [comment]
@jancborchardt @karlitschek Backport?

**Comment by karlitschek** [comment]
not sure this is something to backport. not an urgent bugfix. :-1:

**Pull request merged**
