### PR TITLE
Increase files_externals oC required version and its own version

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Just realized that https://github.com/owncloud/core/blob/master/lib/private/app.php#L1022 only works on the requiremin and requiremax - not the new app dependencies

@nickvergessen can you please adjust the code and prepare another pr? THX

**Comment by DeepDiver1975** [comment]
for this pr :+1:  - THX

**Comment by nickvergessen** [comment]
@DeepDiver1975 the dependencyresolver is missing
```php
		} else if (isset($appInfo['require'])) {
			$requireMin = $appInfo['require'];
		}
``` should I patch that aswell?

**Comment by DeepDiver1975** [comment]
> should I patch that aswell?

yes - this is what I did mean - THX

**Comment by nickvergessen** [comment]
@DeepDiver1975 see #13348

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
