### PR TITLE
Fix error message and add 'user' to it

### PR DESCRIPTION
**Pull request by jcfischer**
Error message when user deletion failed was incomplete

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by LukasReschke** [comment]
Test needs to get adjusted as well: https://ci.owncloud.org/job/pull-request-analyser-ng-simple/12775/label=SLAVE/testReport/junit/(root)/Tests_Core_Command_User_DeleteTest__testValidUser/testValidUser_with_data_set__1/

```
Tests\Core\Command\User\DeleteTest::testValidUser with data set #1 (false, 'The specified could not be deleted')
Expectation failed for method name is equal to <string:writeln> when invoked 1 time(s)
Parameter 0 for invocation Symfony\Component\Console\Output\OutputInterface::writeln('<error>The specified user cou...error>', 0) does not match expected value.
Failed asserting that '<error>The specified user could not be deleted. Please check the logs.</error>' contains "the specified could not be deleted".

/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/command/user/delete.php:66
/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/tests/lib/testcase.php:68
/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/tests/core/command/user/deletetest.php:86
```


@jcfischer As this is on a fork of this repo can I ask you to submit a commit? Thanks a lot!

**Comment by jcfischer** [comment]
@LukasReschke of course, sorry didn't realize that

**Comment by LukasReschke** [comment]
Thanks. Very much appreciated. – Let's get this in once @owncloud-bot agrees,

**Comment by nickvergessen** [comment]
woops, should be my fault.

:+1:

**Pull request merged**
