### PR TITLE
Webinterface use sharee API

### PR DESCRIPTION
**Pull request by rullzer**
Replaces #18236

Use the sharee endpoint for getting the list of people to share with.
- [X] Use sharee API
- [X] Filter sharees already shared with
- [X] Filter current user
- [X] Filter shared by (if this file/folder is shared with you)
- [x] More unit tests

CC: @owncloud/javascript @nickvergessen

### CODE REVIEW

**Comment by rullzer** [comment]
Ok tests added. Lets get this in :)

**Comment by blizzz** [comment]
Do we need to do all this post processing of the results to take out owner and current User on the client side? I've seen this on the desktop client as well. Feels somewhat error prone to me, too much code duplication, too much error prone?

**Comment by MorrisJobke** [comment]
> Do we need to do all this post processing of the results to take out owner and current User on the client side? I've seen this on the desktop client as well. Feels somewhat error prone to me, too much code duplication, too much error prone?

True story. I would like to have this filtered on the server side.

**Comment by nickvergessen** [comment]
> I would like to have this filtered on the server side.

Yeah we would have liked that as well, but together with the requirement of pagination, that is sadly not possible. Also note, that the API doesn't really know shares, it just knows share types. So we would have sent a list of names to filter out, but then if you are on page 2, you can't know if you need to start on 202 (author and owner were on page 1), 201 (author or owner were on page 1) or 200 (neither author nor owner were on page 1). So that is even more messy and in order to have a clean API, it is like this.

**Comment by nickvergessen** [comment]
Works, thanks for taking over :+1:

**Comment by nickvergessen** [comment]
PS: do we delete the old endpoint, or you want to keep it for calendar + contacts for now?

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by rullzer** [comment]
> PS: do we delete the old endpoint, or you want to keep it for calendar + contacts for now?

We should move that over to the calendar and contacts app I think eventually.

**Comment by rullzer** [comment]
As @nickvergessen pointed out server side has several issues. 

* Either the clients send a list of stuff to filter out (which is problematic as described)
* You send a list of share ids (same problem)
* You tell the sharee API which file/folder you want to have completion for. This is very bad performance wise since it leads to a significant amount of queries for each sharee lookup.

So yeah it is not ideal. But it is the only thing we could come up with that kind of scaled. Since the clients have the list of sharees already anyway.

**Pull request merged**
