### PR TITLE
Add favicon for IE8-10

### LINKED ISSUE #18012: Favicon in IE9 not presented
### Steps to reproduce
1. install oC 8.0.5
2. use IE9 
3. check Favicon on the open browser tab

### Expected behaviour
Favicon should show ownCloud icon
see image below (from IE11)
favicon_missing_ie9-3
:

### Actual behaviour
IE icon visible on IE 9

favicon_missing_ie9-2

### Server configuration
RHEL 6.6

**Web server:**
Apache 2.4
**Database:**
Mysql
**PHP version:**
5.4.
**ownCloud version:** (see ownCloud admin page)
oc8.0.5
**Updated from an older ownCloud or fresh install:**
fresh

### Client configuration
IE 9

**Operating system:**
Win 7

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @jancborchardt 

Fixes #18012 

This doesn't work yet and needs further refinement. This is my current state of the fix.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@CaptionF please review if this fixes your issue.

**Comment by MorrisJobke** [comment]
@jancborchardt please read my comments. This is not yet finished and therefore also marked as wip

**Comment by MorrisJobke** [comment]
@jancborchardt For favicon support in IE we need to generate `ico` files. For older IEs (8, 9) we also need to place them in the root of the URL (https://my.domain.com/favicon.ico - could be done via rewrite rule if owncloud is in a subfolder) - for higher version it can also be placed in a subdirectory (https://my.domain.com/owncloud/favicon.ico is valid).

@MTRichards Is this worth the effort?

**Comment by jancborchardt** [comment]
@MTRichards @DeepDiver1975 statement please if this is worth the effort.

**Comment by MTRichards** [comment]
Yes please, because it is IE up to 10.

**Comment by MorrisJobke** [comment]
> Yes please, because it is IE up to 10.

Okay. So this PR already solves it for IE10. For IE8 & 9 it will only work if owncloud is installed in the root and not a subdirectory and we add some rewrite rules. :see_no_evil:

**Comment by DeepDiver1975** [comment]
@MorrisJobke let's move this one in - fixes at least some case.

**Comment by DeepDiver1975** [comment]
@rperezb we need qa power on this - thx

**Comment by MorrisJobke** [comment]
I just downloaded the IE10 image to test if it even fixes it in IE10

**Comment by MorrisJobke** [comment]
I tested the latest changes and they now work with IE10

I will try to get it working in IE9 ...but I think this is harder.

**Comment by MorrisJobke** [comment]
I need to choose an ico file to support IE9 and IE10. PNG support started with IE11: https://en.wikipedia.org/wiki/Favicon#How_to_use

I tested this and it works in IE8, IE9 and IE10 too now.

Also work in other browsers - Firefox: (left old version, right, new version)

bildschirmfoto von 2015-10-08 23-58-13


@DeepDiver1975 Ready for review now.

**Comment by MorrisJobke** [comment]
I also updated the example theme favicon.

**Comment by MorrisJobke** [comment]
@LukasReschke @nickvergessen @CaptionF Please test

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Should we not have those as IE8/9/10-only fallback rules?

**Comment by MorrisJobke** [comment]
> Should we not have those as IE8/9/10-only fallback rules?

Feel free to do so. I have no idea how to do them, because IE10 doesn't support the magic HTML-comment-ifdef stuff and then we also need a way to remove the other rule on all IE (so we need the else branch, which is also not available). I would be more than happy to have it, but none of my tests were successful.

**Comment by MorrisJobke** [comment]
@owncloud/designers @Henni @jancborchardt @LukasReschke @davitol Can we get this reviewed?

**Comment by PVince81** [comment]
Moving to 9.0 to match the ticket

**Comment by davitol** [comment]
@MorrisJobke :-1: It doesn't work for me. :crying_cat_face: 

logs:

{"reqId":"K9nO0WLyPgk+SP84WiDs","remoteAddr":"82.159.139.58","app":"core","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"image not found: image:favicon.ico webroot: serverroot:\\\/opt\\\/owncloud\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/helper.php(174): OC\\\\URLGenerator->imagePath('', 'favicon.ico')\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/functions.php(169): OC_Helper::imagePath('', 'favicon.ico')\\n#2 \\\/opt\\\/owncloud\\\/core\\\/templates\\\/layout.guest.php(15): image_path('', 'favicon.ico')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(160): include('\\\/opt\\\/owncloud\\\/c...')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(138): OC\\\\Template\\\\Base->load('\\\/opt\\\/owncloud\\\/c...')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template.php(211): OC\\\\Template\\\\Base->fetchPage()\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template.php(233): OC_Template->fetchPage()\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/template.php(338): OC\\\\Template\\\\Base->printPage()\\n#9 \\\/opt\\\/owncloud\\\/index.php(55): OC_Template::printExceptionErrorPage(Object(RuntimeException))\\n#10 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php\",\"Line\":189}","level":3,"time":"2015-10-13T08:59:30+00:00"}

**Comment by MorrisJobke** [comment]
> @MorrisJobke  It doesn't work for me.

Which browser? Which OS?

**Comment by davitol** [comment]
@MorrisJobke IE9, WIn XP (64-bits) ; sorry about not writing the info in the previous comment

**Comment by MorrisJobke** [comment]
> @MorrisJobke IE9, WIn XP (64-bits) ; sorry about not writing the info in the previous comment

Can you check that you use the correct commit 457b43f ? I rebased recently, maybe you are on an old version :see_no_evil:

**Comment by PVince81** [comment]
@davitol any update ?

**Comment by davitol** [comment]
> Can you check that you use the correct commit 457b43f

@PVince81 @MorrisJobke I have retested and it doesn't work for me. Same error as said before

**Comment by MorrisJobke** [comment]
> @PVince81 @MorrisJobke I have retested and it doesn't work for me. Same error as said before

I don't get it. I just rebased this again. Maybe we can debug this together at your machine via screensharing? I would like to get this in. Just ping me once you have time @davitol

**Comment by davitol** [comment]
:+1: Now it WFM @MorrisJobke 

screen shot 2015-11-04 at 10 29 37

**Comment by MorrisJobke** [comment]
@PVince81 Mind to give this a short test?

**Comment by PVince81** [comment]
Tested IE8, IE9, IE10, IE11, Firefox and Chrome, combined with login page, public link and regular page => favicon works :+1:

**Comment by mmccarn** [comment]
The favicon.ico patch seems not to work with  a custom theme:
[favicon.ico from custom theme is not applied #23758](https://github.com/owncloud/core/issues/23758)

**Pull request merged**
