### PR TITLE
[Appframework] Add IServerContainer to DI

### PR DESCRIPTION
**Pull request by MorrisJobke**
- it is already available under `ServerContainer` (see ~10 lines below) but being able to use the type hinting is easier and the way to go

cc @Raydiation @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
I hereby agree :+1:

**Comment by Raydiation** [comment]
Usecase?

**Comment by Raydiation** [comment]
Everything is already resolved from the server container using the respective interfaces, I kinda see this promoting the service locator anti pattern.

**Comment by MorrisJobke** [comment]
I have a method that needs the user folder, but multiple different. The other way would be to use the IRootFolder, that can resolve the user folders. Then we should also remove the ServerContainer alias.

Should I add the getUserFolder to the IRootFolder?

**Comment by MorrisJobke** [comment]
> I kinda see this promoting the service locator anti pattern.

Agreed

**Comment by Raydiation** [comment]
> Should I add the getUserFolder to the IRootFolder?

@MorrisJobke yep :) that's the way to go. Sorry for shooting down your suggestions lately :)

**Comment by MorrisJobke** [comment]
> @MorrisJobke yep :) that's the way to go. Sorry for shooting down your suggestions lately :)

no problem :)

**Comment by DeepDiver1975** [comment]
> I kinda see this promoting the service locator anti pattern.
> 
> Agreed

and therefore: close

**Comment by MorrisJobke** [comment]
Replaced by #16965

**Pull request closed without merging**
