### PR TITLE
Only show message in the UI when the checker is enabled

### LINKED ISSUE #24752: integrity.check.disabled does not completely disable integrity check feature
I need to disable this integrity feature as I am patching ownCloud. 
For example to fix that issue https://github.com/owncloud/core/issues/18971.

I have tried integrity.check.disabled config option but I still see 'There were problems with the code integrity check.' message.

Syncloud users usually install ownCloud app for themselves so they are admins by default, hence all our users see the message. 

Is it possible to honour this flag in UI as well?
I understand I can patch Checker as well, but what is the point of this flag then?

### PR DESCRIPTION
**Pull request by nickvergessen**
@karlitschek @PVince81 should backport?

Fix #24752 

review @LukasReschke

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by karlitschek** [comment]
hehe nice. please backport

**Comment by PVince81** [comment]
Second review @rullzer @icewind1991 @LukasReschke ?

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
