### PR TITLE
Always show current app-name

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Always show the current app-name in the top left corner no matter if CE or EE

## Motivation and Context
Company requirement

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
> felix@heidecke.me seems not to be a GitHub user

committed with wrong email address?

**Comment by PVince81** [comment]
please fill "How Has This Been Tested?" with your test cases to confirm that you tested this, thanks (CE and EE)

**Comment by PVince81** [comment]
@felixheidecke please always set the milestone and ping some people, especially for important PRs, else the PR might not get noticed...

**Review by pmaier1 — COMMENTED** [review]
I can't review this :) @PVince81 or else

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
