### PR TITLE
Allow listing of users and groups via OCS API

### PR DESCRIPTION
**Pull request by rullzer**
As described in #16646

This allows listing of users and groups so clients can also implement user/group sharing (with completion).

Original I had the Link header. But that breaks unit testing.

TODO:
- [ ] shareable option (to only list who we can share with) (default?, no other reason to list)
- [ ] Maybe direct avatar link .../users/<uid>/avatar (separate PR).

Comments are welcome: @DeepDiver1975 @LukasReschke @PVince81 @MorrisJobke 

@dragotin: Can you think of any additional stuff we need in the client besides the uid/displayname and maybe an avatar?

### CODE REVIEW

**Comment by nickvergessen** [comment]
Duplicating https://github.com/owncloud/core/blob/master/apps/provisioning_api/lib/users.php#L40-L45 :question: 
Maybe we can extend the existing end point to allow searching? But then again you need the Provi App to be enabled, so maybe some core thing makes more sense.

**Comment by rullzer** [comment]
@nickvergessen well the provisioning API requires ADMIN_AUTH.
And the whole app servers a different purpose. So yes there is duplication but there is a reason ;)

Also this should probably be in core... just as the sharing API *should* be in core.

**Comment by nickvergessen** [comment]
> Also this should probably be in core... just as the sharing API should be in core.

Which is exactly what I wanted to tell you. Instead of duplicating it, move one to core ;)

**Comment by rullzer** [comment]
@nickvergessen well, the functions calls are already standardized in core. So then both would just call the same function. Which now also is basically the case (provision is bad by not using OCP). We just happen to have 2 endpoints that can show the same data.

Keep in mind that we might want to filter the endpoint here to only people/groups that we can share with. Which would not be a requirement for the provisioning API.

At some point we probably should move more stuff to core. But probably that only makes sense if sharing is also moved.

**Comment by DeepDiver1975** [comment]
This implementation has to respect the existing behavior - see https://github.com/owncloud/core/blob/master/core/ajax/share.php#L238-L389

**Comment by DeepDiver1975** [comment]
Hmm ... I don't know if this is the right approach, because (at least from my understanding) we need to return users, groups and remote users (fed cloud id from contacts) based on the search string.

This would result into 3 server calls ... we might want to have an api with combined results?

For the link sharing by email we need only mail addresses to be returned ....

@rullzer @PVince81 @blizzz @danimo @rperezb

**Comment by rullzer** [comment]
@DeepDiver1975 yeah thinking about this also made me reconsider.
For now I think I'll just copy the old behaviour to the OCS Share API. Maybe a bit more structured. Hopefully I can get it fixed this weekend.

**Comment by DeepDiver1975** [comment]
> For now I think I'll just copy the old behaviour to the OCS Share API. Maybe a bit more structured. Hopefully I can get it fixed this weekend.

I'll chat with @danimo and @rperezb about this .... let's see

**Comment by DeepDiver1975** [comment]
We need a different approach as discussed - let me close this - THX @rullzer

**Pull request closed without merging**
