### PR TITLE
Token Auth: Return proper HTTP code (follow up #25162)

### PR DESCRIPTION
**Pull request by guruz**

### CODE REVIEW

**Comment by PVince81** [comment]
having 403 mixed up with the "NotAuthenticated" base class.

Is it necessary to have this be 403 ?
Note that the firewall also returns 403.

The clients might also be able to parse the exception name, not too nice I guess.

**Comment by PVince81** [comment]
CC @ChristophWurst

**Comment by PVince81** [comment]
If you want to keep 403 and are sure it won't cause other side effects, then it might be better to make the exception extend from Sabre's `Forbidden` exception instead of `NotAuthenticated`

**Comment by guruz** [comment]
Hm, maybe we can keep it at 401. But then for sure the client needs some handling because it is currently just redisplaying the auth dialog without further reason.

I'm confused now myself.

**Comment by ChristophWurst** [comment]
I don't see the why 403 would be a better option. It's an authentication error, so 401 is fine by me. Also 3rd party clients will handle 403 differently.
Our own clients can detect the custom exception message an show an appropriate error message. Any other clients should behave as if the password was wrong.

**Comment by guruz** [comment]
OK, I'll take this back then for now and check the client code.

**Pull request closed without merging**
