### PR TITLE
Bump 3rdparty for phpseclib-2.0.0

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/213

No code changed in the 3rdparty repo... only 2.0-dev to 2.0.0

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3rdpart merged .. please update @rullzer

**Comment by rullzer** [comment]
rebased

**Comment by LukasReschke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
