### PR TITLE
3rdparty bump for pimple-3.0.2

### PR DESCRIPTION
**Pull request by rullzer**
requires https://github.com/owncloud/3rdparty/pull/204

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by LukasReschke** [comment]
@rullzer can you rebase since 3rdparty is merged?

**Comment by LukasReschke** [comment]
Rebased upon merged 3rdparty.

**Comment by LukasReschke** [comment]
@DeepDiver1975 THX

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
