### PR TITLE
Add unix_socket support for mysql during initial installation - fixes…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… #20210

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@josh4trunks mind testing? THX

**Comment by PVince81** [comment]
Code looks good, apparently copied from the connection factory. :+1: 
Setup still works with standard settings (no port, no socket)

**Comment by josh4trunks** [comment]
I'll take a look in the following days.

**Comment by PVince81** [comment]
If this PR doesn't cause any side effects I suggest merging it soon.

@icewind1991 what do you think ?

@DeepDiver1975 also needs a forward port to master ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 also needs a forward port to master ?

already there: https://github.com/owncloud/core/pull/20984

**Comment by DeepDiver1975** [comment]
> If this PR doesn't cause any side effects I suggest merging it soon.

yeah - we should

**Comment by PVince81** [comment]
Needs a second reviewer @icewind1991 @nickvergessen @Xenopathic

**Comment by DeepDiver1975** [comment]
> Needs a second reviewer @icewind1991 @nickvergessen @Xenopathic

as per https://github.com/owncloud/core/pull/20984#issuecomment-163529688 :+1:

**Pull request merged**
