### PR TITLE
[stable8.1][avatar] add error handlers for avatar setup

### PR DESCRIPTION
**Pull request by rullzer**
Backport of #17805
Approved in https://github.com/owncloud/core/pull/17805#issuecomment-123674758

CC: @MorrisJobke @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Thx

**Comment by DeepDiver1975** [comment]
We need this for 8.1.1

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by SergioBertolinSG** [comment]
Tested in stable8.1+ this PR works fine. :+1:
But it is very slow, it throws the error after uploading the whole image.
This behaviour depends on a more general function in core? I see it always when uploading files that has to show an error.
@DeepDiver1975 do you know if errors could be shown before uploading the file, and therefore not even start to upload it?
 or that file info is not available until the upload is complete?

**Comment by rullzer** [comment]
@SergioBertolinSG well, feel free to submit a PR against master that can check for that. HTML5 does allow some checks in that direction if I'm not mistaken. This PR makes sure it works on all browsers.

But as I said in the original PR. If a users thinks it is a good idea to upload a 50MB image for an avatar then I don't think we should try to make the experience as smooth as possible. We have more important issues to focus on ;)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 do you know if errors could be shown before uploading the file, and therefore not even start to upload it?
> or that file info is not available until the upload is complete?

Since we perform the checks server side there is nothing else to be done from my POV.
While there might be possibilities to handle certain checks on the client this all sounds like over engineering for a problem which does not really exist since the avatar is set once in a life time and done.

**Comment by PVince81** [comment]
The FileReader API might make it possible to read the file size early as it's done for regular file uploads. HOWEVER it needs workarounds for IE8 and co, so probably overkill for this use case anyway.

**Comment by karlitschek** [comment]
backport is fine with me :+1:

**Pull request merged**
