### PR TITLE
setting for recursive extra config.php search

### PR DESCRIPTION
**Pull request by mrow4a**
## Description

Feature: setting for recursive extra config.php search

Before this change extra config.php files were required to be placed directly in the config folder. 
This change allows to have nested folders configuration structure, enabled by config value OC_CONFIG_EXTRA_RECURSIVE_SEARCH, that can be useful in some deployments.

NOTE: due to the fact that this configuration control setting the configuration itself, it is only possible to enable this setting with environment variable, it is not possible to enable it with *.config.php file.

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/5406

## How Has This Been Tested?
- manually in the developer instance

-> add nested config
-> Update entry in `/etc/apache2/sites-available/owncloud.conf` with `SetEnv OC_CONFIG_EXTRA_RECURSIVE_SEARCH true` 
@d7oc NOTE: probably in your case it needs to be Dockefile env, but you would need to test this. In owncloud code we do not care how env is provided, as soon as it is provided by methods allowed by deployment (docker, apache2, etc..).
-> check that config is applied

- unit/acceptance tests

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] Base code changes
- [x] Unit tests added
- [x] Acceptance tests added
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliEncryption-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36968/114

**Comment by mrow4a** [comment]
@phil-davis has something change to SonarCloud? I have full coverage for the code, and sonar says 0%. Somehow my unit test was not detected?

**Comment by phil-davis** [comment]
> @phil-davis has something changed to SonarCloud? I have full coverage for the code, and sonar says 0%. Somehow my unit test was not detected?

Thanks for letting me know. Should be fixed by #40415

**Comment by mrow4a** [comment]
@mmattel not true, check description. it is not possible to add this to any of *.config.php, it can only be enabled using ENV variable

```
NOTE: due to the fact that this configuration control setting the configuration itself, it is only possible to enable this setting with environment variable, it is not possible to enable it with *.config.php file.
```

however, I am not sure if we ever merge this PR.. seems no longer needed for related deployment

**Comment by pako81** [comment]
@d7oc is this still needed?

**Comment by d7oc** [comment]
Not from my side. See my comment in https://github.com/owncloud/enterprise/issues/5406#issuecomment-1274719083

**Pull request closed without merging**
