### PR TITLE
Remove readdir implementation from View.php, unused and broken.

### PR DESCRIPTION
**Pull request by ahmedammar**
## Description
`readdir` implemention in View.php seems pretty broken, possibly left-over from some old approach. No one even uses it. Should just remove since `View::opendir` and system `readdir` is a perfectly functional alternative.

## Motivation and Context

Removing dead code.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Please also remove Filesystem::readdir - this is the only location which uses View::readdir - THX for noticing!

**Comment by ahmedammar** [comment]
Ah, didn't spot that, will do (once I have a clean tree) 😉

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase was successful!

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
