### PR TITLE
Move Gdrive to separate repo

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Remove GDrive.
Moved to https://github.com/owncloud/files_external_gdrive

## Related Issue
Ref https://github.com/owncloud/core/issues/27049

## Motivation and Context
Marketplace

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Repo added here: https://github.com/owncloud/files_external_gdrive.

Still WIP, don't merge until we have a stable release of https://github.com/owncloud/files_external_gdrive

**Comment by PVince81** [comment]
rebased.

Wow "244,487" lines removed

**Review by DeepDiver1975 — APPROVED** [review]
🏆

**Comment by PVince81** [comment]
to be backported to stable10 only once the app actually works... trouble ahead due to Guzzle versions, changed SDK APIs in more recent versions, etc... fun times

**Comment by DeepDiver1975** [comment]
@PVince81 shall we really backport this?

**Comment by PVince81** [comment]
Only once the app is released and available on the marketplace.

**Pull request merged**
