### PR TITLE
more secure way to update the database

### LINKED ISSUE #17443: "occ encryption:migrate" throws different exceptions (8.1)
Hi all,

I have just upgraded from 8.0.4 to 8.1.0, and the syslog was showing :

"Installation is in transit between the old Encryption (ownCloud <= 8.0) and the new encryption. Please enable the "Default encryption module" and run 'occ encryption:migrate'"

Which I just tried, I activated the Default encryption in the administration page, put OC in the maintenance mode, but when running "./occ encryption:migrate" I get back this:

------------------------------------------------- cut --------------------------------------------
$ ./occ encryption:migrate
Reorganize system folder structure
                                                                                                                                                   
  [Doctrine\DBAL\Exception\UniqueConstraintViolationException]                                                                                     
  An exception occurred while executing 'UPDATE "oc_appconfig" SET "appid" = ? WHERE "appid" = ?' with params ["encryption", "files_encryption"]:  
  SQLSTATE[23000]: Integrity constraint violation: 19 columns appid, configkey are not unique                                                      
                                                            
  [Doctrine\DBAL\Driver\PDOException]                                                          
  SQLSTATE[23000]: Integrity constraint violation: 19 columns appid, configkey are not unique  

  [PDOException]                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 19 columns appid, configkey are not unique  
                                                                                               
encryption:migrate [user_id1] ... [user_idN]

$
------------------------------------------------- cut --------------------------------------------

Backend is SQLite. Any help is welcome,

kind regards, Joerg.

### PR DESCRIPTION
**Pull request by schiessle**
make update of the database more robust.

fix https://github.com/owncloud/core/issues/17443

@jknockaert can you review it. Note: Trashbin still needs to be disabled

### CODE REVIEW

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
@schiesbn so if I understand well now you first set the target value and then delete the original one instead of directly renaming.

**Comment by PVince81** [comment]
Any steps to reproduce the original issue ? Should I manually add some extra values in the config table ?

**Comment by PVince81** [comment]
- [ ] TEST: regular migration
- [ ] TEST: migration with "difficult" config

**Comment by schiesbn** [comment]
> Any steps to reproduce the original issue ? Should I manually add some extra values in the config table ?

yes, you can for example add something like ('encryption', 'publicShareKeyId', 'dummy share id') to the appconfig table before you run the migration. With this PR it should work, with stable8.1 you will get a Doctrine\DBAL\Exception\UniqueConstraintViolationException because a "publicShareKeyId" already exists for "encryption" if you want to rename the value from "files_encryption"

**Comment by PVince81** [comment]
:+1: works

**Comment by MorrisJobke** [comment]
Tested and works with this fix. (without the UNIQUE constraint issue appears) :+1:

**Comment by MorrisJobke** [comment]
@schiesbn Please create the backport PR for 8.1.1 against stable8.1

**Comment by schiesbn** [comment]
@karlitschek this need to be backported to 8.1, approved?

**Comment by karlitschek** [comment]
Please backport :+1:

**Pull request merged**
