### PR TITLE
encryption improvements

### PR DESCRIPTION
**Pull request by schiessle**
- remove files_encryption from database at the end of the migration process (as long as files_encryption is in the database the new module will not be loaded, this should block all possible file operations on encrypted files until the migration finished)

improvements from https://github.com/owncloud/core/issues/17035

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by schiesbn** [comment]
@PVince81 this should fix the migration case. As long as the migration runs the stream wrapper should fail to load the encryption module and return a error.

I couldn't reproduce the other problems with this branch. Uploading a new file works but if I try to update a encrypted file I get a error because this will throw an exception: https://github.com/owncloud/core/blob/master/lib/private/files/storage/wrapper/encryption.php#L360

**Comment by PVince81** [comment]
Note: I also see the web UI showing the sizes as "8k" (even on this branch)

**Comment by PVince81** [comment]
I am still able to upload/overwrite files with the sync client and they appear unencrypted in the data folder.

**Comment by PVince81** [comment]
This is directly after upgrading to this branch. I didn't run any encryption migration nor enabled the new module.

I see the version is still in the DB:
`| files_encryption  | installed_version        | 0.7.1`

**Comment by schiesbn** [comment]
> Note: I also see the web UI showing the sizes as "8k" (even on this branch)

Yes, but that's because the migration is not completed, not much we can do about this.

> I am still able to upload/overwrite files with the sync client and they appear unencrypted in the data folder.

Strange, I can't reproduce it. As said above a exception should be thrown while calling this method: https://github.com/owncloud/core/blob/master/lib/private/files/storage/wrapper/encryption.php#L360

Maybe you can set a break point and step though it with your debugger?

**Comment by PVince81** [comment]
Steps:
1. Setup stable8
2. Enable encryption, log out then log in again
3. Setup sync client, let it sync
4. Create two files locally "one.txt" and "two.txt", let it sync
5. Let the sync client running
6. Switch to this branch
7. Run the core update in the web UI
8. Edit "one.txt" locally, save, let it sync
9. Check "one.txt" in the data folder: not encrypted.

Ok let me try debugging this

**Comment by PVince81** [comment]
@schiesbn is the migration.php even run in my situation ? I didn't do anything with encryption after the core update. So I think that file is never executed at this point and this PR change would not have any effect. Is this code run after I click "Start migration" ?

**Comment by PVince81** [comment]
Let me try with the redis module disabled, in case it's a side effect of memcaching.

**Comment by schiesbn** [comment]
@PVince81 no but this shouldn't change the behaviour. We read the encryption module from the header, try to load it -> exception. Don't know why the exception isn't thrown in your case.

The changes to the migration.php just prevent that we don't "release" the new encryption to early while we run the migration -> different issue (second checkbox here https://github.com/owncloud/core/issues/17035#issue-89396929)

**Comment by PVince81** [comment]
Same problem without memcache/redis.

Ok, time to debug

**Comment by PVince81** [comment]
`$encryptionEnabled` is false, so `$shouldEncrypt` becomes false too.

This is the encryption wrapper. It just happily forwards the call to $storage->fopen().

Where is the code that throws the exception ? I can check if it goes there.

**Comment by PVince81** [comment]
Hmm, uploading in the web UI works too.

Either this is a misunderstanding in the steps or something is different in our environments.

**Comment by schiesbn** [comment]
> This is the encryption wrapper. It just happily forwards the call to $storage->fopen().
> Where is the code that throws the exception ? I can check if it goes there.

That's OK. This function call should throw the exception: https://github.com/owncloud/core/blob/master/lib/private/files/storage/wrapper/encryption.php#L360

From here we get OC_DEFAULT_MODULE as encryption module because we try to overwrite a existing encrypted file, so the if statement in L358 is true, we try to load the encryption module (which isn't enabled") -> exception.

**Comment by schiesbn** [comment]
@PVince81 Please have a look. Should work now.

**Comment by PVince81** [comment]
:+1: works, encrypted files cannot be overwritten any more before the migration.

**Pull request merged**
