### PR TITLE
[master] Use correct expiration variable for link share mail

### PR DESCRIPTION
**Pull request by PVince81**
Master port of https://github.com/owncloud/core/pull/31201/

### CODE REVIEW

**Comment by PVince81** [comment]
also added https://github.com/owncloud/core/pull/31212

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
@DeepDiver1975 quick review of this port ?

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
