### PR TITLE
Tests maintenancemode endpoint

### PR DESCRIPTION
**Pull request by PVince81**
Add integration tests for maintenance mode.

Currently they fail randomly on Jenkins and some environments but not others, see details here https://github.com/owncloud/core/pull/27821#issuecomment-300522184

Needs further research.

### CODE REVIEW

**Comment by PVince81** [comment]
Solved conflict, rebased. Trying our luck 🍀

**Comment by PVince81** [comment]
@SergioBertolinSG do you still want to keep this ? or maybe write this differently ?

**Comment by SergioBertolinSG** [comment]
Not sure, it requires to solve conflicts, rebase with master and use current master improvements.

After that check if they are passing or failing sometimes like before.

I can take a look when I have less manual testing to do.

**Comment by PVince81** [comment]
@SergioBertolinSG thanks for taking over, assigning to you then

**Comment by phil-davis** [comment]
I assigned myself also, because I "nearly" have the integration tests refactoring ready. That will make more merge conflicts. This looks like a useful few tests for the maintenance on/off command and will be easy for me to resolve conflicts against the refactored integration tests (while it is still in my head).

**Comment by PVince81** [comment]
too high effort for not much value, also conflicts

closing

**Pull request closed without merging**
