### PR TITLE
Group fixup

### PR DESCRIPTION
**Pull request by rullzer**
Move the legacy classes OC_Group_Backend and OC_Group_Database to the proper namespace \OC\Group.

Legacy wrappers in OC_Group_xx are still in place.

CC: @nickvergessen @MorrisJobke @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by PVince81** [comment]
@rullzer can you rebase to revive to kick Jenkins ? Would be good to have at least the basic DB tests passing.

**Comment by rullzer** [comment]
Rebased

**Pull request merged**
