### PR TITLE
Log which path was not found

### PR DESCRIPTION
**Pull request by butonic**
Don't make the admin guess... wait are there more occurences?

``` console
➜  core git:(master) ✗ grep -r 'NotFoundException()' | grep new | grep -v coverage
3rdparty/symfony/routing/Matcher/Dumper/PhpMatcherDumper.php:        throw 0 < count(\$allow) ? new MethodNotAllowedException(array_unique(\$allow)) : new ResourceNotFoundException();
lib/private/legacy/helper.php:          throw new \OCP\Files\NotFoundException();
lib/private/Share20/Share.php:              throw new NotFoundException();
lib/private/Share20/Share.php:              throw new NotFoundException();
lib/private/Comments/Manager.php:           throw new NotFoundException();
lib/private/Files/Node/Root.php:        throw new NotFoundException();
lib/private/Files/Node/Root.php:        throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:       throw new NotFoundException();
lib/private/Files/Node/NonExistingFolder.php:           throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:     throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:     throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:     throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:     throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:     throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:     throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:     throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:         throw new NotFoundException();
lib/private/Files/Node/NonExistingFile.php:     throw new NotFoundException();
lib/private/Files/Node/Node.php:                throw new NotFoundException();
apps/files_external/tests/Controller/StoragesControllerTest.php:            ->will($this->throwException(new NotFoundException()));
apps/files_external/tests/Controller/StoragesControllerTest.php:            ->will($this->throwException(new NotFoundException()));
apps/files_external/tests/Command/CommandTest.php:              throw new NotFoundException();
apps/files_sharing/lib/Controllers/ShareController.php:         throw new NotFoundException();
apps/files_sharing/lib/Controllers/ShareController.php:             throw new NotFoundException();
apps/files_sharing/lib/Controllers/ShareController.php:             throw new NotFoundException();
apps/files_sharing/lib/Controllers/ShareController.php:         throw new NotFoundException();
apps/files_sharing/lib/External/Storage.php:                throw new NotFoundException();
apps/files_sharing/lib/API/Share20OCS.php:          throw new NotFoundException();
apps/files_sharing/tests/API/Share20OCSTest.php:            ->will($this->throwException(new \OCP\Files\NotFoundException()));
apps/files/lib/Controller/ViewController.php:       throw new \OCP\Files\NotFoundException();
apps/dav/tests/unit/SystemTag/SystemTagNodeTest.php:            ->will($this->throwException(new TagNotFoundException()));
apps/dav/tests/unit/SystemTag/SystemTagNodeTest.php:            ->will($this->throwException(new TagNotFoundException()));
apps/dav/tests/unit/SystemTag/SystemTagMappingNodeTest.php:         ->will($this->throwException(new TagNotFoundException()));
apps/dav/tests/unit/SystemTag/SystemTagsObjectMappingCollectionTest.php:            ->will($this->throwException(new TagNotFoundException()));
apps/dav/tests/unit/SystemTag/SystemTagsObjectMappingCollectionTest.php:            ->will($this->throwException(new TagNotFoundException()));
apps/dav/tests/unit/SystemTag/SystemTagsObjectMappingCollectionTest.php:            ->will($this->throwException(new TagNotFoundException()));
apps/dav/tests/unit/SystemTag/SystemTagsByIdCollectionTest.php:         ->will($this->throwException(new TagNotFoundException()));
apps/dav/tests/unit/SystemTag/SystemTagsByIdCollectionTest.php:         ->will($this->throwException(new TagNotFoundException()));
apps/dav/tests/unit/Comments/EntityCollectionTest.php:          ->will($this->throwException(new \OCP\Comments\NotFoundException()));
apps/dav/tests/unit/Comments/EntityCollectionTest.php:          ->will($this->throwException(new \OCP\Comments\NotFoundException()));
apps-repos/activity/tests/FilesHooksTest.php:               ->willThrowException(new NotFoundException());
apps-repos/activity/tests/FilesHooksTest.php:               ->willThrowException(new NotFoundException());
apps-repos/activity/tests/FilesHooksTest.php:           ->willThrowException(new NotFoundException());
apps-repos/activity/tests/FilesHooksTest.php:               ->willThrowException(new NotFoundException());
apps-repos/activity/tests/ViewInfoCacheTest.php:                ->willThrowException(new NotFoundException());
apps-repos/activity/tests/ViewInfoCacheTest.php:                    ->willThrowException(new NotFoundException());
tests/lib/Files/Node/FolderTest.php:            ->will($this->throwException(new NotFoundException()));
tests/lib/Files/Node/FileTest.php:          ->will($this->throwException(new NotFoundException()));
tests/lib/Files/Node/FileTest.php:          ->will($this->throwException(new NotFoundException()));
tests/Core/Controller/AvatarControllerTest.php:     $this->avatarMock->method('getFile')->will($this->throwException(new NotFoundException()));
tests/Settings/Controller/UsersControllerTest.php:          ->will($this->throwException(new \OCP\Files\NotFoundException()));
```

oh tons ... feel free to add to this PR

### CODE REVIEW

**Comment by PVince81** [comment]
:cry:

**Comment by DeepDiver1975** [comment]
> wait are there more occurences?

go go go

**Comment by butonic** [comment]
Ok, leaving out tests I think I got them all ...
```
✗ grep -r 'NotFoundException()' | grep new | grep -v coverage | grep -v Test
lib/composer/symfony/routing/Matcher/Dumper/PhpMatcherDumper.php:        throw 0 < count(\$allow) ? new MethodNotAllowedException(array_unique(\$allow)) : new ResourceNotFoundException();
```

I hope nothing breaks ... I mean ... these are exceptions ... I beg no one expects the message to be empty ...

**Comment by DeepDiver1975** [comment]
We have to be careful to not expose internal paths like the data directory full path .....

**Comment by butonic** [comment]
1. Node::path is relative to Node::root - no exposure of the full path
2. Share::target is only the filename - no exposure of the full path
3. ids - not a path
4. https://github.com/owncloud/core/pull/25950/files#diff-7d1489ffb372bce311fdb1dd50cd38b3R570 is also relative to the root storage - no exposure of the full path

@DeepDiver1975 not an issue of this PR

**Comment by DeepDiver1975** [comment]
background: it's okay to write the absolute path into the log file but we shall not expose it to the outside via http - this is considered as data leakage ....

**Comment by PVince81** [comment]
inactive: moving to backlog for now

**Pull request closed without merging**
