### PR TITLE
Avoid the restriction of having only the specific core apps enabled in apps scenario

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
This will be needed in every app running core tests.

### CODE REVIEW

**Comment by PVince81** [comment]
Ah it's this one.

How about we change the result check to be "verify that the list contains 'dav' and 'files'" just for the sake of checking if the API works.

A separate feature test could be "test that all bundled/shipped apps are enabled properly", that feature could then be excluded.

We don't need the exhaustive list here.

**Comment by SergioBertolinSG** [comment]
@PVince81 I've changed it to check if apps are included in the response. And removed the tag.

**Comment by PVince81** [comment]
Thanks.

Can you also change the sentence to say something like "these apps are included" instead of "the apps should be"

**Comment by SergioBertolinSG** [comment]
Hmm currently it says:
And apps returned are
| and a list here |

I find it right, they are returned, perhaps there are more returned also, but that is hided.

**Comment by PVince81** [comment]
Fine by me. Tests are green but unpublished.

**Pull request merged**
