### PR TITLE
Redirect properly while browsing the filelist

### PR DESCRIPTION
**Pull request by MorrisJobke**
Needs to be verified, that it solves issues, when the server responds with a redirect due to i.e. authorization token expiry.

cc @butonic

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Untested yet.

This PR is used for collaboration.

cc @CaptionF @PVince81

**Comment by danimo** [comment]
retest this please

**Comment by danimo** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@butonic the js unit test are failing to some extend - can you take care? THX

**Comment by DeepDiver1975** [comment]
Furhtermore this only helps in the files app - the issue is not fixed in case somebody has opened any other app.

**Comment by MorrisJobke** [comment]
> Furhtermore this only helps in the files app - the issue is not fixed in case somebody has opened any other app.

But this has to be fixed in these apps. I will fix the unit tests tomorrow and test this.

**Comment by MorrisJobke** [comment]
@cmonteroluque This is currently in a testing/collaboration state (to get this sorted out between @butonic and me) ;)

**Comment by DeepDiver1975** [comment]
Potential global solution:http://api.jquery.com/ajaxerror/

**Comment by butonic** [comment]
Ok, I tested this with my local testshib setup and can reproduce the issue. it seems using `statusCode` to specify handlers does not work as documented (the functions for 302 and 307 are not triggered), so I used the redirect function as the error callback. jquery treats a 30x as an error and will call the error handler. with this the app is refreshed when the shibboleth session has expired (either by timeout or lifetime).

cc @CaptionF after the redirect the user will land at the idp. depending on how long the session is valid there the user will either have to relogin at the idp or will land in the files app.

this might even be improved by redirecting directly to the current folder.

**Comment by butonic** [comment]
@danimo thx for pointing out the test installation, I had a local shibboleth setup that I just needed to dust off (as in boot linux).

**Comment by DeepDiver1975** [comment]
> jquery treats a 30x as an error and will call the error handler.

which is great as we can come up with a global solution - https://github.com/owncloud/core/pull/16726#issuecomment-108760418

@butonic let me know if you need further assistance on this - THX

**Comment by butonic** [comment]
closing in favor of https://github.com/owncloud/core/issues/16783

**Pull request closed without merging**
