### PR TITLE
[stable10] Remove S3 files external from core

### PR DESCRIPTION
**Pull request by jvillafanez**
…les_external_s3

Cherry-picked from https://github.com/owncloud/core/pull/30475

Conflicts:
```
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by them: apps/files_external/3rdparty/aws-sdk-php/Symfony/Component/EventDispatcher/Tests/ImmutableEventDispatcherTest.php
	both modified:   apps/files_external/lib/AppInfo/Application.php
	deleted by them: apps/files_external/lib/Lib/Auth/AmazonS3/AccessKey.php
	deleted by them: apps/files_external/lib/Lib/Backend/AmazonS3.php
	deleted by them: apps/files_external/lib/Lib/Storage/AmazonS3.php
	deleted by them: apps/files_external/tests/AmazonS3MigrationTest.php
	deleted by them: apps/files_external/tests/Storage/Amazons3Test.php
```
All the "deleted by them" files have been removed. The apps/files_external/lib/AppInfo/Application.php file had a conflict due to Google storage also removed from master (?). Google storage has been kept, so only amazon S3 has been removed

## Description
Remove code from core in order to use the other apps

## Related Issue
https://github.com/owncloud/enterprise/issues/3214

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by jvillafanez** [comment]
Checked manually: Amazon S3 no longer appears in the storage selection.

**Comment by PVince81** [comment]
hmmm, we haven't released said app yet.

would it be possible to only remove the vendor dependencies from the current code but leave the code as is ?

**Comment by jvillafanez** [comment]
I don't think it's possible. I'm not sure when, but I'm pretty sure the code will explode at some point. The users could still select the amazon S3 storage, so the code will explode because the library won't be found.
There could also be users accessing the storage.

**Comment by PVince81** [comment]
@jvillafanez if the library is already availble in core's "vendor" folder, shouldn't the autoloader of the app also be able to use it ? or is the current situation different ?

**Comment by jvillafanez** [comment]
I don't find any aws-related code in this branch, so I don't know where that code can come from.

**Comment by PVince81** [comment]
so we now have two choices:

1) update AWS on files_external on stable10 as the app is not fully unbundled yet

or

2) wait for app unbundling, which is currently not on the radar as it will need extra QA

**Comment by jvillafanez** [comment]
updating AWS doesn't seem easy. There are several changes to do in the code, so it won't be a clean update.

Just updating the libraries I get the following error trying to use the app:
```
{"reqId":"8C8wmz3BKN2geNbD6R4a","level":3,"time":"2019-04-16T12:30:44+00:00","remoteAddr":"10.0.2.9","user":"admin","app":"index","method":"POST","url":"\/index.php\/apps\/files_external\/globalstorages","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Undefined class constant 'COMMAND_PARAMS'\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/AmazonS3.php(541): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\AmazonS3->getConnection()\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(205): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\AmazonS3->test(false, true)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(254): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus('\\\\\\\\OCA\\\\\\\\Files_Exte...', Array, false, true)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/GlobalStoragesController.php(119): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OC\\\\Files\\\\External\\\\StorageConfig))\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->create('AmazonS3', 'amazons3', 'amazons3::acces...', Array, Array, Array, Array, 100)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#10 \\\/opt\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/AmazonS3.php\",\"Line\":574}"}
```
fixing that problem with the same code as in the files_external_s3 I get the next one:
```
{"reqId":"bFHCmT1M3xfBd3t6ziAu","level":3,"time":"2019-04-16T12:39:03+00:00","remoteAddr":"10.0.2.9","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/files_external\/globalstorages\/2?testOnly=true","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 2 passed to Aws\\\\AwsClient::getCommand() must be of the type array, string given, called in \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws\\\/aws-sdk-php\\\/src\\\/AwsClientTrait.php on line 77\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws\\\/aws-sdk-php\\\/src\\\/AwsClientTrait.php(77): Aws\\\\AwsClient->getCommand('isValidBucketNa...', 'ocbuck')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/AmazonS3.php(593): Aws\\\\AwsClient->__call('isValidBucketNa...', Array)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/AmazonS3.php(541): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\AmazonS3->getConnection()\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(205): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\AmazonS3->test(false, true)\\n#4 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(254): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus('\\\\\\\\OCA\\\\\\\\Files_Exte...', Array, false, true)\\n#5 \\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(303): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OC\\\\Files\\\\External\\\\StorageConfig), true)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Files_External\\\\Controller\\\\StoragesController->show(2, true)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 \\\/opt\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/aws\\\/aws-sdk-php\\\/src\\\/AwsClient.php\",\"Line\":228}"}
```

@PVince81 I'm not sure if we want to copy also all the code from the files_external_s3 here. Otherwise, I don't think it will be easy to update.

**Comment by PVince81** [comment]
does the app files_external_s3 already have the lib update and works fine ? as far as I know we haven't tested it yet

**Comment by jvillafanez** [comment]
> does the app files_external_s3 already have the lib update and works fine ? as far as I know we haven't tested it yet

The composer.json file I've used is the same, but the exact same version isn't: files_external's has been updated to 3.91.4 while files_external_s3 has 3.61.5.
The exact version of the aws library in stable10 is unclear because it isn't handled by composer. There are some commits claiming version 2.7.5

I've installed both versions in the same ownCloud and only the mount point with the files_external_s3 works fine.

**Comment by PVince81** [comment]
ok, so this means the files_external_s3 app actually already works. cool.

so might be better to just have it published to marketplace with the update.

can you update aws in the app instead ?

**Comment by micbar** [comment]
@jvillafanez Is there still a conflict with Google Storage?
We plan to remove it from stable10 too.

**Comment by karakayasemi** [comment]
@micbar as far I understand, @jvillafanez resolved conflict by keeping Google Storage part. I also tested Google Drive functionality in this PR. It is still working. As @jvillafanez said Amazon S3 no longer appears in the storage selection after this PR.
I guess we can merge this. After the merge, we should test files_extarnal_s3 app with stable10 branch and fill missing parts of it if any. We need QA effort to ensure files_external_s3 app properly. https://github.com/owncloud/files_external_s3 should be ready in marketplace with ownCloud server v10.3.

**Review by karakayasemi — APPROVED** [review]
Google Drive functionality is still working and Amazon S3 no longer appears in the storage selection after this PR. All tests are also passing. LGTM 👍

**Comment by jvillafanez** [comment]
I don't remember if the app in core and the one in the repo have the same storage id. If it's different, I'm not sure what we want to do, because they'll have to resync the whole storage after the app change

**Comment by karakayasemi** [comment]
https://github.com/owncloud/enterprise/issues/3214#issuecomment-500314795 according to your comment, they have different storage ids. 
As a next step, we need to write a migration config/command to prevent re-sync described in here: https://github.com/owncloud/enterprise/issues/3214#issuecomment-502153275.

**Comment by phil-davis** [comment]
@micbar @DeepDiver1975 and anybody else. This is all green for merge, making it tempting to press the button ;)
Any reason not to merge it for 10.3 ?

**Pull request merged**
