### PR TITLE
[3rdparty] Bump symfony/polyfill-php* to 1.1.0

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/254

It is time to get our depenencies a bit more up to date again!

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by rullzer** [comment]
Rebased

**Comment by rullzer** [comment]
Rebased to get a run with php5.4

**Comment by rullzer** [comment]
@DeepDiver1975 I think this is ready to merge

**Pull request merged**
