### PR TITLE
Use chunking in web upload

### LINKED ISSUE #8955: Web Based File Upload Chunking
### Steps to reproduce

Web based large file upload
### Expected behaviour

File gets chunked and multiple ajax requests send the chunks to the server for reassembly
### Actual behaviour

File is uploaded as a whole file. A single request is made
### Server configuration

**Operating system**: RHEL 6

**Web server:** NGINX

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:**  6.0.3

**Updated from an older ownCloud or fresh install:**

**List of activated apps:** Files, Activity, Contacts, Pictures

**The content of config/config.php:**

I had to remove the identifying URLs so it seems a little empty.

```
<?php
$CONFIG = array (
  'instanceid' => 'oc8fdcdb7be6',
  'passwordsalt' => '',
  'datadirectory' => '/var/www/html/macdrop_assets',
  'dbtype' => 'mysql',
  'version' => '6.0.3.1',
  'dbname' => '',
  'dbhost' => '',
  'dbtableprefix' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'theme' => 'macdrop',
  'proxy' => '',
  'loglevel' => '2',
  'maxZipInputSize' => 1073741824,
  'allowZipDownload' => true,
  'mail_domain' => '',
  'mail_smtphost' => '',
  'mail_smtpname' => 'macDrop',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'url1',
    1 => 'url2',
  ),
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
### Client configuration

**Browser:** Chrome

**Operating system:** Windows
#### Browser log

This is a 1.7GB file. One request taking 3.2 minutes.
no_chunk

If this feature does not exist I am willing to look into implementing it and making a pull request.

### PR DESCRIPTION
**Pull request by PVince81**
## Description

Switch on chunking for files bigger than 10 MB.
Some additional fixes to make it use the correct URL/client.
## Related Issue

Fixes https://github.com/owncloud/core/issues/8955
## Motivation and Context

Makes it possible to avoid timeouts when uploading bigger files.
Might also make it resumable (still to be tested)
## How Has This Been Tested?

For all tests, check the network console:
- [x] TEST: upload small file, no chunking endpoint used
- [x] TEST: upload file bigger than 10 MB, see chunking endpoint used, multiple call mades followed by final MOVE. Then file appears in the UI.
- [x] TEST: chunking not enabled for public upload even for big files
- [x] TEST: with IE11 which is one of the main reasons for this fix
- [x] TEST: upload + overwrite
- [x] TEST: mtime preserved on chunked upload
- [x] TEST: uploads transfer folder is deleted in case of error or abort (you can see a DELETE call happening at the end)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
### Important note
jquery blueimp doesn't support parallel uploading of chunks, so the chunks are always uploaded sequentially. This isn't too bad as it still brings the benefit of avoiding timeouts.
In the future we should look into using a different library (ex: resumable.js) and/or implement the chunking algo by ourselves.

**Comment by DeepDiver1975** [comment]
tested - works :+1:

**Comment by PVince81** [comment]
- [ ] BUG: simulating a failed upload triggers the global ajax error handlers which causes a full page reload

**Comment by PVince81** [comment]
Hmm this is tricky because if you test it by making the server unavailable, there are other ajax calls (notifications, getstoragestats) that will fail too.

I tried disabling the reload and it seems that jquery.fileupload doesn't automatically resume.

**Comment by michaelstingl** [comment]
@PVince81 I need confirmation that this will work in IE11. How could I verify this asap?

**Comment by butonic** [comment]
When the connection is closed the Response status is 0, which triggers the reload. Reloading on Status = 0 was introduced with https://github.com/owncloud/core/pull/16783#issuecomment-111135129 because of a missing Access-Control-Allow-Origin header on the IdP. The proper fix is to make the IdP send this header.

While we currently cannot detect an abort we might ba able to configure mod_shib to send 403 forbidden for xhr requests. That is what mod_mellon does:  https://github.com/UNINETT/mod_auth_mellon/blob/master/README#L169-L173

Either test mod_mellon or try to make apache send 403 responses when no shibboleth session is present for xhr requests (X-Request-With: XMLHttpRequest). The latter might be very tricky ...

see https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
see http://charliedigital.com/2015/07/17/adventures-in-single-sign-on-cross-domain-script-request/
see https://github.com/monmohan/cors-experiment/blob/master/docs/CORS.md

**Comment by butonic** [comment]
That being said ... I can live with the page refreshing too often... I cannot live with IE11 failing to upload files >2.2GB.

**Comment by michaelstingl** [comment]
Upload with 32-bit IE11 worked well (In my example 2.281.105.750 bytes). Progress bar shows very wrong estimated values in the range from days to seconds. It took some time after the progress bar disappeared and the file appeared.

**Comment by butonic** [comment]
Tested in IE11:
ie11 chunks

Backport to 9.1 upcoming

**Comment by butonic** [comment]
tested with 4.6GB \o/ @PVince81 is awesome!

**Comment by PVince81** [comment]
There's a potential bug, see the discussion here https://github.com/owncloud/client/pull/5476#issuecomment-273711366.

Need to make sure that the uploaded chunk names are ascii-sortable in the correct order to avoid corruption because the endpoint expects this.

**Comment by PVince81** [comment]
- [ ] make sure the chunks have the proper order

**Comment by PVince81** [comment]
- [ ] might require a final DELETE, see https://github.com/owncloud/core/issues/26981

**Comment by PVince81** [comment]
- [ ] DELETE transaction if the user cancels

**Comment by PVince81** [comment]
- [ ] BUG: no progress shown during final move

At this stage no progress can be shown because the transfer already ended. So one idea would be to already insert the entry into the file list but let it appear with a spinner.

**Comment by PVince81** [comment]
If we had a good solution to get rid of the IDP "status=0" fail detection it would be great, because that check is messing up with more stuff. https://github.com/owncloud/core/pull/26306#issuecomment-273512544

**Comment by PVince81** [comment]
- [ ] BUG: cannot work on public link page because the "uploads" endpoint only accepts logged in sessions.

Will need further work there.
This also means that anonymous upload with chunking will not work either.

**Comment by PVince81** [comment]
> cannot work on public link page because the "uploads" endpoint only accepts logged in sessions.

this is a major blocker. Need to talk with @DeepDiver1975 how to redesign the DAV endpoints to allow public access

**Comment by PVince81** [comment]
Let's finish this without the public link part then.

**Comment by felixboehm** [comment]
Still any blockers?

Open separat issue for discussion on public link?

**Comment by PVince81** [comment]
No blocker, just need to find time to finish this...

The biggest missing bit now is error handling in case of abort.

**Comment by mmattel** [comment]
@PVince81 Thanks in advance and :+1:

**Comment by PVince81** [comment]
Giving up on trying to make it retry chunks. This jquery.fileupload lib is really painful to use.
For example it triggers the upload "fail" event before the "chunkfail" event and resuming doesn't seem to work with this workflow. I'm sure that if we invest enough time we might be able to find the right code gymnastics to make it work properly...
Another challenge is detecting whether the 500 returned by the server is actually a timeout error and we should try resuming or whether it's a legit error and we need to abort.

But for now let's focus on getting this merged. The main purpose for now is to make it possible to upload files bigger than 2 GB in IE11.

**Comment by PVince81** [comment]
- [ ] BUG: progress bar disappears too early while the final MOVE is in progress

This would also require hacking around jquery.fileupload since that one thinks we're already done since the last chunk was uploaded already... The lib isn't really compatible, too much hacking... Maybe one day we should find another lib or develop our own.

**Comment by PVince81** [comment]
Jenkins is kaputt:
```
12:57:30 ERROR: Error fetching remote repo 'origin'
12:57:30 hudson.plugins.git.GitException: Failed to fetch from https://github.com/owncloud/core.git
```

Resent PR separately: https://github.com/owncloud/core/pull/28415

**Pull request closed without merging**
