### PR TITLE
Enable unit tests for files_external for autotest.sh

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
I've enabled the common unit tests for files_external in autotest.sh. This means we test the core functionality of files_external in CI. To accomplish this, I've augmented the way we gather test files, by checking for the suffix '.noauto' on a directory or '.noauto.php' on a test file, and not including the test/directory if it contains that. This way, we can exclude parts of a test suite, like the backend tests for files_external, which are otherwise unavailable on CI. Running them manually is always available, of course.

In addition, I've noticed a partial regression in the files_external unit tests. Since #10673, simply creating an SMB storage backend attempts to create a connection to the server. As some unit tests used the SMB backend as a reference storage, this meant that the unit tests attempted to create connections to a (non-existent) SMB server, slowing everything down and printing unnecessary logs. I've replaced all references to real storage backends with the dummy ones available in the `mountconfig.php` test file (which now extends \OC\Files\Storage\Common). I suppose we'd have noticed this if CI was testing files_external... :speak_no_evil: 

@MorrisJobke Please give your `autotest-external.sh` a good test to make sure I haven't broken anything :smile:

cc @icewind1991 @LukasReschke @DeepDiver1975 @MorrisJobke @PVince81

### CODE REVIEW

**Comment by Xenopathic** [comment]
Looks like one of the AmazonS3Migration unit tests is failing. Looks like this PR is doing its job!

**Comment by MorrisJobke** [comment]
@Xenopathic Yes. They are also failing in the dedicated files_external unit tests ;)

**Comment by DeepDiver1975** [comment]
@Xenopathic this is exactly the kind of hack I'd love to NOT have time invested - on all of us

**Comment by Xenopathic** [comment]
@DeepDiver1975 Is that the .noauto bit that you are referring to? I thought about moving the backend tests to a different directory entirely (tests-backend or something) but I thought this would be a better idea.

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
@DeepDiver1975 BTW, this PR is expected to fail tests, since one of the AmazonS3Migration tests is currently failing. As long as it's only that test failing though, this PR is successful.

**Comment by DeepDiver1975** [comment]
> this PR is expected to fail tests, since one of the AmazonS3Migration tests is currently failing.

can you add a fix to this PR for this issue? Otherwise any other PR will fail after merging - THX

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
OK, I've stripped out the unnecessary commits pulled in by #14675 . @DeepDiver1975 What are your thoughts on this approach - you said you weren't happy with the hack before but didn't really elaborate. @MorrisJobke what are your thoughts as well?

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
@DeepDiver1975 What do you think of this?

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @Xenopathic ping ... if this is valid a rebase is needed

**Comment by PVince81** [comment]
We now have ./autotest-external.sh which runs the backends against docker instances and also runs the class tests from the files_external app.

I guess we don't need this hack any more ?

**Comment by Xenopathic** [comment]
@PVince81 This PR runs the 'common' files_external unit tests, aka the ones that test OC_Mount_Config, the Services, etc. Not the actual backends. It would be really useful to have those unit tested by CI.

**Comment by PVince81** [comment]
These common tests are also run by ./autotest-external.sh which is run on CI.
They run on master and stable branches, but not in the PR analyzer.
I think that's already enough. (we caught a SMB issue recently thanks to that)

**Comment by Xenopathic** [comment]
Ah, I didn't realise we have CI testing of autotest-external.sh. I guess that makes this redundant :smile:

**Pull request closed without merging**
