### PR TITLE
check disabled user on apache auth, expose as proper exception to end user

### PR DESCRIPTION
**Pull request by butonic**
cc @tomneedham

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase was successful!

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
fix le coverage?

**Comment by PVince81** [comment]
any update ? there's also a conflict now

**Comment by DeepDiver1975** [comment]
@tomneedham @butonic please reopen if still of interest - THX

**Comment by butonic** [comment]
superseded by https://github.com/owncloud/core/pull/29669/files#diff-c0c524d903241b79ce3d82c9f290e8e2R181 which will throw the exception when a user has been disabled as well.

**Comment by phil-davis** [comment]
Removed backport label, since that is not relevant for this PR any more.

**Pull request closed without merging**
