### PR TITLE
UI tests - encode special char when using User Provisioning API

### PR DESCRIPTION
**Pull request by individual-it**
## Description
sending data in the path to the User Provisioning API requires some char to be encoded

## Motivation and Context
we want be able to create/delete etc. groups with char like "&/#" in the name from UI tests

## How Has This Been Tested?
travis will tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
It breaks integration-API tests that actually use real "?" etc URLs.

**Comment by individual-it** [comment]
true, it does not make sense to encode the complete path. moved encoding a level higher up.

other requests use POST, so no need to encode there and user names cannot have any of this characters anyway

**Review by phil-davis — APPROVED** [review]
assuming CI passes.

**Comment by individual-it** [comment]
backport in #30010

**Pull request merged**
