### PR TITLE
Add occ commands to manager trusted certificates

### PR DESCRIPTION
**Pull request by icewind1991**
- [x] Depends on https://github.com/owncloud/core/pull/21336 for system wide cert stuff
- `oc security:certificates` list trusted certificates
- `oc security:certificates:import` add a trusted certificate
- `oc security:certificates:remove` remove a trusted certificate

manage certificates

Proper diff is https://github.com/owncloud/core/commit/29206df1266776d60d7a33a508d6e378012d53f1 rest is part of #21336

cc @LukasReschke @PVince81

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
````
.PHP Fatal error:  Uncaught TypeError: Argument 4 passed to OC\Settings\Controller\CertificateController::__construct() must implement interface OCP\ICertificateManager, instance of Mock_IL10N_6f0eb89c given in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/settings/controller/certificatecontroller.php:55
00:00:36.189 Stack trace:
00:00:36.189 #0 [internal function]: OC\Settings\Controller\CertificateController->__construct('settings', Object(Mock_IRequest_f377dbf5), Object(Mock_ICertificateManager_45f09e98), Object(Mock_IL10N_6f0eb89c), Object(Mock_IAppManager_26f5b782))
00:00:36.189 #1 phar:///usr/local/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php(257): ReflectionClass->newInstanceArgs(Array)
00:00:36.189 #2 phar:///usr/local/bin/phpunit/phpunit-mock-objects/Framework/MockObject/Generator.php(225): PHPUnit_Framework_MockObject_Generator->getObject('class Mock_Cert...', 'Mock_Certificat...', 'OC\\Settings\\Con...', true, true, Array, false, NULL)
00:00:36.189 #3 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(1259): PHPUnit in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/settings/controller/certificatecontroller.php on line 55

**Comment by PVince81** [comment]
@icewind1991 looks like tests still fail ?

**Comment by DeepDiver1975** [comment]
rebased after merge of  #21336

**Comment by DeepDiver1975** [comment]
:+1: tested

**Comment by DeepDiver1975** [comment]
@LukasReschke please have a look - THX

**Comment by icewind1991** [comment]
@LukasReschke *poke*

@PVince81 maybe

**Comment by LukasReschke** [comment]
Works :+1:

**Pull request merged**
