### PR TITLE
Move alt text for favorite action to image

### LINKED ISSUE #19286: Accessibility of 'favorite button', alternative text is not provided for the image that is the only thing within a link.
### Steps to reproduce

1. Login ownCloud.
2. Click on share button (Sidebar is shown)

### Expected behaviour
An alternative text should be provided for 'favorite button' due to it is a image that is the only thing within a link.

### Actual behaviour

An alternative text is not provided for 'favorite' image.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 Firefox.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/19286

@davitol please verify

@MorrisJobke @rullzer @blizzz

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works here :+1:

**Comment by karlitschek** [comment]
nice :+1:

**Comment by rullzer** [comment]
:+1:

**Comment by davitol** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@PVince81 Please create the backport for 8.2.1

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19772

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
