### PR TITLE
preLogin hook should use string UID not IUser

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
Everywhere else, `preLogin` uses string UID as the first param - this causes plugins to 💥 

## Related Issue
Found whilst debugging portal.

## Motivation and Context
Broken plugins / inconsistency.

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
changing this could break existing plugins, unless this event is so new that it is unlikely that new plugins use it

**Comment by PVince81** [comment]
@sharidas please clarify if this was introduced in recent code or was released before to evaluate if this change will break anything...

**Comment by tomneedham** [comment]
It was always string - got changed when it was converted to symfony event

**Comment by PVince81** [comment]
assigning @sharidas to do the needed research

**Comment by sharidas** [comment]
Grepped through apps:
- password_policy
- encryption
- audit
- guest
- activity
- splunk

Couldn't find place where the signal 'preLogin' is listened to other than in lib/private/Server.php. Hence I believe we can safely take this change.

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
@sharidas was this event released before or not ?

Depending on this it could become more urgent to fix it or revert it before people start using it.

**Comment by sharidas** [comment]
Updated the tests and now they do pass. @PVince81

**Comment by sharidas** [comment]
Backport PR to stable10 branch : https://github.com/owncloud/core/pull/32563

**Comment by sharidas** [comment]
> was this event released before or not ?

No I believe this was not released.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
we should revert this, see https://github.com/owncloud/core/pull/32563#issuecomment-418398956

information was incomplete and this event already existed before, so changing it would break API

**Comment by PVince81** [comment]
@sharidas please revert

**Comment by sharidas** [comment]
Reverted PR : https://github.com/owncloud/core/pull/32642

**Pull request merged**
