### PR TITLE
Update some JS dependencies

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @DeepDiver1975 @PVince81 @rullzer 

It's only backbone. Bootstrap was only a version number bump for the tooltip library.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
These are the low hanging fruits of https://www.versioneye.com/user/projects/54f4a2384f3108959a000a16#tab-dependencies

**Comment by blizzz** [comment]
> These are the low hanging fruits of https://www.versioneye.com/user/projects/54f4a2384f3108959a000a16#tab-dependencies

Whatever that link is,  the doorman won't let me in without registering.

**Comment by blizzz** [comment]
:+1: sidebar (and sharing) continue to work

**Comment by MorrisJobke** [comment]
> Whatever that link is, the doorman won't let me in without registering.

Okay...it says in the settings that this is a "public" project.

**Comment by Henni** [comment]
:+1: tooltips still work (bootstrap)

**Pull request merged**
