### PR TITLE
Register type mappings on createSchema invocation too

### LINKED ISSUE #29262: Type mappings are not applied to platform when using migrations
Basically https://github.com/owncloud/core/issues/9806.  Now for migrations only.

### Steps to reproduce
1. Install OC with MySQL
2. Execute `CREATE TABLE `oc__enum_bit_test5kBmyPCe0uejl` (
  `b` bit(1) DEFAULT NULL,
  `e` enum('1','2','3','4') COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin`
3. Create a `ISchemaMigration` for any app, bump app version
4. php occ upgrade

### Expected behaviour
upgrade

### Actual behaviour
```
2017-10-16T17:04:18+00:00 Doctrine\DBAL\DBALException: Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.                                                                                                                         
2017-10-16T17:04:18+00:00 Update failed

```

### Server configuration
**Database:**
mysql-community-server-5.6.37

**ownCloud version:** (see ownCloud admin page)
master

**Where did you install ownCloud from:**
git

```
{"reqId":"ag43VC4s1MjXyv6d29EM","level":3,"time":"2017-10-16T16:10:00+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Exception: {"Exception":"Doctrine\DBAL\DBALException","Message":"Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.","Code":0,"Trace":"
#0 /lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php(126): Doctrine\DBAL\Platforms\AbstractPlatform->getDoctrineTypeMapping('bit')
#1 /lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(820): Doctrine\DBAL\Schema\MySqlSchemaManager->_getPortableTableColumnDefinition(Array)
#2 /lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(175): Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList('oc__enum_bit_te...', 'octmp_mysql', Array)
#3 /lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(281): Doctrine\DBAL\Schema\AbstractSchemaManager->listTableColumns('oc__enum_bit_te...')
#4 /lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(268): Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails('oc__enum_bit_te...')
#5 /lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(1040): Doctrine\DBAL\Schema\AbstractSchemaManager->listTables()
#6 /lib/private/DB/Migrator.php(139): Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema()
#7 /lib/private/DB/Connection.php(413): OC\DB\Migrator->createSchema()
#8 /lib/private/DB/MigrationService.php(400): OC\DB\Connection->createSchema()
#9 /lib/private/DB/MigrationService.php(358): OC\DB\MigrationService->executeStep(20170927201245)
#10 /lib/private/legacy/app.php(1074): OC\DB\MigrationService->migrate()
#11 /lib/private/Updater.php(307): OC_App::updateApp('dav')
#12 /lib/private/Updater.php(233): OC\Updater->doAppUpgrade()
#13 /lib/private/Updater.php(108): OC\Updater->doUpgrade('10.0.3.3', '10.0.3.3')
#14 /core/Command/Upgrade.php(254): OC\Updater->upgrade()
#15 /lib/composer/symfony/console/Command/Command.php(264): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /lib/composer/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /lib/composer/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /lib/composer/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /lib/private/Console/Application.php(162): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /console.php(106): OC\Console\Application->run()
#21 /occ(11): require_once('/home/deo/publi...')
#22 {main}","File":"/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php","Line":423}"}
```

Hint: https://github.com/owncloud/core/commit/7d60f7a2220d0c7f4dbdd4bdd9d765cfbd64e4ab#diff-054ef00831a177b931682ea3550da06b

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
Register type mappings for MigrationService too

## Related Issue
Fixes #29262 

## Motivation and Context
Smooth Upgrade process

## How Has This Been Tested?
Manually. See exact steps in #29262

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by VicDeo** [comment]
One source was indented with spaces, so https://github.com/owncloud/core/pull/29263/files?w=1 is better to see what's changed

**Comment by VicDeo** [comment]
hmmm. should I revert tabs to spaces to satisfy that beasty mech ego? 
`registerAdditionalMappings` and `createSchema` are covered in both classes, so the diff has coverage that is close to 100% in my Universe

**Review by PVince81 — COMMENTED** [review]
Add test to assert that the MySQL migrator did register additional type mappings ?

**Comment by VicDeo** [comment]
@PVince81 try to comment https://github.com/owncloud/core/pull/29263/files#diff-f31830e77645a4634cf4f0258e1a3272R35
and execute `MySqlMigrationTest::testCreateSchemaWithNonOcTables`

**Comment by PVince81** [comment]
@VicDeo explain that to codecov 😦

**Comment by VicDeo** [comment]
@PVince81 I have a strong impression that it counts coverage using sqlite only

**Comment by PVince81** [comment]
@DeepDiver1975 ignore codecov here then ?

**Comment by VicDeo** [comment]
The truth is that 
- these two lines are now covered by tests:
https://github.com/owncloud/core/pull/29263/files#diff-58177c1fd3826cc2a9f1f8e5b4736d7dR91
https://github.com/owncloud/core/pull/29263/files#diff-1f3942e6e76594e802a7eb628c067f76R33

- changes in  lib/private/DB/MySQLMigrator.php are 100% covered by tests/lib/DB/MySqlMigrationTest.php
- changes in  lib/private/DB/SQLiteMigrator.php are 100% covered by tests/lib/DB/SqliteMigrationTest.php

**Comment by PVince81** [comment]
@VicDeo please backport to stable10

**Comment by VicDeo** [comment]
Without whitespaces 2/49 = 0.04081632653061224, so the coverage is 96%
With whitespaces it is 20/69 = 0.2898550724637681 and the coverage is 71%

**Comment by VicDeo** [comment]
Stable10: https://github.com/owncloud/core/pull/29268

**Pull request merged**
