### PR TITLE
Register DAVACL plugin to provide current-user-principal

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@dmfs this will bring back the current-user-principal

``` sh
$ curl -k -X PROPFIND -H "content-type: application/xml" -u admin:admin --data-binary '<?xml version="1.0" encoding="UTF-8"?><A:propfind xmlns:A="DAV:"><A:prop><A:current-user-principal/><A:resourcetype/></A:prop></A:propfind>' -H "Depth: 0" http://localhost:8080/remote.php/dav/ | xmllint --format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   545    0   406  100   139   1553    531 --:--:-- --:--:-- --:--:--  1549
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <d:response>
    <d:href>/remote.php/dav/</d:href>
    <d:propstat>
      <d:prop>
        <d:current-user-principal>
          <d:href>/remote.php/dav/principals/admin/</d:href>
        </d:current-user-principal>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG we need to talk about integration tests for the webdav interface.

Current idea:
- create a new behat driven test suite within t apps/dav/tests

**Comment by dmfs** [comment]
@DeepDiver1975 looks good. Can you update the test instance accordingly, so I can test again?

Also have a look at [CalDAVTester](http://calendarserver.org/wiki/CalDAVTester) for testing. Many of the server folks at CalConnect use that to test their implementations.

**Comment by DeepDiver1975** [comment]
> Also have a look at CalDAVTester for testing. Many of the server folks at CalConnect use that to test their implementations.

#20195 - already on that ;-)

**Comment by rullzer** [comment]
:+1: works :)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 looks good. Can you update the test instance accordingly, so I can test again?

updated - have fun

**Comment by dmfs** [comment]
yeah, principal discovery looks good now. I guess you've created another ticket for addressbook-home-set?!

**Comment by DeepDiver1975** [comment]
> yeah, principal discovery looks good now

Great



> I guess you've created another ticket for addressbook-home-set?!

will come asap :wink:

**Comment by DeepDiver1975** [comment]
> yeah, principal discovery looks good now.

treated as :+1:

**Pull request merged**
