### PR TITLE
Add visual cue when moving draggable item over droppable item,

### PR DESCRIPTION
**Pull request by pellaeon**
ie. breadcrumb and filenameTd

The style on breadcrumb might need tweaking.

Solves #10369

### CODE REVIEW

**Comment by karlitschek** [comment]
very nice. thanks for the pull request :-)
@PVince81 @jancborchardt what do you think?

**Comment by MorrisJobke** [comment]
@pellaeon I can't find any visual changes, when testing with chrome. Can you maybe add some screenshots? Maybe I just tried the wrong stuff ;)

**Comment by pellaeon** [comment]
@MorrisJobke 
Drag an item over a folder


Drag an item over breadcrumb

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by PVince81** [comment]
@jancborchardt do you like this highlight ?

**Comment by jancborchardt** [comment]
The color of the highlight should be the same that is used for when an upload is successfully finished. And that shade of yellow should be defined centrally so we can pull it as highlightcolor and change it in one place.

**Comment by pellaeon** [comment]
It is the same color, copied from https://github.com/owncloud/core/blob/master/apps/files/css/upload.css#L171 .

I don't know how to define it centrally.

**Comment by PVince81** [comment]
- [ ] the hover should cover the whole row, now only the files row ? @jancborchardt 

Tested, functionally it works.

**Comment by jancborchardt** [comment]
Yeah, the style should cover the whole row. We can adjust the exact color later.

**Comment by PVince81** [comment]
@pellaeon can you change it to cover the whole row ?

**Comment by pellaeon** [comment]
@PVince81 it now covers the whole row, also making the whole row droppable.
highlight_entire_row

**Comment by PVince81** [comment]
Looks good to me, JS unit tests pass locally :+1: 

Merge ? @MorrisJobke @jancborchardt @rullzer @nickvergessen

**Comment by MorrisJobke** [comment]
This has conflicts :(

Generally I like this, but maybe we want to use a not that aggressive color. But that could be addressed in an additional PR. cc @owncloud/designers 

@pellaeon Could you rebase and resolve the conflicts? Then we could merge this :)

**Comment by skjnldsv** [comment]
I wanted to propose some kind of striped background, but the css is goind wild.
I applied it to the tr, and all the td are disrupting the background, I never saw that! :/
capture d ecran_2016-05-14_10-42-28

**Comment by pellaeon** [comment]
@MorrisJobke rebased!

**Comment by skjnldsv** [comment]
Ok, apparently, my stripped background problem is a webkit issue. It work fine on other browsers.
Should we goo for it? I like it. :)

**Comment by PVince81** [comment]
@skjnldsv I'd rather vote against it, at least for now. Maybe reconsider striping all the things for 9.2 ?

Goal is to get this PR here merged soon.

**Comment by skjnldsv** [comment]
@PVince81 Yep, let's merge! :)

**Comment by PVince81** [comment]
@skjnldsv counting your comment as a :+1:

**Comment by PVince81** [comment]
JS unit tests still passed locally, merging

**Pull request merged**
