### PR TITLE
use background image for log in view

### PR DESCRIPTION
**Pull request by jancborchardt**
Experimenting a bit with this. cc @karlitschek @owncloud/designers what do you think?
background1capture du 2016-04-14 12-25-47capture du 2016-04-14 12-32-01

The goal is to make ownCloud more friendly and approachable, instead of the current elegant but very bland log in view. We could change the default image a bit with every release, kind of like background wallpapers of Ubuntu, GNOME, OS X etc.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Also works nicely in the error/warning views:
capture du 2016-04-14 12-53-02

**Comment by enoch85** [comment]
This can be done on the theme already. Shouldn't it go there?

**Comment by skjnldsv** [comment]
Excellent idea! :)
:+1: :+1: :+1:

**Comment by DeepDiver1975** [comment]
Nice! I like it!

Regarding the image - let's do some community poll thingy with this - let people submit ideas and finally the community decides.

We can do this as a recurring event for each release.

@jospoortvliet @karlitschek

**Comment by jancborchardt** [comment]
For the first iteration I would actually provide a picture from us, to warm people up to the idea and to keep it in line with the theme of »ownCloud«. The picture provided is actually by @karlitschek and we talked about this already.

**Comment by georgehrke** [comment]
I really like it! :)

**Comment by karlitschek** [comment]
yes. I think a community poll is a great idea. But also start with a good starting point first is also makes sense. Should be disabled in the EE of course.

**Comment by karlitschek** [comment]
about the pictures: Not sure you are serious about the cows? ;-)
I like the other two. Maybe the dark one from Paris is a bit too depressive. 
The first one is fine but I don't want to comment on that because I can't judge objectively. ;-)

**Comment by DeepDiver1975** [comment]
> I like the other two. Maybe the dark one from Paris is a bit too depressive.
> The first one is fine but I don't want to comment on that because I can't judge objectively. ;-)

the first is a bit too bright for my understanding - and yes Paris it a bit too dark.
Can we tweak the pics?

**Comment by cdamken** [comment]
Müüühh-cloud :+1:  I like the cows :smile:

**Comment by cdamken** [comment]
I think Frank have a lot of really nice pictures, could be them set in a rotation.. for example every X minutes :)

**Comment by DeepDiver1975** [comment]
@jancborchardt do we require tests on all supported browser if this works as designed or if the used css/html magic from the 80s? :laughing:

**Comment by jancborchardt** [comment]
The different pictures are just there as examples of how this will work in the future with potentially different pictures. The cloud/mountains picture is the one in this pull request and the one we should go for.

I would say we should merge and any potential edge-cases can be fixed going forward. Let’s iterate fast.

**Comment by jospoortvliet** [comment]
I vote for grabbing a random image from the web. THAT will create some fun conversations and screenshots for sure ;-)

But hey, nice idea!

**Comment by jancborchardt** [comment]
Well another idea was to grab a random image from the ownCloud instance itself ;D

**Comment by DeepDiver1975** [comment]
> Well another idea was to grab a random image from the ownCloud instance itself ;D

Please do not leak my private images used for adult entertainment .....

**Comment by DeepDiver1975** [comment]
... ooops :wink:

**Pull request merged**
