### PR TITLE
[stable10] unit test files_primary_s3 on core

### PR DESCRIPTION
**Pull request by patrickjahns**
## Description
port of https://github.com/owncloud/core/pull/31635/commits/4950f87bbbc83a479c66a7027e1ab47699ed6b44 

better approach then what is done in master already - would forward port the changes then again

## Motivation and Context
Test files_primary_s3 during PRs so changes to not necessarily break objectstorage integration 

## How Has This Been Tested?
🤖 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mmattel** [comment]
@patrickjahns mind to add [stable10] in the headline 😄

**Comment by phil-davis** [comment]
A couple of drone jobs barfed. I will restart drone for this...

**Comment by patrickjahns** [comment]
@DeepDiver1975 
```
1) Test\Files\ObjectStore\SwiftTest::testStat
Undefined index: url
```

are they relevant to be tested with `files_primary_s3` ?

**Comment by DeepDiver1975** [comment]
> are they relevant to be tested with files_primary_s3 ?

I have a look ....

**Comment by DeepDiver1975** [comment]
ok - SwiftTest is not supposed to be executed on s3 - we removed the file in the past when running on s3

**Comment by DeepDiver1975** [comment]
pushed a commit to mark swift as skipped if not running on swift storage

**Comment by patrickjahns** [comment]
@DeepDiver1975 - LGTM - approve and merge?

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
Added ``backport-request`` which is really forwardport-request.
I noticed this while comparing ``master`` and ``stable10`` ``.drone.yml`` for #34050 
I will forward port stuff from here to get drone in ``master`` more like ``stable10``

**Comment by phil-davis** [comment]
@patrickjahns ping ^

**Comment by phil-davis** [comment]
@patrickjahns ping again ^^ - anything to forward port still?

**Pull request merged**
