### PR TITLE
[stable9.1] LDAP replica working as expected

### PR DESCRIPTION
**Pull request by jvillafanez**
## Related Issue
https://github.com/owncloud/core/issues/27575

## How Has This Been Tested?
Manually tested as described in the issue

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
@butonic can you help review ?

**Comment by jvillafanez** [comment]
Notes for reviewers and testers:
* Removed weird recursion -> I'm not sure how can affect to code outside of the bug
* Low code quality which could lead to confusion (not sure how to solve it without rewriting half of the file):
    - Checking `ldap->isResource` when the `doConnect` should already do that
    - I'm not sure how many times the code might be binding to LDAP.
* The change affects to a public function that was recursive and had static variables now removed. I'm not sure how the change could affect to other code

**Comment by PVince81** [comment]
@jvillafanez will need a forward port as well ?

@tomneedham can you review ?

**Comment by jvillafanez** [comment]
Port to 10 is needed. I'm not sure about the backport to 9.0

**Comment by PVince81** [comment]
moving to "planned" for next release. Please make sure it's reviewed and read for merge by then.

**Comment by PVince81** [comment]
@jvillafanez can you forward port to 10 / user_ldap app ?

**Comment by jvillafanez** [comment]
Ported in https://github.com/owncloud/user_ldap/pull/138

**Comment by PVince81** [comment]
@jvillafanez rebase for CI ?

**Comment by jvillafanez** [comment]
rebased

**Comment by jvillafanez** [comment]
ping for review

**Comment by tomneedham** [comment]
Reviewing....

**Comment by jvillafanez** [comment]
Maybe we can close this and bring the master code

**Comment by tomneedham** [comment]
Verified the issue, PR fixes the issue.

**Comment by butonic** [comment]
closing in favor of #29593

**Pull request closed without merging**
