### PR TITLE
Check imagecreate*() return before using and use logger in \OC_Image

### PR DESCRIPTION
**Pull request by DeepDiver1975**
followup of https://github.com/owncloud/core/pull/11096

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I backported just the fix to stable7:

stable7 8778af6

@DeepDiver1975 @karlitschek What about backporting the fix to stable6 which was requested by @cdamken ?

**Comment by karlitschek** [comment]
@MorrisJobke Please backport. Thanks :-)

**Comment by MorrisJobke** [comment]
stable6 441cdcc

**Comment by MorrisJobke** [comment]
@cdamken the fix will be in 6.0.7

**Pull request merged**
