### PR TITLE
Use flysystem for the ftp backend

### PR DESCRIPTION
**Pull request by icewind1991**
Our current ftp backend has some issues (not passing all unit tests, mostly unmaintained).

This switches the ftp backend to use flysystem which is done by introducing a wrapper to make flysystem compatible with our storage system.

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
also CC @Xenopathic

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by LukasReschke** [comment]
Not sure why, doesn't work. Same config work fine on master:

```
Array
(
    [Exception] => Array
        (
            [Message] => File not found at path: 
            [Code] => 0
            [Trace] => #0 /Users/lreschke/Programming/owncloud/master/apps/files_external/3rdparty/league/flysystem/src/Filesystem.php(480): League\Flysystem\Filesystem->assertPresent('')
#1 /Users/lreschke/Programming/owncloud/master/apps/files_external/3rdparty/league/flysystem/src/Plugin/GetWithMetadata.php(31): League\Flysystem\Filesystem->getMetadata('')
#2 [internal function]: League\Flysystem\Plugin\GetWithMetadata->handle('', Array)
#3 /Users/lreschke/Programming/owncloud/master/apps/files_external/3rdparty/league/flysystem/src/Plugin/PluggableTrait.php(66): call_user_func_array(Array, Array)
#4 /Users/lreschke/Programming/owncloud/master/apps/files_external/3rdparty/league/flysystem/src/Filesystem.php(564): League\Flysystem\Filesystem->invokePlugin('getWithMetadata', Array, Object(League\Flysystem\Filesystem))
#5 /Users/lreschke/Programming/owncloud/master/apps/files_external/lib/flysystem.php(157): League\Flysystem\Filesystem->__call('getWithMetadata', Array)
#6 /Users/lreschke/Programming/owncloud/master/apps/files_external/lib/flysystem.php(157): League\Flysystem\Filesystem->getWithMetadata('', Array)
#7 /Users/lreschke/Programming/owncloud/master/lib/private/files/storage/common.php(419): OCA\Files_External\Flysystem->stat('')
#8 /Users/lreschke/Programming/owncloud/master/apps/files_external/lib/config.php(463): OC\Files\Storage\Common->test(false)
#9 /Users/lreschke/Programming/owncloud/master/apps/files_external/lib/config.php(545): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)
#10 /Users/lreschke/Programming/owncloud/master/apps/files_external/ajax/addMountPoint.php(46): OC_Mount_Config::addMountPoint('FTP', '\\OC\\Files\\Stora...', Array, 'group', 'admin', false)
#11 /Users/lreschke/Programming/owncloud/master/lib/private/route/route.php(151) : runtime-created function(1): require_once('/Users/lreschke...')
#12 [internal function]: __lambda_func(Array)
#13 /Users/lreschke/Programming/owncloud/master/lib/private/route/router.php(270): call_user_func('\x00lambda_2221', Array)
#14 /Users/lreschke/Programming/owncloud/master/lib/base.php(825): OC\Route\Router->match('/apps/files_ext...')
#15 /Users/lreschke/Programming/owncloud/master/index.php(38): OC::handleRequest()
#16 {main}
            [File] => /Users/lreschke/Programming/owncloud/master/apps/files_external/3rdparty/league/flysystem/src/Filesystem.php
            [Line] => 533
        )

)
```

**Comment by LukasReschke** [comment]
Tutorial I followed to setup an FTP server: https://www.thomas-krenn.com/en/wiki/Setup_FTP_Server_under_Debian

**Comment by DeepDiver1975** [comment]
I tend to move this to 8.2 - just that we do not loose focus on the tasks for 8.1

**Comment by DeepDiver1975** [comment]
Spending research time will still be valid trough out the next weeks :speak_no_evil:

**Comment by cdamken** [comment]
@DeepDiver1975 Will be in 8.2-next?

**Comment by DeepDiver1975** [comment]
@icewind1991 we shall take the opportunity to extract this to it's own app and repo.

@butonic will move his curl based implementation https://github.com/owncloud/core/pull/16568 into an isolated app as well.

**Comment by icewind1991** [comment]
It might make sense to have the generic flysystem stuff core so we can have apps implementing the various flysystem backends with minimal code

**Comment by DeepDiver1975** [comment]
> It might make sense to have the generic flysystem stuff core so we can have apps implementing the various flysystem backends with minimal code

yes - indeed

- flysystem to 3rdparty
- some base adapter-fu in core
- any explicit implementation in it's own repos

**Comment by Xenopathic** [comment]
@icewind1991 @cdamken ping, we need this for 8.2

**Comment by icewind1991** [comment]
Work is being done here: https://github.com/icewind1991/files_external_ftp

Atm all tests succeed when running against proftpd, when running againsts vsftpd or pure-ftpd there are various issues but I dont know if those exists in the ftp backend we currently ship

**Comment by DeepDiver1975** [comment]
> Work is being done here: https://github.com/icewind1991/files_external_ftp

@icewind1991 I guess we can close this one - right? THX

**Comment by icewind1991** [comment]
Yes

**Pull request closed without merging**
