### PR TITLE
[OCS] With V2 we should ensure that the status codes are kept in sync

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@karlitschek @LukasReschke @schiesbn @Raydiation

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by DeepDiver1975** [comment]
@LukasReschke @schiesbn @Raydiation

**Comment by DeepDiver1975** [comment]
> @LukasReschke @schiesbn @Raydiation

ping - THX

**Comment by Raydiation** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
THX

**Pull request merged**
