### PR TITLE
use the preSetup hook to ensure the encryption wrapper is applied correctly

### LINKED ISSUE #15640: [enc2] Restore encrypted file from trash breaks the file + versions
### Steps to reproduce
1. Enable encryption 2.0 + default encryption modul
2. Log out then log in again
3. Create a text file
4. Edit it and save multiple times to create versions
5. Delete the file to trash
6. Restore the file
7. Download the file itself
8. Download any version of the file

### Expected result
File + versions can be downloaded

### Actual result
Download gives a broken file (garbage)

### Versions
ownCloud git master (1a2475227b6777e016ec931ddae533437bfbb2dd)

@schiesbn @th3fallen @DeepDiver1975

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #15640

cc @PVince81 @DeepDiver1975 @schiesbn

### CODE REVIEW

**Comment by PVince81** [comment]
While testing, it seems that downloading versions is extremely slow: https://github.com/owncloud/core/issues/15970

**Comment by PVince81** [comment]
Restoring a file still lets me download versions, works :+1: (the slowness is unrelated, it's also on master)

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
Regression: https://github.com/owncloud/core/issues/15981

**Pull request merged**
