### PR TITLE
Trigger login if remember_login checked

### PR DESCRIPTION
**Pull request by prastut**
Enhancement for #20477

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! It’s a really good experience. Simple and quick. Exactly as I expected. Great job @prastut 

Please review @owncloud/designers @owncloud/javascript

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by raghunayyar** [comment]
Awesome. @prastut. :+1:

**Comment by jancborchardt** [comment]
@prastut can you rebase your branch on top of current master? Also, did you sign the contributor agreement yet – see http://owncloud.org/about/contributor-agreement/

**Comment by prastut** [comment]
@jancborchardt I sent the signed agreement to Frank today. Will do the rebase asap.

**Comment by prastut** [comment]
@jancborchardt rebase done.

**Comment by jancborchardt** [comment]
@karlitschek can you confirm the CLA from @prastut? :)

**Comment by karlitschek** [comment]
@jancborchardt @prastut confirmed :-)

**Comment by jancborchardt** [comment]
@prastut do you want to get added to @owncloud/designers? Then you will receive notifications of issues where this team is mentioned. :)

**Comment by prastut** [comment]
@jancborchardt please do. :smirk:

**Pull request merged**
