### PR TITLE
[stable 9] Add mimetype to OCS Share API output

### PR DESCRIPTION
**Pull request by rullzer**
Backport of https://github.com/owncloud/core/pull/23056
Approval in: https://github.com/owncloud/core/pull/23056#issuecomment-194482593

CC: @LukasReschke @nickvergessen @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@rullzer please add the integration test here as well - THX

**Comment by rullzer** [comment]
Thanks :)

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Good to merge?

**Comment by rullzer** [comment]
@MorrisJobke if you provide the missing thumbs up ;)

**Comment by MorrisJobke** [comment]
> @MorrisJobke if you provide the missing thumbs up ;)

The first one is already mine, but I could place a second one here ;)

Take it: :+1:

**Comment by rullzer** [comment]
> The first one is already mine, but I could place a second one here ;)

I might need new glasses :confused:

**Pull request merged**
