### PR TITLE
Move public search namespace to PSR-4

### LINKED ISSUE #24803: Search provider class not found in file search
### Steps

1. Go to files app
1. Open the search field on the top right
1. Type in any string
1. Wait for results

### Expected result
Results appear eventually, or "not found" message

### Actual result
Spinner spins forever

### Logs
```
{"reqId":"6wUpiwUMaYXhK4Yzhe06","remoteAddr":"127.0.0.1","app":"PHP","message":"Class 'OCP\\Search\\Provider' not found at \/srv\/www\/htdocs\/owncloud\/lib\/private\/Search\/Provider\/File.php#32","level":3,"time":"2016-05-24T09:41:09+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/search?query=wel&inApps%5B%5D=files&page=1&size=30","user":"admin"}
```

### Versions
Observed on 9.1 pre-alpha git master 452542747cf895eaac69d7ca486a2dcb655785d0
Regression from v9.0.2

@georgehrke

### PR DESCRIPTION
**Pull request by nickvergessen**
@rullzer @PVince81 

Fix #24803

### CODE REVIEW

**Comment by georgehrke** [comment]
Wasn't able to reproduce https://github.com/owncloud/core/issues/24803, but this PR doesn't brake anything 👍

**Comment by nickvergessen** [comment]
Well on latest master lowercase folders/files are not loaded from public/ anymore, so :wink:

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
Works again :+1:

**Pull request merged**
