### PR TITLE
enable transational locking by default

### PR DESCRIPTION
**Pull request by icewind1991**
Also fixes memcache locking backend not being used due to debug work that was commited.

cc @DeepDiver1975 @PVince81 @MorrisJobke @Xenopathic

### CODE REVIEW

**Comment by Xenopathic** [comment]
LOL :+1:

**Comment by PVince81** [comment]
@icewind1991 please also update config.sample.php to have file locking set to true (and the comment that must say it's enabled by default)

**Comment by icewind1991** [comment]
@PVince81 done

**Comment by karlitschek** [comment]
:+1:

**Comment by icewind1991** [comment]
@PVince81 can this be merged?

**Comment by PVince81** [comment]
Looks good :+1:

**Pull request merged**
