### PR TITLE
files_sharing private function to proper signature

### PR DESCRIPTION
**Pull request by rullzer**
The collectShares function took an array which contained arguments for the function. Now it takes a bunch of arguments. Which makes static checking possible and IMO the code more readable.

Unit tests still pass of course.
Other than that rather tirival.

CC: @PVince81 @DeepDiver1975 @schiesbn @PVince81 @MorrisJobke @Raydiation

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Code looks good and I tested some sharing cases with resharing via groups and users. All still works and no errors are logged :+1:

**Comment by DeepDiver1975** [comment]
Changed code is not covered by unit tests - https://ci.owncloud.org/job/server-master-linux/database=sqlite,label=SLAVE/ws/tests/coverage-html-sqlite/apps/files_sharing/api/local.php.html

Can we add some please? @rullzer THX

**Comment by rullzer** [comment]
@DeepDiver1975 sure thing. Sounds like a plan.
Btw can I get access to that URL ;)?

**Comment by rullzer** [comment]
@DeepDiver1975 code coverage increased. We still need more but probably also need DI for 100%

**Comment by MorrisJobke** [comment]
Still :+1:

**Comment by MorrisJobke** [comment]
@PVince81 @DeepDiver1975 @schiesbn @LukasReschke Please review

**Comment by PVince81** [comment]
"Shared with you" section in UI still works :+1:

**Pull request merged**
