### PR TITLE
[stable9.1] Merge pull request #29181 from owncloud/fix-owncloud-for-…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…phpdbg

Use phpdbg to create coverage data

backport of #29181 to stable9.1

### CODE REVIEW

**Review by tboerger — APPROVED** [review]
LGTM code-wise, but drone fails.

**Comment by SergioBertolinSG** [comment]
Should I backport the missing PRs here? or make different PRs after this is merged?

**Comment by SergioBertolinSG** [comment]
```
There were 3 failures:

1) Test\FilesTest::testSetUploadLimitWrite with data set #1 (false, false, 2097152, false, '513M', '513M')

Failed asserting that 2097152.0 matches expected false.

/drone/src/tests/lib/FilesTest.php:114

2) Test\FilesTest::testSetUploadLimitWrite with data set #2 (true, false, 2097152, false, '2M', '513M')

Failed asserting that 2097152.0 matches expected false.

/drone/src/tests/lib/FilesTest.php:114

3) Test\FilesTest::testSetUploadLimitWrite with data set #3 (false, true, 2097152, false, '513M', '2M')

Failed asserting that 2097152.0 matches expected false.

/drone/src/tests/lib/FilesTest.php:114
```

**Comment by DeepDiver1975** [comment]
> Should I backport the missing PRs here? or make different PRs after this is merged?

I added everything to this pr - your choice at the end now 😉

**Comment by SergioBertolinSG** [comment]
There is this error appearing several times also: 
```pcntl_signal() has been disabled for security reasons.```

**Comment by PVince81** [comment]
considering that stable9.1 will be EOL soon I think this is not worth the effort if it needs a lot more work

**Comment by patrickjahns** [comment]
agree

**Pull request closed without merging**
