### PR TITLE
[stable8.1] allow an attribute to return more than one value

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #19635 (on top of #19427)

cc @blizzz @DeepDiver1975 @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by MorrisJobke** [comment]
I tested this and there were no errors in the logs :+1:

Before merging this I would really like to have @blizzz a look at this.

@davitol Can you test this nevertheless?

**Comment by GreenArchon** [comment]
c1953f96760163efb62f0bb8e244016d8e32dba7 includes the commit that caused #19816 regression, so you might want to add #19821 on top of it

**Comment by MorrisJobke** [comment]
> c1953f9 includes the commit that caused #19816 regression, so you might want to add #19821 on top of it

@GreenArchon Thanks for the hint :)

I added them and all still works here.

**Comment by MorrisJobke** [comment]
Okay ... then I need the test for this by @davitol here ;)

**Comment by blizzz** [comment]
I tested this a bit and have seen no issues yet, so plus :+1: 

However, most of the commits are mine anyway, so more different eyes and testers are more than welcome, @davitol @GreenArchon, maybe also @PeteSSS @plastilincheg ?

**Comment by davitol** [comment]
@MorrisJobke @blizzz I am testing it right now and I could not find any issue yet too, so from my POW :+1:

**Comment by MorrisJobke** [comment]
3 working tests -> merged

**Pull request merged**
