### PR TITLE
[stable10] Don't try decrypting federated shares in decrypt-all command

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/29724 to stable10

### CODE REVIEW

**Comment by PVince81** [comment]
@ownclouders please rebase

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
restarted drone build...

**Comment by PVince81** [comment]
@patrickjahns seems Drone doesn't properly restart the build. Or it doesn't show "pending" when restarted

**Comment by phil-davis** [comment]
drone doesn't show pending - there seems to be no hook from drone that notifies GitHub when a new job/build starts. I guess that is caused because drone makes a whole new job, rather than "restarting" the existing one.
When the new job completes, it does notify GitHub - so you have to just "wait and hope"

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by sharidas — APPROVED** [review]
LGTM :+1:

**Comment by sharidas** [comment]
Verified this change:
- scenario 1 
server1 is encrypted with masterkey and server2 with no encryption. server2 shares a folder with a file to server1 and later remove server2 instance. Delete the config.php and data folder of server2.
```
➜  owncloud3 git:(stable10) ✗ ./occ encryption:decrypt-all
Cannot load Xdebug - it was already loaded
Disable server side encryption... done.


You are about to start to decrypt all files stored in your ownCloud.
It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user access his files during this process!

Do you really want to continue? (y/n) y
prepare encryption modules...

Prepare "Default encryption module"

Use master key to decrypt all files
 done.


 decrypt files for user admin (1 of 1): /admin/files/welcome.txt 
 [-->-------------------------]

 starting to decrypt files... finished 
 [============================]


all files could be decrypted successfully!
```

- scenario 2
server1 is encrypted with user-keys and server2 is not encrypted and server2 shares a folder with a file to server1 and later remove server2 instance. Delete the config.php and data folder of server2.
```and later remove server2 instance. Delete the config.php and data folder of server2.

➜  owncloud3 git:(stable10) ✗ ./occ encryption:decrypt-all                                                                                                         
Cannot load Xdebug - it was already loaded
Disable server side encryption... done.


You are about to start to decrypt all files stored in your ownCloud.
It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user access his files during this process!

Do you really want to continue? (y/n) y
prepare encryption modules...
 done.


 decrypt files for user admin (1 of 1): /admin/files/welcome.txt (already decrypted) 
 [--->------------------------]

 starting to decrypt files... finished 
 [============================]


all files could be decrypted successfully!
➜  owncloud3 git:(stable10) ✗ 
```

**Pull request merged**
