### PR TITLE
Show colored avatar placeholder for unknown users

### PR DESCRIPTION
**Pull request by MorrisJobke**
- previously it was a grey X
- ref https://github.com/owncloud/core/pull/21811#issuecomment-173223265

cc @owncloud/designers @rullzer @PVince81 @oparoz 

bildschirmfoto 2016-01-25 um 10 08 43

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! One thing: It should also be round, like all the other avatar images. `border-radius: 50%;`

**Comment by DeepDiver1975** [comment]
jsunit also has issues ...

**Comment by MorrisJobke** [comment]
> jsunit also has issues ...

Fixed

**Comment by nickvergessen** [comment]
This was used in the activity app, to identify deleted users a bit better

**Comment by MorrisJobke** [comment]
> This was used in the activity app, to identify deleted users a bit better

@jancborchardt told me to remove it :see_no_evil:

**Comment by MorrisJobke** [comment]
> Nice! One thing: It should also be round, like all the other avatar images. border-radius: 50%;

Different topic, because the example is taken from the documents app - please report this there.

**Comment by jancborchardt** [comment]
@MorrisJobke @nickvergessen well, guests and deleted users are a different thing. And deleted users are probably not going to show up in the »who is editing this document right now« sidebar in the Documents app. ;)

**Comment by MorrisJobke** [comment]
> @MorrisJobke @nickvergessen well, guests and deleted users are a different thing. And deleted users are probably not going to show up in the »who is editing this document right now« sidebar in the Documents app. ;)

But how to differentiate them? Both are not existent in the user list ;)

**Comment by rullzer** [comment]
So what we actually need is a bit of a rework of the avatar js code. Maybe one with promises. So then the code can always first set the placeholder. And then call the avatar code which does something depending on the call. Since the avatar code is already getting to big for my taste (for what it actually does).

Since adding yet another parameter probabaly does not make stuff easier.

**Comment by MorrisJobke** [comment]
I'm also fine with killing this PR. I Just was asked to do it and I did it. Then people complained about it. Do what you think suites best. I'm out of this discussion.

**Comment by jancborchardt** [comment]
Ok, sorry for the confusion then. I wasn’t aware that this messes with the Activity code.

Seems that keeping the »X« feedback in the Activity app is more important than fixing the Documents app I guess? In that case we can close it.

**Comment by MorrisJobke** [comment]
> Ok, sorry for the confusion then. I wasn’t aware that this messes with how the Activity app and others make deleted users look.

No problem :) I always like clear decisions :+1: better than having this open for months and waste time in discussing, rebasing and fixing again and again ;)

**Pull request closed without merging**
