### PR TITLE
Make Cache\Updater per storage

### PR DESCRIPTION
**Pull request by icewind1991**
Give more control over the cache to the storage.

Possible since we no longer need to do cross-storage propagation

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
@icewind1991 what kind of control ?

**Comment by icewind1991** [comment]
Prevent oC from trying to update the cache if the storage backend doesn't require it

**Comment by PVince81** [comment]
- [ ] TEST: fullsmash
- [ ] TEST: cross-storage rename/copy

**Comment by PVince81** [comment]
Cross storage move works, even with encryption (tested with share mounts)

:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
