### PR TITLE
chore: remove unused openidconnect config option `use-token-introspec…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…tion-endpoint`

## Description
see https://github.com/owncloud/openidconnect/pull/286
## Related Issue
- refs https://github.com/owncloud/openidconnect/pull/286

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by mmattel — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
I guess we don't need a changelog for this ..... :shrug:

**Comment by mmattel** [comment]
At least notify @jnweiger as this is together with the related PR app-release relevant.

**Review by phil-davis — APPROVED** [review]

**Comment by jnweiger** [comment]
@phil-davis adjust some tests?
- tests/unit/SessionVerifierTest.php
- tests/unit/OpenIdConnectAuthModuleTest.php

**Comment by phil-davis** [comment]
> adjust some tests?

Those tests are in the `openidconnect` repo, so that needs a separate PR.
See https://github.com/owncloud/openidconnect/pull/286
and https://github.com/owncloud/openidconnect/pull/288

**Pull request merged**
