### PR TITLE
[WIP] Add transaction to cache put method

### PR DESCRIPTION
**Pull request by mrow4a**
- [ ] Needs proper manual testing

### CODE REVIEW

**Comment by butonic** [comment]
starting a transaction will commit an already running transaction. we are using explicit transactions for the filescanner so this needs to be examined regarding subsequent failures, because the surrounding transaction is not restarted. AFAICT since we are now using a transation in every individual put the more global filescan transaction has become obsolete. It was moved to a more global place to speed up scanning multiple files. but IMNSHO making put work as expected is more important than trying to speed up an operation that is not meant to be executed anyway.

**Comment by PVince81** [comment]
@butonic afaik we have nested transactions, so starting a new one would just go one level deeper. (I saw a counter about nested transactions many times when debugging into the DB code)

**Comment by butonic** [comment]
@PVince81 that is fake transaction nesting. Reading the docs at http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/transactions.html#transaction-nesting makes me think we may need to revisit the whole transaction mess in oc:
```console
$ grep -R beginTransaction . | grep -v "/lib/composer"
grep: ./core/Migrations/Version20170526104128.php:		$db->beginTransaction();
./apps-repos/user_ldap/lib/Command/UpdateGroup.php:		$this->connection->beginTransaction();
./lib/public/IDBConnection.php:	public function beginTransaction();
./lib/public/DB.php:	 * @deprecated 8.1.0 use beginTransaction() of \OCP\IDBConnection - \OC::$server->getDatabaseConnection()
./lib/public/DB.php:	public static function beginTransaction() {
./lib/public/DB.php:		\OC::$server->getDatabaseConnection()->beginTransaction();
./lib/private/Files/Cache/Cache.php:				$this->connection->beginTransaction();
./lib/private/Files/Cache/Scanner.php:			\OC::$server->getDatabaseConnection()->beginTransaction();
./lib/private/Files/Cache/Propagator.php:		$this->connection->beginTransaction();
./lib/private/Files/Utils/Scanner.php:				$this->db->beginTransaction();
./lib/private/Files/Utils/Scanner.php:				$this->db->beginTransaction();
./lib/private/DB/Migrator.php:		$connection->beginTransaction();
./lib/private/DB/Adapter.php:		$this->conn->beginTransaction();
./lib/private/DB/MDB2SchemaManager.php:		$this->conn->beginTransaction();
./lib/private/Repair/SqliteAutoincrement.php:		$this->connection->beginTransaction();
./lib/private/AppFramework/Db/Db.php:	public function beginTransaction() {
./lib/private/AppFramework/Db/Db.php:		$this->connection->beginTransaction();
./lib/private/SystemTag/SystemTagManager.php:		$this->connection->beginTransaction();
./lib/private/Share20/DefaultShareProvider.php:		$this->dbConn->beginTransaction();
./apps/files_sharing/lib/Migration.php:		$this->connection->beginTransaction();
./apps/dav/lib/Files/CustomPropertiesBackend.php:		$this->connection->beginTransaction();
./apps/dav/lib/Connector/Sabre/CustomPropertiesBackend.php:		$this->connection->beginTransaction();
./tests/lib/User/AccountMapperTest.php:		\OC::$server->getDatabaseConnection()->beginTransaction();

```
:cry:

**Comment by mrow4a** [comment]
So this PR can be closed, since generally transactions in OC need rethinking?

**Comment by butonic** [comment]
using diagnostics occ db:stress -f we can rule this out as a solution. still throws an exception after just a second. https://github.com/owncloud/core/pull/28698 is much more promising.

**Pull request closed without merging**
