### PR TITLE
Revert "adjust to nested group fix"

### LINKED ISSUE #19816: [8.2 regression] LDAP: Having memberOf enabled breaks nested groups
See https://github.com/owncloud/core/issues/17759#issuecomment-148320869

@MorrisJobke @davitol @cmonteroluque 

so this is broken again in 8.2

### PR DESCRIPTION
**Pull request by GreenArchon**
This reverts commit 845485cfe, which fixes #19816 regression.

### CODE REVIEW

**Comment by karlitschek** [comment]
@LukasReschke @blizzz

**Comment by PVince81** [comment]
Thanks a lot @GreenArchon!

@davitol can you test that this PR fixes https://github.com/owncloud/core/issues/19816.
Also please check if https://github.com/owncloud/core/issues/17362 still works (because this PR reverts part of the code that was used to fix that one)

**Comment by MorrisJobke** [comment]
I will also have a look, because it affects blue ticket related stuff.

**Comment by LukasReschke** [comment]
Let me cherry-pick this to an ownCloud branch for CI purposes. Also we should add an unit test.

**Comment by LukasReschke** [comment]
Replaced by https://github.com/owncloud/core/pull/19821

**Comment by davitol** [comment]
+1: fixes #19816 regression and https://github.com/owncloud/core/issues/17362 still works for me. Good job :clap:

**Comment by PVince81** [comment]
Thanks!

**Pull request closed without merging**
