### PR TITLE
fixes #18971

### LINKED ISSUE #18971: php 32 bit (arm) filemtime on large file issue
I am facing an issue with running file:scan on arm:

filemtime(): stat failed

Looks like the reason is filemtime [1] is not working for files over 2G on 32 bit php [2]

Fixing function according to php website comment solved the problem:

```
  exec ('stat -c %Y '. escapeshellarg ($this->getSourcePath($path)));
```

I am sure that worked fine in past with older owncloud/php versions on the same hardware.

Is there something I am missing or this never worked on php (32bit) / arm?
Or is it possible to have some if, like:

```
if (PHP_INT_SIZE === 4)
   return exec ('stat -c %Y '. escapeshellarg ($this->getSourcePath($path)));
else
   return filemtime($this->getSourcePath($path));
```

I cannot upgrade php to 64 bit on arm board as there there is no such thing yet as arm64 or at least not popular enough on single board computers yet.

[1] http://php.net/manual/en/function.filemtime.php#68814
[2] https://github.com/owncloud/core/blob/master/lib/private/files/storage/local.php#L159

My system:
ownCloud version 8.0.4
PHP Version => 5.6.9
System => Linux cubietruck 3.4.79-sun7i #13 SMP PREEMPT Thu Jul 3 06:34:55 CST 2014 armv7l
Configure Command =>  './configure'  '--enable-fpm' '--with-pgsql' '--with-pdo-pgsql' '--enable-opcache' '--prefix' '--with-config-file-path=/root/build/install/config' '--with-gd' '--enable-zip' '--with-zlib' '--with-curl' '--with-readline' '--with-ldap' '--with-ldap-sasl' '--with-libdir=lib/arm-linux-gnueabihf' '--enable-mbstring'

### PR DESCRIPTION
**Pull request by cyberb**

### CODE REVIEW

**Comment by cyberb** [comment]
This contribution is MIT licensed

**Comment by icewind1991** [comment]
This workaround should only be used on system where it's actually needed (32bit systems)

**Comment by cyberb** [comment]
I can do another PR, but I am not sure why would you use two different implementations if one covers all the cases.

**Comment by cyberb** [comment]
just in case you really want 32bit only fix, here is another PR: https://github.com/owncloud/core/pull/25428

**Comment by DeepDiver1975** [comment]
> I can do another PR, but I am not sure why would you use two different implementations if one covers all the cases.

forking another process has an impact on performance - I prefer to go with #25428

**Pull request closed without merging**
