### PR TITLE
feature endorse password for share links

### PR DESCRIPTION
**Pull request by tbenk**
## Description

At the moment there are two possible configuration option
for shared links:
- enforce password protection
- do not enforce password protection

If you choose to not enforce password protection, the shared
link will be publically available until you set a password
for the shared link.

We have the requirement in our company that all shared links 
will be password protected from the moment on the shared
link is created, but optionally it should be possible to remove
the password protection from the link. Having an explicitly
opt-out option should additionally increase the users
security awareness.

For this we have implemented another option which is somewhat
in between the existing two options:
- endorse password protection

This works like "enforce password protection", but let the
user optionally remove the password protection after the
password is set.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Code looks good, explanation makes sense. Thanks for the PR!

How about just calling it "Enable password by default for link shares" because all this is doing is simply changing which value is set by default. (at least in the GUI, the code can stay)

What do you think ?

**Comment by tbenk** [comment]
"Enable password by default for link shares" sounds good for me.

**Comment by PVince81** [comment]
@tbenk sounds good :smile: 
Can you adjust the PR ?
Thanks

**Comment by tbenk** [comment]
The PR is now updated.

**Comment by PVince81** [comment]
@tbenk hmm, looks like there is a conflict, can you fix it ?

**Comment by tbenk** [comment]
The conflict should be fixed now.

**Comment by PVince81** [comment]
I've just tested this and it works, but the UX workflow feels a bit strange.

I'm forced to enter a password before I get a chance to opt-out.
Ideal would be to have the checkbox visible as well or alternatively let the user enter an empty password to disable it (adjust the placeholder accordingly).

Additionally, but less of an issue is on the admin page: the options "Enable password by default for link shares" and "Enforce password" are mutually exclusive. Maybe enabling one should disable the checkbox of the other one (minor issue, not needed for merging).

**Comment by tbenk** [comment]
I have changed the PR so that the user can enter an empty password to disable it.

**Comment by PVince81** [comment]
Now I'd say change the admin setting name to "Always ask for a password", this matches the workflow better.

**Comment by tbenk** [comment]
I have updated the label.

**Comment by PVince81** [comment]
Thanks. Tested, works :+1:

**Pull request merged**
