### PR TITLE
Stable9.1 chunked web upload

### PR DESCRIPTION
**Pull request by butonic**
backport of https://github.com/owncloud/core/pull/26306 to stable9.1

requires a few more commits to first enable PUT uploads.

manually tested in IE11, chrome canary and firefox.

cc @michaelstingl @PVince81

### CODE REVIEW

**Comment by butonic** [comment]
tested with 4.6GB \o/ @PVince81 is awesome!

**Comment by PVince81** [comment]
How can this even work ? We don't have Webdav PUT upload support in the JS code in 9.1 and from what I remember it was a huge change

**Comment by PVince81** [comment]
Hmm ok you backported everything... I'm not too happy to backport this huge change and change of behavior of 9.1.

**Comment by PVince81** [comment]
Had a chat with @DeepDiver1975 and he agreed that we should **not** backport this. This is a new feature in 10.0 and the code changes are too big.

**Comment by DeepDiver1975** [comment]
this is total madness - the feature is not even ready for master/10.0 and we are considering a backport?
this is total nuts - no way I'll ever accept this pr

**Comment by butonic** [comment]
agreed. backport too risky.

**Pull request closed without merging**
