### PR TITLE
Increase the 2nd digit of shipped apps

### PR DESCRIPTION
**Pull request by nickvergessen**
We need to increase the 2nd digit of app versions, otherwise apps are never able to trigger an update in the stable branches without causing major troubles (duplicate version number)

### CODE REVIEW

**Comment by nickvergessen** [comment]
@DeepDiver1975 @karlitschek @cmonteroluque we should do that in 8.2 as well, to avoid problems.

@MorrisJobke @LukasReschke @PVince81 please review

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@nickvergessen I would propose to align the versions of the shipped apps with the core version number. This would make it easier to know which version number is reserved for a later core version. :see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by nickvergessen** [comment]
Well lower versions just never get to update anything but the minor.
We can also use 4 digits for the app version and use the first 3 from the core version, so apps only have the patch level version to trigger updates. But doesn't really matter a lot. We just need to make sure that versions get updated correctly on releases and on changes. This patch was the easier version for now.

**Comment by MorrisJobke** [comment]
> We just need to make sure that versions get updated correctly on releases and on changes. This patch was the easier version for now.

Sure. But having it applied implicit would make it easier to spot ;)

**Pull request merged**
