### PR TITLE
Added repair script to upgrade the legacy home storage ids

### PR DESCRIPTION
**Pull request by PVince81**
I'm tired of these legacy storage id issues when people move their homes, so here is the repair script.
Fixes #6493 

I've tested with MySQL:
- [x] correctly migrates legacy storage ids to home:: based ids
- [x] doesn't migrate existing home:: other storages
- [x] doesn't migrate "local::/path/to/datadir/" which I still wonder why it exists, some kind of root storage?

This needs to be tested on all DBs.

TODO:
- [x] Test on more DBs
- [x] Add unit tests containing a mix of legacy storage ids, home storage ids and external storage ids

@DeepDiver1975 @icewind1991 @karlitschek

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@karlitschek The backport request was triggered by @butonic

**Comment by PVince81** [comment]
Beware, if any user in OC 7 has broken storages the upgrade will REFUSE to run because of the exception. I thought it isn't acceptable to block users in a minor upgrade. Major upgrade might be ok.

Else we'll need to reconsider making it a soft fail: https://github.com/owncloud/core/pull/13513

**Comment by PVince81** [comment]
"broken storage" as in "a broken storage situation that cannot be repaired automatically"

**Comment by karlitschek** [comment]
I agree with @PVince81 We should the broken entries or ignore them. But blocking upgrade without the option to repair it is not good in a minor version.

**Comment by idmacdonald** [comment]
Hi, can anyone tell me whether I should expect the 'occ maintenance:repair' task to fix the absolute paths in oc_storages on v8.2.3? I just migrated an ownCloud install from one server to another and in the end I had to install it in the same filesystem location on the new server as the old one (which in this case is rather inconvenient), because I was not able to fix the storage IDs. I've run 'occ maintenance:repair', but after running it I still see all the absolute paths in the oc_storages table, so it doesn't appear to actually be doing anything. Cheers, Ian.

**Comment by PVince81** [comment]
@idmacdonald for support please ask in http://central.owncloud.org/
Feel free to ping me there and I'll answer.

**Comment by idmacdonald** [comment]
Hi @PVince81 I have posted my issue there: 
https://central.owncloud.org/t/shared-files-broken-after-moving-install-to-a-different-filesystem-location/1537

I couldn't figure out how to send a private message over there, so just letting you know. Cheers, Ian.

**Pull request merged**
