### PR TITLE
Improve settings/apps page

### LINKED ISSUE #15650: Keep current section in hash/URL in apps page
### Steps:
1. Go to the apps page
2. Select a section, for example "Recommended"
3. Refresh the browser page

### Expected
Still in "Recommended" section

### Actual
Back to the "Enabled" section

Optionally the search term could also be kept in the URL so that the search stays. That might become more relevant in the future when there are more apps.

@owncloud/designers

### LINKED ISSUE #15651: Reapply search when switching sections in apps page
### Steps
1. Go to apps page
1. Type in a search term, for example "storage"
1. Switch to "Not enabled" section

### Expected
Search/filter must still be applied to the newly selected section

### Actual
Search field still contains the value, but no search is applied. I need to type something in the field to retrigger it.

@owncloud/designers

### LINKED ISSUE #16836: Apps search: No feedback when there is no search result
Search in the apps management and type in »test« or some other term which does not give any result.

Instead of just leaving it blank, we should show a nice `.emptycontent` message is shown with an icon-search and a »No apps found for <searchterm>«.

@icewind1991 or someone from @owncloud/designers maybe? Using .emptycontent just like in the files app should work.

### PR DESCRIPTION
**Pull request by nickvergessen**
- Search by author name
- Search by app level (Experimental, official, ...)
- Load same category again when refreshing page https://github.com/owncloud/core/issues/15650
- Clear search field when changing category, until we search cross categories https://github.com/owncloud/core/issues/15651
- Display #empty-content when search result is empty https://github.com/owncloud/core/issues/16836

@PVince81 @MorrisJobke @LukasReschke 

Fix #15650
Fix #15651
Fix #16836

### CODE REVIEW

**Comment by nickvergessen** [comment]
cc @jancborchardt

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by jancborchardt** [comment]
Cool! Just some remarks:

* Instead of »No apps found for your version« it should say »No apps found for "`searchterm`"«.
* When trying to search for the »Mail« app and mistype »maiö« and the emptycontent message comes up – you need to remove the whole search input. Only clearing the last wrong letter doesn’t reset it back.
* Searching for »mail« brings up the Activity app first, presumably because it has the word »email« in its description. Of course matches with app titles should be prioritized higher.
* Instead of the technical link `apps?category=1` can we make the URL speak by using `apps?category=enabled`, `apps?category=tools`, etc?

**Comment by nickvergessen** [comment]
> * Instead of »No apps found for your version« it should say »No apps found for "`searchterm`"«.

yes

> * When trying to search for the »Mail« app and mistype »maiö« and the emptycontent message comes up – you need to remove the whole search input. Only clearing the last wrong letter doesn’t reset it back.

That's a problem with the search in general then I guess?

> * Searching for »mail« brings up the Activity app first, presumably because it has the word »email« in its description. Of course matches with app titles should be prioritized higher.

We can do that once we search cross categories. ATM this would require too much of a refactoring

> * Instead of the technical link `apps?category=1` can we make the URL speak by using `apps?category=enabled`, `apps?category=tools`, etc?

Will try to have a look

**Comment by jancborchardt** [comment]
Cool, thanks!

> That's a problem with the search in general then I guess?

No, it works fine in Files, Users and Mail. When the emptycontent message is shown and you delete the last (wrong) character, a new search is fired.

**Comment by nickvergessen** [comment]
Resolved the three issues I mentioned

**Comment by nickvergessen** [comment]
@LukasReschke @schiesbn review?

**Comment by PVince81** [comment]
- [ ] BUG: Browser back/forward button do refresh the URL, but the section isn't switched. You need to add code to react on the hashchange event, like this: https://github.com/owncloud/core/blob/v8.2.0/apps/files/js/app.js#L145

**Comment by nickvergessen** [comment]
Thanks, fixed and rebased.

Mind testing again?

**Comment by PVince81** [comment]
:+1: tested

**Comment by MorrisJobke** [comment]
Tested again :+1:

**Pull request merged**
