### PR TITLE
Introduce phpstan

### PR DESCRIPTION
**Pull request by patrickjahns**
## Description
Introduce https://github.com/phpstan/phpstan into owncloud/core

The `phpstan.neon` configuration is a very minimal configuration to get it running and prevent some of the problems/technical debt related to `templates` / `routes.php` etc.

We currently use **level 0** - which is the most lenient level - in this level, we already have ~ 400 errors/violations which need to be gradually adressed.

Some of them are related to Migrations and autoloading

General noticed the issue with autoloading - right now our internal autoloader requires ownCloud to be properly installed (and apps enabled) to be able to provide the classes for phpstan.

I would consider this also quite some technical debt which at some point would need some ❤️ . If possible at some point I see it feasible to move towards composer as being the only autoloader, and our class being registered to composer as authoritative autoloader. 

## Motivation and Context
- Improve code quality
- Prevent bugs that can sneak

## How Has This Been Tested?
🤖 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] improve code quality 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by patrickjahns** [comment]
CI shows in https://drone.owncloud.com/owncloud/core/7980/74

```
[ERROR] Found 414 errors       
```

errors regarding autoloading in migrations need some closer view if we skip that in phpstan - include it otherwise
```
 ------ ------------------------------------------------------------------------- 
  Line   core/Migrations/Version20171026130750.php                                
 ------ ------------------------------------------------------------------------- 
         Class OC\Migrations\Version20171026130750 was not found while trying to  
         analyse it - autoloading is probably not configured properly.            
 ------ ------------------------------------------------------------------------- 
```

**Comment by phil-davis** [comment]
Note for when this gets to the "backport to stable10" stage:
It will be nice to get the "owncloud coding standard" changes backport merged to ``stable10`` first.
Then changes in this PR are much more likely to backport without conflict.

**Comment by DeepDiver1975** [comment]
> errors regarding autoloading in migrations need some closer view if we skip that in phpstan - include it otherwise

migrations are never loaded using the autoloader but purly on basis of requiring the explicit file.
So we can easily savely ignore autoloading errors on migrations.

**Comment by patrickjahns** [comment]
After merging `phan` branch - we are now down to  `[ERROR] Found 302 errors`

Need to schedule some more time to move this forward.

@ondrejmirtes 
Thanks for sharing - quick question - would you rather recommend to temporarily include them via phpstan directly?

Also do you recommend for a large project like this, to use our (legacy) application bootstrapping file - or use autoloading capabilities for stan.

(On a sidenote - absolutely love phpstan 😍 )

**Comment by ondrejmirtes** [comment]
@patrickjahns One option I forgot to tell you about - yes, you can use `autoload_files` or `autoload_directories` PHPStan option to do this, it's absolutely fine - just be careful about side effects. If there's something else beside a class definition in an autoloaded file, it will get executed! (I need to tackle this in some future version.)

Thank you for your kind words 😊

**Comment by ondrejmirtes** [comment]
You have several options for autoloading and they are equal:

* Built-in Composer autoloader - the easiest option, works out of the box
* Add some files and directories using `autoload_files` and `autoload_directories`
* Use a completely custom autoloader registered in PHPStan's `bootstrap` (config option) or `--autoload-file` (CLI option).

**Comment by patrickjahns** [comment]
@DeepDiver1975 @PVince81 - are we still using jcrop in the frontend?

It ships with some demo php code - which is not required and leads to static code analyzer failures i.e.

```
 ------ -------------------------------------------------------------- 
  Line   core/vendor/jcrop/demos/crop.php                              
 ------ -------------------------------------------------------------- 
  17     Call to function imagecreatetruecolor() with incorrect case:  
         ImageCreateTrueColor                                          
 ------ -------------------------------------------------------------- 

 ------ -------------------------------------------------------------- 
  Line   core/vendor/Jcrop/demos/crop.php                              
 ------ -------------------------------------------------------------- 
  17     Call to function imagecreatetruecolor() with incorrect case:  
         ImageCreateTrueColor                                          
 ------ -------------------------------------------------------------- 
```

We can ignore the `core/vendor` path - but all of the files/libraries in there seem to be very old?

**Comment by patrickjahns** [comment]
@DeepDiver1975 @PVince81 
I don't understand - why does a core entity use the AppFramework:

```
 ------ --------------------------------------------------- 
  Line   lib/private/Authentication/Token/DefaultToken.php  
 ------ --------------------------------------------------- 
  94     Call to an undefined static method                 
         OCP\AppFramework\Db\Entity::getLoginName().        
  103    Call to an undefined static method                 
         OCP\AppFramework\Db\Entity::getPassword().         
  122    Call to an undefined static method                 
         OCP\AppFramework\Db\Entity::getLastCheck().        
  131    Call to an undefined static method                 
         OCP\AppFramework\Db\Entity::setLastCheck().        
  141    Call to an undefined static method                 
         OCP\AppFramework\Db\Entity::setName().             
  151    Call to an undefined static method                 
         OCP\AppFramework\Db\Entity::setLoginName().        
 ------ --------------------------------------------------- 
```

**Comment by PVince81** [comment]
@patrickjahns probaby because the app framework provides a DB layer based on entities which can be convenient in some cases. At some point there was the thought of using DB entities everywhere but we never got to plan porting everything over.

**Comment by patrickjahns** [comment]
That just seems like a mess all over again - I am happy to introduce static code analysis all over the place to uncover and prevent further things ;-)

**Comment by DeepDiver1975** [comment]
These errors are fixed in phpstan master branch

```
 ------ -------------------------------------------------------------- 
  Line   apps/dav/appinfo/v1/caldav.php                                
 ------ -------------------------------------------------------------- 
         Internal error: Call to undefined method                      
         PhpParser\Node\Scalar\String_::parseDocString()               
         Run PHPStan with --debug option and post the stack trace to:  
         https://github.com/phpstan/phpstan/issues/new                 
 ------ -------------------------------------------------------------- 

 ------ -------------------------------------------------------------- 
  Line   apps/dav/appinfo/v1/carddav.php                               
 ------ -------------------------------------------------------------- 
         Internal error: Call to undefined method                      
         PhpParser\Node\Scalar\String_::parseDocString()               
         Run PHPStan with --debug option and post the stack trace to:  
         https://github.com/phpstan/phpstan/issues/new                 
 ------ -------------------------------------------------------------- 

 ------ -------------------------------------------------------------- 
  Line   apps/dav/lib/Server.php                                       
 ------ -------------------------------------------------------------- 
         Internal error: Call to undefined method                      
         PhpParser\Node\Scalar\String_::parseDocString()               
         Run PHPStan with --debug option and post the stack trace to:  
         https://github.com/phpstan/phpstan/issues/new                 
------ --------------------------------------------------------------

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by phil-davis** [comment]
Note: this might be reasonable to do in `stable10` with or after drop PHP 7.0 (maybe it is not strictly dependent on that, but anyway)
I noticed this when preparing some "drop PHP7.0" stuff and I also applied some drone changes that ran `phpstan` on `stable10`

**Comment by phil-davis** [comment]
Proposed backport `stable10` is in #35774

**Pull request merged**
