### PR TITLE
uniquify drone pipeline steps

### PR DESCRIPTION
**Pull request by patrickjahns**
## Description
The current `.drone.yml` is not valid yaml. Duplicate keys are not allowed in a valid yaml

## Related Issue

- Fixes <issue_link>

## Motivation and Context
Fix pipeline and have it ready for drone 1.0 

## How Has This Been Tested?
🤖 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM - I had wondered how that had survived drone-YAML parsing. It only ever ran one of each pair of duplicated steps, so somehow got away with it.

**Comment by patrickjahns** [comment]
FML - now the certificates don't match the hostname -_-

**Comment by patrickjahns** [comment]
I believe this will be green now - however let me think about how to cleanup the pipeline

**Comment by patrickjahns** [comment]
This is needed when moving to drone 1.0 for the public instance - we need to have unique keys ( any yaml linter should have complained by now :( )

**Comment by individual-it** [comment]
`"cURL error 51: SSL: certificate subject name 'server' does not match target host name 'server_https'"`

`- APACHE_SSL_CERT_CN=server` needs to be `- APACHE_SSL_CERT_CN=server_${SERVER_PROTOCOL}`

**Comment by phil-davis** [comment]
@patrickjahns I rebased, resolved the `.drone.yml` conflict and added the extra change that @individual-it pointed out.
CI should pass now - let's see.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/15952/606
```
  Scenario: restoring file to old version changes the content of the file                                   # /drone/src/tests/acceptance/features/webUIFiles/versions.feature:25
    Given user "user0" has logged in using the webUI                                                        # WebUILoginContext::theUserLogsInUsingTheWebUI()
    And the user has browsed to the files page                                                              # WebUIFilesContext::theUserBrowsesToTheFilesPage()
    And user "user0" has uploaded file with content "lorem content" to "/lorem-file.txt"                    # FeatureContext::userUploadsAFileWithContentTo()
    And user "user0" has uploaded file with content "new lorem content" to "/lorem-file.txt"                # FeatureContext::userUploadsAFileWithContentTo()
    When the user browses directly to display the "versions" details of file "lorem-file.txt" in folder "/" # WebUIFilesContext::theUserBrowsesDirectlyToDetailsTabOfFileInFolder()
INFORMATION: timed out waiting for ajax calls to start
    And the user restores the file to last version using the webUI                                          # WebUIFilesContext::theUserRestoresTheFileToLastVersionUsingTheWebui()
      │ INFORMATION: timed out waiting for ajax calls to start
    Then the content of file "lorem-file.txt" for user "user0" should be "lorem content"                    # FeatureContext::contentOfFileForUserShouldBe()
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'lorem content'
      +'new lorem content'
SCENARIO RESULT: (fail)

--- Failed scenarios:

    /drone/src/tests/acceptance/features/webUIFiles/versions.feature:25

1 scenario (1 failed)
8 steps (7 passed, 1 failed)
```

https://drone.owncloud.com/owncloud/core/15952/809
```
--- Failed scenarios:

    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:49
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:50
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:68
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:69
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:87
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:88
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:106
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:107
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:110
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:149
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:188
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:243
    /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:244

40 scenarios (27 passed, 13 failed)
552 steps (464 passed, 13 failed, 75 skipped)
15m40.41s (22.64Mb)
```

```
  Scenario Outline: deleting the only remaining lock of a file/folder                                            # /drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:34
    Given user "brand-new-user" has locked file "lorem.txt" setting following properties                         # WebDavLockingContext::userHasLockedFile()
      | lockscope | <lockscope> |
    And user "brand-new-user" has locked folder "simple-folder" setting following properties                     # WebDavLockingContext::userHasLockedFile()
      | lockscope | <lockscope> |
    And the user has browsed to the files page                                                                   # WebUIFilesContext::theUserBrowsesToTheFilesPage()
    When the user unlocks the lock no 1 of file "lorem.txt" on the webUI                                         # WebUIWebDavLockingContext::unlockFileOnTheWebui()
    And the user unlocks the lock no 1 of folder "simple-folder" on the webUI                                    # WebUIWebDavLockingContext::unlockFileOnTheWebui()
    Then file "lorem.txt" should not be marked as locked on the webUI                                            # WebUIWebDavLockingContext::theFileShouldNotBeMarkedAsLockedOnTheWebui()
    And folder "simple-folder" should not be marked as locked on the webUI                                       # WebUIWebDavLockingContext::theFileShouldNotBeMarkedAsLockedOnTheWebui()
    And 0 locks should be reported for file "lorem.txt" of user "brand-new-user" by the WebDAV API               # WebDavLockingContext::numberOfLockShouldBeReported()
    And 0 locks should be reported for folder "simple-folder" of user "brand-new-user" by the WebDAV API         # WebDavLockingContext::numberOfLockShouldBeReported()
    And 0 locks should be reported for file "simple-folder/lorem.txt" of user "brand-new-user" by the WebDAV API # WebDavLockingContext::numberOfLockShouldBeReported()

    Examples:
      | lockscope |
      | exclusive |
        │ INFORMATION: timed out waiting for ajax calls to start
        │ INFORMATION: timed out waiting for ajax calls to start
        'lorem.txt' should not be marked as locked, but it is
        Failed asserting that true is false.

--- Failed scenarios:

/drone/src/tests/acceptance/features/webUIWebdavLocks/unlock.feature:49
```

what???

These are failing the same on multiple re-runs. But existing core master CI is running fine, so the problem is somewhere in this PR!

**Comment by phil-davis** [comment]
https://en.wikipedia.org/wiki/Hostname - host names cannot contain underscore.
Probably something bad happens with WebDav if you put an underscore in your host name.
I will add a commit to change that.

**Comment by phil-davis** [comment]
Backport `stable10` #34749

**Pull request merged**
