### PR TITLE
Add symfony events for file read and update

### PR DESCRIPTION
**Pull request by sharidas**
This event wouldbe generated and would
also be helpful when user tries to download
file or files from the UI.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Add symfony events for readfile method.

## Motivation and Context

Add symfony dispatcher event for `readfile` method.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Not sure if this is the right approach because this is not the only code path that can read a file. For example an app can do `$view->fopen()` then several `fread()`.

If this is only about downloads, maybe add the symfony event more closely to the download code ?

**Comment by SergioBertolinSG** [comment]
Tried this with admin_audit 0.9.0 and marketplace's gallery:

It couldn't open the files:

```
{"reqId":"HkFX8WG0GwbeU5SQF8Tl","level":3,"time":"2018-01-30T12:50:41+00:00","remoteAddr":"HIDDEN_IP","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/gallery\/preview\/16?width=1500&height=1500&c=1864db6adb63bdc70df60e08f964ceea&requesttoken=WhI7AUlYWmQqBgEQCQsTO2oiXAoMHBl3CFE4ZQM4XHo%3D%3A5QhX8hj7OdPSo2kT%2Fveh8S6996JVUW3%2BQwecBJJ%2FbHY%3D","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OC\\\\Preview::__construct() must implement interface OCP\\\\Files\\\\Node, string given, called in \\\/opt\\\/owncloud\\\/apps\\\/gallery\\\/preview\\\/preview.php on line 100\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/gallery\\\/preview\\\/preview.php(100): OC\\\\Preview->__construct('admin', 'files', 'parda.jpg')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/gallery\\\/service\\\/previewservice.php(107): OCA\\\\Gallery\\\\Preview\\\\Preview->setupView('admin', Object(OC\\\\Files\\\\Node\\\\File), 'parda.jpg')\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/gallery\\\/controller\\\/preview.php(167): OCA\\\\Gallery\\\\Service\\\\PreviewService->createPreview(Object(OC\\\\Files\\\\Node\\\\File), 1500, 1500, true, false)\\n#3 \\\/opt\\\/owncloud\\\/apps\\\/gallery\\\/controller\\\/preview.php(117): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getPreviewData(Object(OC\\\\Files\\\\Node\\\\File), true, 1500, 1500, true, false)\\n#4 \\\/opt\\\/owncloud\\\/apps\\\/gallery\\\/controller\\\/previewcontroller.php(128): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getData(16, 1500, 1500)\\n#5 [internal function]: OCA\\\\Gallery\\\\Controller\\\\PreviewController->getPreview(16, 1500, 1500)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getPreview')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getPreview')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('PreviewControll...', 'getPreview', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/base.php(915): OC\\\\Route\\\\Router->match('\\\/apps\\\/gallery\\\/p...')\\n#13 \\\/opt\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/Preview.php\",\"Line\":112}"}
```

**Comment by SergioBertolinSG** [comment]
And https://github.com/owncloud/admin_audit/issues/35 is not fixed.

**Comment by sharidas** [comment]
Updated the PR. Took a different approach. Used the streamer code and `getSingleFile` -> https://github.com/owncloud/core/blob/master/lib/private/legacy/files.php#L261 when user tries to download single and multiple files.

**Comment by PVince81** [comment]
is this still needed?

**Comment by SergioBertolinSG** [comment]
@sharidas is this PR the one which is required for comments?

**Comment by sharidas** [comment]
Closing this PR. We don't need this PR.

**Comment by SergioBertolinSG** [comment]
Ah I was confused, I was referring to https://github.com/owncloud/core/pull/30118 , nevermind.

**Pull request closed without merging**
