### PR TITLE
[WIP] Introduce uikit

### PR DESCRIPTION
**Pull request by PVince81**
- [x] Makefile
- [ ] Fix core styling to not be destroyed by uikit side-effects
- [x] Basic owncloud uikit theme
- [x] Provide mechanism to compile basic owncloud uikit theme
- [ ] Provide mechanism to compile and load any uikit theme from theme app (idea: OC_Defaults::getMainCss() to load the theme's uikit CSS instead of the default one)

### CODE REVIEW

**Comment by PVince81** [comment]
@felixheidecke please checkin your stuff even if unfinished.

**Comment by felixheidecke** [comment]
K … editing the makefile takes up too much time for me. Here is what we need.

1. link `core/less/*` into `build/node_modules/uikit/custom/`
2. run `npm install && npm run compile` in `build/node_modules/uikit/`
3. copy `build/node_modules/uikit/dist/*` into `core/vendor/uikit/`
4. copy `build/node_modules/material-design-icons/*/svg/*.svg` to `core/vendor/material-design-icons/svg/`
5. copy `build/node_modules/material-design-icons/iconfont/*` to `core/vendor/material-design-icons/iconfont/`

Is this cool?

**Comment by PVince81** [comment]
@felixheidecke yes, I can try to put this into the Makefile. Can you upload your less/sass files into the proposed locations ?

**Comment by PVince81** [comment]
Adjusted makefile: run `make uikit` and it will only rebuild if the files under "core/less" have changed, and the result is published in "core/vendor/uikit".

- [ ] Next up: the material design stuff

**Comment by PVince81** [comment]
@felixheidecke the copy operation fails:
```
cp -R build/node_modules/material-design-icons/*/svg/production/*.svg core/vendor/material-design-icons/svg/
cp: will not overwrite just-created 'core/vendor/material-design-icons/svg/ic_rv_hookup_24px.svg' with 'build/node_modules/material-design-icons/places/svg/production/ic_rv_hookup_24px.svg'
cp: will not overwrite just-created 'core/vendor/material-design-icons/svg/ic_rv_hookup_48px.svg' with 'build/node_modules/material-design-icons/places/svg/production/ic_rv_hookup_48px.svg'
make: *** [Makefile:211: core/vendor/material-design-icons] Error 1
```

This is because some of the source dirs have the same file name so they would be overwritten.

Can you confirm that this copy above is exactly what we want or is there another way ? Is there a build step that first puts everything into an output directory ?

If name conflicts are expected I can change the command to ignore those.

**Comment by PVince81** [comment]
Will use bower instead

**Comment by PVince81** [comment]
@felixheidecke please try again (`make clean; make`), it will now pull material design icons through bower and put them into "core/vendor/material-design-icons". 

However it doesn't put everything into a "svg" folder, I hope it's ok. There is an "iconfont" folder though.
I have the feeling that this is how this was intended to be used.

**Comment by PVince81** [comment]
I realize that the most difficult part of themeing is not about loading the theme CSS. This could simply be done in "app.php" or somewhere relevant with the proper API.

The difficult part is compiling the theme's LESS file.

For that there are at least two possible approaches:

1) Let the app's Makefile do it: need instructions, npm, etc. We could provide a script or a rules file "owncloud-uikit.mk" file that provides the command/target for the app + documentation

or

2) Have the app use core's build system to build it.

or

3) Have an occ command that runs npm, etc as shell commands...

Thoughts ?

I think I prefer approach 1) as it's almost self-contained.

**Comment by PVince81** [comment]
another concern that was raised: some admins want to tweak their theme on a productive system. In general we advise against that. Those admins will likely complain if they cannot build their LESS file directly there due to lack of build tools / npm.

**Comment by PVince81** [comment]
- [ ] if theme app enabled, don't load the UIKit owncloud.css (or is there a way to override)

**Comment by PVince81** [comment]
will wait for https://github.com/owncloud/core/pull/30088 to be merged before rebasing.

this will make it possible to load UIKit stuff through webpack

**Comment by PVince81** [comment]
note: I have already prepared a branch "introduce-uikit-2" containing this rebased code and made compatible with https://github.com/owncloud/core/pull/30088

**Comment by PVince81** [comment]
close in favor of https://github.com/owncloud/core/pull/30166

**Pull request closed without merging**
