### PR TITLE
[IE8] Fix checkboxes in login page and file list

### PR DESCRIPTION
**Pull request by PVince81**
- Fixes checkbox in the file list
- Fixes checkbox in the login page (it is **almost** aligned, I can't get it to align better and don't want to spend another hour just for a few pixels)

You might see that the "Delete" action when selecting all files is dangling, this is another issue that exists since 8.1, to be fixed separately (not easy)

Please review @MorrisJobke @SergioBertolinSG @Henni @rullzer @schiesbn

### CODE REVIEW

**Comment by PVince81** [comment]
@davitol

**Comment by MorrisJobke** [comment]
Tested and works :+1:

Awesome job @PVince81! Many thanks :)

Also tested with Firefox and there it still works.

cc @Henni

**Comment by Henni** [comment]
Looks good to me :+1:

BTW I completely understand your branch name...

**Comment by PVince81** [comment]
@DeepDiver1975 please merge (CSS only)

**Pull request merged**
