### PR TITLE
Move \OCP\Authentication to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @nickvergessen @MorrisJobke @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
@rullzer another rebase to kick Jenkins ?

**Comment by DeepDiver1975** [comment]
> @rullzer another rebase to kick Jenkins ?

hold your horses ... that guy is already busy ...

**Pull request merged**
