### PR TITLE
Do not rewrite letsencrypt .well-known URI

### PR DESCRIPTION
**Pull request by knox**
This excludes the URI `.well-known/acme-challenge` from beeing rewritten to HTTP 404 in order to allow an owncloud installation to be verified by letsencrypt client, e.g. using the webroot or manual plugins. See https://letsencrypt.readthedocs.org/en/latest/using.html#webroot for details.

### CODE REVIEW

**Comment by icewind1991** [comment]
Makes sense, cant test atm (nginx here)

**Comment by knox** [comment]
I had tested this with 8.2.1 stable and it worked for me.

Sorry to say: _after_ having issued this pull request i realized that it might be incomplete for master branch because there is another rewrite rule i wasn't aware of.

Probably my [additional ```RewriteCond```](https://github.com/knox/core/blob/27f420e0a797f8a56b5e83e8dd8e19df289c766b/.htaccess#L45) should also be placed before that other [```RewriteRule```] (https://github.com/knox/core/blob/27f420e0a797f8a56b5e83e8dd8e19df289c766b/.htaccess#L63), too.

**Comment by MorrisJobke** [comment]
> Sorry to say: after having issued this pull request i realized that it might be incomplete for master branch because there is another rewrite rule i wasn't aware of.
> 
> Probably my additional RewriteCond should also be placed before that other RewriteRule, too.

cc @LukasReschke because you introduced the new rules ;)

**Comment by LukasReschke** [comment]
No idea about LE, sorry. :speak_no_evil:

**Comment by mbiebl** [comment]
@LukasReschke The issue here is, that when using the webroot method of letsencrypt, it places a token file under .well-known/acme-challenge/<token>

If you try to access that url, you get:
"Datei nicht gefunden
Das ausgewählte Dokument wurde auf dem Server nicht gefunden."

So the automatic domain verification fails.

We need to disable rewriting for the .well-known/acme-challenge/ path.

**Comment by PVince81** [comment]
@LukasReschke in the light of the clarification, is this rewrite exclusion acceptable ?

**Comment by Sailing74** [comment]
Not sure what the status of this is. In case it helps: I ran into this issue as well, and the change suggested here fixed it for me.

**Comment by LukasReschke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
fine for me as well :+1:

**Comment by FlorentCoppint** [comment]
Will this patch be included in future 8.2.x release ?

**Comment by DeepDiver1975** [comment]
> Will this patch be included in future 8.2.x release ?

very unlikly - new feature always go into the next version - we only backport critical bug fixes

**Comment by MorrisJobke** [comment]
> very unlikly - new feature always go into the next version - we only backport critical bug fixes

It's some kind of bug that this is fixing.

**Comment by DeepDiver1975** [comment]
sure - but given the regressions we had after 9.0 because of our changes in htaccess we should consider carefully

**Comment by MorrisJobke** [comment]
> sure - but given the regressions we had after 9.0 because of our changes in htaccess we should consider carefully

Okay :)

**Pull request merged**
