### PR TITLE
Make sure all sharing tests extend the testcase

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 maybe this helps,

I can still not reproduce the issue locally, because it depends on the run order of tests

### CODE REVIEW

**Comment by MorrisJobke** [comment]
o.O

```
PHP Fatal error:  Cannot use 'Null' as class name as it is reserved in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/memcache/null.php on line 11
END INDEX
Testing with sqlite ...
PHP Fatal error:  Uncaught Exception: Not installed in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/base.php:223
Stack trace:
#0 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/base.php(558): OC::checkInstalled()
#1 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/base.php(1039): OC::init()
#2 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/tests/bootstrap.php(11): require_once('/ssd/jenkins/wo...')
#3 phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php(58): include_once('/ssd/jenkins/wo...')
#4 phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php(42): PHPUnit_Util_Fileloader::load('/ssd/jenkins/wo...')
#5 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(751): PHPUnit_Util_Fileloader::checkAndLoad('/ssd/jenkins/wo...')
#6 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(579): PHPUnit_TextUI_Command->handleBootstrap('/ssd/jenkins/wo...')
#7 phar:///usr/local/bin/php in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/base.php on line 223
```

cc @DeepDiver1975

**Comment by nickvergessen** [comment]
@MorrisJobke nothing to `O.o` :stuck_out_tongue: 
Stable8 is not php7 compatible, so this is expected

**Comment by MorrisJobke** [comment]
> Stable8 is not php7 compatible, so this is expected

Ah...I didn't notice that this is a backport :see_no_evil:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
lets merge this to fix stable8 ci

**Pull request merged**
