### PR TITLE
[Stable10] Replay migrations on the created schema before copying data

### PR DESCRIPTION
**Pull request by VicDeo**
Backport of https://github.com/owncloud/core/pull/30643

Ref https://github.com/owncloud/core/issues/27075#issuecomment-351673046
and some  more fixes:

- answer  'n' to the 'continue' question was ignored
- added a new line after progressbar completion. Because this sucks:
```
oc_account_terms
    0 [>---------------------------]oc_accounts
 1/1 [============================] 100%oc_addressbookchanges
```
now it looks like this:
```
oc_account_terms
    0 [>---------------------------]
oc_accounts
 1/1 [============================] 100%
oc_addressbookchanges
```

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Comment by micbar** [comment]
@VicDeo Why do we have a different coverage than on master?

**Comment by VicDeo** [comment]
@micbar 
no idea, I can't even say why
```
#javascript | 53.85% <ø> (?) | 0 <ø> (?) |  
#phpunit | 65.9% <37.09%> (+0.09%) | 20118 <37> (+18)
```
so #javascript is the same and #phpunit increased by +0.09% but it will **decrease** coverage by 1.06% according to https://github.com/owncloud/core/pull/35390#issuecomment-497728874

**Comment by micbar** [comment]
@VicDeo another random failure on CI

**Comment by VicDeo** [comment]
after several rebases it has been passed finally.

**Pull request merged**
