### PR TITLE
fix objectstore rename

### PR DESCRIPTION
**Pull request by butonic**
## Description
This PR makes oc keep the old fileId when using PUT. Objectstorage implementations do not need a part file. Metadata is kept in the filecache, no scanning is possible.

## Motivation and Context
fileids must be stable or shares, tags and comments get lost

## How Has This Been Tested?
locally with minio and the desktop client.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
When trying to use objectstore in master I am getting an internal error. Creation of new files is not allowed.

(using 9.1.4 works fine)

```
{"reqId":"liPFTFOdsjws6RY6B3oX","remoteAddr":"82.159.139.58","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(135): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(206): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/base.php(898): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":570}","level":3,"time":"2017-03-01T11:28:43+00:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"admin"}
```

**Comment by butonic** [comment]
@SergioBertolinSG I assume the files folder tor the home storage of your user ha not been created:

try 
```diff
--- a/lib/private/Files/ObjectStore/HomeObjectStoreStorage.php
+++ b/lib/private/Files/ObjectStore/HomeObjectStoreStorage.php
@@ -37,6 +37,10 @@ class HomeObjectStoreStorage extends ObjectStoreStorage implements \OCP\Files\IH
                }
                $this->user = $params['user'];
                parent::__construct($params);
+               //initialize cache with files directory
+               if ( ! $this->is_dir('files') ) {
+                       $this->mkdir('files');
+               }
        }
 
        public function getId () {
```

**Comment by SergioBertolinSG** [comment]
Adding this code the starting internal error is gone. But the creation of files is still failing. Creating a text file shows an error, the file is created but cannot be opened. Also uploading a picture cannot be opened also.

**Comment by butonic** [comment]
well, you know ... what error?

**Comment by SergioBertolinSG** [comment]
screen shot 2017-03-01 at 13 54 16

**Comment by butonic** [comment]
@SergioBertolinSG anything in the log?

**Comment by SergioBertolinSG** [comment]
Yes I've added it in https://github.com/owncloud/core/pull/27281#issuecomment-283329715

**Comment by butonic** [comment]
hm, what objectstorage are you testing against

**Comment by SergioBertolinSG** [comment]
> hm, what objectstorage are you testing against

Minio https://hub.docker.com/r/webhippie/minio/

**Comment by butonic** [comment]
I can reproduce. It seems the files don't even make it to minio ... actually it doas, but is immediately deleted ... meh, this PR needs rework.

**Comment by butonic** [comment]
@SergioBertolinSG can you test again?

**Comment by SergioBertolinSG** [comment]
But the code added in https://github.com/owncloud/core/pull/27281#issuecomment-283328085 is not included in this PR, so that is still failing.

**Comment by SergioBertolinSG** [comment]
Adding those lines it is working fine.

Also issue is fixed.

**Comment by butonic** [comment]
ok, I have not yet found out why sometimes the files folder is not created. It should be created automatically on the first login of a user. My feeling is that it has to do with copying the skeleton... @SergioBertolinSG can you try reverting the patch from https://github.com/owncloud/core/pull/27281#issuecomment-283328085 and logging in with a new user?

**Comment by SergioBertolinSG** [comment]
Reverting https://github.com/owncloud/core/pull/27281#issuecomment-283328085 and creating a new user has worked fine.

Seems to be only a problem with admin user (first user) at first login.

**Comment by butonic** [comment]
backport to 9.1 requested

**Review by SergioBertolinSG — CHANGES_REQUESTED** [review]
Nothing has changed. First run throws an error. Admin user's files cannot be created.
```
{"reqId":"xkdzGqIxkNZteI3chXrB","remoteAddr":"HIDDEN_IP","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(135): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(206): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/base.php(898): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":570}","level":3,"time":"2017-03-08T16:28:50+00:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"admin"}
```

**Comment by PVince81** [comment]
Seems https://github.com/owncloud/core/issues/25826 is overdue (let storages tell whether they need part files or not). I'll tag it as junior job 😉

**Comment by butonic** [comment]
> Nothing has changed. First run throws an error. Admin user's files cannot be created
unrelated to the original issue, as you yourself said in https://github.com/owncloud/core/pull/27281#issuecomment-283581874

**Comment by PVince81** [comment]
@butonic 

Unit test needs adjustment:
```
17:36:28 1) OCA\DAV\Tests\unit\Connector\Sabre\FileTest::testPutSingleFileCancelPreHook
17:36:28 Failed asserting that false is true.
17:36:28 
17:36:28 /var/lib/jenkins/workspace/owncloud-core_core_PR-27281-ZLEMELGGQSHOW5XAXE7CTMNN3YKEXHZEQRZ6O7WK7AO32G534PTQ/apps/dav/tests/unit/Connector/Sabre/FileTest.php:535
```

**Comment by PVince81** [comment]
Selenium test failure unrelated, merging.

**Comment by butonic** [comment]
backport request to 9.1

**Pull request merged**
