### PR TITLE
[stable9] Add repair step for updater issues

### PR DESCRIPTION
**Pull request by LukasReschke**
The updater as shipped with ownCloud =< 9.0.1 has several bugs leading to a not properly executed update. For example the third-party changes are not copied.

This pull request:
1. Ships the third-party files changed since ownCloud 9.0.1 in the resources folder. On update the files are replaced. (https://github.com/owncloud/updater/issues/316)
2. Adds updater/\* and _oc_upgrade/\* as an exemption to the code integrity checker since the updater is updating in the wrong order. (https://github.com/owncloud/updater/issues/318)

Most of this code are actually the missed files. This is what is included in `resources/`.

@DeepDiver1975 @karlitschek @VicDeo Please review.
@karlitschek Please approve.

I'd recommend to get this in as soon as possible so we can have some proper testing on this including also the daily channel.

Fixes https://github.com/owncloud/core/issues/23997
Fixes https://github.com/owncloud/core/issues/23857

### CODE REVIEW

**Comment by LukasReschke** [comment]
Relevant changed files:

- [checker.php](https://github.com/owncloud/core/pull/24134/files#diff-5e9a24cf87de95470f56db008c32364a)
- [excludefoldersbypathfilteriterator.php](https://github.com/owncloud/core/pull/24134/files#diff-de53eaf13d189f04a2c2fa14e910abcc)
- [repair.php](https://github.com/owncloud/core/pull/24134/files#diff-d44a4c8919d4194b72e20cce773d88bc)
- [brokenupdaterrepair.php](https://github.com/owncloud/core/pull/24134/files#diff-3bcd5fec98c316c6c45e324cdf242b2d)

**Comment by karlitschek** [comment]
not tested but looks ok. As discussed. 👍 We need some full testing for that somehow.

**Comment by PVince81** [comment]
@LukasReschke I guess we don't need a master PR and this PR is to cleanup the mess that was done by the updater between 9.0.1 and 9.0.2 ?

**Comment by PVince81** [comment]
Are there any steps to reproduce for QA to test this ?

@VicDeo would be good if you could help to quickly review and test this so we can get it merged for tomorrow's daily.

CC @owncloud/qa

**Comment by VicDeo** [comment]
According to @DeepDiver1975 updater should be able to update itself separately from core update (not implemented yet) 
so updater/* should not be checked with core.

**Comment by LukasReschke** [comment]
> According to @DeepDiver1975 updater should be able to update itself separately from core update (not implemented yet) 
> so updater/* should not be checked with core.

The PR adds this. _HOWEVER_, I'm not willed to add this to master as well until this has actually been implemented.

**Comment by LukasReschke** [comment]
> @LukasReschke I guess we don't need a master PR and this PR is to cleanup the mess that was done by the updater between 9.0.1 and 9.0.2 ?

Correct, and 9.0.0 to 9.0.2.

> Are there any steps to reproduce for QA to test this ?

That's kinda hard to test reliably, the easiest way would be to get this into the stable9 branch and test to update from 9.0.0 to 9.0-daily once this has been merged. Another way would be to modify the code to download a build with this changes included.

So I'd say there is no real way to test this except waiting for being this in daily. I mean I surely can post the ways that I tested this locally here but it will involve modifying 5 files in ownCloud and is not really a representative real life test 😢

**Comment by VicDeo** [comment]
@LukasReschke Looks good, I was about to start testing in a hard way. 
:+1:

**Comment by PVince81** [comment]
@LukasReschke @VicDeo Ok then, once this is on daily, what are the steps to reproduce the issue and run the fix ?

**Comment by nickvergessen** [comment]
@PVince81 
Install 9.0.0
Update to 9.0.1
Run code checker => :x: 

Install 9.0.0
Update to daily
Run code checker :white_check_mark:

**Comment by PVince81** [comment]
@nickvergessen thanks, did you get that @owncloud/qa ? :smile: 

Merging then

**Comment by PVince81** [comment]
Button grayed out :frowning: 

@DeepDiver1975 can you merge this ?

**Comment by VicDeo** [comment]
Tested
Updating 9.0 to ownCloud 9.0.1 (daily) Build:2016-04-22T03:03:05+00:00 6365851672a64aa515afc7310d018bea136819f3
`sudo -u www-data php occ integr:check-core` 
passed with no errors

**Pull request merged**
