### PR TITLE
Remove double quotes from boolean values in status.php output

### PR DESCRIPTION
**Pull request by mmattel**
## Description
This PR removes double quotes unintentionally added in the boolean result values from status.php
An QA issue has been raised https://github.com/owncloud/QA/issues/500 (Add scenario to check status.php output)
A documentation release note PR follows asap

## Related Issue
#29228 (Change in status.php from 9.1.x to 10.x)

## How Has This Been Tested?
Access yourdomain/status.php
```
{"installed":true,"maintenance":false,"needsDbUpgrade":true,"version":"10.0.3.3","versionstring":"10.0.3","edition":"Community","productname":"ownCloud"}
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@mmattel please backport to stable10, thanks a lot!

**Comment by PVince81** [comment]
Waiting for Travis...

**Comment by mmattel** [comment]
@PVince81 mind to help me how to backport? I have never done that before and no clue...

**Comment by PVince81** [comment]
@mmattel create a branch from stable10, then git cherry-pick your commits onto that branch. Then push and create a pull request that targets stable10 instead of master.

**Comment by mmattel** [comment]
This worked fine...
```
sudo git checkout -b bp_stable10 origin/stable10
Checking out files: 100% (1432/1432), done.
Branch stable10 set up to track remote branch stable10 from origin.
Switched to a new branch 'bp_stable10'

sudo git cherry-pick 893a9f0
[bp_stable10 ec81f45] Remove double quotes from boolean values in status.php output
 Date: Mon Oct 16 17:48:19 2017 +0200
 1 file changed, 3 insertions(+), 3 deletions(-)
```

But either ``sudo git push`` or ``sudo git push -u origin stable10`` reports me following error:
```
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 481 bytes | 0 bytes/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/stable10.
remote: error: 3 of 3 required status checks are expected. At least one approved review is required by reviewers with write access.
To https://github.com/owncloud/core.git
 ! [remote rejected] stable10 -> stable10 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/owncloud/core.git'
```

What am I doing wrong?

**Comment by phil-davis** [comment]
You should not push back to stable10. My commands would be something like:
1) get stable10 up to date from GitHub
```
git fetch origin
git checkout stable10
git pull
```

2) branch and cherry-pick
```
git checkout -b stable10-fix_for_29228
git cherry-pick <commit-id>
git push
```
and follow the message that ``git push`` gives you to make ``stable10-fix_for_29228`` push itself to origin.

Then go to GitHub and it will be siggesting for you to make a PR from that branch - make the PR to ``stable10`` ...

**Comment by PVince81** [comment]
glad to be reminded that pushing to stable10 directly is forbidden in the repo settings 😄

**Comment by mmattel** [comment]
I created a documentation PR https://github.com/owncloud/documentation/pull/3463 to guide backporting

**Comment by mmattel** [comment]
Q: is it necessary to have that documented so admins know we have fix it in 10.0.4?

**Comment by PVince81** [comment]
I think the known issues section is enough for now.

**Pull request merged**
