### PR TITLE
[stable9.1] Update icewind/streams to 0.5.2 in files_external

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/26974

Please review @jvillafanez @DeepDiver1975 

I had a quick test with SMB and it still works.

### CODE REVIEW

**Comment by jvillafanez** [comment]
Maybe we should change the title to avoid confusion. The library version is 0.5.2

**Comment by jvillafanez** [comment]
Other than that 👍

**Comment by PVince81** [comment]
Indeed... once again I mistyped the version.

Oh, and there's a fail.

**Comment by PVince81** [comment]
```
Parse error: ./apps/files_external/3rdparty/composer/autoload_static.php:20

    18|         'Icewind\\Streams\\' => 

    19|         array (

  > 20|             0 => __DIR__ . '/..' . '/icewind/streams/src',

    21|         ),

    22|         'Icewind\\SMB\\' => 

Unexpected '.', expecting ')'
```

Syntax error specific to PHP <= 5.5... will fix manually.

**Comment by PVince81** [comment]
Are you kidding me ??

```
Parse error: ./apps/files_external/3rdparty/composer/autoload_static.php:20

    18|         'Icewind\\Streams\\' => 

    19|         array (

  > 20|             __DIR__ . '/..' . '/icewind/streams/src',

    21|         ),

    22|         'Icewind\\SMB\\' => 

Unexpected '.', expecting ')'
```

**Comment by PVince81** [comment]
Strangely this file didn't exist in the past.
Maybe I need to use an old version of composer to create this ? Or delete it ?

**Comment by PVince81** [comment]
Apparently this is expected behavior by composer (so it in various tickets when searching "autoload_static.php syntax error"). The thing is that "autoload_real.php" will pick the correct file depending on the PHP version here https://github.com/owncloud/core/pull/26986/files#diff-061a0039b0df9e1a2d214d7c0ab61e1bR26

So if it's PHP < 5.6 it will not load that file.

The syntax error is reported by our linter so we should probably make it exclude this file when the env is PHP < 5.6. @DeepDiver1975 agreed ?

**Comment by DeepDiver1975** [comment]
> The syntax error is reported by our linter so we should probably make it exclude this file when the env is PHP < 5.6. @DeepDiver1975 agreed ?

agreed

**Comment by PVince81** [comment]
Oh look, it seems we already do that for core's 3rdparty. I've added the one from apps/files_external now: https://github.com/owncloud/core/pull/26986/commits/5be0ff7514860b8e20bcc729359bae763928e126

If tests pass now I'll merge this.

**Comment by PVince81** [comment]
MEEP... missing space

**Comment by PVince81** [comment]
Here we go, fixed and rebased

**Pull request merged**
