### PR TITLE
Always installed apps includes the hardcoded ones from shipped.json

### LINKED ISSUE #20568: Files not installed?
Sorry if this is the wrong project, I don't know if Files is still part of the Core.

My sync client refuses to work after upgrading to OC8. It keeps receiving error 500. I checked OC error log and the message is that Files app is not installed. Obviously it's there, the "files" menu item is there and it shows my files.

Using OC 8.1.4

<pre>
{"reqId":"xxxxxxxxxxxx","remoteAddr":"xxxxxxxxx","app":"webdav","message":"Exception: {"Message":"HTTP/1.1 503 Exception: App not installed: files","Code":0,"Trace":"#0 [internal function]: {closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#1 /owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)
#2 /owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(456): Sabre\Event\EventEmitter->emit('beforeMethod', Array)
#3 /owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#4 /owncloud/remote.php(64): Sabre\DAV\Server->exec()
#5 /owncloud/remote.php(135): handleException(Object(Exception))
#6 {main}","File":"/owncloud/remote.php","Line":62}","level":4,"time":"2015-11-18T10:44:24+00:00"}
</pre>

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #20568 

Simply delete the "files, enabled, yes" entry from oc_appconfig and check the webdav endpoint.

cc @nickvergessen @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@DeepDiver1975 This seems to kill the unit tests, because now dav is enabled and the unit tests are also called for the enabled apps. :see_no_evil:

**Comment by DeepDiver1975** [comment]
So ... Fix it

**Comment by MorrisJobke** [comment]
> So ... Fix it

:white_check_mark:

**Comment by MorrisJobke** [comment]
> cc @nickvergessen @DeepDiver1975 @LukasReschke

Review is much appreciated ;)

cc @rullzer

**Comment by PVince81** [comment]
I checked out this branch and ran the upgrade, but oc_appconfig still contains these entries:
```
| dav               | enabled                  | yes
| files             | enabled                  | yes
```

Or did I misunderstand what this PR is doing ?

**Comment by nickvergessen** [comment]
This PR ignores the setting. Set the values to false or remove them. They should still get enabled while running tests

**Comment by MorrisJobke** [comment]
> This PR ignores the setting. Set the values to false or remove them. They should still get enabled while running tests

Correct. It only just should show the apps as enabled even if the DB says something different (missing entry or set to false). That's why they are set to "always enabled". ;)

**Comment by rullzer** [comment]
We should have a repair step that clear the db entries. If we are not going to be using them they will at some point cause confusion.

Tested and acts as expected :+1:

**Comment by MorrisJobke** [comment]
> We should have a repair step that clear the db entries. If we are not going to be using them they will at some point cause confusion.

I would keep them. They don't hurt and will be added again on every update.

**Comment by MorrisJobke** [comment]
@PVince81 @LukasReschke @nickvergessen Please review

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @karlitschek Should we backport this (of course without the adjustments of the unit tests to dav)?

**Comment by karlitschek** [comment]
@DeepDiver1975 what do you suggest?

**Comment by DeepDiver1975** [comment]
should not hurt

**Comment by karlitschek** [comment]
ok. let's backport please

**Comment by MorrisJobke** [comment]
I just noticed that the problem only exists in master because of the refactoring in https://github.com/owncloud/core/pull/19837 

A backport then doesn't make sense. Sorry for the noise :see_no_evil:

**Comment by karlitschek** [comment]
cool. better to look into it then to forget a potential backport :-)

**Pull request merged**
