### PR TITLE
[Stable10] cleanup drone

### PR DESCRIPTION
**Pull request by patrickjahns**
Backport of #30578

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@patrickjahns this commit will fix this - https://github.com/owncloud/core/pull/28043/commits/44181bab615d1ba65a2e9d2dbb8706d288cf9bff

**Comment by patrickjahns** [comment]
@DeepDiver1975 
separate backport or put on top here?

**Comment by DeepDiver1975** [comment]
> c9ccd3b

ok



> 407a70d

not needed - the issue is related to changes in doctrine dbal 2.6+

**Comment by DeepDiver1975** [comment]
> separate backport or put on top here?

just put on top

**Comment by patrickjahns** [comment]
Coverage drop is because we are now tracking coverage from `files_external` which we did not do before

Compared to `master` - we have a lot more external storage backends still in stable10 - they are not yet migrated/moved to their own app

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
