### PR TITLE
the path of a mount config may be an empty string, which requires a nullable column on oracle

### PR DESCRIPTION
**Pull request by butonic**
without this files_external is broken on oracle

### CODE REVIEW

**Comment by butonic** [comment]
cc @PVince81 because he wanted me to give him oracle

**Comment by PVince81** [comment]
Since you changed the structure, we need to increase version.php

**Comment by butonic** [comment]
oh great, doctrine does not correctly generate the SQL. It wants to do
```sql
ALTER TABLE "oc_external_config" MODIFY ("config_id" NUMBER(20) DEFAULT NULL, "value" CLOB DEFAULT NULL NULL)
```

which leads to
```
SQL-Fehler: ORA-22296: Ungültige Option ALTER TABLE für Konvertierung von Datentyp LONG in LOB
22296. 00000 -  "invalid ALTER TABLE option for conversion of LONG datatype to LOB"
*Cause:    An attempt was made to specify ALTER TABLE options which are
           disallowed during conversion of LONG datatype to LOB. The only ALTER
           TABLE options allowed during conversion of LONG datatype to LOB are
           the default clause and LOB storage clause for the column being
           converted to LOB.
*Action:   Remove the disallowed options.
```
changing the config_id column is totally useless and regarding the ALTER for CLOB see http://stackoverflow.com/a/7443301

it should just be
```sql
ALTER TABLE "oc_external_config" MODIFY "value" NULL
```

@DeepDiver1975 @PVince81 we need that different update mechanism ...

**Comment by PVince81** [comment]
Yeah, it's not the first time. Last time we had to add specific tweaks to make it accept adding autoincrement on columns.

**Comment by DeepDiver1975** [comment]
Doctrine migrations .... Doctrine migrations ... Doctrine migrations ...

**Comment by PVince81** [comment]
> Doctrine migrations .... Doctrine migrations ... Doctrine migrations ...

Time to revive ?

**Comment by PVince81** [comment]
needs rewrite, the tables were moved to core and are using a doctrine migration for their creation

**Comment by PVince81** [comment]
conflicts

since this is inactive I'm moving this to triage to reconsider priority

**Comment by PVince81** [comment]
obsolete, please rewrite this with a migration in a separate PR

**Pull request closed without merging**
