### PR TITLE
cache found l10n per app and not globally

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes: if the first call to this is with an app that has no translations
  all future call will get a list with only english in there - even
  if their l10n holds more translations

cc @nickvergessen @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
can we kill that static bubu and add some unit test around?

**Comment by icewind1991** [comment]
Changes look good :+1: 

Tests would indeed be nice

**Comment by MorrisJobke** [comment]
> can we kill that static bubu and add some unit test around?

I don't think that refactoring this into unit testable code base is a good thing during the feature freeze.

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
