### PR TITLE
Prevent LOCK/UNLOCK methods from public endpoint

### LINKED ISSUE #34347: Public webdav should not be able to lock read-only public links
### Steps

1. Create a folder "test/share/abc"
1. Share "share" with link with "download only" mode
1. Copy the link token
1. Lock "abc" on the public webdav with curl: `curl -u $PUBLICTOKEN: -X LOCK http://localhost/owncloud/public.php/webdav/abc -d "<?xml version='1.0' encoding='UTF-8'?><d:lockinfo xmlns:d='DAV:'> <d:lockscope><d:exclusive/></d:lockscope></d:lockinfo>" -H 'Depth: infinite'`

### Expected result
Cannot lock as this is read-only access. The locks are there only for write access.

### Actual result
Lock acquired.

### Version
10.1.0 RC1

@davitol @individual-it @DeepDiver1975 seeing this I tend more in the direction of preventing the LOCK / UNLOCK verbs completely on public links. This will save a lot of pain and other related bugs. For now.

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Prevent LOCK/UNLOCK methods from public endpoint

## Related Issue
Fixes https://github.com/owncloud/core/issues/34347

## How Has This Been Tested?
- unit test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
might need additional acceptance test changes
cc @individual-it

**Review by phil-davis — APPROVED** [review]
Code looks good. See what acceptance tests now fail and adjust those for the changed behavior.

**Comment by PVince81** [comment]
I've adjusted the acceptance tests, let's see.

I've removed most of the tests by public. @individual-it sorry for losing your hard work on all these cases. If we ever bring this back we can restore from this commit.

Only two tests remain to check that public cannot lock or unlock.
For the lock case, we get 403.
For unlock, I needed an owner with a lock, and the error is 409 instead of 403.

**Comment by PVince81** [comment]
Closes https://github.com/owncloud/core/issues/34347
Closes https://github.com/owncloud/core/issues/34304
Closes https://github.com/owncloud/core/issues/34302

**Comment by PVince81** [comment]
removed even more obsolete tests, squashed

**Comment by PVince81** [comment]
added a note in https://github.com/owncloud/core/issues/34222#issuecomment-459515698 so we can remember that there are tests we can recover once we address federation with locking

**Comment by PVince81** [comment]
annnnd one last deletion, squashed.

CI should pass now, then @individual-it @phil-davis can review the test changes

**Review by individual-it — APPROVED** [review]
@PVince81 reviewed the deleted tests, they look good ;-)

**Comment by phil-davis** [comment]
Backport ``stable10`` #34355

**Pull request merged**
