### PR TITLE
Fix file drag and drop JS error

### LINKED ISSUE #18349: sidebar breaks file move operation
Steps to reproduce:

- create a folder "folder"
- create a file 
- try to drag & drop file to folder

Expected:
file gets moved to folder

Actual result:
empty sidebar opens and move operation fails

JS Console:

````TypeError: $el.attr is not a function                share.js:66:32````

cc @jancborchardt @PVince81 @blizzz

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/18349

Please review @schiesbn @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] BUG: dragging on parent folder breadcrumb doesn't move but says "file already exists"

**Comment by PVince81** [comment]
Fixed

**Comment by PVince81** [comment]
Yeah I know, I force-pushed...

**Comment by PVince81** [comment]
Jenkins PR https://github.com/owncloud/core/pull/18355

**Comment by MorrisJobke** [comment]
Tested and works :+1:

Code looks good

**Comment by PVince81** [comment]
needs a second reviewer @schiesbn @blizzz @rullzer

**Comment by PVince81** [comment]
or @nickvergessen ?

**Comment by rullzer** [comment]
Tested and works.
Code looks good.
:+1:

**Pull request merged**
