### PR TITLE
Check that user can reset their password using email address

### PR DESCRIPTION
**Pull request by paurakhsharma**
## Description
This PR adds tests to check that user should be able to reset password using their email address

Related issue: #32889 

Other relevant issue: #32868

## How Has This Been Tested?
Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
As discussed, the 2nd scenario will fail in the 1st commit, and demonstrates the issue. 
Then make a 2nd commit to skip the 2nd scenario.

**Review by phil-davis — APPROVED** [review]
The skip is good in the 2nd commit.

**Comment by phil-davis** [comment]
@paurakhsharma please make a backport, and put just 1 commit at first. That will demonstrate what fails in ``stable10``. Then push the 2nd commit to the backport.

**Comment by phil-davis** [comment]
The test that fails outputs:
```
  Scenario: reset password for the ordinary (no encryption) case                                 # /drone/src/tests/acceptance/features/webUILogin/resetPasswordUsingEmail.feature:29
    When the user requests the password reset link using the webUI                               # WebUILoginContext::theUserRequestsThePasswordResetLinkUsingTheWebui()
    And the user follows the password reset link from email address "u1@oc.com.np"               # WebUILoginContext::theUserFollowsThePasswordResetLinkFromTheirEmail()
    Then the user should be redirected to a webUI page with the title "ownCloud"                 # WebUIGeneralContext::theUserShouldBeRedirectedToAWebUIPageWithTheTitle()
    When the user resets the password to "%alt1%" using the webUI                                # WebUILoginContext::theUserResetsThePasswordToUsingTheWebui()
      Form field with id|name|label|value|placeholder "password" not found.
      
      +--[ https://server/lostpassword/reset/form/iWvdTT6ziSAXuRwnNFqYY/u1@oc.com.np | Selenium2Driver ]
      |
      |  <!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" class="ng-csp" data-placeholder-focus="false" lang="en"><head data-requesttoken="J2kbbioBAAk7VQ8TAhlXJCkPAxAUPhgPGB0IARsTABU=:B+b/njPlWawDMzoipjLZaYBH7gjynwLDA8NvTOxddm4=">
      |  		<meta charset="utf-8" />
      |  		<title>
      |  		ownCloud		</title>
      |  		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
      |  		<meta name="referrer" content="never" />
      |  		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
      |  					<meta name="apple-itunes-app" content="app-id=543672169" />
      |  				<meta name="theme-color" content="#1d2d44" />
      |  		<link rel="icon" href="/core/img/favicon.ico" />
      |  		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png" />
      |  		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44" />
      |  					<link rel="stylesheet" href="/core/vendor/select2/select2.css?v=b13721f0b8b600f33377e995043797fb" />
      |  					<link rel="stylesheet" href="/core/css/styles.css?v=b13721f0b8b600...
      |
    Then the email address "u1@oc.com.np" should have received an email with the body containing # EmailContext::assertThatEmailContains()
      """
      Password changed successfully
      """
    When the user logs in with username "user1" and password "%alt1%" using the webUI            # WebUILoginContext::theUserLogsInWithUsernameAndPasswordUsingTheWebUI()
    Then the user should be redirected to a webUI page with the title "Files - ownCloud"         # WebUIGeneralContext::theUserShouldBeRedirectedToAWebUIPageWithTheTitle()
SCENARIO RESULT: (fail)

--- Failed scenarios:

    /drone/src/tests/acceptance/features/webUILogin/resetPasswordUsingEmail.feature:29

9 scenarios (8 passed, 1 failed)
52 steps (48 passed, 1 failed, 3 skipped)
```

**Comment by paurakhsharma** [comment]
Backport on: #32886

**Pull request merged**
