### PR TITLE
Reduce amount of rows to update

### PR DESCRIPTION
**Pull request by VicDeo**
Ref https://github.com/owncloud/core/issues/16791

### CODE REVIEW

**Comment by VicDeo** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
looks good. not tested :+1:

**Comment by nickvergessen** [comment]
@VicDeo you missed to fetch the value from the query, instead you tried to use the query as a string.
I pushed a fix.

:+1: for the rest of the code

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
@MorrisJobke easy to review? :wink:

**Comment by MorrisJobke** [comment]
Works :+1:

**Pull request merged**
