### PR TITLE
[full-ci] Add Cache-Control to default allowedCorsHeaders

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
I'm trying to get this PR green: https://github.com/owncloud/web/pull/6494
It makes certain requests from oC Web send a Cache-Control header, which fails in a CORS setup.
As you can see, I added `php occ config:system:set cors.allowed-headers --type json --value '["cache-control"]'` which fixed the tests locally for me. Still waiting for the CI to finish at this moment.

## Motivation and Context
c.f. https://github.com/owncloud/web/pull/6447
"When apps (i.e Drawio) try to load a file, the browser caches the request.
If the file was modified somewhere else, this causes inconsistent results which prevent saving any changes until the cache is properly cleared.

We had observed this is the past in our text editor, hence the noCache addition to the SDK. Now we also saw it in Drawio."

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuth-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/35489/47

**Comment by dschmidt** [comment]
Are those CI failures expected? Cannot make sense of them in relation to my change

**Comment by phil-davis** [comment]
> Are those CI failures expected? Cannot make sense of them in relation to my change

https://drone.owncloud.com/owncloud/core/35490/10/8
There were 5 failures:
And all are in CorsPluginTest

That seems related.

**Comment by dschmidt** [comment]
You're right, I did miss to see the actual failure, what I was seeing was just noise. Will fix!

**Review by IljaN — APPROVED** [review]

**Comment by dschmidt** [comment]
Why do the CI builds keep getting canceled? 
I just see canceled pipelines but no failed ones...

**Comment by phil-davis** [comment]
> Why do the CI builds keep getting canceled? I just see canceled pipelines but no failed ones...

I noticed that. "someone" or "something" must be cancelling them. The drone timeout for the core repo is set to 3 hours at https://drone.owncloud.com/owncloud/core/settings

**Comment by dschmidt** [comment]
I've kept restarting it, but to no avail - it keeps being canceled. No idea why. Can anyone help me?

**Comment by dschmidt** [comment]
Aha, at last it looks like a real error: https://drone.owncloud.com/owncloud/core/35537/100/13

**Comment by dschmidt** [comment]
Aaaw yiiiss, finally green.

@IljaN wanna review again after my force push? Feel free to merge if you think this is ok.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
