### PR TITLE
[stable9] Backport of share id as string fix

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/23066

Backport of https://github.com/owncloud/core/pull/24689 to stable9

Please review @nickvergessen @icewind1991 @rullzer 

@TDannhauer I guess you already tested this on OC 9.0 ?

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by TDannhauer** [comment]
@PVince81 yes on my productive 9.0.1 system

**Comment by rullzer** [comment]
:+1:

**Comment by ianathompson** [comment]
Doesn't fix the gallery or the public share. Must add those 2 fixes to be complete. 

https://github.com/owncloud/core/issues/23066

**Comment by vssware** [comment]
**After upgrade to 9.0.3，the bug still exist!** 

`{"reqId":"hQAmZHF7DqrwRLkcM6if","remoteAddr":"10.25.67.244","app":"gallery","message":"Exception: Missing password (401)","level":3,"time":"2016-06-12T03:13:40+00:00","method":"GET","url":"\/apps\/gallery\/config.public?extramediatypes=1&token=pe2HtmaHHhjuHQp","user":"--"} {"reqId":"7yXSupTg9whiBdnZCSPj","remoteAddr":"10.25.67.244","app":"gallery","message":"Exception: Missing password (401)","level":3,"time":"2016-06-12T03:13:43+00:00","method":"GET","url":"\/apps\/gallery\/config.public?extramediatypes=1&token=pe2HtmaHHhjuHQp","user":"--"} {"reqId":"zPjV7JzvbLjWwawNBFom","remoteAddr":"10.25.67.244","app":"gallery","message":"Exception: Missing password (401)","level":3,"time":"2016-06-12T03:13:46+00:00","method":"GET","url":"\/apps\/gallery\/config.public?extramediatypes=1&token=pe2HtmaHHhjuHQp","user":"--"} {"reqId":"JGLdPWDNxrM7hBMikVXS","remoteAddr":"10.25.67.244","app":"gallery","message":"Exception: Missing password (401)","level":3,"time":"2016-06-12T03:13:50+00:00","method":"GET","url":"\/apps\/gallery\/config.public?extramediatypes=1&token=pe2HtmaHHhjuHQp","user":"--"} `

**Comment by PVince81** [comment]
Yes, see https://github.com/owncloud/core/issues/23066#issuecomment-230992681

**Pull request merged**
