### PR TITLE
[9.2] Share via social

### PR DESCRIPTION
**Pull request by DeepDiver1975**
bildschirmfoto von 2016-07-22 15-08-12

ownCloud sharing moves on! We are now sharing via social media!

Supported share buttons:
- twitter
- diaspora
- facebook
- Google+
- mail

### CODE REVIEW

**Comment by tcitworld** [comment]
Just had a quick look : 
* could the title of the file also be put inside the sharing string ?
* Google+ gives me a 400 error.
* 404 on `/core/img/actions/mail-grey.svg`

**Comment by DeepDiver1975** [comment]
> 404 on /core/img/actions/mail-grey.svg

nice catch - thx

**Comment by DeepDiver1975** [comment]
> Google+ gives me a 400 error.

Mind submitting a screenshot?

**Comment by DeepDiver1975** [comment]
> could the title of the file also be put inside the sharing string ?

I was thinking about proper messages - but I could not really come up with something of value.
I think the folder/file name can easily be added manually.

Thanks for testing!

**Comment by tcitworld** [comment]
>>Google+ gives me a 400 error.

> Mind submitting a screenshot?

My bad, I should have specified, it's a 400 error on Google's side because it can't find the shared address since it's a local network one. Sad they don't authorize to post unreachable addresses.

oc_google_plus

I think it stays an issue in the case of people sharing some information to specific groups, but it can be ignored.

EDIT : It seems to have worked once, though.

> I think the folder/file name can easily be added manually.

Imho, it's easier to delete the folder/file name than to add it. :-)

**Comment by DeepDiver1975** [comment]
> My bad, I should have specified, it's a 400 error on Google's side because it can't find the shared address since it's a local network one. Sad they don't authorize to post unreachable addresses.

I guess this is related to the fact that you try to share something from localhost.

**Comment by DeepDiver1975** [comment]
> Imho, it's easier to delete the folder/file name than to add it. :-)

sure - shall we add only the file and folder name and let the user edit the rest?

**Comment by tcitworld** [comment]
> sure - shall we add only the file and folder name and let the user edit the rest?

My opinion is to keep both name and url.

**Comment by DeepDiver1975** [comment]
@jancborchardt maybe you have some ideas on how the messages for twitter, diaspora, google and mail (subject and body) should look like.

**Comment by DeepDiver1975** [comment]
Google and FB have no option to specify the message as far as I can tell

**Comment by tcitworld** [comment]
It seems so indeed. Is there a way to provide Open Graph information on the public link page about the folder/file (I can open a new issue for this) ?

**Comment by DeepDiver1975** [comment]
> Is there a way to provide Open Graph information on the public link page about the folder/file (I can open a new issue for this) ?

see #25579 :wink:

**Comment by tcitworld** [comment]
Right ! Seems good, then. :smile:

**Comment by jancborchardt** [comment]
Ah nice! But we need to make sure this doesn’t overcrowd the sharing sidebar where there is already a bunch of stuff going on.

- [ ] the email button seems like a duplication of the »share via email« line, right? Maybe best remove the input field above so it’s a line of icons
- [ ] the icons are too big, should be capped to 16*16px so they are the same size as the others
- [ ] We should combine this with the »copy link« function: Have a 3-dot icon next to the link, which opens a dropdown with: Copy link, Share to Facebook, Share to Twitter, etc. This then is very similar to how that works on iOS and Android, and at the same time doesn’t overcrowd the whole sidebar.

**Comment by DeepDiver1975** [comment]
Thanks for your feedback @jancborchardt - I'll have a look these days. Mind answering my question as of https://github.com/owncloud/core/pull/25576#issuecomment-234942577 :wink:

**Comment by rperezb** [comment]
@owncloud/qa can you please check this one?

**Comment by DeepDiver1975** [comment]
> the email button seems like a duplication of the »share via email« line, right? Maybe best remove the input field above so it’s a line of icons

Both mail features work a bit different:
The "old email" feature uses email addresses within ownCloud for autocompletion and the email is sent from owncloud. 
This "new email" feature simply starts the email client and the user can edit the body and choose emails from within the addressbook of the email client. Mails are sent from the client.

Both mechanisms have their benefit.

**Comment by DeepDiver1975** [comment]
> the icons are too big, should be capped to 16*16px so they are the same size as the others

bildschirmfoto von 2016-07-26 09-52-57

**Comment by DeepDiver1975** [comment]
> We should combine this with the »copy link« function: Have a 3-dot icon next to the link, which opens a dropdown with: Copy link, Share to Facebook, Share to Twitter, etc. This then is very similar to how that works on iOS and Android, and at the same time doesn’t overcrowd the whole sidebar.

I need to see if I find the time for all this css and js magic

**Comment by davitol** [comment]
:+1: WFM

But using Safari as browser, tooltips for twitter, facebook and diaspora are not shown properly

screen shot 2016-07-26 at 11 11 46
screen shot 2016-07-26 at 11 11 51
screen shot 2016-07-26 at 11 11 51

**Comment by jancborchardt** [comment]
@DeepDiver1975 I’d honestly just prefill the link in the message box. Anything else is just tacky and stock and people will get annoyed needing to delete it. (Just like a »Sent from my iPad« bullshit notice.)

Regarding the »old email« feature. Yeah, probably right. We should eventually make it so that sharing to people via emails is part of the share input, generates an individual revokable link, makes the ppl show up in the list etc. That will take care of that issue.

But still yes – the icons should be in a 3-dot-menu next to the link.

**Comment by LukasReschke** [comment]
I honestly don't see the need to add social sharing like that. I really really really really really really really really really really really really doubt that any average user ever will really use the "Share the file with Twitter" stuff. Just my two cents.

**Comment by DeepDiver1975** [comment]
> Regarding the »old email« feature. Yeah, probably right. We should eventually make it so that sharing to people via emails is part of the share input, generates an individual revokable link, makes the ppl show up in the list etc. That will take care of that issue.

topic on it's own

**Comment by wotanii** [comment]
I don't really know what to test, so I changed my instance of owncloud 8.2.7 to include this PR. 

- I moved all changes to public.php. It now look like [this](https://owncloud.wotanii.de/index.php/s/izhjalkDdzNjVCW)
- I shared some links:
  - password-protected: https://owncloud.wotanii.de/index.php/s/h5MyR1RUfG6AEV3/authenticate
  - pdf file: https://owncloud.wotanii.de/index.php/s/2N6pV82xi6FCD3r#pdfviewer
  - jpg: https://owncloud.wotanii.de/index.php/s/Q42PHXkSBW8x28P
- and when you send them via telegram, those links look like this: 
bildschirmfoto von 2016-09-17 13-23-24

So everything seems to work fine. Although I'm not sure what's the deal with `$shareTmpl['shareUrl']`is. I left it out in my "backport", because I don't really see why it's there in the first place.

**Comment by PVince81** [comment]
- [ ] BUG: clicking on an icon doesn't clear the tooltip. The tooltip stays after the browser popup opens. (observed in Chromium 53)
- [ ] BUG: Google plus URL seems to not work, but could be because I'm testing localhost:
gplus-400

**Comment by DeepDiver1975** [comment]
Google is related to localhost - yes 
Regarding tooltip: any idea how to make this work? Thx

**Comment by PVince81** [comment]
> Regarding tooltip: any idea how to make this work? Thx

Register a click event handler then call `$(el).tooltip('hide')` to force hiding it.
If that is happening too early, wrap the hiding command in a `_.defer(function() {...});` block

**Comment by DeepDiver1975** [comment]
@PVince81 tooltip issue addressed

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
