### PR TITLE
Cleaning up autocapitalize="off"

### LINKED ISSUE #15399: Cleaning up `autocapitalize="off"` in files
`autocapitalize="off"` is [deprecated since iOS 5.0](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html). 
Moreover it is inherited from the enclosing `form` tag, so the current `autocomplete="none"` should be set just once at the parent `form`

Currently in core it occurs 20 times in 6 files.

### PR DESCRIPTION
**Pull request by wenz**
Fixes #15399

## Description
Removes all instances of autocapitalize="off" and adds autocapitalize="none" in the associated <form> element instead.

## Related Issue
- Fixes #15399

## Motivation and Context
Removes deprecated, iOS-only autocapitalize="off"

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: drone CI here is only failing for federated sharing tests because of issue #37966

**Comment by phil-davis** [comment]
@wenz thanks for the contribution.
I fixed the CI problem for PRs coming from a forked-repo in PR #37971 
Please rebase your PR to the current `master` and then CI should pass.

**Comment by wenz** [comment]
@phil-davis  done!

**Comment by phil-davis** [comment]
@micbar can you allocate an appropriate person to review this please?
I am not familiar enough with this to review.

**Review by jvillafanez — APPROVED** [review]

**Comment by phil-davis** [comment]
@micbar CI here is only failing in the federated acceptance tests. They have some trouble finding the certificates used in the test setup so that the 2 ownCloud servers can trust each other. I guess there is some issue with those being stored in some secure place inside drone?

Please force merge - the code changes in this PR are unrelated.

**Review by micbar — APPROVED** [review]

**Pull request merged**
