### PR TITLE
[Stable 9] Make ownCloud work again in php 7.0.6

### PR DESCRIPTION
**Pull request by rullzer**
See https://bugs.php.net/bug.php?id=72117

Backport of https://github.com/owncloud/core/pull/24326
@karlitschek for approval

@cmonteroluque FYI. Up to you if we want this fix in 9.0.2 or 9.0.3

CC: @nickvergessen @PVince81 @LukasReschke @DeepDiver1975 @maki-chan @HLFH

### CODE REVIEW

**Comment by PVince81** [comment]
Not critical, so 9.0.3

**Comment by icewind1991** [comment]
:+1:

**Comment by Xenopathic** [comment]
:+1:

However I'd be inclined to consider this critical - it prevents ownCloud being used with PHP 7.0.6, which rolling-release distros are now shipping.

**Comment by PVince81** [comment]
This is a change deeper in core, I'd prefer to have it better tested on master instead of putting this in a few days before release.

**Comment by enoch85** [comment]
This breaks my VMs and I got several emails regarding this. Please fix this in 9.0.2 as well.

**Comment by RealRancor** [comment]
> This is a change deeper in core, I'd prefer to have it better tested on master instead of putting this in a few days before release.

If it won't be included in oC 9.0.2 PLEASE PLEASE communicate this issue correctly (Mailinglist, main owncloud.org, social media and similar). We got already tons of reports at IRC and forums about that.

**Comment by Akhenaton** [comment]
:clap:  :clap:  :clap:  @RealRancor 
This fix should definitively be included in 9.0.2 !
Many PHP 7.0.6 users have already applied manually the 3 lines patch for their 9.0.1, and when updating to 9.0.2 shouldn't have to do it again....

**Comment by Xenopathic** [comment]
We are seeing a LOT of issue reports showing up about PHP 7.0.6...

**Comment by LukasReschke** [comment]
Personally I'd also second 9.0.2, this will reflect bad on ownCloud otherwise.

cc @cmonteroluque @PVince81 @karlitschek

**Comment by rullzer** [comment]
Rebased to have a full CI run

**Comment by rullzer** [comment]
@PVince81 I get your concern. But if you look at the patch it is really pretty straight forward. With all the requests already here I also vote for 9.0.2. Ping me monday if you want to discuss.

**Comment by karlitschek** [comment]
@pvince81 I agree that careful testing is important. but this change looks pretty simple and is well understood. 
so i would vote for a backport :+1:

**Comment by greyltc** [comment]
This is a *super annoying* bug on Arch Linux. I'd love it if you all could get a fix out asap.

**Comment by alerque** [comment]
I understand the desire to have things tested before they ship, but this really needs to be in the next release out the door. If the release schedule has to be pushed back to get this through the paces then so be it. If testing results matter, the current version and anything shipped that doesn't include this fix is _failing the tests_ and in a known broken state.

OwnCloud has been adament about the need to install directly from upstream or upstream supported packages because distro packages would be too far behind. That's understandable, but this is the kind of thing that needs to get addressed sooner rather than later for that advice not to backfire. Distros are shipping with new PHP patch levels and ownCloud needs to stay compatable with the latest shipping versions.

**Comment by DeepDiver1975** [comment]
9.0.2 - we better fix broken setups

**Comment by rullzer** [comment]
CC: @jospoortvliet in case you find mentions of this on social media etc.

**Comment by PVince81** [comment]
Had a quick test with 9.0.2RC2 on php5-5.6.20-1.2.x86_64 and app framework API seems to still work fine. It can be checked by favoriting/unfavoriting a file.

**Comment by c0mputerking** [comment]
Hello i am using debian jessie, with owncloud upgraded today, and i am getting a login loop as mentioned by others above. 

However I am not sure where/how to apply the above patch to jessie.   None of the files below seem to contain the public function __isset line how do fix my instance of owncloud?

find / -name Request.php
/var/www/owncloud/updater/vendor/guzzlehttp/guzzle/src/Message/Request.php
/var/www/owncloud/updater/src/Http/Request.php
/var/www/owncloud/apps/files_external/3rdparty/aws-sdk-php/Guzzle/Http/Message/Request.php
/var/www/owncloud/apps/files_external/3rdparty/google-api-php-client/src/Google/Http/Request.php
/var/www/owncloud/3rdparty/sabre/http/lib/Request.php
/var/www/owncloud/3rdparty/guzzle/http/Guzzle/Http/Message/Request.php
/var/www/owncloud/3rdparty/guzzlehttp/guzzle/src/Message/Request.php

**Comment by rullzer** [comment]
@c0mputerking which version of ownCloud are you running hen? 9.0.2 should have the fix.

Anyways: the file is still lowercase. So ` lib/private/appframework/http/request.php`

`

**Comment by c0mputerking** [comment]
Looks like im on version 9.0.2

$OC_Version = array(9,0,2,2);
$OC_VersionString = '9.0.2';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(8,2);
$OC_Build = '2016-05-03T09:00:07+00:00 e13d02de2d5d260720b63f3f9ffe87b5aa0dd6c4';

However i still cannot login ... I did upgrade to 9.0.1 something awhile ago which broke things thought if i upgraded again things would start working however they have not.

Thanks i found the file now it contains this is it correct do i have another issue i cannot find the patch post now.

/**
         * @param string $name
         * @return bool
         */
        public function __isset($name) {
                if (in_array($name, $this->allowedKeys, true)) {
                        return true;
                }
                return isset($this->items['parameters'][$name]);
        }
 
        /**
         * @param string $i

**Comment by Xenopathic** [comment]
@c0mputerking Please open a new issue report if you think you have found a bug in ownCloud.

**Pull request merged**
