### PR TITLE
Show data folder warning earlier

### LINKED ISSUE #16078: »Can’t create data folder« message has no further help, shows too late
After clicking install, this message might show when the permissions are not correct yet.
capture du 2015-05-03 20 36 16

There are a few problems with it:
- it shows too late, only after clicking install. But we know that before clicking install already and should show it then already
- the header »Error« is useless and should be »Data directory not writable«
- there should be a link to a docs page on how to solve the problem

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/core/issues/16078
- always show warning about not writable data directory
- add link to documentation

please review @jancborchardt

### CODE REVIEW

**Comment by georgehrke** [comment]
@jancborchardt in #16078 you mentioned:
> the header »Error« is useless and should be »Data directory not writable«

I'm not sure about this, as this box also contains other error messages like database issues.

**Comment by MorrisJobke** [comment]
I rebased this and tested it - works as it should :+1:

**Comment by MorrisJobke** [comment]
@nickvergessen @LukasReschke @rullzer Please review :)

**Comment by PVince81** [comment]
The code looks fine.

@georgehrke can you rebase and solve the conflicts ?

**Comment by jancborchardt** [comment]
@georgehrke can you update this? Also see my recent issue at https://github.com/owncloud/core/issues/24644

**Comment by georgehrke** [comment]
rebased

**Comment by PVince81** [comment]
Rebased to :mans_shoe: Jenkins

**Comment by PVince81** [comment]
:+1: looks fine, regular install did not explode

**Comment by nickvergessen** [comment]
```
PHP Warning:  opendir(/ssd/jenkins/workspace/core-ci-linux-php5.4@3/database/sqlite/label/SLAVE/data-autotest): failed to open dir: No such file or directory in /ssd/jenkins/workspace/core-ci-linux-php5.4@3/database/sqlite/label/SLAVE/tests/lib/TestCase.php on line 274
```
looks not unrelated to me...

**Comment by PVince81** [comment]
@georgehrke please have a look

**Comment by PVince81** [comment]
@georgehrke any update ?

**Comment by georgehrke** [comment]
I rebased and I can't find this warning anymore. 😕

**Comment by georgehrke** [comment]
rebased to 👞 jenkins one more time ...

**Comment by PVince81** [comment]
@georgehrke Jenkins no happy

**Comment by georgehrke** [comment]
@DeepDiver1975 What does Jenkins try to say me with `Test report file /var/lib/jenkins/jenkins-slave/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/autotest-results-sqlite.xml was length 0`?

**Comment by PVince81** [comment]
No one seems to care, no update and it's a huge change for such a minor benefit -> close

**Pull request closed without merging**
