### PR TITLE
[stable8] Fix file move/copy when storage space is not enough

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/14503 to stable8.

@karlitschek please approve, fix for data loss issue https://github.com/owncloud/core/issues/14284

CC @icewind1991 @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
great. please backport

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Can this be merged ? It's 8.0.1 stuff.

@DeepDiver1975 @icewind1991 @nickvergessen @LukasReschke @MorrisJobke

**Comment by LukasReschke** [comment]
My remarks from https://github.com/owncloud/core/pull/14503 apply here as well.

**Comment by PVince81** [comment]
@LukasReschke fixed here too

**Comment by MorrisJobke** [comment]
Tested with cadaver and Nautilus :+1:

**Comment by LukasReschke** [comment]
:+1: - let's wait for my friend @owncloud-bot though.

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by PVince81** [comment]
Your friend is sick unfortunately

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
incredible :fireworks:

**Pull request merged**
