### PR TITLE
dont download the existing file for webdav if we're going to overwrite it

### LINKED ISSUE #17276: Overwrite remote share file first downloads it needlessly
### Steps
1. Setup two OC servers A and B
1. On A create a folder "local"
1. Create a file "local/test.txt"
1. Share "local" with a user on B
1. Connect to B with WebDAV and PUT a file as "local/test.txt" to overwrite it
1. Check the access logs on A

### Expected result
B PUTs file to A through publicwebdav endpoint

### Actual result
Before putting the file, B first does a GET to download the contents of the file from A.
Only then it does a PUT

### Versions
ownCloud 8.1 RC2

It looks like it's happening here: https://github.com/owncloud/core/blob/master/lib/private/files/storage/dav.php#L392

From what I understand `getCachedFile()` was used here in case fopen was done in random access mode. But in the case of full overwrite (mode "w") there is no need to download the remote file.

@icewind1991

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #17276

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Nice. Did you check the other external storages ? SMB has it too.

**Comment by PVince81** [comment]
Please adjust to match https://github.com/owncloud/core/pull/16923#discussion_r33860509

**Comment by PVince81** [comment]
@icewind1991 any update ?

**Comment by PVince81** [comment]
> Please adjust to match #16923 (comment)

@icewind1991 ^

I'm fine if you adjust the other storage types separately.

**Comment by PVince81** [comment]
I'll retest this soon.
It will need a second reviewer @Xenopathic

**Comment by Xenopathic** [comment]
Code looks good :+1:

**Comment by PVince81** [comment]
:+1: works, had to merge with master to test it.

**Pull request merged**
