### PR TITLE
Backport of languages from master

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Backporting translations

## Related Issue
- #32004 (that pr changes the location where some translations are read from)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by mmattel** [comment]
Are you sure the referenced issue #32004 (Add UI for switching public mail notification language) is the correct one ?

**Comment by DeepDiver1975** [comment]
> Are you sure the referenced issue #32004 (Add UI for switching public mail notification language) is the correct one ?

yes - because that pr changes the location where some translations are read from

**Comment by DeepDiver1975** [comment]
@PVince81 merge?

**Comment by PVince81** [comment]
we'll need another RC if we have code changes

**Pull request closed without merging**
