### PR TITLE
Handle no longer existing resource of a link share

### LINKED ISSUE #36005: Not possible to rename a file on the favorites page to a name of a file from an other folder
### Steps to reproduce
1. favorite file `folder/file1.txt`
1. favorite file `folder2/file2.txt`
1. navigate to the favorite page
1. try to rename `folder/file1.txt` to `file2.txt`

### Expected behaviour
renaming should be possible, because there is no conflict

### Actual behaviour
renaming is not possible, the UI claims that filename `file2.txt` is taken

### LINKED ISSUE #36055: accessing a public link of a deleted folder via new public link webdav API results in error 500
### Steps to reproduce
1. create a public link
2. delete the folder of that public link (not only the link the complete folder)
3. access the public link via webdav API

### Expected behaviour
`404 Not Found`

### Actual behaviour
`HTTP/1.1 500 Internal Server Error'`

#### ownCloud log (data/owncloud.log)
```
{
  "reqId": "B911G6jJNL94L42B0gMX",
  "level": 4,
  "time": "2019-08-19T04:31:40+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "--",
  "app": "webdav",
  "method": "PROPFIND",
  "url": "/owncloud-core/remote.php/dav/public-files/hz5nUer6Iumb2lJ",
  "message": "Exception: : {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\/home\\/artur\\/www\\/owncloud-core\\/apps\\/dav\\/lib\\/Files\\/PublicFiles\\/PublicSharedRootNode.php(61): OC\\\\Share20\\\\Share->getNode()\\n#1 \\/home\\/artur\\/www\\/owncloud-core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Tree.php(204): OCA\\\\DAV\\\\Files\\\\PublicFiles\\\\PublicSharedRootNode->getChildren()\\n#2 \\/home\\/artur\\/www\\/owncloud-core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(895): Sabre\\\\DAV\\\\Tree->getChildren('public-files\\/hz...')\\n#3 \\/home\\/artur\\/www\\/owncloud-core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(977): Sabre\\\\DAV\\\\Server->generatePathNodes(Object(Sabre\\\\DAV\\\\PropFind), Array)\\n#4 \\/home\\/artur\\/www\\/owncloud-core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1649): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('public-files\\/hz...', Array, 1)\\n#5 \\/home\\/artur\\/www\\/owncloud-core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(363): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#6 \\/home\\/artur\\/www\\/owncloud-core\\/lib\\/composer\\/sabre\\/event\\/lib\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\/home\\/artur\\/www\\/owncloud-core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(464): Sabre\\\\DAV\\\\Server->emit('method:PROPFIND', Array)\\n#8 \\/home\\/artur\\/www\\/owncloud-core\\/lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\/home\\/artur\\/www\\/owncloud-core\\/apps\\/dav\\/lib\\/Server.php(319): Sabre\\\\DAV\\\\Server->start()\\n#10 \\/home\\/artur\\/www\\/owncloud-core\\/apps\\/dav\\/appinfo\\/v2\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#11 \\/home\\/artur\\/www\\/owncloud-core\\/remote.php(165): require_once('\\/home\\/artur\\/www...')\\n#12 {main}\",\"File\":\"\\/home\\/artur\\/www\\/owncloud-core\\/lib\\/private\\/Share20\\/Share.php\",\"Line\":173}"
}
```

CC @DeepDiver1975

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Handle NotFound exception properly

## Related Issue
- Fixes #36055

## How Has This Been Tested?
- follow steps as per #36055

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by individual-it** [comment]
@DeepDiver1975 this does not fix  #36005, linked the wrong issue?

**Comment by PVince81** [comment]
@individual-it seems he updated the top post, please check again

**Review by PVince81 — APPROVED** [review]
:+1: code looks fine

**Comment by PVince81** [comment]
waiting for @individual-it to confirm and merge

**Review by individual-it — APPROVED** [review]
I've added a test, rebased the branch and fixed the commit message

**Pull request merged**
