### PR TITLE
Removed before and after scenarios to speed up tests

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Integration tests are starting to get too slow. Removing the code executed before and after scenarios when not needed will speed them.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Problems with sharing.Creating link share with edit permissions keeps it
Capabilities and sharees.

**Review by sharidas — APPROVED** [review]
Looks reasonable to me. :+1:

**Comment by SergioBertolinSG** [comment]
Maybe backporting this we can fix the auth problem? 

08:17:02   ┌─ @BeforeScenario # FeatureContext::prepareParameters()
08:17:02   │
08:17:02   ╳  Failed asserting that '' contains "testing".

**Comment by SergioBertolinSG** [comment]
I'll prepare a PR.

**Pull request merged**
