### PR TITLE
Improve images

### PR DESCRIPTION
**Pull request by jnweiger**
* Revamped the onlyoffice.png in gimp: cleaner and smaller PNG, ugly checkerboard background removed. (It was actually a 200k jpeg)
* Replaced wopi.png with the logo found at github.com/OfficeDev/PnP-WOPI (it was a copy of the onlyoffic jpeg)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> * ugly checkerboard background removed

you killed the transparancy with that .....

**Review by phil-davis — APPROVED** [review]
Looks reasonable.
The other existing images are
drawio.png 5.11 KB
richdocuments.png 12.2 KB

So this makes onlyoffice.png and wopi.png have similar format and sizes.

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
Dropped/missing transparancy needs to be coordinated with clients .....

**Comment by DeepDiver1975** [comment]
@jnweiger you might want to apply https://www.conventionalcommits.org/en/v1.0.0/ to your commits ......

**Comment by phil-davis** [comment]
Note: the existing drawio.png and richdocuments.png don't seem to have transparency - is that intended?

**Comment by jnweiger** [comment]
None of them ever had transparency. The checkerboard background in that (jpeg!) icon was really a checkerboard background.

To make it look nice on non-white-background, i'd suggest to
* keep a white margin, otherwise red green blue of e.g. the onlyoffice icon could blend very ugly into a greenish or blueish background.
* add modern rounded corners with transparency.

**Comment by DeepDiver1975** [comment]
> None of them ever had transparency.

lol - totally missed that. THX

**Comment by jnweiger** [comment]
Transparencies now work in all four:
Here on dark background:
grafik

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
