### PR TITLE
Check for authorship on edit attempt

### PR DESCRIPTION
**Pull request by blizzz**
Only authors are allowed to edit their comments. No global moderation :speak_no_evil: 

To test, execute a proppatch with oc:comment property set against a comment that does not belong to you.

please review @PVince81 @icewind1991 @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Code looks good :+1: 

Do we have the same for delete also ? @blizzz

**Comment by blizzz** [comment]
> Do we have the same for delete also ? @blizzz 

Good point, since only file access is assured. Will add.

**Comment by blizzz** [comment]
@PVince81 additional checks added

**Comment by PVince81** [comment]
:+1: thanks

**Comment by icewind1991** [comment]
:+1: looks good

**Pull request merged**
