### PR TITLE
Can't use function return value in write context

### LINKED ISSUE #15885: Can't use function return value in write context
```
PHP Fatal error:  Can't use function return value in write context in ./settings/admin.php on line 127
Fatal error: Can't use function return value in write context in ./settings/admin.php on line 127
Errors parsing ./settings/admin.php
```

empty-getenv-path

Caused by https://github.com/owncloud/core/pull/15617

Slapping @Xenopathic and @DeepDiver1975 as reviewers.

Will fix in a bit

### PR DESCRIPTION
**Pull request by nickvergessen**
@Xenopathic @DeepDiver1975 @mmattel 

Fix #15885

### CODE REVIEW

**Comment by bantu** [comment]
This addresses the issue, but the empty() call is probably pointless anyway. The $path variable is always defined (isset()) and the variable is not in an array with a potentially undefined index. And then empty($path) is basically the same as (bool) getenv('PATH')

**Comment by nickvergessen** [comment]
Well we use this way in other places aswell:
https://github.com/owncloud/core/pull/15597/files#diff-c40cfb9d23d0dda7729076cef8001fe1R934

**Comment by Xenopathic** [comment]
:+1:

**Comment by mmattel** [comment]
:+1:

**Pull request merged**
