### PR TITLE
Mask table and column names with backticks

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 please test with oracle

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 please test with oracle

on it - THX

**Comment by DeepDiver1975** [comment]
looks like it would not hurt to have all repair steps unit tested @nickvergessen would you mind taking a look? THX

**Comment by DeepDiver1975** [comment]
```sh
deepdiver@alien:~/Development/ownCloud/core-autotest [issue/13372-failing-oracle-tests]$ ./autotest.sh oci tests/lib/repair/cleantags.php 
Using database oc_autotest
Setup environment for oci testing ...
drop the database

Benutzer wurde gelöscht.

create the database

Benutzer wurde erstellt.


Benutzer wurde geändert.


Benutzerzugriff (Grant) wurde erteilt.

INDEX
END INDEX
Testing with oci ...
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /home/deepdiver/Development/ownCloud/core-autotest/tests/phpunit-autotest.xml

E

Time: 16.62 seconds, Memory: 32.00Mb

There was 1 error:

1) Test\Repair\CleanTags::testRun
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("path") VALUES(?)' with params ["TestRepairCleanTags"]:

ORA-01400: Einfügen von NULL in ("OC_AUTOTEST"."oc_filecache"."path_hash") nicht möglich

/home/deepdiver/Development/ownCloud/core-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:68
/home/deepdiver/Development/ownCloud/core-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
/home/deepdiver/Development/ownCloud/core-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1000
/home/deepdiver/Development/ownCloud/core-autotest/lib/private/db/connection.php:130
/home/deepdiver/Development/ownCloud/core-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/home/deepdiver/Development/ownCloud/core-autotest/tests/lib/repair/cleantags.php:139
/home/deepdiver/Development/ownCloud/core-autotest/tests/lib/repair/cleantags.php:59

Caused by
Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: Einfügen von NULL in ("OC_AUTOTEST"."oc_filecache"."path_hash") nicht möglich

/home/deepdiver/Development/ownCloud/core-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
/home/deepdiver/Development/ownCloud/core-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
/home/deepdiver/Development/ownCloud/core-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:991
/home/deepdiver/Development/ownCloud/core-autotest/lib/private/db/connection.php:130
/home/deepdiver/Development/ownCloud/core-autotest/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:208
/home/deepdiver/Development/ownCloud/core-autotest/tests/lib/repair/cleantags.php:139
/home/deepdiver/Development/ownCloud/core-autotest/tests/lib/repair/cleantags.php:59

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.

Generating code coverage report in Clover XML format ...

**Comment by nickvergessen** [comment]
Added the one column, not sure whether that is enough, but all others seem to have default values.

**Comment by DeepDiver1975** [comment]
@nickvergessen 

```sb
$ ./autotest.sh oci tests/lib/repair/cleantags.php 
Using database oc_autotest
Setup environment for oci testing ...
drop the database

Benutzer wurde gelöscht.

create the database

Benutzer wurde erstellt.


Benutzer wurde geändert.


Benutzerzugriff (Grant) wurde erteilt.

INDEX
END INDEX
Testing with oci ...
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /home/deepdiver/Development/ownCloud/core-autotest/tests/phpunit-autotest.xml

F

Time: 17.88 seconds, Memory: 32.75Mb

There was 1 failure:

1) Test\Repair\CleanTags::testRun
Assert tag categories count after repair step
Failed asserting that '1' matches expected 2.

/home/deepdiver/Development/ownCloud/core-autotest/tests/lib/repair/cleantags.php:84
/home/deepdiver/Development/ownCloud/core-autotest/tests/lib/repair/cleantags.php:69

FAILURES!
Tests: 1, Assertions: 3, Failures: 1.

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ...

**Comment by nickvergessen** [comment]
So, finished with debugging, will make a new pr

**Pull request closed without merging**
