### PR TITLE
add test for emoji in comments

### PR DESCRIPTION
**Pull request by davitol**
Add testcase 'make a comment with an emoji'

@SergioBertolinSG Please review

### CODE REVIEW

**Comment by PVince81** [comment]
@davitol would be cool to also have a test with emoji in a file name, just in case.

**Comment by SergioBertolinSG** [comment]
I am not getting this to work:

```
{"reqId":"agwA59KhbZpBNeNyabSi","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 Invalid actor \\\"\\\"\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/master_08-03-17\\\/apps\\\/comments\\\/lib\\\/Dav\\\/CommentsPlugin.php(123): OCA\\\\Comments\\\\Dav\\\\CommentsPlugin->createComment('files', '443', NULL, 'application\\\/jso...')\\n#1 [internal function]: OCA\\\\Comments\\\\Dav\\\\CommentsPlugin->httpPost(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/master_08-03-17\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/master_08-03-17\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:POST', Array)\\n#4 \\\/var\\\/www\\\/html\\\/master_08-03-17\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/master_08-03-17\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/master_08-03-17\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/master_08-03-17\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/m...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/master_08-03-17\\\/apps\\\/comments\\\/lib\\\/Dav\\\/CommentsPlugin.php\",\"Line\":240,\"User\":\"user0\"}","level":4,"time":"2017-03-13T13:52:15+00:00","method":"POST","url":"\/remote.php\/dav\/comments\/files\/443\/","user":"user0"}
```

**Comment by SergioBertolinSG** [comment]
Ok, the environment has worked changing the file my.cnf. Like it is recommended here https://www.drupal.org/node/2754539 .


But when running the test it fails and returns an exception:

```php
Exception: {"Message":"HTTP\/1.1 400 Invalid actor \"\"","Exception":"Sabre\\DAV\\Exception\\BadRequest","Code":0,"Trace":"#0 \/var\/www\/html\/master_08-03-17\/apps\/comments\/lib\/Dav\/CommentsPlugin.php(123): OCA\\Comments\\Dav\\CommentsPlugin->createComment('files', '25', NULL, 'application\/jso...')\n#1 [internal function]: OCA\\Comments\\Dav\\CommentsPlugin->httpPost(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/html\/master_08-03-17\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/html\/master_08-03-17\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:POST', Array)\n#4 \/var\/www\/html\/master_08-03-17\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/html\/master_08-03-17\/apps\/dav\/lib\/Server.php(227): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/html\/master_08-03-17\/apps\/dav\/appinfo\/v2\/remote.php(31): OCA\\DAV\\Server->exec()\n#7 \/var\/www\/html\/master_08-03-17\/remote.php(165): require_once('\/var\/www\/html\/m...')\n#8 {main}","File":"\/var\/www\/html\/master_08-03-17\/apps\/comments\/lib\/Dav\/CommentsPlugin.php","Line":240,"User":"user0"}
[Mon Mar 13 14:10:37 2017] 127.0.0.1:35784 [400]: /remote.php/dav/comments/files/25/
    When "user0" posts a comment with content "�~_~X~\" on the file named "/myFileToComment.txt" it should return "201"
```

**Comment by SergioBertolinSG** [comment]
Seems like this function is not ready to use filename with emojis:

https://github.com/owncloud/core/blob/master/tests/integration/features/bootstrap/CommentsContext.php#L68-L85

Warning: file_get_contents(http://localhost:8080/remote.php/webdav/😃.txt): failed to open stream: HTTP request failed!  in /var/www/html/master_08-03-17/tests/integration/features/bootstrap/CommentsContext.php line 87


Also this function seems to have problems with filenames starting with '/':

https://github.com/owncloud/core/blob/master/tests/integration/features/bootstrap/CommentsContext.php#L92-L127

It is not very flexible, it is always using user0 in its fields hardcoded.

Probably this comments context requires a refactor to be more integrated with the rest of the tests.

**Comment by davitol** [comment]
@SergioBertolinSG I have removed the scenario of naming the file with emojis and I have included in the PR only the test of setting a comment with an emoji. Please retest and let's merge this if it works and I'll work in the other scenario in a separately PR

**Comment by SergioBertolinSG** [comment]
Just clean the commits (I recommend to put as fixup all commits but first one)  and it is 👍 .

**Review by SergioBertolinSG — APPROVED** [review]

**Comment by SergioBertolinSG** [comment]
Rebase to trigger jenkins again, seems a problem with it.

**Comment by SergioBertolinSG** [comment]
@PVince81 this needs changes in jenkins before merge I guess.

Preparing mysql to use 4 byte chars.

**Comment by PVince81** [comment]
any update ? since then I think we already have a runner for mb4 ?

**Comment by PVince81** [comment]
@davitol please revive/redo after checking whether we already have such tests before.

note that we might need to skip said test when running on an old non-mb4 compatible database

**Comment by phil-davis** [comment]
@davitol look in https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiComments/createComments.feature - that has a scenario with an emoji in a comment.
Maybe that is enough? Or add a scenario to ``editComments.feature`` and ``deleteComments.feature`` to make sure that edit and delete work OK with emoji comments?

**Comment by davitol** [comment]
> Or add a scenario to `editComments.feature` and `deleteComments.feature` to make sure that edit and delete work OK with emoji comments?

@phil-davis Agree to spread the test with those two scenarios. Feel free to write them if you want to.

**Comment by phil-davis** [comment]
See issue #34419 - I assigned myself.
Closing here as there will be a fresh PR.

**Pull request closed without merging**
