### PR TITLE
in some case charset can be in lower case.

### PR DESCRIPTION
**Pull request by yverry**
Add strtoupper() in UTF-8 check to avoid error message

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
fine with me - THX

**Comment by karlitschek** [comment]
:+1:

**Comment by yanntech** [comment]
Thanks.
Of course as mentioned by jenkins bot I license this commit under MIT, you can merge when you want ;)

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@karlitschek backport?

**Comment by karlitschek** [comment]
please backport

**Pull request merged**
