### PR TITLE
[stable10] Federated Cloud Sharing info icon format

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #28965

### CODE REVIEW

**Review by davitol — APPROVED** [review]
👍

**Comment by phil-davis** [comment]
@PVince81 does the "To Release" label mean that this gets merged for 10.0.3 once CI is done?

**Comment by PVince81** [comment]
"To Release" means, ready for merge whenever merging is allowed. It is useful to quickly find those PRs that only require merging.

**Comment by davitol** [comment]
tested and works

**Pull request merged**
