### PR TITLE
Properly handle return values of OC_App::getAppInfo()

### LINKED ISSUE #23668: Trying to activate app on production stable9, doesn’t work (dependency analyzer)
It seems to be enabled, but doesn’t show in the app switcher. (News app in this case) owncloud.log:

```json


[
  {
    "reqId": "G4dZm8Xq\/Ayl5vyBzPgc",
    "remoteAddr": "93.202.88.105",
    "app": "PHP",
    "message": "Argument 1 passed to OC\\App\\DependencyAnalyzer::analyze() must be of the type array, null given, called in \/lib\/private\/app.php on line 1100 and defined at \/lib\/private\/app\/dependencyanalyzer.php#52",
    "level": 3,
    "time": "2016-03-30T16:41:44+00:00",
    "method": "POST",
    "url": "\/index.php\/settings\/ajax\/enableapp.php",
    "user": "jan"
  },
  {
    "reqId": "G4dZm8Xq\/Ayl5vyBzPgc",
    "remoteAddr": "93.202.88.105",
    "app": "PHP",
    "message": "Argument 2 passed to OC\\App\\DependencyAnalyzer::analyzeOC() must be of the type array, null given, called in \/lib\/private\/app\/dependencyanalyzer.php on line 66 and defined at \/lib\/private\/app\/dependencyanalyzer.php#280",
    "level": 3,
    "time": "2016-03-30T16:41:44+00:00",
    "method": "POST",
    "url": "\/index.php\/settings\/ajax\/enableapp.php",
    "user": "jan"
  }
]


```

@DeepDiver1975 @BernhardPosselt any idea?

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #23668

cc @DeepDiver1975 @jancborchardt @nickvergessen @LukasReschke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Test scenarios? Thx

**Comment by MorrisJobke** [comment]
> Test scenarios? Thx

static nightmare :see_no_evil:

**Comment by jancborchardt** [comment]
@MorrisJobke can you also make a pull request to stable9? We should backport it anyway, and that way I can more easily test on my production instance.

cc @karlitschek for backport request.

**Comment by karlitschek** [comment]
nice! please backport :+1:

**Comment by MorrisJobke** [comment]
stable9: https://github.com/owncloud/core/pull/23684

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
