### PR TITLE
remove unneeded 'goto' prefix from settings anchors

### PR DESCRIPTION
**Pull request by jancborchardt**
They are not really needed. On top of that, translating them (in external storage) makes no sense.

Please review @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by blizzz** [comment]
I am afraid this will reintroduce https://github.com/owncloud/core/issues/12080

**Comment by MorrisJobke** [comment]
> I am afraid this will reintroduce #12080

I tested this with LDAP and the setup still works

**Comment by blizzz** [comment]
Tested as well, and works for me, too. I assume this is due to changed behaviour when reworking the LDAP wizard. This does not mean however, that there no other name clashes now or in future. :±0:

**Comment by jancborchardt** [comment]
@blizzz in doubt name it `#ldap-settings`, or best rename the ID which is _not_ visible in a URL.

Ideally a name clash does not happen because simply the app name is used as the anchor and section ID – that should not be used as ID by the app otherwise.

**Comment by blizzz** [comment]
Whatever. Needs to be documented.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
