### PR TITLE
move font back from Light to Regular for body text, fix #18954

### LINKED ISSUE #18954: Font style is too narrow and looks blurry using 'old screens'
screen shot 2015-09-10 at 13 14 34
The letters are too narrow and they seem to be designed for high definition screens

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix https://github.com/owncloud/core/issues/18954
Only keep thin style for headers, log in & installation fields, and the app name in the header.

(For that reason I also removed the username in the top right, something I wanted to do anyway. It’s too small to be displayed with Light style and looks strange in Regular when the app name is Light.)

Before:
capture du 2015-10-30 16-39-33

This here:
capture du 2015-10-30 16-39-04

Please review @owncloud/designers @oparoz @karlitschek @carlaschroder @davitol @mroi @Akhenaton @BernhardPosselt

### CODE REVIEW

**Comment by MorrisJobke** [comment]
It looks a lot nicer here.

**Comment by davitol** [comment]
I think the same as @MorrisJobke

**Comment by BernhardPosselt** [comment]
Will check on my monitor once I'm home (later this evening)

**Comment by mroi** [comment]
Works OK for me.

**Comment by jancborchardt** [comment]
Updated above comment with screenshots, cc @owncloud/designers @karlitschek

**Comment by carlaschroder** [comment]
Ah, thanks for screenshots. Yes, that is more readable, thanks. Eyeballs usually do not improve with age :)

**Comment by Akhenaton** [comment]
A lot much nicer ! Thank you.

**Comment by enoch85** [comment]
Nice improvment! +1

**Comment by LukasReschke** [comment]
:+1:

**Comment by karlitschek** [comment]
the current lighter one loks more modern and cleaner. at least with a high res display. but i'm ok with changing this to a regular style if i'm the only one with this opinion.

**Comment by BernhardPosselt** [comment]
Ok, looks good :) :+1: 

The only thing left that kinda bugs me is the contrast in the app navigation. Non active entries are too grey for my monitor, I have to take a harder look. Can we move back to the darker grey background when .active is applied?

**Comment by stefan-niedermann** [comment]
regular looks nicer and is much more readable than light :+1: thank you

**Comment by raimund-schluessler** [comment]
:+1:  Looks better.

**Comment by DeepDiver1975** [comment]
@jancborchardt looks like we have enough votes: merge?

**Comment by raimund-schluessler** [comment]
Will this make it into 8.2.1 too?

**Comment by MorrisJobke** [comment]
> Will this make it into 8.2.1 too?

Not decided yet.

**Comment by oparoz** [comment]
It really should the theme in 8.2 is simply unfinished (only focused on HiDPI, some rough edges, missing media types) and lots of people will be using that version for months.

**Comment by raimund-schluessler** [comment]
I would also like to see a backport ;)

**Comment by jancborchardt** [comment]
@karlitschek I’d like to have your explicit take on this, maybe in our call later.
Even though the Light style looks more elegant, I can totally see the problems it causes and think that for now, changing back to Regular for the body text is the good course of action. Probably in a few months/years we could see and switch again – for now though font rendering has too many variables on too many systems, and it breaks the core experience if something goes wrong.

**Comment by jancborchardt** [comment]
Chatted with @PVince81 and @karlitschek about this. We decided to change it so that:
- for high-res displays it stays like it is
- for low-res displays, the body text is changed to Regular weight

Please test @davitol @oparoz @mroi @carlaschroder @Akhenaton @raimund-schluessler @BernhardPosselt @owncloud/designers 

Also setting to 8.2.1 because we should backport this fix, cc @cmonteroluque FYI.

**Comment by karlitschek** [comment]
great solution. testing .....

**Comment by MorrisJobke** [comment]
> for high-res displays it stays like it is
> for low-res displays, the body text is changed to Regular weight

Really nice. Didn't know that this is possible :) Let me test this.

**Comment by MorrisJobke** [comment]
Awesome! And it works just nicely - really sharp and light on high-res and a bit bolder on a low-res to be readable. Only the header ("Files" beside the cloud logo) is still in the light font on low-res displays.

:+1:

**Comment by schiesbn** [comment]
Looks good :+1:

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/core/pull/20176#issuecomment-155441157 thanks @jancborchardt!

**Comment by LukasReschke** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:  please backport

**Comment by jancborchardt** [comment]
@MorrisJobke yeah, headers and the app name are still light to have a bit lighter feel and because they are larger anyway.

**Comment by davitol** [comment]
:+1: Looks good

**Comment by jancborchardt** [comment]
Backport at https://github.com/owncloud/core/pull/20441, please review as well.

**Comment by mroi** [comment]
Since my initial complaint came from a Retina display, I obvious do not like this solution. I find the light fonts less readable. And I think readability should be favored over the modern look.
(For German speakers, here is another perspective: https://youtube.com/watch?v=Sw0syzCeH4Q)

**Comment by Salzi** [comment]
I totally with @mroi. The light fonts may look great but are so horrible to read specially with longer text (for example in the news app).

**Comment by jancborchardt** [comment]
@mroi as you said on the original issue:

> It may be OK for labels and other short texts, but it’s a reduction in usability for longer reads and writes.

I totally agree that for longer texts it would be insufficient. However the main parts of the interface are just what you said, labels and other short texts.

For now this seems like a good solution which solves the issue for displays like @davitol and @oparoz have. We can reconsider more in the future.

@mroi if you want to get involved with the design team more, please join us at https://owncloud.org/contribute/design/ :)

**Comment by jancborchardt** [comment]
@Salzi did you actually test this PR? Which device and resolution do you experience the problems with?

**Comment by karlitschek** [comment]
On a high DPI screen it is totally fine. In fact this font is used in a lot of places online and applications. I agree that it might be a bit different at first look.
I think that the compromise to use a regular font for low dpi screens is a good middle ground.

**Comment by karlitschek** [comment]
Let's go with this compromise for 8.2.1 please and then we can evaluate more if people really have reading problems. Thanks .

**Comment by carlaschroder** [comment]
Several people have said in this thread that the light font is hard to read, including me. I've been working hard to make the oC manuals friendlier to people with less-than-perfect vision-- what do I tell them, the manuals are great but the oC Web GUI is only for people with perfect eyes and high-end displays? Sure, there are a lot of terrible Web sites that have bad fonts. We don't need to imitate them. Do we want to attract and keep users and customers, or not?

**Comment by DeepDiver1975** [comment]
@jancborchardt @karlitschek merge? THX

**Comment by MorrisJobke** [comment]
> Several people have said in this thread that the light font is hard to read, including me. I've been working hard to make the oC manuals friendlier to people with less-than-perfect vision-- what do I tell them, the manuals are great but the oC Web GUI is only for people with perfect eyes and high-end displays? Sure, there are a lot of terrible Web sites that have bad fonts. We don't need to imitate them. Do we want to attract and keep users and customers, or not?

That means that you didn't tested this ;) Because on normal displays it is now in the old style and only on high res displays it uses the new light style. I think this is an excellent solution. Let's wait for the feedback of 8.2.1 and then maybe discuss this again if there are still open issues ;)

**Comment by jancborchardt** [comment]
> Let's wait for the feedback of 8.2.1 and then maybe discuss this again if there are still open issues

Yeah, good call @MorrisJobke.

**Comment by karlitschek** [comment]
@carlaschroder It should be a regular font for you now just as requested. :-) Only people with retina displays should get the light font. I think this is a good compromise

**Comment by mroi** [comment]
I can accept any solution made by those in charge. After all it’s open source (yay!), so I can change it to my liking.
I am just afraid that there may be users on Retina displays who will experience a reduction in readability without being able to consciously notice it or attribute it to the change in font.

**Comment by jancborchardt** [comment]
@mroi yeah, it’s indeed a point I don’t take lightly. We did however test this for quite a while on lots of devices, and especially on High-DPI displays it looks quite good and works well.

As I said, you are very welcome to join the design team and submit fixes where you notice stuff is badly designed. :)

**Comment by carlaschroder** [comment]
What's the use case for a fashionably sub-optimal font? What problem does it solve? Surely readability is the most fundamental aspect of any UI. @jancborchardt How diverse was your group of testers, were they any with vision problems? Have you tried using simulated vision impairments? This whole discussion has me worried that fashion is more important than usability.

**Comment by Akhenaton** [comment]
I quite agree with @carlaschroder. Think first "usability" ! The "bells & whistles" comes after. I'm not a very good tester because i have the eyes of a 70 year old man, but anyway thank you for your work.

**Comment by mroi** [comment]
@jancborchardt Thanks for the offer to join the design team. I like the idea, but currently, all my spare time is soaked up by a movie project of mine. ownCloud is the team collaboration tool, btw.

**Comment by karlitschek** [comment]
relax guys. on a normal screen the regular font is used now. this should be fine for everyone. only if you have a retina hires screen the light font is use. this is totally fine and readable. actually a lot of people think that this looks crisper, sharper and better. only on very high dpi screens of course. this should be fine for everyone. thanks

**Pull request merged**
