### PR TITLE
adjust multiselect bar to controls bar, fix #18989

### LINKED ISSUE #18989: Too much transparency in the header in multi-select mode
transparency

It doesn't look very clean

@jancborchardt

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix the opacity and color, fix https://github.com/owncloud/core/issues/18989, please review @oparoz @owncloud/designers

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

I'm wondering whether this transparency even makes sense, especially when the thumbnails are barely visible now.

**Comment by jancborchardt** [comment]
Yes, even a slight transparency gives a more light feel than a fully opaque color. That’s why it’s there.

**Comment by jancborchardt** [comment]
@oparoz awaiting your review since you opened the issue.

**Comment by raghunayyar** [comment]
I like what I see, getting this in. :+1:

**Comment by raghunayyar** [comment]
@jancborchardt rebase please

**Comment by PVince81** [comment]
No rebase needed, these is no conflict

**Comment by PVince81** [comment]
@raghunayyar rebases are only needed when the text in the box explicitly says that there is a conflict.
That new Github UX is more confusing...

**Comment by oparoz** [comment]
@PVince81 - The merge button is greyed out. It's not possible to merge afaik.

**Comment by oparoz** [comment]
@jancborchardt - It's fixed! Thanks :)

**Comment by raghunayyar** [comment]
If I hit update now, it will merge master to current branch, has happened previously. @PVince81

**Comment by PVince81** [comment]
"out of date != merge conflict"

@DeepDiver1975 asked recently to not force push needlessly and just ask him directly to merge blocked PRs.

But now here I wonder what's wrong with scrutinizer, maybe we should disable that too for now ?

**Comment by jancborchardt** [comment]
Well, the lord (@DeepDiver1975) giveth and taketh away. Giving required CI testing and taking away the ability for everyone to simply merge instead of creating a bottleneck. ;D

**Comment by DeepDiver1975** [comment]
> But now here I wonder what's wrong with scrutinizer, maybe we should disable that too for now ?

waiting for coverage data - which we do not provide

**Pull request merged**
