### PR TITLE
fix the output of error messages

### LINKED ISSUE #37338: error messages should be escaped
In some cases the error message are printed unescaped.

### PR DESCRIPTION
**Pull request by C0rby**
## Description

Escape error messages before printing them on the page.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/37338

## Motivation and Context

Sometimes error messages can break the page if not escaped.

## How Has This Been Tested?

- locally in the browser

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/24590/2/6
code style needs fixing

**Comment by mmattel** [comment]
Pls run `make test-php-style-fix` to fix the issues @phil-davis mentioned

**Comment by mmattel** [comment]
@phil-davis CI is now green. Mergable?

**Comment by phil-davis** [comment]
> @phil-davis CI is now green. Mergable?

I added more people to the review requests. I am not super-confident about the escaping thing - sometimes we have ended up double-escaping stuff...

@C0rby can you give some examples of messages that are not properly escaped?

**Review by jvillafanez — APPROVED** [review]

**Comment by jvillafanez** [comment]
As far as I see in the code, the messages come from exceptions. They shouldn't be escaped because it's impossible to know where the message would end up (normally in the log file, but they could be shown in the web as in this case)

**Comment by C0rby** [comment]
Exactly, the messages come from exceptions and thus controlling the content is hard.
Escaping is also a kind of security measure.

**Pull request merged**
