### PR TITLE
Add webUI tests for federationSharing sub-folder operations

### PR DESCRIPTION
**Pull request by paurakhsharma**
## Description
Add webUI tests for federationSharing sub-folder operations

## Related Issue
#34150

## How Has This Been Tested?
:robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by skshetry — COMMENTED** [review]
:+1:

**Comment by dpakach** [comment]
:+1:

**Review by skshetry — COMMENTED** [review]
:+1:

**Review by individual-it — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@paurakhsharma please backport

**Comment by paurakhsharma** [comment]
Backport on: #34240

**Pull request merged**
