### PR TITLE
add getEditionString() to public util interface

### LINKED ISSUE #22: firstrunwizard app does not pass occ:check-code
### Steps to reproduce

1. Install 8.1 enterprise
2. invoke occ app:check-code

### Expected behaviour

The app passes the check

### Actual behaviour

The app fails the check:

```

[32mAnalysing /var/www/html/owncloud/apps/firstrunwizard/wizard.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/firstrunwizard/templates/wizard.php[39m
 3 errors
    [37;41mline    7: OC_Util - static method call on private class[39;49m
    [37;41mline   28: OC_Util - static method call on private class[39;49m
    [37;41mline   56: OC_Util - static method call on private class[39;49m
[32mAnalysing /var/www/html/owncloud/apps/firstrunwizard/ajax/disable.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/firstrunwizard/ajax/enable.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/firstrunwizard/lib/firstrunwizard.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/firstrunwizard/appinfo/app.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/firstrunwizard/appinfo/routes.php[39m
 0 errors
[37;41mApp is not compliant[39;49m

```
### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

### PR DESCRIPTION
**Pull request by georgehrke**
needed to fix https://github.com/owncloud/firstrunwizard/issues/22

please review @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I removed the unneeded PHPDoc tag `@description`

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Question here is: Do we really want this in public namespace?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Question here is: Do we really want this in public namespace?

Honestly - not really ..... can we grab this via \OCP\Defaults - https://github.com/owncloud/core/blob/master/lib/public/defaults.php#L39

**Comment by georgehrke** [comment]
I totally see your point here, but adding it to OCP\Default implies that themes can add own edition strings. This could break stuff, as a lot of code expects the instance to be the enterprise edition, if the string is not empty.

**Comment by DeepDiver1975** [comment]
maybe we better add this code snippet to the first run wizard:

```php

function getEdition() {
    if (\OC::$server->getAppManager()->isEnabledForUser('enterprise_key')) {
        return "Enterprise";
    }
    return '';
}

**Comment by DeepDiver1975** [comment]
no need to pollute the public api from ym pov

**Comment by georgehrke** [comment]
> maybe we better add this code snippet to the first run wizard:

sure, will take care

**Comment by DeepDiver1975** [comment]
> sure, will take care

thx a lot @georgehrke

**Pull request closed without merging**
