### PR TITLE
[stable8] Fix bugs in ownCloud external storage

### LINKED ISSUE #15262: external storage: WebDAV method works but ownCloud not
I'm using ownCloud 8.0.2. I can connect from one ownCloud server to another one with the WebDAV method by using the address
   https://www.example.com/oc/remote.php/webdav

But it doesn't work with the ownCloud method by using the address
   https://www.example.com/oc/
Error message: Forbidden

Take a look to https://forum.owncloud.org/viewtopic.php?f=31&t=27359

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Backport of #14475

Fixes #15262

cc @karlitschek @PVince81 @DeepDiver1975 @LukasReschke @icewind1991

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by Xenopathic** [comment]
Dammit, hit by the GitHub DDoS...

@owncloud-bot retest this please

**Comment by karlitschek** [comment]
:+1:

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
@karlitschek Request to merge for 8.0.3?

**Comment by karlitschek** [comment]
backport is fine. :+1: 
But we are already in the RC phase for 8.0.3 so this has to wait for 8.0.4 Let´s keep the backport-request tag so that we can find this again late

**Comment by DeepDiver1975** [comment]
assigning milestone 8.0.4

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Pull request merged**
