### PR TITLE
Add index to oc_cards to assist with searching large number of rows

### LINKED ISSUE #27948: High DB load from SELECT on oc_cards due to lack of indexes
Multiple queries as follows:
```
SELECT `id`, `uri`, `lastmodified`, `etag`, `size`, `carddata` FROM `oc_cards` WHERE (`addressbookid` = '380') AND (`uri` = 'LDAP:foo@bar.vcf') LIMIT 1;
```
generates high db load during searching for cards as we don't have any indexes.

```
CREATE INDEX addressbookid_uri_index on oc_cards ( addressbookid, uri );
```
was observed to cut database load in half in production.

Creating a PR...

### PR DESCRIPTION
**Pull request by tomneedham**
Fixes: https://github.com/owncloud/core/issues/27948

Added check for existing index in case this has been deployed already.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by tomneedham** [comment]
screen shot 2017-05-19 at 10 42 52

**Comment by butonic** [comment]
nice and defensive!
👍

**Comment by PVince81** [comment]
10.0.2

and backports ?

**Comment by DeepDiver1975** [comment]
setting 10.1 because this goes into master

**Pull request merged**
