### PR TITLE
[stable6] Remove hacky Substring support for MSSQL

### PR DESCRIPTION
**Pull request by LukasReschke**
Substring() is not required for the core functionality and this allows us to get rid of a huge hack...

@DeepDiver1975 As discussed.

### CODE REVIEW

**Comment by LukasReschke** [comment]
Don't merge for now - we're in freeze.

**Comment by LukasReschke** [comment]
Failing tests were to expect due to incompatible PHPUnit version :see_no_evil:

**Comment by bantu** [comment]
@LukasReschke Do you have a ticket for the PHPUnit problem? Is this supposed to be addressed? stable7 and stable8 fail as well.

**Comment by LukasReschke** [comment]
> @LukasReschke Do you have a ticket for the PHPUnit problem? 

Nope.

> Is this supposed to be addressed? 

No idea. Let's ask @DeepDiver1975. But in my opinion not worth the time since stable6 is anyways EoL in the middle of the year :)

> stable7 and stable8 fail as well.

That looks indeed like another CI error… Seems like we're experiencing new categories of bugs :see_no_evil:

**Comment by LukasReschke** [comment]
Also this requires anyways manual test execution on a Windows machine with MSSQL :see_no_evil:

**Comment by nickvergessen** [comment]
@LukasReschke @bantu 
```irc
<DeepDiver> run the unit tests local and merge if sucessfull

**Comment by LukasReschke** [comment]
MSSQL unit tests? :see_no_evil:

**Pull request merged**
