### PR TITLE
[Stable10] Removed before and after scenarios to speed up tests

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Backport of https://github.com/owncloud/core/pull/28093

Lets see if the auth.feature:10 fails here.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by sharidas — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
jenkins needs the boot

**Comment by SergioBertolinSG** [comment]
boot = rebase? or restart the job?

**Comment by PVince81** [comment]
boot => 👢 aka kick aka punch aka hit aka rebase

**Comment by PVince81** [comment]
not waiting for Travis, this only affects integration tests

**Pull request merged**
