### PR TITLE
[stable9] Require at least libxml 2.7.0

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of #23189

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:question: 

bildschirmfoto von 2016-03-16 17-07-43

**Comment by LukasReschke** [comment]
:dancers: :see_no_evil:

**Comment by LukasReschke** [comment]
And the right branch… https://github.com/owncloud/core/pull/23319

**Pull request closed without merging**
