### PR TITLE
disable the app code checker - some previous shipped apps cannot be inst...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
...alled from the appstore now :facepunch:

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@karlitschek as discussed yesterday

**Comment by PVince81** [comment]
:+1: 

Did Jenkins misreport success ?

**Comment by MorrisJobke** [comment]
@PVince81 No. It was aborted before anything bad happened. So the state is green (because nothing crashed) but the result is bad, because not everything has run.

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
:+1:

**Comment by LukasReschke** [comment]
@Raydiation

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by LukasReschke** [comment]
:+1:

For the reference https://github.com/owncloud/core/pull/9604 and https://github.com/owncloud/core/issues/9574

**Pull request merged**
