### PR TITLE
Adding mimetype x-h for header files

### LINKED ISSUE #70: Unable to open .h files
C header files are downloaded instead being opened.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://github.com/owncloud/files_texteditor/issues/70

@SergioBertolinSG  please test

@PVince81 @icewind1991 @th3fallen please review - THX

### CODE REVIEW

**Comment by th3fallen** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
