### PR TITLE
Do not change color of 'new' button on hover and make new file menu more consistent with button

### LINKED ISSUE #13632: Minor CSS issue in "New" menu
### Steps:
1. In the files app, click "New" and leave the menu open
newmenu1

2. Hover on "New":
newmenu2

3. Hover back and forth between "New" and the upload button.

### Expected result
Menu items stay black

### Actual result
Text of menu items becomes grey. They seem to inherit the hover style from the button.

@owncloud/designers

### PR DESCRIPTION
**Pull request by Sugaroverdose**
Fixes #13632 
MIT, as always

### CODE REVIEW

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by Sugaroverdose** [comment]
cc @MorrisJobke @PVince81

**Comment by PVince81** [comment]
Thanks. To be reviewed for 8.1

**Comment by jancborchardt** [comment]
@Sugaroverdose nice detail fix! :) Just one thing: The popdown overlays the upload button weirdly. Can you make it so the »New« button and its dropdown is above the upload button?

And btw – if you want to be part of the @owncloud/designers team, let me know! :) Would be good to have you. You’ll get notified on design issues. You are also very welcome in our IRC channel #owncloud-design

**Comment by Sugaroverdose** [comment]
@jancborchardt hm, i'll try to fix that, didn't noticed this in safari :)
About owncloud/designers - with pleasure :)

**Comment by MorrisJobke** [comment]
> About owncloud/designers - with pleasure :)

Did you already send the contributors agreement to @karlitschek ? ;) Then it's easy to do ;)

**Comment by Sugaroverdose** [comment]
@MorrisJobke i'll dot it...a little later :)

**Comment by MorrisJobke** [comment]
Okay :)

**Comment by Sugaroverdose** [comment]
tested with IE8, IE11(on scaling, border between button and dropdown appears), GC40, FF35, Safari8
@jancborchardt

**Comment by jancborchardt** [comment]
Looks great, tested and works! :+1:

**Comment by jancborchardt** [comment]
@owncloud/designers another review please, then we can get this into 8.1

@karlitschkek this is the pull request that fixes the detail you also mentioned – the »New« button and the dropdown now look like one element. :)

**Comment by karlitschek** [comment]
cool. :+1:

**Pull request merged**
