### PR TITLE
[Master] Remove hacky Substring support for MSSQL

### PR DESCRIPTION
**Pull request by LukasReschke**
Substring() is not required for the core functionality and this allows us to get rid of a huge hack...

@DeepDiver1975 As discussed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
https://gist.github.com/DeepDiver1975/081ac99e2c3dabb29724

**Comment by DeepDiver1975** [comment]
This code fragment has to die :+1:

**Comment by DeepDiver1975** [comment]
@PVince81 @karlitschek @icewind1991 THX

**Comment by PVince81** [comment]
Hmm okay, looks good :+1:

**Pull request merged**
