### PR TITLE
update symphony components to 2.6.4

### PR DESCRIPTION
**Pull request by icewind1991**
Updates the following symphony packages to 2.6.4
- symfony/routing
- symfony/console
- symfony/process
- symfony/event-dispatcher

This is needed for laravel's job queue package

See https://github.com/owncloud/3rdparty/pull/156

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@icewind1991 that commit does not exist in 3rdparty - can you please double check? THX

**Comment by icewind1991** [comment]
> @icewind1991 that commit does not exist in 3rdparty - can you please double check? THX

oops, force pushed to 3rdparty to fix an issue and forgot to update this

**Comment by DeepDiver1975** [comment]
THX @icewind1991

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@nickvergessen please review - THX

**Comment by PVince81** [comment]
We should push this forward. Time is ticking and we'd better have lib updates early.

@icewind1991 can you rebase ? How to test this ?

**Comment by MorrisJobke** [comment]
@icewind1991 Ping

**Comment by icewind1991** [comment]
rebased

**Comment by MorrisJobke** [comment]
I tested the console, browsed the web UI, used WebDAV to access, upload and modified files

Works :+1:

**Comment by MorrisJobke** [comment]
3rdparty submodule update 9a9633f

**Pull request merged**
