### PR TITLE
Expose syslog tag in the configuration

### PR DESCRIPTION
**Pull request by DeepDiver1975**
followup PR of https://github.com/owncloud/core/pull/11636

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@Gomez here we go - have fun

**Comment by Gomez** [comment]
@DeepDiver1975 Will add docs & a entry in config.sample.php

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by Gomez** [comment]
Docs added.
Can we get this in stable8.1? Backport should be easy. Will do it

**Comment by DeepDiver1975** [comment]
> Can we get this in stable8.1? Backport should be easy. Will do it

@karlitschek objections?

**Comment by karlitschek** [comment]
please backport

**Comment by Xenopathic** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@Gomez Can you please also backport to stable8.2? Thanks

**Pull request merged**
