### PR TITLE
Send the proper original name for uploaded files

### LINKED ISSUE #13234: Any reason to expose tmp directory in response value?
When uploading files:
```json
[
    {
        "id": 2122,
        "parentId": "2121",
        "date": "10. Januar 2015 um 10:55:34 MEZ",
        "mtime": 1420883734000,
        "icon": "/core/img/filetypes/file.svg",
        "name": "Thumbs.db",
        "permissions": 27,
        "mimetype": "application/octet-stream",
        "size": 44032,
        "type": "file",
        "etag": "9a0ec1a78aab749baa0da6f702244b70",
        "status": "success",
        "originalname": "/private/var/tmp/php25k3LL",
        "uploadMaxFilesize": 537919488,
        "maxHumanFilesize": "513 MB",
        "directory": "/A/vbc/img"
    }
]
```

Is there any reason that we expose the tmp directory where that file was stored?

@icewind1991

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #13234

cc @DeepDiver1975 @PVince81 @LukasReschke

### CODE REVIEW

**Comment by PVince81** [comment]
Did you find out what it was needed for ?

**Comment by DeepDiver1975** [comment]
> Did you find out what it was needed for ?

afaik not needed at all - no match in the js files

**Comment by LukasReschke** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
