### PR TITLE
Updating sabre/dav (4.0.0-alpha5 => 4.0.0-beta1)

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
https://github.com/sabre-io/dav/releases/tag/4.0.0-beta1
```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating sabre/dav (4.0.0-alpha5 => 4.0.0-beta1): Downloading (100%)
```

And adjust acceptance tests for https://github.com/sabre-io/dav/pull/1130

## Motivation and Context
Be up-to-date

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
```
  Scenario Outline: lockdiscovery root of public link when root is locked                                                # /drone/src/tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature:7
    Given user "user0" has created a public link share of folder "PARENT" with change permission                         # FeatureContext::userCreatesAPublicLinkShareOfWithPermission()
    And user "user0" has locked folder "PARENT" setting following properties                                             # WebDavLockingContext::userHasLockedFile()
      | lockscope | <lock-scope> |
    When the public gets the following properties of entry "/" in the last created public link using the WebDAV API      # WebDavPropertiesContext::publicGetsThePropertiesOfFolder()
      | d:lockdiscovery |
    Then the value of the item "//d:lockroot/d:href" in the response should match "/%base_path%\/public.php\/webdav\/$/" # WebDavPropertiesContext::assertValueOfItemInResponseRegExp()
    And the value of the item "//d:locktoken/d:href" in the response should be "opaquelocktoken:"                        # WebDavPropertiesContext::assertValueOfItemInResponseIs()
    And the value of the item "//d:timeout" in the response should match "/Second-\d+/"                                  # WebDavPropertiesContext::assertValueOfItemInResponseRegExp()

    Examples:
      | lock-scope |
      | shared     |
        Cannot find item with xpath "//d:locktoken/d:href"
        Failed asserting that false is true.
      | exclusive  |
        Cannot find item with xpath "//d:locktoken/d:href"
        Failed asserting that false is true.
```
https://drone.owncloud.com/owncloud/core/17235/516

The `locktoken` does not seem to be set for these public link scenarios, when previously it was set to `opaquelocktoken:`

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 FYI, no rush but there is some change in behaviour.

yes - this is an intended change we did introduce - see https://github.com/sabre-io/dav/pull/1130

**Review by individual-it — APPROVED** [review]
if that change is intended, then I guess we should merge it

**Comment by phil-davis** [comment]
@DeepDiver1975 please review, and you have the power to override the silly codecov fail.

**Comment by phil-davis** [comment]
Note: `stable10` still requires PHP 7.0 and so there is no `sabre/dav` 4.0 there yet. So no backport for now.

**Comment by phil-davis** [comment]
I rebased just now, in the hope that another CI run might pass codecov...

**Comment by phil-davis** [comment]
@DeepDiver1975 @micbar codecov is too dumb and fails this dependency-bump PR.
Please review and merge if happy.

**Comment by phil-davis** [comment]
@DeepDiver1975 please review, and then override-merge.
I cannot merge because of codecov being too stupid.

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport `stable10` is part of PR #34559

**Pull request merged**
