### PR TITLE
shareowner can edit re-share permissions without any restriction

### LINKED ISSUE #36107: [10.3.0 alpha] Owner cannot edit group's permissions
Works with 2.6.0-daily20190820 (build 12341), macOS 10.14.6, server 10.2
Broken on 2.6.0-daily20190820 (build 12341), macOS 10.14.6, server 10.3.0 alpha
Broken on 2.5.4, Windows 10, server 10.3.0 alpha

Steps to recreate:
1) User1 shares a file to User2 with only Share permission
2) User2 shares a file to group friends (User1 and User2 are both members of this group) without any permissions
3) User1 adds Edit permissions to group friends

Actual result: The entry gets greyed out and cannot be edited again
Expected result: User1 can again immediately remove the Edit permissions

Screenshot 2019-08-23 at 16 18 04

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
Shareowner should have full permission on re-shares.

To exclude ShareOwner from the re-share permission check, I need to know the session user is shareowner or not in `ShareManager` class. In #36144, I injected `IUserSession` to `ShareManager`, but it led to several problems. 

According to my observations, `IRootFolder` `getOwner` method returns the user who made the request. If no user exists in the session it returns `false`. So, I used `IRootFolder`'s `getOwner` method to determine the user who made the request.  @jvillafanez, @VicDeo Do you see any side effect of this approach?

## Related Issue
- Fixes #36107 

## Motivation and Context
Fighting with bugs.

## How Has This Been Tested?
Manually with steps in #36107. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by jvillafanez** [comment]
What if that additional restriction is placed up in the stack? I mean, core maybe doesn't need to check who is calling that function as long as the share makes sense; the one that should check is either the controller or the app making that call.
Probably not a good idea because we can't control who is going to make the call (3rdparty apps can take advantage of this to bypass some restrictions).

In any case, I think the problem is what to do if the session doesn't have a user at that point. If this is required, maybe we should abort the request.

I haven't checked where the `rootFolder->getOwner()` call leads to, but I guess it will still rely on session information, otherwise I don't know how it can return the correct user.

**Comment by PVince81** [comment]
Please investigate whether `Root->getOwner()` is really based on the session or whether it's the storage owner. As far as I remember it should rather be the storage owner as it's the owner of the node, not the owner of the share.

In terms of storage owner, there are scenarios where there is no owner, for example for a system-wide external storage. In the latter case, I remember that there is fallback where it would indeed use the session user. But only as a fallback.

**Comment by micbar** [comment]
@PVince81 @jvillafanez 
I investigated the $rootFolder->getOwner code path.

You are correct, it can be both.
We can get `false` as a response.

**Comment by micbar** [comment]
Further down Common Storage uses `\OC_User::getUser();` as a fallback which does
```
/**
	 * get the user id of the user currently logged in.
	 *
	 * @return string|bool uid or false
	 */
	public static function getUser() {
		$uid = \OC::$server->getSession() ? \OC::$server->getSession()->get('user_id') : null;
		if ($uid !== null && self::$incognitoMode === false) {
			return $uid;
		} else {
			return false;
		}
	}
```

**Comment by karakayasemi** [comment]
> 
> What if that additional restriction is placed up in the stack? I mean, core maybe doesn't need to check who is calling that function as long as the share makes sense; the one that should check is either the controller or the app making that call.

If the original share owner makes a request, we will calculate `$maxPermission` with his own permissions instead of sharer user's permissions. Actually, what we are trying to do is make an exclusion for the original share owner and let him edit reshare without the sharer user's permission limits. 

>
> In any case, I think the problem is what to do if the session doesn't have a user at that point. If this is required, maybe we should abort the request.

If there is no user in session, permissions will be calculated with re-sharer user's permission. So, permission control is even more strict in this case. `occ files:transfer-ownership` command is using `updateShare` function to transfer shared files ownership and there is no session user in this case. When I tried this scenario, `$this->rootFolder->getOwner()->getUID()` returned false and since `false` not equal to Sharer User's UID, `$maxPermission` calculated  with `calculateReshareNodePermissions` method.

**Comment by jvillafanez** [comment]
Just giving some thoughts:
* if there is a user in the session:
    * if it matches the share owner, use the share owner to calculate the permissions
    * if it matches the resharer, use the resharer to calculate the permissions
* if there is no user in the session: abort.

The problem is that core is tying the user in the user session with the user that will perform the action. Maybe the solution is core to be more flexible in this regard, technically allowing any user to perform any operation, and letting other apps to handle proper access or providing specific services to access properly to those resources.

A simple service such as (incompleted dummy code)
```
function updateShare($user, IShare $share) {
  if ($user === $share->getOwner() || $user === $share->getResharer()) {
    updateShare($share);
  }
}
```
should fix the problem as long as the actual update doesn't depend on the session information. The question is if we can reach that point from the current code.

Alternatively, we can try to inject the target user in the session.

**Review by micbar — CHANGES_REQUESTED** [review]
@karakayasemi Please implement the code changes, that we discussed.

**Comment by karakayasemi** [comment]
As we discussed, I implemented passing user information via an optional parameter approach here: https://github.com/owncloud/core/pull/36166.  Also, I did not want to quickly eliminate this PR, and I've investigated possible scenarios of it.

I tracked `IRootFolder` in the DIContainer, as a result, I reached it is a `Root` object: 
https://github.com/owncloud/core/blob/ae9ee7ab15070b1f9a4d5ea6511f63e7f452a908/lib/private/Server.php#L239

When we call `getOwner` function from `IRootFolder`, it equals to this call (`Node` is a parent object of `Root`):
https://github.com/owncloud/core/blob/ae9ee7ab15070b1f9a4d5ea6511f63e7f452a908/lib/private/Files/Node/Node.php#L347

And then, I reached that `View`'s `getFileInfo` method is determining the owner: 
https://github.com/owncloud/core/blob/ae9ee7ab15070b1f9a4d5ea6511f63e7f452a908/lib/private/Files/Node/Node.php#L93

Finally, this method is setting owner user in `View`: 
https://github.com/owncloud/core/blob/ae9ee7ab15070b1f9a4d5ea6511f63e7f452a908/lib/private/Files/View.php#L1352
If storage owner founds, this method returns the storage owner, else, it returns `RemoteUser`. This means we will never call `getUID` method from a null. I had concerns that `getOwner` might return null, looks like it is not possible.

When `$this->rootFolder->getOwner()->getUID()` returns something, even it returns false or any other non-owner user, this won't pass being equal to ShareOwner condition. So, if it is a re-share, `ShareManager` will use the re-sharer permissions to calculate the permissions as it's supposed to be. What I am trying to say is, I could not find any problematic situation for this PR too. I would like to keep open this PR until #36166 merged.

**Pull request closed without merging**
