### PR TITLE
Remove session token creation for dav requests during loadApps

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
There was a new code path added here: https://github.com/owncloud/core/pull/28879 to create session tokens for dav requests. This is a partial revert. DAV requests use basic auth by default, which should be picked up here: 

https://github.com/owncloud/core/blob/31544601c5d3cc2f2ab63ed26c9d1c9d0648f0dc/lib/private/User/Session.php#L452

and token creation here:

https://github.com/owncloud/core/blob/31544601c5d3cc2f2ab63ed26c9d1c9d0648f0dc/lib/private/User/Session.php#L350

Which leaves this code path redundant. This can result in duplicate tokens because created causing UniqueViolation exceptions and confusing the client.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tomneedham** [comment]
cc @SamuAlfageme

**Review by IljaN — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport stable10 #31428

**Comment by PVince81** [comment]
Regression: https://github.com/owncloud/core/issues/31731

**Comment by DeepDiver1975** [comment]
> Regression: #31731

:open_hands:

**Pull request merged**
