### PR TITLE
Remove log entries in admin page

### PR DESCRIPTION
**Pull request by PVince81**
## Description

Remove the log entries table in the admin page.
## Related Issue

https://github.com/owncloud/core/issues/25984
## Motivation and Context

These are slow to parse on some setups.
They block the user's session.
They are not very useful as they are not presented well.
Using a log viewer app is more suitable.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Let's see if tests pass, need to check if docs need updating.

@butonic @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
ah, and little bonus: now the download button displays the log size.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by mmattel** [comment]
Suggestion for a log viewer app: @icewind1991 logreader. Should then be added automatically to the apps delivered, installed and enabled.

**Comment by PVince81** [comment]
killing spree! (second kill after migration simulation)

**Comment by mmattel** [comment]
@PVince81 @DeepDiver1975 
Q: is there a plan to use / fork icewind1991 logreader app, create a new one or include an existing other log reader repository for owncloud to make log reading convinient?

**Comment by DeepDiver1975** [comment]
> Q: is there a plan to use / fork icewind1991 logreader app, create a new one or include an existing other log reader repository for owncloud to make log reading convinient?

logreader looks pretty promissing - I suggest we use the appstore to publish this app for anybody who is interested.

**Comment by mmattel** [comment]
I have just seen that Icewind1991 has moved logreader from his persoal repository to nextcloud. That needs checking if or how it impacts this idea...

**Pull request merged**
