### PR TITLE
[WIP] file list is being reloaded based on etag change

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs #983

@PVince81 

bildschirmvideo von 27 02 2015 16_42_24

### CODE REVIEW

**Comment by PVince81** [comment]
Code looks good.

As discussed: this will mess up with the scroll position. Need to find a way to keep it after refresh.

Also if the user was going to click on anything in the list, and the list suddenly reloads... boom

**Comment by jancborchardt** [comment]
:O this is big!

Just one thing: Since it's the same folder reloading, can we have the spinner (incl half transparent white background) overlay the list instead of replacing it?
Let me know if what I need to help to make that happen.

**Comment by PVince81** [comment]
Note: the list also auto-reloads after detecting uploads, even if the upload was done in the same window.

**Comment by jancborchardt** [comment]
Right – can we then even do it completely without the spinner, and just insert/remove the new elements?

**Comment by jancborchardt** [comment]
Ideally we have a small sliding/expanding animation for the row when something gets added or removed, similar to in the Mail app. There we collapse a mail when it’s deleted: https://github.com/owncloud/mail/blob/master/js/views/message.js#L81

**Comment by PVince81** [comment]
So if the user is hovering over "somefile.txt", ready to click on an action, suddenly 10 files appear on top of it. So the row that is currently hovered needs to stay fixed while everything else moves to avoid having users click on the wrong row. Can be tricky to implement.

Inserting new elements means we need to diff the new list of files with the old one we have cached, should be possible (considering that at the moment we have the full file list cached, not only what is displayed). Would probably not be very compatible with real pagination.

That will be a lot of special code, so I'm not sure whether it's worth spending the time and also maintain that.

Collapsing on delete should be feasible though.

**Comment by MorrisJobke** [comment]
@deepdiver1975 What about this? Is this still valid?

**Comment by jancborchardt** [comment]
@DeepDiver1975 move to 9.0 because of feature freeze? Thanks

**Comment by jancborchardt** [comment]
@DeepDiver1975 any updates here? Still current or throw away?

**Comment by DeepDiver1975** [comment]
> throw away?

because of the big delta -> :skull:

**Pull request closed without merging**
