### PR TITLE
feat: encryption keys location can be specified by the storage implementation

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
This allows storage implementations to specify the location for encryption keys
https://github.com/owncloud/files_spaces needs this because the space does not belong to a user.

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/4687
- alternative approach to #39091

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliEncryption-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33855/120/1

**Comment by DeepDiver1975** [comment]
a specific branch of the encryption app is required

Screenshot from 2021-12-01 16-55-54

**Comment by mmattel** [comment]
This is docs relevant, please file a docs issue wheh close to merge.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33941/172/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliEncryption-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34037/120/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliEncryption-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34278/120/1

**Comment by DeepDiver1975** [comment]
cleaning up - I think this is no longer of anybody's interest

**Pull request closed without merging**
