### PR TITLE
Adjust isLocal() on encryption wrapper

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs #15848

@icewind1991 @schiesbn @VicDeo @PVince81 @oparoz please have a look ....

.... for sure not the perfect solution - but this might already help in some cases. THX

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: makes sense

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by oparoz** [comment]
That's a good thing for 8.1, because it makes the method behave like in 8.0 :+1:

**Comment by bantu** [comment]
Certainly an improvement over the previous solution.

**Pull request merged**
