### PR TITLE
Updated davclient.js to support MKCOL in edge

### LINKED ISSUE #21710: [Edge] Folder creation using the web ui fails.
### Steps to reproduce

Using Microsoft's Edge do:

1. Create a folder using the web UI.

### Expected behaviour
Folder is created.

### Actual behaviour
There is an error. MKCOL operation fails.

### Server configuration
**Operating system**:
CentOS 6.6

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - admin_audit: 0.7
  - dav: 0.1.3
  - enterprise_key: 0.1.0
  - files: 1.4.1
  - files_pdfviewer: 0.8
  - files_sharing: 0.8.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoviewer: 0.1.3
  - firewall: 2.3.0
  - firstrunwizard: 1.1
  - gallery: 14.3.0
  - notifications: 0.2.2
  - provisioning_api: 0.4.0
  - templateeditor: 0.1
  - windows_network_drive: 0.1.1
Disabled:
  - encryption
  - external
  - federation
  - files_antivirus
  - files_drop
  - files_external
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - user_external
  - user_ldap
  - user_shibboleth
```

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"oR\/RcedmbCUBhI8MJjpe","remoteAddr":"176.31.107.195","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 415 The request body for the MKCOL request must have an xml Content-Type\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\UnsupportedMediaType\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(53): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php\",\"Line\":563}","level":4,"time":"2016-01-14T10:08:57+00:00"}
```

### Client configuration

**browser**
Edge

### PR DESCRIPTION
**Pull request by rullzer**
Bump of davclient.js containing: https://github.com/evert/davclient.js/pull/17

Fixes: https://github.com/owncloud/core/issues/21710

CC: @SergioBertolinSG @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested in Edge and it works now (previously a 412 was returned). Also Safari still works :+1:

**Comment by ketolajuha** [comment]
Hi,

I'm experiencing the same behaviour with Internet Explorer v11 - cannot create new folders through WebUI with IE11, but I can create it with EDGE without problems.

Setup in short (sorry short setup, but I believe the trail leads to same issue):

* Browser installed in OS win10 with latest patches. (My IE version 11.103.10586.0)
* Clean install of Owncloud 9.

Error Recorded to log:
----------------

Exception: {"Message":"HTTP\/1.1 415 The request body for the MKCOL request must have an xml Content-Type","Exception":"Sabre\\DAV\\Exception\\UnsupportedMediaType","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/volume1\/web\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#3 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/volume1\/web\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#5 \/volume1\/web\/owncloud\/remote.php(138): require_once('\/volume1\/web\/ow...')\n#6 {main}","File":"\/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","Line":563,"User":"JKetola"} 

------------------

Should the code perhaps be updated for IE as well?

**Comment by MorrisJobke** [comment]
> Should the code perhaps be updated for IE as well?

Please open a new issue

**Comment by ketolajuha** [comment]
Thanks for the nudge...  
Issue #23067 created.

**Pull request merged**
