### PR TITLE
[CI] [tests-only] Update drone.star file

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
Update `drone.star`  file. changes made are:
- Remove `'pull': 'always'`
- put image name to a constant
- implement `skip-if-unchanged`

## Related Issue

Part of:
- https://github.com/owncloud/QA/issues/729
- https://github.com/owncloud/QA/issues/728
- https://github.com/owncloud/QA/issues/730
- https://github.com/owncloud/QA/issues/732

## How Has This Been Tested?

- test environment:
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)
- [x] CI

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm :+1:

**Review by saw-jan — COMMENTED** [review]
LGTM

**Review by SagarGi — COMMENTED** [review]
@SwikritiT  LGTM as well but for others app we have used the constant for Default node version and Default Php version. You might as well change it for core as well so that it will remain similar for all.

**Comment by amrita-shrestha** [comment]
@SwikritiT did it throw a comment when the test fail?

**Review by amrita-shrestha — COMMENTED** [review]
@SwikritiT did it throw a comment when the test fail?

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuth-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/35097/47

**Comment by SwikritiT** [comment]
> boom Acceptance tests pipeline **apiAuth-mariadb10.2-php7.4** failed. The build has been cancelled.
> 
> https://drone.owncloud.com/owncloud/core/35097/47

@amrita-shrestha yes it does

**Review by grgprarup — COMMENTED** [review]
LGTM

**Review by amrita-shrestha — COMMENTED** [review]
lgtm

**Review by individual-it — APPROVED** [review]

**Pull request merged**
