### PR TITLE
Fix error when reading empty authtoken names from db

### PR DESCRIPTION
**Pull request by IljaN**
Issue: #30792

### CODE REVIEW

**Comment by patrickjahns** [comment]
Not sure if this is the right path to go - we explicitly disallowed empty tokens to be entered in the frontend (which makes sense).

Alternative should rather be to provide a proper migration when upgrading?

**Comment by IljaN** [comment]
@patrickjahns Where empty names allowed in the version before?

**Comment by DeepDiver1975** [comment]
Title is missleading

**Comment by IljaN** [comment]
@DeepDiver1975 better?

**Comment by patrickjahns** [comment]
@IljaN 
in 10.0.4 it was allowed - with https://github.com/owncloud/core/pull/29831 it was discouraged 
Issue fixed by disallowing empty tokens: 
https://github.com/owncloud/core/issues/29709

Expected behavior changed to requiring a name for the token with 10.0.5

**Comment by IljaN** [comment]
> Alternative should rather be to provide a proper migration when upgrading?

@PVince81 I think @patrickjahns  has a point, what do you think?

**Comment by PVince81** [comment]
Ok for a migration so no code workaround needed.

I just found it weird that we validate the token data even after reading from the DB.

**Comment by IljaN** [comment]
It`s probably because the DB layer is using same setters when populating objects from db

**Comment by IljaN** [comment]
Will create a migration then

**Comment by patrickjahns** [comment]
@IljaN 
Exactly - that's what made me triage the bug to 'lets just create a string in the db'
https://github.com/owncloud/core/blob/master/lib/public/AppFramework/Db/Entity.php#L67-L70

**Pull request closed without merging**
