### PR TITLE
Check whether we have a user, before trying to use it as an object

### LINKED ISSUE #13270: Encryption is broken with public sharing
On current master when installing new:

1. Install ownCloud as user "admin"
2. Enable encryption app
3. Log out
4. Login
5. Create a file "shared.txt"
6. Share that file publicly
7. Access the file
8. Try to download it

Get the following error:
```
[Mon Jan 12 13:58:57.889593 2015] [:error] [pid 44077] [client 192.168.0.17:55522] PHP Fatal error:  Call to a member function getUID() on null in /Users/lreschke/Programming/core/apps/files_encryption/lib/stream.php on line 139, referer: http://192.168.0.17/index.php/s/6eh2VfEbVfPgcGT
```

@schiesbn

### PR DESCRIPTION
**Pull request by nickvergessen**
FIx #13270 

@LukasReschke @schiesbn

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by DeepDiver1975** [comment]
Looks good :+1: 

@LukasReschke can you please verify that this fixes #13270 - THX

**Comment by LukasReschke** [comment]
I'd love to say: Awesome it works. I'd also love to say: I'm capable to review anything related to the encryption blackmagic that happens but as every-time we change something there something other breaks I'm kinda keen to avoid it ;-)

That said, this breaks other stuff: `Fatal error: Call to a member function getUID() on null in /Users/lreschke/Programming/core/lib/private/user.php on line 219` when logging-in after enabling encryption.

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by DeepDiver1975** [comment]
yepp - break apart :-1: 

````
Mon Jan 12 21:55:40 2015] PHP Fatal error:  Call to a member function getUID() on null in /home/deepdiver/Development/ownCloud/core/lib/private/user.php on line 219
[Mon Jan 12 21:55:40 2015] PHP Stack trace:
[Mon Jan 12 21:55:40 2015] PHP   1. {main}() /home/deepdiver/Development/ownCloud/core/index.php:0
[Mon Jan 12 21:55:40 2015] PHP   2. OC::handleRequest() /home/deepdiver/Development/ownCloud/core/index.php:28
[Mon Jan 12 21:55:40 2015] PHP   3. OC::handleLogin() /home/deepdiver/Development/ownCloud/core/lib/base.php:819
[Mon Jan 12 21:55:40 2015] PHP   4. OC::tryFormLogin() /home/deepdiver/Development/ownCloud/core/lib/base.php:855
[Mon Jan 12 21:55:40 2015] PHP   5. OC_User::login($loginname = *uninitialized*, $password = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/base.php:952
[Mon Jan 12 21:55:40 2015] ::1:36652 [500]: / - Call to a member function getUID() on null in /home/deepdiver/Development/ownCloud/core/lib/private/user.php on line 219

Process finished with exit code 139

**Comment by DeepDiver1975** [comment]
It falls apart in the login hook where the current user is logged out - https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/hooks.php#L91

And later after the login hooks have been processed there is no user anymore - https://github.com/owncloud/core/blob/master/lib/private/user.php#L219

**Comment by DeepDiver1975** [comment]
This behavior is caused by the migration status being in progress - it never finished because if was falling apart in another area:

````
[Mon Jan 12 22:15:23 2015] PHP Fatal error:  Call to a member function getId() on boolean in /home/deepdiver/Development/ownCloud/core/lib/private/files/node/node.php on line 144
[Mon Jan 12 22:15:23 2015] PHP Stack trace:
[Mon Jan 12 22:15:23 2015] PHP   1. {main}() /home/deepdiver/Development/ownCloud/core/index.php:0
[Mon Jan 12 22:15:23 2015] PHP   2. OC::handleRequest() /home/deepdiver/Development/ownCloud/core/index.php:28
[Mon Jan 12 22:15:23 2015] PHP   3. OC::handleLogin() /home/deepdiver/Development/ownCloud/core/lib/base.php:819
[Mon Jan 12 22:15:23 2015] PHP   4. OC::tryFormLogin() /home/deepdiver/Development/ownCloud/core/lib/base.php:855
[Mon Jan 12 22:15:23 2015] PHP   5. OC_User::login($loginname = *uninitialized*, $password = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/base.php:952
[Mon Jan 12 22:15:23 2015] PHP   6. OC\User\Session->login($uid = *uninitialized*, $password = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/user.php:216
[Mon Jan 12 22:15:23 2015] PHP   7. OC\Hooks\PublicEmitter->emit($scope = *uninitialized*, $method = *uninitialized*, $arguments = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/user/session.php:201
[Mon Jan 12 22:15:23 2015] PHP   8. OC\Hooks\BasicEmitter->emit($scope = *uninitialized*, $method = *uninitialized*, $arguments = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/hooks/publicemitter.php:18
[Mon Jan 12 22:15:23 2015] PHP   9. call_user_func_array:{/home/deepdiver/Development/ownCloud/core/lib/private/hooks/basicemitter.php:85}(*uninitialized*, *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/hooks/basicemitter.php:85
[Mon Jan 12 22:15:23 2015] PHP  10. OC\Server->OC\{closure}($user = *uninitialized*, $password = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/hooks/basicemitter.php:85
[Mon Jan 12 22:15:23 2015] PHP  11. OC_Hook::emit($signalclass = *uninitialized*, $signalname = *uninitialized*, $params = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/server.php:159
[Mon Jan 12 22:15:23 2015] PHP  12. call_user_func:{/home/deepdiver/Development/ownCloud/core/lib/private/hook.php:78}(*uninitialized*, *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/hook.php:78
[Mon Jan 12 22:15:23 2015] PHP  13. OCA\Files_Encryption\Hooks::login($params = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/hook.php:78
[Mon Jan 12 22:15:23 2015] PHP  14. OCA\Files_Encryption\Util->encryptAll($dirPath = *uninitialized*) /home/deepdiver/Development/ownCloud/core/apps/files_encryption/lib/hooks.php:102
[Mon Jan 12 22:15:23 2015] PHP  15. OC\Files\View->rename($path1 = *uninitialized*, $path2 = *uninitialized*) /home/deepdiver/Development/ownCloud/core/apps/files_encryption/lib/util.php:798
[Mon Jan 12 22:15:23 2015] PHP  16. OC_Hook::emit($signalclass = *uninitialized*, $signalname = *uninitialized*, $params = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/files/view.php:538
[Mon Jan 12 22:15:23 2015] PHP  17. call_user_func:{/home/deepdiver/Development/ownCloud/core/lib/private/hook.php:78}(*uninitialized*, *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/hook.php:78
[Mon Jan 12 22:15:23 2015] PHP  18. OCA\Search_Lucene\Hooks\Files::renameFile($param = *uninitialized*) /home/deepdiver/Development/ownCloud/core/lib/private/hook.php:78
[Mon Jan 12 22:15:23 2015] PHP  19. OC\Files\Node\Node->getId() /home/deepdiver/Development/ownCloud/core/apps2/search_lucene/hooks/files.php:115
[Mon Jan 12 22:15:23 2015] ::1:37966 [500]: / - Call to a member function getId() on boolean in /home/deepdiver/Development/ownCloud/core/lib/private/files/node/node.php on line 144

**Comment by DeepDiver1975** [comment]
And this lovely error is caused by a part file ...

facepalm

**Comment by DeepDiver1975** [comment]
@butonic Can you please handle the case where $node has no id?

@icewind1991 please adjust the node implementation so that we don't run into this NPE scenario?

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/core/issues/13040

**Comment by schiesbn** [comment]
We always need a user id, if no user is logged in we need to extract the UID from the path, see https://github.com/owncloud/core/pull/13288

**Comment by DeepDiver1975** [comment]
We still have to have a look at all the issues above. @butonic @icewind1991 @schiesbn THX

**Pull request closed without merging**
