### PR TITLE
[8.2] cache isLocal for shared storage

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes https://github.com/owncloud/core/issues/24651

Better performance for isLocal.

@timm2k @scolebrook can you verify that this fixes the problem for you

9.0/9.1 both have separate sollutions

@PVince81 @rullzer

### CODE REVIEW

**Comment by scolebrook** [comment]
@icewind1991 Working fine. Thank you.
@bboule @gig13 

We could only get this issue to occur on our production environment. Considering our 3 node mysql cluster melted with the previous version of this function, testing this version on production servers was a little scary. But there is no noticeable change in mysql query rate or connections from before (isLocal commented out entirely) and after (this version).

Great job.

**Comment by rullzer** [comment]
:+1:

**Comment by timm2k** [comment]
:+1:

https://cloudstorage.uni-oldenburg.de/index.php/s/QkKgcJRFPbOpf1s

**Comment by timm2k** [comment]
Overall OC 8.2.5 produces much more queries than 8.1.6: https://cloudstorage.uni-oldenburg.de/index.php/s/KOH0kiKT3X6nETo

Is this an expected behavior?

**Pull request merged**
