### PR TITLE
Fix warning about an ignored lock release

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Don't try to release a lock that we haven't acquired.
```
{"reqId":"lVtnJZDr0KsCccLRP6iZ","level":2,"time":"2021-03-23T13:05:30+00:00","remoteAddr":"10.0.2.27","user":"admin","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/admin\/giphy-downsized-large.gif","message":"ignoring lock release with type 1 for files\/4acc23eee354b2c83e625301b3e80f8f. Lock hasn't been acquired before"}
```

## Related Issue
No opened issue yet

## Motivation and Context
This is mostly for cleanup. This "bug" is harmless. Redis implementation will just ignore the release without changing anything. It's expected that the DB implementation does something similar without causing problems.

## How Has This Been Tested?
Checked in 10.7.0RC1.
1. Having filelocking enabled with redis
2. Upload a file using the web UI

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by VicDeo — APPROVED** [review]
Looks good

**Review by AlexAndBear — APPROVED** [review]

**Comment by JanAckermann** [comment]
@jvillafanez LGTM, merge?

**Comment by voroyam** [comment]
@jvillafanez in which release will this PR be included in?

**Comment by jvillafanez** [comment]
I don't think it made it to 10.7 so it will be in 10.8

**Pull request merged**
