### PR TITLE
Add a fancy behaviour to failed logins

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
New behaviour:

chrome_bad_login

### CODE REVIEW

**Comment by davitol** [comment]
👍 😍

**Comment by SergioBertolinSG** [comment]
@DeepDiver1975 seems there is a problem with a unit test, not related?:

```
Test\Core\Controller\TwoFactorChallengeControllerTest::testShowChallenge
Undefined variable: csp

/var/lib/jenkins/workspace/owncloud-core/core/PR-25940/core/Controller/TwoFactorChallengeController.php:127
/var/lib/jenkins/workspace/owncloud-core/core/PR-25940/tests/Core/Controller/TwoFactorChallengeControllerTest.php:129
```

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 seems there is a problem with a unit test, not related?:

https://github.com/owncloud/core/pull/25944

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
At least a contribution that it's based on my work would be nice 😉 

nextcloud/server#695

But it's really nice, isn't it? 🎉 

Shake it! 😃

**Pull request merged**
