### PR TITLE
Allow user to set an empty email address

### LINKED ISSUE #16057: Not possible to remove email address from personal info
Currently it’s not possible to revert the email address field back to empty. It doesn’t trigger the autosave in case of being empty. Also when pressing enter, there’s a full page refresh.

@PVince81 @MorrisJobke

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #16057 

cc @jancborchardt

### CODE REVIEW

**Comment by nickvergessen** [comment]
Will commit test once jenkins is done

**Comment by MorrisJobke** [comment]
@nickvergessen Thanks for the unit tests \o/ You rock!

**Comment by nickvergessen** [comment]
Fixed the wrong data provider name @MorrisJobke

**Comment by karlitschek** [comment]
:+1:

**Comment by Xenopathic** [comment]
:+1:

**Comment by jancborchardt** [comment]
:+1:

**Comment by jancborchardt** [comment]
Thank you @MorrisJobke!

**Pull request merged**
