### PR TITLE
Update verify checksums console output to flow more naturally

### PR DESCRIPTION
**Pull request by settermjd**
## Description

Update verify checksums console output to flow more naturally

## Motivation and Context

The previous version of the console output just doesn't flow naturally, so I suggest this, modest, update to it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] UI Text

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by IljaN — APPROVED** [review]

**Comment by IljaN** [comment]
@settermjd Please backport so stable10

**Comment by PVince81** [comment]
please backport to stable10

**Comment by phil-davis** [comment]
@settermjd looks like backport to ``core`` ``stable10`` is still outstanding.

**Comment by phil-davis** [comment]
Backport ``stable10`` #31449

**Pull request merged**
