### PR TITLE
adding a windows smb config for testing to ci

### PR DESCRIPTION
**Pull request by DeepDiver1975**
https://ci.owncloud.org/job/server-master-linux-externals-smb-windows/17/database=sqlite,external=smb-windows,label=master/console

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@icewind1991 FYI - this executed the smb unit tests against a windows server 2012

@MorrisJobke

**Comment by DeepDiver1975** [comment]
@Xenopathic I took the freedom to cherry-pick d6b9b37 - sorry :speak_no_evil:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by Xenopathic** [comment]
@DeepDiver1975 That commit could have been its own PR TBH :laughing:

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 That commit could have been its own PR TBH :laughing:

Sure - but it saved me some time while testing - so here we go :wink:

**Comment by DeepDiver1975** [comment]
failing jenkins is unrelated

**Comment by Xenopathic** [comment]
@DeepDiver1975 I cherry-picked the fix for the AmazonS3Migration bug, so your tests should completely succeed now

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@Xenopathic awesome - THX

**Comment by nickvergessen** [comment]
Looks good, only the credentials confused me :cyclone:

**Pull request merged**
