### PR TITLE
Fix overflowing public link title

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Long public-link titles will be ellipsed if they are "too long" to prevent pushing interactive elements out of view (and reach).

## Related Issue
https://central.owncloud.org/t/offentlicher-link-in-version-10-0-4-ist-nicht-kopierbar/11468

## Motivation and Context
See above.

## How Has This Been Tested?

Visual/functional test in latest FF and Chrome.
(My VM broke so pls test in IE)

## Screenshots (if appropriate):
before-and-after

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
can we get this tested in IE11 ?

**Comment by felixheidecke** [comment]
> can we get this tested in IE11 ?

Wink @ChrisEdS ;-)

**Review by ChrisEdS — APPROVED** [review]

**Comment by phil-davis** [comment]
More "random" UI test fails in drone. One of them was when trying to delete the last file in a folder, and in another run:
```
 GuzzleHttp\Exception\ServerException: Server error response [url] http://server/remote.php/webdav/lorem.txt [status code] 503 [reason phrase] Service Unavailable in /drone/src/lib/composer/guzzlehttp/guzzle/src/Exception/RequestException.php:89
```
I restarted drone again.

**Comment by PVince81** [comment]
conflicts

**Comment by PVince81** [comment]
@felixheidecke please solve the conflict so we can merge this

**Pull request merged**
