### PR TITLE
Add getReshareAttributes method to shareitemmodel with fix for parsing

### PR DESCRIPTION
**Pull request by mrow4a**
This PR:
- make sure reshare properties are properly parsed
- expose reshare attributes to the apps

### CODE REVIEW

**Comment by mrow4a** [comment]
@PVince81 @micbar this is required for https://github.com/ONLYOFFICE/onlyoffice-owncloud/pull/286

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by phil-davis** [comment]
@mrow4a is there any code change here that gets used currently?
Apart from all the general smoketesting that verifies that existing UI (re)sharing functionality still works, is there anything in particular that might be observable and testable on the front-end?

**Comment by mrow4a** [comment]
@phil-davis it is already tested in https://github.com/owncloud/core/blob/master/core/js/tests/specs/shareitemmodelSpec.js#L228

**Pull request merged**
