### PR TITLE
Move \OCP\Http to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @PVince81 @nickvergessen @MorrisJobke @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
@PVince81 Ready for merge :)

**Comment by PVince81** [comment]
The integration tests haven't passed yet, but ok... If it breaks on master I'll know who to call :wink:

**Comment by MorrisJobke** [comment]
> If it breaks on master I'll know who to call

GHOSTBUSTERS!!! 👻

**Pull request merged**
