### PR TITLE
Fix checkboxes in files_external

### LINKED ISSUE #19118: Checkboxes are missing
In the external storage configuration form on master, checkboxes are no longer displayed:

screenshot_2015-09-17_11-09-12

cc @jancborchardt @PVince81

### PR DESCRIPTION
**Pull request by Henni**
fixes #19118 

cc @Xenopathic @raghunayyar @jancborchardt

### CODE REVIEW

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by raghunayyar** [comment]
:+1:

**Comment by raghunayyar** [comment]
I have no idea why the branch is out of date. cc @Henni

**Comment by Xenopathic** [comment]
LGTM :+1:

**Comment by LukasReschke** [comment]
> I have no idea why the branch is out of date. cc @Henni

Merges do require that the branch uses the latest code from master to ensure that there will no problems caused by merge conflicts etc.

**Comment by jancborchardt** [comment]
@DeepDiver1975 or @karlitschek have to merge …

**Pull request merged**
