### PR TITLE
config.php contents won't be overwritten by other files

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Ensure config.php takes priority over other config files

## Related Issue
https://github.com/owncloud/enterprise/issues/3775#issuecomment-633996000

## Motivation and Context
If there are multiple configuration files, changing the config.php file doesn't guarantee the change will take effect.

## How Has This Been Tested?
Checked manually. The contents of the config.php takes priority over other config files that could be in the config directory.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by micbar — CHANGES_REQUESTED** [review]
Please evaluate with PM and deployments before moving on.

**Comment by mmattel** [comment]
Q:
if (1) `config.php`  and (2) `my-other-config.php` has the same key but different value pairs, which will then take precedence. Does reading first implies first key wins on multiple occurences or do we still have last key overwrites pre-last.

In any case, this PR is doc relevant, pls file an issue and reference

**Comment by jvillafanez** [comment]
Currently, "last key wins". This PR change it to "first key wins". In practice, this PR ensures that the keys in the config.php don't get overwritten by other configuration files.
This is still under evaluation and it isn't clear if this will be merged.

**Comment by felixboehm** [comment]
rejected. we have to keep the load order of config files.
1. config.php
2. other.config.php

This mechanism is used to force certain configs by admins.
The issue is, that oc writes to the config, which is bad when config files are expected to not change.

**Comment by micbar** [comment]
I fully agree with that!

Overriding config.php with more specific values is a needed feature.

**Pull request closed without merging**
