### PR TITLE
Use capped cache for encryption's user access list

### PR DESCRIPTION
**Pull request by PVince81**
For https://github.com/owncloud/core/issues/24403#issuecomment-217817883

@owncloud/filesystem @owncloud/encryption @butonic @mmattel @nickvergessen @rullzer

### CODE REVIEW

**Comment by guruz** [comment]
semi- 👍 

Where was the (non capped?) $this->cache initialized before? In some sub class?

Does it make sense to construct it lazily only in getAccessList() ?

**Comment by PVince81** [comment]
> Where was the (non capped?) $this->cache initialized before? In some sub class?

It wasn't. It's PHP magic :crystal_ball: 

This is valid PHP:
```php
<?php
$x = null;
$x[] = 1;
```

I don't think there is much benefit to construct it lazily especially that this here is just a utility class instantiated once.

**Comment by PVince81** [comment]
> This is valid PHP:

I tested that locally and couldn't believe my eyes...

**Comment by butonic** [comment]
:+1:

**Comment by nickvergessen** [comment]
Not even needed to `$x = null`: https://3v4l.org/vC6gF

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/25084

**Comment by PVince81** [comment]
Damn, wrong PR number

**Pull request merged**
