### PR TITLE
Fix oc:tags tag list serializer

### LINKED ISSUE #21852: Cannot PROPPATCH tags any more
Possibly related to Sabre update.

proppatch-tags.xml:
```xml
<?xml version="1.0"?>
<d:propertyupdate xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:set>
    <d:prop>
      <oc:tags>
        <oc:tag>tag1</oc:tag>
        <oc:tag>tag2</oc:tag>
      </oc:tags>
    </d:prop>
  </d:set>
</d:propertyupdate>
```

Gives:
```
{"reqId":"OPzxm\/Y5VSAP4Z0NWZIo","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to undefined method Sabre\\DAV\\Xml\\Property\\Complex::getTags() at \/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/connector\/sabre\/tagsplugin.php#270","level":3,"time":"2016-01-22T12:58:01+00:00","method":"PROPPATCH","url":"\/owncloud\/remote.php\/files\/file.txt"}
```

### PR DESCRIPTION
**Pull request by PVince81**
Fixes propfind/proppatch of oc:tags

Fixes https://github.com/owncloud/core/issues/21852

Please review @blizzz @icewind1991 @nickvergessen @DeepDiver1975 @MorrisJobke 

Note: nothing to do with system tags, these are the personal tags

### CODE REVIEW

**Comment by blizzz** [comment]
As according to doc :+1:

**Comment by PVince81** [comment]
Looks like more is broken, the propfind returns weird results:
```xml
   <d:prop>
    <oc:id>00000003ockbfur1449k</oc:id>
    <oc:permissions>RDNVW</oc:permissions>
    <d:getlastmodified>Fri, 22 Jan 2016 14:50:28 GMT</d:getlastmodified>
    <d:getetag>&quot;0f5790b413e43205fc08417261a0a3cc&quot;</d:getetag>
    <oc:downloadURL></oc:downloadURL>
    <oc:tags>
     <tag1/>
    </oc:tags>
    <tag2/>
   </d:prop>
  </d:propstat>
```

as if the serializer just exploded. Let me debug this.

**Comment by PVince81** [comment]
Here we go, fixed the serializer. The output not looks fine:
```xml
    <oc:tags>
     <oc:tag>tag1</oc:tag>
     <oc:tag>tag2</oc:tag>
    </oc:tags>
    <oc:favorite></oc:favorite>
```

**Comment by nickvergessen** [comment]
:+1: works

**Pull request merged**
