### PR TITLE
Send password reset link to new users

### PR DESCRIPTION
**Pull request by imujjwal96**
## Related Issue

#17398 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tomneedham** [comment]
This looks good 😄 

@pmaier1 Just checking that this is desired functionality and that it does not affect any other use cases here?

**Comment by PVince81** [comment]
@tomneedham seems @pmaier1 already read about it here https://github.com/owncloud/core/issues/17398#issuecomment-292191822 and set prio

**Comment by PVince81** [comment]
Tested, works.

@imujjwal96 would it be possible to also adjust/extend unit tests to include this case ?

**Comment by PVince81** [comment]
@imujjwal96 can you finish this ? if not please let us know so someone else can take over

**Comment by imujjwal96** [comment]
Working on it. Sorry for the delay.

**Comment by PVince81** [comment]
@imujjwal96 thanks a lot!

**Comment by ManuelRighi** [comment]
Hello,
I'am interested in this new feature.
It's possible to use in production environment ? If yes, how ?

THanks

**Comment by imujjwal96** [comment]
haha sure!

**Comment by PVince81** [comment]
@imujjwal96 another rebase please ? Seems the results were still from the old CI setup. The new one only has on Jenkins PR entry instead of two. If that fails again I'll take over. Thanks.

**Comment by imujjwal96** [comment]
What did i do? >.<

**Comment by imujjwal96** [comment]
@PVince81 I pushed a wrong local branch to the remote branch! I've rectified it though but now Jenkins states that the commit cannot be built

**Comment by PVince81** [comment]
@imujjwal96 I suggest to try rebasing again. Seems Jenkins has trouble to check out this branch.

Worst case, close the PR, push to a different branch and make a new PR.

**Comment by radheck** [comment]
Im already have installed owncloud 10.0.3, and I am having problems when i tried to configure and recover email for a password of  normal user, however if this user is an admin the email recovering works perfectly.
What could be the cause ? Is it correct inthis thread ? thanks a lot .

**Comment by tomneedham** [comment]
@radheck Please open a new issue ticket and fill out the information - or try on central.owncloud.org. Sounds like this isn't quite the same as this code change. :)

**Comment by PVince81** [comment]
I wonder if we should add a switch to disable this. Not all admins might be happy to have password reset links sent to every user when provisioning over the APIs.

**Comment by PVince81** [comment]
@pmaier1 any thoughts on this feature and configurability ?

**Comment by PVince81** [comment]
already implemented in some other form in 10.0.10

**Pull request closed without merging**
