### PR TITLE
[WIP] Allow * wildcard in trusted_domains to support unstable DNS names and unstable IP addresses

### PR DESCRIPTION
**Pull request by jernst**
I'm not quite understanding how ownCloud releases are produced from git, nor how to run the tests, and so I don't quite know how to test this. I'm hoping that a friendly soul will advise and/or merge. Thanks.
Corresponding pull requests to docs coming.

### CODE REVIEW

**Comment by Raydiation** [comment]
I feel like this is really bad from a security POV and basically circumvents the host header poisoning prevention. Use a free service like http://www.noip.com/ to handle dynamic ips or use a VPN  :-1:

**Comment by jernst** [comment]
@Raydiation: either you enforce security in the code base to the extent that it is "impossible" to run ownCloud with anything other than maximum security (per your view, whatever that is), in which case you make it impossible for users who know what they are doing (or are willing to take the risk) to do what they want. Or you set the right secure defaults, but let people override them. I'm in favor of #2, thus this proposed patch. I do not believe that it reduces security at all, unless the user decides they want that.

**Comment by LukasReschke** [comment]
Agreed with @jernst - if this change is done correctly I don't mind it.

There is always a compromise between usability and security. This one is fine and has certainly some reasonability behind it. (for example auto-provisoning in a fixed IP block / subdomain etc...)

**Comment by LukasReschke** [comment]
Requires unit tests and rebase. Otherwise we can't merge this :-(

**Comment by indiebox** [comment]
We currently do our own ownCloud patch in UBOS, it's here: https://github.com/indiebox/ubos-owncloud/blob/master/owncloud/allow-wildcard-trusted.patch. This replaces this merge request.

Corresponding test is here: https://github.com/indiebox/ubos-owncloud/blob/master/owncloud/tests/OwnCloud1Test.pm but that uses the UBOS webapptest framework, not your's. I don't currently have time to get up to speed with your test infrastructure, so I don't know how to proceed.

**Comment by LukasReschke** [comment]
Closing due to inactivity. Feel free to reopen once unit tests have been added, see https://github.com/owncloud/core/blob/525745caf5c80f46522a89fefb2e6ec29acfc73c/tests/lib/appframework/http/RequestTest.php#L824-L848 and Co. for examples.

**Pull request closed without merging**
