### PR TITLE
enforce_home_folder_naming_rule cannot be configured in config.php

### PR DESCRIPTION
**Pull request by blizzz**
it is an appconfig setting.

@MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
cc @carlaschroder

**Comment by MorrisJobke** [comment]
This was wrongly documented

**Comment by blizzz** [comment]
Yup, was a topic in https://github.com/owncloud/documentation/pull/1955

**Comment by carlaschroder** [comment]
> This was wrongly documented

Fixed before merging the PR, thanks to good reviewing.

**Comment by blizzz** [comment]
@carlaschroder I think he meant it was wrongly documented in ``config/config.sample.php`` which is cleaned up with this PR. Thumbs? :)

**Comment by blizzz** [comment]
@karlitschek backport to 8.2? removes wrong-placed doc from config sample, no real code change.

**Comment by karlitschek** [comment]
makes sense. please backport

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/pull/21261

**Comment by carlaschroder** [comment]
:+1: 

:)

**Pull request merged**
