### PR TITLE
[stable9.1] Skip hidden files when counting visible files in list

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/26522 to stable9.1

@davitol @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Review ? @mjobst-necls

**Comment by mjobst-necls** [comment]
Well, I would like to test the code, but I'm not able to get the branch stable9.1 run.

Nginx posts the following error:
*1932 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /opt/dev/workspaces/oc/index.php:75

Maybe, some resources are missing, but there is neither a Makefile nor do I know how to get missing files if there are some.

@PVince81 Can you help me?

**Comment by PVince81** [comment]
@mjobst-necls the makefile was only introduced recently.
If you're checking out an older stable branch, you need to run `git submodule update --init`. That should be enough to make it check out the libraries.

**Comment by mjobst-necls** [comment]
Ok, this works.

By the way, I found out, that after renaming a file by adding a dot as a prefix, the file summary is not updated.

test

The column header is also not updated. I'll check whether this behavior still exists in the master branch and if so, I'm going to add a new issue.

**Comment by PVince81** [comment]
@mjobst-necls thanks ! As this PR here is only a backport I suggest merging if it works like the master one and address the other one as part of your new ticket.

For a successful review I'll need a thumbs up from you then 😄

**Comment by mjobst-necls** [comment]
👍

**Pull request merged**
