### PR TITLE
Remove background from curved logo

### PR DESCRIPTION
**Pull request by williambargentball**
The favicon currently has white corners, this make them transparent.

### CODE REVIEW

**Comment by PVince81** [comment]
@owncloud/designers please review

**Comment by skjnldsv** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
Hmmm .... I merged this one to early :cry: 

@williambargent please grant MIT license to your change

**Comment by williambargent** [comment]
@DeepDiver1975 The contributor agreement link returns a 404 error.
How to I grant MIT license?

**Comment by DeepDiver1975** [comment]
> How to I grant MIT license?

just add a comment here

**Comment by williambargent** [comment]
Change follows MIT License.

**Pull request merged**
