### PR TITLE
Password set via OCS API should not be double escaped

### LINKED ISSUE #15777: Setting a password using the OCS API makes shared links unusable.
### Steps to reproduce

1. Share a folder by link.
2. Update the public share adding a password
    2.1. get the shares ids:

    ```
    curl -X GET http://USER:PASSWORD@OWNCLOUDPATH/ocs/v1.php/apps/files_sharing/api/v1/shares
    ```
   2.2. Add a password

   ```
   curl -v -X PUT -d password=sergio http://USER:PASSWORD@OWNCLOUDPATH/ocs/v1.php/apps/files_sharing/api/v1/shares/SHARE_ID
   ```

### Expected behaviour
A password is added to the shared link.

### Actual behaviour
Password is added, but you can't open the shared file/folder, the password is not recognized.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.2","versionstring":"8.1 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
None.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

### Client configuration

**browser**
Chrome

### PR DESCRIPTION
**Pull request by rullzer**
Should fix #15777

Basically there was to much escaping. So the hash got surrounded by quotes in the database.

This got in since it is very hard to unit test this.
The only real solution I see is to really insert the code in mocked database. Retrieve it and see if the hash verifies correctly. But I need to dive into docterine mocking to get that to work. Any hints/tips are appreciated.

Reviewing should be trivial. However I prefer to have unit tests to make sure it keeps on working. But it should anyways get into 8.1! Hence the overlapping labels.

CC: @PVince81 @LukasReschke @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
@rullzer I guess you might be able to test this by calling the method to set a password hash, and the doing a SELECT directly on the DB to see if the hash matches what is expected.

**Comment by PVince81** [comment]
there is already a database available, not a mocked DB, so just use that :smile:

**Comment by LukasReschke** [comment]
That is a nasty one :+1: 

Regarding unit tests: No idea how we do that with the DB QB :(

**Comment by rullzer** [comment]
@PVince81 sure you are right. But mocking makes sure I'm testing the right stuff. Anyways. unit test added.

**Comment by PVince81** [comment]
Works :+1: (if you merge to master when testing, make sure to have https://github.com/owncloud/core/pull/15915 merged too)

**Pull request merged**
