### PR TITLE
Stable8.1 backport 17293

### PR DESCRIPTION
**Pull request by MorrisJobke**
Stable8.1 of #17293

Should be merged before 8.1.0

cc @jancborchardt @schiesbn @libasys @owncloud/designers

### CODE REVIEW

**Comment by Raydiation** [comment]
Can confirm that the backport works @jancborchardt :+1:

**Comment by jancborchardt** [comment]
Another review please – I can’t review cause they are my commits … @libasys would be cool if you can check it out.

**Comment by schiesbn** [comment]
Tested... works :+1:

**Comment by libasys** [comment]
tested ... works, also!

**Comment by jancborchardt** [comment]
Cool, thanks everyone! Sorry again for that mess, and thanks to @libasys & @Raydiation for spotting the issues.

**Pull request merged**
