### PR TITLE
[WIP] Experimenting with dark app navigation look

### PR DESCRIPTION
**Pull request by jancborchardt**
Please check it out @owncloud/designers @karlitschek @MorrisJobke @PVince81 
Current:
capture du 2015-08-25 15-52-38
Now:
capture du 2015-08-25 15-51-18

Alternative light, as in https://github.com/owncloud/core/pull/18514
capture du 2015-08-25 15-51-52

I’m curious to hear your thoughts on it before I say what I think about it. :)

### CODE REVIEW

**Comment by karlitschek** [comment]
nice! :+1:  i like :-)

**Comment by nickvergessen** [comment]
Should the icons be white instead of black?

**Comment by jancborchardt** [comment]
@nickvergessen as I wrote above:
> The only thing not done yet is the icons because I wanted to make a quick prototype before sinking more work into this.

Will follow up with those. I’d really like to hear some reviews from @owncloud/designers @MorrisJobke and others though.

**Comment by jancborchardt** [comment]
Another version of this, reducing the grey tones but keeping the brighter friendly background: https://github.com/owncloud/core/pull/18514

**Comment by MorrisJobke** [comment]
I'm unsure about this. I like that the grey is gone, but now it's too much dark color. :confused:

**Comment by karlitschek** [comment]
I like the dark one. If we can make the icons light and the font a bit lighter and maybe bigger.

**Comment by jancborchardt** [comment]
I honestly think it’s too dark and unfriendly, unlike the lighter feel of the current version or even better #18514. It makes everything seem boxed in, and the stark contrast between sidebar (which belongs to the app) and app-content doesn’t really bode well. It’s also this weird extension of the header again, exactly what we moved away from with the apps menu.

**Comment by jospoortvliet** [comment]
I personally think the blue sidebar is way too dark, the grey one we have is fine. Just my cents...

**Comment by jancborchardt** [comment]
Updated with the proper white icons, highlight styles and checking that it looks good in other core components. Please check again @nickvergessen @PVince81 @schiesbn

**Comment by MorrisJobke** [comment]
I still think this is a bit too dark :( I really like the current light version, because the sidebar is part of the app.

**Comment by schiesbn** [comment]
generally I like it, it let you focus more on the "real content". But I have the feeling that we have to many shades of blue now. Maybe it looks better if the sidebar and the header uses the same color?

**Comment by karlitschek** [comment]
we tried the same color before. this is then very blockish and monolithic. I like the different shades better.

**Comment by schiesbn** [comment]
While we are experimenting. I think one of the reason why I like it is that I was never a big friend of all the gray stuff. So a different experiment could be to make the sidebar really light with a white background and a different way to highlight the selected item and to separate the sidebar from the content? Just thinking...

**Comment by MorrisJobke** [comment]
> So a different experiment could be to make the sidebar really light with a white background and a different way to highlight the selected item and to separate the sidebar from the content? Just thinking...

Sounds also nice. Like the new sidebar design ;)

**Comment by jancborchardt** [comment]
Updated the screenshots in the original post, and please check out the pull request, click around and check if I missed anything. @karlitschek @nickvergessen @schiesbn @MorrisJobke @owncloud/designers

**Comment by jancborchardt** [comment]
More folks for reviewing cc @oparoz @Henni

**Comment by jancborchardt** [comment]
Especially make sure to test with other apps because we will need to adjust quite some things for this to work it seems. :\ cc @karlitschek 

Please review: @oparoz for Gallery, @libasys @georgehrke for Calendar/Contacts, @raimund-schluessler @Henni for Tasks, @Raydiation for News

**Comment by MorrisJobke** [comment]
@jancborchardt I guess we can close this, right?

**Pull request closed without merging**
