### PR TITLE
[stable10] fixes #33216 - lookup in group principal backend as well

### LINKED ISSUE #33216: Deleting Calendar Sharing
### Steps to reproduce
1. Create a Group
2. Create a Calendar
3. Share calendar to a group
4. Update Owncloud (you need to update the dav app as well)

### Expected behaviour
Calendar still be shared
```
MariaDB [ownCloud]> select * from oc_dav_shares;
+----+-------------------------------+----------+--------+------------+-----------+
| id | principaluri                  | type     | access | resourceid | publicuri |
+----+-------------------------------+----------+--------+------------+-----------+
|  2 | principals/users/name.surname | calendar |      2 |      12397 | NULL      |
|  6 | principals/groups/group.prueba     | calendar |      2 |      12398 | NULL      |
+----+-------------------------------+----------+--------+------------+-----------+
```

### Actual behaviour
Delete calendar sharing 
```
MariaDB [ownCloud]> select * from oc_dav_shares;
+----+-------------------------------+----------+--------+------------+-----------+
| id | principaluri                  | type     | access | resourceid | publicuri |
+----+-------------------------------+----------+--------+------------+-----------+
|  2 | principals/users/name.surname | calendar |      2 |      12397 | NULL      |
+----+-------------------------------+----------+--------+------------+-----------+
```

### Server configuration
**Operating system:** 
Debian 9.5
**Web server:**
Apache/2.4.25
**Database:**
mysql  Ver 15.1 Distrib 10.1.26-MariaDB
**PHP version:**
PHP 7.0.30-0+deb9u1 
**ownCloud version:** (see ownCloud admin page)
10.0.10
**Updated from an older ownCloud or fresh install:**
4.5
**Where did you install ownCloud from:**
Repo
**Signing status (ownCloud 9.0 and above):**
Disabled

**Log of update (second line is problem)**

```
2018-10-17T01:22:23+00:00 Repair step: Remove invalid calendar and addressbook shares
2018-10-17T01:22:23+00:00 Repair info:  ... for principal 'principals/groups/group.prueba'
2018-10-17T01:22:23+00:00 Repair info:  ... for principal 'principals/users/XXX YYYY ZZZZZ'
2018-10-17T01:22:23+00:00 Repair info:  ... for principal 'principals/users/AAA BBBB CCCCCCC DDDD'
2018-10-17T01:22:23+00:00 Repair info:  ... for principal 'principals/users/GGGGG HHHHH IIIIII'
2018-10-17T01:22:23+00:00 Updated <dav> to 0.4.0
```

**Function that causes the problem**

file:  https://github.com/owncloud/core/blob/b71cc1c68969d20c1f6cfacf553a4e4d34c03d1e/apps/dav/lib/Repair/RemoveInvalidShares.php#L81

**Quick Patch**
add new line 81  

```
73     public function run(IOutput $output) {
74         $query = $this->connection->getQueryBuilder();
75         $result = $query->selectDistinct('principaluri')
76             ->from('dav_shares')
77             ->execute();
78
79         while ($row = $result->fetch()) {
80             $principaluri = $row['principaluri'];
81             if (!strncmp($principaluri,"principals/groups",17)) continue;
82             $p = $this->principalBackend->getPrincipalByPath($principaluri);
83             if ($p === null) {
84                 $output->info(" ... for principal '$principaluri'");
85                 $this->deleteSharesForPrincipal($principaluri);
86             }
87         }
88
89         $result->closeCursor();
90     }
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport #33245

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
```
Parse error: ./apps/dav/tests/unit/Repair/RemoveInvalidSharesTest.php:49
    47| 	}
    48| 
  > 49| 	public function test(): void {
    50| 		$db = \OC::$server->getDatabaseConnection();
    51| 		/** @var Principal | \PHPUnit_Framework_MockObject_MockObject $principal */
Unexpected ':', expecting ';' or '{' in ./apps/dav/tests/unit/Repair/RemoveInvalidSharesTest.php on line 49
Makefile:215: recipe for target 'test-php-lint' failed
make: *** [test-php-lint] Error 1
```

**Comment by DeepDiver1975** [comment]
> Parse error: ./apps/dav/tests/unit/Repair/RemoveInvalidSharesTest.php:49

php 5.6/7.0 syntax adaptation necessary ....

**Pull request merged**
