### PR TITLE
escape filter in search

### PR DESCRIPTION
**Pull request by peterprochaska**
## Description
Escape the filter parameter in error message

## Motivation and Context
Make owncloud more secure

## How Has This Been Tested?
Inject HTML Code and the error message is HTML-Code free 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
hmmm okay :+1:

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by PVince81** [comment]
Backport or not critical enough ? @Peter-Prochaska @DeepDiver1975

**Comment by Peter-Prochaska** [comment]
backport ot 9.1 https://github.com/owncloud/core/pull/27903

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/27992

**Pull request merged**
