### PR TITLE
[9.0] Pass on the error message from the user manager to the UI

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of https://github.com/owncloud/core/pull/24526
Approval https://github.com/owncloud/core/pull/24526#issuecomment-218090889

@rullzer @MorrisJobke

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
See https://github.com/owncloud/core/pull/24526/files#r62654664

**Comment by rullzer** [comment]
@MorrisJobke #24526 is in with your blessing... mind to give this one another look?

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
