### PR TITLE
Handle (some) exceptions in the scanner

### PR DESCRIPTION
**Pull request by icewind1991**
Catch some exceptions in the scanner and continue scanning.

Also improves the exception throwing in the dav backend a bit.

cc @DeepDiver1975 @PVince81 @Xenopathic

### CODE REVIEW

**Comment by PVince81** [comment]
Makes sense.
How did you test it ?

**Comment by PVince81** [comment]
@icewind1991 there is a risk that unavailable storages will not be detected properly.
Some code paths might call scanFile() and the exception needs to be thrown all the way up ?

**Comment by karlitschek** [comment]
looks definitely good. Not tested :+1:

**Comment by DeepDiver1975** [comment]
looks like this breaks the dav tests ...

**Comment by PVince81** [comment]
@icewind1991 any update ?

**Comment by icewind1991** [comment]
rebased, let's see what jenkins thinks of it

**Comment by MorrisJobke** [comment]
We handle the exceptions during file scan in https://github.com/owncloud/core/pull/20789

**Comment by PVince81** [comment]
Risky stuff as stated here https://github.com/owncloud/core/pull/19128#issuecomment-141085462

If this doesn't provide a clear benefit I suggest closing.
As @MorrisJobke stated, we already catch the most important exceptions on another level.

**Comment by MorrisJobke** [comment]
Yes. No reason to fix stuff, that is not broken.

**Comment by PVince81** [comment]
Looks like this was supposed to fix cases like https://github.com/owncloud/core/issues/18829, reopening.

**Comment by PVince81** [comment]
Rebased and solved conflicts, needs retesting

**Comment by PVince81** [comment]
triage

**Pull request closed without merging**
