### PR TITLE
Backport stable8.1 #17255 #17526

### PR DESCRIPTION
**Pull request by blizzz**
Combined backport of https://github.com/owncloud/core/pull/17255 and https://github.com/owncloud/core/pull/17526.

Integration tests are succeeding.

### CODE REVIEW

**Comment by karlitschek** [comment]
works for me :+1:  :-)

**Comment by MorrisJobke** [comment]
cc @SergioBertolinSG

**Comment by MorrisJobke** [comment]
Tested and still works :+1:

**Comment by davitol** [comment]
:+1: works for me too

**Pull request merged**
