### PR TITLE
emit correct signal when disabling an app

### PR DESCRIPTION
**Pull request by butonic**
lets see if ci picks it up

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
Should backport ot 9.0

**Comment by PVince81** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1: but please consider giving credit where credit is due: https://github.com/nextcloud/server/pull/71

**Comment by PVince81** [comment]
@butonic please submit backport PR

CI did not pick it up because there are no tests for this piece...

**Pull request merged**
