### PR TITLE
Correct mistake in translations

### PR DESCRIPTION
**Pull request by settermjd**
## Description

There was a mistake in three translations across a number of translation files. These are:

- `Your Data directory is readable by other users`
- `Your Data directory  is invalid`
- `Your Data directory must be an absolute path`

"Your Data" should be "Your data" and there's an extra space between "directory" and "is" in the second UI text.

## Motivation and Context

I decided to change this after seeing the second one output in the console when I was trying to fix a local ownCloud build.

## How Has This Been Tested?

n/a

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Console UI message update

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by mmattel — COMMENTED** [review]
LGTM

**Review by mmattel — APPROVED** [review]

**Comment by PVince81** [comment]
@settermjd these must be changed on Transifex

**Comment by mmattel** [comment]
@PVince81, you are right, I have overseen that these are the translated files and not the sources...

@settermjd 
The source eg for: ``Your Data directory is readable by other users`` is in:
https://github.com/owncloud/core/lib/private/legacy/util.php#L975

To lower ``Data`` this file must be corrected, which is then automatically uploaded to Transifex and the basis to all translations. The other text issues are the same.

**Comment by DeepDiver1975** [comment]
Yes - please fix this in the php/js code - on transifex the translations will be adopted.

**Pull request closed without merging**
