### PR TITLE
Testing md5home

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Allow clearing default user backends in config.php.
Testing app provides test user backend for alternative homes.

## Related Issue
Alternative to https://github.com/owncloud/core/pull/26846 and https://github.com/owncloud/core/pull/26851

## Motivation and Context
Need tests for alternative getHome

## How Has This Been Tested?

1. Edit config.php and add:
```
'user_backends' => 
  array (
    'default' => false,   // this is the new setting that kills the default DB user backend
    0 => 
    array (
      'class' => '\\OCA\\Testing\\AlternativeHomeUserBackend',
      'arguments' => 
      array (
      ),
    ),
  ),
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@DeepDiver1975 as discussed
@SergioBertolinSG 

If approve, I'll add an automated test suite that uses this in https://github.com/owncloud/core/pull/26846

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
When editing config.php that affects all users?

**Comment by SergioBertolinSG** [comment]
Admin user account stops working with this set up.

This is my data folder after having admin, user1, user2 and user3 logged in at least once:

```
21232f297a57a5a743894a0e4a801fc3  7e58d63b60197ceb55a1c487989a3720  admin    files_external  owncloud.log
24c9e15e52afc47c225b757e7bee1f9d  92877af70a45fd6a2ed7fe81e1236b78  avatars  index.html
```

Admin user cannot upload files or access to his files.

**Comment by PVince81** [comment]
Admin user is not relevant for integration tests, at least not the filesystem ones. FS tests run as newly created users which would get the correct home.

If causing side effects I can add an exception for users called "admin" and return the normal home for that one.

**Comment by butonic** [comment]
ohhh nice!

**Comment by PVince81** [comment]
@butonic hold your horses, this is only for the testing app 😉 
But nice indeed.

**Comment by PVince81** [comment]
@SergioBertolinSG please retry, I excluded "admin" here https://github.com/owncloud/core/pull/26854/commits/79d1ed05e92b4e2d1de8a38610d8f539330e7e72

**Comment by PVince81** [comment]
All tests passed now, merge ?

**Comment by SergioBertolinSG** [comment]
Works fine 👍

**Comment by PVince81** [comment]
We need to backport this if we want to benefit from automated testing... Agreed ? @DeepDiver1975 @SergioBertolinSG

**Pull request merged**
