### PR TITLE
force log messages to break to alleviate horizontal scroll on Admin page

### PR DESCRIPTION
**Pull request by jancborchardt**
Makes it easier to read the log cause the messages will not be too wide, and the time will be visible as well. Fits the width of the viewport now.

Please review @owncloud/designers

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by MorrisJobke** [comment]
Doesn't work for loaded log entries ;)

**Comment by nickvergessen** [comment]
Seems to work now.

**Comment by MorrisJobke** [comment]
Works :+1:

**Pull request merged**
