### PR TITLE
Update phpseclib to version 0.3.9.

### LINKED ISSUE #12115: Update phpseclib to 0.3.9
AFAICS OC's only use of phpseclib is for SFTP external storage support. I eyeballed the phpseclib Net_SFTP for changes from 0.3.6 to 0.3.9 and didn't see anything that ought to break it. Upstream recently added a changelog - https://github.com/phpseclib/phpseclib/blob/master/CHANGELOG.md - and nothing leaps out at me there either.

I'm not sure of OC's rules/conventions for submitting PRs that bump 3rdparty deps so I thought I'd just submit an issue instead. Mostly it should just be a case of 'composer update phpseclib/*' in the 3rdparty repo, I guess.

### PR DESCRIPTION
**Pull request by bantu**
Fix #12115
Depends on https://github.com/owncloud/3rdparty/pull/155

Tested Webinterface:
- [x] Upload of single file to SFTP Server
- [x] Download of single file from SFTP Server
- [x] Moving single file from OC Server to SFTP Server
- [x] Deleting single file from SFTP Server
- [x] Permanently deleting single file
- [x] Deleting multiple files on SFTP Server

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Thanks a lot @bantu

**Comment by DeepDiver1975** [comment]
Okay - looking at the versions as of composer lock: we are a hell of out dated: https://www.versioneye.com/user/projects/54d1f76f3ca0840b190000c0#tab-dependencies

Hmm - let's move this change to 8.1 - we have to update them all ... better do this coordinated. THX

**Comment by PVince81** [comment]
Fails for the same errors as in master:
```
1) Test\Files\Storage\SFTP::testDirectories with data set #0 ('folder')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

2) Test\Files\Storage\SFTP::testDirectories with data set #1 (' folder')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

3) Test\Files\Storage\SFTP::testDirectories with data set #2 ('folder ')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

4) Test\Files\Storage\SFTP::testDirectories with data set #3 ('folder with space')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

5) Test\Files\Storage\SFTP::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:92

6) Test\Files\Storage\SFTP::testHashInFileName
Failed asserting that false matches expected 'data'.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:395

7) Test\Files\Storage\SFTP::testRenameOverWriteDirectory
rename must return true on success
Failed asserting that false is true.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:460
```

I guess this means :+1: ?

**Comment by th3fallen** [comment]
:+1:

**Comment by th3fallen** [comment]
pending merge of owncloud/3rdparty#155 this can be merged

**Comment by DeepDiver1975** [comment]
> pending merge of owncloud/3rdparty#155 this can be merged

just got merged - please update the submodule - thx

**Comment by MorrisJobke** [comment]
I updated the submodule.

**Comment by bantu** [comment]
Hmm. Apparently submodule update needs to be dropped from this PR now, as another PR already updated the submodule. This seems to be rather questionable work-flow wise, as this might result in breaks in the general case.

**Comment by bantu** [comment]
3rdparty in master already points to https://github.com/owncloud/3rdparty/tree/5142d69c5c467c651a7ef72ea1f09dcfb7ba25b5 which includes phpseclib 0.3.9.

**Comment by DeepDiver1975** [comment]
we can close this then - THX

**Comment by bantu** [comment]
This should be merged instead as it has a patch.

**Comment by DeepDiver1975** [comment]
> This should be merged instead as it has a patch.

I'm sorry

**Comment by DeepDiver1975** [comment]
Let's merge this now - I'll take care about testing this week in the scope of #14068

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
