### PR TITLE
Remove unused config parameters

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Remove config parameters:
``check_for_working_webdav``
``check_for_working_wellknown_setup``
``openssl`` 

## Motivation and Context
Remove stuff that is not used anywhere.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
``openssl`` was added in PR #4514 and seems to have been for servers on Windows, which are no longer supported.

I can't see any use of the other config parameters - maybe there is an app not in my locally cloned set of apps that uses these?

**Comment by PVince81** [comment]
Assuming you grepped the code and saw these aren't used ?

**Comment by phil-davis** [comment]
Yes, I have a lot of app repos also cloned locally and searched those. Nothing found.

Maybe somebody remembers these and where they used to be used?

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport ``stable10`` #30919 

AFAICT these are unused in ``stable10``

**Comment by phil-davis** [comment]
See #30929 for a (hopefully) improved attempt at this.

**Pull request merged**
