### PR TITLE
Add urlencode to username part of ftp and sftp links

### LINKED ISSUE #17796: FTP usernames should be URL-encoded
This is the return value of `$this->constructUrl($path)` when using the FTP external storage.
`ftp:\/\/username@szepe.net:secretpass@eu1.solid-hosting.net\/`
It should look like: `ftp:\/\/username%40szepe.net:secretpass@eu1.solid-hosting.net\/`

### PR DESCRIPTION
**Pull request by Senorsen**
I think this can fix #17796 , which is a junior issue.

### CODE REVIEW

**Comment by icewind1991** [comment]
Changes look good

Note that the ftp implementation is scheduled to be replaced for 9.1 (#23101) I don't know if the new implementation has the same issue

**Comment by Senorsen** [comment]
My contribution is MIT licensed.

**Comment by Senorsen** [comment]
@icewind1991 
Oh it seems like the new implementation does not contains `constructUrl()` function, so I guess that it does not have the same issue.

**Comment by icewind1991** [comment]
It uses flysystem for most of the FTP logic, not sure if they handle it, you can try grabbing the app from http://github.com/icewind1991/files_external_ftp and see if that has the same issue of you want

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> It uses flysystem for most of the FTP logic, not sure if they handle it, you can try grabbing the app from http://github.com/icewind1991/files_external_ftp and see if that has the same issue of you want

best would be to test #23101

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
