### PR TITLE
[WIP] Stable file ids when moving between storages

### PR DESCRIPTION
**Pull request by PVince81**
In the spirit of "test first" this PR contains failing tests to make file ids stable.

Ref https://github.com/owncloud/core/issues/13310

@DeepDiver1975 @icewind1991 FYI

### CODE REVIEW

**Comment by MorrisJobke** [comment]
You rock!

**Comment by MorrisJobke** [comment]
8.0 o.O

**Comment by PVince81** [comment]
It sounds quite tricky and is likely to break stuff, so very likely to be 8.1.

Writing down some ideas here:

Currently when moving a file between storages, it's a "rename" operation (`$view->rename()`)
That operation detects that it's cross-storage, so for a folder it will call `$view->copy()` instead, and if that succeeded it will delete the source (https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L504).
If it's a file, it will do two fopens and stream copy the file to the target, then delete the source.

In the case of copy(), the tricky part is making sure that not only the copied folder keeps its file id but also all children.

Approach 1): prevent any file cache update until completion of the operation. At the end, find all source entries for the source files, then update the "storage" column to be the new storage, update "path", "path_hash" and "parent" to match the new location.
If the change isn't atomic, there will be a small time window where the cache is partially update, could cause side effects if race conditions. Maybe the old entries could be "disabled" somehow (if we had a "invisible" flag) until they are all updated, and then reenabled.

Approach 2): same as approach 1), but the files + cache are updated one by one instead of all at the end of the copy. This means we'll need a special implementation of "copy" which is specific to this case (separate from the read `$view->copy()`)

Approach 3): gather fileid of cache entries that match the file to be copied, then delete them. Perform the copy and update the new cache entries (that appears because of the copy) and change their fileid to the old ones.
Drawback is that there is a short time window where these files might become visible until their file ids get changed.

So far I prefer approach 2)

**Comment by PVince81** [comment]
I forgot about this branch...

Merged it into this PR that has a partial fix: https://github.com/owncloud/core/pull/13385

**Pull request closed without merging**
