### PR TITLE
Specify PHP 5.4 as version for scrutinizer

### PR DESCRIPTION
**Pull request by LukasReschke**
Let's see if this helps for cases such as https://github.com/owncloud/core/issues/19793

### CODE REVIEW

**Comment by LukasReschke** [comment]
@DeepDiver1975 Oh mighty master of CI systems. Your call on that one :speak_no_evil:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1: 

Btw is scrutinizer still reporting back? or is the backlog just too big

**Comment by LukasReschke** [comment]
> Btw is scrutinizer still reporting back? or is the backlog just too big

I _think_ it only works on master and not on PRs anymore?

@DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
I guess because of this change scruinizer is trying to execute the unit tests on their system - which for sure breaks .... already talking to their support

**Pull request merged**
