### PR TITLE
[Stable10] Change to re-create masterkyes

### PR DESCRIPTION
**Pull request by sharidas**
This change brings a new command to re-create
masterkey

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change will help users to re-create a new masterkey.

## Related Issue

https://github.com/owncloud/core/issues/21434

## Motivation and Context

This is a handy command for admins and can be useful if the masterkey is compromised. 

## How Has This Been Tested?

Most of the testing is described in https://github.com/owncloud/encryption/pull/12 and https://github.com/owncloud/core/issues/21434#issuecomment-330254310

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
@sharidas did you do a quick retest with the backport ?

**Comment by sharidas** [comment]
@PVince81 Tested with
- [x] Multiple users
- [x] External storage SFTP
- [x] By creating multiple versions of file

**Review by PVince81 — APPROVED** [review]
:+1: if CI passes

**Comment by PVince81** [comment]
What ?!

```
21:03:29 PHP Parse error:  syntax error, unexpected 'will' (T_STRING) in /var/lib/jenkins/workspace/owncloud-core_core_PR-29260-XM7DRL4RZ2GRMAPQBTEHTN5LJOM5NEDARZUSX6MZZXIPJACWYGBQ/apps/encryption/tests/KeyManagerTest.php on line 78
```

**Review by PVince81 — CHANGES_REQUESTED** [review]
please fix test

**Comment by sharidas** [comment]
Fixed. Waiting for the tests to start and then pass.

**Comment by PVince81** [comment]
Please rebase to trigger Jenkins build

**Review by PVince81 — APPROVED** [review]

**Pull request merged**
