### PR TITLE
Allow non admins to list their own mounts

### PR DESCRIPTION
**Pull request by icewind1991**
Not sure why we only found this now

cc @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
cc @LukasReschke

**Comment by PVince81** [comment]
:+1: works

**Comment by PVince81** [comment]
Needs seconds reviewer @Xenopathic @jmaciasportela @LukasReschke

**Comment by PVince81** [comment]
To test:

1. Allow personal mounts
1. Create non-priviledged user "user1"
1. Login as "user1"
1. Go to personal page
1. Create ext storage config
1. Refresh page
=> this fix prevents the 403 error on the "userstorages" call

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
