### PR TITLE
CollaboraOnline#6546 enable automatic color in default paragraph style

### PR DESCRIPTION
**Pull request by timar**
use the xml token "use-window-font-color" to toggle auto color on.

https://github.com/CollaboraOnline/online/issues/6546

### CODE REVIEW

**Comment by phil-davis** [comment]
@pako81 what do you know about this?
Approve and merge?
What should happen about a changelog entry?

**Review by jvillafanez — APPROVED** [review]
Checked

**Comment by jvillafanez** [comment]
Do we need a changelog entry for this? It seems such a tiny change that I wouldn't bother, and I don't think it's important enough for people to be notified about this.

**Comment by phil-davis** [comment]
@pako81 please merge if happy.

**Review by pako81 — APPROVED** [review]

**Pull request merged**
