### PR TITLE
Add check for activated local memcache

### LINKED ISSUE #14956: Check for activated local memcache in administrative Configuration Checks
A check for `memcache.local` should be added to the administrative configuration checks.

### PR DESCRIPTION
**Pull request by LukasReschke**
Also used the opportunity to refactor it into an AppFramework controller so that we can unit test it.

Fixes https://github.com/owncloud/core/issues/14956

### CODE REVIEW

**Comment by Xenopathic** [comment]
```
PHP Fatal error:  Call to undefined method OC_Util::isInternetConnectionEnabled() in /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/tests/lib/util.php on line 134
...
08:34:41 PHP  12. PHPUnit_Framework_TestCase->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:766
08:34:41 PHP  13. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:881
08:34:41 PHP  14. Test_Util->testIsInternetConnectionEnabled() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:881
```

**Comment by LukasReschke** [comment]
Fixed :) THX… :see_no_evil:

**Comment by LukasReschke** [comment]
Or better: It would be fixed if pushing to GitHub would work properly atm…

**Comment by Xenopathic** [comment]
@LukasReschke Just keep Ctrl+C'ing and retrying the push. It'll work some of the time.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by Xenopathic** [comment]
Tested :+1:

**Pull request merged**
