### PR TITLE
Don't rely on the notify socket but on the service responding

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Let's try to fight this one ....

```
05:47:08 Digest: sha256:ec4c5c087a1802678ae90043687ea616a2465cad399c1d23114c8b47e03737f8
05:47:08 Status: Image is up to date for xenopathic/ceph-keystone:latest
05:47:09 xenopathic/ceph-keystone container: ac672de348f3ece4391d772b2223e60e955cd4846cf45d2874ed6eb3a087ddff
05:47:09 Waiting for ceph initialization
05:47:34 Waiting another 15 seconds
05:47:49 PHPUnit 4.8.24 by Sebastian Bergmann and contributors.
05:47:49 
05:47:49 Runtime:   PHP 5.6.20-0+deb8u1 with Xdebug 2.2.5
05:47:49 Configuration: /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/tests/phpunit-autotest-external.xml
05:47:49 
05:47:55 SEEEEE........................................................... 65 / 80 ( 81%)
05:54:34 ...............
05:55:39 
05:55:39 Time: 7.83 minutes, Memory: 64.00Mb
05:55:39 
05:55:39 There were 5 errors:
05:55:39 
05:55:39 1) OCA\Files_External\Tests\Storage\SwiftTest::testRoot
05:55:39 Guzzle\Http\Exception\CurlException: [curl] 7: Failed to connect to 172.17.0.125 port 80: Connection refused [url] http://172.17.0.125/swift/v1/swift
05:55:39 
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:338
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:279
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:244
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:227
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:211
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:105
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/guzzle/http/Guzzle/Http/Curl/CurlMultiProxy.php:91
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/guzzle/http/Guzzle/Http/Client.php:282
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/guzzle/http/Guzzle/Http/Message/Request.php:198
05:55:39 /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/3rdparty/rackspace/php-opencloud/lib/OpenCloud/ObjectStore
```

### CODE REVIEW

**Comment by Xenopathic** [comment]
This is effectively reverting the change that introduced the notify socket in the first place, which solved the problems with race conditions back then. This approach is known to cause issues, so :-1:

I'm talking about #22588 by the way

**Comment by DeepDiver1975** [comment]
Don't touch my PRs please! :angry:

**Comment by DeepDiver1975** [comment]
> This is effectively reverting the change that introduced the notify socket in the first place, which solved the problems with race conditions back then.

so maybe we need a combination of both ... let's see ...

**Comment by Xenopathic** [comment]
Sorry, I misclicked :cry:

**Comment by PVince81** [comment]
@DeepDiver1975 any progress on beating this into shape ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 any progress on beating this into shape ?

will take care these days as soon as I find the time

**Comment by PVince81** [comment]
Here, take these :watch: :clock10: :clock1130:

**Comment by PVince81** [comment]
@DeepDiver1975 oh look, it's green. It's a miracle !

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
