### PR TITLE
[tests-only] skip old chunking tests on ocis

### PR DESCRIPTION
**Pull request by dpakach**
## Description

[tests-only] skip old chunking tests on ocis
https://github.com/owncloud/ocis/issues/1343#issuecomment-872196526

## Related Issue

- Related https://github.com/owncloud/ocis/issues/2160

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31725/131/1

**Review by Talank — COMMENTED** [review]
LGTM

**Comment by phil-davis** [comment]
@dpakach in PR #39051 I skipped the new chunking tests on OCIS.

I thought that the "old" chunking is supposed to be the chunking that is being supported on OCIS.

Now I am confused. What chunking is supposed to be implemented for OCIS?

**Comment by dpakach** [comment]
@phil-davis as far as I know, ocis doesn't support chunking as it uses TUS except for EOS storage. But since we dont run tests with EOS, I suppose we can remove this.
https://github.com/owncloud/ocis/issues/1343#issuecomment-872196526

**Comment by phil-davis** [comment]
There has been discussion in the OCIS chat. I will clarify at the standup today.

**Comment by dpakach** [comment]
not required since ocis will support chunking v1

**Pull request closed without merging**
