### PR TITLE
Update the cache when renaming even if we dont emit hooks

### PR DESCRIPTION
**Pull request by icewind1991**
Prevent cache issues when using a non-default view (such as when using the node api)

cc @PVince81 @DeepDiver1975 @Raydiation

### CODE REVIEW

**Comment by Raydiation** [comment]
Can confirm that this is working :+1:

**Comment by DeepDiver1975** [comment]
unit test to cover this behavior?

**Comment by icewind1991** [comment]
Now with unit test

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
```	Testergebnis (58 fehlgeschlagene Tests / +58)

    OCA\Files_Encryption\Tests\Hooks.testRenameHook
    OCA\Files_Encryption\Tests\Hooks.testCopyHook
    OCA\Files_Encryption\Tests\Util.testGetFileSize
    OCA\Files_Encryption\Tests\Share::testMoveFileToFolder.testMoveFileToFolder with data set #0
    OCA\Files_Encryption\Tests\Share::testMoveFileToFolder.testMoveFileToFolder with data set #1
    OCA\Files_Encryption\Tests\Share.testDownloadVersions
    OCA\Files_Encryption\Tests\Share.testReShareFile
    OCA\Files_Encryption\Tests\Share.testShareFolder
    OCA\Files_Encryption\Tests\Share.testReShareFolder
    OCA\Files_Encryption\Tests\Share.testShareFileWithGroup
    OCA\Files_Encryption\Tests\Share.testRename
    OCA\Files_Encryption\Tests\Share.testRenameGroupShare
    OCA\Files_Encryption\Tests\Share.testMoveFolder
    Test_Files_Sharing_Api.testEnfoceLinkPassword
    Test_Files_Sharing_Api.testSharePermissions
    Test_Files_Sharing_Api.testGetAllShares
    Test_Files_Sharing_Api.testGetShareFromSourceWithReshares
    Test_Files_Sharing_Api.testGetShareFromId
    Test_Files_Sharing_Api.testGetShareFromFolder
    Test_Files_Sharing_Api.testGetShareFromFolderReshares
    Test_Files_Sharing_Api.testGetShareFromSubFolderReShares
    Test_Files_Sharing_Api.testGetShareFromFolderReReShares
    Test_Files_Sharing_Api.testGetShareFromFileReReShares
    Test_Files_Sharing_Api.testGetShareFromUnknownId
    Test_Files_Sharing_Api.testUpdateShare
    Test_Files_Sharing_Api.testUpdateShareUpload
    Test_Files_Sharing_Api.testUpdateShareExpireDate
    Test_Files_Sharing_Api.testDeleteShare
    Test_Files_Sharing_Api.testShareFolderWithAMountPoint
    Test_Files_Sharing_Api.testShareStorageMountPoint
    Test_Files_Sharing_Api.testDefaultExpireDate
    Test_Files_Sharing_Mount::testStripUserFilesPath.testStripUserFilesPath with data set #0
    Test_Files_Sharing_Mount::testStripUserFilesPath.testStripUserFilesPath with data set #1
    Test_Files_Sharing_Mount::testStripUserFilesPath.testStripUserFilesPath with data set #2
    Test_Files_Sharing_Mount::testStripUserFilesPath.testStripUserFilesPath with data set #3
    Test_Files_Sharing_Mount::testStripUserFilesPath.testStripUserFilesPath with data set #4
    Test_Files_Sharing_Mount::testStripUserFilesPath.testStripUserFilesPath with data set #5
    Test_Files_Sharing_Mount.testDeleteParentOfMountPoint
    Test_Files_Sharing_Mount.testMoveSharedFile
    Test_Files_Sharing::testFileSharePermissions.testFileSharePermissions with data set #0
    Test_Files_Sharing::testFileSharePermissions.testFileSharePermissions with data set #1
    Test_Files_Sharing::testFileSharePermissions.testFileSharePermissions with data set #2
    Test_Files_Sharing::testFileSharePermissions.testFileSharePermissions with data set #3
    Test_Files_Sharing::testFileSharePermissions.testFileSharePermissions with data set #4
    Test_Files_Sharing.testGroupingOfShares
    Test_Files_Sharing.testShareAndUnshareFromSelf
    Test_Files_Sharing.testShareWithDifferentShareFolder
    Test_Files_Sharing.testShareWithGroupUniqueName
    OCA\Files_Sharing\Controllers\ShareControllerTest.testShowShare
    Test_Files_Sharing_Helper.testSetGetShareFolder
    Test_Files_Sharing_Storage.testParentOfMountPointIsGone
    Test_Files_Sharing_Storage.testRenamePartFile
    Test_Files_Sharing_Storage.testFilesize
    Test_Files_Sharing_Storage.testGetPermissions
    Test_Files_Sharing_Storage.testMountSharesOtherUser
    Test_Trashbin.testExpireOldFilesShared
    Test_Files_Versioning.testRenameInSharedFolder
    Test_Files_Versioning.testRenameSharedFile
```

**Comment by icewind1991** [comment]
Tests pass locally...

**Comment by MorrisJobke** [comment]
> Tests pass locally...

That doesn't let them pass on Jenkins ;)

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
> Integrity constraint violation: 19 UNIQUE constraint failed: oc_filecache.storage, oc_filecache.path_hash

Seems like we not update the path to something that does already exist.
Maybe a previous test did not clean up the entry correctly

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
@icewind1991 instead of keeping jenkins busy with retesting
just push your changes to a second branch and create a new PR

**Comment by icewind1991** [comment]
@DeepDiver1975 @PVince81 can this be merged?

**Comment by PVince81** [comment]
Assuming that nothing changed in the main code since @Raydiation's test.
The code looks good :+1:

**Pull request merged**
