### PR TITLE
Hide revert button when no permission to revert

### PR DESCRIPTION
**Pull request by PVince81**
Please review @icewind1991 @georgehrke @VicDeo @DeepDiver1975 

We should backport this down to 8.0.
CC @DeepDiver1975 @dragotin

### CODE REVIEW

**Comment by georgehrke** [comment]
How to test this?

I can still revert read-only shared files.

**Comment by PVince81** [comment]
@georgehrke 

1. Setup OC
1. As admin, create a user "user1"
1. Create a folder "test"
1. Create a file "test/test.txt", edit several times to create versions
1. Share the folder "test" with "user1" with full permissions
1. In a separate browser, login as "user1"
1. Open the folder "test"
1. Open the versions panel for "test" and see that there are multiple versions
1. Back to admin's browser
1. Remove edit permissions on "test"
1. Back to user1's browser
1. Click on of the "Revert" icons to revert a version

I tried again with both folder shares and file shares and it works correctly: cannot revert.
If you disabled the "can edit" permission, you might need to click outside the checkbox for the ajax request to go through when adjusting permissions, just in case.

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by VicDeo** [comment]
@PVince81 tested, works :+1:

**Comment by PVince81** [comment]
@jvillafanez @VicDeo mind helping to review the above backports as well ?

**Pull request merged**
