### PR TITLE
Move parallel merged auth tests to PSR-4

### PR DESCRIPTION
**Pull request by nickvergessen**
@PVince81 @rullzer @ChristophWurst

### CODE REVIEW

**Comment by ChristophWurst** [comment]
unrelated?
``
06:08:45 There were 2 failures:
06:08:45 
06:08:45 1) OCA\UpdateNotification\Tests\Controller\AdminControllerTest::testDisplayPanelWithUpdate
06:08:45 OCP\IConfig::getAppValue('updatenotification', 'notify_groups', '["admin"]') was not expected to be called more than once.
06:08:45 
06:08:45 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/updatenotification/lib/Controller/AdminController.php:104
06:08:45 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/updatenotification/tests/Controller/AdminControllerTest.php:121
06:08:45 
06:08:45 2) OCA\UpdateNotification\Tests\Controller\AdminControllerTest::testDisplayPanelWithoutUpdate
06:08:45 OCP\IConfig::getAppValue('updatenotification', 'notify_groups', '["admin"]') was not expected to be called more than once.
06:08:45 
06:08:45 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/updatenotification/lib/Controller/AdminController.php:104
06:08:45 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/updatenotification/tests/Controller/AdminControllerTest.php:162
``

**Comment by nickvergessen** [comment]
Yeah a second issue of parallel merging:
https://github.com/owncloud/core/pull/24838

**Comment by ChristophWurst** [comment]
okay, then :+1: ;-)

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
