### PR TITLE
Add X-Download-Options and X-Permitted-Cross-Domain-Policies

### PR DESCRIPTION
**Pull request by LukasReschke**
Two small security hardenings for our IE users and those with Adobe products. Aligns it more with https://github.com/twitter/secureheaders#secureheaders---

X-Download-Options: https://msdn.microsoft.com/en-us/library/jj542450(v=vs.85).aspx
X-Permitted-Cross-Domain-Policies: https://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html

### CODE REVIEW

**Comment by rullzer** [comment]
ownCloud did not explode ;)
headers show up :) :+1:

**Comment by MorrisJobke** [comment]
Headers doesn't show up - neither in Chrome nor in Safari - also the security checks shows that it is not included in the response.

**Comment by LukasReschke** [comment]
> Headers doesn't show up - neither in Chrome nor in Safari - also the security checks shows that it is not included in the response.

… including .htaccess in the pull helps. Fixed, THX :speak_no_evil:

**Comment by MorrisJobke** [comment]
Tested and works now :+1: 

(tested with apache)

**Comment by RealRancor** [comment]
Documentation? :see_no_evil:

**Pull request merged**
