### PR TITLE
[stable8.2] 3rdparty bump for full upgrade of sabre/dav-2.1.7

### PR DESCRIPTION
**Pull request by rullzer**
Requires: https://github.com/owncloud/3rdparty/pull/208

Backport of https://github.com/owncloud/core/pull/19987 for https://github.com/owncloud/3rdparty/pull/189 (fix calendar syncing on jolla phones).

Note https://github.com/owncloud/core/pull/19987 is not merged yet. Because we can't verify it will solve the issue since we moved master over to the new DAV stuff already.

@karlitschek please approve
@DeepDiver1975 FYI

### CODE REVIEW

**Comment by karlitschek** [comment]
do we have full testing for this change? @DeepDiver1975  what is your opinion?

**Comment by DeepDiver1975** [comment]
> do we have full testing for this change?

not yet - needs to be done these days.

**Comment by rullzer** [comment]
@nickvergessen could you also run smashbox against this PR?

**Comment by rullzer** [comment]
litmus passes for me

**Comment by nickvergessen** [comment]
Smashing :hourglass_flowing_sand:

**Comment by nickvergessen** [comment]
:white_check_mark:

**Comment by rullzer** [comment]
@DeepDiver1975 is this enough testing or do you have more in mind? I prefer to get this is rather sooner than later so that if it breaks something in 8.2.1 we hopefully find out early.

**Comment by DeepDiver1975** [comment]
@karlitschek change is not breaking sync - ready to pul in for 8.2.1 from my pov

**Comment by karlitschek** [comment]
agreed. thanks :+1:

**Comment by DeepDiver1975** [comment]
@rullzer upstream is merged - mind updating the submodule? THX

**Comment by rullzer** [comment]
@DeepDiver1975 done

**Pull request merged**
