### PR TITLE
Unskip tests for issue 29599

### PR DESCRIPTION
**Pull request by phil-davis**
since it should be fixed by "Update sabre/dav to 3.3.0-alpha1"

~~Just testing here to see if the tests pass. Then I can refactor them into the relevant scenario outlines... and put the final/proper commit in with PR #31644~~

Related issue #29599

### CODE REVIEW

**Comment by phil-davis** [comment]
The unskipped tests are passing, which is good.

**Comment by phil-davis** [comment]
This can sit here until the parent PR moves forward.

**Comment by phil-davis** [comment]
Rebased underlying PR which still has the failing test - see comment https://github.com/owncloud/core/pull/31644#issuecomment-394743022

That is the only fail here. So the unskipped tests are passing - good.

**Comment by individual-it** [comment]
that should be fixed by now @phil-davis can you rebase?

**Comment by phil-davis** [comment]
Rebased. This should pass against current master now. Let's see.

**Comment by phil-davis** [comment]
@paurakhsharma @individual-it this is ready for review

**Review by paurakhsharma — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport ``stable10`` #33402

**Comment by phil-davis** [comment]
@DeepDiver1975 codecov is not coming, I am tired of rebasing this to make CI cooperate.
Please review and force merge.

**Pull request merged**
