### PR TITLE
Lock the mountpoint while removing

### LINKED ISSUE #17144: removeMount should lock
@icewind1991 looks like "$view->removeMount()" doesn't lock.

We should exclusive-lock the mount point path (not the storage root) to avoid concurrent processes to access that path during the umount (in case sharing takes a while...)

Requires https://github.com/owncloud/core/pull/17070 to be merged first for the extra argument.

The same should be done for adding mount points (when sharing, etc)

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #17144 

@PVince81 @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
- [x] TEST: unshare from self with regular share
- [x] TEST: unshare from self with fed share
- [x] TEST: unmount system-wide ext storage
- [x] TEST: unmount personal ext storage

Works :+1:

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
@karlitschek backport to stable9 ?

**Comment by karlitschek** [comment]
please backport

**Comment by DeepDiver1975** [comment]
@nickvergessen @PVince81 @icewind1991 backport pr please - THX

**Pull request merged**
