### PR TITLE
Use owner when expiring versions, not the logged in user

### LINKED ISSUE #16334: Cannot overwrite file through s2s with versions enabled
### Steps to reproduce
1. Setup two ownCloud instances OC A and OC B
2. Login in OC A
3. Share a folder "test" with link, allow editing
4. Mount the folder "test" in OC B
5. Upload a file "test/test.txt"
6. Upload another version of the file as "test/test.txt", overwrite the existing one
7. Go to OC A again
8. Check if a version was created

### Expected result
File is overwritten, a version is created.

### Actual result
File is not overwritten, no version created.
And this in the log of OC A:
```
{"reqId":"1eS3XJoKrGck9jpGE4Kf","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getUID() on null at \/srv\/www\/htdocs\/owncloud\/apps\/files_versions\/lib\/storage.php#543","level":3,"time":"2015-05-13T16:08:50+00:00","method":"PUT","url":"\/owncloud\/public.php\/webdav\/testx.txt"}
```

This is because we try to get the user from the session (classic issue) but as we're connecting to public webdav, there is no user.

We should use the file owner when doing version expiration, not the accessing user.

### Versions
Does NOT occur on master because it is hidden by another bug that prevents versions creation.
It WILL appear on master after https://github.com/owncloud/core/pull/16292 is merged.

Not sure yet whether this is a regression, need to test on stable8.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/16334
- [x] fix the issue
- [x] add unit test that makes sure that the job is schedules with the owner, not the logged in user

FYI @icewind1991

### CODE REVIEW

**Comment by karlitschek** [comment]
good catch :+1:

**Comment by PVince81** [comment]
I have added a unit test that fails on master and works on this branch (with anonymous mode).

I also had to fix TestCase's logout which did not properly log out the user.

Please review @nickvergessen @icewind1991 @MorrisJobke @schiesbn

**Comment by icewind1991** [comment]
Looks good :+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
Thanks.

No backport needed, this is only for 8.1 (with the introduction of scheduleExpire)

**Pull request merged**
