### PR TITLE
Only clean up if migration finished succesfully

### PR DESCRIPTION
**Pull request by schiessle**
- Move the final clean up from the destructor to a separate method. If the migration fails it can happen that the destructor gets called to early. This way we make sure that we really clean up the remaining keys and config settings only at the end of the migration process.
- only create new key pair if both keys, private and public, are missing

Fixes issues like described here https://github.com/owncloud/core/issues/16928

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by blizzz** [comment]
@schiesbn when testing, should i apply https://github.com/owncloud/core/pull/17473 and https://github.com/owncloud/core/pull/17474 as well or is it supposed to work by itself?

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by schiesbn** [comment]
@blizzz 

> when testing, should i apply #17473 and #17474 as well or is it supposed to work by itself?

You can do two things:
 
First:
- run migration script with no patches applied (will fail because of the trashbin issue)
- re-run the migration with #17474 (now it will fail because if the database)
- re-run migration with #17473 (now migration will pass)
- login and try to read one of the encrypted files -> fails

Second run
- apply only this patch and run migration (will fail because of the trashbin issue)
- re-run the migration with #17474 (now it will fail because if the database)
- re-run migration with #17473 (now migration will pass)
- login and try to read one of the encrypted files -> should work now because of this patch

**Comment by blizzz** [comment]
What happend with First it confirmed already on IRC (FYI to others).

Will check with what was described for Second.

**Comment by blizzz** [comment]
@schiesbn works as advertised! Missing understanding of the encryption work flow, but as far as i can tell the code looks good, too :+1:

**Comment by MorrisJobke** [comment]
@schiesbn This was in the milestone for 8.1.1 but the PR was against master. Please open a backport PR.

@karlitschek Is this okay to backport?

**Comment by DeepDiver1975** [comment]
I'll take care of th backport

**Comment by DeepDiver1975** [comment]
> I'll take care of th backport

https://github.com/owncloud/core/pull/17678

**Comment by karlitschek** [comment]
great. backport is fine :+1:

**Pull request merged**
