### PR TITLE
Make external shares work with imported self signed certificates

### PR DESCRIPTION
**Pull request by icewind1991**
This moves the logic for managing trusted certificates from files_external to core, note that the certs are still stored in the files_external folder for backwards compatibilty, this is transparent for any app using the api.

To test:
- try adding a remote share from a server with a self-signed certificate, this should fail
- import the self-signed cert trough settings->personal
- try adding the remote share again, now it should work

Next step is making a nice gui for trusting the certificate when trying to add an external share from an untrusted cert

cc @schiesbn @PVince81 @simsasaile

### CODE REVIEW

**Comment by godfuture** [comment]
Is it somehow possible to completely turn off certificate verification for s2s? I have imported the self signed cert of the source server, but external storage connection is not established anyway:
```
[CURL] Error while making request: SSL certificate problem: unable to get local issuer certificate (error code: 60) 
```
problem_with_ssc_s2s_oc

Source server: oc 7.0.4, iis 7.5 win 7 x64, php 5.5.15
Target server: oc 8.0.0, apache2, ubuntu 14.10, php 5.5.12

**Comment by DeepDiver1975** [comment]
@LukasReschke anything we can do about this? THX

**Comment by DeepDiver1975** [comment]
@godfuture Can I ask you to open a new issue? THX

**Comment by LukasReschke** [comment]
Can't help without a copy of the certificate ;)

**Comment by godfuture** [comment]
@DeepDiver1975 
Sure, https://github.com/owncloud/core/issues/14747.
@LukasReschke 
Have sent you an email with the cert attached. Hope this is okay!

**Pull request merged**
