### PR TITLE
Share with group membership only

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Add an option to allow user to share only with the groups they belong to. If a user isn't a member of a group, that group won't appear as an option to share with it

## Related Issue
https://github.com/owncloud/core/issues/29075

## Motivation and Context
Users can share with any group. This option restricts that behaviour in a similar way the "share with users in their groups" option does.

## How Has This Been Tested?
Tested quickly with the sharing dialog. Other than that, consider this PR as untested for now. New unittests will be added soon.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jvillafanez** [comment]
@phil-davis @individual-it could you check if the failing test is related with this PR's changes? I'm not sure if it's "just" a random failure or if it's something that needs to be fixed.

**Comment by phil-davis** [comment]
@jvillafanez I scanned through your code diffs and there is nothing touching the front-end that should make the test fail like it did (cannot even find the "share with" element on the page). So I restarted the job and we will see.

**Comment by PVince81** [comment]
@jvillafanez can you also add integration tests ? Feel free to ask @SergioBertolinSG for some assistance.

**Comment by jvillafanez** [comment]
I'll check what we can add easily during today and tomorrow.

**Comment by felixboehm** [comment]
Need an assignment here, who continues work on this?

**Comment by PVince81** [comment]
Assigned to @jvillafanez

**Comment by jvillafanez** [comment]
I've found a problem with the share API (probably known) that affects to all the sharing tests. The problem is that the response of the sharing API is different depending on the number of results it needs to return.

For only one group available in the results:
```
Array
(
    [exact] => Array
        (
            [users] => Array
                (
                )

            [groups] => Array
                (
                )

            [remotes] => Array
                (
                )

        )

    [users] => Array
        (
            [element] => Array
                (
                    [label] => Sharee1
                    [value] => Array
                        (
                            [shareType] => 0
                            [shareWith] => Sharee1
                        )

                )

        )

    [groups] => Array
        (
            [element] => Array
                (
                    [label] => ShareeGroup
                    [value] => Array
                        (
                            [shareType] => 1
                            [shareWith] => ShareeGroup
                        )

                )

        )

    [remotes] => Array
        (
        )

)
```
If there are several results:
```
Array
(
    [exact] => Array
        (
            [users] => Array
                (
                )

            [groups] => Array
                (
                )

            [remotes] => Array
                (
                )

        )

    [users] => Array
        (
            [element] => Array
                (
                    [label] => Sharee1
                    [value] => Array
                        (
                            [shareType] => 0
                            [shareWith] => Sharee1
                        )

                )

        )

    [groups] => Array
        (
            [element] => Array
                (
                    [0] => Array
                        (
                            [label] => ShareeGroup
                            [value] => Array
                                (
                                    [shareType] => 1
                                    [shareWith] => ShareeGroup
                                )

                        )

                    [1] => Array
                        (
                            [label] => ShareeGroup2
                            [value] => Array
                                (
                                    [shareType] => 1
                                    [shareWith] => ShareeGroup2
                                )

                        )

                )

        )

    [remotes] => Array
        (
        )

)
```
Note that if there is only one element available, that element is returned under the "element" key, but if there are several elements, the "element" key returns an array of elements. This will likely happen with the users, although I haven't checked.

This problem affects the new tests because we need at least 2 groups. In order to do so, we'll need to patch the underlying test code to accept both possibilities so the parsing is properly done (this will error prone since we can't distinguish both options in a clear way, checking if the key is an integer is ugly but there isn't any other easy way).

The best option would be to fix the problem in the sharing API, but that's out of the scope of this PR (it will also need to fix the tests).

**Comment by jvillafanez** [comment]
@SergioBertolinSG could you take over for the integration tests? Note my last comment.

**Comment by phil-davis** [comment]
And (I think) @individual-it put his hand up to add some UI tests for this. There are already UI tests of this sharing area, so it should be just a matter of setting the new system option and then testing that the sharing dropdown now contains just the expected items.

**Comment by SergioBertolinSG** [comment]
@jvillafanez I can take care after finishing the pending tasks I have (which are several). Is that ok? Otherwise you should continue.

**Comment by jvillafanez** [comment]
Waiting for automatic testing.... other than that, this should be ready

**Review by SergioBertolinSG — APPROVED** [review]
:+1: for the behat tests

**Comment by PVince81** [comment]
@jvillafanez seems to work fine.

One thing that bothers me is that the behavior will change on update.

To recreate the old behavior, one needs to check both checkboxes.

We should write a migration to automatically tick the second checkbox if the first one was checked on update to avoid surprising admins with a sudden change of behavior. Then the admin can decide to tweak if needed.

@jvillafanez does that make sense ?

**Comment by jvillafanez** [comment]
Migration incomming!

**Comment by jvillafanez** [comment]
Migration added (*not tested yet*)

I don't think we need to check the OC version as long as the migrations are run only once (which is what I expect). Under these circumstances, copy the value from one key to another should do the trick.

**Comment by PVince81** [comment]
@jvillafanez migrations are run only once, yes. Keep in mind that migrations also run at install time so make sure it also works in that situation.

**Comment by jvillafanez** [comment]
* Fresh install -> migration runs without doing anything (key is missing so nothing to do)
* Update from 10.0.3 with checkbox active -> key is duplicated
* Update from 9.1.6 with checkbox active -> key is duplicated

LGTM

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@jvillafanez seems codecov is not happy, might be missing some test coverage ?

**Comment by PVince81** [comment]
@jvillafanez I checked the report. Not all is coverable (ignore the migration), please write tests for the changes in ShareesController.

**Comment by PVince81** [comment]
@jvillafanez please backport to stable10

**Comment by jvillafanez** [comment]
stable10 backport in https://github.com/owncloud/core/pull/29391

**Comment by individual-it** [comment]
UI tests in #29406

**Pull request merged**
