### PR TITLE
only show search icon on desktop, like on mobile

### PR DESCRIPTION
**Pull request by jancborchardt**
Much simpler, and actually easier to discover. Expands and focuses when clicked.
Please review @owncloud/designers @PVince81 @karlitschek 

Before:
capture du 2015-08-26 09-38-19
After:
capture du 2015-08-26 09-38-03

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by PVince81** [comment]
Steps:

1. Open search box
1. Type something
1. Click outside
1. Reopen box

At this stage it would be good to auto-select the contents to make it possible to quickly retype new search terms without having to manually select all. Not sure if this is still a common pattern nowadays ?

Otherwise it looks good.

**Comment by MorrisJobke** [comment]
* [ ] text field should stay expanded if something is typed in.

**Comment by jancborchardt** [comment]
@PVince81 @MorrisJobke for both of these things we need JS since the current solution is CSS-only and it’s not possible to detect with CSS if an input field is empty or not (at least not for a search field, with `:valid` for example).
So if you’re up for it just do it. Otherwise I suggest merging this first and then do the detail fixes later.

**Comment by PVince81** [comment]
:+1: from me

The rest will need JS additions

**Comment by jancborchardt** [comment]
Talked with @PVince81 – we will do enhancements later.

**Pull request merged**
