### PR TITLE
Synchronise files_external and objectstore Docker tests with master

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Checkout files from 4d69e562a065a79461343444a842ada025f3643c

Mostly minor changes, I've also ported across the Swift environment files so it will get tested on stable8.2. Probably should have done that right from the beginning.

Superset of a backport of #22742 

cc @PVince81 @DeepDiver1975 @karlitschek @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Makes sense and seems to work :+1:

**Comment by PVince81** [comment]
8.2.3 is technically frozen, then let's get this into 8.2.4 once the release is out

**Comment by karlitschek** [comment]
backport is fine after the freeze as @pvince81 mentioned

**Comment by PVince81** [comment]
:+1: let's get this in

**Pull request merged**
