### PR TITLE
Backport of #16890 to stable8

### PR DESCRIPTION
**Pull request by blizzz**
@MorrisJobke @jvillafanez

### CODE REVIEW

**Comment by jvillafanez** [comment]
The user count, at least for the group, doesn't seem to be updated. The rest of the things work fine.

**Comment by blizzz** [comment]
> The user count, at least for the group, doesn't seem to be updated.

Perhaps caching?

**Comment by jvillafanez** [comment]
I doubt it. The "everyone" count updates fine, but the group count not, even after waiting more than 10 minutes.

**Comment by blizzz** [comment]
If the user was deleted from LDAP, it is not supposed to be counted at all anyway (no matter whether he was deleted via ownCloud or not). Or, is it about local groups?

**Comment by jvillafanez** [comment]
I've checked only LDAP groups. No local groups in the system other than the admin one

**Comment by blizzz** [comment]
Then it is not supposed that anything changes. We do not write to LDAP and only deal with users that are already deleted from LDAP, and so should be their group memberships.

**Comment by DeepDiver1975** [comment]
sounds like this has to wait until 8.0.6 :question: 

@blizzz @jvillafanez

**Comment by MorrisJobke** [comment]
Tested and works. :+1:

**Comment by MorrisJobke** [comment]
The same as https://github.com/owncloud/core/pull/17034#issuecomment-114460504 applies to this PR.

**Comment by MorrisJobke** [comment]
@jvillafanez please retest with a LDAP user, a home folder naming rule and the deletion of that folder.

**Comment by jvillafanez** [comment]
:+1:

**Comment by jvillafanez** [comment]
@blizzz FYI, regarding the supposed bug with the user count, I didn't notice that the member list of the groups didn't get updated on its own after deleting the user; I haven't set the referencial integrity in the LDAP server (openLDAP) so the entry for the user was still in the groups. That explains why the user count didn't get updated.

Now you can sleep like a log :smile:

**Comment by blizzz** [comment]
super, thank you @jvillafanez 

 :zzz: 
:poodle:

**Pull request merged**
