### PR TITLE
[stable9] Ensure that stored version is at least 1 for cross-storage copy

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/owncloud/core/pull/23108

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

@nickvergessen can you redo the smashbox dance ?

**Comment by schiesbn** [comment]
:+1: (and thanks for adding the unit test!)

**Comment by nickvergessen** [comment]
We have no smashbox test for cross-storage copying. So :no_mouth:

**Comment by nickvergessen** [comment]
But smashed the original PR and was fine as well: https://github.com/owncloud/core/pull/23108#issuecomment-196318896
Also the jenkins smashbox tests pass, so fine

**Pull request merged**
