### PR TITLE
[CI] Fixed issue #21452

### PR DESCRIPTION
**Pull request by rullzer**
Jenkins PR for https://github.com/owncloud/core/pull/21590

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I squashed the commits. 

:+1: because it works 

@PVince81 also already +1ed here https://github.com/owncloud/core/pull/21590#issuecomment-170854283

**Comment by DeepDiver1975** [comment]
@ErikPel Did you sign the contributors agreement? Or is this change MIT licensed? THX

**Comment by DeepDiver1975** [comment]
ok - 3 SLOC change does not require a contrib agreement -> merge

**Comment by ErikPel** [comment]
@DeepDiver1975  Yeah I signed it couple of days ago

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 Yeah I signed it couple of days ago

@karlitschek Please verify then ;)

**Comment by karlitschek** [comment]
confirmed :+1:

**Pull request merged**
