### PR TITLE
make decrypt all work with the master key

### LINKED ISSUE #22502: Make decrypt-all work with the master key
Currently the occ tool to decrypt all files doesn't work with the master key enabled.
The occ tool decrypt-all expects either the recovery key password or the user login password. Both is not needed, if the master key is enabled. We should just skip the password prompt in this case.

### PR DESCRIPTION
**Pull request by schiessle**
make decrypt all work with the master key, fix: https://github.com/owncloud/core/issues/22502

cc @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Works :+1: 

- [x] TEST: decrypt with master key
- [x] TEST: decrypt with recovery key
- [x] TEST: decrypt with user's password

**Comment by schiesbn** [comment]
@nickvergessen second review? Thanks!

**Comment by PVince81** [comment]
@schiesbn best is to ping more people to increase your changes

Needs a second reviewer @MorrisJobke @icewind1991 @DeepDiver1975

**Comment by icewind1991** [comment]
Code looks good :+1:

**Pull request merged**
