### PR TITLE
Update JS unit test libs

### PR DESCRIPTION
**Pull request by PVince81**
Update sinon to 1.15.4.
Update karma-jasmine to 0.3.0
Update jasmine to 2.3.4

This brings a bunch of new useful functions for unit testing.

@DeepDiver1975 @rullzer (this time for real!)

### CODE REVIEW

**Comment by PVince81** [comment]
Jenkins is happy ! Please review @rullzer @DeepDiver1975 @MorrisJobke

**Comment by MorrisJobke** [comment]
Weird only sinon has changes: https://github.com/owncloud/core/pull/17555/files

**Comment by rullzer** [comment]
@MorrisJobke the other stuff is installed in ./build/

**Comment by MorrisJobke** [comment]
Ah right. They aren't checked in :)

**Comment by MorrisJobke** [comment]
`./autotest-js.sh` still works :+1:

**Comment by rullzer** [comment]
JS unit tests run fine.

I do get a big warning now

>WARN [reporter]: Can not load "junit"!
>  Error: You must set an output directory for JUnitReporter via the outputDir config property
>    at new JUnitReporter (/home/roeland/owncloud/core/build/lib/node_modules/karma-junit-reporter/index.js:12:11)
    at invoke (/home/roeland/owncloud/core/build/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate [as 0] (/home/roeland/owncloud/core/build/lib/node_modules/karma/node_modules/di/lib/injector.js:59:20)
    at get (/home/roeland/owncloud/core/build/lib/node_modules/karma/node_modules/di/lib/injector.js:48:43)
    at /home/roeland/owncloud/core/build/lib/node_modules/karma/lib/reporter.js:88:75
    at Array.forEach (native)
    at createReporters (/home/roeland/owncloud/core/build/lib/node_modules/karma/lib/reporter.js:76:9)
    at Array.invoke [as 0] (/home/roeland/owncloud/core/build/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at get (/home/roeland/owncloud/core/build/lib/node_modules/karma/node_modules/di/lib/injector.js:48:43)
    at get (/home/roeland/owncloud/core/build/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)

**Comment by PVince81** [comment]
@rullzer you probably got this on the old version too. The junit plugin is for generating reports or coverage for Jenkins. I could add it to package.json to make it disappear.

**Comment by PVince81** [comment]
@rullzer I also got this error on master.

**Comment by rullzer** [comment]
@PVince81 ah mmm then I just did not pay attention to the header :)
Anyway, fine with me. I do not want coverage reports usually

**Comment by rullzer** [comment]
so :+1:

**Pull request merged**
