### PR TITLE
Add social media buttons

### LINKED ISSUE #16190: Expain Federation to user
Add a “Federation” section to the personal page which shows the users' personal Federation Id.

Something like:

Federation
========
Your federation Id is "xxx@xxx.de/yyy”
Users on other ownCloud servers can share something with you by entering this ID into their sharing dialog. Find out more about federation on http://owncloud.org/federation (or documentation link?)

Share you Id on:
- Twitter
- Facebook
- Google+
- Diaspora
- website (provide website code)

Message:
“Share with me through my #ownCloud federation Id xxx@xxx/yyy see http://owncloud.org/federation"
Website code can be similar to above, just in html.

Text can perhaps use more discussion.

Depends on a page on owncloud.org/federation - owncloud/owncloud.org#544

For the future we have lots of ideas for improvement - that's for 8.2.

### PR DESCRIPTION
**Pull request by schiessle**
Add social media buttons to enable the user to share his federated cloud Id on various social networks.

@jospoortvliet the url http://owncloud.org/federation doesn't work yet, is it the right one? 

State:
- [x] Twitter -> works
- [x] Diaspora works, if the solution is acceptable? Should we try to add the dialog directly to the ownCloud or to owncloud.org or is it acceptable to link to a 3rdparty site to chose your pod and forward the message?
- [x] Facebook it seems that it is only possible to share links but not predefined messages (see: https://developers.facebook.com/blog/post/510/ -> unless someone has a better idea the current implementation is the best we can offer.
- [x] Goggle+ same like Facebook, seems not to be possible to share predefined messages.  -> unless someone has a better idea the current implementation is the best we can offer.
- [x] I found a nice GNU Social button (formally identi.ca/status.net), https://github.com/chimo/gs-share and added it to the list. What do you think? 
-  [x] need nice buttons for the social networks (Diaspora, Facebook, Google+, Twitter, GNU Social (if the defaul one doesn't fit with the other)) cc @jancborchardt 
- [x] need a banner/button people can add to their homepage cc @jancborchardt 

fix https://github.com/owncloud/core/issues/16190

### CODE REVIEW

**Comment by schiesbn** [comment]
cc @MorrisJobke this is the new PR for the social media buttons. From my POV it is ready to go once we have the necessary buttons/banners

**Comment by karlitschek** [comment]
:+1: from my side once we have the icons. 
Would be great to have an config.php switch to disable this complete section on the personal page. This is for the case where an admin doesn't like this.

**Comment by LukasReschke** [comment]
> Would be great to have an config.php switch to disable this complete section on the personal page. This is for the case where an admin doesn't like this.

I'd suggest to make a dedicated application out of this then since this would do the same without adding new config switches.

**Comment by schiesbn** [comment]
> I'd suggest to make a dedicated application out of this then since this would do the same without adding new config switches.

Not sure about this. Sharing is already today quite complex. We have the share API in core which can be enabled/disabled, we have the files_sharing  app which can be enabled/disabled and now we would add a "share your server-to-server file sharing app". IMHO this clearly belongs to the files_sharing app which by the way already has some admin settings so we could just add one more setting point to it.

On the other hand sharing already has quite a lot of settings. Therefore I would suggest to keep it always enabled for now (if outgoing server-to-server sharing is enabled) and only add another option if we really see the need for it and if various user request it.

**Comment by LukasReschke** [comment]
Maybe we can just hide it if S2S is disabled?

**Comment by schiesbn** [comment]
> Maybe we can just hide it if S2S is disabled?

yes, I'm just adding the check. Of course it doesn't make sense to show/share a ID which doesn't work

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by jospoortvliet** [comment]
https://owncloud.org/federation/ has been enabled, btw ;-)

**Comment by schiesbn** [comment]
@jospoortvliet thanks! So we just need some nice buttons to finish this PR

**Comment by DeepDiver1975** [comment]
> So we just need some nice social media buttons and a banner/button we want share on users web pages to finish this PR

@jancborchardt task for you? THX

**Comment by MorrisJobke** [comment]
@jancborchardt Something like http://sharebutton.co/ has nice icons. Maybe we can use them. I'm unsure about this.

**Comment by jancborchardt** [comment]
Will look into the icons.

@schiesbn can we make the small windows which are opened new tabs instead? Or is this the standard way of handling these intents? Seems a bit strange.
Also, the link below »Add your Federated Cloud Id to your homepage:« should be target="_blank" (will do it later) – all external links in ownCloud _need_ to be force opened in a new tab so we don’t throw people out of the app.

**Comment by schiesbn** [comment]
> can we make the small windows which are opened new tabs instead? Or is this the standard way of handling these intents? Seems a bit strange.

I had it on a new window at the beginning but it looks quite strange because you have just a large input field and submit button and the rest is empty. Also most other pages with such buttons open them in a pop-up window. But I don't have a strong opinion here.

**Comment by jancborchardt** [comment]
Ok, if most other pages do it like that I’m fine with it. Currently we open the popup in the top left – can we center it?

**Comment by schiesbn** [comment]
> Currently we open the popup in the top left – can we center it?

Not sure if we can influence it. For me it doesn't open in the top left, but also not in the middle... I will check if there is a solution.

**Comment by schiesbn** [comment]
With my last commit the pop-ups should be always in the center.

**Comment by schiesbn** [comment]
@jancborchardt any news here?

**Comment by DeepDiver1975** [comment]
JAN - GO GO GO
sonic-boom-ass-spank_o_119721

**Comment by schiesbn** [comment]
@jancborchardt if you have the buttons feel free to push them directly to this branch and also directly update the image tags if you want.

**Comment by LukasReschke** [comment]
Fine I will get the whip

**Comment by jancborchardt** [comment]
@schiesbn I added the icons, fixed the HTML & layout etc. You need to wire the buttons up again now. Also, can you add the absolute path to the social-owncloud icon there in the HTML?

**Comment by schiesbn** [comment]
looks great, I will take care about the rest

**Comment by schiesbn** [comment]
Now everything should work and look like it is expected. Please ignore the failing tests, this is a stand-alone page which doesn't influence anything else. Jenkins just doesn't like this branch because of some rebase action in the past.

**Comment by schiesbn** [comment]
@jancborchardt please also have a final look. I have the feeling that the ownCloud logo after "Add it to you webpage" could be improved to be more in line with the text.




Also I would have expected something more like the social media button for the "add it to your website" section instead of just a small ownCloud icon with some text next to it. But that's your final decision, you are the designer. :wink:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by jancborchardt** [comment]
@schiesbn updated:
image

**Comment by schiesbn** [comment]
Looks great! Just one more thought. Should the button somehow contain the users cloud ID? Because if you put the current button on your homepage the visitor will only have a link to a general description but don't know the ID of the user.

**Comment by jancborchardt** [comment]
True … that’s tough since we can’t really cram the whole address in there :D or it will look incredibly stupid.

That’s exactly why I said back in the day when we talked about it that we should be able to pass the Federated Cloud ID to the microsite using a hash so we can display it there.

It’s not that hard, no?
1. Append it to the link as a hash:
`https://owncloud.org/federation#username@example.com/owncloud`
2. On the federation page, call `location.hash` via Javascript and display it prominently on the page making clear that’s the address you need to copy.

**Comment by schiesbn** [comment]
@jancborchardt agree, I would also like to have the right ID at the microsite. Ideally not only in the examples (because there it is not always obvious if it is a example or a real address) but additionally something along the line "This is my federated cloud id: foo@bar.org" at the top of the page.

What was the reason that it was rejected?

**Comment by schiesbn** [comment]
@jospoortvliet do you think you could add something like that?

**Comment by jancborchardt** [comment]
I guess it was rejected because we thought it was too complicated for version 1. ;)

**Comment by jospoortvliet** [comment]
no, it was rejected because we shouldn't be sending all those federation ID's to our owncloud.org website to be possibly recorded and stored for our evil purposes. In other words - privacy thing.

For version two we want to integrate the microsite in ownCloud so we don't have this problem.

But that's ownCloud 8.2. For this release I'd prefer to have this merged rather than us re-hashing earlier conversations ;-)

**Comment by MorrisJobke** [comment]
> no, it was rejected because we shouldn't be sending all those federation ID's to our owncloud.org website to be possibly recorded and stored for our evil purposes. In other words - privacy thing.

Anchors (stuff after `#` in the URL) are never send to the HTTP server ;) They reside only in the browser. But they can be read by the JS in the browser. Then it's easy to display them in the side ;)

**Comment by jancborchardt** [comment]
Exactly what Morris said.

**Comment by jancborchardt** [comment]
As mentioned above the button does not have the address, and the microsite doesn't have it either. As it will look extremely strange on the button (also because the button leads you away) we need it on the microsite.

**Comment by jospoortvliet** [comment]
BTW I tested the current code and it works for me, so :+1: for what it's worth.

It would indeed be nice if somebody's federation ID would show up on the button, it's annoying enough that we have to ask users to add their ID to the social media messages as we can't do that automatically :(

**Comment by jospoortvliet** [comment]
@MorrisJobke @jancborchardt if you say so - I'm happy to add this to the website. @schiesbn change the code to give the federation ID to owncloud.org and I will follow the suggestions given earlier to get it displayed on that site. Be sure to include it in the social media links ;-)

**Comment by schiesbn** [comment]
@jospoortvliet let's do it. I think that would be a great improvement. I will update the links here and you update the webpage.

BTW: I agree about version 2, would be nice to move the microsite directly to the ownCloud server instead of one centralized page. This way it also benefit from theming, translations etc.

**Comment by jancborchardt** [comment]
@Schiesbn when it’s then part of the link in the social media message, you can remove the ID from the message itself. Otherwise I guess we also run out of space e.g. for tweets.

**Comment by schiesbn** [comment]
I updated the URLs... So we just need a second reviewer, who wants to give a +1 ?

**Comment by DeepDiver1975** [comment]
> I updated the URLs... So we just need a second reviewer, who wants to give a +1 ?

and a green jenkins is required as well - just saying :speak_no_evil:

**Comment by MorrisJobke** [comment]
I will create the jenkins branch

**Comment by MorrisJobke** [comment]
Looks good and works :+1:

**Comment by schiesbn** [comment]
Jenkins finished successfully

**Pull request merged**
