### PR TITLE
[full-ci] [10.11.0] Allow editing of public link shared single files 10.11

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
This is the same as #40317 but targeted at `release-10.11.0` branch.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by pmaier1 — APPROVED** [review]

**Review by jnweiger — APPROVED** [review]
Looks good, has all the 6 comits of original 40317.

**Comment by mrow4a** [comment]
@phil-davis backported changed from https://github.com/owncloud/core/pull/40289/files in the commit here https://github.com/owncloud/core/pull/40333/commits/96c704cd55ee32b34d1fd421f904923081dac944

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIWebdavLockProt-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36755/160

**Comment by phil-davis** [comment]
I made a mess of rebasing, accidentally!!! I will try to fix it soon, but I need to go to the airport now. Sorry.

**Comment by phil-davis** [comment]
See $40342

**Review by jnweiger — CHANGES_REQUESTED** [review]
Superceeded by https://github.com/owncloud/core/pull/40342

**Pull request closed without merging**
