### PR TITLE
[stable10] Backport all objectstore related changes

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Targetting 10.0.9

- [x] backport #29207 - first 8 commits until 0a3c04567a1ef064693c333084f95a9e49c73ca4
- [x] backport #29257 - next 6 commits until aafd6eb46ff5d7ba00e94d5ef4e57f0b1c1717dc
- [x] backport #29607 - next 2 commits until e20f258b6127aeedfec84fc69e9ede738daf9f78
- [x] backport #29319 - next 6 commits until 4b8dc069860b5e28a998ded2fc2637914d2e891a
- [x] backport #30254 - 1 commit
- [x] backport #30192 - 1 commit
- [x] backport #29637 - 1 commit
- [x] backport https://github.com/owncloud/core/pull/31285 - 12 commits

### CODE REVIEW

**Comment by PVince81** [comment]
a wild conflict appears...

**Review by patrickjahns — CHANGES_REQUESTED** [review]
There seem to be some issues appearing now in master - let's first resolve them in master and then continue to port / release these changes
https://github.com/owncloud/core/pull/31285#issuecomment-390181706

**Comment by PVince81** [comment]
- [ ] BUG: PR will likely break tests with skeleton issue, see https://github.com/owncloud/core/issues/31514

**Comment by patrickjahns** [comment]
@phil-davis - I assume the changes to `tests/acceptance/run.sh` - could you take a look so we can rebase and move this PR into QA

**Comment by phil-davis** [comment]
Conflicts resolved and rebased.

**Comment by phil-davis** [comment]
@DeepDiver1975 PR #31577 in ``master`` added some more scenarios about versions.
Can you add the commit to this backport please?

**Comment by PVince81** [comment]
cherry-picked https://github.com/owncloud/core/pull/31595 to solve https://github.com/owncloud/core/pull/31050#issuecomment-391634077

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/31681

**Comment by phil-davis** [comment]
Added small change to ``dav-versions.feature`` from PR #31608

**Review by patrickjahns — APPROVED** [review]
release - 🚄 is taking on steam - tested with files_primary_S3 - 👍

**Comment by phil-davis** [comment]
Added a commit to remove duplicate code that got left behind in ``tests/integration`` and another copy of ``dav-versions.feature`` - the "real" ``apiMain/dav-versions.feature`` has all the deleted scenarios already.

**Comment by phil-davis** [comment]
I  think something is still wrong with:
```
 >> apiMain suite has undefined steps. Please choose the context to generate snippets:

  [0] None
  [1] FeatureContext
  [2] CardDavContext
  [3] CalDavContext
  [4] AppManagementContext
 > 0

--- Use --snippets-for CLI option to generate snippets for following apiMain suite steps:

    And we save it into "FILEID"
```
That ``And we save it into`` is a Behat built-in thing in BehatVariablesContext. I guess we lost that along the way somewhere recently.

**Comment by phil-davis** [comment]
Added commit ``FeatureContext extends \rdx\behatvars\BehatVariablesContext `` 
Something went wrong in conflict resolution in 1 of the other 50 commits, this critical line got missed.
I think it will pass - we will see.

**Comment by phil-davis** [comment]
Travis has some stupid travis-ci/push thing that does not work - whatever that is about???
At least drone is passing now.

**Comment by phil-davis** [comment]
Good that this is finally merged. In future we should try very hard not to have big changes like this that wait a long time until someone decides they should be backported, and other dependent changes pile up behind and...
"semver" should help because we would make a new/fresh release branch (e.g. 10.1) for such a thing, and not attempt to backport it.

@DeepDiver1975 re: commits - I know all about rebasing and squashing "fix" commits into the original commits where they belong. For those last 2 commits, it was late at night here and I wanted to just prove the fixes. Then I intended to try and find the commits (among the other 49) where the conflict resolution had gone wrong in the past and apply the fixes to those commits. That is a bit tedious (looking at the content of each commit in the history to find ones that went wrong), so I left it for after sleep. In  the meantime the PR has been merged. So it is too late now - those last 2 commits are on the stable10 branch.

**Comment by PVince81** [comment]
two regressions:
- https://github.com/owncloud/core/issues/18645
- https://github.com/owncloud/enterprise/issues/2904

**Pull request merged**
