### PR TITLE
Issue/15138 feedback for empty apps list

### LINKED ISSUE #15138: No feedback when there are no apps in the appstore for your version
# Steps to reproduce
1. Install current master
2. Go to the App Management
3. Open "Multimedia"
4. Wait for feedback ... or better don't

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Message when no app was returned from the app store
- [x] Deduplicate CSS for emptycontent from files.css
- [x] Use the same CSS when no search result was found

Fix #15138

@MorrisJobke @jancborchardt

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by MorrisJobke** [comment]
* [ ] switching to a category and then back to 'active apps` will show the content of the category (but should show the activity apps)

**Comment by nickvergessen** [comment]
Pushed

**Comment by MorrisJobke** [comment]
Works now :+1:

**Comment by jancborchardt** [comment]
@nickvergessen nice work! And good on finding the duplicate CSS.

**Pull request merged**
