### PR TITLE
Stop executing, when 3rdparty is missing or apps directory is invalid

### PR DESCRIPTION
**Pull request by nickvergessen**
Replaces #11063

Just making the behaviour consistent when 3rdparty and app path is missing/not valid.

empty `OC::$APPSROOTS` gives a blank page atm, because the exception message is not displayed.

@LukasReschke @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Always the same:

```
16:05:50 Using database oc_autotest8
16:05:50 Setup environment for sqlite testing ...
16:05:51 Installing ....
16:05:51 PHP Notice:  Undefined index: SERVER_PROTOCOL in /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/private/response.php on line 57
16:05:51 PHP Stack trace:
16:05:51 PHP   1. {main}() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/occ:0
16:05:51 PHP   2. require_once() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/occ:11
16:05:51 PHP   3. require_once() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/console.php:14
16:05:51 PHP   4. OC::init() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/base.php:1042
16:05:51 PHP   5. OC_Response::setStatus() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/base.php:486
16:05:51 App directory "/var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/apps2" not found! Please put the ownCloud apps folder in the ownCloud folder or the folder above. You can also configure the location in the config.php file.Testing with sqlite ...
16:05:51 PHP Notice:  Undefined index: SERVER_PROTOCOL in /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/private/response.php on line 57
16:05:51 PHP Stack trace:
16:05:51 PHP   1. {main}() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/tests/enable_all.php:0
16:05:51 PHP   2. require_once() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/tests/enable_all.php:9
16:05:51 PHP   3. OC::init() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/base.php:1042
16:05:51 PHP   4. OC_Response::setStatus() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/base.php:486
16:05:51 PHP Notice:  Undefined index: SERVER_PROTOCOL in /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/private/response.php on line 57
16:05:51 PHP Stack trace:
16:05:51 PHP   1. {main}() /usr/local/bin/phpunit:0
16:05:51 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:612
16:05:51 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
16:05:51 PHP   4. PHPUnit_TextUI_Command->handleArguments() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:148
16:05:51 PHP   5. PHPUnit_TextUI_Command->handleBootstrap() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:651
16:05:51 PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:817
16:05:51 PHP   7. PHPUnit_Util_Fileloader::load() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:77
16:05:51 PHP   8. include_once() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:93
16:05:51 PHP   9. require_once() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/tests/bootstrap.php:16
16:05:51 PHP  10. OC::init() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/base.php:1042
16:05:51 PHP  11. OC_Response::setStatus() /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/base.php:486
16:05:51 App directory "/var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/apps2" not found! Please put the ownCloud apps folder in the ownCloud folder or the folder 
```

**Comment by nickvergessen** [comment]
No, thats different and

```
App directory "/var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/apps2" not found! Please put the ownCloud apps folder in the ownCloud folder or the folder 
``` points out a problem ;)

**Comment by DeepDiver1975** [comment]
@nickvergessen the config to be changed is here: https://github.com/owncloud/core/blob/master/tests/preseed-config.php#L14

**Comment by nickvergessen** [comment]
Yes, I fixed that yesterday already, but couldnt push (no interwebz)

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
