### PR TITLE
Expose share owner id and display name via files webdav

### PR DESCRIPTION
**Pull request by PVince81**
- Required by the Webdav files UI: we need the share owner to be able to display it in the UI. It was formerly available in the "ajax/list.php" response.
- This PR brings this value to the files' Webdav response, when requested explicitly.
- Whether a folder is an incoming share is already available in the "S" permission (oc:permissions)
- This does not cause a performance penalty because the share info has already been resolved at the time the mount point was created. So we're basically reading information that is already available.
#### To test:
1. Create two users "root" and "user1"
2. Login as "user1"
3. Share a folder "test" with "root"
4. Save the following into "propfind.txt"

``` xml
<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">
        <a:prop><oc:permissions/></a:prop>
        <a:prop><oc:owner-id/></a:prop>
        <a:prop><oc:owner-display-name/></a:prop>
</a:propfind>
```
1. `curl -X PROPFIND -H "Content-Type: text/xml" --data-binary "@propfind.txt" http://root:admin@localhost/owncloud/remote.php/webdav/test | xmllint --format -`

This PR will output two additional properties, when requested as above:

``` xml
<d:response>
    <d:href>/owncloud/remote.php/webdav/test/</d:href>
    <d:propstat>
      <d:prop>
        <oc:owner-id>user1</oc:share-owner-id>
        <oc:owner-display-name>User One</oc:share-owner-display-name>
        <oc:permissions>SRDNVCK</oc:permissions>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
```

Edit: now renamed to "owner-id" and "owner-display-name"
#### Open questions:
- [x] Should we rename "share owner" to simply "owner" ? If yes:
  - In ownCloud's terms, the owner of a file is always either the current user or the sharer.
  - Note that is we rename it to "owner" we'll need to return the current user.
  - It is still possible to detect if this is a shared mount by checking the "S" permission.
  - We'd then remove SharesPlugin and move the attribute to FilesPlugin, as it is more generic
- [x] @icewind1991 do you think we should cache the `getOwner()` for better performance ? The code path looks like it goes up to the SharedStorage which has the share cached
- [x] TODO: add unit tests once everything is clarified

Let's discuss @DeepDiver1975 @icewind1991 @schiesbn @rullzer @nickvergessen

### CODE REVIEW

**Comment by PVince81** [comment]
I realized that this PR already returns the current user "root" when doing a PROPFIND on a non-shared item. If we really want this only for shares, then the property would need to be adjusted.

I think I'm more in favor of having a more generic "owner-id" and "owner-display-name" attribute.
Thinking further, I wonder how this would fit in with principals in the future. But we need a short term solution.

**Comment by PVince81** [comment]
- [ ] TODO: make sure to return 403 if someone tries to PROPPATCH these new properties

**Comment by icewind1991** [comment]
I agree with moving to `owner-id`

**Comment by icewind1991** [comment]
> @icewind1991 do you think we should cache the getOwner() for better performance ? The code path looks like it goes up to the SharedStorage which has the share cached

Might be good to add `getOwner` to the `FileInfo` which could then be used to cache it

**Comment by PVince81** [comment]
@icewind1991 I added getOwner to the FileInfo interface and also Node API, please check my implementation: https://github.com/owncloud/core/commit/f563648661412593e33863dbd4a4f7c33cd6869d

And I renamed the properties to "owner-id" and "owner-display-name".

Please review

**Comment by PVince81** [comment]
Regarding getOwner on the interface: I checked that the `Common` storage, `SharedStorage` and all the external storages have that method implemented. External storages all directly or indirectly extend `Common`.

**Comment by icewind1991** [comment]
> @icewind1991 I added getOwner to the FileInfo interface and also Node API, please check my implementation: f563648

Since we also want the display name it makes more sense imo to return a user object.

See https://github.com/owncloud/core/pull/20224

**Comment by rullzer** [comment]
@PVince81  rebase now that #20224 is in.

**Comment by PVince81** [comment]
I'll fix it to use the "new" API, as we're now getting a user object.

**Comment by PVince81** [comment]
I have updated the API usage and the unit tests to reflect the fact that `getOwner()` now returns user objects.

Please review @icewind1991 @rullzer @DeepDiver1975 @blizzz @schiesbn

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
CC @dragotin @guruz @rperezb in case desktop and mobile clients are interested in this property too.
Note that the original reason I added it is because the web UI will need it when using Webdav.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
