### PR TITLE
[stable8.2] Use new APCu API

### LINKED ISSUE #21095: APCu 5.1.2 & PHP7: \OC\Memcache\APCu not usable
### Steps to reproduce
1. Install PHP7 and APCu 5.1.2
2. Set `memcache.local` config to `\OC\Memcache\APCu`

### Expected behaviour
ownCloud should use the APCu extension for caching.

### Actual behaviour
Error message `Memcache \OC\Memcache\APCu not available for local cache Is the matching PHP module installed and enabled?`

### Reason
The new APCu version drops the APC compatibility layer. The extension is now called `apcu.so` (instead of `apc.so`) and the functions and classes have changed prefixes. There is a compatibility extension ( https://pecl.php.net/package/apcu_bc ) but relying on that would IMHO be too restrictive.

### Workaround
Replace `lib/private/memcache/apcu.php` with the following:
```php
<?php
/**
 * @author Andreas Fischer <bantu@owncloud.com>
 * @author Morris Jobke <hey@morrisjobke.de>
 * @author Otto Sabart <ottosabart@seberm.com>
 * @author Robin Appelman <icewind@owncloud.com>
 *
 * @copyright Copyright (c) 2015, ownCloud, Inc.
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

namespace OC\Memcache;

use OCP\IMemcache;

class APCu extends Cache implements IMemcache {
  use CASTrait {
    cas as casEmulated;
  }

  use CADTrait;

  public function get($key) {
    $result = apcu_fetch($this->getPrefix() . $key, $success);
    if (!$success) {
      return null;
    }
    return $result;
  }

  public function set($key, $value, $ttl = 0) {
    return apcu_store($this->getPrefix() . $key, $value, $ttl);
  }

  public function hasKey($key) {
    return apcu_exists($this->getPrefix() . $key);
  }

  public function remove($key) {
    return apcu_delete($this->getPrefix() . $key);
  }

  public function clear($prefix = '') {
    $ns = $this->getPrefix() . $prefix;
    $ns = preg_quote($ns, '/');
    $iter = new \APCUIterator('user', '/^' . $ns . '/', APC_ITER_KEY);
    return apcu_delete($iter);
  }

  /**
   * Set a value in the cache if it's not already stored
   *
   * @param string $key
   * @param mixed $value
   * @param int $ttl Time To Live in seconds. Defaults to 60*60*24
   * @return bool
   */
  public function add($key, $value, $ttl = 0) {
    return apcu_add($this->getPrefix() . $key, $value, $ttl);
  }

  /**
   * Increase a stored number
   *
   * @param string $key
   * @param int $step
   * @return int | bool
   */
  public function inc($key, $step = 1) {
    $this->add($key, 0);
    return apcu_inc($this->getPrefix() . $key, $step);
  }

  /**
   * Decrease a stored number
   *
   * @param string $key
   * @param int $step
   * @return int | bool
   */
  public function dec($key, $step = 1) {
    return apcu_dec($this->getPrefix() . $key, $step);
  }

  /**
   * Compare and set
   *
   * @param string $key
   * @param mixed $old
   * @param mixed $new
   * @return bool
   */
  public function cas($key, $old, $new) {
    // apc only does cas for ints
    if (is_int($old) and is_int($new)) {
      return apcu_cas($this->getPrefix() . $key, $old, $new);
    } else {
      return $this->casEmulated($key, $old, $new);
    }
  }

  static public function isAvailable() {
    if (!extension_loaded('apcu')) {
      return false;
    } elseif (!\OC::$server->getIniWrapper()->getBool('apc.enabled')) {
      return false;
    } elseif (!\OC::$server->getIniWrapper()->getBool('apc.enable_cli') && \OC::$CLI) {
      return false;
    } elseif (version_compare(phpversion('apcu'), '5.1.2') === -1) {
      return false;
    } else {
      return true;
    }
  }
}
```

Obviously this is not a fix that can be incorporated into core since it relies on PHP7 & APCu 5.1.2. But it will do as a workaround.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.9

**Database:** mysql 5.5

**PHP version:** 7.0 (via https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0 )

**ownCloud version:** 8.2.1.4

**Updated from an older ownCloud or fresh install:** yes

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - notifications: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - gallery
  - provisioning_api
  - search_lucene
  - templateeditor
  - updater
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "installed": true,
        "has_internet_connection": true,
        "datadirectory": "\/cloud\/data\/owncloud",
        "dbtype": "mysql",
        "redis": {
            "host": "localhost",
            "port": "6379"
        },
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "version": "8.2.1.4",
        "maintenance": false,
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "trashbin_retention_obligation": "auto",
        "apps_paths": [
            {
                "writable": false,
                "url": "\/apps",
                "path": "\/var\/www\/owncloud\/apps"
            },
            {
                "writable": true,
                "url": "\/user-apps",
                "path": "\/var\/www\/owncloud-apps\/user-apps"
            }
        ],
        "dbname": "owncloud",
        "instanceid": "uniq-id",
        "dbhost": "localhost",
        "loglevel": 2,
        "trusted_domains": [
            "domain.name"
        ],
        "mail_smtpmode": "php"
    }
}

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### ownCloud log (data/owncloud.log)
```json
{"reqId":"F4CugmkIqRCiIqhhACjF","remoteAddr":"1.2.3.4","app":"core","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Memcache \\\\OC\\\\Memcache\\\\APCu not available for local cache\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/server.php(267): OC\\\\Memcache\\\\Factory->__construct('8d4c1e106006f44...', Object(OC\\\\Log), '\\\\\\\\OC\\\\\\\\Memcache\\\\\\\\AP...', '\\\\\\\\OC\\\\\\\\Memcache\\\\\\\\AP...', NULL)\\n#1 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#2 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): Pimple\\\\Container->offsetGet('MemCacheFactory')\\n#3 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/server.php(753): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('MemCacheFactory')\\n#4 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/server.php(242): OC\\\\Server->getMemCacheFactory()\\n#5 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#6 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): Pimple\\\\Container->offsetGet('URLGenerator')\\n#7 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/server.php(726): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('URLGenerator')\\n#8 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/helper.php(174): OC\\\\Server->getURLGenerator()\\n#9 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template\\\/functions.php(169): OC_Helper::imagePath('', 'favicon.png')\\n#10 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/core\\\/templates\\\/layout.guest.php(15): image_path('', 'favicon.png')\\n#11 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(160): include('\\\/var\\\/www\\\/8.2.1\\\/...')\\n#12 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(138): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/8.2.1\\\/...')\\n#13 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template.php(211): OC\\\\Template\\\\Base->fetchPage()\\n#14 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template.php(233): OC_Template->fetchPage()\\n#15 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(121): OC_Template->fetchPage()\\n#16 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/template.php(308): OC\\\\Template\\\\Base->printPage()\\n#17 \\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/index.php(49): OC_Template::printErrorPage('Memcache \\\\\\\\OC\\\\\\\\Me...', 'Is the matching...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/8.2.1\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/factory.php\",\"Line\":94}","level":3,"time":"2015-12-10T01:57:00+00:00"}
```

### PR DESCRIPTION
**Pull request by cdamken**
Backport of https://github.com/owncloud/core/pull/21308 to stable8.2

This one is available since APCu 4.0, since we require APCu 4.0.6 this works fine. Also it brings us PHP 7 compatibility and thus fixes #21095

Tested on Ubuntu 16.0.4,  php7 and 8.2.7 and works.

@PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by cdamken** [comment]
@michaelstingl Dankeschön :smiley:

**Comment by cdamken** [comment]
Found some errors:
```
APCuIterator::__construct() expects parameter 2 to be integer, string given at /var/www/owncloud/lib/private/memcache/apcu.php#62
```
I'll check the code a few more

**Comment by cdamken** [comment]
@PVince81 I saw that the configuration in APCu should be:
```
   apc.enabled = on
   apc.enable_cli = off
```
explained in : http://php.net/manual/de/class.apciterator.php

if I change that way the APCu does not work because all the calls are in cli, any clue what should be changed?

**Comment by DeepDiver1975** [comment]
> if I change that way the APCu does not work because all the calls are in cli, any clue what should be changed?

APCu has two caches of it's own - one for web and one for cli.
Cli cannot access data stored in the web cache - same the other way around.

**Comment by DeepDiver1975** [comment]
@cdamken where is the neccessity for this backport coming from - we never agreed on backporting - https://github.com/owncloud/core/pull/21308#issuecomment-202570400

Happy to reevaluate if there are new reasons - THX

**Comment by PVince81** [comment]
Backporting such class changes on 8.2 looks dangerous. Unless there is a critical reason to do so :-1: for backporting.

**Comment by PVince81** [comment]
Moving to 8.2.9 and will close later if there is no feedback.

**Comment by PVince81** [comment]
Closing due to lack of feedback.

**Pull request closed without merging**
