### PR TITLE
[stable8.1] let the encryption storage wrapper always update the file cache

### PR DESCRIPTION
**Pull request by schiessle**
approved backport of https://github.com/owncloud/core/pull/18009

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:  please backport

**Comment by schiesbn** [comment]
We need this reviewed and merged for 8.1.1.  ... Who wants to review it? @DeepDiver1975 @MorrisJobke @LukasReschke ? Was already reviewed and tested successfully by @PVince81 for master.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
