### PR TITLE
fix infinite loops with propagating etags on reshares

### LINKED ISSUE #18034: Upload into reshared folder fails
### Steps
1. Create three users "user1", "user2", "user3"
3. Login as "user1"
4. Create a folder "sh"
5. Share "sh" with "user2"
6. Login as "user2"
7. Reshare "sh" with "user3"
8. Enter "sh" (still as "user2")
9. Upload a picture "test.jpg"

### Expected result
Upload succeeds

### Actual result
Internal server error appears after a delay. (even with files_locking disabled)
After refreshing the page, the files are there and seem to be downloadable.
If I unshare from "user3", uploading works without delay.

### Versions
ownCloud 8.1.1RC1

### Log
Nothing.

@schiesbn please have a look

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #18034

cc @DeepDiver1975 @PVince81 @schiesbn

### CODE REVIEW

**Comment by schiesbn** [comment]
tested, upload works again without a error message :+1:

**Comment by PVince81** [comment]
Tested, works :+1: 
I also saw that the etag of the folder for "user3" changed properly.

@karlitschek backport to stable8.1 ? We might want this in 8.1.1 because it shows "Internal Server Error" on upload into a reshared folder which looks bad.

**Comment by karlitschek** [comment]
backport is fine. :+1: 
@deepdiver1975 What is your opinion about timeing? 8.1.1 vs. 8.1.2 ?

**Comment by PVince81** [comment]
@icewind1991 please prepare the backport PR

**Comment by DeepDiver1975** [comment]
> What is your opinion about timeing? 8.1.1 vs. 8.1.2 ?

Let's see what will pop up in the next days during testing of RC1 - PR to be opened please @icewind1991

**Comment by icewind1991** [comment]
8.1: https://github.com/owncloud/core/pull/18054

**Pull request merged**
