### PR TITLE
First steps of zip folder plugin

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by PVince81** [comment]
Ah! What a discovery! Nice thing

**Comment by DeepDiver1975** [comment]
Bloody olf wip ...

**Comment by PVince81** [comment]
Works now:
ZIP: `curl -D - -X GET -H "Accept: application/zip" http://admin:admin@localhost/owncloud/remote.php/dav/files/admin/test -o test.zip`
tar: `curl -D - -X GET -H "Accept: application/x-tar" http://admin:admin@localhost/owncloud/remote.php/dav/files/admin/test -o test.tar`.

If no "Accept" header is given, it will auto-detect based on user-agent or default to ZIP.

Yes, I changed the behavior because depending on the given extension could conflict with an existing file stored in ownCloud.

I had to hack Sabre a bit to prevent it to send its own response so that the streamer can use the good old dirty "echo directly the output".

@DeepDiver1975 @butonic @mrow4a  check it out !

TODOs:
- [ ] unit tests

**Comment by PVince81** [comment]
Note: this doesn't fully replace the download endpoints. We're still missing something like "MGET" with a list of files to download from a given folder. Maybe we can do this separately if we agree on using a custom method.

**Comment by PVince81** [comment]
before I start with the pain of writing tests I'd like to know whether the approach described above is acceptable

**Comment by PVince81** [comment]
moving to backlog until there is more interest

**Comment by PVince81** [comment]
old PR... do we still want this ? if yes, please review...

**Comment by mrow4a** [comment]
Maybe just integrate already existing plugin, which my friend implemented once https://github.com/deic-dk/files_compress and that should work

**Comment by DeepDiver1975** [comment]
> Maybe just integrate already existing plugin, which my friend implemented once https://github.com/deic-dk/files_compress and that should work

I dislike the code and the concept

**Comment by DeepDiver1975** [comment]
> old PR... do we still want this ? if yes, please review...

let me revive this ....

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2017-07-05 15-20-27

@PVince81 test side effect bullshit as usual or real issue ❓

**Comment by PVince81** [comment]
might be the bullshit one... I didn't rebase this PR yet on a version that doesn't have this

**Comment by PVince81** [comment]
wait... you did rebase 😢 

I don't see how it could be related

**Comment by PVince81** [comment]
it's indeed the bullshit zombie fail, PR to annihilate it: https://github.com/owncloud/core/pull/28310

**Pull request closed without merging**
