### PR TITLE
[stable10] Occ repair list and single run command

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/core/pull/29830 to stable10

### CODE REVIEW

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
lets first get the pr to master merged - THX

**Comment by tomneedham** [comment]
Sure - need it for testing something

**Comment by PVince81** [comment]
is there still interest in getting this finished ?

**Comment by PVince81** [comment]
master PR not finished, closing. can be backported again later if finished

**Pull request closed without merging**
