### PR TITLE
[oc8.1] owner is stored as 'uid_owner', not as 'owner' in the oc_share table

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/owncloud/core/pull/17327

cc @MorrisJobke

### CODE REVIEW

**Comment by schiesbn** [comment]
cc @blizzz 8.1 backport from our fix, please review. Thanks!

**Comment by MorrisJobke** [comment]
I think time for 8.1.0 is over. the git tag is already there https://github.com/owncloud/core/releases

**Comment by schiesbn** [comment]
didn't saw the tag... Thanks for updating the milestone

**Comment by blizzz** [comment]
Next maintenance is fine, not critical.

**Comment by karlitschek** [comment]
:+1: backport is fine

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
