### PR TITLE
Set files_app table head position to fixed

### LINKED ISSUE #29118: Files view: Freeze top bar
**Freeze top bar (red)**
If you have many items in the file view you have to scroll. Currently the top bar (with column names) vanishes when scrolling down. We should freeze it for that it stays and column names are always visible.

Please ignore the blue stuff on the image below.

top_bar

@PVince81 @felixheidecke Please assign.

### PR DESCRIPTION
**Pull request by lordelix**
## Description
The table head in files-app stays put if files list is scrolled.

## Related Issue

Fixes: https://github.com/owncloud/core/issues/29118
Fixes: https://github.com/owncloud/enterprise/issues/1776

## Motivation and Context

If you have many items in the file view you have to scroll. Currently the top bar (with column names) vanishes when scrolling down.

## How Has This Been Tested?

Visual test in MacOS / Windows Firefox, Chrome and IE11

## Screenshots (if appropriate):
29118-filesapp-fixed-top-bar

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
ohhh, so it does work ? does it integrate properly with the sidebar when opened and also mobile view ?

**Comment by PVince81** [comment]
please also test dragging a file from the bottom, the list must still scroll up/down when stopping at the top

**Comment by felixheidecke** [comment]
Sidebar and mobile devices work fine as well as dragging and dropping. The latter is a bit choppy, but that's not new ;-)

**Comment by phil-davis** [comment]
There are automated UI tests that scroll the files list, drag-and-drop files up-and-down... so it will be interesting to see if they still pass.

**Comment by phil-davis** [comment]
A rename files UI test fails trying to rename a file at the very end of the list. I can reproduce the problem manually:
1) Scroll to the bottom of the list
2) Click the "..." Actions menu
3) Hover over "Rename" Delete" etc - they cannot be clicked.

Whichever items on the Actions menu are in the "empty space" below the actual file list, those cannot be clicked.

Video of original working behavior in master:
files-actionmenu-master

and the changed behavior where Action menu items are not clickable:
files-actionmenu-changed

**Comment by davitol** [comment]
Using Safari for iPad in iOS11:

1. Open hamburger left menu
2. Scroll files

screenrecording_11-06-2017 09_35

**Comment by davitol** [comment]
Using IE11 as browser, Size and modifed words seems to be out of place moved from the column when opening the sidebar:

With this fix:

screen shot 2017-11-06 at 10 53 00


Previously:

screen shot 2017-11-06 at 10 52 31

**Comment by phil-davis** [comment]
Latest issue:
```
 Scenario: Delete multiple files at once                             # /home/[secure]/build/owncloud/core/tests/ui/features/trashbin/delete.feature:60

    When I batch delete these files                                   # FilesContext::iBatchDeleteTheseFiles()

      | name          |

      | data.zip      |

      | lorem.txt     |

      | simple-folder |

      exception 'WebDriver\Exception\UnknownError' with message 'unknown error: Element <a href="" class="delete-selected" data-original-title="" title="">...</a> is not clickable at point (981, 63). Other element would receive the click: <div id="controls" style="width: 770px; min-width: 770px;">...</div>

        (Session info: chrome=62.0.3202.62)

        (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.10586 x86_64)' in /home/[secure]/build/owncloud/core/lib/composer/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
```
To reproduce manually:
1) Login to the files page
2) Select one or more files or folders by clicking their icon
The file list headings disappear (OK I guess).
The bar that displays the number of files/folders selected and gives you the chance to download or delete them does not appear. There is just a bit of empty space.

**Comment by davitol** [comment]
@felixheidecke Selecting a file, the head bar disappears

desaparece

**Comment by davitol** [comment]
Also selecting from the head bar

desap2

**Comment by phil-davis** [comment]
That is the items in my post above, which failed the automated UI tests - same behavior problems.

**Comment by felixheidecke** [comment]
My initial euphoria has been tainted a bit since there are issues in IE11 and caveats which are really annoying and not easy to fix. Some of them can be contributed to old jquery plugins and ancient JS/CSS in the files_app.

We better move this to planned since this might come around and bite us (me) in the ass 😞

**Comment by pmaier1** [comment]
What's the plan here?

**Comment by felixheidecke** [comment]
> What's the plan here?

@pmaier1  … we could make this a *"all browsers but iE11"* feature. I could do some JavaScript semi-magic here to support IE11 but it would introduce a lag in the UI while resizing and we don't want that.

**Comment by PVince81** [comment]
I'd be fine to have people who use less modern browsers get a less modern experience. Not a friend of extensive JS hacks for IE11...

**Comment by pmaier1** [comment]
> I'd be fine to have people who use less modern browsers get a less modern experience. Not a friend of extensive JS hacks for IE11...

Agree!

**Comment by PVince81** [comment]
- [ ] BUG: one pixel is sneaking through
image

Chromium 63

**Comment by PVince81** [comment]
if this is still a prioritiy we need to finish this. there are still problems with the current PR

**Comment by PVince81** [comment]
@pmaier1 I'd like to close this.

any cosmetic enhancements like this to be reconsidered in [phoenix](https://github.com/owncloud/phoenix)

**Comment by pmaier1** [comment]
:+1:

**Pull request closed without merging**
