### PR TITLE
Files_Versions don't show when the files are erased

### PR DESCRIPTION
**Pull request by cdamken**
Upgrading the log level From Debug to INFO to be consistent with files_trashbin

### CODE REVIEW

**Comment by felixboehm** [comment]
👍

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@cdamken Thanks a lot for your contribution!

Does this fix any issue here on github? Please reference.

please submit PRs for stable9.1 und stable9 branches - THX

**Comment by cdamken** [comment]
> Does this fix any issue here on github? Please reference.

It does not fix the issue, but I'm working in https://github.com/owncloud/enterprise/issues/1279 and I saw that I have logs from the `files_trashbin` but none from `files_versions`

This probably will help me to monitor the cleanup in the cronjob

**Comment by cdamken** [comment]
Not sure if I did it right but:
For 9.0 - https://github.com/owncloud/core/pull/25370
For 9.1 - https://github.com/owncloud/core/pull/25369

**Comment by PVince81** [comment]
@cdamken you need to create a new branch before doing the backport PR.
Start with stable9.1, create a branch, put your fix on it (git cherry-pick or patch it), then push, then submit a PR from that branch to stable9.1.

It looks like you tried to submit a PR directly from the master branch, which is wrong.
Let me know if you need help on IRC #owncloud-dev

**Comment by PVince81** [comment]
@cdamken thanks for the backports. We also need one to stable9.1. (master is 9.2)

**Comment by cdamken** [comment]
@PVince81 I think I committed that yesterday:

https://github.com/owncloud/core/commit/19cf727a0f055246c83317ff745b2a64a414b063

But I'm not sure what I did :smile: I never used Sourcetree before. @michaelstingl Just show me how to use it.

Should I do it again?

**Comment by VicDeo** [comment]
@cdamken  no, thanks
here it is 
stable9.1: https://github.com/owncloud/core/pull/25377

**Comment by michaelstingl** [comment]
@cdamken overestimates his powers – he thinks he is Chuck Norris and don't need to do pr's 😆

**Comment by cdamken** [comment]
:see_no_evil: Ups I did't again!

@PVince81 do you remember I did that b4 :smiling_imp: 

I will do it in the future like a normal person :)

**Comment by DeepDiver1975** [comment]
backport are done to all stable branches afaik

**Comment by PVince81** [comment]
@cdamken yes, don't be Chuck Norris.

**Pull request merged**
