### PR TITLE
Use StringUtils::equals on CSRF token and add unit tests

### PR DESCRIPTION
**Pull request by LukasReschke**
Neat small hardening. - And unit tests are always nice to have. Function was completely untested…

### CODE REVIEW

**Comment by LukasReschke** [comment]
Seems like it doesn't like this on older PHP versions. Will look into it,

**Comment by LukasReschke** [comment]
Good old https://bugs.php.net/bug.php?id=66773

**Comment by Xenopathic** [comment]
Fun fact: the new code isn't broken. It's the code in `lib/private/security/crypto.php`. Why that decided to blow up now, I have no idea.

**Comment by LukasReschke** [comment]
Let's see if the last change suffices for https://bugs.php.net/bug.php?id=66773 …

**Comment by LukasReschke** [comment]
CI is happy now. 

@Xenopathic @MorrisJobke Mind to review?

**Comment by Xenopathic** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
