### PR TITLE
Revert "[stable10] Backpot of Fix visibility of static tags in the tags page"

### PR DESCRIPTION
**Pull request by sharidas**
Reverts owncloud/core#34116

### CODE REVIEW

**Comment by sharidas** [comment]
Original PR: https://github.com/owncloud/core/pull/34575

**Comment by PVince81** [comment]
ci failed?

**Comment by sharidas** [comment]
CI is green now.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
note: I've already removed this from today's changelog https://github.com/owncloud/core/pull/34602

**Pull request merged**
