### PR TITLE
Add mimetype to OCS Share API output

### LINKED ISSUE #23044: ownCloud 9: missing document icons in filter views
### Steps to reproduce
1. Upgrade from ownCloud 8.2.2 to 9.0
2. Share a file (e.g. a pdf file) by link
3. Open the view "shared by link"

### Expected behaviour
The document icon (e.g. pdf-symbol) and the name of the shared document is shown.

### Actual behaviour
Only the document name is shown. There are no document symbols. Logs are empty. Symbols for shared folders are displayed correctly. 

### Server configuration
**Operating system**: Embedded QNAP Linux

**Web server:** Apache 2.4.12

**Database:** MariaDB 5.5

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0

**Updated from an older ownCloud or fresh install:** Upgraded from 8.2.2

**Signing status (ownCloud 9.0 and above):** "No errors have been found."

**List of activated apps:**
Calendar 1.0
Contacts 1.0

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #23044

Was missed during the conversion of the API and apparently no tests in place. (they are now)

@BenS89 please verify

CC: @LukasReschke @PVince81 @nickvergessen @MorrisJobke

### CODE REVIEW

**Comment by rullzer** [comment]
@karlitschek trivial patch but fixes some UX. Backport to 9.0.1 makes sense to me.

**Comment by karlitschek** [comment]
backport makes sense :+1:

**Comment by BenS89** [comment]
@rullzer that did the trick. Thanks for fixing the issue with this PR.

**Comment by rullzer** [comment]
stable9 in #23060

**Comment by MorrisJobke** [comment]
:+1:

**Comment by nickvergessen** [comment]
Can we add that to the integration test?

**Comment by DeepDiver1975** [comment]
> Can we add that to the integration test?

@rullzer

**Comment by rullzer** [comment]
Yes good point. let me add that.

**Comment by rullzer** [comment]
Intergration tests added.

**Comment by MorrisJobke** [comment]
```
Feature: federated

  Background:                   # /ssd/jenkins/workspace/ocs-api-integration-tests-ci/build/integration/federation_features/federated.feature:2
    Given using api version "1" # FederationContext::usingApiVersion()

  Scenario: Federate share a file with another server                                                    # /ssd/jenkins/workspace/ocs-api-integration-tests-ci/build/integration/federation_features/federated.feature:5
    Given Using server "REMOTE"                                                                          # FederationContext::usingServer()
[Thu Mar 10 08:34:45 2016] ::1:38866 [404]: /ocs/v2.php/cloud/users/user1
[Thu Mar 10 08:34:46 2016] ::1:38880 [200]: /ocs/v1.php/cloud/users
[Thu Mar 10 08:34:48 2016] ::1:38888 [200]: /ocs/v1.php/cloud/users/user1
[Thu Mar 10 08:34:49 2016] ::1:38900 [200]: /ocs/v2.php/cloud/users/user1
    And user "user1" exists                                                                              # FederationContext::assureUserExists()
    And Using server "LOCAL"                                                                             # FederationContext::usingServer()
[Thu Mar 10 08:34:49 2016] ::1:33709 [404]: /ocs/v2.php/cloud/users/user0
[Thu Mar 10 08:34:50 2016] ::1:33715 [200]: /ocs/v1.php/cloud/users
Build timed out (after 20 minutes). Marking the build as aborted.
Build was aborted
Regular expression run condition: Expression=[origin/master|origin/stable\d+(\.\d+)?], Label=[origin/fix_23044]
Run condition [Regular expression match] preventing perform for step [[E-mail Notification]]
Recording test results
    And user "user0" exists                                                                              # FederationContext::assureUserExists()
      cURL error 52: Empty reply from server (GuzzleHttp\Exception\ConnectException)
    When User "user0" from server "LOCAL" shares "/textfile0.txt" with user "user1" from server "REMOTE" # FederationContext::federateSharing()
    Then the OCS status code should be "100"                                                             # FederationContext::theOCSStatusCodeShouldBe()
    And the HTTP status code should be "200"                                                             # FederationContext::theHTTPStatusCodeShouldBe()
  │
  ╳  cURL error 56: Recv failure: Connection reset by peer (GuzzleHttp\Exception\RequestException)
  │
  └─ @AfterScenario # FederationContext::cleanupUsers()
```


@rullzer Simply rerun? Or is this an actual failure?

**Comment by rullzer** [comment]
`Build timed out (after 20 minutes). Marking the build as aborted.`

@MorrisJobke it is a timeout... @DeepDiver1975 is already notified.

**Comment by DeepDiver1975** [comment]
> @MorrisJobke it is a timeout... @DeepDiver1975 is already notified.

incremented to 30 minutes

**Comment by rullzer** [comment]
Thanks @DeepDiver1975 

Rebased to retrigger CI

**Pull request merged**
