### PR TITLE
Replace getServer by querying the public interface for share app

### PR DESCRIPTION
**Pull request by LEDfan**
Since #12830 a lot of debug messages are posted in the owncloud.log.

cc @Raydiation

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Using the getters on the $server object is perfectly fine and shall not cause these debug messages.

Following code snippet wold cause the debug message:

```php
$c->query('ServerContainer');
```

calling $c->getServer() how ever shall not cause this error from my understanding.
Unfortunatly getServer() is calling query('ServerContainer')

@Raydiation I vote for removing the debug message completly and let's rethink this for 8.1.
getServer() would be implicit deprecated by this. THX

**Comment by Raydiation** [comment]
Good idea. One of the goals should also be to not fail to instantiate the container if OC::$server is not accessible, e.g. in unit tests. We should probably just move it into a getter in the container and use that one. Will start to work on a PR

**Comment by DeepDiver1975** [comment]
> Will start to work on a PR

thanks a lot!

**Comment by DeepDiver1975** [comment]
@LEDfan thanks for bringing up this issue! Much appreciated! I'll close this in favor of @Raydiation 's upcoming PR

**Comment by LEDfan** [comment]
Okay thanks for solving :)

**Pull request closed without merging**
