### PR TITLE
[Tests-Only] Enable testRecursive in Archive/TARTest.php

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
- Re-enable this unit test which was disabled in PR #35693

- Move the data files that are used by these `lib/Archive` tests into a new folder `tests/data/archive`
  Note: `data.tar.gz` and `data.zip` are only used by these `Archive` tests, so those files have been moved. `lorem.txt` is used by other tests, so I made a copy of it in `tests/data/archive`

- Refactor the test code to avoid repeating `tests/data/archive` in so many places.

## Related Issue
#35685

## How Has This Been Tested?
With the test disabled:
```
make test-php-unit TEST_PHP_SUITE=tests/lib/Archive/TARTest.php
/home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/phpunit --configuration phpunit-autotest.xml --log-junit autotest-results-sqlite.xml ../tests/lib/Archive/TARTest.php 
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.9.2
Configuration: /home/phil/git/owncloud/core/tests/phpunit-autotest.xml

.........                                                           9 / 9 (100%)

Time: 120 ms, Memory: 16.00 MB

OK (9 tests, 53 assertions)
```

With the test enabled:
```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.9.2
Configuration: /home/phil/git/owncloud/core/tests/phpunit-autotest.xml

.........                                                           9 / 9 (100%)

Time: 49.14 seconds, Memory: 18.00 MB

OK (9 tests, 55 assertions)
```

It takes a lot longer to run, but does not use much more memory.

After moving the test data into `tests/data/archive`
```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.33-12+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.9.2
Configuration: /home/phil/git/owncloud/core/tests/phpunit-autotest.xml

..................                                                18 / 18 (100%)

Time: 155 ms, Memory: 16.00 MB

OK (18 tests, 110 assertions)
```
It is much faster because `testRecursive` is now only recursively creating a tar with the specific 3 test files that it intends to test. Previously it was recursively adding all files in `tests/data`, which has grown over time to be big.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/23772/15/10
```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Runtime:       PHPDBG 7.1.33-9+ubuntu18.04.1+deb.sury.org+1
Configuration: /drone/src/tests/phpunit-autotest.xml

.............................................................   61 / 9959 (  0%)
........................S....................................  122 / 9959 (  1%)
.............................................................  183 / 9959 (  1%)
.............................................................  244 / 9959 (  2%)
.............................................................  305 / 9959 (  3%)
.............................................................  366 / 9959 (  3%)
.............................................................  427 / 9959 (  4%)
.............................................................  488 / 9959 (  4%)
.............................................................  549 / 9959 (  5%)
.............................................................  610 / 9959 (  6%)
.............................................................  671 / 9959 (  6%)
.............................................................  732 / 9959 (  7%)
........................................
[PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 65536 bytes) in /drone/src/lib/composer/pear/archive_tar/Archive/Tar.php on line 2275]
[PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 65536 bytes) in /drone/src/lib/private/Shutdown/ShutDownManager.php on line 58]
```

That is sad - something different in drone that eats up 4GB memory.

**Comment by phil-davis** [comment]
It tried again locally with PHP 7.1
```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.33-12+ubuntu18.04.1+deb.sury.org+1 with Xdebug 2.9.2
Configuration: /home/phil/git/owncloud/core/tests/phpunit-autotest.xml

.........                                                           9 / 9 (100%)

Time: 50.65 seconds, Memory: 16.00 MB

OK (9 tests, 55 assertions)
```
It is happy, and if I run the whole unit test suite (similar to in drone), it also gets past that `732 / 9959` fine.

**Comment by phil-davis** [comment]
And locally with `phpdbg`
```
phpdbg -d memory_limit=4096M -rr ./lib/composer/bin/phpunit --configuration tests/phpunit-autotest.xml
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Runtime:       PHPDBG 7.1.33-12+ubuntu18.04.1+deb.sury.org+1
Configuration: /home/phil/git/owncloud/core/tests/phpunit-autotest.xml

.............................................................   61 / 7209 (  0%)
........................S....................................  122 / 7209 (  1%)
.............................................................  183 / 7209 (  2%)
.............................................................  244 / 7209 (  3%)
.............................................................  305 / 7209 (  4%)
.............................................................  366 / 7209 (  5%)
.............................................................  427 / 7209 (  5%)
.............................................................  488 / 7209 (  6%)
.............................................................  549 / 7209 (  7%)
.............................................................  610 / 7209 (  8%)
.............................................................  671 / 7209 (  9%)
.............................................................  732 / 7209 ( 10%)
.............................................................  793 / 7209 ( 11%)
...
Time: 3.12 minutes, Memory: 248.00 MB
```
That uses more memory, but still nowhere near the 4GB limit.

**Comment by phil-davis** [comment]
@micbar @individual-it please call in whoever else you feel needs to review this.

**Review by individual-it — APPROVED** [review]

**Pull request merged**
