### PR TITLE
Revert "[stable10] Bump small stuff"

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Reverts owncloud/core#31686

We are in freeze on stable10 - forgot about this. :crying_cat_face:

### CODE REVIEW

**Comment by phil-davis** [comment]
:( - and I thought that we could get these little things bumped up to current versions in 10.0.9.

**Comment by DeepDiver1975** [comment]
> :( - and I thought that we could get these little things bumped up to current versions in 10.0.9.

if merged yesterday: yes
today: no

**Comment by phil-davis** [comment]
I would have merged it yesterday, and nobody reviewed/approved it :(

**Comment by DeepDiver1975** [comment]
> "what to do?"

nothing - shit happens

**Comment by DeepDiver1975** [comment]
lib bumps got tested within the RC - no need to revert them anymore

**Pull request closed without merging**
