### PR TITLE
The header title and claim is rendered as escaped HTML in files_sharing public template.

### LINKED ISSUE #40605: The header title and claim is rendered as escaped HTML in files_sharing public template.
### Steps to reproduce
1. Use the owncloud theme-example as theme
2. Access the public page of any shared link

### Expected behaviour
The header title and claim must be rendered as HTML.
Captura de pantalla 2023-01-27 a las 9 02 36

### Actual behaviour
The header title and claim is rendered as escaped HTML.
Captura de pantalla 2023-01-27 a las 8 59 41

### Server configuration
**Operating system**:
Debian

**Web server:**
Apache

**Database:**
MariaDb

**PHP version:**
7.4.33

**ownCloud version:**
10.11.0 and latest master

**Updated from an older ownCloud or fresh install:**
Both

**Where did you install ownCloud from:**
http://download.opensuse.org/repositories/isv:/ownCloud:/server:/10/Debian_11/ and https://github.com/owncloud/

### Client configuration
**Browser:**
All

**Operating system:**
All

### PR DESCRIPTION
**Pull request by ocubom**
## Description
The files_sharing public template escaped the Theme HTML title and claim. The raw HTML markup is shown.

## Related Issue

- Fixes #40605 

## Motivation and Context
The header in the public pages shows raw HTML code instead of the theme markup requested.

## How Has This Been Tested?
Check with a browser that it doesn't show the HTML markup.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/37771/4/2
`file changelog/unreleased/40606: title is too long (max 80 characters)`

**Review by jvillafanez — APPROVED** [review]
I'm approving for consistency with other places, but I think it's a security risk and it should be restricted (no HTML should be allowed)

**Comment by ocubom** [comment]
The values are provided by the OC_Theme::getHTMLName() and OC_Theme::getLogoClaim() methods of the active theme. They are not dynamic values provided by a user, but by the owncloud admin.

If this is an issue, both methods should be deprecated. In the first case the replacement would be OC_Theme::getName. The second has no substitute.

**Review by phil-davis — APPROVED** [review]
The HTML set in the theme is done by an admin, it is not external-user-provided data. So, IMO, we trust that the admin only does sensible/reasonable things when setting up the theme.

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
