### PR TITLE
[stable9] Fix PHP memory leak in file_get_contents()

### LINKED ISSUE #20261: Desktop sync fails with big files (OC 8.2.0, client 2.0.2)
Hi,

I'm having a trouble uploading a 9GB file using desktop sync client 2.0.2 (and owncloud 8.2.0).

The uploading goes well but when uploading is done, owncloud starts to assemble the file. During the assembly a temporary file is created in the user's files folder.

Then, for some reason, the desktop client tries to sync the temporary file, it fails and syncing is restarted (including uploading of the 9GB file or at least the missing bits).

I have filesystem_check_changes = 0. Shouldn't it prevent stuff like this?

Would it be better to assemble the final file in the cache folder and then move the file to files folder after assembly is done?

### PR DESCRIPTION
**Pull request by MorrisJobke**
- ref https://bugs.php.net/bug.php?id=61961
- ref https://github.com/owncloud/core/issues/20261#issuecomment-180000256
- code is based on the proposal of @chriseqipe
- fixes #20261 
- backport of #23304 
- approval in https://github.com/owncloud/core/pull/23304#issuecomment-205338565

@LukasReschke @nickvergessen @icewind1991 @rullzer @PVince81 Please review

### CODE REVIEW

**Comment by skjnldsv** [comment]
:+1: Ok here.

**Comment by icewind1991** [comment]
:+1:

**Comment by nickvergessen** [comment]
:-1: https://github.com/owncloud/core/pull/23304#issuecomment-207418014

**Comment by MorrisJobke** [comment]
> #23304 (comment)

I cherry picked your fix from #23860 and it works now :)

**Comment by MorrisJobke** [comment]
> #23304 (comment)

fixed meanwhile.

**Comment by nickvergessen** [comment]
:+1: for not my commit

**Comment by MorrisJobke** [comment]
I tested @nickvergessen's commit 👍

**Pull request merged**
