### PR TITLE
[stable10] Verify checksum fixes 

### PR DESCRIPTION
**Pull request by IljaN**
Backport of #31430

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
