### PR TITLE
Require to use at least desktop client 2.0 by default

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

asking for desktop client 2.0.0 as minimum by default
## Motivation and Context

Force people to update in order to protect them from evil.
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Jenkins hates you

**Comment by PVince81** [comment]
Wow, we actually have tests for that:
```
15:17:26 1) OCA\DAV\Tests\unit\Connector\Sabre\BlockLegacyClientPluginTest::testBeforeHandlerException with data set #0 ('Mozilla/5.0 (1.5.0) mirall/1.5.0')
15:17:26 Expectation failed for method name is equal to <string:getSystemValue> when invoked 1 time(s)
15:17:26 Parameter 1 for invocation OCP\IConfig::getSystemValue('minimum.supported.desktop.version', '2.0.0') does not match expected value.
15:17:26 Failed asserting that two strings are equal.
15:17:26 --- Expected
15:17:26 +++ Actual
15:17:26 @@ @@
15:17:26 -'1.7.0'
15:17:26 +'2.0.0'
```

**Comment by LukasReschke** [comment]
> Wow, we actually have tests for that:

Of course. I have written that file 😉

**Comment by RealRancor** [comment]
What about https://github.com/owncloud/core/blob/master/config/config.sample.php#L1150 ? :-)

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
