### PR TITLE
Hack to prevent infinite loop with LDAP + logging

### PR DESCRIPTION
**Pull request by PVince81**
Forward port of a50619200c6a08929dbe802118a6afadb376b866 to 9.1/master

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/24467

Please review @owncloud/ldap @SergioBertolinSG @davitol 

To reproduce the original issue, make sure to have "loglevel => 0" and login with a LDAP user.
On this PR logging in works again.

**Comment by PVince81** [comment]
also @nickvergessen @rullzer @MorrisJobke @LukasReschke

**Comment by nickvergessen** [comment]
:+1: untested, but worked in 9.0

**Comment by SergioBertolinSG** [comment]
👎  Can't login using a LDAP user in this branch.

```
{"reqId":"nhnP9z+DiJGbdeqE13L1","remoteAddr":"HIDDEN_IP","app":"core","message":"Login failed: 'aaliyah_adams' (Remote IP: 'HIDDEN_IP')","level":2,"time":"2016-05-25T16:40:11+00:00","method":"POST","url":"\/index.php\/login?user=aaliyah_maggio","user":"--"}
{"reqId":"XqLAQuv4yJnyH3YDc\/dl","remoteAddr":"HIDDEN_IP","app":"PHP","message":"Undefined offset: 1 at \/opt\/owncloud\/core\/Controller\/LoginController.php#118","level":3,"time":"2016-05-25T16:40:11+00:00","method":"GET","url":"\/index.php\/login?user=aaliyah_adams","user":"--"}
{"reqId":"XqLAQuv4yJnyH3YDc\/dl","remoteAddr":"HIDDEN_IP","app":"PHP","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/core\/templates\/login.php#23","level":3,"time":"2016-05-25T16:40:11+00:00","method":"GET","url":"\/index.php\/login?user=aaliyah_adams","user":"--"}
```

Seems like the urls are mixing previous and current user?

**Comment by davicente** [comment]
For me loging in is working with LDAP user. But it generates an infinite loop when I log out the first time.

`{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b8ea61b6-8742-1034-8cef-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => uid=aaliyah_dach,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => uid=aaliyah_dach,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b8ea9d16-8742-1034-8cf0-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => uid=aaliyah_dach_ii,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => uid=aaliyah_dach_ii,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b8eaba6c-8742-1034-8cf1-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => uid=aaliyah_daniel,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => uid=aaliyah_daniel,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"} {"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}`

**Comment by PVince81** [comment]
Log out also works for me properly.

@davicente can you double check ? Maybe make sure cookies are cleared before testing, maybe you had an old session or something.

**Comment by PVince81** [comment]
Since this solves log in which is a more important use case than log out, I'm going to merge this.

@davicente if you're still seeing an issue with logging out, please make a new ticket. Thanks.

**Comment by davicente** [comment]
Tested in a clean docker works ok
:+1:

**Pull request merged**
