### PR TITLE
Cache non-existing accounts

### PR DESCRIPTION
**Pull request by butonic**
followup to https://github.com/owncloud/core/pull/27068

### CODE REVIEW

**Comment by butonic** [comment]
hm jenkins failed on oracle, the other dbs were ok

**Comment by PVince81** [comment]
@butonic I'd appreciate at least a quick explanation why the last PR wasn't enough and what this commit is doing, for posterity. Normally as per the PR template you should provide way more information than just a single line.

**Comment by butonic** [comment]
@PVince81 This pr prevents the user manager from eating memory by using a capped cache. Helps when iterating over all users.

**Comment by PVince81** [comment]
deja vu... or maybe it's the same code I reviewed a while ago and it didn't have a capped cache ?

code looks fine.

ready for review ? (status is still "developing")

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
