### PR TITLE
Add quality setting for JP(E)G preview images

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
A new config setting `previewJPEGImageDisplayQuality` has been introduced with which the quality of generated JP(E)G previews can be determined.

## Related Issue

- Relates to https://github.com/owncloud/enterprise/issues/4702

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [x] Documentation ticket raised: https://github.com/owncloud/docs/issues/4142
- [x] Changelog item

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-10.7.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33012/110/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIWebdavLockProt-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33012/150/1

**Review by phil-davis — COMMENTED** [review]
Just a small typo.

**Comment by JanAckermann** [comment]
@JammingBen what do you think about adding the \imagejpeg PHP docs to the config.sample.php description?

**Comment by JammingBen** [comment]
At first sight I couldn't find a nice way to actually analyse the quality of an JPEG image via PHP. The quality string is included somewhere in the response body, but it seems a bit "random" to me. For now I added a test to check for the file size.

**Comment by mmattel** [comment]
> ...Previews will always be stored as png file on the local disk. Therefore it will always have "full quality", regardless out the newly introduced setting...

Then the config parameter should be renamed to avoid misleading and confusement.

**Review by phil-davis — APPROVED** [review]

**Review by JammingBen — APPROVED** [review]

**Comment by mmattel** [comment]
@JammingBen I have adopted the config.sample text above based on the discussion. Please have a look and commit in case you agree.

**Comment by JammingBen** [comment]
> is there a need for recreation?

No, that change will be applied immediately.

> @JammingBen I have adopted the config.sample text above based on the discussion. Please have a look and commit in case you agree.

Hm I cannot find it, could you link the comment here please? I only see your first review on the outdated text.

**Comment by JammingBen** [comment]
It's not showing for me :/

image

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
