### PR TITLE
[stable10] Use sabre/vobject ^4.2 to fix issues in ITip messages

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Generated ITip messages are missing the timezone information.
This results in invalid ics messages which can cause issues with clients receiving these messages - e.g. MS Exchange

## Related Issue
- refs … https://github.com/sabre-io/vobject/pull/412

## How Has This Been Tested?
- generate event in calendar app
- add attendee's email address
- receive the invite
- validate the ics attachment is valid - https://icalendar.org/validator.html
- edit the event & save
- receive update email
- validate the ics attachment is valid - https://icalendar.org/validator.html
- delete the event
- receive cancel email
- validate the ics attachment is valid - https://icalendar.org/validator.html

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Master does not need this change - sabre/dav already pulls in the correct version

**Comment by PVince81** [comment]
do we really want to depend on alpha libraries ?

**Comment by DeepDiver1975** [comment]
> do we really want to depend on alpha libraries 

good point - will do a final release ...... THX for pointing out

**Comment by DeepDiver1975** [comment]
> good point - will do a final release ...... THX for pointing out

https://github.com/sabre-io/vobject/pull/446

**Comment by phil-davis** [comment]
See PR #34564 for implementing the official `sabre/vobject` `4.2.0` in `master`. Something like that will need to be added to this PR.

**Comment by DeepDiver1975** [comment]
Already incorporated

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@DeepDiver1975 port to master ?

**Comment by DeepDiver1975** [comment]
Phil already Took Care of master. Pr is linked

**Pull request merged**
