### PR TITLE
remove border from button style

### PR DESCRIPTION
**Pull request by jancborchardt**
What do you think @owncloud/designers @karlitschek @schiesbn @nickvergessen?

### CODE REVIEW

**Comment by nickvergessen** [comment]
@jancborchardt mind adding screenshots when you change stuff, so we don't have to check out the branch, interrupting our work?

**Comment by PVince81** [comment]
I find it a bit too light/soft, at least with the current general styling of the UI. Did you intend this to fit with one of your other experiments ?
test-button

**Comment by karlitschek** [comment]
nice :+1:

**Comment by jancborchardt** [comment]
@PVince81 if it’s darker, it looks disabled. Lighter isn’t easily visible anymore.
It should fit with the general style of the coming changes to the left sidebar, yes. But also standalone I already think it’s much better.

@nickvergessen @MorrisJobke another review please?

**Comment by MorrisJobke** [comment]
I also like it :+1:

**Comment by davitol** [comment]
IMHO It should be a little bit darker. Using for example Firefox, it is not very clear which option is selected.

e.g.  AND / OR in File Firewall

file firewall

**Comment by nickvergessen** [comment]
@davitol we might fix that differently

**Comment by davitol** [comment]
What about the searchbox in community version? Maybe it is need more contrast too or code it in the same way as the EE version

searchtb

**Comment by jancborchardt** [comment]
@davitol check latest master regarding the search box. :)

**Pull request merged**
