### PR TITLE
[External storage - Google Drive] skip google map files

### PR DESCRIPTION
**Pull request by lanato**
Possible fix for #24253 by ignoring google map files

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks a lot! Now for the official stuff, you need to either pick the MIT license by stating it or sign the CLA:

"
Thanks a lot for your contribution!
Contributions to the core repo require a signed contributors agreement http://owncloud.org/about/contributor-agreement/

Alternatively you can add a comment here where you state that this contribution is MIT licensed.

Some more details about out pull request workflow can be found here: http://owncloud.org/code-reviews-on-github/
"

Am currently busy with other stuff but I'll try and test this in the context of 9.1. :smile:

**Comment by altyr** [comment]
This contribution licensed under the MIT License

**Comment by PVince81** [comment]
@altyr don't mind the drunken bot... sorry.

**Comment by PVince81** [comment]
Damn, second time I try to test this and bump against https://github.com/owncloud/core/issues/24407

**Comment by PVince81** [comment]
Tested together with the SSL fix https://github.com/owncloud/core/pull/24630

Works fine :+1: 

Second review ? @Xenopathic @icewind1991

**Comment by PVince81** [comment]
Can we merge this ? Quick one... @Xenopathic @icewind1991

**Comment by PVince81** [comment]
@altyr ah, it's you too ! I didn't realize it was you who made these two PRs :smile: 
Great stuff

**Comment by PVince81** [comment]
Rebased, had to do it in a separate PR: https://github.com/owncloud/core/pull/24807
Let's continue there.

**Pull request closed without merging**
