### PR TITLE
Check for current user to have the same id then the owner of the config ...

### LINKED ISSUE #12307: occ should verify that it is run as web server user
To my understanding occ should verify that it is run as webserver user. Otherwise we might run into problems as soon as an action creates files which may then have the file permissions.

Also I think I remember some bug reports about data being gone when executed as the wrong user. - Can we somehow easily check whether the user is the web-server user? I can't think of an easy way to do that though.

Or am I completely missing something? - At least we should document that somehow or ensure that we don't mess with files.

@icewind1991 

@jnfrmarks As discussed.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
...file - fixes #12307 

@LukasReschke @PVince81 @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by DeepDiver1975** [comment]
I'm asking my self if this is a too hard check - shall we ask the user to continue on his own risk?

**Comment by LukasReschke** [comment]
I think this non-bypassable check is reasonable if we add some documentation about this. :+1:

@carlaschroder

**Comment by MorrisJobke** [comment]
I just checked again: `posix_getpwuid` isn't available in my PHP even if PHP is compiled with `--enable-posix=shared`. Ideas?

**Comment by MorrisJobke** [comment]
Ah. posix.so needs to be enabled. Can we add a check for this extension or should we enforce this extension just for this check?

**Comment by Xenopathic** [comment]
This breaks my workflow (I know, I know :laughing): I point my web server directly at my git repository, but use ACLs so that the web server can write to the important directories. Unfortunately after this PR I can no longer run `occ`. What about checking if `config.php`, or some other core object like `data/`, is writable? That is the real requirement here as I see it.

**Comment by DeepDiver1975** [comment]
> That is the real requirement here as I see it.

No - here is an example:

config.php is owned by www-data
root can write to config.php
in case files are touches by occ - the owner is getting changed to root
www-data can no longer access the changed files

**Comment by Xenopathic** [comment]
@DeepDiver1975 Ah, true. Perhaps it'd be best not to check the owner of config.php then, but rather a hidden unimportant file generated by oC, like `data/.ocdata`? Or will that cause issues when it comes to using an object store?

**Pull request merged**
