### PR TITLE
Properly DI the servercontainer into share provider factory

### PR DESCRIPTION
**Pull request by rullzer**
As suggested by @nickvergessen in https://github.com/owncloud/core/pull/21792#discussion_r50220031

Just less static usage!

Easy one to review.

CC: @schiesbn @PVince81 @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by PVince81** [comment]
You forgot to adjust the comment's "ManagerFactory" to make use of this.
Anyway, this PR shouldn't break it so it's fine for now.

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
