### PR TITLE
move fonts from Regular+Bold to Light+Semibold for lighter feel

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @owncloud/designers @karlitschek 

Before:
capture du 2015-08-24 16-20-04
After:
capture du 2015-08-24 16-15-16

### CODE REVIEW

**Comment by karlitschek** [comment]
nice. more light weight :+1:

**Comment by MorrisJobke** [comment]
@jancborchardt Looks like the test cases depend on those fonts. Please update them too.

**Comment by MorrisJobke** [comment]
Mmmh...looks here a bit to light. I would keep the regular font size. Also have a look at this on other PCs, because you have a high DPI device with enabled zoom. Try a regular PC or a smartphone too

**Comment by karlitschek** [comment]
@MorrisJobke You are soooo old school ;-)

**Comment by jancborchardt** [comment]
@MorrisJobke I did test it with normal settings and mobile as well. Of course light fonts are rendered correctly. :)

**Comment by jancborchardt** [comment]
Can we have some more reviewers @nickvergessen @PVince81 @schiesbn :)

**Comment by jancborchardt** [comment]
Folks, more reviews here please :) @owncloud/designers @oparoz @schiesbn @DeepDiver1975 @nickvergessen

**Comment by jancborchardt** [comment]
Folks, more reviews here please :) @owncloud/designers @oparoz @henni @schiesbn @DeepDiver1975 @nickvergessen

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by MorrisJobke** [comment]
Yep. Looks good :+1:

**Pull request merged**
