### PR TITLE
[stable8.2][WIP] decryption fixes and added logging

### PR DESCRIPTION
**Pull request by butonic**
cc @phisch

### CODE REVIEW

**Comment by butonic** [comment]
I'll add a commit to prevent changing fileids

**Comment by butonic** [comment]
```
14:19:21 There was 1 failure:
14:19:21 
14:19:21 1) Test\Encryption\DecryptAllTest::testDecryptFile
14:19:21 OC\Files\View::copy('test.txt.decrypted.42', 'test.txt', false) was not expected to be called more than once.
14:19:21 
14:19:21 /var/lib/jenkins/workspace/owncloud-core_core_PR-27385-HUMQYUKFGNM5LBKTC57RUFTOUGADL6U2R3QQLTW4N6SQXD3CRGKA@2/lib/private/encryption/decryptall.php:259
14:19:21 /var/lib/jenkins/workspace/owncloud-core_core_PR-27385-HUMQYUKFGNM5LBKTC57RUFTOUGADL6U2R3QQLTW4N6SQXD3CRGKA@2/tests/lib/testcase.php:100
14:19:21 /var/lib/jenkins/workspace/owncloud-core_core_PR-27385-HUMQYUKFGNM5LBKTC57RUFTOUGADL6U2R3QQLTW4N6SQXD3CRGKA@2/tests/lib/encryption/decryptalltest.php:300
```

**Comment by phisch** [comment]
Both tests fixed.

**Comment by phisch** [comment]
How is that a syntax error? https://travis-ci.org/owncloud/core/jobs/210996519#L258
Are you drunk, travis?

**Comment by DeepDiver1975** [comment]
php 5.4 has no understanding of ::class

**Comment by DeepDiver1975** [comment]
you are on 8.2 and php 5.4 is supported in this version

**Comment by DeepDiver1975** [comment]
````
PHP Fatal error:  Class 'Test\Encryption\FileInfo' not found in /var/lib/jenkins/workspace/owncloud-core_core_PR-27385-HUMQYUKFGNM5LBKTC57RUFTOUGADL6U2R3QQLTW4N6SQXD3CRGKA/tests/lib/encryption/decryptalltest.php on line 242
22:55:02 PHP Stack trace:
22:55:02 PHP   1. {main}() /usr/local/bin/phpunit:0
22:55:02 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:548
22:55:02 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:100
22:55:02 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:149
22:55:02 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:440
22:55:02 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:747
22:55:02 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:747
22:55:02 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:724
22:55:02 PHP   9. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:612
22:55:02 PHP  10. PHPUnit_Framework_TestCase->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:768
22:55:02 PHP  11. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:909
22:55:02 PHP  12. Test\Encryption\DecryptAllTest->testDecryptUsersFiles() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:909

**Comment by phisch** [comment]
added the missing use statement, should work now

**Comment by PVince81** [comment]
:+1:

Wasn't this a backport ? And it seems to have more code that we should then forward port.

**Comment by butonic** [comment]
There are some added log statements and decrytion no longer stops when a file cannot be decrypted. I am working with a customer to improve the error messages. will continuously update this PR. changed title to reflect WIP status

**Comment by PVince81** [comment]
is this close to completion or is still going to take a while ?

**Comment by PVince81** [comment]
abandon this ? not a security fix for 8.2 and 8.2 is EOL end of May.

if anything is useful for stable9 or stable9.1, please submit a PR there

**Comment by butonic** [comment]
let me work on this a little bit ... I will forward port / resubmit this agains master once the problem at the customer has been resolved

**Comment by butonic** [comment]
let me work on this a little bit ... I will forward port / resubmit this or parts of it against master once the problem at the customer has been resolved

**Comment by PVince81** [comment]
8.2 is dead, close?

**Comment by PVince81** [comment]
no feedback, closing this

**Pull request closed without merging**
