### PR TITLE
Require dg/composer-cleaner

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
By adding https://github.com/dg/composer-cleaner we can reduce the size of the release packages.
Let's give it a try.

## Related Issue
- @butonic opened an issue somewhere ....

## How Has This Been Tested?
- :robot: 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)
- [ ] find something similar for npm/yarn

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
please hold the backport as we want to see how it behaves on master

**Comment by phil-davis** [comment]
@PVince81 your comment is 2 months ago. Is this a "thing" that [can|should] be done for 10.1 ?

**Comment by PVince81** [comment]
let's continue holding. the current release scripts are already cleaning up quite a lot.

this PR would make it possible to remove the cleaning logic from the release scripts. and we'll need new release scripts for Semver anyway in the near future

**Comment by phil-davis** [comment]
Backport `stable10` #34784 - let's see if this "just works" in `stable10`

**Pull request merged**
