### PR TITLE
Refactoring tests test1

### PR DESCRIPTION
**Pull request by phil-davis**
Just try running these changes from @carusogabriel from a branch inside core repo and see of the CI passes from here.

### CODE REVIEW

**Comment by carusogabriel** [comment]
@phil-davis Good, will be easy to debug and found fails

**Comment by phil-davis** [comment]
@carusogabriel I don't think it will automatically update commits in this PR. But I can easily force pull-push any changes you make. Actually Jenkins and Drone jobs should run fine for you. It is only the Travis-SauceLabs UI tests that fail for you because they need access to a secure key for SauceLabs authentication. And Travis-Saucelabs has passed fine here.

**Comment by carusogabriel** [comment]
I’ve fix some test. Can you force push here to test them again? I guess now everything is ready

**Comment by phil-davis** [comment]
See #29754 for later code.

**Pull request closed without merging**
