### PR TITLE
[8.2] Fix trashbin wrapper when no user is loggedin

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/owncloud/core/pull/20081

### CODE REVIEW

**Comment by PVince81** [comment]
@icewind1991 please do mention people if you expect faster reviews

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Second reviewer @MorrisJobke @schiesbn ?

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
