### PR TITLE
[stable8] LDAP: make sure port input box is not getting too small on low width

### PR DESCRIPTION
**Pull request by blizzz**
It's a backport picked from refurbished wizard included in master/OC 8.1. Contains CSS format changes only.

@MorrisJobke @Kawohl @karlitschek

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and fixes the too small port field. :+1:

**Comment by MorrisJobke** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
@blizzz also cc your LDAP homies to review this please! :) We can’t have everything reviewed by only a small group of people, that doesn’t scale at all.

**Comment by MorrisJobke** [comment]
@rullzer @Xenopathic Can I ask you to review this? It's visible in the first step of the LDAP wizard, so there is no real need for an LDAP server. Only the port input field has to be wider than before ;)

**Comment by Xenopathic** [comment]
:+1:

**Pull request merged**
