### PR TITLE
Fix routes

### LINKED ISSUE #15913: Public sharing broken on master
@icewind1991 While fixing the namespace in https://github.com/owncloud/core/blob/557b4a2cb0ae0367e5facb1e4be136de07ab8cff/apps/files_sharing/appinfo/application.php you broke public sharing in core completely, please take a look at https://github.com/owncloud/core/blob/557b4a2cb0ae0367e5facb1e4be136de07ab8cff/core/routes.php#L111-L126

Regression by the ETag PR from https://github.com/owncloud/core/pull/14764

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes  https://github.com/owncloud/core/issues/15913

@icewind1991 Please review and test. Thx.

### CODE REVIEW

**Comment by PVince81** [comment]
Opening public link works now :+1:

**Comment by nickvergessen** [comment]
test? *me hides*

**Comment by PVince81** [comment]
Lukas said it here: https://github.com/owncloud/core/issues/15913#issuecomment-97048722

**Comment by nickvergessen** [comment]
I though we could just include the file, but we would need to call all those closures... didnt see them in first place

**Comment by icewind1991** [comment]
Makes sense :+1:

**Comment by DeepDiver1975** [comment]
Please somebody open a tech dept on unit testing routes.php and app.php - maybe we find a solution .... THX

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/issues/15917

**Pull request merged**
