### PR TITLE
Revert "Updating license headers"

### LINKED ISSUE #14524: Revert - update license header
It dropped some documentation for classes including deprecation marks.

#14403

@DeepDiver1975 Can you have a look?

### PR DESCRIPTION
**Pull request by MorrisJobke**
This reverts commit 6a1a4880f0d556fb090f19a5019fec31916f5c36.

cc @LukasReschke @DeepDiver1975 

fixes #14524

### CODE REVIEW

**Comment by MorrisJobke** [comment]
ref #14403

**Comment by MorrisJobke** [comment]
#14530

**Comment by DeepDiver1975** [comment]
ok - let's revert this an fix this properly - THX @MorrisJobke

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
