### PR TITLE
Switch the web UI to the new endpoint for logged in users

### PR DESCRIPTION
**Pull request by PVince81**
@DeepDiver1975 

To be tested fully.

Seems we also need more integration tests, found a bug already on root (will raise)

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] BUG: wrong perms in home node: https://github.com/owncloud/core/issues/25495

**Comment by PVince81** [comment]
- [ ] BUG: no permissions to upload in home folder: https://github.com/owncloud/core/issues/26064

**Comment by PVince81** [comment]
- [ ] make chunk size dependent on "max_upload_filesize"

**Comment by PVince81** [comment]
- [ ] BUG: missing favorite info: https://github.com/owncloud/core/pull/26098

**Comment by PVince81** [comment]
- [ ] BUG: missing share info, seems the plugin is missing there too

**Comment by PVince81** [comment]
and also comments plugin for "comments-unread":

```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns">
 <d:response>
  <d:href>/owncloud/remote.php/dav/files/admin/test/</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Thu, 22 Sep 2016 10:59:03 GMT</d:getlastmodified>
    <d:getetag>&quot;57e3b977111c7&quot;</d:getetag>
    <d:resourcetype>
     <d:collection/>
    </d:resourcetype>
    <oc:fileid>9</oc:fileid>
    <oc:permissions>RDNVCK</oc:permissions>
    <oc:size>0</oc:size>
    <oc:tags/>
    <oc:favorite>1</oc:favorite>
    <oc:owner-display-name>admin</oc:owner-display-name>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <d:getcontenttype/>
    <d:getcontentlength/>
    <oc:comments-unread/>
    <oc:share-types/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/owncloud/remote.php/dav/files/admin/test/abc/</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Thu, 22 Sep 2016 10:59:03 GMT</d:getlastmodified>
    <d:getetag>&quot;57e3b9770c56a&quot;</d:getetag>
    <d:resourcetype>
     <d:collection/>
    </d:resourcetype>
    <oc:fileid>10</oc:fileid>
    <oc:permissions>RDNVCK</oc:permissions>
    <oc:size>0</oc:size>
    <oc:tags/>
    <oc:favorite></oc:favorite>
    <oc:owner-display-name>admin</oc:owner-display-name>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <d:getcontenttype/>
    <d:getcontentlength/>
    <oc:comments-unread/>
    <oc:share-types/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

**Comment by PVince81** [comment]
- [ ] BUG: missing "comments-unread" property

**Comment by PVince81** [comment]
Looks like we're done here, it works !

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/22753

**Comment by PVince81** [comment]
Any objections to this ?

The only part I see is that QA would need to retest all the files app features (comments, system tags, file operations, etc).

@DeepDiver1975 @owncloud/qa @jvillafanez

**Comment by jvillafanez** [comment]
Not tested but changes look good 👍

**Comment by PVince81** [comment]
and we keep on finding issues with the new DAV endpoint... like the recent quota one: https://github.com/owncloud/core/issues/28159

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
@PVince81 @DeepDiver1975 this change causes 2 fails in the UI tests.
The last Travis-CI run before this was merged yesterday was from before the UI tests existed, so it passed many moons ago. That is why the CI for this PR shows good, but when it has been rebased/merged to master the CI fails from the latest master.
See issue #28441

**Comment by PVince81** [comment]
@DeepDiver1975 should we backport this to stable10 ?

**Comment by PVince81** [comment]
Regression: https://github.com/owncloud/core/issues/28730.

Maybe we could backport for 10.0.4. If we do, we also need to backport the fix of the above ticket.

**Comment by phil-davis** [comment]
Note: if/when this is backported to 10.0.? then either issue #28441 needs to be fixed and the fix backported, or PR #28442 needs to be backported to skip the tests that will fail.

**Comment by PVince81** [comment]
The above fix was wrong.

This is the correct fix for encoding mismatch: https://github.com/owncloud/core/pull/28749

So if we backport "switch to new DAV endpoint in web UI", we also need to backport https://github.com/owncloud/core/pull/28749

**Comment by PVince81** [comment]
backport here: https://github.com/owncloud/core/pull/28769

**Comment by PVince81** [comment]
Another missing bit: https://github.com/owncloud/core/pull/28874

**Comment by PVince81** [comment]
Switching back here https://github.com/owncloud/core/pull/28914 because of https://github.com/owncloud/core/issues/28779 which is just the tip of the iceberg. There are more perf issues hidden in there, to be looked into in this WIP PR https://github.com/owncloud/core/pull/28853

**Pull request merged**
