### PR TITLE
UI test to add group

### PR DESCRIPTION
**Pull request by sushilkshetri**
## Description
UI test for adding group

## Motivation and Context
This is the UI test for adding a new group. 

## How Has This Been Tested?
Locally Tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sushilkshetri** [comment]
@phil-davis  @individual-it  please review again

**Review by phil-davis — DISMISSED** [review]
Looks good.
I see you just rebased to put this feature in the manageUsersGroups suite - good stuff.

**Comment by sushilkshetri** [comment]
@phil-davis @individual-it  please review again

**Comment by phil-davis** [comment]
Something went wrong with the reabse. There should not be a big merge commit. There should just be your real code commit.

**Comment by sushilkshetri** [comment]
should be fixed now

**Review by phil-davis — APPROVED** [review]
Looks good again.

**Comment by individual-it** [comment]
backport in #30607

**Pull request merged**
