### PR TITLE
Adding repair steps for install and uninstall 

### LINKED ISSUE #24306: Allow apps to have some uninstall routine
The app that I'm currently writing starts several external jobs that should be unregistered when the app gets uninstalled. 

There is the `ManagerEvent::EVENT_APP_DISABLE` event but that one is called after the app has been disabled (ref https://github.com/owncloud/core/blob/2ab4b1ce0402cca1903d06fb7977809088355891/lib/private/App/AppManager.php#L258)

Should we maybe have an appinfo.xml entry for an uninstall class? 

cc @karlitschek @DeepDiver1975

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #24306

### CODE REVIEW

**Comment by MorrisJobke** [comment]
And don't forget the documentation :)

**Comment by DeepDiver1975** [comment]
> And don't forget the documentation :)

https://github.com/owncloud/documentation/issues/2384

**Comment by DeepDiver1975** [comment]
Please review @PVince81 @MorrisJobke @icewind1991 @LukasReschke - THX

**Comment by DeepDiver1975** [comment]
Please review @PVince81 @MorrisJobke @icewind1991 @LukasReschke - THX

**Comment by PVince81** [comment]
Code looks fine :+1:

**Comment by MorrisJobke** [comment]
👍 (enabling/disabling current apps still work)

**Pull request merged**
