### PR TITLE
Do not overlap the author's comment with other things on small screens

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
On small screens, the comment section might be too small to hold a long display name for the author of the comment. The display name will overlap with the "edit" button and the date.
This have been adjusted so there is no overlapping of those elements. The display name will be cut to ensure you can edit the comment and see the date. It will be adjusted with the available width.

## Related Issue
https://github.com/owncloud/enterprise/issues/5177

## How Has This Been Tested?
Manually tested using a user with a long display name.

## Screenshots (if appropriate):
Screenshot from 2022-06-15 12-36-03

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
Works for me.

**Comment by phil-davis** [comment]
Developer review of the technical css changes please - IMO it is good, but also good to have an extra review.

**Comment by mmattel** [comment]
@IljaN @JammingBen mind to have a second review?

**Comment by JanAckermann** [comment]
Did you checked with ie11?

**Comment by phil-davis** [comment]
> Did you check with ie11?

I haven't - I would struggle to find a way to run IE11 somewhere!

**Comment by mmattel** [comment]
> I haven't - I would struggle to find a way to run IE11 somewhere!

https://docs.microsoft.com/en-us/lifecycle/products/internet-explorer-11
`The Internet Explorer (IE) 11 desktop application ended support for Windows 10 semi-annual channel on June 15, 2022. Customers are encouraged to move to Microsoft Edge with IE mode. IE mode enables backward compatibility and will be supported through at least 2029. Additionally, Microsoft will provide notice one year prior to retiring IE mode.`

I think we can skip IE11...
Maybe to add a note in the changelog

**Comment by jvillafanez** [comment]
I think I've only tested on firefox. I'll have a look with more browsers tomorrow.

**Comment by jvillafanez** [comment]
Tested with
* IE 11.3750.14393.0
* Edge 103.0.1264.37
* Firefox 101.0.1
* Chromium 103.0.5060.53

Al of them works fine.

**Review by AlexAndBear — APPROVED** [review]

**Pull request merged**
