### PR TITLE
Fix preview generation for mp3 files

### LINKED ISSUE #34900: uploading .mp3 file shows weird logs
### Steps to reproduce
1. install oC 10.1.0 from tarball
2. upload a .mp3 file
3. check the log

### Expected behaviour
no special log shown

### Actual behaviour
logs shown about not found preview

#### ownCloud log (data/owncloud.log)
```
{"reqId":"lDqjyhdrmYStBqo9i387","level":3,"time":"2019-03-26T15:17:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/owncloud-10.1.1\/community\/remote.php\/dav\/files\/admin\/access.mp3?c=e6a84a50fd5e6acc0796b657f4b1321b&x=39&y=39&forceIcon=0&preview=1","message":"file_get_contents(\/home\/artur\/www\/owncloud-10.1.1\/community\/data\/admin\/files\/home\/artur\/www\/owncloud-10.1.1\/community\/core\/img\/filetypes\/audio.svg): failed to open stream: No such file or directory at \/home\/artur\/www\/owncloud-10.1.1\/community\/lib\/private\/Files\/Storage\/Local.php#227"}
{"reqId":"lDqjyhdrmYStBqo9i387","level":3,"time":"2019-03-26T15:17:48+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/owncloud-10.1.1\/community\/remote.php\/dav\/files\/admin\/access.mp3?c=e6a84a50fd5e6acc0796b657f4b1321b&x=39&y=39&forceIcon=0&preview=1","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/artur\/www\/owncloud-10.1.1\/community\/lib\/private\/legacy\/image.php#573"}
{"reqId":"1hgbZb9WbygIzWsBKqRV","level":3,"time":"2019-03-26T15:17:49+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/owncloud-10.1.1\/community\/remote.php\/dav\/files\/admin\/access.mp3?c=e6a84a50fd5e6acc0796b657f4b1321b&x=39&y=39&forceIcon=0&preview=1","message":"file_get_contents(\/home\/artur\/www\/owncloud-10.1.1\/community\/data\/admin\/files\/home\/artur\/www\/owncloud-10.1.1\/community\/core\/img\/filetypes\/audio.svg): failed to open stream: No such file or directory at \/home\/artur\/www\/owncloud-10.1.1\/community\/lib\/private\/Files\/Storage\/Local.php#227"}
{"reqId":"1hgbZb9WbygIzWsBKqRV","level":3,"time":"2019-03-26T15:17:49+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/owncloud-10.1.1\/community\/remote.php\/dav\/files\/admin\/access.mp3?c=e6a84a50fd5e6acc0796b657f4b1321b&x=39&y=39&forceIcon=0&preview=1","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/artur\/www\/owncloud-10.1.1\/community\/lib\/private\/legacy\/image.php#573"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by prsnbrg**
## Related Issue

- Fixes #34900

## How Has This Been Tested?

- test environment: oC 10.6, oC 10.8 with encryption
- test case 1: Load file list with mp3 file before and after change- compare log output (level 3)
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by prsnbrg** [comment]
After this fix there is still an error with `imagecreatefromstring`. The string given to the method is `/var/www/owncloud/core/img/filetypes/audio.svg`.
The following message appears: `imagecreatefromstring(): Data is not in a recognized format at` [https://github.com/owncloud/core/blob/master/lib/private/legacy/image.php#L573](/lib/private/legacy/image.php#L573)

**Comment by JammingBen** [comment]
Although this is legacy code, I'm not too confident about removing `\OC\Files\Filesystem::file_get_contents()`. As the comment above states, we might need this to properly handle encrypted files. Also this method is not suited for handling SVG files, hence the error with `imagecreatefromstring()`.

IMO the best approach would be to adjust `getNoCoverThumbnail()` (see https://github.com/owncloud/core/blob/master/lib/private/Preview/MP3.php#L83). Some logic to convert SVGs should do the trick here (plus it only affects mp3-files without a cover). Something like:

```
$stream = \fopen($icon, 'r');
$content = \stream_get_contents($stream);
\fclose($stream);

$svg = new \Imagick();
$svg->setBackgroundColor(new \ImagickPixel('transparent'));
$svg->setResolution(1200, 1200);
$svg->readImageBlob($content);
$svg->setImageFormat('png32');

$image = new \OC_Image();
$image->loadFromData($svg);
return $image->valid() ? $image : false;
```

**Comment by JammingBen** [comment]
Okay that is weird. Differences in PHP and/or imagick versions on both of these servers?

Note that this is also not an optimal solution. The best approach would be to ignore the thumbnail creation for mp3s without cover and use the svg image instead. Unfortunately, the current architecture does not allow that easily. It just divides into "needs thumbnail" and "doesn't need thumbnail". There is no category for "may need a thumbnail based in meta data".

**Comment by prsnbrg** [comment]
Is there a way to prevent overwriting the icon when there is no preview.

Even if getThumbnail returns false, the icon is changed for me.

**Pull request closed without merging**
