### PR TITLE
get only vcards which match both the address book id and the vcard uri

### PR DESCRIPTION
**Pull request by schiessle**
getContact() should only return contacts which match both the address book id and the vcard uri

This is just a one-liner, so there shouldn't be any copyright issues. But if you prefer, I hereby grant you permission to use it under the MIT license.

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Thanks @schiessle - I assume this also affects 9.0.x - right?

**Comment by schiessle** [comment]
@DeepDiver1975 didn't checked it but most likely this needs to be backported

**Comment by georgehrke** [comment]
👍 good catch

**Comment by DeepDiver1975** [comment]
unit tests are green as well :+1:

**Pull request merged**
