### PR TITLE
[Backport-14734-stable8]

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@karlitschek backport of https://github.com/owncloud/core/pull/14734 to stable8

### CODE REVIEW

**Comment by karlitschek** [comment]
great! as discussed :+1:

**Comment by jnfrmarks** [comment]
Still seeing issues with my smashbox test:

```

{"reqId":"98d53ae643c18154cb02acaacf8a4fb2","remoteAddr":"172.18.5.120","app":"core","message":"DB Error: \"An exception occurred while executing 'INSERT INTO \"oc_filecache\" (\"mimepart\",\"mimetype\",\"mtime\",\"size\",\"etag\",\"storage_mtime\",\"permissions\",\"path_hash\",\"path\",\"parent\",\"name\",\"storage\") SELECT ?,?,?,?,?,?,?,?,?,?,?,?  WHERE NOT EXISTS (SELECT 1 FROM \"oc_filecache\" WHERE \"mimepart\" = ? AND \"mimetype\" = ? AND \"mtime\" = ? AND \"size\" = ? AND \"etag\" = ? AND \"storage_mtime\" = ? AND \"permissions\" = ? AND \"path_hash\" = ? AND \"path\" = ? AND \"parent\" = ? AND \"name\" = ? AND \"storage\" = ?)' with params [\"3\", \"8\", \"1425666623\", \"2000000\", \"0cd913743f560e114f098f66ca30c714\", \"1425666623\", \"27\", \"a4caed861677625a2f47c347d317b759\", \"files\\\/localShareDir\\\/TEST_FILE_NEW_USER_SHARE_183.dat\", \"21\", \"TEST_FILE_NEW_USER_SHARE_183.dat\", \"3\", \"3\", \"8\", \"1425666623\", \"2000000\", \"0cd913743f560e114f098f66ca30c714\", \"1425666623\", \"27\", \"a4caed861677625a2f47c347d317b759\", \"files\\\/localShareDir\\\/TEST_FILE_NEW_USER_SHARE_183.dat\", \"21\", \"TEST_FILE_NEW_USER_SHARE_183.dat\", \"3\"]:\n\nSQLSTATE[HY000]: General error: 5 database is locked\"<br \/>Offending command was: INSERT INTO `*PREFIX*filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?  WHERE NOT EXISTS (SELECT 1 FROM `*PREFIX*filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `path_hash` = ? AND `path` = ? AND `parent` = ? AND `name` = ? AND `storage` = ?)<br \/>","level":4,"time":"2015-03-06T18:30:32+00:00"}
{"reqId":"98d53ae643c18154cb02acaacf8a4fb2","remoteAddr":"172.18.5.120","app":"remote","message":"Database Error","level":4,"time":"2015-03-06T18:30:32+00:00"}

```

**Comment by LukasReschke** [comment]
That's a different bug. In your case the database is locked now:

```
Array
(
    [reqId] => 98d53ae643c18154cb02acaacf8a4fb2
    [remoteAddr] => x.x.x.x
    [app] => core
    [message] => DB Error: "An exception occurred while executing 'INSERT INTO "oc_filecache" ("mimepart","mimetype","mtime","size","etag","storage_mtime","permissions","path_hash","path","parent","name","storage") SELECT ?,?,?,?,?,?,?,?,?,?,?,?  WHERE NOT EXISTS (SELECT 1 FROM "oc_filecache" WHERE "mimepart" = ? AND "mimetype" = ? AND "mtime" = ? AND "size" = ? AND "etag" = ? AND "storage_mtime" = ? AND "permissions" = ? AND "path_hash" = ? AND "path" = ? AND "parent" = ? AND "name" = ? AND "storage" = ?)' with params ["3", "8", "1425666623", "2000000", "0cd913743f560e114f098f66ca30c714", "1425666623", "27", "a4caed861677625a2f47c347d317b759", "files\/localShareDir\/TEST_FILE_NEW_USER_SHARE_183.dat", "21", "TEST_FILE_NEW_USER_SHARE_183.dat", "3", "3", "8", "1425666623", "2000000", "0cd913743f560e114f098f66ca30c714", "1425666623", "27", "a4caed861677625a2f47c347d317b759", "files\/localShareDir\/TEST_FILE_NEW_USER_SHARE_183.dat", "21", "TEST_FILE_NEW_USER_SHARE_183.dat", "3"]:

SQLSTATE[HY000]: General error: 5 database is locked"<br />Offending command was: INSERT INTO `*PREFIX*filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`path_hash`,`path`,`parent`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?  WHERE NOT EXISTS (SELECT 1 FROM `*PREFIX*filecache` WHERE `mimepart` = ? AND `mimetype` = ? AND `mtime` = ? AND `size` = ? AND `etag` = ? AND `storage_mtime` = ? AND `permissions` = ? AND `path_hash` = ? AND `path` = ? AND `parent` = ? AND `name` = ? AND `storage` = ?)<br />
    [level] => 4
    [time] => 2015-03-06T18:30:32+00:00
)
```

**Comment by jnfrmarks** [comment]
I think it's a result of this change - I wasn't seeing it before.

**Comment by LukasReschke** [comment]
@PVince81 SQLite fun ^ :see_no_evil:

**Comment by karlitschek** [comment]
not good :-(

**Comment by LukasReschke** [comment]
Maybe a case for https://github.com/owncloud/core/pull/13615?

**Comment by karlitschek** [comment]
Hmm. Not sure I understand. It is expected that sqlite is sometimes locked if a lot of parallel requests are executed. The only thing that is important that ownCloud throws a predictable error so that the client will try again later.
Or what am I missing?

**Comment by karlitschek** [comment]
Hmm. Maybe it is "only" a lock timeout issues as discussed here: https://github.com/owncloud/core/pull/13615
What do you think @PVince81

**Comment by karlitschek** [comment]
Just for fun @jnfrmarks changed the smashbox test to run the sync clients 10 times. And then the test passed. So this is indeed a race condition of database locks

**Comment by karlitschek** [comment]
Problem is still reproducible in smashbox for @jnfrmarks with this changes applied: https://github.com/owncloud/core/pull/13615

**Comment by PVince81** [comment]
Maybe try closing the cursors for every filecache operation ?

**Comment by karlitschek** [comment]
@DeepDiver1975 what do you think?

**Comment by DeepDiver1975** [comment]
For me the observed issues related to the database being locked in unrelated to this change.

We know that database locks can occur - which we should analyse.
@PVince81 approach might help

**Comment by LukasReschke** [comment]
:+1:

**Comment by PVince81** [comment]
Isn't stable8 frozen ?

**Comment by karlitschek** [comment]
Yes. Except this one fix. :-) Jennifer will do a final test on the 8.0.2 tars and then we can unfreeze it for 8.0.3 again :-)

**Pull request merged**
