### PR TITLE
[9.0] Allow opening the password reset link in a new window when …

### PR DESCRIPTION
**Pull request by michaelstingl**
…its a URL
- Backport of https://github.com/owncloud/core/pull/24795

@nickvergessen @PVince81 @butonic

### CODE REVIEW

**Comment by nickvergessen** [comment]
Should do a proper backport, if you are unable to do that, you can ask for help. but we should not call OC:: in a template file :-1:

**Comment by michaelstingl** [comment]
Okay, thanks for your feedback. I will close it for now.

**Comment by nickvergessen** [comment]
I fixed this PR

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Second review ? @icewind1991 @ChristophWurst

**Comment by ChristophWurst** [comment]
needs rebase

**Comment by nickvergessen** [comment]
Rebased, +1? @ChristophWurst

**Comment by ChristophWurst** [comment]
:+1: code looks good

**Pull request merged**
