### PR TITLE
adjust controls bar width to not overlay scrollbar

### PR DESCRIPTION
**Pull request by jancborchardt**
Crazy JS-fu incoming

Currently the controls bar extends all the way to the right to overlay the scrollbar. When you have a lot of files, your complete scrollbar could vanish. This fixes that with _a lot_ of JS.

Check it out @owncloud/designers @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by jancborchardt** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Works in the modern browsers and is still the old behaviour in the old ones (IE8 & 9)

:+1: from me too

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
JS unit tests run fine locally -> merge

**Comment by MorrisJobke** [comment]
@cmonteroluque @karlitschek  Should we backport this to stable8? Incoming request in #16725.

**Comment by karlitschek** [comment]
Please back port after 8.0.4 is out of the door. 
Backporting decisions are mine by the way :-)

**Comment by MorrisJobke** [comment]
> Backporting decisions are mine by the way :-)

Okay :) Good to know :+1:

**Comment by cmonteroluque** [comment]
I never said otherwise

**Comment by MorrisJobke** [comment]
I will prepare the backport PR, because @jancborchardt is on vacation

**Pull request merged**
