### PR TITLE
[tests-only] Refactored inter scenarios space

### PR DESCRIPTION
**Pull request by grgprarup**
## Description
Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines

Suites covered:
- webUIAddUsers
- webUIAdminSettings
- webUIComments
- webUICreateDelete
- webUIFavorites
- webUIFileActionsMenu
- webUIFiles
- webUILogin
- webUIManageQuota
- webUIManageUsersGroups
- webUIMoveFilesFolders
- webUIPersonalSettings
- webUIRenameFiles
- webUIRenameFolders
- webUIRestrictSharing
- webUISettingsMenu
- webUISharingAcceptShares
- webUISharingAutocompletion1
- webUISharingAutocompletion2
- webUISharingExternal1
- webUISharingExternal2
- webUISharingInternalGroups1
- webUISharingInternalGroups2
- webUISharingInternalUsers1
- webUISharingInternalUsers2
- webUISharingNotifications
- webUISharingPublic1
- webUISharingPublic2
- webUITags
- webUITrashbin
- webUIUpload
- webUIWebdavLockProtection
- webUIWebdavLocks
- webUIWithCLI

## Related Issue

- Part of https://github.com/owncloud/QA/issues/769

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiOnSqlite-sqlite-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37168/175

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37168/169

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIMobileSize-3-3-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37168/166

**Review by saw-jan — APPROVED** [review]
LGTM

**Pull request merged**
