### PR TITLE
Add php-intl as hard requirement

### PR DESCRIPTION
**Pull request by jvillafanez**
## Related Issue
https://github.com/owncloud/core/issues/29247

## Motivation and Context
See issue

The `Collator` class is used in https://github.com/owncloud/core/blob/intl_hard_requirement/lib/private/NaturalSort.php#L89

## How Has This Been Tested?
Manually tested from a working installation. Removed the php7.0-intl package and also the config.php to trigger a new installation process. A message requiring the installation of the "intl" php module is shown.
Note that ownCloud will keep running without the package being installed if the ownCloud installation isn't fresh (after an upgrade, for example)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
do we have harder than that like for php7-gd ? or is that the same level of hard ?

**Comment by DeepDiver1975** [comment]
Please evaluate if we can Drop the patchwork lib now. Thx

**Comment by jvillafanez** [comment]
> do we have harder than that like for php7-gd ? or is that the same level of hard ?

Unless there are specific check spread around the code, I think that's the place. Checks for gd and other functions / classes are around those lines.

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by jvillafanez** [comment]
Backport in https://github.com/owncloud/core/pull/29539

**Pull request merged**
