### PR TITLE
[stable9] Revert "No longer evaluate appinfo/version"

### PR DESCRIPTION
**Pull request by PVince81**
Reverts owncloud/core#22264

Many apps weren't adjusted yet (including enterprise), total count is 13.

Among them:
- files_antivirus
- files_pdfviewer
- templateeditor
- user_external
- firstrunwizard

Also we could argue that this is like an API change, so best is to give developers (and also us) more time to adjust all apps.

@DeepDiver1975 @nickvergessen @MorrisJobke @davitol 

I we don't want to revert then expect 26 PRs to be reviewed for the release for adjusting versions...

@karlitschek confirm this backport to 9.0

As suggested by @nickvergessen we'd only revert this for stable9 but keep it in 9.1 to give apps more time to adjust. What do you think ?

### CODE REVIEW

**Comment by PVince81** [comment]
Tested with WND, its update works again.

**Comment by karlitschek** [comment]
Yes. Please backport. We shouldn't have done this in the first place because of the API break.

**Comment by karlitschek** [comment]
@cmonteroluque probably a must have for 9.0.0

**Comment by cmonteroluque** [comment]
@karlitschek totally agree, will be merged before RC2 tomorrow

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by davitol** [comment]
:+1: WFM

**Pull request merged**
