### PR TITLE
[stable8.1] Do not print exception message

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/owncloud/core/pull/19739, unfortunately with fewer unit-tests as not all could be backported due to static madness :speak_no_evil:

### CODE REVIEW

**Comment by LukasReschke** [comment]
@rullzer @icewind1991 @MorrisJobke Mind testing? THX.

**Comment by rullzer** [comment]
Looking good! :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
Approval in https://github.com/owncloud/core/pull/19739#issuecomment-147706591 -> merge

**Pull request merged**
