### PR TITLE
Remove DEBUG constant and use config value

### LINKED ISSUE #18404: Missing parameter from config.sample.php, section end?
A couple of questions about config.sample.php. In the manual page, for example 8.2 https://raw.githubusercontent.com/owncloud/documentation/master/admin_manual/configuration_server/config_sample_php_parameters.rst,  DEFAULT_SECTION_START omits the very first parameter, `define('DEBUG', true);`

Then there is an editable section at the end:

``` 
.. ALL_OTHER_SECTIONS_END
.. Generated content above. Don't change this.

App config options
------------------

Retention for activities of the activity app:
```

Are these things in purpose? Is the final section intended for direct editing of config_sample_php_parameters.rst? 

Thanks!

### PR DESCRIPTION
**Pull request by MorrisJobke**
- introduces config.php option 'debug' that defaults to false

Fixes #18404

This would also allow to move away from the evaluated config file to a static config file and makes the config more consistent.
- [x] once this is merged I will drop a email to the devel mailing list https://mailman.owncloud.org/pipermail/devel/2015-August/001508.html
- [x] update documentation owncloud/documentation#1612

cc @nickvergessen @DeepDiver1975 @LukasReschke @PVince81

### CODE REVIEW

**Comment by LukasReschke** [comment]
From my PoV: Good call. :+1:

**Comment by MorrisJobke** [comment]
This also removes more black magic from our architecture.

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
good idea :+1:

**Comment by nickvergessen** [comment]
How about adding a update.php that automatically sets the config, if the constant is set?

**Comment by nickvergessen** [comment]
@MorrisJobke master is broken

**Comment by MorrisJobke** [comment]
> @MorrisJobke master is broken

previously there was a GitException on Jenkins - therefore the retest :wink:

**Comment by MorrisJobke** [comment]
> How about adding a update.php that automatically sets the config, if the constant is set?

I don't think there is such a thing for core :see_no_evil:

**Comment by nickvergessen** [comment]
Appuse this app: https://github.com/owncloud/core/blob/master/apps/files/appinfo/update.php

**Comment by MorrisJobke** [comment]
> Appuse this app: https://github.com/owncloud/core/blob/master/apps/files/appinfo/update.php

I abused it ;)

**Comment by nickvergessen** [comment]
:+1: if you do the doc + email thing

**Comment by MorrisJobke** [comment]
> :+1: if you do the doc + email thing

Sure :) I rebased to fix the failing tests.

**Comment by MorrisJobke** [comment]
I don't have the failures that are present on Jenkins. :confused: 
```
14:34:50 ...................................S.........................   61 / 5065 (  1%)
14:34:50 .............................................................  122 / 5065 (  2%)
14:34:51 .............................................................  183 / 5065 (  3%)
14:34:51 .............................................................  244 / 5065 (  4%)
14:34:52 .............................................................  305 / 5065 (  6%)
14:34:52 .............................................................  366 / 5065 (  7%)
14:34:52 .............................................................  427 / 5065 (  8%)
14:34:52 .............................................................  488 / 5065 (  9%)
14:34:52 .............................................................  549 / 5065 ( 10%)
14:34:52 .............................................................  610 / 5065 ( 12%)
14:34:54 .....................................PHP Fatal error:  Call to a member function remove() on null in /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/cache/file.php on line 82
14:34:54 PHP Stack trace:
14:34:54 PHP   1. {main}() /usr/local/bin/phpunit:0
14:34:54 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:537
14:34:54 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:105
14:34:54 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:153
14:34:54 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:406
14:34:54 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
14:34:54 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
14:34:54 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:699
14:34:54 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:607
14:34:54 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
14:34:54 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
14:34:54 PHP  12. Test\Cache\FileCache->tearDown() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:774
14:34:54 PHP Warning:  Unknown: Cannot destroy the zip context in Unknown on line 0
14:34:54 PHP Stack trace:
14:34:54 PHP   1. {main}() /usr/local/bin/phpunit:0
14:34:54 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:537
14:34:54 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:105
14:34:54 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:153
14:34:54 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:406
14:34:54 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
14:34:54 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
14:34:54 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:699
14:34:54 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:607
14:34:54 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
14:34:54 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
14:34:54 PHP  12. Test\Cache\FileCache->tearDown() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:774
14:34:54 PHP Warning:  Unknown: Cannot destroy the zip context in Unknown on line 0
14:34:54 PHP Stack trace:
14:34:54 PHP   1. {main}() /usr/local/bin/phpunit:0
14:34:54 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:537
14:34:54 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:105
14:34:54 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:153
14:34:54 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:406
14:34:54 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
14:34:54 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
14:34:54 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:699
14:34:54 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:607
14:34:54 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
14:34:54 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
14:34:54 PHP  12. Test\Cache\FileCache->tearDown() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:774
14:34:54 Build step 'Execute shell' marked build as failure
14:34:54 Recording test results
14:34:56 Setting commit status on GitHub for https://github.com/owncloud/core/commit/5beeca88289d97081cac5b84a08397da09f5a33d
14:34:56 Finished: FAILURE
```

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
I know see the error also locally ... debugging.

**Comment by LukasReschke** [comment]
:+1:

**Comment by PVince81** [comment]
Regression: https://github.com/owncloud/core/issues/18529

**Comment by MorrisJobke** [comment]
FIx #18532

**Pull request merged**
