### PR TITLE
Add sidebar to public link page

### PR DESCRIPTION
**Pull request by PVince81**
- [x] add sidebar
- [ ] BUG: fix scrollbars, might need to revamp the layout. The scrollbar needs to be back on the list instead of the whole page

@jancborchardt assuming that we want the sidebar in the public link page ? It would have no tabs (no activity or sharing info) and only the top info.

### CODE REVIEW

**Comment by jancborchardt** [comment]
As discussed the sidebar on the public page only makes sense when we can display something relevant there. For example, as soon as we have comments, and the ability for people to leave comments on public shares.

**Comment by jancborchardt** [comment]
When we implement comments for public links, it makes sense to have the sidebar here. Until then not really.

**Comment by DeepDiver1975** [comment]
> When we implement comments for public links, it makes sense to have the sidebar here. Until then not really.

@PVince81 9.1 from my pov - objections? THX

**Comment by jancborchardt** [comment]
Yeeha, now that we have comments and such this really makes sense on the public page. Also cc @oparoz as we should do this in the Gallery app then as well.

**Comment by oparoz** [comment]
The whole template has to be fixed (https://github.com/owncloud/core/issues/22347) when implementing this and then backported to the logged-in side. Then other apps will be able to use the side-navigation and sidebar

**Comment by karlitschek** [comment]
close for now. Let's reconsider this in the future.

**Pull request closed without merging**
