### PR TITLE
[stable9] adjust PrincipalUri as returned from Sabre to effective username

### PR DESCRIPTION
**Pull request by blizzz**
backport of #23404 

please test and review @DeepDiver1975 @reuterbal @Grot4x @tomghyselinck @georgehrke  or others

### CODE REVIEW

**Comment by Grot4x** [comment]
Fixes the sync issue described in #22988 for owncloud users :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by danielbierstedt** [comment]
Sorry, but this does NOT fix the sync issues I have. I still receive the 404 error.

**Comment by blizzz** [comment]
@danielbierstedt please open a new issue

**Pull request merged**
