### PR TITLE
Register only one dav auth backend

### LINKED ISSUE #26351: DAV auth backend registered twice in DAV v2
Observed on master (89078909e95bc62a746711e6b161efa8dbefd4a3) with a debugger into lib/composer/sabre/dav/lib/DAV/Auth/Plugin.php `beforeMethod`:

```
  $this->backends                = (array[4]);
    $this->backends[0]           = (object|OCA\DAV\Connector\Sabre\Auth[7])+;
    $this->backends[1]           = (object|OCA\DAV\DAV\PublicAuth[1])+;
    $this->backends[2]           = (object|OCA\Federation\DAV\FedAuth[3])+;
    $this->backends[3]           = (object|OCA\DAV\Connector\Sabre\Auth[7])+;
```

Not sure if this can have side effects apart from checking the auth twice.

cc @DeepDiver1975

### PR DESCRIPTION
**Pull request by tcitworld**
## Description

Register auth backend only once. 
## Related Issue

Fixes #26351
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks !

I've retested regular public auth (public link page for files) and it still works.

:+1:

**Comment by DeepDiver1975** [comment]
Federation address book sync will not work afaik

**Comment by PVince81** [comment]
@DeepDiver1975 so only the duplicate needs to be removed then instead of moving the block to the bottom ?

**Review by DeepDiver1975 — COMMENTED** [review]
> @DeepDiver1975 so only the duplicate needs to be removed then instead of moving the block to the bottom ?

from my understanding - yes

**Comment by DeepDiver1975** [comment]
@tcitworld I allowed myself to adjust your pr :wink:

**Comment by DeepDiver1975** [comment]
@PVince81 mind testing? THX

**Comment by tcitworld** [comment]
No worries. ;-)

**Comment by PVince81** [comment]
```
  $this->backends                = (array[3]);
    $this->backends[0]           = (object|OCA\DAV\DAV\PublicAuth[1])+;
    $this->backends[1]           = (object|OCA\Federation\DAV\FedAuth[3])+;
    $this->backends[2]           = (object|OCA\DAV\Connector\Sabre\Auth[7])+;
```

Not sure what the empty challenge method is supposed to do ?

**Comment by PVince81** [comment]
- [x] regular DAV auth
- [x] public link auth (files)
- [ ] public link shared calendar
- [x] fed share auth

If calendar sharing by link still works then this is good to go. @tcitworld can you check ?

**Comment by DeepDiver1975** [comment]
> Not sure what the empty challenge method is supposed to do ?

it will not add another www-auth header ;-)

**Comment by PVince81** [comment]
@tcitworld did you get a chance to test whether calendar link sharing still work with this PR ?

I tried to test it myself but I can't seem to find where in the UI I can create a link share for calendars (using calendar master branch)

**Comment by DeepDiver1975** [comment]
> (using calendar master branch)

you need this PR (which was closed - work continued at nc) - https://github.com/owncloud/calendar/pull/605

**Comment by tcitworld** [comment]
It doesn't work, here's the log error : 
```
[Mon Oct 24 14:17:34 2016] Exception: {"Exception":"TypeError","Message":"Argument 2 passed to OCA\\DAV\\Connector\\Sabre\\FilesPlugin::__construct() must be an instance of OC\\Files\\View, null given, called in \/home\/tcit\/dev\/core\/apps\/dav\/lib\/Server.php on line 168","Code":0,"Trace":"
#0 \/home\/tcit\/dev\/core\/apps\/dav\/lib\/Server.php(168): OCA\\DAV\\Connector\\Sabre\\FilesPlugin->__construct(Object(Sabre\\DAV\\Tree), NULL, Object(OC\\AllConfig), Object(OC\\AppFramework\\Http\\Request), false, false)\n
#1 [internal function]: OCA\\DAV\\Server->OCA\\DAV\\{closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#2 \/home\/tcit\/dev\/core\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n
#3 \/home\/tcit\/dev\/core\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n
#4 \/home\/tcit\/dev\/core\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#5 \/home\/tcit\/dev\/core\/apps\/dav\/lib\/Server.php(216): Sabre\\DAV\\Server->exec()\n
#6 \/home\/tcit\/dev\/core\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()\n
#7 \/home\/tcit\/dev\/core\/remote.php(164): require_once('\/home\/tcit\/dev\/...')\n
#8 {main}","File":"\/home\/tcit\/dev\/core\/apps\/dav\/lib\/Connector\/Sabre\/FilesPlugin.php","Line":114}

```

**Comment by DeepDiver1975** [comment]
> It doesn't work, here's the log error :

I'll look into this ... strange this is untouched ...

**Comment by DeepDiver1975** [comment]
@tcitworld mind testing again? THX

**Comment by PVince81** [comment]
Calendar link share works too :+1:

**Comment by PVince81** [comment]
Ideally we should also add integration tests for this, should be easy to make a DAV request and check that the challenge header only appears once.

@owncloud/qa

**Comment by PVince81** [comment]
Added integration test here https://github.com/owncloud/core/pull/26690

**Pull request merged**
