### PR TITLE
Update to jquery 3.3.1

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Update to latest jquery

## How Has This Been Tested?
Quick manual test of files app, still seems to work.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
Just started to have a play here. In ``master`` it needs the user_management app to create users, so the first thing is using the Users page to get me some ordinary users.

I can add users OK, and add groups on-the-fly as I add users...

But:

- the "Add Group" button is not responsive
- Clicking group names does nothing (should list the members of the group)
- the Everyone group as got a ``NaN`` member count!

screenshot-2018-7-2 users - owncloud

**Comment by PVince81** [comment]
- [ ] NaN group members count
- [ ] fix JS tests

**Comment by phil-davis** [comment]
Trying to share a file or folder always tells me "No users or groups found". Thee server is responding to reasonable-looking requests like:
```
[Mon Jul  2 18:37:28 2018] 192.168.100.18:54734 [200]: /ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=jsg&perPage=200&itemType=folder
```
So it is sending off the right requests, but something in the JS is not understanding the response properly.

**Comment by phil-davis** [comment]
Stuff that seems to work OK:
- [x] files_texteditor
- [x] versions list and restore
- [x] deleted files, restore and/or delete from trashbin
- [x] comments - add/change/delete
- [x] tags
- [x] favorites
- [x] download 1or more files
- [x] upload 1 or more files
- [x] rename
- [x] drag file into folder
so that is encouraging

**Comment by PVince81** [comment]
@phil-davis I'm more afraid of some darker JS corners where obscure jQuery functions were used. It is likely that the only way to find these is to grep the code for deprecated methods.

**Comment by PVince81** [comment]
huh, what, no CI failure ?

but `make test-js` fails with a lot of things for me locally

**Comment by PVince81** [comment]
I see this locally and a looot more:
```
PhantomJS 2.1.1 (Linux 0.0.0) LOG: 'JQMIGRATE: Migrate is installed, version 1.4.0'
02 07 2018 15:48:26.083:WARN [web-server]: 404: /owncloud/index.php/apps/files_external/userglobalstorages?testOnly=true
......02 07 2018 15:48:26.088:WARN [web-server]: 404: /owncloud/index.php/apps/files_external/userstorages
..........................................................................
....................................................................02 07 2018 15:48:26.446:WARN [web-server]: 404: /owncloud/index.php/avatar/foo/32
02 07 2018 15:48:26.488:WARN [web-server]: 404: /owncloud/index.php/avatar/foo/61
............
........
PhantomJS 2.1.1 (Linux 0.0.0) OC.L10N tests async loading of translations loads bundle for given app and calls callback FAILED
        Expected false to equal true.
        core/js/tests/specs/l10nSpec.js:157:43
        Expected false to equal true.
        core/js/tests/specs/l10nSpec.js:158:42
        Expected 'Hello world!' to equal '你好世界!'.
        core/js/tests/specs/l10nSpec.js:159:47
PhantomJS 2.1.1 (Linux 0.0.0) OC.L10N tests async loading of translations calls callback if translation already available FAILED
        Expected false to equal true.
        core/js/tests/specs/l10nSpec.js:169:43
        Expected false to equal true.
        core/js/tests/specs/l10nSpec.js:170:42
PhantomJS 2.1.1 (Linux 0.0.0) OC.L10N tests async loading of translations calls callback if locale is en FAILED
        Expected false to equal true.
        core/js/tests/specs/l10nSpec.js:178:43
        Expected false to equal true.
        core/js/tests/specs/l10nSpec.js:179:42
.............
PhantomJS 2.1.1 (Linux 0.0.0) Backbone Webdav extension collections makes a POST request to create model into collection FAILED
        Expected undefined to equal '123'.
        core/js/tests/specs/oc-backbone-webdavSpec.js:107:28
```

**Comment by PVince81** [comment]
we'd better get rid of jquery-migrate v1 to avoid side effects, as we're supposed to finish the migration to 2 first by doing so: https://github.com/owncloud/core/issues/12877

**Comment by phil-davis** [comment]
I am very surprised - there are webUI tests for file sharing, and from what I observed manually, it just does not show matches. I will look again tomorrow.
The Users Page issues would require running the user_management tests, or backporting this PR for stable10, where the Users Page still exists.

**Comment by PVince81** [comment]
I wonder if somehow there is something unclean and that the library didn't actually get updated on CI.

**Comment by PVince81** [comment]
I heard there might be env caching involved.

- [ ] fix CI env to properly catch lib updates

**Comment by PVince81** [comment]
we'll do jquery update to 2 first, for which we already had some failures https://github.com/owncloud/core/issues/12877#issuecomment-404771097

**Pull request closed without merging**
