### PR TITLE
fix button text color

### PR DESCRIPTION
**Pull request by jancborchardt**
Before & after:
capture du 2015-11-02 17-58-57capture du 2015-11-02 17-57-59

Please review @owncloud/designers @ChristophWurst @Gomez @irgendwie (can be tested with the mail app when Ctrl-clicking on a link in an email)

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by ChristophWurst** [comment]
:+1:

**Comment by jancborchardt** [comment]
@karlitschek I’d like to backport this as the text is not readable without this fix. Ok?

**Comment by karlitschek** [comment]
cool. please backport :+1:

**Comment by jancborchardt** [comment]
Backport at https://github.com/owncloud/core/pull/20337

**Pull request merged**
