### PR TITLE
Fix files select bar width when app sidebar is visible

### LINKED ISSUE #18376: Sidebar overlaps selection summary
### Steps

1. Upload one file
1. Select the file using the checkbox
1. Open the sidebar

### Expected result
Selection summary properly visible

### Actual result
Selection summary overlapped by sidebar

sidebar-selectionoverlap

@jancborchardt FYI

Probably needs some CSS tweaking.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/18376

Only select a single file to see the effect because currently multiple files would close the sidebar.

Please review @MorrisJobke @jancborchardt @blizzz

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@hasso @Henni Mind to review this one?

**Comment by PVince81** [comment]
needs a second reviewer @rullzer @jancborchardt @Xenopathic

**Comment by Xenopathic** [comment]
:+1: tested, works

**Pull request merged**
