### PR TITLE
Remove .idea file since it's marked as changed all the time with new phpStorm

### LINKED ISSUE #13324: Get rid of .idea
It was a nice idea to ship the IDEs configuration inside of the repo, but I would vote for removing it and provide it in another way. You can simply import and export PHPStorms settings. Maybe provide them simply as download and don't mess with others config by default.

If this is approved I will prepare a PR.

cc @icewind1991 @nickvergessen @DeepDiver1975 @LukasReschke @butonic (you are the PHPStorm users I know)

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #13324 

@MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
Should backport to all branches, so this annoyance stops.

**Comment by nickvergessen** [comment]
@DeepDiver1975 Should backport to all branches, so this annoyance stops.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:-1: let's first finish the discussion in #13324

**Comment by LukasReschke** [comment]
Mhm. Maybe as an alternative we can then just upload what PHPStorm changes this all the time to per default in the newer version? ;-)

@nickvergessen care to push? :)

**Pull request closed without merging**
