### PR TITLE
[stable7] Use PHP 5.3 syntax

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/core/issues/18791

@PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
grrr. good catch :+1:

**Comment by DeepDiver1975** [comment]
ok - jenkins is goning nuts - please execute autotest.sh locally - Ill fix Jenkins after my vac - sorry

**Comment by MorrisJobke** [comment]
> ok - jenkins is goning nuts - please execute autotest.sh locally - Ill fix Jenkins after my vac - sorry

The problem is that for example I only can run it against PHP 5.6 :(

**Comment by cdamken** [comment]
Recommendations from oC7 is php5.4+

**Comment by LukasReschke** [comment]
> Recommendations from oC7 is php5.4+

Recommendation != what we support :-)

**Pull request merged**
