### PR TITLE
group principals are now verified as well when sharing…

### LINKED ISSUE #31402: Calendar cannot be shared to group (10.0.8)
The issue #23699 appeared again few days ago, i have time today to attach all the info.

#### Steps to reproduce
* login as fst and share Meetings calendar to Developers group containing user2
* refresh website after did the share, the change is not visible
* login as user2 to review if the share was done
#### Expected behaviour
* Meetings calendar should be visible for user2
#### Actual behaviour
* calendar is not visible for user2, but it is visible if shared directly.
#### Server configuration
* CentOS 7 running latest Docker image of owncloud/server (Tag ID: 2e73a4f3de8c)
* MariaDB latest Docker image (Tag ID: cb0d69450b8e)
* ownCloud version: (see ownCloud admin page) - 10.0.8.5 (stable)
* Calendar version: (see ownCloud apps page) - 1.5.7
* The content of config/config.php:
```
<?php
$CONFIG = array (
  'datadirectory' => '/mnt/data/files',
  'updatechecker' => 'false',
  'upgrade.disable-web' => 'true',
  'skipUpdateCheck' => true,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/custom',
      'url' => '/custom',
      'writable' => true,
    ),
  ),
  'dbtype' => 'mysql',
  'dbhost' => 'ownsql:3306',
  'dbname' => 'owncloud',
  'dbuser' => 'root',
  'dbpassword' => '****************',
  'dbtableprefix' => 'oc_',
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'passwordsalt' => '****************',
  'secret' => '****************',
  'overwrite.cli.url' => '****************',
  'version' => '10.0.8.5',
  'mysql.utf8mb4' => true,
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => '****************',
  'redis' => array('host' => 'redis', 'port' => 6379),
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'loglevel' => '2',
  'default_language' => 'en',
  'htaccess.RewriteBase' => '/',
  'maintenance' => false,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
);
```
#### Client configuration
* Browser: Chrome
* Operating system: Mac OS 10.13.4
#### Logs
``` **.**.**.*** - - [09/May/2018:10:04:10 +0000] "POST /remote.php/dav/calendars/fst/meetings/ HTTP/1.1" 200 647 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36" ```
#### Owncloud logs
```{"reqId":"WLQsk2rM7p2nbjKzmE4h","level":3,"time":"2018-05-09T10:17:25+00:00","remoteAddr":"**.**.**.***","user":"fst","app":"OCP\\Share","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=deve&perPage=200&itemType=principals","message":"Sharing backend for principals not found"}```
#### Browser logs (payload sent)
```https://**********/remote.php/dav/calendars/fst/meetings/```
```<o:share xmlns:o="http://owncloud.org/ns"><o:set><d:href xmlns:d="DAV:">principal:principals/groups/Developers</d:href><o:summary>Meetings shared by fst</o:summary></o:set></o:share>```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… a dav resource with a group

## Description
Since 10.0.8 calendars and addressbooks can no longer be shared with groups.
This regression was introduced because of a verification was added to ensure that the principal is valid.
Group principals have simply been forgotten :man_facepalming: 

## Related Issue
fixes #31402 

## How Has This Been Tested?
- manual testing as described in  #31402

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mrow4a** [comment]
Changes looks easy, you just added groupPrincipalBackend to caldav and if principal is not found using first principal, you use group one. To me looks good, but needs manual testing

**Comment by Julian1998** [comment]
Works fine!

**Comment by phil-davis** [comment]
@DeepDiver1975 - this has backport-request label, but no backport PR referenced yet?

**Comment by firlevapz** [comment]
I just applied the patch and it still not working on my owncloud installation 10.0.8.5

Everytime when I want to add a group-share for a calendar, it disappears after a refresh of the page. Sharing with users works fine.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 - this has backport-request label, but no backport PR referenced yet?

THX for noticing - will open asap

**Comment by DeepDiver1975** [comment]
> I just applied the patch and it still not working on my owncloud installation 10.0.8.5
> 
> Everytime when I want to add a group-share for a calendar, it disappears after a refresh of the page. Sharing with users works fine.

@firlevapz mind opening a new issue? there is most probably something else broken then ....

**Pull request merged**
