### PR TITLE
Add the DB group for preview tests that require the database

### PR DESCRIPTION
**Pull request by nickvergessen**
Got 8 failures otherwise:

```
1) Test\Preview\Movie::testGetThumbnail with data set #0 (-93, -72)
Your test case is not allowed to access the database.

/home/nickv/ownCloud/master/core/tests/lib/testcase.php:110
/home/nickv/ownCloud/master/core/3rdparty/pimple/pimple/src/Pimple/Container.php:113
/home/nickv/ownCloud/master/core/lib/private/AppFramework/Utility/SimpleContainer.php:102
/home/nickv/ownCloud/master/core/lib/private/servercontainer.php:87
/home/nickv/ownCloud/master/core/lib/private/Server.php:907
/home/nickv/ownCloud/master/core/lib/private/db.php:56
/home/nickv/ownCloud/master/core/lib/private/db.php:133
/home/nickv/ownCloud/master/core/lib/private/Files/Cache/Storage.php:81
/home/nickv/ownCloud/master/core/lib/private/Files/Cache/Storage.php:133
/home/nickv/ownCloud/master/core/lib/private/Files/Cache/Storage.php:170
/home/nickv/ownCloud/master/core/lib/private/Files/Filesystem.php:434
/home/nickv/ownCloud/master/core/lib/private/Files/Filesystem.php:370
/home/nickv/ownCloud/master/core/lib/private/util.php:220
/home/nickv/ownCloud/master/core/tests/lib/testcase.php:331
/home/nickv/ownCloud/master/core/tests/lib/preview/provider.php:57
/home/nickv/ownCloud/master/core/tests/lib/preview/movie.php:31
```

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Why wasn't this triggered before?

**Comment by nickvergessen** [comment]
I guess most have default previews activated and didnt configure libre office for doc previews?

**Comment by DeepDiver1975** [comment]
> Why wasn't this triggered before?

because not tested on jenkins - libreoffice and libav... not installed

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
