### PR TITLE
search term for users and groups may occur anywhere in the name or displ...

### PR DESCRIPTION
**Pull request by blizzz**
...ayname, not just in the beginning.

Solves #8959 

How to test? Have a local user with displayname "John Smith". On the users page, filter for "smith".
Before: the user will not be shown.
Now: he will.

Please test/review @icewind1991 @raghunayyar @Xenopathic 

cc @MTRichards

### CODE REVIEW

**Comment by Auraya86** [comment]
Does this fix also effect Ajax Requests? I tried to find users via autosuggest in the sharewith section, but the users are not found if the search term occurs anywhere but not in the beginning.

Any suggestions?

**Comment by blizzz** [comment]
prepend an * to your search term

**Comment by Auraya86** [comment]
thank you for your fast reply. But it doesnt work. I tried several versions:
*term
term*
*term*

**Comment by Auraya86** [comment]
it's because I enabled the app "user_external". There is another search method for getDisplayNames(). And there is the error.

**Comment by blizzz** [comment]
My bad, i thought it was a behaviour change in LDAP backend.

Well, user backends implement their search mechanisms themselves. Prepending % might work with the database (local users). Unsure about files_external.

**Pull request merged**
