### PR TITLE
Testing encryption stream wrapper with various file sizes

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs #15631

### CODE REVIEW

**Comment by PVince81** [comment]
Please note that Sabre does this: https://github.com/owncloud/3rdparty/blob/master/sabre/http/lib/Sapi.php#L70 where the body is actually the stream itself.
The stream_read calls are made by file_put_contents internally.

Not sure if this could affect the behavior.

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
Yes, we can merge this first :+1:

**Comment by PVince81** [comment]
Wait, it's still tagged as "4 - Developing".

@DeepDiver1975 your call.

**Comment by PVince81** [comment]
Obsoleted by https://github.com/owncloud/core/issues/15757

**Pull request closed without merging**
