### PR TITLE
[tests-only] Use postgres for the owncloud server in external storage tests

### LINKED ISSUE #39046: PHP unit test OwncloudTest sometimes fails
Here is an example from last night:

https://drone.owncloud.com/owncloud/core/31438/31/10
```
PHPUnit 8.5.18 by Sebastian Bergmann and contributors.

Runtime:       PHPDBG 7.2.34-23+ubuntu18.04.1+deb.sury.org+1
Configuration: /drone/src/tests/phpunit-autotest-external.xml

.............................................S.....E............. 65 / 85 ( 76%)
....................                                              85 / 85 (100%)

Time: 1.86 minutes, Memory: 52.63 MB

There was 1 error:

1) OCA\Files_External\Tests\Storage\OwncloudTest::testFOpen with data set #4 ('spéciäl fäile')
OCP\Files\StorageNotAvailableException: Sabre\HTTP\ClientHttpException: Internal Server Error

/drone/src/lib/private/Files/Storage/DAV.php:901
/drone/src/lib/private/Files/Storage/DAV.php:859
/drone/src/lib/private/Files/Storage/DAV.php:694
/drone/src/lib/private/Files/Storage/DAV.php:188
/drone/src/apps/files_external/tests/Storage/OwncloudTest.php:55

```

I have noticed this a couple of times recently. There is always "Internal Server Error" reported.

### PR DESCRIPTION
**Pull request by JammingBen**
Approach to fix https://github.com/owncloud/core/issues/39046

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JammingBen** [comment]
Haha ok, pipeline already failed 🥲

**Review by phil-davis — APPROVED** [review]

**Comment by JammingBen** [comment]
I think I found a suitable solution by using a Postgres database for the OC server that receives the DAV requests. I did again several tests via https://github.com/owncloud/core/pull/39069, it looks good so far.

I've set the wait back to 0, although we can keep the new implementation as other tests also have it.

**Review by phil-davis — APPROVED** [review]
LGTM

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiSharePublicLink2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31651/78/1

**Pull request merged**
