### PR TITLE
[stable8.2] move font back from Light to Regular for body text on normal-res screens, fix #18954

### LINKED ISSUE #18954: Font style is too narrow and looks blurry using 'old screens'
screen shot 2015-09-10 at 13 14 34
The letters are too narrow and they seem to be designed for high definition screens

### PR DESCRIPTION
**Pull request by jancborchardt**
Backport of https://github.com/owncloud/core/pull/20176

Please review @davitol @karlitschek @LukasReschke @owncloud/designers @cmonteroluque

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
CSS only change -> merge

**Comment by cmonteroluque** [comment]
thanks!

**Pull request merged**
