### PR TITLE
Revert "Add indexes to speedup DB queries"

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Reverts owncloud/core#17498

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
reverting because of regression :space_invader:

**Comment by DeepDiver1975** [comment]
fixes #17619

@PVince81 @icewind1991 @schiesbn

**Comment by karlitschek** [comment]
:+1:  Why not increase the version number? :-)

**Comment by MorrisJobke** [comment]
Can we please first of all discuss the reason in #17619

**Comment by DeepDiver1975** [comment]
> Can we please first of all discuss the reason in #17619

No - first fix and then resubmit the proper fix.

**Comment by DeepDiver1975** [comment]
> :+1: Why not increase the version number? :-)

THX for the pointer

**Comment by DeepDiver1975** [comment]
> Can we please first of all discuss the reason in #17619

@MorrisJobke enough discussion - https://github.com/owncloud/core/issues/17619#issuecomment-121192357

**Comment by MorrisJobke** [comment]
I would think that #17639 is the better approach, because it keeps the other index, that is working well.

**Pull request closed without merging**
