### PR TITLE
[stable10] Update the sql query to delete duplicate sub share

### PR DESCRIPTION
**Pull request by sharidas**
## Description

`group by id` was causing the results to get skipped and hence returning empty results even if duplicated shares were there. This change would help to solve the issue.

## Motivation and Context

`group by id` was causing the results to get skipped and hence returning empty results even if duplicated shares were there. This change would help to solve the issue.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sharidas** [comment]
The reason for this PR: https://github.com/owncloud/core/pull/30695#issuecomment-381689933.
Verified as follows:

```
➜  owncloud3 git:(fix-repair-subshare-stable10) ✗ ./occ maintenance:repair
Cannot load Xdebug - it was already loaded
 - Repair mime types
 - Detect file cache entries with path that does not match parent-child relationships
 - Generate ETags for file where no ETag is present.
     - ETags have been fixed for 0 files/folders.
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Drop old database tables
 28/28 [============================] 100%
 - Drop old background jobs
 - Remove getetag entries in properties table
     - Removed 0 unneeded "{DAV:}getetag" entries from properties table.
 - Repair outdated OCS IDs
 - Repair invalid shares
 - Remove old share propagation app entries
 - Move user avatars outside the homes to the new location
 - Remove shares of a users root folder
 - Repair unmerged shares
 - Disable extra themes
 - Repair sub shares
     - Removed 1 shares where duplicate rows where found
 - Remove invalid calendar and addressbook shares
➜  owncloud3 git:(fix-repair-subshare-stable10) ✗
```

**Comment by jvillafanez** [comment]
```
mysql> select id, parent, count(*) from share where share_type = 2 group by parent, share_with having count(*) > 1;
ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'owncloud.share.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

Quoting https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html:
> MySQL 5.7.5 and up implements detection of functional dependence. If the ONLY_FULL_GROUP_BY SQL mode is enabled (which it is by default), MySQL rejects queries for which the select list, HAVING condition, or ORDER BY list refer to nonaggregated columns that are neither named in the GROUP BY clause nor are functionally dependent on them. (Before 5.7.5, MySQL does not detect functional dependency and ONLY_FULL_GROUP_BY is not enabled by default. For a description of pre-5.7.5 behavior, see the MySQL 5.6 Reference Manual.)

I don't think the query will work for other DBs since the ONLY_FULL_GROUP_BY is intended to match the standard, so disabling the setting in MySQL shouldn't be an option.

**Comment by jvillafanez** [comment]
PostgreSQL 9.6.8 also have problems running the query:
```
owncloud=# select id, parent, count(*) from oc_share where share_type = 2 group by parent, share_with having count(*) > 1;
ERROR:  column "oc_share.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select id, parent, count(*) from oc_share where share_type =...
               ^
```

**Comment by jvillafanez** [comment]
@sharidas I guess you've tested with mysql < 5.7.5 (or the corresponding mariadb version).
We need another option.

**Comment by PVince81** [comment]
does anything break without this PR ? from my understanding the repair step just doesn't do its job and doesn't break anything, so this task could be considered a bug and deferred to 10.0.9

**Comment by jvillafanez** [comment]
> does anything break without this PR ? from my understanding the repair step just doesn't do its job and doesn't break anything, so this task could be considered a bug and deferred to 10.0.9

Without this PR, that's should be the behaviour. The query won't detect any duplicate

**Comment by PVince81** [comment]
to be rescheduled

**Comment by sharidas** [comment]
@PVince81  estimate: 2-3 md for this task.

**Comment by butonic** [comment]
based on https://stackoverflow.com/questions/18932/how-can-i-remove-duplicate-rows#comment3999923_18949

lets use 
```sql
SELECT id FROM oc_share WHERE id NOT IN (SELECT MIN(id) FROM oc_share GROUP BY share_with, parent) AND share_type=2;
```

to find all the duplicates that should be deleted

**Comment by sharidas** [comment]
Forward port to master branch: https://github.com/owncloud/core/pull/31781

**Comment by sharidas** [comment]
Updated this PR according the suggestions made at https://github.com/owncloud/core/pull/31781.
Tested the code, and during the upgrade process, the duplicate share entry was removed and similar output was observed as in https://github.com/owncloud/core/pull/31781#issuecomment-402459053

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
for manual testing, use steps from https://github.com/owncloud/core/issues/27990#issuecomment-357899190

**Pull request merged**
