### PR TITLE
[wip] decryption enhancements

### PR DESCRIPTION
**Pull request by tomneedham**

### CODE REVIEW

**Comment by tomneedham** [comment]
With this you can skip the confirmation using `--continue`

**Comment by tomneedham** [comment]
You must not specify the decryption method using `--method=password` or `--method=recovery`

**Comment by tomneedham** [comment]
You must now insert the recovery key using an environment variable `OC_RECOVERY_KEY`

**Comment by tomneedham** [comment]
You must now insert the users password using an environment variable `OC_PASSWORD`

**Comment by tomneedham** [comment]
Decryption failures are now listed in the output along with the exception message

**Comment by tomneedham** [comment]
Example command `export OC_RECOVERY=myrecoverykey && ./occ encryption:decrypt-all -vvv username --method=recovery --continue`

**Comment by PVince81** [comment]
moving to triage to schedule finishing this later...

**Comment by PVince81** [comment]
@tomneedham do you intend to finish this later or should we take over ?

**Comment by tomneedham** [comment]
> @tomneedham do you intend to finish this later or should we take over ?

Take over. I used this in some consulting - makes sense to bring it into core as it is very helpful for admins.

**Comment by PVince81** [comment]
- [ ] rename `OC_RECOVERY` to `OC_RECOVERY_PASSWORD`

**Comment by PVince81** [comment]
@sharidas please take over and finish

**Comment by sharidas** [comment]
Closing this PR in favour of https://github.com/owncloud/core/pull/32252

**Pull request closed without merging**
