### PR TITLE
reduce grey tones in app navigation

### PR DESCRIPTION
**Pull request by jancborchardt**
Similar to the dark app navigation experimentation (https://github.com/owncloud/core/pull/18507), here a smaller step inbetween of just reducing the grey tones in the app navigation a bit. Moving from full background highlight towards simpler icon and font highlight (which is also utilized in the dark app navigation design).

Current:
capture du 2015-08-25 15-52-38
This:
capture du 2015-08-26 17-01-32
Alternative dark, as in https://github.com/owncloud/core/pull/18507
capture du 2015-08-25 15-51-18

What do you think @owncloud/designers @karlitschek @MorrisJobke @nickvergessen?

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I really really like this. Looks good. Changes are also fine.

:+1:

Master is currently broken -> CSS/image only change -> ignore it.

**Comment by jancborchardt** [comment]
@karlitschek @PVince81 updated with changes as we discussed so we can proceed with the new upload style:
capture du 2015-08-26 17-01-32
Ok?

**Comment by karlitschek** [comment]
nice! :+1:

**Comment by MorrisJobke** [comment]
:+1:

CSS only ->merge

**Pull request merged**
