### PR TITLE
[stable10] hotfix 10.0.6 commits

### PR DESCRIPTION
**Pull request by phil-davis**
Port just the missing commits from the hotfix-10.0.6 branch into stable10

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
Ok fine, thanks 👍

**Comment by phil-davis** [comment]
NP

**Comment by PVince81** [comment]
Congrats on losing the CI lottery with such simple changes

**Comment by PVince81** [comment]
restarted failed Drone test

**Pull request merged**
