### PR TITLE
Fix openFile method to handle error in acceptance tests

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Modify the acceptance test method `webUIFilesContext::openFile` to handle errors that may occur while opening the file.

## Related Issue

- Fixes <issue_link>

## Motivation and Context

The method originally only assumes that the operation will be always successful. But sometimes it may fail and in that case the file is not opened. So the method needed modification to handle the situations when the user opens the file expecting to fail.

## How Has This Been Tested?

:robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by dpakach** [comment]
Requires #35265 to be merged first.

**Review by skshetry — COMMENTED** [review]
:+1:

**Review by skshetry — COMMENTED** [review]
:+1:

**Review by individual-it — APPROVED** [review]

**Comment by dpakach** [comment]
Backport on #35299

**Pull request merged**
