### PR TITLE
Check whether the file id is valid, before using it to delete the previe...

### PR DESCRIPTION
**Pull request by nickvergessen**
...ws

Backport of #14713 

@DeepDiver1975 please approve Backport
@MorrisJobke as per your request

### CODE REVIEW

**Comment by oparoz** [comment]
:+1: 
It's an important fix as it dramatically slows down the ownCloud experience for anybody using the Android app (and maybe even more users) as all cached thumbnails get wiped at each upload.

**Comment by MorrisJobke** [comment]
:+1:

:construction: Don't merge before 8.0.2 is out :construction:

**Comment by oparoz** [comment]
:cry:

**Comment by karlitschek** [comment]
backport approved after 8.0.2 is out.

**Pull request merged**
