### PR TITLE
Clean up AppFramework database layer

### PR DESCRIPTION
**Pull request by BernhardPosselt**
See #14467

@DeepDiver1975 @MorrisJobke @PVince81 @LukasReschke @butonic @icewind1991 @georgehrke @jbtbnl

TODO:
- [x] run unit test on oracle

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
THX a lot!

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
not that promissing in the first place
```sh
deepdiver@alien:~/Development/ownCloud/master [af-db-cleanup]$ ./autotest.sh oci
Using database oc_autotest
Setup environment for oci testing ...
drop the database

Benutzer wurde gelöscht.

create the database

Benutzer wurde erstellt.


Benutzer wurde geändert.


Benutzerzugriff (Grant) wurde erteilt.

INDEX
END INDEX
Testing with oci ...
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /home/deepdiver/Development/ownCloud/master/tests/phpunit-autotest.xml

..............S..............................................   61 / 2994 (  2%)
.............................................................  122 / 2994 (  4%)
............................F................................  183 / 2994 (  6%)
.............................................................  244 / 2994 (  8%)
.............................................................  305 / 2994 ( 10%)
.............................................................  366 / 2994 ( 12%)
.............................................................  427 / 2994 ( 14%)
.............................................................  488 / 2994 ( 16%)
......................EEE....................................  549 / 2994 ( 18%)
.............................................................  610 / 2994 ( 20%)
.............................................................  671 / 2994 ( 22%)
................S.SSSSSSS....................................  732 / 2994 ( 24%)
.............................................................  793 / 2994 ( 26%)
.............................................................  854 / 2994 ( 28%)
.............................................................  915 / 2994 ( 30%)
..SSSSSS.....................................................  976 / 2994 ( 32%)
..............................................SSSSSSSSSSSSSSS 1037 / 2994 ( 34%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.................. 1098 / 2994 ( 36%)
............................................................. 1159 / 2994 ( 38%)
............................................................. 1220 / 2994 ( 40%)
............................................................. 1281 / 2994 ( 42%)
............................................................. 1342 / 2994 ( 44%)
............................................................. 1403 / 2994 ( 46%)
............................................................. 1464 / 2994 ( 48%)
............................................................. 1525 / 2994 ( 50%)
............................................................. 1586 / 2994 ( 52%)
............................................................. 1647 / 2994 ( 55%)
............................................................. 1708 / 2994 ( 57%)
............................................................. 1769 / 2994 ( 59%)
............................................................. 1830 / 2994 ( 61%)
............................................................. 1891 / 2994 ( 63%)
............................................................. 1952 / 2994 ( 65%)
..........................................................SS. 2013 / 2994 ( 67%)
..........SSSSSSSSSSSSSSSSSSSS..........SSSSSSSSSSSSSSSSSSSSS 2074 / 2994 ( 69%)
SSSSSSSSS...............................SS...............EEEE 2135 / 2994 ( 71%)
EEEEEE................EEEEEE................................. 2196 / 2994 ( 73%)
............................................................. 2257 / 2994 ( 75%)
............................................................. 2318 / 2994 ( 77%)
............................................................. 2379 / 2994 ( 79%)
............................................................. 2440 / 2994 ( 81%)
............E................................................ 2501 / 2994 ( 83%)
.......................S..........................SS......... 2562 / 2994 ( 85%)
..S....EEE..............EEEEEEEEEEEEEEEEEEEEEEEEEE........... 2623 / 2994 ( 87%)
....E......EEEE....EEEE.EE...............EEEEEEEEEEEEEEEEEEEE 2684 / 2994 ( 89%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEPHP Fatal error:  Call to a member function unlink() on null in /home/deepdiver/Development/ownCloud/master/apps/files_sharing/tests/updater.php on line 48
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:605
PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:423
PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:711
PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:641
PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
PHP  12. Test_Files_Sharing_Updater->tearDown() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:802

**Comment by Raydiation** [comment]
I actually dont know why this happens, it should only affect mapper classes in the first place and sharing does not use mappers

**Comment by Raydiation** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
bäh - also doomed on master :anguished:

**Comment by DeepDiver1975** [comment]
works on oracle :+1:

**Comment by DeepDiver1975** [comment]
on pgsql as well - ready to go from my perspective

**Comment by LukasReschke** [comment]
Let's get this in then? :+1: – Works here and looks good.

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @Raydiation This breaks backwards compatibility between ownCloud 7,8 and 8.1 for the mapper class -.-

**Comment by DeepDiver1975** [comment]
@LukasReschke in which sense? I use the mapper class in the mail app - which runs fine in 7, 8 and 8.1

**Comment by DeepDiver1975** [comment]
@MorrisJobke please open a new issue - THX

**Comment by MorrisJobke** [comment]
I injected IDBConnection to my mapper (and then to the parent class) ... and this breaks at this point

**Comment by DeepDiver1975** [comment]
> I injected IDBConnection to my mapper (and then to the parent class) ... and this breaks at this point
ah - yes - because before IDb was taken by the ctor

@Raydiation can we have some compatibility mode in here? THX

**Comment by MorrisJobke** [comment]
> @Raydiation can we have some compatibility mode in here? THX

Okay. You need to do this the other way around. Currently I used IDBConnection(works only in 8.1+). If I use IDb it works also in previous versions (so this is the compatibility mode)

**Pull request merged**
