### PR TITLE
Public link share disabled if password length is equal to 0

### LINKED ISSUE #20177: Submit button on password-protected link page should be disabled until something is put in
Because I assume there can not be empty passwords anyway? @DeepDiver1975 @PVince81 @MorrisJobke

### PR DESCRIPTION
**Pull request by prastut**
Fixes #20177

@MorrisJobke , @PVince81

### CODE REVIEW

**Comment by prastut** [comment]
I am sorry I accidentally clicked the merge branch option. Let me know what should I do on my end.

**Comment by nickvergessen** [comment]
Thanks a lot for your contribution!
Contributions to the core repo require a signed contributors agreement http://owncloud.org/about/contributor-agreement/

Alternatively you can add a comment here where you state that this contribution is MIT licensed.

Some more details about out pull request workflow can be found here: http://owncloud.org/code-reviews-on-github/

**Comment by prastut** [comment]
@jancborchardt, @LukasReschke, @MorrisJobke 

I am in the process of getting the contribution agreement signed. It mentions "Employers Name". Since I am student, what shall I fill here?

Also where I can move this discussion to? I feel this isn't the place to such questions.

**Comment by MorrisJobke** [comment]
> Also where I can move this discussion to? I feel this isn't the place to such questions.

https://doc.owncloud.org/server/9.0/developer_manual/commun/index.html



> I am in the process of getting the contribution agreement signed. It mentions "Employers Name". Since I am student, what shall I fill here?

I guess you could leave it empty - cc @karlitschek

**Comment by MorrisJobke** [comment]
Looks good. Maybe @rullzer @PVince81 @owncloud/sharing and @owncloud/designers could have a look.

**Comment by karlitschek** [comment]
@prastut You can leave it empty. This is fine. Thanks a lot for your contribution :-)

**Comment by prastut** [comment]
@MorrisJobke @karlitschek PR moved to #22810

**Pull request closed without merging**
