### PR TITLE
Skip failing ui-tests on ldap

### PR DESCRIPTION
**Pull request by individual-it**
## Description
some UI tests fail when run on LDAP, we are skipping them before we have a fix

## Related Issue
https://github.com/owncloud/user_ldap/issues/229

## Motivation and Context
get CI working again

milestone is set to "development" because its only test-related code

## How Has This Been Tested?
:robot: 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by individual-it** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
Rebase was a NOOP because this PR was already off the head of ``master``. When that happens, the CI does not get triggered.

I did a local ``git rebase -i master`` and faked rewording the commit text, then ``git push -f``. That makes CI trigger.

**Comment by phil-davis** [comment]
Backport ``stable10`` is in #31126 which is the backport of where these scenarios were added and is still waiting for CI/merge.

**Pull request merged**
