### PR TITLE
[Jenkins] add download feedback

### PR DESCRIPTION
**Pull request by MorrisJobke**
Jenkins PR for #17175

### CODE REVIEW

**Comment by LukasReschke** [comment]
Well. Jenkins will fail also further if tests fail :speak_no_evil:

**Comment by LukasReschke** [comment]
```
09:15:33 PhantomJS 1.9.8 (Linux 0.0.0) OCA.Files.FileList tests File selection Actions Download Opens download URL when clicking "Download" FAILED
09:15:33 	TypeError: 'undefined' is not an object (evaluating 'sourceImage.replace')
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/files/js/filelist.js:432
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/underscore/underscore.js:616
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/jquery/jquery.min.js:5
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/jquery/jquery.min.js:5
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/jquery/jquery.min.js:5
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/jquery-migrate/jquery-migrate.min.js:2
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/jquery/jquery.min.js:5
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/jquery/jquery.min.js:4
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/jquery/jquery.min.js:4
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/jquery/jquery.min.js:5
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/vendor/jquery/jquery.min.js:6
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/files/tests/js/filelistSpec.js:1775
09:15:33 PhantomJS 1.9.8 (Linux 0.0.0) OCA.Files.FileList tests File selection Actions Download Downloads root folder when all selected in root folder FAILED
09:15:33 	TypeError: Attempted to wrap redirect which is already wrapped
09:15:33 	    at wrapMethod (/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/js/tests/lib/sinon-1.7.3.js:528)
09:15:33 	    at stub (/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/js/tests/lib/sinon-1.7.3.js:1685)
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/files/tests/js/filelistSpec.js:1783
09:15:33 PhantomJS 1.9.8 (Linux 0.0.0) OCA.Files.FileList tests File selection Actions Download Downloads parent folder when all selected in subfolder FAILED
09:15:33 	TypeError: Attempted to wrap redirect which is already wrapped
09:15:33 	    at wrapMethod (/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/js/tests/lib/sinon-1.7.3.js:528)
09:15:33 	    at stub (/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/js/tests/lib/sinon-1.7.3.js:1685)
09:15:33 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/files/tests/js/filelistSpec.js:1791
09:15:33 ......................
09:15:34 PhantomJS 1.9.8 (Linux 0.0.0) OCA.Files.FileList tests Handeling errors reloads the page on authentication errors FAILED
09:15:34 	TypeError: Attempted to wrap redirect which is already wrapped
09:15:34 	    at wrapMethod (/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/js/tests/lib/sinon-1.7.3.js:528)
09:15:34 	    at stub (/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/core/js/tests/lib/sinon-1.7.3.js:1685)
09:15:34 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/files/tests/js/filelistSpec.js:2215
09:15:34 	ReferenceError: Can't find variable: redirectStub
09:15:34 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/files/tests/js/filelistSpec.js:2236
09:15:34 	ReferenceError: Can't find variable: redirectStub
09:15:34 	    at /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/files/tests/js/filelistSpec.js:2222
09:15:34 ...........................................[33mWARN [web-server]: [39m404: /svg
09:15:34 .....................................
```

**Comment by MorrisJobke** [comment]
> Well. Jenkins will fail also further if tests fail :speak_no_evil:

In the other branch it always failed due to the git clone exception -.-

**Comment by LukasReschke** [comment]
20 cent on: Now this git clone will also fail :see_no_evil:

**Pull request closed without merging**
