### PR TITLE
Add initial CHANGELOG.md, preparing 10.0.3 beta

### PR DESCRIPTION
**Pull request by PVince81**
Unreleased entries based on v10.0.2..f0b834649d2149d8bbc218c15bcade7bdeffecde: `git log --merges v10.0.2..stable10 --format="format:%s - %b" | grep "pull request" | cut -d" " -f4,8-`

Some open issues:

- [ ] should we continue adding the major/minor labels ?
- [x] removed test-related entries (unit test, integration test, etc), hope this is ok
- [ ] seems there are still too many entries, I had the feeling that the purpose of the changelog is more to be user friendly, not developer friendly (to be discussed)

I haven't decided yet whether to use any tooling for changelogs, for now I'll continue to compile them manually.

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] TODO: convert hash links to real links. I thought Github would do that automatically

**Comment by phil-davis** [comment]
Agree - test infrastructure and devops-related changes are not of interest here, for viewing by end-user sysadmins that want to know what "real" features and fixes are in a release.

Also regressions that happened in master and were fixed in master before release - those commits are not needed a changelog because the bug never happened to any end-user.

**Comment by PVince81** [comment]
- [ ] update with new merges (can also be done separately, but before tagging)

**Comment by PVince81** [comment]
To avoid having to copy-paste regexps, I put it all into a script: f003f111f045e3e836ab8479c97ad5099ca33d07

The entries in question still need to be reworded and split into the "added/changed/deleted" but at least a lot of the repetitive work is not needed here.

**Comment by PVince81** [comment]
- [ ] update with new merges, one last time (expecting https://github.com/owncloud/core/pull/28662)

**Comment by PVince81** [comment]
@pmaier1 @stkjj you guys happy with the changelog format ? do we still want/need the "major/minor" prefix ?

**Comment by PVince81** [comment]
Update changelog and increated version to 10.0.3 beta.

**Comment by PVince81** [comment]
PR to forward port the changelog script only to master: https://github.com/owncloud/core/pull/28682

**Comment by pmaier1** [comment]
Yay, this looks perfect and is really really helpful! :+1: :+1: 

> should we continue adding the major/minor labels ?

For me this would help as it's kind of a preselection from an engineering POV. Therefore I would of course prefer adding such labels. In the end I would leave it up to you to decide on effort/benefit ratio.

**Pull request merged**
