### PR TITLE
Php 7.1

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Makes sense 👍

**Comment by PVince81** [comment]
Code looks good, OC still boots up on my PHP 5.6 :+1: 

Happy to see a phpseclib update which will help close other issues!

**Comment by Kaelber** [comment]
Is OC 10 also compatible with earlier PHP versions? Before of PHP 5.6?

**Comment by PVince81** [comment]
No, PHP 5.6 is the minimum for OC 10.0

**Pull request merged**
