### PR TITLE
Update randomlib

### PR DESCRIPTION
**Pull request by LukasReschke**
Core for https://github.com/owncloud/3rdparty/pull/159

### CODE REVIEW

**Comment by LukasReschke** [comment]
@karlitschek @DeepDiver1975 Also backport candidate to stable8. This RandomLib bump fixes a security problem (I had a custom workaround for this in our code so we were not affected in the public API) and also fixes a problem with ugly webhosters (https://github.com/owncloud/core/issues/14165) and when running HHVM.

**Comment by th3fallen** [comment]
silly question for @karlitschek @DeepDiver1975 why do we constantly update the subproject commit version instead of letting 3rd party always be on master and when we create a stable x on core create a stable x on 3rdparty as well and then update it once?

**Comment by karlitschek** [comment]
@th3fallen Hmm. Would be an option. The benefit with doing it manually is that we can do proper testing of the new version, can do security checks, make sure that this doesn´t introduce feature or supported platform regressions and so on. The latest versions are unfortunately not always the best :-)
I agree that this creates some work but often enough we where also happy to control upgrades in the right way. 
Do you know what I mean?

**Comment by th3fallen** [comment]
@karlitschek no, no, no I meant our 3rdparty repo not composer. I was saying we set master of core to use master of 3rdparty. Then when we introduce a stable{x} on core we create it on 3rdparty and update the submodule on core.

Hope that explains what i mean better.

**Comment by karlitschek** [comment]
Ahh O.K. 
@DeepDiver1975 What do you think?

**Comment by DeepDiver1975** [comment]
Individually updating the sub project commit allows us testing the change on 3rdparty within the pull request analysis in core.

For example @PVince81 is currently updating sabredav to version 2.1 - which requires some adoptions and most important: some testing effort. 
We need a pr in core pointing to a different branch/commit in 3rdparty.

I'm aware that the current approach is somewhat clumsy - but I see no better way (besides moving composer into core - but this is topic of another PR)

**Comment by bantu** [comment]
https://github.com/owncloud/3rdparty/pull/159 was merged.

**Comment by nickvergessen** [comment]
Needs a different commit id now, otherwise it removes the doctrine update

**Comment by LukasReschke** [comment]
Isn't this already in master… I think?

https://github.com/owncloud/3rdparty/commits/59f092231c6036838746262a4db80997908bb06f

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/3rdparty/commit/98f2e8b825dad13d81704f88268130497abdebd7 - this one is in master

**Comment by DeepDiver1975** [comment]
this 3rdparty submodule things is driving me nuts

**Comment by LukasReschke** [comment]
So erm close? :see_no_evil:

**Comment by DeepDiver1975** [comment]
> /me doesn't get it anymore.

welcome to the show ...

yes - we can close this

**Pull request closed without merging**
