### PR TITLE
Bump 3rdparty for icewind/streams-0.3.0

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/212

### CODE REVIEW

**Comment by rullzer** [comment]
Ah failure is deteced by CI :)

```
03:19:20 PHP Warning:  Declaration of OC\Files\Stream\Encryption::wrapSource($source, $mode, $context, $protocol, $class) should be compatible with Icewind\Streams\Wrapper::wrapSource($source, $context, $protocol, $class) in /ssd/jenkins/workspace/server-master-linux-php7-ci@3/database/sqlite/label/SLAVE/lib/private/files/stream/encryption.php on line 30
03:19:20 PHP Fatal error:  Class OC\Files\Stream\Encryption contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Icewind\Streams\Directory::dir_opendir) in /ssd/jenkins/workspace/server-master-linux-php7-ci@3/database/sqlite/label/SLAVE/lib/private/files/stream/encryption.php on line 30```

CC: @schiesbn

**Comment by DeepDiver1975** [comment]
@rullzer please rebase - in addition the missing method implementation should be pretty straight forward. Wana give it a try? THX

**Comment by rullzer** [comment]
@icewind1991 it fails because of https://github.com/icewind1991/Streams/blob/master/src/Directory.php#L19 

If I just add the function and make it return true. Everything is fine. But I don't think that is actually what we want. All the other dir_ functions are overloaded in https://github.com/icewind1991/Streams/blob/master/src/Wrapper.php so it seems kind of weird to not overload dir_opendir.

Any suggestions on what to do that really fixes this instead of only the symptones with a fix that will most likely bite us later.

**Comment by icewind1991** [comment]
> If I just add the function and make it return true. Everything is fine.

If wrapping directory handles doesn't make sense for the specific wrapper it should return `false`

`dir_opendir` is not overloaded in the wrapper for the same reason `stream_open` isn't

**Comment by rullzer** [comment]
dir_diropen now returns false.
All unit tests pass. So stuff seems to be fine.

@schiesbn @icewind1991 please review.

**Comment by icewind1991** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@rullzer 3rdparty merged - please update - thx

**Comment by rullzer** [comment]
@DeepDiver1975 done

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 done

thx

**Pull request merged**
