### PR TITLE
fix for user ldap

### PR DESCRIPTION
**Pull request by haribhandari07**
## Description

Fix for https://github.com/owncloud/user_ldap/issues/429
## Related Issue

On top of #35555
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by dpakach — COMMENTED** [review]
LGTM :+1:

**Comment by dpakach** [comment]
The earlier implementation did not initialize LDAP users. Because of that LDAP users would not have skeleton files and the tests failed with errors like
```
Then folder "simple-folder (2)" should be listed on the webUI                                    # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()
      could not find  file 'simple-folder (2)' in current folder when it should be listed
      Failed asserting that null is not null.
```
That should be fixed now by initializing the users while creating them.

**Review by phil-davis — APPROVED** [review]

**Comment by HariBhandari07** [comment]
Backport on #35610

**Comment by phil-davis** [comment]
I did rebase and force push. Let's see if we can get codecov status.

**Pull request merged**
