### PR TITLE
add support for user group by branch.

### PR DESCRIPTION
**Pull request by bpoussin**
example:
  uid=Jean,ou=people,o=group1,o=root
  uid=Jacques,ou=people,o=group1,o=root
  uid=Bernard,ou=people,o=group2,o=root

In this example, there are two group
some LDAP are structured like this

### CODE REVIEW

**Comment by PVince81** [comment]
@blizzz is now a good time to try it ? :wink:

**Comment by MorrisJobke** [comment]
@blizzz ping

**Comment by MorrisJobke** [comment]
@owncloud-bot this is okay to test

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@blizzz Can you have a look at this?

**Comment by blizzz** [comment]
So, yes, this is incomplete. Tested against current master:

* [ ] getUserGroups does not return the group.
* [ ] on users page, no groups are assigned. Same reason as above.
* [ ] on users page, all(?) "proper" LDAP groups are listed

This happens for me even when I disable useMemberOfToDetectMembership via occ.

Another thing, @bpoussin if we merge this, will you be there to maintain this feature? Because, personally I have some doubts on this support (while I acknowledge your need) and having someone who would take care of it would really benefit. An additionall plus is to add integration tests. Meanwhile we have first two or so cases that we test. Using docker against OpenLDAP, nevertheless I expect this should work there as well. 

Hence my doubts I was, honestly, avoiding to look further into it (we all have other things to do as well, eh?), which is not proper behaviour and I like to apologize therefore.

**Comment by bpoussin** [comment]
I am very embarrassed because I would like that our business group uses owncloud, as I personally do, and for that, this patch is required. But unfortunately, I can not promise anything in the long term for the support of this patch, I already miss considerable the time for many other projects in which I am involved and php is not a language in which I am very comfortable :(

**Comment by blizzz** [comment]
Tu sum up, basically we have the options to close this (would be sad) or fix the remaining issues, merge and hope for the best in the future. With having tests it, it would make it easier, but we're a bit in the blue if we would need to do bigger changes in the future.

Would you be willing to take time and effort to work on the [open issues](https://github.com/owncloud/core/pull/11308#issuecomment-124505377)?

@MTRichards did you hear anywhere any voice who is asking for a feature like this? If there would be more potential users I'd feel more encouraged to get it in and take care of it long term, if it would be necessary.

**Comment by MTRichards** [comment]
There is one request from a user where the tree is structure more like this:
https://github.com/owncloud/enterprise/issues/693
Not sure if this would help make that happen or not?

**Comment by MTRichards** [comment]
I have not heard from customers of this sort of a setup before...

**Comment by blizzz** [comment]
> There is one request from a user where the tree is structure more like this:
owncloud/enterprise#693
Not sure if this would help make that happen or not?
Nope, in their case it is about wildcards base DNs, so they are updated dynamically, but groups are still records of their own.

**Comment by DeepDiver1975** [comment]
@bpoussin please rebase this - THX

**Comment by DeepDiver1975** [comment]
@blizzz do we accept this change? THX

**Comment by jancborchardt** [comment]
@owncloud/ldap would be cool if you can test this as well. :)

**Comment by blizzz** [comment]
No reply, so I close it to lack of activity.

**Pull request closed without merging**
