### PR TITLE
[stable8.0] don't allow to create a federated share if source and target are the same

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/owncloud/core/pull/21067

### CODE REVIEW

**Comment by PVince81** [comment]
Getting a 500 when fed-sharing with self in share dialog

**Comment by PVince81** [comment]
- [ ] regular user, share dialog blocking
- [ ] regular user, link share blocking
- [ ] LDAP user, ldap uuid share dialog blocking :no_entry_sign: FAIL
- [ ] LDAP user, user id share dialog blocking => sharing was not possible with user id back then
- [ ] LDAP user, link share blocking

**Comment by schiesbn** [comment]
This is exactly the mess I expected right from the beginning. To make it work we also need to backport following PRs to 8.1 and 8.0:

- https://github.com/owncloud/core/pull/14401
- https://github.com/owncloud/core/pull/19580

@karlitschek please approve that we should go that far. 

@blizzz @nickvergessen can you take care of the backports if @karlitschek approves it? They create quite some merge conflicts. I would prefer if someone handles them who knows the code better than me, especially in the LDAP case.
Maybe both of you can already check in advance if this pull request can be backported at all without requiring additional backports, to have some more information for @karlitschek to make a decision.

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
@rullzer second review ?

**Comment by rullzer** [comment]
Works over here! :+1:

**Pull request merged**
