### PR TITLE
Kill OC_Group

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Finally it's about time to get rid of the legacy class OC_Group.
This class is also causing trouble with #27276 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Some apps in https://github.com/owncloud/apps seem to use `OC_Group` to register their group backends and other things. Let's raise a ticket there after this is merged.

**Comment by PVince81** [comment]
raised LDAP ticket: https://github.com/owncloud/user_ldap/issues/61

**Comment by PVince81** [comment]
raised ticket for apps: https://github.com/owncloud/apps/issues/2212

**Comment by DeepDiver1975** [comment]
> Some apps in https://github.com/owncloud/apps seem to use OC_Group to register their group backends and other things. Let's raise a ticket there after this is merged.

we for sure have to fix this .... THX for raising the issues

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
