### PR TITLE
Avoid sending passwords in the API

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Passwords could be seen in several requests made by ownCloud

## Related Issue
https://github.com/owncloud/enterprise/issues/5036

## How Has This Been Tested?
Manually checked with some external storages and some operations on them.
* Create a new storage
* Update a storage config without changing the password
* Reload the web page (password should be replaced)
* Check with additional WND authentication methods
  * WND Collaborative
  * User-entered authentication
* Personal mounts

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by C0rby — APPROVED** [review]
Looks good to me. But we should also tackle the other things like private key or OAuth2 secret.

**Comment by phil-davis** [comment]
There is no changelog.

Tests? There could be unit tests to check that the special password is produced in output, and that it is correctly recognised when it arrives as input.

And/or I can get someone to add a couple of API acceptance tests that check GET and POST of this stuff.

**Review by C0rby — CHANGES_REQUESTED** [review]
Yeah, @phil-davis is right. At least a unit test and a changelog would be good.

**Review by C0rby — APPROVED** [review]

**Review by AlexAndBear — CHANGES_REQUESTED** [review]
LGTM so far.
But we need to add tests, that the actual password won't be changed if you provided the REDACTED_PASSWORD via a patch.

If this would ever happen, it might be a crucial bug, so let's better be safe here.

**Review by AlexAndBear — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
