### PR TITLE
Ocm via sciencemesh for 10.12

### LINKED ISSUE #40576: Support sharee search for the sciencemesh app
When the sciencemesh app is enabled, it provides the option to OCM-share a resource via ScienceMesh instead of via regular OCM. For this, the user search, as well as the actual OCM sending is handled by a call to a Reva instance.

For the OCM sending, we can configure this using the [`sharing.managerFactory` config option](https://github.com/owncloud/core/blob/v10.11.0/lib/private/Server.php#L896), but for sharee search, we need to add an if statement that diverts the code path if the sciencemesh app is installed.

### PR DESCRIPTION
**Pull request by phil-davis**
# Description
This is a rebase of PR #40577 to go to `release-10.12.0` branch.

I have left the changelog linking to #40577 because that PR actually has all the discussion etc., so it will be more useful to be linked in the changelog.

## Related Issue
- Fixes #40576

## Motivation and Context
This is needed for OC-10 instances that want to join https://sciencemesh.io

## How Has This Been Tested?
- test environment:
  - GitPod from https://github.com/cs3org/ocm-test-suite
  - run ./gitpod-init.sh
  - run ./scripts/clean.sh
  - run ./scripts/orro-testing.sh
  - go the Firefox browser-in-a-browser that is exposed to port 5800
  - in there, navigate to https://oc1.docker (einstein / relativity)
  - create a local user 'john'
  - using the ScienceMesh app, generate an invite
  - accept the invite on oc2.docker (marie / radioactivity)
  - confirm that marie is now a ScienceMesh contact of einstein on oc1.docker
- test case 1: sharing via ScienceMesh
  - as einstein on oc1.docker, share a file and start typing "m..." as the sharee
  - as marie on oc2.docker, accept the share
  - check the revaoc1.docker logs and see that the sharing happened via oc1 -> revaoc1 -> revaoc2 -> oc2
- test case 2: sharing via local
  - as einstein on oc1.docker, share a file and start typing "jo..." as the sharee
  - it should offer to share with John as a local user

## Screenshots (if appropriate):
Screenshot 2023-01-13 at 13 53 37

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: there is no unit test that covers the new code in `ShareesController` `getRemote`

Someone needs to decide if that is OK or not.

**Comment by michielbdejong** [comment]
Yeah, the existing unit test covers the case where the config variable is not set.

**Review by jvillafanez — APPROVED** [review]

**Comment by jvillafanez** [comment]
We'll likely need time to check if we can mock the service. If this is expected to be in the release, unless the test is added today, I think it's better to leave it as technical debt and fix it later.

The problem is that we need to register a service with the mock, and then unregister it after the test. Not sure if this is planned or not.

**Comment by jvillafanez** [comment]
Test added. It should be ready now.

**Comment by GeraldLeikam** [comment]
Testing cannot currently be performed as the test build is failing.

**Pull request merged**
