### PR TITLE
Move Files_Sharing to PSR-4

### PR DESCRIPTION
**Pull request by nickvergessen**
@schiesbn @rullzer

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:boom: 

```
00:17:13.683 ..................................................PHP Fatal error:  Class 'OCA\Files_sharing\Lib\DeleteOrphanedSharesJob' not found in /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/apps/files_sharing/tests/deleteorphanedsharesjobtest.php on line 92
00:17:13.687 PHP Stack trace:

**Comment by DeepDiver1975** [comment]
00:03:14.184 ................................................PHP Fatal error:  Class 'Test_Files_Sharing_Api' not found in /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/apps/files_sharing/tests/ApiTest.php on line 127
00:03:28.086 PHP Stack trace:

**Comment by rullzer** [comment]
Conflicts...

**Comment by nickvergessen** [comment]
Rebased

**Comment by rullzer** [comment]
:+1:

**Comment by rullzer** [comment]
Rebased because of conflicts.

**Comment by ChristophWurst** [comment]
Conflicts again

**Comment by nickvergessen** [comment]
Rebased because of flat resharing

**Comment by nickvergessen** [comment]
Rebase again for conflicts sake

**Comment by nickvergessen** [comment]
@ChristophWurst is that the second :+1: ? :wink:

**Comment by ChristophWurst** [comment]
> This branch has conflicts that must be resolved

And again and again and again

**Comment by nickvergessen** [comment]
Rebased because of conflicts

**Comment by PVince81** [comment]
Ok, sharing still works even with encryption, so does fed sharing :+1:

**Pull request merged**
