### PR TITLE
remove old propagation logic

### PR DESCRIPTION
**Pull request by icewind1991**
Per-storage propagation handles all of that for us

cc @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Yes :+1:

**Comment by MorrisJobke** [comment]
I'm fine with this, but can we smash it please? cc @nickvergessen 

:+1: from my side

**Comment by PVince81** [comment]
Ok let me smash this.

**Comment by DeepDiver1975** [comment]
> Ok let me smash this.

reminds of the ci smasher ....

**Comment by MorrisJobke** [comment]
> reminds of the ci smasher ....

But it is only run once a day, right? I just want to have it tested before the merge ;)

**Comment by DeepDiver1975** [comment]
> ci

CI as in CONTINUOUS ....

https://ci.owncloud.org/job/smashbox-on-docker-ci/

**Comment by PVince81** [comment]
It doesn't seem to be running for PRs, so if we merge this first we will find out later ?

(still smashing atm)

**Comment by DeepDiver1975** [comment]
> It doesn't seem to be running for PRs, so if we merge this first we will find out later ?

yes - it's a reminder to myself to get this fixed!

**Comment by PVince81** [comment]
Can't test properly, this test fails and also fails on master ?!

```
2015-12-02 11:43:57,426 - CRITICAL - recipient2 - Exception occured: OCS error: 403 
 Traceback (most recent call last):
  File "./python/smashbox/multiprocessing_engine.py", line 164, in worker_wrap
    f(step)
  File "/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py", line 286, in recipient2
    share2_data = clients[0].share_file_with_group('/test/sub', group4, perms=31)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1178, in share_file_with_group
    self.__check_ocs_status(tree)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1395, in __check_ocs_status
    raise OCSResponseError(r)
OCSResponseError: OCS error: 403

2015-12-02 11:43:58,236 - CRITICAL - recipient4 - Exception occured: HTTP error: 404 
 Traceback (most recent call last):
  File "./python/smashbox/multiprocessing_engine.py", line 164, in worker_wrap
    f(step)
  File "/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py", line 429, in recipient4
    sub_etags = get_client_etags(clients, '/sub')
  File "/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py", line 83, in get_client_etags
    new_etags.append(client.file_info(path).get_etag())
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 254, in file_info
    res = self.__make_dav_request('PROPFIND', path)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1451, in __make_dav_request
    raise HTTPResponseError(res)
HTTPResponseError: HTTP error: 404

2015-12-02 11:43:59,971 - ERROR - owner - recipient2 uploads to /test/test3.txt etag for / previous ["565ecb6f3c784"] new ["565ecb6f3c784"] 'etag for / previous [%s] new [%s]' % (root_etag2, root_etag3)) failed in owner() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 150]
2015-12-02 11:44:00,097 - ERROR - recipient3 - recipient2 uploads to /test/test3.txt etag for / previous [['"9627fe96e6ab7caaa51f658a56eaf017"', '"da576942aa98db510bbd512e01cb7128"']] new [['"9627fe96e6ab7caaa51f658a56eaf017"', '"da576942aa98db510bbd512e01cb7128"']] 'etag for / previous [%s] new [%s]' % (root_etags2, root_etags3)) failed in recipient3() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 374]
2015-12-02 11:44:00,130 - ERROR - recipient1 - recipient2 uploads to /test/test3.txt etag for / previous [['"ae5b5c1715eed8d8c2c7973f78527144"', '"51f3671b62ece0fe152005b12d7d590f"']] new [['"ae5b5c1715eed8d8c2c7973f78527144"', '"51f3671b62ece0fe152005b12d7d590f"']] 'etag for / previous [%s] new [%s]' % (root_etags2, root_etags3)) failed in recipient1() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 219]
2015-12-02 11:44:06,240 - ERROR - owner - recipient 4 uploads to /sub/test6.txt through reshare etag for / previous ["565ecb744352e"] new ["565ecb744352e"] 'etag for / previous [%s] new [%s]' % (root_etag5, root_etag6)) failed in owner() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 176]
2015-12-02 11:44:06,243 - ERROR - owner - recipient 4 uploads to /sub/test6.txt through reshare etag for /test previous ["565ecb7442c1b"] new ["565ecb7442c1b"] 'etag for /test previous [%s] new [%s]' % (test_etag3, test_etag4)) failed in owner() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 178]
2015-12-02 11:44:06,511 - ERROR - recipient3 - recipient 4 uploads to /sub/test6.txt through reshare etag for / previous [['"fdae6d28efc8e8eca6afc819d1dc02f2"', '"196b8739bca943b3195fb1ba5986f567"']] new [['"fdae6d28efc8e8eca6afc819d1dc02f2"', '"196b8739bca943b3195fb1ba5986f567"']] 'etag for / previous [%s] new [%s]' % (root_etags5, root_etags6)) failed in recipient3() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 396]
2015-12-02 11:44:06,512 - ERROR - recipient3 - recipient 4 uploads to /sub/test6.txt through reshare etag for /test previous [['"565ecb7442c1b"', '"565ecb7442c1b"']] new [['"565ecb7442c1b"', '"565ecb7442c1b"']] 'etag for /test previous [%s] new [%s]' % (test_etags3, test_etags4)) failed in recipient3() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 398]
2015-12-02 11:44:06,573 - ERROR - recipient1 - recipient 4 uploads to /sub/test6.txt through reshare etag for / previous [['"37ee059473ec03fa9e9fa252108a64fd"', '"5c8d16299267d515cd5bd18bc4d73a1c"']] new [['"37ee059473ec03fa9e9fa252108a64fd"', '"5c8d16299267d515cd5bd18bc4d73a1c"']] 'etag for / previous [%s] new [%s]' % (root_etags5, root_etags6)) failed in recipient1() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 246]
2015-12-02 11:44:06,574 - ERROR - recipient1 - recipient 4 uploads to /sub/test6.txt through reshare etag for /test previous [['"565ecb7442c1b"', '"565ecb7442c1b"']] new [['"565ecb7442c1b"', '"565ecb7442c1b"']] 'etag for /test previous [%s] new [%s]' % (test_etags3, test_etags4)) failed in recipient1() ["/home/vincent/work/workspace/smashbox/lib/owncloud/test_sharePropagationInsideGroups.py" at line 248]
2015-12-02 11:44:08,197 - ERROR - recipient3 - 3 error(s) reported
2015-12-02 11:44:08,202 - ERROR - owner - 3 error(s) reported
2015-12-02 11:44:08,205 - ERROR - recipient1 - 3 error(s) reported
SUMMARY:smash.:Elapsed time: 43s (0:00:43.581313)
CRITICAL:smash.:Aborting run -- non-zero exit code (2)
```

Possibly unrelated.

**Comment by DeepDiver1975** [comment]
> Possibly unrelated.

I guess this is related because of the sharing rewrite?

**Comment by PVince81** [comment]
@rullzer

**Comment by PVince81** [comment]
Smashbox fail raised here https://github.com/owncloud/core/issues/20892

**Comment by PVince81** [comment]
I'll resmash this and disable this test.

**Comment by PVince81** [comment]
Without the broken test everything else passes.
Merge ?

**Pull request merged**
