### PR TITLE
[stable8] Allow chunk GC mtime tolerance for unfinished part chunks

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/24691 to stable8

Please review @icewind1991 @MorrisJobke @nickvergessen @schiesbn @rullzer

### CODE REVIEW

**Comment by PVince81** [comment]
Tested using the steps https://github.com/owncloud/core/issues/24653#issuecomment-219735296 and worked fine.

**Comment by rullzer** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1:

**Comment by Marginal** [comment]
:+1:

**Pull request merged**
