### PR TITLE
feat: implement App Registry 

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Implements https://owncloud.dev/services/app-registry/apps/

## How Has This Been Tested?
- connect to a server running this PR via ios 12.0.3+ or desktop client 4.0+
- install only office, ms office and/or collabora
- upload a supported file format to the server (depending on the installed office apps)
- open the file ios or the context menu in desktop file manager
- see an option to open the file in the app "Open in MS Office"
- browser to the oc server will open and open the file in the app

## Screenshots (if appropriate):
Screenshot from 2023-07-05 15-00-39

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToShares2-maria10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38628/68

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiWebdavLocks3-maria10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38628/83

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares2-10.9.1-maria10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38628/107

**Comment by DeepDiver1975** [comment]
@mmattel you might want to write some docs about this ;-)

**Comment by mmattel** [comment]
> via ios 12.0.3+ or desktop client 4.0+

what about android?

thanks for notifying, need to think about how to document this and which repos is affects.

**Comment by DeepDiver1975** [comment]
Android is not ready yet

**Comment by jvillafanez** [comment]
I'm worried most of the hardcoded information should be provided by the apps... core should just provide a registration mechanism for the apps to use.
The apps can change the routes and / or the supported mime types. With the current approach, not only we need a new core version to adjust the information, but also the apps must rise the minimum OC version because the feature won't be usable in older OC versions.

**Comment by DeepDiver1975** [comment]
> I'm worried most of the hardcoded information should be provided by the apps... core should just provide a registration mechanism for the apps to use.
> The apps can change the routes and / or the supported mime types. With the current approach, not only we need a new core version to adjust the information, but also the apps must rise the minimum OC version because the feature won't be usable in older OC versions.

I fully agree with this - but this is a starting point and needs to grow over time. 
Furthermore - none of these urls got changed in the past years and I doubt that there will be any major change to these apps in the scope of oc10. Any new development effort is going into ocis .... :shrug:

**Comment by pako81** [comment]
do we want to have this in 10.13? Review is still required.

**Comment by DeepDiver1975** [comment]
review was requested via rocketchat and done by jp .....

**Comment by mmattel** [comment]
> review was requested via rocketchat and done by jp .....

...but no approval made
maybe to add persons to the review list here making it easier to get that approved?

**Review by jvillafanez — APPROVED** [review]

**Comment by Salipa-Gurung** [comment]
Tested with:
ownCloud 4.2.0.11670 f5a29b
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: wincfapi
windows-10.0.19045

Server version : ownCloud 10.13.0 beta 1 (stable)

Screenshot (28)

**Comment by jnweiger** [comment]
* [ ] enable drawio app
   Route `/app/list` reports
```
{"mime-types":[{"mime_type":"application\/x-drawio","app_providers":[{"name":"draw.io","icon":"https:\/\/avatars.githubusercontent.com\/u\/1769238?s=200&v=4"}],"ext":"drawio","name":"draw.io (diagrams.net)","description":"draw.io (diagrams.net) document","default_application":"draw.io"}]}
```

* [ ] enabled drawio and wopi app (no office server configs needed)

```
{"mime-types":[{"mime_type":"application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet","app_providers":[{"name":"MS Office","icon":"https:\/\/www.pikpng.com\/pngl\/m\/343-3435764_onlyoffice-desktop-editors-onlyoffice-logo-clipart.png"}],"ext":"xlsx","name":"Microsoft Excel","description":"Microsoft Excel document","default_application":"MS Office"},{"mime_type":"application\/vnd.openxmlformats-officedocument.wordprocessingml.document","app_providers":[{"name":"MS Office","icon":"https:\/\/www.pikpng.com\/pngl\/m\/343-3435764_onlyoffice-desktop-editors-onlyoffice-logo-clipart.png"}],"ext":"docx","name":"Microsoft Word","description":"Microsoft Word document","default_application":"MS Office"},{"mime_type":"application\/vnd.openxmlformats-officedocument.presentationml.presentation","app_providers":[{"name":"MS Office","icon":"https:\/\/www.pikpng.com\/pngl\/m\/343-3435764_onlyoffice-desktop-editors-onlyoffice-logo-clipart.png"}],"ext":"pptx","name":"Microsoft Excel","description":"Microsoft Excel document","default_application":"MS Office"},{"mime_type":"application\/x-drawio","app_providers":[{"name":"draw.io","icon":"https:\/\/avatars.githubusercontent.com\/u\/1769238?s=200&v=4"}],"ext":"drawio","name":"draw.io (diagrams.net)","description":"draw.io (diagrams.net) document","default_application":"draw.io"}]}
```

* [  ] neither drawio nor wopi enabled

```
{"mime-types":[]}
```

-> Note that the icon URLS are remote URLs -> #40953

**Pull request merged**
