### PR TITLE
Fix OAuth external storage auth for step 2

### LINKED ISSUE #20835: Cannot mount dropbox on master
### Steps

1. Mount Dropbox storage as system-wide mount
```
{"reqId":"CCjK3fsHqvlp1ohDlm9+","remoteAddr":"127.0.0.1","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creating \\\\OC\\\\Files\\\\Storage\\\\Dropbox storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(259): OC\\\\Files\\\\Storage\\\\Dropbox->__construct(Array)\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(174): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n
#3 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(1, 'Dropbox', 'dropbox', 'oauth1::oauth1', Array, Array, Array, Array, 100)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n
#8 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n
#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(858): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n
#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n
#12 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/dropbox.php\",\"Line\":59}","level":3,"time":"2015-11-30T13:31:54+00:00","method":"PUT","url":"\/owncloud\/index.php\/apps\/files_external\/globalstorages\/1"}
```

### Version
Observed on master (a94819f4a47ba98b185c9c75eab43d8cb933ed5c)

@icewind1991 @Xenopathic 

Bisect will follow.

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Parameters are only available after the onCompletion promise is run

Fixes #20835 

cc @PVince81 @icewind1991 

This needs serious testing, both Dropbox and GDrive storages.

### CODE REVIEW

**Comment by Xenopathic** [comment]
Gee, that's useful @mention-bot

**Comment by LukasReschke** [comment]
Yeah. That's https://github.com/facebook/mention-bot/issues/66 :speak_no_evil:

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/pull/21517/files?w=1 <- easier to review

**Comment by PVince81** [comment]
Tested, works :+1: 

@davitol @MorrisJobke second review ?

**Comment by davitol** [comment]
:+1: WFM now

**Pull request merged**
