### PR TITLE
Stable9 integration tests refactoring

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Backport of https://github.com/owncloud/core/pull/26235

### CODE REVIEW

**Comment by PVince81** [comment]
Test failed: ' /var/lib/jenkins/workspace/owncloud-core_core_PR-26666-CPCQE56ODM5DBDSTILRD55B5A6C53RQJOJT4PQVVGYUA2VOUB3WA/build/integration/features/dav-v2.feature:5`

**Comment by SergioBertolinSG** [comment]
I've tried manually and if user doesn't log in previously, using cadaver he cannot see his files yet.
 It answers 'Did not find a collection resource'. When the users logs in he can see it.

**Comment by SergioBertolinSG** [comment]
This doesn't happen in master. The not previously logged in user can browse his files using cadaver in dav endpoint.

**Comment by PVince81** [comment]
in `FilesPlugin::checkMove`, during the test:
```
$source                          = (string[25]) 'files/user0/textfile0.txt';
$destination                     = (string[32]) 'files/user0/FOLDER/textfile0.txt';
```

when done manually with cadaver:
```
// by property_get
$source                          = (string[13]) 'textfile0.txt';


// by property_get
$destination                     = (string[20]) 'FOLDER/textfile0.txt';
```

something fishy with absolute paths vs relative paths on the new DAV endpoint.

**Comment by PVince81** [comment]
On stable9.1 the values are the same so the test is fine.
But on stable9.1 there's a fix for MOVE on the new dav endpoint. Let me check how to backport it...

**Comment by PVince81** [comment]
Seems some fix is here https://github.com/owncloud/core/pull/24971 but not directly backportable because it relies on another fix.

Ok... Let's remove the dav v2 move test for now and process it separately.
I'll make a separate PR for that one.

**Comment by PVince81** [comment]
Removed failing test, submit separately: https://github.com/owncloud/core/pull/26707

**Comment by PVince81** [comment]
sharing-v1.feature:769 passes for me now on this PR, so let's hope everything else passes too

**Comment by PVince81** [comment]
Woohoo, all green 👍

**Pull request merged**
