### PR TITLE
no php execution timeout for webdav

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@icewind1991 @PVince81 @MorrisJobke @karlitschek 

@dragotin @guruz @ogoffart 

This might help to prevent timeouts on long running operations ....

### CODE REVIEW

**Comment by karlitschek** [comment]
hmm. radical approach. but why not. ;-)   :+1:

**Comment by PVince81** [comment]
Should we make this configurable ? In case admins aren't happy with long running PHP processes

**Comment by DeepDiver1975** [comment]
> Should we make this configurable ? In case admins aren't happy with long running PHP processes

Maybe there are php.ini settings to overwrite? no clue :speak_no_evil: @bantu any idea? or objections against about this approach?

**Comment by guruz** [comment]
:+1:
Looks nice
(Although remember that the client also has timeouts and will see a request as timeouted after some time..)

CC @ckamm

**Comment by bantu** [comment]
This doesn't belong in appinfo?

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
> This doesn't belong in appinfo?

You mean the file itself? Well this is there from the very first day ....

**Pull request merged**
