### PR TITLE
be a little more verbose in the exception message when we cant connect to...

### PR DESCRIPTION
**Pull request by icewind1991**
... the db

(I would never forget to start mysql two times in two days....)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
cc @rullzer @Xenopathic @nickvergessen do you want to review?

**Comment by Xenopathic** [comment]
I already see `Can't connect to MySQL server` in the error log - do other database types not print this or similar?

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
