### PR TITLE
Fix files:scan repair + basic tests for files:scan command

### PR DESCRIPTION
**Pull request by PVince81**
~~Will fail on CI, pass locally, needs work...~~

### CODE REVIEW

**Comment by PVince81** [comment]
Ohhh that explains the failure: `Testing with oci ...`

**Comment by PVince81** [comment]
running this one test class locally with oci passes... now to run the full set...

**Comment by PVince81** [comment]
boo... local test run with Oracle and all tests does not fail...

**Comment by PVince81** [comment]
also ran tests locally with filtering by group "DB" with oci, still doesn't fail...

**Comment by PVince81** [comment]
@owncloud-bot rebase

**Comment by PVince81** [comment]
rebased and hoping for some magic resolution...

**Comment by PVince81** [comment]
@owncloud-bot rebase please

**Comment by PVince81** [comment]
@ownclouders rebase please

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
Oh wait, it's the primary object store tests failing! I'll exclude those as scanning doesn't make sense there.

**Comment by PVince81** [comment]
rebased again, not sure why the npm/yarn stuff wasn't picked up

**Comment by PVince81** [comment]
wow

>OK, but incomplete, skipped, or risky tests!
>Tests: 9561, Assertions: 35816, Skipped: 202.
>Segmentation fault

**Comment by sharidas** [comment]
Looks like changing to PHP 7.1 worked.

**Comment by PVince81** [comment]
If this is related https://github.com/travis-ci/travis-ci/issues/8748, it seems we might need to switch the XDebug version on Drone ? @SergioBertolinSG @DeepDiver1975

**Comment by PVince81** [comment]
Feel free to push on this branch to experiment

**Comment by patrickjahns** [comment]
@PVince81 not using xdebug in drone - using `phpdbg` - investigating currently if I can reproduce it locally

**Comment by patrickjahns** [comment]
Travis is also failing with a segmentation fault:
https://travis-ci.org/owncloud/core/jobs/331986111#L2452

**Comment by PVince81** [comment]
so we need phpunit 6 on master and php unit 5 on stable10

**Comment by PVince81** [comment]
I'm going to remove all experimental commits then rebase on top of master where we removed memcache

**Comment by PVince81** [comment]
rebased

**Comment by PVince81** [comment]
Rebased and solved conflicts with @sharidas' tests.

I removed the UserTrait because we were not using it properly: we were missing `setupUserTraits`.

However now it looks like the test is taking much longer so I'll likely bring back the UserTrait and make my tests use it to hopefully improve performance. I also wonder whether we should just mock the whole thing instead...

**Comment by PVince81** [comment]
Looks like I can't use UserTrait for my own tests because the regular non-group scan uses `UserManager->search()` which cannot find the users to scan because the AccountManager is mocked.

For groups it works because it doesn't rely on "oc_users table" but "oc_group_user" table which has membership info.

**Comment by PVince81** [comment]
Ok fixed: it turns out that the `MemoryAccountMapper` used for mocking did not properly support empty pattern for `search` method. Fixed now, scan tests passed locally.

**Comment by PVince81** [comment]
some weird errors not even related to this PR... it's like it was testing another PR...

anyway, rebased

**Comment by PVince81** [comment]
Not even related to my PR ?!

```
1) OCA\Files\Tests\Command\ScanTest::testScanRepairAllInMaintenanceMode with data set #0 (array(array('singleuser', false, true), array('maintenance', false, false)))
ArgumentCountError: Too few arguments to function OC\Repair\RepairMismatchFileCachePath::__construct(), 2 passed in /drone/src/apps/files/lib/Command/Scan.php on line 157 and exactly 3 expected
```

**Comment by PVince81** [comment]
oh wait, I read it wrong... oh...

**Review by tomneedham — APPROVED** [review]
Makes sense. Tests run locally and repair/scan command runs fine.

**Comment by PVince81** [comment]
requires backport of https://github.com/owncloud/core/pull/30020 to not have conflicts on ScanTest

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/30618

**Comment by PVince81** [comment]
Repair command was broken through https://github.com/owncloud/core/pull/30451 (unreleased), so this PR could be counted as an addition to this one to fix it.

**Pull request merged**
