### PR TITLE
[master] Option to reenable users when syncing with a backend

### PR DESCRIPTION
**Pull request by tomneedham**
Forward port to master of this PR https://github.com/owncloud/core/pull/31124

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
resolve conflicts please and rebase

**Comment by mmattel** [comment]
@tomneedham 
Can you please take a look on that because stable10 has been merged but not this one - please check !

**Comment by mmattel** [comment]
BTW, I would really like to see [master] in front of the description to identify this as forwardport - else these things get forgotten easily AND we can´t filter them ...

**Comment by butonic** [comment]
@mmattel the best I could do for a more polished help message is this
```console
$ ./occ user:sync --help
Usage:
  user:sync [options] [--] [<backend-class>]

Arguments:
  backend-class                                        The quoted PHP class name for the backend, eg
                                                       - LDAP:		"OCA\User_LDAP\User_Proxy"
                                                       - Samba:		"OCA\User\SMB"
                                                       - Shibboleth:	"OCA\User_Shibboleth\UserBackend"

Options:
  -l, --list                                           List all enabled backend classes
  -u, --uid=UID                                        Sync only the user with the given user id
  -s, --seenOnly                                       Sync only seen users
  -c, --showCount                                      Calculate user count before syncing
  -m, --missing-account-action=MISSING-ACCOUNT-ACTION  Action to take if the account isn't connected to a backend any longer. Options are "disable" and "remove". Note that removing the account will also remove the stored data and files for that account.
  -r, --re-enable                                      When syncing multiple accounts re-enable accounts that are disabled in ownCloud but available in the synced backend.
  -h, --help                                           Display this help message
  -q, --quiet                                          Do not output any message
  -V, --version                                        Display this application version
      --ansi                                           Force ANSI output
      --no-ansi                                        Disable ANSI output
  -n, --no-interaction                                 Do not ask any interactive question
      --no-warnings                                    Skip global warnings, show command output only
  -v|vv|vvv, --verbose                                 Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Synchronize users from a given backend to the accounts table.
```
moving the description to a different place would require hacking around the framework used to render the help messages.

I also removed some of the description. `quoted` has the same meaning as `Please wrap the class name in double quotes.` and the `You can use the option --list to list all known backend classes.` is completely redundant.

**Comment by mmattel** [comment]
@butonic 👍 great !
please also fix stable10 so it is consistent with master

**Comment by mmattel** [comment]
I have updated the documentation PR (https://github.com/owncloud/documentation/pull/4173) accordingly, matching now this output

**Comment by butonic** [comment]
pinging @DeepDiver1975 for an outside review because tom and I messed with this

**Comment by mmattel** [comment]
@butonic can you update the help description for stable10 too so it is consistant and link that PR with this one ?
@DeepDiver1975 could you do the review, stable10 is already merged and we are diverging...

**Comment by mmattel** [comment]
@DeepDiver1975 need to ping you on that PR...

**Comment by tomneedham** [comment]
Rebased and squashed

**Comment by PVince81** [comment]
I've fixed the PHP CS issues and squashed

**Review by PVince81 — APPROVED** [review]
:+1: otherwise

**Comment by phil-davis** [comment]
``stable10`` PR #31124 is also merged. backport-request label is no longer needed.

**Pull request merged**
