### PR TITLE
Fix removal of share permissions when share disabled for user

### LINKED ISSUE #13306: Remove share permissions on mount points failure
I'm working with Owncloud 7.0.4.2

The file lib/private/files/view.php generates the following error when a user without share permissions but with a file or a folder shared with him views his filesystem root.

**PHP 	Undefined variable: content at [...]/lib/private/files/view.php#1030**

The error is generated when Owncloud tries to remove share permissions for the file. Looks like a bad copy-paste issue ;)
I would replace this line (view.php, line 1030)
**$content['permissions'] = $content['permissions'] & ~\OCP\PERMISSION_SHARE;**
with this one
**$rootEntry['permissions'] = $rootEntry['permissions'] & ~\OCP\PERMISSION_SHARE;**

It's not such a problem for me because I do not allow resharing, it just fills my log file with errors. However, it could be a problem for other people if some of their users have more rights than expected.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/13306

Please review @icewind1991 @Xenopathic @DeepDiver1975 @MorrisJobke @nickvergessen

### CODE REVIEW

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by Xenopathic** [comment]
:+1:

**Comment by Xenopathic** [comment]
Needs backporting to stable8.1 and stable8 (and stable7?) too BTW, confirm @karlitschek ?

**Comment by karlitschek** [comment]
yes. confirme :-)

**Comment by PVince81** [comment]
It's not critical as it only shows a warning in the console.
I suggest backporting only to 8.1.

**Comment by PVince81** [comment]
stable 8.1 PR: https://github.com/owncloud/core/pull/18135

**Pull request merged**
