### PR TITLE
Backporting #14125 to stable8, as called for by @LukasReschke

### PR DESCRIPTION
**Pull request by dratini0**
I still not very experienced with git, but @LukasReschke , is this what you have meant?

### CODE REVIEW

**Comment by dratini0** [comment]
This contribution is MIT licensed.

**Comment by Xenopathic** [comment]
@owncloud-bot ok to test

**Comment by LukasReschke** [comment]
@dratini0 Yep. That was what I asked for. THX!

**Comment by LukasReschke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
refs #14125

**Comment by DeepDiver1975** [comment]
@karlitschek 8.0.3 still open for backports?

**Comment by karlitschek** [comment]
we are already in the RC phase for 8.0.3 so this has to wait for 8.0.4 Let´s keep the backport-request tag so that we can find this again later

**Comment by DeepDiver1975** [comment]
> we are already in the RC phase for 8.0.3 so this has to wait for 8.0.4

moving this to 8.0.4 milestone - thx for clarification

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
