### PR TITLE
Hide updater.secret from occ output by default

### PR DESCRIPTION
**Pull request by LukasReschke**
We should not have people post that value to us.

@karlitschek @VicDeo

### CODE REVIEW

**Comment by VicDeo** [comment]
:+1:

**Comment by LukasReschke** [comment]
On a related note, there is still the risk of people posting that to us somehow considering that there nowadays are as well people that post their `secret` to us.

The `updater.secret` is way grave to be leaked. We should in the future make sure that the updater app should not allow arbitrary code execution. Right now it's an endpoint where we send the payload and it gets executed.

Also we should think about how we could harden that more. For example starting with decreasing the timeout to less than 24 hours there.

**Comment by LukasReschke** [comment]
Limiting it to an IP also seems like a feasible idea. Makes it a tad harder to manually configure it (e.g. somebody needs to lookup their IP) but is probably really worth it considering some of our users…

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
