### PR TITLE
[8.1] Dont output paths in scan.php

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of #20733

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Ah ... You deleted the wrong line. :(

**Comment by MorrisJobke** [comment]
> Ah ... You deleted the wrong line. :(

Let me fix this.

**Comment by MorrisJobke** [comment]
> Let me fix this.

#21463

**Pull request merged**
