### PR TITLE
[stable8.2] Hide revert button when no permission to revert

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/25288 to stable9

Please review  @georgehrke @VicDeo @DeepDiver1975 @owncloud/filesystem

### CODE REVIEW

**Comment by PVince81** [comment]
I retested this and it works fine

**Comment by PVince81** [comment]
Unit tests will fail, there is no share manager in 8.2 :disappointed:

**Comment by PVince81** [comment]
Okay, I fixed the tests :smiley:

**Comment by PVince81** [comment]
Please review @DeepDiver1975 @VicDeo @georgehrke @owncloud/filesystem @butonic

**Comment by jvillafanez** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
