### PR TITLE
make sure we actually have an object store

### PR DESCRIPTION
**Pull request by icewind1991**
Verify that we actually have an object store

cc @Xenopathic @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Makes sense :+1: 

@LukasReschke can you confirm ?

**Comment by Xenopathic** [comment]
:-1:

**Comment by PVince81** [comment]
@Xenopathic no happy ?

**Comment by LukasReschke** [comment]
I'd also prefer to have a check in the appropriate storage controllers whether the passed storage contains an objectstore, probably we can add this at https://github.com/owncloud/core/blob/69e72eeb37b6d0084c137e1cffffe8717c2f1de0/apps/files_external/controller/storagescontroller.php#L81

That said this addition on it's own can from my PoV stay but we should have a double-fallback.

**Comment by Xenopathic** [comment]
Agreed. This PR is mostly a sanity check, but we need to check in storage validation to hard-fail if an objectstore is specified at all.

**Comment by LukasReschke** [comment]
What's the state on this?

**Comment by PVince81** [comment]
Needs rebase and review

**Comment by icewind1991** [comment]
rebased

**Comment by Xenopathic** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
