### PR TITLE
Don't swallow errors in console.php

### PR DESCRIPTION
**Pull request by kampka**
In the current implementation, console.php swallows unhandled exceptions instead of propagating an error to the calling shell.
This makes error handling in scripts difficult.

I agree to license this commit under the MIT license as well as AGPL as required.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot This is okay to test.

**Comment by LukasReschke** [comment]
cc @DeepDiver1975 Please review. You know more about that script than me :smile:

**Comment by Xenopathic** [comment]
:+1: This will definitely help integrating occ with external scripts.

**Comment by karlitschek** [comment]
I agree. :+1:  @DeepDiver1975 What do you think?

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Pull request merged**
