### PR TITLE
Use memcaching in AppConfig

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Running `\OC_Util::needUpgrade()` 1000 times:

graph

graph2

cc @PVince81 @DeepDiver1975 @MorrisJobke @LukasReschke @karlitschek @georgehrke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
```
00:33:32.225 1) Test_Appconfig::testSetValueUnchanged
00:33:32.226 Argument 2 passed to OC\AppConfig::__construct() must be an instance of OC\Memcache\Cache, none given, called in /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/tests/lib/appconfig.php on line 127 and defined
00:33:32.226 
00:33:32.226 /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/private/appconfig.php:58
00:33:32.226 /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/tests/lib/appconfig.php:127
00:33:32.226 
00:33:32.226 2) Test_Appconfig::testSetValueUnchanged2
00:33:32.227 Argument 2 passed to OC\AppConfig::__construct() must be an instance of OC\Memcache\Cache, none given, called in /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/tests/lib/appconfig.php on line 162 and defined
00:33:32.227 
00:33:32.227 /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/lib/private/appconfig.php:58
00:33:32.227 /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/tests/lib/appconfig.php:162
```

**Comment by Xenopathic** [comment]
I disabled two tests, since it requires a cache implementation and #13211 hasn't been implemented yet so there is no reliable cache implementation available.

**Comment by Xenopathic** [comment]
Right, so the problem with those two unit tests is that they expect trying to set the same value multiple times to do nothing (aka not attempt a database update/insert). That was the previous logic, but I've changed it so that any 'set' clears the relevant caches first, then pushes to the database. As such, there is no mechanism to prevent the redundant database queries. The question is, do we want to keep the original behaviour? Is the performance degredation of setting a value multiple times to the same thing (which shouldn't be happening anyway) so bad that we need to protect against it? cc @DeepDiver1975 @PVince81 @MorrisJobke

**Comment by DeepDiver1975** [comment]
hmm - caching the app config in ram (to ensure stuff is queried from the db only once in one request) should be enough from my pov.

We need to make sure that to intensive memcaching will not break the functionality - refs #13658 

Furthermore the time saving on this use case seems rather little.

@icewind1991 @PVince81 your opinions please - THX

**Comment by icewind1991** [comment]
https://github.com/owncloud/core/pull/13829 already saved most of the time from the comparison by caching enabled apps

**Comment by Xenopathic** [comment]
@icewind1991 From what I can tell, #13829 only enables the array cache of AppManager, not a Memcache like this PR introduces.

**Comment by icewind1991** [comment]
Yes, but that combined with #13852 removes most of the performance advantage from this PR.

Can you make a new comparison

**Comment by Xenopathic** [comment]
@icewind1991 on it

**Comment by Xenopathic** [comment]
Hmm. 10ms difference, for a total of 0.5% improvement! Of course, this is a synthetic benchmark calling the one function thousands of times, not multiple requests (where the memcache way will save queries) but I think this PR has become redundant.

**Pull request closed without merging**
