### PR TITLE
Update to doctrine DBAL v3

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
This is needed to run PostgreSQL with a persistent connection.

## Related Issue

- Needed for https://github.com/owncloud/enterprise/issues/4613

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JammingBen** [comment]
@micbar As discussed I've opened this draft PR for the doctrine DBAL update. As expected this is a *huge* one.

This PR includes some minor changes already. But we basically need to adjust every database interaction because methods like `fetch()` or `closeCursor()` are not available anymore. Maybe we could introduce some kind of compatibility layer by implementing own DB classes which "translate" our old methods to new ones. I'll check 👍

**Comment by phil-davis** [comment]
Link to upgrade notes: https://github.com/doctrine/dbal/blob/3.1.x/UPGRADE.md
https://github.com/doctrine/dbal/blob/3.1.x/composer.json requires PHP minimum of 7.3, which I see is done in this PR.
PR #38697 has the minimal core changes needed to drop PHP 7.2 (without increasing major versions of dependencies) - look there for "interesting stuff"  that you will need to do for that.

The dropping PHP 7.2 has been advised in release notes of at least 10.6 and 10.7. So it is not a surprise, when we do it. But if it is going to happen for 10.8, then someone needs to decide that ASAP.

**Comment by JammingBen** [comment]
Okay, so I managed to get OC running with the update. The main things that changed for us:

* Minimum PHP version is 7.3 (was 7.2 previously)
* Type constants are now located in `Doctrine\DBAL\Types\Types` (was `Doctrine\DBAL\Types\Type` previously)
* `closeCursor()` is now `free()`
* `\Doctrine\DBAL\DBALException` is now `\Doctrine\DBAL\Exception`
* The `Statement` interface no longer extends `ResultStatement`. That means we cannot fetch from a statement directly like we often do.
* ...and some more "minor" changes

Note that this PR does not provide options for backwards-compatibility. That means while core might run fine, most (or all) of our apps probably wont. I guess we could go for some implementations to ensure backwards-compatibility, but we have to dig deeper.

To the main reason for going on this adventure: I tried running with PostgreSQL and a persistent connection, it seems(!) to run. Meaning, I don't get any errors like before. But I cannot tell for sure if the connection is now persistent 🤷  

@micbar what do you suggest?

**Comment by micbar** [comment]
>     * Minimum PHP version is 7.3 (was 7.2 previously)
Not a problem, we wanted to remove php7.2 support anyway. 
>     * Type constants are now located in `Doctrine\DBAL\Types\Types` (was `Doctrine\DBAL\Types\Type` previously)
will be used across a lot of apps
>     * `closeCursor()` is now `free()`
same
>     * `\Doctrine\DBAL\DBALException` is now `\Doctrine\DBAL\Exception`
same
>     * The `Statement` interface no longer extends `ResultStatement`. That means we cannot fetch from a statement directly like we often do.
same
>     * ...and some more "minor" changes
same
> 
> Note that this PR does not provide options for backwards-compatibility. That means while core might run fine, most (or all) of our apps probably wont. I guess we could go for some implementations to ensure backwards-compatibility, but we have to dig deeper.

Main Effort: identify all changes in all apps that are needed. Would need a big release effort.
> 
> To the main reason for going on this adventure: I tried running with PostgreSQL and a persistent connection, it seems(!) to run. Meaning, I don't get any errors like before. But I cannot tell for sure if the connection is now persistent 🤷

That is good news, but we would need to be sure. we need support help and maybe benchmarking.
> @micbar what do you suggest?

1) Use this branch as a experiment to understand really if that solves our DBConnection requirements.
2) if yes: Estimate the changes in the apps.

**Comment by JammingBen** [comment]
One thing I can already tell regarding performance: Getting the connection is noticeably faster in persistent mode while using a SSL connection.

A simple time test on my local setup:

* Without persistent: 0.04s
* With persistent: 0.002

https://github.com/owncloud/core/blob/eebd754771a99bc44820eb67a6d57cea238e6b86/lib/private/DB/ConnectionFactory.php#L137

**Comment by JammingBen** [comment]
Closing for now as we won't do this anytime soon. We can reopen one day if necessary.

**Pull request closed without merging**
