### PR TITLE
General review of integration test code

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Remove unused ``use`` statements.
2) Make gherkin statements have lowercase letter to go after "Given" "When" "Then" "And"...
3) Code formatting stuff
4) Sort out "Given" "When" "Then" "And" to be consistently used.
5) In ``sharing-v1`` some downloading tests use ``welcome.txt`` of the ``admin`` account. When running in a local dev environment that is being used for a bunch of different work, different types of tests, then maybe the skeleton files when the ``admin`` account was set up do not have a ``welcome.txt`` with the expected content. (or...) Change those tests so that they use an account (``user0``) that has just been created. That will guarantee that the expected ``welcome.txt`` will be there to download.

Point (5) is the only one that makes a functional change here.

## Motivation and Context
Make the integration tests code more consistent.
After #28922 it seems good to look through the integration tests and see if any other tests might not be doing quite what is expected.

## How Has This Been Tested?
Integration test runs locally.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by individual-it — APPROVED** [review]
no function changes, formatting and rewording looks fine.
Passing of CI proves that you haven't forgotten anything.

Need robots or interns for this kind of work 😁

**Comment by phil-davis** [comment]
The PHPstorm IDE robot was quite good at doing "Refactor..." for some changes, and "Replace in path..." etc. Once I learned the IDE features, many of the changes were quite easy to apply.

**Comment by phil-davis** [comment]
I will merge this now.
@SergioBertolinSG @davitol please comment next week if you would like any of this formatting better or different and I will make more changes in a later PR.

**Comment by phil-davis** [comment]
Backport stable10 #28955

**Pull request merged**
