### PR TITLE
Stable8.1 chunk cleanupgracefulonlock

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/17259 to stable8.1

Pending approval @karlitschek @cmonteroluque 
This would be for 8.1.1 as discussed.

### CODE REVIEW

**Comment by karlitschek** [comment]
as discussed :+1:

**Comment by karlitschek** [comment]
please merge after 8.1.0 is done

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Jenkins PR https://github.com/owncloud/core/pull/17299

**Comment by MorrisJobke** [comment]
> Jenkins PR #17299

This is completely different code.

**Comment by MorrisJobke** [comment]
> This is completely different code.

From #17289 ... I will fix the jenkins PR.

**Comment by PVince81** [comment]
I might have mixed up the Jenkins PRs... I had to raise a bunch...

**Comment by PVince81** [comment]
@MorrisJobke no, this looks correct to me. Maybe you mixed up the PRs when checking ? Anyway, whichever Jenkins PR, when done, should update the correct status.

**Comment by MorrisJobke** [comment]
> @MorrisJobke no, this looks correct to me. Maybe you mixed up the PRs when checking ? Anyway, whichever Jenkins PR, when done, should update the correct status.

I force pushed the correct commits ;)

**Comment by MorrisJobke** [comment]
Tests passed: https://github.com/owncloud/core/pull/17299#issuecomment-117978631

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
