### PR TITLE
[stable10] Check apache auth on login form

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/core/pull/31054 to stable10

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]
Not tested - but fine by me if it work ... needs testing

**Comment by patrickjahns** [comment]
@tomneedham 
What needs to be tested exactly?

This PR with latest shibboleth release, or latest shibboleth development part?

**Comment by tomneedham** [comment]
Setup:
 - core @ this PR
 - user_ldap @ 0.10.0
 - user_shibboleth @ https://github.com/owncloud/user_shibboleth/pull/208

Test 1:

 - Configure LDAP user backend
 - Configure Shibboleth in SSO mode
 - Try to login

Without this: Doesn't login.
With PR: login should work

Test 2:

 - Configure Shibboleth in autoprovison mode
 - Try to login

Without this: Doesn't login.
With PR: login should work

**Comment by patrickjahns** [comment]
Tested positive case:
- ldap 0.10.0 from marketplace
- user_shibboleth
```
1fbc668d71c1082635665f794f6d9b09215f86a6 (HEAD -> sync-in-core, origin/sync-in-core) fix phpdoc
```
- owncloud 
```
0fbda7b22bb0a6c57e8eb476c8787d4ab2a9275a (grafted, HEAD -> stable10-fix-apache-auth, origin/stable10-fix-apache-auth) Check apache auth on login form
```

Status: ✅ 


Testing negative case:
- ldap 0.10.0 from marketplace
- user_shibboleth
```
1fbc668d71c1082635665f794f6d9b09215f86a6 (HEAD -> sync-in-core, origin/sync-in-core) fix phpdoc
```
- owncloud - stable10 branch
```

```

Status: 🚧

**Comment by tomneedham** [comment]
>redirect loop 302
>just ending up on the login screen without anything happening

both expected haviours

**Comment by patrickjahns** [comment]
@tomneedham 

Another thing noticed - any signed in request will trigger an ldap auth request - example:
```
openldap_1  | 5acccfad conn=1023 fd=15 ACCEPT from IP=172.18.0.6:56826 (IP=0.0.0.0:389)
openldap_1  | 5acccfad conn=1023 op=0 BIND dn="cn=admin,dc=owncloudqa,dc=com" method=128
openldap_1  | 5acccfad conn=1023 op=0 BIND dn="cn=admin,dc=owncloudqa,dc=com" mech=SIMPLE ssf=0
openldap_1  | 5acccfad conn=1023 op=0 RESULT tag=97 err=0 text=
openldap_1  | 5acccfad conn=1023 op=1 SRCH base="dc=owncloudqa,dc=com" scope=2 deref=0 filter="(&(objectClass=*)(cn=*)(uid=aaliyah_bruen*))"
openldap_1  | 5acccfad conn=1023 op=1 SRCH attr=dn uid samaccountname memberof cn entryuuid jpegphoto thumbnailphoto
openldap_1  | 5acccfad <= bdb_substring_candidates: (uid) not indexed
openldap_1  | 5acccfad conn=1023 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
openldap_1  | 5acccfad conn=1023 op=2 UNBIND
openldap_1  | 5acccfad conn=1023 fd=15 closed
owncloud_1  | 172.18.0.1 - "" [10/Apr/2018:14:52:28 +0000] "GET /oc-shib/index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 961 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
```

**Comment by patrickjahns** [comment]
Also tested with sync clients - when the user logged one time - it works - but aso `PROPFINDS` will cause a ldap search to be issued

**Comment by patrickjahns** [comment]
@tom @butonic 

Regarding ldap binds - following observation on stable10 ( dab8d0f67abf4a722c55813d4db6303724068cfc ) - and this PR:
when just authenticating via ldap - no further ldap request are triggered.

When logging in via shibboleth + ldap - I see frequent ldap search / binds going on

**Comment by butonic** [comment]
user_shibboleth needs to do a user search in order to look up the actual user id and responsible backend. That will make a bind with admin credentials (which is what you see in https://github.com/owncloud/core/pull/31074#issuecomment-380130522). In SAML scenarios we recommend oauth, which does not hammer ldap with additional checkPassword calls that would lead to user specific bind requests. 

In general the lookup user & backend magic is needed to autoprovision ldap users when auth happens via SAML. That code needs to move to core. If we do that we can first check if we have an account with the given username or email and only if it is unknown search the user backends. future work.

**Comment by patrickjahns** [comment]
@butonic 
see https://github.com/owncloud/user_shibboleth/issues/234 what I mean with a lot of requests for comparison.

The last commit from you in owncloud/user_shibboleth#208 has resolved the issue - but during testing that commit was not there yet

**Review by butonic — APPROVED** [review]

**Review by patrickjahns — APPROVED** [review]
With the right `user_shibboleth` branch it is working as expected -> needs to be checked when RC is ready

**Pull request merged**
