### PR TITLE
Statistics output for ./occ files:scan

### PR DESCRIPTION
**Pull request by mmattel**
PR for Issue #19593 (./occ command feature request - stat output on scanning)

This PR adds a statistics printout for the `sudo -u www-data ./occ files:scan` command.
New: works also in `--quiet` mode.

image

It handles also interruptions by pressing ctrl-c so you can see how far you have gone.

Current caveat: 
1. The number of files is not exactly correct because of Issue #19458 "Scanner sends folder through the scanFile event". When this is solved the number files are exact. (Info: the number of folders is beeing added to the number of files)
2. ~~Even I have prepared a stat printout when having parameter ´´--quiet´´, this is currently not beeing printed out. (*)~~

~~(*) Note: Something we should think about to have a possibility by a special parameter to printout data but not the full blast. eg we print statistic data but not each file/folder processed. Another exampe: there is also a problem when you do --quiet, but the code might request a user input (like: do you really want to... yes/no) - this would never been shown and would wait forever.~~

Many thanks to @oparoz for his inspiration.
@DeepDiver1975 @icewind1991

### CODE REVIEW

**Comment by karlitschek** [comment]
good idea. What do you think @icewind1991 
Unfortunately we are in feature freeze for 8.2

**Comment by DeepDiver1975** [comment]
Can we please get the new introduced code unit tested? THX

**Comment by mmattel** [comment]
@DeepDiver1975
> Can we please get the new introduced code unit tested?

Pls excuse, but what does that mean

**Comment by DeepDiver1975** [comment]
> Pls excuse, but what does that mean

We need unit tests for the scan command - this is the unit test for the cleanup command:
https://github.com/owncloud/core/blob/master/apps/files/tests/command/deleteorphanedfilestest.php

We need something similar for the scan command.

**Comment by mmattel** [comment]
@DeepDiver1975 what is the cause of the failing unit test. I read it but I do not understand it.
Regarding the unit test to be made, stupid question from myself, late at night... This is over my knowledge capabilities. Doesn´t this command already exist for some time and nobody made a test for?

**Comment by mmattel** [comment]
I am not really satisfied with having a printout (even for statistics) when using --quiet. The solution made is a compromise, because we only have a full blown printout or nothing.

Something in between is currently not made. See also in the ./occ documentation.
We have --quiet, --verbose is imho not an option, because naturally would mean more data then normal, at least for my understanding.

My suggstion would be to implement a --info parameter that is in between --quiet and --verbose. Based on the example above we would then have following options:

option | printout
-------- | ----------
n.a. | full printout (eg list all the files and folders processed plus statistics)
--quiet | nothing, even no statistics
--info | statistics only

I would handle  --quiet and --info the same during processing but decide at the end if eg statistics are printed or not. I have already tested this and it would work perfect.

@karlitschek @DeepDiver1975 My question: what is your opinion, because this also would mean a documentation update and/or other  ./occ commands could use this --info option parameter too. I also suggest that the --info parameter would then in the documentation be used as explicit mentioned option in the particular command where available.

**Comment by oparoz** [comment]
I think it all depends on the definition of quiet. If the output is never read or any output is treated as an error, then it might be worth adding an extra option. I find "info" to be too vague and would prefer "stats".

**Comment by mmattel** [comment]
@oparoz I had in my first attempt the term ``stats`` instead of ``info``. Than I remembered your occ gallery:xxxhumbnail commands where you eg have a question before you delete. My thinking was now the following: if I name it ``stats``, it would not satisfy the idea that there is a possibility to have a user-interaction (eg a question), so I wanted to be more open and named it ``info``. It can be named anything, but we should consider that this term could be used in other commands too and we should avoid imho creating too many terms for options. Pls let me know if I am on the right track or ...

**Comment by oparoz** [comment]
Looking at the doc, I don't think "quiet" means non-interactive, so it's OK to ask questions and from my pov, even to present stats without any additional flag.

**Comment by mmattel** [comment]
From: https://github.com/owncloud/documentation/blob/master/admin_manual/configuration_server/occ_command.rst
````
--quiet (-q)          Do not output any message
````

That´s the reason why I am asking

**Comment by oparoz** [comment]
Then that documentation could be updated, because

> If you want to suppress the output of the executed command, pass a NullOutput as the second argument to $command->execute().

http://symfony.com/doc/current/components/console/introduction.html

**Comment by mmattel** [comment]
@oparoz Maybe I did not get it what you mean, but currently we suppress all output with --quiet.

I raise the question how we should handle a small output (vs the full blown stuff when not using --quiet). Either we accept that --quiet does do some printout - then we have to change the occ documentation or we implement a new option which makes it clear that there is a printout but not like in scan the full blown one.

I would like to know the preference from experts and in case of a new option a suggested name for this option.

My personal POV is, that --quiet should do how it is documented - beeing fully quiet and implement a new option (suggestion: info) beeing in between of --quiet and full printout.
It is also to be considered, that when using an occ command as part of an admin script, a printout when using --quiet may have impacts.

**Comment by mmattel** [comment]
Hmm, sometimes you need some sleep to get new thoughts :smile: 

One option would be, and this sounds to me the best solution (feedback welcomed), to do the following:

1. Keep the options list and the description for as it is. 
Means we have option parameter: --quiet, nothing, -v (verbose).
2. On --quiet we do no printout at all, but if there is a question to be made reqiring a user input than do this -> documentation change needed
3. On no option provided, we printout the statistics but not the full blown list
4. On -v we behave th same as like no ption provided but also print the files currently processed 

There is one drawback: is it justifyable that by this change a user who is used to have the full printout providing no parameter now needs to add the option -v to get it.

**Comment by mmattel** [comment]
Based on my comment above (https://github.com/owncloud/core/pull/19717#issuecomment-148649113), I have rewritten the code to use --quiet and --verbose for the decision which data will be printed to the console. I will create a documentation PR where the use of --verbose in files:scan is reflected.

**Comment by mmattel** [comment]
@DeepDiver1975 
you requested to have a test for the occ files:scan command.
The command was long time ago implemented and I just do an update to printout statistics.
Due to time constraints, I can´t do the coding for, but it would be great if there is a way to get that merged as this is really helpful for admins.

**Comment by mmattel** [comment]
I am closing this because of a rebase problem and file a fresh PR
New PR is at #21201

**Pull request closed without merging**
