### PR TITLE
Notifications context test steps to core 2

### PR DESCRIPTION
**Pull request by phil-davis**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mmattel** [comment]
@phil-davis mind to add some description ?

**Comment by phil-davis** [comment]
It is "developing" - I am first trying to work out what to do and how to make it work properly in drone. When I know, I can write description :)

**Comment by mmattel** [comment]
Completely understand, just taking your words
> another try similar to #31665 - I was messing about seeing why notifications app did not get properly enabled. Turns out to be an issue - #31669

Why not writing this, can be edited afterwards when more details are there

**Comment by phil-davis** [comment]
This was testing only.

**Pull request closed without merging**
