### PR TITLE
Only do the description kung-fu on strings

### LINKED ISSUE #17028: Log errors after upgradde 7.0.4 -> 8.0.4
Hello,

I just upgraded from ownCloud 7.0.4 to 8.0.4, using the build in update center.
As described in several blog posts I found, I deactivated the old Calendar and Contacts app, before the actual upgrade.

The upgrade process itself went through without errors.
One thing bothers me after the upgrade:
Each time I open the App manager (.../index.php/settings/apps), two errors are reported into the log (see below).

Do you have any help on this?
Can you tell something about the errors' impact on owncloud's functionality?

### Steps to reproduce
* have a running ownCloud 7.0.4 server installation
* disable Calendar app and Contacts app
* upgrade from ownCloud 7.0.4 to 8.0.4 using integrated Update Center

### Expected behaviour
No log erros after upgrade procedure

### Actual behaviour
2 log errors each time when opening App manager

### Logs
```
{
	"reqId": "0f354fc916e8571fd11afda56f649625",
	"remoteAddr": "...",
	"app": "PHP",
	"message": "Invalid argument supplied for foreach() at ...\/lib\/private\/app.php#1233",
	"level": 3,
	"time": "2015-06-17T20:42:18+00:00"
},
{
	"reqId": "0f354fc916e8571fd11afda56f649625",
	"remoteAddr": "...",
	"app": "PHP",
	"message": "preg_split() expects parameter 2 to be string, array given at ...\/lib\/private\/app.php#1230",
	"level": 3,
	"time": "2015-06-17T20:42:18+00:00"
}
```

Kind regards,
Sascha.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #17028

@MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/pull/17252/files?w=1

:+1: 
but rebase required...

**Comment by MorrisJobke** [comment]
Rebased.

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Please open the backport PR ;)

**Pull request merged**
