### PR TITLE
Upgrade 3rdparty submodule for docterine v1.2.6

### PR DESCRIPTION
**Pull request by rullzer**
Submodule upgrade for https://github.com/owncloud/3rdparty/pull/179

CC: @LukasReschke @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Still works :+1:

**Comment by karlitschek** [comment]
So this was tested with all database including migration? ;-)

**Comment by LukasReschke** [comment]
@karlitschek Library update did not touch any DB related code: https://github.com/owncloud/3rdparty/pull/179/files#diff-d8d5c93115fc62fbc7d078fd73b6c5dfR165

**Comment by LukasReschke** [comment]
Actually it introduced PHP 7 compatibility and removed a logical error in unlinking temporary files.

**Pull request merged**
