### PR TITLE
Update phpseclib to 2.0 for increased PHP7 compatibility

### PR DESCRIPTION
**Pull request by bantu**
Depends on https://github.com/owncloud/3rdparty/pull/190

New Features Include:
- Minimum PHP Version 5.3.3
- PSR-4 autoloading with namespace rooted at `\phpseclib\`
  - Removal of PHP4 constructors
  - Removal of manual includes
  - One class per file
- Refactoring of function files into classes
- Some refactoring of defined constants into class constants (only true constants)
- Removal of side-effects from class files
- Removal of full license text from source code files
- Removal of the `phpseclib_resolve_include_path` function

### CODE REVIEW

**Comment by bantu** [comment]
@LukasReschke

**Comment by DeepDiver1975** [comment]
I just merged 3rdparty - please update submodule - THX

**Comment by bantu** [comment]
@DeepDiver1975 Done

**Comment by LukasReschke** [comment]
Crypto stuff still works. Can't judge SFTP though. Needs to get properly tested before the release :+1:

cc @rperezb

**Comment by DeepDiver1975** [comment]
> Can't judge SFTP though

*hust* sftp container for tests *hust* https://ci.owncloud.org/job/server-master-linux-externals/

@PVince81 @MorrisJobke there was an sftp docker - right? Did I miss anything? THX

**Comment by srt10coupe** [comment]
Thx

**Comment by MorrisJobke** [comment]
> @PVince81 @MorrisJobke there was an sftp docker - right? Did I miss anything? THX

I will have a look at them. It is present, but has two failing tests.

**Comment by srt10coupe** [comment]
i think it is chat app

**Comment by DeepDiver1975** [comment]
> I will have a look at them. It is present, but has two failing tests.

@MorrisJobke are these failing on master as well? AFAIK sftp unit test never fully passed

**Comment by MorrisJobke** [comment]
> @MorrisJobke are these failing on master as well? AFAIK sftp unit test never fully passed

Yes. Failing on master too and I have no idea why :see_no_evil:

**Comment by DeepDiver1975** [comment]
> Yes. Failing on master too and I have no idea why :see_no_evil:

so no regression and as a result we can merge this - please open an issue regarding failing sftp unit tests (if not already there - @PVince81 you already did have a look - right?)

**Comment by LukasReschke** [comment]
I bumped the 3rdparty reference to  https://github.com/owncloud/3rdparty/commit/0590498b38aa0c760e2ad7af4fbd19787d62ed4e

**Comment by PVince81** [comment]
I had a look at long time ago and don't remember why they failed.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
