### PR TITLE
[stable10] Fixes #31849 - delete thumbnails on write hooks

### LINKED ISSUE #31849: Thumbnail not regenerated as file changes
### Steps part 1

1. Login as "someuser"
1. Create a file "test.txt" and edit several times to create versions
1. Open the "Versions" tab in the sidebar
1. Restore some previous version
1. Close the "Versions" panel, even refresh the whole files page
1. Look at the thumbnail preview

### Expected results
Thumbnail shows content from the restored version.

### Actual result
Thumbnail shows unchanged content.

### Version
10.0.9RC1

### Steps part 2
There is no thumbnail update when doing upload-overwrite:
1. Upload some x.png file - observe the thumbnail looks like a small version of the file content
1. Locally edit/replace the x.png file with some other graphics content
1. Upload x.png and choose to keep the new file
1. Download x.png - check that is does have the new content

### Expected results
Thumbnail displays updated content

### Actual result
Thumbnail shows unchanged content.

### Steps part 3
There is no thumbnail update when editing and existing text file:
1. Create a new text file with some content - observe that the thumbnail shows the early content
1. Edit the text file in the webUI, changing some content early on line 1 (to make sure it should be part of the thumbnail)

### Expected results
Thumbnail displays updated content

### Actual result
Thumbnail shows unchanged content.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport #31853

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by phil-davis** [comment]
Tested all 3 scenarios in issue #31849 and they pass with this change.
I believe this is good  to merge to ``stable10`` for 10.0.9RC2? @PVince81

**Comment by PVince81** [comment]
yes, let's merge after CI reports green

**Comment by phil-davis** [comment]
woohoo - some code for 10.0.9RC2!

**Pull request merged**
