### PR TITLE
Adding global error handler for ajax calls which run into redirection…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…s or unauthorized responses

refs https://github.com/owncloud/core/pull/16726

@butonic @MorrisJobke 

Let see how far we re getting with this one.

### CODE REVIEW

**Comment by PVince81** [comment]
This fix is fine for testing, but note that it might break in cases where 302 might be an expected response (not sure which ones though).

There is a small chance that this breaks WebDAV connectivity detection as it might rely on 401 error codes. Not tested yet, but something to look into if we decide to keep this fix after all.

Ideal would be to have the server always return 401 instead of anything else when the authentication expired.

**Comment by DeepDiver1975** [comment]
> Ideal would be to have the server always return 401 instead of anything else when the authentication expired.

302 is used with shibboleth to redirect to the idp in case of session expiry - we might want to add some additional shib specific criteria ....

**Comment by PVince81** [comment]
Is that something that sits between Apache and the PHP code ? (aka hard to detect)

**Comment by DeepDiver1975** [comment]
> Is that something that sits between Apache and the PHP code ? (aka hard to detect)

well the js code might extract some information from the response itself - maybe some header used in an shib env ....

**Comment by butonic** [comment]
I tested this and ran into:
```
XMLHttpRequest cannot load https://idp.testshib.org/idp/profile/SAML2/Redirect/SSO?SAMLRequest=fZFdb4I…ss%3Amc%3A843092a07293cec8de8082ccda862a15578d7e87481b9ebe13dc61d0cbe6bd0d. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://lance' is therefore not allowed access.
```
As a result the status is 0 not 30x. Solved that by changing:
```diff
-		if (_.contains([302, 307, 401], request.status)) {
+		if (_.contains([0, 302, 307, 401], request.status)) {
```

After that the redirect worked bautifully for the list request, share action and heartbeat.

@DeepDiver1975 @LukasReschke does that make sense?

**Comment by butonic** [comment]
@LukasReschke @DeepDiver1975 should I just add that change as a commit? Then we test webdav again?

**Comment by DeepDiver1975** [comment]
Without shib enabled we should only react on 401. All the other cases are shibboleth only and should be treated within the shibboleth apps.

**Comment by PVince81** [comment]
How does shib behave with Webdav endpoints ? (asking for https://github.com/owncloud/core/pull/16902)

**Comment by PVince81** [comment]
Defer to 9.0 ?

**Comment by felixboehm** [comment]
If one of several webservers is down, we would need to handle a 503. Is it missing? I am not sure ...

**Comment by DeepDiver1975** [comment]
> If one of several webservers is down, we would need to handle a 503. Is it missing? I am not sure ...

Well if a webserver is physically down there should be no response at all and a timeout is raised.
Something to consider ... but let's first get this moving in.

**Comment by MorrisJobke** [comment]
@butonic This one is against master and not finished yet? We need this in 8.1.4? That is due in one week. 

cc @cmonteroluque Just to keep you posted.

**Comment by DeepDiver1975** [comment]
THX @MorrisJobke - the plan is to schedule this for 9.0 with a backport option to 8.2

Any 8.1.x instance needs manual patching @butonic

**Comment by MorrisJobke** [comment]
> Any 8.1.x instance needs manual patching @butonic

Okay. So no need to get this into 8.1.4? @butonic Please comment on this, because you changed the milestone.

**Comment by butonic** [comment]
We had a call with @cmonteroluque @bboule @MTRichards yesterday and as a result I changed the milestone. Since this PR does not contain the fix we need for shibboleth anyway I propose we add the necessary js directly to user_shibboleth as @DeepDiver1975 [proposed](https://github.com/owncloud/core/pull/16783#issuecomment-114049829). We need to test compatibility with 8.1.4 anyway.

**Comment by DeepDiver1975** [comment]
> We had a call with @cmonteroluque @bboule @MTRichards yesterday and as a result I changed the milestone. Since this PR does not contain the fix we need for shibboleth anyway I propose we add the necessary js directly to user_shibboleth as @DeepDiver1975 proposed. We need to test compatibility with 8.1.4 anyway.

part of this is valid for core and some is only for shibboleth.

As a result a proper solution is to be dsigned for 9.0 - trying to backport to 8.2

For the immediate need we need manually patch any 8.1.x instance

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/core/pull/16783#issuecomment-151498757 Spoke with @bboule. We will provide this as a patch to the specific customer and do the main fix for 9.0. Moving milestone forward.

**Comment by DeepDiver1975** [comment]
since the code base changed dramatically because of webdav reimplementation -> close

**Comment by DeepDiver1975** [comment]
@PVince81 reopened, rebased and revived as requested

**Comment by PVince81** [comment]
Wow, thanks

**Comment by MorrisJobke** [comment]
> @PVince81 reopened, rebased and revived as requested

Ready for review or does this still needs some work?

**Comment by PVince81** [comment]
I need to think about it. Do apps want to have their own handlers for these error codes or is it ok if we always handle it globally ? If not, then we need a mechanism for apps to be able to override/disable this for specific calls. (this was my main worry about this PR back then)

**Comment by DeepDiver1975** [comment]
> does this still needs some work?

needs work in terms of testing the hell out of it in various system setups

**Comment by DeepDiver1975** [comment]
````
10:41:06 PhantomJS 1.9.8 (Linux 0.0.0) ERROR
10:41:06   TypeError: Fake XHR onreadystatechange handler threw exception: 'undefined' is not an object (evaluating '$('#content').attr('class').substring')
10:41:06   at /ssd/jenkins/workspace/core-ci-linux-jsunit/database/sqlite/label/SLAVE/core/js/js.js:9
10:41:06 PhantomJS 1.9.8 (Linux 0.0.0): Executed 166 of 652 (skipped 2) ERROR (0.273 secs / -24162685 mins 33.562 secs)
10:41:07 Build step 'Conditional step (single)' marked build as failure
10:41:07 Setting commit status on GitHub for https://github.com/owncloud/core/commit/924a6575402b8ee7972cb05e1de079e22a17b3eb
10:41:28 Finished: FAILURE

**Comment by PVince81** [comment]
Most importantly is making sure that this doesn't cause regressions.

Redirects cannot be caught unfortunately as the JS code cannot know, that will need a different approach. But if the purpose of catching redirects is mostly for SSO, the question is whether the error code "0" would be enough for most/all SSO cases ?
If not then we need to think of an approach to detect redirects: adding a known header to ALL responses and if the header is missing it means we got redirected to another page.

**Comment by PVince81** [comment]
Just did some experimenting and it seems there is no official way for an app to tell the global error handler that the error was processed already.
So one idea is to have apps set "xhr.errorProcessed = true" and then that value can then be checked in the global handler. This is really just for apps that want to process 301, 307 and 401.

How does that sounds ?

Here is the list of challenges, as a reminder:
- [ ] make global handler overridable by apps (see `xhr.errorProcessed` idea)
- [ ] detect redirects with special header
- [ ] check for status 0 in shibboleth app
- [ ] make davclient.js (for files app webdav) trigger ajaxError on error
- [ ] what about apps using XmlHttpRequest directly instead of jquery ajax ?

**Comment by PVince81** [comment]
Added https://github.com/owncloud/core/commit/ae914a1de5d1560e4ad1956173a967abbc3a655b to make the files client also throw "ajaxError". A nice side effect of this is that we don't need to handle 401 any more inside the files app as it's done globally :smile:

**Comment by PVince81** [comment]
- [ ] TODO: reload the same page. Else the user would find themselves back to the root of the files app regardless of which page was open.

**Comment by PVince81** [comment]
I discovered that some ajax calls in the setupchecks.js page might expect a 401.
To make it easier, now you can pass `allowAuthErrors` to the ajax call object.

Now it reloads the current page, so if the session times out on the activity app, it will redirect to that. After login, voila, back to the activity app :smile:

**Comment by PVince81** [comment]
and of course as usual IE8 is behaving differently. What would be a web dev life without IE8's challenges ?

- [ ] BUG: Webdav XmlHttpRequest broken / does not trigger global ajax error in IE8

**Comment by PVince81** [comment]
Also ref https://github.com/owncloud/core/issues/16392

**Comment by PVince81** [comment]
Having big trouble with IE8... it doesn't support having two separate handlers for "onreadystatechange", the local one (for apps/davclient) and the global one for catching errors.

Next up: override the global `window.XmlHttpRequest` with a wrapper instance

**Comment by PVince81** [comment]
Note, this IE8 bullshit is not needed for OC < 8.2.2 so it could be deferred to purely 9.0.
But it would also affect any app that doesn't use jQuery for ajax requests...

**Comment by PVince81** [comment]
Now considering that many SSO solutions might redirect to IDP, not only shib, we should probably have the "http status code 0" handling in core too. The only drawback is that some app is doing a cross-domain call but forgot to set CORS, then the page will reload completely.

- [ ] TODO: add cross-domain http status 0 detection

**Comment by MorrisJobke** [comment]
Rebased on current master (and resolved a easy to fix merge conflict).

@PVince81 Is this now ready for testing? Remind: IE8 support is dropped :)

**Comment by DeepDiver1975** [comment]
needs yet another rebase

**Comment by MorrisJobke** [comment]
> needs yet another rebase

Done and was easy to fix :P

**Comment by PVince81** [comment]
I'll need to take some time to evaluate whether this fix is good enough for 9.0

**Comment by MorrisJobke** [comment]
It still shows weird behavior ... the redirect isn't triggered, but a authentication popup shows up.

**Comment by PVince81** [comment]
Rebased, squashed.

Hmmm... auth popup isn't supposed to occur, might depend on the call.
The call in question must have the "XMLHttpRequest" header set to make it work.
It should be the case if jQuery is used by default. If not, I can try adding that header globally for all jQuery calls.

@MorrisJobke do you have the matching ajax call from the network console ?

Now testing with the notifications app.

**Comment by PVince81** [comment]
Ok got it... OCS calls can also return 401 sometimes...
We need to add this https://github.com/owncloud/core/pull/20609 for OCS calls as well.

**Comment by PVince81** [comment]
- [ ] make OCS calls detect the "X-Requested-With" header and return a fake basic auth in case of 401 (CC @LukasReschke)

**Comment by PVince81** [comment]
- [ ] make appframework endpoints also use the same logic

@LukasReschke can you help with that ? See https://github.com/owncloud/core/pull/20609/files#diff-991151d360ecd314a632cf966b485429R169 or point me to the right places to implement this ?

**Comment by PVince81** [comment]
or base.php ? :see_no_evil:

**Comment by LukasReschke** [comment]
> @LukasReschke can you help with that ? See https://github.com/owncloud/core/pull/20609/files#diff-991151d360ecd314a632cf966b485429R169 or point me to the right places to implement this ?

Will do.

**Comment by PVince81** [comment]
Thanks @LukasReschke, assigning to you for now. Please reassign to me when you're done :smile:

**Comment by PVince81** [comment]
To test the OCS case:

1. Have the notifications app enabled
1. Go to the admin page (any page that doesn't poll the server)
1. Delete the PHP session
1. Wait 30 seconds (make sure not heartbeat appears in-between though)

Before: browser basic auth dialog appears
After @LukasReschke's fix of OCS: dialog doesn't appear, redirect to login

Not sure yet how to test the app framework ones, might need specific app actions.

**Comment by LukasReschke** [comment]
That should work now. Appframework does not need any adjustments from what I can tell and tested. :smile:

**Comment by PVince81** [comment]
Nice, thanks a lot @LukasReschke!

**Comment by PVince81** [comment]
- [x] TEST: OCS 401 (share dialog, notification)
- [x] TEST: app framework REST (click favorite icon after session timeout)

Works!

@MorrisJobke if you like could you retry your test case ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke if you like could you retry your test case ?

Really nice - works now in all my tested scenarios like:

* folder/file creation
* switching navigation sidebar entries (right)
* open sidebar
* trigger actions

:+1: 

Another topic is the upload handling. There it is already covered but only prompts a "Authentication error" and doesn't redirects. I'm open to do this in a new PR, because it's another code path or to directly put this in here. It's your decision.

**Comment by LukasReschke** [comment]
> Another topic is the upload handling. There it is already covered but only prompts a "Authentication error" and doesn't redirects. I'm open to do this in a new PR, because it's another code path or to directly put this in here. It's your decision.

@MorrisJobke @PVince81 That should be done with https://github.com/owncloud/core/commit/b99c6f1f67a207984b8b5355703cabd89d1e7c73 as well now. That's `OC_JSON::checkLoggedIn()` which is used for authentication checks in older code and now we're also sending a 401 there.

**Comment by PVince81** [comment]
@LukasReschke does that 401 also sends the DummyBasicAuth ?

**Comment by LukasReschke** [comment]
> @LukasReschke does that 401 also sends the DummyBasicAuth ?

No. Because it won't reply with any auth request at all. It will simply return a 401 with a JSON blob stating that the auth failed.

**Comment by PVince81** [comment]
Ok, so let's test again with IE9 and IE10 to make sure it still works, then merge this.

This :+1: is for @LukasReschke's code. Will need another thumbs up for the JS code.

**Comment by PVince81** [comment]
- [x] TEST: Chrome
- [x] TEST: Firefox
- [x] TEST: IE9
- [x] TEST: IE10

Needs a second reviewer for the JS changes @LukasReschke @nickvergessen @rullzer

**Comment by PVince81** [comment]
Note, redirecting would cause whatever input the user had to be lost. This is fine short term, raised https://github.com/owncloud/core/issues/22458 to discuss having a popup login dialog instead.

**Comment by LukasReschke** [comment]
:+1: for the JS changes. Short-term this seems like the way to go. Better than before :smile:

**Pull request merged**
