### PR TITLE
Move file actions to dropdown

### PR DESCRIPTION
**Pull request by PVince81**
@jancborchardt don't try the dropdown, it doesn't exist yet :wink: 
- [x] file action types
- [x] implement dropdown
- [x] unit tests

### CODE REVIEW

**Comment by PVince81** [comment]
For https://github.com/owncloud/core/issues/12081

**Comment by PVince81** [comment]
CC @blizzz FYI

**Comment by jancborchardt** [comment]
Great! Let me know as soon as it’s testable. :)

**Comment by PVince81** [comment]
This is how it looks like at the moment:
fileactionsdropdown-first

Not very beautiful.
@jancborchardt do we have existing styles we want to reuse like highlights ?

- [ ] BUG: menu must scroll with list, just like the share dropdown
- [ ] BUG: don't show menu if no actions / show message in menu "no actions" ?

**Comment by PVince81** [comment]
- [ ] BUG: delete and rename actions must also appear in menu!

**Comment by PVince81** [comment]
- [ ] support for actions order, we certainly want to have "Delete" as the last action

**Comment by PVince81** [comment]
Ok, fixed some bugs and did a bit of naive styling:
fileactionsdropdown-second

**Comment by PVince81** [comment]
- [ ] TODO: remove deletion spinner logic

**Comment by PVince81** [comment]
- [ ] TEST: trashbin and other file list views

**Comment by PVince81** [comment]
- [ ] obsoletes download spinner
- [ ] provide a spinner for the whole row instead ? would be triggered by actions in progress like download, rename, etc @jancborchardt what do you think ?

**Comment by PVince81** [comment]
Here, looks a bit more ownCloud-y :smile: 
fileactionsdropdown-third

**Comment by PVince81** [comment]
@jancborchardt it is testable.
Some things to check:
- check out the "Download" action in the menu, I think it's ok to keep it
- check the public link page: I'd remove the menu there and have a single inline "Download" action (also no right sidebar yet in 8.2)
- call `FileList.setFileBusyState("filename.txt", true)` on the CLI to simulate busy state, in case you want to restyle it. It's currently used by rename, delete and download
- actions order ?
- don't show menu if no actions ? what if there is only one, show that inline ?
- go to "shared with you" and see how the share link jumps on hover
- mobile ? (long press or always show the three dots icon ?)

**Comment by PVince81** [comment]
- [ ] TODO: bring back "unshare from self" label, it used to be a hack, needs a different approach

**Comment by PVince81** [comment]
I rechecked the mock ups and saw that the menu trigger must be permanent, so fixed that. This also fixes the jumpiness in some situations.

**Comment by PVince81** [comment]
fileactionsdropdown-four

**Comment by MorrisJobke** [comment]
I guess it would be better to reuse the stuff, that is already in the news app (design wise):

bildschirmfoto von 2015-08-05 12-02-27

I think that leaving this a list of icons & text (and not a grid of icons) is fine, but I would really like to have it a special "bubble" and not an all in one color thingy. @jancborchardt also said this would be better.

**Comment by PVince81** [comment]
I prefer the dropdown menu, especially if there will be more than two actions. Having only icons alone will become confusing. And thanks to the dropdown we have more room.
Also on mobile such small icons will be more difficult to tap and also don't have a tooltip to tell what they are.

**Comment by PVince81** [comment]
also note that some actions don't have an icon like for example "Edit" for ODT documents (from the documents app).

**Comment by PVince81** [comment]
Unit tests have been added/adjusted. :smile:

**Comment by PVince81** [comment]
@owncloud-bot gimme some green https://github.com/owncloud/core/pull/18073 !

**Comment by PVince81** [comment]
This is already in a mergable state, the open stuff can be addressed separately if needed.

Please let me know about the decision regarding the menu's design.

Please review @jancborchardt @MorrisJobke @DeepDiver1975 @blizzz

**Comment by blizzz** [comment]
works and code looks good :+1:

**Comment by jancborchardt** [comment]
@PVince81 so @MorrisJobke’s point is not about the icons nor about the text. It’s about the style of the dropdown.

Instead of being this slab (like the share dropdown is now) it should be this bubble with a pointer which is already defined in styles in the apps.css as you can see from the News app. :)
The rest (the vertical list of icons + text) is fine for now. :)

**Comment by karlitschek** [comment]
Agreed. the bubble with the pointer looks much nicer :-)

**Comment by PVince81** [comment]
- [ ] change border+background style of the dropdown to match the bubble style from https://github.com/owncloud/core/pull/17709#issuecomment-127944410

**Comment by MorrisJobke** [comment]
> change border+background style of the dropdown to match the bubble style from #17709 (comment)

This is already available as style in apps.css. Just use the correct css classes ;) See https://doc.owncloud.org/server/8.2/developer_manual/app/css.html#menus

**Comment by PVince81** [comment]
I'm not so optimistic that it will work directly, but let's find out.

**Comment by jancborchardt** [comment]
If it doesn’t directly work, then we need to adjust the styles so it works for both. :) DRY, homie

**Comment by PVince81** [comment]
fileactions-bubble

See global `bubble` class: https://github.com/owncloud/core/commit/fc523adc06f2fb098fe75051fad4daa54bc2e3b2#diff-d28ce211f72cb6409a66e6c8ab52d723R322

**Comment by PVince81** [comment]
Hop, another Jenkins branch: https://github.com/owncloud/core/pull/18094

**Comment by PVince81** [comment]
Can we merge this now ?

**Comment by Bullnados** [comment]
One question. why is the right border of the rectangle not dark?

**Comment by PVince81** [comment]
Which rectangle ?

Posting both screenshots again:
bildschirmfoto von 2015-08-05 12-02-27

fileactions-bubble

**Comment by jancborchardt** [comment]
@pvince81 I just need to fix the position of the triangle and the clickable area of the actions. Otherwise it’s fine. :)

**Comment by karlitschek** [comment]
yes. very nice !!! :-)

**Comment by jancborchardt** [comment]
Some more things need to be fixed, making a list here:
* [ ] fix position of the triangle, should be centered below the dot-dot-dot menu
* [ ] increase clickable area of the actions
* [ ] fix text labels of the actions disappearing on mobile
* [ ] fix ellipsizing of filenames not working anymore

Will do that later today.
Also give the functionality a good test please! @owncloud/designers

**Comment by Bullnados** [comment]
I mean the pointer rectangle. The whole dropdown has a dark border/line around. But the right edge of the pointer doesnt have that dark border/line.

**Comment by PVince81** [comment]
I just copied the style from the apps.css as it was before.
@jancborchardt can you add the right border of the arrow, unless it was intended to be like it is now ?

**Comment by PVince81** [comment]
@jancborchardt I also wonder whether the sidebar should also open when clicking on the other columns like mtime and size ?

**Comment by jancborchardt** [comment]
Improved the design and fixed some issues I mentioned above. Stuff left:

* [ ] fix ellipsizing of filenames not working anymore (I’ll work on this)
* [ ] make bubble menu behave like the sharing dropdown, hiding it when another is opened. Or will that be obsolete with the sidebar anyway @PVince81?

**Comment by jancborchardt** [comment]
Everything style-wise is fixed from my POV. Please review @owncloud/designers @Raydiation :)

@Bullnados the pointer rectangle is something for a different pull request – please open a separate issue.

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Jenkins PR #18140

**Comment by MorrisJobke** [comment]
Jenkins is now happy :)

**Comment by MorrisJobke** [comment]
I just talked with @jancborchardt:

* [ ] Always show the share icon but without showing the text label if nothing is shared. Should then look like this:

bildschirmfoto von 2015-08-08 10-42-09

**Comment by jancborchardt** [comment]
(I’ll work on fixing that. :)

**Comment by PVince81** [comment]
Seems the sidebar merge is causing conflict.
Rebasing...

**Comment by PVince81** [comment]
Rebased

@jancborchardt I removed the display name already:
fileactions-sharenodisplayname

Please review.

**Comment by PVince81** [comment]
Ooops, I seem to have discarded Jan's commits. I'll try to recover them now.

**Comment by PVince81** [comment]
Here we go, @jancborchardt's commits are back from the nether. Phew.

**Comment by MorrisJobke** [comment]
@PVince81 One last thing: Can you make it permanent to not require the hover anymore? ;)

**Comment by PVince81** [comment]
Ah, make the share action permanent ? Let's add the "permanent" class then.

**Comment by PVince81** [comment]
Ok let's do it differently: from now on ALL inline actions will be permanently visible (favorite icon, share icon and trigger menu)

**Comment by PVince81** [comment]
Hmm, can't destroy the "permanent" class completely. There are global styles that seem to imply that ".action" are used also outside of the files app. If I remove the "permanent" class there it will risk breaking apps.

So, going back to the simpler solution: setting "permanent" explicitly on inline actions.

**Comment by PVince81** [comment]
Here we go: https://github.com/owncloud/core/commit/86e1eaf370ff5c290805bac130f3c3bbd1d1c774

Note that this needed more changes: there is code that updates the icon after changing the sharing state. That code needed to properly keep the permanent state and also remove the label.

**Comment by PVince81** [comment]
@owncloud-bot boo

**Comment by PVince81** [comment]
@owncloud-bot go catch the candy https://github.com/owncloud/core/pull/18174

**Comment by MorrisJobke** [comment]
Really nice :+1: works

**Comment by MorrisJobke** [comment]
@jancborchardt @rullzer @Xenopathic Please have a look and review it :)

**Comment by jancborchardt** [comment]
@PVince81 only one issue: When clicking the dot-dot-dot menu again, the bubble should close again.

**Comment by PVince81** [comment]
Ok, since have to touch this again I'll take the opportunity to backbonize the menu (make it a backbone view).

**Comment by PVince81** [comment]
Done. FileActionsMenu is now a Backbone View.
Clicking on the trigger again will close the menu.
Moved the logic to remove the highlight into FileActions.

Please review again.

**Comment by PVince81** [comment]
Another jenkins PR: https://github.com/owncloud/core/pull/18195

**Comment by PVince81** [comment]
Tests passed. Please review.

**Comment by MorrisJobke** [comment]
One last thing:

* [ ] on mobile layout the permanent share menu should be more transparent if there is no share for this item. Otherwise it looks like a shared element ;)

Beside that: Awesome work :) I like it very much :)

**Comment by PVince81** [comment]
No. Let's merge this first. I'm tired of having to re-fix and re-PR-Jenkins every time.

**Comment by PVince81** [comment]
or you do it yourself...

**Comment by PVince81** [comment]
in general mobile styling has to be re-reviewed anyway in regards to the sidebar and dropdown, so there will surely be more to fix.

**Comment by jancborchardt** [comment]
Let’s do this! :)

**Comment by jancborchardt** [comment]
Really awesome work again, and great collab @PVince81 :)

**Pull request merged**
