### PR TITLE
Reload versions list after revert

### LINKED ISSUE #19498: Sidebar doesn't update correctly on version restore
Move this to a separate issue:  https://github.com/owncloud/core/issues/19403#issuecomment-144668831

Steps to reproduce:

1. create a file with multiple versions
2. open the sidebar and go to versions
3. restore a version

Expected Result:

The version you restored should disappear from the sidebar instead the new version, created during restore, should show up

Actual Result:

The new version gets added but the restored version doesn't get removed

cc @PVince81

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/19498

@schiesbn @davitol  @MorrisJobke

### CODE REVIEW

**Comment by schiesbn** [comment]
Doesn't work here. Not I only see the new version after restore all the other existing versions are gone and only come back if I navigate away to sharing and come back to the versions drop down.

Also on master we add the new version without re-loading the whole list. Couldn't we do the same with the version we want to remove? Having this spinner looks a bit annoying. On the other hand it prevents people from trying to restore multiple versions at once.

**Comment by PVince81** [comment]
Fixed. But I left the spinner, it prevents people to click "Revert" twice.

A more luxurious version with a more dynamic and responsive list could be implemented later in 9.0.

@schiesbn please retest

**Comment by MorrisJobke** [comment]
> Fixed. But I left the spinner, it prevents people to click "Revert" twice.

How? There is no new code. Do you forget to push?

**Comment by PVince81** [comment]
It's magic :tophat:  !

Yeah, forgot to push, sorry...

**Comment by PVince81** [comment]
Please re-review @schiesbn @MorrisJobke

**Comment by schiesbn** [comment]
Works great now :+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
