### PR TITLE
[stable9] Don't decrypt shared files

### PR DESCRIPTION
**Pull request by PVince81**
Backport of #25639 to stable9

Please review and test @DeepDiver1975 @VicDeo @owncloud/encryption

### CODE REVIEW

**Comment by PVince81** [comment]
Retested, still works

**Comment by PVince81** [comment]
I skimmed through the log and it seems all passed except OCI that timed out.

**Comment by PVince81** [comment]
Review please @DeepDiver1975 @VicDeo @butonic @jvillafanez  (backport)

**Comment by jvillafanez** [comment]
👍

**Pull request merged**
