### PR TITLE
Move files_external to PSR-4

### PR DESCRIPTION
**Pull request by nickvergessen**
The lib/Lib/ folder is a bit unfortunate, but that is where the namespace belongs to.
Could be cleaned up in another PR, but I'm not sure what of that is considered "public API" so I didn't touch it.

@rullzer @Xenopathic @MorrisJobke

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by Xenopathic** [comment]
:+1:

Why does the namespace belong to lib/ rather than the app root folder?

**Comment by MorrisJobke** [comment]
> Why does the namespace belong to lib/ rather than the app root folder?

Because this makes separation between app code and app statics more visible. Also it would avoid having 3rdparty or vendor accessible via two different name spaces.

**Comment by PVince81** [comment]
would be good to get this one passing at least: server-master-linux-externals-smb-windows-ext-ci/database=sqlite

Can you rebase/push ? Seems the log got discarded already :frowning:

**Comment by nickvergessen** [comment]
Rebased and pushed

**Comment by DeepDiver1975** [comment]
rebased to resolve conflicts

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2016-05-17 11-59-30

**Comment by PVince81** [comment]
and of course no one tested... admin page broken now

**Comment by PVince81** [comment]
```
{"reqId":"9piTp2t1APDNxJ\/2pjsH","remoteAddr":"127.0.0.1","app":"PHP","message":"require_once(): Failed opening required '\/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/Lib\/Storage\/..\/..\/3rdparty\/Dropbox\/autoload.php' (include_path='\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/console_getopt:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/pear_exception:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/archive_tar:\/srv\/www\/htdocs\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/srv\/www\/htdocs\/owncloud\/lib\/private:\/srv\/www\/htdocs\/owncloud\/config:\/srv\/www\/htdocs\/owncloud\/3rdparty:\/srv\/www\/htdocs\/owncloud\/apps:\/srv\/www\/htdocs\/owncloud\/apps2:\/srv\/www\/htdocs\/owncloud\/apps3:.:\/usr\/share\/php5:\/usr\/share\/php5\/PEAR:\/srv\/www\/htdocs\/owncloud:\/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php') at \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/Lib\/Storage\/Dropbox.php#36","level":3,"time":"2016-05-24T10:05:26+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin","user":"admin"}
```

Will try and fix separately

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/24805 need help for fixing...

**Comment by nickvergessen** [comment]
Fixed in #24806

**Pull request merged**
