### PR TITLE
tests: Fix typos (found by codespell)

### PR DESCRIPTION
**Pull request by stweil**
Fix also a small grammar issue.

Signed-off-by: Stefan Weil sw@weilnetz.de

### CODE REVIEW

**Comment by stweil** [comment]
@owncloud-bot: My contribution is MIT licensed.

**Comment by nickvergessen** [comment]
:+1:

**Comment by skjnldsv** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Comment by LukasReschke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
needs rebase - has conflicts

**Comment by stweil** [comment]
@DeepDiver1975, upstream removed one of the modified files. I rebased the PR now.

**Comment by DeepDiver1975** [comment]
> upstream removed one

yes - it was me :wink:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
