### PR TITLE
Ignore empty plurals just like with singulars

### PR DESCRIPTION
**Pull request by nickvergessen**
The js and php code of n() has fallbacks for when the key is missing.
However there is no fallback, when the key is defined with an array of empty
strings. So we just don't extract them anymore and use the english language.

See https://github.com/owncloud/administration/pull/31

### CODE REVIEW

**Comment by nickvergessen** [comment]
@DeepDiver1975 @MorrisJobke

**Comment by MorrisJobke** [comment]
:+1:

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
@DeepDiver1975

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
