### PR TITLE
[Tests-Only] Php 7.4 fix phpunit

### PR DESCRIPTION
**Pull request by VicDeo**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
@VicDeo I merged PR #37281 and there were some other unrelated dependency updates overnight that are merged PR #37283 
Also PR #37279 is waiting for review and merge - you might like to review that first and merge if it looks OK.

Then you can rebase this PR and get a new run of phpunit with less errors reported.

**Comment by phil-davis** [comment]
@VicDeo I cherry-picked the last commit into #37300 so that ordinary CI can run for that and it can get merged this morning.

Congratulations on getting CI passing! Now we can think about a real PR that adjusts CI permanently for master PHP 7.4 support.

**Comment by phil-davis** [comment]
See PR #37302 for a PR to enable PHP 7.4 in core. IMO CI should pass there.

**Comment by VicDeo** [comment]
All known issues have been fixed. it's time to close

**Pull request closed without merging**
