### PR TITLE
Deduplicate external manager tests

### PR DESCRIPTION
**Pull request by nickvergessen**
Based on #15158 

@MorrisJobke @icewind1991

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by icewind1991** [comment]
Can you split the unit test into smaller functions, each testing one case

**Comment by nickvergessen** [comment]
Well I tried, but they depend on each other and I failed to get it working with the `@depends` annotation

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
