### PR TITLE
Add security hardenings to $.ajax()

### LINKED ISSUE #16926: requesttoken.js verify that request goes to ownCloud domain

### PR DESCRIPTION
**Pull request by LukasReschke**
Adds two security hardening to `$.ajax`:
1. Do not add sensitive request headers for cross domain requests
   - Prevents leaking the CSRF token to another third-party domain by mistake. (fixes https://github.com/owncloud/core/issues/16926)
2. Disable automatic evaluation of responses
   - If a response to a $.ajax() request returns a content type of "application/javascript"
     JQuery would previously execute the response body. This is a pretty unexpected
     behaviour and can result in a bypass of our Content-Security-Policy as well as
     multiple unexpected XSS vectors.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@MorrisJobke @nickvergessen Mind testing? :)

**Comment by icewind1991** [comment]
> Disable automatic evaluation of responses

Does this effect `$.getScript` ?

**Comment by LukasReschke** [comment]
> Does this effect $.getScript ?

No. `$.getScript` is overriding the default behaviour. `$.getScript` will still behave as before.

Tested with:

```javascript
$.get('http://localhost/test.php');
```

```javascript
$.getScript('http://localhost/test.php');
```

```php
<?php
header('Content-Type: application/javascript');
?>
alert(1);
```

**Comment by icewind1991** [comment]
:+1:

**Comment by rullzer** [comment]
Looks good! And your testcase works as expected. :+1:

**Comment by VicDeo** [comment]
:+1: Tested

**Pull request merged**
