### PR TITLE
Bugfix/fix apps list test  test command input for update testing

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
In an update scenario the version of the files app is not exactly determinable.
As of now it can either be 1.5.3 or1.5.2

We just assert for 1.5.

## Related Issue
https://drone.owncloud.com/owncloud/update-testing/208/193

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
backport and remove the return types ?

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/33896

**Comment by phil-davis** [comment]
The part that specifies the return types is PHP 7.1+
That can be backported after we drop PHP7.0

**Pull request merged**
