### PR TITLE
Remove .idea folder - already ignored in .gitignore

### PR DESCRIPTION
**Pull request by lucasmichot**
The `.idea` has no reason to be in the repository.

If the initial reason was code formatting, it can be set for all IDE via `.editorconfig` and PR can be checked with https://styleci.io and https://nitpick-ci.com

### CODE REVIEW

**Comment by nickvergessen** [comment]
Ref https://github.com/owncloud/core/issues/13324

**Comment by DeepDiver1975** [comment]
closing this for now - no need to restart the discussion as per #13324

**Comment by dimsav** [comment]
ha! @lucasmichot I was about to open a PR for this!

**Comment by lucasmichot** [comment]
ah my dear @dimsav !!! :-) We lynx eyes
Let's skype Sunday ?! ~~ my last planned bitter soup was on Tuesday BTW :-)

**Pull request closed without merging**
