### PR TITLE
Close the user menu when clicking it again

### LINKED ISSUE #20178: Clicking on name/picture in top right after opening menu doesn’t close it again
1. Click on the name/picture in the top right to open the user menu
2. Attempt to close it by clicking on the same area again

Doesn’t work but shouldn’t, and did before. @PVince81 @MorrisJobke to the rescue. ;)

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #20178

@PVince81 @MorrisJobke @jancborchardt

### CODE REVIEW

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@karlitschek I added the backport request because the initial issue was scheduled for 8.2.1

**Comment by jancborchardt** [comment]
Nice, thanks!

And yeah, I would say this should be backported since it’s a regession and a glitch in a very present functionality.

**Comment by nickvergessen** [comment]
@karlitschek can you approve the backport please?

**Comment by karlitschek** [comment]
yes. please backport :+1:

**Pull request merged**
