### PR TITLE
In case the email delivery fails the wrong status was returned.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Fixing a logic issue in the code. Detected in the IDE ...

## Related Issue
- none 

## How Has This Been Tested?
- unit tests added

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by phil-davis** [comment]
Backport ``stable10`` #32489

**Pull request merged**
