### PR TITLE
[stable7] Fix bugs in ownCloud external storage

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Backport of #14475

cc @karlitschek @PVince81 @DeepDiver1975 @LukasReschke @icewind1991

### CODE REVIEW

**Comment by karlitschek** [comment]
backport is fine :+1:

**Comment by Xenopathic** [comment]
@icewind1991 Review this backport? Thanks

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
