### PR TITLE
[Stable9] Use a CappedCache in the user database backend

### PR DESCRIPTION
**Pull request by rullzer**
Backport of https://github.com/owncloud/core/pull/24405
Approved in: https://github.com/owncloud/core/pull/24405#issuecomment-216497180

CC: @MorrisJobke @nickvergessen @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by nickvergessen** [comment]
stuff seems to still work :+1:

**Comment by MorrisJobke** [comment]
👍

**Comment by PVince81** [comment]
@rullzer mind running the OCS integration tests locally just in case ? Then merge it

**Comment by DeepDiver1975** [comment]
@pvince81 looks good to me .... Lets merge

**Pull request merged**
