### PR TITLE
Fix overlapping selectively in default fileslist

### LINKED ISSUE #28850: Broken trashbin layout
### Steps:
1. Check out stable10
1. Delete some files
1. Go to "Deleted files"
spectacle t28947

### PR DESCRIPTION
**Pull request by lordelix**
## Description

Scope changes previously done in https://github.com/owncloud/core/pull/28678 to the default files-list view only.
Aka: `#app-content-files`

## Related Issue
Fixes https://github.com/owncloud/core/issues/28850
Fixes https://github.com/owncloud/enterprise/issues/2068

## How Has This Been Tested?
Visual test in FF, Chrome & IE11

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by felixheidecke** [comment]
**PLS hold review!**

**Comment by haukman** [comment]
I can verify that it looks ok for the files app and is not doing anything in the "shared with me" section.

**Comment by felixheidecke** [comment]
@haukman and @PVince81 … This works now ;-)

**Comment by haukman** [comment]
stupid presales question: Will this be part of 10.0.3 or 10.0.4?

**Comment by PVince81** [comment]
>  This works now ;-)

@felixheidecke retested in all browsers ?

**Comment by felixheidecke** [comment]
Looks good from here ;-)
bildschirmfoto 2017-09-04 um 16 41 34

**Comment by PVince81** [comment]
@felixheidecke please backport to table10.

@haukman aiming for 10.0.3

**Comment by phil-davis** [comment]
Backport stable10 #28906 
@felixheidecke I did this backport for you, to save European office time.
Note that some of the diffs here in master were already in stable10 correctly. So the diff of the backport has less lines. The cherry-pick did its thing correctly and automatically.

**Pull request merged**
