### PR TITLE
treat LDAP users not available by user filter as deleted

### LINKED ISSUE #15656: treat LDAP users not available by user filter as deleted
### Steps to reproduce
In our LDAP (AD) configuration, we have these filters : 
a. User Filter : (memberOf=CN=ownCloud,OU=domain_users,DC=mydomain,DC=com)
b. Login Filter : (&(memberOf=CN=ownCloud,OU=domain_users,DC=mydomain,DC=com)(sAMAccountName=%uid))
c. No Group Filter.

1. Add a user to the Active Directory group "ownCloud".
2. Optional : Log in ownCloud with this user and then log out.
3. Remove the user from the group. (note that the user is not deleted from LDAP)
4. run this in shell : sudo -u www-data php occ ldap:show-remnants

### Expected behaviour
The removed user should apear in the show-remnants list and the CleanUp job should remove the user from the DB and delete his data folder.

### Actual behaviour
The user doesn't apear in the show-remnants list. his information are still in the DB and his folder is never deleted. 

If I run this query in mysql : **select * from oc_preferences where userid='USERNAME'**, the user is not mark as deleted (isDeleted=1)

### Server configuration
**Operating system**: Debian 7.8

**Web server:** Apache 2.2

**Database:** Mysql 5.5

**PHP version:** 5.4

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
 - activity
 - calendar
 - files
 - files_locking
 - files_mv
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - gallery
 - user_ldap

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'na',
  'passwordsalt' => 'na',
  'secret' => 'na',
  'trusted_domains' =>
  array (
    0 => 'mydomain.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://mydomain.com/',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'database',
  'dbhost' => 'host',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => '',
  'installed' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'mydomain.com',
  'loglevel' => 0,
  'ldapUserCleanupInterval' => 1,
  'skeletondirectory' => '',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => 'myTheme',
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** Yes LDAP (ActiveDirectory)

#### LDAP configuration (delete this part if not used)

```
| user_ldap | cleanUpJobOffset                  | 0                                                                                                       |
| user_ldap | enabled                           | yes                                                                                                     |
| user_ldap | has_memberof_filter_support       | 0                                                                                                       |
| user_ldap | home_folder_naming_rule           |                                                                                                         |
| user_ldap | installed_version                 | 0.5.0                                                                                                   |
| user_ldap | last_jpegPhoto_lookup             | 0                                                                                                       |
| user_ldap | ldap_agent_password               | 
                                                                                     |
| user_ldap | ldap_attributes_for_group_search  |                                                                                                         |
| user_ldap | ldap_attributes_for_user_search   | displayName
mail                                                                                        |
| user_ldap | ldap_backup_host                  |                                                                                                         |
| user_ldap | ldap_backup_port                  |                                                                                                         |
| user_ldap | ldap_base                         | OU=USERS,DC=mydomain,DC=com                                                                      |
| user_ldap | ldap_base_groups                  | OU=USERS,DC=mydomain,DC=com                                                                       |
| user_ldap | ldap_base_users                   | OU=USERS,DC=mydomain,DC=com                                                                       |
| user_ldap | ldap_cache_ttl                    | 600                                                                                                     |
| user_ldap | ldap_configuration_active         | 1                                                                                                       |
| user_ldap | ldap_display_name                 | displayname                                                                                             |
| user_ldap | ldap_dn                           | user_name                                                                                       |
| user_ldap | ldap_email_attr                   | mail                                                                                                    |
| user_ldap | ldap_experienced_admin            | 1                                                                                                       |
| user_ldap | ldap_expert_username_attr         |                                                                                                         |
| user_ldap | ldap_expert_uuid_group_attr       | cn                                                                                                      |
| user_ldap | ldap_expert_uuid_user_attr        | sAMAccountName                                                                                          |
| user_ldap | ldap_group_display_name           | cn                                                                                                      |
| user_ldap | ldap_group_filter                 |                                                                                                         |
| user_ldap | ldap_group_filter_mode            | 1                                                                                                       |
| user_ldap | ldap_group_member_assoc_attribute | member                                                                                                  |
| user_ldap | ldap_groupfilter_groups           |                                                                                                         |
| user_ldap | ldap_groupfilter_objectclass      |                                                                                                         |
| user_ldap | ldap_host                         | ldap.mydomain.com                                                                                          |
| user_ldap | ldap_login_filter                 | (&(memberOf=CN=ownCloud,OU=domain_users,DC=mydomain,DC=com)(sAMAccountName=%uid)) |
| user_ldap | ldap_login_filter_mode            | 1                                                                                                       |
| user_ldap | ldap_loginfilter_attributes       |                                                                                                         |
| user_ldap | ldap_loginfilter_email            | 0                                                                                                       |
| user_ldap | ldap_loginfilter_username         | 1                                                                                                       |
| user_ldap | ldap_nested_groups                | 1                                                                                                       |
| user_ldap | ldap_nocase                       | 1                                                                                                       |
| user_ldap | ldap_override_main_server         | 0                                                                                                       |
| user_ldap | ldap_paging_size                  | 500                                                                                                     |
| user_ldap | ldap_port                         | 389                                                                                                     |
| user_ldap | ldap_quota_attr                   |                                                                                                         |
| user_ldap | ldap_quota_def                    |                                                                                                         |
| user_ldap | ldap_tls                          | 0                                                                                                       |
| user_ldap | ldap_turn_off_cert_check          | 0                                                                                                       |
| user_ldap | ldap_user_filter_mode             | 1                                                                                                       |
| user_ldap | ldap_userfilter_groups            |                                                                                                         |
| user_ldap | ldap_userfilter_objectclass       |                                                                                                         |
| user_ldap | ldap_userlist_filter              | (memberOf=CN=ownCloud,OU=domain_users,DC=mydomain,DC=com)                         |
| user_ldap | types                             | authentication        
```

### Client configuration
**Browser:** FireFox, Chrome

**Operating system:** Windows 7

### PR DESCRIPTION
**Pull request by ryno83**
Pull Request from master branch intead of stable8 

Fixes #15656

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot This is okay to test

**Comment by LukasReschke** [comment]
> Contributions to the core repo require a signed contributors agreement http://owncloud.org/contribute/agreement/ Alternatively you can add a comment here stating that this contribution is MIT licensed.

@ryno83 Your action is required on this :-)

**Comment by LukasReschke** [comment]
cc @blizzz

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by blizzz** [comment]
Imho should this should be done as well:

* [ ]  You could have "shadow" users that are allowed to login and use ownCloud, but do not show up in lists or the sharing box. This should be tested as well.
* [ ] Unit tests for this scenario against readAttribute(). Yes, it is not convered at all, yet, but this should be improved continuously.
* [ ] Unit tests for this scenarios against userExsists() or userExistsOnLDAP() (so far the latter is covered indirectly via userExists() tests).

**Comment by blizzz** [comment]
fyi @MTRichards

**Comment by MTRichards** [comment]
Any more detail on this would be awesome, not entirely sure the conditions that lead to this?

**Comment by ryno83** [comment]
@LukasReschke  Sorry but I'm really new here... should I do something ?

**Comment by MorrisJobke** [comment]
@blizzz @MTRichards Isn't the ticket #15656 enough? What needs to be done here?

**Comment by MTRichards** [comment]
Let me make sure I understand the depth of the change.

If I change the user filter and it removes someone (who is still in ldap but is no longer allowed based on the updated filter), I want them to be deleted - right?

This resolves this problem by having them appear as deletable by the LDAP cleanup algorithm?

**Comment by blizzz** [comment]
> If I change the user filter and it removes someone (who is still in ldap but is no longer allowed based on the updated filter), I want them to be deleted - right?

Yes, that's the idea behind.

> This resolves this problem by having them appear as deletable by the LDAP cleanup algorithm?

Exactly.

**Comment by MTRichards** [comment]
GREAT!

**Comment by MTRichards** [comment]
@cmonteroluque @rperezb This is a good test case for our LDAP testing for 8.2. Not sure where do document this so it doesn't get lost.

**Comment by rperezb** [comment]
added to the LDAP test plan, thx

**Comment by blizzz** [comment]
@ryno83 did you delete your branch? ldap-fix

``` 
it pull https://github.com/ryno83/core.git ldap-fix
fatal: Couldn't find remote ref ldap-fix
```

**Comment by MorrisJobke** [comment]
@blizzz Looks so:

bildschirmfoto von 2015-08-07 17-15-42

Try to apply the patch: https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/15847.patch

**Comment by ryno83** [comment]
Sorry but I think so :( I don't remeber exactly why I've done that but I'm new to Github (was on svn) and I have a lot of thing to learn... @blizzz @MorrisJobke Should I make a pull request again ?

**Comment by MorrisJobke** [comment]
@ryno83 That would make our lives a lot easier :)

**Comment by ryno83** [comment]
This is the new pull request #18212.

**Pull request closed without merging**
