### PR TITLE
Add hint about additional PHP database modules

### LINKED ISSUE #16391: Better UX: Provide info why "Only SQLite is available.." in installer
With the current installer of OC 8.0.3 the user gets this screen shown if only php5-sqlite on debian/ubuntu is installed:

screenshot - 18 05 2015 - 09 57 14

This currently contains no informations why only SQLite is available. A user needs to install php5-pgsql or php5-mysql/php5-mysqlnd to get other database options shown within the installer.

This has lead to some confusion and forums postings in the past how to get other options shown.

The modules to install are listened at https://doc.owncloud.org/server/8.0/admin_manual/installation/source_installation.html but the experience has shown that users are not reading this informations or just can't find it.

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #16391 

cc @owncloud/designers @realrancor

### CODE REVIEW

**Comment by MorrisJobke** [comment]
THis is how it looks now:

bildschirmfoto von 2015-05-18 22-57-38

**Comment by oparoz** [comment]
:+1: based on the mock up

**Comment by karlitschek** [comment]
good idea :+1:

**Comment by jancborchardt** [comment]
Good stuff @MorrisJobke!

**Comment by RealRancor** [comment]
Better later than never but also :+1: Will save us a lot of duplicate questions about this at the forums.

**Comment by LukasReschke** [comment]
This breaks installation on hosts that allowed have SQLite installed: https://github.com/owncloud/core/issues/16648

**Pull request merged**
