### PR TITLE
[stable9] decrease initial users to load to 50

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/24999 to stable9

Please review @georgehrke @DeepDiver1975 @nickvergessen @rullzer @butonic

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/24734

**Comment by MorrisJobke** [comment]
Makes sense and works :+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by georgehrke** [comment]
needs a rebase

**Pull request merged**
