### PR TITLE
Ajax load groups in sidebar of users page

### PR DESCRIPTION
**Pull request by PVince81**
The sidebar contents is now loaded with ajax.

@nickvergessen that's the separated part

TODOs:
- [x] user count must be grey instead of black
- [x] "admin" group should say "Admins" (special case)

### CODE REVIEW

**Comment by PVince81** [comment]
@blizzz is paginated loading with the group list even possible (LDAP) ?

**Comment by blizzz** [comment]
> is paginated loading of the group list even possible (LDAP) ?

Yes, of course. It only must be done the same way for the list on the left sidebare as well as for the group pickers. In the other PR i have seen you are aware of this, so all fine.

**Comment by PVince81** [comment]
For the group pickers it will likely be a search field, so no real pagination / lazy loading of the next page. Well, unless the API supports it.

I'll have to dig into the API

**Comment by nickvergessen** [comment]
I guess you need to tunnel the limit through until this method:
https://github.com/owncloud/core/blob/master/lib/private/group/metadata.php#L188-188

**Comment by PVince81** [comment]
- [ ] do not reload the sidebar contents when assigning/unassigning groups

**Comment by MorrisJobke** [comment]
> do not reload the sidebar contents when assigning/unassigning groups

Is this the only missing thing?

**Comment by MorrisJobke** [comment]
Rebased.

**Comment by PVince81** [comment]
> Is this the only missing thing?

Possibly, but IIRC there are other glitches and inconsistencies.

**Comment by PVince81** [comment]
Looks like Backbone collections with events would be of a great use here, considering that there are multiple views displaying similar information

**Comment by PVince81** [comment]
Ok, from what I see even master reloaded the sidebar group list with ajax when adding groups... something to fix separately.

This PR is already a good step forward.

To be done separately:
- make the selection dropdowns use the ajax-loaded group list (done in https://github.com/owncloud/core/pull/10994 as follow up)
- use some event system to update the counters in the group sidebar instead of reloading it fully.


Please review and test !

**Comment by VicDeo** [comment]
@PVince81 
- [ ] The input with a new group title should be cleared if group is created successfully
- [ ] Click any group, users of this group are displayed. There is no way to reset filter to show all users now.
- [ ] Create a group, assign any user to it. Click group, user list is filtered. Now click a `delete` icon. Group is deleted but filter is still applied.

Looks good apart of three points above

**Pull request closed without merging**
