### PR TITLE
Fix typo in PHPDoc

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @LukasReschke @nickvergessen 

added in 8.1 with 2b58e8489fcb5eff0e2312209beca038bfe9b40a

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @rullzer @Xenopathic

**Comment by LukasReschke** [comment]
Insta-:1: coming in …

**Comment by LukasReschke** [comment]
Insta-:+1: successfully executed :see_no_evil:

**Comment by Xenopathic** [comment]
:+1:

**Pull request merged**
