### PR TITLE
Remove the listener dav plugin

### PR DESCRIPTION
**Pull request by nickvergessen**
It was added for the FFW, but it moved to a storage wrapper for 9.0 so we can remove it again?

@DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: considering that this was private API

**Comment by rullzer** [comment]
:+1: fine by me :)

**Comment by DeepDiver1975** [comment]
rebased

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
