### PR TITLE
Add tests for doing dav requests with encryption enabled

### PR DESCRIPTION
**Pull request by icewind1991**
Extends the existing dav integration tests with encryption

cc @schiesbn @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
cc @MorrisJobke @LukasReschke please review

**Comment by schiesbn** [comment]
great idea to add tests for it :+1:

**Comment by PVince81** [comment]
:+1: makes sense

Is that OCI failing relevant ?

**Comment by icewind1991** [comment]
> Is that OCI failing relevant ?

has been failing a lot in the last week

**Comment by PVince81** [comment]
Needs rebase.

**Comment by icewind1991** [comment]
just waiting for ci now

**Comment by PVince81** [comment]
@DeepDiver1975 merge or force push here ?

**Pull request merged**
