### PR TITLE
Don't restrain width of icon-logo in example-theme

### LINKED ISSUE #30139: [theme-example] CSS needs to be adjusted for changes in 10.0.3 and 10.0.4
@felixheidecke I remember you had to adjust the ownBrander generated themes (https://github.com/owncloud/core/pull/29161) for changes in 10.0.3 and 10.0.4. Please check if the `theme-example` app also needs changes.

@chriseds tested the `theme-example` in a 10.0.4 and the name was cut:

custom

### PR DESCRIPTION
**Pull request by lordelix**
## Description
See title

## Related Issue

Fixes: https://github.com/owncloud/core/issues/30139

## How Has This Been Tested?

Visual test in FF and Chrome

## Screenshots (if appropriate):
bildschirmfoto vom 2018-01-19 22-42-16

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by felixheidecke** [comment]
GitHub won't find the @ChrisEdS handle?!?! Couldn't add him in the reviewer's section.

**Comment by ChrisEdS** [comment]
Everything looks good to me. However, we should still carry out a test in Safari.

**Comment by felixheidecke** [comment]
@ChrisEdS … can you review and accept so I can merge that thingy? Would be niiiiice

**Comment by ChrisEdS** [comment]
For the moment we have to wait for @michaelstingl - he is the reviewer for this pull request. You can change if you want.

**Comment by felixheidecke** [comment]
There can be multiple reviews/reviewers :-) Don't hesitate to give your thumbs up.

**Review by ChrisEdS — APPROVED** [review]
Go.

**Comment by DeepDiver1975** [comment]
@felixheidecke - please dont remove the codecov comment - https://github.com/owncloud/core/pull/30203#event-1433657519 - never ever - thx

**Comment by DeepDiver1975** [comment]
> GitHub won't find the @ChrisEdS handle?!?! Couldn't add him in the reviewer's section.

@ChrisEdS is now in the core developer team and can be used as reviewer and can be mentioned

**Comment by DeepDiver1975** [comment]
@felixheidecke please backport this to stable10 - THX

**Comment by phil-davis** [comment]
Backport stable10 #30282

**Pull request merged**
