### PR TITLE
Choose button remains disbaled for httpd/unix-directory

### PR DESCRIPTION
**Pull request by sharidas**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

This is not correct. Hence in this patch we validate
if the mimetype is 'httpd/unix-directory'. If so we
don't disable it.

This patch addresses solution for issue: 26034

Signed-off-by: Sujith Haridasan Sujith_Haridasan@mentor.com

### CODE REVIEW

**Comment by sharidas** [comment]
@PVince81 Kindly review my change. This is against issue: https://github.com/owncloud/core/issues/26034

**Comment by PVince81** [comment]
@sharidas next time please properly fill the PR template, there is a section about "Related issue" and "How did you test it". It's fine for now.

**Comment by PVince81** [comment]
Works for the regular use case when entering a folder, but doesn't when clicking a breadcrumb item.

Steps:

1. Create a folder "test/sub"
1. Open the file picker with file "httpd/unix-directory"
1. Click "test": "choose" button will enable itself
1. Click "sub": button stays enabled
1. Click on "test" in the breadcrumb row to return back

Expected: button stays enabled
Actual: button disables itself again

@sharidas please have a look, thanks

**Comment by sharidas** [comment]
@PVince81 Sure. From next time onward I will fill the template properly. I got bit shocked by seeing the template in the beginning. Will take care.

**Comment by sharidas** [comment]
@PVince81 I have updated my patch by validating against the test case shared by you. Kindly review them. 

Thanks,
Sujith H

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by DeepDiver1975** [comment]
@PVince81 I'll remove the backport-request - not that critical in my pov and it introduced a regression - not what we want to have

**Comment by PVince81** [comment]
Indeed, we didn't backport the original PR

**Pull request merged**
