### PR TITLE
[tests-only]Add spaces tests on Share Operations features

### PR DESCRIPTION
**Pull request by amrita-shrestha**
## Description
This PR adds tests related to spaces WebDAV in apiShareOperationsToShares2 suites.

## Related Issue

- https://github.com/owncloud/ocis/issues/3024

## How Has This Been Tested?

- Locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares2-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/111/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIProxySmoke-3-2-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/166/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIFileActionsMenu-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/155/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIMoveFilesFolder-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/134/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIManageUsersGrps-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/133/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-4-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/174/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/171/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingExt2-10.8.0-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/161/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-6-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/176/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/130/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-7-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/177/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIWebdavLockProt-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/152/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingIntUsers1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/145/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUITags-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/149/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIRestrictSharing-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/138/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIFfSmoke-3-3-firefox-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/164/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIWebdavLocks-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/153/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIProxySmoke-3-1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/165/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIManageQuota-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34396/132/1

**Comment by kiranparajuli589** [comment]
lgtm :+1:

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm :+1:

**Comment by phil-davis** [comment]
Looks good. I will approve and merge after #39711 (I want to get various test changes committed in an order that I can easily update test commit ids in stages)

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
