### PR TITLE
Mark ldap agent password as sensitive

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 @blizzz @gig13

### CODE REVIEW

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by blizzz** [comment]
:+1:

**Comment by nickvergessen** [comment]
Tests pass, only the coverage file can not be copy pasted :fearful:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
We should prepare backport prs right away to get this in as soon as we get the confirmation by @karlitschek

**Comment by nickvergessen** [comment]
No backport needed, occ config:* is new in 8.2 :wink:

**Comment by DeepDiver1975** [comment]
> No backport needed, occ config:* is new in 8.2 :wink:

as discussed:

**Pull request merged**
