### PR TITLE
[stable8.1] use login name for password reset

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/owncloud/core/pull/18556

@PVince81 @blizzz please review, thanks!

@cdamken your backport... have fun.

cc @karlitschek please approve, thanks!

### CODE REVIEW

**Comment by cdamken** [comment]
@pako81 Could you please Test in your environment

**Comment by karlitschek** [comment]
yes. makes sense. please backport

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by cdamken** [comment]
@schiesbn the backport worked great!, thank you a lot!

**Comment by schiesbn** [comment]
@PVince81 @blizzz you already reviewed the already merged PR for master, can you also have a look at the backport? Thanks!

**Comment by PVince81** [comment]
:+1: tested, works

**Comment by schiesbn** [comment]
successful tested by @pako81 and @cdamken ... count as second :+1:

**Pull request merged**
