### PR TITLE
Update existing auth token on apache login

### PR DESCRIPTION
**Pull request by butonic**
## Description
In SAML scenarios the php session token may be gone (switching backend servers due to shutdown when using sticky sessions). This currently leads to a UniqueConstraintViolationException in the authtoken table.

```json
{"reqId":"WHShMTK0w95u6uexze52XwAAAA4","remoteAddr":"192.168.224.185","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_authtoken`(`uid`,`login_name`,`name`,`token`,`type`,`last_activity`) VALUES(?,?,?,?,?,?)' with params [\\\"<userid>\\\", \\\"<userid>\\\", \\\"Mozilla\\\\\\\/5.0 (Windows NT 6.1; WOW64; Trident\\\\\\\/7.0; rv:11.0) like Gecko\\\", \\\"934b909ea678992996e3cf537fbbf2ea68ad6137f6aacad2069b9d229f4b9246686e2ff477aeb237e8bb9a89bcd53924823375f7b8c8c6dd8aa1a6cc1aa6c249\\\", 0, 1484038449]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '934b909ea678992996e3cf537fbbf29a68ad6127f6aacad2069b9d229f4b9246' for key 'authtoken_token_index'\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n
#1 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(174): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n
#2 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(251): Doctrine\\\\DBAL\\\\Statement->execute()\\n
#3 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(125): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array)\\n
#4 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(89): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OC\\\\Authentication\\\\Token\\\\DefaultToken))\\n
#5 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/lib\\\/private\\\/User\\\/Session.php(527): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->generateToken(*** sensitive parameters replaced ***)\\n
#6 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/lib\\\/private\\\/legacy\\\/user.php(184): OC\\\\User\\\\Session->createSessionToken(Object(OC\\\\AppFramework\\\\Http\\\\Request), '<userid>', '<userid>')\\n
#7 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/lib\\\/private\\\/legacy\\\/user.php(217): OC_User::loginWithApache(Object(OCA\\\\User_Shibboleth\\\\UserBackend))\\n
#8 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/lib\\\/base.php(939): OC_User::handleApacheAuth()\\n
#9 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/lib\\\/base.php(879): OC::handleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n
#10 \\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/index.php(54): OC::handleRequest()\\n
#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud-9.1.3\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}","level":3,"time":"2017-01-10T08:54:09+00:00","method":"GET","url":"\/oc-shib\/","user":"<userid>"}
```

The end user will see an ugly error message.

## Motivation and Context
This PR allows regenerates the session id to prevent on a successful apache login to prevent the UniqueConstraintViolationException.

## How Has This Been Tested?
manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by phisch — APPROVED** [review]

**Comment by PVince81** [comment]
No possible unit tests I guess ? 😞

**Comment by PVince81** [comment]
Moving to 9.1.5 as this is a corner case.

@PhilippSchaffrath will try and write a unit test for this.

**Comment by PhilippSchaffrath** [comment]
Ok, forget it! Testing this is waaay too complex, we would not gain anything from that since the test itself would be unmaintainable and stop us from refactoring this in the future.

An additional review from @DeepDiver1975 or @PVince81 would be good though.

**Comment by butonic** [comment]
this has been tested successfully at two customers and needs forward port to master.

**Comment by PVince81** [comment]
@butonic @phisch should I do the forward port ?

**Comment by PVince81** [comment]
👍 then, let's merge

**Comment by PVince81** [comment]
master: https://github.com/owncloud/core/pull/27223

**Pull request merged**
