### PR TITLE
Fix repair constructor for single user repair

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
Repair for a single user was broken. Missing logging instance in the constructor.

## Related Issue
Tried it and it was broken.

## Motivation and Context
Would be nice if it worked. 

## How Has This Been Tested?
`occ files:scan --repair testuser`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
It would be nice to have a suite of ``occ`` acceptance tests that did a basic run of all the ``occ`` commands. It would not be difficult to do, since we already have the ability to easily run ``occ`` commands during acceptance tests.

Then these sort of regressions would be caught.

**Comment by PVince81** [comment]
apparently duplicate of https://github.com/owncloud/core/pull/29635, how come this is still needed ?

**Comment by tomneedham** [comment]
> apparently duplicate of #29635, how come this is still needed ?

You fixed the repairAll, not singe user repair:

https://github.com/owncloud/core/pull/29635/files#diff-20ef48bfe43033b6fb2e585b873420beR163

**Comment by PVince81** [comment]
please add matching unit test if possible

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@tomneedham please backport

**Comment by PVince81** [comment]
Repair command was broken through https://github.com/owncloud/core/pull/30451 (unreleased then), so this PR could be counted as an addition to this one to fix it.

**Pull request merged**
