### PR TITLE
detect root of mountpoint also if the trailing slash is missed

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/owncloud/core/pull/13881

cc @DeepDiver1975 @icewind1991 @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
:heavy_check_mark: for backporting this as it fixes a support issue

**Comment by nickvergessen** [comment]
Also tested with encryption enabled on server1 and server2 seperatly aswell as using the same and different passwords, everything still works.

**Pull request merged**
