### PR TITLE
Fix file size of encrypted files

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@schiesbn @th3fallen @PVince81 please test - THX

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by PVince81** [comment]
Works :+1:

Without encryption: filesize leaves files alone and doesn't set "encrypted" any more in the DB.
With encryption: file can be encrypted and downloaded properly

**Comment by PVince81** [comment]
@schiesbn your +1 too ?

**Comment by schiesbn** [comment]
looks good :+1:

**Pull request merged**
