### PR TITLE
Catch more exceptions in DAV client

### LINKED ISSUE #15430: propfind on webdav root results in a http 500 internal error when fc share is unavailable
### Steps to reproduce
1. Do a PROPFIND on the webDAV root - something like "http://server/owncloud/remote.php/webdav/"
    Also checked with `curl -u <username>:<password> -X PROPFIND -H "Content-Type: text/xml" -d "<?xml version='1.0' encoding='utf-8' ?><D:propfind xmlns:D='DAV:'><D:allprop/></D:propfind>" <owncloud-server-url>/remote.php/webdav/`

### Expected behaviour
Valid webdav response

### Actual behaviour
Internal error

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log)
```
{"reqId":"06cce899959355c34f6a11854494fde7","remoteAddr":"10.40.30.21","app":"remote","message":"The passed data is not valid XML","level":4,"time":"2015-04-07T09:02:42+00:00"}
{"reqId":"dfa929d07bd6993351e2fc8230411a16","remoteAddr":"10.40.10.254","app":"remote","message":"The passed data is not valid XML","level":4,"time":"2015-04-07T09:10:10+00:00"}
```

#### PROPFIND response
```
<!DOCTYPE html>
<!--[if lt IE 7]><html class="ng-csp ie ie6 lte9 lte8 lte7" data-placeholder-focus="false" lang="en"><![endif]-->
<!--[if IE 7]><html class="ng-csp ie ie7 lte9 lte8 lte7" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if gt IE 9]><html class="ng-csp ie" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if !IE]><!--><html class="ng-csp" data-placeholder-focus="false" lang="en" ><!--<![endif]-->

	<head data-requesttoken="">
		<title>
		ownCloud		</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=543672169">
		<link rel="shortcut icon" type="image/png" href="/core/img/favicon.png" />
		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png" />
					<link rel="stylesheet" href="/core/css/styles.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/header.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/mobile.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/icons.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/fonts.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/apps.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/fixes.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/multiselect.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/jquery-tipsy.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/share.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/styles.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/header.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
							<script type="text/javascript" src="/core/vendor/jquery/jquery.min.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/jquery/jquery-migrate.min.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/underscore/underscore.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/moment/min/moment-with-locales.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/handlebars/handlebars.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/placeholders.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/jquery-tipsy.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/compatibility.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/jquery.ocdialog.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/oc-dialogs.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/js.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/l10n.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/octemplate.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/eventsource.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/config.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/search/js/search.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/oc-requesttoken.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/apps.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/snapjs/dist/latest/snap.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/placeholder.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/blueimp-md5/js/md5.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/jquery.avatar.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/avatar.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/backgroundjobs.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/share.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/apps/files_sharing/js/share.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/apps/files_sharing/js/external.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/apps/files_versions/js/versions.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					</head>
	<body id="body-login">
		<noscript><div id="nojavascript"><div>This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank">enable JavaScript</a> and reload the page.</div></div></noscript>
		<div class="wrapper"><!-- for sticky footer -->
			<div class="v-align"><!-- vertically centred box -->
									<header>
						<div id="header">
							<div class="logo svg">
								<h1 class="hidden-visually">
									ownCloud								</h1>
							</div>
							<div id="logo-claim" style="display:none;"></div>
						</div>
					</header>
								<span class="error error-wide">
	<h2><strong>Internal Server Error</strong></h2>
		<p>The server encountered an internal error and was unable to complete your request.</p>
		<p>Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.</p>
		<p>More details can be found in the server log.</p>
	<br />

	<h2><strong>Technical details</strong></h2>
	<ul>
		<li>Remote Address: 10.40.30.21</li>
		<li>Request ID: 06cce899959355c34f6a11854494fde7</li>
					<li>Code: 0</li>
			<li>Message: The passed data is not valid XML</li>
			<li>File: /home/jvillafanez/src/owncloud/owncloud2/3rdparty/sabre/dav/lib/Sabre/DAV/Client.php</li>
			<li>Line: 542</li>
			</ul>

			<br />
		<h2><strong>Trace</strong></h2>
		<pre>#0 /home/jvillafanez/src/owncloud/owncloud2/3rdparty/sabre/dav/lib/Sabre/DAV/Client.php(181): Sabre\DAV\Client-&gt;parseMultiStatus(&#039;&lt;!DOCTYPE html&gt;...&#039;)
#1 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/storage/dav.php(550): Sabre\DAV\Client-&gt;propFind(&#039;&#039;, Array)
#2 /home/jvillafanez/src/owncloud/owncloud2/apps/files_sharing/lib/external/storage.php(144): OC\Files\Storage\DAV-&gt;hasUpdated(&#039;&#039;, 1424774464)
#3 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/storage/wrapper/wrapper.php(357): OCA\Files_Sharing\External\Storage-&gt;hasUpdated(&#039;&#039;, 1424774464)
#4 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/cache/watcher.php(67): OC\Files\Storage\Wrapper\Wrapper-&gt;hasUpdated(&#039;&#039;, 1424774464)
#5 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/view.php(976): OC\Files\Cache\Watcher-&gt;checkUpdate(&#039;&#039;, Array)
#6 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/filesystem.php(793): OC\Files\View-&gt;getFileInfo(&#039;/pics&#039;, false)
#7 /home/jvillafanez/src/owncloud/owncloud2/lib/private/helper.php(923): OC\Files\Filesystem::getFileInfo(&#039;/pics&#039;, false)
#8 /home/jvillafanez/src/owncloud/owncloud2/lib/private/connector/sabre/directory.php(235): OC_Helper::getStorageInfo(&#039;/pics&#039;)
#9 /home/jvillafanez/src/owncloud/owncloud2/lib/private/connector/sabre/server.php(247): OC_Connector_Sabre_Directory-&gt;getQuotaInfo()
#10 /home/jvillafanez/src/owncloud/owncloud2/lib/private/connector/sabre/server.php(104): OC_Connector_Sabre_Server-&gt;getPropertiesForPath(&#039;&#039;, Array, 1)
#11 [internal function]: OC_Connector_Sabre_Server-&gt;httpPropfind(&#039;&#039;)
#12 /home/jvillafanez/src/owncloud/owncloud2/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;&#039;)
#13 /home/jvillafanez/src/owncloud/owncloud2/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;PROPFIND&#039;, &#039;&#039;)
#14 /home/jvillafanez/src/owncloud/owncloud2/apps/files/appinfo/remote.php(61): Sabre\DAV\Server-&gt;exec()
#15 /home/jvillafanez/src/owncloud/owncloud2/remote.php(54): require_once(&#039;/home/jvillafan...&#039;)
#16 {main}</pre>
	</span>
				<div class="push"></div><!-- for sticky footer -->
			</div>
		</div>

		<footer>
			<p class="info">
				<a href="https://owncloud.org" target="_blank">ownCloud</a> – web services under your control			</p>
		</footer>
	</body>
</html>

```

### Notes
This bug is preventing the correct functions of mobile apps, and probably the desktop apps

### LINKED ISSUE #15524: Handle HTTP connection errors in files_external as StorageNotAvailable
Follow up from https://github.com/owncloud/core/pull/15521#issuecomment-91370650

If I shut down the apache it's a:

`Sabre\HTTP\ClientException` with code `7` and message `Failed to connect to 192.168.0.17 port 80: Connection refused`. We should handle this as well.

If I shut down the whole PC it's:

`Sabre\HTTP\ClientException` with code `7` and message `Failed to connect to 192.168.0.17 port 80: No route to host`.

Can we include these two as well? Because I think they are also valid "storage not available", because of network/server/process outage.

### PR DESCRIPTION
**Pull request by PVince81**
- catch parse errors when remote server returns HTML instead of XML (ex: when EE license expired)
- catch ClientException / ConnectionException when connection was refused when remote server is down / unreachable

@MorrisJobke @icewind1991 @LukasReschke @nickvergessen 

Fixes https://github.com/owncloud/core/issues/15524
Fixes https://github.com/owncloud/core/issues/15430

To test:
- PROPFIND on root (200, list returned)
- PROPFIND on received share (503)
- web UI, access share

combined with:
- with remote server in maintenance mode: share stays
- with remote server with expired/invalid license: share stays
- with no connection to remove server (unplug cable): share stays
- unshare/expire the share on the remote server: accessing the share auto-deletes it for the recipient

### CODE REVIEW

**Comment by PVince81** [comment]
I ran the pyocclient test suite in a received s2s share (with "add to ownCloud") and all FS operations worked fine.

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
I prepared a backport PR here for stable8: https://github.com/owncloud/core/issues/15533

@karlitschek please confirm

**Comment by MorrisJobke** [comment]
Works like a charm :+1:

**Pull request merged**
