### PR TITLE
[stable9.1] Catch session unavailable exception

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/core/pull/30141 to stable9.1

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
uh oh `Test\Session\CryptoSessionDataTest.testDestructExceptionCatching` fails

**Comment by tomneedham** [comment]
Oh dear - which means its dead on core as well.

**Comment by tomneedham** [comment]
Needs forward port

**Comment by PVince81** [comment]
@tomneedham it's green! merge ?

can you do the forward ports ?

**Pull request merged**
