### PR TITLE
revert #10422

### PR DESCRIPTION
**Pull request by jknockaert**
Now that #14383 is merged the motivation for #10422 is gone, so it should be reverted.

### CODE REVIEW

**Comment by jknockaert** [comment]
Bah, needs to be rebased.

**Comment by jknockaert** [comment]
OK, successfully rebased (that's a first).

**Comment by jknockaert** [comment]
Ok, the rebase wasn't successful. I'll try again later.

**Comment by jknockaert** [comment]
It seems that the code to disable http-range requests being served for encrypted files has been moved since #10422. I think I correctly located it and removed it. I would appreciate any review here.

**Comment by jknockaert** [comment]
Not sure how to understand the test results.

**Comment by jknockaert** [comment]
@PVince81 could you pls check this pr? As far as I can see the code I am working on was introduced when Sabre was updated to 2.1.

**Comment by PVince81** [comment]
Our bot is sometimes sick, let me fix that

**Comment by PVince81** [comment]
Created a new local branch: https://github.com/owncloud/core/pull/15150

**Pull request closed without merging**
