### PR TITLE
Allow integrity check via OccController

### PR DESCRIPTION
**Pull request by VicDeo**
## Description

Allow integrity check via OccController
## Related Issue

https://github.com/owncloud/updater/issues/404
## Motivation and Context

Message on integrity check after 9.1->daily master update
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: as discussed.

Backport ?

**Comment by VicDeo** [comment]
Stable9.1: https://github.com/owncloud/core/pull/26482

**Comment by PVince81** [comment]
@VicDeo stable9 needed as well I guess ?

**Comment by VicDeo** [comment]
@PVince81 yes, just to be on the safe side

**Pull request merged**
