### PR TITLE
[stable8.2] Fixes pagination in IE

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/22548 to stable8.2

Please review/test @MorrisJobke @LukasReschke @Henni @DeepDiver1975 @karlitschek

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] backport approval

@karlitschek please approve this backport

**Comment by MorrisJobke** [comment]
Tested and works in IE, Edge, Firefox, Chrome and Safari. :+1:

**Comment by karlitschek** [comment]
backport is fine :+1:

**Comment by PVince81** [comment]
CSS only => merging

**Pull request merged**
