### PR TITLE
Avoid re-propagation of shares during one propagation run

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fix was proposed by @nickvergessen 

cc @schiesbn @icewind1991 @Xenopathic @PVince81

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1: was going to do the same thing

**Comment by PVince81** [comment]
:+1:

**Comment by icewind1991** [comment]
@karlitschek backport I assume

**Comment by karlitschek** [comment]
yes. absolutely!

**Comment by MorrisJobke** [comment]
I will create the backport soon.

**Comment by MorrisJobke** [comment]
Backport: https://github.com/owncloud/core/pull/18928

**Pull request merged**
