### PR TITLE
Backport  #23752 to stable9

### PR DESCRIPTION
**Pull request by josh4trunks**
Fixes orientation of thumbnails and gallery view of JPG's with exif rotation.

@MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by MorrisJobke** [comment]
Backport approval: https://github.com/owncloud/core/issues/21485#issuecomment-205776437

**Comment by MorrisJobke** [comment]
Tested and works 👍 

cc @oparoz @rullzer @icewind1991

**Comment by karlitschek** [comment]
nice. please backport 👍

**Comment by DeepDiver1975** [comment]
can we have a jenkins pr on this? THX

**Comment by MorrisJobke** [comment]
> can we have a jenkins pr on this? THX

Yes.

**Comment by MorrisJobke** [comment]
CI PR: https://github.com/owncloud/core/pull/23948

**Comment by DeepDiver1975** [comment]
> CI PR: #23948

THX @MorrisJobke

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
