### PR TITLE
[WIP] Remote shares in OCS API

### PR DESCRIPTION
**Pull request by rullzer**
This is a WIP PR for #13627
- [x] Possibility to share remote via OCS API
- [ ] Unit tests
- [ ] OCS Call to list pending shares
- [ ] OCS Call to accept/reject pending shares

### CODE REVIEW

**Comment by rullzer** [comment]
I'm not sure how to do proper unit testing with this to be honest.

Also we already have the externalsharescontroller. Which is probably something we do not want to duplicate. But as far as I know the OC_API::register stuff does not yet handle controllers.

**Comment by PVince81** [comment]
From what I remember, I was told to keep the controllers "light" and use service classes instead.
So when writing the tags stuff I put most of the logic in a service class https://github.com/owncloud/core/blob/master/apps/files/service/tagservice.php#L53 which is then called from the controller here https://github.com/owncloud/core/blob/master/apps/files/controller/apicontroller.php#L85

But I heard it should be possible to write tests for controllers too. You need to instantiate it and just pass arguments. Then check if the DataResponse contains whatever is expected.

**Comment by PVince81** [comment]
I guess you should probably also add the "get list of pending shares" so you can use it in the unit test to see if the shares were actually added.

**Comment by PVince81** [comment]
CC @jnfrmarks this is the API that will be needed for the automated tests

**Comment by DeepDiver1975** [comment]
rescheduling this for 8.2 - we are entering freeze for 8.1 tomorrow

**Comment by nickvergessen** [comment]
Replaced by #16733

**Pull request closed without merging**
