### PR TITLE
[WIP] Apply commits from release 10.8.0

### PR DESCRIPTION
**Pull request by phil-davis**
These are the things in `release-10.8.0` that are not in `master`.

I am just seeing what there is - to think about how to get rid of the merge-conflict that `release-10.8.0` reports.

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-7-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31140/177/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31140/172/1

**Comment by phil-davis** [comment]
> boom Acceptance tests pipeline **apiProxySmoke-8-7-mariadb10.2-php7.4** failed. The build has been cancelled.
> 
> https://drone.owncloud.com/owncloud/core/31140/177/1

https://drone.owncloud.com/owncloud/core/31140/177/14
curl: (6) Could not resolve host: proxy

some startup timing issue - restarted

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUICreateDelete-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31142/131/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingExt1-10.6.0-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31142/161/1

**Comment by phil-davis** [comment]
Good - drone CI passes. SonarCloud complains about a little bit low unit test coverage.

**Comment by phil-davis** [comment]
This has been resolved - another PR merged some trashbin-skip fixes from release-10.8.0 to master.

**Pull request closed without merging**
