### PR TITLE
Deleted duplication in UI tests

### PR DESCRIPTION
**Pull request by AustrianDC**
## Description
Deleted duplicated code in UI test feature files

## Related Issue
https://github.com/owncloud/guests/issues/162

## Motivation and Context
It shortens the code, Makes it easier to understand and speeds up the test run.

## How Has This Been Tested?
Travis will test it

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by individual-it** [comment]
UI tests on travis will fail here because it comes from a remote fork. kicked them of here https://github.com/individual-it/owncloud-core/pull/43

**Comment by individual-it** [comment]
screenshot-2017-10-25 job 329 4 - individual-it owncloud-core - travis ci

@AustrianDC your editor seems to add some characters to the start of the file. Please make the edit again, so that the first line is not changed

**Review by phil-davis — DISMISSED** [review]
That will reduce a bit of wasted time in testing.
How do we merge this, since CI is not going to happen?

**Comment by individual-it** [comment]
Please do not merge yet, there are some funny bytes at the start of the file, so behat does recognize the file start

**Comment by individual-it** [comment]
travis tests passed  on https://github.com/individual-it/owncloud-core/pull/44

**Comment by individual-it** [comment]
backport in #29361

**Pull request merged**
