### PR TITLE
Add mount option to disable sharing

### PR DESCRIPTION
**Pull request by icewind1991**
Adds a mount option to disable sharing from an external storage

mount option

sharing disabled

cc @PVince81

### CODE REVIEW

**Comment by rullzer** [comment]
So what happens when I share a file. And then move that file to the external storage?

**Comment by icewind1991** [comment]
The share still exists, this only affects creating new shares

**Comment by PVince81** [comment]
Tested, the basic stuff works.

@icewind1991 would it be possible to add a check in the sharing code to make sure that the target storage allows sharing ?

Steps:

1. Mount "sftp"
1. Share "sftp/test" with link
1. Change "sftp" config and disallow share
1. Open link
=> link share should stop working, but it still does

Same problem with user shares: the user can still access the share.

**Comment by icewind1991** [comment]
Is removing existing shares intended behavior?

**Comment by PVince81** [comment]
@icewind1991 good question, I'll ask in the original ticket.

In the meantime I think this can be merged already :+1:

**Comment by PVince81** [comment]
https://github.com/owncloud/core/issues/19157#issuecomment-161624238

**Comment by rullzer** [comment]
So I don't know enough about external shares. But the following just hit me. Assume a structure like:

```
root
|--FOLDER
   |--ExternalMount
```

Is that possible? And if so are share permissions propergated up? So that if I try to share FOLDER but ExernalMount does not allow sharing. Does the FOLDER than also tell me that I can't share it?

**Comment by PVince81** [comment]
@rullzer good question for the original ticket

**Comment by icewind1991** [comment]
Good catch, it currently doesn't take that into account

I'll see if I can come up with a fix

**Comment by icewind1991** [comment]
Hmm, from some testing it seems that if you share a folder containing an external storage the external storage doesn't actually show up for the recipient (master and stable8.2)

**Comment by PVince81** [comment]
> Hmm, from some testing it seems that if you share a folder containing an external storage the external storage doesn't actually show up for the recipient (master and stable8.2)

Possible regression, I seem to remember that it used to work.

**Comment by PVince81** [comment]
=> separately

**Comment by PVince81** [comment]
@icewind1991 please rebase and fix the conflicts.
I also believe that we added some fixes for share permissions which might be relevant for retesting this.
Thanks.

**Comment by icewind1991** [comment]
rebased

**Comment by PVince81** [comment]
I retested and while it seems to work overall there are the following issues:
- [ ] TODO: existing user shares still work even after disabling shares: @icewind1991 did we talk about a separate fix for this ? a separate ticket/todo/pr is fine to not forget it
- [ ] BUG: cannot move a local folder into the mount point when the mount point has sharing disabled, getting this in the log: `{"reqId":"3cjeDuWOL10wnTb2zX2T","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function executeQuery() on null at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/cache\/cache.php#508","level":3,"time":"2016-01-08T11:40:35+00:00","method":"MOVE","url":"\/owncloud\/remote.php\/webdav\/rooxxy"}
`

**Comment by PVince81** [comment]
Hold on, might have fetched an older version. Testing again

**Comment by PVince81** [comment]
The mentioned problems still exist after fetching. Please have a look, thanks.

**Comment by icewind1991** [comment]
> BUG: cannot move a local folder into the mount point when the mount point has sharing disabled, getting this in the log:

Can't reproduce

**Comment by icewind1991** [comment]
> TODO: existing user shares still work even after disabling shares

https://github.com/owncloud/core/pull/22015

**Comment by PVince81** [comment]
Looks good, the weird bug is gone :+1:

**Comment by PVince81** [comment]
Needs a second reviewer @schiesbn @rullzer @nickvergessen 

Note: existing shares will still be accessible, will be fixed separately with https://github.com/owncloud/core/pull/22015 and https://github.com/owncloud/core/pull/20928

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
