### PR TITLE
Add events for password validation

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Makes it possible for apps to implement validation.
Also added code to properly throw exceptions and convert them into
messages to display in the UI.

## Motivation and Context
To allow for password policies

## How Has This Been Tested?
With a quick test app, throw an exception in the hooks and check that the message is properly displayed in the following cases:

- [x] TEST: when setting a password in the link share dialog
- [x] TEST: when a user sets a password in the personal page
- [x] TEST: when a user sets a password after password reset
- [x] TEST: when an admin sets a password in the users page
- [x] TEST: when creating a user with OCC: `occ user:add user1`
- [x] TEST: when resetting a password with OCC `occ user:resetpassword user1`
- [x] TEST: when creating a user with provisioning API: `curl -X POST --user admin:admin "http://localhost/owncloud/ocs/v1.php/cloud/users" -d userid="userx" -d password="y"`
- [x] TEST: when setting a password with provisioning API: `curl -X PUT --user admin:admin "http://localhost/owncloud/ocs/v1.php/cloud/users/user1" -d key="password" -d value="x"`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
All test cases work now, please review @DeepDiver1975 @tomneedham @VicDeo

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2017-05-15 13-28-37

**Comment by PVince81** [comment]
One does not simply... ok I'll have a look

**Comment by PVince81** [comment]
Rebased for CI, please recheck

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
