### PR TITLE
Adding error handling in case setting the password fails

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@jancborchardt @blizzz here is an alternative approach - please test - THX

@karlitschek @cmonteroluque backport as with #17763

New behavior:
bildschirmvideo von 23 07 2015 09_48_52

Old behavior:
bildschirmvideo von 23 07 2015 12_07_19

### CODE REVIEW

**Comment by jancborchardt** [comment]
Can we also show the error message via tipsy tooltip, and not deleting the password in that case so ppl can add characters? This is also how we handle the password strength meter in the personal settings.

I’m just worried the input title change is not very visible.

**Comment by jancborchardt** [comment]
That said, this new solution is definitely better than the old one because in the old one, the modal rips you out of the flow and closes the whole sharing dropdown when »Ok« is clicked.

**Comment by DeepDiver1975** [comment]
> Can we also show the error message via tipsy tooltip, and not deleting the password in that case so ppl can add characters? This is also how we handle the password strength meter in the personal settings.

without resetting the password we are back to the issue sending-the-same-request-twice

**Comment by DeepDiver1975** [comment]
> . So :+1:, although improvements would be nice.

We will anyhow improve as soon as we move this to the sidebar - this change should be kept minimal because of the backport necessity

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
