### PR TITLE
Test email verification with international email address

### LINKED ISSUE #13586: [User management] International email addresses aren't valid
### Steps to reproduce

Using an admin user:

Activate send email to new users checkbox
1. Create a new user with international email address.
### Expected behaviour

International email addresses are allowed.
### Actual behaviour

International email addresses (with Ñ,Ö,Ç..) are invalid.
### Server configuration

**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no
### Client configuration

**Browser:**
Chrome, Firefox

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Adds unit test to show that international email addresses are supported now

## Related Issue
fixes #13586

## How Has This Been Tested?
:robot: 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 please backport to core's stable10

no - because it requires swift mailer update and this is not compatible with stable10 due to php versions

**Comment by PVince81** [comment]
ah yes, indeed. thanks for the reminder

**Comment by PVince81** [comment]
backported now that we could update swiftmailer: https://github.com/owncloud/core/pull/34759

**Pull request merged**
