### PR TITLE
Combine upload action into the "New" menu

### PR DESCRIPTION
**Pull request by PVince81**
Combine upload action into the "New" menu.

Also refactored the new menu to be encapsulated in the more portable NewFileMenu JS class.
Moved directory and file creation logic to the FileList class instead of having it floating in file-upload.js.

This is a simplified version of https://github.com/owncloud/core/pull/18589 where the menu stays where it is. We can move it to the sidebar later.
- [x] TODO: write JS unit tests

@jancborchardt @MorrisJobke please review.
If we agree on the design/placement I'll write the missing unit tests.

### CODE REVIEW

**Comment by PVince81** [comment]
Let me rebase this onto master first so we get the latest styles.

**Comment by PVince81** [comment]
Rebased. (Jenkins will stumble and fall)

**Comment by MorrisJobke** [comment]
bildschirmfoto von 2015-08-28 17-53-25

Text file icon is missing.

**Comment by karlitschek** [comment]
where are we with that? We need this for 8.2

**Comment by jancborchardt** [comment]
Fixed some layout issues.

@PVince81 when I click New file or Folder, the input field does not show right away, but this:
capture du 2015-09-03 00-58-22
As soon as that is fixed, I can do the input field detail positioning.

**Comment by PVince81** [comment]
Strange, works fine in Chromium but Firefox shows the three dots

**Comment by PVince81** [comment]
There's a text-overflow: ellipsis on every menu item. For some reason it kicks in in Firefox but not Chromium. I'll disable it for this specific menu.

Last time I checked that all possible translations of "New file" would fit the current width, so it should be fine.

**Comment by PVince81** [comment]
@jancborchardt I removed the ellipsis, should work now.

I'll take care of unit tests.

**Comment by PVince81** [comment]
Unit tests were added.

@jancborchardt when you're done with the design, please set the label to "to review".
Thanks.

**Comment by karlitschek** [comment]
Can we review and merge this? Quite important :-)

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by jancborchardt** [comment]
Nice! :) :+1: any details we can fix in follow-up PRs.

**Comment by karlitschek** [comment]
nice!

**Pull request merged**
