### PR TITLE
Systemtags sidebar permissions

### PR DESCRIPTION
**Pull request by PVince81**
- [x] REQUIRES: https://github.com/owncloud/core/pull/21831
- [x] REQUIRES: https://github.com/owncloud/core/pull/21814
- [x] fix unit tests

For https://github.com/owncloud/core/issues/21815#issue-127709860

### CODE REVIEW

**Comment by PVince81** [comment]
Note: this PR also contains to be able to test: https://github.com/owncloud/core/pull/21814

**Comment by nickvergessen** [comment]
:+1: works

user-view is still crappy, but we will see; admin-view looks nice and shiny

**Comment by PVince81** [comment]
- [ ] BUG: when creating tags in the sidebar as admin, they appear as "invisible, non-assignable" until refresh

I'll have a look

**Comment by PVince81** [comment]
Rebased and fixed, please review.

**Comment by PVince81** [comment]
@MorrisJobke if you want to review this too :smile: 
Currently you can only change tag visibility/assignability directly in the database or PROPPATCH.

Need to test both with admin user (sees permissions in GUI) and regular user (doesn't see permissions)

**Comment by PVince81** [comment]
@DeepDiver1975 looks like Oracle is already off for the week-end ?
```
10:56:16  -> ORA-01017: invalid username/password; logon denied Check environment: ORACLE_HOME=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server ORACLE_SID=XE LD_LIBRARY_PATH=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/lib: NLS_LANG=AMERICAN_AMERICA.AL32UTF8 tnsnames.ora is readable
10:56:16 Kill the docker aefb2dc13100930ee3c2f08571dfe9c520a6da37fc44e9cee0d85b582791db82
```

**Comment by MorrisJobke** [comment]
* [ ] BUG: adding a new tag as admin shows wrong attributes (invisible) - after pressing enter the correct attributes are shown in the selection:
bildschirmfoto 2016-01-22 um 17 17 35

**Comment by PVince81** [comment]
@MorrisJobke did you fetch/pull ? That's the bug I just fixed

**Comment by MorrisJobke** [comment]
> @MorrisJobke did you fetch/pull ? That's the bug I just fixed

Yes. I was at 2d354be

**Comment by MorrisJobke** [comment]
I just pulled again - no change. Refreshed both of my browsers (chrome & safari) both show the same behavior :(

**Comment by PVince81** [comment]
Okay, thanks. Then you found another case.

**Comment by PVince81** [comment]
Rebased and fixed @MorrisJobke

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
