### PR TITLE
reduce query size by properly reusing the query builder

### PR DESCRIPTION
**Pull request by butonic**
:disappointed: ... :crossed_fingers: this works

for reviewing ignore whitespace changes, that makes a lot clearer what I did.

### CODE REVIEW

**Comment by butonic** [comment]
tests seem to be running into unrelated problems

**Comment by butonic** [comment]
failing tests unrelated.

**Comment by phil-davis** [comment]
I restarted the drone build, so you will (hopefully) get a clean run of green CI today.

**Comment by jvillafanez** [comment]
Changes make sense 👍 
As far as I know, the limit for the "in" clause is 1000 due to Oracle: not sure if we want to rise the chunk size a bit more.

**Comment by butonic** [comment]
Other db platforms have different limits for the IN clause. 900 should be safe, even if someone accidentally adds other elements to the in clause ... on the other hand ... that should explode as early as possible. Again, define a constant for every platform with the max allowed elements in the in clause, use it instead of hard coded values. In a different PR.

**Comment by PVince81** [comment]
the limit is not only on the "IN" clause as far as I reember. at least with sqlite it was the total count of parameters, including the ones specified in "IN", so depending how many params were used in the WHERE clause the IN limit goes down.

**Comment by VicDeo** [comment]
yes, this limit is applied to the total amount of placeholders in the query

**Comment by butonic** [comment]
@PVince81 that would be a different limit. It depents on many factors:
- does doctrine build the query (then no parameters are used) or does the driver natively send prepared statements (oracle does as you can see in the query plans: the parameters are still placeholders)
- is there a limit on the number of parameters per query: https://stackoverflow.com/a/6582902 and the [jooq docs](https://www.jooq.org/doc/3.12/manual/sql-building/dsl-context/custom-settings/settings-inline-threshold/): 
  - Oracle : 32767
  - PostgreSQL : 32767
  - SQLite : 999

**Comment by butonic** [comment]
I think we have a :+1: from @jvillafanez and tests failing for unrelated reasons. can we merge this or are we waiting for a response from @voroyam?

**Comment by voroyam** [comment]
A response to what?

**Comment by PVince81** [comment]
I've restarted the build

**Comment by PVince81** [comment]
@butonic you can already raise the backport PR

**Comment by phil-davis** [comment]
I rebased this. I don't know why it keeps failing CI today, when other PRs are getting through.
I made a cherry-pick of this to my own test PR #34916 and it looks like that is passing.
Maybe a rebase will do magic here?

**Review by mrow4a — APPROVED** [review]
wow.. good find!

**Comment by mrow4a** [comment]
The fix is much correct, as this was clearly overlooked that query could become massive, but I am actually quite curious what happens in Oracle that just parsing takes forever.

**Comment by butonic** [comment]
@mrow4a AFAICT the hard parsing step in oracle also check access permissions on columns. See https://blog.pythian.com/cursor-pin-s-wait-on-x-in-the-top-5-wait-events/

**Comment by phil-davis** [comment]
Backport `stable10` #34915

**Pull request merged**
