### PR TITLE
[stable10] Revert auth PR

### PR DESCRIPTION
**Pull request by tomneedham**
Revert of https://github.com/owncloud/core/pull/31428, backport of this from https://github.com/owncloud/core/pull/31759

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
As discussed in https://github.com/owncloud/core/issues/31731#issuecomment-396970001

**Comment by PVince81** [comment]
- [ ] requires https://github.com/owncloud/core/pull/31460 to be merged first

**Comment by phil-davis** [comment]
drone job fails here https://drone.owncloud.com/owncloud/core/7822/201 
this (and any other PRs to ``stable10``) need to be rebased after https://github.com/owncloud/core/pull/31762 has been merged.

**Comment by PVince81** [comment]
/me doing robot voice :robot: yes, sir :robot: I will rebase, sir :robot:

**Comment by PVince81** [comment]
rebased

**Comment by PVince81** [comment]
restarted web UI acceptance test, hoping it's just a timeout of some sorts

**Pull request merged**
