### PR TITLE
Move core apps from OC_Log::write to OCP\Util

### PR DESCRIPTION
**Pull request by rullzer**
In a lot of places the OC_Log::write was still used. Pretty trivial to review.
Brings us a step closer to #4774 

In the future most of the stuff probably should be migrated to the appframework and then use the ilogger interface. But until that day this seems like a good alternative.

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by rullzer** [comment]
Rebased. Lets see if Jenkins is happy now.

I can't remember anymore why I set this to 8.2... @DeepDiver1975 fine to add to 8.1?

**Comment by rullzer** [comment]
@DeepDiver1975 never mind... lets keep it on 8.2. :)

**Comment by MorrisJobke** [comment]
stable8.1 is created -> merge

**Pull request merged**
