### PR TITLE
Do not compare the value on Oracle

### LINKED ISSUE #18949: Oracle broken on master
I suppose caused by https://github.com/owncloud/core/pull/18799

```
15:48:07 exception 'Doctrine\DBAL\Driver\OCI8\OCI8Exception' with message 'ORA-00932: inconsistent datatypes: expected - got CLOB' in /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
15:48:07 Stack trace:
15:48:07 #0 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php(214): Doctrine\DBAL\Driver\OCI8\OCI8Exception::fromErrorInfo(Array)
15:48:07 #1 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\DBAL\Driver\OCI8\OCI8Statement->execute()
15:48:07 #2 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php(203): Doctrine\DBAL\Connection->executeUpdate('UPDATE "oc_appc...', Array, Array)
15:48:07 #3 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\DB\Connection->executeUpdate('UPDATE `*PREFIX...', Array, Array)
15:48:07 #4 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/querybuilder/querybuilder.php(121): Doctrine\DBAL\Query\QueryBuilder->execute()
15:48:07 #5 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/appconfig.php(183): OC\DB\QueryBuilder\QueryBuilder->execute()
15:48:07 #6 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/app/appmanager.php(170): OC\AppConfig->setValue('files_sharing', 'enabled', 'yes')
15:48:07 #7 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/app.php(312): OC\App\AppManager->enableApp('files_sharing')
15:48:07 #8 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/enable_all.php(13): OC_App::enable('files_sharing')
15:48:07 #9 /var/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/tests/enable_all.php(19): enableApp('files_sharing')
15:48:07 #10 {main}
15:48:07 
15:48:07 Next exception 'Doctrine\DBAL\Exception\DriverException' with message 'An exception occurred while executing 'UPDATE "oc_appconfig" SET "configvalue" = ? WHERE ("appid" = ?) AND ("configkey" = ?) AND ("configvalue" <> ?)' with params ["yes", "files_sharing", "enabled", "yes"]:
```
cc @DeepDiver1975

### PR DESCRIPTION
**Pull request by nickvergessen**
As per docs: http://docs.oracle.com/cd/E11882_01/server.112/e26088/conditions002.htm#i1033286

> Large objects (LOBs) are not supported in comparison conditions.

@MorrisJobke @LukasReschke @DeepDiver1975 

Fixes #18949

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
my docker has issues as of today .... can somebody please run autotest.sh oci ? THX

**Comment by DeepDiver1975** [comment]
4 more checks a missing ....

**Comment by nickvergessen** [comment]
Fixed the failing test

**Comment by Xenopathic** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
Let's move this in :+1: THX

**Pull request merged**
