### PR TITLE
Locking: Limit key length in Shared Storage #25376

### PR DESCRIPTION
**Pull request by guruz**
TODO After this is merged:
- [ ] Port tests and length check (not md5 code) to master

### CODE REVIEW

**Comment by PVince81** [comment]
Looks good. However it seems Oracle fails:
```
11:44:45 Time: 23.45 minutes, Memory: 229.50Mb
11:44:45 
11:44:45 There was 1 error:
11:44:45 
11:44:45 1) Test_Files_Sharing_Storage::testLongLock
11:44:45 Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("mimepart","mimetype","mtime","size","etag","storage_mtime","permissions","parent","path_hash","path","name","storage") SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM "oc_filecache" WHERE "storage" = ? AND "path_hash" = ? HAVING COUNT(*) = 0' with params ["424", "425", 1467992043, -1, "577fc7eb2612b", 1467992043, 31, "3558", "23265a8cde155b4cc87acde38fb22c29", "files\/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "1134", "1134", "23265a8cde155b4cc87acde38fb22c29"]:
11:44:45 
11:44:45 ORA-12899: value too large for column "AUTOTEST"."oc_filecache"."name" (actual: 255, maximum: 250)
11:44:45 
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:76
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:996
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:203
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/adapter.php:93
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:242
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/cache.php:258
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/scanner.php:226
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/scanner.php:189
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/scanner.php:267
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/updater.php:133
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/view.php:1039
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/view.php:251
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/sharedstorage.php:492
11:44:45 
11:44:45 Caused by
11:44:45 Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-12899: value too large for column "AUTOTEST"."oc_filecache"."name" (actual: 255, maximum: 250)
11:44:45 
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:33
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:214
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:989
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:203
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/adapter.php:93
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/db/connection.php:242
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/cache.php:258
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/scanner.php:226
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/scanner.php:189
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/scanner.php:267
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/cache/updater.php:133
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/view.php:1039
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/lib/private/files/view.php:251
11:44:45 /ssd/jenkins/workspace/core-ci-linux/database/oci/label/SLAVE/apps/files_sharing/tests/sharedstorage.php:492
```

Seems the max length of the name column is 250, not 255.

**Comment by guruz** [comment]
@PVince81 updated..

**Comment by PVince81** [comment]
Oracle hates you:
```
-> ORA-01033: ORACLE initialization or shutdown in progress Check environment: ORACLE_HOME=/usr/lib/oracle/12.1/client64 ORACLE_SID= LD_LIBRARY_PATH= NLS_LANG= tnsnames.ora is not readable
09:50:49 Kill the docke
```

**Comment by guruz** [comment]
What to do?
@butonic ?

**Comment by PVince81** [comment]
Nah, need to rebase again to kick CI for retesting. But since this branch is up to date with stable8.2... Maybe wait for another stable8.2 fix to be merged and then rebase.

Or change the commit slightly and force push...

Sucks, I know..

**Comment by guruz** [comment]
Changed commit to add my author name ;)

**Comment by PVince81** [comment]
Congrats on the passing tests.

Looks good :+1:

**Comment by PVince81** [comment]
Second review ? @owncloud/filesystem

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@guruz what about the backport? Can you take care? THX

**Comment by PVince81** [comment]
no backport needed, the code doesn't exist as is in past versions. And in next major versions the code changed in a way that works and doesn't require this fix. Removing label.

**Pull request merged**
