### PR TITLE
[3rdparty] Bump symfony/routing to 2.7.7

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/223

Only a version number increase. So CI _should_ be happy

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by rullzer** [comment]
Updated

**Comment by DeepDiver1975** [comment]
> Updated

thx

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
