### PR TITLE
Streamline CSRF and login check

### PR DESCRIPTION
**Pull request by LukasReschke**
Let's make this consistent with other pieces of the code to make it easier to audit.

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
I really love this:

```
curl http://localhost/master/index.php/apps/files/ajax/newfile.php -v
*   Trying ::1...
* connect to ::1 port 80 failed: Verbindungsaufbau abgelehnt
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /master/index.php/apps/files/ajax/newfile.php HTTP/1.1
> User-Agent: curl/7.40.0
> Host: localhost
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 28 Jan 2015 10:29:12 GMT
< Server: Apache/2.4.10 (Unix) OpenSSL/1.0.1l mod_fcgid/2.3.9 mod_wsgi/4.4.5 Python/3.4.2
< X-Powered-By: PHP/5.6.5
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
< X-Robots-Tag: none
< Set-Cookie: ocg3i9y10n3x=fd0c5j60f4p81ipjfrndeuum22; path=/master; HttpOnly
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host localhost left intact
```

Not a single line of output and a 200 status code \o/

**Comment by MorrisJobke** [comment]
With this patch applied it's better :+1:

```
$ curl http://localhost/master/index.php/apps/files/ajax/newfile.php  
{"data":{"message":"Authentication error","error":"authentication_error"},"status":"error"}
```

Creating new files still works.

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Also something for 8.0 I guess

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Also something for 8.0 I guess

not really critical - 8.1

**Pull request merged**
