### PR TITLE
Improve displaying errors in the extexternal storage settings ui

### LINKED ISSUE #38272: Handle external storage errors properly
### Steps to reproduce
1. Navigate to Settings->Admin->Storage
2. e.G Enter a SFTP Storage with invalid login data

### Expected behaviour
Show an error description
1. Display a tooltip on the red error square with the actual error message
2. Display notification if the user just entered data in the input-form, which results in a faulty storage error.

**Cons:
Sometimes there will be shown translated Errors, sometimes untranslated exceptions without proper user messages, depends on the type of error and also the storage driver**

Bildschirmfoto vom 2021-01-07 14-04-51
Unbenannt

### Actual behaviour
If I enter a faulty external storage config, I don't get any message or information about why the connection bind doesn't work properly.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes https://github.com/owncloud/core/issues/38272

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by mmattel** [comment]
@JanAckermann do you have any progress on that?
It would help me sorting out an issue which I linked in your referenced issue

**Comment by JanAckermann** [comment]
@mmattel this PR should work out of the box even if it is in a draft. PMs needs to decide if this gets in the master

**Comment by mmattel** [comment]
Thx, pls put that PR in normal mode and add eg @micbar and/or @phil-davis and/or @cdamken as reviewers.
Any possible untranslated text strings can be post fixed in a separate PR.
Would appreciate a quick review and merge 😃

**Comment by JanAckermann** [comment]
@mmattel Unfortantly there are still some issues with the error tool tips, they get overlayed by the navbar.
At least there should be some UI Tests I guess.

@hodyroff mentioned as well if we should display the errors to user/admin/both

@micbar and @pmaier1 also needs to decide if they want it in the product.

It's not easy to replace the error messages, sometimes these are desired HTTP Responses with translated Strings and sometimes these are 
Thrown Exceptions, even from some libs

**Pull request closed without merging**
