### PR TITLE
Re-use the share entry we have for the shared storage instead of searching for it every time

### LINKED ISSUE #18075: Recipient sees two shared folders with same content
### Steps:

1. Create three users "user1", "user2", "user3"
1. Put "user2" and "user3" in a group "group1"
1. Login as "user1"
1. Create a folder "Documents" with a file "users.txt"
1. Share "Documents" with group "group1"
1. Login as admin "root"
1. Create another folder "Documents" with a file "root.txt"
1. Share "Documents" with "group1"
1. Login as "user2" and check both folders

### Expected result
"user2" sees "Documents/users.txt" file and "Documents (2)/root.txt"

### Actual result
Both folders contain the same contents!
"user2" sees "Documents/root.txt" file and "Documents (2)/root.txt"

### Versions
ownCloud v8.1.0

Here is the share table:
```
MariaDB [owncloud]> select * from oc_share;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+----------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target    | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+----------------+-------------+------------+----------+------------+-------+-----------+
|  1 |          1 | group1     | user1     |   NULL | folder    | 23          | /23         |          23 | /Documents     |          31 | 1438772523 |        0 | NULL       | NULL  |         0 |
|  2 |          1 | group1     | root      |   NULL | folder    | 14          | /14         |          14 | /Documents     |          31 | 1438772531 |        0 | NULL       | NULL  |         0 |
|  3 |          2 | user2      | root      |      2 | folder    | 14          | /14         |          14 | /Documents (2) |          31 | 1438772531 |        0 | NULL       | NULL  |         0 |
|  4 |          2 | user3      | root      |      2 | folder    | 14          | /14         |          14 | /Documents (2) |          31 | 1438772531 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+----------------+-------------+------------+----------+------------+-------+-----------+
```

and the matching file entries:
```
MariaDB [owncloud]> select * from oc_filecache where fileid in (23,14);
+--------+---------+-----------------+----------------------------------+--------+-----------+----------+----------+---------+------------+---------------+-----------+------------------+---------------+-------------+
| fileid | storage | path            | path_hash                        | parent | name      | mimetype | mimepart | size    | mtime      | storage_mtime | encrypted | unencrypted_size | etag          | permissions |
+--------+---------+-----------------+----------------------------------+--------+-----------+----------+----------+---------+------------+---------------+-----------+------------------+---------------+-------------+
|     14 |       1 | files/Documents | 0ad78ba05b6961d92f7970b2b3922eca |      2 | Documents |        2 |        1 | 4347554 | 1438772643 |    1438772643 |         0 |                0 | 55c1eda3148ac |          31 |
|     23 |       3 | files/Documents | 0ad78ba05b6961d92f7970b2b3922eca |     17 | Documents |        2 |        1 |       0 | 1438772643 |    1438772519 |         0 |                0 | 55c1eda3293ec |          31 |
+--------+---------+-----------------+----------------------------------+--------+-----------+----------+----------+---------+------------+---------------+-----------+------------------+---------------+-------------+
```

Something seems wrong with the shared mounts, a possible mix up.

@icewind1991 @schiesbn

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #18075

Also saves some database queries by re-using data

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
also @schiesbn @rullzer

**Comment by schiesbn** [comment]
makes sense :+1:

**Comment by PVince81** [comment]
Works :+1:

**Comment by PVince81** [comment]
I suggest backport for 8.1.2 @karlitschek @DeepDiver1975

**Comment by karlitschek** [comment]
Please backport. :+1:  Thanks!

**Pull request merged**
