### PR TITLE
Mark some mail values at config report as sensitive

### PR DESCRIPTION
**Pull request by mmattel**
## Description
This PR marks three additional mail values as sensitive in configreport

```
"mail_smtpmode": "smtp",
"mail_from_address": "***REMOVED SENSITIVE VALUE***",
"mail_domain": "***REMOVED SENSITIVE VALUE***",
"mail_smtphost": "***REMOVED SENSITIVE VALUE***",
"mail_smtpport": "587"
```

## Related Issue
References: https://github.com/owncloud/core/issues/29912 ([Feature Request] config report: star out some mail settings)

## Motivation and Context
These settings are usually internal, for admin only and not for the public

## How Has This Been Tested?
run ``sudo -uwww-data ./occ config:list``

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
I'm fine with this 👍 

@cdamken @pako81 as this will affect the config report, would be good if you also confirm that you're ok with this

**Comment by pako81** [comment]
👍

**Comment by mmattel** [comment]
Travis failed at 15584.5:
image

**Comment by PVince81** [comment]
Never mind travis for this change...

**Comment by PVince81** [comment]
@mmattel please backport to stable10

**Pull request merged**
