### PR TITLE
[8.2] update icewind/smb to 1.0.8

### PR DESCRIPTION
**Pull request by icewind1991**

### CODE REVIEW

**Comment by icewind1991** [comment]
cc @Xenopathic @PVince81

**Comment by PVince81** [comment]
@karlitschek please confirm this backport (icewind/smb library with DFS fixes)

**Comment by karlitschek** [comment]
yep. obviously confirmed! :-)

**Comment by PVince81** [comment]
- [ ] TEST: unit tests against windows server
- [ ] TEST: unit tests against samba server

**Comment by PVince81** [comment]
Test running, I'm already seeing some errors :frowning: 
Will post results soon

**Comment by PVince81** [comment]
@icewind1991 not looking good, see below:

```
± % ./autotest-external.sh sqlite smb-windows
Using database oc_autotest
Setup environment for sqlite testing ...
cp: cannot stat '/srv/www/htdocs/owncloud/tests/autoconfig-sqlite.php': No such file or directory
Installing ....
ownCloud is not installed - only a limited number of commands are available
{"reqId":"gGPU+8gu5SQwlSsrCqvu","remoteAddr":"","app":"PHP","message":"file_put_contents(\/srv\/www\/htdocs\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/srv\/www\/htdocs\/owncloud\/lib\/private\/setup.php#456","level":3,"time":"2016-03-17T15:35:48+00:00"}
{"reqId":"gGPU+8gu5SQwlSsrCqvu","remoteAddr":"","app":"PHP","message":"file_put_contents(\/srv\/www\/htdocs\/owncloud\/data\/index.html): failed to open stream: Permission denied at \/srv\/www\/htdocs\/owncloud\/lib\/private\/setup.php#457","level":3,"time":"2016-03-17T15:35:48+00:00"}
creating sqlite db
ownCloud was successfully installed
{"reqId":"gGPU+8gu5SQwlSsrCqvu","remoteAddr":"","app":"PHP","message":"chmod(): Operation not permitted at \/srv\/www\/htdocs\/owncloud\/lib\/private\/log\/owncloud.php#92","level":3,"time":"2016-03-17T15:35:48+00:00"}
Testing with sqlite ...
Run only smb-windows ...
files_external enabled
No coverage
PHPUnit 5.2.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.17 with Xdebug 2.3.3
Configuration: /srv/www/htdocs/owncloud/tests/phpunit-autotest-external.xml

...............................................................  63 / 174 ( 36%)
............................................................... 126 / 174 ( 72%)
................................................                174 / 174 (100%)

Time: 2.33 seconds, Memory: 33.50Mb

OK (174 tests, 748 assertions)
skip: start-amazons3-ceph.sh
skip: start-ftp-morrisjobke.sh
skip: start-sftp-atmoz.sh
skip: start-smb-silvershell.sh
start: start-smb-windows.sh
name: smb-windows
No coverage
PHPUnit 5.2.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.17 with Xdebug 2.3.3
Configuration: /srv/www/htdocs/owncloud/tests/phpunit-autotest-external.xml

F..............E.........................F....................... 65 / 75 ( 86%)
.........F                                                        75 / 75 (100%)

Time: 8.64 minutes, Memory: 27.75Mb

There was 1 error:

1) Test\Files\Storage\SMB::testCopy with data set #7 ('/single ' quote.txt', '/tar'get.txt')
fwrite() expects parameter 1 to be resource, boolean given

/srv/www/htdocs/owncloud/lib/private/files/storage/common.php:185
/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:183
/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:203

--

There were 3 failures:

1) Test\Files\Storage\SMB::testRenameWithSpaces
Failed asserting that false is true.

/srv/www/htdocs/owncloud/apps/files_external/tests/backends/smb.php:61

2) Test\Files\Storage\SMB::testStat
Failed asserting that 1458229299 is equal to 1458229285 or is less than 1458229285.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:295

3) Test\Files\Storage\SMB::testIsShareable
Failed asserting that false is true.

/srv/www/htdocs/owncloud/tests/lib/files/storage/storage.php:599

FAILURES!
Tests: 75, Assertions: 259, Errors: 1, Failures: 3.
```

**Comment by PVince81** [comment]
Looks like there was a problem with the Windows Server VM (env issue in the lab it seems). Was getting timeouts, had to rerun several times.

Ran the tests again:
- [x] smb-silvershell
- [ ] smb-windows

**Comment by PVince81** [comment]
I can't get a clean single-pass run, there seem to be connection/timeout issues to the lab.
On each run, different tests fail so this means every one of them passed at least once.

Also after merging this it will be retested on CI, so let's move on for now.

:+1: 

Needs a second reviewer @SergioBertolinSG @jmaciasportela @DeepDiver1975

**Comment by PVince81** [comment]
I also did some tests with the sync client, moving files around, upload/download (also with chunking), all seems fine.

**Comment by PVince81** [comment]
@icewind1991 can you also send one for stable9 ?

**Comment by PVince81** [comment]
ah, here it is https://github.com/owncloud/core/pull/23359

**Comment by PVince81** [comment]
Second review ? @Xenopathic

**Comment by LukasReschke** [comment]
:+1:

**Comment by PVince81** [comment]
@owncloud/qa can you help test it ? (SMB storage, also with DFS)

**Pull request merged**
