### PR TITLE
translate contacts birthdays calendar

### PR DESCRIPTION
**Pull request by tcitworld**
Same than https://github.com/owncloud/core/pull/25887 but for contact birthdays calendar.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
This is not neccessary. The Name is translate on runtime. See calendar.php

**Comment by tcitworld** [comment]
Hmm, I'll check again but it didn't notice it translated, and therefore added this. Anyway, wouldn't this way be cleaner ?

**Comment by DeepDiver1975** [comment]
the displayname of the birthday calendar is translated here https://github.com/owncloud/core/blob/master/apps/dav/lib/CalDAV/Calendar.php#L38 - in this case the language of the request will be taken into account (if set) or the language choosen by the user at the time of the request.

**Comment by tcitworld** [comment]
Totally right.

**Pull request closed without merging**
