### PR TITLE
Proper repair step info during upgrade on cli

### PR DESCRIPTION
**Pull request by MorrisJobke**
I added this during the analysis of an upgrade failure.

I will have a look what can be ported to stable8 and master

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @karlitschek for backport approval

**Comment by karlitschek** [comment]
backort is fine with me. :+1:

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975

**Comment by MorrisJobke** [comment]
@DeepDiver1975 This can be ported straight to master and stable8 if wished.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Slightly different for master: #17088

**Comment by jvillafanez** [comment]
@MorrisJobke I'm not seeing the messages. The repairs are done, but messages aren't being shown

**Comment by MorrisJobke** [comment]
> @MorrisJobke I'm not seeing the messages. The repairs are done, but messages aren't being shown

You mean, that the engine was MyISAM and is after the upgrade InnoDB?

**Comment by jvillafanez** [comment]
No, I changed the charset and collation for a couple of tables to test this. There should be messages about changing the collation of the tables back to utf8, as far as I see in the code, but those messages aren't shown.

**Comment by jnfrmarks** [comment]
@MorrisJobke @jvillafanez 

Is this issue resolved?

**Comment by jvillafanez** [comment]
I guess not, at least in my environment. Anyway, I don't think it's a showstopper: the action (change back the charset to utf8) is executed, just the informative message isn't shown.

**Comment by jnfrmarks** [comment]
Did you/can you file an issue for the missing message?

**Comment by MorrisJobke** [comment]
Actual message is shown with the fix in #18385

**Pull request merged**
