### PR TITLE
Settings admin warning levels

### PR DESCRIPTION
**Pull request by rullzer**
Before we can merge #17919 we first should have different levels of warnings.

This adds 3 warnings levels to the setupchecks.
- INFO
- WARNING
- ERROR

I assigned the error levels to the messages. But feel free to correct me if I'm wrong.

Somebody work the CSS magic please (CC: @jancborchardt @MorrisJobke)

Eventually we should move to #17109 (also in the admin panel).

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Something like this:

bildschirmfoto von 2015-08-10 12-08-23

It's the usual red for error, 'orange` for warning and `black` for the info.

cc @jancborchardt

**Comment by jancborchardt** [comment]
I would say let’s for now only use 2 sections:
* red for errors/warnings (they should be sorted by severity)
* black for notices/info

(Orange and yellow on light is just really hard to read and one distinction is enough for now.)

**Comment by karlitschek** [comment]
I agree. red and black should be enough.

**Comment by MorrisJobke** [comment]
I fixed the CSS and now it looks good :+1:

**Comment by MorrisJobke** [comment]
bildschirmfoto von 2015-08-17 11-18-45

This involves all different kind of warnings (the first one is a PHP generated default security warning, second one is a JS one with state "error", third and fourth are JS "warnings" and the last one is a JS "info" message.

**Comment by jancborchardt** [comment]
:+1:

**Pull request merged**
