### PR TITLE
Properly quote file names in listFiles query for GDrive

### LINKED ISSUE #13189: Single quotes not escaped when fetching files from mounted volume
I'm having trouble syncing files on my local drive when filenames contains a single quote and are issued from my GoogleDrive mounted volume. 

Windows client crash : 
11:52     Gdrive/Documents/StBruno - Oenologie/2014 - Novembre - Alsace/CREMANT D'ALSACE.pdfownCloud       Error downloading https://cloud.uldosphere.org/remote.php/webdav/Gdrive/Documents/StBruno - Oenologie/2014 - Novembre - Alsace/CREMANT D'ALSACE.pdf - server replied: Internal Server Error

Apache access.log ispretty obvious : 

cloud.uldosphere.org:443 localhost - uld [09/Jan/2015:11:55:19 +0100] "GET /remote.php/webdav/Gdrive/Documents/StBruno%20-%20Oenologie/2014%20-%20Novembre%20-%20Alsace/CREMANT%20D'ALSACE.pdf HTTP/1.1" 500 860 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"

Filename CREMANT%20D'ALSACE.pdf is not escaped on the single quote.

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes #13189
Replaces https://github.com/owncloud/core/pull/15215

Todo:
- [x] BUG: with spaces

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by LukasReschke** [comment]
Verified by reporter in https://github.com/owncloud/core/issues/13189#issuecomment-88108444

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
