### PR TITLE
[stable8] Do not abort when meeting unfixable legacy storages

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/13513 to stable8

@DeepDiver1975 @MorrisJobke @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
@karlitschek Still awaiting confirmation: https://github.com/owncloud/core/pull/13513#issuecomment-81730144

**Comment by PVince81** [comment]
Had a quick local test and the warnings are shown.

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
