### PR TITLE
Fix file upload, conflict dialog, also in public link

### LINKED ISSUE #19922: upload on link shared folder failes with JS Error "TypeError: OCA.Files.App is undefined"
### Steps to reproduce
1. share a folder by link with upload permission
2. try to upload a file to this link share

### Expected behaviour
file should be uploaded

### Actual behaviour
file isn't uploaded
JS Error: TypeError: OCA.Files.App is undefined  -  file-upload.js:185:7

### Server configuration
Fresh VM Image: http://download.owncloud.org/community/production/vm/xUbuntu_14.04-owncloud-8.2.0-2.1-201510201921.vmx.zip

### PR DESCRIPTION
**Pull request by PVince81**
- Use "FileList" instead of "OCA.Files.App.fileList" that doesn't exist in public
  link page.
- Fix public link upload by properly adding the form data using a new
  utility function "addFormData". That one is needed because IE8 upload
  and regular upload use a different format...

Fixes https://github.com/owncloud/core/issues/19922

Please note that IE8 is using a different code path / format for formData that's why it needs to be tested separately.
#### Files app
- [x] TEST: upload
- [x] TEST: upload + overwrite when existing file is visible in list (client side conflict)
- [x] TEST: upload + overwrite when existing file is NOT visible in list (server side conflict)
- [x] TEST: IE8: upload + overwrite when existing file is visible in list (client side conflict)
- [x] TEST: IE8: upload + overwrite when existing file is NOT visible in list (server side conflict)
#### Public link page
- [x] TEST: upload
- [x] TEST: upload + overwrite when existing file is visible in list (client side conflict)
- [x] TEST: upload + overwrite when existing file is NOT visible in list (server side conflict)
- [x] TEST: IE8: upload + overwrite when existing file is visible in list (client side conflict)
- [x] TEST: IE8: upload + overwrite when existing file is NOT visible in list (server side conflict)

Please review @nickvergessen @MorrisJobke @icewind1991 @butonic 

@karlitschek we should backport this to fix the regression on 8.2

### CODE REVIEW

**Comment by nickvergessen** [comment]
Works :+1: 

Only a little glitch (but that also happens on master and in the normal file list, so I will create a new ticket).

If you have a lot of files

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19956

Still needs a second reviewer

**Comment by icewind1991** [comment]
:+1: code looks good, tested in chrome

**Comment by LukasReschke** [comment]
@DeepDiver1975 Merge please.

**Comment by ansemjo** [comment]
applied #19956 as a manual patch to owncloud stable 8.2 on Debian and completely fixed the issue for me (:

**Pull request merged**
