### PR TITLE
remove insane debug-log from OC_Image

### PR DESCRIPTION
**Pull request by georgehrke**
please review @DeepDiver1975 @oparoz

### CODE REVIEW

**Comment by oparoz** [comment]
Works for me :+1:

**Comment by karlitschek** [comment]
good :+1:

**Comment by DeepDiver1975** [comment]
thx - as discussed :+1:

**Comment by DeepDiver1975** [comment]
@karlitschek backport? Was reported as issue on oc7

**Comment by karlitschek** [comment]
yes. would be good

**Comment by DeepDiver1975** [comment]
summoning backport master @MorrisJobke - THX

**Comment by MorrisJobke** [comment]
stable7 2d2e024

**Comment by MorrisJobke** [comment]
stable7 2d2e024

**Pull request merged**
