### PR TITLE
Ensure that the basic auth module is the last module in the list

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
We need to make sure that the BasicAuthModule is the last one to be checked.

Shall fix https://github.com/owncloud/core/pull/30364#issuecomment-363750684

https://github.com/owncloud/core/pull/30364#issuecomment-363750684

## How Has This Been Tested?
- needs manual test with oauth @SamuAlfageme  THX

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
Of course, because the "auth-modules" would run in the middle 👍

**Comment by PVince81** [comment]
selenium failures https://drone.owncloud.com/owncloud/core/3570/97, restarting...

**Comment by SamuAlfageme** [comment]
Will start https://github.com/owncloud/QA/issues/529#issuecomment-363762536 from scratch targetting this patch.

**Comment by SamuAlfageme** [comment]
@DeepDiver1975 I think the "Login failed" issue is still reproducing when applying this one over 10.0.7 RC1

### Steps:

#### Prepare the environment:

```bash
# Get 10.0.7 RC1 tarball
wget -qO- https://download.owncloud.org/community/testing/owncloud-10.0.7RC1.tar.bz2 | tar xvz
# Start a test container w/ oauth2 and inject the tarball:
OWNCLOUD_APPS_INSTALL=oauth2 OWNCLOUD_APPS_ENABLE=oauth2 \
docker run -p 443:443 -v $(pwd)/owncloud:/var/www/owncloud --name owncloud owncloud/server
# Get this patch: 
docker exec owncloud wget https://github.com/owncloud/core/pull/30398.patch
# Install git & apply the patch
docker exec owncloud bash -c 'apt-get update && apt-get install -y git && git apply -- 30398.patch'
``` 

#### Reproduce the issue:

1. Login as admin:admin
2. Create an application password in `https://localhost/settings/personal?sectionid=security`
3. Use it to (successfully) login on the client 
4. Observe last container logs: `docker logs owncloud | grep 'Login failed'`

However, while still an issue, I realise it's pretty minor: instead one `'Login failed'` entry per client request; there's just one for the `/index.php/apps/oauth2/api/v1/token` request.

**Comment by PVince81** [comment]
codecov result is bullshit. merging

**Comment by PVince81** [comment]
please backport to hotfix-10.0.7 and stable10

**Comment by PVince81** [comment]
as discussed, https://github.com/owncloud/core/pull/30365 could be the right solution

**Pull request merged**
