### PR TITLE
Cleanup remote

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
remove query and|or anchor part in remote url

## Motivation and Context
Better remote sharing

## Related Issue

- Fixes <issue_link>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by VicDeo** [comment]
@micbar tests added

**Comment by micbar** [comment]
@VicDeo I am fine with the code now.
Please add a changelog item.

**Comment by VicDeo** [comment]
@micbar changelog added

**Review by micbar — APPROVED** [review]

**Comment by VicDeo** [comment]
After adding the changelog the build was running for 13 hours. Restarted.

**Pull request merged**
