### PR TITLE
[9.0] Better callForAllUsers memory usage

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #24327 
Approval https://github.com/owncloud/core/pull/24327#issuecomment-216195213

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
9.0.3 is fine I guess @butonic

**Comment by butonic** [comment]
9.0.3 is fine.

**Comment by butonic** [comment]
hm ... there are other big instances that may want to upgrade to 9.0.2. We will have to recommend to postpone their upgrade to 9.0.3. cc @cmonteroluque

**Comment by butonic** [comment]
in any case, this PR alone does not remove / replace all array caches that can cause the OOM exception during an upgrade (leaving the instance in a broken state because the internal dav routes will not have been upgraded) so 9.0.3 makes more sense.

**Comment by rullzer** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
