### PR TITLE
[stable9] Fix dropbox storage to not store the whole file in memory

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/23272

Please review @LukasReschke @icewind1991 @Xenopathic

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by PVince81** [comment]
Second review please @MorrisJobke @Xenopathic @LukasReschke

**Comment by PVince81** [comment]
@owncloud/qa can you help testing ?

**Comment by SergioBertolinSG** [comment]
Not working fine :-1: , download spinner gets stuck with big files and it doesn't progress.

**Comment by PVince81** [comment]
I guess you probably used a huge file and it's taking too much time to be downloaded to temp.

Just now I remembered that we have this fix for FTP storage streaming https://github.com/owncloud/core/issues/22286, the `RetryWrapper`. It's probably a better idea to use streaming for Dropbox too now that it can work properly.

I'll submit separate PRs.

**Comment by PVince81** [comment]
Closing in favor of stream download which works way better: https://github.com/owncloud/core/pull/23516 (with RetryWrapper to make it work for encryption too)

**Pull request closed without merging**
