### PR TITLE
Localize numbers in JS using toLocaleString()

### PR DESCRIPTION
**Pull request by PVince81**
Fix for https://github.com/owncloud/core/issues/20674

Might not work in all browsers.
- [x] Chromium
- [x] Firefox
- [ ] Safari
- [ ] IE8
- [ ] IE9
- [ ] IE10
- [ ] IE11
- [x] Edge

I set this to "To review" but I'm not sure this is the right approach.

Let's find out first which browsers support this...

### CODE REVIEW

**Comment by tomneedham** [comment]
Get this when I try with formal German language set:

screen shot 2015-11-25 at 15 05 00

Also noticed this behaviour when testing with English (note when I try with size=1000):
screen shot 2015-11-25 at 15 06 56

**Comment by PVince81** [comment]
Hmmm, I tried to reproduce this locally and somehow it didn't want to throw the exception.

We might need to cut the underscore and only keep the left part.
And/or catch the exception.

**Comment by tomneedham** [comment]
I only get the exception with the Formal version. On Safari no exception but always get a very long number:
screen shot 2015-11-25 at 15 28 55

**Comment by tomneedham** [comment]
Rebased.

Fixed the formatting of the local string, was 'de_DE' but we need 'de-DE' as in http://tools.ietf.org/html/rfc5646#section-2.1.1.

Also added handling to catch the exception when this function is not supported. Works in Chrome / Firefox. No support for Safari at the moment.

**Comment by tomneedham** [comment]
Doesn't work with IE8.

**Comment by tomneedham** [comment]
Does work in Edge :+1:

**Comment by tomneedham** [comment]
So it seems like if we actually want to solve this issue in a cross-browser way we need something like numerals.js. Supported languages are here: https://github.com/adamwdraper/Numeral-js/tree/master/languages. Library file size is: 48kB uncompressed, 21kB minified. License is open, just have to include the license file https://github.com/adamwdraper/Numeral-js/blob/master/LICENSE.

I also checked out humanize.js from HubSpot but it seems we would have to implement the languages ourselves whereas we can add languages upstream with Numerals.

Who makes the call to include this? @PVince81

**Comment by PVince81** [comment]
I think numerals.js would be nice if it bundles the logic and locales.

@DeepDiver1975 do you agree to include this new library to be able to localize numbers on the JS side ? See https://github.com/owncloud/core/pull/20689#issuecomment-159871033

**Comment by MorrisJobke** [comment]
Doesn't work in safari here:

bildschirmfoto 2015-12-01 um 14 32 31

:( I also increased the oc version to bust all caches. No change.

**Comment by PVince81** [comment]
@MorrisJobke yes, Safari doesn't support this API, see https://github.com/owncloud/core/pull/20689#issuecomment-159641403

We need a better solution. Switching to "To develop".

**Comment by PVince81** [comment]
Since this solution didn't work cross-browser, I'll close it.

We should look into a library that does this correctly, like momentjs but for numbers.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 do you agree to include this new library to be able to localize numbers on the JS side ? See #20689 (comment)

better late then never :wink: - yes!

**Pull request closed without merging**
