### PR TITLE
[stable10] Rename "remote" to "federated" in share list

### PR DESCRIPTION
**Pull request by PVince81**

### CODE REVIEW

**Comment by PVince81** [comment]
needs forward port to master

**Review by davitol — APPROVED** [review]
Tested and works.

**Comment by PVince81** [comment]
I've adjusted the end to end tests

**Comment by PVince81** [comment]
that codecov report doesn't sound right, ignoring...

**Comment by PVince81** [comment]
Forward port: https://github.com/owncloud/core/pull/30220

**Pull request merged**
