### PR TITLE
[stable9.1] Skip FailedStorage in background scan

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/26529 to stable9.1

@jvillafanez

### CODE REVIEW

**Comment by PVince81** [comment]
@cdamken can you test it on your cloud ?

**Comment by PVince81** [comment]
Interestingly I can't reproduce this on stable9.1. when checking with a debugger it seems that https://github.com/owncloud/core/pull/26600 already fixes it through the `ISharedStorage` check.

Still, this PR would help cover more potential cases.

**Comment by cdamken** [comment]
Trying to apply the patch:

```
root@snoopy:/var/www/owncloud# patch -p 1 < /root/jail.patch
patching file lib/private/Files/Utils/Scanner.php
Hunk #1 succeeded at 120 with fuzz 2 (offset -1 lines).
Hunk #2 FAILED at 170.
1 out of 2 hunks FAILED -- saving rejects to file lib/private/Files/Utils/Scanner.php.rej
root@snoopy:/var/www/owncloud# more lib/private/Files/Utils/Scanner.php.rej
--- lib/private/Files/Utils/Scanner.php
+++ lib/private/Files/Utils/Scanner.php
@@ -170,6 +176,12 @@ public function scan($dir = '') {
                        if (is_null($storage)) {
                                continue;
                        }
+
+                       // don't bother scanning failed storages (shortcut for same result)
+                       if ($storage->instanceOfStorage('OC\Files\Storage\FailedStorage')) {
+                               continue;
+                       }
+
                        // if the home storage isn't writable then the scanner is run as the wrong user
                        if ($storage->instanceOfStorage('\OC\Files\Storage\Home') and
                                (!$storage->isCreatable('') or !$storage->isCreatable('files'))

```

**Comment by PVince81** [comment]
@cdamken you might need to update to 9.1.3 first.

**Comment by cdamken** [comment]
> @cdamken you might need to update to 9.1.3 first.

I updated to 9.1.3 and the error does not appear anymore, probably I don't need to apply the patch

**Comment by jvillafanez** [comment]
Makes sense 👍

**Pull request merged**
