### PR TITLE
config.sample.php: instanceid documentation

### PR DESCRIPTION
**Pull request by guruz**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@guruz can you please add some background here please?

**Comment by guruz** [comment]
@DeepDiver1975 I'm just forwarding the code comment from https://github.com/owncloud/core/commit/332756197b3f073295aef9fd2342f288109ad2e3#diff-ec8c121d705ff47eacbfdd23f36a9f6cR1141 to the sample config.

**Comment by DeepDiver1975** [comment]
So we can close this - right?

**Comment by kdslkdsaldsal** [comment]
Not sure about the tests but i think the comment in the config.sample.php makes sense.

**Comment by guruz** [comment]
@DeepDiver1975 Close? you mean merge?

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
@DeepDiver1975 you added "To release" label. Does that mean that this should be backported "to Release" in 10.0.* series?

**Pull request merged**
