### PR TITLE
Update guzzlehttp to 5.3.1

### PR DESCRIPTION
**Pull request by PVince81**
Core PR for https://github.com/owncloud/3rdparty/pull/281

Let's see what CI says

### CODE REVIEW

**Comment by PVince81** [comment]
@DeepDiver1975 please approve once CI passes.

I also added it to your "kill submodule" PR for later: https://github.com/owncloud/core/pull/25513

**Comment by butonic** [comment]
👍

**Comment by DeepDiver1975** [comment]
green 

bildschirmfoto von 2016-08-22 15-39-30

**Comment by DeepDiver1975** [comment]
I'm updating the submodule ...

**Comment by PVince81** [comment]
I did update the submodule, not sure what happenned.

/me grab moar :coffee:

**Comment by DeepDiver1975** [comment]
backport? @PVince81

**Comment by PVince81** [comment]
@DeepDiver1975 not needed, see https://github.com/owncloud/3rdparty/blob/stable9.1/patches.txt#L5

unless you want it clean

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 not needed, see https://github.com/owncloud/3rdparty/blob/stable9.1/patches.txt#L5
> 
> unless you want it clean

that's nasty .....

**Pull request merged**
