### PR TITLE
Fix for #23066

### PR DESCRIPTION
**Pull request by TDannhauer**
Fix for #23066

### CODE REVIEW

**Comment by TDannhauer** [comment]
@PVince81 That looks better :) Thanks for your guidance so far!

**Comment by TDannhauer** [comment]
Hm, still failing the same tests as in my first PR attempts... any thoughts?

**Comment by TDannhauer** [comment]
ups, it seems the line edings are screwed up

**Comment by PVince81** [comment]
If you're editing on Windows, you need to set the newlines to unix mode.
Also, you're likely going to have a bad time :frowning: 

Regarding the unit tests, you might need to adjust the tests to match your changes.

**Comment by TDannhauer** [comment]
Hehe jepp, Windows dev is usually painful, but I'm bound to it by my job, so I'll do my best. 

I'll look at the tests as soon as I can, but this might take some time/days.

**Comment by TDannhauer** [comment]
I closed this PR and created a fixed one with corrected line endings: #24689

**Pull request closed without merging**
