### PR TITLE
some encryption fixes

### PR DESCRIPTION
**Pull request by schiessle**
Some changes which should fix (most) litmus tests.
- delete all file keys doesn't need the encryption module as parameter
- implement rmdir
- getFileKeyDir should also work for part files and complete directories

@DeepDiver1975 please test this. 1-2 litmus tests still fail on my system randomly ( :fearful: ) but also without encryption. Let's hope that something is wrong on my setup.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@schiesbn please post your litmus output - thx

**Comment by schiesbn** [comment]
As I said on every run different tests failed here with different errors. Strange enough now that I try to reproduce it every test pass with and without encryption... But this is one of the failing tests I still have in my terminal (with encryption), didn't change anything since it failed (sadly I don't have any failure output of a test without encryption):

````
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... WARNING: server does not claim Class 2 compliance
    ...................... pass (with 1 warning)
 3. put_get............... pass
 4. put_get_utf8_segment.. pass
 5. put_no_parent......... pass
 6. mkcol_over_plain...... pass
 7. delete................ pass
 8. delete_null........... pass
 9. delete_fragment....... pass
10. mkcol................. pass
11. mkcol_again........... pass
12. delete_coll........... pass
13. mkcol_no_parent....... pass
14. mkcol_with_body....... pass
15. finish................ pass
<- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `copymove':
 0. init.................. pass
 1. begin................. pass
 2. copy_init............. pass
 3. copy_simple........... pass
 4. copy_overwrite........ pass
 5. copy_nodestcoll....... pass
 6. copy_cleanup.......... pass
 7. copy_coll............. WARNING: Could not clean up cdest
    ...................... pass (with 1 warning)
 8. copy_shallow.......... pass
 9. move.................. pass
10. move_coll............. FAIL (DELETE from copied collection failed for `/master/remote.php/webdav/litmus/mvdest/foo.2': 404 Not Found)
11. move_cleanup.......... pass
12. finish................ pass
<- summary for `copymove': of 13 tests run: 12 passed, 1 failed. 92.3%
-> 1 warning was issued.
````

**Comment by DeepDiver1975** [comment]
looks far better - I see one message in the log:

````
{"reqId":"ghdNqoRYPeo79TKsScfb","remoteAddr":"::1","app":"PHP","message":"Undefined index: encrypted at \/home\/deepdiver\/Development\/ownCloud\/master\/lib\/private\/files\/storage\/wrapper\/encryption.php#286","level":3,"time":"2015-05-13T15:15:30+00:00"}

**Comment by DeepDiver1975** [comment]
@schiesbn mind taking care? I'll fire up the sync tests

**Comment by DeepDiver1975** [comment]
there is still some issue left on t1.pl

````
No database Transaction to commit
===============> http://localhost/oc/master/remote.php/webdav/t1-20150513171722-50/
Propfind failed: Server response: Server closed connection without sending any data back
#### localpath = t1-20150513171722-50/
Use of uninitialized value $error[0] in join or string at /usr/share/perl/5.20/Carp.pm line 423.
Filename local, but not remote: t1-20150513171722-50/remoteToLocal1 at ownCloud/Test.pm line 794.
	ownCloud::Test::assert(undef, "Filename local, but not remote: t1-20150513171722-50/remoteTo"...) called at ownCloud/Test.pm line 459
	ownCloud::Test::traverse("", 0, undef) called at ownCloud/Test.pm line 474
	ownCloud::Test::assertLocalAndRemoteDir("", 0) called at t1.pl line 184

**Comment by schiesbn** [comment]
undefined index error should be fixed... Where can I find the t1.pl script?

**Comment by schiesbn** [comment]
Damn, now some litmus tests fail again:

````
 ./litmus http://localhost/master/remote.php/webdav litmus litmus
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... WARNING: server does not claim Class 2 compliance
    ...................... pass (with 1 warning)
 3. put_get............... pass
 4. put_get_utf8_segment.. pass
 5. put_no_parent......... pass
 6. mkcol_over_plain...... pass
 7. delete................ pass
 8. delete_null........... pass
 9. delete_fragment....... pass
10. mkcol................. pass
11. mkcol_again........... pass
12. delete_coll........... pass
13. mkcol_no_parent....... pass
14. mkcol_with_body....... pass
15. finish................ pass
<- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `copymove':
 0. init.................. pass
 1. begin................. pass
 2. copy_init............. pass
 3. copy_simple........... pass
 4. copy_overwrite........ pass
 5. copy_nodestcoll....... pass
 6. copy_cleanup.......... pass
 7. copy_coll............. FAIL (COPY destination coll missing /master/remote.php/webdav/litmus/ccdest/foo.3? 404 Not Found)
 8. copy_shallow.......... pass
 9. move.................. pass
10. move_coll............. FAIL (DELETE from copied collection failed for `/master/remote.php/webdav/litmus/mvdest/foo.6': 404 Not Found)
11. move_cleanup.......... pass
12. finish................ pass
<- summary for `copymove': of 13 tests run: 11 passed, 2 failed. 84.6%
See debug.log for network/debug traces.
````

I don't get it, the only change is this two if statements: https://github.com/owncloud/core/pull/16323/files#diff-a36b9c0307e0126dd50baa38fb4bb74aR287

**Comment by DeepDiver1975** [comment]
t1.pl is living in the client repo csync/tests/owncloud/

I observe these failing tests on copy and move as well - sometimes ...

**Comment by schiesbn** [comment]
Hah, and now I have a similar failure if encryption is disabled (on master, so the last commit here can't affect it!):

````
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... WARNING: server does not claim Class 2 compliance
    ...................... pass (with 1 warning)
 3. put_get............... pass
 4. put_get_utf8_segment.. pass
 5. put_no_parent......... pass
 6. mkcol_over_plain...... pass
 7. delete................ pass
 8. delete_null........... pass
 9. delete_fragment....... pass
10. mkcol................. pass
11. mkcol_again........... pass
12. delete_coll........... pass
13. mkcol_no_parent....... pass
14. mkcol_with_body....... pass
15. finish................ pass
<- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `copymove':
 0. init.................. pass
 1. begin................. pass
 2. copy_init............. pass
 3. copy_simple........... pass
 4. copy_overwrite........ pass
 5. copy_nodestcoll....... pass
 6. copy_cleanup.......... pass
 7. copy_coll............. FAIL (COPY destination coll missing /s2s/remote.php/webdav/litmus/ccdest/foo.6? 404 Not Found)
 8. copy_shallow.......... pass
 9. move.................. pass
10. move_coll............. pass
11. move_cleanup.......... pass
12. finish................ pass
<- summary for `copymove': of 13 tests run: 12 passed, 1 failed. 92.3%

````

**Comment by DeepDiver1975** [comment]
I'm off until friday now .... so sick of looking at these los files and test results. Take care.

**Comment by DeepDiver1975** [comment]
litmus and t1.pl run okay now locally :+1:

**Pull request merged**
