### PR TITLE
Fix user preference key definition for insertIfNotExists()

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 Should fix the failing oracle test

@MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Nice - I was trying to make the query work on that clob thingy ...

**Comment by nickvergessen** [comment]
> I was trying to make the query work on that clob thingy ...

feel free to, then we can remove the note I just added ;)

**Comment by DeepDiver1975** [comment]
> Nice - I was trying to make the query work on that clob thingy ...

it was a local fix in the allconfig.php to build a query which properly compares on the clob
 but if we compare wrong keys anyhow ....

**Comment by nickvergessen** [comment]
Pushed the fix to the stable8 backport #14914 aswell

**Comment by DeepDiver1975** [comment]
tested :+1:

**Comment by PVince81** [comment]
Makes sense :+1:

**Pull request merged**
