### PR TITLE
fix setting mountpoint and auth backend of external storages

### LINKED ISSUE #21083: Renaming personal mount deletes it / doesn't work
### Steps to reproduce

1. Enable SFTP mount for users
1. Go to the personal page
1. Mount an SFTP storage under "/sftp"
1. Go to the files app and navigate into it, works
1. In the web UI, rename "sftp" to "sftp_renamed"
1. Refresh the page => not renamed
1. Go to the personal page
1. Rename "sftp" to "sftpren"
1. Refresh the page => mount point is gone ?!!

### Expected result
Ability to rename mount points in the files app and also personal page.

### Actual result
Renaming mount point in the files app doesn't work, mount point is not renamed.
Renaming it in the personal page kills it, the config disappears.

### Versions
ownCloud 9.0 pre-alpha git master bec34f12757517a784f6e35fc6b7294ab1673c59

@icewind1991 @Xenopathic

### PR DESCRIPTION
**Pull request by icewind1991**
Now with tests

Fixes #21083

cc @PVince81

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1: but the unit tests for external storages seems to be broken.

**Comment by icewind1991** [comment]
Fixed the tests

**Comment by PVince81** [comment]
- [x] TEST: renaming in web UI
- [ ] TEST: renaming in personal page :no_entry_sign: 

Renaming in personal page still kills the mount point entry.

**Comment by icewind1991** [comment]
> Renaming in personal page still kills the mount point entry.

Fixed

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by PVince81** [comment]
Rebased for CI

**Comment by PVince81** [comment]
@icewind1991 now renaming the SFTP mount in the files app kills the entry, it disappears from the list in the personal page.

**Comment by icewind1991** [comment]
> now renaming the SFTP mount in the files app kills the entry, it disappears from the list in the personal page.

Renaming from the files app works fine for me

**Comment by PVince81** [comment]
Looks like I missed a huge `git fetch`... will retest

**Comment by PVince81** [comment]
Yup, works now :+1:

**Pull request merged**
