### PR TITLE
Fix for 40872

### LINKED ISSUE #40872: Add max-height to sharing dialog
Add max-width to sharing dialog

### Expected behaviour
The dialog should give me a quick overview of the groups and people I can share with. 
It would be great to extend that to approx 6 items.

### Actual behaviour
The sharing dialog shows 2,5 items

image

In some situations, there may be multiple options - I have to scroll in order to see them.

### PR DESCRIPTION
**Pull request by steelcuts**
Changed the share dropdown. It will expand to the page bottom now if there are more entries.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/40872

## How Has This Been Tested?

- Local instance
- presales.owncloud.com
## Screenshots (if appropriate):

Bildschirm­foto 2023-07-11 um 16 39 19
Bildschirm­foto 2023-07-11 um 16 39 01

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by hurradieweltgehtunter** [comment]
Thank you for your work and the PR! One question, though: what happens if the dropdowns' height exceeds the screen height to the bottom?
I haven't tested it, but it looks like, that the list will exceed the screen height if it's long enough and some elements will be hidden. Have you tested that?

**Comment by phil-davis** [comment]
@steelcuts please click the button to "sign" the CLA

**Comment by steelcuts** [comment]
> What happens if the dropdowns' height exceeds the screen height to the bottom? 

Thanks and good question:
You can see in the second screenshot that it already has reached its maximum height, there is a scrollbar to the right of it. 
The combination of y-overflow (scroll if it can't expand further) and bottom margin ( always leave 15px space to the bottom ) let the dropdown behave this way.

> please click the button to "sign" the CLA

Thanks for letting me know

**Comment by hurradieweltgehtunter** [comment]
Please test the following:
- Have the list as long as in your second screenshot
- Reduce the window height so the lists bottom is lower than the window bottom, for example reduce the window height until the bottom is at "admin-matthias"

I'm pretty sure that the user list will be cut off. 
I hope the explanation is understandable. it's bit tricky since I cannot test it locally rn :)

**Comment by steelcuts** [comment]
I just retested and it didn't work at all. I didn't clear my cache and still had following css loaded:
```
max-height: -moz-available; 
max-height: -webkit-fill-available; 
max-height: fill-available;
```
I think that's what you where trying to say? :D

Now it behaves like i had intended:
Bildschirm­foto 2023-07-12 um 12 15 56
Bildschirm­foto 2023-07-12 um 12 16 13

**Comment by ChrisEdS** [comment]
Please only use common resolutions. Seems like this resolution is way to small - I see other misbehaviour here like

image
 
 and
 
image
 
 actually I think this is another bug! Should the `Archivierte Dateien` part be in the section of `Gelöschte Dateien` and `Papierkorb`?

**Comment by steelcuts** [comment]
You can test it here:
https://branding-aalvarez.owncloud.works/
user: demo_user
password: demo_password

**Comment by pako81** [comment]
What is the status here? @ChrisEdS is this needed for the 10.13 release?

**Comment by ChrisEdS** [comment]
I would love to have it in the release. @tbsbdr can you have a look?
https://github.com/owncloud/core/pull/40873#issuecomment-1632348302

**Review by hurradieweltgehtunter — APPROVED** [review]

**Pull request merged**
