### PR TITLE
add icons for disabled checkbox, radio button, error and colored checkmark

### PR DESCRIPTION
**Pull request by jancborchardt**
As requested by @Henni :)

Please review @owncloud/designers – I also took the chance to compress the action icons as some of them were not really compressed for whatever reason.

### CODE REVIEW

**Comment by nickvergessen** [comment]
disabled && checked checkbox is missing?

**Comment by jancborchardt** [comment]
@nickvergessen no, look at the files. checkbox-disabled.svg & png are here, and checkbox-checked is already in master.

**Comment by nickvergessen** [comment]
I mean checkbox-checked-disabled.svg :wink: which exists in the browser:
personlich_-_owncloud_-_2015-11-16_16 32 55

**Comment by jancborchardt** [comment]
@nickvergessen ah, good point. Will add that. :)

**Comment by jancborchardt** [comment]
@nickvergessen added.

Please review again @Henni @owncloud/designers

**Comment by jancborchardt** [comment]
Homies? @Henni @owncloud/designers please review this very simple icon change. :)

**Comment by MorrisJobke** [comment]
:+1: from my side

**Comment by nickvergessen** [comment]
the disabled checkbox icons are not used automatically, would be nice to add that CSS to core as well?

**Comment by MorrisJobke** [comment]
> the disabled checkbox icons are not used automatically, would be nice to add that CSS to core as well?

I would like to have this in a separate PR

**Comment by jancborchardt** [comment]
Yes, separate PR for the functionality for sure. Initially this was just for the icons – please review just this @nickvergessen ;)

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
> Yes, separate PR for the functionality for sure. Initially this was just for the icons – please review just this @nickvergessen ;)

@jancborchardt Can you create the PR for the actual use of this icon? :)

**Comment by jancborchardt** [comment]
@Henni can you do that? You requested the icons and know the code best. ;)

**Comment by nickvergessen** [comment]
Patch at https://github.com/owncloud/core/issues/20991

**Pull request merged**
