### PR TITLE
[stable9.1] Create new birthday calendar without VTODO and give order 100

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/core/pull/28011 to stable9.1.

Tested in UI, installing owncloud + calendar, checking created system calendar

### CODE REVIEW

**Comment by tomneedham** [comment]
Since we don't have migrations in <OC10, this doesn't fix previous created calendars. Repair step @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
> Since we don't have migrations in <OC10, this doesn't fix previous created calendars. Repair step

hmmmm .... if necessary yes .... but we want people to move to oc10 .... ;-)

**Comment by tomneedham** [comment]
> Can we merge this ? If a repair step is needed then separately...

this fixes the problem for new installs, doesn't fix old installs where this is already broken => we should probably add the repair step -> separately is fine

**Comment by PVince81** [comment]
still no review and still "2 - Developing". Moving to "planned" for the next release

**Comment by tomneedham** [comment]
Rebased to kick jenkins timeout

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
