### PR TITLE
fix personal page layout for LDAP users, fix #22272

### LINKED ISSUE #22272: Personal page elements are not correctly distibuted for LDAP users.
### Observed behaviour

There is a lack of order in the LDAP users personal page:

screen shot 2016-02-10 at 13 25 25

While regular users have elements correctly ordered:

screen shot 2016-02-10 at 13 25 13

Observed in current master 9.0.10 pre alpha using Chrome.

### PR DESCRIPTION
**Pull request by jancborchardt**
Fixes the remaining issues from #22272, please review @SergioBertolinSG @owncloud/designers @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works better than before :+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1: should go into 9.0

**Comment by jancborchardt** [comment]
@DeepDiver1975 merge please

**Pull request merged**
