### PR TITLE
refactor-webUISharingContext to support password_policy

### PR DESCRIPTION
**Pull request by paurakhsharma**
## Description
webUISharingContext refactor to support password_policy

## Related Issue
https://github.com/owncloud/password_policy/issues/126

## How Has This Been Tested?
Locally

## Types of changes
- [x] Tests

## Checklist:
- [x] Acceptance tests added

### CODE REVIEW

**Review by individual-it — CHANGES_REQUESTED** [review]

**Comment by paurakhsharma** [comment]
@individual-it I have made some changes, please review it.

**Review by individual-it — APPROVED** [review]
if CI passes, it must be good

**Comment by paurakhsharma** [comment]
Backport on #32757

**Comment by individual-it** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
