### PR TITLE
Check the syntax on travis

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by nickvergessen** [comment]
```
PHP Fatal error:  Can't use method return value in write context in ./apps/files_external/lib/google.php on line 268

Fatal error: Can't use method return value in write context in ./apps/files_external/lib/google.php on line 268

Errors parsing ./apps/files_external/lib/google.php
```
Test still passes thou, seems like the exit code is wrong...

**Comment by LukasReschke** [comment]
Got this working now using the parallel PHP linter. Works fine on Travis. I'd propose to merge this so that all future 

# Error



# Success

**Comment by DeepDiver1975** [comment]
Nice :+1:

**Comment by DeepDiver1975** [comment]
@karlitschek php syntax check is also of importance on our stable branches - I suggest backport - THX

**Comment by karlitschek** [comment]
absolutely. please backport

**Comment by LukasReschke** [comment]
stable8: https://github.com/owncloud/core/pull/23310
stable8.1: https://github.com/owncloud/core/pull/23311
stable8.2: https://github.com/owncloud/core/pull/23312
stable9: https://github.com/owncloud/core/pull/23313

**Pull request merged**
