### PR TITLE
How to polish code, eg: OC\User

### PR DESCRIPTION
**Pull request by butonic**
This PR serves as an example for polishing some of the issues that PHPStorm spits out when pressing "Inspect Code ...". They should be limited to a namespace to keep it reviewable.

**Inspecting a subfolder:**
unbenannt

unbenannt

**Before**
unbenannt

**After**
unbenannt

The four commits all address a single type of code smell. Feel free to just submit PRs for a single smell.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
looks good :+1:

**Comment by DeepDiver1975** [comment]
> After
> unbenannt

Could you also add the missing PHPDoc?

**Comment by butonic** [comment]
Sure thing.

**Comment by PVince81** [comment]
Looks good, OC didn't explode on my env like it sometimes does with `use` statements :+1:

**Comment by tflidd** [comment]
@butonic Do you know if there are good free alternatives to PHPStorm?

**Comment by DeepDiver1975** [comment]
@tflidd jentbrains offer a free of charge open source license - https://www.jetbrains.com/buy/opensource/

**Pull request merged**
