### PR TITLE
[stable8] Upgrade jquery-migrate to 1.2.1

### LINKED ISSUE #16817: jquery-migrate version has known sink
An external firm has done a quick web vulnerability assessment scan on owncloud and the result were impressive. Only one potential vulnerability was found in jquery-migrate.js, and it was of medium severity. Great! 

I don't believe this issue deserves an email to security@owncloud.org as it's 2 years old. But maybe the version could simply be bumped to 1.2.x? 

I know older libs are sometimes required for backward compatibility, if so, just let me know. 

```
weisheit :: /tmp/owncloud/core ‹master*› % retire . --js                                                                                                                                                                                     
Loading from cache: https://raw.github.com/RetireJS/retire.js/master/repository/jsrepository.json
/tmp/owncloud/core/core/vendor/jquery/jquery-migrate.js
 ↳ jquery-migrate 1.1.1 has known vulnerabilities: severity: medium; release: jQuery Migrate 1.2.0 Released, summary: cross-site-scripting; http://blog.jquery.com/2013/05/01/jquery-migrate-1-2-0-released/ severity: medium; bug: 11290, summary: Selector interpreted as HTML; http://bugs.jquery.com/ticket/11290 http://research.insecurelabs.org/jquery/test/
/tmp/owncloud/core/core/vendor/jquery/jquery-migrate.min.js
 ↳ jquery-migrate 1.1.1 has known vulnerabilities: severity: medium; release: jQuery Migrate 1.2.0 Released, summary: cross-site-scripting; http://blog.jquery.com/2013/05/01/jquery-migrate-1-2-0-released/ severity: medium; bug: 11290, summary: Selector interpreted as HTML; http://bugs.jquery.com/ticket/11290 http://research.insecurelabs.org/jquery/test/
weisheit :: /tmp/owncloud/core ‹master*› % 
```

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #16818 to stable8

Fixes #16817 on stable8

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @LukasReschke @svigneux

@karlitschek Please approve

**Comment by LukasReschke** [comment]
:+1:

**Comment by karlitschek** [comment]
backport is fine :+1:

**Comment by MorrisJobke** [comment]
@PVince81 Want to review again?

**Comment by PVince81** [comment]
:+1:

**Comment by svigneux** [comment]
+1, good job

**Pull request merged**
