### PR TITLE
[stable8] Use certificates that expire in 10 years

### PR DESCRIPTION
**Pull request by LukasReschke**
:speak_no_evil: :speak_no_evil: :speak_no_evil:

@DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
and here a lot of others unhappy, including php 7

**Comment by LukasReschke** [comment]
> and here a lot of others unhappy, including php 7

Expected. They will fail on anything except master. Only default matters on non-master branches.

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
