### PR TITLE
[stable8.1] Heal unencrypted file sizes at download time

### PR DESCRIPTION
**Pull request by schiessle**
approved backport of https://github.com/owncloud/core/pull/22579

@PVince81 @MorrisJobke please test and review... Thanks!

### CODE REVIEW

**Comment by schiesbn** [comment]
@jknockaert maybe you can also review the backports.... Thanks!

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by schiesbn** [comment]
ignore the failing tests, they are unrelated... @jknockaert final review? Thanks!

**Comment by jknockaert** [comment]
Yes working on it right now.

**Comment by jknockaert** [comment]
This one is good :+1:

**Pull request merged**
