### PR TITLE
Remove file mapper - was only use in Windows and never worked properly

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@PVince81 @nickvergessen @karlitschek

**Comment by karlitschek** [comment]
:+1:  
maybe we need something like that in the future for
- encrypted filenames
- workaround path lenght and filename limitations in external storage, local storage or desktop

just a thought

**Comment by DeepDiver1975** [comment]
Well - this is then more to be added as an additional column to the file_cache.

This was already part of a long time discussion with @dragotin - https://github.com/owncloud/core/wiki/Cross-Platform-File-Handling#platform-name

**Comment by PVince81** [comment]
:+1:

I agree that file name differences must be tracked in oc_filecache as a separate column, we discussed this several times already with @nickvergessen

**Comment by PVince81** [comment]
Tested, can still browse files :smile:

**Comment by PVince81** [comment]
:fire:

**Comment by nickvergessen** [comment]
https://youtu.be/LWQbuJ24Wzg?t=55 :disappointed_relieved: :broken_heart: 
/me saluts

**Pull request merged**
