### PR TITLE
Add postLogout hook to finish sessions from external session managers

### PR DESCRIPTION
**Pull request by felixrupp**
## Description

Added a second hook emit in the logout method in \OC\User\Session to achieve a cleaner logout routine, when using external session managers, like [CAS](https://wiki.jasig.org/display/CAS/Home).

## Related Issue

[Issue 26692](https://github.com/owncloud/core/issues/26692)

## Motivation and Context

When using external session managers, owncloud logout only allows to execute my own code before the oc session is terminated. Some of the mentioned session managers must be called after local sessions are terminated, otherwise the oc session is not terminated correctly.

## How Has This Been Tested?

The new hook has been testet on an Ubuntu 14 installation with PHP 5.6 and Owncloud 9.1.3-1.1 and a CAS session management via user_cas Application.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks.

@PhilippSchaffrath please review

**Review by phisch — APPROVED** [review]

**Comment by PhilippSchaffrath** [comment]
Files changed looks good, but there are 2 commits containing the same changes.

- [ ] Squash required

@DeepDiver1975 should we backport this?

**Comment by PVince81** [comment]
We usually don't backport features or API changes. Adding a hook like this is like adding a new API, so I'd say no.

I'll squash on merge.

**Comment by PVince81** [comment]
@felixrupp can you sign the CLA ? https://github.com/owncloud/core/pull/27048#issuecomment-275944532

**Comment by felixrupp** [comment]
@PVince81 Sorry, I signed the CLA, but my commit-e-mail-adress was not linked with github. Should be signed by now!

**Pull request merged**
