### PR TITLE
check if the user is trying to scan a valid path

### PR DESCRIPTION
**Pull request by icewind1991**
cc @DeepDiver1975 @PVince81 @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
I'd love to have an unit-test covering this.

**Comment by MorrisJobke** [comment]
> I'd love to have an unit-test covering this.

@icewind1991 Ping

**Comment by LukasReschke** [comment]
@karlitschek Please approve backport to stable8 and stable8.1 as well.

**Comment by LukasReschke** [comment]
I will add unit tests.

**Comment by LukasReschke** [comment]
Unit tests added. :+1: from my side.

**Comment by DeepDiver1975** [comment]
> I will add unit tests.

@icewind1991 next time I expect you to add tests right away.

THX @LukasReschke

**Comment by LukasReschke** [comment]
Stable8.1: https://github.com/owncloud/core/pull/17896/files
Stable8: https://github.com/owncloud/core/pull/17897

**Comment by DeepDiver1975** [comment]
> @karlitschek Please approve backport to stable8 and stable8.1 as well.

@icewind1991 please open PRs for stable8 and stable8.1 right away - THX

**Comment by DeepDiver1975** [comment]
@cmonteroluque packaging of this weeks RC1s has to wait until we have these PRs merged - THX

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by karlitschek** [comment]
backport is fine :+1:

**Pull request merged**
