### PR TITLE
Stable8 backport 19546

### PR DESCRIPTION
**Pull request by oparoz**
Backport of #19546

### CODE REVIEW

**Comment by oparoz** [comment]
Requires a backport of https://github.com/owncloud/core/pull/19574

**Comment by oparoz** [comment]
Backport of #19574 has been merged: https://github.com/owncloud/core/pull/19681

**Comment by MorrisJobke** [comment]
I rebased on current stable8. 

@oparoz AFAIK this is now ready for review?! ;)

**Comment by oparoz** [comment]
I see that the tests now pass, so yes :)

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@PVince81 @icewind1991 @nickvergessen Please review

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
