### PR TITLE
Chunk the "db:convert-type" select queries, to not run out of memory …

### PR DESCRIPTION
**Pull request by nickvergessen**
…so fast

Based on the idea of https://github.com/owncloud/core/pull/17548

### CODE REVIEW

**Comment by rullzer** [comment]
@nickvergessen how to test? (I modified a column in the db_structure.xml and ran update)... looked OK...

**Comment by nickvergessen** [comment]
Run the command to migrate from mysql to postgres and use chunk_size 2

**Comment by rullzer** [comment]
Finally got around... works here... :+1:

**Comment by nickvergessen** [comment]
@PVince81 second review?

**Comment by PVince81** [comment]
Code looks fine. I hope some day we can also add CI for this, might be complex as one needs two databases... Merging for now. :+1:

**Pull request merged**
