### PR TITLE
Fix the FIXME in DecryptAll from parallel merges

### PR DESCRIPTION
**Pull request by nickvergessen**
https://github.com/owncloud/core/pull/24992 and https://github.com/owncloud/core/pull/24998 had parallel merge conflicts.

### CODE REVIEW

**Comment by nickvergessen** [comment]
@PVince81 @davitol

**Comment by PVince81** [comment]
Parallel merges for the parallel worlds :+1:

**Comment by PVince81** [comment]
@owncloud/encryption @mmattel @icewind1991

**Comment by nickvergessen** [comment]
@ChristophWurst easy to review

**Comment by ChristophWurst** [comment]
:+1: looks good

**Pull request merged**
