### PR TITLE
Preventing Handlebars from escaping expressions. #29989

### PR DESCRIPTION
**Pull request by ajainuary**
## Description

By default with {{expressions}}, Handlebars.js HTML-escapes values returned (& -> &amp;). By replacing the double-parrenthesis with triple-parenthesis {{{expression}}} this can be prevented.(& is preserved)

## Related Issue

https://github.com/owncloud/core/issues/29989
## Motivation and Context

It prevents the appearing of HTML-escape values for special characters like &,<,>, etc. when used in Group names in the sharing auto-complete menu.
## How Has This Been Tested?

Steps followed as mentioned in https://github.com/owncloud/core/issues/29989 result in the proper rendering of group-names as displayed in the screenshot.
## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks a lot! Can you double check that display names are already escaped on another level ? Not escaping on handlebars level could cause a risk of XSS injection if a group name somehow contains something like a script tag.

**Comment by ajainuary** [comment]
@PVince81 can you please point out at what level the string should be escaped?

**Comment by PVince81** [comment]
@ajainuary I'd expect it to be escaped one level higher: not on handlebars level but the code that sets the value to the handlebars template.

**Comment by ajainuary** [comment]
@PVince81  sorry for the delay, I was a bit caught up with with my university exams. I am new to this, so I cannot understand how would this create an Cross Site Scripting bug as when I tried the characters were properly escaped.

**Comment by sharidas** [comment]
Ok, so looking at issue https://github.com/owncloud/core/issues/29989 for which this PR was created, did a basic testing ( without this patch ) and here is the result 
group_name_with_ampersand 

The testing I did was for group name with `&`. Lets say even if the group name has other special characters like `$#@` and created group `a$#@char` and  here is the result 
specialchars

We have fixed issues like escape urlencoding. Hence I am getting a feel that we can close this PR. Let me know if we agree on this.

**Comment by PVince81** [comment]
thanks for verifying, looks fixed then

**Pull request closed without merging**
