### PR TITLE
[stable9] Fixed 'Help Translate' link

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of #23705

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by rullzer** [comment]
:+1:

**Comment by rullzer** [comment]
This patch is MIT licenced as stated in https://github.com/owncloud/core/pull/23705#issuecomment-204001207

**Comment by paurisa** [comment]
@rullzer Correct, it's MIT licenced.

**Pull request merged**
