### PR TITLE
Allow files app nav entries to have a different icon class

### PR DESCRIPTION
**Pull request by MorrisJobke**
Replacement for #15602

cc @DeepDiver1975 @jancborchardt 

This reuses the currently unused icon entry of the navigation to pass in the css class to use with `nav-icon-...`

I will create the fixing PRs in the corresponding apps.

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@jancborchardt @DeepDiver1975 Is this the way how we want this?

**Comment by jancborchardt** [comment]
Works nicely. :+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 check please if this is the correct way to do this.

**Comment by DeepDiver1975** [comment]
THX, guys! :+1:

**Pull request merged**
