### PR TITLE
Update icewind/smb v3.2.5 and other files_external/3rdparty dependencies

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
```
cd apps/files_external/3rdparty
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 5 updates, 1 removal
  - Removing guzzlehttp/promises (v1.3.1)
  - Updating icewind/smb (v3.2.3 => v3.2.4): Downloading (100%)         
  - Updating google/apiclient-services (v0.130 => v0.136): Downloading (100%)         
  - Updating react/promise (v2.7.1 => v2.8.0): Loading from cache
  - Updating google/auth (v1.8.0 => v1.9.0): Downloading (100%)         
  - Updating monolog/monolog (1.25.3 => 2.0.2): Downloading (100%)         
```

https://github.com/icewind1991/SMB/releases/tag/v3.2.4

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
  - Updating icewind/smb (v3.2.4 => v3.2.5): Downloading (100%)         
  - Updating google/apiclient-services (v0.136 => v0.138): Downloading (100%)         
  - Updating monolog/monolog (2.0.2 => 2.1.0): Loading from cache
```

https://github.com/icewind1991/SMB/releases/tag/v3.2.5

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating google/apiclient (v2.4.1 => v2.5.0): Downloading (100%)         
```

https://github.com/googleapis/google-api-php-client/releases/tag/v2.5.0

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
> Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would create a [changelog](https://github.com/owncloud/core/blob/master/changelog/README.md) item based on your changes.

There is a changelog - `changelog/unreleased/37415` - what did I do wrong?

**Comment by jvillafanez** [comment]
I'd keep this on hold until we have more information about the problem.
I can't reproduce the issue which the smb 3.2.3 -> 3.2.4 update should solve using samba under ubuntu 20.04 (default installation). The changes in the update look fishy if we can't reproduce the problem.

I haven't checked the changes for the google update, but it might need a different PR.

**Comment by phil-davis** [comment]
Rebased and added latest `icewind/smb` and `google/apiclient` ...

**Comment by mmattel** [comment]
stuck at `yarn install` ... ?

**Comment by phil-davis** [comment]
> stuck at `yarn install` ... ?

sometimes there are `yarn install` network issues. I will rebase again. But no rush to merge this - it needs more detailed testing of smb... storages. Probably for after 10.5.0.

**Comment by jvillafanez** [comment]
> I'd keep this on hold until we have more information about the problem.
I can't reproduce the issue which the smb 3.2.3 -> 3.2.4 update should solve using samba under ubuntu 20.04 (default installation). The changes in the update look fishy if we can't reproduce the problem.

Not sure how did I test it, but it's reproducible with smbclient 4.10 (using a ppa for ubuntu 18.04) and with smbclient 4.11.6 (default installation in ubuntu 20.04). It seems the php version doesn't affects the behaviour.
smbclient 4.7.6 (default for 18.04) doesn't have this problem.

The consequences are that folders are mistakenly taken as regular files.

It seems a problem with the libsmbclient library. I've checked against a samba server (default installation for ubuntu 16.04) and also against a windows server 2016 without any difference.

I've also noticed that the smbclient's "allinfo" command shows the right dos mode, but the php-libsmbclient doesn't. However, there is no noticeable change in the code of the php-libsmbclient.

**Comment by phil-davis** [comment]
I rebased and added the 3rd commit to grab the very latest dependency `google/apiclient-services (v0.138 => v0.139)`

So that  this is up-to-date if anyone needs it...

**Comment by davitol** [comment]
> So that this is up-to-date if anyone needs it...

I have stumbled upon this problem testing SMB in 10.5 with ubuntu 20.4. when browsing into the SMB mountpoint configured

Screenshot 2020-06-25 at 09 29 11


`{"reqId":"719aNRuge9DK4ev9lYAB","level":4,"time":"2020-06-25T07:21:52+00:00","remoteAddr":"172.19.0.1","user":"admin","app":"webdav","method":"GET","url":"\/remote.php\/webdav\/SMB","message":"Exception: HTTP\/1.1 503 Could not open file: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"Could not open file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpGet()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\DAV\\\\Server->emit()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(251): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(319): Sabre\\\\DAV\\\\Server->start()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(65): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":397}"}`

but works with smbclient

Screenshot 2020-06-25 at 09 30 13

**Comment by davitol** [comment]
Issue commented above is solved using this PR so IMHO it is a must to be included into 10.5 @micbar @jvillafanez

**Comment by phil-davis** [comment]
Note: #37594 has been merged to `release-10.5.0` branch. That gets this into the next 10.5.0RC. It will get merged back to master in due course.

I will leave this PR to master open for the moment, but actually we should not need it.

**Comment by phil-davis** [comment]
PR #37594 was merged to an old `release-10.5.0` branch, and that branch has since been merged back to `master`. So this code is all in `master` now.

Closing.

**Pull request closed without merging**
