### PR TITLE
[stable8.1] Allow public auth to recognize sesssion

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/19402

Please review @LukasReschke @oparoz @icewind1991 @schiesbn @SergioBertolinSG

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1: 

Is 8.1 frozen atm, I think not, right?

**Comment by MorrisJobke** [comment]
> Is 8.1 frozen atm, I think not, right?

cc @cmonteroluque @DeepDiver1975

**Comment by cmonteroluque** [comment]
not frozen

**Pull request merged**
