### PR TITLE
[encryption] check recovery key setting for the correct user

### LINKED ISSUE #15825: [enc2] Recovery key doesn't seem to work
### Steps to reproduce
1. Setup OC from scratch
2. Enable encryption and the default enc module
3. Log out then log in again as admin
4. Enable recovery key by setting a recovery password in the admin page
5. Create a user "user1" with password "test"
6. Login as "user1" and upload some files
7. Enable recovery key in the personal page
8. Login as admin
9. Go to the users page
10. Enter the recovery password
11. Change the password of "user1" to "xxx" (imagine the user had forgotten the password)
12. Login as "user1" with the password "xxx"
13. Access files

### Expected result
"user1" still has access to files.

### Actual result
After login, "user1" sees a notification about invalid private keys, asks the user to enter their password in the personal page. However, "user1" has forgotten the old password and cannot do that.

### Version
ownCloud 8.1 alpha2

@schiesbn @th3fallen @DeepDiver1975

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/owncloud/core/issues/15825

Steps to test: https://github.com/owncloud/core/issues/15825#issuecomment-97391474

cc @SergioBertolinSG This should fix the recovery key issue we discussed today, please give it a try. Thanks!

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Tested #15825 (comment) here, working fine :+1:

**Comment by schiesbn** [comment]
great... Needs a second reviewer, maybe @PVince81 @nickvergessen or @th3fallen ? Thanks!

**Comment by nickvergessen** [comment]
Needs to be rebased?

**Comment by schiesbn** [comment]
@nickvergessen  rebased

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Pull request merged**
