### PR TITLE
[backport] [stable8.2] add port to host only, if an URL is used instead of a plain hostname

### PR DESCRIPTION
**Pull request by blizzz**
Backport of #20155 

Please test / review @Xenopathic @PVince81 @directict

### CODE REVIEW

**Comment by karlitschek** [comment]
thanks a lot!

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
cc @davitol

**Comment by directict** [comment]
will this become available in future update?

**Comment by MorrisJobke** [comment]
> will this become available in future update?

There are PRs prepared for 8.1.5 and 8.2.1 ... it's very likely then ;)

**Comment by directict** [comment]
@MorrisJobke ah :) sorry ;)

**Comment by davitol** [comment]
:+1:

**Pull request merged**
