### PR TITLE
Do not display details bar after rename

### LINKED ISSUE #19839: Sidebar should not open, when renaming a file on mobile
### Steps
1. Open file list with max. 700 pixels, so the responsive design triggers
bildschirmfoto vom 2015-10-16 16 53 28
2. Rename the file

### Expected
You should see the file list with your renamed file

### Actual
You see the sidebar  instead of the file list

---

I would not expect this behaviour. Suddenly a view pops up out of no where, although I didn't trigger it (intentionally).
The behaviour would be okay, if you can rename a file from the sidebar I guess. But atm it feels wrong.

@PVince81 what do you think?

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/19839

@nickvergessen @MorrisJobke @jancborchardt @rullzer

### CODE REVIEW

**Comment by PVince81** [comment]
Note: this is not specific to mobile. Just rename a file, the sidebar should not open any more.
However if the sidebar was already open, its contents will still update with the new file name.

**Comment by nickvergessen** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:


Adding backport request, because the initial issue was filed against 8.2.1

**Comment by karlitschek** [comment]
yes. please backport

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19939

**Pull request merged**
