### PR TITLE
execute remote share operations in an async manner

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@schiesbn alternative approach for #14070 

TODO:
~~\- [ ] add unit test for the asnc http job~~
~~\- [ ] create new background job class: DelayQueuedJob - a one time job with an minimum pause time~~
~~\- [ ] move the async job class to core for general usage~~
- [ ] test if s2s is still working
- [x] oc_jobs.argument only holds 255 char - needs to be incremented
- [ ] possibility on the command bus to have some kind of delay

### CODE REVIEW

**Comment by LukasReschke** [comment]
I'd prefer this one as it does not add more stuff to the Public API :rocket:

**Comment by DeepDiver1975** [comment]
should even be easier to accomplish with https://github.com/owncloud/core/pull/14300

**Comment by DeepDiver1975** [comment]
> should even be easier to accomplish with #14300

I take that back - due to the nature that we want this to retry posting - we have to stick with this apporach.

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by LukasReschke** [comment]
Bunch of errors such as the following:

```
09:44:39 1) Test\App\InfoParser::testParsingValidXml with data set #0 ('expected-info.json', 'valid-info.xml')
09:44:39 Argument 3 passed to OC\HTTPHelper::__construct() must implement interface OCP\Command\IBus, none given
```

**Comment by PVince81** [comment]
Needs rebase

**Comment by DeepDiver1975** [comment]
rescheduling this for 8.2 - we are entering freeze for 8.1 tomorrow

**Comment by MorrisJobke** [comment]
@DeepDiver1975 What is the status of this?

**Comment by PVince81** [comment]
@DeepDiver1975 defer to 9.0 or is there anything that can be finished for 8.2 already ?

**Comment by schiesbn** [comment]
we are in feature freeze, so I would say -> 9.0

**Comment by DeepDiver1975** [comment]
:fallen_leaf:

**Pull request closed without merging**
