### PR TITLE
Acceptance tests for release 10.2.1

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Backport all acceptance test changes to `release-10.2.1` 
Then we will be running the most acceptance tests that we have, including various new test scenarios that have been added in the 2 months since `release-10.2.0` was branched off from `stable10`

I could have tried to identify which acceptance test changes are additions of useful tests/test code fixes vs refactoring. And then just cherry-pick those that are additions of useful tests/test code fixes. But then many of those cherry-picks would have to be adjusted back to the way of doing things before the various refactorings. So it is much easier to cherry-pick everything. That way we get the acceptance test suite as it is currently working in `stable10`

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
Acceptance test PRs in `stable10` that have their commits in here:
35008
35090
35120
35141
35152
35158
35173
35186
35190
35216
35217
35200
35231
35250
35251
35259
35281
35296
35297
35298
35299
35276
35285
35302
35306 - Accessing sharetab directly for a long list of files - has js code changes and acceptance test changes - this one is a minor fix as well as acceptance test code
35291
35320
35300
35287
35333
35343
35351
35352
35357
35360
35361
35369
35370
35372
35374
35376
35377
35379
35381
35367
35383
35391
35402
35393
35404
35424
35410
35411
35425
35428
35423
35416
35431
35409
35435
35439
35449 - Revert "[stable10] Backport of Convert shareWith to lower case" - 1st commit was already there, I cherry-picked the other 2 commits
35452
35456
35462
35465
35463
35467
35469
35470
35473
35479
35481
35489
35495
35496
35497
35504
35529
35397 - [stable10] use a multi line approach to display share autocomplete - has lots of acceptance test refactoring in it - took the middle 6 commits related to UI tests, those have useful acceptance test code refactoring
and then added `281af08e47` "Adjust SharingDialog suffixToIdentify Groups Users RemoteUsers" so that the test expectations should match the old strings
35514
35515
35517
35522
35527
35532
35533
35536
35537
35547
35548
35553
35559
35560

Let's see if the acceptance tests go anywhere near passing.

**Review by individual-it — APPROVED** [review]
if CI passes it must be good!

**Comment by phil-davis** [comment]
I luv CI (not) https://drone.owncloud.com/owncloud/core/18468/754
```
  [Composer\Downloader\TransportException]                                                                                                                                     
The "https://packagist.org/p/provider-latest%249a01b3c3c1cd2ae4764e239f6e1d56d32c44b05e77ce9132e81f2777d9d30e0e.json" file could not be downloaded (HTTP/1.1 404 Not Found) 
```
Restarting drone build...

**Comment by phil-davis** [comment]
CI is good. That is very nice. It means that all the latest acceptance test scenarios pass against 10.2.1 code.
@patrickjahns please review.

**Comment by micbar** [comment]
@phil-davis Could you remove https://github.com/owncloud/core/pull/35306 from this PR and create a separate backport?

**Comment by phil-davis** [comment]
I pushed a revert on the end.
Removing the commit from the middle was causing annoying conflicts in later commits.

**Review by patrickjahns — APPROVED** [review]
LGTM

**Comment by phil-davis** [comment]
@patrickjahns this is ready to merge - you are the person controlling `release-10.2.0` branch.

**Pull request merged**
