### PR TITLE
German correction

### PR DESCRIPTION
**Pull request by nerdoc**
https://en.wiktionary.org/wiki/verschl%C3%BCssle
I think that "Verschlüssle den Speicher" is not quite explanatory what it exactly does. This could be the RAM as well. "home storage" is a bit technical, but as this is the admin interface, I would suggest even a better Translation: "Verschlüssle den Speicherort der Benutzer" - but this is not the exact translation neither, so I don't dare suggesting it ;-)

### CODE REVIEW

**Comment by LukasReschke** [comment]
Also https://github.com/owncloud/core#important-notice-on-translations :)

**Comment by nerdoc** [comment]
Oh - how is translation handled for apps? I cant find that on transifex? There's only files_encryption.

**Comment by LukasReschke** [comment]
Mhm. files_encryption was the old namespace for the app.

Summoning @DeepDiver1975 I assume it has to be done there as well? Or is there another project for that one?

**Comment by nerdoc** [comment]
Ah. Already found it: https://www.transifex.com/owncloud-org/owncloud/viewstrings/#de/files_encryption/64933898?qt=verschl%C3%BCssel%20den

**Comment by LukasReschke** [comment]
:)

**Comment by DeepDiver1975** [comment]
the transifex project files_encryption has bee reused for encryption ... just because

**Pull request closed without merging**
