### PR TITLE
Fix (re)share permission checks in a few code paths

### LINKED ISSUE #20476: Files/folders created while the users group was included in 'Exclude groups from sharing' cannot be shared even if the group is removed from the excluded groups.
### Steps to reproduce

1. Create a user that belongs to a group
2. Go to admin page
3. Set the group to be excluded from sharing
4. Login with the  user created in another browser and create a folder and a file
5. With admin user remove the users group from the list of 'excluded from sharing"

### Expected behaviour

After removing the users group from the list of 'excluded from sharing", the file/folder created WHILE the group was in the list, now should be enabled from sharing.

### Actual behaviour

The files/folders created while the users group was included in 'Exclude groups from sharing' cannot be shared even if the group is removed from the excluded groups.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 8.2.1. (RC2)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

screen shot 2015-11-12 at 13 16 38

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/20476 by making sure that the file cache permissions is still the original one, but the share permissions are computed at view time / FileInfo.

Fixes issues where incoming remote shares were still resharable even though resharing was disabled in the admin page.

I'm not proud of this fix but this is the simplest and hopefully backportable way.
@icewind1991 @rullzer what do you think ?

### CODE REVIEW

**Comment by icewind1991** [comment]
I was thinking about doing something similar but use a cache wrapper to apply the final sharing permissions.

I'm fine with this approach to :+1:

**Comment by rullzer** [comment]
Yes looks good! :+1: 
But the unit tests are not yet happy

**Comment by PVince81** [comment]
> But the unit tests are not yet happy

Again ? Already fought them before. Let me have a look.

**Comment by PVince81** [comment]
```
....................................SSSSSS...............PHP Fatal error:  Call to a member function getId() on null in /srv/www/htdocs/owncloud/lib/private/files/fileinfo.php on line 270
PHP Stack trace:
PHP   1. {main}() /home/vincent/.composer/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main($exit = *uninitialized*) /home/vincent/.composer/vendor/phpunit/phpunit/phpunit:56
PHP   3. PHPUnit_TextUI_Command->run($argv = *uninitialized*, $exit = *uninitialized*) /home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_TestRunner->doRun($suite = *uninitialized*, $arguments = *uninitialized*) /home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run($result = *uninitialized*) /home/vincent/.composer/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:423
PHP   6. PHPUnit_Framework_TestSuite->run($result = *uninitialized*) /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:751
PHP   7. PHPUnit_Framework_TestCase->run($result = *uninitialized*) /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:751
PHP   8. PHPUnit_Framework_TestResult->run($test = *uninitialized*) /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:711
PHP   9. PHPUnit_Framework_TestCase->runBare() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestResult.php:643
PHP  10. PHPUnit_Framework_TestCase->runTest() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:775
PHP  11. ReflectionMethod->invokeArgs(*uninitialized*, *uninitialized*) /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:905
PHP  12. Test\Files\Node\File->testDelete() /home/vincent/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php:905
PHP  13. OC\Files\Node\File->delete() /srv/www/htdocs/owncloud/tests/lib/files/node/file.php:55
PHP  14. OC\Files\Node\Node->checkPermissions($permissions = *uninitialized*) /srv/www/htdocs/owncloud/lib/private/files/node/file.php:100
PHP  15. OC\Files\Node\Node->getPermissions() /srv/www/htdocs/owncloud/lib/private/files/node/node.php:104
PHP  16. OC\Files\FileInfo->getPermissions() /srv/www/htdocs/owncloud/lib/private/files/node/node.php:221
PHP  17. OC\Files\FileInfo->isShared() /srv/www/htdocs/owncloud/lib/private/files/fileinfo.php:199
```

**Comment by PVince81** [comment]
Okay, some tests are minimally mocking the FileInfo object by passing only `['permissions'=>31]`, so there is no storage for the `isShared` call...

**Comment by PVince81** [comment]
Okay, now that we use `isShare()` the `FileInfo` **MUST** have a storage passed to its constructor. I fixed the tests that didn't.

Also, the sharing code was relying on the storage Common::isSharable() to check for groups excluded from shares. Since I removed this check above, I added it back explicitly in the sharing code, see https://github.com/owncloud/core/commit/d0cca6c3aded2aaa35e5b2caab46ff49676eecbd

Please rereview the last two commits @icewind1991 @rullzer

**Comment by icewind1991** [comment]
:+1:

**Comment by rullzer** [comment]
The joy of the sharing code!

:+1:

**Comment by PVince81** [comment]
@karlitschek backport to 8.2.2 and 8.1.5 ?

**Comment by karlitschek** [comment]
please backport to 8.2 and 8.1

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/21080
stable8.1: TODO

**Pull request merged**
