### PR TITLE
Prohibit email/displayname change via API when not allowed

### LINKED ISSUE #39332: User can change their email address through api call when `allow_user_to_change_mail_address` is set `false`
### Steps to reproduce (for both v1 and v2 api)
1. Disallow user to change their email address by using occ command: 
`sudo -u www-data php occ config:system:set --value 'false' --type boolean allow_user_to_change_mail_address`
2. Use curl command to try to change the user email: 
for v1:
`curl -X PUT -u boe:password http://localhost/core/ocs/v1.php/cloud/users/boe -d key="email" -d value="boe@gmail.com" `
for v2:
`curl -X PUT -u boe:password http://localhost/core/ocs/v2.php/cloud/users/boe -d key="email" -d value="boe@gmail.com" `

### Expected behaviour
```<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
```
and email should not change for boe
### Actual behaviour
```<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
```
and email is changed for boe
if using .../v2.php/...
```<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
```
and email is changed for boe
### Server configuration
**Operating system**:
Ubuntu 20.04.3 LTS
**Web server:**
Apache
**Database:**
mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
**PHP version:**
PHP 7.4.3
**ownCloud version:** (see ownCloud admin page)
Latest master branch from github repo
**Updated from an older ownCloud or fresh install:**
Fresh install
**Where did you install ownCloud from:**
Github

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
When the configs `allow_user_to_change_mail_address` or `allow_user_to_change_display_name` are set to `false`, changing the corresponding values via the provisioning API is no longer possible.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/39332
- Fixes https://github.com/owncloud/core/issues/39331

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by AlexAndBear — APPROVED** [review]
LGTM, wondering if we should throw back a 405 instead of silently omitting the email address, if set in the request ?

**Comment by JammingBen** [comment]
> LGTM, wondering if we should throw back a 405 instead of silently omitting the email address, if set in the request ?

It actually throws a `997` 👍  The logic for this already exists a few lines below my implementation.

**Comment by JanAckermann** [comment]
Perfect one :+1:

**Review by jvillafanez — APPROVED** [review]
Changes look good

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
