### PR TITLE
fix "app":"PHP","message":"Undefined variable: user at/principal.php#66"

### PR DESCRIPTION
**Pull request by derkostka**
changed variable #user to #name

### CODE REVIEW

**Comment by derkostka** [comment]
@MorrisJobke : Could you please take this bugfix over to OC8 ? This error occured in OC8 Alpha 1:

"app":"PHP","message":"Undefined variable: user at \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/principal.php#66","level":3,"time":"January 04, 2015 16:46:22"}

-> This change is available to the public domain, to be used within owncloud under the MIT license

**Comment by derkostka** [comment]
This pull-request is MIT licensed, feel free to make use of it :-)
@LukasReschke : can you perform a short review ? Thanks !

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@derkostka Thanks for spotting this :)

**Comment by MorrisJobke** [comment]
@derkostka And of course fixing it! Awesome

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot this is okay to test

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Pull request merged**
