### PR TITLE
Recreate trashbin folder after full deletion

### PR DESCRIPTION
**Pull request by PVince81**
Possibly fix for https://github.com/owncloud/core/issues/9855

### CODE REVIEW

**Comment by PVince81** [comment]
@schiesbn @nickvergessen @MorrisJobke

**Comment by karlitschek** [comment]
:+1: makes sense

**Comment by nickvergessen** [comment]
:+1: *hopefully there is no test that tests that the directory is empty* :stuck_out_tongue_winking_eye:

**Comment by laodan** [comment]
Same problem as #9855 with 9.02 fresh install. Made fresh install of owncloud 9.02. Everything works fine from the interface except deleting. 


**Steps to reproduce**
Nor sure. Fresh install of owncloud 9.02 and impossible to delete. 

**Expected behavior**
Possibility to delete

**Actual behavior**
can't delete nor folder nor file.
owncloud logs: {"reqId":"V0@DGx8WBDsACJOfcjcAAAAA","remoteAddr":"211.100.51.17","app":"PHP","message":"opendir(\/home\/liusolas\/ownclouddata\/laodan\/files_trashbin\/files): failed to open dir: No such file or directory at \/home\/liusolas\/public_html\/owncloud\/lib\/private\/files\/storage\/local.php#99","level":3,"time":"2016-06-02T00:51:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files_trashbin\/ajax\/list.php?dir=%2F&sort=mtime&sortdirection=desc","user":"laodan"}

**Server configuration**
shared server. linux 64 bits (no clue which version)
Database: mysql
PHP version: 7.0
Updated from an older ownCloud or fresh install: fresh
Are you using external storage, if yes which one: no
Are you using encryption: no
Client configuration: owncloud desktop version

**Browser:** Firefox 46.0.1
**Operating system:** Ubuntu 14.04


I saw "Recreate trashbin folder after full deletion #15179" but this was done for owncloud version 7  I suppose. Seen I'm on version 9.02 I did not touch  apps/files_trashbin/lib/trashbin.php

**Pull request merged**
