### PR TITLE
Use OCP classes as much as possible in files_external v2

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Revival of #15363, with some further replacements and tests fixed.

@DeepDiver1975 The problem was with registration of users - one test didn't do so, relying on the (dangerous!) behaviour of `OC_User::getHome()`. Now it just registers the user, and all is well.

Please review @rullzer @karlitschek @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Won't this conflict with your other PR ?

**Comment by Xenopathic** [comment]
@PVince81 It might :see_no_evil: 

But I've gotten pretty good at fixing rebase conflicts now... so I'm not too bothered :smile:

**Comment by Xenopathic** [comment]
Rebased! Very simple. Please review @rullzer @karlitschek @PVince81 @DeepDiver1975 

files_external common unit tests all pass.

**Comment by PVince81** [comment]
Simple ? Needs regression testing for the parts that were touched.

**Comment by PVince81** [comment]
To test:
- [ ] applicable field search :no_entry_sign: FAIL
- [ ] Amazon S3 upload/download/mimetype
- [ ] dropbox upload/download
- [ ] gdrive upload/download
- [ ] openstack swift upload/download/mimetype
- [ ] read/save ext storage config (create a config, refresh the page)
- [ ] "External storage" section in the files list UI

- [ ] BUG: applicable list returns "[Object object]".

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by PVince81** [comment]
I can't test openstack, my old devstack instance is broken/outdated.

**Comment by PVince81** [comment]
Since the others work with the same API, it should also work with openStack

@Xenopathic please fix the issue with the applicable field.

**Comment by Xenopathic** [comment]
Applicable AJAX has been fixed

**Comment by PVince81** [comment]
:+1:

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
Oracle failed to start (again), but other tests were OK -> suggest merge @DeepDiver1975 ?

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
I saw other PRs succeeding today, so maybe Oracle luck is back on our side.

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
@karlitschek Could you quickly re-review? There wasn't much changed from the first review, just some AJAX applicable.php stuff.

**Comment by karlitschek** [comment]
yes. easy one. :+1:

**Pull request merged**
