### PR TITLE
Kill update simulation

### PR DESCRIPTION
**Pull request by PVince81**
## Description

Remove all code related to simulating migration at update time.
## Related Issue

None
## Motivation and Context

Update migration is only useful for small databases but also slows down upgrades by creating duplicates of databases.
Admins should rather rely on backups if something went wrong. Additionally, the new updater app will eventually be extended to also make database backups (or does it do it already @VicDeo?)
On bigger setups admins complained that they forgot to pass `--skip-migration-test` and then the simulation started and they had to revert their huge database.
## How Has This Been Tested?

Not tested yet:
- [ ] TEST: CLI upgrade
- [ ] TEST: web upgrade
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@DeepDiver1975 @butonic @VicDeo as discussed

I thought there was more code ?

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
Hmm, should we rather deprecate `--skip-migration-test` and the dry run one and make them do nothing ? And then remove it later ?

Because if people have existing automation scripts with that option these will fail to update with "option does not exist".

On the other hand this directly forces admin to adjust their scripts.

Thoughts @DeepDiver1975 @butonic ?

**Comment by butonic** [comment]
A script to automate upgrades? That's as wrong as it can be. We will need to document this in the release notes anyway.

**Comment by DeepDiver1975** [comment]
> On the other hand this directly forces admin to adjust their scripts.

:+1:

**Comment by PVince81** [comment]
Ok. I just ran this and it worked fine.

**Comment by PVince81** [comment]
Doc ticket: https://github.com/owncloud/documentation/issues/2640

**Comment by PVince81** [comment]
@owncloud/qa FYI in case testing scripts need to be adjusted

**Pull request merged**
