### PR TITLE
[stable8.1] Delete OCS ID from DB if none is specified 

### PR DESCRIPTION
**Pull request by LukasReschke**
If no OCS ID is specified in appinfo.xml and an app update is triggered and a OCS ID is stored in the DB we should clean the value.

Makes only sense with the other PRs against stable8.1.

@karlitschek I would love to have this in the 8.1.0 final

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by LukasReschke** [comment]
Merged as approved via private mail.

**Comment by karlitschek** [comment]
@LukasReschke Why 8.1.0 ? What is the criticality ?

**Comment by LukasReschke** [comment]
> @LukasReschke Why 8.1.0 ? What is the criticality ?

Happens to spam the log very often with fatal errors (which actually are non fatal)  in case an invalid OCS ID has been provided. This is however the case quite often since we could not update them reliably before.

**Comment by LukasReschke** [comment]
Such as the following when clicking on the app menu:

```
Fatal core Invalid OCS content returned for app 166049 2015-07-02T02:39:00+00:00
Fatal core Invalid OCS content returned for app 166055 2015-07-02T02:39:00+00:00
Fatal core Invalid OCS content returned for app 166059 2015-07-02T02:39:00+00:00
Fatal core Invalid OCS content returned for app 166053 2015-07-02T02:38:59+00:00
Fatal core Invalid OCS content returned for app 166052 2015-07-02T02:38:59+00:00
Fatal core Invalid OCS content returned for app 166038 2015-07-02T02:38:59+00:00
Fatal core Invalid OCS content returned for app 166056 2015-07-02T02:38:59+00:00
Fatal core Invalid OCS content returned for app 166051 2015-07-02T02:38:59+00:00
```

Since the OCS IDs do not resolve properly anymore.

**Comment by karlitschek** [comment]
hmm. ok. I guess this doesn't hurt. please backport

**Pull request merged**
