### PR TITLE
[stable10] Return false if the rename fails except for connect exceptions

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Backport of https://github.com/owncloud/core/pull/35598 to stable10

## Related Issue
https://github.com/owncloud/phoenix/issues/1326

## Motivation and Context
It should fail normally instead of blocking the storage

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by mmattel** [comment]
Q: what is the plan that this is available as part of a build?

**Comment by jvillafanez** [comment]
@mmattel sorry, I don't understand your question.

**Comment by mmattel** [comment]
It will most likely not go into 10.2.1.
What will be the release it will be in and when will that release be available? Sorry that my former writing was not clear enough.

**Comment by jvillafanez** [comment]
I think 10.2.1 is already on QA phase, so it will likely be in the next one, post 10.2.1.

**Comment by jvillafanez** [comment]
@micbar this is ready. Similar to the original PR, coverage can't be increased due to changes in the storage implementation that can't be unittested.

**Pull request merged**
