### PR TITLE
Resize thumbnails with keep aspect

### PR DESCRIPTION
**Pull request by zarej**
Now you can get thumbnail for any image and keep its aspect ratio. WIth this approach http://cloud.localhost/index.php/apps/files/api/v1/thumbnail/200/300/slika.png image will be croped to exactly requested dimensions (200x300). I added new approach which can keep aspect ratio of image and resize image within requested borders. REST call is the same just you need to add keepaspect after thumbnail and before resolution, it looks like this http://cloud.localhost/index.php/apps/files/api/v1/thumbnail/keepaspect/200/300/slika.png

### CODE REVIEW

**Comment by oparoz** [comment]
From 9.0, there should be a new WebDAV endpoint which serves previews meeting all sorts of requirements, so I doubt this will be merged in, but I'll let people closer to the action be the judge of that.

@georgehrke @icewind1991 

@zarej - If you need thumbnails which keep the aspect ratio for a project on 8.0+, you should use Gallery(+):
https://github.com/owncloud/gallery/wiki/RESTful-API#apipreviewfileidwidthheight

8.2 (gallery is included)
`http://cloud.localhost/index.php/apps/gallery/api/preview/{fileId}/{width}/{height}`
8.0-8.1 (gallery+ required)
`http://cloud.localhost/index.php/apps/galleryplus/api/preview/{fileId}/{width}/{height}`

**Comment by icewind1991** [comment]
You can also use the older preview endpoint which allows keeping aspect ratio

`http://localhost/owncloud/index.php/core/preview.png?file=/path/to/file&x=width&y=height&a=1`

**Comment by oparoz** [comment]
> You can also use the older preview endpoint which allows keeping aspect ratio

But I think it will be a problem if accessed like an API because of the lack of CORS support, no?

**Comment by icewind1991** [comment]
I think so yes

**Comment by zarej** [comment]
@oparoz Thanks for the suggestions. I didn't know about gallery, that should better suit my requirements. This request can be rejected.

**Pull request closed without merging**
