### PR TITLE
[stable8] fix theme in IE8 and IE9

### PR DESCRIPTION
**Pull request by MorrisJobke**
Forward port of #16415

cc @karlitschek @jancborchardt @gig13

### CODE REVIEW

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by DeepDiver1975** [comment]
@jancborchardt @gig13 @rperezb please test and verify this fixes the issue - THX

**Comment by gig13** [comment]
I see the same behavior when using IE8 in compatibility mode, the screen shows the Log in button far right and in some resolutions you are unable to click it.

**Comment by jancborchardt** [comment]
@gig13 how about IE8 in normal mode? I'm not sure we support compat mode? @MorrisJobke?

**Comment by MorrisJobke** [comment]
> @gig13 how about IE8 in normal mode? I'm not sure we support compat mode? @MorrisJobke?

I also don't think so. Compat mode mimics the pre-IE8 behaviour ... nothing we support - cc @karlitschek

**Comment by gig13** [comment]
@jancborchardt @MorrisJobke 
It displays normally for IE8 in non-compatibility mode. I still need to test with IE9, since that was the customer standard.

**Comment by jancborchardt** [comment]
@gig13 @davitol @jnfrmarks so just for the record: We do _not_ support anything older than IE8. That means please do_not_ use IE8 in compatibility mode when testing.

**Comment by davitol** [comment]
:+1: fixed in IE9

**Comment by davitol** [comment]
Also tested in IE8 and :+1:

**Pull request merged**
