### PR TITLE
Unit tests for validatePassword event

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Added missing unit tests for some cases of "validatePassword" Symfony event.

## Related Issue
None

## Motivation and Context
I was actually working on a fix and found that these unit tests were missing so added them.
Then it turned out that the fix wasn't needed, so I decided to still submit the tests here.

## How Has This Been Tested?
Pure unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
No chance to get the Event Dispatcher mocked?

**Comment by PVince81** [comment]
> No chance to get the Event Dispatcher mocked?

not now... this was part of another task where I already lost time because of these missing unit tests.

which solution is LBS ?

**Review by sharidas — APPROVED** [review]
LGTM :+1:

**Comment by PVince81** [comment]
@ownlouders rebase

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
