### PR TITLE
Remove children from the cache in one query

### PR DESCRIPTION
**Pull request by icewind1991**
Go from 1 query per folder + 1 query per file to 2 queries per folder

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Can you extend "testFolder" to have a second level of folders ?
Currently the test folder only contains two files "foo" and "bar" and doesn't cover the case where we recurse into subdirs.

**Comment by icewind1991** [comment]
Added extra unit test

**Comment by MorrisJobke** [comment]
Awesome. It's much faster :+1:

1GB in 136 files

11.1s -> 809 ms (with disabled trashbin and encryption) 

Before https://blackfire.io/profiles/db8a168e-41b3-4de7-8f02-63023b4a434b/graph
After https://blackfire.io/profiles/885db930-dea5-40b9-9366-d1fe144f72de/graph

**Comment by MorrisJobke** [comment]
before 136 * OC_DB::executeAudited 
after 7 * OC_DB::executeAudited

**Comment by MorrisJobke** [comment]
Compare view: https://blackfire.io/slots/compare/acd15fca-713b-4f09-b11e-1b8308ddb989...54097398-7f60-4105-85e5-9b594abec59f/graph?callname=main()&selected=&settings%5Bdimension%5D=wt&settings%5BcallerDepth%5D=2&settings%5BcalleeDepth%5D=&settings%5BminNodeCost%5D=5&settings%5BminCallCost%5D=0.01

**Comment by PVince81** [comment]
Code looks good, makes sense :+1:

**Comment by PVince81** [comment]
@DeepDiver1975 if this is ok for 8.0 then we can merge this ?

**Comment by MorrisJobke** [comment]
Even more impressive is the deletion of 2.2 GB with nearly 700 files and process time drops from 52.9s to 1.63s \o/ I like that profiling :)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 if this is ok for 8.0 then we can merge this ?

let me have a look ... had some reallife the past few houes :wink:

**Comment by DeepDiver1975** [comment]
@MorrisJobke can you please share the profiling graph with me? THX

**Comment by LukasReschke** [comment]
> @MorrisJobke can you please share the profiling graph with me? THX

They are posted above? - The links in https://github.com/owncloud/core/pull/13394#issuecomment-70134185 work fine for me here

**Comment by DeepDiver1975** [comment]
> They are posted above? - The links in #13394 (comment) work fine for me here

thx - the compare did not work .... anyway

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 if this is ok for 8.0 then we can merge this ?

:rocket: THX guys! - Now that you know how it works: GO GO GO :wink:

**Comment by MorrisJobke** [comment]
52 s https://blackfire.io/profiles/5e58c63e-afdd-4a37-bdc1-b42582cca061/graph
1,6s https://blackfire.io/profiles/d8b01cba-3e0b-46ea-932f-2e217f893e80/graph

**Comment by MorrisJobke** [comment]
Compare between them: https://blackfire.io/profiles/compare/bf7c3c41-945e-49dd-832a-1bbadc0ddec8/graph

**Comment by MorrisJobke** [comment]
> thx - the compare did not work .... anyway

Upps ... wrong link. I updated it above. 

https://blackfire.io/profiles/compare/97434597-dc19-4756-a76f-bdde8647a36e/graph

**Comment by DeepDiver1975** [comment]
@icewind1991 nice job - THX

**Pull request merged**
