### PR TITLE
[WIP] change dropdowns to light version

### PR DESCRIPTION
**Pull request by jancborchardt**
The dark dropdowns (for apps and user menu) feel more and more out of place. We should switch them to bright, with dark text and icons.

The first part of this is to change the user dropdown on the top right. What do you think @owncloud/designers @karlitschek?

The next part is doing the same for the apps menu, and changing all app icons to bright.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
* [ ] Too much shadow
* [ ] Change font color to something more black or even black

**Comment by jancborchardt** [comment]
Screenshots before:
dropdown-before
after:
menu-after

@MorrisJobke good points, will look into it.

Another point I just discussed with @karlitschek is how we handle upgrading for apps … cause the icon is completely different in 8.1 from 8.0 then.

A solution would be to keep it dark, but make it black and look more like the tipsy tooltip, with triangle and further away from the header.

**Comment by MorrisJobke** [comment]
@jancborchardt Can we finish the right menu in this PR and try to address the apps icons in a new PR. Otherwise this will get too hard to be reviewed.

**Comment by jancborchardt** [comment]
Fixed by https://github.com/owncloud/core/pull/14958 already.

**Pull request closed without merging**
