### PR TITLE
standardize sizes for headings

### PR DESCRIPTION
**Pull request by jancborchardt**
Use the h2 and h3 styles globally, not only inside .section elements. This makes sure it also is used on error pages etc.

Please review @owncloud/designers :)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by tomneedham** [comment]
:+1: just needs rebase

**Comment by jancborchardt** [comment]
@DeepDiver1975 merge please

**Comment by jancborchardt** [comment]
Yo yo @DeepDiver1975 @karlitschek, merge please ;)

**Comment by DeepDiver1975** [comment]
rebased ...

**Pull request merged**
