### PR TITLE
[stable8.2] [user_ldap] properly decode cached objects

### LINKED ISSUE #21896: Sharing with LDAP Users not working on subsequent attempts when cache is enabled
### Steps to reproduce
1. Having cache enabled: APCu 4.0.7, Redis 2.2.7 
2. Trying to share some files/folders with an LDAP User
2. When typing the first letters of the Username, User is being correctly found on the first attempt
3. However, when deleting the letters and searching again for the same User, this cannot be found and the search seems to be stuck
4. This only happens when cache is enabled

### Expected behaviour

LDAP User should also be found on the second attempt

### Actual behaviour

See above

### Server configuration
**Operating system**:

Debian Jessie

**Web server:**

Apache 2.4

**Database:**

Percona XtraDB 5.6.27

**PHP version:**

5.6

**ownCloud version:** (see ownCloud admin page)

8.2.2

**Updated from an older ownCloud or fresh install:**

Fresh install

**Are you using external storage, if yes which one:** local/smb/sftp/...

local

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

@MorrisJobke can you maybe help here?

00004656

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #21896
- [x] approval by @karlitschek needed
- backport of #21999 

cc @blizzz @nickvergessen @PVince81 @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by blizzz** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Oracle failure unrelated.

**Comment by MorrisJobke** [comment]
@karlitschek Could you please approve this backport?

**Comment by karlitschek** [comment]
The linked issue don't work. What is the fixed issue?

**Comment by MorrisJobke** [comment]
> The linked issue don't work. What is the fixed issue?

They do, but Safari has a bug (either refresh the page or use a different browser ;))

**Comment by MorrisJobke** [comment]
> Having cache enabled: APCu 4.0.7, Redis 2.2.7
> Trying to share some files/folders with an LDAP User
> When typing the first letters of the Username, User is being correctly found on the first attempt
> However, when deleting the letters and searching again for the same User, this cannot be found and the search seems to be stuck
> This only happens when cache is enabled

**Comment by blizzz** [comment]
@karlitschek backport ok?

**Comment by karlitschek** [comment]
backport is fine. :+1:

**Pull request merged**
