### PR TITLE
Fix duplicated line in doc block

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke @PVince81 @icewind1991 

Regresseion from #17295

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by PVince81** [comment]
Well, "Regression" is only when functionality is broken.

:+1:

**Comment by nickvergessen** [comment]
"Regression" is "to go back to previous behaviour" or in software terms "the appearance of a bug which was absent in a previous revision" https://en.wikipedia.org/wiki/Regression

anyway, was just trying to make a link with description ;)

**Comment by PVince81** [comment]
It's not a bug :open_mouth:. Well, maybe it's a bug on another level, if you consider crying IDEs bugs :wink:

**Pull request merged**
