### PR TITLE
Allow admins to add system wide root certificates

### PR DESCRIPTION
**Pull request by icewind1991**
Allow adding ssl root certificates from the admin page just like from the personal page, these certificates will be trusted system wide.

This is needed since the user added root certs aren't used for while doing cron jobs which makes it impossible to have things like federation with self signed certificates.

cc @LukasReschke @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense. We need a way to disable this because it seems that this setting confused some admins in the past. Yes. Don't ask me why. ;-)
@MTRichards

**Comment by karlitschek** [comment]
config.php setting is enough btw. no GUI

**Comment by MTRichards** [comment]
Yep, thank you.

**Comment by LukasReschke** [comment]
Are you sure on the config flag? The previous complaints where about the user page as the admins did not want to have users import certificates. Why one would forbid admin to do such administrative tasks would be behind my knowledge :smile:

**Comment by karlitschek** [comment]
@mtrichards what do you think? your call :-)

**Comment by icewind1991** [comment]
Fixed the failing tests

**Comment by PVince81** [comment]
@MTRichards in the light of https://github.com/owncloud/core/pull/21336#issuecomment-166718544, to GUI or not to GUI ?

**Comment by MTRichards** [comment]
@LukasReschke correct, the reported problem was for the user page.

This is only relevant for Federated Sharing, or also for other use cases?

If only federated sharing, I would config switch it for the admin page too, just to keep it simple for the less complex scenarios and less sophisticated admins. It can be turned on if config switch is on, but otherwise the admin won't see it or be confused by it. 

@bboule any thought here?

**Comment by icewind1991** [comment]
Besides fed sharing it also effects external storages (dav at least not sure about others)

**Comment by bboule** [comment]
@MTRichards :+1:

**Comment by MTRichards** [comment]
Ok, we have a decision. Thanks.

**Comment by DeepDiver1975** [comment]
> Ok, we have a decision. Thanks.

Which is? Add config or not? Sorry - I don't get it :crying_cat_face:

**Comment by MTRichards** [comment]
>I would config switch it for the admin page too, just to keep it simple for the less complex scenarios and less sophisticated admins. It can be turned on if config switch is on, but otherwise the admin won't see it or be confused by it.

**Comment by icewind1991** [comment]
Added config switch (`enable_certificate_management`) to enable the certificate management ui.

please review @PVince81 @LukasReschke @DeepDiver1975

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
We can ignore the smahbox tests on this one :+1:

**Comment by DeepDiver1975** [comment]
We can ignore the smahbox tests on this one :+1:

**Comment by LukasReschke** [comment]
This broke the setup: https://github.com/owncloud/core/issues/21669

**Comment by RealRancor** [comment]
Documentation for this is (as quite often) completely missing :see_no_evil: 

-> https://github.com/owncloud/documentation/issues/2534

**Pull request merged**
