### PR TITLE
Add file row indicator for unread comments

### PR DESCRIPTION
**Pull request by PVince81**
- [x] add indicator
- [x] send Webdav PROPPATCH request to reset the counter when opening the comments tab
- [x] reset indicator in file row after the backend returned success (use backbone model event magic)
- [x] unit tests for all
- [ ] update icon to be a comment ( @jancborchardt can probably change this later)

unread-comments-indicator

@blizzz

### CODE REVIEW

**Comment by karlitschek** [comment]
nice! :+1:

**Comment by PVince81** [comment]
Note: there is a separate bug where your own comments are "unread": https://github.com/owncloud/core/issues/22100

Please review @blizzz @icewind1991 @nickvergessen @rullzer @schiesbn

**Comment by icewind1991** [comment]
Looks good, works :+1:

**Comment by blizzz** [comment]
suggetion: also show the comments icon even if there are no comments, just without number. Like share button?

**Comment by PVince81** [comment]
> suggetion: also show the comments icon even if there are no comments, just without number. Like share button? 

that would needlessly clutter the UI when comments are sparse.

**Comment by blizzz** [comment]
Hm… or an action in the dropdown? But this can be adjusted when couple people tested in and we have some feedback on the UX.

:+1: code looks code and works

**Comment by jancborchardt** [comment]
Excuse the late comment, but I was on vacation last week as you know.

Instead of having this separate indicator, we should add the indicator to the 3-dot menu, where it should then be shown at the »Details« entry. Because adding this in the row will again cause long filenames to overlap. Also it doesn’t scale down to mobile.

cc @PVince81

**Comment by PVince81** [comment]
@jancborchardt mind making a ticket for this change, assign it to me. Thanks.

**Comment by PVince81** [comment]
also make sure to clarify how it looks like and what you mean with "at the "Details" entry".

**Comment by jancborchardt** [comment]
Yup, will do! Thanks a lot and sorry – bad timing with the vacation. :\

**Pull request merged**
