### PR TITLE
Properly catch whether a share is `null`

### LINKED ISSUE #15097: Data leak using orphaned share-over-link
### Steps to reproduce

I was not able to reproduce it so far.
It might have been a relict of the OC7 => OC8 upgrade.

Still there is a deep security/data leak issue:

I had shared a file with the share over link function in OC (I think it was the latest version of OC7) on my website a few weeks ago.
Later I unshared the file (I can't recall doing it through the webinterface or a mobile app or whether I just deleted the file).

Today I clicked the link that I still had on my website and unexpectedly an endless stream of data was downloaded from my OC (a download.zip accessed by a link that earlier had pointed to a shared picture).

I downloaded up to 3GB of that stream before I killed my apache out of fear.
The download.zip in the HEX editor showed terrifyingly my folder structure as well as all the files' contents.

The orphaned token of the shared link was still in the oc_share table of my database.

### Expected behaviour

Invalid share-link should display a missing file / error message.

Orphaned shared links should not exist.

### Actual behaviour

A whole stream of all my OC-users data was downloaded in a download.zip-file.

### Server configuration
**Operating system**:

Ubuntu 12.04

**Web server:**

Apache/2.4.12 (Ubuntu)

**Database:**

mysql  Ver 14.14

**PHP version:**

PHP 5.5.22-1+deb.sury.org~precise+1

**ownCloud version:** (see ownCloud admin page)

8.0.2.0

**Updated from an older ownCloud or fresh install:**

updated from latest OC7

**List of activated apps:**

Activity, Calendar, Contacts, Deleted Files, External storage support, First Run Wizard, Mozilla Sync, PDF Viewer, Pictures, Share Files, Text Editor, Updater, Versions, Video Viewer

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '---',
  'passwordsalt' => '---',
  'datadirectory' => '---',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '---',
  'dbpassword' => '---',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'trusted_domains' => 
  array (
    0 => '---',
    1 => '---',
  ),
  'secret' => '---',
  'loglevel' => 1,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

smb

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** 

none

### PR DESCRIPTION
**Pull request by LukasReschke**
Despite it's PHPDoc the function might return `null` which was not properly catched and thus in some situations the share was resolved to the sharing users root directory.

To test this perform the following steps:
- Share file in owncloud 7 (7.0.4.2)
- Delete the parent folder of the shared file
- The share stays is in the DB and the share via the sharelink is inaccessible. (which is good)
- Upgrade to owncloud 8 (8.0.2) (This step is crucial. The bug is not reproducible without upgrading from 7 to 8)
- Optional Step: Logout, Reset Browser Session, etc.
- Access the share via the old share url: almost empty page, but there is a download button which adds a "/download" to the URL.
- Upon clicking, a download.zip is downloaded which contains EVERYTHING from the owncloud directory (of the user who shared the file)
- No exception is thrown and no error is logged.

This will add a check whether the share is a valid one and also adds unit tests to prevent further regressions in the future. Needs to be backported to ownCloud 8. Will create a backport once this got reviewed and tested to avoid triple the work.

Adding a proper clean-up of the orphaned shares is out-of-scope and would probably require some kind of FK or so.

Fixes https://github.com/owncloud/core/issues/15097

cc @PVince81 @icewind1991 @karlitschek @DeepDiver1975 Please review and test properly.
cc @jnfrmarks Requires a complete retest of whether the sharing still works properly.

### CODE REVIEW

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by PVince81** [comment]
Proper cleanup would be done here: https://github.com/owncloud/core/pull/14676

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by davitol** [comment]
Tested and seems good :+1:

**Pull request merged**
