### PR TITLE
No fatal error if dstart is not set

### LINKED ISSUE #23004: Calendar doesn't support dates before Unix epoch => can't import contact birthdays
You can't create event in the calendar with the start/end date that predates Unix epoch because of the column type for oc_calendarobjects.firstoccurence and calendarobjects.lastoccurence being INT UNSIGNED. This problem is especially visible when system tries to create birthday calendar entries for "older" (born before 1970) contacts.

Modifying the type of those columns to just BIGINT resolves the problem. Using BIGINT helps with another problem of how iOS stores birthdates without a year, it assigns them year 1604 resulting in a very long timestamp like -11540880000

### LINKED ISSUE #23020: php fatal error during upgrade from 8.2.2.2 to 9.0.0.1
### Steps to reproduce
1. Upgrade from 8.2.2 to 9.0.0 (both using packages and manual results in the same error)
2. Run occ upgrade from console
3. After databases are updated, owncloud returns the following error: Call to a member function getDateTime() on null at \/var\/www\/owncloud\/apps\/dav\/lib\/caldav\/caldavbackend.php#1298

### Expected behaviour
Upgrade should finish without problems.

### Actual behaviour
Upgrade aborts due to aforementioned error

### Server configuration
**Operating system**: Debian

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.6.14-0+deb8u1

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Upgraded from 8.2.2

**Where did you install ownCloud from:** deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:** 

  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - dav: true
  - federatedfilesharing: true
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mail: 0.2.1
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - shorten: 0.0.14
  - templateeditor: 0.1

**The content of config/config.php:**

  'instanceid' => 'xxxxxxxx',
  'passwordsalt' => 'xxxxxxxx',
  'secret' => 'xxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'xxxxxxxx',
    2 => 'xxxxxxxx',
    3 => 'xxxxxxxx',
    4 => 'xxxxxxxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://xxxxxxxx/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxxxxxxx',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'asset-pipeline.enabled' => true,
  'appstore.experimental.enabled' => true,
  'maintenance' => false,
  'loglevel' => 0,
  'theme' => '',

**Are you using external storage, if yes which one:** owncloud (separate user on same instance)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 44.0.2

**Operating system:** Windows 7

#### Web server error log
[Wed Mar 09 14:01:39.747264 2016] [:error] [pid 5880] [client 212.4.225.145:45650] PHP Fatal error:  Call to a member function getDateTime() on null in /var/www/owncloud/apps/dav/lib/caldav/caldavbackend.php on line 1298

#### ownCloud log (data/owncloud.log)
{"reqId":"NCCOb0\/0UVm2jjSaGpnU","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.2.2 to 9.0.0.19","level":0,"time":"2016-03-09T12:26:57+00:00","method":"--","url":"--"}
{"reqId":"NCCOb0\/0UVm2jjSaGpnU","remoteAddr":"","app":"PHP","message":"Call to a member function getDateTime() on null at \/var\/www\/owncloud\/apps\/dav\/lib\/caldav\/caldavbackend.php#1298","level":3,"time":"2016-03-09T12:27:41+00:00$

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #23020 
fixes #23004

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@thejabok please test - THX
@twistedfall please test - THX

**Comment by DeepDiver1975** [comment]
counting as :+1: :see_no_evil: 
bildschirmfoto von 2016-03-10 08-27-44

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by DeepDiver1975** [comment]
@karlitschek requesting backport - THX

**Comment by karlitschek** [comment]
please backport :+1:

**Pull request merged**
