### PR TITLE
Allow uploading empty files

### LINKED ISSUE #19116: Uploading of 0 bytes files is not possible.
### Steps to reproduce

1. Upload an empty file (0 bytes) using the web ui.

### Expected behaviour
File is uploaded.

### Actual behaviour
File is not uploaded because it has 0 bytes.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome.

### PR DESCRIPTION
**Pull request by PVince81**
## Description

Allow upload zero sized files in the web UI.
It didn't work before because there was a check for directory uploads in browsers that don't support it, the check relied on zero file size and gave false positives when uploading files with no known mime types.
## Related Issue

Fixes https://github.com/owncloud/core/issues/19116
## Motivation and Context

Because people sometimes upload multiple files and have an empty file in the list, they want it to go through too.
## How Has This Been Tested?

Create two local empty files "test.txt" and "test.blubb". Upload both with drag and drop and the upload dialog.
Before: test.blubb doesn't go through
After: it does!
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
## Backports:
- [ ] stable8.2
- [ ] stable9
- [ ] stable9.1

Please review @SergioBertolinSG @michaelstingl @VicDeo @DeepDiver1975

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Works 👍

**Comment by VicDeo** [comment]
:+1: tested with empty files and directories

**Comment by PVince81** [comment]
I'll backport this after the releases

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/26135
stable9: https://github.com/owncloud/core/pull/26136

I think this is not critical enough for stable8.2, so I'll leave it.

**Pull request merged**
