### PR TITLE
Move \OCP\Notification to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @nickvergessen @PVince81 @DeepDiver1975 @MorrisJobke @ChristophWurst

### CODE REVIEW

**Comment by nickvergessen** [comment]
Make me happy https://github.com/owncloud/core/blob/master/.mention-bot#L17 :stuck_out_tongue_winking_eye:

**Comment by rullzer** [comment]
Done

**Comment by nickvergessen** [comment]
:+1:

**Comment by ChristophWurst** [comment]
:+1:

**Pull request merged**
