### PR TITLE
[phpunit] Fail on warnings

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
phpunit warnings shall lead to failed status on drone

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by patrickjahns — CHANGES_REQUESTED** [review]
Please also add it to other phpunit.xml files in the project - for example: `phpunit-autotest-external.xml`

What about apps / developer documentation, I think that we can/should provide a default phpunit.xml(.dist) that includes mandatory configurations

**Comment by DeepDiver1975** [comment]
> Please also add it to other phpunit.xml files in the project - for example: phpunit-autotest-external.xml

done

**Comment by DeepDiver1975** [comment]
> What about apps / developer documentation, I think that we can/should provide a default phpunit.xml(.dist) that includes mandatory configurations

I'm personally more the type of guy believing into the principle lead-by-example.
Do it properly and people will follow - developer docs are always outdated.
I never really read developer docs ...

Feel free to propose a diffferent approach.

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by patrickjahns — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport stable10 #30650 (I had already had a little look so did this)

**Pull request merged**
