### PR TITLE
Do not register sidebar panels when no sidebar

### LINKED ISSUE #19804: Can not open trashbin from within a folder
1. Freshly open the files view
2. Go into a folder
3. Click on "trashbin" link

### Expected
Trashbin opens

### Actual
Console:
```
TypeError: this._detailsView is null
```

A second click loads it correctly.

Most likely related to https://github.com/owncloud/core/pull/19647

@PVince81

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/19804

Please review @blizzz @rullzer @nickvergessen @schiesbn @icewind1991 

@karlitschek backport to 8.2.1 ?

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
No need to backport, it's not broken in 8.2.1 because the details view is loaded there?

**Comment by PVince81** [comment]
It will be broken as soon as this backport is merged for 8.2.1: https://github.com/owncloud/core/pull/19775

**Comment by icewind1991** [comment]
:+1:  looks good

**Comment by karlitschek** [comment]
:+1: backport for .1 makes sense

**Comment by PVince81** [comment]
stable 8.2: https://github.com/owncloud/core/pull/19819

**Pull request merged**
