### PR TITLE
Tests for second attempt 36107

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
I made some scenarios where the original sharer modifies the permissions of the reshare.

My first commit has scenarios that demonstrate the existing behaviour in master.

My 2nd commit adjusts those to demonstrate the corrected behaviour with PR #36159 

## Related Issue
#36107 

## How Has This Been Tested?
Local runs of added acceptance tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
@karakayasemi @PVince81 @micbar - these demonstrate that PR #36159 improves things.

Maybe just cherry-pick them into #36159 ?

**Comment by micbar** [comment]
If CI passes, yes please do.

Do we have acceptance tests where the resharer changes the permissions and cannot increase them higher than the incoming share?

**Comment by phil-davis** [comment]
> Do we have acceptance tests where the resharer changes the permissions and cannot increase them higher than the incoming share?

Yes, for example https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiShareReshare/reShare.feature#L372 and https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiShareReshare/reShare.feature#L247

**Comment by micbar** [comment]
> > Do we have acceptance tests where the resharer changes the permissions and cannot increase them higher than the incoming share?
> 
> Yes, for example https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiShareReshare/reShare.feature#L372 and https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiShareReshare/reShare.feature#L247

Great!

**Comment by phil-davis** [comment]
This has been cherry-picked into #36159

**Pull request closed without merging**
