### PR TITLE
Permit {DAV:}getlastmodified to set mtime. #15850

### PR DESCRIPTION
**Pull request by ziotibia81**
Fix https://github.com/owncloud/core/issues/15850 and permit to change mtime via DAV using PROPATCH getlastmodified

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ziotibia81 can you please add a description? What is the purpose of this change? THX

**Comment by PVince81** [comment]
Hmmm, was the change required in the Sabre library ? That's not good :frowning: 

We shouldn't change it. Maybe there's a better way ?

This was solved differently on 8.1 / master by having this in the plugin: https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/filesplugin.php#L165

Maybe a similar approach can be used, but beware that the Sabre APIs have changed so the format might be different.

**Comment by DeepDiver1975** [comment]
I'd mark this as won't fix - 8.1 will soon be released - please upgrade

**Comment by MorrisJobke** [comment]
> I'd mark this as won't fix - 8.1 will soon be released - please upgrade

I will close this now.

@ziotibia81 If you really want to get this in report back.

**Pull request closed without merging**
