### PR TITLE
run UI tests on FF57 and retire FF47

### PR DESCRIPTION
**Pull request by individual-it**
## Description
saucelabs can now run our tests with FF 57, so we should get rid of the ancient FF version

## Motivation and Context
run tests in a modern browser

## How Has This Been Tested?
run all tests https://github.com/individual-it/owncloud-core/pull/73

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
Finally! What was specially new/different that SauceLabs did? (other than the selenium version to use)

**Comment by individual-it** [comment]
I don't know, they came back to me saying selenium 3.5 works now. I tried it and it didn't work for us. So I tried again with selenium 3.4 and all is green. :see_no_evil: 
Maybe its the usage of newest geckodriver

**Comment by phil-davis** [comment]
FireFox tests on Travis have been removed completely since this PR. (part of temporarily minimizing test time and then moving tests to drone). So backport of this PR is no longer relevant.
@individual-it

**Comment by individual-it** [comment]
backport in #30436 its needed because we run FF tests in cron

**Pull request merged**
