### PR TITLE
[stable10] Backport of Fixing the transfer of child shares for transferShare

### PR DESCRIPTION
**Pull request by sharidas**
The child shares are transferred first before deleting
the parent share. If this is not done, then the child
shares are lost, which could result in loss of shares.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Backport of PR : https://github.com/owncloud/core/pull/31924

## Related Issue

https://github.com/owncloud/core/issues/31150

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sharidas** [comment]
Original PR: https://github.com/owncloud/core/pull/31924

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by sharidas** [comment]
With normal storages:
- [x] Tested based on https://github.com/owncloud/core/pull/31924#issuecomment-401319732 and it worked.
- [x] Tested with object store and it worked.

In the object store testing, tried to verify with 3 users. Tried to share folder from user1 to user2. And new folder from user3 to user1. Basically a test which does verify incoming shares are not transferred, public links are available after the share. Also the normal user shares are available too.

**Review by PVince81 — APPROVED** [review]
Thanks a lot :+1:

**Pull request merged**
