### PR TITLE
[stable10] Bump OSD_SIZE from 500 to 800

### PR DESCRIPTION
**Pull request by phil-davis**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by patrickjahns** [comment]
Not sure what you are trying to achieve - but there is no storage issue in unit tests - see the ceph docker container:
```
2018-12-01 13:50:49.411471 mon.0 [INF] pgmap v139: 152 pgs: 152 active+clean; 275 kB data, 117 MB used, 681 MB / 800 MB avail
```

**Comment by phil-davis** [comment]
Just trying different adjustments to see if anything can help it pass.
This does not help!

**Comment by patrickjahns** [comment]
> Reverting the PR that added testDeleteLargeOrphans() does get rid of the problem - so that new test induced and issue somewhere in the sequence of unit tests that make use of the object store.

Thanks for confirming - as I've stated before - if not the code path in that PR introduced the issue - most likely the unit test has introduced it as it leaves residue which triggers errors further down the line.

There is no env/infrastructure issue involved

**Comment by phil-davis** [comment]
This is not useful.

**Pull request closed without merging**
