### PR TITLE
[stable10] Update composer in stable10 with versions as at 2018-02-07

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Do:
```
composer update
```
in ``stable10`` with PHP ``5.6.33`` 

## Related Issue
This change will get ``composer.lock`` in ``stable10`` to have similar versions to what PR #30242 does to ``master``

## Motivation and Context
Lots of minor point versions of things are out-of-date in ``stable10``

## How Has This Been Tested?
CI will tell us.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
This makes the following version bumps in ``stable10``

```
doctrine/cache                         v1.6.1   v1.6.2
doctrine/common                        v2.7.2   v2.7.3
doctrine/dbal                          v2.5.12  v2.5.13
guzzlehttp/guzzle                      5.3.1    5.3.2
league/flysystem                       1.0.35   1.0.42
paragonie/random_compat                v2.0.9   v2.0.11
react/promise                          v2.5.0   v2.5.1
sabre/http                             4.2.2    4.2.3
swiftmailer/swiftmailer                v5.4.8   v5.4.9
symfony/console                        v3.2.14  v3.4.4
symfony/event-dispatcher               v3.2.14  v3.4.4
symfony/routing                        v3.2.14  v3.4.4
zendframework/zend-inputfilter         2.8.0    2.8.1
zendframework/zend-servicemanager      3.3.1    3.3.2
zendframework/zend-validator           2.10.1   2.10.2
behat/behat                            v3.3.0   v3.4.3
behat/gherkin                          v4.4.5   v4.5.1
behat/transliterator                   v1.1.0   v1.2.0
instaclick/php-webdriver               1.4.3    1.4.5
myclabs/deep-copy                      1.6.0    1.7.0
phpdocumentor/reflection-common        1.0      1.0.1
phpdocumentor/reflection-docblock      3.1.1    3.3.2
phpdocumentor/type-resolver            0.2.1    0.4.0
phpspec/prophecy                       v1.7.0   1.7.3
phpunit/php-code-coverage              4.0.7    4.0.8
phpunit/php-file-iterator              1.4.2    1.4.5
phpunit/php-token-stream               1.4.11   1.4.12
phpunit/phpunit                        5.7.19   5.7.27
phpunit/phpunit-mock-objects           3.4.3    3.4.4
sebastion/diff                         1.4.1    1.4.3    (not in master)
sensiolabs/behat-page-object-extension v2.0.1    v2.1.0
symfony/config                         v3.2.14   v3.4.4
symfony/dependency-injection           v3.2.14   v3.4.4
symfony/yaml                           v3.3.16   v3.4.4
webmozart/assert                       1.2.0     1.3.0
zendframework/zend-eventmanager        3.1.0     3.2.0
```
That will bring all the above to the same version that will be in master after PR #30242 

The exception is ``sebastion/diff`` which does not appear in the ``master`` ``composer.lock``

**Comment by phil-davis** [comment]
This should quieten ``dependabot``
After this, the diffs of ``composer.json`` between ``master`` and ``stable10`` could be reviewed, and appropriate changes be also backported to ``stable10``

**Comment by phil-davis** [comment]
Getting this stuff in sync as much as possible before moving ``master`` forward for Guzzle v6 or other "future" stuff seems to me to be "a good thing".

**Comment by phil-davis** [comment]
Hmmm - output in the Jenkins job has stopped coming after an hour or so of integration test running. Did something get killed there, but the job never got to report that it was killed?

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
