### PR TITLE
Cache app versions

### PR DESCRIPTION
**Pull request by icewind1991**
Saves a lot of filesystem operations (100+ on my instance)

[comparison](https://blackfire.io/profiles/compare/b6c82a8a-881c-4888-8b4f-f65dd25a6f26/graph)

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
nice :+1:

**Comment by MorrisJobke** [comment]
```
Test_Installer::testUpdateApp
Failed asserting that '0.9' is not equal to <string:0.9>.

/var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/tests/lib/installer.php:79
```

**Comment by icewind1991** [comment]
@PVince81 @MorrisJobke can this be merged?

**Comment by PVince81** [comment]
- [ ] update test

**Comment by PVince81** [comment]
Seems to work fine on update too :+1:

**Pull request merged**
