### PR TITLE
Allow space for federated share id search

### LINKED ISSUE #25955: Cannot share folder to a user on another server with a username containing spaces
### Steps to reproduce
1. Open ownCloud website and click to button to share a folder
2. Input a link to a user on another server (federated sharing) containg spaces, e.g. `Firstname Lastname@otherserver.com`

### Expected behaviour
The folder must be shared with the selected user.

### Actual behaviour
ownCloud does not share the folder and gives the error "no users or groups found matching `Firstname Lastname@otherserver.com` (or similar, my ownCloud is not in English).

### Server configuration
**Operating system:** raspbian on raspberry pi 3
**Web server:** apache
**Database:** postgresql
**ownCloud version:** 9.0.4

This issue has been discussed here: https://central.owncloud.org/t/federated-sharing-with-spaces-in-usernames/1878. If you need any more details, please let me know.

### PR DESCRIPTION
**Pull request by PVince81**
## Description

When providing autocompletion for the "share with" field, there is code to detect whether the entered value is a potential federated share id. This value now allows for spaces like it did in OC < 9.0.
## Related Issue

Fixes https://github.com/owncloud/core/issues/25955
## Motivation and Context

User ids allow for spaces, so spaces would appear in federated cloud ids.
## How Has This Been Tested?

Unit test and web UI test as per https://github.com/owncloud/core/issues/25955
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
## Backports required:
- [x] stable9.1
- [x] stable9

Please review @DeepDiver1975 @jvillafanez @butonic @VicDeo @owncloud/sharing @tflidd @vojeroen

### CODE REVIEW

**Comment by tflidd** [comment]
Works for me. :+1:

**Comment by jvillafanez** [comment]
code looks good 👍

**Comment by PVince81** [comment]
Thanks guys

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/25981

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/25982

**Pull request merged**
