### PR TITLE
[backport] [stable8.2] Fix shared files of deleted users, detect DN change when checking for existence on LDAP

### PR DESCRIPTION
**Pull request by blizzz**
Backport of https://github.com/owncloud/core/pull/21133 to stable8.2, look original PR for test steps.

@owncloud/ldap @davitol @alex42ka @esakol @tomcat-sdb @ckruetze @alexweirig @frankuit @MorrisJobke

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Tested case 1 - Working correctly. (Used AD)

**Comment by MorrisJobke** [comment]
Tested case 1 and it works (using LDAP)

**Comment by MorrisJobke** [comment]
:+1: from my side

**Comment by SergioBertolinSG** [comment]
Tested case 2 - Works well (AD + enforce_home_folder_naming_rule parameter)
:+1:

**Pull request merged**
