### PR TITLE
fixes #38988

### LINKED ISSUE #38988: [QA] over-eager foldername elipsis
Seen with 10.8.0 beta2

PR #38748 works into using more space for filenames, and less for meta data, when horizontal space is limited. On my adroid 10, I see a result that is half way between the before and after screenshots.

image

A very short folder name `WND` gets truncated after the first character `W...`,  whereas the folder name `beta2adminphotos` is truncated only after 12 chars. 
Sharefolder2, Sharefolder Documents, and demo_photos have exactly their last three characters replaced with '...' -- that indicates a broken algorithm.

It seems that there is a difference between filename and folder names. Filenames can use the available space 

image

Expected behavior: do not truncate without need. In the sceenhots, almost all names would have fit.

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
## Description
Fixes over-eager long file/folder names truncation

## Related Issue
https://github.com/owncloud/core/issues/38988

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
@hurradieweltgehtunter can you set the target branch to release-10.8.0 as well add this PR to the recent changelog item?

**Comment by JanAckermann** [comment]
Unfortunately the ellipsis doesn't show up anymore

image

**Comment by hurradieweltgehtunter** [comment]
grafik

is this browser related?!

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliExternalStorage-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31177/125/1

**Comment by jnweiger** [comment]
I've cherry-picked one relevant chunk:
```
--- apps/files/css/files.css.orig       2021-07-14 16:15:08.547274027 +0200
+++ apps/files/css/files.css    2021-07-14 16:15:14.971263378 +0200
@@ -408,6 +408,7 @@
        text-overflow: clip;
        max-width: 800px;
        height: 100%;
+       width: 100%;
 }
 
 .has-favorites #fileList td.filename a.name {
```
that fixes issue #38988 for me. Android 10 with google chrome.

**Pull request closed without merging**
