### PR TITLE
[backport] [stable8.1] memberOf resembles a DN as well and is actively used

### PR DESCRIPTION
**Pull request by blizzz**
Backport of https://github.com/owncloud/core/pull/19419 to 8.1

Please test and review @GreenArchon @MorrisJobke @davitol @pako81

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@davitol Can we get this tested?

**Comment by davitol** [comment]
@blizzz @MorrisJobke I think password is not need. I cannot reproduce it in stable8.1 oC version:

mysql> select * from ldap_group_mapping; 
+------------------------------------------+------------------+--------------------------------------+
| ldap_dn                                  | owncloud_name    | directory_uuid                       |
+------------------------------------------+------------------+--------------------------------------+
| cn=grupo_pa_david_0,dc=owncloudqa,dc=com | Grupo_pa_david_0 | 2CE3A13F-F928-4235-92A0-D68423C19391 |
+------------------------------------------+------------------+--------------------------------------+


screen shot 2015-10-27 at 16 39 36

**Comment by blizzz** [comment]
@DeepDiver1975 merge?

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 merge?

@blizzz There are conflicts, that need to be resolved first.

**Comment by blizzz** [comment]
> @blizzz There are conflicts, that need to be resolved first.

ha, and i thought the merge button was disabled just because it's me.

**Comment by DeepDiver1975** [comment]
rebased - and typo fixed

**Comment by DeepDiver1975** [comment]
failing jenkins jobs can be ignored

**Pull request merged**
