### PR TITLE
Use "json_encode" and "json_decode" instead of unserialize

### LINKED ISSUE #16498: Get rid of `unserialize` in LDAP caching
https://github.com/owncloud/core/blob/896130b68d4712ec9ced3561036bc435e7e5a2dc/apps/user_ldap/lib/connection.php#L205 would be way nicer to not use the unserialize if not required. Because it's really easy to do mistakes with it.

cc @blizzz Would that be possible?

### PR DESCRIPTION
**Pull request by LukasReschke**
@blizzz Please review.

Fixes https://github.com/owncloud/core/issues/16498

### CODE REVIEW

**Comment by Xenopathic** [comment]
:+1::+1::+1::+1::+1::+1::+1::+1:

**Comment by blizzz** [comment]
@LukasReschke migration?

**Comment by LukasReschke** [comment]
@blizzz As far I see this uses the memcached, if you update to a new release the caching keys will have a new prefix (including the version) and thus there is no migration required.

**Comment by blizzz** [comment]
@LukasReschke never mind. I mixed it up, overnight, with settings. I give it a practical try later, so far stuff looks good.

**Comment by MorrisJobke** [comment]
Tested and still works with LDAP. :+1:

**Comment by MorrisJobke** [comment]
@LukasReschke @blizzz Would it make sense to backport this to stable8.1 to mitigate the unserialize issue in https://github.com/owncloud/enterprise/issues/1094? Or is this too risky?

**Comment by blizzz** [comment]
@MorrisJobke if you include the other fix (the missing true), it's low risk.

**Comment by MorrisJobke** [comment]
> @MorrisJobke if you include the other fix (the missing true), it's low risk.

Sure. I just think about migration implications.

@LukasReschke After an upgrade the cache gets cleared completely, right?

**Comment by MorrisJobke** [comment]
> @LukasReschke After an upgrade the cache gets cleared completely, right?

Or better: it will use the version for cached entries and therefore not reuse the cache that was created before the update. Is this correct?

**Comment by MorrisJobke** [comment]
Regression fix: https://github.com/owncloud/core/pull/21999

**Comment by MorrisJobke** [comment]
> @MorrisJobke if you include the other fix (the missing true), it's low risk.

https://github.com/owncloud/core/pull/22632

**Pull request merged**
