### PR TITLE
[Stable8.1] Update parent when moving share into recieved share

### PR DESCRIPTION
**Pull request by rullzer**
Backport of  #20989 for #20769

Approved in https://github.com/owncloud/core/pull/20989#issuecomment-163208386

CC: @PVince81 @schiesbn

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
When moving test.txt into sub with user1, the spinner keeps spinning forever.

**Comment by PVince81** [comment]
The reason for the stuck spinner is that the MOVE operation returns a 500:
```
{"reqId":"uKURRhvszk3g3P5CQ92\/","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 3 passed to OC\\Hooks\\BasicEmitter::listen() must be callable, array given, called in \/srv\/www\/htdocs\/owncloud\/apps\/files\/ajax\/scan.php on line 50 and defined at \/srv\/www\/htdocs\/owncloud\/lib\/private\/hooks\/emittertrait.php#36","level":3,"time":"2015-12-10T10:13:59+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=oFbl4cERFYyL4Eb6gwqAlvm01%2FJPtY"}
{"reqId":"w4s5qpzPLNcpLG5+1cUw","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to undefined method OC\\Server::getMountManager() at \/srv\/www\/htdocs\/owncloud\/apps\/files_sharing\/lib\/updater.php#85","level":3,"time":"2015-12-10T10:14:02+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/move.php"}
```

**Comment by PVince81** [comment]
@rullzer please have a look. Maybe we didn't have this mount manager method yet in 8.1 ? CC @icewind1991

**Comment by rullzer** [comment]
Mmmm did I test the wrong branch, I could have sworn this was working...

**Comment by rullzer** [comment]
mmm yes it seems I did. Since the querybuilder is also not yet available there...

**Comment by rullzer** [comment]
Ok this looks better

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by SergioBertolinSG** [comment]
:+1: Working fine now.

**Pull request merged**
