### PR TITLE
fix browser compatibility issue for element.closest

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #17490

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Problem with the entropy?!? :confused: 
```
PHP Fatal error:  Maximum execution time of 3600 seconds exceeded in /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/MicroTime.php on line 100
```

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@PVince81 @rullzer @Xenopathic @owncloud/designers Mind to review?

**Comment by jancborchardt** [comment]
@raimund-schluessler @Henni can you double-check since you were involved in the original PR? :)

**Comment by raimund-schluessler** [comment]
Works for me :+1:

**Comment by davitol** [comment]
:+1: Works for me too in Safari and IE11
OC server: owncloud-daily-stable8.1.tar.bz2 (22-jul) version":"8.1.0.8","versionstring":"8.1.0

**Pull request merged**
