### PR TITLE
ucwords does not support delimiter before 5.4.32

### LINKED ISSUE #22849: Comments are not kept when you log out the account
### Steps to reproduce

1. In the sidebar, write a comment about the file. (The comment is shown)
2. Logout from oC
3. Login again

### Expected behaviour

The comment should be shown and kept

### Actual behaviour

The comment is not available

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0.0 RC1 (testing)

### Logs

```
{"reqId":"AxGf1oU9S58cWNB+\/PNR","remoteAddr":"82.159.139.58","app":"PHP","message":"ucwords() expects exactly 1 parameter, 2 given at \/opt\/owncloud\/lib\/private\/comments\/comment.php#365","level":3,"time":"2016-03-04T10:26:29+00:00"}
```

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

screen shot 2016-03-04 at 11 33 59

screen shot 2016-03-04 at 11 34 07

### PR DESCRIPTION
**Pull request by nickvergessen**
Fixes #22849

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/22849

Testing now...

**Comment by nickvergessen** [comment]
Fixed since 5.4.32: https://3v4l.org/ftEAs

**Comment by PVince81** [comment]
Tested on PHP 5.5.14, works :+1: 

The comments list can now properly be loaded again.

Second review @blizzz ?

@karlitschek backport to 9.0 ? Without this the comments feature is broken for PHP <= 5.5.16

**Comment by blizzz** [comment]
splendid, thx @nickvergessen  :+1:

**Comment by nickvergessen** [comment]
its broken on PHP <= 5.4.31, 5.5.0 < PHP <= 5.5.15,

Which means problem users didn't update their minor version since Aug. 2014, that is when 5.5 and 5.4 both received the update ;)

**Comment by davitol** [comment]
:+1: WFM

**Comment by karlitschek** [comment]
argh. please backport

**Comment by MorrisJobke** [comment]
@nickvergessen Could you please create the backport PR?

**Comment by nickvergessen** [comment]
No: https://github.com/owncloud/core/issues/22852

**Pull request merged**
