### PR TITLE
Clear cached app info before installing an app

### LINKED ISSUE #27949: [10.0.1RC3] after upgrade downloaded apps have version 'false'
### Steps to reproduce
1. intall oc 9.1.x
2. upgrade to 10.0.1RC3
3. run x sudo -u www-data php /var/www/oc/owncloud-9.1-10x/occ app:list

### Expected behaviour
get a list of installed apps with the version

### Actual behaviour
version for apps downloaded from the market is true:

Enabled:
  - activity: true
  - admin_audit: 0.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - enterprise_key: 0.1.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: true
  - files_sharing: 0.10.0
  - files_texteditor: true
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.4.0
  - firstrunwizard: 1.1
  - gallery: true
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - theme-enterprise: 1.0.0
  - updatenotification: 0.2.1
  - user_ldap: true
  - windows_network_drive: 0.6.0
  - workflow: 0.2.3
Disabled:
  - announcementcenter
  - encryption
  - external
  - files_antivirus
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - theme-example
  - user_external
  - user_shibboleth

cc @DeepDiver1975 @IljaN

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Related Issue
fixes https://github.com/owncloud/core/issues/27949

## How Has This Been Tested?
- install texteditor via market app
- double check the version as printed in console of ./occ a:l

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Tested, works and code makes sense 👍

**Comment by butonic** [comment]
👍 works!
```
➜  owncloud-9.1-10x patch -p1 < 27953.diff
patching file lib/private/App/AppManager.php
patching file lib/private/Installer.php
patching file lib/private/legacy/app.php
➜  owncloud-9.1-10x sudo -u www-data php /var/www/oc/owncloud-9.1-10x/occ upgrade 
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 0.8.2
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.2
Updating <gallery> ...
Updated <gallery> to 16.0.2
Updating <user_ldap> ...
Updated <user_ldap> to 0.9.0.1
Updating <activity> ...
Updating <dav> ...
Updated <dav> to 0.2.9
Drop old database tables

 Done
 28/28 [============================] 100%
Fix permissions so avatars can be stored again
 Done
 2/2 [============================] 100%
Move user avatars outside the homes to the new location
 Done
 1/1 [============================] 100%
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Reset log level
➜  owncloud-9.1-10x sudo -u www-data php /var/www/oc/owncloud-9.1-10x/occ app:list
Enabled:
  - activity: 2.3.4
  - admin_audit: 0.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - enterprise_key: 0.1.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.4.0
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - theme-enterprise: 1.0.0
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0.1
  - windows_network_drive: 0.6.0
  - workflow: 0.2.3
Disabled:
  - announcementcenter
  - encryption
  - external
  - files_antivirus
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - theme-example
  - user_external
  - user_shibboleth
```

**Comment by butonic** [comment]
the mysql docker did not come up in jenkins

**Comment by PVince81** [comment]
Rebased. COME ON, JENKINS!!!

**Comment by PVince81** [comment]
IT WAS ABOUT TIME!

**Pull request merged**
