### PR TITLE
Add "Reply-To" support for sharing mails as well as refactor code and add unit-tests

### LINKED ISSUE #10545: Set the sender mail address by user
I don't see any options to set the real owncloud user mail address as sender address for shares…

The main 
"mail_from_address" => "owncloud",
is ok for the password recovery option, but receiving a share mail with the full mail address from the sharing user would me more useful.

Is this already a milestone feature or a known "problem/issue" ?

Cheers
Christian

### PR DESCRIPTION
**Pull request by LukasReschke**
Current sharing mails set no "Reply-To" header, this means that when a sharing mail is sent and somebody clicks reply it will end-up in /dev/null and this has lead to multiple complaints.

Thus this pull request does:
1. Add "Reply-To" support to mailer class 
2. Refactored the sharing notification mail class a bit and added unit-tests for it where possible
3. When a sharing notification mail is sent and the user has specified a mail address it it set as "Reply-To" header, so when somebody clicks "Reply" in their mail program the reply will be sent to the actual user.
4. The "From" field displayname is now "$user via ownCloud" (where ownCloud uses the name from the theme), this is what most other providers do as well and at least I find it way easier to filter for mails then etc…

@karlitschek @DeepDiver1975 Please sort out for which releases we want this. That said, for me this is a new feature and not a bug fix and thus I'd advise against any kind of hacky backport. (which with the old API will also not be able easily)

@MTRichards @gig13 @karlitschek 

Replaces https://github.com/owncloud/core/pull/13855, fixes https://github.com/owncloud/core/issues/10545 and probably some other issues

### CODE REVIEW

**Comment by PVince81** [comment]
Tested with link share, works well.

Maybe we should also add the sender's display name in the Reply-To field ?

**Comment by PVince81** [comment]
Other than that this looks good :+1:

**Comment by MorrisJobke** [comment]
Tested and it works as intended. Also the code looks good

:+1:


@karlitschek @DeepDiver1975 Decide if this should go into 8.1 or 8.2

**Comment by karlitschek** [comment]
Looks straight forward enough to put it into master/8.1
:+1: 
Not a bugfix so no backport.

**Comment by jcfischer** [comment]
@karlitschek please reconsider backport - we have exactly the same problem with our users replying to mails.

**Comment by jcfischer** [comment]
also, I would argue that this is indeed a bug! (I will file a ticket if necessary ;) )

**Comment by karlitschek** [comment]
@jcfischer Interestingly enough a ticket actually helps with this decision :-)
@LukasReschke Can you backport please? :-)

**Comment by jcfischer** [comment]
@karlitschek - ticket filed

**Comment by LukasReschke** [comment]
> @LukasReschke Can you backport please? :-)

As I stated this cannot be easily backported but we can add a completely not unit-tested and completely static hack to the older version…

That said I'd really appreciate some guidelines what we consider as "critical bug" now. Let's discuss this on tuesday.

**Comment by jcfischer** [comment]
@LukasReschke I'm totally fine with a not unit-tested, static hack to the old version. I would have to do it myself if it doesn't come from you

**Comment by LukasReschke** [comment]
I'm fine with doing it – was just the usual me ranting on Sundays. No worries ;-) – PR coming in a few minutes :-)

**Comment by jcfischer** [comment]
awesome! and no - it's not a critical bug per se, but it sure as hell annoys our support people, because the replies to those mails end up in our request tracker...

**Comment by LukasReschke** [comment]
> it's not a critical bug per se, but it sure as hell annoys our support people

And we thought we just re-invented switchboard operator 2.0 ;-)

> awesome! 

Sure - we all are. And if you want to increase your awesomeness level even further you could review and test https://github.com/owncloud/core/pull/15558, well, more test, don't look at the source because it is a huge hack ;-)

The same patch should btw. also apply against stable7 but naïvely and optimistically that I am I assumed just stable8 :see_no_evil:

**Pull request merged**
