### PR TITLE
[Stable10] test check statusphp

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Backport of https://github.com/owncloud/core/pull/29265

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@SergioBertolinSG the Jenkins had a problem with a Jenkins restart that happened. I rebased this so that the CI will start again. Maybe it will pass in a few hours???

**Comment by phil-davis** [comment]
and rebased again to see if Jenkins will last the distance this time.

**Comment by phil-davis** [comment]
Jenkins fails because of:
```
16:27:30   Scenario: Status.php is correct                                       # /var/lib/jenkins/workspace/owncloud-core_core_PR-29296-AIKVVJCJWZPZ4MQBZ7AXKLNPKRJASD4AFJEAG2Q2TMG33FVLFMSA/tests/integration/features/status.feature:3
16:27:30 [Mon Oct 23 16:27:30 2017] ::1:40212 [200]: /status.php
16:27:30     When requesting status.php                                          # FeatureContext::getStatusPhp()
16:27:31     Then the status.php with versions fixed responded should match with # FeatureContext::statusPhpRespondedShouldMatch()
16:27:31       """
16:27:31       {"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"$CURRENT_VERSION","versionstring":"$CURRENT_VERSION_STRING","edition":"Community","productname":"ownCloud"}
16:27:31       """
16:27:31       Failed asserting that two strings are equal.
16:27:31       --- Expected
16:27:31       +++ Actual
16:27:31       @@ @@
16:27:31       -'{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.4.0","versionstring":"10.0.4","edition":"Community","productname":"ownCloud"}'
16:27:31       +'{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.4.0","versionstring":"10.0.4 beta1","edition":"Community","productname":"ownCloud"}'
```
The substitution of ``$CURRENT_VERSION_STRING`` does not have the "beta1" on the end. But actually I cannot find "CURRENT_VERSION_STRING" anywhere other than in the integration tests. How is that variable created.substituted??? My grep and PHPstorm search skills have eluded me.

@SergioBertolinSG @PVince81

**Comment by SergioBertolinSG** [comment]
@phil-davis that string is not really a variable, it is a fake variable to make clear that there is a substitution. I used "x.x.x.x" but after review it was suggested to show it this way.

**Comment by SergioBertolinSG** [comment]
If 0ccc3da works it should be forward ported to master.

**Comment by phil-davis** [comment]
Forward port of last commit is in PR #29350 
When CI for that passes, we can merge that and also merge this stable10 PR.

**Pull request merged**
