### PR TITLE
Moving encryption_dummy to the apps repo

### LINKED ISSUE #15950: Do not ship dummy encryption test module
### Steps to reproduce

1. Install 8.1
2. Go to not enabled apps
3. Scroll down to the bottom for the encryption apps

### Expected behaviour

No dummy modules should be shipped

### Actual behaviour

There is a dummy test module 

### Server configuration

ownCloud Enterprise Edition 8.1 alpha 2 (testing)

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #15950

new location https://github.com/owncloud/apps/pull/2052

@karlitschek @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
...to the app graveyard :see_no_evil: ;)

**Comment by nickvergessen** [comment]
:+1: 
I hope we don't use it in tests

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
@morrisjobke shouldn't be a graveyard. maybe developers should care more about this repo ;-)

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
> @morrisjobke shouldn't be a graveyard. maybe developers should care more about this repo ;-)

@karlitschek Was just kidding, but sometimes it feels like nobody really cares about stuff there :'(

**Comment by karlitschek** [comment]
@MorrisJobke I agree with this statement :-)

**Pull request merged**
