### PR TITLE
[stable8.2] Use IRequest's `getScriptName` functionality instead of $_SERVER

### PR DESCRIPTION
**Pull request by LukasReschke**
Proposed backport of https://github.com/owncloud/core/pull/19954

@karlitschek ACK?

### CODE REVIEW

**Comment by LukasReschke** [comment]
Tested by @R0ckweb at https://github.com/owncloud/core/issues/19901#issuecomment-149971237

**Comment by LukasReschke** [comment]
Tested by @maphy-psd at https://github.com/owncloud/core/issues/19901#issuecomment-149974664

**Comment by LukasReschke** [comment]
Tested by @bubbelb at https://github.com/owncloud/core/issues/19901#issuecomment-149979141

**Comment by rullzer** [comment]
Tested using the steps in  https://github.com/owncloud/core/pull/19954#issue-112618110
Works. :+1:

**Comment by LukasReschke** [comment]
@DeepDiver1975 Merge please.

**Pull request merged**
