### PR TITLE
Expand area filename area to min size  in file list

### LINKED ISSUE #39591: Folders with very short names are hard to open in Web UI
Seen in 10.9.0 RC1

* at the web UI create a folder namend 'I' 
* click slightly left if the I, the checkbox toggles.
* click slightly right of the I, the details sidebar opens
image

The mousepointer in this position is already too far to the left, although it is only 2 or 3 pixels off.
To the right, one pixel off is already too much. On a thin letter I, the active area seems to be only 3 or 4 pixels wide.

Expected behaviour:
* the active area should be padded left and right, so that very short names still have a sufficiently large target area.
* The mouse should give visual feedback when crossing the border between checkbox and name. Maybe a two pixel inactive gap in between or a different shape?

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
This is a cherry-pick of #39592 from `master`.
The issue was raised in 10.9.0 testing. Maybe we want it in 10.9.0?

I have made this PR so that CI gets run and this is ready to merge if wanted.

## Related Issue
- Fixes #39591 

## How Has This Been Tested?
See master PR #39592 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiWebdavLocksUnlock-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34028/91/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliLocalStorage-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34029/115/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToRoot1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34029/58/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIMobileSize-3-1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34033/167/1

**Review by jnweiger — APPROVED** [review]
Cool. thanks!

**Pull request merged**
