### PR TITLE
Convert error and hint to string before writing to the output

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://mailman.owncloud.org/pipermail/devel/2015-April/001184.html

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@karlitschek we shall backport this - issue was reported on 8.0.3RC2

**Comment by nickvergessen** [comment]
What other type can those two be, I can't seem to create a problem?

**Comment by karlitschek** [comment]
nice :+1:  backport is fine for 8.0.3

**Comment by nickvergessen** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> What other type can those two be, I can't seem to create a problem?

for the record - these are instances of our l10n string class which require explicit cast to string

**Pull request merged**
