### PR TITLE
Don't show "report this to the community" when the upgrade is unsuppo…

### LINKED ISSUE #21367: Remove wrong/misleading text if major version was skipped.
There is currently a wave of duplicate created issues about the "Exception: Updates between multiple major versions and downgrades are unsupported" message here at github.

I think a main problem here is, that the text afterwards is telling "The update was unsuccessful. Please report this issue to the ownCloud community". This is plainly wrong as that issue don't need to be reported here, instead the user just needs to do a correct upgrade path.

### PR DESCRIPTION
**Pull request by MorrisJobke**
…rted
- fixes #21367 

cc @RealRancor @nickvergessen @PVince81 @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Should we maybe add a link to the forum post that explains this issue? Or something in our documentation?

**Comment by MorrisJobke** [comment]
> Should we maybe add a link to the forum post that explains this issue? Or something in our documentation?

Feel free to hijack ;)

**Comment by LukasReschke** [comment]
> Feel free to hijack ;)

https://github.com/owncloud/core/commit/019f24db614f00fe5f66b3d267d2c286526d018e

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@LukasReschke I moved the URL out of the translated string. ;)

**Comment by MorrisJobke** [comment]
Beside that your change works fine.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
