### PR TITLE
Do not set response status in CLI in case of error

### LINKED ISSUE #23031: Call to a member function getRequest() on null
### Steps to reproduce
1. Replace owncloud-Folder with 9.0.0 Folder
2. Tried upgrade via "sudo -u apache php ./occ upgrade"

### Expected behaviour
Upgrade should go on

### Actual behaviour
PHP Fatal error:  Call to a member function getRequest() on null in /var/www/html/owncloud/lib/private/response.php on line 77

### Server configuration
**Operating system**: Centos 7.2

**Web server:** Apache 2.4.6

**Database:** 5.5.44-MariaDB

**PHP version:** PHP 5.6.18

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** 8.2.3

**Where did you install ownCloud from:** Manual

**List of activated apps:**

Enabled:
  - activity: 2.1.4
  - bookmarks: 0.6
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - files: 1.2.1
  - files_antivirus: 0.8.0.1
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
  - galleryplus: 14.4.0
  - news: 7.1.2
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - updater: 0.6
Disabled:
  - announcementcenter
  - calendarplus
  - contactsplus
  - encryption
  - external
  - files_videoviewer
  - gallery
  - templateeditor
  - user_external
  - user_ldap

**The content of config/config.php:**
```json
{
    "system": {
        "instanceid": "oct8eeegq0jz",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.thielking-vonessen.de",
            "owncloud.thielking-vonessen.de"
        ],
        "datadirectory": "\/srv\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.thielking-vonessen.de",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "dbname": "db_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "log_type": "owncloud",
        "logfile": "\/srv\/owncloud\/data\/owncloud.log",
        "loglevel": 1,
        "logtimezone": "Europe\/Berlin",
        "cron_log": true,
        "log_rotate_size": 104857600,
        "installed": true,
        "mail_smtpmode": "php",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "activity_expire_days": "30",
        "mail_from_address": "owncloud",
        "mail_domain": "thielking-vonessen.de",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/owncloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "appstore.experimental.enabled": true,
        "default_language": "de",
        "asset-pipeline.enabled": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.1.4",
            "types": "filesystem"
        },
        "announcementcenter": {
            "enabled": "no",
            "installed_version": "1.0.2",
            "ocsid": "173921",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "794"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "0.6",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "0.8.2",
            "ocsid": "168707",
            "types": ""
        },
        "calendarplus": {
            "enabled": "no",
            "installed_version": "1.1.1",
            "ocsid": "170560",
            "types": ""
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "0.5.0.0",
            "ocsid": "168708",
            "types": ""
        },
        "contactsplus": {
            "enabled": "no",
            "installed_version": "1.0.9",
            "ocsid": "171237",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "installedat": "1449586863.1978",
            "lastcron": "1457533390",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastupdatedat": "1457533290",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_calendarplus": "calendarplus\/share.php",
            "public_calendarplusevent": "calendarplus\/shareevent.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "files_sharing\/publicwebdav.php",
            "remote_caldav": "calendar\/appinfo\/remote.php",
            "remote_calendar": "calendar\/appinfo\/remote.php",
            "remote_calendarplus": "calendarplus\/appinfo\/remote.php",
            "remote_carddav": "contacts\/appinfo\/remote.php",
            "remote_contacts": "contacts\/appinfo\/remote.php",
            "remote_contactsplus": "contactsplus\/appinfo\/remote.php",
            "remote_files": "files\/appinfo\/remote.php",
            "remote_webdav": "files\/appinfo\/remote.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "yes",
            "shareapi_default_expire_date": "no",
            "shareapi_enforce_links_password": "yes",
            "shareapi_exclude_groups": "yes",
            "shareapi_exclude_groups_list": "[\"fisi13\"]",
            "shareapi_expire_after_n_days": "30"
        },
        "documents": {
            "converter": "local",
            "enabled": "yes",
            "installed_version": "0.11.1",
            "ocsid": "168711",
            "types": ""
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_chunk_size": "1024",
            "av_cmd_options": "",
            "av_host": "",
            "av_infected_action": "only_log",
            "av_mode": "socket",
            "av_path": "\/usr\/bin\/clamscan",
            "av_port": "0",
            "av_socket": "\/var\/run\/clamd.scan\/clamd.sock",
            "enabled": "yes",
            "installed_version": "0.8.0.1",
            "ocsid": "157439",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "0.3.0",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "owncloud,smb,\\OC\\Files\\Storage\\SMB_OC"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.7",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "9": "1450424459.3075",
            "enabled": "yes",
            "installed_version": "0.7.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.0",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.7.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "14.2.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "yes",
            "installed_version": "14.4.0",
            "ocsid": "169116",
            "types": ""
        },
        "news": {
            "enabled": "yes",
            "installed_version": "7.1.2",
            "ocsid": "168040",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "filesystem"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "filesystem"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "templateeditor": {
            "enabled": "[\"admin\",\"home\"]",
            "installed_version": "0.1",
            "types": ""
        },
        "updater": {
            "enabled": "yes",
            "installed_version": "0.6",
            "types": ""
        }
    }
}
```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox 38.6.0

**Operating system:** Scientfic Linux 7.2

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/23031

Please review @icewind1991 @LukasReschke @rullzer @MorrisJobke @nickvergessen

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek @PVince81 Backport request because the initial issue was scheduled for 9.0.1

**Comment by PVince81** [comment]
It's not critical, it was an admin error.
However it helps finding out what went wrong, so backport should be ok.

**Comment by karlitschek** [comment]
makes sense. please backport :+1:

**Comment by nickvergessen** [comment]
Backport in https://github.com/owncloud/core/pull/23071

**Comment by inducer** [comment]
FWIW, this fix is insufficient. I just encountered a `Call to a member function getRequest() on null in response.php` when running through nginx. Not sure why, but this was obscuring another error message for no good reason. Perhaps you shouldn't just check for being in a CLI, but rather whether a request object is available...?

**Comment by nickvergessen** [comment]
Well anything that is not CLI should have a request?!

**Comment by inducer** [comment]
What I'm saying is that--somehow--something that *was* a web request ended up running into this with `getRequest()` returning `null`.

**Comment by nickvergessen** [comment]
Well then we need to figure out how it happened to not have a request, instead of simply ignoring it.

**Pull request merged**
