### PR TITLE
Same name devices are not allowed

### LINKED ISSUE #24778: Prevent device tokens with same name
From https://github.com/owncloud/core/pull/24703#issuecomment-220575223:

> bug? I can create several devices with the same name

Maybe we should prevent it or at least warn the user as they then see 
### Steps to reproduce
1. Go to personal settings once #24703 is merged
2. Create device token 'my phone'
3. Create device token 'my phone'
### Expected behaviour

See a warning
### Actual behaviour

I can create multiple tokens with the same name

cc @PVince81

### PR DESCRIPTION
**Pull request by virajparimi**
## Description

The fix does not allow user to create a new device token with a name that has already been used by that user.

## Related Issue

Fixes [#24778](https://github.com/owncloud/core/issues/24778)

## How Has This Been Tested?

Tested in chrome, Ubuntu 14.04.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by viraj96** [comment]
@PVince81 @phisch  Can you guys take a look at this?

**Comment by viraj96** [comment]
Don't know why it seems to fail a test. It works perfectly fine on my computer. Here is a small demo 

myimage

Does any error pop up in your setup?

**Comment by DeepDiver1975** [comment]
May I propose to add a unique index on the column?
In this case we save a query and can simply react on the duplicate key exception as thrown by the database layer.

THX

**Comment by phisch** [comment]
Did @DeepDiver1975's recommended solution in #27587 since this pr seems inactive.

**Pull request closed without merging**
