### PR TITLE
Show storage full warning for shared storages temporary

### LINKED ISSUE #18208: Quota warning in shared folder don't disappear after leaving shared folder
### Steps to reproduce

1. Alice uses 95% of her quota
2. Alice shares folder with Bob
3. Bob opens Alices shared folder ==> notification: "Storage of Alice is almost full (95%)" (on top)
4. Bob leaves Alices shared folder ==> notification don't disappear
5. Bob needs to fully reload the page to get rid of the notification

files - owncloud - quota

### Expected behaviour

Quota notification should disappear after leaving the quota limited folder.

### Actual behaviour

Quota notification stays forever.

### Server configuration

**ownCloud version:**
oC 8.1.0

**Updated from an older ownCloud or fresh install:**
fresh install

### Client configuration

**Browser:**
Chrome 44

**Operating system:**
Mac OS X

@MorrisJobke 

00003624

### PR DESCRIPTION
**Pull request by MorrisJobke**
- removed the setDefault call because then it will always be
  reshown
  - was added with ba475d486258c0b7ea86cd766814053df6c69170
- fixes #18208 

cc @DeepDiver1975 you added the `setDefault`

@PVince81 @michaelstingl Review please

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@Xenopathic @Henni @owncloud/designers Mind to review this?

**Comment by jancborchardt** [comment]
Looks good :+1:

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
@MorrisJobke what backports would be required for this ?
CC @karlitschek

**Comment by MorrisJobke** [comment]
@PVince81 @karlitschek I would like to backport this to stable8.1 because we added it there #16771

**Comment by karlitschek** [comment]
Backport is fine with me. :+1:

**Comment by MorrisJobke** [comment]
Backport is in #18288

**Pull request merged**
