### PR TITLE
Remove unneeded private wrapper methods

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @rullzer @nickvergessen @LukasReschke @DeepDiver1975 
- [x] send mail about this to ML (once merged)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Because OC_Helper is one of the oldest classes there is a high chance that this used out there in the wild by some apps - please drop a mail to the ML - THX

**Comment by MorrisJobke** [comment]
> Because OC_Helper is one of the oldest classes there is a high chance that this used out there in the wild by some apps - please drop a mail to the ML - THX

I will do.

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
> I will do.

@MorrisJobke did you ? :smile: 
(link to mail archive could be nice)

**Comment by MorrisJobke** [comment]
> @MorrisJobke did you ?

I will do once this is merged ;)

**Comment by LukasReschke** [comment]
Go go go go go 😉

**Comment by MorrisJobke** [comment]
> send mail about this to ML (once merged)

https://mailman.owncloud.org/pipermail/devel/2016-May/002485.html

**Pull request merged**
