### PR TITLE
Use OCP classes as much as possible in files_external

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
To progress towards #4774 , I've modified files_external so that it uses OCP as much as is possible with the current public interfaces.

Also makes the code slightly cleaner and easier to work with in unit tests.

cc @DeepDiver1975 @rullzer @PVince81 @icewind1991

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by rullzer** [comment]
Looks good! :+1: 
Lets see what Jenkins has to say :)

**Comment by Xenopathic** [comment]
Should we merge for oC 8.1? @DeepDiver1975

**Comment by MorrisJobke** [comment]
I rebased this to invoke new CI run.

**Comment by DeepDiver1975** [comment]
I'm going to revert this - please resubmit with externals storage tests not failing - THX

**Comment by Xenopathic** [comment]
Eek, I wonder what happened. Investigating.

**Comment by DeepDiver1975** [comment]
> Eek, I wonder what happened. Investigating.

no worries - shit happens

**Comment by Xenopathic** [comment]
Right, it looks like (for some reason) the UserManager cannot find the user passed in to the files_external code, so it returns null, triggering the error when `getHome()` is called on it. The old `OC_User::getHome()` code checks for null, and returns what it hopes is a valid home path if the user cannot be found. IMHO this is extremely dangerous, as the user might not even exist on the system.

@PVince81 @icewind1991 @DeepDiver1975 What should we do? Emulate the old behaviour and guess? Or bomb out with some sort of UserNotFound exception?

**Pull request merged**
