### PR TITLE
[WIP] Refactor shared storage

### PR DESCRIPTION
**Pull request by icewind1991**
Since the removal of the Shared folder in oc7 the logic of the shared storage and cache can be greatly simplified.

This replaces the shared storage with a combination of 2 generic storage and cache wrappers
- `\OC\Files\Storage\Wrapper\Jail`: limits all access of the storage to a specific folder
- `\OC\Files\Storage\Wrapper\PermissionsMask`: applies a permissions mask on top of a storage

Together they form 99% of the logic behind a share (a sub directory of storage with limited permissions) and also allow dropping the `ReadOnlyWrapper` previously in place.

Overall this drastically reduces the amount of logic for shared storages which results in a nice performance increase.
On my local test instance this reduces the time needed for a WebDAV upload to a shared folder with ~120ms and drops the number of database queries by 103

TODO:
- [x] Adjust unit tests
- [x] Mount any storage inside a shared folder for the share recipient

cc @DeepDiver1975 @PVince81 @schiesbn

### CODE REVIEW

**Comment by PVince81** [comment]
Looking into fixing https://github.com/owncloud/core/issues/10299.
I debugged into `$storage->getPermissions()` and it does gets to the source storage. But still, permissions are stored as 15 in the database instead of 31 as it would with my quick and dirty fix for OC 7: https://github.com/owncloud/core/pull/13347

**Comment by PVince81** [comment]
Ok got it. The problem is that even though the source storage returns 31, the permissions mask is applied so it becomes 15. We need to fix this.
Whenever we use the scanner, we need to get the real unmasked permissions instead.
And that would be the correct fix for https://github.com/owncloud/core/issues/10299

**Comment by PVince81** [comment]
- [ ] scanner must get unmasked permissions in `scanFile` / `getData` from source storage when operating on a SharedStorage

**Comment by PVince81** [comment]
:bell: sounds like it's time to continue this :smile:

**Comment by DeepDiver1975** [comment]
If I'm not mistaken we need encryption as storage wrapper first. Right? @schiesbn @th3fallen @icewind1991 thx

**Comment by PVince81** [comment]
From what I remember this worked well already with a few bugs. Not sure if it depends on encryption storage wrapper. @icewind1991 ?

**Comment by PVince81** [comment]
Do you think you'll be able to finish this a few weeks before release ? (to get enough testing)

If not, let's defer.

**Comment by MorrisJobke** [comment]
@icewind1991 ping

**Comment by jospoortvliet** [comment]
We're past feature freeze, right, this should target 8.2?

**Comment by jospoortvliet** [comment]
Darth Vader is VERY angry ;-)

**Comment by PVince81** [comment]
@icewind1991 reminder to try and have this early in 8.2 :smile:

**Comment by PVince81** [comment]
@icewind1991 another reminder to continue this so we can have early in 8.2

**Comment by MorrisJobke** [comment]
> @icewind1991 another reminder to continue this so we can have early in 8.2

Ping? Defer to 9.0?

**Comment by icewind1991** [comment]
Defer

**Comment by MorrisJobke** [comment]
@icewind1991 Can we get this in? @rullzer is maybe also happy about this ;9

**Comment by icewind1991** [comment]
Waiting for @rullzer sharing work before continuing with this

**Comment by MorrisJobke** [comment]
> Waiting for @rullzer sharing work before continuing with this

Ah okay. If this is the better approach I'm fine with it :)

**Comment by jospoortvliet** [comment]
Isn't the sharing work by @rullzer in? The basics, at least...

**Comment by rullzer** [comment]
@jospoortvliet baby steps ;)

**Comment by PVince81** [comment]
Moving this major refactoring to 9.1, if it still makes sense @icewind1991 ?

CC @carlaschroder

**Comment by rullzer** [comment]
Closing this for now.
But keeping a reminding in #22209

**Pull request closed without merging**
