### PR TITLE
[3rdparty] Bump doctrine/dbal deps

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/230

@DeepDiver1975 should we run upgrade tests again like for https://github.com/owncloud/core/pull/20045 ?

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 should we run upgrade tests again like for #20045 ?

yes

**Comment by rullzer** [comment]
@jvillafanez could you run the upgrade tests again like you did in https://github.com/owncloud/core/pull/20045? Thanks.

**Comment by jvillafanez** [comment]
Same as last time, mysql, sqlite and postgresql pass, but oracle fails with the same error as in #20045

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by rullzer** [comment]
Bumped ref

**Comment by MorrisJobke** [comment]
Tested and still works :+1:

**Pull request merged**
