### PR TITLE
Properly set exception in FailedStorage

### LINKED ISSUE #18299: when smb connection is dropped it break syncing for all local storage
I turned off a file server for maintenance and have noticed that if your file connection is lost it will break syncing for all storage. I have my owncloud data folder, a local folder and an smb connection connected to my owncloud.

I also got this error in admin:
Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken.

```
Exception: {"Message":"","Code":0,"Trace":"
#0 \/opt\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Connection.php(37): Icewind\\SMB\\Connection->checkConnectionError('Connection to f...')\n
#1 \/opt\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(346): Icewind\\SMB\\Connection->read()\n
#2 \/opt\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(122): Icewind\\SMB\\Share->execute('allinfo \"\"')\n
#3 \/opt\/owncloud\/apps\/files_external\/lib\/smb.php(102): Icewind\\SMB\\Share->stat('\/')\n
#4 \/opt\/owncloud\/apps\/files_external\/lib\/smb.php(272): OC\\Files\\Storage\\SMB->getFileInfo('')\n
#5 \/opt\/owncloud\/lib\/private\/files\/storage\/common.php(90): OC\\Files\\Storage\\SMB->filetype('')\n
#6 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(98): OC\\Files\\Storage\\Common->is_dir('')\n
#7 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(98): OC\\Files\\Storage\\Wrapper\\Wrapper->is_dir('')\n
#8 \/opt\/owncloud\/lib\/private\/files\/cache\/watcher.php(90): OC\\Files\\Storage\\Wrapper\\Wrapper->is_dir('')\n
#9 \/opt\/owncloud\/lib\/private\/files\/view.php(1182): OC\\Files\\Cache\\Watcher->checkUpdate('', Array)\n
#10 \/opt\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php(148): OC\\Files\\View->getFileInfo('Video')\n
#11 \/opt\/owncloud\/lib\/private\/connector\/sabre\/custompropertiesbackend.php(101): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('Video')\n
#12 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropertyStorage\/Plugin.php(86): OC\\Connector\\Sabre\\CustomPropertiesBackend->propFind('Video', Object(Sabre\\DAV\\PropFind))\n
#13 [internal function]: Sabre\\DAV\\PropertyStorage\\Plugin->propFind(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n
#14 \/opt\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#15 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1016): Sabre\\Event\\EventEmitter->emit('propFind', Array)\n
#16 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(936): Sabre\\DAV\\Server->getPropertiesByNode(Object(Sabre\\DAV\\PropFind), Object(OC\\Connector\\Sabre\\Directory))\n
#17 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(327): Sabre\\DAV\\Server->getPropertiesForPath('', Array, 1)\n
#18 [internal function]: Sabre\\DAV\\CorePlugin->httpPropfind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#19 \/opt\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#20 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n
#21 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#22 \/opt\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#23 \/opt\/owncloud\/remote.php(132): require_once('\/opt\/owncloud\/a...')\n#24 {main}","File":"\/opt\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Connection.php","Line":65} 
```

### PR DESCRIPTION
**Pull request by PVince81**
Please review @icewind1991 @xenopathic @jmaciasportela @MorrisJobke 

Fixes https://github.com/owncloud/core/issues/18299

I'll evaluate whether this needs backporting, depending whether it was broken on 8.2 or not.

### CODE REVIEW

**Comment by PVince81** [comment]
I checked the following behaviors when the SMB server is down
- WND on v8.2.2 doesn't throw StorageNotAvailable but returns the cached folder list
- SMB on v8.2.2 throws errors https://github.com/owncloud/core/issues/18299#issuecomment-191194356
- WND on 9.0 now uses SMB, so we need this PR to be backported to stable9

@karlitschek backport to stable9 for 9.0.1 ? (will be important to avoid WND regression)

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by karlitschek** [comment]
please backport

**Comment by MorrisJobke** [comment]
:+1:

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/22779

**Comment by Xenopathic** [comment]
:exclamation: Wait what! :exclamation: Why are we checking the storage availability at this point?! With this, we will *never* hit the availability update logic, so an unavailable external storage will never get marked available after the TTL expires?!

**Comment by PVince81** [comment]
I only fixed it... feel free to discuss this with @icewind1991 who introduced that block.
It's a bit late to remove it now, so would be something for 9.0.1

**Comment by PVince81** [comment]
@Xenopathic can you make a new ticket to discuss this and set it to 9.0.1 ? Thanks

**Comment by Xenopathic** [comment]
So it's acceptable that an external storage that, for whatever reason (probably temporary network interruption) is marked as unavailable, *never* comes back online without manual intervention?

**Comment by PVince81** [comment]
@Xenopathic I think in my test it came back, but I'll double check this

**Comment by PVince81** [comment]
The ticket you raised to discuss this: https://github.com/owncloud/core/issues/22790

**Comment by PVince81** [comment]
@Xenopathic indeed, you're right. After a storage has been marked unavailable, it has no way of recovering. This means this PR of mine is not suitable.

Closing and increasing severity of your ticket.

**Pull request closed without merging**
