### PR TITLE
[8.1 backport] Don't mix up directories if the migration runs multiple times

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/owncloud/core/pull/17701, approved by @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by schiesbn** [comment]
@owncloud-bot retest this plase

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Pull request merged**
