### PR TITLE
Add whitespace to right of list to prevent accidental deletion when scrolling

### PR DESCRIPTION
**Pull request by jancborchardt**
This adds a bit of whitespace to the right of the file list (as well as the user list) to prevent accidental deletion when wanting to use the scrollbar with the mouse. Please review @owncloud/designers 

@dragotin @ShamimIslam @Wikinaut I think this will at least partly make you happy. :) Please test.

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
squash, baby - squash!

**Comment by MorrisJobke** [comment]
Nice :+1:

**Comment by jancborchardt** [comment]
Hey – please no squashing without asking! It was two entirely different things …

**Comment by ShamimIslam** [comment]
While this helps, my constituents have expressed that they prefer to have
both the confirm and the space - until the two click delete is in place (I
think I saw something like that) or the context menu for the delete
appears. They did mention some trepidation that the delete in the context
menu still creates opportunities for accidental delete since there are
other options in the context menu and there is not opportunity to recover
from the delete click without either a confirm or a delayed execution. For
now, I've been asked to retain the confirm.

But yes, this does help.

**Comment by jancborchardt** [comment]
@ShamimIslam yup – we’re working on the undo mechanism atm.

**Pull request merged**
