### PR TITLE
[stable8] Add default value for remote_id

### PR DESCRIPTION
**Pull request by PVince81**
Fixes SQLite migration with non-null column.

Backport of https://github.com/owncloud/core/pull/14532 to stable8

Please review @schiesbn @DeepDiver1975 @icewind1991 @LukasReschke
@karlitschek please approve (fixes db upgrade issue with s2s on sqlite)

Needs to be tested on all DBs (see original PR)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
app version increment required - see #14532

**Comment by PVince81** [comment]
I increased the version.

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
He lives!

Now still need a second thumbs up @icewind1991 @DeepDiver1975

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
