### PR TITLE
chore: no dynamic properties

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
preparation for php 8.2

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/39157/20/8
```
) Test\PreviewCleanupTest::test
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT "fileid", "name", "storage"
FROM "oc_filecache" "thumb"
WHERE "parent" IN (
  SELECT "fileid"
  FROM "oc_filecache"
  WHERE "storage" IN (
    SELECT "numeric_id"
    FROM "oc_storages"
    WHERE "id" LIKE 'home::%' OR "id" LIKE 'object::user:%'
  )
  AND "path_hash" = '3b8779ba05b8f0aed49650f3ff8beb4b'
)
AND NOT EXISTS (
  SELECT 1
  FROM "oc_filecache"
  WHERE "fileid" = CAST("thumb"."name" AS BIGINT)
)
AND "fileid" > ?
ORDER BY "storage" limit 1000' with params [0]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "welcome.txt"

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:182
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:159
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:2226
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1313
/drone/src/lib/private/DB/Connection.php:191
/drone/src/lib/private/PreviewCleanup.php:145
/drone/src/lib/private/PreviewCleanup.php:53
/drone/src/tests/lib/PreviewCleanupTest.php:106
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:106

Caused by
Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "welcome.txt"

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1304
/drone/src/lib/private/DB/Connection.php:191
/drone/src/lib/private/PreviewCleanup.php:145
/drone/src/lib/private/PreviewCleanup.php:53
/drone/src/tests/lib/PreviewCleanupTest.php:106
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:106

Caused by
PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "welcome.txt"

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1304
/drone/src/lib/private/DB/Connection.php:191
/drone/src/lib/private/PreviewCleanup.php:145
/drone/src/lib/private/PreviewCleanup.php:53
/drone/src/tests/lib/PreviewCleanupTest.php:106
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:106
```
```

**Comment by phil-davis** [comment]
The unit test failure is strange - I don't see any code changes that are related to that test.

**Comment by phil-davis** [comment]
Other PRs are passing. I restarted CI. Let's see what happens.

**Comment by DeepDiver1975** [comment]
Thx

**Pull request merged**
