### PR TITLE
don't delete share table entries for the unique name if re-share permission was removed

### PR DESCRIPTION
**Pull request by schiessle**
If reshare permission was removed from a share we remove all reshares from the table. But we should keep the table entries for the unique name.

### CODE REVIEW

**Comment by PVince81** [comment]
@schiesbn please provide the test steps. Thanks.

**Comment by schiesbn** [comment]
Steps to test:

- create two users: "user1" and "user2"
- add "user2" to group "users"
- "user1" share the file "test.txt" with the group "users"
- login as "user2" and rename the shared "test.txt" to "renamed test.txt"
- "user1" removes the "can share" permission

Expected result: user2 should still see the "renamed test.txt" share

Result without this patch: the shared file for user2 will be named "test.txt" again

Note: To test the failure case you need this commit https://github.com/owncloud/core/commit/e9e7ee67d373e138b4a9749f9e9a7847a7d3875d. Otherwise the code who deletes the reshares will never be executed because of a type mismatch.

**Comment by PVince81** [comment]
Tested, code makes sense :+1:

**Comment by PVince81** [comment]
This caused a regression here https://github.com/owncloud/core/issues/13445.
The question is why removing the share permission would auto-delete the children ? It should only delete them if they were actual reshares, not in all cases.

This is probably due to the fact that the "parent" column is misused for different types: for reshares but also for children of group shares.

**Pull request merged**
