### PR TITLE
[full-ci] Enable streaming for propfind

### LINKED ISSUE #14531: Depth infinity: Make recursive PROPFIND calls cheaper
### Testcase

 `curl -XPROPFIND https://user:pwd@server/owncloud/remote.php/webdav -H "Depth:infinity"`
### Actual results

On a well-equipped x86_64 machine it takes 7:20 minutes under heavy server load to list 5279 items (dirs/files). 
### Expected results

This should actually be fairly cheap, since all required information is available from the DB. The suspicion is that we could attain some serious speedup by investigating code paths and DB queries and optimizing them.
### Motivation

Cheap recursive PROPFINDs would allow the client to move away from doing directory-by-directory discovery, which in turn would significantly speed up syncs, especially all sync runs until completing initial sync.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Propfind requests will now be streamed to reduce memory usage with large responses.
Additionally, the new config `dav.propfind.depth_infinity` has been added to tell clients whether `depth=infinity` is allowed for propfind requests. It defaults to true. 

https://github.com/owncloud/core/pull/36336 reloaded
Fixes https://github.com/owncloud/core/issues/14531

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [x] Acceptance tests added
- [x] Documentation ticket raised:  https://github.com/owncloud/docs/issues/4127
- [x] Changelog item

### CODE REVIEW

**Review by michaelstingl — DISMISSED** [review]
Please add capability for the clients, so they don't meltdown servers without this improvement.

**Comment by michaelstingl** [comment]
@DeepDiver1975 @hodyroff what's next. Can be released in next iOS version, but there's no capability yet. When can this be released?

**Comment by DeepDiver1975** [comment]
> When can this be released?

Once these things are taken care of:
- [ ] capability
- [ ] add dedicated acceptance tests for depth infinity (especially exceptional scenarios)
- [ ] fix any issues which arise (basically fix all acceptance tests when streaming is enabled on all requests/responses)
- [ ] enable streaming only if depth: infinity is used (risk minimization)

total effort: ~2 weeks

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-5-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32901/172/1

**Comment by JammingBen** [comment]
@DeepDiver1975 Pipeline runs now, please have a look. We basically just added a preflight check if the tree is traversable and if the resource has read permissions in case of a share.

Regarding the open to-dos, please verify the following assumptions:

* `capability` -> we just add `depth_infinity` to the capabilities and set it to `true`
* `enable streaming only if depth: infinity is used (risk minimization)` -> That's outdated, we always enable streaming

**Comment by pmaier1** [comment]
> @pmaier1 it was not forbidden before

I'd keep that behavior then unless you see an issue with it that I might be missing :)

**Comment by michaelstingl** [comment]
> * `capability` -> we just add `depth_infinity` to the capabilities and set it to `true`

How can admins disable it? Doc issue?

**Comment by michaelstingl** [comment]
> @michaelstingl We still need to figure out if we throw an exception if depth infinity was sent but is not allowed

Simple check with `curl`:

```
curl "https://demo.owncloud.com/remote.php/dav/files/test/" \
  -u "test:test" \
  -X "PROPFIND" \
  -H "Depth:infinity" | xmllint --format -
```

**Comment by JanAckermann** [comment]
@michaelstingl misunderstanding -> i mean if we should throw an exception

**Comment by michaelstingl** [comment]
> @michaelstingl misunderstanding -> i mean if we should throw an exception

Is there an exception in 10.8? If not, why add it with 10.9? From my pov, it's okay to use this only to control behaviour of ownCloud original apps.

**Comment by JanAckermann** [comment]
> Is there an exception in 10.8?
No but this was also not configurable in 10.8

**Comment by JammingBen** [comment]
@phil-davis Could you/your team assist us with the acceptance tests here? I'm currently thinking of:

* PROPFIND with `depth=infinity` fails if `dav.propfind.depth_infinity` is set to `false`
* PROPFIND with `depth=infinity` succeeds if `dav.propfind.depth_infinity` is set to `true` (which is default)

The other exception scenarios (PROPFIND on a read-only share and PROPFIND on an element which does not exist) are already covered AFAIK. @JanAckermann @DeepDiver1975 Any additions to that?

**Review by IljaN — APPROVED** [review]
Just some optional remarks/thought. LGTM :+1:

**Review by phil-davis — APPROVED** [review]
LGTM

**Review by IljaN — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Comment by jnweiger** [comment]
Capability confirmed:
```
curl -k -s -u admin:admin 'https://localhost/ocs/v1.php/cloud/capabilities?format=json' | jq .ocs.data.capabilities.dav.propfind
{
  "depth_infinity": true
}

**Comment by jnweiger** [comment]
Confirmed fixed in 10.9.0 RC2

* On a tree with 40000 files and folders, the first output appears conistently within 10 seconds:
* `curl -k -s -u admin:admin -XPROPFIND https://$server/remote.php/dav/files/admin/Deep -H "Depth:infinity" | pv > /dev/null`
* total wall clock time: 43 sec.

**Pull request merged**
