### PR TITLE
Hide the delete button, until we know its a custom avatar

### LINKED ISSUE #21908: Not expected trashbin appears when refreshing personal page.
### Steps to reproduce

1. Go to personal page.
2. If personal picture exist remove it.
3. Refresh page.

### Observed behaviour

papelera

##### ownCloud Version
{"installed":true,"maintenance":false,"version":"9.0.0.7","versionstring":"9.0 pre alpha","edition":""}

##### Browser
Observed in Chrome and Firefox

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #21908 

@SergioBertolinSG Now the flickering is the other way around, there will be no button for some milli-seconds until we know the user has an avatar and then it appears.

cc @jancborchardt @PVince81

### CODE REVIEW

**Comment by jancborchardt** [comment]
Sounds good :+1: – @SergioBertolinSG please review this as well.

**Comment by jancborchardt** [comment]
Also @nickvergessen you can cc @owncloud/designers to review this directly. You don’t need to be a member of the team to do that.

**Comment by SergioBertolinSG** [comment]
:+1: works

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
