### PR TITLE
[8.1] fix infinite loops with propagating etags on reshares

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of #18037

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
This patch was confirmed to fix the massive DB updates observed here https://github.com/owncloud/core/issues/18032

**Comment by PVince81** [comment]
I'd also vote for 8.1.1 for now. I'll set this to 8.1.1 so we don't forget it.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
