### PR TITLE
First process group shares and then user shares

### LINKED ISSUE #26523: Transfer ownership path already shared
### Steps

1. Create three users "user1", "user2" and "user3"
1. Add "user2" and "user3" in "group1"
1. Login as "user1"
1. Create a folder "test"
1. Share "test" with "group1" and "user2" and "user3"
1. Run `./occ files:transfer-ownership user1 user2`

### Expected result
Resulting share: "user2" shares with "group1" and "user3".

### Actual result
```
Analysing files of user1 ...
    1 [============================]
Collecting all share information for files and folder of user1 ...
    3 [============================]
Transferring files to user2/files/transferred from user1 on 2016-11-02T12:07:16+00:00 ...
Restoring shares ...
 1/3 [=========>------------------]  33%
                                      
  [Exception]                         
  Path already shared with this user  
```

### Versions
Observed on OC 9.0.5, 9.0.6RC2, 9.1.1, 9.1.2RC2, 9.2 pre-alpha (master)

Seems it will need more fine-grained checks.

@DeepDiver1975 @owncloud/qa

### PR DESCRIPTION
**Pull request by PVince81**
## Description
This prevents a validation failure where the code checks whether a file
is already shared with another user, but the check disables itself when
the owner is the same. Processing the groups first prevents the check
to kick in too early when the group share still has the old owner while
we try transferring the user share.

## Related Issue
Fixes https://github.com/owncloud/core/issues/26523

## Motivation and Context
See issue for a detailed explanation of what happens.

## How Has This Been Tested?
Follow steps from issue.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### Backports
- [ ] stable9.1
- [ ] stable9

### CODE REVIEW

**Comment by davitol** [comment]
:+1: WFM  Fixes #26523

**Comment by PVince81** [comment]
Integration tests will be added as part of https://github.com/owncloud/core/pull/26543

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/26568
stable9: https://github.com/owncloud/core/issues/26567

**Pull request merged**
