### PR TITLE
[stable8] Use transactions when renaming directory contents

### PR DESCRIPTION
**Pull request by MorrisJobke**
backport of #13948

cc @DeepDiver1975 @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
Bumped into this weird issue: https://github.com/owncloud/core/issues/14757

Now thinking of it, it could somehow be due to the transaction.

**Comment by christianrj** [comment]
Some of the bugs I reported related to rename problems:
#10711
#11487
#12659
#12661

**Comment by DeepDiver1975** [comment]
> Bumped into this weird issue: #14757
> 
> Now thinking of it, it could somehow be due to the transaction.

so - we better holds this back for now :-1:

**Comment by PVince81** [comment]
Thing is, @jnfrmarks managed to recreate the same issue (mysql lock) on 8.0.2 with smashbox, so I'm not 100% sure whether what I observed was really due to this change or my general "unluck" of being able to trigger random race conditions.

**Comment by MorrisJobke** [comment]
@PVince81 We can redo this easiely, but if it really cause an problem, then we better analyse this before a backport and not once it hit users ;)

**Comment by PVince81** [comment]
So far it seems that the issues we were seeing were not related to this addition, so we might maybe want to reopen/resend this, at least as a quickfix to reduces the probability of data loss here https://github.com/owncloud/core/issues/13391

**Pull request closed without merging**
