### PR TITLE
core improvements for Encryption 2.0

### PR DESCRIPTION
**Pull request by schiessle**
- Fix the detection of files which shouldn't be encrypted
- add additional parameter to update shares and expose additional methods to the public interface

cc @DeepDiver1975 @th3fallen

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
tested - works :+1: :speak_no_evil:

**Pull request merged**
