### PR TITLE
Always enable files_external

### PR DESCRIPTION
**Pull request by PVince81**
## Motivation and Context
Because we want the UI to still be available while the backend is
already in core.

Eventually the files_external backends will be moved to separate apps and all that will be left is the GUI and the OCC commands which we'll eventually move to core. Ref: https://github.com/owncloud/core/issues/27050

## How Has This Been Tested?
- [x] TEST: update from 9.1 with files_external disabled to master: app is now enabled
- [x] TEST: setup OC 10.0 from scratch, app is enabled
- [x] TEST: cannot disable files_external app

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Please review @pmaier1 @DeepDiver1975 as discussed

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
Tests require adjustments

**Comment by PVince81** [comment]
757 failures ???!!!

**Comment by PVince81** [comment]
Hmm, I suspect that some admins might not be happy that there will be a permanent "External storage" section in the files app. Maybe need to make it possible to disable this.

**Comment by pmaier1** [comment]
> Hmm, I suspect that some admins might not be happy that there will be a permanent "External storage" section in the files app. Maybe need to make it possible to disable this.

Yes, would be good to be able to disable it if you do not use external storages at all.

**Comment by PVince81** [comment]
- [ ] problem: since files_external is always enabled, the unit test facility also tries to run **all** tests from that app

**Comment by PVince81** [comment]
- [ ] setting to disable external storage in config.php

**Comment by PVince81** [comment]
Excluded files_external unit tests from regular run.

**Comment by PVince81** [comment]
Cool, tests pass now.

I'll do a bit of manual testing then merge this.

The config.php switch will be added in a separate PR.

**Comment by PVince81** [comment]
PR for the checkbox here: https://github.com/owncloud/core/pull/27196

It also disabled external storage completely as before. So there is no loss of functionality in 10.0.

**Comment by kdslkdsaldsal** [comment]
@PVince81 @DeepDiver1975 @pmaier1 FWIW this has disabled the "remember me" button on the login page because files_external is setting ``<rememberlogin>false</rememberlogin>``:

https://github.com/owncloud/core/blob/v10.0.2/apps/files_external/appinfo/info.xml#L15

I think this is not that serve as the "remember me" function wasn't working since oC 9.1 but still something to note / document somewhere.

**Pull request merged**
