### PR TITLE
fix for loading spinner reappearing after errors in db-connection

### LINKED ISSUE #14526: Installation page has a confusing gif
### Steps to reproduce

1. Start a fresh installation, you don't need to fill any fields or do anything, just see the installation page.

### Expected behaviour
Installation page loads correctly and doesn't have confusing gifs of loading.

### Actual behaviour
There is a confusing gif at the bottom of the page.

screen shot 2015-02-26 at 10 47 42

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.0

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
Browser, Chrome

### PR DESCRIPTION
**Pull request by sebomoto**
this should fix #14526

This contribution is MIT licensed

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1: fixes the issue

**Comment by nickvergessen** [comment]
@MorrisJobke review?

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
@nickvergessen @sebomoto Can one of you create a backport PR against stable8? Thanks :)

**Comment by jancborchardt** [comment]
Ping @nickvergessen ^

**Comment by nickvergessen** [comment]
that code does not exist like that in stable8, so I dont think we can backport this.

**Pull request merged**
