### PR TITLE
Filter out group shares for owner where owner is included

### LINKED ISSUE #25186: Files and folders shared with a group including the sharer are shared with himself as well.
### Steps to reproduce:

1. As admin create several users, including 'user1' and make them belong to a group 'group1'.
2. As 'user1' share a folder or file with 'group1'.

### Expected behaviour:
All users except 'user1' gets the share from 'user1'.

### Actual behaviour
'user1' now have the file/folder twice, he has received his own share too.

screen shot 2016-06-20 at 12 53 32

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

### Client configuration

Chrome, Firefox.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/25186

Please review @georgehrke @icewind1991 @owncloud/sharing @DeepDiver1975 @guruz 

Also introduces a unit test class for this class as it was missing...

### CODE REVIEW

**Comment by PVince81** [comment]
also @SergioBertolinSG for retesting

**Comment by SergioBertolinSG** [comment]
Works 👍

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by guruz** [comment]
👍

**Pull request merged**
