### PR TITLE
Enable upstream entrypoint changes with Ceph Docker

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
See Xenopathic/ceph-keystone.docker@724f791181979fcd3999a07300046373d4dcf7cb

Might help with #22588 ? @DeepDiver1975 

The entrypoint.sh that was in the ownCloud test directory was identical to the old entrypoint.sh in the Docker image itself, but was only used for the Swift tests (and not the AmazonS3 tests, for some reason)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
let's get this in an see whats happening - THX

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
we have now failing unit tests:
https://ci.owncloud.org/job/server-master-linux-externals/database=sqlite,external=swift-ceph,label=SLAVE/4948/console

````
06:28:10 There were 2 failures:
06:28:10 
06:28:10 1) Test\Files\Storage\Swift::testRoot
06:28:10 Root folder does not exist
06:28:10 Failed asserting that false is true.
06:28:10 
06:28:10 /ssd/jenkins/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/tests/lib/files/storage/storage.php:48
06:28:10 
06:28:10 2) Test\Files\Storage\Swift::testTestFunction
06:28:10 Failed asserting that false is true.
06:28:10 
06:28:10 /ssd/jenkins/workspace/server-master-linux-externals/database/sqlite/external/swift-ceph/label/SLAVE/tests/lib/files/storage/storage.php:62
06:28:10

**Comment by Xenopathic** [comment]
It's almost like there's still a race condition, but internal to the Docker image - the tests after the first two all succeed (yet all succeed on my machine). Could you get the Docker logs from that run?

**Comment by DeepDiver1975** [comment]
> Could you get the Docker logs from that run?

not really the docker is dead ... let me see what I can tweak .....

**Comment by DeepDiver1975** [comment]
> not really the docker is dead ... let me see what I can tweak .....

https://github.com/owncloud/core/pull/22623

**Pull request merged**
