### PR TITLE
Automatically enable "federation" app

### PR DESCRIPTION
**Pull request by LukasReschke**
For https://github.com/owncloud/core/issues/22869

… also made the indentation consistent for master.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by PVince81** [comment]
One does not simply enable an app without breaking the test...

**Comment by LukasReschke** [comment]
> One does not simply enable an app without breaking the test...

:see_no_evil:

**Comment by karlitschek** [comment]
:+1:

**Comment by schiesbn** [comment]
Should it? This will mean that from ownCloud 9 on we will automatically add all servers you share with as "trusted servers" and sync the user list. At least we should make sure that the user really knows this, maybe a message during upgrade? I could imagine that some users don't like it once they see it.

Just want to make sure that we are aware of all implications.

**Comment by karlitschek** [comment]
I don't understand how this failing test can be related to enabling the app by default. Should be fine to merge IMHO

**Comment by karlitschek** [comment]
@schiesbn true. i think there is always the option on the admin page. but we should enable by default

**Comment by PVince81** [comment]
We should probably state this clearly in the release notes to make sure that user lists are not exchanged without the admins knowing, so they get a chance to disable it if they do not want to expose the user lists for privacy reasons.

@jospoortvliet @carlaschroder

**Pull request merged**
