### PR TITLE
update moment.js to 2.10.3

### PR DESCRIPTION
**Pull request by MorrisJobke**
To test: Have a look at the tooltip of the files app modified date.

cc @PVince81 @rullzer @Xenopathic @oparoz @DeepDiver1975

### CODE REVIEW

**Comment by rullzer** [comment]
:white_check_mark:  js unit test pass
 :white_check_mark:  files app modification time displayed as expected

I can't find any breaking of the API in the changelog. :+1:

**Comment by MorrisJobke** [comment]
@Xenopathic @PVince81 Please review :)

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @LukasReschke Second reviewer needed :)

**Comment by Xenopathic** [comment]
Basic test, everything works. Changelog looks good (just need to watch out for 2.10.5 if we update to that at some point). :+1:

**Pull request merged**
