### PR TITLE
Show error messages if a password reset link is invalid or expired

### PR DESCRIPTION
**Pull request by juliusknorr**
This pull request will show the user a message if the password reset token is invalid or has expired. 

This solves #24561

### CODE REVIEW

**Comment by nickvergessen** [comment]
Works :+1: 

@juliushaertl can you comment about the license?

**Comment by nickvergessen** [comment]
@ChristophWurst review?

**Comment by ChristophWurst** [comment]
Conflicts, please rebase

Looks good otherwise

**Comment by nickvergessen** [comment]
Maybe we should rebase and push to our org, to make sure the tests pass (don't run for 3rdparty repos)

**Comment by juliushaertl** [comment]
I've just rebased against current master.

This contribution is MIT licensed.

I've also signed the contributors agreement, but I guess this takes a while.

**Comment by PVince81** [comment]
Jenkins PR: https://github.com/owncloud/core/pull/24797

**Comment by PVince81** [comment]
Tested, works :+1: 

If CI passes in https://github.com/owncloud/core/pull/24797 we can merge this

**Pull request merged**
