### PR TITLE
back port of #14419

### PR DESCRIPTION
**Pull request by georgehrke**
backport of https://github.com/owncloud/core/pull/14419

please review @DeepDiver1975 @nickvergessen

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
@LukasReschke

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
THX @georgehrke

**Pull request merged**
