### PR TITLE
Change log level of debugging logs to debug

### PR DESCRIPTION
**Pull request by nickvergessen**
@rullzer @schiesbn 

Fixes https://github.com/owncloud/core/pull/17195/files#r34869009

### CODE REVIEW

**Comment by LukasReschke** [comment]
```
06:14:50 PHP Catchable fatal error:  Argument 3 passed to OC\AppFramework\Http\Request::__construct() must be an instance of OCP\Security\ICrypto, instance of OC\AllConfig given, called in /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/server.php on line 488 and defined in /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/appframework/http/request.php on line 93
06:14:50 PHP Stack trace:
06:14:50 PHP   1. {main}() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/occ:0
06:14:50 PHP   2. require_once() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/occ:11
06:14:50 PHP   3. require_once() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/console.php:41
06:14:50 PHP   4. OC::init() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/base.php:1133
06:14:50 PHP   5. OC::initTemplateEngine() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/base.php:606
06:14:50 PHP   6. OC_Util::addTranslations() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/base.php:404
06:14:50 PHP   7. OC_L10N::findLanguage() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/util.php:477
06:14:50 PHP   8. OC_User::getUser() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/l10n.php:452
06:14:50 PHP   9. OC\Server->getSession() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/user.php:431
06:14:50 PHP  10. OC\AppFramework\Utility\SimpleContainer->query() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/server.php:635
06:14:50 PHP  11. Pimple\Container->offsetGet() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/appframework/utility/simplecontainer.php:104
06:14:50 PHP  12. OC\Server->OC\{closure}() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/3rdparty/pimple/pimple/src/Pimple/Container.php:112
06:14:50 PHP  13. OC\Server->getSessionCryptoWrapper() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/server.php:166
06:14:50 PHP  14. OC\AppFramework\Utility\SimpleContainer->query() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/server.php:1017
06:14:50 PHP  15. Pimple\Container->offsetGet() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/appframework/utility/simplecontainer.php:104
06:14:50 PHP  16. OC\Server->OC\{closure}() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/3rdparty/pimple/pimple/src/Pimple/Container.php:112
06:14:50 PHP  17. OC\AppFramework\Http\Request->__construct() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/server.php:488
06:14:50 PHP  18. OC\Log\ErrorHandler->onError() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/server.php:93
06:14:50 PHP  19. OC\Log->error() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/log/errorhandler.php:86
06:14:50 PHP  20. OC\Log->log() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/log.php:118
06:14:50 PHP  21. call_user_func:{/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/log.php:241}() /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/log.php:241
```

Seems like another change caused problems after merge.

**Comment by LukasReschke** [comment]
I will fix this in master…

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/18513

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
I'm fine with this :+1:

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
