### PR TITLE
Adding new tests for federation sharing

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Adding case about resharing and others.

Please review @rullzer @schiesbn

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG please rebase - THX

**Comment by SergioBertolinSG** [comment]
rebased.

**Comment by SergioBertolinSG** [comment]
After talking with @LukasReschke, failing situation seems to be related with a change in endpoints for other file sync solutions.

**Comment by rullzer** [comment]
@DeepDiver1975 it seems the intergration tests are taking to much time and get killed now... We should look into how to speed them up. But as a quickfix maybe move the timeout from 20 => 30 min.

**Comment by rullzer** [comment]
So this setup fails I think because we have actually only 1 server. And you do a cylic share. So when the test is finished and we try to tear down everything this results in a deadlock because we only have 1 share.

Try to convert the test to the following.

1. user1@local shares with user2@remote
2. user2@remote shares (locally) with user3

That should work.

**Comment by SergioBertolinSG** [comment]
please review.

**Comment by rullzer** [comment]
:+1:

**Comment by SergioBertolinSG** [comment]
another reviewer? @schiesbn , @DeepDiver1975

**Comment by MorrisJobke** [comment]
looks good so far :+1:

**Pull request merged**
