### PR TITLE
Set "ie" CSS class for IE10, IE11

### LINKED ISSUE #20419: Files menu doesn't have borders in edge browser.
### Steps to reproduce

1. Using edge, in the files view, click in the '+' and show the dropdown.

### Expected behaviour
Same as in chrome or firefox.

### Actual behaviour
No borders:

screen shot 2015-11-10 at 09 10 54

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.1.0","versionstring":"8.2.1 RC1","edition":"Enterprise"}

Happening also in master branch.

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Server logs**
```

```

cc @jancborchardt

### PR DESCRIPTION
**Pull request by PVince81**
Fixed border in file action menu

Fixes https://github.com/owncloud/core/issues/20419

@SergioBertolinSG please test in all browsers and IE variants

Please review @nickvergessen @rullzer @icewind1991 @jancborchardt 

@karlitschek backport this IE style fix ?

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense to backport. Shoudn't hurt ;-)

**Comment by SergioBertolinSG** [comment]
Tested in:
chrome: :white_check_mark: 
firefox: :white_check_mark: 
safari: :white_check_mark: 
ie8: :white_check_mark: 
ie9: :white_check_mark: 
ie10: :white_check_mark: 
ie11 :white_check_mark: 
edge: :X:

**Comment by SergioBertolinSG** [comment]
Tested in:

| Browser  | Result |
|----------|:------:|
| chrome   | :white_check_mark: |
| firefox | :white_check_mark: | 
| safari | :white_check_mark: | 
| ie8 |  :white_check_mark: |
| ie9 | :white_check_mark: |
| ie10 | :white_check_mark: |
| ie11 | :white_check_mark: |
| edge | :x: |

**Comment by PVince81** [comment]
Grrr... the IE11 in my VM lied and told me it was in edge mode.

**Comment by PVince81** [comment]
I had to add an extra code for Edge... @SergioBertolinSG please only retest if Edge works (other ones not needed). Thanks

**Comment by SergioBertolinSG** [comment]
Hmm it is not working either with the last code.

**Comment by SergioBertolinSG** [comment]
Sorry bad enviroment, after a retest if works fine in Edge as well. :+1:

**Comment by PVince81** [comment]
I squashed this.

@rullzer @icewind1991 second review ?

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/20443

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
