### PR TITLE
UI tests to add public link shares to remote server

### PR DESCRIPTION
**Pull request by individual-it**
UI tests for  #29675

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by individual-it** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase was successful!

**Comment by individual-it** [comment]
@phil-davis had to do some changes, please review again

**Review by phil-davis — APPROVED** [review]
Looks fine.

**Comment by phil-davis** [comment]
Backport stable10 #29863

**Pull request merged**
