### PR TITLE
add dockerfile for dev

### PR DESCRIPTION
**Pull request by agrim123**
I am adding a Dockerfile to make it easier for people who are setting up owncloud for first time. I myself faced some issues (like php version mismatch etc.) and I think other developers may also face them. 

### Commands

$ ifconfig
note the address of docker0 (lets says its 172.17.0.1)
$  sudo docker build -t owncloud 
$  sudo docker run -it -v /home/path/to/owncloud/:/var/www/owncloud owncloud
root@randomstring:/# service apache2 restart

You can view the application at 172.17.0.1/owncloud

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks, but I think we already have this somewhere else.

@SergioBertolinSG @tboerger @DeepDiver1975 ?

**Comment by SergioBertolinSG** [comment]
There are public docker images already available:
 https://hub.docker.com/_/owncloud/ and https://github.com/owncloud-docker/server

**Comment by tboerger** [comment]
It should be better to provide a docker-compose file that uses owncloud/base:latest, linking the code to /var/www/owncloud, to persist the config you can also use the volume /mnt/data

**Comment by tboerger** [comment]
https://github.com/owncloud-docker/server/blob/master/docker-compose.yml is a good example, just use the base image instead of the server image

**Comment by agrim123** [comment]
@tboerger i will try to complete it asap

**Comment by DeepDiver1975** [comment]
I'm closing this one - we maintain docker images at https://github.com/owncloud-docker

**Pull request closed without merging**
