### PR TITLE
Fix failing preview unit tests

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

Preview unit tests are failing on jenkins.owncloud.org
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Code looks good :+1:

**Comment by butonic** [comment]
👍

**Comment by DeepDiver1975** [comment]
https://jenkins.owncloud.org/job/owncloud-core/job/core/job/PR-26039/1/testReport/%28root%29/Test_PreviewTest/ are successfull now - but there are other issues with jenkins -> merge

**Comment by DeepDiver1975** [comment]
will prepare backports

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/issues/26043
stable9: https://github.com/owncloud/core/pull/26051

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/26053

**Pull request merged**
