### PR TITLE
[stable8] make sure that hooks are emitted properly on file move operation

### PR DESCRIPTION
**Pull request by schiessle**
approved backport of https://github.com/owncloud/core/pull/17932

fix: https://github.com/owncloud/core/issues/17877

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
```
11:51:15 There were 3 errors:
11:51:15 
11:51:15 1) Test_Trashbin::testExpireOldFiles
11:51:15 opendir(/dev/shm/data-autotest3/test-trashbin-user1/files_trashbin/files): failed to open dir: No such file or directory
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/storage/local.php:78
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/storage/wrapper/wrapper.php:69
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/view.php:848
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/view.php:252
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/lib/helper.php:29
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/trashbin.php:132
11:51:15 
11:51:15 2) Test_Trashbin::testExpireOldFilesShared
11:51:15 opendir(/dev/shm/data-autotest3/test-trashbin-user1/files_trashbin/files): failed to open dir: No such file or directory
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/storage/local.php:78
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/storage/wrapper/wrapper.php:69
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/view.php:848
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/view.php:252
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/lib/helper.php:29
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/trashbin.php:186
11:51:15 
11:51:15 3) Test_Trashbin::testExpireOldFilesUtilLimitsAreMet
11:51:15 opendir(/dev/shm/data-autotest3/test-trashbin-user1/files_trashbin/files): failed to open dir: No such file or directory
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/storage/local.php:78
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/storage/wrapper/wrapper.php:69
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/view.php:848
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/lib/private/files/view.php:252
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/lib/helper.php:29
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/trashbin.php:281
11:51:15 
11:51:15 --
11:51:15 
11:51:15 There were 10 failures:
11:51:15 
11:51:15 1) OCA\Files_Encryption\Tests\Trashbin::testRestoreFile
11:51:15 Failed asserting that null is not null.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_encryption/tests/trashbin.php:218
11:51:15 
11:51:15 2) OCA\Files_Encryption\Tests\Trashbin::testPermanentDeleteFile
11:51:15 Failed asserting that true is false.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_encryption/tests/trashbin.php:296
11:51:15 
11:51:15 3) OCA\Files_trashbin\Tests\Storage\Storage::testSingleStorageDeleteFile
11:51:15 Failed asserting that 0 matches expected 1.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/storage.php:82
11:51:15 
11:51:15 4) OCA\Files_trashbin\Tests\Storage\Storage::testSingleStorageDeleteFolder
11:51:15 Failed asserting that 0 matches expected 1.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/storage.php:99
11:51:15 
11:51:15 5) OCA\Files_trashbin\Tests\Storage\Storage::testCrossStorageDeleteFile
11:51:15 Failed asserting that 0 matches expected 1.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/storage.php:130
11:51:15 
11:51:15 6) OCA\Files_trashbin\Tests\Storage\Storage::testCrossStorageDeleteFolder
11:51:15 Failed asserting that 0 matches expected 1.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/storage.php:157
11:51:15 
11:51:15 7) OCA\Files_trashbin\Tests\Storage\Storage::testDeleteVersionsOfFile
11:51:15 Failed asserting that 0 matches expected 1.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/storage.php:187
11:51:15 
11:51:15 8) OCA\Files_trashbin\Tests\Storage\Storage::testDeleteVersionsOfFolder
11:51:15 Failed asserting that 0 matches expected 1.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/storage.php:216
11:51:15 
11:51:15 9) OCA\Files_trashbin\Tests\Storage\Storage::testDeleteVersionsOfFileAsRecipient
11:51:15 Versions in owner's trashbin
11:51:15 Failed asserting that 0 matches expected 1.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/storage.php:265
11:51:15 
11:51:15 10) OCA\Files_trashbin\Tests\Storage\Storage::testDeleteVersionsOfFolderAsRecipient
11:51:15 Failed asserting that 0 matches expected 1.
11:51:15 
11:51:15 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/apps/files_trashbin/tests/storage.php:314
```

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
Ah yes, please fix the unit tests

**Comment by PVince81** [comment]
Any update ? Unit tests are failing.

**Comment by DeepDiver1975** [comment]
we discovered some issue in hook handling - we need to analysis this more in detail -> 8.0.8

**Comment by MorrisJobke** [comment]
See https://github.com/owncloud/core/issues/17877#issuecomment-148378172

**Comment by schiesbn** [comment]
as discussed with @cmonteroluque we would need to introduce to large changes to fix it for 8.0. -> Closed

**Pull request closed without merging**
