### PR TITLE
encryption requires openssl and user_ldap requires ldap :speak_no_evil:

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes self

@blizzz @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
bildschirmfoto von 2015-02-02 10 08 35

Seems to have problems with the name.

**Comment by DeepDiver1975** [comment]
@MorrisJobke 

```sh
$ php --info | grep ldap

**Comment by MorrisJobke** [comment]
It gets even listed, but because no version number is extracted it isn't added to the packages array here: https://github.com/owncloud/core/blob/master/lib/private/app/platformrepository.php#L43 (it is listed in `$loadedExtension`

Maybe also add extensions that are just enabled, but didn't have any version number?

**Comment by MorrisJobke** [comment]
```
$ php --info | grep ldap
Configure Command =>  './configure'  '--srcdir=../php-5.6.5' '--config-cache' '--prefix=/usr' '--sbindir=/usr/bin' '--sysconfdir=/etc/php' '--localstatedir=/var' '--with-layout=GNU' '--with-config-file-path=/etc/php' '--with-config-file-scan-dir=/etc/php/conf.d' '--disable-rpath' '--mandir=/usr/share/man' '--without-pear' '--disable-cgi' '--with-readline' '--enable-pcntl' '--enable-bcmath=shared' '--enable-calendar=shared' '--enable-dba=shared' '--enable-exif=shared' '--enable-ftp=shared' '--enable-gd-native-ttf' '--enable-intl=shared' '--enable-mbstring' '--enable-opcache' '--enable-phar=shared' '--enable-posix=shared' '--enable-shmop=shared' '--enable-soap=shared' '--enable-sockets=shared' '--enable-sysvmsg=shared' '--enable-sysvsem=shared' '--enable-sysvshm=shared' '--enable-zip=shared' '--with-bz2=shared' '--with-curl=shared' '--with-db4=/usr' '--with-enchant=shared,/usr' '--with-fpm-systemd' '--with-freetype-dir=/usr' '--with-xpm-dir=/usr' '--with-gd=shared,/usr' '--with-gdbm' '--with-gettext=shared' '--with-gmp=shared' '--with-iconv=shared' '--with-icu-dir=/usr' '--with-imap-ssl' '--with-imap=shared' '--with-jpeg-dir=/usr' '--with-vpx-dir=/usr' '--with-ldap=shared' '--with-ldap-sasl' '--with-libzip' '--with-mcrypt=shared' '--with-mhash' '--with-mssql=shared' '--with-mysql-sock=/run/mysqld/mysqld.sock' '--with-mysql=shared,mysqlnd' '--with-mysqli=shared,mysqlnd' '--with-openssl=shared' '--with-pcre-regex=/usr' '--with-pdo-mysql=shared,mysqlnd' '--with-pdo-odbc=shared,unixODBC,/usr' '--with-pdo-pgsql=shared' '--with-pdo-sqlite=shared,/usr' '--with-pgsql=shared' '--with-png-dir=/usr' '--with-pspell=shared' '--with-snmp=shared' '--with-sqlite3=shared,/usr' '--with-tidy=shared' '--with-unixODBC=shared,/usr' '--with-xmlrpc=shared' '--with-xsl=shared' '--with-zlib' 'CFLAGS=-march=x86-64 '-mtune=generic' '-O2' '-pipe' '-fstack-protector-strong' '--param=ssp-buffer-size=4'' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CXXFLAGS=-march=x86-64 '-mtune=generic' '-O2' '-pipe' '-fstack-protector-strong' '--param=ssp-buffer-size=4''
ldap
ldap.max_links => Unlimited => Unlimited
```

**Comment by DeepDiver1975** [comment]
> Maybe also add extensions that are just enabled, but didn't have any version number?

seems to be ..... let me double check how composer is handling this ...

**Comment by DeepDiver1975** [comment]
https://github.com/composer/composer/blob/master/src/Composer/Repository/PlatformRepository.php#L65

**Comment by DeepDiver1975** [comment]
@MorrisJobke please retest - THX a lot!

**Comment by MorrisJobke** [comment]
> THX a lot!

I guess that is my job ;)

Works now :+1:

**Comment by blizzz** [comment]
Is the check done on a regular basis or only on the apps page? And what about CLI? If regularly, we can remove the php-ldap check on the settings page with this move.

**Comment by DeepDiver1975** [comment]
> Is the check done on a regular basis or only on the apps page?

This only happens on the apps management page for not yet installed apps.
We could think about applying these checks in other locations as well - e.g. loading a app - the app will only be loaded if all requirements are fullfilled.

**Comment by nickvergessen** [comment]
change itself looks good, although I didn't test it:
:+1:

**Comment by LukasReschke** [comment]
Works here :+1:

**Pull request merged**
