### PR TITLE
separate given step to create user from when step

### PR DESCRIPTION
**Pull request by individual-it**
## Description
- Given steps should not been forced to use a specific way (API/OCC/webUI) to achieve a specific state
- Given steps don't need to be checked, we assume they work

## Motivation and Context
when using this step for LDAP tests it fails because in LDAP we do not create users, but skip the user creation and believe they exist. Still the given step should work and not throw an exception.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by individual-it** [comment]
backport in  #32246

**Comment by phil-davis** [comment]
```
Given steps don't need to be checked, we assume they work
```
Actually I would like to see that ``Given`` steps check themselves a little bit (e.g. they check the HTTP status) so that they do explode if they obviously go wrong. That makes it a little bit easier when something goes wrong in the environment - you see the scenario explode early, rather than thinking that a ``Then`` test failed because there is a real bug.

``When`` steps should not check anything really (maybe only explode if the whole network is down). It is best if it is one of the ``Then``` steps that fails - then it should be easier to understand exactly which thing went wrong.

But in the case here, we really do have expected ``Given`` cases where we "assume" the action happened, without any evidence.

**Comment by individual-it** [comment]
I guess in this case we could check if the user really exists, that should work on local and on external userbackends. But currently `theUserShouldExist()` does not do really anything

**Comment by phil-davis** [comment]
It's fine like it is for now. Some day I would like to do a general refactoring:

1) Separate all ``Given``` and ``When``
2) Make all the ``Given`` have some sort of "reasonably think it worked" check built-in to the method
3) Remove bonus checks from ``When`` steps, in most cases. Let it 99% pass through to be the responsibility of ``Then`` checks to confirm the ``When`` statements under test have worked.

**Comment by phil-davis** [comment]
I added an extra commit to remove various duplicated "Given user has been created" steps that now cause failures. The commit has also been added to the backport.

**Pull request merged**
