### PR TITLE
Use baseUrl as provided

### PR DESCRIPTION
**Pull request by DeepDiver1975**
I was not able to start the tests using the plain config file

### CODE REVIEW

**Comment by LukasReschke** [comment]
Did you try to run it using `➜  integration git:(solve-csrf-for-good) ✗ bash run.sh features/webdav-related.feature`?

**Comment by DeepDiver1975** [comment]
Run.sh works but not if you run behat directly

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG ping

**Comment by SergioBertolinSG** [comment]
👍  Federation tests still work.

**Pull request merged**
