### PR TITLE
Add config value for TTL of files in cache folder before removed by garbage collection

### LINKED ISSUE #23455: Make chunk cache ttl configurable
### Steps to reproduce
1. Start uploading a very large file (e.g. 10 GB) via owncloud client
2. Use uploading computer as usual (let it go to sleep, shut it down over night, don't have an internet connection all the time)

### Expected behaviour
 - ocClient starts to upload the large file in 5MB chunks.
 - It pauses once in a while (no connection, computer goes to sleep or is shut down).
 - It resumes uploading after the connection is established again
 - Upload finishes after all chunks are uploaded

### Actual behaviour
 - ocClient starts to upload the large file in 5MB chunks.
 - It pauses once in a while (no connection, computer goes to sleep or is shut down).
 - It resumes uploading after the connection is established again
 - **Chunks older than one day are removed by the Garbage Collection**
 - ocClient detects that a good amount of chunks is missing (as they were deleted by GC)
 - Starts to upload these chunks again
 - During that, other now outdated chunks are deleted

Problem: The upload takes forever as the client is not able to upload all chunks in 24 hours.

#### Fix
You can fix that behaviour by increasing the default `ttl` in https://github.com/owncloud/core/blob/master/lib/private/cache/file.php#L114 to a greater value.

It would be nice if this value could be configurable via the config file. As I have more than enough disc space left it would be no problem to increase it to multiple days or a week (I hardcoded it now).

### Server configuration
**Operating system**:
Debian 8.3 amd64
**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Nov 28 2015 14:05:48
**Database:**
mysql  Ver 14.14 Distrib 5.5.47
**PHP version:**
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 (stable)
**Updated from an older ownCloud or fresh install:**
Updated from multiple older ownCloud versions
**Where did you install ownCloud from:**
Linux distribution packages (from Open Build Service) 
**Signing status (ownCloud 9.0 and above):**
`No errors have been found.`
**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - files_external
  - search_lucene
  - user_external
  - user_ldap
```
**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "oc22d9880cdf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.osnaware.de"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/owncloud.osnaware.de",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "osnaware.de",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.osnaware.de",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 4,
        "mail_smtpsecure": "tls",
        "theme": "",
        "maintenance": false,
        "forceSSLforSubdomains": true,
        "singleuser": false,
        "updatechecker": false,
        "trashbin_retention_obligation": "auto"
    }
}
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
ownCloud Client – Version 2.1.1 (build 3107)
**Operating system:**
OS X El Capitan (10.11.3)

### PR DESCRIPTION
**Pull request by fkammer**
Closes #23455 

Excerpt from issue:
### Steps to reproduce
1. Start uploading a very large file (e.g. 10 GB) via owncloud client
2. Use uploading computer as usual (let it go to sleep, shut it down over night, don't have an internet connection all the time)
### Expected behaviour
- ocClient starts to upload the large file in 5MB chunks.
- It pauses once in a while (no connection, computer goes to sleep or is shut down).
- It resumes uploading after the connection is established again
- Upload finishes after all chunks are uploaded
### Actual behaviour
- ocClient starts to upload the large file in 5MB chunks.
- It pauses once in a while (no connection, computer goes to sleep or is shut down).
- It resumes uploading after the connection is established again
- **Chunks older than one day are removed by the Garbage Collection**
- ocClient detects that a good amount of chunks is missing (as they were deleted by GC)
- Starts to upload these chunks again
- During that, other now outdated chunks are deleted

Problem: The upload takes forever as the client is not able to upload all chunks in 24 hours.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
I'm wondering if we better set this in the chunking code instead of adjusting the default which is used in different places as well.

https://github.com/owncloud/core/blob/master/lib/private/filechunking.php#L70

**Comment by fkammer** [comment]
@DeepDiver1975 Do you mean changing

```
public function store($index, $data) {
    $cache = $this->getCache();
    $name = $this->getPrefix().$index;
    $cache->set($name, $data);
    return $cache->size($name);
}
```

to

```
public function store($index, $data) {
    $cache = $this->getCache();
    $name = $this->getPrefix().$index;
    $ttl = \OC::$server->getConfig()->getSystemValue('cache_folder_gc_ttl', 86400);
    $cache->set($name, $data, $ttl);
    return $cache->size($name);
}
```
in https://github.com/owncloud/core/blob/master/lib/private/filechunking.php#L67-L73

**Comment by fkammer** [comment]
I was wondering if it would be more elegant to update the `mtime` of all corresponding chunks if a new one is added. That should fix the problem for all installations without the need to configure the new variable.

Nevertheless could we keep that variable if someone experiences problems while uploading a large file over multiple days and can't ensure that at least one chunk is uploaded every 24 hours.

**Comment by PVince81** [comment]
> I was wondering if it would be more elegant to update the mtime of all corresponding chunks if a new one is added.

That would be expensive, you'd need to touch the mtime of all existing chunks (which could be a lot) while leaving the current one untouched.

**Comment by PVince81** [comment]
@fkammer also, yes I think https://github.com/owncloud/core/pull/23486#issuecomment-200392080 is correct. Move the config value to the "FileChunking" class.

**Comment by PVince81** [comment]
Looks like the TTL value passed in 'set()` is also likely to cause other trouble, see https://github.com/owncloud/core/issues/24653

Maybe we should get rid of it or make it instance-global instead of file-specific.

**Comment by PVince81** [comment]
Moved to https://github.com/owncloud/core/pull/24812 that implements the correct approach.

**Pull request closed without merging**
