### PR TITLE
[docs-only] fix owncloud central URL

### PR DESCRIPTION
**Pull request by C0rby**
Switched owncloud central URL from `.com` to `.org`.

### CODE REVIEW

**Comment by C0rby** [comment]
I cancelled the CI build since it doesn't make sense for this change.

**Comment by phil-davis** [comment]
> I cancelled the CI build since it doesn't make sense for this change.

The drone logic should be smart enough to not actually run any of the tests for a change to `README.md`

I will restart so that we get green CI in a few minutes.

**Comment by phil-davis** [comment]
It was changed in #39014 and I made this comment:
https://github.com/owncloud/core/pull/39014/files#r671074338

Then I commented https://github.com/owncloud/core/pull/39014/files#r671080914 "Looks like it is fixed already." - I don't know exactly what I was referring to by "it"! Did central exist on owncloud.com for a while?

**Comment by C0rby** [comment]
> > I cancelled the CI build since it doesn't make sense for this change.
> 
> The drone logic should be smart enough to not actually run any of the tests for a change to `README.md`
> 
> I will restart so that we get green CI in a few minutes.

I see, cool thanks!

**Comment by C0rby** [comment]
> Did central exist on owncloud.com for a while?

I'm not sure but I guess so.

**Review by mmattel — APPROVED** [review]
LGTM, 👍 Addressing README.md in this repo only.

**Pull request merged**
