### PR TITLE
[For 10.4] Set 599 HTTP code on error

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
web page shows a 200 status instead of a 500 (or similar) in case of error

## Related Issue
https://github.com/owncloud/core/issues/36072

## How Has This Been Tested?
Load any ownCloud web page without having connection to the DB (ownCloud was installed but the DB connection was cut later)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by jvillafanez** [comment]
Summing up the changes:
* Shutdown log is removed due to unreliability. There is no guarantee the ownCloud's logger will be available during the shutdown (seen when there is no connection to the DB)
* /favicon.ico route will be rewritten to /core/img/favicon.ico. This happens when there is no connection to the DB. The browser doesn't load any page due to the server crash, and make a request to "/favicon.ico" to get the favicon. The change will make the favicon load properly under these circunstances.
* New logger for crashes and improved error handling on the endpoints.

-----------

Notes on the error handling:

The request processing goes as follows:
1. Try to process the request normally. If there isn't any problem, this will generate a normal response.
2. In case the request isn't handled properly and throws an exception that isn't handled, the endpoint should try to log that exception using ownCloud's logging facility and show a proper error message to the user.

    This will likely depend on the endpoint, but generally, the expected HTTP status should be 500 and an error message should be presented to the user. ownCloud already provides some templates that can be used, such as `OC_Template::printExceptionErrorPage`. In this case, we can assume that ownCloud is working properly, and it's an app the one that failed to process the request.

    Note that this exception handling is expected to be light, mostly log the error and show a nice message to the user
3. In case we can't handle the exception, this means that ownCloud is broken and we can't report the error properly to the user. This has been seen if the connection to the DB is stopped, but there could be some additional scenarios.

    In this case we assume that ownCloud is unreliable (we've decided to just log and show an error in step 2, but we couldn't even do that). In order to provide a similar behaviour in all the endpoints, we'll perform the following actions:

    * For web environments (not CLI):
       1. send a "599 Broken" HTTP status to the client. This is intended to help to distinguish between this situation and a 500, which could mean that an app failed the processing but ownCloud still works.
       2. log the exceptions in the "crash-Y-m-d.log" ("crash-2019-11-13.log", for example) file.
    * For CLI:
       1. log the exceptions in the "crash-Y-m-d.log" file (same as above)
       2. log the original exception in the console.

This new crash log file will be generated in the configured data directory, unless the `crashdirectory` is present in the config.php file. If it's present, that directory must exists and must be writable by the web server.

**Comment by ho4ho** [comment]
Really good idea by using 599 for status code?

> 599 Network Connect Timeout Error
>
> This status code is not specified in any RFCs, but is used by some HTTP proxies to signal a network connect timeout behind the proxy to a client in front of the proxy.
>
> https://httpstatuses.com/599
> https://github.com/rmaake1/httpstatuses/issues/22

**Comment by jvillafanez** [comment]
I checked the code list from mozilla, and the 599 didn't appear... it might not be the best code.
I'm opened to suggestions, but I'd like to avoid 500 and 503 in order to distinguish this particular case from other "normal" errors.

**Review by sharidas — COMMENTED** [review]
Haven't tested. But code wise looks ok to me.

**Review by micbar — CHANGES_REQUESTED** [review]
please add a changelog item

**Review by micbar — APPROVED** [review]

**Comment by phil-davis** [comment]
@micbar should this be added to 10.4.0 project?
It might be difficult to add acceptance tests, because we would have to induce a server error to make code paths happen. Existing CI being green is good!

**Comment by micbar** [comment]
@phil-davis 10.4 is ok.
IMO this could be done via Changelog testing.

**Comment by phil-davis** [comment]
Someone needs to decide what to do about the codecov result.

**Comment by VicDeo** [comment]
@micbar  
ErrorHandler: only removed lines, adding tests won't increase coverage (and the method is static too)
Setup.php: 1 line was added into a static method with no proper DI
base.php: static method once again technically it is possible to cover `crashLog` method but it would be not a classic unit-test.


the rest is too low-level for unit tests
console.php 
index.php 
public.php 
remote.php 
status.php

**Review by micbar — APPROVED** [review]
Accepted the PR, Needs a manual Release test during QA phase.
@davitol Please post an example of the crashlog contents.

**Review by phil-davis — APPROVED** [review]
LGTM - as in the discussion, automated tests are not realistic.
Someone with privs needs to override the codecov result and merge.

**Pull request merged**
