### PR TITLE
assign password change error message to correct object

### PR DESCRIPTION
**Pull request by michag86**
fix for  #17817

### CODE REVIEW

**Comment by michag86** [comment]
@MorrisJobke and @LukasReschke could you please take a look at this?

**Comment by MorrisJobke** [comment]
Tested :+1:

**Comment by rullzer** [comment]
Looking good. :+1:

**Comment by rullzer** [comment]
Since the PR is against master this goes into 8.2

@karlitschek probably a good idea to backport this
@DeepDiver1975 you assigned the 8.1.1 milestone so the backport asap and still into 8.1.1?

**Comment by karlitschek** [comment]
great :+1:  please backport

**Comment by rullzer** [comment]
Backport for 8.1 in #17842

**Pull request merged**
