### PR TITLE
Skip version and trash expiry for users that never logged in

### PR DESCRIPTION
**Pull request by butonic**
it saves us trying to set up the filesystem

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by VicDeo** [comment]
:+1:

**Comment by VicDeo** [comment]
Stable9.1: https://github.com/owncloud/core/pull/25745
Stable9: https://github.com/owncloud/core/pull/25742

**Comment by mrow4a** [comment]
@butonic @DeepDiver1975 Lets go back to this pull request and instead of again asking each LDAP users, maybe lets inplement in userManager function callForOCUsers, which will loop through users which loged at least once

**Comment by DeepDiver1975** [comment]
> Lets go back to this pull request and instead of again asking each LDAP users, maybe lets inplement in userManager function callForOCUsers, which will loop through users which loged at least once.

this is the idea of the user account table which will be the only central store where all users are listed in.
This is a topic which We can hopefully battle in 9.2 ......

**Comment by mrow4a** [comment]
Can? We must :D

**Pull request merged**
