### PR TITLE
[Stable8.2] Use a CappedCache in the user database backend

### PR DESCRIPTION
**Pull request by rullzer**
Backport of https://github.com/owncloud/core/pull/24405
Approved in: https://github.com/owncloud/core/pull/24405#issuecomment-216497180

CC: @MorrisJobke @nickvergessen @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I can't login after I checkout this pr. On `stable8.2` this is not a problem.

**Comment by rullzer** [comment]
Ah got it. It was because the capped memory cache had a tiny bug.. lets see if the backport fixes it.

**Comment by rullzer** [comment]
Else I propose to skip this backport.

**Comment by PVince81** [comment]
> had a tiny bug

What bug ?

> the backport fixes it.

Which backport ?

**Comment by nickvergessen** [comment]
> Which backport ?

The commit with name: `Allow indirect set in CappedMemoryCache`

The bug can be easily seen from there. you couldn't do `$cache['key'] = 'new value';` on stable8.2

**Comment by PVince81** [comment]
Ok thanks, I requested a backport here then https://github.com/owncloud/core/pull/21721

**Comment by nickvergessen** [comment]
Whoot, it's in this PR and required for a blue ticket

**Comment by PVince81** [comment]
Ok... I just completely misunderstood @rullzer's statement, didn't see that he did the backport.

Ok then let me test this, also with LDAP.

**Comment by PVince81** [comment]
Login with LDAP, and also background jobs with LDAP users still work :+1:

**Pull request merged**
