### PR TITLE
WebUI feedback when sharing

### LINKED ISSUE #22304: Missing spinner, when creating a share
### Steps
1. Add a `sleep(5);` before https://github.com/owncloud/core/blob/46045ecc528566edcbe302339ce37819e5320e86/apps/files_sharing/api/ocssharewrapper.php#L44
2. Share a file

### Expected
Should see some spinner or anything else, telling the user that we are processing the info.
This is especially important for remote shares, where it might take a bit longer.
E.g. 8.1 (before the sidebar): https://doc.owncloud.org/server/8.1/user_manual/_images/direct-share-2.png

### Actual
blank field, no info anywhere

@PVince81

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #22304

The input field is locked and the spinner is shown.
All is unlocked once it is shared.

CC: @owncloud/designers @owncloud/javascript @nickvergessen

### CODE REVIEW

**Comment by rullzer** [comment]
It seems the background of the spinner is not transparent...

**Comment by MorrisJobke** [comment]
> It seems the background of the spinner is not transparent...

Another one for the https://github.com/owncloud/core/issues/19091


But it is still an improvement. :+1: 

@owncloud/designers Any idea how to improve the spinner look?

**Comment by nickvergessen** [comment]
works :+1:

**Comment by nickvergessen** [comment]
Please create a new issue for the non-transparent spinner issue or use the linked issue from morris

**Pull request merged**
