### PR TITLE
Add FilesPlugin

### LINKED ISSUE #22507: V2 DAV backend is not displaying file properties
### Steps to reproduce
1. Upload a file 
2. Call new WebDAV endpoint: `curl -i -s -k  -X 'PROPFIND' --data-binary $'<?xml version=\"1.0\"?>\x0d\x0a<d:propfind  xmlns:d=\"DAV:\" xmlns:oc=\"http://owncloud.org/ns\">\x0d\x0a  <d:prop>\x0d\x0a    <d:getlastmodified />\x0d\x0a    <d:getetag />\x0d\x0a    <d:getcontenttype />\x0d\x0a    <d:resourcetype />\x0d\x0a    <oc:fileid />\x0d\x0a    <oc:permissions />\x0d\x0a    <oc:size />\x0d\x0a    <d:getcontentlength />\x0d\x0a    <oc:tags />\x0d\x0a    <oc:favorite />\x0d\x0a    <oc:comments-unread />\x0d\x0a    <oc:owner-display-name />\x0d\x0a  </d:prop>\x0d\x0a</d:propfind>' 'http://user0:123456@localhost:8080/remote.php/dav/files/user0/myFileToComment.txt'`
3. Call old WebDav endpoint: `curl -i -s -k  -X 'PROPFIND' --data-binary $'<?xml version=\"1.0\"?>\x0d\x0a<d:propfind  xmlns:d=\"DAV:\" xmlns:oc=\"http://owncloud.org/ns\">\x0d\x0a  <d:prop>\x0d\x0a    <d:getlastmodified />\x0d\x0a    <d:getetag />\x0d\x0a    <d:getcontenttype />\x0d\x0a    <d:resourcetype />\x0d\x0a    <oc:fileid />\x0d\x0a    <oc:permissions />\x0d\x0a    <oc:size />\x0d\x0a    <d:getcontentlength />\x0d\x0a    <oc:tags />\x0d\x0a    <oc:favorite />\x0d\x0a    <oc:comments-unread />\x0d\x0a    <oc:owner-display-name />\x0d\x0a  </d:prop>\x0d\x0a</d:propfind>' 'http://user0:123456@localhost:8080/remote.php/webdav/myFileToComment.txt'`

### Expected behaviour
Properties such as `oc:fileid` are properly filled out. That works in the old endpoint:

```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
 <d:response>
  <d:href>/remote.php/webdav/myFileToComment.txt</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Thu, 18 Feb 2016 18:11:18 GMT</d:getlastmodified>
    <d:getetag>&quot;a92001619ea96db36d5ea4d061957532&quot;</d:getetag>
    <d:getcontenttype>text/plain</d:getcontenttype>
    <d:resourcetype/>
    <oc:fileid>1000</oc:fileid>
    <oc:permissions>RDNVW</oc:permissions>
    <d:getcontentlength>28</d:getcontentlength>
    <oc:tags/>
    <oc:favorite></oc:favorite>
    <oc:comments-unread>0</oc:comments-unread>
    <oc:owner-display-name>user0</oc:owner-display-name>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <oc:size/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```
### Actual behaviour

Properties such as `oc:fileid` are empty. That's what the new endpoint returns:

```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns">
 <d:response>
  <d:href>/remote.php/dav/files/user0/</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Thu, 18 Feb 2016 18:11:18 GMT</d:getlastmodified>
    <d:resourcetype>
     <d:collection/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <d:getetag/>
    <d:getcontenttype/>
    <oc:fileid/>
    <oc:permissions/>
    <oc:size/>
    <d:getcontentlength/>
    <oc:tags/>
    <oc:favorite/>
    <oc:comments-unread/>
    <oc:owner-display-name/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/remote.php/dav/files/user0/myFileToComment.txt</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Thu, 18 Feb 2016 18:11:18 GMT</d:getlastmodified>
    <d:getetag>&quot;a92001619ea96db36d5ea4d061957532&quot;</d:getetag>
    <d:getcontenttype>text/plain</d:getcontenttype>
    <d:resourcetype/>
    <d:getcontentlength>28</d:getcontentlength>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <oc:fileid/>
    <oc:permissions/>
    <oc:size/>
    <oc:tags/>
    <oc:favorite/>
    <oc:comments-unread/>
    <oc:owner-display-name/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/remote.php/dav/files/user0/welcome.txt</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Thu, 18 Feb 2016 17:42:57 GMT</d:getlastmodified>
    <d:getetag>&quot;c6b42687f5de5cd41fa058efca058fce&quot;</d:getetag>
    <d:getcontenttype>text/plain</d:getcontenttype>
    <d:resourcetype/>
    <d:getcontentlength>163</d:getcontentlength>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <oc:fileid/>
    <oc:permissions/>
    <oc:size/>
    <oc:tags/>
    <oc:favorite/>
    <oc:comments-unread/>
    <oc:owner-display-name/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

<hr/>

cc @DeepDiver1975 Thoughts?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #22507

@rullzer @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Works :+1:

**Comment by rullzer** [comment]
Note that we are still missing stuff:

* tags
* favorite
* comments

But :+1: since it at least fixes part of it.

**Comment by PVince81** [comment]
:+1:

also missing the files report plugin to be able to filter, but something for another time.

**Comment by rullzer** [comment]
https://travis-ci.org/owncloud/core/builds/110327411

Mmmmm so it seems this fails due to the checksum still. Since carddav and caldav elements are deep down Files. But apparently they get converted to `OCA\DAV\Connector\Sabre\File`. Which is kind of strange.

**Comment by rullzer** [comment]
Ok got it... PR incomming

**Comment by rullzer** [comment]
- [ ] Requires https://github.com/owncloud/core/pull/22515

**Comment by DeepDiver1975** [comment]
rebased

**Comment by rullzer** [comment]
All is well now!

**Pull request merged**
