### PR TITLE
Catch StorageNotAvailableException while formatting the share

### PR DESCRIPTION
**Pull request by jvillafanez**
The getById method called while formatting could go down to the storage
if somehow the node needs to be updated. If so, the storage where the
node is could not be available, causing the exception to pop up.
Such exception causes the list of shares to be broken since it wasn't
being caught.

## Description
Catch a possible StorageNotAvailableException that could be thrown while formatting the shares.
This specially affects to the share listing, which could be broken and the UI might not show any local share if such exception happens.

So far, this has been detected only while listing the shares, and the steps to reproduce aren't fully clear. There are some other locations for the `formatShare` method being called, although it's expected to behave better since other similar exception that could happen such as `NotFoundException` aren't being handled in those places.

## Related Issue
Related to https://github.com/owncloud/enterprise/issues/4250

## Motivation and Context
Could lead to an empty list of shares

## How Has This Been Tested?
Not tested yet

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by cdamken** [comment]
Works with Damken-Cloud!

**Review by karakayasemi — DISMISSED** [review]

**Comment by karakayasemi** [comment]
We need changelog entry before merge.

**Comment by jvillafanez** [comment]
I assume we don't need to rush so this will be in 10.7. I haven't been able to reproduce the scenario locally, so maybe the conditions to reach the issue cannot happen in the recent versions.

**Comment by jvillafanez** [comment]
Added changelog item

**Review by karakayasemi — APPROVED** [review]

**Pull request merged**
