### PR TITLE
Revert "Move trashbin specific CSS that modifies sidebar"

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Reverts owncloud/core#19702

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@nickvergessen @PVince81 @MorrisJobke

**Comment by PVince81** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
so - somebody needs to reopen the PR for 8.2.1 again

**Comment by DeepDiver1975** [comment]
> so - somebody needs to reopen the PR for 8.2.1 again

https://github.com/owncloud/core/pull/19714

**Pull request merged**
