### PR TITLE
Explicitly specify status code 200 as response code

### LINKED ISSUE #17586: Upgrading to 8.1 breaks Android client upload / Sabre HEAD request
The Android client refused to upload anything after upgrading to Owncloud 8.1.

Tracked it down to an issue with HEAD requests in WebDav. See https://github.com/fruux/sabre-dav/issues/684 for the upstream issue.

### PR DESCRIPTION
**Pull request by LukasReschke**
Potentially fixes https://github.com/owncloud/core/issues/17586, as advised in https://github.com/fruux/sabre-dav/issues/684#issuecomment-134512866

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: makes sense, but could not test as I cannot reproduce the original issue

**Comment by MorrisJobke** [comment]
@tohojo @mhzawadi @demofreak @wvandelli @magicmyth @teemu-torma Can you try to test this if this fixes #17586 for you? Thanks

**Comment by wvandelli** [comment]
In a simple test, it works for me, I can successfully upload from the Android client. I will leave the patch in place. In case there are any side effects, I'll report them here

Thank you guys.

**Comment by teemu-torma** [comment]
It appears to fix the issue for me too.  Thanks.

**Comment by mhzawadi** [comment]
Have tested an upload and it still works, but I got my setup working anyway.

Good job.

**Comment by MorrisJobke** [comment]
@mhzawadi @wvandelli @teemu-torma Thanks for testing :)

Code looks good :+1:

**Comment by MorrisJobke** [comment]
@LukasReschke Backport?

**Comment by DemoFreak** [comment]
Sorry, but it doesn't solve the problem here.
As my installation still is on 8.1, I simply inserted the line 64 from the patch in lib/private/connector/sabre/dummygetresponseplugin.php (the tests folder do not exist here).
When I try to upload new files with Android FolderSync, I still get a 401 HTTP error and then a 404 to PROPFIND, and then a 500 to PUT.
The same file uploaded by the desktop client results in HTTP 207 to PROPFIND and 201 to PUT, and the file is successfully uploaded.

**Comment by LukasReschke** [comment]
> @LukasReschke Backport?

No idea if some sync clients would break… Just my personal opinion, when touching WebDAV I'm hesitant…

@DemoFreak Please file a new issue. Yours look to be unrelated to #17586 according to your log. Also ensure to use the issue template. Thanks.

**Comment by DemoFreak** [comment]
@LukasReschke Why do you think it's unrelated?
- Android file upload stopped after update to 8.1
- Desktop upload works
- Log files tell something regarding authorization

But ok, I'll file a new issue anyway.

**Comment by LukasReschke** [comment]
> @LukasReschke Why do you think it's unrelated?

Yes. Same symptoms but your log file indicates another problem as far I can tell :-)

**Comment by DemoFreak** [comment]
Filed #18568

**Comment by delumerlino** [comment]
Does not work for me too...

**Pull request merged**
