### PR TITLE
[stable8] Fix parsing of sharetime as string

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #17489 to stable8

Approval: https://github.com/owncloud/core/pull/17489#issuecomment-125935048

@PVince81 @rullzer @nazar-pc Please test :)

### CODE REVIEW

**Comment by rullzer** [comment]
Again, very familiar. :+1:

**Comment by MorrisJobke** [comment]
@PVince81 @nazar-pc Mind to review this easy one?

**Comment by nazar-pc** [comment]
It is the same actually)

**Comment by MorrisJobke** [comment]
@nazar-pc needs a review nevertheless ;)

**Comment by PVince81** [comment]
The code looks good, regular exp date still appears :+1: 
Note: I can't test the actual issue this is fixing.

**Pull request merged**
