### PR TITLE
setUserVars() should only attempt substitution with strings

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Otherwise funky things happen like `true (bool)` => `'1' (string)`

@PVince81 @DeepDiver1975 @MorrisJobke @icewind1991

### CODE REVIEW

**Comment by Xenopathic** [comment]
I think I've caught all the `$var === 'true'` lines in the external storages. A quick debug shows them working as expected at least

**Comment by PVince81** [comment]
Tested with the Amazon S3 mount :+1:

**Comment by Xenopathic** [comment]
:warning: Hold up, I forgot about migrating legacy storages that actually use strings to represent booleans.

**Comment by Xenopathic** [comment]
OK, that latest commit adds some conversion stuff for string booleans to real booleans. Everything is unit tested. Please test setting up a checkbox-containing storage in stable8 (e.g. Amazon S3, FTP, SMB_OC), check `mount.json` to ensure string booleans are saved, then either copy that config to an instance running this branch or upgrade your instance. Load the admin interface, make sure the checkboxes are still correctly checked, and/or do some debugging to make sure the storages themselves are getting real booleans.

**Comment by Xenopathic** [comment]
@PVince81 Please re-review

**Comment by PVince81** [comment]
Hmm I see that upgrading from stable8 to stable8.1 already replaces the strings with booleans in "mount.json". Okay, so that's probably the moment where the problem started happening with string substitution.

I tried the steps like you did, reusing the config that had strings instead of booleans directly on this branch.

:+1: works

**Comment by Xenopathic** [comment]
@MorrisJobke @icewind1991 @LukasReschke Please review (and the backport if you don't mind :smile:)

**Comment by MorrisJobke** [comment]
Tested and code looks good :+1:

**Pull request merged**
