### PR TITLE
Stable8.2 provis api group special char

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Backport of https://github.com/owncloud/core/pull/20961

Please review @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Moving to 8.2.8 as we're post RC1

**Comment by SergioBertolinSG** [comment]
OCA\Provisioning_API\Tests\GroupsTest::testAddGroupEmptyGroup
Undefined property: OCA\Provisioning_API\Groups::$request

This will need a different approach.

**Comment by PVince81** [comment]
If it is too complicated I suggest to not backport this as it's not really critical.

**Comment by SergioBertolinSG** [comment]
Failing because EEEPHP Fatal error:  Call to undefined method OC\Group\Manager::method() in /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/apps/provisioning_api/tests/groupstest.php on line 262

**Comment by PVince81** [comment]
@SergioBertolinSG I suggest closing this. There are more important tests to work on.

**Comment by SergioBertolinSG** [comment]
Yes, I agree.

**Pull request closed without merging**
