### PR TITLE
Set page title for the tags file list

### LINKED ISSUE #39556: System tags: page header (HTML title) is not changed
### Steps to reproduce
1. Login as User
2. Open "Shared with you"
3. Open "Tags"

### Expected behaviour
Title should change like "Shared with you" to somethin with "Tags"
### Actual behaviour
Title of the previous view ("Shared with you").
### Server configuration
**ownCloud version:** (see ownCloud admin page)
10.8.0
**Systemtag app version:**
0.3.0

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

### Client configuration
**Browser:**
Google Chrome, Firefox
**Operating system:**
Windows 10
### Logs
No log outputs (webbrowser)

### PR DESCRIPTION
**Pull request by JammingBen**
## Related Issue

- Fixes https://github.com/owncloud/core/issues/39556

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
works - I can go back-and-forth between Favorites/Shared with you/Shared with others/... and Tags and the page title changes correctly.

**Comment by phil-davis** [comment]
This PR is targeted to `master` branch.
Are we not fixing this little thing for 10.9.0?

**Comment by JanAckermann** [comment]
@phil-davis TBH, I think it is not that good to pack too much new stuff/fixes after a code freeze :/

**Comment by JammingBen** [comment]
As we're now in code freeze, I think we should only include regressions or critical issues in the `release-10.9.0` branch from now on. I know this is just a "little" fix which could we included easily, but we keep adding stuff which eventually has to be tested as well. At some point, we just have to draw a line 🤷

**Pull request merged**
