### PR TITLE
No longer evaluate appinfo/version

### LINKED ISSUE #17598: Only read app version from one source
See https://github.com/owncloud/core/issues/17457

The updater app had 0.5 in info.xml but 0.6 in version, and this caused update loops.

The code that reads app versions needs to be changed to only read the version in a single location.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://github.com/owncloud/core/issues/17598

### CODE REVIEW

**Comment by nickvergessen** [comment]
Unit tests are odd:
```
Test_Installer::testInstallApp
Undefined index: version

/ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/lib/private/installer.php:393
/ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/lib/private/installer.php:89
/ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/tests/lib/installer.php:47
```

**Comment by PVince81** [comment]
:+1:

@nickvergessen seems he fixed the unit test

**Comment by nickvergessen** [comment]
testapp2 contains a `__MACOSX` folder, intentional @DeepDiver1975 ?

Otherwise looks good

**Comment by DeepDiver1975** [comment]
> testapp2 contains a __MACOSX folder, intentional @DeepDiver1975 ?

was there before - no idea

**Comment by nickvergessen** [comment]
:+1: then

**Comment by PVince81** [comment]
This broke the WND app and might break others too. I'll see if I can adjust them quickly for 9.0.

This makes me wonder whether it was too early for this change.

**Comment by PVince81** [comment]
Revert PR here https://github.com/owncloud/core/pull/22829

**Pull request merged**
