### PR TITLE
[9.0] Correctly default to null and add type hint

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of https://github.com/owncloud/core/pull/22896

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by blizzz** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek @cmonteroluque This caused sync errors on my existing clients. I put it into 9.0 - feel free to move this to 9.0.1 if this is accepted to be broken.

**Comment by DeepDiver1975** [comment]
> This caused sync errors on my existing clients.

unfortunately a showstopper @karlitschek @cmonteroluque 

note to self - we need to unit test the v1 and v2 webdav entrypoints :angry:

**Comment by karlitschek** [comment]
argh. Please backport/merge. 
@cmonteroluque Is it still possible to do new packages?

**Pull request merged**
