### PR TITLE
setup storage wrappers before setting up the filesystem

### PR DESCRIPTION
**Pull request by icewind1991**
Make wrapping more predictable.

cc @DeepDiver1975 @schiesbn

### CODE REVIEW

**Comment by Xenopathic** [comment]
```
11:25:19 PHP Fatal error:  Call to a member function getAll() on null in /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/lib/private/files/filesystem.php on line 209
11:25:19 PHP Stack trace:
11:25:19 PHP   1. {main}() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/occ:0
11:25:19 PHP   2. require_once() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/occ:11
11:25:19 PHP   3. Symfony\Component\Console\Application->run() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/console.php:74
11:25:19 PHP   4. Symfony\Component\Console\Application->doRun() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/3rdparty/symfony/console/Symfony/Component/Console/Application.php:126
11:25:19 PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/3rdparty/symfony/console/Symfony/Component/Console/Application.php:195
11:25:19 PHP   6. Symfony\Component\Console\Command\Command->run() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/3rdparty/symfony/console/Symfony/Component/Console/Application.php:874
11:25:19 PHP   7. OC\Core\Command\Maintenance\Install->execute() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php:253
11:25:19 PHP   8. OC\Setup->install() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/core/command/maintenance/install.php:74
11:25:19 PHP   9. OC_User::login() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/lib/private/setup.php:345
11:25:19 PHP  10. OC_Util::setupFS() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/lib/private/user.php:244
11:25:19 PHP  11. OC\Files\Filesystem::addStorageWrapper() /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/lib/private/util.php:142
```

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by schiesbn** [comment]
looks good :+1:

**Comment by MorrisJobke** [comment]
This introduced a regression for background jobs and file handling: #17513 and owncloud/enterprise#867 

cc @icewind1991

**Comment by icewind1991** [comment]
I think the difference is that the `'setup'` hook isn't triggered when no user is loggedin while `'preSetup'` is.

The trashbin wrapper will need to handle the cases of being applied without a user being logged in

**Pull request merged**
