### PR TITLE
[9.0] Make sure that the return value is an array

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport #22904 

Missing approval @PVince81 @DeepDiver1975 @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport for 9.0.1

**Comment by MorrisJobke** [comment]
:+1:

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
Tested, this fixes https://github.com/owncloud/core/issues/22931 and removes the warning.

**Pull request merged**
