### PR TITLE
[stable9] remember email when setting expiration date

### PR DESCRIPTION
**Pull request by ChristophWurst**
Simple fix for 9 as https://github.com/owncloud/core/pull/24149 touches too much unrelated code and hence potentially breaks things.

~~Backport of https://github.com/owncloud/core/pull/23980~~, fixes https://github.com/owncloud/core/issues/22947

Approval: https://github.com/owncloud/core/pull/23980#issuecomment-212352956

@PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Tested, works :+1: 

Second review ? @rullzer @MorrisJobke @schiesbn

**Comment by rullzer** [comment]
:+1:

**Comment by rullzer** [comment]
@ChristophWurst any reason this is still on Developing?

**Comment by ChristophWurst** [comment]
> @ChristophWurst any reason this is still on Developing?

Nope. I wanted to wait for CI but forgot to change the label then, sorry

**Pull request merged**
