### PR TITLE
Stable8: 15145

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of #15145

@icewind1991 As discussed.

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@PVince81 please review ;)

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
@karlitschek please confirm this backport

**Comment by karlitschek** [comment]
backport is fine :-)

**Comment by jvillafanez** [comment]
Validated using the steps from https://github.com/owncloud/core/pull/15145

**Pull request merged**
