### PR TITLE
[stable10] Fix not-useful capabilities unit tests

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #31587

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by phil-davis** [comment]
wot I dun?
```
PHP Fatal error: Cannot use OCP\Files\File as File because the name is already in use in /drone/src/tests/lib/Share20/ManagerTest.php on line 28
```

**Comment by PVince81** [comment]
usually appears on some setups with older PHP versions when having a `use` statement that, for some mysterious reasons, clashes with another use statement. It happened to me locally years ago while on other setups it didn't. Could be related to class loading order...

Maybe restart the build and hope ? :see_no_evil:

**Comment by phil-davis** [comment]
I  think another PR ggot merged to ```stable10`` in the last hours - my ``ManagerTest.php`` did have  duplicate ``use`` statement. Rebase looks like it fixed it - we will see.

**Pull request merged**
