### PR TITLE
Backport files external fixes

### LINKED ISSUE #13781: External Storage available user GUI issue
### Expected behavior

I'm setting up some external storage to an smb share to be restricted by user/group. In testing I've just added it to my account and one other persons. I see the two users in mount.json defined by their active directory uid. 

When I go back to the admin page I see the mounts listed but the available users box is empty instead of showing the two grey buttons with my name and the other guy's. I've then added a third person. Only they show up in the web interface but all 3 users show in mount.json. If I reload the admin page again the box is empty. 

The behavior is the same on 6.0.6 and 7.0.4. And no buttons for users means no little x's to click on to remove a user. I can do it in the mount.json file but it'd be better not to. 

### Actual behavior
Should be showing name at Available for box with x in fron of username in EXTERNAL STOREGE section 

### Steps to reproduce

1) Add SMB add user  pointed to SMB ...but i'm unable reproduce issue 
2) My system behave as design

### Server configuration

Operating system:centos 6.6 

Web server:Apache 2.2.15

Database:

PHP version:5.5.20

ownCloud version:7.0.4

Storage backend:

Client configuration

Client version:

Operating system:

OS language:

Installation path of client:

### Logs

Logs /image can be found at s3 under support/github-issues/core/13781
@MorrisJobke

### LINKED ISSUE #15800: External storage: when admin makes available for an user from LDAP the user badge is not shown when returning to admin page
### Steps to reproduce
1. Create new external storage in admin pageand make it available to an user from  LDAP selecting from dropdown
2. Exit the admin page and then return
3. The "available for" field is empty. If you search the user you previously added is no more available on the list

Repeat the same with a local user and the problem doesn't exist. The users gets the correct external storage shown.

### Expected behaviour
User badge should be shown.

### Actual behaviour
The field is empty. On HTML side you see data-applicable-users containing the list of the enabled users (e.g.: '["D501C74A-3BD8-437C-A0AB-D80BA42E1436"]' which is the GUID of my LDAP user).

### Server configuration
**Operating system**: RHEL 6
**Web server:** Apache 2.2.15
**Database:** Mysql 5
**PHP version:** 5.4.16
**ownCloud version:** 7.0.3
**Updated from an older ownCloud or fresh install:** fresh install
**List of activated apps:** 
Enabled:
 - activity
 - admin_dependencies_chk
 - appVNCsafe
 - contacts
 - documents
 - files
 - files_external
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - search_lucene
 - templateeditor
 - user_ldap

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '0984980098',
  'passwordsalt' => 'pòoiuhhulikhlkjhljk',
  'trusted_domains' => 
  array (
    /*0 => 'site0',
    1 => 'site1',*/
    2 => 'site2',
  ),
  'datadirectory' => '/var/opt/owncloud/data',
  'overwrite.cli.url' => 'https://site3',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '*******',
  'installed' => true,
  'appstoreenabled' => false,
  'updatechecker' => false,
  'has_internet_connection' => false,
  'loglevel' => '1',
  'log_query' => false,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'skeletondirectory' => '/opt/owncloud/ic_skeleton/',
  'customclient_desktop' => 'https://site3/client/',
  'customclient_android' => 'https://site3/client/client_android.apk',
  'customclient_ios' => 'https://itunes.apple.com/us/app/owncloud/id543672169?mt=8',
  'singleuser' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'ic4sync',
  'mail_domain' => 'site3.it',
  'mail_smtphost' => 'mailserver.site3',
  'mail_smtpport' => '25',
  'maintenance' => false,
  'theme' => 'ic4sync',
);

```

**Are you using external storage, if yes which one:** smb with OC login

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)

```
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                |                                                                                                                                                                |
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport     | 1                                                                                                                                                              |
| hasPagedResultSupport        |                                                                                                                                                                |
| homeFolderNamingRule         |                                                                                                                                                                |
| lastJpegPhotoLookup          | 0                                                                                                                                                              |
| ldapAgentName                | CN=owncloud,CN=Users,DC=clic,DC=intra,DC=company,DC=it                                                                                                      |
| ldapAgentPassword            | ***                                                                                                                                                            |
| ldapAttributesForGroupSearch |                                                                                                                                                                |
| ldapAttributesForUserSearch  |                                                                                                                                                                |
| ldapBackupHost               | dc2.clic.intra.company.it                                                                                                                            |
| ldapBackupPort               | 389                                                                                                                                                            |
| ldapBase                     | DC=clic,DC=intra,DC=company,DC=it                                                                                                                           |
| ldapBaseGroups               | DC=clic,DC=intra,DC=company,DC=it                                                                                                                           |
| ldapBaseUsers                | DC=clic,DC=intra,DC=company,DC=it                                                                                                                           |
| ldapCacheTTL                 | 600                                                                                                                                                            |
| ldapConfigurationActive      | 1                                                                                                                                                              |
| ldapEmailAttribute           | mail                                                                                                                                                           |
| ldapExperiencedAdmin         | 0                                                                                                                                                              |
| ldapExpertUUIDGroupAttr      |                                                                                                                                                                |
| ldapExpertUUIDUserAttr       |                                                                                                                                                                |
| ldapExpertUsernameAttr       |                                                                                                                                                                |
| ldapGroupDisplayName         | cn                                                                                                                                                             |
| ldapGroupFilter              | (&(|(objectclass=group))(|(cn=OC_*)))                                                                                                                          |
| ldapGroupFilterGroups        |                                                                                                                                                                |
| ldapGroupFilterMode          | 1                                                                                                                                                              |
| ldapGroupFilterObjectclass   | group                                                                                                                                                          |
| ldapGroupMemberAssocAttr     | member                                                                                                                                                         |
| ldapHost                     | DC.clic.intra.company.it                                                                                                                            |
| ldapIgnoreNamingRules        |                                                                                                                                                                |
| ldapLoginFilter              | (&(&(|(objectclass=user))(|(memberof=CN=CU_00000000000111111,OU=ORG00000000000111111,OU=CLOUD,DC=clic,DC=intra,DC=company,DC=it)))(|(sAMAccountName=%uid))) |
| ldapLoginFilterAttributes    | sAMAccountName                                                                                                                                                 |
| ldapLoginFilterEmail         | 0                                                                                                                                                              |
| ldapLoginFilterMode          | 1                                                                                                                                                              |
| ldapLoginFilterUsername      | 0                                                                                                                                                              |
| ldapNestedGroups             | 0                                                                                                                                                              |
| ldapNoCase                   | 1                                                                                                                                                              |
| ldapOverrideMainServer       | 0                                                                                                                                                              |
| ldapPagingSize               | 500                                                                                                                                                            |
| ldapPort                     | 389                                                                                                                                                            |
| ldapQuotaAttribute           |                                                                                                                                                                |
| ldapQuotaDefault             | 3221225472                                                                                                                                                     |
| ldapTLS                      | 0                                                                                                                                                              |
| ldapUserDisplayName          | displayname                                                                                                                                                    |
| ldapUserFilter               | (&(|(objectclass=user))(|(memberof=CN=CU_00000000000111111,OU=ORG00000000000111111,OU=CLOUD,DC=clic,DC=intra,DC=company,DC=it)))                            |
| ldapUserFilterGroups         | CA_00000000000111111                                                                                                                                           |
| ldapUserFilterMode           | 1                                                                                                                                                              |
| ldapUserFilterObjectclass    | user                                                                                                                                                           |
| ldapUuidGroupAttribute       | auto                                                                                                                                                           |
| ldapUuidUserAttribute        | auto                                                                                                                                                           |
| turnOffCertCheck             | 0                                                                                                                                                              |
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

### Client configuration
**Browser:** Firefox 37, Chrome 41

**Operating system:** Ubuntu 12.04

#### Web server error log
```
[Wed Apr 22 10:34:39 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:34:39 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:34:40 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/breadcrumb.svg, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:34:46 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:34:46 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:34:46 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/loading.gif, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:49:23 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/loading-small.gif, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:11 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:11 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:13 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/breadcrumb.svg, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:29 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:29 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:29 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/loading.gif, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:39 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/loading-small.gif, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:58 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:58 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:56:59 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/breadcrumb.svg, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:57:20 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:57:20 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:57:20 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/loading.gif, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:58:16 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:58:16 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:58:18 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/breadcrumb.svg, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:58:25 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/loading.gif, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 10:59:05 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/loading-small.gif, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 11:19:03 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/favicon.ico
[Wed Apr 22 11:37:29 2015] [error] [client 10.5.104.205] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-wide.svg, referer: https://site3/public.php?service=files&t=b54655890af8dde073a8f0e8ab05bd04
[Wed Apr 22 11:37:30 2015] [error] [client 10.5.104.205] File does not exist: /opt/owncloud/themes/ic4sync/core/img/breadcrumb.svg, referer: https://site3/public.php?service=files&t=b54655890af8dde073a8f0e8ab05bd04
[Wed Apr 22 12:29:21 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 12:29:21 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 12:29:22 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/breadcrumb.svg, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 12:29:26 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 12:29:26 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 12:29:26 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/loading.gif, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 12:50:36 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/logo-icon.svg, referer: https://site3/themes/ic4sync/core/css/header.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 12:50:36 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/actions, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc
[Wed Apr 22 12:50:45 2015] [error] [client 10.5.93.175] File does not exist: /opt/owncloud/themes/ic4sync/core/img/loading.gif, referer: https://site3/themes/ic4sync/core/css/styles.css?v=41dc06ecd6457bf799abd7a59cc7adcc

```

#### ownCloud log (data/owncloud.log)
I have several messages like these. If you want the full log of today ask me, is over 32k lines.
```
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-04-22T10:33:24+00:00"}
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-04-22T10:33:24+00:00"}
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-04-22T10:33:24+00:00"}
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-04-22T10:33:30+00:00"}
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-04-22T10:33:40+00:00"}
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-04-22T10:33:40+00:00"}
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-04-22T10:33:40+00:00"}
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-04-22T10:33:44+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/opt\/owncloud\/lib\/private\/request.php#118","level":3,"time":"2015-04-22T10:33:47+00:00"}
{"app":"PHP","message":"Undefined offset: 0 at \/opt\/owncloud\/lib\/private\/request.php#118","level":3,"time":"2015-04-22T10:33:47+00:00"}

```

### PR DESCRIPTION
**Pull request by blizzz**
Fixes #15800 
Fixes #13781

The fix is already in OC 8 and master, probably was missed to backport to stable7 in https://github.com/owncloud/core/issues/10558 (a while ago)

Please test and review @butonic @LukasReschke @remixtj @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
@karlitschek please confirm this backport to stable7

**Comment by remixtj** [comment]
I confirm that this patch solved issue. Thank you very much!

**Comment by karlitschek** [comment]
please backport after 8.0.3

**Comment by PVince81** [comment]
@karlitschek you mean after 7.0.6 ?

**Comment by karlitschek** [comment]
lol. yes

**Comment by blizzz** [comment]
Oops, i should have asked right away, sorry.

**Comment by MorrisJobke** [comment]
I verified, that this fixes the display issue that occur on 7.0.5 with LDAP users. Works :+1:

**Comment by MorrisJobke** [comment]
@karlitschek Should this really go into 7.0.7? It became a blue ticket and there aren't any announcement regarding the freeze and release of 7.0.6. I would say this can go into 7.0.6.

@LukasReschke @butonic Reviewers?

**Comment by karlitschek** [comment]
@MorrisJobke agreed. 7.0.6 :-)

**Comment by MorrisJobke** [comment]
How to test:

* simply add an external mount for an LDAP user and check if the user is still listed in the "mount for user" setting (last row in the external storage settings table) after a page refresh

cc @nickvergessen @LukasReschke

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
