### PR TITLE
[stable8.1]Properly nest groups when using memberOf to detect group membership, fixes #17759

### LINKED ISSUE #17759: 8.1 - LDAP: Having memberOf enabled breaks nested groups
### Steps to reproduce
1. Have an LDAP server, with memberOf enabled
2. Have owncloud configured for said LDAP server, with "Nested groups" enabled in the  "advanced settings"
3. Put LDAP user u1 in LDAP group g2
4. Put LDAP group g2 in LDAP group g1

### Expected behaviour
Owncloud should see the user u1 as a member of g1 (as well as g2)

### Actual behaviour
Owncloud only sees the user u1 as a member of g2

### Server configuration
**Operating system**: CentOS 7
**ownCloud version:** 8.1
**Are you using an external user-backend, if yes which one:** LDAP
**LDAP Server** OpenLDAP

### A bit of debugging...

090478a95e1adc904cd8971158c848b9c00374f6 added a speedup to the apps/user_ldap/group_ldap.php' getUserGroups() function, by using the memberOf attribute if possible (instead of checking all groups to see if the user's there, recursively if the nested groups option is enabled in the settings). However, memberOf itself is not recursive, thus nested groups are missed.

The code checks for memberOf support as well as the config option 'useMemberOfToDetectMembership', however, the said option is not exposed anywhere in the user interface...

I'd provide a PR but I'm unsure what would be the best solution between adding an option in the settings and not using memberOf if nested groups are enabled (or some third option I didn't think of)

@blizzz Thoughts, since you wrote that code?

### PR DESCRIPTION
**Pull request by GreenArchon**
Backport of #18042 , approval https://github.com/owncloud/core/pull/18042#issuecomment-128693519

This backport is also under MIT license.

### CODE REVIEW

**Comment by karlitschek** [comment]
@blizzz what do you think?

**Comment by MorrisJobke** [comment]
> @blizzz what do you think?

I guess he also wants the backport ;) https://github.com/owncloud/core/pull/18042#issuecomment-128671716

**Comment by MorrisJobke** [comment]
@owncloud-bot this is okay to test

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
let's hold back this merge until #18042 is in master

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/18042 is still requiring review/attention

**Comment by MorrisJobke** [comment]
cc @blizzz @davivel

**Comment by davivel** [comment]
@MorrisJobke, me, sure? I don't know what is this about :S

**Comment by blizzz** [comment]
looks good, tested, works, :+1: 

@davitol maybe?

**Comment by davitol** [comment]
@davitol maybe? I`ve just tested and I think it is not solved
Nested Groups checbox checked
ad1

nest1
nest2
nest3

**Comment by blizzz** [comment]
@davitol you need to check in the user management whether a member of group1 is also shown when you click on group2. Don't forget to check "Nested groups" in advanced settings. See reproduction steps here https://github.com/owncloud/core/issues/17759

**Comment by MorrisJobke** [comment]
@davivel Sorry I always mixup your username with the one of @davitol  :confused: :P

**Comment by davitol** [comment]
The user does not appear in group 1 or group2, only when clicking in Everyone

nousuvisi

**Comment by blizzz** [comment]
@davitol might it be some caching thing? can you give the owncloud config, just to check? it  worked fine for me here.

**Comment by MellonQ** [comment]
Hi!
In order to operate properly search for nested groups in Active Directory you have not to use expression like "(memberof=CN=ownCloud Users,OU=Groups,DC=example,DC=com)" because it looks only for direct group membership. In AD there is "special-M$" search OID for this purposes (discribed here -  https://msdn.microsoft.com/en-us/library/aa746475%28v=vs.85%29.aspx), so the correct search filter is:
(memberof:1.2.840.113556.1.4.1941:=CN=ownCloud Users,OU=Groups,DC=example,DC=com)

**Comment by MorrisJobke** [comment]
@cmonteroluque I will move this to 8.1.3

**Comment by davitol** [comment]
It worked OK for me switching the BP patch to oc server: version":"8.1.2.1","versionstring":"8.1.2"

**Comment by davitol** [comment]
:+1: Waiting for another reviewer :smile_cat:

**Comment by blizzz** [comment]
@MellonQ that's interesting and probably worth an improvement for the future (>= OC 9.0). However, it would be very MS specific and we cannot guess the directory server in use. Maybe you are interested in following this idea and doing a PR against master? Or open a new issue as feature request with those details, so they do not get lost, at least.

**Comment by blizzz** [comment]
@davitol I reviewed already here https://github.com/owncloud/core/pull/18123#issuecomment-134955524, let's merge

**Comment by davitol** [comment]
@cmonteroluque @DeepDiver1975 @blizzz Maybe it would be necessary a 'forwardport' to 8.2.X ?

**Comment by MorrisJobke** [comment]
> @cmonteroluque @DeepDiver1975 @blizzz Maybe it would be necessary a 'forwardport' to 8.2.X ?

It is already in master: #18042

**Pull request merged**
