### PR TITLE
Fix persistent locking handling in public links

### PR DESCRIPTION
**Pull request by PVince81**
## Description
- Display "unknown user" in UI when locked through public link and owner
info is null
- Properly check parent lock for Webdav calls on the public Webdav
endpoint

## Related Issue
Fixes public link part of https://github.com/owncloud/core/issues/33848

## How Has This Been Tested?
- [x] public webdav write access to locked resource: https://github.com/owncloud/core/issues/33848#issuecomment-455537368
- [x] lock a folder through public webdav then view the lock as regular user: owner field missing, now appears as "unknown user"

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
There's another bug I found here: https://github.com/owncloud/core/issues/34225

**Comment by individual-it** [comment]
@PVince81 I've added acceptance tests for that case, please check if they describe the intended behaviour correctly and if more tests are needed

@phil-davis please review the test code

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
not merged - waiting for @phil-davis to approve the acceptance tests as requested by @individual-it

**Review by phil-davis — APPROVED** [review]
Test code looks good

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/34227

**Pull request merged**
