### PR TITLE
[stable9] Do not use the language name, when it's not the one from the language…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… we want

backport of #24954

### CODE REVIEW

**Comment by PVince81** [comment]
Tested, works :+1: (on stable9 I was able to reproduce the issue)

**Comment by PVince81** [comment]
Second review ? @rullzer @nickvergessen @icewind1991

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
Failing tests unrelated

**Pull request merged**
