### PR TITLE
Execute unit tests with postgre:10.3 as well

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
We shall support postgres 10.3 as well

## Related Issue
#31320 

## How Has This Been Tested?
- PHP_VERSION=7.1 TEST_SUITE=phpunit DB_TYPE=postgres POSTGRES_IMAGE=postgres:10.3 drone exec

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by tboerger — APPROVED** [review]

**Comment by phil-davis** [comment]
@DeepDiver1975 this is another PR where all drone has passed, but the codecov result has not got back to GitHub. It is happening to a few PRs today.

**Comment by phil-davis** [comment]
and hours later the codecov report pops out. what happened there???

**Comment by DeepDiver1975** [comment]
Maybe some hickup in the Processing queue ....

**Comment by phil-davis** [comment]
Backport `stable10` #34789

**Comment by phil-davis** [comment]
This is coming "one day" to `stable10` with "drop PHP 7.0" #35786

**Pull request merged**
