### PR TITLE
Apply new checkbox style in app settings

### PR DESCRIPTION
**Pull request by Henni**
image

image

cc @jancborchardt

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

Also the group feature still works.

**Comment by raghunayyar** [comment]
Works for me to, I just updated the branch (the GitHub Way). I will merge as soon as I see the checks passing.

**Comment by MorrisJobke** [comment]
> Works for me to, I just updated the branch (the GitHub Way). I will merge as soon as I see the checks passing.

-.- This won't work. Please don't do that - @DeepDiver1975 will merge them. It's some broken behavior of Github.

**Comment by jancborchardt** [comment]
Cool, thanks a lot! :)

**Comment by raghunayyar** [comment]
This is so weird.

**Pull request merged**
