### PR TITLE
Add `getNonExistingName()` to the node api

### PR DESCRIPTION
**Pull request by icewind1991**
@LukasReschke as discussed.

cc @PVince81

### CODE REVIEW

**Comment by LukasReschke** [comment]
:heart:

**Comment by LukasReschke** [comment]
:+1:

@karlitschek Would love this for 8.0 for the files_drop app as well to be able to have testable code without much code duplication… :see_no_evil:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by karlitschek** [comment]
backport should be safe. :+1:

**Pull request merged**
