### PR TITLE
Remove a fed share from the local table before trying to notify the remote server

### PR DESCRIPTION
**Pull request by icewind1991**
Otherwise we never remove the share if the notify fails

cc @owncloud/sharing @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Second review please @guruz @SergioBertolinSG @jvillafanez @georgehrke

**Comment by jvillafanez** [comment]
With the patch, what happens if the notification fails? Will ownCloud keep sending notifications, or will the share reappear since the notification fail?

If the notification fails, how the other server will behave if the user wants to access to the file?

**Comment by PVince81** [comment]
@jvillafanez from what I remember what @schiessle told me is that if it fails here, there is a background job that will retry a few times

**Comment by jvillafanez** [comment]
I guess it's too much for this PR, but I think it's better if the background job (or the notification system) handle the deletion because he knows if the file has been deleted in the other server. I'd mark the share as deleted here (and hide it for the users).

The problem I see is that even if we delete the share from the DB, there is no guarantee that the file is deleted in the other server.

**Comment by icewind1991** [comment]
> there is no guarantee that the file is deleted in the other server.

There is no file to delete on the remote server, the worst that can happen is  the share still showing up for the recipient until he tries to access it, at which point the recipient server will notice the share is invalid and remove it

**Comment by jvillafanez** [comment]
> the share still showing up for the recipient until he tries to access it

That's the point I'd like to avoid.

Anyway, my point has a lot of changes to be done within the scope of 9.1 and I don't think we'll have enough time, so let's go with this.

👍

**Pull request merged**
