### PR TITLE
Restructure config.sample.php of stable8.1

### PR DESCRIPTION
**Pull request by ghost**
Those are no default parameters created by the installer as stated in the headline.

Backport of https://github.com/owncloud/core/pull/19288

### CODE REVIEW

**Comment by RealRancor** [comment]
This also solves the issue that "supportedDatabase" parameter is currently found within the "Using Object Store" headline:

https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/config_sample_php_parameters.html#using-object-store-with-owncloud

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
cc @PVince81

**Comment by PVince81** [comment]
:+1:

CC @karlitschek for this doc backport

**Comment by karlitschek** [comment]
hmmm. not a critical backport but also doesn't hurt. :+1:

**Pull request merged**
