### PR TITLE
Disable autocomplete for SMTP Password

### PR DESCRIPTION
**Pull request by LukasReschke**
While really nearly no modern browser cares about it anymore too much it's still not wrong to have it here (and also stops some automated scanners reporting this...)

cc @nickvergessen @th3fallen Please review. :smile:

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by th3fallen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@th3fallen I don't know if you noticed, but:

1. we are in feature freeze
2. Jenkins hasn't finished yet

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Is this still okay to go into master? Otherwise I will revert it.

**Comment by LukasReschke** [comment]
Told him that as well in Skype. No need to revert though it's a minimal fix.

**Comment by LukasReschke** [comment]
(which actually could even solve some problems in case the administrator uses some stone-age browsers such as IE)

**Comment by th3fallen** [comment]
@MorrisJobke @DeepDiver1975 yeah my coffee apparently hasn't kicked in, i was half way to reverting and @LukasReschke Said not to so....

**Comment by DeepDiver1975** [comment]
Please revert - this was scheduled for 8.0.1 - THX

**Pull request merged**
