### PR TITLE
[stable9.0] Proper separation of quota values in APIs

### PR DESCRIPTION
**Pull request by Gomez**
Backport of https://github.com/owncloud/core/pull/27896

Fixes: https://github.com/owncloud/core/issues/27608

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks. If you tested all scenarios I listed in the original ticket, please post them here

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2017-05-19 13-54-25

**Comment by Gomez** [comment]
Same unit errors as here https://github.com/owncloud/core/pull/27895#issuecomment-301739415 cant spot the difference. Any help appreciated.

Tests done:

Set default quota to 5 GB
- [x] TEST: newly created user gets "default" quota, properly applies in personal page, 5 GB
- [x] TEST: set existing user quota to "default", properly applies in personal page, 5 GB
- [x] TEST: set existing user quota to "unlimited", properly applies in personal page (unlimited)
- [x] TEST: set existing user quota to "1 GB", properly applies in personal page, 1 GB

**Comment by PVince81** [comment]
Indeed, the patch is the same like stable9.1...

**Comment by PVince81** [comment]
running all the tests locally do not reproduce this issue... classic.

And running the versions suite alone gives me weird errors:
```
...FF....F......E...                                              20 / 20 (100%)

Time: 1.23 seconds, Memory: 33.50MB

There was 1 error:

1) Test_Files_Versioning::testRestoreNoPermission
Exception: The share API is disabled

/srv/www/htdocs/owncloud/lib/private/share20/manager.php:486
/srv/www/htdocs/owncloud/lib/private/share20/manager.php:504
/srv/www/htdocs/owncloud/apps/files_versions/tests/versions.php:631
```

welcome to weirdland

**Comment by PVince81** [comment]
okay, seems I got it with phpunit 4.4.5:
```

11) Test_Files_Versioning::testRename
Failed asserting that false is true.

/srv/www/htdocs/owncloud/apps/files_versions/tests/versions.php:290

12) Test_Files_Versioning::testRenameInSharedFolder
Failed asserting that false is true.

/srv/www/htdocs/owncloud/apps/files_versions/tests/versions.php:333

13) Test_Files_Versioning::testCopy
Failed asserting that false is true.

/srv/www/htdocs/owncloud/apps/files_versions/tests/versions.php:532
```

why 11) ? well, locally there are some tests that always failed for me (testGetThumbnail: your test is not allowed to access the database), never had time to look into these...

**Comment by PVince81** [comment]
Apparently the quota returned in `OCA\Files_Versions\Storage` is "default" but the code passes this to `computerFileSize` which converts it to 0. I'll try and fix this, seems something is missing here.

**Comment by PVince81** [comment]
ah yes of course, you're missing a lot of the code from the original stable9.1 PR, like https://github.com/owncloud/core/pull/27896/commits/f5734c0454aff51723523c69a2a2ccb99ee78641#diff-efc44835a2c59b3707c965b80a3d669e

**Comment by PVince81** [comment]
I'm going to redo the backport from scratch, just in case

**Comment by PVince81** [comment]
protip: to backport to stable9, create patches with `git format-patch`, then edit the patches, lower case the file names, remove "test" suffixes. Then use `git am -3 patch.patch` to apply.

**Comment by PVince81** [comment]
new PR: https://github.com/owncloud/core/pull/28302

**Comment by Gomez** [comment]
Thanks @PVince81 for redo and the protip !

**Pull request closed without merging**
