### PR TITLE
Fix tooltip for versions mtime

### PR DESCRIPTION
**Pull request by PVince81**
It was missing a call to jquery.tooltip

@owncloud/designers @morrisjobke @rullzer @Blizzz

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by blizzz** [comment]
Looks good, tested, works, :+1:

**Comment by MorrisJobke** [comment]
@PVince81 @karlitschek Backport?

**Comment by karlitschek** [comment]
please backport! thanks :+1:

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/22924

**Pull request merged**
