### PR TITLE
Parse mtime from the data attributes

### LINKED ISSUE #18526: Right sidebar reports modified date wrongly as »a few seconds ago« on every file
@PVince81 as I showed you. Every file and folder shows in the sidebar »a few seconds ago« for the modified date instead of the correct one.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/18526

Please review @nickvergessen @jancborchardt @MorrisJobke @blizzz

### CODE REVIEW

**Comment by jancborchardt** [comment]
Works nicely, thanks! :) :+1:

**Comment by nickvergessen** [comment]
So currently it used no time?

**Comment by PVince81** [comment]
@nickvergessen yes, it seems the utility method used the current time for some reason.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
