### PR TITLE
[8.1] Delay setting up the filesystem for a share owner untill the share is used

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/owncloud/core/pull/18810

### CODE REVIEW

**Comment by karlitschek** [comment]
as discussed :+1:

**Comment by PVince81** [comment]
@MorrisJobke @cmonteroluque

**Comment by MorrisJobke** [comment]
Works for me here :+1:

Let's wait for @nickvergessen to run the unit tests

**Comment by MorrisJobke** [comment]
> Let's wait for @nickvergessen to run the unit tests

I meant smashbox tests.

**Comment by PVince81** [comment]
test_sharePermission also passed on this branch.

A quick test of shares with reshares (subdir reshares) and a few file operations like rename, delete, mkdir seem to work fine.

:+1: 

@karlitschek @DeepDiver1975 @cmonteroluque before merging this a decision needs to be made whether to put this into 8.1.2 (which will need some more extensive regression testing from QA) or defer to 8.1.3.

**Comment by MorrisJobke** [comment]
> @karlitschek @DeepDiver1975 @cmonteroluque before merging this a decision needs to be made whether to put this into 8.1.2 (which will need some more extensive regression testing from QA) or defer to 8.1.3.

They reason for asking this is a huge load impact - as currently seen on s3

**Comment by nickvergessen** [comment]
Matrix | No Locking
------ | ----------
test_reshareDir | :white_check_mark: 
test_shareDir | :white_check_mark: 
test_shareFile | :white_check_mark: 
test_shareGroup | :white_check_mark: 
test_sharePermissions | :white_check_mark: 
test_uploadFiles | :clock2:
test_basicSync

**Comment by karlitschek** [comment]
I think this is the call of @cmonteroluque 
Unfortunately he is offline today and tomorrow. So let's wait.

**Comment by karlitschek** [comment]
@msrex

**Comment by nickvergessen** [comment]
@MorrisJobke all tests passed

**Pull request merged**
