### PR TITLE
url encode search query, fix unwanted search on scroll

### PR DESCRIPTION
**Pull request by butonic**
allows sending special chars like ? and *, also prevents sending the old query when adding a single char

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@LukasReschke THX

**Comment by MorrisJobke** [comment]
> allows sending special chars like ? and *, also prevents sending the old query when adding a single char

This actually breaks it. In master it is working. In this branch it doesn't work anymore.

* add a folder abc
* add a file `?welcome.txt` to abc
* search for `?wel` in there root.

**Comment by butonic** [comment]
well then we need to also url decode the query string in php again.

**Comment by PVince81** [comment]
CC @georgehrke

**Comment by PVince81** [comment]
Closing due to lack of activity.
As I see this is a trivial fix so if it's important feel free to reopen and complete the work.

**Pull request closed without merging**
