### PR TITLE
Allow to delete the email address in user management

### PR DESCRIPTION
**Pull request by MorrisJobke**
@PVince81 @nickvergessen @LukasReschke @butonic Please review

steps:
- delete the email address of a user by set it to `''`(empty string)
- before: it was reset to the previous email address
- after: the email address is deleted

@karlitschek I would like to backport this at least to stable8.2

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by MorrisJobke** [comment]
Easy to review by ignoring whitespace: https://github.com/owncloud/core/pull/22146/files?w=1

**Comment by nickvergessen** [comment]
:+1:

**Comment by butonic** [comment]
:+1:

**Comment by blizzz** [comment]
post-merge :+1:

**Pull request merged**
