### PR TITLE
Backport 15362 purge app cache cli enable

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #15362

### CODE REVIEW

**Comment by nickvergessen** [comment]
cc @jvillafanez @LukasReschke @MorrisJobke @jnfrmarks

**Comment by nickvergessen** [comment]
@DeepDiver1975 @karlitschek please approve backport

**Comment by karlitschek** [comment]
please backport after 8.0.3 is out :+1:

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
I think it broke, will create a new PR later

**Comment by nickvergessen** [comment]
Replaced by #16027

**Pull request closed without merging**
