### PR TITLE
also call generateTarget for group shares

### PR DESCRIPTION
**Pull request by schiessle**
oc8 backport of https://github.com/owncloud/core/pull/15247

cc @MorrisJobke @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Verified that it is broken in stable8 and works with this :+1:

**Comment by karlitschek** [comment]
cool :+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Pull request merged**
