### PR TITLE
[stable8.1] Properly trigger testRemote after getting a 404 from remote fed share

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/22498 to stable8.1

Please review @nickvergessen @MorrisJobke @rullzer @schiesbn @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
Please hold the review, there seems to be an additional issue...

**Comment by PVince81** [comment]
It does work on stable8.1. There is another issue introduced in stable8.2...

**Comment by icewind1991** [comment]
:+1:

**Comment by PVince81** [comment]
Needs a second reviewer @MorrisJobke @nickvergessen @rullzer @schiesbn

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
