### PR TITLE
Revert "Show cached previews directly"

### PR DESCRIPTION
**Pull request by icewind1991**
This reverts commit 1b708e26efbcb4052becad3d7b6618064c2605a6.

cc @PVince81 @jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
Do we have to revert here? Isn’t there a solution which has the caching, but doesn’t break the layout?

Also cc @oparoz who reviewed the original PR.

**Comment by oparoz** [comment]
@jancborchardt - It depends... Fixing the side-bar shouldn't be a problem, but what about other apps which ask for a preview? I'd say that they should resize what they get to make it fit, but every single ajax call needs to be checked.

**Comment by PVince81** [comment]
:+1: for revert and resubmit a PR with a better fix, if needed.

**Comment by jancborchardt** [comment]
Ok, :+1: then.

**Pull request merged**
