### PR TITLE
[stable10] UI tests for reset password

### PR DESCRIPTION
**Pull request by paurakhsharma**
backport of #31168 
depends on #31144 CI will pass after the fix is merged

### CODE REVIEW

**Comment by phil-davis** [comment]
Planned to merge after 10.0.8 - for 10.0.9...

**Review by phil-davis — APPROVED** [review]
For merge after #31144

**Comment by phil-davis** [comment]
See #31225 for a later rebase of this.

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
I could do a rebase here within GitHub - good stuff. Code looks good, let's see what CI says.

**Comment by phil-davis** [comment]
No good - ``webUIManageUsersGroups needs work. Doing that in #31225

**Comment by phil-davis** [comment]
Done in #31225

**Pull request closed without merging**
