### PR TITLE
Path needs adjustments so that the code can be viewed online

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Code should be viewable on codecov online ....

## Motivation and Context
Try to fix this ...
bildschirmfoto von 2018-01-11 13-04-05

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
still does not work -> chatting with codecov support

**Comment by butonic** [comment]
@DeepDiver1975 I think it works: https://codecov.io/gh/owncloud/core/src/bd4df59c721324b82bb9449b0f68cdbfda1de206/index.php

**Review by butonic — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
superseeded by #30206

**Comment by butonic** [comment]
well, it is. take a look at https://github.com/codecov/support/wiki/Codecov-Yaml#full-yaml

but if the other pr works ... whatever ...

**Comment by DeepDiver1975** [comment]
> well, it is. take a look at https://github.com/codecov/support/wiki/Codecov-Yaml#full-yaml. take a look at the codecov build log. it spews an error about wrong yeml in the other PRs. this PR now works

funny - codecov guys told me something completely different ...

**Comment by DeepDiver1975** [comment]
We will fix the coverage reporting -> close

**Pull request closed without merging**
