### PR TITLE
[tests-only] [full-ci] PHP Ubuntu22.04

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
WIP - related to PR #40006 which tests with Ubuntu 20.04

This tests with Ubuntu 22.04

## Related Issue
#38348 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliEncryption-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/35991/112

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/35992/112/14
```
runsh: Total unexpected failed scenarios throughout the test run:
cliEncryption/encryption.feature:27
cliEncryption/encryption.feature:39
cliEncryption/encryption.feature:45
cliEncryption/encryption.feature:51
```
Issue #40071

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/35992/20/8
```
+ phpdbg -d memory_limit=6G -rr ../lib/composer/bin/phpunit --configuration phpunit-autotest-external.xml --coverage-clover output/coverage/autotest-external-clover-sqlite-samba.xml ../apps/files_external/tests/Storage/SmbTest.php
[Welcome to phpdbg, the interactive PHP debugger, v7.4.29]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
PHPUnit 9.5.20 #StandWithUkraine

Runtime:       PHPDBG 7.4.29
Configuration: phpunit-autotest-external.xml

...................................FFFFFFFF...................F.F 65 / 85 ( 76%)

F...................                                              85 / 85 (100%)

Time: 00:02.928, Memory: 60.70 MB

There were 11 failures:

1) OCA\Files_External\Tests\Storage\SmbTest::testMoveOverwrite with data set #0 ('/source.txt', '/target.txt')
/source.txt still exists
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:259
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

2) OCA\Files_External\Tests\Storage\SmbTest::testMoveOverwrite with data set #1 ('/source.txt', '/target with space.txt')
/source.txt still exists
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:259
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

3) OCA\Files_External\Tests\Storage\SmbTest::testMoveOverwrite with data set #2 ('/source with space.txt', '/target.txt')
/source with space.txt still exists
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:259
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

4) OCA\Files_External\Tests\Storage\SmbTest::testMoveOverwrite with data set #3 ('/source with space.txt', '/target with space.txt')
/source with space.txt still exists
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:259
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

5) OCA\Files_External\Tests\Storage\SmbTest::testMoveOverwrite with data set #4 ('/source.txt', '/tärgét.txt')
/source.txt still exists
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:259
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

6) OCA\Files_External\Tests\Storage\SmbTest::testMoveOverwrite with data set #5 ('/sòurcē.txt', '/target.txt')
/sòurcē.txt still exists
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:259
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

7) OCA\Files_External\Tests\Storage\SmbTest::testMoveOverwrite with data set #6 ('/sòurcē.txt', '/tärgét.txt')
/sòurcē.txt still exists
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:259
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

8) OCA\Files_External\Tests\Storage\SmbTest::testMoveOverwrite with data set #7 ('/single ' quote.txt', '/tar'get.txt')
/single ' quote.txt still exists
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:259
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

9) OCA\Files_External\Tests\Storage\SmbTest::testRenameOverWriteFile
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'bar'
+'foo'

/drone/src/tests/lib/Files/Storage/Storage.php:476
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

10) OCA\Files_External\Tests\Storage\SmbTest::testRenameOverWriteDirectory
rename must return true on success
Failed asserting that false is true.

/drone/src/tests/lib/Files/Storage/Storage.php:513
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

11) OCA\Files_External\Tests\Storage\SmbTest::testRenameOverWriteDirectoryOverFile
rename must return true on success
Failed asserting that false is true.

/drone/src/tests/lib/Files/Storage/Storage.php:527
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

FAILURES!
Tests: 85, Assertions: 369, Failures: 11.
```

These 11 failures happen with the pipelines that run with samba, windows and owncloud external storage.

Needs looking at to see what is the cause - are there some test settings to modify, or some PHP extension to update, or some real code to fix up, or...?

**Comment by phil-davis** [comment]
See #40745

**Pull request closed without merging**
