### PR TITLE
[3rdparty] Bump sabre to 3.0.7 (PHP7 support)

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/240

@DeepDiver1975 as requested.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
fix for failing travis test is here https://github.com/owncloud/core/pull/21684

**Comment by DeepDiver1975** [comment]
@PVince81 @nickvergessen mind smashing this one? THX

**Comment by DeepDiver1975** [comment]
@rullzer 3rdparty merged - please update - THX

**Comment by rullzer** [comment]
@DeepDiver1975 done

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 done

THX

**Comment by nickvergessen** [comment]
anyone has php7 and wants to run smashbox against it?

**Comment by DeepDiver1975** [comment]
all green :+1: from my side

**Comment by DeepDiver1975** [comment]
still smashing with php7 would be nive

**Comment by rullzer** [comment]
I can smash with php7 later this evening

**Comment by PVince81** [comment]
@rullzer any results ?

**Comment by rullzer** [comment]
@PVince81 well my smashbox with php7 fails... but it also does that on master. Basically file syncing back not always works... if I modify the tests to not have 2 syncs in the same step all works out... so it seems we have a race condition somewhere...

**Comment by DeepDiver1975** [comment]
Okay - looks like we need to setup our smashbox ci system with php7

**Comment by DeepDiver1975** [comment]
> Okay - looks like we need to setup our smashbox ci system with php7

https://github.com/owncloud/docker-servers/issues/35

**Comment by DeepDiver1975** [comment]
let's merge this

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
