### PR TITLE
[8.1] Activity oracle sql error for favorites

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport #20487

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
on 8.1 we have no ocs api tests and no swift primary storage tests and no php7 support -> ignore them

**Comment by MorrisJobke** [comment]
Tested and works here :+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Please review :)

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
