### PR TITLE
Backport of LDAP second display name

### PR DESCRIPTION
**Pull request by PVince81**
From c1871f5787cd48eb1e116f7f62bc4d4a50a0a04b

### CODE REVIEW

**Comment by PVince81** [comment]
Please review @blizzz @MorrisJobke @scolebrook 

I did a quick test locally using the "uidNumber" as second attribute and it worked fine!

**Comment by karlitschek** [comment]
backport is ok :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@blizzz Could you have a look at the failing unit tests:

```

1) OCA\user_ldap\tests\Test_User_User::testComposeAndStoreDisplayName with data set #0 ('Roland Deschain', '', 'Roland Deschain')
Undefined offset: 7

/ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/user_ldap/tests/user/user.php:895

2) OCA\user_ldap\tests\Test_User_User::testComposeAndStoreDisplayName with data set #1 ('Roland Deschain', null, 'Roland Deschain')
Undefined offset: 7

/ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/user_ldap/tests/user/user.php:895

3) OCA\user_ldap\tests\Test_User_User::testComposeAndStoreDisplayName with data set #2 ('Roland Deschain', 'gunslinger@darktower.com', 'Roland Deschain (gunslinger@d...r.com)')
Undefined offset: 7

/ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/user_ldap/tests/user/user.php:895
```

**Comment by blizzz** [comment]
> @blizzz Could you have a look at the failing unit tests:

this second, literally

**Comment by blizzz** [comment]
now we shall pass

Also, works :+1:

**Pull request merged**
