### PR TITLE
[Stable8.1] Use a CappedCache in the user database backend

### PR DESCRIPTION
**Pull request by rullzer**
Backport of https://github.com/owncloud/core/pull/24405
Approved in: https://github.com/owncloud/core/pull/24405#issuecomment-216497180

CC: @MorrisJobke @nickvergessen @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Can't login after this branch is checked out.

Got following in the logs:

```

{"reqId":"jVNp3ParsSdWygSSzbFR","remoteAddr":"::1","app":"PHP","message":"Indirect modification of overloaded element of OC\\Cache\\CappedMemoryCache has no effect at \/Users\/morrisjobke\/Projects\/owncloud\/master\/lib\/private\/user\/database.php#230","level":3,"time":"2016-05-18T16:32:27+00:00"}
```

**Comment by PVince81** [comment]
Cherry-picked 23fa0e982b7b383a85c160017d0c7c4d6e58c126 to this branch to make it work again.

Tested locally with Webdav, works :+1:

**Comment by rullzer** [comment]
Ah yes same fix. Thanks @PVince81

**Pull request merged**
