### PR TITLE
Fix "AutoloadNotAllowedException" when files_sharing is disabled

### LINKED ISSUE #491: Activities not loading (Autoload path not allowed)
**OS** CentOS 7 64 bit
**DB** mysql  Ver 14.14 Distrib 5.6.29
**Webserver** nginx 1.6.3
**PHP**  5.6.19
**Ownloud** 9.0.0
**Plugin** Activity  2.2.1
After a Manual upgrade from OC 8.2.2 to 9.0.0 the Activity pane on all Folders no longer loads. The log error:
{"reqId":"xxx","remoteAddr":"xxx","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Mess                                                                                age\":\"Autoload path not allowed: \\\/var\\\/www\\\/xxx\\\/cloud\\\/apps\\\/files_sharing\\\/lib\\\/activity.php\

- I have tried to disable re-enable the app
- Clear the jobs table with DELETE from oc_jobs WHERE `class` LIKE '%CommandJob%' AND `argument` LIKE 'O:33%Files_Versions%'

When I try to view the apps/activity I get the same error, and no results on the page.

Only current solution is to disable the the Activities. 
--more info on request.--

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. Disable the files_sharing
2. Enable activity
3. Open activity page

Fix owncloud/activity#491

@rullzer @PVince81 @MorrisJobke 

@karlitschek should backport this easy fix

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek We should backport this to stable8.2 for https://github.com/owncloud/enterprise/issues/1284 - is this okay?

cc @gig13

**Comment by karlitschek** [comment]
yes. please backport 👍

**Comment by nickvergessen** [comment]
@MorrisJobke so you managed to reproduce this? I was unable to do so for 8.2, so I can not confirm that this fixes the issue

**Comment by MorrisJobke** [comment]
> @MorrisJobke so you managed to reproduce this? I was unable to do so for 8.2, so I can not confirm that this fixes the issue

No. I just have seen the report from @gig13

**Pull request merged**
