### PR TITLE
[stable10] Allow non hardcoded icons for apps

### PR DESCRIPTION
**Pull request by sharidas**
This change helps users to provide their own
custom icons for the apps which work with
ownCloud.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change helps contributors to use non-hardcoded icons. That is every app developer or contributor can now have their own separate icons which can be used with core.

## Related Issue

https://github.com/owncloud/core/issues/28751

## Motivation and Context

At present the icons are hard coded and are located at core. This prohibits the usage of custom icons for apps. With this change, contributors of apps, can have their own custom app which can be used along with core. No more saving of svg files in the core.

## How Has This Been Tested?

The procedure remains same as mentioned at https://github.com/owncloud/core/pull/29013

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@sharidas please raise documentation ticket to explain how to use this.

I expect that there is already a ticket for the settings panel stuff, maybe add this info there.

**Comment by sharidas** [comment]
I found this ticket: https://github.com/owncloud/documentation/issues/2922 . Can I reopen the ticket?

**Comment by PVince81** [comment]
@sharidas since the ticket was merged already, please raise a new one

**Comment by sharidas** [comment]
Created the document ticket: https://github.com/owncloud/documentation/issues/3483

**Pull request merged**
