### PR TITLE
[WIP] Only show SSL table header if there are certificates

### PR DESCRIPTION
**Pull request by rullzer**
@jancborchardt  As requested in #15263

We currently do now have javascript unit tests for the personal page. I'll make a start with that by adding unit tests for this commit later this week. (cc @PVince81)

### CODE REVIEW

**Comment by karlitschek** [comment]
very nice :+1:

**Comment by rullzer** [comment]
So the code there is not really unit testable. We probably need to fix that first before the unit tests can be added here.

**Comment by jancborchardt** [comment]
Good stuff, thank you! :+1:

**Comment by MorrisJobke** [comment]
@jancborchardt NEVER merge a PR that is tagged with Developing OR [WIP] OR the next major release.

**Comment by MorrisJobke** [comment]
Reverted via #15432

**Comment by MorrisJobke** [comment]
@rullzer Can I ask you to open a new PR? Thanks

**Comment by jancborchardt** [comment]
@rullzer sorry for the mess – only remembered the PR from last week and was focused on reviewing it. :(

**Pull request merged**
