### PR TITLE
New dav endpoint register tags plugin

### PR DESCRIPTION
**Pull request by PVince81**
## Description

This makes it possible to retrieve and PROPPATCH the favorite info
## Related Issue

None raised, discovered while testing https://github.com/owncloud/core/pull/25494
## Motivation and Context

Make new dav behave like old dav
## How Has This Been Tested?

Check out this PR https://github.com/owncloud/core/pull/25494 which makes the web UI use the new DAV endpoint.
Favorite a file then refresh the page.
Before: no favorite info.
After: favorited file still appears as favorite.
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Please review @DeepDiver1975 @guruz @SergioBertolinSG

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
The properties are the same as in old webdav endpoint? ("{http://owncloud.org/ns}favorite" with value "1")

**Comment by PVince81** [comment]
@SergioBertolinSG yes, same properties. It's the same plugin with the same behavior.

**Comment by PVince81** [comment]
Very strange... when debugging I can see that the integration test's call is passing the "favorite" property, it also detects it in the plugin's "handleUpdateProperties" but for some strange reason it doesn't go into the handler function.

However if I set the property with cadaver on the new endpoint, it goes there.
Not sure what the difference is, needs more debugging.

**Comment by PVince81** [comment]
From the integration test:
```
// by property_get
$path                            = (string[6]) 'FOLDER';


// by property_get
$propPatch                       = (object|Sabre\DAV\PropPatch[4]);
  $propPatch->mutations          = (array[1]);
    $propPatch->mutations['{http://owncloud.org/ns}favorite'] = (string[1]) '1';
  $propPatch->result             = (array[0]);
  $propPatch->propertyUpdateCallbacks = (array[0]);
  $propPatch->failed             = (bool) '0';
```

from cadaver:
```
// by property_get
$path                            = (string[6]) 'FOLDER';


// by property_get
$propPatch                       = (object|Sabre\DAV\PropPatch[4]);
  $propPatch->mutations          = (array[1]);
    $propPatch->mutations['{http://owncloud.org/ns}favorite'] = (string[1]) '1';
  $propPatch->result             = (array[0]);
  $propPatch->propertyUpdateCallbacks = (array[0]);
  $propPatch->failed             = (bool) '0';
```

No difference ?!

**Comment by PVince81** [comment]
There's an ignored exception:
```
  $e->xdebug_message             = (string[5961]) '<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Sabre\DAV\Exception\NotFound: File not found: FOLDER in 'root' in /srv/www/htdocs/owncloud/lib/composer/sabre/dav/lib/DAV/SimpleCollection.php on line <i>91</i></th></tr>
```

Maybe the test is using the wrong DAV path when setting the property ?

**Comment by PVince81** [comment]
Indeed, dav URL is wrong in the test in `changeFavStateOfAnElement`:
```
$url                             = (string[21]) 'remote.php/dav/FOLDER';
```

This is probably due to the bizarre magic when the path is "remote.php/dav" it gets changed to another one, but doesn't do it for all functions. I suggest to get rid of this and use the expression "when using the old dav path" and "when using the new dav path".

**Comment by PVince81** [comment]
@SergioBertolinSG can you fix the test ?

**Comment by SergioBertolinSG** [comment]
@PVince81 sure.

**Comment by SergioBertolinSG** [comment]
There is something wrong here, but I am not seeing why

https://github.com/owncloud/core/blob/newdav-tagsplugin/build/integration/features/bootstrap/WebDav.php#L341

**Comment by PVince81** [comment]
Looks like `$this->davPath` is **always* "remote.php/dav" when selecting the new endpoint.
So maybe instead of using it we should use this method instead: https://github.com/owncloud/core/blob/newdav-tagsplugin/build/integration/features/bootstrap/WebDav.php#L27 to get the correct files path.

**Comment by SergioBertolinSG** [comment]
At that point the url is: remote.php/dav/files/admin/FOLDER

But the propfind is raising an exception HTTP error: 404 (Sabre\DAV\Exception)

**Comment by PVince81** [comment]
Yes, it's using the wrong user...

Because `$this->currentUser` is "admin" but the user for who to retrieve the properties is "user0".

I think this needs a good refactoring, it's quite messed up.

**Comment by SergioBertolinSG** [comment]
Ok user is wrong, I'll fix that.

**Comment by SergioBertolinSG** [comment]
> I think this needs a good refactoring, it's quite messed up.

We can improve it in a separate PR, it affects many test cases.

**Comment by PVince81** [comment]
:+1: for the tests part

**Pull request merged**
