### PR TITLE
[stable7] fix theme in IE8 and IE9

### LINKED ISSUE #16409: Web Interface does not display correctly in IE9
**Expected Behavior**
The web interface should display correctly in IE9.

**Actual Behavior**
The log in screen does not display correctly when using IE9 (compatibility mode ON or OFF) and prevents the user from logging in.The password field is not accessible, and the login button is off center

*Steps to reproduce**
Use IE9 with compatibility mode ON or OFF and try to login using the login screen

**Server configuration**
CentOS 6
Database MySQL
OC 7.0.5
Browser: IE9

Note: When testing with IE8, the login screen works when compatibility mode is turned OFF. When compability mode is turned ON, the similar behavior is observed.

screenshot using IE9
201514_display_issue_login_page

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes #16409

cc @jancborchardt @karlitschek 

Tested with IE8 and IE9

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Before:
bildschirmfoto von 2015-05-18 15-55-37

After:
bildschirmfoto von 2015-05-18 15-58-53

**Comment by jancborchardt** [comment]
:+1: would be good if reporter @gig13 can also test the fix. :)

**Comment by MorrisJobke** [comment]
cc @davitol

**Comment by davitol** [comment]
@MorrisJobke did it work to you the setup page in IE9?
captura de pantalla 2015-05-28 a las 10 23 25
Did the orange setup button appeared to you?

**Comment by MorrisJobke** [comment]
This breaks the scrollbar for IE8 and IE9 ... needs another fix. see #15413

**Pull request closed without merging**
