### PR TITLE
Rename user_webdavauth to prevent accidental activation - refs #17112

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@karlitschek @LukasReschke @RealRancor please review - THX

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

cc @carlaschroder Needs documentation update.

**Comment by karlitschek** [comment]
great. :+1:

**Comment by DeepDiver1975** [comment]
Should we backport this? Not sure - on the one hand on older installations people already know what this is about - on the other hand: you never know ....

I'm honestly undecided ...

**Comment by karlitschek** [comment]
I think we can't. This would confuse people too much.

**Comment by carlaschroder** [comment]
@LukasReschke Me and my little friend grep will take care of it.

**Comment by LukasReschke** [comment]
Grep is your friend too? :cry:

**Comment by carlaschroder** [comment]
Grep is everyone's friend! Even yours! :dancers:

**Comment by LukasReschke** [comment]
Yay! A real friend! :beers:

**Pull request merged**
