### PR TITLE
Silently fail app upgrade exceptions

### LINKED ISSUE #16240: WebDAV quota value returned in exponential format
See https://github.com/owncloud/android/issues/940

### LINKED ISSUE #17323: Third party app code update during OC upgrade fails OC upgrade
Normally the upgrade process should disable third party apps.
I suspect that the package might be using the option to prevent disabling third party apps.
@jnweiger can you confirm ?

Before the update I had the calendar app version 0.6.4 installed and contacts 0.3.0.18 installed from git (because the app store versions weren't ready back then)

I did a `zypper update`, updating from 8.1.0~RC1

```
( 1/23) Installing: owncloud-server-8.1.0~RC2-2.1 .............................................................................................................[done]
Additional rpm output:
owncloud-server: Upgrade starting
owncloud-server: occ maintenance:mode --on
Maintenance mode enabled
owncloud-server Upgrade complete
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Maintenance mode disabled
owncloud-server: occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Update 3rd-party app: calendar
Exception: App can't be installed because it is not compatible with this version of ownCloud
Update failed
Maintenance mode is kept active
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Maintenance mode disabled


( 2/23) Installing: owncloud-app-files_trashbin-8.1.0~RC2-2.1 .................................................................................................[done]
( 3/23) Installing: owncloud-app-gallery-8.1.0~RC2-2.1 ........................................................................................................[done]
( 4/23) Installing: owncloud-app-firstrunwizard-8.1.0~RC2-2.1 .................................................................................................[done]
( 5/23) Installing: owncloud-app-files_sharing-8.1.0~RC2-2.1 ..................................................................................................[done]
( 6/23) Installing: owncloud-app-files_pdfviewer-8.1.0~RC2-2.1 ................................................................................................[done]
( 7/23) Installing: owncloud-app-encryption-8.1.0~RC2-2.1 .....................................................................................................[done]
( 8/23) Installing: owncloud-app-files_texteditor-8.1.0~RC2-2.1 ...............................................................................................[done]
( 9/23) Installing: owncloud-app-user_ldap-8.1.0~RC2-2.1 ......................................................................................................[done]
(10/23) Installing: owncloud-app-files-8.1.0~RC2-2.1 ..........................................................................................................[done]
(11/23) Installing: owncloud-app-templateeditor-8.1.0~RC2-2.1 .................................................................................................[done]
(12/23) Installing: owncloud-app-activity-8.1.0~RC2-2.1 .......................................................................................................[done]
(13/23) Installing: owncloud-app-external-8.1.0~RC2-2.1 .......................................................................................................[done]
(14/23) Installing: owncloud-app-user_external-8.1.0~RC2-2.1 ..................................................................................................[done]
(15/23) Installing: owncloud-app-files_versions-8.1.0~RC2-2.1 .................................................................................................[done]
(16/23) Installing: owncloud-app-files_external-8.1.0~RC2-2.1 .................................................................................................[done]
(17/23) Installing: owncloud-app-provisioning_api-8.1.0~RC2-2.1 ...............................................................................................[done]
(18/23) Installing: owncloud-app-files_videoviewer-8.1.0~RC2-2.1 ..............................................................................................[done]
(19/23) Installing: owncloud-3rdparty-8.1.0~RC2-2.1 ...........................................................................................................[done]
(20/23) Installing: owncloud-app-user_webdavauth-8.1.0~RC2-2.1 ................................................................................................[done]
(21/23) Installing: owncloud-app-files_locking-8.1.0~RC2-2.1 ..................................................................................................[done]
(22/23) Installing: owncloud-config-apache-8.1.0~RC2-2.1 ......................................................................................................[done]
Additional rpm output:
owncloud update: Checking for running Apache
owncloud-config-apache: Upgrade complete
owncloud-config-apache: Reloading


(23/23) Installing: owncloud-8.1.0~RC2-2.1 ....................................................................................................................[done]
```

When opening my server I was presented with the usual update screen.
When I clicked "Update now", the update worked.

This ticket is about discussing whether packages should auto-disable third party apps or not. (currently it doesn't).

In theory the script could even first run the update and if an app update failed, then re-run it with app disabling. (I wonder if we could do that on the PHP side instead)

Please confirm whether this is expected behavior. I can understand that on environment that work with packages admins do not want to have to re-enable apps automatically.

@jnweiger @DeepDiver1975 @karlitschek

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #17323

@PVince81 @MorrisJobke @icewind1991 @schiesbn THX

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
```
PHP Fatal error:  Call to a member function logException() on null in /home/mjob/Projekte/owncloud/master/lib/private/updater.php on line 209
PHP Stack trace:
PHP   1. {main}() /home/mjob/Projekte/owncloud/master/occ:0
PHP   2. require_once() /home/mjob/Projekte/owncloud/master/occ:11
PHP   3. OC\Console\Application->run() /home/mjob/Projekte/owncloud/master/console.php:69
PHP   4. Symfony\Component\Console\Application->run() /home/mjob/Projekte/owncloud/master/lib/private/console/application.php:97
PHP   5. Symfony\Component\Console\Application->doRun() /home/mjob/Projekte/owncloud/master/3rdparty/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRunCommand() /home/mjob/Projekte/owncloud/master/3rdparty/symfony/console/Symfony/Component/Console/Application.php:195
PHP   7. Symfony\Component\Console\Command\Command->run() /home/mjob/Projekte/owncloud/master/3rdparty/symfony/console/Symfony/Component/Console/Application.php:874
PHP   8. OC\Core\Command\Upgrade->execute() /home/mjob/Projekte/owncloud/master/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP   9. OC\Updater->upgrade() /home/mjob/Projekte/owncloud/master/core/command/upgrade.php:203
```

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Guys! Wait :-1:

**Comment by DeepDiver1975** [comment]
> PHP Fatal error: Call to a member function logException() on null in /home/mjob/Projekte/owncloud/master/lib/private/updater.php on line 209

WHOT?

I have a look!

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/blob/silently-fail-app-upgrade-exceptions-master/lib/private/templatelayout.php#L81-L82

https://github.com/owncloud/core/blob/silently-fail-app-upgrade-exceptions-master/core/command/upgrade.php#L128-L129

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by MorrisJobke** [comment]
> fixes #16240

Really? "WebDAV quota value returned in exponential format" This fixes that issue? Can you explain what this fixes?

**Comment by MorrisJobke** [comment]
Do we really want this? There is no feedback to the user that something has gone wrong. It simply passes.

**Comment by MorrisJobke** [comment]
And then the app is maybe installed, but the update.php wasn't called, or the app isn't updated at all and the update screen will show up again and again and always doesn't show anything useful. Or is this just because the app is already disabled and it is tried to enable it again?

**Comment by DeepDiver1975** [comment]
> And then the app is maybe installed, but the update.php wasn't called, or the app isn't updated at all and the update screen will show up again and again and always doesn't show anything useful. Or is this just because the app is already disabled and it is tried to enable it again?

https://github.com/owncloud/core/issues/17323#issuecomment-143744013

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
