### PR TITLE
Apply new checkbox style in users settings

### PR DESCRIPTION
**Pull request by Henni**
cc @jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
Please review @owncloud/designers :)

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by Henni** [comment]
Rebased on top of master. Should be up to date now.

**Comment by MorrisJobke** [comment]
> Rebased on top of master. Should be up to date now.

You don't need to. @DeepDiver1975 will merge if this is ready for merge ;)

**Pull request merged**
