### PR TITLE
[stable8.2] Escape special characters (#25429)

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of (#25429)

### CODE REVIEW

**Comment by PVince81** [comment]
Backported too far ?
```
PHP Fatal error:  Call to undefined method OC\DB\Connection::escapeLikeParameter() in /var/lib/jenkins/workspace/owncloud-core_core_PR-26410-RSBZVPREXG4ACRWHSZYC3V354NUOFDJQM6MUCKK4F3CXR4R4MCHQ/lib/private/connector/sabre/custompropertiesbackend.php on line 330
```

**Comment by DeepDiver1975** [comment]
escapeLikeParameter is only available since 9.0 - backport or close? @PVince81 @butonic

**Comment by PVince81** [comment]
Considering that this could have security implications, I'd say let's backport that method if possible

**Comment by DeepDiver1975** [comment]
> Considering that this could have security implications, I'd say let's backport that method if possible

will take care

**Comment by PVince81** [comment]
LDAP still works :+1:

**Comment by PVince81** [comment]
@DeepDiver1975 are you done or is there more to come ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 are you done or is there more to come ?

ask jenkins :see_no_evil:

**Pull request merged**
