### PR TITLE
[config sample] Update info about appstore

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @cdamken @LukasReschke @karlitschek 

Needs to be backported down to stable8.

### CODE REVIEW

**Comment by LukasReschke** [comment]
Guess this makes sense :+1:

**Comment by LukasReschke** [comment]
Guess this makes sense :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek Can you confirm the backport and that the appstore is enabled starting with EE 8.0?

**Comment by karlitschek** [comment]
Confirmed. Please backport :+1:

**Comment by MorrisJobke** [comment]
Stable8: #17608
stable8.1: #17607

**Pull request merged**
