### PR TITLE
Message clean-up

### PR DESCRIPTION
**Pull request by cmeh**
**Changes:**
- _"… is not yet properly setup"_ in line 24 is changed to _" … is not yet set up properly"_ (better word order and space in the middle of "set up", as it is a participle of the verb "to set up").
- _"internet"_ is corrected to _"Internet"_ with a capitalized "I" in lines 54 and 59.
- Also in line 54: _"3rd party apps"_ is changed to _"third-party apps"_ for achieving a more coherent spelling across the different ownCloud components.
- _"… apps don´t work"_ is corrected to _"… apps won't work"_ (with a proper (and hopefully correctly escaped) [apostrophe](http://en.wikipedia.org/wiki/Apostrophe#Typographic_form) instead of the [acute accent](http://en.wikipedia.org/wiki/Acute_accent) currently used).
- Still in line 54: The negation is corrected from _"… might also not work"_ to _"… might not work, either"_.

### CODE REVIEW

**Comment by cmeh** [comment]
This contribution is MIT licensed.

**Comment by DeepDiver1975** [comment]
> "… apps don´t work" is corrected to "… apps won't work" (with a proper (and hopefully correctly escaped) apostrophe instead of the acute accent currently used).

I'd move away from any kind of shortening form.

... will no ..
... cannot ...

**Comment by DeepDiver1975** [comment]
THX @cmeh

**Comment by DeepDiver1975** [comment]
@owncloud-bot this is okay to test

**Comment by cmeh** [comment]
Added a missing "n" in line 63 of user_ldap's /templates/settings.php ("a internal username" -> "an internal username").

**Comment by DeepDiver1975** [comment]
@owncloud-bot this is okay to test

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
