### PR TITLE
Add option to `occ files_external:list` to show all configured mounts

### PR DESCRIPTION
**Pull request by icewind1991**
`occ files:external:list -a` and `occ files:external:export -a`

cc @owncloud/filesystem

### CODE REVIEW

**Comment by guruz** [comment]
Please change ```->setDescription('List configured mounts')``` or whatever to explain what it shows _without_ the -a parameter. System? User?

**Comment by PVince81** [comment]
New functionality ? => 9.2

**Comment by PVince81** [comment]
Tested, works.

However it would be good to add an additional column in the output "mount scope" to differentiate them.

In my case:
```
+----------+-------------+---------+-----------------------+------------------------------------------------------------------------------------------------+------------------------------------------------------+------------------+-------------------+
| Mount ID | Mount Point | Storage | Authentication Type   | Configuration                                                                                  | Options                                              | Applicable Users | Applicable Groups |
+----------+-------------+---------+-----------------------+------------------------------------------------------------------------------------------------+------------------------------------------------------+------------------+-------------------+
| 1        | /sftp       | SFTP    | Username and password | host: "localhost", root: "\/home\/vincent\/temp\/sftpmount", user: "vincent", password: "***"  | enable_sharing: false, encoding_compatibility: false | All              |                   |
| 2        | /sftp2      | SFTP    | Username and password | host: "localhost", root: "\/home\/vincent\/temp\/sftpmount2", user: "vincent", password: "***" | enable_sharing: false, encoding_compatibility: false | user1            |                   |
+----------+-------------+---------+-----------------------+------------------------------------------------------------------------------------------------+------------------------------------------------------+------------------+-------------------+
```

The first one is a system-wide mount the second one is user mount.
However a system-wide mount could also have a single applicable user, so it is not reliable to distinguish the mount scope.

**Comment by PVince81** [comment]
Moving to 9.1 as this is required for proper setup of wnd:listen.
CC @felixboehm 

@icewind1991 please address https://github.com/owncloud/core/pull/25171#issuecomment-226755414

**Comment by icewind1991** [comment]
Changed the description wording and added a 'Type' column if the `--all` option is provided

**Comment by PVince81** [comment]
Almost there:
```
# sudo -uwwwrun ./occ files_external:list -a
+----------+-------------+---------+-----------------------+------------------------------------------------------------------------------------------------+---------+------------------+-------------------+----------+
| Mount ID | Mount Point | Storage | Authentication Type   | Configuration                                                                                  | Options | Applicable Users | Applicable Groups | Type     |
+----------+-------------+---------+-----------------------+------------------------------------------------------------------------------------------------+---------+------------------+-------------------+----------+
| 1        | /sftp       | SFTP    | Username and password | host: "localhost", root: "\/home\/vincent\/temp\/sftpmount", user: "vincent", password: "***"  |         | All              |                   | Admin    |
| 2        | /sftp2      | SFTP    | Username and password | host: "localhost", root: "\/home\/vincent\/temp\/sftpmount2", user: "vincent", password: "***" |         | user1            |                   | Personal |
+----------+-------------+---------+-----------------------+------------------------------------------------------------------------------------------------+---------+------------------+-------------------+----------+
```

Looks good :+1: 

@guruz second review ?

**Comment by PVince81** [comment]
or @georgehrke

**Comment by georgehrke** [comment]
code looks good, testing ...

**Comment by georgehrke** [comment]
works 👍

**Comment by felixboehm** [comment]
awesome !

**Pull request merged**
