### PR TITLE
Remove dav migration for 9.1

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@karlitschek @jancborchardt as discussed

### CODE REVIEW

**Comment by jancborchardt** [comment]
Can not comment on the technical implementation, but yeah since we do not support updates skipping versions, it makes sense to remove the migration with 9.1

**Comment by rullzer** [comment]
Makes sense :+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by RealRancor** [comment]
And as always, updating the documentation when removing such stuff is missing: https://github.com/owncloud/documentation/issues/2645

**Pull request merged**
