### PR TITLE
migrate deprecated jQuery 1.x functions

### LINKED ISSUE #12877: Drop jquery-migrate v1
- enable the unminified (unsilenced) version of jquery-migrate
- look for JQMIGRATE warnings in the console log
- fix all of them
- announce on mailing list

### PR DESCRIPTION
**Pull request by ChristophWurst**
in preparation for #12877 

TODO:
- [x] WARN: 'JQMIGRATE: jQuery.browser is deprecated'
- [x] WARN: 'JQMIGRATE: jQuery.fn.unload() is deprecated'
- [x] WARN: 'JQMIGRATE: jQuery.parseJSON requires a valid JSON string'
- [x] WARN: 'JQMIGRATE: jQuery.fn.attr('checked') might use property instead of attribute'

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Code looks good. @ChristophWurst What is missing until this could be reviewed?

**Comment by ChristophWurst** [comment]
Well, these are just the errors I found by running the js tests. There are probably other pieces of code that need adaption. We could do it step-by-step and migrate the other code in another PR. In that case, this PR can be reviewed.

**Comment by MorrisJobke** [comment]
I did some smoke tests and it worked fine :)

👍 

cc @PVince81 @rullzer @Henni @skjnldsv review needed :)

**Comment by ChristophWurst** [comment]
@MorrisJobke note that as long as jquery-migrate is in use, nothing should break because it provides the APIs removed in the newer versions of jquery. So make sure you include the non-minified version of jquery-migrate when testing so you can see warnings in the console whenever a deprecated API is being used.

**Comment by MorrisJobke** [comment]
> @MorrisJobke note that as long as jquery-migrate is in use, nothing should break because it provides the APIs removed in the newer versions of jquery. So make sure you include the non-minified version of jquery-migrate when testing so you can see warnings in the console whenever a deprecated API is being used.

That is then part of a separate PR. I just tested that the current code change also works. If with or without the wrapper for old APIs doesn't matter here, because nothing is removed yet ;)

**Comment by rullzer** [comment]
Nice cleanup! Code makes sense!

I clicked around a bit. And stuff did not fall appart. 

:+1:

**Comment by rullzer** [comment]
nope... firefox + chromium here.
There are IE virtualbox images by MS...

**Comment by ChristophWurst** [comment]
ok, then let me check that quickly before merging

**Comment by ChristophWurst** [comment]
IE11 is detected, seems to work.

**Pull request merged**
