### PR TITLE
compress app banners on personal page

### PR DESCRIPTION
**Pull request by jancborchardt**
The banners for the desktop/Android/iOS apps on the Personal page weren’t fully compressed. Fixing this. Please review @owncloud/designers @PVince81 @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 merge please.

**Pull request merged**
