### PR TITLE
Fix federation panel

### PR DESCRIPTION
**Pull request by tomneedham**
Least interesting PR ever.

Context: https://github.com/owncloud/core/issues/27445

### CODE REVIEW

**Comment by mmattel** [comment]
Tested, checkbox is now visible, 
but text styles are different compared to the texts above (Allow username vs Add server):
image

And compared to the documentation:
image

Tested with Opera and FF on Ubuntu

**Comment by mmattel** [comment]
Addon: after hours, the federation was existing, the checkbox is now set, no item in trusted servers is shown...

**Comment by tomneedham** [comment]
@mmattel can you give me the html output of the panel?

**Comment by mmattel** [comment]
```
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" >
	<head data-user="mmm" data-user-displayname="mmm" data-requesttoken="NSBEXzMeP0EXYjwZDhsgaiBXCDkaeyEMeEMSACgHSXw=:Vlknruk3UMWpAyl9IepAbKIMJupYcIyI1xlfK8Q7Vws=">
		<meta charset="utf-8">
		<title>
			Settings - ownCloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="referrer" content="never">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=543672169">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta name="apple-mobile-web-app-title" content="Settings">
		<meta name="mobile-web-app-capable" content="yes">
		<meta name="theme-color" content="#1d2d44">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44">
		<link rel="manifest" href="/core/img/manifest.json">
					<link rel="stylesheet" href="/core/css/styles.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/inputs.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/header.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/icons.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/fonts.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/apps.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/global.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/fixes.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/multiselect.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/mobile.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/tooltip.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/share.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/apps/firstrunwizard/css/colorbox.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/apps/firstrunwizard/css/firstrunwizard.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/apps/federation/css/settings-admin.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/core/vendor/select2/select2.css?v=59d043cbba170572d5acad90ce76647a">
					<link rel="stylesheet" href="/settings/css/settings.css?v=59d043cbba170572d5acad90ce76647a">
									<script src="/core/js/oc.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/jquery/dist/jquery.min.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/jquery-migrate/jquery-migrate.min.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/underscore/underscore.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/moment/min/moment-with-locales.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/handlebars/handlebars.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/blueimp-md5/js/md5.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/bootstrap/js/tooltip.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/backbone/backbone.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/es6-promise/dist/es6-promise.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/davclient.js/lib/client.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/clipboard/dist/clipboard.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/bowser/src/bowser.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/jquery.ocdialog.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/oc-dialogs.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/js.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/l10n.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/octemplate.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/eventsource.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/config.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/search/js/search.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/oc-requesttoken.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/apps.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/mimetype.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/mimetypelist.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/snapjs/dist/latest/snap.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/oc-backbone.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/placeholder.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/jquery.avatar.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/shareconfigmodel.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/shareitemmodel.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/sharedialogresharerinfoview.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/sharedialoglinkshareview.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/sharedialogmailview.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/sharedialoglinksocialview.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/sharedialogexpirationview.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/sharedialogshareelistview.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/sharedialogview.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/share.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/apps/firstrunwizard/js/jquery.colorbox.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/apps/firstrunwizard/js/firstrunwizard.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/files/fileinfo.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/files/client.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/apps/federation/js/settings-admin.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/apps/federatedfilesharing/js/settings-admin.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/settings/js/settings.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/settings/js/admin.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/apps/files/js/jquery.fileupload.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/vendor/select2/select2.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/multiselect.js?v=59d043cbba170572d5acad90ce76647a"></script>
					<script src="/core/js/integritycheck-failed-notification.js?v=59d043cbba170572d5acad90ce76647a"></script>
					</head>
	<body id="body-settings">
	<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
	<div id="notification-container">
		<div id="notification"></div>
	</div>
	<header role="banner"><div id="header">
			<a href="/"
				id="owncloud" tabindex="1">
				<div class="logo-icon">
					<h1 class="hidden-visually">
						ownCloud					</h1>
				</div>
			</a>

			<a href="#" class="header-appname-container menutoggle" tabindex="2">
				<h1 class="header-appname">
					Settings				</h1>
				<img alt="" class="caret" src="/core/img/actions/caret.svg">
			</a>

			<div id="logo-claim" style="display:none;"></div>
			<div id="settings">
				<div id="expand" tabindex="6" role="link" class="menutoggle">
										<div class="avatardiv" style="display: none">
											</div>
										<span id="expandDisplayName">mmm</span>
					<img alt="" src="/core/img/actions/caret.svg">
				</div>
				<div id="expanddiv">
				<ul>
									<li>
						<a href="/settings/personal"
							 class="active">
							<img alt="" src="/settings/img/admin.svg">
							Settings						</a>
					</li>
									<li>
						<a href="/settings/users"
							>
							<img alt="" src="/settings/img/users.svg">
							Users						</a>
					</li>
									<li>
						<a href="/settings/help"
							>
							<img alt="" src="/settings/img/help.svg">
							Help						</a>
					</li>
									<li>
						<a id="logout" href="http://oclt/logout?requesttoken=NSBEXzMeP0EXYjwZDhsgaiBXCDkaeyEMeEMSACgHSXw%3D%3AVlknruk3UMWpAyl9IepAbKIMJupYcIyI1xlfK8Q7Vws%3D">
							<img alt="" src="/core/img/actions/logout.svg">
							Log out						</a>
					</li>
				</ul>
				</div>
			</div>

			<form class="searchbox" action="#" method="post" role="search" novalidate>
				<label for="searchbox" class="hidden-visually">
					Search				</label>
				<input id="searchbox" type="search" name="query"
					value="" required
					autocomplete="off" tabindex="5">
			</form>
		</div></header>

		<nav role="navigation"><div id="navigation">
			<div id="apps">
				<ul>
									<li data-id="files">
						<a href="/apps/files/" tabindex="3"
							>
							<img class="app-icon" alt="" src="/apps/files/img/app.svg">
							<div class="icon-loading-dark" style="display:none;"></div>
							<span>
								Files							</span>
						</a>
					</li>
								</ul>
			</div>
		</div></nav>

		<div id="content-wrapper">
			<div id="content" class="app-settings" role="main">
				
<div id="app-navigation">
	<ul class="with-icon">
		<li class="divider">Personal</li>
		<li><a class="svg  icon-user" href='/settings/personal?sectionid=general'>General</a></li><li><a class="svg  icon-folder" href='/settings/personal?sectionid=storage'>Storage</a></li><li><a class="svg  icon-password" href='/settings/personal?sectionid=security'>Security</a></li><li><a class="svg  icon-more" href='/settings/personal?sectionid=additional'>Additional</a></li>
			<li class="divider">Admin</li>
			<li><a class="svg  icon-settings" href='/settings/admin?sectionid=general'>General</a></li><li><a class="svg  icon-folder" href='/settings/admin?sectionid=storage'>Storage</a></li><li><a class="svg  icon-password" href='/settings/admin?sectionid=encryption'>Encryption</a></li><li><a class="svg  active  icon-share" href='/settings/admin?sectionid=sharing'>Sharing</a></li><li><a class="svg  icon-list" href='/settings/admin?sectionid=apps'>Apps</a></li><li><a class="svg  icon-info" href='/settings/admin?sectionid=help'>Help &amp; Tips</a></li><li><a class="svg  icon-more" href='/settings/admin?sectionid=additional'>Additional</a></li>	</ul>
</div>
<div id="app-content">
	        <div id="OC\Settings\Panels\Admin\FileSharing">
            <div id="shareAPI" class="section">
	<h2 class="app-name has-documentation">Sharing</h2>
	<a target="_blank" rel="noreferrer" class="icon-info"
		title="Open documentation"
		href="https://doc.owncloud.org/server/10.0/go.php?to=admin-sharing"></a>
	<p id="enable">
		<input type="checkbox" name="shareapi_enabled" id="shareAPIEnabled" class="checkbox"
			   value="1" checked="checked" />
		<label for="shareAPIEnabled">Allow apps to use the Share API</label><br/>
	</p>
	<p class="">
		<input type="checkbox" name="shareapi_allow_links" id="allowLinks" class="checkbox"
			   value="1" checked="checked" />
		<label for="allowLinks">Allow users to share via link</label><br/>
	</p>

	<p id="publicLinkSettings" class="indent ">
		<input type="checkbox" name="shareapi_allow_public_upload" id="allowPublicUpload" class="checkbox"
			   value="1" checked="checked" />
		<label for="allowPublicUpload">Allow public uploads</label><br/>

		<input type="checkbox" name="shareapi_enable_link_password_by_default" id="enableLinkPasswordByDefault" class="checkbox"
			   value="1"  />
		<label for="enableLinkPasswordByDefault">Always ask for a password</label><br/>

		<input type="checkbox" name="shareapi_enforce_links_password" id="enforceLinkPassword" class="checkbox"
			   value="1"  />
		<label for="enforceLinkPassword">Enforce password protection</label><br/>

		<input type="checkbox" name="shareapi_default_expire_date" id="shareapiDefaultExpireDate" class="checkbox"
			   value="1"  />
		<label for="shareapiDefaultExpireDate">Set default expiration date</label><br/>

		<input type="checkbox" name="shareapi_allow_public_notification" id="allowPublicMailNotification" class="checkbox"
			   value="1"  />
		<label for="allowPublicMailNotification">Allow users to send mail notification for shared files</label><br/>

		<input type="checkbox" name="shareapi_allow_social_share" id="allowSocialShare" class="checkbox"
			   value="1" checked="checked" />
		<label for="allowSocialShare">Allow users to share file via social media</label><br/>

	</p>
	<p id="setDefaultExpireDate" class="double-indent hidden">
		Expire after 		<input type="text" name='shareapi_expire_after_n_days' id="shareapiExpireAfterNDays" placeholder="7"
			   value='7' />
		days		<input type="checkbox" name="shareapi_enforce_expire_date" id="shareapiEnforceExpireDate" class="checkbox"
			   value="1"  />
		<label for="shareapiEnforceExpireDate">Enforce expiration date</label><br/>
	</p>
	<p class="">
		<input type="checkbox" name="shareapi_allow_resharing" id="allowResharing" class="checkbox"
			   value="1" checked="checked" />
		<label for="allowResharing">Allow resharing</label><br/>
	</p>
	<p class="">
		<input type="checkbox" name="shareapi_allow_group_sharing" id="allowGroupSharing" class="checkbox"
			   value="1" checked="checked" />
		<label for="allowGroupSharing">Allow sharing with groups</label><br />
	</p>
	<p class="">
		<input type="checkbox" name="shareapi_only_share_with_group_members" id="onlyShareWithGroupMembers" class="checkbox"
			   value="1"  />
		<label for="onlyShareWithGroupMembers">Restrict users to only share with users in their groups</label><br/>
	</p>
	<p class="">
		<input type="checkbox" name="shareapi_allow_mail_notification" id="allowMailNotification" class="checkbox"
			   value="1"  />
		<label for="allowMailNotification">Allow users to send mail notification for shared files to other users</label><br/>
	</p>
	<p class="">
		<input type="checkbox" name="shareapi_exclude_groups" id="shareapiExcludeGroups" class="checkbox"
			   value="1"  />
		<label for="shareapiExcludeGroups">Exclude groups from sharing</label><br/>
	</p>
	<p id="selectExcludedGroups" class="indent hidden">
		<input name="shareapi_exclude_groups_list" type="hidden" id="excludedGroups" value="" style="width: 400px"/>
		<br />
		<em>These groups will still be able to receive shares, but not to initiate them.</em>
	</p>
	<p class="">
		<input type="checkbox" name="shareapi_allow_share_dialog_user_enumeration" value="1" id="shareapi_allow_share_dialog_user_enumeration" class="checkbox"
			checked="checked" />
		<label for="shareapi_allow_share_dialog_user_enumeration">Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered.</label><br />
	</p>
</div>
        </div>
	        <div id="OCA\Federation\Panels\Admin">
            <div id="ocFederationSettings" class="section">
	<h2 class="app-name>"Federation</h2>
	<em>ownCloud Federation allows you to connect with other trusted ownClouds to exchange the user directory. For example this will be used to auto-complete external users for federated sharing.</em>

	<p>
		<input id="autoAddServers" type="checkbox" class="checkbox" checked />
		<label for="autoAddServers">Add server automatically once a federated share was created successfully</label>
	</p>

	<h3>Trusted ownCloud Servers</h3>
	<p id="ocFederationAddServer">
		<button id="ocFederationAddServerButton" class="">+ Add ownCloud server</button>
		<input id="serverUrl" class="hidden" type="text" value="" placeholder="ownCloud Server" name="server_url"/>
		<button id="ocFederationSubmit" class="hidden">Add</button>
		<span class="msg"></span>
	</p>
	<ul id="listOfTrustedServers">
			</ul>

</div>

        </div>
	        <div id="OCA\FederatedFileSharing\AdminPanel">
            
<div id="fileSharingSettings" class="section">
	<h2>Federated Cloud Sharing</h2>
	<a target="_blank" rel="noreferrer" class="icon-info svg"
		title="Open documentation"
		href="https://doc.owncloud.org/server/10.0/go.php?to=admin-sharing-federated"></a>

	<p>
		<input type="checkbox" name="outgoing_server2server_share_enabled" id="outgoingServer2serverShareEnabled" class="checkbox"
			   value="1" checked="checked" />
		<label for="outgoingServer2serverShareEnabled">
			Allow users on this server to send shares to other servers		</label>
	</p>

	<p>
		<input type="checkbox" name="incoming_server2server_share_enabled" id="incomingServer2serverShareEnabled" class="checkbox"
			   value="1" checked="checked" />
		<label for="incomingServer2serverShareEnabled">
			Allow users on this server to receive shares from other servers		</label><br/>
	</p>
</div>
        </div>
	</div>
			</div>
		</div>
	</body>
</html>
```

**Comment by tomneedham** [comment]
`<h2 class="app-name>"Federation</h2>` does not appear to match the `<h2 class="app-name">` from the diff. Please could you check `apps/federation/templates/settings-admin.php`

**Comment by mmattel** [comment]
My fault, because this was only one character, I did quick and dirty and added it manually to see - at the wrong place. Sorry for that.

**Review by mmattel — APPROVED** [review]
PR is ok and works now

**Comment by mmattel** [comment]
@tomneedham @DeepDiver1975  can you check why travis failed, this is a bugfix and needs to get into 10

**Comment by tomneedham** [comment]
Seems the tests passed, but `ERROR: No test report files were found. Configuration error?`

**Comment by mmattel** [comment]
ok, so how to merge, respectively who can merge?

**Comment by mmattel** [comment]
:+1:

**Pull request merged**
