### PR TITLE
Port sharing related tests to Share2.0

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Port sharing related tests to use the Share2.0 API.
Also moved old ShareTest tests to be integration tests instead, as they
cannot be applied directly as unit tests.

## Related Issue
Ref https://github.com/owncloud/core/pull/26608

## Motivation and Context
We want to move away from the old sharing code for files and folders, so the first step is to adjust the tests to not rely on that one. Then later on adjust the code itself, this is what I tried here https://github.com/owncloud/core/pull/26608

## How Has This Been Tested?
Just run the tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Tech debt

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@DeepDiver1975 @jvillafanez @butonic

### CODE REVIEW

**Comment by PVince81** [comment]
Note: there is likely more but this is a first step forward.

**Comment by PVince81** [comment]
```
17:43:27 1) Test\Files\ViewTest::testMoveMountPointIntoSharedFolder
17:43:27 InvalidArgumentException: Share does not have a full id
17:43:27 
17:43:27 /var/lib/jenkins/workspace/owncloud-core_core_PR-26610-7CGLOWUWW7YCOI3Q3BQJZ42IU2XWJIECIS423LISWQMF5CKP646Q/lib/private/Share20/Manager.php:775
17:43:27 /var/lib/jenkins/workspace/owncloud-core_core_PR-26610-7CGLOWUWW7YCOI3Q3BQJZ42IU2XWJIECIS423LISWQMF5CKP646Q/tests/lib/Files/ViewTest.php:1630
17:43:27 
17:43:27 2) OCA\Files_Sharing\Tests\UpdaterTest::testDeleteParentFolder
17:43:27 OCP\Share\Exceptions\ShareNotFound: Unspecified share exception
17:43:27 
17:43:27 /var/lib/jenkins/workspace/owncloud-core_core_PR-26610-7CGLOWUWW7YCOI3Q3BQJZ42IU2XWJIECIS423LISWQMF5CKP646Q/lib/private/Share20/DefaultShareProvider.php:534
17:43:27 /var/lib/jenkins/workspace/owncloud-core_core_PR-26610-7CGLOWUWW7YCOI3Q3BQJZ42IU2XWJIECIS423LISWQMF5CKP646Q/lib/private/Share20/Manager.php:963
17:43:27 /var/lib/jenkins/workspace/owncloud-core_core_PR-26610-7CGLOWUWW7YCOI3Q3BQJZ42IU2XWJIECIS423LISWQMF5CKP646Q/apps/files_sharing/tests/UpdaterTest.php:113
```

Hmm strange, but on the other PR these passed...

**Comment by PVince81** [comment]
Here, fixed.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
