### PR TITLE
Fixed #21542

### LINKED ISSUE #21542: 'Choose file' button for avatar image is not right located
### Steps to reproduce

1. Go to personal settings page
2. In Profile picture section, click on 'Select from files button'

### Expected behaviour

The button should fit inside the 'choose an image window' 

### Actual behaviour

The button is stack to the border

Note: It happens in several browsers, but the issue is more visible in Mozilla

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-07T04:44:34+00:00 d3922510d01fb5feed3ea01a3d390dfaa8b1312f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

screen shot 2016-01-08 at 12 39 19

### PR DESCRIPTION
**Pull request by ErikPel**
#21542

Before
9ef70142-b606-11e5-8e4e-60fef8accb10
After (ignore the language change)
owncloud

### CODE REVIEW

**Comment by PVince81** [comment]
@owncloud/designers is 3 pixels suitable here ?

**Comment by jancborchardt** [comment]
I was thinking it should be a bit more up, like 5px instead, to be more visually balanced with the right margin.

**Comment by ErikPel** [comment]
@jancborchardt
Alright, is that better?
image

**Comment by jancborchardt** [comment]
Yeah, it's just a bit but looks better, while not taking too much space from the dialog itself.

:+1:

@ErikPel can you squash your commits into one for cleaner history? And thanks a lot for your contribution – welcome to ownCloud and I'm looking forward to further design fixes from you. :)

**Comment by ErikPel** [comment]
@jancborchardt
Done I guess.
I think I messed something up and added someone elses commit by accident too?

**Comment by jancborchardt** [comment]
Yup, looks good. A second review please @PVince81 @owncloud/designers :)

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Hey @ErikPel welcome onboard :) Nice to see new contributors :) Ways how to get in touch with us beside GitHub (e.g. mailing lists or IRC) can be found here https://doc.owncloud.org/server/9.0/developer_manual/commun/index.html :)

**Pull request merged**
