### PR TITLE
[Stable10]skeletonfilessharing

### PR DESCRIPTION
**Pull request by bhawanaprasain**
Backport on: #35455

## Description

It includes API test when receiver has matching file name .

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests only (no source changes

### CODE REVIEW

**Comment by phil-davis** [comment]
What happened? This PR adds 19 lines. But the master PR #35434 has few hundred lines of diffs.

**Comment by individual-it** [comment]
@phil-davis this is the backport of #35455 that also has 19 lines

**Review by individual-it — APPROVED** [review]

**Comment by individual-it** [comment]
comment above was fixed

**Comment by phil-davis** [comment]
> @phil-davis this is the backport of #35455 that also has 19 lines

OK, the master PR number was wrong the first time and has been corrected now in the original post.

**Pull request merged**
