### PR TITLE
fix public link sharing if the master key is enabled

### LINKED ISSUE #21598: Public share fails when master key is enabled
Hello,

When master key is enabled in ownCloud 8.2.1, and a public link is accessed by a public user, the following screen is shown:

image

(In words: error "Private Key missing for user: please try to log-out and log-in again" shows up in browser)

However, any **logged in** user can download the file by accessing the same public link. A related pubShare_`<xxx>`.shareKey exists. No errors found in the ownCloud log.

In case this is a bug, it's really a show stopper to us. Please help, thanks.

### PR DESCRIPTION
**Pull request by schiessle**
fix https://github.com/owncloud/core/issues/21598

Steps to test:
1. Enable encryption with default module.
2. Run occ encryption:enable-master-key
3. Upload some files.
4. Public share one file.
5. Open it in another browser.

### CODE REVIEW

**Comment by schiesbn** [comment]
@karlitschek I would suggest to backport it to 8.2. Changes are minimal and it fixes public link share in combination with the newly introduced encryption master key.

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by SergioBertolinSG** [comment]
Works fine :+1: fixes 21598

**Comment by schiesbn** [comment]
8.2 backport: https://github.com/owncloud/core/pull/21614

**Pull request merged**
