### PR TITLE
[stable7] Do not overwrite the shareType so the post hook is still correct

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #13979 

cc @LukasReschke @schiesbn 

Backport approved by karlitschek @ https://github.com/owncloud/core/pull/13979#issuecomment-73509449

### CODE REVIEW

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Seems to work fine on stable7 ?

I tried the following:
1. Create two users "user1" and "user2"
2. Add "user2" in "group1"
3. As "user1" create a folder and share it with "group1"
4. Check activity of "user1": it says "shared with group1"
5. Check activity as "user2": it says "shared with you"

I don't see any difference before and after the fix.

**Comment by nickvergessen** [comment]
@PVince81 try:

1. Create two users "user1" and "user2"
2. Add "user2" in "group1"
3. As "user1" create a folder and share it with "user2"
3. Share the folder with "group1"
4. Check activity of "user1": it says "shared with group1"
5. Check activity as "user2": it says "shared with you"

So first share with the user, then with the group (the "sharing-collision" is needed)

**Comment by PVince81** [comment]
Tried your steps.
Before fix:
- activity of user1 says "You shared folder with user2"
- activity of user2 says "user1 shared folder with you"

After fix: (redoing the share)
- activity of user1 says "You shared folder with user2" AND "You shared folder with group1"
- activity of user2 says **twice** "user1 shared folder with you"

This sounds correct and logical :+1:

**Comment by LukasReschke** [comment]
Sharing black-magic :crystal_ball: 

Nothing exploded, seems to work :+1:

**Pull request merged**
