### PR TITLE
Fix backwards compatibility for mapper execute method

### LINKED ISSUE #14985: fetchRow method removed after upgrade to DBAL 2.5.x
Hi

When trying to run the Chat app with ownCloud master I'm getting this error:
````
( ! ) Fatal error: Call to undefined method Doctrine\DBAL\Statement::fetchRow() in /var/www/owncloud/apps/chat/lib/och/db/conversationmapper.php on line 110
````

The documentation says this
````
 public function authorNameCount($name) {
        $sql = 'SELECT COUNT(*) AS `count` FROM `*PREFIX*myapp_authors` ' .
            'WHERE `name` = ?';
        $query = $this->db->prepareQuery($sql);
        $query->bindParam(1, $name, \PDO::PARAM_STR);
        $result = $query->execute();

        while($row = $result->fetchRow()) {
            $result->closeCursor();
            return $row['count'];
        }
    }
````
Which is almost the same code as I'm using. I think this method is removed after upgrading to DBAL 2.5.x?

Why is this method removed?

### PR DESCRIPTION
**Pull request by BernhardPosselt**
Fix #14985 

@LEDfan can you check if this fixes it for you?

@LEDfan @DeepDiver1975 @MorrisJobke @PVince81 @LukasReschke

### CODE REVIEW

**Comment by LEDfan** [comment]
@Raydiation no this doesn't fix the issue. To see the error, just clone the Chat app and enable it.  Maybe you'll need more than one user on your instance. However replacing all occurrences of `fetchRow` by `fetch` do work. (Which I eventually will do, but I don't want other apps to break )

**Comment by Raydiation** [comment]
OK, this is kinda weird, can you debug further why this doesn't fix your issue?

**Comment by Raydiation** [comment]
OK I think I've got it: we also need to use prepareQuery instead of prepare if the db is an instance of IDb. Can you check if that works? I'll be back later this evening

**Comment by LEDfan** [comment]
@Raydiation replacing https://github.com/owncloud/core/blob/master/lib/public/appframework/db/mapper.php#L196 by
````
	// this is only for backwards compatibility reasons and can be removed
		// in ownCloud 10. See the comment at the end of this function.
		if ($this->db instanceof IDb) {
			$query = $this->db->prepareQuery($sql, $limit, $offset);
		} else {
			$query = $this->db->prepare($sql, $limit, $offset);
		}
````
works :) . However I can't push to this branch/origin.

**Comment by Raydiation** [comment]
Added, can you test again?

**Comment by LEDfan** [comment]
@Raydiation it solves the issue. :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
THX @Raydiation @LEDfan

**Pull request merged**
