### PR TITLE
Optionally show server hostname in status.php

### LINKED ISSUE #26941: Proposal: output of servername in status.php
For diagnostic reasons it is helpful in a clustered environment to see where we're having a problem. So, it might be helpful to change status.php like this:

```
/[root@owncloud01.MS owncloud]# diff status.php status2.php // 
//33c33// 
//< // 
//---// 
//> $servername = gethostname();// 
//36a37// 
//> 'servername'=>$servername,// 
//  
```

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
Allow config.php option to show hostname in status.php

## Related Issue
Fixes https://github.com/owncloud/core/issues/26941

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tomneedham** [comment]
Updated version of https://github.com/owncloud/core/pull/26973

**Comment by mmattel** [comment]
👍

**Comment by PVince81** [comment]
@tom please backport

**Comment by PVince81** [comment]
@tomneedham please backport

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/29471

**Pull request merged**
