### PR TITLE
Check if groupname is empty or already exists while creating user

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Before this change, the admin could create groups with empty name or multiple
times with the same name.
This has been fixed with this change.

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/4890

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
I can still add a group that is a single space character.

And I can add the same group multiple times (keep the dropdown open and keep adding the same group name):
add-group-many-times

**Review by phil-davis — APPROVED** [review]
works for me. I can't get "duplicate" groups. I can't add a group that is just spaces.

Note: I can add a group whose name starts with a space, like " aaa". But that is an existing long-time feature.

**Comment by JanAckermann** [comment]
> Note: I can add a group whose name starts with a space, like " aaa". But that is an existing long-time feature.

This is unacceptable, thx for hint, fixed.

**Comment by JanAckermann** [comment]
@micbar unfortunately we don't have a spec file for that, can you merge this?

**Review by JammingBen — APPROVED** [review]

**Pull request merged**
