### PR TITLE
Revert "Removed unnecessary check 'installed' system value' call."

### PR DESCRIPTION
**Pull request by LukasReschke**
Reverts owncloud/core#23171

This broke the setup.

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
The setup still works for me even without this revert :(

But I now rechecked the syntax and it makes sense to leave it there. :+1:

**Comment by nickvergessen** [comment]
Well installing via web UI was not possible. See #23254

**Comment by MorrisJobke** [comment]
Ah. I forgot to delete the.ocdata file

**Pull request merged**
