### PR TITLE
[8.2] use the default view for propagation if possible

### PR DESCRIPTION
**Pull request by icewind1991**
For #20329

9.0 doesn't need this since propagation is no longer tied to a view

cc @schiesbn @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by schiesbn** [comment]
I tried it, but it doesn't seem to work. I followed the steps from https://github.com/owncloud/core/issues/20329 but perform all action in the web interface and checked the etags.

After user 2 uploads a file to 'B' only the etag for 'files' changes for user1 but the etag for 'files/A' and 'files/B' stays the same.

**Comment by icewind1991** [comment]
@schiesbn should work now

**Comment by schiesbn** [comment]
works now :+1:

**Comment by schiesbn** [comment]
Bug was reported against 8.1 so we should probably backport it... @karlitschek

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
