### PR TITLE
Bump PHP to 5.6.33 in composer

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Bump PHP to 5.6.33 in ``composer.json``

## Motivation and Context
Before taking the plunge to PHP 7.1, might as well get ``master`` right up-to-date with the current PHP 5.6.33

## How Has This Been Tested?
CI will tell

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
This is a follow-on from #30242 and completes the obvious version bumps waiting to happen in ``master``

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
whats wrong with drone? only red all day long @patrickjahns

**Comment by phil-davis** [comment]
I restarted the drone job for this. Some crud in "files" UI test suite. @individual-it made a PR for another page load timing issue today, and we will gradually find other places where we need to put more check-and-wait code into the UI tests.

**Comment by DeepDiver1975** [comment]
LOL - jenkins is so nuts

```
15:46:33 This version of ownCloud requires at least PHP 7.1.0
15:46:33 You are currently running PHP 7.1.0RC4. Please update your PHP version.
15:46:33 No coverage
```

I need to update php on that machine ......

**Comment by DeepDiver1975** [comment]
WTF? https://jenkins.owncloud.org/job/owncloud-core/job/core/job/PR-28043/8/console

```
16:23:32 .........................................................PHP Fatal error:  Class Mock_DriverException_5eb04368 cannot implement interface Throwable, extend Exception or Error instead in /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(345) : eval()'d code on line 1
16:23:32 PHP Stack trace:
16:23:32 PHP   1. {main}() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/phpunit:0
16:23:32 PHP   2. PHPUnit_TextUI_Command::main() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/phpunit:52
16:23:32 PHP   3. PHPUnit_TextUI_Command->run() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/TextUI/Command.php:116
16:23:32 PHP   4. PHPUnit_TextUI_TestRunner->doRun() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/TextUI/Command.php:186
16:23:32 PHP   5. PHPUnit_Framework_TestSuite->run() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/TextUI/TestRunner.php:517
16:23:32 PHP   6. PHPUnit_Framework_TestSuite->run() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/Framework/TestSuite.php:733
16:23:32 PHP   7. PHPUnit_Framework_TestCase->run() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/Framework/TestSuite.php:733
16:23:32 PHP   8. PHPUnit_Framework_TestResult->run() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/Framework/TestCase.php:868
16:23:32 PHP   9. PHPUnit_Framework_TestCase->runBare() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/Framework/TestResult.php:686
16:23:32 PHP  10. PHPUnit_Framework_TestCase->runTest() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/Framework/TestCase.php:913
16:23:32 PHP  11. ReflectionMethod->invokeArgs() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/Framework/TestCase.php:1062
16:23:32 PHP  12. Test\DB\AdapterTest->testUpsertCatchDeadlockAndThrowsException() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/Framework/TestCase.php:1062
16:23:32 PHP  13. PHPUnit_Framework_TestCase->createMock() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/tests/lib/DB/AdapterTest.php:135
16:23:32 PHP  14. PHPUnit_Framework_MockObject_MockBuilder->getMock() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit/src/Framework/TestCase.php:1466
16:23:32 PHP  15. PHPUnit_Framework_MockObject_Generator->getMock() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit-mock-objects/src/Framework/MockObject/MockBuilder.php:117
16:23:32 PHP  16. PHPUnit_Framework_MockObject_Generator->getObject() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:268
16:23:32 PHP  17. PHPUnit_Framework_MockObject_Generator->evalClass() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:292
16:23:32 PHP  18. eval() /var/lib/jenkins/workspace/owncloud-core_core_PR-28043-BOJGKI6NLEZIKS5M6MYWFIBVGMTPQC6S4JKWY3BZKO5MWC5SLI7A/lib/composer/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:345
16:23:32 Kill the swift docker
16:23:32 Docker executable found - stop and remove docker containers
16:23:32 Stopping and removing docker container 7976700a7a2b4e3d903193e62c36fa52a3cb3de154d49b7568a83f774f8cd14d
16:23:44 7976700a7a2b4e3d903193e62c36fa52a3cb3de154d49b7568a83f774f8cd14d
16:23:44 7976700a7a2b4e3d903193e62c36fa52a3cb3de154d49b7568a83f774f8cd14d
16:23:44 Makefile:163: recipe for target 'test-php' failed
16:23:44 make: *** [test-php] Error 255

**Comment by patrickjahns** [comment]
@DeepDiver1975 
Why does it not fail then? weird stuff

**Comment by phil-davis** [comment]
@DeepDiver1975 are you posting in the wrong PR?
I don't see that in the Jenkins log here.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 are you posting in the wrong PR?

yeah - too-many-open-tabs-hell

**Pull request merged**
