### PR TITLE
install testing app for federation server in CI tests

### PR DESCRIPTION
**Pull request by individual-it**
## Description
testing app is needed also in fed. server

## Related Issue
https://github.com/owncloud/QA/issues/580

## How Has This Been Tested?
:robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by individual-it** [comment]
backport in #32411

**Comment by individual-it** [comment]
closing in favour of #32413

**Comment by individual-it** [comment]
reopening as discussed in the chat as  #32413 has more general issues to be solved

**Review by patrickjahns — APPROVED** [review]
temporary solution - for now 👍

**Pull request merged**
