### PR TITLE
Unskip login redirect test for issue 28129

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Unskip the previously skipped test that was waiting for issue 28129 to be resolved.

## Related Issue
#28129 

## Motivation and Context
PR #28255 has been merged, which fixes issue #28129 
So the related test will now pass, and can be run as part of the regular UI test suite.

## How Has This Been Tested?
Run UI login.feature tests locally

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
Rebased

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
please backport

**Comment by phil-davis** [comment]
Backport to stable10 #28538

**Pull request merged**
