### PR TITLE
Fix childs of slideToggle not sliding the target

### PR DESCRIPTION
**Pull request by Henni**
If the slideToggle, which is used for the settings in the navigation sidebar, contains a child element, this child element doesn't trigger the show or hide animation.
This problem occurs on the current master of the files and tasks app.

**Example**:

```
<button data-apps-slide-toggle=".slide-area"><span>Click me</span></button>
<div class=".slide-area" class="hidden">Slide Area</div>
```

If you click on "Click me" the _Slide Area_ isn't shown, whereas a click somewhere else within the button shows the _Slide Area_.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Comment by nickvergessen** [comment]
cc @MorrisJobke @jancborchardt

**Comment by jancborchardt** [comment]
Aaah, the same bug we have in the Mail app. This does not seem to fix it though? And how can I reproduce this in the Tasks app?

(Related: When I click on »Add list« in the tasks app on mobile then the sidebar closes. Maybe you need to add a `.noclose` there?)

cc @Raydiation as well

**Comment by Henni** [comment]
@jancborchardt where does this issue occur in the mail app?
The tasks app added a label to the settings slide toggle in one of the latest commits (owncloud/tasks@5dc74e71fb09cd90a6fc5ed43eeba84f95415060).

**Comment by jancborchardt** [comment]
@Henni for anything in the sidebar at the moment. It used to happen for the »New message« and »Add account« buttons since longer, see https://github.com/owncloud/mail/issues/600

**Comment by Henni** [comment]
@jancborchardt we are talking about to different issues it seems.
I am referring to the settings slider inside the navigation:
image

**Comment by Raydiation** [comment]
BTW this is for buttons inside slide up areas correct?

**Comment by Henni** [comment]
```
<button data-apps-slide-toggle=".slide-area"><span>Click me</span></button>
<div class=".slide-area" class="hidden">Slide Area</div>
```
@Raydiation the slideToggle button isn't a parent of any elements inside the slide up areas. So this works even with buttons inside the slide-area.

**Comment by Raydiation** [comment]
OK just wanted to make sure that this issue isn't caused by putting a slide area inside a button (which would be horribly wrong ;))

**Comment by DeepDiver1975** [comment]
@jancborchardt what are the next steps in here? THX

**Comment by jancborchardt** [comment]
@Henni indeed, I misunderstood! :)

Tested and your fix works! :+1:  – I also fixed the mouse cursor not having the micky-clicky look. :)

To test, simply open the Files app, and click on the »Settings« text bottom left. It won’t open on master. This fixes that.

**Comment by jancborchardt** [comment]
A second review please @owncloud/designers

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
