### PR TITLE
Free up folder content from memory before recursing in the file scanner

### PR DESCRIPTION
**Pull request by icewind1991**
Reduces memory usage for the scanner with larger folder structures

[comparison](https://blackfire.io/profiles/compare/d264ce36-184c-4587-9a8c-e84cc33d9c66/graph)

cc @MorrisJobke @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
I know this is supposed to be obvious but I don't seem to see it. Mind pointing out ?

**Comment by icewind1991** [comment]
By splitting of the main memory consuming into it's own function php free's up the memory before we start going recursive

**Comment by PVince81** [comment]
Thanks, so I got it right after all :smile:

**Comment by DeepDiver1975** [comment]
> Reduces memory usage for the scanner with larger folder structures
> 
> comparison

nice - can we document this a bit more please so that we can recreate this information in the future better?

- what is the test setup (# of file in # of folders with which depth)
- save a screenshot in the description of the comparison graph of blackfire

THX

**Comment by icewind1991** [comment]
> what is the test setup (# of file in # of folders with which depth)

```
/
  subfolder1/
    10k files
  subfolder2/
    10k files
  subfolder3/
    10k files
  10k files
```

**Comment by PVince81** [comment]
I'm fine with this :+1:

**Comment by MorrisJobke** [comment]
Scanning a (new) folder works 👍

**Pull request merged**
