### PR TITLE
refs #18241 Make the 'please reload this page' a clickable link

### PR DESCRIPTION
**Pull request by hutchic**
Simple fix for #18241.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@hutchic Thanks for the contribution. We currently working on our CI system. Therefore it doesn't work properly for PRs from forks.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

cc @PVince81 @nickvergessen @LukasReschke

**Comment by MorrisJobke** [comment]
I created a jenkins PR: #19699

**Comment by LukasReschke** [comment]
:+1:

**Comment by hutchic** [comment]
closing this PR as it was duplicated / merged in https://github.com/owncloud/core/pull/19699. TY

**Comment by MorrisJobke** [comment]
> closing this PR as it was duplicated / merged in #19699. TY

No. I didn't merged it. I just want to trigger the CI run. Okay... then I will reopen the other PR ;)

**Pull request closed without merging**
