### PR TITLE
Update sabre/dav to 3.0.9 on stable9

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of https://github.com/owncloud/core/pull/23839
3rdparty PR https://github.com/owncloud/3rdparty/pull/270

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3dparty merged - please update submodule - thx

**Comment by nickvergessen** [comment]
Done, please review @rullzer @MorrisJobke

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
