### PR TITLE
UI tests - make it possible to create users&groups using a table

### PR DESCRIPTION
**Pull request by individual-it**
## Description
This makes it possible for UI tests to create a bunch of users and groups using a behat table in the feature

## Motivation and Context
a handy way to quickly create users and groups for the tests

## How Has This Been Tested?
- travis run all current UI tests
- new UI tests in the file firewall are using this functionality

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
This will help with being able to create multiple users with different password in the "background/given" of features, and then be able to remember the password that goes with each user for later steps where that user does some action.

**Comment by individual-it** [comment]
add a little enhancement to be able to set also display name and email address

**Review by phil-davis — APPROVED** [review]
Latest enhancement for display name and email looks good.
This will be needed to test, e.g. when the sharing panel starts trying to match users based on their display name as well as the current UID-based matching.
@individual-it does not have any more goodies to add here - so others please review also.

**Comment by SergioBertolinSG** [comment]
This is duplicating the create user functionality. Which could be avoided creating a library.

**Comment by phil-davis** [comment]
The functionality needs to be available for UI tests. So the question is, for now, 
1) do we enhance the existing UI tests code that creates users so that it can do a bit extra (like here).
or
2) stop doing any new UI tests that need extra infrastructure like this, while we make some common library for the integration and UI tests to share

**Comment by felixboehm** [comment]
You can build a lib, but please do not block ongoing work until the lib is done.

**Review by felixboehm — APPROVED** [review]

**Comment by felixboehm** [comment]
@DeepDiver1975 please check the jenkins thingy. Thanks

**Comment by phil-davis** [comment]
Backported to stable10 in #28439

**Pull request merged**
