### PR TITLE
[admin settings] only retrieve log file size if file exists

### LINKED ISSUE #17467: Error messages when using syslog for logging
Version: 8.1
When set:
'log_type' => 'syslog',
'loglevel' => 1,
'logfile' => '',
'logtimezone' => 'FooTZ',
'log_authfailip' => true,

every call to the admin page will result an error message like this: {PHP} filesize(): stat failed for /var/www/html/owncloud/data/owncloud.log at /var/www/html/owncloud/settings/admin.php#49

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #17467 

cc @georgehrke @nickvergessen @LukasReschke @rullzer @Xenopathic 

@karlitschek Backport to stable8.1 would be nice

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@tuxmaster please test if this fixes your issue

**Comment by karlitschek** [comment]
yes. backport makes sense :+1:

**Comment by georgehrke** [comment]
:+1:

**Comment by tuxmaster** [comment]
Yes tested ->works :)

**Comment by Xenopathic** [comment]
:+1:

**Pull request merged**
