### PR TITLE
Fix SMB backend registration

### LINKED ISSUE #24903: After Upgrade: Error: Unable to get backend for smb
### Steps to reproduce
After fixing the issue with upgrading from 9.0.2 with daily build (today), every thing worked but not SMB
(See https://github.com/owncloud/core/issues/24871#issuecomment-222518463)

Other instances running 9.0.2 have a working SMB external storage backend (=not server dependent)

### Expected behaviour
Upgrade should keep smb as storage backend

### Actual behaviour
There is no SMB/CIFS in the list of available external storages, the log gets continious entries regarding the failing backend

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.14

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.2 RC1 (daily) Build:2016-04-28T03:03:12+00:00 795f321a1985b682bff584f252dd6f2fd95dad65

**Updated from an older ownCloud or fresh install:**
This was a fresh setup from tar and updated once, daily channel

**Where did you install ownCloud from:**
tar

**Signing status (ownCloud 9.0 and above):**

```
Datei nicht gefunden
Das ausgewählte Dokument wurde auf dem Server nicht gefunden.
Sie können zur Rückkehr zu ownCloud hier klicken.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ock982ae3c5s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxxx",
        "dbtype": "mysql",
        "version": "9.0.2.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "xxxx",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "xxxx",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

#### owncloud.log
```
{"reqId":"VJrPVoyiymDUFhr\/1bNx","remoteAddr":"xx.xx.xx.xx","app":"files_external","message":"Could not load storage: \"Unable to get backend for smb\"","level":3,"time":"2016-05-30T18:34:20+02:00","method":"GET","url":"\/index.php\/apps\/files_external\/globalstorages","user":"user_x"}
{"reqId":"VJrPVoyiymDUFhr\/1bNx","remoteAddr":"xx.xx.xx.xx","app":"files_external","message":"Could not load storage: \"Unable to get backend for smb\"","level":3,"time":"2016-05-30T18:34:20+02:00","method":"GET","url":"\/index.php\/apps\/files_external\/globalstorages","user":"user_x"}
{"reqId":"SyTaxKShqoCrZSJlbqDN","remoteAddr":"xx.xx.xx.xx","app":"files_external","message":"Could not load storage: \"Unable to get backend for smb\"","level":3,"time":"2016-05-30T18:34:20+02:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"user_x"}
{"reqId":"85M6jXNGOMMxzgSdxNaB","remoteAddr":"xx.xx.xx.xx","app":"files_external","message":"Could not load storage: \"Unable to get backend for smb\"","level":3,"time":"2016-05-30T18:34:20+02:00","method":"PROPFIND","url":"\/remote.php\/webdav","user":"user_x"}
{"reqId":"EcHPtV04l2+ahR30l0QP","remoteAddr":"xx.xx.xx.xx","app":"files_external","message":"Could not load storage: \"Unable to get backend for smb\"","level":3,"time":"2016-05-30T18:34:20+02:00","method":"GET","url":"\/index.php\/settings\/ajax\/checksetup","user":"user_x"}
{"reqId":"VoTlBBZ1N5z4X4eFupQG","remoteAddr":"xx.xx.xx.xx","app":"files_external","message":"Could not load storage: \"Unable to get backend for smb\"","level":3,"time":"2016-05-30T18:34:20+02:00","method":"GET","url":"\/index.php\/heartbeat","user":"user_x"}
{"reqId":"iZkZrUhEE65Oij0nKRPi","remoteAddr":"xx.xx.xx.xx","app":"files_external","message":"Could not load storage: \"Unable to get backend for smb\"","level":3,"time":"2016-05-30T18:34:39+02:00","method":"GET","url":"\/index.php\/logout?requesttoken=VVdKTwEGFQUwEC19P1cEEHF%2BL0NeBGVUMDpqZgUkFQ4%3D%3Ac93544SJIHiDE4oVEKG1jA5lhY8Q0uogv84bmGm3Khc%3D","user":"user_x"}
```

#### webserver.log
There is no corresponding webserver error log

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Fixes #24903 

cc @mmattel @owncloud/filesystem

### CODE REVIEW

**Comment by mmattel** [comment]
Tested, works :+1:

**Comment by nickvergessen** [comment]
https://3v4l.org/cKvXn confirmed :+1: 
Same behaviour from 4.3.0 till 7.0.7

The dark handling of php arrays at its best.

**Comment by nickvergessen** [comment]
Okay stable9 looks unaffected

**Comment by Xenopathic** [comment]
Yeah, the regression was introduced with a recent PR of mine that only exists in master :see_no_evil:

**Pull request merged**
