### PR TITLE
Fixed bug #19116

### PR DESCRIPTION
**Pull request by gmurayama**
Sorry about last pull request. This time I checked if I was merging the right files.

### CODE REVIEW

**Comment by karlitschek** [comment]
@PVince81

**Comment by PVince81** [comment]
Thanks for the pull request.
Ref to the ticket here for easy access: https://github.com/owncloud/core/issues/19116

I don't think this is the correct approach. It should be possible to upload 0 byte files, but the algorithm might require an approach where it only creates the file with no contents whenever this situation is detected.

Think of the following use case: a user has a local folder with 50 files and wants to upload them. The user uses either drag and drop for all 50 files from the local folder into the browser or using the upload dialog. If one of the file has zero bytes, it should still be possible to upload it and see it.
Failure to do so means that the user would have to keep track of which empty files they need to manually recreate over the web UI or using a different method.

**Comment by gmurayama** [comment]
@PVince81 Understood. I think I'm going try it that way, in a couple of days I may be able to upload this algorithm. So, should I upload in a new request or just leave it be? Firefox doesn't allow, but Chrome doesn't act in the same way.

**Comment by PVince81** [comment]
It is best to upload it using the regular upload.php but make sure that it doesn't fail with 0 bytes, it should simply create the file and that's it. As before it also needs to check for conflicts, but that should be handled by the upload.php already.

**Pull request closed without merging**
