### PR TITLE
[stable10] scroll in modals

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Allow scrolling in modals if the window height is less than the modal height.

_Expected behavior:_
If a modals height is greater than the window height then its contents should be scrollable.

_Actual behavior:_
The contents of the modal expand beyond the vertical space and the user is not able to interact/reach them.

## How Has This Been Tested?
Visual tests in Chrome, FF

## Screenshots (if appropriate):
fireshot capture 20 - dateien - owncloud_ - http___192 168 21 18_8000_index php_apps_files_

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ChrisEdS** [comment]
Und täglich grüßt das Murmeltier.

**Review by ChrisEdS — COMMENTED** [review]
Code looks much cleaner. Is there a different to https://github.com/owncloud/core/pull/30311 ?

**Comment by phil-davis** [comment]
This is a backport of #30311 
So the code diffs are the same (good)

**Review by ChrisEdS — APPROVED** [review]
Go.

**Comment by phil-davis** [comment]
I restarted drone. Let's see our luck this time...

**Comment by davitol** [comment]
Manuaally tested and it LGTM

**Comment by PVince81** [comment]
restarted drone job

**Comment by felixheidecke** [comment]
> restarted drone job

hmm … hope it helps this time. Didn't help 3 days ago 😢

**Pull request merged**
