### PR TITLE
PHP mimetype stuff should also use config/mimetypealiases.json

### PR DESCRIPTION
**Pull request by rullzer**
The title is pretty clear ;)

Bases on my mimetype-js branch. Should only be merged after #16724 is in!

Pretty trivial change.

### CODE REVIEW

**Comment by Xenopathic** [comment]
:+1: for the last commit

**Comment by rullzer** [comment]
#16724  is in. Rebased. Now even easier to review.

CC: @PVince81 @MorrisJobke

**Comment by rullzer** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
Suggestion: filesystem reads can be slow, use a memcache for this?

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by rullzer** [comment]
Mmm the _comment entries made it convert to a StdClass. should be fixed now

**Comment by rullzer** [comment]
> Suggestion: filesystem reads can be slow, use a memcache for this?

@Xenopathic I agree. But this class uses multiple access to file_exists anyway. So I guess that is something for a later PR.

**Comment by PVince81** [comment]
Mimetype icons still work in the files app (the files app is still using the PHP code at this time).

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Yes. It still works :+1:

**Pull request merged**
