### PR TITLE
Return 401 when accessing public webdav and s2s is disabled

### PR DESCRIPTION
**Pull request by PVince81**
This will make sure the connecting server gets a proper error code.

`return false` was wrong anyway.

Please review @icewind1991 @schiesbn @th3fallen 

Should fix the 500 reported here https://github.com/owncloud/core/issues/16439

### CODE REVIEW

**Comment by PVince81** [comment]
also @LukasReschke

**Comment by icewind1991** [comment]
Looks good :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by davitol** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@PVince81 Is a backport reasonable?

**Pull request merged**
