### PR TITLE
Mapping of m3u, m3u8, pls to audio streams

### PR DESCRIPTION
**Pull request by Rello**
Usage of m3u, m3u8, pls as audio playlists according to their standard
https://en.m.wikipedia.org/wiki/M3U
https://en.m.wikipedia.org/wiki/PLS_(file_format)

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: assuming you tested this already

**Comment by PVince81** [comment]
@Rello please backport to stable10

**Comment by Rello** [comment]
@PVince81 can you help me "how" I need to backport? then I will take care

**Comment by phil-davis** [comment]
You need a local clone of the core repo, then something like:
```
git checkout master
git fetch origin
git pull
git checkout stable10
git pull
```
That makes sure that your local clone is up-to-date in both branches.
Then from being on ``stable10`` branch, make a new branch off it:
```
git checkout -b stable10-m3u
```
Then find the commit id (SHA) of the commit in master that needs to be backported. Look in GitHub https://github.com/owncloud/core/commits/master and copy the relevant "magic number". Do a cherry-pick:
```
git cherry-pick fb5b2497c85cf2791960001c7e5861fefc4fcdfb
```
then push it up to GitHub:
```
git push --set-upstream origin stable10-m3u
```
Then on GitHub make a pul request and choose "stable10" as the base for the pull request.

I did the above and ended up with PR #28885

**Comment by phil-davis** [comment]
Backport stable10 #28885

**Comment by PVince81** [comment]
I forgot to verify this: https://github.com/owncloud/core/issues/28967

**Pull request merged**
