### PR TITLE
fix selenium tests

### PR DESCRIPTION
**Pull request by individual-it**
trying to fix selenium tests

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Great @individual-it , thanks for your help.

**Review by SergioBertolinSG — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
i guess we need to backport this ... @PVince81 right?

**Review by DeepDiver1975 — COMMENTED** [review]
...

**Comment by SergioBertolinSG** [comment]
These tests weren't backported to stable9.1.

**Comment by DeepDiver1975** [comment]
> These tests weren't backported to stable9.1.

true :confused: thx

**Pull request merged**
