### PR TITLE
[9.2] Adding Open Graph Support for public shares http://ogp.me/

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Sharing a image where a preview can be generated:
bildschirmfoto von 2016-07-26 21-31-47

Sharing a PDF where no preview is available an we fallback to the logo
bildschirmfoto von 2016-07-26 21-32-04

### CODE REVIEW

**Comment by tcitworld** [comment]
May there be a default `og:image` even if we have no preview (like the oC logo) or is it a bad practice to provide a picture that doesn't indicate content ?

**Comment by DeepDiver1975** [comment]
> May there be a default og:image even if we have no preview (like the oC logo)

sounds reasonable to me

**Comment by DeepDiver1975** [comment]
@wotanii please help testing this - thx

**Comment by wotanii** [comment]
I don't really know what to test, so I changed my instance of owncloud 8.2.7 to include this PR. 

- I moved all changes to public.php. It now look like [this](https://owncloud.wotanii.de/index.php/s/izhjalkDdzNjVCW)
- I shared some links:
  - password-protected: https://owncloud.wotanii.de/index.php/s/h5MyR1RUfG6AEV3/authenticate
  - pdf file: https://owncloud.wotanii.de/index.php/s/2N6pV82xi6FCD3r#pdfviewer
  - jpg: https://owncloud.wotanii.de/index.php/s/Q42PHXkSBW8x28P
- and when you send them via telegram, those links look like this: 
bildschirmfoto von 2016-09-17 13-23-24

So everything seems to work fine. Although I'm not sure what the deal with `$shareTmpl['shareUrl']`is. I left it out in my "backport", because I don't really see why it's there in the first place.

**Comment by DeepDiver1975** [comment]
Ready for final review, test and merge from my pov

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/12946

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
