### PR TITLE
[stable9] fix ldap:check-user command / User Cleanup does not work

### PR DESCRIPTION
**Pull request by felixboehm**
Fixes User Cleanup does not work https://github.com/owncloud/enterprise/issues/1431
Related: https://github.com/owncloud/core/issues/22024#issuecomment-177932477

@PVince81 @butonic

### CODE REVIEW

**Comment by PVince81** [comment]
@owncloud/ldap @DeepDiver1975 

@felixboehm please note that in general PRs have to be submitted against master and backported afterwards.

After reviewing this PR will need to submit PRs for stable9.1 and master too.

**Comment by PVince81** [comment]
@owncloud/qa can you help testing this ? Also check if previous versions are affected.

**Comment by SergioBertolinSG** [comment]
Works 👍

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
Requires PRs for stable9.1 and master

**Comment by DeepDiver1975** [comment]
> Requires PRs for stable9.1 and master

on it

**Comment by PVince81** [comment]
We might also want to backport to 8.2 ? (depending when that command was introduced)

**Comment by DeepDiver1975** [comment]
master #25344

**Comment by SergioBertolinSG** [comment]
Stable8.2 is affected.

**Comment by PVince81** [comment]
@DeepDiver1975 can you also submit a backport to 8.2 ?

**Comment by SergioBertolinSG** [comment]
Stable8.1 affected as well.

**Comment by DeepDiver1975** [comment]
backports have been prepared

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/issues/25394
stable8.1: https://github.com/owncloud/core/issues/25393

**Pull request merged**
