### PR TITLE
Fix wrong path generation

### LINKED ISSUE #15742: Inverted arguments in ResourceNotFoundException
The variables being concatenated are swapped : https://github.com/owncloud/core/blob/master/lib/private/template/resourcenotfoundexception.php#L42

This makes for disconcerting log messages such as:
 `Could not find resource file "js/app.min.js//owncloud/apps/chat"`

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fix #15742 

cc @zinks- @nickvergessen @LukasReschke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
unit test? THX

**Comment by nickvergessen** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> unit test? THX

@MorrisJobke

**Comment by nickvergessen** [comment]
added a test

**Comment by MorrisJobke** [comment]
@nickvergessen :+1: for the unit tests

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
