### PR TITLE
Store the personal certificates in the user's home directory

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Store personal SSL certificates inside the user's home folder.
Note that there are some additional cases (commented in the code) to be checked, which might need a bigger refactor

## Related Issue
https://github.com/owncloud/enterprise/issues/3961

## How Has This Been Tested?
Manually verified with additional changes in the code to open an easy entrypoint. Note that there isn't an official way to provide personal certificates in core, and there could be 3rd party apps using this support.
The certificates end up in the right location

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by mmattel** [comment]
The label 3-to review was set but no reviewer added...

**Comment by phil-davis** [comment]
A drone agent seemed to hang and timeout after 3 hours: https://drone.owncloud.com/owncloud/core/25332/116/15

I restarted the drone CI just now.

**Comment by mmattel** [comment]
Q: does this PR need a docs change?

**Comment by jvillafanez** [comment]
I don't think this needs any change in the docs. It isn't a new feature.

**Comment by mmattel** [comment]
With this new PR, certificates are stored in the users `files_external` directory.
What are you doing with existing user certificates? Is there any mitration possible/necessary?

Coming back to docs, if we delete a user with the current setup, will the certificates get orphaned? If so, we should write for 10.5 that deleting a user also deletes the certificates. (ref: https://doc.owncloud.com/server/10.5/admin_manual/configuration/server/import_ssl_cert.html)
If certificates do not get orphaned, what is the way of removing the certificates exactly for that deleted user. There is also no mentioning in docs about that?

**Comment by jvillafanez** [comment]
> What are you doing with existing user certificates? Is there any migration possible/necessary?

That's something to be decided. I don't know how many installations are / will be affected, or how big those installations are. The easiest workaround would be for the users to reupload the certificates.
Note that personal certificates doesn't seem to be "officially" supported by ownCloud for a while, not sure if intentionally or not. I haven't seen a way to upload personal certificates from the web UI.

> if we delete a user with the current setup, will the certificates get orphaned?

Certificates are stored within the user's data directory, so they're expected to be removed when the user's account is removed.
In case of the certificates stored in the wrong user's directory, the user delete command has been improved with a `--force` option recently to remove the user even if it doesn't exists. This should help to deal with this case by removing the wrong account (not tested, but should work)

**Comment by mmattel** [comment]
@jvillafanez 
For better understanding this change, you may add a certificate with the existing functionality and print the path and then do the same with this PR. So we can see the difference more easily.

**Comment by jvillafanez** [comment]
The case where this was detected was:
* A user from ldap ("abcde") with a home directory of "homes/001-abcde" (for example).
* The user_ldap app configured to use the home directory attribute

The expected base path for the user's content in this case is `<data-directory>/homes/001-abcde/`. Certificates for that user should be stored in `<data-directory>/homes/001-abcde/files_external`, however, without this fix, the certificates end up in `<data-directory>/abcde/files_external`.

Note that deleting the "abcde" user in this scenario is expected to delete the `<data-directory/homes/001-abcde` folder as long as the user is present with that directory as home.
Also note that there could be a valid "abcde" local account with `<data-directory>/abcde` folder as home

There could be additional twisted scenarios to be taken into account, and it's unclear how many installations are using this feature a part from the one that reported this problem.

**Comment by pako81** [comment]
> That's something to be decided. I don't know how many installations are / will be affected, or how big those installations are. The easiest workaround would be for the users to reupload the certificates.

I don't think there is a way for users to upload such certificates. Those are automatically created. So maybe the way to go in case of such migration scenarios is having the admin moving over certs for existing users to the right location? For new users, certs should already land in the correct place thanks to this PR.

My gut feeling is that this affecting a very small percentage of installations out there.

**Comment by micbar** [comment]
@VicDeo can we get a code review?

**Comment by VicDeo** [comment]
@micbar  @jvillafanez  I'm not aware of any ability for **user** to store a certificate...
and `occ security:certificates:import` does **NOT** work per user.

https://github.com/owncloud/enterprise/issues/3961 seems to be wrongly qualified as a bug

**Comment by micbar** [comment]
> @micbar @jvillafanez I'm not aware of any ability for **user** to store a certificate...
> and `occ security:certificates:import` does **NOT** work per user but per instance
> 
> [owncloud/enterprise#3961](https://github.com/owncloud/enterprise/issues/3961) seems to be wrongly qualified as a bug

That is entirely true.

**Comment by VicDeo** [comment]
@micbar wait... I found how to reproduce it, but i need to setup LDAP to check if the fix is working

**Comment by phil-davis** [comment]
And this needs a changelog entry.
So please add one and rebase... when trying out the next iteration.

**Comment by micbar** [comment]
ok, so this is valid - fine.

**Comment by micbar** [comment]
Dont rush, we will not include in 10.5.0 as clarified with @pako81

**Comment by VicDeo** [comment]
@micbar @jvillafanez @pako81 
here what I did:
oc@master, 
user_ldap@master
1. Settings -> admin -> storage 
Allow users to mount external storage  is checked
2. Connect ou with the single user  to ldap, set **deparmentNumber** for this user to 
'/tmp/african'
3. set `User Home Folder Naming Rule` to **attr:departmentNumber**
4. `php occ user:sync -m remove "OCA\User_LDAP\User_Proxy"` 
5. login as this user
6. tried to add Webdav storage for a valid domain at personal -> storage
7. 
```
s -l data/
total 844
drwxr-x--- 4 deo www   4096 Jun 23 12:55 admin
-rw-r--r-- 1 deo www    145 Sep 26  2019 htaccesstest.txt
-rw-r--r-- 1 deo www      0 Jun 23 13:58 index.html
-rw-r--r-- 1 deo www   4096 Jul 30  2019 owncloud.db
-rw-r----- 1 deo www 842168 Jun 23 15:49 owncloud.log
-rw-r--r-- 1 deo www    447 Apr 29 15:56 update.log
```

8. 
```
> ls -l /tmp/african/
total 20
drwxr-x--- 3 deo www 4096 Jun 23 15:39 archive
drwxr-xr-x 2 deo www 4096 Jun 23 15:39 cache
drwxr-xr-x 2 deo www 4096 Jun 23 15:39 files
drwxr-xr-x 2 deo www 4096 Jun 23 15:40 files_external
drwxr-xr-x 3 deo www 4096 Jun 23 15:39 thumbnails
```

so, `files_external` was created at the correct location for master.
It would be nice to have the more details on the env where the bug is reproducible.

**Comment by phil-davis** [comment]
@jvillafanez @micbar is this a thing that is moving ahead for 10.6 ?

**Comment by jvillafanez** [comment]
Without clear steps to reproduce we can't verify properly if this PR solves the problem.

**Comment by micbar** [comment]
needs to be tested with the customer first @cdamken

**Comment by mmattel** [comment]
Ping, any news on that?

**Comment by phil-davis** [comment]
Why did this PR suddenly get a codecov report posted to it?
There was no rebase, and the link to the drone run goes to a drone build that was 6 months ago!

**Comment by phil-davis** [comment]
I rebased - this needs fresh CI anyway.

**Review by micbar — APPROVED** [review]
LGTM

**Comment by phil-davis** [comment]
CI was red, so I rebased again. Let's see what happens :)

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/28954/9/8
There are unit test fails. @jvillafanez ?

**Comment by DeepDiver1975** [comment]
cleaning up - I think this is no longer of anybody's interest

**Pull request closed without merging**
