### PR TITLE
[WIP] Update guzzle and add integration test capabilities settings

### PR DESCRIPTION
**Pull request by phil-davis**
About to try integrating the Guzzle update with some integration test refactoring.
First pass - the Guzzle change and see if they pass CI OK.

### CODE REVIEW

**Comment by individual-it** [comment]
duplication of #28063

**Comment by phil-davis** [comment]
Yes, last week I noticed that there was work to move to Guzzle v6 that changed quite a lot of integration test files. So I quickly did a merge of my proposed integration test refactoring changes on top of it - to see if there would be a lot of annoying conflicts. Actually it was quite easy to resolve the conflicts and Jenkins comes up with the same set of test fails as are currently happening in #28063 

So my proposed refactorings in #28970 will not cause too much pain (and do not break anything for #28063 )

**Comment by PVince81** [comment]
@phil-davis feel free to push directly to https://github.com/owncloud/core/pull/28063 if your changes help solving / simplifying the Guzzle update

**Comment by PVince81** [comment]
most of the guzzle related changes are on the tests anyway. The core changes are rather small.

**Comment by phil-davis** [comment]
@PVince81 I will look in the morning. After the merge of my integration test stuff today, that WIP PR of yours will have conflicts to be resolved, but they are not difficult. Then there were a list of failed integration test scenarios. From memory, the fails in Jenkins here were the same as in your other PR:
```
490 scenarios (355 passed, 135 failed)
4522 steps (3772 passed, 135 failed, 615 skipped)
```
so there i a bit of guzzling to be done to tweak it into success.

**Comment by phil-davis** [comment]
See #29211 for "the final solution"

**Pull request closed without merging**
