### PR TITLE
Add config lang

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Requirement for:
https://github.com/owncloud/web/issues/6243

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by jvillafanez** [comment]
The idea looks ok to me.

Do we have any plans for adding more information in the "config" key? Otherwise, it seems better to use the "language" key directly.
In addition, should we include the default configured language if the user hasn't configured anything? or maybe include the default in a different key?

**Comment by phil-davis** [comment]
> In addition, should we include the default configured language if the user hasn't configured anything? or maybe include the default in a different key?

The code could return the "effective" language for the user. If the user has explicitly set a language, then return that. If the user has not set a language then return the system default language (which is the language that the user is going to be shown when they log in). There must already be a function somewhere for `getEffectiveLanguage`

**Comment by phil-davis** [comment]
> get default system lang if not user specified

works

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiSharingNotificationsToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/35794/103

**Review by kulmann — APPROVED** [review]
😍

**Comment by kulmann** [comment]
> The code could return the "effective" language for the user. If the user has explicitly set a language, then return that. If the user has not set a language then return the system default language (which is the language that the user is going to be shown when they log in). There must already be a function somewhere for `getEffectiveLanguage`

Fully agree, clients don't/shouldn't know or care where the language key comes from. They only need a value. The chain of fallbacks as proposed and implemented is perfect. 👍  (user choice -> system default -> hardcoded "en")

**Pull request merged**
