### PR TITLE
Update 3rdparty commit for sabre update 3.0.8

### PR DESCRIPTION
**Pull request by PVince81**
CI for 3rdparty commit https://github.com/owncloud/3rdparty/pull/258

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3rdparty pr merged - please update submodule

**Comment by PVince81** [comment]
Updated to point at 3rdparty/master (and force-pushed)

**Comment by DeepDiver1975** [comment]
> Updated to point at 3rdparty/master (and force-pushed)

thx

**Comment by rullzer** [comment]
house did not burn down... :+1:

**Comment by PVince81** [comment]
@DeepDiver1975 merge ?

**Pull request merged**
