### PR TITLE
Fix missing checkboxes in file comparator

### LINKED ISSUE #19135: Missing check boxes in file comparator
checkboxes

@Henni

### PR DESCRIPTION
**Pull request by Henni**
fixes #19135 

cc @oparoz

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by nickvergessen** [comment]
Doesn't work for me, they still don't show up

**Comment by Henni** [comment]
@nickvergessen should look like this:
image

**Comment by nickvergessen** [comment]
yeah, should... on does in Chrome,

but firefox is still broken

**Comment by Henni** [comment]
@nickvergessen Works fine for me in firefox.

**Comment by nickvergessen** [comment]
Works in private mode, so seems to be caching or something.

:+1:

**Pull request merged**
