### PR TITLE
keep spaces out of translation

### PR DESCRIPTION
**Pull request by vgezer**
otherwise translators cannot notice it on Transifex

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by wakeup** [comment]
thx!

**Comment by LukasReschke** [comment]
I guess this fixes https://github.com/owncloud/core/issues/13246 then?

**Comment by wakeup** [comment]
@LukasReschke yes! thanks for finding. accidentally a fix for it :smile:

**Pull request merged**
