### PR TITLE
Let files_share only fetch data from oc_appconfig what is actually needed.

### PR DESCRIPTION
**Pull request by schnidrig**
## Description

We at SWTICH had severe performance problems due to a large oc_appconfig table which was fetched from the db on every request.

With this patch, we could retire 80% of the app-server hardware and get a much faster average response times.

Also we could reduce our db galera cluster back to a three node cluster and now it is running with very little load (we had six servers before and they could hardly keep up).

It is a very small change, but it make a hell of a difference performance wise.

## Related Issue

https://github.com/owncloud/core/issues/26900

## Motivation and Context

performance

## How Has This Been Tested?

On our production site. We have 24K Users.

## Screenshots (if appropriate):

The following graphs show some load and timing graphs from the day when we applied the patch. 

screen shot 2017-02-27 at 11 59 34
screen shot 2017-02-27 at 12 01 46
screen shot 2017-02-27 at 11 59 58

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
@schnidrig thanks, but 8.1 is EOL so there won't be any more releases for that version: https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

This performance hack could be used for 8.2 at least where the oc_appconfig table still contains the many share entries that cause slowness.

Starting with 9.0 these entries will not be there any more so the hack should not be needed any more.

@butonic @DeepDiver1975 @jvillafanez thoughts about porting this to 8.2 ?

**Comment by PVince81** [comment]
Apparently this is not directly reusable for 8.2 because 8.2 seems to preload **all** config keys in memory first before giving access to them.

It looks like 8.2 already solved this somehow, the files_sharing app is excluded from the "big preload" here: https://github.com/owncloud/core/blob/stable8.2/lib/private/appconfig.php#L286.

Also see the comment above: https://github.com/owncloud/core/blob/stable8.2/lib/private/appconfig.php#L277.

So in the best case there is nothing to do and updating to 8.2 should already solve the issue.

**Comment by jvillafanez** [comment]
> Apparently this is not directly reusable for 8.2 because 8.2 seems to preload all config keys in memory first before giving access to them.

😭 

From my point of view we'll have to reimplement that class. Loading the whole table doesn't look good:
* If I ask for one specific entry, I expect only that one entry. Fetching everything isn't good because I'm only interested in that specific value.
* The same for app values. I'm interested only in my app not in any other apps.
* There isn't anything to prevent an app from storing everything in the appconfig table. This means that every app will be affected by this "rogue" app with millions of things stored there.

**Comment by PVince81** [comment]
Hmm, I thought these values would be cached in memcache but I can't see the code there for that.

`loadConfigValues` also exists in OC 9.0: https://github.com/owncloud/core/blob/stable9/lib/private/appconfig.php#L267 and 9.1: https://github.com/owncloud/core/blob/stable9.1/lib/private/AppConfig.php#L267

Do you remember where the memcache magic was supposed to happen ?
Or was it something different ? (maybe it was the apps list from the apps page)

**Comment by PVince81** [comment]
Ref, the PR that introduced `loadConfigValues`: https://github.com/owncloud/core/pull/18799. It seems to be able to reduce the number of queries because in practice more than one values is read within a given PHP request.

**Comment by butonic** [comment]
Ok, the fuckup was cased by someone thinking that storing the timestamp a share was last propagated in this table was a good idea which of course creates this very performance problem when we added an 'optimization' that would simply fetch the whole appconfig table as during a request it was highly likely that we had to query nearly all rows anyway. But ... someone forgot that in old installations these sharing timestamps were added ... causing a huge headache for large installations that now fetch the whole table. 

In any case the files_sharing entries can be deleted in OC9 (there is [a repair step](https://github.com/owncloud/core/blob/stable9/lib/private/repair/sharepropagation.php) for it which is executed during migration). You can speed it up if you use plain sql to delete them.

So in 9.0 the issue is gone. And @PVince81 is correct that 8.2 filters the unneeded files_sharing rows. For 8.1, not loading all rows, as added with this PR definitely makes sense. But as @PVince81 pointed out 8.1 is EOL, so ... closing.

**Pull request closed without merging**
