### PR TITLE
[stable8.1] Use name of ICollection for exception message

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #21232 to stable8.2

Approval in https://github.com/owncloud/core/pull/21232#issuecomment-165137396

cc @icewind1991 @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by rullzer** [comment]
Also works. :+1: 
But same here. Please rebase so we can see if testing goes OK

**Comment by MorrisJobke** [comment]
> But same here. Please rebase so we can see if testing goes OK

These tests always fail on stable8.1

**Comment by LukasReschke** [comment]
No. This exploded hard https://github.com/owncloud/core/issues/21339

**Pull request merged**
