### PR TITLE
enhance sqlite warning on admin page as well as during setup

### LINKED ISSUE #13906: Enhance sqlite warning in admin section and during setup
Admin page:
bildschirmfoto von 2015-02-04 20 41 30

Setup page:
bildschirmfoto von 2015-02-04 20 48 28

@karlitschek please review the proposed text - THX

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #13906

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by karlitschek** [comment]
I don´t think we want to discharge sqlite for desktop clients at all. I would say something like. "more than 3 clients in parallel". Beside that :+1:

**Comment by DeepDiver1975** [comment]
Hmm 3 client performing up to 3 parallel requests makes it 9 requests in total queueing up. I fear this will already give bad user experience. 

@dragotin we do up to 3 requests in parallel - right?

**Comment by RealRancor** [comment]
> Hmm 3 client performing up to 3 parallel requests makes it 9 requests in total queueing up. I fear this will already give bad user experience. 

Have also written this in the linked issues. There are user reports where one single client has caused "database locked" messages on sqlite.

**Comment by dragotin** [comment]
Yes, that is purely statistically. More users/interactions etc. just make it more likely to happen.

**Comment by Raydiation** [comment]
:+1:

**Pull request merged**
