### PR TITLE
[9.2] Sync deathdate and anniversary to birthday calendar 

### PR DESCRIPTION
**Pull request by DeepDiver1975**
In addition to the birthday also deathdate and anniversary are synced to the calendar

bildschirmfoto von 2016-07-29 16-16-09
bildschirmfoto von 2016-07-29 16-15-38

### CODE REVIEW

**Comment by PVince81** [comment]
```
20:59:25 1) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testBuildBirthdayFromContact with data set #0 (true, null)
20:59:25 Missing argument 2 for OCA\DAV\CalDAV\BirthdayService::buildDateFromContact(), called in /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php on line 60 and defined
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:115
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:60
20:59:25 
20:59:25 2) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testBuildBirthdayFromContact with data set #1 (true, '')
20:59:25 Missing argument 2 for OCA\DAV\CalDAV\BirthdayService::buildDateFromContact(), called in /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php on line 60 and defined
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:115
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:60
20:59:25 
20:59:25 3) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testBuildBirthdayFromContact with data set #2 (true, 'yasfewf')
20:59:25 Missing argument 2 for OCA\DAV\CalDAV\BirthdayService::buildDateFromContact(), called in /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php on line 60 and defined
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:115
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:60
20:59:25 
20:59:25 4) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testBuildBirthdayFromContact with data set #3 (true, 'BEGIN:VCARD\nVERSION:3.0\nPRODI...VCARD\n', 'Dr. Foo Bar')
20:59:25 Missing argument 2 for OCA\DAV\CalDAV\BirthdayService::buildDateFromContact(), called in /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php on line 60 and defined
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:115
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:60
20:59:25 
20:59:25 5) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testBuildBirthdayFromContact with data set #4 (true, 'BEGIN:VCARD\nVERSION:3.0\nPRODI...VCARD\n', 'Dr. Foo Bar')
20:59:25 Missing argument 2 for OCA\DAV\CalDAV\BirthdayService::buildDateFromContact(), called in /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php on line 60 and defined
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:115
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:60
20:59:25 
20:59:25 6) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testBuildBirthdayFromContact with data set #5 (true, 'BEGIN:VCARD\nVERSION:3.0\nPRODI...VCARD\n', 'Dr. Foo Bar')
20:59:25 Missing argument 2 for OCA\DAV\CalDAV\BirthdayService::buildDateFromContact(), called in /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php on line 60 and defined
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:115
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:60
20:59:25 
20:59:25 7) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testBuildBirthdayFromContact with data set #6 (false, 'BEGIN:VCARD\nVERSION:3.0\nPRODI...VCARD\n', 'Dr. Foo Bar')
20:59:25 Missing argument 2 for OCA\DAV\CalDAV\BirthdayService::buildDateFromContact(), called in /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php on line 60 and defined
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:115
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:60
20:59:25 
20:59:25 --
20:59:25 
20:59:25 There were 4 failures:
20:59:25 
20:59:25 1) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testOnCardDeleted
20:59:25 OCA\DAV\CalDAV\CalDavBackend::deleteCalendarObject(1234, 'default-gump.vcf.ics-death') was not expected to be called more than once.
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:86
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:87
20:59:25 
20:59:25 2) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testOnCardChanged with data set #0 ('delete')
20:59:25 OCA\DAV\CalDAV\CalDavBackend::getCalendarObject(1234, 'default-gump.vcf-death.ics') was not expected to be called more than once.
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:232
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:69
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:128
20:59:25 
20:59:25 3) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testOnCardChanged with data set #1 ('create')
20:59:25 Expectation failed for method name is equal to <string:createCalendarObject> when invoked 1 time(s).
20:59:25 Method was expected to be called 1 times, actually called 0 times.
20:59:25 
20:59:25 4) OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testOnCardChanged with data set #2 ('update')
20:59:25 OCA\DAV\CalDAV\CalDavBackend::getCalendarObject(1234, 'default-gump.vcf-death.ics') was not expected to be called more than once.
20:59:25 
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:232
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/lib/CalDAV/BirthdayService.php:69
20:59:25 /var/lib/jenkins/workspace/owncloud-core/core/PR-25655/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:128
```

**Comment by DeepDiver1975** [comment]
Needs rebase

**Comment by butonic** [comment]
rename BirthdayService.php to ContactsService because it is no longer about Birthdates only?

**Comment by butonic** [comment]
👍

**Pull request merged**
