### PR TITLE
[stable10] make it possible to use the --remote option without additional argument

### PR DESCRIPTION
**Pull request by individual-it**
backport of #29776 to stable10

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@DeepDiver1975 or @PVince81 this is another UI tests code change only. CI is stuck because of the docker troubles. Can you merge anyway?

**Comment by individual-it** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase was successful!

**Pull request merged**
