### PR TITLE
also add icons for other external storages

### PR DESCRIPTION
**Pull request by jancborchardt**
@DeepDiver1975 @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 instead of hardcoding this in core, another solution would be to give the `<a>` element of the wnd and spmounts the class `.nav-icon-extstoragemounts`. Then it will just pick up the existing code.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 instead of hardcoding this in core, another solution would be to give the <a> element of the wnd and spmounts the class .nav-icon-extstoragemounts. Then it will just pick up the existing code.

I prefer this approach - can you open two PRs for this please? THX

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 instead of hardcoding this in core, another solution would be to give the element of the wnd and spmounts the class .nav-icon-extstoragemounts. Then it will just pick up the existing code.

This isn't easy, because this is autogenerated from the app ID. I would suggest to add this rule to the corresponding apps.

**Comment by jancborchardt** [comment]
@MorrisJobke @DeepDiver1975 can one of you do this then? I have no idea how to make that work, probably requires some PHP or JS hackery.

**Comment by MorrisJobke** [comment]
@jancborchardt I will give this a try ;)

**Comment by DeepDiver1975** [comment]
THX @MorrisJobke

**Pull request closed without merging**
