### PR TITLE
Fix cache update when doing a rename that overwrites the target

### LINKED ISSUE #14559: Version dropdown not removed after restoring a file
### Steps to reproduce

1. Install owncloud 
2. upload or create a text file
3. edit the file a couple of time so that there are a few versions
4. click on the version link for the file
5. select one of the version and click the restore link

### Expected behaviour

The file is restored and the version dropdown goes away

### Actual behaviour

The file is restored but the version dropdown remains.  This makes it seem that the restore didn't happen so I end up clicking it multiple times getting an error message that the file can't be restored because I'm trying to restore a file that has already been restored.

This is a regression from 7.

p295

### Server Host info:

CentOS release 6.6 (Final)
PHP 5.4.36

### Server configuration

ownCloud Enterprise Edition 8.0 (daily) Build:2015-02-26T05:30:39+00:00 bc1418156339d4e61fe81bd1474f91555432ca00

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #14559

@jnfrmarks can you verify that this fixes the problem for you?

cc @DeepDiver1975 @PVince81 @LukasReschke

### CODE REVIEW

**Comment by karlitschek** [comment]
@jnfrmarks Can you verify?

**Comment by DeepDiver1975** [comment]
adding backport-request because of #14559

@icewind1991 please prepare PR against stable8 - THX

**Comment by LukasReschke** [comment]
Would it be possible to add an unit test? – I mean we should be able to detect if a SQL error happened – right?

**Comment by DeepDiver1975** [comment]
> Would it be possible to add an unit test? – I mean we should be able to detect if a SQL error happened – right?

truestory

**Comment by karlitschek** [comment]
backport would be great

**Comment by icewind1991** [comment]
Added test

**Comment by PVince81** [comment]
Works, code makes sense :+1:

**Comment by MorrisJobke** [comment]
Fixes the issue - tested :+1:

**Comment by MorrisJobke** [comment]
@icewind1991 Can you create the backport PR? Thanks

**Comment by icewind1991** [comment]
stable8: https://github.com/owncloud/core/pull/14584

**Pull request merged**
