### PR TITLE
Check if archive contains a directory named like appid

### PR DESCRIPTION
**Pull request by michag86**
Small change to check if the archive contains a folder named like the app id for issue #18116

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
thx a lot :+1: 

@karlitschek backport should be considered since the issue of wrong formated archives can hin any release.

**Comment by michag86** [comment]
I've added "OC_Helper::rmdirr($basedir);" to clean up
otherwise "App directory already exists" error occurs on next try

**Comment by karlitschek** [comment]
Agreed. :+1:   please backport

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
:hankey: the code is anyhow not tested -> merge

**Comment by DeepDiver1975** [comment]
@michag86 can I ask you to create PRs for stable8.1, stable8 and stable7 - THX

**Comment by DeepDiver1975** [comment]
:faceplam: did I close the PR? Stupid me - wrong button! :imp:

**Pull request merged**
