### PR TITLE
Verify the path is a file on avatar update

### LINKED ISSUE #21533: An error 500 is shown if you do not select any file changing the profile image
### Steps to reproduce

1. Go to personal settings page
2. In Profile picture section, click on 'Select from files button'
3. Click on choose button without choosing any file

### Expected behaviour

The 'choose an image window' should be closed without performing any action

### Actual behaviour

An error 500 is shown

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:  ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-01-07T04:44:34+00:00 d3922510d01fb5feed3ea01a3d390dfaa8b1312f

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

screen shot 2016-01-08 at 08 54 35

```
{"reqId":"sRz3Nl5twTSwAFfMqIaz","remoteAddr":"82.159.139.58","app":"PHP","message":"Call to undefined method OC\\Files\\Node\\Folder::getContent() at \/opt\/owncloud\/core\/avatar\/avatarcontroller.php#170","level":3,"time":"2016-01-08T07:54:25+00:00"}
```

### PR DESCRIPTION
**Pull request by rullzer**
Fixes #21533

Before we just assumed that the passed path was a file. This does not
have to be the case. Thus check if it actually is a file before doing
any more tests.

Added a unit test.

Please verify @davitol 

CC: @PVince81 @nickvergessen @MorrisJobke

### CODE REVIEW

**Comment by davitol** [comment]
:+1: But as it was commented in https://github.com/owncloud/core/issues/21533#issuecomment-169939079 the error bar looks too big
screen shot 2016-01-08 at 10 17 20
@jancborchardt

**Comment by rullzer** [comment]
@davitol yeah that is a left over from the old layout. But different bug ;)

**Comment by MorrisJobke** [comment]
> But as it was commented in #21533 (comment) the error bar looks too big

I fixed it and pushed the commit.

Tested the issue and the problem is gone :+1: for this PR.

**Comment by rullzer** [comment]
CSS fix is simple enough :+1:

**Comment by davitol** [comment]
:+1: to CSS fix

**Comment by jancborchardt** [comment]
Ah thanks @MorrisJobke for fixing the width.

Still, the error message itself is not really helpful. How can we improve that – what is the actual error?

**Comment by MorrisJobke** [comment]
> How can we improve that – what is the actual error?

No file is selected in the file chooser

**Comment by jancborchardt** [comment]
Then the »Choose« button should be disabled. This error should essentially never need to be shown as we need to catch it elsewhere.

**Pull request merged**
