### PR TITLE
Handle case when breadcrumb and filelist item overlap and both receive a drop

### PR DESCRIPTION
**Pull request by MorrisJobke**
- ref #20294 
- solves #20161
- includes the fix of https://github.com/owncloud/core/pull/20294#issuecomment-183227797

@PVince81 @nickvergessen @pellaeon @DeepDiver1975 @jancborchardt Please review

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I tested this and it works here :+1: (because most of this was done by @pellaeon ;))

**Comment by pellaeon** [comment]
@MorrisJobke 's line will break on Firefox 43, both td and breadcrumb will receive a drop event, not sure why, but it works on Chrome 48.

BTW, in Chrome, dragging an item over breadcrumb doesn't make file list folder tds fade out.

**Comment by MorrisJobke** [comment]
@pellaeon This works for me in Safari, Chrome and Firefox. Also the highlight is visible in all 3 of them, but only when I hover over the house icon or the parent folder - the last entry in the breadcrumbs doesn't trigger the highlight change.

**Comment by pellaeon** [comment]
I still haven't figure this out, you can see 2 requests being made. And I was wrong about chrome, it also have this problem, after I cleared browser cache.

Adding `console.log()` to apps/files/js/files.js#L412 and apps/files/js/filelist.js#L760, I found that the folder td still receives drop.

Any ideas?

**Comment by pellaeon** [comment]
@MorrisJobke I'm still not sure why you can't reproduce it. I added a commit that waits 10ms before re-enabling drop, this solves my problem.

**Comment by MorrisJobke** [comment]
I rebased this, squashed and tested the change.

Everything works as it should in IE11, Firefox, Chrome and Safari :+1: 

@PVince81 @LukasReschke @nickvergessen @rullzer @Xenopathic Please review

**Comment by PVince81** [comment]
Tested, works :+1: 

The breadcrumb has higher priority.

**Pull request merged**
