### PR TITLE
[WIP] Only show the storage full warning when the folder is writable

### PR DESCRIPTION
**Pull request by icewind1991**
In read-only folders this message this message only adds clutter since nothing can be uploaded anyway

Can be tested with owncloud/apps#1756

cc @DeepDiver1975 @PVince81 @jancborchardt

### CODE REVIEW

**Comment by PVince81** [comment]
@icewind1991 wanna continue this ?

**Comment by MorrisJobke** [comment]
@icewind1991 We will close this in 5 days. ;)

**Comment by DeepDiver1975** [comment]
@icewind1991 still valid? rebase please in case - THX

**Comment by icewind1991** [comment]
Dont think this is still valid

**Pull request closed without merging**
