### PR TITLE
[9.2] Update some more libs

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

Update some dependencies
## Related Issue

https://github.com/owncloud/core/issues/20787
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Should https://github.com/owncloud/core/blob/0a1ec3c7e80cde02de69c7ccf09cbe6776feb721/composer.json#L24 be "phpseclib/phpseclib": "2.0.2" ? like said in https://github.com/owncloud/core/pull/25339

**Comment by PVince81** [comment]
@SergioBertolinSG no, because it breaks our signing... Until we have a solution for this we can't update it...

**Comment by PVince81** [comment]
@DeepDiver1975 I took the liberty to also add the davclient.js version to 0.0.1 since we now tagged it. Looks better than a commit id.

**Comment by PVince81** [comment]
@DeepDiver1975 looks like the update makes some tests unhappy:
```
Test\Command\AsyncBusTest::testClosureSelf
Error: Cannot access self:: when no class scope is active
```

all these:
```
    Test\Command\AsyncBusTest.testClosureSelf
    Test\Command\AsyncBusTest.testClosureBind
    Tests\Core\Command\Config\App\GetConfigTest::testGet.testGet with data set #2
    Tests\Core\Command\Config\System\GetConfigTest::testGet.testGet with data set #2
    Tests\Core\Command\Config\System\GetConfigTest::testGet.testGet with data set #22
    Tests\Core\Command\User\SettingTest::testCheckInput.testCheckInput with data set #3
    Tests\Core\Command\User\SettingTest::testCheckInput.testCheckInput with data set #5
    Tests\Core\Command\User\SettingTest::testCheckInput.testCheckInput with data set #6
    Tests\Core\Command\User\SettingTest::testCheckInput.testCheckInput with data set #7
    Tests\Core\Command\User\SettingTest::testCheckInput.testCheckInput with data set #11
    Tests\Core\Command\User\SettingTest::testCheckInput.testCheckInput with data set #12
    Tests\Core\Command\User\SettingTest::testExecuteDelete.testExecuteDelete with data set #0
    Tests\Core\Command\User\SettingTest::testExecuteDelete.testExecuteDelete with data set #1
    Tests\Core\Command\User\SettingTest::testExecuteDelete.testExecuteDelete with data set #2
    Tests\Core\Command\User\SettingTest::testExecuteSet.testExecuteSet with data set #0
    Tests\Core\Command\User\SettingTest::testExecuteSet.testExecuteSet with data set #1
    Tests\Core\Command\User\SettingTest::testExecuteSet.testExecuteSet with data set #2
    Tests\Core\Command\User\SettingTest::testExecuteGet.testExecuteGet with data set #1
```

**Comment by DeepDiver1975** [comment]
Will Work on failing Tests

**Comment by DeepDiver1975** [comment]
Jenkins is green on this one @PVince81 @VicDeo @butonic merge?

**Comment by PVince81** [comment]
:+1: let's hope the version eyes will be happy now

**Pull request merged**
