### PR TITLE
Make it possible to filter by tags with REPORT method

### LINKED ISSUE #23263: Add oc:favorite to REPORT call for searching for favorites
The "Favorites" section in the files app is still using an internal API.

Since 9.0 we have a new REPORT Webdav call that is able to return filtered results.

This ticket is about extending the REPORT request:
- accept a "oc:favorite" filter criteria to specify that we want only favorites or only non-favorites (0 or 1)
- return a list of filtered results
- change the web UI to use that Webdav call

### PR DESCRIPTION
**Pull request by PVince81**
## Description

Enhanced the REPORT method on the Webdav endpoint and added a
"oc:favorite" filter rule. When set, it will return a flat list of
results filtered with only favorite files.

The web UI was also adjusted to use this REPORT method instead of the
private API endpoint.
## Related Issue

Fixes https://github.com/owncloud/core/issues/23263
## Motivation and Context

This makes it possible for other clients like desktop and mobile to retrieve a flat filtered list of favorite files. The previous API was private and was not supposed to be used, but the REPORT method and the webdav endpoint are public. @davivel @nasli @dragotin @guruz 
## How Has This Been Tested?
1. Favorite a few files in folders and subfolders, share one of them with link (for the share indicator). 
2. Go to the "Favorites" section in the web UI. 
3. Check the network console and see that it's using REPORT to get the results.
4. Check that the displayed results look fine and also contain the share indicator from the previous link share (it's part of the Webdav response)
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Please review @DeepDiver1975 @butonic @VicDeo @guruz @davivel @SergioBertolinSG @nasli

### CODE REVIEW

**Comment by PVince81** [comment]
I just saw that we can actually have different report types using the report name.

The report here was called "filter-files". The question maybe is whether we want to separate all these into separate reports:
- filter-systemtags
- filter-favorites
- get-files (for pagination)
- search-files ?

**Comment by PVince81** [comment]
The advantage of a single "filter-files" report is that you can combine filters and intersect results, but it also increases complexity because of this.

**Comment by VicDeo** [comment]
@PVince81 
is it ok, that a response has several dummy parts like that in addition to the file list itself?
```
  <d:propstat>
   <d:prop>
    <oc:size/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
```
If yes, consider my comment for :+1:

**Comment by PVince81** [comment]
@VicDeo yes, this happens when requesting a property that doesn't exist on all nodes.
The "oc:size" property only exists on folders, not files. So the file entries will tell so in the 404 block.
This is a standard PROPFIND response.

**Comment by PVince81** [comment]
@DeepDiver1975 @butonic do we agree on the API-side of this ? Basically use multiple filters within the same report "filter-files".

**Comment by butonic** [comment]
basically the report tesult is a list of files. What we want to change are the filter criteria, eg. by favorite, tag, mtime range, file name, file content ...

so yes, keep a single filter-files report.

**Comment by PVince81** [comment]
Thanks, merging.

Pagination as it was mentionned is a topic for another time, see https://github.com/owncloud/core/issues/13915.

**Pull request merged**
