### PR TITLE
Move OC_Archive to \OC\Archive and PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @nickvergessen @DeepDiver1975 @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by DeepDiver1975** [comment]
I guess we can fix the naming of the class right away - both classes should only be used internally

**Comment by rullzer** [comment]
@DeepDiver1975 ok let me fix it directly then :)

**Comment by nickvergessen** [comment]
Also for me legacy always ment "we have a new replacement for that already, we just keep it because of BC" which does not apply to the moves you did lately

**Comment by rullzer** [comment]
Updated PR.
Please review.

**Comment by MorrisJobke** [comment]
Still 👍

**Comment by LukasReschke** [comment]
👍

**Pull request merged**
