### PR TITLE
FIX for webdav.mediencenter.t-online.de

### PR DESCRIPTION
**Pull request by OliverKohl**
https://webdav.mediencenter.t-online.de returns invalid response code.

e.g.
{"reqId":"f9a1c394b98108e4e5ca62bf47829c64","remoteAddr":"81.189.45.224","app":"PHP","message":"Undefined offset: 2 at \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Client.php#569","level":3,"time":"2015-03-25T18:25:48+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=External%2FT-Cloud%2FTests"}

e.g.
{"reqId":"3407d66672b3cef206b0af883e49bff4","remoteAddr":"46.74.125.245","app":"PHP","message":"Undefined index: {DAV:}getlastmodified at \/var\/www\/owncloud\/lib\/private\/files\/storage\/dav.php#563","level":3,"time":"2015-03-25T16:33:21+00:00"}

### CODE REVIEW

**Comment by karlitschek** [comment]
@OliverKohlDSc The ownCloud development policy is that every pull request needs to be reviewed and approved by at least two other people before it is merged. please revert this immediately.

**Comment by karlitschek** [comment]
@DeepDiver1975 fyi

**Comment by MorrisJobke** [comment]
@karlitschek Done: https://github.com/owncloud/core/pull/15203

**Comment by MorrisJobke** [comment]
@icewind1991 @PVince81 @DeepDiver1975 Does it make sense to bring this in master again?

**Comment by icewind1991** [comment]
Yes

**Comment by MorrisJobke** [comment]
@icewind1991 feel free to do it :)

**Comment by OliverKohlDSc** [comment]
@icewind1991 @PVince81 @DeepDiver1975 Have you brought it to master back again?

**Comment by PVince81** [comment]
@OliverKohlDSc can you resubmit it ?

**Comment by OliverKohlDSc** [comment]
@PVince81: Pull request for the recommit to the master has been created here:
https://github.com/owncloud/core/pull/16562

**Comment by OliverKohlDSc** [comment]
done

**Pull request merged**
