### PR TITLE
Suggest to include php_flag display_errors in .htaccess

### PR DESCRIPTION
**Pull request by jnweiger**
so that users know how to make error messages visible. 
Maybe even default, to make them visible?

### CODE REVIEW

**Comment by karlitschek** [comment]
this is a setting that is usually turned off on production systems and turned on development systems and maybe staging systems. If we explicitly set and override this in owncloud then this might get harder. So not sure about this change.

**Comment by DeepDiver1975** [comment]
I have also a bad feeling about this change - this php setting was great back in the days pure html was rendered - but as of today where our php code returns various response types (json/xml) this might have bad impact - imagine errors being printed to a file download.

This for sure required more in depth testing ... honestly for which benefit - errors are written to the log

**Comment by DeepDiver1975** [comment]
http://stackoverflow.com/questions/12872515/php-warning-demolishes-json-response

**Comment by jnweiger** [comment]
I agree, it is bad for enterprise installations. I actually thought of isv:owncloud:communtiy releases. maybe better suited for :testing ... and :nightly then...

**Comment by karlitschek** [comment]
I definitely wouldn´t do anything special in community releases or testing releases compared with enterprise releases. This just created problems and confusion in the future. Let´s leave it as it. But thanks for the creative thinking.

**Comment by DeepDiver1975** [comment]
@jnweiger thanks for bringing this up - basically enabling this setting can break installations @LukasReschke another check to be disabled/warned about? THX

**Comment by LukasReschke** [comment]
> @LukasReschke another check to be disabled/warned about? THX

That would indeed make sense. – There are also quite some other PHP configuration settings that should for multiple reasons, mostly security, be changed from some defaults. Let me see how we can address this the best way.

Maybe a "Secure Deployment" app? – I personally don't mind adding everything to the setup checks but @karlitschek has a different opinion on that considering the recent warnings that I had to change again in Nuremberg ;-)

**Comment by LukasReschke** [comment]
(that said this one can go into the setup check probably as it actually might break stuff)

**Comment by karlitschek** [comment]
@LukasReschke Well we should check for all the important things that are real security problems. Something that is more in the area of best practices could be in the documentation or in such a "turning" app you described. But we shouldn´t flood the admin section with techno-bubble that most users don´t understand unless the instance is really insecure. IMHO.

**Comment by DeepDiver1975** [comment]
well - besides security there is the field of data corruption. This has identical criticaliy from my pov.

**Comment by karlitschek** [comment]
Hmm. Isn´t this only a theoretical problem?
ownCloud shouldn´t trigger error messages in the first place?
Or what is the exact example where this can happen?

**Comment by DeepDiver1975** [comment]
> Hmm. Isn´t this only a theoretical problem?

no



> ownCloud shouldn´t trigger error messages in the first place?

yes - should - but shit happens as we know.
So even in case error messages are triggered - we shall not corrupt data



> Or what is the exact example where this can happen?

A very basic example is described here: http://stackoverflow.com/questions/12872515/php-warning-demolishes-json-response

same applies to webdav requests and this is corrupting data - yes should not happen - but thinking about the BOM fuckup we had: safety first

**Comment by karlitschek** [comment]
Sure. I know. But do we have a concrete example in ownCloud?

**Comment by DeepDiver1975** [comment]
> Sure. I know. But do we have a concrete example in ownCloud?

let's wast time on this after the freeze - will for sure not take much longer then a few minutes - but still .... time is critical

**Comment by karlitschek** [comment]
@DeepDiver1975 agreed :-)

**Comment by MorrisJobke** [comment]
This is superseeded by #16050

**Pull request closed without merging**
