### PR TITLE
Kill more legacy classes

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
fuxx you

**Comment by DeepDiver1975** [comment]
@karlitschek @PVince81 @icewind1991 @schiesbn please review - THX

**Comment by PVince81** [comment]
Rebase please. (wow)

**Comment by PVince81** [comment]
Looks good :+1:

**Comment by PVince81** [comment]
@nickvergessen @MorrisJobke

**Comment by MorrisJobke** [comment]
I checked the code, did an upgrade, did a setup, tested upload, download via WebUI and Webdav, clicked around and did some basic smoke tests. All looks good :+1: Let's get this in, before it get's outdated.

**Comment by karlitschek** [comment]
:+1: great

**Comment by DeepDiver1975** [comment]
Some apps require adjustment. I will take care step by step.

**Pull request merged**
