### PR TITLE
[8.2] Activity oracle sql error for favorites

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport #20487

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport. thanks for the fix

**Comment by nickvergessen** [comment]
@cmonteroluque 8.2.2 as discussed?

**Comment by cmonteroluque** [comment]
@nickvergessen probably, I am asking GCX on the https://github.com/owncloud/enterprise/issues/908 issue if that works for them

**Comment by PVince81** [comment]
OCI test passed, good sign ?

**Comment by DeepDiver1975** [comment]
> OCI test passed, good sign ?

no - as far as I can tell the query never hits the database @nickvergessen am I right?

**Comment by nickvergessen** [comment]
> no - as far as I can tell the query never hits the database @nickvergessen am I right?

Yes, but let me add a unit test that runs an equivalent query against an existing table

**Comment by DeepDiver1975** [comment]
> Yes, but let me add a unit test that runs an equivalent query against an existing table

do I need to say that I consider this sql parts very spooky :ghost:

**Comment by nickvergessen** [comment]
> do I need to say that I consider this sql parts very spooky :ghost:

No, don't like them to be in the public API either, but well it was added back then. None of the known filters (apart from the files app favorites) uses it anyway.

**Comment by MorrisJobke** [comment]
I tested activity with favorites and it works :+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Please review

**Comment by nickvergessen** [comment]
Just as a note: the backports only have 2 commits, because the other 3 are related to new functionality in 9.0

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
