### PR TITLE
Highlight files after setFiles

### LINKED ISSUE #28106: Permalink to files in subfolders doesn't point to the file.
### Steps to reproduce

1. Create a folder 'FOLDER'. 
2. Upload a file 'file.txt' to 'FOLDER'.
3. Copy permalink of the file (chain icon in the sidebar).
4. Open the copied link in a new window/tab.

### Expected behaviour
It should open 'file.txt' folder, showing it selected. (maybe with the sidebar open? cc @pmaier1 )

### Actual behaviour
It opens the folder 'FOLDER'. The permalink points to that folder. File 'file.txt' is not selected.

This affects mobile development (cc @nasli).

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Firefox

**Logs**
```
```

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Call file highlighting *after* files are redered to view

## Related Issue

Fixes https://github.com/owncloud/core/issues/28106

## How Has This Been Tested?

Visual test in FF; Chrome, IE11 and MS Edge

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
This will likely re-highlight the file again every time the file list is reloaded, when navigating between folders.

I suggest setting `_scrollTo` to null as soon as the event has run.

**Comment by felixheidecke** [comment]
> This will likely re-highlight the file again every time the file list is reloaded when navigating between folders.

That's true. I thought `.one(…` should do the trick but it doesn't :-P

**Review by PVince81 — APPROVED** [review]
:+1:

Please backport to stable10

**Comment by felixheidecke** [comment]
> Please backport to stable10

Never done this before. Whats the workflow?

**Comment by DeepDiver1975** [comment]
> Never done this before. Whats the workflow?

https://gist.github.com/DeepDiver1975/33cde0c03f0c321132ca517cc5fbd580

**Comment by DeepDiver1975** [comment]
but first squash these commits together - THX

**Comment by phil-davis** [comment]
@DeepDiver1975 has his own magic script, but the process is:
- find the commit-id SHA in the list of commits in master (after the main PR to master has been squash-merged...) - there is a button to "Copy the full SHA" which is easy
```
git checkout stable10
git checkout -b stable10-fh_fix_permalink
git cherry-pick <commit-id>
git push
```
then go to GitHub make a PR from that branch, making sure to select stable10 as the to which to make the PR to.

**Comment by felixheidecke** [comment]
@PVince81 backport: https://github.com/owncloud/core/pull/28681

**Pull request merged**
