### PR TITLE
Fix global app list state

### LINKED ISSUE #17344: 8.1rc2 js error if a app gets disabled on settings/apps
TestEnviro:
8.1rc2

Step to reproduce:
1. goto settings apps
2. goto enabled tab
3. click on app to disable

Expected result
No errors

Actual result 
js error
```
TypeError: OC.Settings.Apps.State.apps[appId] is undefined apps.js:231:5
```

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/17344

@DeepDiver1975 @icewind1991 @MorrisJobke @LukasReschke @libasys

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Verified the bug, tested this and it works :+1:

**Comment by PVince81** [comment]
and a unit test to make sure it doesn't happen again: https://github.com/owncloud/core/commit/d5b7e40c1906494699c6c29b082636132744f095

would be nice to add unit tests for the other apps.js code as well at some point

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Jenkins PR https://github.com/owncloud/core/pull/17354

**Comment by PVince81** [comment]
@karlitschek backport to stable8.1 once merged ?

**Comment by PVince81** [comment]
Backport PR here https://github.com/owncloud/core/pull/17356

Looks like Jenkins isn't happy either about the hot weather.

**Comment by karlitschek** [comment]
yes. should be safe. please backport :+1:

**Comment by MorrisJobke** [comment]
@PVince81 Please create the backport PR :)

**Comment by PVince81** [comment]
@MorrisJobke it was already done, see https://github.com/owncloud/core/pull/17356

**Pull request merged**
