### PR TITLE
compress icons in navigation, move to monochrome again

### PR DESCRIPTION
**Pull request by jancborchardt**
While compressing some icons I also came to agree with @PVince81 as he said in https://github.com/owncloud/core/pull/18621#issuecomment-135729677 that the sidebar color icons are a bit too flashy.

So, compressed and also monochrome again now. Please review @owncloud/designers @PVince81 @MorrisJobke @nickvergessen

### CODE REVIEW

**Comment by tomneedham** [comment]
:+1:

**Comment by PVince81** [comment]
:+1:

CSS + image changes only => merge

**Comment by MorrisJobke** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
