### PR TITLE
Fix password reset confirmation email from occ

### LINKED ISSUE #33384: Password reset confirmation email is not sent on occ command user:resetpassword
# Description
When the `administrator` resets the password of a user using the occ command with environment variable `OC_PASS` and set `--sent-email`. 
`sudo -E -u www-data ./occ user:resetpassword newuser --send-email --password-from-env`
As expected the password of the user is changed but the email is not sent to the user saying his/her email has been changed. 

Is this the expected behavior? 
@phil-davis, @individual-it

### PR DESCRIPTION
**Pull request by sharidas**
Fix password reset confirmation email from occ.
This was missing when user:resetpassword command
was used with options "--send-email --password-from-env".
With this change set the issue is resolved.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

When password for user is set using command `user:resetpassword`, with options `--send-email --password-from-env` ( apart from username ) , the password successful email is not sent. This is a minor issue though. In this PR an extra condition is added, so that password setting logic is routed to LostController's `setPassword`, if `--send-email` is used along with the option `password-from-env`. Care has also been taken to evaluate the return from LostControllers `setPassword()` method.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/33384

## Motivation and Context

An email will be triggered if the password change has been made for the user with the options ``--send-email --password-from-env` passed to command `user:resetpassword`.

## How Has This Been Tested?

- Create `user1` user
- Execute the command below:
```
sujith@sujith-ownCloud  ~/test/owncloud3   master ●  ./occ user:resetpassword user1 --send-email --password-from-env
Cannot load Xdebug - it was already loaded
Successfully reset password for user1
 sujith@sujith-ownCloud  ~/test/owncloud3   master ● 
```
- Verified that email is sent when the password is changed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
@sharidas I discovered that the acceptance test for this issue was not really demonstrating the issue.
I corrected the acceptance test in PR #34139 
After that is merged, the acceptance test will then be demonstrating the wrong behavior described in the issue.
Then this PR will need to correct the acceptance test, as well as fixing the issue.

**Review by phil-davis — COMMENTED** [review]
Adjusted acceptance test passes, so that is "a good thing"

**Comment by sharidas** [comment]
Current state of the PR:
- Verified the issue using this PR. And it resolves the issue.
- Have cherry-picked one of the commits of @phil-davis for this fix.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@sharidas please backport

**Comment by sharidas** [comment]
Original PR https://github.com/owncloud/core/pull/34154

**Pull request merged**
