### PR TITLE
[stable10] move testing app to dedicated repository

### PR DESCRIPTION
**Pull request by patrickjahns**
Backport of #32397 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
What happened to make conflicts with the ``apiSkeleton`` files that were added to the testing app last week?

**Comment by patrickjahns** [comment]
> What happened to make conflicts with the apiSkeleton files that were added to the testing app last week?

What do you mean by that?

**Comment by phil-davis** [comment]
When I made the comment, GitHub was showing conflicts for ``data/apiSkeleton`` files.
Now GitHub is happy, so I have no idea what was happening.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
```
  App "QA testing" cannot be installed because the following dependencies are  
not fulfilled: ownCloud 10.1 or higher is required.
```
https://drone.owncloud.com/owncloud/core/9631/81

**Pull request merged**
