### PR TITLE
[master] Fix mail debug message recipient field

### PR DESCRIPTION
**Pull request by PVince81**
Master port of https://github.com/owncloud/core/pull/31227

### CODE REVIEW

**Comment by PVince81** [comment]
fixed phpcs stuff

**Comment by PVince81** [comment]
@DeepDiver1975 quick review of this port ?

**Comment by PVince81** [comment]
rebased

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
added more php cs fixes

**Review by VicDeo — APPROVED** [review]
Looks good

**Pull request merged**
