### PR TITLE
Delete last undoable user before user creation

### LINKED ISSUE #13589: [User Management] User is not created if it was first created and deleted
### Steps to reproduce

1. Go to users
2. Activate send to email address to new users.
3. Write down user/password
4. Click create new user.
5. Delete the new user just created
6. Create again a user with the same info as the previous one

### Expected behaviour
User should be created and mail sent.

### Actual behaviour

User does not appear in the list but the email is sent. If the browser is refreshed after the deletion, it works ok.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome, Firefox

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/13589

Please review @LukasReschke @MorrisJobke @blizzz

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@PVince81 Please create the backport for 8.2.1

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19769

**Comment by karlitschek** [comment]
please backport

**Pull request merged**
