### PR TITLE
Stable8.1 backport 19546

### PR DESCRIPTION
**Pull request by oparoz**
Backport of #19546

### CODE REVIEW

**Comment by oparoz** [comment]
I think the failed test is related.

**Comment by DeepDiver1975** [comment]
@MorrisJobke @nickvergessen did we backport the unit test cleanup pr already?

**Comment by MorrisJobke** [comment]
> @MorrisJobke @nickvergessen did we backport the unit test cleanup pr already?

@DeepDiver1975 #19604 That one?

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 #19604 That one?

I just noticed, that it is ready for merge.

**Comment by oparoz** [comment]
Looks like it could help get rid if the 7 extra shares returned by the DB query :)

**Comment by MorrisJobke** [comment]
I rebased this because #19604 was merged :)

**Comment by oparoz** [comment]
Could someone re-run the tests please?

**Comment by oparoz** [comment]
Ooops, my page was out of date :)
Seems all good now.

**Comment by oparoz** [comment]
Ready to review @icewind1991 @PVince81

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested :+1:

**Pull request merged**
