### PR TITLE
OCS api request header needs to be checked before the controller meth…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…od is executed

## Description
OCS requests need to transmit the header OCS-APIREQUEST

## Motivation and Context
This got lost while migrating from the legacy OCS implementation to OCSControllers

## How Has This Been Tested?
- send an OCS request (e.g. create share) with session cookie but no OCS_APIREQUEST header -> get a 401
- with the header the request will be processed properly

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
restarting drone - litmus tests failed ..... should be unrelated .....

**Review by micbar — CHANGES_REQUESTED** [review]
Needs changelog file

**Comment by micbar** [comment]
@C0rby FYI

**Review by IljaN — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
@micbar shalle we merge this now? And/Or do we need this on another branch? THX

**Comment by micbar** [comment]
Great!
We need it on the `release-10.4.0` branch

**Comment by DeepDiver1975** [comment]
> Great!
> We need it on the `release-10.4.0` branch

cherry-picked to https://github.com/owncloud/core/pull/36700/commits/4890576668cc585d886012cc81254bf5144a35f8

**Comment by phil-davis** [comment]
`release-10.4.0` is now saying it has merge conflicts with `CHANGELOG.md`

**Comment by micbar** [comment]
This got cherry picked to the release branch. So we should close this PR.

In the future, we should just merge the PR on the release branch.

**Comment by micbar** [comment]
Closing in favour of https://github.com/owncloud/core/pull/36762

**Pull request closed without merging**
