### PR TITLE
Fix typos and some other adjustments

### PR DESCRIPTION
**Pull request by LukasReschke**
@schiesbn @th3fallen Probably most relevant here is that I changed some public interface signature to enforce the array type which was annotated.

### CODE REVIEW

**Comment by LukasReschke** [comment]
```
Argument 4 passed to Mock_IEncryptionModule_6a003bf4::begin() must be of the type array, null given, called in /var/jenkins/workspace/pull-request-analyser-ng-simple@3/label/SLAVE/lib/private/files/stream/encryption.php on line 240 and defined
```

@schiesbn So apparently null is also a valid data then? This should get annotated then properly too. Something like `array $foo = null` and in the annotation `array|null`.

**Comment by th3fallen** [comment]
i could be mistaken since i didn't touch the wrapper but im almost positive it should always be an array @schiesbn Is that the case?

**Comment by DeepDiver1975** [comment]
let me have a look - I did implement the test cases here ...

**Comment by schiesbn** [comment]
looks good to me :+1:

**Comment by LukasReschke** [comment]
@DeepDiver1975 @owncloud-bot looks still unhappy.

**Comment by DeepDiver1975** [comment]
Oh I was only testing the stream wrapper. Did forget the storage wrapper.

**Comment by LukasReschke** [comment]
+1 for @DeepDiver1975's changes and I assume he +1's mine so let's merge this… Nobody loves bureaucracy.

**Pull request merged**
