### PR TITLE
Remove AvatarPermissions repair step

### PR DESCRIPTION
**Pull request by PVince81**
## Description
It is obsoleted because avatars were moved to a separate folder during
upgrade.

## Related Issue
https://github.com/owncloud/core/issues/28902

## Motivation and Context
Makes upgrade faster by not running extra queries.

## How Has This Been Tested?
Increase version.php and rerun upgrade: no errors.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tomneedham** [comment]
jenkins mysql docker timeout 😒

**Comment by jvillafanez** [comment]
Code is fine, but we need to check the tests 👍

**Comment by PVince81** [comment]
tests passed, merging

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/29202

**Pull request merged**
