### PR TITLE
Left align checkboxes in group dropdown

### LINKED ISSUE #19158: Users checkbox and +add group button should be aligned
Users checkbox and +add group button should be aligned
ownCloud Enterprise Edition 8.2 pre alpha (daily) 9803d68e55254c63e0b60ad76b36fa5da948adf7
alinear

8.1.3
alinear2

### PR DESCRIPTION
**Pull request by Henni**
fixes #19158

### CODE REVIEW

**Comment by Henni** [comment]
@davitol @PVince81 @jancborchardt

**Comment by PVince81** [comment]
Looks better :+1:

**Comment by davitol** [comment]
:+:1 It looks better now IMHO

**Comment by jancborchardt** [comment]
Cool, thank you! :) :+1:

**Pull request merged**
