### PR TITLE
Revert "verify the path in the autoloader"

### PR DESCRIPTION
**Pull request by nickvergessen**
This reverts commit e9b91b1798fde385aafc0512865b1c11b0249069.

Reverting as per https://github.com/owncloud/core/pull/18396#issuecomment-137036147

@DeepDiver1975

### CODE REVIEW

**Comment by icewind1991** [comment]
:-1:

**Comment by Xenopathic** [comment]
:-1:

**Comment by nickvergessen** [comment]
Well instead of -1ing you could also just send the solution to the mailing list.

**Comment by Xenopathic** [comment]
Solution was sent -> closing

**Pull request closed without merging**
