### PR TITLE
Return privatelink via DAV

### PR DESCRIPTION
**Pull request by IljaN**
## Description
Possibility to retrieve privatelinks via dav, to facilitate better integration with clients
## Related Issue
#28984 

## How Has This Been Tested?
- Manually (mitmproxy, cadaver)
- Integration tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by IljaN** [comment]
### Example request/response:
Request:
PROPFIND http://localhost:8000/remote.php/dav/files/admin/foo/zubulski.txt 
```xml
<?xml version='1.0' encoding='utf-8'?>
<propfind xmlns="DAV:">
  <prop>
    <privatelink xmlns="http://owncloud.org/ns"/>
  </prop>
</propfind>
```
Response:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"
xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"
xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/files/admin/foo/zubulski.txt</d:href>
    <d:propstat>
      <d:prop>
        <oc:privatelink>http://localhost:9090/index.php/f/22</oc:privatelink>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```
### Capabilities
```json
{
   "ocs":{
      "meta":{
         "status":"ok",
         "statuscode":100,
         "message":"OK",
         "totalitems":"",
         "itemsperpage":""
      },
      "data":{
         "version":{
            "major":10,
            "minor":0,
            "micro":3,
            "string":"10.0.3 beta",
            "edition":"Community"
         },
         "capabilities":{
            "core":{
               "pollinterval":60,
               "webdav-root":"remote.php/webdav",
               "status":{
                  "installed":"true",
                  "maintenance":"false",
                  "needsDbUpgrade":"false",
                  "version":"10.0.3.0",
                  "versionstring":"10.0.3 beta",
                  "edition":"Community",
                  "productname":"ownCloud"
               }
            },
            "dav":{
               "chunking":"1.0"
            },
            "files_sharing":{
               "api_enabled":true,
               "public":{
                  "enabled":true,
                  "password":{
                     "enforced":false
                  },
                  "expire_date":{
                     "enabled":false
                  },
                  "send_mail":false,
                  "upload":true,
                  "multiple":true,
                  "supports_upload_only":true
               },
               "user":{
                  "send_mail":false
               },
               "resharing":true,
               "group_sharing":true,
               "default_permissions":31,
               "federation":{
                  "outgoing":true,
                  "incoming":true
               }
            },
            "checksums":{
               "supportedTypes":[
                  "SHA1"
               ],
               "preferredUploadType":"SHA1"
            },
            "files":{
               "privateLinks":true, // <----- New capability
               "bigfilechunking":true,
               "blacklisted_files":[
                  ".htaccess"
               ],
               "undelete":true,
               "versioning":true
            }
         }
      }
   }
}
```

**Comment by ckamm** [comment]
Looks good from a client point of view. The private link returned by the new DAV property works and respects `overwritehost`.

However, the private link displayed in the file browser web ui did not! (seems orthogonal to this PR)

**Comment by PVince81** [comment]
>However, the private link displayed in the file browser web ui did not respect overwritehost in my tests! (seems orthogonal to this PR)

I think the one from the web UI is based on whatever URL is displayed in the web browser / UI, so if that domain does not match overwritehost, then it would not match. In a normal setup I'd expect both to be the same.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@IljaN please backport to stable10

**Pull request merged**
