### PR TITLE
Moving mysql setup code over to Doctrine

### LINKED ISSUE #11788: deprecated mysql_connect should be replaced with PDO
During install we are using mysql_connect, which has been deprecated with PHP 5.5. We should migrate to PDO for all db connections where possible (at least PDO_OCI is still experimental).

Furthermore, driver options, which are eg. needed to set up an SSL encryted connection to a mysql server should be respected for the initial set up as well as for post install doctrine connections.

- [ ] During installation replace mysql_connect with PDO or maybe even doctrine2 if possible
- [ ] The db availability checks need to be changed https://github.com/owncloud/core/search?q=mysql_connect&type=Code&utf8=%E2%9C%93
- [ ] Pass additional driver options to the connection during installation, as well as post installation

ref https://github.com/owncloud/core/pull/11783
ref https://github.com/owncloud/core/issues/11718

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #11788

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Broken tests can't be fixed by jenkins branches;) Let me have a look at them and fix them ;)

**Comment by DeepDiver1975** [comment]
THX @MorrisJobke

**Comment by LukasReschke** [comment]
Requires some more fine tuning for PHP 7. Let me hijack this one.

**Comment by LukasReschke** [comment]
Modified so that the setup also checks against PDO instead of the removed deprecated function. Installation does now work for PHP 7 :+1:

**Comment by DeepDiver1975** [comment]
> Installation does now work on PHP 7 :+1:

great - thx - this was my next step ... thanks for jumping in

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
THX

**Pull request merged**
