### PR TITLE
Warn for password reset when files_encryption is enabled

### PR DESCRIPTION
**Pull request by LukasReschke**
This patch will warn the user of the consequences when resetting the password and requires checking a checkbox (as we had in the past) to reset a password.

Furthermore I updated the code to use our new classes and added some unit tests for it :dancers:

Fixes https://github.com/owncloud/core/issues/11438

@jancborchardt Requires some UI love.

\cc @gig13

### CODE REVIEW

**Comment by hostingnuggets** [comment]
Where is this nice warning message when a user tries to recover his password and does not have the recovery password enabled you mention @schiesbn ? I am using 7.0.4 and just tried the reset password function with no such warning. This is a catastrophy in terms of UX as his account is all messed up after. How do you expect a user remembering his old password in order to reset his private key? This user just clicked "reset password" for a reason... because he forgot it...

**Comment by RandieM** [comment]
Hello everyone.

Having the warning message back is really great. However, there will still be MANY users that will just tick the box and proceed and will then complain to us (their admin) for not being able to access their old files. Password reset through an email link -at least the way it is is right now- is quite of a problem for us. It significantly increases the administration work on our side, as we have to reply to emails and phone calls and explain to technical or non-technical customers why they no longer have access to their files, no matter if we clearly stress out in our instructions and FAQ that password recovery disabled together with a weak memory can be a catastrophic combination. 

Most importantly, we have several customers that forget their password/encryption key, reset their log-in password via the email link, realise that they no longer have access to their files and instead of contacting us, they decide to re-upload them. This means that they end up using double the storage space that they are paying us for (e.g. if they have a 10 GB storage package, they can end up using 20 GB; 10 GB for their newly uploaded unencrypted files and 10 GB for the inaccessible encrypted files).

For us, an "easy" solution to this would be to have the possibility to disable password reset via email link for customers with password recovery disabled and enable password reset via email link for those that have password recovery enabled.

Thanks.

**Comment by MorrisJobke** [comment]
@RandieM Can you open this as a feature request with a new ticket in this bug tracker. Otherwise it will get lost. Thanks

**Comment by RandieM** [comment]
@MorrisJobke thanks for the advice. I opened this issue #16839. I was a bit unsure how to do what you suggested, so I hope it's OK like that.

**Pull request merged**
