### PR TITLE
[stable9.1] Dont decrypt shared files

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/25639 to stable9.1

Please review and test @DeepDiver1975 @VicDeo @owncloud/encryption

### CODE REVIEW

**Comment by PVince81** [comment]
Retested, works

**Comment by PVince81** [comment]
I skimmed through the log and it seems all passed except OCI that timed out.
(if you wonder how I do it that fast, I use keywords to search for the result line :wink:)

**Comment by PVince81** [comment]
Review please @DeepDiver1975 @VicDeo @butonic (backport)

**Comment by PVince81** [comment]
or @jvillafanez

**Comment by DeepDiver1975** [comment]
jenkins is green - status was not reported back due to rate limitation issues :angry:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
