### PR TITLE
Stable10 oracle ilike fix

### PR DESCRIPTION
**Pull request by butonic**
backport of https://github.com/owncloud/core/pull/26672 to stable10

### CODE REVIEW

**Comment by patrickjahns** [comment]
Please show maintainers some ❤️ and provide meaningful PR and commit messages that can be included in CHANGELOG later on :-)

**Comment by butonic** [comment]
ping @tomneedham

**Comment by phil-davis** [comment]
@tomneedham @butonic @DeepDiver1975 @PVince81 is this a backport that should be in 10.0.9?

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
