### PR TITLE
Update issue_template.md

### PR DESCRIPTION
**Pull request by jnweiger**
## Description

Provide a way in the webinterface to let users view a version of the config file where all sensitive values are removed (like the command line instruction, but more accessible).
Change the instruction and avoid all references to pasting the raw config file content

## Related Issue

https://hackerone.com/bugs?report_id=196969&subject=owncloud

## Motivation and Context

Advertise the apparently not well known config report of the web-ui

## How Has This Been Tested?

no. It is usability. Time will tell.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
If users post the whole config report inside the ticket it is likely to get very long.
Ideal would be to post it as attachment, if possible.

**Comment by DeepDiver1975** [comment]
@jnweiger can you please fix this PR as discussed ? THX

##ToDos:
- [ ] set milestone
- [ ] set label
- [ ] squash commits
- [ ] use reasonable commit message

**Comment by michaelstingl** [comment]
Perhaps recommend to paste the generated configreport to https://gist.github.com/ and link in the issue.

**Comment by jnweiger** [comment]
@DeepDiver1975 I suggest to merge without waiting for the broken travis job. This is a pure textual change that cannot be selenium-tested anyway!

**Comment by lefherz** [comment]
https://github.com/owncloud/core/pull/27695 
I thought it would be a good idea to add another warning not to post the passwords inside config.php. The line "paste your config.php" still stands there as it is. This would look very bad on a screenshot in a blogpost how owncloud apparently didn't solve the problem. one more line doesn't hurt.

**Pull request merged**
