### PR TITLE
inject the correct external share manager into the storage

### LINKED ISSUE #21125: Can load empty folder of "not available" external storage
The PROPFIND of the folder returns 200, although the storage is not available.
But the list of files is empty.
Trying to create a folder/file both results in an error.

cc @PVince81

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #21125

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Tested, works :+1: 

Will need backport to 8.2 too, together with https://github.com/owncloud/core/pull/22629

@karlitschek backport to 8.2 ?

**Comment by PVince81** [comment]
Need a seconds reviewer @nickvergessen @Xenopathic @MorrisJobke @LukasReschke @rullzer @schiesbn

**Comment by karlitschek** [comment]
Backport makes sense. Thanks a lot!

**Comment by icewind1991** [comment]
8.2: #22649

**Comment by rullzer** [comment]
Tested and works: :+1:

**Pull request merged**
