### PR TITLE
[stable9] Fix conditional check in MySQL setup

### PR DESCRIPTION
**Pull request by enoch85**
Backport of #23760

Fix conditional check in MySQL setup.

cc @DeepDiver1975 @MorrisJobke @bartv2 @Xenopathic

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Backport of #23760

cc @karlitschek

**Comment by MorrisJobke** [comment]
> cc @karlitschek

Was already approved in https://github.com/owncloud/core/pull/23760

@enoch85 For the future please wait with the backport PR until the PR is merged or at least fully reviewed. Otherwise you could run into the situation that the PR receives updates which cause additional work ;)

**Comment by enoch85** [comment]
Thanks for the hint @MorrisJobke Just figured that @karlitschek did :+1: so it was approved.

**Comment by enoch85** [comment]
Btw, please Review @MorrisJobke :)

**Comment by Xenopathic** [comment]
You committed the patch as yourself, although technically I'm the author :see_no_evil: (it's no problem really, but you might find it easier to `git cherry-pick <commit-id>` in the future, which preserves authorship information)

**Comment by enoch85** [comment]
@Xenopathic Just wanted to help.

**Comment by karlitschek** [comment]
yes. the backport of this is fine. Sorry if this wasn't clear

**Comment by rullzer** [comment]
:+1:

**Comment by enoch85** [comment]
What is taking Scrutinizer so long?

**Comment by MorrisJobke** [comment]
> What is taking Scrutinizer so long?

It's broken afaik - cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
