### PR TITLE
Use the query builder for the joblist queries

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested this and also jobs are properly added (also only once if they are the same), updated and removed.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by nickvergessen** [comment]
Just saying, we have full unit test coverage for this :speak_no_evil:

**Comment by rullzer** [comment]
:+1: works :)

**Pull request merged**
