### PR TITLE
[Stable7] Read version and product name from update template

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #13341

@PVince81 you are the original author
@DeepDiver1975 @jnfrmarks @LukasReschke

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: works

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
friendly reminder - stable7 is still frozen until 7.0.5 is off the hook

**Comment by MorrisJobke** [comment]
Tested, works :+1:

**Pull request merged**
