### PR TITLE
[WIP] Adding new symfony events to replace old hooks

### PR DESCRIPTION
**Pull request by sharidas**
Adding new symfony events for the following:
1) setPassword
2) setPassphrase

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

There are more places where old hooks are being used. The intention of this PR is to hunt them down and replace with the symfony events.

## Motivation and Context

Replace the old private hooks with the symfony events.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sharidas** [comment]
There is a followup for this PR in the app: https://github.com/owncloud/encryption/pull/25

**Comment by PVince81** [comment]
please don't delete the old hooks, we want to stay compatible

the event dispatcher events are an **addition**

**Comment by PVince81** [comment]
obsolete ?

**Comment by PVince81** [comment]
tech debt to be rescheduled

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
