### PR TITLE
[stable8] Properly handle NotPermittedException in SabreDAV

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Makes sense :+1: 

I get this is caught already on master and stable8.1 by the convertToSabreException, right ?

**Comment by MorrisJobke** [comment]
> I get this is caught already on master and stable8.1 by the convertToSabreException, right ?

Yes.

**Comment by MorrisJobke** [comment]
@PVince81 I also added a unlink for the part file. It is intended that the part file is moved to the trash?

**Comment by PVince81** [comment]
No, the part file should never be moved to trash.
But in older version if it uses the view, it might still happen.

Please add `if ($needsPartFile)` before deleting it. There are cases where it isn't a part file but the real file (s2s)

**Comment by MorrisJobke** [comment]
> Please add if ($needsPartFile) before deleting it. There are cases where it isn't a part file but the real file (s2s)

The whole try-catch block is within a `if($needsPartFile)`.

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Then it's fine :smile:

**Comment by PVince81** [comment]
@MorrisJobke did you intend to make this delete the part file ?
There are two code paths: chunking and non-chunking. You only changed the non-chunking one.
The chunking one is here, did you miss it ? https://github.com/owncloud/core/blob/stable8-catch-notpermitted/lib/private/connector/sabre/file.php#L336

**Comment by MorrisJobke** [comment]
> @MorrisJobke did you intend to make this delete the part file ?
> There are two code paths: chunking and non-chunking. You only changed the non-chunking one.
> The chunking one is here, did you miss it ? https://github.com/owncloud/core/blob/stable8-catch-notpermitted/lib/private/connector/sabre/file.php#L336

Oh. Possible, because I tested this only with small files.

**Comment by MorrisJobke** [comment]
@PVince81 I added it and tested the chunking with the sync client. Before my fix the part file was still present in the files/ folder. Afterward it was deleted.

**Comment by MorrisJobke** [comment]
@PVince81 Thanks for the hint.

**Comment by PVince81** [comment]
Yeah, I hate those two code paths, it's not the first time the second one was forgotten... needs a good refactoring.

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
GIve it another try ... then I will create a jenkins PR

**Comment by MorrisJobke** [comment]
Jenkins success can be found here https://github.com/owncloud/core/pull/17521#issuecomment-119882211

**Comment by icewind1991** [comment]
:+1: looks good

**Pull request merged**
