### PR TITLE
Update info checker requirements

### PR DESCRIPTION
**Pull request by nickvergessen**
- version is not mandatory
- require/requiremin/requiremax are deprecated replaced by dependency->owncloud
- dependency is marked to be mandatory for 11+

@DeepDiver1975 @MorrisJobke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
from my understanding version is not mandatory - you can have an app which has no version.
Background: we only need the version for update scenarios

**Comment by nickvergessen** [comment]
Right, adjusted the unit test to make sure that without version it also passes

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
