### PR TITLE
[10.2.0] Wait for form to load when following password reset link

### PR DESCRIPTION
**Pull request by skshetry**
## Description

This adds a wait for the form in the `password reset` page. 

## Motivation and Context

Fixes [drone error](https://drone.owncloud.com/owncloud/core/17030/903)

## How Has This Been Tested?

- locally and :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by skshetry** [comment]
`composer install` has failed. https://drone.owncloud.com/owncloud/core/17106/1083

**Comment by skshetry** [comment]
Backport of #35115 for `10.2.0`

**Comment by PVince81** [comment]
bad day today :'(

```
fatal: unable to access 'https://github.com/owncloud/core.git/': Could not resolve host: github.com
time="2019-05-02T10:16:14Z" level=fatal msg="exit status 128"
```

**Review by individual-it — APPROVED** [review]

**Comment by PVince81** [comment]
and I can't cancel the build even on the CLI... will need to wait for it to finish then restart

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Note: acceptance test code only. Fixes an intermittent timing issue with some tests. So would be good to also have this in the release branch so that CI there runs as reliably as we know how. Therefore this backport.

**Comment by PVince81** [comment]
restarted

**Comment by PVince81** [comment]
failed tests unrelated, merging

**Pull request merged**
