### PR TITLE
use efficient startsWith implementation, don't check if key exists twice

### PR DESCRIPTION
**Pull request by butonic**
While working on https://github.com/owncloud/core/pull/28212 I was profiling the performance for user:sync and this actually made a measurable difference.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: since all tests still pass

**Comment by PVince81** [comment]
@butonic backport?

**Comment by PVince81** [comment]
@butonic missing backport. If not required, please remove label

**Comment by DeepDiver1975** [comment]
backport pr open

**Pull request merged**
