### PR TITLE
Bump Zipstreamer

### LINKED ISSUE #19862: Encoding issue on tar and zip names
bildschirmfoto von 2015-10-19 10-13-50

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/core/issues/19862

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
3rdparty merged - please update submodule

**Comment by LukasReschke** [comment]
Rebased.

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
