### PR TITLE
Backport of various fixes in OCS api auth - refs #12917

### PR DESCRIPTION
**Pull request by DeepDiver1975**
# Test plan:
- connect to owncloud with the client
- file up and download (Testing WebDAV operations)
- share and unshare a file (Testing OCS API)
# Requires testing of following constellations:

|  | Desktop Client | Android | iOS | WebDAV Client | external dav mount |
| --- | --- | --- | --- | --- | --- |
| With Shibboleth |  |  |  |  |  |
| With Shibboleth using secondary WebDAV | <sub>not relevant</sub> | <sub>not relevant</sub> | <sub>not relevant</sub> |  |  |
| With LDAP |  |  |  |  |  |
| With Regular Users |  |  |  |  |  |

### CODE REVIEW

**Comment by karlitschek** [comment]
Hey @DeepDiver1975 Where are we here? We want to have this in the next patch release.

**Comment by DeepDiver1975** [comment]
> Hey @DeepDiver1975 Where are we here? We want to have this in the next patch release.

As stated in the description (an over here https://github.com/owncloud/core/pull/12917#issuecomment-70618711) - there is a test plan which was to be executed. QA task from my pov. THX

**Comment by DeepDiver1975** [comment]
re schedule for 7.0.6

**Comment by MorrisJobke** [comment]
Ping?

Something to work on together with @jnfrmarks ?

**Comment by jnfrmarks** [comment]
The tests are written; the server configurations are not yet fully vetted out in our automation.  The tests do not support LDAP users just yet (that is in the works)

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
```
01:39:18.760 Using database oc_autotest6
01:39:18.760 Setup environment for oci testing ...
01:39:18.768 Fire up the oracle docker
01:39:19.540 Waiting 60 seconds for Oracle initialization ... 
01:40:19.539 Installing ....
01:40:19.725 ownCloud is not installed - only a limited number of commands are available
01:40:21.398 Oracle connection could not be established
01:40:21.398  -> ORA-01033: ORACLE initialization or shutdown in progress Check environment: ORACLE_HOME=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server ORACLE_SID=XE LD_LIBRARY_PATH=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/lib: NLS_LANG=AMERICAN_AMERICA.AL32UTF8 tnsnames.ora is readable
01:40:21.402 Kill the docker 2e9bdc0fba83c85797b317cf356d6dfa707ad2890ee5927240ee41f2b375a1d6
01:40:33.927 2e9bdc0fba83c85797b317cf356d6dfa707ad2890ee5927240ee41f2b375a1d6
```

@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@jnfrmarks @rperezb Would be nice to get this in 7.0.6. @nickvergessen Are the smashbox tests that use the OCS API? (maybe through pyocclient or cmd line part of our client)

@DeepDiver1975 In the original PR the tests were run against the client matrix. Is this useful?

**Comment by nickvergessen** [comment]
> @nickvergessen Are the smashbox tests that use the OCS API? (maybe through pyocclient or cmd line part of our client)

I think that is what happens. Not sure how they auth though, so don't use them to test this PR

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Something for 7.0.9?

**Comment by DeepDiver1975** [comment]
TBH: close - nobody gave a :hankey: ...

**Comment by chrsch** [comment]
Hm looking into this after some time. This means that the related problems (i. e. not able to view pdf in ios app if oc is 7.0.x) will not be fixed (https://github.com/owncloud/ios/issues/246)? This would be really disappointing...

**Comment by nickvergessen** [comment]
As per https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule and https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule#minor-releases---maintenance-releases 
* ownCloud 7.0 was released on: 2014-06-23
* ownCloud 7.0 reached `security fixes only` on: 2015-06-23
* ownCloud 7.0 reaches end-of-life on: 2016-01

**Pull request closed without merging**
