### PR TITLE
kill RemoveOldShares

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
:skull: 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
10.0.1. Only criticals from now on.

JS tests timed out.

**Comment by PVince81** [comment]
:+1:

To merge after 10.0.0 is out.

**Review by DeepDiver1975 — COMMENTED** [review]
Printing out the log before behat execution?

**Comment by SergioBertolinSG** [comment]
Removed last commits, they were just for debugging. Being addressed here https://github.com/owncloud/core/issues/27749

This PR will require a rebase after that one is fixed in master.

**Comment by PVince81** [comment]
Rebased for CI

**Pull request merged**
