### PR TITLE
[stable10] make sure mtime is always an int

### PR DESCRIPTION
**Pull request by phil-davis**
Backport of #28066

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
@DeepDiver1975 @PVince81 Jenkins infrastructure not working so well.
Can we just get this sort of backport merged so it is available to others who backport/build in stable10?

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
please set milestone and labels

**Comment by phil-davis** [comment]
@DeepDiver1975 these are "acceptance tests" but I do not see a label for that, so I chose "integration tests".
I suppose we put 10.0.3 milestone on stuff like this? Acceptance tests (and other integration tests, unit tests) are not something that is "released" for users in the ordinary sense, but I guess these things need some milestone to generate a change log.

**Comment by PVince81** [comment]
> these are "acceptance tests"

no need to label that. Just the "To review" and target milestone

**Comment by PVince81** [comment]
rebase for jenkins ?

**Comment by phil-davis** [comment]
Rebased, CI is off and running.

**Comment by phil-davis** [comment]
@PVince81 Jenkins is happy at last. Feel free to merge if you are happy.

**Pull request merged**
