### PR TITLE
[stable10] skip unstable test on LDAP

### PR DESCRIPTION
**Pull request by individual-it**
backport of  #32415

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by individual-it** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
I rebased locally and pushed. For some reason drone did not start from the automated rebase.

**Pull request merged**
