### PR TITLE
Allow 0 byte quota to be entered on UI

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Add a test for entering 0 byte quota (note: 0 can be entered as "0" "0 B" "0 KB" etc)
2) While we are here, add a test to make sure entering a quota of "-1" fails.
3) Improve the check of the return value from ``computerFileSize()``

## Related Issue
#29105 
also improves on old closed issue #25358

## Motivation and Context
It be broke.

## How Has This Been Tested?
Run automated UI tests in a local dev VM. Watch it work.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by SergioBertolinSG — APPROVED** [review]

**Comment by phil-davis** [comment]
For people that just want to offer shared folders to a user, the user's own quota needs to be zero.
Then the user cannot save any real files in their own "personal" area.
Note: there is another issue about the fact that a user with zero quota can create empty files and empty folders - but that is a separate thing that follows on after this PR which lets the admin actually set zero quota.

**Comment by hodyroff** [comment]
In 9.1 with 0 quota I am not able to create any file or folder (Web Frontend).

**Comment by phil-davis** [comment]
Now that zero quota can be entered, there will need to be followup to test exactly what can and cannot be done by a user with 0 bytes quota. Then decide if that is the desired behavior or not.

**Comment by davitol** [comment]
> Now that zero quota can be entered, there will need to be followup to test exactly what can and cannot be done by a user with 0 bytes quota. Then decide if that is the desired behavior or not.

@pmaier1 @PVince81 FYI

**Comment by PVince81** [comment]
I'd say the same things as a user who has filled their storages completely and has 0 bytes available. I don't think "0 bytes quota" should have a special meaning here.

**Pull request merged**
