### PR TITLE
fix: use correct l10n folder when theme is enabled and apps_path is a…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… symlink

## Description
Due to magic path operations an instance could explode under following constellation:
- theme enabled
- symlinked oc installation like `/var/www/owncloud` -> `/var/www/owncloud-10.12.13-crazy.long-name`

## How Has This Been Tested?
- :hand: 
- unit test will follow

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by IljaN — APPROVED** [review]
Not very knowledgeable around this parts of core, but LGMT :+1:

**Comment by phil-davis** [comment]
@DeepDiver1975 changelog?

**Comment by DeepDiver1975** [comment]
I also have one test case pending. Will finish tomorrow

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToRoot2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37858/64

**Comment by jnweiger** [comment]
Cannot confirm this fix. Details see https://github.com/owncloud/enterprise/issues/5633

**Pull request merged**
