### PR TITLE
Fix #30279: Modifies check for CSRF tokens

### LINKED ISSUE #30279: Webdav: only check CSRF for POST
See https://github.com/owncloud/core/blob/v10.0.4/apps/dav/lib/Connector/Sabre/Auth.php#L187.

Some code paths can lead to checking CSRF for PROPFIND or other methods.

This should be changed to only ever check CSRF for POST requests.

This could then avoid strange errors like https://github.com/owncloud/android/issues/1964#issuecomment-360484533

@DeepDiver1975 @settermjd

### PR DESCRIPTION
**Pull request by pandeykartikey**
## Description
In this PR I have modified checks of requiresCSRFCheck() to only check on POST request

## Motivation and Context
It solves the issue #30279 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kartik-25** [comment]
@PVince81 Please review.

**Comment by DeepDiver1975** [comment]
please fix failing unit tests

**Comment by kartik-25** [comment]
@DeepDiver1975 how to run the tests on local?

**Comment by kartik-25** [comment]
@DeepDiver1975 I think test in jenkins also needs to be upgraded. Can you tell me which directory contains those test?

**Comment by phil-davis** [comment]
Down the end of the Jenkins log for the integration tests is the result:
```
--- Failed scenarios:

    /var/lib/jenkins/workspace/owncloud-core_core_PR-30289-5LJAJFDHKDVEDBJV4XL4JDZ7QT2ZQHBEROLNWG6DO43TVVWFW33Q/tests/integration/features/webdav-related-new-endpoint.feature:427
    /var/lib/jenkins/workspace/owncloud-core_core_PR-30289-5LJAJFDHKDVEDBJV4XL4JDZ7QT2ZQHBEROLNWG6DO43TVVWFW33Q/tests/integration/features/webdav-related-old-endpoint.feature:413

532 scenarios (530 passed, 2 failed)
5007 steps (5005 passed, 2 failed)
74m41.96s (29.00Mb)
```
so look in ``tests/integration/features`` in ``webdav-related-new-endpoint.feature:427`` and ``webdav-related-old-endpoint.feature:413``

The Behat/Gherkin of the test scenario has:
```
	Scenario: Doing a PROPFIND with a web login should not work without CSRF token on the new backend
		Given user "user0" exists
		And logging in using web as "user0"
		When sending a "PROPFIND" to "/remote.php/dav/files/user0/welcome.txt" without requesttoken
		Then the HTTP status code should be "401"
```
The behaviour of CSRF stuff is changed in this PR, so these tests will need to expect something different now.

**Comment by kartik-25** [comment]
@phil-davis @DeepDiver1975 have a look I have removed the tests with PROPFIND as if I were to update them they will lead to redundant tests.

**Comment by PVince81** [comment]
Please adjust the tests to confirm that PROPFIND without CSRF does work.

I think no need to have two tests, one with and one without CSRF. Just keep one test for PROPFIND *without* CSRF.

**Comment by kartik-25** [comment]
Propfind without csrf will mean same as get without csrf so no need for such atest @PVince81

**Comment by PVince81** [comment]
Fair enough, makes sense. I restarted CI, let's hope it passes now.

**Comment by kartik-25** [comment]
Just one last question, it's on setting up core I think I have missed some steps in installation can you tell me where is the setting up doc. @PVince81

**Comment by phil-davis** [comment]
https://doc.owncloud.org/server/latest/developer_manual/general/devenv.html
hopefully that gives enough information to get a functioning dev environment that can then be used to develop and run unit, integration (API) and UI tests.

**Comment by PVince81** [comment]
Looks like codecov report is useless on forks ? I can't make it display what pieces of code have reduced coverage. Can we get this fixed ? @DeepDiver1975

**Comment by kartik-25** [comment]
@PVince81 @DeepDiver1975 So what should be done now, regarding the coverage?

**Comment by PVince81** [comment]
@kartik-25 please rebase on top of master. The reason is that the codecov config was broken so the report is wrong. Might also apply to your other PRs if you see no detailed results.

**Comment by kartik-25** [comment]
@PVince81 Done. 😄

**Review by PVince81 — APPROVED** [review]
Looks good 👍

**Comment by phil-davis** [comment]
Backport stable10 #30358

**Pull request merged**
