### PR TITLE
Move user creation to a separate service

### PR DESCRIPTION
**Pull request by sharidas**
Move user creation to a separate service.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Move the user creation to the service class.

## Related Issue

- Fixes <issue_link>

## Motivation and Context

Add the create user to a service class. It is moved from user_management apps UsersController. This will help us in integrating the change with the `user:add` command support creating users with username and email address. It will also help for provisioning API.

## How Has This Been Tested?

- Verified that from webUI users can be created using users page, with and without email address
- Verified that from webUI users can be created using users page and while creation the user could be added to the group. Tested with and without email address.
- Verified in the settings page of the logged in user and in the users page of admin that the group associated with the user is reflected.
- Verified that using `user:add` command the users are created with email address and/or with password. For example:
```
sujith@sujith-ownCloud  ~/test/owncloud   move-createuser-toservice-v2 ●  ./occ user:add --display-name "Test User5" --email "***********" --group "group1" --group "group2" user5
Cannot load Xdebug - it was already loaded
The user "user5" was created successfully
Display name set to "Test User5"
Email address set to "************"
User user5 added to group group1
User user5 added to group group2
 sujith@sujith-ownCloud  ~/test/owncloud   move-createuser-toservice-v2 ●  
```
- In the above example `group1` and `group2` were created and the `user5` is added to the group
- An email is sent to to the user to set the password, if the email is configured in the sever.
- Verified that user can set the pasword.
- Verified using provisioningapi the users are created with and without email address, for example:
```
sujith@sujith-ownCloud  ~/test/owncloud   move-createuser-toservice-v2 ●  curl -X POST http://admin:admin@localhost/testing/ocs/v1.php/cloud/users -d userid="test6" -d email='********' -d groups\[\]="group1" -d groups\[\]="group2"                           
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
 sujith@sujith-ownCloud  ~/test/owncloud   move-createuser-toservice-v2 ● 
```
- From the above example verified that password could be reset from the email received.
- Another example using password:
```
 sujith@sujith-ownCloud  ~/test/owncloud   move-createuser-toservice-v2 ●  curl -X POST http://admin:admin@localhost/testing/ocs/v1.php/cloud/users -d userid="test7" -d password="1" -d email='*********' -d groups\[\]="group2" -d groups\[\]="group1"
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
 sujith@sujith-ownCloud  ~/test/owncloud   move-createuser-toservice-v2 ● 
```
- Was able to login as test7 user with the password provided in the above example. Also verified that email address is added to the user.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Requires https://github.com/owncloud/user_management/pull/196

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by jvillafanez — APPROVED** [review]

**Comment by settermjd** [comment]
I'm not able to create a user from the WebUI without an email address, as the image below shows. I'm using ownCloud 10.3.0 prealpha.

cannot create user without email address

**Comment by sharidas** [comment]
@settermjd In the users page we have a settings in the left bottom of the page where you have to select `Set password for new users` if you have to create user without email address: 
users

**Comment by settermjd** [comment]
Thanks. I'll include that in the documentation.

**Comment by sharidas** [comment]
Created PR https://github.com/owncloud/core/pull/36122 to revert this change.

**Pull request merged**
