### PR TITLE
[WIP] Cleanup filesystem setup code

### PR DESCRIPTION
**Pull request by icewind1991**
- Move the logic of setting up the filesystem from "all over the place" to `\OC\Files\Factory`
- Seperate out logic of setting up the filesystem for object storage based systems (cc @butonic)
- Remove filesystem state from `\OC\Files\Filesystem`
- Let the server container keep track of the state instead

cc @DeepDiver1975 @PVince81 @th3fallen

### CODE REVIEW

**Comment by LukasReschke** [comment]
Rebase required.

**Comment by PVince81** [comment]
@icewind1991 any update ? Is that the one you are splitting in smaller pieces ?

**Comment by PVince81** [comment]
Needs rebasing.

Didn't you split this up already partly ?

**Comment by icewind1991** [comment]
Some of it went in the various other filesystem related PR over the year, but most of it still needs to be done

**Comment by MorrisJobke** [comment]
This PR is over an year old and touches a lot of files that have changed meanwhile. Can this be splitted up in smaller parts to make it easier to review or what is the state of this?

**Comment by icewind1991** [comment]
Yes, would be better to close this and make new PR(s) when we decide to work on it further

Trying to rebase/update this PR would probably be more work then redoing it

**Pull request closed without merging**
