### PR TITLE
fix system wide mount point detection on migration

### PR DESCRIPTION
**Pull request by schiessle**
fix issue detected here by  @nickvergessen 

@karlitschek needs to be backported to 8.1.1.

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1: thanks

**Comment by karlitschek** [comment]
makes sense :+1:  please backport

**Comment by SergioBertolinSG** [comment]
This PR fixes a filed issue ?

**Comment by schiesbn** [comment]
@SergioBertolinSG no, this was a bug we introduced with another issue. But it was already merged when it was discovered. So this is just a follow-up-pr of https://github.com/owncloud/core/pull/17701#discussion_r34992586

**Pull request merged**
