### PR TITLE
Email notifications stable10

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Backport of https://github.com/owncloud/core/pull/30489 to stable10

## Related Issue
New feature

## How Has This Been Tested?
Tested via app as well as unittestsareas of the code, etc.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
```
  [Behat\Testwork\Suite\Exception\SuiteNotFoundException]                               
`sharingInternalGroupsUsers` suite is not found or has not been properly registered. 
```

weird stuff happening... anything we can do ? @phil-davis

**Comment by phil-davis** [comment]
That UI tests suite was split into ``sharingInternalGroups`` and ``sharingInternalUsers`` suites last week.
But the diffs of this PR look OK (i.e. up-to-date with those changes)???

**Comment by phil-davis** [comment]
But when I checkout this ``email_notifications_stable10`` my IDE shows me the UI suites in their old arrangement.
Weird - then why do they not show in the GitHub diffs against ``stable10`` ?

**Comment by PVince81** [comment]
@phil-davis not sure. Maybe @jvillafanez branched off an older stable10.
Or Drone is testing the wrong commit ids...

**Comment by phil-davis** [comment]
I rebased it, see if that helps.

**Comment by jvillafanez** [comment]
Looks like my branch wasn't as up-to-date as it should.

**Comment by phil-davis** [comment]
Happy ``drone``, happy life. It has all the current UI suites and they passed.

**Pull request merged**
