### PR TITLE
Refactoring tests test2

### PR DESCRIPTION
**Pull request by phil-davis**
See if tests pass

### CODE REVIEW

**Comment by phil-davis** [comment]
@carusogabriel I think the changes in the last commit here will make it pass. There were a couple of refactoring errors, but also a couple of existing ``assertEquals()`` where that existing test is a bit loose (false, null, 0 are all equal - true, 1... are equal) but changing to a more strict ``assertTrue()`` etc breaks it. I put "TODO" comment lines in those places.

**Comment by carusogabriel** [comment]
Gonna wait for `Travis CI` and replicate this changes in #29745

**Comment by phil-davis** [comment]
I rebased again tro trigger CI - hopefully Jenkins is up and running by now.

**Comment by phil-davis** [comment]
@carusogabriel all passing now.
The couple of places I commented "TODO" would need someone to look a bit harder and see exactly which of false,0,null and so on is the thing that really should be expected/asserted in order to change them to a more tight assert.

**Comment by carusogabriel** [comment]
What should I do know?

**Comment by phil-davis** [comment]
@carusogabriel I suggest just taking the code that works from here. The TODO items can be looked at later - they are existing "features" of the asserts in the tests.

**Comment by carusogabriel** [comment]
I did, it’s now in the oficial PR. How should it be test there? It’s keeping failing

**Comment by phil-davis** [comment]
See #29791

**Pull request closed without merging**
