### PR TITLE
[stable7] generate valid human readable text for 0 - fixed #9342

### LINKED ISSUE #9342: Storage full message shows NaN as the remaining free space.
Reproduce:

1. Reduce the available storage for one user below to the used space.
2. Upload a file using the web interface

The message shown is:

*Not enough free space, you are uploading 527 B but only NaN undefined is left*

It seems the code is [here](https://github.com/owncloud/core/blob/master/apps/files/js/file-upload.js#L292)

### LINKED ISSUE #19613: NaN error message when changing quota
### Steps to reproduce
1. Setup OC 7.0.5.2
2. Set the primary storage to an Amazon NFS mounted EBS
3. Attempt to Change the quota

### Expected behaviour
An admin should be able to change the quota. If an error occurs, it should be a useful message for the end user.

### Actual behaviour
When changing the quota, a poorly handled error is propagated to the end user.

quotaerror

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.9-1ubuntu4.7

**ownCloud version:** 7.0.5.2

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** See config report on S3

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration 
See Config Report

#### ownCloud log 
To obtain

@tariqsiddiqui @MorrisJobke

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #13771 to stable7 
Fixes #19613

@karlitschek Please approve

cc @cmonteroluque @bboule 

@gig13 Please test.

I tested this and it seems to work. Unit tests run also fine.

### CODE REVIEW

**Comment by karlitschek** [comment]
yes. please backport as discussed

**Comment by cmonteroluque** [comment]
thanks

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @LukasReschke @PVince81 Please review

**Comment by PVince81** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
