### PR TITLE
Use Doctrines filter by table name

### LINKED ISSUE #12506: Upgrade Prob
I was trying an update from 7.0.2 to 7.0.3 in debians jessie. Between installation of these versions I had created some other tables within the owncloud database. The result was a not working database upgrade. The problem in my environment is that listTableNames() or listSequences() in Doctrines SchemaManager are insensitive against the owncloud table prefixes.

I will fix it because I need this fix. But whithout to be any member of any developers community. Whom can I simply send that? Say within next 36 hours...

### PR DESCRIPTION
**Pull request by MorrisJobke**
Doctrine's SchemaManager can filter table names by regular expression.
On this way it picks up only ownClouds's tables in a database.

by @tbelau666

fixes #12506 
superseeds #12537

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Failing tests are unrelated.

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @LukasReschke Reviewers needed

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by LukasReschke** [comment]
Generally speaking: :+1:

If we actually want this for 8 or 8.1 is not my department though ;-)

**Comment by DeepDiver1975** [comment]
:+1: tested by manually generating the schema files

**Pull request merged**
