### PR TITLE
Master is ownCloud 11

### LINKED ISSUE #33205: Set master version to OC 11
Currently the OC version on master is still 10.1.

Since we intend to switch stable10 to semver and use 10.1 there, we should switch master to OC 11 first.

Once we do, to get stable again with CI etc we need to, in order:
- [ ] allow CI to ignore max-version: https://github.com/owncloud/core/issues/31518
- [ ] adjust CI everywhere to ignore max-version
- [ ] set core master version to "OC 11.0.0"
- [ ] do a release of all apps with "max-version=11" and increase their minor version component at least (or major if needed)

Any concerns ? @owncloud/qa

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Related Issue
- Fixes #33205 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
please also update max-version of all apps in core "apps/*" to be "11". should it be "11.0" or "11" for max-version ?

**Comment by DeepDiver1975** [comment]
requires https://github.com/owncloud/files_primary_s3/pull/141

**Comment by DeepDiver1975** [comment]
requires https://github.com/owncloud/notifications/pull/246

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by PVince81 — APPROVED** [review]
:+1: :tada:

**Pull request merged**
