### PR TITLE
use the correct version of the encrypted file

### PR DESCRIPTION
**Pull request by schiessle**
I have no concrete bug for this. All tests I did work before and after this change, still I think that this is the right behavior.

see this PR/discussion for more details and how the bug was introduced: https://github.com/owncloud/core/pull/21557#discussion_r52384938

cc @PVince81 @LukasReschke

### CODE REVIEW

**Comment by PVince81** [comment]
Let me smash this just in case

**Comment by PVince81** [comment]
All smashbox tests failed.

However @LukasReschke pointed out on IRC that there is another bug that the version doesn't get increased on master. It also doesn't get increased in this PR on webdav PUT.

**Comment by PVince81** [comment]
raised here https://github.com/owncloud/core/issues/22260

**Comment by PVince81** [comment]
@schiesbn is this still valid or obsolete by the other fixes ?

**Comment by schiesbn** [comment]
If the other fix goes through, then this one is obsolete.

**Comment by PVince81** [comment]
Obsoleted by https://github.com/owncloud/core/pull/22267

**Pull request closed without merging**
