### PR TITLE
[stable8.1 backport] more secure way to update the database

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/owncloud/core/pull/17473

cc @karlitschek please approve
cc @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Backport approval: https://github.com/owncloud/core/pull/17473#issuecomment-120401700

**Comment by karlitschek** [comment]
yes please :+1:

**Comment by schiesbn** [comment]
@PVince81 you already reviewed the PR for master, can you also have a look at the backport? Thanks!

**Comment by PVince81** [comment]
Tested, works :+1:

**Pull request merged**
