### PR TITLE
Include a migration to disable the enterprise_key app if present

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Disable the enterprise_key app during the upgrade to 10.5.0.
A warning message will appear in the logs.
Requested as part of the new licensing.

## Related Issue
https://github.com/owncloud/core/issues/37510

## How Has This Been Tested?
Manually checked with an upgrade from 10.4.1 to current master (~ 10.5.0beta2)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by micbar — APPROVED** [review]
LTGM

**Review by micbar — CHANGES_REQUESTED** [review]
Tests are failing on server install

**Comment by jvillafanez** [comment]
Migrations don't have tests, so I can't increase the coverage.
This has been tested manually.

**Comment by phil-davis** [comment]
It should get run in nightly https://github.com/owncloud/update-testing 
e.g. https://drone.owncloud.com/owncloud/update-testing/862/1/5

which uses `owncloud-daily-master-qa.tar.bz2` 

So after merging this, we will see if it all goes OK overnight.

**Comment by phil-davis** [comment]
@micbar IMO this does not need a separate changelog, it is part of the existing enterprise_app-related changes.

Please review again.

**Review by micbar — APPROVED** [review]

**Pull request merged**
