### PR TITLE
Do not getShare in deleteShare, it's already there when deleting

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps
1. Create a link share
2. Set Expire date
3. Manipulate DB to set the expire date to the past
4. Access share
### Expected

Message that share is expired
### Actual

500 - Server error
Problem: infinite recursion:

```
->getShare()
->deleteShare()
->getShare()
->deleteShare()
....
```

@rullzer said the get inside delete was for the transition phase and is not needed anymore

@PVince81 review

### CODE REVIEW

**Comment by nickvergessen** [comment]
Tests fail because of https://github.com/owncloud/core/issues/22311 @rullzer

**Comment by rullzer** [comment]
I'll fix #22311 separetly.

Fixed the tests here.

**Comment by nickvergessen** [comment]
:+1: for the test fix

**Comment by rullzer** [comment]
:+1: for the initial commit

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
