### PR TITLE
Log exception when background job class not found

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
otherwise this goes unnoticed - when apps remove background jobs like market / ldap.

## Related Issue
xxx

## Motivation and Context
Unknown cron failures

## How Has This Been Tested?
Not yet. @cdamken 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: makes sense

this also means potential future log pollution as @cdamken found out that some apps aren't removing their jobs when disabled

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
uh what...
```
1) Test\BackgroundJob\JobListTest::testUnknownJobLogsException
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_jobs" ("class") VALUES('wrong job title')':

ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_jobs"."argument")

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:49
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:169
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:145
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1063
/drone/src/lib/private/DB/Connection.php:207
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:203
/drone/src/lib/private/DB/QueryBuilder/QueryBuilder.php:141
/drone/src/tests/lib/BackgroundJob/JobListTest.php:259
/drone/src/tests/lib/BackgroundJob/JobListTest.php:263

Caused by
Doctrine\DBAL\Driver\OCI8\OCI8Exception: ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_jobs"."argument")

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php:16
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:372
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php:136
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1060
/drone/src/lib/private/DB/Connection.php:207
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:203
/drone/src/lib/private/DB/QueryBuilder/QueryBuilder.php:141
/drone/src/tests/lib/BackgroundJob/JobListTest.php:259
/drone/src/tests/lib/BackgroundJob/JobListTest.php:263
```

**Comment by phil-davis** [comment]
Backport `stable10` #34723

**Pull request merged**
