### PR TITLE
Fix 17677 - Remove LDAP case sensitive checkbox

### PR DESCRIPTION
**Pull request by Takuto88**
This PR removes the ldap_nocase checkbox from the ldap-app as specified in 
#17677.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
@Takuto88 thank you very much for your contribution!

What we have here already looks good. I found more traces though:

```
$ ack-grep -i "nocase" apps/user_ldap/
apps/user_ldap/js/wizard/wizardTabAdvanced.js
44:                             ldap_nocase: {
45:                                     $element: $('#ldap_nocase'),
46:                                     setMethod: 'setNoCase'
172:             * @param {string} noCase contains an int
174:            setNoCase: function(noCase) {
175:                    this.setElementValue(this.managedItems.ldap_nocase.$element, noCase);
```

``setNoCase`` can probably vanish and lines 44-47 as well. Could you take care of it as well?


In the issue we also have

> Thus the remaining code is a left over that just should go. With the cleanup, there should be an update script that removes the setting from the database as well.

which needs to be added.

For doing so, could you bump the app version to 0.6.2 (appinfo/version) and in appinfo/update.php delete all "ldapNoCase" settings from existing configurations if the installed version is lower then 0.6.2?

**Comment by Takuto88** [comment]
Thanks for getting back to me. I will be happy to take care of all of there things and get back to you once it is done.

**Comment by Takuto88** [comment]
@blizzz Sorry about the delay. I have now removed the final occurrence of ldap_nocase from the code, bumped the version to 0.6.2 and added the DB update routine. Looking forward to your feedback.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by blizzz** [comment]
@Takuto88 thank you very much! I think we can leave out the one if block. Otherwise, everything looks fine :)

**Comment by Takuto88** [comment]
@blizzz Thanks for pointing that out. I've removed the if statement .

**Comment by blizzz** [comment]
Tested and works, thank you @Takuto88!

**Pull request merged**
