### PR TITLE
[3rdparty] bump symfony/console to 2.7.7

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/226

https://github.com/owncloud/core/pull/20765 Should go first

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> #20765 Should go first

merged

**Comment by DeepDiver1975** [comment]
> Requires owncloud/3rdparty#226

merged

**Comment by rullzer** [comment]
Rebased and bumped.

**Comment by DeepDiver1975** [comment]
still merge conflict

**Comment by rullzer** [comment]
Ah warg...
Fixed.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
