### PR TITLE
Adding report support

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
It is currently failing here (perhaps not exactly that code, we have sabre 3.2). https://github.com/fruux/sabre-http/blob/3.0/lib/Client.php#L411 When doing the report request.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
@PVince81 There are more cases needed?

**Comment by PVince81** [comment]
Looks good so far except that the big string isn't flexible.
For the properties block you might not need all attributes, unless you are checking them all in the test result.

There is another case worth covering and that is filtering by system tag.

**Comment by SergioBertolinSG** [comment]
I'll change that part and add some different situations.

**Comment by SergioBertolinSG** [comment]
I think it is better to merge this and continue with report + tags in a different PR when adding the the new property or not is agreed.

**Comment by PVince81** [comment]
Yes, let's merge the fav stuff first then

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
