### PR TITLE
[stable8] show a better error message when trying to create a user that already ex...

### PR DESCRIPTION
**Pull request by MorrisJobke**
...ists

backport of #15050

cc @nickvergessen @icewind1991 @Xenopathic

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I also did a quick test for this.

**Comment by MorrisJobke** [comment]
@DeepDiver1975 we need to run @vgezer 's script right before the release to backport l10n ;)

**Comment by nickvergessen** [comment]
Since it is an error language string, I assume it's not too bad UX if it is not translated?

**Comment by DeepDiver1975** [comment]
> Since it is an error language string, I assume it's not too bad UX if it is not translated?

indeed

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by vgezer** [comment]
Maybe we can wait for translators to translate a bit then we can create a backport PR for this string :)

**Pull request merged**
