### PR TITLE
Add blob: scheme to default CSP policy

### LINKED ISSUE #19438: Fix the left side of the file comparator
Since 8.1, it's not possible to get a preview of the uploaded file when using the Web GUI on Firefox.

### Approach 1

Add the `blob:` scheme to the CSP. I don't think this is going to happen. cc @LukasReschke 

### Approach 2

Fix the comparator so that it doesn't require `blob:`

* Stop using ObjectURL to load the data into a blob. I don't see the point of using an ObjectURL since the whole image is going to be loaded in memory anyway
* Use a better re-sampling algorithm

----

@icewind1991 @butonic @PVince81 @MorrisJobke @Xenopathic @rullzer @georgehrke

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/core/issues/19438

cc @oparoz as requested

### CODE REVIEW

**Comment by oparoz** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by oparoz** [comment]
@LukasReschke Backport to 8.1 since it's affected by the same CSP conflict?

**Comment by LukasReschke** [comment]
From my PoV would make sense. Please create a PR.

@karlitschek Fixes https://github.com/owncloud/core/issues/19438#issue-108856248 / https://github.com/owncloud/core/issues/17618#issuecomment-143456397. I'd vote for a backport. Any objections?

**Comment by karlitschek** [comment]
Backport is fine! :+1:

**Pull request merged**
