### PR TITLE
Add support for the x-office/drawing mimetype

### PR DESCRIPTION
**Pull request by JammingBen**
## Related Issue

- Fixes https://github.com/owncloud/core/issues/39593

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by jvillafanez — APPROVED** [review]

**Comment by jvillafanez** [comment]
Will the admins need to run any occ command in order to update the mimetype data? I guess it's run during the upgrade, but I'm not sure.

**Review by phil-davis — APPROVED** [review]
works for me - I see the image with an `odg` file.

**Comment by jnweiger** [comment]
Cool!
Please merge into release-10.9.0 branch, I'll build RC2 with this!

**Comment by jnweiger** [comment]
@JammingBen Tested in 10.9.0RC2

I don't see Drawings offered in the new file dialog:

image

Should that be there?

**Comment by jnweiger** [comment]
Apart from the missing entry in the new file dialog:
Confirmed fixed in 10.9.0 RC2

**Pull request merged**
