### PR TITLE
move updater panel above version number

### LINKED ISSUE #18802: Updater app is above the version on the admin page.
I think we should hardcode that the version is always shown on the bottom of the page and the updater above that. I actually thought that we have this already.

order

### PR DESCRIPTION
**Pull request by georgehrke**
fixes https://github.com/owncloud/core/issues/18802

please review @karlitschek @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
nice! Nobrainer :+1:

**Comment by karlitschek** [comment]
Can you have a look @MorrisJobke @Xenopathic @jancborchardt

**Comment by Xenopathic** [comment]
Version should always be at the bottom :+1:

**Comment by jancborchardt** [comment]
Good, thank you!

**Pull request merged**
