### PR TITLE
[3rdparty] Bump symfony/polyfill-php

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/237

### CODE REVIEW

**Comment by MorrisJobke** [comment]
3rdparty merged, this PR updated and tested -> works :+1:

**Comment by DeepDiver1975** [comment]
@MorrisJobke you are too fast - non of the php test jobs did finish yet

**Comment by MorrisJobke** [comment]
> @MorrisJobke you are too fast - non of the php test jobs did finish yet

? Which tests? There are tests in the 3rdparty repo? I just checked this out -> tested -> merged 3rdparty -> updated this commit and force pushed to this branch to trigger the tests.

**Comment by DeepDiver1975** [comment]
> ? Which tests?

The phpunit test here in this pr did not yet run

**Comment by MorrisJobke** [comment]
> The phpunit test here in this pr did not yet run

Because I force pushed just minutes before your comment ;)

**Comment by DeepDiver1975** [comment]
> Because I force pushed just minutes before your comment ;)

no - dude - I know what I'm talking about - the commit before the force push only had 6 successful checks

**Comment by DeepDiver1975** [comment]
anyway - all green now - ready to merge - THX

**Pull request merged**
