### PR TITLE
don't move files in cache twice, fixes renaming for objectstores

### PR DESCRIPTION
**Pull request by butonic**
cc @icewind1991

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by butonic** [comment]
fixes https://github.com/owncloud/core/issues/15702

**Comment by DeepDiver1975** [comment]
hmmm .. behavioral change with no adoption of unit tests? This is fishy - please investigate - THX

**Comment by DeepDiver1975** [comment]
:-1: until impact/unit testing solved - THX

**Comment by bboule** [comment]
For what is is worth I have applied this change in the lab and it works as expected (files and folders no longer disappear on rename)...hope this is helpful!!!

**Comment by MorrisJobke** [comment]
> :-1: until impact/unit testing solved - THX

@butonic @icewind1991 Can you have a look at this please

**Comment by LorenzoLuconi** [comment]
Patch applied in my owncloud installation using public openstack swift service as storage and now it works. I hope to see this branch merged as soon as possible.

**Comment by butonic** [comment]
superseded by https://github.com/owncloud/core/pull/19414 which contains this fix as well as a testsuite

**Comment by butonic** [comment]
Reopening because the testsuite is now in place.

@DeepDiver1975 please enable objectstore tests for this one

**Comment by butonic** [comment]
pinging @icewind1991 and @MorrisJobke for review now that the testsuite is in place.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 please enable objectstore tests for this one

done

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @butonic Running since 3hs: https://ci.owncloud.org/job/core-ci-linux-swift_primary_storage_tests/database=sqlite,label=SLAVE/29/console

**Comment by icewind1991** [comment]
Change looks good :+1:

**Comment by DeepDiver1975** [comment]
TODO:

- [ ] ci is hanging for what ever reason
- [ ] I really insist on a unit test which covers the changed behavior

**Comment by butonic** [comment]
@icewind1991 keep it coming! This is awesome!

**Comment by MorrisJobke** [comment]
SQLite seems to fail:

```
11:49:02 1) Test_Files_Sharing_Watcher::testFolderSizePropagationToOwnerStorage
11:49:02 Failed asserting that true is false.
11:49:02 
11:49:02 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/files_sharing/tests/watcher.php:123
11:49:02 
11:49:02 2) Test_Files_Sharing_Watcher::testSubFolderSizePropagationToOwnerStorage
11:49:02 Failed asserting that true is false.
11:49:02 
11:49:02 /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/files_sharing/tests/watcher.php:153
```

**Comment by MorrisJobke** [comment]
@icewind1991 Please have a look at this.

**Comment by icewind1991** [comment]
In the current state this PR fixes the sev1 issue this is linked to, adds a unit test for it and fixes ~50% of the failing unit tests when using an object store as home storage (object store unit tests themselves pass).

I've looked trough the remaining failing unit tests but I can't figure out how to fix those at the moment (also not sure if they are bugs or issues with the tests)
With the timescale for 8.2 I suggest merging this PR as-is and move the remaining failures to 8.2.1

cc @DeepDiver1975 @cmonteroluque

**Comment by MorrisJobke** [comment]
Moving this to 8.2.1 too, because the main ticket was moved: https://github.com/owncloud/core/issues/15702#issuecomment-147690595

**Comment by icewind1991** [comment]
> OK, but incomplete, skipped, or risky tests!
> [snip]
> Build step 'Execute shell' marked build as failure

All that work and then the ci script ruins the party :disappointed:

**Comment by icewind1991** [comment]
@DeepDiver1975 can you have a look at what's messing with the ci script

**Comment by DeepDiver1975** [comment]
````
10:31:53 Kill the swift docker
10:31:53 ./autotest.sh: line 274: tests/objectstore/stop-swift-ceph.sh: No such file or directory
10:31:53 Kill the swift docker
10:31:53 Docker executable found - stop and remove docker containers
10:31:53 Stopping and removing docker container 32abd09735483baf51658d0f34e45ca0d9fcaebe07e3a89591c4a1bb48d6b92b
10:31:53 32abd09735483baf51658d0f34e45ca0d9fcaebe07e3a89591c4a1bb48d6b92b
10:31:53 Build step 'Execute shell' marked build as failure
10:31:54 Recording test results

**Comment by DeepDiver1975** [comment]
> 10:31:53 ./autotest.sh: line 274: tests/objectstore/stop-swift-ceph.sh: No such file or directory

there is a file missing .....

**Comment by DeepDiver1975** [comment]
called here https://github.com/owncloud/core/blob/master/autotest.sh#L274

but the wrong path because we are already in tests https://github.com/owncloud/core/blob/master/autotest.sh#L256

**Comment by icewind1991** [comment]
Between the fixes to unit tests this PR holds the following bug fixes:

- Don't move cache files if the source doesn't exist (prevents disappearing files on object stores)
- Properly detect shared files outside the home folder for object home stores (prevents deleted files showing in "Shared By X")
- Fix files having "create" permissions on object stores
- Preserve file ids when restoring a file with object home stores
- Fix trash and versions expire logic with storages that have unlimited/unknown free space

**Comment by icewind1991** [comment]
> 07:35:58 cat: tests/objectstore//dockerContainerCeph.9.swift: No such file or directory
07:35:58 rm: cannot remove ‘tests/objectstore//swift.config.php’: No such file or directory
07:35:58 rm: cannot remove ‘tests/objectstore//dockerContainerCeph.9.swift’: No such file or directory

The whole `$thisFolder` seems unneeded

**Comment by DeepDiver1975** [comment]
rebased ...

**Comment by DeepDiver1975** [comment]
Nice job  @icewind1991 :rocket:

**Comment by DeepDiver1975** [comment]
I'm actually setting the milestone to 9.0 since this pr is against master.

@karlitschek we need to backport this to fix serious issues in 8.2.1

**Comment by karlitschek** [comment]
agreed. please backport

**Comment by MorrisJobke** [comment]
The unit tests crash on a btrfs docker host ...

```
Turning ON incompat feature 'mixed-bg': mixed data and metadata block groups
Turning ON incompat feature 'extref': increased hardlink limit per file to 65536
SMALL VOLUME: forcing mixed metadata/data groups

WARNING! - Btrfs v3.12 IS EXPERIMENTAL
WARNING! - see http://btrfs.wiki.kernel.org before using

Created a data/metadata chunk of size 8388608
fs created label (null) on /tmp/osddata
        nodesize 4096 leafsize 4096 sectorsize 4096 size 300.00MiB
Btrfs v3.12
mounting via loopback
mount: Could not find any loop device. Maybe this kernel does not know
       about the loop device? (If so, recompile or `modprobe loop'.)
```

@butonic Is there a way to fix this easily? Otherwise I'm fine with this but can't test it.

But code wise this looks good :+1:

**Comment by butonic** [comment]
@MorrisJobke hm did you run autotest or just start the container? It needs to run in privileged mode so that loopback devices can be used.

Another solution would be to autodetect btrfs and then not do the whole loobpack device magic as docker can then use the native snapshots to do the fs layering. You could try ripping the loopback stuff from https://github.com/owncloud/core/blob/master/tests/objectstore/entrypoint.sh to see if that helps.

Another thing is that the test currently uses a 300MB storage ... which is enough to run the test suite but might not be enough to test large file uploads.

**Comment by MorrisJobke** [comment]
> @MorrisJobke hm did you run autotest or just start the container?

I did:
```
$ PRIMARY_STORAGE_CONFIG=swift ./autotest.sh sqlite
```

I will try to add a condition for btrfs ... but I think this can be hard to detect :see_no_evil:

**Comment by DeepDiver1975** [comment]
> I will try to add a condition for btrfs ... but I think this can be hard to detect :see_no_evil:

I see no need in spending more time into this - @butonic already invested days in finally funding a running solution for our ci system - this is enough from my pov at the moment.

**Comment by icewind1991** [comment]
> The unit tests crash on a btrfs docker host ...

Run `sudo modprobe loop` beforehand

**Comment by MorrisJobke** [comment]
> Run sudo modprobe loop beforehand

Already solved: https://github.com/owncloud/core/pull/19864

**Comment by butonic** [comment]
:+1: Awesome work icewind! Thanks for taking a look at this!

**Comment by MorrisJobke** [comment]
@butonic can you create the backport? Thanks

**Comment by butonic** [comment]
will create PRs for 8.2 and then try 8.1

**Comment by DeepDiver1975** [comment]
> will create PRs for 8.2 and then try 8.1

up to now we did only talk about 8.2 - what is the need to have this in 8.1?

**Comment by butonic** [comment]
probably none with the next enterprise edition being based on 8.2. Let's see who starts screaming first...

**Pull request merged**
