### PR TITLE
Improve: Index for file_map

### PR DESCRIPTION
**Pull request by LukasReschke**
Replaces https://github.com/owncloud/core/pull/11639

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1: from my site (I'm not the original author)

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by PVince81** [comment]
@nickvergessen might like this? :smile:

**Comment by nickvergessen** [comment]
Well since I'm not on windows anymore, I can't test it when I'm not at home.
but the change looks quite save.

:+1:

**Comment by PVince81** [comment]
One does not simply add an index: https://github.com/owncloud/core/issues/14204 :frowning:

**Pull request merged**
