### PR TITLE
Remove encryption app

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
As per https://github.com/owncloud/core/issues/35777 the encryption app will be released from its own repo

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by patrickjahns** [comment]
This needs to be taken into account for the next releases and we shall publish the first app release 

Can we make a diff between what is in here and encryption repository to be sure we have no extra/false stuff ;-)

**Comment by DeepDiver1975** [comment]
> This needs to be taken into account for the next releases and we shall publish the first app release

Didn't we agree on bundling it from the own repo?

**Comment by phil-davis** [comment]
The old core `stable10` had the encryption acceptance tests in it, so they also need to be removed in this PR. I did that in the commit that I just pushed.

I diff'd the test suites between core `stable10` and the encryption app not long ago. The test code and scenarios are the same in the encryption app.

**Comment by patrickjahns** [comment]
@DeepDiver1975 
> Didn't we agree on bundling it from the own repo?`

works for me - just wanted to keep a reminder in this PR to update this then in the build definitions

@phil-davis 
Did you also diff the code, or only the tests?

**Comment by phil-davis** [comment]
> Did you also diff the code, or only the tests?
I only diffed the acceptance tests

**Comment by patrickjahns** [comment]
There is an issue open to check code alignment https://github.com/owncloud/encryption/issues/118 

So the question is - should we archive the code in `owncloud/encryption` master and move over the code from this repository. That would give us the easiest way forward.

We then could release the app in the repo as 1.4.0 ( as we did with other apps not in the marketplace, but being bundled )

**Comment by DeepDiver1975** [comment]
> So the question is - should we archive the code in `owncloud/encryption` master and move over the code from this repository. That would give us the easiest way forward.

my understanding was that the code is more advanced in owncloud/encryption - did I miss anything?

**Comment by DeepDiver1975** [comment]
> my understanding was that the code is more advanced in owncloud/encryption - did I miss anything?

@patrickjahns see https://github.com/owncloud/encryption/issues/118#issuecomment-517134308 - the code in the app is fine - no need to copy over any code from core

**Comment by DeepDiver1975** [comment]
```
settings/ChangePassword/Controller.php:104 PhanUndeclaredClassMethod Call to method __construct from undeclared class \OCA\Encryption\Crypto\Crypt
settings/ChangePassword/Controller.php:110 PhanUndeclaredClassMethod Call to method __construct from undeclared class \OCA\Encryption\Util (Did you mean class \League\Flysystem\Util)
settings/ChangePassword/Controller.php:117 PhanUndeclaredClassMethod Call to method __construct from undeclared class \OCA\Encryption\KeyManager
settings/ChangePassword/Controller.php:122 PhanUndeclaredClassMethod Call to method __construct from undeclared class \OCA\Encryption\Session
settings/ChangePassword/Controller.php:125 PhanUndeclaredClassMethod Call to method __construct from undeclared class \OCA\Encryption\Recovery
settings/ChangePassword/Controller.php:134 PhanUndeclaredClassMethod Call to method isRecoveryKeyEnabled from undeclared class \OCA\Encryption\Recovery
settings/ChangePassword/Controller.php:139 PhanUndeclaredClassMethod Call to method checkRecoveryPassword from undeclared class \OCA\Encryption\KeyManager
settings/ChangePassword/Controller.php:140 PhanUndeclaredClassMethod Call to method isRecoveryEnabledForUser from undeclared class \OCA\Encryption\Recovery
Makefile:224: recipe for target 'test-php-phan' failed

**Comment by patrickjahns** [comment]
stan doesn't like you
```
In RobotLoader.php line 239:
                                                                               
  File or directory '/drone/src/apps/encryption/appinfo/Migrations' not found  
```

Fixed by dropping the lines here https://github.com/owncloud/core/blob/master/phpstan.neon#L4-L5

**Review by phil-davis — APPROVED** [review]
LGTM - the various bits-and-pieces that reference the now-gone encryption app are tidied up.

**Comment by phil-davis** [comment]
No codecov came, but that is not really relevant anyway - not much can be done if a lot of code is deleted and then the average codecov percentage is different.
@patrickjahns @DeepDiver1975 merge this when drone comes back?

**Comment by phil-davis** [comment]
Note: this did not need to remove encryption tests from drone CI, because during the drone v0.8->v1 upgrade the new drone v1 `.drone.yml` was implemented without encryption test matrix entries anyway (we knew that this PR here was ready to merge!)

**Pull request merged**
