### PR TITLE
log in screen improvement & simplification

### LINKED ISSUE #15527: No loading feedback on log in
When pressing the log in button, the only feedback is the fields being disabled. This is not really feedback enough.

We should also display a loading spinner centered on top of the username/password fields. Just like we do for the installation.

cc @owncloud/designers

### PR DESCRIPTION
**Pull request by jancborchardt**
Better version of https://github.com/owncloud/core/pull/18591 without the color change and even more nice layout changes. :) Please review @owncloud/designers @schiesbn @karlitschek 
- Move log in button into fields and use icon instead of text – this reduces the amount of different elements on the screen a lot and makes it even easier.
- Subdue remember checkbox to not be so distracting
- Use simpler logo style
- It even finally has a nice feedback spinner to fix https://github.com/owncloud/core/issues/15527!

Before & after:
log in

### CODE REVIEW

**Comment by jancborchardt** [comment]
@PVince81 are the test failures cause of the JS? Can you help? ;)

**Comment by karlitschek** [comment]
good :+1:

**Comment by LukasReschke** [comment]
Failing test is unrelated => see https://github.com/owncloud/core/pull/18610 and co.

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
