### PR TITLE
add download icon for image detail view, ref gallery issue 51

### PR DESCRIPTION
**Pull request by jancborchardt**
Fixing https://github.com/owncloud/gallery/issues/51, please review @owncloud/designers @oparoz 

Simple icon addition we need for Gallery.

### CODE REVIEW

**Comment by PVince81** [comment]
White icons ?

We already have "icon-download" that is black/grey. Maybe this one should be called "icon-white-download" ?

Anyway, I see there are already other white icons, so something to keep in mind in the future.

:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
Yes, this is for the details view such as from Gallery. As you can see there are others prefixed »view-« already like play, pause, next, previous etc.

**Comment by jancborchardt** [comment]
@DeepDiver1975 I guess CI and such can be ignored since it’s just images and CSS, right?

**Pull request merged**
