### PR TITLE
fix commit fix z-index of share-autocomplete

### PR DESCRIPTION
**Pull request by libasys**
…86e1fc1c396725ea0a6c8e82

https://github.com/owncloud/core/commit/4edf388a3852507886e1fc1c396725ea0a6c8e82

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1: 
@jancborchardt What do you think?

**Comment by jancborchardt** [comment]
:-1: am fixing this with a revert, we should not pile up more and more z-index changes on top of this :( @libasys will mention you on the PR to review

**Comment by jancborchardt** [comment]
Pleae review https://github.com/owncloud/core/pull/17293

**Comment by MorrisJobke** [comment]
#17293 was merged

**Pull request closed without merging**
