### PR TITLE
Don't return quota when none set

### PR DESCRIPTION
**Pull request by PVince81**
- [x] test for potential regressions!
- [x] BUG: also returns -3 when asking for quota on a shared storage, even when the share owner has a quota set (I suspect a bug on master :frowning:)
- [x] TEST: with desktop clients
- [x] TEST: with mobile clients

### CODE REVIEW

**Comment by MorrisJobke** [comment]
* [ ] integration tests - inspiration could be found at https://github.com/owncloud/core/blob/0d715c1184cf98ac9aae32e42056cf8fad9e7e30/build/integration/features/webdav-related.feature#L19-L25 (for setting up the instance) and https://github.com/owncloud/core/blob/0d715c1184cf98ac9aae32e42056cf8fad9e7e30/build/integration/features/comments.feature#L17-L34 (for checking the webdav response)

**Comment by PVince81** [comment]
Had a chat with @schiesbn and he pointed out that my approach is dangerous: because many things depend on the "free space" value regardless of the quota, like trashbin and versions retention.

I'll use a different less intrusive approach in a way that only affects whatever is displayed or returned in the GUI.

**Comment by PVince81** [comment]
I used a different approach. Instead of touching the `free` index of the result of `getStorageInfo()` I simply added a new attribute `quota`. This means that existing code will still work as before, working with the actual free disk space.

The code paths that affect the personal page and Webdav response are the only ones using that new property to decide whether to return something different when quota is unlimited.

**Comment by PVince81** [comment]
Preliminary review and testing would be good, at least to make sure the server stuff still works.

It is not clear yet whether we want to keep "-3" as the "quota-available-bytes" value, an empty string or remove the element completely. This will depend on the client's behavior.

**Comment by PVince81** [comment]
@icewind1991 @DeepDiver1975 @rullzer

**Comment by PVince81** [comment]
Added behat tests. @MorrisJobke check this out, now you can easily do a propfind on single folders.

**Comment by PVince81** [comment]
According to @ogoffart https://github.com/owncloud/core/issues/19988#issuecomment-188782231, desktop client version >= 2.1.0 will show "125 MB used" without quota when returning -1. This is also what I observed.

According to @davivel and @rperezb https://github.com/owncloud/core/issues/19988#issuecomment-188815444 mobile clients work fine and don't use this value.

- [ ] TEST: test with desktop clients older than 2.1, expecting to see "125 MB of 125 MB used"

Please help review/test

**Comment by PVince81** [comment]
@ogoffart you were right, this is what 1.8.4 shows:
oldclient-negative-quota

Please review this change of behavior related to quota @karlitschek @icewind1991 @MorrisJobke @DeepDiver1975 @rullzer

**Comment by karlitschek** [comment]
i hope and think this is safe with all of out and other clients. :+1:

**Comment by PVince81** [comment]
I'lll have a look at the failing tests

**Comment by PVince81** [comment]
I rebased and fixed the tests.

**Comment by PVince81** [comment]
```
OCA\DAV\Tests\Unit\Connector\Sabre\Directory::testGetQuotaInfo
Expectation failed for method name is equal to <string:instanceOfStorage> when invoked 1 time(s)
Parameter 0 for invocation OC\Files\Storage\Wrapper\Wrapper::instanceOfStorage('\OC\Files\Storage\Shared') does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'\OC\Files\Storage\Wrapper\Quota'
+'\OC\Files\Storage\Shared'

/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/lib/private/helper.php:616
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/dav/lib/connector/sabre/directory.php:293
/ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/dav/tests/unit/connector/sabre/directory.php:229
```

Let me have a look...

**Comment by PVince81** [comment]
Aha, tests look better now.

**Comment by PVince81** [comment]
All important tests passed.

Please review @MorrisJobke @icewind1991 @rullzer @schiesbn

**Comment by icewind1991** [comment]
:+1: looks good

**Pull request merged**
