### PR TITLE
Add unix_socket support for mysql during initial installation - fixes…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… #20210

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@josh4trunks mind testing? THX

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
Needs a second reviewer @icewind1991 @nickvergessen @Xenopathic

**Comment by josh4trunks** [comment]
I won't have a chance to test till tonight. bit maybe someone in the forum post I linked on the bug report could test it out.

**Comment by josh4trunks** [comment]
Just tested a fresh install with this patch and specifying a socket worked as expected! Thanks!
:+1:

**Pull request merged**
