### PR TITLE
Add metadata to post delete hooks

### PR DESCRIPTION
**Pull request by icewind1991**
Allows reading metadata (fileid, mimetype, etc) from postDelete hooks

cc @PVince81 @blizzz

### CODE REVIEW

**Comment by PVince81** [comment]
@icewind1991 is this to fix any particular ticket/task ?

**Comment by blizzz** [comment]
@PVince81 very useful for #20775

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by blizzz** [comment]
Thank you @icewind1991 !

**Pull request merged**
