### PR TITLE
Parse backslash as directory separator in breadcrumb

### LINKED ISSUE #13643: Broken breadcrumbs if backslahes are used in the URL
broken-breadcrumbs

The correct folder is shown, but the breadcrumbs aren't available for URLs that contain backslashes instead of slashes.

### PR DESCRIPTION
**Pull request by LukasReschke**
This will parse backslashes as directory separators in breadcrumbs. Thus when accessing something like `/index.php/apps/files?dir=foo\foo` the breadcrumb will properly resolve this instead of showing `foo\foo`

Fixes https://github.com/owncloud/core/issues/13643

@MorrisJobke @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Can you also change `FileList.setDirectory()` with the same conversion logic ?
Better have that unified format everywhere.

**Comment by DeepDiver1975** [comment]
> Can you also change FileList.setDirectory() with the same conversion logic ?
> Better have that unified format everywhere.

@PVince81 I cannot find this - has this already been addressed? THX

**Comment by PVince81** [comment]
I actually meant here: https://github.com/owncloud/core/blob/fix-breadcrumb-backslash/apps/files/js/filelist.js#L988 Could be put into "setCurrentDir"

**Comment by DeepDiver1975** [comment]
@PVince81 like this?

I'm happy to get some direction on where to ad unit tests for this - THX

**Comment by PVince81** [comment]
Please have a look at this test here: https://github.com/owncloud/core/blob/master/apps/files/tests/js/filelistSpec.js#L1236

You could simply use the two first lines: first call "changeDirectory(...)" with backslashes, then check whether `getCurrentDirectory()` returns the correct path (without backslashes).
No need for any fakeServer tests.

**Comment by DeepDiver1975** [comment]
@PVince81 please have a look - THX

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Works :+1:
Before:
breadcrumbs-backslash-before

After:
breadcrumbs-backslash-after

**Pull request merged**
