### PR TITLE
Add tests for downloading files over dav

### PR DESCRIPTION
**Pull request by icewind1991**
The download counterpart for the dav upload tests from #18127

Once #18901 is merged this can be easily extended with tests where encryption is enabled

cc @PVince81 @DeepDiver1975 @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
Looks good :+1:

**Comment by icewind1991** [comment]
@DeepDiver1975 can we merge this?

**Comment by PVince81** [comment]
Needs a second reviewer (it's only additional tests) @DeepDiver1975 @nickvergessen @Xenopathic

**Comment by Xenopathic** [comment]
Tests pass and make sense :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
