### PR TITLE
Switch from PhantomJS to ChromeHeadless for JS tests

### PR DESCRIPTION
**Pull request by PVince81**
## Related Issue

- Fixes <issue_link>

## Motivation and Context
- PhantomJS is unmaintained and older
- This will deliver more accurate results and avoid headaches while trying to debug PhantomJS-only test issues as the one in https://github.com/owncloud/core/pull/32250

## How Has This Been Tested?
`make test-js`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
conflicting yarn.lock

**Comment by PVince81** [comment]
bah... forgot to pull master

**Comment by PVince81** [comment]
For CI we should look into https://github.com/GoogleChrome/puppeteer/blob/v1.9.0/docs/api.md#environment-variables to avoid redownloading Chrome from mirrors for every run. We should cache this. The PhantomJS packages used to do that automatically.

- [ ] cache chrome download

**Comment by PVince81** [comment]
idea: add chromium to the docker env that runs the JS tests, then set `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`

**Comment by PVince81** [comment]
or bundle puppeteer in the global npm in the drone env, hoping that it will only download it once.

will try locally

**Comment by PVince81** [comment]
just tried: `sudo npm install -g puppeteer` fails with permission denied errors, maybe the installation drops back to regular user in some stage.

Also if you set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 make test-js" it will no use the locally installed chromium. It seems we must download and provide the actual "chrome headless" version somewhere.

**Comment by PVince81** [comment]
not blocking any more, less important => backlog

**Comment by PVince81** [comment]
not working as I'd like to and no time to finish

phantomjs is fine for now

**Pull request closed without merging**
