### PR TITLE
Suppress warnings from DAV migration if there's nothing to do

### LINKED ISSUE #23637: Error output when passing --data-dir during command line installation
### Steps to reproduce
*Basically, install ownCloud via CLI.*
1. Use [this](https://github.com/enoch85/ownCloud-VM/blob/master/beta/owncloud_install.sh#L158-L187) script
2. Install ownCloud with --^ script

(Change `--data-dir` to something else other than `/var/www/owncloud/data`)

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html#command-line-installation

### Expected behaviour
No error output

### Actual behaviour

OwnCloud installs fine, but I get this error output during install:

```
ownCloud is not installed - only a limited number of commands are available
{"reqId":"mWcNULK3K9oZiXs7OLp1","remoteAddr":"","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-30T00:48:11+00:00","method":"--","url":"--","user":"--"}
{"reqId":"mWcNULK3K9oZiXs7OLp1","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(636): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(587): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/maintenance\\\/install.php(84): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Maintenance\\\\Install->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Maintenance\\\\Install), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#14 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-03-30T00:48:13+00:00","method":"--","url":"--","user":"--"}
{"reqId":"mWcNULK3K9oZiXs7OLp1","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(636): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(587): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/maintenance\\\/install.php(84): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Maintenance\\\\Install->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Maintenance\\\\Install), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#14 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-03-30T00:48:13+00:00","method":"--","url":"--","user":"--"}
ownCloud was successfully installed
{"reqId":"mWcNULK3K9oZiXs7OLp1","remoteAddr":"","app":"PHP","message":"chmod(): No such file or directory at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#112","level":3,"time":"2016-03-30T00:48:13+00:00","method":"--","url":"--","user":"ocadmin"}

ownCloud version:
  - installed: true
  - version: 9.0.1.1
  - versionstring: 9.0.1 RC1
  - edition: 

```

### Server configuration
**Operating system**:
Ubuntu Server 14.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5.6
**PHP version:**
7
**ownCloud version:** (see ownCloud admin page)
9.0.1-RC1
**Updated from an older ownCloud or fresh install:**
New
**Where did you install ownCloud from:**
ZIP package from ownCloud

### Logs
 
No logs

### LINKED ISSUE #23747: Fresh installations should not contain "Calendar tables are missing" and "Contacts tables are missing" in log
### Steps to reproduce
1. Install master or 9.0
2. Check the ownCloud log

### Expected behaviour
Should be empty or at least have no "Errors" and only "Info" entries.

### Actual behaviour
Contains the following entries with the log level "Error":

> Exception: {"Exception":"DomainException","Message":"Calendar tables are missing. Nothing to do.","Code":0,"Trace":"#0 \/Users\/lukasreschke\/Documents\/Programming\/oc\/apps\/dav\/lib\/migration\/migratecalendars.php(84): OCA\\Dav\\Migration\\CalendarAdapter->setup()\n#1 \/Users\/lukasreschke\/Documents\/Programming\/oc\/apps\/dav\/appinfo\/application.php(202): OCA\\Dav\\Migration\\MigrateCalendars->setup()\n#2 \/Users\/lukasreschke\/Documents\/Programming\/oc\/apps\/dav\/appinfo\/install.php(27): OCA\\Dav\\AppInfo\\Application->migrateCalendars()\n#3 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/private\/installer.php(634): include('\/Users\/lukasres...')\n#4 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/private\/installer.php(585): OC_Installer::includeAppScript('\/Users\/lukasres...')\n#5 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/private\/installer.php(556): OC_Installer::installShippedApp('dav')\n#6 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/private\/Setup.php(370): OC_Installer::installShippedApps()\n#7 \/Users\/lukasreschke\/Documents\/Programming\/oc\/core\/controller\/setupcontroller.php(64): OC\\Setup->install(Array)\n#8 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/base.php(822): OC\\Core\\Controller\\SetupController->run(Array)\n#9 \/Users\/lukasreschke\/Documents\/Programming\/oc\/index.php(39): OC::handleRequest()\n#10 {main}","File":"\/Users\/lukasreschke\/Documents\/Programming\/oc\/apps\/dav\/lib\/migration\/calendaradapter.php","Line":68}	

> Exception: {"Exception":"DomainException","Message":"Contacts tables are missing. Nothing to do.","Code":0,"Trace":"#0 \/Users\/lukasreschke\/Documents\/Programming\/oc\/apps\/dav\/lib\/migration\/migrateaddressbooks.php(83): OCA\\Dav\\Migration\\AddressBookAdapter->setup()\n#1 \/Users\/lukasreschke\/Documents\/Programming\/oc\/apps\/dav\/appinfo\/application.php(186): OCA\\Dav\\Migration\\MigrateAddressbooks->setup()\n#2 \/Users\/lukasreschke\/Documents\/Programming\/oc\/apps\/dav\/appinfo\/install.php(26): OCA\\Dav\\AppInfo\\Application->migrateAddressbooks()\n#3 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/private\/installer.php(634): include('\/Users\/lukasres...')\n#4 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/private\/installer.php(585): OC_Installer::includeAppScript('\/Users\/lukasres...')\n#5 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/private\/installer.php(556): OC_Installer::installShippedApp('dav')\n#6 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/private\/Setup.php(370): OC_Installer::installShippedApps()\n#7 \/Users\/lukasreschke\/Documents\/Programming\/oc\/core\/controller\/setupcontroller.php(64): OC\\Setup->install(Array)\n#8 \/Users\/lukasreschke\/Documents\/Programming\/oc\/lib\/base.php(822): OC\\Core\\Controller\\SetupController->run(Array)\n#9 \/Users\/lukasreschke\/Documents\/Programming\/oc\/index.php(39): OC::handleRequest()\n#10 {main}","File":"\/Users\/lukasreschke\/Documents\/Programming\/oc\/apps\/dav\/lib\/migration\/addressbookadapter.php","Line":72}
	
<hr/>
cc @DeepDiver1975

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Errors should not be printed to the log if there's nothing to do (that's a good thing!)

Fixes #23747, fixes #23637 

cc @enoch85 @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by enoch85** [comment]
Tested and working! :+1:

**Comment by enoch85** [comment]
This is now in the VM: https://github.com/enoch85/ownCloud-VM/commit/300cb2a7c80e72b94b12e74c2abe94c2b8ed7eef

**Comment by enoch85** [comment]
Backport to stable 9 please?

**Comment by Xenopathic** [comment]
@enoch85 I'd advise you don't patch files in the VM, since they will fail the integrity check and cause confusion for users... Since these messages are only seen when creating the VM, I'd suggest we don't rush a backport for 9.0.1 and rather wait for 9.0.2 (but I'd be inclined to backport too, @karlitschek )

**Comment by enoch85** [comment]
Didn't think if that. You are right.

**Comment by DeepDiver1975** [comment]
Looking at this as of now - it might be better to simply return a boolean from the setup method and don't run the migration based on it's result.

There is no need for an exception here

**Comment by Xenopathic** [comment]
@DeepDiver1975 Feel free to push here to fix it, you'll know how to organise the code better :smile:

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Feel free to push here to fix it, you'll know how to organise the code better :smile:

will do

**Comment by enoch85** [comment]
This should be merged as @DeepDiver1975 yet haven't written an improvement of this PR.

**Comment by DeepDiver1975** [comment]
> This should be merged as @DeepDiver1975 yet haven't written an improvement of this PR.

No needs - the migration code has been dropped already for 9.1

**Comment by enoch85** [comment]
@DeepDiver1975 What about backport then?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 What about backport then?

valid point - I'll prepare a pr - THX

**Pull request closed without merging**
