### PR TITLE
2FA can now be enabled and disabled via the provisioning api

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@hodyroff 

@carlaschroder we need to add this to the provisioning api docs for 9.2 and 9.1

### CODE REVIEW

**Comment by PVince81** [comment]
@DeepDiver1975 what's the test command ?
I scrolled through the diff twice and all I see is "Result", "Result", "Result", "Result", ... and one injected two factor provider. Mind pointing to the place where the command was modified ?

**Comment by DeepDiver1975** [comment]
> Mind pointing to the place where the command was modified ?

https://github.com/owncloud/core/pull/25876/files#diff-b883261d8003d06c420013ab69dbc6a6R302

**Comment by DeepDiver1975** [comment]
corresponding test - https://github.com/owncloud/core/pull/25876/files#diff-90184cbe7bbff574266f442de80364c6R1047

**Comment by PVince81** [comment]
Tested:

1. Enable two factor app
1. Disable two factor for the admin on the CLI: `./occ twofactorauth:disable admin` (else the provisioning API doesn't work, alternative is to create a token)
1. Create a user "user1"
1. `curl -X PUT --user admin:admin "http://localhost/owncloud/ocs/v1.php/cloud/users/user1" -d key="two_factor_auth_enabled" -d value="false"`
1. Check the user state: `curl -X GET --user admin:admin http://localhost/owncloud/ocs/v1.php/cloud/users/user1`

```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <enabled>true</enabled>
  <quota/>
  <email/>
  <displayname>user1</displayname>
  <two_factor_auth_enabled></two_factor_auth_enabled>
 </data>
</ocs>
```

When enabled it shows as 1.

:+1: works

**Comment by PVince81** [comment]
@DeepDiver1975 please submit backport PR for 9.1.1

**Comment by DeepDiver1975** [comment]
> When enabled it shows as 1.

hmmmm - shouldn't it be a proper true and false?

**Comment by PVince81** [comment]
This is what I saw when getting the user:
```
  % curl -X GET --user admin:admin http://localhost/owncloud/ocs/v1.php/cloud/users
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <enabled>true</enabled>
  <quota/>
  <email/>
  <displayname>user1</displayname>
  <two_factor_auth_enabled>1</two_factor_auth_enabled>
 </data>
</ocs>
```

**Comment by PVince81** [comment]
@DeepDiver1975 please backport and include https://github.com/owncloud/core/issues/25908

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 please backport and include #25908

done - https://github.com/owncloud/core/pull/25911

**Pull request merged**
