### PR TITLE
lastInsertId() is properly working with Oracle if the table name is p…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…roperly passed in

@schiesbn @icewind1991 @PVince81 @blizzz THX

### CODE REVIEW

**Comment by PVince81** [comment]
Really ? I remember @nickvergessen telling me that insert ids did not work in Oracle when I wrote unit tests, and I seem to remember that I did pass the table name. Let's see what Jenkins says.

**Comment by DeepDiver1975** [comment]
> Really ?

yes

**Comment by icewind1991** [comment]
> Failed asserting that Array &0 (
    0 => Array &1 (
        'id' => '2'
    )
    1 => Array &2 (
        'id' => '3'
    )
    2 => Array &3 (
        'id' => '4'
    )
    3 => Array &4 (
        'id' => '5'
    )
    4 => Array &5 (
        'id' => '6'
    )
) is identical to Array &0 (
    0 => Array &1 (
        'id' => 2
    )
    1 => Array &2 (
        'id' => 3
    )
    2 => Array &3 (
        'id' => 4
    )
    3 => Array &4 (
        'id' => 5
    )
    4 => Array &5 (
        'id' => 6
    )
).

Looks like we need to do some type casting for the insert id

**Comment by DeepDiver1975** [comment]
@PVince81 from my pov using assertEquals should be used - objections?

**Comment by DeepDiver1975** [comment]
> @PVince81 from my pov using assertEquals should be used - objections?

hmmm - doesn't help either

**Comment by nickvergessen** [comment]
Seems to work, fine by me :+1:

**Comment by DeepDiver1975** [comment]
@PVince81 @icewind1991 objections? THX

**Comment by PVince81** [comment]
Can we throw an exception starting with 9.0 if no table name was passed to "lastInsertId" ?
Or at least a warning if we don't want to break existing functionality.
This could help making sure that developers always pass a table name.

**Comment by nickvergessen** [comment]
Well instead of throwing an exception we could just make the parameter non optional

**Comment by DeepDiver1975** [comment]
> we could just make the parameter non optional

would break the api

**Comment by PVince81** [comment]
then log a warning is the best approach for now

**Comment by DeepDiver1975** [comment]
Let's throw an exception in case of Oracle - other dbms don't need the table name since they have different mechanisms to return the last id

**Comment by icewind1991** [comment]
I would still prefer to explicitly cast the return value to an int

**Comment by DeepDiver1975** [comment]
> I would still prefer to explicitly cast the return value to an int

doesn't work out - on sqlite the ids are returned as strings from the select in https://github.com/owncloud/core/blob/fix-usage-of-lastInsertId/tests/lib/repair/oldgroupmembershipsharestest.php#L74

**Comment by icewind1991** [comment]
Ok :+1:

**Pull request merged**
