### PR TITLE
[stable8] fix getting mount points when passing a path to the files:scan command

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/enterprise/issues/1330

Please review @owncloud/filesystem @MorrisJobke @nickvergessen

### CODE REVIEW

**Comment by PVince81** [comment]
Note, this is a partial backport of https://github.com/owncloud/core/pull/17337 as per https://github.com/owncloud/enterprise/issues/1330#issuecomment-218407200

**Comment by icewind1991** [comment]
:+1:

**Comment by PVince81** [comment]
Second review please @rullzer @nickvergessen

**Comment by nickvergessen** [comment]
Works :+1:

**Comment by nickvergessen** [comment]
Failing tests seem unrelated :+1:

**Pull request merged**
