### PR TITLE
Log insufficient storage in debug level

### LINKED ISSUE #17836: Don't log fatal error for each WebDAV request when quota is exceeded
When a user who has exceeded his quota tries to upload stuff via WebDAV, a fatal error is logged for each PUT request - see also #14516. 

First of all, thanks for making the error message more understandable in #14791.

With lots of users and quite a few of them regularily exceeding their quota, this still fills up the error log fast and makes it difficult to read. 

For our own use, we added Sabre\DAV\Exception\InsufficientStorage to nonFatalExceptions in lib/private/connector/sabre/exceptionloggerplugin.php, thereby logging the message only in DEBUG level. I'll attach a pull request shortly.

Not sure whether that's a good solution for all ownCloud users. For smaller installations where e.g. the hard drive runs full, the error may be beneficial (unless that's logged some other way still).

### PR DESCRIPTION
**Pull request by fmkaiser**
Fix #17836

### CODE REVIEW

**Comment by karlitschek** [comment]
@icewind1991 @DeepDiver1975 What do you think?

**Comment by DeepDiver1975** [comment]
hmmm ... we did have situations where it was really helpful to see this exception in the logs by default (as in non-debug log level)

In this case I'm more for better logging too much then too less.

**Comment by Xenopathic** [comment]
It's important for an admin to know whether a user is at their quota, so I agree with @DeepDiver1975

**Comment by rzg-kaiser** [comment]
@DeepDiver1975 @Xenopathic I can certainly see your point of view and and I'm fine for this pull request to be rejected. 

However it would be very useful in general to be able to separate the really important errors ("ownCloud isn't working, somebody has to do something NOW") from stuff that may be useful to be logged for later analysis. I guess that's what log levels are generally for, but then we would need to log different levels to different files or at least tag the entries to they can be filtered later on. 
In the last three months, our medium sized ownCloud installation (~200 users) has logged >1Mio messages, 200K of them InsufficientStorage errors. 
This makes it pretty much impossible to proactively monitor the ownCloud log for errors.

**Comment by Xenopathic** [comment]
@rzg-kaiser Which log priority do these messages get logged at? You can do the log message filtering at the syslog level (with the syslog backend of course), or shunt everything to an external logging server.

**Comment by raphael-ritz** [comment]
Maybe I got it all wrong - and others will correct me then - but to me the issue seems to be about two different scenarios resulting in the same log entry 'insufficient storage' as fatal error:
1. The entire system as such runs out of storage: in that case I consider it appropriate to signal a 'fatal error' (and triggered by that fire up whatever it takes to bring the system back to operation).
2. An individual user exceeds his/her quota. While I may want to know that as well I wouldn't worry as much as in the other situation. 
Therefore these two cases shouldn't produce the same warning.

Just my two cents.

**Comment by rzg-kaiser** [comment]
@Xenopathic Thanks for the tip about the syslog level. We are logging to syslog already, but it turns out syslog-ng doesn't save the loglevel by default. 

However, in this particular case the InsufficientStorage error gets logged as critical, so that doesn't help much.

**Comment by Xenopathic** [comment]
@rzg-kaiser @raphael-ritz Yes, critical level is certainly too high for this log message. A critical message should be used when 'immediate admin action is required', which is not the case. However, it's definitely not a debug level event either.

**Comment by DeepDiver1975** [comment]
> 1. The entire system as such runs out of storage: in that case I consider it appropriate to signal a 'fatal error' (and triggered by that fire up whatever it takes to bring the system back to operation).

I agree - it would be great have the possibility to separate these cases. In simple setups this works *almost* reliable. But we have seen many cases where the over all physical disk usage can not properly/reliably be taken.

In addition: ownCloud is not mean to be a system monitoring component - others do a far better job on this.

**Pull request closed without merging**
