### PR TITLE
reset mailadress/displayname on blur

### LINKED ISSUE #17789: User details not saved unless click Enter
ownCloud 8.1

* Go to `index.php/settings/users`
* click to edit full name of user
* type new name, click outside of text field

Visually: name was changes
Really: refresh page, name was not changed

However, changes are saved when click enter to submit changes, not just click outside.

So, there is need to either reset user's name or actually save it.

Same for email (probably other fields, didn't check).

### PR DESCRIPTION
**Pull request by michag86**
Fix #17789
Resets values on blur

### CODE REVIEW

**Comment by schiesbn** [comment]
Just tested it... Wouldn't it be better to save it on blur?

**Comment by michag86** [comment]
@schiesbn this question is answered here https://github.com/owncloud/core/issues/17789#issuecomment-162437623

**Comment by schiesbn** [comment]
@michag86 thanks... in this case :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
JS unit tests run fine locally -> ready to merge

**Comment by MorrisJobke** [comment]
@jancborchardt @karlitschek Do we want to backport this? @michag86 asked me about the backport in IRC

**Comment by karlitschek** [comment]
risk is low. so backport is fine with me. :+1:

**Comment by MorrisJobke** [comment]
@michag86 Can you create the backport PRs?

**Comment by michag86** [comment]
@MorrisJobke I will create PRs for stable8, stable8.1 and stable 8.2. Okay?

**Pull request merged**
