### PR TITLE
[stable10] redis develop support fix

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/core/pull/28741

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
conflict ?!

**Comment by PVince81** [comment]
conflict ?!

**Comment by tomneedham** [comment]
> conflict ?!

weird, HEAD didnt have the line comment, cherry-pick had the line comment

=> matrix glitch

**Comment by tomneedham** [comment]
Already fixed in master

**Pull request closed without merging**
