### PR TITLE
Prevent sharing twice with user when already a group

### LINKED ISSUE #18831: Can share twice
### Steps

1. Create a group "group1" and add a user "user1" in it
1. Create a folder "test"
1. Open the network console in the browser
1. Share "test" with "user1"
1. Share "test" with "group1"
1. Replay the XHR from the "user1" share
1. Login as "user1"

This creates a second bogus share entry:
```
MariaDB [owncloud]> select * from oc_share;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
|  1 |          0 | user1      | root      |   NULL | folder    | 8           | /8          |           8 | /test       |          31 | 1441375795 |        0 | NULL       | NULL  |         0 |
|  2 |          1 | group1     | root      |   NULL | folder    | 8           | /8          |           8 | /test       |          31 | 1441375800 |        0 | NULL       | NULL  |         0 |
|  3 |          0 | user1      | root      |   NULL | folder    | 8           | /8          |           8 | /test       |          31 | 1441375807 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+
```

@nickvergessen also managed to produce this with OCS too.

@MorrisJobke @icewind1991 @schiesbn @nickvergessen

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/18831

Dictated by @nickvergessen and typed by me.

@nickvergessen @schiesbn @MorrisJobke @rullzer please review

### CODE REVIEW

**Comment by karlitschek** [comment]
good :+1:

**Comment by PVince81** [comment]
also approved by @schiesbn verbally :+1:

**Comment by icewind1991** [comment]
Might this prevent the duplicate share entries we're seeing

**Comment by nickvergessen** [comment]
Wellit prevents you from doing it via the dropdown. Howeveri dont think anyone did that by hand on our instance, so there might be another code path doing that

**Comment by icewind1991** [comment]
Changes look good :+1: 

@MorrisJobke can you see if this maybe fixes the duplicates

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you see if this maybe fixes the duplicates

The shares that are duplicated here are group shares (to be more specific - share type == 2)

**Comment by icewind1991** [comment]
Ok, then it sounds like it's related to the "create a unique target for the share" logic for group shares.

**Pull request merged**
