### PR TITLE
Changed background image

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Decided after a poll in https://central.owncloud.org/t/new-background-image-your-call/7927

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Is this the result of the poll on central?

**Comment by Kawohl** [comment]
@DeepDiver1975 

Yes it is

**Review by JKawohl — APPROVED** [review]
Looking forward to it

**Comment by felixheidecke** [comment]
Merged into https://github.com/owncloud/core/pull/28424

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG your branch was more then 1500 commits in the past - please always use a recent branch to submit prs - THX

**Pull request closed without merging**
