### PR TITLE
Fix migration of group shared calendars and addressbooks

### LINKED ISSUE #22932: Calendar group shares are not properly migrated
### Steps to reproduce
1. Install ownCloud 8.2
2. Create a group named "Calendar Access"
3. Add some users to that group
4. Create a calendar and share with "Calendar Access"
5. Try to access with some users of the groups => Works
6. Update to ownCloud 9.0
7. Open the calendar app

### Expected behaviour
The calendar should still be properly shared. Users should be able to access it.

### Actual behaviour
It shows the calendar is shared but users don't see it. When deleting the share and recreating it then users finally see the share.

<hr/>

cc @DeepDiver1975

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #22932

@LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
I'd prefer `(int)$s['share_type']` more, but :+1:

**Comment by DeepDiver1975** [comment]
@MorrisJobke this now also fixes the permission issue

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@karlitschek please approve backport - THX

**Comment by karlitschek** [comment]
approved! but don't merge before 9.0.1

**Comment by DeepDiver1975** [comment]
> but don't merge before 9.0.1

jep

**Comment by DeepDiver1975** [comment]
backport is there: https://github.com/owncloud/core/pull/22949

**Pull request merged**
