### PR TITLE
Refactoring tests

### PR DESCRIPTION
**Pull request by carusogabriel**
## Description
I've refactored some tests with [`assertFileExists`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFileExists) and `assertFileNotExists`, [`assertFileEquals`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFileEquals), [`assertFalse`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFalse), [`assertTrue`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertTrue), [`assertNull`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertNull) and `assertNotNull` methods.

## How Has This Been Tested?
`PHPUnit`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by carusogabriel** [comment]
I don't know if I did this commit to the correct branch. If someone can help me :sweat_smile:

**Comment by VicDeo** [comment]
@carusogabriel Thanks for your effort.
Yes, the branch is correct.

**Comment by carusogabriel** [comment]
I've refactored more tests:

- Instead of `count` PHP method, use [`assertCount`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertCount);
- Avoid use PHP functions `is_*`. Instead, use [`assertInternalType`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertInternalType);
- Use [`assertStringEqualsFile`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertStringEqualsFile) when comparing strings and files;
- When comparing string, use [`assertContains`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertContains) instead of `strpos`, `in_array` or `array_search`;
- Use [`assertTrue`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertTrue) or [`assertFalse`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertFalse), instead of comparing `true` or `false` keyworkds with [`assertEquals`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertEquals)/[`assertSame`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertSame);

**Comment by VicDeo** [comment]
@carusogabriel it looks like the last commit broke some tests. Could you please fix them?

**Comment by carusogabriel** [comment]
I’m trying to fix them. I let you know when succeed

**Comment by carusogabriel** [comment]
@VicDeo I've rebased with master. Some `Travis CI` tests are passing, `Drone` as well, but the fail ones, sound like aren't related to this PR (I guess). May you help me?

**Comment by phil-davis** [comment]
@carusogabriel @VicDeo this is now passing all Jenkins and Drone CI, so it should be good to review and then ask someone to merge it.
Travis-CI does not pass because the UI tests need access to the SauceLabs ownCloud account credentials. That should be fine - no code relevant to that has been changed.

**Review by VicDeo — APPROVED** [review]
Fine with me as soon as https://github.com/owncloud/core/pull/29791 passed

**Comment by VicDeo** [comment]
@DeepDiver1975 I have no permissions  to merge it with  CI failing

**Comment by carusogabriel** [comment]
@DeepDiver1975 Would you consider merging this PR? Also, I would like to work on `PHPUnit 6` support for you. What branch should I do it?

**Comment by phil-davis** [comment]
@carusogabriel I will make a backport PR - that way the CI for it will go green.

**Comment by carusogabriel** [comment]
@phil-davis May I work on `PHPUnit 6` support in `master` branch?

**Comment by DeepDiver1975** [comment]
> @phil-davis May I work on PHPUnit 6 support in master branch?

please not - phpunit 6 drops php 5.6 - we still support php 5.6 in master

**Comment by phil-davis** [comment]
Backport stable10 #29862

**Comment by carusogabriel** [comment]
Support, not complete migration :sweat_smile: 

We could have `"phpunit/phpunit" : ^5.7 || ^6.5` in composer

**Comment by DeepDiver1975** [comment]
> Support, not complete migration 😅

as long as it continues to work ;-)

**Comment by carusogabriel** [comment]
Ok. Gonna work on that in `master` :man_technologist:

**Comment by phil-davis** [comment]
I guess you mean in a branch off ``master``

**Pull request merged**
