### PR TITLE
cap the normalized path cache

### LINKED ISSUE #24340: Use CappedCache for normalized file names
Could help resolve memory errors when scanning a bit number of file.

@icewind1991

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes https://github.com/owncloud/core/issues/24340

Improves memory usage for requests that handle a lot of paths (file scanner)

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
Thanks :+1:

**Comment by MorrisJobke** [comment]
The original issue was filed against 8.2.2 - @cmonteroluque @PVince81 @DeepDiver1975 What about the backport?

**Comment by MorrisJobke** [comment]
The capped memory cache was backported to 8.2.4 at least.

**Comment by PVince81** [comment]
A backport should be fine but would need good regression testing, since this affects a core element.
So 9.0.3 and 8.2.5.

CC @karlitschek

**Comment by karlitschek** [comment]
@PVince81 I completely agree. 👍

**Comment by MorrisJobke** [comment]
@icewind1991 Please prepare the backport PRs after the maintenance releases are out.

**Comment by icewind1991** [comment]
- stable8.2 https://github.com/owncloud/core/pull/24391
- stable9 https://github.com/owncloud/core/pull/24390

**Pull request merged**
