### PR TITLE
Update apps.css (Scroll more smoothly for Webkit browser)

### PR DESCRIPTION
**Pull request by ghost**
Scroll more smoothly for Webkit browser(mobile).

### CODE REVIEW

**Comment by karlitschek** [comment]
@jancborchardt what do you think?

**Comment by icewind1991** [comment]
I dont notice any difference on mobile chrome

**Comment by fuhaoshih** [comment]
https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

Here is the demo of this css change.

**Comment by fuhaoshih** [comment]
Here is my ownloud for test
Server. http://www.ploutizo.com/owncloud/
Account /password  :   demo   demo

**Comment by fuhaoshih** [comment]
Sorry ! I find out ,this change just works for ios safari/chrome
Android chrome without this also can scroll smoothly.

**Comment by jancborchardt** [comment]
:+1: another review please @owncloud/designers and anyone who has an iOS device @LukasReschke @karlitschek

**Comment by jancborchardt** [comment]
Btw @fuhaoshih you are very welcome in our IRC channel #owncloud-design! : ) And if you want to contribute more design fixes, just go ahead. :)

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
one line change -> no contrib agreement required - right? @karlitschek

**Comment by karlitschek** [comment]
correct. everything less then 7 lines is usually considered no problem by for example the FSF

**Comment by jancborchardt** [comment]
@fuhaoshih btw, should this also be added to the `#app-navigation` and `#app-sidebar` then?

**Comment by oparoz** [comment]
This only works on iOS and kills other browsers. Revert, please.

**Comment by jancborchardt** [comment]
@oparoz strange – I tested with Chrome on mobile and didn’t really notice any difference. Can you open a revert pull request?

**Comment by jancborchardt** [comment]
Created a revert PR at https://github.com/owncloud/core/pull/19349

**Pull request merged**
