### PR TITLE
[stable8] forcessl needs SSL configured in webserver

### LINKED ISSUE #16778: Better description of "Enforce HTTPS" in admin backend
Hi,

the option "Enforce HTTPS" within the admin backend is subject of a lot of misinterpretation. Quite often it happens that:

1. Users think they can magically enable SSL within their webserver when using this option
2. Users don't know at all why the checkbox is greyed out

Currently don't know if its better to just document this: https://github.com/owncloud/documentation/issues/1197 or just extend the description here:

https://github.com/owncloud/core/blob/v8.0.4/settings/templates/admin.php#L396

This affects only OC8 and below as OC8.1 has removed this checkbox: https://github.com/owncloud/core/pull/14651

### PR DESCRIPTION
**Pull request by ghost**
fixes #16778

Only stable8-stable6 affected.

### CODE REVIEW

**Comment by RealRancor** [comment]
MIT licensed

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by DeepDiver1975** [comment]
This will break translations. :-1:

**Comment by RealRancor** [comment]
@DeepDiver1975 
What are the alternatives? Documenting it in the docs (where it is probably also not noticed)?

I'm really tired of answering forums and irc questions about this simple thing.

**Comment by MorrisJobke** [comment]
> What are the alternatives? Documenting it in the docs (where it is probably also not noticed)?

Add it after the `p()` element. Wrapping it into `$l->t()` is also not needed anymore, because translations of stable versions aren't update anymore.

**Comment by RealRancor** [comment]
Honestly i don't care anymore about 8.0 so closing this. If some one wants to take this over feel free to create a new PR with the changes.

**Comment by MorrisJobke** [comment]
Reborn in #17917

**Pull request closed without merging**
