### PR TITLE
AvatarController to all OCP functions/Node API

### PR DESCRIPTION
**Pull request by rullzer**
Our shiny new avatarcontroller still has some code that needs to be properly replaced as mentioned in #14802 

This first commit moves towards the Node API

### CODE REVIEW

**Comment by PVince81** [comment]
@rullzer what's left to do ?

**Comment by rullzer** [comment]
@PVince81 nothing really. Altough that still leaves the two issues as mentioned in #14802

PR is rebased. Lets see what jenkins thinks about it.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@Xenopathic @Kondou-ger @Henni Feel free to test this :)

**Comment by MorrisJobke** [comment]
@rullzer rebase is needed

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@Xenopathic Please review this one :)

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
