### PR TITLE
Revert "[stable10] Fix failure of shares which are already moved with transfer-ownership

### PR DESCRIPTION
**Pull request by PVince81**
Reverts https://github.com/owncloud/core/pull/30161

Had to adjust the test reverting as the test file moved to a new location since the original PR

### CODE REVIEW

**Comment by sharidas** [comment]
Below are the steps done to verify the change.
The command fails, as expected:
```
➜  owncloud3 git:(stable10-revert-transfer-ownership-share) ✗ ./occ files:transfer-ownership admin user1                                                       
Cannot load Xdebug - it was already loaded
Analysing files of admin ...
    1 [============================]
Collecting all share information for files and folder of admin ...
    2 [============================]
Transferring files to user1/files/transferred from admin on 20180417_102837 ...
Restoring shares ...
 1/2 [==============>-------------]  50%Could not restore share with id 2:#0 /home/sujith/test/owncloud3/lib/private/Share20/Manager.php(1108): OC\Share20\DefaultShareProvider->getShareById('2', NULL)
#1 /home/sujith/test/owncloud3/lib/private/Share20/Manager.php(691): OC\Share20\Manager->getShareById('2')
#2 /home/sujith/test/owncloud3/apps/files/lib/Command/TransferOwnership.php(317): OC\Share20\Manager->updateShare(Object(OC\Share20\Share))
#3 /home/sujith/test/owncloud3/apps/files/lib/Command/TransferOwnership.php(171): OCA\Files\Command\TransferOwnership->restoreShares(Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/sujith/test/owncloud3/lib/composer/symfony/console/Command/Command.php(252): OCA\Files\Command\TransferOwnership->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/sujith/test/owncloud3/lib/composer/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/sujith/test/owncloud3/lib/composer/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\TransferOwnership), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/sujith/test/owncloud3/lib/composer/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/sujith/test/owncloud3/lib/private/Console/Application.php(161): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/sujith/test/owncloud3/console.php(106): OC\Console\Application->run()
#10 /home/sujith/test/owncloud3/occ(11): require_once('/home/sujith/te...')
#11 {main}
 2/2 [============================] 100%
➜  owncloud3 git:(stable10-revert-transfer-ownership-share) ✗ git show
➜  owncloud3 git:(stable10-revert-transfer-ownership-share) ✗
```

The folder foo/test is created as `admin` user. 'foo/test' is shared to user `user1`. And as `user1` create public link. After this command is run,
- the folder foo/test is available under transferred folder
- the public share link doesn't work. User has to create a new link.

Tried with private link in `user1`. And after running the command, when user tries to open the link,
it opens the folder from transferred folder.

**Review by sharidas — APPROVED** [review]
After the change is reverted, the command does throw exception. And the private link can be opened. :+1:

**Comment by PVince81** [comment]
@sharidas on the chat @pako81 claimed that the share is still lost. Please double check

**Comment by PVince81** [comment]
I've tested this and the share is still lost, so not a solution

**Pull request closed without merging**
