### PR TITLE
Use migrations in Dav app

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
Port dav app to use migrations

## Motivation and Context
Groundwork for https://github.com/owncloud/core/pull/27005

## How Has This Been Tested?
- Installed from this branch/master
- compared the structure for the following tables:
`oc_addressbookchanges`
`oc_addressbooks`
`oc_calendarchanges`
`oc_calendarobjects`
`oc_calendars`
`oc_calendarsubscriptions`
`oc_cards`
`oc_cards_properties`
`oc_dav_shares`
`oc_schedulingobjects`
See https://github.com/owncloud/core/pull/27157#issuecomment-280063994

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
````
23:11:42 creating sqlite db
23:11:42 
23:11:42                                                                                                                                                                                                                                                                                                                              
23:11:42   [Doctrine\DBAL\Exception\SyntaxErrorException]                                                                                                                                                                                                                                                                             
23:11:42   An exception occurred while executing 'CREATE TABLE oc_cards_properties (id INTEGER DEFAULT 0 NOT NULL PRIMARY KEY AUTOINCREMENT, addressbookid INTEGER DEFAULT  NOT NULL, cardid INTEGER UNSIGNED DEFAULT  NOT NULL, name VARCHAR(64) DEFAULT '', value VARCHAR(255) DEFAULT '', preferred INTEGER DEFAULT 1 NOT NULL)':  
23:11:42   SQLSTATE[HY000]: General error: 1 near "NOT": syntax error                                                                                                                                                                                                                                                                 
23:11:42                                                                                                                                                                                                                                                                                                                              
23:11:42 
23:11:42 Exception trace:
23:11:42  () at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:74
23:11:42  Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
23:11:42  Doctrine\DBAL\DBALException::driverExceptionDuringQuery() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:945
23:11:42  Doctrine\DBAL\Connection->query() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/private/DB/Migrator.php:258
23:11:42  OC\DB\Migrator->applySchema() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/private/DB/Migrator.php:81
23:11:42  OC\DB\Migrator->migrate() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/private/DB/Connection.php:429
23:11:42  OC\DB\Connection->migrateToSchema() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/private/DB/MigrationService.php:388
23:11:42  OC\DB\MigrationService->executeStep() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/private/DB/MigrationService.php:346
23:11:42  OC\DB\MigrationService->migrate() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/private/Installer.php:498
23:11:42  OC\Installer::installShippedApp() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/private/Installer.php:467
23:11:42  OC\Installer::installShippedApps() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/private/Setup.php:368
23:11:42  OC\Setup->install() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/core/Command/Maintenance/Install.php:86
23:11:42  OC\Core\Command\Maintenance\Install->execute() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/composer/symfony/console/Command/Command.php:256
23:11:42  Symfony\Component\Console\Command\Command->run() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/composer/symfony/console/Application.php:818
23:11:42  Symfony\Component\Console\Application->doRunCommand() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/composer/symfony/console/Application.php:186
23:11:42  Symfony\Component\Console\Application->doRun() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/composer/symfony/console/Application.php:117
23:11:42  Symfony\Component\Console\Application->run() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/lib/private/Console/Application.php:158
23:11:42  OC\Console\Application->run() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/console.php:99
23:11:42  require_once() at /var/lib/jenkins/workspace/owncloud-core_core_PR-27157-25VSB34MRMU5FI6E6HSAGP4GYEGO5HNHSY3P6QQK67YQW7FFIY4Q/occ:11

**Comment by VicDeo** [comment]
@DeepDiver1975 thanks, I'm aware of it:
```
CREATE TABLE oc_cards_properties
(

id INTEGER DEFAULT 0 NOT NULL PRIMARY KEY AUTOINCREMENT, 
addressbookid INTEGER DEFAULT  NOT NULL, 
cardid INTEGER UNSIGNED DEFAULT  NOT NULL, 
name VARCHAR(64) DEFAULT '', 
value VARCHAR(255) DEFAULT '', 
preferred INTEGER DEFAULT 1 NOT NULL
)
```

**Comment by VicDeo** [comment]
ok, here are some sensible differences based on early adopters pitfalls:
- for numeric fileds `<default></default>` means `'default' => 0,`
- MDB2 schema add implicit `DEFAULT NULL` when there is no default
- MDB2 schema add implicit `COLLATE BINARY` for varchar fields
- MDB2 schema needs explicit `<notnull>true</notnull>` or field will be nullable by default,
 migrations need explicit `'notnull' => false,` or field will have NOT NULL constraint

...to be continued

**Comment by VicDeo** [comment]
Here are results of `show create` comparison for the affected tables:

<table>
  <tbody>
    <tr>
      <th>
        MDB2  (Master)
      </th>
      <th>
        Migrations (This PR)
      </th>
   </tr>
   <tr>
      <td>
CREATE TABLE "oc_addressbookchanges" (   <br>
   "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "uri" VARCHAR(255) DEFAULT NULL, <br>
 "synctoken" INTEGER UNSIGNED DEFAULT 1 NOT NULL, <br>
 "addressbookid" INTEGER NOT NULL, <br>
 "operation" SMALLINT NOT NULL <br>
)
      </td>
      <td>
CREATE TABLE oc_addressbookchanges ( <br>
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 uri VARCHAR(255) DEFAULT NULL, <br>
 synctoken INTEGER UNSIGNED DEFAULT 1 NOT NULL, <br>
 addressbookid INTEGER NOT NULL, <br>
 operation SMALLINT NOT NULL <br>
)
      </td>
   </tr>
   <tr>
      <td>
CREATE TABLE "oc_addressbooks" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "principaluri" VARCHAR(255) DEFAULT NULL, <br>
 "displayname" VARCHAR(255) DEFAULT NULL, <br>
 "uri" VARCHAR(255) DEFAULT NULL, <br>
 "description" VARCHAR(255) DEFAULT NULL, <br>
 "synctoken" INTEGER UNSIGNED DEFAULT 1 NOT NULL <br>
)
      </td>
      <td>
CREATE TABLE oc_addressbooks ( <br>
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 principaluri VARCHAR(255) DEFAULT NULL, <br>
 displayname VARCHAR(255) DEFAULT NULL, <br>
 uri VARCHAR(255) DEFAULT NULL, <br>
 description VARCHAR(255) DEFAULT NULL, <br>
 synctoken INTEGER UNSIGNED DEFAULT 1 NOT NULL <br>
)
      </td>
   </tr>
   <tr>
      <td>
CREATE TABLE "oc_calendarchanges" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "uri" VARCHAR(255) DEFAULT NULL, <br>
 "synctoken" INTEGER UNSIGNED DEFAULT 1 NOT NULL, <br>
 "calendarid" INTEGER NOT NULL, <br>
 "operation" SMALLINT NOT NULL <br>
)
      </td>
      <td>
CREATE TABLE oc_calendarchanges ( <br>
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 uri VARCHAR(255) DEFAULT NULL, <br>
 synctoken INTEGER UNSIGNED DEFAULT 1 NOT NULL, <br>
 calendarid INTEGER NOT NULL, <br>
 operation SMALLINT NOT NULL <br>
)
      </td>
   </tr>
   <tr>
      <td>
CREATE TABLE "oc_calendarobjects" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "calendardata" BLOB DEFAULT NULL, <br>
 "uri" VARCHAR(255) DEFAULT NULL, <br>
 "calendarid" INTEGER UNSIGNED NOT NULL, <br>
 "lastmodified" INTEGER UNSIGNED DEFAULT NULL, <br>
 "etag" VARCHAR(32) DEFAULT NULL, <br>
 "size" BIGINT UNSIGNED NOT NULL, <br>
 "componenttype" VARCHAR(8) DEFAULT NULL, <br>
 "firstoccurence" BIGINT UNSIGNED DEFAULT NULL, <br>
 "lastoccurence" BIGINT UNSIGNED DEFAULT NULL, <br>
 "uid" VARCHAR(255) DEFAULT NULL, <br>
 "classification" INTEGER DEFAULT 0 <br>
)
      </td>
      <td>
CREATE TABLE oc_calendarobjects ( <br>
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 calendardata BLOB DEFAULT NULL, <br>
 uri VARCHAR(255) DEFAULT NULL, <br>
 calendarid INTEGER UNSIGNED NOT NULL, <br>
 lastmodified INTEGER UNSIGNED DEFAULT NULL, <br>
 etag VARCHAR(32) DEFAULT NULL, <br>
 size BIGINT UNSIGNED NOT NULL, <br>
 componenttype VARCHAR(8) DEFAULT NULL, <br>
 firstoccurence BIGINT UNSIGNED DEFAULT NULL, <br>
 lastoccurence BIGINT UNSIGNED DEFAULT NULL, <br>
 uid VARCHAR(255) DEFAULT NULL, <br>
 classification INTEGER DEFAULT 0 <br>
)
      </td>
   </tr>
   <tr>
      <td>
CREATE TABLE "oc_calendars" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "principaluri" VARCHAR(255) DEFAULT NULL, <br>
 "displayname" VARCHAR(255) DEFAULT NULL, <br>
 "uri" VARCHAR(255) DEFAULT NULL, <br>
 "synctoken" INTEGER UNSIGNED DEFAULT 1 NOT NULL, <br>
 "description" VARCHAR(255) DEFAULT NULL, <br>
 "calendarorder" INTEGER UNSIGNED DEFAULT 0 NOT NULL, <br>
 "calendarcolor" VARCHAR(255) DEFAULT NULL, <br>
 "timezone" CLOB DEFAULT NULL, <br>
 "components" VARCHAR(20) DEFAULT NULL, <br>
 "transparent" SMALLINT DEFAULT 0 NOT NULL <br>
)
      </td>
      <td>
CREATE TABLE "oc_calendars" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "principaluri" VARCHAR(255) DEFAULT NULL, <br>
 "displayname" VARCHAR(255) DEFAULT NULL, <br>
 "uri" VARCHAR(255) DEFAULT NULL, <br>
 "synctoken" INTEGER UNSIGNED DEFAULT 1 NOT NULL, <br>
 "description" VARCHAR(255) DEFAULT NULL, <br>
 "calendarorder" INTEGER UNSIGNED DEFAULT 0 NOT NULL, <br>
 "calendarcolor" VARCHAR(255) DEFAULT NULL, <br>
 "timezone" CLOB DEFAULT NULL, <br>
 "components" VARCHAR(20) DEFAULT NULL, <br>
 "transparent" SMALLINT DEFAULT 0 NOT NULL <br>
)
      </td>
   </tr>
   <tr>
      <td valign="top">
CREATE TABLE "oc_calendarsubscriptions" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "uri" VARCHAR(255) DEFAULT NULL, <br>
 "principaluri" VARCHAR(255) DEFAULT NULL, <br>
 "source" VARCHAR(255) DEFAULT NULL, <br>
 "displayname" VARCHAR(100) DEFAULT NULL, <br>
 "refreshrate" VARCHAR(10) DEFAULT NULL, <br>
 "calendarorder" INTEGER UNSIGNED DEFAULT 0 NOT NULL, <br>
 "calendarcolor" VARCHAR(255) DEFAULT NULL, <br>
 "striptodos" SMALLINT DEFAULT NULL, <br>
 "stripalarms" SMALLINT DEFAULT NULL, <br>
 "stripattachments" SMALLINT DEFAULT NULL, <br>
 "lastmodified" INTEGER UNSIGNED DEFAULT NULL <br>
)
      </td>
      <td>
CREATE TABLE oc_calendarsubscriptions ( <br>
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 uri VARCHAR(255) DEFAULT NULL, <br>
 principaluri VARCHAR(255) DEFAULT NULL, <br>
 source VARCHAR(255) DEFAULT NULL, <br>
 displayname VARCHAR(100) DEFAULT NULL, <br>
 refreshrate VARCHAR(10) DEFAULT NULL, <br>
 calendarorder INTEGER UNSIGNED DEFAULT 0 NOT NULL, <br>
 calendarcolor VARCHAR(255) DEFAULT NULL, <br>
 striptodos SMALLINT DEFAULT NULL, <br>
 stripalarms SMALLINT DEFAULT NULL, <br>
 stripattachments SMALLINT DEFAULT NULL, <br>
 lastmodified INTEGER UNSIGNED NOT NULL <br>
)
      </td>
   </tr>
   <tr>
      <td>
CREATE TABLE "oc_cards" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "addressbookid" INTEGER DEFAULT 0 NOT NULL, <br>
 "carddata" BLOB DEFAULT NULL, <br>
 "uri" VARCHAR(255) DEFAULT NULL, <br>
 "lastmodified" BIGINT UNSIGNED DEFAULT NULL, <br>
 "etag" VARCHAR(32) DEFAULT NULL, <br>
 "size" BIGINT UNSIGNED NOT NULL <br>
)
      </td>
      <td>
CREATE TABLE oc_cards ( <br>
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 addressbookid INTEGER DEFAULT 0 NOT NULL, <br>
 carddata BLOB DEFAULT NULL, <br>
 uri VARCHAR(255) DEFAULT NULL, <br>
 lastmodified BIGINT UNSIGNED DEFAULT NULL, <br>
 etag VARCHAR(32) DEFAULT NULL, <br>
 size BIGINT UNSIGNED NOT NULL <br>
)
      </td>
   </tr>
   <tr>
      <td>
CREATE TABLE "oc_cards_properties" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "addressbookid" BIGINT DEFAULT 0 NOT NULL, <br>
 "cardid" BIGINT UNSIGNED DEFAULT 0 NOT NULL, <br>
 "name" VARCHAR(64) DEFAULT NULL, <br>
 "value" VARCHAR(255) DEFAULT NULL, <br>
 "preferred" INTEGER DEFAULT 1 NOT NULL <br>
)
      </td>
      <td>
CREATE TABLE oc_cards_properties ( <br>
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 addressbookid BIGINT DEFAULT 0 NOT NULL, <br>
 cardid BIGINT UNSIGNED DEFAULT 0 NOT NULL, <br>
 name VARCHAR(64) DEFAULT NULL, <br>
 value VARCHAR(255) DEFAULT NULL, <br>
 preferred INTEGER DEFAULT 1 NOT NULL <br>
)
      </td>
   </tr>
   <tr>
      <td>
CREATE TABLE "oc_dav_shares" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "principaluri" VARCHAR(255) DEFAULT NULL, <br>
 "type" VARCHAR(255) DEFAULT NULL, <br>
 "access" SMALLINT DEFAULT NULL, <br>
 "resourceid" INTEGER UNSIGNED NOT NULL, <br>
 "publicuri" VARCHAR(255) DEFAULT NULL <br>
)
      </td>
      <td>
CREATE TABLE oc_dav_shares ( <br>
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 principaluri VARCHAR(255) DEFAULT NULL, <br>
 type VARCHAR(255) DEFAULT NULL, <br>
 access SMALLINT DEFAULT NULL, <br>
 resourceid INTEGER UNSIGNED NOT NULL, <br>
 publicuri VARCHAR(255) DEFAULT NULL <br>
)
      </td>
   </tr>
   <tr>
      <td>
CREATE TABLE "oc_schedulingobjects" ( <br>
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 "principaluri" VARCHAR(255) DEFAULT NULL, <br>
 "calendardata" BLOB DEFAULT NULL, <br>
 "uri" VARCHAR(255) DEFAULT NULL, <br>
 "lastmodified" INTEGER UNSIGNED DEFAULT NULL, <br>
 "etag" VARCHAR(32) DEFAULT NULL, <br>
 "size" BIGINT UNSIGNED NOT NULL <br>
)
      </td>
      <td>
CREATE TABLE oc_schedulingobjects ( <br>
 id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, <br>
 principaluri VARCHAR(255) DEFAULT NULL, <br>
 calendardata BLOB DEFAULT NULL, <br>
 uri VARCHAR(255) DEFAULT NULL, <br>
 lastmodified INTEGER UNSIGNED DEFAULT NULL, <br>
 etag VARCHAR(32) DEFAULT NULL, <br>
 size BIGINT UNSIGNED NOT NULL <br>
)
      </td>
   </tr>
  </tbody>
<table>

**Comment by VicDeo** [comment]
@DeepDiver1975 @PVince81
 ready from my POV

**Comment by PVince81** [comment]
> Here are results of show create comparison for the affected tables:

Nice. I usually do a DB dump and then vimdiff the before.sql and after.sql.

**Comment by PVince81** [comment]
Great work 👍 

I tested a few upgrade paths as well as setting up OC on this branch and it went fine.

**Pull request merged**
