### PR TITLE
[stable9] Ignore names that can't be found in the user manager

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description

Ignore ownCloud names that can't be found in the user manager. This should so
## Related Issue

https://github.com/owncloud/core/issues/26281
## Motivation and Context

User manager can return null objects if the user we're looking for doesn't exists. This isn't being handled at the moment.
## How Has This Been Tested?

❗️ Not tested yet ❗️ 
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
> Ignore ownCloud names that can't be found in the user manager. This should so

Can you provide an example which triggers this?

**Comment by SergioBertolinSG** [comment]
upgrading from stable8.2 to this branch has dropped some errors:

```
dav: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists
```

**Comment by PVince81** [comment]
> User manager can return null objects if the user we're looking for doesn't exists. This isn't being handled at the moment.

@butonic FYI, what could possibly go wrong in other scenarios

**Comment by PVince81** [comment]
@jvillafanez finish for 9.0.6 or defer to 9.0.7 ?

**Comment by jvillafanez** [comment]
It's finished but not fully tested 😅 

I'd rather defer this to 9.0.7 until we have confirmation that it works.

**Comment by jvillafanez** [comment]
> Can you provide an example which triggers this?

Not really. I'll have to gaze at the code. Probably some users where deleted during, or just before the upgrade, but I can't say for sure.

**Comment by PVince81** [comment]
@jvillafanez any update?

**Comment by jvillafanez** [comment]
No updates.

**Comment by PVince81** [comment]
@jvillafanez finish this for 9.0.9 ?

**Comment by jvillafanez** [comment]
Code is finished but untested. I'm checking how we can prove it works.

**Comment by jvillafanez** [comment]
So far, the mapping for a LDAP user might be missing, which would lead to reinsert the mapping in the DB, that's should be what `$ocName = $this->dn2ocname($ldapObject['dn'][0], $nameByLDAP, $isUsers);` is doing.

The problem is with the user manager, somehow it can't fetch the user.

I still don't know how to reach that point.

**Comment by PVince81** [comment]
Any update ?

**Comment by PVince81** [comment]
@jvillafanez can we move this forward ? test steps ? is there any value keeping this ?

Did the original reporter confirmed that it works ?

**Comment by jvillafanez** [comment]
I'm not sure if QA can help to reproduce the issue. https://github.com/owncloud/core/pull/26337#issuecomment-281649889 is the only hint I have, but no clear steps.

**Comment by DeepDiver1975** [comment]
stable 9 is on sec patches only -> close

**Pull request closed without merging**
