### PR TITLE
Remove hardcoded link to performance docs

### LINKED ISSUE #15420: Hardcoded documentation link
We have a hard-coded documentation link [here](https://github.com/owncloud/core/blob/master/core/js/setupchecks.js#L64) and it is likely to be forgotten in the upcoming releases.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix  #15420

@MorrisJobke @LukasReschke @Xenopathic @vgezer

### CODE REVIEW

**Comment by LukasReschke** [comment]
Reminds me to change `linkToDocs` to HTTPS… Other topic though.

**Comment by DeepDiver1975** [comment]
JS unit tests are broken:

````
Test Name	Duration	Age
 PhantomJS 1.9.8 (Linux).OC_SetupChecks tests checkSetup.should return an error if server has no internet connection
 Stack Trace

Expected [ 'This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.', 'Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.', 'No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our <a href="{docLink}">documentation</a>.' ] to equal [ 'This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.', 'Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.', 'No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our <a href="https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/performance_tuning.html">documentation</a>.' ].
Error: Expected [ 'This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.', 'Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.', 'No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our <a href="{docLink}">documentation</a>.' ] to equal [ 'This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.', 'Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.', 'No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our <a href="https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/performance_tuning.html">documentation</a>.' ].
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/js/tests/specs/setupchecksSpec.js:73
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/vendor/jquery/jquery.min.js:4
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/vendor/jquery/jquery.min.js:4
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/js/tests/specs/setupchecksSpec.js:75

 Standard Output
	0.0	1
 PhantomJS 1.9.8 (Linux).OC_SetupChecks tests checkSetup.should return an error if server has no internet connection and data directory is not protected
 Stack Trace

Expected [ 'This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.', 'Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.', 'No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our <a href="{docLink}">documentation</a>.' ] to equal [ 'This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.', 'Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.', 'No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our <a href="https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/performance_tuning.html">documentation</a>.' ].
Error: Expected [ 'This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.', 'Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.', 'No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our <a href="{docLink}">documentation</a>.' ] to equal [ 'This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.', 'Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.', 'No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our <a href="https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/performance_tuning.html">documentation</a>.' ].
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/js/tests/specs/setupchecksSpec.js:90
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/vendor/jquery/jquery.min.js:4
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/vendor/jquery/jquery.min.js:4
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/js/tests/specs/setupchecksSpec.js:92
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/js/tests/specs/setupchecksSpec.js:74
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/vendor/jquery/jquery.min.js:4
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/vendor/jquery/jquery.min.js:4
    at /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/core/js/tests/specs/setupchecksSpec.js:75

 Standard Output

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
