### PR TITLE
[Stable10] improved fed user search

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/core/pull/27996

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: assuming you tested this and it still works

**Comment by tomneedham** [comment]
In the office in a few minutes which has my federated oc setup to test this

**Comment by tomneedham** [comment]
Yes retested on stable10 with 2 instances, setup trusted relationship, created user with email on remote server, synched addressbooks. on local server ran: `./occ config:app:set dav remote_search_properties --value="CLOUD,FN,EMAIL"` then attempted to find a sharee using the remote users email address and their entry was shown.

**Comment by tomneedham** [comment]
kicking jenkins

**Review by butonic — APPROVED** [review]

**Pull request merged**
