### PR TITLE
Avatar speedup

### PR DESCRIPTION
**Pull request by rullzer**
Getting an avatar first wraps it in an OC_Image. This is of no use since we do not do any image operations on it we just pass it on to the request.

Results in roughly a 10% speedup on my local machine (108 ms => 98 ms).

### CODE REVIEW

**Comment by LukasReschke** [comment]
```
14:38:02 ................................................PHP Fatal error:  Uncaught Error: Call to a member function getContent() on null in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/core/avatar/avatarcontroller.php:118
```

**Comment by rullzer** [comment]
It helps of ourse if I also add the updated unit tests.

**Comment by rullzer** [comment]
Probably this is what we want: http://sabre.io/dav/acl/ So we need the ACL stuff.

**Comment by MorrisJobke** [comment]
Avatars still work and code changes look good :+1:

**Comment by icewind1991** [comment]
Looks good :+1:

**Pull request merged**
