### PR TITLE
Handle mountpoint collisions for different providers

### LINKED ISSUE #35154: receiving a local share is not possible when a federation share with same name was received before
### Steps to reproduce
1. install two servers with owncloud and configure federation sharing for me `http://localhost/owncloud-10.2.0/rc2_a` & `http://localhost/owncloud-10.2.0/rc2_b`
2. on server A create a user `user1_on_server_a`
3. on server B create two users `user1_on_server_b` `user2_on_server_b`
4. as `user1_on_server_a` create a folder called `to-share`
5. as `user1_on_server_a` share the folder `to-share` with `user1_on_server_b` via federation sharing
6. as `user1_on_server_b` accept the share
7. as `user2_on_server_b` create a folder called `to-share`
8. as `user2_on_server_b` share the folder `to-share` locally with `user1_on_server_b`

### Expected behaviour
as  `user1_on_server_b` there should be a received folder called `to-share` (fed sharing) and a folder called `to share (2)` local sharing

### Actual behaviour
as  `user1_on_server_b` there is only one received folder called `to-share` (fed sharing) and NO folder called `to share (2)` local sharing
in shared-with-you only one share is listed

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
SQLite / MySQL
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
10.2.0 RC2
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
community tarball

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "occbl8s2az4f",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-10.2.0\/rc2_b\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-10.2.0\/rc2_b",
        "dbtype": "sqlite3",
        "version": "10.2.0.2",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/home\/artur\/www\/owncloud-10.2.0\/rc2_b\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/home\/artur\/www\/owncloud-10.2.0\/rc2_b\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "sharing.federation.allowHttpFallback": true,
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/apps\/testing\/data\/webUISkeleton",
        "installed": true
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.4.0
  - federatedfilesharing: 0.4.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.10.1
  - firstrunwizard: 1.2.0
  - market: 0.4.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Lf15XM4iMAsCf0u8CEo2","level":2,"time":"2019-05-06T07:39:56+00:00","remoteAddr":"127.0.0.1","user":"--","app":"notifications","method":"POST","url":"\/owncloud-10.2.0\/rc2_b\/index.php\/apps\/federatedfilesharing\/shares","message":"notification remote_share#2 can't be sent to user1_on_server_b via email: email for the user isn't set"}
```

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
Check that all user mount points has unique names

## Related Issue
- Fixes #35154

## Motivation and Context
invisible local share when federated share with the same name exists

## How Has This Been Tested?
1. install two servers with owncloud and configure federation sharing for me `http://localhost/owncloud-10.2.0/rc2_a` & `http://localhost/owncloud-10.2.0/rc2_b`
2. on server A create a user `user1_on_server_a`
3. on server B create two users `user1_on_server_b` `user2_on_server_b`
4. as `user1_on_server_a` create a folder called `to-share`
5. as `user1_on_server_a` share the folder `to-share` with `user1_on_server_b` via federation sharing
6. as `user1_on_server_b` accept the share
7. as `user2_on_server_b` create a folder called `to-share`
8. as `user2_on_server_b` share the folder `to-share` locally with `user1_on_server_b`

### Expected behaviour
as  `user1_on_server_b` there should be a received folder called `to-share` (fed sharing) and a folder called `to share (2)` local sharing

### Actual behaviour
as  `user1_on_server_b` there is only one received folder called `to-share` (fed sharing) and NO folder called `to share (2)` local sharing

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by VicDeo** [comment]
Well, there are existing tests that assume there could be shares with the same mount points. 
:open_mouth:

**Comment by micbar** [comment]
@VicDeo What are the next steps on this?
Do you need a review?

**Comment by VicDeo** [comment]
@micbar I'm stuck here. No idea how to fix the tests

**Comment by micbar** [comment]
@phil-davis @individual-it Could you help with the tests?

**Comment by phil-davis** [comment]
@micbar the acceptance tests are passing. Various unit tests are failing e.g. https://drone.owncloud.com/owncloud/core/18094/127
```
here were 83 errors:

1) OCA\Files_Sharing\Tests\UpdaterTest::testShareFile with data set #0 ('/')
Error: Call to a member function getShare() on null
```

We can have a look, however it will be some learning to understand what is going on in the unit tests here (which might be "a good thing")

**Comment by micbar** [comment]
@patrickjahns Could you help here with testing issues?

**Comment by VicDeo** [comment]
This solution causes existing 53 test cases to fail because they are not true unit tests. These tests have external dependencies :/
I'm not sure how to proceed here...

**Comment by VicDeo** [comment]
it;s even more interesting.
`getMountsForUser::MountProviderCollection` has two identical sets of shares from different providers. Let me check...

**Comment by VicDeo** [comment]
can of worms opened :)
3 and 6 
4 and 7 
are the same mount providers :mask: 
mount providers

**Comment by VicDeo** [comment]
I've added a static property to register files_sharing mount providers only once.
But we might want to block duplication  on MountProviderCollection level.
This will also speed up FS initialization a bit.

**Comment by individual-it** [comment]
with this change I have two folders as receiver, but the remote share (that was received firsts) is renames to `xx (2)` the local share (that was received last) keeps its original name

tests to demonstrate the issue were added in https://github.com/owncloud/core/pull/35870
after that test PR is merged, please rebase this PR. After fixing the issue the current tests will fail and will have to be adjusted according to the comments in the feature file

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
