### PR TITLE
cron shall not operate in case we are in maintenance mode - fixes #14843

### LINKED ISSUE #14843: cron.php must not run in maintenance mode is enabled
### Steps
1. Setup OC with either ajax cron or CLI cron
2. Switch on maintenance mode
3. `update oc_jobs set last_run=0`
4. Run `php cron.php` or `curl http://userid:password/owncloud/cron.php`
5. Check "oc_jobs" table

### Expected result
Cron does NOT run, timestamps left as is

### Actual result
Cron runs through the background jobs and updates the "last_run" field.

This can have nasty consequences especially when doing manual database repairs, there is a risk that the background file watcher kicks in and does some scanning.

### Versions
Observed in OC 6.0.5, likely to exist in OC 7 and OC 8 too

@DeepDiver1975 @karlitschek @MorrisJobke @icewind1991

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:  backport is fine

**Comment by nickvergessen** [comment]
:+1:

**Comment by AdamWill** [comment]
Isn't this completely broken without a backport of https://github.com/owncloud/core/commit/50c2a819a0c5ae50571d36a3e2dec4e8267fd13b or adjusting the patch to not use `getSystemConfig()`? There is no `getSystemConfig()` on stable7 ATM.

    [adamw@adam owncloud-core-adamwill (stable7 %)]$ grep -R getSystemConfig *
    cron.php:	if (\OC::$server->getSystemConfig()->getValue('maintenance', false)) {
    [adamw@adam owncloud-core-adamwill (stable7 %)]$

**Comment by PVince81** [comment]
Hmm, maybe this wasn't tested properly.
We shouldn't backport getSystemConfig() as it's from a major refactoring.

We should fix the cron stuff using the old API for reading maintenance mode instead

**Comment by PVince81** [comment]
I'll prepare a follow up PR

**Comment by PVince81** [comment]
Fix here: https://github.com/owncloud/core/pull/15161

**Pull request merged**
