### PR TITLE
avoid triggering frequent error log entries via tempmanager in certain configurations

### PR DESCRIPTION
**Pull request by Larzenegger**
tempnam accepts a directory as its first parameter, not a full path and filename.

tempnam falls back to creating a file in the system's temp directory. On systems with write protection in the installation directory and open_basedir restrictions, this would trigger an error message. By moving this below the checkTemporaryDirectory-loop, the tempnam-directory will only be tested if all alternatives failed and the error message is most likely avoided.

### CODE REVIEW

**Comment by PVince81** [comment]
@Larzenegger thanks for the PR. Any steps/config to reproduce the original issue ?

**Comment by PVince81** [comment]
@icewind1991 @DeepDiver1975 please review

**Comment by Larzenegger** [comment]
@PVince81 the config directives to reproduce the message would be these php.ini settings:
`open_basedir = /var/www/`
`upload_tmp_dir = /var/www/tmp/`

owncloud.log reports:
> {"reqId":"Vn0oofSXgKJRgWQ69SlIoQAAAAo","remoteAddr":"10.0.2.2","app":"PHP","message":"tempnam(): open_basedir restriction in effect. File(\/tmp) is not within the allowed path(s): (\/var\/www) at \/var\/www\/html\/owncloud\/lib\/private\/tempmanager.php#228","level":3,"time":"2015-12-25T11:29:37+00:00"}

I created a Vagrantfile that should build a minimal environment to trigger the issue. Opening http://127.0.0.1:21363/owncloud/ after `vagrant up` completes should generate that log entry. It can be reviewed by connecting to the vm via `vagrant ssh` and excuting `sudo cat /var/www/html/owncloud/data/owncloud.log`.

[Vagrantfile.txt](https://github.com/owncloud/core/files/72170/Vagrantfile.txt)

**Comment by PVince81** [comment]
> tempnam accepts a directory as its first parameter, not a full path and filename.

Hmm so I guess this means that the `tempnam` block never really worked ?

**Comment by PVince81** [comment]
Another approach would have been to add `@` in front of `tempnam` ?

Anyway, I tested whether temp folders still work with this PR and they do :+1:

**Comment by PVince81** [comment]
I pushed this PR https://github.com/owncloud/core/pull/21543 to unstuck the CI tests

**Comment by PVince81** [comment]
Needs a second reviewer @mmattel @Xenopathic @icewind1991 @DeepDiver1975

**Comment by icewind1991** [comment]
:-1: looks good

**Comment by DeepDiver1975** [comment]
#21363 has just merged to get this in

**Pull request closed without merging**
