### PR TITLE
Integration tests new location

### PR DESCRIPTION
**Pull request by SergioBertolinSG**

### CODE REVIEW

**Comment by PVince81** [comment]
I'll adjust the makefiles

**Comment by DeepDiver1975** [comment]
Jenkinsfile needs to be adjusted - right?

**Comment by PVince81** [comment]
on it

**Comment by PVince81** [comment]
Done, let's see if that runs now.

**Comment by DeepDiver1975** [comment]
unit tests are failing due to version bump:

````
Stacktrace

OCA\DAV\Tests\unit\CardDAV\ConverterTest::testCreation with data set #0 ('BEGIN:VCARD\nVERSION:3.0\nPRODI...VCARD\n')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'BEGIN:VCARD
 VERSION:3.0
-PRODID:-//Sabre//Sabre VObject 4.1.1//EN
+PRODID:-//Sabre//Sabre VObject 4.1.2//EN
 UID:12345
 FN:12345
 N:12345;;;;
 PHOTO;ENCODING=b;TYPE=JPEG:MTIzNDU2Nzg5
 END:VCARD
 '

/var/lib/jenkins/workspace/owncloud-core_core_PR-27247-JKJ7BEPSQMZCHJTN2MO6C3I72NMBSERYL7KYLCL6NYXOGXLCQPRA/apps/dav/tests/unit/CardDAV/ConverterTest.php:43

**Comment by DeepDiver1975** [comment]
two are left ...

````
OCA\DAV\Tests\unit\CardDAV\BirthdayServiceTest::testOnCardChanged with data set #1 ('create')
Expectation failed for method name is equal to <string:createCalendarObject> when invoked 3 time(s)
Parameter 2 for invocation #0 OCA\DAV\CalDAV\CalDavBackend::createCalendarObject(1234, 'default-gump.vcf.ics', 'BEGIN:VCALENDAR\nVERSION:2.0\nP...ENDAR\n') does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'BEGIN:VCALENDAR
 VERSION:2.0
-PRODID:-//Sabre//Sabre VObject 4.1.1//EN
+PRODID:-//Sabre//Sabre VObject 4.1.2//EN
 CALSCALE:GREGORIAN
 END:VCALENDAR
 '

/var/lib/jenkins/workspace/owncloud-core_core_PR-27247-JKJ7BEPSQMZCHJTN2MO6C3I72NMBSERYL7KYLCL6NYXOGXLCQPRA/apps/dav/lib/CalDAV/BirthdayService.php:275
/var/lib/jenkins/workspace/owncloud-core_core_PR-27247-JKJ7BEPSQMZCHJTN2MO6C3I72NMBSERYL7KYLCL6NYXOGXLCQPRA/apps/dav/lib/CalDAV/BirthdayService.php:74
/var/lib/jenkins/workspace/owncloud-core_core_PR-27247-JKJ7BEPSQMZCHJTN2MO6C3I72NMBSERYL7KYLCL6NYXOGXLCQPRA/apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php:143

**Comment by PVince81** [comment]
there's a conflict

**Comment by PVince81** [comment]
:+1: rebase all the things!

**Pull request merged**
