### PR TITLE
Improve login screen

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
## Description
When the new OIDC / AzureAD Login was presented the old-fashioned grey "Login with AzureAD" button did not represent this modern feature accordingly. Also the missing dedicated Login-Button was bugging me for years.
This PR adds some styling, makes the HTML valid and adds a dedicated login button.

## How Has This Been Tested?
Latest Firefox, Latest Chrome, Latest Safari

## Screenshots (if appropriate):
Before:
grafik

After:
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

## QA
- [ ] (1) Deleting the background shows weird behaviour
- [x] (2) Setup screen needs some adjustments
- [x] (3) When setting a password in setup screen the password indicator is inside the password field

### CODE REVIEW

**Comment by hurradieweltgehtunter** [comment]
Can't fix the php-code-style issue in drone:
grafik

**Comment by hurradieweltgehtunter** [comment]
One thing to keep in mind (mentioned by @ChrisEdS ): For custom brandings the button color should be included in the styling process.

**Comment by micbar** [comment]
@pmaier1 @hurradieweltgehtunter Ok for me to keep the arrow and add the login button.

@phil-davis but we need to make sure that we really press the login buttton.

**Comment by hurradieweltgehtunter** [comment]
There's multiple possibilities:
1) Keep it as it is now (keep the arrow) -> no functional changes, tests should pass
2) Remove arrow & put loading animation in the login button -> tests need to be adapted; Best UX

I'd prefer 2) UX wise. Let me know if I should do this change also.

**Comment by JanAckermann** [comment]
Beautiful 1 !

**Comment by JanAckermann** [comment]
One more thing: hovering over the -> login arrow button, will now make the item disappear

**Comment by hurradieweltgehtunter** [comment]
Updated also 
- PW reset form
- PW set form

**Comment by hurradieweltgehtunter** [comment]
> One more thing: hovering over the -> login arrow button, will now make the item disappear
> (Only in Chrome, IE11 works)

Last commit removes the login button arrow (which is ok UX wise IMHO). Need to check with CI if problems occur

**Comment by JanAckermann** [comment]
Build is passing, nice one! But please keep the IE11 issue in mind I mentioned before

**Comment by micbar** [comment]
nice!
We need to switch the test suite to use the new button before we merge.

**Review by AlexAndBear — CHANGES_REQUESTED** [review]
Build is passing, nice one! But please keep the IE11 issue in mind I mentioned before.
@pmaier1 candidate for 10.7.1 ?

**Review by JammingBen — COMMENTED** [review]
Awesome! Also LGTM code-wise. Would love to see a focus on these buttons though, especially when having alternative logins.

**Comment by hurradieweltgehtunter** [comment]
> Beautiful 1 !
> 
> @hurradieweltgehtunter encountered a little bug with IE11:
> clicking in the input field will clear the placeholder
> 
> image

That's not a bug. HTML5 Placeholder work like this (only visible if input is empty and not focused).

@micbar If we adapt the test suite I'd prefer to add some more changes to the login button to have a nice loading spinner. I didn't do that before to avoid the need to change the test suite. The tests pass because AFAIK they only look out for a button with the class "login" which is still present. But as I'm not a pro in automatic testing I'd prefer somone looking into that in detail to be safe.

**Comment by JanAckermann** [comment]
@hurradieweltgehtunter That is the 'issue' I am talking about. If I click inside the input field in Chrome/FF the Placeholder will still be visible, in IE11 it disappears. So we got a different behavior here.

**Comment by hurradieweltgehtunter** [comment]
> @hurradieweltgehtunter That is the 'issue' I am talking about. If I click inside the input field in Chrome/FF the Placeholder will still be visible, in IE11 it disappears. So we got a different behavior here.

I re-checked:
- AFAIK the behaviour wasn't changed to the previous one
- There is no other technical implementation than the HTML placeholder tag. Thus, the browser decides who to handle that (which might lead to different behaviours).

As I don't have a IE11 at hand:
- Could you verify that this behaviour differs from other login forms, e.g. https://www.facebook.com
- Also, is there a difference to the previous implementation? Please check on https://cloud.owncloud.com

# Solutions
## A) Leave it like it is
From a technical perspective everything is set up correctly. There is no bug to fix.

## B) Use labels instead of placeholders
A common opinion is to use labels instead of placeholders. Labels are persistent and do not disappear on focus the input or entering data. Could look like this:

grafik

For comparison, this is how it looked before:

grafik


Opinions?

**Comment by JanAckermann** [comment]
@hurradieweltgehtunter 
>Could you verify that this behaviour differs from other login forms, e.g. https://www.facebook.com

For example, Facebook renders labels instead of placeholders in IE11
image

> Also, is there a difference to the previous implementation? Please check on https://cloud.owncloud.com

You are totally right, same behavior

IHMO the Label + Input solutions look much better/modern :+1:

**Review by AlexAndBear — APPROVED** [review]

**Comment by phil-davis** [comment]
The test logs are too old here: https://drone.owncloud.com/owncloud/core/29662/129/15
It would be good if someone first rebases this PR and force-pushes. Then there will be up-to-date drone CI logs.

**Comment by micbar** [comment]
@phil-davis @hurradieweltgehtunter the CI should use the "new" button for all login actions.

**Comment by JanAckermann** [comment]
@micbar seems that the CI already uses this button

**Comment by mmattel** [comment]
Colleagues, this is docs relevant.
In case close to merge, pls file a docs issue (plus example screenshots) so we can do the updates.
In addition, there is the normal u/p login and you now can login via a iDP.
In the screenshot on top, I see that there is twice and iDP login with Azure?
@EParzefall fyi

**Comment by hurradieweltgehtunter** [comment]
@mmattel thakns for pointing this out. Will do.
The duplicate login buttons are only to show that if alternate login methods are present they get the same new button design. The logic behind was not touched.

@JanAckermann I updated the login form to keep the CI test (triggers button with id "login"). CI only needs to be updated to check the lables instead of the previously used placeholders.

**Comment by JanAckermann** [comment]
@hurradieweltgehtunter done, CI is fixed

**Comment by JanAckermann** [comment]
@hurradieweltgehtunter, I squashed the commits and fixed the CI could you add more desprictive words in the changelog item?

Besides that, LGTM 🚀

**Comment by hurradieweltgehtunter** [comment]
@JanAckermann very nice! Thank you.
Let's wait for @ChrisEdS . He heeds to check the new login form in combination with various customer themes. If no problems occur we're good to go

**Comment by ChrisEdS** [comment]
(1) Deleting the background shows weird behaviour

When no background image is set it looks like this:

image

When a background color is set it looks like this:

image

**Comment by ChrisEdS** [comment]
(2) Setup screen needs some adjustments

- Button is not centred
- Border is broken
- User/Password hint is shown twice.

image

**Comment by ChrisEdS** [comment]
(3) When setting a password in setup screen the password indicator is inside the password field

image

**Comment by ChrisEdS** [comment]
(1)(2)(3) Fixed. Sorry caching issue.

**Comment by JanAckermann** [comment]
Somebody unsquashed :)

**Comment by hurradieweltgehtunter** [comment]
@ChrisEdS yould you re-check with errors end customer themes?

**Comment by hurradieweltgehtunter** [comment]
Changes are final, ready to merge.
https://github.com/owncloud/guests/pull/446 needs to be merged too

**Comment by ChrisEdS** [comment]
@hurradieweltgehtunter Please document how the users/customers can theme the new elements. That should be part of the admin release notes as well. // cc @pmaier1

**Comment by JanAckermann** [comment]
@cdamken old version ? invalidate your cache please

**Review by phil-davis — APPROVED** [review]
LGTM. There are 50 commits here, and the rebase process was giving me conflicts...

I squashed all the commits into another branch on  top of current master - see PR #38821 - we could actually merge the code from that PR with a single clean commit. The changelog link could be left as it is, pointing to this PR, because this PR is where all the discussion and history is.

**Pull request closed without merging**
