### PR TITLE
Run API tests by suite

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
- enhance the make-run scripts of the API acceptance tests to allow passing through the Behat suite name to the Behat command
- ~~In Jenkins, split the work into the existing 4 API suites. Jenkins runs them in series, no there is no parallel benefit here. But for the future, when moving them to drone..., the suite-per-job infrastructure is there.~~

## Related Issue
https://github.com/owncloud/QA/issues/517

## Motivation and Context
We want to be able to split the API tests into smaller suites and run them as separate jobs on parallel workers.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
This helps towards 2 things:
- ability to run each suite in parallel
- for when webUI suites get added under the ``acceptance`` folder, we need to be able to run specific suites, so that we can run API and webUI test suites separately (webUI test suites need all the selenium, browser... environment, API tests do not)

**Review by patrickjahns — DISMISSED** [review]
There should be no additions to Jenkins - the test suites should also be here moved to drone

**Comment by phil-davis** [comment]
OK - I will try to do that all in this PR. I was hoping to just add this ability to run individual API acceptance suites, prove it works on Jenkins, then follow up with the change to drone.

**Comment by patrickjahns** [comment]
For drone I'd like to have this first:
https://github.com/owncloud/core/pull/30578

It cleans out double steps and provides one `install-server.sh`

**Comment by patrickjahns** [comment]
Also keep in mind @SergioBertolinSG  has adjusted some steps here https://github.com/owncloud/core/pull/30187 since some api tests failed when run against apache

**Comment by phil-davis** [comment]
I removed the changes to Jenkins. With this PR I really just want the ability to specify a particular suite to the ``behat`` command in ``run.sh``

That gives the possibility for real people, or some other future script... to easily just run a single suite of the API acceptance tests by defining the ``BEHAT_SUITE`` env var.

The fact that we do not use that in the Jenkins CI is bot an issue. It will be easy to use it as/when we move to drone, and as the UI suites move under ``tests/acceptance``

This is just a little enhancement that is orthogonal to drone changes - if I get mixed up in those then it will delay this for xxx amount of time.

Please review again.

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport stable10 #30720

**Pull request merged**
