### PR TITLE
[master] Async put with poll

### PR DESCRIPTION
**Pull request by PVince81**
Master port of https://github.com/owncloud/core/pull/32414 which is a simplified version of https://github.com/owncloud/core/pull/31851 with simple polling.

As we merged it into stable10 we should at least align master to that until we decide what to do with https://github.com/owncloud/core/pull/31851

### CODE REVIEW

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by PVince81** [comment]
@DeepDiver1975 can we merge this to master ? we already have this code on stable10 and 10.0.10 now...

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
