### PR TITLE
Replace deprecated OC_Helper::linkToRoute calls

### PR DESCRIPTION
**Pull request by rullzer**
Just replace it with the body (and suggested replacement) of the call.

Easy one ;)

CC: @MorrisJobke @PVince81 @LukasReschke @nickvergessen

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and code makes sense :+1:

**Comment by rullzer** [comment]
Also removed the private function now to cleanup our code base.

**Comment by MorrisJobke** [comment]
Still :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
