### PR TITLE
Add tests for app management for apps-external path

### LINKED ISSUE #34657: Acceptance tests using pre-installed apps_paths
PR #30889 issue #29839 introduced `apps-external` as a second apps path on a default installation.

- [ ] review existing `appmanagement.feature` scenarios to see if they are still "a good thing"
- [ ] add scenarios to confirm the new default path works
- [ ] whatever else might be useful related to this for testing ;)

### PR DESCRIPTION
**Pull request by skshetry**
## Description

Adds tests for current `apps` vs `apps-external` scenarios.

## Related Issue

- Fixes #34657

## How Has This Been Tested?

- locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by paurakhsharma — COMMENTED** [review]
Looks good to me :+1:

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
o codecove came. @DeepDiver1975 please merge.

**Comment by phil-davis** [comment]
@skshetry when you backport you will get a conflict in https://github.com/owncloud/core/pull/35621/files#diff-fc1ea618b418ebd7f014562bd5d4cce4R24

I cleaned up unused use statements, and the `stable10` backport of that is already merged to `stable10` - PR #35629

**Comment by phil-davis** [comment]
Backport `stable10` #35631

**Pull request merged**
