### PR TITLE
add locks in the scanner to prevent multiple scanners running on the …

### LINKED ISSUE #20555: "Deadlock found when trying to get lock" in file locking
We have a ton of following entries, they appear dozens to hundreds of times per second:

```
{"reqId":"96M5ZtaObvQI\/q+FUTeB","remoteAddr":"93.202.76.110","app":"core","message":"Exception while scanning file \"msrex\/files_versions\/owncloud\/support\/XXXX\/XXXX/XXXX9\": An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/7a4d0ec119d9e99086554694bf6fa2bc\", 1, 1447758814, \"files\\\/7a4d0ec119d9e99086554694bf6fa2bc\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":0,"time":"2015-11-17T10:13:34+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=TOKEN"}
```

@cmonteroluque @karlitschek @PVince81 FYI - this is what is killing S3 right now. I'd vote for priority on this once.
cc @icewind1991 THX!
cc @danimo

### PR DESCRIPTION
**Pull request by icewind1991**
…same files

Fixes #20555

@adamreed90 @BenS89 @pako81 @hostingnuggets can you verify if this fixes the issue for you

cc @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: tested here https://github.com/owncloud/core/issues/20555#issuecomment-213456487 and it solved the problem for me

**Comment by PVince81** [comment]
Retested with the correct transaction modes, still works.

**Comment by PVince81** [comment]
Second review ? @nickvergessen @schiesbn @rullzer @DeepDiver1975

**Comment by rullzer** [comment]
Basically tested the same way as https://github.com/owncloud/core/issues/20555#issuecomment-213456487

:+1:

**Comment by PVince81** [comment]
@karlitschek backport to 9.0.2, 8.2.4 ? (fixes database dead lock with concurrent scanner processes)

**Comment by rullzer** [comment]
Rebased to make github happy after the move to PSR-4

**Comment by karlitschek** [comment]
nice. please backport

**Comment by MorrisJobke** [comment]
> nice. please backport

@icewind1991 Could you please open the backport PRs?

**Comment by PVince81** [comment]
@icewind1991 what happened to the 8.2 backport in the end ? (I know you pushed by mistake, did you revert?)

**Comment by icewind1991** [comment]
> did you revert

Yes

stable9: https://github.com/owncloud/core/issues/24250
stable8.2: https://github.com/owncloud/core/issues/24260

**Pull request merged**
