### PR TITLE
Bring back delete permission in share overview

### LINKED ISSUE #20105: Bring back delete action for "Shared with *" sections
Since the delete action is now in the menu, we can bring it back.

The original reason for removing the trashbin icon was to prevent misunderstand and people mistakenly deleting the folder/file in that section believing it was "unshare". See https://github.com/owncloud/core/issues/11599

Approved by @jancborchardt here https://github.com/owncloud/core/issues/20068#issuecomment-151649613

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/20105

@jancborchardt @MorrisJobke @nickvergessen @rullzer @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

It would be super awesome to have the item labeled "unshare" instead of "delete". ;)

**Comment by PVince81** [comment]
> It would be super awesome to have the item labeled "unshare" instead of "delete"

No because it really is a deletion, the file/folder is completely gone (or moved to trash)

The place where you want "Unshare from self" is in the other section, unrelated to this PR.

**Comment by MorrisJobke** [comment]
> No because it really is a deletion, the file/folder is completely gone (or moved to trash)

Right ... Then here is my :+1: for the actual change. I tested it and it is now there. (I now did a before/after test ;))

:see_no_evil:

**Comment by schiesbn** [comment]
> No because it really is a deletion, the file/folder is completely gone (or moved to trash)
> The place where you want "Unshare from self" is in the other section, unrelated to this PR.

Hm, for to the "share with others" and "share by link" section it makes sense. But for the "shared with you" section the action should be called "unshare" because this is what it does.

**Comment by MorrisJobke** [comment]
> Hm, for to the "share with others" and "share by link" section it makes sense. But for the "shared with you" section the action should be called "unshare" because this is what it does.

Correct, but this PR only fixes the "shared by you" section and this is done just fine ;)

**Comment by schiesbn** [comment]
> Correct, but this PR only fixes the "shared by you" section and this is done just fine ;)

Just double checked it and compared it with master. You are right, share with you already had the "delete" action before. So it is probably a separate issue.

@PVince81 do you prefer if I raise a extra issue for it or do you want to fix it within this PR where you touch the code anyway?

**Comment by PVince81** [comment]
Yes, separate issue please. It used to be called "Unshare from self" but got lost when transitioning to the actions menu. (because it used to be a hack that couldn't be ported). Will need to take some time to find a good solution.

**Comment by schiesbn** [comment]
Separate issue raised here: https://github.com/owncloud/core/issues/20172

:+1: for this PR

**Comment by PVince81** [comment]
Thanks

**Comment by PVince81** [comment]
@MorrisJobke looks like we didn't backport this. It's the PR that brings back the "Delete" action for "Shared with others".

@karlitschek backport to 8.2.2 ?

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/21182

**Comment by karlitschek** [comment]
please backport. :+1:

**Pull request merged**
