### PR TITLE
Fix fileglobalgc unlink parameter warnings

### LINKED ISSUE #14932: fileglobalgc warning
On stable8, repeateadly (when refreshing a s2s folder as recipient)
```
{"reqId":"8506c8202f1e9ba6a95615452b0e5743","remoteAddr":"127.0.0.1","app":"PHP","message":"unlink() expects parameter 2 to be resource, integer given at \/srv\/www\/htdocs\/owncloud\/lib\/private\/cache\/fileglobalgc.php#51","level":0,"time":"2015-03-16T15:45:58+00:00","method":"GET","url":"\/owncloud\/cron.php"}
```

I compared the code of "fileglobalgc" with master and it's the same, so likely to happen there as well.

I haven't been able to reproduce it, and from reading the code I'm not sure what would return an integer instead of an array.

@icewind1991 any idea ?

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
From the documentation (http://php.net/manual/en/function.array-walk.php):

>    Typically, callback takes on two parameters. The array parameter's value being the first, and the key/index second. 
> Many internal functions (for example strtolower()) will throw a warning if more than the expected number of argument are passed in and are not usable directly as a callback. 

`unlink` has an optional second parameter, a resource, which prints a warning when passed an integer as per `array_walk`.

Fixes #14932

@karlitschek This affects stable8, backport?

### CODE REVIEW

**Comment by karlitschek** [comment]
looks fine :+1: @icewind1991 @DeepDiver1975 what do you think?

**Comment by DeepDiver1975** [comment]
looks good - but please add a unit test for the method gc() - we could have detect this years back - THX

**Comment by icewind1991** [comment]
:+1:

**Comment by icewind1991** [comment]
< looks good - but please add a unit test for the method gc() - we could have detect this years back

https://github.com/owncloud/core/blob/master/tests/lib/cache/fileglobalgc.php covers most of the logic

**Comment by DeepDiver1975** [comment]
> https://github.com/owncloud/core/blob/master/tests/lib/cache/fileglobalgc.php covers most of the logic

es - but not the method gc() which is causing this issue

**Comment by Xenopathic** [comment]
@DeepDiver1975 Unit tests implemented :smile:

**Comment by DeepDiver1975** [comment]
THX @Xenopathic

**Pull request merged**
