### PR TITLE
[stable10] Add cascade delete to oc_persistent_locks

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/33771 to stable10

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
@PVince81 no drone job is queued. This will need massaging to make it try again.

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@PVince81 because there are no new commits in ``stable10``, the default rebase is a NOOP.
I have to locally ``git rebase -i stable10``, pretend to reword the commit, exit the editor, ``git push -f``
Then GitHub will try again to trigger CI.
It's a PITA

**Comment by PVince81** [comment]
or we merge a bunch of other PRs then rebase again

**Comment by PVince81** [comment]
rebased again

**Comment by PVince81** [comment]
blocked by https://github.com/owncloud/core/issues/33792

**Comment by individual-it** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
