### PR TITLE
Update phpseclib to v3.0.9

### PR DESCRIPTION
**Pull request by JammingBen**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiSharees-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiAuthOcs-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiShareManagementToRoot-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiComments-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiProvisioning-v2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiAuthWebDav-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiShareCreateSpecialToShares2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiFavorites-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiShareCreateSpecialToRoot2-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiShareOperationsToShares-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingExt1-10.6.0-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingIntGroup2-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingAcceptSh-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiOnSqlite-sqlite-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingExt1-git-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIAdminSettings-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUIRestrictSharing-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Review by phil-davis — APPROVED** [review]
LGTM - I added the dependency bump to the "summary"  dependency changelog. That reduces the amount of "crud" that appears in the release notes.

This "summary"  dependency changelog got the file name that happened "accidentally" because of the PR number of the first dependency bump. We probably should have a nicer convention for naming that, so that people can recognise it in the changelog unreleased folder!

**Comment by phil-davis** [comment]
@JammingBen CI passes. Please click "Ready to Review" and then merge.

**Comment by JammingBen** [comment]
@phil-davis I'm hesitating because of https://github.com/owncloud/enterprise/issues/4595#issuecomment-860526445, but I think the update is a good thing anyway, right?

**Comment by phil-davis** [comment]
> @phil-davis I'm hesitating because of [owncloud/enterprise#4595 (comment)](https://github.com/owncloud/enterprise/issues/4595#issuecomment-860526445), but I think the update is a good thing anyway, right?

CI passes, so there is no nasty regression. We should do this update. And then if another update happens overnight, we do that also.

**Pull request merged**
