### PR TITLE
[3rdparty] Bump phpseclib to 2.0.1

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/257
Blocked by: https://github.com/owncloud/core/pull/23255

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:boom:

**Comment by rullzer** [comment]
@LukasReschke mind taking a look? It seems a bit :fish:-y that a minor update of phpseclib crashes the integrity check.

**Comment by rullzer** [comment]
Blocked by https://github.com/owncloud/core/pull/23255 will rebase all soon

**Comment by rullzer** [comment]
Ok this breaks stuff.. and need a rebase in 3rdparty. I'm closing this... and will reopen once @LukasReschke has had a look.

**Pull request closed without merging**
