### PR TITLE
objectids for tags and comment are strings

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
The object ids changed in the PR are stored as strings in the DB, but ownCloud tries to store them as int.

## Related Issue
No issue opened
https://central.owncloud.org/t/php-7-4-18-breaking-owncloud-10-6-wih-postgresql-9-6-on-centos-7/31933

## Motivation and Context
Fixed bug in php caused a problem on our side.

## How Has This Been Tested?
Manually checked with postgresql 9.2 and php 7.4.18
**NOT** tested with other DBs yet.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
I restarted the Merge CI here: https://drone.owncloud.com/owncloud-ci/php/482
That should publish new `owncloudci/php` docker images that have the latest PHP 7.*.* patch releases.
Then I can run some CI against current core master with various databases to see if the unit or acceptance tests find this problem.

**Comment by mherrb** [comment]
Hi, I can confirm that this patch fixes the issue on my system.
Thanks for the help.

**Comment by srcr** [comment]
I was running into the same issue on my Owncloud instance. running on FreeBSD, PostgreSQL 9.6.21 and PHP 7.4.18.
I did the fix manually and I can get to my files again. thanks for this fix hope this will get merged.

**Comment by phil-davis** [comment]
I tried to see if this bug is found by CI - PR #38685 - but no joy.
Can someone post a sequence of actions (curl requests to the API, or webUI actions) that would make this bug happen.

**Review by VicDeo — APPROVED** [review]
:+1:

**Comment by VicDeo** [comment]
@phil-davis  I guess it needs the exact pgsql driver shipped with PHP 7.4.18 (version released on 29 April 2021)

**Review by JammingBen — APPROVED** [review]

**Pull request merged**
