### PR TITLE
Update google-api-php-client to 1.1.7

### PR DESCRIPTION
**Pull request by PVince81**
Continuing Google lib update from https://github.com/owncloud/core/pull/24516 from @altyr

Also fixed autoloader issue.

### CODE REVIEW

**Comment by PVince81** [comment]
@owncloud-bot license was stated as MIT here https://github.com/owncloud/core/pull/24516#issue-153791104

**Comment by PVince81** [comment]
Unit test results:
```
Runtime:       PHP 5.6.21 with Xdebug 2.3.3
Configuration: /srv/www/htdocs/owncloud/tests/phpunit-autotest.xml

............................................F..............F..F.. 65 / 80 ( 81%)
FF..F..........                                                   80 / 80 (100%)

Time: 8.66 minutes, Memory: 62.50Mb

There were 6 failures:

1) OCA\Files_External\Tests\Storage\GoogleTest::testStat
Failed asserting that false is true.

/srv/www/htdocs/owncloud/tests/lib/Files/Storage/Storage.php:288

2) OCA\Files_External\Tests\Storage\GoogleTest::testRenameOverWriteDirectory
target/test1.txt has not been overwritten
Failed asserting that false matches expected 'foo'.

/srv/www/htdocs/owncloud/tests/lib/Files/Storage/Storage.php:489

3) OCA\Files_External\Tests\Storage\GoogleTest::testCopyOverWriteDirectory
Failed asserting that true is false.

/srv/www/htdocs/owncloud/tests/lib/Files/Storage/Storage.php:540

4) OCA\Files_External\Tests\Storage\GoogleTest::testCopyFromSameStorage with data set #0 ('/source.txt', '/target.txt')
Expected /target.txt to be a copy of /srv/www/htdocs/owncloud/tests/data/lorem.txt
Failed asserting that false matches expected 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'.

/srv/www/htdocs/owncloud/tests/lib/Files/Storage/Storage.php:196
/srv/www/htdocs/owncloud/tests/lib/Files/Storage/Storage.php:570

5) OCA\Files_External\Tests\Storage\GoogleTest::testCopyFromSameStorage with data set #1 ('/source.txt', '/target with space.txt')
Expected /target with space.txt to be a copy of /srv/www/htdocs/owncloud/tests/data/lorem.txt
Failed asserting that false matches expected 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'.

/srv/www/htdocs/owncloud/tests/lib/Files/Storage/Storage.php:196
/srv/www/htdocs/owncloud/tests/lib/Files/Storage/Storage.php:570

6) OCA\Files_External\Tests\Storage\GoogleTest::testCopyFromSameStorage with data set #4 ('/source.txt', '/tärgét.txt')
Expected /tärgét.txt to be a copy of /srv/www/htdocs/owncloud/tests/data/lorem.txt
Failed asserting that false matches expected 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'.

/srv/www/htdocs/owncloud/tests/lib/Files/Storage/Storage.php:196
/srv/www/htdocs/owncloud/tests/lib/Files/Storage/Storage.php:570

FAILURES!
Tests: 80, Assertions: 409, Failures: 6.
```

Even less failures than before, nice! https://github.com/owncloud/core/issues/22481
Failures are expected, will need fixing the copy operation separately anyway.

Will do some manual regression testing.

**Comment by altyr** [comment]
Such a clean fix, I wasn't aware the autoloader was required in more places. Learned something again.

And the bot is going to haunt me forever, isn't it.

**Comment by PVince81** [comment]
Upload/download of big files (video) also still works and so are many file operations.
Google docs file can still be downloaded as ODT.

Looks good :+1: 

Second review @Xenopathic @LukasReschke @icewind1991

**Comment by PVince81** [comment]
@altyr sorry about the clumsy bot...
I just rebased to solve conflicts

**Comment by PVince81** [comment]
annnnd rebased again because master had files_external completely broken... works again now

**Comment by icewind1991** [comment]
Fixed the path to the cert bundle, I now get the same test results as @PVince81 

I suspect most of the failing tests are related to caching since when I manually check the resulting files/folders in drive everything seems fine

:+1:

**Comment by PVince81** [comment]
@icewind1991 thanks!

**Pull request merged**
