### PR TITLE
[stable10] Check for delete permission in CopyPlugin to stay compliant

### PR DESCRIPTION
**Pull request by PVince81**
## Description
The old permission requirement requires delete permission to be granted
to allow copy because it used to be delete + overwrite.

This PR aligns the new code with this old behavior to prevent breaking
expectations.

## Related Issue
Fixes https://github.com/owncloud/core/issues/31789

## Motivation and Context
Align with old expectation.
We can discuss later if we want to change expectations, which would trigger release notes.

## How Has This Been Tested?
- Unit test
- smashbox test `bin/smash lib/oc-tests/test_sharePermissions.py -t 6`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes. (+ bonus tests!)
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] clarify whether restoring a version also requires delete permission
    - [ ] check old behavior in 10.0.8
    - [ ] align with old behavior if applicable
    - [ ] check/add acceptance test exists for this @phil-davis

**Comment by PVince81** [comment]
Version restoration doesn't require delete permission, it didn't in the past. Let's keep the same behavior, this PR leaves this untouched. See https://github.com/owncloud/core/issues/31789#issuecomment-397575330

@DeepDiver1975 please review

**Review by DeepDiver1975 — COMMENTED** [review]
looks good

**Comment by DeepDiver1975** [comment]
@mrow4a can you throw smashbix on this? THX

smashit

**Comment by PVince81** [comment]
broke...

```
SUMMARY:smash.:running lib/oc-tests/test_sharePermissions.py in /home/vincent/work/smashdir/test_sharePermissions as test testset #12 {'use_new_dav_endpoint': False, 'sharePermissions_matrix': {'allowed_operations': ['upload', 'move_in', 'move_in_overwrite', 'move_in_subdir', 'move_in_subdir_overwrite', 'move_out', 'move_out_subdir', 'copy_in', 'copy_in_overwrite', 'delete', 'mkdir', 'rmdir'], 'permission': 13}}
2018-06-15 17:19:42,341 - ERROR - recipient_worker - Operation "copy_in_overwrite" must be allowed when share permissions are 13 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/vincent/work/workspace/smashbox/lib/oc-tests/test_sharePermissions.py" at line 406]
2018-06-15 17:19:45,390 - ERROR - recipient_worker - 1 error(s) reported
SUMMARY:smash.:Elapsed time: 42s (0:00:42.742015)
CRITICAL:smash.:Aborting run -- non-zero exit code (2)
```

**Comment by PVince81** [comment]
Instead of trying to replicate the old behavior, let's simply fall back to the old implementation when not dealing with versions (which are the only ones that implement ICopySource).

Obsoleted by https://github.com/owncloud/core/pull/31805

**Pull request closed without merging**
