### PR TITLE
Welcome 2018

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Update ownCloud copyright year to 2018
2) Standardize some other copyright line formats that were noticed in regexing for this stuff

## Related Issue
#29998 

## Motivation and Context
Fulfill New Year's resolution

## How Has This Been Tested?
CI will know

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: last 2017's effort was #27141

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
@DeepDiver1975 do we backport this so that the copyright year is bumped for 10.0.* releases?
Or care factor low?

**Comment by DeepDiver1975** [comment]
No idea if backporting will help - maybe *just* reapply all the regex to stable10?

**Comment by phil-davis** [comment]
Backport with similar but different set of files touched in stable10 #30056

**Pull request merged**
