### PR TITLE
[stable8] Use oracle docker for ci with stable8

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
unit test failing on sqlite

@schiesbn @rullzer mind taking a look? THX

````
05:32:33 There was 1 error:
05:32:33 
05:32:33 1) OCA\Files_Encryption\Tests\Share::testRemoteShareFile
05:32:33 Exception: Sharing 1142 failed, could not find user1@server1, maybe the server is currently unreachable.
05:32:33 
05:32:33 /var/lib/jenkins/jenkins-slave/workspace/core-ci-linux@3/database/sqlite/label/SLAVE/lib/private/share/share.php:748
05:32:33 /var/lib/jenkins/jenkins-slave/workspace/core-ci-linux@3/database/sqlite/label/SLAVE/lib/public/share.php:236
05:32:33 /var/lib/jenkins/jenkins-slave/workspace/core-ci-linux@3/database/sqlite/label/SLAVE/apps/files_encryption/tests/share.php:643

**Comment by MorrisJobke** [comment]
There is no OCI job :(

**Comment by PVince81** [comment]
Rebased to wake the CI sleeper

**Comment by PVince81** [comment]
```
07:19:44 							Oracle connection could not be established				<span class='hint'>ORA-12541: TNS:no listener Check environment: ORACLE_HOME=/usr/lib/oracle/12.1/client64 ORACLE_SID= LD_LIBRARY_PATH= NLS_LANG= tnsnames.ora is not readable</span>
```

**Comment by PVince81** [comment]
@DeepDiver1975 continue fighting or move to next maintenance ?

**Comment by DeepDiver1975** [comment]
:boom:

**Comment by DeepDiver1975** [comment]
oracle is green -> merge

**Pull request merged**
