### PR TITLE
Update phpseclib/phpseclib from 2.0.30 to 3.0.3

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
This is a rebase of #38435 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
@micbar this is a current version of this code. Please ask whoever is appropriate to review etc.

**Comment by phil-davis** [comment]
I notriced that the PR link in the changelog is now out-of-date. And there are 6 commits here. So I made a new squashed PR #38454 with updated changelog.

**Review by JammingBen — APPROVED** [review]
LGTM, seem to be the exact changes I previously did on this.

**Comment by phil-davis** [comment]
> LGTM, seem to be the exact changes I previously did on this.

Yes, "something happened" (tm) to the original dependabot PR. This is a rebased version of exactly the code.

I adjusted the PR number in the changelog just now, and squashed the commits. IMO this can be merged when CI finishes.

**Pull request merged**
