### PR TITLE
Introducing CalDAV into core

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Please test!

@LukasReschke @MorrisJobke @georgehrke @karlitschek for iCAL and IOS integration
@jancborchardt for gnome and android integration
@blizzz for jolla and KDE integration
@jakobsack @icewind1991 you are my Windows phone test dummies - THX

**Comment by icewind1991** [comment]
> @icewind1991 you are my Windows phone test dummies

No longer have one, switched to an even more obscure OS :)

Will tests for Jolla instead

**Comment by DeepDiver1975** [comment]
> No longer have one, switched to an even more obscure OS :)
> 
> Will tests for Jolla instead

Fine as well - THX a lot!

**Comment by icewind1991** [comment]
How do I add a calendar to test with?

**Comment by DeepDiver1975** [comment]
> How do I add a calendar to test with?

Will add a occ command :see_no_evil:

**Comment by DeepDiver1975** [comment]
@icewind1991 occ command added

**Comment by icewind1991** [comment]
[ ] No display name set for calendars added from occ

**Comment by icewind1991** [comment]
- [ ] 403 error when trying to add an event in korganizer, nothing added to the db

```
::1 - icewind [16/Nov/2015:16:45:47 +0100] "PUT /owncloud/remote.php/dav/calendars/icewind/Test/1447688747.R308.ics HTTP/1.1" 403 346 "-" "Mozilla/5.0 (X11; Linux x86_64) KHTML/5.15.0 (like Gecko) Konqueror/5.15"
```

**Comment by DeepDiver1975** [comment]
thx for testing @icewind1991

**Comment by DeepDiver1975** [comment]
Do we want to test this on a publicly available server?

@icewind1991 @blizzz @jancborchardt @schiesbn ?

**Comment by DeepDiver1975** [comment]
> Do we want to test this on a publicly available server?
> 
> @icewind1991 @blizzz @jancborchardt @schiesbn ?

I have a publicly availble server for testing - ping me to more ...

**Comment by icewind1991** [comment]
- [ ] normalize uri's for added calendars

**Comment by icewind1991** [comment]
Seems to work fine with syncing between kde, android (caldav-sync from the store) and jolla.

For kde and android `/owncloud/remote.php/dav` seem to be enough for it to detect the calendars, for jolla I needed to enter the full `/owncloud/remote.php/dav/calendars/icewind`

**Comment by DeepDiver1975** [comment]
> The uri should only contain lower-case alphanumeric characters and underscores, if a user creates a calendar with things like spaces or parenthesis in the name they should be removed from the uri.

this seems to be a issue for the console command only - will add this to the meta issue - THX

**Comment by raimund-schluessler** [comment]
@DeepDiver1975 Is there something like a guide what has to be done to migrate an existing app (https://github.com/owncloud/tasks/issues/280) to the new CalDAV endpoint?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Is there something like a guide what has to be done to migrate an existing app (owncloud/tasks#280) to the new CalDAV endpoint?

good point - @Henni is driving the pilot on pure js integration with CardDAV - so any results/findings should apply to CalDAV as well

@Henni looks like we have to collect all your knowledge - wana write a blog?
@jospoortvliet ^^^

**Comment by Henni** [comment]
@DeepDiver1975 I would love to write some stuff up, when I find the time.
But as I am part of the tasks team, I can help there directly.

**Comment by jakobsack** [comment]
@DeepDiver1975 will test later today

**Comment by jakobsack** [comment]
:+1: Works with both Windows Phone 8.1 and Windows 10 (for PC).

It seems like Windows 10 does not read the calendar entries created with Windows Phone but maybe I did not wait long enough. KDE shows the entries from contacts and calendar correctly.

**Comment by georgehrke** [comment]
OS X doesn't work, probably due to the missing principals:
```
dav:/remote.php/dav/principals/admin/> ls
Listing collection `/remote.php/dav/principals/admin/': succeeded.
Error: calendar-proxy-read            404 Not Found
Error: calendar-proxy-write           404 Not Found
```

**Comment by DeepDiver1975** [comment]
thx @georgehrke I'll have a look

**Comment by DeepDiver1975** [comment]
> OS X doesn't work, probably due to the missing principals:

@georgehrke does this work in the 'old' calendar?

**Comment by georgehrke** [comment]
> @georgehrke does this work in the 'old' calendar?

Strange, it doesn't work with 8.1 or 8.2 neither.

**Comment by georgehrke** [comment]
It works if I choose the account type `advanced` and enter everything (even server path) on my own. If I choose the account type `manual` it gives me: ``Unable to verify account name or password``.

I will take a look at the access.log to see the difference.

**Comment by DeepDiver1975** [comment]
> It works if I choose the account type advanced and enter everything (even server path) on my own. If I choose the account type manual it gives me: Unable to verify account name or password.

maybe this is not working because of missing .well-known ???

**Comment by georgehrke** [comment]
It's using the old well-known, even though I entered the entire url (`http://owncloud.dev/remote.php/dav/principals/admin`). GRMPF

Manual:
```
192.168.56.1 - - [18/Nov/2015:15:23:47 +0000] "PROPFIND /.well-known/caldav HTTP/1.1" 301 246 "-" "Mac+OS+X/10.11.1 (15B42) accountsd/113"
192.168.56.1 - - [18/Nov/2015:15:23:47 +0000] "PROPFIND /remote.php/caldav/ HTTP/1.1" 500 - "-" "Mac+OS+X/10.11.1 (15B42) accountsd/113"
192.168.56.1 - - [18/Nov/2015:15:23:47 +0000] "PROPFIND / HTTP/1.1" 405 - "-" "Mac+OS+X/10.11.1 (15B42) accountsd/113"
192.168.56.1 - - [18/Nov/2015:15:23:47 +0000] "PROPFIND /caldav/v2 HTTP/1.1" 405 235 "-" "Mac+OS+X/10.11.1 (15B42) accountsd/113"
192.168.56.1 - - [18/Nov/2015:15:23:47 +0000] "PROPFIND /principals/users/admin/ HTTP/1.1" 405 249 "-" "Mac+OS+X/10.11.1 (15B42) accountsd/113"
...
```

Advanced:
```
192.168.56.1 - - [18/Nov/2015:15:25:02 +0000] "PROPFIND /remote.php/dav/principals/admin HTTP/1.1" 401 242 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
192.168.56.1 - - [18/Nov/2015:15:25:03 +0000] "PROPFIND /remote.php/dav/principals/admin HTTP/1.1" 207 484 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
192.168.56.1 - - [18/Nov/2015:15:25:03 +0000] "PROPFIND /remote.php/dav/principals/admin/ HTTP/1.1" 207 1715 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
192.168.56.1 - - [18/Nov/2015:15:25:03 +0000] "OPTIONS /remote.php/dav/principals/admin/ HTTP/1.1" 200 - "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
...
```

**Comment by DeepDiver1975** [comment]
> It's using the old well-known,

we need to adopt .well-known

**Comment by georgehrke** [comment]
So it would probably help to update our htaccess
https://github.com/owncloud/core/blob/master/.htaccess#L42

**Comment by DeepDiver1975** [comment]
> So it would probably help to update our htaccess
> https://github.com/owncloud/core/blob/master/.htaccess#L42

for sure - already in the meta-issue

**Comment by DeepDiver1975** [comment]
does ical work besides the initial lookup?

**Comment by georgehrke** [comment]
> does ical work besides the initial lookup?

Looks good so far.
:+1:

**Comment by jospoortvliet** [comment]
@Henni dude ping me about a blog, I do think this would be nice to talk about. Cool stuff ;-)

**Pull request merged**
