### PR TITLE
[tests-only] [full-ci] Split cliFilesExternal into 2 pipelines

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
The `cliFilesExternal` pipeline runs the CLI test scenarios that need the files_external app. There are currently 110 scenarios that take about 40 minutes. That is the longest pipeline in the core CI, and it is slowing down the ability to get a CI result.

Example: https://drone.owncloud.com/owncloud/core/35570/120/14
```
runsh: Total 110 scenarios (110 passed, 0 failed)
runsh: Exit code of main run: 0
```

1) Split this into 2 pipelines.

2) `cliLocalStorage` suite is too big. Move "create local storage" test scenarios out of `cliLocalStorage` and into a new test suite `cliCreateLocalStorage`

3) Rename cliAppManagement to cliManageApps - there happen to be 10 cli acceptance test suites. When split into 2 parts, the first 5 suites (alphabetically) are run in the first pipeline. Changing this suite name moves it into the 2nd pipeline and the number of scenarios in each pipeline is more balanced. (this was an easy way to achieve a reasonable result! Otherwise, we would have to have code that analyzes the number of scenarios in each suite when splitting a list of suites into parts - that would take a lot of effort and we don't need to do that for 95% of the usages of the suite-list-splitting that we do.)

4) Split and/or balance other acceptance test suites to balance the run times. See comment https://github.com/owncloud/core/pull/40041#issuecomment-1116939351

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

### CODE REVIEW

**Comment by phil-davis** [comment]
First pipeline: https://drone.owncloud.com/owncloud/core/35575/120/13
only 20 scenarios actually matched.

**Comment by phil-davis** [comment]
Second pipeline: https://drone.owncloud.com/owncloud/core/35575/121/13
`runsh: Total 90 scenarios (90 passed, 0 failed)`

The `cliLocalStorage` suite already has `86 scenarios (86 passed)` - so splitting into more pipelines can only get to a minimum of 86 scenarios in a single pipeline. That took 29m46.83s to run.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/35579/122/13
runsh: Total 83 scenarios (83 passed, 0 failed)

still too many - I will look at which test suites now end up in which pipeline.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/35590/121/13
runsh: Total 47 scenarios (47 passed, 0 failed)
25 minutes

https://drone.owncloud.com/owncloud/core/35590/122/13
runsh: Total 63 scenarios (63 passed, 0 failed)
35 minutes

**Review by individual-it — APPROVED** [review]

**Pull request merged**
