### PR TITLE
[WIP] Display an overlay on drop area. Implements #10369

### PR DESCRIPTION
**Pull request by vgezer**
Basically displays a div with a border around.
Needed to change drop event a little bit since there is
an issue with the sidebar if only `$(document)` is used.

Do not merge yet! On mobile, the overlay does not cover all list.

@owncloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
@vgezer any update on this?

**Comment by th3fallen** [comment]
@owncloud-bot retest this please

**Comment by vgezer** [comment]
@jancborchardt Hi, unfortunately I am currently quite busy with my tasks at work and this will be delayed. If anyone wants to take it, please feel free.

**Comment by PVince81** [comment]
@vgezer are you interested in continuing this for 8.2 ?

**Comment by vgezer** [comment]
Hi @PVince81, Unfortunately I have a failing HDD, therefore do not have a development environment. Is that possible to keep the branch intact?

**Comment by jancborchardt** [comment]
@vgezer yeah, the branch will just stay here with your work. :) You can continue any time you want.

**Comment by PVince81** [comment]
@vgezer any update ? Needs rebase, also see outstanding comments

**Comment by PVince81** [comment]
@vgezer if you're not interested in continuing, feel free to close it :smile:

**Comment by vgezer** [comment]
I will do that later :)

**Pull request closed without merging**
