### PR TITLE
cache the source cache of a share

### PR DESCRIPTION
**Pull request by icewind1991**
Dont do the same work over and over again

[comparison](https://blackfire.io/profiles/compare/c523fabc-77f7-4d18-948a-5b0bde282f46/graph)

cc @DeepDiver1975 @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by MorrisJobke** [comment]
16 broken tests ;)

**Comment by PVince81** [comment]
Nice, I remember noticing this potential performance issue.

**Comment by icewind1991** [comment]
This doesn't really work due to the way a single shared storage can map to multiple source storages atm.

#12086 is needed to do things like this properly

**Comment by PVince81** [comment]
Right. Switching back to "To develop" then.

**Comment by PVince81** [comment]
- [ ] requires https://github.com/owncloud/core/pull/12086

**Comment by PVince81** [comment]
Is this still valid ?

**Comment by icewind1991** [comment]
#12086 will fix this

**Pull request closed without merging**
