### PR TITLE
External files oauth callback url should include settings sectionid

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
appended `?sectionid=storage` to the callback urls to ensure they are hooked up correctly on return to OC.

## Related Issue
https://github.com/owncloud/core/issues/27456

## How Has This Been Tested?
 - Setup oauth with google
 - Tested was brokne
 - Implemented fix
 - Works, without alteration to google credentials / callback URI settings

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by davitol** [comment]
@tomneedham applying this patch and granting credentials to googleDrive mount:

```
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://myserverurl.com/index.php/index.php/settings/admin?sectionid=storage, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/XXXXXXX to update the authorized redirect URIs.
```

I think index.php/index.php/  should not be repeated in the URI requested


OOTH I added http://myserverurl.com/index.php/index.php/settings/admin?sectionid=storage and it didn't work too.

**Comment by tomneedham** [comment]
Hmm ok this is good testing, I think I can remove the OC.generateURL() wrapper as this can add in the additional index.php in some environments

**Comment by tomneedham** [comment]
Please retest @davitol

**Comment by davitol** [comment]
@tomneedham tested and works 👍

**Comment by tomneedham** [comment]
Can @davicente also test this?

**Comment by tomneedham** [comment]
@davitol Are you able to test an oauth1 option as well, since this also had to have modifications to teh redirction code

**Comment by davitol** [comment]
> @davitol Are you able to test an oauth1 option as well, since this also had to have modifications to teh redirction code

Tested with DropBox with oauth1 and it works fine :1st_place_medal:

**Comment by davicente** [comment]
OneDrive doesn't allow to set the callback url associated to the application with query parameters (see image). 
I have tested without the query parameter, but sending the complete url (with query parameters) in the authorization request and I have got a token. I think OneDrive just check the callback is the same until path (no params), and it works because of that. 
I'll do more tests just in case. 

image

**Comment by tomneedham** [comment]
So does this work or not? Sorry I don't understand the conclusion of your comment.

**Comment by tomneedham** [comment]
We could always make the core files_external app have its own controller which receives oauth callbacks, does its stuff then pushes the user to the settings panel.

**Comment by tomneedham** [comment]
But this PR is more about providing backwards compatibility after the settings panel changes.

**Comment by PVince81** [comment]
> core files_external app

Yes, have a unique url that contains the mount config id inside (without query parameters) ?

Note that files_external will die in the long term so that route would be better to have in core eventually.

**Comment by PVince81** [comment]
@tomneedham I think we missed an opportunity here to use proper routing.

Basically instead of having `?sectionid=xx` we could have appended the section name directly in the URL: "settings/$sectionid"

**Comment by tomneedham** [comment]
> @tomneedham I think we missed an opportunity here to use proper routing.

Yep, that is becoming more obvious. However, there would be a ton of routing collisions which is why I went for this first. Core settings apps use /settings/$something in a lot of places so that huge PR would have broken lots more than it did already -.-

**Comment by PVince81** [comment]
Fine for the short term, but we'll need a good solution that works with url args as well: https://github.com/owncloud/core/issues/27543

**Comment by PVince81** [comment]
@davicente did you try url-encoding the question mark ? maybe that works...


PR is fine, merging

**Comment by davicente** [comment]
@PVince81 @tomneedham It seems to work without the query parameters. I think is enough right now :)

**Pull request merged**
