### PR TITLE
[tests-only] add 'Z' for the expected webdav permission when testing with oCIS

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
Update the expected permissions on the merge share scenario `Merging shares for recipient when shared from inside with group with less permissions`.

## Related Issue

- Part of https://github.com/owncloud/ocis/issues/4929

## How Has This Been Tested?

- :robot:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

---
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Comment by micbar** [comment]
Awesome, thanks!

**Review by grgprarup — COMMENTED** [review]
lgtm

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@kiranparajuli589 oe @grgprarup do you have time to make an oCIS and reva PRs to update the core commit id to include this?

**Comment by kiranparajuli589** [comment]
> @kiranparajuli589 oe @grgprarup do you have time to make an oCIS and reva PRs to update the core commit id to include this?

sure @phil-davis, there may be some ongoing bumping PRs. I will check and do the update if still necessary.

**Comment by phil-davis** [comment]
core commit id bumps have been done

**Pull request merged**
