### PR TITLE
Merge back 10.5.0 20200703

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Merge back the current diffs between `release-10.5.0` and `master` to `master`

Then we can delete the `release-10.5.0` branch that was used for making `10.5.0RC3` and when we are ready we can branch again from `master1` before creating RC4.

This will allow us to easily include various stuff like Transifex translation commits that are in `master` and would otherwise need to be backported...

To make this PR I did:
```
git fetch origin
git checkout master
git pull
git checkout release-10.5.0
git pull
git checkout -b merge-back-10.5.0-20200703
git rebase master
First, rewinding head to replay your work on top of it...
Applying: Prepare 10.5.0 changelog
Applying: Bump version in version.php
Applying: Update icewind/smb v3.2.4 and other files_external/3rdparty dependencies
Applying: Bump icewind/smb 3.2.5 and google/apiclient 2.5.0
Applying: Updating google/apiclient-services (v0.138 => v0.139) in apps/files_external/3rdparty
Applying: Bump version in version.php
```

And it happily did the rebase without any conflicts, and ended up with just a reasonable set of commits that are the things from `release-10.5.0` that are not already in `master`. i.e. the `icewind/smb` version bumps, ownCloud changelog, and ownCloud RC version bumps.

2020-07-06PM - rebased to latest master and added the commits from the new tip of `release-10.5.0` (from PR #37654 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
@micbar merge-back is ready if you would like to do that.

**Comment by phil-davis** [comment]
@micbar do this merge-back?

**Comment by micbar** [comment]
@phil-davis We need to merge the other branch.
There were additions to the branch.

**Comment by phil-davis** [comment]
@micbar I updated this branch already from the latest on `release-10.5.0` branch.

**Comment by phil-davis** [comment]
> @phil-davis We need to merge the other branch.
> There were additions to the branch.

Note: `release-10.5.0` does not merge "automagically", GitHub claims that there are conflicts. We have to do something like this to merge the content (or someone with privs has to do a rebase of `release-10.5.0` and force-push it, which seems more risky to me)

**Comment by phil-davis** [comment]
@micbar I rebased to get fresh CI against latest master.
Are we going ahead and doing this?
Please review.

**Review by micbar — APPROVED** [review]

**Pull request merged**
