### PR TITLE
[Tests-Only] Add acceptance tests for sharees min search length

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Add acceptance test for limit user search min length 

## Related Issue

- Tests for https://github.com/owncloud/core/pull/38489

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by C0rby — APPROVED** [review]
Looks good to me. :+1:

**Comment by individual-it** [comment]
some tests fail
image

**Comment by phil-davis** [comment]
I guess that this commit should be added on top of #38489 and the test scenarios will pass?

**Comment by micbar** [comment]
please rebase. #38489 was merged.

**Comment by dpakach** [comment]
New issue opened in https://github.com/owncloud/core/issues/38501

**Pull request merged**
