### PR TITLE
[stable10] Bump paragonie/random_compat v2.0.17 => v2.0.18

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
```
composer update paragonie/random_compat
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating paragonie/random_compat (v2.0.17 => v2.0.18): Loading from cache
```
https://github.com/paragonie/random_compat/releases/tag/v2.0.18

Note: this dependency works differently in ``master`` and does not need a version bump.

## Motivation and Context
Keep dependencies up-to-date

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
what is special about this PR. drone has twice got https://drone.owncloud.com/owncloud/core/13998/168
``Segmentation fault (core dumped) $phpunit_cmd``

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by individual-it — APPROVED** [review]

**Pull request merged**
