### PR TITLE
ignore any clover.xml - which is generated by some phpunit calls

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@MorrisJobke @blizzz @schiesbn @icewind1991 @PVince81 THX

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by nickvergessen** [comment]
Same for `tests/coverage*` ?

:+1:

**Comment by DeepDiver1975** [comment]
> Same for tests/coverage* ?

https://github.com/owncloud/core/blob/gitignore-clover.xml/.gitignore#L110

**Comment by blizzz** [comment]
:+1:

**Comment by nickvergessen** [comment]
@DeepDiver1975 
> https://github.com/owncloud/core/blob/gitignore-clover.xml/.gitignore#L110

The leading `/` means its not anywhere, but on this full path.

**Pull request merged**
