### PR TITLE
Removemount expects absolutePath

### PR DESCRIPTION
**Pull request by rullzer**
Simple one liner...
~~No tests :(~~

CC: @icewind1991 @LukasReschke @PVince81 @MorrisJobke @nickvergessen

### CODE REVIEW

**Comment by icewind1991** [comment]
> No tests :(

Your time to shine :)

**Comment by rullzer** [comment]
> > No tests :(

> Your time to shine :)

yeah fair enough.. I'll look into it

**Comment by rullzer** [comment]
Pff we need way more tests for that part of the code ;)
But there is a start.

**Comment by MorrisJobke** [comment]
@icewind1991 Can you please review this? Thanks :)

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by MorrisJobke** [comment]
I did some basic tests. Still works :+1:

**Comment by MorrisJobke** [comment]
@butonic @icewind1991 @DeepDiver1975 Please merge

**Pull request merged**
