### PR TITLE
[do not merge] Bump phpunit 8

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
See if this will help with reliable exit codes.
Note: we cannot do this yet "for real" because PHPUnit8 is only supported on PHP 7.2+

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
To automatically change `expectedException` annotations to `setExpectedException()` calls use like:
```
./vendor-bin/owncloud-codestyle/vendor/bin/php-cs-fixer fix apps --allow-risky=yes --rules='php_unit_no_expectation_annotation'
```

**Comment by DeepDiver1975** [comment]
I suggest to hold the horses With such Changes. This will be relevant in 6 month or later

**Comment by phil-davis** [comment]
Yes, I did this a while ago when investigating `phpunit` exit code problems. It only takes a few minutes to rebase and keep it up-to-date.

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
