### PR TITLE
Add OCS API to send, get, accept and decline remote shares

### LINKED ISSUE #13627: Add Share API calls to automatically mount remote shares
Use cases:
- a user wants to accept a server to server share over the Android app
- trigger a server to server share invite over the Android app
- automated tests that automatically setup two servers and automatically mounts server to server shares

@schiesbn some of them might already be possible, but I remember you said some still need to be covered.

The Share API should be extended to support these cases:
- share file/folder with external user (might work with shareType = 4?)
- mount "link" share
- mount/accept "remote" share

CC @jnfrmarks will be of interest for automated tests

### PR DESCRIPTION
**Pull request by nickvergessen**
This is required so we can manage remote shares via the pyoc client for smashbox

Replace #14668
Fix #13627

### CODE REVIEW

**Comment by karlitschek** [comment]
super cool!!! :+1:

**Comment by nickvergessen** [comment]
@schiesbn mind having a look at the URL and stuff? Thanks

**Comment by schiesbn** [comment]
looks good :+1:

**Comment by nickvergessen** [comment]
@rullzer are you okay with the direction as well? I want to get this in, as soon as 8.1 is out, so we can have all the smashbox tests with server2server share from the beginning of the 8.2 dev cycle

**Comment by rullzer** [comment]
Yep looking good! :+1:

**Comment by rullzer** [comment]
Rebase of course ;)

**Comment by nickvergessen** [comment]
rebased cleanly
no idea what was wrong that it couldn't be merged before.

**Comment by rullzer** [comment]
Would it be possible to add some tests here?
Maybe just inject some stuff in the database and see if this retrieves it clearly etc..

**Comment by nickvergessen** [comment]
Well the methods are tested in https://github.com/owncloud/core/blob/master/apps/files_sharing/tests/external/managertest.php ;)

**Comment by rullzer** [comment]
Ah great! Lets merge this baby then, so smashbox can do its thing and break ;)

**Comment by PVince81** [comment]
@nickvergessen Do we want to backport this ?

**Comment by nickvergessen** [comment]
No, if so we should have merged it before the release.. this is a new feature

**Comment by PVince81** [comment]
Fine by me, makes sense.

**Comment by jnfrmarks** [comment]
@nickvergessen 

Is there any doc for the new apis?

**Comment by nickvergessen** [comment]
It's OCS, what doc do you need? the URLs or what?

If you can point me to other OCS api docs I can prepare a PR

**Comment by jnfrmarks** [comment]
Are there new apis to support the remote shares or is this change an extension of the existing api?

**Comment by PVince81** [comment]
The OCS docs for sharing are here: https://github.com/owncloud/documentation/blob/master/developer_manual/core/ocs-share-api.rst

So I guess you could update them ?

**Comment by nickvergessen** [comment]
@jnfrmarks this just adds a non-UI way for remote shares, so we can use them in smashbox to test federated cloud sharing

**Comment by nickvergessen** [comment]
Documentation PR at https://github.com/owncloud/documentation/pull/1329

Feel free to review

**Pull request merged**
