### PR TITLE
added configuration option for Log in dialog

### PR DESCRIPTION
**Pull request by EtlamGit**
Based on the discussion in issue #18940 and many others I decided to test an implementation of an easy changeable Log in dialog:
People that like the new simplistic design with the embedded button in the password form can keep it without doing anything. But others that have usability problems without a separated button can set a simple configuration string in config.php and get the button back. They can also decide to keep the embedded button or to remove it.

As these are my first lines of PHP it would be nice to get some feedback if everything is done the right way. I tested the principle code changes on ownCloud 8.1.4, 8.2.0 and 8.2.1.

It would be possible to configure other things like the removed icons also. But as I could live without them I have not changed anything regarding that. But if multiple persons request it, I could extend it.

(sorry, my editor removed trailing white spaces in config/config.sample.php)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:-1: no additional config option please - we have to have con-sens on the way the login screen should look like

**Comment by EtlamGit** [comment]
I have the feeling that no consensus is possible on design versus usability, as different people have different opinion by nature. And all these opinions are from value, non is right or false. That is the reason I made this suggestion to satisfy both groups.
I'm fine if you don't like this approach.

The main slogan of ownCloud is "Web services under your control" so I think the user should have easy control instead of being forced to follow a given design. Theming the login screen is quite hard at the moment. At least I found no easy way to implement the button.

**Comment by DeepDiver1975** [comment]
Sorry to sound rude now - not really my intention - but we will not open th can of worms to control various ui elements by config options - this is the road to hell!

Worst case this really has to be done using a theme - even if painful. Sorry

**Comment by EtlamGit** [comment]
I understand your point. (Does not help me, but it is like it is...)

Would be changing login.php and style.css to allow easier theming a valid approach?
I have no idea if this would be feasible, but I could at least try...

**Comment by DeepDiver1975** [comment]
with respect to theming it should be enough to copy the login template and the required css file(s) to the theme - should not be that of an issue from my pov

**Comment by EtlamGit** [comment]
You are right, it is possible to copy the complete files and apply the desired changes to them.

The drawback with that is, that you have to redo your work every time the original files are altered. And the development speed at ownCloud is very very high :smile:

I have something in mind like: the extra button is hidden by default and a tiny css just switches it visible. There are several hidden elements in the login screen, so an additional hidden element might be ok.

**Comment by DeepDiver1975** [comment]
> The drawback with that is, that you have to redo your work every time the original files are altered.

this applies to any theming in ownCloud



> And the development speed at ownCloud is very very high :smile:

This should only affect for major upgrades

**Comment by DeepDiver1975** [comment]
> I have something in mind like: the extra button is hidden by default and a tiny css just switches it visible. There are several hidden elements in the login screen, so an additional hidden element might be ok.

I'm also not willing to walk this path - sorry

**Comment by jancborchardt** [comment]
Well, as it is now you can pretty easily style this via CSS to make it a separate button.

However yeah, it might indeed be best to move forward to a separate button again, or visually separate it more as previously requested cc @oparoz @owncloud/designers

**Comment by robertboyl** [comment]
Guys,

This doesnt make sense to me, perhaps youre thinking of SSO. Why all this complication of removing the login button? It just makes usability worse. How are lame users supposed to know how to login? That they have to hit ENTER key to login?

Why give everyone all this work of having to complain with you guys about this. Why make usability worse...  Then someone asks to have a switch to enable button and you deny it also. Seems you dont consider USABILITY :( or at least some text "hit enter to login". A smaller button, an arrow, anything. Just dont keep it the way it is, ask anyone, put a less experienced person in front of login page and ask them to try to login. Thats how usability is tested in ecommerce sites of major companies...

Come on, guys, just put the button back, please.

Thanks.

**Pull request closed without merging**
