### PR TITLE
[stable10] rethrow correct exception in case of ForbiddenException

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #28953

### CODE REVIEW

**Comment by phil-davis** [comment]
After 2 hours in Jenkins it decides:
```
[ERROR] Waited 600 seconds, no response
```

**Review by individual-it — APPROVED** [review]

**Comment by PVince81** [comment]
> https://github.com/owncloud/core/pull/28953#issuecomment-328085874

@phil-davis we're in code freeze, please only merge criticals

**Comment by individual-it** [comment]
@PVince81 you have requested a backport to 10.0.4 https://github.com/owncloud/core/pull/28953#issuecomment-328085874
Is there an other branch for that?

**Comment by PVince81** [comment]
no, for now we just keep it in PR form and merge after stable10 is open for merges again. (merging to master is ok)

In the future we should consider a branching model that allows merging even after freeze.

**Pull request merged**
