### PR TITLE
properly use smb permissions

### PR DESCRIPTION
**Pull request by icewind1991**
implement`isUpdatable` and `isReadable` for smb external storage

@karlitschek should be backported to 9.0.1

cc @PVince81 @Xenopathic @jmaciasportela

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks @icewind1991 :+1:

**Comment by karlitschek** [comment]
please backport

**Comment by PVince81** [comment]
@jmaciasportela @jvillafanez @SergioBertolinSG please help testing

**Comment by jmaciasportela** [comment]
Maybe we can add some debug log when an exception is catched

**Comment by Xenopathic** [comment]
:+1:

@jmaciasportela No debug log needed, if an exception bubbles out of the storage it hits catches higher up in the call stack, which perform the logging.

**Comment by icewind1991** [comment]
stable9: https://github.com/owncloud/core/pull/23447

**Pull request merged**
