### PR TITLE
Remove checks whether OC is running on Windows

### PR DESCRIPTION
**Pull request by PVince81**
## Description

There is a setup check that prevents installing on Windows.
No need to keep the old unsupported Windows code paths.
## Related Issue

None
## Motivation and Context

Additional useless code paths and legacy code.
Additional warnings every time the unit tests are run and I'm too lazy to adjust my console's scrollback buffer.
## How Has This Been Tested?

Ran unit tests.
Checked that files_external still works after the change in there.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Tech debt
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@DeepDiver1975 @butonic @jvillafanez @VicDeo :skull:

### CODE REVIEW

**Comment by th3fallen** [comment]
go home @mention-bot you're drunk

**Comment by PVince81** [comment]
@th3fallen hmm seems your email address is still in https://github.com/owncloud/core/blob/master/.mailmap#L72, want me to remove it ?

**Comment by th3fallen** [comment]
@PVince81 please/thanks also probably Craigs too

**Comment by nickvergessen** [comment]
@PVince81 mailmap is all fine and should stay.
Seems like mention had a hick-up and ignored https://github.com/owncloud/core/blob/master/.mention-bot#L31

**Comment by PVince81** [comment]
Ah, thanks. I was indeed looking at the wrong file.

**Comment by butonic** [comment]
👍 yes please

**Comment by PVince81** [comment]
seems I missed some tests, let me grab my :gun:

**Comment by PVince81** [comment]
uh oh... seems that the posix test was actually running the windows verify method... will fix as well

**Comment by RealRancor** [comment]
> There is a setup check that prevents installing on Windows.

That is currently not even working: https://github.com/owncloud/core/issues/26208

**Comment by DeepDiver1975** [comment]
👍

**Pull request merged**
