### PR TITLE
Correctly check if the real file exists, otherwise try the part file

### LINKED ISSUE #17188: Sharing file with group and then deleting it does not delete the file for group recipients
### Config
* Encryption enabled
* Local sharing
* **NO** locking

### Steps to reproduce

1. user1 creates a file (size=9,8K)
2. user1 shares file to group1 (which is only user2)
3. user2 modifies the file (size=9,9K)
     + Remember smashbox uploads via WebDav using part files
4. user1 verifies the modified file (size=22K)
5. user1 deletes the file
6. user2 checks if the file is deleted => :boom: 
    + file is retained as conflict file, since it was not the deleted file I guess
    + file is owned by user2 and not marked as shared by user1

or

```
bin/smash lib/oc-tests/test_shareGroup.py -a
```

Breaking commit is 95602d4069a1eb9a45e1d08edeecc0d5b90e01ca from #17045 

Will try to find out if I can fix it similar to #16803 but since we are close to lock down, calling @schiesbn for the rescue as well.

@DeepDiver1975 this is the failing smashbox test on jenkins +enc -locking

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #17188 

@DeepDiver1975 @schiesbn @PVince81

### CODE REVIEW

**Comment by LukasReschke** [comment]
```
05:56:13 
05:56:13 1) Test\Files\Storage\Wrapper\Encryption::testGetHeader with data set #0 ('/foo/bar.txt', '/foo/bar.txt')
05:56:13 OCP\Files\Storage::file_exists('/foo/bar.txt') was not expected to be called more than once.
05:56:13 
05:56:13 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/lib/private/files/storage/wrapper/encryption.php:614
05:56:13 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/testcase.php:68
05:56:13 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/files/storage/wrapper/encryption.php:415
05:56:13 
05:56:13 2) Test\Files\Storage\Wrapper\Encryption::testGetHeader with data set #1 ('/foo/bar.txt.part', '/foo/bar.txt')
05:56:13 OCP\Files\Storage::file_exists('/foo/bar.txt.part') was not expected to be called more than once.
05:56:13 
05:56:13 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/lib/private/files/storage/wrapper/encryption.php:614
05:56:13 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/testcase.php:68
05:56:13 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/files/storage/wrapper/encryption.php:415
05:56:13 
05:56:13 3) Test\Files\Storage\Wrapper\Encryption::testGetHeader with data set #2 ('/foo/bar.txt.ocTransferId7437493.part', '/foo/bar.txt')
05:56:13 OCP\Files\Storage::file_exists('/foo/bar.txt.ocTransferId7437493.part') was not expected to be called more than once.
05:56:13 
05:56:13 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/lib/private/files/storage/wrapper/encryption.php:614
05:56:13 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/testcase.php:68
05:56:13 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/files/storage/wrapper/encryption.php:415
```

**Comment by nickvergessen** [comment]
@LukasReschke yeah didn't adjust the test on the first push, since I just wanted to be able to discuss the patch with @schiesbn

**Comment by DeepDiver1975** [comment]
@nickvergessen smashbox is not green?

**Comment by nickvergessen** [comment]
by `not` you mean `now`?
With this patch at least the failing shareGroup is green again, didn't try the others, but I can if you want me to.

**Comment by DeepDiver1975** [comment]
> by not you mean now?

now - sorry - friday afternoon ...

**Comment by nickvergessen** [comment]
with encryption without locking:

Test | Result
---- | ------
reshareDir | :white_check_mark: 
shareDir | :white_check_mark: 
shareFile | :white_check_mark: 
shareGroup | :white_check_mark: 
sharePermissions | :white_check_mark: 
uploadFiles | :white_check_mark: 
basicSync | :white_check_mark: 

So it fixes the failing test without breaking anything else

**Comment by schiesbn** [comment]
makes sense :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
