### PR TITLE
App navigation scrolling (Possible fix for #22158)

### PR DESCRIPTION
**Pull request by ErikPel**
#22158

I think this works but I feel really dirty using pixel value like that but I can't do anything with percents since the parent has no height value set, only max-height.

Can't figure out any other way to do it though unless we use javascript to set the height in relation to the parent.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by Henni** [comment]
`620px` seems a bit arbitrary.

Try something like `max-height: calc(100vh - 100px);`
Furthermore `#navigation` has a max-height which should be removed to make this work, I believe.

**Comment by ErikPel** [comment]
@Henni Agreed. Calc is better here. Changed it
It works fine for me without removing the max-height form #navigation so I don't think thats neccessary

**Comment by Henni** [comment]
The content and scrollbar currently overflow the black box.
image

**Comment by ErikPel** [comment]
@Henni squashed

**Comment by MorrisJobke** [comment]
Awesome! Works in Safari, Chrome, Firefox, Chrome on Android 5, IE9 :)

:+1:

**Comment by jancborchardt** [comment]
Nice work @ErikPel! :) You’re very welcome in our #owncloud-design IRC channel.

**Pull request merged**
