### PR TITLE
fix: this allows to implement OPTIONS request handling in framework c…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…ontrollers - if it is  not a CORS preflight request. CORS requests will continue to be handled by core

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
@JammingBen fyi

**Comment by JammingBen** [comment]
@DeepDiver1975 Is this still needed?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Is this still needed?

Don't needed anymore for my original case ..... but worth it as a general enhancement ...

**Comment by JammingBen** [comment]
I rebased and added a changelog item. @DeepDiver1975 If you're fine with it we can merge.

**Comment by phil-davis** [comment]
@DeepDiver1975 this is not in the `release-10.9.0` branch. 
Does it need to be released "soon" in 10.9.0?

**Comment by DeepDiver1975** [comment]
> Does it need to be released "soon" in 10.9.0?

no - thx

**Pull request merged**
