### PR TITLE
Revert OCS error code change from #20135

### LINKED ISSUE #127: Failing tests against master
```
======================================================================
FAIL: test_add_user_to_group_remove_user_from_group (__main__.TestUserAndGroupActions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "owncloud/test/test.py", line 889, in test_add_user_to_group_remove_user_from_group
    self.assertEquals(e.exception.status_code, 102)
AssertionError: 101 != 102

----------------------------------------------------------------------
Ran 53 tests in 123.776s
```

Could also be a regression on OC master.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix https://github.com/owncloud/pyocclient/issues/127

@PVince81 @LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG please add an integration test for this case - THX

**Comment by DeepDiver1975** [comment]
We will merge this once the integration test is there.

The intention of the integration tests is to detect exactly such cases

**Comment by nickvergessen** [comment]
Well it has unit tests, they just have also been adjusted in the other PR

**Comment by SergioBertolinSG** [comment]
@DeepDiver1975 I've added it while adding some of the sharing tests https://github.com/owncloud/core/pull/20351

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I've added it while adding some of the sharing tests #20351

THX - and it fails .... that's the way this should work :+1:

**Pull request merged**
