### PR TITLE
[stable9] Return remote shares in oc:share-types Webdav property

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/23549 to stable9

Please review  @icewind1991 @rullzer @MorrisJobke @nickvergessen @blizzz @DeepDiver1975

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
Second review @icewind1991 @schiesbn @nickvergessen ?

**Comment by rullzer** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1: ( @rullzer seems to be growing a split personality)

**Pull request merged**
