### PR TITLE
Version bump and changelog update

### PR DESCRIPTION
**Pull request by HanaGemela**

### CODE REVIEW

**Review by jnweiger — CHANGES_REQUESTED** [review]
Nah, the new changlog folder is missing.

**Comment by phil-davis** [comment]
Somehow the changelogs got deleted, not renamed into a new folder.
We need a well-known process that works :)

**Comment by micbar** [comment]
@phil-davis check handbook.owncloud.com should be documented.

@HanaGemela If you move files in a git repo, you need to add the new locations
I always do `git add .`

**Comment by phil-davis** [comment]
Found it https://handbook.owncloud.com/changelog_entries.html
I thought there was some scripting magic, but not so. Just a matter of creating `changelog/10.4.1_2020-03-30` and moving the files to it, and making sure that they are added to the commit.

PR #37179

**Pull request closed without merging**
