### PR TITLE
Stable9.1 integration tests adding etag support

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Backport of https://github.com/owncloud/core/pull/26370

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by SergioBertolinSG** [comment]
@PVince81 failing case:
```
[Thu Nov 24 09:18:46 2016] 127.0.0.1:45556 [404]: /remote.php/webdav/merge-test-outside-groups-renamebeforesecondshare-renamed
    Then as "user1" gets properties of folder "/merge-test-outside-groups-renamebeforesecondshare-renamed" with                                        # FeatureContext::asGetsPropertiesOfFolderWith()
      | {http://owncloud.org/ns}permissions |
      HTTP error: 404 (Sabre\DAV\Exception)
```

I guess you improved this test recently didn't you?

**Comment by PVince81** [comment]
No, that's the test that usually randomly fails. Let's see if it passes during the next run...

**Comment by SergioBertolinSG** [comment]
What about removing it?

**Comment by PVince81** [comment]
This is an important test about merging shares, I don't want to remove it...

**Comment by PVince81** [comment]
Green but result unpublished => merge

**Pull request merged**
