### PR TITLE
Markdown support for app descriptions ...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
More and more apps use markdown in the description - we need to support this in the apps settings panel as well

## Screenshots (if appropriate):
bildschirmfoto von 2017-06-22 11-16-05

vs

bildschirmfoto von 2017-06-22 11-18-20

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
any potential security implications, XSS or so ? @Peter-Prochaska

**Comment by Peter-Prochaska** [comment]
No

**Comment by kdslkdsaldsal** [comment]
Just to note that the ``*`` bulletpoints in the new screenshot for GpxPod are not rendered like e.g. on the marketplace page:

https://marketplace.owncloud.com/apps/gpxpod

**Review by lordelix — APPROVED** [review]
Hmm … I don't like the visual look at all, but this is a topic for another day. ;-)

**Comment by DeepDiver1975** [comment]
> Hmm … I don't like the visual look at all, but this is a topic for another day. ;-)

Feel free to change this ;-)

**Comment by felixheidecke** [comment]
> Feel free to change this ;-)

That will be a bigger undertaking.

**Pull request merged**
