### PR TITLE
encode jobs that have an array as job value

### LINKED ISSUE #35222: Error thrown when running occ background:queue:status
# Description
I am getting
`A cell must be a TableCell, a scalar or an object implementing __toString, array given.`
error when running occ command `background:queue:status`

This is produced if there is job in the background queue whose arguments is an array
Some of the job class which has an array as an argument are  `OCA\Federation\BackgroundJob\RequestSharedSecret` and `OCA\FederatedFileSharing\BackgroundJob\RetryJob`

# Steps to reproduce:
1) Setup two servers eg: `core` and `core-fed`
2) Add `'sharing.federation.allowHttpFallback' => false,` in config.php both servers
3) Login as admin in server `core` and add `http://localhost/core-fed` on Federation Trusted Server
Step 3 creates a background job with class `OCA\Federation\BackgroundJob\RequestSharedSecret`
4) On server `core` run occ command `background:queue:status`

# Expected Behaviour
You get the table with the information of jobs in a background queue

# Actual Job
You get error `A cell must be a TableCell, a scalar or an object implementing __toString, array given.`

This can be reproduced in latest master, 10.2 RC 2, 10.2 RC 3

cc @individual-it @phil-davis @PVince81 @micbar @DeepDiver1975

### PR DESCRIPTION
**Pull request by patrickjahns**
## Description
If the argument of a job is an array, json_encode it

## Related Issue

- Fixes https://github.com/owncloud/core/issues/35222

## Motivation and Context
Fix https://github.com/owncloud/core/issues/35222

## How Has This Been Tested?

- 🤖 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by individual-it** [comment]
```
---------- begin diff ----------
--- Original
+++ New
@@ -45,8 +45,8 @@
 	}
 
 	private function getJobArgumentAsString($argument) {
-		if (is_array($argument)) {
-			$argument = json_encode($argument);
+		if (\is_array($argument)) {
+			$argument = \json_encode($argument);
 		}
 		return $argument;
 	}

----------- end diff -----------

**Comment by phil-davis** [comment]
Backport `stable10` PR #35225
Backport `release-10.2.9.0` PR #35228

**Comment by individual-it** [comment]
CC @paurakhsharma please adjust the tests you are writing accordingly

**Pull request merged**
