### PR TITLE
[stable10] Backport of repair step for mismatch filecache paths

### PR DESCRIPTION
**Pull request by tomneedham**
Backport of https://github.com/owncloud/core/pull/28253 to stable10.

Not tested manually yet, waiting for CI

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: assuming it's the same code

**Comment by phil-davis** [comment]
The very first commit from #28253 is not listed here. Is that because it was totally overridden by later commits in this list?

**Comment by socrat3000** [comment]
@phil-davis  Does this mean #28253 isn't going to be resolved in 10.0.4??

**Comment by phil-davis** [comment]
It means I ma asking @tomneedham if there is a reason that the 1st commit is missing from the backport, or???

**Comment by tomneedham** [comment]
Hmm investigating what happened here

**Comment by tomneedham** [comment]
Cleaned the branch, re-cherry-picked starting from the correct commit.

**Comment by tomneedham** [comment]
This is still missing the lib/private/repair.php modification - huh!

**Comment by tomneedham** [comment]
Ready for review

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by agross** [comment]
Hi,

Any idea why the `--repair` option is not available on 10.0.3?

```
[root@cloud data]# docker exec -it -u www-data owncloud_owncloud_1 php occ --version
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
ownCloud 10.0.3
[root@cloud data]# docker exec -it -u www-data owncloud_owncloud_1 php occ files:scan --all --repair
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php


  [Symfony\Component\Console\Exception\RuntimeException]
  The "--repair" option does not exist.


files:scan [--output [OUTPUT]] [-p|--path PATH] [-q|--quiet] [-v|vv|vvv|--verbose] [--all] [--unscanned] [--] [<user_id>]...
```

**Comment by socrat3000** [comment]
When is 10.0.4 going to be released?

Kind Regards,

Ahmad Amr

**Comment by agross** [comment]
You're right. I wish I could read better ;-) Really looking forward to this feature. I have several users with sync errors and I hope I can fix these with the new extended repair.

**Comment by socrat3000** [comment]
Hi Guys,

Could you please let me know when the expected release data for 10.0.4 is?
This issue is killing us here!

Kind Regards / مع تحياتي

أحمد عمرو
Ahmad Amr

**Comment by PVince81** [comment]
There is no fixed release date. 10.0.4 RC1 has just been released and needs to go through QA first which could take 1-2 weeks depending on complications. If no critical issues are found we can then provide a final build.

**Comment by PVince81** [comment]
the other alternative would be to download this PR as a patch https://github.com/owncloud/core/pull/29074.patch and then run the repair step. The PR itself only adds repair code and adds the `--repair` switch for occ files:scan and doesn't affect anything else.

**Comment by PVince81** [comment]
By the way, if you do so, make sure to check the documentation: https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/occ_command.html?highlight=repair#the-repair-option

**Comment by socrat3000** [comment]
Sorry for my ignorance, but how I apply the patch? Also, should I have
10.0.3 installed in order to apply it?

Kind Regards / مع تحياتي

أحمد عمرو
Ahmad Amr

**Comment by PVince81** [comment]
1. install 10.0.3.
1. download patch https://github.com/owncloud/core/pull/29074.patch
1. make backup of the code for quick rollback
1. execute `patch -p1 < 29074.patch`
1. backup your data
1. run commands as per https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/occ_command.html?highlight=repair#the-repair-option

**Comment by socrat3000** [comment]
Thanks a lot, will try it.

Kind Regards,

Ahmad Amr

**Comment by socrat3000** [comment]
Hi Guys,

Today is the last day in November, but 10.0.4 hasn't been released yet.

Are there any updates regarding this?

Kind Regards / مع تحياتي

أحمد عمرو
Ahmad Amr

**Comment by PVince81** [comment]
10.0.4 RC1 is currently still in QA, hopefully next week. See https://github.com/owncloud/core/issues/29697

**Comment by socrat3000** [comment]
On the releases page, you guys committed to release it in October, then in
November, and now in December.

I am sorry to say that, but this is very unprofessional.

Kind Regards,

Ahmad Amr

On Nov 30, 2017 1:02 PM, "Vincent Petry" <notifications@github.com> wrote:

10.0.4 RC1 is currently still in QA, hopefully next week. See #29697
<https://github.com/owncloud/core/issues/29697>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/owncloud/core/pull/29074#issuecomment-348140240>, or mute
the thread

**Pull request merged**
