### PR TITLE
[stable9.1]  Add CleanupRemoteStorages command 

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/26379 to stable9.1

@butonic @DeepDiver1975 @PhilippSchaffrath please review

### CODE REVIEW

**Comment by PVince81** [comment]
Looks like commands can't be registered in info.xml on this branch, I'll move it to register_command.php then

**Comment by PVince81** [comment]
Done.

**Comment by PVince81** [comment]
@butonic @jvillafanez @IljaN @DeepDiver1975 @VicDeo please review

**Comment by DeepDiver1975** [comment]
> Looks like commands can't be registered in info.xml on this branch,

yes - this is a new feature as of oc10

**Comment by jvillafanez** [comment]
Same as https://github.com/owncloud/core/pull/27010#issuecomment-274836572 , so 👍

**Pull request merged**
