### PR TITLE
Revert "Revert "Move trashbin specific CSS that modifies sidebar""

### PR DESCRIPTION
**Pull request by DeepDiver1975**
This reverts commit 0738ddfb768c541e8a6b112fb2cd12d15676a0ab.

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by jancborchardt** [comment]
:+1: again on this.

To any eager people: **DO NOT MERGE THIS** BEFORE THE 8.2 RELEASE! Look at the milestone, it says »8.2.1«. ;)

**Comment by MorrisJobke** [comment]
@PVince81 Can you create the backport PR for 8.2.1? Thanks

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19779
(see original PR here https://github.com/owncloud/core/pull/19702#issuecomment-148042102)

**Pull request merged**
