### PR TITLE
remove unneeded icons from input fields to not distract from submit button, fix #18940

### LINKED ISSUE #18940: That new tiny login arrow is not a proper way to login
That tiny arrow in the field just doesn't work.

* It gets completely masked if a user uses a password manager like Lastpass
* It looks tiny
* It's almost invisible
* it looks like it's part of the design, not like an actionable item

It needs to be overhauled or it needs to go.

@jancborchardt - Call your army to fix this!

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #18940

Please review @owncloud/designers @oparoz @dragotin @enoch85 @HLFH

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@karlitschek I added the backport request, because #18940 is filed against 8.2.1 ;)

**Comment by karlitschek** [comment]
Yes. Backport is fine :+1:

**Comment by DeepDiver1975** [comment]
@jancborchardt please prepare backport pr - THX

**Comment by jancborchardt** [comment]
@carlaschroder as notice for the docs: This and the wording change in https://github.com/owncloud/core/pull/19990 changed the look of the log in screen and installation screen. Both for upcoming 9.0 and are backported to be released with 8.2.1

**Pull request merged**
