### PR TITLE
Move s3 to own app

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Secondary s3 storage integration has been moved to it's own repository
https://github.com/owncloud/files_external_s3

## Motivation and Context
- minimize core
- divide and conquer

## How Has This Been Tested?
- manually with mino

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

10.1 only. the new app will have min-version=10.1

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by DeepDiver1975** [comment]
> any reason? this would mean we need to run files_external tests in 10.0 again

or keep it as is for all these years: dont run the tests

**Comment by PVince81** [comment]
the app will use new AWS SDK. if it's compatible with 10.0 then why not...

**Pull request merged**
