### PR TITLE
Use SVG for desktop app button

### PR DESCRIPTION
**Pull request by LukasReschke**
For the other ones we unfortunately don't have that. Partially addresses https://github.com/owncloud/core/issues/22154

Otherwise the font is super blurry on a retina display.

@owncloud/designers

### CODE REVIEW

**Comment by rullzer** [comment]
The image differs: https://github.com/owncloud/core/blob/master/core/img/desktopapp.png vs https://github.com/owncloud/core/blob/master/core/img/desktopapp.svg

The svg is cut off...

**Comment by LukasReschke** [comment]
> The image differs: https://github.com/owncloud/core/blob/master/core/img/desktopapp.png vs https://github.com/owncloud/core/blob/master/core/img/desktopapp.svg

For me only a bit in the font (well, before it was just totally blurry) but cut off? I see everything :see_no_evil:

**Comment by rullzer** [comment]
button

**Comment by LukasReschke** [comment]
Don't we love browser standards? :tada: 

What browser do you use? And does it look in ownCloud as well so wrong? :see_no_evil:

**Comment by rullzer** [comment]
Firefox
And yes looks the same in owncloud

**Comment by LukasReschke** [comment]
Chrome here. Well, I guess our pixel overlords need to fix that then as well. Closing and moving to  https://github.com/owncloud/core/issues/22154 :cry:

**Comment by Henni** [comment]
please take another look @LukasReschke @rullzer

**Comment by LukasReschke** [comment]
Works for me :+1:

**Comment by Henni** [comment]
I also updated the Google Play and App Store badges.
Please also take a look at them @LukasReschke

**Comment by LukasReschke** [comment]
:tada:

**Comment by rullzer** [comment]
Looking better.

button

**Comment by rullzer** [comment]
So it seems my button is still hugging the side a bit more... but at least the text is all there now. :+1:

**Comment by Henni** [comment]
just one second ;)

**Comment by rullzer** [comment]
@Henni yes awesome!

**Comment by LukasReschke** [comment]
:+1: again as well :)

**Comment by DeepDiver1975** [comment]
What about our beloved IE comrades? Does this work there as well?

**Comment by Henni** [comment]
**Should** work from IE9 up. I haven't tested it.

@owncloud/designers anyone able to test this?

**Comment by MorrisJobke** [comment]
Tested and works in IE9

**Pull request merged**
