### PR TITLE
[stable8.1] Execute parallel-lint

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/owncloud/core/pull/22994 and https://github.com/owncloud/core/pull/23303

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by rullzer** [comment]
So why is there no travis in the check list?

**Comment by LukasReschke** [comment]
No idea :see_no_evil: - Let's rerun :tada:

**Comment by MorrisJobke** [comment]
@rullzer Travis succeeded. :tada:

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
