### PR TITLE
implement path_list|-l "..." option for batch scanning. This option t…

### PR DESCRIPTION
**Pull request by Yetangitu**
…akes one argument, pointing to a file which is assumed to contain one line per file or directory to scan.

Mind, I ported the change from 8.2.2 to master without testing as I do not have an instance of master running at the moment. Try before you buy...

### CODE REVIEW

**Comment by PVince81** [comment]
@icewind1991 please review

**Comment by mmattel** [comment]
I would prefer to merge #21701 first.
This would mean rebasing this PR afterwards
I also suggest naming the command parameter ``path_list`` --> ``file``
In case we proceed here, a documentation PR is necessary to reflect the changes

**Comment by Yetangitu** [comment]
Related pull request for an experimental scan api for the files app:

https://github.com/owncloud/core/pull/21984

**Comment by Yetangitu** [comment]
@owncloud-bot this contribution is MIT licensed

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/21701 was merged.

@Yetangitu can you rebase and solve the conflicts ?
Thanks :smile:

**Comment by PVince81** [comment]
@icewind1991 @Xenopathic can you comment on this proposal ?

**Comment by PVince81** [comment]
Is there still interest in this enhancement ?
@Yetangitu @mmattel @DeepDiver1975 ?

**Comment by Yetangitu** [comment]
I'm using the API-based version nowadays (by patching new releases of OC and NC) but the original use case still stands. I can update the occ-based version, possibly in tandem with the API.

**Comment by DeepDiver1975** [comment]
> I'm using the API-based version nowadays (by patching new releases of OC and NC) but the original use case still stands. I can update the occ-based version, possibly in tandem with the API.

@Yetangitu your contribution is still welcome - please rebase - THX

**Comment by PVince81** [comment]
Do you still intend to update this ?

**Comment by Yetangitu** [comment]
If there is any interest I can update it, yes.

**Comment by PVince81** [comment]
I don't think there is a strong interest in this. On the CLI one could achieve the same result with a quick bash loop that reruns the command with different paths.

I'm closing this for now. Thanks.

**Pull request closed without merging**
