### PR TITLE
Update the list of shipped apps

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by nickvergessen** [comment]
@DeepDiver1975 `user_webdavauth` was removed from this repo lately, is it still shipped?

**Comment by nickvergessen** [comment]
Also `"core-version": "8.1.0.0",` in this file should be adjusted before the release, @cmonteroluque maybe part of the "increment version on release" step you do

**Comment by MorrisJobke** [comment]
> Also "core-version": "8.1.0.0", in this file should be adjusted before the release, @cmonteroluque maybe part of the "increment version on release" step you do

@DeepDiver1975 Do we even need this. It isn't used in the code.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
