### PR TITLE
drop any fallback code related to curl

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs https://github.com/owncloud/core/pull/14838#issuecomment-78586447

@LukasReschke @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
I really really really hope this doesn´t bite us in the ass if we introduce a new major dependency in a patch release.

**Comment by LukasReschke** [comment]
> I really really really hope this doesn´t bite us in the ass if we introduce a new major dependency in a patch release.

The dependency was always there. S2S and Co. required it. We just never checked for it.

**Comment by nickvergessen** [comment]
The setup still checks for it and reports it as missing, I assume?

**Comment by LukasReschke** [comment]
:+1:

**Comment by LukasReschke** [comment]
> The setup still checks for it and reports it as missing, I assume?

Since https://github.com/owncloud/core/pull/14838: Yes.

**Comment by nickvergessen** [comment]
> I really really really hope this doesn´t bite us in the ass if we introduce a new major dependency in a patch release.

We could simply not backport this to stable8, then it's not a patch release. Which I think would be the right process

**Comment by LukasReschke** [comment]
> We could simply not backport this to stable8, then it's not a patch release. Which I think would be the right process

The setup check has been already added to stable8 because ownCloud simply does not work correctly without cURL :see_no_evil:

**Comment by LukasReschke** [comment]
(that said this PR should not get backported – yes.)

**Comment by karlitschek** [comment]
agreed. fine for 8.1 but no backport. thanks guys :-)

**Comment by DeepDiver1975** [comment]
> I really really really hope this doesn´t bite us in the ass if we introduce a new major dependency in a patch release.

This PR is just a logical followup on https://github.com/owncloud/core/pull/14838 - we do require curl now - no need to maintain fallback code which will never be executed anymore.

**Comment by DeepDiver1975** [comment]
> agreed. fine for 8.1 but no backport. thanks guys :-)

counting as :+1:

**Pull request merged**
