### PR TITLE
Test creating users with various passwords using the Provisioning API

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Add test scenarios to verify that users can be created with various unusual passwords using the Provisioning API, and that a password with just space is invalid.

## Related Issue
- Part of issue #33570 

## Motivation and Context
See issue

## How Has This Been Tested?
Local run of test scenarios

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
Interestingly, you can have embedded space(s) in a password, even starting with the space character. But you cannot have 1 space, or multiple spaces.

As per the issue, the equivalent test scenarios should also be created for the ``occ`` command and the webUI.

**Comment by phil-davis** [comment]
Any ideas for other strings that might be invalid passwords?

**Review by individual-it — APPROVED** [review]

**Comment by individual-it** [comment]
here more ideas for "interesting" strings https://github.com/minimaxir/big-list-of-naughty-strings

**Comment by patrickjahns** [comment]
> here more ideas for "interesting" strings https://github.com/minimaxir/big-list-of-naughty-strings

Was about to also suggest that one - recently had a revival on hn ;-) 
Maybe we can package that one into a composer package and provide it as helper for our acceptance tests?

**Comment by phil-davis** [comment]
Backport ``stable10`` #33580

**Pull request merged**
