### PR TITLE
Backport objectstore fixes to 8.2

### PR DESCRIPTION
**Pull request by butonic**
backport of objectstore fixes https://github.com/owncloud/core/pull/17641#issuecomment-148911335

cc @DeepDiver1975 @icewind1991 @MorrisJobke

### CODE REVIEW

**Comment by butonic** [comment]
locally all tests passed:
```
OK, but incomplete, skipped, or risky tests!
Tests: 5883, Assertions: 16578, Skipped: 294.
```

**Comment by butonic** [comment]
@DeepDiver1975 can you enable objectstore tests for 8.2 please?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 can you enable objectstore tests for 8.2 please?

they are already active for all branches ... takes some time ....

**Comment by DeepDiver1975** [comment]
all green :+1:

**Pull request merged**
