### PR TITLE
Merge back 10.13.3

### PR DESCRIPTION
**Pull request by jnweiger**
Note, this is only a cherry-pick of changelog/* and version.php changes done in the release/10.13.3 branch.
All code changes are assumed to be already part of master.

* Not sure what to do with the v10.13.3 tag - it is not coming automatically into master, as before. Should it remain in the release/10.13.3 branch?
* Not sure what the correct conventional commit categories are. conventionalcommits.org implies that categories should convey meaning. But even the "full specification" has at most one line of text per category. Some categories are only mentioned without any explanation. This leaves room for guesswork. I am trying now with the categories "build:" and "docs:" as these make most sense to me. 

Please provide some helpful hints if this PR is still unacceptable. Referring to an agreed standard is not helpful, when the specification of the standard is lacking.

Replaces: #41118

### CODE REVIEW

**Comment by phil-davis** [comment]
The default valid categories are this list that gets emitted when there is an invalid category used:
```
category not one of build,ci,chore,docs,feat,fix,perf,refactor,revert,style,test
```

But the "spec" only requires a shorter list to be valid. And the repo that we use for the validation does not have this expanded default list mentioned in its README or other docs. The list is embedded in the code only.

IMO we need to write somewhere about the requirements for our commit messages so that contributors know what is the valid list. I had a look in https://doc.owncloud.com/server/next/developer_manual/ but there are a lot of things there that are out of date, so as soon as "someone" starts to touch that to add commit message docs, it will be difficult without first doing quite a review of the current state of it.

**Review by phil-davis — APPROVED** [review]
This should work - it gets the changelog files for 10.13.3 in the right folder, and that should cause an appropriate matching 10.13.3 changelog to be generated in master.

It pro-actively bumps the version in master to 10.13.4, which is fine. We want to do that anyway directly after 10.13.3 happens.

**Comment by phil-davis** [comment]
> Not sure what to do with the v10.13.3 tag

`v10.13.3` is a progression from 10.13.2, separate from the sequence of things happening in master. So the tag has to stay with the commit that is at the head of the 10.13.3 commits.

At this stage, the reality is that we are making a sequence of 10.13.* patch releases that build on each other, picking patches from the things that are merged to master. And master has things that will become 10.14.0. So maybe it would be nice to have a branch called something-10.13 which has the sequential history of 10.13.*, and we can easily add to that branch if we want to provide more patches as a 10.13.4 release.

(We were trying to do a "oneflow" release system, where we always move forward and release whatever is in master (often a combination of patches and features and refactoring. But "life" happened differently for the 10.13 series)

**Comment by jnweiger** [comment]
Thanks for merging. Thanks for the explanations! I have oneflow implemented in the release checklists. So probably the release process needs a review now. Well, it needs a review for many other reasons too.

I observed that release tags of the desktop client also seem to live outside of master sometimes. So they probably also already deviated from oneflow?

**Comment by jnweiger** [comment]
Is there a commandline or web tool that I can use to "test" commit messages with?

I wonder how the category "chore" should be used. I believe, that all my commits during QA and release also fit there.

I see it used frequently and to me, it still has no meaning (except for a slight hint of negative emotions). It appears to be the great fallback for anything miscellaneous / other / uncategorized.

If we seriously adopt conventional commits, shouldn't we try to avoid chore and rather use categories that convey meaning?

**Comment by DeepDiver1975** [comment]
`chore:` has it's legitimate use.

Some explanations:
```
More Examples:

    feat: (new feature for the user, not a new feature for build script)
    fix: (bug fix for the user, not a fix to a build script)
    docs: (changes to the documentation)
    style: (formatting, missing semi colons, etc; no production code change)
    refactor: (refactoring production code, eg. renaming a variable)
    test: (adding missing tests, refactoring tests; no production code change)
    chore: (updating grunt tasks etc; no production code change)
```

I tend to use `ci:` for anything ci related - as per definition above this could be `chore:` as well.
And I use `chore:` for things which could fall into `style:` as well

In a perfect world we would have a clear list of definitions. But I am happy that we made it until here. :heart:

**Comment by phil-davis** [comment]
Note: I checked the commits between the `v10.13.3` and `v10.13.2` tags. All the code in those is already correctly in master, and the changelog and version bump stuff in this PR are the only diffs - so this is "a good thing".

**Pull request merged**
