### PR TITLE
[stable8.2] check if renamed user is still valid by reapplying the ld…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…ap filter 

backport #25338

### CODE REVIEW

**Comment by PVince81** [comment]
@owncloud/qa can you retest ?

**Comment by davitol** [comment]
@PVince81 @DeepDiver1975 This PR has a different behaviour than with https://github.com/owncloud/core/pull/25338

In this PR it is needed to click on the Clear buttons in the Expert tab in the LDAP wizard in order to get the right answer running the ldap:check-user command

Stable9

sudo -u www-data ./occ ldap:check-user aaliyah_armstrong
The user does not exists on LDAP anymore.
Clean up the user's remnants by: ./occ user:delete "aaliyah_armstrong"

This PR

The given user is not a recognized LDAP user.

**Comment by PVince81** [comment]
@felixboehm @jvillafanez do you have an idea whether that's a bad thing or whether it's the way it worked in 8.2 ? (regarding the previous comment)

**Comment by felixboehm** [comment]
You can't clear the user mapping (expert tab) in a production system. Bad thing.
Maybe in 8.2 it needs more to fix the issue?

**Comment by felixboehm** [comment]
This backport does not work. After removing a group of users from ldap, users are not shown in User page, but still 
```
>occ ldap:check-user felix                          
The user is still available on LDAP.
```

Needs more to fix this for 8.2.6 ...
@jvillafanez

**Comment by jvillafanez** [comment]
Recheck with the new commit. There was a missing filter so the user was being checked against the whole LDAP directory.

**Comment by davitol** [comment]
> Recheck with the new commit. There was a missing filter so the user was being checked against the whole LDAP directory.

:-1: Keeps failing for me using the new commit 😢

**Comment by jvillafanez** [comment]
Now it's fixed for sure for 8.2.

I hope the same set of changes works for 8.1

**Comment by PVince81** [comment]
@davitol can you retest ?

**Comment by davitol** [comment]
:+1: tested in 8.2 and WFM 👏

**Pull request merged**
