### PR TITLE
SAMEORIGIN in all caps

### PR DESCRIPTION
**Pull request by srcr**
RFC7034 states possible options are DENY, SAMEORIGIN and ALLOW-FROM.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mmattel** [comment]
https://tools.ietf.org/html/rfc7034#section-2 notes explicitly upper case values

Also written in upper case, in the documentation repository:
admin_manual/configuration_server/harden_server.rst
admin_manual/installation/nginx_examples.rst

http://www.ietf.org/rfc/rfc2616.txt
Section "4.2 Message Headers" states that the field is case insensitive, but there is no statement about this regarding the value.

Therefore I say :+1:

**Comment by PVince81** [comment]
Thanks, guys! Merging as CI won't cover this anyway.

**Comment by kdslkdsaldsal** [comment]
@PVince81 What about:

https://github.com/owncloud/core/blob/b2eb39a881/tests/integration/features/dav-v2.feature#L29
https://github.com/owncloud/core/blob/b2eb39a881/tests/integration/features/webdav-related.feature#L246

Not quite sure how these tests are working...

**Comment by PVince81** [comment]
oops. I'll check

**Comment by PVince81** [comment]
nice catch, PR here https://github.com/owncloud/core/issues/27602

**Pull request merged**
