### PR TITLE
My fix for #24272, #23613, File not found when single file in a folder

### PR DESCRIPTION
**Pull request by popov-d**
This is a new version of my fix. What I wrote yesterday in #24783 worked not the best way — a single file was downloaded as a ZIP with folder inside. This version makes archives only when really needed: when selecting multiple files or a folder.

In fact, we have 2 factors:
- All / not all files in a folder are selected
- One / multiple files are selected

The "change all selected to a folder download" operation should be made only in case all && multiple, not all && one. Therefore it is better to fix the first if(), leaving second as is.

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks for your PR!

6 commits for one line of code is a bit much. Are you able to squash your commits or do you need assistance ?

**Comment by PVince81** [comment]
@hhaeb @kgulti does this PR fix the issue for you ? Thanks

**Comment by popov-d** [comment]
It's the same repository I used some time ago to fix another bug. Before working on this one I merged it with current owncloud/core master (e0956ed), and then made 2 commits. 97d891d yesterday evening the the "dirty" fix, today's 965dfcc is a more clean one. It rolls back 97d891d and changes another line. Just this change is needed. Should I redo something?

**Comment by nickvergessen** [comment]
@PVince81 you can also squash on merge :-X

**Comment by PVince81** [comment]
@nickvergessen ok, will do

- [ ] squash on merge

**Comment by PVince81** [comment]
Tested, works :+1:
JS unit tests still pass locally.

**Comment by PVince81** [comment]
Second review ? @rullzer @blizzz @nickvergessen @schiesbn

**Comment by kgulti** [comment]
Fix does not work out for my problem. Still the same error when I try to download a single file.

**Comment by popov-d** [comment]
Are you sure new version is loaded in browser? In my case I had to clean the owncloud/assets directory on server (if you have asset-pipeline.enabled in config.php), clean browser cache and reload page completely. Before that, old version of code worked. May be hard to distinguish when JS is minified.

**Comment by PVince81** [comment]
Counting as second :+1:

**Comment by RealRancor** [comment]
Should fix https://github.com/owncloud/core/issues/23613 and https://github.com/owncloud/core/issues/24272

**Comment by PVince81** [comment]
Backported to stable9 here https://github.com/owncloud/core/pull/24966 as it has been reported several times

CC @cmonteroluque @DeepDiver1975

**Pull request merged**
