### PR TITLE
[WIP] Add composer loader to core

### PR DESCRIPTION
**Pull request by rullzer**
Lets try a different approach to https://github.com/owncloud/core/pull/20025.

This adds composer to core (only stuff in `lib` for now).

Saves almost 13ms in the autoloader.
Pretty impressive results for a simple propfind: https://blackfire.io/profiles/compare/779972a3-ecb9-4422-a48b-35a5945e0272/graph

### CODE REVIEW

**Comment by rullzer** [comment]
To put this in perspective: on current master a regular propfind is ~85-90ms for me. And a PUT of an empty file is about ~115ms. Saving 13ms on every call made has a pretty significant impact.

If you run the sync client propfinds and puts are all over the place and saving 10% on the fixed price that has to be paid is huge. Since we can't fix the upload speed of a file. The time saves is almost pure CPU time. Which means that this will also drop the server load! Which in means that we can support more sync client on the same hardware!

**Comment by Xenopathic** [comment]
@rullzer We all know about the performance benefits of a class map :smile:

But realistically, the goal is to replace \OC\Autoloader with Composer directly, and have the *option* of generating a class map. The class map shouldn't be the aim here. That approach would allow us to only regenerate the class map for production builds, making PRs simpler and annoying devs less :smile:

So, sorry, but :-1:, we just don't have the bits in place to support this properly IMO

**Comment by rullzer** [comment]
I agree that the current approach is not the ideal way to go. But investigating how much we could gain and how much work it will be is something we need to start doing in my opinion.

**Comment by DeepDiver1975** [comment]
From my pov we are currently loosing valuable time which could be better invested.

Performance analysis in the area of SQL will bring even better improvnents.

Once we properly use composer in core the class map genetation is a no-brainer.

@rullzer no offense - great initiative

**Pull request closed without merging**
