### PR TITLE
[WIP] introduction of interface IChunkHandler and a very first stupid implemen...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
...tation reusing the existing chunking mechanism

:construction: 

refs https://github.com/owncloud/core/issues/4997

@icewind1991 @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
So will we continue this for 8.2 ?

**Comment by PVince81** [comment]
We probably want https://github.com/owncloud/core/pull/17104 first

**Comment by DeepDiver1975** [comment]
> We probably want #17104 first

yes - there might be no necessity to have storage specific implementations ....

**Comment by DeepDiver1975** [comment]
let me close this

**Pull request closed without merging**
