### PR TITLE
Move \OCP\Command to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @MorrisJobke @nickvergessen @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by nickvergessen** [comment]
./run.sh: line 3: /usr/local/bin/composer: Permission denied

something is really f*cked up with jenkins atm

**Comment by MorrisJobke** [comment]
> something is really f*cked up with jenkins atm

Out of storage or something like that :(

**Comment by DeepDiver1975** [comment]
No - this was running on the newly installed jenlins slave and composer was not properly installed

**Comment by MorrisJobke** [comment]
👍

**Comment by georgehrke** [comment]
👍

**Pull request merged**
