### PR TITLE
Update the help links to point to the online documentation

### LINKED ISSUE #34510: Bundled docs missing in release
### Steps

1. Extract the ownCloud 10.1.0 tarball.
1. Check "core/doc" folder

### Expected result
Docs are there.

### Actual result
They aren't, only index.html.

### Version
ownCloud 10.1.0 Community and Enterprise bundles.

In the old versions 10.0.10 of the tarballs the docs are there.

Since we migrated to a new documentation format, we'll need extra steps to make sure the documentation is correctly bundled as it was before.

Now bundling the new one is likely not only a matter of putting the files there, we should also check that it properly renders in the UI.

Alternatively we could also decide to remove the bundled documentation altogether.
The various links inside of ownCloud are already pointing at the online documentation instead of the bundled one.

@settermjd @pmaier1 @hodyroff thoughts ?

### PR DESCRIPTION
**Pull request by settermjd**
## Description

This PR:

- Removes the docs directory
- Points the user and admin documentation help links to the latest version of the online documentation
- Adds a link to the developer documentation

## Related Issue

- Fixes #34510

## Motivation and Context

This has been created because the decision was made in #34510 to stop bundling the docs with the community edition, and instead link to the online documentation. 

## How Has This Been Tested?

- viewed and tested the links in a local development environment

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
@settermjd what's missing to finish this ?

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by PVince81** [comment]
rebasing so https://github.com/owncloud/core/pull/34611 is in as well

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by settermjd** [comment]
@PVince81, nothing else is required, that I know of. I did a check in the Makefile to see if there were any targets to remove, but I've not found any applicable ones.

**Comment by settermjd** [comment]
If you're happy with it, so am I.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@settermjd please backport to stable10

**Comment by phil-davis** [comment]
Backport `stable10` #34649

**Pull request merged**
