### PR TITLE
[stable9] Fix uploading to fed shares where free space is unlimited

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/22898
- [x] Pending confirmation 

Need to evaluate for 9.0 since it breaks upload for fed shares, however it's limited to the web UI (Webdav is fine)

CC @karlitschek @cmonteroluque

### CODE REVIEW

**Comment by PVince81** [comment]
Please review @icewind1991 @LukasReschke @tflidd @rullzer @MorrisJobke

**Comment by PVince81** [comment]
also this has a workaround: the sharer would need to set a quota for himself. (that assuming that they have admin rights...)

**Comment by rullzer** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by karlitschek** [comment]
please backport. @cmonteroluque it seems that we need this too. :-(

**Pull request merged**
