### PR TITLE
add hint to exception

### PR DESCRIPTION
**Pull request by schiessle**
add translatable hint to exception to improve error messages, displayed to the user.

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
unit tests are failing because of https://github.com/owncloud/core/pull/16796

**Comment by DeepDiver1975** [comment]
> unit tests are failing because of #16796

merged

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@schiesbn 

Regression

OCA\Encryption\Tests\lib\Crypto\EncryptionTest.testDecrypt (from OCA_Encryption_Tests_lib_Crypto_EncryptionTest)
Failing for the past 1 build (Since Failed#12729 )
Took 19 ms.
add description
Stacktrace

OCA\Encryption\Tests\lib\Crypto\EncryptionTest::testDecrypt
Failed asserting that exception message 'Can not decrypt this file,
			probably this is a shared file.
			Please ask the file owner to reshare the file with you.' contains 'Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.'.

**Comment by schiesbn** [comment]
I will look into it

**Comment by schiesbn** [comment]
@owncloud-bot retest this please

**Comment by schiesbn** [comment]
test passed

**Pull request merged**
