### PR TITLE
New colors and CI

### PR DESCRIPTION
**Pull request by ChrisEdS**
## Description
This PR changes the CI color project wide and adds a new background image for the login screen. 
This will adapt ownCloud to the new style guide.

## How Has This Been Tested?

- Manually tested

## Screenshot:
image

## Types of changes

- [x] Non-breaking change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by pmaier1 — APPROVED** [review]

**Comment by phil-davis** [comment]
@pmaier1 should there be a changelog entry written about this?

**Comment by pmaier1** [comment]
> @pmaier1 should there be a changelog entry written about this?

Yes. Thanks for catching that!

**Comment by ChrisEdS** [comment]
> @pmaier1 should there be a changelog entry written about this?

Done.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Note: there are no text strings changed here, so no impact on translations. So this is fine to just be merged into the release branch, and it will "appear" in master when the release branch is merged back to master...

**Comment by phil-davis** [comment]
This gets some crazy fail in webUI tests, e.g. https://drone.owncloud.com/owncloud/core/25720/107/15
```
  Scenario: simple user login                                                                 # /drone/src/tests/acceptance/features/webUILogin/login.feature:23
    Given these users have been created with default attributes and without skeleton files:   # FeatureContext::theseUsersHaveBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
      | username |
      | Alice    |
    When user "Alice" logs in using the webUI                                                 # WebUILoginContext::logInWithUsernameUsingTheWebUI()
      unknown error: session deleted because of page crash
      from tab crashed
        (Session info: chrome=74.0.3729.169)
        (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-106-generic x86_64) (WebDriver\Exception\UnknownError)
    Then the user should be redirected to a webUI page with the title "Files - %productname%" # WebUIGeneralContext::theUserShouldBeRedirectedToAWebUIPageWithTheTitle()
SCENARIO RESULT: (fail)
```

Need to work out why such a simply color changes causes this.

**Comment by phil-davis** [comment]
In #37649 I am adding these changes piece-by-piece to see exactly what triggers the browser crash.

**Comment by phil-davis** [comment]
See #37650 for a new PR that should pass.

**Pull request closed without merging**
