### PR TITLE
[Tests-Only] Test with some unusual usernames

### PR DESCRIPTION
**Pull request by phil-davis**
Trying out this test functionality. This should run the whole test suite with some different usernames, display names etc.

### CODE REVIEW

**Comment by dpakach** [comment]
@phil-davis I have added a commit that should fix the issues with most failing tests except for 
```
tests/acceptance/features/apiShareManagementBasic/createShare.feature:324
```
Since this scenario is actually a bug demonstration, it still fails
issue in https://github.com/owncloud/core/issues/35484

**Comment by phil-davis** [comment]
> Since this scenario is actually a bug demonstration, it still fails

@dpakach I added a special step to cover that scenario, so it understands under which conditions the file should be seen or not seen.

**Comment by phil-davis** [comment]
Code changes from here have been cherry-picked into #37502 to be reviewed and merged.

**Comment by phil-davis** [comment]
Passing acceptance tests - great.

**Pull request closed without merging**
