### PR TITLE
Handle calendar migration issue by writing the faulty event to the lo…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…g and continue

### CODE REVIEW

**Comment by PVince81** [comment]
PR to master, setting milestone to 9.1.

@DeepDiver1975 did you mean this should be backported for 9.0.0 ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 did you mean this should be backported for 9.0.0 ?

to be discussed - I'd vote for yes

**Comment by PVince81** [comment]
@DeepDiver1975 is there a bug report that this fixes ? How critical is the original issue ?

**Comment by DeepDiver1975** [comment]
> is there a bug report that this fixes ?

no



> How critical is the original issue ?

calendar migration stops somewhere in the middle - sev1 from my pov

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by PVince81** [comment]
Code makes sense :+1:

**Comment by cmonteroluque** [comment]
ok, we're doing a few other things, so sure

**Comment by MorrisJobke** [comment]
Reproduced the failing scenario, tested with this branch and it is fixed. Code looks good :+1:

**Pull request merged**
