### PR TITLE
Update TarStreamer to v0.1.0

### PR DESCRIPTION
**Pull request by DeepDiver1975**
requires:
- [x] https://github.com/owncloud/3rdparty/pull/248

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/core/issues/19862

**Comment by PVince81** [comment]
Tested with Firefox, works :+1: 

Had to fiddle with https://github.com/owncloud/core/blob/v8.2.2/lib/private/streamer.php#L40 to make it use tar on linux.

**Comment by DeepDiver1975** [comment]
> Had to fiddle with https://github.com/owncloud/core/blob/v8.2.2/lib/private/streamer.php#L40 to make it use tar on linux.

I use https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by DeepDiver1975** [comment]
will update submodule

**Comment by MorrisJobke** [comment]
Tested on OS X and the tars could be extracted (also with UTF-8 characters)

:+1:

**Pull request merged**
