### PR TITLE
add upgrade command before repair, handle NeedsUpgradeExcaption better

### LINKED ISSUE #26401: Update v9.1.0 to master NeedsUpdateException dav app
### Steps

1. Setup v9.1.0
1. Check out master (a8e96d75a355d71f23093652ce842b5057575447)
1. Run `./occ upgrade`

### Expected
Success?

### Actual
```
An unhandled exception has been thrown:
exception 'OC\NeedsUpdateException' in /srv/www/htdocs/owncloud/lib/private/legacy/app.php:149
Stack trace:
#0 /srv/www/htdocs/owncloud/lib/private/legacy/app.php(121): OC_App::loadApp('dav')
#1 /srv/www/htdocs/owncloud/lib/private/legacy/util.php(135): OC_App::loadApps(Array)
#2 /srv/www/htdocs/owncloud/lib/private/Files/Filesystem.php(260): OC_Util::setupFS(NULL)
#3 /srv/www/htdocs/owncloud/lib/private/Server.php(176): OC\Files\Filesystem::getMountManager(NULL)
#4 /srv/www/htdocs/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#5 /srv/www/htdocs/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('RootFolder')
#6 /srv/www/htdocs/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('RootFolder')
#7 /srv/www/htdocs/owncloud/lib/private/Server.php(784): OC\ServerContainer->query('RootFolder')
#8 /srv/www/htdocs/owncloud/lib/private/Server.php(361): OC\Server->getRootFolder()
#9 /srv/www/htdocs/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#10 /srv/www/htdocs/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('AvatarManager')
#11 /srv/www/htdocs/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AvatarManager')
#12 /srv/www/htdocs/owncloud/lib/private/Server.php(775): OC\ServerContainer->query('AvatarManager')
#13 /srv/www/htdocs/owncloud/lib/private/Repair.php(147): OC\Server->getAvatarManager()
#14 /srv/www/htdocs/owncloud/core/register_command.php(125): OC\Repair::getRepairSteps()
#15 /srv/www/htdocs/owncloud/lib/private/Console/Application.php(88): require_once('/srv/www/htdocs...')
#16 /srv/www/htdocs/owncloud/console.php(98): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /srv/www/htdocs/owncloud/occ(11): require_once('/srv/www/htdocs...')
#18 {main}
```

Note that upgrading from v9.1.1 doesn't have this issue, so not sure if this is important.

In general we recommend people to first update to the last point release before going to the next major release.

@DeepDiver1975 @VicDeo what do you think ?

### PR DESCRIPTION
**Pull request by butonic**
## Description

1. load the upgrade command befor the repair steps
2. catch the NeedsUpdateException and treat it like the needUpgrade() result
## Related Issue

fixes https://github.com/owncloud/core/issues/26401
## How Has This Been Tested?

local with occ throwing an exception before but not after this patch
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by butonic** [comment]
cc @PVince81

**Comment by DeepDiver1975** [comment]
backport?

**Review by phisch — APPROVED** [review]

**Comment by PhilippSchaffrath** [comment]
Can i approve this or should the second :+1:  approve it?

**Comment by butonic** [comment]
@DeepDiver1975 I don't think so, see https://github.com/owncloud/core/issues/26401#issuecomment-255131113. @PVince81 should be able to decide.

**Comment by PVince81** [comment]
I'm not sure a backport is needed because the issue only appeared on master.

On the other hand, if the order is different/wrong on stable9.1 it might make it safer if we fix it there too.
So I'd say: yes, try a backport

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
Backport has conflict and as I see we seem to have changed some message.
Let's not backport then.

**Pull request merged**
