### PR TITLE
Delete compatibility.js

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

Compatibility for older browsers is no longer required
## How Has This Been Tested?
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [x] IE
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
> DeepDiver1975-patch-2

Editing directly on Github ? :suspect:

**Comment by PVince81** [comment]
You missed removing the place where this file is actually loaded. Since I now already booted up IE11 for testing I'll do that for you.

Also we talked about killing placeholder.js, let's see if IE11 tolerates that...

**Comment by DeepDiver1975** [comment]
> Editing directly on Github ? :suspect:

I was bored while waiting for a  call .....

**Comment by PVince81** [comment]
@davitol can you do a quick test in Safari and Edge ? We removed old compatibility shims.
Goal is to find out whether share dialog, some file operations, admin page still work overall.

**Comment by PVince81** [comment]
placeholders kill raised separately: https://github.com/owncloud/core/pull/26443

**Comment by MorrisJobke** [comment]
I assembled just 2 days ago the full list of all the links to the browser compatibility pages:

- `Object.create` supported with IE9+: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/create#Browser_compatibility
- `Object.keys` supported with IE9+: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/keys#Browser_compatibility
- `Array.prototype.filter` supported in IE9+: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#Browser_compatibility
- `Array.prototype.indexOf` supported in IE9+: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf#Browser_compatibility
- `Array.prototype.map` supported in IE9+: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Browser_compatibility
- `Function.prototype.bind` supported in IE9+: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Browser_compatibility
- `String.prototype.trim` supported with IE9+: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim#Browser_compatibility
- `outerHTML` supported with Firefox 11+: https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML#Browser_compatibility
- `window.devicePixelRatio` supported in IE11+: http://caniuse.com/#feat=devicepixelratio

So this looks good 👍  

😉

**Comment by PVince81** [comment]
@MorrisJobke wow, thanks. I had this list in my head... kind of :wink:

**Comment by LukasReschke** [comment]
Yeah. Has to be telepathy or so. _Must_ be it.

**Comment by davitol** [comment]
> @davitol can you do a quick test in Safari and Edge ? We removed old compatibility shims.
> Goal is to find out whether share dialog, some file operations, admin page still work overall.

Tested in Safari 9.1.2 and Edge 38.14 and everything works fine

**Comment by PVince81** [comment]
@davitol thanks!

**Comment by PVince81** [comment]
Regression, please review this fix: https://github.com/owncloud/core/pull/26489

**Pull request merged**
