### PR TITLE
drop global file cache support, fixes #15621

### LINKED ISSUE #15621: Unexpected LDAP errors in server log file
### Steps to reproduce

1. Install 8.0.3 enterprise edition
2. Enable the LDAP app and configure it
3. run smashbox test_uploadFiles.py test in a loop using local users and share_sets = 3

### Expected behaviour

There should be no errors in the server log file

### Actual behaviour

I see errors related to LDAP:

```
{"reqId":"96981d7175c576360c5b2a0f8d505619","remoteAddr":"172.18.5.75","app":"PHP","messa
ge":"unlink(\/tmp\/owncloud-ochewo9lqdny\/LDAP-user_ldap-s01-d94e891c5073ba522188dcd74950
51fe): No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/cache\/file
global.php#58","level":3,"time":"2015-04-14T16:08:49+00:00"}
```

### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0.3 RC1 (testing) and 15577.patch

### PR DESCRIPTION
**Pull request by blizzz**
Also as requested here https://github.com/owncloud/core/pull/15577#issuecomment-92696647

Low latency cache is the better choice anyway and we have a warning/hint in the admin area now. We should raise this also as release note i guess and maybe stress in the LDAP doc.

We may add hint into the LDAP configuration about the cache TTL. This aspect is rather an enhancement, so a topic for 8.2.

Pls review and test: @DeepDiver1975 @jnfrmarks @MorrisJobke

### CODE REVIEW

**Comment by jnfrmarks** [comment]
@jvillafanez 

Can you please validate this?

**Comment by jvillafanez** [comment]
@blizzz I'm seeing some "LDAP-Proxy-<id>" in the /tmp/owncloud-something directory. Is this expected?

Other than that, I'm not seeing anything weird

**Comment by MorrisJobke** [comment]
Works. Also the upgrade from an existing version without an memcache works fine :+1:

**Comment by DeepDiver1975** [comment]
nice @blizzz - THX :+1:

**Comment by DeepDiver1975** [comment]
as a result we can now kill https://github.com/owncloud/core/blob/master/lib/private/cache.php as well

**Comment by DeepDiver1975** [comment]
grr - I was too fast ... 

@blizzz the cache is also used in the proxy class https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/proxy.php#L45

I should have read this comment more in depth https://github.com/owncloud/core/pull/16170#issuecomment-100151932

**Comment by blizzz** [comment]
@jvillafanez Good catch! Totally forgot about the piece in the proxy. Will open another PR for this.

**Comment by blizzz** [comment]
Would be nice to have a runtime cache as a fallback. For next release maybe?

**Comment by LukasReschke** [comment]
> Would be nice to have a runtime cache as a fallback. For next release maybe?

Users can configure the ArrayCache https://github.com/owncloud/core/blob/ebf3953908a8dfdb754a5031d69326c6b83cf609/config/config.sample.php#L820

**Comment by blizzz** [comment]
@LukasReschke thx, have not noticed this went in.

**Pull request merged**
