### PR TITLE
Simply hide sharing buttons for IE8 

### LINKED ISSUE #18011: IE8 issue with gs-sharejs
````
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
Timestamp: Fri, 31 Jul 2015 14:43:27 UTC


Message: Object doesn't support this property or method
Line: 6
Char: 1
Code: 0
URI: http://alien.fritz.box:8080/apps/files_sharing/js/3rdparty/gs-share/gs-share.js?v=b02269f5bca3c4c7370dce5296c8c557

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #18011

@PVince81 @nickvergessen @schiesbn @jancborchardt @MorrisJobke please review and test

@karlitschek issue is in 8.1 as well - backport? THX

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
Works :+1:

**Comment by PVince81** [comment]
Wait, that is not enough. You need to prevent loading gs-share.js

**Comment by PVince81** [comment]
:-1:

**Comment by PVince81** [comment]
IE8 still shows warnings for gs-share.js, so there is a risk of breaking other JS

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
backport is fine.

**Comment by PVince81** [comment]
Tested, no more warnings :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
