### PR TITLE
Check whether ownCloud is installed

### LINKED ISSUE #21955: Master web installation is broken
Took me 40 minutes to realize that master is broken and not the release script that I'm trying to run locally here…

```
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: oc_preferences' in /Users/lukasreschke/Documents/Programming/release-test/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
Stack trace:
#0 /Users/lukasreschke/Documents/Programming/release-test/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('SELECT "appid",...', Array)
#1 /Users/lukasreschke/Documents/Programming/release-test/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(825): Doctrine\DBAL\Driver\PDOConnection->prepare('SELECT "appid",...')
#2 /Users/lukasreschke/Documents/Programming/release-test/lib/private/db/connection.php(183): Doctrine\DBAL\Connection->executeQuery('SELECT "appid",...', Array, Array, NULL)
#3 /Users/lukasreschke/Documents/Programming/release-test/lib/private/allconfig.php(338): OC\DB\Connection->executeQuery('SELECT `appid`,...', Array)
#4 /Users/lukasreschke/Documents/Programming/release-test/lib/private/allconfig.php(242): OC\AllConfig->getUserValues('')
#5 /Users/lukasreschke/Documents/Programming/release-test/lib/private/l10n/factory.php(112): OC\AllConfig->getUserValue('', 'core', 'lang')
#6 /Users/lukasreschke/Documents/Programming/release-test/lib/private/l10n/factory.php(86): OC\L10N\Factory->findLanguage('lib')
#7 /Users/lukasreschke/Documents/Programming/release-test/lib/private/server.php(836): OC\L10N\Factory->get('lib', NULL)
#8 /Users/lukasreschke/Documents/Programming/release-test/lib/base.php(250): OC\Server->getL10N('lib')
#9 /Users/lukasreschke/Documents/Programming/release-test/lib/base.php(575): OC::checkConfig()
#10 /Users/lukasreschke/Documents/Programming/release-test/lib/base.php(1094): OC::init()
#11 /Users/lukasreschke/Documents/Programming/release-test/index.php(37): require_once('/Users/lukasres...')
#12 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: oc_preferences' in /Users/lukasreschke/Documents/Programming/release-test/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79
Stack trace:
#0 /Users/lukasreschke/Documents/Programming/release-test/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(825): Doctrine\DBAL\Driver\PDOConnection->prepare('SELECT "appid",...')
#1 /Users/lukasreschke/Documents/Programming/release-test/lib/private/db/connection.php(183): Doctrine\DBAL\Connection->executeQuery('SELECT "appid",...', Array, Array, NULL)
#2 /Users/lukasreschke/Documents/Programming/release-test/lib/private/allconfig.php(338): OC\DB\Connection->executeQuery('SELECT `appid`,...', Array)
#3 /Users/lukasreschke/Documents/Programming/release-test/lib/private/allconfig.php(242): OC\AllConfig->getUserValues('')
#4 /Users/lukasreschke/Documents/Programming/release-test/lib/private/l10n/factory.php(112): OC\AllConfig->getUserValue('', 'core', 'lang')
#5 /Users/lukasreschke/Documents/Programming/release-test/lib/private/l10n/factory.php(86): OC\L10N\Factory->findLanguage('lib')
#6 /Users/lukasreschke/Documents/Programming/release-test/lib/private/server.php(836): OC\L10N\Factory->get('lib', NULL)
#7 /Users/lukasreschke/Documents/Programming/release-test/lib/base.php(250): OC\Server->getL10N('lib')
#8 /Users/lukasreschke/Documents/Programming/release-test/lib/base.php(575): OC::checkConfig()
#9 /Users/lukasreschke/Documents/Programming/release-test/lib/base.php(1094): OC::init()
#10 /Users/lukasreschke/Documents/Programming/release-test/index.php(37): require_once('/Users/lukasres...')
#11 {main}

Next exception 'Doctrine\DBAL\Exception\TableNotFoundException' with message 'An exception occurred while executing 'SELECT "appid", "configkey", "configvalue" FROM "oc_preferences" WHERE "userid" = ?' with params [""]:

SQLSTATE[HY000]: General error: 1 no such table: oc_preferences' in /Users/lukasreschke/Documents/Programming/release-test/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:58
Stack trace:
#0 /Users/lukasreschke/Documents/Programming/release-test/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /Users/lukasreschke/Documents/Programming/release-test/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT "appid",...', Array)
#2 /Users/lukasreschke/Documents/Programming/release-test/lib/private/db/connection.php(183): Doctrine\DBAL\Connection->executeQuery('SELECT "appid",...', Array, Array, NULL)
#3 /Users/lukasreschke/Documents/Programming/release-test/lib/private/allconfig.php(338): OC\DB\Connection->executeQuery('SELECT `appid`,...', Array)
#4 /Users/lukasreschke/Documents/Programming/release-test/lib/private/allconfig.php(242): OC\AllConfig->getUserValues('')
#5 /Users/lukasreschke/Documents/Programming/release-test/lib/private/l10n/factory.php(112): OC\AllConfig->getUserValue('', 'core', 'lang')
#6 /Users/lukasreschke/Documents/Programming/release-test/lib/private/l10n/factory.php(86): OC\L10N\Factory->findLanguage('lib')
#7 /Users/lukasreschke/Documents/Programming/release-test/lib/private/server.php(836): OC\L10N\Factory->get('lib', NULL)
#8 /Users/lukasreschke/Documents/Programming/release-test/lib/base.php(250): OC\Server->getL10N('lib')
#9 /Users/lukasreschke/Documents/Programming/release-test/lib/base.php(575): OC::checkConfig()
#10 /Users/lukasreschke/Documents/Programming/release-test/lib/base.php(1094): OC::init()
#11 /Users/lukasreschke/Documents/Programming/release-test/index.php(37): require_once('/Users/lukasres...')
#12 {main}Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```
Regression caused by https://github.com/owncloud/core/pull/21741

### PR DESCRIPTION
**Pull request by LukasReschke**
ownCloud might not yet be setup. This causes an issue as the user config requires a setup ownCloud. Thus this needs a block whether ownCloud is installed or not.

(most of the changes are unit-tests adjustments)

Fixes https://github.com/owncloud/core/issues/21955

<hr/>

@nickvergessen @rullzer THX.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by PVince81** [comment]
:+1:

**Comment by redhell** [comment]
PHP Fatal error:  Cannot redeclare class OC_L10N in ../lib/private/l10n.php on line 41 @latest master after applying your patch using PHP7

**Comment by DeepDiver1975** [comment]
> PHP Fatal error: Cannot redeclare class OC_L10N in ../lib/private/l10n.php on line 41 @latest master after applying your patch using PHP7

looks like the class exists twice - maybe error on patch apply?

I suggest to use git to switch branches - makes life easier

**Comment by redhell** [comment]
@DeepDiver1975 Yep, that was it

**Pull request merged**
