### PR TITLE
[stable8] don't update identical values

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #15549 

cc @icewind1991 @DeepDiver1975 @nickvergessen

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
A unit test would have been nice, but as we cannot mock the database part we cannot count how many updates have been done.

Anyway, looks good :+1:

**Comment by rperezb** [comment]
Checked by @SergioBertolinSG

**Comment by jvillafanez** [comment]
Checking data from OC 8.0.3:

screenshot from 2015-05-29 14 22 37

Data from OC 8.0.4 (?) - current stable8:

screenshot from 2015-05-29 14 22 10

Same test, Same environment. Looks like there is some improvement

**Pull request merged**
