### PR TITLE
Users are available under it's own principal resource named 'principa…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…ls/users' this will allow us to introduce e.g. groups as principals (one day) and system specific principals (needed for federation)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
YES - litmus tests are passing finally

@icewind1991 @PVince81 @blizzz @schiesbn @rullzer please review

**Comment by icewind1991** [comment]
```
dav:/owncloud/remote.php/dav/> ls principals/users
Listing collection `/owncloud/remote.php/dav/principals/users/': failed:
404 Not Found
```

Intended?

**Comment by PVince81** [comment]
@icewind1991 might be a security feature. I remember a discussion about it where it was said that it can only be listed in debug mode. Not sure if that's the case though.

**Comment by rullzer** [comment]
> @icewind1991 might be a security feature. I remember a discussion about it where it was said that it can only be listed in debug mode. Not sure if that's the case though.

Nope not the case. Would make sense to allow listing there as well in debug mode

**Comment by rullzer** [comment]
@DeepDiver1975 how can I test this? navigation to principals/users/admin/ does not work either...

**Comment by DeepDiver1975** [comment]
hmmmm ... I'll look into this ... THX for testing

**Comment by DeepDiver1975** [comment]
@icewind1991 @rullzer @PVince81 please test again - thx

**Comment by DeepDiver1975** [comment]
> @icewind1991 @rullzer @PVince81 please test again - thx

all green - let's get this in please

**Comment by rullzer** [comment]
See them appear now!

However I do get 404 for
* calendar-proxy-read
* calendar-proxy-write

in the user folder (under principals/users).

Will that be handled later?

**Comment by DeepDiver1975** [comment]
> However I do get 404 for
> 
>     calendar-proxy-read
>     calendar-proxy-write
> 
> in the user folder (under principals/users).
> 
> Will that be handled later?

this happens forever - not critical

**Comment by rullzer** [comment]
Ok, :+1: then

**Comment by icewind1991** [comment]
:+1: 

Could this be used in the future for doing user management over DAV?

```
MKCOL remote.php/dav/principals/users/foo
COPY remote.php/dav/principals/users/foo remote.php/dav/principals/groups/testgroup/foo
```

**Comment by PVince81** [comment]
That would be cool. If the Webdav spec also says so. :smile:

**Comment by LukasReschke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> Could this be used in the future for doing user management over DAV?

technically possible - atleast the creation and modification of users and groups

**Pull request merged**
