### PR TITLE
Change remote to federated in autocomplete dialog.

### PR DESCRIPTION
**Pull request by Lutacon**
## Description

Rename "Remote" for "Federated" in autocomplete dialog. I have only changed the string on the JS/PHP because I read there is a bot which replaces the other strings, is that correct?

## Related Issue
https://github.com/owncloud/core/issues/29015

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by sharidas** [comment]
@Lutacon Kindly assign the PR to yourself. Also set the Label to "3- To Review", If you intend this PR for review. Or to any suitable label. Also set the milestone to "Development".

**Comment by Lutacon** [comment]
@sharidas What if I told you I can't do anything about those things. I think I don't have any permission for that.

**Comment by phil-davis** [comment]
True, without write access to the core repo, you can't set labels, milestones...
I did that for you just now. @PVince81 should be back "soon" for the New Year...

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
I've restarted the Travis builds, hoping that this was a one-off timeout thing...

**Comment by Lutacon** [comment]
@PVince81  Is it something else? A problem with my changes?

**Comment by phil-davis** [comment]
The UI tests fail on Travis because this is a PR coming from another forked repo. The job does not have access to the ownCloud SauceLabs credentials.
I pushed the branch into my fork, where I have my own SauceLabs credentials. That should demonstrate the UI tests pass:
https://github.com/phil-davis/core/pull/136

**Comment by phil-davis** [comment]
UI Tests pass in https://github.com/phil-davis/core/pull/136

**Comment by PVince81** [comment]
@phil-davis can you do the backport ?

**Comment by phil-davis** [comment]
Backport stable10 #30046

**Pull request merged**
