### PR TITLE
[stable10] Webdav locking frontend

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/32250 to stable10.

There was an easy to solve conflict in behat file because of multiple added new suites.

### CODE REVIEW

**Comment by PVince81** [comment]
I wonder what's different on stable10...

```
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Files.LockPlugin tests Webdav requests parses lock information from response XML to JSON FAILED
	TypeError: undefined is not an object (evaluating 'this.dirInfo.permissions') in apps/files/js/filelist.js (line 1671)
	reloadCallback@apps/files/js/filelist.js:1671:20
	[native code]
	core/vendor/jquery/dist/jquery.min.js:2:56437
	j@core/vendor/jquery/dist/jquery.min.js:2:27194
	fireWith@core/vendor/jquery/dist/jquery.min.js:2:54761
	core/vendor/jquery/dist/jquery.min.js:2:56856
	core/js/files/client.js:9:18585
	core/vendor/jquery/dist/jquery.min.js:2:56437
	j@core/vendor/jquery/dist/jquery.min.js:2:27194
	fireWith@core/vendor/jquery/dist/jquery.min.js:2:54761
	core/vendor/jquery/dist/jquery.min.js:2:56856
apps/files/tests/js/filelockpluginSpec.js:185:27
```

**Comment by PVince81** [comment]
I hope we didn't forget a backport...

**Comment by PVince81** [comment]
as discussed with @DeepDiver1975 in chat we will merge https://github.com/owncloud/core/pull/33544 for 10.1

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by PVince81** [comment]
web ui lock tests fail, just like on https://github.com/owncloud/core/pull/33888#issuecomment-449036712

maybe broken on stable10 ?

**Pull request merged**
