### PR TITLE
consolidate all admin warnings and notices into one section

### LINKED ISSUE #14519: Admin page needs return to top
Admin page needs a link that goes back to the top. We have all the links to the sections on the left (LOVE IT!!! SUPER!!!) but we don't link back to the top of the page.

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #14519. Using the header »Security & setup warnings« like in the sidebar. And putting all the notices in one section instead of a section for each and every warning.

@DeepDiver1975 @LukasReschke is there a way I can trigger all the warnings at once so I can check if the layout looks good?

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by LukasReschke** [comment]
> @DeepDiver1975 @LukasReschke is there a way I can trigger all the warnings at once so I can check if the layout looks good?

Change the if in the template, for example ` if ($_['databaseOverload']) {` in `if(true)` or something that always will result in a true :smile:

**Comment by jancborchardt** [comment]
Please retest @LukasReschke @owncloud/designers

**Comment by MorrisJobke** [comment]
Looks weird. Can we use a consistent style: 
bildschirmfoto von 2015-03-24 11 34 57

**Comment by karlitschek** [comment]
yes. would be good to have a consistent style. And I still think that the bullets should be intended. :-) See here as example: http://en.wikipedia.org/wiki/Bullet_(typography)

**Comment by MorrisJobke** [comment]
Missed to refresh hard enough. Now looks good, except the read heading. @jancborchardt is fixing this :+1:

**Comment by jancborchardt** [comment]
@MorrisJobke cool!

@karlitschek good point linking the Wikipedia article. See their »Further Reading« section: [Five simple steps to better typography - Part 2: Hanging punctuation](http://www.markboulton.co.uk/journal/five-simple-steps-to-better-typography-part-2) – illustrates my point nicely. ;)

**Comment by MorrisJobke** [comment]
Still :+1:

**Comment by MorrisJobke** [comment]
@rullzer @Xenopathic @oparoz Easy to review ;)

**Comment by rullzer** [comment]
I did not check all the induvidial cases but it looks good.
However, rebase time!

**Comment by nickvergessen** [comment]
:+1: from me aswell

**Comment by jancborchardt** [comment]
Rebased, waiting for Jenkins.

**Comment by MorrisJobke** [comment]
Still works :+1:

**Comment by MorrisJobke** [comment]
Nickvergessen works on this, because master is broken :(

**Pull request merged**
