### PR TITLE
Keep up occ command working if redis is down or misconfigured

### LINKED ISSUE #35637: occ command competely broken if misconfigured redis IP in config.php
Steps to reproduce
Add a wrong Redis IP to ownClouds config.php (e.g. a valid IP but no Redis running on it) and try to use any `occ ...` command. Result:

```
$ occ
An unhandled exception has been thrown:
RedisException: No route to host in /var/www/owncloud/lib/private/RedisFactory.php:81
Stack trace:
#0 /var/www/owncloud/lib/private/RedisFactory.php(81): Redis->connect('192.168.122.8', '6379', 0)
#1 /var/www/owncloud/lib/private/RedisFactory.php(101): OC\RedisFactory->create()
#2 /var/www/owncloud/lib/private/Memcache/Redis.php(37): OC\RedisFactory->getInstance()
#3 /var/www/owncloud/lib/private/Memcache/Factory.php(131): OC\Memcache\Redis->__construct('545493d4e8fd57a...')
#4 /var/www/owncloud/lib/private/Server.php(724): OC\Memcache\Factory->createLocking('lock')
#5 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#6 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): Pimple\Container->offsetGet('LockingProvider')
#7 /var/www/owncloud/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query('LockingProvider')
#8 /var/www/owncloud/lib/private/Server.php(1488): OC\ServerContainer->query('LockingProvider')
#9 /var/www/owncloud/lib/private/Files/View.php(120): OC\Server->getLockingProvider()
#10 /var/www/owncloud/lib/private/Server.php(173): OC\Files\View->__construct()
#11 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#12 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): Pimple\Container->offsetGet('EncryptionManag...')
#13 /var/www/owncloud/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query('EncryptionManag...')
#14 /var/www/owncloud/lib/private/Server.php(919): OC\ServerContainer->query('EncryptionManag...')
#15 /var/www/owncloud/lib/base.php(751): OC\Server->getEncryptionManager()
#16 /var/www/owncloud/lib/base.php(665): OC::registerEncryptionWrapper()
#17 /var/www/owncloud/lib/base.php(994): OC::init()
#18 /var/www/owncloud/console.php(64): require_once('/var/www/ownclo...')
#19 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
```
This is a very bad case if you rely on `occ` for ownCloud deployment automation and you will not be able to fix misconfigured values.

Actual behavior

`occ` hardly fails with wrong or not responding redis IP in config.php

Operating system: RHEL 7

Web server: apache

Database: mysql

PHP version: 7.2

ownCloud version: 10.2.0

Updated from an older ownCloud or fresh install: fresh

Where did you install ownCloud from: tarball

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
The @ error control operator was not quite helpful, as errors still was thrown, as well we exit the function now, as we don't want to execute the lower code.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/35637

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
@xoxys Please keep in mind, based on the timeout, occ commands might be pretty slow

**Comment by xoxys** [comment]
> @xoxys Please keep in mind, based on the timeout, occ commands might be pretty slow

Thanks! Is the timeout configurable?

**Comment by JanAckermann** [comment]
TBD: we should fairly log connection errors

**Review by jvillafanez — APPROVED** [review]
Just a little detail, assuming the rest works.

**Review by phil-davis — COMMENTED** [review]
LGTM - just remove the unused `use` and rebase to get a green CI result.

**Review by phil-davis — APPROVED** [review]

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliAppManagement-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33018/119/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingExt1-latest-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33018/155/1

**Comment by jvillafanez** [comment]
> @jvillafanez Can you reevaluate, I needed to surround all the redis commands in try catches to make commands work fluent, even if a timeout is set

I'm not sure if that's a good idea. The problem I see is that we don't have a way to know if there has been an error in redis. If a method returns `false`, does it return `false` because it has to return `false` or because there has been an error?

I think this has more consequences across all the code and we need to check anywhere where this class is being used.

Error handling isn't defined in the interface, and it's a big problem. The assumptions that have been steam from the interface might be no longer true with these changes

**Comment by JanAckermann** [comment]
@jvillafanez Yes, I am a bit unsure about this too! The WebClient is trowing and exception much more higher in the stack 'OC\Session\Memory->validateSession()'. 
The intentional way with this PR did not really fix the issue @xoxys mentions reliable and I don't know if we will find a suitable solution.

**Pull request closed without merging**
