### PR TITLE
Remove apps/files/appinfo/remote.php - this is no longer used

### LINKED ISSUE #19865: [pre-alpha 9] Client can't connect: OCA\\DAV\\Connector\\Sabre\\ServerFactory
I'm just testing the new testpilot & nightly build of OC. The client can't connect:
````
PHP Fatal error:  Class 'OCA\\DAV\\Connector\\Sabre\\ServerFactory' not found in /var/www/owncloud/apps/files/appinfo/remote.php on line 35
````
Nightly build is on Debian 8.0 installed from SuSE-repos:
ownCloud 9.0 pre alpha (daily) Build:2015-10-19T03:42:58+00:00 8d25528c49bfaa72873cad3e06188e3484ef552b

If this is due to work in progress, please close this.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@MorrisJobke 

Fix https://github.com/owncloud/core/issues/19865

### CODE REVIEW

**Comment by karlitschek** [comment]
we need a migration story here. We can't just remove it and expect that people figure this out on their own.
Can we keep it for legacy users for a while?

**Comment by DeepDiver1975** [comment]
> we need a migration story here.

I'll  look into it ... as soon as the new dav app is enabled the remote entry in the db has to be updated and redirected to the remote.php file in the dav app.

**Comment by DeepDiver1975** [comment]
Looks like we miss an upgrade to be executed ....

**Comment by MorrisJobke** [comment]
I tried this. After a clean install the app `dav`is not enabled. And the error message is not very helpful:

bildschirmfoto 2015-10-16 um 17 09 47


And once enabled. The request doesn't get a response, but times out.

**Comment by DeepDiver1975** [comment]
> After a clean install the app davis not enabled.

On a clean install the app should be enabled because of enabled_default in info.xml

**Comment by DeepDiver1975** [comment]
okay - this mechanism is broken as well :imp:

**Comment by DeepDiver1975** [comment]
> okay - this mechanism is broken as well :imp:

... because the dav app has no app.php

**Comment by karlitschek** [comment]
do you mean http redirect? Not sure if every client follows redirects.

**Comment by DeepDiver1975** [comment]
> do you mean http redirect? Not sure if every client follows redirects.

no - any request is issued against remote.php (the one living in the root) - in that code we do a look up to find out about the file which implements the call. this information is defined in appinfo/info.xml and stored in the database.

**Comment by karlitschek** [comment]
got it. Should work. 
Smells like a DB call that could be removed in the future by the way. :imp:

**Comment by DeepDiver1975** [comment]
> okay - this mechanism is broken as well :imp:
> 
> ... because the dav app has no app.php

https://github.com/owncloud/core/pull/19843

**Comment by PVince81** [comment]
:+1: webdav still works

**Comment by DeepDiver1975** [comment]
@MorrisJobke mind testing? THX

**Comment by MorrisJobke** [comment]
Tested and works :+1: (on this branch only if I enable day app by hand, but this was fixed buy another PR)

**Pull request merged**
