### PR TITLE
simpler style for filetype icons

### PR DESCRIPTION
**Pull request by jancborchardt**
Before:
capture du 2015-08-27 19-21-24
After:
capture du 2015-08-27 19-20-31

Please review @owncloud/designers @karlitschek @PVince81 @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks really nice :+1:

**Comment by enoch85** [comment]
Wow, nice! :+1:

**Comment by MorrisJobke** [comment]
Images only and one image definition list -> merge

**Comment by jancborchardt** [comment]
AWESOME :))))

**Comment by oparoz** [comment]
This is what broke tests in Gallery. We still need two image types, vector and bitmap. They're very different types which require different apps, etc.

**Comment by jancborchardt** [comment]
@oparoz there is a redirect in the mimetypelist.js though which makes the image thumbnail be used for vectors as well.

**Comment by oparoz** [comment]
Then that needs to be changed as well :)

**Comment by jancborchardt** [comment]
We don’t really need to make the distinction in the interface though. Most bitmaps will actually get a preview generated anyway. And we should work to also get previews for the vector formats done.

**Comment by oparoz** [comment]
I've just had a look and there are several issues :
1. The decision as to which file type gets it own icon is arbitrary. Why a pdf icon and not a generic office document? etc. A SVG or AI fie is not like a JPG and they do require extra components to be installed to be viewed in ownCloud
2. Font files are not images, nor are they text files
3. What was so wrong about the old approach? It's OK to have a nicer set of icons which look like they came from the same pack, but why remove some of the types at the same time?
4. The dist file still uses the old aliases. https://github.com/owncloud/core/blob/master/config/mimetypealiases.dist.json#L14
5. @rullzer Why is the dist file not used when an app is requesting the mimeicon? Is there still wip for the new way to retrieve icons?

**Comment by rullzer** [comment]
@oparoz probably because the stuff was not updated using occ.

```./occ maintenance:mimetypesjs```

And you are correct that the dist files need to be updated!

**Comment by oparoz** [comment]
Got it. Actually, RTFM shows me that it's the other way around. The template is the dist file. The file edited in this PR gets overwritten.

> /**
* This file is automatically generated
* DO NOT EDIT MANUALLY!
*
* You can update the list of MimeType Aliases in config/mimetypealiases.json
* The list of files is fetched from core/img/filetypes
* To regenerate this file run ./occ maintenance:mimetypesjs
*/

**Comment by oparoz** [comment]
So, @jancborchardt will re-introduce a couple of icons and the dist file will be used to generate the js file.

**Pull request merged**
