### PR TITLE
revert logic to expose free_space, but keep availableStorage config

### PR DESCRIPTION
**Pull request by phil-davis**
This is a copy of PR #40669 with the conflict resolved.

The original PR text was:

- fixes https://github.com/owncloud/core/issues/40665
- related https://github.com/owncloud/enterprise/issues/5006 , https://github.com/owncloud/core/pull/40389
- needed for https://github.com/owncloud/metrics/pull/159

The issue here is that originally when doing https://github.com/owncloud/core/pull/40389 I somehow mixed the storage_id for S3 bucket with the user urns storage_id's . So when matching with filecache I though it represents that one. 

However I was wrong, and used the wrong storage .. also the correct filecache entry for the entire bucket is always showing 0 size. 

In this PR, I just expose the config entry for availableStorage, so that apps could use it. Please note that this PR reverts logic to expose this on storage level, so all "quota" calculations wont work. If we want to make it work on storage level, something like background job that calculates this size would need to be done. However, metrics app does not require that complexity and it can simply just use that parameters as in https://github.com/owncloud/metrics/pull/159

### CODE REVIEW

**Comment by mrow4a** [comment]
@phil-davis why do we duplicate this? I fixed my PR..

**Comment by phil-davis** [comment]
> @phil-davis why do we duplicate this? I fixed my PR..

GitHub reports a conflict with your PR. You can rebase your PR and resolve the conflict.

**Comment by phil-davis** [comment]
I see that you have rebased a few minutes ago - good.

**Comment by jnweiger** [comment]
I'd like to have this in the release-10.12.0-branch -- 
Initially, i wanted to retarget the original PR, but then I saw that @phil-davis already made a 'duplicate' tpointing into the release branch. 

So fine with me to have them both, one into master, an one into the release branch.

**Comment by phil-davis** [comment]
Sorry for the confusion. @mrow4a changed his PR to target `release-10.12.0` just after I made this PR.

But I see that @jnweiger changed that PR #40669 back to target `master` late yesterday.

IMO we should just merge something to `release-10.12.0` and it will get merged into `master` later. If we merge PRs into both branches then we are going to get annoying conflicts later, because the changelog files might be in different places.

**Comment by phil-davis** [comment]
Somebody please review, and we can merge...

**Comment by mrow4a** [comment]
@phil-davis I did not change branch in my PR, I just rebased when seeing conflicts.

**Comment by mrow4a** [comment]
@phil-davis @jnweiger please note that I also squashed commits. Be careful not to diverge PRs too much, because it could lead to mismatch between oc-master and oc-10-12

**Comment by phil-davis** [comment]
@jnweiger @pako81 please decide what is happening and merge something.

**Comment by jvillafanez** [comment]
Changes in the l10n files don't look good.

It might be better to start over. Get a fresh branch from the latest release-10.12.0 branch, put the commits there and open a new PR against the release branch.

The changes in the logic are ok since we need to fix the issue.

**Pull request closed without merging**
