### PR TITLE
[Stable7] app upgrade order fix

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/13865 to stable7

@blizzz @DeepDiver1975 @icewind1991 @karlitschek @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
Should we merge this ? Or wait for 7.0.6 maybe ?

**Comment by karlitschek** [comment]
should be safe to merge now

**Comment by LukasReschke** [comment]
That is a nasty one but certainly makes sense. As this is against stable7 the static non-testable code path looks okay :+1:

**Comment by MorrisJobke** [comment]
I did an upgrade from 7.0.4 to this branch with all core apps and music, maps, news, contacts and calendar enabled -> works fine. No errors in log :+1:

**Pull request merged**
