### PR TITLE
Fix private member access of parent class in ocsresponse

### PR DESCRIPTION
**Pull request by MorrisJobke**
- noticed while checking PHPDoc

see https://github.com/owncloud/core/blob/ac133e9faa0a3568716596e83c5ff0993c8dcf89/lib/public/appframework/http/response.php#L63

cc @LukasReschke @Raydiation

### CODE REVIEW

**Comment by Raydiation** [comment]
:+1: it was broken right? There should have been warnings when overriding parent variables.

**Comment by MorrisJobke** [comment]
> There should have been warnings when overriding parent variables.

There was a big red warning in PHPStorm ;)

**Comment by MorrisJobke** [comment]
> it was broken right?

yes

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
