### PR TITLE
Minor update to the description of the root variable

### PR DESCRIPTION
**Pull request by oparoz**
After having lost time trying to get search() working, I thought it would be good to mention that the root variable should never end with a slash.
It's not something which can be solved via code.

@PVince81 @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
Sorry @oparoz, I think this isn't 100% accurate
That class is super messed-up and there are cases where you need to add a trailing slash, if you miss it it will mess up other parts of the code.

See https://github.com/owncloud/core/issues/16478

Still, I appreciate the thought :smile:

**Comment by oparoz** [comment]
Yeah, I knew you were working on that :)

But if you add a slash, search() doesn't work any more... https://github.com/owncloud/core/issues/16548

**Comment by PVince81** [comment]
Gargll... this pretty much illustrates how broken this API is.

**Comment by PVince81** [comment]
@oparoz maybe we can fix search to add the missing trailing slash ? (short term)

**Comment by oparoz** [comment]
Well, it's more of a matter of removing it
https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L1355

but it breaks tests..

**Comment by oparoz** [comment]
Broken tests
```
10) Test\Files\View::testSearch
Failed asserting that 4 matches expected 6.
/tests/lib/files/view.php:255
11) Test\Files\View::testSearchNotOutsideView
Failed asserting that actual size 0 matches expected size 1.
/tests/lib/files/view.php:503
```

**Comment by PVince81** [comment]
@oparoz maybe the tests need fixing too ?

**Comment by oparoz** [comment]
Indeed, but it didn't seem trivial to me and that's not my area of expertise, so I think it would be best it someone else took a look.

**Comment by PVince81** [comment]
That's fine. Let's mark this as bug then to be looked into.

**Comment by MorrisJobke** [comment]
@oparoz needs a rebase

**Comment by oparoz** [comment]
Not sure that should even be merged given the work being done in https://github.com/owncloud/core/issues/16478

**Comment by MorrisJobke** [comment]
> Not sure that should even be merged given the work being done in #16478

Then we should maybe simply close this one :see_no_evil: cc @PVince81

**Comment by MorrisJobke** [comment]
Let's close it for now.

**Pull request closed without merging**
