### PR TITLE
[WIP] make jQuery UI look more like ownCloud

### PR DESCRIPTION
**Pull request by jancborchardt**
This fixes the LDAP settings looking out of place, and also adds a header.

It includes a front-port of @LukasReschke’s https://github.com/owncloud/core/pull/10998

Please test @blizzz @LukasReschke @owncloud/designers 

Please also test @raghunayyar @georgehrke if this works with the Calendar which also uses jQuery UI.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jancborchardt what's the status on this? THX

**Comment by PVince81** [comment]
Something to revive? (and rebase)

**Comment by jancborchardt** [comment]
Yeah … for 8.2

**Comment by MorrisJobke** [comment]
> Yeah … for 8.2

Last chance the next days. But I would like to get this merged early in the 9.0 development cycle.

**Comment by jancborchardt** [comment]
Honestly I would like to get rid of jQuery UI completely instead. The only place where we use it is LDAP (cc @blizzz) and Calendar (cc @georgehrke @raghunayyar).

For Calendar, I assume rework will take care of removing these components.

For LDAP, it only needs the tabs – so we should handle that exactly like the Files sidebar handles tabs. Ok @blizzz?

**Comment by PVince81** [comment]
@jancborchardt close ?
Is there a ticket to make the LDAP wizard move away from jquery.ui ?

**Comment by blizzz** [comment]
> For LDAP, it only needs the tabs – so we should handle that exactly like the Files sidebar handles tabs. Ok @blizzz?

We also use the accordion. As discussed, when can log into getting rid of jQueryUI for 9.0. I'd say: new ticket as enhancement request and close this one here.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/issues/18739

**Pull request closed without merging**
