### PR TITLE
Prevent bkg scanner going crazy with unavailable storages (ajax/scan.php)

### LINKED ISSUE #18480: ajax/scan.php goes crazy when storage temp not available
### Steps

1. Let there be two users "user1@A" and "user2@B" where A and B are two separate ownCloud instances
1. Login as "user1@A"
1. Share a new folder "test" with "user2@B".
1. As "user2@B" accept the share and let it appear as "/test" in the root
1. Turn off / enable maintenance mode on A
1. Refresh the page
1. Observe the network console

### Expected result
scan.php only runs once

### Actual result
scan.php appears several times, every few seconds.

### Versions
ownCloud 8.2 git master 510010e774c4019b7fc616c90085649abb7afac3

I haven't tested with other storages, but it could potentially happen for any storage that throws StorageNotAvailableException.

We could get rid of scan.php, see https://github.com/owncloud/core/issues/17906

Or at least make it more robust.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/18480

### CODE REVIEW

**Comment by PVince81** [comment]
Please review @icewind1991 @Xenopathic @nickvergessen

**Comment by PVince81** [comment]
Steps:

1. Create a federated share
1. Mount it as recipient
1. Delete the original share as owner (it moves to trash)
1. As recipient, refresh the file list in the web UI and check the network console
1. If nothing happens, set "-1" in the "size" column of the matching "shared::xxxx" storage, then refresh the web UI again

Before this fix: scanner would rerun every second
After this fix: scanner bails out

**Comment by Xenopathic** [comment]
:+1: LGTM

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
