### PR TITLE
Revert "Detect Docker initialization properly"

### PR DESCRIPTION
**Pull request by DeepDiver1975**
This reverts commit 8467dbfa91921ccb0262161360edbf339f6b7daa.

This change causes issues on Jenkins and (at least for me) locally.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@Xenopathic we have to find a different mechanism to detect a service being up and running - nc *at least as called as of now* does not work

**Comment by DeepDiver1975** [comment]
@PVince81 @MorrisJobke @LukasReschke please review - thx

**Comment by PVince81** [comment]
Ceph docker still works :+1:

**Comment by Xenopathic** [comment]
This *will* break: @MorrisJobke and @butonic have experience with this, the timeout is really unpredictable.

@DeepDiver1975 What exactly is going wrong?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 What exactly is going wrong?

the while loop with nc is never executed - so that bloody script is not waiting for the service to be available

**Comment by DeepDiver1975** [comment]
e.g.

https://ci.owncloud.org/job/server-master-linux-externals-ci/database=sqlite,external=webdav-ownCloud,label=vm-slave-02/3959/console

````
07:49:10 Digest: sha256:b7dfcfbeb38649bd41c8a5a8612c458b3010d18d63d13a24a1523ca5ce1f4a36
07:49:10 Status: Image is up to date for morrisjobke/owncloud:latest
07:49:10 Waiting for ownCloud initialization
07:49:11 ownCloud container: de40b8ee58ea2bdf497ee97776882cfd883eced0ffb25a6b4d2fd3577c47e272
07:49:12 PHPUnit 4.6.6 by Sebastian Bergmann and contributors.
07:49:12 
07:49:12 Configuration read from /var/jenkins/workspace/server-master-linux-externals-ci/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/tests/phpunit-autotest-external.xml
07:49:12 
07:49:12 Deprecated configuration setting "strict" used
07:49:12 
07:49:13 E................................................................ 65 / 78 ( 83%)
07:51:11 .............

**Comment by Xenopathic** [comment]
Which netcat is installed on Jenkins, the BSD one or the GNU one?

**Comment by DeepDiver1975** [comment]
To be more precise this call is returning nothing

```sh
nc -c -w 1 ${host} ${port}

**Comment by DeepDiver1975** [comment]
nice -c is to execute a shell command? wtf

```sh
$ nc -h
[v1.10-41]
connect to somewhere:	nc [-options] hostname port[s] [ports] ... 
listen for inbound:	nc -l -p port [-options] [hostname] [port]
options:
	-c shell commands	as `-e'; use /bin/sh to exec [dangerous!!]
	-e filename		program to exec after connect [dangerous!!]

**Comment by Xenopathic** [comment]
@DeepDiver1975 WTF is that variant of netcat?! There's a *third*?!?!?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 WTF is that variant of netcat?! There's a third?!?!?

this is what is shipped with debian ...

**Comment by Xenopathic** [comment]
You know what, screw using netcat, the unreliable PoS it is, I'm going to prepare a PR that uses a really hacky PHP script to wait 60 seconds and try connecting repeatedly...

**Comment by DeepDiver1975** [comment]
> You know what, screw using netcat, the unreliable PoS it is, I'm going to prepare a PR that uses a really hacky PHP script to wait 60 seconds and try connecting repeatedly...

until that arrives - let's merge this to get CI back in shape

**Pull request closed without merging**
