### PR TITLE
Fix empty PATH_INFO

### LINKED ISSUE #29: Reloads every 5 seconds
Why does it reload the page every 5 seconds when I'm typing in the code? It's quite annoying.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://github.com/ChristophWurst/twofactor_totp/issues/29

@elie195 this should also fix your issue as reported in https://github.com/elie195/duo_provider#notes

### CODE REVIEW

**Comment by PVince81** [comment]
Couldn't reproduce the original issue, but fix looks fine :+1:

**Comment by DeepDiver1975** [comment]
> Couldn't reproduce the original issue

you need to
- enable any twofactor app - e.g. the one by @ChristophWurst and enable it for the user
- enable notifications
- run owncloud in apache
- setup index.php-less urls

then you can observe the reload on the two factor selection page already

**Comment by PVince81** [comment]
> setup index.php-less urls

ah, was missing that. Will try again

**Comment by PVince81** [comment]
Was able to reproduce the issue and can confirm that this fixes it.

**Comment by PVince81** [comment]
Unpublished test results that passed => merge

**Comment by PVince81** [comment]
@DeepDiver1975 please submit the backport PR

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 please submit the backport PR

https://github.com/owncloud/core/pull/25904

**Pull request merged**
