### PR TITLE
use a normal rename when moving from the same storage in the encryption wrapper

### PR DESCRIPTION
**Pull request by icewind1991**
Saves having to re-encrypt the data

Speeds up dav upload

cc @schiesbn @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by schiesbn** [comment]
Can you provide some steps to test this? I would like to double-check that the keys are moved correctly and that the file cache entries are correct after the rename.

**Comment by icewind1991** [comment]
Webdav upload uses `moveFromStorage` to rename the part file to the final name

**Comment by PVince81** [comment]
Rebase needed

**Comment by icewind1991** [comment]
rebased

**Comment by PVince81** [comment]
@schiesbn any update ? Would like to know what you think

**Comment by schiesbn** [comment]
I think this should work :+1:

**Comment by MorrisJobke** [comment]
I rebased this.

@PVince81 Can you please review this? Thanks

**Comment by PVince81** [comment]
Seems to work fine :+1: 
Tested upload and move between shared and non-shared storage with and without encryption.

**Pull request merged**
