### PR TITLE
[stable8.2] Fix paths returned by \OC\Files\Storage\Shared hooks

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/23620

Resend of https://github.com/owncloud/core/pull/23648 from @oparoz for stable8.2

### CODE REVIEW

**Comment by oparoz** [comment]
:+1:

**Comment by PVince81** [comment]
@DeepDiver1975 @VicDeo second review ?

**Comment by PVince81** [comment]
Rebased

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
