### PR TITLE
Append search results to custom container

### LINKED ISSUE #13968: Append search results at appropriate location
### Steps to reproduce
1. Create an app, insert a div with the id 'searchresults'.
2. Perform a search.

### Expected behaviour
owncloud should use the already existing div#searchresults to show the search results

### Actual behaviour
owncloud creates a second div#searchresults appended to div#app-content and shows the search results there.

This behaviour makes it hard to present the search results for the app well as it may break the layout. For the files app the current behaviour works good. But for calendar (at commit https://github.com/owncloud/calendar/commit/de376292f9e6cca44ca2afa9c1ccbf8d871a2132) or tasks (at commit https://github.com/owncloud/tasks/commit/17ea797e3bbf2e47923c116649a95b743faf5c41) the results are just appended to the content and you have to scroll to find them. With the proposed change the app developer can decide where to place the search results best.

### PR DESCRIPTION
**Pull request by raimund-schluessler**
fixes #13968

### CODE REVIEW

**Comment by PVince81** [comment]
@butonic @MorrisJobke @georgehrke

**Comment by raimund-schluessler** [comment]
Could we please have a review for this? As of https://github.com/owncloud/tasks/commit/0f78b8727d18cc300420b9aef61aa4e7afafd919 the tasks app requires this to show the search results correctly.

@MorrisJobke @butonic

**Comment by LukasReschke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by raimund-schluessler** [comment]
@karlitschek @MorrisJobke Would it be possible to backport this to stable8 so the next release of the Tasks app can use it with oC8.0.1?

**Comment by karlitschek** [comment]
Would be fine for me. @MorrisJobke What do you think?

**Comment by MorrisJobke** [comment]
@karlitschek I think this is a good idea. I will prepare the backport PR.

**Pull request merged**
