### PR TITLE
[stable8.1] Missing memcache should not cause occ hard-fail

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Backport of #17663 

cc @MorrisJobke @karlitschek @MightyCreak

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
seriously: no :-1: 

I don't see any critial reason on backporting this.

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/issues/17329#issuecomment-122244948

**Comment by karlitschek** [comment]
Hmmm. @DeepDiver1975 Do you think there is a high risk to break anything?

**Comment by DeepDiver1975** [comment]
It touches the cache factory which initializes also the memcache which is used for transactional file locking. We did add a hart exception in case the cache could not be initialized properly.

For me this touches a critical component and requires in depth review and test - nothing to be done in a quick backport rush to get 8.1.1 out of the door.

Furthermore I kindly ask everybody to rethink what is supposed to be backported and if the backport is really necessary.

This fixes an issue - yes - but this issue can easily be worked around if it happens at all.

**Comment by karlitschek** [comment]
O.K. I agree with @DeepDiver1975  :-1:

**Comment by Xenopathic** [comment]
Right, no CLI memcache for 8.1.1. I'll leave the PR in case we want it for 8.1.2

**Comment by MorrisJobke** [comment]
THen I would simply close this. Okay @Xenopathic ?

**Comment by Xenopathic** [comment]
@MorrisJobke Do we not want to keep the PR active for 8.1.2?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Do we not want to keep the PR active for 8.1.2?

I don't think so:

> I don't see any critial reason on backporting this.

**Pull request closed without merging**
