### PR TITLE
Fix of  Bug #23066

### PR DESCRIPTION
**Pull request by TDannhauer**
This is a fix for Bug #23066 as discussed.

### CODE REVIEW

**Comment by TDannhauer** [comment]
My contribution is MIT licensed

**Comment by TDannhauer** [comment]
My contribution is MIT licensed

**Comment by MorrisJobke** [comment]
cc @rullzer @LukasReschke @PVince81

**Comment by MorrisJobke** [comment]
Successful tests at https://github.com/owncloud/core/issues/23066#issuecomment-219420146 and https://github.com/owncloud/core/issues/23066#issuecomment-219228365 by @jgroszko and @milprog

**Comment by DeepDiver1975** [comment]
jenkins pr please - THX

**Comment by TDannhauer** [comment]
@DeepDiver1975  pardon, do I need to do any further step? I'm not used to Github /owncloud development procedures. The above mentioned automatic checks are still not marked as finished, however @MorrisJobke announced successful tests. What do I have to next to continue?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 pardon, do I need to do any further step? I'm not used to Github /owncloud development procedures. The above mentioned automatic checks are still not marked as finished, however @MorrisJobke announced successful tests. What do I have to next to continue?

nothing you have to take care of ... THX

**Comment by MorrisJobke** [comment]
> however @MorrisJobke announced successful tests.

I meant manual tests ;)



> jenkins pr please - THX

I will create one.

**Comment by MorrisJobke** [comment]
> I will create one.

@DeepDiver1975 was faster: https://github.com/owncloud/core/pull/24659

**Comment by rullzer** [comment]
You got to love those comparissions... :+1:

**Comment by TDannhauer** [comment]
I send the contribution license agreement to the mentioned oc member yesterday but haven't got feedback yet.

**Comment by MTRichards** [comment]
We received it! Thank you. You should get more info shortly...

**Comment by TDannhauer** [comment]
Since I'm now marked as developer, how can I restart the failed checks?

**Comment by PVince81** [comment]
failed tests:

```
05:30:21 1) Test_Share::testCheckPasswordProtectedShare with data set #5 (true, array('1234567890', '3', 100))
05:30:21 Failed asserting that false matches expected true.
05:30:21 
05:30:21 /ssd/jenkins/workspace/core-ci-linux@3/database/sqlite/label/SLAVE/tests/lib/share/share.php:993
05:30:21 
05:30:21 2) Test_Share::testCheckPasswordProtectedShare with data set #6 (true, array('1234567890', 3, 100))
05:30:21 Failed asserting that false matches expected true.
05:30:21 
05:30:21 /ssd/jenkins/workspace/core-ci-linux@3/database/sqlite/label/SLAVE/tests/lib/share/share.php:993
```

@TDannhauer the best would be if you could close this PR, then create git clone the ownCloud repo, create a git branch, put your commits, push your branch and submit a new PR from that branch. (basically the branch must be in the core repo, not your fork)

I saw in the original ticket that you mentioned (https://github.com/owncloud/core/issues/23066#issuecomment-219308379) not being a Github hero, so let me know if that's too much or need help. :smile: 

For running unit tests, see https://doc.owncloud.org/server/9.0/developer_manual/core/unit-testing.html#running-unit-tests-for-the-owncloud-core-project

**Comment by TDannhauer** [comment]
@PVince Hehe I see you got my git level (we're stuck to SVN without any branching or cloning in my job...).
- Installing Github Desktop: check
- Cloning Owncloud/core: check
- Creating Branch "Fix-for-#23066" : It seems it creates the branch directly in owncloud master and not in my clone?

Another "strange thing is that the desktop knows about my previous changes I applied on helper.php and Share.php. since they are not commited to the master, and i cloned the master - why does the github desktop is aware of it?

**Comment by PVince81** [comment]
I'm not really familiar with Github desktop, so not sure... Did you use the same local folder where you already had your code changes for the check out ?

From what I see on Github's branch list is that your branch has not been pushed yet, so it's only available for you locally.

In any case, when pushing you need to make sure to **never** push "master", only push your own branch.

**Comment by PVince81** [comment]
To clarify, "master" is the name of the main branch. In SVN I believe it's "trunk" ?

**Pull request closed without merging**
