### PR TITLE
Backport asset generation fix 

### LINKED ISSUE #14134: External Storage config options unavaiable when using asset-pipeline.enabled
Using stable7, after selecting an external storage type, the config options are not displayed!
When i set 'asset-pipeline.enabled' => false, it works as intended.
Console shows:

```
Uncaught TypeError: undefined is not a function  ad7293bd07935ab658745d598cd67fbb.js:24032 
And line 24032 starts with:
(function (factory) {
    'use strict';
    if (typeof define === 'function' && define.amd) {
        // Register as an anonymous AMD module:
        define([
            'jquery',
            'jquery.ui.widget'
        ], factory);
    } else {
        // Browser globals:
        factory(window.jQuery);
    }
```

@DeepDiver1975

### PR DESCRIPTION
**Pull request by MorrisJobke**
fixes #14134

Backport of #13116 to stable7

cc @xenopathic @DeepDiver1975 @karlitschek

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @fossxplorer

**Comment by DeepDiver1975** [comment]
This is not enough afaik - strengthify needs to be upgraded as well and there was a syntax error in files_external/js/* as well

**Comment by DeepDiver1975** [comment]
7.0.5 is off the hook -> 7.0.6

**Comment by Xenopathic** [comment]
:+1:

**Comment by Xenopathic** [comment]
@DeepDiver1975 Could you review this please? Thanks

**Comment by MorrisJobke** [comment]
stable7 simply doesn't support asset pipeline .... as this doesn't fix everything and even more stuff needs to be backported, that will introduce problems with a high propability: I will close this. It's fixed in stable8+

**Pull request closed without merging**
