### PR TITLE
Fix Undefined variable: csp in TwoFactorChallengeControllerTest

### PR DESCRIPTION
**Pull request by DeepDiver1975**
```

Duration

Age
 Test\Core\Controller\TwoFactorChallengeControllerTest.testShowChallenge
 Stack Trace

Test\Core\Controller\TwoFactorChallengeControllerTest::testShowChallenge
Undefined variable: csp

/var/lib/jenkins/workspace/owncloud-core/core/master/core/Controller/TwoFactorChallengeController.php:127
/var/lib/jenkins/workspace/owncloud-core/core/master/tests/Core/Controller/TwoFactorChallengeControllerTest.php:129
```

### CODE REVIEW

**Comment by butonic** [comment]
Jesus why do we have IProvider and IProvider2? Who named them ... oh well ...

**Comment by DeepDiver1975** [comment]
> Jesus why do we have IProvider and IProvider2

IProvider was introduced with 9.1 - in order to extend the interface and to not break any existing implementation out there we introduce another interface for 9.2 which extends IProvider

**Comment by butonic** [comment]
👍

**Comment by DeepDiver1975** [comment]
backporting ....

**Comment by elie195** [comment]
@DeepDiver1975 thanks for the fix!

**Pull request merged**
