### PR TITLE
AmazonS3 automatic tests

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
This uses the same Docker image as in #14077, but this time with the S3 API. In getting it working however I discovered that the 'Enable path style' option was broken, being completely disconnected from any code. Trawling through some API references, I fixed that, so now that option actually works (and is used by the tests since we don't control the DNS infrastructure).

Oh, and all the tests pass too! :grinning: 

Given that this includes a bug fix, and the only other part is tests, I'm marking this as for 8.2.

cc @icewind1991 @MorrisJobke @butonic @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Ran the tests locally, they pass.
Also did some quick test in the web UI with a S3 mount, still works.
However I can't test with my Amazon S3 bucket with path style (honestly I have no idea what this is) as it would give me a red square.
Without path style it still works.

**Comment by PVince81** [comment]
Hmmm no, I spoke to fast.
Mount point of ANY external storage does not appear, raised here: https://github.com/owncloud/core/issues/19084

**Comment by Xenopathic** [comment]
@PVince81 Path style involves trying to connect via the URL `http://server/bucket`, while without path style (aka virtual host style, the default, but only works with cooperating DNS) it uses `http://bucket.server/`.

**Comment by icewind1991** [comment]
Is path style properly documented?

Code looks good :+1:

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
let me integrate this into jenkins these days ...

**Comment by butonic** [comment]
Path style is mainly needed when connecting to ceph

**Comment by Xenopathic** [comment]
@butonic Actually, path style works just fine when connecting to Ceph, but you need to configure DNS properly (which is impossible for an automated Docker container)

**Pull request merged**
