### PR TITLE
Fixed Issue 23316 - Invisible buttons should be visible

### PR DESCRIPTION
**Pull request by prisas**
Changed the style sheet for the Advanced settings and Delete icons as asked in issue #23316.

### CODE REVIEW

**Comment by PVince81** [comment]
@jancborchardt do you agree ? I remember that you asked for these to only be visible on hover back when we introduced it.

@owncloud/designers

**Comment by PVince81** [comment]
@paurisa thanks for your PR :smile:

**Comment by paurisa** [comment]
This contribution is MIT licensed.

**Comment by MorrisJobke** [comment]
@paurisa Could I ask you to remove the star icon fixes from this PR? They are unrelated.

**Comment by paurisa** [comment]
@MorrisJobke Sure, is there a safe way of doing it?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Sure, is there a safe way of doing it?

```
git remote add upstream git@github.com:owncloud/core
git fetch upstream
git checkout -b upstream-master upstream/master
git checkout -b new-fixed-23316
git cherry-pick cf2a8f8
```

This will create a new branch and it's the safest way. Then close this PR and open a new one. The other alternative would be to overwrite the existing branch, but it is not that safe ;)

**Comment by jancborchardt** [comment]
I would say this fix is fine. Since it’s external storage config it’s ok to show them all the time.

**Pull request closed without merging**
