### PR TITLE
Don't show PCNTL warning if --no-warnings is passed

### LINKED ISSUE #252: Dependency on PCNTL extension
I got this when opening the updater. It seems that it requires an extension to work properly. This should be checked before running the updater.

```
UnexpectedValueException: Could not parse a response for config:list --private. Please check if the current shell user can run occ command. 
Raw output: The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php HERE IS THE ACTAUL OUTPUT OF THE COMMAND
```

cc @karlitschek @cmonteroluque @DeepDiver1975 and for the other dependency checks @LukasReschke 

We maybe also want to check this on all supported platforms.

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes owncloud/updater#252

cc @LukasReschke @VicDeo @DeepDiver1975 

@karlitschek @cmonteroluque I put this in the 9.0 milestone because it fixes a updater issue. And I would rate this low risk.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> @karlitschek @cmonteroluque I put this in the 9.0 milestone because it fixes a updater issue. And I would rate this low risk.

Feel free to move this to 9.1 and 9.0.1.

**Comment by rullzer** [comment]
:+1:

**Comment by karlitschek** [comment]
I would recommend to do this for 9.0.0 Should be low risk and improves the experience! :+1:

**Comment by VicDeo** [comment]
:+1:

**Pull request merged**
