### PR TITLE
Do not use the asset pipeline when doing updates

### LINKED ISSUE #184: Broken in C 8.2?
This screenshot will tell more:
untitled

### PR DESCRIPTION
**Pull request by nickvergessen**
Not sure if it fixes https://github.com/owncloud/updater/issues/184

But at least it fixes the white page I had when updating from 8.0 to 8.1 to 8.2 last week

@DeepDiver1975 @rullzer @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1;

**Comment by MorrisJobke** [comment]
@nickvergessen Do we want to backport this?

**Comment by DeepDiver1975** [comment]
No backportable from m pov

**Comment by mmattel** [comment]
Great :+1: 

One question remains: what was causing the issue when using the asset pipline and could that effect other code too?

**Comment by MorrisJobke** [comment]
> One question remains: what was causing the issue when using the asset pipline and could that effect other code too?

I have a similar issue in the music app: https://github.com/owncloud/music/issues/434

**Comment by nickvergessen** [comment]
> One question remains: what was causing the issue when using the asset pipline and could that effect other code too?

the problem in the case I fixed is that the used file is not what the files existing on the disc match.

**Comment by MorrisJobke** [comment]
Okay. so in my case (music app) this is something different ... I need to investigate

**Comment by mmattel** [comment]
@nickvergessen 
do you mind to explain what you mean with
> that the used file is not what the files existing on the disc match

**Comment by nickvergessen** [comment]
@mmattel 
Well the assets (JS + CSS) are gather together and stored in a file with the current version of the apps and core.
So when you upload the new version, the files are different. But until you run the database update, the app and core version are still old and so the old file is still used. But since that missed some CSS and JS, which is used in the template file, it caused a blank page for me.

**Comment by mmattel** [comment]
ah, ok.
- Does this mean, that the DB-Update deletes the asset files so they are fresh generated and therefore actual?
- And isn´t it true that if the asset files are not present, they are generated - from the actual code present?
- And if both is true, would´t it be an idea to have an mechanism (whatever we think of) outside DB-Update to recreate the asset files? (eg admin-forced via the admin UI (could be even timed as a preemtive task based on cpu load), at the enabled apps list as checkbox,  ect)

**Comment by mmattel** [comment]
I just tested when deleting all files in the asset directory, the files were recreated, but at the admin page, the issue was still there (without your PR)

**Comment by nickvergessen** [comment]
> Does this mean, that the DB-Update deletes the asset files so they are fresh generated and therefore actual?

No, the random name becomes different and therefor a new file is created from the new source

> And isn´t it true that if the asset files are not present, they are generated - from the actual code present?

Thats correct

> admin-forced via the admin UI

No, the correct way is to delete the files from the folder. Another option would be to give them a TTL and expire them with a cron job. But then strange behaviour changes could happen although no one changed something intentionally.

**Comment by mmattel** [comment]
I understand that you disabled assets for the updater.
But as described above, even I have deleted all the assets, the updater still had the problem. This is confusing me, because the asset has been fresh generated from the actual code and should therefore be correct, but somehow it still causes problems. Your method disabling the asset for the updater is a work-around. I think that this is something we should have a deeper look in because this can cause very strange side effects...

**Pull request merged**
