### PR TITLE
[stable10] UI-tests set marionette to null

### PR DESCRIPTION
**Pull request by individual-it**
backport of #30110 to stable10 plus bumping mink extension, see original PR #30033

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by individual-it** [comment]
It does not work in stable10, I guess the mink extension was not updated here.

**Comment by phil-davis** [comment]
I think this backport is needed first:
https://github.com/owncloud/core/pull/30102/files
after 10.0.5 is sorted

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@individual-it All CI passing, so this looks good to merge. The mink extension version change does not impact production.

**Pull request merged**
