### PR TITLE
Fix "It is not possible to seek the video"

### PR DESCRIPTION
**Pull request by ghost**
Fix for https://github.com/owncloud/apps/issues/1896

### CODE REVIEW

**Comment by PVince81** [comment]
The better solution is to make the video player point at the Webdav endpoint, which supports http ranges

**Comment by binron** [comment]
The idea was to support range requests for shared files.
Not just for video players, also for downloading big files (resume download)

E.g.: https://example.com/owncloud/index.php/s/zfT7yQhtF9WSzI3/download

**Comment by DeepDiver1975** [comment]
files.php will die in 9.0 and 8.2 is closed for new features.

Thanks a lot for your contributions - but I have to reject this - sorry

**Comment by binron** [comment]
What does this mean for owncloud/apps#1896, owncloud/apps#1865 and owncloud/apps#1935

**Comment by PVince81** [comment]
Please note that in the future the Webdav endpoints will be used (#12353). There is also a Webdav endpoint already for public links. Webdav endpoints already support range requests.

**Pull request closed without merging**
