### PR TITLE
[stable7] Add min-height to login page for IE8 and IE9

### LINKED ISSUE #15413: Style and some images are lost in Internet Explorer 8
### Observed behaviour:
 
1.
screen shot 2015-04-06 at 08 58 51

2.
screen shot 2015-04-06 at 08 59 46

3.
screen shot 2015-04-06 at 09 00 32

### Expected behaviour:

1.
screen shot 2015-04-06 at 08 58 39

2.
screen shot 2015-04-06 at 08 59 38

3.
screen shot 2015-04-06 at 09 00 20

Server configuration

Operating system:
Ubuntu 14.04

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.1","versionstring":"8.1 pre alpha","edition":"Enterprise"}

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
Files drop

The content of config/config.php:

Are you using external storage, if yes which one: local/smb/sftp/...
No

Are you using encryption:
Yes

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
No

### Client configuration

Browser:
Internet Explorer 8.0.7601

Operating System:
Windows Server 2008 R2 enterprise

### PR DESCRIPTION
**Pull request by MorrisJobke**
same as #16703 for stable7 (without the revert, because the PR wasn't merged for stable7)
Fixes #15413 for stable7

@owncloud/designers @SergioBertolinSG Please review

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@PVince81 review?

**Comment by PVince81** [comment]
Works :+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by SergioBertolinSG** [comment]
:+1: white cloud is missing but i guess we can live with that.

**Comment by MorrisJobke** [comment]
> :+1: white cloud is missing but i guess we can live with that.

IE 8 restriction, that background images are not supported.

**Pull request merged**
