### PR TITLE
[tags] remove unneeded variables

### PR DESCRIPTION
**Pull request by MorrisJobke**
@PVince81 I just noticed this while reading the code. Feel free to also close this if this was by intention and should stay.

cc @nickvergessen

### CODE REVIEW

**Comment by PVince81** [comment]
Wow, nice find! I didn't even know this file existed  !

It seems it's there for tags management from the contacts app. Which means we'll be able to reuse it for the future tag management features.

:+1:

**Comment by MorrisJobke** [comment]
> Wow, nice find! I didn't even know this file existed !
> 
> It seems it's there for tags management from the contacts app. Which means we'll be able to reuse it for the future tag management features.

Okay...I thought you wrote it. :see_no_evil:

**Comment by LukasReschke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> It seems it's there for tags management from the contacts app. Which means we'll be able to reuse it for the future tag management features.

if the code ft our needs ... otherwise we simply move it to the contacts app and bye bye

**Pull request merged**
