### PR TITLE
Files drag and drop improvements

### PR DESCRIPTION
**Pull request by PVince81**
## Description

Make it possible copy instead of move in the web UI by holding ctrl.
When holding onto a folder or breadcrumb for 1 second, automatically switch to that one.
## Related Issue

https://github.com/owncloud/core/issues/6636
https://github.com/owncloud/core/issues/8570
https://github.com/owncloud/core/issues/10656

## Motivation and Context

Improve UX by making it more easy to move/copy folders in the UI
## How Has This Been Tested?

With the folder structure "a/b/c"
- [ ] move several entries from "a" into "b" while viewing "a"
- [ ] move several entries from "c" into "a" using drop on breadcrumb
- [ ] move several entries from "a" into "c", hold on "b" to enter it, drop on "c"
- [ ] move several entries from "a" into "c", hold on "b" then "c" to enter it, drop on empty table space
- [ ] move several entries from "c" into "a", hold on "a" breadcrumb, drop on empty table space
- [ ] move entry into the same folder by dropping onto table space: no result
- [ ] drag hold on a file (not folder) does nothing
- [ ] same as all above but with copy (hold Ctrl when dropping)
- [ ] same as above but on the public page
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
## Todos:
- [x] indicator when holding Ctrl
- [ ] improve that ugly drag shadow ?
- [x] copy to same folder, append "(2)" suffix ? (complicated due to iterative name-finding)
- [ ] Add unit tests

@DeepDiver1975 @butonic @VicDeo @SergioBertolinSG

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Tested this using firefox in ubuntu and holding ctrl doesn't copy. I guess it is better to wait for  "indicator when holding Ctrl" before testing this.

**Comment by SergioBertolinSG** [comment]
Tested using mac, ctrl+drag not working either.

**Comment by SergioBertolinSG** [comment]
Okay, it actually works, but you need to drop in a folder. It is not able to copy in the same directory. ( adding a " (2)" )

**Comment by PVince81** [comment]
> Okay, it actually works, but you need to drop in a folder. It is not able to copy in the same directory. ( adding a " (2)" )

Ah yes, that part is missing...

**Comment by PVince81** [comment]
added indicator when holding ctrl

**Comment by PVince81** [comment]
@SergioBertolinSG I've added logic to autorename (append "(2)") if you copy a file in the same folder as itself. Note that it doesn't work if you're dragging a file into another folder, switching the view, and there's a file with the same name there (which is not technically the same file). In the latter case, we need to look into providing the conflict dialog at some point: https://github.com/owncloud/core/issues/24885

**Comment by PVince81** [comment]
For now I think this feature is already usable enough to be merged.
Please have a look, might need full retesting :smile:

**Comment by SergioBertolinSG** [comment]
Being tested here https://github.com/owncloud/QA/issues/311

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2016-10-07 13-29-19

**Comment by SergioBertolinSG** [comment]
> Note that it doesn't work if you're dragging a file into another folder, switching the view

This is related and very likely not expected to work yet but perhaps knowing the current behaviour is useful:

having file1.txt in /
and having file1.txt also in /BBB/CCC
when copying file1.txt from /BBB/CCC to / using breadcrumbs, the spinner gets spinning forever, and warning message is confusing, saying that file already exist and saying that is was copied correctly.

**Comment by PVince81** [comment]
> warning message is confusing, saying that file already exist and saying that is was copied correctly.

ok, then that's a bug
- [ ] BUG

**Comment by SergioBertolinSG** [comment]
There is a bug in safari:

Using safari
When having several files in /BBB/CCC which doesn't exist in /
and copying all of them from /BBB/CCC to / using breadcrumbs, the spinner gets spinning forever in all of them and files are copied twice, both in their folder (/BBB/CCC) and in destination folder (/)

**Comment by SergioBertolinSG** [comment]
When notifying user that something has been moved, it always keeps saying files, but it could be only folders or a mix of both. What about saying elements instead of files?

**Comment by PVince81** [comment]
@SergioBertolinSG elements is maybe too technical. I'll see if I can find a better wording

- [ ] change wording of success/error messages

**Comment by PVince81** [comment]
Regarding the failing test: I realize now that we can't keep the size recalculation logic as it was before. The reason is because here we can now move files from an invisible folder into the current one. When running the move operation we only have the file names and not the old size to add it.

Maybe this logic needs to be changed to simply re-fetch the target folder's info through PROPFIND at the end of the transfer.

**Comment by SergioBertolinSG** [comment]
Using edge, 
Having an structure /AAA/BBB
when entering in /AAA dragging some files if you try to enter/drop files in BBB, the row doesn't highlilght and you cannot enter it.

In this picture the row should be yellow:
screen shot 2016-10-07 at 15 04 33

**Comment by PVince81** [comment]
Edge and Safari always the party poopers it seems

**Comment by PVince81** [comment]
ok, so once again I mixed up IE11 with Edge... Drag and drop works fine with IE11

**Comment by PVince81** [comment]
Argh, this dropping stuff is complicated... If you drop an element onto the breadcrumb, not only the breadcrumb receives a drop event but also the container (the full table), this is why it not only copies to the breadcrumb target but also to the current folder.

Will need more advanced magic to prevent this.

**Comment by PVince81** [comment]
Turns out there is a "greedy" mode for jquery.ui droppable which makes sure that only the overlapped element and not its parent receives the drop event. This should fix all the issues you saw @SergioBertolinSG

**Comment by PVince81** [comment]
- [ ] make sure to integrate https://github.com/owncloud/core/pull/26555

**Comment by PVince81** [comment]
I plan to finish this for OC 10.0.

**Comment by PVince81** [comment]
Rebased onto master and integrated with https://github.com/owncloud/core/pull/26555.

Still seems to work but I didn't try all the steps above.

While the whole manipulation isn't 100% ideal as there are some non-covered cases, it is still a big jump forward so I think the last thing needed is adding JS unit tests now. (and fixing major bugs if any appears)

**Comment by PVince81** [comment]
- [ ] BUG: folder sizes not properly updated after moving in/out

**Comment by PVince81** [comment]
- [ ] JS unit tests for all filelist.js changes

**Comment by PVince81** [comment]
- [ ] BUG: drag and hold on folder, then subfolder doesn't react

**Comment by PVince81** [comment]
Abandoning this due to no time and bad legacy code that doesn't let itself be tamed.

Should be reimplemented in newer files apps

**Pull request closed without merging**
