### PR TITLE
[stable9] Add webdav share-types property to fix favorites/tags share status icon

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/22789 to stable9
- [x] Backport request pending: https://github.com/owncloud/core/pull/22789#issuecomment-198299494

Please review @MorrisJobke @rullzer @nickvergessen @blizzz

### CODE REVIEW

**Comment by PVince81** [comment]
Had a quick test and this still works :smile:

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
@DeepDiver1975 hmm, you merged the backport but wanted some changes in the original PR: https://github.com/owncloud/core/pull/22789

**Pull request merged**
