### PR TITLE
Enabling streaming of video content in AJAX and allow seeking for public links

### PR DESCRIPTION
**Pull request by ghost**
the added code allow streaming of video content with seeking capabilities for AJAX links.
I have test the code with a current video player through public link to enable ajax testing.
how ever the private video player links should be changed from webdav links to ajax link to enable the seeking in it.
I hope you find this code useful. Kindly note i can send the modified videoplayer code if required.

### CODE REVIEW

**Comment by hassanhawilo** [comment]
he added code allow streaming of video content with seeking capabilities for AJAX links.
I have test the code with a current video player through public link to enable ajax testing.
how ever the private video player links should be changed from webdav links to ajax link to enable the seeking in it.
I hope you find this code useful. Kindly note i can send the modified videoplayer code if required.

**Comment by PatelParas** [comment]
+1

**Comment by DeepDiver1975** [comment]
@PVince81 do we want to move over to webdav for download? In this case this change is obsolete

**Comment by PVince81** [comment]
Yes. Please use `FileList.getDownloadUrl(fileName, dir)` to get the Webdav URL in 9.0, also works in the public page. The Webdav URL is streamable and supports range requests.

**Comment by PVince81** [comment]
Note, for the public page's `getDownloadUrl()`, this PR needs to be merged first https://github.com/owncloud/core/pull/20688

**Pull request closed without merging**
