### PR TITLE
[stable10] Changes updated by rewriting config.php should sent events

### PR DESCRIPTION
**Pull request by sharidas**
When changes updated by rewriting config.php, for example
using method writeData() should also be logged. This change
would help to log these data. An example is updating
email settings from UI.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

When config rewrite happens with `setValues()`, the symfony events are not triggered for config changes. The config.php rewrite happens. Events should be triggered for the changes that happened.

## Motivation and Context

When config rewrite happens with `setValues()`, the symfony events are not triggered for config changes. The config.php rewrite happens. Events should be triggered for the changes that happened.

## How Has This Been Tested?

- [x] Try to update the config say email from UI
- [x] Verify the events are triggered by using debugger.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Works. Fixes https://github.com/owncloud/admin_audit/issues/67 . @PVince81 Please review the code and evaluate the risk of adding it in the next RC of 10.0.8.

**Comment by SergioBertolinSG** [comment]
@sharidas there is a failure in the acceptance tests:

```
Notice: Undefined index: apps_paths in /drone/src/lib/private/Config.php line 196
```

**Review by PVince81 — APPROVED** [review]
:+1: I think the change is fine.

What will need retesting is parts that save config.php like the email server setup

**Comment by PVince81** [comment]
please port to master

**Comment by sharidas** [comment]
forward port to master banch PR: https://github.com/owncloud/core/pull/31106

**Pull request merged**
