### PR TITLE
Disable video preview if previews are disabled

### LINKED ISSUE #9878: [6.0.4] Plays video streaming without video viewer or additional apps
### Expected behavior 
Users has to be forced to download the video over the share link

### Actual behavior
Users steams video direct from ownCloud.

### Steps to reproduce:
1.Install only the ownCloud core, without the video features.
2. upload a video
3. share video with link
4. use the link in the browser and the video start to be played directly.

### version
ownCloud 6.0.4 only core

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes #9878

Please review @PVince81 @LukasReschke @cdamken

### CODE REVIEW

**Comment by PVince81** [comment]
Makes sense :+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek backport to stable8 and 7?

**Comment by karlitschek** [comment]
yes. back port please

**Comment by MorrisJobke** [comment]
stable8 #16861

**Comment by MorrisJobke** [comment]
stable7: #16863

**Pull request merged**
