### PR TITLE
add https:// placeholder for From Link feature. closes #13255

### LINKED ISSUE #13255: "Paste URL here" placeholder
What do you think adding a placeholder into "From link" input field? Something like:

image

It is very minor, but nice to see at least a text instead of a blank field IMO.

@jancborchardt

### PR DESCRIPTION
**Pull request by vgezer**
Like discussed here: https://github.com/owncloud/core/issues/13255

@jancborchardt @enoch85. Is it too late for OC8.0?

### CODE REVIEW

**Comment by jancborchardt** [comment]
You forgot the `…` after the `https://`, as mentioned in #13255

**Comment by wakeup** [comment]
@jancborchardt ah yes. here it is.

**Comment by DeepDiver1975** [comment]
@wakeup there is a special ellipsis character to be used instead of 3 dots. THX

**Comment by wakeup** [comment]
@DeepDiver1975 and also no force push, right?

**Comment by MorrisJobke** [comment]
@wakeup Give the force push a try ;)

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Works :+1: Thanks

**Comment by MorrisJobke** [comment]
cc @owncloud/designers easy to review :)

**Comment by oparoz** [comment]
Tested on Chrome & Firefox
:+1:

**Pull request merged**
