### PR TITLE
fix LDAP update routine to OC 7

### PR DESCRIPTION
**Pull request by blizzz**
Supposed to fix https://github.com/owncloud/core/issues/12035 and #12801 

Please review and test @butonic @MorrisJobke @PVince81 @jcfischer @fleish

(sidenote: for OC 8 the whole update.php can be dropped imho, as there where no relevant changed. will test and do a PR later).

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jcfischer** [comment]
-99

does not solve the problem, exactly same symptom as before in #12801

**Comment by PVince81** [comment]
Thing is, if the users were already migrated to new GUIDs then this PR will not repair those. It would only work if the fix is applied before the upgrade to OC 7 (which I believe you did ?)

**Comment by MorrisJobke** [comment]
:cry: 

@jcfischer So you already update to the stable7 branch before?

**Comment by jcfischer** [comment]
@PVince81 @MorrisJobke - we did a test upgrade in october/november last year from 6.0.4 or 0.5 to oC 7 EE (possibly the first release) and it went smoothly. We have since upgraded that installation to 7.0.4.

We changed from LDAP uuid to LDAP uid (i.e. email addresses) shortly after our 6.0 deployment with just a few hundred users by manually fixing up the database. There haven't been any UUID users since then.

**Comment by MorrisJobke** [comment]
@butonic @blizzz It seems that this isn't the only cause for the problem.

**Comment by butonic** [comment]
@jcfischer how exactly did you configure oc to use the email adress as the userid in owncloud? in the ldap settings dialog? please describe.

**Comment by jcfischer** [comment]
@butonic on the LDAP experts page, use the `uid` attribute

**Comment by MorrisJobke** [comment]
@butonic Can you review this because this reduces the propability, that something is broken later. Thanks :)

**Comment by PVince81** [comment]
@blizzz can you describe the steps and test cases for this fix ?
I get there is at least two different user id formats ?

**Comment by blizzz** [comment]
1. Have 6.0.6/stable6 with LDAP
2. Configure one LDAP server. Leave Expert tab with defaults.
3. Do not go  to Users tab.
4. Upgrade to stable7/this branch
5. Check LDAP config by ./occ ldap:show-config

Before fix: ldap_uuid_user_attribute is empty
After with: ldap_uuid_user_attribute is auto 

In case it is neither empty nor auto it's even far less a problem ;)

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
