### PR TITLE
Explicitly add the current principal to the acl in case of group sharing

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of https://github.com/owncloud/core/pull/23318

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@LukasReschke @PVince81 @MorrisJobke @icewind1991 @schiesbn @blizzz please review - has to go into 9.0.1 - THX

**Comment by blizzz** [comment]
Some tests are really failing, e.g.

```
Tests\Connector\Sabre\CalDavBackendTest::testCalendarSharing with data set #0 (true, true, true, false, array(array('principal:principals/users/ca...-test1', false), array('principal:principals/groups/c...-group', true)))
Missing argument 3 for OCA\DAV\CalDAV\CalDavBackend::applyShareAcl(), called in /ssd/jenkins/workspace/server-master-linux-php7-ci@2/database/sqlite/label/SLAVE/apps/dav/lib/caldav/calendar.php on line 101 and defined

/ssd/jenkins/workspace/server-master-linux-php7-ci@2/database/sqlite/label/SLAVE/apps/dav/lib/caldav/caldavbackend.php:1382
/ssd/jenkins/workspace/server-master-linux-php7-ci@2/database/sqlite/label/SLAVE/apps/dav/lib/caldav/calendar.php:101
/ssd/jenkins/workspace/server-master-linux-php7-ci@2/database/sqlite/label/SLAVE/3rdparty/sabre/dav/lib/CalDAV/Calendar.php:111
/ssd/jenkins/workspace/server-master-linux-php7-ci@2/database/sqlite/label/SLAVE/apps/dav/tests/unit/caldav/caldavbackendtest.php:186
```

**Comment by DeepDiver1975** [comment]
@blizzz addressed - THX

**Comment by blizzz** [comment]
code fine, tested + works with LDAP group and user :+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
The original PR isn't needed anymore because it was fixed by another PR. Now this other PR has also a pending backport: https://github.com/owncloud/core/pull/23552 - this would then mean that this PR here is not needed anymore.

**Comment by DeepDiver1975** [comment]
let's revert this - THX

**Comment by MorrisJobke** [comment]
Revert is in https://github.com/owncloud/core/pull/23689

**Pull request merged**
