### PR TITLE
feat: add rector

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by sfadschm** [comment]
Will rector then also be used to perform the php 8.2 upgrade?

**Comment by DeepDiver1975** [comment]
Php 8.2 is already in here https://github.com/owncloud/core/pull/40981

This PR is an experiment..... Let's see....

**Comment by sfadschm** [comment]
Fingers crossed!

From my experience, rector is a valuable tool and might ease the php upgrade significantly.

But I see you are right, a lot of work towards 8.2 has already been done.

Btw: Thanks for all the work!

**Comment by DeepDiver1975** [comment]
conflicting meanwhile ...... :shrug:

**Pull request closed without merging**
