### PR TITLE
Fix placeholder in files upload

### LINKED ISSUE #13255: "Paste URL here" placeholder
What do you think adding a placeholder into "From link" input field? Something like:

image

It is very minor, but nice to see at least a text instead of a blank field IMO.

@jancborchardt

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Revert "add https:// placeholder for From Link feature. closes #13255"

'From link' feature was removed in #14652

cc @vgezer @LukasReschke @DeepDiver1975 @PVince81 @jancborchardt

### CODE REVIEW

**Comment by nickvergessen** [comment]
How to test this?

**Comment by Xenopathic** [comment]
Go to New -> Folder then remove the text to give an empty text box. before PR this says 'https://...', now it is empty.

**Comment by nickvergessen** [comment]
AH right, :+1:

**Comment by MorrisJobke** [comment]
Works :+1:

**Pull request merged**
