### PR TITLE
Fix "uri" when  owncloud is used with "overwritewebroot"

### PR DESCRIPTION
**Pull request by Morlinest**
Repair bug, where you cant use webdav behind proxy if not default url is used.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@Morlinest Thanks a lot for your pull request. Can you by any change add a unit test at https://github.com/owncloud/core/blob/master/tests/lib/appframework/http/RequestTest.php? That way we can ensure that this won't break anything and behaves as expected. 

To run them change into `tests` and execute `phpunit lib/appframework/http/RequestTest.php`, then add or modify one existing test with regard  to `testGetRequestUriWithoutOverwrite`.

**Comment by Morlinest** [comment]
I can only tell, i will try... Never did it but will try my best and finish it asap.

**Comment by Morlinest** [comment]
While i was finding how to test it, i have tested it in my mind and after that test on my server... this PR is not good. Problem is that if URI starts with "/" (uri from proxy is "/owncloud//remote.php/webdav/") than this fix helps, but without that double "//" after your "subdomain", it will fail (or with multiple "/", that acts always like "//"). I will have to change this code.

**Comment by Morlinest** [comment]
This contribution is MIT licensed.

**Comment by FinlStrm** [comment]
Hi guys,

I've tested this patch in my environment and can confirm that it does in fact work. I am now able to use my OC instance behind my Apache reverse-proxy. It also does not seem to break any functionality when accessing the OC instance directly.

It would be nice to have this in the next release. I'd prefer not to make manual changes like this when updating :)

Thanks a million!!!

My post: [https://forum.owncloud.org/viewtopic.php?f=38&t=35110](https://forum.owncloud.org/viewtopic.php?f=38&t=35110)

**Comment by PVince81** [comment]
@Morlinest to fix the slashes issues you might be able to normalize the strings for example using "ltrim($s, '/')" to remove all slashes on the left, then add as many as you need :smile: 

Can you adjust the PR to make it work for all the needed scenarios ?
Thank you!

**Pull request closed without merging**
