### PR TITLE
sabre/dav 3.0 and related

### PR DESCRIPTION
**Pull request by DeepDiver1975**
requires https://github.com/owncloud/3rdparty/pull/218

fixes #https://github.com/owncloud/core/issues/17039

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
The failing unit tests is related to a connectivity error

````
05:08:19 There was 1 error:
05:08:19 
05:08:19 1) Test\Files\Storage\DAV::testRoot
05:08:19 OCP\Files\StorageNotAvailableException: Sabre\HTTP\ClientException: Failed to connect to 172.17.40.24 port 80: Connection refused
05:08:19 
05:08:19 /var/jenkins/workspace/server-master-linux-externals-ci/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/lib/private/files/storage/dav.php:788
05:08:19 /var/jenkins/workspace/server-master-linux-externals-ci/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/lib/private/files/storage/dav.php:628
05:08:19 /var/jenkins/workspace/server-master-linux-externals-ci/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/lib/private/files/storage/dav.php:171
05:08:19 /var/jenkins/workspace/server-master-linux-externals-ci/database/sqlite/external/webdav-ownCloud/label/vm-slave-02/apps/files_external/tests/backends/webdav.php:42

**Comment by DeepDiver1975** [comment]
please review @rullzer @icewind1991 @schiesbn @blizzz @PVince81

**Comment by PVince81** [comment]
Code changes look good, let's smash this

**Comment by PVince81** [comment]
- [ ] TEST: smashbox
- [ ] TEST: pyocclient unit tests
- [ ] TEST: files web UI Webdav operations
- [ ] TEST: session expiration (due to changes in auth)
- [ ] TEST: fake locker plugin (@LukasReschke ?)

**Comment by PVince81** [comment]
@DeepDiver1975 I tried to merge this with master so we can test web UI + webdav, but got a conflict on auth.php. Can you rebase this PR ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I tried to merge this with master so we can test web UI + webdav, but got a conflict on auth.php. Can you rebase this PR ?

I rebased this just a few minutes ago ...

**Comment by DeepDiver1975** [comment]
grrrr ...

```
03:58:46 ............................PHP Fatal error:  Uncaught Error: Call to undefined method OCA\DAV\Connector\Sabre\Auth::authenticate() in /ssd/jenkins/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/dav/tests/unit/connector/sabre/auth.php:318

**Comment by PVince81** [comment]
Ah ok, then my local branch was probably not up to date.

**Comment by PVince81** [comment]
- [ ] BUG: folder not recognized as folder from the UI, I'll have a look at this one. resourcetype seems correct though.

**Comment by PVince81** [comment]
bäääh "resourcetype" is parsed as two newlines... will have to patch davclient.js again.

**Comment by PVince81** [comment]
We are currently experiencing temporary (and unexplained) issues with the smashing service, unrelated to this PR. Stay tuned.

**Comment by nickvergessen** [comment]
Smashing over lunch :hourglass_flowing_sand:

**Comment by nickvergessen** [comment]
Smashed: :white_check_mark:

**Comment by DeepDiver1975** [comment]
@LukasReschke @MorrisJobke please test the mac finder mount - THX

**Comment by PVince81** [comment]
Thanks, :+1: from me after the finder stuff is tested

**Comment by LukasReschke** [comment]
Works here for me :+1:

**Comment by DeepDiver1975** [comment]
3rdparty merged ... updating ref ....

**Comment by MorrisJobke** [comment]
This doesn't work. The web UI shows folders as zero byte files and once you click on them a white page with 

> This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.

appears.

Happens in (often refreshed) Chrome and safari :-1: from me

**Comment by MorrisJobke** [comment]
Ah...congrats to @DeepDiver1975 for rebasing before pulling:

bildschirmfoto 2015-11-24 um 15 24 25


@PVince81's fixes are gone in this PR

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/commit/11e19835c736d2143a909450287875c34e750282

**Comment by MorrisJobke** [comment]
Also https://github.com/owncloud/core/commit/d1c8f6190238196e98745bc2065014818415bf04 and https://github.com/owncloud/core/commit/d6d37b6230ff50dcf8c9023ffba266de00e6c292 are gone ;)

**Comment by DeepDiver1975** [comment]
> Also d1c8f61 and d6d37b6 are gone ;)

no - squashed

**Comment by MorrisJobke** [comment]
> no - squashed

Ah...okay, I just had a look and can't find the changes easily.

**Comment by MorrisJobke** [comment]
I tested it also with Finder. 

Also WebUI now works again.

Works :+1:

**Pull request merged**
