### PR TITLE
Fix ocs expectation

### LINKED ISSUE #27098: Failed tesst on master related to OCS
Possibly introduced after merging https://github.com/owncloud/core/pull/27076

https://jenkins.owncloud.org/job/owncloud-core/job/core/job/master/356/

```
13:23:41     /var/lib/jenkins/workspace/owncloud-core_core_master-34LTVSCLINVJJ27NGKSEQIHMECTKVSQK3BNUXCMTIMC23OPFL6GA@2/build/integration/federation_features/federated.feature:187
13:23:41     /var/lib/jenkins/workspace/owncloud-core_core_master-34LTVSCLINVJJ27NGKSEQIHMECTKVSQK3BNUXCMTIMC23OPFL6GA@2/build/integration/sharees_features/sharees_provisioningapiv2.feature:167
```
No encryption nor alt home involved.

Let's hope it's not some crazy side effect.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41737092-failed-tesst-on-master-related-to-ocs?utm_campaign=plugin&utm_content=tracker%2F216439&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F216439&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by PVince81**
## Description
OCS madness requires a status code in the response and also the HTTP status code.
When I fixed https://github.com/owncloud/core/pull/27076 I forgot that there were two status codes and forgot to leave the old one in. Fortunately some tests failed to enforce this.

## Related Issue
Fixes https://github.com/owncloud/core/issues/27098

## Motivation and Context
Don't ask, it's OCS madness...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@DeepDiver1975 please review this OCS madness

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
hmmm - we did not catch this because the integration tests are not executed on prs - maybe run one config with prs as well?

**Comment by PVince81** [comment]
@DeepDiver1975 added here https://github.com/owncloud/core/pull/27099/commits/3d37d300e9e6aaf29e4573eaa9f863b6254adc5d?w=1

Will backport that one commit after the merge.

**Comment by PVince81** [comment]
@DeepDiver1975 tests passed on Jenkins, unpublished. Merge ?

**Comment by PVince81** [comment]
forward port of the commit that reenables int tests on PR:
- stable9.1: https://github.com/owncloud/core/pull/27106 
- stable9: https://github.com/owncloud/core/pull/27107

**Comment by PVince81** [comment]
Had to rebase due to a conflict from another merge...

**Comment by PVince81** [comment]
Looks like luck is not on our side today:
```
19:40:14 Waiting for MySQL(utf8mb4) initialisation ...
19:41:15 ....................
19:41:15 [ERROR] Waited 60 seconds, no response
19:41:15 Kill the docker 2b140c15530c271e95626bc6f772005c452a02d0f73ca931f54c7c5d2cf39a16
```

**Comment by PVince81** [comment]
@DeepDiver1975 tests passed again now, merge ?

**Pull request merged**
