### PR TITLE
updated dependencies

### PR DESCRIPTION
**Pull request by phisch**
## Description
Updated dependencies with composer.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Uh oh, trouble ahead:
```
16:03:37   Problem 1
16:03:37     - Installation request for ocramius/package-versions 1.1.2 -> satisfiable by ocramius/package-versions[1.1.2].
16:03:37     - ocramius/package-versions 1.1.2 requires php ~7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
16:03:37   Problem 2
16:03:37     - Installation request for ocramius/proxy-manager 2.1.1 -> satisfiable by ocramius/proxy-manager[2.1.1].
16:03:37     - ocramius/proxy-manager 2.1.1 requires php ^7.1.0 -> your PHP version (5.6.30) does not satisfy that requirement.
16:03:37   Problem 3
16:03:37     - ocramius/proxy-manager 2.1.1 requires php ^7.1.0 -> your PHP version (5.6.30) does not satisfy that requirement.
16:03:37     - sensiolabs/behat-page-object-extension v2.0.1 requires ocramius/proxy-manager ^1.0||^2.0 -> satisfiable by ocramius/proxy-manager[2.1.1].
16:03:37     - Installation request for sensiolabs/behat-page-object-extension v2.0.1 -> satisfiable by sensiolabs/behat-page-object-extension[v2.0.1].
```

@individual-it @phil-davis

**Comment by PVince81** [comment]
if this was already like this in a RC we might be safe... but we can't update composer.lock as it might endanger future build script runs...

**Comment by PVince81** [comment]
can we revert for 10.0.1 and solve properly for 10.0.2 ?

@individual-it @phil-davis @DeepDiver1975 @phisch

**Comment by phil-davis** [comment]
Commit https://github.com/owncloud/core/commit/7896db7a3556700f15e17fbd3ba6edd59f7d546f just bumped:
"behat/mink-selenium2-driver": "dev-master"
(from 1.3)
to get some new tests working.

Has that somehow caused this huge change to dependency diffs here?

@individual-it ?

**Comment by PVince81** [comment]
Usually when updating composer.json one needs to also commit composer.lock.

At this point please don't merge this PR before 10.0.2

**Comment by individual-it** [comment]
Strange, composer.lock was changed after bumping the version of the selenium driver https://github.com/owncloud/core/pull/27944/files#diff-1da2c7edc898c70e5a79a9997c98cecc

**Comment by phil-davis** [comment]
When I use current master on my Ubuntu 16.04 development VM (that includes the recent small changes to composer.json and composer.lock for behat/mink-selenium2-driver I can do:
```
phil@phil-VirtualBox:~/core$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
  - Installing behat/mink-selenium2-driver (dev-master 739b757)
    Cloning 739b7570f0536bad9b07b511a62c885ee1ec029a

Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating optimized autoload files
```
and running the Behat end-to-end UI tests passes (I checked with Chrome)

As long as people use "composer install" then it will just install for them what is in composer.lock - e.g. in this case I just got behat/mink-selenium2-driver (dev-master).

**Comment by phil-davis** [comment]
Composer update gets me:
```
phil@phil-VirtualBox:~/core$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)


  - Installing ocramius/package-versions (1.1.2)
    Downloading: 100%         

  - Removing symfony/routing (v3.2.4)
  - Installing symfony/routing (v3.2.8)
    Downloading: 100%         

  - Removing symfony/process (v3.2.4)
  - Installing symfony/process (v3.2.8)
    Downloading: 100%         

  - Removing league/flysystem (1.0.35)
  - Installing league/flysystem (1.0.40)
    Downloading: 100%         

  - Removing symfony/yaml (v3.2.4)
  - Installing symfony/yaml (v3.2.8)
    Downloading: 100%         

  - Removing sebastian/diff (1.4.1)
  - Installing sebastian/diff (1.4.3)
    Downloading: 100%         

  - Removing phpunit/php-code-coverage (4.0.7)
  - Installing phpunit/php-code-coverage (4.0.8)
    Downloading: 100%         

  - Removing myclabs/deep-copy (1.6.0)
  - Installing myclabs/deep-copy (1.6.1)
    Downloading: 100%         

  - Removing phpunit/phpunit (5.7.15)
  - Installing phpunit/phpunit (5.7.20)
    Downloading: 100%         

  - Removing zendframework/zend-code (2.6.3)
  - Installing zendframework/zend-code (3.1.0)
    Downloading: 100%         

  - Removing ocramius/proxy-manager (1.0.2)
  - Installing ocramius/proxy-manager (2.0.4)
    Downloading: 100%         

  - Removing symfony/filesystem (v3.2.4)
  - Installing symfony/filesystem (v3.2.8)
    Downloading: 100%         

  - Removing symfony/config (v3.2.4)
  - Installing symfony/config (v3.2.8)
    Downloading: 100%         

  - Removing symfony/css-selector (v2.8.18)
  - Installing symfony/css-selector (v2.8.20)
    Downloading: 100%         

  - Removing symfony/translation (v3.2.4)
  - Installing symfony/translation (v3.2.8)
    Downloading: 100%         

  - Removing symfony/event-dispatcher (v3.2.4)
  - Installing symfony/event-dispatcher (v3.2.8)
    Downloading: 100%         

  - Removing symfony/dependency-injection (v3.2.4)
  - Installing symfony/dependency-injection (v3.2.8)
    Downloading: 100%         

  - Removing symfony/debug (v3.2.4)
  - Installing symfony/debug (v3.2.8)
    Downloading: 100%         

  - Removing symfony/console (v3.2.4)
  - Installing symfony/console (v3.2.8)
    Downloading: 100%         

  - Removing symfony/class-loader (v3.2.4)
  - Installing symfony/class-loader (v3.2.8)
    Downloading: 100%         

  - Removing behat/transliterator (v1.1.0)
  - Installing behat/transliterator (v1.2.0)
    Downloading: 100%         

  - Removing behat/behat (v3.3.0)
  - Installing behat/behat (v3.3.1)
    Downloading: 100%         

  - Removing sensiolabs/behat-page-object-extension (v2.0.1)
  - Installing sensiolabs/behat-page-object-extension (v2.1.0)
    Downloading: 100%         

  - Removing paragonie/random_compat (v2.0.9)
  - Installing paragonie/random_compat (v2.0.10)
    Downloading: 100%         

  - Removing react/promise (v2.5.0)
  - Installing react/promise (v2.5.1)
    Downloading: 100%         

  - Removing symfony/dom-crawler (v2.8.18)
  - Installing symfony/dom-crawler (v2.8.20)
    Downloading: 100%         

  - Removing symfony/browser-kit (v2.8.18)
  - Installing symfony/browser-kit (v2.8.20)
    Downloading: 100%         

Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Writing lock file
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
```

**Comment by phil-davis** [comment]
The resulting composer.lock for me is at https://github.com/owncloud/core/tree/composer-lock-check
And that does have a mention of php 7 at https://github.com/owncloud/core/blob/composer-lock-check/composer.lock#L3868 that looks like it really wants it (not an || with php 5).
Hmmm - is that something that has just been waiting for someone to type "composer update"?

**Comment by phil-davis** [comment]
Start with a composer.json and composer.lock from before https://github.com/owncloud/core/commit/cac897be7f1bbc4b63d684e70a4caa80ada8b608 then add the lines that were added in that commit:
```
"behat/mink-extension": "^2.2",
"behat/mink-goutte-driver": "^1.2",
"behat/mink-selenium2-driver": "^1.3",
"sensiolabs/behat-page-object-extension": "^2.0",
```
to composer.json and make a new composer.lock
```
composer update
```
in the original commit, things that added mentions of php 7.* had it "or"d with php 5.* which was all good.
Now the "composer update" produces things that mention php 7 outright, e.g. some ocramius stuff like:
```
"require": {
    "ocramius/package-versions": "^1.0",
    "php": "7.0.0 - 7.0.5 || ^7.0.7",
    "zendframework/zend-code": "3.0.0 - 3.0.2 || ^3.0.4"
},
```
which I guess is the problem.
What to look at/do next?

**Comment by phil-davis** [comment]
A a similar php 7 dependency in the tree discussed at https://github.com/dustin10/VichUploaderBundle/issues/564

**Comment by PVince81** [comment]
Can we get this sorted out soon ? We'll likely need to upgrade other libraries soon...

**Comment by PVince81** [comment]
@phil-davis @phisch any update ? or abandon ?

**Comment by phil-davis** [comment]
@individual-it - we had to use some "latest" behat or mink or... stuff, which I think does not help here (tends to want to pull in dependencies that end up with PHP7 being forced somewhere). Where did that get to? I think I remember there were some people asking for a point release to be made of some "fix" and that could get us out of having to use the "latest dev"?
Or am I just rambling?

**Comment by individual-it** [comment]
tried to run `composer update` on current master on a php 5.6 box
(before I've done a "normal" `make`)
It seems to work and even does not try to load ocramius tuff. Why is it different for me?
```
Package operations: 0 installs, 30 updates, 0 removals
  - Updating pear/archive_tar (1.4.2 => 1.4.3): Downloading (100%)         
  - Updating symfony/routing (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating symfony/process (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating league/flysystem (1.0.35 => 1.0.40): Downloading (100%)         
  - Updating paragonie/random_compat (v2.0.9 => v2.0.10): Downloading (100%)         
  - Updating symfony/polyfill-php70 (v1.3.0 => v1.4.0): Downloading (100%)         
  - Updating symfony/yaml (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating sebastian/diff (1.4.1 => 1.4.3): Downloading (100%)         
  - Updating phpunit/phpunit-mock-objects (3.4.3 => 3.4.4): Downloading (100%)         
  - Updating phpunit/php-code-coverage (4.0.7 => 4.0.8): Downloading (100%)         
  - Updating myclabs/deep-copy (1.6.0 => 1.6.1): Downloading (100%)         
  - Updating phpunit/phpunit (5.7.15 => 5.7.21): Downloading (100%)         
  - Updating symfony/filesystem (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating symfony/config (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating symfony/css-selector (v2.8.18 => v2.8.24): Downloading (100%)         
  - Updating symfony/polyfill-mbstring (v1.3.0 => v1.4.0): Downloading (100%)         
  - Updating symfony/translation (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating symfony/event-dispatcher (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating symfony/dependency-injection (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating symfony/debug (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating symfony/console (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating symfony/class-loader (v3.2.4 => v3.3.3): Downloading (100%)         
  - Updating behat/transliterator (v1.1.0 => v1.2.0): Downloading (100%)         
  - Updating behat/behat (v3.3.0 => v3.3.1): Downloading (100%)         
  - Updating sensiolabs/behat-page-object-extension (v2.0.1 => v2.1.0): Downloading (100%)         
  - Updating sabre/http (4.2.2 => 4.2.3): Downloading (100%)         
  - Updating instaclick/php-webdriver (1.4.3 => 1.4.5): Downloading (100%)         
  - Updating react/promise (v2.5.0 => v2.5.1): Downloading (100%)         
  - Updating symfony/dom-crawler (v2.8.18 => v2.8.24): Downloading (100%)         
  - Updating symfony/browser-kit (v2.8.18 => v2.8.24): Downloading (100%)    
```

**Comment by DeepDiver1975** [comment]
conflicting - outdated - failing -> close

**Pull request closed without merging**
