### PR TITLE
Update - Only add one section for disabled apps

### LINKED ISSUE #19891: Upgrade disabled apps listed twice
When running an upgrade where apps get disabled, the disabled apps get listed twice:

screenshot_2015-10-20_13-17-23

cc @PVince81

### PR DESCRIPTION
**Pull request by nickvergessen**
owncloud_-_2015-10-21_10 51 36

@MorrisJobke @PVince81 @jancborchardt 

Fix #19891

### CODE REVIEW

**Comment by nickvergessen** [comment]
cc @Xenopathic

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by DeepDiver1975** [comment]
> Fix #19891

only partially since there will still be two entries for calendar - right?

**Comment by MorrisJobke** [comment]
> only partially since there will still be two entries for calendar - right?

No. There was only the "3rdparty" one, when I tested. Let me force an incompatible info.xml and retest.

**Comment by nickvergessen** [comment]
> only partially since there will still be two entries for calendar - right?

No, that's why the array uses the appid as index key.
Incompatible is prefered over 3rdparty.

**Comment by DeepDiver1975** [comment]
> No, that's why the array uses the appid as index key.
> Incompatible is prefered over 3rdparty.

THX - did not see that :+1:

**Comment by jancborchardt** [comment]
Thanks!

**Pull request merged**
