### PR TITLE
[stable8.2] When sharing with the owner show the path

### PR DESCRIPTION
**Pull request by rullzer**
Backport of #19820

@karlitschek please approve the backport.

CC: @MorrisJobke @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
you probably meant 8.2.1 ?

**Comment by karlitschek** [comment]
backport is fine for 8.2.1 :-)  Too late for 8.2.0

**Comment by rullzer** [comment]
@PVince81 yes of course :)

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
