### PR TITLE
sidebar click modification

### LINKED ISSUE #23381: Open sidebar when clicking in the right part of rows in files view
### Steps to reproduce

1. Having a file or folder uploaded, try to open sidebar clicking at the right of the three dots.

### Expected behaviour
Sidebar opens.

I'd expect specially that the sidebar opens in the orange area:

screen shot 2016-03-18 at 08 59 22

But perhaps it is interesting to allow opening sidebar in the pink area as well.

### Actual behaviour
Nothing happens.

### PR DESCRIPTION
**Pull request by ErikPel**
Fixes #23381

@SergioBertolinSG

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
The menu which opens when clicking on the three dots is moved:

screen shot 2016-03-23 at 13 34 34

**Comment by ErikPel** [comment]
@SergioBertolinSG didn't realize that has to be moved. I'll get it sorted out. Other than that, how does it look?

**Comment by SergioBertolinSG** [comment]
@ErikPel besides that looks fine.

**Comment by ErikPel** [comment]
@SergioBertolinSG how about now?

**Comment by SergioBertolinSG** [comment]
Fine :+1:

Code review @owncloud/javascript

**Comment by nickvergessen** [comment]
@PVince81

**Comment by PVince81** [comment]
@ErikPel failing JS unit tests:
```
PhantomJS 2.1.1 (Linux 0.0.0) OCA.Files.FileList tests Details sidebar triggers file action when clicking on row if no details view configured FAILED
09:50:38 	Expected false to equal true.
09:50:38 	/ssd/jenkins/workspace/core-ci-linux-jsunit/database/sqlite/label/SLAVE/apps/files/tests/js/filelistSpec.js:1951:41
09:50:38 .......
09:50:38 PhantomJS 2.1.1 (Linux 0.0.0) OCA.Files.FileList tests File actions Clicking on a file name will trigger default action FAILED
09:50:38 	Expected false to equal true.
09:50:38 	/ssd/jenkins/workspace/core-ci-linux-jsunit/database/sqlite/label/SLAVE/apps/files/tests/js/filelistSpec.js:2054:41
09:50:38 ..[33mWARN [web-server]: [39m404: /actions/download.svg
09:50:39 ..............................................................................
09:50:39 .............
09:50:40 PhantomJS 2.1.1 (Linux 0.0.0) OCA.Sharing.App tests file actions redirects to files app when opening a directory FAILED
09:50:40 	Expected false to equal true.
09:50:40 	/ssd/jenkins/workspace/core-ci-linux-jsunit/database/sqlite/label/SLAVE/apps/files_sharing/tests/js/appSpec.js:139:48
09:50:40 ..[33mWARN [web-server]: [39m404: /svg
```

To run them: `./autotest-js.sh` (requires nodejs + npm)

**Comment by ErikPel** [comment]
Tests pass now. @PVince81

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by DeepDiver1975** [comment]
rebased and squashed

**Comment by SergioBertolinSG** [comment]
Backport to stable9? @karlitschek @PVince81

**Comment by karlitschek** [comment]
please backport

**Comment by jancborchardt** [comment]
@ErikPel did you backport this already? Do you know how to do this via git cherry-pick on the commit to stable9?

**Comment by ErikPel** [comment]
@janborchardt oh sorry, didn't know those were adressed to me. And no, I don't know how to do thay

**Comment by nickvergessen** [comment]
```
git fetch origin stable9
git checkout stable9
git checkout -b backport-23511
git cherry-pick 50655cb
git push origin backport-23511
```

And then send a PR from `backport-23511` against `stable9`

**Pull request merged**
