### PR TITLE
No need to url decode the file

### LINKED ISSUE #18074: [Thumbnails api] No thumbnail is returned if the name contains +
### Steps to reproduce
1. There is an image called +.JPG
2. Using curl, it is possible to see that no thumbnail is returned

```curl -u user server/index.php/apps/files/api/v1/thumbnail/25/25/%2B.JPG```

neither

 ```curl -u user server/index.php/apps/files/api/v1/thumbnail/25/25/+.JPG```

It is possible to check it coping the url in the browser
	server/index.php/apps/files/api/v1/thumbnail/25/25/%2B.JPG

What it is received is {"message":"File not found."}

### Expected behaviour
thumbnail is returned

### Actual behaviour
This message is shown {"message":"File not found."} instead of the thumbnail

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:**  apache 2.4.7

**Database:** mysql

**PHP version:**  5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1"}

This affect the android app.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #18074

Please test @rperezb @purigarcia 

Please review @rullzer @PVince81

### CODE REVIEW

**Comment by LukasReschke** [comment]
I think we added it by purpose at https://github.com/owncloud/core/commit/f451ecb8d848636f37d8c80f1f12ab3c695c136f. @tobiasKaminsky requested this at https://github.com/owncloud/core/pull/11009#issuecomment-56108434

I'd like to have this double-checked from @tobiasKaminsky as well.

**Comment by oparoz** [comment]
That's not the solution -> https://github.com/owncloud/core/issues/17855

**Comment by DeepDiver1975** [comment]
let me test rawurldecode ...

**Comment by DeepDiver1975** [comment]
For me $file is already decoded when entering the method - are there scenarios where this is not the case?
I'm testing with php development server ... let me retest this with apache ....

**Comment by DeepDiver1975** [comment]
> I'm testing with php development server ... let me retest this with apache ....

same with apache - no need to decode from my pov

**Comment by oparoz** [comment]
> For me $file is already decoded when entering the method - are there scenarios where this is not the case?

Yes, using the Android app, because of this:

> In the android app I am using GetMethod(String uri) to retrieve the thumbnail.
This uri has to be escaped via URLEncoder.encode(uri), otherwise I get "escaped absolute path not valid".

The only problem with having a decoder is if people start naming their files file_version_%2B.txt, but from my pov, supporting the Android client is more important.

I'm guessing you've tested with the browser? If that's the case, try with the curl command given by the user
`curl -u user server/index.php/apps/files/api/v1/thumbnail/25/25/%2B.JPG`

**Comment by DeepDiver1975** [comment]
> I'm guessing you've tested with the browser? If that's the case, try with the curl command given by the user
> curl -u user server/index.php/apps/files/api/v1/thumbnail/25/25/%2B.JPG

I'm testing with curl

````
$ curl -u admin http://localhost/oc/core/index.php/apps/files/api/v1/thumbnail/25/25/%2B.jpeg

**Comment by DeepDiver1975** [comment]
> The only problem with having a decoder is if people start naming their files file_version_%2B.txt, but from

This is not a problem since the path will be (as in has to be) encoded.

**Comment by oparoz** [comment]
@DeepDiver1975 - I figured out why you're seeing these results. You're on 8.2 and the AppFramework has probably already been fixed.

Try on 8.1

**Comment by oparoz** [comment]
Never mind, I was still testing with the master URL.... I got the same resultss using curl

**Comment by oparoz** [comment]
OK, so both no decoding and rawurldecoding works on 8.1 and master.
I've tried with a folder, but the path fails if slashes are encoded.

We need @tobiasKaminsky to test this branch and to give us a test case or two.

**Comment by DeepDiver1975** [comment]
@rperezb can you please coordinate to get this tested with the mobile apps? THX

**Comment by tobiasKaminsky** [comment]
In our android app we are using: https://developer.android.com/reference/android/net/Uri.html#encode%28java.lang.String,%20java.lang.String%29

From there the initial fix is mentioned: https://github.com/owncloud/core/pull/11009#issuecomment-56305128

This is a reference by @oparoz https://github.com/owncloud/core/pull/11675#issuecomment-66182340

Slashes are not encoded, as we are using Uri.encode(file.getRemotePath(), "/"), which lets "/" intact.

**Comment by DeepDiver1975** [comment]
Is it depending on the PHP version if the URL params are decoded in the server or not?

**Comment by rperezb** [comment]
checked on Android, it works fine.
thx

**Comment by DeepDiver1975** [comment]
According to http://php.net/manual/en/function.urldecode.php#refsect1-function.urldecode-notes we should never have decoded the parameter ourselves.

@LukasReschke

**Comment by oparoz** [comment]
Are only some versions of Android affected?
Which were the test cases used in #11675 and why are they passing now?

**Comment by DeepDiver1975** [comment]
> checked on Android, it works fine.

taking this as the last remaining :+1:

**Comment by rperezb** [comment]
@oparoz on iOS, ftm, we have not implemented thumbnails, so no affected,

**Comment by PVince81** [comment]
Should this be backported to stable8.1 ?

**Pull request merged**
