### PR TITLE
Personal calendar should be generated even if the birthday calendar a…

### LINKED ISSUE #24082: No "Personal" calendar created for installing user
### Steps to reproduce
1. Install owncloud as user admin
2. Login as user admin
3. Check that the default calendar "Personal" is created

### Expected behaviour
Should exist

### Actual behaviour
Only calendar "Contact birthdays" is created.
https://github.com/owncloud/core/pull/24076#issuecomment-211783838

> Btw for my admin user the personal calendar is not created on login, because the birthday calendar got already generated on install, so `if (empty($calendars)) {` is not true.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…lready exists - fixes #24082

@nickvergessen @MorrisJobke THX

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1: fixes my problem

**Comment by MorrisJobke** [comment]
Tested and works now 👍

**Comment by DeepDiver1975** [comment]
@nickvergessen @MorrisJobke is 9.0 affected as well? I guess so ... backport?

**Comment by nickvergessen** [comment]
It does

**Comment by DeepDiver1975** [comment]
@karlitschek requesting backport

**Comment by karlitschek** [comment]
backport makes sense :+1:

**Comment by DeepDiver1975** [comment]
> backport makes sense :+1:

thx

**Pull request merged**
