### PR TITLE
Unified symfony event for updates happening in share

### PR DESCRIPTION
**Pull request by sharidas**
A unified symfony event for updates happening in share.
This change covers the updates for updates in:
a) share name
b) password change
c) update in expiry date
d) update of permission

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

A unified event to handle updates in share, like:
a) share name update
b) share password update
c) update of expiry date
d) permissions

## Motivation and Context

A unified event to handle updates in share, like:
a) share name update
b) share password update
c) update of expiry date
d) permissions

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
