### PR TITLE
Also exclude __apps

### PR DESCRIPTION
**Pull request by LukasReschke**
Workaround for https://github.com/owncloud/updater/issues/331 for 9.0.2

cc @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Looks like the patch worked, no more infinite loop. :+1: 

There's another issue that I will report soon.

**Comment by LukasReschke** [comment]
@karlitschek In case the updater fails at one of the steps this will hide the actual error message and make debugging very hard. See for example https://github.com/owncloud/updater/issues/335 (@PVince81's follow-up).

I propose a backport to stable9 so we have some proper means for debugging. Any objections?

**Comment by PVince81** [comment]
@VicDeo second review ?

@karlitschek backport ?

**Comment by PVince81** [comment]
I will do the backport to save some time.

**Comment by VicDeo** [comment]
:+1: looks good

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/24292

**Pull request closed without merging**
