### PR TITLE
Ignore minified js in translation process

### PR DESCRIPTION
**Pull request by BernhardPosselt**
owncloud/news#719

@DeepDiver1975 @jakobsack @MorrisJobke @LukasReschke 

I have no idea what I'm doing (I dont know perl) but this should work.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@Raydiation this perl script is used for core only

**Comment by DeepDiver1975** [comment]
This is the script used for apps: https://github.com/owncloud/administration/blob/master/jenkins/translation_sync/l10n.pl

**Comment by DeepDiver1975** [comment]
We had a similar case with another app - the solution was to NOT checking build artifacts :speak_no_evil:

**Comment by Raydiation** [comment]
What does not checking build artifacts mean?

**Comment by DeepDiver1975** [comment]
> checking

check-in :speak_no_evil:

**Comment by Raydiation** [comment]
i see :)

Not a solution. A user should be able to git clone the repo into the apps folder and it have it working right away

**Comment by DeepDiver1975** [comment]
AFAIK there is a way to exclude folders - let me get this sorted out these days.

**Comment by Raydiation** [comment]
Minified files should be ignored nonetheless, if not for the sake of preventing mistakes then for the sake of speed

**Comment by PVince81** [comment]
I agree with this change :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
rescheduling to 8.1 - translation kung-fu only applies to master branches

**Pull request merged**
