### PR TITLE
Debounce cancel upload message

### PR DESCRIPTION
**Pull request by icewind1991**
Re-submit of https://github.com/owncloud/core/pull/19628 which was merged to early and reverted

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks

**Comment by MorrisJobke** [comment]
@PVince81 Can you please create the backport PR for 8.2.1

**Comment by PVince81** [comment]
CC @karlitschek for backport confirmation (due to the revert/resend confusion)

**Comment by karlitschek** [comment]
yes. please backport :+1:  :-)

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19778

**Pull request merged**
