### PR TITLE
API test for disableSharing

### PR DESCRIPTION
**Pull request by paurakhsharma**
## Description
This PR adds test to check API behavior when link sharing is disabled.

## Related Issue
#31531 

## How Has This Been Tested?
Locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Acceptance test

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
We could also add scenarios that try to share a folder, and make sure that does not work.

**Comment by paurakhsharma** [comment]
What are other scenarios you think I should add here? I will add scenarios for public share after #31677 is merged.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
This seems a good set of tests. So I will merge when CI finishes.

**Comment by paurakhsharma** [comment]
Thank you, @phil-davis I will remember it form next time.

**Comment by paurakhsharma** [comment]
Backport on #31694

**Pull request merged**
