### PR TITLE
[WIP] backport callforseenusers to stable9

### PR DESCRIPTION
**Pull request by butonic**
backport of https://github.com/owncloud/core/pull/26361 to stable9
there are changes I need to get into core first, so this is on hold

### CODE REVIEW

**Comment by PVince81** [comment]
moving to 9.0.7

**Comment by PVince81** [comment]
@butonic any update ? what are those core changes ?

**Comment by PVince81** [comment]
Finish this for 9.0.9 ?

By the way, I think @jvillafanez saw a perf issue with LDAP regarding these functions

**Comment by PVince81** [comment]
@butonic is this backport still worth it or close ?

**Comment by PVince81** [comment]
would close in favor of "upgrade! upgrade! upgrade!

**Comment by DeepDiver1975** [comment]
stable9 is on sec patches only -> close

**Pull request closed without merging**
