### PR TITLE
Don't load commands of apps when in maintenance mode

### LINKED ISSUE #20939: occ fails hard if instance is in maintenance mode
```
$ ./occ list
PHP Fatal error:  Class 'OC_Mount_Config' not found in /home/deepdiver/Development/ownCloud/master-autotest/apps/files_external/appinfo/register_command.php on line 30
PHP Stack trace:
PHP   1. {main}() /home/deepdiver/Development/ownCloud/master-autotest/occ:0
PHP   2. require_once() /home/deepdiver/Development/ownCloud/master-autotest/occ:11
PHP   3. OC\Console\Application->loadCommands($output = *uninitialized*) /home/deepdiver/Development/ownCloud/master-autotest/console.php:68
PHP   4. require() /home/deepdiver/Development/ownCloud/master-autotest/lib/private/console/application.php:64

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #20939

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@karlitschek this can happen on previous version of ownCloud as well

**Comment by karlitschek** [comment]
Wow. Didn't we fix this before? Strange.
Backport makes sense :+1:

**Comment by DeepDiver1975** [comment]
> Wow. Didn't we fix this before? Strange.

no - we did fix it for the upgrade case - but not if the instance stays in maintenance mode afterwards

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
preparing backports ....

**Comment by Xenopathic** [comment]
As an admin, I want to be able to modify my LDAP configuration and external storages, re-scan the filesystem and do other maintenance stuff while my instance is in maintenance mode. Can I still do that?

**Comment by MorrisJobke** [comment]
> As an admin, I want to be able to modify my LDAP configuration and external storages, re-scan the filesystem and do other maintenance stuff while my instance is in maintenance mode. Can I still do that?

Changing LDAP stuff is not possible, because it is an app.

**Comment by MorrisJobke** [comment]
The other mentioned stuff is possible

**Comment by Xenopathic** [comment]
@MorrisJobke But that would be one of the main reasons I *would* put my instance into maintenance mode, to adjust critical settings such as LDAP!

**Comment by MorrisJobke** [comment]
> @MorrisJobke But that would be one of the main reasons I would put my instance into maintenance mode, to adjust critical settings such as LDAP!

It's boon and bane of the apps. We either enable them and they cause trouble because the instance is in maintenance mode or we can disable them and then their functionality is missing.

**Comment by Xenopathic** [comment]
@MorrisJobke As I pointed out right at the beginning (https://github.com/owncloud/core/issues/20939#issuecomment-161908840) the problem isn't with the apps, it's with our app loader mechanism.

**Comment by MorrisJobke** [comment]
> @MorrisJobke As I pointed out right at the beginning (#20939 (comment)) the problem isn't with the apps, it's with our app loader mechanism.

Ah. Now it makes sense. Okay - why is this mechanism in place there? I guess it has a reason ;)

**Comment by Xenopathic** [comment]
@MorrisJobke From what I can tell, it's a basic hack to stop ownCloud from loading apps while in maintenance mode, since they (usually) aren't needed. Except when using occ to perform maintenance on an app. The easiest way to solve it, as I mentioned, is to call `loadApp()` on each installed app individually when we load app commands, rather than rely on `loadApps()` to do all of it for us.

**Pull request merged**
