### PR TITLE
clarify filesystem_check_changes in config.sample.php

### PR DESCRIPTION
**Pull request by carlaschroder**
Needs to specify that it is for local, not external storages

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
:+1:

**Comment by carlaschroder** [comment]
This needs to be propagated to `https://github.com/owncloud/documentation/blob/master/admin_manual/configuration_server/config_sample_php_parameters.rst`.  @MorrisJobke wrote a script to sync the manual page with this file, and as I recall he ran it manually.
@PVince81

**Comment by PVince81** [comment]
I don't remember :frowning: 
With a bit of luck it might be automatic as part of the documentation makefiles ?

**Comment by carlaschroder** [comment]
> With a bit of luck it might be automatic as part of the documentation makefiles ?

I'm pretty sure not. I'll ask Morris.

**Comment by MorrisJobke** [comment]
> I'm pretty sure not. I'll ask Morris.

It still runs here and was pushed :)

**Comment by PVince81** [comment]
> here

where ?

> pushed

where ?

**Comment by MorrisJobke** [comment]
> where ?

localhost 😝 



> where ?

https://github.com/owncloud/documentation/commit/c53c951ba03f8020187619e3708d7a4f478af2e0

Code: https://github.com/MorrisJobke/ownCloud-config-converter

**Comment by carlaschroder** [comment]
> Code: https://github.com/MorrisJobke/ownCloud-config-converter

@MorrisJobke I tried following your instructions (yay instructions!), installed dependencies with `composer install, composer require phpdocumentor/reflection-docblock`, and now I am stuck at this error: 

`core$ php ../ownCloud-config-converter/convert.php 
PHP Fatal error:  Call to undefined method phpDocumentor\Reflection\DocBlock::getShortDescription() in /home/carla/Documents/11owncloud/git-repos/ownCloud-config-converter/convert.php on line 183`

Any hints how to fix this?

**Comment by carlaschroder** [comment]
Google is unhelpful.

**Comment by MorrisJobke** [comment]
Which version is installed? I run this with 2.0.3 of reflection-docblock

**Comment by carlaschroder** [comment]
I'm not very experienced with composer-- it tells me this:
````
$ composer show -i
hamcrest/hamcrest-php             v1.2.2 This is the PHP port of Hamcrest Matchers
mockery/mockery                   0.9.5  Mockery is a simple yet flexible PHP mock object framework for use in unit testing w...
phpdocumentor/reflection-common   1.0    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock 3.0.1  With this component, a library can provide support for annotations via DocBlocks or ...
phpdocumentor/type-resolver       0.1.8  
webmozart/assert                  1.0.2  Assertions to validate method input/output with nice error messages.

**Comment by MorrisJobke** [comment]
maybe drop the vendor folder and reset the composer.lock file. Then run only `composer install`

**Comment by carlaschroder** [comment]
Thanks @MorrisJobke, I'll try that.

**Comment by carlaschroder** [comment]
\o/ It works! I blew away composer and re-installed it according to http://symfony.com/doc/current/cookbook/composer.html. No more weird errors, just nice fresh config.sample.php files.

Now more than one person knows how to do this, which is always good. :metal:

**Pull request merged**
