### PR TITLE
[jenkins] Webdav handle server not available exception ci

### PR DESCRIPTION
**Pull request by DeepDiver1975**
for https://github.com/owncloud/core/pull/17224

### CODE REVIEW

**Comment by LukasReschke** [comment]
> Expectation failed for method name is equal to <string:setAppValue> when invoked at sequence index 1
Parameter 2 for invocation OCP\IConfig::setAppValue('core', 'lastupdatedat', 1435590320) does not match expected value.
Failed asserting that 1435590320 matches expected 1435590319.

I'm to blame for that… Let me create a PR that does not rely on PHP being fast :see_no_evil:

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Comment by MorrisJobke** [comment]
@LukasReschke Please port this to the original PR, because this is a jenkins PR.

**Comment by LukasReschke** [comment]
I shall do what? I'm not touching and rebasing anything :speak_no_evil:

**Comment by MorrisJobke** [comment]
> I shall do what? I'm not touching and rebasing anything :speak_no_evil:

Oh. I thought you added commits, but you only referenced this PR ;)

**Comment by LukasReschke** [comment]
:angel:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Pull request closed without merging**
