### PR TITLE
fix trusted domain localization

### PR DESCRIPTION
**Pull request by vgezer**
well, it seems this also has been forgotten to be changed.

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Can we delay this to 8.1? Because otherwise translations are broken with no actual reason.

**Comment by LukasReschke** [comment]
Erm… - Translations *ARE* actually already broken ;-) – With this patch they actually work…

**Comment by MorrisJobke** [comment]
Oh. Just tested. :+1: You're right. This fixes the problem and result in correct translations. Sorry

**Comment by MorrisJobke** [comment]
@DeepDiver1975 This is a small fix that doesn't have any risk. something for 8.0? The translations are already in settings in place

**Pull request merged**
