### PR TITLE
Return proper error when destination header is missing

### LINKED ISSUE #38898: Restoring a file/folder from trashbin without specifying the destination header gives 403 forbidden with confusing message
### Steps to reproduce
1. Create a folder and file `parent/sub/parent.txt`
2. Delete folder `parent`
3. try to restore the deleted folder `parent` without giving the destination header 
```
curl -XMOVE http://localhost/core/remote.php/dav/trash-bin/admin/2147578722/ -u admin:admin -v
```

### Expected behaviour
Give http 400 response with correct error message

### Actual behaviour
Tell us what happens instead
The API returns http 403 forbidden response with following message
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message>Requested uri () is out of base uri (/core/remote.php/dav/)</s:message>
</d:error>
```

### Server configuration
**Operating system**: ubuntu 20.04

**Web server:** apache2

**Database:** Ver 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

**PHP version:** 7.4

**ownCloud version:** (see ownCloud admin page) git latest

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** git

### PR DESCRIPTION
**Pull request by JammingBen**
## Description
Move- and copy-requests without destination header now give a proper error response:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>The destination header was not supplied</s:message>
</d:error>
```

## Related Issue
- Fixes https://github.com/owncloud/core/issues/38898

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM - if the enabled acceptance tests pass then this is "a good thing"

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuthWebDav-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32390/48/1

**Comment by JammingBen** [comment]
@phil-davis I needed to add some default `Destination` headers in our acceptance-test suite - please have a look again. Let's see if it affects any other tests.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32397/144/1

**Review by phil-davis — APPROVED** [review]
Acceptance test changes look good. Those steps are not used for specifying a specific destination anyway - so `/path/to/folder` is fine as a "dummy" value.

Let's see what CI says - it might complain that the folder `path` etc does not exist.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32400/144/1

**Pull request merged**
