### PR TITLE
Bump php-cs-fixer from 2.11 to 2.12

### PR DESCRIPTION
**Pull request by phil-davis**
There are various fixes in there, including a Yoda-style one that I raised a few weeks ago.
https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.12.0

### CODE REVIEW

**Comment by phil-davis** [comment]
Backport not relevant because this is not yet impleneted in ``stable10`` - when it is, the current ``php-cs-fixer``` version will come there.

**Comment by DeepDiver1975** [comment]
hates us .....

**Comment by phil-davis** [comment]
I didn't think to actually run the fixer! It found more of Yoda's work. I will fix...

**Comment by phil-davis** [comment]
Gone is evidence of Yoda. Pass it now should.

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
Not sure which question you are asking but,
1) ``composer.json`` says to use php-cs-fixer ``2.11`` and up - so when ``2.12`` came out, a ``composer update`` finds it.
2) ``2.12`` has "Yoda" fixes that find and undo more "Yoda" code. So more "Yoda" speak it did find.

**Pull request merged**
