### PR TITLE
[stable9] Delay reloading the page if an ajax error occurs, show notification

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/24126 to stable9

Please review @rullzer @nickvergessen @owncloud/javascript

### CODE REVIEW

**Comment by PVince81** [comment]
For https://github.com/owncloud/core/issues/24309

**Comment by nickvergessen** [comment]
:+1: makes sense

**Comment by PVince81** [comment]
Second review @ChristophWurst @icewind1991 ?

**Comment by ChristophWurst** [comment]
:+1: looks good

**Pull request merged**
