### PR TITLE
Cron has to be executed with the correct user

### PR DESCRIPTION
**Pull request by DeepDiver1975**
the same approach as in https://github.com/owncloud/core/pull/13282

We need to cleanup this - we are duplicating too much stuff here.

Choosing simple approach to allow backport

@karlitschek @MorrisJobke @schiesbn please review - THX

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
fixes #15353, https://github.com/owncloud/core/issues/15299#issuecomment-88195061

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
The owner of `config.php` is not necessarily the web server user... Can you check something that is generated by ownCloud, like `data/.ocdata`?

**Comment by MorrisJobke** [comment]
> The owner of config.php is not necessarily the web server user... Can you check something that is generated by ownCloud, like data/.ocdata?

But it should.

**Comment by Xenopathic** [comment]
@MorrisJobke Why? The requirement is that the web server user can write the config.php, not that it owns it.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Why? The requirement is that the web server user can write the config.php, not that it owns it.

true story ... sorry.

**Comment by DeepDiver1975** [comment]
This is the check we have in place for the console as well since oc8.
I'd prefer to get this in now as well and backport this - further enhancments (not to be backported) will go in a second step into master only.

@Xenopathic sounds reasonable?

**Comment by Xenopathic** [comment]
@DeepDiver1975 OK, that sounds reasonable :smile:

Code looks good :+1:

**Comment by DeepDiver1975** [comment]
@karlitschek backport? THX

**Comment by karlitschek** [comment]
please backport. this is important

**Comment by DeepDiver1975** [comment]
@MorrisJobke @nickvergessen some spare time to prepare the PR for me? THX a lot!

**Comment by MorrisJobke** [comment]
stable8 #15369

**Comment by MorrisJobke** [comment]
stable7 #15370

**Pull request merged**
