### PR TITLE
[stable10] Use OC_DEFAULT_MODULE constant in core

### PR DESCRIPTION
**Pull request by sharidas**
Use OC_DEFAULT_MODULE constant in core. This
would help us to decouple the app dependency.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Use const 'OC_DEFAULT_MODULE' constant in core. This would help to reduce the dependency with encryption app.

## Motivation and Context

Use const 'OC_DEFAULT_MODULE' constant in core. This would help to reduce the dependency with encryption app.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
```
5) Test\Cache\FileCacheTest::testSimple
Exception: Bucket does not exist.

/drone/src/apps/files_primary_s3/lib/s3storage.php:103
/drone/src/apps/files_primary_s3/lib/s3storage.php:118
/drone/src/lib/private/Files/ObjectStore/ObjectStoreStorage.php:415
/drone/src/lib/private/Files/Stream/Close.php:104
/drone/src/lib/private/Files/Storage/Common.php:196
/drone/src/lib/private/Files/Storage/Wrapper/Wrapper.php:251
/drone/src/lib/private/Files/Storage/Wrapper/Availability.php:273
/drone/src/lib/private/Files/Storage/Wrapper/Checksum.php:191
/drone/src/lib/private/Files/View.php:1180
/drone/src/lib/private/Files/View.php:712
/drone/src/lib/public/Events/EventEmitterTrait.php:50
/drone/src/lib/private/Files/View.php:714
/drone/src/lib/private/Cache/File.php:112
/drone/src/tests/lib/Cache/FileCacheTest.php:83
```

@DeepDiver1975 need yet another rebase ?

**Pull request merged**
