### PR TITLE
Check usage of != and == 

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs #16054

@Raydiation @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Let's see if a possitive test also works :P I will add another test case with `===` and `!==`

**Comment by DeepDiver1975** [comment]
> Let's see if a possitive test also works :P I will add another test case with === and !==

more then welcome - push it ...

**Comment by MorrisJobke** [comment]
Seems to work :+1:

**Comment by LukasReschke** [comment]
Yes :+1:

**Comment by DeepDiver1975** [comment]
Remaining question: hard fail on this kind of errors?

**Comment by DeepDiver1975** [comment]
@owncloud-bot :skull: retest this please :hocho:

**Comment by Raydiation** [comment]
Awesome! :+1: 

Can we also get in_array with strict in (if possible at all)?

**Comment by LukasReschke** [comment]
> Can we also get in_array with strict in (if possible at all)?

I'm on that and others at the moment – let's move this to another PR.

**Comment by MorrisJobke** [comment]
> Remaining question: hard fail on this kind of errors?

No. Because we rely on these. I'm fine with the app code check approach.

**Comment by nickvergessen** [comment]
While it "only" says "discouraged", it still makes the app "not compliant" :-1:

**Comment by MorrisJobke** [comment]
> While it "only" says "discouraged", it still makes the app "not compliant" :-1:

The calls to our private APIs also works ... but it might break. The same applies for these stuff here. I'm against bringing in more logic just to have a slightly better wording.

**Comment by nickvergessen** [comment]
> The calls to our private APIs also works ... but it might break. The same applies for these stuff here. I'm against bringing in more logic just to have a slightly better wording.

That is not what I was refering to. I just hope no one ever submits a hook with a shareType that is a string instead of the const (int) e.g. when it's read from the database, because that will cause problems for apps now, when they need to `===` now:
https://github.com/owncloud/activity/pull/290/files#diff-80d6c46dcaf39a1ebaafb6e920b7eec6L175

**Comment by Raydiation** [comment]
Constants which are abused as enums are always ints. No need ever to use a string as a share constant.

**Comment by Raydiation** [comment]
Also I dont get the argument, shouldnt it be comparable just fine?

**Comment by nickvergessen** [comment]
Maybe you understand it like this:
```php

			$query = \OC_DB::prepare(
				'SELECT `share_type`, `file_source`, `file_target`
				FROM `*PREFIX*share`
				WHERE `item_source` = ? AND `share_with` = ? AND `item_type` IN (\'file\', \'folder\')'
			);

			$result = $query->execute(array($source, 'uid'));

			if (\OCP\DB::isError($result)) {
				\OCP\Util::writeLog('OCP\Share', \OC_DB::getErrorMessage(), \OC_Log::ERROR);
			} else {
				while ($row = $result->fetchRow()) {
					\OC_Hook::emit('OCP\Share', 'lalala', $row);
				}
			}
```

The hook has a string for the share_type not an int, so comparing to `=== Share::SHARE_TYPE_GROUP``will fail.

anyway, I'm done here :speak_no_evil:

**Comment by Raydiation** [comment]
should be **(int) $valueInDb === Share::SHARE_TYPE_GROUP** or **$valueInDb === (string) Share::SHARE_TYPE_GROUP**  then. Having multiple possible types for this seems very brittle, it should either be a string or an int. Just using == actually does not solve this problem.

**Pull request merged**
