### PR TITLE
[stable9] Hide revert button when no permission to revert

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/25288 to stable9

Please review  @georgehrke @VicDeo @DeepDiver1975 @owncloud/filesystem

### CODE REVIEW

**Comment by PVince81** [comment]
I have retested this manually and it still works.

**Comment by PVince81** [comment]
@VicDeo I can't reproduce your issue.

I tried the following on this branch with and without encryption and it worked fine:

1. Login as admin
1. Create a user "user1"
1. Create a folder "test"
1. Create a file "test/test.txt"
1. Edit the file several times to create versions
1. Share "test" with "user1"
1. Login as "user1"
1. Open the versions panel for "test/test.txt"
1. Rollback to an older version

@VicDeo please provide detailed steps and compare with stable9. Maybe you found another bug that is not related to this PR.

**Comment by VicDeo** [comment]
@PVince81 the only difference is 
step 0. Install clean 9.0.3 and do not change any settings before trying steps 1-9

And It ends up with 500 (Internal Server Error)

**Comment by PVince81** [comment]
@VicDeo can't reproduce your issue. Maybe you have other apps enabled that cause side effects ? I only have core + files_texteditor. Or maybe a slightly different config.

**Comment by VicDeo** [comment]
@PVince81 I downloaded OC 9.0.3 with all default enabled  apps yesterday. So no.
> Install clean 9.0.3 and do not change any setting

**Comment by PVince81** [comment]
@VicDeo ah, so did you patch the tarball with this PR then ? Will try that

**Comment by PVince81** [comment]
@VicDeo also works for me:

1. Download 9.0.3 tarball
1. Set it up (mysql)
1. Patch it
1. Go with steps from https://github.com/owncloud/core/pull/25327#issuecomment-230700792

Reverting a version as recipient still works.

**Comment by PVince81** [comment]
@VicDeo `apps/files_versions/lib/storage.php on line 342`

After patching the line 342 is empty, so you probably didn't patch at all and testing on plain 9.0.3.
This also worked for me.

**Comment by PVince81** [comment]
@VicDeo please note that to test this you need to keep the share but remove the "can edit" permission.
Maybe you deleted the file or removed the share completely ?

**Comment by PVince81** [comment]
Anyone else having this issue ?

@jvillafanez

**Comment by jvillafanez** [comment]
Patch works for me. If the recipient doesn't have permissions, the rollback icon isn't there; if he has permissions, he can rollback without any apparent issue.

**Comment by PVince81** [comment]
@jvillafanez actually you should also test by having the browser open for the receipient, open in the versions tab so you see the buttons. Then change the perms in another tab. Then use the existing view to click rollback (no page refresh else the button disappears).

**Pull request merged**
