### PR TITLE
[WIP] Separate storage and quota

### PR DESCRIPTION
**Pull request by pellaeon**
Should solve https://github.com/owncloud/core/issues/5475

### CODE REVIEW

**Comment by pellaeon** [comment]
@PVince81 Is there any new design decisions made? Is this PR still valid?

**Comment by PVince81** [comment]
There are no new design decisions.

But one thing regarding the files UI will be done, it will be using WebDAV instead of ajax calls: #12353 
This means free space and all will be read from the WebDAV response instead.

**Comment by pellaeon** [comment]
I re-tested the current behavior.
"Available space" shown to the user will be the smaller of these two:
1. actual available space on disk
2. the user's quota

Since [you don't want to change the current implementation](https://github.com/owncloud/core/issues/5475#issuecomment-47638564), I think this PR can be closed, and #5475 can be solved by displaying a "disk low" warning message to admin, what do you think?

**Comment by PVince81** [comment]
A disk low warning might be enough, yes.

**Pull request closed without merging**
