### PR TITLE
Revert route breaking changes

### PR DESCRIPTION
**Pull request by nickvergessen**
Reverting #17961 and #18109 

The changes caused more damage and troubles then it helped: #18200 

So we revert this for now until a new fix is there that does not break everything

@DeepDiver1975 @LukasReschke @MorrisJobke @Xenopathic 

Has anything been backported already?

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
as discussed - THX :+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by Xenopathic** [comment]
So, TODO:

- Make the Router more robust, so it doesn't try loading app routes before apps are loaded
- Re-introduce knowledge base URL configuration parameter

**Comment by nickvergessen** [comment]
+
* Make sure OCS API routes also work

**Pull request merged**
