### PR TITLE
Prefer basic auth over session auth in ocs

### PR DESCRIPTION
**Pull request by icewind1991**
When both basic auth and a session is available dont error out

cc @DeepDiver1975 @LukasReschke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
fixes which issue?

unless there is a good explanation this is a topic for 9.0 - we shall not break auth again right before the freeze

**Comment by karlitschek** [comment]
I agree with @DeepDiver1975 What is the issue. My gut-feeling says that we should do it exactly as we do with WebDAV where session has the priority over basic auth.

**Comment by PVince81** [comment]
@icewind1991 https://github.com/owncloud/core/pull/19044#issuecomment-140372043

**Comment by MorrisJobke** [comment]
@icewind1991 Please answer the question or I will close this ticket soon ;)

**Comment by icewind1991** [comment]
I'm fine with closing this

**Pull request closed without merging**
