### PR TITLE
Remove encryption from unignored gitignore list

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #29002

### CODE REVIEW

**Comment by phil-davis** [comment]
@PVince81 your decision about when you want to merge this backport.
It does stop annoying dev git behavior when switching around branches when also having ``apps/encryption``

**Comment by PVince81** [comment]
@phil-davis encryption is still bundled with stable10

**Comment by phil-davis** [comment]
Indeed it is - better not backport then!

**Comment by PVince81** [comment]
adding to gitignore likely means that any changes we make in the apps/encryption folder will not be added by `git add` and would require `git add -f`, that's not good.

**Comment by phil-davis** [comment]
Yes, I agree. When branched off core ``stable10`` for some work on an "old" encryption issue, we want edits to encryption files to get added-committed to core.

**Pull request closed without merging**
