### PR TITLE
Added part files for when writing chunks

### PR DESCRIPTION
**Pull request by PVince81**
Whenever a chunk is being written, it is now written to a part file
first. This is to avoid a concurrent chunk upload to believe that the
former chunk already exists, even though it's not fully written.

This makes sure that the final file assembly is only done when all
chunks were successfully written.

Also added an extra unique id to chunk parts in case the same chunk is uploaded twice concurrently.

@DeepDiver1975 as discussed

@dragotin @guruz @ogoffart please disable the "send last chunk alone instead of in parallel" workaround in the client and test this

### CODE REVIEW

**Comment by PVince81** [comment]
also CC @icewind1991 @schiesbn @karlitschek

**Comment by PVince81** [comment]
I tested this by creating 10x120MB files in my local folder and let the sync client upload them all.
While the upload was in progress I observed the "cache" directory of the user and could see the chunks (and chunks.xxx.part) being created.

The md5 of the files after redownload was the same.

Tested with the master version of the desktop client, but I suspect that it has the workaround in place. So would be curious to see it working without it.

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Please review

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
