### PR TITLE
Replace tipsy with tooltip

### LINKED ISSUE #18069: Replace tipsy with tooltip calls
"Deprecation warning: tipsy is deprecated. Use tooltip instead"

Replace all usage of `$(...).tipsy()` with `$(...).tooltip()` in the Javascript code.

### PR DESCRIPTION
**Pull request by Henni**
fixes #18069

TODO (for now):
**core/js/js.js**
- [x] `$('.displayName .action').tipsy({gravity:'se', live:true});`
- [x] `$('.password .action').tipsy({gravity:'se', live:true});`
- [x] `$('#upload').tipsy({gravity:'w'});`
- [x] `$('.selectedActions a').tipsy({gravity:'s', live:true});`
- [x] `$('a.action.delete').tipsy({gravity:'e', live:true});`
- [x] `$('a.action').tipsy({gravity:'s', live:true});`
- [x] `$('td.lastLogin').tipsy({gravity:'s', html:true});`
- [x] `$('input').tipsy({gravity:'w'});`
- [x] `$('.extra-data').tipsy({gravity:'w', live:true});`

more can be found [here](https://github.com/owncloud/core/search?l=javascript&q=tipsy%28&utf8=%E2%9C%93)

### CODE REVIEW

**Comment by karlitschek** [comment]
@jancborchardt FYI

**Comment by jancborchardt** [comment]
Please review too @PVince81 @MorrisJobke @oparoz cause it solves an issue you were active in.

**Comment by oparoz** [comment]
I think it's not ready to review yet ;)

**Comment by Henni** [comment]
I need some help with this:

* The tooltips for `$('.selectedActions a')` and `$('a.action')` never contained any content for me, so I wasn't able to test them. Maybe someone else can take a look and find a scenario where these elements actually contain a title.
* I don't know what the tipsy on `$('td.lastLogin')` is used for. It references the last login entries in the user settings, but I have no idea what it should show.
* tipsys on `$('input')`!? Why do we apply tipsys to **all** inputs?!
* I didn't find any elements matching `$('.extra-data')`

**Comment by MorrisJobke** [comment]
> I don't know what the tipsy on $('td.lastLogin') is used for. It references the last login entries in the user settings, but I have no idea what it should show.

Go to user management -> open settings (left bottom) -> "Show last login" -> column with last login is shown.

**Comment by jancborchardt** [comment]
> * The tooltips for `$('.selectedActions a')` and `$('a.action')` never contained any content for me, so I wasn't able to test them. Maybe someone else can take a look and find a scenario where these elements actually contain a title.

This actually does not seem needed anymore since the selectedActions (multiselect delete and download) have the text directly next to them.

> * I don't know what the tipsy on `$('td.lastLogin')` is used for. It references the last login entries in the user settings, but I have no idea what it should show.

What @MorrisJobke said, and it should show the detailed time (just like for Files modified date).

> * tipsys on `$('input')`!? Why do we apply tipsys to **all** inputs?!

If it’s a performance hit we shouldn’t do it. As far as I know we mainly do that for the LDAP wizard cc @blizzz – maybe we should do it only in a dedicated way on the fields which need it.

> * I didn't find any elements matching `$('.extra-data')`

No idea about that. @PVince81 @MorrisJobke?

**Comment by Henni** [comment]
Thanks @jancborchardt and @MorrisJobke

**Comment by MorrisJobke** [comment]
> I didn't find any elements matching $('.extra-data')

https://github.com/owncloud/core/blob/master/apps/files/js/filelist.js#L792
https://github.com/owncloud/core/blob/master/core/css/styles.css#L949-L951

@jancborchardt @PVince81 ^

**Comment by Henni** [comment]
I removed the tooltips for `$('input')` because I think the selector should be more specific.

@jancborchardt Should I also remove `$('.selectedActions a')` and `$('a.action')`?

**Comment by jancborchardt** [comment]
> I removed the tooltips for `$('input')` because I think the selector should be more specific.

Ok, @blizzz then you need to fix this with custom calls for the fields in the LDAP wizard. Also @MorrisJobke I think this is used in the password strength indicator. Anywhere else?

> @jancborchardt Should I also remove `$('.selectedActions a')` and `$('a.action')`?

@Henni `.selectedActions a` yes. `a.action` I’m not sure because while we get rid of it moving the actions like rename and delete to the bubble menu, it’s probably still used by lots of other apps (Calendar and Contacts I guess).

**Comment by Henni** [comment]
@jancborchardt I moved the call for $('a.action') to the files app in 2817fedf3186c83458dc14c3d18b18dc7cb4a399.
I'll have to move it back to core to apply for other apps as well. Is there any better place than `core/js/js.js`?

**Comment by jancborchardt** [comment]
@Henni not sure – @PVince81 what’s a good place? ^

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by blizzz** [comment]
> Ok, @blizzz then you need to fix this with custom calls for the fields in the LDAP wizard.

Done!

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Jenkins: #18186

**Comment by MorrisJobke** [comment]
Jenkins is happy: https://github.com/owncloud/core/pull/18186#issuecomment-129643510

**Comment by MorrisJobke** [comment]
Maybe we merge this now and address all the other cases in a separate PR? Otherwise this will get stuck maybe.

**Comment by Henni** [comment]
If it's ok to break the tooltips for other apps (like the share button of the calendar app) we can merge this. I would fix this in a new PR then.

**Comment by oparoz** [comment]
@Henni - You mean because of this?

> I removed the tooltips for $('input') because I think the selector should be more specific.

**Comment by Henni** [comment]
@oparoz no. because of this:
> @jancborchardt I moved the call for $('a.action') to the files app in 2817fed.
> I'll have to move it back to core to apply for other apps as well. Is there any better place than core/js/js.js?

**Comment by Henni** [comment]
@oparoz I'm happy with removing `$('input')`. If this breaks anything this should be patched in the affected apps.

**Comment by PVince81** [comment]
Fine by me :+1: 
If issues pop up, please fix separately.

**Comment by Henni** [comment]
I'll squash the commits to prepare the merge.

**Comment by MorrisJobke** [comment]
@Henni I rebased your PR.

@PVince81 Can you have a look at the action entry render stuff. There was a merge conflict, but I can't find any troubles so far and everything works for me.

:+1: from my side for this.

**Comment by MorrisJobke** [comment]
Jenkins PR #18246

**Comment by MorrisJobke** [comment]
Jenkins is happy: https://github.com/owncloud/core/pull/18246#issuecomment-130474836

**Comment by jancborchardt** [comment]
Merging so we can move forward with fixing it in other apps. :)

**Comment by blizzz** [comment]
@Henni Looks like my commit https://github.com/owncloud/core/commit/e324e908f7281235773b7ac3b8ae00b9e80b1323 got lost?

**Comment by PVince81** [comment]
Looks like the tipsy disappeared completely from the LDAP wizard: https://github.com/owncloud/core/issues/19684

**Pull request merged**
