### PR TITLE
Remove Server Hostname from Capabilities (WebDav)

### PR DESCRIPTION
**Pull request by mmattel**
## Description
See referenced merged PR
Many thanks to @individual-it 
When capabilities are called, the servers hostname should not be included
@DeepDiver1975 I was just working on the referenced PR while you merged it :smile: 

## Related Issue
Followup to https://github.com/owncloud/core/pull/28513

## Motivation and Context
Security

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I was just working on the referenced PR while you merged it 😄

funny - again - sorry

next time please set the label from 'to review' back to 'developing' - this will be a hint to not merge ;-)
 THX

**Comment by mmattel** [comment]
Will do,
it was a note from @individual-it regarding the parameters at another place which made me thinking about this. Now this one should be the last one for that topic :smile:

**Comment by mmattel** [comment]
@DeepDiver1975 
might take a look and merge?

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@mmattel if the original change was backported to stable10 please backport this one too

**Pull request merged**
