### PR TITLE
feat: previews are physically deleted from disk and db in an async ma…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…nner

## ToDos
- [x] background job for automation
- [x] occ command for cron on bigger installations
- [x] define occ command printout
- [x] add tests for cleanup procedure
- [x] implement cleanup logic for objectstore - requires different sql queries
- [ ] invalidate previews if a file is upldated
- [x] kills gallery because of https://github.com/owncloud/gallery/blob/0d980ea3fd7858f27e9096c9f2c0c71e1fb160ed/preview/preview.php#L105 :vomiting_face: :vomiting_face: :vomiting_face: :vomiting_face: :vomiting_face: 

## Description
All preview hooks are gone now. Previews are cleaned up on disk and db in a background job (alternative occ command)

## Related Issue
- Fixes https://github.com/owncloud/enterprise/issues/5164

### Scenario I
- disable trashbin
- upload file which can have previews (e.g. image)
- wait for the preview to be generated
- note the fileid (e.g.query filecache)
- look up the thumbnails for this file (data/$user/thumbnails/$fileid)
- delete the file
- make sure the thumbnail is still there
- run occ p:c --all
- make sure thumbnail got removed from disk and failcache

### Scenario II
- same as Scenario II - but with trashbin enabled
- file needs to be deleted from trashbin

### Scenario III
- create new test file
- enter some text via texteditor
- see the text on the preview
- edit the file again aka change the contents
- make sure the preview holds the new file contents

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiWebdavPreviews-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/35434/95

**Comment by DeepDiver1975** [comment]
:cry: 

```
1) Test\PreviewCleanupTest::test

Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'select `name`, `user_id` from `oc_filecache` `fc`

		join `oc_mounts` on `storage` = `storage_id`

		where `parent` in (select `fileid` from `oc_filecache` where `storage` in (select `numeric_id` from `oc_storages` where `id` like 'home::%') and `path` = 'thumbnails')

		  and not exists(select `fileid` from `oc_filecache` where CAST(`fc`.`name` as INT) = `oc_filecache`.`fileid`)

		  order by `user_id` limit 1000':


SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INT) = `oc_filecache`.`fileid`)

		  order by `user_id` limit 1000' at line 4


/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:182

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:159

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:2226

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1313

/drone/src/lib/private/DB/Connection.php:191

/drone/src/core/Command/Previews/Cleanup.php:83

/drone/src/core/Command/Previews/Cleanup.php:59

/drone/src/tests/lib/PreviewCleanupTest.php:98

**Comment by cdamken** [comment]
Is this patch not needed?

https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/39988.patch

@butonic provided that too

**Comment by DeepDiver1975** [comment]
> Is this patch not needed?

I'd say this one is also needed as far as I can tell

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/pull/40045

**Pull request closed without merging**
