### PR TITLE
[stable10] webUI test to check decrypt on user specific keys

### PR DESCRIPTION
**Pull request by paurakhsharma**
Backport of: https://github.com/owncloud/encryption/pull/65
~~This PR is in top of~~ #33321

### CODE REVIEW

**Comment by phil-davis** [comment]
@paurakhsharma this is ready to rebase and resolve conflicts

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
