### PR TITLE
[stable8] fix filepicker

### LINKED ISSUE #11563: Missing $_GET[mimetypes] Parameter in apps/files/ajax/list.php
Hi, I work with the oc-dialogs to search for pics in the cloud, but can't filter only for images!
So i take a look in the apps/files/ajax/list.php, and here is the parameter $_GET['mimetypes] missing, but needed in this js call

core/js/oc-dialogs.js
```
_getFileList: function(dir, mimeType) {
		if (typeof(mimeType) === "string") {
			mimeType = [mimeType];
		}

		return $.getJSON(
			OC.filePath('files', 'ajax', 'list.php'),
			{
				dir: dir,
				mimetypes: JSON.stringify(mimeType)
			}
		);
	},
```
And the 2. problem if you filter for images the folders/ subfolders not shown so it make sense to work with the mimetype filter for more filtering possibilities (array needed instead of string), like filter for: image/jpeg' and 'httpd/unix-directory'! Now the oc-dialogs filepicker works as expected.
We have to perform the lib/private/files/view.php
method: getDirectoryContent($directory, $mimetype_filter = '');
like:
```
public function getDirectoryContent($directory, $mimetype_filter = '') {
...
if ($mimetype_filter) {
				if(is_array($mimetype_filter)){
					
					foreach ($files as $file) {
						foreach($mimetype_filter as $filter){
							 if (strpos($filter, '/')){
							 	  if ($file['mimetype'] === $filter) {
										$result[] = $file;
									}
							 }else{
							 	if ($file['mimetype'] === $filter) {
									$result[] = $file;
								}
							 }
						}
					
				}
				}else{
					
				foreach ($files as $file) {
					if (strpos($mimetype_filter, '/')) {
						if ($file['mimetype'] === $mimetype_filter) {
							$result[] = $file;
						}
					} else {
						if ($file['mimepart'] === $mimetype_filter) {
							$result[] = $file;
						}
					}
				}
			}
			} else {
				$result = $files;
			}
```

as example on the js side
```
var mimeparts=['image/jpeg','httpd/unix-directory'];
OC.dialogs.filepicker(t('app', 'app title', callbackfunc, false, mimeparts, true);
```

And now all works es expected!

### LINKED ISSUE #15526: Filtering for mimetypes in filepicker dialog does not work
So what I did was:

```js
OC.dialogs.filepicker(
	t('files_drop', 'Choose the folder to store files uploaded with File Drop'),
    OCA.Files_Drop.savePath,
    false,
    'httpd/unix-directory',
    true
);
```

Which fires a request to `/index.php/apps/files/ajax/list.php?dir=&mimetypes=%5B%22httpd%2Funix-directory%22%5D`, so the JS part is completely fine, but let's take a look at the endpoint: https://github.com/owncloud/core/blob/43b503641c9f3cc705f4a5c318c4122d00f8940a/apps/files/ajax/list.php

There is simply no filter at all for the mimetype, the whole parameter is unused :see_no_evil:

This is caused by the fact that in previous ownCloud versions, such as ownCloud 6, `rawlist.php` was called which indeed had a mimetype filter: https://github.com/owncloud/core/blob/231bc00a501f1ab9cea67b4d9fa6a87f1a1a7c30/apps/files/ajax/rawlist.php#L12-L17

From my PoV this is a regression introduced with https://github.com/owncloud/core/pull/6968's https://github.com/owncloud/core/commit/0be9de5df558232e12e2f582af5d08e1f488ba90, so ~~since Oct. 28 2013~~ Apr 4, 2014 broken and nobody really cared :see_no_evil:

<hr/>
X-Post from https://github.com/owncloud/files_drop/issues/40#issuecomment-91480081

### PR DESCRIPTION
**Pull request by MorrisJobke**
- add ability to filter for mimetype
- fixes #15526
- fixes #11563 

Backport of #15566 

cc @libasys @PVince81 @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
without this being merged 8.0.3 will not properly work with the app files_drop @karlitschek @MTRichards @LukasReschke

**Comment by PVince81** [comment]
Tested with avatar selection, which correctly filters by image and shows subfolders :+1: 
I also tested on stable8 and saw that results were not filtered.

**Comment by MorrisJobke** [comment]
@DeepDiver1975 So merge this into 8.0.3?

**Comment by LukasReschke** [comment]
> without this being merged 8.0.3 will not properly work with the app files_drop @karlitschek @MTRichards @LukasReschke

Well… The app actually works fine… Just has the same issue like the avatar picker: You can also select non-valid mimetypes ;-)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 So merge this into 8.0.3?

no my call @karlitschek @MTRichards

**Comment by MTRichards** [comment]
If we are beyond feature freeze, we should delay for 8.0.4 and accept that the folder picker will have files in it. I don't see a better answer, because this could affect other things...right?
@karlitschek

**Comment by karlitschek** [comment]
I agree with @MTRichards

**Comment by LukasReschke** [comment]
Works. Let's ship it then for the next release :+1:

**Comment by SergioBertolinSG** [comment]
Tested in stable8, works fine in general but there is a problem with some filetypes (same happens in files view):
BMP files are not shown https://github.com/owncloud/core/issues/16461 and
TIFF files are not shown https://github.com/owncloud/gallery/issues/166

**Comment by rperezb** [comment]
@carlaschroder perhaps this would be worthy to be documented
BMP and TIFF images not supported

**Comment by oparoz** [comment]
@rperezb - BMP and TIFF are supported, but the Files app can't show thumbnails of some BMPs for some reason and Pictures has been superseded by [Gallery](https://github.com/owncloud/galleryplus)

**Pull request merged**
