### PR TITLE
Fix for issue #20050

### LINKED ISSUE #20050: WebInterface - Shared link page text of link too small
In teh webinterface of an shared link the display of the Link is too small:

http://i.imgur.com/416krNx.png

The field thoud have a much bigger size. Should be possible to have teh filed longer depending on teh available size

### PR DESCRIPTION
**Pull request by kavishdahekar**
Minor change in width of input box.

fixes #20050

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Thanks @kavishdahekar - welcome to the show!

**Comment by kavishdahekar** [comment]
@DeepDiver1975 can you please help me with this? Why would the Jenkins build fail for this? I am unable to check the details as the [page](https://ci.owncloud.org/job/ownCloud/job/core/job/PR-25735/1/) times out.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 can you please help me with this? Why would the Jenkins build fail for this? I am unable to check the details as the page times out.

no need to worry about jenkins - your changes are pure css - there is no need to have Jenkins running at all.

:+1:

**Comment by butonic** [comment]
yup ... jenkins just choked on mysql:
```
Test\ServerTest::testQuery with data set #27 ('DateTimeZone', '\OC\DateTimeZone')
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] FATAL:  sorry, too many clients already
FATAL:  sorry, too many clients already
```
👍

**Comment by DeepDiver1975** [comment]
Not really an issue. We shall replace all these Link holding input fields with copy to clipboard buttons.

**Comment by jancborchardt** [comment]
@DeepDiver1975  exactly for that reason the width doesn’t matter and should look nice visually. Now it’s way too wide.

**Pull request merged**
