### PR TITLE
Update php parser

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
php-parser required an update to understand php 7+ syntax

## How Has This Been Tested?
- locally by calling make test-php-style

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
you mean running `make test-php` not `make test-php-style`. the style checker worked fine before this

**Comment by DeepDiver1975** [comment]
> you mean running make test-php not make test-php-style. the style checker worked fine before this

I added the ocp checker to the make target https://github.com/owncloud/core/pull/31926/files#diff-b67911656ef5d18c4ae36cb6741b7965R195

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
uh oh...

```
1) Test\Command\AsyncBusTest::testClosureSelf
Error: Cannot access self:: when no class scope is active

/drone/src/lib/private/Command/ClosureJob.php:32
/drone/src/lib/private/BackgroundJob/Job.php:57
/drone/src/lib/private/BackgroundJob/QueuedJob.php:42
/drone/src/tests/lib/Command/AsyncBusTest.php:174
/drone/src/tests/lib/Command/AsyncBusTest.php:134
```

**Comment by DeepDiver1975** [comment]
> uh oh...
> 
> 1) Test\Command\AsyncBusTest::testClosureSelf
> Error: Cannot access self:: when no class scope is active

upstream issue: https://github.com/jeremeamia/super_closure/issues/74

tests have been adopted - issue is not hitting us ...

**Comment by patrickjahns** [comment]
To be honest - I'd rather get rid of the OCP checker and provide this as extension for phan/phpstan/psalm

**Comment by DeepDiver1975** [comment]
Agreed. Let me know once the Extension is ready and we kill this script

**Comment by PVince81** [comment]
raised https://github.com/owncloud/core/issues/31929 to address this later

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
Segfault now at the end of PHPUnit https://drone.owncloud.com/owncloud/core/8278/140.

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by DeepDiver1975** [comment]
fixes the missing since tag: https://github.com/owncloud/core/pull/31942

**Comment by phil-davis** [comment]
I rebased to make CI  run again. But still:
https://drone.owncloud.com/owncloud/core/8347/140
```
OK, but incomplete, skipped, or risky tests!
Tests: 9801, Assertions: 43569, Skipped: 83.
./tests/drone/test-phpunit.sh: line 58: 13 Segmentation fault (core dumped) $phpunit_cmd --configuration tests/phpunit-autotest.xml ${GROUP} --coverage-clover tests/output/coverage/autotest-clover-"${DB_TYPE}".xml
```

how does this change cause a segfault of phpunit, and only for 1 sqlite drone job?

**Comment by phil-davis** [comment]
At the moment in master, unit tests fail when I do something like:
```
make test-php NOCOVERAGE=true TEST_DATABASE=mysql TEST_PHP_SUITE=tests/lib/Share/ShareTest.php
```
It bombs with:
```
PHPUNIT="/home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/phpunit" build/autotest.sh mysql tests/lib/Share/ShareTest.php
Using PHP executable /usr/bin/php
Parsing all files in lib/public for the presence of @since or @deprecated on each method...

PHP Fatal error:  Uncaught PhpParser\Error: Syntax error, unexpected T_CONST, expecting T_FUNCTION on line 31 in /home/phil/git/owncloud/core/lib/composer/nikic/php-parser/lib/PhpParser/ParserAbstract.php:275
Stack trace:
#0 /home/phil/git/owncloud/core/build/OCPSinceChecker.php(140): PhpParser\ParserAbstract->parse('<?php\n/**\n * @a...')
#1 {main}
  thrown in /home/phil/git/owncloud/core/lib/composer/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 275
Makefile:166: recipe for target 'test-php' failed
make: *** [test-php] Error 255
```
That (unfortunately) does not report the file it is parsing. Turns out it is parsing ``lib/public/Shutdown/IShutdownManager.php`` and line 31 is:
```
public const HIGH = 10;
```
which, I guess, is newer syntax that the older version of the parser does not understand.

My questions is:

Why does CI pass in master, but running locally fails?

Hmmm - I see that ``build/autotest.sh``  has:
```
$PHP build/OCPSinceChecker.php
```
I can comment that out locally to avoid this issue, and the unit tests get to run.

**Comment by DeepDiver1975** [comment]
> which, I guess, is newer syntax that the older version of the parser does not understand.
> 
> My questions is:
> 
> Why does CI pass in master, but running locally fails?

this is the reason for this PR - the php parser needs an update to uderstand php 7.1+ syntax
in addition this PR adds the ocp checker to drone

**Comment by phil-davis** [comment]
> in addition this PR adds the ocp checker to drone

OK, now I see. drone is not running through that ``autotest.sh`` script - thus avoiding the problem.

**Comment by DeepDiver1975** [comment]
no idea how to address the seg fault - @patrickjahns @crrodriguez

**Comment by DeepDiver1975** [comment]
maybe we need to update the php container to run php 7.2.7 - the changelog is talking about a fix for seg fault - http://php.net/ChangeLog-7.php#7.2.7

**Comment by patrickjahns** [comment]
I am working to integrate xdebug in the containers - once merged it will built them with the latest version in each branch. That will provide us with feedback if php 7.2.7 would solve the issue

**Comment by crrodriguez** [comment]
@DeepDiver1975 no problem if you want me to investigate a PHP crash.. however I need an specific reproducer as an starting point, something that will crash either instantly or if it is a heisenbug something that crashes according to the phase of the moon.

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by crrodriguez** [comment]
@DeepDiver1975 So..what's going on here..the memcached extension is not loaded yet it still crashes at shutdown..  it is some other extension that is crashing ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 So..what's going on here..the memcached extension is not loaded yet it still crashes at shutdown.. it is some other extension that is crashing ?

No idea - using the env variable as you proposed finally made it work - I'm fine with that ;-)

**Comment by phil-davis** [comment]
And even better, I can run ``make test-php`` locally without having to work-around stuff.

**Pull request merged**
