### PR TITLE
Delete button now showing at lesser screen-widths than 768px

### PR DESCRIPTION
**Pull request by noveens**
## Description

Delete button now showing at lesser screen-widths than 768px at the "deleted files" page

## Related Issue

https://github.com/owncloud/core/issues/21421

## How Has This Been Tested?

I have tested it at resolutions lesser than 768px.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by noveens** [comment]
@PVince81 ,
can you have a look?

**Comment by felixheidecke** [comment]
Who knows, what the original purpose was? I don't see why this was removed in the first place.

**Comment by noveens** [comment]
@felixheidecke ,
Thumbs up? :P

**Review by lordelix — APPROVED** [review]
👍

**Pull request merged**
