### PR TITLE
Adding support to exclude files or directories from versioning based a pattern matching per user.

### PR DESCRIPTION
**Pull request by mnefedov**
The config.php should contain:

'files_versions_excludes' =>
    array(
       'ownclouduser' => array( '/picasa-db/_', '/install/_'),
    ),

The key for the 'files_version_excludes' are the user names.
The value is an array of fnmatch() type of pattern strings.
An INFO message is generated when a match is detected and the file is not going to be versioned.

In the ideal world -- this should be done per user and through the WEB UI. 
Unfortunately this is not something I could learn in a short period of time.

### CODE REVIEW

**Comment by schiesbn** [comment]
Thanks for the pull request! I think it can be useful to exclude certain files from versions. But I'm not sure if we should do this on a per-user basis. Per-User settings should be controllable by the users in the personal settings. Config.php should contain system wide settings only. Maybe it would make more sense to have a config.php setting based on file types, e.g. exclude all "*.mp4" files because you don't want to create version for the users large video collections or something like "exclude files larger then XMB"?

Would this work for the use-case you want to solve too?

Otherwise we maybe really need a per-user setting in the personal page, where the user can exclude special files/folders. This would also lead to other question, e.g. what to do if the file/folder gets renamed? Should we update the settings in this case as well or not? Probably we should update it in this case. 

@jancborchardt @MTRichards  what do you think about the general idea and what kind of solution would you prefer?

**Comment by mnefedov** [comment]
@schiesbn 

I absolutely agree with your assessment -- it should be done on the per user basis. I feel that the system wide setting is not needed if the 'per-user' way is supported correctly. I used config.php because it was the fastest way to implement a feature, but obviously it is not a proper one.

I am not in a position to tell *how* it should be done, I don't have the knowledge, but I would like to tell where and what should be done:

-- in the WEB UI on per-user basis to select a folder and make it "un-versioned"
-- in the WEB UI on per-user basis to have a "version" list of patterns to exclude from versioning.

I like you suggestion about the size. I was solving the /picasa-db/*. Picasa creates/update massive files >200MB and it does it often. Even the smaller ones (<40MB) are updated on a constant basis. For example the total size of the picasa-db in my case is ~380MB (~50files), the version directory contained >2GB and over 1000 files. I guess what I am trying to say is that the initial file size may not be a good measure without the "update" rate. Perhaps if the update rate and the size exceed some amount of bytes --> start "expiring" these files immediately? or maybe simply set the maximum number of versions per file?

**Comment by MTRichards** [comment]
Granularity of control on what apps are configured to do what, where is in general a good thing. We need to think about 100.000 users though, and I agree to doing this on a per user basis becomes impossible for admins when the user counts get higher. 

We also want to protect the view from an admin - so that an admin doesn't have a view into a user's account through ownCloud. Without such a view, it is difficult for an admin to exclude directories. A pattern approach will work, but I wonder if it is necessary.

On where to put something like this, a config file not such a good idea.

This puts us back to the need for a personal page setting that excludes certain directories from versioning. App settings for users to configure things (like versioning) should be done from the app itself, and located in the personal settings / admin settings as appropriate when the app is activated. 

For an extended example consider external storage. We should be able to turn versions off for external storage on a mount basis (at some point), and sync etc. Depending on the use case, those would be handled by the external storage app when the mount point is created, AND also in the personal page if the admin decides it is important.

**Comment by jancborchardt** [comment]
Let's take a step back and see what the use-cases are here. With this change, every single user of Picasa+ownCloud still has to figure this problem out and add the exception.

Instead we should maybe directly fix special cases like that by way of some kind of ignore list, similar to how the desktop client does.

Other cases like exclusion of video or music files don't make much sense: usually they don't change. Amd if they do, you are probably a music producer/videographer and _want_ the versions to be there.

**Comment by jancborchardt** [comment]
Btw this smells very similar to the Thunderbird .eml sync issue. We probably need to understand that there are some problems we have to solve specifically instead of generally (or ignoring them / offloading them to each and every end user to figure out) if we want to be a prime sync solution. cc @karlitschek @DeepDiver1975

**Comment by mnefedov** [comment]
@jancborchardt 
I agree with your statements. An intrinsic way is  good. I think in the case of picasa databases it is relatively easy. The directory path is easy to identify: '*/Google/Picasa2/db3/*'.

One more observation for locations like picasa-db. When versioning is enabled it would be nice to have a way of "restoring" every file in the directory to a particular time point. Think 'snapshots'. It is not useful to restore just one file -- it is going to break the application, the files in the directory are interdependent.  Manually restoring each file is tedious. This may be turned into a *directory* versioning snapshot feature. In my head -- it is complicated.

**Comment by jancborchardt** [comment]
This requires some technical input on how we should move forward: @karlitschek @DeepDiver1975 @PVince81

**Comment by karlitschek** [comment]
I have concerns that this approach might not works for more then a handful of users that are manually configured in the config.php. Also not sure about if it makes sense to hard-code certain directories in config.php by the admin if the user can circumvent this be just renaming a directory. 
We really really appreciate this contribution but :-1: for now.

If you really need this functionality then please implement this as an app. Should be relatively easy to do.

**Comment by schiesbn** [comment]
I come to the conclusion  that it might make sense as a personal setting but not as a global setting because the setting is to specific to apply it to all users

**Pull request closed without merging**
