### PR TITLE
Fix group sharing for v1 caldav and carddav stable9

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of https://github.com/owncloud/core/pull/23342

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@LukasReschke @PVince81 @cmonteroluque we need this one for 9.0.1 - THX

**Comment by LukasReschke** [comment]
:+1:

**Comment by cmonteroluque** [comment]
ok,

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Fixes also #23011

**Pull request merged**
