### PR TITLE
dont go trough the view when moving to trash

### PR DESCRIPTION
**Pull request by icewind1991**
For #16237

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
also CC @schiesbn

**Comment by PVince81** [comment]
I realize this means that apps that provide hooks need to do that too. If they rely on the Node API (as it would be expected since it's public) it would also go through the view. One day we'll need to find a good solution for that.

**Comment by PVince81** [comment]
```
08:29:41 1) OCA\Files_trashbin\Tests\Storage\Storage::testDeleteVersions
08:29:41 Failed asserting that 0 matches expected 1.
08:29:41 
08:29:41 /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/apps/files_trashbin/tests/storage.php:138
08:29:41 
08:29:41 2) OCA\Files_trashbin\Tests\Storage\Storage::testSingleStorageDeleteFail
08:29:41 Failed asserting that true is false.
08:29:41 
08:29:41 /var/jenkins/workspace/pull-request-analyser-ng-simple@4/label/SLAVE/apps/files_trashbin/tests/storage.php:209
```

Tests might need updating

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
I'll review/test this soon.

**Comment by PVince81** [comment]
Need to check whether we need to manually trigger hooks there. But I guess that normally `shouldEmitHooks()` would be false or something.

**Comment by PVince81** [comment]
Looks like setUpTrash  is also called and uses the view (and triggers hooks that no one implements), but since it's operating on "files_trashbin" it might be fine to keep that.

**Comment by PVince81** [comment]
@icewind1991 please rebase

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
We will likely need this for "::restore()" too, but separately. We'll first see how it goes with locking.

**Comment by PVince81** [comment]
- [ ] BUG: breaks encryption

1. Enable encryption
1. Create a folder "delete this"
1. Create a file inside "delete this/test.txt"
1. Edit the file several times to create versions (yeah, always a good idea to test this too :wink:)
1. Delete the folder "delete this"
1. Restore the folder
1. Download "test.txt" or any of its versions => the delivered file is corrupt or cannot be downloaded

**Comment by PVince81** [comment]
CC @schiesbn for possible clues, but I would expect encryption to work even when working on storage level

**Comment by icewind1991** [comment]
`\OCA\Encryption\Crypto\Encryption::shouldEncrypt()` returns false for files_trashbin, is that intended @schiesbn ?

**Comment by SergioBertolinSG** [comment]
@icewind1991 I've just tested a PR who changes that https://github.com/owncloud/core/pull/16404

**Comment by icewind1991** [comment]
rebased, @PVince81 can you retest?

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by schiesbn** [comment]
> \OCA\Encryption\Crypto\Encryption::shouldEncrypt() returns false for files_trashbin, is that intended 

No, I fixed it today on master: https://github.com/owncloud/core/pull/16404

**Comment by PVince81** [comment]
Ok cool. I see the change is also on this branch.

**Comment by PVince81** [comment]
Nope, still not working:
```
{"reqId":"QQ5pzdrZ4ckzSpwbGC\/F","remoteAddr":"127.0.0.1","app":"no app in context","message":"Can not decrypt this file,\n\t\t\tprobably this is a shared file.\n\t\t\tPlease ask the file owner to reshare the file with you.","level":3,"time":"2015-05-18T15:48:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"QQ5pzdrZ4ckzSpwbGC\/F","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(430): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('NIFR7sKNQ4JlJhy...')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(278): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/helper.php(616): fread(Resource id #361, 8192)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(477): OC_Helper::streamCopy(Resource id #361, Resource id #365)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(450): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_versions\\\/...', 'files_trashbin\\\/...', false, false)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(470): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_versions\\\/...', 'files_trashbin\\\/...')\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(424): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_versions\\\/...', 'files_trashbin\\\/...', true, true)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(526): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_versions\\\/...', 'files_trashbin\\\/...')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(276): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files_versions\\\/...', 'files_trashbin\\\/...')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(223): OCA\\\\Files_Trashbin\\\\Trashbin::retainVersions('delete this', 'delete this', 1431964114)\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(125): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('delete this')\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(89): OCA\\\\Files_Trashbin\\\\Storage->doDelete('files\\\/delete th...', 'unlink')\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(938): OCA\\\\Files_Trashbin\\\\Storage->unlink('files\\\/delete th...')\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(573): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/\\\/delete this', Array)\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(677): OC\\\\Files\\\\View->unlink('\\\/\\\/delete this')\\n#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/delete.php(59): OC\\\\Files\\\\Filesystem::unlink('\\\/\\\/delete this')\\n#17 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#18 [internal function]: __lambda_func(Array)\\n#19 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('\\\\x00lambda_237', Array)\\n#20 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(862): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#21 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php\",\"Line\":287}","level":4,"time":"2015-05-18T15:48:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
```

This is following the steps from https://github.com/owncloud/core/pull/16322#issuecomment-102376541

**Comment by PVince81** [comment]
If the file has no versions, the deletion will work.
So this is related to the versions.

**Comment by PVince81** [comment]
This works on master. So we should fix the versions case in this PR to avoid introducing a regression there.

@icewind1991 @schiesbn can you have a look ?

**Comment by icewind1991** [comment]
@PVince81 can you retest?

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Works now. I also tested deleting shared files as recipient and restoring, that worked too.

Please add the unit test for the copyFromStorage change and this is good to go.

**Comment by icewind1991** [comment]
Added a test

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
This needs a second reviewer @schiesbn @nickvergessen @th3fallen @DeepDiver1975

**Comment by MorrisJobke** [comment]
Works :+1:

**Pull request merged**
