### PR TITLE
Fix get local file encryption master

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@PVince81 @icewind1991 @th3fallen @schiesbn please review this change - this was originally intended to fix an issue but I was able to solve it in a different way.

But to me this still is a reasonable change.

Just let me know - THX

### CODE REVIEW

**Comment by th3fallen** [comment]
seems logical here :+1:  (also doesn't explode from what i see)

**Comment by PVince81** [comment]
Makes sense :+1:

**Comment by DeepDiver1975** [comment]
let's wait for @schiesbn on this - I'd like to get his opinion on this as well

**Comment by schiesbn** [comment]
I think I don't really understand the reasons for this change. The file caching happens independent from encryption, so why do you need the check if encryption is enabled? 

At the end ```$this->storage->getLocalFile($path);``` will also try to read the path from the cache if it is cached and otherwise create a new local file. So why the extra code if encryption is enabled, which at the and does the same as a ```$this->storage->getLocalFile($path);``` would do anyway?

**Comment by DeepDiver1975** [comment]
> I think I don't really understand the reasons for this change. The file caching happens independent from encryption, so why do you need the check if encryption is enabled?

In order to get the real physical file of an encrypted file we need to decrypt and store the file temporary in the temp folder - this is what that cache call is doing. In case the file is not encrypted there is no need to cache it and the file can directly be used (as long it is from a local storage).

We basically gain performance if encryption is not enabled.

**Comment by PVince81** [comment]
Not sure, but maybe what @schiesbn means is that getLocalFile() will also do the same logic, but I haven't checked

**Comment by schiesbn** [comment]
> Not sure, but maybe what @schiesbn means is that getLocalFile() will also do the same logic, but I haven't checked

Yes, we don't have a special  getCachedFile() implementation in the stream wrapper, so we call directly LocalTempFileTrait:getCachedFile(), the same method ````$this->storage->getLocalFile($path);```` calls at the end. So I don't see the reason for the shortcut to skip the other storages in case of encryption is enabled if at the end the same method is executed to get the same result.

**Comment by DeepDiver1975** [comment]
But we only have to cache the file if encrpytion is enabled - if not there is no reason to do it.

Because the encryption storage wrapper is always enabled - we will always create copies even of local files.

**Comment by schiesbn** [comment]
Hm, now I see the idea. The assumption is that getLocalFile() returns the path to a local file which can be read (is unencrypted). But somehow it still feels wrong. getLocalFile() returns a path, not the file as such. In case of a encrypted file in the local storage it should be OK to return just the path to the file. As soon as the user will use the path to read the file we will decrypt it. What's the advantage to decrypt it in advance and store it unencrypted in the tmp folder?

Do you have any example where we use getLocalFile() and where it makes a difference?

**Comment by DeepDiver1975** [comment]
> What's the advantage to decrypt it in advance and store it unencrypted in the tmp folder?

Some tools/functions like image processing etc require direct access to a local file - this is what this function is used for.

**Comment by schiesbn** [comment]
Thanks for explaining, makes sense :+1:

**Pull request merged**
