### PR TITLE
Use setifempty to please incompatible httpd versions

### PR DESCRIPTION
**Pull request by LukasReschke**
Some httpd versions have problem with the old logic leading to resourced served with multiple headers.

@MorrisJobke Should fix your issue.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Still doesn't work:

bildschirmfoto 2015-12-16 um 10 44 46


```
$ apachectl -v
Server version: Apache/2.4.17 (Unix)
Server built:   Dec  2 2015 08:34:50
```

mod_version is loaded

**Comment by butonic** [comment]
@LukasReschke @MorrisJobke adding the "always" fixes it for me

**Comment by butonic** [comment]
pinging @oparoz for review

**Comment by MorrisJobke** [comment]
Tested and works with @butonic's change :+1:

**Comment by MorrisJobke** [comment]
Rebase to fetch the latest changes.

**Comment by MorrisJobke** [comment]
Headers of the files app:

bildschirmfoto 2016-01-08 um 11 17 11

Headers of an image:

bildschirmfoto 2016-01-08 um 11 17 51

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
