### PR TITLE
Proper details about git submodule update

### LINKED ISSUE #18801: Developer experience: Submodule installation error page
Currently looks like this:
capture du 2015-09-03 01-59-38

Instead of that we should directly already hint at the command you need to run which is `git submodule update --init`

cc @karlitschek @DeepDiver1975 @owncloud/designers

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #18801

cc @jancborchardt @karlitschek @Xenopathic

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by Xenopathic** [comment]
:+1:

**Comment by Xenopathic** [comment]
Text only change, unit tests pass (unless Jenkins is lying) -> merge

**Comment by jancborchardt** [comment]
Thank you @MorrisJobke! :) I assume a more beautiful page is not possible or necessary here?

**Comment by jancborchardt** [comment]
(I know it might sound a bit much, but never ever having an unstyled black-on-white page makes for a so much nicer developer experience.)

**Comment by karlitschek** [comment]
NO! Please don't! We are walking in circles here for years. A beautiful page would require a working ownCloud installation which we don't have here. A lot of people tried to use a template here and afterwards we realized that this broke the full check because then you get a strange internal ownCloud error because of missing 3rdparty stuff instead of the current warning. Which might not look pretty but at least it works. 
:-)

**Comment by jancborchardt** [comment]
Ok. :) I was talking more about a pure HTML page with inline styles instead of a template though.

**Comment by jospoortvliet** [comment]
1. is it worth the effort? Considering how this is only for developers and rarely happens...
2. at least if it's done be darn sure to have a lot of code comments saying "do not add any dependency on 3rdparty" because https://github.com/owncloud/core/pull/18811#issuecomment-137711816

**Comment by karlitschek** [comment]
let's keep it as it is please :-) Nothing a normal user will ever see. Just a hint for developers who don't read the documentation.

**Comment by jancborchardt** [comment]
kk ;)

**Comment by MorrisJobke** [comment]
> let's keep it as it is please :-) Nothing a normal user will ever see. Just a hint for developers who don't read the documentation.

Yep. Nothing to add here. That's enough. It should also force you to do the described steps to have a beautiful owncloud instead ;)

**Pull request merged**
