### PR TITLE
[stable8.2] Properly trigger testRemote after getting a 404 from remote fed share

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/22498 to stable8.2

Please review @nickvergessen @MorrisJobke @rullzer @schiesbn @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
Please hold the review, there seems to be an additional issue...

**Comment by PVince81** [comment]
Requires https://github.com/owncloud/core/pull/22649 to work.
Please test these two together.

**Comment by rullzer** [comment]
:+1: Tested with #22649

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
