### PR TITLE
[stable10] Remove bogus logException in DefaultTokenProvider

### PR DESCRIPTION
**Pull request by PVince81**
Some leftover from some sneaky past debugging session...

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes issue discovered in apps CI which checks for exceptions in log

**Comment by PVince81** [comment]
also pushed commit to master PR: https://github.com/owncloud/core/pull/31778

**Comment by patrickjahns** [comment]
> Fixes issue discovered in apps CI which checks for exceptions in log 

won't fix the issue for now - as the amount of stray logging information has exploded ;-)

**Review by patrickjahns — APPROVED** [review]
LGTM

**Pull request merged**
