### PR TITLE
Settings sections id should not change with i18n

### LINKED ISSUE #25527: Settings sections id should not change with i18n
This can be a problem when you to put CSS based on id

### Steps to reproduce
1. Go to admin or personal settings page
2. Look at section html code generated by a not-shipped app
3. Change language
4. Look again the html code, the id has changed (KO), as the title (OK)

### Expected behaviour
The id attribute should not change

### Actual behaviour
The id attribute if section is the same string as sectionName (displayed inside h2 title)

### Server configuration
**Operating system**:
GNU/Linux Debian sid

**Web server:**
Apache2.4

**Database:**
MariaDB

**PHP version:**
PHP 7

**ownCloud version:** (see ownCloud admin page)
9.1RC1

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Git clone

### PR DESCRIPTION
**Pull request by ppaysant**
This PR fix #25527

This split the sectionName and id string process, keeping translation active for sectionName in title but not for id.

### CODE REVIEW

**Comment by ppaysant** [comment]
Please let's this contribution be under MIT license.

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by jancborchardt** [comment]
Yeah, ID or class names should for sure not change based on language. We also don’t change the app IDs and routes like `/index.php/apps/mail`

**Comment by PVince81** [comment]
Tested, works :+1: 

@DeepDiver1975 @VicDeo @butonic second review ?

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
Regression: https://github.com/owncloud/core/issues/25925

**Pull request merged**
