### PR TITLE
export correct 48px png fallbacks for filetype icons

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @owncloud/designers @oparoz this is for IE8 compatibility. Previously I erroneously exported only 16px pngs which of course are too small.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
This seems to be still a bit off (definitely better than before):

bildschirmfoto von 2015-09-04 10-33-54

**Comment by karlitschek** [comment]
:+1: better

**Comment by oparoz** [comment]
@MorrisJobke - I think the problem you're seeing needs to be fixed in Files. IE8 must be ignoring the CSS.

**Comment by MorrisJobke** [comment]
Yep. So let this go in :+1:

**Pull request merged**
