### PR TITLE
Allow saving incomplete external storage config

### PR DESCRIPTION
**Pull request by PVince81**
This is needed for Dropbox and others that need a token.

Also fixes former unit test failures due to incomplete test config.

To test:
1) Run `./autotest.sh sqlite apps/files_external/tests/mountconfig.php` (make sure to enable "files_external" in enable_all.php to make autoloading work)
2) Test with Dropbox + GDrive

Please review @icewind1991 @MorrisJobke @Xenopathic @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/13698

**Comment by icewind1991** [comment]
Tested with dropbox, code looks good :+1:

**Comment by MorrisJobke** [comment]
It works :+1: (all files are listed and can be downloaded)

But the log got some messages, that are weird:

```
{"reqId":"b6cd85f1e3626cf68c56d646153d2eb8","remoteAddr":"::1","app":"files_external","message":"Exception: {\"Message\":\"Creating \\\\OC\\\\Files\\\\Storage\\\\Dropbox storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_external\\\/lib\\\/config.php(456): OC\\\\Files\\\\Storage\\\\Dropbox->__construct(Array)\\n#1 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, true)\\n#2 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('Dropbox', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, 'user', 'mjob', true)\\n#3 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/home\\\/mjob\\\/Proj...')\\n#4 [internal function]: __lambda_func(Array)\\n#5 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_248', Array)\\n#6 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#7 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/index.php(28): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_external\\\/lib\\\/dropbox.php\",\"Line\":50}","level":4,"time":"2015-01-27T12:57:04+00:00"}
{"reqId":"e556492f868b1b7a152c930f2cdf6080","remoteAddr":"::1","app":"core","message":"Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":3,"time":"2015-01-27T12:57:05+00:00"}
{"reqId":"40e69e868c0d42e47332a2b3d9133231","remoteAddr":"::1","app":"core","message":"Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":3,"time":"2015-01-27T12:57:07+00:00"}
{"reqId":"40e69e868c0d42e47332a2b3d9133231","remoteAddr":"::1","app":"files_external","message":"Exception: {\"Message\":\"Creating \\\\OC\\\\Files\\\\Storage\\\\Dropbox storage failed\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_external\\\/lib\\\/config.php(456): OC\\\\Files\\\\Storage\\\\Dropbox->__construct(Array)\\n#1 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_external\\\/lib\\\/config.php(433): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, true)\\n#2 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_external\\\/personal.php(29): OC_Mount_Config::getPersonalMountPoints()\\n#3 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/app.php(710): include('\\\/home\\\/mjob\\\/Proj...')\\n#4 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/settings\\\/personal.php(108): OC_App::getForms('personal')\\n#5 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/home\\\/mjob\\\/Proj...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_1556', Array)\\n#8 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/settings\\\/perso...')\\n#9 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/index.php(28): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files_external\\\/lib\\\/dropbox.php\",\"Line\":50}","level":4,"time":"2015-01-27T12:57:07+00:00"}
{"reqId":"7ed958bda858518332581a08b9d3ac0d","remoteAddr":"::1","app":"core","message":"Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":3,"time":"2015-01-27T12:57:07+00:00"}
{"reqId":"cc90cf3b991acba7ade9fbe00c2a8b5b","remoteAddr":"::1","app":"core","message":"Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":3,"time":"2015-01-27T12:57:08+00:00"}
{"reqId":"8708a6a376be328b3f9beab53744c11e","remoteAddr":"::1","app":"core","message":"Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":3,"time":"2015-01-27T12:57:08+00:00"}
{"reqId":"b9fef6cd0a766f30811a3f1cc6fd7cb8","remoteAddr":"::1","app":"core","message":"Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":3,"time":"2015-01-27T12:57:08+00:00"}
{"reqId":"c5728e1ed17d4436a44cd6d6a5aec52c","remoteAddr":"::1","app":"core","message":"Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":3,"time":"2015-01-27T12:57:09+00:00"}
{"reqId":"bb8d818431080280ad0fe92189640828","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:21+00:00"}
{"reqId":"bb8d818431080280ad0fe92189640828","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:23+00:00"}
{"reqId":"bb8d818431080280ad0fe92189640828","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:25+00:00"}
{"reqId":"bb8d818431080280ad0fe92189640828","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:27+00:00"}
{"reqId":"bb8d818431080280ad0fe92189640828","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:28+00:00"}
{"reqId":"bb8d818431080280ad0fe92189640828","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:28+00:00"}
{"reqId":"966dc340d016144cfc7b5226b9b25f14","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:33+00:00"}
{"reqId":"966dc340d016144cfc7b5226b9b25f14","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:34+00:00"}
{"reqId":"966dc340d016144cfc7b5226b9b25f14","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:36+00:00"}
{"reqId":"8a344b85d4b00f02541a7de4ca64f0eb","remoteAddr":"::1","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-01-27T12:57:45+00:00"}
```

The unauthorized errors appear while browsing - until you browsed every folder - then it stopped.

**Comment by MorrisJobke** [comment]
And of course the setup also works.

**Comment by PVince81** [comment]
@MorrisJobke do you see these on stable7 as well ?

**Comment by MorrisJobke** [comment]
@PVince81 Just the two long ones with storage failed:

```
{"reqId":"54c795050e390","app":"files_external","message":"Exception: Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795050e390","app":"files_external","message":"Exception: #1 \/home\/mjob\/Projekte\/owncloud\/core\/apps\/files_external\/lib\/config.php(538): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, true)","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795050e390","app":"files_external","message":"Exception: #2 \/home\/mjob\/Projekte\/owncloud\/core\/apps\/files_external\/ajax\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('Dropbox', '\\\\OC\\\\Files\\\\Stora...', Array, 'user', 'mjob', true)","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795050e390","app":"files_external","message":"Exception: #3 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/base.php(799): require_once('\/home\/mjob\/Proj...')","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795050e390","app":"files_external","message":"Exception: #4 [internal function]: OC::loadAppScriptFile(Array)","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795050e390","app":"files_external","message":"Exception: #5 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/private\/route\/router.php(227): call_user_func(Array, Array)","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795050e390","app":"files_external","message":"Exception: #6 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/base.php(707): OC\\Route\\Router->match('\/apps\/files_ext...')","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795050e390","app":"files_external","message":"Exception: #7 \/home\/mjob\/Projekte\/owncloud\/core\/index.php(28): OC::handleRequest()","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795050e390","app":"files_external","message":"Exception: #8 {main}","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795054112c","app":"files_external","message":"Exception: Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795054112c","app":"files_external","message":"Exception: #1 \/home\/mjob\/Projekte\/owncloud\/core\/apps\/files_external\/lib\/config.php(538): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, true)","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795054112c","app":"files_external","message":"Exception: #2 \/home\/mjob\/Projekte\/owncloud\/core\/apps\/files_external\/ajax\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('Dropbox', '\\\\OC\\\\Files\\\\Stora...', Array, 'user', 'mjob', true)","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795054112c","app":"files_external","message":"Exception: #3 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/base.php(799): require_once('\/home\/mjob\/Proj...')","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795054112c","app":"files_external","message":"Exception: #4 [internal function]: OC::loadAppScriptFile(Array)","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795054112c","app":"files_external","message":"Exception: #5 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/private\/route\/router.php(227): call_user_func(Array, Array)","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795054112c","app":"files_external","message":"Exception: #6 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/base.php(707): OC\\Route\\Router->match('\/apps\/files_ext...')","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795054112c","app":"files_external","message":"Exception: #7 \/home\/mjob\/Projekte\/owncloud\/core\/index.php(28): OC::handleRequest()","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c795054112c","app":"files_external","message":"Exception: #8 {main}","level":4,"time":"2015-01-27T13:39:17+00:00","method":"POST","url":"\/core\/index.php\/apps\/files_external\/ajax\/addMountPoint.php"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: Creating \\OC\\Files\\Storage\\Dropbox storage failed","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #1 \/home\/mjob\/Projekte\/owncloud\/core\/apps\/files_external\/lib\/config.php(434): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, true)","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #2 \/home\/mjob\/Projekte\/owncloud\/core\/apps\/files_external\/personal.php(29): OC_Mount_Config::getPersonalMountPoints()","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #3 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/private\/app.php(754): include('\/home\/mjob\/Proj...')","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #4 \/home\/mjob\/Projekte\/owncloud\/core\/settings\/personal.php(102): OC_App::getForms('personal')","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #5 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/home\/mjob\/Proj...')","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #6 [internal function]: __lambda_func(Array)","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #7 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/private\/route\/router.php(227): call_user_func('\\x00lambda_314', Array)","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #8 \/home\/mjob\/Projekte\/owncloud\/core\/lib\/base.php(707): OC\\Route\\Router->match('\/settings\/perso...')","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #9 \/home\/mjob\/Projekte\/owncloud\/core\/index.php(28): OC::handleRequest()","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
{"reqId":"54c79509ac9ce","app":"files_external","message":"Exception: #10 {main}","level":4,"time":"2015-01-27T13:39:21+00:00","method":"GET","url":"\/core\/index.php\/settings\/personal?oauth_token=uFyrlQkSVGXpdiEU&uid=382105122"}
```

**Comment by MorrisJobke** [comment]
I would say that the "unauthorized error" messages are new.

**Comment by PVince81** [comment]
They are probably because at this time the token isn't configured yet.
Or do you see these still appearing while browsing ?

**Comment by MorrisJobke** [comment]
They appear on the first browsing after the settings page shows the green dot beside the external mount I clicked on Apps -> Files and then the output started. I think we can ignore them for now. Should I open a new issue for that?

**Comment by PVince81** [comment]
Yes, thanks.

Strange, Jenkins didn't even start. Is that because the changed code is in files_external ?

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
:-1: When an incomplete storage is saved (GDrive in my case) the file list will not load, as `scan.php` keeps getting a `Call to a member function getScanner() on a non-object at lib/private/files/storage/wrapper/wrapper.php#385` error.

**Comment by PVince81** [comment]
@Xenopathic is this only on this branch or stable7 ?
Because I'm pretty sure it might happen on stable7 as well...
You are referring to a non-authenticated GDrive ?

**Comment by Xenopathic** [comment]
@PVince81 Yes, unauthenticated GDrive. Perhaps what should happen is the config adapter that returns a list of external storages to be mounted (apps/files_external/lib/config/configadapter.php) should check if the storage can be created successfully before returning it. Either there, or in the mount manager.

**Comment by Xenopathic** [comment]
:+1: Makes sense

**Comment by PVince81** [comment]
Could not reproduce on stable7, so might be a regression on master.

**Comment by PVince81** [comment]
I will merge this because at least it makes Dropbox/Gdrive work again.

I raised https://github.com/owncloud/core/issues/13715 to fix the other regression when an incomplete config is used from the file list.

**Pull request merged**
