### PR TITLE
Add a public api for apps to add mounts

### PR DESCRIPTION
**Pull request by icewind1991**
This adds a public api which apps can use to add additional mountpoints in a more structured way then listening to hooks.

First PR for #12216

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by jnfrmarks** [comment]
@LukasReschke 

Is there a write up of the api?  I assume that we need to doc and test this for 8.0.

**Comment by LukasReschke** [comment]
That's an internal API for application developers, so nothing directly exposed  to the end-user.

As far I know there is no documentation about this for developers, however there is https://github.com/owncloud/documentation/issues/693 to track this.

**Comment by jnfrmarks** [comment]
What is meant by "public"?  I thought that meant available to all, not just internal use.

**Comment by LukasReschke** [comment]
A public API refers to an API exposed to application developers. An internal API is just to be used by the core folks.

This is just a programming API, not something exposed via REST / SOAP / etc ;-)

**Comment by DeepDiver1975** [comment]
It's the public PHP API - used by application developers. And yes this means we need to document this - just like a hell of other php classes - see http://api.owncloud.org/namespaces/OCP.Files.Config.html

**Comment by LukasReschke** [comment]
Well - that's why I linked to https://github.com/owncloud/core/pull/12577#issuecomment-71192716 ;-) – But there is no need that @jnfrmarks tests this IMHO

**Comment by DeepDiver1975** [comment]
> But there is no need that @jnfrmarks tests this IMHO

indeed - nothing to take care of from an QA perspective

**Pull request merged**
