### PR TITLE
make cookies a little bit more secure

### PR DESCRIPTION
**Pull request by peterprochaska**
## Description
Added secure and httpOnly flag to setcookie and setCookie

## Related Issue
Issue: RIPS Scanning Tool Report

## Motivation and Context
Make ownCloud more secure

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
any potential risks ? old existing cookies not working any more ?

**Comment by kdslkdsaldsal** [comment]
What about webservers not running on HTTPS? Sure, you shouldn't run HTTP pages these days but setting a secure flag on a cookie transferred via HTTP will mostly break something.

**Comment by Peter-Prochaska** [comment]
@PVince81 no potential risk, but more security. Old cookies should continue to work. Except you have http cookies, they don't work anymore.
@kdslkdsaldsal Sure, it works only for https, but i have talked to @DeepDiver1975 yesterday, owncloud should be complete https only.

**Comment by kdslkdsaldsal** [comment]
> Sure, it works only for https, but i have talked to @DeepDiver1975 yesterday, owncloud should be complete https only.

Yes, sure. But the reality out there is something completely else. Thats why most other software products are only enabling the ``secure`` flag if the software is accessed via https.

**Comment by PVince81** [comment]
It also means cookies will stop working on dev envs which run http ?
Would be good to only set the flag if using https.

**Comment by Peter-Prochaska** [comment]
Ok, i will change it, after my Unittests are running on my MacBook ;-)

**Comment by PVince81** [comment]
I'm a bit afraid to merge this close to release (10.0) as it would require retesting many session related things.

If not critical, would move to 10.0.1.

**Comment by DeepDiver1975** [comment]
@Peter-Prochaska can we DRY the code a bit? THX

**Comment by PVince81** [comment]
Moving to 10.0.1

**Comment by PVince81** [comment]
> @Peter-Prochaska can we DRY the code a bit? THX

any update ?

**Comment by Peter-Prochaska** [comment]
@PVince81 We should move this to 10.0.2, because we have to test, what happens if a user has proxy or an loadbalancer, which makes the ssl termination. It should work now, but i'am not sure

**Comment by PVince81** [comment]
moving to 10.0.2 then

**Comment by butonic** [comment]
rebased to trigger jenkins

**Comment by PVince81** [comment]
rebased ⛏

**Comment by PVince81** [comment]
Please rebase for CI, and there's a conflict now

**Comment by PVince81** [comment]
moving to "planned"

needs priority and severity label @Peter-Prochaska

**Comment by PVince81** [comment]
conflicts

**Comment by PVince81** [comment]
lots of conflicts

moving to "triage"

@settermjd let me know if this needs more priority

**Comment by PVince81** [comment]
I see a lot of repeated logic, this should be rewritten using utility functions. I'm closing this

**Comment by phil-davis** [comment]
``backport-request`` label removed since it is not relevant to closed PRs.

**Pull request closed without merging**
