### PR TITLE
fix mobile scrolling, lower sidebar sensitivity, fix #11193

### LINKED ISSUE #11193: Mobile experience very flaky due to snap.js issues
I've been using the new News app release on my mobile phone the last couple of days and the snap.js experience is very flaky:

* If you scroll down with your finger, the menu shows quite often even if you dont want it. To fix this you need to swipe down from the top left to the bottom right corner to not trigger a left swipe which is kinda weird
* The flying loading icon issue, same as in https://github.com/owncloud/notes/issues/64
* The loading icon and hamburger menu overlap the navigation

All in all I think it would be best to get rid of snap.js (if none of these issues can be fixed in the next couple months) and just use the hamburger button to toggle the right menu, you dont need the menu that often and the hamburger menu is reachable pretty well at all times due to the fixed positioning.

PS: please try out the new News app release, also on your mobile and touch devices :)

@jancborchardt @MorrisJobke @jbtbnl @georgehrke @raghunayyar @PVince81 @th3fallen

### PR DESCRIPTION
**Pull request by jancborchardt**
Attempting to fix https://github.com/owncloud/core/issues/11193 by applying @zerosine’s fix from https://github.com/owncloud/core/issues/11193#issuecomment-117595417

Please test @owncloud/designers @Raydiation @zerosine @finius

If this works nicely, we should also backport it.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@tflidd @oparoz please also test this. :)

**Comment by jancborchardt** [comment]
@tflidd @oparoz @SunboX please also test this. :)

**Comment by MorrisJobke** [comment]
I got a bit less responsive, because the menu reveals instantly after the threshold is reached, which looks a bit clumsy. But now it's easier to scroll downwards.

**Comment by jancborchardt** [comment]
Maybe we need to play around with some of the other values at https://github.com/owncloud/core/blob/7df96f19227e3cf4c42f853a50b15ccecb366da7/core/vendor/snapjs/dist/latest/snap.js#L44-L61

For example resistance, flickThreshold and slideIntent.

**Comment by finius** [comment]
IMHO one can say that side scrolling shouldn't appear as long as your vertical scrolling is more intense. So the side menu should only open if you scroll more horizontal than vertical. 
It seems also that some kind of any low "refresh rate" makes scrolling that clumsy

**Comment by tflidd** [comment]
The initial bug for me was this here: https://github.com/owncloud/core/issues/14639 (menu on the right can't be opened in iOS 8/safari). But in OC 7.0.7 and OC 8.1.0 have fixed this (or iOS was fixed). Regarding the menu, it still opens with the fix.

**Comment by Bullnados** [comment]
On Opera Android looks good. :+1: 
But perhaps we should reduce the value a little bit. After testing I reduced the value from 145 to 100. With 145 the side menu opened little hard with 100 the sensivity is imo perfect.

**Comment by jancborchardt** [comment]
@Bullnados great, thanks a lot for testing! :) You are very welcome in our IRC channel #owncloud-design (on freenode) by the way!

**Comment by jancborchardt** [comment]
Rebased and applied the change @Bullnados mentioned. Please retest @owncloud/designers @Raydiation @zerosine @finius @tflidd

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by jancborchardt** [comment]
Please test again so we can merge @Bullnados @MorrisJobke @Raydiation @zerosine @finius @tflidd :)

**Comment by MorrisJobke** [comment]
Feels better now :+1:

**Comment by MorrisJobke** [comment]
@karlitschek Should we backport this?

@jancborchardt To which versions? I would say 8.1 only.

**Comment by jancborchardt** [comment]
stable8.1 and stable8 I’d say.

**Comment by karlitschek** [comment]
Let's backport. :+1:

**Comment by MorrisJobke** [comment]
stable8 #18286 
stable8.1 #18284

**Pull request merged**
