### PR TITLE
replace outdated 'shared' people icon with regular share icon as fallback

### PR DESCRIPTION
**Pull request by jancborchardt**
Since we shouldn’t use the »People« icon at all anymore I just replaced the existing one with the normal »Share« icon as fallback. In case it gets used somewhere.

Please review @owncloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
Is not really a bug but it would still be good to backport it to remove the »people« icon out of any future releases. cc @DeepDiver1975

**Comment by karlitschek** [comment]
yes please :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek Was this the backport request approval for stable7? @jancborchardt do we want this in stable7 and stable6?

**Comment by karlitschek** [comment]
backport is fine

**Comment by jancborchardt** [comment]
Backported to stable7 as bd1bf9e. I’ll not backport to stable6 as sharing still used that icon then and we didn’t have usernames displayed.

**Comment by jbtbnl** [comment]
@jancborchardt this makes https://github.com/owncloud/calendar/pull/665 obsolete?

**Comment by MorrisJobke** [comment]
@jbtbnl Not really. As icon-shared shouldn't used anymore ;)

**Pull request merged**
