### PR TITLE
[9.0] sidebar click modification

### PR DESCRIPTION
**Pull request by ErikPel**
Backport #23511
Approval https://github.com/owncloud/core/pull/23511#issuecomment-202394022

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1: 

@owncloud/designers @Henni Please review

**Comment by skjnldsv** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@skjnldsv Thanks for the review :) Feel free to review more PRs :) We always look for help in this direction :)

**Comment by skjnldsv** [comment]
@MorrisJobke Yep, I saw that, I have like 5 pr waiting in contacts :p
Will do my best though. :)

**Comment by jancborchardt** [comment]
@ErikPel this needs a rebase, then we can merge. :)

**Comment by skjnldsv** [comment]
Well, that's unfortunate! ^^
I did the exact same think yesterday! What command did you do?

**Comment by ErikPel** [comment]
@skjnldsv I messed something up and added whole bunch of unrelated commits and then thought I'd just reset the branch and then push the changes again but didn't realize it will get closed when there are no commits. I'll get another pull request up soon

**Comment by skjnldsv** [comment]
I ended up doing the same. Much more easier to reopen. Don't forget to put references to this pull.

**Pull request closed without merging**
