### PR TITLE
Add pull request template

### LINKED ISSUE #22486: Add pull_request_template.md file
Seems that it's supposed to work, see https://github.com/dear-github/dear-github/issues/125#issuecomment-185326859

So let's use this shiny new feature :smile: 

Any suggestions what to put in ?

I'd suggest something like:

```
DESCRIPTION

Fixes BUG_NUMBER

TEST CASE LIST

Please review $REVIEWERS
```

Should we add a note about the review process or checkboxes ?
For example:
- [ ] reviewed by at least two people
- [ ] contains unit tests
- [ ] passes CI

@karlitschek @jospoortvliet @LukasReschke @oparoz @jancborchardt @DeepDiver1975 @rullzer @nickvergessen @VicDeo @icewind1991 @schiesbn

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

This pull request introduces a template for pull request.
## Related Issue

fixes #22486
## Motivation and Context

Well - we should simply have a template .... 
## How Has This Been Tested?

By copy and pasting it in here and typing ...
## Screenshots (if appropriate):

:no_entry: 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by butonic** [comment]
nice! 👍

**Comment by DeepDiver1975** [comment]
@PVince81 objections?

**Comment by PVince81** [comment]
I'm fine with it, let's give it a try :+1:

**Comment by RealRancor** [comment]
Works but places like:

https://github.com/owncloud/core/blob/master/.github/CONTRIBUTING.md#short-version

needs to point to the new file location.

**Pull request merged**
