### PR TITLE
Update undelete.php

### PR DESCRIPTION
**Pull request by Originalimoc**
ownCloud 10.0.2
Prevent a warning log when undeleting all files($files unset).

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by DeepDiver1975** [comment]
backport?

**Comment by iMocW** [comment]
I'm not sure. I'm using 10.0.2 stable and manually fixed a few bugs.

PS.
It's weird I'm still facing ```
Deprecation warning: tipsy is deprecated. Use tooltip instead.
```
I may open an issue sooner.

**Comment by PVince81** [comment]
@iMocW please submit the same change to the stable10 branch, thanks

**Pull request merged**
