### PR TITLE
normalize root before setting it in FilesView

### LINKED ISSUE #21173: Owncloud Android App can't see Thumbnails of images located on some external storage in 8.2.1- 8.2.2 - 9.0.0
Steps to reproduce :

    Browse photo directories in external storage in Owncloud official app 1.9.0
        Only placeholder is shown
        Not Thumbnails in external storage on official android app - Works fine directly from web browser (Like Firefox)
        Thumbnails work fine out of the external storage on official android app
        Thumbnails work fine in external storage with Web browser

My external storage is just another local folder in the same owncloud's server

Expected behaviour : 

  There is a thumbnail.

Actual behaviour :

  Placeholder icon is shown

Operating system:

Debian Jessie (8.0)

Web server:
Apache

Database:
MySQL

PHP version:
5.6.14

ownCloud version: 8.2.1(stable) 

Owncloud log : 
`{"reqId":"qvwmBaQX\/gQVUzWPBpx5","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/Euro2008.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/Euro2008.png"}
{"reqId":"qvwmBaQX\/gQVUzWPBpx5","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/Euro2008.png"}
{"reqId":"qvwmBaQX\/gQVUzWPBpx5","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:27+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/Euro2008.png"}
{"reqId":"KxfNYjDs5j8L7qHjhX8D","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/FondEcranCroixSmartphoneSansPhoto.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/FondEcranCroixSmartphoneSansPhoto.png"}
{"reqId":"KxfNYjDs5j8L7qHjhX8D","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/FondEcranCroixSmartphoneSansPhoto.png"}
{"reqId":"KxfNYjDs5j8L7qHjhX8D","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/FondEcranCroixSmartphoneSansPhoto.png"}
{"reqId":"PfoWr48VV4NyRVJCDyhv","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/logo.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/logo.png"}
{"reqId":"PfoWr48VV4NyRVJCDyhv","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/logo.png"}
{"reqId":"PfoWr48VV4NyRVJCDyhv","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:28+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/logo.png"}
{"reqId":"CUZ+fj5crMxsSrxA6kG7","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/PtitCoeur.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:29+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/PtitCoeur.png"}
{"reqId":"CUZ+fj5crMxsSrxA6kG7","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:29+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/PtitCoeur.png"}
{"reqId":"CUZ+fj5crMxsSrxA6kG7","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:29+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/PtitCoeur.png"}
{"reqId":"C3fC8nRYyW+OxJYqPNd7","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/SmileyCoeur2.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/SmileyCoeur2.png"}
{"reqId":"C3fC8nRYyW+OxJYqPNd7","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/SmileyCoeur2.png"}
{"reqId":"C3fC8nRYyW+OxJYqPNd7","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/SmileyCoeur2.png"}
{"reqId":"0h45oTMfydQVuZWYy+32","remoteAddr":"192.168.0.254","app":"core","message":"Generating preview for \"files\/DonneesReseaux\/DessinsPerso\/WorldCup2010.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/WorldCup2010.png"}
{"reqId":"0h45oTMfydQVuZWYy+32","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/WorldCup2010.png"}
{"reqId":"0h45oTMfydQVuZWYy+32","remoteAddr":"192.168.0.254","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-12-13T21:43:30+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/448\/448\/DonneesReseaux\/DessinsPerso\/WorldCup2010.png"}`

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #21173 

please test @PVince81 @oparoz

### CODE REVIEW

**Comment by georgehrke** [comment]
also cc @tigermick @davivel

**Comment by nickvergessen** [comment]
Also @icewind1991

**Comment by oparoz** [comment]
Looking at how the tests fail I'm guessing this isn't going to be that simple :(

**Comment by PVince81** [comment]
Yeah, that is dangerous territory... especially due to the unlogical and inconsistent way how the View is used.

**Comment by georgehrke** [comment]
In my case `$root` was `/admin//` and the two slashes caused the bug.

**Comment by PVince81** [comment]
So far I'd suggest putting on gloves and only fixing the problem in the calling code only, remove the duplicate slash if needed.

**Comment by tigermick** [comment]
@PVince81 @oparoz @georgehrke it's working for me ! My problem about thumbnails in external local storage in owncloud app is solved !
Thank you very much !

**Comment by georgehrke** [comment]
I'm not sure if fixing only the external storage when using the thumbnail API is the best approach here.
The problem comes down to this function:
mountpoint php - owncloud - -development-projects-owncloud intellij idea today at 1 39 36 pm
https://github.com/owncloud/core/blob/ed7e009e056cb46b67aba8827efb5fdb3961de1c/lib/private/Files/Mount/MountPoint.php#L190L198

`$path` has too many slashes, therefore `strlen($this->mountPoint)` won't work properly.

cc @icewind1991

**Comment by PVince81** [comment]
Too bad we don't have a "comparePath" function...

**Comment by georgehrke** [comment]
What about normalizing both `$path` and `$this->mountPoint`?

**Comment by PVince81** [comment]
or use some `ltrim($path, '/')` magic before concat, if that's even possible

**Comment by icewind1991** [comment]
Would probably be sense to normalize the incoming path in `getInternalPath` iirc, the mountpoint is already normalized

**Comment by georgehrke** [comment]
okay, will try it :)

**Pull request closed without merging**
