### PR TITLE
Combine autotest-hhvm.sh with autotest.sh

### PR DESCRIPTION
**Pull request by bantu**
Partially addresses #16025

### CODE REVIEW

**Comment by nickvergessen** [comment]
Does the `./occ` call also need changing?

**Comment by bantu** [comment]
@nickvergessen It's unrelated, but probably doesn't hurt to also use the PHP executable for ./occ.

**Comment by nickvergessen** [comment]
@bantu just wanted to make sure, because in the old file it was `hhvm ./occ` :wink:

**Comment by bantu** [comment]
@nickvergessen Oh. I must have looked at the wrong just now then. In that case, it's related and needs to be changed.

**Comment by nickvergessen** [comment]
`./occ maintenance:install ` line 154 in the new code, just out of sight on the diff

**Comment by bantu** [comment]
@nickvergessen fixed.

**Comment by nickvergessen** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
