### PR TITLE
Fix warning in filecache gc

### PR DESCRIPTION
**Pull request by icewind1991**
cc @PVince81 @LukasReschke

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks, the warning is gone :+1:

**Comment by LukasReschke** [comment]
Yup. :+1:

@karlitschek @DeepDiver1975 This is a regression introduced to stable8 as well with https://github.com/owncloud/core/pull/14500#issuecomment-76174176 today. Please approve backport.

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by LukasReschke** [comment]
GRRRRRRRRRRRR

**Comment by MorrisJobke** [comment]
@owncloud-bot Retest this please :heart:

**Comment by LukasReschke** [comment]
He is my friend not yours :angry:

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please :bomb: :bomb:

**Comment by LukasReschke** [comment]
Ok. I give up.

@DeepDiver1975 How shall we proceed? – It's impossible to convince Jenkins to be more cooperative.

**Comment by karlitschek** [comment]
nice. please backport

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
