### PR TITLE
[full-ci] Get extended attributes for user for apps

### PR DESCRIPTION
**Pull request by phil-davis**
## Description

Get extended attributes for user from the apps. A
new method which emits events to get the attributes
for user, which is listened by apps to provide the
attributes for the specific user. Use case for example:
When apps are not whitelisted for guest user
they should not be visible in the personal settings.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

This is a rebase of #36258 - needs review and decision if it is wanted.

## Motivation
Do not show the apps which are not whitelisted for the guest user.

## How Has This Been Tested?
- Enable customgroups. Make sure its not listed as whitelisted apps in guest configuration.
- As guest user navigate to the settings page.
- The settings page should not show customgroups. And it does not.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliTrashbin-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36470/124

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares2-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36470/116

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliCreateLocalStorage-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36470/119

**Comment by phil-davis** [comment]
This is a rebase of #36258 

It needs someone to first decide if it is wanted, then review what it does and the technical code.

**Comment by pmaier1** [comment]
If it is ready-go, yes. Otherwise I'd not spend time here at the moment.

**Comment by phil-davis** [comment]
@jvillafanez @JanAckermann @JammingBen can someone review this. IMO it is ready - so if it looks OK on review then it can be merged.
If you review and think it needs rework, then we can leave it for now.

**Review by jvillafanez — COMMENTED** [review]
Looks good to me, but we need to update all the "since" tags

**Comment by phil-davis** [comment]
> Looks good to me, but we need to update all the "since" tags

I can do that...

**Comment by phil-davis** [comment]
> > Looks good to me, but we need to update all the "since" tags
> 
> I can do that...

done

**Review by jvillafanez — APPROVED** [review]

**Comment by phil-davis** [comment]
Note: changelog is added by PR #40277 - I forgot to add it here.

**Comment by jnweiger** [comment]
@phil-davis Ooops. I cannot confirm that your test results.
For me, the guest user always has access to custom groups. whitelisted or not.
How Has This Been Tested?How Has This Been Tested?

**Comment by phil-davis** [comment]
> Ooops. I cannot confirm your test results.

Some guest app code was never merged - see comments in https://github.com/owncloud/guests/issues/516 and PR https://github.com/owncloud/guests/pull/518

**Pull request merged**
