### PR TITLE
[admin settings] Show success message if security warnings are empty

### LINKED ISSUE #15257: remove »Security & setup warnings« section when there are no warnings
@LukasReschke as discussed, the Admin settings entry for »Security & setup warnings« should of course not show when there are none of the warnings. Including the sidebar entry.

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #15257

cc @LukasReschke @owncloud/designers @Henni Mind to review this?

### CODE REVIEW

**Comment by jancborchardt** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@nickvergessen @rullzer @Xenopathic Please review

**Comment by Xenopathic** [comment]
I'm not entirely sure if I like the section disappearing completely, it almost seems like the code is broken when that happens. However, there being an empty space is also bad. Perhaps a simple message 'No issues found, good to go!' would be better? It also avoids the jump when the section gets removed, which might be a pain if you scroll down immediately without waiting for it to finish the checks.

**Comment by karlitschek** [comment]
I think it should disappear when there are no warning. A notice that says that there are no notices is stupid ;-)

**Comment by PVince81** [comment]
It could show a special visually appealing congratulations badge to congratulate the admin for such insightful configuration.

**Comment by MorrisJobke** [comment]
Okay. Lets address following question:

* Do we want to give the admin a warm fuzzy feeling in showing a green badge stating that everything is fine and all checks have passed (and that there are even checks that can be passed)?

I for myself also like this, but I also can understand to simply remove the section, because there is nothing to do.

@owncloud/designers Opinions on this?

**Comment by MorrisJobke** [comment]
Especially @jancborchardt should answer here ;)

**Comment by jancborchardt** [comment]
Good question. We hid the section before so this is a regression fix. Introducing a confirmation like that would be a new addition hence it should be a separate thread. 

That said, a short »Everything set up correctly« with a checkmark and/or green dot seems like a nice confirmation.

**Comment by MorrisJobke** [comment]
I updated the logic and now a success message is shown:

bildschirmfoto von 2015-08-21 11-08-31

**Comment by MorrisJobke** [comment]
@Xenopathic @PVince81 @karlitschek @owncloud/designers Is this now better?

**Comment by PVince81** [comment]
Make it green :wink: 

Just kidding, fine by me :+1:

**Comment by rullzer** [comment]
Looking good! :+1:

**Comment by MorrisJobke** [comment]
> Make it green

I tried around with the green, but it was simply to much. So I dropped it again. :wink:

**Comment by Xenopathic** [comment]
:+1: \o/

**Comment by karlitschek** [comment]
good for me :+1:

**Pull request merged**
