### PR TITLE
.htaccess RewriteRules: use permanent redirect for .well-known/(cal|card)dav, add 'L' flag

### PR DESCRIPTION
**Pull request by wolfgangkarall**
As per the docs at https://doc.owncloud.org/server/8.0/user_manual/pim/troubleshooting.html, use  a permanent redirect for caldav/carddav .well-known RewriteRules.

### CODE REVIEW

**Comment by wolfgangkarall** [comment]
Yeah, sure, that change is MIT licensed, whatever.

**Comment by MorrisJobke** [comment]
cc @LukasReschke @DeepDiver1975

**Comment by MorrisJobke** [comment]
@owncloud-bot this is okay to test

**Comment by DeepDiver1975** [comment]
> @owncloud-bot this is okay to test

no need to test htaccess changes :see_no_evil:

**Comment by MorrisJobke** [comment]
@LukasReschke Ping :)

**Comment by Spacefish** [comment]
The commit makes sense to me, as it saves one request if the client caches the permanent redirect. can we merge it?

**Comment by MorrisJobke** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
