### PR TITLE
Trigger propagation from the background scanner

### PR DESCRIPTION
**Pull request by icewind1991**
Make sure we do proper etag propagation when scanning an un-indexed file or folder

cc @PVince81 @rullzer @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
Looks fine. :+1: 

I'm slightly worried about the propagator's array size which could blow up if there are too many changes / a lot of data in an initial scan run of an external storage.

**Comment by icewind1991** [comment]
atm propagation is not batched so it's not a problem, I'm planning to add batching for it with a max batch size

(also the non-background scanner already does this)

**Comment by PVince81** [comment]
Without batching it means that if it recurses into a folder "a/b/c/d/e/f" it will redo the propagation for each section, repeatedly ?

**Comment by icewind1991** [comment]
Yes

**Comment by PVince81** [comment]
... and that sounds wasteful and slow

**Comment by icewind1991** [comment]
Yes, but it's not a simple problem if we also want the cache to be consistent

**Comment by PVince81** [comment]
One idea would be to have a list of pending paths to propagate, and for every path if there's a "propagate" entry for the parent.

Basically when scanning "a", add "a" in pending list.
When scanning "a/b", see that "a" is already in list, so don't add "a/b".
Etc.

And at the end go through the list and propagate for each entry.

**Comment by icewind1991** [comment]
Yes, I'm planing something like that

**Comment by icewind1991** [comment]
outside of the scope of this pr though

**Comment by PVince81** [comment]
@icewind1991 is there time to do this for 9.1 ? I'm worried about the performance impact, especially for the initial scan of newly added external storages by the bkg job.

**Comment by icewind1991** [comment]
The impact is already limited by the use of transactions in the scanner, I have some wip code for batching though which I will try to finish in the next few days

**Comment by PVince81** [comment]
Ok, thanks for the info. Fair enough :+1: 

Second review please @owncloud/filesystem @nickvergessen @mmattel @SergioBertolinSG

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
