### PR TITLE
[stable8] Fix root request path for Dropbox

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/14946 to stable8

@icewind1991 @Xenopathic @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by TanvirKha** [comment]
#10934

**Comment by TanvirKha** [comment]
#10934

**Comment by TanvirKha** [comment]
#10934

**Pull request merged**
