### PR TITLE
Tech dept/remove deprecated owncloud 8.0.0 calls

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
remove deprecated owncloud 8.0.0 calls

## How Has This Been Tested?
- unit tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
@DeepDiver1975 for all "kill deprecated PRs", please state whether you grepped through all known apps.

This looks good otherwise.

**Comment by DeepDiver1975** [comment]
> please state whether you grepped through all known apps.

I have some representative apps repos locally checked out - for sure not all of them. But this is not within our responsibility.

**Comment by PVince81** [comment]
with known apps I mean the ones we support and maintain

**Comment by DeepDiver1975** [comment]
OCP\Config:: is used in https://github.com/search?q=org%3Aowncloud+%22OCP%5CConfig%3A%3A%22&type=Code
- apps repo - ???
- wnd - needs fixing
- sharepoint - ???
- SMStorage - outdated
- user_cas - outdated - a new version exists with the current maintainer
- user_ldap - PR to come

**Comment by PVince81** [comment]
AFAIK those apps are unmaintained.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by phil-davis** [comment]
ownbrander has a bunch of `OCP\Config` references. I raised an issue.

**Comment by phil-davis** [comment]
(potential) Backport to `stable10` #34927

**Pull request merged**
