### PR TITLE
Fixes pagination in IE

### LINKED ISSUE #20044: IE 11: Pagination doesn't work on Public Link
ownCloud 8.2.0
Internet Explorer 11 doesn't shows the pagination.
Also this fixed didn't solved the problem:
https://github.com/owncloud/core/pull/19895

### PR DESCRIPTION
**Pull request by MorrisJobke**
- tested in Firefox, Chrome, Safari, IE and Edge with folder and file shares
- fixes #20044

@PVince81 @karlitschek @DeepDiver1975 @LukasReschke @Henni 

@karlitschek We should backport this to stable8.2

### CODE REVIEW

**Comment by PVince81** [comment]
@MorrisJobke can you prepare the backport PR (I predict conflicts) so we can test applying it on top of the 8.2.2 release ? (some apps might cause side-effects, so best is to have them too)

**Comment by LukasReschke** [comment]
Works here in Safari, Chrome and Firefox. Can't really judge though except "didn't break anything when clicking around" :see_no_evil: :+1:

**Comment by PVince81** [comment]
I reproduced the issue in 8.2.2 (release tarball) in Chromium, Firefox, IE8, IE9, then applied this patch and it fixed the issue. :+1:

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/22556

**Pull request merged**
