### PR TITLE
Merge back Release 10.8.0

### PR DESCRIPTION
**Pull request by micbar**
## Description
Merge back the release branch after successful release

## Related Issue

- Relates to https://github.com/owncloud/enterprise/issues/4508

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiWebdavMove1-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiFederationToShares1-git-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-7-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30990/177/1

**Comment by phil-davis** [comment]
> boom Acceptance tests pipeline **apiProxySmoke-8-7-mariadb10.2-php7.4** failed. The build has been cancelled.
> 
> https://drone.owncloud.com/owncloud/core/30990/177/1

https://drone.owncloud.com/owncloud/core/30990/177/14
It had some problem with "proxy" not starting quickly enough.

I  restarted CI.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiOnSqlite-sqlite-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30991/179/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/31139/88/13
```
  Scenario Outline: Skip trashbin based on extensions - match is case-sensitive                   # /drone/src/tests/acceptance/features/apiTrashbin/trashbinSkip.feature:44
    Given the administrator has set the following file extensions to be skipped from the trashbin # TrashbinContext::theAdministratorHasSetFollowingFileExtensionsToBeSkippedFromTrashbin()
      | extension |
      | dat       |
      | php       |
      | go        |
    And user "Alice" has uploaded file with content "sample delete file 1" to "sample.TXT"        # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 2" to "sample.DAT"        # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 3" to "sample.PHP"        # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 4" to "sample.GO"         # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 5" to "sample.PY"         # FeatureContext::userHasUploadedAFileWithContentTo()
    And using <dav-path> DAV path                                                                 # FeatureContext::usingOldOrNewDavPath()
    When user "Alice" deletes the following files                                                 # FeatureContext::userDeletesFollowingFiles()
      | path       |
      | sample.TXT |
      | sample.DAT |
      | sample.PHP |
      | sample.GO  |
      | sample.PY  |
    Then as "Alice" the file with original path "/sample.TXT" should exist in the trashbin        # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.DAT" should exist in the trashbin         # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.PHP" should exist in the trashbin         # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.GO" should exist in the trashbin          # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.PY" should exist in the trashbin          # TrashbinContext::elementIsInTrashCheckingOriginalPath()

    Examples:
      | dav-path |
      | old      |
        File previously located at /sample.DAT wasn't found in the trashbin
        Failed asserting that false is true.
      | new      |
        File previously located at /sample.DAT wasn't found in the trashbin
        Failed asserting that false is true.
```

This is an old version of the scenario. `sample.DAT` is not in the trashbin, because `dat` files are skipped from going in the trashbin, and the matching of `dat` with `DAT` is not case-sensitive.

I will look at what commit needs to be added here to get the correct test expectations...

**Comment by phil-davis** [comment]
And we are back to having GitHub say that there are conflicts for `tests/acceptance/features/apiTrashbin/trashbinSkip.feature`

Something in the order that changes have been done to `trashbinSkip.feature` is causing `git` to not know how to auto-merge that. IMO we are stuck with it for now. We know that the tests pass when they run, because each PR  to `release-10.8.0` passes. So that is "a good thing".

We will have to do a "temporary manual rebase" of the commits from this branch in order to do the final merge-back to master - when the release has been tagged.

**Comment by phil-davis** [comment]
After merging #38999 to core, this merge-back PR no longer reports conflicts - :rocket:

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToRoot1-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31420/108/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToRoot1-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31420/107/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToRoot1-10.6.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31420/109/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares1-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31425/114/1

**Comment by phil-davis** [comment]
Maybe #39042 will help. It should pass "soon", I hope.

**Review by phil-davis — APPROVED** [review]
The code diffs here are all things that are wanted/correct to go in master.
IMO  this can be merged when CI  passes.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/31427/35/10
```
There was 1 error:

1) OCA\Files_External\Tests\Storage\OwncloudTest::testCopy with data set #6 ('/sòurcē.txt', '/tärgét.txt')
OCP\Files\StorageNotAvailableException: Sabre\HTTP\ClientHttpException: Internal Server Error

/drone/src/lib/private/Files/Storage/DAV.php:901
/drone/src/lib/private/Files/Storage/DAV.php:859
/drone/src/lib/private/Files/Storage/DAV.php:694
/drone/src/lib/private/Files/Storage/DAV.php:188
/drone/src/apps/files_external/tests/Storage/OwncloudTest.php:55
```

I have seen this unit test error "sometimes". I will restart CI.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/31428/9/6
``phpunit-php7.2-sqlite: 1 error occurred: * Forbidden: Forbidden status code: 403, request id: , host id:`

what???

restarted again

**Pull request merged**
