### PR TITLE
Update sabre-2.1.3 thirdparty submodule

### PR DESCRIPTION
**Pull request by PVince81**
Requires https://github.com/owncloud/3rdparty/pull/168

@DeepDiver1975 @LukasReschke @icewind1991

### CODE REVIEW

**Comment by LukasReschke** [comment]
```
07:06:48 .................................................PHP Fatal error:  Declaration of OC\Connector\Sabre\Principal::findByUri() must be compatible with Sabre\DAVACL\PrincipalBackend\BackendInterface::findByUri($uri, $principalPrefix) in /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/connector/sabre/principal.php on line 18
```

**Comment by DeepDiver1975** [comment]
3rdparty submodule ref has to be updated - 

> Requires owncloud/3rdparty#168

merged

**Comment by PVince81** [comment]
Updated ref

**Comment by DeepDiver1975** [comment]
ltmus:

```sh
 ~/Development/ownCloud/litmus-0.13$ litmus -k http://localhost/oc/master/remote.php/webdav/ admin admin
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... WARNING: server does not claim Class 2 compliance
    ...................... pass (with 1 warning)
 3. put_get............... pass
 4. put_get_utf8_segment.. pass
 5. put_no_parent......... pass
 6. mkcol_over_plain...... pass
 7. delete................ pass
 8. delete_null........... pass
 9. delete_fragment....... pass
10. mkcol................. pass
11. mkcol_again........... pass
12. delete_coll........... pass
13. mkcol_no_parent....... pass
14. mkcol_with_body....... pass
15. finish................ pass
<- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `copymove':
 0. init.................. pass
 1. begin................. pass
 2. copy_init............. pass
 3. copy_simple........... pass
 4. copy_overwrite........ pass
 5. copy_nodestcoll....... pass
 6. copy_cleanup.......... pass
 7. copy_coll............. pass
 8. copy_shallow.......... WARNING: Could not delete csrc
    ...................... pass (with 1 warning)
 9. move.................. pass
10. move_coll............. pass
11. move_cleanup.......... pass
12. finish................ pass
<- summary for `copymove': of 13 tests run: 13 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `props':
 0. init.................. pass
 1. begin................. pass
 2. propfind_invalid...... pass
 3. propfind_invalid2..... pass
 4. propfind_d0........... pass
 5. propinit.............. pass
 6. propset............... pass
 7. propget............... pass
 8. propextended.......... pass
 9. propmove.............. pass
10. propget............... pass
11. propdeletes........... pass
12. propget............... pass
13. propreplace........... pass
14. propget............... pass
15. propnullns............ pass
16. propget............... pass
17. prophighunicode....... pass
18. propget............... pass
19. propremoveset......... pass
20. propget............... pass
21. propsetremove......... pass
22. propget............... pass
23. propvalnspace......... pass
24. propwformed........... pass
25. propinit.............. pass
26. propmanyns............ pass
27. propget............... pass
28. propcleanup........... pass
29. finish................ pass
<- summary for `props': of 30 tests run: 30 passed, 0 failed. 100.0%
-> running `locks':
 0. init.................. pass
 1. begin................. pass
 2. options............... WARNING: server does not claim Class 2 compliance
    ...................... pass (with 1 warning)
 3. precond............... SKIPPED (locking tests skipped,
server does not claim Class 2 compliance)
-> 1 test was skipped.
<- summary for `locks': of 3 tests run: 3 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `http':
 0. init.................. pass
 1. begin................. pass
 2. expect100............. pass
 3. finish................ pass
<- summary for `http': of 4 tests run: 4 passed, 0 failed. 100.0%

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
