### PR TITLE
Do not set the default quota if no suitable quota can be found

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Do not set the default quota if no suitable quota can be found. Setting the default quota seems a wrong choice.

## Related Issue
https://github.com/owncloud/core/issues/28309

## How Has This Been Tested?
manually tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Port to 10.0 will be needed.

@PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
> How Has This Been Tested?

**Comment by jvillafanez** [comment]
I've tested manually

**Comment by PVince81** [comment]
@jvillafanez and I guess you'll leave it up to QA to guess what the test steps were ?

**Comment by jvillafanez** [comment]
1. Setup a LDAP connection without quota info in the advanced tab
2. Go to the users page and setup a quota for one of the LDAP users from there.
3. Make sure the `lastFeatureRefresh` in the user's preferences hasn't been updated for 1 day (you can delete the key from the DB)
4. Run the `occ ldap:check-user` with the target user.
5. Login with the target user
6. Go to the personal page and check the quota.

Previously, the quota would be the default one (set in the users page). Now the quota shouldn't change.

Note that these steps might not be 100% failproof. Sometimes I had to go back to step 3 and repeat.

There could also be other scenarios which could trigger this issue. I think the key point is to remove the `lastFeatureRefresh` from the DB and check the user's existence in order to force an update of the user's information.

**Comment by cdamken** [comment]
The expected behavior:

1.- ownCloud default quota is set as 1 choice.
2.- Administrators can modify the quota in the user page.
3.- If LDAP quota is set -> overrides ownCloud quotas.
4.- If quota per attribute in LDAP is set -> overrides LDAP quota.

ref: https://github.com/owncloud/enterprise/issues/1813#issuecomment-281051811

**Comment by PVince81** [comment]
and if no quota is set inside of LDAP at all (no quota attributes), don't override the local quota.

@jvillafanez please rebase and move this forward.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by jvillafanez** [comment]
Rebased

**Comment by jvillafanez** [comment]
Checking tests failures...

**Pull request merged**
