### PR TITLE
Cache generated result

### PR DESCRIPTION
**Pull request by LukasReschke**
Saves 50ms for simple GETs :speak_no_evil: 

With this and https://github.com/owncloud/core/issues/18913 applied we're down to 145ms from 274ms on my local machine.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@karlitschek @icewind1991 THX

**Comment by LukasReschke** [comment]
And good call @icewind1991 to do some benchmarking… I should start Blackfire more often as well :see_no_evil:

**Comment by karlitschek** [comment]
nice! Every ms counts :-)

**Comment by karlitschek** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1: looks good

**Pull request merged**
