### PR TITLE
Allow to decrypt user '0' files only

### LINKED ISSUE #24994: Cannot decrypt a user's account called 0 via occ command
### Steps to reproduce

1. Create a oC user called "0"
2. Encrypt your oC server via occ command
3. Try to decrypt "0"'s account via occ command ```occ encryption:decrypt 0```

### Expected behaviour

Running ```occ encryption:decrypt 0``` command should decrypt "0"'s account

### Actual behaviour

The CLI is taking 0 parameter as empty, so the whole oC server will be decrypted 

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.1.0.5","versionstring":"9.1.0 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes
**Logs**
```

```
### Client configuration

**browser**

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #24994 

@PVince81 @davitol

### CODE REVIEW

**Comment by nickvergessen** [comment]
Needs rebase after https://github.com/owncloud/core/pull/24992 is merged

**Comment by PVince81** [comment]
:+1:

**Comment by guruz** [comment]
👍

**Comment by rullzer** [comment]
Sometimes you just got to love php :S

**Comment by nickvergessen** [comment]
@PVince81 now you merged both conflicting PRs, will send a follow up

**Comment by PVince81** [comment]
Ah... I thought it was resolved differently since they were both "To release".

Looking forward to the follow up PR.

**Pull request merged**
