### PR TITLE
[backport][stable8.2] passing an empty base in this diagnosis call will not result  in LDAP…

### PR DESCRIPTION
**Pull request by blizzz**
… errors

Backport of https://github.com/owncloud/core/pull/21037 to stable8.2

### CODE REVIEW

**Comment by blizzz** [comment]
Please test and review @owncloud/ldap @CaptionF @davitol

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by davitol** [comment]
:+1: WFM

**Pull request merged**
