### PR TITLE
Disallow cookie auth for cors requests stable8

### PR DESCRIPTION
**Pull request by BernhardPosselt**
Backport of #16532 

Just a git cherry-pick 

confirmed working using the News app

@LukasReschke @DeepDiver1975 @MorrisJobke @PVince81

### CODE REVIEW

**Comment by LukasReschke** [comment]
Targeting 8.0.5 next maintenance. THX.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> Targeting 8.0.5 next maintenance. THX.

is that a :+1: :question:

**Comment by DeepDiver1975** [comment]
@LukasReschke

**Comment by LukasReschke** [comment]
Yes.

**Pull request merged**
