### PR TITLE
Implement the autocomplete blocker from #18341 into the OCS endpoint

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Requires #18234 - Add OCS API for sharees list
- [x] Make check case insensitive

Replacing #18341

### CODE REVIEW

**Comment by nickvergessen** [comment]
Only review the last commit here @DeepDiver1975 @MorrisJobke

**Comment by MorrisJobke** [comment]
Ömmm...I changed the config option to an appconfig implementation. Including options in the web UI

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/commit/accba48874967c181abd9d06887b9b5f25a15752

**Comment by nickvergessen** [comment]
@MorrisJobke cherry-picked

**Comment by rullzer** [comment]
@nickvergessen could you rebase (since the shareeAPI is now merged)?. Seems like a good idea to respect the config variable.

**Comment by nickvergessen** [comment]
Done

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
This is actually the forward port for https://github.com/owncloud/core/pull/18353 which already exists on 8.1

**Comment by PVince81** [comment]
@nickvergessen needs rebase

**Comment by nickvergessen** [comment]
rebased

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Can you merge once CI is fine? :smile:

**Pull request merged**
