### PR TITLE
Introduce new global config to disable user enumeration - first to be us...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
...e in the sharing drop down - more to follow ???

@karlitschek to be used in certain education setups

@schiesbn @PVince81 @LukasReschke  please review - THX

### CODE REVIEW

**Comment by MTRichards** [comment]
@karlitschek to reopen.

**Comment by MTRichards** [comment]
Use case: disable the type ahead filter in the sharing dialog and only allow a user to
share based on an exactly correct email address (in this case the username), and each user may have
several email addresses.

**Comment by LukasReschke** [comment]
> @karlitschek to reopen the issue of not enumerating user email addresses while trying to share for privacy officer objections.

If we're going to prevent this then the threat model is simply: "Users shall not be able to gain a list of other users on the instance" and this requires _far_ more changes than done in this PR and shall require to get a new issue opened.

**Comment by MTRichards** [comment]
https://github.com/owncloud/core/issues/16907

**Pull request closed without merging**
