### PR TITLE
add overflow ellipsis to session and device tokens list

### PR DESCRIPTION
**Pull request by ChristophWurst**
Long user agent made the list/table too wide for small screens.
# Before

bildschirmfoto von 2016-06-09 10-50-19
# After

bildschirmfoto von 2016-06-09 10-49-48

@PVince81 @nickvergessen @owncloud/designers

### CODE REVIEW

**Comment by nickvergessen** [comment]
Should have a tool tip or another option to read the full text?

**Comment by ChristophWurst** [comment]
@nickvergessen yes, it should. Let me add that

**Comment by guruz** [comment]
Yep either tooltip or ```overflow: scroll``` ? The latter you could still cut+paste

**Comment by ChristophWurst** [comment]
Ff I wrap the token name with a span, add the title attribute and call the ``.tooltip()`` helper it works. However, the tooltip position depends on the width of the span. In case the span is at least 2x as wide as the column, the tooltip is shown outside the column. @PVince81 any idea how to circumvent that?

**Comment by PVince81** [comment]
@ChristophWurst I think there's a parameter for the tooltip plugin where you can tell it in which container to render. You can try changing it to render to the body instead of the parent of the span.

**Comment by jancborchardt** [comment]
The »Browser« column could be a bit wider compared to the »Most recent activity« one, right? Because that has a maximum length also set in Files. You can use the same one here, as well as for the »Devices« section below.

Btw @ChristophWurst the Sessions and Devices sections should be _below_ the Language and Sync clients sections. Otherwise the layout gets messed up.

**Comment by PVince81** [comment]
Try 1: On the "td" it is centered properly but it is not close enough to the text any more and looks disconnected.
Try 2: On a wrapping "span" inside the "td", the span has the same size.
Try 3: same as 2 and move "ellipsis" properties directly on the span. Now it's centered on the cell and closer to the text when ellipsized. However as soon as no ellipsis is needed, it's centered on the cell, not on the text...

**Comment by PVince81** [comment]
I tried many different things, it doesn't seem to be possible.

The problem is that ellipsised size vs non-ellipsized is not the same.
So we have two possibilities:
1) Center the tooltip on the td / container, but then if the text is short the tooltip will be off (ex: "seconds ago" is shorter than the column)
2) Center the tooltip on the span, this is the same effect as what this PR is doing currently: the tooltip will not be centered when ellipsized

Other tweaks would require hacking the jquery.tooltip library to maybe use "scrollWidth" instead of "offsetWidth". But even that didn't work because ellipsis requires "display: block", so the text span always takes as much horizontal space as available. So neither "offsetWidth" nor "scrollWidth" represent the actual text's width.

Another even more complicated hack involves detecting resize events and then detecting whether the text is ellipsized and changing the tooltip's position calculation logic based on whether the ellipsis mode is active or not. To detect ellipsis mode, compare "offsetWidth" with "scrollWidth".

**Comment by PVince81** [comment]
Ah, now there's even another possibilty which would be even nicer: only show the tooltip if the element is actually ellipsized. In this case centering only applies to one mode and would match.
This would also require hacking the jquery.tooltip plugin...

**Comment by PVince81** [comment]
Yeah, or something like this: http://chadkuehn.com/show-tooltip-over-truncated-text/

**Comment by PVince81** [comment]
I went with a compromise: since user agents are usually bigger, the tooltip is set on the TD and centered on that. So most of the time it should look fine.

But for the timestamp, it is less likely to be ellipsized so I left the tooltip to be centered on the SPAN instead of TD.

Please review, I think this is good enough.

:+1: from me for @ChristophWurst's commits

**Comment by ChristophWurst** [comment]
:+1: for @PVince81's commit ;-)

**Comment by PVince81** [comment]
Second review ? @VicDeo @georgehrke @guruz

**Comment by guruz** [comment]
👍

**Pull request merged**
