### PR TITLE
[stable10] Fix migration issue caused during upgrade to version 10

### PR DESCRIPTION
**Pull request by sharidas**
This change will help users to fix the migration
issue caused during upgrade to version 10. If
user had opted user specific key in the older versions
then no drop down will appear in the version 10.
Same applies if user had opted for the masterkey
in older version, no drop down will appear in version
10.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

When user tries to upgrade from versions < 10, the userSpecificKey is not present in the appConfig. And as a result during migration to version 10.0.2, the user gets an option to select the encryption mode :
- [x] User Specific Key
- [x] Master Key
This issue is addressed with this change.

## Related Issue

https://github.com/owncloud/core/issues/28985

## Motivation and Context

The change made here solves, the issues caused during migration.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
@sharidas please do a quick retest when coming from 10.0.3 to this branch (just one case is enough)

**Review by PVince81 — APPROVED** [review]
:+1: if it works

**Comment by PVince81** [comment]
@sharidas please always add a link in the original PR to the backport

**Comment by sharidas** [comment]
Test result of migration from 10.0.3beta ( tarball ) to the current change:
- [x] Migration of 10.0.3beta with masterkey enabled to the current master change. Works well. The encryption page doesn't show drop down and here is the screenshot: 
migrationwithmasterkeyfrom10-0-3

- [x] Migration from 10.0.3beta from userkey enabled to the current change. Works well. The encrytion page doesnt show the drop down and here is the screenshot : 
migrationwithuserkeyfrom10-0-3

**Pull request merged**
