### PR TITLE
Do not try clearing locked files in cache folder

### LINKED ISSUE #39: Interrupted upload results in lock on unrelated folders
### Steps to reproduce

With curl:
1.  `curl -v -X PUT -u [user]:[pass] -H "OC-Chunked:1" "http://[server]/remote.php/webdav/Photos/file.mp4-chunking-7860-2-0" -F myfile=@"[localPath]\file.mp4"`
2. Interrupt abruptly the transference - (unplug the Ethernet cable, turn off the WiFi adapter...)
3. Wait for curl aborts the connection
4. Enable again the network access
5. `curl -v -u [user]:[pass] -X PROPFIND -H "Content-Type: text/xml" -d "<?xml version='1.0' encoding='UTF-8'?><D:propfind xmlns:D='DAV:'><D:prop><D:resourcetype/><D:getlastmodified/><size xmlns='http://owncloud.org/ns'/><D:creationdate/><id xmlns='http://owncloud.org/ns'/><D:getcontentlength/><D:displayname/><D:getetag/><permissions xmlns='http://owncloud.org/ns'/><D:getcontenttype/></D:prop></D:propfind>" http://[server]/remote.php/webdav/`
6. `curl -v -u [user]:[pass] -X PROPFIND -H "Content-Type: text/xml" -d "<?xml version='1.0' encoding='UTF-8'?><D:propfind xmlns:D='DAV:'><D:prop><D:resourcetype/><D:getlastmodified/><size xmlns='http://owncloud.org/ns'/><D:creationdate/><id xmlns='http://owncloud.org/ns'/><D:getcontentlength/><D:displayname/><D:getetag/><permissions xmlns='http://owncloud.org/ns'/><D:getcontenttype/></D:prop></D:propfind>" http://[server]/remote.php/webdav/Documents`
### Expected behaviour

Both (5) and (6) should return the list of files in folders "/" (5) and "/Documents/" (6). Please, notice that the file in (1) was uploading to "/Photos/"
### Actual behaviour

Both (5) and (6) finish with error 500 and next response:
`<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
      <s:exception>OCP\Files\LockNotAcquiredException</s:exception>
      <s:message>Could not obtain lock type 1 on "/opt/owncloud/data/admin/cache/file.mp4-chunking-7860-0.y9A4yfbYqmIyat4w.part".</s:message>
</d:error>`
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache/2.4.7

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.1.0.7  (nightly generated 30/06/2015)

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Activity 2.0.0
Deleted files 0.6.2
File Locking
First Run Wizard 1.1
Mail Template Editor 0.1
PDF Viewer 0.7
Pictures 0.6.0
Provisioning API 0.2
Share Files 0.6.1
Text Editor 0.4
Updater 0.5
Versions 1.0.5
Video Viewer 0.1.3

No matter if transactional file locking is enabled or not.

The bug does not happen with File Locking app disabled.

**The content of config/config.php:**
Unknown

**Are you using external storage, if yes which one:** local/smb/sftp/...
Not sure

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### ownCloud log (data/owncloud.log)

```
Exception: {"Message":"Could not obtain lock type 1 on \"\/opt\/owncloud\/data\/admin\/cache\/file.mp4-chunking-7860-0.y9A4yfbYqmIyat4w.part\".","Code":0,"Trace":"#0 \/opt\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php(45): OCA\\Files_Locking\\Lock->addLock(1, Resource id #30)\n
#1 \/opt\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php(172): OCA\\Files_Locking\\LockingWrapper->getLock('cache\/file.mp4-...', 1, Resource id #30)\n
#2 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(609): OCA\\Files_Locking\\LockingWrapper->fopen('cache\/file.mp4-...', 'r')\n
#3 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(629): OC\\Files\\Storage\\Wrapper\\Encryption->getHeader('cache\/file.mp4-...')\n
#4 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php(215): OC\\Files\\Storage\\Wrapper\\Encryption->getEncryptionModule('cache\/file.mp4-...')\n
#5 [internal function]: OC\\Files\\Storage\\Wrapper\\Encryption->unlink('cache\/file.mp4-...')\n
#6 \/opt\/owncloud\/apps\/files_trashbin\/lib\/storage.php(116): call_user_func_array(Array, Array)\n
#7 \/opt\/owncloud\/apps\/files_trashbin\/lib\/storage.php(89): OCA\\Files_Trashbin\\Storage->doDelete('cache\/file.mp4-...', 'unlink')\n
#8 \/opt\/owncloud\/lib\/private\/files\/view.php(1006): OCA\\Files_Trashbin\\Storage->unlink('cache\/file.mp4-...')\n
#9 \/opt\/owncloud\/lib\/private\/files\/view.php(598): OC\\Files\\View->basicOperation('unlink', '\/file.mp4-chunk...', Array)\n
#10 \/opt\/owncloud\/lib\/private\/cache\/file.php(187): OC\\Files\\View->unlink('\/file.mp4-chunk...')\n
#11 \/opt\/owncloud\/lib\/base.php(734): OC\\Cache\\File->gc()\n
#12 [internal function]: OC::{closure}(Object(OC\\User\\User), 'Password')\n
#13 \/opt\/owncloud\/lib\/private\/hooks\/emittertrait.php(99): call_user_func_array(Object(Closure), Array)\n
#14 \/opt\/owncloud\/lib\/private\/hooks\/publicemitter.php(32): OC\\Hooks\\BasicEmitter->emit('\\OC\\User', 'postLogin', Array)\n
#15 \/opt\/owncloud\/lib\/private\/user\/session.php(223): OC\\Hooks\\PublicEmitter->emit('\\OC\\User', 'postLogin', Array)\n
#16 \/opt\/owncloud\/lib\/private\/user.php(241): OC\\User\\Session->login('admin', 'Password')\n
#17 \/opt\/owncloud\/lib\/private\/connector\/sabre\/auth.php(71): OC_User::login('admin', 'Password')\n
#18 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php(74): OC\\Connector\\Sabre\\Auth->validateUserPass('admin', 'Password')\n
#19 \/opt\/owncloud\/lib\/private\/connector\/sabre\/auth.php(135): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n
#20 \/opt\/owncloud\/lib\/private\/connector\/sabre\/auth.php(115): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n
#21 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n
#22 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#23 \/opt\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#24 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n
#25 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#26 \/opt\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n
#27 \/opt\/owncloud\/remote.php(84): require_once('\/opt\/owncloud\/a...')\n
#28 {main}","File":"\/opt\/owncloud\/apps\/files_locking\/lib\/lock.php","Line":257}
```

EXTRA: relevant for mobile in cases of lost connectivity.
Android client:
1. Upload a file bigger than 1MB (chunked mode) to "/Photos/"
2. Turn off the network access while the file is uploading (simulate lost conectivity)
3. The upload fails; tap on the notification bar to access the folder where the upload was in progress.
4. Turn on notification
5. Browse to root folder (is not refreshed)
6. Browse to "/Documents/" folder (not refreshed; if never browsed into before, appears as an empty folder, although it's not).

The client can't refresh anymore until the lock is released by the server (some minutes later).

cc: @DeepDiver1975 , @PVince81

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/files_locking/issues/39

@davivel can you test ?

@icewind1991 @DeepDiver1975 @schiesbn 
- [x] TODO: add unit tests

### CODE REVIEW

**Comment by davivel** [comment]
@PVince81 I will!

**Comment by davivel** [comment]
Tested. Works like a charm.

:+1:

**Comment by PVince81** [comment]
I have some additions: I fixed the postLogin hook to log an the exception instead of preventing login. This is better in case any other exception would popup in the GC code...

Waiting for Jenkins to finish to push.

**Comment by PVince81** [comment]
Please review the code.

**Comment by icewind1991** [comment]
Looks good :+1:

**Comment by PVince81** [comment]
Jenkins PR https://github.com/owncloud/core/pull/17261

**Comment by PVince81** [comment]
@karlitschek @cmonteroluque backport to stable8.1 or do we want to wait for 8.1.1 ?

**Comment by PVince81** [comment]
Backport PR here https://github.com/owncloud/core/pull/17288

**Comment by davivel** [comment]
Seen. Thx.

**Pull request merged**
