### PR TITLE
trigger event on input autofill

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Trigger a js event on choosing autofill in input fields

## Related Issue

https://github.com/owncloud/core/issues/27096

## How Has This Been Tested?

Tested in FF 51 only _(so far)_

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by davitol** [comment]
- [ ] Firefox 51 for OSX
- [ ] Safari 9.1.2
- [ ] Chrome 56

@felixheidecke 

:+1: From my POV to merge this PR, but:

* With all browser, cleaning the textbox, the message says email saved ( I feel OK about it)
* Using Safari as browser, using one of the mails saved, the gauge does not work properly, but the mail gets saved.

mailbeh

**Comment by PVince81** [comment]
This will clash with https://github.com/owncloud/core/pull/27277 where a Save button was added because of sending email confirmation.

**Comment by PVince81** [comment]
but as this is usable for other fields => 👍

**Comment by felixheidecke** [comment]
> This will clash with #27277 where a Save button was added because of sending email confirmation.
@PVince81 What's the way to go?

**Comment by PVince81** [comment]
whoever finishes first gets the merge

**Comment by PVince81** [comment]
@felixheidecke did your bad luck break travis today ?

Try rebasing

**Comment by felixheidecke** [comment]
I tried no such thing today!?

**Comment by felixheidecke** [comment]
@davitol … well, this is as good as it gets right now. I could add the blur event also, but this gets fired too often in conjunction with the current event watchers. Checking if the content changed and save depending on the outcome should be a new issue.

@PVince81 fine with you?

**Comment by PVince81** [comment]
Fine with me if this works with IE11 also

**Comment by felixheidecke** [comment]
> Fine with me if this works with IE11 also

Japp – works fine ;-)

**Pull request merged**
