### PR TITLE
make knowledge base url configurable

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #17961

fix https://github.com/owncloud/core/issues/17959

### CODE REVIEW

**Comment by schiesbn** [comment]
:+1:

**Comment by karlitschek** [comment]
as discussed :+1:

**Comment by Xenopathic** [comment]
:warning: :warning: :warning: This *might* be broken: https://github.com/owncloud/core/pull/17961#issuecomment-128175025 :warning: :warning: :warning:

**Comment by DeepDiver1975** [comment]
:-1: :-1: until we have a confirmation regarding #18095

**Comment by Xenopathic** [comment]
I've added the fix from #18109.

**Comment by Xenopathic** [comment]
LGTM :+1:

@icewind1991 Could you review the backport of the Router fix? THX

**Comment by LukasReschke** [comment]
:-1:

**Comment by LukasReschke** [comment]
Blocked by https://github.com/owncloud/core/pull/18200

**Comment by Xenopathic** [comment]
Wow, this simple little change really exposed how fraglie our Router is...

**Comment by DeepDiver1975** [comment]
we are going to revert all changes in master - once we have a proper fix in place we can reconsider backport - THX

**Pull request closed without merging**
