### PR TITLE
[stable8.1] Fix global app list state

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/17353

@DeepDiver1975 @MorrisJobke @karlitschek

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
Fixes #17344

**Comment by PVince81** [comment]
Oracle failed... not related, this is a JS only change and the JS tests ran already.

@DeepDiver1975 merge ? (if this was intended for RC3/final)

**Comment by PVince81** [comment]
Hmm the test passed here: https://github.com/owncloud/core/pull/17354#issuecomment-118097121

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
(just to kill time until someone wants to review this)

**Comment by LukasReschke** [comment]
Works :+1:

**Comment by cmonteroluque** [comment]
thank you!

**Comment by davitol** [comment]
:+1: Tested in version":"8.2.0.0","versionstring":"8.2 pre alpha" (master 2015/07/03)

**Pull request merged**
