### PR TITLE
update 3rdparty to latest JSqueeze

### PR DESCRIPTION
**Pull request by georgehrke**
please review @DeepDiver1975 
- [x] requires https://github.com/owncloud/3rdparty/pull/266

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by georgehrke** [comment]
@karlitschek Can we backport this?
(otherwise calendar is completely broken when asset pipelines are enabled)

**Comment by karlitschek** [comment]
makes sense. please backport 👍

**Comment by DeepDiver1975** [comment]
> makes sense. please backport :+1:

@georgehrke please open backport prs in core and 3rdparty - THX

**Comment by MorrisJobke** [comment]
> @georgehrke please open backport prs in core and 3rdparty - THX

@georgehrke Ping

**Comment by MorrisJobke** [comment]
> @georgehrke Ping

Ping

**Comment by georgehrke** [comment]
There is yet another jsqueeze update we need for the calendar. I send a pr to 3rdparty master yesterday, that's why I didn't send a pull request for the old update to stable9 yet.

**Comment by MorrisJobke** [comment]
stable9: https://github.com/owncloud/3rdparty/pull/271

**Comment by MorrisJobke** [comment]
We should backport the 2.0.5 https://github.com/owncloud/3rdparty/pull/275

**Pull request merged**
