### PR TITLE
Remove deprecated \OCP\User::getUser

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
 \OCP\User::getUser was deprecated in ownCloud 8 - time to say good bye

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
litmus failed with:
```
unhandled exception has been thrown:
TypeError: Argument 6 passed to OCA\DAV\HookManager::__construct() must implement interface OCP\IUserSession, null given in /drone/src/apps/dav/lib/HookManager.php:63
```

maybe there's more to adjust ?

**Comment by DeepDiver1975** [comment]
Load Order issue. Will Take Care

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by DeepDiver1975** [comment]
doesn't work -> bomb

**Pull request closed without merging**
