### PR TITLE
[stable8.1] setUserVars() should only attempt substitution with strings

### LINKED ISSUE #18386: files_external smb_oc.php username_as_share is logical not string
External storage support 0.2.3

Line 42 sets local username_as_share if the parameter is the string 'true', but the data item is a logical value:
```
$this->username_as_share = ($params['username_as_share'] === 'true');
```

The local value of username_as_share is used in this code block:
```
     58                         if ($this->username_as_share) {
     59                                 $share = '/' . $user;
     60                         } elseif (isset($params['share'])) {
     61                                 $share = $params['share'];
     62                         } else {
     63                                 throw new \Exception();
     64                         }
```

I was customizing the code in line 59 to execute a transformation I need to apply to my username values (my  usernames are <folder>@domain.tld, and I need to strip off the extra cruft), but the resulting code was never invoked.

However, my custom code worked fine after changing line 42::
```
$this->username_as_share = ($params['username_as_share'] === TRUE);
```

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Otherwise funky things happen like `true (bool)` => `'1' (string)`

Backport of #18445
Fixes #18386 

@PVince81 @DeepDiver1975 @MorrisJobke @icewind1991

Please confirm backport @karlitschek

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: tested with S3 mount point

**Comment by Xenopathic** [comment]
:warning: Hold up, I forgot about migrating legacy storages that actually use strings to represent booleans.

**Comment by Xenopathic** [comment]
The fix here isn't anywhere nearly as neat as the one in the master PR, but to avoid messing with lots of code I went down the easy route.

**Comment by Xenopathic** [comment]
@karlitschek Please confirm backport? This fixes a regression from 8.0 with the handling of checkbox values in files_external

**Comment by karlitschek** [comment]
makes sense. please backport :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
