### PR TITLE
Use newly generated certificate authority

### PR DESCRIPTION
**Pull request by LukasReschke**

### CODE REVIEW

**Comment by danimo** [comment]
Merging on Lukas' request

**Comment by karlitschek** [comment]
Let's please stick with the review process and wait for two reviewers in the future. Thanks

**Comment by LukasReschke** [comment]
> Let's please stick with the review process and wait for two reviewers in the future. Thanks

While I generally agree I do believe that it the added benefit of having another reviewer here is actually pretty much non existent due to the type of the change. But fair enough.

**Comment by karlitschek** [comment]
maybe. but let's stick to the rules please.

**Comment by LukasReschke** [comment]
Yeah. You're right, will do. But please blame me instead of poor @danimo. I forced him with a gun :see_no_evil:

**Pull request merged**
