### PR TITLE
Fix missing use statements in ext. str. tests

### PR DESCRIPTION
**Pull request by nickvergessen**
@rullzer @PVince81 @Xenopathic @ChristophWurst

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by PVince81** [comment]
Doesn't seem to work correctly:

```
Runtime:       PHP 5.6.21 with Xdebug 2.3.3
Configuration: /srv/www/htdocs/owncloud/tests/phpunit-autotest-external.xml

...............................................................  63 / 996 (  6%)
............................................................... 126 / 996 ( 12%)
..............................................................E 189 / 996 ( 18%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 252 / 996 ( 25%)
EEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 315 / 996 ( 31%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 378 / 996 ( 37%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSS 441 / 996 ( 44%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 504 / 996 ( 50%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 567 / 996 ( 56%)
SSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 630 / 996 ( 63%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSS 693 / 996 ( 69%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 756 / 996 ( 75%)
SSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 819 / 996 ( 82%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 882 / 996 ( 88%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 945 / 996 ( 94%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.             996 / 996 (100%)

Time: 2.99 seconds, Memory: 72.25Mb

There were 485 errors:

1) OCA\Files_External\Tests\Storage\AmazonS3Test::testStat
include(files_external/tests/config.amazons3.php): failed to open stream: No such file or directory

/srv/www/htdocs/owncloud/apps/files_external/tests/Storage/AmazonS3Test.php:45
/srv/www/htdocs/owncloud/apps/files_external/tests/Storage/AmazonS3Test.php:45

...
```

This is from running `./autotest-external.sh sqlite sftp-atmoz` or `./autotest-external.sh sqlite swift-ceph`

Something else might be missing. It is supposed to only run the test for the selected class.

**Comment by nickvergessen** [comment]
Well I guess https://github.com/owncloud/core/pull/24815

**Comment by nickvergessen** [comment]
Let me rebase this to be sure

**Comment by PVince81** [comment]
@nickvergessen ok I merged the other one, I thought it was done already.

One last rebase ? Hopefully all will be green then

**Comment by nickvergessen** [comment]
Rebased and fixed the exclude path in phpunit config

**Comment by PVince81** [comment]
Works now :+1: 

@owncloud-bot now show us some green!

**Comment by PVince81** [comment]
Cool, the SMB test passed again. Merging this to save some time...

**Pull request merged**
