### PR TITLE
cron.php on cli has no time limitation - fixes #14481

### LINKED ISSUE #14481: cron on CLI should not run into execution time outs

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@karlitschek @PVince81 @MorrisJobke @icewind1991 THX

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:  I have a dejavu. Didn´t we fix this lately?

**Comment by DeepDiver1975** [comment]
> I have a dejavu. Didn´t we fix this lately?

kind of - in the console - but not in cron.php - https://github.com/owncloud/core/blob/master/console.php#L17

We should consolidate this one day

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
fixes #14481

**Pull request merged**
