### PR TITLE
fallback for isimage

### PR DESCRIPTION
**Pull request by icewind1991**
Maybe, possibly fix js tests?

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Maybe, possibly fix js tests?

only one of two

**Comment by MorrisJobke** [comment]
```
PhantomJS 1.9.8 (Linux 0.0.0) OCA.Files.MainFileInfoDetailView tests rendering displays mime icon FAILED
	Expected '' to contain 'filetypes/text-calendar.svg'.
	    at /home/mjob/Projekte/owncloud/master/apps/files/tests/js/mainfileinfodetailviewSpec.js:83
```

**Comment by PVince81** [comment]
Fixed the unit test by properly simulating calling either "callback" then "error" for a mime icon without preview, or by simulating calling "callback" twice, once with a mime icon and once with a preview.

I don't like this legacy API and the fact that we call callback twice, but that's legacy stuff to be improved later.

@icewind1991 @MorrisJobke @nickvergessen please review

**Comment by PVince81** [comment]
@icewind1991 also please don't forget setting the label "To review" and the milestone on your PRs

**Comment by rullzer** [comment]
Tests are fixed!
Code looks good. And horray for extra tests. :+1:

**Comment by DeepDiver1975** [comment]
> Maybe, possibly fix js tests?

@icewind1991 seriously - just fire up the unit tests yourself and have a look. What attitude is this to throw code at the community and let other do the job?

**Comment by MorrisJobke** [comment]
:+1: works

**Pull request merged**
