### PR TITLE
[stable8.2] make sure that we update the unencrypted size for the versions

### PR DESCRIPTION
**Pull request by schiessle**
approved backport of https://github.com/owncloud/core/pull/20288

Steps to test:
- Enable encryption
- Upload a larger file (pdf, odt, jpg,...)
- Upload another copy of the same file
- check if you can download/revert the versions

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Unlike the master branch this doesn't seem to work:

```
{"reqId":"Nn87wfTozFZEpUJmxihW","remoteAddr":"::1","app":"PHP","message":"rewinddir(): 364 is not a valid Directory resource at \/Users\/morrisjobke\/Projects\/owncloud\/master\/lib\/private\/files\/stream\/encryption.php#187","level":0,"time":"2015-11-05T12:54:32+00:00","method":"GET","url":"\/master\/index.php\/apps\/files_versions\/preview?file=%2Fabc.png&version=1446728067"}
{"reqId":"kZpmALwG9hQ9RP4o27+G","remoteAddr":"::1","app":"PHP","message":"rewinddir(): 358 is not a valid Directory resource at \/Users\/morrisjobke\/Projects\/owncloud\/master\/lib\/private\/files\/stream\/encryption.php#187","level":0,"time":"2015-11-05T12:54:32+00:00","method":"GET","url":"\/master\/index.php\/core\/preview.png?file=%2Fabc.png&x=348&y=196&a=1&mode=cover&c=2893456120&forceIcon=0"}
```

(this is also the same error like on an unpatched master.

**Comment by karlitschek** [comment]
nice :+1:

**Comment by schiesbn** [comment]
@MorrisJobke I don't think that this is related. The error happens in the stream wrapper but here we only touch the storage wrapper. Did you tested the steps above. For me this works.

**Comment by MorrisJobke** [comment]
> Did you tested the steps above. For me this works.

Yes. I will retry later

**Comment by PVince81** [comment]
@schiesbn @karlitschek too risky for 8.2.1 ?

**Comment by MorrisJobke** [comment]
Just rechecked and it works now. Maybe I was on a wrong branch. :+1: from my side

**Comment by MorrisJobke** [comment]
> @schiesbn @karlitschek too risky for 8.2.1 ?

https://github.com/owncloud/core/issues/20234 was scheduled for 8.2.2

**Comment by PVince81** [comment]
@MorrisJobke no, I scheduled the ticket based on the milestone from the PR.
But since this fixes a "broken version files" case, I think we could try and put it into 8.2.1

**Comment by MorrisJobke** [comment]
> But since this fixes a "broken version files" case, I think we could try and put it into 8.2.1

fine with me ;) Lets wait for @karlitschek

**Comment by karlitschek** [comment]
let's backport and do additional testing. This bug is too big to not be fixed. @PVince81 @rperezb Can we do some additional manual testing?

**Comment by schiesbn** [comment]
> @PVince81 @rperezb Can we do some additional manual testing? 

Would be great to have some additional manual testing.

What should be tested:

1. Encryption enabled.
2. Upload multiple copies of a file
3. Check if all versions can be downloaded
4. Check if all versions can be reverted and the reverted version can be downloaded correcty
5. repeat step 1-4 with different file typed and different file sizes.

**Comment by PVince81** [comment]
I did some testing myself and it works for me :+1: 

Let's wait for an additional :+1: from QA

**Comment by cmonteroluque** [comment]
we can merge and have QA check during this coming week. @rperezb @SergioBertolinSG

**Comment by SergioBertolinSG** [comment]
Works without problems :+1:

**Comment by pongraczi** [comment]
Check your stored filesize in oc_filecache and the real filesize of the problematic file. Try to rewrite the possible wrong size to the correct one in the table and start resync, maybe it fixes the problem.
I found this workaround and wrote a comment here: https://github.com/owncloud/client/issues/4047

**Pull request merged**
