### PR TITLE
[WIP] Bump phan 0.12.10=>1.1.8

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
TBD

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/13616/96
```
apps/dav/lib/CalDAV/Calendar.php:63 PhanUndeclaredMethod Call to undeclared method \Sabre\CalDAV\Backend\BackendInterface::updateShares
apps/dav/lib/CalDAV/Calendar.php:81 PhanUndeclaredMethod Call to undeclared method \Sabre\CalDAV\Backend\BackendInterface::getShares
apps/dav/lib/CalDAV/Calendar.php:142 PhanUndeclaredMethod Call to undeclared method \Sabre\CalDAV\Backend\BackendInterface::applyShareAcl
apps/dav/lib/CalDAV/Calendar.php:169 PhanUndeclaredMethod Call to undeclared method \Sabre\CalDAV\Backend\BackendInterface::updateShares
apps/dav/lib/CalDAV/Calendar.php:256 PhanUndeclaredMethod Call to undeclared method \Sabre\CalDAV\Backend\BackendInterface::setPublishStatus
apps/dav/lib/CalDAV/Calendar.php:265 PhanUndeclaredMethod Call to undeclared method \Sabre\CalDAV\Backend\BackendInterface::getPublishStatus
apps/dav/lib/CalDAV/CalendarHome.php:65 PhanUndeclaredMethod Call to undeclared method \Sabre\CalDAV\Backend\BackendInterface::getSubscriptionsForUser
apps/dav/lib/CalDAV/CalendarHome.php:96 PhanUndeclaredMethod Call to undeclared method \Sabre\CalDAV\Backend\BackendInterface::getSubscriptionsForUser
apps/dav/lib/CalDAV/Publishing/PublishPlugin.php:184 PhanUndeclaredMethod Call to undeclared method \Sabre\DAV\ServerPlugin::checkPrivileges
...
```

**Review by patrickjahns — CHANGES_REQUESTED** [review]
Please switch to using composer-bin instead of phar for core to align with the other repositories

**Comment by phil-davis** [comment]
Yes, this is just a demonstration anyway of what "new" code issues are reported. So "somebody" has to look into those, or sort out why we would skip stuff, in order to do this version bump anyway.
Moving to composer-bin can be done separately, with only whatever version bump can work without inducing new reports.

**Comment by phil-davis** [comment]
Waiting for someone to review #33908 and get it merged. Then we can look at what to do next with ``phan`` version.

**Comment by phil-davis** [comment]
Out of date. See #34023 for next phan bump

**Pull request closed without merging**
