### PR TITLE
include the final update in the transaction when moving a folder in the cache

### PR DESCRIPTION
**Pull request by icewind1991**
Make sure we keep the cache in a consistent state

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
:+1: makes sense. I remember having tried this a while ago when investigating concurrency issues.

**Comment by PVince81** [comment]
Looks like CI is having trouble with sqlite ? @icewind1991

**Comment by icewind1991** [comment]
jenkins happy again -> merging

**Comment by icewind1991** [comment]
@karlitschek backport to 8.2?

**Comment by karlitschek** [comment]
please backport

**Comment by icewind1991** [comment]
8.2: #20159

**Pull request merged**
