### PR TITLE
Conditional Logging target logfile for shared_secret and users

### PR DESCRIPTION
**Pull request by mmattel**
## Description

Conditional Logging:
This PR adds the ability to define the logfile not only for ``apps``, but also for ``shared_secret`` and ``users``.

When preparing for PR #30406, I saw this missing. You also need to read the documentation carefully to get this. Naturally you would like to have a logfile for a conditional logging block, not only for ``apps``.

## Related Issue

None

## Motivation and Context

Usability

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

A documentaion PR is on the way which includes not only this change but also an improved readbility of conditional logging.

@PVince81 FYI

### CODE REVIEW

**Comment by PVince81** [comment]
@sharidas please review as you have more understanding of this piece which you improved recently

**Comment by DeepDiver1975** [comment]
please fix code cov

**Comment by mmattel** [comment]
@phil-davis mentioned in https://github.com/owncloud/core/pull/30406#pullrequestreview-94749963 that extending unit-tests is to be discussed. He also noted in https://github.com/owncloud/core/pull/30406#issuecomment-363819562 that in case "someone" being able to will cover that.

**Review by sharidas — APPROVED** [review]
Looks fine to me :+1:

**Comment by mmattel** [comment]
@sharidas 
I updated the commit and solved the conflict because of recently merged https://github.com/owncloud/core/pull/30418

**Comment by sharidas** [comment]
@mmattel I have tried to use the change on my master branch :)

**Comment by mmattel** [comment]
Our beloved Jenkins... : Test execution failed: hudson.AbortException: missing workspace

**Comment by phil-davis** [comment]
It was restarted this morning - killed stuff that was in progress.

**Comment by mmattel** [comment]
@ownclouders rebase please

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
The automated rebase is ineffective at triggering CI again because there are no new commits in ``master`` - so the rebase is effectively a NOOP.
It needs something else merged to ``master`` or some other trickery to force a rebase!

**Comment by mmattel** [comment]
Help please...

**Comment by sharidas** [comment]
@mmattel Let me help you

**Comment by sharidas** [comment]
@mmattel The CI is in progress.

**Comment by mmattel** [comment]
Glory 😄 
@sharidas if it gets merged, I will create a backport

**Pull request merged**
