### PR TITLE
use the cache for trash listing

### PR DESCRIPTION
**Pull request by icewind1991**
Large speedup when listing a large trashbin.

Speeds up trying to list a trashbin with 20k+ entries from timing out after 2minutes to ~4.5s

Afaik the trashbin has been in the cache for many releases by now

cc @schiesbn @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by schiesbn** [comment]
Actually I thought that I changed this already for a long time. Thanks @icewind1991 for spotting it! Didn't tested it but code changes look good :+1:

**Comment by PVince81** [comment]
:-1: try deleting a subdirectory, all entries have file ids instead of names in the web UI

**Comment by icewind1991** [comment]
> :-1: try deleting a subdirectory, all entries have file ids instead of names in the web UI

Fixed

**Comment by PVince81** [comment]
- [x] TEST: deleted files
- [x] TEST: deleted folder on first level trash
- [x] TEST: deleted subfolder appearing on first level trash
- [x] TEST: deleted file/folder with same name in trash

**Comment by PVince81** [comment]
- [x] TEST: restoring files/folders (for "original location" part)
- [x] TEST: with encryption (just in case)

Looks fine :+1:

**Pull request merged**
