### PR TITLE
Remove old unused private utility method isSharingDisabledForUser

### PR DESCRIPTION
**Pull request by PVince81**
See https://github.com/owncloud/core/pull/31819#issuecomment-398028939

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
You will need to burn the unit tests also in
tests/lib/UtilTest.php

**Comment by PVince81** [comment]
:fire:burnt and squashed

**Review by phil-davis — APPROVED** [review]
Assuming CI passes.

**Comment by phil-davis** [comment]
I suspect this will "break the internet" because I just used this method in #31816 "can_share capability".
I should have modified that PR to use the newer/proper method. I will have a look...

**Comment by PVince81** [comment]
how dare you use private APIs :wink:

**Comment by phil-davis** [comment]
I wasn't me, my IDE found it for me.
"Always deflect blame to the IDE" :stuck_out_tongue:

**Comment by phil-davis** [comment]
Extra commit added to cleanup "capabilities" crud. Let's see what CI  thinks.

**Comment by phil-davis** [comment]
Backport ``stable10`` is in PR #31824

**Pull request merged**
