### PR TITLE
collect javascript code coverage

### PR DESCRIPTION
**Pull request by patrickjahns**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by individual-it — APPROVED** [review]

**Comment by PVince81** [comment]
not sure if the report works correctly: https://codecov.io/gh/owncloud/core/pull/30730/changes and https://codecov.io/gh/owncloud/core/pull/30730/src/apps/comments/js/commentstabview.js don't show me which parts of the file are not covered properly.

**Comment by DeepDiver1975** [comment]
> not sure if the report works correctly: https://codecov.io/gh/owncloud/core/pull/30730/changes and https://codecov.io/gh/owncloud/core/pull/30730/src/apps/comments/js/commentstabview.js don't show me which parts of the file are not covered properly.

looks like the reports need a cleanup step - usually done by the codecov bash script ... needs research

**Comment by patrickjahns** [comment]
> looks like the reports need a cleanup step - usually done by the codecov bash script ... needs research
If you can trust the codecov script - the fixes where applied:
https://drone.owncloud.com/owncloud/core/4727/29

If you check the build files (tag `#javascript`) it should work
https://codecov.io/gh/owncloud/core/commit/def6dc5d7e7e2356b8395269e8c63d2da71851aa/build

@DeepDiver1975 
contact codecov support?

**Comment by PVince81** [comment]
@patrickjahns please backport

**Comment by patrickjahns** [comment]
Will do once #30728 is sorted out

**Comment by phil-davis** [comment]
Backport ``stable10`` include in PR #30760

**Pull request merged**
