### PR TITLE
Fix visual checkbox issue

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
When the checkbox was checked, reloading the whole page would unmark the checkbox (the right state was kept in the server)

## Related Issue
https://github.com/owncloud/enterprise/issues/3036

## How Has This Been Tested?
1. Mark the checkbox. Reload the page. Make sure the checkbox is checked
2. Unmark the checkbox. Reload the page. Make sure the checkbox is unchecked
3. Mark the checkbox again. Reload the page. Make sure the checbox is checked

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by jvillafanez** [comment]
Backport in https://github.com/owncloud/core/pull/34168

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by phil-davis** [comment]
@jvillafanez backport-request label is set - backporting?

**Comment by jvillafanez** [comment]
The backport is already linked (https://github.com/owncloud/core/pull/34167#issuecomment-455086931) but not merged yet.

**Pull request merged**
