### PR TITLE
[stable10] Adding repair step for sub share

### PR DESCRIPTION
**Pull request by sharidas**
Adding repair step for sub share.
When share table due to some magic gets
duplicate entries ( except the id or primary
key ), then this repair step comes for rescue.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Remove the duplicate entries from the `share` table which can cause exception described in the issue.

## Related Issue

https://github.com/owncloud/core/issues/27990

## Motivation and Context

For some magical reason, if the share table gets populated with duplicate entries then we would have to remove the duplicate entry. Keeping the row with minimum id. Else exception would be thrown as mentioned in the issue.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sharidas** [comment]
Backported from PR: https://github.com/owncloud/core/pull/30186

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by jvillafanez** [comment]
It doesn't seem to be working.
```
mysql> select * from share;
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+------------+
| id | share_type | share_with | uid_owner | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token | mail_send | share_name |
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+------------+
|  1 |          1 | group1     | admin     | admin         |   NULL | folder    | 60          | NULL        |          60 | /test1      |          31 | 1523863967 |        0 | NULL       | NULL  |         0 | NULL       |
|  2 |          2 | user1      | admin     | admin         |      1 | folder    | 60          | NULL        |          60 | /test1      |           0 | 1523863967 |        0 | NULL       | NULL  |         0 | NULL       |
|  3 |          2 | user2      | admin     | admin         |      1 | folder    | 60          | NULL        |          60 | /test1_mine |          31 | 1523863967 |        0 | NULL       | NULL  |         0 | NULL       |
|  4 |          2 | user2      | admin     | admin         |      1 | folder    | 60          | NULL        |          60 | /test1_mine |          31 | 1523863967 |        0 | NULL       | NULL  |         0 | NULL       |
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+------------+
4 rows in set (0.00 sec)
```
```
mysql> select id, parent, count(*) from share where share_type = 2 group by parent, id, share_with;
+----+--------+----------+
| id | parent | count(*) |
+----+--------+----------+
|  2 |      1 |        1 |
|  3 |      1 |        1 |
|  4 |      1 |        1 |
+----+--------+----------+
3 rows in set (0.00 sec)
```
```
mysql> select id, parent, count(*) from share where share_type = 2 group by parent, id, share_with having count(*) > 1;
Empty set (0.00 sec)
```

**Comment by PVince81** [comment]
@sharidas please check

**Comment by sharidas** [comment]
The issue was caused because of 'group by id' in the query. When this is removed, the duplicate shares are removed. Also when there are duplicate sub shares, the result is not empty.

**Pull request merged**
