### PR TITLE
fixing setting page titles

### LINKED ISSUE #16451: Website title stays just »ownCloud« in some sections of the web app
In the Files app for example the title changes to »Files - ownCloud« as it should. This doesn’t happen though in the Apps management, Personal, Admin, Users and Help. The titles should be changed though to reflect our pattern:
> [App/Section] - ownCloud

E.g
> Apps - ownCloud
> Personal - ownCloud

And so on.

cc @owncloud/designers @schiesbn

### PR DESCRIPTION
**Pull request by th3fallen**
resolves https://github.com/owncloud/core/issues/16451

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by th3fallen** [comment]
actually fixes all cases except App's page, will investigate and solve in seperate pr

**Comment by DeepDiver1975** [comment]
@jancborchardt  please test

**Comment by jancborchardt** [comment]
Good stuff, thank you! :+1: 

Would be cool if you can fix the Apps mgmt title as well. :)

**Pull request merged**
