### PR TITLE
[stable9] Fix download spinner to work with CSS styles

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/22846 to stable9

Please review @rullzer @MorrisJobke @icewind1991 @schiesbn @nickvergessen @SergioBertolinSG

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by SergioBertolinSG** [comment]
:+1:

Tested with chrome, firefox and safari on OS X and edge in windows.

**Comment by PVince81** [comment]
- [ ] pending backport confirmation @karlitschek

**Comment by rullzer** [comment]
:+1:

**Comment by karlitschek** [comment]
backport makes sense :+1:

**Pull request merged**
