### PR TITLE
Birthday calendar should never have write acl

### LINKED ISSUE #24154: Can create events in contacts_birthday calendar
### Steps to reproduce
1. Use calendar app
2. Add a new event

### Expected behaviour
Calendar should not be selectable at all

### Actual behaviour
200

Also happens on 9.0

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #24154

@nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
works :+1:

**Comment by schiesbn** [comment]
tested, works as expected :+1:

**Comment by DeepDiver1975** [comment]
@karlitschek backport requested

**Comment by karlitschek** [comment]
yep. definitely backport 👍

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Ping

**Comment by DeepDiver1975** [comment]
@MorrisJobke https://github.com/owncloud/core/pull/24163

**Pull request merged**
