### PR TITLE
Allow file upload when storage quota is unlimited

### PR DESCRIPTION
**Pull request by labkode**
Thanks to @IATkachenko, who reported this issue from the CERNBox 9 prototype.

### CODE REVIEW

**Comment by labkode** [comment]
MIT licensed

**Comment by PVince81** [comment]
Strange, I thought this was fixed already 👍 

Mind providing steps to reproduce to find out about the exact scenario ?

It is possible that this bug was fixed in another location on ownCloud, not sure if CERNBox took that fix.
The test scenario might help identify that.

**Comment by labkode** [comment]
Sure.

Your storage implementations return a numeric value for free space or SPACE_UNKOWN for the **free_space** function.

```
grep -r free_space /var/www/html/core
````

Our implementation returns SPACE_UNLIMITED.

To reproduce, just change the return value to SPACE_UNLIMITED in the storage back-end you are using in the **free_space** call and try to upload a file (I tried with files of some mb).

We always branch CERNBox from stable branches, however this time we branched with the version-10.0.0alpha until the final production version arrives this month.

The good news if that the set of patches we had in the past was drastically reduced from migration to 9 and more now to 10. Good job 👍

**Comment by PVince81** [comment]
Ok understood. So far in ownCloud we didn't have any storage returning SPACE_UNLIMITED which explains why we didn't find this issue before.

In the mentioned context, the change makes sense 👍

**Pull request merged**
