### PR TITLE
allow html in claim and use htmlname in layout

### LINKED ISSUE #30881: Themes getHTMLName not used for layout.*.php
Admins want to add a link to the name that is shown next to the logo. Currently the themes getName is used (also for the basic auth realm) but we actually already have a getHTMLName that should be used in the layout.guest.php and layout.user.php files.

### PR DESCRIPTION
**Pull request by butonic**
fixes https://github.com/owncloud/core/issues/30881

also updated the custom theme to use html

### CODE REVIEW

**Comment by PVince81** [comment]
please fix the conflicts

**Comment by butonic** [comment]
split example / theme to new pr in dedicated repo: https://github.com/owncloud/theme-example/pull/7

**Comment by butonic** [comment]
maybe @ChrisEdS can have a quick look?

**Comment by butonic** [comment]
@PVince81 please take over

**Comment by PVince81** [comment]
will need release notes in case an existing claim already contains special chars that now need to be escaped like `<` and `>`

**Comment by PVince81** [comment]
@pmaier1 agree with this change ?

**Comment by felixheidecke** [comment]
I guess I am requested by accident?

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@butonic please backport to stable10

**Comment by butonic** [comment]
@PVince81 @micbar how do we track backport requests? only via the label? I won't have time for this.

**Comment by micbar** [comment]
@butonic Yes, that is the only way.

**Pull request merged**
