### PR TITLE
Add hint for troubleshooting MS Word previews

### PR DESCRIPTION
**Pull request by ghost**
Anchor for the auto generated documentation part needs https://github.com/owncloud/documentation/issues/835

Should be also backported to stable7

### CODE REVIEW

**Comment by RealRancor** [comment]
MIT licenced

**Comment by LukasReschke** [comment]
:+1: if @MorrisJobke can confirm that this works properly :)

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@LukasReschke Yes it will.

**Comment by MorrisJobke** [comment]
stable7 #14078

**Comment by MorrisJobke** [comment]
stable8 #14080

**Pull request merged**
