### PR TITLE
check whether index is set before using it

### LINKED ISSUE #24228: Undefined index: extension at /var/www/owncloud/lib/private/installer.php#272
### Steps to reproduce
1. Have a bookmarks app 0.6 from oC 8.2 installed which got removed during the upgrade to 9.0.x
2. Get new version 0.7 of the bookmarks app for 9.0.x offered
3. Click on "enabled" within the oC internal appstore
4. See that the bookmarks app have been successfully installed
5. Have a look at the owncloud.log

### Expected behaviour
No log entry about an undefined index should be logged

### Actual behaviour
Log entry about an undefined index is logged. The entry is triggered from:

https://github.com/owncloud/core/blob/v9.0.1/lib/private/installer.php#L272

~~According to https://github.com/owncloud/core/issues/20242 this should have been already fixed with oC9, 8.2.1 and 8.1.5 with https://github.com/owncloud/core/pull/20196~~

### Server configuration
**PHP version:** 7.0.x

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** Upgraded from oC 8.2.3

**Where did you install ownCloud from:** manual tar.bz2 archvie

**Signing status (ownCloud 9.0 and above):** No errors have been found.

#### ownCloud log (data/owncloud.log)
```
{"reqId":"8CcuXiPTXgmWTBY0Rpmq","remoteAddr":"xxx","app":"PHP","message":"Undefined index: extension at \/var\/www\/owncloud\/lib\/private\/installer.php#272","level":3,"time":"2016-04-25T06:18:38+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"xxx"}
```

### PR DESCRIPTION
**Pull request by blizzz**
Fixes #24228 

Please test / review @RealRancor @nickvergessen @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
@blizzz Backport?

cc @karlitschek

**Comment by karlitschek** [comment]
great. please backport :+1:

**Comment by MorrisJobke** [comment]
@blizzz Could you prepare the backport PRs

**Comment by blizzz** [comment]
@MorrisJobke on it just these seconds

**Comment by blizzz** [comment]
### backports

**stable9**: https://github.com/owncloud/core/pull/24282
**stable8.2**: https://github.com/owncloud/core/pull/24283
**stable8.1**: https://github.com/owncloud/core/pull/24284

**Comment by shaneonabike** [comment]
I am still getting an error after the latest release came out `Undefined index: version at /var/www/owncloud/lib/private/Installer.php#405`

**Pull request merged**
