### PR TITLE
Updating example theme

### PR DESCRIPTION
**Pull request by michaelstingl**
## Description
Example Theme:
- update year in footer to 2017
- update link to 10.0 docs

## Related Issue
https://github.com/owncloud/enterprise/issues/1864#issuecomment-282781137

## Motivation and Context
2016 is outdated and 9.2 version is confusing

## How Has This Been Tested?
Set `'theme' => 'example',` in `config.php`, then log in as new user
1. Check `firstrunwizard` links
2. Check themed footer

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by davitol** [comment]
There are many other files that should be updated

e.g.

```
grep -ri 'server/9.2' *
core/doc/admin/release/index.html:<li><a class="reference external" href="https://doc.owncloud.org/server/9.2/user_manual/">ownCloud User Manual</a></li>
core/doc/admin/release/_sources/index.txt:.. _`ownCloud User Manual`: https://doc.owncloud.org/server/9.2/user_manual/
core/doc/admin/release/_sources/issues/general_troubleshooting.txt:   https://doc.owncloud.org/server/9.2/developer_manual/bugtracker/index.html
core/doc/admin/release/_sources/maintenance/restore.txt:#. Your custom theme files, if you have any. (See `Theming ownCloud <https://doc.owncloud.org/server/9.2/developer_manual/core/theming.html>`_)
core/doc/admin/release/_sources/maintenance/backup.txt:#. Your custom theme files, if you have any. (See `Theming ownCloud <https://doc.owncloud.org/server/9.2/developer_manual/core/theming.html>`_)
core/doc/admin/release/_sources/enterprise_file_management/files_tagging.txt:<https://doc.owncloud.com/server/9.2/user_manual/files/access_webgui.html>`_ in
core/doc/admin/release/issues/general_troubleshooting.html:<p>If you can&#8217;t find a solution, please use our <a class="reference external" href="https://doc.owncloud.org/server/9.2/developer_manual/bugtracker/index.html">bugtracker</a>. You can generate a
core/doc/admin/release/maintenance/restore.html:<li>Your custom theme files, if you have any. (See <a class="reference external" href="https://doc.owncloud.org/server/9.2/developer_manual/core/theming.html">Theming ownCloud</a>)</li>
core/doc/admin/release/maintenance/backup.html:<li>Your custom theme files, if you have any. (See <a class="reference external" href="https://doc.owncloud.org/server/9.2/developer_manual/core/theming.html">Theming ownCloud</a>)</li>
core/doc/admin/release/enterprise_file_management/files_tagging.html:<p>See <a class="reference external" href="https://doc.owncloud.com/server/9.2/user_manual/files/access_webgui.html">Tagging Files</a> in
themes/example/defaults.php:		return $this->getDocBaseUrl() . '/server/9.2/go.php?to=' . $key;
```

**Comment by PVince81** [comment]
Will only work properly once https://github.com/owncloud/documentation/issues/2765 is done

**Comment by settermjd** [comment]
I'm hoping to have that ticket done either today, or at the latest of this Friday.

**Comment by phisch** [comment]
Ideally we close #27162 before we do this, else we run into conflicts here.
I'll create a new PR with @michaelstingls changes and @davitols mentioned other instances once #27162 is done.

**Comment by DeepDiver1975** [comment]
> #27162

merged ... go go go :wink:

**Comment by VicDeo** [comment]
`core/doc` is not related to core as it seems at the first glance.
It is built while baking a package from documentation repo.

**Comment by phisch** [comment]
@michaelstingl's changes for the app theme are here: https://github.com/owncloud/core/pull/27338
@davitol's changes will be in another PR in a few minutes.

**Comment by phisch** [comment]
Like @VicDeo said, @davitol's findings are tracked in owncloud/documentation#2765.
So no need for another PR here.

Since @michaelstingl's changes are in #27338, this PR can be closed.

**Comment by fcturner** [comment]
Small question: the documentation for OC10 [now states](https://github.com/owncloud/documentation/blob/master/developer_manual/core/theming.rst#appinfoinfoxml):

> The value of the `id` element needs to be the name of your theme’s folder. We recommend that it always be prefixed with `theme-`. The main reason for doing so, is that it is alphabetically sorted in a terminal when  handling app folders.

So shouldn't the example theme be named `theme-example` instead of `example-theme`?

**Comment by fcturner** [comment]
(And 
_We recommend that it always be prefixed with `theme-`_ 
should be 
_We recommend to let it be prefixed by `theme-` always_ 
for proper English :wink: )

**Comment by phisch** [comment]
@fcturner you are right, i'll take care of that!

**Comment by fcturner** [comment]
:+1:

**Pull request closed without merging**
