### PR TITLE
[stable9] Contacts API: replace raw image data with url

### PR DESCRIPTION
**Pull request by georgehrke**
backport of #25081 

for some reason it automatically downloads the image
@DeepDiver1975 Can you take a look at this? ^

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> for some reason it automatically downloads the image
> @DeepDiver1975 Can you take a look at this? ^

please compare the http response headers - I assume a different disposition header is sent to the browser

**Comment by georgehrke** [comment]
Master does this as well, never mind then

**Comment by georgehrke** [comment]
please review @DeepDiver1975 @PVince81 @ChristophWurst

**Comment by georgehrke** [comment]
TODO:
-  [ ] should include https://github.com/owncloud/core/pull/25215/files/7f01e49998ef2af68817bf70a4afd1999a654f06#r68037612

**Comment by DeepDiver1975** [comment]
@Gomez @ChristophWurst mind testing mail app with this patch for stable9? THX

**Comment by Gomez** [comment]
tested and works :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
