### PR TITLE
Fixes issues when renaming favorite file

### LINKED ISSUE #12944: Can not rename folder twice in Favorites
### Steps to reproduce
1. create a folder "test" 
2. tag "test" as favorite
3. go into "test" and create a subfolder "aaa"
4. mark "aaa" as favorite
5. click "Favorites" button on the sidebar
6. rename "aaa" into "bbb" in the favorites list
7. rename "bbb" into "ccc" in the favorites list

### Expected behaviour
by step 6: the folder is renamed and star icon is still yellow
by step 7: the folder can be renamed

### Actual behaviour
by step 6: the folder is renamed but star icon tunes to grey
by step 7: the folder can not be renamed, because "bbb could not be renamed as it has been deleted"

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** owncloud 8 git master, commit 5c6e08213e6ed52517f9f729ae91a2973f09c182

**Updated from an older ownCloud or fresh install:** 

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)

```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 34.0.5

**Operating system:** ubuntu 13.10

#### ownCloud log (data/owncloud.log)
```
{"reqId":"5c00793d3b44a659285ec93879585395","remoteAddr":"192.168.1.34","app":"core","message":"unable to rename, file does not exists : files_encryption\/keys\/isittrue\/aaa\/","level":3,"time":"2014-11-27T00:25:25+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/rename.php?dir=%2Fisittrue&newname=bbb&file=aaa"}


```

### LINKED ISSUE #13215: star gone after rename a favorite folder
### Steps to reproduce
1. create a folder "test" 
2. tag "test" as favorite
3. rename "test" to "testtest"

### Expected behaviour
folder's name changed and the star icon stayed

### Actual behaviour
folder's name changed and the star icon is gone, but after refreshing the page, the folder is still marked as favorite

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** owncloud 8 git master

**Updated from an older ownCloud or fresh install:** 

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 34.0.5

**Operating system:** ubuntu 13.10

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/13215 (star disappears after rename)
Fixes https://github.com/owncloud/core/issues/12944 (cannot rename file twice in favorite view)

Please review @icewind1991 @MorrisJobke @LukasReschke @nickvergessen

### CODE REVIEW

**Comment by PVince81** [comment]
Note: I know this is not the most elegant way to do it. In the future that "rename()" function should be moved to the ApiController or even removed completely and have the files app use WebDAV.
That would be out of scope for a bugfix.

**Comment by nickvergessen** [comment]
Can this have a test?

**Comment by PVince81** [comment]
- [ ] add unit test

**Comment by dttpy** [comment]
:+1:  tested, and works, but find another bug, see #13283

**Comment by PVince81** [comment]
@dttpy can you update the branch and test again ?

Fixes https://github.com/owncloud/core/issues/13283

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Works :+1: 

I tested all 3 scenarios and all work now.

**Comment by PVince81** [comment]
Sorry, pushed to the wrong branch. Please ignore.

@nickvergessen I have pushed/squashed unit tests

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
