### PR TITLE
use divs for header carets

### PR DESCRIPTION
**Pull request by phisch**
## Description
This switches out the header caret images with divs that are styled via css.

## Motivation and Context
This makes it possible to style each caret individually, rather than both by overwriting an image. Overwriting both by overwriting an image is still possible like this. So we got the best of both.

## How has this been tested?
Tested for the default and the enterprise theme. Both now look like expected. Screenshot for enterprise and default themes below.

## Screenshots (if appropriate):
Carets individually styled:
2017-05-19-152257_767x40_scrot

Default theme:
2017-05-19-153257_767x40_scrot

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Please list tested scenarios. Missing: retesting core theme and seeing that it still works.

**Comment by phisch** [comment]
Didn't mention, but it still works for the default theme, and will for all other themes:

2017-05-19-153257_767x40_scrot

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
js tests pass locally, merging

**Pull request merged**
