### PR TITLE
escape . in htaccess regex for CSS and JS HTTP headers

### PR DESCRIPTION
**Pull request by MorrisJobke**
fixes https://github.com/owncloud/core/issues/11496#issuecomment-68175097

Thanks @HannesSommer

cc @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
This is already properly documented for Nginx in the documentation repo.

**Comment by MorrisJobke** [comment]
cc @karlitschek Should this go into oc8?

**Comment by LukasReschke** [comment]
Makes sense :+1:

**Comment by karlitschek** [comment]
:+1: from my point of view

**Pull request merged**
