### PR TITLE
No CSRF check should be required for setup check

### LINKED ISSUE #18336: Error occurred while checking server setup after upgrade to OC 8.1.1
### Steps to reproduce
1. Upgrade from 8.0.5 to 8.1.1
2. Open Browser Developer Tools (Network tab or console)
2. Call Admin panel <HOST>/index.php/settings/admin

### Expected behaviour
No errors in admin panel:
<HOST>/index.php/settings/admin

### Actual behaviour
Call <HOST>/index.php/settings/admin
Shows the following Error:
"Error occurred while checking server setup
Please double check the installation guides ↗, and check for any errors or warnings in the log."

### Server configuration
**Operating system**:
CentOS

**Web server:**
Apache 2

**Database:**
MySQL

**PHP version:**
5.5.15

**ownCloud version:** (see ownCloud admin page)
8.1.1

**Updated from an older ownCloud or fresh install:**
Update from 8.0.5

**List of activated apps:**
* activity: 2.0.1
* calendar: 0.7.3
* contacts: 0.4.0.0
* encryption: 1.0.0
* files: 1.1.10
* files_pdfviewer: 0.7
* files_sharing: 0.6.2
* files_texteditor: 0.4
* files_trashbin: 0.6.3
* gallery: 0.6.1
* templateeditor: 0.1
* updater: 0.6

### Client configuration
Chrome (current)

**Operating system:**
Mac OS X

#### Web server error log
No logs

#### ownCloud log (data/owncloud.log)
No Logs

#### Browser log
The network tab or console:
"GET <HOST>/index.php/settings/ajax/checksetup 403 (Forbidden)"
If I open the url that is called via ajax I get an: ERR_TOO_MANY_REDIRECTS

### PR DESCRIPTION
**Pull request by mitar**
Fixes #18336.

### CODE REVIEW

**Comment by LukasReschke** [comment]
I'd rather prefer to see the actual bug fixed. Why is an invalid token or none sent?

**Comment by LukasReschke** [comment]
Also can you post how your HTTP request looks like?

**Comment by mitar** [comment]
Hm, now that I think more about this. It is probably normal that I get CSRF error if I try to open the URL check setup directly in the browser. But it should probably still not loop. I am not sure though why I was getting the error when opened in the admin itself. But it happens occasionally.

**Comment by LukasReschke** [comment]
>  But it should probably still not loop.

Yes. PR for that can be found at https://github.com/owncloud/core/pull/20807

> I am not sure though why I was getting the error when opened in the admin itself. But it happens occasionally.

Could you post the sent request here when it reappears? That way we can see why it fails.

**Comment by LukasReschke** [comment]
(closing this one for now since this is the wrong solution from my POV)

**Pull request closed without merging**
