### PR TITLE
[Stable8] Check if we have a proper fileinfo

### LINKED ISSUE #14390: OC\Files\Node\Node doesn't check it has a valid FileInfo object before working on it
### Problem
A method creates a new OC\Files\Node\Node, using a broken path
A method then calls OC\Files\Node\Node->getFileInfo()
```
public function getFileInfo() {
	if (!$this->fileInfo) {
		$this->fileInfo = $this->view->getFileInfo($this->path);
	}
	return $this->fileInfo;
}
```
which calls OC\Files\View->getFileInfo using the broken path
```
public function getFileInfo($path, $includeMountPoints = true) {
...
		$data = array();
		if (!Filesystem::isValidPath($path)) {
			return $data;
		}
...
```
which returns an empty array as a FileInfo object.

Now the Node object is going to call many different methods on an array and that will fail and break anything sitting on top of it.

Some examples of these methods
```
public function isMounted() {
	return $this->getFileInfo()->isMounted();
}
public function isShared() {
	return $this->getFileInfo()->isShared();
}
public function getMimeType() {
	return $this->getFileInfo()->getMimetype();
}
public function getMimePart() {
	return $this->getFileInfo()->getMimePart();
}
public function getType() {
	return $this->getFileInfo()->getType();
}
public function isEncrypted() {
	return $this->getFileInfo()->isEncrypted();
}
public function getMountPoint() {
	return $this->getFileInfo()->getMountPoint();
}
```

### Fix it in Node
* Check that we actually have a FileInfo object
* Throw an exception letting others know that things went sour

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #14437 and #14567 

Fix #14390 

@DeepDiver1975 @icewind1991 @MorrisJobke

### CODE REVIEW

**Comment by nickvergessen** [comment]
Fixes #14390

**Comment by icewind1991** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by oparoz** [comment]
The milestone is wrong as this is already in 8.0.1, but I don't see an 8.0.1 milestone

**Comment by MorrisJobke** [comment]
@oparoz Because there was some mixup with 8.0.1 release (it somehow got into the wild before the announcement) the 8.0.2 will be released soon with the stuff that should be in 8.0.1.

**Comment by MorrisJobke** [comment]
@oparoz I also updated the wiki page: https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by oparoz** [comment]
Ah, this explains why I was seeing the strange versioning :) Thanks!

**Pull request merged**
