### PR TITLE
[stable10] Always set headers

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport #31231

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

for 10.1.1

**Comment by benrubson** [comment]
Strangely enough, `owncloud-10.1.1.tar.bz2` from https://owncloud.org/download/ does not contain these modifications !

**Comment by patrickjahns** [comment]
@benrubson 
Please see the changelog for  10.1.1 https://github.com/owncloud/core/blob/stable10/CHANGELOG.md#1011 

It only contained a single change we deemed critical enough to release 10.1.1

Above PR is stell listed in the unreleased section

**Comment by benrubson** [comment]
Sorry for having misunderstood this @patrickjahns, and thank you very much for clarification 👍

**Pull request merged**
