### PR TITLE
Move tests/ to PSR-4

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Depends on https://github.com/owncloud/core/pull/24728

Last PSR-4 PR for tests, afterwards we are ready to go
@rullzer @ChristophWurst @MorrisJobke

### CODE REVIEW

**Comment by ChristophWurst** [comment]
#24728 is merged.

> This branch has conflicts that must be resolved

**Comment by nickvergessen** [comment]
Ready for review @rullzer

**Comment by ChristophWurst** [comment]
:+1: changes look good. Finally test class names end with 'Test', that was confusing before

**Comment by MorrisJobke** [comment]
👍

**Pull request merged**
