### PR TITLE
bool data type is not mapped to boolean for sqlite

### LINKED ISSUE #17671: [master] Migration issue
````
Doctrine\DBAL\DBALException: Unknown database type bool requested, OC\DB\OCSqlitePlatform may not support it.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #17671

### CODE REVIEW

**Comment by rullzer** [comment]
How do you want me to test this other than running the unit tests?

**Comment by MorrisJobke** [comment]
@rullzer Install with master on sqlite and add a table with such a column ;) Then upgrade and check if it is now correctly boolean ;)

**Comment by nickvergessen** [comment]
Can we have a test? :speak_no_evil:  :runner:

**Comment by DeepDiver1975** [comment]
> Can we have a test? :speak_no_evil: :runner:

Well - this happens in case there is a table in the db which was created outside of the scope ownCloud.

Do too sure if we should test something like this.

**Comment by PVince81** [comment]
I can't believe we never used bool in core :open_mouth:

**Comment by PVince81** [comment]
Tested as follows:

1. Append this in db_structure.xml in core:
```
	<table>

		<name>*dbprefix*testtable</name>

		<declaration>

		<field>
			<name>keyid</name>
			<type>integer</type>
			<default>0</default>
			<notnull>true</notnull>
			<unsigned>true</unsigned>
			<length>4</length>
			<autoincrement>1</autoincrement>
		</field>

		<field>
			<name>testboolfalse</name>
			<type>boolean</type>
			<default>false</default>
		</field>
		<field>
			<name>testbooltrue</name>
			<type>boolean</type>
			<default>true</default>
		</field>
		<field>
			<name>testboolempty</name>
			<type>boolean</type>
			<default>true</default>
		</field>

		</declaration>

	</table>
```
1. Setup OC on this branch
1. Increase version in version.php
1. Run the update

Tested with SQLite and MySQL :+1:

**Comment by MorrisJobke** [comment]
> I can't believe we never used bool in core :open_mouth:

Yes. We never used `bool` we used `boolean` with works ;)

**Comment by MorrisJobke** [comment]
If I change the test table of @PVince81 to `bool` the setup doesn't work anymore.

@DeepDiver1975 Can you have a look.

I get following message:

```
Error while trying to create admin user: Unknown column type "bool" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information. 
```

**Comment by MorrisJobke** [comment]
@DeepDiver1975 This is still broken. Please fix :)

**Comment by DeepDiver1975** [comment]
Yeah -  one day ....

**Comment by Xenopathic** [comment]
Well, we now use booleans in core. Perhaps it's a good time to brush off the dust on this PR? :smile:

**Comment by PVince81** [comment]
@DeepDiver1975 any update ?
(note: we don't use booleans any more now in core)

**Comment by DeepDiver1975** [comment]
Okay, guys - you are getting this wrong I guess - the intention of this pr is not to introduce bool as valid type in our xml db structure.

This wil 'only' fix the case that some existing table in the sqlite db is using a bool columns and the upgrade process will not fall apart.

**Comment by Xenopathic** [comment]
@DeepDiver1975 So is bool a valid type for our DB schema at all? Doctrine happily eats it, but we've found these bugs with it...

**Comment by DeepDiver1975** [comment]
> So is bool a valid type for our DB schema at all?

No idea :speak_no_evil:

**Comment by PVince81** [comment]
(D)efer, (K)ill, (R)evive ?

**Pull request closed without merging**
