### PR TITLE
ensure multiselect always receives an array when setting its value, f…

### PR DESCRIPTION
**Pull request by blizzz**
…ixes #18734

For reproduction steps see https://github.com/owncloud/core/issues/18734

Please test and review @owncloud/ldap @davitol @tkaufm @pierrejochem

@karlitschek backport request down to 8.1 – OK?

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport

**Comment by davitol** [comment]
:+1: WFM

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> please backport

@blizzz please submit backport prs - THX

**Comment by blizzz** [comment]
backports

stable8.2: https://github.com/owncloud/core/pull/21090
stable8.1: https://github.com/owncloud/core/pull/21091

**Pull request merged**
