### PR TITLE
Fix namespace conflict in OC.Encryption JS code

### PR DESCRIPTION
**Pull request by PVince81**
To test:
1. Enable encryption
2. Go to personal page without logging out to see the warning

Please review @oparoz @schiesbn

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/18098

**Comment by Xenopathic** [comment]
:+1:

**Comment by schiesbn** [comment]
works :+1:

**Comment by schiesbn** [comment]
@karlitschek I would suggest to backport it for 8.1.2

**Comment by PVince81** [comment]
It's not so critical, I'd evaluate as sev-low.

**Comment by karlitschek** [comment]
No backport if not critical

**Pull request merged**
