### PR TITLE
Move federation app to PSR-4

### PR DESCRIPTION
**Pull request by nickvergessen**
@rullzer @schiesbn

### CODE REVIEW

**Comment by rullzer** [comment]
Namespace trouble it seems: 

```04:05:49 Error: Class 'OCA\Federation\AppInfo\Application' not found in /var/lib/jenkins/jenkins-slave/workspace/server-master-linux-php7-ci/database/sqlite/label/SLAVE/apps/federation/appinfo/install.php:22```

**Comment by nickvergessen** [comment]
Fix is in https://github.com/owncloud/core/issues/24531

**Comment by nickvergessen** [comment]
Rebased

**Comment by rullzer** [comment]
:+1:

**Comment by ChristophWurst** [comment]
> This branch has conflicts that must be resolved

Apart from that :+1:

**Comment by nickvergessen** [comment]
Rebased again

**Pull request merged**
