### PR TITLE
Make new checkbox style accessible for screenreaders

### LINKED ISSUE #19898: Accessibility Bug for 8.2 UI
The web UI for 8.2 has accessibility bug where you can't activate a lot of elements using tab keys. For example
1. Any check box in settings
Also, the check boxes don't report as a check box for screen readers.
2. Can't browse and open files/folder with using tab/shift+tab key
This is important for any user who uses screen readers or anyone who can't use mouse.
It'd be great if the accessibility bug can be fixed for the new design.
Please check out Web Content Accessibility Guidelines (WCAG) 2.0.
http://www.w3.org/TR/WCAG20/
Using WAI-ARIA
http://www.w3.org/TR/wai-aria/usage
Definition of Roles
http://www.w3.org/TR/wai-aria/roles
Definitions of States and Properties
http://www.w3.org/TR/wai-aria/states_and_properties

### PR DESCRIPTION
**Pull request by Henni**
fixes #19898 

we probably want to backport this to stable8.2

cc @jancborchardt @jsl303

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: makes sense, checkboxes still work

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@karlitschek Can we please backport this to stable8.2

**Comment by karlitschek** [comment]
please backport

**Comment by Henni** [comment]
Backport at #20457 
Please take a look and review.

**Comment by jancborchardt** [comment]
@Fmstrat please test this, as it fixes your issue https://github.com/owncloud/core/issues/20448

**Pull request merged**
