### PR TITLE
Reduce the elapsed time of the various Travis jobs

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Pull out sauce_connect from the global addons and put it just in the selenium jobs that need it. The addons section is not able to have a global section, and then add to it in each matrix include, so YAML anchors http://www.yaml.org/spec/1.2/spec.html#id2785586 are used to minimize code duplication.
This makes each of the other "little" jobs in the matrix run >30 seconds faster, as they do not waste time connecting to sauce labs and disconnecting.

2) Make each of the before_install, install, before_script and script lines only execute if it is really a step for the given combination of environment variables. This saves a bit of time e.g. for cases like when $TEST_DAV=0 so there is no point even bothering to do "make".

3) Add a CRON_ONLY environment variable to flag jobs in the matrix to only be run when in a Travis cron job. When a build is run as a Travis cron job, Travis kindly sets the env var $TRAVIS_EVENT_TYPE to 'cron'.
I added back older browser/OS combinations that could be just run in the Travis cron job. I also made the chrome latest-1 to be cron-only. Thus there are only 3 browsers that will be run for every PR... - chrome latest, latest working Firefox and IE on Win7.

4) Put the selenium jobs at the top. That way they start straight away, taking 3 job slots out of 5. The other 2 jobs slots will run the other quicker jobs, which will all end up finishing in about the time of the 3 parallel selenium jobs. We will get an example of total elapsed time when this PR builds.

## Related Issue
#27858 

## Motivation and Context
Optimize the elapsed time for a regular Travis build/test run, thus giving quicker feedback to devs.

## How Has This Been Tested?
Running test runs in a separated forked repo.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
A regular cron job (e.g. daily) to fully build/test master can be enabled by logging in to the ownCloud Travis account and going to settings and scolling down the bottom to the cron section and enabling it.
Then we need to see where the result will be visible to someone if there is a build/test failure. There would not be much point running it every day if nobody reacted to the result.

**Comment by phil-davis** [comment]
Travis elapsed time 13min 21sec, and it was only running 4 jobs in paralell much of the time, as there was a prior user_ldap build that had a single job going. It should be in the 11-13 minute range, the time of the longest single selenium job. If (when) a single selenium job gets too long, then we can look at splitting the set of features into suites that can be run as separate jobs to increase the parallelism a bit.

**Comment by DeepDiver1975** [comment]
cron is enabled in travis - running daily - let's see ....

...even the cron only jobs take close to 2 minutes .... can we get this further down?
... in addition: the jobs which are executed on every build sum up quite well ... can we reduce the configs we test?

THX a lot - really awesome ... 

bildschirmfoto von 2017-05-16 10-18-07

**Comment by phil-davis** [comment]
And apologies for the repeated logical conditions in various bash if tests. Travis runs each "step" of the before_install, script etc sections as its own command, underneath the controlling process that does all the steps. So each step can see all the env vars, but it cannot export env vars back up to the parent to become available to the next step.
So an attempt to do:
```
  - if [ '$TC' = 'selenium' ] && [ ! -z "$SAUCE_USERNAME" ] && [ ! -z "$SAUCE_ACCESS_KEY" ] && { [ '$CRON_ONLY' = '0' ] || [ '$TRAVIS_EVENT_TYPE' = 'cron' ]; }; then export TEST_SELENIUM='1'; fi

```
And then use just $TEST_SELENIUM multiple times in later lines - it is doomed to failure :(

**Comment by phil-davis** [comment]
The matrix entries that would use Sauce Labs if they actually do anything, need to have sauce_connect specified. Travis does the sauce_connect magic itself, so there is nowhere to put a test to only do the sauce_connect if "that big long bash test condition" is true. So each of those waste time doing a Sauce connect and disconnect. I did not see a way around that.

Even better would be for Travis to not even start matrix entries that are going to do nothing. But that needs Travis to set the env vars first, then call a user hook that can decide if each matrix entry should bother to run. Unfortunately there have been a few people asking for ways to do this kind of thing, but no functionality yet from Travis that I could see.

**Comment by phil-davis** [comment]
That last commit reduced the time from:
https://travis-ci.org/owncloud/core/builds/232711291?utm_source=github_status&utm_medium=notification elapsed 13min 21sec and total 49min 12ec
to:
https://travis-ci.org/owncloud/core/builds/232823471?utm_source=github_status&utm_medium=notification elapsed 10min 8sec and total 43min 25sec

That is all I can think of to optimize at this level.

@DeepDiver1975 the Travis cron job will build from master, I expect. So actually this needs to be merged in order to see that the Travis cron job will indeed run all the jobs in the build matrix.

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
