### PR TITLE
Copy Etag header to OC-Etag for sabre calls

### PR DESCRIPTION
**Pull request by PVince81**
@DeepDiver1975 @icewind1991 

Fix for https://github.com/owncloud/core/issues/9005

### CODE REVIEW

**Comment by PVince81** [comment]
Note, this is only possible with Sabre 2.1 thanks to its revamped plugin architecture.

**Comment by PVince81** [comment]
CC @guruz @ogoffart

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by DeepDiver1975** [comment]
@guruz @ogoffart an you test this please? THX

**Comment by guruz** [comment]
:+1: Tested and confirmed that this patch works while the previous iteration by @DeepDiver1975 didn't..
I tested 15 MB chunked file with parallel chunks enabled.

**Comment by PVince81** [comment]
Cool. Let me click the green button then.

**Comment by PVince81** [comment]
Note: this fix cannot be backported because the Sabre version in 8.0.x didn't support overwriting headers.

**Pull request merged**
