### PR TITLE
fix encryption stream for 2.0

### PR DESCRIPTION
**Pull request by jknockaert**
port some more code from #14383 in an attempt to fix remaining issues with #15234
@schiesbn could you check this code? I wrote it in a hurry and didn't do any testing

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jknockaert Jenkins is crying because 3rdparty submodule does not match

````
00:01:59.228 .......................................................PHP Fatal error:  Declaration of OC\Connector\Sabre\Principal::findByUri() must be compatible with Sabre\DAVACL\PrincipalBackend\BackendInterface::findByUri($uri) in /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/connector/sabre/principal.php on line 37

**Comment by DeepDiver1975** [comment]
@jknockaert Thanks a lot for this patch - much appreciated!

**Comment by jknockaert** [comment]
@DeepDiver1975 Thanks for pointing out. I'm trying to fix that (returning) issue right now.

**Comment by DeepDiver1975** [comment]
@jknockaert as you wrote you coded that in a hurry - we can take that burden from you and continue from now if you like :wink:

**Comment by jknockaert** [comment]
@DeepDiver1975 honestly I can't get rid of the 3rdparty thing. Did a rebase, solved obscure merge conflicts; still it comes back.

**Comment by DeepDiver1975** [comment]
@jknockaert no worries - I'll take over ....

**Comment by DeepDiver1975** [comment]
I'll resubmit these changes asap to a new branch ...

**Comment by DeepDiver1975** [comment]
THX once more @jknockaert

**Comment by jknockaert** [comment]
@DeepDiver1975 ok, please let me know after you resubmit this PR, I already found a small mistake...

**Pull request closed without merging**
