### PR TITLE
Store installed at version

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
Stores a key in the app config with the originating version of owncloud so we know the upgrade history (to some extent)

## Motivation and Context
Useful for bug tracking at least

## How Has This Been Tested?
manual reinstalls. and testing without this key being present

## Screenshots (if appropriate):
screen shot 2018-01-15 at 12 46 28
screen shot 2018-01-15 at 12 46 06

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Rename to "first_install_version" because "origin" is a bit confusing.

Ideal would be a way to store a value for every upgrade step, but that would require more complex code.

This PR is fine otherwise.

**Comment by tomneedham** [comment]
updated to implement comments

**Comment by tomneedham** [comment]
@ownclouders rebase please

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
The output of ``occ status`` now has the first_install_version line:
```
./occ status
  - installed: true
  - first_install_version: unknown
  - version: 10.0.6.1
  - versionstring: 10.0.6
  - edition: Enterprise
```
the ``status.feature`` test code parsed that output to find out the current version of the installation (and then use it in the comparison with the JSON received from the ``status.php`` endpoint).

so the parsing of the lines of output needed adjusting.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
conflicts

moving to triage to schedule time to finish this

**Comment by PVince81** [comment]
rebased and conflict solved

**Comment by PVince81** [comment]
Fixed code style, squashed into first commit. Rebased onto master. Expecting greenery now.

**Comment by PVince81** [comment]
@tomneedham please backport

**Pull request merged**
