### PR TITLE
[stable8.1.] Make update server URL configurable

### PR DESCRIPTION
**Pull request by LukasReschke**
Currently testing the updates is a big problem and not really super easy possible. Since we now have a new updater server we should also make this configurable so that people can properly test updates.

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by blizzz** [comment]
looks good :+1:

**Comment by PVince81** [comment]
would be good to get  core-ci-linux/database=sqlite,label=SLAVE  passing here at least

**Comment by PVince81** [comment]
Rebased

**Comment by PVince81** [comment]
where did the usual sqlite/mysql and co tests go ? Jenkins ate them ??

**Comment by nickvergessen** [comment]
after too many errors they are not started anymore, this always was the case iirc

**Comment by PVince81** [comment]
Anyway, code is not DB related, let's merge...

**Pull request merged**
