### PR TITLE
Revert "Allow application-specific favicons"

### PR DESCRIPTION
**Pull request by LukasReschke**
Reverts owncloud/core#13435 which introduced a regression as can be seen at https://github.com/owncloud/core/pull/13435#issuecomment-73913689

### CODE REVIEW

**Comment by LukasReschke** [comment]
Either somebody needs to fix this or we revert it – it's a regression.

**Comment by VicDeo** [comment]
argh. Is this one that makes unit tests to fail now?

**Comment by LukasReschke** [comment]
Nope. This only spits errors in the error log ;-)

**Comment by LukasReschke** [comment]
Replaced by https://github.com/owncloud/core/pull/14121 - thanks a lot @Zillode

**Pull request closed without merging**
