### PR TITLE
Throw a InvalidArgumentException when a consumer/extension is invalid

### LINKED ISSUE #17825: Log errors (and/or throw Exceptions) when activity usage was wrong
We should at least log an error, if an activity extension/consumer was registered but then ignored,
because it didn't implement the interface, similar to my suggestion on the capabilities sutff:
https://github.com/owncloud/core/pull/15093/files#r35293260

Consumer: https://github.com/owncloud/core/blob/master/lib/private/activitymanager.php#L98
Extension: https://github.com/owncloud/core/blob/master/lib/private/activitymanager.php#L154

This helps developers to find out quicker, why their code is not working/executed.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix  #17825
Diff without whitespaces: https://github.com/owncloud/core/pull/17830/files?w=1

Similar to the new Capabilities code

@DeepDiver1975 @rullzer @MorrisJobke

### CODE REVIEW

**Comment by rullzer** [comment]
Looking good! :+1:

**Comment by DeepDiver1975** [comment]
hmm - should the while thin fall apart because of one ext/consumer if faulty?

**Comment by nickvergessen** [comment]
I think we should yes, it saves debugging time for the developers

**Comment by MorrisJobke** [comment]
> I think we should yes, it saves debugging time for the developers

But only when actually developing. While running this in production it is better to only log this and skip the consumer/extension. Right?

**Comment by nickvergessen** [comment]
Well there should never be a case like this, because there should never be a invalid consumer/extension. If we start this now before tons of consumers/extensions are written it will also never happen...

And btw the capabilities manager does the same (hard failing).

**Comment by LukasReschke** [comment]
FWIW, agreeing with @nickvergessen :+1:

**Pull request merged**
