### PR TITLE
Checkboxes

### LINKED ISSUE #19741: Add indeterminate style to checkboxes
The new checkbox style should support the indeterminate property.
Icons already exist: https://github.com/owncloud/core/blob/master/core/img/actions/checkbox-mixed.png

### LINKED ISSUE #19743: Add custom radio input styling
We added custom styles for checkboxes in #18735.
To be consistent we should also add custom styles for radio buttons.

@jancborchardt

### PR DESCRIPTION
**Pull request by Henni**
fixes #19741 
fixes #19743 

@jancborchardt I'm still missing some icons. Can you add them to this PR please?

image
#### Checkbox
- [x] normal
- [x] indeterminate
- [x] checked
- [x] disabled
- [ ] indeterminate + disabled
- [x] checked + disabled
#### Checkbox White
- [x] normal
- [x] indeterminate
- [x] checked
- [x] disabled
- [ ] indeterminate + disabled
- [ ] checked + disabled

image
#### Radio
- [x] normal
- [x] checked
- [x] disabled
- [x] checked + disabled
#### Radio White
- [x] normal
- [ ] checked
- [ ] disabled
- [ ] checked + disabled

### CODE REVIEW

**Comment by Henni** [comment]
ping @jancborchardt

**Comment by nickvergessen** [comment]
what about the missing icons?

**Comment by jancborchardt** [comment]
The radio white: checked, disabled and checked+disabled are the same as the normal radio ones.

The checkbox white checked+disabled is also the same as the normal one.

Added the missing checkbox-mixed-disabled icon – also the same for both normal and white.

**Comment by MorrisJobke** [comment]
@Henni Any chance to get the code for your tests in a building block example app? To easily show what CSS building blocks are there and to easily test, if all is still working with a new version?

**Comment by Henni** [comment]
@MorrisJobke I have already worked on such an example app.
I might revive it and publish it on github.

**Comment by Henni** [comment]
Current state (ready for review):
image

**Comment by MorrisJobke** [comment]
I think the png file isn't needed.

beside that: 👍

**Comment by Henni** [comment]
@MorrisJobke We should probably remove all png files for checkboxes/radios.
Should this be part of this PR?

**Comment by MorrisJobke** [comment]
> Should this be part of this PR?

Not really, but adding unneeded files should be addressed in this PR ;)

**Comment by Henni** [comment]
@MorrisJobke fixed.
Should this be squashed or is it good as it is?

**Comment by MorrisJobke** [comment]
> Should this be squashed or is it good as it is?

Squashing is always nice, but we now could squash on merge because GitHub supports it now :)

**Comment by jancborchardt** [comment]
:+1: nice!

**Pull request merged**
