### PR TITLE
[stable10] extracted code that loads the default enabled app theme, load that th…

### PR DESCRIPTION
**Pull request by phil-davis**
…eme in case of exceptions (error pages)

Backport of #27974

### CODE REVIEW

**Comment by phil-davis** [comment]
This was noticed (is a problem) because https://github.com/owncloud/core/pull/28559 "send 403 error when preview is blocked by firewall rule" was back-ported to stable10 in https://github.com/owncloud/core/pull/28565
In there, the line:
```
\OC::loadDefaultEnabledAppTheme();
```
was included in the new catch block:
```
} catch (\OCP\Files\ForbiddenException $ex) {
 +	\OC::loadDefaultEnabledAppTheme();
 +	OC_Response::setStatus(OC_Response::STATUS_FORBIDDEN);
 +	OC_Template::printErrorPage($ex->getMessage());
  } catch (Exception $ex) {
...
```
because at the time in master this "extracted code that loads the default enabled app theme" commit was already there, and the other catch blocks had that line.

Because this "extracted code that loads the default enabled app theme" has not yet been backported to stable10, loadDefaultEnabledAppTheme is not a working "thing" in stable10.

If caused failures running firewall tests about viewing forbidden previews on top of stable10, because those exercised ForbiddenException.

With this backport to stable10, the firewall tests are passing.

**Comment by phil-davis** [comment]
If this should not be backported, then the alternative is to remove:
```
\OC::loadDefaultEnabledAppTheme();
```
from the ForbiddenException block in stable10.

**Review by PVince81 — APPROVED** [review]
:+1: fine by me.

I thought we backported this already.

**Comment by phil-davis** [comment]
On the original PR there is no note about backporting - I guess it just was missed.

**Pull request merged**
