### PR TITLE
[stable8.1] Add warning for not existing CA bundle when updating

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/owncloud/core/pull/18430

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by LukasReschke** [comment]
```
12:17:04 Oracle connection could not be established
12:17:04  -> ORA-01017: invalid username/password; logon denied Check environment: ORACLE_HOME=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server ORACLE_SID=XE LD_LIBRARY_PATH=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/lib: NLS_LANG=AMERICAN_AMERICA.AL32UTF8 tnsnames.ora is readable

```

*sigh*

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Pull request merged**
