### PR TITLE
Stable9 backport integration tests

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Removing failing and not applying situations.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
@PVince81 
https://github.com/owncloud/core/pull/25543 this one is not merged yet. 
Should I remove tests about merging shares here or keep it?

**Comment by SergioBertolinSG** [comment]
Problems with new dav endpoint:

1. Moving a file to a folder fails. Scenario: moving a file new endpoint way
This can be modified and move file to the same folder.

2. Scenario: Downloading a file on the new endpoint should serve security headers
This doesn't happen. Not sure if something to fix or a test to remove.

**Comment by SergioBertolinSG** [comment]
Fixed security headers as they changed.

**Comment by SergioBertolinSG** [comment]
I'd prefer to remove merging tests from here and include them in https://github.com/owncloud/core/pull/25543 it will require a rebase though.

**Comment by DeepDiver1975** [comment]
great work :+1:

**Pull request merged**
