### PR TITLE
[stable10] Change jakearchibald/es6-promise#2.3.0 to components/es6-promise#v4.2.4 like in master

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
This changes from `jakearchibald` to `components` and bumps the version.

## Motivation and Context
Make `stable10` like `master`

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by phil-davis** [comment]
Let's see what CI says about this.

And does anyone know:

Why does `stable10` use `jakearchibald` ?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/16228/87
```
ReferenceError: Can't find variable: Promise in core/vendor/davclient.js/lib/client.js (line 255)

PhantomJS 2.1.1 (Linux 0.0.0): Executed 985 of 989 (30 FAILED) (skipped 4) (20.08 secs / 19.532 secs) 
```
There must be something more/different in `master` that makes this work.

**Comment by PVince81** [comment]
there's also this struggle with master: https://github.com/owncloud/core/pull/30487

**Comment by PVince81** [comment]
@phil-davis bisect ?

**Comment by phil-davis** [comment]
See #35627 for newer PR

**Pull request closed without merging**
