### PR TITLE
Move caldav tester to drone

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
why does this fix it?

**Comment by DeepDiver1975** [comment]
nice - thx for explaining.

I'll grab your commit and continue in my branch - or do you want to take over completly?

**Comment by phil-davis** [comment]
whichever - do like moving things to drone or adding php-cs-fixer rules better?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 whichever - do you like moving things to drone or adding php-cs-fixer rules better?

:twisted_rightwards_arrows: I don't care much - all has to be done. Go ahead as you wish ;-)

**Comment by phil-davis** [comment]
I squashed this one
@DeepDiver1975 please review/approve

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport ``stable10`` #31450

**Pull request merged**
