### PR TITLE
[stable10] The great CORS fix ..

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport #34391

### CODE REVIEW

**Comment by PVince81** [comment]
```
1) OCA\DAV\Tests\unit\Connector\Sabre\CorsPluginTest::testAuthenticatedAdditionalAllowedHeaders
Expectation failed for method name is equal to <string:getHTTPMethods> when invoked zero or more times
Parameter 0 for invocation Sabre\DAV\ServerPlugin::getHTTPMethods('') does not match expected value.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'owncloud/remote.php/dav/files/user1/target/path'
+''
```

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
:sacrebleu:

**Comment by DeepDiver1975** [comment]
@PVince81 test fixed ....

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by DeepDiver1975** [comment]
Thx

**Pull request merged**
