### PR TITLE
Fixes shifted rename field

### LINKED ISSUE #13338: Rename field in "Favorites" is shifted to the right
* mark a file/folder as favorite (star)
* go to the favorite view
* rename the file/folder by clicking on the pencil icon
* looks like:

rename-favs-in-master

version: current master

cc @PVince81 @jancborchardt You played around with that too. Wasn't there a fix for the other views? Maybe this is causing this problem here

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #13338

cc @jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
Instead of adding this rule
```
:not(.has-favorites) table td.filename input.filename {
	margin-left: 48px;
}
```

Wouldn’t it make more sense to adjust the margin-left in the rule above: https://github.com/owncloud/core/pull/13421/files#diff-bb10e776e76087440b4aeccb0e18b927R267
From 8 to 48px?

**Comment by MorrisJobke** [comment]
@jancborchardt :'( ...you're right. Fixed it and tested in IE8, IE9, Firefox, Chrome...works :)

**Comment by jancborchardt** [comment]
Tested and works :+1:

Makes me question my own sanity on why I put the 8px there in the first place …

**Comment by Xenopathic** [comment]
:+1: tested

**Pull request merged**
