### PR TITLE
password_policy is a shipped app

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of https://github.com/owncloud/core/pull/20541

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
@cmonteroluque @karlitschek something to include when building the final package

**Comment by karlitschek** [comment]
@PVince81 what final packages do you mean? 8.2.1 ? I guess it is too late for that.

**Comment by cmonteroluque** [comment]
8.2.1 final enterprise tarball should have password_policy in it.

**Pull request merged**
