### PR TITLE
files_encryption -> encryption

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@schiesbn @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Ah, yes this one too. :+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
dummy encryption is shipped aswell? or is that not needed?

**Comment by karlitschek** [comment]
This brings up an interesting question. How is our upgrade experience here? What happens if someone _doesn't_ delete the old files_encryption.

**Comment by karlitschek** [comment]
the dummy encryption app should be moved outside the core repository by the way. Maybe into the apps repo.

**Comment by DeepDiver1975** [comment]
> the dummy encryption app should be moved outside the core repository by the way. Maybe into the apps repo.

or simply dropped as this was for pure development purpose

**Comment by DeepDiver1975** [comment]
> What happens if someone doesn't delete the old files_encryption.

first of all we know that one is not capable to read our upgrade docs - second: from my understanding the instance will explode because e.g. we removed the OC_FileProxy with 8.1 which was only used my encryption.

**Comment by nickvergessen** [comment]
Well the problem is the same when someone does not delete the 3rdparty folder before uploading it again. Old files of the 3rdparty might still be there with their security issues and other problems.

**Pull request merged**
