### PR TITLE
[stable10] Adding background:queue commands: status and delete

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #31630

### CODE REVIEW

**Comment by phil-davis** [comment]
Blocked. See comment on original PR: https://github.com/owncloud/core/pull/31630#issuecomment-473932726

**Comment by phil-davis** [comment]
@PVince81 this backport is ready for review-approve-merge now that master PR #31617 is ready

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/31617 was merged

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
