### PR TITLE
verify path when getting a node for sabredav

### LINKED ISSUE #16825: Renaming folders in webdav interface using backslash coded doesn't return proper error.
### Steps to reproduce

1. Rename a folder using curl:
```
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H 'Destination:http://User:Password@Host/remote.php/webdav/%2F'
```
or
```
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H 'Destination:http://User:Password@Host/remote.php/webdav/%2Fhola'
```
or
```
curl -v -X MOVE 'http://User:Password@Host/remote.php/webdav/carpeta' -H "Destination:http://User:Password@Host/remote.php/webdav/hola%2Fhola"
```

### Expected behaviour
It should answer error, forbidden characters.

### Actual behaviour
In first case it returns `<s:exception>Sabre\DAV\Exception\Forbidden</s:exception>`
In second case 'carpeta' is renamed to 'hola'
In third case it return "The destination node is not found"

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
None.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

curl

### PR DESCRIPTION
**Pull request by icewind1991**
This time with unit tests and tested manually.

Fix #16825 

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
@karlitschek so you tested it too this time ?

Running some tests now

**Comment by PVince81** [comment]
- [x] TEST: pyocclient test suite
- [x] TEST: sync client (with s2s folder and link shares)
- [x] TEST: move to backslash folder

Fixes https://github.com/owncloud/core/issues/16825

:+1:

**Comment by SergioBertolinSG** [comment]
tested #16825 here, working fine :+1:

**Comment by PVince81** [comment]
Follow up fix here https://github.com/owncloud/core/pull/16943

**Pull request merged**
