### PR TITLE
Fix ocs calls for oauth

### LINKED ISSUE #33: No access to OCS API.
In my prototype implementation for the desktop client, i can successfully do PROPFIND on webdav endpoint, but ocs/v1.php/cloud/capabilities or ocs/v1.php/cloud/user returns 404.

The token needs to grant permission to the OCS API as the client uses it.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
AuthModules need to be processed in handeLogin as well

## Related Issue
fixes https://github.com/owncloud/oauth2/issues/33

## Motivation and Context
fix oauth on android

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by davivel — APPROVED** [review]
LGTM

**Comment by PVince81** [comment]
Does this need a backport ? There were other backports about this auth module thingy

**Comment by davivel** [comment]
Probably?

**Comment by michaelstingl** [comment]
> Does this need a backport ?

oauth2 app is oC10 only?
`<owncloud min-version="10.0" max-version="10.0"/>`
(https://github.com/owncloud/oauth2/blob/master/appinfo/info.xml#L12)

**Comment by DeepDiver1975** [comment]
> If this is the case, then I don't know why we need a backport.

there is also a stable9.1 branch in oauth - this is the original version as used by the student project with the moodle integration.

**Comment by michaelstingl** [comment]
@DeepDiver1975 Thanks for clarification. Backport would be cool then!

**Pull request merged**
