### PR TITLE
explicitly set z-index on app-content, fix overlap from navigation

### PR DESCRIPTION
**Pull request by jancborchardt**
Manual backport of https://github.com/owncloud/core/pull/17105 to stable7, please review @owncloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
@karlitschek FYI

**Comment by jancborchardt** [comment]
So just to be sure for everyone here as well: We only merge this in after the 7.0.7 release, right @MorrisJobke?

**Comment by MorrisJobke** [comment]
> So just to be sure for everyone here as well: We only merge this in after the 7.0.7 release, right @MorrisJobke?

Yes

**Pull request closed without merging**
