### PR TITLE
remove warning when trying to get a lock while in transaction

### PR DESCRIPTION
**Pull request by icewind1991**
cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by Xenopathic** [comment]
How will locking work in a transaction? Are we still guaranteed concurrency protection?

**Comment by individual-it** [comment]
this line did not protect anything, just printed a lot of log lines
to throw an exception would bring protection

**Comment by nickvergessen** [comment]
> this line did not protect anything, just printed a lot of log lines
to throw an exception would bring protection

exactly, therefor :+1: 

The admin can't do anything with this log message, it's not a misconfiguration or anything.

As for
> How will locking work in a transaction?

We tell the connection to "read commited": https://github.com/owncloud/core/blob/master/lib/private/db/connection.php#L135-135
The rest is up to your knowledge

**Comment by nickvergessen** [comment]
@icewind1991 please always set labels and milestones according to the ticket and PR status, to help getting stuff reviewed that is done.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by mmattel** [comment]
:+1: 
At least the log is not filled up.

When I used the new occ command (see: 
https://github.com/owncloud/gallery/pull/387#issuecomment-143813524), ton´s of these messages have been logged.

But, and maybe important, the thumbnail generation broke at some late point in time due to a database error. This means that the root cause is not fixed, only the messaging:
````
Warning	files_versions	-1 is not a valid value for maximal versions retention obligation. Check versions_retention_obligation in your config.php. Falling back to auto.

Error	index	Exception: {"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1443467817, \"files\\\/f734dc428f23a4e02ecd79ea7cb5ff96\"]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction","Code":0,"Trace":"
#0 \/xxx\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\
n#1 \/xxx\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE `oc_file...', Array)\
n#2 \/xxx\/lib\/private\/db\/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\
n#3 \/xxx\/lib\/private\/lock\/dblockingprovider.php(116): OC\\DB\\Connection->executeUpdate('UPDATE `*PREFIX...', Array)\
n#4 \/xxx\/lib\/private\/files\/storage\/common.php(638): OC\\Lock\\DBLockingProvider->acquireLock('files\/f734dc428...', 1)\
n#5 \/xxx\/lib\/private\/files\/storage\/wrapper\/wrapper.php(571): OC\\Files\\Storage\\Common->acquireLock('files', 1, Object(OC\\Lock\\DBLockingProvider))\
n#6 \/xxx\/lib\/private\/files\/storage\/wrapper\/wrapper.php(571): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files', 1, Object(OC\\Lock\\DBLockingProvider))\
n#7 \/xxx\/lib\/private\/files\/view.php(1779): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files', 1, Object(OC\\Lock\\DBLockingProvider))\
n#8 \/xxx\/lib\/private\/files\/view.php(1874): OC\\Files\\View->lockPath('\/', 1, false)\
n#9 \/xxx\/lib\/private\/files\/view.php(1190): OC\\Files\\View->lockFile('\/', 1)\
n#10 \/xxx\/lib\/private\/files\/filesystem.php(861): OC\\Files\\View->getFileInfo('\/', false)\
n#11 \/xxx\/apps\/files\/index.php(91): OC\\Files\\Filesystem::getFileInfo('\/', false)\
n#12 \/xxx\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/xxx...')\
n#13 [internal function]: __lambda_func(Array)\
n#14 \/xxx\/lib\/private\/route\/router.php(281): call_user_func('?lambda_590', Array)\
n#15 \/xxx\/lib\/base.php(830): OC\\Route\\Router->match('\/apps\/files')\
n#16 \/xxx\/index.php(40): OC::handleRequest()\
n#17 {main}","File":"\/xxx\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115}
````

**Pull request merged**
