### PR TITLE
Bump version 10.5.0beta2 in version.php

### PR DESCRIPTION
**Pull request by jnweiger**
We have succeeded with beta1 which serves as a technical exercise for the changed process. 

@phil-davis @micbar Let's roll a more useful (content-wise) beta2 -- I assume today's master is good?

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
core master is good - I don't have any run-time code waiting to be merged.

**Comment by jnweiger** [comment]
@HanaGemela @davitol suggest to directly go to RC1.

**Comment by phil-davis** [comment]
Note: https://drone.owncloud.com/owncloud/core/25175/39/9
```
wait-for-it -t 600 fsweb.test.owncloud.com:445
services aren't ready in 10m0s
```

This is a current known problem - fsweb.test.owncloud.com is down. I have sent email to sysadmin to get it back.

**Comment by phil-davis** [comment]
I don't care what we call it. I would like to avoid making the "permanent" release branch for 10.5 just yet, because I want to get PR #37332 merged. That has a bunch of acceptance test code changes, and if I can, it would be nice that it also ends up in the 10.5 release branch/tag.

**Review by micbar — APPROVED** [review]

**Comment by jnweiger** [comment]
Ci is done. With exactly two expected test failures due to fsweb.test being unavailable.

**Pull request merged**
