### PR TITLE
[stable10] View-only dav plugin using IShare attributes

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/33994/ to stable10

There were minor conflicts in unit test files.

### CODE REVIEW

**Comment by PVince81** [comment]
huh wat
```
An unhandled exception has been thrown:
Error: Undefined class constant 'JSON' in /drone/src/core/Migrations/Version20181220085457.php:41
Stack trace:
#0 /drone/src/lib/private/DB/MigrationService.php(411): OC\Migrations\Version20181220085457->changeSchema(Object(Doctrine\DBAL\Schema\Schema), Array)
#1 /drone/src/lib/private/DB/MigrationService.php(366): OC\DB\MigrationService->executeStep(20181220085457)
#2 /drone/src/lib/private/Setup/AbstractDatabase.php(107): OC\DB\MigrationService->migrate()
#3 /drone/src/lib/private/Setup.php(343): OC\Setup\AbstractDatabase->runMigrations()
#4 /drone/src/core/Command/Maintenance/Install.php(86): OC\Setup->install(Array)
#5 /drone/src/lib/composer/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /drone/src/lib/composer/symfony/console/Application.php(960): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /drone/src/lib/composer/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Maintenance\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /drone/src/lib/composer/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /drone/src/lib/private/Console/Application.php(161): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /drone/src/console.php(106): OC\Console\Application->run()
#11 /drone/src/occ(11): require_once('/drone/src/cons...')
#12 {main}
```

**Comment by PVince81** [comment]
could it be that on stable10 the Doctrine version doesn't support JSON yet ?

**Comment by PVince81** [comment]
I did some research and we can't upgrade doctrine/dbal to 2.6 because it would require PHP 7.1 and we're currently still on PHP 7.0.

So the only solution for now is using a text column. Pushed as the latest commit.

I've adjusted master as well here: https://github.com/owncloud/core/pull/34965

**Comment by PVince81** [comment]
fixed test issue that sneaked in during conflict resolution.
squashed and rebased onto stable10

**Comment by PVince81** [comment]
and now the "git fetch remote timeout" issue. restarted

**Comment by PVince81** [comment]
@DeepDiver1975 CI green, review ?

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
