### PR TITLE
Bump 3rdparty for opencloud-1.15.0 + deps

### PR DESCRIPTION
**Pull request by rullzer**
requires: https://github.com/owncloud/3rdparty/pull/215

### CODE REVIEW

**Comment by rullzer** [comment]
As expected swith chokes on this...
Who is our swift expert that can have a look?

**Comment by DeepDiver1975** [comment]
This update breaks primary storage integration :dancers: 

````
OCA\ObjectStore\Tests\Unit\Swift::testMove with data set #0 ('/source.txt', '/target.txt')
Guzzle\Http\Exception\ClientErrorResponseException: Client error response
[status code] 405
[reason phrase] Method Not Allowed
[url] http://172.17.7.136/swift/v1?bulk-delete=1

/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Message/Request.php:145
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:53
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Message/Request.php:589
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Message/Request.php:378
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php:49
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:303
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:257
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:240
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:224
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:111
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php:94
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Client.php:284
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/guzzle/guzzle/src/Guzzle/Http/Message/Request.php:198
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Service.php:250
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Service.php:229
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Resource/Container.php:235
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Resource/Container.php:199
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/3rdparty/rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Resource/Container.php:164
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/lib/private/files/objectstore/swift.php:146
/ssd/jenkins/workspace/core-ci-linux-swift-primary-storage@3/database/mysql/label/SLAVE/tests/lib/files/objectstore/swift.php:67

**Comment by rullzer** [comment]
@butonic could you have a look?

**Comment by rullzer** [comment]
Lets close this for now.

**Pull request closed without merging**
