### PR TITLE
Pass web requests to occ controller if upgrade is needed

### LINKED ISSUE #371: Update 9.1.0 to 9.1.1RC1 fails
I wanted to enable updated for 9.1.1RC1 in the update server but when I did I met this issue (reproduced at least twice):

1. Setup v9.1.0
1. Update URL to match local update server
1. Switch to beta channel
1. Update to v9.1.1RC1

```
[info] Execution of upgrade:detect command started
[info] ownCloud 9.1.0.15 found
[info] Execution of upgrade:detect command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:checkpoint command started
[info] Execution of upgrade:checkpoint command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.1.0.15 found
[info] Execution of upgrade:detect command stopped. Exit code is 0
[info] Execution of upgrade:disableNotShippedApps command started
[info] Execution of upgrade:disableNotShippedApps command stopped. Exit code is 0
[info] Execution of upgrade:executeCoreUpgradeScripts command started
[debug] Replacing 3rdparty
[debug] Replacing config
[debug] Replacing core
[debug] Replacing l10n
[debug] Replacing lib
[debug] Replacing ocs
[debug] Replacing ocs-provider
[debug] Replacing resources
[debug] Replacing settings
[debug] Replacing .htaccess
[debug] Replacing .mailmap
[debug] Replacing .tag
[debug] Replacing .user.ini
[debug] Replacing AUTHORS
[debug] Replacing console.php
[debug] Replacing COPYING-AGPL
[debug] Replacing cron.php
[debug] Replacing db_structure.xml
[debug] Replacing index.html
[debug] Replacing index.php
[debug] Replacing indie.json
[debug] Replacing occ
[debug] Replacing public.php
[debug] Replacing remote.php
[debug] Replacing robots.txt
[debug] Replacing status.php
[debug] Replacing version.php
[error] 

                                                                                                                                         
  [GuzzleHttp\Exception\ServerException]                                                                                                 
  Server error response [url] http://localhost/owncloudtest/index.php/occ/upgrade [status code] 503 [reason phrase] Service Unavailable  
                                                                                                                                         


Exception trace:
 () at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
 GuzzleHttp\Exception\RequestException::create() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php:33
 GuzzleHttp\Subscriber\HttpError->onComplete() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Event/Emitter.php:109
 GuzzleHttp\Event\Emitter->emit() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:91
 GuzzleHttp\RequestFsm->__invoke() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:132
 GuzzleHttp\RequestFsm->GuzzleHttp\{closure}() at /srv/www/htdocs/owncloudtest/updater/vendor/react/promise/src/FulfilledPromise.php:25
 React\Promise\FulfilledPromise->then() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
 GuzzleHttp\Ring\Future\CompletedFutureValue->then() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
 GuzzleHttp\Message\FutureResponse::proxy() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/RequestFsm.php:135
 GuzzleHttp\RequestFsm->__invoke() at /srv/www/htdocs/owncloudtest/updater/vendor/guzzlehttp/guzzle/src/Client.php:165
 GuzzleHttp\Client->send() at /srv/www/htdocs/owncloudtest/updater/src/Utils/OccRunner.php:103
 Owncloud\Updater\Utils\OccRunner->runAsRequest() at /srv/www/htdocs/owncloudtest/updater/src/Utils/OccRunner.php:70
 Owncloud\Updater\Utils\OccRunner->run() at /srv/www/htdocs/owncloudtest/updater/src/Command/ExecuteCoreUpgradeScriptsCommand.php:118
 Owncloud\Updater\Command\ExecuteCoreUpgradeScriptsCommand->execute() at /srv/www/htdocs/owncloudtest/updater/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /srv/www/htdocs/owncloudtest/updater/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at /srv/www/htdocs/owncloudtest/updater/src/Console/Application.php:197
 Owncloud\Updater\Console\Application->doRunCommand() at /srv/www/htdocs/owncloudtest/updater/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /srv/www/htdocs/owncloudtest/updater/src/Console/Application.php:174
 Owncloud\Updater\Console\Application->doRun() at /srv/www/htdocs/owncloudtest/updater/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /srv/www/htdocs/owncloudtest/updater/src/Controller/IndexController.php:150
 Owncloud\Updater\Controller\IndexController->ajaxAction() at /srv/www/htdocs/owncloudtest/updater/src/Controller/IndexController.php:88
 Owncloud\Updater\Controller\IndexController->dispatch() at /srv/www/htdocs/owncloudtest/updater/index.php:29


upgrade:executeCoreUpgradeScripts
```

For some reason "occ" from the owncloud server responds 503.

@VicDeo please investigate

### PR DESCRIPTION
**Pull request by VicDeo**
## Related Issue

Fixes https://github.com/owncloud/updater/issues/371
## Motivation and Context

503 response to requests initiated by updater
## How Has This Been Tested?

Manually.
1. Install 9.1.0
2. Install local update server
3. Patch local update server to serve 9.1.1RC1
4.  Patch lib/base.php in 9.1.1RC1
5. Update 'updater.server.url' => '', in config.php to match local update server
6. Trigger update from web UI
...
8. Profit!
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 please have a look

**Comment by VicDeo** [comment]
Setting severity according to the issue

**Comment by VicDeo** [comment]
Stable9.1: https://github.com/owncloud/core/pull/26048

**Comment by PVince81** [comment]
Tested, works :+1:

**Pull request merged**
