### PR TITLE
wording in LDAP wizard

### LINKED ISSUE #13936: Better wording in LDAP wizard
The verbiage of the "User Filter" tab is supper confusing: "Limit ownCloud access to users meeting these criteria: " that to me implies that users not meeting the criteria don't get access :)

Same with the verbiage of the "Login Filter" tab: "Users login with this attribute", does not mention access restriction at all.

From https://github.com/owncloud/core/issues/13929#issuecomment-73157481

cc @blizzz @unamedplayer

### PR DESCRIPTION
**Pull request by davicente**
@MorrisJobke @owncloud/qa 
Fixes https://github.com/owncloud/core/issues/13936

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @MTRichards for native speaker review :)

**Comment by MTRichards** [comment]
Native language check passed!

**Comment by MorrisJobke** [comment]
👍

**Comment by blizzz** [comment]
Thx!

**Pull request merged**
