### PR TITLE
Add reshare activities for the parent sharee and the original file owner

### PR DESCRIPTION
**Pull request by nickvergessen**
Required for owncloud/activity#384

### CODE REVIEW

**Comment by rullzer** [comment]
Looks good!
But why don't we have tests to make sure nothing breaks?

**Comment by schiesbn** [comment]
tested, works and code looks good :+1: 

Is it possible to add some unit tests as suggested by @rullzer ?

**Comment by nickvergessen** [comment]
Well in unit tests I could only duplicate the hardcoded arrays. The files here in core don't really contain a lot of logic.

**Comment by nickvergessen** [comment]
@DeepDiver1975 merge please

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
