### PR TITLE
Fix delete user dav hook to only delete users addressbooks

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
On the deleteUser hook, only delete addressBooks that the user owns, not ones that have been shared with them.

## Motivation and Context
Right now, if you delete a user, any addressbooks shared with them are also deleted.

## How Has This Been Tested?
 - In the browser
 - Unit test updated

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tomneedham** [comment]
+ should be backported

**Comment by PVince81** [comment]
Makes absolute sense 👍 

@tomneedham please backport

**Comment by PVince81** [comment]
@tomneedham backport still pending

**Comment by PVince81** [comment]
@tomneedham missing backport

**Comment by DeepDiver1975** [comment]
This is already in 10 - we want it in 9.1? 9.0? @PVince81

**Comment by PVince81** [comment]
sounds critical enough for a backport to 9.1 at least.

**Comment by PVince81** [comment]
ok so, 9.1 will be EOL soon... removing backport label

**Pull request merged**
