### PR TITLE
Using TRANSACTION_READ_COMMITTED

### PR DESCRIPTION
**Pull request by nickvergessen**
Related #15337 

@dragotin @DeepDiver1975

### CODE REVIEW

**Comment by jnfrmarks** [comment]
I'm running some tests using with the patch applied to the latest complete stable 8 build.  I'll update this issue with my results in a bit.

**Comment by jnfrmarks** [comment]
I'm running a bunch of smashbox tests (really, just running test_uploadFiles a bunch of times).  I installed the enterprise-complete tarball and configured an LDAP before running my tests.

Occasionally, I see some funky things in the log file, such as:

```

{"reqId":"2552d0904bc5fbe0134e6ad9faaddefb","remoteAddr":"172.18.5.75","app":"PHP"
,"message":"array_merge(): Argument #2 is not an array at \/var\/www\/html\/ownclo
ud\/lib\/private\/group\/manager.php#226","level":3,"time":"2015-04-13T17:58:30+00
:00"}
{"reqId":"a74de58df4fcad2c5ee508205e86b774","remoteAddr":"172.18.5.75","app":"PHP"
,"message":"unlink(\/tmp\/owncloud-ochewo9lqdny\/LDAP-user_ldap-s01-2373a3ba50c893
7f76ae1ce111be2368): No such file or directory at \/var\/www\/html\/owncloud\/lib\
/private\/cache\/fileglobal.php#58","level":3,"time":"2015-04-13T18:00:21+00:00"}

```


Even though I'm testing with local users and not LDAP users.

And, 

```

{"reqId":"1cd7dc17141019572c0f394491ab4647","remoteAddr":"x.x.x.x","app":"PHP","message":"array_merge(): Argument #2 is not an array at \/var\/www\/html\/owncloud\/lib\/private\/group\/manager.php#226","level":3,"time":"2015-04-13T14:04:19+00:00"}
{"reqId":"1cd7dc17141019572c0f394491ab4647","remoteAddr":"x.x.x.x","app":"PHP","message":"Argument 2 passed to OCA\\windows_network_drive\\lib\\DBAccess::getMountsForUser() must be of the type array, null given, called in \/var\/www\/html\/owncloud\/apps\/windows_network_drive\/lib\/hooks.php on line 33 and defined at \/var\/www\/html\/owncloud\/apps\/windows_network_drive\/lib\/dbaccess.php#106","level":3,"time":"2015-04-13T14:04:19+00:00"}
{"reqId":"1cd7dc17141019572c0f394491ab4647","remoteAddr":"x.x.x.x","app":"PHP","message":"array_merge(): Argument #2 is not an array at \/var\/www\/html\/owncloud\/apps\/windows_network_drive\/lib\/dbaccess.php#118","level":3,"time":"2015-04-13T14:04:19+00:00"}
{"reqId":"1cd7dc17141019572c0f394491ab4647","remoteAddr":"x.x.x.x","app":"PHP","message":"Argument 2 passed to OCA\\windows_network_drive\\lib\\DBAccess::executeSelectAndGetCursor() must be of the type array, null given, called in \/var\/www\/html\/owncloud\/apps\/windows_network_drive\/lib\/dbaccess.php on line 119 and defined at \/var\/www\/html\/owncloud\/apps\/windows_network_drive\/lib\/dbaccess.php#632","level":3,"time":"2015-04-13T14:04:19+00:00"}
{"reqId":"1cd7dc17141019572c0f394491ab4647","remoteAddr":"x.x.x.x","app":"hook","message":"error while running hook (\\OCA\\windows_network_drive\\lib\\Hooks::mount_storages): An exception occurred while executing 'SELECT DISTINCT `wnd_mounts`.* , `wnd_credentials`.* FROM `wnd_mounts` JOIN `wnd_mounts_applicable` ON `wnd_mounts`.`mount_id` = `wnd_mounts_applicable`.`applicable_mount_id_fk` LEFT JOIN `wnd_credentials` ON (`wnd_mounts`.`mount_id` = `wnd_credentials`.`credentials_mount_id_fk` AND `wnd_credentials`.`mounting_user` = ?) WHERE (`mount_type` = 'global' OR (`mount_type` = 'user' AND `mount_type_name` = ?) )':\n\nSQLSTATE[HY093]: Invalid parameter number: no parameters were bound","level":3,"time":"2015-04-13T14:04:19+00:00"}

```

even though I'm don't have a WND configured (the app is enabled, just no mount is configured)

I'm trying to get more data on the specifics and will update when/if I do

**Comment by nickvergessen** [comment]
New issue, not caused by this, please test without it and report the issue in the respective repo

**Comment by DeepDiver1975** [comment]
> even though I'm don't have a WND configured (the app is enabled, just no mount is configured)

this needs to be fixed within the scope of WND - we need to have a closer look - scope of 8.0.3 is questionable

**Comment by DeepDiver1975** [comment]
> Occasionally, I see some funky things in the log file, such as:

for sure something we have to look into - afaik this should have no impact

**Comment by jnfrmarks** [comment]
One more error in the log file; saw once; trying to reproduce.  


```
{"reqId":"2005ead87c9af1ea36e269b70447828b","remoteAddr":"x.x.x.x","app":"remo
te","message":"An exception occured in driver: SQLSTATE[HY000] [2013] Lost connect
ion to MySQL server at 'reading authorization packet', system error: 0","level":4,
"time":"2015-04-13T20:30:37+00:00"}
{"reqId":"ad5acc535949e56d68e96b814f4d2a3d","remoteAddr":"x.x.x.x","app":"remo
te","message":"An exception occured in driver: SQLSTATE[HY000] [2013] Lost connect
ion to MySQL server at 'reading authorization packet', system error: 0","level":4,
"time":"2015-04-13T20:30:37+00:00"}


```

**Comment by DeepDiver1975** [comment]
> Lost connect ion to MySQL server at 'reading authorization packet'

Are you connecting to the mysql server by IP or hostname?
Background: general cause for this error seems to be issues with the DNS or firewalls

In case you connect via hostname -> enter the ip into /etc/hosts to eliminate DNS queries

**Comment by DeepDiver1975** [comment]
> this needs to be fixed within the scope of WND - we need to have a closer look - scope of 8.0.3 is questionable

basically an issue in core - https://github.com/owncloud/core/issues/15590 - but this has no impact on the sync mechanisms - fixing this in the scope of 8.1 should be enough

**Comment by DeepDiver1975** [comment]
> {"reqId":"a74de58df4fcad2c5ee508205e86b774","remoteAddr":"172.18.5.75","app":"PHP" ,"message":"unlink(\/tmp\/owncloud-ochewo9lqdny\/LDAP-user_ldap-s01-2373a3ba50c893 7f76ae1ce111be2368): No such file or directory at \/var\/www\/html\/owncloud\/lib\ /private\/cache\/fileglobal.php#58","level":3,"time":"2015-04-13T18:00:21+00:00"}

this looks like a race condition where two parallel requests clear out the file cache.
@icewind1991 @PVince81 do we really want such a caching mechanism?
We would now need to invest time/resources to implement proper locking - easier solution would be to tell the admin to install a proper memcache thingy.

**Comment by PVince81** [comment]
or maybe the clearing should be put in a background job / cron instead ?

**Comment by DeepDiver1975** [comment]
\OC\Cache\FileGlobal seems to be only used in LDAP - @blizzz can you live without this class? THX

**Comment by DeepDiver1975** [comment]
> or maybe the clearing should be put in a background job / cron instead ?

sorry - have to rephrase - this happens on expiry of a cache element - async will not work from my understanding. Furthermore also write operations are not locked - which is more of an issue from my understanding.

**Comment by nickvergessen** [comment]
This is all unrelated? So we can merge this PR and get 8.0.3 out of the door finally?

**Comment by DeepDiver1975** [comment]
@jnfrmarks besides the sql errors https://github.com/owncloud/core/pull/15577#issuecomment-92548205 which need to be analyzed - all other errors are of no relevance with respect to this change.

**Comment by blizzz** [comment]
> \OC\Cache\FileGlobal seems to be only used in LDAP - @blizzz can you live without this class? THX

From the hip: do we have a replacement?

**Comment by jnfrmarks** [comment]
I'm connecting to mysql via an IP address.

**Comment by DeepDiver1975** [comment]
> I'm connecting to mysql via an IP address.

from what I can tell this is a setup issue and unrelated to our code

**Comment by jnfrmarks** [comment]
ok; I'll file issues for the LDAP exception and the WND exception.

**Comment by DeepDiver1975** [comment]
> ok; I'll file issues for the LDAP exception and the WND exception.

not really necessary - both issue come down to  #15590 in core

**Comment by nickvergessen** [comment]
@DeepDiver1975 I assume this one goes into 8.0.4 now since RC2 has just been release?

**Comment by DeepDiver1975** [comment]
@karlitschek we should have merged this for 8.0.3rc2

**Comment by dragotin** [comment]
Oh yes, please. Do not ship 8.0.3 without this!

**Comment by PVince81** [comment]
Well... if we're now putting stuff in 8.0.3 at the last minute again, we might as well put this here too https://github.com/owncloud/core/pull/15572#issuecomment-93678724 and delay the release...

**Comment by DeepDiver1975** [comment]
> Well... if we're now putting stuff in 8.0.3 at the last minute again, we might as well put this here too #15572 (comment) and delay the release...

this is NOT a last minute change - this change was the only reason we delayed 8.0.3 fro almost 2 weeks now.
This change was intensively tested as well - we did freeze 8.0.3 back then and NO other change then this is supposed to be merged into 8.0.3

**Comment by PVince81** [comment]
Ok, thanks. Makes sense then.

**Comment by DeepDiver1975** [comment]
@nickvergessen please open a pr for master - thx

**Comment by karlitschek** [comment]
we won't release 8.0.3 before is is fully fixed and tested. this is super important

**Pull request merged**
