### PR TITLE
[backport-14243-stable6] console commands shall not be limited with respect to execution time

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Comment by DeepDiver1975** [comment]
@LukasReschke it's a PR against stable6 - unit test execution fails because if phpunit version being installed. ...

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@MorrisJobke THX

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
`console.php` isn't unittested -> merge

**Pull request merged**
