### PR TITLE
[stable9] commit transaction after select query

### PR DESCRIPTION
**Pull request by phisch**
backport of #26700

### CODE REVIEW

**Comment by PVince81** [comment]
@PhilippSchaffrath please always set the label "3 - To Review" and more importantly the milestone

**Comment by PVince81** [comment]
also try to not be unlucky 😆 

```
Receiving objects:  16% (81393/488383), 45.06 MiB | 121.00 KiB/s   
error: index-pack died of signal 15
fatal: index-pack failed
```

Restarting build...

**Comment by PhilippSchaffrath** [comment]
@PVince81 easier said than done :cry:

**Comment by butonic** [comment]
👍

**Comment by PVince81** [comment]
Rebased to revive Jenkins

**Pull request merged**
