### PR TITLE
[stable10] Store quota overrides in preferences table

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
Currently the user management UI in stable10 uses this method, through `setquota.php` to update the quota of a user. However, if they are from another user backend, on sync the quota is just replaced. 

New version of https://github.com/owncloud/core/pull/32731

Setting the quota override should set it in the preferences table as well which is used as the manual override. On sync, the sync serivce checks this and uses this as an override instead. You can delete the key here to go back to the one supplied by the user backend.

## Related Issue
https://github.com/owncloud/core/pull/32731

## Motivation and Context
Quota is replaced on every sync if you override the quota in owncloud 10 and use an external user backend. 

## How Has This Been Tested?
Manually in the UI.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by PVince81** [comment]
@tomneedham hmm but wouldn't this code here also overwrite any value that was set by an admin as the override value during the next sync ?

**Comment by tomneedham** [comment]
No. Sync sets on the account. https://github.com/owncloud/core/blob/master/lib/private/User/SyncService.php#L223

SyncSerice is the connector between the Account and the User Backend. 

This convenince method is only used by the provisioning api and the UI to override the user quota that is provided by the user backend.

**Comment by PVince81** [comment]
Right, I see. So you brought back something we deleted back then.

**Comment by PVince81** [comment]
I agree with the change, let's see what CI says. I hope we do have some coverage here

**Comment by PVince81** [comment]
@individual-it @phil-davis as we have some work regarding LDAP automated tests, we should include something to cover this override

**Comment by phil-davis** [comment]
@PVince81 @tomneedham looks like this was thought about recently: https://github.com/owncloud/user_ldap/issues/368

**Comment by PVince81** [comment]
ok let's cover that with LDAP then, merging

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
master: https://github.com/owncloud/core/pull/34511

**Comment by micbar** [comment]
@tom see https://github.com/owncloud/enterprise/issues/2844#issuecomment-493048205

**Comment by micbar** [comment]
@pmaier1 
Carlos re opened the ticket.

**Pull request merged**
