### PR TITLE
[10.7.0] Fix regression that occurred after https://github.com/owncloud/core/pull/38375

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #38452 to 10.7.0

This is needed to fix the regression issue https://github.com/owncloud/encryption/issues/244

### CODE REVIEW

**Review by karakayasemi — APPROVED** [review]

**Comment by phil-davis** [comment]
@micbar this fixes a regression that was being worked on, but missed the `release-10.7.0` branch.

Is it OK to merge this backport?

**Review by micbar — CHANGES_REQUESTED** [review]
maybe recreate the release branch?

**Comment by phil-davis** [comment]
@micbar whatever you like to do. I just think that this fix should end up in the release.

**Comment by phil-davis** [comment]
@micbar I see that you merged-back release=1-.7.0 etc. So I guess this PR is no longer needed here?

**Comment by micbar** [comment]
yes. we needed to unfreeze the release for another regression.

**Pull request closed without merging**
