### PR TITLE
Test calendar object with various characters

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Postgress seems to have issues with some characters - pg being the new mysql?

## Related Issue
refs https://github.com/owncloud/core/issues/27426

## How Has This Been Tested?
- run unit test on jenkins for pg - no local pg at the moment

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
@DeepDiver1975 finish this ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 finish this ?

will do

**Comment by PVince81** [comment]
@DeepDiver1975 finish this ?

**Comment by PVince81** [comment]
unfinished -> planned

**Comment by DeepDiver1975** [comment]
@PVince81 finally the issue could be properly reproduced and fixed - we shall backport this. THX

**Review by PVince81 — APPROVED** [review]
looks fine if other DBs approve :+1:

**Pull request merged**
