### PR TITLE
[stable7] The class name is Movie NOT Movies

### LINKED ISSUE #14316: Video thumbnails not generated since 7.0.3
It was working in 7.0.2 but since 7.0.3 the mp4 files i uploaded only show default icons. The same is true for 7.0.4 and 8.0 as well.

All these versions were installed on Ubuntu Server 14.04.1 LTS. I also made sure libav-tools (ffmpeg equivalent in Ubuntu) is installed and avconv is working. Lastly I added line 'enable_previews' => true, to config.php and restarted apache2 afterwards.

It appears only video files are affected and image files are showing thumbnails correctly. In owncloud.log, I can see thumbnail related logs when a jpg file is being uploaded but nothing such is seen when a mp4 file is being uploaded.

I wonder if this is a known issue and if so it's on radar being addressed. Thx.

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #12313 
Fix #14316

Backport approved https://github.com/owncloud/core/pull/12313#issuecomment-75444865

@fxshpac @RealRancor @oparoz @MorrisJobke

### CODE REVIEW

**Comment by oparoz** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@karlitschek This doesn't seem to be included in the 7.0.5 tag: https://github.com/owncloud/core/compare/v7.0.5...stable7 ... should we move the milestone or the tag?

**Comment by karlitschek** [comment]
Ahh. I think we should move the tag. Can you do this?

**Comment by nickvergessen** [comment]
Btw there is no such thing as "move tag", its delete and recreate :speak_no_evil:

**Comment by MorrisJobke** [comment]
@karlitschek done. I simply assign the tag to eb778eb (previously it was 0e20e4e)

**Pull request merged**
