### PR TITLE
[Stable10] MariaDB 10.2.7+

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
Backport of https://github.com/owncloud/core/pull/29100

## Related Issue
https://github.com/owncloud/core/issues/28695

## Motivation and Context
installation/update of ownCloud with recent MariaDB

## How Has This Been Tested?
By applying PR on the environment with MariaDB 10.2.8 (**testing in progress**)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]
I did not test this - but looks reasonable

**Comment by DeepDiver1975** [comment]
I suggest to kill this pr and reopen after we properly addressed the issue in the master PR #29100 

@PVince81

**Comment by VicDeo** [comment]
@DeepDiver1975 @PVince81 revived

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
