### PR TITLE
Fix: X-Accel-Redirect did not support custom data dir and local mounts

### PR DESCRIPTION
**Pull request by dratini0**
I was moving my install with a custom data directory and a local mount to ngnix, and I ran into this problem. (Cloud not download anything with MOD_X_ACCEL_REDIRECT_ENABLED on). It was a nightmare to debug, but here it is.

This contribution is MIT licensed.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by dratini0** [comment]
If I am not mistaken, these have nothing to do with my patch, right?

**Comment by MorrisJobke** [comment]
@owncloud-bot Retest this please.

**Comment by MorrisJobke** [comment]
@dratini0 Yes. It was broken on master too

**Comment by MorrisJobke** [comment]
:+1: 

@jnfrmarks This fixes itself. See http://doc.owncloud.org/server/6.0/admin_manual/configuration/xsendfile.html#id4

**Comment by brumsoel** [comment]
Are you aware that this is an exact revert of #8045? Although I'm not sure I understood what this change was about, it was meant to fix #7754.

**Comment by dratini0** [comment]
I was not aware of that. (And I was reading the 6.0 admin manual) However, I think it is not a good idea to ask server admins to to recreate getLocalFiles's functionality in nginx.conf either. Besides the complexity, what happens for example if I share something with a local user from a local mount? (I need to test that)

**Comment by josh4trunks** [comment]
Please revert these changes so they can get into the next point release. This resurrects problems I fixed here https://github.com/owncloud/core/issues/7754

As the NGINX docs state it should be passed a URI not a path
http://wiki.nginx.org/XSendfile

@dratini0 Always us the current docs, you got this working acording to the OC6 docs but this causes the aforementioned problems. Yes, it is burdonsome to have to add new local mountpoints to the NGINX config, but NGINX by its design is config burdonsome (everything is directed by a config not htaccess files). The commits here don't actually remove this burdon, any local mount points still need to be a location in the NGINX config.

**Comment by LukasReschke** [comment]
@josh4trunks The problem with the previous code are multiple things:

1. The data directory is hardcoded - it can be anywhere located as defined in config.php
2. Files might not be existent in the data directory and only in some /tmp/ folder when you for example use the files_external application with external mounts

From what I see the way to go would be then to use `getLocalFile` and use some function to resolve the relative path from the absolute one? Could somebody that uses NGINX here try this?

**Comment by josh4trunks** [comment]
@dratini0 "getLocalFiles" isn't the issue, the issue is  NGINX is expecting a URI not a file path as specified here.
http://wiki.nginx.org/XSendfile

You solution does not make this any simplier. Regardless of what owncloud passes to NGINX it will still need to parse it to a location, so unless you have "root /;" and somehow make sure the datadirectory or any local mount points doesn't collide this won't make things simpiler for the admin. You also are banking 100% on OC's authentication from stopping the webserver from reading and file on the filesystem accessible to the 'www' user ( for example session files in /tmp). At least in the model recommended by NGINX you'd need to find a comprise in the webserver (not the application) to browse to one of these locations.

**Comment by LukasReschke** [comment]
Okay – 2 seems not to be an issue when looking at the code path. So we just have to read the correct data dir from the config.

**Comment by josh4trunks** [comment]
@LukasReschke
1) isn't a problem either. Please see http://doc.owncloud.org/server/8.0/admin_manual/configuration/serving_static_files_configuration.html#nginx-x-accel-redirect

I use NGINX extensively.

**Comment by dratini0** [comment]
If I am not very much mistaken, your approach causes huge problems with
shares and local mounts, i. e. it would require every local mount and share
to be listed in the server config.

**Comment by josh4trunks** [comment]
@dratini0 yes, as seen in the OC docs I just linked every local mount point needs to be in the NGINX config. If you think it's possible, share an NGINX config that can get around this limitation.

Please explain how shares cause a problem.

**Comment by josh4trunks** [comment]
@dratini0 How do shares not work? I tested this extensively before OC7 and I don't remember them not working? Did you ever test this as not working?

**Comment by josh4trunks** [comment]
What's funny was was I was coeherced into getting X-Accel-Redirect working properly for OC7. And now I feel like I gotta maintain it =D

I even am in the process of fixing it up for the pydio project, and had to go through a several day heated explanation of how this is the proper method. After enough explanation the dev finally understood. I think it just takes everyone a while cause NGINX configs are like reading martian for those who aren't fluent.

**Comment by dratini0** [comment]
Are shares not accesed by their apparent path? (Forgive me if it is not the
right terminology, or if I am mistaken)

I think a good solution would be to combine alias, root / and internal to
achieve paths like /oc_sendfile_prefix/path/to/data_and_mounts. This would
mean a new configuration option, or better yet, a new envvar. (To store the
prefix) Sorry, i can not give a config right now, but I do believe a simple
location will work.

**Comment by josh4trunks** [comment]
@dratini0
Not my expertese but I believe shares are translated to a file before files.php
you're trying to solve a problem that isn't an issue and that you never even verified as existing?

Im open to reviewing this but I don't agree a simple location will work that doesn't have the problems I fixed here https://github.com/owncloud/core/issues/7754

**Comment by josh4trunks** [comment]
until you provide a solution that doesn't have the aforementioned issues and is simpler that mine please revert this. I'd really love if it could get in the next point release so the people I help with owncloud on FreeNAS don't keep running into this issue.

**Pull request merged**
