### PR TITLE
First we need to check the token auth module - otherwise we DOS the u…

### LINKED ISSUE #30157: [10.0.4] Sessions created from application passwords result in "Login failed" errors when used
### Context:
~~Prior to 10.0.4, there was a problem with application password and the sessions left behind after deletion (see https://github.com/owncloud/core/issues/28553). This is most likely a collateral of the new logic for the fix on https://github.com/owncloud/core/pull/28879 (lacking a migration strategy maybe)~~

The clients send 2 auth. methods (required) on the headers for **all their requests**: `Authorization: Basic` and `Cookies`. 

### Steps to reproduce
0. Setup lockout mechanism
1. Create an application password on a 10.0.4 installation
2. Use it to log in to the Desktop client 
3. Observe the server logs

### Expected behavior
Everything goes smooth

### Actual behavior
See https://github.com/owncloud/core/issues/30157#issuecomment-360444643; **each client request** results in 2 entries on the logs:

```
owncloud_1  | {"reqId":"b5PoKuAGyNkriyfFAMbG","level":2,"time":"2018-01-30T16:06:51+00:00","remoteAddr":"172.19.0.1","user":"admin","app":"core","method":"PROPFIND","url":"\/remote.php\/dav\/files\/admin\/","message":"Login failed: 'admin' (Remote IP: '172.19.0.1')"}
owncloud_1  | 172.19.0.1 - admin [30/Jan/2018:16:06:51 +0000] "PROPFIND /remote.php/dav/files/admin/ HTTP/1.1" 207 1551 "-" "Mozilla/5.0 (Macintosh) mirall/2.3.4 (build 8537)"
```

- **One successful, for the `Authorization` header.**
- **One that causes a `Login failed` in core, that can be attributed to the `Cookie`** -> the issue here; this makes password lockout mechanisms to trigger if present (see 0)

### Cause:
https://github.com/owncloud/core/pull/29525

### Related Issues:
- https://github.com/owncloud/client/issues/6258
- https://github.com/owncloud/user_ldap/issues/167

~~I'm assigning @IljaN since he's familiar with the https://github.com/owncloud/core/pull/28879 patch, feel free to change assignment.~~

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…ser backends with wrong login requests 

## Description
Login requests to the user backends (using IUserManager::checkPassword) need to be the last operation to be tried because this will cause logout of the user in worst case.

As a result any other auth checks need to be performed before (cookies, oauth and so on).

## Related Issue
fixes #30157

## How Has This Been Tested?
- manual testing following the description in #30157

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by IljaN — APPROVED** [review]
I Just did a test, error is gone. :+1:  If we can`t think of any side-effects this reordering might have.

**Review by PVince81 — APPROVED** [review]
Looks good for a workaround :+1:

However, from looking at the fix, it seems to imply that the "Login failed" error is actually logged by BasicAuthModule since it used to appear before. Now with this workaround it will appear at the end, so the behavior is correct. I'd prefer if we have the code outside of this log the entry, once all modules failed, instead of having the logging code specific to BasicAuthModule. This way we're not dependent on the order.

**Comment by DeepDiver1975** [comment]
> I'd prefer if we have the code outside of this log the entry, once all modules failed, instead of having the logging code specific to BasicAuthModule. This way we're not dependent on the order.

absolutly reasonable - but thinking about ldap it is still necessary to execute the checkPassword command within the last module - failed logins to ldap need to be prevented because they are causing logouts within ldap

**Comment by PVince81** [comment]
please backport to stable10

would be nice to only backport the relevant change, not the code styling ones...

**Comment by PVince81** [comment]
backport to hotfix branch instead ^

we'll merge it back

**Comment by DeepDiver1975** [comment]
> backport to hotfix branch instead ^

Will open a new pr with the actual fix only

**Comment by SamuAlfageme** [comment]
👍 Manages to get rid of the error in basic auth schemas. 

⚠️  Still throws the "Login Failed" messages when using OAuth2 together with application passwords:

```
{"reqId":"784b6f28-87b4-40b8-b76a-cd1c2e034234","level":2,"time":"2018-02-07T12:08:51+00:00","remoteAddr":"172.17.0.1","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/oauth2\/api\/v1\/token","message":"Login failed: 'xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69' (Remote IP: '172.17.0.1')"}
172.17.0.1 - xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69 [07/Feb/2018:12:08:51 +0000] "POST /index.php/apps/oauth2/api/v1/token HTTP/1.1" 200 1322 "-" "Mozilla/5.0 (Macintosh) mirall/2.4.0 (build 8836)"
```

Still need to check together with https://github.com/owncloud/core/pull/30365 + https://github.com/owncloud/oauth2/pull/112 **but I guess 10.0.7 should contain the fix**

**Comment by DeepDiver1975** [comment]
> Still throws the "Login Failed" messages when using OAuth2 together with application passwords:

I know why ..... hmmmm - do we want this in 10.0.7 as well? One line change
@PVince81 @SamuAlfageme

**Comment by PVince81** [comment]
@DeepDiver1975 yes please

**Comment by PVince81** [comment]
@DeepDiver1975 is this something we need to backport ? Seems to be auth related. Not sure if obsoleted by any of the other recent auth changes. How risky ?

**Pull request merged**
