### PR TITLE
Allow sub-locking with acquired exclusive lock

### LINKED ISSUE #17029: Move in, Move in overwrite and Move out fail using WebDAV with locking
https://github.com/owncloud/core/pull/16963#issuecomment-113206603

Test | Result
---- | ------
test_sharePermissions -t=0 (ALL) | :x: move_in, move_in_overwrite and move_out fail
test_sharePermissions -t=1 (READ) | :white_check_mark: 
test_sharePermissions -t=2 (READ + CREATE) | :x: move_in
test_sharePermissions -t=3 (READ + UDPATE) | :white_check_mark: 
test_sharePermissions -t=4 (READ + DELETE) | :x: move_out
test_sharePermissions -t=5 (READ + CREATE + UPDATE) | :x: move_in
test_sharePermissions -t=6 (READ + CREATE + DELETE) | :x: move_in, move_in_overwrite and move_out
test_sharePermissions -t=7 (READ + UPDATE + DELETE) | :x: move_out

Note: move_in_overwrite deletes + creates thats why READ+UPDATE is okay.

@icewind1991 @PVince81 @DeepDiver1975

### PR DESCRIPTION
**Pull request by nickvergessen**
We need a way so that subcalls of the same process can try to get locks.
This is required because storage wrappers and hooks are within the parent lock,
but currently fail to be allowed to get locks, because the file is already locked.

So I added local lock tracking, if we have an exclusive lock already. The memcache lock
can only be released when we have no more local locks. This allows subsequent calls of the
same process to lock and release files just normally.
This thereby fixes the problem of the encryption storage wrapper that makes smashbox fail, see #17029 for more details.

Fixes #17029 

@PVince81 @icewind1991 @DeepDiver1975 @schiesbn

### CODE REVIEW

**Comment by nickvergessen** [comment]
Will create a full smashbox overview over lunch

**Comment by icewind1991** [comment]
:-1: 

I don't think this is the correct way to solve the problem, having the lock actually lock the file even for the current process prevents getting unexpected results when trying to do fs work in the middle of an existing fs operation, having a storage wrapper call `getFileInfo` on a file that hasn't been created yet should not return an unspecified maybe-valid-but-relies-completely-on-the-storage-backend result, this should return an error value (or an exception, a man can dream...).

A write lock is not just to keep other processes from reading the file, it should also prevent the same process from reading the file since we can't guarantee correct behavior when reading a file that's being written to.

In the past we've had to fix multiple bugs that we're caused by wrappers/hooks/etc interfering with filesystem operations. Locking should make filesystem operations atomic and prevent unexpected behavior, something we cant do if the same process can simply ignore the lock.

**Comment by PVince81** [comment]
@nickvergessen can you run the loop=10 case you had before on this branch ?
Might help find out if it's related to double-locking within a single PHP request.

**Comment by nickvergessen** [comment]
Done with locking for today => monday

**Pull request closed without merging**
