### PR TITLE
skip btrfs hack for objectstore docker container on btrfs host

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @butonic

### CODE REVIEW

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/pull/19864/files?w=1

**Comment by MorrisJobke** [comment]
Works here on my btrfs docker host.

**Comment by icewind1991** [comment]
:+1: no longer need to modprobe loop before running

**Comment by butonic** [comment]
:+1: nice

**Pull request merged**
