### PR TITLE
[3rdparty] Bump symfony/event-dispatcher to 2.7.7

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/221

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by rullzer** [comment]
Updated and rebased.

**Comment by DeepDiver1975** [comment]
> Updated and rebased.

thx

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
