### PR TITLE
[stable8] fix warning in gc

### LINKED ISSUE #14696: "Only variables should be passed by reference" - fileglobalgc.php
### Steps to reproduce
1. Upgrade to `owncloud-server-8.0.1-11.1.noarch` on CentOS 7
2. Run cron.php using system cron.

### Expected behaviour
No PHP errors or warnings.

### Actual behaviour
Each invocation of cron.php results in warnings:

    {"reqId":"3833c91003ad6f7edbd63762bb062ccf","remoteAddr":"","app":"PHP","message":"Only variables should be passed by reference at \/var\/www\/html\/owncloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-03-05T13:30:01+11:00"}
    {"reqId":"3833c91003ad6f7edbd63762bb062ccf","remoteAddr":"","app":"PHP","message":"chmod(): Operation not permitted at \/var\/www\/html\/owncloud\/lib\/private\/log\/owncloud.php#85","level":3,"time":"2015-03-05T13:30:01+11:00"}

Resolved (temporarily) by changing line 50 from:

    array_walk($this->getExpiredPaths($cacheDir, $now), 'unlink');

To:

    $expiredPaths = $this->getExpiredPaths($cacheDir, $now);
    array_walk($expiredPaths, 'unlink');

### Server configuration
**Operating system**:

CentOS 7

**Web server:**

Apache 2.4 => `httpd-2.4.6-19.el7.centos.x86_64`

**Database:**

MySQL => `mariadb-server-5.5.41-2.el7_0.x86_64`

**PHP version:**

`php-5.4.16-23.el7_0.3.x86_64`

**ownCloud version:** (see ownCloud admin page)

8.0.1 (stable) (RPM: owncloud-server-8.0.1-11.1.noarch)

**Updated from an older ownCloud or fresh install:**

Updated using yum from http://download.opensuse.org/repositories/isv:/ownCloud:/community/CentOS_CentOS-7/

**List of activated apps:**

Activity, Deleted files, External storage support, First Run Wizard, Mail Template Editor, PDF Viewer, Pictures, Server-side Encryption, Share Files, Text Editor, Updater, Versions, Video Viewer.

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'oc89b470161f',
  'passwordsalt' => 'passwordsalt',
  'trusted_domains' => 
  array (
    0 => 'owncloud.mydomain.net',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'version' => '8.0.1.1',
  'dbtype' => 'mysql',
  'dbname' => 'ownclouddb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ownclouduser',
  'dbpassword' => 'dbpassword',
  'installed' => true,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'mydomain.net',
  'logtimezone' => 'Australia/Melbourne',
  'logfile' => '/var/log/owncloud.log',
  'loglevel' => '2',
  'log_authfailip' => true,
  'overwritehost' => 'owncloud.mydomain.net',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'forcessl' => true,
  'theme' => '',
  'secret' => 'secret',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

No.

**Are you using encryption:** yes/no

Yes.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No.

### PR DESCRIPTION
**Pull request by nickvergessen**
Backport of #14550 
Fix #14696 

@icewind1991 @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by pierrejochem** [comment]
:+1:

**Comment by hmuus** [comment]
This only shifts the error message from line 50 to line 51 .. still an issue .. each cron cycle adds some 70 entries to the log

**Comment by bedzkowp** [comment]
I confirm, it's not a fix.

**Comment by pierrejochem** [comment]
I can confirm it to. What a about this change:

$paths = $this->getExpiredPaths($cacheDir, $now);
if(is_array($paths) && count($paths) > 0) {
	array_walk($paths, 'unlink');
}

**Comment by hmuus** [comment]
@bedzkowp 
locked up what is in there, found

```PHP
	$paths = $this->getExpiredPaths($cacheDir, $now);
	array_walk($paths, function($file) {
		unlink($file);
	});
```
will give it a try..

..tried..seems to work, at least the last cron cycle was pretty silent..

**Comment by pierrejochem** [comment]
Okay then I propose the more secure solution :-P :

```php
$paths = $this->getExpiredPaths($cacheDir, $now);
array_walk($paths, function($file) {
    if (file_exists($file)) {
        unlink($file);
    }
});
```

**Comment by pierrejochem** [comment]
https://github.com/owncloud/core/commit/42fcd0e8b7bda681069a79be1511a2fe407f09fa

@hmuus It looks like that your way is in the master branch :+1:

**Comment by ravermeister** [comment]
@pierrejochem but your solution is more safe, Iwould prefer it...

**Comment by MorrisJobke** [comment]
@nickvergessen Can you have a look at this?

**Comment by nickvergessen** [comment]
Well that's a different issue and this here is a merged PR.
So i suggest a new issue + PR is done by any of those who commented to have a problem here.

**Comment by Xenopathic** [comment]
@MorrisJobke @nickvergessen That issue was fixed on stable8 over at #15079

**Comment by pierrejochem** [comment]
@ravermeister : https://github.com/owncloud/core/pull/15354#issuecomment-88414832 ;-)

**Comment by hmuus** [comment]
13 days ago I altered the fileglobalgc to what i found in #14696 and commented here, that this will just shift the line number while comming up with same error

the immidiate comment from bedzkowp was, that he solved it with a copy from master branch .. so ..
i look up what was there .. and post it here so everybody can find what is already in master and which is working :+1: 

it seems the topic now makes a second run ..  

by the way, the working code from master was not in the updates received some 6 days ago and i needed to again repair fileglobalgc :-1:

**Pull request merged**
