### PR TITLE
Allow automatic dependency injection for OCP\Mail\Mailer

### PR DESCRIPTION
**Pull request by nickvergessen**
@MorrisJobke @BernhardPosselt @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
👍

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
@nickvergessen Does it make sense to backport this? I would vote for this. Because already in older versions the public interface is available, but not usable with the automatic DI.

**Comment by nickvergessen** [comment]
> Does it make sense to backport this? I would vote for this. Because already in older versions the public interface is available, but not usable with the automatic DI.

Not sure, the problem is if an app uses it, they have to require a min. maintenance version. But well works for me, the authors can then also just state "please update to latest maintenance"

**Comment by MorrisJobke** [comment]
@karlitschek for this backport

**Comment by karlitschek** [comment]
hmm. it has a risk to break apps. but it is the 'right' fix. backport is fine. 👍

**Comment by nickvergessen** [comment]
No need to backport, otherwise we have apps that depend on minor versions.
No app can break because of this, but an app that uses it does not work on previous minors.

I'd say bad luck, but for 9.0 you have to manually inject it, in 9.1+ you can use auto again?

**Comment by BernhardPosselt** [comment]
Depending on a minor version is IMHO no problem, since you can do this very easily in your info.xml. Examples here would be apps that depend on a bugfix in a minor version. 

All depends on how you want to define the latest number :)

**Pull request merged**
