### PR TITLE
[WIP] Update public.php

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by MorrisJobke** [comment]
@FacedownPhp Thanks for this PR. Some additional context would be really nice. What issue do you have? How can someone reproduce this?

**Comment by LukasReschke** [comment]
Generally speaking: That change seems to make sense for me when used in combination with some proxies etc…

However, I'd like to streamline the code a bit, this can also be achieved using `OC_Response::setStatus(\OC_Response::STATUS_NOT_FOUND)` which is easier to understand and to port to non-static code in the future.

@FacedownPhp Could you adjust this please in your fork so that this PR gets updated? Thanks!

**Comment by LukasReschke** [comment]
It also makes sense to replace this in other parts of the code as well where we currently hard-code `HTTP/1.` - would be awesome if you could grep for those and replace them as well :smile:

**Comment by LukasReschke** [comment]
(or if you have some creative ideas what one could do with injected headers)

**Comment by DeepDiver1975** [comment]
no feedback -> close

**Pull request closed without merging**
