### PR TITLE
Use intermediate root authority + sign other release channels

### PR DESCRIPTION
**Pull request by LukasReschke**
Danimo proposed to use an intermediate root authority for signing purposes which makes sense considering that we may also sign updates this way in the future. So this uses now an intermediate authority.  Also contains a security hardening so somebody with push privileges to core cannot tamper with our signing machine.

This and https://github.com/owncloud/updater/pull/221 would be the last step before we can regularly activate code signing on the release machine. Will get the certificate authority reviewed by @danimo and friends' but that is independent from this.

@karlitschek @danimo

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by LukasReschke** [comment]
Ups. Closed the wrong one :speak_no_evil:

**Comment by LukasReschke** [comment]
To test this:

1. Download https://download.owncloud.org/community/daily/owncloud-daily-master.tar.bz2
2. Install it
3. See a big yellow warning
4. Replace resources/codesigning/core.crt and resources/codesigning/root.crt with the versions from this PR
5. Press rescan in the admin setups warning
6. See a big yellow warning
7. Click on details. See that only the hash on the certificate mismatches.

So once this is merged our builds will be properly signed.

@MorrisJobke @rullzer Mind testing? THX.

**Comment by karlitschek** [comment]
:+1:

**Comment by karlitschek** [comment]
Who can help to review this? @DeepDiver1975 @MorrisJobke @PVince81 ?

**Comment by PVince81** [comment]
@LukasReschke your test steps don't seem to use the code from this PR at all, only the certificates. So testing the daily would only test the certificates, not the code ?

**Comment by LukasReschke** [comment]
> @LukasReschke your test steps don't seem to use the code from this PR at all, only the certificates. So testing the daily would only test the certificates, not the code ?

The code is only different in the sense that it affects the write operations for the signature not the reading. But you can also replace all files and just keep the signature if that makes you feel more comfortable.

**Comment by PVince81** [comment]
@LukasReschke but then if I copy over all the code, what is the point of downloading the stable build ? Does it have an old signature that would get updated ?

**Comment by LukasReschke** [comment]
> @LukasReschke but then if I copy over all the code, what is the point of downloading the stable build ? Does it have an old signature that would get updated ?

You'll see a big yellow error message and if you click on that and follow it you will see which files have invalid hashes. Which are the ones changed from here. An invalid signature does not make ownCloud unusable, it just shows some nag screen :speak_no_evil:

**Comment by LukasReschke** [comment]
Nag screens:

**Comment by PVince81** [comment]
Okay, so before copying the certs it looks like all files fail the cert test.
After copying the ones from this PR, only the cert files themselves fail the test.

If that's the expected behavior, the it works :+1:

**Pull request merged**
