### PR TITLE
Fix integration tests findLines strpos check

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Make the check more robust.
2) Fix tests that now fail because they were not really testing for quite the correct thing.
3) (in the 2nd commit) transfering => transferring - fix typo

## Related Issue
#28919 

## Motivation and Context
False positives can be returned, as described in issue.

## How Has This Been Tested?
Jenkins will tell.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
Did I make this failure in the integration tests:
```
  Scenario: Merging shares for recipient when shared from outside with group then user and recipient renames in between                                # /var/lib/jenkins/workspace/owncloud-core_core_PR-28922-NYQJNLXBXH4PCVWHDSEL4GIELQYJWUS6TAU5TNZUM33YUIWXIPYA/tests/integration/features/sharing-v1.feature:914
    Given As an "admin"                                                                                                                                # FeatureContext::asAn()
[Thu Sep  7 05:43:16 2017] ::1:41529 [404]: /ocs/v2.php/cloud/users/user0
[Thu Sep  7 05:43:17 2017] ::1:41532 [200]: /ocs/v1.php/cloud/users
[Thu Sep  7 05:43:18 2017] ::1:41537 [200]: /ocs/v1.php/cloud/users/user0
[Thu Sep  7 05:43:18 2017] ::1:41545 [200]: /ocs/v2.php/cloud/users/user0
    And user "user0" exists                                                                                                                            # FeatureContext::assureUserExists()
[Thu Sep  7 05:43:18 2017] ::1:41549 [404]: /ocs/v2.php/cloud/users/user1
[Thu Sep  7 05:43:19 2017] ::1:41554 [200]: /ocs/v1.php/cloud/users
[Thu Sep  7 05:43:20 2017] ::1:41557 [200]: /ocs/v1.php/cloud/users/user1
[Thu Sep  7 05:43:20 2017] ::1:41565 [200]: /ocs/v2.php/cloud/users/user1
    And user "user1" exists                                                                                                                            # FeatureContext::assureUserExists()
[Thu Sep  7 05:43:20 2017] ::1:41569 [404]: /ocs/v2.php/cloud/groups/group1
[Thu Sep  7 05:43:20 2017] ::1:41570 [200]: /ocs/v1.php/cloud/groups
[Thu Sep  7 05:43:21 2017] ::1:41573 [200]: /ocs/v2.php/cloud/groups/group1
    And group "group1" exists                                                                                                                          # FeatureContext::assureGroupExists()
[Thu Sep  7 05:43:21 2017] ::1:41577 [200]: /ocs/v2.php/cloud/users/user1/groups
[Thu Sep  7 05:43:21 2017] ::1:41578 [200]: /ocs/v1.php/cloud/users/user1/groups
[Thu Sep  7 05:43:21 2017] ::1:41580 [200]: /ocs/v2.php/cloud/users/user1/groups
    And user "user1" belongs to group "group1"                                                                                                         # FeatureContext::assureUserBelongsToGroup()
[Thu Sep  7 05:43:21 2017] ::1:41582 [201]: /remote.php/webdav/merge-test-outside-groups-renamebeforesecondshare
    And user "user0" created a folder "/merge-test-outside-groups-renamebeforesecondshare"                                                             # FeatureContext::userCreatedAFolder()
[Thu Sep  7 05:43:21 2017] ::1:41586 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Fmerge-test-outside-groups-renamebeforesecondshare
[Thu Sep  7 05:43:22 2017] ::1:41587 [200]: //ocs/v1.php/apps/files_sharing/api/v1/shares
[Thu Sep  7 05:43:22 2017] ::1:41589 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Fmerge-test-outside-groups-renamebeforesecondshare
    When folder "/merge-test-outside-groups-renamebeforesecondshare" of user "user0" is shared with group "group1"                                     # FeatureContext::assureFileIsSharedWithGroup()
[Thu Sep  7 05:43:22 2017] ::1:41593 [201]: /remote.php/webdav/merge-test-outside-groups-renamebeforesecondshare
    And User "user1" moved folder "/merge-test-outside-groups-renamebeforesecondshare" to "/merge-test-outside-groups-renamebeforesecondshare-renamed" # FeatureContext::userMovedFile()
[Thu Sep  7 05:43:22 2017] ::1:41594 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Fmerge-test-outside-groups-renamebeforesecondshare
[Thu Sep  7 05:43:22 2017] ::1:41595 [200]: //ocs/v1.php/apps/files_sharing/api/v1/shares
[Thu Sep  7 05:43:22 2017] ::1:41597 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Fmerge-test-outside-groups-renamebeforesecondshare
    And folder "/merge-test-outside-groups-renamebeforesecondshare" of user "user0" is shared with user "user1"                                        # FeatureContext::assureFileIsShared()
[Thu Sep  7 05:43:23 2017] ::1:41599 [404]: /remote.php/webdav/merge-test-outside-groups-renamebeforesecondshare-renamed
    Then as "user1" gets properties of folder "/merge-test-outside-groups-renamebeforesecondshare-renamed" with                                        # FeatureContext::asGetsPropertiesOfFolderWith()
      | {http://owncloud.org/ns}permissions |
    And the single response should contain a property "{http://owncloud.org/ns}permissions" with value "SRDNVCK"                                       # FeatureContext::theSingleResponseShouldContainAPropertyWithValue()
      Cannot find property "{http://owncloud.org/ns}permissions" with "SRDNVCK" (Exception)
    And as "user1" the folder "/merge-test-outside-groups-renamebeforesecondshare" does not exist                                                      # FeatureContext::asTheFileOrFolderDoesNotExist()
```

But it passes in stable10 in the backport PR #28933 ???

I will rebase to make the CI run again and see if this is a "random" fail.

**Comment by PVince81** [comment]
@phil-davis no, you only won the lottery again...

**Comment by phil-davis** [comment]
Do we have any idea why this test can sometimes fail?
(it would be good to fix the issue)

**Comment by phil-davis** [comment]
@PVince81 this is already up-to-date so I cannot rebase and push without making an actal change. I do not want to touch the code because it is already backported to stable10...
Can you do one of:
1) merge it anyway
2) restart Jenkins (I wish PR owners could do that themselves)
3) merge something else into master, then I will be able to pull down the changed master and rebase to it, triggering CI again myself.

**Comment by PVince81** [comment]
I already did 2 after commenting

**Comment by PVince81** [comment]
Restarting builds require having an account on Jenkins. I don't think we can automatically give access to PR committers. But then, I don't know the config details of Jenkins. We could create accounts for more people there.

**Comment by phil-davis** [comment]
@PVince81 CI success - this is already backported in stable10, so I guess you will approve and merge here.

**Pull request merged**
