### PR TITLE
fix for users creation in ldap test

### PR DESCRIPTION
**Pull request by haribhandari07**
## Description

```Given these users have been created with default attributes and skeleton files: # FeatureContext::theseUsersHaveBeenCreated()``` 
step fails with
```  GuzzleHttp\Exception\ClientException: Client error response [url] http://server/ocs/v2.php/cloud/users [status code] 400 [reason phrase] Bad Request in /var/www/owncloud/server/lib/composer/guzzlehttp/guzzle/src/Exception/RequestException.php:89```

This pull request fixes this issue https://github.com/owncloud/user_ldap/issues/429
## Related Issue

Fix for https://github.com/owncloud/user_ldap/issues/429
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
@HariBhandari07 somehow you have got lots of `l10n` translation files into this PR ???

**Review by dpakach — COMMENTED** [review]
LGTM :+1:  if user_ldap tests pass then its good.

**Review by skshetry — COMMENTED** [review]
LGTM

**Review by paurakhsharma — COMMENTED** [review]
Looks good :+1:

**Review by phil-davis — APPROVED** [review]

**Comment by HariBhandari07** [comment]
Backport on #35573

**Pull request merged**
