### PR TITLE
[stable9] Sabre plugin browser error page

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of https://github.com/owncloud/core/pull/23557

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Message is too general. In 8.2 we had specific messages in error pages.

Error message for a firewall rule block:

In stable9 + this patch:

Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: HIDDEN_IP
Request ID: 95P8aMF7vOuzr9ohBg/V

In stable8.2:

Access to this resource has been forbidden by a file firewall rule.	
If you feel this is an error, please contact your administrator or logout.

**Comment by DeepDiver1975** [comment]
Screenshots please. THX

**Comment by SergioBertolinSG** [comment]
The standard error page in both cases:

screen shot 2016-03-28 at 12 26 41

Only the text message is different. Style and images is fine.

**Comment by DeepDiver1975** [comment]
Which exception is thrown the firewall app?

**Comment by SergioBertolinSG** [comment]
It should answer 403 (Forbidden) instead of 500.

**Comment by DeepDiver1975** [comment]
I need to know the explicit exception type.

**Comment by SergioBertolinSG** [comment]
ForbiddenException

**Comment by nickvergessen** [comment]
@DeepDiver1975 `OCP\Files\ForbiddenException` https://github.com/owncloud/firewall/blob/master/lib/firewall.php#L161-L167

**Comment by DeepDiver1975** [comment]
Okay - I have to test this and see why this is not converted into a proper sabre dav excpeption ...

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG this is what I see when trying to download a blocked file
I cannot reproduce your screenshot

bildschirmfoto von 2016-04-04 13-49-22

**Comment by SergioBertolinSG** [comment]
Just reproduced the same way:
screen shot 2016-04-04 at 16 53 05

**Comment by SergioBertolinSG** [comment]
OK it works :+1:.

As addressed by @DeepDiver1975 the problem was not related and it was because the user was never logged in and the firewall was breaking the data folder initialization.

I'll open another issue about it.

**Comment by DeepDiver1975** [comment]
> I'll open another issue about it.

THX

**Comment by DeepDiver1975** [comment]
@cmonteroluque merge this on into 9.0.1? originial issue was a regression

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
