### PR TITLE
IMemcacheTTL was backported to 8.2.2

### PR DESCRIPTION
**Pull request by MorrisJobke**
see #21113 

This only updates the PHPDoc

cc @PVince81 @icewind1991 @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by rullzer** [comment]
:+1:

**Comment by nickvergessen** [comment]
In this case okay, in general the 9.0 reference should be kept, if it is not 9.0.0

**Comment by MorrisJobke** [comment]
> In this case okay, in general the 9.0 reference should be kept, if it is not 9.0.0

yep

**Pull request merged**
