### PR TITLE
Issue 19147 backport update break

### LINKED ISSUE #19147: Backport request of #18684
Hi,

to avoid that this got lost please consider to backport #18684 to stable8.1

Within this week we had at least 6-7 people at the forums or IRC breaking their encryption setup because they where directly upgrading from 7.0.x to 8.1.3 which is definitely not supported.

### PR DESCRIPTION
**Pull request by nickvergessen**
@karlitschek backport to 8.1, only allowing upgrades from 8.0 or later: #18684 

@PVince81 @MorrisJobke @RealRancor 

Fix #19147

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense as discussed :+1:

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
What happened to CI ? Did it slide out of existence ? @DeepDiver1975

**Comment by PVince81** [comment]
ah! here it is, all green. Long time haven't seen green :smile:

**Pull request merged**
