### PR TITLE
[8.2] Add ttl for redis based locking

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/owncloud/core/pull/21073

### CODE REVIEW

**Comment by PVince81** [comment]
Running smashbox tests with redis...

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I updated the PHPDoc of master too https://github.com/owncloud/core/pull/21131

**Pull request merged**
