### PR TITLE
fix: Update StoragesBackendService.php to default handling

### PR DESCRIPTION
**Pull request by jnweiger**
fix: another occurance of #41272

### CODE REVIEW

**Comment by pako81** [comment]
category is missing in commit message

**Review by pako81 — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
The commit needs to have the commit message edited, and then force-push the change.

**Comment by jnweiger** [comment]
> The commit needs to have the commit message edited, and then force-push the change.

cannot be done through web UI? sigh.
second attempt... done.

**Comment by phil-davis** [comment]
> cannot be done through web UI?

You can edit the PR title, but that is not editing the commit message of the commit(s).

**Comment by jnweiger** [comment]
@phil-davis  I still struggle to understand how to make drone happy.
This error occurs in php unit tests, but seems unrelated to my one-liner fix:

----
There was 1 failure:

1) Test\Files\External\StoragesBackendServiceTest::testUserMountingBackends

OCP\Files\External\Backend\Backend::removeVisibility(1) was not expected to be called.

**Comment by phil-davis** [comment]
```
$ make test-php-unit NOCOVERAGE=true TEST_PHP_SUITE=tests/lib/Files/External/StoragesBackendServiceTest.php
...
PHPUNIT="/home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/phpunit" build/autotest.sh sqlite tests/lib/Files/External/StoragesBackendServiceTest.php
Using PHP executable /usr/bin/php
Parsing all files in lib/public for the presence of @since or @deprecated on each method...

Using database oc_autotest
Setup environment for sqlite testing on local storage ...
Updated 0 paths from the index
Installing ....
creating sqlite db
ownCloud was successfully installed
Testing with sqlite ...
No coverage
/home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/phpunit --configuration phpunit-autotest.xml --log-junit autotest-results-sqlite.xml ../tests/lib/Files/External/StoragesBackendServiceTest.php 
PHPUnit 9.6.19 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.33
Configuration: phpunit-autotest.xml

....F.                                                              6 / 6 (100%)

Time: 00:00.023, Memory: 20.00 MB

There was 1 failure:

1) Test\Files\External\StoragesBackendServiceTest::testUserMountingBackends
OCP\Files\External\Backend\Backend::removeVisibility(1) was not expected to be called.

/home/phil/git/owncloud/core/lib/private/Files/External/StoragesBackendService.php:124
/home/phil/git/owncloud/core/tests/lib/Files/External/StoragesBackendServiceTest.php:177

FAILURES!
Tests: 6, Assertions: 25, Failures: 1.
make: *** [Makefile:194: test-php-unit] Error 1
```

I get this unit test fail locally with your branch but not with `master`

I will have a look at what happens differently in the code.

**Comment by phil-davis** [comment]
Should be fixed - now the call to `getAppValue` is done with `getAppValue('files_external', 'allow_user_mounting', 'no')`
So we need to put the 'no' into the test `returnValueMap` and then the test mocking will recognize the call and return the needed value.

**Pull request merged**
