### PR TITLE
[stable9] Fix call to disk_free_space when a file is provided

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/22900 to stable9

Please review @icewind1991 @MorrisJobke @rullzer @nickvergessen

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/22899

**Comment by PVince81** [comment]
Rebased for CI

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
