### PR TITLE
[WIP] Live without files app

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
The files app shall live a life more on it's own in an repo of its own.

## Motivation and Context
Shrink core ... deploy files app via marketplace

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
js test go :boom:

**Comment by PVince81** [comment]
Additional tasks:

- [ ] setup new repo for files with CI
- [ ] move files specific JS tests there
- [ ] move sharing specific JS code from files_sharing to files app
- [ ] make "files_sharing" an always-on backend app which provides the OCS Share API (still possible to disable through the admin checkbox)

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/files

**Comment by PVince81** [comment]
Added "move all OCC commands to core as they are not related to the web UI but rather to core (also see https://github.com/owncloud/core/issues/28561)" to task list

**Comment by PVince81** [comment]
same for background jobs...

**Comment by PVince81** [comment]
added "move mimetype detector classes to core (core seems to use them directly from server.php)"

**Comment by PVince81** [comment]
moving to "triage" as this is likely going to take more time (see checkboxes)

**Comment by PVince81** [comment]
we're not ready for that. close ?

we first need to strip the backend parts of the files app to core, then we can maybe plug in a shiny new frontend... there's still way too much important stuff in the files app, even some commands like "occ files:scan"

**Comment by DeepDiver1975** [comment]
There are 2 commits which might still be of value:
https://github.com/owncloud/core/pull/28440/commits/ddfbcdd65b346776bcb791aa8d3a0d07ee5b9811

https://github.com/owncloud/core/pull/28440/commits/85506ef4100905408ddc49709eeb68679c0241fc

These two will fix the situation where the files app is not loaded - sooner or later we might need this ....


For the rest of it: 💣  - we shall also remove the files repo

**Pull request closed without merging**
