### PR TITLE
Only if the files system is properly setup FileHome can properly be i…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…nitialized

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/3591

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by micbar** [comment]
LGTM

**Comment by micbar** [comment]
If this should go in, we need to merge on monday.
@DeepDiver1975 Could you provide an CHANGELOG item?

**Comment by DeepDiver1975** [comment]
> Could you provide an CHANGELOG item?

done - changed code set is not covered by unit tests at the moment. Would need refactoring .... I'd not introduce more code changes at this point in time

**Review by micbar — APPROVED** [review]
👍

**Pull request merged**
