### PR TITLE
Commit new version of phpStorms codeStyleSettings.xml

### PR DESCRIPTION
**Pull request by nickvergessen**
This should allow easy rebasing and branch switching for now,
until the discussion about removing .idea is finished

Related #13324 

@DeepDiver1975 @MorrisJobke @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Tested - works on IntelliJ Idea 14 :+1:

**Comment by nickvergessen** [comment]
I have IntelliJ phpStorm 8.0.3

**Comment by DeepDiver1975** [comment]
hmm - why is this change required?

foe me the code style is set to project - we shall not care about that preferrend default

**Comment by LukasReschke** [comment]
> hmm - why is this change required?
> foe me the code style is set to project - we shall not care about that preferrend default

Well because if I, @MorrisJobke or @nickvergessen want to commit something we always have to stash this file as it changed. But if you have an alternative suggestion how we can change PHPStorm from doing this nasty thing all the time we're open to it ;-)

**Comment by DeepDiver1975** [comment]
I'm not questioning that this is annoying for you. I'm questioning why your phpstorm installation wants to insert this line. Mine doesn't!

**Comment by nickvergessen** [comment]
this file is supposed to help. I really can't see that atm.... :bomb:

**Comment by LukasReschke** [comment]
@DeepDiver1975 Which PHPStorm version? - Any non default settings?

**Comment by DeepDiver1975** [comment]
> Which PHPStorm version?

8.0.3



> Any non default settings?

No - why should I :wink:

**Comment by schiesbn** [comment]
I have exactly the same problem since today. Don't know what changed compared to yesterday.

**Comment by DeepDiver1975** [comment]
This happened to me as well - afaik this helped:
- close the ide
- revert the changed of that settings xml
- open up the ide again

**Comment by schiesbn** [comment]
Indeed, this seems to work. Thanks!

**Comment by MorrisJobke** [comment]
> Indeed, this seems to work. Thanks!

But only for a limited time. and it's annoying.

**Pull request closed without merging**
