### PR TITLE
Full content width search results

### PR DESCRIPTION
**Pull request by butonic**
This introduces
- Full content width search results
- OC.Search
- icons instead of type text
- formatters and handlers for search results
- cleans up css
- uses mime instead of mime_type
- deprecates OC.search.customResults and OC.search.resultTypes
- by default only handles generic search results
- comes with formatters and handlers for `file` and `folder` types
- restores the old result template when no formatter is present for a specific type to ensure backwards compatibility

@PVince81 how do I get the mimetype icon for a file when I am in the contacts app? How do I better encapsulate OC.Search?

@jancborchardt @MTRichards UI / css input is very welcome. I wanted to get this out as the first draft to discuss it.

TODO
- [ ] better formatters and handlers for calendar, contacts, bookmarks ...
- [x] remove resultTypes and customResults
- [x] don't lazy load the search result js & css stuff to make it more themable?
- [x] ajax scrolling for results

cc @andrewsbrown @MorrisJobke

### CODE REVIEW

**Comment by jancborchardt** [comment]
Do you need another design review from me? And how’s the status on this in regards to ownCloud 8? 8.1 or postpone to 9?

**Comment by MorrisJobke** [comment]
> 8.1 or postpone to 9?

ownCloud 9 is the first release in 2016 ... but I think this is ready for review

**Comment by jancborchardt** [comment]
... I meant: backporting or wait for 8.1? (The non-semantic versioning is still a bit confusing.)

**Comment by butonic** [comment]
This has got a feature freeze exemption, so it will make it into OC8 if I can resolve the provisioning API test failures until then. I am on it.

**Comment by DeepDiver1975** [comment]
> f I can resolve the provisioning API test failures until then. I am on it.

they are failing on master as well -> ignore

**Comment by MorrisJobke** [comment]
* [ ] search for `p` in a folder where no entry has a `p` in it's name -> white page without feedback

**Comment by MorrisJobke** [comment]
Mockup for the filtered view:
bildschirmfoto von 2015-01-02 11-06-10

**Comment by MorrisJobke** [comment]
* [ ] update search term doesn't clear results
      * having a file called `Plastik` in a subfolder
      * search for `Pla` -> list file
      * add a `d` to the search term -> file is still listed even if the search term is now `Plad` and doesn't match the filename

**Comment by MorrisJobke** [comment]
* [ ] The spinner just pops up really shortly before the result is shown. During the waiting for the response it just displays a white page

**Comment by butonic** [comment]
@PVince81 hm how can I access the filelist for trashbin, favorites etc? I found the navigation but it will only give me the id or the container, not the FileList object that has the filter method I want to call...

I was planning to make the filer logic access the currently active filelist but I cannot find a codepath to access is. The show event maybe. Will try that later ...



Am 2. Januar 2015 14:47:26 MEZ, schrieb Morris Jobke <notifications@github.com>:
>* [ ] The spinner just pops up really shortly before the result is
>shown. During the waiting for the response it just displays a white
>page
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/pull/12653#issuecomment-68527408

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MorrisJobke** [comment]
Looks fine for me :+1:

**Comment by butonic** [comment]
Ok, I fixed all the remaining issues and some cornercases I found while testing. Final :+1:s please!

**Comment by icewind1991** [comment]
Seems to work good now :+1:

**Comment by MorrisJobke** [comment]
Jenkins PR: #13111

**Comment by MorrisJobke** [comment]
* [ ] search result is show in files app -> switch to trashbin -> glitch

**Comment by MorrisJobke** [comment]
* [ ] vanish search term if you click in the filtered list on a folder (create folder "test" in root, search for "tes" in root -> click on filtered file list -> glitch

**Comment by butonic** [comment]
@MorrisJobke fixed!

**Comment by MorrisJobke** [comment]
@butonic Yes. I cleared the cache. I just want to search for 'Plas' and it simply just shows the spinner and no result are shown - just a spinner.

**Comment by MorrisJobke** [comment]
* [ ] in trashbin: if no element in current view and no result in the subfolders is present it looks like this:
bildschirmfoto von 2015-01-06 14-14-49

**Comment by butonic** [comment]
@MorrisJobke fixed. `$('#elementid') always returns one result. using class fixes this

**Comment by MorrisJobke** [comment]
@butonic And I found another problem :)

You all know of my file `Plastik.docx`

* search for `Pla` -> search result is correct
* append a `s` to search for `Plas` -> search result seems to be fine
* remove the `s` and append a `d` to search for `Plad` -> still the same result, but it actually should list nothing
* looking at the network tab it shows that it alwas search for `Pla` and doesn't update the search term -> seems to be a variable caching issue (loading of value of a cached jQuery selcetion or something like that)

* [ ] have fun fixing another of my issues

**Comment by MorrisJobke** [comment]
Now I'm fine with this :+1: Thanks for all the hard work :)

**Comment by MorrisJobke** [comment]
I also updated the Jenkins PR ;)

**Comment by MorrisJobke** [comment]
@icewind1991 was fine with this and now also Jenkins https://github.com/owncloud/core/pull/13111#issuecomment-68880749 is fine with this -> merge

**Comment by butonic** [comment]
cc @karlitschek @jancborchardt full content search results is in :)

**Comment by karlitschek** [comment]
@butonic Very cool. Thanks

**Comment by jancborchardt** [comment]
@butonic nice, finally we got it done! :) :rocket:

**Comment by jancborchardt** [comment]
Submitted two follow-up issues for some problems I found. Only nitpicking though, the overall result is DAMN AWESOME! :)

* Initial load shows »No files yet« https://github.com/owncloud/core/issues/13141
* What to display when there are no results https://github.com/owncloud/core/issues/13142

**Pull request merged**
