### PR TITLE
Rename "local link" to "private link"

### LINKED ISSUE #27593: Change name of 'local/permanent link' to 'private link'
To enhance usability and ease-of-use we decided to change the name of the feature to 'private link' as it reflects better that you need access, doesn't necessarily exclude other users and fits with public links.

- [ ] Change the name as discussed
- [ ] Maybe display some hint: e.g. "Private link: Only people who have access to the file/folder can use it. Use it as a permanent link for yourself or to point others to files or folders within shares"

@PVince81

### PR DESCRIPTION
**Pull request by PVince81**
@pmaier1 @felixheidecke please review

private_link

Fixes https://github.com/owncloud/core/issues/27593

### CODE REVIEW

**Comment by pmaier1** [comment]
Great! :+1:

**Comment by PVince81** [comment]
I find this big block to be a bit heavy, but ok.

If @felixheidecke doesn't object we can merge this.

**Comment by pmaier1** [comment]
> I find this big block to be a bit heavy, but ok.

True. Maybe @felixheidecke comes up with a better idea, otherwise I'm fine with this as it's definitely better than no explanation.

**Comment by PVince81** [comment]
I don't think we can add line breaks in a tooltip, so if there is a better way it will like have to be a different revamped UI. I think I'll merge this for now.

**Comment by felixheidecke** [comment]
7e419d4a-1b81-11e7-8ec6-fa7ab1b4175f

Still a double wording?!

**Comment by pmaier1** [comment]
> Public-Link people have "access" too but can't use it ;-)

This does not make sense or at least I don't understand it^^

There are two use cases for the private link:
1) Have a link to a certain file/folder that will stay as it is as long as the file is available (this is why I described it as 'permanent')
2) Point others to certain files/folders within shares

I'm also not totally happy with it but I don't know how we could make it more clear :/

**Pull request merged**
