### PR TITLE
Update ca-bundle.crt

### LINKED ISSUE #27304: Update shipped resources/config/ca-bundle.crt
It seems the https://github.com/owncloud/core/blob/master/resources/config/ca-bundle.crt was updated the last time one year ago with https://github.com/owncloud/core/pull/21862

I don't know how often this file is updated by Mozilla so it might worth to update that at least once a year.

*Edit*
Just had a short compare with https://github.com/bagder/ca-bundle/blob/master/ca-bundle.crt and it seems 9 CAs where removed and 16 CAs (including Amazons) where added in the meantime.

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
Update shipped cert list.
Build with https://github.com/curl/curl/blob/master/lib/mk-ca-bundle.pl

## Related Issue
Closes https://github.com/owncloud/core/issues/27304

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by PVince81** [comment]
@VicDeo thanks. Do we have docs somewhere about how to do this ? If not, please make a documentation ticket with steps.

@Peter-Prochaska please review this certs update.

cc @DeepDiver1975

**Review by peterprochaska — APPROVED** [review]

**Comment by PVince81** [comment]
@VicDeo I guess we should backport this ?

**Comment by kdslkdsaldsal** [comment]
> I guess we should backport this ?

9 CAs where removed and 16 CAs where added since the last update so it could make sense to backport this.

**Comment by Peter-Prochaska** [comment]
That makes sense.

**Comment by VicDeo** [comment]
Stable9.1 https://github.com/owncloud/core/pull/27523

**Pull request merged**
