### PR TITLE
Add a public interface for the language factory so apps can use it

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 as per discussion
@LukasReschke

Related #14663

### CODE REVIEW

**Comment by PVince81** [comment]
```
06:12:40 + ./autotest.sh sqlite
06:12:40 Using PHP executable /home/vagrant/.phpenv/shims/php
06:12:40 Parsing all files in lib/public for the presence of @since or @deprecated on each method...
06:12:40 
06:12:40 PHPDoc is needed for OCP\L10N\IFactory::IFactory
06:12:40 @since or @deprecated tag is needed in PHPDoc for OCP\L10N\IFactory::get
```

**Comment by MorrisJobke** [comment]
Code looks good :+1:

**Comment by MorrisJobke** [comment]
@Xenopathic @PVince81 Please review :) Easy one

**Comment by PVince81** [comment]
:+1:

The failing test is unrelated and was fixed on master => merging

**Pull request merged**
