### PR TITLE
[user mgnt] fix delete user feedback on failure

### LINKED ISSUE #18099: JS TypeError when deleting user
You get a JS error after having deleted a user
`TypeError: result is undefined deleteHandler.js:197:0`

Not sure who deals with this. @PVince81 ?

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #18099 

To reproduce the failure case change the condition of the if in https://github.com/owncloud/core/blob/637edfde24eefd9e9723ce3d438a7d627059681c/settings/controller/userscontroller.php#L393-393 to `true`.

Before:
- no error message shown - looks like delete was successful

After:
- error message
- user is added to the user list again

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Use the whitespace cleaned diff: https://github.com/owncloud/core/pull/18114/files?w=1

**Comment by MorrisJobke** [comment]
cc @blizzz @PVince81 @oparoz

**Comment by MorrisJobke** [comment]
@karlitschek Just tested it and it is also broken on stable8 and stable8.1. I would like to backport this then.

**Comment by DeepDiver1975** [comment]
> Just tested it and it is also broken on stable8 and stable8.1.

in this case it's not a regession :speak_no_evil:

**Comment by MorrisJobke** [comment]
> in this case it's not a regession :speak_no_evil:

It's a regression, because it worked in stable7 and broke during the move of the ajax files to a user controller ;)

**Comment by MorrisJobke** [comment]
Was introduced in #12618

@LukasReschke You also now have the opportunity to review this :P

**Comment by MorrisJobke** [comment]
I fixed the unit tests.

@PVince81 @blizzz Please review

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@Xenopathic @rullzer @LukasReschke @blizzz @oparoz Please review :)

**Comment by oparoz** [comment]
Works! :+1:

**Comment by MorrisJobke** [comment]
@karlitschek What about the backport to stable8 and stable8.1?

**Comment by MorrisJobke** [comment]
> @karlitschek What about the backport to stable8 and stable8.1?

Ping.

**Comment by karlitschek** [comment]
please backport!

**Comment by MorrisJobke** [comment]
stable8.1 https://github.com/owncloud/core/pull/18566
stable8 https://github.com/owncloud/core/pull/18567

**Comment by MorrisJobke** [comment]
Issue noticed during the backports: https://github.com/owncloud/core/issues/20254

**Pull request merged**
