### PR TITLE
[Stable9.1] Improved remote user search (#27996)

### PR DESCRIPTION
**Pull request by butonic**
* Use dav appconfig for customisable remote contact search properties

* Add limit and offset to remote user search

* Implement & fix carddavbackend search tests for limit and offset

* Fix sharee test to get search properties from config

* Improve sharee controller remote user search tests

* Include custom search properties in sharee exact matches

* Add explicit sorting of remote user searches

* Make addressbook search limit and offset optional

Backport of https://github.com/owncloud/core/pull/27996 to stable9.1

### CODE REVIEW

**Comment by PVince81** [comment]
any update on this backport ?

**Comment by Helios07** [comment]
I am trying to test the backport in sciebo, but still have some problems with the patch and the trust relationship. I hope I can give you feedback in a few days.

**Comment by Helios07** [comment]
We are using the patch since several days now in a production instance. It is working as expected (as far as I can tell) and I did not find any side effects so far.

**Comment by PVince81** [comment]
@Helios07 thanks for the feedback. The fix was merged so it will make it into the next 9.1 release.

**Pull request merged**
