### PR TITLE
Set a minimum timeout for UI test waits

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Ensure that anything calling a method to do a wait in the UI tests will have some reasonable minimum timeout.

## Motivation and Context
This sort of test crash:
```
  Scenario: share a folder with another internal user and prohibit deleting  # /home/travis/build/owncloud/core/tests/ui/features/other/sharing.feature:58
    When the folder "simple-folder" is shared with the user "User One"       # SharingContext::theFileFolderIsSharedWithTheUser()
      exception 'InvalidArgumentException' with message 'negative or zero timeout' in /home/travis/build/owncloud/core/tests/ui/features/lib/OwncloudPage.php:278
      Stack trace:
      #0 /home/travis/build/owncloud/core/tests/ui/features/lib/OwncloudPage.php(345): Page\OwncloudPage->waitForOutstandingAjaxCalls(Object(Behat\Mink\Session), -2843.9090251923)
      #1 /home/travis/build/owncloud/core/tests/ui/features/lib/FilesPageElement/SharingDialog.php(85): Page\OwncloudPage->waitForAjaxCallsToStartAndFinish(Object(Behat\Mink\Session), 10000)
      #2 /home/travis/build/owncloud/core/tests/ui/features/lib/FilesPageElement/SharingDialog.php(155): Page\FilesPageElement\SharingDialog->fillShareWithField('User One', Object(Behat\Mink\Session))
      #3 /home/travis/build/owncloud/core/tests/ui/features/lib/FilesPageElement/SharingDialog.php(185): Page\FilesPageElement\SharingDialog->shareWithUserOrGroup('User One', 'User One', Object(Behat\Mink\Session))
      #4 /home/travis/build/owncloud/core/tests/ui/features/bootstrap/SharingContext.php(70): Page\FilesPageElement\SharingDialog->shareWithUser('User One', Object(Behat\Mink\Session))
```

## How Has This Been Tested?
Travis will tell.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
In addition to this, we could also remove the exception "negative or zero timeout" in ``waitForOutstandingAjaxCalls`` and ``waitForAjaxCallsToStart`` and implement the minimum check in those methods also. I am not sure if we care when something calls the "wait" methods with a negative, zero or small (and likely useless) timeout - we just implement a minimum timeout value anyway, because the caller does want to wait for something.

**Comment by individual-it** [comment]
I think that change is useful but why would you need it anywhere else than in https://github.com/owncloud/core/pull/29104/files#diff-6690e23bacc320c50254348da567e94cR348 ?

**Comment by phil-davis** [comment]
Yes, the other places I was just being careful to give a "reasonable" minimum value of something calls it with a zero or negative or tiny value. I agree, it should not be needed.
I will make a PR with just the line that really needs to be fixed...

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport stable10 #29112

**Pull request merged**
