### PR TITLE
Remove the app version from disabled app list

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
@nickvergessen :+1: 
> Changing the json format is not necessary from my understanding - the version for disabled apps can simply be null or empty string

**Comment by nickvergessen** [comment]
That has already been adressed

**Comment by MorrisJobke** [comment]
Correct :) Sorry for the trouble

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
