### PR TITLE
Update README.md

### LINKED ISSUE #40187: make reports requirements could not be resolved to an installable set of packages
Tried to run `make` respectively `make test-php-style-fix` I get following error:
Note the I used the recent master, all is rebased.

@phil-davis maybe you can help...

```
make
Building core

Note: You can type 'make help' for more targets

php /usr/local/bin/composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bamarni/composer-bin-plugin 1.6.0 -> satisfiable by bamarni/composer-bin-plugin[1.6.0].
    - bamarni/composer-bin-plugin 1.6.0 requires composer-plugin-api ^2.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
make: *** [Makefile:149: lib/composer/phpunit] Error 2
```

### PR DESCRIPTION
**Pull request by mmattel**
Fixes: https://github.com/owncloud/core/issues/40187 (make reports requirements could not be resolved to an installable set of packages)

* Small text/link improvements
* Adding prerequisites (composer v2, yarn, node)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
This is a start. There will be lots of other development tools that you need to have on your development system. Maybe nodejs v? yarn v? We don't always notice exactly what is required because the default version supplied with some *nix happens to work, so nobody has to dig into it.

**Comment by mmattel** [comment]
I think to add a note to have yarn installed is easy and does no harm.
Same when it comes to node, we can also just drop a note that it is necessary to be installed.
But there are several node versions available...

**Comment by phil-davis** [comment]
core CI has:
```
DEFAULT_NODEJS_VERSION = "14"
```
So nodejs v14 is the current version used in core. The challenge with writing this in README or documentation is that we will forget to update it when it goes to v16 then v18.

**Comment by mmattel** [comment]
I have added `v14 or higher` knowing that we have v14 atm.
This gives at least a starting point...

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
