### PR TITLE
Add OC.joinPaths for convenient path joining

### PR DESCRIPTION
**Pull request by PVince81**
I'm tired of fiddling with paths, so here is `OC.joinPaths`.
Will be needed by https://github.com/owncloud/core/pull/16902 (the Webdav JS client for the files app)

Please review @MorrisJobke @rullzer @DeepDiver1975 @icewind1991 @oparoz 
Unit tests enclosed that show it in action :smile:

### CODE REVIEW

**Comment by rullzer** [comment]
Looking good!
And tests! Whoohoo!
:+1:

**Comment by oparoz** [comment]
I can see this being useful at times :)
I still can't test, so my vote doesn't count...yet...

**Comment by PVince81** [comment]
Well, you could look at the JS unit tests and see that I covered all possible cases :wink: 
(unless you find more)

**Comment by oparoz** [comment]
OK, maybe a couple with slashes in the middle to be sure that there is no interferences. I'm sure it works now, but in case someone decides to "optimise" it one day ;)

```
expect(OC.joinPaths('/abc', '/def')).toEqual('/abc/def');
expect(OC.joinPaths('/abc/', '/def')).toEqual('/abc/def');
expect(OC.joinPaths('/abc/', 'def')).toEqual('/abc/def');
```

What do you think?

**Comment by PVince81** [comment]
I thought I covered this here https://github.com/owncloud/core/pull/17559/files#diff-163902768f6bb1fc76108ce0e0c7cd5eR161 already. But maybe you're right, better be sure :smile:

**Comment by PVince81** [comment]
here we go https://github.com/owncloud/core/commit/fbc03b43b900d8657a865e447a471687342c4ce7 !

**Comment by oparoz** [comment]
Good for me! :+1:

**Pull request merged**
