### PR TITLE
Show system status in Settings/General

### PR DESCRIPTION
**Pull request by mmattel**
@PVince81 

## Description

The status query is moved into a fuction making it available to be regualry called.
Printout of system details as you would see them like in status.php
Adding additional elements in the status query does not need additional code changes in the template.

## Related Issue

#27231

## Motivation and Context

This PR shows the elements like you see in ownclouddomain.com/status.php at the bottom of Settings/General

## How Has This Been Tested?

call /settings/admin?sectionid=general and move to the bottom to see the result

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mmattel** [comment]
Why did jenkins fail?

**Comment by PVince81** [comment]
Seems you added a new public method:
```
@since or @deprecated tag is needed in PHPDoc for OCP\Util::getStatusInfo
```

you need to add `@since 10.0` in its PHPDoc

**Comment by PVince81** [comment]
Tested, works. 👍

**Comment by Emil-G** [comment]
May I ask why the servername was not added to the admin pages as well?
cheers,
Emil

**Comment by PVince81** [comment]
@Emil-G the admin page simply outputs whatever values are in status.php. If no server name is visible in status.php then it won't be visible there.

But maybe you meant to add it as additional info on this page regardless of status.php ? (the intent here was only about status.php)

**Comment by Emil-G** [comment]
@PVince81 yes, that is what I was asking. That would be useful admin info when servers are clustered.

**Comment by PVince81** [comment]
@Emil-G raised here https://github.com/owncloud/core/issues/28382

**Pull request merged**
