### PR TITLE
multiple separate instances for one source dir 

### PR DESCRIPTION
**Pull request by phlb**
Currently it is possible to use the environment variable PHPUNIT_CONFIG_DIR to define the variable $configDir. This allow to use a specific config directory depending on this environment variable.
This is done for testing purpose but It should be great to use it to setup several instances on top of one source dir. For example each instance having their own database and their own apps/themes/config/data folders.

Is it possible to either rename the environment variable PHPUNIT_CONFIG_DIR to CONFIG_DIR or to add another environment variable ?

If, ok I can propose a "pull request"

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
I honestly don't know if we should really walk this path

**Comment by thiagovsk** [comment]
@phlb you forgot to )]

    
    } elseif(isset($_SERVER["OWNCLOUD_CONFIG_DIR") {

change to

    } elseif(isset($_SERVER["OWNCLOUD_CONFIG_DIR"])) {

on the change seems to work for me, but still need to see any way to fix the autoconfig.php

in my case in nginx conf 
fastcgi_param OWNCLOUD_CONFIG_DIR "your_dir"

in apache2 i think setEnv works too.

**Comment by oparoz** [comment]
Thanks @thiagovsk . That shows the importance of letting Scrutinizer do its job :)

**Comment by phlb** [comment]
@thiagovsk  Thanks ! Fixed :)

I've never tested for nginx. For apache2 I've set :

    SetEnv OWNCLOUD_CONFIG_DIR "your_dir"

**Comment by thiagovsk** [comment]
@phlb  Nice!

now I'm trying to see a way to be possible every single folder config also able to have a autoconfig.php

the autoconfig.php is searched by default in the config folder, just will not work for this case.

When I'm done I can send a commit to your branch if deemed necessary.

Also I will try to commit this change in the .deb package in debian repository. As this seems to help other people besides us two.

Hugs!

**Comment by DeepDiver1975** [comment]
> I honestly don't know if we should really walk this path

my comment still remains - I don't think this is of any value - generally speaking

**Comment by oparoz** [comment]
It's of great value for companies who want to offer ownCloud as a SaaS, so it depends if you think ownCloud has its place there or not.

**Comment by phlb** [comment]
Le 19/06/2015 11:20, Thomas Müller a écrit :
>
>     I honestly don't know if we should really walk this path
>
> my comment still remains - I don't think this is of any value -
> generally speaking
>

@DeepDiver1975 I'm involved in a non profit organization providing
Internet services to other non profit organizations. Each organization
wants their own instance. So I've to host several owncloud instances on
the same server.

Handling several instances with one source directory will make the
server administration easier...

This is also needed if you want to host multiple instances with distro
packages (debian, etc.).

**Comment by DeepDiver1975** [comment]
> Handling several instances with one source directory will make the server administration easier...

I don't think this will make is easier for you - as soon as our upgrade the source code ALL instances have to run the migration code. You will loose any ability to migrate step-by-step smoothly.

**Comment by DeepDiver1975** [comment]
> It's of great value for companies who want to offer ownCloud as a SaaS, so it depends if you think ownCloud has its place there or not.

These days I'd expect an architecture on basis of isolated containers like docker to host multiple instance on the same server.

**Comment by phlb** [comment]
@DeepDiver1975  You can use one source dir by owncloud version. This allow to upgrade smoothly.

**Comment by LukasReschke** [comment]
FWIW, I agree with @DeepDiver1975 here. This will need to be tested with all possible scenarios and thus add a maintenance burden for a marginal new feature.

**Comment by oparoz** [comment]
Maybe this needs to live in a separate fork then. I for sure don't want to have to deal with Docker for anything else than testing.

**Comment by thiagovsk** [comment]
@DeepDiver1975 

In my case, I would have get multiple instances of owncloud with a single .deb
Currently this would only be possible if it had multiple copies of owncloud, copying folders packet for example (yes, I need to be all via packets).

And that's not the best way.

In wordpress for example I can have settings per domain, it already allows, I can with just one package to create various settings per domain on the same server, just that each domain has a separate wp-content folder.

With owncloud and this change, I need only have each data folder separately in addition autoconfig one for each domain.

But I can keep this change only in .deb instead of the upstream.

cc: @phlb

**Comment by gig13** [comment]
@bboule @MTRichards 
Any updates?

**Comment by MTRichards** [comment]
Seems pretty clear from the comments above that this will create major problems for others, and potentially themselves, and that tools like docker will provide a more scalable and fault tolerant environment.

**Comment by phlb** [comment]
Tools like docker are currently fashionable but a lot of web hosting platforms don't use it (and won't use it).

I'm currently testing this patch with several owncloud instances. This works with the standard apps (contact, calendar +  the official apps), autoconfig and the owncloud versions  8.1.1 & 8.0.4. 

Please contact me if you want me to do some tests. I am also interested in feedback on what could be a problem with this setup, for testing them.

**Comment by MorrisJobke** [comment]
I like the idea of getting rid of the hardcoded `/config/` in `cron.php` and the setup controller. But the change in `initPaths()` won't make it into core, because it is yet another code path, that needs extensive testing.

@phib @DeepDiver1975 @LukasReschke Is this a good compromise?

**Comment by MorrisJobke** [comment]
Then also the change that needs be maintained to add this feature is minimal and can be done in a fork.

**Comment by MorrisJobke** [comment]
@gig13 For your request this is a clear no, we wont support this officially in the ownCloud Server.

**Comment by gig13** [comment]
@MorrisJobke @bboule @MTRichards @cmonteroluque 
Please do not remove blue tickets tag for tracking purposes.

**Comment by DeepDiver1975** [comment]
I'm going to close this due to all the stated reasons above.
I can see the necessity of a multi domain feature - but I guess this is something we should think more in depth about.

In addition - we do a bit more then a word press installation and I can see major issue with a multi domain approach.

Thanks!

**Comment by DeepDiver1975** [comment]
reopening to get final feedback from @gig13 regarding blue-ticket status - THX

**Comment by DeepDiver1975** [comment]
> reopening to get final feedback from @gig13 regarding blue-ticket status - THX

time's up -> close

**Pull request closed without merging**
