### PR TITLE
Fix sidebar for trashbin and others

### LINKED ISSUE #18527: Right sidebar issues with sharing overviews
- highlight looks wrong
- sidebar is empty

It should be possible to display all known panels from the regular file list.

### PR DESCRIPTION
**Pull request by PVince81**
- properly update the sidebar contents for other sections (shared with you, trashbin)
- fixed trashbin preview + file name display

Please review @jancborchardt @MorrisJobke @blizzz @nickvergessen 

Fixes https://github.com/owncloud/core/issues/18527

### CODE REVIEW

**Comment by nickvergessen** [comment]
Looks good, only the highlight is a bit strange only half the row is colored bright when clicking on it.

**Comment by PVince81** [comment]
I'll fix the highlight separately, thanks.

**Comment by PVince81** [comment]
@nickvergessen I pushed a fix here, turns out it was easier than I thought: https://github.com/owncloud/core/commit/010c03fc30a6d5d1765889431905dc415d289018

**Comment by PVince81** [comment]
Jenkins PR https://github.com/owncloud/core/pull/18541

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
