### PR TITLE
[tests-only] [full-ci] Run tests with MariaDb 10.6

### PR DESCRIPTION
**Pull request by phil-davis**
see if there is even a docker image for MariaDb 10.6

Issue #39283

### CODE REVIEW

**Comment by IljaN** [comment]
Not sure where this is coming from: https://drone.owncloud.com/owncloud/core/32640/21/5

**Comment by IljaN** [comment]
I guess @JanAckermann was correct, it looks to me as if doctrine is creating all tables with default compressed

**Comment by IljaN** [comment]
Found another instance of "compressed": https://github.com/owncloud/core/pull/39282/commits/ec9474920181ad12afeba19653f2b72f0b21bb6d

**Comment by IljaN** [comment]
Are there more configs which set row_format?

**Comment by IljaN** [comment]
So unit tests pass with my commits on 10.6 now, but some acceptance tests are pulling the 10.7 tarball. What now @phil-davis ?

**Comment by phil-davis** [comment]
> So unit tests pass with my commits on 10.6 now, but some acceptance tests are pulling the 10.7 tarball. What now @phil-davis ?

https://drone.owncloud.com/owncloud/core/32643/103/11 is using the "latest" tarball to install a federated server = 10.8.0

Actually we don't care what database the federated server is using - we just care that it is running the latest release, so that we test that the newer code in core master still talks correctly with a "latest" federated server.

I will change that back to MariaDb 10.5 for the federated server.

**Comment by phil-davis** [comment]
That's good - all tests passed. For new installations it seems like this will be the only code changes needed.

We will have to investigate what issues there might be, if any, for existing sites that are on oC 10.8.0 or earlier, upgrade to a future 10.9.0 and then update MariaDb to 10.6.

**Comment by phil-davis** [comment]
PR #39286 implements this and has been merged to master.

**Pull request closed without merging**
