### PR TITLE
add title to entries in app menu

### LINKED ISSUE #15344: Add Title tag to "Apps menu" items
Currently the Title tag of the Apps menu items is empty, but it should include the name of the icon.
It's easy, here is a diff, please someone capable, include it:

```
--- layout.user.php	2015-03-31 20:28:29.000000000 +0200
+++ layout.user.php.new	2015-03-31 20:28:37.000000000 +0200
@@ -112,7 +112,7 @@
 				<ul>
 				<?php foreach($_['navigation'] as $entry): ?>
 					<li data-id="<?php p($entry['id']); ?>">
-						<a href="<?php print_unescaped($entry['href']); ?>" title=""
+						<a href="<?php print_unescaped($entry['href']); ?>" title="<?php p($entry['name']); ?>"
 							<?php if( $entry['active'] ): ?> class="active"<?php endif; ?>>
 							<img class="app-icon svg" alt="" src="<?php print_unescaped($entry['icon']); ?>"/>
 							<div class="icon-loading-dark" style="display:none;"></div>
@@ -126,7 +126,7 @@
 				<!-- show "More apps" link to app administration directly in app navigation, as last entry -->
 				<?php if(OC_User::isAdminUser(OC_User::getUser())): ?>
 					<li id="apps-management">
-						<a href="<?php print_unescaped(OC_Helper::linkToRoute('settings_apps')); ?>" title=""
+						<a href="<?php print_unescaped(OC_Helper::linkToRoute('settings_apps')); ?>" title="<?php p($l->t('Apps')); ?>"
 							<?php if( $_['appsmanagement_active'] ): ?> class="active"<?php endif; ?>>
 							<img class="app-icon svg" alt="" src="<?php print_unescaped(OC_Helper::imagePath('settings', 'apps.svg')); ?>"/>
 							<div class="icon-loading-dark" style="display:none;"></div>
```
OC 8.0.2

It's really necessary for the Direct Menu app, but otherwise should be included.

### PR DESCRIPTION
**Pull request by MorrisJobke**
fixes #15344

Improves the accessability of the app menu.

cc @owncloud/designers @oparoz @nickvergessen @Xenopathic

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @tylia

**Comment by MorrisJobke** [comment]
cc @tylla

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by jancborchardt** [comment]
Is this really needed? Doesn’t it just duplicate the content of the span inside anyway? Or @tylla did you test this with a screen reader? cc @Volker-E

**Comment by nickvergessen** [comment]
well it does, but either the title should be non-empty or just be removd

**Comment by Volker-E** [comment]
@jancborchardt Thanks for including me here. @MorrisJobke actually I'm sure, that this doesn't help accessibility at all. Screen Readers like JAWS and NVDA ignore `title` attributes on links at all as long as there's a textnode in the anchor. What is now added and merged by this commit is duplicating the textnode content in the title attribute.

I'm with @nickvergessen here, the `title` attribute in this case should be removed completely.
See [this article for more information on anchor title accessibility](http://silktide.com/i-thought-title-text-improved-accessibility-i-was-wrong/).

**Comment by jancborchardt** [comment]
@Volker-E thank you, and thanks for fixing it! :)

**Pull request merged**
