### PR TITLE
Exclude mimetypelist.js from integrity check

### LINKED ISSUE #28967: [10.0.3] occ maintenance:mimetype:update-js ==> failed the integrity check
Running `sudo -u www-data php occ maintenance:mimetype:update-js` (after workaround from https://github.com/owncloud/core/issues/28966#issuecomment-328351281) breaks integrity:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 8edea6fdddf5c20e8fd0de847a25b7af57d0b454877138a917587e1eafcc31754aece7549cd92536f78cd9d29583458757802315ae60e656a332de9e4e0879d0
                            [current] => b0d4ad86424111f2a1fdec231d888d55aa6292a81c684705da8eda915b3a5815d52555d220c8e3b945cd348e1b08559c2c42caf21aa25266e6758d7d727ed186
                        )

                )

        )

)
```

### Steps to reproduce
1. Install oC 10.0.3 RC1
2. Activate Example ownCloud Theme
3. `cp resources/config/mimetypealiases.dist.json config/mimetypealiases.json`
4. `sudo -u www-data php occ maintenance:mimetype:update-js -vvv`

### Expected behaviour
modified `mimetypelist.js` shouldn't break integrity

### Actual behaviour
The following list covers which files have failed the integrity check:
`core/js/mimetypelist.js`

### Server configuration
**Operating system**:
Ubuntu 16.04.3 LTS

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
10.0.31-MariaDB-0ubuntu0.16.04.

**PHP version:**
PHP 7.0.22-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page)
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.2","versionstring":"10.0.3 RC1","edition":"Enterprise","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Updated from oC 9.1.x

**Where did you install ownCloud from:**
*.tar

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- oauth2
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- diagnostics
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- theme-example
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- theme-mailtest
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.3.2",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "gmail.com",
        "mail_smtpsecure": "ssl",
        "loglevel": 2,
        "maintenance": false
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.4
  - admin_audit: 0.8
  - announcementcenter: 1.2.0
  - comments: 0.3.0
  - configreport: 0.1.1
  - customgroups: 0.3.1
  - dav: 0.3.0
  - diagnostics: 0.1.2-beta1
  - enterprise_key: 0.1.3
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.4.1
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - guests: 0.4.1
  - market: 0.2.1
  - notifications: 0.3.1
  - oauth2: 0.1.1
  - password_policy: 1.0.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - theme-example: 1.0.0
  - workflow: 0.2.4
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-mailtest
  - updatenotification
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 60

**Operating system:**
macOS Sierra 10.12.6

@phisch This is important to fix. Could you check?

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Because this file can be regenerated with additional entries with `occ maintenance:mimetype:update-js`

## Related Issue
Fixes https://github.com/owncloud/core/issues/28967

## Motivation and Context
Because admins need to be able to theme their instances without being annoyed by integrity failures.

## How Has This Been Tested?
This cannot be tested without merging because the signature file needs to be regenerated without this one entry. After merging, verify on daily master that after running the occ command above there are no integrity failures. Or modify the JS file manually and do a `occ integrity:check-core`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jvillafanez** [comment]
It might be better to use a custom mimetype list file to override whatever is in the "official" mimetypelist.js file. The idea is similar to what is used in other parts of ownCloud: get the data from the mimetypelist.js file and override or extend that data with the contents of another custom file if needed.
The mimetypelist.js will keep being hashed while the other custom file won't.

**Comment by michaelstingl** [comment]
> It might be better to use a custom mimetype list file to override whatever is in the "official" mimetypelist.js file.

Why can't a mimetypelist.js in the theme override the "official one"? (each theme could have a different one)

**Comment by PVince81** [comment]
In general JS files can be overridden with JS, so I assume that overriding this one file should be possible as well.

But the original purpose of the mimetype aliases as I understand it is to let people specify custom mime types specific to their installs without having to submit a PR to core. We could make it so that people **must** use a theme if they want to specify custom mime types.

**Comment by michaelstingl** [comment]
With this PR applied to my 10.0.3 RC1, it says `mimetypelist.js` is missing:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- core/js/mimetypelist.js
	- INVALID_HASH
		- lib/private/IntegrityCheck/Checker.php

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 8edea6fdddf5c20e8fd0de847a25b7af57d0b454877138a917587e1eafcc31754aece7549cd92536f78cd9d29583458757802315ae60e656a332de9e4e0879d0
                            [current] => 
                        )

                )

            [INVALID_HASH] => Array
                (
                    [lib/private/IntegrityCheck/Checker.php] => Array
                        (
                            [expected] => 5535a8edd183f7de414c87b8f2fa0a80dae274fa52e450145c972fb74ab551cf1e10e08efe134ae2a023bccf52f02dd71d73390755bdd478057e88cb4b3da836
                            [current] => f2ab3ed31b1777a874fc923ab161016953a1f81b28346005e7a3188cdb36343c6b8288fc23216a805be518b96ac721ef573b6f1eb9c4ccf0827001591385edb2
                        )

                )

        )

)
```


I checked, and it's there:

```
/var/www/owncloud# tail -n 15 core/js/mimetypelist.js
    "x-office-document",
    "x-office-presentation",
    "x-office-spreadsheet"
],
	themes: {
    "theme-mailtest": [
        "folder",
        "folder-drag-accept",
        "folder-external",
        "folder-public",
        "folder-shared",
        "folder-starred"
    ]
}
```

**Comment by jvillafanez** [comment]
I didn't take theming into consideration, but anyway, an additional custom file could come in handy. We could have 3 different files: core's mimefiletype.js, the one coming from theming, and the last one from a custom location maybe configured through the config.php file.

The priority would be: core < theming < custom. This could work because there will be only one  active theme, so no competition among themes will happen, and the priorities are quite clear. Anyway, it's something to decide what we'll allow.

Particularly, I think everything we package should be hashed. Unless the mimetypelist.js can be safely removed from ownCloud, it must be hashed. If the file can be removed without affecting ownCloud, we can say it's a example file that can be edited, but only if this is the case.

**Comment by PVince81** [comment]
@michaelstingl please read "how has this been tested" section in the original post. tldr; you can't test it because it requires resigning the whole tarball. You also can't manually remove "mimetypelist.js" from the signature file because the file itself is signed.

**Comment by PVince81** [comment]
@jvillafanez please repost your suggestions here: https://github.com/owncloud/core/issues/28974.

**Comment by michaelstingl** [comment]
@PVince81 Oh, this explains a lot. Sorry for the noise.

**Comment by PVince81** [comment]
do we agree to merge this ? is the check code acceptable ?

**Review by peterprochaska — APPROVED** [review]
Code looks good

**Comment by PVince81** [comment]
- [ ] test with tomorrow's daily master
- [ ] backport to stable10

**Comment by PVince81** [comment]
@michaelstingl can you test with daily master ?

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/29048

**Pull request merged**
