### PR TITLE
Cast share id to string in public auth

### PR DESCRIPTION
**Pull request by PVince81**
Additional fix for https://github.com/owncloud/core/issues/23066

@butonic @DeepDiver1975 @owncloud/sharing 

Backports needed to:
- stable9.1
- stable9

### CODE REVIEW

**Comment by PVince81** [comment]
review please @DeepDiver1975 @butonic @georgehrke @VicDeo

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by georgehrke** [comment]
lgtm 👍

**Comment by DeepDiver1975** [comment]
Will take care about the backports

**Comment by PVince81** [comment]
stable9.1: https://github.com/owncloud/core/pull/25432
stable9: https://github.com/owncloud/core/pull/25431

**Pull request merged**
