### PR TITLE
fix selecting parent

### PR DESCRIPTION
**Pull request by butonic**
guess what is wrong here: https://github.com/owncloud/core/blob/master/lib/private/Share/Share.php#L1901-L1902

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]
that code has to die .....

**Comment by DeepDiver1975** [comment]
@butonic backport?

**Comment by butonic** [comment]
@DeepDiver1975 no backport needed. we can do it later if we find out it causes problems in the wild.

**Comment by PVince81** [comment]
@butonic this is the old sharing code, is it really still triggered on OC 10 ?

**Comment by PVince81** [comment]
@butonic any linked bug report ? the code change doesn't explain what the problem is, maybe add a PHP doc to explain what it is doing and why ?

**Comment by PVince81** [comment]
closing due to lack of feedback and context

**Pull request closed without merging**
