### PR TITLE
[stable9.1] Users page lazy multiselect group dropdowns

### PR DESCRIPTION
**Pull request by PVince81**
Squashed backport of https://github.com/owncloud/core/pull/25922 to stable9.1

Please review and test @mrow4a @davitol @SergioBertolinSG

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Works fine 👍 

But I've noticed that https://github.com/owncloud/core/issues/16041 is still there.

**Comment by PVince81** [comment]
@SergioBertolinSG yes, because nobody fixed https://github.com/owncloud/core/issues/16041 yet

**Comment by SergioBertolinSG** [comment]
@PVince81 I've created a PR for it https://github.com/owncloud/core/pull/25934

**Comment by mrow4a** [comment]
LDAP
50000 users
2000 groups

Verified, on stable9.1 branch, it freezes my Firefox and one need to spam continue button for many seconds.

On stable9.1-users-lazydropdownwithpencil I am not experiencing the problem and it behaves similarly to what we discussed in owncloud master. It also seems to work faster than for 9.0

image

**Pull request merged**
