### PR TITLE
Fix encryption feof to not return too early

### LINKED ISSUE #15580: [enc2] New encryption much slower to download files
### Steps
1. Setup OC 8.0.3RC1 (or stable8)
1. Enable encryption
1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "test"
1. Upload a big file "data1.dat" (mine was 121MB big)
1. Share "test" with "user2"
1. Download the file with curl as "user2": `curl http://user2:test@localhost/owncloud/remote.php/webdav/test/data1.dat -o temp.dat`. Took 2s "Time spent"
1. Upgrade to master (I used the migration branch https://github.com/owncloud/core/pull/15445)
1. Go to the admin page and enable encryption
1. Click "Start migration"
1. Enable "ownCloud default encryption module" app
1. Rerun the curl command: took 16 seconds "Time spent"

### Expected result
No significant performance impact

### Actual result
Performance loss of about 800%

I'll try running it into blackfire before and after

### Versions
Migrating stable8 to this branch https://github.com/owncloud/core/pull/15445 (for the migration)

### PR DESCRIPTION
**Pull request by PVince81**
This is because stream_read will pre-cache the next block which causes
feof($this->source) to return true prematurely. So we cannot rely on it.

Fixes https://github.com/owncloud/core/issues/15580

@jknockaert @schiesbn @th3fallen @DeepDiver1975 
- [x] add unit test with a loop to reproduce the original issue

### CODE REVIEW

**Comment by PVince81** [comment]
Unit test will be more tricky than I thought. The current stream wrapper mock is working with one to one block sizes instead of different size ratios, so the original issue cannot be reproduced this way.

**Comment by PVince81** [comment]
I have fixed the unit test mock to actually simulate 6k/8k blocks which is needed to be able to catch such errors.
Unit test that reproduces the case has been added. You can try commenting out the feof fix and you'll see it failing. Also this proves again that stream_read_contents disregards feof (at least here in PHP 5.6.7).

Please review @schiesbn @jknockaert @DeepDiver1975 @th3fallen

**Comment by jknockaert** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
This reminds me of a todo - we should wrap these stream wrapper tests around the encryption module in the app to test the interaction of these two (enc module and stream wrapper)

**Comment by DeepDiver1975** [comment]
I guess this PR superseeds https://github.com/owncloud/core/pull/15633

**Comment by PVince81** [comment]
Ah! There is was! I was looking for your PR but found another one that was closed as obsolete and got confused.

The reason why your PR didn't catch the issue is because it didn't use a while loop that calls `feof()` and also because the mock wasn't mocking the block size change.

**Comment by DeepDiver1975** [comment]
> Ah! There it was!

close #15633 ???

**Comment by PVince81** [comment]
Done.

**Comment by schiesbn** [comment]
Looks good :+1: 

@PVince81 Are the tests complete? Because the checkbox at the top is still open?

**Comment by PVince81** [comment]
Yes they are. I ticked it now.

**Pull request merged**
