### PR TITLE
add slight shadow to close icon to make it visible on top of dark images

### LINKED ISSUE #19291: Preview in sidebare hides close button
The preview in the sidebar hides the (X) at the top right to close the sidebar which makes it impossible to close the sidebar.

cc @jancborchardt @PVince81

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #19291, please review @schiesbn @oparoz @owncloud/designers 

This shadow was achieved by:
- duplicating the shape of the icon
- changing it to white, adding 1px of border, and 25% of blur
- putting it behind the original shape

I’ll also do that for the Gallery controls @oparoz

### CODE REVIEW

**Comment by schiesbn** [comment]
It is still almost not visible with my example image:



Also I'm not sure if it is a good idea to place control elements in the image.

1. It can be hard to distinguish if it belongs to the image or if it is a control element
2. If you identify it as control element it looks like it is used to control the preview and not the complete sidebar, e.g. hide the preview

**Comment by schiesbn** [comment]
Also this looks really broken:

**Comment by jancborchardt** [comment]
@schiesbn can you retest? I increased the border from 1 to 2.

The second screenshot I can’t do much about – @icewind1991 your part.

**Comment by schiesbn** [comment]
@jancborchardt better but I'm still  not convinced that it is a good idea to have it in the preview. If you really want to keept it this way, can you at least add some on-hover effect so that you can detect the action better if you move your mouse over it?

**Comment by icewind1991** [comment]
> Also this looks really broken

Fix is here: #19307

**Comment by MorrisJobke** [comment]
:+1: Better than before

**Comment by jancborchardt** [comment]
So @icewind1991 @schiesbn can you review this here as well?

**Comment by schiesbn** [comment]
definitely an improvement :+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 mergable.

**Pull request merged**
