### PR TITLE
Use appConfig to get app versions

### PR DESCRIPTION
**Pull request by icewind1991**
Saves a query by re-using the appconfig cache.

Also improved the performance of `AppConfig->getValues`

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and still works :+1: 

@DeepDiver1975 What about the primary storage test?

**Comment by PVince81** [comment]
Remember that we download the latest code for third party apps in occ upgrade, do these properly invalidate the cached installed versions ?

**Comment by PVince81** [comment]
> Remember that we download the latest code for third party apps in occ upgrade, do these properly invalidate the cached installed versions ?

@icewind1991 ?

**Comment by LukasReschke** [comment]
Cache is only in request and behaviour is the same as before. :+1: from my side.

**Pull request merged**
