### PR TITLE
Fix #15962

### LINKED ISSUE #15962: PHP Warning:  The use statement with non-compound name 'JsonSerializable' has no effect
@Raydiation 

````
00:00:53.202 Testing with sqlite ...
00:00:53.376 PHP Warning:  The use statement with non-compound name 'JsonSerializable' has no effect in /var/jenkins/workspace/server-master-linux/database/sqlite/label/SLAVE/lib/private/l10n/string.php on line 27
00:00:53.376 PHP Stack trace:
00:00:53.376 PHP   1. {main}() /usr/local/bin/phpunit:0
00:00:53.376 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:612
00:00:53.376 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
00:00:53.376 PHP   4. PHPUnit_TextUI_Command->handleArguments() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:148
00:00:53.376 PHP   5. PHPUnit_TextUI_Command->handleBootstrap() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:651
00:00:53.376 PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:817
00:00:53.376 PHP   7. PHPUnit_Util_Fileloader::load() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:77
00:00:53.376 PHP   8. include_once() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:93
00:00:53.376 PHP   9. require_once() /var/jenkins/workspace/server-master-linux/database/sqlite/label/SLAVE/tests/bootstrap.php:16
00:00:53.376 PHP  10. OC::init() /var/jenkins/workspace/server-master-linux/database/sqlite/label/SLAVE/lib/base.php:1101
00:00:53.376 PHP  11. OC_Util::checkServer() /var/jenkins/workspace/server-master-linux/database/sqlite/label/SLAVE/lib/base.php:602
00:00:53.376 PHP  12. OC_Defaults->__construct() /var/jenkins/workspace/server-master-linux/database/sqlite/label/SLAVE/lib/private/util.php:559
00:00:53.376 PHP  13. OC_L10N->t() /var/jenkins/workspace/server-master-linux/database/sqlite/label/SLAVE/lib/private/defaults.php:64
00:00:53.376 PHP  14. spl_autoload_call() /var/jenkins/workspace/server-master-linux/database/sqlite/label/SLAVE/lib/private/defaults.php:287
00:00:53.376 PHP  15. OC\Autoloader->load() /var/jenkins/workspace/server-master-linux/database/sqlite/label/SLAVE/lib/private/defaults.php:0

### PR DESCRIPTION
**Pull request by BernhardPosselt**
fix #15962

@DeepDiver1975 @MorrisJobke @nickvergessen @PVince81

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Works and fixes the issue :+1:

**Comment by PVince81** [comment]
Warning gone :+1: 

Where's Jenkins ?

**Comment by MorrisJobke** [comment]
> Where's Jenkins ?

Dead :(

**Comment by DeepDiver1975** [comment]
> Where's Jenkins ?

I fear that :bloody: :sucker: lost the config during restart again .....

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Pull request merged**
