### PR TITLE
Fix overriding for gif images in themes for CLI scripts

### LINKED ISSUE #31804: Theming: overriding is broken for gif images
1. Enable theme-example
2. Enable notifications app
3. Set `Mail Notifications` in personal page to 'Notify about all events'
3. php occ notifications:generate -u boo --link http://home.org  go home!

## Expected
Mail notification has `logo-email.gif` from theme-example

## Actual 
Mail notification has `logo-email.gif` from core

### PR DESCRIPTION
**Pull request by VicDeo**
## Related Issue
- Fixes https://github.com/owncloud/core/issues/31804

## Motivation and Context
Fixes overriding logo for emails that are sent from CLI 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by VicDeo** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by PVince81 — APPROVED** [review]
Code looks good and makes sense :+1:

**Comment by VicDeo** [comment]
stable10: https://github.com/owncloud/core/pull/32131

**Pull request merged**
