### PR TITLE
[tests-only][mobile-screen] wait till settings button is visible before clicking

### LINKED ISSUE #39621: test fail webUIFiles/hiddenFile.feature:14
https://drone.owncloud.com/owncloud/core/34117/168/17
```
  Background:                                                                              # /drone/src/tests/acceptance/features/webUIFiles/hiddenFile.feature:8
    Given user "Alice" has been created with default attributes and without skeleton files # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "Alice" has logged in using the webUI                                         # WebUILoginContext::theUserHasLoggedInUsingTheWebUI()
    And the user has browsed to the files page                                             # WebUIFilesContext::theUserBrowsesToTheFilesPage()

  ┌─ @BeforeScenario @webUI # WebUIGeneralContext::setUpScenario()
  │
  │  Running webUI test under resolution: 375x812
  │
  @smokeTest @mobileResolutionTest
  Scenario: create a hidden folder                                        # /drone/src/tests/acceptance/features/webUIFiles/hiddenFile.feature:14
    When the user creates a folder with the name ".xyz" using the webUI   # WebUIFilesContext::theUserCreatesAFolderUsingTheWebUI()
    Then folder ".xyz" should not be listed on the webUI                  # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()
    When the user enables the setting to view hidden folders on the webUI # WebUIFilesContext::theUserEnablesTheSettingToViewHiddenFoldersOnTheWebUI()
      element click intercepted: Element <div id="app-settings">...</div> is not clickable at point (125, 661). Other element would receive the click: <div id="app-content" style="transition: all 0.3s ease 0s; transform: translate3d(250px, 0px, 0px);">...</div>
        (Session info: chrome=74.0.3729.169)
        (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-162-generic x86_64) (WebDriver\Exception\UnknownError)
    Then folder ".xyz" should be listed on the webUI                      # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()
SCENARIO RESULT: (fail)
```

This was "Running webUI test under resolution: 375x812". Maybe there is some chance of it being intermittent on the "mobile" sized browser window?

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
- wait for xpath to be visible
- run the related flaky test more often

## Related Issue

- Fixes https://github.com/owncloud/core/issues/39621

## How Has This Been Tested?

- :house: 
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

### CODE REVIEW

**Comment by kiranparajuli589** [comment]
build to watch https://drone.owncloud.com/owncloud/core/34169/4/17

**Comment by kiranparajuli589** [comment]
build running flaky scenario passed.
```console
runsh: Total 65 scenarios (65 passed, 0 failed)
runsh: Exit code of main run: 0
runsh: There were no unexpected failures.
runsh: There were no unexpected success.
sleeping for 30 seconds at end of test run
```

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiTags-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34176/81/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareUpdateToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34176/79/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToRoot2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34176/75/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareUpdateToShares-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34176/80/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareReshareToRoot3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34176/77/1

**Comment by kiranparajuli589** [comment]
https://drone.owncloud.com/owncloud/core/34176/81/1 failed on yarn install

**Comment by phil-davis** [comment]
@kiranparajuli589 IMO you can squash the commits now. We don't want the "experimental" commits to end up in the commit history f master branch.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
