### PR TITLE
Template to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
- function.php to legacy
- Move \OC\Template to PSR-4

CC: @MorrisJobke @nickvergessen @DeepDiver1975 @LukasReschke 

For future work we should really properly namespace functions.php...

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> For future work we should really properly namespace functions.php...

It is already. See `OCP\Template::...`

**Comment by rullzer** [comment]
@MorrisJobke ok also properly namespace the private part I mean ;)

**Comment by MorrisJobke** [comment]
> @MorrisJobke ok also properly namespace the private part I mean ;)

This is by intention :) See  https://doc.owncloud.org/server/9.0/developer_manual/app/templates.html  for documentation :P

**Comment by rullzer** [comment]
Ah ok... I get it... but nice is different...

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by rullzer** [comment]
Ran intergration tests locally. All passed.

**Comment by MorrisJobke** [comment]
@PVince81 Please merge 🙈

**Pull request merged**
