### PR TITLE
Fix remaining unit tests for provisioning_api

### PR DESCRIPTION
**Pull request by tomneedham**
Fixes self

Since these aren't real unit tests they need a better setup and tear down methods.

~~Still [WIP] as one test is still failing.~~
- [x] Fix `Test_Provisioning_Api_Groups::testGetGroupAsAdmin` with error: 

```
1) Test_Provisioning_Api_Groups::testGetGroupAsAdmin
Failed asserting that false is true.

/var/www/owncloud.dev/cloud/apps/provisioning_api/tests/groupsTest.php:125
```

### CODE REVIEW

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by tomneedham** [comment]
Obviously this isn't the real fix, the provisioning_api classes should use injection and the tests should use mocks :/ ....

**Comment by MorrisJobke** [comment]
Jenkins PR: #13093

**Comment by MorrisJobke** [comment]
:+1: from me

**Comment by MorrisJobke** [comment]
Success: https://github.com/owncloud/core/pull/13093#issuecomment-68610394

**Pull request merged**
