### PR TITLE
[Tests-only] Add acceptance test to share subfolder to invisible user in share chain

### PR DESCRIPTION
**Pull request by haribhandari07**
## Description

This PR adds acceptance test to share a subfolder to a user that already received parent folder share but is invisible in the share chain
## Related Issue

https://github.com/owncloud/enterprise/issues/3896

## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

### CODE REVIEW

**Review by jasson99 — COMMENTED** [review]
LGTM

**Review by dpakach — COMMENTED** [review]
LGTM :+1:

**Review by dpakach — COMMENTED** [review]
LGTM :+1:

**Comment by kiranparajuli589** [comment]
LGTM :+1:

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
