### PR TITLE
Exclude lost+found dir in integrity check

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/owncloud/core/issues/23341

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

@karlitschek Backport to 9.0.1?

**Comment by RealRancor** [comment]
MIT licensed

**Comment by RealRancor** [comment]
> Works. Thank you. :-)

from @stephan2012 in https://github.com/owncloud/core/issues/23341#issuecomment-198767113

**Comment by karlitschek** [comment]
please backport

**Comment by LukasReschke** [comment]
Replaced by https://github.com/owncloud/core/pull/23474 for CI

**Pull request closed without merging**
