### PR TITLE
[stable10] UI Test redirect from personal settings to login page

### PR DESCRIPTION
**Pull request by phil-davis**
Backport of #28257 

This will be needed in stable10 ready for when issue #28129 is fixed by PR #28255 and that fix is backported to stable10. #28255 will unskip the skipped test, so that test had better be there to be unskipped.

### CODE REVIEW

**Comment by phil-davis** [comment]
Hmmm - needs some other underlying bits backported first. I will look.

**Comment by phil-davis** [comment]
Rebased. Should have the needed infrastructure in stable10 now. Let's see what Jenkins thinks.

**Comment by phil-davis** [comment]
@PVince81 
The same Jenkins problem happens if I just make a white-space edit to a file - e.g. https://github.com/owncloud/core/pull/28300
So something is broken either with Jenkins or some code or test has been committed to stable10 that does not work.
I do not think it is a problem with this articular PR.

**Comment by PVince81** [comment]
```
06:04:34 --- Skipped scenarios:
06:04:34 
06:04:34     /var/lib/jenkins/workspace/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ/tests/integration/features/auth.feature:10
06:04:34 
06:04:34 438 scenarios (437 passed, 1 skipped)
06:04:34 4109 steps (4105 passed, 4 skipped)
06:04:34 39m34.51s (27.30Mb)
06:04:35 ./run.sh: line 121:  6249 Terminated              php -S localhost:$PORT -t "$OC_PATH"
06:04:35 ./run.sh: line 121:  6250 Terminated              php -S localhost:$PORT_FED -t ../..
06:04:35 Config value enable_external_storage for app core set to no
06:04:35 No such app enabled: testing
06:04:36 {"reqId":"CbKq4RDJV2RXtLzohJYx","level":3,"time":"2017-07-05T04:02:48+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/apps?filter=enabled","message":"file_get_contents(\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/apps\/testing\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#39"}
06:04:36 {"reqId":"CbKq4RDJV2RXtLzohJYx","level":3,"time":"2017-07-05T04:02:48+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/apps?filter=enabled","message":"file_get_contents(\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/apps\/theme-example\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#39"}
06:04:36 {"reqId":"CbKq4RDJV2RXtLzohJYx","level":3,"time":"2017-07-05T04:02:48+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/apps?filter=enabled","message":"file_get_contents(\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/apps\/comments\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#39"}
06:04:36 {"reqId":"nF981MuYGjchER9pb3g1","level":3,"time":"2017-07-05T04:04:24+00:00","remoteAddr":"::1","user":"test","app":"OCP\\Share","method":"GET","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/sharees?search=test%40localhost&itemType=calendar","message":"Sharing backend for calendar not found"}
06:04:36 {"reqId":"jZ2Vt3OmbB0onqy521Nn","level":3,"time":"2017-07-05T04:04:34+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/cloud\/apps?filter=enabled","message":"file_get_contents(\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/apps\/systemtags\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#39"}
06:04:36 {"reqId":"jZ2Vt3OmbB0onqy521Nn","level":3,"time":"2017-07-05T04:04:34+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/cloud\/apps?filter=enabled","message":"file_get_contents(\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/apps\/multidirtest\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#39"}
06:04:36 {"reqId":"jZ2Vt3OmbB0onqy521Nn","level":3,"time":"2017-07-05T04:04:34+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/cloud\/apps?filter=enabled","message":"file_get_contents(\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/apps\/testing\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#39"}
06:04:36 {"reqId":"jZ2Vt3OmbB0onqy521Nn","level":3,"time":"2017-07-05T04:04:34+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/cloud\/apps?filter=enabled","message":"file_get_contents(\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/apps\/theme-example\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#39"}
06:04:36 {"reqId":"jZ2Vt3OmbB0onqy521Nn","level":3,"time":"2017-07-05T04:04:34+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/cloud\/apps?filter=enabled","message":"file_get_contents(\/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/apps\/comments\/appinfo\/signature.json): failed to open stream: No such file or directory at \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/lib\/private\/IntegrityCheck\/Helpers\/FileAccessHelper.php#39"}
06:04:36 {"reqId":"Nv75y1oCCAxi9OjavTyQ","level":3,"time":"2017-07-05T04:04:34+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Not quoting the scalar \"%paths.base%\/..\/output\/\" starting with the \"%\" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0. at \/var\/lib\/jenkins\/workspace\/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ\/lib\/composer\/symfony\/yaml\/Inline.php#325"}
06:04:36 runsh: Exit code: 1
06:04:36 Makefile:9: recipe for target 'test' failed
06:04:36 make[1]: *** [test] Error 1
06:04:36 make[1]: Leaving directory '/var/lib/jenkins/workspace/owncloud-core_core_PR-28292-JZVBMLTQWI7DVBPCVKB72DFZ7XE4KBXX7LD5TOASFW3FDBJUVLOQ/tests/integration'
06:04:36 Makefile:195: recipe for target 'test-integration' failed
06:04:36 make: *** [test-integration] Error 2
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
06:04:36 Test execution failed: hudson.AbortException: script returned exit code 2
[Pipeline] step
06:04:36 Recording test results
[Pipeline] error
[Pipeline] }
[Pipeline] // wrap
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

Strange that `run.sh` returns exit code 1 despite skipped tests. Does it do so when run locally ?

**Comment by phil-davis** [comment]
@SergioBertolinSG is seeing if it can be fixed by the backport in #28301 so we may as well leave this for the next few hours and see if he gets success.

**Comment by phil-davis** [comment]
Rebased again - let's see the result tomorrow...

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
@PVince81 @DeepDiver1975 this has got through CI nd is ready to merge into stable10

**Pull request merged**
