### PR TITLE
[stable10] return all failed recipients in sendLinkShareMailFromBody

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #31847

### CODE REVIEW

**Comment by PVince81** [comment]
uh oh...
```
1) Test\Share\MailNotificationsTest::testSendLinkShareMailException with data set #0 ('lukas@owncloud.com', '', '', 'lukas@owncloud.com')
Argument 4 passed to Test\Share\MailNotificationsTest::testSendLinkShareMailException() must be an instance of Test\Share\string, string given
```

**Comment by PVince81** [comment]
it was green on master... weird

**Comment by phil-davis** [comment]
The cherry-pick was clean - I didn't have to resolve any conflicts.
I will look...

**Comment by phil-davis** [comment]
@PVince81 should I forward-port the 2nd commit?
That will make the ``master``and ``stable10`` code match.

**Comment by PVince81** [comment]
@phil-davis yes please

**Comment by phil-davis** [comment]
2nd commit forward-port to ``master`` PR #31940

**Comment by phil-davis** [comment]
CI passes now - achievement unlocked.

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
