### PR TITLE
The birthday_calendar is read-only

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #23079 

@georgehrke THX

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
rebased after merge of https://github.com/owncloud/core/pull/22909

**Comment by DeepDiver1975** [comment]
> I don't see how the tests are related to the birthday fix. Is back porting them necessary?

wana see them failing? :wink:

**Comment by georgehrke** [comment]
:+1:

**Comment by PVince81** [comment]
:+1:

**Comment by nikerossxp** [comment]
Now i can't localize name of calendar and change his color. And, visibility in calendar app always drops.

And still doesn't working autosync of contact births.

**Pull request merged**
