### PR TITLE
fixed typo error stated in issue #27228

### LINKED ISSUE #27228: typo in sftp public key
in apps/files_external/lib/Controller/AjaxController.php
--> private function generateSshKeys()

$key['publicKey'] = str_replace('phpseclib-generated-key', gethostname(), $key['publickey']);

creates a new array entry "public**K**ey" instead of replace the "publickey" field.
...

### PR DESCRIPTION
**Pull request by Prakharsvnit**
## Description
Fixes typo error in in apps/files_external/lib/Controller/AjaxController.php where a new array entry "publicKey" is created instead of "publickey" field.

## Related Issue

Fixes #27228 

## Motivation and Context
Prevents creation of another key

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mmattel** [comment]
Duplicate fix of #27234

**Comment by Prakharsvnit** [comment]
@mmattel i didn't see that before.I was just trying to solve some junior jobs.

**Comment by mmattel** [comment]
No worry, just wanted to document so it does not get double fixed :smile:

**Comment by Prakharsvnit** [comment]
@mmattel should i close this PR to resolve any possible conflict.

**Comment by mmattel** [comment]
As it is 100% the same, I would say yes.
There are for sure other open Junior Jobs which are just waiting for you !

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/pull/27234

**Comment by PVince81** [comment]
next time I suggest you assign yourself to the ticket you are working on to avoid having other people taking on it

**Comment by Prakharsvnit** [comment]
ok, will do that from next time.

**Pull request closed without merging**
