### PR TITLE
Revert "feat: show alert about ioc scanner to all customers on upgrade"

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Reverts owncloud/core#41137

### CODE REVIEW

**Review by IljaN — APPROVED** [review]

**Comment by pako81** [comment]
changelog missing?

**Comment by pako81** [comment]
we had actually https://github.com/owncloud/core/pull/41137/files#diff-f7540c5d8386d24f096d7231b371c0154ed89f6f7a7f32e4f4b2f65cb6c35f88. And we had it also documented in the Release Notes https://doc.owncloud.com/server_release_notes.html#changes-in-10-13-4

**Comment by DeepDiver1975** [comment]
why is it not in the revert then? did I miss to remove some parts?

**Comment by DeepDiver1975** [comment]
never the less - I consider this not worth a changelog item - release notes might be a different story.

but i don't know - no hard feelings here .... BTR topic - you guys decide :shrug:

**Pull request merged**
