### PR TITLE
notify on build failures when pushed/tagged on core

### PR DESCRIPTION
**Pull request by patrickjahns**
## Description

Send slack notifications, when a push/tag to `master` branch leads to a build failure

## Motivation and Context
We want to know instantly when our master branch is in 🔴 

## How Has This Been Tested?
🤖 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] CI improvement

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
slack notifications ? does it interface with rocketchat ?

**Comment by patrickjahns** [comment]
@PVince81 - rocketchat exposes a slack compatible webhook api so we can use the slack plugin for notifications :-)

**Comment by patrickjahns** [comment]
For testing - well I can purposely remove the tag/push part and fail a build iteration - we should see that notifications work

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@patrickjahns backport to have this on stable10 too ?

**Comment by patrickjahns** [comment]
Already there  https://github.com/owncloud/core/pull/31977 ;-)

**Pull request merged**
