### PR TITLE
Do not crash the command when exception happens on delete

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Exception could happen if there is any issue when we're deleting the uploads. If this happens, the command would crash and prevent further cleaning from happening

## Related Issue
https://github.com/owncloud/enterprise/issues/5125

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by mmattel** [comment]
@jvillafanez mind to add a changelog entry. We could approve and merge afterwards.

**Comment by phil-davis** [comment]
And rebase please - the branch is now a long way behind.

**Review by phil-davis — COMMENTED** [review]
Looks reasonable to me. I am struggling to think how to really test this, because it handles a situation that does not normally/easily happem.

Dev review please.

**Comment by jvillafanez** [comment]
> Looks reasonable to me. I am struggling to think how to really test this, because it handles a situation that does not normally/easily happen.

While probably not the best scenario, you can try to force an error by changing the permissions.
1. Upload a couple of chunks of a big file
2. Change the permissions of the uploaded chunks directly in the FS so they can't be deleted (not sure if the permission change should be applied to the chunk folder too or not)
3. Run the cleanup-chuk command

I'd expect an error to happen because it isn't possible to delete the chunks.

**Review by AlexAndBear — APPROVED** [review]

**Pull request merged**
