### PR TITLE
Adding CardDAV plugin to provide addressbook-home-set property

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@dmfs please test - THX - I'll update the test instance ...

@blizzz mind testing with KDE as well
@LukasReschke please test - THX

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Works for me :rocket:

**Comment by dmfs** [comment]
Looks good! Works for me too.

**Comment by LukasReschke** [comment]
:+1:

**Comment by blizzz** [comment]
Works with KDE.

To work with SailfishOS, the addressbooks must have a displayname set (currently not the case). Without displayname, syncing does not happen.

**Comment by DeepDiver1975** [comment]
:rocket:

**Pull request merged**
