### PR TITLE
Public link share disabled if password length is equal to 0

### LINKED ISSUE #20177: Submit button on password-protected link page should be disabled until something is put in
Because I assume there can not be empty passwords anyway? @DeepDiver1975 @PVince81 @MorrisJobke

### PR DESCRIPTION
**Pull request by prastut**
Fixes  #20177

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@prastut You don't need to create new branches all the time. Just update the old branch with a new commit and push that commit to github. Then it will get automatically added to the pull request ;)

**Comment by prastut** [comment]
@MorrisJobke:

@rullzer said since I am a ownCloud member now, I could push to main repo and it's better for review. Therefore made a new branch.

**Comment by rullzer** [comment]
:+1: works as advertised

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
