### PR TITLE
Initially load at least 250 users

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of https://github.com/owncloud/core/pull/20108

@butonic @blizzz @MorrisJobke @karlitschek THX

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by blizzz** [comment]
:-1: https://github.com/owncloud/core/pull/20108#issuecomment-151866829 f

**Comment by butonic** [comment]
@tariqsiddiqui can you test this for performance impacts in 8.2 please?

**Comment by DeepDiver1975** [comment]
> backport of #20108

even revert the pr against master?

**Comment by DeepDiver1975** [comment]
let close this PR for now to prevent accidental merge

**Pull request closed without merging**
