### PR TITLE
Fix path and secure flag of cookie_test

### LINKED ISSUE #26651: cookie_test path prevents clients to resend
As observed with @ogoffart, the "cookie_test" cookie doesn't have a correct path so the desktop client doesn't resend that cookie to the server.

This will make the server believe that this client doesn't support cookies and will recreate a session for every request. (I believe that the original purpose was that it tries to reuse the same session if a device token is used, not sure).

We need to make sure that the desktop client and mobile clients properly send "cookie_test" when it's there. @ogoffart @guruz @davivel 

If the path of the cookie needs to be adjusted we can do that on the server.

@PhilippSchaffrath since you're diving into auth code you might be able to find out why "cookie_test" is needed at all and what kind of logic is used if no cookies are supported.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/26651

@ogoffart @davivel please test

### CODE REVIEW

**Comment by PVince81** [comment]
I baked this cookie taking inspiration from the other cookies in that file, so I think now the path and secure flag should be correct.

cc @phisch @DeepDiver1975 @Peter-Prochaska

**Comment by davivel** [comment]
@jesmrec , could you have a look with the mobile apps? Thanks.

**Comment by PVince81** [comment]
I suspect that the problem only appears on environments where ownCloud is hosted in a subfolder, like "/owncloud". If it's hosted on the root of the vhost, the path will be correct since it defaults to "/".
That might explain why I never saw this issue on my own server.

**Comment by PVince81** [comment]
@guruz

**Comment by jesmrec** [comment]
@davivel iOS devices send correctly the `cookie_test` but Android devices does not, using the same server with the current patch and performing the same actions. 

CC @PVince81

**Comment by guruz** [comment]
Tried testing this with the desktop client.
In general I agree with the fix, HOWEVER for me it seems to have no effect.

If you send the cookie only when checking supportsCookies and you call supportsCookies only once from logClientIn then there was no chance to get the cookie even.

I also don't see the desktop client session in index.php/settings/personal?sectionid=security so no token was created.

**Comment by guruz** [comment]
you need to set the cookie when sending the first 401
but even that won't work for clients like the desktop client that send the password blindly
we wanted to change that in the desktop but then old server versions borked so we never changed it

https://github.com/owncloud/client/blob/c6f4f446192e5f11df80186e391b636471c15984/src/libsync/creds/httpcredentials.cpp#L53

**Comment by davivel** [comment]
> @davivel iOS devices send correctly the cookie_test but Android devices does not, using the same server with the current patch and performing the same actions.

I'll have a look to the Android app.

**Comment by PVince81** [comment]
@guruz indeed, I have the feeling this could never have worked

**Comment by PVince81** [comment]
I do wonder how the iOS client works then ? @jesmrec 

From the code path it looks like the iOS client would need to login twice, the first login would receive the cookie and the second login will tell the code that cookies work.

Unless maybe the first request receives a 401 with challenge ? But I don't think `supportsCookie` is reached for a 401.

**Comment by jesmrec** [comment]
Sorry, i have rechecked this issue. Both mobile clients are not sending the cookie in all requests. The cookie is received in the first OK response (propfind 207), but not resent in all the following requests. Needs to be checked deeply @davivel.

**Comment by jesmrec** [comment]
Maybe related with https://github.com/owncloud/core/issues/26651#issuecomment-291088914

- If the server is in "\", the cookie_test does not contain the path:

`Set-Cookie: ocfgt15emms5=2hhgs4fc6s0tle7oc48pgq3puf; path=/; secure; HttpOnly                                                                                                                                                      
Set-Cookie: cookie_test=test; expires=Fri, 28-Apr-2017 23:04:31 GMT; Max-Age=36000; secure; HttpOnly`

the first cookie contains the path, but the second does not.

- In the server is not in "\", the cookie_test contains the path:

`Set-Cookie: ocfjcfv3pcvs=i6sboee9j1hnp9uqcser74gfd6; path=/stable91/owncloud; secure; HttpOnly                                                                                                                                     
Set-Cookie: cookie_test=test; expires=Fri, 28-Apr-2017 14:08:52 GMT; Max-Age=3600; path=/stable91/owncloud; secure; httponly`

Both cases are tested with patched servers. 

@davivel @PVince81

**Comment by davivel** [comment]
@jesmrec , in the second case (server not in root path), are the mobile clients sending ```cookie_test``` in all the requests after the first one receiving ```Set-Cookie: cookie_test=test```?

**Comment by davivel** [comment]
@jesmrec , if I recall correctly, in the first case, the requests to Webdav path are sending ```cookie_test```, while the requests to OCS are not sending it, right?

That would be a correct behaviour. If ```Set-Cookie``` has no path set, the path of the current request is used by default. In the tested cases, that was the Webdav path, so the app will not send the cookie to OCS path.

The confusing part is that the PR seems to set a path. @PVince81 , is it possible that ```OC::$WEBROOT``` is not set the first time that ```supportsCookie``` is run if OC is in the root path of the web server?

**Comment by guruz** [comment]
@davivel @jesmrec The server is broken anyway because it does not send the cookie at the right place: https://github.com/owncloud/core/pull/27549#issuecomment-291584172
(Independant of whatever the path is)

**Comment by PVince81** [comment]
Cannot work, likely needs a different approach

**Pull request closed without merging**
