### PR TITLE
clean up typos in config.sample.php

### PR DESCRIPTION
**Pull request by carlaschroder**
A gaggle of typo fixes.

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by carlaschroder** [comment]
Contributor https://github.com/phil-davis has been doing an amazing job of going through the manuals and fixing typos.

**Comment by carlaschroder** [comment]
I applied his edits to configuration.sample.php, and made a clearer note in https://github.com/owncloud/documentation/blob/master/admin_manual/configuration_server/config_sample_php_parameters.rst that it needs to be edited here.

**Comment by phil-davis** [comment]
Happy to help. As a first-language English speaker it is easy for me to fix up this sort of stuff while reading the manuals when I start using a new Open Source product. English is such a rubbish language, no consistent spelling or syntax rules! I feel sorry for everyone else that somehow online multinational interaction and documentation has standardized to English. Someone should choose a better language for this :) Esparanto?

**Comment by carlaschroder** [comment]
lol @phil-davis. Yes, English is way fun.

"If the English language made any sense, lackadaisical would have something to do with a shortage of flowers...a catastrophe would be an apostrophe with fur." - Doug Larson

"To read makes our speaking English good." - Joss Whedon.

**Pull request merged**
