### PR TITLE
Restructure config.sample.php of master

### PR DESCRIPTION
**Pull request by ghost**
Same as #19287 but for master

### CODE REVIEW

**Comment by RealRancor** [comment]
This also solves the issue that "supportedDatabase" parameter is currently found within the "Using Object Store" headline:

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/config_sample_php_parameters.html#using-object-store-with-owncloud

**Comment by RealRancor** [comment]
@PVince81 @LukasReschke Just some random ping :)

Anyone which i can pull in here so that such a simple change is merged?

**Comment by PVince81** [comment]
:+1:

CC @MorrisJobke @carlaschroder as it affects (improves) the docs

**Comment by MorrisJobke** [comment]
Looks good :+1:

**Comment by RealRancor** [comment]
Thanks for merging. Backport to stable8.1 can be also found in https://github.com/owncloud/core/pull/19287

**Pull request merged**
