### PR TITLE
Fix login page logo + login arrow

### PR DESCRIPTION
**Pull request by PVince81**
Before:
ie8-madness-before

After:
ie8-madness-after

The checkbox must be fixed separately, might be more complicated.

Please review @MorrisJobke @owncloud/designers @karlitschek @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
For https://github.com/owncloud/core/issues/18619

**Comment by karlitschek** [comment]
argh. :+1:

**Comment by SergioBertolinSG** [comment]
In the enterprise theme there is no logo.

screen shot 2015-09-30 at 09 33 26

**Comment by SergioBertolinSG** [comment]
It is happening also with community theme:

screen shot 2015-09-30 at 09 42 37

**Comment by MorrisJobke** [comment]
@PVince81 Can we move the changes to the `fixes.css`? I will try to do so now.

**Comment by MorrisJobke** [comment]
I moved the fixes to the fixes.css and tested it. It works all fine here in IE8.

@SergioBertolinSG Maybe a caching issue? Can you check if the image is correctly loaded (network tools in IE)

**Comment by PVince81** [comment]
Enterprise theme needs to be fixed separately. In this PR I had to recreate a separate PNG file for the logo. The same needs to be done for the enterprise team.

**Comment by PVince81** [comment]
@MorrisJobke the problem with fixes.css is that whenever someone touches the original style, they don't directly see that there was a IE8 workaround for it. Also in the future it's easy to grep for ".ie8" to remove them. In the bright future where IE8 is :skull:

**Comment by SergioBertolinSG** [comment]
@MorrisJobke I'm not seeing network tools in ie8 . But only three images are loaded loading-dark.gif, user.png and password.png

**Comment by PVince81** [comment]
My IE8 version on windows XP: 8.0.6001.18702
The one from @SergioBertolinSG on Windows Server 2008: 8.0.7601.17514

**Comment by MorrisJobke** [comment]
> @MorrisJobke the problem with fixes.css is that whenever someone touches the original style, they don't directly see that there was a IE8 workaround for it. Also in the future it's easy to grep for ".ie8" to remove them. In the bright future where IE8 is :skull:

This was just requested by @jancborchardt back in time. Feel free to revert the commit. I just don't want to clutter all the IE8 related fixes all over the place

**Comment by PVince81** [comment]
@MorrisJobke it's fine by me, I don't mind

**Comment by PVince81** [comment]
I setup a Windows 7 VM which has IE8 8.0.7601.17514 and the logo appear properly.

**Comment by PVince81** [comment]
Let's hope optipng will help having the same format in the end and make windows server 2008 behave

**Comment by PVince81** [comment]
@SergioBertolinSG can you make a separate ticket for the enterprise edition logo ? (in the enterprise repo)

First we need to solve the mystery of the community edition logo.

**Comment by davitol** [comment]
:+1:

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/19474 to investigate the Windows Server 2008 mystery. We need to move forward with the other IE8 fixes first...

**Comment by jancborchardt** [comment]
(I’m on vacation, this is another exception. ;)

@PVince81 @MorrisJobke THANK YOU AWESOME FOLKS FOR FIXING THESE BLOODY IE8 ISSUES! I owe you a beer.

**Pull request merged**
