### PR TITLE
fix: create previews from first page on multi-page documents

### LINKED ISSUE #41042: PDF Preview only shows last section of pdf
Hi!
I enabled the PDF preview provider.
That did work, however, the thumbnail images generated for documents with multiple pages are not as expected.
I tried to fix this in /var/www/owncloud/lib/private/Preview/Bitmap.php, but I can't get it to work as I don't fully understand imagick and how it works with pdfs when using stream handles.
Is there an easy fix I could apply?
Every Idea is very appreaciated!

### Steps to reproduce
1. Enable PDF Preview
2. Upload a PDF File with more than 2 pages
3. Open file detail view

### Expected behaviour
My expectation was, that the very first page would be used to generate the preview like when the document only has one page.

### Actual behaviour
When a preview for a PDF with 2 or more pages is generated, the thumbnail only shows the last visible portion of the bottom most page instead of the upmost part of the first page.

### Server configuration
**Operating system**:
Debian 10

**Web server:**
Included in docker image, don't know

**Database:**
MariaDB10.6
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.12.2 
**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
dockerhub

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Previews are now generated from the first page and no longer from the last page.

## Related Issue
- Fixes  https://github.com/owncloud/core/issues/41042

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by pako81 — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@DeepDiver1975 this seems like a good thing - merge?

**Comment by DeepDiver1975** [comment]
this need some more testing - as per #41042 it is not working ...... no idea if the code has issues or there have been issues in applying the patch.

**Comment by pako81** [comment]
Confirmed current code is not properly working. It seems `setIteratorIndex` should be used in this case, so:
```
$bp->readImageFile($stream);
$bp->setIteratorIndex(0);
```
this way it looks like previews are correctly generated from the first page of the document.

**Comment by phil-davis** [comment]
works for me. This PR is quite old, so I will rebase to get up-to-date CI with current master. Then I will try to add an acceptance test - we already have thumbnail tests, so I should be able provide a multi-page PDF as a fixture along with the expected thumbnail of the first page.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
```
    When user "Alice" downloads the preview of "/Preview-test.pdf" with width "612" and height "792" using the WebDAV API # FeatureContext::downloadPreviewOfFiles()
    Then the HTTP status code should be "200"                                                                             # FeatureContext::thenTheHTTPStatusCodeShouldBe()
      HTTP status code 404 is not the expected value 200
      Failed asserting that 404 matches expected '200'.
```
Hmm, this passed for me locally. I suppose there is some setting of the max preview size or something that needs to be done to get a "large" preview like in this test.

**Comment by phil-davis** [comment]
> Hmm, this passed for me locally. I suppose there is some setting of the max preview size or something that needs to be done to get a "large" preview like in this test.

Preview of PDFs is not enabled by default. I had to set it in system config `enabledPreviewProviders`

**Pull request merged**
