### PR TITLE
[stable8] Don't use command concatenation

### PR DESCRIPTION
**Pull request by LukasReschke**
Possibly fixes https://github.com/owncloud/core/issues/16853
(needs a backport once verified)

### CODE REVIEW

**Comment by LukasReschke** [comment]
@stmgit Please test

**Comment by PVince81** [comment]
Tested overwriting file with sync client, works :+1:

**Comment by LukasReschke** [comment]
7: https://github.com/owncloud/core/pull/16864
6: https://github.com/owncloud/core/pull/16865

**Comment by stmgit** [comment]
@LukasReschke fix confirmed working. Thx

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by directict** [comment]
How do i implement this? we also get e-tag errors when editing files synced on SMB.
'Don't use command concatenation'

**Comment by LukasReschke** [comment]
> How do i implement this? we also get e-tag errors when editing files synced on SMB.

Replace `apps/files_external/3rdparty/smb4php/smb.php` on your instance with the one from https://raw.githubusercontent.com/owncloud/core/stable8/apps/files_external/3rdparty/smb4php/smb.php

**Comment by directict** [comment]
Dear Lukas,

/hero! Works! Thx!

Met vriendelijke groet:
Gert-Jan Slot

[cid:CC33FB0A-C3E8-4664-B08B-5F3C283035A2]
AUTOMATISERING – INTERNETDIENSTEN – BUSINESS SOFTWARE

Kroezenhoek 5
7683 PP DEN HAM OV
Tel: +31 546 – 641144
Fax: +31 546 – 641133
Email: gertjan@directict.nl<mailto:gertjan@directict.nl>
Website: http://www.directict.nl<http://www.directict.nl/>

Van: Lukas Reschke [mailto:notifications@github.com]
Verzonden: woensdag 17 juni 2015 15:55
Aan: owncloud/core
CC: NOC | Direct ICT
Onderwerp: Re: [core] [stable8] Don't use command concatenation (#16862)


How do i implement this? we also get e-tag errors when editing files synced on SMB.

Replace apps/files_external/3rdparty/smb4php/smb.php on your instance with the one from https://raw.githubusercontent.com/owncloud/core/stable8/apps/files_external/3rdparty/smb4php/smb.php

**Comment by anduz** [comment]
That's what I've been looking for. Created some *.ocTransferId*.part files.
Thank you.

**Pull request merged**
