### PR TITLE
[stable8.1] Remove last occurence of `forcessl`

### PR DESCRIPTION
**Pull request by LukasReschke**
@karlitschek Backport?

backport of https://github.com/owncloud/core/pull/18582

### CODE REVIEW

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by MorrisJobke** [comment]
Backport approved: https://github.com/owncloud/core/pull/18582#issuecomment-135019915

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot Retest this please.

**Comment by MorrisJobke** [comment]
cc @Xenopathic

**Comment by Xenopathic** [comment]
:+1:

**Comment by LukasReschke** [comment]
Ok. 3rd retest already or so.

@DeepDiver1975 OCI on CI seems broken.

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Comment by DeepDiver1975** [comment]
Afaik the unit test execution times are tooooo Bad now since we merged DB locking. 
I tend to revert .....

**Pull request merged**
