### PR TITLE
Adjust edition string

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Expired demo key will return community edition instead of enterprise

## Related Issue

https://github.com/owncloud/enterprise/issues/4020

## How Has This Been Tested?
Manually tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

**PR targets release-10.5.0 branch**, It's expected to be merged into master along with the release changes

### CODE REVIEW

**Comment by micbar** [comment]
@jvillafanez Can you cover the complex "edition" logic in a unit test?

**Comment by jvillafanez** [comment]
Added tests matching the current logic

**Comment by jvillafanez** [comment]
@micbar this is ready

**Comment by phil-davis** [comment]
@micbar if you want to merge this like it is, to `release-10.5.0` then please do that. And I can then update the merge-back PR #37648 so that it includes this (or if you do not want to do merge-back then say so)

**Review by micbar — APPROVED** [review]

**Pull request merged**
