### PR TITLE
fixes occ doesn't support enabling/disabling multiple apps at once

### PR DESCRIPTION
**Pull request by alchalade**
## Description

Allows users to enable multiple apps at once
./occ app:enable app1, app2
## Related Issue

- Fixes <issue_link>
https://github.com/owncloud/core/issues/32751
## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ x] Code changes
- [ x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by mmattel** [comment]
Documentation relevant.
@settermjd FYI

**Comment by mmattel** [comment]
@alchalade , can you sign the CLA, link above, many thanks.

**Comment by alchalade** [comment]
> @alchalade , can you sign the CLA, link above, many thanks.

Hi,
done.

**Comment by mmattel** [comment]
@phil-davis drone failed, but when you look into all is green ? Mind to take a look on ?

**Comment by phil-davis** [comment]
@alchalade https://drone.owncloud.com/owncloud/core/14314/74 
You have made code style changes (as well as the functional changes), and those code style changes fail the code style checking.
You can fix/revert them with:
```
make test-php-style-fix
```

**Comment by alchalade** [comment]
> @alchalade https://drone.owncloud.com/owncloud/core/14314/74
> You have made code style changes (as well as the functional changes), and those code style changes fail the code style checking.
> You can fix/revert them with:
> 
> ```
> make test-php-style-fix
> ```

Sorry for the late response, I will do it over the weekend.

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
