### PR TITLE
Admin checkboxes for stable8.2

### PR DESCRIPTION
**Pull request by Henni**
backport of #19744

@nickvergessen is this the correct way to submit a backport?

cc @MorrisJobke @PVince81 @jancborchardt

### CODE REVIEW

**Comment by nickvergessen** [comment]
only the translation commit should not be there
https://github.com/owncloud/core/pull/19744#issuecomment-148017261

What did you do different?

**Comment by Henni** [comment]
I rebased the admin-checkboxes branch on stable8.2

**Comment by MorrisJobke** [comment]
```
git rebase --interactive stable8.2
```

and then remove the commit in the editor that is opened ;)

**Comment by PVince81** [comment]
When submitting a PR, it's always best to check the "commits" tab and "files changed". If you see that it doesn't match what you changed, then it's wrong.

In the case of this PR, it looks wrong because you also have the transifex commit in it.

Please try again, first you need to check out "stable8.2" locally and make sure it's up to date ("git pull origin stable8.2"). Then from there, you create a sub-branch "stable8.2-yourchanges" then commit and push your changes there. And then you submit a PR for this branch to stable8.2 :smile:

**Comment by Henni** [comment]
@nickvergessen @MorrisJobke @PVince81 thanks for all the help!

#19763 should work

**Pull request closed without merging**
