### PR TITLE
Test for checking existence of tags in shared files

### PR DESCRIPTION
**Pull request by bhawanaprasain**
## Description

We can check for existence of tags in shared files .

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests only (no source changes)

### CODE REVIEW

**Comment by bhawanaprasain** [comment]
@dpakach @skshetry @paurakhsharma please review on my PR.

**Comment by bhawanaprasain** [comment]
@dpakach @skshetry @paurakhsharma please review on my PR.

**Comment by phil-davis** [comment]
@bhawanaprasain now it got conflicts with the other `createTags` PR that was merged.

**Comment by bhawanaprasain** [comment]
@phil-davis I have fixed the conflicts.

**Review by paurakhsharma — COMMENTED** [review]
Looks good to me :+1:

**Review by phil-davis — APPROVED** [review]

**Review by dpakach — APPROVED** [review]
LGTM :+1:

**Comment by phil-davis** [comment]
Random drone errors - restarting build.

**Comment by phil-davis** [comment]
Backport `stable10` #35859

**Comment by phil-davis** [comment]
restarted drone - master CI should be OK now.

**Pull request merged**
