### PR TITLE
[tests-only]Add provisioning app required tag to a tests

### LINKED ISSUE #4824: A test requires provisioning API but is not annotated as such
During https://github.com/cs3org/reva/pull/3300 and https://github.com/owncloud/core/pull/40406 I ran into this:
```
  @issue-ocis-3561 @skipOnLDAP @skip_on_objectstore @skipOnOcV10.3
  Scenario Outline: Listing other user's trashbin is prohibited for newly recreated user with same name # /drone/src/tmp/testrunner/tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature:228
    Given using <dav-path> DAV path                                                                     # FeatureContext::usingOldOrNewDavPath()
    And user "testtrashbin102" has been created with default attributes and without skeleton files      # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "testtrashbin102" has uploaded file "filesForUpload/textfile.txt" to "/textfile0.txt"      # FeatureContext::userHasUploadedAFileTo()
    And user "testtrashbin102" has uploaded file "filesForUpload/textfile.txt" to "/textfile2.txt"      # FeatureContext::userHasUploadedAFileTo()
    And user "Brian" has been created with default attributes and without skeleton files                # FeatureContext::userHasBeenCreatedWithDefaultAttributesAndWithoutSkeletonFiles()
    And user "testtrashbin102" has deleted file "/textfile0.txt"                                        # FeatureContext::userHasDeletedFile()
    And user "testtrashbin102" has deleted file "/textfile2.txt"                                        # FeatureContext::userHasDeletedFile()
    And the administrator has deleted user "testtrashbin102" using the provisioning API                 # FeatureContext::theAdministratorHasDeletedUserUsingTheProvisioningApi()
    And these users have been created without skeleton files and not initialized:                       # FeatureContext::theseUsersHaveBeenCreatedWithoutSkeletonFiles()
      | username        |
      | testtrashbin102 |
    And user "testtrashbin102" has uploaded file "filesForUpload/textfile.txt" to "/textfile3.txt"      # FeatureContext::userHasUploadedAFileTo()
    And user "testtrashbin102" has deleted file "/textfile3.txt"                                        # FeatureContext::userHasDeletedFile()
    When user "Brian" tries to list the trashbin content for user "testtrashbin102"                     # TrashbinContext::userTriesToListTheTrashbinContentForUser()
    Then the HTTP status code should be "<status-code>"                                                 # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the last webdav response should not contain the following elements                              # TrashbinContext::theLastWebdavResponseShouldNotContainFollowingElements()
      | path          | user            |
      | textfile0.txt | testtrashbin102 |
      | textfile2.txt | testtrashbin102 |
      | textfile3.txt | testtrashbin102 |

    Examples:
      | dav-path | status-code |
      | new      | 404         |
        Failed step: And the administrator has deleted user "testtrashbin102" using the provisioning API
        User 'testtrashbin102' should not exist but does exist
        Failed asserting that true is false.
INFORMATION: could not delete user 'testtrashbin102' 401 
      | spaces   | 404         |
        Failed step: And the administrator has deleted user "testtrashbin102" using the provisioning API
        User 'testtrashbin102' should not exist but does exist
        Failed asserting that true is false.
```

The test tries to use the provisioning API in reva but is not annotated as such. I'll add a new section in the expected failures file in https://github.com/cs3org/reva/pull/3300 and reference this issue.

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description

The changed test requires `provisioning-app` but the tag was missing and it failed in reva. This PR adds the required tag

## Related Issue

- Fixes: https://github.com/owncloud/ocis/issues/4824

## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by SwikritiT** [comment]
Do not merge until https://github.com/cs3org/reva/pull/3366 is green on ci

**Review by phil-davis — COMMENTED** [review]
I don't see any tag add or changed ???

**Comment by SwikritiT** [comment]
> I don't see any tag add or changed ???

I added the the tag here https://github.com/owncloud/core/pull/40429/commits/336b98c32878fa7574f8dd59e34a6654d3c466c8 and then realized  maybe if i add code of user deletion in ldap the test might run in reva as well. This PR should be in draft for now. Forgot to change it. I'll revert the changes and add the tag if the test fails in reva

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm :+1:

**Review by grgprarup — APPROVED** [review]
lgtm :+1:

**Pull request merged**
