### PR TITLE
update icewind/smb to 1.0.1

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes a php warning for some smb servers.

cc @PVince81 @DeepDiver1975 @mmattel

### CODE REVIEW

**Comment by Xenopathic** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
Looks good - @icewind1991 we need to update owncloud/windows_network_drive as well

**Comment by icewind1991** [comment]
since icewind/smb is in core owncloud/windows_network_drive should use the lib from core instead of bundling it's own

one day...

**Comment by DeepDiver1975** [comment]
> since icewind/smb is in core owncloud/windows_network_drive should use the lib from core instead of bundling it's own
> 
> one day...

yeah - well this brings up the old issue of apps being self contained vs having multiple lib versions installed in parallel.

**Comment by mmattel** [comment]
:+1:  (for merging readyness)

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
