### PR TITLE
Fix postScanFile event and make it available to utils scanner

### PR DESCRIPTION
**Pull request by oparoz**
The `postScanFile` event is important when scanning external storage as it indicates when the file is ready to be used and it currently only fires when updated metadata is available.

The 2nd commit makes the 2 events `postScanFile` and `postScanFolder` events available in OC\Files\Utils\Scanner. This one can be postponed as this would be considered an enhancement.

@icewind1991 @PVince81 @Xenopathic

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by mmattel** [comment]
:+1:  merging welcomed :smile:

**Comment by oparoz** [comment]
@DeepDiver1975

**Comment by PVince81** [comment]
I'd still like to get a comment from the scanning expert @icewind1991

**Comment by oparoz** [comment]
Me too :)

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by oparoz** [comment]
@karlitschek - It would be useful to have this in 8.1 for people wanting to generate thumbnails.

**Comment by karlitschek** [comment]
Yes. Shouldn't hurt. Please backport to stable8.1 Thanks!

**Pull request merged**
