### PR TITLE
Dont check for avatar folder if not enabled

### LINKED ISSUE #30415: Disabling avatars doesn't stop looking for avatar folder
If you disable avatars in the config.php the owncloud code will still look for and try to create the avatar folder. This is because of the templatelayout code ignoring if avatars are loaded. We can use this patch to force ownCloud to stop looking for the avatar folder.

```diff
--- lib/private/TemplateLayout.php      2017-11-27 09:45:17.879231965 +0100
+++ lib/private/TemplateLayout.php      2017-12-12 22:33:49.752298379 +0100
@@ -98,7 +98,8 @@
                        if (\OC_User::getUser() === false) {
                                $this->assign('userAvatarSet', false);
                        } else {
-                               $this->assign('userAvatarSet', \OC::$server->getAvatarManager()->getAvatar(\OC_User::getUser())->exists());
+                               $this->assign('userAvatarSet', false);
+                               //$this->assign('userAvatarSet', \OC::$server->getAvatarManager()->getAvatar(\OC_User::getUser())->exists());
                        }

                } else if ($renderAs == 'error') {
```

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
If avatars are not enabled system wide, dont check if they exist as this does FS / FC calls which can fail if the migration to 10 failed. Basically, be more tolerant.

## Related Issue

- Fixes <issue_link>

## Motivation and Context
Fixed https://github.com/owncloud/core/issues/30415

## How Has This Been Tested?
Tried with and without an avatar. With and without avatars enabled. Tried deleting the avatars folder from FS and FC. All covered.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
Makes sense :+1:

**Comment by PVince81** [comment]
@tomneedham please backport

**Comment by PVince81** [comment]
added TemplateLayout as untestable class here https://github.com/owncloud/core/issues/31854

**Comment by phil-davis** [comment]
Backport ``stable10`` #31998

**Pull request merged**
