### PR TITLE
[testing] Allow to lock a file without the lock being killed at the end of the request

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Yo @DeepDiver1975 lately I’m mentioned by mention-bot on some pull requests where I have no idea why I am related. Any issue there?

**Comment by nickvergessen** [comment]
Yo @jancborchardt you are the only person, apart from the PR owner, who touched the info.xml:
https://github.com/owncloud/core/blame/add-fake-locking-to-testing-app/apps/testing/appinfo/info.xml

So in order to find people that can help reviewing the change, the blaming finds you.
If you need more info read: https://github.com/facebook/mention-bot#algorithm

If that still sucks, we can add you to the userBlacklist, so you are never mentioned anymore.

**Comment by jancborchardt** [comment]
Ah ok, in that case nevermind. :)

**Comment by nickvergessen** [comment]
@PVince81 @icewind1991 please review, so we can finally have smashbox locking tests: https://github.com/owncloud/smashbox/issues/134

**Comment by PVince81** [comment]
:+1:

**Comment by nickvergessen** [comment]
@DeepDiver1975 can we have this testing only PR?

**Comment by nickvergessen** [comment]
Bump, @DeepDiver1975 please review and merge ;)

**Comment by PVince81** [comment]
@nickvergessen is the "testing" app removed from the tarballs at build time ?
If not we need to make sure it gets done.

**Comment by nickvergessen** [comment]
Yes it is already since 8.2

**Comment by PVince81** [comment]
@icewind1991 @SergioBertolinSG second review ?

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
