### PR TITLE
Test updating text(4000) to clob

### PR DESCRIPTION
**Pull request by nickvergessen**
Revive of https://github.com/owncloud/core/pull/15058 to see if the doctrine updates helped for https://github.com/owncloud/activity/pull/512

### CODE REVIEW

**Comment by nickvergessen** [comment]
@DeepDiver1975 jenkins having issues again?

**Comment by nickvergessen** [comment]
Okay, would still need to hack doctrine, since it only uses modify, instead of the recommended add-copy-drop-rename workaround when changing types: https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:1770086700346491686

**Comment by DeepDiver1975** [comment]
Just another reason to move over to #14851

**Comment by DeepDiver1975** [comment]
setting 9.2 @cmonteroluque

**Comment by DeepDiver1975** [comment]
will not work ->close

**Pull request closed without merging**
