### PR TITLE
Prevent share-icon from shrinking

### LINKED ISSUE #29821: Long public share name hides share options and deforms icon
master @ fc4873385330fd7c9182c7c05913fed3421f46ee

1. create a folder
2. click share icon
3. go to public link
4. create public link with a long name

expected: everything looks pretty
actual: weird squished link icon see screenshot

screen shot 2017-12-12 at 10 46 09

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Prevents public-share icons from shrinking if the link title is long.

## Related Issue

Fixes: https://github.com/owncloud/core/issues/29821

## How Has This Been Tested?
Visual Test in latest Chrome, FF and MS Edge

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
using exotic CSS stuff ? => need testing in IE11

**Comment by tomneedham** [comment]
👍

**Review by tomneedham — APPROVED** [review]

**Comment by davitol** [comment]
Tested and works in Mozilla, IE11 and Safari

**Comment by tomneedham** [comment]
Still fails if you enter a name wihtout spaces - is this a real use case?

**Comment by PVince81** [comment]
backport please

**Comment by phil-davis** [comment]
Backport stable10 #30352

**Pull request merged**
