### PR TITLE
[stable8] proper filename for "require version.php"

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #14750 

cc @DeepDiver1975 @Xenopathic @fluffy88

### CODE REVIEW

**Comment by Xenopathic** [comment]
:+1:

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by MorrisJobke** [comment]
:construction: Don't merge until 8.0.2 is released :construction:

**Comment by nickvergessen** [comment]
can this easily have a test?

**Comment by MorrisJobke** [comment]
> can this easily have a test?

let me try this

**Comment by MorrisJobke** [comment]
> let me try this

Invoking a private static method doesn't work that well with the Test_Helper. I would say this is something once this is done non static.

**Comment by nickvergessen** [comment]
Well we could test `getBuild()` or one of the other methods, but fine by me

**Pull request merged**
