### PR TITLE
[stable9] Log more information by default

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/owncloud/core/pull/23443

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
Rebased to retrigger CI

**Comment by MorrisJobke** [comment]
@LukasReschke Why "2 - Developing"? I checked it with the command line tool, cron and the web UI all work.

**Comment by DeepDiver1975** [comment]
This change is suspected to break ci on mysql

**Comment by LukasReschke** [comment]
>  @LukasReschke Why "2 - Developing"? I checked it with the command line tool, cron and the web UI all work.

Because of https://github.com/owncloud/core/pull/23488 :wink:

**Comment by MorrisJobke** [comment]
> Because of #23488

Could you add that fix to this PR?

**Comment by LukasReschke** [comment]
> Could you add that fix to this PR?

Done.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
