### PR TITLE
composer remove natxet/CssMin

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
cssmin was used in the asset pipline feature which we removed some time back

## Motivation and Context
leave behind what you dont need anymore

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
yeah... we should rather minify CSS later using some tools called from the Makefile

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
backport ?

**Comment by DeepDiver1975** [comment]
> backport ?

will take care - yes

**Comment by DeepDiver1975** [comment]
do we need to wait for the ui tests?

**Comment by DeepDiver1975** [comment]
rebased because of conflict in composer.lock

**Comment by DeepDiver1975** [comment]
merging

**Pull request merged**
