### PR TITLE
feat: add samesite cookie attribute to session cookie

### PR DESCRIPTION
**Pull request by fschade**
## Description
to decrypt oc_sessionPassphrase we need to have the session cookie samesite attribute to be set the same

## Related Issue

- Extends #38458

## Motivation and Context

the passphrase cookie should have the same samesite attribute as the oc_sessionPassphrase cookie. If they are different it's not possible to decrypt oc_sessionPassphrase in cases like a iframe because the passphrase then is unknown.

## How Has This Been Tested?

- manual in teams

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by IljaN — APPROVED** [review]
LGTM :+1:

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
1. conflict
2. drone :red:
3. please explain why this is necessary - usage scenario- THX

**Comment by mmattel** [comment]
`strict` --> `Strict`
in this case you also have to fix: https://github.com/owncloud/core/pull/38458/files#diff-3bbe91e1f85eec5dbd0031642dfb0ad6749b550fc3b94af7aa68a98210b78738R277
(config/config.sample.php: `'http.cookie.samesite' => 'strict',`)

**Comment by fschade** [comment]
> `strict` --> `Strict`
> in this case you also have to fix: https://github.com/owncloud/core/pull/38458/files#diff-3bbe91e1f85eec5dbd0031642dfb0ad6749b550fc3b94af7aa68a98210b78738R277
> (config/config.sample.php: `'http.cookie.samesite' => 'strict',`)

thanks @mmattel, i updated the pr

**Comment by fschade** [comment]
> 1. conflict
> 2. drone :red:
> 3. please explain why this is necessary - usage scenario- THX

i updated "Motivation and Context"

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
squash plz

**Review by micbar — APPROVED** [review]
LGTM

**Comment by DeepDiver1975** [comment]
> i like to keep the history, anyway done

we always squash before merge

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
