### PR TITLE
Fix tab headers on small display ratio

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Fixing tabheader misalign issue on small display ratio, also adjust selected style which is matching better now to other elements (for example left sidebar)
Issue reported by @ChrisEdS 

## Tested on:
- Firefox
- Google Chrome
- IE11
- Edge
- Safari 
- Android Chrome Mobile

## Screenshots (if appropriate):
Before:
image

After:
image
(Normal view mode)
image
(Shrinked view mode)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Comment by micbar** [comment]
please add changelog

**Comment by JanAckermann** [comment]
@micbar done

**Review by JammingBen — APPROVED** [review]
LGTM 👍

**Review by hurradieweltgehtunter — DISMISSED** [review]
Hovering state of the tabs is wider than the un-hovered state which results in a little sideways glitch when hovering over the tabs.
`font:weight: bold; ` makes the tab wider.
-> remove `font-weight: bold;`
or add `font-weight: bold` to unhovered state, too

**Comment by JanAckermann** [comment]
@hurradieweltgehtunter in which browser you expirience this glitch ? can't reproduce it.

**Comment by JanAckermann** [comment]
@micbar @hurradieweltgehtunter @ChrisEdS since we refactored the whole tab headers look and feel, i request a new review

**Review by ChrisEdS — APPROVED** [review]
Tested on Chrome. Looks good to me!

**Pull request merged**
