### PR TITLE
Exclude users from sharing if they are a member of any excluded group - util.php

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Apply changes from PR #31490 to the "copy"  of the logic that (unfortunately) is in ``lib/private/legacy/util.php`` ``isSharingDisabledForUser()``

## Related Issue
https://github.com/owncloud/enterprise/issues/2508

## Motivation and Context
Fix all copies of this code.
Discovered while doing the code for issue #31817 PR #31816 

## How Has This Been Tested?
Unit test change.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
I wonder from where this is called, we should find this for the acceptance tests to trigger it

**Comment by PVince81** [comment]
Ouch, lots of them.

```
apps/files_sharing/appinfo/app.php|77| if (\OCP\Util::isSharingDisabledForUser() === false) {
apps/files_sharing/lib/External/Storage.php|297| if (\OCP\Util::isSharingDisabledForUser() || !\OC\Share\Share::isResharingAllowed()) {
apps/files_sharing/lib/SharedStorage.php|169| if (\OCP\Util::isSharingDisabledForUser()) {
apps/files_sharing/lib/SharedStorage.php|200| if (\OCP\Util::isSharingDisabledForUser() || !\OC\Share\Share::isResharingAllowed()) {
lib/public/Util.php|179| public static function isSharingDisabledForUser() {
lib/private/Files/FileInfo.php|210| if (\OCP\Util::isSharingDisabledForUser() || ($this->isShared() && !\OC\Share\Share::isResharingAllowed())) {
lib/private/Files/View.php|1474| $sharingDisabled = Util::isSharingDisabledForUser();
lib/private/Files/View.php|1552| if (Util::isSharingDisabledForUser()) {
lib/private/Share/Share.php|671| if (!\OC\Files\Filesystem::isSharable($path) || \OCP\Util::isSharingDisabledForUser()) {
lib/private/Share/Share.php|1928| if (isset($row['permissions']) && (!self::isResharingAllowed() | \OCP\Util::isSharingDisabledForUser())) {
core/js/config.php|172| 'sharingDisabledForUser' => \OCP\Util::isSharingDisabledForUser(),
```

As I can see it might be reflected on "oc:permissions" for a received share: the user wouldn't be able to reshare. The share permission would be missing on that entry.

**Comment by phil-davis** [comment]
The conflict is like always nowadays - many lines of code between ``master``  and ``stable10`` are different because of the code-style changes in ``master``. The backport PR has not been merged yet.

**Comment by phil-davis** [comment]
Yes, I agree - I could not see anything that currently uses it. I just "happened" to use it in #31816 and thus noticed the missing logic. I will amend that PR  to use a not-deprecated method.

I guess we could tag this old method as deprecated? @PVince81 feel free to push an extra commit here if you want to do that now.

**Comment by PVince81** [comment]
@phil-davis :fire: https://github.com/owncloud/core/pull/31823

**Pull request merged**
