### PR TITLE
Catch exception when querying direct download link

### PR DESCRIPTION
**Pull request by PVince81**
- [x] REQUIRES https://github.com/owncloud/core/pull/21086 to be testable

@LukasReschke @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/21033

**Comment by PVince81** [comment]
Steps here https://github.com/owncloud/core/issues/21033#issuecomment-163323692

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I rebased this to include #21086

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by PVince81** [comment]
Would like to backport this to 8.2.2 as it was a 8.2 issue @karlitschek (related to detecting remote share availability)

backport PR here: https://github.com/owncloud/core/pull/21046

**Comment by PVince81** [comment]
Note: only 8.2 backport is needed because the issue was introduced by the new "storage availability check debouncer" storage wrapper that only exists since 8.2.

**Comment by karlitschek** [comment]
backport makes sense for me. thanks :+1:

**Pull request merged**
