### PR TITLE
[stable10] Groups for occ command and UI testing

### PR DESCRIPTION
**Pull request by phil-davis**
Backport of #28190

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]

**Comment by phil-davis** [comment]
I am starting to hate CI - random stuff goes wrong. With Travis, I can restart a job that got some connection problem or... between SauceLabs and Travis. I don't see how to restart Jenkins???

**Review by individual-it — APPROVED** [review]

**Comment by PVince81** [comment]
> I am starting to hate CI

welcome to the club

**Comment by PVince81** [comment]
> I don't see how to restart Jenkins???

There used to be a button for logged in users. Then after some update it disappeared. We never managed to make it appear again for non-admins.

**Comment by phil-davis** [comment]
#28276 is the same code for stable10. CI passed there and it has been merged.
Closing this one.

**Pull request closed without merging**
