### PR TITLE
[full-ci] Symfony 5.4

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Code and tests have already been updated so that they work with the existing Symfony 4.4 and also work with Symfony 5.4.
See the related issue for links to those PRs.

IMO this is ready for merge to core.

Note: if we merge this, then it will end up in the 10.13 release. We will have to also release any apps that need code changes. Those will be found by nightly CI running with core master having Symfony 5. Apps can have code made compatible with both Symfony 4 and 5, so any effected apps can be released separately prior to 10.13 and will still work with older 10.* releases that have Symfony 4.

There will be some effort needed to sort out and release the apps.

## Related Issue
#39630 

## Motivation and Context
Symfony 4 support is heading to the end.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliEncryption-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37635/114

**Comment by phil-davis** [comment]
Note: needs discussion about when we actually do this - now for 10.13, or later in the year.
Symfony 4.4 security support ends in November 2023.

**Comment by pako81** [comment]
We should probably try to get this into 10.13.0. I don't think we will able to release an other major version before November 2023.

**Comment by phil-davis** [comment]
> We should probably try to get this into 10.13.0. I don't think we will able to release an other major version before November 2023.

Sounds reasonable. I don't think that there will be much work in adjusting app code - the few things that had to be changed in core are known, so I can look for those in apps easily. The main effort will "just" be going through the process of QA and release for new versions of quite a few apps (might be 10 or 15 to do).

**Review by pako81 — APPROVED** [review]

**Comment by phil-davis** [comment]
Merging - we will get nightly CI from all the apps overnight and can sort out which apps also need touching.

**Pull request merged**
