### PR TITLE
[stable9.1] Custom Authentication Mechanisms for WebDAV and APIs

### PR DESCRIPTION
**Pull request by joneug**
## Description

This is a backport of #26742 to `stable9`. It would be great to update sabre/dav to 3.2 (as in `master`), too, because it would simplify the implementation of Bearer Authentication.

## Related Issue

#10400

## Motivation and Context

This, for example, allows the implementation of Bearer Authentication with OAuth 2.0 (see [OAuth 2.0 app](https://github.com/owncloud/oauth2)).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
> It would be great to update sabre/dav to 3.2 

We don't update major library versions in minor releases, sorry. This is likely to cause a lot of breakage.

**Comment by PVince81** [comment]
@DeepDiver1975 can you restart the Jenkins job ? Not sure why this specific random failure is back

**Comment by joneug** [comment]
> We don't update major library versions in minor releases, sorry. This is likely to cause a lot of breakage.

I see.

> @DeepDiver1975 can you restart the Jenkins job ? Not sure why this specific random failure is back

That would be great.

**Comment by joneug** [comment]
@PVince81 Are we ready to merge?

**Comment by joneug** [comment]
Or is there something to change?

**Comment by PVince81** [comment]
@DeepDiver1975 @phisch please review

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
