### PR TITLE
remove slow fade animation for remaining tipsy tooltips

### PR DESCRIPTION
**Pull request by jancborchardt**
Follow-up to https://github.com/owncloud/core/pull/15626, found some more instances where the fading was used.

Please review @MorrisJobke @PVince81 @owncloud/designers

### CODE REVIEW

**Comment by nickvergessen** [comment]
@jancborchardt should I do that on the activity aswell? https://github.com/owncloud/activity/blob/master/js/script.js#L126

**Comment by jancborchardt** [comment]
@nickvergessen yep, thanks!

**Comment by karlitschek** [comment]
nice :+1:

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
