### PR TITLE
[tests-only] Update phpunit/phpunit (8.5.16 => 8.5.17)

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading phpunit/phpunit (8.5.16 => 8.5.17)
Writing lock file
```

https://github.com/sebastianbergmann/phpunit/releases/tag/8.5.17

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingExt1-latest-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30772/159/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiProxySmoke-8-3-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30772/172/1

**Comment by phil-davis** [comment]
Note: this PR is not important - no rush at all to merge.

**Review by dpakach — APPROVED** [review]
looks simple enough

**Comment by phil-davis** [comment]
i will wait to push the merge button - we just want to minimize any unnecessary "noise" in master, just in case someone needs to also change dependencies or... in `release-10.8.0` branch. I don't want to accidentally cause a conflict for merge-back of the release branch.

**Comment by phil-davis** [comment]
Other things have been merged to master. This patch version should not create any problems. Merging.

**Pull request merged**
