### PR TITLE
Revert "Deprecated \OCP\IAppConfig - add missing methods to IConfig"

### PR DESCRIPTION
**Pull request by PVince81**
This reverts commit 012016d3311a13c3c1e9d60778dc6fbd6be0204e.

@MorrisJobke seems the last test run was quite old and didn't match the new code.

We need to revert this to have tests pass on master

@icewind1991 @schiesbn

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
I will have a look at a fix on monday.

**Comment by PVince81** [comment]
@MorrisJobke thanks :smile:

**Pull request merged**
