### PR TITLE
[stable8] Check for file existence before doing a DAV copy

### PR DESCRIPTION
**Pull request by PVince81**
Partial backport of https://github.com/owncloud/core/pull/14505

For 8.1.3

Please review @icewind1991 @MorrisJobke @Xenopathic

### CODE REVIEW

**Comment by PVince81** [comment]
@davivel

**Comment by PVince81** [comment]
Test steps can be found here: https://github.com/owncloud/core/issues/14501

**Comment by Xenopathic** [comment]
:+1:

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
:+1:

**Comment by Nocxelp** [comment]
hello

 

Von: Robin Appelman [mailto:notifications@github.com] 
Gesendet: Montag, 31. August 2015 15:44
An: owncloud/core <core@noreply.github.com>
Betreff: Re: [core] [stable8] Check for file existence before doing a DAV copy (#18704)

 

  <https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png>

**Comment by davivel** [comment]
Tested in Android client, works for us to :+1:

**Comment by davivel** [comment]
> For 8.1.3

Is this right? Not for 8.0.x ?

**Pull request merged**
