### PR TITLE
Handle group shares of addressbooks on v1 as well ... now FINALLY ....

### LINKED ISSUE #23328: shared address book doesn't show through carddav
owncloud 9: If someone shares an address book with me, I can see the contacts from the address book online in the contacts app. However, through carddav the address book is not shown. If I do a:
```
$ curl -u myself --data @propfind3.xml -H 'Depth: 1' -H 'Content-Type: application/xml; charset-utf-8' -X PROPFIND https://www.example.com/owncloud/remote.php/carddav/addressbooks/myself/
```
with propfind3.xml containing:
```
<d:propfind xmlns:d="DAV:" xmlns:cs="http://calendarserver.org/ns/">
  <d:allprop/>
</d:propfind>
```
I only get this:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav">
 <d:response>
  <d:href>/owncloud/remote.php/carddav/addressbooks/myself/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/owncloud/remote.php/carddav/addressbooks/myself/contacts/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <card:addressbook/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```
which is my own collection and my own address book "contacts" but the shared one is missing.

The problem seems to be that getAddressBooksForUser is called with principal "principals/myself" from the getChildren in UserAddressBooks which only returns my own address books.

(Another call to getAddressBooksForUser from the hookmanager uses principal "principals/users/mysql" which does in fact return my own and the shared address book. So it seems an issue of the principal uri used.)

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@gvde mind testing? THX a lot!

commit has been added to backport https://github.com/owncloud/core/pull/23552

fixes #23328

### CODE REVIEW

**Comment by gvde** [comment]
Great. Looks good to me.

**Comment by DeepDiver1975** [comment]
@LukasReschke @MorrisJobke @PVince81 please review - THX

**Comment by MorrisJobke** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
