### PR TITLE
Merge back release-10.10.0

### PR DESCRIPTION
**Pull request by jnweiger**
Release done. Ready to merge back the branch. 
Hooray!

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliAppManagement-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/35770/121

**Comment by phil-davis** [comment]
> Huch, how can ownclouders sign a CLA?

It can't - stupid GitHub. I will fake that result.

**Comment by phil-davis** [comment]
> boom Acceptance tests pipeline **cliAppManagement-mariadb10.2-php7.4** failed. The build has been cancelled.
> 
> https://drone.owncloud.com/owncloud/core/35770/121

cliAppManagement no longer exists in `master` so that is a problem for this merge-back PR. Sadly, PR #40041 rearranged some test suites to optimize run-times, but it missed getting into the release-10.10.0 branch.

PR #40088 should fix the problem. It needs to be merged to `release-10.10.0`

**Comment by phil-davis** [comment]
Now it tells me there are conflicts!!! I am going to have to backport a bunch of other test changes - looking...

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
