### PR TITLE
Keep opacity in current item in newFileMenu

### PR DESCRIPTION
**Pull request by PVince81**
Whenever the input field appears, the menu item should keep its opacity
instead of reacting on hover.

Before:
newfilemenuhighlight-before

See how it looks disabled, you'd need to hover on it with the mouse to keep it enabled.

After:
newfilemenuhighlight-after

Please review @jancborchardt @DeepDiver1975 @karlitschek @rullzer @blizzz @schiesbn

### CODE REVIEW

**Comment by PVince81** [comment]
@MorrisJobke might like it too

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
And code looks good :)

**Comment by MorrisJobke** [comment]
cc @oparoz

**Comment by oparoz** [comment]
No CSS love for IE?

**Comment by PVince81** [comment]
@oparoz added https://github.com/owncloud/core/commit/def76bed2a9fbaa9a3440bfb7d1684cd9a6f9db0

**Comment by karlitschek** [comment]
good :+1:

**Comment by oparoz** [comment]
Approved :+1:

**Pull request merged**
