### PR TITLE
Show error if confirmation mail not send due to recent send

### PR DESCRIPTION
**Pull request by imujjwal96**

### CODE REVIEW

**Comment by PVince81** [comment]
Tested, works 👍 

Thanks a lot!

**Comment by pmaier1** [comment]
If you need to trial-and-error your mail server credentials the new handling is really annoying. To set the first mail address (admin) you need a mail server configured. To try the mail server you again need to have a mail address specified. As there's a delay after entering a mail address you have to wait between each retry and even if sending the mail does not work the delay applies. Maybe we can disable the delay for admins? Need to find some improved handling for this as it's really annoying. Tried with 10.0.0RC5 enterprise. 
mail_config

**Comment by PVince81** [comment]
Maybe we should let admins set an email without verification ?

Actually the workaround is for the admin to set their email directly in the users page which doesn't require any verification.

**Comment by pmaier1** [comment]
> Maybe we should let admins set an email without verification ?

Yes, I think this would make sense as an admin won't do spamming with the mail server he configured and verification mails are not necessary.

> Actually the workaround is for the admin to set their email directly in the users page which doesn't require any verification.

Good to know!

**Pull request merged**
