### PR TITLE
[stable9.1] add test for . in path with no extension, fix smb

### PR DESCRIPTION
**Pull request by butonic**
backport of https://github.com/owncloud/core/pull/26143
see https://github.com/owncloud/core/pull/25994#r77006659

### CODE REVIEW

**Comment by butonic** [comment]
cc @VicDeo @jvillafanez @PVince81

**Comment by PVince81** [comment]
Weird failure in DAV storage:
```
13:42:40 1) OCA\Files_External\Tests\Storage\WebdavTest::testWriteWithDotInPath
13:42:40 OCP\Files\StorageNotAvailableException: Sabre\HTTP\ClientHttpException: Conflict
13:42:40 
13:42:40 /var/lib/jenkins/workspace/owncloud-core/core/PR-26146/lib/private/Files/Storage/DAV.php:832
13:42:40 /var/lib/jenkins/workspace/owncloud-core/core/PR-26146/lib/private/Files/Storage/DAV.php:669
13:42:40 /var/lib/jenkins/workspace/owncloud-core/core/PR-26146/lib/private/Files/Storage/DAV.php:181
13:42:40 /var/lib/jenkins/workspace/owncloud-core/core/PR-26146/tests/lib/Files/Storage/Storage.php:155
```

strange that it didn't happen on master ?

**Comment by PVince81** [comment]
seems SFTP would fail too, run: `./autotest-external.sh sqlite sftp-atmoz`


```

1) OCA\Files_External\Tests\Storage\SftpTest::testWriteWithDotInPath
data returned from file_get_contents is not equal to the source data
Failed asserting that 'lorem ipsum dolor sit ...' matches expected false.

```

**Comment by DeepDiver1975** [comment]
lets get first the master pr merged and do the backport after making a decission

**Pull request closed without merging**
