### PR TITLE
Fix single file download

### LINKED ISSUE #19614: [Sharing by link] Text files are not downloaded right. Instead the file, a .rar with a folder is downloaded.
### Steps to reproduce

1. Create a text file
2. Click on share icon (sidebar is shown)
3. Share the file via link
4. Paste the link in another browser
5. Try to download the file

### Expected behaviour
A .txt should be download

### Actual behaviour
A .rar file is downloaded and it contains an empty folder named as the text file

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 RC1 (daily) Build:2015-10-07T03:08:55+00:00 648b86abdd3c6610716a418cd52d8e4186ae11b2

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox and Chrome

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #19614

@davitol @nickvergessen @PVince81 @jvillafanez please review and test

### CODE REVIEW

**Comment by PVince81** [comment]
I'm still hearing an echo "with 9.0 I want to finally see files.php die" :wink:

**Comment by PVince81** [comment]
Tested all known download combinations, they all work now :+1:

**Comment by DeepDiver1975** [comment]
> I'm still hearing an echo "with 9.0 I want to finally see files.php die" :wink:

:echo: :echo: :echo: :echo: :echo:

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
