### PR TITLE
[release-10.2.0] backport "add encryption version fix command"

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Add encryption version fix command (all the PRs commits that backported and "cleaned" code in the built-in core `stable10` `encryption` in the last few days) - this is a "new feature" so maybe or maybe not for 10.2

These used to be in this PR but are now in the 10.2 release branch:
2) Dependency bumps, specially for symfony to 3.4.24 => 25 => 26 - some CVEs there
3) Link to installation docs in README - easy fix (it was noticed when testing the 10.2 changelog)
4) Correcting of translation calls - seems useful to fix the translation calls so that people get more translations on the UI

## Motivation and Context
Keep track of things that can be reviewed for inclusion if/when there is a 10.2RC2 to be made

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by PVince81** [comment]
ah ok, already up to date but still so many commits

**Comment by PVince81** [comment]
are there any actual bug fixes in there ? @sharidas

**Comment by phil-davis** [comment]
The first 3 commits are the "real" ones to implement "Add encryption version fix command".
The others are refactoring that helped get the `stable10` `encryption` code to match the code the the separate `encryption` app repo.

So you could just take those first 3 commits.

**Comment by phil-davis** [comment]
I added `[stable10] Backport of Fixing encrypted version test ` commit from PR #35039 just now.
That was another recent change (to unit test only) related to this stuff. If we take this new command into 10.2 then it seems good to take the latest version of the unit tests for it.

**Comment by PVince81** [comment]
I rechecked and it seems we didn't merge the new encryption command, and considering that we already have a lot to test for 10.2 I'd prefer not to add it right now.

**Comment by phil-davis** [comment]
Yeh, that's fine. I put it here when I was accumulating stuff that might be wanted for a future RC, and it is now the only thing remaining in this "maybe" PR.

**Comment by PVince81** [comment]
yup. we already picked up what we needed, thanks.

I'll close this then.

**Pull request closed without merging**
