### PR TITLE
Properly hide strengthify after password change

### LINKED ISSUE #14142: Hide password strength after password change
* go to the personal page
* type in the old password and a new one (password strength appears)
* hit enter or the "Change password" button

### expected

strength meter hides

### actual

strength meter is still visible

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/14142

Please review @MorrisJobke @schiesbn @rullzer @jancborchardt

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Doesn't work here. Not in Firefox nor in Chromium.

**Comment by PVince81** [comment]
@MorrisJobke it only disappears after a **successful** password change, because that will clear the field. If the password is wrong, the field stays populated and the indicator stays.

**Comment by MorrisJobke** [comment]
> @MorrisJobke it only disappears after a successful password change, because that will clear the field. If the password is wrong, the field stays populated and the indicator stays.

It was always successful :(

**Comment by PVince81** [comment]
Indeed. Weird shit.

**Comment by PVince81** [comment]
of course, I forgot to commit the "change" event handler

**Comment by PVince81** [comment]
please try again

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@PVince81 Please create the backport for 8.2.1

**Comment by PVince81** [comment]
stable8.1: https://github.com/owncloud/core/pull/19768

**Pull request merged**
