### PR TITLE
Stable8.1 files cleanuppartfileonlyonce

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/17268 to stable8.1

Do not merge before 8.1.1.
Approved here https://github.com/owncloud/core/pull/17268#issuecomment-117636858

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Jenkins PR: https://github.com/owncloud/core/pull/17300

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
