### PR TITLE
3rdparty bump for assetic-1.3.1

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/205

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@rullzer 3rdparty is merged - please update and rebase - THX

**Comment by rullzer** [comment]
Rebases.

**Comment by MorrisJobke** [comment]
@cmonteroluque What is this new label "in progress" for? We could simply set this to "2 - Developing" which is the "in progress" state ;)

**Comment by DeepDiver1975** [comment]
> Rebased.

no - still a merge conflict

**Comment by rullzer** [comment]
@DeepDiver1975 yeah actually pushing the latest stuff helps :S

**Comment by DeepDiver1975** [comment]
tested - works :+1:

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/core/pull/19967#issuecomment-150145204 As mentioned on IRC, this is a waffle.io construct. Not ideal...

**Pull request merged**
