### PR TITLE
Sort behat.yml

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Sort the acceptance test ``behat.yml`` suites and contexts into alphabetical order, except that ``FeatureContext`` and ``apiMain`` get priority at the top.

## Motivation and Context
It is annoying to compare suites and contexts in other apps with what is in core.
Sort the list in core so it is easy to scan through it.

## How Has This Been Tested?
CI will know if I broke it.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by paurakhsharma — APPROVED** [review]

**Comment by phil-davis** [comment]
No codecov came :(

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
Backport ``stable10`` #32917

**Pull request merged**
