### PR TITLE
Run API acceptance tests on drone

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Implement API acceptance tests item in drone pipeline

## Motivation and Context
Progress moving stuff off Jenkins and onto drone.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Test refactoring

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
This is just the first commit from #30883 

If people are happy, we could merge this, and backport. Then as the next step, we reorganize the API acceptance ``apiMain`` suite into smaller pieces.

This means that issues with reorganizing the API acceptance suites can be dealt with cleanly and separately to the move to drone.

**Comment by phil-davis** [comment]
This PR just adds the scripts and jobs in drone to run API acceptance tests for each of the existing API acceptance test suites. It is the smallest change.

There are issues that are seen on Jenkins if I split the suites up more and rearrange them. This seems to be for some tests that check a public link with password download, and require federated sharing to be enabled. When I try running some "new" combinations of suite order, then those tests fail. I am looking at that now as a separate issue. It is an existing problem with the API acceptance tests, not one that is actually caused by drone.

**Comment by phil-davis** [comment]
So I am asking if people are willing to merge this PR. And I can look into the other issues separately.

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
@patrickjahns @SergioBertolinSG please give an opinion. I do not want to merge with just @individual-it approval in this case.

**Comment by phil-davis** [comment]
Backport ``stable10`` #30923

**Comment by SergioBertolinSG** [comment]
@phil-davis here I also see the problem with changing permissions when running the tests locally:

```
PHP_VERSION=7.1 DB_TYPE=mariadb USE_SERVER=true INSTALL_SERVER=true CHOWN_SERVER=true OWNCLOUD_LOG=true BEHAT_SUITE=apiWebdav TEST_SUITE=api drone exec --commit-branch master --build-event push
```

```
[fix-permissions:L1:4s] chown: changing ownership of '/drone/src/build/bin/bower': No such file or directory
[fix-permissions:L2:21s] chown: changing ownership of '/drone/src/core/vendor': No such file or directory
```

**Comment by phil-davis** [comment]
Superseded by #30927

**Pull request closed without merging**
