### PR TITLE
Added test. In some cases $result is null

### PR DESCRIPTION
**Pull request by LukasReschke**
Replaces https://github.com/owncloud/core/pull/7375 by adding also a check whether the value is empty

@MorrisJobke @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
ref #7373

**Comment by MorrisJobke** [comment]
@LukasReschke What is the state of this? 8.0 or 8.1?

**Comment by LukasReschke** [comment]
Well 8.1 I guess - this is just a remake of https://github.com/owncloud/core/pull/7375 and until now nothing exploded anyways so…

**Comment by LukasReschke** [comment]
Apparently not needed then…

**Pull request closed without merging**
