### PR TITLE
Remove unused win code

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Remove unused Windows code in core test infrastructure
## Motivation and Context
Cleanup stuff when I notice it

## How Has This Been Tested?
CI still runs

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
conflict ?!

**Comment by phil-davis** [comment]
yes, I removed other code from right next to this last night. That is how I happened to notice it.

**Comment by phil-davis** [comment]
I don't see how this "if" block will ever be used any more. Someone reviewing can confirm that they agree.

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
