### PR TITLE
[stable9] DAV now returns file name with Content-Disposition header

### PR DESCRIPTION
**Pull request by PVince81**
That was a tough backport of https://github.com/owncloud/core/pull/25043 to stable9 due to many conflicts.

Please review and test @owncloud/filesystem @DeepDiver1975 @nickvergessen @rullzer @guruz 

Sync client download, cadaver download and Chromium download worked properly.

### CODE REVIEW

**Comment by nickvergessen** [comment]
> That was a tough backport of #25043 to stable9 due to many conflicts.

still looks good  ;)

However, integration tests failed due to network issues:
> [Composer\Downloader\TransportException]                                                                             
The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Connection timed out  

since you touched them, I guess it would be nice to rebase (just to be sure)

**Comment by PVince81** [comment]
Rebased

**Comment by PVince81** [comment]
Rebased

**Comment by PVince81** [comment]
I just ran the webdav feature tests locally and they went fine.
```
25 scenarios (25 passed)
157 steps (157 passed)
```

Seems that the OCS int executor still has timeout troubles. CC @DeepDiver1975 

Still need two thumbs up to get this merged.

**Comment by PVince81** [comment]
To test:

1. Upload a file "test.jpg" to ownCloud
1. `curl -D - -X GET http://localhost/owncloud/remote.php/webdav/test.jpg`
1. Check the "Content-Disposition" header

Before: no filename part
After: filename part is there

Then for the Chrome bug, see https://github.com/owncloud/core/issues/23176
Basically upload a "test.xml" file and download it in the Chromium web UI. Chromium would save it as "test.txt" instead of "test.xml".

**Comment by nickvergessen** [comment]
works fine by me, but even before.
But nothing broke and the header is good, so :+1:

**Comment by rullzer** [comment]
Header is set here :+1:

**Pull request merged**
