### PR TITLE
Fix + button is not square anymore

### LINKED ISSUE #38945: [QA] Plus (+) button is no longer square
### Expected behaviour
In version 10.7 the plus button to upload things was sqare.

image

### Actual behaviour
The button looks like this in the upcoming version.

image

### Server configuration
**ownCloud version:** 
ownCloud 10.8 Beta2

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Due to faulty css, wrong style used to be applied to all icons (class icon)

## Related Issue

- Fixes #38945 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
@micbar needs to go with 10.8.0

**Comment by micbar** [comment]
can you use the release branch as a target?

**Review by phil-davis — APPROVED** [review]
WFM locally - upload button is square again.
I wonder what other UI elements will change a little?

**Comment by JanAckermann** [comment]
@micbar I tried, also rebased to 10.8.0 but still have too much commits then

**Pull request closed without merging**
