### PR TITLE
[8.1 backport] make sure that there is a space between user- and admin-documentation

### PR DESCRIPTION
**Pull request by schiessle**
selective backport from https://github.com/owncloud/core/pull/17807

cc @jancborchardt @nickvergessen @MorrisJobke

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by jancborchardt** [comment]
Just noticed – why is there a span around the a anyway? Not needed really. But :+1: for the backport.

**Comment by schiesbn** [comment]
@jancborchardt right. Do you want to open a pr for master so that we can fix it there?

**Comment by jancborchardt** [comment]
@schiesbn will do. Are both the ID and the class needed?

**Comment by schiesbn** [comment]
> will do. Are both the ID and the class needed?

I'm not sure. But as this are only simple links I would try it out. It can only impact the visual representation.

**Pull request merged**
