### PR TITLE
Keep redirect_url on failed auth

### LINKED ISSUE #28129: Login screen: entering the wrong password breaks the redirect
This bug was initially reported in https://github.com/owncloud/oauth2/issues/47 , but it's actually valid for every redirection.

### Steps to reproduce
1. Make sure that you are logged *out* of owncloud.
2. Go to some specific URL, such as https://<server_url>/index.php/settings/personal?section=apppasswords
3. On the login page, enter the wrong password. (can happen, everybody makes mistakes ☺) Observe that the `redirect_url` parameter in the URL disapear
4. On the second attempt, use the right password
5. Get redirected to the homepage instead of the page you were trying to reach

### Expected behaviour

After login, we should be redirected to the page we're trying to reach, even after a failed attempt.

### Actual behaviour

If we make a failed attempt, we go to the home instead. 

### Server configuration

**ownCloud version:** Tested with ownCloud 9.1.3 (stable)  and master branch.

### PR DESCRIPTION
**Pull request by butonic**
fixes https://github.com/owncloud/core/issues/28129

### CODE REVIEW

**Comment by phil-davis** [comment]
I was looking at a UI test for this, because we need to make the current UI login tests be able to handle landing on different pages after the login is done (currently they expect to land on the Files page). So this bug seemed an appropriate one to use as a test case.
There is a test at https://github.com/phil-davis/core/pull/13 which currently has @skip and fails when I run it. After making this source code change, the test passes.
I will work on making that UI test code production ready.

**Comment by PVince81** [comment]
@butonic please add unit test

**Comment by PVince81** [comment]
- [ ] add unit tests
- [ ] rebase
- [ ] unskip the UI test

**Review by DeepDiver1975 — APPROVED** [review]
tested - works

**Pull request merged**
