### PR TITLE
Include a sync limiter for LDAP

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Include a sync limiter and disable LDAP users automatically if the number of users is above the limit

## Related Issue
https://github.com/owncloud/enterprise/issues/3245

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

## TODO:
* [x] notification of disabled users
* [x] status / warning during `user:sync`
* [x] make "notification sent" key backend-agnostic
* [x] distinguish between no limit set for the backend and limit disabled for the backend
* [x] enabling user prevention in `user:enable` if applies (otherwise we might disable a different user in the next sync round)
* [x] handle migration scenario
* [x] unittests
* [ ] include "since" tag in the `OCP\IUserManager`
* [ ] (nice to have) enable auto_disabled users until fill the limit

### CODE REVIEW

**Comment by jvillafanez** [comment]
Known missing unittests:
* AccountMapper: tests are against only one fixture, not being reset after each test.
    * "getUserCountForBackendGroupByState" -> missing scenarios. It would require changing the DB, which might affect following tests
    * "ensureMaximumEnabledUsersForBackend" -> modifies the fixture. It would affect the rest of the tests
    * "enableAutoDisabledUsers" -> same as above.
* SyncBackend: no tests found
* Migrations: no tests found
* sync/syncnotification.js: to discuss. Code is relatively small and might not be worthy.

The rest of the cases should either be fully covered or can't be unittested.

**Comment by jvillafanez** [comment]
This is ready to review. The only additional thing left is to determine the "since" tag in the new method of the `OCP\IUserManager`, maybe 10.2.1?

**Comment by patrickjahns** [comment]
> This is ready to review. The only additional thing left is to determine the "since" tag in the new method of the OCP\IUserManager, maybe 10.2.1?

Checking https://semver.org/
> MINOR version when you add functionality in a backwards-compatible manner [..]

Meaning we can only introduce this with `10.3.0`

**Comment by jvillafanez** [comment]
Waiting for confirmation on https://github.com/owncloud/enterprise/issues/3245#issuecomment-492584968

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
