### PR TITLE
use the main search box to filter users in user management

### PR DESCRIPTION
**Pull request by icewind1991**
Before:

before

After:

after

cc @DeepDiver1975 @jancborchardt

### CODE REVIEW

**Comment by karlitschek** [comment]
very nice :+1:

**Comment by PVince81** [comment]
Tested, works :+1: 

@blizzz @jancborchardt @MorrisJobke please review

**Comment by jancborchardt** [comment]
Nice work! :+1: 

There was also an issue about this, no? I didn’t find it, but that can be closed.

**Comment by jancborchardt** [comment]
Fix https://github.com/owncloud/core/pull/18083

**Comment by jancborchardt** [comment]
Fix https://github.com/owncloud/core/issues/14973

**Pull request merged**
