### PR TITLE
Run API acceptance tests on drone

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
1) Implement API acceptance test suites in drone pipeline
2) Split the existing API acceptance tests in more suites, so each suite takes less time and the suites can be run in parallel drone jobs
3) Fix issue found when reorganizing suites - when testing a public upload or download with password, the test code accesses endpoints like ``public.php/download`` ... When Federated Cloud Sharing is enabled, this works as-is. But when Federated Cloud Sharing is disabled, then those tests were failing. This happened on Jenkins when running all the suites together, with the rearranged suites and feature files order. The fix is to use:
```
$options['headers']['X-Requested-With'] = 'XMLHttpRequest';
```
in those requests. The server responds to that differently than to an "ordinary" request that might come from a remote (federated) server.

## Related Issue
https://github.com/owncloud/QA/issues/517

## Motivation and Context
1) Move stuff off Jenkins
2) Make the elapsed time of tests less

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Test refactoring

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
This is the "all-singing-all-dancing" PR. It gets API acceptance tests running on drone, splits up the API acceptance tests suites in some "reasonable" way and fixes the latent bug that became evident on Jenkins after rearranging the suites.

The latent bug can be seen in ``core`` ``master`` locally by:
1) Install your system and have ``Allow users on this server to send shares to other servers `` off in Federated Cloud Sharing"
2) Run this test (1 of 12 that fail):
```
./run.sh features/apiMain/sharing-v1.feature:50
```
and see a result like:
```
Feature: sharing

  Background:                   # /home/phil/ownCloud/core/tests/acceptance/features/apiMain/sharing-v1.feature:3
    Given using API version "1" # FeatureContext::usingApiVersion()
    And using old DAV path      # FeatureContext::usingOldDavPath()

  Scenario: Creating a new public share with password                                        # /home/phil/ownCloud/core/tests/acceptance/features/apiMain/sharing-v1.feature:50
    Given user "user0" has been created                                                      # FeatureContext::adminCreatesUserUsingTheAPI()
    When user "user0" creates a share using the API with settings                            # FeatureContext::userCreatesAShareWithSettings()
      | path      | welcome.txt |
      | shareType | 3           |
      | password  | publicpw    |
    Then the OCS status code should be "100"                                                 # FeatureContext::theOCSStatusCodeShouldBe()
    And the HTTP status code should be "200"                                                 # FeatureContext::theHTTPStatusCodeShouldBe()
    And the last public shared file should be able to be downloaded with password "publicpw" # FeatureContext::checkLastPublicSharedFileWithPasswordDownload()
      Client error response [url] http://localhost:8080/public.php/webdav [status code] 401 [reason phrase] Unauthorized (GuzzleHttp\Exception\ClientException)

--- Failed scenarios:

    /home/phil/ownCloud/core/tests/acceptance/features/apiMain/sharing-v1.feature:50

1 scenario (1 failed)
7 steps (6 passed, 1 failed)
0m4.88s (22.80Mb)
```

**Comment by phil-davis** [comment]
Thanks to @PVince81 for the hint about setting the ``X-Requested-With`` header.

**Comment by phil-davis** [comment]
Backport ``stable10`` #30928

**Comment by patrickjahns** [comment]
@phil-davis 

there is double steps:

```
  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /drone/src/data/owncloud.log
    when:
      matrix:
        OWNCLOUD_LOG: true
``` 

and 

```
  print-log:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cat /drone/src/data/owncloud.log
    when:
      status:  [ failure ]
      matrix:
        TEST_SUITE: phpunit
```

One displays the logfile when there was a failure - the other one follows the log file.

Not sure if we need both? Maybe it makes more sense to show the logfile on any failure?

**Review by patrickjahns — APPROVED** [review]
Minor improvements with logging could be done (in a subsequent PR)

**Comment by phil-davis** [comment]
Both those logging things were added by different people in different PRs 1 and 2 months ago. So that is an existing issue for refactoring.

**Pull request merged**
