### PR TITLE
[stable6] Cleanup handling of temporary files

### PR DESCRIPTION
**Pull request by icewind1991**
Backport for #11709

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
Same tests seem to fail on stable6 (https://ci.owncloud.org/job/server-stable6-linux/lastCompletedBuild/testReport/) unrelated I guess?

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Broken stable6 :(

**Comment by DeepDiver1975** [comment]
@icewind1991 from my pov stable6 is failing because of we updated phpunit in the meanwhile.

Please take a look if we can update the code base in stable6 to make it work with phpunit 4.x.x - THX

@MorrisJobke FYI

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
