### PR TITLE
Catch exceptions in files ajax calls

### PR DESCRIPTION
**Pull request by PVince81**
Needed to be able to show the locking exceptions: https://github.com/owncloud/core/issues/16701
- [x] rename
- [x] move
- [x] new file
- [x] new folder
- [x] delete
- [x] upload

### CODE REVIEW

**Comment by karlitschek** [comment]
good catch :+1:

**Comment by PVince81** [comment]
Download is much more tricky because at the time where LockedException is thrown, the headers are already send (including content-disposition). This causes the browser to show a generic error page "invalid_response" instead of the actual error page returned by the server.

**Comment by DeepDiver1975** [comment]
> Download is much more tricky because at the time where LockedException is thrown, the headers are already send (including content-disposition). This causes the browser to show a generic error page "invalid_response" instead of the actual error page returned by the server.

can we delay sending of these headers? we also need to send back a proper http status code.

**Comment by PVince81** [comment]
I hope so. But from the current code structure it might be tricky... Because we get the exception from the readfile() call. One idea would be to try and explicitly get a shared lock on the file before sending the headers, to make sure we get the exception early.

**Comment by PVince81** [comment]
I'd like to investigate the download case separately.

If we get this merged, it will be easier for @jnfrmarks and @SergioBertolinSG to test the other file operations.

Please review @DeepDiver1975 @icewind1991

**Comment by DeepDiver1975** [comment]
@PVince81 let treat the remaining ops in a second pr

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
