### PR TITLE
Return correct user count when the group has none

### LINKED ISSUE #17260: "NaN" appears instead of the count of members of the group in the sidebar
### Steps to reproduce
1. Create new users in different groups

### Expected behaviour
The count of the member of a group should appear in the sidebar

### Actual behaviour
NaN is shown instead of the count of members of the group in the sidebar

### Server configuration
**Operating system**: centOS 6.6

**Web server:** Apache/2.2.15

**Database:** mysql

**PHP version:** 5.4.

**ownCloud version:**""7.0.7.0","versionstring":"7.0.7beta

**Updated from an older ownCloud or fresh install:** Fresh install
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

### PR DESCRIPTION
**Pull request by nickvergessen**
@PVince81 @davitol 

@DeepDiver1975 @karlitschek please rate if we should fix this on stable7

Fix #17260

### CODE REVIEW

**Comment by PVince81** [comment]
To make it clearer because I didn't notice at first: this PR is already against **stable7**.
Please confirm if this backport is acceptable.

**Comment by karlitschek** [comment]
Shouldn't hurt. Backport is fine with me :+1:

**Comment by MorrisJobke** [comment]
@nickvergessen Is this already fixed in stable8+?

**Comment by nickvergessen** [comment]
The problem does not happen in 8+ (maybe due to https://github.com/owncloud/core/issues/17420 but didn't investigate)

**Comment by MorrisJobke** [comment]
Tested, reproduced and it works with this PR :+1:

**Comment by MorrisJobke** [comment]
Code looks also good

**Comment by davitol** [comment]
:+1: The PR fixes #17260

**Pull request merged**
