### PR TITLE
UI test for PR #26979

### PR DESCRIPTION
**Pull request by individual-it**
## Description
This is an UI test for the PR #26979 that fixes the issue #26975

This also includes the complete setup of the selenium infrastructure that can be used as the basis of further UI tests. After the discussion in #27057 behat+mink is used instead of the facebook webdriver.

See also discussion in #27191

For this to work travis starts behat/mink tests. And they connect to selenium running on https://saucelabs.com

## Related Issue
PR #26979 
issue #26975

### List of PRs/issues that potentially would benefit of UI tests:
Can't set a user's quota back to Unlimited #26975
Fix long display names #27059
files_external: Keep checkbox and its label on one line #25120
Improve quota validation including a regexp which matches expected formats #25358 
Rows are not updated after sharing via web ui. #27294 https://github.com/nextcloud/server/issues/3688
Fixed disappearing of share info in file view #26534 https://github.com/nextcloud/server/pull/2010

## Motivation and Context

See issue  #27055 
Some bugs are hard to catch with karma & PHPUnit tests. Primarily this are front-end bugs. This PR implements end-to-end testing environment run on real browsers. Currently only Chrome browser is used, but it can be extended to multiple browsers/platforms including mobile browsers.
Currently my own sauce-labs account is used. Of course it would be good that a oC account would be used in future.

### run this tests locally
- download Selenium standalone server jar from http://docs.seleniumhq.org/download/
- download the chromedriver from: https://sites.google.com/a/chromium.org/chromedriver/ and place it in the same folder as the selenium server
- start selenium:` java -jar selenium-server-standalone-3.0.1.jar -port 4445`
- set the 3 environment variables: `SRV_HOST_NAME, SRV_HOST_URL and SRV_HOST_PORT` e.g.:
```
export SRV_HOST_NAME=localhost
export SRV_HOST_URL=owncloud-core
export SRV_HOST_PORT=80
```
- if no webserver is already running start php development server with: `bash tests/travis/start_php_dev_server.sh` (leave `SRV_HOST_URL` empty if you are using the php dev. server `export SRV_HOST_URL=""`)
it will bind to:` $SRV_HOST_NAME:$SRV_HOST_PORT`
- run tests: `bash tests/travis/start_behat_tests.sh`

### limitations
Only PRs from local branches are tested. PRs that come from a fork cannot be tested as they do not have access to the saucelabs username+key.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## How Has This Been Tested?

@individual-it joined travis with their own account on sauce labs and has run multiple tests. Created bugs and run tests again to see if they are failing.

## Screenshots (if appropriate):
**travis job:**
https://travis-ci.org/individual-it/owncloud-core/jobs/203733741
**saucelabs job:**
https://saucelabs.com/beta/tests/840fed2401854c50ab20109ac2812fb3/watch#305

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by SergioBertolinSG** [comment]
I've tested this locally and I am getting four failures:

    Examples:
      | start_quota | wished_quota |
      | Unlimited   | 5 GB         |
        Fatal error: Call to a member function click() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
      | Unlimited   | 1 GB         |
        Fatal error: Call to a member function click() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
      | 1 GB        | 5 GB         |
      | 5 GB        | Unlimited    |
        Fatal error: Call to a member function click() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
      | 1 GB        | Unlimited    |
        Fatal error: Call to a member function click() on null (Behat\Testwork\Call\Exception\FatalThrowableError)


Any idea why those tests are failing?

I thought it was because the size of the window, but maximizing it manually has not helped.

**Comment by DeepDiver1975** [comment]
> Any idea why those tests are failing?

no - can you try to get an understanding of this @SergioBertolinSG - THX

**Comment by SergioBertolinSG** [comment]
Ok, the problem was that my server was in spanish and this was looking for "Unlimited" instead of "Ilimitado". Works fine.

**Review by SergioBertolinSG — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
