### PR TITLE
add occ command to remove deleted files

### PR DESCRIPTION
**Pull request by schiessle**
occ tool to remove deleted files

```
$ ./occ help trashbin:clean
Usage:
 trashbin:cleanup [user_id1] ... [user_idN]

Arguments:
 user_id               remove deleted files of the given user(s), if no user is given all deleted files will be removed
```

part of https://github.com/owncloud/core/issues/9652

### CODE REVIEW

**Comment by karlitschek** [comment]
very nice! :+1:

**Comment by rullzer** [comment]
Looking good! And a simple tests seems to work. :+1: 

Would it be an idea to add a min age? I could imaging running this script in cron to delete all files that have been in the trash for more than a week or so.

**Comment by schiesbn** [comment]
> Would it be an idea to add a min age? I could imaging running this script in cron to delete all files that have been in the trash for more than a week or so.

Would be much more complicated (at the moment we just have to delete the root folder) and time consuming. Maybe for a next version of the script.

Btw. the normal expire method already knows a min age, so for your use case it would be probably better to provide a job for the normal expire algorithm.

**Comment by jospoortvliet** [comment]
@carlaschroder this does not seem to be documented on https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html should it be or am I looking in the wrong place?

**Comment by carlaschroder** [comment]
Hrm, seems to be missing @jospoortvliet. I blame society.

**Pull request merged**
