### PR TITLE
Fix JS reference error for personal password changing

### LINKED ISSUE #15328: user can't change login password
Tested with current master. 

Changing the user password in the personal settings fails. There is no error message and everything seems to work fine but the password wasn't changed.

Steps to reproduce
1. go to personal settings
2. change password by enter old and the new password
3. logout and try to login with the new password -> fails
4. login with the old password still works

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Fixes #15328 

cc @MorrisJobke @PVince81 @schiesbn @jancborchardt

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
unit-tests

**Comment by Xenopathic** [comment]
@DeepDiver1975 I have no idea how to create a unit test to test that. If you have any idea (or anyone else, cc @PVince81 ) go ahead and push directly here.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I have no idea how to create a unit test to test that. If you have any idea (or anyone else, cc @PVince81 ) go ahead and push directly here.

my comment was more on how we could have prefented to introduce a regression .... adding unit tests is out of scope since this code base is not testable.

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
