### PR TITLE
[stable9] Add transfer ownership integration tests (#26543)

### PR DESCRIPTION
**Pull request by PVince81**
Backport of new integration tests for transfer ownership https://github.com/owncloud/core/pull/26543 to stable9

@DeepDiver1975 @owncloud/qa

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] requires https://github.com/owncloud/core/pull/26623

**Comment by PVince81** [comment]
well... we might be lucky that the tests still passed...

**Comment by PVince81** [comment]
Uh oh... Jenkins reporting success despite error ?! @DeepDiver1975 

```
11:51:57 --- FeatureContext has missing steps. Define them with these snippets:
11:51:57 
11:51:57     /**
11:51:57      * @Given User :arg1 deletes folder :arg2
11:51:57      */
11:51:57     public function userDeletesFolder($arg1, $arg2)
11:51:57     {
11:51:57         throw new PendingException();
11:51:57     }
11:51:57 
```

also I think this PR will need https://github.com/owncloud/core/pull/26576 too

**Comment by DeepDiver1975** [comment]
> Uh oh... Jenkins reporting success despite error ?! @DeepDiver1975

will take care ...

**Comment by PVince81** [comment]
Run `./run.sh features/transfer-ownership.feature:97` on this branch, I see the exit code is still 0.
Maybe it's behat's fault. We might need to grep the test results for "undefined".

**Comment by PVince81** [comment]
- [ ] requires https://github.com/owncloud/core/pull/26576

**Comment by DeepDiver1975** [comment]
> Run ./run.sh features/transfer-ownership.feature:97 on this branch, I see the exit code is still 0.

1 here ...

**Comment by PVince81** [comment]
Still missing the `userDeletesFolder` method.

@SergioBertolinSG which PR needs backporting for that ?

**Comment by PVince81** [comment]
Rebased, should hopefully fix the tests

**Comment by PVince81** [comment]
So, the tests worked, can we merge this ?

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
