### PR TITLE
Make sure to hide empty content message when mask is shown

### LINKED ISSUE #17393: Emptycontent message often visible below loading spinner when switching categories
When refreshing the page or in a new browser session, the emptycontent is often shown below the loading spinner for the categories of the files sidebar.

Now seeing »No files shared with you« or »No favorites yet« when you know there are some makes you really worry. They appear after the loading, but this is really not clean. The emptycontent should not show while the loading is going on.

cc @owncloud/designers @PVince81

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/17393
Not sure about the randomness of the original issue... but this fixes it in all cases.

Please review @jancborchardt @MorrisJobke @blizzz

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by MorrisJobke** [comment]
Tested, reproduced and works. :+1:

**Comment by jancborchardt** [comment]
Yep, nice fix! :) :+1:

**Comment by MorrisJobke** [comment]
@karlitschek The backport of this was requested in the original issue. @jancborchardt To which version should it be backported?

**Comment by jancborchardt** [comment]
stable8.1 for sure

**Comment by PVince81** [comment]
Backport PR: https://github.com/owncloud/core/pull/18266

**Pull request merged**
