### PR TITLE
throw ServerUnavailable exception with unexpected SMB errors

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
throw StorageNotAvailableException in case of unexpected errors in the public methods of the connector

## Related Issue

No public issue reported

## Motivation and Context
Unexpected errors might cause the storage to misbehave, for example getting empty results when accessing to a folder although it's in fact unable to connect or return a proper response.

## How Has This Been Tested?
**UNTESTED** for the moment

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

@butonic @PVince81

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
Makes sense, not sure about potential side effects though. 👍

**Comment by patrickjahns** [comment]
@jvillafanez 
Can you provide further instructions how this can / should be tested? 
What steps would need to be taken to automate the testing for this

**Comment by jvillafanez** [comment]
I can't provide much information. I guess QA should have error cases such as connection to a server temporary down, writing to read-only shares, and so on. These cases should behave the same with and without the patch (if not it should be reported to check if the current is better or not).

For the specific issue, it seems it's an overloaded network which has temporary connection problems to the SMB server, or somehow the SMB server is busy and can't respond. The libsmbclient-php reports an unknown error 16 which seems to match a "resource or device busy", but I don't really know the exact details not how to reproduce the error.

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by jvillafanez** [comment]
Can someone recheck what happened with the failure in jenkins? I can't say for sure if it's a temporary error or there is in fact something that I need to change.

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
fix the codecov issues by mocking the SMB library ? we didn't do this before but we have the unit tests running against a true SMB server. With a true server we likely will not be able to cover the paths so need a mock.

**Comment by jvillafanez** [comment]
We'd likely have to schedule time to do it.

We'll need to refactor the class in order to mock the dependencies. 
In addition, we'll need to check anything that the library could throw; the problem here is that we'll end up testing what we *think* it might throw, but not what it could throw, I mean, we might think the library throws an error code 14 in an scenario, but it reality either it throws an error code 55 or it might not throw anything and swallow the error. I think this already happened with SMB1 vs SMB2 protocol.

**Comment by PVince81** [comment]
ok so with the real server we cannot trigger the exception code paths easily

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
@jvillafanez PHP CS Fixer needs your attention

**Comment by jvillafanez** [comment]
Rebased to fix it.

**Comment by felixboehm** [comment]
@jvillafanez please provide tests and info on expected behavior for error handling

**Comment by PVince81** [comment]
deferred. need to schedule some time to finish this / provide clearer test steps

**Comment by jvillafanez** [comment]
rebased

**Comment by pako81** [comment]
can we push this forward?

**Comment by PVince81** [comment]
test info was provided on the original ticket

**Comment by PVince81** [comment]
let's merge this, testing can happen latest when testing changelog

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
php-cs-fixer not happy @jvillafanez

**Comment by PVince81** [comment]
ugh, what
```
  [Behat\Testwork\Suite\Exception\SuiteNotFoundException]              
  `apiWebdav` suite is not found or has not been properly registered.  
```

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@PVince81 in QA we love to split and rename acceptance test suites, just to give you all the chance to practice rebasing ;)

**Comment by PVince81** [comment]
not unit testable

well, sometimes I wonder if we should mock the library...

**Comment by PVince81** [comment]
@jvillafanez please backport

**Comment by jvillafanez** [comment]
Backport in https://github.com/owncloud/core/pull/32416

**Pull request merged**
