### PR TITLE
Do not create a new job when federation failed to connect but use existing job

### LINKED ISSUE #22887: non-ending background job
### Steps to reproduce
1. Play around with sharing (federated sharing)
2. Remove all shared folders (from others), remove all shared folders (to others)
3. background job of a different setup is running crazy

### Expected behaviour
Just delete the shares.

### Actual behaviour
Heavy connection activity to other server (via cronjob).

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7.0.4 mod_php (dotdeb)

**ownCloud version:** 9.0.0 RC 2

**Updated from an older ownCloud or fresh install:** good question, I'm not sure

**Where did you install ownCloud from:** manual install from zip

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```
**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### oc_jobs
````
OCA\Files\BackgroundJob\ScanFiles 
OCA\Files_Trashbin\BackgroundJob\ExpireTrash 
OCA\Files_sharing\Lib\DeleteOrphanedSharesJob 	
OCA\Files_sharing\ExpireSharesJob
OCA\Federation\SyncJob 	 	
OCA\Files\BackgroundJob\DeleteOrphanedItems
OCA\DAV\CardDAV\SyncJob
OCA\Files\BackgroundJob\CleanupFileLocks 
OC\BackgroundJob\Legacy\RegularJob
OC\BackgroundJob\Legacy\RegularJob
````

#### ownCloud log (data/owncloud.log)
```
{"reqId":"U2XI+wm\/+8BOUpJREs2m","remoteAddr":"","app":"federation","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ClientException\",\"Message\":\"Client error response [url] https:\\\/\\\/my-ip\\\/owncloud\\\/ocs\\\/v2.php\\\/apps\\\/federation\\\/api\\\/v1\\\/request-shared-secret?format=json [status code] 404 [reason phrase] Not Found\",\"Code\":404,\"Trace\":\"#0 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(32): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Message\\\\Response))\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(109): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete(Object(GuzzleHttp\\\\Event\\\\CompleteEvent), 'complete')\\n#2 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit('complete', Object(GuzzleHttp\\\\Event\\\\CompleteEvent))\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#4 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#5 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#6 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#7 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#8 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#9 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(150): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#10 \\\/var\\\/www\\\/oc9\\\/lib\\\/private\\\/http\\\/client\\\/client.php(191): GuzzleHttp\\\\Client->post('https:\\\/\\\/data.as...', Array)\\n#11 \\\/var\\\/www\\\/oc9\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(144): OC\\\\Http\\\\Client\\\\Client->post('https:\\\/\\\/data.as...', Array)\\n#12 \\\/var\\\/www\\\/oc9\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->run(Array)\\n#13 \\\/var\\\/www\\\/oc9\\\/lib\\\/private\\\/backgroundjob\\\/queuedjob.php(42): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#14 \\\/var\\\/www\\\/oc9\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(125): OC\\\\BackgroundJob\\\\QueuedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#15 \\\/var\\\/www\\\/oc9\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(116): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->parentExecute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#16 \\\/var\\\/www\\\/oc9\\\/cron.php(141): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89}","level":3,"time":"2016-03-05T21:13:26+00:00","method":"--","url":"--"}
{"reqId":"U2XI+wm\/+8BOUpJREs2m","remoteAddr":"","app":"cron","message":"Finished job with ID 8478","level":0,"time":"2016-03-05T21:13:26+00:00","method":"--","url":"--"}
{"reqId":"U2XI+wm\/+8BOUpJREs2m","remoteAddr":"","app":"cron","message":"Run job with ID 8479","level":0,"time":"2016-03-05T21:13:26+00:00","method":"--","url":"--"}
{"reqId":"U2XI+wm\/+8BOUpJREs2m","remoteAddr":"","app":"federation","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ClientException\",\"Message\":\"Client error response [url] https:\\\/\\\/my-ip\\\/owncloud\\\/ocs\\\/v2.php\\\/apps\\\/federation\\\/api\\\/v1\\\/request-shared-secret?format=json [status code] 404 [reason phrase] Not Found\",\"Code\":404,\"Trace\":\"#0 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Subscriber\\\/HttpError.php(32): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Message\\\\Response))\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Event\\\/Emitter.php(109): GuzzleHttp\\\\Subscriber\\\\HttpError->onComplete(Object(GuzzleHttp\\\\Event\\\\CompleteEvent), 'complete')\\n#2 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(91): GuzzleHttp\\\\Event\\\\Emitter->emit('complete', Object(GuzzleHttp\\\\Event\\\\CompleteEvent))\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#4 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#5 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#6 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#7 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#8 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#9 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(150): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#10 \\\/var\\\/www\\\/oc9\\\/lib\\\/private\\\/http\\\/client\\\/client.php(191): GuzzleHttp\\\\Client->post('https:\\\/\\\/data.as...', Array)\\n#11 \\\/var\\\/www\\\/oc9\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(144): OC\\\\Http\\\\Client\\\\Client->post('https:\\\/\\\/data.as...', Array)\\n#12 \\\/var\\\/www\\\/oc9\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->run(Array)\\n#13 \\\/var\\\/www\\\/oc9\\\/lib\\\/private\\\/backgroundjob\\\/queuedjob.php(42): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#14 \\\/var\\\/www\\\/oc9\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(125): OC\\\\BackgroundJob\\\\QueuedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#15 \\\/var\\\/www\\\/oc9\\\/apps\\\/federation\\\/backgroundjob\\\/requestsharedsecret.php(116): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->parentExecute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#16 \\\/var\\\/www\\\/oc9\\\/cron.php(141): OCA\\\\Federation\\\\BackgroundJob\\\\RequestSharedSecret->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":89}","level":3,"time":"2016-03-05T21:13:26+00:00","method":"--","url":"--"}
{"reqId":"U2XI+wm\/+8BOUpJREs2m","remoteAddr":"","app":"cron","message":"Finished job with ID 8479","level":0,"time":"2016-03-05T21:13:26+00:00","method":"--","url":"--"}
{"reqId":"U2XI+wm\/+8BOUpJREs2m","remoteAddr":"","app":"cron","message":"Run job with ID 8480","level":0,"time":"2016-03-05T21:13:26+00:00","method":"--","url":"--"}
```
These messages are repeated over and over again. On the second server which is queried, I got corresponding 404-errors in the logfile.

### PR DESCRIPTION
**Pull request by nickvergessen**
@schiesbn can you have a look? Also see the explanation in https://github.com/owncloud/core/issues/22887#issuecomment-198322444

Fix #22887 

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by nickvergessen** [comment]
Setting sev1 as this can kill cron/server, @PVince81 please rate.

**Comment by PVince81** [comment]
Ok for critical. I guess there is no workaround ?

**Comment by schiesbn** [comment]
Did you checked what return code we get if the server is temporarily not available or in maintenance mode? In this case we should re-try it.

**Comment by nickvergessen** [comment]
Maintenance mode is 503

**Comment by schiesbn** [comment]
Please also update the unit test here: https://github.com/owncloud/core/blob/master/apps/federation/tests/backgroundjob/requestsharedsecrettest.php#L145

**Comment by nickvergessen** [comment]
@karlitschek backport request, to fix problem with inifinite running background jobs

**Comment by schiesbn** [comment]
tested successfully and code looks good :+1:

**Comment by karlitschek** [comment]
yes. please backport

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by PVince81** [comment]
Failed pgsql test unrelated:
```
OCA\Files_sharing\Tests\EtagPropagation::testOwnerWritesToSingleFileShare
Failed asserting that the etag for "" of user test-share-user2 has changed
Failed asserting that 'b1472b1ce674c7e8d901038ae4483e5e' is not equal to <string:b1472b1ce674c7e8d901038ae4483e5e>.

/ssd/jenkins/workspace/core-ci-linux@6/database/pgsql/label/SLAVE/apps/files_sharing/tests/propagationtestcase.php:63
/ssd/jenkins/workspace/core-ci-linux@6/database/pgsql/label/SLAVE/apps/files_sharing/tests/etagpropagation.php:131
```

(classic)

**Pull request merged**
