### PR TITLE
Chunk the users correctly in the trashbin and versions background job

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 @schiesbn @VicDeo @MorrisJobke 

Should help with https://github.com/owncloud/enterprise/issues/1279 although we are not entirely sure it fixes all of the issues

### CODE REVIEW

**Comment by PVince81** [comment]
Tested with few LDAP users, trashbin + version expiration jobs are still executed and removed properly :+1:

**Comment by PVince81** [comment]
@blizzz @MorrisJobke second review ?

@karlitschek backport to 9.0 ?

**Comment by schiesbn** [comment]
code looks good :+1:

**Comment by karlitschek** [comment]
backport makes sense 👍

**Pull request merged**
