### PR TITLE
Fix code that never worked

### PR DESCRIPTION
**Pull request by LukasReschke**
Introduced with https://github.com/owncloud/core/commit/1df8a5a774ae5d665849daf74540d967826d5e11 in February 2013…

@DeepDiver1975 @icewind1991 THX.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
what_meme

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by LukasReschke** [comment]
```
07:46:59 1) Test\Files\Cache\Wrapper\CacheJail::testMove
07:46:59 Failed asserting that two strings are equal.
07:46:59 --- Expected
07:46:59 +++ Actual
07:46:59 @@ @@
07:46:59 -'dc761cbf774573c685167a9f2aa82df6'
07:46:59 +'308b6040d33824f37124cf3ef584e8c3'
07:46:59 
07:46:59 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/files/cache/cache.php:388
07:46:59 
07:46:59 2) Test_Files_Sharing_Api::testSharePermissions
07:46:59 Failed asserting that true is false.
07:46:59 
07:46:59 /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/files_sharing/tests/api.php:247
07:46:59 
07:46:59 --
```

Looks unrelated but also happens on SQLite see https://github.com/owncloud/core/issues/14449?

**Comment by Xenopathic** [comment]
:+1:

**Pull request merged**
