### PR TITLE
handle connection errors as storage not available in smb

### LINKED ISSUE #22826: 500 error instead of 503 when SMB not available
### Steps

1. Go to admin page
1. Setup a SMB mount with custom credentials as "/smb". (make sure there are already files in there)
1. PROPFIND on "/smb" => see non-empty contents
1. Shut down the SMB server. This should result in "connection refused" internally.
1. PROPFIND on "/smb" again
1. Restart SMB server
1. PROPFIND on "/smb" again

### Expected result

- Should receive a 503 Storage Not Available response on the PROPFIND while the SMB server is down. The entry in oc_storages must have "available" set to 0.
- On the last PROPFIND after restarting the server, the results should appear again.

### Actual result

- The entry in oc_storages must have "available" is still set to 1.
- PROPFIND returns a 500 error "Connection refused"

### Versions
Observed on stable9 and master

We should adapt the SMB storage implementation to properly throw StorageNotAvailableException in all code paths. Note that relevant exceptions like "not found" or "forbidden" should NOT get converted.

Would it make sense to have a storage wrapper that is able to catch all kinds of exceptions and translate them to StorageNotAvailableException ? 

@icewind1991 @Xenopathic

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #22826

backport to stable9? (@karlitschek)

cc @Xenopathic @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by Xenopathic** [comment]
:+1:

But we should really have a generic mechanism for converting exceptions, like the DAV class does with `convertException()`, built directly into the filesystem layer.

**Comment by karlitschek** [comment]
makes sense. please backport

**Comment by icewind1991** [comment]
stable9: https://github.com/owncloud/core/pull/23308

**Pull request merged**
