### PR TITLE
Properly catch guzzle 503 when querying share info

### LINKED ISSUE #15430: propfind on webdav root results in a http 500 internal error when fc share is unavailable
### Steps to reproduce
1. Do a PROPFIND on the webDAV root - something like "http://server/owncloud/remote.php/webdav/"
    Also checked with `curl -u <username>:<password> -X PROPFIND -H "Content-Type: text/xml" -d "<?xml version='1.0' encoding='utf-8' ?><D:propfind xmlns:D='DAV:'><D:allprop/></D:propfind>" <owncloud-server-url>/remote.php/webdav/`

### Expected behaviour
Valid webdav response

### Actual behaviour
Internal error

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log)
```
{"reqId":"06cce899959355c34f6a11854494fde7","remoteAddr":"10.40.30.21","app":"remote","message":"The passed data is not valid XML","level":4,"time":"2015-04-07T09:02:42+00:00"}
{"reqId":"dfa929d07bd6993351e2fc8230411a16","remoteAddr":"10.40.10.254","app":"remote","message":"The passed data is not valid XML","level":4,"time":"2015-04-07T09:10:10+00:00"}
```

#### PROPFIND response
```
<!DOCTYPE html>
<!--[if lt IE 7]><html class="ng-csp ie ie6 lte9 lte8 lte7" data-placeholder-focus="false" lang="en"><![endif]-->
<!--[if IE 7]><html class="ng-csp ie ie7 lte9 lte8 lte7" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if gt IE 9]><html class="ng-csp ie" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if !IE]><!--><html class="ng-csp" data-placeholder-focus="false" lang="en" ><!--<![endif]-->

	<head data-requesttoken="">
		<title>
		ownCloud		</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=543672169">
		<link rel="shortcut icon" type="image/png" href="/core/img/favicon.png" />
		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png" />
					<link rel="stylesheet" href="/core/css/styles.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/header.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/mobile.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/icons.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/fonts.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/apps.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/fixes.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/multiselect.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/jquery-tipsy.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/share.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/styles.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
					<link rel="stylesheet" href="/core/css/header.css?v=80fedb79ee9a6aa51604bbf8ccf137e8" type="text/css" media="screen" />
							<script type="text/javascript" src="/core/vendor/jquery/jquery.min.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/jquery/jquery-migrate.min.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/underscore/underscore.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/moment/min/moment-with-locales.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/handlebars/handlebars.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/placeholders.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/jquery-tipsy.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/compatibility.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/jquery.ocdialog.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/oc-dialogs.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/js.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/l10n.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/octemplate.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/eventsource.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/config.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/search/js/search.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/oc-requesttoken.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/apps.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/snapjs/dist/latest/snap.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/placeholder.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/vendor/blueimp-md5/js/md5.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/jquery.avatar.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/avatar.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/backgroundjobs.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/core/js/share.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/apps/files_sharing/js/share.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/apps/files_sharing/js/external.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					<script type="text/javascript" src="/apps/files_versions/js/versions.js?v=80fedb79ee9a6aa51604bbf8ccf137e8"></script>
					</head>
	<body id="body-login">
		<noscript><div id="nojavascript"><div>This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank">enable JavaScript</a> and reload the page.</div></div></noscript>
		<div class="wrapper"><!-- for sticky footer -->
			<div class="v-align"><!-- vertically centred box -->
									<header>
						<div id="header">
							<div class="logo svg">
								<h1 class="hidden-visually">
									ownCloud								</h1>
							</div>
							<div id="logo-claim" style="display:none;"></div>
						</div>
					</header>
								<span class="error error-wide">
	<h2><strong>Internal Server Error</strong></h2>
		<p>The server encountered an internal error and was unable to complete your request.</p>
		<p>Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.</p>
		<p>More details can be found in the server log.</p>
	<br />

	<h2><strong>Technical details</strong></h2>
	<ul>
		<li>Remote Address: 10.40.30.21</li>
		<li>Request ID: 06cce899959355c34f6a11854494fde7</li>
					<li>Code: 0</li>
			<li>Message: The passed data is not valid XML</li>
			<li>File: /home/jvillafanez/src/owncloud/owncloud2/3rdparty/sabre/dav/lib/Sabre/DAV/Client.php</li>
			<li>Line: 542</li>
			</ul>

			<br />
		<h2><strong>Trace</strong></h2>
		<pre>#0 /home/jvillafanez/src/owncloud/owncloud2/3rdparty/sabre/dav/lib/Sabre/DAV/Client.php(181): Sabre\DAV\Client-&gt;parseMultiStatus(&#039;&lt;!DOCTYPE html&gt;...&#039;)
#1 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/storage/dav.php(550): Sabre\DAV\Client-&gt;propFind(&#039;&#039;, Array)
#2 /home/jvillafanez/src/owncloud/owncloud2/apps/files_sharing/lib/external/storage.php(144): OC\Files\Storage\DAV-&gt;hasUpdated(&#039;&#039;, 1424774464)
#3 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/storage/wrapper/wrapper.php(357): OCA\Files_Sharing\External\Storage-&gt;hasUpdated(&#039;&#039;, 1424774464)
#4 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/cache/watcher.php(67): OC\Files\Storage\Wrapper\Wrapper-&gt;hasUpdated(&#039;&#039;, 1424774464)
#5 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/view.php(976): OC\Files\Cache\Watcher-&gt;checkUpdate(&#039;&#039;, Array)
#6 /home/jvillafanez/src/owncloud/owncloud2/lib/private/files/filesystem.php(793): OC\Files\View-&gt;getFileInfo(&#039;/pics&#039;, false)
#7 /home/jvillafanez/src/owncloud/owncloud2/lib/private/helper.php(923): OC\Files\Filesystem::getFileInfo(&#039;/pics&#039;, false)
#8 /home/jvillafanez/src/owncloud/owncloud2/lib/private/connector/sabre/directory.php(235): OC_Helper::getStorageInfo(&#039;/pics&#039;)
#9 /home/jvillafanez/src/owncloud/owncloud2/lib/private/connector/sabre/server.php(247): OC_Connector_Sabre_Directory-&gt;getQuotaInfo()
#10 /home/jvillafanez/src/owncloud/owncloud2/lib/private/connector/sabre/server.php(104): OC_Connector_Sabre_Server-&gt;getPropertiesForPath(&#039;&#039;, Array, 1)
#11 [internal function]: OC_Connector_Sabre_Server-&gt;httpPropfind(&#039;&#039;)
#12 /home/jvillafanez/src/owncloud/owncloud2/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;&#039;)
#13 /home/jvillafanez/src/owncloud/owncloud2/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;PROPFIND&#039;, &#039;&#039;)
#14 /home/jvillafanez/src/owncloud/owncloud2/apps/files/appinfo/remote.php(61): Sabre\DAV\Server-&gt;exec()
#15 /home/jvillafanez/src/owncloud/owncloud2/remote.php(54): require_once(&#039;/home/jvillafan...&#039;)
#16 {main}</pre>
	</span>
				<div class="push"></div><!-- for sticky footer -->
			</div>
		</div>

		<footer>
			<p class="info">
				<a href="https://owncloud.org" target="_blank">ownCloud</a> – web services under your control			</p>
		</footer>
	</body>
</html>

```

### Notes
This bug is preventing the correct functions of mobile apps, and probably the desktop apps

### PR DESCRIPTION
**Pull request by PVince81**
@icewind1991 @LukasReschke 

Fixes https://github.com/owncloud/core/issues/15430

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1: makes sense

**Comment by MorrisJobke** [comment]
I still get the following:

bildschirmfoto von 2015-04-09 19-20-33

**Comment by PVince81** [comment]
That's the hard part about exceptions: they can happen in many different code paths. Not sure how you managed to trigger that specific code part. Looks like yet another issue.
I'll try and fix it too.

**Comment by PVince81** [comment]
Wait, this is a screenshot of a web page ? You were supposed to test PROPFIND :wink:

**Comment by PVince81** [comment]
@MorrisJobke did you update the submodule ?

The Sabre exception is supposed to be ClientHttpException in 2.1, not ClientException.

**Comment by MorrisJobke** [comment]
@PVince81 I got HTML back in the curl -> I then let it render as HTML or do you want the plain HTML:

Here you go (If you like that more ;))

```
$ curl -u mjob:mjob -X PROPFIND http://localhost/master/remote.php/webdav                                                                                      1 ↵
<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Call to undefined method Sabre\HTTP\ClientException::getHttpStatus() in /home/mjob/Projekte/owncloud/master/lib/private/files/storage/dav.php on line <i>753</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>228872</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/mjob/Projekte/owncloud/master/remote.php' bgcolor='#eeeeec'>.../remote.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0156</td><td bgcolor='#eeeeec' align='right'>1763200</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/home/mjob/Projekte/owncloud/master/apps/files/appinfo/remote.php'</font> )</td><td title='/home/mjob/Projekte/owncloud/master/remote.php' bgcolor='#eeeeec'>.../remote.php<b>:</b>84</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0177</td><td bgcolor='#eeeeec' align='right'>2008296</td><td bgcolor='#eeeeec'>Sabre\DAV\Server->exec(  )</td><td title='/home/mjob/Projekte/owncloud/master/apps/files/appinfo/remote.php' bgcolor='#eeeeec'>.../remote.php<b>:</b>80</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0177</td><td bgcolor='#eeeeec' align='right'>2008648</td><td bgcolor='#eeeeec'>Sabre\DAV\Server->invokeMethod(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/dav/lib/DAV/Server.php' bgcolor='#eeeeec'>.../Server.php<b>:</b>254</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.1148</td><td bgcolor='#eeeeec' align='right'>2834680</td><td bgcolor='#eeeeec'>Sabre\Event\EventEmitter->emit(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/dav/lib/DAV/Server.php' bgcolor='#eeeeec'>.../Server.php<b>:</b>469</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.1148</td><td bgcolor='#eeeeec' align='right'>2834776</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/home/mjob/Projekte/owncloud/master/3rdparty/sabre/event/lib/EventEmitterTrait.php:105}' target='_new'>call_user_func_array:{/home/mjob/Projekte/owncloud/master/3rdparty/sabre/event/lib/EventEmitterTrait.php:105}</a>
(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/event/lib/EventEmitterTrait.php' bgcolor='#eeeeec'>.../EventEmitterTrait.php<b>:</b>105</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.1148</td><td bgcolor='#eeeeec' align='right'>2835496</td><td bgcolor='#eeeeec'>Sabre\DAV\CorePlugin->httpPropfind(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/event/lib/EventEmitterTrait.php' bgcolor='#eeeeec'>.../EventEmitterTrait.php<b>:</b>105</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.1148</td><td bgcolor='#eeeeec' align='right'>2844376</td><td bgcolor='#eeeeec'>Sabre\DAV\Server->getPropertiesForPath(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/dav/lib/DAV/CorePlugin.php' bgcolor='#eeeeec'>.../CorePlugin.php<b>:</b>327</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.1181</td><td bgcolor='#eeeeec' align='right'>2931696</td><td bgcolor='#eeeeec'>Sabre\DAV\Server->getPropertiesByNode(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/dav/lib/DAV/Server.php' bgcolor='#eeeeec'>.../Server.php<b>:</b>936</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.1181</td><td bgcolor='#eeeeec' align='right'>2932136</td><td bgcolor='#eeeeec'>Sabre\Event\EventEmitter->emit(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/dav/lib/DAV/Server.php' bgcolor='#eeeeec'>.../Server.php<b>:</b>1016</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.1207</td><td bgcolor='#eeeeec' align='right'>2979368</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/home/mjob/Projekte/owncloud/master/3rdparty/sabre/event/lib/EventEmitterTrait.php:105}' target='_new'>call_user_func_array:{/home/mjob/Projekte/owncloud/master/3rdparty/sabre/event/lib/EventEmitterTrait.php:105}</a>
(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/event/lib/EventEmitterTrait.php' bgcolor='#eeeeec'>.../EventEmitterTrait.php<b>:</b>105</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.1207</td><td bgcolor='#eeeeec' align='right'>2979792</td><td bgcolor='#eeeeec'>Sabre\DAV\PropertyStorage\Plugin->propFind(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/event/lib/EventEmitterTrait.php' bgcolor='#eeeeec'>.../EventEmitterTrait.php<b>:</b>105</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>0.1207</td><td bgcolor='#eeeeec' align='right'>2979792</td><td bgcolor='#eeeeec'>OC\Connector\Sabre\CustomPropertiesBackend->propFind(  )</td><td title='/home/mjob/Projekte/owncloud/master/3rdparty/sabre/dav/lib/DAV/PropertyStorage/Plugin.php' bgcolor='#eeeeec'>.../Plugin.php<b>:</b>86</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>0.1207</td><td bgcolor='#eeeeec' align='right'>2979792</td><td bgcolor='#eeeeec'>OC\Connector\Sabre\ObjectTree->getNodeForPath(  )</td><td title='/home/mjob/Projekte/owncloud/master/lib/private/connector/sabre/custompropertiesbackend.php' bgcolor='#eeeeec'>.../custompropertiesbackend.php<b>:</b>99</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>0.1207</td><td bgcolor='#eeeeec' align='right'>2979872</td><td bgcolor='#eeeeec'>OC\Files\View->getFileInfo(  )</td><td title='/home/mjob/Projekte/owncloud/master/lib/private/connector/sabre/objecttree.php' bgcolor='#eeeeec'>.../objecttree.php<b>:</b>140</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>16</td><td bgcolor='#eeeeec' align='center'>0.1212</td><td bgcolor='#eeeeec' align='right'>2994656</td><td bgcolor='#eeeeec'>OC\Files\Cache\Watcher->checkUpdate(  )</td><td title='/home/mjob/Projekte/owncloud/master/lib/private/files/view.php' bgcolor='#eeeeec'>.../view.php<b>:</b>1123</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>17</td><td bgcolor='#eeeeec' align='center'>0.1212</td><td bgcolor='#eeeeec' align='right'>2994960</td><td bgcolor='#eeeeec'>OC\Files\Storage\Wrapper\Wrapper->hasUpdated(  )</td><td title='/home/mjob/Projekte/owncloud/master/lib/private/files/cache/watcher.php' bgcolor='#eeeeec'>.../watcher.php<b>:</b>89</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>18</td><td bgcolor='#eeeeec' align='center'>0.1212</td><td bgcolor='#eeeeec' align='right'>2994960</td><td bgcolor='#eeeeec'>OC\Files\Storage\Wrapper\Wrapper->hasUpdated(  )</td><td title='/home/mjob/Projekte/owncloud/master/lib/private/files/storage/wrapper/wrapper.php' bgcolor='#eeeeec'>.../wrapper.php<b>:</b>375</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>19</td><td bgcolor='#eeeeec' align='center'>0.1212</td><td bgcolor='#eeeeec' align='right'>2995056</td><td bgcolor='#eeeeec'>OCA\Files_Sharing\External\Storage->hasUpdated(  )</td><td title='/home/mjob/Projekte/owncloud/master/lib/private/files/storage/wrapper/wrapper.php' bgcolor='#eeeeec'>.../wrapper.php<b>:</b>375</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>20</td><td bgcolor='#eeeeec' align='center'>0.1212</td><td bgcolor='#eeeeec' align='right'>2995368</td><td bgcolor='#eeeeec'>OC\Files\Storage\DAV->hasUpdated(  )</td><td title='/home/mjob/Projekte/owncloud/master/apps/files_sharing/lib/external/storage.php' bgcolor='#eeeeec'>.../storage.php<b>:</b>161</td></tr>
</table></font>
```

**Comment by PVince81** [comment]
@MorrisJobke how did you mount it ? S2S share or "add to owncloud" ? How did you made the target OC unavailable, did you set it to maintenance mode ?

**Comment by PVince81** [comment]
@MorrisJobke can you put a breakpoint in dav.php on line 753 and evaluate the exception  and post the result here ? I don't understand why Sabre would return a ClientException instead of ClientHttpException. Or is it "connection refused" or something ? (which is on another layer,  not HTTP)

**Comment by MorrisJobke** [comment]
> Or is it "connection refused" or something ? (which is on another layer, not HTTP)

Yes. I shut down the apache :(


I will retry with the maintenance mode

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
If I shut down the apache it's a:

`Sabre\HTTP\ClientException` with code `7` and message `Failed to connect to 192.168.0.17 port 80: Connection refused`. We should handle this as well.

If I shut down the whole PC it's:

`Sabre\HTTP\ClientException` with code `7` and message `Failed to connect to 192.168.0.17 port 80: No route to host`.

Can we include these two as well? Because I think they are also valid "storage not available", because of network/server/process outage.

**Comment by MorrisJobke** [comment]
Let's address the above two use cases in a separate ticket and merge this, because this fixes a specific case.

**Pull request merged**
