### PR TITLE
Set files_list to empty array if we don't have any selected files

### LINKED ISSUE #39187: Downloading all files from the root directory delivers the file ".zip"
### Steps to reproduce
1. Login at https://demo.owncloud.org/
2. Click the "select all files" checkbox
3. Click "Download"

### Expected behavior
The file name offered for download is somefilename.zip, not only the extension

### Actual behavior
The file name offered for download is .zip

### Server configuration
demo.owncloud.org

**ownCloud version:** (see ownCloud admin page)
10.8

This behavior makes it impossible for users of some operating systems to directly open the file without renaming it.

"I also noticed that if I select 3 or 4 files, but not all, then “download.zip” is downloaded. But as soon as I put a check mark to select all files, then only “zip” is downloaded."

Reference: https://central.owncloud.org/t/files-are-downloaded-as-a-file-without-extension/33798

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Bugfix: Set file name to download.zip while downloading the whole user directory

Before this PR, selecting all files and folders in the webUI and clicking the
download button, resulted in a file downloaded with the name ".zip".
With this PR the file name is now "download.zip".

## Related Issue

- Fixes https://github.com/owncloud/core/issues/39187

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32231/144/1

**Review by jvillafanez — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]
works - I tried:
- download all files/folders - `download.zip` comes
- download just 2 files/folders - `download.zip` comes
- download just 1 file - just the file downloads
- download just 1 folder - `folderName.zip` comes

**Comment by JanAckermann** [comment]
@phil-davis maybe we can add some acceptance tests later on?

**Comment by phil-davis** [comment]
> @phil-davis maybe we can add some acceptance tests later on?

Issue #39199

**Comment by jnweiger** [comment]
confirmed fixed in 10.9.0-beta1

**Pull request merged**
