### PR TITLE
Early fail debug

### PR DESCRIPTION
**Pull request by xoxys**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>install-dependencies-php7.2</strong> failed. The build is cancelled...</summary>

**Comment by xoxys** [comment]
<details><summary>:boom: Acceptance tests <strong>install-dependencies-php7.2</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
Hello World!

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>install-dependencies-php7.2</strong> failed. The build is cancelled...</summary>

**Pull request closed without merging**
