### PR TITLE
fix broken logtimezone

### PR DESCRIPTION
**Pull request by Phiber2000**
This fixes unapplied logtimezone reported in #23134.

### CODE REVIEW

**Comment by nickvergessen** [comment]
@karlitschek should backport, since wrong timestamps on logs are nasty.

**Comment by nickvergessen** [comment]
:+1:

**Comment by Phiber2000** [comment]
**License comment**
These contributions by me are licensed under MIT.

**Comment by karlitschek** [comment]
makes sense. please backport :+1:

**Comment by Phiber2000** [comment]
@nickvergessen ...a bit more than nasty because it breaks logs and so f.e. fail2ban, too.

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
Let me throw this into a branch which can be tested by travis ....

**Comment by Phiber2000** [comment]
@DeepDiver1975 now travis should be able to check it.
I updated branch to trigger a new check.

**Comment by nickvergessen** [comment]
@Phiber2000 the problem is, that jenkins can only check branchse in our repository, where you didn't push to.

**Comment by Phiber2000** [comment]
@nickvergessen I only recognized the abort because I wasn't a registered contributor.
Thanks for information!

**Comment by DeepDiver1975** [comment]
#23225 got merged

**Pull request closed without merging**
