### PR TITLE
[stable7] owner is stored as 'uid_owner', not as 'owner' in the oc_share table

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/owncloud/core/pull/17327

cc @MorrisJobke

### CODE REVIEW

**Comment by schiesbn** [comment]
cc @blizzz 7.0.7 backport from our fix, please review. Thanks!

**Comment by karlitschek** [comment]
:+1:

**Comment by schiesbn** [comment]
@rullzer you aready reviewed the 8.0 and 8.1 backport... maybe you also want to review this one? Thanks!

**Comment by rullzer** [comment]
I don't have a 7.0 install... Code looks good but I can't verify it :P

**Comment by MorrisJobke** [comment]
> I don't have a 7.0 install...

```
$ git checkout stable7
$ git submodule update
```

:stuck_out_tongue_closed_eyes:

**Comment by blizzz** [comment]
In my tests I could not see that this method is always called, and what I have not seen is that a valid $item was ever received. Otherwise codewise it looks good and is consistent with the other usages of array keys.

As a sidenote, instead I saw this (but also with plain stable7):

```
{"reqId":"559aa53d527b9","app":"files_sharing","message":"can not update etags on \/files\/ for user 004. Path does not exists","level":0,"time":"2015-07-06T15:56:45+00:00","method":"POST","url":"\/stable7\/index.php\/core\/ajax\/share.php"}
{"reqId":"559aa53d527b9","app":"files_sharing","message":"can not update etags on \/files\/ for user 006. Path does not exists","level":0,"time":"2015-07-06T15:56:45+00:00","method":"POST","url":"\/stable7\/index.php\/core\/ajax\/share.php"}
```

(004 and 006 are local users)  Anything known?

**Comment by schiesbn** [comment]
@blizzz At the moment I'm also not sure how this code path can be reached. That's why I have this follow-up PR https://github.com/owncloud/core/pull/17381. This will probably not go down to oC7, still I think it make sense to fix this obvious bug, as you can see here some people managed to reach this code path even if I don't know exactly how https://github.com/owncloud/core/issues/16740

Not sure about the other issue, does it only happens on this branch. Looks unrelated to me.

**Comment by schiesbn** [comment]
today is 7.0.8 freeze, so we have to decide if it should go in or not? Obvious in my few because we reference a db column which doesn't exists even if it is hard to find a code path to execute it.

cc @DeepDiver1975

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
