### PR TITLE
[tests-only] delete storage imports created by filesExternalWebdavOwncloud.feature:193

### PR DESCRIPTION
**Pull request by individual-it**
## Description
https://github.com/owncloud/core/blob/237a42963d7717b2906d16fed1b2760684be084f/tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature#L193 left an mountpoint behind after the test and other tests from https://github.com/owncloud/core/blob/5210ceedd21059c38c715474fa5b4ed24e351c13/tests/acceptance/features/cliLocalStorage/importLocalStorage.feature would fail

this was never a problem in core because both suites would run seperately but in app repos they might run after each other when using `DIVIDE_INTO_NUM_PARTS` and `RUN_PART`

## Related Issue

- Fixes https://github.com/owncloud/QA/issues/710 

## Motivation and Context
fix nightly builds of apps

## How Has This Been Tested?
running filesExternalWebdavOwncloud.feature:193 and importLocalStorage.feature:13 after each other before and after the fix
 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCapabilities-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34132/50/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiAuthWebDav-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34132/49/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToRoot2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34132/60/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToShares1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34132/59/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToShares2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34132/61/1

**Review by kiranparajuli589 — APPROVED** [review]

**Pull request merged**
