### PR TITLE
DAV authentication: use Owncloud's internal user instead of HTTP auth one

### LINKED ISSUE #14048: User did not have the required privileges ({DAV:}read) for path "principals/username”
### Actual behaviour
iOS and OS X is unable to sync contacts
OS X Error: The operation couldn’t be completed. (CoreDAVErrorDomain error 2.)
iOS Error: Could not establish SSL Connection

### Server configuration
**Operating system**:
Debian Wheezy 7.8 

**Web server:**
nginx 1.2.1

**Database:**
mysql 14.14
**PHP version:**
PHP 5.4.36-0+deb7u3 (fpm-fcgi)

**ownCloud version:** 
ownCloud 8.0 (stable)

**Updated from an older ownCloud or fresh install:**
Upgraded from previous stable version
moved data directory, saved config.php and placed it into the new owncloud version and set the new data directory. The upgrade worked well, but the clients cant sync contacts and calendars anymore. 

**List of activated apps:**
Activity 1.2.0
Bookmarks 0.4
Calendar 0.6.4
Contacts 0.3.0.18
Deleted files 0.6.2
First Run Wizard 1.1
PDF Viewer 0.7
Pictures 0.6.0
Share Files 0.6.0
Text Editor 0.4
Updater 0.4
Versions 1.0.5
Video Viewer 0.1.3

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => ‘123321’,
  'passwordsalt' => ‘123321’,
  'datadirectory' => '/var/www/owncloud-data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => ‘123321’,
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 4,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'cloud.123321.12’,
    1 => 'cloud.123321.13’,
  ),
  'mail_from_address' => 'no-reply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'cloud.123321.12’,
  'secret' => ‘123321’,
);

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
no

### Client configuration
**Operating system:**
iOS 8.1.3

#### ownCloud log (data/owncloud.log)

{"reqId":"605072fb2dc469836a2f0d235aca1e82","remoteAddr":"123.123.123.123","app":"carddav","message":"Exception: {\"Message\":\"User did not have the required privileges ({DAV:}read) for path \\\"principals\\\/username\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAVACL\\\/Plugin.php(712): Sabre\\\\DAVACL\\\\Plugin->checkPrivileges('principals\\\/username', '{DAV:}read')\\n#1 [internal function]: Sabre\\\\DAVACL\\\\Plugin->beforeMethod('OPTIONS', 'principals\\\/username')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('OPTIONS', 'principals\\\/username')\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAVACL\\\/Plugin.php\",\"Line\":217}","level":4,"time":"2015-02-10T12:47:56+00:00"}username

### PR DESCRIPTION
**Pull request by chris-se**
Fixes: #14048, #14104, calendar#712

### CODE REVIEW

**Comment by LukasReschke** [comment]
@karlitschek Fixes a regression introduced with stable8 which is caused by using the loginname and not the username. This breaks a lot of things and we should backport it. Agreed?

**Comment by LukasReschke** [comment]
We should adjust L55 then as well here.

**Comment by chris-se** [comment]
Please consider this contribution MIT licensed, I don't want to read, understand, think about and sign a legal document for something as trivial as this. (Honestly, I believe it's so trivial it probably doesn't even fall under copyright, but just in case...)

**Comment by LukasReschke** [comment]
@chris-se Thanks a lot for the contribution! *Very* nice catch! Can I ask you to adjust L55 as well and test whether this still works? 

For example like `$this->isDavAuthenticated(\OC_User:.getUser())`

**Comment by LukasReschke** [comment]
@owncloud-bot This is okay to test.

**Comment by chris-se** [comment]
I've updated the pull request for line 55. With that change it still works for me, i.e. if I change stuff on my smartphone, it updates the OC server.

**Comment by Phillinger** [comment]
Re-activated my owncloud 8 installation, patched my auth.php and ... it works! Thank you, awesome work!

**Comment by karlitschek** [comment]
absolutely. please backport

**Comment by blizzz** [comment]
:+1:

**Comment by Karl52** [comment]
Patched Line 64 and Line 55 -  Thunderbird is syncing again with OC 8.0.5
Thanks a lot

**Comment by RealRancor** [comment]
Milestone 8.1-next? Isn't it better to have this in the next maintenance release 8.0.1?

**Comment by LukasReschke** [comment]
This will be backported as well - no worries :smile:

**Comment by LukasReschke** [comment]
:+1:

**Comment by LukasReschke** [comment]
Backport PR to stable8: https://github.com/owncloud/core/pull/14423

**Comment by rstoever** [comment]
Hi, I update the my owncloud to 8.0 and already to change some sources but is not resolved my problem

/remote.php/caldav/principals/username/core/img/breadcrumb.svg HTTP/1.1" 503 6571
/remote.php/caldav/principals/username/core/search/templates/part.results.html HTTP/1.1" 503 6571

And If I entry in home page, stay updating and not progress this

 rpm -qa | grep owncloud
owncloud-3rdparty-8.0.0-27.1.noarch
owncloud-app-files_locking-8.0.0-27.1.noarch
owncloud-app-files_pdfviewer-8.0.0-27.1.noarch
owncloud-app-files_versions-8.0.0-27.1.noarch
owncloud-app-external-8.0.0-27.1.noarch
owncloud-app-files_sharing-8.0.0-27.1.noarch
owncloud-app-files_encryption-8.0.0-27.1.noarch
owncloud-app-firstrunwizard-8.0.0-27.1.noarch
owncloud-config-apache-8.0.0-27.1.noarch
owncloud-app-files_trashbin-8.0.0-27.1.noarch
owncloud-app-user_external-8.0.0-27.1.noarch
owncloud-app-files_external-8.0.0-27.1.noarch
owncloud-app-files_videoviewer-8.0.0-27.1.noarch
owncloud-app-user_webdavauth-8.0.0-27.1.noarch
owncloud-app-files_texteditor-8.0.0-27.1.noarch
owncloud-app-files-8.0.0-27.1.noarch
owncloud-app-templateeditor-8.0.0-27.1.noarch
owncloud-app-activity-8.0.0-27.1.noarch
owncloud-app-provisioning_api-8.0.0-27.1.noarch
owncloud-app-user_ldap-8.0.0-27.1.noarch
owncloud-app-updater-8.0.0-27.1.noarch
owncloud-app-gallery-8.0.0-27.1.noarch
owncloud-server-8.0.0-27.1.noarch
on CentOS release 6.6 (Final)

**Comment by RealRancor** [comment]
@rstoever 
A 503 means "Service not available" which shouldn't be related to this issue. Instead of manually modification its also better to wait until OC 8.0.2 is released on the repos which includes this fix.

**Pull request merged**
