### PR TITLE
[stable10] Bump symfony v3.4.20 => v3.4.21

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
https://symfony.com/blog/symfony-3-4-21-released
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 0 installs, 14 updates, 0 removals
  - Updating symfony/debug (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/console (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/event-dispatcher (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/process (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/routing (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/translation (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/class-loader (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/filesystem (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/config (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/dependency-injection (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/finder (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/options-resolver (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/stopwatch (v3.4.20 => v3.4.21): Loading from cache
  - Updating symfony/yaml (v3.4.20 => v3.4.21): Loading from cache
```

Note: ``master`` PR is #34041 

## Motivation and Context
Keep up-to-date with patches of dependencies

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
I vote for merge for 10.1 - final decision is up to @PVince81

**Comment by phil-davis** [comment]
This is getting https://drone.owncloud.com/owncloud/core/14331/596
```
    And user "user1" from server "REMOTE" shares "/simple-folder (2)" with user "user2" from server "LOCAL" using the sharing API # FederationContext::userFromServerSharesWithUserFromServerUsingTheSharingAPI()
    And the user sets the sharing permissions of "user2@%local_server%/ (federated)" for "simple-folder (2)" using the webUI to   # WebUISharingContext::theUserSetsTheSharingPermissionsOfForOnTheWebUI()
      | edit | no |
      SensioLabs\Behat\PageObjectExtension\PageObject\Exception\ElementNotFoundException: Page\FilesPageElement\SharingDialog::setSharingPermissions xpath .//*[@id='shareWithList']//*[@class='has-tooltip username' and .='user2@https://server/ (federated)']/.. could not find share permissions field for user user2@https://server/ (federated) in /drone/src/tests/acceptance/features/lib/OwncloudPage.php:821
```

```
--- Failed scenarios:

    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:201
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:219

46 scenarios (44 passed, 2 failed)
474 steps (460 passed, 2 failed, 12 skipped)
```

These scenarios were added by master PR #33506 and backported to stable10 by PR #34172 
It passes in master which has symfony 3.4.21, but fails here attempting to bump symfony to 3.4.21 in stable10 ???

**Comment by phil-davis** [comment]
I rebased to latest stable10, and compared the diff of ``composer.lock`` with PR #34180 and the diffs are the same. CI passed this time. Maybe there is just some intermittent timing issue with those new scenarios.

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
