### PR TITLE
Use correct name for background jobs

### LINKED ISSUE #26202: Carddav sync job never runs, namespace mismatch
### Steps

1. Setup v9.1.1
1. `select * from oc_jobs`
1. Run cron several times
1. `select * from oc_jobs`

### Expected
Sync job runs, marked as such in oc_jobs

### Actual
OCA\DAV\CardDAV\Sync\SyncJob  job never runs:

```
MariaDB [owncloud]> select * from oc_jobs;
+----+---------------------------------------------------+----------+------------+--------------+-------------+
| id | class                                             | argument | last_run   | last_checked | reserved_at |
+----+---------------------------------------------------+----------+------------+--------------+-------------+
|  1 | OCA\Files_Versions\BackgroundJob\ExpireVersions   | null     | 1474639042 |   1474639118 |           0 |
|  2 | OCA\Files_Sharing\DeleteOrphanedSharesJob         | null     | 1474639117 |   1474639118 |           0 |
|  3 | OCA\Files_Sharing\ExpireSharesJob                 | null     | 1474639117 |   1474639117 |           0 |
|  4 | OCA\Files_Trashbin\BackgroundJob\ExpireTrash      | null     | 1474639117 |   1474639117 |           0 |
|  5 | OCA\Files\BackgroundJob\ScanFiles                 | null     | 1474639117 |   1474639117 |           0 |
|  6 | OCA\Files\BackgroundJob\DeleteOrphanedItems       | null     | 1474639117 |   1474639117 |           0 |
|  7 | OCA\Files\BackgroundJob\CleanupFileLocks          | null     | 1474639117 |   1474639117 |           0 |
|  8 | OCA\DAV\CardDAV\Sync\SyncJob                      | null     |          0 |   1474639117 |  1474639117 |
|  9 | OCA\Federation\SyncJob                            | null     | 1474639117 |   1474639117 |           0 |
| 10 | OCA\UpdateNotification\Notification\BackgroundJob | null     | 1474639117 |   1474639117 |           0 |
| 11 | \OC\Authentication\Token\DefaultTokenCleanupJob   | null     | 1474639118 |   1474639118 |           0 |
+----+---------------------------------------------------+----------+------------+--------------+-------------+
```

It seems that the namespace doesn't match the class, wasn't this moved recently ?

@DeepDiver1975 please clarify. What's the consequence ?
What's the difference with the federation sync job ?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

Use proper class name
## Related Issue

fixes #26202
## TODO
- [ ] remove old wrong job from oc_jobs
- [x] increment app version to trigger upgrade :question: 
- [x] backport :question: 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
> remove old wrong job

or invent a special repair step that is clever enough to delete jobs for which the class does not exist any more (ex: disabled apps) and kill two birds with the same stone :smile:

**Comment by PVince81** [comment]
on the other hand, what happens when inserting two jobs with the same name ? isn't there some kind of deduplication in place ?

**Comment by MorrisJobke** [comment]
> on the other hand, what happens when inserting two jobs with the same name ? isn't there some kind of deduplication in place ?

It will simply not be added. That was the trick back then with the "cleanup the trashbin" background job. Simply add it again and again. It was always only once in the jobs table.

**Comment by PVince81** [comment]
@DeepDiver1975 any update ?

**Comment by PVince81** [comment]
tagging as regression to make sure we get this in for 9.2

**Comment by PVince81** [comment]
@DeepDiver1975 any update ? People who setup 9.1.1 from scratch will have problems with system address book syncing.

**Comment by PVince81** [comment]
Tested, upgrading to this branch properly adds the missing job.
We can look into providing a repair step to delete the old one separately :+1:

**Comment by PVince81** [comment]
@DeepDiver1975 can you prepare the backport PR for 9.1 ? (being optimistic that CI will pass...)

**Pull request merged**
