### PR TITLE
Fixing node components

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
PR #34794 forward-ported yarn-related changes to `Makefile` from `stable10` PR #33665

Those need other commits from that PR, so that `make dist` will know about `clean-modules`

## How Has This Been Tested?
```
make clean
make dist
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by DeepDiver1975 — COMMENTED** [review]
Looks good. THX

**Comment by phil-davis** [comment]
NP - I broke it. IMO better to try and fix it than back-out the changes.
It is a pain having code in `stable10` that did not start its life in `master` - forward-porting seems to be often even less obvious than back-porting.

**Comment by phil-davis** [comment]
@PVince81 @DeepDiver1975 or anyone who approves this. Please merge it so it gets in the QA tarball tonight.

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
