### PR TITLE
Fixes hiding i in right sidebar.

### PR DESCRIPTION
**Pull request by raghunayyar**
A fix for : https://github.com/owncloud/core/issues/20061

@owncloud/designers @schiesbn

### CODE REVIEW

**Comment by MorrisJobke** [comment]
This looks weird on wide screens: 
bildschirmfoto 2015-10-27 um 20 48 32

**Comment by raghunayyar** [comment]
@MorrisJobke observe carefully that if I span it any longer, the tooltip of the i gets cut. So, I did it the maximum which was possible. I have a retina display myself so I am seeing something similar to what you are seeing. :)

**Comment by MorrisJobke** [comment]
> @MorrisJobke observe carefully that if I span it any longer, the tooltip of the i gets cut. So, I did it the maximum which was possible. I have a retina display myself so I am seeing something similar to what you are seeing. :)

But it looks ugly. Then the tooltip should open to the left side. cc @owncloud/designers

**Comment by raghunayyar** [comment]
@MorrisJobke I dont mind that, lets wait for what @jancborchardt has to say. I will make changes based on the conclusion. :)

**Comment by jancborchardt** [comment]
The tooltip should be below (not overlaying the input field which it relates to), but can be made so that it’s right-aligned with the icon and spans further to the left. @raghunayyar can you change that?

**Comment by raghunayyar** [comment]
@jancborchardt I didnt get anything you said, something on paper please?

**Comment by MorrisJobke** [comment]
Better fix is in https://github.com/owncloud/core/pull/20843 -> closing this

**Pull request closed without merging**
