### PR TITLE
Get rid of the obsolete OC_VObject class

### PR DESCRIPTION
**Pull request by PVince81**
The class isn't needed any more since the update to Sabre 2.1

We might want to wait for the tasks app to stop using it: https://github.com/owncloud/tasks/pull/159

@DeepDiver1975 @georgehrke @raimund-schluessler

### CODE REVIEW

**Comment by nickvergessen** [comment]
Either we drop this for 8.1, or we still need the fix from #15668 right?

**Comment by georgehrke** [comment]
I'd also vote to get rid of this.

**Comment by PVince81** [comment]
Contacts and calendar already don't need this any more.
Only the tasks app remain to be adapted: https://github.com/owncloud/tasks/pull/159

**Comment by georgehrke** [comment]
and theoretically the journal app, but there are some other issues causing it not to work with ownCloud 8 anyway https://github.com/tanghus/journal

**Comment by PVince81** [comment]
Also, OC_VObject isn't in the public namespace, so apps aren't even supposed to use it!

**Comment by raimund-schluessler** [comment]
I will definitely update the tasks app so it won't use OC_VObject anymore. So we should drop support for it

However, for the next two weeks I won't be available as I am on a business trip. So adapting the tasks app will take probably 3 weeks.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
even 8.1 would be okay for me - why carry it around much longer

**Comment by DeepDiver1975** [comment]
@georgehrke we have been talking about geo.php months back - time to kill it as well? https://github.com/owncloud/core/blob/master/lib/private/geo.php

**Comment by PVince81** [comment]
Because we're past feature freeze ? This is not technically a bugfix, just cleanup. Potentially an API change, but it's a private API. So... I don't mind.

**Comment by georgehrke** [comment]
@DeepDiver1975 I'll prepare a pr for the calendar to the remove OC_Geo's usage and then we can get rid of it.

**Comment by raimund-schluessler** [comment]
I guess for the Tasks app 8.1 is OK too, as it requires a lot of changes anyway to make it work with Sabre 2.1.

**Comment by nickvergessen** [comment]
@PVince81 as stated already, if we ship it we need to fix it, but fixing it when we dump it anyway is kind of ... pointless?

**Comment by DeepDiver1975** [comment]
> Because we're past feature freeze ? This is not technically a bugfix, just cleanup

The whole class is a bug as it's broken and we would need to fix and test it for 8.1.
Because it's not longer needed we can just simply skip it.

**Comment by DeepDiver1975** [comment]
> I'll prepare a pr for the calendar to the remove OC_Geo's usage and then we can get rid of it.

thx

**Comment by PVince81** [comment]
>The whole class is a bug
Haha. Agreed.

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
