### PR TITLE
Add mapping for a broken varchar type.

### LINKED ISSUE #14247: Upgrade 7.0.4.2 -> 8.0.0.7: Unknown database type varchar requested
Update failed with the following message:

Unknown database type varchar requested, Doctrine\DBAL\Platforms\SqlitePlatform may not support it.

Please find the relevant log entries below:

{"reqId":"70a092144084d5e3a9db39e857b444aa","remoteAddr":"131.152.98.222","app":"core","message":"starting upgrade from 7.0.4.2 to 8.0.0.7","level":0,"time":"2015-02-16T09:50:24+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=99b5c91d1c1ba25c0ed9"}
{"reqId":"70a092144084d5e3a9db39e857b444aa","remoteAddr":"131.152.98.222","app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'Unknown database type varchar  requested, Doctrine\\DBAL\\Platforms\\SqlitePlatform may not support it.' in \/var\/www\/owncloud\/lib\/private\/db\/sqlitemigrator.php:39\nStack trace:\n#0 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(113): OC\\DB\\SQLiteMigrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#1 \/var\/www\/owncloud\/lib\/private\/db.php(252): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#2 \/var\/www\/owncloud\/lib\/private\/updater.php(241): OC_DB::simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#3 \/var\/www\/owncloud\/lib\/private\/updater.php(210): OC\\Updater->checkCoreUpgrade()\n#4 \/var\/www\/owncloud\/lib\/private\/updater.php(149): OC\\Updater->doUpgrade('8.0.0.7', '7.0.4.2')\n#5 \/var\/www\/owncloud\/core\/ajax\/update.php(49): OC\\Updater->upgrade()\n#6 {main})","level":4,"time":"2015-02-16T09:50:24+00:00","method":"GET","url":"\/cloud\/core\/ajax\/update.php?requesttoken=99b5c91d1c1ba25c0ed9"}

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes #14247

As reported in https://github.com/owncloud/core/issues/6416 also reproducible for 5 to 6 migrations

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@karlitschek we should backport this to stable8 from my understanding - THX

**Comment by karlitschek** [comment]
yes. please backport

**Comment by DeepDiver1975** [comment]
@VicDeo please open a new pr against stable8 branch - THX

**Comment by VicDeo** [comment]
@DeepDiver1975 done https://github.com/owncloud/core/issues/14345

**Pull request merged**
