### PR TITLE
occ option to update all third party apps without disable

### LINKED ISSUE #16221: occ option to update all third party apps without disable
Right now an upgrade disables all third party apps (but not gallery / activity, for some reason?).
Suggestion: If I know what I am doing and replace all third party apps (before the update) with working/tested versions, an option to "force" the update would be helpful. As a result core and all available apps (also the deactivated?) get the update. The user will never see the update screen. 

Can this be achieved? 

Similar discussion: https://github.com/owncloud/core/issues/14754

### PR DESCRIPTION
**Pull request by Gomez**
Adds option ./occ upgrade --no-app-disable 

Fixes https://github.com/owncloud/core/issues/16221

Need further testing

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
thanks @Gomez 

@PVince81 @MorrisJobke please review - thx

@karlitschek we might want to consider this to be backported for stable8 as this might hit upgrades on bigger installations.

**Comment by karlitschek** [comment]
:+1: nice. please also back port

**Comment by nickvergessen** [comment]
:+1: - also checked that the web UI still disables the apps.

**Comment by nickvergessen** [comment]
@Gomez will you prepare the backport?

**Comment by Gomez** [comment]
@nickvergessen Done, ready for review/merge

**Pull request merged**
