### PR TITLE
[tests-only] Adjust tests to match trashbin-skip requirements

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
The trashbinSkip test scenarios are incorrect in the `release-10.8.0` branch after https://github.com/owncloud/core/commit/ee1f77ec7e7358a8ed8ae8f7243323b435eb88bc was pushed to the branch.

This gets the test scenarios correct and passing.

IMO it might cause git to report conflicts with `master` - I am not sure, because the fix of trashbinSkip behavior, and these test fixes, are not in `master` yet anyway. So they should merge OK to master.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares2-10.6.0-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31141/118/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIProxySmoke-3-3-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31141/170/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingAutocomp1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31141/144/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiTrashbin-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31143/88/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIComments-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31148/130/1

**Comment by phil-davis** [comment]
Note: the diffs here are the reverse of the last commit to `release-10.8.0` https://github.com/owncloud/core/pull/38861/commits/ee1f77ec7e7358a8ed8ae8f7243323b435eb88bc

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliExternalStorage-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31149/125/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliExternalStorage-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31149/126/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/31149/35/10
`services aren't ready in 13m20s`
various slow  pipeline starts in drone - restarted

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/31151/160/19
That pipeline "just stopped" after 2 hours 26 minutes. It looks like it hung - there was no output from the tests after the first 4 minutes.
Restarting CI...

**Comment by phil-davis** [comment]
@micbar merge?
We need to do something to make tests pass in the release branch.

**Review by micbar — APPROVED** [review]

**Pull request merged**
