### PR TITLE
use query builder

### PR DESCRIPTION
**Pull request by butonic**
`to_char` may throw an error, `dbms_lob.substr` is the way to go

see https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions179.htm and https://asktom.oracle.com/pls/asktom/f?p=100:11:0::no::p11_question_id:367980988799

### CODE REVIEW

**Comment by butonic** [comment]
see https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions179.htm and https://asktom.oracle.com/pls/asktom/f?p=100:11:0::no::p11_question_id:367980988799

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2016-10-20 12-20-45

**Comment by DeepDiver1975** [comment]
mysql:

````
15:27:16 Time: 5.57 minutes, Memory: 216.89MB
15:27:16 
15:27:16 There was 1 error:
15:27:16 
15:27:16 1) Test\AllConfigTest::testGetUsersForUserValue
15:27:16 Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT `userid`, `value` FROM `oc_preferences` WHERE (`appid` = ?) AND (`configkey` = ?) AND (`configvalue` IS NOT NULL) AND (`configvalue` = ?)' with params ["appFetch9", "keyFetch9", "value9"]:
15:27:16 
15:27:16 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'value' in 'field list'
15:27:16 
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:836
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/private/DB/Connection.php:188
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/private/DB/QueryBuilder/QueryBuilder.php:141
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/private/AllConfig.php:437
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/tests/lib/AllConfigTest.php:426
15:27:16 
15:27:16 Caused by
15:27:16 Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'value' in 'field list'
15:27:16 
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:828
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/private/DB/Connection.php:188
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/private/DB/QueryBuilder/QueryBuilder.php:141
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/private/AllConfig.php:437
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/tests/lib/AllConfigTest.php:426
15:27:16 
15:27:16 Caused by
15:27:16 PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'value' in 'field list'
15:27:16 
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:828
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/private/DB/Connection.php:188
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/private/DB/QueryBuilder/QueryBuilder.php:141
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/lib/private/AllConfig.php:437
15:27:16 /var/lib/jenkins/workspace/owncloud-core_core_PR-26425-X4V3NBBAVWUOJSFSMT2V7H72UNM3P5XSZEQR4D7TZHBTRBZT6DMA@2/tests/lib/AllConfigTest.php:426
15:27:16 
15:27:16 --
15:27:16

**Comment by butonic** [comment]
quick review @PhilippSchaffrath @IljaN

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
