### PR TITLE
also log the class for dav exceptions

### PR DESCRIPTION
**Pull request by icewind1991**
Make it consistent with the rest of our exception logging.

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
:+1: makes sense

**Comment by icewind1991** [comment]
@MorrisJobke can you review this?

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
