### PR TITLE
Bump phan to 1.3.5 and enable on PHP 7.2 7.3

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #35697

Backport #35817 

The 4th commit is for code that is in `stable10` but not `master` and gets reported by `phan`

Note: this has been rebased to the "new" `master`.

### CODE REVIEW

**Comment by phil-davis** [comment]
ToDo:
- [ ] sort out extra `PhanUndeclaredMethod` reported in `stable10`

```
apps/encryption/lib/AppInfo/Application.php:143 PhanUndeclaredMethod Call to undeclared method \OCP\IServerContainer::getTimeFactory
apps/files_sharing/lib/Scanner.php:78 PhanUndeclaredMethod Call to undeclared method \OC\Files\Storage\Storage::resolvePath
apps/files_sharing/lib/Scanner.php:93 PhanUndeclaredMethod Call to undeclared method \OC\Files\Storage\Storage::resolvePath
apps/provisioning_api/lib/Groups.php:106 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
apps/provisioning_api/lib/Groups.php:181 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
lib/private/DB/MySqlSchemaColumnDefinitionListener.php:54 PhanUndeclaredMethod Call to undeclared method \OCP\IDBConnection::getDatabaseVersionString
lib/private/Files/ObjectStore/ObjectStoreStorage.php:341 PhanUndeclaredMethod Call to undeclared method \OCP\Files\Storage::getBucket
lib/private/Files/View.php:384 PhanUndeclaredMethod Call to undeclared method \OC\Files\Storage\Local::readdir
lib/private/Group/MetaData.php:192 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
lib/private/Share/Share.php:2037 PhanUndeclaredMethod Call to undeclared method \OCP\Share_Backend::getParents
lib/private/Share/Share.php:2061 PhanUndeclaredMethod Call to undeclared method \OCP\Share_Backend::getParents
settings/Controller/UsersController.php:196 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:314 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:419 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:426 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:757 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:810 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:930 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:972 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:1056 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:1057 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
settings/Controller/UsersController.php:1138 PhanUndeclaredMethod Call to undeclared method \OCP\IGroupManager::getSubAdmin
```

**Comment by phil-davis** [comment]
Note: https://drone.owncloud.com/owncloud/core/19398/112
```
The latest Phan release (Phan 2) requires PHP 7.1+ to run, but PHP 7.0.33-8+ubuntu16.04.1+deb.sury.org+1 and Phan 1.3.5 are installed.
```

This is why I bumped to only `phan` `1.3.5`

After we drop PHP 7.0 then we can move to `phan` `2.*.*`

**Comment by phil-davis** [comment]
@patrickjahns @DeepDiver1975 or somebody, please review.

**Comment by phil-davis** [comment]
@DeepDiver1975 @patrickjahns if someone could review this, then it could be merged now. That will save having to regenerate it against the "new" `master` that is coming.

I rebased it this morning and drone passed. It fails codecov by a bit, because it edits "random" files in places that might not have the average 65% code coveraage.

**Comment by phil-davis** [comment]
@patrickjahns @DeepDiver1975 or anybody.
This has been rebased to "new" `master`.
drone CI passes. It fails codecov because the small additions for `phan` on average are in classes that do not have the project-average code coverage.
IMO it would be nice to get this running again.
Please review.

**Comment by phil-davis** [comment]
In the drone update we have preserved the "random" drone errors:
https://drone.owncloud.com/owncloud/core/20018/26/9
```
cURL error 6: Could not resolve host: scality 
```

**Comment by individual-it** [comment]
@phil-davis please resolve conflict

**Comment by phil-davis** [comment]
Conflicts resolved.
@patrickjahns @DeepDiver1975 or somebody - please review.

**Comment by phil-davis** [comment]
I rebased again to make sure that CI is all good with today's current master.
@PVince81 @DeepDiver1975 @patrickjahns or anybody - review please.

**Comment by PVince81** [comment]
I wonder why our code needs that many string literals for variables and whether there is something we can do to avoid those in the future, like better variable / type declarations ? Or is it the way our classes are constructed ?

**Review by PVince81 — APPROVED** [review]
:+1: if CI passes

**Comment by phil-davis** [comment]
> I wonder why our code needs that many string literals for variables and whether there is something we can do to avoid those in the future, like better variable / type declarations ? Or is it the way our classes are constructed ?

This gets `phan` running and passing again. Basically I did:
- if there was already a "comment" typehint (which `phan` could not understand) or other "obvious" evidence of what type the object is, then I put in the "magic" `@phan-var` string literal that allows `phan` to understand the type hint.
- if the type of the object was not "obviously" guaranteed in some way, then I did `@phan-suppress-next-line PhanUndeclaredMethod` to suppress the report from `phan`

"somebody" "someday" should go through these in detail, understand why `phan` could not deduce the object type, understand if there is a real code problem that could actually go boom in some way, and fix/refactor our code.

**Comment by phil-davis** [comment]
Stupid drone https://drone.owncloud.com/owncloud/core/20351/83/4
```
behat-chrome-webUIWebdavLockProtection: Error: No such image: docker.io/library/mariadb:10.2
```

**Comment by patrickjahns** [comment]
@phil-davis 
Instead of needing to use `@phan-var` please try to use `@property` for class properties. This should deliver a more clean annotation

https://github.com/phan/phan/wiki/Annotating-Your-Source-Code#property

**Pull request merged**
