### PR TITLE
[stable9] Fix post_unshareFromSelf hook parameter format

### PR DESCRIPTION
**Pull request by PVince81**
Forward port of https://github.com/owncloud/core/pull/26364 to stable9

### CODE REVIEW

**Comment by jvillafanez** [comment]
:+1:

**Comment by PVince81** [comment]
oh noes, failing tests

**Comment by PVince81** [comment]
can't reproduce the problem with a manual test... hmmm

**Comment by PVince81** [comment]
Weiiird... I debugged into the code.

The code that combines etags based on all mount points is inside `FileInfo->addSubEntry()` (and later `FileInfo->getEtag`). But the combination is only done if the data passed to `addSubEntry()` contains an "etag" attribute. For some reason during the unit tests the "etag" attribute is missing from the passed file info... this makes the etag combination fail and the test fails.

**Comment by PVince81** [comment]
It looks like the ownerView belongs to user2, for the shared storage connected to "files/test" in user3's point. This is wrong, the owner is user1. So because in the test user2 unshares from self, so when checking if the folder is still visible it does it with user2's view where it's obviously gone instead of user1...

Need to find out why... possibly another bug. Also strange that it doesn't happen in stable9.1...

**Comment by PVince81** [comment]
So... I tried reproducing this in the web UI but the correct owner is added to the database.
However when running these unit tests, the owner in the DB is user2 instead of user1, which is wrong.

So I suspect that the web UI is using the new APIs to create the share, which create it correctly, while the test still uses the old static APIs, which might not do it correctly. But since it works in stable9.1, then it means there is a fix that might need backporting.

**Comment by PVince81** [comment]
Yep, found it... the GroupEtagPropagation test in stable9.1 is using the new API and stable9 is using the old one... So the old API is broken, probably related to https://github.com/owncloud/core/issues/24981

**Comment by PVince81** [comment]
For the sake of finishing this PR, I'll try and backport the part that makes use of the new sharing API

**Comment by PVince81** [comment]
@jvillafanez I had to partially backport the etag propagation test cases from stable9.1 which use the new sharing API for creating shares while testing, see https://github.com/owncloud/core/pull/26389/commits/a3bcee8c8c821f8dd9eda203e012d3c711572668

We'll eventually need to look into the actual issue with the old sharing API here: https://github.com/owncloud/core/issues/24981 (or ideally get rid of it completely...)

**Comment by PVince81** [comment]
@jvillafanez mind approving the extra backport ?

**Pull request merged**
