### PR TITLE
Have displayname, or username if there is no displayname, appear in s…

### PR DESCRIPTION
**Pull request by scolebrook**
…haring error messages rather than just username only. Fixes guids appearing in user facing messages in ldap/ad based setups.

### CODE REVIEW

**Comment by scolebrook** [comment]
To test, share a file to a group. Login as a member of the that receiving group and try and share that file to another member of the group. On an LDAP/AD system before this commit you see the internal username (objectGUID attribute) of the user you were trying to share to in the error message. After the commit you see that persons displayname if they have one. If a backend doesn't provide a displayname then the username appears as a fallback, just like it does now.

**Comment by PVince81** [comment]
Thanks! @owncloud/sharing @owncloud/ldap

**Comment by PVince81** [comment]
Tested, works :+1: 

Second review please @jvillafanez @butonic

**Comment by jvillafanez** [comment]
I have my doubts about creating a variable near the top with the display name of what we need (shareWith for eaxample) to reduce duplication, or to keep it as it is now because it should perform faster in same cases (no need to get the display name specially if there is no error)

Anyway, code looks good 👍

**Comment by PVince81** [comment]
> I have my doubts about creating a variable near the top with the display name of

I recommended not doing this because the call itself does an additional database call which might be wasted if we don't need the display name after all.

**Comment by PVince81** [comment]
CC @dragotin @DeepDiver1975 not really a backport but fixes a bug in 8.2

**Pull request merged**
