### PR TITLE
Show hint if there is no delete permission

### LINKED ISSUE #15172: Show disabled icon for delete action if there is no permission
* have a file where you don't have a permission for delete

## expected behaviour

show that the delete action isn't available because of the missing permission

## actual behaviour

delete action is simply not there

cc @jancborchardt 

as discussed with @msrex

### PR DESCRIPTION
**Pull request by MorrisJobke**
- add class .no-permission which shows the default delete icon
- fixes #15172 

cc @owncloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I will fix the tests and write some new ones

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by MorrisJobke** [comment]
@PVince81 I added a JS unit test to check for the CSS class. \o/

This is now ready for review :)

**Comment by MorrisJobke** [comment]
I fixed some scrutinizer complains

**Comment by jancborchardt** [comment]
Nice work, thank you! :+1:

**Pull request merged**
