### PR TITLE
[3rdparty] Bump assetic to 1.3.2

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/224

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by rullzer** [comment]
https://github.com/owncloud/core/pull/20742 should go in first before rebasing.

**Comment by DeepDiver1975** [comment]
> #20742 should go in first before rebasing.

merged

**Comment by rullzer** [comment]
Rebased

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
