### PR TITLE
Use a birthday title which does not require translation because we ha…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…ve no idea about the target device language and forcing English upon all users is kind of bad

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jakobsack FYI

**Comment by DeepDiver1975** [comment]
@jancborchardt @georgehrke @raghunayyar please review - THX

**Comment by georgehrke** [comment]
:+1:

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
