### PR TITLE
[stable10] Remove session handling from loadApps (revived)

### PR DESCRIPTION
**Pull request by PVince81**
Brings back what was reverted due to time constraints: https://github.com/owncloud/core/pull/31761

For 10.0.10, don't merge yet

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jvillafanez this an old backport related to session - mind having a look? Do we still need this? THX

**Comment by jvillafanez** [comment]
I'm not sure if we need it, but I don't think it's a good place to have something regarding sessions there, so I'd pefer to keep the PR.
I think we'll have to test this patch with the latest code and changes, specially regarding the sessions, in order to ensure we don't break anything. Session code is too fragile to merge anything without testing.

**Comment by DeepDiver1975** [comment]
Drone is read because of network issues on a web acceptance test - anything else is green.
Please note that the original PR was merged long time ago to archive/master.

I vote for merge ....

**Comment by jvillafanez** [comment]
I'd rather wait until the rest of the PR are merged so we can test this PR on top those changes. As far as I know, this PR hasn't been tested recently and there could be changes that could affect this PR, specially the latest changes for the sessions (which hasn't been merged yet)

**Comment by PVince81** [comment]
as I remember, this was a rather dangerous PR that broke stuff.

if there is no clear need for it, maybe just close ?

**Pull request closed without merging**
