### PR TITLE
[HHVM] Throw RunTimeException from OC\AppFramework\App::buildAppNamespace()

### LINKED ISSUE #16056: HHVM segfault via simplexml_load_file()
```
hhvm /usr/local/bin/phpunit --configuration phpunit-autotest.xml --tap --filter OC\\\\AppFramework\\\\AppTest
TAP version 13
ok 1 - OC\AppFramework\AppTest::testControllerNameAndMethodAreBeingPassed
Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.10181.log
Segmentation fault
```

```
#0  simplexml_load_file(/appinfo/info.xml) called at [lib/private/appframework/app.php:54]
```
This means `OC_App::getAppPath($appId)` returns an empty string (or something equivalent) in
https://github.com/owncloud/core/blob/master/lib/private/appframework/app.php#L52 which is suspicious. The root cause for the segfault is probably simpleXML not handling non-existing files properly.

### PR DESCRIPTION
**Pull request by bantu**
This should prevent the segfault we are seeing for the HHVM job on ci.owncloud.org.

Fix #16056
Ref #16118

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@bantu Unit tests need some love: 

```
OC\AppFramework\AppTest::testBuildAppNamespace
RuntimeException: Could not get path for app id someapp

/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/appframework/app.php:55
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/appframework/AppTest.php:112


OC\AppFramework\AppTest::testBuildAppNamespaceCore
RuntimeException: Could not get path for app id someapp

/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/appframework/app.php:55
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/appframework/AppTest.php:118

```

**Comment by bantu** [comment]
@MorrisJobke Probably this is a pre-existing issue only uncovered by this change. cc @Raydiation

**Comment by MorrisJobke** [comment]
> @MorrisJobke Probably this is a pre-existing issue only uncovered by this change. cc @Raydiation

I meant that you need to fix the code that is tested there, because this relies on "I can't open a file - okay fallback to something other" ;)

**Comment by bantu** [comment]
@MorrisJobke I see. I've changed the implementation.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
