### PR TITLE
[stable10] UI tests to add public link shares to remote server

### PR DESCRIPTION
**Pull request by individual-it**
backport of #29860 to stable10

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@individual-it no drone status reported - CI is not going to pass.
will need a rebase again

**Comment by DeepDiver1975** [comment]
> will need a rebase again

gimme a sec ....

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by DeepDiver1975** [comment]
rebase is better ....

**Comment by ownclouders** [comment]
Automated rebase was successful!

**Comment by individual-it** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase was successful!

**Comment by individual-it** [comment]
second rebase didn't trigger CI correctly, now its running again

**Pull request merged**
