### PR TITLE
Added test case about not seeing own shares reshared with them

### PR DESCRIPTION
**Pull request by SergioBertolinSG**

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
@phil-davis @individual-it there is a failure when using firefox:

Problem of the test or actual bug? 

   When I rename the folder "simple-folder" to one of these names # FilesContext::iRenameTheFileToOneOfThisNames()
      | simple/folder    |
      | .htaccess        |
      | simple\folder    |
      | \\simple/folder  |
      | ../simple-folder |
      Element is no longer attached to the DOM

**Comment by phil-davis** [comment]
There seem to be some timing conditions when the tests take some action and need to wait for the page to refresh/AJAX to respond... and if the sleep wakes up to check if the page is ready to progress but finds the page in some unfortunate transition state then this stale element reference http://www.seleniumhq.org/exceptions/stale_element_reference.jsp has been seen.
@individual-it has been looking today at how to make this more robust, as well as reducing the sleep times (to minimize wasted elapsed test time) - https://github.com/individual-it/owncloud-core/pull/20/files
I restart the job that got the error.
I don't expect there is any problem with your code or any other recent commit to master. Probably the UI test will pass this time - we will see.

**Comment by phil-davis** [comment]
It worked this time. We will be working to find all the annoying timing conditions in this sort of testing!

**Comment by SergioBertolinSG** [comment]
Great, thanks @phil-davis

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
please backport to 9.1 and 9.0

**Comment by SergioBertolinSG** [comment]
This Pr required a change: https://github.com/owncloud/core/pull/27998

backports in:
stable9.1 https://github.com/owncloud/core/pull/27997
stable9    https://github.com/owncloud/core/pull/27999 cherry picked in https://github.com/owncloud/core/pull/28000

**Pull request merged**
