### PR TITLE
Do not allow username to have whitespace at the beginning or at the end

### LINKED ISSUE #22035: do not allow to create a user with a space in its username
Currently with the web interface of OC 8.2.2 it is possible to create a user with a space at the beginning or the end of its user name. Someone would of course only do that by mistake but it is hard to notice, so IMHO owncloud should catch that. Or do you reall want to be able to create users with spaces inside their username?

### PR DESCRIPTION
**Pull request by vincchan**
fixes #22035

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @Xenopathic 

Shouldn't this be handle by the backend? or the user manager?

**Comment by nickvergessen** [comment]
Yes, I'd say so as well:
https://github.com/owncloud/core/blob/adf532fe4e45c529fd0f4a3605cc3e13762642a9/lib/private/user/manager.php#L250-L288

**Comment by vincchan** [comment]
@MorrisJobke @nickvergessen 

Can you please have another look at it. Should fix #20917 as well.

**Comment by MorrisJobke** [comment]
Looks good now - and works :+1:

**Comment by MorrisJobke** [comment]
@PVince81 @icewind1991 @blizzz Please review

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by LukasReschke** [comment]
CI execution is at https://github.com/owncloud/core/pull/22113

@vincchan Thanks a lot for the contribution. :rocket: You have contributor permissions now and can directly use a branch on our repository which allows direct execution of the unit tests :smile:

**Pull request merged**
