### PR TITLE
Allow domain to be specified for SMB

### LINKED ISSUE #13407: SMB_OC not passing domain through to samba share auth
smb_oc is passing through the username, but not the domain for the smb shares.
See: https://github.com/owncloud/core/blob/89db2a027701503ea758380b20b10ca7f5a244d9/apps/files_external/lib/smb_oc.php#L40

This causes mapping of external samba shares using domain authentication to fail.

Example of failed login:

```
session setup failed: NT_STATUS_LOGON_FAILURE params(-d 0 '//files.yourdomain.com/shared' -c 'ls') at /var/www/owncloud/apps/files_external/3rdparty/smb4php/smb.php#201
```

This is caused by trying to map the share named 'shared' with username rather than domain\username

hacking smb_oc.php to hard code the domain infront of the username fixes the issue, but obviously this needs to be added into the code properly.

```
        "user" => "mydomain\\$user",
```

My suggestion is to add the option to allow users to specify the domain they wish to prepend to smb users.

I am happy to provide testing if some code is provided?

cc/ @Xenopathic @PVince81

### LINKED ISSUE #17480: SMB-with OC-login not working in 8.10
Hi,

System Information: Debian 8.1
 uname -a
Linux aub-cloud 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

We are using owncloud as a frontend for our internal Windows Servers. When a user logs in, owncloud automaticaly connect the Shares set in the admin panel with the OC-Login. The users authenticate with there Microsoft Active-Directory Account. 

Till Version 8.04 I could do this by adding our domain in the Script smb_oc.php

```
public function __construct($params) {
		if (isset($params['host']) && \OC::$server->getSession()->exists('smb-credentials')) {
			$host=$params['host'];
			$this->username_as_share = ($params['username_as_share'] === 'true');

			$params_auth = json_decode(\OC::$server->getCrypto()->decrypt(\OC::$server->getSession()->get('smb-credentials')), true);
			
			$domain = "ourdomain.local\\";
			$user = \OC::$server->getSession()->get('loginname');
			$userincldomain = $domain . $user;
			$password = $params_auth['password'];

			$root=isset($params['root'])?$params['root']:'/';
			$share = '';

			if ($this->username_as_share) {
				$share = '/'.$user;
			} elseif (isset($params['share'])) {
				$share = $params['share'];
			} else {
				throw new \Exception();
			}
			parent::__construct(array(
				"user" => $userincldomain,
				"password" => $password,
				"host" => $host,
				"share" => $share,
				"root" => $root
			));
		} else {
			throw new \Exception();
		}
	}
```

Till 8.04 the App files_external use smb4php to connect to smb shares.
In owncloud 8.1 the App files_external now use icewind to connect to smb shares.
I tried to edit the smb_oc in the same way.

```
public function __construct($params) {
		if (isset($params['host'])) {
			$host = $params['host'];
			$this->username_as_share = ($params['username_as_share'] === 'true');

			// dummy credentials, unused, to satisfy constructor
			$user = 'foo';
			$password = 'bar';
			if (\OC::$server->getSession()->exists('smb-credentials')) {
				$params_auth = json_decode(\OC::$server->getCrypto()->decrypt(\OC::$server->getSession()->get('smb-credentials')), true);
				$domain = "ourdomain.local\\";
				$user = \OC::$server->getSession()->get('loginname');
				$userincldomain = $domain . $user;
				$password = $params_auth['password'];
			} else {
				// assume we are testing from the admin section
			}

			$root = isset($params['root']) ? $params['root'] : '/';
			$share = '';

			if ($this->username_as_share) {
				$share = '/' . $user;
			} elseif (isset($params['share'])) {
				$share = $params['share'];
			} else {
				throw new \Exception();
			}
			parent::__construct(array(
				"user" => $userincldomain,
				"password" => $password,
				"host" => $host,
				"share" => $share,
				"root" => $root
			));
		} else {
			throw new \Exception();
		}
	}

```

Login with this script gives heavy load on the apache process and many processes from smbclient

in Top for each mounted share one process is displayed.
```
smbclient -authentication-file=/proc/self/fd/3 //IP-to-smb-server-Share
```

Can't someone add a input field "domain" to the admin panel for external_files and add some stuff to the scripts? That would be great.

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
This adds an additional field in the SMB storage backend, 'Domain', which when specified is prepended to the username in the format `domain\username` before being handed off to the storage implementation.

This was implemented within the backend logic instead of directly in the SMB class, since these sort of pre-mounting parameter mangling is the usecase for the backends, and such logic shouldn't be in the mounting implementation.

Fixes #13407, fixes #17480 

cc @icewind1991 @PVince81 @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by PVince81** [comment]
I agree with the code, but it seems it breaks the windows smb test

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
@PVince81 I don't know why that would happen, the Windows SMB tests do not hit the domain logic at all, ever. Hopefully the retest will be all green. Please re-review?

cc @icewind1991

**Comment by Xenopathic** [comment]
Well, CI still seems broken. The good news is, since the linked issues are classed as bugs, this can be merged after feature freeze. But it would be nice to get some reviewers cc @icewind1991 @DeepDiver1975 @PVince81

**Comment by PVince81** [comment]
Does this need any migration logic to extract the domain part from user names, in case it was added in that field already before ?

**Comment by Xenopathic** [comment]
@PVince81 None at all, the domain can still continue to be specified as part of the username, but this approach also works with session credentials where the username cannot be manually set.

**Comment by PVince81** [comment]
:+1: then

**Comment by PVince81** [comment]
@DeepDiver1975 force push to make retrigger scrutinizer ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 force push to make retrigger scrutinizer ?

no push please - not for scrutinizer

**Comment by mmattel** [comment]
:+1:   

@Xenopathic can you do a update at the documentation too?

https://github.com/owncloud/documentation/blob/master/admin_manual/configuration_files/external_storage_configuration_gui.rst#smbcifs

https://github.com/owncloud/documentation/blob/master/admin_manual/configuration_files/external_storage_configuration.rst#smb

**Comment by Xenopathic** [comment]
@mmattel To be honest, I think with all the changes the documentation for the admin storages GUI will have to be nearly completely rewritten. I'll get to work on it some time this or next week

**Pull request merged**
