### PR TITLE
Document the config of the activity app

### PR DESCRIPTION
**Pull request by nickvergessen**
@MorrisJobke @michaelstingl @carlaschroder @cdamken

### CODE REVIEW

**Comment by nickvergessen** [comment]
@karlitschek should backport down to stable7 where this config was added?

**Comment by karlitschek** [comment]
yes. backport would be good :+1:

**Comment by DeepDiver1975** [comment]
to me this is so wrong - why shall we maintain app specific config options in core?

**Comment by karlitschek** [comment]
@DeepDiver1975 true. But what other alternative do we have. ;-)

**Comment by nickvergessen** [comment]
Well the problem here is, that the config was added as a sys-config. So its not in the appconfig table. Putting it into the table would mostlikly require a UI, or can we expect people to run a query manually?

**Comment by DeepDiver1975** [comment]
app specific configs are to be documented in the app somewhere - e.g. in the README.md.

**Comment by nickvergessen** [comment]
Replaced with https://github.com/owncloud/documentation/pull/988

**Pull request closed without merging**
