### PR TITLE
Update lost password email to use HTML link

### PR DESCRIPTION
**Pull request by joeyberkovitz**
## Description

Update the lost password email to send both HTML and plain text versions so that URL in email can be clicked.

## Related Issue

https://github.com/owncloud/core/issues/30742

## Motivation and Context

Solve issue https://github.com/owncloud/core/issues/30742

## How Has This Been Tested?

Update associated tests to add HTML support.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks a lot for this PR!

Please note that some of these templates are customizable so I'm not sure if relying on "strip_tags" here would fit all scenarios.

A better way would be to use the same approach like for other emails: there are two template files, one called "mail.php" (for HTML) and "altmail.php" (for plain text). So here I suggest to do the same and have "core/templates/lostpassword/email.php" be the HTML email and create a new template "core/templates/lostpassword/altemail.php" with the plain text version.

Then wire this up with the code.

**Comment by joeyberkovitz** [comment]
Sure.
I added a plain text template as you recommended.
I also updated both templates to be consistent with the format of the other email templates.

**Review by PVince81 — APPROVED** [review]
Tested, works :+1: 

cc @phil-davis @individual-it to include in acceptance tests

**Comment by PVince81** [comment]
Hmm just noticed an extra ">" at the end of the HTML mail:
image

That one doesn't appear for other mails.

@joeyberkovitz mind verifying the markup ? I had a quick look but wasn't able to spot it

**Comment by joeyberkovitz** [comment]
That's odd because I don't see the ">" in the source or in the email it sends out from my system, which is up to date with the Git repository. I'll try to debug some more later.
owncloud_lost_email

**Comment by joeyberkovitz** [comment]
I cloned the repository into a separate directory and reinstalled Owncloud.
I wasn't able to reproduce the extra ">" using two different SMTP servers.
The only thing I did notice is that since the image is added by URL rather than being included, when mail clients like gmail try to pre-render the image, it'll fail if the URL isn't public. That might be a different issue though because it affects all of the existing email templates.

**Comment by PVince81** [comment]
Thanks for confirming. Then maybe it was a bug in Mailhog's HTML renderer.

**Comment by PVince81** [comment]
Mind backporting this to the stable10 branch ? Basically branch off stable10, cherry-pick your commits then submit PR to stable10 after checking it still works.

**Comment by joeyberkovitz** [comment]
I created the backport PR

**Comment by phil-davis** [comment]
Backport stable10 #31144

**Comment by individual-it** [comment]
@paurakhsharma is working on acceptance tests in #31168

**Pull request merged**
