### PR TITLE
Check for PHP configuration before executing unit tests

### PR DESCRIPTION
**Pull request by LukasReschke**
Dirty hack… If somebody has a better idea: Go for it ;-)
Ref https://github.com/owncloud/core/issues/13681#issuecomment-75307601

### CODE REVIEW

**Comment by LukasReschke** [comment]
Please test properly locally… Works on my systems… But considering the myriads of possible configurations…

**Comment by DeepDiver1975** [comment]
We could put this into bootstrap.php from my understanding. 

Furthermore (kind of OT) we should redirect everything which is written to the logs to console somehow.

Finally ./occ setup would be great.

**Comment by LukasReschke** [comment]
No idea how to redirect something to the console output :see_no_evil: 

Also you can't invoke anything here at this point which includes base.php - base.php madness.

**Comment by DeepDiver1975** [comment]
> Also you can't invoke anything here at this point which includes base.php - base.php madness.

https://github.com/owncloud/core/pull/14413

**Comment by DeepDiver1975** [comment]
> Also you can't invoke anything here at this point which includes base.php - base.php madness.

we need to have a base.php which throws exception in case something is fuxxed

**Comment by LukasReschke** [comment]
Agreed. Anyways, let's close this in favour of https://github.com/owncloud/core/pull/14413 for now. Thanks - much better approach :smile:

**Pull request closed without merging**
