### PR TITLE
[tests-only] test issue 35974

### PR DESCRIPTION
**Pull request by phil-davis**
Related issue: #35974

### CODE REVIEW

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiTrashbin-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/30741/4/13
The test show 2 different behaviors:
1) The file still has "PARENT file content" - the restore from trashbin did nothing, the original text is still in the file or
2) The file has the expected restored content "file to delete" and the over-written file is in the trashbin.

They each happen about 50% of the time.

Behavior (2) seems the most reasonable one.

https://drone.owncloud.com/owncloud/core/30743/4/13
The scenario is now written to expect behavior (2). That is passing abut 50% of the time.
And 50% of the time the content of the file has not been restored - the original content is still there.

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiTrashbin-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiTrashbin-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/30744/4/13
That is another variation of behavior (2) - this time it exxpects both of:
a) the previous content is in the trashbin
b) the restored content is in the file

(a) is maybe not a requirement - we do not normally put an old "version" in the trashbin when it is overwritten by new content. We would usually save it in "versions"

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiTrashbin-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>apiTrashbin-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/30747/4/13
I put extra `sleep(5)` before the checks in `Then` steps and still the same result - about half the time the updated content gets restored, and half the time not. So it does not seem to be a test timing issue.

**Comment by phil-davis** [comment]
This demonstrates that the issue is still happening.

**Pull request closed without merging**
