### PR TITLE
Remove useless margin when trashbin is disabled

### LINKED ISSUE #16244: Sidebar broken layout if "deleted files" is disabled
If "deleted files" is disabled "Shared by link" is no longer align to the other side bar entries, see attached screenshot:

cc @jancborchardt

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/16244

Please review @owncloud/designers @oparoz @rullzer @schiesbn @nickvergessen

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Change looks good. Tested with Firefox, Chromium and IE8 :+1:

**Comment by MorrisJobke** [comment]
cc @Henni easy to review :)

**Comment by schiesbn** [comment]
> Tested with Firefox, Chromium and IE8

tested with iceweasel 41 :wink:  ... works :+1: 

@PVince81 I complete forgot this issue... Thanks for fixing it!

**Comment by karlitschek** [comment]
:+1:

**Comment by jancborchardt** [comment]
As it says in the code comment, that code is necessary so there is a scrollbar on small displays for the last navigation entry. Otherwise that gets obscured by the Deleted files entry:
capture du 2015-10-12 14-04-56


As I said in issue #16244:

> This is because »Deleted files« is not the last entry in the list. Can you make it so it is?

Deleted files needs to be the last entry in the list, in the DOM.

**Comment by MorrisJobke** [comment]
@PVince81 What about putting this rule into the files_trashbin CSS? ;)

**Comment by PVince81** [comment]
Good idea

**Comment by PVince81** [comment]
Superseded by https://github.com/owncloud/core/pull/19702

**Pull request closed without merging**
