### PR TITLE
Improve code occ files_external:list --short

### PR DESCRIPTION
**Pull request by mmattel**
## Description

This PR improves the code for the `--short` option in occ command `files_external:list`
- removing unnecessary double code paths - make one code stream for:
standard output and json output
- greatly improving the array handling by using if statemens instead looping thru arrays
- better output of `--all` and if a `user` is given 

## Related Issue

- Fixes https://github.com/owncloud/core/pull/32178#issuecomment-451386297

## Motivation and Context

Better code, easier to handle and enhance. Better output

## Screenshots (if appropriate):
**Commands**
```
sudo -uwww-data ./occ files_external:list -s 
+----------+-------------+------------------+-------------------+------+-------+
| Mount ID | Mount Point | Applicable Users | Applicable Groups | Auth | Type  |
+----------+-------------+------------------+-------------------+------+-------+
| 2        | /test       | user_x           | admin, testg      | User | Admin |
+----------+-------------+------------------+-------------------+------+-------+

sudo -uwww-data ./occ files_external:list -s user_y
+----------+---------------+------+----------+
| Mount ID | Mount Point   | Auth | Type     |
+----------+---------------+------+----------+
| 1        | /martin@filer | User | Personal |
+----------+---------------+------+----------+

sudo -uwww-data ./occ files_external:list -s -a
+----------+---------------+------------------+-------------------+------+----------+
| Mount ID | Mount Point   | Applicable Users | Applicable Groups | Auth | Type     |
+----------+---------------+------------------+-------------------+------+----------+
| 1        | /martin@filer | user_y           |                   | User | Personal |
| 2        | /test         | user_x           | admin, testg      | User | Admin    |
+----------+---------------+------------------+-------------------+------+----------+
```

**Auth**
This new field shows if a mount is based on User/Pwd (User) or Session (Session).
This info is important when using files:scan as session based mounts cant be scanned by occ.

The output of json is tested and correct to the plain one

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by mmattel** [comment]
@sharidas can you help fixing the tests ?

**Comment by mmattel** [comment]
Commit `improve code` improves the following:

**Improved helptext**
```
Arguments:
  user_id                User id to list the personal mounts for, if no user is provided admin mounts will be listed

Options:
      --show-password    Show passwords and secrets
      --full             Don't truncate long values in table output
  -a, --all              Show mounts for all users. All has precedence over user_id
  -s, --short            Show only a reduced mount info
      --output[=OUTPUT]  The output format to use (plain, json or json_pretty). [default: "plain"]
```
**Commands**
```
sudo -uwww-data ./occ files_external:list -s 
+----------+-------------+------------------+-------------------+------+-------+
| Mount ID | Mount Point | Applicable Users | Applicable Groups | Auth | Type  |
+----------+-------------+------------------+-------------------+------+-------+
| 2        | /test       | user_x           | admin, testg      | User | Admin |
+----------+-------------+------------------+-------------------+------+-------+

sudo -uwww-data ./occ files_external:list -s user_y
+----------+---------------+------+----------+
| Mount ID | Mount Point   | Auth | Type     |
+----------+---------------+------+----------+
| 1        | /martin@filer | User | Personal |
+----------+---------------+------+----------+

sudo -uwww-data ./occ files_external:list -s -a
+----------+---------------+------------------+-------------------+------+----------+
| Mount ID | Mount Point   | Applicable Users | Applicable Groups | Auth | Type     |
+----------+---------------+------------------+-------------------+------+----------+
| 1        | /martin@filer | user_y           |                   | User | Personal |
| 2        | /test         | user_x           | admin, testg      | User | Admin    |
+----------+---------------+------------------+-------------------+------+----------+
```

**Auth**
This new field shows if a mount is based on User/Pwd (User) or Session (Session).
This info is important when using files:scan as session based mounts cant be scanned by occ.

@sharidas

**Comment by davitol** [comment]
Tested and the behavior is like commented in https://github.com/owncloud/core/pull/34033#issuecomment-454898381

IMHO, behavior should be like commented in https://github.com/owncloud/core/pull/34033#issuecomment-452611484 . From the user perspective who executes this command, I would expect the no mounts configured for user1 when using -a option. Anyway, now it is documented in the help with ```Show mounts for all users. All has precedence over user_id```

**Comment by PVince81** [comment]
Seems this implementation aligns with how `occ files:scan --all user1` works, so let's keep it for consistency.

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by PVince81** [comment]
@mmattel please run `make test-php-style-fix`

**Comment by mmattel** [comment]
@PVince81 Question:
updating master, running `make clean` and `make` rebasing this PR and running `make test-php-style-fix` I get following error message:
```
composer bin owncloud-codestyle install --no-progress
                                 
  [InvalidArgumentException]     
  Command "bin" is not defined.  
                                 

Makefile:364: recipe for target 'vendor-bin/owncloud-codestyle/vendor' failed
make: *** [vendor-bin/owncloud-codestyle/vendor] Error 1
```
Any ideas ?

**Comment by phil-davis** [comment]
What to say? I just did 
```
git fetch origin
git checkout master
git pull
make clean
make
make test-php-style
```
and it works hard for a while loading loads of dependencies for ``make`` and then for ``make test-php-style`` and finally it runs the style tests:

```
Changed current directory to vendor-bin/php_codesniffer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing squizlabs/php_codesniffer (3.4.0): Loading from cache
Writing lock file
Generating autoload files
php -d zend.enable_gc=0 vendor-bin/owncloud-codestyle/vendor/bin/php-cs-fixer fix -v --diff --diff-format udiff --allow-risky yes --dry-run
Loaded config ownCloud coding standard from "/home/phil/git/owncloud/core/.php_cs.dist".
Using cache file ".php_cs.cache".
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Checked all files in 29.321 seconds, 28.000 MB memory used
vendor-bin/php_codesniffer/vendor/bin/phpcs --runtime-set ignore_warnings_on_exit --standard=phpcs.xml tests/acceptance tests/TestHelpers
............................................................  60 / 107 (56%)
...............................................              107 / 107 (100%)


Time: 7.6 secs; Memory: 26MB

php build/OCPSinceChecker.php
Parsing all files in lib/public for the presence of @since or @deprecated on each method...
```

in hte ``make`` it should be getting:
```
  - Installing bamarni/composer-bin-plugin (v1.2.0): Loading from cache
```
that is the magic thing that makes the ``composer bin`` command exist.

**Comment by mmattel** [comment]
I have updated the PR, run php-style-fix, added tests, squashed the commits

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@mmattel please backport

**Pull request merged**
