### PR TITLE
Prevent null to be passed into the closure of callForAllUsers

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs https://github.com/owncloud/core/issues/23759#issuecomment-205708642

### CODE REVIEW

**Comment by nickvergessen** [comment]
Right, I had code in my closure for that:
```php
			if (!($user instanceof IUser)) {
				// In case we get null
				return;
			}
```

:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MorrisJobke** [comment]
@karlitschek @DeepDiver1975 What about the backport request?

**Comment by karlitschek** [comment]
@DeepDiver1975 What do you think?

**Comment by DeepDiver1975** [comment]
yeah - should be backported ....

**Comment by DeepDiver1975** [comment]
will prepare pr

**Pull request merged**
