### PR TITLE
ellipsize long group names in select2 dropdown, fix #16977

### LINKED ISSUE #16977: List of users and groups does not render correctly when there is a group with a long name
### Steps to reproduce

1. Install 8.1 
2. create a group with a long name 
3. enable external storage
4. configure an external storage and select a group

### Expected behaviour

Drop down list of users and groups display correctly

### Actual behaviour

Drop down list of users and groups does not display correctly

p359

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-15T03:10:33+00:00 fe9b28a800514315eba17ac5da84b8b93abd9ffc

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #16977 by adding an ellipsis to the select2 entries if they get too long.

Please test @jnfrmarks @PVince81 @owncloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works in Firefox and Chrome :+1:

**Comment by nickvergessen** [comment]
@jancborchardt jnfrmarks is not QA anymore. @rperezb is now

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
Even works in IE8, kudos!

**Pull request merged**
