### PR TITLE
Replace share proxy with a hook

### PR DESCRIPTION
**Pull request by icewind1991**
No need to use a proxy for this.

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Better have @schiesbn double check, there might have been a reason

**Comment by DeepDiver1975** [comment]
@schiesbn please review - we need to kill the file proxy - THX

**Comment by schiesbn** [comment]
There was a good reason why I moved this to a proxy. But I can't really remember what it was, let me sleep a weekend over it :wink: 

I have the feeling that it was because of the trashbin, to make sure that first the trashbin creates a copy and then we remove the mount point. But because we moved the trashbin already to a stream wrapper this might no longer be an issue. Or at least it doesn't make a difference now.

**Comment by PVince81** [comment]
#### Tests
- [x] delete folder containing outgoing shares (files moved to trashbin)
- [x] delete folder containing incoming shares
- [x] unshare from self a folder as recipient
- [x] delete folder inside share as owner (files moved to trashbin)
- [x] delete folder inside share as recipient (files moved to trashbin)

Everything seems to work fine :+1:

**Comment by PVince81** [comment]
#### Tests
- [x] delete folder containing outgoing shares (files moved to trashbin)
- [x] delete folder containing incoming shares
- [x] unshare from self a folder as recipient
- [x] delete folder inside share as owner (files moved to trashbin)
- [x] delete folder inside share as recipient (files moved to trashbin)

Everything seems to work fine :+1:

**Comment by PVince81** [comment]
Please rebase.

@schiesbn can you confirm that this fix is safe ?

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
