### PR TITLE
Fix 500 when uploading in to share without write/edit permissions #33416

### PR DESCRIPTION
**Pull request by IljaN**
Forward port of #33640

### CODE REVIEW

**Comment by IljaN** [comment]
Might need additional work as encryption is now removed from core, lets see if CI passes

**Review by PVince81 — APPROVED** [review]
:+1:

codecov report likely broken, from what I see the touched code is covered, merging

**Comment by PVince81** [comment]
@IljaN please backport

**Comment by phil-davis** [comment]
Backport ``stable10`` #33640

**Pull request merged**
