### PR TITLE
[master] Bump icewind/smb from 1.1.0 to 2.0.4 in /apps/files_external…

### PR DESCRIPTION
**Pull request by mmattel**
…/3rdparty

Bumps [icewind/smb](https://github.com/icewind1991/SMB) from 1.1.0 to 2.0.4.
- [Release notes](https://github.com/icewind1991/SMB/releases)
- [Commits](https://github.com/icewind1991/SMB/compare/v1.1.0...v2.0.4)

## Description

@dependabot created the originally PR to stable10 but not to master.
This PR is the master version and the basis for testing
stable10 PR: https://github.com/owncloud/core/pull/30212

## Motivation and Context

The upgrade fixes the anonymous login issue, see https://github.com/owncloud/core/issues/30153#issuecomment-358909754 and following

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> @dependabot created the originally PR to stable10 but not to master.

seems to be an issue with the bot - reported here - THX https://github.com/dependabot/feedback/issues/90

**Comment by DeepDiver1975** [comment]
oh - wait .... what do we have here .... https://github.com/owncloud/core/pull/29905

**Comment by patrickjahns** [comment]
As discussed here: https://github.com/owncloud/core/pull/30212#issuecomment-363851833

Also not sure if merging into master is the right time now. As stated - we need to allocate QA resources to properly test changes and possible side effects.

**Comment by mmattel** [comment]
This one can be closed, dependabot created a correct one...
But just for the record ... the update fixes the anonymous access issue, see #30153 (comment) and following.

**Pull request closed without merging**
