### PR TITLE
Add setup check for overwrite.cli.url setting

### LINKED ISSUE #29606: Setup check for overwrite.cli.url
When installing from occ, usually the URL might not be set correctly. The CLI cannot detect the true domain.

I suggest to have a setup check that does the following:
1) Generate a URL on the backend using the APIs, the APIs will use whatever values are set `overwrite.cli.url` or others when needed.
2) Return said value to the setup check JS code
3) JS code connects to that URL and appends "status.php"
4) If no status.php found, then it's likely the URL is wrong and needs adjusting.

Bonus check: if the given URL contains a domain not listed in trusted_domains, also display a warning.

Inspired by questions from @settermjd.

cc @kdslkdsaldsal @butonic @DeepDiver1975 @cdamken

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Checks that "overwrite.cli.url" is set and is usable by calling status.php.
If no status.php response, displays a warning message in setup checks section in settings page.

## Related Issue
Fixes https://github.com/owncloud/core/issues/29606

## How Has This Been Tested?
- [x] TEST: when not set at all, message appears
- [x] TEST: when set to wrong URL, message appears
- [x] TEST: when set to correct URL, no message

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## TODO:
- [ ] double check how the CLI URL influences notification URLs. it seems that when it's not set it still works fine, but might not work in all scenarios. (needed to decide whether to keep the warning when it's not set)
- [ ] add unit tests

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
tests need some love

**Comment by PVince81** [comment]
> tests need some love

yes, but before that I need to finish my TODOs... there is some unclarity there about expectation

**Comment by PVince81** [comment]
Hmm, apparently the notifications URL is not affected by "overwrite.cli.url", however it's influenced by "overwritehost". So we'll likely need to add a second check using the same routing code.

**Comment by PVince81** [comment]
Another problem: if the `overwrite*` settings are pointing to another domain, then we can't test it unless the current OC is being opened in the same domain.

**Comment by PVince81** [comment]
doesn't work as expected, closing due to lack of time

**Pull request closed without merging**
