### PR TITLE
Add per-user storage view

### PR DESCRIPTION
**Pull request by pako81**
## Description
Add per-user storage view

## Related Issue
- https://github.com/owncloud/enterprise/issues/5468

## Motivation and Context
Make possible to visualise used storage on per-user basis

## How Has This Been Tested?
- Access ~/settings/users URL. A new column `Storage Used` will display the amount of used storage for every user. This option can be also opted in/out under `Settings` in order to align with all other available users' options.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised
- [X] Changelog item

### CODE REVIEW

**Comment by pako81** [comment]
This is a follow-up of https://github.com/owncloud/core/pull/40477

**Comment by phil-davis** [comment]
Note: this touches the same code areas as #40588 - we need to merge one of these, then make sure to rebase the other and test it again.

**Comment by phil-davis** [comment]
@pako81 the branch for this in your repo https://github.com/pako81/core has disappeared.

**Comment by pako81** [comment]
@phil-davis thanks for noticing it, the branch was deleted by mistake. Let's wait for https://github.com/owncloud/core/pull/40588 to get merged and I will then open a new PR on a new branch in core repo for this one. This will not anyway be in 10.12.0 so we have some time.

**Comment by pako81** [comment]
Closing this in favour of https://github.com/owncloud/core/pull/40657

**Pull request closed without merging**
