### PR TITLE
[backport] [stable8.2] if a user that is flag as deleted shows up again, remove that flag. F…

### PR DESCRIPTION
**Pull request by blizzz**
…ixes #20090 

Backport of https://github.com/owncloud/core/pull/20192 to stable8.2

Please test and review @pierrejochem @Venice-89 @Xenopathic @davitol @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by blizzz** [comment]
Need one more reviewer, maybe @PVince81 @ryno83 or others

**Comment by PVince81** [comment]
Tested, works as advertised :+1:

**Comment by davidak** [comment]
Is the included in the 8.2.1 release? I installed it and get this error.

**Comment by blizzz** [comment]
Yes, it is. You should update to 8.2.4 nevertheless.

**Comment by davidak** [comment]
8.2.4 still has this bug, ldap is not usable https://github.com/owncloud/core/pull/24498

Which 8.x version is usable with ldap? I recognize 8.2.0 to be working. Do i have to use that for a fresh install now if i want to use ldap? (i can't wait for 8.2.5, the customer needs it today)

**Comment by MorrisJobke** [comment]
> 8.2.4 still has this bug, ldap is not usable #24498

We have multiple setups of 8.2.3+ with LDAP that all work just fine. Please open a new ticket with detailed infos, what is not working and possible log entries.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/24498 is an unmerged PR. If that one works for you you could patch your instance until 8.2.5 is out.

**Comment by blizzz** [comment]
@davidak #24498 is unrelated to this one here. #24498 is a backport that still needs to be merged to 8.2. It helps if you can test it and report back on that PR :)

**Comment by davidak** [comment]
@MorrisJobke fresh installed 8.2.4: `Call to a member function processAttributes() on a non-object at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#723`

fresh installed 8.2.1: `Call to a member function processAttributes() on a non-object at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#717`

looks exactly like this bug to me.

i will install 8.2.0 since i know it works. we won't support owncloud any further after that. i have done what i could, sorry.

**Pull request merged**
