### PR TITLE
Add Imprint and Privacy Policy to getShortFooter()

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Add imprint and privacy policy links in the global footer

## Related Issue
https://github.com/owncloud/enterprise/issues/2537

## How Has This Been Tested?
Visual tests in FF, Chrome & IE11 on
- login page footer
- public link page footer
- full screen error page footer

## Screenshots (if appropriate):
fireshot capture 26 - owncloud - http___localhost_8000_index php_s_a1jbqp5smbmjlap

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
``make test-php-style`` enforces braces for ``if`` statements, even "if" there is just a single line of code. IMO this is "a good thing"  as it avoids future problems when people add more lines that are intended to be inside the ``if`` block.
I quickly fixed it with commit 3.

**Comment by phil-davis** [comment]
Code works for me - I can define the imprint and privacy links in Admin Settings General and they show and work on the login page.

**Review by PVince81 — DISMISSED** [review]
:+1:

**Comment by PVince81** [comment]
Let's add unit tests, as I see the class should be unit-testable. Need to write it from scratch.

- [ ] add unit tests

**Comment by PVince81** [comment]
@VicDeo can you bootstrap and add the theme related unit tests for the OC_Defaults part ?

**Comment by felixheidecke** [comment]
> Let's add unit tests …

Better not me. Will take hours.
Updated initial post.

**Review by PVince81 — APPROVED** [review]
Thanks, guys ! :+1: 

@felixheidecke can you backport ?

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/31730

**Comment by PVince81** [comment]
regression: https://github.com/owncloud/core/issues/31741

**Pull request merged**
