### PR TITLE
Do not restrict permissions for the original owner

### LINKED ISSUE #15771: "Shared with you and the group {group} by {owner}" displayed for owner
### Steps to reproduce

1. Create a folder
2. Create a file inside the folder
3. Share the folder with a group you are in and remove all permissions
4. Open the share dialog of the file

### Expected

The file can be shared normally

### Actual

`Shared with you and the group {group} by {owner}` is displayed at the top of the share dropdown.
Also the file can not be shared because "resharing is not allowed"

### Fix
```js
		if (data !== false &amp;&amp; data.reshare !== false &amp;&amp; data.reshare.uid_owner !== undefined) {
			if (data.reshare.share_type == OC.Share.SHARE_TYPE_GROUP) {
				html += '&lt;span class="reshare">'+t('core', 'Shared with you and the group {group} by {owner}', {group: data.reshare.share_with, owner: data.reshare.displayname_owner})+'&lt;/span>';
			} else {
				html += '&lt;span class="reshare">'+t('core', 'Shared with you by {owner}', {owner: data.reshare.displayname_owner})+'&lt;/span>';
			}
			html += '&lt;br />';
			// reduce possible permissions to what the original share allowed
			possiblePermissions = possiblePermissions &amp; data.reshare.permissions;
		}
```
the block is missing a check whether `data.reshare.uid_owner` is the current owner

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #15771 

``` js
            // reduce possible permissions to what the original share allowed
            possiblePermissions = possiblePermissions & data.reshare.permissions;
```

was wrongly called for the owner.

We should write a test for this, if someone can help me through the shareSpec.js that would be nice

### CODE REVIEW

**Comment by nickvergessen** [comment]
@rullzer can you (help to) add a js unit test for this?

**Comment by PVince81** [comment]
@nickvergessen added JS unit test

**Comment by PVince81** [comment]
:+1: for your fix

**Comment by nickvergessen** [comment]
I verified that the test fails without the patch:
```
PhantomJS 1.9.8 (Linux) OC.Share tests dropdown share permissions resharing allows owner to share their own share when they are also the recipient FAILED
	Expected 0 to equal 1.
	Error: Expected 0 to equal 1.
	    at /home/nickv/ownCloud/master/core/core/js/tests/specs/shareSpec.js:796
```

:+1:

**Comment by rullzer** [comment]
So the javascript now works. But I still get an error because the logic in the share.php also fails to handle this properly.

**Comment by DeepDiver1975** [comment]
> But I still get an error because the logic in the share.php also fails to handle this properly.

@nickvergessen can you have a look at this please? THX

**Comment by nickvergessen** [comment]
Yeah, I'm just catching up from yesterday sorry

**Comment by DeepDiver1975** [comment]
> Yeah, I'm just catching up from yesterday sorry

no worries - thx

**Comment by nickvergessen** [comment]
I don't feel to comfortable in the share.php code, maybe @schiesbn or @rullzer is better fixing it there?

**Comment by PVince81** [comment]
nobody feels comfortable in share.php code, especially `getItems` :wink:

**Comment by nickvergessen** [comment]
It's not `getItems` but `checkReshare` https://github.com/owncloud/core/blob/1c1013d7c1210f75336b1add199aaf1bdd8a586b/lib/private/share/share.php#L2083-L2103

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
@owncloud-bot retest this please

**Comment by nickvergessen** [comment]
Fixed the php side aswell. 

After writing the test, I first had to fix a problem with the query that selects parent group shares: https://github.com/owncloud/core/commit/3c37cbdfe7eb29db30dc5b9b62b7430f19419412
https://ci.owncloud.org//job/pull-request-analyser-ng-simple/11890/

```
Test_Share::testSharingAFolderThatIsSharedWithAGroupOfTheOwner
Undefined index: path

/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/apps/files_sharing/lib/share/folder.php:42
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/share/share.php:1821
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/share/share.php:426
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/share/share.php:2093
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/share/share.php:1896
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/share/share.php:777
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/public/share.php:262
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/share/share.php:527
```

Afterwards the test was finally failing as expected:
```
Stacktrace

Test_Share::testSharingAFolderThatIsSharedWithAGroupOfTheOwner
Exception: Sharing 46 failed, because resharing is not allowed

/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/share/share.php:2137
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/share/share.php:1896
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/private/share/share.php:777
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/lib/public/share.php:262
/var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/share/share.php:527
```

And could then be fixed: https://github.com/owncloud/core/commit/f524ae261ae53b7d3ea88f952ad29d72eb48dcb4

**Comment by nickvergessen** [comment]
Please review @PVince81 @rullzer @schiesbn

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by schiesbn** [comment]
Tested, works as expected... Code looks good too :+1:

**Comment by nickvergessen** [comment]
@DeepDiver1975 @karlitschek please approve/deny backport

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 @karlitschek please approve/deny backport

Ping

**Comment by karlitschek** [comment]
please back port after 8.0.4 is out of the door

**Comment by MorrisJobke** [comment]
@nickvergessen please backport ;)

**Comment by nickvergessen** [comment]
Backport available at #17158

**Pull request merged**
