### PR TITLE
[stable10] Backport of resetpassword command supports send password r…

### PR DESCRIPTION
**Pull request by sharidas**
…eset link and display link

The resetpassword supports options to
1) display the password reset link in command line.
2) send email to reset the password for user and
   display the link in the command line.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

Update `user:resetpassword` with options `--send-email` and `--output-link`. Where `--send-email` would send email to the user if email is configured and displays the reset link in the command line. The `--output-link` will just display the link in the command line.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/29542

## Motivation and Context

Update `user:resetpassword` with options `--send-email` and `--output-link`. Where `--send-email` would send email to the user if email is configured and displays the reset link in the command line. The `--output-link` will just display the link in the command line.

## How Has This Been Tested?

- Create a user `user1`
- Update the config.php `overwrite.cli.url` with the proper url. By default it points to `http://localhost`. Provide the url which makes user land in the long in page.
- Update config.php with the smtp settings or user can configure from UI
- execute `./occ user:resetpassword --send-email user1`, an email will be sent to users email address and a password reset link will be displayed on the command line.
- execute `./occ user:resetpassword --send-email --output-link user1`, will give same result as above
- execute `./occ user:resetpassword --output-link user1`, will give the password reset link in the command line ( no email will be sent ).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by sharidas** [comment]
Original PR: https://github.com/owncloud/core/pull/32345

**Comment by PVince81** [comment]
@sharidas please investigate:
```
1) Tests\Core\Command\User\ResetPasswordTest::testDisplayLink
Error: Call to a member function with() on null

/drone/src/tests/Core/Command/User/ResetPasswordTest.php:127

2) Tests\Core\Command\User\ResetPasswordTest::testEmailLink
Error: Call to a member function with() on null

/drone/src/tests/Core/Command/User/ResetPasswordTest.php:166
```

**Comment by sharidas** [comment]
Updated. The CI should pass now.

**Comment by PVince81** [comment]
@sharidas what did you change ? since you squashed the commits I can't see it

**Comment by sharidas** [comment]
> what did you change ? since you squashed the commits I can't see it

Previously in the unit test method `testDisplayLink` had line :
```
$this->lostController->method('generateTokenAndLink')
			->with('foo')
			->willReturn(['http://localhost/foo/bar/123AbcFooBar/foo', '123AbcFooBar']);
```

was changed to 
```
$this->lostController->expects($this->once())
			->method('generateTokenAndLink')
			->with('foo')
			->willReturn(['http://localhost/foo/bar/123AbcFooBar/foo', '123AbcFooBar']);
```
Basically `expects()` was added.

Similarly in method `testEmailLink()` the line :
```
$this->lostController->method('generateTokenAndLink')
			->with('foo')
			->willReturn(['http://localhost/foo/bar/123AbcFooBar/foo', '123AbcFooBar']);
		$this->lostController->method('sendEmail')
			->with('foo', '123AbcFooBar', 'http://localhost/foo/bar/123AbcFooBar/foo');
```
was changed to
```
$this->lostController->expects($this->once())
			->method('generateTokenAndLink')
			->with('foo')
			->willReturn(['http://localhost/foo/bar/123AbcFooBar/foo', '123AbcFooBar']);
		$this->lostController->expects($this->once())
			->method('sendEmail')
			->with('foo', '123AbcFooBar', 'http://localhost/foo/bar/123AbcFooBar/foo');
```

i.e, added `expects`.

**Comment by PVince81** [comment]
@sharidas so this needs changes for master as well ?

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
how come ?

**Pull request merged**
