### PR TITLE
Prevent password removal if it is enforced

### PR DESCRIPTION
**Pull request by lordelix**
## Description

Prevent users from removing a password from a link share if it is enforced.

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/2371

## How Has This Been Tested?

 - Manual testing on latest Chrome on macOS
 - Manual testing on latest Firefox on macOS

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by felixheidecke** [comment]
The issue was, that the model is being saved and the validation is being handled by the server. The date then wasn't being transformed into the right format and things got weird. So I just added a check on password removal that prevents the save.

Please test.

**Comment by PVince81** [comment]
@felixheidecke please test this yourself. Ideal is if you list the scenarios that you have tested, as originally intended by the "how did you test this"

**Comment by felixheidecke** [comment]
@PVince81 I updatet the description above. (Currently, have no means to test on other OS/Browsers.)

**Comment by PVince81** [comment]
@felixheidecke update the JS unit tests ?

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by felixheidecke** [comment]
@phil-davis one Webui-acceptance-test fails _"test resharing folder as readonly and set it as readonly by resharer"_ but I see no reason that my code changes f****ed up the UI. Do you have any Ideas what's going on there?

**Comment by phil-davis** [comment]
There were problems since last Friday with some JS component bumps that were merged to core stable10 and broke sharing on the webUI. That got into the QA tarball and... The federation tests use a federated server running whatever is the stable10 QA tarball. So federated sharing tests started failing because the combination of "local server" master plus "federated server" stable10 was broken.

The component bumps were reverted yesterday. Rebase and it will pass.

**Comment by felixheidecke** [comment]
@phil-davis … nice, thx. Will do.

**Comment by PVince81** [comment]
@felixheidecke please backport

**Comment by phil-davis** [comment]
Backport `stable10` #34497

**Pull request merged**
