### PR TITLE
Change small thumbnails to 32 px

### LINKED ISSUE #16913: Decide which size should be used for thumbnails and stick to it
With a devicePixelRatio of 1, the web GUI is asking for 36x36 thumbnails, but the CSS used to display those thumbnails has a hardcoded value of 32px.

Maybe some parts of the GUI need the 36x36 thumbnails and it's been designed that way in order to not have to generate both sizes. If not, we should decide whether there is room to show the 36x36 thumbnails or if we should ask for 32x32 thumbnails instead and fix all the scripts which ask for 36x36 thumbnails.

@jancborchardt  @schiesbn @PVince81 @nickvergessen

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #16913
- fixes issues in IE8 where the thumbnail is too big

All current previews are resized by CSS (`background-size: 32px`) which cause the issues with IE8.

cc @oparoz @PVince81 @georgehrke

### CODE REVIEW

**Comment by oparoz** [comment]
I would also get rid of `background-size: 32px` at these locations since the thumbnail already provides width and height.
https://github.com/owncloud/core/blob/fix-36-vs-32-previews/apps/files/js/filelist.js#L949
https://github.com/owncloud/core/blob/fix-36-vs-32-previews/apps/files/js/filelist.js#L954

**Comment by PVince81** [comment]
It fixes the IE8 text file icon issue when merged with https://github.com/owncloud/core/pull/19454

**Comment by MorrisJobke** [comment]
> I would also get rid of background-size: 32px at these locations since the thumbnail class already provides width and height.

This will result in something like this:

bildschirmfoto von 2015-09-30 11-13-41


I would like to keep this just as a general fix for the actual issue. Cleaning up this CSS rules should be done in 9.0

**Comment by oparoz** [comment]
> I would like to keep this just as a general fix for the actual issue. Cleaning up this CSS rules should be done in 9.0

OK

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
