### PR TITLE
close navigation menu when opening app in new tab

### PR DESCRIPTION
**Pull request by ChristophWurst**
I remember there was an issue for that…

### CODE REVIEW

**Comment by nickvergessen** [comment]
"Right click + open in new tab" is not catched by this, but only Ctrl+Click.
But I guess it's fine.

**Comment by ChristophWurst** [comment]
@jancborchardt @owncloud/designers  review please

**Comment by jancborchardt** [comment]
Nice :+1:

**Comment by skjnldsv** [comment]
:+1:

**Pull request merged**
