### PR TITLE
Adding VCFExportPlugin

### PR DESCRIPTION
**Pull request by DeepDiver1975**
http://localhost:8888/remote.php/dav/addressbooks/users/admin/test/?export

refs https://github.com/owncloud/contacts/issues/248

### CODE REVIEW

**Comment by skjnldsv** [comment]
Wow, this is amazing! The dav interface could be very useful!
Anyway, :+1: , works good.

Ps: the downloaded file with export doesn't have a name, should we add this?

**Comment by Xenopathic** [comment]
@skjnldsv Hah, looks like another patch is needed upstream to sabre-dav (I already did exactly this for the ICSExportPlugin for CalDAV, so it's practically a straight port over, let me prepare a PR).

:+1: for this

**Comment by DeepDiver1975** [comment]
@karlitschek requesting backport

**Comment by karlitschek** [comment]
great. please backport 👍

**Comment by Xenopathic** [comment]
For the .vcf filename extension, see fruux/sabre-dav#814

**Comment by DeepDiver1975** [comment]
> For the .vcf filename extension, see fruux/sabre-dav#814

THX @Xenopathic  - really awesome!

**Comment by skjnldsv** [comment]
:+1:

**Pull request merged**
