### PR TITLE
Make sender display name in mail notifications configurable

### PR DESCRIPTION
**Pull request by pako81**
## Description
Make sender display name in mail notifications configurable.

## Motivation and Context
In some cases mail notifications related to sharing activities are blocked by mail filters as they are flagged as email impersonation. In such cases it may be desirable for an oC admin to have a config option for removing the sender display name.

## How Has This Been Tested?

- Set `remove_sender_display_name => true` in config.php. The `From` address in the mail notifications is displayed as follow:

image

- Set `remove_sender_display_name => false` in config.php / do not set it at all. The `From` address in the mail notifications is displayed as per current behaviour:

image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised
- [ ] Changelog item

### CODE REVIEW

**Comment by pako81** [comment]
It would eventually need documentation.

**Comment by pako81** [comment]
@hodyroff @phil-davis @jnweiger @jvillafanez does it make sense?

**Comment by jvillafanez** [comment]
Looks good to me

**Comment by phil-davis** [comment]
Looks reasonable. I pushed a fix for the unit tests. That should help CI to pass.

We can add:
- changelog
- config.sample.php entry
- new unit test case for when `remove_sender_display_name` is set to `true`

**Comment by pako81** [comment]
Doc issue created: https://github.com/owncloud/docs-server/pull/887

**Review by jvillafanez — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Comment by pako81** [comment]
@phil-davis is it not sufficient to have an issue in docs-server repo for getting new config options in config.sample.php?

**Comment by phil-davis** [comment]
> @phil-davis is it not sufficient to have an issue in docs-server repo for getting new config options in config.sample.php?

`comfig.sample.php` original source code is in the core repo. @mmattel will then do a "config to docs" run to update it in the appropriate docs repo.

**Review by jnweiger — APPROVED** [review]
Nice!

**Comment by pako81** [comment]
> comfig.sample.php original source code is in the core repo. @mmattel will then do a "config to docs" run to update it in the appropriate docs repo.

I was under the impression it was the other way round. Thanks for clarifying it!

**Comment by phil-davis** [comment]
Is this to go in 10.12.0?

If so, I can make a PR to `release-10.12.0` rather than this PR to master.

**Comment by pako81** [comment]
> Is this to go in 10.12.0?

Yes, 10.12.0. @jnweiger just changed the target branch.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
