### PR TITLE
Run federation testing on proxy

### LINKED ISSUE #35263: run acceptance tests with proxy in between
acceptance tests should also run through a proxy server, specially interesting for federation tests when one of the servers is behind a proxy.
e.g. we could run some federation smoke tests with one or both servers behind a proxy

see also https://github.com/owncloud/core/pull/34101 specially https://github.com/owncloud/core/pull/34101#issuecomment-493459318

### PR DESCRIPTION
**Pull request by skshetry**
## Description

Run federation testing via proxy (without interception enabled) and without fix/ #34101

## Related Issue

- Fixes #35263

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by skshetry** [comment]
Things to do:
- [ ] Fix `.drone.yml`

**Comment by individual-it** [comment]
blocked by #34101

**Comment by micbar** [comment]
@phil-davis @skshetry 
#34101 got merged and backported

**Comment by phil-davis** [comment]
OK, I will look.

**Comment by phil-davis** [comment]
closing because of the `stable10` ->  `master` branch changes today.

I have made a note to come back and look at this.

**Pull request closed without merging**
