### PR TITLE
Correctly create activities for public downloads

### LINKED ISSUE #14270: Activity [downloaded] seems to be triggered more than once
### Steps to reproduce

1. Make a public share
2. Download it

### Expected behavior

In the activity view it should be entered as 1 (one) single output.

### Actual behavior

It seems like the output is triggered more than once.

From activity mail:

```
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:26:58
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:17
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:18
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:18
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:18
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:19
* Der öffentliche geteilte Ordner ownCloud files/Owncloud (delad)/ownCloud pre-installed [Stable 8] [SSL] [Ubuntu Server 14.04] wurde heruntergeladen - I går 15:27:19
```

From the Web UI:

image

### Server configuration

Ubuntu Server 12.04

**Database:**
Server version: 5.5.41-0ubuntu0.12.04.1 - (Ubuntu)
PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version: (see ownCloud admin page)**
8.0
*Updated from an older ownCloud or fresh install:*
5, 6, 7.

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Version 39.0.2171.71 m
**Operating system:**
Windows 8.1
**Sync Client**
1.7.1 stable

### Logs

**Web server error log**

```
Insert your webserver log here
```

**ownCloud log (data/owncloud.log)**

```
No logs
```

**Browser log**

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #14270 

@schiesbn @enoch85

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by LukasReschke** [comment]
Lucky you that the mix-up of non-static and static code here does not allow unit-tests :see_no_evil:

**Comment by LukasReschke** [comment]
- [x] Downloading single files works and notification is added 
- [x] Downloading a single file in a folder works and notification is added 
- [x] Downloading multiple files in a folder works and notification is added

However in case 2 and 3 there is always a folder icon shown as preview instead of the actual file preview. Maybe we want to address this as well here?

Otherwise: :+1:

**Comment by nickvergessen** [comment]
Fixed the preview (used the old variable there)

**Comment by enoch85** [comment]
Tested and works as expected. :+1: 

Thanks for this quick fix @nickvergessen !

**Comment by enoch85** [comment]
( Merging as I see 3 :+1: )

**Pull request merged**
