### PR TITLE
remove testing caldav/carddav from travis pipeline

### PR DESCRIPTION
**Pull request by patrickjahns**
## Description
Testing for litmus / caldav /carddav has been migrated to drone already - this pr cleans up

## Motivation and Context
No need to wait for travis on this

## How Has This Been Tested?
🤖 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] CI

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
also remove the test files? see https://github.com/owncloud/core/pull/31651/commits/a58b1e903def63565dec2414551a1fd74844882c ;-)

**Comment by patrickjahns** [comment]
@DeepDiver1975 
testfiles would still be needed for drone, as we haven't yet put it into a container - or do I misunderstand something here?

I also wonder if travis allows us to have a nightly run - without PR testing? Maybe we need a minimal bogus step ?

**Comment by DeepDiver1975** [comment]
> testfiles would still be needed for drone, as we haven't yet put it into a container - or do I misunderstand something here?

litmus can be killed because the tests use the litmus container - your statement is true regarding caldav and carddav tests

**Comment by phil-davis** [comment]
Maybe you can turn off the travis-ci required in GitHub? Then it will not block PRs just because there is no Travis job to run. And it (hopefully) will still let Travis-cron happen.

**Comment by DeepDiver1975** [comment]
> Maybe you can turn off the travis-ci required in GitHub? Then it will not block PRs just because there is no Travis job to run. And it (hopefully) will still let Travis-cron happen.

once we have this merged I'll remove the required status

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@patrickjahns @DeepDiver1975 I rebased again. We have the "problem" that there are no regular Travis jobs remaining (mentioned above). I guess we merge this and see how to stop Travis from being a  required result, without breaking the Travis cron functionality...

Is there more litmus files cleanup to be done? Or?

**Comment by patrickjahns** [comment]
@phil-davis 
Fine by me - lets observe how travis reacts when there are no more results cc @DeepDiver1975 - any doubts?

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Note: No Travis result will happen, because there are no Travis jobs. Merge will need to be overridden, then "Travis required" adjusted.

**Comment by phil-davis** [comment]
Backport ``stable10`` #32674

**Comment by phil-davis** [comment]
> I would love to get rid of these jobs

But right at the moment I think there are more important things to get merged for RC2.

**Pull request merged**
