### PR TITLE
[stable8.1] Preview tests require imagick 2

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
````
00:08:59.979 There were 40 failures:
00:08:59.979 
00:08:59.979 1) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #16 (1, -470, -791, false, false)
00:08:59.979 /test-preview-user1/thumbnails/2268/756-537-max.png 
00:08:59.979 
00:08:59.979 Failed asserting that false matches expected true.
00:08:59.979 
00:08:59.979 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.979 
00:08:59.979 2) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #17 (1, 636, 588, false, false)
00:08:59.979 /test-preview-user1/thumbnails/2274/756-537-max.png 
00:08:59.979 
00:08:59.979 Failed asserting that false matches expected true.
00:08:59.979 
00:08:59.979 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.979 
00:08:59.979 3) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #18 (1, -767, 314, false, false)
00:08:59.979 /test-preview-user1/thumbnails/2280/756-537-max.png 
00:08:59.979 
00:08:59.979 Failed asserting that false matches expected true.
00:08:59.979 
00:08:59.979 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.979 
00:08:59.979 4) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #19 (1, 513, -358, false, false)
00:08:59.980 /test-preview-user1/thumbnails/2286/756-537-max.png 
00:08:59.980 
00:08:59.980 Failed asserting that false matches expected true.
00:08:59.980 
00:08:59.980 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.980 
00:08:59.980 5) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #20 (1, -318, -281, false, true)
00:08:59.980 /test-preview-user1/thumbnails/2292/756-537-max.png 
00:08:59.980 
00:08:59.980 Failed asserting that false matches expected true.
00:08:59.980 
00:08:59.980 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.980 
00:08:59.980 6) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #21 (1, 765, 282, false, true)
00:08:59.980 /test-preview-user1/thumbnails/2298/756-537-max.png 
00:08:59.980 
00:08:59.980 Failed asserting that false matches expected true.
00:08:59.980 
00:08:59.980 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.980 
00:08:59.980 7) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #22 (1, -657, 596, false, true)
00:08:59.981 /test-preview-user1/thumbnails/2304/756-537-max.png 
00:08:59.981 
00:08:59.981 Failed asserting that false matches expected true.
00:08:59.981 
00:08:59.981 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.984 
00:08:59.984 8) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #23 (1, 486, -659, false, true)
00:08:59.984 /test-preview-user1/thumbnails/2310/756-537-max.png 
00:08:59.984 
00:08:59.984 Failed asserting that false matches expected true.
00:08:59.984 
00:08:59.984 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.984 
00:08:59.984 9) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #24 (1, -287, -581, true, false)
00:08:59.984 /test-preview-user1/thumbnails/2316/756-537-max.png 
00:08:59.984 
00:08:59.984 Failed asserting that false matches expected true.
00:08:59.984 
00:08:59.984 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.984 
00:08:59.984 10) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #25 (1, 339, 337, true, false)
00:08:59.984 /test-preview-user1/thumbnails/2322/756-537-max.png 
00:08:59.984 
00:08:59.984 Failed asserting that false matches expected true.
00:08:59.984 
00:08:59.984 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.984 
00:08:59.984 11) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #26 (1, -334, 692, true, false)
00:08:59.985 /test-preview-user1/thumbnails/2328/756-537-max.png 
00:08:59.985 
00:08:59.985 Failed asserting that false matches expected true.
00:08:59.985 
00:08:59.985 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.985 
00:08:59.985 12) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #27 (1, 503, -607, true, false)
00:08:59.985 /test-preview-user1/thumbnails/2334/756-537-max.png 
00:08:59.985 
00:08:59.985 Failed asserting that false matches expected true.
00:08:59.985 
00:08:59.985 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.985 
00:08:59.985 13) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #28 (1, -768, -221, true, true)
00:08:59.985 /test-preview-user1/thumbnails/2340/756-537-max.png 
00:08:59.985 
00:08:59.985 Failed asserting that false matches expected true.
00:08:59.985 
00:08:59.985 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.985 
00:08:59.985 14) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #29 (1, 293, 623, true, true)
00:08:59.985 /test-preview-user1/thumbnails/2346/756-537-max.png 
00:08:59.985 
00:08:59.985 Failed asserting that false matches expected true.
00:08:59.985 
00:08:59.985 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.986 
00:08:59.986 15) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #30 (1, -553, 314, true, true)
00:08:59.987 /test-preview-user1/thumbnails/2352/756-537-max.png 
00:08:59.987 
00:08:59.987 Failed asserting that false matches expected true.
00:08:59.987 
00:08:59.987 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.987 
00:08:59.987 16) Test\Preview::testCreateMaxAndNormalPreviewsAtFirstRequest with data set #31 (1, 754, -770, true, true)
00:08:59.987 /test-preview-user1/thumbnails/2358/756-537-max.png 
00:08:59.987 
00:08:59.987 Failed asserting that false matches expected true.
00:08:59.987 
00:08:59.987 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:332
00:08:59.987 
00:08:59.987 17) Test\Preview::testSecondPreviewsGetCachedMax with data set #16 (1, -493, -666, false, false)
00:08:59.987 Failed asserting that false is identical to 'thumbnails/2822/756-537-max.png'.
00:08:59.987 
00:08:59.987 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.987 
00:08:59.987 18) Test\Preview::testSecondPreviewsGetCachedMax with data set #17 (1, 444, 397, false, false)
00:08:59.988 Failed asserting that false is identical to 'thumbnails/2828/756-537-max.png'.
00:08:59.988 
00:08:59.988 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.988 
00:08:59.988 19) Test\Preview::testSecondPreviewsGetCachedMax with data set #18 (1, -330, 509, false, false)
00:08:59.988 Failed asserting that false is identical to 'thumbnails/2834/756-537-max.png'.
00:08:59.988 
00:08:59.988 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.988 
00:08:59.988 20) Test\Preview::testSecondPreviewsGetCachedMax with data set #19 (1, 401, -564, false, false)
00:08:59.988 Failed asserting that false is identical to 'thumbnails/2840/756-537-max.png'.
00:08:59.988 
00:08:59.988 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.988 
00:08:59.988 21) Test\Preview::testSecondPreviewsGetCachedMax with data set #20 (1, -378, -346, false, true)
00:08:59.988 Failed asserting that false is identical to 'thumbnails/2846/756-537-max.png'.
00:08:59.988 
00:08:59.988 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.988 
00:08:59.988 22) Test\Preview::testSecondPreviewsGetCachedMax with data set #21 (1, 745, 218, false, true)
00:08:59.988 Failed asserting that false is identical to 'thumbnails/2852/756-537-max.png'.
00:08:59.988 
00:08:59.988 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.988 
00:08:59.988 23) Test\Preview::testSecondPreviewsGetCachedMax with data set #22 (1, -382, 618, false, true)
00:08:59.989 Failed asserting that false is identical to 'thumbnails/2858/756-537-max.png'.
00:08:59.989 
00:08:59.989 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.989 
00:08:59.989 24) Test\Preview::testSecondPreviewsGetCachedMax with data set #23 (1, 757, -649, false, true)
00:08:59.989 Failed asserting that false is identical to 'thumbnails/2864/756-537-max.png'.
00:08:59.989 
00:08:59.989 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.989 
00:08:59.989 25) Test\Preview::testSecondPreviewsGetCachedMax with data set #24 (1, -791, -744, true, false)
00:08:59.989 Failed asserting that false is identical to 'thumbnails/2870/756-537-max.png'.
00:08:59.989 
00:08:59.989 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.989 
00:08:59.989 26) Test\Preview::testSecondPreviewsGetCachedMax with data set #25 (1, 217, 672, true, false)
00:08:59.989 Failed asserting that false is identical to 'thumbnails/2876/756-537-max.png'.
00:08:59.989 
00:08:59.989 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.990 
00:08:59.990 27) Test\Preview::testSecondPreviewsGetCachedMax with data set #26 (1, -745, 749, true, false)
00:08:59.990 Failed asserting that false is identical to 'thumbnails/2882/756-537-max.png'.
00:08:59.990 
00:08:59.990 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.990 
00:08:59.990 28) Test\Preview::testSecondPreviewsGetCachedMax with data set #27 (1, 228, -775, true, false)
00:08:59.990 Failed asserting that false is identical to 'thumbnails/2888/756-537-max.png'.
00:08:59.990 
00:08:59.990 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.990 
00:08:59.990 29) Test\Preview::testSecondPreviewsGetCachedMax with data set #28 (1, -358, -511, true, true)
00:08:59.990 Failed asserting that false is identical to 'thumbnails/2894/756-537-max.png'.
00:08:59.990 
00:08:59.990 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.990 
00:08:59.990 30) Test\Preview::testSecondPreviewsGetCachedMax with data set #29 (1, 548, 763, true, true)
00:08:59.990 Failed asserting that false is identical to 'thumbnails/2900/756-537-max.png'.
00:08:59.990 
00:08:59.990 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.990 
00:08:59.990 31) Test\Preview::testSecondPreviewsGetCachedMax with data set #30 (1, -680, 597, true, true)
00:08:59.991 Failed asserting that false is identical to 'thumbnails/2906/756-537-max.png'.
00:08:59.991 
00:08:59.991 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.991 
00:08:59.991 32) Test\Preview::testSecondPreviewsGetCachedMax with data set #31 (1, 696, -475, true, true)
00:08:59.991 Failed asserting that false is identical to 'thumbnails/2912/756-537-max.png'.
00:08:59.991 
00:08:59.991 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:395
00:08:59.991 
00:08:59.991 33) Test\Preview::testDoNotCreatePreviewsLargerThanConfigMax with data set #4 (1, false, false)
00:08:59.991 Failed asserting that -1 matches expected 756.
00:08:59.991 
00:08:59.991 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:476
00:08:59.991 
00:08:59.991 34) Test\Preview::testDoNotCreatePreviewsLargerThanConfigMax with data set #5 (1, false, true)
00:08:59.991 Failed asserting that -1 matches expected 756.
00:08:59.991 
00:08:59.991 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:476
00:08:59.991 
00:08:59.991 35) Test\Preview::testDoNotCreatePreviewsLargerThanConfigMax with data set #6 (1, true, false)
00:08:59.991 Failed asserting that -1 matches expected 756.
00:08:59.991 
00:08:59.991 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:476
00:08:59.991 
00:08:59.991 36) Test\Preview::testDoNotCreatePreviewsLargerThanConfigMax with data set #7 (1, true, true)
00:08:59.991 Failed asserting that -1 matches expected 756.
00:08:59.991 
00:08:59.991 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:476
00:08:59.992 
00:08:59.992 37) Test\Preview::testIsBiggerWithAspectRatioCached with data set #4 (1, false, false)
00:08:59.992 Failed asserting that -1 matches expected 400.
00:08:59.992 
00:08:59.992 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:631
00:08:59.992 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:525
00:08:59.992 
00:08:59.992 38) Test\Preview::testIsBiggerWithAspectRatioCached with data set #5 (1, false, true)
00:08:59.992 Failed asserting that -1 matches expected 400.
00:08:59.992 
00:08:59.992 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:631
00:08:59.992 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:525
00:08:59.992 
00:08:59.992 39) Test\Preview::testIsBiggerWithAspectRatioCached with data set #6 (1, true, false)
00:08:59.992 Failed asserting that -1 matches expected 400.
00:08:59.992 
00:08:59.992 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:631
00:08:59.992 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:525
00:08:59.993 
00:08:59.993 40) Test\Preview::testIsBiggerWithAspectRatioCached with data set #7 (1, true, true)
00:08:59.993 Failed asserting that -1 matches expected 400.
00:08:59.993 
00:08:59.993 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:631
00:08:59.993 /ssd/jenkins/workspace/core-ci-linux-php5.4/database/sqlite/label/SLAVE/tests/lib/preview.php:525
00:08:59.993

**Comment by PVince81** [comment]
@DeepDiver1975 any update ? Or move to next if CI already runs properly ?

**Comment by DeepDiver1975** [comment]
@PVince81 preview tests are now executed properly (well - actually they are not - as give by the fact that there is no imagick modules with the php installations on jenkins)

**Comment by DeepDiver1975** [comment]
preview tests no longer cause ci to fall apart -> merge

**Pull request merged**
