### PR TITLE
added better description for files:cleanup

### PR DESCRIPTION
**Pull request by dercorn**

### CODE REVIEW

**Review by PVince81 — COMMENTED** [review]
:+1:

From what I see it seems to delete oc_filecache entries where the matching oc_storage entry is gone

**Review by tomneedham — APPROVED** [review]
Kicked Travis to retest

**Comment by PVince81** [comment]
@dercorn please backport to stable10 (submit new PR to stable10 with cherry-picked commit)

**Comment by DeepDiver1975** [comment]
already in stable10 - https://github.com/owncloud/core/commit/3f247f2788f620ad8a7265343cd8922d7e047ce3

**Pull request merged**
