### PR TITLE
Fix Chinese typos.

### PR DESCRIPTION
**Pull request by Red54**
I requested to join the transifex team, but you rejected me, so I have to commit it here.

### CODE REVIEW

**Comment by Red54** [comment]
Okay, this contribution is MIT licensed.

**Comment by PVince81** [comment]
This will not work, the translations will be overwritten next time the transifex bot runs.

@Red54 who rejected you ?

**Comment by Red54** [comment]
@PVince81 
qq20150617-1 2x

**Comment by PVince81** [comment]
You could try contacting the maintainers of the chinese language directly, sending them a message. Not sure why they would reject.

**Comment by Red54** [comment]
Okay, sent.

**Pull request closed without merging**
