### PR TITLE
[stable9] Read available l10n files also from theme folder

### PR DESCRIPTION
**Pull request by MorrisJobke**
- Backport of #23362 
- Approval https://github.com/owncloud/core/pull/23362#issuecomment-200316254

I tested it and it works fine :)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @nickvergessen @LukasReschke @DeepDiver1975

**Comment by MorrisJobke** [comment]
> cc @nickvergessen @LukasReschke @DeepDiver1975

It would be super nice to get this reviewed ;)

also @PVince81 maybe ;)

**Comment by nickvergessen** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
