### PR TITLE
[stable8] Properly return fileid when scanFile() did not find differences

### PR DESCRIPTION
**Pull request by PVince81**
@icewind1991 see unit test.

Not sure if the fix is adequate or could have side effects.
I basically just copied over this two lines into one: https://github.com/owncloud/core/commit/4242dd0d9d3c11a67511ec21c50e5d3a91f66f7f#diff-a53613a10fd8e2a0bb19c40f83baeaf0R145

Fixes https://github.com/owncloud/core/issues/16659

### CODE REVIEW

**Comment by icewind1991** [comment]
Fix looks like it should work, lets see what jenkins thinks

**Comment by PVince81** [comment]
Maybe I misunderstood array_diff_assoc, but it looked like even though `$data` didn't contain a fileid but `$cachedData` did, it still returned an empty array.

**Comment by icewind1991** [comment]
The result from the diff is only used for the cache update, not for the returned data

**Comment by nickvergessen** [comment]
Tested the test without the actual fix:
```
1) Test\Files\Cache\Scanner::testReuseIdentical
Failed asserting that false is true.

/home/nickv/ownCloud/eightStable/core/tests/lib/files/cache/scanner.php:189
```

So :+1:

**Comment by nickvergessen** [comment]
```
OCA\Files_Encryption\Tests\Webdav::testWebdavPUT
Undefined index: fileid
```

:see_no_evil:

**Comment by PVince81** [comment]
You can also apply this fix on top of https://github.com/owncloud/core/pull/16369 and it will make the versions tests pass.

Now let's have a look at WebdavPUT... else I'll need a less intrusive fix...

**Comment by PVince81** [comment]
I got it locally.
There is another way to fix this, let me have a try.

**Comment by PVince81** [comment]
This fix seems to be less intrusive and didn't fail the tests locally.

**Comment by PVince81** [comment]
@nickvergessen @icewind1991 another glance ?

**Comment by icewind1991** [comment]
:+1:

**Comment by PVince81** [comment]
@karlitschek please confirm this fix to OC 8.
This case is already fixed on master with a huge PR (actually fixed as a side-effect of a huge PR).

This PR fixes an issue where the file scanner fails to return the file id if called on an already known/existing file, which can break subsequent code in some cases (race conditions).

This is also required to fix some unit tests on stable8 which fail for that exact reason, see https://github.com/owncloud/core/pull/16369#issuecomment-107490984

(this will be for 8.0.5)

**Comment by karlitschek** [comment]
backport is fine. But please don't merge before 8.0.4 is out.

**Comment by nickvergessen** [comment]
my :+1: stands, so setting "To release"

**Pull request merged**
