### PR TITLE
added Safari tabbed pin icon

### PR DESCRIPTION
**Pull request by maprambo**
Added the necessary code and a black version of the ownCloud logo svg
like it is needed. See Issue #20211

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jancborchardt please have a look - THX

**Comment by DeepDiver1975** [comment]
@maprambo Thanks a lot for your contribution!
Contributions to the core repo require a signed contributors agreement http://owncloud.org/about/contributor-agreement/

Alternatively you can add a comment here where you state that this contribution is MIT licensed.

Some more details about out pull request workflow can be found here: http://owncloud.org/code-reviews-on-github/

**Comment by maprambo** [comment]
I'll sign the agreement later...
For now; of course, this contribution is MIT licensed.

**Comment by jancborchardt** [comment]
@maprambo can you attach a screenshot of how it looks so @owncloud/designers without Safari can review?

**Comment by MorrisJobke** [comment]
Doesn't work here - Safari Version 9.0.1 (11601.2.7.2).

Th pinned tab is simply empty: 
bildschirmfoto 2015-11-03 um 08 54 30

**Comment by maprambo** [comment]
@jancborchardt Screenshots are in #20211
@MorrisJobke The icon didn't appear when I was using MAMP either, Safari seems to need a real domain it can the icon associate to.

**Comment by MorrisJobke** [comment]
> @MorrisJobke The icon didn't appear when I was using MAMP either, Safari seems to need a real domain it can the icon associate to.

Correct. Now it works. But please use the other icon.

**Comment by maprambo** [comment]
What other icon? Do you mean the touch-icon?

**Comment by MorrisJobke** [comment]
> What other icon? Do you mean the touch-icon?

The inverse of this. The cloud is transparent and a box with rounded corners is blue https://raw.githubusercontent.com/owncloud/core/master/core/img/favicon-touch.png

**Comment by maprambo** [comment]
Ok, done. See Issue #20211 for screenshots.

**Comment by MorrisJobke** [comment]
here this simply shows a blue square with rounded colors :(

**Comment by maprambo** [comment]
Whoopsie. This one works.

**Comment by MorrisJobke** [comment]
Awesome, works :+1:

**Comment by MorrisJobke** [comment]
Can I ask you to squash the commits into one? That would be nice :)

**Comment by maprambo** [comment]
yep. back from school right now. one second...

**Comment by maprambo** [comment]
Everything should be in 1d648e0 however im not really familiar to git yet. I'll learn it, promised!

**Comment by MorrisJobke** [comment]
@maprambo Doesn't seem to have worked. Do following (I have a backup of all of this here locally for the case something goes wrong)

```
$ git rebase --interactive master
```

An editor opens that has a line with "pick commit-sha" per commit - replace beginning at the second line all "pick" with an "s" (for squash) - now the first line looks like "pick commit-sha" and all other like "s commit-sha" - save and leave the editor.

A new editor will open - write there the commit message that should be used for the squashed commit.

Now you need to force push because you changed the history of your branch:

```
$ git push --force origin safari-pinned-tab-icon
```

That should do the trick and this PR should then only list one commit. ;)

**Comment by jancborchardt** [comment]
Looks good! :) (I copied the screenshots over here)

Only one thing, please rename the icon to `favicon-mask.svg` and compress the image file using this code:
```
scour -i favicon-mask.svg -o favicon-mask-compressed.svg --create-groups --enable-id-stripping --enable-comment-stripping --shorten-ids --remove-metadata;
```
(And afterwards delete favicon-mask.svg and rename the compressed one to the actual one. ;)

**Comment by maprambo** [comment]
@MorrisJobke You should get a cookie. It worked :smile: (didn't expect anything else either)
I also compressed and renamed the icon to favicon-mask.svg.

**Comment by MorrisJobke** [comment]
> @MorrisJobke You should get a cookie.

Coooookiiiiiiies! :cookie: :cookie: :cookie:  :smiley:

**Comment by MorrisJobke** [comment]
:+1: from my side

**Comment by MorrisJobke** [comment]
@LukasReschke Easy to review ;) Keep in mind to address your server via IP address ;)

**Comment by jancborchardt** [comment]
Look good from my side as well, but I can’t test with Safari so it’d be cool if @LukasReschke could have a second look at it. :)

**Comment by LukasReschke** [comment]
Works :+1:

**Pull request merged**
