### PR TITLE
[8.1] Update Icewind/SMB to 1.0.4

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of #18287

### CODE REVIEW

**Comment by PVince81** [comment]
```
No coverage
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /srv/www/htdocs/owncloud/tests/phpunit-autotest-external.xml

................................................................. 65 / 70 ( 92%)
.....

Time: 1.24 seconds, Memory: 15.00Mb

OK (70 tests, 262 assertions)
stop: stop-smb-silvershell.sh
Docker executable found - stop and remove docker containers
Stopping and removing docker container c65c5822921b4eb21df7c1ef24f9a705dcdad1e9f10ad289d74fcc317442e19e
c65c5822921b4eb21df7c1ef24f9a705dcdad1e9f10ad289d74fcc317442e19e
skip: start-smb-windows.sh
skip: start-webdav-ownCloud.sh
```

**Comment by PVince81** [comment]
:+1:

**Comment by PVince81** [comment]
@icewind1991 please get into the habit of setting labels and milestone when you submit PRs. Thanks.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
