### PR TITLE
Check directory handle before we use it

### LINKED ISSUE #13953: OC 8 RC2: Log flooded with php messages: readdir() expects parameter 1 to be resource, boolean
I installed OC 8 RC2 and deactivated all apps. As soon as I browse to my OC login page (don't even have to login) my owncloud.log is flooded with:
`{"reqId":"a795aba02ba3565855ce2967d2a5493d","remoteAddr":"xx.xxx.xxx.xx","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/mnt\/web2\/c1\/92\/xxxxxx\/htdocs\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-06T16:14:57+00:00"}`
The log grows to several MBs within minutes! The remoteAddr is the IP address of my pc (I blanked it in the quote). I can login, but OC reactes slowly and sometimes I receive an internal server error.
tempmanager.php:135 is `while (($file = readdir($dh)) !== false) {`
A quick look at the code, suggests that `$file` might be undefined or we need an `==` instead of `=`.

PHP Version = 5.5.21
MYSQL = 5.0.96

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #13953

cc @DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Thx - please open a second pr against stable8. We shall fix this for 8.0.1 as well.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> Thx - please open a second pr against stable8. We shall fix this for 8.0.1 as well.

@icewind1991 THX

**Comment by icewind1991** [comment]
stable8: #13983

**Comment by nickvergessen** [comment]
:+1:

**Comment by RealRancor** [comment]
Seems this also needs to be backported to stable7? https://github.com/owncloud/core/issues/14876

**Pull request merged**
