### PR TITLE
Looks like ceph requires more time to come up ....

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:-1: still not enough :puke:

**Comment by MorrisJobke** [comment]
> still not enough :puke:

Give all the time you have :wink:

**Comment by DeepDiver1975** [comment]
Well ... jenkins doesn't have proper fs in place ....

````
09:27:36 [ERROR] Waited 600 seconds, no response
09:27:36 creating /etc/ceph/ceph.client.admin.keyring
09:27:36 creating /etc/ceph/ceph.mon.keyring
09:27:36 monmaptool: monmap file /etc/ceph/monmap
09:27:36 monmaptool: set fsid to bc255eb9-00e6-4f26-8efb-46d9c71e2315
09:27:36 monmaptool: writing epoch 0 to /etc/ceph/monmap (1 monitors)
09:27:36 creating /tmp/ceph.mon.keyring
09:27:36 importing contents of /etc/ceph/ceph.client.admin.keyring into /tmp/ceph.mon.keyring
09:27:36 importing contents of /etc/ceph/ceph.mon.keyring into /tmp/ceph.mon.keyring
09:27:36 ceph-mon: set fsid to bc255eb9-00e6-4f26-8efb-46d9c71e2315
09:27:36 ceph-mon: created monfs at /var/lib/ceph/mon/ceph-ab44ed02a4ba for mon.ab44ed02a4ba
09:27:36 set pool 0 size to 1
09:27:36 0
09:27:36 2015-12-09 14:17:44.417598 7fcf572eb900 -1 journal FileJournal::_open: disabling aio for non-block journal.  Use journal_force_aio to force use of aio anyway
09:27:36 2015-12-09 14:17:44.833982 7fcf572eb900 -1 filestore(/var/lib/ceph/osd/ceph-0) Extended attributes don't appear to work. Got error (95) Operation not supported. If you are using ext3 or ext4, be sure to mount the underlying file system with the 'user_xattr' option.
09:27:36 2015-12-09 14:17:44.834055 7fcf572eb900 -1 filestore(/var/lib/ceph/osd/ceph-0) FileStore::mount : error in _detect_fs: (95) Operation not supported
09:27:36 2015-12-09 14:17:44.834083 7fcf572eb900 -1 OSD::mkfs: couldn't mount ObjectStore: error -95
09:27:36 2015-12-09 14:17:44.834142 7fcf572eb900 -1 [0;31m ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-0: (95) Operation not supported[0m
09:27:36 stop: stop-swift-ceph.sh
09:27:36 Docker executable found - stop and remove docker containers
09:27:36 ./../apps/files_external/tests/env/stop-swift-ceph.sh: line 20: replace: command not found
09:27:36 cat: ./dockerContainerCeph.9.swift: No such file or directory
09:27:36 rm: cannot remove ‘./config.swift.php’: No such file or directory
09:27:36 rm: cannot remove ‘./dockerContainerCeph.9.swift’: No such file or directory
09:27:36 Error during start file execution ... terminating
09:27:36 Build step 'Execute shell' marked build as failure
09:27:36 Recording test results
09:27:36 Finished: FAILURE

**Comment by DeepDiver1975** [comment]
@Xenopathic mind taking a look
@butonic didn't we fix this for the primary storage?

**Comment by MorrisJobke** [comment]
> @butonic didn't we fix this for the primary storage?

Yep.

**Comment by MorrisJobke** [comment]
> Yep.

https://github.com/owncloud/core/pull/19864/files?w=1

**Comment by DeepDiver1975** [comment]
tata - https://ci.owncloud.org/job/server-master-linux-externals-swift/database=sqlite,external=swift-ceph,label=lex-j1/191/console

````
09:53:52 Configuration read from /ssd/jenkins/workspace/server-master-linux-externals-swift/database/sqlite/external/swift-ceph/label/lex-j1/tests/phpunit-autotest-external.xml
09:53:52 
09:53:52 S................................................................ 65 / 78 ( 83%)
09:55:07 .............
09:55:16 
09:55:16 Time: 1.48 minutes, Memory: 46.00Mb
09:55:16 
09:55:16 There was 1 skipped test:
09:55:16 
09:55:16 1) Test\Files\Storage\Swift::testStat
09:55:16 Swift doesn't update the parents folder mtime
09:55:16 
09:55:16 /ssd/jenkins/workspace/server-master-linux-externals-swift/database/sqlite/external/swift-ceph/label/lex-j1/apps/files_external/tests/backends/swift.php:71
09:55:16 
09:55:16 OK, but incomplete, skipped, or risky tests!
09:55:16 Tests: 78, Assertions: 328, Skipped: 1.
09:55:16 
09:55:16 Generating code coverage report in Clover XML format ... done
09:55:31 
09:55:31 Generating code coverage report in HTML format ... done
09:55:31 stop: stop-swift-ceph.sh
09:55:31 Docker executable found - stop and remove docker containers
09:55:31 Stopping and removing docker container bc73d0ea19ca540947a07fb56955ead28aa74f0a83e47a40184f94547c8ea3cf
09:55:31 bc73d0ea19ca540947a07fb56955ead28aa74f0a83e47a40184f94547c8ea3cf
09:55:31 skip: start-webdav-ownCloud.sh
09:55:31 + [ -f /owncloud.log ]
09:55:31 + [ -f /data/owncloud.log ]
09:55:31 + cp tests/autotest-external-clover-sqlite-swift-ceph.xml tests/autotest-clover.xml
09:55:31 + rm -rf /ssd/jenkins/workspace/server-master-linux-externals-swift/database/sqlite/external/swift-ceph/label/lex-j1/tests/karma-coverage
09:55:31 Recording test results
09:55:32 Finished: SUCCESS

Page generated: Dec 9, 2015 10:04:29 AMREST APIJenkins ver. 1.638

**Comment by DeepDiver1975** [comment]
Please review  @butonic @Xenopathic @LukasReschke @MorrisJobke @icewind1991  THX

**Comment by Xenopathic** [comment]
Why don't we simply push the entrypoint.sh changes upstream into the Docker image? Then we avoid all the duplication cruft... especially since @MorrisJobke can push to the Docker image directly

**Comment by MorrisJobke** [comment]
> Why don't we simply push the entrypoint.sh changes upstream into the Docker image?

Can you simply do this?

**Comment by Xenopathic** [comment]
@MorrisJobke Sure, just reminding you that you have push access :smile:

**Comment by MorrisJobke** [comment]
> @MorrisJobke Sure, just reminding you that you have push access

Yep. I got that :stuck_out_tongue_winking_eye:

**Comment by Xenopathic** [comment]
Docker entrypoint.sh changes pushed. I assume that means the entrypoint.sh duplication in the objectstore tests is no longer needed too, since that was the btrfs fix (that is now included)?

**Comment by DeepDiver1975** [comment]
> Docker entrypoint.sh changes pushed.

nice - thanks a lot! mind linking the commit?

**Comment by DeepDiver1975** [comment]
> mind linking the commit?

@Xenopathic looks like you don't have a repo for the image on github - too bad ...

**Comment by butonic** [comment]
well, I actually prefer having the entrypoint.sh outside of the docker image. Makes it a lot easier to fiddle with what is happening in the container and add more logging. my 2 cent

**Comment by Xenopathic** [comment]
@butonic Well sure, but we've already got an extracted entrypoint.sh in the objectstore tests, so with this PR we would have code duplication, not to mention the Docker image itself is (effectively) controlled by us ownCloud devs, so we can just treat it as an offshoot of ownCloud and push changes directly there to benefit others too.

**Comment by butonic** [comment]
no objections here, just opinion. Do whatever works best in engineering.

**Comment by DeepDiver1975** [comment]
Since the pure docker based approach is not yet working #21088 - I'm merging this for now so that we get a working CI system on swift. THX

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 : https://github.com/Xenopathic/ceph-keystone.docker

Great - THX

**Pull request merged**
