### PR TITLE
Revert "Revert "FIX for webdav.mediencenter.t-online.de""

### PR DESCRIPTION
**Pull request by OliverKohl**
@PVince81 Recommitted to the master as discuess here:
https://github.com/owncloud/core/pull/15201#issuecomment-105493897

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks.

So if I understand well, `hasUpdated()` should always return false when connecting to one of those special clouds ? This means that update detection will not work.

**Comment by OliverKohlDSc** [comment]
@PVince81: You're welcome. That's right.

**Comment by PVince81** [comment]
Once again you were too fast with merging. A PR needs to be validated by two people, see https://doc.owncloud.org/server/7.0/developer_manual/bugtracker/codereviews.html#how-will-it-work point 5

**Comment by DeepDiver1975** [comment]
Changes have been reverted once more ...

**Comment by DeepDiver1975** [comment]
@OliverKohlDSc please follow our guidelines! THX

**Comment by OliverKohlDSc** [comment]
@ DeepDiver1975,  PVince81: Thanks for the link. Would you guys be so kind to have a look at it? Thx.

**Comment by OliverKohlDSc** [comment]
@DeepDiver1975 @PVince81 Any news? Thanks.

**Pull request merged**
