### PR TITLE
Search address book for federated cloud id

### PR DESCRIPTION
**Pull request by schiessle**
Search the address book for federated cloud IDs and use it for auto completion in the share dialog. In order to work you need the contacts app from master (was added to contacts here: https://github.com/owncloud/contacts/pull/924) and add a "Federated Cloud ID" to your contact.

This is how auto completion looks like (we search for the full name and the cloud id)

After the file was shared successfully and you re-open the share dialog you will see:

The display name is the full name stored in the address book, on hover we show the federated cloud id of the user.

cc @jancborchardt what do you think from the design point of view. Anything we could/should improve?

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
8.2? Would be great to have this in for 8.1 with respect to feature completeness - right?

@karlitschek freeze excpetion just because this would be awesome to have? :speak_no_evil:

**Comment by schiesbn** [comment]
> 8.2? Would be great to have this in for 8.1 with respect to feature completeness - right?

I will not oppose if someone feels that it is worth a exception :speak_no_evil:

**Comment by karlitschek** [comment]
@schiesbn You are my personal hero of the day!!!!How cool is that.

**Comment by karlitschek** [comment]
Code looks easy enough for a freeze exception. And it doesn't require new screenshot or documentation.  Let's merge it if @DeepDiver1975 and @schiesbn agrees!!! :-)

**Comment by jancborchardt** [comment]
Wooooo this is awesome! :) @babelouest @derkostka can you review this as well? :)

**Comment by derkostka** [comment]
Bring it it, tested on a local owncloud on master :+1:  :100: 
Nice Idea, would be awesome to have such options also in the mobile apps :-)

**Comment by DeepDiver1975** [comment]
Thx for testing @derkostka - let's move this in then :+1:

**Comment by jancborchardt** [comment]
@derkostka you are always welcome in our IRC channels #owncloud-dev and #owncloud-contacts :)
Btw since I guess you are based in Germany, do you know of the [ownCloud Conf](https://owncloud.org/conf/) in Berlin and will you attend? There’s a call for papers as well, until Sunday.

**Comment by derkostka** [comment]
Thanks Jan-Christoph !
I will see if i can take some time for owncloud-testing. I really like your
ideas. I live in Berlin so yes, i should be able to visit the conference :

**Comment by jancborchardt** [comment]
@derkostka cool! :) You already helped a bunch with testing and pull requests. If you don’t know yet, you should check out the ownCloud Berlin meetups: http://www.meetup.com/owncloud-berlin

**Pull request merged**
