### PR TITLE
Create .htaccess

### PR DESCRIPTION
**Pull request by LukasReschke**
Ref https://github.com/owncloud/core/pull/16724#discussion_r33236344 – shouldn't hurt also.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Already blocked: https://github.com/owncloud/core/blob/master/.htaccess#L46

**Comment by LukasReschke** [comment]
> Already blocked: https://github.com/owncloud/core/blob/master/.htaccess#L46

This relies on mod_rewrite

**Comment by LukasReschke** [comment]
(this rewrite rule is also scary as it might block legit stuff. But as long nobody complains :speak_no_evil:)

**Comment by MorrisJobke** [comment]
ah ... only when rewrite engine is enables

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
jenkins failed because I aborted the job

**Pull request merged**
