### PR TITLE
Trigger "apprendered" event in users page

### LINKED ISSUE #17945: Search box in user management only appears when making the font bigger or smaller.
### Steps to reproduce

1. As admin, go to user management.
2. Create some users.
3. Look for the search box, to search users.
4. Hit ctrl+'+'

### Expected behaviour
We can see the search box all the time.

### Actual behaviour

screen shot 2015-07-29 at 10 34 14

Search box only appears after step 4.

This happens using both themes enterprise and community.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.0","versionstring":"8.1.1 beta1","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default ones.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

### Client configuration

**browser**
Chrome 43

### PR DESCRIPTION
**Pull request by PVince81**
This will properly update the controls bar width and display the search
box initially.

Fixes https://github.com/owncloud/core/issues/17945

Please review @SergioBertolinSG @DeepDiver1975 @blizzz @MorrisJobke @jancborchardt

### CODE REVIEW

**Comment by PVince81** [comment]
@karlitschek would like to backport to 8.1

**Comment by blizzz** [comment]
Tested, reviewed, and i support  the backport request :+1:

**Comment by PVince81** [comment]
Backport PR for 8.1: https://github.com/owncloud/core/pull/17949

**Comment by karlitschek** [comment]
nice. please backport :+1:

**Pull request merged**
