### PR TITLE
Storage 503 message improvements

### PR DESCRIPTION
**Pull request by PVince81**
## Description

"Storage not available" is now "Storage temporarily not available".
Exceptions are now logged in DEBUG level, not FATAL.
## Related Issue

For https://github.com/owncloud/core/issues/25854#issuecomment-244923063
## Motivation and Context

See https://github.com/owncloud/core/issues/25854#issuecomment-244923063
## How Has This Been Tested?

Setup a federated share.
Set the source share server to maintenance mode.
Try accessing the received federated share.
- [x] TEST: Check the log that the log level is DEBUG for StorageNotAvailableException
- [x] TEST: UI message says "Storage is temporarily not available" now
- [x] TEST: Webdav response message also says says "Storage is temporarily not available"
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@owncloud/filesystem @mmattel

### CODE REVIEW

**Comment by PVince81** [comment]
Hmm, it still logs a fatal, checking...

**Comment by butonic** [comment]
hm, the smb storage throws StorageNotAvailableExceptions all over the place: https://github.com/owncloud/core/blob/master/apps/files_external/lib/Lib/Storage/SMB.php#L47

**Comment by PVince81** [comment]
@butonic hmm, indeed. Not sure if the message "Storage temporarily available" is adequate in these case. If we do want it, maybe need to rethrow another StorageNotAvailableException and wrap the SMB one in "$previous".

**Comment by PVince81** [comment]
this change here was in the context of unavailable federated shares

**Comment by PVince81** [comment]
Can we still merge this even if it cannot cover all possible cases ?

**Comment by mmattel** [comment]
For me ok, agreed - better this than nothing :+1:

**Comment by guruz** [comment]
In the client we have
```
src/libsync/discoveryphase.cpp:        if (reason == "Storage not available") {
```
Will adjust..

**Pull request merged**
