### PR TITLE
Update certificate bundle

### PR DESCRIPTION
**Pull request by LukasReschke**
Syncs with ca-certificates version 2.5.
- Removes expired TURKTRUST Certificate Services Provider Root 1 (https://bugzilla.mozilla.org/show_bug.cgi?id=1165992)
- Removes obsolete TC TrustCenter certificates (https://bugzilla.mozilla.org/show_bug.cgi?id=1159070)
- Removes ComSign Secured certificate as it is not used for websites (https://bugzilla.mozilla.org/show_bug.cgi?id=1160208)
- Adds updated TURKTRUST certificates as the old ones are expired (https://hg.mozilla.org/integration/mozilla-inbound/rev/2f1a37cb43ac)
- Add Certinomis as root certificate (https://bugzilla.mozilla.org/show_bug.cgi?id=1169083)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@LukasReschke do we need to backport this?

**Comment by LukasReschke** [comment]
> @LukasReschke do we need to backport this?

I'd say so as otherwise we do have problems with certificates signed by said authorities. I will create a PR for it.

**Comment by DeepDiver1975** [comment]
@karlitschek regarding backport - THX

**Comment by LukasReschke** [comment]
stable8.1: https://github.com/owncloud/core/pull/20137
stable8.2: https://github.com/owncloud/core/pull/20138

**Pull request merged**
