### PR TITLE
AutoComplete off for password fields

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Add `autocomplete="off"` on password DOM Elements. This does not affect all browsers.

## Related Issue

- Fixes https://github.com/owncloud/enterprise/issues/2279

## Motivation and Context
See ticket

## How Has This Been Tested?

- Firefox
- Chrome
- IE 11

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: thanks

please backport

**Comment by PVince81** [comment]
@felixheidecke please backport

**Comment by cdamken** [comment]
Is it backported to 10.0.10?

**Comment by felixheidecke** [comment]
See backport https://github.com/owncloud/core/pull/32590

**Comment by csware** [comment]
Please make this optional!

**Pull request merged**
