### PR TITLE
load aws-sdk with composer

### PR DESCRIPTION
**Pull request by icewind1991**
Make it easier to manage.

Does _not_ update the aws-sdk to the latest version (maybe for a later PR)

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by LukasReschke** [comment]
> Does not update the aws-sdk to the latest version (maybe for a later PR)

But includes the tests again and Co. which leaks informations :see_no_evil: 

Especially https://github.com/owncloud/core/blob/aws-composer/apps/files_external/3rdparty/aws/aws-sdk-php/compatibility-test.php

**Comment by PVince81** [comment]
Summoning the composer expert @AdamWill :wink:

**Comment by icewind1991** [comment]
> But includes the tests again and Co. which leaks informations :see_no_evil:

> Especially https://github.com/owncloud/core/blob/aws-composer/apps/files_external/3rdparty/aws/aws-sdk-php/compatibility-test.php

I blame amazon for not putting all tests in the test folder.

removed the file

**Comment by DeepDiver1975** [comment]
26k SLOC - looks like a dump of :hankey:

**Comment by AdamWill** [comment]
I think I'd prefer my PR to move it to the main 3rdparty/ directory:

https://github.com/owncloud/core/issues/13062

which allows us to avoid having two copies of Guzzle and Symfony's event dispatcher.

**Comment by DeepDiver1975** [comment]
> I think I'd prefer my suggestion to move it to the main 3rdparty/ directory:
> 
> #13062
> 
> which allows us to avoid having two copies of Guzzle and Symfony's event dispatcher. If we put it there, that instance of composer will notice that it already has Guzzle and Symfony and not duplicate them.

I fully understand this approach - but this violates out design principle where apps are self contained.

**Comment by DeepDiver1975** [comment]
> 26k SLOC - looks like a dump of :hankey:

@karlitschek can we please talk about moving at least some of the external storages outside of core?

The sdks are dumping more an more code into core - really frustrating

**Comment by AdamWill** [comment]
@DeepDiver1975 I understand. An alternative is to manually strip those bits like you can manually strip the test cases and docs and so on...but then you've kinda lost the advantage of using composer in the first place because you have to do a ton of manual tweaking.

You could ask upstream php-aws-sdk to configure things so that the tests and other bits aren't included when using Composer, it is possible for them to do that. Unfortunately the Composer system doesn't appear to provide a mechanism whereby they can make it optional, other than actually setting up multiple separate packages in Packagist.

**Comment by MorrisJobke** [comment]
What is the state of this?

**Comment by helmutschneider** [comment]
:+1: for this. Forgive me for asking, but why do we need the sdk commited to OC core if we're using composer anyways? Shouldn't ```composer.lock``` be enough?

**Comment by PVince81** [comment]
See https://github.com/owncloud/core/issues/11973
At some point that's the way we want to do it with composer...

**Comment by DeepDiver1975** [comment]
@icewind1991 I guess we can close this - we will drag in aws-sdk into the s3 app - right?

**Comment by MorrisJobke** [comment]
@icewind1991 said that this is obsolete

**Pull request closed without merging**
