### PR TITLE
Make version.php PHP 5.3 compatible for the build scripts

### PR DESCRIPTION
**Pull request by PVince81**
@karlitschek as discussed 

@DeepDiver1975 express merge ? :wink:

### CODE REVIEW

**Comment by karlitschek** [comment]
awesome! As discussed :+1:

**Comment by MorrisJobke** [comment]
Really? This is very likely to break again in the future. I would fix the build scripts then. We officially don't support PHP 5.3 anymore.

**Comment by karlitschek** [comment]
It's not the build script. It's the machine where the build script is running on. Which might take significantly longer to upgrade then merging this fix. :-/
I general I completely agree :-)

**Comment by DeepDiver1975** [comment]
I suggest to move the tar ball generation (at least for daily) to jenkins where we can publicly see issues.

**Comment by DeepDiver1975** [comment]
besides that :+1:

**Comment by DeepDiver1975** [comment]
@karlitschek can you please kick off the build script again? we need updated tar balls - THX

**Comment by karlitschek** [comment]
done. will be available after the next run.

**Pull request merged**
