### PR TITLE
use new checkbox style for Apps mgmt settings

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @DeepDiver1975 @Henni @owncloud/designers 

We should also backport this since the new checkboxes should be used for 8.2 everywhere. @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:  please backport

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by jancborchardt** [comment]
Backport PR at https://github.com/owncloud/core/pull/20440, please review as well.

**Comment by jancborchardt** [comment]
@DeepDiver1975 merge please

**Pull request merged**
