### PR TITLE
Fix share email sending feedback

### LINKED ISSUE #19276: [Sidebar] Email link to person; wrong 'placeholder' when emailing a link to a wrong address
### Steps to reproduce

1. Create a file
2. Click on share button (Sidebar appears)
3. Email link to person with a invalid email

### Expected behaviour
The 'placeholder' shown should be related about email not sent

### Actual behaviour
The 'placeholder' shown says the mail was sent

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

placeholdmail

### PR DESCRIPTION
**Pull request by PVince81**
Redisplay email address after failure

Fixes https://github.com/owncloud/core/issues/19276

Please review @schiesbn @rullzer @blizzz @davitol @MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
sweet :+1:

**Comment by nickvergessen** [comment]
works :+1:

**Comment by davitol** [comment]
:+1: Do what it promises

**Comment by rullzer** [comment]
Unit tests added... so it will hopefully keep on working :)

**Comment by PVince81** [comment]
@rullzer thanks a lot

**Comment by MorrisJobke** [comment]
@PVince81 Please create the backport for 8.2.1

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19771

**Pull request merged**
