### PR TITLE
fix getUsersSharingFile with locking

### PR DESCRIPTION
**Pull request by icewind1991**
Possible fix for #17029 

I still can reproduce 17029 myself...

@nickvergessen @PVince81 please test

### CODE REVIEW

**Comment by nickvergessen** [comment]
Let me run the full set against this over lunch

**Comment by PVince81** [comment]
You mean run it over :hamburger: ?

**Comment by nickvergessen** [comment]
```
$ bin/smash lib/oc-tests/test_sharePermissions.py -t=0
SUMMARY:smash.:runid: 150622-145450
SUMMARY:smash.:URL: http://test:***@192.168.177.243/ownCloud/Smashbox/master/remote.php/webdav/
SUMMARY:smash.:Running iteration 1
SUMMARY:smash.:running lib/oc-tests/test_sharePermissions.py in /home/nickv/ownCloud/Smashbox/ramdir/test_sharePermissions-150622-145450 as test testset #0 {'sharePermissions_matrix': {'allowed_operations': ['upload', 'upload_overwrite', 'rename', 'move_in', 'move_in_overwrite', 'move_in_subdir', 'move_in_subdir_overwrite', 'move_out', 'move_out_subdir', 'delete', 'mkdir', 'rmdir'], 'permission': 31}}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
2015-06-22 14:55:11,731 - ERROR - recipient_worker - Unexpected response: Status code: 500 - SabreDAV Exception: OC\Encryption\Exceptions\DecryptionFailedException - Message: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
2015-06-22 14:55:11,746 - ERROR - recipient_worker - Operation "move_in_subdir_overwrite" must be allowed when share permissions are 31 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: 192.168.177.243
2015-06-22 14:55:15,049 - ERROR - recipient_worker - 1 error(s) reported
CRITICAL:smash.:Aborting run -- non-zero exit code (2)

```

**Comment by nickvergessen** [comment]
So moving a file into a subfolder "overwriting" an existing file is not working as expected anymore.
Note that overwrite via webdav is delete + create?

**Comment by icewind1991** [comment]
> PHP Fatal error:  Maximum execution time of 3600 seconds exceeded

...

**Comment by nickvergessen** [comment]
@icewind1991 doesn't matter:

> So moving a file into a subfolder "overwriting" an existing file is not working as expected anymore.
Note that overwrite via webdav is delete + create?
```
$ bin/smash lib/oc-tests/test_sharePermissions.py -t=0
SUMMARY:smash.:runid: 150622-145450
SUMMARY:smash.:URL: http://test:***@192.168.177.243/ownCloud/Smashbox/master/remote.php/webdav/
SUMMARY:smash.:Running iteration 1
SUMMARY:smash.:running lib/oc-tests/test_sharePermissions.py in /home/nickv/ownCloud/Smashbox/ramdir/test_sharePermissions-150622-145450 as test testset #0 {'sharePermissions_matrix': {'allowed_operations': ['upload', 'upload_overwrite', 'rename', 'move_in', 'move_in_overwrite', 'move_in_subdir', 'move_in_subdir_overwrite', 'move_out', 'move_out_subdir', 'delete', 'mkdir', 'rmdir'], 'permission': 31}}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.177.243
2015-06-22 14:55:11,731 - ERROR - recipient_worker - Unexpected response: Status code: 500 - SabreDAV Exception: OC\Encryption\Exceptions\DecryptionFailedException - Message: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
2015-06-22 14:55:11,746 - ERROR - recipient_worker - Operation "move_in_subdir_overwrite" must be allowed when share permissions are 31 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: 192.168.177.243
2015-06-22 14:55:15,049 - ERROR - recipient_worker - 1 error(s) reported
CRITICAL:smash.:Aborting run -- non-zero exit code (2)

```

**Comment by icewind1991** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
@icewind1991 rebase to get oracle fix in - THX

**Comment by nickvergessen** [comment]
@DeepDiver1975 
> @icewind1991 rebase to get oracle fix in - THX

The patch does not solve the problem, no need to rebase anything :speak_no_evil:

**Comment by nickvergessen** [comment]
:-1:

**Comment by icewind1991** [comment]
This fixes the web ui upload found by @PVince81

**Comment by icewind1991** [comment]
Also this fixes the "overwrite a file in a share by moving a file in" which fails on master.

- create a folder 'foo' as user1 and share it with user2

With cadaver as user2:

- `put bar.txt bar.txt` (asuming you have a local file 'bar.txt')
- `mv bar.txt foo/`
- `put bar.txt bar.txt`
- `mv bar.txt foo/`

**Comment by PVince81** [comment]
- [x] TEST: web upload works
- [x] TEST: move cross-storage works
- [ ] TEST: smashbox re-run

**Comment by PVince81** [comment]
I ran smashbox on this branch: success.
Then I ran it on master: fail.
Then ran again on this branch: fail.

Maybe stray users or stray locks.

**Comment by PVince81** [comment]
Let's check the keys in redis before and after these runs. (`redis-cli` then `KEYS *`)

**Comment by nickvergessen** [comment]
Well it fixes most of the sharePermission for me.
Only `./bin/smash lib/oc-tests/test_sharePermissions.py -t=7` fails with:
```
2015-06-26 16:56:50,225 - ERROR - recipient_worker - Unexpected response: Status code: 500 - SabreDAV Exception: OC\Encryption\Exceptions\DecryptionFailedException - Message: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
2015-06-26 16:56:50,240 - ERROR - recipient_worker - Operation "move_in_subdir_overwrite" must be forbidden when share permissions are 11 'Operation "%s" must be %s when share permissions are %i' % (operation, success_message, perms) failed in recipient_worker() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_sharePermissions.py" at line 251]
```

which is what I pointed out all the way up there already.

**Comment by PVince81** [comment]
I deleted all tests users manually and cleared the stray keys.
Smashbox test run (`bin/smash lib/oc-tests/test_sharePermissions.py -a`):
- Run 1: on this branch, no stray keys: success, no errors

**Comment by nickvergessen** [comment]
I started it with loop=10 and run 5 and 6 failed with above exception. So it seems to be a timing issue :see_no_evil:

**Comment by PVince81** [comment]
No stray keys after run 1.

- Run 2: on master: fail

But no stray keys now. (note: in my previous test runs I got the "Connection Closed" error, maybe that left stray keys)

- Run 3: on this PR: fails now `('Connection aborted.', BadStatusLine("''",)) `

There are 4 stray keys in redis, I leave them there.
Restart apache2.

- Run 4: on this PR: fail

Now I remove the stray keys with `flushall`

- Run 5: on this PR: success

@nickvergessen can you make sure that there are no stray keys in your redis before you run the test ?
I remember you mentionned having the "BadStatusLine" error a few times. That one would leak keys that then influence the outcome of subsequent tests.

And I think this is the explanation for the randomness.

@nickvergessen did you see any "BadStatusLine" failures in your most recent loop test ? If possible, would be good to see if keys were leaked between runs.

**Comment by nickvergessen** [comment]
No, I didn't have any "BadStatusLine" anymore since I use a VM for testing.

Well since the patch fixes the upload via webui, I think we can use it for now, and when we find a reliable circumstance that still needs fixing, we can have a look for that later?

**Comment by PVince81** [comment]
Yes, let's do that. And raise a separate ticket to keep the other random case in mind.

:+1: for this PR

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
Jenkins, don't be a buzzkill please

**Comment by icewind1991** [comment]
@nickvergessen are you able to manually trigger the error that smashbox gives you?

**Pull request merged**
