### PR TITLE
LDAP: set up paged search even if limit is 0

### PR DESCRIPTION
**Pull request by blizzz**
Fixes an issues found in https://github.com/owncloud/core/issues/13533#issuecomment-76092306 ff

Thing is, the issue is hard to reproduce. I wrote a test script, but was never able to reproduce the issue on my system against AD 2008 nor 2012.  On the system of the ticket however, it was reproducible, the test worked and the fix also.

I don't expect side effects.

@DeepDiver1975 @MorrisJobke @jnfrmarks  @sbelov1

### CODE REVIEW

**Comment by blizzz** [comment]
A backport to OC 7 is here, because original issue is against OC 7: https://github.com/owncloud/core/pull/14707

PR for OC 8 will follow when master is dealt herewith.

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Backport: #14751

**Pull request merged**
