### PR TITLE
correction to logging levels

### LINKED ISSUE #19035: correct logging levels in config.sample.php
Hello, on the ownCloud Admin page there are five loggings levels, but in config.sample.php there are only four: 0 = Debug, 1 = Info, 2 = Warning, 3 = Error. Shouldn't there also be 4 = Fatal?

### PR DESCRIPTION
**Pull request by carlaschroder**
Added 4 = Fatal

Fix #19035

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Documentation only - > Merge

**Comment by MorrisJobke** [comment]
-. - rebate needed

**Pull request merged**
