### PR TITLE
Fix check behat exit

### PR DESCRIPTION
**Pull request by individual-it**
## Description
the exit code of behat running selenium tests was not checked correctly
this resulted in showing failed test as passed in travis & saucelabs

## Related Issue
 #27879

## How Has This Been Tested?
locally & by cherry picking the commits to #27872

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
Here is a test build without this change: https://travis-ci.org/individual-it/owncloud-core/builds/232406044?utm_source=github_status&utm_medium=notification
I purposely made a test that would fail, and this Job shows the scenario failure in it: https://travis-ci.org/individual-it/owncloud-core/jobs/232406052
but the status is not passed back, and Travis thinks that the Job and thus the whole Build passed.

Here is a test build with the same bad test, and this change to pass back the status properly: https://travis-ci.org/individual-it/owncloud-core/jobs/232406052
Each of the 4 selenium jobs show as failed (as they should), e.g.: https://travis-ci.org/individual-it/owncloud-core/jobs/232408321

So this is "a good thing".

**Comment by phil-davis** [comment]
Hmm @individual-it why did Job https://travis-ci.org/owncloud/core/jobs/232354259 fail with messages about scenarios "Failed asserting that two strings are equal."?

**Comment by individual-it** [comment]
restarting the job did fix it

**Comment by phil-davis** [comment]
Always good to know that the traditional support "fix" even works here - restart or reboot ;)

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
