### PR TITLE
Fix compatibility with 5.3 again

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/core/issues/16665

### CODE REVIEW

**Comment by LukasReschke** [comment]
@DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Fix compatibility with 5.4 again

5.3

**Comment by LukasReschke** [comment]
> 5.3

:see_no_evil:

**Comment by DeepDiver1975** [comment]
https://ci.owncloud.org/job/server-stable7-linux-php5.3-lukas/1/

**Comment by MorrisJobke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
all green -> merge

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
