### PR TITLE
Return ETag and OC-ETag in case of a move

### LINKED ISSUE #25682: New chunking: etags on the final MOVE
The MOVE command of the .file from the uploads to the taget  folder does not return the new etag as a header  (ETag, or better, OC-ETag)
This is required so the client know the etag for which a specific file is uploaded.

Also, if we specify the If-Match header of the expected destination etag, we get a 412 precondition failed when the etag match

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #25682

### CODE REVIEW

**Comment by PVince81** [comment]
MEEP
```
{"reqId":"A7JjiDLr7flPSBsv0p\/o","remoteAddr":"127.0.0.1","app":"PHP","message":"Cannot use Sabre\\DAV\\Server as Server because the name is already in use at \/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/CopyEtagHeaderPlugin.php#25","level":3,"time":"2016-08-08T18:42:41+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"admin"}
```

with php5-5.6.23-1.1.x86_64

@DeepDiver1975 stop doing that! It's not the first time :wink:

**Comment by DeepDiver1975** [comment]
> with php5-5.6.23-1.1.x86_64

bäääh - let's drop php 5.6 as well :see_no_evil:

**Comment by PVince81** [comment]
Code looks good :+1:

@ogoffart please test

**Comment by ogoffart** [comment]
Tested and works.

However We still have the Match-IF problem for which we need a solution. But that's another problem

**Comment by PVince81** [comment]
> another problem

another ticket, another day :smile:

**Comment by PVince81** [comment]
@DeepDiver1975 conflicts :cry:

**Comment by DeepDiver1975** [comment]
rebased

**Pull request merged**
