### PR TITLE
[stable10] UI tests - autocomplete sharing

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #27933 

This has some enhancements to "waitforAjaxCalls" and similar underlying UI test processing that will be handy in stable10 also.

### CODE REVIEW

**Comment by phil-davis** [comment]
@PVince81 this is needed in stable10 in order to backport https://github.com/owncloud/core/pull/28190
The feature added here in #28188 is then enhanced and added to by #28190

**Comment by PVince81** [comment]
I can merge this one someone who understands UI tests has reviewed it

**Comment by phil-davis** [comment]
@individual-it - this is just a straight backport of the code in master. Nothing is technically different.
Review please.

**Review by individual-it — APPROVED** [review]
yes looks exactly the same like the PR to master and travis does run the tests fine, so should work

**Pull request merged**
