### PR TITLE
fixed typos in 'phoenix.baseUrl' documentation

### PR DESCRIPTION
**Pull request by individual-it**
## Description
follow up of #36007 fixing typos

### CODE REVIEW

**Review by mmattel — APPROVED** [review]
LGTM, many thanks 👍

**Review by phil-davis — APPROVED** [review]

**Comment by sharidas** [comment]
Restarted the CI.

**Comment by mmattel** [comment]
is backporting necessary?

**Comment by phil-davis** [comment]
> is backporting necessary?

there is no `stable10` any more - no more backporting needed in `core`

**Pull request merged**
