### PR TITLE
Properly handle return code of OC_App::getAppPath

### LINKED ISSUE #20128: Strange "open_basedir" problem
I have strange errors in Owncloud log during cron job like:
`is_file(): open_basedir restriction in effect. File(/appinfo/app.php) is not within the allowed path(s): {...} at /usr/share/webapps/owncloud/lib/private/app.php#136`
`file_exists(): open_basedir restriction in effect. File(/appinfo/routes.php) is not within the allowed path(s): {...} at /usr/share/webapps/owncloud/lib/private/route/router.php#106`

Why does it look in root ('/') for files? How can I debug it? If I turn off all apps from gui, these errors still occur. There is nothing wrong with functionality as I can see though. I broke my head already :)

Version 8.2.0

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #20128
- getAppPath could return false, but it was not handled everywhere

cc @LukasReschke @nickvergessen @rullzer

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Best to review with whitespace ignored: https://github.com/owncloud/core/pull/22376/files?w=1

**Comment by MorrisJobke** [comment]
cc @Xenopathic

**Comment by nickvergessen** [comment]
:+1:

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
