### PR TITLE
[WIP] Only show SSL table header if there are certificates

### PR DESCRIPTION
**Pull request by rullzer**
Another try after the to early merge of #15345

Still for #15263

@DeepDiver1975 @PVince81 it is almost impossible to unit test this now (see #15352). Do we require unit test for this? Or do we wait with this merge until #15352 is fixed?

CC: @jancborchardt

### CODE REVIEW

**Comment by karlitschek** [comment]
works for me :+1:

**Comment by jancborchardt** [comment]
@rullzer is the only reason this is set for 8.2 about the unit tests? This is a quite good user-visible fix and very little code. We should really release it with 8.1

cc @DeepDiver1975

**Comment by karlitschek** [comment]
Do we still have time to merge this?
The code is trivial IMHO

**Comment by DeepDiver1975** [comment]
@rullzer please rebase - THX

**Comment by rullzer** [comment]
Rebased. (later than planned, sorry for that).
Yes the only thing this was hanging on is the unit tests. Al tough it is trivial code.
So merge at your own digression.

But we should have proper unit tests before 8.2!!!

**Comment by rullzer** [comment]
@owncloud-bot retest this please

**Comment by jancborchardt** [comment]
:+1: works for me. Merging now and for real this time, ok @rullzer? ;)

**Comment by karlitschek** [comment]
:+1:

**Comment by rullzer** [comment]
Like I said on IRC. Fine by me :)

**Comment by jancborchardt** [comment]
Nice! Btw @rullzer are you not in the ownCloud organization? @karlitschek we should probably add him, right? ;)

**Pull request merged**
