### PR TITLE
Fake LOCK statement for Windows 7, 8 and 10 network mounts

### LINKED ISSUE #22596: Windows Office files via SMB mount through WebDAV is prompting for authentication
### Steps to reproduce
1. Place Windows Office files ( .doc, .docx, ..) on a Windows Share
2. Setup an ownCloud External Storage - SMB/CIF mount to the Windows Share
3. Attempt to open the files via a WebDAV mount through the OC mount

### Expected behavior
The user should be able to open the Windows Office files just as if they were using a standard Windows mount.

### Actual behavior
The user is prompted to authenticate when trying to open the files through WebDAV

### Server configuration
**Operating system**: RHEL

**Web server:** Apache

**Database:** MySQL

**PHP version:** to obtain

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** Updated

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** AD

### Client configuration
**Browser:** IE

**Operating system:** Windows

#### ownCloud log (data/owncloud.log)
Attached on s3

@MorrisJobke

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #22596 

cc @LukasReschke @gig13 

@karlitschek I would like to backport this to stable8.2 and stable9

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1: looks good, cant test atm

**Comment by karlitschek** [comment]
makes sense. please backport :+1:

**Comment by MorrisJobke** [comment]
stable9: #23102
stable8.2: #23103

**Comment by gig13** [comment]
@MorrisJobke A customer tested the patch in an 8.2.2  dev environment and when trying to map the drive got the “A device Attached to the system is not functioning" on both win10 and 7

Do you want more information from the customer? Do you know what might be causing this messgae?

**Comment by MorrisJobke** [comment]
> @MorrisJobke A customer tested the patch in an 8.2.2 dev environment and when trying to map the drive got the “A device Attached to the system is not functioning" on both win10 and 7

Did they apply https://github.com/owncloud/core/pull/23103/files ?



> Do you want more information from the customer? Do you know what might be causing this messgae?

I never have seen such an issue. Please open a new ticket. Also the access logs would be helpful.

**Comment by gig13** [comment]
@MorrisJobke 
Yes, they used that file from https://github.com/owncloud/core/pull/23103/files 

I will see if I can get more info

**Comment by marco-aa** [comment]
Hi all :-)

just in case it's help/ usefull - i had the same Error - added the patch from #23094 by hand into the file and i had no more Errors (look at the bottom) in my lockfile :-)

Running CentOS Linux release 7.2.1511 (Core) in KVM, Owncloud 8.2.3 (stable) using Windows 7 and WebDav mount over Windows Networkshare

Exception: {"Message":"HTTP\/1.1 501 There was no handler found for this \"LOCK\" method","Exception":"Sabre\\DAV\\Exception\\NotImplemented","Code":0,"Trace":"#0 \/host-data-store\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/host-data-store\/www\/html\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#2 \/host-data-store\/www\/html\/remote.php(137): require_once('\/host-data-stor...')\n#3 {main}","File":"\/host-data-store\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":472}

**Pull request merged**
