### PR TITLE
[tests-only] Escape $ in href response

### PR DESCRIPTION
**Pull request by kobergj**
Signed-off-by: jkoberg <jkoberg@owncloud.com>

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Comment by individual-it** [comment]
Why do we need this? Would be good some explanation in the PR

**Comment by phil-davis** [comment]
Note: this branch is currently referenced by cs3org/reva edge branch. So do not delete the branch.

**Comment by micbar** [comment]
in https://github.com/cs3org/reva/pull/2790/ we changed the resource IDs in reva to become `<storageproviderid>$<rootnodeid>!<nodeid>`.

That will enable us to use a static registry. So all resource IDs will have a storageproviderid in the space id.

**Comment by kobergj** [comment]
@individual-it We changed the format of the storageid to be of form "providerid$spaceid", thus we need to escape it now otherwise strings don't match in multiple tests.

@phil-davis this branch can be savely deleted. I have another branch which is based on the commit used in edge. This one here is based on master to avoid conflicts and side effects.

**Pull request merged**
