### PR TITLE
Update EmptyContentSecurityPolicy.php

### PR DESCRIPTION
**Pull request by Originalimoc**
ownCloud 10.0.2
Correct Content Security Policy.

### CODE REVIEW

**Comment by PVince81** [comment]
@iMocW can you explain why this is needed ? (it seems you skilled the PR template)

**Comment by iMocW** [comment]
Because of this.
I'm afraid if there's someone can use "data:" to injection something harmful too.
this

**Comment by DeepDiver1975** [comment]
tests are failing badly

bildschirmfoto von 2017-07-31 15-34-44

**Comment by iMocW** [comment]
Fixed.

**Comment by DeepDiver1975** [comment]
> Fixed.

I'm sorry to say ... but: no

**Comment by iMocW** [comment]
But I'm running nicely?????

**Comment by DeepDiver1975** [comment]
I'm closing this for now - it is conflicting and tests are failing ... please resubmit if this still needs to be chaned

**Pull request closed without merging**
