### PR TITLE
[9.0] error out if a local storage isn't setup correctly

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of #24246 to 9.0

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: local storage still works

**Comment by PVince81** [comment]
@LukasReschke second review ?

**Comment by rullzer** [comment]
:+1:

**Comment by PVince81** [comment]
Some weird integration test errors:
Test Result (17 failures / +17)

    caldav.Accessing a not existing calendar of another user
    caldav.Accessing a not existing calendar of myself
    carddav.Accessing a not existing addressbook of another user
    carddav.Accessing a not shared addressbook of another user
    carddav.Accessing a not existing addressbook of myself
    carddav.Creating a new addressbook
    checksums.Uploading a file with checksum should work
    checksums.Uploading a file with checksum should return the checksum in the propfind
    checksums.Uploading a file with checksum should return the checksum in the download header
    checksums.Moving a file with checksum should return the checksum in the propfind
    checksums.Moving file with checksum should return the checksum in the download header
    checksums.Copying a file with checksum should return the checksum in the propfind
    checksums.Copying file with checksum should return the checksum in the download header
    checksums.Overwriting a file with checksum should remove the checksum and not return it in the propfind
    checksums.Overwriting a file with checksum should remove the checksum and not return it in the download header
    checksums.Uploading a chunked file with checksum should return the checksum in the propfind
    checksums.Uploading a chunked file with checksum should return the checksum in the download header

Doesn't happen on other PRs, probably unrelated.

**Comment by PVince81** [comment]
Rebased to relaunch CI, to be on the safe side

**Pull request merged**
