### PR TITLE
Add some PHPDocs

### PR DESCRIPTION
**Pull request by LukasReschke**
My IDE was crying...

@Xenopathic @icewind1991 THX

### CODE REVIEW

**Comment by Xenopathic** [comment]
Is there no way to inherit the docblocks of the parent classes?

**Comment by LukasReschke** [comment]
Yes - it's also very good documented: http://phpdoc.org/docs/latest/references/phpdoc/inheritance.html

**Comment by LukasReschke** [comment]
=> I have no idea how to do it properly and standard compliant :see_no_evil:

**Comment by DeepDiver1975** [comment]
hmmm .... http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlineinheritdoc.pkg.html

**Comment by LukasReschke** [comment]
Adjusted. No idea if that works or not ;-)

**Comment by Xenopathic** [comment]
FYI: http://phpdoc.org/docs/latest/guides/inheritance.html

**Comment by LukasReschke** [comment]
Still, has not really a lot of examples which would be more helpful for lazy peoples that don't want to read that bunch of page :see_no_evil:

**Comment by Xenopathic** [comment]
Apparently an overridden method doesn't need any docblock, as it will automatically inherit that from the parent:

> Inheritance for methods functions similar to classes and interfaces. When a superclass of the current class contains a method with the same name (hence, this method is re-defined) then the following information is inherited from that overridden method:
> 
>    Summary
>     Description
>     The following tags:
>         author
>         copyright
>         version
>         param
>         return
>         throws

**Comment by LukasReschke** [comment]
Yeah… PHPDoc is like "everybody does it differen" :-/

**Comment by LukasReschke** [comment]
Fail is unrelated.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
