### PR TITLE
backport of #23222

### PR DESCRIPTION
**Pull request by Phiber2000**
backport of #23222 (pulled with #23225) - fix broken logtimezone
(replaces pull requests with external commit #23235, #23224)

### CODE REVIEW

**Comment by karlitschek** [comment]
@PVince81 @DeepDiver1975

**Comment by Phiber2000** [comment]
CI output from "core-ci-linux-swift-primary-storage/mysql,SLAVE" reported:
```
ownCloud is not installed - only a limited number of commands are available
[OCP\Files\NotFoundException]
```
I think the build target should be runned again to trigger the rest. This is not caused by the commit itself.

**Comment by PVince81** [comment]
@Phiber2000 your change doesn't affect home object store, so we can just ignore that failing test. Sometimes the server fails to initialize due to timeout issues when the swift docker is slow to initialize.

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
