### PR TITLE
Combine new+upload and move to sidebar

### PR DESCRIPTION
**Pull request by PVince81**
This has several advantages:
- simplify means of creating and uploading files into one
- adjust »New« menu« to ownCloud bubble style
- have the button at the same place always
- more space for breadcrumbs on mobile

The proposed flow:
new file menu

As discussed @PVince81 @karlitschek cc @owncloud/designers 
(In the uploading entry, there needs to be a progress bar and an x icon to cancel it. That’s details we can adjust.)

@PVince81 we need to take care that the button is hidden in the other views like favorites, shared. And also that it’s still placed in the breadcrumbs bar for shared files.

(Similar to https://github.com/owncloud/core/issues/7031)

### CODE REVIEW

**Comment by PVince81** [comment]
Argh... just when I tried the new shiny "hub pull-request" command, it decided to convert this issue to a pull request... I thought it would just reference it.

Well, anyway, try it out :smile: 

What is done so far:
- moved upload button to the sidebar as "+" button with the menu
- "+" button hides when switching section
- "+" button is disabled when inside a read-only folder
- public page still works as before

TODOs:
- [ ] TODO: progress bar

@jancborchardt I have concerns regarding the progress bar: if we implement like in the mock up, we still need a different solution for the public link page. @nickvergessen suggested a different approach where we add a thin row under the controls bar (with witdth:100%) and show the progress bar there. The cancel button could be at the right of the controls bar. And this for all views, regular file list and public link page.
I'd like to avoid having two different implementations/behavior for the progress bar.

- [ ] TODO: implement unit tests
- [ ] TODO: tooltip for max upload size ?
- [ ] BUG: tooltip doesn't work
- [ ] TEST: in IE8 and IE9 ...

@jancborchardt @nickvergessen @schiesbn @Xenopathic @karlitschek @DeepDiver1975

**Comment by PVince81** [comment]
- [ ] TODO: fix alignments/jumpy behavior inside the menu when switching states

**Comment by MorrisJobke** [comment]
> Argh... just when I tried the new shiny "hub pull-request" command, it decided to convert this issue to a pull request... I thought it would just reference it.

Neat :)

**Comment by PVince81** [comment]
Due to the various design complications we (with @jancborchardt) to do a smaller step and first combine the upload action into the menu.

This is done in this PR: https://github.com/owncloud/core/pull/18630
We can discuss and solve the progress bar and public page issues later.

**Comment by karlitschek** [comment]
ping :-)

**Comment by jancborchardt** [comment]
@karlitschek so now that we’re using the new solution since some time: Is it cool like that, or should we move it to the sidebar too? Drawbacks I see with that:
* will look a bit strange with the button next to »All files«, but even worse with it as an own button (as described above) because of the sidebar jumping around when the function is not available (like in Favorites and the other views)
* very little space for the loading bar, or we need to insert it strangely below (which will also result in the other entries jumping)
* it’s really tedious to reach on mobile

What do you think? Also cc @owncloud/designers

**Comment by PVince81** [comment]
I'd vote for leaving the button where it is now in 8.2. Also note that in the public link page the button will still have to be in the top bar, so from the code perspective it will be two different code paths to support.

**Comment by jancborchardt** [comment]
Right, the potential difference with the public page is an even bigger drawback I forgot.

**Comment by MorrisJobke** [comment]
I would also leave it in the controls bar.

**Comment by nickvergessen** [comment]
Same here, we have more important stuff to design and implement...
Close?

**Comment by MorrisJobke** [comment]
Close because the current approach is quite good.

**Comment by karlitschek** [comment]
guys. We have to talk about this before just closing this pull request for a feature that was discussed.

**Comment by karlitschek** [comment]
@jancborchardt Can we talk about this at our next opportunity and reopen this in the meantime please? Thanks

**Comment by jancborchardt** [comment]
Yeah folks, I specifically asked for @karlitschek so please don’t go rogue-closing discussions, thanks. ;)

**Comment by karlitschek** [comment]
Let's leave this open for now and discuss at the next opportunity. Thanks

**Comment by PVince81** [comment]
Did you get a chance to talk about this ?

**Comment by PVince81** [comment]
Moving to 9.1.

I guess you guys still want to discuss this ?

**Comment by karlitschek** [comment]
@jancborchardt Do you still think we should do this? or drop it?

**Comment by jancborchardt** [comment]
@karlitschek after some more thinking about it I would say the cons slightly outweigh the pros:
- difficult to reach on mobile since it’s in the sidebar only
- we don’t have a sidebar on the public sharing page so we need to put it in the controls bar here anyway

I’d say we close it for now and revisit it again at a later date when we feel the need for it. The mockup up top is still a valid solution, but maybe with time & using the current version we come up with something better.

**Comment by karlitschek** [comment]
agreed. makes sense

**Pull request closed without merging**
