### PR TITLE
Accept this language change "at your own risk"

### PR DESCRIPTION
**Pull request by nickvergessen**
@LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
https://translate.google.com/#de/en/Auf%20eigene%20Gefahr

**Comment by MorrisJobke** [comment]
:+1:

**Comment by Xenopathic** [comment]
:+1:

**Comment by nickvergessen** [comment]
@DeepDiver1975 too late for language changes, or still okay?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 too late for language changes, or still okay?

still okay from my pov

**Pull request merged**
