### PR TITLE
[stable9] Chunk upload for GDrive

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/23323 to stable9

Please review @icewind1991 @LukasReschke @schiesbn @Xenopathic @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
@owncloud/qa can you help testing ?

**Comment by SergioBertolinSG** [comment]
Works fine :+1: 

A problem with an upload happened once, but not reproducible. Logs here http://paste.debian.net/417740/

**Comment by PVince81** [comment]
Looks like the error you saw was a connection failed to the GDrive server in the constructor.

**Comment by PVince81** [comment]
@icewind1991 second review ?

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
