### PR TITLE
[stable9] Update files_external's icewind/streams to 0.5.2

### PR DESCRIPTION
**Pull request by PVince81**
Update of icewind/streams library in stable9 as backport of https://github.com/owncloud/core/pull/26974

Please review @jvillafanez @DeepDiver1975 

I had a quick test with SMB and it worked fine.

### CODE REVIEW

**Comment by jvillafanez** [comment]
Changes for the streams/src/RetryWrapper.php file didn't show up in the PRs for 9.1 and master. Are those changes the ones between 0.4 and 0.4.1?

**Comment by PVince81** [comment]
Fix travis syntax error.

@jvillafanez https://github.com/icewind1991/Streams/compare/0.4.0...0.4.1 apparently RetryWrapper was indeed changed there

**Comment by jvillafanez** [comment]
changes look fine except for the syntax error.

**Comment by PVince81** [comment]
Green on Jenkins, interpreting @jvillafanez's as a thumbs up.

**Pull request merged**
