### PR TITLE
[full-ci] Bump PHP dependencies (since release-10.9.0)

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Bump PHP  dependencies:
1) "league" releases:
- league/flysystem (1.1.5 to 1.1.6)
- league/mime-type-detection (1.8.0 to 1.9.0)

2) https://symfony.com/blog/symfony-4-4-34-released
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 8 updates, 0 removals
  - Upgrading symfony/console (v4.4.33 => v4.4.34)
  - Locking symfony/deprecation-contracts (v2.5.0)
  - Upgrading symfony/event-dispatcher (v4.4.30 => v4.4.34)
  - Upgrading symfony/event-dispatcher-contracts (v1.1.9 => v1.1.11)
  - Upgrading symfony/process (v4.4.30 => v4.4.34)
  - Upgrading symfony/routing (v4.4.30 => v4.4.34)
  - Upgrading symfony/service-contracts (v2.4.0 => v2.5.0)
  - Upgrading symfony/translation (v4.4.32 => v4.4.34)
  - Upgrading symfony/translation-contracts (v2.4.0 => v2.5.0)
Writing lock file
```

3) next group of dependencies as at 2021-11-29:
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 6 updates, 0 removals
  - Upgrading doctrine/dbal (2.13.5 => 2.13.6)
  - Upgrading laminas/laminas-inputfilter (2.12.0 => 2.12.1)
  - Upgrading league/flysystem (1.1.6 => 1.1.8)
  - Upgrading phpseclib/phpseclib (3.0.11 => 3.0.12)
  - Upgrading roave/security-advisories (dev-master 40581b6 => dev-master 6f99479)
  - Upgrading symfony/process (v4.4.34 => v4.4.35)
Writing lock file
```

https://github.com/doctrine/dbal/releases/tag/2.13.6
https://github.com/laminas/laminas-inputfilter/releases/tag/2.12.1
https://github.com/thephpleague/flysystem/releases/tag/1.1.8
https://github.com/thephpleague/flysystem/releases/tag/1.1.7
https://github.com/phpseclib/phpseclib/releases/tag/3.0.12
https://symfony.com/blog/symfony-4-4-35-released

4)  Update sabre/dav (4.2.0 => 4.2.1)
Note: `nikic/php-parser` is a dev dependency, so no need to add to the changelog.

```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Upgrading nikic/php-parser (v4.13.1 => v4.13.2)
  - Upgrading sabre/dav (4.2.0 => 4.2.1)
Writing lock file
```

5) https://github.com/laminas/laminas-validator/releases/tag/2.15.1
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 3 updates, 0 removals
  - Upgrading laminas/laminas-validator (2.15.0 => 2.15.1)
  - Upgrading phpunit/php-file-iterator (3.0.5 => 3.0.6)
  - Upgrading roave/security-advisories (dev-master 6f99479 => dev-master 344cf93)
Writing lock file
```

`phpunit/php-file-iterator` is only a dev dependency.

6) Upgrading phpunit/php-code-coverage (9.2.9 => 9.2.10)

7) Upgrading sabre/vobject (4.4.0 => 4.4.1)

8) Upgrading laminas/laminas-stdlib (3.6.1 => 3.6.2)

9) Upgrading phpspec/prophecy (1.14.0 => v1.15.0)

10) Upgrading sabre/dav (4.2.1 => 4.2.2)

11) dav and flysystem again
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Upgrading league/flysystem (1.1.8 => 1.1.9)
  - Upgrading sabre/dav (4.2.2 => 4.2.3)
Writing lock file
```

12) Upgrading sabre/dav (4.2.3 => 4.3.0) 

13) Upgrading laminas/laminas-zendframework-bridge (1.4.0 => 1.4.1)

IMO there are no critical fixes in the above, so this does not have to get into 10.9.0

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
I don't think that there is anything important to get into 10.9.0. So I started new changelog files for dependencies, and this can be left in draft until 10.9.0 is further progressed.

**Comment by phil-davis** [comment]
This supersedes #39520 #39521 #39522 #39523 #39524 #39526 PRs that the bot raised for each individual component of the symfony patch release.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiSharePublicLink2-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/33808/72/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/33808/72/13
```
  @issue-ocis-reva-373 @issue-37683
  Scenario: Copy folder within a public link folder to the same folder name as an already existing file # /drone/src/tests/acceptance/features/apiSharePublicLink2/copyFromPublicLinkOc10Issue37683.feature:9
    Given user "Alice" has created folder "/PARENT/testFolder"                                          # FeatureContext::userHasCreatedFolder()
    And user "Alice" has uploaded file with content "some data" to "/PARENT/testFolder/testfile.txt"    # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "some data 1" to "/PARENT/copy1.txt"                # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has created a public link share with settings                                      # FeatureContext::userHasCreatedAPublicLinkShareWithSettings()
      | path        | /PARENT                   |
      | permissions | read,update,create,delete |
    When the public copies folder "/testFolder" to "/copy1.txt" using the new public WebDAV API         # PublicWebDavContext::thePublicCopiesFileUsingTheWebDAVApi()
    Then the HTTP status code should be "204"                                                           # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And as "Alice" folder "/PARENT/testFolder" should exist                                             # FeatureContext::asFileOrFolderShouldExist()
    And as "Alice" folder "/PARENT/copy1.txt" should exist                                              # FeatureContext::asFileOrFolderShouldExist()
    And as "Alice" file "/PARENT/copy1.txt/testfile.txt" should exist                                   # FeatureContext::asFileOrFolderShouldExist()
    And the content of file "/PARENT/testFolder/testfile.txt" for user "Alice" should be "some data"    # FeatureContext::contentOfFileForUserShouldBe()
    And the content of file "/PARENT/copy1.txt/testfile.txt" for user "Alice" should be "some data"     # FeatureContext::contentOfFileForUserShouldBe()
      The downloaded content was expected to be 'some data', but actually is '<?xml version="1.0" encoding="utf-8"?>
      <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
        <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
        <s:message>Could not open file</s:message>
      </d:error>
      '. HTTP status was 503
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -'some data'
      +'<?xml version="1.0" encoding="utf-8"?>\n
      +<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n
      +  <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>\n
      +  <s:message>Could not open file</s:message>\n
      +</d:error>\n
      +'
```

I will restart CI to see if this repeats.

**Review by JammingBen — APPROVED** [review]

**Review by AlexAndBear — APPROVED** [review]

**Pull request merged**
