### PR TITLE
add item_source index

### PR DESCRIPTION
**Pull request by butonic**
```sql
EXPLAIN SELECT * FROM `oc_share` WHERE `item_source` = '1410';
+------+-------------+----------+------+---------------+------+---------+------+------+-------------+
| id   | select_type | table    | type | possible_keys | key  | key_len | ref  | rows | Extra       |
+------+-------------+----------+------+---------------+------+---------+------+------+-------------+
|    1 | SIMPLE      | oc_share | ALL  | NULL          | NULL | NULL    | NULL | 2998 | Using where |
+------+-------------+----------+------+---------------+------+---------+------+------+-------------+
1 row in set (0.00 sec)

CREATE INDEX item_source_index ON oc_share (item_source);
Query OK, 0 rows affected (0.09 sec)
Records: 0  Duplicates: 0  Warnings: 0

EXPLAIN SELECT * FROM `oc_share` WHERE `item_source` = '1410';
+------+-------------+----------+------+-------------------+-------------------+---------+-------+------+-----------------------+
| id   | select_type | table    | type | possible_keys     | key               | key_len | ref   | rows | Extra                 |
+------+-------------+----------+------+-------------------+-------------------+---------+-------+------+-----------------------+
|    1 | SIMPLE      | oc_share | ref  | item_source_index | item_source_index | 768     | const |    1 | Using index condition |
+------+-------------+----------+------+-------------------+-------------------+---------+-------+------+-----------------------+
1 row in set (0.00 sec)
```

or more visually:

6d6184662f97bf8dd753c3c1a8d82e83249ba075645632b752 pimgpsh_fullsize_distr

index added at 15:45

### CODE REVIEW

**Comment by butonic** [comment]
@DeepDiver1975 backport to 10 in https://github.com/owncloud/core/pull/29592

**Comment by DeepDiver1975** [comment]
there is no coverage on the migrations ... this is because they are executed on installation where no coverage is collected.

@PVince81 @butonic general question: shall we exclude migrations from coverage?

**Comment by butonic** [comment]
@patrickjahns any ideas for testing migrations with your docker toobox?

**Comment by patrickjahns** [comment]
What do you want to test? 
Upgrading owncloud, or if migrations are successfully executed?

If the later - I've only seen database migration tests when we based our projects on doctrine migrations.
Wet let the migrations execute, and them compare if `schema:update` would still would detect changes / differences between database and entity model. (Assuming developers populated their migrations properly and they we're in sync with the entities).

Since we don't have this luxury currently - we might need to discuss how/when we want to test migrations. 
Guess best approach would be, to have a pre-migration schema/dump and a post-migration schema/dump and compare if executing the migration would result in the desired effect?

**Comment by tomneedham** [comment]
> What do you want to test?

a lot of the time its just checking that nothing explodes on the various matrices of db platforms - since by default we dont run these in tests automagically

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
