### PR TITLE
Add assertion to test

### PR DESCRIPTION
**Pull request by LukasReschke**
This seems to be missing on that test.

@blizzz Please confirm.

### CODE REVIEW

**Comment by blizzz** [comment]
Not really missing, but it's a good addition :+1:  If setting the empty string would not succeed, an Exception would be thrown. That one will be thrown is for instance ensured here https://github.com/owncloud/core/blob/fix-risky-test-comments/tests/lib/comments/comment.php#L50

**Comment by blizzz** [comment]
another thumb? @icewind1991 @nickvergessen

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> Not really missing, but it's a good addition

tests require an assertion

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
