### PR TITLE
Add occ files_external:create command to add new mounts

### PR DESCRIPTION
**Pull request by icewind1991**
Also adds `occ files_external:backends` to get a list of available authentication and their config options

Usage example:

usage

All input (auth and storage backend identifiers, config options and username) is validated and proper errors are show.

Both `files_external:backends` and `files_external:create` support json output which makes it possible to create 3rdparty tools for creating mounts that automatically read the available backends and their required options.

cc @PVince81 @Xenopathic

### CODE REVIEW

**Comment by PVince81** [comment]
That backends command is great.
Can you add a row "supported auth backends" maybe ?

**Comment by PVince81** [comment]
- [ ] BUG: do not allow create two mount points with the same path (ex: create SFTP using the mount point path "sftp" twice)

- [ ] TODO: add "support authentication backends" fields in "files_external:backends" output

Otherwise this seems to work fine.

**Comment by PVince81** [comment]
- [ ] TODO: after creating a mount, show a message that includes the mount id

Always keep in mind that some people might want to script this, so everything that can be output could be useful as such :smile:

**Comment by PVince81** [comment]
@icewind1991 please always reference the matching ticket, I'm getting tired of always having to do this myself. Thanks.

**Comment by PVince81** [comment]
REf https://github.com/owncloud/core/issues/20368#issuecomment-157761007

**Comment by icewind1991** [comment]
- list supported auth backends for each storage backend
- verify that the auth backend is valid for the storage on create
- output mount id on create

**Comment by icewind1991** [comment]
> do not allow create two mount points with the same path (ex: create SFTP using the mount point path "sftp" twice)

Not really easy to check due to things like applicables etc, the web ui also allows creating mounts with the same mount points

**Comment by PVince81** [comment]
Tested, works :+1: 
Great stuff!

**Comment by PVince81** [comment]
Needs a second reviewer @jmaciasportela @Xenopathic @SergioBertolinSG

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
