### PR TITLE
console commands shall not be limited with respect to execution time

### LINKED ISSUE #14156: occ upgrade fail "Maximum execution time of 3600 seconds exceeded"
Applied this patch nlegoff/dbal@7f89a78317808a4cdf271bb5e4740c06d230c2d8 to fix this issue #14003 but still doesn't upgrade and Owncloud is stuck in maintenance mode even when you set it to false in the config.

```bash
 sudo -u www-data php /var/www/owncloud/occ upgrade
Turned on maintenance mode
Checked database schema update
Updated database
PHP Fatal error:  Maximum execution time of 3600 seconds exceeded in /var/www/owncloud/lib/private/fileproxy.php on line 118
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #14156

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@karlitschek we might want to think about backporting this to all stable branches

**Comment by DeepDiver1975** [comment]
@icewind1991 @MorrisJobke please review - THX

**Comment by icewind1991** [comment]
Makes sense :+1:

**Comment by MorrisJobke** [comment]
works :+1:

**Comment by karlitschek** [comment]
please backport

**Comment by DeepDiver1975** [comment]
stable8: https://github.com/owncloud/core/pull/14253

**Pull request merged**
