### PR TITLE
Added Opus Mimetype Support

### PR DESCRIPTION
**Pull request by aidanamavi**
Added Opus audio mimetype support.

### CODE REVIEW

**Comment by aidanamavi** [comment]
@owncloud-bot I signed and sent the contributor's agreement some time ago, but thanks for the reminder. 

Reviews please @jancborchardt @DeepDiver1975 @wurstchristoph @irgendwie

**Comment by jancborchardt** [comment]
@karlitschek can you add @aidanamavi to the org then, if we signed and sent the contributor agreement? :)

:+1: for this change. Another review please @icewind1991 @schiesbn

**Comment by karlitschek** [comment]
Cool. I added @aidanamavi to the developer group. Will add to core-developer after I got the contributor agreement :)

**Comment by aidanamavi** [comment]
@karlitschek Thanks for the addition. :) Should I resend the signed agreement? I sent it a couple of weeks ago.

**Comment by karlitschek** [comment]
hmm. strange. can you send it again to frank at owncloud org please?
Thanks

**Comment by icewind1991** [comment]
:+1:

**Comment by jancborchardt** [comment]
Btw @aidanamavi do you also want to be added to the @owncloud/designers group? That means that you will get notified of issues where we mention the design team with @owncloud/designers. :)

**Comment by aidanamavi** [comment]
@jancborchardt I'd love to. Thanks for the invitation. :)

**Comment by jancborchardt** [comment]
@aidanamavi cool! @karlitschek can you add @aidanamavi to @owncloud/designers please? :)

**Comment by karlitschek** [comment]
done :-)

**Comment by jancborchardt** [comment]
Great stuff, welcome @aidanamavi to the ownCloud Design Team! :rocket:

**Pull request merged**
