### PR TITLE
[9.0] Update icewind/streams and icewind/smb

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of #23351

Requires https://github.com/owncloud/3rdparty/pull/262

### CODE REVIEW

**Comment by PVince81** [comment]
Tested SMB, still works :+1:

I'm not too happy about those changes in the CallbackWrapper though, which could affect other parts of the code

**Comment by schiesbn** [comment]
:+1:

**Comment by schiesbn** [comment]
Just saw that the backport was not yet approved by @karlitschek, so back to "to review"

**Comment by karlitschek** [comment]
o.k. please backport :+1:

**Comment by PVince81** [comment]
annnnd ack to "To Release" :smile: 

@DeepDiver1975 nudge nudge, also merge https://github.com/owncloud/core/pull/23351

**Comment by PVince81** [comment]
WAIT, the submodule has a conflict. https://github.com/owncloud/3rdparty/pull/262

**Comment by icewind1991** [comment]
rebased

**Comment by PVince81** [comment]
Merged 3rdparty and updated 3rdparty commit again.

Now as soon as CI passes we can merge this.

**Comment by DeepDiver1975** [comment]
conflicting

**Comment by PVince81** [comment]
This third party is really a buzzkill.

**Comment by PVince81** [comment]
Rebased onto origin/stable9 and adjusted 3rdparty commit

**Comment by schiesbn** [comment]
Maybe we need another rebase? Test already running for 15 hours...

**Comment by DeepDiver1975** [comment]
There have been some github hickups ....

**Comment by PVince81** [comment]
> github hickups

ghick-hubs

PunFailedException :disappointed:

**Comment by schiesbn** [comment]
after 4 hours I don't think we have to wait for Scrutinizer... Can we merge it?

**Pull request merged**
