### PR TITLE
add list routes command

### PR DESCRIPTION
**Pull request by butonic**
@tomneedham since we keep getting asked which routes oc uses.

produces:
```
$ ./occ security:routes
+-----------------------------------------------------------+-----------------+
| Path                                                      | Methods         |
+-----------------------------------------------------------+-----------------+
| /apps/activity/                                           | GET             |
| /apps/activity/api/v2/activity                            | GET             |
| /apps/activity/api/v2/activity/{filter}                   | GET             |
| /apps/activity/rss.php                                    | GET             |
| /apps/activity/settings                                   | POST            |
| /apps/activity/settings/feed                              | POST            |
| /apps/federation/auto-add-servers                         | POST            |
| /apps/federation/trusted-servers                          | POST            |
| /apps/federation/trusted-servers/{id}                     | DELETE          |
| /apps/files/                                              | GET             |
| /apps/files/ajax/download.php                             |                 |
| /apps/files/ajax/getstoragestats.php                      |                 |
| /apps/files/ajax/list.php                                 |                 |
| /apps/files/ajax/setupload.php                            |                 |
| /apps/files/api/v1/files/{path}                           | POST            |
| /apps/files/api/v1/showhidden                             | POST            |
| /apps/files/api/v1/sorting                                | POST            |
| /apps/files/api/v1/thumbnail/{x}/{y}/{file}               | GET             |
| /apps/files/download{file}                                |                 |
| /apps/files_external/ajax/oauth1.php                      |                 |
| /apps/files_external/ajax/oauth2.php                      |                 |
| /apps/files_external/ajax/public_key.php                  | POST            |
| /apps/files_external/applicable                           |                 |
| /apps/files_external/globalstorages                       | GET,POST        |
| /apps/files_external/globalstorages/{id}                  | DELETE,GET,PUT  |
| /apps/files_external/userglobalstorages                   | GET,POST        |
| /apps/files_external/userglobalstorages/{id}              | DELETE,GET,PUT  |
| /apps/files_external/userstorages                         | GET,POST        |
| /apps/files_external/userstorages/{id}                    | DELETE,GET,PUT  |
| /apps/files_external_dropbox/oauth                        | POST            |
| /apps/files_sharing/ajax/list.php                         |                 |
| /apps/files_sharing/ajax/publicpreview.php                |                 |
| /apps/files_sharing/api/externalShares                    | GET,POST        |
| /apps/files_sharing/api/externalShares/{id}               | DELETE,GET,PUT  |
| /apps/files_sharing/external                              |                 |
| /apps/files_sharing/publicpreview                         |                 |
| /apps/files_sharing/shareinfo                             |                 |
| /apps/files_sharing/testremote                            | GET             |
| /apps/files_trashbin/ajax/delete.php                      |                 |
| /apps/files_trashbin/ajax/isEmpty.php                     |                 |
| /apps/files_trashbin/ajax/list.php                        |                 |
| /apps/files_trashbin/ajax/preview.php                     |                 |
| /apps/files_trashbin/ajax/undelete.php                    |                 |
| /apps/files_versions/ajax/getVersions.php                 |                 |
| /apps/files_versions/ajax/rollbackVersion.php             |                 |
| /apps/files_versions/download.php                         |                 |
| /apps/files_versions/preview                              |                 |
| /apps/updatenotification/channel                          | POST            |
| /apps/updatenotification/credentials                      | GET             |
| /apps/user_ldap/ajax/clearMappings.php                    |                 |
| /apps/user_ldap/ajax/deleteConfiguration.php              |                 |
| /apps/user_ldap/ajax/getConfiguration.php                 |                 |
| /apps/user_ldap/ajax/getNewServerConfigPrefix.php         |                 |
| /apps/user_ldap/ajax/setConfiguration.php                 |                 |
| /apps/user_ldap/ajax/testConfiguration.php                |                 |
| /apps/user_ldap/ajax/wizard.php                           |                 |
| /apps/user_shibboleth/envSourceConfig                     | GET,PUT         |
| /apps/user_shibboleth/mode                                | GET,PUT         |
| /apps/user_shibboleth/timezone                            | POST            |
| /avatar/                                                  | DELETE,POST     |
| /avatar/cropped                                           | POST            |
| /avatar/tmp                                               | GET             |
| /avatar/{userId}/{size}                                   | GET             |
| /core/ajax/appconfig.php                                  |                 |
| /core/ajax/share.php                                      |                 |
| /core/ajax/update.php                                     |                 |
| /core/js/oc.js                                            |                 |
| /core/preview.png                                         |                 |
| /core/search                                              |                 |
| /displaynames                                             | POST            |
| /f/{fileId}                                               |                 |
| /heartbeat                                                |                 |
| /login                                                    | GET,POST        |
| /login/challenge/{challengeProviderId}                    | GET,POST        |
| /login/selectchallenge                                    | GET             |
| /logout                                                   | GET             |
| /lostpassword/email                                       | POST            |
| /lostpassword/reset/form/{token}/{userId}                 | GET             |
| /lostpassword/set/{token}/{userId}                        | POST            |
| /occ/{command}                                            | POST            |
| /ocs/apps/files_external/api/v1/mounts                    | GET             |
| /ocs/apps/files_sharing/api/v1/remote_shares              | GET             |
| /ocs/apps/files_sharing/api/v1/remote_shares/pending      | GET             |
| /ocs/apps/files_sharing/api/v1/remote_shares/pending/{id} | DELETE,POST     |
| /ocs/apps/files_sharing/api/v1/remote_shares/{id}         | DELETE,GET      |
| /ocs/apps/files_sharing/api/v1/shares                     | GET,POST        |
| /ocs/apps/files_sharing/api/v1/shares/{id}                | DELETE,GET,PUT  |
| /ocs/cloud/activity                                       | GET             |
| /ocs/cloud/apps                                           | GET             |
| /ocs/cloud/apps/{appid}                                   | DELETE,GET,POST |
| /ocs/cloud/groups                                         | GET,POST        |
| /ocs/cloud/groups/{groupid}                               | DELETE,GET      |
| /ocs/cloud/groups/{groupid}/subadmins                     | GET             |
| /ocs/cloud/shares                                         | POST            |
| /ocs/cloud/shares/{id}/accept                             | POST            |
| /ocs/cloud/shares/{id}/decline                            | POST            |
| /ocs/cloud/shares/{id}/permissions                        | POST            |
| /ocs/cloud/shares/{id}/reshare                            | POST            |
| /ocs/cloud/shares/{id}/revoke                             | POST            |
| /ocs/cloud/shares/{id}/unshare                            | POST            |
| /ocs/cloud/users                                          | GET,POST        |
| /ocs/cloud/users/{userid}                                 | DELETE,GET,PUT  |
| /ocs/cloud/users/{userid}/disable                         | PUT             |
| /ocs/cloud/users/{userid}/enable                          | PUT             |
| /ocs/cloud/users/{userid}/groups                          | DELETE,GET,POST |
| /ocs/cloud/users/{userid}/subadmins                       | DELETE,GET,POST |
| /ocs/config                                               | GET             |
| /ocs/person/check                                         | POST            |
| /ocs/privatedata/deleteattribute/{app}/{key}              | POST            |
| /ocs/privatedata/getattribute                             | GET             |
| /ocs/privatedata/getattribute/{app}                       | GET             |
| /ocs/privatedata/getattribute/{app}/{key}                 | GET             |
| /ocs/privatedata/setattribute/{app}/{key}                 | POST            |
| /ocsapp/apps/federation/api/v1/request-shared-secret      | POST            |
| /ocsapp/apps/federation/api/v1/shared-secret              | GET             |
| /ocsapp/apps/files_sharing/api/v1/sharees                 | GET             |
| /ocsapp/cloud/capabilities                                | GET             |
| /ocsapp/cloud/user                                        | GET             |
| /s/{token}                                                |                 |
| /s/{token}/authenticate                                   | GET,POST        |
| /s/{token}/download                                       | GET             |
| /settings/admin                                           | GET             |
| /settings/admin/certificate                               | POST            |
| /settings/admin/certificate/{certificateIdentifier}       | DELETE          |
| /settings/admin/log/download                              | GET             |
| /settings/admin/log/level                                 | POST            |
| /settings/admin/mailsettings                              | POST            |
| /settings/admin/mailsettings/credentials                  | POST            |
| /settings/admin/mailtest                                  | POST            |
| /settings/admin/startmigration                            | POST            |
| /settings/admin/{id}/mailAddress                          | PUT             |
| /settings/ajax/changegroupname.php                        |                 |
| /settings/ajax/checksetup                                 | GET             |
| /settings/ajax/disableapp.php                             |                 |
| /settings/ajax/enableapp.php                              |                 |
| /settings/ajax/excludegroups.php                          |                 |
| /settings/ajax/navigationdetect.php                       |                 |
| /settings/ajax/setlanguage.php                            |                 |
| /settings/ajax/setquota.php                               |                 |
| /settings/ajax/togglegroups.php                           |                 |
| /settings/ajax/togglesubadmins.php                        |                 |
| /settings/ajax/uninstallapp.php                           |                 |
| /settings/ajax/updateapp.php                              |                 |
| /settings/apps/list                                       | GET             |
| /settings/help                                            |                 |
| /settings/integrity/failed                                | GET             |
| /settings/integrity/rescan                                | GET             |
| /settings/mailaddress/change/{token}/{userId}             | GET             |
| /settings/personal                                        | GET             |
| /settings/personal/authtokens                             | GET,POST        |
| /settings/personal/authtokens/{id}                        | DELETE,GET,PUT  |
| /settings/personal/certificate                            | POST            |
| /settings/personal/certificate/{certificateIdentifier}    | DELETE          |
| /settings/personal/changepassword                         | POST            |
| /settings/users                                           |                 |
| /settings/users/changepassword                            | POST            |
| /settings/users/groups                                    | GET,POST        |
| /settings/users/groups/{id}                               | DELETE,GET,PUT  |
| /settings/users/stats                                     | GET             |
| /settings/users/users                                     | GET,POST        |
| /settings/users/users/{id}                                | DELETE,GET,PUT  |
| /settings/users/{id}/enabled                              | POST            |
| /settings/users/{id}/mailAddress                          | PUT             |
| /settings/users/{username}/displayName                    | POST            |
| /token/generate                                           | POST            |
+-----------------------------------------------------------+-----------------+
```

json is available as well. needs backport to 10.0.2

### CODE REVIEW

**Comment by butonic** [comment]
cc @dercorn could you test this patch with 10.0.2?

**Comment by mmattel** [comment]
Please do not forget a documentation PR

**Comment by phil-davis** [comment]
works fine when cherry-picked back on top of stable10 (which would make its way into 10.0.3 if this gets promptly merged and backported)
looks like "a good thing" to me

**Comment by tomneedham** [comment]
All looks sensible and well done. Like that it even shows off the parameters in the routes. 👍

**Review by tomneedham — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
Hail to duplicate work .... https://github.com/owncloud/core/pull/28642

**Comment by phil-davis** [comment]
Backport stable10 #28907 
@butonic @tomneedham I made a "prospective" backport since that will allow the CI for it to run before European office time. If this code here in master is merged as-is, then the backport can also be merges as-is to stable10.

**Comment by phil-davis** [comment]
One of the Travis jobs got the random:
```
exception 'SensioLabs\Behat\PageObjectExtension\PageObject\Exception\UnexpectedPageException' with message 'Expected to be on "http://owncloud:8889/index.php/apps/files/" but found "http://owncloud:8889/index.php/login?redirect_url=%252Findex.php%252Fapps%252Ffiles%252F" instead' in /home/travis/build/owncloud/core/tests/ui/features/lib/FilesPage.php:463
```
sometimes "the system" forgets the user is logged in and takes the user (the test driver) unexpectedly back to the login page. I would love to know why.

I restarted the Travis job.

**Comment by butonic** [comment]
hm in https://github.com/owncloud/core/pull/28642#issuecomment-323352366 asked about webdav routes. absent here as well ... hm cc @dercorn

**Pull request merged**
