### PR TITLE
Fix password strength meter tooltip message

### PR DESCRIPTION
**Pull request by Maddoc42**
## Description

Fix the password field strength indicator tooltip message not being updated when typing.

Changes:
- Upgrade strengthify to v 0.5.0
- Load OC css file after strengthify css under settings/personal
## Related Issue
#24422
## How Has This Been Tested?

Personal machine, Chrome 53.0.2785.143, Ubuntu 14.04
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Looks good to me - THX

One thing: when scrolling the tooltip will stay absolute on the screen and doesn't follow the input field.

maybe the tooltip is attached to the wrong element?

@Maddoc42 wana have a look at this as well? THX

**Comment by Maddoc42** [comment]
@DeepDiver1975 sure thing! The tooltips seem stuck in position on multiple pages, not just the settings page (for example /apps/files the last modified timestamp). 

The problem was an outdated version of bootstrap tooltip.css (prior 3.3.5, now 3.3.6). I copied the relevant section from https://github.com/twbs/bootstrap/blob/v3.3.6/dist/css/bootstrap.css.

**Comment by DeepDiver1975** [comment]
> The problem was an outdated version of bootstrap tooltip.css (prior 3.3.5, now 3.3.6).

cool - nice finding.

Any objections in updating bootstrap fully in bower.json? THX

**Comment by PVince81** [comment]
> Any objections in updating bootstrap fully in bower.json?

Not sure... hope it doesn't break other things. But minor updates shouldn't.
Let's try it ?

**Comment by Maddoc42** [comment]
Correct me if I'm wrong, but bower already is a 3.3.6. It should contain the tooltip.css, so maybe remove that completely? I'll try that ...

**Comment by Maddoc42** [comment]
Bootstrap has one *.less file for each component, but when compiled those are bundled together in one big css file. Hence the dependency in bower does not provide a tooltip.css, but rather the whole bootstrap.css :see_no_evil: 

Since OC does not seem to use this bootstrap.css and also does not have a less to css "compile" step (please correct if mistaken), including a precompiled tooltip.css under core/css actually makes sense :+1:

So all done from my side :rocket:

**Comment by DeepDiver1975** [comment]
Awesome! THX :+1:

**Comment by DeepDiver1975** [comment]
failing jenkins can be ignores - it's on integration tests

**Comment by PVince81** [comment]
yeah, let's look into that bootstrap + bower thing separately...

:+1:

**Pull request merged**
