### PR TITLE
[tests-only][full-ci]Donot set OCC status code for all steps

### PR DESCRIPTION
**Pull request by kiranadh1452**
## Description
This PR changes the implementation structure of setting occ status code.

## Related Issue
- #40351 

## Motivation and Context
Instead of trying to reset the occ status code, the implementation structure has been modified such that occ status code is not set for such cases where reset is required.

## How Has This Been Tested?

- locally
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>cliExternalStorage-10.9.1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36816/132

**Review by SwikritiT — COMMENTED** [review]
LGTM

**Comment by phil-davis** [comment]
CI only failed because of fsweb Windows server being down - the 2 related unit test pipelines can't pass.

**Review by phil-davis — APPROVED** [review]

**Comment by grgprarup** [comment]
@kiranadh1452 The PR description doesn't relate to the changes made.

**Comment by kiranadh1452** [comment]
> @kiranadh1452 The PR description doesn't relate to the changes made.

Oops, missed this comment for months. Fixed it

**Pull request merged**
