### PR TITLE
allow user to configure automatically accept incoming federated share…

### PR DESCRIPTION
**Pull request by karakayasemi**
## Description
Let the users decide whether they want to manually accept federated shares from a trusted server or not. 

- Also, I moved all the old panels to new `Panels` folder in the code base and refactored Panel related files by including section names to their filename.
## Related Issue
- Continuation of #34593, `federatedfilesharing` part of https://github.com/owncloud/enterprise/issues/3128 .`

## Motivation and Context
some users will not want that shares are accepted automatically.

## How Has This Been Tested?
Unit tests are added. Manually tested by installing two instance and applying the following steps:
- When global `auto_accept_trusted` enabled for federated files sharing, go Sharing Personal Panel and disable auto_accept_share_trusted` forFederated Cloud Sharing, the next share from a trusted server should be on the pending status.
- When global `auto_accept_trusted` enabled for federated files sharing, go Sharing Personal Panel and enable auto_accept_share_trusted` for Federated Cloud Sharing, the next share from a trusted server should be accepted automatically.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by mmattel** [comment]
Question: is there a documentation change necessary?

**Comment by karakayasemi** [comment]
@mmattel Yes, I will rise documentation ticket for both #34593 and this PR.

**Comment by jvillafanez** [comment]
I forgot to ask: as user, you can choose to automatically accept or not the incoming shares, but you can't choose "whatever the admin decided". Is this known?. I'm not sure if there is a valid use case for this.

Code looks good.

**Comment by karakayasemi** [comment]
@jvillafanez As I understand from here https://github.com/owncloud/enterprise/issues/3128#issuecomment-460246766 , it is decided that to allow users to override the administrator configurations in this topic.

**Comment by jvillafanez** [comment]
It isn't so clear for me... I mean, the user has "yes", "no" or "whatever the admin decided" options, but once the user has actively said "yes" or "no", he doesn't have the option to go back to the "whatever the admin decided" option. In addition, the user has to explicitly set the option: if the admin says "yes", the user can assume "yes", but if the admin changes to "no", since the user hasn't actively set the option to "yes", he will see "no".
This doesn't conflict with the idea of the user overwritting the admin's decision, but it doesn't seem a good UX.

In any case, I guess this is out of scope for this PR because we'll still need to adjust code for the local shares too.

**Review by jvillafanez — APPROVED** [review]
https://github.com/owncloud/core/pull/34655#issuecomment-469269643 if needed, will require new ticket because the changes are out of this PR's scope

**Comment by mmattel** [comment]
Q: if this gets merged, backporting ?

**Comment by karakayasemi** [comment]
> Q: if this gets merged, backporting ?

Yes, backport in open tasks.

**Comment by mmattel** [comment]
Everything green, merging?

**Comment by PVince81** [comment]
@karakayasemi please backport

**Pull request merged**
