### PR TITLE
always return the complete permissions the file was shared with

### PR DESCRIPTION
**Pull request by schiessle**
Always return the complete permissions the file was shared with.
This is needed for https://github.com/owncloud/core/pull/23918 in order to return the correct permissions on webdav requests.

cc @rullzer as discussed, please have a look.

Also a second reviewer needed, maybe @DeepDiver1975 or @nickvergessen ? Thanks!

### CODE REVIEW

**Comment by rullzer** [comment]
:+1: as discussed.

**Comment by nickvergessen** [comment]
As forseen:
> 	Test Result (2 failures / +2)

    sharing.Correct webdav share-permissions for received file with edit permissions but no reshare permissions
    sharing.Correct webdav share-permissions for received folder with all permissions but share

**Comment by schiesbn** [comment]
@nickvergessen all tests passed... time for a +1 :wink:

**Comment by nickvergessen** [comment]
Doesn't break anything else, so :+1:

**Pull request merged**
