### PR TITLE
Update TransferOwnership.php

### PR DESCRIPTION
**Pull request by chagrawil**
date('c') uses colons which do not transfer to Windows clients. Perhaps 'Ymd_his' would work for all clients?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> date('c') uses colons which do not transfer to Windows clients. Perhaps 'Ymd_his' would work for all clients?

Windows? I don't get the use case. Windows is not supported

**Comment by chagrawil** [comment]
I am describing the case for file transfer to clients. Imagine a windows
user who takes over the files from another user:

occ files:transfer-ownership old_user new_user

This will result in a folder, "new_user/files/transferred from old_user on
2017-02-24T10:26:09-05:00", for the transferred files. This folder will not
transfer to Windows clients (using the ownCloud desktop app from
ownCloud-2.2.4.6408-setup.exe, for example) because colons are used in
Windows as a drive-path separator.

Hence the files will properly transfer from one user to the next, but not
from the server to the new_user local folder.

It is my goal to complete the user to user experience.

Does this help explain the requested change?

- Charlie

**Comment by DeepDiver1975** [comment]
Oh. I see.  This is absolutely valid. Thanks for the explanation.

**Comment by PVince81** [comment]
Will the new format parse properly here ? https://github.com/owncloud/core/blob/master/build/integration/features/bootstrap/CommandLineContext.php#L58

For some reason the integration tests still passed, so might be fine.

**Comment by chagrawil** [comment]
I've not the environment to run the test where the [9105.4](https://travis-ci.org/owncloud/core/jobs/204977136) error occurred. It would seem that this is a coincidental problem, not a causal one as
  events.js:72
  throw er; // Unhandled 'error' event
usually means the server:port pair is unavailable. Recommendations for solution focus on killing an errant daemon.

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
