### PR TITLE
Fix installation of shipped apps

### PR DESCRIPTION
**Pull request by DeepDiver1975**
- isolate include calls in installer.php which prevents local variables to be overwritten
- add the app to the autoloader before calling install.php

### CODE REVIEW

**Comment by LukasReschke** [comment]
:+1:

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
Backport was requested here https://github.com/owncloud/core/issues/22625#issuecomment-188430349 and approved.

@LukasReschke you mentionned a specific commit. Can you do the backport ? Should it be a full backport or just the single commit ?

**Comment by PVince81** [comment]
Ok I'll do it myself. Seems it's just that specific commit.

**Comment by MorrisJobke** [comment]
Partial backport to 8.2.3 is here:  https://github.com/owncloud/core/pull/22751

**Pull request merged**
