### PR TITLE
Fixing long filenames / long shared user names clash

### LINKED ISSUE #19790: File name and sharee user name are overlapped
### Steps to reproduce
1. Create a file whose name is quite long
   2.- Share it with a user whose user id is long too, "useruser@owncloud.com"
   3.- Access as "useruser@owncloud.com"
   4.- Click on share
### Expected behaviour

The file name is cut
### Actual behaviour

The file name and the user name is overlapped, see attached image
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

screen shot 2015-10-13 at 11 28 17

### PR DESCRIPTION
**Pull request by LukasReschke**
https://github.com/owncloud/core/pull/19873 on core so CI can ran over it, also squashed the commits.

Fixes https://github.com/owncloud/core/issues/19790

<hr/>

cc @edwardcrompton @schiesbn @jancborchardt @PVince81

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works. Looks also good in the mobile UI :+1: 

cc @owncloud/designers please review

**Comment by jancborchardt** [comment]
@SergioBertolinSG please review as you opened an issue about this.

**Comment by SergioBertolinSG** [comment]
This works fine in english. But in translated languages with a longer word for "shared" it is still being overlapped:

screen shot 2016-01-27 at 09 10 25

**Comment by jancborchardt** [comment]
@edwardcrompton can you give an extra 10px leeway maybe for different languages? I suppose it will still look good in English then.

cc @owncloud/designers … unfortunately we can’t really cut off the »Share« text at a certain width so it never overlaps. Because we never know if the filename is too long.

**Comment by jancborchardt** [comment]
@edwardcrompton can you update it with an extra 10px leeway? :)

**Comment by MorrisJobke** [comment]
> @edwardcrompton can you update it with an extra 10px leeway? :)

I fixed it. Ready for review. I like it and it works here :+1:

**Comment by MorrisJobke** [comment]
@PVince81 @rullzer @owncloud/designers @LukasReschke Please review :)

**Comment by LukasReschke** [comment]
:+1:

**Comment by jancborchardt** [comment]
:+1: looks good. But needs a rebase. Or is this the only-@DeepDiver1975-can-merge-thing again? (I thought Github fixed it)

**Comment by DeepDiver1975** [comment]
@edwardcrompton is this MIT licensed? Otherwise we cannot merge - THX

**Comment by DeepDiver1975** [comment]
> @edwardcrompton is this MIT licensed? Otherwise we cannot merge - THX

@edwardcrompton ping

**Comment by DeepDiver1975** [comment]
removing release label - we still miss the license agreement from @edwardcrompton

**Comment by PVince81** [comment]
Closing due to lack of activity.

Also, maybe a JS approach would be more adequate for calculating the ellipsised width because of the very dynamic sizes. It is likely that these hard-coded values will not cover all cases.

**Comment by PVince81** [comment]
also see https://github.com/owncloud/core/pull/21872#issuecomment-205780646 (license question)

**Comment by skjnldsv** [comment]
@PVince81 stop putting js everywhere! :p 
What css did to you in your early childhood ;)

**Pull request closed without merging**
