### PR TITLE
Do not recurse link share fetching

### PR DESCRIPTION
**Pull request by DeepDiver1975**
- Might fix an issue on oracle

@butonic as discussed
@PVince81 @dragotin @guruz

### CODE REVIEW

**Comment by PVince81** [comment]
Code looks good :+1:

**Comment by butonic** [comment]
works as expected and fixes oracle :+1:

**Comment by PVince81** [comment]
@DeepDiver1975 needs forward port to master ?

**Comment by butonic** [comment]
@PVince81 nope, https://github.com/owncloud/core/blob/master/lib/private/Share20/Manager.php#L926 is what made @DeepDiver1975 question my other array_udiff PR in the first place

**Pull request merged**
