### PR TITLE
Increase the JPEG quality from ~75 to 90

### LINKED ISSUE #20665: Increase default quality for previews to e.g. 90 or 95
Re-Opened https://github.com/owncloud/gallery/issues/465
### Steps to reproduce

```
Upload a bunch of photos to your OC
Open the Gallery app for these photos
Open a single photo (slideshow view)
```
### Expected behaviour

Assuming uploaded photos had proper resolution a sharp photo should appear.
### Actual behaviour

The resolution of the displayed photo fits (so this is not a duplicate to those issues pointing to resolution) but compression artifacts are visible.
Probably due to a low quality on JPEG compression?
### Server configuration

*\* Operating system: **
Ubuntu 14.04 LTS
*\* Web server: **
Apache/2.4.7 (Ubuntu)
*\* Database: **
MySQL
*\* PHP version: **
PHP/5.5.9-1ubuntu4.14 OpenSSL/1.0.1f configured
*\* ownCloud version: *\* (see ownCloud admin page)
8.2.1
### Updated from an older ownCloud or fresh install:

from 8.1.4, didn't test before 8.2.1 however
### Request/Suggestion

Increase preview quality from 75 to at least 90, better 95. Because in full screen as well as in previews already lot's of artifacts are visible.

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #20665

cc @georgehrke @oparoz @jaimy85 @maddylliieeee Please review

### CODE REVIEW

**Comment by LukasReschke** [comment]
Makes sense, file size does not increase massively. That said, needs fixing of the unit tests :wink:

**Comment by MorrisJobke** [comment]
> Makes sense, file size does not increase massively and it works. That said, needs fixing of the unit tests

Done.

**Comment by nickvergessen** [comment]
:+1:

**Comment by oparoz** [comment]
> file size does not increase massively

@LukasReschke Did you test this? We just need to be sure so that it can become the official answer if people start complaining that their ownCloud is 20% slower when browsing their media gallery via their mobile or Gallery.

@MorrisJobke It's not a complete fix for #20665. It increases the quality, yes, but only for new installs. Also, I still feel this setting should be configurable so that users can pick what's best for their use cases.

**Comment by MorrisJobke** [comment]
> @MorrisJobke It's not a complete fix for #20665. It increases the quality, yes, but only for new installs. Also, I still feel this setting should be configurable so that users can pick what's best for their use cases.

We don't want to introduce yet another setting to tweak. We should do the best for all installs. Settings just move the responsibility from the (lazy) developer to the user which is not really useful.

**Comment by oparoz** [comment]
>  Settings just move the responsibility from the (lazy) developer to the user which is not really useful.

I don't agree. We're not all on the same mobile data plan per example (even worse when roaming), etc. . There are already settings for tuning previews (for fixing similar issues with size), this is just another one. 

But we really need some benchmarks to know for sure, because if the difference is something like 5% extra space for previews, then I don't think it matters. If someone has time to test, it should be easy to use the Gallery occ commands on a large sample to compare the results.

**Comment by nickvergessen** [comment]
There are quite some examples out there for size comparisons (of course it always matters which image you have, but for average it works):
http://www.impulseadventure.com/photo/jpeg-compression.html

> We're not all on the same mobile data plan per example (even worse when roaming), etc.

In which case you don't want to have the gallery anyway? :-O

**Comment by oparoz** [comment]
@nickvergessen - Thanks for that article. Looking at the graph, it seems there is a **300%** file size increase. If confirmed, it's far from being negligible.

> In which case you don't want to have the gallery anyway? :-O

Sure, but I don't think it's up to the devs to decide how people should use their ownCloud (a recurrent theme...). I would vote to keep the setting at 75% and to make it possible to easily change to an admin defined value. People serving images to their LAN exclusively will love to be able to see crisp pictures, but other people will appreciate the bandwidth savings that the default setting offer. It's always possible to download the full size image (in mobile apps or Gallery), so it should be a large issue, even if the admin keeps it at 75%.

**Comment by maddylliieeee** [comment]
If many people are against a separate setting, then is it an option to just change the quality for the full size image?
Most people (if not all) won't care about the quality of the smaller previews, but the full size image should user a better quality definitely.
If I recall it correctly the Gallery app uses previews even for the full size image (which I still don't get - why is that??), so can't we change the quality for this particular area only?

For me personally a dedicated setting seems to be the best solution - people should be able to decide themselves based on how they want to use the Gallery.

As of now the Gallery app is useless for people that would like to share high quality photos with friends, family, colleagues or even as a small gallery website replacement (which I was looking forward to) because 70% just doesn't look good enough.

**Comment by oparoz** [comment]
> is it an option to just change the quality for the full size image?

It's more complex than it seems. On an old desktop, you want lowfi for 400x200 thumbnails and you may want hifi for anything above 1000. Now take a recent mid-range mobile phone with a pixel ratio of 3. The thumbnail will be 1200x600 and thus *hifi*, meaning a file which is quite large, but to be displayed on a 5" screen...

Unless we start sending and understanding the ratio in the preview class, I'm not sure we can easily implement your solution.

> If I recall it correctly the Gallery app uses previews even for the full size image (which I still don't get - why is that??)

Nobody wants to download 10+MP pictures on their mobile when watching the slideshow. Even on the desktop, especially if images are served from an embedded device per example.

> As of now the Gallery app is useless for people that would like to share high quality photos with friends, family, colleagues or even as a small gallery website replacement (which I was looking forward to) because 70% just doesn't look good enough.

In the meantime you can apply this PR as a patch and wipe your thumbnails.

**Comment by maddylliieeee** [comment]
>It's more complex than it seems. On an old desktop, you want lowfi for 400x200 thumbnails and you may want hifi for anything above 1000. Now take a recent mid-range mobile phone with a pixel ratio of 3. The thumbnail will be 1200x600 and thus hifi, meaning a file which is quite large, but to be displayed on a 5" screen...

I agree that we need to consider mobile users as well, but I don't agree on the sizes you mention  - 3 examples for "decent" mobiles:

Samsung Galaxy S6: 2560x1440
Samsung Galaxy S5: 1920 x 1080
Motorola Moto G 1st gen (2013): 1280x720
iPhone 5 (2012): 1136 x 640

So even the very affordable Moto G has more than 1200 pixels.

But to get back to the quality topic - if we had a dedicated setting people could decide themselves how much their Gallery will be optimized for mobile users. I don't know how many people use the mobile slideshow frequently, but if they do I would expect them to do it via wifi anyway to save the valuable mobile data.

I will apply this fix manually and do some checks for file sizes and speed in my instance.
Question: Will I have to apply this again after each OC update I am going to install?

**Comment by oparoz** [comment]
> but I don't agree on the sizes you mention

I think I need to explain it better

400x200 thumbnails x 3 (dpr) = 1200x600 thumbnails which will be download at 95% quality instead of 75% quality, thus wasting lots of bandwidth.

> if they do I would expect them to do it via wifi anyway to save the valuable mobile data.

I'm not sure. Most people don't think it's going to waste 100MB just to look at a few thumbnails in a Gallery (5MB for 95% quality x 20). They're usually taught that video is bad on a metered plan.

As I mentioned earlier, even a setting won't fix the problem for a heterogeneous user base. Some people will complain about the low quality of large previews, other about the bandwidth wasting...

> Question: Will I have to apply this again after each OC update I am going to install?

Unfortunately, yes, until a solution is found and merged.

**Pull request closed without merging**
