### PR TITLE
Remove commented code

### PR DESCRIPTION
**Pull request by MorrisJobke**
Followup of #17075

cc @Henni @Raydiation @jancborchardt

### CODE REVIEW

**Comment by Xenopathic** [comment]
:+1:

**Comment by Henni** [comment]
:+1:

**Comment by rullzer** [comment]
:+1:

**Comment by jancborchardt** [comment]
The multiselect script was removed, but the multiselect css is still there. Don’t we use multiselect in the users management for group selection? If it’s separately loaded there, then we can remvoe the styles here I guess?

**Pull request merged**
