### PR TITLE
Remove appstoreenabled and assume true

### LINKED ISSUE #27951: Can't install market app when "appstoreenabled" is false in config.php
### Steps

1. Set "appstoreenabled" to false in config.php (it might be set to that value as a result of upgrading from an old version where the admin decided to disabled it, but now the market ignores it)
1. `occ market:install files_texteditor`

### Expected
Install works

### Actual
```
files_texteditor: Installing new app ...
files_texteditor: Can't create app folder. Please fix permissions. /files_texteditor
```

I see in the code that `OC_App::getInstallPath()` returns `false` if "appstoreenabled" is false.

I suggest killing all usages of that variable.

Workaround: remove the variable.

### Versions
10.0.1RC3 / git master

Let's see how complex the fix is to decide whether 10.0.1 or 10.0.2...

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Obsoleted by the market.

## Related Issue
Fixes https://github.com/owncloud/core/issues/27951

## How Has This Been Tested?
Not tested yet...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## TODO

- [ ] test

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
To make this change smaller and ready for 10.0.1 we could just force return true in getSystemConfig implementation.

**Comment by PVince81** [comment]
@DeepDiver1975 or a repair step that sets it to true. We can add that after the code that auto-enables the market. I'll make a PR

**Comment by PVince81** [comment]
@DeepDiver1975 PR to auto-remove the key from config.php if set https://github.com/owncloud/core/pull/27956

**Comment by PVince81** [comment]
maybe we should also auto-remove the value of "appstoreurl" if pointing at the old one... see https://github.com/owncloud/core/issues/28025#issuecomment-304640264

**Comment by PVince81** [comment]
Rebased.

I added `'appstoreenabled' => false` to the config and the market still works.

**Comment by PVince81** [comment]
@VicDeo @DeepDiver1975 please review

**Comment by DeepDiver1975** [comment]
rebased, tests adjusted and config removed from config.sample

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
@PVince81 backport?

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/28714

**Pull request merged**
