### PR TITLE
Cacheappconfig

### PR DESCRIPTION
**Pull request by butonic**
I tried reviving https://github.com/owncloud/core/pull/13417 for an oracle based installation of OC8.2.3 and was rewarded with a status.php page load speedup from ~1080ms down to ~550ms. Oracle has a high connection creation latency (~400-500ms) and I would really like to avoid doing a db trip if possible because they are expensive as well, see https://github.com/owncloud/core/pull/23835 for the fetch cost for status.php

In OC 8 OC_App uses a db query to determine the app versions. In OC9 we are using the AppCache, which creates a cyclic dependency that I removed by removing the app versions from the memcache prefix. @LukasReschke How important are they? AFAICT having them in the cache prefix automagically invalidates the cache on app enable/disable. Couldn't we achieve the same thing by invalidating the cache manually?

What about deleting appconfig entries from the DB when an app is disabled? Currently there are tons of todos in OC_Installer::removeApp() https://github.com/owncloud/core/blob/master/lib/private/installer.php#L493 This is currently not included in the PR.

A review with a db not on the same host / some latency to the db would be nice to verify or falsify my observations.

cc @MorrisJobke @DeepDiver1975 @Xenopathic 

00004686

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> In OC 8 OC_App uses a db query to determine the app versions. In OC9 we are using the AppCache, which creates a cyclic dependency that I removed by removing the app versions from the memcache prefix. @LukasReschke How important are they? AFAICT having them in the cache prefix automagically invalidates the cache on app enable/disable. Couldn't we achieve the same thing by invalidating the cache manually?

In general I'm against this, because it's very likely that this will introduce problems with the cache.

**Comment by MorrisJobke** [comment]
> What about deleting appconfig entries from the DB when an app is disabled? Currently there are tons of todos in OC_Installer::removeApp()

They are needed to run migration steps. We also should remove unneeded tables then, but this could kill user data 🙈

**Comment by DeepDiver1975** [comment]
> Oracle has a high connection creation latency (~400-500ms)

Maybe something to optimize together with the dba?

Furthermore the connection is opened once for each request - so in very specific situations caching might give a performance boost - but for most of the requests the connection will be opened sooner or later.

@butonic Am I missing anything?

**Comment by DeepDiver1975** [comment]
> In general I'm against this, because it's very likely that this will introduce problems with the cache.

I second that - we should by design only cache information which is retrieved from external resources or data which is expensive in creation. AppConfig doesn't fit in here from my understanding.

**Comment by DeepDiver1975** [comment]
> What about deleting appconfig entries from the DB when an app is disabled? Currently there are tons of todos in OC_Installer::removeApp() https://github.com/owncloud/core/blob/master/lib/private/installer.php#L493 This is currently not included in the PR.

Needs a closer look - low prio

**Comment by butonic** [comment]
@DeepDiver1975 Tho proper way of using oracle is to use [Database Resident Connection Pooling](http://php.net/manual/de/oci8.connection.php) (DRCP). It will reuse connections and drastically reduce connection creation time. However, this customer is also using oracle wallet. Testing showed that the connections are not reused when using the wallet. Without the wallet the status.php loads much more reasonable, and I quote:

> wie vermutet, ohne Wallet geht das ganze schneller (status.php 150ms anstelle von 550ms), die ganze Anwendung "flutscht" [...]

They will ping oracle for a statement regarding wallet and DRCP.

That being said large installations I still think it makes sense to try and avoid a db connection for the status.php

**Comment by DeepDiver1975** [comment]
But I seriously see no need to optimize status.php.
The Rest of the application will still suffer from the bad connection performance.

**Comment by DeepDiver1975** [comment]
@butonic I'm closing this - conflicts and I don't see this necessary - THX

**Pull request closed without merging**
