### PR TITLE
Fix failing migration stable9

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of https://github.com/owncloud/core/pull/22911

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Reproduced locally, tested and works :+1:

**Comment by SergioBertolinSG** [comment]
Did the upgrade from 8.2 to this branch, server works correctly, calendars and contacts are in the database. But accesing to the endpoints doesn't show any contact. 
What are the endpoints to connect?
I've tried:
remote.php/dav/addressbooks/principals/users/admin
and
remote.php/dav/addressbooks/system/system/system

**Comment by DeepDiver1975** [comment]
> remote.php/dav/addressbooks/system/system/system

not relevant for this pr - but users first have to be synced using occ command or wait a day until the cron job runs

**Comment by DeepDiver1975** [comment]
> remote.php/dav/addressbooks/principals/users/admin

should be
remote.php/dav/addressbooks/users/admin

**Comment by DeepDiver1975** [comment]
In order to test a failing migration you need to enter an invalid vcal into the old calendar objects table

**Comment by cmonteroluque** [comment]
it looks as if we're ok to merge?

**Comment by PVince81** [comment]
Code looks good, not tested :+1:

**Pull request merged**
