### PR TITLE
Add help & tips admin section

### PR DESCRIPTION
**Pull request by tomneedham**
## Description
Added a new admin section called 'Help & Tips' with an 'i' icon.

## Motivation and Context
https://github.com/owncloud/configreport/pull/12

## How Has This Been Tested?
Tested with https://github.com/owncloud/configreport/pull/12

## Screenshots (if appropriate):
screen shot 2017-03-13 at 20 59 31

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by noveens** [comment]
The second external link for "<a href="https://doc.owncloud.org/server/10.0/go.php?to=admin-monitoring">advanced monitoring</a>" returns a 404 page, please look into that.

rest is fine :+1:

**Comment by imujjwal96** [comment]
@DeepDiver1975 : The following test is failing in all of the recent PRs.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 : The mentioned test is failing in all of the recent PRs.

not really - the relevant change is within this pr

**Comment by imujjwal96** [comment]
@DeepDiver1975 Thought i saw a similar error in the console o/p of my pr. my bad

**Pull request merged**
