### PR TITLE
[stable8] Only use quota stream wrapper on "files"

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/16613 to stable8 (approved here https://github.com/owncloud/core/pull/16613#issuecomment-106545962)

Please review @icewind1991 @MorrisJobke @schiesbn @th3fallen

### CODE REVIEW

**Comment by PVince81** [comment]
Had a quick retest with 0 quota, still works

**Comment by PVince81** [comment]
:bomb: ? Really ?

**Comment by PVince81** [comment]
Ah yes, of course. We use the quota to simulate a copy fail. But now quota isn't applied on the folder because it doesn't start with "files/".

I'll have a look.

**Comment by PVince81** [comment]
Backported the unit tests only from 31e94708f86e21174e4bcfaf33f645dbba1efc1e which makes the tests not rely on the quota to simulate fail but on mocks.
Also backported c4ec8fbeff926e459317829695af1354b4c8ad61 to make that backport work.

**Comment by DeepDiver1975** [comment]
Unit test execution fails:

https://ci.owncloud.org/job/server-master-linux-locking/database=sqlite,label=SLAVE/1/testReport/junit/%28root%29/Test_Lock_MemcacheLockingProvider/testChangeLockToShared/

**Comment by PVince81** [comment]
@DeepDiver1975 wrong ticket

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 wrong ticket

thx

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
