### PR TITLE
Add integration for checksuming for shared files

### PR DESCRIPTION
**Pull request by mrow4a**
Related to issue described here: https://github.com/owncloud/core/pull/32337

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@mrow4a please backport so we can also get this in ``stable10`` nightly QA build tonight. That way all apps will run these overnight.

**Comment by mrow4a** [comment]
@phil-davis could you please cherry-pick it for me? I am out of laptop at the moment

**Comment by phil-davis** [comment]
Backport ``stable10`` #32356

**Comment by phil-davis** [comment]
@mrow4a @DeepDiver1975 this looks good:
- test scenarios pass in ``core`` ``master`` and ``stable10`` branches (i.e. with "ordinary" storage)
- test scenarios pass in ``files_primary_s3`` against ``core`` ``master`` (which is where the code fix has been applied by PR #32337 ) https://drone.owncloud.com/owncloud/files_primary_s3/468/569
- the 2nd test scenario fails in ``files_primary_s3`` against ``core`` ``stable10`` (which has the test scenarios but not the code fix - yet) https://drone.owncloud.com/owncloud/files_primary_s3/468/479

So the code change has not broken an tests against "ordinary" storage and has fixed a test on object storage.

**Pull request merged**
