### PR TITLE
[stable8.2] Check libsmbclient-php as well as smbclient binary

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Backport of #21481, requested by @MorrisJobke 

Please confirm @karlitschek 

cc @icewind1991

### CODE REVIEW

**Comment by Crazyphil** [comment]
I don't want to be notified for random pull requests by @mention-bot everytime. How can I unsubscribe from this "service"?

**Comment by Xenopathic** [comment]
@Crazyphil https://github.com/owncloud/core/blob/master/.mention-bot

**Comment by karlitschek** [comment]
confirmed

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
