### PR TITLE
Integrity check: Return 1 if it is failed. Fixes #22806

### LINKED ISSUE #22806: occ integrity check should return an exit code different than 0 in case of error
### Steps to reproduce
1. Run `sudo -u www-data ./occ integrity:check-core` and verify success (no console message and exit code = 0)
2. Create a new file with any content in the FS inside the ownCloud installation
3. Run again `sudo -u www-data ./occ integrity:check-core`
### Expected behaviour

Error message is shown (through stderr?) and the exit code is different than 0. There could be more exit codes depending on the type of error (new file added, modified file, missing file, etc).
### Actual behaviour

Error message is shown, but the exit code is 0.
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0RC1

**Updated from an older ownCloud or fresh install:** fresh install

This applies to "integrity:check-app", "integrity:check-core", "integrity:sign-app" and "integrity:sign-core"

@LukasReschke

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
If integrity report has entries, exit code will be 1

## Related Issue
#22806

## Motivation and Context
See #22806

## How Has This Been Tested?
In CLI
```
sudo -u www-data ./occ integrity:check-core
echo $?
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 @jvillafanez

**Comment by jvillafanez** [comment]
Just asking: is it too complex to analyze the result there and return different error codes based on whether there are new files present, or files modified, etc? Maybe it isn't worthy.

Anyway this seems good enough looking at the changes 👍

**Comment by PVince81** [comment]
Bad luck apparently:
```
18:19:47 start: start-smb-windows.sh
18:19:47 name: smb-windows
18:20:48 ....................
18:20:48 [ERROR] Server not reachable
18:20:48 stop: stop-smb-windows.sh
```

**Comment by PVince81** [comment]
Rebased for CI

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
