### PR TITLE
Stable9.1 tests md5 homedir

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Backport of https://github.com/owncloud/core/pull/26846, https://github.com/owncloud/core/pull/26865 and https://github.com/owncloud/core/pull/26920

Jenkinsfile has been modified to avoid the use of makefiles.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by SergioBertolinSG** [comment]
Runnning locally tests with alternative home there are some failures:

```
build/integration/features/external-storage.feature:7
build/integration/features/sharing-v1.feature:59
build/integration/features/sharing-v1.feature:80
build/integration/features/sharing-v1.feature:113
build/integration/features/sharing-v1.feature:144
build/integration/features/sharing-v1.feature:174
build/integration/features/sharing-v1.feature:204
build/integration/features/sharing-v1.feature:857
```

**Comment by SergioBertolinSG** [comment]
The problem is related with public shares, it is not detecting a url in the answer:
url doesn't have value AN_URL

**Comment by SergioBertolinSG** [comment]
External storage one is failing because the same reason.

**Comment by SergioBertolinSG** [comment]
The problem is the string 'core' is being added to the public link. Should I add it to the expected url?

**Comment by PVince81** [comment]
@SergioBertolinSG are you sure ? Why didn't we see these failures before this PR ?

I don't think there is any such big change related to public links between master and 9.1 so it might be a false failure.

**Comment by PVince81** [comment]
I could never run these tests due to permission issues:
```
    And Public shared file "welcome.txt" can be downloaded # FeatureContext::checkPublicSharedFile()
      Unable to open ./welcome.txt using mode w+: fopen(./welcome.txt): failed to open stream: Permission denied (GuzzleHttp\Exception\RequestException)
```

somehow it seems to be trying to write a local file. We should change that at some point to store the file contents in memory instead.

**Comment by PVince81** [comment]
by the way, I don't see anything with "core":
```
Config value enable_alt_user_backend for app testing set to yes
Feature: sharing

  Background:                   # /srv/www/htdocs/owncloud/build/integration/features/sharing-v1.feature:2
    Given using api version "1" # FeatureContext::usingApiVersion()
    Given using old dav path    # FeatureContext::usingOldDavPath()

  Scenario: Creating a new public share                    # /srv/www/htdocs/owncloud/build/integration/features/sharing-v1.feature:59
[Mon Jan 23 20:23:02 2017] 127.0.0.1:47250 [404]: /ocs/v2.php/cloud/users/user0
[Mon Jan 23 20:23:03 2017] Successful addUser call with userid: user0
[Mon Jan 23 20:23:03 2017] 127.0.0.1:47254 [200]: /ocs/v1.php/cloud/users
[Mon Jan 23 20:23:03 2017] copying skeleton for user0 from /srv/www/htdocs/owncloud/core/skeleton to /user0/files/
[Mon Jan 23 20:23:04 2017] 127.0.0.1:47258 [200]: /ocs/v1.php/cloud/users/user0
[Mon Jan 23 20:23:04 2017] 127.0.0.1:47262 [200]: /ocs/v2.php/cloud/users/user0
    Given user "user0" exists                              # FeatureContext::assureUserExists()
    And As an "user0"                                      # FeatureContext::asAn()
[Mon Jan 23 20:23:05 2017] 127.0.0.1:47266 [200]: /ocs/v1.php/apps/files_sharing/api/v1/shares
    When creating a share with                             # FeatureContext::creatingShare()
      | path      | welcome.txt |
      | shareType | 3           |                                                                                                                                                                                 
    Then the OCS status code should be "100"               # FeatureContext::theOCSStatusCodeShouldBe()
    And the HTTP status code should be "200"               # FeatureContext::theHTTPStatusCodeShouldBe()
[Mon Jan 23 20:23:05 2017] 127.0.0.1:47270 [200]: /index.php/s/0A5g53VALzvBJAm/download
    And Public shared file "welcome.txt" can be downloaded # FeatureContext::checkPublicSharedFile()
      Unable to open ./welcome.txt using mode w+: fopen(./welcome.txt): failed to open stream: Permission denied (GuzzleHttp\Exception\RequestException)
```

did you switch dev env maybe ?

**Comment by PVince81** [comment]
I put all these into the other PR https://github.com/owncloud/core/pull/26993 to save time...

**Comment by SergioBertolinSG** [comment]
Yes, I guess my server is broken because of switching between master and stable9.1. I'll use a new one only for stable9.1.

**Pull request closed without merging**
