### PR TITLE
Jenkins #18212 

### PR DESCRIPTION
**Pull request by blizzz**
Jenkins PR for https://github.com/owncloud/core/pull/18212

DO NOT MERGE

### CODE REVIEW

**Comment by blizzz** [comment]
@DeepDiver1975 can we make @mention-bot ignore issues with "jenkins" label, por favor? :smile_cat:

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 can we make @mention-bot ignore issues with "jenkins" label, por favor? :smile_cat:

not that I'm aware of ...

**Comment by blizzz** [comment]
@DeepDiver1975 happens. Well, and that single failing test either has fun with lexington or a github limit was exceeded?

**Comment by MorrisJobke** [comment]
All are green now -> closing

**Pull request closed without merging**
