### PR TITLE
3rdparty bump of pear-core-minimal

### PR DESCRIPTION
**Pull request by rullzer**
requires https://github.com/owncloud/3rdparty/pull/203

CC: @DeepDiver1975 @PVince81 @MorrisJobke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@rullzer 3rdparty is merged - please update the submodule - THX

**Comment by rullzer** [comment]
@DeepDiver1975 done

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 done

THX

**Comment by rullzer** [comment]
Failing tests are unrelated

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
