### PR TITLE
[3rdparty] bump jeremeamia/superclosure to 2.1.0

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/227

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@rullzer 3rdparty merge conflict

**Comment by rullzer** [comment]
Fixed.

**Comment by DeepDiver1975** [comment]
> Requires owncloud/3rdparty#227

merged

**Comment by rullzer** [comment]
Rebased

**Pull request merged**
