### PR TITLE
Use Guzzle stream to download files from GDrive

### PR DESCRIPTION
**Pull request by PVince81**
The API library does not support streaming and always reads the full
file into memory.

This workaround copies the signed headers to a Guzzle request and
returns the response as stream.

Inspired by @icewind1991's approach for DAV: https://github.com/owncloud/core/pull/18653

Before: (the download takes a while to start due to temp storage)

```
  % curl "http://root:admin@localhost/owncloud/remote.php/webdav/gdrive/direct%20upload/BigBuckBunny_320x180.mp4" -o test_master.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 61.6M  100 61.6M    0     0   352k      0  0:02:59  0:02:59 --:--:-- 16.6M
```

After:

```
  % curl "http://root:admin@localhost/owncloud/remote.php/webdav/gdrive/direct%20upload/BigBuckBunny_320x180.mp4" -o test.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 61.6M  100 61.6M    0     0   712k      0  0:01:28  0:01:28 --:--:--  785k
```

Fixes the download part of https://github.com/owncloud/core/issues/21357

Please review @icewind1991 @Xenopathic

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by PVince81** [comment]
@MorrisJobke

**Comment by icewind1991** [comment]
Looks good :+1:

**Comment by PVince81** [comment]
@karlitschek backport to 8.2.2 at least ?

**Comment by karlitschek** [comment]
backport is fine if this is fully tested. :+1:

**Comment by PVince81** [comment]
@davitol mind doing another test for this PR ? The only test needed is downloading, see original post. Maybe spice it up a bit with encryption and shares :smile:

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/21825

**Pull request merged**
