### PR TITLE
Move away from OCA.files.getMimeIcon and use OC.MimeType.getIconUrl

### PR DESCRIPTION
**Pull request by rullzer**
Since we now have the fancy OC.MimeType class (#16724) we should actively use it!

This moves the file app away from the getMimeIcon function that did a request for every mimetype to the server

Testing is easy!
1. Add some files for which we have mimetypes
2. Reload files app and observe the console.. for each mimetype you should see at least 1 request to the server (ajax/mimeicon.php)
3. Now checkout this awesome branch
4. Reload files app
5. Observe no calls to the server for each mimetype (but you still see them)

TODO:
- [x] Remove ajax/mimeicon.php (and its routes)
- [x] Migrate calls in core app to getMimeIcon to OC.MimeType.getIconUrl

### CODE REVIEW

**Comment by rullzer** [comment]
Would it be safe to remove ajax/mimeicon.php and its routes? Could other apps depend on that? I guess they can. Probably no real way to mark this deprecated then... :S

**Comment by rullzer** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
Yes, please kill the ajax stuff with :fire:

**Comment by rullzer** [comment]
Review time!

CC: @PVince81 @Xenopathic @MorrisJobke

**Comment by rullzer** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
- [ ] TEST: regular file list icons
- [ ] TEST: public file list icons
- [ ] TEST: file picker
- [ ] TEST: conflict dialog

**Comment by PVince81** [comment]
- [ ] BUG: public page does not show mime icons

@rullzer please have a look

**Comment by rullzer** [comment]
> - [ ] BUG: public page does not show mime icons

Seems to work here.
Which mime icons are not displayed?

**Comment by PVince81** [comment]
All of them :wink: 
public-nomime

**Comment by PVince81** [comment]
This is the file list from a public link.

Regular file list works fine.

**Comment by PVince81** [comment]
Rebase onto master, it's a regression caused by https://github.com/owncloud/core/pull/16902/files#diff-dafefd9519924bec4efa9f5af4af8e68R765

**Comment by MorrisJobke** [comment]
I tested this and it works just fine: (chrome, firefox, IE8)

- [x] TEST: regular file list icons
- [x] TEST: public file list icons
- [x] TEST: file picker
- [x] TEST: conflict dialog

**Comment by MorrisJobke** [comment]
:+1:

**Comment by rullzer** [comment]
@MorrisJobke I did not rebase on master yet. But all should be fixed now.
@PVince81 please give it another go.

I fixed #17527 here as well.

**Comment by Xenopathic** [comment]
@rullzer @PVince81 Wouldn't an easier way to fix the 'httpd/unix-directory' mismatch be to add it to the aliases list? Then it works in PHP too, which is nice

**Comment by rullzer** [comment]
@Xenopathic could also be done indeed.. but I can imagine people wanting to map stuff to `httpd/unix-directory'....

But fine with me both ways

**Comment by rullzer** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
AFAIK we use the mimetype 'dir' all over the place, rather than 'httpd/unix-directory'.

**Comment by rullzer** [comment]
@Xenopathic agreed. And fixed.

**Comment by rullzer** [comment]
@owncloud-bot retest this please

**Comment by rullzer** [comment]
Ah need to fix the js unit tests... let me take care of that

**Comment by rullzer** [comment]
@owncloud-bot retest this please

**Comment by rullzer** [comment]
Unit tests updated... all is fine now... I hope...
Review time!

**Comment by PVince81** [comment]
All work :+1:

**Comment by jospoortvliet** [comment]
just curious - does this make loading folders faster, too? As you mention it doesn't have to do a request for mimetype for each file anymore...

**Comment by rullzer** [comment]
@jospoortvliet should be a little snappier. But I did not run any timing benchmarks.

**Comment by jospoortvliet** [comment]
Just wanted to make sure I wrote no nonsense ;-) thanks!

**Pull request merged**
