### PR TITLE
[hotfix-10.0.7] Add CI and hotfix for app passwords

### PR DESCRIPTION
**Pull request by patrickjahns**
# Motivation

We need to run the full suite also on hotfix releases. 
Backported `.drone.yml` from stable10 and added hotfix branch

### CODE REVIEW

**Comment by PVince81** [comment]
random failure ?

**Comment by phil-davis** [comment]
I expect so - I restarted the drone job

**Comment by PVince81** [comment]
Failed again it seems ?

**Comment by PVince81** [comment]
Failed again... @phil-davis @patrickjahns

**Comment by PVince81** [comment]
or is it a legit failure ?

**Comment by phil-davis** [comment]
The full set of UI test suites pass fine on Travis - so it is not a "hard" UI error. There is most likely some timing issue on drone that is causing those UI test failures (or possibly some way the the browser "simulation" in the drone docker happens differently to tghe browser environment in SauceLabs)

**Comment by PVince81** [comment]
I'm tired of these shitty random failures, merging now

**Pull request merged**
