### PR TITLE
add word wrap to tooltips. Fixes #22746

### LINKED ISSUE #22746: Tooltip in federated sharing is not showing the full url.
### Steps to reproduce

Having admin in serverA and admin in serverB
1. Share a file from admin@serverA with admin@serverB.
2. In ServerB accept the share.
3. In ServerA open the sidebar of the shared file and hover the shared name

### Expected behaviour
Tooltip shows full url.

### Actual behaviour
Tooltip shows the same information.

screen shot 2016-03-01 at 09 35 07

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.0.13","versionstring":"9.0.0 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome

### PR DESCRIPTION
**Pull request by ErikPel**
Would this be good solution for the issue?
@jancborchardt 

Fixes #22746

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ErikPel please rebase - THX

**Comment by ErikPel** [comment]
@DeepDiver1975 should be good now?

**Comment by ChristophWurst** [comment]
:+1: looks good

**Comment by ChristophWurst** [comment]
@owncloud/designers review please

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by MorrisJobke** [comment]
@karlitschek The original ticket was filed for 9.0.2 - backport?

**Comment by karlitschek** [comment]
cool. not a big issues but should be low risk. please backport 👍

**Comment by MorrisJobke** [comment]
@ErikPel Could you create a backport PR against stable9? That would be nice :) Thanks :)

**Comment by LukasReschke** [comment]
Revert is at https://github.com/owncloud/core/pull/24138

**Comment by skjnldsv** [comment]
👍

**Pull request merged**
