### PR TITLE
Remove pcntl warning for 9.0.2

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes https://github.com/owncloud/updater/issues/335

### CODE REVIEW

**Comment by VicDeo** [comment]
@LukasReschke @PVince81

**Comment by PVince81** [comment]
As discussed :+1: 

CC @karlitschek for approval, not a backport but 9.0.2 workaround for updater, see explanation here https://github.com/owncloud/updater/pull/339#issuecomment-214822212

**Comment by LukasReschke** [comment]
👍

**Comment by PVince81** [comment]
@cmonteroluque actually this is already mergable, this commit has no JS code, so no need to wait for JS tests

**Comment by karlitschek** [comment]
:+1: yes. as discussed

**Pull request merged**
