### PR TITLE
polish totp middleware a little

### PR DESCRIPTION
**Pull request by butonic**
was reading code ... polished it while trying to understand it.

### CODE REVIEW

**Review by tomneedham — APPROVED** [review]

**Review by tomneedham — CHANGES_REQUESTED** [review]
Failing test still it seems

**Comment by tomneedham** [comment]
screen shot 2018-03-12 at 10 09 08

**Comment by tomneedham** [comment]
Need to fix the test because we cant mock the redirect url using `OC_Util::getDefaultUrl` - might just use `IURLGenerator->getAbsoluteUrl('')`

**Comment by patrickjahns** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by tomneedham — APPROVED** [review]

**Comment by tomneedham** [comment]
@butonic backport?

**Comment by butonic** [comment]
no, it is just polish ... well it fixes the redirect for totp ... so  ... would make sense. but cow on my prio list

**Comment by phil-davis** [comment]
Suggested backport #30723

**Pull request merged**
