### PR TITLE
Added favorites integration tests

### PR DESCRIPTION
**Pull request by davitol**
WIP Adding integration tests for favorites feature

### CODE REVIEW

**Comment by PVince81** [comment]
@davitol any chance to finish this ? More tests === good

**Comment by PVince81** [comment]
@davitol what's missing ?

**Comment by PVince81** [comment]
Let's move this forward, the tests pass.

@SergioBertolinSG second review ?

**Comment by DeepDiver1975** [comment]
rebased

**Comment by SergioBertolinSG** [comment]
> @SergioBertolinSG second review ?

Tests didn't pass, they required some changes.

**Comment by PVince81** [comment]
Looks good so far :+1: 

If possible, would be good to have another test for "un-favorite" and check that the property isn't set any more.

**Comment by PVince81** [comment]
:+1: again

**Comment by SergioBertolinSG** [comment]
Another review @davitol , @DeepDiver1975 ?

**Comment by davitol** [comment]
:+1:

**Pull request merged**
