### PR TITLE
Test sharing a folder and then it shows up on Shared with others page

### PR DESCRIPTION
**Pull request by skshetry**
## Description

This adds a test that after sharing a file/folder to other user, the file/folder is listed on the `Shared with others` page.  

## Related Issue

- Related to #32846 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
Next we can add some scenarios that share different folders/files that have the same name, and check that they aare both listed on the shared-by-you and shared-with-you pages.

**Comment by skshetry** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
