### PR TITLE
[stable7] Check for file existence before doing a DAV copy

### PR DESCRIPTION
**Pull request by PVince81**
Partial backport of #14505

For 7.0.10

Please review @icewind1991 @MorrisJobke @Xenopathic @davivel

### CODE REVIEW

**Comment by PVince81** [comment]
Test steps can be found here: https://github.com/owncloud/core/issues/14501

**Comment by Xenopathic** [comment]
:+1:

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
:+1:

**Comment by davivel** [comment]
Tested from mobile, :+1: for us too.

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Pull request merged**
