### PR TITLE
Fix middle click on breadcrumb

### LINKED ISSUE #9175: Chrome can not open file list "root icon" in a new tab without mouse wheel
The click event seems to be overwritten.
It works in Firefox thou.

Confirmed on Linux by @PVince81

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/9175

@nickvergessen @MorrisJobke @jancborchardt

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Reproduced, tested and works :+1:

**Comment by MorrisJobke** [comment]
cc @jancborchardt @oparoz @rullzer @Xenopathic easy one ;)

**Comment by nickvergessen** [comment]
Testergebnis (2 fehlgeschlagene Tests / +2)

    PhantomJS 1.9.8 (Linux).OCA_Files_FileList tests breadcrumb events.clicking on root breadcrumb changes directory to root
    PhantomJS 1.9.8 (Linux).OCA_Files_FileList tests breadcrumb events.clicking on breadcrumb changes directory

**Comment by PVince81** [comment]
I fixed the unit tests.
Please review.

**Comment by Xenopathic** [comment]
Code looks good :+1:

Ref: https://www.w3.org/Bugs/Public/show_bug.cgi?id=23240

**Pull request merged**
