### PR TITLE
Add Roave Security Advisories as a development dependency

### PR DESCRIPTION
**Pull request by settermjd**
## Description

Add [Roave Security Advisories](https://github.com/Roave/SecurityAdvisories) as a development dependency to block packages with known security vulnerabilities being added to the project. 

## Related Issue

n/a

## Motivation and Context

The intent of this PR is to continue helping to increase the security posture and quality of the project. By not being able to include any package with a known security vulnerability, then the quality of the code, everyone's confidence in it, and the peace of mind about it will improve. 

## How Has This Been Tested?

n/a

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by patrickjahns** [comment]
How should we handle this with our apps - require it for all applications?

**Review by patrickjahns — APPROVED** [review]
👍 from my side - would like feedback from @PVince81 / @DeepDiver1975 if they have any concerns

**Comment by DeepDiver1975** [comment]
> How should we handle this with our apps - require it for all applications?

yes - I see no other way ....

**Comment by DeepDiver1975** [comment]
we shall backport this ...

**Comment by patrickjahns** [comment]
@settermjd - pleae backport

**Comment by DeepDiver1975** [comment]
> @settermjd - please backport

done

**Pull request merged**
