### PR TITLE
[3rdparty] Bump sabre/dav to 3.0.6

### PR DESCRIPTION
**Pull request by rullzer**
Finally using a proper release again

Requires https://github.com/owncloud/3rdparty/pull/238

### CODE REVIEW

**Comment by rullzer** [comment]
Ah we check the exact sabre version in unit test apparently... Let me fix that..

**Comment by rullzer** [comment]
@nickvergessen since it involes sabre stuff... do you mind smashing it? Just to be a little extra sure.

**Comment by DeepDiver1975** [comment]
3rdparty merged - update submodule please - THX

**Comment by rullzer** [comment]
Updated

**Comment by nickvergessen** [comment]
Smashed :white_check_mark:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
