### PR TITLE
Disable filesystem_check_changes by default

### LINKED ISSUE #16897: Set filesystem_check_changes to 0 by default
Many ownCloud setups are using the "data" folder exclusively through ownCloud, which means the data is never modified through external programs. This is even more true for people using encryption, in which case the files cannot be accessed externally anyway with direct access to the "data" folder.

Since 8.1, external storage mount points have their own "detect remote changes" setting. This means that "filesystem_check_changes" isn't global any more and only applies to the home/local storage (data directory).

So we could change it to 0 by default which would improve performance in such setups by avoiding unnecessary update checks and also potential issues related to concurrent scanner runs.

People who use an externally mounted data folder (ex: NAS) would then need to explicitly set that setting to 1. Unless we find a way to auto-detect such situations or ask the admin at setup time.

@icewind1991 @karlitschek @DeepDiver1975 @schiesbn @nickvergessen 

Also see https://github.com/owncloud/core/issues/13391#issuecomment-111401970

### PR DESCRIPTION
**Pull request by PVince81**
This will prevent detecting remote changes done in the data folder /
root storage by default. In the rare cases where the data folder is
shared with other apps/users outside ownCloud and change detection is
needed, the admin will have to set the option explicitly from now on.

Note that this doesn't affect external storages which have their own
setting in the mount options.

Fixes https://github.com/owncloud/core/issues/16897, see discussion there.

Please review @nickvergessen @schiesbn @DeepDiver1975 @Xenopathic @icewind1991 @karlitschek (CC @MTRichards)

This should go in 8.2. Not sure if we want this in the 8.1 as well because we'd be changing a default value. If we do, we'll need a mention in the release notes.

### CODE REVIEW

**Comment by PVince81** [comment]
Please note that many concurrency issues (but not all of them) can be avoided by having this setting set to 0.

**Comment by PVince81** [comment]
also @MorrisJobke

**Comment by DeepDiver1975** [comment]
> This should go in 8.2. Not sure if we want this in the 8.1 as well because we'd be changing a default value. If we do, we'll need a mention in the release notes.

From my POV no behavioral changes on minor releases.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by Xenopathic** [comment]
:+1:

I agree with @DeepDiver1975, 8.2 only

**Comment by MorrisJobke** [comment]
```
12:51:50 1) Test\Files\Cache\Watcher::testWatcher
12:51:50 Failed asserting that false is true.
12:51:50 
12:51:50 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/tests/lib/files/cache/watcher.php:52
12:51:50 
12:51:50 2) Test\Files\Cache\Watcher::testFileToFolder
12:51:50 Failed asserting that two strings are equal.
12:51:50 --- Expected
12:51:50 +++ Actual
12:51:50 @@ @@
12:51:50 -'httpd/unix-directory'
12:51:50 +'text/plain'
12:51:50 
12:51:50 /var/jenkins/workspace/pull-request-analyser-ng-simple@8/label/SLAVE/tests/lib/files/cache/watcher.php:91
```

Behavioural change without unit test change is either

* bad unit test coverage
* broken tests ;)

**Comment by PVince81** [comment]
I am positively surprised that it's the latter :smile:

**Comment by MorrisJobke** [comment]
> I am positively surprised that it's the latter :smile:

:smile:

**Comment by karlitschek** [comment]
nice. This makes total sense. :+1: We will get a few questions from user who change files directly in data. But this is unsupported and we can explain.
Definitely no backport please.

**Comment by PVince81** [comment]
Here we go, I fixed the tests.

**Pull request merged**
