### PR TITLE
Fix OC_Helper::rmdirr for nested symlinks

### PR DESCRIPTION
**Pull request by VicDeo**
Partial backport of https://github.com/owncloud/core/pull/24899
Fixes https://github.com/owncloud/core/issues/24453 for stable9

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 @DeepDiver1975 I'm unsure about milestone. I set it to 9.0.4, please adjust if needed.

**Comment by PVince81** [comment]
@VicDeo how often is this likely to happen ? If rare then 9.0.4 is ok

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by VicDeo** [comment]
@PVince81 the only issue I'm aware of is above (installing/updating news app). 
In general symlinks are rare.

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
