### PR TITLE
Add openssl randomness source

### LINKED ISSUE #16575: Consider adding OpenSSL to RNG mixer
Ref https://github.com/owncloud/core/pull/16565

### PR DESCRIPTION
**Pull request by LukasReschke**
This is a clone of the OpenSSL mixer from RandomLib but with an assigned strength
of medium instead of high. This is useful because there are cases where /dev/urandom
is not readable and thus we should have another randomness source.

To test this the easiest way is to create a random number in `index.php` using `\OC::$server->getSecureRandom()->getMediumStrengthGenerator()->generate(12);` and add breakpoint at https://github.com/owncloud/3rdparty/blob/54e62d2dc4fa8ff341c843fa844f533da08ff51e/ircmaxell/random-lib/lib/RandomLib/Generator.php#L163, `$this->sources` should contain `OC\Security\RandomNumberGenerator\OpenSSL` as well.

Fixes https://github.com/owncloud/core/issues/16575

### CODE REVIEW

**Comment by LukasReschke** [comment]
@DeepDiver1975 Your choice whether 8.1 or 8.2 – 8.2 is fine for me. This is basically only to help admins that misconfigured their systems (unlikely) and did not read the documentation (more likely)…

Shouldn't hurt as far I can tell.

**Comment by LukasReschke** [comment]
```
12:04:44 PHP Fatal error:  Cannot redeclare class SecureRandomTest in /var/jenkins/workspace/pull-request-analyser-ng-simple/label/SLAVE/tests/lib/security/securerandom.php on line 77
```

:confused:

**Comment by DeepDiver1975** [comment]
I did not have a closer look at the changes - but isn't this something we would want to fix upstream?

**Comment by MorrisJobke** [comment]
Rebase needed

**Comment by LukasReschke** [comment]
Upstream likely has other security considerations... Will rebase and talk to upstream this pr next week.

**Pull request closed without merging**
