### PR TITLE
make scrollbar less obnoxious: tad narrower, rounded corners

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @owncloud/designers @PVince81 @MorrisJobke 

Otherwise it overpowers other elements on the page. Especially when used in the app-navigation and the content list used in Mail and the new Contacts app.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and looks good :+1:

**Comment by ChristophWurst** [comment]
Looks good, but what about people actually using the scrollbar by clicking and dragging? It's not easy to hit that 5px scrollbar on a touch pad.

**Comment by karlitschek** [comment]
i like :+1:

**Comment by jancborchardt** [comment]
@Deepdiver1975 merge please

**Pull request merged**
