### PR TITLE
Backport of #17723 to stable8.1

### PR DESCRIPTION
**Pull request by blizzz**
See original issue for reproduction steps: https://github.com/owncloud/core/pull/17723

(Hint: adding ?w=1 to the files URL hides whitespace changes. )

Please check @benwilliams @johansmitsnl @Nick-Lock @nickvergessen @MorrisJobke @rperezb

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

cc @rperezb for testing

**Comment by karlitschek** [comment]
:+1:

**Comment by rperezb** [comment]
@owncloud/qa

**Comment by nickvergessen** [comment]
Btw why was the whitespace commit backported as well?
Backports should be kept as small as possible to avoid problems....

**Comment by blizzz** [comment]
Broken indentations may lead to wrong interpretation of what was coded. Probably not a big issue here, but: *Principiis obsta*.

> The problem was the second (duplicate) “goto fail”. The indentation here is misleading; since there are no curly braces after the “if” statement, the second “goto fail” is always executed. [source](http://www.dwheeler.com/essays/apple-goto-fail.html)

**Comment by davitol** [comment]
:+1: works in version":"8.1.0.8","versionstring":"8.1.0","edition

**Pull request merged**
