### PR TITLE
Make an assertion in risky test testGetNodeForPathRoot

### LINKED ISSUE #17079: Risky test Test\OC\Connector\Sabre\ObjectTree::testGetNodeForPathRoot
```
There was 1 risky test:

1) Test\OC\Connector\Sabre\ObjectTree::testGetNodeForPathRoot
This test did not perform any assertions
```

Introduced with https://github.com/owncloud/core/commit/5a5639ab763662d8105bc61c5f124fcc99a7a813, @icewind1991 mind to add an assertion as well?

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #17079 

@MorrisJobke @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks good, let's wait for jenkins :)

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
cc @rullzer @Xenopathic @Henni @nickvergessen @LukasReschke

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
