### PR TITLE
remove duplicate shares before mounting them

### PR DESCRIPTION
**Pull request by icewind1991**
Only try to mount one share for every source file

cc @MorrisJobke @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by MorrisJobke** [comment]
This solves a lot of the performance issues that I've seen on s3. But it only solves the symptoms and not the actual cause, because new share entries are added nevertheless :cry:

**Comment by nickvergessen** [comment]
:-1:  this only shows us, that the bug is inside the sharing code
So we need to find the underlying issue in `Share::getItems()`

**Comment by schiesbn** [comment]
We already group the shares in getItems: https://github.com/owncloud/core/blob/master/lib/private/share/share.php#L1814

If you still get multiple items for the same file in getMountsForUser() you should probably check what gets wrong in getItems() instead of fixing it outside.

**Comment by MorrisJobke** [comment]
I think we can move this to a health check and not put it in our day-to-day code base. This allows us to maybe clean it up and properly detect broken behaviour.

**Comment by icewind1991** [comment]
Closing since the cause is fixed

**Pull request closed without merging**
