### PR TITLE
[9.2] Moving user ldap to it's own repo 

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description

In order to support and move ownCloud modularization more and more - the user_ldap module will be moved to it's own repo.
This will allow to easier cut it out for our future plans with respect to the marketplace. 

https://github.com/owncloud/user_ldap

### CODE REVIEW

**Comment by felixboehm** [comment]
perfect :+1:

**Comment by PVince81** [comment]
and also make it possible to have it run specific automated tests :+1: 

@owncloud/ldap @jvillafanez

**Comment by DeepDiver1975** [comment]
> and also make it possible to have it run specific automated tests :+1:

yes - preparing travis .....

**Comment by PVince81** [comment]
go go go !

**Pull request merged**
