### PR TITLE
Move basic auth login out of `isLoggedIn`

### PR DESCRIPTION
**Pull request by LukasReschke**
Potentially fixes https://github.com/owncloud/core/issues/12915 and https://github.com/owncloud/core/issues/12339 and opens the door for potential other bugs...

Please test very carefully, this includes:
- Testing from OCS via cURL (as in #12915)
- Testing from OCS via browser (Open the "Von Dir geteilt" shares overview)
- WebDAV
- CalDAV
- CardDAV

@PVince81 Please test with your awesome Python library. - I think this might potentially also fixes some other problems that we found…
@DeepDiver1975 As discussed.

### CODE REVIEW

**Comment by karlitschek** [comment]
@LukasReschke Can you backport this?
@craigpg isolated that this might fix: 
https://github.com/owncloud/ios/issues/246 and https://github.com/owncloud/ios/issues/253

**Comment by LukasReschke** [comment]
Not easily. Merging this has broken other stuff that we fixed in https://github.com/owncloud/core/pull/13217 then – so we could backport both but don't blame me if something is broken then ;-)

**Comment by LukasReschke** [comment]
aka: everything that touches base.php probably breaks completely unrelated code …

**Comment by karlitschek** [comment]
@LukasReschke @craigpg What are your suggestions?

**Comment by LukasReschke** [comment]
Backporting it not impossible but due to the fact that it touches a critical component (base.php) we need really do proper and very careful regression testing not only for all API related stuff but also upgrading, maintenance mode, LDAP, some pre-authentication app and whatever is influenced by changes in base.php (nearly everything - plus the testplan in https://github.com/owncloud/core/pull/12917#issue-52279146 and https://github.com/owncloud/core/pull/13217)

If we can guarantee that this gets done properly I think I could live with backporting this to 7, however 6 is certainly out-of-scope, the code path is too different for that. – However, please be noted that in the past often "WHAT THE FUCK HAS BROKEN XYZ IN THE LAST STABLE RELEASE?!?"-moments were caused by backports of changes in base.php ;-) – So don't blame me then if some magical toaster app does not work then anymore…

**Comment by DeepDiver1975** [comment]
I would suggest to rethink backporting after oc8 release - too critical from my pov at the moment.

**Comment by craigpg** [comment]
This has been confirmed to fix a serious bug with iOS + encryption where iOS downloads encrypted files.  Fortunately, this has _not_ been widely reported.

Looks like a typo here:
https://github.com/owncloud/core/pull/12917/files#diff-d03ba189671916ae1c793777d94546d0R326

I would like to see this code make use of the new tryBasicAuthLogin function:
https://github.com/owncloud/core/blob/058324b80e18474e0b3bd55ce9be8410209da1d2/lib/private/api.php#L295-L299

Other than that, this change looks pretty straightforward to me and, despite the fact that every request is going to hit this code (yikes), I think is a good candidate for the next 7.0.x maintenance release because of the iOS bug (and perhaps a lot of others) it fixes.

**Comment by DeepDiver1975** [comment]
@craigpg thanks for the detailed explanation - and true there is a typo :skull: - hail to missing unit tests

Here is a PR which basically moves master's api.php back to stable7 - https://github.com/owncloud/core/pull/13496

Within the description I added a test plan on what to take care about in order to make sure we do not break it badly. 

@craigpg @jnfrmarks Can we team up on testing? I can provide a stable7 server running shibboleth (needs to be updated first: https://test1.owncloud.com/oc7-shib/ )

**Pull request merged**
