### PR TITLE
[Tests-only] Fix failing tests due to undefined method "assertContainsEquals()"

### PR DESCRIPTION
**Pull request by haribhandari07**
## Description

This PR fixes failing tests in various apps due to `call to undefined method PHPUnit\Framework\Assert::assertContainsEquals()` error

Should fix:
https://drone.owncloud.com/owncloud/guests/1427/13/11

This error is caused due to phpunit update PRs https://github.com/owncloud/QA/issues/647

## How Has This Been Tested?

- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
That link https://drone.owncloud.com/owncloud/guests/1427/12/11 is to a drone run that is using the old phpunit7.

guests app needs to be updated to phpunit8 and it should pass.

`assertContainsEquals` was done in PR #37310 as it will be needed for the future phpunit9. That should be able to stay like that - it is a method added in phpunit8.

**Review by phil-davis — CHANGES_REQUESTED** [review]
See my comment. Please explain why this PR is needed.

**Comment by HariBhandari07** [comment]
@phil-davis aren't we only updating `phpunit` of apps with failing unit tests?

**Comment by phil-davis** [comment]
We need to update phpunit in `vendor-bin/behat` of all apps that have acceptance tests.
And `guests` app will be failing acceptance tests. We need to fix every failing test.

**Comment by HariBhandari07** [comment]
@phil-davis I thought we are only updating apps with failing unit tests. So, closing this issue.

**Pull request closed without merging**
