### PR TITLE
restrict access to public files only

### PR DESCRIPTION
**Pull request by rjaeckel**
use mod_rewrite to pretend theese files are not existend for security purposes

this would make the brances be used in production environment #12423
would suggest to merge this into stable7

allowed ocs compared to #12474

### CODE REVIEW

**Comment by AdamWill** [comment]
For the record this isn't 100% backportable to OC 7 anyway, it looks like: I tested it, and at least creating a new appointment in the calendar app seems to generate a request into the /3rdparty directory (for some bit of jquery). There may well be other cases, that's just one I happened to run into. So anyone who wants to apply this to OC 7 should at least drop 3rdparty from the first regex.

**Comment by DeepDiver1975** [comment]
@AdamWill OC7 still holds javascript file in 3rdparty - that's why these rewrite rules will cause issues on OC7.

**Comment by AdamWill** [comment]
@DeepDiver1975 yep, that's exactly what it looked like. Do you know of any reason it might be problematic to apply the other three to OC 7, btw?

**Comment by DeepDiver1975** [comment]
Should be fine from my pov ....

**Pull request merged**
