### PR TITLE
Show label for password change in IE8

### LINKED ISSUE #10729: Problems with IE 8+9: writing in the field is gone
Hello OC Community,

I have read a lot of posts about problems with Internet Explorer 8 + 9, but I didn't find my topic.

In the "Personal" Area there is the "Password" field, to change the Password. You have to write your old password in the first, and your new password in the second filed. To understand this (because is is not intuitive), there is written in Gray "Current password" and "New password".

But with IE 8 the fields are empty and the User doesn't understand what to do? With IE 11 I have no problem. What is the problem, any idea?

IE is not my favourite browser, but there are a few important persons with have to use IE 8 ...

best regards,

Matthias

PS: With chrome and Firefox OC works perfekt!

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #10729

cc @owncloud/designers @PVince81 @matthias1983

### CODE REVIEW

**Comment by jancborchardt** [comment]
:+1: also doesn’t impact the current appearance.

@Matthias1983 please check if this fixes https://github.com/owncloud/core/issues/10729 for you.

**Comment by MorrisJobke** [comment]
@LukasReschke @PVince81 @Xenopathic @rullzer easy to review? :D

**Comment by PVince81** [comment]
Can we also remove the bogus placeholders then ?
Now that the labels are there it is ok to have the fields empty in IE8

**Comment by MorrisJobke** [comment]
> Can we also remove the bogus placeholders then ?
> Now that the labels are there it is ok to have the fields empty in IE8

Adding shitty JS rules just to remove the placeholder in the seldom use case where a user looks at the personal page. I'm against it.

**Comment by MorrisJobke** [comment]
@PVince81 or @icewind1991 Please review ;)

**Comment by PVince81** [comment]
Ok fine... :+1:

**Pull request merged**
