### PR TITLE
Init the headers in iedavclient.js

### LINKED ISSUE #23471: 9.0 - cannot create folder with IE11 and when I log in to folder shared with a link (without user name)
### Steps to reproduce
1. Create folder and share it as a link (with "Allow editing") 
2. Log out (or use InPrivate session of IE11) and use link - you should see password-only login page - enter password and log in
3. Try to create folder - enter folder name and hit enter

### Expected behaviour
Folder should be created

### Actual behaviour
1. the layer with folder name is not closed
2. folder is not created
3. IE console shows 1 error (i have only polish version so translation can be wrong)

SCRIPT5007: Nie można ustawić właściwości „Authorization” dla niezdefiniowanego lub pustego odwołania (Cannot set property 'Authorization' of undefined ??)
File: iedavclient.js, line: 34, column: 5 

### Server configuration

**ownCloud version:** (see ownCloud admin page)
9.0 - latest fresh install on Ubuntu ubuntu-14.04.4-server-amd64 

### Client configuration
**Browser:**
IE11
**Operating system:**
Windows 8.1 x64

#### Browser log

Insert your browser log here, this could for example include:

a) The javascript console log

SCRIPT5007: Nie można ustawić właściwości „Authorization” dla niezdefiniowanego lub pustego odwołania  (Cannot set property 'Authorization' of undefined ??)
Plik: iedavclient.js, wiersz: 34, kolumna: 5

b) The network log 

empty

### PR DESCRIPTION
**Pull request by PVince81**
@michaelstingl @kpalik @owncloud/javascript @icewind1991 @guruz please review

Fixes https://github.com/owncloud/core/issues/23471

Needs backport to 9.0 to make it work there

@dragotin @DeepDiver1975

### CODE REVIEW

**Comment by michaelstingl** [comment]
@PVince81 The fix works in my 9.0.2 too. Tested in [IE11 on Win 8.1 (32.bit)](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/25234

**Comment by guruz** [comment]
👍

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
