### PR TITLE
Fix more IE issues

### LINKED ISSUE #18992: Missing shadow on "new" dropdown on all of Microsoft's browsers
border

@jancborchardt

### LINKED ISSUE #19290: Options icons are not shown properly using IE11
### Steps to reproduce

1. Login ownCloud using IE as browser
2. Click on file/folder options button  (menu is dropdrown)

### Expected behaviour
The icons of each option should be shown properly

### Actual behaviour
The icons of each option are not shown properly

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 IE9 & 11

Internet Explorer:
screen shot 2015-09-23 at 10 51 47

Firefox
screen shot 2015-09-23 at 10 52 45

### LINKED ISSUE #19527: Minor IE8 styling bugs
Remaining issues from https://github.com/owncloud/core/issues/18619
- [x] ridiculously small trash icon

ie8-trash-icon

- [x] "New" button is too wide

### LINKED ISSUE #19629: [IE9] actions menu icon garbled
While IE8 is working fine now, IE9 decided to not show the file actions menu properly.

### Steps

1. Upload a file in IE9
1. Click on the three dots "..."
1. Look at the icons and feel sad

### PR DESCRIPTION
**Pull request by PVince81**
See commit list for details, each fix is in an individual one.

Fixes https://github.com/owncloud/core/issues/19629
Fixes https://github.com/owncloud/core/issues/18992
Fixes https://github.com/owncloud/core/issues/19527 (except the ridiculous icon, I don't think it's worth creating another set of bigger PNG icons for IE8...)
Fixes #19290

@MorrisJobke @oparoz @Henni @icewind1991 @davitol @SergioBertolinSG

### CODE REVIEW

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/19290

**Comment by karlitschek** [comment]
wow!! :+1:

**Comment by davitol** [comment]
:+1: WFM great job

**Comment by jancborchardt** [comment]
Nice! Thank you. Just needs a rebase apparently.

**Comment by MorrisJobke** [comment]
@PVince81 Please create the backport for 8.2.1

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/core/pull/19770

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
