### PR TITLE
Make sidebar properly fullscreen in mobile/compact mode

### PR DESCRIPTION
**Pull request by PVince81**
Please review @oparoz @jancborchardt @Henni @MorrisJobke

### CODE REVIEW

**Comment by PVince81** [comment]
Note: in mobile mode you can only open the sidebar using "Details" in the menu. This is likely to be the intended interaction design (at least for now).

**Comment by PVince81** [comment]
Fixes https://github.com/owncloud/core/issues/19561

**Comment by Henni** [comment]
Works, but shouldn't this be fixed differently?
Why is the mobile.css inserted before the apps.css?
In my opinion this issue should be fixed by loading the mobile.css after all (or most) of the other stylesheets.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by PVince81** [comment]
@Henni not sure, but if the order hasn't changed I don't want to risk breaking other stuff at this point close to the RC1. But I agree that mobiles.css should be loaded after the others, so something for 8.2.1 or 9.0

**Comment by Henni** [comment]
@PVince81 Then :+1:
I opened #19596 for 9.0

**Comment by PVince81** [comment]
@Henni thanks

**Pull request merged**
