### PR TITLE
Translate file summary connector

### PR DESCRIPTION
**Pull request by PVince81**
## Description

Translate " and " in file summary.
## How Has This Been Tested?

Switch the language to french or german, create a file and folder and see that the connector is in the summary translated again instead of saying " and "
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Please review @ppaysant @davitol @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
should be backported to 9.1 where the refactoring with the template was introduced

**Comment by davitol** [comment]
:+1: WFM

**Comment by ppaysant** [comment]
Tested, works for me :+1:

**Comment by DeepDiver1975** [comment]
9.1: https://github.com/owncloud/core/pull/26222

**Pull request merged**
