### PR TITLE
Restore old view with -m option

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Enhancement: Bring back minimalistic view to occ app:list with '-m' option

## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

### Without -m flag
image

### With -m flag
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Documentation ticket raised: https://github.com/owncloud/docs/issues/4117
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
FYI @voroyam

**Comment by JanAckermann** [comment]
@mmattel do we need a docs issue for that ?

**Comment by voroyam** [comment]
https://github.com/owncloud/docs/issues/4117

**Review by phil-davis — APPROVED** [review]
Works for me. I pushed an acceptance test scenario.

**Comment by mmattel** [comment]
> @mmattel do we need a docs issue for that ? 

Yes please 😃

**Pull request merged**
