### PR TITLE
[Stable9] Added tests using provisioning api v2.php for sharees

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
Backport of https://github.com/owncloud/core/pull/26915

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
There is a problem here, all the statements saying 'Then the OCS status code should be "100"' fails. It returns 200. @PVince81 should I remove this ocs checks and keep only the http answer?

**Comment by PVince81** [comment]
Hmm, no that would be wrong. The whole point of v2.php was that the ocs status code is supposed to be "200" instead of "100" while in v1.php it was "100".

**Comment by SergioBertolinSG** [comment]
This is also wrong in master then.

**Comment by SergioBertolinSG** [comment]
In master it is returning 100 instead of 200.

<font color="green">
[Wed Jan 25 15:49:48 2017] 127.0.0.1:40373 [200]: /ocs/v2.php/apps/files_sharing/api/v1/sharees?search=Sharee1&itemType=file
    When getting sharees for                                                                  # ShareesContext::whenGettingShareesFor()
      | search   | Sharee1 |
      | itemType | file    |
    Then the OCS status code should be "100"
</font>

**Comment by PVince81** [comment]
> In master it is returning 100 instead of 200.

please investigate. Maybe master has a regression ?

**Comment by SergioBertolinSG** [comment]
Well all this tests https://github.com/owncloud/core/blob/master/build/integration/sharees_features/sharees_provisioningapiv2.feature

Are passing. It is returning 100 in all places like https://github.com/owncloud/core/blob/master/build/integration/sharees_features/sharees_provisioningapiv2.feature#L30

@DeepDiver1975 is this intended or it is a regression?

**Comment by SergioBertolinSG** [comment]
After talking with mobile devs, they are expecting only the ocs response and it should be 200. So the tests in master are wrong and we have a regression.

**Comment by PVince81** [comment]
@SergioBertolinSG so are the tests here correct ? We already merged the 9.1 tests

**Comment by SergioBertolinSG** [comment]
@PVince81 after https://github.com/owncloud/core/pull/27024/commits/0ea3dfd7328142e7306f7af4f2c3ed7dad1d5fe0 they are correct, yes.

**Comment by PVince81** [comment]
Rebased to get CI results for int tests

**Pull request merged**
