### PR TITLE
Do not run method when the path is empty

### LINKED ISSUE #15924: PHP Notice versions
````
{"reqId":"3OphSUQJnlPdis0GuFrF","remoteAddr":"::1","app":"PHP","message":"Undefined index: dirname at \/home\/deepdiver\/Development\/ownCloud\/core\/apps\/files_versions\/lib\/storage.php#314","level":3,"time":"2015-04-29T08:03:11+00:00","method":"GET","url":"\/oc\/core\/cron.php"}
{"reqId":"3pZRXjisIiw7qXJP1rTU","remoteAddr":"::1","app":"PHP","message":"Undefined index: dirname at \/home\/deepdiver\/Development\/ownCloud\/core\/apps\/files_versions\/lib\/storage.php#314","level":3,"time":"2015-04-29T08:03:18+00:00","method":"GET","url":"\/oc\/core\/cron.php"}

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #15924 

@DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
unit test :question:

**Comment by DeepDiver1975** [comment]
> unit test :question:

~~unit~~ *integraton* test :exclamation: 

https://github.com/owncloud/core/blob/master/apps/files_versions/tests/versions.php#L395

**Comment by nickvergessen** [comment]
> ~~unit~~ *integraton* test :exclamation: 

pushed

**Comment by MorrisJobke** [comment]
Works and code looks good :+1:

**Pull request merged**
