### PR TITLE
Add a notice to the share tooltip when there is no autocomplete

### LINKED ISSUE #31137: Tooltip in sharing autocomplete doesn't mention it is autocompleting
### Steps to reproduce

1. Having a server with several users "aabaa", "aabb", "aabc"
2. In config.php add 'user.search_min_length' => 3,
3. Using admin try to share with "aac" wait for autocompletion.

### Expected behavior
A tooltip appears saying:
'No users or groups found containing "aac"'

### Actual behavior
A tooltip appears saying
'No users or groups found for "aac"'

screen shot 2018-04-16 at 14 40 41

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**Cache**
DB

**ownCloud version:** (see ownCloud admin page)
**{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.8.1","versionstring":"10.0.8 RC1","edition":"Enterprise","productname":"ownCloud"}**

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
Yes.

**Logs**
```
```

### Client configuration

**Browser**
Chrome.  
  

@pmaier1 When having 'user.search_min_length' => 4 in config.php maybe the tooltip should not appear when searching "aac".

### PR DESCRIPTION
**Pull request by VicDeo**
## Description
- [x] change the default length for suggestions back to 2 (release notes!)
- [x] if the number of entered chars is below limit, show "Please enter at least X characters for suggestions", because you can still get exact matches when typing less. Message must be adjusted to singular if X is 1. (use the appropriate "n()" translation function argument)
- [x] if the number of entered chars is above or equal to X, show "No results" if no results were found

## Related Issue
Closes https://github.com/owncloud/core/issues/31137 (Tooltip in sharing autocomplete doesn't mention it is autocompleting)

## How Has This Been Tested?
1. set `user.search_min_length` to 10
2. enter 5 chars.
See "No users or groups found for 12345 Please enter at least 10 characters for suggestions"

3. Enter 10 or more characters
See "No users or groups found for 1234567890 "

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: code looks good

**Comment by mmattel** [comment]
Info:
https://github.com/owncloud/core/issues/31305 (Delay start of search to avoid searching for single letters)
Discussion that in Chinese or Japanese (and others?), a single character can represent a word

**Comment by phil-davis** [comment]
LGTM

Re: Chinese characters...
This PR is reverting back to the old default. The behavior might have been not suitable for Unicode scripts where a single Unicode character is often a whole word. It was even less suitable with the min set at 4. With the min set at 2, the issue should not be back to being less noticed.
More behavior improvements for those scripts can be considered separately.

**Comment by VicDeo** [comment]
@PVince81 yes, a proper description was missed

**Comment by PVince81** [comment]
@VicDeo can you also adjust the test ?

```
--- Failed scenarios:

/drone/src/tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature:54
```

**Comment by phil-davis** [comment]
See #31718 last commit - that fixes the problem here (the failing test adjusted ``user.search_min_length`` after the user is already logged in, so it is not effective) and makes the whole set of shareAutocomplete webUI tests more complete and robust. Assuming it passes, then I suggest you cherry-pick the last commit from there.

**Comment by PVince81** [comment]
@phil-davis can you cherry pick here to save some time ? unless the other PR can be merged soon and we can rebse this one

**Comment by phil-davis** [comment]
Acceptance test refactoring commit cherry-picked here. Let's see CI pass...

**Comment by phil-davis** [comment]
drone is all green.
@PVince81 you are welcome to override whatever codecov is complaining about, and merge :)

**Comment by phil-davis** [comment]
Backport ``stable10`` #31729

**Comment by PVince81** [comment]
@VicDeo can you add a JS test for https://github.com/owncloud/core/pull/31714/files#diff-a25afa955e6a768d34381f4e9c1e0685R278 ? (see codecov)

**Comment by PVince81** [comment]
Looks like it's just pure luck that the tooltip wraps exactly after the search:
image

**Comment by PVince81** [comment]
I've added JS tests and also added a dot between the messages. Didn't want to touch the messages directly to not influence translations... Anyway, here the dot is optional and only appears when concatenating.

**Comment by phil-davis** [comment]
Added a commit to adjust the webUI acceptance test scenarios for the full-stop added.

**Comment by phil-davis** [comment]
All good. Now what happens?
@VicDeo @PVince81 and I have all had a finger in this pie. Who can give it an "independent" review tick?

**Comment by PVince81** [comment]
@phil-davis acceptance tests look good.

Now need to find someone to review the JS part...

**Review by sharidas — APPROVED** [review]
The js test looks ok to me.

**Review by individual-it — COMMENTED** [review]
Acceptance test look good :+1:

**Comment by phil-davis** [comment]
Thanks @individual-it - you were just a few minutes late for the :tada:

**Pull request merged**
