### PR TITLE
New issue template workflow.

### LINKED ISSUE #37566: You are using an old version of issue templates. Please update to the new issue template workflow.
https://github.com/owncloud/core/blob/master/.github/issue_template.md show:

issue

https://help.github.com/articles/about-issue-and-pull-request-templates
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

`blank_issues_enabled: false` by config.yml + central.owncloud.org link prevent question like https://github.com/owncloud/core/issues/37523?

### PR DESCRIPTION
**Pull request by ho4ho**
## Description
Suggest for #37566

https://help.github.com/articles/about-issue-and-pull-request-templates
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

## Related Issue

- Fixes #37566

## Motivation and Context
- Update workflow
- Prevent question like #37523

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ho4ho** [comment]
Require?
- Changelog
- Docs / other change
- Admin github configuration on template

**Comment by DeepDiver1975** [comment]
Looks good .. let's merge and see the results ..

**Comment by DeepDiver1975** [comment]
Screenshot from 2020-06-23 20-33-49

There is something missing ... now no new issues can be opened anymore at all ...

**Comment by ho4ho** [comment]
Need specific config? https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

https://help.github.com/assets/images/help/repository/repo-actions-settings.png

https://help.github.com/assets/images/help/repository/set-up-templates.png

https://help.github.com/assets/images/help/repository/add-template-drop-down-menu.png

**Comment by ho4ho** [comment]
Or https://help.github.com/en/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository ?

**Comment by ho4ho** [comment]
Trying fixing by https://github.com/owncloud/core/pull/37581

**Comment by ho4ho** [comment]
Look good now:

oc

**Pull request merged**
