### PR TITLE
[WIP] adding configuration option for sqlite timeout - refs #12429

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@PVince81 this is how we could configure sqlite timeout

Code segment from PHP where busyTimeout is applied - https://github.com/php/php-src/blob/master/ext/pdo_sqlite/sqlite_driver.c#L303

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
refs #12429

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by LukasReschke** [comment]
Falling apart:

```
5:07:22 There were 3 failures:
15:07:22 
15:07:22 1) Test_DB::testUpdateAffectedRowsSame
15:07:22 Failed asserting that 0 is identical to 1.
15:07:22 
15:07:22 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/db.php:252
15:07:22 
15:07:22 2) Test_DB::testUpdateAffectedRowsMultiple
15:07:22 Failed asserting that 1 is identical to 2.
15:07:22 
15:07:22 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/db.php:263
15:07:22 
15:07:22 3) Test_OC_OCS_Privatedata::testSetSameValue
15:07:22 Failed asserting that 2 matches expected 1.
15:07:22 
15:07:22 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/ocs/privatedata.php:161
15:07:22 /var/jenkins/workspace/pull-request-analyser-ng-simple@5/label/SLAVE/tests/lib/ocs/privatedata.php:97
```

**Comment by DeepDiver1975** [comment]
> Falling apart:

tired

**Comment by LukasReschke** [comment]
73upl4

**Comment by guruz** [comment]
Will this also go into 7.x?

@dragotin and me are a bit worried about the paralleism that the 1.8 client brings..

**Comment by DeepDiver1975** [comment]
> Will this also go into 7.x?

this will even not go into 8.0 - milestone is on 8.1

**Comment by guruz** [comment]
*sigh*
Related https://github.com/owncloud/client/issues/2743

**Comment by DeepDiver1975** [comment]
@guruz we even don't know if it really helps to tweak around on the timeout. This has to be properly tested.

**Comment by guruz** [comment]
Why I think the busy handler needs to be in 7.0, 8.0 and 8.1

owncloud_suggestions

**Comment by PVince81** [comment]
I merged this with master (which contains the other sqlite fix for the FS part) and as far as I understand I don't need to add any settings, and the timeout would default to 60 second.

And yet the "lastlogin" update from the concurrent auth-ing PROPFINDs from https://github.com/owncloud/core/issues/13705 still locks:
```
{"reqId":"aed15bdbfe760abde09535ee60345647","remoteAddr":"192.168.1.2","app":"remote","message":"An exception occurred while executing 'UPDATE \"oc_preferences\" SET \"configvalue\" = ? WHERE \"userid\" = ? AND \"appid\" = ? AND \"configkey\" = ? ' with params [1417180669, \"root\", \"login\", \"lastLogin\"]:\n\nSQLSTATE[HY000]: General error: 5 database is locked","level":4,"time":"2014-11-28T13:17:49+00:00"}
{"reqId":"cd04246444522861fa21cdeba9b7a0f7","remoteAddr":"192.168.1.2","app":"remote","message":"An exception occurred while executing 'UPDATE \"oc_preferences\" SET \"configvalue\" = ? WHERE \"userid\" = ? AND \"appid\" = ? AND \"configkey\" = ? ' with params [1417180669, \"root\", \"login\", \"lastLogin\"]:\n\nSQLSTATE[HY000]: General error: 5 database is locked","level":4,"time":"2014-11-28T13:17:49+00:00"}
{"reqId":"ca8bbbcb5052a9c47d5c19a49f3a5068","remoteAddr":"192.168.1.2","app":"remote","message":"An exception occurred while executing 'UPDATE \"oc_preferences\" SET \"configvalue\" = ? WHERE \"userid\" = ? AND \"appid\" = ? AND \"configkey\" = ? ' with params [1417180669, \"root\", \"login\", \"lastLogin\"]:\n\nSQLSTATE[HY000]: General error: 5 database is locked","level":4,"time":"2014-11-28T13:17:49+00:00"}
{"reqId":"e2dec4ec401c1833fb91bd1859f8b384","remoteAddr":"192.168.1.2","app":"remote","message":"An exception occurred while executing 'UPDATE \"oc_preferences\" SET \"configvalue\" = ? WHERE \"userid\" = ? AND \"appid\" = ? AND \"configkey\" = ? ' with params [1417180669, \"root\", \"login\", \"lastLogin\"]:\n\nSQLSTATE[HY000]: General error: 5 database is locked","level":4,"time":"2014-11-28T13:17:49+00:00"}
```

Either the timeout value isn't passed properly or SQLite is just being mean.

**Comment by PVince81** [comment]
Am debugging this now. Something suspicious with "driverOptions".

**Comment by PVince81** [comment]
Basically `PDO::ATTR_TIMEOUT` evaluates to `2`. I'd expect this to be a string id instead.
So we have this:
`$connectionParams['driverOptions'][2] = 60`

**Comment by PVince81** [comment]
Ok turns out that PDO attributes are indeed integers.

While debugging I have the feeling that we might not be passing the options properly to the PDO driver (still trying to find out where it is actually created through debugging), especially that we pass a connection wrapper which doesn't seem to do anything with these options.

**Comment by PVince81** [comment]
I debugged deep and saw that the parameter was passed properly to the PDO class. And yet still seems to be ignored.

**Comment by PVince81** [comment]
Tried using `PRAGMA busy_timeout 6000` (without @DeepDiver1975's option) and also tried querying `PRAGMA busy_timeout` and it did return the correct value.

This means that the setting is indeed set properly but SQLite refuses to behave.

**Comment by PVince81** [comment]
I got news: if SQLite seems to ignore the timeout and throw "Database is locked" directly, first step is to check for any unclosed "SELECT" that is directly followed by an "UPDATE" on the same table.
We seem to do that often, see here: https://github.com/owncloud/core/blob/master/lib/private/allconfig.php#L180

**Comment by guruz** [comment]
Developer of the day: @PVince81

**Comment by PVince81** [comment]
Also thanks @guruz for the psychological support :wink:

**Comment by guruz** [comment]
My only goal was to prove @DeepDiver1975 wrong. But now you found so many related bugs :D gooood!

**Pull request closed without merging**
