### PR TITLE
Provisioning api v2 should return 200

### PR DESCRIPTION
**Pull request by SergioBertolinSG**
These tests are not currently passing. So they require a fix before merging.

### CODE REVIEW

**Comment by PVince81** [comment]
A bisect might help find out when this changed.

So do I understand correctly that stable9.1 returns 200 and master returns 100 ?

Do you want to attempt a bisect ? You can use curl to check the return status for each step.

**Comment by SergioBertolinSG** [comment]
After bisecting the bad commit is e8b4d4bc942a2d2f36c225ab0d4f337008480a91.

**Comment by PVince81** [comment]
WTF, I see the code setting the correct status code 200 but when I evaluate the response object it still contains 100. Need to dig deeper.

**Comment by PVince81** [comment]
`setStatus` (from AppFramework base class `Response`) vs `setStatusCode` (from `OCSResponse`).

**Comment by PVince81** [comment]
I rebased and force pushed, but Github doesn't show my commit yet 😦

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/27076/commits/e1dd5e125710552a2627f3488c16d5a0d39b7ce5

**Comment by PVince81** [comment]
@DeepDiver1975 please review if https://github.com/owncloud/core/pull/27076/commits/e1dd5e125710552a2627f3488c16d5a0d39b7ce5 is an acceptable fix

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
THX

**Comment by PVince81** [comment]
Failed tessssst on master, posssssibly related https://github.com/owncloud/core/issues/27098

**Pull request merged**
