### PR TITLE
Fix TagList namespace in property map

### PR DESCRIPTION
**Pull request by PVince81**
Without this, it becomes impossible to set tags using PROPPATCH

@DeepDiver1975 @nickvergessen @icewind1991 @rullzer

### CODE REVIEW

**Comment by nickvergessen** [comment]
Should have a test that fails?

Smashbox could do a proppatch and check it?

**Comment by PVince81** [comment]
Smashbox test makes sense.
Here are instructions how to do it with curl: https://github.com/owncloud/core/pull/12865#issuecomment-67346274

**Comment by icewind1991** [comment]
Code looks good :+1: 

You could also try using the [`RequestTest`](https://github.com/owncloud/core/blob/master/apps/dav/tests/unit/connector/sabre/requesttest/requesttest.php) as base for testing.

**Comment by PVince81** [comment]
@icewind1991 is there any helper to build XML ? One would need to pass XML as string to do a PROPFIND/PROPPATCH request. But then having it in smashbox as well feels like duplicated effort.

**Comment by icewind1991** [comment]
> is there any helper to build XML

No

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
