### PR TITLE
[stable10] Expand test scenarios for emojis and Unicode in comments

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #34420

### CODE REVIEW

**Comment by PVince81** [comment]
some weird Jasmine failures.

AFAIK we didn't update Jasmine on stable10?!

**Comment by phil-davis** [comment]
I have a problem on stabel10 locally when trying to share: "Sharing is not allowed"
I  did git bisect. When I:
```
git revert 4ca7afd1720e67cd0c42ba72178f68d22c846b17
```
and ``make``
then all is good again.
That commit is from PR https://github.com/owncloud/core/pull/34333 by the bot which is "Bumps [@bower_components/bowser](https://github.com/ded/bowser) from 1.6.0 to 2.1.0."

**Comment by PVince81** [comment]
@phil-davis weird... ok let's revert

**Comment by phil-davis** [comment]
I just rebased this. CI should pass now that the other Jasmine things have been reverted in stable10.

**Comment by PVince81** [comment]
it's still failing... and I did rebuild the stable10-qa tarballs

**Comment by PVince81** [comment]
hmm wait the build was from before... ok let's wait a bit further

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by PVince81** [comment]
let's see if now it appears in the Drone queue...

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by individual-it — APPROVED** [review]

**Pull request merged**
