### PR TITLE
don't show no files yet when mask is in place, fixes #13141

### LINKED ISSUE #13141: Initial load shows »No files yet« in the background for a short time
When you open ownCloud Files (or you refresh), behind the spinner the message »No files yet« is shown for a split-second.

This is very disconcerting and wrong information, as the files show up shortly afterwards. It wasn’t the case before as only the spinner showed.

The issue shows since commit 7a812801db6cc2cddf4e176dc893b07c7c486d76 – can you look into it @butonic? :)

### PR DESCRIPTION
**Pull request by butonic**
cc @jancborchardt @PVince81 

fixes #13141

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1: resolves the described flickering

**Comment by PVince81** [comment]
Would be good to have a JS unit test for this part.
One way to test it is to call FileList.reload() but not return any data, letting the call linger.
Then call whichever code part is calling "hideXXXX" (the super long method name) and check if the wanted elements are visible or not (check for the "hidden" class)

**Comment by PVince81** [comment]
Does it mean that something is called `setFilter()` with an empty value initially before the data is loaded ? It seems only `setFilter()` calls it.

Anyway, if that's the right way, the unit test could then just call `setFilter()` with nothing then.

**Comment by PVince81** [comment]
Also seem unit tests are missing in general for `hideIrrelevantUIWhenNoFilesMatch`, but you were probably under pressure to release it :smile: 
Would you mind adding them now ? That function has several code/logic paths that need to be covered.

Thanks.

**Comment by jancborchardt** [comment]
This fixes the issue for me :+1: from my side but please check @PVince81's remarks.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
@PVince81 do the tests look ok then?

**Comment by PVince81** [comment]
The tests look good. You might want to remove the commented out code though :+1:

**Pull request merged**
