### PR TITLE
[master] log token related changes

### PR DESCRIPTION
**Pull request by PVince81**
Master port of https://github.com/owncloud/core/pull/31460

### CODE REVIEW

**Review by tomneedham — APPROVED** [review]

**Comment by tomneedham** [comment]
CS fixed doesnt like `else if` 
screen shot 2018-06-14 at 11 04 15

**Comment by PVince81** [comment]
fixed for CS

**Comment by PVince81** [comment]
cherry-picked: https://github.com/owncloud/core/pull/31794

some stray debugging stuff...

**Comment by PVince81** [comment]
rebased

**Comment by phil-davis** [comment]
See #32039 for a fix to this PR. 
Why has this not been merged to ``master`` yet?
This needs to be merged first, then resolve conflict that will come in #32039 
Or just add the fixing commit from #32039 to this PR.

**Comment by PVince81** [comment]
cherry-picked extra fix https://github.com/owncloud/core/pull/32039 as pointed out by @phil-davis

**Comment by phil-davis** [comment]
That last commit looks good.

**Comment by PVince81** [comment]
let's merge after CI passes

**Pull request merged**
