### PR TITLE
Always run npm even for make dist

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Always run npm in make, even for make dist

## Related Issue
None raised. Complains by @ppaysant on IRC 😄 

## Motivation and Context
Fixes an issue where `make` followed by `make test-js` would not work
due to npm not having installed deps. Will also make it easier for new contributors to run the JS tests without being confused.

This also brings back the faster make through `make -j4`.

Note that node deps will be required in the future anyway once we have
handlebars template compilation, minifying and other nice stuff.

## How Has This Been Tested?
1) `make clean && make && make test-js`
2) `make clean && make test-js`
3) `make clean && make -j4` (yay! multithreading!)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

@DeepDiver1975 @VicDeo @ppaysant @PhilippSchaffrath

### CODE REVIEW

**Comment by ppaysant** [comment]
:+1: all tests proposed in issue description work on my install.

**Comment by PVince81** [comment]
I need to fix travis:
```
build/node_modules/bower/bin/bower install

make: build/node_modules/bower/bin/bower: Command not found

make: *** [core/vendor] Error 127
```

**Comment by PVince81** [comment]
Failed again ? But it works locally... weird.

**Comment by PVince81** [comment]
Ok, I think I got it. Since the folder "build/node_modules" is cached by travis, it still has a recent timestamp so make will not rerun `npm install`. I'll remove it because we already cache the npm packages in another folder, so it's ok to reinstall them from there.

However i added phantom js to the cached dirs because it seems some package redownloads it.

@DeepDiver1975 let me know if that's not ok

Let's see how it goes now.

**Comment by PVince81** [comment]
Not good, it still downloaded phantomjs. Seems there is a version on Travis already but it says wrong version. Let me see if I can prevent taht...

In total `make` took about a minute.

**Comment by DeepDiver1975** [comment]
> Not good, it still downloaded phantomjs.

it has to download it once before moving it into cache AFTER a successfull build

**Comment by PVince81** [comment]
According to the phantomjs docs, one would need to add a lot of other lines
: https://github.com/Medium/phantomjs#travisyml

But I don't want to have to do this in every one of our apps that uses JS testing... or need to put this into an external script.

But first, let's see if the next run uses the cached version.

**Comment by PVince81** [comment]
Don't merge yet, seems it's still downloading every time.

I'll need to find a better approach. In most cases we don't even need npm or bower when testing PHP code stuff only so it might be possible to provide a more specific "make" command to that.

**Comment by PVince81** [comment]
Ah no, seems it found it:
```
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2

Verified checksum of previously downloaded file
```

According to https://docs.travis-ci.com/user/caching/ there is one cache per branch.

So this means that while all jobs on a PR would reuse the cached version (unless run in parallel, race condition 😞), every branch would redownload it. I guess there is no other way because even the recommended approach would cache a local version that is branch specific.

But also it says "If a branch does not have its own cache, Travis CI fetches the master branch cache." so if we're lucky phantomjs would be cached at some point for the master branch and reused by every build.

Let's try that ? @DeepDiver1975 please review

**Comment by DeepDiver1975** [comment]
:+1: looks good to me -> merge

**Pull request merged**
