### PR TITLE
remove mssql from supported dbs

### PR DESCRIPTION
**Pull request by carlaschroder**
A simple fix, removing mssql from supported db list

@jnfrmarks

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: 

@karlitschek for ultimate confirmation

**Comment by karlitschek** [comment]
Yes. :+1:  He is dead Jim.

**Comment by DeepDiver1975** [comment]
@carlaschroder did we apply this to master as well? THX

**Comment by carlaschroder** [comment]
Yup! Master ea9c21f94ed1c3d1efb8bf0539dd866786b1f26c

**Pull request merged**
