### PR TITLE
[stable9] Fix decrypt message stable9

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #24992

### CODE REVIEW

**Comment by PVince81** [comment]
Not critical => 9.0.4

**Comment by PVince81** [comment]
:+1: still

**Comment by davitol** [comment]
:-1: 
1) run command sudo -u www-data ./occ encryption:decrypt later (later is the user's name of an encrypted account)

Expected output: You are about to start to decrypt all files stored in later's account...
Current output: You are about to start to decrypt all files stored in your ownCloud...

**Comment by DeepDiver1975** [comment]
the cherry-pick is totally fucked up -> :skull:

**Comment by DeepDiver1975** [comment]
@davitol thx for testing - mind rerunning the tests? THX

**Comment by davitol** [comment]
:+1: WFM now 💃

**Comment by guruz** [comment]
code looks ok 👍

**Pull request merged**
