### PR TITLE
Remove app framework's IApi

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Removed IApi interface.
Removed IAppContainer::getCoreApi()

## Related Issue
None

## Motivation and Context
Remove old deprecated code.

## How Has This Been Tested?
Not tested. Grepped the code. Acceptance tests will tell.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
```
There were 7 errors:

1) Test\AppFramework\DependencyInjection\DIContainerTest::testProvidesAPI
ReflectionException: Class Mock_API_9c6ed22a does not have a constructor, so you cannot pass any constructor arguments

/drone/src/tests/lib/AppFramework/DependencyInjection/DIContainerTest.php:42

2) Test\AppFramework\DependencyInjection\DIContainerTest::testProvidesRequest
ReflectionException: Class Mock_API_9c6ed22a does not have a constructor, so you cannot pass any constructor arguments

/drone/src/tests/lib/AppFramework/DependencyInjection/DIContainerTest.php:42

3) Test\AppFramework\DependencyInjection\DIContainerTest::testProvidesSecurityMiddleware
ReflectionException: Class Mock_API_9c6ed22a does not have a constructor, so you cannot pass any constructor arguments

/drone/src/tests/lib/AppFramework/DependencyInjection/DIContainerTest.php:42

4) Test\AppFramework\DependencyInjection\DIContainerTest::testProvidesMiddlewareDispatcher
ReflectionException: Class Mock_API_9c6ed22a does not have a constructor, so you cannot pass any constructor arguments

/drone/src/tests/lib/AppFramework/DependencyInjection/DIContainerTest.php:42

5) Test\AppFramework\DependencyInjection\DIContainerTest::testProvidesAppName
ReflectionException: Class Mock_API_9c6ed22a does not have a constructor, so you cannot pass any constructor arguments

/drone/src/tests/lib/AppFramework/DependencyInjection/DIContainerTest.php:42

6) Test\AppFramework\DependencyInjection\DIContainerTest::testAppNameIsSetCorrectly
ReflectionException: Class Mock_API_9c6ed22a does not have a constructor, so you cannot pass any constructor arguments

/drone/src/tests/lib/AppFramework/DependencyInjection/DIContainerTest.php:42

7) Test\AppFramework\DependencyInjection\DIContainerTest::testMiddlewareDispatcherIncludesSecurityMiddleware
ReflectionException: Class Mock_API_9c6ed22a does not have a constructor, so you cannot pass any constructor arguments

/drone/src/tests/lib/AppFramework/DependencyInjection/DIContainerTest.php:42

**Comment by PVince81** [comment]
- [ ] remove CodeChecker in favor of new QA tools to develop for app validation (IApi is used in its tests)

**Comment by PVince81** [comment]
fixed test.

did not fail code checker as the test class using IApi is not actually loaded but just parsed by code checker

**Comment by DeepDiver1975** [comment]
phan error:

````
lib/private/AppFramework/DependencyInjection/DIContainer.php:319 PhanUndeclaredClassMethod Call to method __construct from undeclared class \OC\AppFramework\Core\API (Did you mean class \OCA\Files_External\Lib\Api)

**Comment by PVince81** [comment]
@DeepDiver1975 it's green now, approve ?

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
@DeepDiver1975 I noticed this when backporting "Introduce PHPstan" #35774 
In `stable10` `DIContainer.php` has to be adjusted to stop `phpstan` shouting.
https://github.com/owncloud/core/pull/35774/commits/b318f6646471584106a3b7f13ab07f4e6cbfd4af

I guess we cannot backport this PR?

**Pull request merged**
