### PR TITLE
[stable8.1]  check for the right user if we can change his password

### PR DESCRIPTION
**Pull request by schiessle**
approved backport of https://github.com/owncloud/core/pull/18983

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by andybuchs** [comment]
my test was not successful, change password in ldap, login as admin, go to users, set new password with recovery key. Login as the user, still the message that the key needs to update.
ungueltigerschluessel

**Comment by schiesbn** [comment]
@andybuchs thanks for your feedback. I can't reproduce it in this branch. Password reset works fine here. Are you sure that you logged out with the user to perform the reset and then logged in again after the password reset was successful? Just want to make sure that you didn't reused a old session.

@PVince81 you already tested the PR against master successfully, can you also test the backport? Does it work for your too or can you re-produce the issue reported by @andybuchs ?

**Comment by PVince81** [comment]
Tested, works :+1:

**Pull request merged**
