### PR TITLE
hotfix branch rebased onto stable10

### PR DESCRIPTION
**Pull request by PVince81**
This is the hotfix-10.0.7 branch **before** the merge commit from https://github.com/owncloud/core/pull/30535, rebased onto stable10.

I'm a bit worried that those version changing commits will not be accurate after merge.

In the future we should refrain to backport stuff onto stable10 if the target is the hotfix branch. They will then eventually land on stable10 through the final "merge release branch into stable10" and keep their proper order.

Thoughts ? Should we move forward with this PR this time and improve next time ?

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
The first 2 commits that just turn on CI for the hotfix branch are not wanted in stable10 - we would need to revert them anyway if we merge this.

All the functional code is already in stable10 (I hope!), so why not just make a new branch off stable10 and cherry-pick the last 3 commits here, push it and make a PR?

That will get the changelog and version files up-to-date in stable10.

**Comment by PVince81** [comment]
ok here is what I'm going to do: I'm going to send this PR and the other one to trash.

On stable10 I'll set the version to 10.0.8 pre-alpha so at least we have a higher number than 10.0.7. I don't want to merge any of these version changing commits without having the proper history attached in between.

**Comment by phil-davis** [comment]
> On stable10 I'll set the version to 10.0.8 pre-alpha so at least we have a higher number than 10.0.7
Good idea - because the code in ``stable10`` is well ahead of the code that is being released as ``10.0.7`` - putting a ``10.0.7`` version bump at the end of the current ``stable10`` branch would mislead people into thinking that was like a tag point for ``10.0.7``

**Comment by phil-davis** [comment]
and it would be good to insert the changelog changes also to ``stable10`` so it can move on from there for 10.0.8 changelog.

**Pull request closed without merging**
