### PR TITLE
[stable8] Fix fileglobalgc unlink parameter warnings

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Backport of #14980

Request for backport @karlitschek It seems that our users are complaining about this bug: #14698

cc @pierrejochem @hmuus @bedzkowp if you are interested :)

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport

**Comment by DeepDiver1975** [comment]
looks good :+1:

**Comment by PVince81** [comment]
:+1:

**Comment by hmuus** [comment]
@Xenopathic thx
:+1:

**Pull request merged**
