### PR TITLE
[stable10] Backport of #28457 (Enabled CORS on ownCloud)

### LINKED ISSUE #28832: PHP array warning in response.php
### Steps to reproduce
1. run limituploadbasedonsize.feature firewall test against current master
2. examine data/owncloud.log

### Expected behaviour
No PHP messages

### Actual behaviour
This:
```
{"reqId":"Jwtuaff38pjoU0rHVRR5","level":3,"time":"2017-08-29T11:23:10+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/admin\/","message":"in_array() expects parameter 2 to be array, null given at \/home\/phil\/core\/lib\/private\/legacy\/response.php#294"}
```
### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
PHP dev server
**Database:**
MySQL
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
current master from git

seems to be the new code added in CORS stuff:
https://github.com/owncloud/core/commit/e3564e6c53bceb2dbe23dd1fbfec8b4696f7454d
https://github.com/owncloud/core/pull/28457

### PR DESCRIPTION
**Pull request by noveens**
## Description

Backport Request of #28457 
Fixes #28832 

@PVince81 @phil-davis

### CODE REVIEW

**Review by phil-davis — DISMISSED** [review]

**Comment by PVince81** [comment]
please don't merge yet, I'd like @Peter-Prochaska to have a look.

Also @SamuAlfageme reported some potential issues with the OAuth app. Please post details here if needed.

**Comment by jesmrec** [comment]
Please, pay attention on this one: https://github.com/owncloud/core/issues/28860

**Comment by noveens** [comment]
One more backport requred: https://github.com/owncloud/core/pull/28864

**Comment by Peter-Prochaska** [comment]
Can you rebase it? Then it's ok

**Review by peterprochaska — APPROVED** [review]

**Comment by PVince81** [comment]
please don't merge before 10.0.4, just make it merge ready 😄

**Pull request merged**
