### PR TITLE
[WIP] Update doctrine/dbal to 2.5.1

### LINKED ISSUE #13303: dbal 2.5.1 has been released - we should consider updating
@VicDeo  can I ask you to prepare a PR which updates 3rdparty repo and core? THX

In case you have questions feel free to ping me

### PR DESCRIPTION
**Pull request by VicDeo**
Closes #13303 
Depends on https://github.com/owncloud/3rdparty/pull/152

Scheduled for 8.1

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@VicDeo thx - can you please have a look at the failing unit tests? Looks like something changed which breaks on our side - THX

**Comment by VicDeo** [comment]
@DeepDiver1975 yes, there are breaking change with index handling. https://github.com/owncloud/3rdparty/blob/dbal-251/doctrine/dbal/UPGRADE.md

Will have a look

**Comment by VicDeo** [comment]
@owncloud-bot retest this please

**Comment by VicDeo** [comment]
@DeepDiver1975 This is what we call a `breaking` change: indexes with the same name are compared by some additional features

https://github.com/doctrine/dbal/commit/c1eae738651fb95a2950b49ea253bdb59e7c7b4d
https://github.com/doctrine/dbal/commit/32fae862d376eb4eed60db4bf4e82f1a675c6509

An `autoincrement` field is always a primary index and according to a new 'smart' logic no more primary indexes are allowed for tables with autoincrement:
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Table.php#L508

So there is a definition conflict between https://github.com/owncloud/core/blob/master/db_structure.xml#L1208 and https://github.com/owncloud/core/blob/master/db_structure.xml#L1245

**Comment by DeepDiver1975** [comment]
oh - brilliant!

**Comment by DeepDiver1975** [comment]
I'll have a look once 8.0 has left - THX @VicDeo

**Comment by DeepDiver1975** [comment]
@VicDeo did you find any solution already to these problem? This is kind of getting momentum - see #14003 - please put some prio on this - THX

**Comment by karlitschek** [comment]
How risky would be a 8.0.1 backport? https://github.com/owncloud/core/issues/14003 Sounds not good.

**Comment by DeepDiver1975** [comment]
From my pov the risk depends on the amount of adjustments. Maybe a selective patch could be an option for oc8.0.1
But let's get 2.5.1 working first.

**Comment by VicDeo** [comment]
Something went fubar here.
Resubmitted as https://github.com/owncloud/core/pull/14119

**Pull request closed without merging**
