### PR TITLE
improve trashbin skip scenarios

### PR DESCRIPTION
**Pull request by micbar**
## Related Issue

- Fixes <issue_link>

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIProxySmoke-3-2-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31205/169/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/31205/88/13
```
  Scenario Outline: Skip trashbin based on extensions - match is case-insensitive                 # /drone/src/tests/acceptance/features/apiTrashbin/trashbinSkip.feature:74
    Given the administrator has set the following file extensions to be skipped from the trashbin # TrashbinContext::theAdministratorHasSetFollowingFileExtensionsToBeSkippedFromTrashbin()
      | extension |
      | dat       |
      | php       |
      | go        |
    And user "Alice" has uploaded file with content "sample delete file 1" to "sample.TXT"        # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 1" to "sample.txt"        # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 2" to "sample.DAT"        # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 2" to "sample.dat"        # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 3" to "sample.PHP"        # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 3" to "sample.php"        # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 4" to "sample.GO"         # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 4" to "sample.go"         # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 5" to "sample.PY"         # FeatureContext::userHasUploadedAFileWithContentTo()
    And user "Alice" has uploaded file with content "sample delete file 5" to "sample.py"         # FeatureContext::userHasUploadedAFileWithContentTo()
    And using <dav-path> DAV path                                                                 # FeatureContext::usingOldOrNewDavPath()
    When user "Alice" deletes the following files                                                 # FeatureContext::userDeletesFollowingFiles()
      | path       |
      | sample.TXT |
      | sample.txt |
      | sample.DAT |
      | sample.dat |
      | sample.PHP |
      | sample.php |
      | sample.GO  |
      | sample.go  |
      | sample.PY  |
      | sample.py  |
    Then as "Alice" the file with original path "/sample.TXT" should exist in the trashbin        # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.txt" should exist in the trashbin         # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.PY" should exist in the trashbin          # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.py" should exist in the trashbin          # TrashbinContext::elementIsInTrashCheckingOriginalPath()
    But as "Alice" the file with original path "/sample.DAT" should not exist in the trashbin     # TrashbinContext::elementIsNotInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.dat" should not exist in the trashbin     # TrashbinContext::elementIsNotInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.PHP" should not exist in the trashbin     # TrashbinContext::elementIsNotInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.php" should not exist in the trashbin     # TrashbinContext::elementIsNotInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.GO" should not exist in the trashbin      # TrashbinContext::elementIsNotInTrashCheckingOriginalPath()
    And as "Alice" the file with original path "/sample.go" should not exist in the trashbin      # TrashbinContext::elementIsNotInTrashCheckingOriginalPath()

    Examples:
      | dav-path |
      | old      |
        File previously located at /sample.DAT was found in the trashbin
        Failed asserting that true is false.
      | new      |
        File previously located at /sample.DAT was found in the trashbin
        Failed asserting that true is false.
```
This scenario fails because the latest fix is in `release-10.8.0` and not in `master`

We would need to also forward-port the fixed code to `master` to make this pass.

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingExt1-10.6.0-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/31219/161/1

**Review by phil-davis — APPROVED** [review]
This looks correct now. It implements the fix to the master branch.

**Comment by phil-davis** [comment]
That did the job. The merge-back PR #38861 no longer reports having conflicts.

**Pull request merged**
