### PR TITLE
Fixes link to external storage from files view

### LINKED ISSUE #27203: Wrong link in 'You can add external storages in the personal settings' in files view
### Steps to reproduce

1. As admin user go to Files page
2. On the left sidebar, click on External storage section
3. Click on 'You can add external storages in the personal settings' link

### Expected behaviour

We should be redirected to External Storage section

### Actual behaviour

We are redirected to the personal info

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**

 Mozilla

wrongfilesexternall

### PR DESCRIPTION
**Pull request by davitol**
Fixes https://github.com/owncloud/core/issues/27203

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: nice catch

**Comment by PVince81** [comment]
There might be other links in some of the popup dialogs I believe ?

**Comment by tomneedham** [comment]
https://github.com/owncloud/core/blob/master/apps/files_external/js/statusmanager.js#L183 here as well

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
