### PR TITLE
Fix preview for non images

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Fixes the issue where the preview icons are repeated over and over again.

## Related Issue
#31071 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
- [x] TEST: preview icon of text file doesn't repeat
- [x] TEST: preview of picture uses sidebar width
- [x] TEST: folder icon looks fine

**Review by PVince81 — APPROVED** [review]
:+1: please backport

**Comment by PVince81** [comment]
needs another backport which revert needs to be reverted ?

**Comment by PVince81** [comment]
need to understand what this was about again to decide about backport or not

**Comment by phil-davis** [comment]
@PVince81 @DeepDiver1975 backport decision is still waiting.

**Comment by PVince81** [comment]
@DeepDiver1975 please backport. we have another bunch of preview issues to fix there so better backport them all when possible

**Comment by phil-davis** [comment]
@DeepDiver1975 did the backport happen yet?
cc: @PVince81

**Comment by PVince81** [comment]
I'm fine backporting, this was about the repeated pattern issue

**Pull request merged**
