### PR TITLE
Reorganize sampe.config.php

### PR DESCRIPTION
**Pull request by MorrisJobke**
Most of the stuff of owncloud/documentation#1282 should be done by this ;)

cc @jospoortvliet

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@Raydiation @nickvergessen @LukasReschke @PVince81 @rullzer @Xenopathic This is an easy one and only affects the config sample documentation ;)

Please review :)

**Comment by rullzer** [comment]
Was already reading :)
Looks fine to me. :+1:

**Comment by MorrisJobke** [comment]
@karlitschek I would like to backport this to stable8.1 and stable8 to have a pretty documentation :)

**Comment by jospoortvliet** [comment]
Little too fast, there are still quite a few small issues, as a cursory glance with Sphinx shows that, for example, a list made with * has to be preceded by an empty line or it'll look like this:

Available cache backends: * OCMemcacheAPC Alternative PHP Cache backend * OCMemcacheAPCu APC user backend * OCMemcacheArrayCache In-memory array-based backend (not recommended) * OCMemcacheMemcached Memcached backend * OCMemcacheRedis Redis backend * OCMemcacheXCache XCache backend

**Comment by MorrisJobke** [comment]
> Little too fast, there are still quite a few small issues, as a cursory glance with Sphinx shows that, for example, a list made with * has to be preceded by an empty line or it'll look like this:
> 
> Available cache backends: * OCMemcacheAPC Alternative PHP Cache backend * OCMemcacheAPCu APC user backend * OCMemcacheArrayCache In-memory array-based backend (not recommended) * OCMemcacheMemcached Memcached backend * OCMemcacheRedis Redis backend * OCMemcacheXCache XCache backend

I want to do them step by step :)

**Comment by jospoortvliet** [comment]
@MorrisJobke your call. If you want I can help.

**Comment by MorrisJobke** [comment]
Ah ... okay ... I will test this now :)

**Comment by MorrisJobke** [comment]
@jospoortvliet I just want the big reordering in and then do the RST fixes you already did in the documentation repo.

**Pull request merged**
