### PR TITLE
[stable9] Show version to update to properly

### PR DESCRIPTION
**Pull request by LukasReschke**
Properly shows the version that will be updated to.

cc @karlitschek 9.0.1 from my PoV. Backport of https://github.com/owncloud/core/pull/22885

Also fixes https://github.com/owncloud/core/issues/22917

### CODE REVIEW

**Comment by karlitschek** [comment]
agreed. :+1

**Comment by karlitschek** [comment]
please backport

**Comment by rullzer** [comment]
:+1:

**Comment by nhantam** [comment]
I try to fix:
$newVersionString =  isset($_['newVersionString']) ? $_['newVersionString'] : '';
but still warning error ...

**Pull request merged**
