### PR TITLE
the user is gone, userExists will not bring him back. But the user's …

### LINKED ISSUE #16588: [7.0.5] LDAP user can not be deleted.
### Expected behavior:
Erase LDAP user and the user does not appear, the data folder is erased and the user does not appear in any groups.
### Actual behavior:
Erase LDAP user and the user does not appear, the data folder still exist and the user appears in the groups.

### Architecture
oC7.0.5
php 5.4
Ubuntu 14.04

#### LDAP configuration:

S3-ownCloud\Shared\owncloud\support\github-issues\core\16588

@MorrisJobke 

00003201

### PR DESCRIPTION
**Pull request by blizzz**
…folder needs to be deleted anyway

Fixes #16588 (see https://github.com/owncloud/core/pull/16830#issuecomment-111191893 for what's going in).

~~@MorrisJobke i keep this wip to consider whether unit test is possible. the exisiting ones work  either way.~~ Done.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@blizzz is this ready to review? Has the developing label attached - confudes :confused: - THX

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by blizzz** [comment]
@DeepDiver1975 Added unit test, now we are good.

@jvillafanez @davitol  mind testing?

**Comment by blizzz** [comment]
or @cdamken

**Comment by MorrisJobke** [comment]
```
00:54:30.493 + ./autotest.sh oci
00:54:30.496 Using PHP executable /home/vagrant/.phpenv/shims/php
00:54:30.618 Using database oc_autotest6
00:54:30.618 Setup environment for oci testing ...
00:54:30.622 Fire up the oracle docker
00:54:31.138 Waiting 60 seconds for Oracle initialization ... 
00:55:31.131 Installing ....
```

Known problem AFAIK - cc @DeepDiver1975

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by jvillafanez** [comment]
I've followed the next steps:
1. Delete the user from the LDAP
2. Check that the user doesn't appear in the user page (in "everyone" and in any of the groups where the user belongs previously). I don't think I have any cache in the server
3. At this point the user folder still remains in ownCloud
4. Use ./occ ldap:check-user to check for the delete user. This should answer the user doesn't exist
5. Use ./occ user:delete to delete the user

After all these steps, the user data is removed from ownCloud. :+1:

**Comment by MorrisJobke** [comment]
@blizzz To which version should this be backported? stable8 and stable7? #16588 was reported on stable7

cc @karlitschek for the approval

**Comment by blizzz** [comment]
Yes, to both 7 and 8.

**Comment by karlitschek** [comment]
@MorrisJobke Backport is fine with me.

**Comment by MorrisJobke** [comment]
@blizzz Can you create the backport PRs?

**Comment by blizzz** [comment]
Backport to 7: https://github.com/owncloud/core/pull/17034
Backport to 8: https://github.com/owncloud/core/pull/17033

**Pull request merged**
