### PR TITLE
Sync master version with stable10: 10.0.3beta

### PR DESCRIPTION
**Pull request by PVince81**
@DeepDiver1975 required for PRs of apps that have min-version=10.0.3 and build/test against master.

This PR is until we decide to jump with https://github.com/owncloud/core/pull/28043

@VicDeo FYI, will need to restart travis builds after this merge

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Looks good 👍

**Comment by DeepDiver1975** [comment]
and THC

**Comment by DeepDiver1975** [comment]
@PVince81 backport?

**Comment by PVince81** [comment]
@DeepDiver1975 no... this was technically a forward port

**Pull request merged**
