### PR TITLE
[stable8.1] Decode request content only on getContent

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Backport of #18691 

cc @PVince81 @MorrisJobke @cmonteroluque @karlitschek 

Please confirm @karlitschek ? Minor fix for certain third party WebDAV applications that PUT with specific mimetypes.

### CODE REVIEW

**Comment by karlitschek** [comment]
works! :+1:

**Comment by PVince81** [comment]
:+1:

**Comment by Xenopathic** [comment]
@owncloud-bot retest this please

**Comment by Xenopathic** [comment]
Note: we may also need to backport #19034 to avoid warnings

**Pull request merged**
