### PR TITLE
move uploadWithAllMechanisms to helper

### PR DESCRIPTION
**Pull request by individual-it**
## Description
move function to helper and make it simpler

## Related Issue
part of #33690

## Motivation and Context
make WebDav.php shorter

## How Has This Been Tested?
:robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by phil-davis — DISMISSED** [review]
Looks correct.

**Comment by individual-it** [comment]
@phil-davis please review again, added check if the combinations are valid

**Comment by individual-it** [comment]
this change will break at least the guests and files_classifier app.
PRs to fix the apps:
- https://github.com/owncloud/guests/pull/287
- https://github.com/owncloud/files_classifier/pull/125

**Review by phil-davis — APPROVED** [review]
Validation looks good.
The old code used to specifically do the valid combinations, rather than looping.

**Comment by individual-it** [comment]
backport in #33858

**Pull request merged**
