### PR TITLE
fixed exception, if $node is type SimpleCollection

### PR DESCRIPTION
**Pull request by peterprochaska**
## Description
Fixed Exception, if $node is type Sabre\DAV\SimpleCollection

## Motivation and Context
I don't like exceptions

## How Has This Been Tested?
After the change, i can see remote.php/dav/files again, without an exception

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by DeepDiver1975 — DISMISSED** [review]
- [ ] all other methods need the same check
- [ ] please add unit tests - codecov will be red

**Comment by VicDeo** [comment]
To populate the check across all methods it's better to override getNodeForPath from parent
```
	/**
	 * @param string $path
	 * @return INode|null
	 */
	protected function getNodeForPath($path){
           $node = parent::getNodeForPath($path);
		if (!$node instanceof Node) {
			return null;
		}
           return $node;
        }
```

**Comment by DeepDiver1975** [comment]
> To populate the check across all methods it's better to override getNodeForPath from parent

sounds reasonable - please commit to this branch right away - I want this solved asap

**Comment by VicDeo** [comment]
> The diff coverage is 100%.

:muscle:

**Review by VicDeo — APPROVED** [review]
👍

**Pull request merged**
