### PR TITLE
Fixed app length size problem issue#27564

### PR DESCRIPTION
**Pull request by Dave-Melia**
## Description

I fixed a design bug with the app list in the settings menu which caused the boxes to resize

## Related Issue

https://github.com/owncloud/core/issues/27564

## Motivation and Context

Aesthetics
## How Has This Been Tested?

Tested using a git clone in a Docker container
## Screenshots (if appropriate):
https://i.imgur.com/lBlRmZ0.png
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
@SergioBertolinSG please review

**Comment by SergioBertolinSG** [comment]
@Dave-melia thanks for you contribution.

Currently with this fix the authors of the apps are hidden, and there is no tooltip showing the full string. :-1:

screen shot 2017-04-10 at 09 46 29

**Comment by PVince81** [comment]
Any update ?

**Comment by DeepDiver1975** [comment]
> Any update ?

@Dave-Melia

**Comment by PVince81** [comment]
closing due to lack of feedback

**Pull request closed without merging**
