### PR TITLE
Use buttons and icons for file list actions without text in mobile view

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Enhancement: Use icons + buttons instead of text for file actions in mobile view

Before this PR, as files were selected in the files list, actions was shown with
icon and text, for example: 'Download' and 'Delete'.
This uses much space and UI glitches are possible due to limited screen size.
With this PR we now show buttons with the associated icons without any text.

### Files - Before
image

### Files - After 
image

### Deleted files - Before
image

### Deleted files - After
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
works

**Comment by JanAckermann** [comment]
@pmaier1 agree ?

**Comment by phil-davis** [comment]
As a separate thing, the "..." dropdown also shows each action with icon and text:
webUI-mobile-size-dropdown

Should we remove the text from those?
(I am not sure of the answer myself)

**Comment by JanAckermann** [comment]
@phil-davis we should just shrink items, which takes too much space and conflicts with other elements.
So i vote for everything cool here :+1:

**Review by JammingBen — APPROVED** [review]

**Pull request merged**
