### PR TITLE
[stable8.1] don't allow to create a federated share if source and target are the same

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/owncloud/core/pull/21067

### CODE REVIEW

**Comment by PVince81** [comment]
Blocking local users works.

With LDAP users, sharing with "zombie1@localhost/owncloud" doesn't find the user, probably because we didn't have the mapping detection in 8.1, which is fine.

However, if I share with myself with the LDAP id "b8261b06-36b2-1035-9a72-cd0b96131b42@localhost/owncloud" it goes through. So the blocking doesn't seem to work.

**Comment by PVince81** [comment]
- [x] regular user, share dialog blocking
- [x] regular user, link share blocking
- [ ] LDAP user, ldap uuid share dialog blocking :no_entry_sign: FAIL
- [x] LDAP user, user id share dialog blocking => sharing was not possible with user id back then
- [ ] LDAP user, link share blocking

**Comment by schiesbn** [comment]
This is exactly the mess I expected right from the beginning. To make it work we also need to backport following PRs to 8.1 and 8.0:

- https://github.com/owncloud/core/pull/14401
- https://github.com/owncloud/core/pull/19580

@karlitschek please approve that we should go that far. 

@blizzz @nickvergessen can you take care of the backports if @karlitschek approves it? They create quite some merge conflicts. I would prefer if someone handles them who knows the code better than me, especially in the LDAP case.
Maybe both of you can already check in advance if this pull request can be backported at all without requiring additional backports, to have some more information for @karlitschek to make a decision.

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
@rullzer second review ?
Please be aware that LDAP sharing only works with LDAP ids in that older version.

**Comment by rullzer** [comment]
Tested and also works! :+1:

**Comment by karlitschek** [comment]
:+1: Thanks an backport is fine as mentioned elsewhere :-)

**Pull request merged**
