### PR TITLE
Test publicly shared folder to show up on Shared-By-Link page

### PR DESCRIPTION
**Pull request by skshetry**
## Description

This tests that publicly shared folder appear on `Shared by link` page.

## Related Issue

- Related to #32847 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by skshetry** [comment]
@phil-davis The email again timed out, but the test I had written has passed.

**Comment by phil-davis** [comment]
@skshetry I restarted the drone job

**Comment by skshetry** [comment]
Backport for `stable10` on #32931

**Comment by skshetry** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@skshetry now there are conflicts with other  PRs that have been merged.
Please resolve them.

**Comment by phil-davis** [comment]
Now a tag test fails ???

**Comment by phil-davis** [comment]
@skshetry and more conflicts to resolve

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
I restarted drone again. This PR has no luck.

**Pull request merged**
