### PR TITLE
Signature of overriding method should match the parent

### PR DESCRIPTION
**Pull request by oparoz**
Fix for https://github.com/owncloud/core/issues/17194

@PVince81 I couldn't find any other class which extended that one. Let me know if I've missed one.

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: 

@icewind1991 @nickvergessen

**Comment by rullzer** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
I still see this in RC2:
```
{"reqId":"3efbIbaiE+R2Ji+Nwln9","remoteAddr":"192.168.1.3","app":"PHP","message":"Declaration of OCA\\Files_Sharing\\External\\Scanner::scanFile() should be compatible with OC\\Files\\Cache\\Scanner::scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = NULL, $lock = true) at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/external\/scanner.php#0","level":3,"time":"2015-07-01T08:19:50+00:00"}
```

Seems to be yet another method.

**Comment by oparoz** [comment]
Yep, I should have checked all the methods... :facepalm:

scanChildren also has the new argument...

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/17295

**Pull request merged**
