### PR TITLE
fix updating folder sizes with cross storage move

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes https://github.com/owncloud/core/issues/21236

cc @owncloud/filesystem

### CODE REVIEW

**Comment by PVince81** [comment]
Any chance for a unit test here ?

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
@nickvergessen @rullzer second review please

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
Please backport to 8.1 (8.0 is fine)

CC @DeepDiver1975 @dragotin

**Comment by icewind1991** [comment]
stable8.1: https://github.com/owncloud/core/pull/25116

**Pull request merged**
