### PR TITLE
fix login form alignment

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
## Description
Login form was not centered in IE11

## How Has This Been Tested?
IE11

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by AlexAndBear — APPROVED** [review]

**Comment by JanAckermann** [comment]
@micbar needs backport to 10.8.0

**Comment by ownclouders** [comment]
<details><summary>:boom: Acceptance tests <strong>webUISharingExt1-git-chrome-mariadb10.2-php7.4</strong> failed. The build is cancelled...</summary>

**Comment by micbar** [comment]
Release branch will be rebased tomorrow after the new translations are synced tonight

**Comment by JanAckermann** [comment]
I checked on different browser LGTM,
@hurradieweltgehtunter anything more Todo, or is this final stage from your POV

**Comment by hurradieweltgehtunter** [comment]
Nothing I'm aware of

**Pull request merged**
