### PR TITLE
Move dav app to PSR-4

### PR DESCRIPTION
**Pull request by nickvergessen**
@DeepDiver1975 @rullzer @LukasReschke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
On travis:

````
PHP Fatal error:  Class 'OCA\DAV\AppInfo\Application' not found in /home/travis/build/owncloud/core/apps/dav/appinfo/install.php on line 24

PHP Stack trace:

PHP   1. {main}() /home/travis/build/owncloud/core/index.php:0

PHP   2. OC::handleRequest() /home/travis/build/owncloud/core/index.php:39

PHP   3. OC\Core\Controller\SetupController->run() /home/travis/build/owncloud/core/lib/base.php:821

PHP   4. OC\Setup->install() /home/travis/build/owncloud/core/core/Controller/SetupController.php:64

PHP   5. OC\Installer::installShippedApps() /home/travis/build/owncloud/core/lib/private/Setup.php:370

PHP   6. OC\Installer::installShippedApp() /home/travis/build/owncloud/core/lib/private/Installer.php:539

PHP   7. OC\Installer::includeAppScript() /home/travis/build/owncloud/core/lib/private/Installer.php:568

PHP   8. include() /home/travis/build/owncloud/core/lib/private/Installer.php:620

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/issues/24531

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
