### PR TITLE
fix trashbin previews for text files

### LINKED ISSUE #18516: Previews of text files not working in trashbin
### Steps to reproduce
1. Upload an image and a text file
2. Delete both files
3. Go to trashbin

### Expected
Both rows have a preview

### Actual
The image has a preview
The text has the mimetype icon

@oparoz @georgehrke @PVince81

### PR DESCRIPTION
**Pull request by schiessle**
make sure to add the correct file size to the file info, otherwise we will not show the preview for some file types

Steps to test:
- upload a non-empty text file
- delete it
- go to the trashbin
- check if you have a correct preview for the text file

fix #18516

cc @nickvergessen @georgehrke

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1: works

**Comment by nickvergessen** [comment]
Tests? :-D

**Comment by schiesbn** [comment]
@nickvergessen have you looked at the class and the method? Good luck writing a unit test for it.

**Comment by georgehrke** [comment]
:+1: works

Tests would indeed be great though, but testing this method really seems quite challenging :/

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by schiesbn** [comment]
who is able to click the merge button.... @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
> who is able to click the merge button.... @DeepDiver1975 ?

all checks are green ... @schiesbn you should be in the position to merge ... can't you?

**Comment by schiesbn** [comment]
@DeepDiver1975 no, the merge button is disable for me.



Trying "update branch" first also doesn't help

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2015-09-21 16-11-40


hmmm .... github broken?

**Comment by schiesbn** [comment]
Btw, same for me on all branches already for the whole day.

**Comment by nickvergessen** [comment]
same here, maybe because we are not admins and are not allowed to push to master anymore because it is protected :speak_no_evil:

**Comment by LukasReschke** [comment]
Pretty simple, the branch needs to be up-to-date with master. So you need to rebase upon master and then merge it as soon as CI passed (which takes about 15 minutes) :speak_no_evil: :see_no_evil: :hear_no_evil: 

Once something else is pushed into master you need to repeat this… :gun:

**Comment by LukasReschke** [comment]
… or you are evil as I am and use the GitHub Status API to fake the status and merge stuff without owner permissions :smile:

**Comment by schiesbn** [comment]
since when does it need to be up-to-date? And why only for some people? This doesn't make any sense. As said, I tried the update button but probably someone merged already a other branch before CI finished... and then it starts again

**Comment by LukasReschke** [comment]
> since when does it need to be up-to-date? And why only for some people? 



@DeepDiver1975 is more equal as he has admin permissions.

> This doesn't make any sense. 

From my PoV it does. - We had problems before due to that before. Yes, pain though.

> As said, I tried the update button but probably someone merged already a other branch before CI finished... and then it starts again

Correct. Be faster ;-)

**Comment by LukasReschke** [comment]
Since when: https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by LukasReschke** [comment]
> When using required status checks, your branch must be up-to-date to ensure your tests will pass after merging. The new “Update branch” button lets you merge the latest changes from the base branch of the Pull Request with one click.

**Comment by schiesbn** [comment]
I don't think that this works on a fast moving repository like core. Sorry, I can't click "update" and then stare at the screen and wait until CI finished, hope that nobody merged something in between and repeat the steps until I found a small time window to merge my PR. Imho we should disable this option again.

**Pull request merged**
