### PR TITLE
fix Files sidebar layout of Versions and Sharing

### PR DESCRIPTION
**Pull request by jancborchardt**
Some small layout fixes to polish the design as now everything is moved into the sidebar. (This does not fix the checkboxes or the sharing dropdown yet.)

Please review @owncloud/designers @schiesbn @PVince81

### CODE REVIEW

**Comment by jancborchardt** [comment]
Btw @PVince81 why is there so much duplication between share.css and sharetabview.css? Can’t it be fully removed from share.css when it has been moved to sharetabview.css?

**Comment by PVince81** [comment]
Good point. We should namespace the styles from share.css and then move them to shareTabView.css.

Not sure what to do about "#dropdown", probably remove it.

**Comment by jancborchardt** [comment]
Ok, smth for a different PR though. Can you review this?

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by PVince81** [comment]
:+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 @PVince81 check the fixes for the Activity view as well: https://github.com/owncloud/activity/pull/394

**Pull request merged**
