### PR TITLE
add visibility of methods in server container

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @LukasReschke @DeepDiver1975 @nickvergessen 

Make scrutinizer more happy :)

### CODE REVIEW

**Comment by nickvergessen** [comment]
Do it on the public interface aswell?

**Comment by MorrisJobke** [comment]
> Uh, seems like someone is on fire. 48 issues were fixed!

**Comment by MorrisJobke** [comment]
@nickvergessen Done

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
