### PR TITLE
Groupmanagers displayNamesInGroup should actually search in displaynames

### PR DESCRIPTION
**Pull request by rullzer**
I was looking into #6967.
At first I thought it was a bug in the ajax/share.php however it seems the displayNamesInGroup only searchers uid's. I assume it should search in displayNames.

Lets see how Jenkins feels about this. Probably I can add a few more unit tests. But I'll look into that.

Once we have a clean fix in place this should probably be backported.

### CODE REVIEW

**Comment by rullzer** [comment]
@icewind1991 @PVince81 @DeepDiver1975 could you have a look if the patch makes any sense?

**Comment by icewind1991** [comment]
Looks good to me

**Comment by DeepDiver1975** [comment]
@rullzer still WIP? THX

**Comment by rullzer** [comment]
@DeepDiver1975 ah forgot that one. No it should be ready for review now. Unit tests were already in place but just testing the wrong thing. I think this is fine now.

**Comment by DeepDiver1975** [comment]
@rullzer THX
@MorrisJobke @nickvergessen review? THX

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by nickvergessen** [comment]
Odd, tested and works now :+1:

**Comment by rullzer** [comment]
@nickvergessen it did not work before?

**Comment by nickvergessen** [comment]
yes

**Pull request merged**
