### PR TITLE
[stable10] Show new basename and extension while waiting for AJAX rename

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #29680

### CODE REVIEW

**Comment by phil-davis** [comment]
Can be merged either before or after 10.0.5 - your choice @PVince81

**Review by PVince81 — APPROVED** [review]
:+1: 10.0.5 is fine as the tests confirm it's working

**Comment by PVince81** [comment]
Rebased for Drone, due to yarn having been merged in parallel. Hope it helps.

**Comment by phil-davis** [comment]
@PVince81 this can be merged whenever suits. Resisting pressing the button myself since you are now controlling anything being merged for 10.0.5 RCn builds

**Pull request merged**
