### PR TITLE
adjust navigation text opacity, fix #19016

### LINKED ISSUE #19016: Grey colors in the sidebar very hard to read
The new grey colors in the side bar are really hard to read. They may look fancier but besides this I think they decrease UX. At least I _really_ do prefer the previous 8.0 ones…

The following pictures are from about 80cm distance from a 27' monitor with 2560x1440 pixel.

Before (8.0): 

photo-2015-09-14-15-23-31_2610

After (master):
photo-2015-09-14-15-21-22_2609

<hr/>

cc @jancborchardt

### PR DESCRIPTION
**Pull request by jancborchardt**
Slightly increases the readability of the navigation entries. Fix https://github.com/owncloud/core/issues/19016

Please review @owncloud/designers @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Will test tomorrow.

**Comment by karlitschek** [comment]
can you post a before and after screenshot?

**Comment by jancborchardt** [comment]
It’s a very very slight change. Otherwise the contrast to the active entry is not enough anymore.

capture du 2015-09-15 19-27-07 capture du 2015-09-15 19-29-17

**Comment by LukasReschke** [comment]
Increases readability :+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
