### PR TITLE
treat LDAP users not available by user filter as deleted

### PR DESCRIPTION
**Pull request by ryno83**
New PR for the deleted one in #15847 

Sorry for the mess !!!

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@blizzz please review - THX

**Comment by jancborchardt** [comment]
@owncloud/ldap can you test this? You can also use this shorthand mention to get your pull requests reviewed. :)

**Comment by ryno83** [comment]
@owncloud/ldap I made a lot of tests on two different versions : 8.1.4 and 9.0 pre alpha.
* On my 8.1.4 installation, all my tests was successful.
* On 9.0 (github master copy) I got a weird result. I will try to explain the best I can : On my ldap configuration (AD) I use a userfilter group to control access to owncloud. Also, I use ldap groups to control work team sharing (A user in a team group cannot have access if it's not in the userfilter group). If I remove a user from userfilter group on my AD the user appear in the ldap:show-remnants. if I delete the user with user:delete the user is deleted. So far everything is normal but because the user is still in a work team group the deleted user reapear in ldap:show-remnants. This doesn't append in 8.1.4

**Comment by blizzz** [comment]
@ryno83 i do not think there were any changes in the workflow between 8.1.4 and now. If the user reappears in the show-remnants list, then one possibility is that the removal was not complete, as in his entry is still in the LDAP user mappings table after deletion. Can you verify?

The other is that the user somehow got mapped again, ignoring the LDAP user filter. That must be the case if you can rule out the first possibility. Now I would not know how this could happen.

**Comment by blizzz** [comment]
> The other is that the user somehow got mapped again, ignoring the LDAP user filter. That must be the case if you can rule out the first possibility. Now I would not know how this could happen.

I could reproduce this behaviour on master. It does not work when the users are from different bases then allowed, however they will be mapped independently from the LDAP filter. This, however, is not caused by this pull request.

**Comment by blizzz** [comment]
@ryno83 actually, I see this also with current 8.1 from git and also specifically with 8.1.4 and 8.1.3. I will open a bug report for this. It's a blocker for this PR, it obviously turns you (admin) into Sisyphus ever deleting users.

**Comment by blizzz** [comment]
Bug filed here: https://github.com/owncloud/core/issues/20588

**Comment by blizzz** [comment]
This works for me, also the integration tests pass.

#20588 is still present, which is gets more difficult because it has another corner case (i add input there), but it is not a blocker for this. :+1:  from me, when units test pass. For unit tests, see https://github.com/owncloud/core/pull/21002

**Comment by MorrisJobke** [comment]
Tested and my LDAP setup still works :+1:

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Jenkins just run fine in #21002

**Comment by blizzz** [comment]
@carlaschroder Change starting 9.0 with LDAP user cleanup: a user is now detected as deleted, when he cannot be fetched according to the LDAP user filter. Before, the user was required to be totally deleted from the LDAP server.

**Comment by ryno83** [comment]
@blizzz @MorrisJobke Did you try the modification proposed (not commited yet) 10 days ago ? See my comments for the commit 3c53a0d. All my tests show me that it would be the equivalent. Personnaly, I prefer this way : less code modifications. let me know if you want me to commit.

**Comment by blizzz** [comment]
@ryno83 thanks for the heads up. Yes, I though what I commented here 
https://github.com/owncloud/core/pull/18212#commitcomment-14770688 was already part of the commit. My fault.

However, in the end, whether you request the display name attribute or just purely check the existence, it does not matter. Adding the $userFilter to the method call is the secret ingredient.

**Comment by MorrisJobke** [comment]
@blizzz Would it make sense to backport this to stable8.2?

**Comment by blizzz** [comment]
@MorrisJobke imho not, because it causes a behavioural change.

**Pull request merged**
