### PR TITLE
Fix for #23066

### PR DESCRIPTION
**Pull request by TDannhauer**
Fix for #23066  - this time without changing the line breaks

### CODE REVIEW

**Comment by PVince81** [comment]
Seems the newlines are wrong again.

If you like you can also leave it as is and we can take care of it :smile: 
The fact that you found how to fix this is already a very valuable contribution.

**Comment by TDannhauer** [comment]
very strange.. the graphical diff showed only the modified line, whereas in the recently closed PR the line ending issue was shown.  

However, I'll try to solve it to learn and to be able contribution to OC without your babysitting (thanks :))
If I fail I'll contact you :)

**Comment by PVince81** [comment]
@TDannhauer thanks !

There's still a bit of time before the 9.0.3 maintenance release :smile:

**Comment by nickvergessen** [comment]
The diff reads like real pain: https://github.com/owncloud/core/pull/24689/files?w=1

Again an issue with int vs string

**Comment by nickvergessen** [comment]
I pushed a fix for the messed up file ends

**Comment by TDannhauer** [comment]
@PVince81 My daughter was born on 20th may, I was not able to finish it before.

Can you please chip in and adapt the tests to help that this fix can make it into 9.0.3?

Thanks,
Torben

**Comment by PVince81** [comment]
@TDannhauer congratulations !

And thanks for the info, we'll take it from there. :smile:

**Comment by nickvergessen** [comment]
Rebased and adjusted the tests

**Comment by TDannhauer** [comment]
Thanks Joas!

**Comment by PVince81** [comment]
:+1:

@rullzer second review ?

**Comment by TDannhauer** [comment]
Can I see the mentioned confilcts in Github graphically?

**Comment by nickvergessen** [comment]
I rebased it once again for you :wink:

**Comment by PVince81** [comment]
> Can I see the mentioned confilcts in Github graphically?

@TDannhauer I don't think Github has such feature

**Comment by PVince81** [comment]
@nickvergessen @owncloud/sharing @icewind1991 second review ?

**Comment by nickvergessen** [comment]
Well :+1: since I only ever rebased and fixed the tests

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by PVince81** [comment]
We should backport this to OC 9.0.3

CC @DeepDiver1975 @cmonteroluque

**Comment by PVince81** [comment]
Had to do some patch editing gymnastics thanks to file renames.

stable9: https://github.com/owncloud/core/pull/24956

**Comment by icewind1991** [comment]
> Had to do some patch editing gymnastics thanks to file renames.

```
git config merge.renameLimit 99999
```

Will make git try a little harder with renames

**Pull request merged**
