### PR TITLE
UI tests for renaming a file inside a folder with problematic name

### PR DESCRIPTION
**Pull request by individual-it**
## Description
test if file reaming works inside folders with problematic names

## Motivation and Context
test some more edge cases

## How Has This Been Tested?
run the tests locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by individual-it** [comment]
@sushilkshetri please sign the CLA

**Review by phil-davis — COMMENTED** [review]
We should use camelcaswe in the file nAme
problematicFilename.feature

**Comment by sushilkshetri** [comment]
Rename the file name and locate into its proper location.

**Review by phil-davis — APPROVED** [review]

**Comment by individual-it** [comment]
backport in #29961

**Pull request merged**
