### PR TITLE
Use new updater URL + add unit tests

### PR DESCRIPTION
**Pull request by LukasReschke**
Uses the new updater url "https://updates.owncloud.com/server/"

@karlitschek @VicDeo

### CODE REVIEW

**Comment by LukasReschke** [comment]
To test this set `$OC_Version` to `array(8, 0, 0, 7)`, `$OC_Channel` to `stable` and `$OC_Build` to a value from the last build (grab it from the release ball), also you need to have no enterprise edition (i.e. disable enterprise key app)

**Comment by LukasReschke** [comment]
Should call something like https://updates.owncloud.com/server/?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00
 then

**Comment by LukasReschke** [comment]
Of course Jenkind has other values. Gotta love hard-coded static stuff. Will adjust tests later...

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
The updater app has to be adopted as well? https://github.com/owncloud/updater/blob/master/lib/app.php#L42

@LukasReschke @VicDeo THX

**Comment by LukasReschke** [comment]
https://github.com/owncloud/updater/pull/139

**Comment by DeepDiver1975** [comment]
thx - merged

**Pull request merged**
