### PR TITLE
Close cursor after checking for existing config values

### LINKED ISSUE #13705: Concurrent PROPFINDs result in error 500
### Steps to reproduce
1. Create a folder /c/a/ in your account (not sure if meaningful).
2. Run 
```bash
for (( c=1; c<=5; c++ )) 
do 
curl --user <user>:<pass> -X PROPFIND -o out${c}.txt -H "Content-Type: text/xml" -d "<?xml version='1.0' encoding='utf-8' ?><D:propfind xmlns:D='DAV:'><D:allprop/></D:propfind>" http://<domain/path>remote.php/webdav/c/a/ &
done
```

### Expected behaviour
All requests should finish with HTTP code 207; files out1.txt to out5.txt should contain the properties of the folder /c/a/,  something like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>[edited]/remote.php/webdav/c/a/</d:href>
      <d:propstat>
        <d:prop>
          <oc:id>00000044ocee3337d5cf</oc:id>
          <oc:permissions>RDNVCK</oc:permissions>
          <d:getetag>"54c75bef2d6bc"</d:getetag>
          <d:getlastmodified>Tue, 27 Jan 2015 09:35:43 GMT</d:getlastmodified>
          <d:resourcetype><d:collection/></d:resourcetype>
          <d:quota-used-bytes>0</d:quota-used-bytes>
          <d:quota-available-bytes>6199443456</d:quota-available-bytes>
        </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

### Actual behaviour
4 of 5 methods finish in 500 Internal Error.

### Server configuration

**ownCloud version:** - 8.0.0.4

daily/master

#### ownCloud log (data/owncloud.log)
One message
```
An exception occurred while executing 'UPDATE "oc_preferences" SET "configvalue" = ? WHERE "userid" = ? AND "appid" = ? AND "configkey" = ? ' with params [1422353148, "<user>", "login", "lastLogin"]: SQLSTATE[HY000]: General error: 5 database is locked
```
is shown per failed request.

### Extra
Not only affecting PROPFIND requests, Android client is receiving 500 Internal error when downloads (GET) and refresh (PROPFIND) are run in parallel .

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/13705

@DeepDiver1975 @guruz @davivel @icewind1991 @MorrisJobke

### CODE REVIEW

**Comment by guruz** [comment]
nice.. e.g. see https://github.com/owncloud/core/issues/6536

**Comment by PVince81** [comment]
Wow yeah, so this is old.

**Comment by MorrisJobke** [comment]
:+1: works :)

**Comment by PVince81** [comment]
@karlitschek backport ?

**Comment by karlitschek** [comment]
backport please

**Comment by MorrisJobke** [comment]
@LukasReschke Mind to review?

**Comment by LukasReschke** [comment]
Makes sense :+1:

I feel not really qualified to backport this change on my own. Can you please take care of that @PVince81?

**Comment by PVince81** [comment]
Yes, @MorrisJobke cleant up a lot of the config code so there might be conflicts.
I'll have a  look.

**Comment by PVince81** [comment]
I checked the code on stable7 and there is no such query.
I also tested the PROPFIND test case against stable7 and the issue didn't exist on that version.
So... no backport needed :smile:

**Comment by PVince81** [comment]
I found similar code in stable7 that could affect oc_preferences, see https://github.com/owncloud/core/pull/13831

**Pull request merged**
