### PR TITLE
[tests-only][full-ci][do-not-merge] run tests with pgsql 11

### PR DESCRIPTION
**Pull request by individual-it**
testing for https://github.com/owncloud/enterprise/issues/5064

### CODE REVIEW

**Comment by phil-davis** [comment]
PHP unit tests passed - good
https://drone.owncloud.com/owncloud/core/34866/21/8

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareOperationsToShares2-pgsql11-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/34866/71/1

**Comment by individual-it** [comment]
rerunning with full-ci to see what acceptance tests will fail

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/34869/60/13
```
runsh: Total unexpected failed scenarios throughout the test run:
apiShareOperationsToShares2/shareAccessByID.feature:50
apiShareOperationsToShares2/shareAccessByID.feature:51
apiShareOperationsToShares2/shareAccessByID.feature:52
apiShareOperationsToShares2/shareAccessByID.feature:53
```

```
Scenario Outline: Get a share with an invalid share id                    # /drone/src/tests/acceptance/features/apiShareOperationsToShares2/shareAccessByID.feature:40
    Given using OCS API version "<ocs_api_version>"                         # FeatureContext::usingOcsApiVersion()
    When user "Alice" gets share with id "<share_id>" using the sharing API # FeatureContext::userGetsTheLastShareWithTheShareIdUsingTheSharingApi()
    Then the OCS status code should be "404"                                # OCSContext::theOCSStatusCodeShouldBe()
    And the HTTP status code should be "<http_status_code>"                 # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the API should not return any data                                  # FeatureContext::theApiShouldNotReturnAnyData()

    Examples:
      | ocs_api_version | share_id   | http_status_code |
      | 1               | 2333311    | 200              |
      | 2               | 2333311    | 404              |
      | 1               | helloshare | 200              |
        OCS status code is not any of the expected values 404 got 996
        Failed asserting that an array contains '996'.
      | 2               | helloshare | 404              |
        OCS status code is not any of the expected values 404 got 500
        Failed asserting that an array contains '500'.
      | 1               | $#@r3      | 200              |
        OCS status code is not any of the expected values 404 got 996
        Failed asserting that an array contains '996'.
      | 2               | $#@r3      | 404              |
        OCS status code is not any of the expected values 404 got 500
        Failed asserting that an array contains '500'.
      | 1               | 0          | 200              |
      | 2               | 0          | 404              |
```
"something happens" (tm) when we request a non-existent share-id and use a non-numeric string.

I will run a PR with pgsql 10 to confirm if this happens or not in pgsql 10.

**Comment by phil-davis** [comment]
See #39878 for a later PR.

**Pull request closed without merging**
