### PR TITLE
[WIP] Dispatch etag change on event dispatcher

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by guruz** [comment]
* [ ] Support for share(d) folders
* [ ] Add etag transition in message: old etag AND new etag
* [ ] If possible also add the fileId (can help the client at a later stage, i had some ideas)


FYI @PVince81

**Comment by DeepDiver1975** [comment]
> If possible also add the fileId (can help the client at a later stage, i had some ideas)

I wanted to keep the load minimalistic - the idea is to only send a notification for the root etag change.

**Comment by DeepDiver1975** [comment]
> Add etag transition in message: old etag AND new etag

with the current approach this will be problematic since the etag is computed and we don't have the explicit change available in the db

**Comment by DeepDiver1975** [comment]
> Support for share(d) folders

agreed

**Pull request closed without merging**
