### PR TITLE
[stable8] Determine the size we need before asking for a thumbnail

### PR DESCRIPTION
**Pull request by MorrisJobke**
backport of #16911
approval: https://github.com/owncloud/core/pull/16911#issuecomment-115221069

Tested and works.

cc @oparoz @LukasReschke @PVince81

### CODE REVIEW

**Comment by rullzer** [comment]
Looks good!
I can't test the high DPI version. But on my screen the result is still as expected.

:+1:

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by MorrisJobke** [comment]
@Xenopathic @oparoz @PVince81 @jbtbnl A second reviewer is needed for this easy changeset :)

**Comment by oparoz** [comment]
Can I really review my own patch if it's a backport?

**Comment by MorrisJobke** [comment]
> Can I really review my own patch if it's a backport?

It is about testing that it works in the new environment (stable8 instead of master). I would say yes.

**Comment by Xenopathic** [comment]
:+1:

**Pull request merged**
