### PR TITLE
Allow removing of link password in OCS again

### PR DESCRIPTION
**Pull request by rullzer**
My commit b0aa17b13fe504445a3108e46a56031ca4b73bc6 set no password for a link share to 'NULL' but this should be null. Else it will just be the string 'NULL'.

This commit fixes that and extends the unit tests to make sure that we can actually unset the password of a link share.

CC: @DeepDiver1975 @LukasReschke @schiesbn @MorrisJobke @PVince81

### CODE REVIEW

**Comment by schiesbn** [comment]
looks good :+1:

**Comment by PVince81** [comment]
@nickvergessen review ?

**Comment by LukasReschke** [comment]
:+1:

**Comment by rullzer** [comment]
I'll also prepare a backport request to stable8 as the same bug is present there.

CC: @karlitschek

**Comment by karlitschek** [comment]
Yes. please back port :+1:  :-)

**Pull request merged**
