### PR TITLE
[stable9] Workaround to check htaccess in case of redirects

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/25331 to stable9

Please review @RealRancor @owncloud/javascript @guruz @DeepDiver1975 @georgehrke @VicDeo

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] backport test fix https://github.com/owncloud/core/pull/25439

**Comment by DeepDiver1975** [comment]
:-1: js red

**Comment by PVince81** [comment]
backported fix

**Comment by VicDeo** [comment]
:+1: works. Looks like build is stalled

**Comment by PVince81** [comment]
@DeepDiver1975 second review ?

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
