### PR TITLE
Return milliseconds instead of seconds for lastLogin - refs #14005

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
refs #14005

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
shame on me

````
	Test Result (8 failures / +8)

    OC\Settings\Controller\UsersControllerTest.testIndexAdmin
    OC\Settings\Controller\UsersControllerTest.testIndexSubAdmin
    OC\Settings\Controller\UsersControllerTest.testIndexWithSearch
    OC\Settings\Controller\UsersControllerTest.testIndexWithBackend
    OC\Settings\Controller\UsersControllerTest.testRestorePossibleWithoutEncryption
    OC\Settings\Controller\UsersControllerTest.testRestorePossibleWithAdminAndUserRestore
    OC\Settings\Controller\UsersControllerTest.testRestoreNotPossibleWithoutAdminRestore
    OC\Settings\Controller\UsersControllerTest.testRestoreNotPossibleWithoutUserRestore
````

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
