### PR TITLE
Lock scanner to the given user

### LINKED ISSUE #17414: CLI scan ignores passed user / options parser seems broken
### Steps to reproduce
1. Create two users "user1" and "user2"
2. Login as "user1"
3. Create a folder "test"
4. Upload a file into "test"
5. On the CLI: `sudo -uwwwrun ./occ files:scan --path=test user1`
6. On the CLI: `sudo -uwwwrun ./occ files:scan user1`

### Expected result
Both commands can run

### Actual result
```
# sudo -uwwwrun ./occ files:scan --path=test user1
Unknown user test

# sudo -uwwwrun ./occ files:scan user1
Scanning file   /
Scanning folder /
Scanning file   /user1
Scanning file   /.locks
Scanning file   /.ocdata
Scanning file   /root
Scanning file   /index.html
Scanning file   /owncloud.log
Scanning folder /user1
Scanning file   /user1/thumbnails
Scanning file   /user1/files
Scanning file   /user1/cache
Scanning folder /user1/thumbnails
Scanning file   /user1/thumbnails/17
Scanning file   /user1/thumbnails/11
Scanning folder /user1/thumbnails/17
Scanning file   /user1/thumbnails/17/36-36.png
Scanning file   /user1/thumbnails/17/2048-1536-max.png
Scanning folder /user1/thumbnails/11
Scanning file   /user1/thumbnails/11/36-36.png
Scanning file   /user1/thumbnails/11/2048-2048-max.png
Scanning folder /user1/files
Scanning file   /user1/files/test
Scanning file   /user1/files/welcome.txt
Scanning folder /user1/files/test
Scanning file   /user1/files/test/P1040667.JPG
Scanning folder /user1/cache
Scanning folder /.locks
Scanning folder /root
Scanning file   /root/thumbnails
Scanning file   /root/files
Scanning folder /root/thumbnails
Scanning file   /root/thumbnails/3
Scanning folder /root/thumbnails/3
Scanning file   /root/thumbnails/3/36-36.png
Scanning file   /root/thumbnails/3/2048-2048-max.png
Scanning folder /root/files
Scanning file   /root/files/welcome.txt
Scanning file   /user1/
Scanning folder /user1/
Scanning file   /user1/thumbnails
Scanning file   /user1/files
Scanning file   /user1/cache
Scanning folder /user1/thumbnails
Scanning file   /user1/thumbnails/17
Scanning file   /user1/thumbnails/11
Scanning folder /user1/thumbnails/17
Scanning file   /user1/thumbnails/17/36-36.png
Scanning file   /user1/thumbnails/17/2048-1536-max.png
Scanning folder /user1/thumbnails/11
Scanning file   /user1/thumbnails/11/36-36.png
Scanning file   /user1/thumbnails/11/2048-2048-max.png
Scanning folder /user1/files
Scanning file   /user1/files/test
Scanning file   /user1/files/welcome.txt
Scanning folder /user1/files/test
Scanning file   /user1/files/test/P1040667.JPG
Scanning folder /user1/cache
```

It seems it has trouble parsing the command line arguments.
In the first case it thought that "test" was the user name, and in the second case it scanned everything instead of just the user's home.

@icewind1991 @DeepDiver1975 @nickvergessen 

### Versions
ownCloud 8.1 RC2 and master
php5-5.6.9-1.1.x86_64

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #17414

Set the path to `'/' . $user` when no other path is given

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works now. This fixes the issue. Also the code looks good :+1:

@karlitschek The issue was filed against 8.1.1. Can you confirm the backport after this is merged to master? Thanks :)

**Comment by PVince81** [comment]
:+1: makes sense

**Comment by MorrisJobke** [comment]
@icewind1991 Can you prepare the backport PR ;)

**Comment by karlitschek** [comment]
yes please backport :+1: :-)

**Comment by DeepDiver1975** [comment]
backport https://github.com/owncloud/core/pull/17676

**Comment by MorrisJobke** [comment]
@karlitschek There was the question about a backport to stable8.0 of this fix in https://github.com/owncloud/core/issues/17414#issuecomment-160542900

@icewind1991 How risky is this backport and does it make sense to do the backport? I think so.

**Comment by MorrisJobke** [comment]
@karlitschek I added the blue label because of https://github.com/owncloud/core/issues/17414#issuecomment-160542900 ;)

**Comment by karlitschek** [comment]
backport makes sense. thanks

**Comment by MorrisJobke** [comment]
@icewind1991 Can you please take care of the backport? Thanks

**Comment by icewind1991** [comment]
- 8.0: https://github.com/owncloud/core/pull/20844

**Pull request merged**
