### PR TITLE
More elaborate command description for upgrade

### LINKED ISSUE #14864: Extend ./occ upgrade description to clarify this won't automatically download and update the latest version
Hi,

some people think that the "./occ upgrade" command will download and install the latest OC update:

https://github.com/owncloud/updater/issues/94
https://forum.owncloud.org/viewtopic.php?f=31&t=27011
(And IIRC also some other questions in either the mailinglist or IRC)

Maybe the text should be extended that this is not the case?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #14864

@MorrisJobke @PVince81 @nickvergessen

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by LukasReschke** [comment]
Looked at it very carefully :+1:

**Comment by schiesbn** [comment]
awesome :+1:

**Comment by danimo** [comment]
:+1:

**Pull request merged**
