### PR TITLE
Integration tests - for file exists step, throw exception if the file…

### PR DESCRIPTION
**Pull request by phil-davis**
… does not exist

## Related Issue
#29700 

## How Has This Been Tested?
Tried making some steps for files that actually do not exist, ran the scenarios and confirmed that the step now fails if the file does not exist.

CI will run through all the existing integration tests and maybe find some interesting results.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
@DeepDiver1975 @PVince81 @SergioBertolinSG @davitol @individual-it 
I discovered just now that a step like:
```
Then as "alice" the file "/file.txt" exists
```
always passes, whether the file exists or not.

This is my first try at fixing it (the check I have put here does make it fail if the file does not exist). But maybe there is a cleaner way to decide if the ``listFolder()`` response is good or not?

**Review by individual-it — DISMISSED** [review]
we need tests to test the tests

**Comment by phil-davis** [comment]
Yes, over time somehow each step needs to have it confirmed that if something is wrong, the step will actually fail. Maybe I should write a framework for automatically testing test frameworks?

**Comment by individual-it** [comment]
image

**Comment by phil-davis** [comment]
The 2nd commit fixes 2 tests that failed after the code was fixed in the 1st commit.
For both of those, there was a typo in the expected file name. But even then, actually the previous step did "upload with all mechanisms" which creates a set of uploads that add old/new dav/chunking suffixes to the file names.
So I made a new step definition that checks that each of the files with the generated suffixes exists.

**Review by individual-it — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport stable #29719

**Pull request merged**
