### PR TITLE
Extend fallback scrollContainer object

### LINKED ISSUE #30064: files action menu does not scroll into view on public link page
### Steps to reproduce
1. create a public link with R/W permissions
2. access that link with a browser
3. try to delete a file that is just visible in the browser window

### Expected behaviour
the file list should scroll up so that the file action menu is visible

### Actual behaviour
the file action menu stays hidden, user needs to scroll manually
if other menus are opened they partly overlap
image

There was a very similar bug in the normal filelist of the user a long time ago, I just cannot find it now

### Server configuration
**Operating system**:
Ubuntu 17.10
**Web server:**
Apache2
**Database:**
SQlite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.0.4 (git)
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git
### Client configuration
**Browser:**
FF 57 , Chrome 63
**Operating system:**
Ubuntu 17.10

### PR DESCRIPTION
**Pull request by lordelix**
## Description

Opening the files action menu in public links scrolls view to show the whole menu.

## Related Issue

Fixes https://github.com/owncloud/core/issues/30064

## How Has This Been Tested?

Visual test in latest IE, Edge, FF und Chrome

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
Scrolling to show the actions menu is not working on the ordinary Files page. Travis UI tests failed, and I can see the problem manually (the rows scroll, but not into view). A possible fix is in PR #30109 - cherry pick that if you like, or work out some less hacky-feeling way to make the scrolling work reliably on all variations of the files page.

**Comment by felixheidecke** [comment]
I guess the best way is to add a class to the HTML documents called scoll-container and use that instead of checking for existing elements. I'll go ahead and do that.

**Comment by phil-davis** [comment]
s/scoll-container/scroll-container
sounds good

**Comment by phil-davis** [comment]
@felixheidecke any progress?

**Comment by phil-davis** [comment]
@felixheidecke is anything happening with this? 
(and/or my related #30109 that has one possible hack)
Or is it going in the "will be fixed by Phoenix" bucket?

**Comment by felixheidecke** [comment]
Oh yeah … not sure why this was abandoned. Are you mentioning this because the problem persists?
I can go ahead and revive it in the next sprint.

**Comment by phil-davis** [comment]
I rebased this just now. Then rebased #30109 also. When CI catches up, I will have a look and see if something useful can be done with this stuff.

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
