### PR TITLE
[stable8.1] Use certificates that expire in 10 years

### PR DESCRIPTION
**Pull request by LukasReschke**
:speak_no_evil: :speak_no_evil: :speak_no_evil:

@DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by PVince81** [comment]
Here it's php7 that's unhappy ?!

**Comment by LukasReschke** [comment]
> Here it's php7 that's unhappy ?!

Expected. They will fail on anything except master. Only default matters on non-master branches.

**Comment by MorrisJobke** [comment]
:+1;

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
