### PR TITLE
use string array when fetching share ids

### PR DESCRIPTION
**Pull request by butonic**
fixes https://github.com/owncloud/core/issues/25226
tested with customer

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by georgehrke** [comment]
👍 looks good

**Comment by butonic** [comment]
@PVince81 fix for #25226 taken care of

**Comment by PVince81** [comment]
Databases are so weird... :+1:

**Comment by PVince81** [comment]
@butonic does it affect 9.0 and 9.1 too ?

**Comment by PVince81** [comment]
weird test failures: https://ci.owncloud.org/job/ocs-api-integration-tests-ci/11790/console related to provisioning API. unrelated ?

**Comment by PVince81** [comment]
never mind...
```
cURL error 7: Failed to connect to localhost port 8083: Connection refused
```

**Comment by DeepDiver1975** [comment]
> @butonic does it affect 9.0 and 9.1 too ?

to be analysed

**Comment by butonic** [comment]
9.0 and 9.1 use a different mechanism to propagate changes. I also grepped for PARAM_INT_ARRAY in master but found nothing suspicious. The default is string.

**Comment by PVince81** [comment]
Let's rebase, would be good to see the OCS API test pass too, especially that such tests involve shares

**Comment by PVince81** [comment]
All green! Congrats!

**Pull request merged**
