### PR TITLE
Move \OC\AppFramework to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
Big one ;)
- Had to move the adding of the autoloader a bit up. Since initpaths needs it (for the 3rdparty autoloader).
- Fixed some faulty includes (Appframework vs AppFramework).

CC: @nickvergessen @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and still works 👍

**Comment by DeepDiver1975** [comment]
integration tests badly falling apart :-1:

**Comment by LukasReschke** [comment]
```
09:48:23 [Fri Apr 22 09:48:23 2016] ::1:43506 [500]: /ocs/v2.php/cloud/users/user0 - Class 'OC\AppFramework\routing\RouteConfig' not found in /ssd/jenkins/workspace/ocs-api-integration-tests-ci@2/lib/public/appframework/app.php on line 98
```

Seems like some `use` statements are not adjusted? ;)

**Comment by rullzer** [comment]
Will take care... But now the big question why phpstorm did not find those...

**Comment by rullzer** [comment]
Ok Fixed.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
