### PR TITLE
Issue/13451 redis json encode

### LINKED ISSUE #13451: [Redis] redis can only store string values - breaks storing of arrays

### PR DESCRIPTION
**Pull request by nickvergessen**
Didn't test it and also Jenkins does not Test Redis.

@DeepDiver1975 @butonic @LukasReschke 

Fix #13451

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@butonic can you please execute the unit tests against your redis setup? THX

**Comment by DeepDiver1975** [comment]
unit test executing with local redis server :+1: 

````
deepdiver@alien:~/Development/ownCloud/core-autotest [issue/13451-redis-json-encode]$ ./autotest.sh oci tests/lib/memcache/redis.php 
Using database oc_autotest
Setup environment for oci testing ...
drop the database

Benutzer wurde gelöscht.

create the database

Benutzer wurde erstellt.


Benutzer wurde geändert.


Benutzerzugriff (Grant) wurde erteilt.

INDEX
END INDEX
Testing with oci ...
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /home/deepdiver/Development/ownCloud/core-autotest/tests/phpunit-autotest.xml

..........

Time: 21.84 seconds, Memory: 34.25Mb

OK (10 tests, 35 assertions)

**Comment by DeepDiver1975** [comment]
tested on apps page as well where the issue was discovered first

**Comment by DeepDiver1975** [comment]
@icewind1991 @PVince81 @blizzz please review - THX

**Comment by icewind1991** [comment]
Makes sense :+1:

**Pull request merged**
