### PR TITLE
Fix share indicator handling

### LINKED ISSUE #25311: Share indicator not appearing upon sharing, only after refresh
### Steps
1. Create a folder "test"
2. Share "test" with another user or with link
3. Check the share icon/indicator on the row
### Expected result

Share indicator is updated to say "Shared"
### Actual result

The row is re-rendered, but the indicator still doesn't say anything.
Only after refreshing the page it says "Shared".
### Versions

Observed on v9.0.2 and v9.1.0RC1

Regression from v8.2.5

### PR DESCRIPTION
**Pull request by PVince81**
Properly update the fileInfoModel with the updated share types, which
also updates the file list row indicator properly

Fixes https://github.com/owncloud/core/issues/25311
- [x] Need to check performance impact because this code is sometimes called even when there are no changes
- [x] JS unit tests

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Works fine 👍 
Tested on chrome, firefox, safari, edge and ie11.

**Comment by DeepDiver1975** [comment]
Again the Oracle Docker did not Start ....

**Comment by PVince81** [comment]
>  Need to check performance impact because this code is sometimes called even when there are no changes

In general Backbone only fires change events if attributes are really changed. So setting the same attributes to the same value will not fire any change event so it should be fine.

**Comment by PVince81** [comment]
Added unit tests

**Comment by butonic** [comment]
does not work with 10.0beta2

**Comment by PVince81** [comment]
@butonic this isn't merged yet. Or did you patch 10.0beta2 with this PR to test it ?

**Comment by butonic** [comment]
yup, I patched 10.0beta2 and the bug was still there. double checked the code in the browser wasn't cached

**Comment by PVince81** [comment]
You're right. Apparently the indicator only updates for local shares.

Could be related to the changes related to link shares related to multiple link changes.
Let me see if I can quickly fix this...

**Comment by PVince81** [comment]
Rebased, and added fix for link shares.

Please retest.

**Comment by butonic** [comment]
👍

**Pull request merged**
