### PR TITLE
add whitespace to bottom of files list to correctly show dropdowns

### LINKED ISSUE #15801: Share menu of items in the bottom of the list is not visible
When sharing a item in the bottom of the list the share menu opens itself below it which is not accessible. Please see the screenshot.

snapshot47

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #15801, please review @donniezazen @nickvergessen @owncloud/designers 

Who removed that whitespace in the first place? cc @MorrisJobke @PVince81 do you know? Did it have something to do with lazy loading? Seems to work fine.

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1: makes sense

**Comment by oparoz** [comment]
This fix makes a little difference in the sense that on 8.0, the menu is too close to the bottom of the screen, but it doesn't address the main problem imho. That menu should either slide up or the window should scroll so that the user has full access to the menu without having to scroll the window himself.

**Comment by jancborchardt** [comment]
I'm pretty sure it will also solve the original problem to an extent since you will probably scroll the list down a bit further before pressing share on an item.

**Comment by oparoz** [comment]
Well, I just gave it a go and, as a user, you don't naturally create empty space at the bottom of the interface when scrolling, but even if you do, you probably won't leave enough for the whole menu (when already shared), requiring an extra step to scroll down. It's not a big deal, but I think autoscrolling would be a nice touch.

**Comment by jancborchardt** [comment]
@oparoz do you want to add it? If it's nice and smooth that would indeed be a good addition. :)

**Comment by donniezazen** [comment]
An ideal long term solution would be to create menu wherever the space is that is either top or bottom. I am not sure hijacking mouse is a very good idea. You go down in the list and the whole page is automatically moved up doesn't sound like the best possible solution.

**Comment by jancborchardt** [comment]
You know what: Before we introduce any additional magic, let's solve this issue in the simplest, most non-breaking way possible for 8.1

Please review and +1 if it works. cc @owncloud/designers

**Comment by oparoz** [comment]
@donniezazen - The idea is to just scroll the window enough so that you can see the whole menu. I'll create a PR to illustrate what I mean.

@jancborchardt - I don't like the fact that this creates empty space at the bottom of the interface and introduces scrollbars when they're not needed :(

**Comment by jancborchardt** [comment]
@oparoz it was there before as well, it just got removed somehow. Empty space at the bottom is a very good indicator that the list ends there, and it also doesn’t require people to look all the way to the bottom to see the last files.

@owncloud/designers please review.

**Comment by oparoz** [comment]
@jancborchardt - But isn't it what the summary box is for? It marks the end of the list.

**Comment by jancborchardt** [comment]
It’s 300 to also make space for the normal height of the share dropdown. Otherwise it’s like we wanted to make space but didn’t do it right.

**Comment by oparoz** [comment]
Ah, yes... :D 

I've used a 100px for https://github.com/owncloud/core/pull/15817

**Comment by MorrisJobke** [comment]
:+1: works

**Pull request merged**
