### PR TITLE
[Stable9.1] Lower the priority from error to debug

### PR DESCRIPTION
**Pull request by sharidas**
Lowering the priority of the messages from
error to debug.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

This change reduces the priority of the messages of trashbin from error to debug.

## Related Issue

The issue which this change tries to solve is https://github.com/owncloud/enterprise/issues/1557

## Motivation and Context

It would be annoying to see repeated messages for the admin. Hence reducing the priority.

## How Has This Been Tested?

[x] Tested on 8.2.11. The error log message comes in the log file without this change. After applying this change the logs disappeared because of priority lowering. When the loglevel is reduced to debugging in the config.php, "trash bin database inconsistent!" log appears again.
[x] Tested on master branch.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
@sharidas please always add a reference in the original PR to all backport PRs, else it is difficult to track and find what belongs together

**Comment by sharidas** [comment]
@PVince81 Sure.

Backport of https://github.com/owncloud/core/pull/27826

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
Please rebase to restart CI

**Comment by sharidas** [comment]
@PVince81 Did a rebase. But jenkins failed again :(

**Pull request merged**
