### PR TITLE
fix js tests 

### LINKED ISSUE #39244: JS expiration date test fails depending on time
https://drone.owncloud.com/owncloud/core/32427/9/4
```
Firefox 91.0.0 (Ubuntu 0.0.0) OCA.Sharing.FileList tests loading file list for link shares render only link shares FAILED
	Expected 'in 2 days' to equal 'in a day'.
	@apps/files_sharing/tests/js/sharedfilelistSpec.js:729:50
```

PR #39238 adjusted the expiration date displyed in the webUI. The associated test was also adissted. But it seems to now depend on the time-of-day that the test is run.

Needs sorting out, otherwise we will only be able to get green CI for half the day!

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes #39244 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
Hopefully this actually fixes the problem

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/32446/9/4 passed - so that is something!

**Review by phil-davis — APPROVED** [review]
Let's see. We can merge and will find out for real over the next 24 hours of CI runs.

**Review by JammingBen — APPROVED** [review]

**Comment by phil-davis** [comment]
Looking good - JS tests and caldav-carddav tests have all passed :rocket:

**Pull request merged**
