### PR TITLE
Fix PHPDoc of public interface ILockingProvider

### PR DESCRIPTION
**Pull request by MorrisJobke**
Easy one ;) Found while reviewing.

cc @nickvergessen @LukasReschke @rullzer @Xenopathic @icewind1991

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
