### PR TITLE
link to file_versioning.rst

### PR DESCRIPTION
**Pull request by carlaschroder**
which describes files_versions and config.php settings
backports to 8.2
Please review @MorrisJobke

### CODE REVIEW

**Comment by LukasReschke** [comment]
👍

**Comment by rullzer** [comment]
I get why. But this looks very weird to admins that just read config.sample.php...

**Comment by carlaschroder** [comment]
Just give it a thumbs up, @rullzer

**Comment by rullzer** [comment]
Ok ok... :+1:

**Comment by carlaschroder** [comment]
thanks @rullzer :)

**Pull request merged**
