### PR TITLE
[tests-only] low level TUS tests for uploading chunks

### PR DESCRIPTION
**Pull request by individual-it**
## Description
low level tests of uploading chunks with the TUS protocol

## Related Issue
part of https://github.com/owncloud/product/issues/153

## How Has This Been Tested?
https://github.com/owncloud/ocis/pull/1004
https://github.com/cs3org/reva/pull/1355

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
LGTM
If you get fancy, you could also have a scenario that uploads some data, e.g. "1234567890" with offset 0, then tries to upload to to some more data to somewhere starting in the middle, e.g. "more text" to offset 5.

And also, after uploading "1234567890" then try to upload more data somewhere past there - e.g. to offset 42...

From looking at the spec, IMO the pieces of the file have to be sent in ascending byte order. The TUS protocol does not support sending "random" bits and pieces of the file in "random" order.

**Comment by individual-it** [comment]
tests fail on cs3org/reva and ocis, strange - need a closer look

**Comment by individual-it** [comment]
the issue was, that there is not always a location header https://github.com/owncloud/core/pull/38184/files#diff-5e43d120499cc7c65899d36bbe80efd785e4d9323ea0c82519b08b8281bc9b49R71-R74

**Comment by individual-it** [comment]
tests in owncloud/ocis#1004 pass, those who still fail there, should pass after owncloud/ocis#1004

**Pull request merged**
