### PR TITLE
revert logic to expose free_space, but keep availableStorage config

### LINKED ISSUE #40665: [QA] public links do not work with files_primary_s3
Seen with core 10.12.0-rc.2

* Install server with files_primary_s3
* Create a public link. (file drop, read/write, read only does not matter.)
* paste the public link into a private browser window.
* An error occurs:
grafik

The log says:
```
{
  "reqId": "ZAJ-mnI5zr-f5hMlA2iXnQAAAAg",
  "level": 3,
  "time": "2023-03-03T23:15:38+00:00",
  "remoteAddr": "46.114.208.108",
  "user": "--",
  "app": "index",
  "method": "GET",
  "url": "/s/KuoxwuxY0uiyBkh",
  "message": "Exception: {
\"Exception\":\"Error\",
\"Message\":\"Call to a member function getFileInfo() on null\",
\"Code\":0,
\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/ObjectStore\\/ObjectStoreStorage.php(438): OC\\\\Files\\\\Filesystem::getFileInfo()\\n
#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/ObjectStore\\/ObjectStoreStorage.php(454): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->getTotalUsedStorage()\\n
#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(335): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->free_space()\\n
#3 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Availability.php(350): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->free_space()\\n
#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(335): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->free_space()\\n
#5 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(335): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->free_space()\\n
#6 \\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(335): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->free_space()\\n
#7 \\/var\\/www\\/owncloud\\/apps\\/files_sharing\\/lib\\/Controllers\\/ShareController.php(353): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->free_space()\\n
#8 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(169): OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController->showShare()\\n
#9 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n
#10 \\/var\\/www\\/owncloud\\/lib\\/private\\/AppFramework\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n
#11 \\/var\\/www\\/owncloud\\/lib\\/public\\/AppFramework\\/App.php(131): OC\\\\AppFramework\\\\App::main()\\n
#12 \\/var\\/www\\/owncloud\\/core\\/routes.php(130): OCP\\\\AppFramework\\\\App->dispatch()\\n
#13 \\/var\\/www\\/owncloud\\/lib\\/private\\/Route\\/Router.php(344): OC\\\\Route\\\\Router::{closure}(*** sensitive parameters replaced ***)\\n
#14 \\/var\\/www\\/owncloud\\/lib\\/base.php(913): OC\\\\Route\\\\Router->match()\\n
#15 \\/var\\/www\\/owncloud\\/index.php(54): OC::handleRequest()\\n
#16 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/private\\/Files\\/Filesystem.php\",
\"Line\":1030}"
}
```

This only happens, when the public link is created in the primary_s3 storage. E.g. an SFTP external storage is not affected.

Expected behaviour: 
* public links should also work with files_primary_s3

This appears to be a regression. It is not reproducable with 10.11.0 and files_primary_s3

### PR DESCRIPTION
**Pull request by mrow4a**
- fixes https://github.com/owncloud/core/issues/40665
- related https://github.com/owncloud/enterprise/issues/5006 , https://github.com/owncloud/core/pull/40389
- needed for https://github.com/owncloud/metrics/pull/159

The issue here is that originally when doing https://github.com/owncloud/core/pull/40389 I somehow mixed the storage_id for S3 bucket with the user urns storage_id's . So when matching with filecache I though it represents that one. 

However I was wrong, and used the wrong storage .. also the correct filecache entry for the entire bucket is always showing 0 size. 

In this PR, I just expose the config entry for availableStorage, so that apps could use it. Please note that this PR reverts logic to expose this on storage level, so all "quota" calculations wont work. If we want to make it work on storage level, something like background job that calculates this size would need to be done. However, metrics app does not require that complexity and it can simply just use that parameters as in https://github.com/owncloud/metrics/pull/159

### CODE REVIEW

**Comment by phil-davis** [comment]
PR #40670 has this code with the conflict resolved.

**Comment by phil-davis** [comment]
"Piotr Mrowczynski seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA"

It looks like the name used in the commit is missing the "accent" characters in "Piotr Mrówczyński"

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiSharingNotificationsToRoot-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38051/91

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUILogin-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/38051/125

**Comment by phil-davis** [comment]
Note: this PR now has 20 commits - the switch back to `master` recorded by GitHub 17 hours ago did not do what we want.
New PR is coming...

**Comment by phil-davis** [comment]
This code has been merged to `release-10.12.0` in PR #40674 

IMO this PR to master can be closed.

**Pull request closed without merging**
