### PR TITLE
Enforce string as passed type

### PR DESCRIPTION
**Pull request by LukasReschke**
@th3fallen @schiesbn The AppFramework supports enforcing the string type, please use the PHPDocs as annotations where sensible. Can prevent bad bugs.

cc @MorrisJobke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Grmpf… Seems like I will also have to commit some other PHPDoc problems :anguished:

**Comment by LukasReschke** [comment]
@owncloud-bot Retest this please.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by schiesbn** [comment]
Thanks for cleaning up the PHPDocs!
:+1:

**Pull request merged**
