### PR TITLE
Use correct variable

### PR DESCRIPTION
**Pull request by butonic**
and add tests for all storages.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@butonic thx- fixes an issue? just asking because nothing is referenced - THX

**Comment by butonic** [comment]
@DeepDiver1975 none that I am aware of ... writing an app that relies on stuff from core. Fixing stuff as I come along it.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 none that I am aware of ... writing an app that relies on stuff from core. Fixing stuff as I come along it.

THX

:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
