### PR TITLE
fix uncaught exception on not permitted file types when setting avata…

### LINKED ISSUE #17232: LDAP - avatar in format other than jpg/png throws exception
Hi,
when using LDAP with OwnCloud lib/private/avatar.php ( https://github.com/owncloud/core/blob/master/lib/private/avatar.php#L104 ) could make instance unusable for some users. If they have avatar in other format than jpg or png - they have 500 internal server error, in logs you just see exception from avatar.php.

Exception:
```javascript
{"Message":"Unknown filetype","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(346): OC_Avatar->set(Object(OCP\\Image))\n#1 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(319): OCA\\user_ldap\\lib\\user\\User->setOwnCloudAvatar()\n#2 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/user\/user.php(134): OCA\\user_ldap\\lib\\user\\User->updateAvatar()\n#3 \/var\/www\/html\/owncloud\/apps\/user_ldap\/user_ldap.php(213): OCA\\user_ldap\\lib\\user\\User->update()\n#4 \/var\/www\/html\/owncloud\/lib\/private\/user\/manager.php(113): OCA\\user_ldap\\USER_LDAP->userExists('user')\n#5 \/var\/www\/html\/owncloud\/lib\/private\/user\/manager.php(142): OC\\User\\Manager->get('user')\n#6 \/var\/www\/html\/owncloud\/lib\/private\/user.php(574): OC\\User\\Manager->userExists('user')\n#7 \/var\/www\/html\/owncloud\/lib\/private\/user.php(334): OC_User::userExists('user')\n#8 \/var\/www\/html\/owncloud\/lib\/base.php(774): OC_User::isLoggedIn()\n#9 \/var\/www\/html\/owncloud\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/avatar.php","Line":66} 
```

Steps to reproduce:
1. Use LDAP
2. Create user in LDAP with f.e. gif avatar.
3. Try to login to OwnCloud

or
1. Use LDAP
2. Create user in LDAP
3. Login to OwnCloud with that user
4. Set in LDAP gif avatar
5. Every link user opens - will give 500 Internal server error.

### PR DESCRIPTION
**Pull request by blizzz**
…r, fixes #17232 
Includes the plain fix, not the integration tests (not backportable).

@MorrisJobke @SergioBertolinSG @hostingnuggets here is the backport to OC 7 if you like to test and review.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by SergioBertolinSG** [comment]
Same problem like found in stable8, pictures are not shown, jpg or png. Gif doesn't return 500.

**Comment by DeepDiver1975** [comment]
not fixed -> 7.0.10

**Comment by blizzz** [comment]
@SergioBertolinSG also  here, how did you test?

**Comment by SergioBertolinSG** [comment]
@blizzz just tested this again, in chrome there are problems when uploading the second image. It is not shown. 
Uploading a gif image it is shown and later it warns the user saying unknown format. Not very user friendly.
In firefox it is working better but the gif file is also shown.

**Comment by blizzz** [comment]
@SergioBertolinSG  it's not about uploading. It's about fetching the avatar from LDAP.

**Comment by SergioBertolinSG** [comment]
OK, using LDAP users with avatars, they are not shown at all.

**Comment by blizzz** [comment]
Which brings us to your test steps again :)

**Comment by SergioBertolinSG** [comment]
Working fine in stable7, but besides waiting for 24h it needs to wait for the UserExist cached to expire.
Perhaps something to be documented as a little advise in oc 7 @carlaschroder 
(LDAP users with avatars should wait 24h after first login to see their avatars)

**Comment by carlaschroder** [comment]
Note added to stable7 manuals
https://github.com/owncloud/documentation-enterp
rise/commit/7e0e14f3f0573fb240ef64cb87ac5f435de8b227
https://github.com/owncloud/documentation/commit/985f389879e31c01b1de11fcba185a6572d71b88

**Pull request merged**
