### PR TITLE
show txt preview when file contains text

### LINKED ISSUE #16556: Preview text icon is shown only when it is written more than six characters in the file.
### Steps to reproduce
1. Create a new file and edit it with less than 6 characters

### Expected behaviour
If the file has text written, the 'preview icon' should be shown.

### Actual behaviour
The standard icon is shown unless it has more than five characters

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Firefox

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #16556 

please review @jancborchardt @oparoz

### CODE REVIEW

**Comment by jancborchardt** [comment]
@davitol as well since he opened the issue.

**Comment by PVince81** [comment]
Works :+1: (tested with :one: byte file)

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by davitol** [comment]
:+1:

**Pull request merged**
