### PR TITLE
Make enable_avatars setting more robust

### LINKED ISSUE #21949: Setting enable_avatar to false with occ causes some bugs
Hello,
I'm Installing owncloud 8.2.2 on CentOS 6.6 with php7

When I set enable_avatar to false through occ, with this command :

    sudo -u apache php ${oc_dir}/occ config:system:set enable_avatars --value="false"

* First it just disable the avatar in the "Personnal" page but not the tiny picture beside the display name (photos of LDAP users are automatically used when I plug my LDAP on owncloud).
* Then when I go on the user's admin page, loading never ends. Even if I do not enable LDAP user backend app and admin is the only user.

### PR DESCRIPTION
**Pull request by MorrisJobke**
- handles the setting in the same way everywhere
- fixes #21949 

@nickvergessen @rullzer @LukasReschke @pookay Please review

@karlitschek We maybe want to backport this ;)

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport. :+1:

**Comment by nickvergessen** [comment]
I don't think this is needed.

**Comment by MorrisJobke** [comment]
> I don't think this is needed.

Be more precise please.

Set it to:

* `true` -> it is always evaluated as `true`
* `'everyString'` -> it is sometimes evaluated as `true` (where no explicit check is done - `if($config)`) and sometimes evaluated as `false` where the check is specified (`if($config === true)`
* `false` -> is is always evaluated as `false`


This change unified the overall behavior to: `'randomString'` means `false`

**Comment by DeepDiver1975** [comment]
We have this 'issue' with multiple config settings.

**Comment by MorrisJobke** [comment]
> We have this 'issue' with multiple config settings.

That's because we have no proper options validation/casting and unified defaults management.

**Comment by nickvergessen** [comment]
Well we could do casting based on the provided default value...

Anyway this is at least nothign we should backport, because it is a behaviour change

**Comment by MorrisJobke** [comment]
> Well we could do casting based on the provided default value...

-.- Really? This could break everything.

**Comment by nickvergessen** [comment]
Well with null being an exception, but everytime we set a default its of the type we want to have, anyway your patch here is changing behaviour as well, because '1' previously was enabled, and now it's disabled...
From my pov we shouldn't touch something like this until we have a final outcome about casting in general...

**Comment by MorrisJobke** [comment]
> anyway your patch here is changing behaviour as well, because '1' previously was enabled, and now it's disabled...

Not really. Because it was enabled in some code paths and disabled in other code paths, which actually cause the issue this is fixing. The issue was, that it tried to load avatars(setting was evaluated to true) even if the markup to put them in is not present (setting was evaluated to false). This only aligns all usages of the setting to evaluate in the same way.

**Comment by DeepDiver1975** [comment]
TBH: the real issue is that the value in the config file was simply wrong - which was caused by the occ command.

**Comment by MorrisJobke** [comment]
> TBH: the real issue is that the value in the config file was simply wrong - which was caused by the occ command.

I would nevertheless make all checks be proof against this. Either all check for true or all use the plain `if($value)` format. But definitely not the mixed stuff, because PHP is sometimes hard to tame and we should avoid this. At least in this case where the actual issue is really hard to notice easy. (compared to a typo in the config.php or a plain wrong DB password, etc)

**Comment by nickvergessen** [comment]
We can also check the type of all known values and display warnings on the admin page :speak_no_evil:

**Comment by DeepDiver1975** [comment]
Seriously - let's just assume users editing the config file are capable to read.

As said above: the original issue was raised because of the config command was not capable to set the boolean value properly

**Comment by MorrisJobke** [comment]
Could we get back to topic and simply review this change. Even if it is stupid - it doesn't hurt to merge it and it fixes a problem that exists in the real world. The actual problem here is that PHP is dynamically typed and we as developers failed to use a value in the same way everywhere. So this is a pragmatic approach to fix it and it doesn't make anything more complex.

**Comment by PVince81** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
backport is in https://github.com/owncloud/core/pull/22047

**Pull request merged**
