### PR TITLE
[tests-only] update image preview fixture

### LINKED ISSUE #1213: [QA] Nightly failure in file preview
```feature
Scenario: it should update the preview content if the file content is updated (content with UTF chars)         # /var/www/owncloud/testrunner/tests/acceptance/features/apiWebdavPreviews/previews.feature:211
    Given user "Alice" has uploaded file "filesForUpload/lorem.txt" to "/lorem.txt"                              # FeatureContext::userHasUploadedAFileTo()
    And user "Alice" has uploaded file with content "सिमसिमे पानी" to "/lorem.txt"                               # FeatureContext::userHasUploadedAFileWithContentTo()
    When user "Alice" downloads the preview of "/lorem.txt" with width "32" and height "32" using the WebDAV API # FeatureContext::downloadPreviewOfFiles()
    Then the HTTP status code should be "200"                                                                    # FeatureContext::thenTheHTTPStatusCodeShouldBe()
    And the downloaded image should be "32" pixels wide and "32" pixels high                                     # FeatureContext::imageDimensionsShouldBe()
    And the downloaded preview content should match with "सिमसिमे-पानी.png" fixtures preview content             # FeatureContext::theDownloadedPreviewContentShouldMatchWithFixturesPreviewContentFor()
      Failed asserting that two strings are equal.
      --- Expected
      +++ Actual
      @@ @@
      -Binary String: 0x89504e470d0a1a0a0000000d4948445200000020000000200806000000737a7af4000000097048597300000ec400000ec401952b0e1b0000013e494441545885edd33d8bc24010c6f1ffeea589125b5fda80626c14b110f19b591ce43ba4b5b3b109d8044b6b4bb133a08582481025820477af386ceea5081c78c53ed53003c38f81115a6bcd0b239f85528ae9744a14457c35cd6633c6e3318bc5e2c7254a29269309c7e33137408461a81f8f07d7eb95ed764bb55a65bfdfd3ebf5b85c2e28a558afd7341a0dc23024080256ab15699a72bbdd9052522814582e975896c56834ca7781cd66c3e974c2b66deaf53abbdd8e62b1489aa6c4714c9665743a1de238a6dd6e532e97399fcf74bb5d1cc721cb329224c1755d9acd66ee0bbcf9beffeeba2e499220a564381ca2b5a6d56a51abd5b8dfef00f4fb7d2ccbc2f33c2a950af3f91cdbb629954a0c06030e8703009ee7e50208fd198410df86bff5ff32e2df7c810118800118800118800118800118800118c0abf201ae12860252f9577a0000000049454e44ae426082
      +Binary String: 0x89504e470d0a1a0a0000000d4948445200000020000000200806000000737a7af4000000097048597300000ec400000ec401952b0e1b00000149494441545885edd3c1ca415110c0f1ffb98ea28ebb9143916279bb0b6283d47d0a0fe119286fe31dbc010b525cc95658285244d2f956be8dbec5adaf6cce2c67a699df624618630c5f8c58100483300c793c1e68ad7f0b93c984f97ccee974229fcfb3dfef592e97140a858f21c61886c3215a6b94529100a2d7eb997abdce6c36a3582c9248240008c39056abc5743ac5755dd2e934ebf59a6eb7cb62b1e07abd72bbdd701c07a514e3f1182925fd7e3f12c0a9542a6cb75b32990cf1789cd56ac56eb7a35aad72bfdf01504ab1d96c905292cd66399fcfd46a3552a914afd78be3f148b95cc6f3bc48cb01629d4e67e0fb3ea55289cbe542bbdde67d16beefa3b5e6f97cd268349052e2791eb95c8ed168443299c4755d9acd2687c301203242bc8fd0188310e2a3e1affc7f85f8f61738df5c6e011660011660011660011660011660011600f003f3e175dc6151c1c80000000049454e44ae426082
```
Build: https://drone.owncloud.com/owncloud/activity/3960/57/16

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
Updated the preview image fixture

## Related Issue
- Fixes https://github.com/owncloud/activity/issues/1213

## How Has This Been Tested?
- test environment: :raised_back_of_hand: 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
@saw-jan do you know what changed to cause a slightly different preview content?

**Comment by saw-jan** [comment]
> do you know what changed to cause a slightly different preview content?

no idea, the core has no commit changes from last week.  the current generated preview has few more strings

**Review by phil-davis — APPROVED** [review]
This fixture is used in core acceptance test feature file
https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdavPreviews/previews.feature

There hasn't been any core CI used for a few days. I suppose the test would have been failing in core also.

Maybe some underlying library in Ubuntu+PHP got updated and the preview content has changed a little bit (been improved?)

Anyway, CI passes and we can visually see that the new preview image looks OK.

**Comment by phil-davis** [comment]
Backport to `release-10.15.0` branch is PR #41296

**Pull request merged**
