### PR TITLE
remove composer_dev_deps from acceptance test runs

### PR DESCRIPTION
**Pull request by individual-it**
## Description
I don't think we need that for acceptance tests because the alias only refers to php_unit

## How Has This Been Tested?
:robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
Let's see what CI says.
```
$(composer_dev_deps): $(COMPOSER_BIN) composer.json composer.lock
	php $(COMPOSER_BIN) install --dev
```
I suspect that without the dependency, nothing will do ``composer install`` and there might not be any Behat...

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Review by phil-davis — APPROVED** [review]
CI passes

**Comment by phil-davis** [comment]
@individual-it please backport

**Comment by individual-it** [comment]
I think it works  because we run `make all` or just `make` before running the tests and that gives us all debs. So if we want to be able to run the tests on a clean clone that might fail.

**Comment by DeepDiver1975** [comment]
the idea of make is each target pulls in the necessary depending steps. If I clone the repo the idea is that a make test-acceptance-api executes all necessary steps. So please revert. THX

**Comment by phil-davis** [comment]
Reverted in #33399 
Backport request removed!

**Pull request merged**
