### PR TITLE
Move user management ui to its own app

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
The user managment ui is moved out of core. Core should more and more become a pure api server. This is one of many steps.

app is here: https://github.com/owncloud/user_management

## ToDos
- [x] remove all currently used controllers from settings -  move them as well if 
- [x] move the app to it's own repo
- [x] move acceptance tests ...

## How Has This Been Tested?
- manually

## Screenshots (if appropriate):
bildschirmfoto von 2018-03-02 12-22-13

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
UI tests will need sorting out also.

``upload`` suite does a UI-based upload by a user that has insufficient quota, checking that the UI gives some expected error... Somewhat stupidly, it looks like it sets the quota of the user via the UI (drives the Users page). That can easily be modified to setup the user quota via the API.

``manageUsersGroups`` suite - needs to be moved to the new app

``manageQuota suite - needs to be moved to the new app

They are the UI tests that drive the Users page, which of course is gone in ``core`` with this PR.

**Comment by DeepDiver1975** [comment]
> manageUsersGroups suite - needs to be moved to the new app
> 
> manageQuota suite - needs to be moved to the new app
> 
> They are the UI tests that drive the Users page, which of course is gone in core with this PR.

This was easy - I just mived them over ....

**Comment by DeepDiver1975** [comment]
> upload suite does a UI-based upload by a user that has insufficient quota, checking that the UI gives some expected error... Somewhat stupidly, it looks like it sets the quota of the user via the UI (drives the Users page). That can easily be modified to setup the user quota via the API.

Can you use the provisioning api for this?

**Comment by phil-davis** [comment]
> Can you use the provisioning api for this?

Yes, and it will faster/better. I will look...

**Comment by DeepDiver1975** [comment]
> Yes, and it will faster/better. I will look...

let me have a look as well ....

**Comment by phil-davis** [comment]
PR #30709 has some code I did. Locally I get 401 "unauthorized" from the quota-setting step. I couldn't see immediately what silly thing was wrong in sending the ``admin/admin`` authentication.

**Comment by DeepDiver1975** [comment]
> PR #30709 has some code I did. Locally I get 401 "unauthorized" from the quota-setting step. I couldn't see immediately what silly thing was wrong in sending the admin/admin authentication.

let me have a look ....

**Comment by phil-davis** [comment]
#30709 is merged. A rebase here should pick that up, and help this pass.

**Comment by DeepDiver1975** [comment]
> #30709 is merged. A rebase here should pick that up, and help this pass.

rebase done ... let's see ....

**Review by PVince81 — APPROVED** [review]
:+1: if tests pass

**Comment by PVince81** [comment]
conflicts and codecov issue

**Comment by DeepDiver1975** [comment]
> conflicts and codecov issue

conflicts resolved

**Comment by phil-davis** [comment]
@DeepDiver1975 sorry for continuously refactoring UI test files/code! I might be finished annoying other PRs "real soon now".

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 sorry for continuously refactoring UI test files/code! I might be finished annoying other PRs "real soon now".

no problem

**Comment by phil-davis** [comment]
@DeepDiver1975 I guess this (and other future refactorings like it) will not be backported?

Just confirming, because that will leave more UI tests in ``stable10`` (along with the UI code) and we will just have to take care to manage those kind of differences.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I guess this (and other future refactorings like it) will not be backported?

at least not right away ... for now master only

**Pull request merged**
