### PR TITLE
Create the contact birthday calendar right away as soon as the comman…

### LINKED ISSUE #23203: Missing contacts_birthday calendar after upgrade to 9.0
### Steps to reproduce
1. Have users using and syncing calendars with devices
2. Upgrade from 8.2.3 to 9.0
3. A users DavDroid tries to sync contacts_birthday

### Expected behaviour
Either it exists and succeeds or it does not exist and no sync is attempted

### Actual behaviour
ownCloud returns 404, error message on every sync on android side

There were no issues before. In oc_calendars such a calendar is not listed for the user in question. In the old calendars table there were none at all. ``./occ dav:sync-birthday-calendar $USER`` does not have any effect.

Back in 8.2.x days, the calendar was synced successfully. Possibly a migration issue? Or it was not migrated, because it was empty – is this possible?

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** update from 8.2.3

**Where did you install ownCloud from:** tarball

**Signing status (ownCloud 9.0 and above):** awesome

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Sync App:** DavDroid

**Operating system:** Android 4.4.2

#### Web server error log
```
90.234.23.123 - USERNAME [13/Mar/2016:22:27:47 +0100] "PROPFIND /owncloud/remote.php/caldav/calendars/USERNAME/contact_birthdays/ HTTP/1.1" 404 5813 "-" "DAVdroid/0.9.1.3 (2016/01/02; dav4android) Android/4.4.2"
```

#### ownCloud log (data/owncloud.log)
```
(nothing related)
```

@DeepDiver1975

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…d is executed once - fixes #23203 
@karlitschek backport should be considered as well - THX

### CODE REVIEW

**Comment by karlitschek** [comment]
Backport is fine if you want to.

**Comment by DeepDiver1975** [comment]
> Backport is fine if you want to.

thx

**Comment by blizzz** [comment]
Applied this on my 9.0 instance, fixes the issue :+1:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
