### PR TITLE
Make repairmimetypes compatible with case sensitive SQL backends

### PR DESCRIPTION
**Pull request by oparoz**
Change for #14132
Just a word of warning, ILIKE seems to be a Doctrine only clause. The statements are thus not portable.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Can we have a unit test covering this case? THX

**Comment by Raydiation** [comment]
@PVince81 @DeepDiver1975 @LukasReschke @MorrisJobke

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by LukasReschke** [comment]
> Just a word of warning, ILIKE seems to be a Doctrine only clause. The statements are thus not portable.

Actually it's magic we invented ourselves with https://github.com/owncloud/core/pull/10958 :see_no_evil:

**Comment by oparoz** [comment]
Hehe...well, as long as it's documented somewhere, it shouldn't be a problem.

**Comment by oparoz** [comment]
@DeepDiver1975 - Let me know if what I added suffices as tests.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 - Let me know if what I added suffices as tests.

:+1: THX

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
