### PR TITLE
Unit test `DeleteHelper` and setup CI for it

### PR DESCRIPTION
**Pull request by skshetry**
## Description

This still requires configuration changes to make it better.
- [x] Change makefile
- [x] Change drone setup

## Related Issue

- Part of #32527

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
@skshetry Latest ``master`` checks for code style in ``TestHelpers`` so please fix the things reported: https://drone.owncloud.com/owncloud/core/13472/91

**Comment by skshetry** [comment]
@phil-davis Please review again

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@skshetry this is merged, so you can make a backport now.
And rebase the other PR to master...

**Comment by phil-davis** [comment]
@skshetry backport needed - ping.

**Comment by skshetry** [comment]
Backport for `stable10` in #33876

**Comment by skshetry** [comment]
Backport for `stable10` in #33876

**Pull request merged**
