### PR TITLE
Remove swift primary and secondary storage support

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Description
Swift primary storage was deprecated in 10.0.9 - we are now fully killing it - primary as well as secondary.
https://doc.owncloud.com/server/10.2/admin_manual/release_notes.html#swift-objectstore-deprecation

## Related Issue
https://github.com/owncloud/core/issues/27049

## How Has This Been Tested?
- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by patrickjahns** [comment]
@DeepDiver1975 
Drone has some swift jobs - also drop the from `.drone.yml` that should get us green then

**Comment by patrickjahns** [comment]
Example https://github.com/owncloud/core/blob/master/.drone.yml#L807-L813

**Review by patrickjahns — APPROVED** [review]
Code refactoring LGTM

**Review by pmaier1 — APPROVED** [review]
As discussed. This needs a mention in the release notes!

**Comment by DeepDiver1975** [comment]
drone is only failing because of #35970 -> merge

**Pull request merged**
