### PR TITLE
[stable9] Properly handle return values of OC_App::getAppInfo()

### LINKED ISSUE #23668: Trying to activate app on production stable9, doesn’t work (dependency analyzer)
It seems to be enabled, but doesn’t show in the app switcher. (News app in this case) owncloud.log:

```json


[
  {
    "reqId": "G4dZm8Xq\/Ayl5vyBzPgc",
    "remoteAddr": "93.202.88.105",
    "app": "PHP",
    "message": "Argument 1 passed to OC\\App\\DependencyAnalyzer::analyze() must be of the type array, null given, called in \/lib\/private\/app.php on line 1100 and defined at \/lib\/private\/app\/dependencyanalyzer.php#52",
    "level": 3,
    "time": "2016-03-30T16:41:44+00:00",
    "method": "POST",
    "url": "\/index.php\/settings\/ajax\/enableapp.php",
    "user": "jan"
  },
  {
    "reqId": "G4dZm8Xq\/Ayl5vyBzPgc",
    "remoteAddr": "93.202.88.105",
    "app": "PHP",
    "message": "Argument 2 passed to OC\\App\\DependencyAnalyzer::analyzeOC() must be of the type array, null given, called in \/lib\/private\/app\/dependencyanalyzer.php on line 66 and defined at \/lib\/private\/app\/dependencyanalyzer.php#280",
    "level": 3,
    "time": "2016-03-30T16:41:44+00:00",
    "method": "POST",
    "url": "\/index.php\/settings\/ajax\/enableapp.php",
    "user": "jan"
  }
]


```

@DeepDiver1975 @BernhardPosselt any idea?

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #23668

cc @DeepDiver1975 @jancborchardt @nickvergessen @LukasReschke 

Backport of #23676 
Approval in https://github.com/owncloud/core/pull/23676#issuecomment-203805609

### CODE REVIEW

**Comment by jancborchardt** [comment]
Now on activation I get a red error message in the app management:
> App "" cannot be installed because appinfo file cannot be read.

cc @BernhardPosselt

**Comment by BernhardPosselt** [comment]
@jancborchardt did you check the open_basedir issue yet?

**Comment by jancborchardt** [comment]
@BernhardPosselt I don’t really know what you mean by that, and didn’t find `open_basedir` in the code samples you linked in the issue. Can you give me instructions how to test, or prepare a pull request I can test?

**Comment by BernhardPosselt** [comment]
https://github.com/owncloud/core/issues/20128 which was fixed by the PR that needs to be fixed in here ;)

Other than that I don't know why it happens

**Comment by jancborchardt** [comment]
Well, this comment still doesn’t really help in what I can try to review it.

@MorrisJobke can you update the PR? I’m still having problems as said.

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you update the PR? I’m still having problems as said.

At least it doesn't crash with a bad message now. We now need to find the reason for the empty app path.

**Comment by jancborchardt** [comment]
Any way I can help finding the issue?

**Comment by LukasReschke** [comment]
:+1:

**Comment by jancborchardt** [comment]
Yaeh, so :+1: from me for this too. @MorrisJobke rebase please.

**Comment by jancborchardt** [comment]
@MorrisJobke you working on the remaining issue? Any way I can help?

**Pull request merged**
