### PR TITLE
Update expiration date on link sharing

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@SergioBertolinSG @cmonteroluque @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
and @rullzer @schiesbn

- [ ] BUG: don't call "showExpirationDate" if the expiration is null/empty, else it will activate the checkbox but leave the field empty

**Comment by PVince81** [comment]
- [x] TEST: expiration date stays after editing password
- [x] TEST: expiration date stays when "set default exp date" on admin page is checked
- [x] TEST: expiration date stays when "set default exp date" + enforced on admin page is checked

**Comment by PVince81** [comment]
- [ ] BUG: when password is enforced in the admin page, the exp date from the server isn't being set to the field (maybe it's a slightly different code path...)

**Comment by PVince81** [comment]
- [ ] BUG: if "expiration" is null in the server response and the field contains a value already, it should probably be reset to empty

**Comment by DeepDiver1975** [comment]
> BUG: don't call "showExpirationDate" if the expiration is null/empty, else it will activate the checkbox but leave the field empty

fixed @PVince81

**Comment by PVince81** [comment]
Works now :+1:

**Comment by rullzer** [comment]
Yes works :+1:

**Pull request merged**
