### PR TITLE
Improve IE11 compatibility

### PR DESCRIPTION
**Pull request by lordelix**
## Description

Added Flexbox vendor prefix where needed

## How Has This Been Tested?

Visual test in IE11

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@felixheidecke please backport to stable10

**Comment by PVince81** [comment]
@felixheidecke missing backport. Maybe this fixes the top left menu ?

**Comment by DeepDiver1975** [comment]
fix is already in stable10 - https://github.com/owncloud/core/commit/5b4c46f2e8e1b654094e357c7e161cd257033ffd

removing backport label

**Pull request merged**
