### PR TITLE
The full name has to be tested if it's a dir

### LINKED ISSUE #19854: 8.2RC1 Files - Downloading entire subdirectories produces 0-byte .tar and .zip files
### Steps to reproduce
1. Create a top level directory and a subdirectory: `Top Level Directory/Second Level Directory (Parenthesis)`
2. Upload a file to the subdirectory.
3. Browse the top level directory and select "Download" for the subdirectory, or browse to the subdirectory, select all files, then download.

### Expected behavior
Based on #19318 - OC should generate a .tar or .zip file correctly named after the subdirectory and with the subdirectory contents: `Second Level Directory (Parenthesis).tar`

### Actual behavior
OC generates a 0-byte file correctly named after the subdirectory with no extension under both Mac OS X (Safari 9) and Windows (Chrome): `Second Level Directory (Parenthesis)`

### Additional info
Navigating to the subdirectory and selecting multiple (but not all) files results in a valid .tar or .zip file with the selected files, but poorly named with URL encoded characters: 

Mac OS X: `Second%20Level%20Directory%20%28Parenthesis%29.tar`
Windows: `Second Level Directory %28Parenthesis%29.zip`

This affects files either stored within the OC data directory or files accessed via local external storage. A fresh install of OC 8.1 does not have this issue, but I'm looking to switch to tarstreamer due to Mac OS X's inability to natively decompress the .zip files that OC 8.1 generates.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
nginx/1.9.4

**Database:**
mysql  Ver 15.1 Distrib 10.0.21-MariaDB

**PHP version:**
PHP 5.5.9-1ubuntu4.13

**ownCloud version:** (see ownCloud admin page)
8.2 RC1 (testing)

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
```
Enabled:
  - files: 1.1.11
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.6.3
  - files_texteditor: 2.0
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - notifications: 0.1.0
  - provisioning_api: 0.2
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - activity
  - encryption
  - external
  - files_external
  - gallery
  - user_external
  - user_ldap
```

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "foo",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "foo.example.com"
        ],
        "datadirectory": "\/var\/www\/foo.example.com\/owncloud82-data",
        "overwrite.cli.url": "https:\/\/foo.example.com\/cloud",
        "dbtype": "mysql",
        "version": "8.2.0.9",
        "dbname": "owncloud82rc1",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logtimezone": "UTC",
        "installed": true,
    }
}
```

**Are you using external storage, if yes which one:**
Local

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #19854

@karlitschek @cmonteroluque  this is a regression and requires immediate backport to 8.2 - THX

Here is the backport - https://github.com/owncloud/core/pull/19860

@MorrisJobke @PVince81 @icewind1991 please review and test - THX

### CODE REVIEW

**Comment by PVince81** [comment]
Tested with zip download as per the original steps, works :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by nickvergessen** [comment]
Will add a smashbox case for the "full subfolder" case

**Comment by nickvergessen** [comment]
Smashbox cse for this https://github.com/owncloud/smashbox/issues/130

**Comment by karlitschek** [comment]
argh. Not again. Please backport. @cmonteroluque I suggest to do new packages.

**Comment by cmonteroluque** [comment]
I will make new packages. We need this merged...

**Comment by DeepDiver1975** [comment]
> argh. Not again. Please backport. @cmonteroluque I suggest to do new packages.
> @LukasReschke

Fix is in the final tar ball

**Pull request merged**
