### PR TITLE
Small perf tweak in strlen loop

### PR DESCRIPTION
**Pull request by PVince81**
See http://stackoverflow.com/questions/6955913/isset-vs-strlen-a-fast-clear-string-length-calculation

@jknockaert @th3fallen @schiesbn @DeepDiver1975

### CODE REVIEW

**Comment by PVince81** [comment]
also @nickvergessen @LukasReschke @MorrisJobke

**Comment by MorrisJobke** [comment]
@PVince81 Is there a use case where this is heavily used? Or is this just a random optimization?

**Comment by nickvergessen** [comment]
Should help a bit, but the line bellow still calls strlen() :(

**Comment by PVince81** [comment]
Well, at least it doesn't call it twice.

This is the loop in the encryption app that encrypts block by block. So could help for bigger files.

**Comment by PVince81** [comment]
Usually the blocks have a specific size, so another possible optimization for the second strlen would be to first see if it's a full block with `if (isset($block, 6126))` and only if it is not, then call strlen. This would then only call strlen on the last block.

**Comment by nickvergessen** [comment]
sounds good

**Comment by jknockaert** [comment]
Sorry, I can't fully assess the impact of this change.

**Comment by jknockaert** [comment]
@PVince81 Am I correct to understand that you substitute a test checking if the first character/byte is set for a test on the length of the string? That should work here. Would such a test also improve performance at L429 (`$this->cache === ''`)?

**Comment by PVince81** [comment]
Not sure. I just remember that we found out that "strlen" is slow compared to "isset".

It is not too bad, we can also put this in for 8.2 as it's not critical.

**Comment by PVince81** [comment]
Yes, you are right that we substitute the test for length and do it with a "isset" hack.

**Comment by nickvergessen** [comment]
Okay, let's do it one after the other: :+1:

**Comment by jknockaert** [comment]
:+1:

**Comment by bantu** [comment]
Also move `$remainingLength = strlen($data);` into the `if (!($this->readOnly) && ($resultFseek || $positionInFile === $this->size)) {` block, then?

**Comment by jknockaert** [comment]
@bantu You could do that, but performance will improve only marginally. I can think of only two contexts where the if-statement would evaluate to false and a strlen would be avoided by moving it into it: the case where a write is attempt on a file opened in r-mode (that should not happen), or the case where something is written in r+ mode in the middle of an unseekable encrypted stream, which is not supported by the encryption wrapper (and as far as I know r+ mode is currently not used in owncloud).

**Comment by MorrisJobke** [comment]
stable8.1 is created -> merge

**Pull request merged**
