### PR TITLE
Ensure the password is only hashed in case it's changed on the client…

### LINKED ISSUE #19950: changing expiration date of shared link breaks password
Hi.

Since 8.2.0 setting/changing the expiration date for shared links breaks the password for these links, so you can't access them anymore with the correct password.

Expected behaviour: setting/changing the expiration date of a shared link sets/changes it and that's it.

Actual behaviour: changing or setting the expiration date of a shared link breaks the password, i.e. you cannot access the shared link with the correct password because it always reports "wrong password" (even though it's correct).

Strangely, there's one way: when I set a **default, _not enforced_ expiration date for _shared links_ as an admin for _all_ users**. Then when I share a link I **do not touch** the previously set default expiration date (= not change nor disable it). Then it works.
 
But that's hardly a good longterm solution to this problem.

-----------
Operating system: CentOS 6.7
Web server: Apache 2.2.15
PHP version: 5.6.12
ownCloud version: 8.2
Enabled apps:  Activity, Gallery, Mail Template Editor, PDF Viewer, Share Files, Updater, Video Viewer
Are you using external storage, if yes which one: no
Are you using encryption: no
Are you using an external user-backend: no
Browser: Firefox 41.0.x, Safari 9

logs show nothing related to this problem or the time it happened.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… - fixes #19950

@davitol please revalidate - THX

@MorrisJobke @schiesbn @PVince81 @LukasReschke please test and review

@karlitschek @cmonteroluque this is a regression in 8.2 - backport is out of question from my pov - THX

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Oh no - js unit tests are falling apart ..... please someone help out here before I go nuts - THX

**Comment by DeepDiver1975** [comment]
JAY - break all the unit test! :hankey:

**Comment by rullzer** [comment]
Looking at the code it is a wonder this worked properly before... (did it really?) we really should move the webinterface over to the OCS API. Then at least we have only 1 code path to worry about.

I see no way to backport this without a nasty hack. However I propose a slightly different approach (will update PR).

As far as I know this path is only taken from the ajax endpoint. The OCS endpoint really updates the share.

**Comment by rullzer** [comment]
CI seems (happier)... time for bed now.

@PVince81 please check me and @DeepDiver1975 did not break the whole shareitemmodel

**Comment by davitol** [comment]
@DeepDiver1975 :-1: It is not fixed switching 19982.patch and following the steps:

1.- Share a folder by link
2.- Set up a password
3.- Access to the link the password is requested -> works
4.- Set up an expiration date
5.- Access to the link, the password is requested -> not works

**Comment by rullzer** [comment]
@davitol try again please.

**Comment by davitol** [comment]
@rullzer @DeepDiver1975 :+1: WFM

**Comment by DeepDiver1975** [comment]
If we only would have the ocs sharing api tests ready ....

**Comment by PVince81** [comment]
>@PVince81 please check me and @DeepDiver1975 did not break the whole shareitemmodel

Looks fine.

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by DeepDiver1975** [comment]
THX

**Comment by MorrisJobke** [comment]
@DeepDiver1975 Can you please create the backport PR? Thx

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Can you please create the backport PR? Thx

surey :wink:

**Pull request merged**
