### PR TITLE
Resize filepicker on window size change

### LINKED ISSUE #16100: ownCloud filepicker does not resize according to window
1. Open an ownCloud file picker, e.g. the image picker in the personal settings (or the first run wizard)
2. Resize the window – this could also be when rotating a tablet from landscape to portrait
3. Observe the file picker not resizing and becoming unusable:
capture du 2015-05-06 10 21 14

@schiesbn @MorrisJobke we need to adjust that library.

### PR DESCRIPTION
**Pull request by MorrisJobke**
- add 20 px space to each direction -> 10px padding to left, right, top and bottom
- fixes #16100 

cc @owncloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! Can you define a max-width of 600px for the thing? Otherwise it gets very wide.

**Comment by MorrisJobke** [comment]
> Nice! Can you define a max-width of 600px for the thing? Otherwise it gets very wide.

done

**Comment by jancborchardt** [comment]
Great stuff. :+1: 

Please also test this @Xenopathic :) when we open the filepicker issues, we should also review them.

**Comment by Xenopathic** [comment]
The size is correctly scaled when opening the filepicker, but on window resize it doesn't seem to change:

screenshot - 060515 - 10 28 37

**Comment by jancborchardt** [comment]
Ahh yes – you can reproduce that by opening the dev console quickly via Ctrl-Shift-i instead of slowly resizing the window. Result: It will not change size.

**Comment by Xenopathic** [comment]
Note: I am using the i3 titling window manager, so resizes are 'atomic' operations (not slow slides like in other DEs). That could be part of the reason.

**Comment by jancborchardt** [comment]
I use Ubuntu, Gnome 3 and Firefox – reproducable. Does anyone have an iPad or some regular Android tablet to test if rotates work fine?

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
> I use Ubuntu, Gnome 3 and Firefox – reproducable. Does anyone have an iPad or some regular Android tablet to test if rotates work fine?

What is the issue here? Broken or does it work?

**Comment by jancborchardt** [comment]
@MorrisJobke I have the same problem like @Xenopathic in the case of an atomic operation resize – like when opening the dev tools with Ctrl-Shift-i. Then the resize does not happen.

**Comment by jancborchardt** [comment]
@MorrisJobke any updates here? I would actually say that fixing the atomic resizing is something for another pull request.

Can we have a second review here @Xenopathic @owncloud/designers?

**Comment by Xenopathic** [comment]
Well it's definitely better than before (though not quite 100% working), so :+1:

**Pull request merged**
