### PR TITLE
handle case where the given language is unknown - refs #15794

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by mmattel** [comment]
:+1:

**Comment by nickvergessen** [comment]
Fetch the folder case aswell?
```
$ ./occ l10n:createjs files_pdfviewer

  [UnexpectedValueException]
  DirectoryIterator::__construct(/home/nickv/ownCloud/master/repos/files_pdfviewer/l10n):
  failed to open dir: No such file or directory
```

**Comment by DeepDiver1975** [comment]
> Fetch the folder case aswell?

well - I would throw an UnexpectedValueException as well - no difference in the behavior from my pov

**Comment by nickvergessen** [comment]
hmm right: :+1:

**Pull request merged**
