### PR TITLE
Allow regular users to change their CORS domains

### LINKED ISSUE #30647: Users cannot add domains under CORS settings
In 10.0.7 under "Personal Settings->Security" options for CORS are shown. 

image

However, if a normal user attempts to add a domain the following error is displayed:
```
Access forbidden
Logged in user must be an admin
```
 
we should fix it.

@Emil-G @PVince81

### PR DESCRIPTION
**Pull request by PVince81**
## Description
See subject

## Related Issue
Fixes https://github.com/owncloud/core/issues/30647

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]
Tested - works :+1:

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/30649

**Comment by pako81** [comment]
works. But should not the domains then appear in the list of the white-listed domains?

**Comment by pako81** [comment]
ah ok it looks like there is no error showed if you enter an invalid URL (i.e. missing the http part)

**Comment by PVince81** [comment]
> ah ok, it looks like there is no error showed if you enter an invalid URL (i.e. missing the http part)

yes, that's another bug... will take a bit more time to fix as there is no way to return an error here... need to port the code to use ajax calls instead of full page request

**Pull request merged**
