### PR TITLE
Add missing version field

### PR DESCRIPTION
**Pull request by LukasReschke**
@nickvergessen THX

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
Merge "conflict" from your patch earlier, so no chance to discover that.

**Comment by LukasReschke** [comment]
Yup. Nobody to blame here :smile: 

(except PHP. Of course we _always_ have to blame PHP! ;-))

**Comment by nickvergessen** [comment]
@DeepDiver1975

**Comment by MorrisJobke** [comment]
Works :+1:

**Pull request merged**
