### PR TITLE
[3rdparty] Bump symfony/console to 2.8.3

### PR DESCRIPTION
**Pull request by rullzer**
Requires https://github.com/owncloud/3rdparty/pull/255

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
smb tests failing? :fish: y

**Comment by rullzer** [comment]
Rebased to see if smb was just a glitch...

**Comment by DeepDiver1975** [comment]
3rdparty merged

**Comment by rullzer** [comment]
Rebased.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
