### PR TITLE
[backport] [stable8.1] Fix shared files of deleted users, detect DN change when checking for existence on LDAP

### PR DESCRIPTION
**Pull request by blizzz**
Backport of #21133 to stable8.1, see original PR for test steps.

@owncloud/ldap @davitol @alex42ka @esakol @tomcat-sdb @ckruetze @alexweirig @frankuit @MorrisJobke

### CODE REVIEW

**Comment by blizzz** [comment]
Failing tests either unrelated or due to some CI hickup.

**Comment by MorrisJobke** [comment]
I tested this with LDAP and it works :+1:

**Comment by SergioBertolinSG** [comment]
Tested case 1 with AD - Working correctly.

**Comment by SergioBertolinSG** [comment]
Case 2 - Has failed. Files cannot be finded by user2.

I guess the problem is that I am using sAMAccountName and I've changed this value too when editing DN. :-1:

**Comment by SergioBertolinSG** [comment]
OK changing back that sAMAccountName value it works.
:+1:

**Pull request merged**
