### PR TITLE
Normalize file names for comparison with array

### PR DESCRIPTION
**Pull request by LukasReschke**
Mac OS X uses the NFD normalization form to encode UTF-8, this leads to the problem that the values compared in the array are differently encoded making these tests on OS X fail.

Personally I'd more prefer if we would have a wrapper around readdir adressing encoding issues as there are a lot of encoding issues on different filesystems. Evert has done an interesting write-up: http://evertpot.com/filesystem-encoding-and-php/

Fixes the following failing tests:

```
/Users/lukasreschke/Documents/Programming/master/tests/lib/files/storage/storage.php:88

2) Test\Files\Storage\CopyDirectory::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'spéciäl földer'
+    0 => 'spéciäl földer'
 )

/Users/lukasreschke/Documents/Programming/master/tests/lib/files/storage/storage.php:88

3) Test\Files\Storage\Home::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'spéciäl földer'
+    0 => 'spéciäl földer'
 )

/Users/lukasreschke/Documents/Programming/master/tests/lib/files/storage/storage.php:88

4) Test\Files\Storage\Local::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'spéciäl földer'
+    0 => 'spéciäl földer'
 )

/Users/lukasreschke/Documents/Programming/master/tests/lib/files/storage/storage.php:88

5) Test\Files\Storage\Wrapper\Encryption::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'spéciäl földer'
+    0 => 'spéciäl földer'
 )

/Users/lukasreschke/Documents/Programming/master/tests/lib/files/storage/storage.php:88

6) Test\Files\Storage\Wrapper\Jail::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'spéciäl földer'
+    0 => 'spéciäl földer'
 )

/Users/lukasreschke/Documents/Programming/master/tests/lib/files/storage/storage.php:88

7) Test\Files\Storage\Wrapper\PermissionsMask::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'spéciäl földer'
+    0 => 'spéciäl földer'
 )

/Users/lukasreschke/Documents/Programming/master/tests/lib/files/storage/storage.php:88

8) Test\Files\Storage\Wrapper\Quota::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'spéciäl földer'
+    0 => 'spéciäl földer'
 )

/Users/lukasreschke/Documents/Programming/master/tests/lib/files/storage/storage.php:88

9) Test\Files\Storage\Wrapper\Wrapper::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'spéciäl földer'
+    0 => 'spéciäl földer'
 )
```

@MorrisJobke @icewind1991 THX.

### CODE REVIEW

**Comment by icewind1991** [comment]
@LukasReschke changed it to normalize the readdir result in a wrapper, can you test it on osx?

**Comment by LukasReschke** [comment]
@icewind1991 Are you sure this ever works? I added an exit in `dir_readdir` and yet `phpunit lib/files/storage/commontest.php` does not exit but fails.

**Comment by PVince81** [comment]
@LukasReschke I wanted to see how this behaves with NFD file names on SMB, but when scanning I'm getting this in the middle of the scan, just when it was about to scan the NFD file:

```
        Folder /root/files/smb/encoding/both-conflict
        File   /root/files/smb/encoding/both-conflict/ümlaut.txt
        File   /root/files/smb/encoding/both-conflict/ümlaut.txt
        Folder /root/files/smb/encoding/both-separate
        File   /root/files/smb/encoding/both-separate/good-ümlaut.txt
PHP Fatal error:  Call to undefined function random_int() in /srv/www/htdocs/owncloud/lib/private/security/securerandom.php on line 80
PHP Stack trace:
PHP   1. {main}() /srv/www/htdocs/owncloud/occ:0
PHP   2. require_once() /srv/www/htdocs/owncloud/occ:11
PHP   3. OC\Console\Application->run() /srv/www/htdocs/owncloud/console.php:81
PHP   4. Symfony\Component\Console\Application->run() /srv/www/htdocs/owncloud/lib/private/console/application.php:110
PHP   5. Symfony\Component\Console\Application->doRun() /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRunCommand() /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php:195
PHP   7. Symfony\Component\Console\Command\Command->run() /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php:874
PHP   8. OCA\Files\Command\Scan->execute() /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP   9. OCA\Files\Command\Scan->scanFiles() /srv/www/htdocs/owncloud/apps/files/command/scan.php:201
PHP  10. OC\Files\Utils\Scanner->scan() /srv/www/htdocs/owncloud/apps/files/command/scan.php:136
PHP  11. OC\Files\Cache\Scanner->scan() /srv/www/htdocs/owncloud/lib/private/files/utils/scanner.php:157
PHP  12. OC\Files\Cache\Scanner->scanChildren() /srv/www/htdocs/owncloud/lib/private/files/cache/scanner.php:292
PHP  13. OC\Files\Cache\Scanner->scanChildren() /srv/www/htdocs/owncloud/lib/private/files/cache/scanner.php:411
PHP  14. OC\Files\Cache\Scanner->scanChildren() /srv/www/htdocs/owncloud/lib/private/files/cache/scanner.php:411
PHP  15. OC\Files\Cache\Scanner->scanFile() /srv/www/htdocs/owncloud/lib/private/files/cache/scanner.php:371
PHP  16. OC\Files\Cache\Scanner->getData() /srv/www/htdocs/owncloud/lib/private/files/cache/scanner.php:143
PHP  17. OCP\Util::writeLog() /srv/www/htdocs/owncloud/lib/private/files/cache/scanner.php:114
PHP  18. OC\Log->log() /srv/www/htdocs/owncloud/lib/public/util.php:154
PHP  19. call_user_func:{/srv/www/htdocs/owncloud/lib/private/log.php:266}() /srv/www/htdocs/owncloud/lib/private/log.php:266
PHP  20. OC_Log_Owncloud::write() /srv/www/htdocs/owncloud/lib/private/log.php:266
PHP  21. OC\AppFramework\Http\Request->getId() /srv/www/htdocs/owncloud/lib/private/log/owncloud.php:83
PHP  22. OC\Security\SecureRandom->generate() /srv/www/htdocs/owncloud/lib/private/appframework/http/request.php:463
```

Use this https://github.com/owncloud/core/issues/21365#issuecomment-176618528 ZIP file's contents on SMB for testing.

**Comment by PVince81** [comment]
... never mind had an early morning git submodule fail

**Comment by PVince81** [comment]
Okay, this PR is not suitable at all for external storage. It simply normalizes the file, doesn't help with reverse lookup.

**Comment by PVince81** [comment]
As we don't support developing/running OC on Mac, I suggest closing.

**Comment by MorrisJobke** [comment]
> As we don't support developing/running OC on Mac, I suggest closing.

Correct.

**Pull request closed without merging**
