### PR TITLE
[10.2.0] share attribute required feature

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/35016 to release-10.2.0

### CODE REVIEW

**Comment by PVince81** [comment]
@mrow4a please have a look and fix.

it seems you might have been using a jquery function that only exists in newer jquery on master

**Comment by patrickjahns** [comment]
I believe we should have this ready for RC2 - @mrow4a @DeepDiver1975

**Comment by mrow4a** [comment]
We need this from master too https://github.com/owncloud/core/pull/35111

**Comment by PVince81** [comment]
additional changes look good :+1:

**Pull request merged**
