### PR TITLE
Add restic/calens for changelog management

### PR DESCRIPTION
**Pull request by micbar**
## Description
Calens is a changelog management tool. It allows us to create and manage changelog entries more easily.

We are using [calens](https://github.com/restic/calens) to properly generate a
changelog before we are tagging a new release. 

## Create Changelog items
Create a file according to the [template](TEMPLATE) for each 
changelog in the [unreleased](./unreleased) folder. The following change types are possible: `Bugfix, Change, Enhancement, Security`.

## Generate the Changelog 
- copy the files from the [unreleased](./unreleased) folder into a folder matching the
schema `10.0.0_2019-09-01` to tag and 
- execute `docker run -ti --rm -v $(pwd):$(pwd) -w $(pwd) toolhippie/calens:latest` in the root folder of the project.

## Example Output:
Changelog for ownCloud Core unreleased (UNRELEASED)
=======================================

The following sections list the changes in ownCloud core unreleased relevant to
ownCloud admins and users. The changes are ordered by importance.

Summary
-------

* Fix [#1234](https://github.com/owncloud/core/issues/1234): Fix behavior for foobar (in present tense)

Details
-------

* Bugfix [#1234](https://github.com/owncloud/core/issues/1234): Fix behavior for foobar (in present tense)

We've fixed the behavior for foobar, a long-standing annoyance for ownCloud users.

The text in the paragraphs is written in past tense. The last section is a list of issue URLs, PR
   URLs and other URLs. These urls need to be plain urls of public resource. The first issue ID (or
   the first PR ID, in case there aren't any issue links) is used as the primary ID.

https://github.com/owncloud/core/issues/1234
https://github.com/owncloud/core/pull/55555
https://doc.owncloud.com/server/admin_manual/configuration/server/config_sample_php_parameters.html

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by pmaier1 — APPROVED** [review]
Can't judge on the tech details but looks good.

**Comment by micbar** [comment]
> Can't judge on the tech details but looks good.

How does the Format fit?

You will get something like my example, 
Real example in https://github.com/restic/restic/blob/master/CHANGELOG.md

**Comment by micbar** [comment]
@DeepDiver1975 done
changelog404

**Review by phil-davis — APPROVED** [review]
LGTM - when we use it we will really know :)

**Pull request merged**
