### PR TITLE
Fixing master unit tests, disabling trashbin trial

### PR DESCRIPTION
**Pull request by PVince81**
It seems the trashbin isn't disabled properly with some test runs/orders.

I couldn't reproduce locally so I'll push tentative changes here and hope it will work...

### CODE REVIEW

**Comment by PVince81** [comment]
This is about fixing the following issue:
```
06:23:35 1) Test\BackgroundJob\DeleteOrphanedSharesJobTest::testClearShares
06:23:35 Failed asserting that actual size 2 matches expected size 1.
06:23:35 
06:23:35 /var/jenkins/workspace/server-master-linux/database/mysql/label/SLAVE/apps/files_sharing/tests/deleteorphanedsharesjobtest.php:132
06:23:35 
06:23:35 2) Test\BackgroundJob\DeleteOrphanedSharesJobTest::testKeepNonFileShares
06:23:35 Failed asserting that actual size 2 matches expected size 1.
06:23:35 
06:23:35 /var/jenkins/workspace/server-master-linux/database/mysql/label/SLAVE/apps/files_sharing/tests/deleteorphanedsharesjobtest.php:155
```

**Comment by nickvergessen** [comment]
If that "works", the fix needs to be different!

**Comment by PVince81** [comment]
Yes... I noticed that the app manager doesn't trigger the "pre_disable" hook @icewind1991

**Comment by PVince81** [comment]
I pushed too fast

**Comment by nickvergessen** [comment]
Please fix this correctly, by triggering the hook, not changing which method we call

**Comment by PVince81** [comment]
Later...

**Comment by PVince81** [comment]
The trashbin app doesn't even use that hook, so it probably won't help this case.

Next try is clearing the hooks.
Note that I cannot debug this locally... so doing it through this PR.

**Comment by PVince81** [comment]
Hmmmmm... so unlogical.

I'll try and debug and see if pre_disable really does something.

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
After having a closer look at the Jenkins error, it looks like it's not necessarily due to the trashbin, but rather some other test that didn't clean up its shares.

**Pull request closed without merging**
