### PR TITLE
[stable7] Fix getItemSharedWithUser for groups

### PR DESCRIPTION
**Pull request by PVince81**
Fixed SQL query for whenever a user has more than one group.
Added missing $owner where clause for group lookup.
Added unit tests for the group cases.

Backport of https://github.com/owncloud/core/pull/13423 to stable7

Please review and test @schiesbn @MorrisJobke @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
Great :+1:

**Comment by PVince81** [comment]
I have retested with the steps from https://github.com/owncloud/core/issues/13361#issuecomment-70136056
And also tested with users that have no group (u1 shares with u2, then u2 shares the subfolder with u3) works as well.

**Comment by PVince81** [comment]
Strange, tests passed for me locally

**Comment by PVince81** [comment]
Can we get this important fix merged ? Thanks

@schiesbn @MorrisJobke @LukasReschke @DeepDiver1975

**Comment by MorrisJobke** [comment]
Let me test that.

**Comment by MorrisJobke** [comment]
Works :+1:

**Pull request merged**
