### PR TITLE
check login name when authenticating via token and basic auth

### LINKED ISSUE #24985: Check loginname when authenticating with basic auth and device token
Starting with 9.1 it is possible to use HTTP basic auth with username and device token. The current implementation does *not* check the username if a token is used as password. Hence one could use a random username. While that works for the first request, sub-sequent requests will be logged out as soon as the password check is performed. That check uses the loginname+password stored in the token.

Although this will kill performance for session-less clients, we have to check the loginname against the user-backend if we want to fix that.

The current behavior also breaks any clients that rely on that check.

cc @PVince81 not sure how critical this is in the scope of 9.1

@owncloud/desktop-developers @owncloud/android-developers @owncloud/ios-developers

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes https://github.com/owncloud/core/issues/24985

### CODE REVIEW

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by ChristophWurst** [comment]
If possible I'd prefer to merge the conflicting PR https://github.com/owncloud/core/pull/25172 first as this PR is way easier to rebase than the other one :see_no_evil:

**Comment by icewind1991** [comment]
Shouldn't this check that the provided uid is the same as the token is for?

**Comment by ChristophWurst** [comment]
Good catch! That should be checked too.

**Comment by PVince81** [comment]
@ChristophWurst https://github.com/owncloud/core/pull/25172 was merged, please rebase and solve conflicts. Thanks!

**Comment by ChristophWurst** [comment]
fixed. @PVince81 @icewind1991 @DeepDiver1975 @guruz @georgehrke  review please

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
Tested, works :+1:

**Pull request merged**
