### PR TITLE
check request token on cookie authenticated request

### PR DESCRIPTION
**Pull request by C0rby**
## Description

Check the request token on cookie authorized requests.

## Motivation and Context

Since the OCS_APIREQUEST header was removed we needed another way to restrict cookie authenticated requests.

## How Has This Been Tested?

- manual smoke testing of the web and android app

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by C0rby** [comment]
Wtf was that condition before?
I must have been tired or something...

**Comment by C0rby** [comment]
Oh this looks promising. Restarting the tests because there was a network timeout

**Comment by C0rby** [comment]
Did some manual smoke testing with the android app and the browser. Nothing seems to be broken there.

**Comment by phil-davis** [comment]
Changelog? Ready for review?

**Comment by C0rby** [comment]
Yeah, I forgot the changelog. Will add it now.

**Review by IljaN — APPROVED** [review]
Did a quick smoke-test by sharing and creating public links from the desktop :heavy_check_mark: 

LGTM :beers:

**Review by micbar — APPROVED** [review]

**Pull request merged**
