### PR TITLE
Fix typo in encryption module message

### PR DESCRIPTION
**Pull request by MorrisJobke**
- finishes #16021 

cc @MTRichards @schiesbn @LukasReschke @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
should this be "... enable an encryption module in the app menu"?

**Comment by MorrisJobke** [comment]
> should this be "... enable an encryption module in the app menu"?

Indeed ... sounds better.

**Comment by MorrisJobke** [comment]
> Indeed ... sounds better.

I will push once Jenkins has finished the current CI run.

**Comment by schiesbn** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@nickvergessen @schiesbn Updated the string again ;)

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
