### PR TITLE
Drop old calendar and contacts tables

### LINKED ISSUE #21889: [9.1] drop old calendar and contacts tables
With 9.0 we will migrate conatcts and calendar data over to the new core tables.
I don't want to run into the situation where we fail to execute the migration and delete the tables in 9.0.

Therefore we drop the tables with 9.1

clndr_calendars
clndr_objects
clndr_share_event
clndr_share_calendar
clndr_repeat

contacts_addressbooks
contacts_cards

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #21889

### CODE REVIEW

**Comment by rullzer** [comment]
:+1:

**Comment by MorrisJobke** [comment]
So we are 100% sure, that we properly migrate everything? :)

Then this is okay for me 👍 

Anyways: we would have time to fix migrations in stable9 branch.

**Comment by DeepDiver1975** [comment]
> So we are 100% sure, that we properly migrate everything? :)
> 
> Then this is okay for me :+1:
> 
> Anyways: we would have time to fix migrations in stable9 branch.

there is no upgrade path from 8.2 to 9.1 - any installation has to go through 9.0 which will handle the import

**Comment by ho4ho** [comment]
Missed contacts_cards_properties removing: https://github.com/owncloud/core/issues/35720, https://github.com/nextcloud/server/pull/157

**Pull request merged**
