### PR TITLE
Encryption fix key lost if group share gets renamed

### PR DESCRIPTION
**Pull request by schiessle**
In master we lose all encryption keys if a file gets shared with a group and one of the group members renamed/moved the share.

This was not detected because the unit tests only tried to read the file again after rename. A few weeks ago we introduced caching for the encryption keys therefore we never detected during the second read operation that the keys no longer exists. This PR adapt the unit tests to check if the keys still exists and fixes the bug. 

It seems like the hooks.php was converted to the dos file format while it was moved to a different location a few weeks ago. I reformatted it back to the unix file format, sorry. The crucial change is at this line: 

old: https://github.com/owncloud/core/compare/enc_fix_key_lost?expand=1#diff-fa12f63daf51643b442e9f6efc7ed784L441 
new: https://github.com/owncloud/core/compare/enc_fix_key_lost?expand=1#diff-fa12f63daf51643b442e9f6efc7ed784R443

### CODE REVIEW

**Comment by karlitschek** [comment]
looks very good :+1:

**Comment by LukasReschke** [comment]
@schiesbn https://github.com/owncloud/core/pull/13204/files?w=1 is easier to review ;-)

**Comment by schiesbn** [comment]
This should also fix #12762 @PVince81 maybe you want to give it a try?

**Comment by PVince81** [comment]
Reviewed and tested, works for both the use case described above and also fixes https://github.com/owncloud/core/issues/12762

:+1:

**Pull request merged**
