### PR TITLE
Filter closures when writing config

### PR DESCRIPTION
**Pull request by butonic**
We would like to give administrators the power to customize the behavior of apps. This PR allows creating a `config/myapp.config.php` like:

``` php
<?php
$CONFIG = array (
  'myapp.uid_mapping' => function($uid) {
    return $uid.'@foo.tld';
  },
);
```

Without this PR writing the config file, eg when changing the loglevel in the web ui will result in a broken and unusable owncloud instance:

```
Fatal error: Call to undefined method Closure::__set_state() in /var/www/owncloud/config/config.php on line 30
```

which looks like:

``` php
  'myapp.uid_mapping' => 
  Closure::__set_state(array(
  )),
```

With this PR the closure is replaced with a hint `Closure from separate config file` so it is clear the actual closure comes from another config file.

cc @felixboehm

### CODE REVIEW

**Comment by butonic** [comment]
I don't know if this is another case where @LukasReschke would like to shoot me for opening another can of worms.

**Comment by DeepDiver1975** [comment]
I honestly vote against such an approach - this feel so fishy.

**Comment by nickvergessen** [comment]
Yes, me too.

Please speak what you want to achieve and we can find a way that works.

**Comment by butonic** [comment]
In this case setting up a mapping for the uid that is provided by the IdP to match something retrievable from ldap. In one case we needed to mad the in memory representation of the Active Directory GUID to the one in ldap - swapping byte positions. In another case we need to add the domain as in the example config above.

Does it make sense to add these corner cases to the web ui? I don't think so. Does it help bring customers in production? Definitely. Having seen the weird GUID stuff I don't believe we can be prepared for everything. And we have yet to see a second customer with the same strange IdP or requirements. I would assume the next customer needs a different mapping.

And I want to be prepared and have a way of solving the problem without going through a full feature request cycle. We can do that as soon as a strange mapping reoccurs. Maybe @MTRichards can share an opinion from product management?

Other than this 'feeling fishy' are there technical or security arguments against it?

**Comment by karlitschek** [comment]
Very hacky. What is the exact problem and then we can find a proper architecture to do this.

**Comment by butonic** [comment]
For SSO we need to align whatever uniqe user id comes from the IdP to whatever the LDAP server can provide as a unique id. If an Active Directory is used together with ADFS you can for example take the [sAMAccountName](https://msdn.microsoft.com/de-de/library/windows/desktop/ms679635(v=vs.85).aspx) or the [objectGUID](https://msdn.microsoft.com/en-us/library/windows/desktop/jj650827(v=vs.85).aspx). In shibboleth federations a so called eppn or [eduPersonPrincipalName](https://www.incommon.org/federation/attributesummary.html#eduPersonPrincipal) is used.

To successfully log in a user in a combined shibboleth / SAML and LDAP / AD environment the twe attributes must be the same. Or to phrase it differently: the uid that comes from the shibboleth side must exist in the ldap server for a successful login. There is an autolearning mechanism in user_shibboleth but no industry customer needs that.

Unfortunately, it is not always AD and ADFS. There is a zoo of both IdPs and LDAP servers and in addition customer specific requirements that do not always allow a 1:1 mapping. see https://github.com/owncloud/core/pull/22530#issuecomment-186360324 for the two cases we already encountered.

IMO it does not make sense to add these exeptions to our code base. They happen infrequently, but the next one is going to come. At least with the next update. Or do you want us to maintain code that is only used at a single installation of owncloud?

In this case we need a tiny bit of customizability. We can of course put the closure in an app specific config.php in the app folder. I think it makes more sense to reuse whatever config code we have in core and place the config file in the config folder so that the app can be upgraded without us having to provide a patch.

However, I think it makes sense to allow closures as config variables. There may be other use cases where this comes in handy. I am not suggesting to use this for complicated stuff. In this case we need to customizing a string.

Any ideas welcome.

**Comment by nickvergessen** [comment]
Can  you post a sample, of what they want to put into such a closure?

**Comment by nickvergessen** [comment]
Closing as per discussion

**Pull request closed without merging**
