### PR TITLE
[stable10] Backport of Fix the redirection url when oC run in localhost

### PR DESCRIPTION
**Pull request by sharidas**
## Description

`OC.getRootPath` returns empty string, when oC is installed under localhost. That is not under any subdirectories. So OC.redirect needs "/" when empty string is got for `getRootPath`.

## Related Issue

- Fixes https://github.com/owncloud/core/issues/32647

## Motivation and Context

`OC.getRootPath` returns empty string, when oC is installed under localhost. That is not under any subdirectories. So OC.redirect needs "/" when empty string is got for `getRootPath`.

## How Has This Been Tested?

- Install oC in localhost ( meaning http://localhost will point to the login page )
- Create user with email address ( so that an email arrives to set password )
- Click the link in th email to set the password
- User doesn't see token invalid message in the page.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [x] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by mmattel** [comment]
I see that this has been named as backport but I can not find the master PR of it.
Can you please add a reference link or in case that there is no master PR created, create a master PR [master] and refrence it.

**Comment by sharidas** [comment]
Original PR: https://github.com/owncloud/user_management/pull/63

**Review by individual-it — APPROVED** [review]
tests in https://github.com/owncloud/core/pull/32638 seems to pass after this fix

**Comment by davitol** [comment]
Tested and works

**Pull request merged**
