### PR TITLE
Scrollable oc.dialog modals

### PR DESCRIPTION
**Pull request by lordelix**
## Description
Allow scrolling in modals if the window height is less than the modal height.

_Expected behavior:_
If a modals height is greater than the window height then its contents should be scrollable.

_Actual behavior:_
The contents of the modal expand beyond the vertical space and the user is not able to interact/reach them.

## How Has This Been Tested?
Visual tests in Chrome, FF

## Screenshots (if appropriate):
fireshot capture 20 - dateien - owncloud_ - http___192 168 21 18_8000_index php_apps_files_

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by PVince81 — COMMENTED** [review]
Code looks fine. Needs testing in IE11, Safari

**Comment by felixheidecke** [comment]
@Testingcew: The "create public share" modal is a good candidate for testing the vertical height issue.
Please test if all the contents from top to bottom are visible. Especially if the buttons still work as they supposed to do.

**Comment by ChrisEdS** [comment]
Tested in Safari and iE11 - works as expected.

**Review by ChrisEdS — APPROVED** [review]
Ready. Steady. Go!

**Comment by davitol** [comment]
> Tested in Safari and iE11 - works as expected.

👍 Same here

**Review by davitol — APPROVED** [review]

**Comment by PVince81** [comment]
@felixheidecke please backport

**Comment by phil-davis** [comment]
Backport stable10 #30424

**Pull request merged**
