### PR TITLE
Delay listening to owner changes untill we use a share for that owner

### PR DESCRIPTION
**Pull request by icewind1991**
Make setting up a shared mountpoint a bit faster

cc @MorrisJobke @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
makes sense :+1:

**Comment by MorrisJobke** [comment]
Change looks good, tested some (re-)shares and their etag propagation :+1:

* [ ] local tests are still running

**Comment by PVince81** [comment]
Please rebase and also set the labels (this should become a habit!)

**Comment by icewind1991** [comment]
Rebased

**Comment by PVince81** [comment]
@MorrisJobke did the local tests finish ? :wink:

**Comment by MorrisJobke** [comment]
Rebased.



> @MorrisJobke did the local tests finish ? :wink:

No idea anymore. Let Jenkins do it's job :)

**Comment by DeepDiver1975** [comment]
@icewind1991 does this solve and open issues - THX

**Comment by icewind1991** [comment]
No, just performance improvement

**Comment by DeepDiver1975** [comment]
> No, just performance improvement

THX

**Pull request merged**
