### PR TITLE
Disable some server checks when running on HHVM

### PR DESCRIPTION
**Pull request by LukasReschke**
Ref https://github.com/owncloud/core/issues/10837#issuecomment-76516839

### CODE REVIEW

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/14605/files?w=1

**Comment by LukasReschke** [comment]
Also probably needs another adjustments at https://github.com/owncloud/core/blob/master/tests/bootstrap.php#L10…

**Comment by DeepDiver1975** [comment]
let's move this in :+1:

**Comment by Xenopathic** [comment]
What happens with `ini_get()` when running under HHVM? I couldn't find any related issues on Google.

**Comment by LukasReschke** [comment]
> What happens with ini_get() when running under HHVM? I couldn't find any related issues on Google.

It just returns other default values and for now this is a quick win approach to get our unit tests running again. As we're anyways not yet fully compatible with HHVM this looks okay :see_no_evil:

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
