### PR TITLE
Allow search in synced addressbooks

### PR DESCRIPTION
**Pull request by DeepDiver1975**
# Test Scenario 1
1. make sure the local system addressbook has been generated (occ command)
2. search for a local user in the share tab (yes - local remote shares are stupid - this is for testing)
   note that search is based on the display name
3. see the local user being displayed in the drop down
# Test Scenario 2
1. have two instances trusting each other
2. have local addressbooks generated
3. have them remote addressbooks synced
4. seach for a user on the other system within the share tab
5. see the remote user popping up

### CODE REVIEW

**Comment by schiesbn** [comment]
local user search works but the search for the remote user seems to be broken.

I have two server: server1 and server2
server1 has the user userServer1
server2 has the user userServer2

address books are exchanged correctly.

But if I start to type "user" in the share drop-down of server1 I get two suggestions the local user "userServer1" and a remote user "userServer1@server1". As remote user I would expect "userServer2@server2" instead.

**Comment by DeepDiver1975** [comment]
> address books are exchanged correctly.

so there is an additional addressbook under remote.php/dav/system/system ?

Can you please connect cadaver and ls the cards inside that new addressbook?

**Comment by schiesbn** [comment]
I think the problem is here: https://github.com/owncloud/core/pull/21988/files#diff-629026ae74b32f159209da5b36c26751L41

You only load the local system address book and the users address book. "principals/system/system" is the local system address book. That's also the reason why I see the local user as remote user. But the synced system address book from the remote server has a random principalURI, in my case "8a7f317f5296de227f7ac1ff8a351ef74145b7dc"

**Comment by DeepDiver1975** [comment]
> You only load the local system address book and the users address book. "principals/system/system" is the local system address book. That's also the reason why I see the local user as remote user. But the synced system address book from the remote server has a random principalURI, in my case "8a7f317f5296de227f7ac1ff8a351ef74145b7dc"

that code is correct - the principal is the user who owns the addressbooks. There are two users for whom we want to register the addressbooks: the logged in user and all system addressbooks.

**Comment by schiesbn** [comment]
That's how my oc_addressbooks table looks like:

````
id| principaluri | displayname | uri | description | synctoken 
1|principals/system/system|system|system|System addressbook which holds all users of this instance|3
2|8a7f317f5296de227f7ac1ff8a351ef74145b7dc|http://localhost/federation|principals/system/system||3
````

The line above loaded the address books with the principal ID ````principals/users/$userId```` and ````principals/system/system```` but ````principals/system/system```` is the local system wide address book and not the synced address book. The synced has the principalurl ````8a7f317f5296de227f7ac1ff8a351ef74145b7dc````

**Comment by DeepDiver1975** [comment]
There is something wrong with the insert statement of the synced addressbook

**Comment by DeepDiver1975** [comment]
> 2|8a7f317f5296de227f7ac1ff8a351ef74145b7dc|http://localhost/federation|principals/system/system||3

the values of column principaluri and uri are switched

**Comment by DeepDiver1975** [comment]
@schiesbn for further testing of this pr please switch the values in the db - I'll investigate where the switch is coming from. THX

**Comment by DeepDiver1975** [comment]
In addition I rebased this PR to make sure we have the latest code pieces in place

**Comment by schiesbn** [comment]
> I'll investigate where the switch is coming from. THX

I found it... will open a PR

**Comment by DeepDiver1975** [comment]
> I found it... will open a PR

Great! THX

**Comment by nickvergessen** [comment]
Should this respect https://github.com/owncloud/core/blob/master/apps/files_sharing/api/sharees.php#L351-L352 ?

**Comment by DeepDiver1975** [comment]
> Should this respect https://github.com/owncloud/core/blob/master/apps/files_sharing/api/sharees.php#L351-L352 ?

hmmm - I guess not since we have no federated group concept - we have no idea on how groups are organized on thrusted servers

**Comment by nickvergessen** [comment]
Well at least enumeration could be blocked? Or should this just not work at all, if enumeration is off?

**Comment by DeepDiver1975** [comment]
> Well at least enumeration could be blocked? Or should this just not work at all, if enumeration is off?

will the sharee code not take care of that? As in discard all non-exact matches?

**Comment by schiesbn** [comment]
with my PR above it works (almost).

Now I find the local users and the remote users. But I still find the local users twice, once as local user and once as federated user. This probably happens because we load the address book ````principals/system/system```` but a address book with this principleuri exists twice. Once the synced remote address book and once the system wide local address book. So if I search for "localUser" we will find the user in the local user management and in the local system address book which lead to the two results.

**Comment by DeepDiver1975** [comment]
Let me have a look on how to filter this properly.
Generally speaking we need to register all address books because we want to know local users as well when e.g. searching for E-Mail adresses from the mail app.

**Comment by nickvergessen** [comment]
> will the sharee code not take care of that? As in discard all non-exact matches?

right, it does:
```php
if (strtolower($contact['FN']) === $search || strtolower($cloudId) === $search) {
```

**Comment by DeepDiver1975** [comment]
@schiesbn local users are now filtered - please have a look - THX

**Comment by schiesbn** [comment]
everything works now :+1:

**Comment by DeepDiver1975** [comment]
THX @schiesbn

**Comment by LukasReschke** [comment]
Stuff seems to work and code looks good :+1:

**Pull request merged**
