### PR TITLE
Add confirm password after new password

### PR DESCRIPTION
**Pull request by sharidas**
The confirm password would help to validate
if the password entered is same as new
password entered.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

The confirm password text box would help users to validate the new password. If there is any mismatch between 2 passwords then no reset action should take place.

## Related Issue

https://github.com/owncloud/core/issues/29901

## Motivation and Context

The confirm password text box would help users to validate the new password. If there is any mismatch between 2 passwords then no reset action should take place.

## Screenshots (if appropriate):
 
confirmpassword1

confirmpassword2

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
@pmaier1 see above, looks like this would be useful

**Comment by PVince81** [comment]
for consistency, might need to add a "confirm second password" to the personal page

**Comment by PVince81** [comment]
@sharidas please rebase.

if this is finished we could move forward as it's a nice addition

**Comment by phil-davis** [comment]
This will need some webUILogin acceptance test changes - the UI workflow changes and the acceptance test will need to input the new password twice now.

**Comment by sharidas** [comment]
- [ ] Need to adjust the acceptance test.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
we can ignore codecov as this is covered by acceptance tests

**Comment by PVince81** [comment]
@sharidas please backport

**Comment by phil-davis** [comment]
@sharidas I will make a backport of this PR and PR #34490 together in a moment.

**Comment by phil-davis** [comment]
Backport ``stable10`` #34492

**Pull request merged**
