### PR TITLE
Starlark for 10.3.1

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Apply recent `.drone.yml` and associated `.drone.starlark` etc... commits to the `release-10.3.1` branch.

From PRs:
#36209 Add coverage-upload to phpunit pipelines which generate coverage
#36272 Initial drone starlark
#36296 drone notify on failure
#36292 Run sftp unit tests in drone
#36319 Do not encode path separator in LargeFileHelper::getFileSizeViaCurl
  (includes "disable external samba and windows phpunit tests - issue 36322")

## Motivation and Context
Make CI current and passing for `10.3.1`

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by micbar — APPROVED** [review]
Great!

**Comment by phil-davis** [comment]
Hmmm - I don't like that codecov result https://github.com/owncloud/core/pull/36374#issuecomment-549673157 
Let's see what the next CI run reports. Maybe I am missing some other commits that fixed that codecov problem recently.

**Comment by micbar** [comment]
@phil-davis Yes. I remember that. Some coverage steps were missing as you created the original starlark PR.

It should have got fixed in another commit later.

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
> @phil-davis Yes. I remember that. Some coverage steps were missing as you created the original starlark PR.
> 
> It should have got fixed in another commit later.

Now I look more closely - codecov is telling me about the 10% increase in coverage, which is the codecov result upload that is fixed by one of the commits I cherry-picked in here. So that is all good.

**Pull request merged**
