### PR TITLE
Reword external storage auth backends

### LINKED ISSUE #21911: Rewording of credentials dropdown in external storage.
A change is needed from "session credentials" and "login credentials" to "login credentials, save in session"  and "login credentials, save in DB"

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/21911

See https://github.com/owncloud/core/issues/21911#issuecomment-175126272 for the new wording

Please review @SergioBertolinSG @Xenopathic @icewind1991 @jmaciasportela

### CODE REVIEW

**Comment by PVince81** [comment]
screenshot_20160201_122631

**Comment by SergioBertolinSG** [comment]
<script type="text/javascript" src="//www.google.es/trends/embed.js?hl=es&q=%22login+credentials%22,+log-in+credentials,+log+in+credentials&cmpt=q&tz=Etc/GMT-1&tz=Etc/GMT-1&content=1&cid=TIMESERIES_GRAPH_0&export=5&w=500&h=330"></script>

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
@SergioBertolinSG to be honest I don't care whether it's "log in", "log-in" or "login". Most important is that it's easy to understand what it is about.

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
