### PR TITLE
[stable10] [phpunit] Fail on warnings

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #30629

### CODE REVIEW

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
I guess CI in ``stable10`` is running extra encryption cases and it generates this warning:
```
There was 1 warning:

1) OCA\Encryption\Tests\Crypto\EncryptAllTest::testEncryptUsersFiles
Class "Symfony\Component\Console\Helper\ProgressBar" is declared "final" and cannot be mocked.
```
from ``apps/encryption/tests/Crypto/EncryptAllTest.php`` that has:
```
		$progressBar = $this->getMockBuilder('Symfony\Component\Console\Helper\ProgressBar')
			->disableOriginalConstructor()->getMock();
```
@DeepDiver1975 you know all about this sort of thing?

**Comment by patrickjahns** [comment]
@DeepDiver1975 
should we forward port the stub for this testcase?

**Comment by DeepDiver1975** [comment]
> should we forward port the stub for this testcase?

needs to go into https://github.com/owncloud/encryption

**Comment by DeepDiver1975** [comment]
> needs to go into https://github.com/owncloud/encryption
> Merge state

https://github.com/owncloud/encryption/pull/28 ... ongoing ...

**Comment by phil-davis** [comment]
@DeepDiver1975 congratulations!

This code is not in ``core`` ``master`` - so AFAIK that last commit does not need to be forward-ported.

**Pull request merged**
