### PR TITLE
Include new capabilities for the password enforcement for sharing

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Files sharing capabilities will include these new options. The previous "password enforced" capability (which wasn't working properly in 10.0.8) will indicate if any of the options are active. This should keep backwards compatiblity because the clients should enforce the password for all the options, which is more restrictive but should be less problematic for old clients.

Note that the internal sharing API remains unchanged, particularly https://github.com/owncloud/core/blob/master/lib/public/Share/IManager.php#L239

## Related Issue
https://github.com/owncloud/core/issues/31492

## Motivation and Context
Broken capability in 10.0.8

## How Has This Been Tested?
Unittest as well as checking "/ocs/v1.php/cloud/capabilities" endpoint

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
Also see #31494 which has API acceptance test code and scenarios. Grab those, then I can close that PR.

**Comment by jvillafanez** [comment]
This should be mostly ready. I feel we should add some acceptance test for the case where the password isn't enforced, but I'm not sure if it's already covered by the rest of the scenarios.

**Comment by phil-davis** [comment]
It looks like you got all the code from mine, and I got the code from yours. So both were equivalent.

**Comment by phil-davis** [comment]
No need for backport label on this PR that was closed.

**Pull request closed without merging**
