### PR TITLE
[Tests-Only] Make the excludes longer in sonar-project 

### PR DESCRIPTION
**Pull request by phil-davis**
On top of #37982 

See if this helps the coverage calculation.

### CODE REVIEW

**Comment by phil-davis** [comment]
Only gets 55.2% - that hardly made any difference from 55.1%

**Comment by micbar** [comment]
> Only gets 55.2% - that hardly made any difference from 55.1%

Thanks for trying out.

So either
1) Codecov is wrong :-)
2) We are not getting every report.

**Comment by phil-davis** [comment]
IMO there are some coverage-specific include/exclude parameters. I will look for the documentation on those and see if it can help.

**Comment by micbar** [comment]
I cannot spot in the sonar-analysis log where it finds the `lcov.info` from the JS tests.

**Comment by phil-davis** [comment]
`sonar.php.coverage.reportPaths` has `lcov.info` in it. @dpakach got the coverage to increase from 50.7% to 55.1% by adding that. So it did have an effect.

I suspect that more files are being included in the "total amount of code to cover" and that brings down the percentage coverage. But I don't actually know. It would be nice to see a detailed report online showing each file - it should be obvious from that if there are groups if files that are listed as 0% coverage.

**Comment by phil-davis** [comment]
When I go to https://sonarcloud.io/code?id=owncloud_core&pullRequest=37984 and select the "Code" tab, it is empty.
Maybe we have to merge something first, and then it will have some "baseline coverage" in master and will start showing useful coverage diffs or?

**Comment by micbar** [comment]
Yes. let us merge and see.

**Comment by phil-davis** [comment]
"Yes. let us merge and see." - to get an initial set of `master` coverage information where we will be able to (hopefully)  browse around the results and see the detail of the coverage that SonarCloud is calculating.

I also found https://community.sonarsource.com/t/sonarqube-and-code-coverage/4725 - that has information about how the "coverage" metric is calculated by SonarCloud. It includes calculations of conditions that have evaluated to both true and false, as well as "basic line coverage". So that might also have some influence on the numbers.

After merging, we will see...

**Review by individual-it — APPROVED** [review]

**Pull request merged**
