### PR TITLE
[stable8] fix mobile scrolling, lower sidebar sensitivity, fix #11193

### LINKED ISSUE #11193: Mobile experience very flaky due to snap.js issues
I've been using the new News app release on my mobile phone the last couple of days and the snap.js experience is very flaky:

* If you scroll down with your finger, the menu shows quite often even if you dont want it. To fix this you need to swipe down from the top left to the bottom right corner to not trigger a left swipe which is kinda weird
* The flying loading icon issue, same as in https://github.com/owncloud/notes/issues/64
* The loading icon and hamburger menu overlap the navigation

All in all I think it would be best to get rid of snap.js (if none of these issues can be fixed in the next couple months) and just use the hamburger button to toggle the right menu, you dont need the menu that often and the hamburger menu is reachable pretty well at all times due to the fixed positioning.

PS: please try out the new News app release, also on your mobile and touch devices :)

@jancborchardt @MorrisJobke @jbtbnl @georgehrke @raghunayyar @PVince81 @th3fallen

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #17785 
Approval https://github.com/owncloud/core/pull/17785#issuecomment-130663801

@owncloud/designers @Bullnados @Raydiation @zerosine @finius @tflidd Please review :) 

I tested it locally and it works.

### CODE REVIEW

**Comment by jancborchardt** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@rullzer @Xenopathic @Henni Mind to test/review this?

**Comment by rullzer** [comment]
Code looks simple enough :)
Works as expected on my phone.
:+1:

**Comment by Bullnados** [comment]
:+1:

**Pull request merged**
