### PR TITLE
[stable10] Log exception when background job class not found

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #32623 

@PVince81 I found this backport branch already here, but there did not seem to be a PR. So I have rebased and started this backport PR.

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/15888/92
```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.38-3+ubuntu16.04.1+deb.sury.org+1
Configuration: /drone/src/tests/phpunit-autotest.xml
Error:         No code coverage driver is available

........S....................................................   61 / 5109 (  1%)
.............................................................  122 / 5109 (  2%)
PHP Fatal error: Call to undefined method OC\BackgroundJob\JobList::listJobs() in /drone/src/tests/lib/BackgroundJob/JobListTest.php on line 268
```

**Comment by phil-davis** [comment]
Commit from other backport PR #34783 has been added here, because this backport is dependent on that commit getting in first/also.

**Comment by phil-davis** [comment]
@PVince81 this is ready for approval after #34783 is merged.

**Comment by PVince81** [comment]
rebased and adjusted "since" version to say 10.2.0

**Comment by phil-davis** [comment]
@PVince81 CI is green. I can't review, because it is my PR.

**Comment by phil-davis** [comment]
> rebased and adjusted "since" version to say 10.2.0

"since" PHPdoc changes forward-ported to `master` in #34994

**Pull request merged**
