### PR TITLE
handle non existing job classes in $jobList->getNext

### LINKED ISSUE #18295: Cronjob failing due to not continuously assigned IDs in jobs table
Hi there.

After upgrading to OC 8.1 and seperatly updating my installed apps, I did recognize that my cron.php was not handling all exiting jobs anylonger. 

The main reason for this was a gap within the continuously assigned IDs in jobs table. Probably any app upgrade was the reason for this, but this is not really replicable for me. This gap within the given IDs, that is ID 5 was present, but the next ID was 9, lead to a stop of job processing at ID 5. 

It seems that the current implementation of "getLastJob()" in "joblist.php" return the last processed job's ID, but the method "getNext()" is currently not able to skip the gap of IDs in the table, so it stops without processing the rest of existing jobs. 

I solved it by re-assigning consistent IDs in MySql, but I think the method "getNext()" shall be able to handle such a gap of IDs, because it is obviously possible to create such situation using the WebClient.

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes issues after disabling an app that has registered a job when not using system cron.

Fixes #18295

@MarioSchymura can you check if this fixes the problem

cc @PVince81 @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:  looks good

**Comment by PVince81** [comment]
I tried to reproduce the original issue as follows:

1. Install and enable "activity" app
1. Install and enable "news" app
1. Check the `oc_jobs` table, you should see 4 entries
1. Disable and delete the "activity" app (the code must be gone)
1. SQL: update oc_jobs set last_run=0;
1. Run cron several times

On master it seemed to still work properly. I also tried deleting the "activity" app without disabling it. Also worked.

Anyway, this PR also works fine with my test scenario, so I think it can be merged :+1:

**Comment by icewind1991** [comment]
> Run cron several times

The problem only occurs when using webcron

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
