### PR TITLE
[WIP] smb domain fix with migrations

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
SMB domain fixes

## Related Issue
https://github.com/owncloud/core/issues/30184

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**WIP Not ready to be merged.**

### CODE REVIEW

**Comment by jvillafanez** [comment]
I'll need some advice here on how to proceed. The migration code is quite bad, and failed storages aren't being handled right now, which implies very likely changes in core that will need to be tested, and more dirty code to add here.

**Comment by jvillafanez** [comment]
Bump!

**Comment by mmattel** [comment]
@jvillafanez any update on that?

**Comment by jvillafanez** [comment]
No updates. Either @PVince81 or @felixboehm need to take a decision on how we want to proceed:
* Forget about the migration. This might be problematic for large SMB storages because all the content will need to be redownloaded.
* Invest time to fix the migration code. As said in https://github.com/owncloud/core/pull/30534#issuecomment-369214954 things will likely get very dirty. The solution looked bad back then.

**Comment by PVince81** [comment]
alternative: is there a way to somehow detect domain collision and simply show a warning ?

so far it seems this use case is so rare that such tricky fix might not be worth the effort... but at least warning an admin in case a collision would happen would be nice

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
