### PR TITLE
Password login forbidden hint

### LINKED ISSUE #25091: Add hint in 401 response when regular password is disabled (2FA)
When two factor auth is enabled, Webdav doesn't accept regular login/password but only tokens.
In order for the clients to be able to display a useful message for users, the server should return additional info in the 401 Webdav response.

The current 401 response looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured</s:message>
</d:error>
```

So either use another exception name or try adding a "s:reason" block with a message or a hint that the client can parse.

@ChristophWurst @ogoffart @dragotin

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes https://github.com/owncloud/core/issues/25091

### CODE REVIEW

**Comment by PVince81** [comment]
Fixed exception type.

Works now:
```
  % curl -D - -X PROPFIND http://admin:admin@localhost/owncloud/remote.php/webdav/
HTTP/1.1 401 Unauthorized
Date: Fri, 17 Jun 2016 13:49:55 GMT
Server: Apache/2.4.20 (Linux/SUSE)
X-Powered-By: PHP/5.6.22
Set-Cookie: ockbfur1449k=k30ahaqbsg8iq5c2p3hdag4m4ig42s21k9pj20k4aqltans1o881; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=1QhZfo87rcLL%2FyyWEmw6DHaltw5QavQdw0%2FyimJAHgOorVpD1kYiwb8WqyWqzTbQ07SOHnRxS1T18Yt6C3FMv7pAMo7DfM5SbOX6ZQtLP3PLeu7IRLq1GMtauJX381K6; path=/owncloud; httponly
Content-Security-Policy: default-src 'none';
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Content-Length: 299
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\PasswordLoginForbidden</s:exception>
  <s:message/>
  <o:hint xmlns:o="o:">password login forbidden</o:hint>
</d:error>
```

@ogoffart @guruz

**Comment by ChristophWurst** [comment]
:+1: works

**Comment by icewind1991** [comment]
Looks good :+1:

**Comment by guruz** [comment]
Did you check if the client actually displays this?

**Comment by PVince81** [comment]
No, I only checked that the exception was returned. Not sure if the client side is ready ?

**Comment by PVince81** [comment]
@ChristophWurst @ogoffart @guruz please check with the client. This is merged, so check out master when testing.

**Comment by guruz** [comment]
Testing client now: I don't seem to get it with the wizard..

```
06-21 13:17:05:263 176703 OCC::OwncloudSetupWizard::slotConnectToOCUrl: Connect to url:  "http://127.0.0.1:1239/"
06-21 13:17:05:264 176703 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "Trying to connect to ownCloud at http://127.0.0.1:1239/..."
06-21 13:17:05:264 176703 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "http://127.0.0.1" + "/" "OCC::OwncloudSetupWizard"
06-21 13:17:05:329 176703 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(AuthenticationRequiredError) "Host requires authentication" QVariant(int, 401)
06-21 13:17:05:329 176703 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 401 ""
```

But I get it if the account was already setup before I get a repeating password input dialog:
```
06-21 13:20:47:356 179577 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
06-21 13:20:47:357 179577 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "http://127.0.0.1" + "/" "OCC::ConnectionValidator"
06-21 13:20:47:444 179577 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(AuthenticationRequiredError) "Host requires authentication" QVariant(int, 401)
06-21 13:20:47:444 179577 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href=\"http://127.0.0.1:1239\">http://127.0.0.1:1239</a>.\nThe provided credentials are not correct"
06-21 13:20:47:447 179577 OCC::FolderMan::slotAccountStateChanged: Account "woboq@127.0.0.1:1239" disconnected or paused, terminating or descheduling sync folders
06-21 13:20:47:447 179577 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 401 ""
06-21 13:20:47:447 179577 OCC::ConnectionValidator::slotAuthFailed: QNetworkReply::NetworkError(AuthenticationRequiredError) "Host requires authentication"
06-21 13:20:47:447 179577 OCC::ConnectionValidator::slotAuthFailed: ******** Password is wrong!
```

**Comment by guruz** [comment]
If I change getHTTPCode to return 403 it works better.
It shows "Forbidden (OCA\DAV\Connector\Sabre\Exception\PasswordLoginForbidden" in the desktop client in both wizard and if the account is already setup.

**Pull request merged**
