### PR TITLE
[stable10] run phan on php7.0 - 7.2

### PR DESCRIPTION
**Pull request by patrickjahns**
## Description
Added 2 permutations for phan, to run it with php 7.0, 7.1 and 7.2

## Motivation and Context
phan analyzes the AST - which gets compiled from the underlying php. Running in the different versions, ensures that methods / interface are staying compatible with the different php runtimes

## How Has This Been Tested?
- 🤖 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by phil-davis** [comment]
Acronym translation:
For me, AST - Asynchronous System Trap (my OpenVMS system call days)
Fr PHP, AST - Abstract Syntax Tree

**Review by phil-davis — APPROVED** [review]
A good thing. I guess you will forward-port?

**Comment by patrickjahns** [comment]
> A good thing. I guess you will forward-port? 

Yes was working on that in #32493 

Errors is related to memached not being in php7.2 image

**Comment by patrickjahns** [comment]
RFC for the AST https://wiki.php.net/rfc/abstract_syntax_tree :-)

**Comment by patrickjahns** [comment]
@owmclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
