### PR TITLE
[Tests-Only] Bug reproduce 36920

### PR DESCRIPTION
**Pull request by kiranparajuli589**
## Description
Issue stated inside #36920 is added as acceptance test scenario

## Related Issue
-  #36920 #36821

## Motivation and Context
track existing bug!

## How Has This Been Tested?

- :robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by kiranparajuli589** [comment]
Add error assertion support!!

**Comment by mmattel** [comment]
Adding @phil-davis as he was in #36821

**Review by phil-davis — APPROVED** [review]
I changed a few words in the step text (putting in `the` and so on).
The code looks good.

**Comment by mmattel** [comment]
@kiranparajuli589 pls run `make test-php-style-fix` to fix the complains from CI regarding code style

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
I will override the silly codecov result when I get my laptop out...

**Pull request merged**
