### PR TITLE
Add api acceptance test for checking that the sensitive data are not exposed by ocs api on share

### LINKED ISSUE #35232: Acceptance test: Don't expose hashed password in OCS api
Part of #35207

Add acceptance test to check the fields that are private are not shown through the sharing API.

Test for #34691

### PR DESCRIPTION
**Pull request by dpakach**
## Description

Add API acceptance test to check if the OCS API exposes sensitive information.

## Related Issue

- Fixes #35232

## Motivation and Context

This was a newly added change in #34691

## How Has This Been Tested?

:robot: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Review by skshetry — COMMENTED** [review]
:+1:

**Review by paurakhsharma — COMMENTED** [review]
Looks good to me :+1:

**Review by individual-it — APPROVED** [review]

**Comment by individual-it** [comment]
could add tests when getting the shares by api https://doc.owncloud.com/server/10.1/developer_manual/core/ocs-share-api.html#get-all-shares
but can be done in new PR

**Comment by dpakach** [comment]
Backport on #35251

**Pull request merged**
