### PR TITLE
[stable10] Bye bye Dropbox v1

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of #28073

### CODE REVIEW

**Comment by tomneedham** [comment]
What do we do with existing v1 mounts that are configured? Do they stay in the database? Should we clean these up? Maybe log a message that they have been cleaned up for $user and will need to be recreated in v2 app?

**Comment by phil-davis** [comment]
Is there an algorithm that can take V1 mount settings as input and produce valid V2 settings as output?
Then it could be upgraded automagically.
Or is V2 too much different?

**Comment by tomneedham** [comment]
> Is there an algorithm that can take V1 mount settings as input and produce valid V2 settings as output?

@Hemant-Mann ? 

Obviously this would require installing the v2 app - but the converted mounts could be ready and waiting if compatible?

**Comment by Hemant-Mann** [comment]
@tomneedham Yes there is way
Dropbox v1 used oauth1 which had **token** and **token_secret**
According to dropbox api documentation we can use these to obtain access_token using app id and secret
[https://www.dropbox.com/developers/documentation/http/documentation#auth-token-from_oauth1](https://www.dropbox.com/developers/documentation/http/documentation#auth-token-from_oauth1)

I think We can look for old dropbox mounts and convert them to Dropbox v2 mounts

Thoughts @PVince81?

**Comment by tomneedham** [comment]
Maybe just add this as something that is performed on install for the new app? Since it requires the new app code anyway - keeps it separated.

**Comment by phil-davis** [comment]
Yes, old mount data will just sit in the system waiting for the new V2 app to be enabled, then "magically" get converted.

I guess the old mount points would stay visible (and not working) on the system in the transition period, so users could delete those if they wish without ever enabling the new V2 app.

**Comment by PVince81** [comment]
We should still properly test this to make sure that our current APIs are still able to read the old Dropbox mount configs even when the old Dropbox mount code is gone.

**Comment by PVince81** [comment]
I seem to remember seeing a comment from @hodyroff somewhere suggesting to keep this until 10.0.5 to give people enough time to migrate. Sounds like a good plan.

**Comment by PVince81** [comment]
Moving to "planned" for 10.0.5

**Comment by DeepDiver1975** [comment]
removing my assignment - merge once you agree

**Comment by PVince81** [comment]
Before we merge this, I'd like to have https://github.com/owncloud/core/pull/26539 finished and merged as it would prevent breaking an instance whenever a storage backend is suddenly missing.

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! This pull request is being rebased automatically. Please DO NOT push while rebase is in progress or your changes would be lost!

**Comment by ownclouders** [comment]
Automated rebase failed! Please rebase your pull request manually via the command line.

Error:
```Command '['git', 'clone', '--depth', '1', 'rebase', '/tmp/tmpmvg6o1w4']' returned non-zero exit status 128.```

**Pull request merged**
