### PR TITLE
Do not return not availlable users

### LINKED ISSUE #20588: LDAP: users being mapped, although they do not pass user filter
### Steps to reproduce
1. Configure a user filter that rules out some users, which are members of a group. Important detail might(not necessarily) be that it happens when "member" is used as user-group-association attribute, but only because i did not test otherwise.
2. Go to users tab and click on the group
3. Check oc_ldap_user_mappings table

Backtrace to when the first undesired mapping happens:

```
Array
(
    [0] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/apps/user_ldap/lib/access.php
            [line] => 405
            [function] => dn2ocname
            [class] => OCA\user_ldap\lib\Access
            [type] => ->
        )

    [1] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/apps/user_ldap/group_ldap.php
            [line] => 579
            [function] => dn2username
            [class] => OCA\user_ldap\lib\Access
            [type] => ->
        )

    [2] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/lib/private/group/group.php
            [line] => 194
            [function] => usersInGroup
            [class] => OCA\user_ldap\GROUP_LDAP
            [type] => ->
        )

    [3] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/lib/private/group/manager.php
            [line] => 312
            [function] => searchUsers
            [class] => OC\Group\Group
            [type] => ->
        )

    [4] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/settings/controller/userscontroller.php
            [line] => 227
            [function] => displayNamesInGroup
            [class] => OC\Group\Manager
            [type] => ->
        )

    [5] => Array
        (
            [function] => index
            [class] => OC\Settings\Controller\UsersController
            [type] => ->
        )

    [6] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/lib/private/appframework/http/dispatcher.php
            [line] => 159
            [function] => call_user_func_array
        )

    [7] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/lib/private/appframework/http/dispatcher.php
            [line] => 89
            [function] => executeController
            [class] => OC\AppFramework\Http\Dispatcher
            [type] => ->
        )

    [8] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/lib/private/appframework/app.php
            [line] => 108
            [function] => dispatch
            [class] => OC\AppFramework\Http\Dispatcher
            [type] => ->
        )

    [9] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/lib/private/appframework/routing/routeactionhandler.php
            [line] => 45
            [function] => main
            [class] => OC\AppFramework\App
            [type] => ::
        )

    [10] => Array
        (
            [function] => __invoke
            [class] => OC\AppFramework\routing\RouteActionHandler
            [type] => ->
        )

    [11] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/lib/private/route/router.php
            [line] => 282
            [function] => call_user_func
        )

    [12] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/lib/base.php
            [line] => 855
            [function] => match
            [class] => OC\Route\Router
            [type] => ->
        )

    [13] => Array
        (
            [file] => /home/blizzz/owncloud/dev/master/index.php
            [line] => 39
            [function] => handleRequest
            [class] => OC
            [type] => ::
        )

)

```

Initially found by @ryno83, blocks https://github.com/owncloud/core/pull/18212
### Expected behaviour

Only those users are being mapped that actually pas User (or Login) filter.
### Actual behaviour

Even users are being mapped, that would not pass user filter.
### Server configuration

**ownCloud version:** git master, and back to stable8.1

**Are you using an external user-backend, if yes which one:** LDAP
#### LDAP configuration

```
+-------------------------------+-----------------------------------------------------------------------------------------+
| Configuration                 |                                                                                         |
+-------------------------------+-----------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                       |
| hasPagedResultSupport         |                                                                                         |
| homeFolderNamingRule          |                                                                                         |
| lastJpegPhotoLookup           | 0                                                                                       |
| ldapAgentName                 | uid=owncloudagent,ou=Users,dc=owncloud,dc=bzoc                                          |
| ldapAgentPassword             | ***                                                                                     |
| ldapAttributesForGroupSearch  |                                                                                         |
| ldapAttributesForUserSearch   | mail;displayname;uid                                                                    |
| ldapBackupHost                | ldap://ldap.owncloud.bzoc                                                               |
| ldapBackupPort                | 7770                                                                                    |
| ldapBase                      | dc=owncloud,dc=bzoc                                                                     |
| ldapBaseGroups                | ou=Drawers,dc=owncloud,dc=bzoc                                                          |
| ldapBaseUsers                 | dc=owncloud,dc=bzoc                                                                     |
| ldapCacheTTL                  | 20                                                                                      |
| ldapConfigurationActive       | 1                                                                                       |
| ldapEmailAttribute            | mail                                                                                    |
| ldapExperiencedAdmin          | 1                                                                                       |
| ldapExpertUUIDGroupAttr       |                                                                                         |
| ldapExpertUUIDUserAttr        |                                                                                         |
| ldapExpertUsernameAttr        | uid                                                                                     |
| ldapGroupDisplayName          | cn                                                                                      |
| ldapGroupFilter               | (&(|(objectclass=ownCloudGroup)))                                                       |
| ldapGroupFilterGroups         |                                                                                         |
| ldapGroupFilterMode           | 0                                                                                       |
| ldapGroupFilterObjectclass    | ownCloudGroup                                                                           |
| ldapGroupMemberAssocAttr      | member                                                                                  |
| ldapHost                      | ldap.owncloud.bzoc                                                                      |
| ldapIgnoreNamingRules         |                                                                                         |
| ldapLoginFilter               | (&(&(|(objectclass=ownCloudUser)))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                         |
| ldapLoginFilterEmail          | 1                                                                                       |
| ldapLoginFilterMode           | 0                                                                                       |
| ldapLoginFilterUsername       | 1                                                                                       |
| ldapNestedGroups              | 0                                                                                       |
| ldapOverrideMainServer        |                                                                                         |
| ldapPagingSize                | 500                                                                                     |
| ldapPort                      | 7770                                                                                    |
| ldapQuotaAttribute            |                                                                                         |
| ldapQuotaDefault              |                                                                                         |
| ldapTLS                       | 0                                                                                       |
| ldapUserDisplayName           | displayname                                                                             |
| ldapUserFilter                | ( &( |( objectclass=ownCloudUser) ) (!(uid=zombie*)) )                                  |
| ldapUserFilterGroups          |                                                                                         |
| ldapUserFilterMode            | 0                                                                                       |
| ldapUserFilterObjectclass     | ownCloudUser                                                                            |
| ldapUuidGroupAttribute        | auto                                                                                    |
| ldapUuidUserAttribute         | auto                                                                                    |
| turnOffCertCheck              | 0                                                                                       |
| useMemberOfToDetectMembership | 0                                                                                       |
+-------------------------------+-----------------------------------------------------------------------------------------+

```

### PR DESCRIPTION
**Pull request by PVince81**
Resent PR https://github.com/owncloud/core/pull/20616 from @ryno83, rebased.

Fixes https://github.com/owncloud/core/issues/20588

@owncloud/ldap @butonic

### CODE REVIEW

**Comment by PVince81** [comment]
Potential corner case to clarify: https://github.com/owncloud/core/issues/20588#issuecomment-162555167

**Comment by PVince81** [comment]
@jvillafanez can you help review ? see original PR for details

**Comment by jvillafanez** [comment]
There are a case that I don't know how it will / should behave:

* https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/Access.php#L184-L187 returns an empty array at that point. Should it behave as an error (as when the rest return `false`, or just go with an empty result? However, that function always return an array with values in case of success.

Is this the only place where this change is needed? I've only checked the changes and a few related files but not all the code.

About the corner case, @blizzz is right, but on the other hand the login filter should always include the user one: it should be possible to list all the users, but only a set of them (or all) should be able to login

**Comment by DeepDiver1975** [comment]
please move this to user_ldap

**Comment by jvillafanez** [comment]
Moved to https://github.com/owncloud/user_ldap/pull/12

**Pull request closed without merging**
