### PR TITLE
Add versions tab to files sidebar

### PR DESCRIPTION
**Pull request by PVince81**
TODO
- [x] sidebar tab, models, collection, view
- [x] fix previews
- [x] "revert" action
- [x] styling
- [x] pagination
- [x] make sure that actions update the VersionCollection so that the UI reflects the latest change
- [x] test mimetype preview
- [x] test image preview

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] BUG: don't show versions for folders

**Comment by PVince81** [comment]
- [ ] BUG: load on scroll doesn't work properly

**Comment by jancborchardt** [comment]
Looks good, except that Versions should be the rightmost tab. Activity, Sharing, Versions, in that order. Activity open by default (unless you opened the sidebar direclty by clicking Sharing or Versions of course).

**Comment by PVince81** [comment]
Dammit... once again an order issue. This depends on the loading order of the apps.
I know you hate it that plugins can specify a sort order but I don't see how we can solve this without hard-coding id strings in core, which is even worse.

**Comment by PVince81** [comment]
General ordering problem discussed here: https://github.com/owncloud/core/issues/18280#issuecomment-137346384

**Comment by PVince81** [comment]
I will add back the "More versions" button as I won't have time to make "scroll to load more" to work properly. The tricky part here is that the scrollbar isn't on the tab but on the main container, so the events have to come from there.

**Comment by karlitschek** [comment]
i think a more versions button us totally cool fir now

**Comment by PVince81** [comment]
I added back the "More versions..." button and fixed the spinner position.

Next up:
- [ ] TODO: writing JS unit tests for the versions tab + collection

**Comment by PVince81** [comment]
I'm done with the JS unit tests.

This is ready for review @schiesbn @nickvergessen @jancborchardt @rullzer @MorrisJobke

**Comment by PVince81** [comment]
also CC @blizzz here you'll find more examples how to wire up Backbone collections/models to the view

**Comment by karlitschek** [comment]
awesome :+1:

**Comment by karlitschek** [comment]
someone else want's to review this? I would love to get this in. 
@blizzz @jancborchardt @schiesbn @nickvergessen

**Comment by MorrisJobke** [comment]
Tested and works. Unit tests also pass locally (JS & PHP) :+1:

**Pull request merged**
