### PR TITLE
Add Versions app header to config.sample.php

### PR DESCRIPTION
**Pull request by nickvergessen**
@PVince81 @cmonteroluque 
Up to you, 9.0.0 or 9.0.1

Would be nice to have it, but no real issue when the header is missing some more days.

### CODE REVIEW

**Comment by RealRancor** [comment]
Backport of https://github.com/owncloud/core/issues/22776

MIT licensed (if thats needed at all)

**Comment by MorrisJobke** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by RealRancor** [comment]
Cross-posting from https://github.com/owncloud/core/pull/22802#issuecomment-191825061 (which is already merged):

> Thats a simple comment in a sample config file which is not even used so why discuss 9.0.0 vs. 9.0.1? :-)

**Pull request merged**
