### PR TITLE
Add caldav and carddav tests to drone

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Add caldav-carddav setup and test run steps to drone, add matrix entries.

## Motivation and Context
Get more tests on drone.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Test infrastructure

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by patrickjahns** [comment]
Personally - I prefer to limit this to one matrix job and rather having more pipeline steps for it.

**Comment by phil-davis** [comment]
OK - easy to do...

**Comment by phil-davis** [comment]
Hmmm - I thought it would be easy to do. But I have a single setup of the test environment then try to run each of the 4 sets of tests one after the other. I guess at the end of the first tests, the initial state has been lost (i.e. there are calendars/cards... left behind), and so the next set of test scenarios runs in an unexpected environment and fails.

It is easier to have 4 separate drone matrix jobs to run each of the 4 test scenarios separately.

**Comment by DeepDiver1975** [comment]
@phil-davis conflicting after merge of #31272

**Comment by phil-davis** [comment]
Yes, I tried to take a different approach towards what @patrickjahns was suggesting, but did not get it to work. I will back that out and resolve the conflicts here. Then people can comment again.

**Pull request closed without merging**
