### PR TITLE
[stable8.1] Trigger "apprendered" event in users page

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/17946 to stable8.1

@karlitschek please confirm backport

Please review @SergioBertolinSG @DeepDiver1975 @blizzz @MorrisJobke @jancborchardt

### CODE REVIEW

**Comment by PVince81** [comment]
Note: severity was medium, so not sure if 8.1.1 is appropriate.
See original report https://github.com/owncloud/core/issues/17945

**Comment by blizzz** [comment]
Also good :+1:

**Comment by SergioBertolinSG** [comment]
Tested on stable8.1 + this PR.
I am seeing the same behaviour, opening the users page doesn't show the search box.

**Comment by karlitschek** [comment]
:+1: please backport

**Comment by MorrisJobke** [comment]
Merged as it was discussed here: https://github.com/owncloud/core/issues/17945#issuecomment-125939898

**Pull request merged**
