### PR TITLE
Use the displayname of the groups

### PR DESCRIPTION
**Pull request by jvillafanez**
## Description
Use the displayname name of the group instead of the group id in multiple places. Currently checked in the user's list and in the personal settings.

Note that for regular (local) groups, the id and the displayname is the same, so there shouldn't be any noticeable changes.

The LDAP app will rely on this for further functionality (changes for LDAP in progress)

## Related Issue
https://github.com/owncloud/enterprise/issues/5071

## Motivation and Context
The group id must be immutable, as it is the user id. The group displayname should be shown instead, as the displayname can be changed at any point.

## How Has This Been Tested?
Checked along with a specific patch for the user_ldap app.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by phil-davis** [comment]
Just a note for reference: basic code to allow groups to have a display name was added in #26750
In practice, in core, the display name has always been the same as the Group Id.

**Review by phil-davis — COMMENTED** [review]
Looks OK to me, and all tests pass. So we do not have any obvious mixup of group id and group name for core. And this is more progress supporting the ability to have the display name of a group different from the group id.

Needs review by some developer(s).

**Comment by phil-davis** [comment]
What happens about a changelog entry?
In a way, this is a no-external-change refactoring for core. So does it require a changelog?

**Comment by jvillafanez** [comment]
I'll add a bugfix entry taking into account that this is mainly for ldap.

**Review by phil-davis — APPROVED** [review]
Changelog looks good. Let's merge this.

**Pull request merged**
