### PR TITLE
Comments API is missing hook/event to allow other apps to register valid entities

### PR DESCRIPTION
**Pull request by nickvergessen**
### Steps to reproduce
1. Write a new app that wants to store comments (or change `files` to `files2` everywhere in the [comments js files](https://github.com/owncloud/core/tree/master/apps/comments/js) )
2. Send a request to the comments dav endpoint and ask for comments
### Expected behaviour

`200 OK` - Comments should be delivered
### Actual behaviour

`404 Not Found`

The problem is, that the root collection is hardcoded to files:
https://github.com/owncloud/core/blob/b1c8b077b089f2182e98d24282d4db7913df9e00/apps/dav/lib/comments/rootcollection.php#L96-L103

So instead of being able to use the dav endpoint apps would need to write their own endpoint.
### Second problem

This also allows people to comment on files, although the comments app is disabled :speak_no_evil:  
This is because the entity is not registered by the comments app, but by the dav app (always enabled).

cc @blizzz @DeepDiver1975

### CODE REVIEW

**Comment by blizzz** [comment]
> This also allows people to comment on files, although the comments app is disabled

The app provides just the UI. Otherwise, the feature is just there. We should not check whether the app is installed, but could introduce a config switch to turn off comments. So far there was no requirement about it. The app would need to react on this as well.

**Comment by blizzz** [comment]
> The problem is, that the root collection is hardcoded to files:

That was a known limitation, due to lack of time with the freeze coming closer.

This looks like a nice solution :)

**Comment by nickvergessen** [comment]
> The app provides just the UI. Otherwise, the feature is just there. We should not check whether the app is installed, but could introduce a config switch to turn off comments. So far there was no requirement about it. The app would need to react on this as well.

I think allowing comments without the UI is really a corner case, so if someone does want to do that, he can do that, by adding an app that just has the `app.php` call to register the entity?

**Comment by blizzz** [comment]
> I think allowing comments without the UI is really a corner case, so if someone does want to do that, he can do that, by adding an app that just has the app.php call to register the entity?

Ack. This requires also that comments app should be of the type "filesystem".

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/blob/043625ee522357e25bb786c4b439c90ab21bbfd1/remote.php#L121-L122
```php
	OC_App::loadApps(array('authentication'));
	OC_App::loadApps(array('filesystem', 'logging'));
```

Currently it's `logging` so that should be fine (and also worked in my test with my third app, where I had no type before and logging made it work).

**Comment by nickvergessen** [comment]
Fixed the failing tests, should be good to go now

**Comment by nickvergessen** [comment]
@DeepDiver1975 can you have a look? this would be nice to have for 9.0

**Comment by PVince81** [comment]
Let's add support to register other entities in 9.1.

**Comment by nickvergessen** [comment]
Rebased, adjusted versions to `@since 9.1.0`

Would be nice to get this in soon, so other apps can start making use of it.

**Comment by georgehrke** [comment]
I think this needs yet another rebase

**Comment by nickvergessen** [comment]
Rebased

**Comment by PVince81** [comment]
Comments still work, code looks fine :+1:

**Comment by PVince81** [comment]
@georgehrke @blizzz @rullzer @schiesbn second review ?

**Comment by georgehrke** [comment]
👍

**Comment by nickvergessen** [comment]
Will have a look at the failing tests, they seem to be related

**Comment by nickvergessen** [comment]
Okay, after @PVince81 s rebase the public file wsa not PSR-4 but the old loader was already removed. Fixed by moving it to PSr-4

**Pull request merged**
