### PR TITLE
Use jsqueeze

### LINKED ISSUE #13052: JSMin minifier is non-free (suggest JSqueeze or JShrink as alternatives)
As explained at https://github.com/owncloud/core/pull/11430#issuecomment-68317924 , the JSMin minifier which is used by that PR is non-free according to [FSF](https://www.gnu.org/licenses/license-list.html#JSON), [Debian](https://lists.debian.org/debian-lint-maint/2013/01/msg00153.html), and [Fedora](https://fedoraproject.org/wiki/Licensing:Main#Bad_Licenses). Also, its original upstream developer [abandoned it years ago and explicitly recommends other alternatives](https://github.com/rgrove/jsmin-php/blob/master/README.md). mrclay is maintaining the copy in his repo, but probably not as actively as the newer alternatives.

I [ran some benchmarks](https://www.happyassassin.net/2014/12/29/adventures-in-php-web-asset-minimization/) which indicated JSqueeze might be the best replacement, at least from a numbers perspective. It's also actively maintained by a well-known developer. Its [lack of namespacing](https://github.com/tchwork/jsqueeze/issues/11) is a bit of a pain for distros but in the worst case (if they don't take my suggestion to namespace) can be dealt with.

More importantly, though, I managed to get a hacky build of master up and running and tested it with JSqueeze, and it, er, [doesn't work](https://github.com/tchwork/jsqueeze/issues/14) (for me, anyway, confirmation would be welcome). Upstream seems fairly responsive to bug reports, so I'm hoping they'll get to that one soon.

The other alternative that looked decent to me was [JShrink](https://github.com/tedious/JShrink). It's currently-maintained, namespaced, travis-ified, psr-0 compliant, lots of buzzword boxes. It doesn't perform as well as JSqueeze in terms of speed or file size, but it *does* work with OC for basic use (I just tested), which is a significant advantage.

I'll note an ancillary benefit, here: pulling in mrclay/minify just to get a JavaScript minifier is kind of atomic-weapon-nutcracker stuff. As my blog post (linked earlier) points out, it's a sort of poor man's Assetic with eight different CSS/JS minification implementations and a whole bunch of other nutty stuff in it. Switching to JShrink or JSqueeze would allow us to just have a JavaScript minifier, not a JavaScript minifier tied to three other JavaScript minifiers and lord knows what else. As it stands, OC 8 will be shipping (by my count) four CSS minifiers (the three in mrclay/minify, plus the one it actually *uses*), two full PHP JavaScript minifiers, and two different Closure Compiler wrappers/interfaces (and that's not even counting any others lying around in the source tree...)

I can send PRs for switching to either JSqueeze or JShrink pretty easily - the changes to OC itself are trivial, then it's just a 3rdparty commit that drops mrclay/minify and pulls in the one we want - but it seemed prudent to wait for a response from JSqueeze to my bug report.

Edit: oh, for the record, a drawback of JShrink is that Assetic doesn't currently ship a filter for it. There's a [github project which adds one](https://github.com/nibsirahsieu/SalvaJshrinkBundle) - for my test I just dropped that straight into the Assetic tree and it worked fine, so it could be sent upstream pretty easily if they'd take it. But they do have a JSqueeze filter already, so it's one less step there.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes https://github.com/owncloud/core/issues/13052

requires https://github.com/owncloud/3rdparty/pull/199

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Please review and test @rperezb @MorrisJobke @LukasReschke @icewind1991 THX

**Comment by MorrisJobke** [comment]
Tested and works. Also fine with alreay enabled asset pipelining. :+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
3rdparty submodule updated after merge of owncloud/3rdparty#199

**Comment by SergioBertolinSG** [comment]
How can we test this besides checking that the interface is not broken?
@owncloud/qa

**Comment by DeepDiver1975** [comment]
> How can we test this besides checking that the interface is not broken?

monitoring the browser console while loading various pages ... no js error is allowed to pop up

**Comment by MorrisJobke** [comment]
> monitoring the browser console while loading various pages ... no js error is allowed to pop up

While `asset-pipeline.enabled` is set to true in the config.php

**Comment by SergioBertolinSG** [comment]
Using chrome, no problems found.

Just a recurrent error when opening and closing textfiles, no related I guess.

```
GET http://HOST/index.php/core/preview.png?file=%2Fnetworkjobs.cpp&c=1444375488&x=32&y=32&forceIcon=0 404 (Not Found)
```

**Comment by MorrisJobke** [comment]
> Just a recurrent error when opening and closing textfiles, no related I guess.

Yes. Feel free to open a ticket if this is still a reproducable problem

**Pull request merged**
