### PR TITLE
update icewind/smb to 1.0.5

### LINKED ISSUE #22219: Update icewind smb to latest version
@icewind1991 can you tag a release (1.0.5) to include https://github.com/icewind1991/SMB/pull/41 ?

Then we can update the library in files_external to point to that version.

Tagging as bug as it fixes some known bugs.

### PR DESCRIPTION
**Pull request by icewind1991**
Mainly gives improved error messages and detection

Fixes #22219 

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks, let me do a quick test (and CI will help too)

**Comment by PVince81** [comment]
Seems to work fine :+1: 

Let's see what the SMB CI run says.

**Comment by PVince81** [comment]
looks like it passed, nice!

**Comment by PVince81** [comment]
Needs second reviewer @Xenopathic

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
