### PR TITLE
[8.2] Don't lock if we're only reading cache metadata

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of #20053

### CODE REVIEW

**Comment by PVince81** [comment]
I'm running smashbox tests now.

This will need a second review @karlitschek @nickvergessen

**Comment by PVince81** [comment]
@DeepDiver1975

**Comment by PVince81** [comment]
Smash tests passed. Did some manual testing renaming folders, seems to work fine. :+1:

**Comment by PVince81** [comment]
@nickvergessen can you do the second review ? Thanks

**Comment by nickvergessen** [comment]
I don't feel to comfortable with such changes, but works :+1:

**Pull request merged**
