### PR TITLE
Fix size propagation over shared storage boundary

### PR DESCRIPTION
**Pull request by PVince81**
Fix size propagation for https://github.com/owncloud/core/issues/14596
- [x] propagate sizes over shared storage boundary
- [x] unit test

@icewind1991 FYI

### CODE REVIEW

**Comment by PVince81** [comment]
@icewind1991 I wonder if at some point we should move size calculation to the propagator classes

**Comment by PVince81** [comment]
It turns out size propagation is easy but etag/mtime propagation is **hard**.

The "Updater" class is based on the current user's view, so it's not possible to make it work on another user's view without setupFS gymnastics... I also tried to instantiate a ChangePropagator from the SharedScanner, but that's another code path and isn't triggered.

@icewind1991 any suggestion how to make this work ?
If it's too complicated I might split this into a separate PR so we can at least get the size stuff in...

**Comment by PVince81** [comment]
Keep in mind that the fix needs to be backportable to OC 7...

**Comment by PVince81** [comment]
Let's keep this here only for the size propagation.
Etag propagation is another story, to be looked into separately: https://github.com/owncloud/core/issues/14726

**Comment by luizluca** [comment]
@PVince81 , I just tested and it works for me :-)

**Comment by PVince81** [comment]
Great to hear that, thanks for testing.

I still need to write a unit test to finish this PR.

**Comment by PVince81** [comment]
...that assuming that @icewind1991 is fine with the approach I used.

**Comment by PVince81** [comment]
Just had a go at a unit test locally and the bad news is that it seems to propagate wrong.

Whenever a share recipient changes a file, the size should be propagated to the owner's root, NOT to the recipient's root. The propagation must stop at the shared folder and not go further. It doesn't seem to be the case at the moment. This means that the size would be counted twice, once for each user, which is wrong.

**Comment by PVince81** [comment]
Hmmm, I tried this manually and the propagation seems to work properly. The recipient's root size stays the same. Maybe something is wrong in the unit test then.

**Comment by PVince81** [comment]
Ok fixed the unit test.
The mistake is that I used `getFileInfo($path)` which automatically includes the size of mount points.
The proper call is `getFileInfo($path, false)` to get what's in the DB.

**Comment by PVince81** [comment]
Test steps are here: https://github.com/owncloud/core/issues/14596#issuecomment-77389915

**Comment by PVince81** [comment]
Please review @icewind1991 @DeepDiver1975 @MorrisJobke @nickvergessen @schiesbn 

The patch was tested by the original reporter here https://github.com/owncloud/core/pull/14720#issuecomment-77590395

**Comment by icewind1991** [comment]
Looks good :+1:

**Comment by MorrisJobke** [comment]
Tested & works:+1:

**Comment by PVince81** [comment]
@karlitschek backport to OC 7 and OC 8 ? (for 7.0.7 and 8.0.3)
Size propagation / quota calculation is broken since OC 7 with shares

**Comment by karlitschek** [comment]
Please backport once 8.0.2 and 7.0.5 are done :-) :+1:

**Comment by PVince81** [comment]
Preparing backport PRs now.

**Comment by PVince81** [comment]
stable8: https://github.com/owncloud/core/pull/14860
stable7: https://github.com/owncloud/core/pull/14861

**Pull request merged**
