### PR TITLE
[stable9.1] Prevent PHP7 GC to kill normalizedPathCache too early

### PR DESCRIPTION
**Pull request by PVince81**
attempt 1

### CODE REVIEW

**Comment by PVince81** [comment]
for https://github.com/owncloud/core/issues/22370

**Comment by enoch85** [comment]
So this would remove that message if I patch it on my system with PHP 7? I'm prepared to test on my production system if it doesn't break anything else.

**Comment by enoch85** [comment]
Or, btw, I can test it on a VM. anyone else who want's to try you can download it here: https://www.techandme.se/pre-configured-owncloud-installaton/

**Comment by Webbeh** [comment]
I'll check this tomorrow to see if it makes any difference.

**Comment by PVince81** [comment]
The patch itself shouldn't affect any existing functionality. It only declares an addtional variable that stores a reference to the normalizedPathCache to keep it in memory longer.

The tricky part as usual is finding scenarios where the problem happens. On my setup I can't reproduce the issue often enough to confirm whether this fixes it. So if you guys have setups where it happens very often then you might be able to confirm it the fix works! Thanks!

**Comment by enoch85** [comment]
Added the patch, let's wait and see...

**Comment by enoch85** [comment]
1. Aded the patch
2. Downloaded a file from a public shared link: https://cloud.techandme.se/index.php/s/MUl79ovm7Ifo4kG
3. Got this in the logs:

```
{"reqId":"A6ivPmw2MUS47+O+zgVy","remoteAddr":"192.168.4.201","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-11-26T16:36:17+01:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
```

**Comment by enoch85** [comment]
Nope, it's still there:

```
[Sat Nov 26 17:50:52.871048 2016] [:error] [pid 25309] [client 95.218.86.181:46056] PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in /var/www/nextcloud/lib/private/Files/Filesystem.php:773\nStack trace:\n#0 /var/www/nextcloud/lib/private/Files/View.php(2037): OC\\Files\\Filesystem::normalizePath('/daniel@en0ch.s...')\n#1 /var/www/nextcloud/lib/private/Files/View.php(1154): OC\\Files\\View->unlockFile('/_VMs/Nextcloud...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown in /var/www/nextcloud/lib/private/Files/Filesystem.php on line 773, referer: https://cloud.techandme.se/index.php/s/lTjoMr5smSYHIiM
```

**Comment by RealRancor** [comment]
@enoch85 Not quite sure if you can compare NextCloud vs. ownCloud here as you seems to have NextCloud running on https://cloud.techandme.se/status.php

**Comment by Webbeh** [comment]
No apparent change with this patch, still the same errors.

**Comment by enoch85** [comment]
@RealRancor Yes, you are right. But this bug isn't fixed there either, and the codebase are the same.

This is :-1: from me anyway. Doesn't change anything.

**Comment by RealRancor** [comment]
> and the codebase are the same.

Not exactly as you can see here 😄 :

https://github.com/owncloud/core/commits/v9.1.1/lib/private/Files/View.php

vs.

https://github.com/nextcloud/server/commits/v10.0.1/lib/private/Files/View.php

but i guess this doesn't matter here.

**Comment by Webbeh** [comment]
Can't really compare two different versions of the code either can you ? :)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: RealRancorSent: Sunday, 27 November 2016 17:52To: owncloud/coreReply To: owncloud/coreCc: Nicolas Glassey; CommentSubject: Re: [owncloud/core] [stable9.1] Prevent PHP7 GC to kill normalizedPathCache too early (#26725)
and the codebase are the same.

Not exactly as you can see here 😄 :
https://github.com/owncloud/core/commits/v9.1.1/lib/private/Files/View.php
vs.
https://github.com/nextcloud/server/commits/v10.0.1/lib/private/Files/View.php
but i guess this doesn't matter here.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/owncloud/core","title":"owncloud/core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/owncloud/core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@RealRancor in #26725: \u003e and the codebase are the same.\r\n\r\nNot exactly as you can see here 😄 :\r\n\r\nhttps://github.com/owncloud/core/commits/v9.1.1/lib/private/Files/View.php\r\n\r\nvs.\r\n\r\nhttps://github.com/nextcloud/server/commits/v10.0.1/lib/private/Files/View.php\r\n\r\nbut i guess this doesn't matter here."}],"action":{"name":"View Pull Request","url":"https://github.com/owncloud/core/pull/26725#issuecomment-263132979"}}}

**Comment by PVince81** [comment]
Ok, thanks... It was worth a try. Will need something stronger.

**Pull request closed without merging**
