### PR TITLE
Changed how _put key values are processed in API function editUser()

### PR DESCRIPTION
**Pull request by hanzwo**
Changed how _put key values are processed in API function editUser().

## Description
The param $parameters in the function editUser() has key ['_put']. If you call the function with multiple keys to update, the function will fail with errorcode 997.
I changed this to a foreach that loops through the key values pairs of key ['_put'].

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
this breaks many unit tests - afaik because the behavior is changed - we cannot break the api behavior :-1: 

bildschirmfoto von 2017-04-10 16-50-31

**Comment by hanzwo** [comment]
And what if I make backward compatible?

**Comment by DeepDiver1975** [comment]
> And what if I make backward compatible?

give it a try :wink:

**Comment by PVince81** [comment]
Failing test: `OCA\Provisioning_API\Tests\UsersTest.testEditUserRegularUserSelfEditChangeQuota`

**Comment by PVince81** [comment]
@hanzwo please fix the failing test

**Pull request closed without merging**
