### PR TITLE
Allow occ install on OS X - same behaviour as web setup

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @LukasReschke

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Can you please elaborate why we need this? We don't support Mac - so it's valid to not allow installation. Do I miss anything? THX

**Comment by LukasReschke** [comment]
> Can you please elaborate why we need this? We don't support Mac - so it's valid to not allow installation. Do I miss anything? THX

This is for running the unit tests required. autotest.sh fails hard otherwise. While installation via web is still possible otherwise. This should not hard-fail.

Works :+1:

**Comment by DeepDiver1975** [comment]
Whatever you Mac fan boys want :+1:

**Pull request merged**
