### PR TITLE
[stable7] Fix size propagation over shared storage boundary

### PR DESCRIPTION
**Pull request by PVince81**
Backport of #14720 to stable7

@icewind1991 @nickvergessen @MorrisJobke

(there were merge conflicts)

### CODE REVIEW

**Comment by PVince81** [comment]
Had a quick manual test, it works.

I'll fix the unit test.

**Comment by PVince81** [comment]
Having trouble with the unit tests.
It looks like on stable7 there is a stat cache issue. When re-reading the filesize after simulated upload, it still returns the old size. I need to add an explicit `clearstatcache($fullPath)` here https://github.com/owncloud/core/blob/stable7/lib/private/files/storage/local.php#L113 to make it work.

I'll try and find out why it works on master... maybe something else needs backporting.

**Comment by PVince81** [comment]
Okay, it seems that backporting https://github.com/owncloud/core/pull/10881 would fix it.
Even though that linked PR is about `clearstatcache` for mtime, it has the side effect of also making it work for the size...

**Comment by PVince81** [comment]
I have now backported the commits from https://github.com/owncloud/core/pull/10881#issuecomment-78916964 here, let me know if this is ok.

**Comment by karlitschek** [comment]
backport is fine. :+1:

**Comment by PVince81** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
A Jenkins PR even for stable7 ?! Pffff...
Maybe I should stop pushing furiously.

Here it is: https://github.com/owncloud/core/pull/14934

**Comment by PVince81** [comment]
Please review

**Comment by PVince81** [comment]
Test steps here: https://github.com/owncloud/core/issues/14596#issuecomment-77389915

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
