### PR TITLE
check if mimetype is set - fixes #13452

### LINKED ISSUE #13452: [encyrption] error during initial encryption with part file existing
```json
{"reqId":"1c9e0a696176d9f2ee641273ace6f0ad",
"remoteAddr":"::1",
"app":"PHP",
"message":"Undefined index: mimetype at \/home\/deepdiver\/Development\/ownCloud\/core\/lib\/private\/files\/cache\/cache.php#591",
"level":3,
"time":"2015-01-19T08:35:32+00:00",
"method":"POST",
"url":"\/oc\/core\/"}

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #13452

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@PVince81 @icewind1991 @MorrisJobke THX

**Comment by PVince81** [comment]
Makes sense :+1:

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
:+1: looks good

**Pull request merged**
