### PR TITLE
Add default value for remote_id

### LINKED ISSUE #13970: Upgrade 7.4 --> 8.0: SQLSTATE[23000]: Integrity constraint violation: 19 oc_share_external.remote_id may not be NULL
Hi,

I just tried to do a manual upgrade von 7.04 to 8.0 on my Debian Wheezy machine with SQLite backend, during the upgrade I receive this error message:

$ ./occ upgrade
Turned on maintenance mode
Checked database schema update
An exception occurred while executing 'INSERT INTO oc_share_external (id, "remote", "share_token", "password", "name", "owner", "user", "mountpoint", "mountpoint_hash") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external':

SQLSTATE[23000]: Integrity constraint violation: 19 oc_share_external.remote_id may not be NULL
Turned off maintenance mode
Update failed
$ 

Any help is welcome,

kind regards, Joerg.

### PR DESCRIPTION
**Pull request by PVince81**
Fixes SQLite migration with non-null column.

Fixes https://github.com/owncloud/core/issues/13970

Please review @schiesbn @DeepDiver1975 @icewind1991 @LukasReschke 

Note: steps here https://github.com/owncloud/core/issues/13970#issuecomment-76155893
Needs to be tested on:
- [x] sqlite
- [x] mariadb
- [x] mysql
- [x] postgres
- [x] oracle

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@PVince81  You have to increment the app version to trigger schema migrations

**Comment by DeepDiver1975** [comment]
assigning 8.1 - because pr against master

**Comment by icewind1991** [comment]
> oracle

Turns out external shares never worked with oracle....

**Comment by icewind1991** [comment]
Tested with oracle

**Comment by icewind1991** [comment]
> Turns out external shares never worked with oracle....

#14537

**Comment by PVince81** [comment]
I increased the version.

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
Worked for MySQL:

```
Server version: 5.6.23 MySQL Community Server (GPL)

Copyright (c) 2000, 2014, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [oc]> describe oc_share_external;
+-----------------+---------------+------+-----+---------+----------------+
| Field           | Type          | Null | Key | Default | Extra          |
+-----------------+---------------+------+-----+---------+----------------+
| id              | int(11)       | NO   | PRI | NULL    | auto_increment |
| remote          | varchar(512)  | NO   |     | NULL    |                |
| remote_id       | int(11)       | NO   |     | NULL    |                |
| share_token     | varchar(64)   | NO   |     | NULL    |                |
| password        | varchar(64)   | YES  |     | NULL    |                |
| name            | varchar(64)   | NO   |     | NULL    |                |
| owner           | varchar(64)   | NO   |     | NULL    |                |
| user            | varchar(64)   | NO   | MUL | NULL    |                |
| mountpoint      | varchar(4000) | NO   |     | NULL    |                |
| mountpoint_hash | varchar(32)   | NO   |     | NULL    |                |
| accepted        | int(11)       | NO   |     | 0       |                |
+-----------------+---------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)

MySQL [oc]> describe oc_share_external;
+-----------------+---------------+------+-----+---------+----------------+
| Field           | Type          | Null | Key | Default | Extra          |
+-----------------+---------------+------+-----+---------+----------------+
| id              | int(11)       | NO   | PRI | NULL    | auto_increment |
| remote          | varchar(512)  | NO   |     | NULL    |                |
| remote_id       | int(11)       | NO   |     | -1      |                |
| share_token     | varchar(64)   | NO   |     | NULL    |                |
| password        | varchar(64)   | YES  |     | NULL    |                |
| name            | varchar(64)   | NO   |     | NULL    |                |
| owner           | varchar(64)   | NO   |     | NULL    |                |
| user            | varchar(64)   | NO   | MUL | NULL    |                |
| mountpoint      | varchar(4000) | NO   |     | NULL    |                |
| mountpoint_hash | varchar(32)   | NO   |     | NULL    |                |
| accepted        | int(11)       | NO   |     | 0       |                |
+-----------------+---------------+------+-----+---------+----------------+
11 rows in set (0.00 sec)

MySQL [oc]> 
```

**Comment by MorrisJobke** [comment]
Works also for Postgres:

```
psql (9.4.1, Server 9.4.0)
Geben Sie „help“ für Hilfe ein.

oc=# \d oc_share_external
                                       Tabelle „public.oc_share_external“
     Spalte      |           Typ           |                             Attribute                              
-----------------+-------------------------+--------------------------------------------------------------------
 id              | integer                 | not null Vorgabewert nextval('oc_share_external_id_seq'::regclass)
 remote          | character varying(512)  | not null
 remote_id       | integer                 | not null
 share_token     | character varying(64)   | not null
 password        | character varying(64)   | Vorgabewert NULL::character varying
 name            | character varying(64)   | not null
 owner           | character varying(64)   | not null
 user            | character varying(64)   | not null
 mountpoint      | character varying(4000) | not null
 mountpoint_hash | character varying(32)   | not null
 accepted        | integer                 | not null Vorgabewert 0
Indexe:
    "oc_share_external_pkey" PRIMARY KEY, btree (id)
    "sh_external_mp" UNIQUE, btree ("user", mountpoint_hash)
    "sh_external_user" btree ("user")

oc=# \d oc_share_external
                                       Tabelle „public.oc_share_external“
     Spalte      |           Typ           |                             Attribute                              
-----------------+-------------------------+--------------------------------------------------------------------
 id              | integer                 | not null Vorgabewert nextval('oc_share_external_id_seq'::regclass)
 remote          | character varying(512)  | not null
 remote_id       | integer                 | not null Vorgabewert (-1)
 share_token     | character varying(64)   | not null
 password        | character varying(64)   | Vorgabewert NULL::character varying
 name            | character varying(64)   | not null
 owner           | character varying(64)   | not null
 user            | character varying(64)   | not null
 mountpoint      | character varying(4000) | not null
 mountpoint_hash | character varying(32)   | not null
 accepted        | integer                 | not null Vorgabewert 0
Indexe:
    "oc_share_external_pkey" PRIMARY KEY, btree (id)
    "sh_external_mp" UNIQUE, btree ("user", mountpoint_hash)
    "sh_external_user" btree ("user")
```

:+1:

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by icewind1991** [comment]
:+1:

**Comment by PVince81** [comment]
Thanks guys. I'll do the last mariadb test and then kick Jenkins

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
test with Mariadb-10.0.13 succeeded.

I don't think Jenkins will behave, the error is about checking out.
I'll push a dummy branch.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/14547

**Comment by PVince81** [comment]
Jenkins is back!

**Comment by PVince81** [comment]
Backport PR for stable8 is here: https://github.com/owncloud/core/pull/14533

**Pull request merged**
