### PR TITLE
this must be larger then (>), since buggy behaviour occurs when the para...

### PR DESCRIPTION
**Pull request by blizzz**
...meter is a small number

Thanks to @Flugtiger https://github.com/owncloud/core/commit/f28235a7ef6664978a8b4f6d16a47df508244294#commitcomment-9354126

review pls @MorrisJobke @d-tamm @tkaufm

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by tkaufm** [comment]
@blizzz
works for me.

Best
Tobias

**Comment by blizzz** [comment]
@karlitschek this also needs to go to OC 7 as it is part of a fix that was backported thereto as well. Approved?

**Comment by karlitschek** [comment]
absolutely. Thanks

**Comment by MorrisJobke** [comment]
stable7 1c000b7

**Pull request merged**
