### PR TITLE
WIP: Swift library swap for Keystone v3 compatibility

### PR DESCRIPTION
**Pull request by bradjones1**
## Description

A WIP PR to demonstrate and explore implications of upgrading OpenStack Swift libraries, and by extension Guzzle to 6.x

Importantly, since I am new to developing for OwnCloud, I am not sure how the project keeps the 3rdparty repo in sync with core. I have commented below with a diff of the composer.json file for the third-party dependencies.
## Related Issue

https://github.com/owncloud/core/issues/20787
## Motivation and Context

There are a number of aging dependencies in OwnCloud and the technical debt is catching up to us. There will be some ripple-effect changes with interlocked dependencies, but this problem will just get worse the longer we wait.
## How Has This Been Tested?

As a WIP this still needs some work, but functionally during testing this works with Keystone v3 auth endpoints for creating external Swift storage endpoints, uploading, renaming, introspecting and deleting objects. I have not tested management of subdirectories.
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change) - **Requires PHP 7** which I'm sure is a broader conversation for the project.
## Checklist:
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bradjones1** [comment]
Per above, here's the diff for the composer.json in 3rdparty.
```diff
diff --git a/composer.json b/composer.json
index 3845971..b1a4b44 100644
--- a/composer.json
+++ b/composer.json
@@ -11,7 +11,7 @@
                "doctrine/dbal": "2.5.4",
                "mcnetic/zipstreamer": "^1.0",
                "phpseclib/phpseclib": "2.0.0",
-               "rackspace/php-opencloud": "v1.9.2",
+               "php-opencloud/openstack": "^2.0",
                "jeremeamia/superclosure": "2.1.0",
                "bantu/ini-get-wrapper": "v1.0.1",
                "natxet/CssMin": "dev-master",
@@ -27,7 +27,7 @@
                "nikic/php-parser": "1.4.1",
                "icewind/Streams": "0.4.1",
                "swiftmailer/swiftmailer": "@stable",
-               "guzzlehttp/guzzle": "5.3.1",
+               "guzzlehttp/guzzle": "~6.1",
                "league/flysystem": "1.0.20",
                "pear/pear-core-minimal": "v1.10.1",
                "interfasys/lognormalizer": "^v1.0",
```

**Comment by DeepDiver1975** [comment]
Having hard requirement on PHP 7 all over the project is not accepable for now. Note that we drop 5.4 and 5.5 for ownCloud 9.2

One way to make this work is to implement an isolated app which holds all dependencies and can then require php7.

Please have a look at the repo files_external_ftp as an example on how to implement an external storage app

**Comment by bradjones1** [comment]
@DeepDiver1975 thanks. If anyone else finds this PR/issue and is interested in working on that with me, please e-mail.

**Comment by bradjones1** [comment]
FYI for anyone interested, I'm working on this at https://github.com/BradJonesLLC/files_external_swift

**Pull request closed without merging**
