### PR TITLE
[stable8] Fix cache update when doing a rename that overwrites the target

### LINKED ISSUE #14559: Version dropdown not removed after restoring a file
### Steps to reproduce

1. Install owncloud 
2. upload or create a text file
3. edit the file a couple of time so that there are a few versions
4. click on the version link for the file
5. select one of the version and click the restore link

### Expected behaviour

The file is restored and the version dropdown goes away

### Actual behaviour

The file is restored but the version dropdown remains.  This makes it seem that the restore didn't happen so I end up clicking it multiple times getting an error message that the file can't be restored because I'm trying to restore a file that has already been restored.

This is a regression from 7.

p295

### Server Host info:

CentOS release 6.6 (Final)
PHP 5.4.36

### Server configuration

ownCloud Enterprise Edition 8.0 (daily) Build:2015-02-26T05:30:39+00:00 bc1418156339d4e61fe81bd1474f91555432ca00

### PR DESCRIPTION
**Pull request by icewind1991**
Backport of https://github.com/owncloud/core/pull/14575

Fixes #14559

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Works :+1: error in log is gone

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @PVince81 @LukasReschke

**Comment by LukasReschke** [comment]
Yup :+1:

**Comment by PVince81** [comment]
Works :+1:

**Pull request merged**
