### PR TITLE
Only read from an existing file

### LINKED ISSUE #27988: Failures when getting some signature.json files from apps.
When running integration tests we can see this output:

```php
[Tue May 23 15:40:12 2017] file_get_contents(/var/www/html/multilinkshares/apps/guests/appinfo/signature.json): failed to open stream: No such file or directory at /var/www/html/multilinkshares/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#39
[Tue May 23 15:40:12 2017] file_get_contents(/var/www/html/multilinkshares/apps/testing/appinfo/signature.json): failed to open stream: No such file or directory at /var/www/html/multilinkshares/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#39
[Tue May 23 15:40:12 2017] file_get_contents(/var/www/html/multilinkshares/apps/theme-example/appinfo/signature.json): failed to open stream: No such file or directory at /var/www/html/multilinkshares/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#39
[Tue May 23 15:40:12 2017] file_get_contents(/var/www/html/multilinkshares/apps/customgroups/appinfo/signature.json): failed to open stream: No such file or directory at /var/www/html/multilinkshares/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#39
```

  - installed: true
  - version: 10.0.1.5
  - edition: Community

cc @phisch

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Related Issue
fixes #27988

## How Has This Been Tested?
- tail -f data/owncloud.log
- open apps in settings page
- observer no errors anymore

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Works 👍

**Comment by phil-davis** [comment]
Note: The Travis failure on UI tests here on merge should be improved by the more robust UI testing changes also merged at around the same time. We will see how tests of later merges go.

**Comment by PVince81** [comment]
@DeepDiver1975 backport to stable10 ?

**Comment by PVince81** [comment]
@DeepDiver1975 please backport

**Pull request merged**
