### PR TITLE
Skeleton files are now copied on for shibboleth users 

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Related Issue
- fixes https://github.com/owncloud/user_shibboleth/issues/163

## How Has This Been Tested?
- connect owncloud with testshib.org
- login via testshib.org
- see if skeleton files appear or not

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by davitol** [comment]
:+1: Tested and WFM

**Comment by PVince81** [comment]
please verify that skeleton still works for other scenarios:
- regular home
- alternative home
- object store home (if it ever worked before...)

**Comment by butonic** [comment]
- [x] regular home
- [x] home folder naming rule set to mail, skeleton copied to data/<mail>
- [ ] objectstore ... need to check other saml stuff first

**Comment by PVince81** [comment]
can't test objectstore, app is broken: https://github.com/owncloud/objectstore/issues/56

maybe use the workaround ? ironically the bug itself is related to admin home folder not automatically setup.

**Comment by davitol** [comment]
Objectstore:

1) Apply this PR
2) Create a new user

The user is created and the Skeleton files appears

**Comment by PVince81** [comment]
Thanks!

**Pull request merged**
