### PR TITLE
Update libraries, and Guzzle to 6.2

### PR DESCRIPTION
**Pull request by PVince81**
## Description
Update Guzzle to 6.2, and also other libraries (deleted and regenerated composer.lock)

Expecting many problems as there were API changes in that lib.

## Motivation and Context
Guzzle 5.3 is outdated, needs update.
Also some libs used by apps will need Guzzle > 6.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PVince81** [comment]
First fail:
```
.......WWWWWPHP Fatal error:  Class 'GuzzleHttp\Message\Response' not found in /srv/www/htdocs/owncloud/tests/lib/Http/Client/ResponseTest.php on line 26
```

With a bit of luck if all our code uses the Http\Client wrapper, we only need to adjust that one.

**Comment by PVince81** [comment]
Guide here: https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

- [ ] setDefaultOption has been removed but is used in Http\Client\Client

**Comment by PVince81** [comment]
Needs retesting:
- [ ] TEST: connecting to federated share with proxy server
- [ ] TEST: federated sharing (incoming, outgoing, etc)
- [ ] TEST: Ext storages that use Guzzle:
    - [ ] S3
    - [ ] GDrive
    - [ ] others ?

**Comment by PVince81** [comment]
- [ ] TEST: with PHP 5.6 (if we want to backport this monster to 10.0.x ...)

**Comment by PVince81** [comment]
unit tests passed for me locally, but I expected that some of these API changes aren't covered.

- [ ] TODO: adjust use statements from Guzzle: MessageInterface

**Comment by PVince81** [comment]
Took me a while to adjust the integration test code to work with Guzzle v6, especially because none of it is properly wrapped with utility functions.

Let's see, integration tests should go further now. @SergioBertolinSG

**Comment by PVince81** [comment]
- [ ] TEST: market connection
- [ ] TEST: certificate stuff

**Comment by PVince81** [comment]
- [ ] TEST: smashbox (better run it before merging, just in case, it also covers from federated sharing cases AFAIK)

**Comment by PVince81** [comment]
added more fixes, apparently you can only read the body once.

**Comment by PVince81** [comment]
Added more fixes, also in core for "POST". Federated sharing integration tests passed locally, so it looks promising.

- [ ] update market app guzzle too ??

**Comment by PVince81** [comment]
Great, CI passed!

Now still need to manually test everything I listed above.

**Comment by PVince81** [comment]
- automated tests of amazon s3 passed (`make test-external TEST_EXTERNAL_ENV=amazons3-ceph`) but I suspect they did because the code paths used by the tests are going through the storage code directly so it loads the old Guzzle bundled by aws-php-sdk.

In general we should anyway unbundle these external storages: https://github.com/owncloud/core/issues/20116

**Comment by PVince81** [comment]
did some tests with federated shares and all seemed to work fine:
- [x] TEST: incoming share
- [x] TEST: outgoing share (because it sends remote requests)
- [x] TEST: mount public link
- [x] TEST: remove remote share as sharer (notifies counterpart)
- [x] TEST: remove remote share as recipient (notifies counterpart)

**Comment by PVince81** [comment]
- [ ] TEST: GDrive 🚫 cannot set it up https://github.com/owncloud/core/issues/27456#issuecomment-305810128

**Comment by PVince81** [comment]
@felixboehm @DeepDiver1975 I think this PR is a good example of what is likely too risky to put in a maintenance release, considering that many market apps might also be using the old Guzzle API.

**Comment by PVince81** [comment]
Moving to backlog for now.

@SergioBertolinSG spoke about moving the Guzzle stuff into a utility wrapper, in which case we'll only need to adjust the wrapper and not all the tests like I did here.

**Comment by Hemant-Mann** [comment]
@PVince81 the new dropbox app also requires `guzzlehttp/guzzle >= 6.0` due to a dependency in the UnOfficial Dropbox SDK [https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/composer.json#L13](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/composer.json#L13)

**Comment by PVince81** [comment]
@felixboehm @pmaier1 @DeepDiver1975 looks like updating the Guzzle lib is becoming more pressing, see previous comment... Also see https://github.com/owncloud/core/pull/28063#issuecomment-311327604.

**Comment by PVince81** [comment]
The updated GDrive SDK also requires Guzzle v6: https://github.com/owncloud/files_external_gdrive/issues/4

**Comment by Hemant-Mann** [comment]
Hey so I can work with Guzzle 5.3 for the new dropbox app but in that way I'll have to manually manage the dependency of the app by committing vendor (3rd party) files in the repo which I dont think is a good practise

Thoughts @PVince81 @DeepDiver1975 ?

**Comment by PVince81** [comment]
@Hemant-Mann does this even work with Guzzle 5.3 ? Can you have a quick try ? Note that the APIs are not compatible so if the flysystem adapter has no version compatible with Guzzle 5.3, might need to hack that one too... ugly...

cc @DeepDiver1975

**Comment by Hemant-Mann** [comment]
@PVince81 The Guzzle dependency is in the **SDK** not in _flysystem_
But the SDK allows us to provide our own HTTP Client to send requests to the Dropbox API (Plug and Play type)
So if we can Supply a Guzzle 5.3 client to the SDK everything still works (I have tested my flysystem-adapter)
See this [https://github.com/Hemant-Mann/flysystem-dropbox/blob/master/composer.json#L15](https://github.com/Hemant-Mann/flysystem-dropbox/blob/master/composer.json#L15) my adapter does not require Guzzle as such by the dependency `kunalvarma05/dropbox-php-sdk` requires Guzzle ^6.0 which is the problem

**Comment by PVince81** [comment]
Rebased and solved conflicts. I didn't rerun all tests, so let's see if all still passes.

The next step will be to extract the bits that are compatible with Guzzle v5.3 and merge them to master, so we don't need to change these again once switching to Guzzle v6.

**Comment by PVince81** [comment]
argh... of course... with Jenkins down I won't get test results

**Comment by PVince81** [comment]
hmm seems it wouldn't be that easy as we don't have GuzzleHttp\Psr7\Request with the old Guzzle, so would need to use yet another approach which works with both versions

**Comment by PVince81** [comment]
another fix: WebdavHelper used the obsolete `setBody()`.

Let's hope all CI will pass this time.

**Comment by PVince81** [comment]
superseded by https://github.com/owncloud/core/pull/29211

**Pull request closed without merging**
