### PR TITLE
Replace some OC_Config calls with ILogger methods

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @PVince81 @rullzer @LukasReschke 

I tested:
- `./occ status`
- upgrade via web UI
- `php cron.php`

All works fine. This just was in a local stash and I want to get this in ;)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@MorrisJobke the commit message is wrong I guess? :wink:

**Comment by PVince81** [comment]
:+1:

**Comment by LukasReschke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
> @MorrisJobke the commit message is wrong I guess?

-.- IConfig ... should I really fix the message or do we simply merge?

**Pull request merged**
