### PR TITLE
What user exactly was deleted?

### PR DESCRIPTION
**Pull request by butonic**
just more output for the CLI user delete command

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by karakayasemi** [comment]
We need to adjust test also.
https://github.com/owncloud/core/blob/master/tests/Core/Command/User/DeleteTest.php#L55. 
We can test this class with Symfony's CommandTester. IMHO, it is easy to test with it. https://github.com/owncloud/core/blob/master/tests/Core/Command/User/AddTest.php

**Comment by DeepDiver1975** [comment]
```
Time: 3.1 minutes, Memory: 246.00MB

There was 1 failure:

1) Tests\Core\Command\User\DeleteTest::testValidUser with data set #0 (true, 'The specified user was deleted')
Expectation failed for method name is equal to <string:writeln> when invoked 1 time(s)
Parameter 0 for invocation Symfony\Component\Console\Output\OutputInterface::writeln('<info>User with uid '', displ.../info>', 0) does not match expected value.
Failed asserting that '<info>User with uid '', display name '', email '' was deleted</info>' contains "the specified user was deleted".

/drone/src/core/Command/User/Delete.php:67
/drone/src/tests/lib/TestCase.php:190
/drone/src/tests/Core/Command/User/DeleteTest.php:86

--

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by DeepDiver1975** [comment]
@butonic @PVince81 backport?

**Comment by PVince81** [comment]
yes please

**Comment by DeepDiver1975** [comment]
will take care

**Comment by phil-davis** [comment]
Backport stable10 #30164

**Pull request merged**
