### PR TITLE
fix issue #23600 - mail invites through v1 webdav

### PR DESCRIPTION
**Pull request by allgood**
## Description

Add Schedule and IMip plugins when receiving webdav v1 api calendar calls
## Related Issue

issue #23600

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Thanks a lot @ctodobom

**Comment by DeepDiver1975** [comment]
@ctodobom can I ask you to sign the CLA? THX

**Comment by DeepDiver1975** [comment]
It was confirmed that this actually fixes the issue.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by ctodobom** [comment]
@DeepDiver1975 , just did

> @ctodobom can I ask you to sign the CLA? THX

**Pull request merged**
