### PR TITLE
fix: optimize preview cleanup sql

### LINKED ISSUE #40383: previews:cleanup issues
Important, files and database are on a fast NFS (NetApp) backend connected via GbE. Enterprise server  running VMWare as host for ownCloud.

### Steps to reproduce
1. upgrade from 10.10 to 10.11
2. run `occ previews:cleanup` without any options/arguments

Post successful upgrading, started `occ previews:cleanup` without any options/arguments. This means it should make one round with max 1000 entries (chunks) which is the default. The command started at 18h and did not finish until 23h. Rechecking in the moring, ist finished and reported `1103 orphaned previews deleted`. Means it took between 4 and 11h... (remember, it is only a small instance started many years ago). Running `htop` in a second shell, memory is fine, mariadb takes 1-2 cores with 100%.

**Following findings:**
- the command took extremely long, my instance is a small one
- there is no update what is going on, though you see a lot of NFS traffic
- the default chunksize of 1000 does not get respected, it cleaned up 1103
- compared when you do a fresh install of oc 10.11, when upgrading, you do not get the entry in the backgroundjobs table `OCA\Files\BackgroundJob\PreviewCleanupJob`
- the command cant be stopped (ctrl c) once started

**Required Solutions:**
- update the [documentation](https://doc.owncloud.com/server/10.11/admin_manual/configuration/server/occ_command.html#previews-commands) to relax this situation
- fix the code, especially for:
-- improve performance
-- respect the chunksize
-- add the bg job to the table automatically when upgrading (migration step necessary?)
-- improve command responsiveness (maybe to add a progress option, a timestamp how long it took)

@DeepDiver1975 @pmaier1 fyi
@jnweiger 

Referencing [feat: previews are physically deleted from disk and db in an async manner](https://github.com/owncloud/core/pull/40045)

### Server configuration
**Operating system**: U22.04

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.4

**ownCloud version:** 10.11

**Updated from an older ownCloud or fresh install:** yes

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):** all good

### ownCloud log (data/owncloud.log)
nothing relevant

### PR DESCRIPTION
**Pull request by DeepDiver1975**
## Related Issue

- Fixes #40383

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by mmattel** [comment]
the failing test: php unit 7.4 for sqlite
```
+ php occ config:app:set core enable_external_storage --value=yes
Config value enable_external_storage for app core set to yes
+ case "${FILES_EXTERNAL_TYPE}" in
+ wait-for-it -t 600 fsweb.test.owncloud.com:445
services aren't ready in 10m0s
```

**Comment by DeepDiver1975** [comment]
> the failing test: `php unit 7.4 for sqlite windows`

oldie .....

**Comment by mmattel** [comment]
@phil-davis I just have rebased but the test `php unit 7.4 for sqlite windows` still fails. Can you have a look and support to make CI happy?

**Comment by DeepDiver1975** [comment]
> Can you have a look and support to make CI happy?

It cannot be fixed - see https://github.com/owncloud/core/pull/40426

**Comment by phil-davis** [comment]
@mmattel that CI pipeline has been out-of-action for "a long time". I have been waiting for a replacement Windows SMB share to be made available for CI, but no joy yet.

If someone reviews and approves the PR, then I (or someone else) can post a "success" drone result and merge the PR.

@DeepDiver1975 you have set the "3 - To Review" label, but nobody is actually called up as reviewers, and this has not been added to the "ownTeam Board" project, and there is no PR description or changelog. Is is really ready for review?

**Comment by mmattel** [comment]
We are looking forward to have 10.12 in a forseeable timeframe and this fix is more than welcomed to get in.

**Comment by DeepDiver1975** [comment]
There is no label set because I do not consider this finished. If time permits I will return 🙈

**Comment by phil-davis** [comment]
> There is no label set

I can see that the "3 - To Review" label was set on Nov 29, 2022 - that is what made me ask if it is really ready for review.

**Comment by DeepDiver1975** [comment]
> I can see that the "3 - To Review" label was set on Nov 29, 2022 - that is what made me ask if it is really ready for review.

:confused:

**Comment by DeepDiver1975** [comment]
My current objection:
- the original query was analysed and did not raise the referenced performance issues
- the new proposed query seems to solve some observed performance issues
- will this now open up new performance issues on different dbms?
- a closer look is necessary

**Comment by mmattel** [comment]
rebased

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUITrashbin-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37544/143

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingAcceptSh-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37544/133

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingIntUsers1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37544/138

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUITags-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/37544/142

**Comment by mmattel** [comment]
At least CI is now green after it refused to get there 😄

**Comment by jnweiger** [comment]
I'd like to see some comments on the subquery
```
select `fileid` from `*PREFIX*filecache` where `fc`.`name` = CAST(`*PREFIX*filecache`.`fileid` as CHAR(24))
```

I'd say, his almost always returns empty, as the numeric fileid - (even if cast to string) is very unlikely to be equal to the name??

**Comment by DeepDiver1975** [comment]
> I'd say, his almost always returns empty, as the numeric fileid - (even if cast to string) is very unlikely to be equal to the name??

absolutly not - for thumbnails the the folder name is the fileid. Believe it or not - this is all done by intention ;-)

**Comment by jnweiger** [comment]
Understood.
I tried creating several files and folders with numeric names that match the fileid of thumbnails and fotos. They all survived the
the cleanup jobs correctly. It seems quite save despite that namespace clash.

I thought, that something like 
```
WHERE `fc`.`path` = CONCAT("thumbnails/",CAST(oc_filecache.fileid  as CHAR(24)))
```
should be safter, but I could not provoke any misbehaviour.
Mindblowing technology. :-)

**Comment by jvillafanez** [comment]
Something to consider is to remove the sorting and make a query per user.

Using fileid > 1
```
MariaDB [owncloud]> explain select fileid, name, user_id from oc_filecache fc join oc_mounts on storage = storage_id where parent in (select fileid from oc_filecache where storage in (select numeric_id from oc_storages where id like 'home::%' or id like 'object::user:%') and path = 'thumbnails')   and fc.fileid not in (select fileid from oc_filecache where fc.name = CAST(oc_filecache.fileid as CHAR(24)))   and fc.fileid > 1   order by user_id, fileid;
+------+--------------------+--------------+-----------------+----------------------------------------------------------------------------------------------------------+---------------------+---------+-------------------------------+------+--------------------------------------------------------------+
| id   | select_type        | table        | type            | possible_keys                                                                                            | key                 | key_len | ref                           | rows | Extra                                                        |
+------+--------------------+--------------+-----------------+----------------------------------------------------------------------------------------------------------+---------------------+---------+-------------------------------+------+--------------------------------------------------------------+
|    1 | PRIMARY            | oc_mounts    | ALL             | mounts_storage_index                                                                                     | NULL                | NULL    | NULL                          | 1    | Using temporary; Using filesort                              |
|    1 | PRIMARY            | oc_storages  | range           | PRIMARY,storages_id_index                                                                                | storages_id_index   | 259     | NULL                          | 2    | Using where; Using index; Using join buffer (flat, BNL join) |
|    1 | PRIMARY            | fc           | ref             | PRIMARY,fs_storage_path_hash,fs_parent_name_hash,fs_storage_mimetype,fs_storage_mimepart,fs_storage_size | fs_storage_mimetype | 4       | owncloud.oc_mounts.storage_id | 9    | Using index condition; Using where                           |
|    1 | PRIMARY            | oc_filecache | eq_ref          | PRIMARY,fs_storage_path_hash,fs_storage_mimetype,fs_storage_mimepart,fs_storage_size                     | PRIMARY             | 8       | owncloud.fc.parent            | 1    | Using where                                                  |
|    4 | DEPENDENT SUBQUERY | oc_filecache | unique_subquery | PRIMARY                                                                                                  | PRIMARY             | 8       | func                          | 1    | Using index; Using where                                     |
+------+--------------------+--------------+-----------------+----------------------------------------------------------------------------------------------------------+---------------------+---------+-------------------------------+------+--------------------------------------------------------------+
5 rows in set (0.001 sec)
```

Without sorting and fileid > 1 and user_id = admin
```
MariaDB [owncloud]> explain select fileid, name from oc_filecache fc join oc_mounts on storage = storage_id where parent in (select fileid from oc_filecache where storage in (select numeric_id from oc_storages where id like 'home::%' or id like 'object::user:%') and path = 'thumbnails')   and fc.fileid not in (select fileid from oc_filecache where fc.name = CAST(oc_filecache.fileid as CHAR(24)))   and fc.fileid > 1   and user_id = 'admin';
+------+--------------------+--------------+-----------------+----------------------------------------------------------------------------------------------------------+------------------------+---------+-------------------------------+------+--------------------------------------------------------------+
| id   | select_type        | table        | type            | possible_keys                                                                                            | key                    | key_len | ref                           | rows | Extra                                                        |
+------+--------------------+--------------+-----------------+----------------------------------------------------------------------------------------------------------+------------------------+---------+-------------------------------+------+--------------------------------------------------------------+
|    1 | PRIMARY            | oc_mounts    | ref             | mounts_user_root_index,mounts_user_index,mounts_storage_index                                            | mounts_user_root_index | 258     | const                         | 1    | Using index condition                                        |
|    1 | PRIMARY            | oc_storages  | range           | PRIMARY,storages_id_index                                                                                | storages_id_index      | 259     | NULL                          | 2    | Using where; Using index; Using join buffer (flat, BNL join) |
|    1 | PRIMARY            | fc           | ref             | PRIMARY,fs_storage_path_hash,fs_parent_name_hash,fs_storage_mimetype,fs_storage_mimepart,fs_storage_size | fs_storage_mimetype    | 4       | owncloud.oc_mounts.storage_id | 9    | Using index condition; Using where                           |
|    1 | PRIMARY            | oc_filecache | eq_ref          | PRIMARY,fs_storage_path_hash,fs_storage_mimetype,fs_storage_mimepart,fs_storage_size                     | PRIMARY                | 8       | owncloud.fc.parent            | 1    | Using where                                                  |
|    4 | DEPENDENT SUBQUERY | oc_filecache | unique_subquery | PRIMARY                                                                                                  | PRIMARY                | 8       | func                          | 1    | Using index; Using where                                     |
+------+--------------------+--------------+-----------------+----------------------------------------------------------------------------------------------------------+------------------------+---------+-------------------------------+------+--------------------------------------------------------------+
5 rows in set (0.001 sec)
```

The search on the oc_mount table should use an index now, boosting the performance. Previously, we had to sort a temporary table that didn't seem to be indexed. Note that there could be thousands of users, so that temporary table could be really huge.

**Comment by jvillafanez** [comment]
With around 2000 images for Brian and 100 images for Carol, these are the results for the queries:
```
MariaDB [owncloud]> select fileid, name, user_id
    -> from oc_filecache fc join oc_mounts on storage = storage_id
    -> where parent in (
    ->   select fileid from oc_filecache where storage in (
    ->     select numeric_id from oc_storages where id like 'home::%' or id like 'object::user:%'
    ->   ) and path = 'thumbnails')
    ->   and not exists(select `fileid` from oc_filecache where fc.name = CAST(oc_filecache.fileid as CHAR(24)))
    ->   and fc.fileid > 1
    ->   order by user_id, fileid;
Empty set (17.584 sec)
```
```
MariaDB [owncloud]> select fileid, name, user_id
    -> from oc_filecache fc join oc_mounts on storage = storage_id
    -> where parent in (
    ->   select fileid from oc_filecache where storage in (
    ->     select numeric_id from oc_storages where id like 'home::%' or id like 'object::user:%'
    ->   ) and path = 'thumbnails')
    ->   and fc.fileid not in (select fileid from oc_filecache where fc.name = CAST(oc_filecache.fileid as CHAR(24)))
    ->   and fc.fileid > 1
    ->   order by user_id, fileid;
2114 rows in set (0.034 sec)
```
```
MariaDB [owncloud]> select fileid, name
    -> from oc_filecache fc join oc_mounts on storage = storage_id
    -> where parent in (
    ->   select fileid from oc_filecache where storage in (
    ->     select numeric_id from oc_storages where id like 'home::%' or id like 'object::user:%'
    ->   ) and path = 'thumbnails')
    ->   and fc.fileid not in (select fileid from oc_filecache where fc.name = CAST(oc_filecache.fileid as CHAR(24)))
    ->   and fc.fileid > 1
    ->   and user_id = 'Brian';
2004 rows in set (0.028 sec)
```
```
MariaDB [owncloud]> select fileid, name
    -> from oc_filecache fc join oc_mounts on storage = storage_id
    -> where parent in (
    ->   select fileid from oc_filecache where storage in (
    ->     select numeric_id from oc_storages where id like 'home::%' or id like 'object::user:%'
    ->   ) and path = 'thumbnails')
    ->   and fc.fileid not in (select fileid from oc_filecache where fc.name = CAST(oc_filecache.fileid as CHAR(24)))
    ->   and fc.fileid > 1
    ->   and user_id = 'Carol';
106 rows in set (0.005 sec)
```

**Comment by DeepDiver1975** [comment]
> With around 2000 images for Brian and 100 images for Carol, these are the results for the queries:
> 
> ```
> 
> ```

I am not doubting the performance benefit - but we need to make sure the iterative mechanism catches all elements.

**Comment by DeepDiver1975** [comment]
Analysis from the new query:
```
-> Limit: 1000 row(s)  (actual time=2.472..2.484 rows=183 loops=1)
    -> Sort: oc_mounts.user_id, fc.fileid, limit input to 1000 row(s) per chunk  (actual time=2.471..2.477 rows=183 loops=1)
        -> Stream results  (cost=15.32 rows=12) (actual time=2.366..2.411 rows=183 loops=1)
            -> Inner hash join (oc_mounts.storage_id = fc.`storage`)  (cost=15.32 rows=12) (actual time=2.362..2.383 rows=183 loops=1)
                -> Table scan on oc_mounts  (cost=0.17 rows=4) (actual time=0.006..0.007 rows=4 loops=1)
                -> Hash
                    -> Nested loop antijoin  (cost=12.67 rows=6) (actual time=0.275..2.297 rows=182 loops=1)
                        -> Nested loop inner join  (cost=11.35 rows=6) (actual time=0.270..1.985 rows=182 loops=1)
                            -> Nested loop inner join  (cost=8.70 rows=2) (actual time=0.257..1.349 rows=3 loops=1)
                                -> Filter: ((oc_storages.id like 'home::%') or (oc_storages.id like 'object::user:%'))  (cost=0.65 rows=4) (actual time=0.013..0.017 rows=3 loops=1)
                                    -> Covering index scan on oc_storages using storages_id_index  (cost=0.65 rows=4) (actual time=0.011..0.013 rows=4 loops=1)
                                -> Filter: (oc_filecache.`path` = 'thumbnails')  (cost=1.45 rows=1) (actual time=0.088..0.442 rows=1 loops=3)
                                    -> Index lookup on oc_filecache using fs_storage_path_hash (storage=oc_storages.numeric_id)  (cost=1.45 rows=6) (actual time=0.014..0.426 rows=193 loops=3)
                            -> Index lookup on fc using fs_parent_name_hash (parent=oc_filecache.fileid), with index condition: (fc.fileid > 1)  (cost=0.69 rows=3) (actual time=0.007..0.210 rows=61 loops=3)
                        -> Filter: (fc.`name` = cast(oc_filecache.fileid as char(24) charset utf8mb4))  (cost=0.28 rows=1) (actual time=0.002..0.002 rows=0 loops=182)
                            -> Single-row covering index lookup on oc_filecache using PRIMARY (fileid=fc.fileid)  (cost=0.28 rows=1) (actual time=0.001..0.001 rows=1 loops=182)
```

Previous query:
```
-> Limit: 1000 row(s)  (actual time=4.461..4.475 rows=165 loops=1)
    -> Sort: oc_mounts.user_id, fc.fileid, limit input to 1000 row(s) per chunk  (actual time=4.460..4.468 rows=165 loops=1)
        -> Stream results  (cost=115497.16 rows=326) (actual time=4.143..4.417 rows=165 loops=1)
            -> Hash antijoin (fc.`name` = cast(oc_filecache.fileid as char(24) charset utf8mb4))  (cost=115497.16 rows=326) (actual time=4.140..4.392 rows=165 loops=1)
                -> Nested loop inner join  (cost=18.13 rows=0.5) (actual time=1.227..3.150 rows=215 loops=1)
                    -> Inner hash join (no condition)  (cost=9.91 rows=9) (actual time=1.213..1.218 rows=12 loops=1)
                        -> Table scan on oc_mounts  (cost=0.30 rows=4) (actual time=0.005..0.007 rows=4 loops=1)
                        -> Hash
                            -> Nested loop inner join  (cost=8.70 rows=2) (actual time=0.303..1.196 rows=3 loops=1)
                                -> Filter: ((oc_storages.id like 'home::%') or (oc_storages.id like 'object::user:%'))  (cost=0.65 rows=4) (actual time=0.009..0.011 rows=3 loops=1)
                                    -> Covering index scan on oc_storages using storages_id_index  (cost=0.65 rows=4) (actual time=0.007..0.008 rows=4 loops=1)
                                -> Filter: (oc_filecache.`path` = 'thumbnails')  (cost=1.45 rows=1) (actual time=0.104..0.395 rows=1 loops=3)
                                    -> Index lookup on oc_filecache using fs_storage_path_hash (storage=oc_storages.numeric_id)  (cost=1.45 rows=6) (actual time=0.015..0.382 rows=235 loops=3)
                    -> Filter: (fc.`storage` = oc_mounts.storage_id)  (cost=0.64 rows=0.05) (actual time=0.115..0.160 rows=18 loops=12)
                        -> Index lookup on fc using fs_parent_name_hash (parent=oc_filecache.fileid), with index condition: (fc.fileid > 1)  (cost=0.64 rows=3) (actual time=0.005..0.157 rows=71 loops=12)
                -> Hash
                    -> Covering index scan on oc_filecache using fs_storage_mimetype  (cost=115460.54 rows=709) (actual time=0.016..0.085 rows=709 loops=1)

**Comment by DeepDiver1975** [comment]
> -> Table scan on oc_mounts  (cost=0.17 rows=4) (actual time=0.006..0.007 rows=4 loops=1)

I agree with @jvillafanez that this is yet another optimization opportunity .... but maybe something for a followup pr ...

**Review by jvillafanez — APPROVED** [review]

**Comment by mmattel** [comment]
Do we need any changelog?

**Comment by DeepDiver1975** [comment]
> Do we need any changelog?

argh - totally missed that .... will submit pr ...

**Pull request merged**
