### PR TITLE
[stable10] Improve text in settings/personal App Password

### PR DESCRIPTION
**Pull request by mmattel**
Improve text in settings/personal App Password

## Description
Backport of #31159

## How Has This Been Tested?

Text only change

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phil-davis** [comment]
I restarted drone. It is getting the test timing fail that was addressed in https://github.com/owncloud/core/pull/31528 Detune testStat storage mtime test - maybe the time on some node is drifting further out of sync with reality?

**Review by phil-davis — COMMENTED** [review]
Backport looks fine.
Over to @pmaier1 for approval and what 10.0.n release to merge this for.

**Review by pmaier1 — APPROVED** [review]
Just a wording change, so next release should be ok, I guess. Maybe @PVince81 has a different opinion.

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
SMB windows failure unrelated, merging

**Pull request merged**
