### PR TITLE
external user app: Add note to enable it first

### LINKED ISSUE #13961: Add note to enable the "External user support" app in config.sample.php
Hi,

its still not clear for many users that the "External user support" app needs to be enabled before the config snippet here:

https://github.com/owncloud/core/blob/v7.0.4/config/config.sample.php#L216-L226

can be used. Not enabling this app causes an:

```
User backend OC_User_IMAP not found.
```

Ref to the documentation part: https://github.com/owncloud/documentation/pull/823

### PR DESCRIPTION
**Pull request by ghost**
fixes #13961

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by RealRancor** [comment]
MIT licenced

Could be also useful to backport to stable7

**Comment by karlitschek** [comment]
good idea. please backport

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Because it is just a comment in a config sample file I backported exceptionally directly to stable8 and stable7:
stable8 85d695d
stable7 c2a72ce

**Pull request merged**
