### PR TITLE
[full-ci] Change remote to federated

### LINKED ISSUE #38871: "remote" or "federated" share
1) On the webUI admin sharing settings page there are settings for "Set default expiration date for remote shares"
2) Further down that settings page there is a section about "Federation" and "Federated Cloud Sharing"
3) When a user shares with a user on a different cloud storage, the sharing tab uses the word "Federated" to describe the share type.

Item (1) seems inconsistent. Should the words be adjusted to replace "remote" with "federated"?

(and look for anywhere else where there is a mixed of "remote" and "federated")

Note: the capabilities API reports about these under a key `remote`

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
Change remote to federated in user-facing strings - e.g. in the webUI and in exception/error messages that might be reported somewhere. I also changed some JS variables, ids... to try and be consistent. Acceptance test variable names are also changed.

The API remains the same - any endpoint, capability, config setting etc that has "remote" in it remains the same. Internal constants that have `REMOTE_SHARE` in them remain the same. That preserves compatibility for any existing server installation and clients.

Note: if this is done, then there are translation string changes. So it needs to be merged well before a release, to give time for translators to then adjust the translations.

If this is merged, then a doc issue is needed - we need to check what docs have text or screenshots that need "remote" updated to "federated".

## Related Issue
- Fixes #38871 

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUIFiles-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30764/132/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares2-latest-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30765/116/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiFederationToShares2-git-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30765/115/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiWebdavMove1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/30766/96/1

**Comment by phil-davis** [comment]
All drone CI tests pass - that's good.

I only did search-replace on a  bunch of stuff. SonarCloud Analysis fails because the existing code in these places does not have enough coverage, and has too much "duplication". Someone will have to decide what we do about that, in cases like this.

Anyway, there is no rush for this! It needs to be merged soon after a release, and well before the next release, so that translations can be updated.

**Comment by phil-davis** [comment]
Rebased to get fresh CI.

**Comment by JammingBen** [comment]
SonarCloud tests are going to be fun with this one... It complains about files that have never been tested because they changed now.

And it complains about some spec-files not being tested, which is total nonsense. I fixed this in https://github.com/owncloud/core/pull/39067 already, maybe we should move it to an own PR @phil-davis ?

**Comment by phil-davis** [comment]
I will rebase after that SonarCloud exclude PR. Then if it still fails coverage we will have to discuss - what to do about code that has no measured test coverage, and has only been touched to change var names and text in strings.

Because actually there is test coverage of some part of this - acceptance tests check various UI stuff. But that does not get measured.

**Comment by JammingBen** [comment]
Merged #39077 👍

**Comment by phil-davis** [comment]
@micbar 
I have only changed text strings and variable names. I have not added or changed any logic. But this fails SonarCloud - existing coverage is too low. What do we do about that?

**Comment by JammingBen** [comment]
@phil-davis Could we implement a way to skip SonorCloud for PRs like this? This could be a problem in the future, too.

**Review by AlexAndBear — APPROVED** [review]

**Review by micbar — APPROVED** [review]

**Pull request merged**
