### PR TITLE
jQuery image viewer for better shared/public viewing and large image support

### PR DESCRIPTION
**Pull request by RobAWarner**
Implemented an image viewer (by 'Sudhanshu Yadav' http://ignitersworld.com/lab/imageViewer.html) to allow you to zoom in on the previews of shared/public images and also provide support (zoom & pan) for viewing large images nicely that don't fit in the browser window, mentioned in issue #19986

Here is [an example](https://owncloud.azelphur.com/index.php/s/vrs3tyoUHWC8A7x) of this working, thanks to @Azelphur

### CODE REVIEW

**Comment by oparoz** [comment]
Thanks @MonsterKiller! I like the idea, but the example doesn't work at all. Is it based on this PR?

**Comment by Azelphur** [comment]
@oparoz the example link works fine for me? Tested on Linux and Android, Firefox and Chrome

**Comment by oparoz** [comment]
1. Launch the example. The image is not centered, seem to be cut on the right
1. Click on the image. Image is not fullscreen and centered, but zooming doesn't work
1. It's impossible to leave fullscreen mode. Browser crashes after a while

Windows/Chrome

Also, I've noticed a bug in the library: https://github.com/s-yadav/ImageViewer/issues/4

**Comment by oparoz** [comment]
OK, so I've played with the library a bit and we can't use it as-is. It only really works with large images anything smaller than the window will be stretched to fill the screen.
Let's keep this open until those issues are resolved as there aren't many libs delivering the same features.

**Comment by PVince81** [comment]
Any update ? I see the linked bug was resolved ?

**Comment by PVince81** [comment]
Is there still interest in getting this in core or is this obsolete ?

**Comment by oparoz** [comment]
There is definitely interest from my side since it could also be used in Gallery, but it's blocked by this:
https://github.com/s-yadav/ImageViewer/issues/7

Maybe an issue should be created by @MonsterKiller describing the problem we're trying to solve and people might add links to other potential solutions.

**Comment by PVince81** [comment]
@oparoz thanks for the update

**Comment by PVince81** [comment]
Setting this to 9.2 to reexamine when upstream fixes are in

**Comment by DeepDiver1975** [comment]
please reopen this pr once the upstream issue is fixed - THX

**Pull request closed without merging**
