### PR TITLE
we no longer support webdav locks - no need to keep the column

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Do we want to wait for the next version bump, or do we want to add the bump now?

**Comment by DeepDiver1975** [comment]
> Do we want to wait for the next version bump, or do we want to add the bump now?

No version dump necessary - tables are not going to be removed by the schema mechanism.
This is done in a repair job

**Pull request merged**
