### PR TITLE
Backport fix link sharing regression master stable8.2

### PR DESCRIPTION
**Pull request by DeepDiver1975**
backport of https://github.com/owncloud/core/pull/19982

@MorrisJobke

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@rperezb @davitol please reverify

@SergioBertolinSG can you please add a integration tests for this sceanrio? THX

**Comment by davitol** [comment]
WFM :+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Pull request merged**
