### PR TITLE
Best practice through out the web speak of a max avatar image size of…

### LINKED ISSUE #24488: Owncloud.log goes crazy.
Hi,
as advised on the owncloud forum, i am opening a ticket here.

A few weeks ago (after 9 or 9.0.1 upgrade, can't really tell), the admin panel of my owncloud installation became inaccessible. If i try to access it, the whole server appliance freezes, gives a 504 gateway timeout and needs to be stopped and then started again (restart alone does not work). I will describe in detail: 
 
Steps to reproduce
1. Log on, try to access admin panel
2. tail -f owncloud.log
3. wait and see it grow to 50 + mb in minutes, eats up my ram.

Expected behaviour
Tell us what should happen

admin panel should open, no error should be present

Actual behaviour
Tell us what happens instead

log file is spammed within seconds and now looks like this:

`{"reqId":"IVGC+Iesg4A2EMGc9UmP","remoteAddr":"","app":"core","message":"Error while running background job (class: OCA\\DAV\\CardDAV\\SyncJob, arguments: ): {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_cards` SET `carddata` = ?, `lastmodified` = ?, `size` = ?, `etag` = ? WHERE (`uri` = ?) AND (`addressbookid` = ?)' with params [\\\"BEGIN:VCARD\\\\r\\\\nVERSION:3.0\\\\r\\\\nPRODID:-\\\\\\\/\\\\\\\/Sabre\\\\\\\/\\\\\\\/Sabre VObject 3.5.0...`

And so on. The logfile is HUGE and i cannot really extract useful information from it.

### Server configuration
**Operating system**:
Debian Jessie with apparmor (makes no difference if enabled or disabled completely), /srv is a separate parition with nosuid, nodev, noexec.

**Web server:**
Nginx 1.1.10 + Naxsi (disabled or enabled or not compiled makes no difference) + Php5 - FPM, all behind SSLH as transparent proxy

**Database:**
MariaDB 15.1

**PHP version:**
5.6.20

**ownCloud version:** (see ownCloud admin page)
9.0.2

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
tarball from websites

**Signing status (ownCloud 9.0 and above):**
dont know what this means
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
It says "No errors have been found."

```

**List of activated apps:**
Enabled:
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - provisioning_api: 0.4.1
  - templateeditor: 0.1
```

**The content of config/config.php:**
`{
    "system": {
        "instanceid": "ID",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "IP",
            "URL"
        ],
        "datadirectory": "\/srv\/oc-data",
        "overwrite.cli.url": "https:\/\/SERVER_URL\/",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "oc_db",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "mail_from_address": "webmaster",
        "mail_smtpmode": "php",
        "mail_domain": "SERVER_URL",
        "enable_previews": "true",
        "loglevel": 1,
        "maintenance": false,
        "theme": ""
    }
}
`

**Are you using external storage, if yes which one:** local/smb/sftp/...
sshfs mount on /media

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

```

### Client configuration
**Browser:**
Firefox latest
**Operating system:**
Windows 10
#### Web server error log
[error-log.txt](https://github.com/owncloud/core/files/254157/error-log.txt)

#### ownCloud log (data/owncloud.log)
[owncloud-log.txt](https://github.com/owncloud/core/files/254158/owncloud-log.txt)

### LINKED ISSUE #25730: LDAP can't login - oc_cards problem with VCARD
version: 9.0.1.3

One of my users can't login via LDAP. Problem seems to be large VCARD data which breaks mysql connection..

An exception occurred while executing 'UPDATE `oc_cards` SET `carddata` = ?, `lastmodified` = ?, `size` = ?, `etag` = ? WHERE (`uri` = ?) AND (`addressbookid` = ?)' with params [\\\"BEGIN:VCARD\\\\r\\\\nVERSION:3.0\\\\r\\\\nPRODID:-\\\\\\\/\\\\\\\/Sabre\\\\\\\/\\\\\\\/Sabre VObject 3.5.0\\\\\\\/\\\\\\\/EN\+very long string with "binary" vcard data.....

Then next mysql query gives error "MySQL server has gone away" and user cant login..

### PR DESCRIPTION
**Pull request by DeepDiver1975**
… 96 pixels

@felixboehm 

fixes https://github.com/owncloud/core/issues/25730
fixes https://github.com/owncloud/core/issues/24488

### CODE REVIEW

**Comment by PVince81** [comment]
Will this work on the personal page in the avatar cropping dialog ? I believe it might be using this code path.

**Comment by PVince81** [comment]
Never mind, I thought it was a different code path.

:+1:

**Comment by felixboehm** [comment]
$size argument ignored, here:
https://github.com/owncloud/core/blob/master/lib/private/User/User.php#L376

**Comment by DeepDiver1975** [comment]
> $size argument ignored, here:
> https://github.com/owncloud/core/blob/master/lib/private/User/User.php#L376

itwasme

**Comment by PVince81** [comment]
:+1: for the extra change, avatar still seems to work fine (LDAP, personal page)

**Comment by felixboehm** [comment]
top 👍

**Comment by DeepDiver1975** [comment]
preparing backports ...

**Comment by DeepDiver1975** [comment]
- stable9.1: https://github.com/owncloud/core/pull/25898

**Pull request merged**
