### PR TITLE
Move \OCP\Contacts to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @nickvergessen @MorrisJobke @DeepDiver1975 @LukasReschke @PVince81

### CODE REVIEW

**Comment by MorrisJobke** [comment]
👍

**Comment by davitol** [comment]
:+1:

**Comment by nickvergessen** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
Please fix

````
06:38:30 PHP Fatal error:  Class 'ComposerAutoloaderInit2f23f73bc0cc116b4b1eee1521aa8652' not found in /ssd/jenkins/workspace/ocs-api-integration-tests-ci/3rdparty/autoload.php on line 7
06:38:30 PHP Stack trace:
06:38:30 PHP   1. {main}() /ssd/jenkins/workspace/ocs-api-integration-tests-ci/occ:0
06:38:30 PHP   2. require_once() /ssd/jenkins/workspace/ocs-api-integration-tests-ci/occ:11
06:38:30 PHP   3. require_once() /ssd/jenkins/workspace/ocs-api-integration-tests-ci/console.php:51
06:38:30 PHP   4. OC::init() /ssd/jenkins/workspace/ocs-api-integration-tests-ci/lib/base.php:947
06:38:30 PHP   5. require_once() /ssd/jenkins/workspace/ocs-api-integration-tests-ci/lib/base.php:508
06:38:31 Build step 'Conditional step (single)' marked build as failure

**Comment by rullzer** [comment]
@DeepDiver1975 that is failing all over the place. And it is related to the 3rdparty autoloader ;)

**Comment by DeepDiver1975** [comment]
> And it is related to the 3rdparty autoloader ;)

still need to be fixed and take care off ...

**Comment by rullzer** [comment]
@DeepDiver1975 for sure. But I tried 3 machines I have and it all works there...

**Comment by DeepDiver1975** [comment]
Deleting the workspace on the slave did fix the issue :see_no_evil:

**Pull request merged**
