### PR TITLE
Detect user navigating away, don't interpret as ajax error

### LINKED ISSUE #23482: User trapped in app management screen
### Steps to reproduce
1. Open app management `index.php/settings/apps`
2. Try to click the cloud, or any app menu, or browser bookmark to switch the page

### Expected behaviour
The page should load

### Actual behaviour
App management reloads

### Server configuration
**Operating system**: Linux Mint 17.3

**PHP version:** php 5.5.32

**ownCloud version:** master

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** git

**List of activated apps:**

```
Enabled:
  - activity: 2.3.0
  - announcementcenter: 1.2.0
  - comments: 0.3.0
  - dav: 0.2.2
  - federatedfilesharing: 0.2.0
  - files: 1.5.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.0
  - workflow: 0.2.0
```

**The content of config/config.php:**

```json
{
    "system": {
        "debug": true,
        "trusted_domains": [
            "localhost",
            "owncloudmaster.local"
        ],
        "apps_paths": {
            "0": {
                "path": "\/home\/nickv\/ownCloud\/master\/core\/apps",
                "url": "\/apps",
                "writable": false
            },
            "1": {
                "path": "\/home\/nickv\/ownCloud\/master\/noapps",
                "url": "\/..\/noapps",
                "writable": true
            }
        },
        "loglevel": 1,
        "logtimezone": "UTC",
        "log_rotate_size": 52428,
        "appstore.experimental.enabled": true,
        "appstoreenabled": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.0.0",
        "dbname": "oc_temp",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocz6xyesfky4",
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 45

**Operating system:** Linux Mint 17.3

#### Web server error log
```
--- empty ---
```

#### ownCloud log (data/owncloud.log)
```json
--- empty ---
```

#### Browser log
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src http://localhost 'unsafe-eval'"). apps
Deprecation warning: tipsy is deprecated. Use tooltip instead. js.js:2183:2
```

@schiesbn can reproduce this as well on Iceweasle/Firefox 44

### PR DESCRIPTION
**Pull request by PVince81**
Whenever a user navigates away, all ajax calls will fail with the same result like a cross-domain redirect (SSO). To distinguish these cases, we need to detect whether the error is a result of the user navigating away. For this, we introduce a new flag that will be set in "beforeunload".

Additional handling was required for false positives in case "beforeunload" is used (ex: cancelled upload) and the user cancelled the navigation.

Please review @oparoz @nickvergessen @rullzer @blizzz @DeepDiver1975 

Fixes https://github.com/owncloud/core/issues/23482

@karlitschek backport for 9.0.1 ?

### CODE REVIEW

**Comment by oparoz** [comment]
@PVince81 Is there a sure way to test the before and after? It only happened randomly to me.

**Comment by PVince81** [comment]
@oparoz I was able to reproduce the "before" consistently in Firefox with the app's page with app store loading. For some reason, the app store loads slowly for me, so just go to the Apps page and before it finished loading, click directly on the cloud icon on the top left.

If you don't let it finish, it would reload the current page (before).
After this fix, it will properly go to the correct page (files app).

Goal is to have at least one pending ajax call running at the time you navigate away.

**Comment by karlitschek** [comment]
good. please backport :+1:

**Comment by oparoz** [comment]
Thanks @PVince81 I was able to experience the bug. The reason it's more difficult in Files is probably because the switch needs to be timed to happen exactly in the middle of a request.

**Comment by oparoz** [comment]
OK, that doesn't completely fix it for me...

1. Click on apps
1. Click on a tab. I tried not enabled and tool because the list is longer
1. Quickly click on the cloud

If you can't reproduce, it could be because I get a notification. If you don't see one, it could be because the request happens just before getting the notification and thus you wouldn't know it's because of that.
Notifications have been reported to cancel requests away.

**Comment by schiesbn** [comment]
I can still re-produce the issue, same like @oparoz. Go to the apps menu and quickly try to switch back to files. Result: Instead of the files app, the apps menu gets re-loaded.

**Comment by PVince81** [comment]
Checked on @schiesbn's env and it turns out that sometimes the `beforeunload` is called **after** the ajax error :disappointed: 

We'll have to put the reload in yet another `setTimeout` to make it happen later for the check to work.
I'll adjust this.

**Comment by PVince81** [comment]
@oparoz @schiesbn please try again, I added another layer of strength to the fix

**Comment by schiesbn** [comment]
Tested, works now for me (Iceweasel 44) :+1:

**Comment by oparoz** [comment]
Works for me as well. My only concern is: Does the error catcher still fit the original use case?

**Comment by PVince81** [comment]
@oparoz yes it does. To test it, hack one of the endpoints to redirect to another domain, then have the web UI call it through an ajax call. This simulates what a SSO timeout does, any call to OC usually redirects to another domain (the IDP) for reauth. So when testing this case ownCloud would reload the page.

**Comment by DeepDiver1975** [comment]
````
13:40:05 WARN: 'Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification'
13:40:05 ..
13:40:05 PhantomJS 2.1.1 (Linux 0.0.0) Core base tests global ajax errors reloads current page in case of auth error FAILED
13:40:05 	Expected false to equal true.
13:40:05 	/ssd/jenkins/workspace/core-ci-linux-jsunit/database/sqlite/label/SLAVE/core/js/tests/specs/coreSpec.js:960:43
13:40:05 	Expected false to equal true.
13:40:05 	/ssd/jenkins/workspace/core-ci-linux-jsunit/database/sqlite/label/SLAVE/core/js/tests/specs/coreSpec.js:960:43
13:40:05 	Expected false to equal true.
13:40:05 	/ssd/jenkins/workspace/core-ci-linux-jsunit/database/sqlite/label/SLAVE/core/js/tests/specs/coreSpec.js:960:43
13:40:05 ............................................
13:40:05 PhantomJS 2.1.1 (Linux 0.0.0) ERROR
13:40:05   Some of your tests did a full page reload!

**Comment by PVince81** [comment]
Fixed and enhanced the unit tests

**Comment by oparoz** [comment]
Thanks for the explanation @PVince81

**Comment by schiesbn** [comment]
second reviewer... maybe @nickvergessen

**Comment by nickvergessen** [comment]
Seems to work and solve the issue :+1: 

Sorry, the issue slipped through the last days

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/23735

**Pull request merged**
