### PR TITLE
[full-ci] Drop PHP 7.3

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
PHP 7.3 support ended in December 2021 (9 months ago). Drop support for PHP 7.3. This allows us to update to the latest versions of some dependencies.

composer found the following dependencies that it could update:
```
Package operations: 0 installs, 7 updates, 2 removals
  - Removing laminas/laminas-zendframework-bridge (1.4.1)
  - Removing container-interop/container-interop (1.2.0)
  - Upgrading laminas/laminas-stdlib (3.11.0 => 3.13.0): Extracting archive
  - Upgrading psr/container (1.1.1 => 1.1.2): Extracting archive
  - Upgrading laminas/laminas-servicemanager (3.7.0 => 3.17.0): Extracting archive
  - Upgrading laminas/laminas-validator (2.19.0 => 2.25.0): Extracting archive
  - Upgrading laminas/laminas-filter (2.12.0 => 2.20.0): Extracting archive
  - Upgrading laminas/laminas-inputfilter (2.12.1 => 2.21.0): Extracting archive
  - Upgrading sabre/uri (2.2.4 => 2.3.2): Extracting archive
```

And in `apps/files_external/3rdparty` these have been updated:
- guzzlehttp/psr7 (2.4.0 to 2.4.1)
- phpseclib/phpseclib (3.0.14 to 3.0.16)

There are gradually getting to be more dependencies whose releases no longer support PHP 7.3.

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

The previous PR was #40248

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiShareCreateSpecialToShares1-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/36695/47

**Comment by phil-davis** [comment]
CI passes - good.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/36889/25/7
```
+ phpdbg -d memory_limit=6G -rr ../lib/composer/bin/phpunit --configuration phpunit-autotest-external.xml --coverage-clover output/coverage/autotest-external-clover-sqlite-sftp.xml ../apps/files_external/tests/Storage/SftpTest.php
[Welcome to phpdbg, the interactive PHP debugger, v7.4.30]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
PHPUnit 9.5.24 #StandWithUkraine

Runtime:       PHPDBG 7.4.30
Configuration: phpunit-autotest-external.xml

.........FFFFFF.................................................. 65 / 92 ( 70%)
...........................                                       92 / 92 (100%)

Time: 00:32.791, Memory: 82.75 MB

There were 6 failures:

1) OCA\Files_External\Tests\Storage\SftpTest::testDirectories with data set #0 ('folder')
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:96
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

2) OCA\Files_External\Tests\Storage\SftpTest::testDirectories with data set #1 (' folder')
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:96
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

3) OCA\Files_External\Tests\Storage\SftpTest::testDirectories with data set #2 ('folder ')
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:96
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

4) OCA\Files_External\Tests\Storage\SftpTest::testDirectories with data set #3 ('folder with space')
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:96
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

5) OCA\Files_External\Tests\Storage\SftpTest::testDirectories with data set #4 ('spéciäl földer')
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:96
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

6) OCA\Files_External\Tests\Storage\SftpTest::testDirectories with data set #5 ('test single'quote')
Failed asserting that true is false.

/drone/src/tests/lib/Files/Storage/Storage.php:96
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:97

FAILURES!
Tests: 92, Assertions: 366, Failures: 6.
```
Need to investigate what happened for SFTP.

**Comment by phil-davis** [comment]
Note: there are major releases available for:
Major releases available for:
doctrine/dbal
league/flysystem

But they are not essential.

**Comment by phil-davis** [comment]
See #40394

**Pull request closed without merging**
