### PR TITLE
Fix displaying owner before share icon in file list

### LINKED ISSUE #23645: [Sharing] In files view, the user that made the shares is not shown
### Steps to reproduce

1. With admin user, create two users (user1, user2)
2. user1: create a file and a folder and share with user2
3. Log in with user2 and accept the shares

### Expected behaviour

In files view, it should be shown who was the user that made the shares

### Actual behaviour

In files view, the user that made the shares is not shown

Note: It worked OK in oc 9.0.0. (regression)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** "9.0.1.1","versionstring":"9.0.1 RC1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox, Safari

oC 9.0.0
screen shot 2016-03-30 at 10 34 09

oC 9.0.1

whomadewho

### PR DESCRIPTION
**Pull request by PVince81**
Initial display of owner was missing

Fixes https://github.com/owncloud/core/issues/23645

@rullzer @schiesbn @icewind1991 @MorrisJobke @nickvergessen please review

@karlitschek backport for 9.0.1 to fix regression ?

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by icewind1991** [comment]
Looks good :+1:

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/23664

**Comment by rullzer** [comment]
:+1:

**Pull request merged**
