### PR TITLE
Add Versions app header to config.sample.php

### PR DESCRIPTION
**Pull request by ghost**
https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/config_sample_php_parameters.html#deleted-items-trash-bin

Currently missing the header between trashbin_retention_obligation and versions_retention_obligation

### CODE REVIEW

**Comment by nickvergessen** [comment]
@karlitschek @PVince81 should backport to 9.0 because that generates our documentation page

**Comment by RealRancor** [comment]
MIT licensed (if thats needed at all)

**Comment by karlitschek** [comment]
cool. please backport

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by nickvergessen** [comment]
@DeepDiver1975 can we merge like is, or do we need a ci branch?

**Comment by RealRancor** [comment]
Backport to 9.0 in https://github.com/owncloud/core/pull/22782

Any opinions about backporting to 8.2 as the config.sample.php of it is also affected:

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/config_sample_php_parameters.html#deleted-items-trash-bin

**Comment by MorrisJobke** [comment]
> Any opinions about backporting to 8.2 as the config.sample.php of it is also affected:

Please open a PR. Thanks :)

**Comment by RealRancor** [comment]
Backport to stable8.2 in https://github.com/owncloud/core/pull/22802

**Pull request merged**
