### PR TITLE
[stable9.1]  Group shares with same source and target

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/25113 to stable9.1

Please note that the version check has been adjusted for this branch.

Please review @owncloud/sharing @owncloud/qa

:warning: don't merge before 9.1.0 is released.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
rebased

**Comment by PVince81** [comment]
Oracle is not happy:  -> `ORA-01033: ORACLE initialization or shutdown in progress Check environment: ORACLE_HOME=/usr/lib/oracle/12.1/client64 ORACLE_SID= LD_LIBRARY_PATH= NLS_LANG= tnsnames.ora is not readable`

Since we have tests related to DB, better make sure it works there too. (it did on master though)

**Comment by PVince81** [comment]
Fix on master is incomplete, the repair step doesn't cover https://github.com/owncloud/core/issues/25555.
Also doesn't cover https://github.com/owncloud/core/pull/25543#issuecomment-234462819

Let's hold this for now.

I'll try and fix these on master and then we can cherry-pick the changes into this PR.

**Comment by PVince81** [comment]
cherry-picked https://github.com/owncloud/core/pull/25567 and rebased

**Comment by PVince81** [comment]
Cherry-picked https://github.com/owncloud/core/pull/25568 to fix the issue mentionned in the PR, which is the same as https://github.com/owncloud/core/pull/25543#issuecomment-234462819

This is now ready for review again, I hope we covered all cases now !

**Comment by PVince81** [comment]
@rullzer please give this a quick review, should be the same code as the other PRs to master + this one: https://github.com/owncloud/core/pull/25568

@DeepDiver1975 this PR here can be merged after https://github.com/owncloud/core/pull/25568 is merged.

**Comment by SergioBertolinSG** [comment]
:+1: works fine.

**Pull request merged**
