### PR TITLE
Use integer for availability instead of bool

### LINKED ISSUE #18420: Exception when updating storage availability
### Steps

1. Enable external storage
1. Configure a SMB mount with invalid values (I used my usual local SMB storage's settings but have shut down smbd before adding this)

### Expected result
No errors in log

### Actual result
```
{"reqId":"F5ovzkrcLYIpYvTyG+JF","remoteAddr":"192.168.177.239","app":"files_external","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_storages` SET `available` = ?, `last_checked` = ? WHERE `id` = ?' with params [false, 1439975924, \\\"smb::vincent@localhost\\\\\\\/\\\\\\\/shared\\\\\\\/\\\\\\\/\\\"]:\\n\\nSQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'available' at row 1\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_stor...', Array)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(73): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/db.php(147): OC_DB_StatementWrapper->execute(Array)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/storage.php(157): OC_DB::executeAudited('UPDATE `*PREFIX...', Array)\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(670): OC\\\\Files\\\\Cache\\\\Storage->setAvailability(false)\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(507): OC\\\\Files\\\\Storage\\\\Common->setAvailability(false)\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(123): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n
#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/globalstoragescontroller.php(100): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n
#9 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->create('smb', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, NULL, Array, Array, 100)\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n
#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n
#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'create')\\n
#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n
#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n
#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n
#16 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(879): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n
#17 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n
#18 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":4,"time":"2015-08-19T09:18:44+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/globalstorages"}
```

### Versions
ownCloud 8.2 pre-alpha git master 0b37004808c22792dab350eebfc763db6408b440

@Xenopathic please have a look.
Note that I also observed this on your branch https://github.com/owncloud/core/pull/15914 during testing

### PR DESCRIPTION
**Pull request by RobinMcCorkell**
Fixes #18420

Seems like our codebase isn't ready for booleans yet...

Please review @icewind1991 @PVince81 @LukasReschke @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by karlitschek** [comment]
A DB schema change like that is critical. Needs careful resting on all supported databases

**Comment by Xenopathic** [comment]
@karlitschek The availability stuff is currently only in master, not 8.1. Only dev environments will be affected, and MariaDB/MySQL works just fine with the migration.

**Comment by karlitschek** [comment]
Yes. And master will become 8.2 soon. So my statement is fully valid.
:-1: Until we have answers.

**Comment by LukasReschke** [comment]
Considering that [the field is not in 8.1](https://github.com/owncloud/core/blob/stable8.1/db_structure.xml#L85) and boolean is proven to create problems I'm in favour of this. We're using integers everywhere as booleans do not work properly.

**Comment by icewind1991** [comment]
:+1: "normal" installations will only get a new column like before

**Comment by PVince81** [comment]
@karlitschek can you revisit your statement in the light of the additional information ?

The boolean field was added on master at some point (not 8.1) and we discovered on some envs (like mine) that the boolean field doesn't work properly.

**Comment by PVince81** [comment]
but additional testing doesn't hurt, in case some people had the crazy idea of running pre-alpha code on their env and would have that boolean field already...

**Comment by DeepDiver1975** [comment]
> Considering that the field is not in 8.1 and boolean is proven to create problems I'm in favour of this. We're using integers everywhere as booleans do not work properly.

:+1: from my side

**Comment by karlitschek** [comment]
let's discuss tomorrow. sorry for being careful but this kind of changes broke in the past.

**Comment by DeepDiver1975** [comment]
rebased ...

**Comment by karlitschek** [comment]
ok. discussed this with @DeepDiver1975 This is fine with me because this is a new field in master and not a type change. 
So this shoudl be fine for normal users who upgrade from 8.1 to 8.2 
And the developers have to deal with a maybe broken migration. :-) 
:+1:

**Comment by PVince81** [comment]
@DeepDiver1975 how come this PR is again out of date ? Does it mean we have to rebase PRs and merge directly after that ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 how come this PR is again out of date ? Does it mean we have to rebase PRs and merge directly after that ?

I was fighting some hickups of jenkins last night ... we need to rebase ... I'll take care - THX

**Pull request merged**
