### PR TITLE
Fix backport of #13317

### PR DESCRIPTION
**Pull request by icewind1991**
cc @MorrisJobke @DeepDiver1975

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@dragotin you might want to use this branch for your local testing? THX

**Comment by DeepDiver1975** [comment]
@icewind1991 

local unit test execution helps :speak_no_evil: 

````
00:06:32.835 ........PHP Fatal error:  Class 'Test\Files\Temporary' not found in /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/tests/lib/files/view.php on line 672
00:06:33.000 PHP Stack trace:
00:06:33.000 PHP   1. {main}() /usr/local/bin/phpunit:0
00:06:33.000 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:612
00:06:33.000 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
00:06:33.000 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
00:06:33.001 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:423
00:06:33.001 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
00:06:33.001 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
00:06:33.001 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:722
00:06:33.001 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:641
00:06:33.001 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:06:33.020 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:06:33.021 PHP  12. PHPUnit_Framework_TestCase->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:766
00:06:33.021 PHP  13. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:881
00:06:33.021 PHP  14. Test\Files\View->testPartFileInfo() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:881

**Comment by MorrisJobke** [comment]
#13317

**Comment by MorrisJobke** [comment]
:cry: sorry. Code looks good and browsing around also works :+1: (couldn't test with a client)

**Comment by dragotin** [comment]
upload works again through the client :+1: 

Thanks!

**Comment by DeepDiver1975** [comment]
THX @icewind1991

**Pull request merged**
