### PR TITLE
fix ie promises

### PR DESCRIPTION
**Pull request by butonic**
otherwise ie11 trying to list files in root folder gives: "\"Promise\" ist undefiniert"
```
stack	"ReferenceError: \"Promise\" ist undefiniert\n   at request (http://localhost:8000/oc/core/core/js/files/iedavclient.js?v=5678aa60e76295b7087185731d11dc10:50:4)\n   at dav.Client.prototype.propFind (http://localhost:8000/oc/core/core/vendor/davclient.js/lib/client.js?v=5678aa60e76295b7087185731d11dc10:88:9)\n   at Client.prototype.getFolderContents (http://localhost:8000/oc/core/core/js/files/client.js?v=5678aa60e76295b7087185731d11dc10:468:4)\n   at FileList.prototype.reload (http://localhost:8000/oc/core/apps/files/js/filelist.js?v=5678aa60e76295b7087185731d11dc10:1576:5)\n   at FileList.prototype.changeDirectory (http://localhost:8000/oc/core/apps/files/js/filelist.js?v=5678aa60e76295b7087185731d11dc10:1436:4)\n   at FileList.prototype._onUrlChanged (http://localhost:8000/oc/core/apps/files/js/filelist.js?v=5678aa60e76295b7087185731d11dc10:566:5)\n   at n.event.dispatch (http://localhost:8000/oc/core/core/vendor/jquery/dist/jquery.min.js?v=5678aa60e76295b7087185731d11dc10:3:6410)\n   at r.handle (http://localhost:8000/oc/core/core/vendor/jquery/dist/jquery.min.js?v=5678aa60e76295b7087185731d11dc10:3:3176)\n   at n.event.trigger (http://localhost:8000/oc/core/core/vendor/jquery/dist/jquery.min.js?v=5678aa60e76295b7087185731d11dc10:3:5572)\n   at a.event.trigger (http://localhost:8000/oc/core/core/vendor/jquery-migrate/jquery-migrate.min.js?v=5678aa60e76295b7087185731d11dc10:2:7777)"
```

### CODE REVIEW

**Comment by butonic** [comment]
shouldnt we log something if the json file lists files that no longer exist?

**Comment by PVince81** [comment]
ah, probably due to recent library upgrades?

**Comment by PVince81** [comment]
not sure if this is the correct fix, JS tests fail now:
```
OC.SystemTags.SystemTagsCollection tests fetches only once, until reset FAILED
	ReferenceError: Can't find variable: Promise in core/js/systemtags/systemtagscollection.js (line 9)
	fetch@core/js/systemtags/systemtagscollection.js:9:1914
core/js/tests/specs/systemtags/systemtagscollectionSpec.js:52:19
```

**Comment by PVince81** [comment]
setting to p1: without this OC is completely broken in IE1

**Comment by PVince81** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by PVince81** [comment]
Tested, works

**Comment by PVince81** [comment]
no backport needed, this works correctly on stable10 where no lib updates were done (tested)

**Comment by PVince81** [comment]
hmmm JS tests still fail on Drone but pass for me locally

**Comment by PVince81** [comment]
moving to triage but leaving p2 as we must fix this before the first final release of 11.0

**Comment by PVince81** [comment]
taking over

**Comment by DeepDiver1975** [comment]
As discussed in https://github.com/owncloud/core/issues/35777 the master branch will from now on hold the ownCloud 10 codebase. 

This PR targetted ownCloud 11 which is postponed to a far distant future.

Because of that I'm closing this PR and kindly ask you to re-submit this PR in a few days.

Thanks a lot for your patience

**Pull request closed without merging**
