### PR TITLE
fix don show shares you own in "shared with you"

### PR DESCRIPTION
**Pull request by peterprochaska**
## Description
added check for not showing shares you own

## Related Issue
https://github.com/owncloud/security-tracker/issues/246

## Motivation and Context
make ownCloud more secure

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
👍 Works.

**Comment by PVince81** [comment]
Code looks good but as I see no change in unit tests I expect a failure will happen

**Comment by PVince81** [comment]
fantastic

```
...................
12:59:02 [ERROR] Waited 600 seconds, no response
12:59:02 Kill the docker aaf42736f5408011fd265dd1a80f9f56eaa59db0eba9dd55047df544dd13692a
12:59:02 aaf42736f5408011fd265dd1a80f9f56eaa59db0eba9dd55047df544dd13692a
12:59:02 aaf42736f5408011fd265dd1a80f9f56eaa59db0eba9dd55047df544dd13692a
12:59:02 Makefile:179: recipe for target 'test-php' failed
12:59:02 make: *** [test-php] Error 1
[Pipeline] }
```

@DeepDiver1975 mind restarting the job ?

**Comment by PVince81** [comment]
fantastic

```
...................
12:59:02 [ERROR] Waited 600 seconds, no response
12:59:02 Kill the docker aaf42736f5408011fd265dd1a80f9f56eaa59db0eba9dd55047df544dd13692a
12:59:02 aaf42736f5408011fd265dd1a80f9f56eaa59db0eba9dd55047df544dd13692a
12:59:02 aaf42736f5408011fd265dd1a80f9f56eaa59db0eba9dd55047df544dd13692a
12:59:02 Makefile:179: recipe for target 'test-php' failed
12:59:02 make: *** [test-php] Error 1
[Pipeline] }
```

@DeepDiver1975 mind restarting the job ?

**Comment by DeepDiver1975** [comment]
restarted

**Comment by PVince81** [comment]
@Peter-Prochaska don't forget to submit a separate PR to add a proper test for this

**Pull request merged**
