### PR TITLE
Set expire end of day in UI

### LINKED ISSUE #39234: Link expiration date in webUI Shared by Link is one day too short
### Steps to reproduce
1. make a public link that expires today (that means the end of today)
2.make a public link that expires tomorrow (that means the end of tomorrrow)
3. browse to "Shared by link"

### Expected behaviour
The link at point (1) should expire "in 10 hours" (not "14 hours ago")
The link at point (2) should expire in 1 day and 10 hours (whatever text the system generates for that - it might just say "1 day")

### Actual behaviour
shared-by-link-expiration-date

### Server configuration
Current core master.

This happens because the API returns just the expiration date with a "zero" time `00:00:00`. Because of backward-compatibility issues we could not fix that at the API level. So clients (like the webUI here) need to understand that the link is valid right up to and including 23:59:59 on the expiry day.

Please also have a look around the webUI code to see where else the expiration date is rendered in a way includes the time in the calculation. Any such places are likely to have a similar off-by-one-day error.

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Description
Bugix: Show the correct expiring date in Shared by link files list

Before this PR the "Expiration date" column did not respect that shares 
expiration will be end of date and showing wrong values.
This has been fixed with this PR

## Related Issue

- Fixes https://github.com/owncloud/core/issues/39234

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by JanAckermann** [comment]
@phil-davis this would be a UI based solution, I can remeber that we wanted to change it in the backend, why did we discard it?

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>webUISharingPublic1-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/core/32402/144/1

**Comment by phil-davis** [comment]
> @phil-davis this would be a UI-based solution, I remember that we wanted to change it in the backend, why did we discard it?

The desktop client has a hardcoded matching of the time:
https://github.com/owncloud/client/blob/master/src/gui/sharemanager.cpp#L229
```
    if (data.value("expiration").isString()) {
        _expireDate = QDate::fromString(data.value("expiration").toString(), "yyyy-MM-dd 00:00:00");
    } else {
        _expireDate = value.toDate();
    }
```

So all desktop clients "in the wild" expect the time to always be "00:00:00". If the server changes that, it would be a major version change and would take years for every client everywhere to update.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/32411/9/4
```
	Expected 'in 2 days' to equal 'in a day'.
	@apps/files_sharing/tests/js/sharedfilelistSpec.js:727:50
```

There is a JS unit test to adjust.

**Review by phil-davis — APPROVED** [review]
works - just needs the JS test expectation adjusted.

**Comment by JanAckermann** [comment]
@phil-davis If adjust it to `in 2 days` my tests will fail, otherwise my tests run currently trough.
Expecting some timezone issues or so

**Comment by phil-davis** [comment]
> Expecting some timezone issues or so

True. That might be painful. Have to sort out how that library decides how to do rounding and generate text "in 2 days" "in 3 days" relative to the current time.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
