### PR TITLE
display app update error messages

### LINKED ISSUE #14611: App update says "Error while updating app" caused by outdated release number in upload
### Steps to reproduce
1. Login as admin
2. Select apps
3. Click on update app to vx

### Expected behaviour
Update should take place.
Better error message.

My example: App news was installed in v5.2.6 and I wanted to update to v5.2.7
The issue was the the version number in the uploaded release was still 5.2.6
@Raydiation told me that information.

### Actual behaviour
Got following message
oc8-news-app-update-error-app

### Server configuration
**Operating system**: Linux
**Web server:** apache
**Database:** mysql
**PHP version:** 5.5.21
**ownCloud version:** 8.0.0
**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 36.0
**Operating system:** OS X 10.10

#### ownCloud log (data/owncloud.log)
oc8-news-app-update-error-log

Related to https://github.com/owncloud/news/issues/742

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #14611

@Raydiation @rakekniven  @MorrisJobke @PVince81 @icewind1991 please review - THX

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by Raydiation** [comment]
:+1:

**Comment by karlitschek** [comment]
@DeepDiver1975 possible to backport?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 possible to backport?

sure

**Comment by DeepDiver1975** [comment]
> sure

as in stable8?

**Comment by karlitschek** [comment]
yes. stable8 please :-)

**Pull request merged**
