### PR TITLE
include owncloud coding standard

### PR DESCRIPTION
**Pull request by patrickjahns**
Owncloud coding-standard 1.0.1 is available - use it in core https://github.com/owncloud/coding-standard

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]

**Review by phil-davis — APPROVED** [review]
Looks like a great thing. Having this consistency of "crud" helps in general code-readability.

**Review by DeepDiver1975 — CHANGES_REQUESTED** [review]
- yoda style is applied wrong. I want $var === null and not null === $var

**Comment by phil-davis** [comment]
@DeepDiver1975 are you happy with the code now?

Porposed "effective backport" to ``stable10`` is in PR #31453

**Comment by patrickjahns** [comment]
@DeepDiver1975 
what do you mean by space around `if` ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975
> what do you mean by space around if ?

ignore

**Comment by DeepDiver1975** [comment]
fixing yoda style - https://github.com/owncloud/coding-standard/pull/6

**Comment by phil-davis** [comment]
```
if (null === $var)
if (true === $booleanVar)
if ("a" === $stringVar)
```
looks weird, but actually is handy to do as a habit because then if you accidentally write only a single ``=`` 
```
if (null = $var)
if (true = $booleanVar)
if ("a" = $stringVar)
```
it explodes immediately on you.
Whereas:
```
if ($var = null)
```
is a "silent" bug.

**Comment by patrickjahns** [comment]
@phil-davis 
that should be catched by codestyle checker - will do a quick test and confirm

**Comment by phil-davis** [comment]
@DeepDiver1975 are you making a new release of the coding-standard?
And then we re-fix the code in this PR and my backport.
Or do we merge this attempt, and make another PR(s) to get rid of Yoda?

**Comment by patrickjahns** [comment]
regarding 

```
<?php

if ($var = null) {
	echo "test";
}
```

this is **not** catched by the code checker

**Comment by phil-davis** [comment]
``php-cs-fixer`` does not succeed in "un-Yoda-ing" ``/drone/src/tests/acceptance/features/bootstrap/Logging.php``

I found that you have to get rid of the places that have array references like ``$myArray [$something]`` - manually take the space out between ``$myArray`` and ``[``

Then it might be happy to un-Yoda itself.

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by phil-davis** [comment]
This and other related PRs/commits are in backport PR #31657 which will likely be merged some time after 10.0.9 (to avoid huge rebasing effort while sorting out a release)

**Pull request merged**
