### PR TITLE
Fix sidebar spinner

### LINKED ISSUE #19137: Share dialog checkbox spinner is shifted
On master in the sidebar share tab:

Click on "Share link" or other checkboxes. For a short time the checkbox is shifted and the spinner is shifted.

### PR DESCRIPTION
**Pull request by Henni**
fixes #19137

cc @PVince81 @jancborchardt @davitol 

also fixes the issue with the unshare icon mentioned at https://github.com/owncloud/core/issues/19137#issuecomment-141418074

### CODE REVIEW

**Comment by davitol** [comment]
:+1: looks good

**Comment by karlitschek** [comment]
nice :+1:

**Comment by PVince81** [comment]
Thanks, looks good :+1: 

I get you'll readjust the checkbox styles (`.checkbox`) separately ?

**Comment by PVince81** [comment]
@DeepDiver1975 JS tests passed, please merge this CSS+JS only fix

**Comment by Henni** [comment]
@PVince81 what do you mean by "readjusting separately"?

**Comment by PVince81** [comment]
I mean submit a separate PR after this one here is merged

**Comment by Henni** [comment]
What should the separate PR contain?

**Comment by PVince81** [comment]
The new checkbox styles, by adding the `checkbox` class.

This is how it looks on your branch:
checkbox-oldstyle

**Comment by PVince81** [comment]
ref https://github.com/owncloud/core/issues/19304

**Comment by Henni** [comment]
@PVince81 yes I will fix this in a separate PR.

**Pull request merged**
