### PR TITLE
Remove unnecessary setUp method from provisioning_api

### PR DESCRIPTION
**Pull request by tomneedham**
Fixes self.

Remove setUp method that was meant to end up in a test case.

@MorrisJobke Made it in before the day end ;)

### CODE REVIEW

**Comment by tomneedham** [comment]
This is the method in the right place: https://github.com/owncloud/core/blob/fix-provisioning-api/apps/provisioning_api/tests/groupsTest.php#L30

**Comment by MorrisJobke** [comment]
Slipped somehow in. I already tested without this method earlier. :+1:

**Comment by MorrisJobke** [comment]
cc @LukasReschke @PVince81

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
