### PR TITLE
Validate path in getChild

### LINKED ISSUE #16618: Creating collections using webdav interface with '\' ignores everything after it instead of throwing an error.
### Steps to reproduce

1. Using cadaver or other tool for interacting with webdav interface do:
     
mkcol hola\\\hallo

### Expected behaviour
An error since '\' is still a forbidden character.

### Actual behaviour
cadaver says:
Creating `hola\hallo': succeeded.
And a folder called 'hola' is created. 

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```

```

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```

```

### Client configuration

**browser**
Chrome 41

### PR DESCRIPTION
**Pull request by PVince81**
Returns the correct error message when trying to create a folder called "\":
`curl -v -X MKCOL "http://user:password@host/remote.php/webdav/\\"`
or
`curl -v -X MKCOL 'http://user:password@host/remote.php/webdav/%5C'`

@SergioBertolinSG @icewind1991 @nickvergessen 

Fixes https://github.com/owncloud/core/issues/16618

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
Working fine :+1: 
Tested both options (AllowEncodedSlashes on)

**Comment by icewind1991** [comment]
Makes sense :+1:

**Comment by nickvergessen** [comment]
@PVince81 looks good, mind adding a unit test to https://github.com/owncloud/core/blob/49e1a81eba45fe33e00c217758656cf9201ec0cd/tests/lib/connector/sabre/directory.php#L107-107 ?

**Comment by PVince81** [comment]
Thanks for the tests @nickvergessen

**Comment by PVince81** [comment]
:+1: for the tests

**Pull request merged**
