### PR TITLE
Allow login by email address

### PR DESCRIPTION
**Pull request by DeepDiver1975**
requires #24388

@jancborchardt @LukasReschke

### CODE REVIEW

**Comment by jancborchardt** [comment]
Incredibile … finally it happens.

:+1: tested and works.

**Comment by LukasReschke** [comment]
👍

**Comment by jancborchardt** [comment]
Wow – so how was this so easy now after the conceptual problems before?

**Comment by LukasReschke** [comment]
We basically agreed that a mail address is unique 🙈

**Comment by DeepDiver1975** [comment]
> We basically agreed that a mail address is unique :see_no_evil:

well - in case the email is not unique it will simply not try to login

**Comment by jancborchardt** [comment]
Cool

**Pull request merged**
