### PR TITLE
Move UI acceptance test code from tests/ui to tests/acceptance

### PR DESCRIPTION
**Pull request by phil-davis**
## Description
- add ``api`` and ``webUI`` tags to the feature files, so there is a way to know which are API and which are UI features
- adjust ``run.sh`` so it always only runs the ``api`` tagged features
- adjust ``start_ui_tests.sh`` so it always only runs ``webUI`` tagged features
- Move the feature files and code for UI tests from ``tests/ui`` to ``tests/acceptance``
- Merge the code in ``bootstrap.php`` to make a common one
- Rename the various UI test ``*Context.php`` files to have ``webUI`` in front of the name. This avoids any name conflicts and keeps it clear which files contain gherkin step code relevant to UI tests

## Related Issue
https://github.com/owncloud/QA/issues/517

## Motivation and Context
Migrate the UI acceptance tests into the ``tests/acceptance`` folder so that they can easily make use of API acceptance test step code as useful.

## How Has This Been Tested?
Local runs of sample API and UI acceptance tests
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Test refactoring

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Doc issue is https://github.com/owncloud/documentation/issues/3854

### CODE REVIEW

**Comment by phil-davis** [comment]
Backport stable10 #30726

**Comment by phil-davis** [comment]
This refactoring moves the existing UI test system into the ``tests/acceptance`` folder.
The next few steps after this are:

- reword UI test steps to use grammar like what was done with the API test steps
- use API contexts in UI test suites as relevant to reuse API step code that is useful, and remove duplication from the UI test step code
- sort out the ways that the API and UI test suites are "remembering" stuff like current user, regular user name, regular user password, group names, sharing settings made and reverted, ... and meld it together so this underlying stuff is not duplicated and different
- and then...

**Comment by phil-davis** [comment]
UI test suites in apps need to be updated to find the core UI test code in this new location ``tests/acceptance`` That will be easy to do, but this PR does need to be merged at a time when those changes can quickly follow. So please do not merge me now, just approve!

To do when merging:
- [ ] also merge the ``stable10`` backport #30726 
- [ ] Firewall UI test suite refactoring
- [ ] files_texteditor UI test suite refactoring
- [ ] user_ldap UI test suite refactoring

**Comment by phil-davis** [comment]
Note: this preserves current API acceptance test ways of working, so the changes should be pretty much orthogonal to other PRs in progress to move API acceptance tests from Jenkins to drone, rearrange/sort out drone jobs... So merging this should not cause pain for those other PRs.

**Review by individual-it — APPROVED** [review]

**Review by patrickjahns — APPROVED** [review]
Great 👍

**Pull request merged**
