### PR TITLE
Enable files_external app by default

### PR DESCRIPTION
**Pull request by PVince81**
@DeepDiver1975 @jmaciasportela @jvillafanez @icewind1991

### CODE REVIEW

**Comment by PVince81** [comment]
@karlitschek FYI

**Comment by jmaciasportela** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
Shit - that breaks unit test execution ....

**Comment by PVince81** [comment]
Ah yes, the integration tests, let me adjust that...

**Comment by DeepDiver1975** [comment]
> Ah yes, the integration tests, let me adjust that...

not only that - as soon as files_external is enabled we try to execute the unit tests within - and this fails badly because the configurations for testing do not exist.

we need to explicitly disable files_external within autotest.sh

**Comment by PVince81** [comment]
Let's see if https://github.com/owncloud/core/commit/7f6b4e88d825c8bd03114c648c2c4361f6a07bf8 works

**Comment by nickvergessen** [comment]
Will break app unit tests as well?

Why do we auto enable this app all of a sudden?

**Comment by nickvergessen** [comment]
Integration tests fail, because they assumed that files_external is disabled and use it to test enable/disable.
You can switch to e.g. federation for that

**Comment by PVince81** [comment]
Looks like this might not be needed after all.

**Pull request closed without merging**
