### PR TITLE
Set encrypted to zero in file cache after decrypt-all run on files

### PR DESCRIPTION
**Pull request by sharidas**
Set the encrypted to zero in file cache after the decrypt-all is
run on files.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

## Description

The decrypt-all command never sets the encrypted value in the file cache to zero. If this value is not set to zero, the files like pdf would not be opened ( using files_pdfviewer app ). Setting this value to zero, helps fix this issue.

## Related Issue

- Fixes <issue_link>

## Motivation and Context

The decrypt-all command never sets the encrypted value in the file cache to zero. If this value is not set to zero, the files like pdf would not be opened ( using files_pdfviewer app ). Setting this value to zero, helps fix this issue.

## How Has This Been Tested?

- Create 2 users `admin` and `user1` and enable encryption with user-keys
- Login as `admin` and set the recovery key and enable recovery key for `admin`. For testing I had the recovery key as `1\2`
- Login as `user1` and enable recovery key for `user1`
- Login back to `admin` user and upload files like pdf and jpg
- Share the pdf and jpg files uploaded to `user1`
- Login back to `user1` and create public links of the files shared from `admin`
- Change the recovery key password to `123`
- Run decrypt-all command using recovery keys for `admin` and `user1`
- [x] The decrypted files were able to view in the web ui.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Backport (if applicable set "backport-request" label and remove when the backport was done)

### CODE REVIEW

**Comment by voroyam** [comment]
I applied the patch 
https://github.com/owncloud/core/pull/32014/files#diff-6f510adb432497f4f6a446f791729c79

Then

1. installed RC3
2. activated user-key encryption. Encrypted all files.
3. Created Recovery key
4. Created user1
5. Enabled recovery key for user1 and admin.
6. Uploaded .jpg and .txt  and .png files as user1 and shared them to the admin.
7. Can't view .jpg and .png files with the gallery app in the web ui as admin.

**Comment by sharidas** [comment]
There is an issue with gallery app from market place downloaded in the RC3. Without encryption enabled, the image files are not working on my local instance. The testing I have done is in the master branch of (core + encryption + gallery + files_pdfviewer). And that worked. @voroyam Can you try with master branch of Gallery app?

**Comment by davitol** [comment]
> There is an issue with gallery app from market place downloaded in the RC3

```
{"reqId":"vNZpqvdwrEH07LREOPE7","level":3,"time":"2018-07-09T10:44:19+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"index","method":"GET","url":"\/apps\/gallery\/thumbnails?ids=18&scale=1&square=0&requesttoken=E1UcdgkEOC1gAg8vJxAHbXwVDA87FhkOA1IxUwM4SgU%3D%3AgaqBjRhe9nKwIe1BNbbbsfH8mcRa3B9Vp8tXRzUlHD4%3D","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 3 passed to OC\\\\Preview::__construct() must implement interface OCP\\\\Files\\\\Node, string given, called in \\\/mnt\\\/data\\\/apps\\\/gallery\\\/preview\\\/preview.php on line 100\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/preview\\\/preview.php(100): OC\\\\Preview->__construct('admin', 'files', 'asda\\\/Screen Sho...')\\n#1 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/service\\\/previewservice.php(107): OCA\\\\Gallery\\\\Preview\\\\Preview->setupView('admin', Object(OC\\\\Files\\\\Node\\\\File), 'asda\\\/Screen Sho...')\\n#2 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/controller\\\/preview.php(167): OCA\\\\Gallery\\\\Service\\\\PreviewService->createPreview(Object(OC\\\\Files\\\\Node\\\\File), 400, 200, true, true)\\n#3 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/controller\\\/preview.php(117): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getPreviewData(Object(OC\\\\Files\\\\Node\\\\File), false, 400, 200, true, true)\\n#4 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/controller\\\/preview.php(86): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getData(18, 400, 200, true, false, true)\\n#5 \\\/mnt\\\/data\\\/apps\\\/gallery\\\/controller\\\/previewcontroller.php(103): OCA\\\\Gallery\\\\Controller\\\\PreviewController->getThumbnail(18, false, '1')\\n#6 [internal function]: OCA\\\\Gallery\\\\Controller\\\\PreviewController->getThumbnails('18', false, '1')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getThumbnails')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Gallery\\\\Controller\\\\PreviewController), 'getThumbnails')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('PreviewControll...', 'getThumbnails', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(919): OC\\\\Route\\\\Router->match('\\\/apps\\\/gallery\\\/t...')\\n#14 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php\",\"Line\":112}"}
```

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by sharidas** [comment]
Backport to stable10 -> https://github.com/owncloud/core/pull/32027

**Comment by voroyam** [comment]
@sharidas we need a patch for 10.0.9 correct?

**Comment by voroyam** [comment]
tested with 10.0.9RC3 

set recovery password to 1111\1111 and then change it to 1111

decrypted files and shares are fine.

testing now with "1A\n11" for recovery password and decrypting.

**Pull request merged**
