### PR TITLE
Update google-api-php-client to 1.1.7

### PR DESCRIPTION
**Pull request by lanato**
Experimental update of the google-api-php-client library to version 1.1.7, as discussed in #24431 .
The library is licensed under the Apache License, my own changes to owncloud code under MIT.

### CODE REVIEW

**Comment by PVince81** [comment]
Wow, nice!

**Comment by PVince81** [comment]
After I enable the external storage app, I can't access the admin page.
These errors appear in the log:
```
{"reqId":"eEV5PSoHV4HrKIAgd3ut","remoteAddr":"127.0.0.1","app":"PHP","message":"require_once(Google\/autoload.php): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/storage\/google.php#42","level":3,"time":"2016-05-10T14:45:03+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin","user":"admin"}
{"reqId":"eEV5PSoHV4HrKIAgd3ut","remoteAddr":"127.0.0.1","app":"PHP","message":"require_once(): Failed opening required 'Google\/autoload.php' (include_path='\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/console_getopt:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/pear_exception:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/archive_tar:\/srv\/www\/htdocs\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/srv\/www\/htdocs\/owncloud\/lib\/private:\/srv\/www\/htdocs\/owncloud\/config:\/srv\/www\/htdocs\/owncloud\/3rdparty:\/srv\/www\/htdocs\/owncloud\/apps:\/srv\/www\/htdocs\/owncloud\/apps2:\/srv\/www\/htdocs\/owncloud\/apps3:.:\/usr\/share\/php5:\/usr\/share\/php5\/PEAR:\/srv\/www\/htdocs\/owncloud:\/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php:\/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src') at \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/storage\/google.php#42","level":3,"time":"2016-05-10T14:45:03+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin","user":"admin"}
{"reqId":"J67epMRzG+w1mApst5pF","remoteAddr":"127.0.0.1","app":"PHP","message":"require_once(Google\/autoload.php): failed to open stream: No such file or directory at \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/storage\/google.php#42","level":3,"time":"2016-05-10T14:45:06+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin","user":"admin"}
{"reqId":"J67epMRzG+w1mApst5pF","remoteAddr":"127.0.0.1","app":"PHP","message":"require_once(): Failed opening required 'Google\/autoload.php' (include_path='\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/console_getopt:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/pear_exception:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/srv\/www\/htdocs\/owncloud\/3rdparty\/pear\/archive_tar:\/srv\/www\/htdocs\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/srv\/www\/htdocs\/owncloud\/lib\/private:\/srv\/www\/htdocs\/owncloud\/config:\/srv\/www\/htdocs\/owncloud\/3rdparty:\/srv\/www\/htdocs\/owncloud\/apps:\/srv\/www\/htdocs\/owncloud\/apps2:\/srv\/www\/htdocs\/owncloud\/apps3:.:\/usr\/share\/php5:\/usr\/share\/php5\/PEAR:\/srv\/www\/htdocs\/owncloud:\/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/aws-sdk-php:\/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src') at \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/lib\/storage\/google.php#42","level":3,"time":"2016-05-10T14:45:06+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/admin","user":"admin"}
```

**Comment by PVince81** [comment]
Note that I had to merge with master when I tested it. Maybe something changed in the autoload layer.

For some reason I don't see any "autoload.php" in the Google folder ? Did you maybe miss adding it to your commit ?

**Comment by altyr** [comment]
You suspected right, please try again.

**Comment by altyr** [comment]
@PVince81 as for the merging: It appears the location of the libraries in the OC repo has changed recently, making things a bit confusing when working with a stable release on the side.

**Comment by PVince81** [comment]
> location of the libraries in the OC repo has changed 

I'm not aware of any such changes. I do know there were adjustments regarding autoloader and PSR-4, so not sure what changed here.

Also in general library updates are not backported to stable releases.

Thanks for the update, I'll try again.

**Comment by PVince81** [comment]
The admin page works again. Now when I click "Grant access", nothing happens and the log shows:
```
{"reqId":"raS+4CjMfSAYB+aotuTq","remoteAddr":"127.0.0.1","app":"PHP","message":"Class 'Google_Config' not found at \/srv\/www\/htdocs\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Client.php#80","level":3,"time":"2016-05-10T15:21:03+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files_external\/ajax\/oauth2.php","user":"admin"}
```

**Comment by PVince81** [comment]
CC @Xenopathic for a later review

**Comment by altyr** [comment]
Interesting. I have not caught that as things work as expected when the account is already enabled.

If i can find the time I'll tinker some more later.

**Comment by PVince81** [comment]
Aha, the bot just woke up, just ignore him...

**Comment by PVince81** [comment]
Argh, looks like the `Google_Config` class is actually inside the file `Config.php`. Not sure what weird autoloader magic is needed for this.

@icewind1991 @rullzer @nickvergessen any clues ?

**Comment by nickvergessen** [comment]
> Not sure what weird autoloader magic is needed for this.

It's their autoloading that fails, they have require statements in most of their files, maybe they forgot one? Or the PR does it once in app.php or somewhere similar

**Comment by PVince81** [comment]
The PR does it in our google.php here: https://github.com/owncloud/core/pull/24516/commits/b5f1d35da4e742f3b2208914c10d321be19eb430#diff-843158c77cc9e5bf32a69c285c3fc1cbR42

Okay, turns out the error is from "oauth2.php", I'll try to add their autoloader there.
Thanks for the hint.

**Comment by PVince81** [comment]
Moved to new PR https://github.com/owncloud/core/pull/24799 since I can't push on forks.
Managed to fix the autoloader there.

**Pull request closed without merging**
