### PR TITLE
Dont output paths in scan.php

### PR DESCRIPTION
**Pull request by icewind1991**
use the occ command instead

cc @PVince81 @LukasReschke

### CODE REVIEW

**Comment by PVince81** [comment]
:+1:

I guess keeping the file count is fine ?

**Comment by LukasReschke** [comment]
:+1:

**Comment by LukasReschke** [comment]
@karlitschek We should backport this down to 8.0. Please do approve.

**Comment by karlitschek** [comment]
makes sense. please backport

**Comment by DeepDiver1975** [comment]
@icewind1991 please submit backport r

**Comment by icewind1991** [comment]
- 8.2: #20761
- 8.1: #20764
- 8.0: #20763

**Comment by PVince81** [comment]
All merged.

**Pull request merged**
