### PR TITLE
Fix oracle permission check

### PR DESCRIPTION
**Pull request by pollopolea**
#…ecks for all permissions (6):

     CREATE USER, ALTER USER
     with admin option => GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER

UNLIMITED TABLESPACE has been removed

this isrelated to this old one =>

https://github.com/owncloud/core/issues/24025
#24039 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@pollopolea I need to ask you to sign the CLA - please follow the instructions at https://github.com/owncloud/core/pull/29148#issuecomment-334444273

**Comment by pollopolea** [comment]
I signed CLA yesterday, but I dind't press "recheck button"

**Comment by DeepDiver1975** [comment]
Can I ask you to squash your commits please? We want a clean git commit history - THX a lot!

**Comment by pollopolea** [comment]
Sorry, I'm pretty clumsy using git. How can i do that ?

**Comment by DeepDiver1975** [comment]
see https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History section 'Squashing Commits'

**Comment by pollopolea** [comment]
After 2 days, finally I think everythings is ok.

**Review by butonic — APPROVED** [review]

**Pull request merged**
