### PR TITLE
Fix checkbox in trashbin

### LINKED ISSUE #19405: Trashbin multiselect layout broken
trashbin-multiselect

Also it still has the old checkbox, not sure if related to the breakage.

@jancborchardt @Henni

### PR DESCRIPTION
**Pull request by Henni**
fixes #19405 

cc @PVince81

### CODE REVIEW

**Comment by karlitschek** [comment]
good :+1:

**Comment by PVince81** [comment]
Looks good :+1:

**Comment by PVince81** [comment]
@DeepDiver1975 please merge

**Comment by icewind1991** [comment]
:+1:

**Pull request merged**
