### PR TITLE
[stable9.1] Change png icons to svg

### PR DESCRIPTION
**Pull request by jvillafanez**
Backport of https://github.com/owncloud/core/pull/25405

@PVince81 @DeepDiver1975 Looks like stable9.1 is also affected by https://github.com/owncloud/core/issues/25403 

stable9 and stable8.2 doesn't seem to be affected.

### CODE REVIEW

**Comment by PVince81** [comment]
How come ? We didn't backport the SVG fallback removal.

**Comment by PVince81** [comment]
:+1:

**Comment by davitol** [comment]
:+1:

**Comment by jvillafanez** [comment]
Issue introduced in commit 6cc6538ad215db86aadd156ac033c80a7148baa2 (PR https://github.com/owncloud/core/pull/25240)

```
$ git merge-base --is-ancestor 6cc6538ad215db86aadd156ac033c80a7148baa2 origin/master ; echo $?
0
$ git merge-base --is-ancestor 6cc6538ad215db86aadd156ac033c80a7148baa2 origin/stable9.1 ; echo $?
0
$ git merge-base --is-ancestor 6cc6538ad215db86aadd156ac033c80a7148baa2 origin/stable9 ; echo $?
1
```

**Comment by PVince81** [comment]
But this wasn't merged into stable9.1 ! and stable9.1 was built before we merged it.

That looks fishy

**Comment by PVince81** [comment]
oh... I remember @cdamken did some wrong manipulations and pushed something directly on stable9.1, I hope he didn't push the whole master there.

@jvillafanez can you check the history ?

**Comment by PVince81** [comment]
Here is is: `git show -m 7c4108ee4b1b3ea1e236d3343ffe08c2589c01d7`

**Comment by DeepDiver1975** [comment]
so I guess we can close this - right? @jvillafanez @PVince81

**Pull request closed without merging**
