### PR TITLE
Infinite loop in stream_read() for invalid/corrupt chunks

### LINKED ISSUE #34488: Infinite loop in AssemblyStream.php's stream_read()
We've encountered php processes (using php-fpm) that are running indefinitely due to an infinite loop in AssemblyStream.php's `stream_read()`. We were able to identify this by starting an upload, corrupting a chunk after it started the assembly (this is to bypass the checksum matching) and inspecting PHP processes with `strace -s 1024 -p <pid>`.

It does appear to be an edge case, but we have multiple processes stuck in this loop in our production environment. 

### Steps to reproduce
(these are the steps I used to replicate it)
1. Start an upload via the web interface
2. Once the upload is complete and starts assembling, truncate one of the chunks to 0 bytes
3. Watch the upload never complete because it is stuck in a read loop.

### Expected behaviour
If stream_read() encounters an invalid chunk, throw an exception and exit the loop.

### Actual behaviour
stream_read() continually attempts to read the invalid chunk and enters an infinite loop.

### Server configuration
**Operating system**: RHEL7

**Web server:** Apache 2.4.6

**Database:** MariaDB 10.0.28

**PHP version:** PHP-FPm 7.0.30

**ownCloud version:** 10.0.3

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** TAR on the ownCloud website

**Signing status (ownCloud 9.0 and above):** `Integrity checker has been disabled. Integrity cannot be verified.`

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "5230042dc1897",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "cloudstor.aarnet.edu.au",
        },
        "datadirectory": "\/cloudstor\/data\/owncloud\/data",
        "version": "10.0.3.3",
        "dbtype": "mysql",
        "dbname": "owncloudstable82",
        "dbhost": "127.0.0.1:6033",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "",
        "installed": true,
        "operation.mode": "clustered-instance",
        "default_language": "en_GB",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": false,
        "allow_user_to_change_display_name": false,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "mail_domain": "aarnet.edu.au",
        "mail_from_address": "cloudstor-noreply",
        "mail_smtpmode": "php",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloudstor.aarnet.edu.au\/plus",
        "htaccess.RewriteBase": "\/plus",
        "trashbin_retention_obligation": "30, 60",
        "appcodechecker": false,
        "updatechecker": false,
        "has_internet_connection": true,
        "check_for_working_webdav": false,
        "check_for_working_htaccess": true,
        "log_type": "owncloud",
        "logfile": "\/cloudstor\/logs\/owncloud\/owncloud.log",
        "loglevel": 2,
        "logtimezone": "UTC",
        "log_query": false,
        "customclient_desktop": "https:\/\/cloudstor.aarnet.edu.au\/client-download\/",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=au.edu.aarnet.cloudstor.android",
        "customclient_ios": "https:\/\/itunes.apple.com\/au\/app\/cloudstor\/id1215476371?mt=8",
        "cron_log": true,
        "appstore.experimental.enabled": false,
        "apps_paths": [
            {
                "path": "\/cloudstor\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/cloudstor\/www\/owncloud\/3rdparty-apps",
                "url": "\/3rdparty-apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Movie"
        ],
        "maintenance": false,
        "singleuser": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis.cluster": {
            "seeds": [
                "127.0.0.1:6379"
            ],
            "timeout": 0,
            "read_timeout": 0,
            "failover_mode": 2
        },
        "memcached_servers": [
            [
                "127.0.0.1",
                11211
            ]
        ],
        "blacklisted_files": [
            ".htaccess"
        ],
        "share_folder": "\/Shared",
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "2.4.2",
        "quota_include_external_storage": false,
        "filesystem_check_changes": 0,
        "filesystem_cache_readonly": false,
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "filelocking.enabled": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "upgrade.disable-web": true,
        "upgrade.automatic-app-update": false,
        "integrity.check.disabled": true,
        "cache_path": "\/cloudstor\/data\/tmp",
        "tempdirectory": "\/cloudstor\/data\/tmp",
        "mail_smtpdebug": false,
        "mail_smtphost": "smtp.aarnet.edu.au",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "preview_office_cl_parameters": "",
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 100,
        "openssl": [],
        "activity_expire_days": 365,
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.4
  - cloudstortheme: 1.0.0
  - collections: 1.1.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - dicomviewer: 0.0.6
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.6.4
  - files_external: 0.7.1
  - files_jmol: 0.0.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2
  - files_thingiview: 0.0.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - filescan: 0.0.1
  - filesenderapp: 1.0
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - impersonate: 0.1.0
  - market: 0.2.2
  - music: 0.9.2
  - notifications: 0.3.1
  - onlyoffice: 2.0.3
  - password_policy: 2.0.0
  - provisioning_api: 0.5.0
  - renaming_api: 0.0.1
  - security: 0.0.2
  - swanviewer: 0.0.1
  - tenant_portal: 1.0.8
  - terms: 0.1
  - updatenotification: 0.2.1
  - user_saml: 0.4
Disabled:
  - cloudstor_issues
  - encryption
  - external
  - files_antivirus
  - systemtags
  - templateeditor
  - theme-example
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### PR DESCRIPTION
**Pull request by mdusher**
## Description
We've experienced an edge case where stream_read() will enter an infinite loop when one of the chunks of a web upload is invalid/corrupt as it never reads any more data, so stays in the same position for reading indefinitely.

## Related Issue
- Fixes https://github.com/owncloud/core/issues/34488

## Motivation and Context
Infinite loops are bad and it is holding files open.

## How Has This Been Tested?
This has been tested in our test environment which is a replica of our production environment (see original issue).

The process I used for testing this was:
- Open a window that has the ownCloud "uploads" directory  of the user you are using (eg.  /path/to/datadirectory/michael.usher@aarnet.edu.au/uploads)
- Clear out the directory of any files/directories (rm -rf web-file-upload-*) - this step is just to make step 4 work when we need it
- Get your "how to corrupt an upload command" ready (don't hit enter on it): `sudo -u www-data sh -c 'cd web-file-upload-* && truncate -s 0 $(ls -1 | tail -n1)'`
- Login to ownCloud as your chosen user
- Start uploading a file via the web interface
- Once it reaches 100%, wait for it to change to "Processing files..." then press enter on your "how to corrupt an upload" command (it essentially replaces it with a 0 byte file)
- Watch your logs for the never ending `rewinddir()` errors (not sure if this is just a symptom of our storage, so alternatively - find the pid of the php process for the upload and run `strace -s 1024 -p <pid>` and you'll see it constantly trying to open the same file over and over.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by mdusher** [comment]
This is just an idea on how to resolve this issue, it appears to work as expected (throws an exception which is then reported to the user in a friendly way).

**Review by PVince81 — APPROVED** [review]
:+1: makes sense, thanks

**Comment by PVince81** [comment]
@labkode FYI as you've observed something similar recently

**Comment by PVince81** [comment]
stable10: https://github.com/owncloud/core/pull/34558

**Pull request merged**
