### PR TITLE
[8.2] Escape like parameter in cache operations

### PR DESCRIPTION
**Pull request by icewind1991**
Simplified backport of #16604

cc @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks.

@karlitschek have a look at this simplified backport.

**Comment by karlitschek** [comment]
nice :+1:   please backport!

**Comment by MorrisJobke** [comment]
I did some basic testing and can't see any problems in the logs. Also files are properly handled. :+1: from my side.

**Comment by PVince81** [comment]
Manual testing works :+1:

Let me run smashbox once

**Comment by PVince81** [comment]
Smashbox passed, merging.

**Pull request merged**
