### PR TITLE
Ignore GD JPEG warnings

### LINKED ISSUE #21873: Thumbnails, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG
Hello,

I have some photos taken from a phone which render fine in gwenview and gimp, but give an error in owncloud. The errors I get in the owncloud.log file is
"imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG"

The web UI is unable to show the thumbnail.
The relevant packages i have installed are php56-gd-5.6.17 and jpeg-turbo-1.4.2

Google returned this
golang/go#3916
https://code.google.com/p/go/issues/detail?id=3916

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/core/issues/21873

<hr/>

@MorrisJobke @oparoz @rajil Please review and test.

### CODE REVIEW

**Comment by oparoz** [comment]
Test image: https://storage.googleapis.com/go-attachment/3916/2/xx.jpg

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by TheKaban** [comment]
Tested and works :+1:

**Pull request merged**
