### PR TITLE
Move OC\IntegrityCheck to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @LukasReschke @nickvergessen @MorrisJobke @PVince81

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:boom: 

````
PHP Fatal error:  Class 'OC\Integritycheck\Iterator\ExcludeFileByNameFilterIterator' not found in /ssd/jenkins/workspace/server-master-linux-php5.4-ci/database/sqlite/label/SLAVE/lib/private/IntegrityCheck/Checker.php on line 136
15:47:48 PHP Stack trace:
15:47:48 PHP   1. {main}() /usr/local/bin/phpunit:0
15:47:48 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:537
15:47:48 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:105
15:47:48 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:153
15:47:48 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:406
15:47:48 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
15:47:48 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
15:47:48 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:699
15:47:48 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:607
15:47:48 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
15:47:48 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
15:47:48 PHP  12. PHPUnit_Framework_TestCase->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:743
15:47:48 PHP  13. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:866
15:47:48 PHP  14. Test\IntegrityCheck\CheckerTest->testWriteAppSignature() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:866
15:47:48 PHP  15. OC\IntegrityCheck\Checker->writeAppSignature() /ssd/jenkins/workspace/server-master-linux-php5.4-ci/database/sqlite/label/SLAVE/tests/lib/integritycheck/checkertest.php:116
15:47:48 PHP  16. OC\IntegrityCheck\Checker->getFolderIterator() /ssd/jenkins/workspace/server-master-linux-php5.4-ci/database/sqlite/label/SLAVE/lib/private/IntegrityCheck/Checker.php:268

**Comment by rullzer** [comment]
Ah incorrect use statement... fixed.

**Comment by nickvergessen** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
