### PR TITLE
Added confirm delete of single file and selected files

### PR DESCRIPTION
**Pull request by ShamimIslam**
Implements proper delete confirm using OwnCloud tools. Required for large-scale file/users use. Delete icon is next to scroll elevator and is subject to accidental clicking (click on user menu, click on elevator). Delete loses sharing attributes. Restore does not restore sharing. Better to prevent the problem than to create an undo for a simple problem. Alternatively, this option can be turned into configurable feature. Best option would be a double push like the Apple Store "buy" or the Amazon music buy - first click primes the action. Second click creates the action. Primed action times out after 5s or some timeout. This is the simple fix. This topic has been discussed a number of times, but the "undo" does not resolve the problems that the "automatic delete" creates. Until the "undo" works correctly, this is the correct solution.

This contribution is MIT licensed.

### CODE REVIEW

**Comment by ShamimIslam** [comment]
This contribution is MIT licensed.

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Sorry, but as mentioned again and again we need undo for deletion. Confirmation is annoying and will get ignored after getting used to.

See https://github.com/owncloud/core/issues/119, I'll not comment more for now since I'm on vacation and honestly I'm getting tired of discussing this.

Cc @DeepDiver1975

**Comment by ShamimIslam** [comment]
Why is something EVERYONE that uses this in larger organizations with
larger data sets seems to want a bad idea? Why can't this be an option that
is available? Why do we have to have this draconian attitude that there is
only one possible user experience?

I just had to UNDO the hugest delete yesterday from an accidental mouse
click AND had to recover all the shared links from the delete.

Why are we FIGHITNG about something that should be a choice?

I am not the only one asking for this. We are just getting told that this
cannot be done.

And yet the solution is so simple

**Comment by jancborchardt** [comment]
@ShamimIslam hey – we agree on the problem so we don’t need to fight. :) I can see where you’re coming from with your suggestion, it’s just that modal dialogs have proven to not work very well to prevent errors.

Undo is becoming the more common solution for error prevention because
* people tend to just click »accept« on modal dialogs
* it’s simpler to realize errors when the file is visibly gone (instead of reading a text in a modal)

So undo will also solve your problem – all while being more usable. No need to insist on a specific implementation when the problem can also be solved more elegantly, right? The main problem is that we currently have _no_ solution in place at all, so the experience is of course not nice.

**Comment by jancborchardt** [comment]
@ShamimIslam And about the accidental clicking because of the delete icon position: Totally agree on that as well!

We need to put the file actions (except sharing) in an extra dropdown in the row. The issue for that is https://github.com/owncloud/core/issues/12081

That will also take care of that problem, and do for way better mobile usability. Ok?

**Comment by ShamimIslam** [comment]
Practically speaking this philosophical discussion of modal confirmation
dialog vs no confirmation, and delete vs undo is moot.

1. Every OS and platform either CAHNGES THE MODE OF THE WHOLE SCREEN for
delete or USES A MODAL CONFIRMATION DIALOG.
2. OwnCloud is the ONLY product that uses NO MODAL CONFIRMATION DIALOGAND
DOES NOT CHANGE THE MODE OF THE SCREEN for delete
3. Your delete/undo sequence has problems as listed in steps 1-5 of my
original email
4. This then is the problem - there are obviously many solutions.
5. Each day we delay in implementing a solution that is retained between
upgrades is another day lost in moving out of pilot for me
6. Other enterprise users are still without a solution and may have a
similar problem
7. Since my modal delete confirmation was implemented, not a single call
has come through to recover files or restore sharing
8. I have provided a possible solution that has been proven to work in the
field and is not theoretical
9. Your team has only provided a lot of theory but no solution that works
yet

So please, either use the solution I put in, modify it so it is an option
that can be enabled, or find another solution that satisfies all 5 of my
original points (and if you really do want to have no confirmation - you
can create a button that puts the whole screen in delete mode like in the
iPhone 5).

I don't want a discussion any more. I don't want further explanations. I
have provided action on my part. Please provide the same.

If this is truly an agile environment, we should be able to have both a
temporary solution and a permanent fix.

Why we are waiting for the "perfect" solution is beyond me.

**Comment by LukasReschke** [comment]
:-1: - Doesn't work - throws an JS error

**Comment by LukasReschke** [comment]
```
 Uncaught SyntaxError: Unexpected token ;
versions.js?v=83ca6264f570b8204d4fbed28b9fd084:25 Uncaught TypeError: Cannot read property 'register' of undefinedversions.js?v=83ca6264f570b8204d4fbed28b9fd084:25 (anonymous function)jquery.min.js?v=83ca6264f570b8204d4fbed28b9fd084:4 x.Callbacks.cjquery.min.js?v=83ca6264f570b8204d4fbed28b9fd084:4 x.Callbacks.p.fireWithjquery.min.js?v=83ca6264f570b8204d4fbed28b9fd084:4 x.extend.readyjquery.min.js?v=83ca6264f570b8204d4fbed28b9fd084:4 q
localhost/:1 GET http://localhost/core/vendor/jquery/dist/jquery-migrate.min.map 404 (Not Found)
```

**Comment by ShamimIslam** [comment]
I'm running it on ownCloud 7 with no issues. I did have a problem in
ownCloud 8 - it was thowing a JS error

ownCloud changed the name of the delete parameter from "filename" to
"fileName" in version 8 and context of the patch has changed slightly from
what I can see. I had to create a fix and a new patch.

I can post it if you want.

What version of ownCloud are you running and have you traced the callback
in to the JavaScript? I did. That's how I found the error.

Thanks.

**Comment by LukasReschke** [comment]
> What version of ownCloud are you running and have you traced the callback in to the JavaScript? I did. That's how I found the error.

Well – the master version that your patch is pointing at. Patches contributed as Pull Request have to work flawlessly when checking out the branch if you want even to have the tiniest chance of get them merged ;-)

**Comment by ShamimIslam** [comment]
Anyone know how I can have two different versions of a pull request so that it can be applied to different versions of ownCloud? Or do I just update all the files for the latest copy?

Thanks in advance.

**Comment by ShamimIslam** [comment]
You have to understand - I was pointing to the master while it was still ownCloud 7. I will post the update. I do have it fixed.

Please understand that *I* did not *change* the fileactions.js and filelist.js files parameter names - ownCloud 8 changed them and that is what broke my pull request. I am not sure what the advantage of "filename" over "fileName" was supposed to correct or if it was a large scale search and replace.

**Comment by ShamimIslam** [comment]
Ok - I need help. How do I update my local git repo with the updates from the master? I can't add my new fix/update until I have that because I don't want to lose the history of my update in this repo either.

Any assistance on the command line syntax I should be looking at would be appreciated.

I'm guessing it's "git merge" but I don't know the target to merge with.

**Comment by ShamimIslam** [comment]
Nm. I've fixed the fileactions.js and filelist.js to match ownCloud 8. Figured out how to sync - much more involved than I would have expected. Multiple commands, but I found it online.

**Comment by ShamimIslam** [comment]
git remote add upstream https://github.com/owncloud/core
git fetch upstream
git merge upstream/master
git add
git commit
git push

Hopefully this has been done right.

**Comment by ShamimIslam** [comment]
Ok - that's the last of it. I think I got it all.

**Comment by DeepDiver1975** [comment]
This PR collides with #119 - we can only have one approach

**Comment by ShamimIslam** [comment]
I can't help that your one approach does not satisfy users with large
filesets (20G and upwards per account).There are many on the mailing list
that have clamored for this exact functionality.

I have provided working solution. I am not just blowing off steam. Instead
of taking advantage of the opportunity, you are choosing to sit on your
hands because your long-term vision clashes.

If Linux followed this same process, we'd still be waiting for it to
complete - oh wait - that's GNU Hurd and Minix....right?

Issue #119 in my mind is still broken and long way away. It needs much
refinement before it will serve for large scale use.

So until then, ownCloud will remain as a niche application for small scale
mom-and-pop use-at-home systems that cannot handle large scale accidental
delete problems. I need it to scale today. I am simply providing my working
scalable solution to others.

It may be better to be more meritocratic and less authoritarian. I'm not
even saying "democratic" - it will allow you to overtake the other
providers such as Google and Dropbox that DO NOT HAVE the accidental delete
problem.

Thank you for your review. Maybe one day my PR will be accepted, but I will
keep maintaining it and I will keep using it and I will keep it active.

**Comment by jancborchardt** [comment]
> I can't help that your one approach does not satisfy users with large
filesets (20G and upwards per account).

@ShamimIslam how so? You still didn’t state that. There is actually _no_ difference in our approaches:
* for confirmation, the deletion only gets carried out on clicking »Ok, delete«
* for undo deletion, the deletion only gets carried out when not clicking »undo deletion« for ~5 seconds

Since you mention Google – they employ undo since a long time, even for Gmail.

The second problem (the accidental clicking of the delete icon on scrolling) will be solved by putting the file actions in a dropdown. See https://github.com/owncloud/core/issues/12081

**Comment by ShamimIslam** [comment]
I don't see where the "OK, delete" is mentioned - can you clarify? You
mention "confirmation" - would like to see where that is at. I only did
mine based on the default ownCloud dialogs.

When does the confirmation get used versus the timeout?

Google's "Drive" does do a confirmation. :)

**Comment by Xenopathic** [comment]
@ShamimIslam Actually, Google Drive uses an undo:

screenshot - 050315 - 16 27 55

**Comment by ShamimIslam** [comment]
Ok - just checked. You are correct. It no longer confirms the delete. Did
you note that it's still apples and oranges though?

The problem is not "delete" without confirm. The problem is "accidental
delete".

Please explain to me how you would perform an accidental delete while
simply navigating the position of the page on Google Drive.

Now explain how you would perform an accidental delete while navigating the
position of the page in ownCloud (scrolling).

This is the problem.

Google Docs is already 2 clicks - the "confirm" is implicit. In ownCloud,
this is one click - no implicit feedback that the file is going to be acted
on until it is already acted on.

**Comment by MorrisJobke** [comment]
@ShamimIslam @jancborchardt Can we have a solution here? We don't want a modal and the undo thing. I vote for working on the undo for 8.1. Is someone already working on this? cc @DeepDiver1975

**Comment by ShamimIslam** [comment]
When you get a solution that does the undo properly including the restoring
shares, let me know. If you like the "undelete and manually restore shared
folders" feature, enjoy.

I wold prefer to have an application that is enterprise-ready and not
waiting-to-be-enterprise-ready. I can't get funding for the latter. My
solution gets me to enterprise-ready so that I can get funding. It is for
anyone that WANTS to use it while folks are trying to sort out how to
create the "undo".

What's interesting to note is that I've been struggling with this problem
since v5.0 but it's only when I go implement a solution and publicize is
that everyone gets upset that it's not the "right" solution.  I thought
distributed agile development was all about providing interim functionality
that could evolve into something better. Not a way to leave gaping holes
until the the desired solution is implemented..

I for one like the peace and quiet of not having frantic support calls and
having funding for the required hardware to support all users.

**Comment by jancborchardt** [comment]
@ShamimIslam 

> Ok - just checked. You are correct. It no longer confirms the delete. Did
you note that it's still apples and oranges though?

Well, you brought up the comparison in the first place.


> The problem is not "delete" without confirm. The problem is "accidental
delete".
> Please explain to me how you would perform an accidental delete while
simply navigating the position of the page on Google Drive.
> Now explain how you would perform an accidental delete while navigating the
position of the page in ownCloud (scrolling).

As I mentioned above:
The second problem (the accidental clicking of the delete icon on scrolling) will be solved by putting the file actions in a dropdown. See #12081

**Comment by jancborchardt** [comment]
@ShamimIslam and since you want to see it get fixed and also are able to submit pull requests – please just help us on making #119 a reality, ok?

**Comment by ShamimIslam** [comment]
Was attempting to explain to Morris what the problem was as he seemed be
unaware of why I was requesting the change.

Do you have a target for the dropdown?

**Comment by jancborchardt** [comment]
@ShamimIslam if by target you mean when we plan to have it solved: I hope to be able to work on it for 8.2

**Comment by jancborchardt** [comment]
@ShamimIslam I have a suprise for you: https://github.com/owncloud/core/pull/14962 :) added some whitespace on the right of the delete function to prevent it being clicked accidentally when trying to scroll. Hope that helps to some extent while we wait for the dropdown.

**Comment by ShamimIslam** [comment]
While this helps, my constituents have expressed that they prefer to have
both the confirm and the space - until the two click delete is in place (I
think I saw something like that) or the context menu for the delete. They
did mention some trepidation that the delete in the context menu still
creates opportunities for accidental delete since there are other options
in the context menu and there is not opportunity to recover from the delete
click without either a confirm or a delayed execution. For now, I've been
asked to retain the confirm.

**Comment by jancborchardt** [comment]
@ShamimIslam we’re working on the undo mechanism as we speak. :)

**Comment by ShamimIslam** [comment]
FYI - I have it running on ownCloud 8.0. Will validate if it works for
8.0.2 this weekend. Does that help?

**Comment by watermark** [comment]
The great thing about owncloud is it supports plugins, so if you don't like something, you can "fix" it.  This is crude and hot off the presses, but it works for me.

https://apps.owncloud.com/content/show.php/Delete+Confirmations?content=169968

**Comment by ShamimIslam** [comment]
Awesome. I did not know how to do this with this particular feature. I'll
have to check it out.

**Comment by jancborchardt** [comment]
Great stuff @watermark – that’s what I’m talking about! :) I’ll close this pull request then since your app is basically the same thing.

The undo deletion will also come with 8.2: https://github.com/owncloud/core/pull/15002

**Pull request closed without merging**
