### PR TITLE
Encryption personal panel fix

### LINKED ISSUE #27398: [10.0] after admin enables the encryption recovery key, users don't see the encryption section in the settings
### Steps to reproduce
1. as admin enable encryption
2. as admin add recovery
3. as user try to opt in to recovery key

cc @tomneedham 

### Expected behaviour
there should be an encryption section in the settings with a checkbox to opt in to recovery

### Actual behaviour
```json
{
  "reqId": "4mLwfKUAMQ2Vmjb01llj",
  "remoteAddr": "127.0.0.1",
  "app": "no app in context",
  "message": "Failed to load panel: OCA\\Encryption\\Panels\\Personal with error: Could not resolve OCP\\ILogger! Class can not be instantiated",
  "level": 3,
  "time": "2017-03-16T10:53:29+00:00",
  "method": "GET",
  "url": "/oc/core/index.php/settings/personal?sectionid=general",
  "user": "admin"
}
```

Trying to fiddle with the url doesn't help:
```json
{
  "reqId": "rDkr6xVYyal9lZ0ELOF0",
  "remoteAddr": "127.0.0.1",
  "app": "no app in context",
  "message": "Failed to load panel: OCA\\Encryption\\Panels\\Personal with error: Could not resolve OCP\\ILogger! Class can not be instantiated",
  "level": 3,
  "time": "2017-03-16T09:37:45+00:00",
  "method": "GET",
  "url": "/oc/core/index.php/settings/personal?sectionid=encryption",
  "user": "admin"
}
```
Using a non admin user gives the same error.
### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** sqlite

**PHP version:** 5.6

**ownCloud version:** git master

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** git

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/27398

Also bonus fix: now clicking on the "Enable" label properly clicks the checkbox. This has been annoying me for years!

@tomneedham @butonic please review

### CODE REVIEW

**Comment by tomneedham** [comment]
Nice work vincent - at some point I'd like to understand your method of debugging this!

**Comment by PVince81** [comment]
@tomneedham XDebug + step by step debugging into the DI resolving logic

**Comment by felixboehm** [comment]
👍  code looks good.
Video with setup and debug best practices missing.

**Comment by settermjd** [comment]
@PVince81 testing this with https://docker.oc.solidgear.es:63924 still shows the panel error. Am I missing something here?

**Comment by PVince81** [comment]
@settermjd ah, maybe because it was switched to master key which doesn't support/require recovery keys... in that case we should remove the panel completely. In "user key" mode the panel should be there.

**Pull request merged**
