### PR TITLE
[stable10] Revert "Highlight files after setFiles"

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/core/issues/28106

See ticket for steps.

### CODE REVIEW

**Comment by PVince81** [comment]
reverts https://github.com/owncloud/core/pull/28665

**Comment by SergioBertolinSG** [comment]
Works 👍

**Comment by PVince81** [comment]
JS tests passed on CI. Waiting for Travis UI tests though.

**Comment by phil-davis** [comment]
Note: Travis job https://travis-ci.org/owncloud/core/jobs/275851372 got:
```
     exception 'SensioLabs\Behat\PageObjectExtension\PageObject\Exception\UnexpectedPageException' with message 'Expected to be on "http://owncloud:8889/index.php/apps/files/" but found "http://owncloud:8889/index.php/login?redirect_url=%252Findex.php%252Fapps%252Ffiles%252F" instead' in /home/travis/build/owncloud/core/tests/ui/features/lib/FilesPage.php:166
```
is a "random" thing that happens sometimes (the SauceLabs video will show a sudden "CSRF Failed"), not related to this PR.

The job could be restarted, but it passed all other scenarios fine.

**Pull request merged**
