### PR TITLE
[Tests-only] Remove test tags for 336

### LINKED ISSUE #252: Edit public link OCS response
The OCS response for public links is currently not compliant and might even be empty.
Just writing this from memory as it's a remaining task to look into.

I expect that some API tests will reveal this when enabled.

@refs FYI

### LINKED ISSUE #336: Public share URL truncated in response
### Steps

1. Create a public link share
1. Copy public link and extract the token
1. Get the share with curl using its token: https://localhost:9200/ocs/v1.php/apps/files_sharing/api/v1/shares/$TOKEN
1. Look at the "url" field

### Expected result
Full URL present

### Actual result
URL is missing its prefix and doesn't start with http

Many sharing tests are checking the URL and also some clients use it from here, so we should fix it.
In the code it relies on the "Origin" header, but that one is not always set, at least not when called on API level.

@refs FYI

### PR DESCRIPTION
**Pull request by PVince81**
Fix for https://github.com/owncloud/ocis-reva/issues/336 in https://github.com/cs3org/reva/pull/945

Closes https://github.com/owncloud/ocis-reva/issues/336
Closes https://github.com/owncloud/ocis-reva/issues/252

### CODE REVIEW

**Comment by PVince81** [comment]
Proof PR here: https://github.com/owncloud/ocis-reva/pull/366

**Comment by PVince81** [comment]
Tests in the proof PR have passed

**Comment by PVince81** [comment]
oh no...

**Comment by PVince81** [comment]
reopening proof PR to reverify...

**Comment by PVince81** [comment]
the proof is green: https://github.com/owncloud/ocis-reva/pull/366

**Review by IljaN — APPROVED** [review]

**Review by micbar — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
