### PR TITLE
Wrap the entire dav PUT in a read lock

### LINKED ISSUE #16569: Slow transfer can bypass etag precondition check, no conflict file
### Steps to reproduce
1. Create a file "test.txt" with the contents "initial"
2. Setup as sync client
3. Add `sleep(30)` here: https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/file.php#L190 (before the final rename)
4. Change "test.txt" locally, set its contents to "local" and let the sync client upload the file
5. While it's uploading, change "test.txt" in the web UI and set the contents to "web" and save it
6. Wait for the sync to finish
7. Check the file's contents

### Expected result
Conflict must occur.

### Actual result
File edited from web UI was overwritten

This happens because the precondition check happens before the transfer is finished.
If chunk assembly or writing the part file takes longer (for example with ext storage), we're way past the precondition check and the write operation will simply overwrite what's there.

I didn't check what happens with the etag and other clients, it might also create a situation where one client believes it has the latest version even though the contents is different (to be confirmed).

I hope we can fix this somehow with high-level file locking https://github.com/owncloud/core/issues/11804. We need to make sure the precondition check + final rename are atomic.

### Versions
Observed on master (f70c309c2d8044d46ee3daa74d1a53f48f11d53f)

@dragotin @guruz FYI, maybe this was already known.

@DeepDiver1975 @karlitschek @icewind1991

### PR DESCRIPTION
**Pull request by icewind1991**
Acquire a read lock in the beforeMethod hook to ensure we have the file read locked when precondition checks are made.

Fixes #16569

cc @DeepDiver1975 @PVince81

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works. Also fixes owncloud/files_texteditor#61

**Comment by MorrisJobke** [comment]
:+1:

**Comment by Henni** [comment]
@MorrisJobke does this really solve the frontend issue owncloud/files_texteditor#61 for you?

**Comment by MorrisJobke** [comment]
> @MorrisJobke does this really solve the frontend issue owncloud/files_texteditor#61 for you?

Sorry. Wrong paste. It fixes https://github.com/owncloud/files_texteditor/issues/93

**Comment by PVince81** [comment]
Breaks chunk upload:
```
{"reqId":"lfpmolA5MBbqxHztmKvS","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 5242880 got 4866048\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(100): OC\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #255)\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(115): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #255)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('data2.dat-chunk...', Resource id #255)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('data2.dat-chunk...', Resource id #255, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(132): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#10 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":340}","level":4,"time":"2015-08-06T15:58:13+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/data2.dat-chunking-3130333669-25-0"}
```

This file size is 126679286.
Works correctly on master with locking enabled.

@icewind1991 when touching webdav upload code please always test with both non-chunked upload and chunked upload.

**Comment by icewind1991** [comment]
chunked problems should all be fixed now (and covered with unit tests)

**Comment by MorrisJobke** [comment]
I tested this with and without file locking based on the webdav interface.

Worked so far :+1:

**Comment by PVince81** [comment]
@MorrisJobke the problem was based on file chunking, so must also test with the sync client.

**Comment by PVince81** [comment]
#### With locking
- [x] TEST: sync client chunk upload
- [ ] TEST: sync client chunk upload + overwrite
- [ ] TEST: webdav no-chunk upload
- [ ] TEST: webdav no-chunk upload + overwrite
- [ ] TEST: smashbox basic sync

#### Without locking
- [x] TEST: sync client chunk upload
- [ ] TEST: sync client chunk upload + overwrite
- [ ] TEST: webdav no-chunk upload
- [ ] TEST: webdav no-chunk upload + overwrite
- [ ] TEST: smashbox basic sync

**Comment by PVince81** [comment]
Note that I am testing with encryption enabled too.
I'll continue testing later, I seem to have stumbled on an encryption issue. Need to check whether it happens on master or only on this branch.

**Comment by PVince81** [comment]
- [ ] BUG: encryption (no locking), sync client upload big file (120MB). Wait. Touch the file to trigger a reupload+overwrite. => file cannot be deleted/downloaded in web UI due to key issues, getting 403. This works properly on master.

**Comment by icewind1991** [comment]
> BUG: encryption (no locking), sync client upload big file (120MB). Wait. Touch the file to trigger a reupload+overwrite. => file cannot be deleted/downloaded in web UI due to key issues, getting 403. This works properly on master.

I can't reproduce this, either manually or automated (#18901) and I have a hard time seeing how these changes can introduce an issue with locking disabled

**Comment by PVince81** [comment]
Can you rebase ?

**Comment by PVince81** [comment]
Seems the chunk upload with encryption works now. Let me retest the other cases too.

**Comment by PVince81** [comment]
Also I can confirm that the hooks still work as I could see versions created for both chunked and non-chunked overwritten files.

I can't test the smashbox stuff, it's broken on master: https://github.com/owncloud/core/issues/19031

**Comment by icewind1991** [comment]
@PVince81 @DeepDiver1975 can this be merged?

**Comment by PVince81** [comment]
Ok to merge from me :+1: 

But please have a look at the failing smashbox tests on master.

**Pull request merged**
