### PR TITLE
Clean up files_external

### PR DESCRIPTION
**Pull request by rnicoll**
Apply style corrections requested in #13190 to other plugins within the files_external application.

### CODE REVIEW

**Comment by Xenopathic** [comment]
Tested, fixes the UI issues noted in the other PR. :+1:

@rnicoll you seem good at this - I don't suppose you could have a look at why the checkboxes for backends like Amazon S3 are badly laid out? :smile: Perhaps if it hasn't been merged by then, you could extend this PR?

**Comment by nickvergessen** [comment]
the app.php change should be done in a different PR from my opinion, since it only changes `array()` to `[]` which is kind of unnecessary while being so close to a major release.

**Comment by DeepDiver1975** [comment]
scheduled for 8.1 just like #13190 - THX a lot!

**Comment by DeepDiver1975** [comment]
@owncloud-bot retest this please

**Comment by PVince81** [comment]
:+1: tested, works

**Pull request merged**
