### PR TITLE
Open menus on hover

### LINKED ISSUE #23683: Any menu which opens on click should also open on hover already
This is just to anticipate the click and make interaction on desktop a bit faster. A subsequent click should then of course not close it, but keep it open. (Cause otherwise it will interfere with the click action people are used to currently.)

This goes for the following menus, which are all popover-style:
- App menu in the top left
- User menu in the top right
- Action menu in the files list for every row
- Action menu when it’s used anywhere else, like in the app-navigation (like in News and to be coming in the Calendar app, see https://github.com/owncloud/calendar/pull/400) cc @BernhardPosselt @georgehrke 
- … anything I missed? (Like maybe even the bottom left Settings menu in-app? Not sure about that though since it’s not popover-style.)

cc @owncloud/designers @PVince81

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes #23683

Menus:
- [x] App menu in the top left
- [x] User menu in the top right
- [ ] Action menu in the files list for every row
- [ ] Action menu when it’s used anywhere else, like in the app-navigation

TODO:
- [x] define hover timeout as constant
- [ ] don't ignore subsequent clicks forever
- [ ] close menus that were opened by hovering when moving the mouse out of the element

### CODE REVIEW

**Comment by jancborchardt** [comment]
Right, when leaving the hover area, the menu should stay open for maybe 300ms more to be error-friendly. I guess that's what you mean by hover timeout?

**Comment by ChristophWurst** [comment]
> I guess that's what you mean by hover timeout?

Yes, exactly

**Comment by nickvergessen** [comment]
Can you also check the notifications app, that is also using the js menu system.
Enable the app and then receive a remote share to make it visible

**Comment by jancborchardt** [comment]
Right, notifications tray should definitely use the same mechanism. Good catch @nickvergessen!

**Comment by nickvergessen** [comment]
@ChristophWurst when this is in, send a mail to the mailing list, so app devs can check if their menus still work as intended.

**Comment by FleetAdmiral** [comment]
Hey , new to Open Source here and would like to take this up! Would love some assistance if possible too!

**Comment by ChristophWurst** [comment]
Hi @FleetAdmiral,
awesome, feel free to take over this PR/branch. You can join us in our IRC channel #owncloud-dev on FreeNode if you need help with the task. Thank you

**Comment by FleetAdmiral** [comment]
Thanks @ChristophWurst , will join you on your irc!

**Comment by PVince81** [comment]
We're past feature freeze, moving to 9.2

**Comment by PVince81** [comment]
Is there still interest in getting this feature finished ?

**Comment by PVince81** [comment]
backlog for now.

cc @felixheidecke

**Pull request closed without merging**
