### PR TITLE
Move \OC\Hooks to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @MorrisJobke @nickvergessen @DeepDiver1975

### CODE REVIEW

**Comment by icewind1991** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Woot:

```

There was 1 failure:

1) OCA\Files_sharing\Tests\EtagPropagation::testOwnerWritesToSingleFileShare
Failed asserting that the etag for "" of user test-share-user2 has changed
Failed asserting that 'be777e782c10b15cd42a023d6043ac98' is not equal to <string:be777e782c10b15cd42a023d6043ac98>.

/ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/files_sharing/tests/propagationtestcase.php:63
/ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/apps/files_sharing/tests/etagpropagation.php:197
```

**Comment by nickvergessen** [comment]
quite "normal" nowerdays, happens like 1 in 20

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
