### PR TITLE
[backport #13740] backport #13740 to stable7

### PR DESCRIPTION
**Pull request by blizzz**
Same as https://github.com/owncloud/core/pull/13740 but for stable7

Also incorporates a backport of #15606

### CODE REVIEW

**Comment by blizzz** [comment]
@owncloud-bot retest this please

**Comment by blizzz** [comment]
One bug was detected by scrutinizer, will fix it

**Comment by DeepDiver1975** [comment]
@blizzz 

````
00:25:58.982 PHP Fatal error:  Call to undefined method Mock_Access_b3b5cb35::getFilterForUserCount() in /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/user_ldap/group_ldap.php on line 266
00:25:58.982 PHP Stack trace:
00:25:58.982 PHP   1. {main}() /usr/local/bin/phpunit:0
00:25:58.982 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:605
00:25:58.982 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
00:25:58.982 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
00:25:58.983 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:423
00:25:58.983 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
00:25:58.983 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
00:25:58.983 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:711
00:25:58.983 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:641
00:25:58.984 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:25:58.984 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:25:58.984 PHP  12. PHPUnit_Framework_TestCase->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:775
00:25:58.984 PHP  13. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:905
00:25:58.984 PHP  14. OCA\user_ldap\tests\Test_Group_Ldap->testCountEmptySearchString() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:905
00:25:58.984 PHP  15. OCA\user_ldap\GROUP_LDAP->countUsersInGroup() /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/user_ldap/tests/group_ldap.php:86
00:25:58.984 PHP  16. OCA\user_ldap\GROUP_LDAP->countUsersInPrimaryGroup() /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/user_ldap/group_ldap.php:554
00:25:58.984 PHP  17. OCA\user_ldap\GROUP_LDAP->prepareFilterForUsersInPrimaryGroup() /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/user_ldap/group_ldap.php:311
00:25:59.066 PHP Warning:  Unknown: Cannot destroy the zip context in Unknown on line 0
00:25:59.066 PHP Stack trace:
00:25:59.066 PHP   1. {main}() /usr/local/bin/phpunit:0
00:25:59.066 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:605
00:25:59.067 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
00:25:59.067 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
00:25:59.067 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:423
00:25:59.067 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
00:25:59.067 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:751
00:25:59.068 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:711
00:25:59.068 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:641
00:25:59.068 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:25:59.068 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
00:25:59.068 PHP  12. PHPUnit_Framework_TestCase->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:775
00:25:59.068 PHP  13. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:905
00:25:59.068 PHP  14. OCA\user_ldap\tests\Test_Group_Ldap->testCountEmptySearchString() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:905
00:25:59.068 PHP  15. OCA\user_ldap\GROUP_LDAP->countUsersInGroup() /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/user_ldap/tests/group_ldap.php:86
00:25:59.068 PHP  16. OCA\user_ldap\GROUP_LDAP->countUsersInPrimaryGroup() /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/user_ldap/group_ldap.php:554
00:25:59.068 PHP  17. OCA\user_ldap\GROUP_LDAP->prepareFilterForUsersInPrimaryGroup() /var/jenkins/workspace/pull-request-analyser-ng-simple@2/label/SLAVE/apps/user_ldap/group_ldap.php:311
00:25:59.068 PHP Warning:  Unknown: Cannot destroy the zip context in Unknown on line 0

**Comment by blizzz** [comment]
@DeepDiver1975 that's what i mentioned earlier. fixed now.

**Comment by blizzz** [comment]
@owncloud-bot retest this please

**Comment by DeepDiver1975** [comment]
has to be scheduled for 7.0.6 - THX

**Comment by blizzz** [comment]
This one also needs testers/reviewers @jnfrmarks @MorrisJobke @LukasReschke

**Comment by blizzz** [comment]
Oh my, this has a beard.

I will rebase and add the backport of https://github.com/owncloud/core/pull/15606 which is necessary for #13533 as well.

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@owncloud-bot retest this please

**Comment by MorrisJobke** [comment]
@cmonteroluque @craigpg This is the same as #16456 for stable7

**Comment by MorrisJobke** [comment]
@sbelov1 @bboule @jnfrmarks @plastilincheg @rjaeckel @gig13 Please test. I tested this with an LDAP instance and all works like before and no errors are logged.

:+1:

**Comment by DeepDiver1975** [comment]
we need testing power here @rperezb THX

**Comment by bboule** [comment]
Will ask team to test here as well!!

**Comment by sbelov1** [comment]
I've tested this in my internal lab and it did fix the issue. Correct number of Domain Users was shown in the app and Users page.

**Comment by DeepDiver1975** [comment]
> I've tested this in my internal lab and it did fix the issue.

treating this as :+1:

**Comment by rperezb** [comment]
@DeepDiver1975 hey @jvillafanez will check it, he has been working on checking 7.0.6 bug fixing

**Pull request merged**
