### PR TITLE
\OCP\DB to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @nickvergessen @MorrisJobke @PVince81 @LukasReschke @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1: works here

**Comment by nickvergessen** [comment]
:+1:

**Comment by PVince81** [comment]
I see you rebased 21 hours ago, and Jenkins still hasn't given an answer ?? :frowning: @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> I see you rebased 21 hours ago, and Jenkins still hasn't given an answer ?? :frowning: @DeepDiver1975

Sometimes notifications between github and jenkins get lost ... bad luck

**Comment by PVince81** [comment]
another one:
```
06:16:11 [Tue May 17 06:16:24 2016] ::1:37821 [404]: /ocs/v2.php/cloud/users/user0
06:16:11 Build timed out (after 60 minutes). Marking the build as aborted.
```

@DeepDiver1975 can we increase the timeout to 120 minutes for integration tests ? There will be more and more such tests coming with the new features...

**Pull request merged**
