### PR TITLE
improved app description for the default encryption module

### PR DESCRIPTION
**Pull request by schiessle**
improved app description and adjust it to the way the new encryption module works.

@MTRichards are you OK with it? Maybe you can also check if the English is OK.

As discussed here https://github.com/owncloud/core/issues/17779

cc @jospoortvliet @Raydiation 

@Xenopathic maybe you can also check the wording as a native speaker

### CODE REVIEW

**Comment by Raydiation** [comment]
:+1: 

We should also improve the current message on the settings page which reads atm:

** Encryption is a one way process. Once encryption is enabled, all files from that point forward will be encrypted on the server and it will not be possible to disable encryption at a later date. This is the final warning: Do you really want to enable encryption?**

**Comment by karlitschek** [comment]
might make sense to backport :+1:

**Comment by schiesbn** [comment]
@Raydiation This text was originally written by @MTRichards. Maybe you want to suggest a improved version and discuss it with him? Feel free to open a PR with your suggestion.

**Comment by Xenopathic** [comment]
Language is good :+1:

**Comment by MTRichards** [comment]
Text is ok. Should we also mention the external storage encryption too? maybe bring it back in the last sentence?

"Please read the documentation to know all implications before you decide to enable server-side encryption."
to
"Please read the documentation for a complete description of the consequences of using encryption prior to enabling server-side encryption, such as the implications for external storage."

**Comment by Raydiation** [comment]
I'm preparing a pull request ;)

**Comment by jospoortvliet** [comment]
:+1: on this!

**Pull request merged**
