### PR TITLE
[stable8.2] Properly hide strengthify after password change

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/core/pull/19625

Please review @MorrisJobke @schiesbn @rullzer @jancborchardt

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by LukasReschke** [comment]
… looking at labels helps :speak_no_evil: …

**Comment by PVince81** [comment]
Resent here: https://github.com/owncloud/core/pull/19782

**Pull request merged**
