### PR TITLE
Fixes alignment tooltip issues.

### PR DESCRIPTION
**Pull request by raghunayyar**
A fix for https://github.com/owncloud/core/issues/18601

check @jancborchardt @owncloud/designers

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Makes it better, but this needs to be tweaked also a bit more. Maybe in a separate PR.

**Comment by MorrisJobke** [comment]
bildschirmfoto von 2015-08-29 12-54-18

On the other side it doesn't work well for long file names.

**Comment by MorrisJobke** [comment]
:-1: this break was introduced with this PR

**Comment by raghunayyar** [comment]
weird, it looks just on mine, on it.
screen shot 2015-08-29 at 1 25 13 pm

**Comment by MorrisJobke** [comment]
> weird, it looks just on mine, on it.

Try a longer filename ;)

**Comment by raghunayyar** [comment]
Pushed. I am using ellipsis on really long file names now. @jancborchardt

**Comment by raghunayyar** [comment]
Hold on, there is something wrong here. Damn, I am rushing this.

**Comment by raghunayyar** [comment]
I am closing this PR as I feel the sidebar needs some semantic love. I will make that a separate PR which will fix this as well.

**Comment by jancborchardt** [comment]
@raghunayyar keep the changes small, remember. ;) No need for a rework branch of the sidebar – focus on the issue at hand.

**Pull request closed without merging**
