### PR TITLE
disable submit button while groupname is empty

### LINKED ISSUE #14969: User management: useless modal error when group input not filled in
When you add a group, but don’t specify a name before clicking the plus [+] button, this error appears:

> A valid group name must be provided

Instead, the plus button should just be disabled when the input is empty.

@raghunayyar @icewind1991

### PR DESCRIPTION
**Pull request by icewind1991**
Fixes #14969

cc @jancborchardt

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Works :+1:

**Comment by MorrisJobke** [comment]
```
15:05:09 Finished: SUCCESS
```

**Comment by jancborchardt** [comment]
Nice, great stuff.

@MorrisJobke what about Jenkins?

**Comment by jancborchardt** [comment]
@owncloud-bot retest this please

**Comment by karlitschek** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@jancborchardt Jenkins reported the wrong state. Therefore I copied the result from the console ;)

**Comment by MorrisJobke** [comment]
But I'm fine with waiting for a fully successful test run.

**Comment by jancborchardt** [comment]
Nice

**Comment by jancborchardt** [comment]
Big thank you @icewind1991! :)

**Pull request merged**
