### PR TITLE
make htmlPrefilter an identity function

### PR DESCRIPTION
**Pull request by C0rby**
## Description

The used version of jQuery contains a potential XSS vulneratbility.
This patch is a suggested workaround.
See https://github.com/advisories/GHSA-gxr4-xjj5-5px2

## Related Issue

- Fixes https://github.com/owncloud/security-tracker/issues/344

## Motivation and Context

Since we don't upgrade the libraries we need to patch security changes.

## How Has This Been Tested?

- it hasn't been yet

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by micbar — APPROVED** [review]

**Comment by micbar** [comment]
Needs changelog. Category `security`

**Comment by phil-davis** [comment]
I will make a "backport" to `release-10.5.0` branch.

**Comment by C0rby** [comment]
Thanks you, @phil-davis!

**Comment by phil-davis** [comment]
PR #37599 t `release-10.5.0` branch.

**Comment by ho4ho** [comment]
@C0rby Fix also https://github.com/owncloud/core/issues/37463 ?

**Comment by C0rby** [comment]
> @C0rby Fix also https://github.com/owncloud/core/issues/37463 ?

Yes, that is the same issue.

**Pull request merged**
