### PR TITLE
Move user_ldap to PSR-4

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by rullzer** [comment]
Rebased to fix conflict... lets see what CI says...

**Comment by PVince81** [comment]
Can't properly test LDAP because of https://github.com/owncloud/core/issues/24743

**Comment by nickvergessen** [comment]
Tests pass now @rullzer +1?

**Comment by PVince81** [comment]
Ok, after merging with master LDAP still works :+1:

**Comment by PVince81** [comment]
@rullzer @davicente second review ?

**Comment by PVince81** [comment]
And here are the conflicts... @nickvergessen can you rebase?

**Comment by nickvergessen** [comment]
done

**Comment by PVince81** [comment]
or @SergioBertolinSG @davitol ? (quick LDAP retest)

**Comment by PVince81** [comment]
Unit tests don't run any more locally (master is fine):
```
± % ./autotest.sh sqlite | tee test.log 2>&1
Using PHP executable /usr/bin/php
Parsing all files in lib/public for the presence of @since or @deprecated on each method...

Using database oc_autotest
Setup environment for sqlite testing on local storage ...
Installing ....
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
ownCloud is not installed - only a limited number of commands are available
{"reqId":"xXZWAtzUZ8JCxhBBCT2X","remoteAddr":"","app":"PHP","message":"file_put_contents(\/srv\/www\/htdocs\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/srv\/www\/htdocs\/owncloud\/lib\/private\/Setup.php#499","level":3,"time":"2016-05-25T14:15:08+00:00","method":"--","url":"--","user":"--"}
{"reqId":"xXZWAtzUZ8JCxhBBCT2X","remoteAddr":"","app":"PHP","message":"file_put_contents(\/srv\/www\/htdocs\/owncloud\/data\/index.html): failed to open stream: Permission denied at \/srv\/www\/htdocs\/owncloud\/lib\/private\/Setup.php#500","level":3,"time":"2016-05-25T14:15:08+00:00","method":"--","url":"--","user":"--"}
creating sqlite db
ownCloud was successfully installed
{"reqId":"xXZWAtzUZ8JCxhBBCT2X","remoteAddr":"","app":"PHP","message":"chmod(): Operation not permitted at \/srv\/www\/htdocs\/owncloud\/lib\/private\/Log\/Owncloud.php#114","level":3,"time":"2016-05-25T14:15:08+00:00","method":"--","url":"--","user":"admin"}
Testing with sqlite ...
No coverage
/home/vincent/opt/bin/phpunit --configuration phpunit-autotest.xml --log-junit autotest-results-sqlite.xml  
PHP Fatal error:  Uncaught exception 'Exception' with message 'Failed to connect to localhost port 8474: Connection refused' in /srv/www/htdocs/owncloud/apps/user_ldap/tests/Integration/ExceptionOnLostConnection.php:154
Stack trace:
#0 /srv/www/htdocs/owncloud/apps/user_ldap/tests/Integration/ExceptionOnLostConnection.php(100): OCA\User_LDAP\Tests\Integration\ExceptionOnLostConnection->checkCurlResult(Resource id #2489, false)
#1 /srv/www/htdocs/owncloud/apps/user_ldap/tests/Integration/ExceptionOnLostConnection.php(77): OCA\User_LDAP\Tests\Integration\ExceptionOnLostConnection->setUp()
#2 /srv/www/htdocs/owncloud/apps/user_ldap/tests/Integration/ExceptionOnLostConnection.php(193): OCA\User_LDAP\Tests\Integration\ExceptionOnLostConnection->__construct('http://localhos...', 'ldap', 'dc=owncloud,dc=...')
#3 /srv/www/htdocs/owncloud/tests/apps.php(20): require_once('/srv/www/htdocs...')
#4 /srv/www/htdocs/owncloud/tests/apps.php(18): loadDirectory('/srv/www/htdocs...')
#5 /srv/www/htdocs/owncloud/tests/apps.php(42): loadDirectory in /srv/www/htdocs/owncloud/apps/user_ldap/tests/Integration/ExceptionOnLostConnection.php on line 154
```

**Comment by SergioBertolinSG** [comment]
Works fine setting up openldap and active directory. 👍

**Comment by PVince81** [comment]
@SergioBertolinSG thanks a lot.

Now need to fix the unit test situation

**Comment by PVince81** [comment]
sqlite tests passed locally for me :+1:

**Pull request merged**
