### PR TITLE
Move \OCP\Console to PSR-4

### PR DESCRIPTION
**Pull request by rullzer**
CC: @nickvergessen @MorrisJobke @DeepDiver1975 @LukasReschke @PVince81

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
👍

**Comment by PVince81** [comment]
@rullzer rebase to kick Jenkins ? Definitely you seem to be quite unlucky

**Comment by nickvergessen** [comment]
No need to rebase the PSR-4 stuff really, if one unit test passed it's not a problem with class loading anymore and is save to merge, because either the class was found and loaded or it is not... there is no "dependency" to anything else.

**Comment by DeepDiver1975** [comment]
> No need to rebase the PSR-4 stuff really, if one unit test passed it's not a problem with class loading anymore and is save to merge, because either the class was found and loaded or it is not... there is no "dependency" to anything else.

yes - one successfull phpunit execution is enough

**Pull request merged**
