### PR TITLE
Remove wrongly backported test

### PR DESCRIPTION
**Pull request by MorrisJobke**
- backported with #22752 

cc @icewind1991 @PVince81 @LukasReschke @DeepDiver1975 

@karlitschek for this stable8.2 only backport.

Fixes https://github.com/owncloud/core/issues/22962

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:  makes sense

**Comment by MorrisJobke** [comment]
@cmonteroluque This hasn't any impact to the release because the test folders are cleaned anyway ;)

**Comment by DeepDiver1975** [comment]
````
PHP Fatal error:  Class 'OCA\Files_sharing\Tests\selF' not found in /ssd/jenkins/workspace/server-master-linux-php5.4-ci/database/sqlite/label/SLAVE/apps/files_sharing/tests/grouppropagationmanager.php on line 76

**Comment by icewind1991** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@cmonteroluque stable8.2 open for merges? THX

**Pull request merged**
