### PR TITLE
Use name of ICollection for exception message

### LINKED ISSUE #21230: Object of class OC\\Connector\\Sabre\\Directory could not be converted to string
```
{"reqId":"LrktWybwli\/kyKS3yogp","remoteAddr":"172.26.112.16","app":"PHP","message":"Object of class OC\\Connector\\Sabre\\Directory could not be converted to string at \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php#191","level":3,"time":"2015-12-11T13:33:31+00:00"}
```

Instead it should be something like `Could not copy directory PATH, target exists'.

bildschirmfoto 2015-12-16 um 14 15 19

*cough* @icewind1991 *cough* (please fix it - I don't know how to get a path out of an ICollection :see_no_evil: )

https://github.com/owncloud/core/commit/fe0de5fc10f61a7bb3173a04a986b145789b9160#diff-bad86217951709753766eabf0f82deacR62 ;)

This is the line on current master: 
https://github.com/owncloud/core/blob/aa6230e389b9756fc4cdb0e6b382281a762ddf74/apps/dav/lib/connector/sabre/objecttree.php#L193

Or @deepdiver1975 or @PVince81

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes #21230

cc @DeepDiver1975 @PVince81 @icewind1991

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Let me try to add a test.

**Comment by MorrisJobke** [comment]
Unit test added :)

**Comment by icewind1991** [comment]
:+1: looks good

**Comment by PVince81** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@icewind1991 @DeepDiver1975 @karlitschek I would like to backport this to stable8.1 and stable8.2

**Comment by karlitschek** [comment]
please backport! :+1:

**Comment by DeepDiver1975** [comment]
> @icewind1991 @DeepDiver1975 @karlitschek I would like to backport this to stable8.1 and stable8.2

open prs please

**Comment by MorrisJobke** [comment]
stable8.1 #21235 
stable8.2 #21234

**Comment by DeepDiver1975** [comment]
@MorrisJobke 

unit tests are failing on master


````
10:29:27 ....................................PHP Fatal error:  Class 'OCA\DAV\Connector\Sabre\Directory' not found in /ssd/jenkins/workspace/core-ci-linux/database/sqlite/label/SLAVE/tests/lib/connector/sabre/objecttree.php on line 306
10:29:27 PHP Stack trace:
10:29:27 PHP   1. {main}() /usr/local/bin/phpunit:0
10:29:27 PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:537
10:29:27 PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:105
10:29:27 PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:153
10:29:27 PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php:406
10:29:27 PHP   6. PHPUnit_Framework_TestSuite->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
10:29:27 PHP   7. PHPUnit_Framework_TestCase->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php:722
10:29:27 PHP   8. PHPUnit_Framework_TestResult->run() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:699
10:29:27 PHP   9. PHP_Invoker->invoke() phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php:607
10:29:27 PHP  10. call_user_func_array:{phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93}() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
10:29:27 PHP  11. PHPUnit_Framework_TestCase->runBare() phar:///usr/local/bin/phpunit/php-invoker/Invoker.php:93
10:29:27 PHP  12. PHPUnit_Framework_TestCase->runTest() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:743
10:29:27 PHP  13. ReflectionMethod->invokeArgs() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:866
10:29:27 PHP  14. Test\OC\Connector\Sabre\ObjectTree->testFailingMove() phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php:866

**Comment by MorrisJobke** [comment]
> unit tests are failing on master

What? But it worked in this branch.

**Comment by MorrisJobke** [comment]
Line 306 on master is not really the mock builder: https://github.com/owncloud/core/blob/89233cab8385740c11e566d7507f2e06371bef32/apps/dav/tests/unit/connector/sabre/objecttree.php#L306

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/issues/21339

**Pull request merged**
