### PR TITLE
UI tests creating users with various special char

### PR DESCRIPTION
**Pull request by individual-it**
## Description
some more UI tests to see if valid special char are working and if invalid char are correctly denied

## Motivation and Context
more tests === better

## How Has This Been Tested?
run tests in travis.
The UI tests will not pass in this PR because it comes form an other fork, but they all passed here: https://github.com/individual-it/owncloud-core/pull/58
Not doing a separate branch here because travis has currently a huge backlog

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by individual-it** [comment]
@jaggu4444 please sign the Contributor License Agreement by going to this [link](https://cla-assistant.io/owncloud/core?pullRequest=29931) and clicking at the bottom on "Sign in with Github to agree"

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
This needs to be cherry-picked into a branch in the real owncloud core so that SauceLabs will work.

**Comment by individual-it** [comment]
I would rather request @PVince81 to merge it as travis on owncloud has a huge backlog and is currently pretty slow.

**Comment by PVince81** [comment]
conflict

**Comment by phil-davis** [comment]
Backport stable10 #29953

**Pull request merged**
