### PR TITLE
fix/optimize preview cleanup query

### LINKED ISSUE #40800: PreviewCleanup query is incorrect
### Steps to reproduce
1. Delete 4 files with thumbnails from OwnCloud, deleting from trashbin as well

### Expected behaviour
Tell us what should happen

With old (v10.1) PreviewCleanup query, sql returns correct thumbnails to delete, albeit slowly:

```
+--------+-------+--------------------------------------+
| fileid | name  | user_id                              |
+--------+-------+--------------------------------------+
|  30689 | 30686 | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30693 | 26    | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30696 | 28    | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30699 | 27    | 5019585e-4aee-103d-9ced-f379c4734244 |
+--------+-------+--------------------------------------+
4 rows in set (1 min 57.177 sec)
``` 

### Actual behaviour
Tell us what happens instead

Current query returns extra rows.  This will lead to deleting thumbnails unnecessarily.
```
+--------+-------+--------------------------------------+
| fileid | name  | user_id                              |
+--------+-------+--------------------------------------+
|  30649 | 30589 | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30650 | 30594 | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30651 | 30591 | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30667 | 140   | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30668 | 208   | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30669 | 66    | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30671 | 141   | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30674 | 1174  | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30676 | 30666 | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30689 | 30686 | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30693 | 26    | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30696 | 28    | 5019585e-4aee-103d-9ced-f379c4734244 |
|  30699 | 27    | 5019585e-4aee-103d-9ced-f379c4734244 |
+--------+-------+--------------------------------------+
13 rows in set (0.135 sec)
``` 

### Server configuration
**Operating system**: Debian

**Web server:** Apache

**Database:** MariaDB

**PHP version:** PHP 7.4.3-4ubuntu2.18 

**ownCloud version:** 10.12.1.3

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** Docker (owncloud/server:10.12)

### PR DESCRIPTION
**Pull request by mtillberg**
## Description
Fix to PreviewCleanup query

## Related Issue
- Fixes #40800 

## Motivation and Context
Keeps the faster response time, returns the correct data, prevents unnecessary thumbnail deletes/recreations.

## How Has This Been Tested?
- test environment: Docker owncloud/server:10.12 (current version 10.12.1.3)
Updated lib/private/PreviewCleanup.php with new query
ran occ previews:cleanup
saw that only the correct thunbnails were deleted.
Test run against MariaDB 10.11.3

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [X] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [x] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Review by pako81 — COMMENTED** [review]
Manually tested against MariaDB and can indeed confirm only relevant thumbnails are removed. However, CI fails at https://drone.owncloud.com/owncloud/core/38529/30/8. Maybe special care has to be taken for the query when running it on Oracle DB.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/core/38533/20/8
```
There was 1 error:
1) Test\PreviewCleanupTest::test
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'select `thumb`.`fileid`, `thumb`.`name`, `user_id`
 from `oc_mounts`, `oc_filecache` `thumb` left join `oc_filecache` `file`  on `thumb`.`name` = cast(`file`.`fileid` as VARCHAR(24))
where `thumb`.`parent` in (select `fileid` from `oc_filecache` where `storage` in (select `numeric_id` from `oc_storages` where `id` like 'home::%' or `id` like 'object::user:%') and `path` = 'thumbnails')
  and `oc_mounts`.`storage_id` = `thumb`.`storage`
  and `file`.`fileid` is null
  and `thumb`.`fileid` > ?
  order by `user_id`, `thumb`.`fileid` limit 1000' with params [0]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VARCHAR(24))
where `thumb`.`parent` in (select `fileid` from `oc_filecache` wher' at line 2

/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:182
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:159
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:2226
/drone/src/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1313
/drone/src/lib/private/DB/Connection.php:191
/drone/src/lib/private/PreviewCleanup.php:97
/drone/src/lib/private/PreviewCleanup.php:43
/drone/src/tests/lib/PreviewCleanupTest.php:106
phpvfscomposer:///drone/src/lib/composer/phpunit/phpunit/phpunit:106
```

And locally I get:
```
$ php occ previews:cleanup

In AbstractMySQLDriver.php line 98:
                                                                                                                                                                    
  An exception occurred while executing 'select `thumb`.`fileid`, `thumb`.`name`, `user_id`                                                                         
   from `oc_mounts`, `oc_filecache` `thumb` left join `oc_filecache` `file`  on `thumb`.`name` = cast(`file`.`fileid` as VARCHAR(24))                               
  where `thumb`.`parent` in (select `fileid` from `oc_filecache` where `storage` in (select `numeric_id` from `oc_storages` where `id` like 'home::%' or `id` like  
   'object::user:%') and `path` = 'thumbnails')                                                                                                                     
    and `oc_mounts`.`storage_id` = `thumb`.`storage`                                                                                                                
    and `file`.`fileid` is null                                                                                                                                     
    and `thumb`.`fileid` > ?                                                                                                                                        
    order by `user_id`, `thumb`.`fileid` limit 1000' with params [0]:                                                                                               
                                                                                                                                                                    
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for  
   the right syntax to use near 'VARCHAR(24))                                                                                                                       
  where `thumb`.`parent` in (select `fileid` from `oc_filecache` wher' at line 2                                                                                    
                                                                                                                                                                    
In Exception.php line 18:
                                                                                                                                                                    
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for  
   the right syntax to use near 'VARCHAR(24))                                                                                                                       
  where `thumb`.`parent` in (select `fileid` from `oc_filecache` wher' at line 2                                                                                    
                                                                                                                                                                    
In PDOStatement.php line 117:
                                                                                                                                                                    
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for  
   the right syntax to use near 'VARCHAR(24))                                                                                                                       
  where `thumb`.`parent` in (select `fileid` from `oc_filecache` wher' at line 2                                                                                    

previews:cleanup [--output [OUTPUT]] [--all] [--] [<chunk_size>]

```

I am using mySQL - the unit tests on mySQL and the oldest mariaDB 10.2 are failing. They do not seem to like `VARCHAR`

**Comment by phil-davis** [comment]
Looks good. I have some acceptance test scenarios that fail on master and pass with this fixed code - good. I will put those in a separate PR (to avoid pushing to this branch).

@mtillberg you could squash the commits here - the code is pretty tidy now, so I don't think that we need the "development commit history".

**Comment by phil-davis** [comment]
I squashed and rebased. Anyone please review - maybe @jvillafanez 

This fixes/improves the cleanup of previews/thumbnails.

**Review by jvillafanez — APPROVED** [review]

**Pull request merged**
