### PR TITLE
Add is_dir check to getAllApps() function

### PR DESCRIPTION
**Pull request by ghost**
As requested by @Xenopathic in https://github.com/owncloud/core/issues/17400

### CODE REVIEW

**Comment by RealRancor** [comment]
cc @nougad

**Comment by MorrisJobke** [comment]
@owncloud-bot this is okay to test

**Comment by RealRancor** [comment]
Patch is by @nougad so no idea if i just can licence this by MIT?

**Comment by MorrisJobke** [comment]
> Patch is by @nougad so no idea if i just can licence this by MIT?

AFAIK this is so little code that there is no way to claim licence stuff ...but that is just what I remind.

**Comment by MorrisJobke** [comment]
cc @PVince81 @rullzer @Xenopathic @Henni

**Comment by RealRancor** [comment]
> AFAIK this is so little code that there is no way to claim licence stuff ...but that is just what I remind.

Even better :-)

**Comment by rullzer** [comment]
After extensive testing here is my :+1: ;)

**Comment by Xenopathic** [comment]
:+1: @nougad Could you just put a comment here stating the licensing of this change? Thanks.

**Comment by MorrisJobke** [comment]
Such small changes are not affected by copyright -> merge

**Comment by MorrisJobke** [comment]
Thanks @RealRancor @nougad

**Pull request merged**
