### PR TITLE
feat: in debug mode write sql queries to the log file + add query cou…

### PR DESCRIPTION
**Pull request by DeepDiver1975**
…nt asserts got unit testing

## Description
During development and debugging it is quite interesting to see all sql queries per request.
The log messages are written with the app context `core/sql` which allows to redirect them all into a dedicated log file via log conditions (see sample config).
Please also note the file extension `.jsonl` - see https://jsonlines.org/

Output after reformating in IDE:
```
{
  "reqId": "GUIbokakiGBry534CYD0",
  "level": 0,
  "time": "2023-11-10T11:42:08+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "alice",
  "app": "core\/sql",
  "method": "GET",
  "url": "\/index.php\/apps\/files\/?dir=\/&fileid=1929",
  "message": "SQL query log",
  "queries": [
    {
      "query": "SELECT * FROM \"oc_appconfig\"",
      "parameters": [],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT * FROM \"oc_accounts\" WHERE \"lower_user_id\" = :dcValue1",
      "parameters": {
        "dcValue1": "alice"
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"appid\", \"configkey\", \"configvalue\" FROM \"oc_preferences\" WHERE \"userid\" = ?",
      "parameters": [
        "alice"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"id\", \"uid\", \"login_name\", \"password\", \"name\", \"type\", \"token\", \"last_activity\", \"last_check\" FROM \"oc_authtoken\" WHERE \"token\" = :token",
      "parameters": {
        "token": "d839890fc821667f835ad213e3aa5b9f0ac01d44902f46e1e172ac59608f5514901bbff61619795ee4722dc202b423c5208997a37080aba314e4ec9fe3f23ebf"
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"uid\", \"password\" FROM \"oc_users\" WHERE LOWER(\"uid\") = LOWER(?)",
      "parameters": [
        "alice"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT * FROM \"oc_accounts\" WHERE \"lower_user_id\" = :dcValue1",
      "parameters": {
        "dcValue1": "alice"
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"uid\", \"displayname\" FROM \"oc_users\" WHERE LOWER(\"uid\") = LOWER(?)",
      "parameters": [
        "alice"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "UPDATE \"oc_authtoken\" SET \"last_check\" = ? WHERE \"id\" = ?",
      "parameters": {
        "1": 1699616528,
        "2": 23
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "UPDATE \"oc_authtoken\" SET \"last_check\" = ?,\"last_activity\" = ? WHERE \"id\" = ?",
      "parameters": {
        "1": 1699616528,
        "2": 1699616528,
        "3": 23
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"id\", \"uid\", \"login_name\", \"password\", \"name\", \"type\", \"token\", \"last_activity\", \"last_check\" FROM \"oc_authtoken\" WHERE \"token\" = :token",
      "parameters": {
        "token": "d839890fc821667f835ad213e3aa5b9f0ac01d44902f46e1e172ac59608f5514901bbff61619795ee4722dc202b423c5208997a37080aba314e4ec9fe3f23ebf"
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"id\", \"uid\", \"login_name\", \"password\", \"name\", \"type\", \"token\", \"last_activity\", \"last_check\" FROM \"oc_authtoken\" WHERE \"token\" = :token",
      "parameters": {
        "token": "d839890fc821667f835ad213e3aa5b9f0ac01d44902f46e1e172ac59608f5514901bbff61619795ee4722dc202b423c5208997a37080aba314e4ec9fe3f23ebf"
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"id\", \"uid\", \"login_name\", \"password\", \"name\", \"type\", \"token\", \"last_activity\", \"last_check\" FROM \"oc_authtoken\" WHERE \"token\" = :token",
      "parameters": {
        "token": "d839890fc821667f835ad213e3aa5b9f0ac01d44902f46e1e172ac59608f5514901bbff61619795ee4722dc202b423c5208997a37080aba314e4ec9fe3f23ebf"
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT * FROM \"oc_storages\" WHERE \"id\" = ?",
      "parameters": [
        "fd254efe6f858be769bc8b1c471d946c"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"fileid\" FROM \"oc_filecache\" WHERE \"storage\" = ? AND \"path_hash\" = ?",
      "parameters": [
        583,
        "d41d8cd98f00b204e9800998ecf8427e"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT * FROM \"oc_storages\" WHERE \"id\" = ?",
      "parameters": [
        "home::alice"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"fileid\" FROM \"oc_filecache\" WHERE \"storage\" = ? AND \"path_hash\" = ?",
      "parameters": [
        584,
        "d41d8cd98f00b204e9800998ecf8427e"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"storage_id\", \"root_id\", \"user_id\", \"mount_point\" FROM \"oc_mounts\" WHERE \"user_id\" = ? ORDER BY \"storage_id\" ASC",
      "parameters": {
        "1": "alice"
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"gid\" FROM \"oc_groups\" WHERE \"gid\" = :dcValue1",
      "parameters": {
        "dcValue1": "admin"
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"uid\" FROM \"oc_group_user\" WHERE (\"gid\" = :dcValue1) AND (\"uid\" = :dcValue2)",
      "parameters": {
        "dcValue1": "admin",
        "dcValue2": "alice"
      },
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"fileid\", \"storage\", \"path\", \"parent\", \"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\",\n\t\t\t\t\t   \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\"\n\t\t\t\tFROM \"oc_filecache\" WHERE \"storage\" = ? AND \"path_hash\" = ?",
      "parameters": [
        584,
        "45b963397aa40d4a0063e0d85e4fe7a1"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"fileid\", \"storage\", \"path\", \"parent\", \"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\",\n\t\t\t\t\t   \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\"\n\t\t\t\tFROM \"oc_filecache\" WHERE \"storage\" = ? AND \"path_hash\" = ?",
      "parameters": [
        584,
        "45b963397aa40d4a0063e0d85e4fe7a1"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    },
    {
      "query": "SELECT \"fileid\", \"storage\", \"path\", \"parent\", \"name\", \"mimetype\", \"mimepart\", \"size\", \"mtime\",\n\t\t\t\t\t   \"storage_mtime\", \"encrypted\", \"etag\", \"permissions\", \"checksum\"\n\t\t\t\tFROM \"oc_filecache\" WHERE \"storage\" = ? AND \"path_hash\" = ?",
      "parameters": [
        584,
        "45b963397aa40d4a0063e0d85e4fe7a1"
      ],
      "duration": 0,
      "start": 1699616528,
      "end": 1699616528
    }
  ]
}
```

Finally this PR introduces asserts for query count for unit testing:
https://github.com/owncloud/core/blob/1649787803d7572733023a767a355a5a4e77fb0b/tests/lib/AppConfigTest.php#L153-L162

## Motivation and Context
Make ownCloud even greater! :rofl: 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Database schema changes (next release will require increase of minor version instead of patch)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 
- [ ] Changelog item, see [TEMPLATE](https://github.com/owncloud/core/blob/master/changelog/TEMPLATE)

### CODE REVIEW

**Comment by IljaN** [comment]
Is it very hard to add another field where the query is displayed in executable format which can be copy and pasted?

**Comment by DeepDiver1975** [comment]
Due to Json escaping one anyhow needs to edit the query.....

**Comment by IljaN** [comment]
Is it possible to reference this with the request-id from owncloud.log?

**Comment by DeepDiver1975** [comment]
Should be part of the log entry. Will double check....

**Comment by IljaN** [comment]
Sorry, it is in your example at the top, nvm

**Comment by jvillafanez** [comment]
I'm worried that all the queries will be stored in memory until the end of the request. I don't know if it's possible to write them directly into the file right before or after the query is executed so we don't need to keep them in memory.
I guess it's fine for normal usage, because we don't expect too many queries, but I'm not sure about fixing issues. There could be already memory problems that I don't how this code will behave (it might not output any data), or even cause memory problems due to storing all the queries.

For the tests. I think it's better if we assume that a call to the `trackQueries` method is required to work with the other methods.
```
public function testWithQueries() {
  $this->trackQueries();
  // do your test run
  $this->assertNoQueriesExecuted();
}
```
We could try to warn the user if the `trackQueries` method hasn't been called in the test.

**Comment by DeepDiver1975** [comment]
> I'm worried that all the queries will be stored in memory until the end of the request. I don't know if it's possible to write them directly into the file right before or after the query is executed so we don't need to keep them in memory.
> I guess it's fine for normal usage, because we don't expect too many queries, but I'm not sure about fixing issues. There could be already memory problems that I don't how this code will behave (it might not output any data), or even cause memory problems due to storing all the queries.

It can indeed consume memory - but this is all enabled in debug mode only. I see this as a feature for us developers, support/consulting when analyzing performance topics and for system operators under special conditions.

**Comment by DeepDiver1975** [comment]
> For the tests. I think it's better if we assume that a call to the `trackQueries` method is required to work with the other methods.

I see your point. THX

**Comment by DeepDiver1975** [comment]
split up in #41090 and follow up #41093

**Pull request closed without merging**
